### ISSUE TITLE
文档不清楚问题（我的 url 里怎么有 # 号？要如何去掉？）

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#100]
https://pro.ant.design/docs/deploy#前端路由与服务端的结合
根据上面的文档没有办法去掉 url 中的 #，在React Router 4中，我改了router.js 中：
`import { BrowserRouter as Router, Route, Switch, Redirect } from 'dva/router'; `
就是将**Router**用**BrowserRouter**代替，使用这个方法可以去掉 url 中的 # @sorrycc

**Comment by afc163** [comment]
@nikogu 这块文档应该没有和 dva@2 的升级同步。

**Comment by kaoding** [comment]
第一次进入的时候是：http://localhost:8000/dashboard/analysis#/，#在后面，点击链接后没有问题了？这个还没有解决。

**Comment by mantou-kk** [comment]
import { browserHistory } from 'dva/router';
const app = dva({
  history: browserHistory,
});
这样做不起作用，#还是在；

下面这样做，刷新的时候无法访问，正常的dva不会，正常的react-router不会；
import { BrowserRouter as Router, Route, Switch, Redirect } from 'dva/router';

**Comment by nikogu** [comment]
站点还未发布，可先参看：

https://github.com/ant-design/ant-design-pro-site/blob/master/docs/deploy.md#在-ant-design-pro-中使用前端路由

**Comment by zhouguanglong** [comment]
你写的这个路径找不到，# 还是没去掉
