### ISSUE TITLE
当页面有多个checkboxGroup的时候，如何获取到所有选中的checkbox值

### ISSUE THREAD

**Issue by liushunqiu** [ant-design/ant-design-pro#1000]
![image](https://user-images.githubusercontent.com/13740807/36779154-095cc150-1caa-11e8-81e0-583226cf76c2.png)
各位好，我想请教一下，当我点击选中checkbox的时候，然后再点击取消，好像checkboxGroup的onChange没办法知道我当前把那个取消掉把？

**Comment by chenshuai2144** [comment]
理论上不会的。
如果有这个问题，去 antd 提一个吧。
一般都是你的代码问题
