### ISSUE TITLE
🐛 [BUG] 移除国际化后日期组件出现中英混合

### ISSUE THREAD

**Issue by xiaojinsb** [ant-design/ant-design-pro#10003]
### 🐛 bug 描述
运行 npm run i18n-remove 移除国际化后，时间组件出现中英混合

如果在 config.ts 中恢复因为 i18n-remove 被移除的代码，那么时间时间组件就会显示正常
locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本：4
- 浏览器环境：edge 103
- 开发环境：win10 21H2

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8086117/177950434-b70c698a-0049-4086-a0c2-9c8b5671c2d8.png)

**Comment by chenshuai2144** [comment]
```
// 默认语言为 en-US，如果你需要设置其他语言，推荐在入口文件全局设置 locale
import moment from 'moment';
import 'moment/locale/zh-cn';
import locale from 'antd/lib/locale/zh_CN';
```
