### ISSUE TITLE
🐛 [BUG]为什么当protable数据量小于50条，右下角分页就没有了，umijs3，umijs4，都有这原因

### ISSUE THREAD

**Issue by wanxiaoshengwanxiaosheng** [ant-design/ant-design-pro#10004]
### © 版本信息

- Ant Design Pro 版本: 
- umi 版本
@umi3，@umijs4

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/89174214/178086359-8ff0533a-faf8-4966-8837-9558d9a718b5.png)
![image](https://user-images.githubusercontent.com/89174214/178086561-3ac1c722-3de2-4ee3-bde5-91bb42f9f842.png)

**Comment by chenshuai2144** [comment]
antd 的新featrue。如果想要一直打开，可以配置props.


表格分页为何会出现 size 切换器？[#](https://ant.design/index-cn#%E8%A1%A8%E6%A0%BC%E5%88%86%E9%A1%B5%E4%B8%BA%E4%BD%95%E4%BC%9A%E5%87%BA%E7%8E%B0-size-%E5%88%87%E6%8D%A2%E5%99%A8%EF%BC%9F)

自 4.1.0 起，Pagination 在 total 大于 50 条时会默认显示 size 切换器以提升用户交互体验。如果你不需要该功能，可以通过设置 `showSizeChanger` 为 false 来关闭。
