### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by yelc66** [ant-design/ant-design-pro#10002]
### 🐛 bug 描述

在项目加入@ant-design/pro-components后protable工具栏的密度无法显示
![image](https://user-images.githubusercontent.com/48628500/177931138-873b1fc2-ba20-4478-87b9-928de3d1a1ad.png)
![image](https://user-images.githubusercontent.com/48628500/177931227-b5e36007-c3f8-4683-abf4-0051db133a5f.png)

### © 版本信息

- Ant Design Pro 版本: [V5.0.0]
- umi 版本 3.5.0.0
- 浏览器环境 103.0.5060.114 Google Chrome
- 开发环境 [e.g. mac OS] : win 10

**Comment by chenshuai2144** [comment]
好好写标题
