### ISSUE TITLE
有人遇到开发环境热更新动不动就崩溃的问题嘛

### ISSUE THREAD

**Issue by chengtong0410** [ant-design/ant-design-pro#10016]

**Comment by chenshuai2144** [comment]
搞个重现出来吧。热更新失败一般是文件大小写的问题。

**Comment by hst-Sunday** [comment]
我也遇到了, 自定义一个组件 然后在 ProForm 里使用这个自定义组件  然后在自定义组件里随便更改一些东西大概率会出现

**Comment by hst-Sunday** [comment]
ProForm 里使用 ProFormSelect 的 request 热更新就会卡死

**Comment by hst-Sunday** [comment]
config 里 注释掉 这个fastRefresh: {}  就好了
