### ISSUE TITLE
🧐[问题 | question] 当资源文件正在服务器上被客户使用的时候，我发布了一个新包。跳转页面资源文件404。

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#10012]
### 🧐 问题描述 | Problem description
当资源文件正在服务器上被客户使用的时候，我发布了一个新包。
新包的dist文件层级发生了变化。导致客户跳转页面  console报资源文件404。
但是重新刷新一下页面就好了。

我想询问一下 有没有什么好办法可以检测到资源文件404的方法。
检测到了以后我重新去走一遍刷新事件就可以解决问题。

### 🚑 其他信息 | Other information
![image](https://user-images.githubusercontent.com/45235142/178245758-7b44e72b-e1b9-4459-bd59-aa9fac794cd1.png)
OS:

Node：

浏览器 | browser：谷歌

**Comment by Asence** [comment]
因为我们公司上线时间都是开发完了就上  并且浏览器缓存文件的问题  导致客户在使用的时候前一秒钟都是好的  我们新版本上线以后就导致文件找不到了  客户也不会去刷新  而是直接跑来问我们是不是坏了。  
所以我想问下 怎么去解决这个问题

**Comment by minisola** [comment]
一般而言发布新版的时候旧版本文件都不会删除，做覆盖处理，这样旧版本的用户还可以再继续使用，直到刷新页面。

**Comment by Asence** [comment]
> 一般而言发布新版的时候旧版本文件都不会删除，做覆盖处理，这样旧版本的用户还可以再继续使用，直到刷新页面。

话虽如此   但是现在新版发布以后，跳转到其他页面的时候就找不到其他页面的文件的了(我改过新dist文件的层级，所以找不到了)。

**Comment by chenshuai2144** [comment]
一般都是通过两台服务器来实现的，分组发布。
如果只有一台最好停机一下，然后发布。虽然不可用 几秒，但是比404好一些

**Comment by Asence** [comment]
> 一般都是通过两台服务器来实现的，分组发布。 如果只有一台最好停机一下，然后发布。虽然不可用 几秒，但是比404好一些

我也是跟上面的人这么说的  但是他们觉得这种事情就是我个人能力的问题  因为这个事情我都被训了很多次了.....
所以我才想着有没有什么其他的办法去解决这个事情
