### ISSUE TITLE
🧐[问题 | v4.5.0 UserLayout ts报错信息]

### ISSUE THREAD

**Issue by 666-arch** [ant-design/ant-design-pro#10015]
### 🧐 问题描述 | Problem description

![image](https://user-images.githubusercontent.com/65932450/178489695-dacb22f5-7ea6-4318-a030-b8d2fad87a19.png)
是需要升级@type/script吗？有没有比较容易解决类似错误的部分，感觉挺多地方有这种类似错误的

**Comment by 666-arch** [comment]
> ### 🧐 问题描述 | Problem description
> ![image](https://user-images.githubusercontent.com/65932450/178489695-dacb22f5-7ea6-4318-a030-b8d2fad87a19.png) 是需要升级@type/script吗？有没有比较容易解决类似错误的部分，感觉挺多地方有这种类似错误的

![image](https://user-images.githubusercontent.com/65932450/178501951-18252dd5-02fa-4926-a3cc-5f6fa1490462.png)
还有权限的模板部分

**Comment by 666-arch** [comment]
想问下如果升级 @type/script要升级到对应的多少版本呢？ 目前antd-pro是4.5的
![image](https://user-images.githubusercontent.com/65932450/178502421-ea8b7059-f4d6-46f6-bd54-262b575aed9d.png)

**Comment by ohaTgxK9956562414460** [comment]
这个问题我也遇到了，应该是升级依赖导致的。

**Comment by chenshuai2144** [comment]
react 17 的锅，你可以锁定一下 @types/react  和  @types/react-dom 到 16 


如果有追求可以重写以下类型
