### ISSUE TITLE
🧐[老项目从umi2升级umi3运行报错 | question]

### ISSUE THREAD

**Issue by BryanYbj** [ant-design/ant-design-pro#10019]
### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/52267044/178916261-fa504c8a-30f6-43e0-917b-8896caac07a9.png)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
<img width="116" alt="image" src="https://user-images.githubusercontent.com/8186664/179451949-8527747d-0b81-497a-b736-ab739d0944d5.png">

这个库已经没了


https://github.com/remix-run/react-router/issues/8139

官方看起来也不打算加回来
