### ISSUE TITLE
🧐[问题 | question] umi4使用initialStateConfig会报错

### ISSUE THREAD

**Issue by mwj610** [ant-design/ant-design-pro#10017]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
initialStateConfig 是什么东西？

**Comment by mwj610** [comment]
> 

![image](https://user-images.githubusercontent.com/52907799/179453742-2c2aa6f6-4941-49f7-9571-848394d1c523.png)
ant-design-pro 好像也没有这个了

**Comment by chenshuai2144** [comment]
initialStateConfig  新版本没有了，不需要了

**Comment by zhangnan24** [comment]
initialStateConfig这个loading的问题，只听到你们说很鸡肋，那有明确的替代方案吗？为什么这么多人提？你们有考虑过实际的业务场景吗？首页进来的时候好几秒白屏体验很差知道吗？

**Comment by zhangnan24** [comment]
v5弄得这么不景气，阿里没人了？文档各种缺，各种乱设计，自以为配置大于一切，v4那些高手的思想都没交接给你们？这样敷衍广大开发者

**Comment by gitlwz** [comment]
不明白鸡肋在哪？替代方案也没有

**Comment by zhangnan24** [comment]
你好，你的邮件我已经收到，我将在阅读后尽快给你回复，谢谢来件∩_∩

**Comment by merabtenei** [comment]
It's sad there's no way to display a loading page when initialState is fetching data.
