### ISSUE TITLE
🧐[问题 | question] 升级到umi4, 在document.ejs引入百度地图的script不起作用

### ISSUE THREAD

**Issue by kddloong** [ant-design/ant-design-pro#10010]
### 🧐 问题描述 | Problem description

pro-cli生成的umi4新项目, 在document.ejs引入百度地图的script不起作用. 试过放在head里面, 不起作用

### 🚑 其他信息 | Other information

![图片](https://user-images.githubusercontent.com/47130020/178183554-4216eb58-eea4-4a74-bf88-dff141116e9c.png)

OS: Win10

Node：16.13.1

浏览器 | browser：chrome

**Comment by chenshuai2144** [comment]
注意一下要先等 百度的js加载成功，然后再去读取。

**Comment by kddloong** [comment]
配置了headScripts可以加载了
