### ISSUE TITLE
🐛 [BUG]ie浏览器访问不了吗？怎么兼容ie

### ISSUE THREAD

**Issue by littleGitYxr** [ant-design/ant-design-pro#10011]
🐛 [BUG]ie浏览器访问不了吗？怎么兼容ie

**Comment by xiaojinsb** [comment]
config\config.ts 兼容性设置
targets: {
    ie: 11,
  },

**Comment by chenshuai2144** [comment]
https://v3.umijs.org/docs/faq#ie报错和压缩问题解决思路
