### ISSUE TITLE
🧐[问题 | v4.5.0 BasicLayout ts报错]

### ISSUE THREAD

**Issue by 666-arch** [ant-design/ant-design-pro#10013]
### 🧐 问题描述 | Problem description

![image](https://user-images.githubusercontent.com/65932450/178386654-540b68cf-bfee-4b38-98f6-bf8f9df24378.png)

**Comment by chenshuai2144** [comment]
升级下你的 @types/react 和 @types/react-dom

**Comment by 666-arch** [comment]
> 

感谢你的回答

**Comment by 666-arch** [comment]
> 升级下你的 @types/react 和 @types/react-dom
> 
> 或者偷懒一下 `<>{defaultDom}</>`

感谢你的回复
