### ISSUE TITLE
git commit 

### ISSUE THREAD

**Issue by taofish** [ant-design/ant-design-pro#1002]
ant-design-pro脚手架生成的项目怎么关闭Git commit的 eslint 代码风格检查

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/69cb402f9d4ca72933eafbc9294a860fb1d62991/package.json#L7
看这里

**Comment by taofish** [comment]
"npm run lint-staged"这个命令是手动执行检测，我是想在“git commit 的时候怎么关闭掉检测”， @chenshuai2144 #

**Comment by zichencode** [comment]
可以在 .eslintignore 忽略掉相关文件夹
