### ISSUE TITLE
🐛 [BUG] umi4 navTheme是“dark”，header是白的

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design-pro#10028]
### 📷 复现步骤 | Recurrence steps
npm i @ant-design/pro-cli -g
pro create myapp

修改 `navTheme: 'dark'` `layout: 'mix'` header menu是白色的
### 🏞 期望结果 | Expected results

header menu是深色的

### 💻 复现代码 | Recurrence code

npm i @ant-design/pro-cli -g
pro create myapp
安装后就是

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本： 4
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by MachiBarton** [comment]
同问，umi4 下面 navTheme:dark 无效

**Comment by jianjian-commits** [comment]
同问，并且layout:'side'模式下，头部变到菜单下面去了。。。

**Comment by chenshuai2144** [comment]
新版本layout 已经没有黑色了。 ts 和 发布稿中都有体现

在side 模式下也没有header了。

**Comment by jianjian-commits** [comment]
这个变动也太那啥了吧～～～

**Comment by darkfiredarkhalo** [comment]
那倒是在文档里说明下哈, 预览的网站是不是也该做个变动

**Comment by kerwin-ly** [comment]
我也遇到了这个问题。根据官网的提示，去[pro站点](https://preview.pro.ant.design/dashboard/analysis/?primaryColor=daybreak)拷贝了defaultSettings配置。但发现布局直接错乱了...

**Comment by kerwin-ly** [comment]
> 新版本layout 已经没有黑色了。 ts 和 发布稿中都有体现
> 
> 在side 模式下也没有header了。

建议更新下[And Design Pro](https://pro.ant.design/zh-CN/docs/layout)文档
