### ISSUE TITLE
👑 [需求] document.ejs 要删除吗？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#10024]
根据 umi 4 是不需要 [document.ejs](https://github.com/ant-design/ant-design-pro/blob/master/src/pages/document.ejs)

**Comment by echoyl** [comment]
document.ejs 失效后  刷新页面的loading怎么设置？ 现在刷新就是空白页面

**Comment by chenshuai2144** [comment]
@[kaoding](https://github.com/kaoding) 来看pr搞下？

**Comment by chenshuai2144** [comment]
> document.ejs 失效后 刷新页面的loading怎么设置？ 现在刷新就是空白页面

问了umi那边要写插件了，默认是不能搞的

**Comment by kaoding** [comment]
按 umi 4 来使用，直接删除应该就可以了吧，直接删除会有什么问题就不太清楚了。
