### ISSUE TITLE
更新到umi@4后 layout的配置不生效 样式有点错乱了🧐[问题 | question]

### ISSUE THREAD

**Issue by echoyl** [ant-design/ant-design-pro#10021]
### 🧐 问题描述 | Problem description

![1657786237403](https://user-images.githubusercontent.com/21699984/178934556-0d3773a2-3e07-400f-a2a0-b35a8efd14e0.jpg)
如图所示 
layout版本
"name": "@ant-design/pro-layout",
"version": "7.0.1-beta.28",

求帮助下

**Comment by chenshuai2144** [comment]
这是新版本的样式，你可以回滚到6.0 的版本
