### ISSUE TITLE
🧐[问题 | 这种ts报错怎么从根源解决？？？其他页面也会有！！！求助！！！]

### ISSUE THREAD

**Issue by 666-arch** [ant-design/ant-design-pro#10029]
![image](https://user-images.githubusercontent.com/65932450/179194498-29ce477c-424c-499f-b642-f84409ad6c69.png)

**Comment by chenshuai2144** [comment]
useState 的时候定义一下 类型

`const [inputValue,setInputValue] = useState<string>('')`
