### ISSUE TITLE
🐛 [BUG]antdpro打包出现控制台输出报错，不同antd版本报错都不一样，但是dist打包出来是正常的

### ISSUE THREAD

**Issue by qwe5117022** [ant-design/ant-design-pro#10020]
### 🐛 bug 描述

antd打包的时候，一到less render start 就开始爆各种乱码，感觉怀疑是procard是单独引入的问题，或者是antd版本适配的问题，
在末尾会附上package.json

### 📷 复现步骤 | Recurrence steps
一、第一种情况，antd版本@4.14 
1.第一个问题就是dev启动的时候，antdpro的prolayout无法看见左侧菜单，菜单完全不显示了。但是手动地址栏输入路由是可以访问的。
2.第二个问题是build的时候，less render start开始的时候，控制台一直在输出绿色的错误（如下图），并且一直不会停止（这里与第二种情况不一样），仔细看的话，能看到less render end，但是还是一直在输出。
![image](https://user-images.githubusercontent.com/93125879/178923547-62fe0eeb-04ac-4ecf-9e3f-1c46dd8014c7.png)
------------------------

二、第二种情况，antd版本@4.18（和上面版本有所不一样）

1.第一个问题，dev启动的时候，没有出现任何的错误了，菜单也能够显示。
2.第二个问题，build打包的时候，less render start的时候，会爆出白色的错误（如下图），但是less render end之后就会停止输出，并不会想第一种情况，一直不听输入绿色错误。

![image](https://user-images.githubusercontent.com/93125879/179127299-3985dbf4-2f96-4dba-9f49-74da0e5507ed.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.55.0",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.3.7",
    "@antv/l7-maps": "^2.3.7",
    "@antv/l7-react": "^2.1.9",
    "@types/js-md5": "^0.4.3",
    "@types/lodash.debounce": "^4.0.6",
    "@types/qrcode.react": "^1.0.2",
    "@umijs/route-utils": "^1.0.36",
    "ahooks": "^2.0.0",
    "antd": "^4.14.0",.

![image](https://user-images.githubusercontent.com/93125879/178924950-0e03a005-dd26-4d81-b060-cee5db737086.png)

**Comment by chenshuai2144** [comment]
antd merge less 这个东西很久没维护了，想办法自己处理一下
