### ISSUE TITLE
🧐[问题 | question] favicon.ico在配置publicPath之后，打包路径不正确

### ISSUE THREAD

**Issue by LydiaAgute** [ant-design/ant-design-pro#10027]
### 🧐 问题描述 | Problem description
6.0.0 beta1 版本项目，配置publicPath之后， favicon.ico 打包路径不正确

6.0.0 beta1 版本项目，配置publicPath之后， favicon.ico 路径不正确，没有正确拼接publicPath。document.ejs文件好像已经无效了（似乎是umi4的改动？）
### 🚑 其他信息 | Other information

OS: windows11

Node：18.6.0

浏览器 | browser：

**Comment by xiaohuoni** [comment]
文档遗漏，已填加 https://github.com/umijs/umi/pull/8583

**Comment by GodBlessedSakura** [comment]
同样的问题：
我的项目在nginx上没有部署到根目录，需要用publicPath指定加载 js, css的路径。而publicPath配置对favicon是不生效的，在umi v3中可以通过配置config.js里favicon这个key手动指定目录。现在v4里没有这个key了，默认取src下的favicon，且生成的html模板里用的是"/favicon.ico"，这样的话部署到服务器会取根目录找favicon.ico就不对了。
