### ISSUE TITLE
官网说 DrawerForm 使用trigger ，无需维护 visible 状态， 但我提交时想关闭抽屉，应该怎么做呢？ 🧐[问题 | question]

### ISSUE THREAD

**Issue by erichow** [ant-design/ant-design-pro#10034]
### 🧐 问题描述 | Problem description

官网说 DrawerForm 使用trigger ，无需维护 visible 状态， 但我提交时想关闭抽屉，应该怎么做呢？

现在只能点”关闭“按钮 或 叉叉关闭。 还是要用到visible属性自己去控制，感觉trigger很鸡肋啊，还是我的使用“姿势”有问题？？

**Comment by WuJiY** [comment]
楼上正解
