### ISSUE TITLE
🧐[问题 | question] access配置 这个在哪里配置呢？

### ISSUE THREAD

**Issue by wsx0214** [ant-design/ant-design-pro#10039]
### 🧐 问题描述 | Problem description

想修改为没有就表示没有访问权限，官方文档有个配置说明，这个在哪个文件里面配置呢？

默认逻辑是没有写明权限表示有访问权限，如果要修改为没有写明权限表示没有访问权限，请开启它

`export default {
  access: {
    strictMode: true,
  },
}`

**Comment by chenshuai2144** [comment]
在 config/config.ts 中配置 

`access: { strictMode: true, }, `


具体代码在这里

https://github.com/ant-design/ant-design-pro/blob/c77820812e215bdab149f5aae529f615790c33df/config/config.ts
```

  /**
   * @name 权限插件
   * @description 基于 initialState 的权限插件，必须先打开 initialState
   * @doc https://umijs.org/docs/max/access
   */
  access: {},
```

**Comment by wsx0214** [comment]
谢谢
