### ISSUE TITLE
🧐[问题 | 图片上传的时候为什么没有拿到服务端返回的response？？？？？]在线等 急

### ISSUE THREAD

**Issue by 666-arch** [ant-design/ant-design-pro#10035]
接口上传返回的是正常的200 也可以拿到response 但是 upload的onChange回调获取出来的数据没有response字段
![image](https://user-images.githubusercontent.com/65932450/179653130-be31bf24-7316-498b-89e1-426bad026884.png)
![image](https://user-images.githubusercontent.com/65932450/179653254-bd5f3fee-ce57-445c-971c-fe9e39f5e688.png)
![image](https://user-images.githubusercontent.com/65932450/179653272-76105470-1a95-44f4-bfcb-2189ac88aa23.png)

**Comment by chenshuai2144** [comment]
response 去 action 里面自己处理以下，这个是你的网络请求库处理的
