### ISSUE TITLE
👑 [需求]RequestOptionsType的value属性希望能够增加对boolean类型的支持

### ISSUE THREAD

**Issue by alen256** [ant-design/ant-design-pro#10031]
### 🥰 需求描述 | Requirements description

RequestOptionsType的value属性希望能够增加对boolean类型的支持

### 🧐 解决方案 | Solution

export declare type RequestOptionsType = {
    label?: React.ReactNode;
    value?: React.ReactText | boolean;
    /** 渲染的节点类型 */
    optionType?: 'optGroup' | 'option';
    options?: Omit<RequestOptionsType, 'children' | 'optionType'>[];
    [key: string]: any;
};

**Comment by chenshuai2144** [comment]
boolean 用 Switch 吧。或者用 transform 转化一下
