### ISSUE TITLE
👑 [需求]实现ant design pro 文档预览，如pdf,world,excel，png等

### ISSUE THREAD

**Issue by buxinren** [ant-design/ant-design-pro#10032]
### 🥰 需求描述 | Requirements description

使用 react-file-viewer 实现ant design pro 文档预览，如pdf,world,excel，png等。
有没有哪位大佬使用上述插件实现过，我这面报错
![image](https://user-images.githubusercontent.com/53209455/179356809-d6080c6c-32e4-4f47-b6f5-e475ad46a42d.png)

> import { Button } from 'antd';
import React from 'react';
//react文件预览支持docx，xlsx
import FileViewer from 'react-file-viewer';
//react预览pdf文件插件
import PDF from 'react-pdf-js';
import styles from './styles.less';
import xiangmu from '@/assets/DocumentSharing/项目建议书.docx';
import { PageContainer } from '@ant-design/pro-layout';

const index = () => {
  //const w = require('../../assets/DocumentSharing/项目建议书.docx');
  const type = 'docx';

  return (
    <PageContainer>
      <FileViewer
        fileType={type} //文件类型
        //filePath="../../assets/DocumentSharing/项目建议书.docx" //文件地址（后台给返的二进制流也可以）
        filePath={xiangmu}
        //onError={this.onError.bind(this)} //函数[可选]：当文件查看器在获取或呈现请求的资源时发生错误时将调用的函数。在这里可以传递日志记录实用程序的回调。
        errorComponent={console.log('出现错误')} //[可选]：发生错误时呈现的组件，而不是react-file-viewer随附的默认错误组件。
        unsupportedComponent={console.log('不支持')} //[可选]：在不支持文件格式的情况下呈现的组件。
      />
    </PageContainer>
  );
};

export default index;

**Comment by chenshuai2144** [comment]
阿里云可以买到这个服务的，这不是前端能单独做到的事情

**Comment by pkaq** [comment]
[kkFileView](https://github.com/kekingcn/kkFileView) 了解一下？

**Comment by wangxing0204** [comment]
我之前也想用这个,安装失败,现在统一做的处理是将他们转为pdf 然后进行预览

**Comment by eternallycyf** [comment]
别用了吧 几年不维护了。那个word excel基本样式全乱掉。
- word 预览有个npm包挺好用的 具体可以参考我的 
- 遇到过一个小问题 它在旧版本 chrome 60 需要写几号 global this 的兼容代码
 https://github.com/eternallycyf/Antd-CustomComponent/blob/main/src/components/FileViewer/FileView.tsx
