### ISSUE TITLE
如何修改localhost为电脑ip

### ISSUE THREAD

**Issue by anghuang** [ant-design/ant-design-pro#1003]
如何修改localhost为192.168....，工具里有参数可以设置么

**Comment by yesmeck** [comment]
`HOST`

https://github.com/sorrycc/roadhog#environment-variables

**Comment by xiaodin1** [comment]
> 如何修改localhost为192.168....，工具里有参数可以设置么

参考：umijs/umi#3842

方法：
HOST=0.0.0.0 npm start
or
HOST=0.0.0.0 yarn start
