### ISSUE TITLE
🧐[问题 | question] 为什么我无法修改内容的字体颜色

### ISSUE THREAD

**Issue by wyd1520866381** [ant-design/ant-design-pro#10044]
### 💻 示例代码 | Sample code

 <ProCard ghost style={{ height: "12vh", color: "#000"}}>
 GamePlay </ProCard>

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/64176197/179876232-4c1e7d82-587c-4c9c-948b-a25abf9d7b5b.png)

OS:

Node：

浏览器 | browser：

**Comment by wyd1520866381** [comment]
在暗色风格的情况下无法修改，切换成默认可以修改
![image](https://user-images.githubusercontent.com/64176197/179878047-b7a99238-3958-40c5-8179-7b9f0da186ea.png)

**Comment by chenshuai2144** [comment]
先去了解下 css 和 react 把，这个问题简单到我不知道怎么回答。
