### ISSUE TITLE
🧐[问题 | question]如何修改默认样式之后兼容明暗模式

### ISSUE THREAD

**Issue by xiahller** [ant-design/ant-design-pro#10045]
### 🧐 问题描述 | Problem description
如何修改默认样式之后兼容明暗模式

想用antdpro自带的组件修改一下样式之后，再兼容明暗模式

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
https://ant.design/docs/react/customize-theme-cn#Ant-Design-%E7%9A%84%E6%A0%B7%E5%BC%8F%E5%8F%98%E9%87%8F



可以使用 antd 的 less 变量来设置颜色，不要用自定义的就可以兼容了
