### ISSUE TITLE
🧐[问题 | question] getInitialState 刷新页面重复执行

### ISSUE THREAD

**Issue by imoxuan** [ant-design/ant-design-pro#10042]
### 🧐 问题描述 | Problem description

我想初始化一些全局数据，必须放在 getInitialState 中。像默认项目的获取用户信息，登录之后，跳转到任意路由之后，只要F5刷新页面，就会又执行一遍。能限制只执行一次吗？

### 💻 示例代码 | Sample code

export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: LoginAPI.CurrentUser;
  loading?: boolean;
  fetchUserInfo?: () => Promise<LoginAPI.CurrentUser | undefined>;
}> {
  **_console.log('执行initialState')_**
  const fetchUserInfo = async () => {
    try {
      const msg = await queryCurrentUser();
      return msg.data;
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };

  // 如果不是登录页面，执行
  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: defaultSettings,
    };
  }
  return {
    fetchUserInfo,
    settings: defaultSettings,
  };
}
依赖：

"@ant-design/pro-layout": "6.38.12",
"@umijs/max": "4.0.7",

**Comment by chenshuai2144** [comment]
每次刷新对于前端来说相当于重启
