### ISSUE TITLE
Official website error

### ISSUE THREAD

**Issue by tgdn** [ant-design/ant-design-pro#1004]
On Chrome, white page and console output below:

    progress?id=mvWMRFfrVJ0mJ6U1j-_-O3-X_OUOcOhbpl78HuU4hWU,:1

    Uncaught SyntaxError: Unexpected token <

**Comment by chenshuai2144** [comment]
版本？ 环境？

**Comment by tgdn** [comment]
Visit https://pro.ant.design/ on Chrome and open the Console

**Comment by chenshuai2144** [comment]
Perhaps the reason google,
Try use vpn
