### ISSUE TITLE
👑 [需求]全局 websocket 与后端实时数据交互

### ISSUE THREAD

**Issue by imoxuan** [ant-design/ant-design-pro#10046]
### 🥰 需求描述 | Requirements description
 ant design pro 做前端展示，使用token和后端做身份验证。

但是部分页面的数据需要是实时的。这里想到要用 websocket来接收后端实时数据。

问题：

1. 怎么全局设置websocket？在需要的页面监听数据变化？

2.怎么保证websocket始终是保持连接的？如果因为网络波动断开，可以自动重连。

指导下思路或者有参考的方案或者文章，十分感谢。

**Comment by chenshuai2144** [comment]
这个你问错地方了。去掘金 知乎之类的地方试试把
