### ISSUE TITLE
🧐[问题 | question] 使用默认布局时，菜单的样式如何自定义

### ISSUE THREAD

**Issue by wyd1520866381** [ant-design/ant-design-pro#10043]
### 🧐 问题描述 | Problem description

想要修改菜单的字体，字体颜色，icon颜色等

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
不建议玩这种花活。如果想要一个完全不同的菜单 建议关掉默认的，只用 antd 的基础组件自己搭建
