### ISSUE TITLE
使用ant design pro构建项目后台不报错但是页面报错是什么原因Use ant design pro to build the project，but background is without error and the page has errors . What is the reason for this?

### ISSUE THREAD

**Issue by Mu-99** [ant-design/ant-design-pro#1005]

**Comment by Mu-99** [comment]
![1](https://user-images.githubusercontent.com/36875648/36782919-6d41c46c-1cb5-11e8-96cd-2490371fe695.PNG)

**Comment by chenshuai2144** [comment]
router 配置错了吧。
贴一下你的代码。

**Comment by Mu-99** [comment]
初次使用ant design pro项目，这种报错方式暂时不清楚，与react项目的后台报错和页面报错不同。但是步骤按照官网说法进行，问题出在哪里呢？

**Comment by Mu-99** [comment]
****在common\router.js文件
'/new': {
      component: dynamicWrapper(app, ['monitor'], () => import('../layouts/BasicLayout')),
    },
    '/new/page1': {
      component: dynamicWrapper(app, ['monitor'], () => import('../routes/New/Page1')),
    },
    '/new/page2': {
      component: dynamicWrapper(app, ['monitor'], () => import('../routes/New/Page2')),
    },
****src\router.js
<Router history={history}>
      <Switch>
        <Route path="/new" render={props => <BasicLayout {...props} />} />
        <Route path="/user" render={props => <UserLayout {...props} />} />
        <Route path="/" render={props => <BasicLayout {...props} />} />
      </Switch>
    </Router>

**Comment by chenshuai2144** [comment]
```
<ConnectedRouter history={history}>
        <Switch>
          <Route
            path="/user"
            component={UserLayout}
          />
          <AuthorizedRoute
            path="/"
            render={props => <BasicLayout {...props} />}
            authority={['admin', 'user']}
            redirectPath="/user/login"
          />
        </Switch>
      </ConnectedRouter>
```
需要这样写

**Comment by Mu-99** [comment]
这不是原始的写法吗？在官方文档的路由和菜单下的新建布局模板中不是让在在根路由中增加这组新模板：
// src/router.js
<Router history={history}>
  <Switch>
    <Route path="/new" render={props => <NewLayout {...props} />} />
    <Route path="/user" render={props => <UserLayout {...props} />} />
    <Route path="/" render={props => <BasicLayout {...props} />} />
  </Switch>
</Router>

**Comment by chenshuai2144** [comment]
新版react-router 需要Switch

**Comment by Mu-99** [comment]
不好意思，官网和操作就是加了Switch而报错
// src/router.js
<Router history={history}>
  <Switch>
    <Route path="/new" render={props => <NewLayout {...props} />} />
    <Route path="/user" render={props => <UserLayout {...props} />} />
    <Route path="/" render={props => <BasicLayout {...props} />} />
  </Switch>
</Router>

**Comment by Mu-99** [comment]
> <Router history={history}>
      <Switch>
        <Route path="/new" render={props => <BasicLayout {...props} />} />
        <Route path="/user" render={props => <UserLayout {...props} />} />
        <Route path="/" render={props => <BasicLayout {...props} />} />
      </Switch>
    </Router>
