### ISSUE TITLE
DragSortTable的表格数据接口获取的，拖拽出现异常🐛 [BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#10051]
### 🐛 bug 描述
使用DragSortTable的request属性使用接口获取表格数据， 不是用datasource, 发现拖拽出现异常，代码如图
![image](https://user-images.githubusercontent.com/20655248/180118471-ccaa269a-a15f-4b12-ad72-8bb881c0c82e.png)
![image](https://user-images.githubusercontent.com/20655248/180118547-d8118fc7-e67e-4565-aa25-61cb777e021a.png)
![image](https://user-images.githubusercontent.com/20655248/180118757-bacba658-5fd3-49e6-a201-2d759365bb84.png)

### © 版本信息

- ProComponents 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
```
import { useRefFunction } from '@ant-design/pro-utils';

  const onSubmit = useRefFunction(() => {
    const from = formArrayRef.current[step];
    from.current?.submit();
  });
```

useRefFunction 包裹下你的方法，防止闭包了就好

**Comment by lovehebe330** [comment]
> ```
> import { useRefFunction } from '@ant-design/pro-utils';
> 
>   const onSubmit = useRefFunction(() => {
>     const from = formArrayRef.current[step];
>     from.current?.submit();
>   });
> ```
> 
> useRefFunction 包裹下你的方法，防止闭包了就好，同时你要注意一下你的key不要重复掉

这个formArrayRef是DragSortTable的actionRef属性吗，
![image](https://user-images.githubusercontent.com/20655248/180153131-0cfb8885-bbf6-4b63-932a-a938219b4ab7.png)
这样写依然有问题 主要觉得request请求数据没触发onDragSortEnd方法
