### ISSUE TITLE
动态菜单问题

### ISSUE THREAD

**Issue by zhanchengkun** [ant-design/ant-design-pro#10059]
https://pro.ant.design/zh-CN/docs/advanced-menu
 app.tsx

 下改动:
 
 menu: {
      request:  async (p, defaultMenuData) => {
        const menu = await request('/menu');
        // menu=[{  "path": "/test",       "name": "test",    "icon": "smile",   "component": "./test"  }]
        // menu=[{  "path": "/test",       "name": "test",    "icon": "\<SmileOutlined /\>",   "component": "./test"  }]        
        return menu ;
           },
    },
    
    此时 请求数据作为JSON，  数据中的 icon 识别为字符串， 加载异常。
    求解
    
数据为后台 接口配置JSON，不是配置ReactNode问题。

**Comment by ngwszsd** [comment]
+ 你传的字符串 "<SmileOutlined />"肯定显示字符串了  你传<SmileOutlined /> ReactNode啊 如果报错是因为你的文件名是ts 这是tsx的写法

**Comment by zhanchengkun** [comment]
> * 你传的字符串 ""e 肯定显示字符串了  你传 ReactNode啊   重写你获取的data 把字符串换成ReactNode 如果报错是因为你的文件名是ts 这是tsx的写法


返回值 为 交互接口返回值，JSON数据。

**Comment by ngwszsd** [comment]
> 返回值 为 交互接口返回值，JSON数据。

你map循环一下重写icon字段呀

**Comment by zhanchengkun** [comment]
> > 返回值 为 交互接口返回值，JSON数据。
> 
> 你暂存一份data 然后map循环一下重写icon字段 再重新set值呀

有没有通过配置iconfont  字符串 匹配的？不做二次加工的方式

**Comment by ngwszsd** [comment]
> 有没有通过配置iconfont 字符串 匹配的？不做二次加工的方式

大哥这是jsx  string 和 ReactNode不是一种类型  后端是返回不了jsx的 map一下很难吗

**Comment by zhanchengkun** [comment]
> > 有没有通过配置iconfont 字符串 匹配的？不做二次加工的方式
> 
> 大哥这是jsx string 和 ReactNode不是一种类型 后端是返回不了jsx的 map一下很难吗

嘘……不是难不难的问题，不想2次处理。 都是配置问题 我问有没有 配置能行！

**Comment by zhanchengkun** [comment]
配上iconfont 已实现！

**Comment by LaoHeILY** [comment]
怎么做的呀？

**Comment by zhanchengkun** [comment]
### 内置的menuItemRender 函数第一个参数 能拿到 菜单项对象 ；然后进行 逻辑处理

menuItemRender: (menuItemProps, defaultDom) => {
const icon = getIcon(menuItemProps.icon);
return (<Link>{icon}{menuItemProps.name}</Link>)
}
