### ISSUE TITLE
🧐[问题 | question]在app.tsx中配置菜单项的情况下，如何实现搜索菜单功能

### ISSUE THREAD

**Issue by xiahller** [ant-design/ant-design-pro#10053]
### 🧐 问题描述 | Problem description
在app.tsx中配置菜单项的情况下，如何实现搜索菜单功能，

prolayout官网是在一个tsx文件中useState一个keyword然后再用postMenuData。但在app.tsx的layout是直接配置的，如何去实现菜单搜索功能呢
### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/55370123/180125566-7407bb51-6638-4ecc-9f76-9c93abc6235b.png)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
把值存到 initialvalues 里面


```tsx
// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    menuDataRender: (menuData) => {
      return menuData.filter(initialState.keyWords);
    },
// 只是个示例
    onChange: () => {
      setInitialState((initialState) => {
        return {
          ...initialState,
          keyWords: 'change',
        };
      });
    },
  };
};
```

**Comment by chenshuai2144** [comment]
把值存到 initialvalues 里面


```tsx
// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    menuDataRender: (menuData) => {
      return menuData.filter(initialState.keyWords);
    },
// 只是个示例
    onChange: () => {
      setInitialState((initialState) => {
        return {
          ...initialState,
          keyWords: 'change',
        };
      });
    },
  };
};
```

**Comment by xiahller** [comment]
> 把值存到 initialvalues 里面
> 
> ```tsx
> // ProLayout 支持的api https://procomponents.ant.design/components/layout
> export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
>   return {
>     menuDataRender: (menuData) => {
>       return menuData.filter(initialState.keyWords);
>     },
> // 只是个示例
>     onChange: () => {
>       setInitialState((initialState) => {
>         return {
>           ...initialState,
>           keyWords: 'change',
>         };
>       });
>     },
>   };
> };
> ```

厉害了解决了，谢谢大佬回复

**Comment by peterlxb** [comment]
<img width="561" alt="截屏2023-05-24 19 44 28" src="https://github.com/ant-design/ant-design-pro/assets/8121883/ed123054-5e34-4821-905b-b8bd005b2d46">
为什么自定义 footer 是这样的，看了文档，用 umi3 没有问题，umi4 有问题
