### ISSUE TITLE
👑 [需求] 可以增加表格的列或者宽的拖拽功能 ，ElementUi AntdVue的Surely Vue 都有这个功能啦，

### ISSUE THREAD

**Issue by ngwszsd** [ant-design/ant-design-pro#10056]
### 🥰 需求描述 | Requirements description
+ 可以增加表格的列的拖拽功能， elementUi AntdVue的Surely Vue 都有这个功能  这是高性能组件 Surely Vue 的一个  [Demo ](https://www.surely.cool/doc/dragable#columns)  它只需要在column数据设置一个参数resizable = true就可以实现
+ 虽然有react-resizable这个插件可以在原生Table实现列的拖拽功能（ps: 体验也不太好） 但在Pro组件的ProTable会特别卡 体验非常差
下图是Surely Vue 例子 

![image](https://user-images.githubusercontent.com/45424459/180356599-5284aea2-1f06-4319-8ac9-a2f90ccd2d3f.png)

**Comment by chenshuai2144** [comment]
去催一下 antd，这个功能太卡了。
