### ISSUE TITLE
👑 [需求]: ProLayout的fixSiderbar和navTheme: dark时顶部菜单收起背景变白色

### ISSUE THREAD

**Issue by XueMeijing** [ant-design/ant-design-pro#10062]
### 🥰 需求描述 | Requirements description

问题1、fixSiderbar这个配置介绍的是 是否固定导航，但是他实际上的效果是Drawer的closable，是否显示左上角的关闭按钮。
![image](https://user-images.githubusercontent.com/35559153/180706303-745e51b7-4480-4e64-a329-1ad1d5e632c3.png)

问题2、navTheme: dark时顶部菜单收起背景变白色
![image](https://user-images.githubusercontent.com/35559153/180706931-6ad616f4-631b-4480-b10c-78e0f850e7dc.png)
![image](https://user-images.githubusercontent.com/35559153/180707037-9b7f2055-c672-4cc5-afc1-d14e76432463.png)

### 🧐 解决方案 | Solution

1. 不知道固定导航是否有其他的意思，如果没有的话，文档上能不能改成弹出菜单Drawer的closable
2. 我没有用umi，应该跟这个情况不一样吧？https://github.com/ant-design/ant-design-pro/issues/10028

**Comment by chenshuai2144** [comment]
变成drawer是因为手机模式
你理解的意思是对的 但是屏幕太小了
