### ISSUE TITLE
[@umijs/runtime] load component failed Error: Module "./ethers" does not exist in container. while loading "./ethers" from webpack/container/reference/mf🐛 [BUG]

### ISSUE THREAD

**Issue by YangYuHub** [ant-design/ant-design-pro#10069]
### 🐛 bug 描述

import { ethers } from 'ethers';

<img width="629" alt="image" src="https://user-images.githubusercontent.com/63183404/181039202-82ad98e5-1086-4758-a9dc-939f73f30253.png">

![image](https://user-images.githubusercontent.com/63183404/181039011-8bea1068-8155-40ef-ae0c-999845ae9322.png)

### 🏞 期望结果 | Expected results

可以正常使用ethers

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.20.0]
- umi 版本  3.5.0
- 浏览器环境 chrom
- 开发环境 [e.g. mac OS]

**Comment by coderlcb** [comment]
引入新的库就报这个错，太恶心了

**Comment by chenshuai2144** [comment]
关掉mfus把，这种不怎么规范的库，mfsu兼容性不好

**Comment by soeasyjx** [comment]
> mfus
怎么关闭

**Comment by YanxinTang** [comment]
可以试试删除 node_modules/.cache 重构构建
