### ISSUE TITLE
🧐[问题 | question]  V5版本 菜单从后端请求 如何实现不同用户 能看到不同菜单

### ISSUE THREAD

**Issue by github-lzxlee** [ant-design/ant-design-pro#10066]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by tKlint** [comment]
可以在 app.tsx内 请求meun菜单,并添加到initState上, 然后再layout内添加menuDataRender属性
![image](https://user-images.githubusercontent.com/49471670/180949402-0a2bf083-11c1-4037-9f90-cfc135adfaae.png)
![image](https://user-images.githubusercontent.com/49471670/180949493-81259ea9-42fd-434c-bbbe-b23e4a62a140.png)

**Comment by github-lzxlee** [comment]
> 可以在app.tsx里面请求meun菜单，然后添加到initState上，然后再layout里面的menuDataRender属性 ![图片](https://user-images.githubusercontent.com/49471670/180949402-0a2bf083-11c1-4037-9f90-cfc135adfaae.png) ![图片](https://user-images.githubusercontent.com/49471670/180949493-81259ea9-42fd-434c-bbbe-b23e4a62a140.png)

现在已经实现动态加载菜单 现在是想知道如何在动态菜单的 基础上 对不同用户做路由的访问限制

**Comment by xiahller** [comment]
可以在跳转时查询后端权限接口，没权限就不跳转或者跳转到缺省页么

**Comment by github-lzxlee** [comment]
> 

是指重定向吗

**Comment by github-lzxlee** [comment]
> 可以在跳转时查询后端权限接口，没权限就不跳转或者跳转到缺省页么

是指重定向到403页面吗

**Comment by xiahller** [comment]
> > 可以在跳转时查询后端权限接口，没权限就不跳转或者跳转到缺省页么
> 
> 是指重定向到403页面吗

是的，我也要做类似需求，但我没有考虑到你说的情况，

**Comment by github-lzxlee** [comment]
> > > 可以在跳转时查询后端权限接口，没权限就不跳转或者跳转到缺省页么
> > 
> > 
> > 是指重定向到403页面吗
> 
> 是的，我也要做类似需求，但我没有考虑到你说的情况，

假设用户知道url地址 但是用户没有访问该页面的权限 你是怎么处理的呢 还有你后端返回的菜单是所有菜单还是用户有权限的菜单

**Comment by xiahller** [comment]
> 

我还没开始写这块功能，后端返回所有菜单或者有权限的菜单都一样吧，反正咱们在展示上面要处理呀

**Comment by haiyatx** [comment]
https://blog.csdn.net/haiyabtx/article/details/127363731
配置路由+登录路由

**Comment by lcc908** [comment]
哥们找到解决方案了吗

**Comment by lcc908** [comment]
> > 可以在app.tsx里面请求meun菜单，然后添加到initState上，然后再layout里面的menuDataRender属性 ![图片](https://user-images.githubusercontent.com/49471670/180949402-0a2bf083-11c1-4037-9f90-cfc135adfaae.png) ![图片](https://user-images.githubusercontent.com/49471670/180949493-81259ea9-42fd-434c-bbbe-b23e4a62a140.png)
> 
> 现在已经实现动态加载菜单 现在是想知道如何在动态菜单的基础上 对不同用户做路由的访问限制 现在虽然菜单不同 但是用户还是能够通过地址栏输入地址实现访问 有什么办法能让用户没有权限访问的路由直接跳转内置的403页面

哥们，遇到和你一样的问题，你解决了吗

**Comment by KYX1234** [comment]
我的想法是在页面跳转的时候拿pathname和menu比较，如果menu里不存在，说明没有这个权限，给他反403
