### ISSUE TITLE
pro 5 官方登录逻辑 处理 有问题 

### ISSUE THREAD

**Issue by tuonioooo** [ant-design/ant-design-pro#10061]
pro 5 官方demo  登录逻辑 处理 有问题 

1.我从官方的代码下载下来 install 依赖后， 登录进去 到欢迎页  直接报错

![image](https://user-images.githubusercontent.com/22735328/180642231-8aa108c4-abe2-420c-b628-ebf379fa73f6.png)

2.还有就是 我已经登录进去之后，状态都已经保存了，在浏览器直接访问登录页 ，居然直接跳转过去了，不是应该跳转欢迎页么

**Comment by PaleGeek** [comment]
我也遇到这个问题

**Comment by coderlcb** [comment]
+1

**Comment by pkaq** [comment]
![image](https://user-images.githubusercontent.com/4537450/185818822-160a187f-bdfa-4b5c-8a05-e4a28d89a18f.png)
如图可解决 之前也有人问 官方只解释了问题的原因就是众所周知得组件销毁了还在设置状态 并未给出解决方式以及框架层面得原因
@coderlcb @PaleGeek @tuonioooo

**Comment by loseleo** [comment]
> ![image](https://user-images.githubusercontent.com/4537450/185818822-160a187f-bdfa-4b5c-8a05-e4a28d89a18f.png) 如图可解决 之前也有人问 官方只解释了问题的原因就是众所周知得组件销毁了还在设置状态 并未给出解决方式以及框架层面得原因 @coderlcb @PaleGeek @tuonioooo

还要删除 await refresh();

**Comment by RainThinks** [comment]
遇到了同样的问题。

看了眼BaseForm的实现，里面把传入的onFinish方法又封了一次，在onFinish执行完毕后，有一个 setLoading(false)的操作。所以只要在onFinish方法里unmount组件，比如更改了路由，在执行到setLoading(false)的时候，就会报内存泄露错误。

目前看来是没有优雅的办法绕过去了，只能采用setTimeout的方法，或者就不去管那个报错。

**Comment by chenshuai2144** [comment]
新版本的react 会删除掉的，先假装看不见把，这种很麻烦

**Comment by tuonioooo** [comment]
@chenshuai2144 @loseleo @pkaq  我就是发现问题 顺便提议一下  让大家知晓 一下   绕过的方法 跟大家差不多  希望更多的志同道合的朋友 都来用nice的框架  尤其是UI 每周一更改bug  让我由衷的佩服
