### ISSUE TITLE
🐛 [BUG] app.js 增加export 变量，就会报TypeError: Cannot read properties of undefined (reading '@@initialState')错误

### ISSUE THREAD

**Issue by XueMeijing** [ant-design/ant-design-pro#10063]
### 🐛 bug 描述
umi v3.5.23, app.js 增加export 变量，比如export const aa = 1; 就会报TypeError: Cannot read properties of undefined (reading '@@initialState')错误
跟这个差不多 https://github.com/ant-design/ant-design-pro/issues/8109

![image](https://user-images.githubusercontent.com/35559153/180908835-d37cee68-9d6a-42cf-b52a-4b8797128155.png)

### 📷 复现步骤 | Recurrence steps

app.tsx增加 export const aa = 1;

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
里面不能用任何导出的 只能用我们定义的
