### ISSUE TITLE
利用antd-pro使用umi的qiankun插件做微前端，子应用如何使用主应用的组件,  看下面的代码：使用的原生的button传到子应用可以使用，但是使用antd的Button传递过去使用就会报错，凡是用的antd的组件都不行

### ISSUE THREAD

**Issue by sunlianglife** [ant-design/ant-design-pro#10077]
// app.tsx
export const useQiankunStateForSlave = () => ({
  MainButton: (props: any) => <MainButton {...props} />,
  mainData: {
    aa: 11,
  },
});

// MainButton 组件

export default (props: any) => {
  return (
    <Button {...props} style={{ minWidth: 80, ...props?.style }}>
      {props?.children}
    </Button>
  );
};

**Comment by chenshuai2144** [comment]
Monorepo欢迎你
