### ISSUE TITLE
🐛 [BUG]菜单收缩展开一顿操作之后，子菜单悬浮到最上面去了

### ISSUE THREAD

**Issue by xiahller** [ant-design/ant-design-pro#10075]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/55370123/181226770-0739f9ac-140e-4c0b-b66c-07df11979098.png)

当前菜单有三级菜单，是通过render动态获取的，在操作最后面一个菜单的第三级菜单时，发现三级菜单悬浮到了网页顶部

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
<html>
<body>


getPopupContainer | 弹出框（Select, Tooltip, Menu 等等）渲染父节点，默认渲染到 body 上。 | function(triggerNode) | () => document.body |  
-- | -- | -- | -- | --
getTargetContainer | 配置 Affix、Anchor 滚动监听容器。 | () => HTMLElement | () => window | 4.2.0


</body>
</html>


需要了解一下这两个api

**Comment by xiahller** [comment]
> getPopupContainer	弹出框（Select, Tooltip, Menu 等等）渲染父节点，默认渲染到 body 上。	function(triggerNode)	() => document.body	 
> getTargetContainer	配置 Affix、Anchor 滚动监听容器。	() => HTMLElement	() => window	4.2.0
> 需要了解一下这两个api
> 
> https://ant.design/components/config-provider-cn/

请问这两个api在哪里写呢
