### ISSUE TITLE
🐛 [BUG]表格列配置hideInForm无效

### ISSUE THREAD

**Issue by DongWenHai** [ant-design/ant-design-pro#10071]
### 🐛 bug 描述

表格列配置hideInForm无效，筛选表单依然出现该项

### © 版本信息

- Ant Design Pro 版本: [6.0.0-beta.1]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
hide I search. 

Hide in form被预留到别的地方了

**Comment by shuai4983958** [comment]
so....应该怎么解决，或者使用hideInForm

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/183546102-4aa9e56d-a61d-4513-a7db-418640d31dec.png)


求求看看文档吧，问问题也需要水平的，都是低级问题也太掉社会地位了

**Comment by dalaoque** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/183546102-4aa9e56d-a61d-4513-a7db-418640d31dec.png)
> 
> 求求看看文档吧，问问题也需要水平的，都是低级问题也太掉社会地位了

膜拜装逼大佬！
