### ISSUE TITLE
🧐[问题 | question] 不知道为什么突然所有的card增加了阴影圆角 其他组件也有变化 求助

### ISSUE THREAD

**Issue by xyhallo** [ant-design/ant-design-pro#10079]
![image](https://user-images.githubusercontent.com/44963132/181436404-c796be72-08f4-46d5-8003-10c46b651432.png)
![image](https://user-images.githubusercontent.com/44963132/181436449-4f30e31c-c335-46b3-9f9a-d939632ae716.png)

之前都没有的，突然就自动生成这个样式了，求助

**Comment by drizzlesconsin** [comment]
ProLayout 新版本的设计 https://github.com/ant-design/pro-components/issues/4741

**Comment by xyhallo** [comment]
> ProLayout 新版本的设计 [ant-design/pro-components#4741](https://github.com/ant-design/pro-components/issues/4741)

谢谢
