### ISSUE TITLE
使用 https://beta-pro.ant.design/docs/getting-started-cn 方式创建🧐[问题 | question]

### ISSUE THREAD

**Issue by lazyermax** [ant-design/ant-design-pro#10078]
### 🧐 问题描述 | Problem description
使用 https://beta-pro.ant.design/docs/getting-started-cn 方式创建 没有 v4 v5 版本选择，是什么原因？

创建出来的项目只有umijs内容，没有 antd pro 的登录，权限 ，config等内容

npx create-umi myapp2
? Pick Umi App Template » - Use arrow-keys. Return to submit.
    Simple App
>   Ant Design Pro
    Vue Simple App

√ Pick Umi App Template » Ant Design Pro
? Pick Npm Client » - Use arrow-keys. Return to submit.
    npm
    cnpm
    tnpm
>   yarn
    pnpm

√ Pick Umi App Template » Ant Design Pro
√ Pick Npm Client » yarn
? Pick Npm Registry » - Use arrow-keys. Return to submit.
    npm
>   taobao

**Comment by chenshuai2144** [comment]
看看升级到umi3的那个issue
