### ISSUE TITLE
🧐[问题 | question]chrome浏览器切换回来，表格会默认请求一次，如何取消？

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#10072]
如题，预览页面也有这样的效果，请问如何取消？
https://preview.pro.ant.design/list/table-list
用的chrome浏览器 版本 103.0.5060.134 (正式版本) (64 位元)

**Comment by Merry74751** [comment]
修改 ProTable的revalidateOnFocus 为false就可以了

**Comment by z-lionel** [comment]
> revalidateOnFocus

这个可以，谢谢
