### ISSUE TITLE
👑 [需求] 支持增量编译? 只改了一个页面,只需要编译当前页面对应的.js和.html 就好了啊

### ISSUE THREAD

**Issue by Valar103769** [ant-design/ant-design-pro#10073]
yarn run build 时,会把整个项目build, 只改了一个页面,而一个页面对应一个.js和.html, 应该只需要新生成那一个.js和.html就好了啊

**Comment by chenshuai2144** [comment]
现在的项目也只有一个HTML 和 J's
 剩下的都是那一份的Copy

单页应用的标准套路，而且没有问题的产物比那点性能重要多特
