### ISSUE TITLE
自定义icon地址 结果图标不出来

### ISSUE THREAD

**Issue by wh-990624** [ant-design/ant-design-pro#10083]
![image](https://user-images.githubusercontent.com/75351551/181466786-f23969f2-4e8c-4f52-8ee2-02110df2edea.png)之前是官方地址，目前不能生成新地址，于是我们想下载静态资源挂我们自己的服务器，然后配置了地址，图标没出来 ，看了图标前缀是没错的，控制台查看dom也有对用图标名

**Comment by wh-990624** [comment]
![image](https://user-images.githubusercontent.com/75351551/181466717-713f1435-786b-4010-9c49-4aae7e79c47f.png)之前是官方地址，目前不能生成新地址，于是我们想下载静态资源挂我们自己的服务器，然后配置了地址，图标没出来 ，看了图标前缀是没错的，控制台查看dom也有对用图标名

**Comment by chenshuai2144** [comment]
要用icon开头的明细 你这么用了吗

**Comment by J-env** [comment]
用的 umi@4 创建的项目 ant-design-pro@6.0.0-beta.1, @ant-design/icons 找的icon 没有显示出来


<img width="298" alt="image" src="https://user-images.githubusercontent.com/25259920/184053139-2dc7c07d-42d4-4e98-9ec5-adbbe298e22c.png">

**Comment by J-env** [comment]
> 用的 umi@4 创建的项目 ant-design-pro@6.0.0-beta.1, @ant-design/icons 找的icon 没有显示出来
> 
> <img alt="image" width="298" src="https://user-images.githubusercontent.com/25259920/184053139-2dc7c07d-42d4-4e98-9ec5-adbbe298e22c.png">

写法错误，这样就可以了
<img width="394" alt="image" src="https://user-images.githubusercontent.com/25259920/184056700-f7a51e71-1bef-490b-8a86-99ff11bc105b.png">

**Comment by wh-990624** [comment]
用了&nbsp; 抱歉 是我们授权得问题&nbsp; 当时把icon引入我们自己服务器后更换了在线地址 导致得 抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 凌晨2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 自定义icon地址 结果图标不出来 (Issue #10083)





 
要用icon开头的明细 你这么用了吗
