### ISSUE TITLE
ProTable组件的form的syncToUrl属性刷新页面点击重置按钮表单数据没有清空🐛 [BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#10080]
### 🐛 bug 描述
使用ProTable的form的syncToUrl属性设置选完表单赋值在url链接上，选完表单马上点击重置能清空表单, 但是刷新页面后再点击重置按钮去无法清空表单，为何是为啥？代码如图所示
![image](https://user-images.githubusercontent.com/20655248/181449183-b7fb2048-dca8-48c2-b916-eec98e817906.png)
![image](https://user-images.githubusercontent.com/20655248/181449256-c574d085-8111-4623-a74f-a4a2f910277d.png)
![image](https://user-images.githubusercontent.com/20655248/181449683-4b582d05-54fa-49c6-abb4-9fe53a001972.png)
发现官网的demo也有这个问题存在：
![image](https://user-images.githubusercontent.com/20655248/181450077-4cb71fef-2399-482d-9802-0f62d89888bf.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
reset 会设置为 initialvalues，url 上的值会被设置为默认值，你可以配合这两个 api 满足你的需求



<html>
<body>


syncToUrl | 同步参数到 url 上,url 只支持 string，在使用之前最好读一下url 中的参数类型 | true \| (values,type)=>values | -
-- | -- | -- | --
syncToInitialValues | 同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据 | boolean | true


</body>
</html>syncToUrl	同步参数到 url 上,url 只支持 string，在使用之前最好读一下[url 中的参数类型](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)	true | (values,type)=>values	-
syncToInitialValues	同步结果到 initialValues,默认为 true 如果为 false，form.reset 的时将会忽略从 url 上获取的数据	boolean	true
