### ISSUE TITLE
🧐[问题 | question]v5.2.0版本如何修改自定义layout

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#10084]
请求如何给根路径下的菜单添加自定义layout
官网的说明不是看不是很清楚，在config里面这个routes是要数组结构的，下面的这个说明就看不懂了
我们在 src/layouts/中创建一个新的 BaseLayout.tsx，复制上面的代码，并在 config/config.ts 添加如下代码：
defineConfig({
  // added configuration
  routes: {
    path: '/',
    component: '.../layouts/BaseLayout',
  },
});

我这边只能给二级菜单添加自定义layout，如下，去掉name:'test'菜单就无法展示，只能用二级结构去展示，
请问怎么给一级菜单自定义layout

 {
    path: '/',
    name: 'test',
    component: '../layout/TabPanelLayout',
    routes: [
      {
        path: '/',
        redirect: '/welcome',
      },
      {
        path: '/welcome',
        name: 'welcome',
        icon: 'smile',
        component: './Welcome',
      },
      {
        name: 'testa',
        path: '/testa',
        component: './TestA',
      },
      {
        name: 'testb',
        path: '/testb',
        component: './TestB',
      },
      {
        component: './404',
      },
    ],
  },

**Comment by hsbtr** [comment]
> 配置 layout=false，然后和v4 同样的操作

layout: false后，项目报凑 register failed, invalid key layout from plugin ；
![image](https://user-images.githubusercontent.com/46487804/196317723-0fbb08d0-04e6-4375-91bf-2e2a26dc70ba.png)
请问这个问题你碰到过吗
