### ISSUE TITLE
🧐[问题 | question] router的access函数生效了返回了false,但菜单栏还是有它，也能访问

### ISSUE THREAD

**Issue by 523753042** [ant-design/ant-design-pro#10089]
### 🧐 问题描述 | Problem description

在router.ts中，给某给菜单配置了access是个函数，打印了函数也执行了，返回了false，但是菜单栏还有，也能访问
但是我打印执行canSee函数传入的这个route信息时候，打印了这个route地址引用的话，看到的unaccessible是true。
如果手动在routers.ts给他写死unaccessible:true。肯定是生效的，不知道问题出在哪
相关版本
```
    "umi": "^3.5.0",
    "@ant-design/pro-layout": "^6.15.3",
```

### 💻 示例代码 | Sample code
```
  { path: '/information', name: '资讯中心', access: 'canSee', icon: 'compass', component: './information/Management' },
//下面这个确实隐藏了没权限访问
  { path: '/announcement', name: '公告管理', unaccessible:true, icon: 'sound', component: './announcement/Management' },
//access.ts
export default function access(initialState: { currentUser?: API.CurrentUser | undefined }) {
  const { currentUser } = initialState || {};
  return {
    canAdmin: currentUser && currentUser.access === 'admin',
    canSee: (foo) => {
           console.log('foo', foo);
      console.log('foo', foo.unaccessible);
      return false
    }
  };
}

```

下面是config.ts
```
export default defineConfig({
  hash: true,
  history: { type: 'hash' },
  antd: {},
  dva: {
    hmr: true,
  },
  access: {
    strictMode: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    // locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  // manifest: {
  //   basePath: publicPath,
  // },
  // base: publicPath,
  // publicPath: publicPath,
  // Fast Refresh 热更新
  fastRefresh: {},
  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
  nodeModulesTransform: {
    type: 'none',
  },
  mfsu: {},
  webpack5: {},
  exportStatic: {},
});

```

### 🚑 其他信息 | Other information

<img width="816" alt="image" src="https://user-images.githubusercontent.com/26767055/181758199-cd5a0a42-1d1d-4929-b5be-b780080071f6.png">

<img width="226" alt="image" src="https://user-images.githubusercontent.com/26767055/181758664-90db0ecc-2149-46f4-b5af-920d0ccb773f.png">

OS:mac

Node：v16.14.2

浏览器 | browser：chrome

**Comment by 2430677100** [comment]
解决了么

**Comment by BlowinInWind** [comment]
解决了么

**Comment by 523753042** [comment]
还没有

**Comment by staxd** [comment]
![image](https://user-images.githubusercontent.com/42974252/186619358-34a2cfcc-8b1f-4361-b47d-cc0a487c72cf.png)
手动解决

**Comment by 2430677100** [comment]
好吧，这应该属于他们的原因吧，umi3没这个问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joe ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-pro] 🧐[问题 | question] router的access函数生效了返回了false,但菜单栏还是有它，也能访问 (Issue #10089)





 

 手动解决

**Comment by hb1707** [comment]
同样的问题，只在build后出现，dev下没这个bug

**Comment by choi2k** [comment]
> ![image](https://user-images.githubusercontent.com/42974252/186619358-34a2cfcc-8b1f-4361-b47d-cc0a487c72cf.png) 手动解决

想问一下 getAccess 和 getPathName 是哪里的？.. 没翻到有这样的 API.

**Comment by drizzlesconsin** [comment]
可以先这样处理
https://github.com/ant-design/ant-design-pro/pull/10205/commits/82ab17668b7a2d15ec43b512580affe4c0f4a1b7

**Comment by choi2k** [comment]
> 可以先这样处理 [82ab176](https://github.com/ant-design/ant-design-pro/commit/82ab17668b7a2d15ec43b512580affe4c0f4a1b7)

刚刚看到了 感谢

**Comment by chenshuai2144** [comment]
这里在解决

https://github.com/umijs/umi/pulls

**Comment by wangxing0204** [comment]
解决了么

**Comment by wangmeijian** [comment]
> 可以先这样处理 [82ab176](https://github.com/ant-design/ant-design-pro/commit/82ab17668b7a2d15ec43b512580affe4c0f4a1b7)

不行

**Comment by chenshuai2144** [comment]
试着全套升级下最新版本，我的复现脚手架里面一直没法复现

**Comment by wangmeijian** [comment]
umi3的用户，降级@ant-design/pro-layout 到6.26.0版本可解决
