### ISSUE TITLE
使用ant design pro构建项目后台不报错但是页面报错是什么原因Use ant design pro to build the project，but background is without error and the page has errors . What is the reason for this?

### ISSUE THREAD

**Issue by Mu-99** [ant-design/ant-design-pro#1008]
![1](https://user-images.githubusercontent.com/36875648/36828255-95ba80c0-1d53-11e8-95a1-a32d67e41078.PNG)

**Comment by Mu-99** [comment]
原本是按照官网操作的，但是报错不知道什么原因
// src/router.js
> <Router history={history}>
      <Switch>
        <Route path="/new" render={props => <BasicLayout {...props} />} />
        <Route path="/user" render={props => <UserLayout {...props} />} />
        <Route path="/" render={props => <BasicLayout {...props} />} />
      </Switch>
    </Router>

**Comment by chenshuai2144** [comment]
把代码贴全一点。
写的太模糊了

**Comment by Mu-99** [comment]
![2](https://user-images.githubusercontent.com/36875648/36828696-5d04b144-1d56-11e8-95ae-60c304b826f0.PNG)
因为代码贴上去有些无法显示就截图了

**Comment by afc163** [comment]
http://segmentfault.com/markdown

**Comment by chenshuai2144** [comment]
去补补基础吧。你的代码从开头就是错的
