### ISSUE TITLE
antd pro 的侧边菜单栏宽度新版本是写死了256px吗 改了config里面的siderWidth不生效🐛 [BUG]

### ISSUE THREAD

**Issue by huangye0** [ant-design/ant-design-pro#10088]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by huangye0** [comment]
![image](https://user-images.githubusercontent.com/48897708/181730572-6172e63f-2c39-4cf8-aab0-0e313dfb7ea9.png)

**Comment by huangye0** [comment]
![image](https://user-images.githubusercontent.com/48897708/181730678-66da4daa-0da6-4f04-a58a-4075741de1e0.png)

**Comment by fnoopv** [comment]
+1，应该是写死零或者没有使用这个参数，我这边也是一样的情况

**Comment by chenshuai2144** [comment]
新版本还没有支持 我先记个bug

**Comment by Seven777Z** [comment]
> 新版本还没有支持 我先记个bug

包括mix下的headerTheme=dark 也不支持

**Comment by huangye0** [comment]
这个什么时候会修复

**Comment by huangye0** [comment]
你好 ，这个bug大概会啥时候修复更新呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月4日(星期四) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] antd pro 的侧边菜单栏宽度新版本是写死了256px吗 改了config里面的siderWidth不生效🐛 [BUG] (Issue #10088)





  
新版本还没有支持 我先记个bug
  
包括mix下的headerTheme=dark 也不支持

**Comment by drizzlesconsin** [comment]
把 `siderWidth: 208,` 写在 `defaultSettings.ts` 就行了，去掉 `config/config.ts` 里的 `siderWidth`. 
不然就写在 app.tsx -> layout 的 `menu` props

> Umi4 在 config.ts layout 支持的属性不多

**Comment by huangye0** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] antd pro 的侧边菜单栏宽度新版本是写死了256px吗 改了config里面的siderWidth不生效🐛 [BUG] (Issue #10088)





 
把 siderWidth: 208, 写在 defaultSettings.ts 就行了，去掉 config/config.ts 里的 siderWidth.
 不然就写在 app.tsx -&gt; layout 的 menu props
  
Umi4 在 config.ts layout 支持的属性不多

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果要在 `config/config.ts` 中修改侧边菜单栏的宽度，可以使用 `childrenLayout` 属性，示例如下：

```typescript
export default {
  layout: {
    childrenLayout: {
      siderWidth: 208, // 修改侧边菜单栏宽度
    },
  },
  // ...
}
```

此外，还可以将 `siderWidth` 属性写在 `defaultSettings.ts` 中或在 `app.tsx` 的 `layout` 属性中修改。
