### ISSUE TITLE
🧐 新手问题：SettingDrawer不显示

### ISSUE THREAD

**Issue by haoming** [ant-design/ant-design-pro#10090]
### 🧐 SettingDrawer不显示

用start或start:pre启动一个模板项目，登录后，看不到用来打开SettingDrawer的icon，查看渲染出的HTML，没有找到SettingDrawer对应的内容。

### 💻 示例代码 

$ npm i @ant-design/pro-cli -g
$ pro create my-app
$ cd my-app
$ yarn
$ yarn start    或者  yarn start:pre

打开页面并登录，页面上没有用来打开SettingDrawer的icon。

### 🚑 其他信息

我查看了[SettingDrawer的代码](https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/SettingDrawer/index.tsx)，没有找到控制是否删除SettingDrawer渲染内容的逻辑。

请各位指教，多谢！

### 环境

OS: macOS 12.5

Node：v16.14.2

@ant-design/pro-cli: ^2.1.0

@ant-design/pro-components: 1.1.1

antd: ^4.20.0

浏览器：Safari 15.6

**Comment by chenshuai2144** [comment]
默认的脚手架没有带这个功能。要手动引入下. 可以看看all block的分支

**Comment by joesdu** [comment]
我也有这个疑问, 看了all block的分支也没有发现有什么不同.

**Comment by zhengmenghuang** [comment]
应该是框架的问题吧。all block 是umi3.5的项目。基于umi4.0的是设置按钮不见了，但是 设置 collapse={true} 控制抽屉会出现。

**Comment by chenshuai2144** [comment]
是 antd 的版本问题，antd 新版本去掉了 handle api 我已经修复掉了，更新一下版本

**Comment by qsya** [comment]
> 是 antd 的版本问题，antd 新版本去掉了 handle api 我已经修复掉了，更新一下版本

升级antd到4.22.3，还是不显示SettingDrawer按钮

**Comment by HQDragon** [comment]
@chenshuai2144 ,不想新开issue，但是升级了pro-components和antd之后也不行。 这边在react tools里看，显示的是settingdrawer在strict mode下不显示
![image](https://user-images.githubusercontent.com/15418465/183538884-520027fc-c596-475c-8641-52409f7cd810.png)

**Comment by HQDragon** [comment]
![image](https://user-images.githubusercontent.com/15418465/183541390-d982ceb2-c1a5-491b-aee8-b4c90f3e18d9.png)
![image](https://user-images.githubusercontent.com/15418465/183541412-774b1f53-1276-4fb2-b2fc-d95135b9e3db.png)
对比新老版本，可以看到新版本缺少了data-inspector-column和data-inspector-line属性

**Comment by chenshuai2144** [comment]
是 pro-components 的版本

**Comment by haoming** [comment]
我把pro-components升级到1.1.15，问题解决了。

@chenshuai2144 多谢修复bug。下次回答类似问题，不妨多花两秒钟说清楚把哪个库升级到哪个版本。

再次感谢。

**Comment by haoming** [comment]
我想看一下问题是怎么解决的，找到[这次提交](https://github.com/ant-design/pro-components/commit/bb82097fcd9da37b9733108426c184c66e55af4a#diff-d3026eac49660c20dba3bdedce42f40743fc5f71e4fae842554581f7887ee620)，在packages/layout/src/components/SettingDrawer/index.tsx修改中添了个[留言](https://github.com/ant-design/pro-components/commit/bb82097fcd9da37b9733108426c184c66e55af4a#r80694905)，应该是解决这个bug的关键点（如果不对，请各位指正。谢谢）。

**Comment by qsya** [comment]
> 我把pro-components升级到1.1.15，问题解决了。
> 
> @chenshuai2144 多谢修复bug。下次回答类似问题，不妨多花两秒钟说清楚把哪个库升级到哪个版本。
> 
> 再次感谢。

大佬们，为啥umi4版本的升级后无效，umi3.5 simple升级pro-components后可行

**Comment by cuijiudai** [comment]
我从 github上下载了个最新  umi-3 分支，也不显示

**Comment by changlin0501** [comment]
> 我把pro-components升级到1.1.15，问题解决了。
> 
> @chenshuai2144 多谢修复bug。下次回答类似问题，不妨多花两秒钟说清楚把哪个库升级到哪个版本。
> 
> 再次感谢。

你好，请问antd是用哪个版本呢？我使用pro-components 1.1.15 也还是不出现ICON

**Comment by Zhulan520** [comment]
我的antd版本时4.20.0的，把pro-components升级到1.1.15，SettingDrawe消失的问题解决了
