### ISSUE TITLE
CountDown的target设置为过去时间，首次显示出现问题

### ISSUE THREAD

**Issue by BugHiding** [ant-design/ant-design-pro#1009]
设置时间为过去时间的时候，首次显示有问题
具体如下图

![default](https://user-images.githubusercontent.com/6602889/36830815-2bcae3c8-1d60-11e8-904c-452a4d3da74c.gif)

![qq 20180301145329](https://user-images.githubusercontent.com/6602889/36830908-93073410-1d60-11e8-8792-b3eed313bfa1.png)

![qq 20180301145349](https://user-images.githubusercontent.com/6602889/36830914-9ad82316-1d60-11e8-924b-97eeacd809bc.png)

```JSX
<CountDown
  target={record.targetTime}
/>
```

targetTime 的时间戳比当前时间小的时候，首次加载就会出现上述情况，请问该如何解决，谢谢

**Comment by ddcat1115** [comment]
targetTime 为以当前时间为起点的目标时间，不应该设置为过去的时间吧

**Comment by BugHiding** [comment]
嗯，targetTime是应该以当前时间为基准，但是有的倒数着就结束了，结束后重新打开页面，它就变成过去的时间了。倒计时就终止了，这个时候就希望它可以直接显示00：00：00，而不希望出现上面的NaN。本来我自己在给targetTime的时候加判断，没有成功，所以来求助官方了，谢谢。

**Comment by ddcat1115** [comment]
是有点问题，我瞅瞅

**Comment by BugHiding** [comment]
嗯，非常感谢，我想问一下，如何使用修改过后的ant-design-pro，等npm的包更新么
