### ISSUE TITLE
在导入模块时，class中static函数每次修改代码无法热更新，需要手动刷新

### ISSUE THREAD

**Issue by lee272716** [ant-design/ant-design-pro#10093]
求大佬什么解决这个无法热更新问题，在导入模块时导出class时调用静态方法，在静态方法中修改代码时无法热更新，只能把static关键字去掉，改用new对象去调用方法后，在对象方法中修改代码可以热更新

**Comment by chenshuai2144** [comment]
这是热更新的原理导致的他相当于一个rerender,静态方法不在生命周期里面。
另外推荐尽量不要用静态方法 它很危险
