### ISSUE TITLE
ProTable的request属性携带的参数current要怎么改做pageNum🐛 [BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#10095]
### 🐛 bug 描述
使用ProTable组件的request属性获取参数current，但是接口要传过去的参数是pageNum, 怎样改才能将params的默认参数由current替换为pageNum，这样传过去方便一点。
![image](https://user-images.githubusercontent.com/20655248/182519469-382c2882-8a2c-425e-9b8e-bae7c3aedb0d.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by z-lionel** [comment]
从app的请求拦截统一做，要不然就让后端统一修改了
