### ISSUE TITLE
👑 [需求] ant design sidebar 跟 pro 不太一样

### ISSUE THREAD

**Issue by arlyxiao** [ant-design/ant-design-pro#10104]
### 🥰 需求描述 | Requirements description

这里给的例子， sidebar 的样式 跟 pro 版的 sidebar 有点不太一样
https://ant.design/components/layout/#components-layout-demo-fixed-sider

pro sidebar 效果
https://preview.pro.ant.design/dashboard/analysis

主要的区别在于

- 滚动条样式
- 左下角那个可以向左缩放的 icon

请问，仅仅使用 ant design，如何做成跟 pro 一样的样式效果？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design

你需要这个 库，你应该是版本的问题使用了最新的layout设计，可以手动安装一下 pro-components
