### ISSUE TITLE
没法install  

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design-pro#1010]
![qq 20180301170705](https://user-images.githubusercontent.com/34823990/36836048-1f039410-1d73-11e8-9842-51923d000e03.png)
![qq 20180301170926](https://user-images.githubusercontent.com/34823990/36836105-556044f4-1d73-11e8-8c48-425c50985825.png)

**Comment by chenshuai2144** [comment]
最好不要中文。。。

**Comment by afc163** [comment]
网络问题，建议使用 cnpm。
