### ISSUE TITLE
🧐[问题 | question] protable里的时间段类型的值处理处理优雅点？

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#10100]
protable里面valueType为时间段的，request返回和form获取到的格式为key: [moment, moment]。
现在每次获取的时候都需要自己处理下[start, end] = key,感觉很麻烦，有没有更优雅的方法直接从form返回就是start,end，并去掉key这个东西

现在dataIndex 的string[]格式返回的参数是嵌套格式: start.end:[moment, moment]
可不可以优化为：
可以用点做嵌套格式的返回：start.end:[moment, moment]
用数组直接返回 {start,end}这样的格式

**Comment by chenshuai2144** [comment]
你需要的是 transform 转化把

https://procomponents.ant.design/components/form#transform-%E6%8F%90%E4%BA%A4%E6%97%B6%E8%BD%AC%E5%8C%96

**Comment by z-lionel** [comment]
> 你需要的是 transform 转化把
> 
> https://procomponents.ant.design/components/form#transform-%E6%8F%90%E4%BA%A4%E6%97%B6%E8%BD%AC%E5%8C%96

这个转化在request里面获取的参数是能达到效果，但是通过formRef.current?.validateFields()获取的还是没有转化,
给DatePicker这个组件加上这个api的话就能表现统一了吧
  search:{
        transform:(values) =>{
          return {
            startDate: values ? values[0] : undefined,
            endDate: values ? values[1] : undefined,
          };
        },
      },
