### ISSUE TITLE
🐛 [BUG] 一个小小的API命名问题

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design-pro#10105]
一个小小的API命名问题，说不上Bug

退出登录接口调用的Rest URL路径为 /api/login/outLogin
一般大家管退出登录都叫logoff, 或者logout，几乎非常少听到outLogin。
如果能把代码中的所有outLogin (包括方法名，路径等)改为logout，大家看见这个名字更容易理解什么意思。

我知道antd Pro生成模板后大家都可以自己改。只是觉得如果生成的这个模板如果已经是个好名字好路径的话，大家就省点修改的时间。

### 📷 复现步骤 | Recurrence steps

pro create myapp

### 🏞 期望结果 | Expected results

期望生成的代码中，登录登出用常用的英文单词，Rest URL的路径结构和逻辑结构符合。

### 💻 复现代码 | Recurrence code

略

### © 版本信息

- Ant Design Pro 版本: e.g. 5.2.0
- umi 版本 4.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
个人感觉这个问题不适合,因为模板中的API在实际使用种,几乎是全部都会被替换.

**Comment by chenshuai2144** [comment]
这个命名风格问题，我们都是 openapi生成的，跟着后端来
