### ISSUE TITLE
🧐[问题 | question]不知道为什么我登录按钮需要点击两次才能登录

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#10107]
### 🧐 问题描述 | Problem description

我打开官方的源码,第一次点击登录后会提示登录成功,但实际没有跳转,还需要再次输入账号密码登录才会跳转.修改成自己的接口后,请求接口确实是成功的,并且返回了正确的数据.

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by Try2b1st** [comment]
我也出现类似的问题，可以提供一下解决方法吗
