### ISSUE TITLE
🐛 [BUG] .gitignore中不应该包括lock文件。

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design-pro#10106]
### 🐛 bug 描述

.gitignore中不应该包括下面三个文件。

yarn.lock
package-lock.json
pnpm-lock.yaml

参考文献：https://classic.yarnpkg.com/lang/en/docs/yarn-lock/
All yarn.lock files should be checked into source control (e.g. git or mercurial). This allows Yarn to install the same exact dependency tree across all machines, whether it be your coworker’s laptop or a CI server.

Framework and library authors should also check yarn.lock into source control. Don’t worry about publishing the yarn.lock file as it won’t have any effect on users of the library.

### 📷 复现步骤 | Recurrence steps

pro create myapp

### 🏞 期望结果 | Expected results

.gitignore中不应该包括下面三个文件。

### © 版本信息

- Ant Design Pro 版本: 多个版本
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你可以删掉把，我们这里是不推荐使用lock的，应该总是用最新的
