### ISSUE TITLE
在ant-design-pro关于图片上传的问题

### ISSUE THREAD

**Issue by wdao7** [ant-design/ant-design-pro#1011]
![1](https://user-images.githubusercontent.com/34474826/36836224-c3154a80-1d73-11e8-8e4d-7ceabec8d9bf.png)
![2](https://user-images.githubusercontent.com/34474826/36836230-c6a91f14-1d73-11e8-900e-16fb8fcc2146.png)
![3](https://user-images.githubusercontent.com/34474826/36836234-c8fab1ce-1d73-11e8-99db-dd3242be0f39.png)
接口用表单测试过可以收到数据，可为啥用upload上传图片就一直走err呢

**Comment by valleykid** [comment]
怎么配置的代理呢？能否贴下代码

**Comment by wdao7** [comment]
![1](https://user-images.githubusercontent.com/34474826/36956442-63101dd8-2069-11e8-9454-8d50a7634c7b.png)
@valleykid 我yejuede也觉得好像是代理的问题，可我尝试不出来

**Comment by valleykid** [comment]
感觉和这个[#973](https://github.com/ant-design/ant-design-pro/issues/973)症状一样

**Comment by valleykid** [comment]
#973

**Comment by wdao7** [comment]
确实如此，后面我改成在.webpackrc里面配置代理就不会报错，谢谢 @valleykid

**Comment by liuhong1happy** [comment]
@wdao7 请问你怎么配置的代理，能否贴一下代码呐

**Comment by valleykid** [comment]
@liuhong1happy 请参考https://github.com/sorrycc/roadhog#proxy
