### ISSUE TITLE
🐛 [BUG]路由设置access无效，菜单和URL都能进去

### ISSUE THREAD

**Issue by ZengJun-cloud** [ant-design/ant-design-pro#10117]
### 🐛 bug 描述

路由设置access无效，菜单和URL都能进去

### 💻 复现代码 | Recurrence code

![image](https://user-images.githubusercontent.com/52198079/183861267-f58767c8-fe34-4ac5-b65b-811a5a211443.png)
![image](https://user-images.githubusercontent.com/52198079/183861387-b7217bc2-4bdd-4cc2-a95e-49d4481e8fad.png)
![image](https://user-images.githubusercontent.com/52198079/183861817-92829d6f-fee5-448a-94a2-3bf587237b83.png)

### © 版本信息

- Ant Design Pro 版本: 5.1.0
- umi 版本 "umi": "^3.5.0",
- 浏览器环境
- 开发环境  window

**Comment by ZengJun-cloud** [comment]
> 

在初始化state的时候return出去了

**Comment by ZengJun-cloud** [comment]
> <img alt="image" width="389" src="https://user-images.githubusercontent.com/69514654/184876491-bb150b2e-eb20-48d9-aa9a-9755b1d88094.png">
> 
> 这里面没有 role 吧
> 排错，先在 access.ts 里面，把返回的权限都写死 `false`

在初始化state的时候return出去了

**Comment by grubby14** [comment]
config.ts 里面加上access: {}试试

**Comment by hb1707** [comment]
同样的问题，页面会显示403，只是菜单不会自动隐藏了。权限全部false也是如此

**Comment by hb1707** [comment]
补充：我这边复现发现这个问题可能和setInitialState有关，因为开发环境有个SettingDrawer按钮里面有执行setInitialState，所以开发环境没有复现这个bug。但build之后，SettingDrawer按钮隐藏了，setInitialState没有再次执行，所以bug出现了。总之确实是个bug，setInitialState必须在菜单渲染完成之后再执行一次。

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/9410

这里在解决
