### ISSUE TITLE
👑 [需求]新版本何时能支持navTheme: dark

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#10112]
### 🥰 需求描述 | Requirements description
老版本可以实现和预览网站一样的效果, 并且预览网站的配置也可以直接使用, 使用新版模板创建项目后(`npx @ant-design/pro-cli create myapp`), 黑色菜单栏,导航栏都不起作用了, 且主题色配置也失效了(虽然可以依据非文档指定操作修改),.... 现在的官方文档和实际项目模板出入很大, 新手来了完全懵逼, 为啥按照文档操作啥作用也没有...?预览网站这么炫酷, 实际项目模板运行起来怎么改都不会变化...?

### 🧐 解决方案 | Solution
1, 如果新版已经不支持深色主题, 请直接在文档中说明, 并且指明用户使用哪个版本可以实现深色主题效果, 怎么使用; 如果支持, 请指明怎么配置  
2, 新版的配置和最终展现效果已经和文档不一致了, 这部分需要修改文档  
3, 预览网站的能力和新版不匹配

### 🚑 其他信息 | Other information
无

**Comment by chenshuai2144** [comment]
要用token自己配置，里面有一个 token 配置的 demo

https://next-procomponents.ant.design/components/layout

**Comment by zhangXiaolizi** [comment]
yarn create umi  my-app
选择ant-design-pro
然后运行起来修改navTheme 和  primaryColor都不起作用，但是修改layout: 'mix' 就布局有效，但是样式一直不生效，为啥

**Comment by zjxpcyc** [comment]
用 token 真是反人类的设计。与其 token , 还不如全部放开自定义。
