### ISSUE TITLE
🧐[问题 | question] 请问如何自定义多tabs

### ISSUE THREAD

**Issue by 114xiaoyu** [ant-design/ant-design-pro#10110]
### 🧐 问题描述 | 6版本自定义tabs问题

首先为了多tabs 我直接升级到6，用的很难受，我用的以前的路由获取方式，props无法获取，match，更改了hook
其次，我是动态路由，更改menu需要语义化，更改menu：false 此版本无效..；不得不卸载掉语义化，结果多页tabs又空值，
我想自定义，没地方插入，开启hasCustomTabs 就是需要getCustomTabs，写好getCustomTabs，RunTimeLayoutConfig配置报缺失getCustomTabs错误崩溃了死循环

### 💻 示例代码 | Sample code

tabsLayout: {hasCustomTabs: true}
在app.tsx里面哪里配置
RunTimeLayoutConfig 里面配置不了
我参考了此文档：https://developer.aliyun.com/article/987517

### 🚑 其他信息 | Other information

<img width="378" alt="image" src="https://user-images.githubusercontent.com/38286592/183378811-4a198b0f-758b-43b8-905d-9a79297479b6.png">

OS:

Node：

浏览器 | browser：

**Comment by 114xiaoyu** [comment]
首先为了多tabs 我直接升级到6，用的很难受，我用的以前的路由获取方式，props无法获取，match，更改了hook
其次，我是动态路由，更改menu需要语义化，更改menu：false 此版本无效..；不得不卸载掉语义化，结果多页tabs又空值，
我想自定义，没地方插入，开启hasCustomTabs 就是需要getCustomTabs，写好getCustomTabs，RunTimeLayoutConfig配置报缺失getCustomTabs错误崩溃了死循环

**Comment by 114xiaoyu** [comment]
tabsLayout: {hasCustomTabs: true}
在app.tsx里面哪里配置
RunTimeLayoutConfig 里面配置不了
我参考了此文档：https://developer.aliyun.com/article/987517

**Comment by 114xiaoyu** [comment]
error - ./src/.umi/plugin-keepalive/context.tsx:108:19-32
export 'getCustomTabs' (imported as 'getCustomTabs') was not found in '@/app' (possible exports: getInitialState, layout, request)

**Comment by 114xiaoyu** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/38286592/183380207-cde95909-414a-408f-a0a6-cdaa6f0c68c5.png">

**Comment by 114xiaoyu** [comment]
来个人救救孩子吧，孩子已经上火好几天了，写了那么多代码，难道我要换框架吗

**Comment by dengc367** [comment]
我用得没有问题。你有时间多看看源码和他的测试用例或者examples。

**Comment by 114xiaoyu** [comment]
你好，我是马晓宇，我已经收到你邮件

**Comment by chenshuai2144** [comment]
去问问tabslayout 作者把，我没用过这个多标签功能

**Comment by pkaq** [comment]
哈哈 #220 编号都过万了 官方的回复永远都是 不是我们的业务场景 不听不听就不听

**Comment by johanazhu** [comment]
陈小聪写的文章，https://juejin.cn/user/1838039174227006，在最新的 ant-design-pro 已经合并了 [alita/plugins](https://github.com/umijs/umi-presets-pro/blob/master/packages/umi-preset-pro/src/index.ts#L11)，所以这个问题你可以直接去问[xiaohuoni](https://github.com/xiaohuoni)

**Comment by 114xiaoyu** [comment]
你好，我是马晓宇，我已经收到你邮件

**Comment by qiaolina** [comment]
您好，遇到相同的问题，请问解决方案是什么呢？

**Comment by johanazhu** [comment]
> 您好，遇到相同的问题，请问解决方案是什么呢？

可以看看这个回复：https://github.com/alitajs/alita/issues/421
我的理解是，一环扣一环，你要想在 ant-design-pro 中开启 tabs，那么就需要下载依赖 umi-presets-pro，因为  umi-presets-pro 中有 [xiaohuoni](https://github.com/xiaohuoni) 的 keep-alive，而当 keep-alive 出现bug后并解决后，还需要 umi-presets-pro 升级包，并且 ant-design-pro 升级 umi-presets-pro 的包，总之很麻烦

**Comment by zozopen** [comment]
> 你好，我是马晓宇，我已经收到你邮件

你好大佬，我不小心误删了yarn.lock,也是需要开启tabs的，你的yarn.lock 可以发一份我吗 @114xiaoyu
