### ISSUE TITLE
🧐[question] 引入一个包报错webpackMissingModule 

### ISSUE THREAD

**Issue by hsbtr** [ant-design/ant-design-pro#10113]
### 🧐 问题描述 | Problem description

以这种方式导入`import { Swiper, SwiperSlide } from "swiper/react";` 会直接报错

### 💻 示例代码 | Sample code
```
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/swiper.less";
import "swiper/modules/navigation/navigation.less";
import "swiper/modules/pagination/pagination.less";

```

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/46487804/183397115-8d81966e-7718-4ef0-8dd6-93853cd4d767.png)
![image](https://user-images.githubusercontent.com/46487804/183397221-d155d1ad-8299-4d96-ab23-4d187a884c19.png)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
关掉mfsu把，这个库有点太老了，mfsu没办法帮你转化。

我建议你换个库，这么老的库维护力度可能有问题

**Comment by hsbtr** [comment]
> 关掉mfsu把，这个库有点太老了，mfsu没办法帮你转化。
> 
> 我建议你换个库，这么老的库维护力度可能有问题

感谢回复，已经换了库，查询过似乎pure ESM支持的原因
