### ISSUE TITLE
🐛 [BUG] ProTable里面的dateRange 月份显示英文, ConfigProvider也不知道放哪里

### ISSUE THREAD

**Issue by greenking19** [ant-design/ant-design-pro#10116]
### 🐛 bug 描述
我使用ant-pro生成的项目， 里面使用了antd-Pro-component
在`ProTable`的`Columns`里面的日期选择器 月份是英文的。  
这是ProTable里面的日期Column
```javascript
{
      title: '日期区间',
      valueType: 'dateRange',
      dataIndex: 'dateRange',
      hideInTable: true,
      initialValue: ['2021-01-01', initiaEndTime],
}
```
<img width="574" alt="image" src="https://user-images.githubusercontent.com/43332372/183667341-dacb1321-f3de-45b3-b2ec-d44c1855e2bc.png">
config里面也设置了中文
<img width="676" alt="image" src="https://user-images.githubusercontent.com/43332372/183667756-8a314156-7d03-4b6f-b8b1-a94f1cc36945.png">

我看到其他issue提到可以用`ConfigProvider`包裹 但是 我包裹单个组件不生效
全部我没找到根组件, `app.tsx`只是一些配置 没有根组件 不知道怎么去修复。
像我这种情况 要怎么去

### © 版本信息

- Ant Design Pro 版本:  @ant-design/pro-cli@2.1.5
- umi 版本: @3.5.20
- 浏览器环境: Chrome
- 开发环境 [e.g. mac OS]

**Comment by soeasyjx** [comment]
我也遇到了，怎么解决

**Comment by greenking19** [comment]
> 我也遇到了，怎么解决

无法解决

**Comment by drizzlesconsin** [comment]
[为什么时间类组件的国际化-locale-设置不生效？](https://ant.design/docs/react/faq#Date-related-components-locale-is-not-working)
