### ISSUE TITLE
🐛 [BUG]UMI4半成品是吧？跑起来什么也不能用是吧？KPI是吧？

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design-pro#10129]
跑起来就这样？黑色导航和左侧菜单栏都不能改。
玩呢？

![image](https://user-images.githubusercontent.com/11323678/184478179-9fd56636-d7b0-4b67-a475-fd0098d1de30.png)

**Comment by shanzhaozhen** [comment]
同样遇到这个问题，还有多语言也出问题了

**Comment by pkaq** [comment]
多看看文档再喷吧

**Comment by drizzlesconsin** [comment]
> 同样遇到这个问题，还有加载等待页、多语言、打包配置 targets: {ie: 11} 也有问题

https://github.com/umijs/umi/issues/8930

```ts
// .umirc.ts
export default {
  jsMinifier: 'terser',
  cssMinifier: 'cssnano'
}
```

**Comment by xiaoguikeji** [comment]
> 多看看文档再喷吧

来，秀上你的升级版本看看

**Comment by pkaq** [comment]
> > 多看看文档再喷吧
> 
> 来，秀上你的升级版本看看

9022年了还有伸手党

**Comment by pkaq** [comment]
> 同样遇到这个问题，还有加载等待页、多语言、打包配置 `targets: {ie: 11}` 也有问题

![image](https://user-images.githubusercontent.com/4537450/184849978-aab4ed29-be1b-45cd-9f39-d07681c105cf.png)
https://github.com/ant-design/ant-design-pro/releases/tag/v6.0.0-beta.1

**Comment by J-env** [comment]
> 多看看文档再喷吧

我是看着文档写的，用了 model 命名空间，就很奇怪，当前页面会执行其他页面的命名空间里的model，都还没进那个页面

**Comment by pkaq** [comment]
> 不知道你是不是失明患者，beta 几个字在安装的时候看不到吗？都跟你说 umi4 暂不支持全量，这是一个开源项目，你可以提出建议但是你无权要求命令别人做这做那，你要真觉得垃圾你自己写一个更好的不就好了？

就是惯的 别人免费给他用还唧唧歪歪 ；）

**Comment by chenshuai2144** [comment]
开源项目要有手才能用的，没有手建议买商业产品
