### ISSUE TITLE
🐛 [BUG]src/pages/document.ejs build并没有写入index.html

### ISSUE THREAD

**Issue by Waylon-Firework** [ant-design/ant-design-pro#10128]
src/pages/document.ejs build并没有写入index.html

没有看到任何跟document.ejs相关的文档。请问这个要如何生效。

**Comment by Waylon-Firework** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/95599645/184450181-696b2b39-ca60-420c-87a2-cdb48ea04300.png">

**Comment by drizzlesconsin** [comment]
如果是 Umi4 

### document.ejs 去哪了，如何自定义 HTML 模板
除了可以通过 配置项 注入外部 [script](https://umijs.org/docs/api/config#scripts) 、[css](https://umijs.org/docs/api/config#styles) 外，还可以使用项目级插件更灵活的修改 HTML 产物，参见：https://github.com/umijs/umi-next/issues/868#issuecomment-1151088426

https://github.com/umijs/umi/issues/8930
https://github.com/umijs/umi/issues/8525
