### ISSUE TITLE
🧐[问题 | question] PageContainer 默认不显示面包屑和标题该怎么处理？

### ISSUE THREAD

**Issue by houkunlin** [ant-design/ant-design-pro#10127]
### 🧐 问题描述 | Problem description

最近删除 node_modules 重新更新了一下依赖，然后发现之前的 PageContainer 页面不显示标题和面包屑了，这个应该要怎么处理？
现在的状态是它默认不显示，而我想要让它默认显示，应该如何去配置？

### 💻 示例代码 | Sample code

package.json
```
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0", // 实际 6.38.16
    "@ant-design/pro-list": "^1.21.62",
    "@ant-design/pro-table": "^2.71.0",
    "antd": "^4.20.0", // 实际 4.22.0
```

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：谷歌浏览器最新版

**Comment by mijaclan** [comment]
在defaultSettings.js 文件下添加属性
 pageTitleRender: false,    // 自定义页面标题的显示方法
 breadcrumbRender: false // 自定义面包屑的数据

参考文档：
https://procomponents.ant.design/components/layout/#prolayout
