### ISSUE TITLE
🧐[问题 | question] DVA Migration: How to migrate v4 src/models to v5

### ISSUE THREAD

**Issue by shobhitsinghal624** [ant-design/ant-design-pro#10120]
### 🧐 问题描述 | Problem description

We have a large list of models in our v4 ant-design-pro. How do we migrate them to the v5 useModel

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by shobhitsinghal624** [comment]
This part is missing in the doumentation:
https://pro.ant.design/docs/simple-model#dva-migration

If someone can provide a direction, I can work on a PR for this.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


补充说明：

该回复来自于 Github 的开发人员，向用户展示了如何为该问题提交 PR，让用户可以通过提供 changelog/TypeScript/documentation/test cases 等元素来解决此问题并为社区贡献代码。

**Comment by ferbueno** [comment]
Hi! Has anyone figured this one out? We too have a lot of V4 models and we'd like to migrate them. If possible, not all at once. Thanks!

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/max/dva

你仍然可以继续使用 dva 而不是迁移

**Comment by ferbueno** [comment]
@chenshuai2144 

I know we can still use `dva`, we just want to use the new models. Maybe updating the `dva` plugin to support a custom models path for autoloading would work? In that way a new directory can be created like `models/dva`. 

Thanks!
