### ISSUE TITLE
🐛 [BUG] "Error：Environment key 'es2022' is unknown" after run command `npm run lint`

### ISSUE THREAD

**Issue by kerwin-ly** [ant-design/ant-design-pro#10123]
### 🐛 bug 描述

执行命令`@ant-design/pro-cli`创建`umi4`项目后，安装依赖并修改某文件。执行`npm run lint`报错，如下：

```
Error: ../.eslintrc.js »/xxxx/node_modules/.pnpm/@umijs+max@4.0.8_4kelmht5p6seurkgrs525r3njq/node_modules/@umijs/max/eslint.js:
	Environment key "es2022" is unknown
```

### 📷 复现步骤 | Recurrence steps

1. 创建项目：pro create myapp (pro版本：3.0.0)

2. 选择umi4版本

3. 使用pnpm安装依赖（pnpm版本：7.5.0）

4. 修改任一ts文件

5. 执行`npm run lint`

### 🏞 期望结果 | Expected results

正常执行lint

### 💻 复现代码 | Recurrence code

https://github.com/kerwin-ly/umi-pro

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本: 4.0
- 浏览器环境: Chrome
- 开发环境: mac OS

### 🚑 其他信息

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/23304298/184271081-7a935992-2909-4a69-a8e1-c2b6aca3c92b.png">

我本来尝试直接去排查node_modules中的报错文件。但发现`node_modules`中的文件夹名称不是上图红框部分名字。而是`@umijs+max@4.0.12xxxxx`。不太清楚为什么？

在eslint仓库我发现了同样的issue，希望能对该问题有所帮助。https://github.com/eslint/eslint/issues/15580

**Comment by kerwin-ly** [comment]
Sry, it's my fault.

**Comment by p76** [comment]
你好，请问下是怎么解决的？
