### ISSUE TITLE
table-list的组件应该增加不需要多选的状态

### ISSUE THREAD

**Issue by xjchenhao** [ant-design/ant-design-pro#1012]
不一定所有的数据列表都需要多选操作，但是这个组件没有提供相关的“开关”api。希望官方能够增加一个。

> ps：我的工程是pull下来的，而且后续会一直保持跟官方代码同步的状态，所以这个最好是官方增加，省的后面需要解决冲突。
> 
> 我说的是这个组件（页面）：https://preview.pro.ant.design/#/list/table-list

不管有没有这个计划，希望开发团队回复一下，谢谢🙏

**Comment by afc163** [comment]
应该和这个 https://github.com/ant-design/ant-design-pro/issues/513 类似，来个 PR 支持 rowSelection 传入吧。

**Comment by xjchenhao** [comment]
我发现这个组件如果把rowSelection拿出去的话 就没剩下是么了。还不如直接用antd的Table组件😂
