### ISSUE TITLE
🐛 [BUG] ProTable设置固定列 在Mac上 touch手指滑动，经常出现网页会回退到上一页

### ISSUE THREAD

**Issue by J-env** [ant-design/ant-design-pro#10122]
### 🐛 bug 描述

根据Ant Design Pro文档，选择了 umi@4.0创建的项目

ProTable设置固定列 在Mac上 touch手指往右滑动（也就是表格内容 scrollLeft--），经常出现网页会回退到上一页

补充一点：
在表格右侧 列设置按钮，弹出层里面的内容上下滚动也会触发 网页会回退

下面有截图

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0-beta.1]
- umi 版本： 4.0.12
- 浏览器环境： 最新版谷歌
- 开发环境 [e.g. mac OS 11.2.3]

### 🚑 其他信息

<img width="995" alt="image" src="https://user-images.githubusercontent.com/25259920/184267018-6e33be1a-6a32-4d1f-8fdc-ed2225da08ed.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/25259920/184271802-5f70992a-2e59-4fc5-ae19-74689dc2b7d8.png">

**Comment by chenshuai2144** [comment]
这是mac的交互，你最好改下交互。。。我们也拿浏览器没办法
