### ISSUE TITLE
🧐[问题 | question] umi4版本的antd pro 主题没了

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/ant-design-pro#10125]
### 🧐 问题描述 | Problem description

最近打算升级umi4版本，拉取了模板感觉主题没了，怎么配置都弄不回去

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/29800728/184294969-2bdd6cef-f804-4dd2-9ac5-a373829ac0f6.png)

OS: windows10 

Node：6.x

浏览器 | browser：chrome

**Comment by drizzlesconsin** [comment]
花点时间配置下 token https://github.com/ant-design/pro-components/issues/4741

如果想要与之前一样，需要做些样式的修改。

**Comment by echoyl** [comment]
我再添加了这个依赖 "@ant-design/pro-layout": "6.38.13"  
layout样式就回到原来的样子了

**Comment by chenshuai2144** [comment]
不是很推荐锁包哦

**Comment by huangfenglan** [comment]
> 我再添加了这个依赖 "@ant-design/pro-layout": "6.38.13" layout样式就回到原来的样子了

我想问一下  你添加了这个依赖以后 navtheme设置了啥？是dark吗？
