### ISSUE TITLE
🐛 [BUG]v6 beta.1版本系统菜单（目录图标和菜单图标）存在明显没有左对齐问题

### ISSUE THREAD

**Issue by lovewinders** [ant-design/ant-design-pro#10124]
### 🐛 bug 描述
6.0.0-beta.1版本系统菜单（目录图标和菜单图标）存在明显没有左对齐问题

### 📷 复现步骤 | Recurrence steps

step 1:
```
git切换到tag [v6.0.0-beta.1](https://github.com/ant-design/ant-design-pro/tree/v6.0.0-beta.1)这个版本
```

step 2:
```
npm i
```

step 3
```
npm start
```

step 4:
```
浏览器输入地址：http://localhost:8001/welcome即可看到下图复现样式bug
```

### 🏞 期望结果 | Expected results

期望如同antd pro v5 系统左侧菜单一样：上下图标左对齐、上下文字左对齐；

### © 版本信息

- Ant Design Pro 版本: [6.0.0-beta.1]
- umi 版本: @umijs/max:[^4.0.0-rc.22]
- 浏览器环境 [常见]
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22837419/184271161-32f5181c-1ee0-4857-aae5-7870034b2028.png)

**Comment by joesdu** [comment]
可以在全局样式中添加如下内容来消除
```less
.ant-pro-menu-submenu {
  margin: 0px !important;
}
```

**Comment by joesdu** [comment]
你这个OpenAPI文档背后的那个背景是怎么搞得?教教我😋

**Comment by lovewinders** [comment]
> 可以在全局样式中添加如下内容来消除
> 
> ```css-less
> .ant-pro-menu-submenu {
>   margin: 0px !important;
> }
> ```

自定义全局样式覆盖该样式也行，最好是从原始组件解决该问题

**Comment by joesdu** [comment]
> 

目前我是这么解决的.因为我那天半夜调试自己写的接口的时候,发现菜单看着有点不对劲,然后就发现antd加了个margin,估计是新的设计方案,官方不会改.

**Comment by lovewinders** [comment]
> 你这个OpenAPI文档背后的那个背景是怎么搞得?教教我😋

我没有任何代码修改、只是download下master分支代码然后运行就有你说的背景

**Comment by joesdu** [comment]
> 

我抽空也试试.我用Cli创建的项目没有那个背景.我觉得那个背景还挺好看的.

**Comment by lovewinders** [comment]
> > 
> 
> 我抽空也试试.我用Cli创建的项目没有那个背景.我觉得那个背景还挺好看的.

用最新的

> > 
> 
> 目前我是这么解决的.因为我那天半夜调试自己写的接口的时候,发现菜单看着有点不对劲,然后就发现antd加了个margin,估计是新的设计方案,官方不会改.
我刚看F12定位了一下样式问题，没有额外追加任何样式的情况下，发现是菜单节点样式顺序覆盖冲突导致的，问题如下
![image](https://user-images.githubusercontent.com/22837419/184298411-3218f22f-60e6-419c-bde5-b0bb5b5c213f.png)

**Comment by joesdu** [comment]
> > 你这个OpenAPI文档背后的那个背景是怎么搞得?教教我😋
> 
> 我没有任何代码修改、只是download下master分支代码然后运行就有你说的背景

奇了怪了,我切换了beta6的tag代码,运行起来后没有这个背景,而且欢迎页面也和你的不一样

**Comment by chenshuai2144** [comment]
来个pr把

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


好的，我来为你补充一下这段话的具体用途和内容。

在开发中，出现问题时需要提供能够重新现场的示例，以便开发者们能够更快地找到问题所在。 `codesandbox.io` 是一个提供在线 IDE 的网站，用户可以在该网站上创建一个新的 sandbox 并且分享链接，让其他人来帮忙定位问题。这个内容的意思就是要求 `@lovewinders` 提供能够重现问题的在线示例，或者是一个最小化的 GitHub 仓库，以便于其他人能够更快地帮助你解决问题。同时也提供了一个示范的 GIF 动图，方便理解其含义。
