### ISSUE TITLE
🐛 [BUG] 数据流 model 命名空间bug，当前页会执行其他页面 命名空间model

### ISSUE THREAD

**Issue by J-env** [ant-design/ant-design-pro#10131]
### 🐛 bug 描述

我在登录页，首页（也就是当前页）会执行其他页面的 model.ts 默认导出的hook

### 📷 复现步骤 | Recurrence steps

1. 创建 src/pages/dashboard/demo/model.ts
```js
// dashboard/demo/model.ts
export default () => {
  const [value, setValue] = useState('')
  
  console.log(value, 'dashboard.demo.model')
 
  return { value };
};
```
2. 创建 src/pages/dashboard/demo/index.tsx
```tsx
// dashboard/demo/index.tsx
const Demo: React.FC = () => {
  const {value} = useModel('dashboard.demo.model')
  
  return <div>demo {value}</div>
}
export default Demo
```
3.进登录页 刷新页面，dashboard/demo/model.ts 会打印
4.登录后 点击左侧菜单 进入 /dashboard/demo，打印不会执行了，需要刷新页面

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0-beta.1]
- umi 版本 4.0+
- 浏览器环境 最新谷歌
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
model.ts 只有在 init时候会执行一下，剩下的时候需要用 useEffect 来触发执行的，不然性能会太差
