### ISSUE TITLE
🧐[问题 | question] 有关antd pro中的axios rest call问题

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design-pro#10135]
### 🧐 问题描述 | Problem description

项目的后台用JWT做authentication。简单的说就是用户/user/login/account登录成功后，后台发给UI的response中包含JWT token.然后UI以后发给后台的rest call,需要加上http request header: authorization BEARAR $Token。

项目移植到antd以前，登录成功后调用如下语句，axios就加了全局的interceptor，所有的后续的rest call，axios都会自动加上

```
request header
  import axios from axios
  const interceptorGlobal = axios.interceptors.request.use((config) => {
    config.headers.authorization ='Bearer ' + token;
    return config;
  });
```

项目移植到antd以后，发现src\.umi\plug-request\request.ts中发送消息用的是requestInstanse (line 143)。如果有requestInstance就使用，如果没有requestInstance就新建一个。在axios上直接加载的interceptor不再起作用了，只能在requestInstance上加载interceptor。

于是修改以上代码为：

```
  import { getRequestInstance } from '@/.umi/plugin-request/request';
  const interceptorRequest = getRequestInstance().interceptors.request.use((config) => {
    config.headers.authorization = createJWTToken(token);
    return config;
  });
```

代码在happy flow可以正常工作。

但是用户不能在浏览器上点refresh按钮了。一旦点击refresh按钮，那么request.ts里的requestInstance将是undefine，request.ts新建一个requestInstance。在前面加载的interceptor无效了，http header里面也就没有JWT token了，antd自动回到login页面。

这应该是个通用问题：只要用户在antd的页面上点击refresh按钮（或者手动在地址栏编辑URL)，就会新建一个axios requestinstance，原来requestinstance上的interceptor等配置就会失效，造成JWT等信息失效。

希望antd能提供解决方案，能让axios interceptor活过refresh按钮。(比如request.ts从initialstate里检查有没有需要自动加载的http header，再比如把reqeustInstance保存到initialstate，再比如...)

### 💻 示例代码 | Sample code

如上

### 🚑 其他信息 | Other information

OS: windows

Node：18.2

浏览器 | browser：chrome

**Comment by fengertao** [comment]
请问有方案吗？

**Comment by chenshuai2144** [comment]
你在 utils 里面定义一个统一的请求类，不要每次用的时候才新建应该就可以了
