### ISSUE TITLE
🧐[问题 | question] 一个不太明白作用的空节点和如何设置

### ISSUE THREAD

**Issue by chang0022** [ant-design/ant-design-pro#10134]
### 🧐 问题描述 | Problem description

脚手架好像是在用 6.0版本的？其中有一个节点的颜色影响了正常使用，文档中没有找到对应的修改方式。classname 里面有 hash，想全局覆盖但不确定这个 hash 是否会变更。

```
.ant-design-pro-layout-d08s5k {
    pointer-events: none;
    position: fixed;
    overflow: hidden;
    top: 0;
    left: 0;
    z-index: 0;
    height: 100%;
    width: 100%;
    background: linear-gradient(#fff, #f7f8fa 28%);
}
```

### 🚑 其他信息 | Other information

<img width="600" alt="image" src="https://user-images.githubusercontent.com/6067222/184592732-d9dc4122-ea42-48dc-bded-286533f9cd6a.png">

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
升级到新版本，有了稳定的css 了
