### ISSUE TITLE
🐛 [BUG] Should have a queue. This is likely a bug in React. Please file an issue 

### ISSUE THREAD

**Issue by Frankenstein4** [ant-design/ant-design-pro#10133]
![90d69db13df34fb6511ddd5b9de6900](https://user-images.githubusercontent.com/49185246/184576072-405a9929-0368-4a1c-b6aa-5114e60971ec.jpg)

自从用了你家的antd pro v5，我在页面上每次加一个useState，就报错这个，v4不会，这到底咋回事啊，并且我是在菜单父组件加的，也不是在子组件，这就是一个普通的父组件，我在CodeSandbox把这个代码粘贴过去并不会报错，很尴尬我还提到react那边去了。但是我觉得还是你们这个v5项目的bug、

https://github.com/facebook/react/issues/25063

**Comment by Frankenstein4** [comment]
![unY4qKBtQH](https://user-images.githubusercontent.com/49185246/184576387-c43f1dbb-56c9-4593-b1e4-3e957ef20e11.jpg)
这样

**Comment by chenshuai2144** [comment]
https://stackoverflow.com/questions/65548028/error-should-have-a-queue-this-is-likely-a-bug-in-react-please-file-an-issue

看这里，一般是hooks没用好导致的
