### ISSUE TITLE
ProTable 当列valueType是select或cascader,且选项是多选的时候会报Each child in a list should have a unique "key" prop🐛 [BUG]

### ISSUE THREAD

**Issue by echoyl** [ant-design/ant-design-pro#10141]
### 🐛 bug 描述
如题

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 4.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21699984/184833646-19f87082-d572-42ae-b457-4710cdf9c293.png)

**Comment by chenshuai2144** [comment]
你的数据没有设置value把，默认是拿value当key的

**Comment by miaoziwei** [comment]
是怎么实现valueType是select时可以多选的

**Comment by chenshuai2144** [comment]
filedProps 里面可以设置的
