### ISSUE TITLE
浏览器控制台报错 Uncaught Error: Incompatible SockJS! Main site uses: "1.5.0", the iframe: "1.6.1".   iframe-bootstrap.js:72 

### ISSUE THREAD

**Issue by MyBaymax** [ant-design/ant-design-pro#10145]
浏览器控制台报错 Uncaught Error: Incompatible SockJS! Main site uses: "1.5.0", the iframe: "1.6.1".   iframe-bootstrap.js:72 
项目可以正常运营，功能也正常。不知道怎么解决这个错误，求帮助

**Comment by chenshuai2144** [comment]
看起来是你用的某个库不行了，版本不匹配，用 代码分析 分析一下
