### ISSUE TITLE
🧐[问题] 为什么样式都存在3份相同的内容

### ISSUE THREAD

**Issue by J-env** [ant-design/ant-design-pro#10149]
### 🧐 问题描述 | Problem description

使用 ant-design-pro@6.0.0-beta.1，umi@4.0+，什么都没改，
我以为只有开发环境css都是3份，打包后还是3份一模一样的内容

### 🚑 其他信息 | Other information
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/25259920/185529259-04d02d34-2c6f-463e-bd33-e7a632e30b0c.png">

OS: Mac OS

Node：v14.20.0

浏览器 | browser：最新谷歌

**Comment by chenshuai2144** [comment]
antd的多次引用吧，mfsu 打开的确会有这个问题，build之后应该是没有的
