### ISSUE TITLE
🧐[问题 | question]Protable的横向滚动条如何浮动在页面底部?

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#10142]
### 🧐 问题描述 | Problem description

Protable当设置scroll={x: ***}后会出现横向滚动条, 此时如果每页数据量多,表格高度就会向下延伸,此时如果想看表格右侧的内容就需要横向滑动表格, 但是滚动条固定在表格最底部, 需要先滑动页面到最底部, 横向拖动滚动条之后再上划的起始位置, 在操作上会非常麻烦....   
而设置了scroll={y: xxx}后因为页面高度不固定, 当页面高度过大或过小时, 表格占据整个页面的区域是固定的, 会造成整体布局不好看...  
因此有没有一种方法或者属性, 可以控制滚动条(最好带上分页器)使其浮动在页面(屏幕可见区域)底部, 方便操作?

### 💻 示例代码 | Sample code
```
<ProTable
         ...
        scroll={{ x: 4000 }}
/>
```

### 🚑 其他信息 | Other information
![飞书20220817-100721](https://user-images.githubusercontent.com/13959162/185018856-cae4090d-197f-4945-a0fa-9d6d63cf7746.jpg)

OS:  windows 11

Node：v16.16.0

浏览器 | browser：chrome / edge

**Comment by chenshuai2144** [comment]
这个很难实现，因为渲染的区域不一样，一个简单的办法是把table的width设置的很长，但是体验会很差

另外不建议玩这种花活
