### ISSUE TITLE
dispatch effects

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#1014]
dispatch().then(data => console.log(data))
dispatch的effects返回的promise中 如何带值，谢谢

**Comment by TigerBill2016** [comment]
effects 中直接return就好了，之前试过怎么不行

**Comment by chenshuai2144** [comment]
和这个差不多
https://github.com/reactjs/redux/issues/1251

**Comment by TigerBill2016** [comment]
谢谢啦
