### ISSUE TITLE
V5 navTheme 设置dark不生效

### ISSUE THREAD

**Issue by xiaqingping** [ant-design/ant-design-pro#10151]
### 💻 示例代码 | Sample code
import { Settings as LayoutSettings } from '@ant-design/pro-components';

const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'dark',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: '',
  pwa: false,
  iconfontUrl: '',
};

export default Settings;

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by pkaq** [comment]
这个似乎要通过Token去更改才行

**Comment by wangJacker** [comment]
的确不生效使用的pro-cli脚手架 生成的项目

**Comment by wangJacker** [comment]
https://github.com/ant-design/ant-design-pro/issues/10112

**Comment by xiaqingping** [comment]
> 使用token可以实现，但是build似乎不生效

**Comment by chenshuai2144** [comment]
没有dark模式了，要用新的token来更改
