### ISSUE TITLE
🧐[问题 | question] EditableProTable  onsave触发内存泄漏   Can't perform a React state update on an unmounted component. 

### ISSUE THREAD

**Issue by MINGLIANG98** [ant-design/ant-design-pro#10152]
### 🧐 问题描述 | Problem description
EditableProTable  onSave保存的时候出发react内存泄漏警告 Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function

### 💻 示例代码 | Sample code

``import type { ProColumns } from '@ant-design/pro-components';
import { EditableProTable, ProCard, ProFormField, ProFormRadio } from '@ant-design/pro-components';
import React, { useState } from 'react';

const waitTime = (time: number = 100) => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(true);
        }, time);
    });
};

type DataSourceType = {
    id: React.Key;
    title?: string;
    readonly?: string;
    decs?: string;
    state?: string;
    created_at?: string;
    update_at?: string;
    children?: DataSourceType[];
};

const defaultData: DataSourceType[] = [
    {
        id: 624748504,
        title: '活动名称一',
        readonly: '活动名称一',
        decs: '这个活动真好玩',
        state: 'open',
        created_at: '2020-05-26T09:42:56Z',
        update_at: '2020-05-26T09:42:56Z',
    },
    {
        id: 624691229,
        title: '活动名称二',
        readonly: '活动名称二',
        decs: '这个活动真好玩',
        state: 'closed',
        created_at: '2020-05-26T08:19:22Z',
        update_at: '2020-05-26T08:19:22Z',
    },
];

export default () => {
    const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
    const [dataSource, setDataSource] = useState<DataSourceType[]>([]);
    const [position, setPosition] = useState<'top' | 'bottom' | 'hidden'>('bottom');

    const columns: ProColumns<DataSourceType>[] = [
        {
            title: '活动名称',
            dataIndex: 'title',
            tooltip: '只读，使用form.getFieldValue获取不到值',
            formItemProps: (form, { rowIndex }) => {
                return {
                    rules: rowIndex > 1 ? [{ required: true, message: '此项为必填项' }] : [],
                };
            },
            // 第一行不允许编辑
            editable: (text, record, index) => {
                return index !== 0;
            },
            width: '15%',
        },
        {
            title: '活动名称二',
            dataIndex: 'readonly',
            tooltip: '只读，使用form.getFieldValue可以获取到值',
            readonly: true,
            width: '15%',
        },
        {
            title: '状态',
            key: 'state',
            dataIndex: 'state',
            valueType: 'select',
            valueEnum: {
                all: { text: '全部', status: 'Default' },
                open: {
                    text: '未解决',
                    status: 'Error',
                },
                closed: {
                    text: '已解决',
                    status: 'Success',
                },
            },
        },
        {
            title: '描述',
            dataIndex: 'decs',
            fieldProps: (from, { rowKey, rowIndex }) => {
                if (from.getFieldValue([rowKey || '', 'title']) === '不好玩') {
                    return {
                        disabled: true,
                    };
                }
                if (rowIndex > 9) {
                    return {
                        disabled: true,
                    };
                }
                return {};
            },
        },
        {
            title: '活动时间',
            dataIndex: 'created_at',
            valueType: 'date',
        },
        {
            title: '操作',
            valueType: 'option',
            width: 200,
            render: (text, record, _, action) => [
                <a
                    key="editable"
                    onClick={() => {
                        action?.startEditable?.(record.id);
                    }}
                >
                    编辑
                </a>,
                <a
                    key="delete"
                    onClick={() => {
                        setDataSource(dataSource.filter((item) => item.id !== record.id));
                    }}
                >
                    删除
                </a>,
            ],
        },
    ];

    return (
        <>
            <EditableProTable<DataSourceType>
                rowKey="id"
                headerTitle="可编辑表格"
                maxLength={5}
                scroll={{
                    x: 960,
                }}
                recordCreatorProps={
                    position !== 'hidden'
                        ? {
                              position: position as 'top',
                              record: () => ({ id: (Math.random() * 1000000).toFixed(0) }),
                          }
                        : false
                }
                loading={false}
                toolBarRender={() => [
                    <ProFormRadio.Group
                        key="render"
                        fieldProps={{
                            value: position,
                            onChange: (e) => setPosition(e.target.value),
                        }}
                        options={[
                            {
                                label: '添加到顶部',
                                value: 'top',
                            },
                            {
                                label: '添加到底部',
                                value: 'bottom',
                            },
                            {
                                label: '隐藏',
                                value: 'hidden',
                            },
                        ]}
                    />,
                ]}
                columns={columns}
                request={async () => ({
                    data: defaultData,
                    total: 3,
                    success: true,
                })}
                value={dataSource}
                onChange={setDataSource}
                editable={{
                    type: 'multiple',
                    editableKeys,
                    onSave: async (rowKey, data, row) => {
                        console.log(rowKey, data, row);
                        await waitTime(2000);
                    },
                    onChange: setEditableRowKeys,
                }}
            />
            <ProCard title="表格数据" headerBordered collapsible defaultCollapsed>
                <ProFormField
                    ignoreFormItem
                    fieldProps={{
                        style: {
                            width: '100%',
                        },
                    }}
                    mode="read"
                    valueType="jsonCode"
                    text={JSON.stringify(dataSource)}
                />
            </ProCard>
        </>
    );
};``

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/67278171/185579814-c6101e2f-2b4c-42f3-a4e1-8409ae35de54.png)
![image](https://user-images.githubusercontent.com/67278171/185579920-a895dc2f-2c53-46c5-936a-a069535fa743.png)

OS: windows11

Node：v16.14.2

浏览器 | browser：104.0.5112.81（正式版本） （64 位）

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案 | Solution

首先，这个警告是表示，React 在已经被卸载或关闭的组件中进行状态更新操作，这么做是没有意义的，这个操作被认为是一次内存泄漏，在应用程序中可能会导致性能问题。

在你的情况下，原因是，页面上有一些异步任务可能在组件被卸载后依旧没有完成。

#### 1. 取消所有的 subscription 和 task

你的组件有一些带有`async`关键字的异步请求：`request`函数和`onSave`函数。为了避免内存泄漏可以使用`useEffect`来进行清除。

```javascript
import React, { useState, useEffect } from 'react';

export default () => {
    const [editableKeys, setEditableRowKeys] = useState<React.Key[]>([]);
    const [dataSource, setDataSource] = useState<DataSourceType[]>([]);
    
    // useEffect 清除 subscriptions 和 tasks
    useEffect(() => {
        return () => {
            // 取消 request 函数中的订阅或异步任务
            // ...

            // 取消 onSave 中的订阅或异步任务
            // ...
        }
    }, []);

    // ...
```

#### 2. 使用取消请求库来解决问题

由于只是一个用于测试的Demo，代码中不涉及true Api 的请求情况，因此可以采用 axios 实例化后返回的 CancelToken机制 来解决问题吗，即在 componentWillUnmount中取消所有的请求。

- 基础 CancelToken 示例

```javascript
import axios from 'axios';
import { CancelToken } from 'axios';

class TestCancelToken extends React.Component {

    state = {
        isCancel: false,
        result: {},
    }

    componentDidMount() {
        let cancelRes;
        axios
            .get('https://api.example.com/getData', {
                cancelToken: new CancelToken((c)=> {
                    console.log('取消请求', c);
                    cancelRes = c;
                })
            })
            .then((res) => {
                console.log(res);
                this.setState({
                    isCancel: false,
                    result: res
                });
            })
            .catch((err)=>{
                if(axios.isCancel(err)) {
                    console.log('已取消请求');
                }else{
                    console.error(err);
                }
            });

            // 成功或者失败时取消请求
            cancelRes();

            this.setState({isCancel: true});

    }


    componentWillUnmount() {
        console.log('componentWillUnmount 取消请求')
        // 在 componentWillUnmount 中取消请求
        // 使用 this.cancelSource 传递 CancelToken 的实例
        this.cancelSource.cancel()
    }

    render() {
        return <div>...</div>
    }

}
```

- 处理 onCancel 回调

可以添加一个自定义 onCancel 事件来清除任务订阅以及异步操作。

```typescript
const EditableTable: React.FC<Props> = (props) => {
    // ...

    const [ cancelSource, setCancelSource ] = useState(axios.CancelToken.source());

    // 监听 onCancel 事件， 如果发送 api 请求时，取消了 ， 发出 warning
    // 如果其他情况，即不是发起异步请求导致的取消，那么就忽略这个warning
    useEffect(() => {
        cancelSource &&
            (cancelSource.token.reason ?? Promise.resolve(true)).then((scheduleResolve) => {
                !scheduleResolve && warning(true, "CancelationToken doesn't work, be sure it works!");
            });
    }, [cancelSource]);

    // 每次请求前更新 CancelToken 的实例于 state 中
    const request = (params: any) => {
        console.log('qian',cancelSource);
        setCancelSource(axios.CancelToken.source());
        console.log('hou',cancelSource);
        return request('/api/editable/getList', {
            ...params,
            cancelToken: cancelSource.token,
        });
    };

    const onSave = async (rowKey, data, row) => {
        const response = await saveSomeData(data);
        // 取消请求
        cancelSource.cancel();
        // 更新数据源中的数据
        setDataSource(dataSource.map((item) => item.id === rowKey ? { ...item, ...data } : item));
        // ...
    };

    // ...

    useEffect(() => {
        return () => {
            // 取消请求
            cancelSource.cancel();
        }
    }, []);

    return (
       // ...
    );
};
```

解决内存泄漏的问题有很多方案，本文只提供其中的一些思路，具体解决方案需要根据实际情况而论。
