### ISSUE TITLE
🧐[问题 | 新项目navTheme 修改位dark 和primaryColor不起作用

### ISSUE THREAD

**Issue by zhangXiaolizi** [ant-design/ant-design-pro#10150]
### 🧐 问题描述 | Problem description

1、yarn create umi my-app
2、选择 Ant Design Pro
3、添加defaultSetting，包含navTheme ， layout 和 primaryColor （见下图）
4、在app.ts中进行设置

但是页面没有黑色模式的任何效果

### 💻 示例代码 | Sample code

import { Settings as LayoutSettings } from "@ant-design/pro-components";

const settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'dark',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'top',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: false,
  colorWeak: false,
  title: '管理后台',
  pwa: false,
  logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  iconfontUrl: '',
};

export default settings;

import routes from 'config/routes';
import defaultSetting from '../config/defaultSetting'
// 运行时配置

// 全局初始化数据配置，用于 Layout 用户信息和权限初始化
// 更多信息见文档：https://next.umijs.org/docs/api/runtime-config#getinitialstate
export async function getInitialState(): Promise<{ name: string }> {
  return { name: '管理员' };
}

export const layout = () => {
  
  return {
    //logo地址
    logo: 'https://img.alicdn.com/tfs/TB1YHEpwUT1gK0jSZFhXXaAtVXa-28-27.svg',
    logout: (state: any) =>{
      console.log(state);
    },
    ...defaultSetting
  };
};

### 🚑 其他信息 | Other information

<img width="653" alt="bug" src="https://user-images.githubusercontent.com/15603295/185530893-d91a06ba-4320-4283-8c74-dd73040a2794.png">
<img width="992" alt="bug2" src="https://user-images.githubusercontent.com/15603295/185530900-e82b3376-89a8-4ae3-9efc-4a78b482641e.png">
<img width="921" alt="bug3" src="https://user-images.githubusercontent.com/15603295/185530901-69b88e3e-c916-4eb3-9d69-41e460dde662.png">
<img width="810" alt="bug4" src="https://user-images.githubusercontent.com/15603295/185530908-eb9025ee-fcf3-42be-b472-a7aa8c4e8e23.png">

<img width="810" alt="bug4" src="https://user-images.githubusercontent.com/15603295/185530913-973afbe6-75f4-4dd6-8391-80828e3b8e3f.png">

OS:
mac
Node：
v16.16.0
浏览器 | browser：
chrome  v16.16.0

**Comment by mushroomlb** [comment]
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
      layout:'top',
       ...
  }
}

**Comment by kokman** [comment]
我也遇到同样的问题，请问解决了吗？谢谢！

**Comment by huangfenglan** [comment]
请问解决了吗？我也遇到了相同的问题

**Comment by hfpp2012copy** [comment]
不是 dark 是 readDark https://www.qiuzhi99.com/playlists/antdprov5latest.html

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供解决方案。确实，在 Ant Design Pro 5 中，不是使用 'dark' 的值来设置暗黑主题，而是使用 'realDark'。所以可以尝试在设置中将 'navTheme' 的值改为 'realDark'，如下所示：

```
const settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'realDark',
  primaryColor: '#1890ff',
  layout: 'top',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: false,
  colorWeak: false,
  title: '管理后台',
  pwa: false,
  logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  iconfontUrl: '',
};

export default settings;
```

此外，也可以查看 pro-components 的官方文档来了解更多有关设置的信息：

https://procomponents.ant.design/components/layout-cn/
