### ISSUE TITLE
查询列表写死一定要解析data

### ISSUE THREAD

**Issue by NotExistUserName** [ant-design/ant-design-pro#10157]
不是很明白为什么ProTable一定是写死固定解析data才能展示列表数据，不知是我还没理解整个结构，还是本是如此，因为目前后台一般采用微服务架构，一般会有统一的网关，列表结构不一定能响应data字段，特别是将列表数据直接填充在data中。
像目前响应这种结构，就不报错，但列表没有数据，后面模拟demo返回respData->data立马展示数据：
{
   "respCode": 200,
   "respMsg": "操作成功",
   "respData" : data
}
刚学习，可能了解的不够透彻，麻烦知道的大佬给个解答，谢谢。

**Comment by jiangzm** [comment]
文档也不看一上来就喷，合适吗
```
<ProTable<DataType, Params>
  // params 是需要自带的参数
  // 这个参数优先级更高，会覆盖查询表单的参数
  params={params}
  request={async (
    // 第一个参数 params 查询表单和 params 参数的结合
    // 第一个参数中一定会有 pageSize 和  current ，这两个参数是 antd 的规范
    params: T & {
      pageSize: number;
      current: number;
    },
    sort,
    filter,
  ) => {
    // 这里需要返回一个 Promise,在返回之前你可以进行数据转化
    // 如果需要转化参数可以在这里进行修改
    const msg = await myQuery({
      page: params.current,
      pageSize: params.pageSize,
    });
    return {
      data: msg.result,
      // success 请返回 true，
      // 不然 table 会停止解析数据，即使有数据
      success: boolean,
      // 不传会使用 data 的长度，如果是分页一定要传
      total: number,
    };
  }}
/>
```

**Comment by NotExistUserName** [comment]
可能表达有问题，根本没有喷的意思，对开源作者都是保持崇高的敬意。
后端狗，没搞过前端，可能问的方式不对。文档也确实看不懂。就是想找一个开箱即用的模板，能模仿着写就成。
然后我模仿RuleList的写法。
能展示数据的写法：
type WorkerList = {
    data?: WorkerListItem[];
    /** 列表的内容总数 */
    total?: number;
    success?: boolean;
  };
只有这样列表才展示数据。但按照后端返回体一般是这样的
不能展示数据的写法（也不报错，在oneapi.json中我也进行了定义）：
type RespData = {
    current: number;
    pageSize: number;
    total: string;
    dataList?: WorkerListItem[];
  }

  type WorkerList = {
    respCode: number;
    /** 列表的内容总数 */
    respMsg: string;
    respData: RespData;
  };
现在有两个问题：
1、如果说自定义返回体应该怎么写呢？
2、分页参数必须用current吗，一般都是定义为pageNum

**Comment by darkfiredarkhalo** [comment]
- 1、如果说自定义返回体应该怎么写呢？  
[postData](https://procomponents.ant.design/components/table/#protable)  
![image](https://user-images.githubusercontent.com/13959162/186052480-8a391671-427a-4958-a21d-2bf1d39e1d50.png)  
- 2、分页参数必须用current吗，一般都是定义为pageNum  
是的, 但是`request`中可以拿到原始参数, 然后构造成自己需要的参数


> 文档也不看一上来就喷，合适吗 https://procomponents.ant.design/components/table/#request
> 
> ```
> <ProTable<DataType, Params>
>   // params 是需要自带的参数
>   // 这个参数优先级更高，会覆盖查询表单的参数
>   params={params}
>   request={async (
>     // 第一个参数 params 查询表单和 params 参数的结合
>     // 第一个参数中一定会有 pageSize 和  current ，这两个参数是 antd 的规范
>     params: T & {
>       pageSize: number;
>       current: number;
>     },
>     sort,
>     filter,
>   ) => {
>     // 这里需要返回一个 Promise,在返回之前你可以进行数据转化
>     // 如果需要转化参数可以在这里进行修改
>     const msg = await myQuery({
>       page: params.current,
>       pageSize: params.pageSize,
>     });
>     return {
>       data: msg.result,
>       // success 请返回 true，
>       // 不然 table 会停止解析数据，即使有数据
>       success: boolean,
>       // 不传会使用 data 的长度，如果是分页一定要传
>       total: number,
>     };
>   }}
> />
> ```

这位兄台的回复中有示例  


我也是刚接触这个UI框架, 上来就是最新版的, 好像还是有问题, 大体上不影响使用
