### ISSUE TITLE
🐛 [BUG]菜单收缩状态下，选中三级菜单最末级菜单，然后再展开，最末级菜单一直显示不消失

### ISSUE THREAD

**Issue by lizibeite** [ant-design/ant-design-pro#10159]
### 🐛 bug 描述

有三级菜单的时候,，在收缩时选中三级菜单最末级菜单，然后在展开，最末级菜单一直显示不消失

### 📷 复现步骤 | Recurrence steps

![giff](https://user-images.githubusercontent.com/16713357/185874903-ddfdc286-1668-401d-9904-bd390a1e30ce.gif)

### 🏞 期望结果 | Expected results
三级菜单展开与收缩，末级菜单都消失

### © 版本信息

- Ant Design Pro 版本: 5.2.0
- umi 版本:3.5.0
- 浏览器环境:Google Chrome(版本 104.0.5112.82（正式版本） （64 位）)
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16713357/185875201-1474482c-4a42-4467-88d9-5f9726672e85.png)

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/10159?notification_referrer_id=NT_kwDOAHzrKLI0MjQxOTQ1NzYzOjgxODY2NjQ&notifications_query=repo%3Aant-design%2Fant-design-pro%20is%3Aunread
