### ISSUE TITLE
🧐[问题 | question]proxy代理无法获得后端数据，总是返回html页面

### ISSUE THREAD

**Issue by Hannahfall** [ant-design/ant-design-pro#10153]
### 🧐 问题描述 | Problem description

 把相关issues都看了一遍，返回的html应该是404页面吧。但看了一下proxy和发送请求的格式感觉都没啥问题，启动的时候也no-mock了。
把后端域名和请求拼成url发送是可以拿到数据的，但走代理就不行。

### 💻 示例代码 | Sample code

proxy配置：
![image](https://user-images.githubusercontent.com/51750841/185672272-62bfed2d-d6fb-476f-908d-1175b38de037.png)

request发送请求：
![image](https://user-images.githubusercontent.com/51750841/185672462-8dffd929-ee5b-4a3c-90b9-fda2fbd2b208.png)
![image](https://user-images.githubusercontent.com/51750841/185672504-c69c1ad8-9f5b-4a22-9ef3-3b0b6797e4e4.png)

直接拼接url是可以拿到后端数据的：
![image](https://user-images.githubusercontent.com/51750841/185672598-36c17fec-51f7-481b-830c-c4fd2dbe3a7b.png)

**Comment by Hannahfall** [comment]
没有人理我，你以为我还会在乎吗？我在昆仑山练了六年的剑，我的心早就和昆仑山的雪一样冷了。我在大润发杀了十年的鱼，我以为我的心早已跟我的刀一样冷了，可是当我看文档看得目眩、搜索谷歌搜得头痛，眼泪瞬间如黄果树瀑布般飞流直下，划过我的脸庞，打湿了我的拖鞋，脚丫子都变得酸涩，只想说，能不能不要在这种傻问题上出bug？

**Comment by Hannahfall** [comment]
![image](https://user-images.githubusercontent.com/51750841/185674498-6ea20e24-5b5a-4ccb-880f-54b65b5811fc.png)

**Comment by Hannahfall** [comment]
![image](https://user-images.githubusercontent.com/51750841/185674554-7b434b6b-0943-463e-8083-41a5c3b8872a.png)

**Comment by Hannahfall** [comment]
搞不定问题，你以为我还会在乎吗？我在昆仑山练了六年的剑，我的心早就和昆仑山的雪一样冷了。我在大润发杀了十年的鱼，我以为我的心早已跟我的刀一样冷了，可是当我看文档看得目眩、搜索谷歌搜得头痛，眼泪瞬间如黄果树瀑布般飞流直下，划过我的脸庞，打湿了我的拖鞋，脚丫子都变得酸涩，只想说，能不能不要在这种傻问题上出bug？
![image](https://user-images.githubusercontent.com/51750841/185674831-5a4ce99d-fb3d-4e7d-9f0f-8b83e96c3833.png)

**Comment by kungege** [comment]
为什么你能确认不是自己代码的问题？你这也不是沟通问题的态度。

**Comment by Hannahfall** [comment]
> 为什么你能确认不是自己代码的问题？你这也不是沟通问题的态度。
确实，抱歉啊，提问那天晕头转向了

**Comment by kungege** [comment]
一般proxy代理是用来处理浏览器端跨域的，然而你的后端服务是你本地起的，用不到proxy做代理

**Comment by Hannahfall** [comment]
> 一般proxy代理是用来处理浏览器端跨域的，然而你的后端服务是你本地起的，用不到proxy做代理

嗯嗯，多谢。我应该多钻研一下的，谢谢你啦。
