### ISSUE TITLE
🐛 [BUG] max build后的代码，pluginmanager执行时为空

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design-pro#10156]
### 🐛 bug 描述

以下项目用antd pro v5搭建
https://github.com/fengertao/SudokuMasterV3/tree/master/SudokuMasterUI

如果用yarn start:dev启动，则可以正常执行，显示登录页面，输入账户密码后，点击登录进入系统(后台的代码在https://github.com/fengertao/SudokuMasterV3/tree/master/SudokuMasterServ)

如果做生产部署，执行 yarn:deploy (rm -rf dist && max build && rm -rf ../SudokuMasterServ/src/main/resources/static && cp -r dist ../SudokuMasterServ/src/main/resources/static)，然后编译启动后台，可以显示登陆页面，但输入账户密码后，点击登录报错：
TypeError: Cannot read properties of null (reading 'applyPlugins')
    at dn (umi.a854bfc6.js:1099:5368)
    at Cn (umi.a854bfc6.js:1099:5498)
    at w (umi.a854bfc6.js:1099:46552)
    at p__User__Login__index.dfb9a4e1.async.js:1:1975
    at x (umi.a854bfc6.js:1200:3106)
    at Generator._invoke (umi.a854bfc6.js:1200:2843)
    at Generator.next (umi.a854bfc6.js:1200:3468)
    at h (umi.a854bfc6.js:1197:90287)
    at u (umi.a854bfc6.js:1197:90484)

加了一下log
发现是在src/.umi/plugin-request/request.ts第135行
  config = getPluginManager().applyPlugins({
这里的getPluginManager()返回null

可以合理猜测，yarn start:dev启动的项目，plugin.ts中的pluginManager被初始化了。而yarn deploy打包的项目，plugin.ts中的pluginManager没有被初始化导致错误。

### 📷 复现步骤 | Recurrence steps

如上所述

### 🏞 期望结果 | Expected results

yarn deploy打包的项目，request.ts中调用的getPluginManager()返回一个打包好的pluginManager

### 💻 复现代码 | Recurrence code

https://github.com/fengertao/SudokuMasterV3/tree/master/SudokuMasterUI

### © 版本信息

- Ant Design Pro 版本: 5
- umi 版本 4.0.12
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] windows11 + nodejs v18.7.0

**Comment by chenshuai2144** [comment]
applyPlugins 是什么东西？

**Comment by fengertao** [comment]
https://github.com/umijs/umi/blob/master/packages/plugins/src/request.ts#L157

umi里面的这句话在antpro里返回为null

**Comment by chenshuai2144** [comment]
测试用例看起来没问题，是不是依赖更新有问题

**Comment by 17876005786** [comment]
请问这个错误这么解决  在生产环境下

**Comment by jaikydota** [comment]
我也遇到这个错误，大家怎么解决的？
