### ISSUE TITLE
ant design pro安装脚手架的过程中无法安装成功，报错

### ISSUE THREAD

**Issue by Mu-99** [ant-design/ant-design-pro#1016]
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\part
ition.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\part
ition.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\pluc
k.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\pluc
k.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ish.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ish.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ishBehavior.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ishBehavior.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ishLast.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ishLast.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ishReplay.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\publ
ishReplay.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\race
.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\race
.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\redu
ce.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\redu
ce.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\repe
at.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\repe
at.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\repe
atWhen.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\repe
atWhen.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\retr
y.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\retr
y.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\retr
yWhen.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\retr
yWhen.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\samp
le.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\samp
le.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\samp
leTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\samp
leTime.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\scan
.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\scan
.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\sequ
enceEqual.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\sequ
enceEqual.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\shar
e.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\shar
e.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\shar
eReplay.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\shar
eReplay.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\sing
le.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\sing
le.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
Last.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
Last.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
Until.js'
| Auto installing...npm WARN tar ENOENT: no such file or directory, open 'C:\Use
rs\木\my-project\ant-design-pro-template\node_modules\.staging\rxjs-459de6c6\_es
m5\add\operator\skipUntil.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
While.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\skip
While.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\star
tWith.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\star
tWith.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\subs
cribeOn.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\subs
cribeOn.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\swit
ch.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\swit
ch.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\swit
chMap.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\swit
chMap.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\swit
chMapTo.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\swit
chMapTo.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
Last.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
Last.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
Until.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
Until.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
While.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\take
While.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\thro
ttle.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\thro
ttle.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\thro
ttleTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\thro
ttleTime.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
Interval.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
Interval.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
out.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
out.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
outWith.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
outWith.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
stamp.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\time
stamp.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\toAr
ray.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\toAr
ray.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\toPr
omise.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\toPr
omise.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
ow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
ow.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owCount.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owCount.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owTime.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owTime.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owToggle.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owToggle.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owWhen.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\wind
owWhen.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\with
LatestFrom.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\with
LatestFrom.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\zip.
js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\zip.
js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\zipA
ll.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\木\my-project\ant
-design-pro-template\node_modules\.staging\rxjs-459de6c6\_esm5\add\operator\zipA
ll.js.map'
\ Auto installing... WARN tar ENOENT: no such file or directory, open 'C:\Users\
木\my-project\ant-design-pro-template\node_modules\.staging\typescript-ab6c37eb\
lib\zh-CN\diagnosticMessages.generated.json'
/ Auto installing...
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\木\AppData\Roaming\npm-cache\_logs\2018-03-02T01_14_32_412
Z-debug.log
npm install end
Visit https://pro.ant.design to learn more.

C:\Users\木\my-project>

**Comment by pkaq** [comment]
1.使用中英文字母数字命名的正经目录名称，把路径里的中文目录去掉
2.换yarn
3.再试一次
