### ISSUE TITLE
404与403页面页面出现横向滚动条🐛 [BUG]

### ISSUE THREAD

**Issue by xyovo** [ant-design/ant-design-pro#10167]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/28668830/186554407-aa120f00-9fb6-4938-9365-81513f6aa9f0.png)
![image](https://user-images.githubusercontent.com/28668830/186554498-a455c286-0995-4946-9812-c9aefe32a32c.png)

### © 版本信息

- Ant Design Pro 版本: 3
- umi 版本4
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mijaclan** [comment]
兄弟我这里是正常的，官方的也是正常的 https://preview.pro.ant.design/404 ，你看你是不是改了什么

**Comment by hb1707** [comment]
同样遇到这个问题

**Comment by chenshuai2144** [comment]
帮忙debug一下吧，我这里没复现
