### ISSUE TITLE
🐛 [BUG] layout在首次登录后错乱

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#10164]
### 🐛 bug 描述

无论是生产环境还是本地开发环境, 当项目部署(本地编译)完成, 第一次访问的时候登录成功后, 布局就乱了, 顶部导航栏消失, 左侧菜单栏底部出现了导航栏的内容, 左侧菜单栏顶部logo未按配置显示(变成了antd的logo),如下图所示:  
  
![飞书20220824-094753](https://user-images.githubusercontent.com/13959162/186299697-7b8d7ea3-f2c5-46b9-b289-86818a8d68c1.jpg)

手动刷新后恢复正常, 正确的布局应该如下:    

![飞书20220824-095015](https://user-images.githubusercontent.com/13959162/186299943-31c81548-e88f-4395-b64b-096177cbe03f.jpg)

`defaultSetting.ts`配置如下:   
```
import { Settings as LayoutSettings } from '@ant-design/pro-components';

const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'dark',
  primaryColor: '#42b983',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: 'xxxx',
  pwa: false,
  logo: 'icons/logo.png',
  iconfontUrl: '',
};

export default Settings;
```

### 📷 复现步骤 | Recurrence steps

使用如上配置运行或者打包部署项目, 然后在浏览器内访问

### 🏞 期望结果 | Expected results

布局正常

### 💻 复现代码 | Recurrence code

如上

### © 版本信息

- Ant Design Pro 版本:  v6
- umi 版本: v4
- 浏览器环境: chrome
- 开发环境: windows11

### 🚑 其他信息
测试过将`fixedHeader`设置为`true`, 问题依旧

**Comment by darkfiredarkhalo** [comment]
https://preview.pro.ant.design/使用的是哪个版本的antd pro, 这个版本的挺好的, 整体布局什么的挺舒适.  如果不使用最新版, 比如使用预览站点使用的那个版本, 该如何创建项目, 有清楚的兄弟麻烦告知下

**Comment by ycang89** [comment]
上一个版本。https://pro.ant.design/docs/getting-started

**Comment by ycang89** [comment]
> https://preview.pro.ant.design使用的是哪个版本的antd pro, 这个版本的挺好的, 整体布局什么的挺舒适. 如果不使用最新版, 比如使用预览站点使用的那个版本, 该如何创建项目, 有清楚的兄弟麻烦告知下

上一个版本。https://pro.ant.design/docs/getting-started

**Comment by echoyl** [comment]
> https://preview.pro.ant.design使用的是哪个版本的antd pro, 这个版本的挺好的, 整体布局什么的挺舒适. 如果不使用最新版, 比如使用预览站点使用的那个版本, 该如何创建项目, 有清楚的兄弟麻烦告知下

单独安装一个 pro-layout,我安装的是 "@ant-design/pro-layout": "6.38.13", 这个版本
菜单导航就和以前一样的。右侧内容要使用以前的话 在页面 import { PageContainer } from '@ant-design/pro-layout';

**Comment by chenshuai2144** [comment]
升级到 2.0 正式版本应该能解决。

**Comment by darkfiredarkhalo** [comment]
> 升级到 2.0 正式版本应该能解决。

@chenshuai2144 您好,您说的升级到2.0是升级的什么? `pro-components`吗? 目前我的`dependencies`如下:  
```
"dependencies": {
    "@ant-design/charts": "^1.4.2",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^1.1.1",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.20.0",
    "classnames": "^2.3.0",
    "crypto-js": "^4.1.1",
    "file-saver": "^2.0.5",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "nats.ws": "^1.9.0",
    "omit.js": "^2.0.2",
    "protobufjs": "^7.1.0",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "store": "^2.0.12"
  },
```

**Comment by Sean529** [comment]
请问这个问题解决了吗？

**Comment by Sean529** [comment]
> 升级到 2.0 正式版本应该能解决。

"@ant-design/pro-components": "^2.0.0",
@chenshuai2144 大佬，2.0.0 也存在首次登录导航错乱问题，求解决办法~~

**Comment by Sean529** [comment]
> > [https://preview.pro.ant.design使用的是哪个版本的antd](https://preview.pro.ant.design%E4%BD%BF%E7%94%A8%E7%9A%84%E6%98%AF%E5%93%AA%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84antd) pro, 这个版本的挺好的, 整体布局什么的挺舒适. 如果不使用最新版, 比如使用预览站点使用的那个版本, 该如何创建项目, 有清楚的兄弟麻烦告知下
> 
> 单独安装一个 pro-layout,我安装的是 "@ant-design/pro-layout": "6.38.13", 这个版本 菜单导航就和以前一样的。右侧内容要使用以前的话 在页面 import { PageContainer } from '@ant-design/pro-layout';

@echoyl 大佬按照这个方式改了，还是有问题

**Comment by Sean529** [comment]
从 2.0.0 升级到 2.3.10 解决了
"@ant-design/pro-components": "^2.3.10",

**Comment by AlanJava** [comment]
> > > [https://preview.pro.ant.design使用的是哪个版本的antd](https://preview.pro.ant.design%E4%BD%BF%E7%94%A8%E7%9A%84%E6%98%AF%E5%93%AA%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84antd) pro, 这个版本的挺好的, 整体布局什么的挺舒适. 如果不使用最新版, 比如使用预览站点使用的那个版本, 该如何创建项目, 有清楚的兄弟麻烦告知下
> > 
> > 
> > 单独安装一个 pro-layout,我安装的是 "@ant-design/pro-layout": "6.38.13", 这个版本 菜单导航就和以前一样的。右侧内容要使用以前的话 在页面 import { PageContainer } from '@ant-design/pro-layout';
> 
> @echoyl 大佬按照这个方式改了，还是有问题

我升级这个依赖后就好了"@ant-design/pro-components": "2.4.14",

**Comment by cpc5622** [comment]
我现在也出现这个问题了，如何解决

**Comment by cpc5622** [comment]
> 

按照评论里的解决方法都解决不了
