### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by yuandalu** [ant-design/ant-design-pro#10162]
### 🐛 bug 描述

<img width="295" alt="image" src="https://user-images.githubusercontent.com/3860040/186064516-8ff3c49d-8119-4719-be8d-324d50d9616b.png">
增加了路有前缀之后，面包屑没有带上前缀，点击后路径错误

### 📷 复现步骤 | Recurrence steps
config配置前缀
base: '/backend/',
  publicPath: '/backend/',

访问面包屑，不带前缀

### 🏞 期望结果 | Expected results
能够正常携带前缀

### © 版本信息

- Ant Design Pro 版本: [6.0]
- umi 版本 4.0
- 浏览器环境 chrome
- 开发环境 macos

### 🚑 其他信息
这个问题v5刚出的时候也有，后来修复了，v6又出现了

**Comment by echoyl** [comment]
我也是，是因为单独使用之前的layout导致的吗？

**Comment by yuandalu** [comment]
> 

我确实单独用了之前的layout，因为新的layout有点多，我也是v5升上来的，但是layout和prolist我用了之前的
