### ISSUE TITLE
🐛 [BUG]publicPath和outputPath失效

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#10160]
### 🐛 bug 描述

`config.ts`中配置`publicPath`和`outputPath`, 开发模式下(`yarn start`), `publicPath`生效, 但同时未添加`publicPath`的url也可以访问到页面, 例如未配置`publicPath`时访问页面是`http://localhost:8000`, 配置`publicPath="/dev/"`, 此时访问页面应该是`http://localhost:8000/dev`, 但是在最新的antd pro下, `http://localhost:8000`在配置了`publicPath`的情况下依旧可以访问...  
配置了`publicPath`和`outputPath`后, 打包(`yarn build`), 异常现象有2;  
- 打包后生成的目录未按照`outputPath`配置生成, 依旧是`dist`  
- 使用`serve ./dist`部署后直接使用`http://localhost:3000`访问页面, 可直接访问,静态资源加载也是正常的, 网络中可看到资源路径并没有加上`publicPath`, 但是加上`publicPath`,即访问`http://localhost:3000/dev`就变成了404, 静态资源也是404

### 📷 复现步骤 | Recurrence steps

同上

### 🏞 期望结果 | Expected results

`config.ts`中配置`publicPath`和`outputPath`, 最终可依据配置文档[publicPath](https://v3.umijs.org/zh-CN/config#publicpath)和[outputPath](https://v3.umijs.org/zh-CN/config#outputpath)所述正常生效

### 💻 复现代码 | Recurrence code

同描述

### © 版本信息

- Ant Design Pro 版本: 最新版
- umi 版本: 4.0.9
- 浏览器环境: Chrome
- 开发环境: windows11

### 🚑 其他信息

配置[base](https://v3.umijs.org/zh-CN/config#base)也不起作用(`base`值和`publicPath`值一致), 另外`base`和`publicPath`有什么区别?

**Comment by zhaojunpeng0425** [comment]
base 应该是体现在最后项目的页面路径上，publicPath指的是你最后打包好的js,css文件，最后在服务器上根路径下什么文件夹下面

**Comment by chenshuai2144** [comment]
base 是给路由的前缀。

publicPath 是打包js 和 css 的位置。这两个在开发环境下都不好测试，你最好编译一下试试
