### ISSUE TITLE
🐛 [BUG] 官网文档需要更新，-g已被废弃，应改为--location==global

### ISSUE THREAD

**Issue by Elylicery** [ant-design/ant-design-pro#10168]
### 🐛 bug 描述

运行 `npm i @ant-design/pro-cli -g`时出错，官网文档应改为  `npm i @ant-design/pro-cli --location==global`

### 📷 复现步骤 | Recurrence steps

<img width="572" alt="image" src="https://user-images.githubusercontent.com/23568822/186567616-fab64912-07bb-4850-bd6c-9ed43cb59a3f.png">

### 🏞 期望结果 | Expected results

<img width="565" alt="image" src="https://user-images.githubusercontent.com/23568822/186567551-96283768-6307-470f-8fba-35f0a65faf7d.png">

### © 版本信息

- 浏览器环境：chorme
- 开发环境 ：mac OS

**Comment by KangXinzhi** [comment]
我在本地测试了下，node14, npm 6 环境中，使用npm i @ant-design/pro-cli --location==global 的方式安装会报错bash: /Users/admin/.nvm/versions/node/v14.10.1/bin/pro: No such file or directory，而使用npm i @ant-design/pro-cli -g 一切正常。 @chenshuai2144

**Comment by KangXinzhi** [comment]
node 16以上版本才会有提示：npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

**Comment by xiaohuoni** [comment]
直接用 `npx @ant-design/pro-cli  create` 或者更快的 `pnpm dlx @ant-design/pro-cli create`
