### ISSUE TITLE
🐛 [BUG]新建与登录平级路由，页面跳转会整个页面loading，不需要这样

### ISSUE THREAD

**Issue by marlti7** [ant-design/ant-design-pro#10169]
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "1.1.1",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.20.0",
    "classnames": "^2.3.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "umi": "^3.5.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.11.1",
    "@umijs/openapi": "^1.6.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/plugin-openapi": "^1.3.3",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^2.1.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "stylelint": "^13.0.0",
    "swagger-ui-dist": "^4.12.0",
    "typescript": "^4.5.0",
    "umi-serve": "^1.9.10"
  },
  路由配置
  {
    path: '/user',
    layout: false,
    routes: [
      { name: '登录', path: '/user/login', component: './user/Login' },
      {name: '重置密码', path: '/user/resetPassword', icon: 'crown', component: './user/resetPassword' },
      { component: './404' },
    ],
  },
  // {path: '/user/resetPassword', component: './user/resetPassword' },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },

配置空loading 还是是不行 删除document.ejs  也还是白屏后渲染，只是页面切换，是在哪里设置这步loading的，两个页面push不应该直接渲染不就行了（不涉及登录数据验证）
/** 获取用户信息比较慢的时候会展示一个 loading */
export const initialStateConfig = {
  loading: <></>,
};
 可以去掉loading吗 体验很怪  旧版本没这个东西

**Comment by drizzlesconsin** [comment]
[可以关闭 dynamicImport](https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97)

**Comment by drizzlesconsin** [comment]
[dynamicimport](https://v3.umijs.org/config#dynamicimport)

**Comment by marlti7** [comment]
> dynamicimport

试了 没用

**Comment by marlti7** [comment]
页面会先跳转 再loading 然后再跳转到新路由页

**Comment by marlti7** [comment]
渲染了两次 中间出现了loading覆盖
