### ISSUE TITLE
🐛 [BUG] 执行把ts转化成js 报错

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#10175]
### 🐛 bug 描述
版本：ant-design-pro-5.2.0
 参考：https://pro.ant.design/zh-CN/blog/better-block#-typescript-%E8%BD%AC-javascript  
执行:npx umi block add AccountSettings --npm-client=tyarn --registry=https://registry.npm.taobao.org的时候报如下错误。
```×  error     AssertionError [ERR_ASSERTION]: C:\Users\Administrator\.umi3\blocks\github.com\umijs\umi-blocks\AccountSettings don't exists
```

### 📷 复现步骤 | Recurrence steps
无

### 🏞 期望结果 | Expected results

不报错。

### © 版本信息

- Ant Design Pro 版本:  5.2.0
- umi 版本 ：umi3
- 浏览器环境 crhome 
- 开发环境 webstorm

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8272614/186868355-596c67a4-9e4b-41d1-83af-84d6758474a0.png)

**Comment by chenshuai2144** [comment]
已经不支持这个模式了，推荐不要使用了。可以手动copy下代码
