### ISSUE TITLE
🐛 [BUG] 5.2版本主题样式切换问题

### ISSUE THREAD

**Issue by arlin123** [ant-design/ant-design-pro#10177]
### 🐛 bug 描述
这2天发现开发环境右侧的主题切换样式按钮消失了，但是奇怪的是打包之后正式环境里面可以看到。
昨天尝试新建的项目 选择umi3项目也没有。

下面是之前的包：
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0",
    "@ant-design/pro-table": "^2.71.0",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.19.0",

    "umi": "^3.5.0"
  },

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本 3
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您提供的信息可以初步判断这是Ant Design Pro的一个bug，但是需要进一步了解具体情况。

您可以尝试在开发环境中手动引入该按钮，具体代码如下所示：

```jsx
import React from "react";
import { Dropdown, Menu, Tooltip } from "antd";
import { QuestionCircleOutlined } from "@ant-design/icons";
import { useIntl, SelectLang } from "umi";
import classNames from "classnames";
import HeaderDropdown from "../HeaderDropdown";
import styles from "./index.less";

const SelectLangDropdown = () => {
  const intl = useIntl();

  const changeLang = ({ key }) => {
    const { search, pathname } = window.location;
    const lang = key === "zh-CN" ? "" : key;
    if (lang) {
      window.location.href = `${pathname}?locale=${lang}${search}`;
    } else {
      window.location.href = `${pathname}${search}`;
    }
  };

  const langMenu = (
    <Menu className={styles.menu} selectedKeys={[]} onClick={changeLang}>
      <Menu.Item key="zh-CN">中文简体</Menu.Item>
      <Menu.Item key="en-US">English</Menu.Item>
    </Menu>
  );

  return (
    <HeaderDropdown overlay={langMenu}>
      <span className={classNames(styles.action, styles.account)}>
        <Tooltip title={intl.formatMessage({ id: "navBar.lang" })}>
          <QuestionCircleOutlined />
        </Tooltip>
      </span>
    </HeaderDropdown>
  );
};

export default SelectLangDropdown;
```

如果以上方法实现不了，您可以前往Ant Design Pro的GitHub提交 issue 请求技术支持。具体操作方式可以参考[如何在 GitHub 上提交 issue 或 feature](https://docs.github.com/cn/issues/tracking-your-work-with-issues/creating-issues/about-issues) 文档。

**Comment by chenshuai2144** [comment]
清空依赖之后重新安装一下，应该是环境变量试试
