### ISSUE TITLE
从服务端请求菜单，一级菜单icon生效，二级菜单不生效

### ISSUE THREAD

**Issue by yangyangdg** [ant-design/ant-design-pro#10178]
bug重现：
1、后端路由定义：
<img width="316" alt="image" src="https://user-images.githubusercontent.com/49295228/187031004-0506bc1a-058e-4a29-8f28-ab354aae0dff.png">
2、路由映射icon：
<img width="740" alt="image" src="https://user-images.githubusercontent.com/49295228/187031092-9c660004-6a31-4c4d-950e-48b5fd6dc334.png">
3、运行效果：
<img width="767" alt="image" src="https://user-images.githubusercontent.com/49295228/187031155-a2140ff3-e1ce-4dae-920f-940334be294d.png">

**Comment by pkaq** [comment]
![image](https://user-images.githubusercontent.com/4537450/187066035-541a5ec3-318a-4149-b30b-5b2cfa39dae2.png)
用到的icon要挨个引入映射

**Comment by yangda666** [comment]
> bug重现： 1、后端路由定义： <img alt="image" width="316" src="https://user-images.githubusercontent.com/49295228/187031004-0506bc1a-058e-4a29-8f28-ab354aae0dff.png"> 2、路由映射icon： <img alt="image" width="740" src="https://user-images.githubusercontent.com/49295228/187031092-9c660004-6a31-4c4d-950e-48b5fd6dc334.png"> 3、运行效果： <img alt="image" width="767" src="https://user-images.githubusercontent.com/49295228/187031155-a2140ff3-e1ce-4dae-920f-940334be294d.png">


这个代码有问题 对于2级菜单icon你没有映射到

**Comment by yangyangdg** [comment]
> 

肯定映射到了啊，没映射到我还来提issues干嘛，没看到我已经写了console.log('menuData',menuData)吗，确认过了已经映射

> > bug重现： 1、后端路由定义： <img alt="image" width="316" src="https://user-images.githubusercontent.com/49295228/187031004-0506bc1a-058e-4a29-8f28-ab354aae0dff.png"> 2、路由映射icon： <img alt="image" width="740" src="https://user-images.githubusercontent.com/49295228/187031092-9c660004-6a31-4c4d-950e-48b5fd6dc334.png"> 3、运行效果： <img alt="image" width="767" src="https://user-images.githubusercontent.com/49295228/187031155-a2140ff3-e1ce-4dae-920f-940334be294d.png">
> 
> 这个代码有问题 对于2级菜单icon你没有映射到

> 肯定映射到了啊，没映射到我还来提issues干嘛，没看到我已经写了console.log('menuData',menuData)吗，确认过了已经映射

**Comment by yangyangdg** [comment]
> 
已经映射

**Comment by mushroomlb** [comment]
一直不支持，官方demo也没有

**Comment by Mankvis** [comment]
请问解决了吗

**Comment by yangda666** [comment]
官网提的有子菜单项的render方法可以重写下： subMenuItemRender  
<img width="983" alt="截屏2022-08-30 08 27 16" src="https://user-images.githubusercontent.com/70259086/187321951-01fefe60-6d9d-4ff9-93a2-606cd2ff047e.png">

**Comment by Mankvis** [comment]
> 官网提的有子菜单项的render方法可以重写下： subMenuItemRender <img alt="截屏2022-08-30 08 27 16" width="983" src="https://user-images.githubusercontent.com/70259086/187321951-01fefe60-6d9d-4ff9-93a2-606cd2ff047e.png">

大佬这个有demo代码吗

**Comment by djfyaci** [comment]
试下这个
`// 二级icon
    menuItemRender: (menuItemProps, defaultDom) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      return (
        <Link to={menuItemProps.path}>
          {/* {menuItemProps?.icon?.setAttribute({color: 'red'})} */}
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },
      return (
        <Link to={menuItemProps.path}>
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },`

**Comment by djfyaci** [comment]
// 二级icon
    menuItemRender: (menuItemProps, defaultDom) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      return (
        <Link to={menuItemProps.path}>
          {/* {menuItemProps?.icon?.setAttribute({color: 'red'})} */}
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },
      return (
        <Link to={menuItemProps.path}>
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },

**Comment by djfyaci** [comment]
`
// 二级icon
    menuItemRender: (menuItemProps, defaultDom) => {
      if (menuItemProps.isUrl || !menuItemProps.path) {
        return defaultDom;
      }
      return (
        <Link to={menuItemProps.path}>
          {/* {menuItemProps?.icon?.setAttribute({color: 'red'})} */}
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },
      return (
        <Link to={menuItemProps.path}>
          {menuItemProps.pro_layout_parentKeys &&
            menuItemProps.pro_layout_parentKeys.length > 0 &&
            menuItemProps.icon}
          {defaultDom}
        </Link>
      );
    },
`

**Comment by yangyangdg** [comment]
> > 
> 
> ```
> // 二级icon
> menuItemRender: (menuItemProps, defaultDom) => {
>   if (menuItemProps.isUrl || !menuItemProps.path) {
>     return defaultDom;
>   }
>   return (
>     <Link to={menuItemProps.path}>
>       {menuItemProps.pro_layout_parentKeys &&
>         menuItemProps.pro_layout_parentKeys.length > 0 &&
>         menuItemProps.icon}
>       {defaultDom}
>     </Link>
>   );
> },
> ```

谢谢大佬，这样写可以解决这个二级菜单图标不显示问题！！

**Comment by Libuke5115** [comment]
http://t.csdnimg.cn/5KpDG 可以看看这篇文章
![Uploading 57035f75928a49c298bfe76e0bf6a450.png…]()
