### ISSUE TITLE
🧐[问题 | question] 为什么在antd5.0之后不支持 js 了。。强制用ts吗？ 还是我没找到下载js版本的地方。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#10174]
### 🧐 问题描述 | Problem description

我们平时做一些小项目，就是用的js 来写，本来也不是做什么大型项目，所以我们都是用JS，不用TS。是不是应该考虑一下我们的感受呢？

### 💻 示例代码 | Sample code

无

### 🚑 其他信息 | Other information

无

OS: 无

Node：无

浏览器 | browser： 无

**Comment by 13992094832** [comment]
我也想要js版本，不想学ts版本，

**Comment by chunbobo** [comment]
可以写js吧，我强行写js也正常使用

**Comment by chenshuai2144** [comment]
不支持 js 了，为了团队协作和项目质量我们不会提供 js 版本了

**Comment by 1739616529** [comment]
一样用啊  ts最后还是转成 js运行的
