### ISSUE TITLE
🧐[问题 | question] errorThrower 没有作用

### ISSUE THREAD

**Issue by choi2k** [ant-design/ant-design-pro#10187]
### 🧐 问题描述 | Problem description

https://umijs.org/docs/max/request
“其中 errorThrower 接收你后端返回的数据并且需要抛出一个你自己设定的 error， 你可以在这里根据后端的数据进行一定的处理。”

测试后端返回错误的时候, 使用 `errorThrower` 来做初步处理. 然后 `errorHandler` 再后续处理. 

预期：
应该回进到 `errorThrower` 然后 `errorHandler`. 
实际：
测试只会进到 `errorHandler`. 

测试所用的最新版本的 ant-design pro, 由 ”pro create myapp“ 创建. 

### 💻 示例代码 | Sample code

```ts
// app.tsx
 
export const request: RequestConfig = {
  timeout: 1000,
  // other axios options you want
  errorConfig: {
    errorHandler() {
      console.info('errorHandler');
    },
    errorThrower() {
      console.info('errorThrower');
    },
  },
  requestInterceptors: [
    (url, options) => {
      console.info('requestInterceptors');
      return { url, options };
    },
  ],
  responseInterceptors: [
    (response) => {
      console.info('responseInterceptors');
      return response;
    },
  ],
};
```

```ts
// api 返回 500 错误
request<API.LoginResult>('/api/500', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });


```

### 🚑 其他信息 | Other information

<img width="831" alt="Screenshot 2022-08-31 at 1 55 34 PM" src="https://user-images.githubusercontent.com/2627734/187605158-db9e1b4b-d16e-443d-820b-16d8e95dfa6a.png">
实际只有 requestInterceptors 和 errorHandler 有跑 

OS: Mac 12.4

Node：v16.15.1

浏览器 | browser：Chrome

**Comment by chenshuai2144** [comment]
500 和 404 这些http错误不会进入 errorThrower  的
