### ISSUE TITLE
🐛 [BUG] 设置 hash 路由，PageContainer 面包屑的跳转路径不是 hash 路由

### ISSUE THREAD

**Issue by houkunlin** [ant-design/ant-design-pro#10188]
### 🐛 bug 描述
在 `config/config.ts` 配置了
```
  history: {
    type: 'hash',
  },
```
多级路由的 `PageContainer` 面包屑跳转错误，与预期的不一致，如下图：
![image](https://user-images.githubusercontent.com/12333292/187622599-56d002e6-9cb4-4e6e-af17-6d086ee61e1b.png)

如果在页面中自定义设置 `PageContainer` 面包屑配置，如下：
```
    <PageContainer
      header={{
        breadcrumb: {
          routes: [
            {
              path: 'a',
              breadcrumbName: '一级页面',
            },
            {
              path: 'bb',
              breadcrumbName: '二级页面',
            },
            {
              path: 'c',
              breadcrumbName: '当前页面',
            },
          ],
        }
      }}>
111
</PageContainer>
```
这种场景的表现才是预期想要的
![image](https://user-images.githubusercontent.com/12333292/187623203-9a1fc430-e345-4863-b2fe-b04bd637a5e3.png)

### © 版本信息

- Ant Design Pro 版本:  `AntDesignPro 6.0` `"@ant-design/pro-components": "^1.1.1"` 实际已安装 `1.1.20`
- umi 版本：`"@umijs/max": "^4.0.0-rc.22"` 实际已安装 `4.0.15`
- 浏览器环境：谷歌浏览器最新版
- 开发环境：Windows11，node v16.14.2

**Comment by johanazhu** [comment]
我遇到的恰恰相反，默认 history: browser 情况下，设置 breadcrumb ，跳转的路由带 hash，即使按照这种方法：https://ant.design/components/breadcrumb-cn/，也跳不过去

**Comment by johanazhu** [comment]
> 我遇到的恰恰相反，默认 history: browser 情况下，设置 breadcrumb ，跳转的路由带 hash，即使按照这种方法：https://ant.design/components/breadcrumb-cn/ ，也跳不过去

后来我改了demo，能实现跳转，是不是demo错了呢。暂时对 ant-design pro 不是很了解，等熟悉了再看
