### ISSUE TITLE
🧐[问题 | question] EditableProTable 中当新增一列 recordCreatorProps 给某列设置属性，为什么当此列 设置 hideInTable=true 或者 editable=false时，在任一列 formItemProps 中的 form.getFieldsValues()方法中获取不到此值

### ISSUE THREAD

**Issue by lihengliang-999** [ant-design/ant-design-pro#10184]
### 🧐 问题描述 | Problem description

EditableProTable 中当新增一列 recordCreatorProps 给某列设置默认值，为什么当此列 在column中 设置 hideInTable=true 或者 editable=false时，在任一列 formItemProps 中的 form.getFieldsValues()方法中获取不到此值

### 💻 示例代码 | Sample code

![image](https://user-images.githubusercontent.com/95761715/187580837-67e0890a-66e1-4c56-b6e0-7f6592d18476.png)
![image](https://user-images.githubusercontent.com/95761715/187581356-8d03f66b-3b12-460c-8ed6-9303e168efea.png)
![image](https://user-images.githubusercontent.com/95761715/187581550-b1d07061-5a04-4f4d-89b5-812e57c3ffe8.png)
![image](https://user-images.githubusercontent.com/95761715/187581771-afc2ebff-da4b-42f8-a461-6709c266eb9c.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
` form.getFieldsValues(true)`

加个 true，不然没有 name 不会获取回来
