### ISSUE TITLE
安装antdesignpro出现了N多错误，请大牛帮忙！

### ISSUE THREAD

**Issue by cyp66** [ant-design/ant-design-pro#1019]
，菜鸟做法：1.安装node,安装好后目录自带npm，2.输入命令$ git clone git@github.com:ant-design/ant-design-pro.git --depth=1
3.$ cd ant-design-pro
4.$ npm install
第四步出现一堆err

C:\Users\huitong>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path C:\Users\huitong\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\huitong\
package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\huitong\npm-debug.log

**Comment by valleykid** [comment]
很奇怪在文件夹**ant-design-pro**下执行`npm install`，怎么去找**C:\Users\huitong
package.json**这个文件，难道ant-design-pro文件夹下缺失package.json？
另外“微吐槽”下你本机的node版本，真的太低了。

**Comment by cyp66** [comment]
你好，请帮忙！
D:\ant-design-pro-master\ant-design-pro-master>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nightmare@^2.10.0 (node_modules\
nightmare):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: tunneling socket could not be est
ablished, cause=getaddrinfo ENOTFOUND server server:80
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND server server:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ant-design-pro-master\ant-design-pro-master\npm-debug.log

D:\ant-design-pro-master\ant-design-pro-master>

**Comment by afc163** [comment]
Try upgrade your node and npm.

**Comment by cyp66** [comment]
在命令行升级npm出现错误了
C:\Users\huitong>npm install npm@latest -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND server server:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\huitong\npm-debug.log

**Comment by chenshuai2144** [comment]
npm 不是这个升级的。
https://nodejs.org/en/
