### ISSUE TITLE
🐛 [BUG]ProTable在微应用中无法翻页

### ISSUE THREAD

**Issue by FrankYe84** [ant-design/ant-design-pro#10193]
### 🐛 bug 描述

在正常项目中是没问题的，但作为微前端的子应用时，翻页的按钮点不了，也没有报错。

- Ant Design Pro 版本: pro-table@2.80.4
- umi 版本 : 3.5.33
- 浏览器环境：chrome 87.0.4280.88
- 开发环境：macos 11.1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，由于我是一名 AI 语言模型，无法提供代码复现，但是我可以根据你提供的信息给出一些可能的解决方法。 

由于你在微前端的子应用环境下出现了翻页按钮无法点击的问题，有可能是前端路由的问题导致的。你可以尝试在 ProTable 中添加一个 `request` 属性，将请求的地址包装一下，例如：

```jsx
<ProTable
  request={(params, sort, filter) => {
    const url = new URL("http://example.com/table-data");
    Object.entries({ ...params, sort, filter }).forEach(([key, value]) => {
      if (value) {
        url.searchParams.set(key, value);
      }
    });
    return fetch(url.toString())
      .then((response) => response.json())
      .then((data) => ({
        data: data.list,
        total: data.total,
        success: true,
      }))
      .catch((error) => ({
        data: [],
        total: 0,
        success: false,
      }));
  }}
/>
```

这样可以保证在微前端环境下路由的正确性，从而使翻页按钮正常工作。如果问题还是存在，可以进一步尝试检查路由配置以及子应用间的通信是否正确。
