### ISSUE TITLE
🐛 [BUG]Ant Design Pro 6.0 配置base地址后，登录重定向到redirect参数携带了base路径也带过去了

### ISSUE THREAD

**Issue by CrazyDotNet** [ant-design/ant-design-pro#10197]
### 📷 复现步骤 | Recurrence steps
在config.ts文件配置
```json
{
  base: '/sys/sp/',
  publicPath: '/sys/sp/',
}
```

未登录时浏览器地址栏内容：

`http://localhost:8000/sys/sp/user/login?redirect=%2Fsys%2Fsp%2Fsystem%2Faudit-logs`

登录后根据redirect参数跳转的地址：

`http://[localhost:8000/sys/sp/sys/sp/system/identity-roles`

### 🏞 期望结果 | Expected results

未登录：
`http://localhost:8000/sys/sp/user/login?redirect=%2Fsys%2Fsp%2Fsystem%2Faudit-logs`
登录后：
`http://localhost:8000/sys/sp/system/audit-logs`

### 💻 复现代码 | Recurrence code

拉下来的框架原封未动，只改了后端登录接口，
在 `src\pages\User\Login\index.tsx`文件中，如果登录成功后，不使用redirect参数，直接跳转到 `/` 正常

### © 版本信息

- Ant Design Pro 版本: "6.0.0-beta.1"
- umi 版本 v4.0.15
- 浏览器环境 edge 最新
- 开发环境 windows10 / node v16.13.1

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/065c912d3df3d615d6bc01e5e5c95c0558d6c457/src/components/RightContent/AvatarDropdown.tsx#L30


在这里处理一下base
