### ISSUE TITLE
👑 [需求] Ask for test demo

### ISSUE THREAD

**Issue by cqhung1412** [ant-design/ant-design-pro#10203]
### 🥰 需求描述 | Requirements description

I have been using ant design pro in my projects for a while. However, I am unable to run any tests for my projects, both jest and playwright. This has happened for a while now, from version 5.2.0 up to the current version 6.0.0-beta.1. I followed the instruction at https://pro.ant.design/docs/test but there are still errors. 

### 🧐 解决方案 | Solution

I would like to have some demo test files, for example `login.test.js, 404.test.js`

### 🚑 其他信息 | Other information

I also tried using Cypress as it provides both unit test and e2e test, but I got webpack error. We should consider using Cypress for simpler testing.

**Comment by chenshuai2144** [comment]
Unit tests are not supported at this time, only e2e tests
