### ISSUE TITLE
🐛 [BUG] 脚手架新建项目，启动报错

### ISSUE THREAD

**Issue by tsingby339** [ant-design/ant-design-pro#10200]
### 🐛  脚手架新建项目，启动报错

![image](https://user-images.githubusercontent.com/30325066/188322996-c81e3eb7-ba94-4644-b156-c90fc1db97f7.png)

Warning: [Ant Design CSS-in-JS] Error in 'LoginForm -> .ant-pro-form-login -> &-main -> &-other': You seem to be using non-logical value 'left' of textAlign, which is not compatible with RTL mode. Please use logical properties and values instead. For more information: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties. 

### 📷 复现步骤 | Recurrence steps
![image](https://user-images.githubusercontent.com/30325066/188322967-8204e622-5bbf-4de2-9a2f-7079c3141286.png)
![image](https://user-images.githubusercontent.com/30325066/188322980-7bbd3b95-2187-45e6-b040-8a99005ad43f.png)

### © 版本信息

- Ant Design Pro 版本:3.0.0

**Comment by chenshuai2144** [comment]
更新版本已经修复
