### ISSUE TITLE
🐛 [BUG]src/app.tsx中layout常量的TS定义有类型报错

### ISSUE THREAD

**Issue by j511002** [ant-design/ant-design-pro#10207]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/14238111/188829456-0458a041-a744-4932-a780-ed05b9eb75a3.png)

### 📷 复现步骤 | Recurrence steps

直接打开src/app.tsx文件即可

### 🏞 期望结果 | Expected results

无类型报错提示

### © 版本信息

- Ant Design Pro 版本: v6.0.0 beta1
- umi 版本 v4.0
- 浏览器环境 无
- 开发环境 mac OS

### 🚑 其他信息

无

**Comment by drizzlesconsin** [comment]
新版 navTheme 不支持 `dark`, 默认 `light`
要 dark, 改一下 token 配置

**Comment by chenshuai2144** [comment]
已经修复了，可以看到 issue 修改一下
