### ISSUE TITLE
🧐[问题 | question] v6开启多tabs失败

### ISSUE THREAD

**Issue by qcjackman** [ant-design/ant-design-pro#10202]
### 🧐 问题描述 | Problem description

6.0.0-beta.1 开启多tabs失败
![image](https://user-images.githubusercontent.com/12554120/188560169-3962946e-8e3b-41eb-b033-3159160e5391.png)

### 💻 示例代码 | Sample code

config/config.tsx
```
...
keepalive: [/./],
tabsLayout: {},
...
```

### 🚑 其他信息 | Other information

ant-design-pro: 6.0.0-beta.1

@umijs/max: 4.0.17

OS: MacOS 12.5.1 

Node：v18.8.0

浏览器 | browser：Chrome

**Comment by qcjackman** [comment]
在 `src/app.tsx` 中添加了 `getKeepAlive` 方法也还是不行
```
export const getKeepAlive = (ka: any) => {
  return ka;
}
```
报错如下：
![image](https://user-images.githubusercontent.com/12554120/188578982-c5bb9179-fa32-46f1-8f11-b0c9c282179b.png)

**Comment by gdmec07140512** [comment]
+1

**Comment by lijifa** [comment]
同问

**Comment by codycoding** [comment]
![image](https://user-images.githubusercontent.com/11560507/189542868-80eb3c27-11a1-436d-890a-09b3b8b7b5f0.png)
同问

**Comment by Cyan-Xmw** [comment]
> export const getKeepAlive = (ka: any) => {
>   return ka;
> }

解决了吗，大哥，我也遇到同样的问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，这种问题可能是版本兼容性的问题，可以尝试使用最新的 antd-pro 和 umijs 来解决该问题。同时，也可以尝试看一下其他 issue 的讨论，看看其中是否有可以借鉴的解决方案。

另外，关于上述代码的问题，可能是由于`src/app.tsx`中的导入有问题，可以尝试将以下代码添加到文件顶部来解决该问题：
```jsx
import React from 'react';
import { KeepAlive } from 'umi';
```
希望能对您有所帮助。
