### ISSUE TITLE
🐛 [BUG]"export 'theme' (imported as 'antdTheme') was not found in 'antd'

### ISSUE THREAD

**Issue by Valar103769** [ant-design/ant-design-pro#10201]
老项目, 升级 "@ant-design/pro-layout": "^6.26.4" 到 "@ant-design/pro-layout": "^7.0.2",
出现 
```

 warning  in ./node_modules/@ant-design/pro-provider/es/index.js

"export 'theme' (imported as 'antdTheme') was not found in 'antd'

 warning  in ./node_modules/@ant-design/pro-utils/es/useStyle/index.js

"export 'theme' (imported as 'antdTheme') was not found in 'antd'
```

ps:  "antd": "4.23.0"

我看了[antd源码](https://github.com/ant-design/ant-design/blob/master/components/index.tsx)和[build之后的代码](https://unpkg.com/antd@4.23.0/es/index.js?module), 确实没有导出theme, 就很奇怪

**Comment by dreammaker7** [comment]
layout v7 引入了 antd v5的API，antd升级到v5就不会报这个错，但是v5现在还是开发版，只能说是layout提前带上了antd v5才能用的功能，还没兼容v4。

**Comment by Valar103769** [comment]
> layout v7 引入了 antd v5的API，antd升级到v5就不会报这个错，但是v5现在还是开发版，只能说是layout提前带上了antd v5才能用的功能，还没兼容v4。

antd v5的链接给一下, 没搜到 @dreammaker7

**Comment by hqwlkj** [comment]
使用 umi  的项目不会存在这个问题，但是其他的比如vite就会有这个问题了。

**Comment by wangs1203** [comment]
emmm，这个问题是不打算解决吗？ 我看所有issue都close掉了

**Comment by Valar103769** [comment]
> 

老哥,有其他好看的ui库推荐吗? @wangs1203

**Comment by zombieJ** [comment]
> emmm，这个问题是不打算解决吗？ 我看所有issue都close掉了


<img width="886" alt="截屏2022-09-09 16 04 17" src="https://user-images.githubusercontent.com/5378891/189302544-23c50ed4-804c-41ba-9231-c73e894a8df0.png">

下个 patch 就有了。

**Comment by wangs1203** [comment]
> > 
> 
> 老哥,有其他好看的ui库推荐吗? @wangs1203
@Valar103769
material UI ? 或者 国内Hypers 团队的Rsuite
