### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by AXmeng** [ant-design/ant-design-pro#10206]
登录页面存在问题
登录时使用username="admin"和password="ant.design"登录，post请求返回code=405

**Comment by drizzlesconsin** [comment]
用 `yarn start` or `npm run start` 启动

**Comment by AXmeng** [comment]
> 用 `yarn start` or `npm run start` 启动

npm run dev启动为什么会有这个问题呢？

**Comment by drizzlesconsin** [comment]
没开启 mock

> 关 issue 吧
