### ISSUE TITLE
能不能解释一下".then("这一句判断的具体原理？谢谢！

### ISSUE THREAD

**Issue by hienchu** [ant-design/ant-design-pro#1021]
能不能解释一下".then("这一句判断的具体原理？谢谢！
https://github.com/ant-design/ant-design-pro/blob/b0d3aad9f3d2c81b8b70298a26a4fdded91f5885/src/common/router.js#L19

**Comment by afc163** [comment]
一个 hack 判断，看 https://github.com/seeden/babel-plugin-dynamic-import-node-sync
