### ISSUE TITLE
🐛 [BUG]ProTable每次进入视野都会刷新一遍接口，不知道为啥，之前的项目都不会，是版本原因嘛？

### ISSUE THREAD

**Issue by jianjian-commits** [ant-design/ant-design-pro#10215]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
"@ant-design/pro-components": "1.1.1",
"@ant-design/pro-layout": "^6.38.15",
"@ant-design/pro-cli": "^2.1.0",

**Comment by chenshuai2144** [comment]
<html>
<body>


revalidateOnFocus | 窗口聚焦时自动重新请求 | boolean | true
-- | -- | -- | --



</body>
</html>


看看这个api
