### ISSUE TITLE
🐛 [BUG]Error: ERROR in ./src/.umi-production/plugin-layout/Layout.tsx 129:27-36

### ISSUE THREAD

**Issue by uvd** [ant-design/ant-design-pro#10217]
### 🐛 bug 描述

Error: ERROR in ./src/.umi-production/plugin-layout/Layout.tsx 129:27-36
export 'ProLayout' (imported as 'ProLayout') was not found in '/home/jenkins/workspace/673_adminweb/node_modules/@ant-design/pro-components' (possible exports: BasicLayout, BetaSchemaForm, CheckCard, ConfigConsumer, ConfigProvider, ConfigProviderWrap, DefaultFooter, DefaultHeader, DescriptionsSkeleton, DragSortTable, DrawerForm, DropdownFooter, EditableProTable, ErrorBoundary, FieldCode, FieldContext, FieldDatePicker, FieldIndexColumn, FieldLabel, FieldMoney, FieldPercent, FieldProgress, FieldRangePicker, FieldRender, FieldSelect, FieldStatus, FieldText, FieldTimePicker, FilterDropdown, FooterToolbar, FormItemProvide, GridContent, Group, IndexColumn, InlineErrorFormItem, IntlConsumer, IntlProvider, LabelIconTip, LightFilter, ListPageSkeleton, ListSkeleton, ListSkeletonItem, ListToolBar, ListToolbarSkeleton, LoginForm, LoginFormPage, ModalForm, PageContainer, PageHeaderSkeleton, PageHeaderWrapper, PageLoading, ProBreadcrumb, ProCard, ProDescriptions, ProForm, ProFormCaptcha, ProFormCascader, ProFormCheckbox, ProFormColorPicker, ProFormContext, ProFormDatePicker, ProFormDateRangePicker, ProFormDateTimePicker, ProFormDateTimeRangePicker, ProFormDependency, ProFormDigit, ProFormDigitRange, ProFormField, ProFormFieldSet, ProFormGroup, ProFormItem, ProFormList, ProFormMoney, ProFormRadio, ProFormRate, ProFormSelect, ProFormSlider, ProFormSwitch, ProFormText, ProFormTextArea, ProFormTimePicker, ProFormTreeSelect, ProFormUploadButton, ProFormUploadDragger, ProPageHeader, ProProvider, ProTable, QueryFilter, RouteContext, Search, SettingDrawer, Statistic, StatisticCard, StepsForm, Submitter, TableDropdown, TableItemSkeleton, TableSkeleton, TableStatus, TopNavHeader, WaterMark, arEGIntl, arrayMoveImmutable, caESIntl, conversionMomentValue, conversionSubmitValue, convertMoment, createIntl, dateArrayFormatter, dateFormatterMap, deDEIntl, defaultRenderText, editableRowByKey, enGBIntl, enUSIntl, esESIntl, faIRIntl, frFRIntl, genCopyable, getFieldPropsOrFormItemProps, getMenuData, getPageTitle, hrHRIntl, idIDIntl, intlMap, intlMapKeys, isBrowser, isDeepEqualReact, isDropdownValueType, isImg, isNil, isUrl, itITIntl, jaJPIntl, koKRIntl, merge, msMYIntl, nanoid, omitBoolean, omitUndefined, omitUndefinedAndEmptyArr, parseValueToMoment, pickProFormItemProps, pickProProps, plPLIntl, proFieldParsingText, proFieldParsingValueEnumToArray, ptBRIntl, recordKeyToString, ruRUIntl, runFunction, srRSIntl, trTRIntl, transformKeySubmitValue, useDebounceFn, useDebounceValue, useDeepCompareEffect, useDeepCompareEffectDebounce, useDocumentTitle, useEditableArray, useEditableMap, useFetchData, useIntl, useLatest, useMountMergeState, usePrevious, useRefFunction, version, viVNIntl, zhCNIntl, zhTWIntl)
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 33:19-28

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [Centos]

**Comment by Guoguang397** [comment]
试试更新一下依赖 "@ant-design/pro-components": "^2.0.0"，看起来和 #10214 是一个问题？

**Comment by xzplays** [comment]
尝试docker编译同样错误

**Comment by chenshuai2144** [comment]
@ant-design/pro-components 升级到 2.0 就能解决问题。
或者 layout 升级到最新版本
