### ISSUE TITLE
🐛 [BUG]export 'ProLayout' (imported as 'ProLayout') was not found

### ISSUE THREAD

**Issue by CharellKing** [ant-design/ant-design-pro#10214]
### 🐛 bug 描述

ant-design-pro@6.0.0-beta.1 build /usr/src/app
> max build

Hello PRO
info  - [你知道吗？] 默认使用 esbuild 作为 JavaScript 压缩工具，也可通过 jsMinifier 配置项切换到 terser 或 uglifyJs 等，详见 https://umijs.org/docs/api/config#jsminifier-webpack
Using openapi Plugin
info  - Umi v4.0.18
error - ./src/.umi-production/plugin-layout/Layout.tsx:133:27-36
export 'ProLayout' (imported as 'ProLayout') was not found in '/usr/src/app/node_modules/@ant-design/pro-components' (possible exports: BasicLayout, BetaSchemaForm, CheckCard, ConfigConsumer, ConfigProvider, ConfigProviderWrap, DefaultFooter, DefaultHeader, DescriptionsSkeleton, DragSortTable, DrawerForm, DropdownFooter, EditableProTable, ErrorBoundary, FieldCode, FieldContext, FieldDatePicker, FieldIndexColumn, FieldLabel, FieldMoney, FieldPercent, FieldProgress, FieldRangePicker, FieldRender, FieldSelect, FieldStatus, FieldText, FieldTimePicker, FilterDropdown, FooterToolbar, FormItemProvide, GridContent, Group, IndexColumn, InlineErrorFormItem, IntlConsumer, IntlProvider, LabelIconTip, LightFilter, ListPageSkeleton, ListSkeleton, ListSkeletonItem, ListToolBar, ListToolbarSkeleton, LoginForm, LoginFormPage, ModalForm, PageContainer, PageHeaderSkeleton, PageHeaderWrapper, PageLoading, ProBreadcrumb, ProCard, ProDescriptions, ProForm, ProFormCaptcha, ProFormCascader, ProFormCheckbox, ProFormColorPicker, ProFormContext, ProFormDatePicker, ProFormDateRangePicker, ProFormDateTimePicker, ProFormDateTimeRangePicker, ProFormDependency, ProFormDigit, ProFormDigitRange, ProFormField, ProFormFieldSet, ProFormGroup, ProFormItem, ProFormList, ProFormMoney, ProFormRadio, ProFormRate, ProFormSelect, ProFormSlider, ProFormSwitch, ProFormText, ProFormTextArea, ProFormTimePicker, ProFormTreeSelect, ProFormUploadButton, ProFormUploadDragger, ProPageHeader, ProProvider, ProTable, QueryFilter, RouteContext, Search, SettingDrawer, Statistic, StatisticCard, StepsForm, Submitter, TableDropdown, TableItemSkeleton, TableSkeleton, TableStatus, TopNavHeader, WaterMark, arEGIntl, arrayMoveImmutable, caESIntl, conversionMomentValue, conversionSubmitValue, convertMoment, createIntl, dateArrayFormatter, dateFormatterMap, deDEIntl, defaultRenderText, editableRowByKey, enGBIntl, enUSIntl, esESIntl, faIRIntl, frFRIntl, genCopyable, getFieldPropsOrFormItemProps, getMenuData, getPageTitle, hrHRIntl, idIDIntl, intlMap, intlMapKeys, isBrowser, isDeepEqualReact, isDropdownValueType, isImg, isNil, isUrl, itITIntl, jaJPIntl, koKRIntl, merge, msMYIntl, nanoid, omitBoolean, omitUndefined, omitUndefinedAndEmptyArr, parseValueToMoment, pickProFormItemProps, pickProProps, plPLIntl, proFieldParsingText, proFieldParsingValueEnumToArray, ptBRIntl, recordKeyToString, ruRUIntl, runFunction, srRSIntl, trTRIntl, transformKeySubmitValue, useDebounceFn, useDebounceValue, useDeepCompareEffect, useDeepCompareEffectDebounce, useDocumentTitle, useEditableArray, useEditableMap, useFetchData, useIntl, useLatest, useMountMergeState, usePrevious, useRefFunction, version, viVNIntl, zhCNIntl, zhTWIntl)
info  - Memory Usage: 757.2 MB (RSS: 987.61 MB)
fatal - Error: ERROR in ./src/.umi-production/plugin-layout/Layout.tsx 133:27-36
export 'ProLayout' (imported as 'ProLayout') was not found in '/usr/src/app/node_modules/@ant-design/pro-components' (possible exports: BasicLayout, BetaSchemaForm, CheckCard, ConfigConsumer, ConfigProvider, ConfigProviderWrap, DefaultFooter, DefaultHeader, DescriptionsSkeleton, DragSortTable, DrawerForm, DropdownFooter, EditableProTable, ErrorBoundary, FieldCode, FieldContext, FieldDatePicker, FieldIndexColumn, FieldLabel, FieldMoney, FieldPercent, FieldProgress, FieldRangePicker, FieldRender, FieldSelect, FieldStatus, FieldText, FieldTimePicker, FilterDropdown, FooterToolbar, FormItemProvide, GridContent, Group, IndexColumn, InlineErrorFormItem, IntlConsumer, IntlProvider, LabelIconTip, LightFilter, ListPageSkeleton, ListSkeleton, ListSkeletonItem, ListToolBar, ListToolbarSkeleton, LoginForm, LoginFormPage, ModalForm, PageContainer, PageHeaderSkeleton, PageHeaderWrapper, PageLoading, ProBreadcrumb, ProCard, ProDescriptions, ProForm, ProFormCaptcha, ProFormCascader, ProFormCheckbox, ProFormColorPicker, ProFormContext, ProFormDatePicker, ProFormDateRangePicker, ProFormDateTimePicker, ProFormDateTimeRangePicker, ProFormDependency, ProFormDigit, ProFormDigitRange, ProFormField, ProFormFieldSet, ProFormGroup, ProFormItem, ProFormList, ProFormMoney, ProFormRadio, ProFormRate, ProFormSelect, ProFormSlider, ProFormSwitch, ProFormText, ProFormTextArea, ProFormTimePicker, ProFormTreeSelect, ProFormUploadButton, ProFormUploadDragger, ProPageHeader, ProProvider, ProTable, QueryFilter, RouteContext, Search, SettingDrawer, Statistic, StatisticCard, StepsForm, Submitter, TableDropdown, TableItemSkeleton, TableSkeleton, TableStatus, TopNavHeader, WaterMark, arEGIntl, arrayMoveImmutable, caESIntl, conversionMomentValue, conversionSubmitValue, convertMoment, createIntl, dateArrayFormatter, dateFormatterMap, deDEIntl, defaultRenderText, editableRowByKey, enGBIntl, enUSIntl, esESIntl, faIRIntl, frFRIntl, genCopyable, getFieldPropsOrFormItemProps, getMenuData, getPageTitle, hrHRIntl, idIDIntl, intlMap, intlMapKeys, isBrowser, isDeepEqualReact, isDropdownValueType, isImg, isNil, isUrl, itITIntl, jaJPIntl, koKRIntl, merge, msMYIntl, nanoid, omitBoolean, omitUndefined, omitUndefinedAndEmptyArr, parseValueToMoment, pickProFormItemProps, pickProProps, plPLIntl, proFieldParsingText, proFieldParsingValueEnumToArray, ptBRIntl, recordKeyToString, ruRUIntl, runFunction, srRSIntl, trTRIntl, transformKeySubmitValue, useDebounceFn, useDebounceValue, useDeepCompareEffect, useDeepCompareEffectDebounce, useDocumentTitle, useEditableArray, useEditableMap, useFetchData, useIntl, useLatest, useMountMergeState, usePrevious, useRefFunction, version, viVNIntl, zhCNIntl, zhTWIntl)
 @ ./src/.umi-production/core/route.tsx
 @ ./src/.umi-production/umi.ts 12:0-41 33:19-28

### 📷 复现步骤 | Recurrence steps

npm run buid

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0.beta]
- umi 版本 4.0.18
- 浏览器环境
- 开发环境 [linux]

**Comment by Guoguang397** [comment]
package.json 更新一下依赖 `"@ant-design/pro-components": "^2.0.0"`，原来的 1.1.1 版本会报这个错误。

**Comment by MINGLIANG98** [comment]
info  - [你知道吗？] 如果你有 MPA（多页应用）需求，可尝试新出的 mpa 配置项，详见 https://umijs.org/docs/guides/mpa
Using openapi Plugin
info  - Umi v4.0.29
error - ./src/common/components/table/customDrawerFilter.tsx:147:35-47RM: operation not permitted, open 'D:\A_APPLICATION\NodeJS\node_ 
export 'default' (imported as 'ProForm') was not found in '@ant-design/pro-components' 
命令:pnpm run build 
### 版本  antdpro  6.0.0-beta.1
### umi  4.0.24
###  node  16.14.2
