### ISSUE TITLE
🐛 [BUG] V6 小屏幕下，头像下来被遮挡

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#10216]
### 🐛 bug 描述

点击头像，头像下来被遮挡
![image](https://user-images.githubusercontent.com/3166799/189303769-0f5f78df-650d-4917-bc74-c65f2f6a5e80.png)

多语言切换正常
![image](https://user-images.githubusercontent.com/3166799/189303732-56ac20b7-393a-442e-979c-e3c64ac74dd6.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤖 回复

你好，感谢你向我们反馈问题。

根据你提供的截图和描述，问题是在小屏幕下头像被遮挡的问题，可以尝试以下几种方案解决：

1. 使用 CSS Media Query ，对小屏幕的布局进行优化，让头像在小屏幕下可以正常显示。下面是一个可能的解决方案：

```
@media screen and (max-width: 768px) {
  .avatar {
    position: absolute;
    top: 70%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 999;
  }
}
```

2. 在小屏幕下隐藏对头像的操作，只在大屏幕下显示，可以考虑使用 CSS Media Query 和 JavaScript 实现。下面是一个可能的解决方案：

```
// 在 JavaScript 中添加以下代码
if (window.innerWidth <= 768) {
  document.getElementById("avatar-operation").style.display = "none";
}

// 在 CSS 中添加以下代码
@media screen and (max-width: 768px) {
  #avatar-operation {
    display: none;
  }
}
```

请注意，这里的 `avatar` 和 `avatar-operation` 是根据你的代码来进行的猜测，具体需要根据你的代码进行调整。

希望以上方案能够对你有所帮助。如果还有其他问题，请随时联系我们，我们会尽力帮助你解决问题。
