### ISSUE TITLE
🧐[问题 | question]请问，如何使用js版本的pro，安装默认的是ts版本

### ISSUE THREAD

**Issue by Dnzzk2** [ant-design/ant-design-pro#10219]
我目前不会ts，我需要用antd pro 的js版本，但是通过官方的脚手架，安装的是ts版本，这该如何解决

**Comment by drizzlesconsin** [comment]
直接使用 `.js`

**Comment by Dnzzk2** [comment]
> 直接使用 `.js`

我是个小白，我修改文件名，但是文件内部的结构，我不知道如何修改，我今天改了好多，依然报错，呜呜呜

**Comment by wuranxu** [comment]
[使用旧版本antd pro](https://github.com/ant-design/ant-design-pro/issues/9943)

新版本似乎不再支持jsx了，可以用旧版本顶一顶，里面可以选择`jsx`。

**Comment by LsyWeb** [comment]
ts的学习很快的，可以花几天时间学一下，几天就可以学会在**react**中简单的使用

**Comment by LsyWeb** [comment]
> > 直接使用`.js`
> 
> 我是个小白，我修改了文件名，但是文件内部的修改结构，我不知道怎么做，我今天改了很多，仍然报错，呜呜呜


ts的学习很快的，可以花几天时间学一下，几天就可以学会在react中简单的使用

**Comment by chenshuai2144** [comment]
不支持js了，都2022年了
