### ISSUE TITLE
🧐[问题 | question] 关于废弃`visible`而去使用`open`控制台警告

### ISSUE THREAD

**Issue by DebugIllus1on** [ant-design/ant-design-pro#10213]
使用版本 Ant Design Pro v5.2.0

控制台显示如下:
![image](https://user-images.githubusercontent.com/53471930/189138454-dc556c8f-2354-404d-a86a-1a4ade8dd02b.png)

我们如何去处理这个警告⚠

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/5937

升级到最新的pro试试
