### ISSUE TITLE
🐛 [BUG] 安装依赖后 打开页面报错

### ISSUE THREAD

**Issue by ksgt00857912** [ant-design/ant-design-pro#10211]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/9008437/189031415-e6e7e493-2a62-4910-ac5b-76e61e914583.png)

### 📷 复现步骤 | Recurrence steps

umi4版本 安装依赖后 输入账号密码 打开页面空白 F12报错

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本 4
- 浏览器环境 Chrome最新版
- 开发环境 [e.g. mac OS]

**Comment by ksgt00857912** [comment]
> 问题解决了吗？同样环境，ant design pro不通。umi4初始化的脚手架

package.json 更新一下依赖 "@ant-design/pro-components": "^2.0.0"，原来的 1.1.1 版本会报这个错误。

**Comment by junegod** [comment]
真是佩服阿里写文档的，只管写，不管试下是否好用

**Comment by yqwoe** [comment]
> > 问题解决了吗？同样环境，ant design pro不通。umi4初始化的脚手架
> 
> package.json 更新一下依赖 "@ant-design/pro-components": "^2.0.0"，原来的 1.1.1 版本会报这个错误。

更新以后，layout会出问题

**Comment by chenshuai2144** [comment]
看起来是锁包导致的，重新更新下依赖
