### ISSUE TITLE
🧐[问题 | question]pages文件夹里的 组件、页面 命名规范

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#10224]
### 🧐 问题描述 | Problem description

我看 all-blocks 分支里 pages 里命名，有的小写，有的大驼峰，有的小写 加  - 连字符

大驼峰 是 组件
全小写 是 分类文件夹 ？
带 - 的 是 啥？
![image](https://user-images.githubusercontent.com/5111701/190045188-026ae462-3e84-4ad2-b9e2-3f10cb9f4489.png)
![image](https://user-images.githubusercontent.com/5111701/190045141-22045690-3536-44bc-a471-07be2adf385b.png)
![image](https://user-images.githubusercontent.com/5111701/190045272-f09b81ab-690e-4748-9b83-d82e5598b58b.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by drizzlesconsin** [comment]
带 `-` 杠属于小写的一种

pages 目录都用全小写，多个单词用 `-` 隔开

components 大驼峰
