### ISSUE TITLE
antd Pro @umi4 版本 开启多Tabs 页报错

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design-pro#10226]
安装新版 @umi4
config.ts 
添加配置
keepalive: [/./],
tabsLayout: {},

报错

![image](https://user-images.githubusercontent.com/23204297/190124423-4072f3c1-f452-4a71-9e6c-bb049cac2328.png)
原因是多次引用了useAppData

修正了临时文件后 可以跑动
不过会出现标题undefined，且国际化失效

![image](https://user-images.githubusercontent.com/23204297/190124649-b813e5e2-39f3-4f3f-9769-bce86f92da3a.png)

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17 |
| System | win10 |
| Browser | chrome |

**Comment by lavandulor** [comment]
遇到相同的问题

**Comment by xiaohuoni** [comment]
应该更新一下 plugins 的版本就可以
https://github.com/alitajs/alita/issues/417#issuecomment-1247622694
