### ISSUE TITLE
👑 V6.0 多个请求怎么配置

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#10223]
### 🥰 需求描述 | Requirements description
应用内有多个请求需要处理，不需要走公共的`request`的配置

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/max/request

自己写个拦截器把，或者直接用fetch。

**Comment by 569202812** [comment]
> https://umijs.org/docs/max/request
> 
> 自己写个拦截器把，或者直接用fetch。

``
好吧那得用fetch了

**Comment by 569202812** [comment]
> https://umijs.org/docs/max/request
> 
> 自己写个拦截器把，或者直接用fetch。

或者暴露下axios也行，也不用自己在安装个依赖了

**Comment by chenshuai2144** [comment]
我们的对axios搞了不少东西，为了保证稳定，你还是安装一下

**Comment by 569202812** [comment]
> 我们的对axios搞了不少东西，为了保证稳定，你还是安装一下

ok
