### ISSUE TITLE
🐛 [BUG] 主站首页bug

### ISSUE THREAD

**Issue by KangXinzhi** [ant-design/ant-design-pro#10225]
![image](https://user-images.githubusercontent.com/50164727/190093975-55fda4fe-335e-457e-aa23-3f0ec926239b.png)

**Comment by chenshuai2144** [comment]
来个pr?

**Comment by KangXinzhi** [comment]
>

> 来个pr?

ok, https://github.com/ant-design/ant-design-pro-site/pull/638
