### ISSUE TITLE
🐛 [BUG] umi 4.0.19 login登录成功后首次 setInitialState 未成功，导致跳回login页面。第二次登录才进入首页

### ISSUE THREAD

**Issue by telanflow** [ant-design/ant-design-pro#10222]
### 🐛 bug 描述

setInitialState问题：login.tsx 登录成功后 setInitialState() 首次未生效，导致app.tsx layout事件中的 initialState.currentUser 为 undefined，从而login 跳转回login，再次去点击登录才进入welcome页面。

### 📷 复现步骤 | Recurrence steps

1. `pro create umi` 使用antd pro 创建的项目
2. 修改了 react 依赖版本 18.2.0，以及更新umi为最新版本

### 💻 复现代码 | Recurrence code

复现项目见：[参见此项目](https://github.com/telanflow/umi-4.0.19-bug)

### © 版本信息

- Ant Design Pro 版本: 4.23.1
- React 版本：18.2.0
- umi 版本：4.0.19
- 浏览器环境：chrome
- 开发环境：windows

### 🚑 其他信息

![log](https://github.com/telanflow/umi-4.0.19-bug/raw/master/debug.png) 

 ### 已在umi项目提issue，请看这个issue下的回复：[https://github.com/umijs/umi/issues/9295](https://github.com/umijs/umi/issues/9295)

**Comment by fz6m** [comment]
补充：这个问题是 setState 是异步的原因导致的，数据还没 set 进去就 push 跳走页面了，可能需要调整下逻辑 🤔

**Comment by zhaojunpeng0425** [comment]
![image](https://user-images.githubusercontent.com/94523508/191672590-0cf349ce-0d68-41af-b451-d7799bb0df1c.png)
如图，使用const { initialState, refresh, setInitialState } = useModel('@@initialState');中，refresh()重新更新一下全局的initialState

**Comment by sunjeen** [comment]
这refresh（）在我的环境还是有问题 react 18
最后借鉴了这里才能解决
https://github.com/umijs/umi/issues/9295
import { flushSync } from 'react-dom';

// ...

flushSync(() => {
  setInitialState((s) => ({
    ...s,
    currentUser: userInfo,
  }));
})
