### ISSUE TITLE
语雀的编辑器不错，有可能引入进来吗？

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#1022]
![image](https://user-images.githubusercontent.com/183884/36895580-4d192a86-1e4a-11e8-8a05-e39263c202eb.png)

**Comment by ddcat1115** [comment]
语雀编辑暂时还没有支持被外部引用，如有富文本需求建议选用 antd 推荐的社区组件：https://ant.design/docs/react/recommendation-cn

如果有时间，也可以自己基于语雀编辑器的底层 https://github.com/ianstormtaylor/slate 折腾下

**Comment by WuJiY** [comment]
好的 。谢谢

**Comment by wufeng87** [comment]
谢谢，开源几个slate插件也好呀。。

**Comment by fralychen** [comment]
https://www.slatejs.org/examples/markdown-shortcuts

**Comment by lk0606** [comment]
> 语雀编辑暂时还没有支持被外部引用，如有富文本需求建议选用 antd 推荐的社区组件：https://ant.design/docs/react/recommendation-cn
> 
> 如果有时间，也可以自己基于语雀编辑器的底层 https://github.com/ianstormtaylor/slate 折腾下

slate是不支持vue吗...

**Comment by imal1** [comment]
有一段时间都上线语雀编辑器官网了，怎么突然又不开源了
