### ISSUE TITLE
🐛 [BUG] Layout   token属性配置样式刷新失效

### ISSUE THREAD

**Issue by xiaqingping** [ant-design/ant-design-pro#10236]
### 🐛 bug 描述

配置 Layout   token属性 配置暗黑主题后，改变主题样式，dev环境测试没有问题，build后打开显示正常，刷新样式丢失

```
 token: {
    bgLayout: `url(${require('@/pages/Dashboard/style/images/bg.jpg')})`,
    colorBgAppListIconHover: textColor,
    sider: {
      colorTextMenu: textColor,
      colorBgCollapsedButton: '#3158a0',
      colorTextMenuTitle: textColor,
      colorTextMenuSelected: textActiveColor,
      colorTextMenuActive: textActiveColor,
      colorBgMenuItemSelected: 'rgba(2, 12, 116, 0.2)',
    },
}
```

**Comment by chenshuai2144** [comment]
能给个重现吗？ 我这里看起来没有问题。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以尝试在 `public/index.html` 中添加下列 meta 标签来解决样式刷新问题：

```html
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
```

这样可以禁用浏览器的缓存，确保每次刷新页面都会加载最新的样式文件。具体原理可以参考这篇文章 [浏览器缓存与刷新页面](https://www.cnblogs.com/larry-cache/p/6859901.html)。
