### ISSUE TITLE
🧐[问题 | question] 暗黑模式build到线上，样式丢失，只有部分页面变更了

### ISSUE THREAD

**Issue by chenyu1990** [ant-design/ant-design-pro#10237]
本地一切正常

线上不正常
![微信图片_20220920153657](https://user-images.githubusercontent.com/15179320/191196185-fc247af8-b489-40fc-9a5c-abecaeaf73e7.png)

**Comment by chenshuai2144** [comment]
看看样式优先级的问题，应该是加载顺序变了导致的。

https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity

跟着这个文档调整一下应该就好了
