### ISSUE TITLE
用脚手架创建Design Pro 项目一直提示下面错误，不知道怎么解决，请求帮助

### ISSUE THREAD

**Issue by jasonwang1109** [ant-design/ant-design-pro#10233]
用脚手架创建Design Pro 项目一直提示下面错误，不知道怎么解决，请求帮助

AssertionError [ERR_ASSERTION]: filePath not found of @ant-design/pro-layout/es/PageLoading
    at F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:119:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:64:103)
    at _next (F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:194)
    at F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:364
    at new Promise (<anonymous>)
    at F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:66:97
    at figureOutExport (F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\utils.js:129:17)
    at F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:84:103)
    at _next (F:\Work\Code\FreightCTO\DFC.WebAppClient\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\features\mfsu\DepBuilder.js:86:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.8",
    "@ant-design/pro-layout": "^7.0.7",  **--后期添加的，加了也不行**
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.20.0",
    "classnames": "^2.3.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-cookies": "^0.1.1",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-cookies": "^0.1.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.8.0",
    "@umijs/openapi": "^1.3.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^2.1.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.5.0",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
  },

**Comment by drizzlesconsin** [comment]
把 dynamicImport loading `@ant-design/pro-layout/es/PageLoading` 注释掉

**Comment by jasonwang1109** [comment]
> 把 dynamicImport loading `@ant-design/pro-layout/es/PageLoading` 注释掉

可以解决问题，@ant-design/pro-layout版本保留在6.35.0 也是没有问题，升级到 7.0 就出现问题了，应该是7.0 有什么改变

**Comment by yangbinsoft** [comment]
我也是这个问题

**Comment by edifangyi** [comment]
那使用 yarn add @ant-design/pro-components 依赖项目，咋办？？？

**Comment by drizzlesconsin** [comment]
新建的项目都是 Umi4, 新版 Pro Components 的 PageLoading 导出的方式改了。

正确的姿势就是手动建 `src/loading.tsx` 文件，根据项目自定义 Loading

**Comment by edifangyi** [comment]
> 新建的项目都是 Umi4, 新版 Pro Components 的 PageLoading 导出的方式改了。
> 
> 正确的姿势就是手动建`src/loading.tsx`文件，根据项目自定义加载

使用umi3一个样，新版的 Pro Components 就没的@ant-design/pro-layout/es/PageLoading

**Comment by drizzlesconsin** [comment]
复制[这个文件](https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/PageLoading/index.tsx)的内容，新建 `src/loading/tsx`, 解决问题。

新版 pro 这个文件不再默认导出。Umi 那边导入是 `import Loading from 'Loading'`

**Comment by edifangyi** [comment]
> 复制[这个文件](https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/PageLoading/index.tsx)的内容，新建`src/loading/tsx`，解决问题。
> 
> 新版亲这个文件不再是导出的。海米原来是导入的`import Loading from 'Loading'`

问一下，为什么不能直接改路径，引用‘@ant-design/pro-layout/es/components/PageLoading’ 路径下的

**Comment by drizzlesconsin** [comment]
是 PageLoading 的问题，`export { PageLoading }`

**Comment by edifangyi** [comment]
> 是 PageLoading 的问题，`export { PageLoading }`

好吧~，问最后一个问题，一般这种情况，哪方来修复这个问题？？？

**Comment by Daudxu** [comment]
一堆问题，解决一个来一个
