### ISSUE TITLE
🐛 [BUG] 开启多Tabs页面后，首次编译后登录会白屏

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design-pro#10235]
### 🐛 bug 描述

开启多tabs页后

start首次编译

登录进主界面后会进行白屏报错

![image](https://user-images.githubusercontent.com/23204297/190973235-7fd81d04-322c-4d6f-91f9-defb104b9030.png)

![image](https://user-images.githubusercontent.com/23204297/190973211-bf6e9d85-df4c-430a-933a-04a4b2e19fef.png)

尝试了一下
问题应该是一直重定向导致的

![image](https://user-images.githubusercontent.com/23204297/190981539-7aa77959-3a7d-4345-8f01-e6825b9c7b1d.png)

**Comment by chenshuai2144** [comment]
自己解决一下，是无限render导致的。
