### ISSUE TITLE
👑 [需求]TOKEN　缺少对面包屑导航背景色的配置！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#10232]
### 🥰 需求描述 | Requirements description

<img width="1743" alt="image" src="https://user-images.githubusercontent.com/12706830/190846255-65fefb22-deba-4381-a002-a6b396bfd4ce.png">
之前我提过，设置不生效，今天我重新下载配置后发现可以生效了，但是面包屑导航还是没有生效！我期望面包导航背景可以设置，不希望和下面内容一个色！红色区域是通过我修改css改的。不是通过token配置的。只有黄色是token改的！

### 🧐 解决方案 | Solution

希望增加一个配置

### 🚑 其他信息 | Other information
下面配置不能生效！
```
      pageContainer: {
        colorBgPageContainer: '#ffc324',
        colorBgPageContainerFixed: '#004FD9',
      },
```

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/192085082-5cb044ee-fee0-49f8-83cd-8f0f766d8522.png)


这个颜色是透明的？你能debug一下是被谁挡住了吗？

**Comment by codedart2018** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/192085082-5cb044ee-fee0-49f8-83cd-8f0f766d8522.png)
> 
> 这个颜色是透明的？你能debug一下是被谁挡住了吗？

就是默认是透明的，我希望加参数能配置。上面红色是我手动加的颜色！

**Comment by chenshuai2144** [comment]
你直接改背景不行吗？

**Comment by codedart2018** [comment]
> 

直接改可以，便我希望是配置方式改。不是通过手工css改！

**Comment by chenshuai2144** [comment]
我们希望默认是空的，
你可以用这个 pageHeaderBgGhost 或者用 css  覆盖吧
