### ISSUE TITLE
🧐[问题 | question]antd-pro开启多标签页报错

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10234]
### 🧐 问题描述 | Problem description

![image](https://user-images.githubusercontent.com/40554571/190940747-3246e738-98ae-4660-8a15-71cfce588cf8.png)

### 💻 示例代码 | Sample code

config/config.ts
`
keepalive: [/./],
  tabsLayout: {
    hasCustomTabs: true,
  }
`

### 🚑 其他信息 | Other information

ant-design-pro: 6.0.0-beta.1

@umijs/max: 4.0.18

OS: Window

Node：v16.16.0

浏览器 | browser：Chrome

**Comment by chenshuai2144** [comment]
多标签的问题去库的作者那里看看吧，我没用过这个
