### ISSUE TITLE
🧐[问题 | question]开启多标签 Tabs 后，请问怎么刷新当前子路由

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10238]
### 🧐 开启多标签 Tabs 后，请问怎么刷新当前子路由

我想做一个右键菜单，有刷新功能的，点击刷新会刷新当前路由，注意不是页面

请问我该怎么处理，antd-pro或者umi上是否有这样的API供开发者调用

### 版本信息

Ant Design Pro 版本: 6.0.0-beta.1
umi 版本: 4.0.21
浏览器环境: Google Chrome
开发环境 : windows
node.js: 16.16.0

**Comment by chenshuai2144** [comment]
去相应的社区问吧。官方这里不支持多标签的。
