### ISSUE TITLE
🐛 [BUG]umi4.x下面 配置多环境变量 打包模式下config.ts取的文件不对

### ISSUE THREAD

**Issue by pengxingwang** [ant-design/ant-design-pro#10239]
### 🐛 bug 描述

umi4.x下面 配置多环境变量 打包模式下config.ts取的文件不对。npm run build:uat 取到了prod下面的配置（npm run start:uat是正确的）

### 💻 复现代码 | Recurrence code

    // package.json
     "start": "cross-env UMI_ENV=dev max dev",
      "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev",
      "start:uat": "cross-env REACT_APP_ENV=uat MOCK=none UMI_ENV=uat max dev",
      "start:prod": "cross-env REACT_APP_ENV=prod MOCK=none UMI_ENV=prod max dev",
      "build:dev": "cross-env REACT_APP_ENV=dev UMI_ENV=dev max build",
      "build:uat": "cross-env REACT_APP_ENV=uat UMI_ENV=uat max build",
      "build:prod": "cross-env REACT_APP_ENV=prod UMI_ENV=prod max build"

    // config.uat.ts
    import { defineConfig } from 'umi';
   
    export default defineConfig({
      define: {
        OSS_FILE_URL_PREFIX: 'OSS_FILE_URL_PREFIX',
        API_PREFIX: 'API_PREFIX',
      },
    });

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 6.0.0-beta.1
- umi 版本 4.x
- 浏览器环境 chrome 
- 开发环境 [e.g. mac OS] mac and  centos

### 🚑 其他信息

确保 uat 和 prod 的环境变量不一致

**Comment by zhaojunpeng0425** [comment]
不要用正常的dev,pre,prod等字样，可以使用_dev, _test,_pre等

**Comment by chenshuai2144** [comment]
"start:dev": "cross-env REACT_APP_ENV=mydev MOCK=none UMI_ENV=dev max dev",

然后 // config.mydev.ts

**Comment by chentiewei** [comment]
> `"start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=mydev max dev",`
> 
> 然后 // config.mydev.ts

这是为什么？

**Comment by chenshuai2144** [comment]
是 umi 约定的一个环境变量。用来读取配置文件

**Comment by chentiewei** [comment]
emmm 我的意思是 为啥 一定要改名字 而且我修改了以后 在使用build的时候还是有问题。

"build:dev": "cross-env REACT_APP_ENV=dev UMI_ENV=mydev max build",

打包的文件还是  // config.prod.ts  而不是我重新命名的 // config.mydev.ts

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/215302778-ca463ef6-9a7d-4e6a-b94b-2b720c04cc27.png)
按照优先级来看，`npm run build` 之后，以 `config.prod.ts` 的优先级最高，所以需要把这个也改名。而我们自定义的环境变量名优先级在 2（图中第二行）

**Comment by visla-perlin** [comment]
这设计的优势是什么？感觉带来了很大的困扰

**Comment by IOLOII** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/34856171/c3eefee9-6749-42b4-809c-b6d8d731d71e)
在我运行 nom run build 之后，我希望打包时使用的env配置是.env.production文件（不是指config文件），但是没有生效，脚本改成 "build": "cross-env REACT_APP_ENV=production max build", 之后也是使用的development环境
