### ISSUE TITLE
👑 [需求]LightFilter里面放置ProFormSelect，只能点击显示下拉列表，是否可以鼠标移上时显示下拉列表，鼠标移出隐藏下拉列

### ISSUE THREAD

**Issue by KamChing** [ant-design/ant-design-pro#10241]
### 🥰 需求描述 | Requirements description

比如像这里，点击了性别，才显示选择列表，想要鼠标移上去，显示，并且鼠标移出性别和下拉列表时，隐藏下拉列表
### 🧐 解决方案 | Solution

无

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/30040491/191408039-5334f62c-a0af-4e73-a0fe-c1eba6fe6ea7.png)

**Comment by chenshuai2144** [comment]
现在不支持，你看可以自定义render一下。hover事件容易误触。推荐不要这样搞
