### ISSUE TITLE
🧐[问题 | question]我需要在v5版本中加载glb文件，但是没有响应的webpack入口，也没办法run eject，如何去添加相应的loader？

### ISSUE THREAD

**Issue by lvzhongyuCode** [ant-design/ant-design-pro#10242]
### 💻 示例代码 | Sample code
const WeaponUrl = require('../threeBai/resources/model/rpg/rpg2.glb');

### 🚑 其他信息 | Other information

![图片](https://user-images.githubusercontent.com/28751933/191458285-45461138-e4e4-4ee2-a38a-761d01d746b4.png)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/api/config#chainwebpack

这里
