### ISSUE TITLE
🧐[问题 | question]请问如何正确导入md文件？即md文件作为页面展示。

### ISSUE THREAD

**Issue by andrewgogogo** [ant-design/ant-design-pro#10245]
###
请问如何正确导入md文件？即md文件作为页面展示。

**Comment by andrewgogogo** [comment]
求助求助，太难了

**Comment by andrewgogogo** [comment]
> 这是pro该干的事嘛, 这不是[dumi](https://d.umijs.org/)的事嘛

就是导入md文件的时候会提示找不到模块，可否提供方案参考？
/* eslint-disable react/no-children-prop */
import ReactMarkdown from 'react-markdown';
import Test from 'test.md';

// const Test = '123';

function App() {
  return (
    <div>
      <ReactMarkdown children={`${Test}`} />
    </div>
  );
}

export default App;

**Comment by chenshuai2144** [comment]
改使用dumi吧，有个专门的模式用于和系统搭配
