### ISSUE TITLE
🐛 [BUG] 开启多Tabs页面后，关闭tab标签会导致margin溢出

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design-pro#10240]
https://github.com/alitajs/alita/issues/425

正常情况下是贴合左边的
![image](https://user-images.githubusercontent.com/23204297/191217547-e7c214dd-7776-47a3-9bde-7d05eb340a28.png)

当关闭其中一个tab页面后就会出现

![image](https://user-images.githubusercontent.com/23204297/191217322-dbb41e33-2920-404c-aadb-e2d232b64d53.png)

看了一下是缺少了 margin： 0
![image](https://user-images.githubusercontent.com/23204297/191218032-4d9ad664-c462-4dd6-a215-12a3d20bbb8f.png)

**Comment by chenshuai2144** [comment]
<html>
<body>


token | 说明 | 默认值
-- | -- | --
marginBlockPageContainerContent | pageContainer 自带的 margin block | 24
marginInlinePageContainerContent | pageContainer 自带的 margin inline | 40


</body>
</html>

可以把这两个设置为 0
