### ISSUE TITLE
🧐[问题 | question]菜单如何自定义icon颜色成主题色

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10252]
### 🧐 问题描述 | Problem description
菜单如何自定义icon颜色成主题色，想菜单图标的颜色跟随主体变化，像下图列表一样
![image](https://user-images.githubusercontent.com/40554571/192128892-5291ddac-82d3-452f-87cb-8e56fe992d23.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
<html>
<body>



iconfontUrl | 使用 IconFont 的图标配置 | URL
-- | -- | --



</body>
</html>iconfontUrl	使用 [IconFont](https://ant.design/components/icon-cn/#components-icon-demo-iconfont) 的图标配置	URL



https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont

看看这里

**Comment by Cyan-Xmw** [comment]
> iconfontUrl	使用 IconFont 的图标配置	URLiconfontUrl 使用 [IconFont](https://ant.design/components/icon-cn/#components-icon-demo-iconfont) 的图标配置 URL
> https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont
> 
> 看看这里

现在菜单icon就是通过iconfont引入的，但不知道如何修改icon颜色，还是说iconfont引入的图标只能在iconfont平台上设置好颜色才行，antd-pro团队可以提供一个配置项吗
![image](https://user-images.githubusercontent.com/40554571/192129090-02c20954-f039-4ab0-8671-f6fa599ca457.png)

**Comment by chenshuai2144** [comment]
iconfont 如果是svg就支持的，不过要处理下默认不要带颜色。

![image](https://user-images.githubusercontent.com/8186664/192129319-2319f701-0934-4704-ba74-2bb56ad47f23.png)


让你们美工处理一下

**Comment by Cyan-Xmw** [comment]
> iconfont 如果是svg就支持的，不过要处理下默认不要带颜色。
> 
> ![image](https://user-images.githubusercontent.com/8186664/192129319-2319f701-0934-4704-ba74-2bb56ad47f23.png)
> 
> 让你们美工处理一下

现在iconfont上的菜单icon已经全部多了去色处理，请问下该如何配置才能兼容菜单的全部格式呢。
目前我自己在layout上自定义了subMenuItemRender和menuItemRender，但是结果只有侧边菜单才会正常，顶部菜单和分割菜单没有，大哥能给个思路吗
![image](https://user-images.githubusercontent.com/40554571/192130101-187a9e17-d75e-4fe3-a885-a9a047c6653f.png)
这种布局颜色可以出来
![image](https://user-images.githubusercontent.com/40554571/192130113-6953a19a-f628-47dd-8dca-11fd84535923.png)
但切换顶部布局和菜单分组模式就不行了
![image](https://user-images.githubusercontent.com/40554571/192130133-fe9deb7d-de66-497d-9aa1-bad751a14d11.png)
![image](https://user-images.githubusercontent.com/40554571/192130140-50a256bf-7850-4f56-aafc-0889fa56af55.png)
请问有没有方法可以统一配置icon颜色的
