### ISSUE TITLE
🧐[问题 | question] 6.0 路由配置使用 routes 提示警告即将废弃，改为 children 无法编译，该如何处理？

### ISSUE THREAD

**Issue by houkunlin** [ant-design/ant-design-pro#10258]
### 🧐 问题描述 | Problem description

在 `config/routes.ts` 配置文件中使用 `routes` 来配置路由是正常可以编译运行的，但是浏览器访问的时候控制台提示警告信息，如果改为 `children` 则无法编译通过。
目前的这种情况该如何改为正确的配置。
![image](https://user-images.githubusercontent.com/12333292/192216580-a5fb8da1-4773-487e-b45e-9cfafd073099.png)
![image](https://user-images.githubusercontent.com/12333292/192216615-308bc674-4f5e-4e60-af14-52ce65035bab.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：最新版
`@umijs/max` 已安装版本: 4.0.21
`@ant-design/pro-components` 已安装版本: 2.3.10

**Comment by jalog** [comment]
同问

**Comment by chenshuai2144** [comment]
是插件的问题，先忽略一下
