### ISSUE TITLE
6.0什么时候发布正式版

### ISSUE THREAD

**Issue by SoftwareKing** [ant-design/ant-design-pro#10254]
6.0什么时候发布正式版

**Comment by duwei54** [comment]
> 6.0什么时候发布正式版

@SoftwareKing 大佬也关注这个呀

**Comment by sy296565890** [comment]
同问，并且非常喜欢区块

**Comment by j511002** [comment]
同问，是要等antd发布5.0之后吗？

**Comment by TianQingshuai** [comment]
同问，感谢

**Comment by lontten** [comment]
同问

**Comment by chenshuai2144** [comment]
和 antd 一起发，应该在 11.18 的时候

**Comment by duwei54** [comment]
> 和 antd 一起发，应该在 11.18 的时候

@chenshuai2144 大佬, 想了解一下大概啥时候能出正式版呢. ant 5 发布了, 好想看看pro 😄
