### ISSUE TITLE
🧐[问题 | question]使用umi3搭建的初始化项目，404页面显示问题

### ISSUE THREAD

**Issue by zhoukai12** [ant-design/ant-design-pro#10259]
### 🧐 问题描述 | Problem description

配置404页面的layout为false，但是匹配到无效路径的时候，左侧菜单栏还会显示，如何改成像login一样的全屏显示呢
 {
        layout: false,
        component: './404',
    },

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 解决方案 | Solution

您可以将 `layout` 设置为一个自定义布局组件，并在其中控制是否显示菜单栏。

如下所示：

```javascript
// 引入依赖
import React from 'react';
import { BasicLayoutProps } from '@ant-design/pro-layout';

// 定义自定义布局组件
const CustomLayout: React.FC<BasicLayoutProps> = ({ location, children }) => {
  // 根据路径判断是否显示菜单栏
  const { pathname } = location;
  const showMenu = pathname !== '/login' && pathname !== '/404';

  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      {/* 根据路径显示/隐藏菜单栏 */}
      {showMenu && (
        <div style={{ height: '64px', backgroundColor: '#fff', padding: '0 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', height: '100%' }}>
            <div style={{ marginRight: '24px' }}>logo</div>
            <div>menu</div>
          </div>
        </div>
      )}
      {/* 渲染子组件 */}
      <div style={{ flex: 1 }}>{children}</div>
    </div>
  );
};

export default CustomLayout;
```

然后在路由配置中将 `layout` 设置为该组件即可：

```javascript
{
  path: '/404',
  component: './404',
  layout: CustomLayout,
},
```

这样就可以实现匹配到无效路径时全屏显示的效果。
