### ISSUE TITLE
🐛 [BUG]升级layout版本后，路由菜单不显示

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10251]
### 🐛 bug 描述
之前一切正常，升级了@ant-design/pro-components后，路由可以访问，但菜单不显示
![image](https://user-images.githubusercontent.com/40554571/192110611-92596b3d-bf55-4a3a-9115-b14402db2db4.png)

我看了@ant-design/pro-components的升级文档：https://github.com/ant-design/pro-components/commit/6c54c7e

看他们把route中的routes改成children，不知道对此有没影响，但我改成children无法运行

### 📷 复现步骤 | Recurrence steps

路由配置：
![image](https://user-images.githubusercontent.com/40554571/192110736-c5036d61-5a71-4ec4-b633-3668056a97d6.png)

### 🏞 期望结果 | Expected results

layout菜单能正常显示

### 💻 复现代码 | Recurrence code

Github: https://github.com/Cyan-Xmw/react-umi-xmw/blob/Cyan/Xmw_web/config/routes.ts

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本: 4.0.21
- @ant-design/pro-components: 2.3.12
- 浏览器环境: 谷歌浏览器
- 开发环境 : window

**Comment by Ruboyq** [comment]
你好，请问解决了吗，遇到一样的问题了。。

**Comment by Cyan-Xmw** [comment]
> 你好，请问解决了吗，遇到一样的问题了。。

你用了tabLayout多标签页吗，把这个关了就可以了

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/alita/issues/436
