### ISSUE TITLE
🐛 [BUG]SettingDrawer改变主题色不生效

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10250]
### 🐛 SettingDrawer改变主题色不生效，只有配置了config.ts里面的theme第一次生效

![image](https://user-images.githubusercontent.com/40554571/192093891-31604792-d669-4bbc-a2c3-7597b1a334b4.png)

我看antd-pro官方示例是可以的，但不知道为啥我的不行

### 📷 复现步骤 | Recurrence steps

1、/config/config.ts 配置
`
 theme: {
    "primary-color": "#52c41a",
    "blue-base": "#52c41a",
    // 如果不想要 configProvide 动态设置主题需要把这个设置为 default
    // 只有设置为 variable， 才能使用 configProvide 动态设置主色调
    'root-entry-name': 'variable',
  }
`
1、/config/defaultSettings.ts 配置
`
const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: true,
  fixSiderbar: true,
  colorWeak: false,
  title: 'React Umi Xmw',
  pwa: false,
  logo: '/logo.svg',
  iconfontUrl: '/favicon.ico',
}
`

### 🏞 期望结果 | Expected results

SettingDrawer改变主题色，antd组件主题色能跟着变化

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本: 4.0.21
- 浏览器环境: 谷歌浏览器
- 开发环境 : window

**Comment by chenshuai2144** [comment]
fix by https://github.com/ant-design/pro-components/commit/be6ab651cb1832c96cb0a1e1bafa1668795a0ceb


升级一下 layout 的版本
