### ISSUE TITLE
🐛 [BUG]tabs用法升级后，PageContainer升级到最新后，其中的Tabs依然报warning

### ISSUE THREAD

**Issue by papillon328** [ant-design/ant-design-pro#10255]
### 🐛 [BUG]描述

根据官方文档描述，‘在 4.23.0 版本后，我们提供了 <Tabs items={[...]} /> 的简写方式，有更好的性能和更方便的数据组织方式，开发者不再需要自行拼接 JSX。同时我们废弃了原先的写法，你还是可以在 4.x 继续使用，但会在控制台看到警告，并会在 5.0 后移除。’
我升级了ant-design，tabs用法需要更新，才能不报错。但是在PageContainer组件中引入了tabs，已经将PageContainer升级到最新了，仍然会报错，关于PageContainer的写法官网文档未及时更新，不知道是否是写法有问题？

### 📷 复现步骤 | Recurrence steps

复现代码
<PageContainer
      tabList={[
        {
        tab: "tab1",
        key: "tab1",
        closable: false,
      },
    {
        tab: "tab2",
        key: "tab2",
      },
     ]}
      tabProps={{
        type: "editable-card",
        size: "small",
        hideAdd: true,
      }}
      onTabChange={() => {}}
    ></PageContainer>
    
    报错信息
    Warning: [antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly. 

### 🏞 期望结果 | Expected results
期望不出现报错

### © 版本信息

- antd 版本:4.23.0
- @ant-design/pro-layout 版本: 7.1.2
- umi 版本: 3.5.0
- 浏览器环境
- 开发环境 ：mac OS

**Comment by chenshuai2144** [comment]
升级到 7.1.15，旧版本的没有处理过了
