### ISSUE TITLE
🐛 [BUG] 开启全局model 后，引用 namespace 报错

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design-pro#10266]
![image](https://user-images.githubusercontent.com/23204297/192959730-37269d27-007f-4a17-9cfa-543b6dbdc39a.png)

**Comment by lvdougao1** [comment]
重新跑下项目就好了

**Comment by zozopen** [comment]
> 

不行的，请教下还有其他操作吗

**Comment by boxdz** [comment]
同问，删除插件重跑项目都不行
