### ISSUE TITLE
🧐[问题 | question]在 centos7 的开发环境下启动项目，浏览器显示白板

### ISSUE THREAD

**Issue by yule2001** [ant-design/ant-design-pro#10264]
### 🧐 问题描述 | Problem description
如题

### 💻 示例代码 | Sample code

无

### 🚑 其他信息 | Other information
浏览器显示：
![图片](https://user-images.githubusercontent.com/9146051/192677024-5d9ad917-7f07-41a1-83b8-3026ccdcf08c.png)

控制台错误信息：
![图片](https://user-images.githubusercontent.com/9146051/192676961-70b212a2-9dc1-4199-b7ab-b1d0ae4b9813.png)

日志信息：
![图片](https://user-images.githubusercontent.com/9146051/192677381-26a0edd0-d78b-4d7a-bf39-097138265921.png)

OS:
服务器 centos7
客户端 windows 10

Node：
V16.15.1
浏览器 | browser：
chrome 105.0.5195.127

**Comment by yule2001** [comment]
问题在于，我在服务器之外，通过ip访问，理论上，应该调用http://10.10.9.36:8000/mf-va_remoteEntry.js，但还是调用了localhost地址，所以无法加载

**Comment by chenshuai2144** [comment]
fixed。 try rebuild
