### ISSUE TITLE
node版本更新了很多次，但是还是出现错误，是不是有其他原因？请大牛帮忙！

### ISSUE THREAD

**Issue by cyp66** [ant-design/ant-design-pro#1026]
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npm.taobao.org/antd/download/antd-3
.2.2.tgz failed, reason: getaddrinfo ENOTFOUND server server:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huitong\AppData\Roaming\npm-cache\_logs\2018-03-05T00_51_5
8_884Z-debug.log

**Comment by ddcat1115** [comment]
重现步骤？

**Comment by chenshuai2144** [comment]
你这个错误的关键字是网络错误。
你是不是代理忘记关了？

**Comment by cyp66** [comment]
怎么关闭代理

**Comment by chenshuai2144** [comment]
请自行百度

**Comment by cyp66** [comment]
嗯嗯，已经查过啦，现在又出现网络错误。

**Comment by cyp66** [comment]
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npm.taobao.org/cnpm failed, reason:
 getaddrinfo ENOTFOUND server server:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huitong\AppData\Roaming\npm-cache\_logs\2018-03-05T11_36_5
6_050Z-debug.log

D:\nodejs\node_modules>

**Comment by cyp66** [comment]
淘宝镜像，delete过了，后来根据百度提示我又安装上了。

**Comment by chenshuai2144** [comment]
你的代理跪了 你应该看看代理

**Comment by afc163** [comment]
非 antd pro 问题，建议到其他地方进行提问。
