### ISSUE TITLE
在运行时app.ts ，如何取路径？

### ISSUE THREAD

**Issue by lecd** [ant-design/ant-design-pro#10267]
1.我的项目是部署在非根目录下，在配置必须上base。
在运行时app.ts 取路径时， 使用 import { history } from '@umijs/max';
const { location } = history;  返回的pathname 加上非必要的base，需要做路径判断都要加上base这一级，太难了。

2.运行时app.ts 不允许使用hooks，  const location = useLocation(); 

![image](https://user-images.githubusercontent.com/17017158/192971809-a35f6245-3d79-466a-a098-e0aede8f86d4.png)

### © 版本信息
![image](https://user-images.githubusercontent.com/17017158/192972161-8fcf64bc-54f9-41bd-9650-6a29f6b4fbb9.png)

**Comment by echoyl** [comment]
试试 这个window.location ？

**Comment by chenshuai2144** [comment]
在 app.ts 里面没必要用uselocation ，直接用 window.location
