### ISSUE TITLE
🐛 [BUG]最新6.0.0-beta.1 yarn i18n-remove 报错

### ISSUE THREAD

**Issue by loseleo** [ant-design/ant-design-pro#10273]
### 🐛 bug 描述

最新6.0.0-beta.1 版本在使用 yarn i18n-remove 报错

### 📷 复现步骤 | Recurrence steps
npm i @ant-design/pro-cli -g
pro create myapp
cd myapp 
yarn
yarn  i18n-remove

![image](https://user-images.githubusercontent.com/4935557/193219944-a4636b03-fe5a-4eb7-bebf-3c73cbc7505c.png)
![image](https://user-images.githubusercontent.com/4935557/193220113-23d20de6-eb1a-44e8-b6e1-39ad328ec510.png)

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- 开发环境 mac OS

**Comment by cuiliming666** [comment]
v5版本也遇到同样问题

**Comment by manneia** [comment]
me too

**Comment by fandych** [comment]
修改如下代码，执行成功
node_modules/node-import-ts/lib/index.js
```
//noEmitOnError: true,
noEmitOnError: false,
```

**Comment by dingtianxiu** [comment]
目前看未发现该问题，考虑是否自己的类型错误导致ts emit时跳过该文件处理

**Comment by darkfiredarkhalo** [comment]
> 目前看未发现该问题，考虑是否自己的类型错误导致ts emit时跳过该文件处理

不是, 创建项目`npm install`后立即执行`npm run i18n-remove`就会报这个错误

**Comment by 596094101** [comment]
> 目前看未发现该问题，考虑是否自己的类型错误导致ts emit时跳过该文件处理

这个明显不应该靠改node_modules下的文件来解决问题吧，新拉下来的代码执行直接报错，没有解决但是直接关了不合适

**Comment by odetteasosborneas** [comment]
这个问题到现在没有解决。拉下代码后，pnpm install 完事儿后，执行 i18n-remove 依然这个错误。
