### ISSUE TITLE
项目执行了npm update后，LessError 报错，怎么处理

### ISSUE THREAD

**Issue by 429299291** [ant-design/ant-design-pro#10279]
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
Error occurred compiling file /Users/zhudongdong/Desktop/home/src/pages/Account/Center/Center.less
Error [LessError: .textOverflow is undefined] {
  type: 'Name',
  filename: '/Users/zhudongdong/Desktop/home/src/pages/Account/Center/Center.less',
  index: 1269,
  line: 85,
  column: 4,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '    transition: color 0.3s;', '    .textOverflow();', '' ]
}
![image](https://user-images.githubusercontent.com/29189973/194746580-99801e92-2c26-4198-831b-78be85bdb542.png)

**Comment by wufu-fire** [comment]
update 后，经常出问题，他们升级的时候感觉都不测试，直接盲发，我也是服了。

**Comment by 429299291** [comment]
这真的只是antd的问题吗，不是我本地配置有问题吗？每次看到这些报错都很头大

**Comment by chenshuai2144** [comment]
这个less 变量没有了的样子，你直接删掉吧

**Comment by 429299291** [comment]
> 这个less 变量没有了的样子，你直接删掉吧

有，我删了，看着省心，
