### ISSUE TITLE
🐛 [BUG]Login successful but can't  redirect to ‘/welcome’ and logout error

### ISSUE THREAD

**Issue by PandaYip** [ant-design/ant-design-pro#10276]
### 🐛 bug 描述

1、登录成功，但是无法转跳到‘/welcome’页面，尤其在点击退出登录之后再登录，100%复现。
2、退出登录出错，错误信息
Unhandled Rejection (TypeError): URL constructor:  is not a valid URL.

### 📷 复现步骤 | Recurrence steps

1、按照官方教程使用umi@4创建一个新的pro项目
2、使用npm run start 运行项目
3、打开 http://localhost:8000 登录项目，稳定复现，同时console还会有另外一个错误（见下图1）
4、再次访问 http://localhost:8000 ，发现已经自动转跳到welcome页面
5、点击退出登录，出现错误（见下图2）

### 🏞 期望结果 | Expected results

我使用过旧版的ant design pro 6.0.0.beta.1 配合的大概是umi < 4.0.20，当时时正常的，后来因为一个其他的bug我升级了umi的版本，就开始出问题了，后续我发现重新创建一个新的项目，也会稳定复现，所以大概判断是一个BUG。

### 💻 复现代码 | Recurrence code

直接按照官方教程初始化一个项目即可

### © 版本信息

- Ant Design Pro 版本:  6.0.0-beta.1
- umi 版本 4.0.24
- 浏览器环境 chrome  106.0.5249.103 (64位)
- 开发环境 [e.g. mac OS] windows 11

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/13165391/194705570-97485f57-5d78-4b06-82a0-76c55cf4b633.png)

![图片](https://user-images.githubusercontent.com/13165391/194705547-ba8e816b-6249-4f10-8e7e-2ac33e4e5f20.png)

**Comment by PandaYip** [comment]
为了方便大佬们debug，我把我的package.json贴在这里
`{
  "name": "ant-design-pro",
  "version": "6.0.0-beta.1",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 max build",
    "build": "max build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "max setup",
    "lint": "npm run lint:js && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src ",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "openapi": "max openapi",
    "playwright": "playwright install && playwright test",
    "prepare": "husky install",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev max dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev max dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev max dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev max dev",
    "test:e2e": "node ./tests/run-tests.js",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.13",
    "@umijs/route-utils": "^2.2.0",
    "antd": "^4.23.4",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.6.4",
    "rc-util": "^5.24.4",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.8.1",
    "react-dom": "^17.0.2",
    "react-helmet-async": "^1.3.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.5",
    "@playwright/test": "^1.27.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.14",
    "@types/history": "^4.7.11",
    "@types/lodash": "^4.14.186",
    "@types/react": "^17.0.50",
    "@types/react-dom": "^17.0.17",
    "@types/react-helmet": "^6.1.5",
    "@umijs/fabric": "^2.14.0",
    "@umijs/max": "^4.0.24",
    "@umijs/openapi": "^1.7.0",
    "cross-env": "^7.0.3",
    "cross-port-killer": "^1.4.0",
    "detect-installer": "^1.0.2",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.3",
    "husky": "^7.0.4",
    "lint-staged": "^10.5.4",
    "mockjs": "^1.1.0",
    "prettier": "^2.7.1",
    "swagger-ui-dist": "^4.14.2",
    "typescript": "^4.8.4",
    "umi-presets-pro": "^1.0.5",
    "umi-serve": "^1.9.11"
  },
  "engines": {
    "node": ">=12.0.0"
  }
}
`

**Comment by aibps** [comment]
+1

**Comment by PandaYip** [comment]
最早在项目中应用的时候，ant design pro 也是6.0.0-beta.1，umi< 4.0.20，everything works
然后因为其他的bug，我把依赖升级了 umi 升级到了 4.0.20 ，然后就发现这个bug，我最早以为是我修改了登录跟currentUser相关的代码导致的。
然后我又更新了所有依赖，发现问题依旧，还引入了一个ant.design Tabs相关的废弃告警，我都手工fix了，发现这个问题依然没有改善。
最后我新建了一个测试项目，发现原来是稳定复现的。
我的下一步计划是降级umi的版本看看

**Comment by eskyray** [comment]
+1

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/pull/10257/files
这个改一下，const urlParams = new URL(window.location.href).searchParams;

**Comment by guwan** [comment]
> https://github.com/ant-design/ant-design-pro/pull/10257/files 这个改一下，const urlParams = new URL(window.location.href).searchParams;

我也碰到了这个问题，这个修改并不生效，我的权限是从后台获取的。
这个修改里面最关键的一点是await refresh();而这会将我后台获取到的目录权限刷新掉。
