### ISSUE TITLE
🐛 [BUG]V6 beta版本build编译代码后包含swagger-ui-dist代码导致浏览器兼容问题

### ISSUE THREAD

**Issue by lovewinders** [ant-design/ant-design-pro#10272]
### 🐛 bug 描述
V6 beta执行npm run build编译后代码包含swagger-ui-dist编译后代码

### 📷 复现步骤 | Recurrence steps
第一步：git clone v6.0.0-beta最新代码
第二步：执行编译命令
```
npm run build
```
第三步：查看dist内umi.xxx.js文件内会包含swagger-ui-dist的代码，该代码内有??操作符（nullish-coalescing-operator）导致360极速最新浏览器无法识别??符号，页面出现白屏；

### 🏞 期望结果 | Expected results
期望生产环境编译后的代码内不要有openAPI和swagger-ui-dist的编译源码存在

### 💻 复现代码 | Recurrence code
<img width="1562" alt="image" src="https://user-images.githubusercontent.com/22837419/193211263-274a1ce4-fafc-4d4b-a1da-b6b092779942.png">
<img width="2364" alt="image" src="https://user-images.githubusercontent.com/22837419/193211420-c0a82a29-2944-4ed8-a69a-9bba410bc9c4.png">

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://github.com/umijs/plugins/blob/9f03cb623dd84cd1f6acdfb8ce52aa94e4f6e916/packages/plugin-openapi/src/index.ts#L102

做了相关的配置，你改了环境变量吗

**Comment by lovewinders** [comment]
> https://github.com/umijs/plugins/blob/9f03cb623dd84cd1f6acdfb8ce52aa94e4f6e916/packages/plugin-openapi/src/index.ts#L102
> 
> 做了相关的配置，你改了环境变量吗

复现路径：我只是把v6 beta master分支下载下来直接npm run build就会出现360极速浏览器该问题，我本机是没有做环境变量cross env设置的，我怀疑是你写法问题没有触发webpack tree-sharking导致代码被编译进入dist，虽然.UI层看起来没有swagger-ui的影子

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以尝试在`package.json`中配置`cross-env UMI_ENV=prod`，然后再执行`npm run build`，这样可以强制使用production环境，也可以去掉开发环境的依赖，减小打包后的体积。

除此之外，也可以修改构建配置，在`webpack.prod.js`中将`mode`设为`production`，这样也会在打包时去掉开发环境相关的代码。

如果以上方法都不能解决问题，可以尝试手动移除`swagger-ui-dist`的引入，可以在`.umirc.ts`中添加以下代码：

```typescript
export const chainWebpack = (config: any) => {
  config.optimization.delete("splitChunks");
  config.module.rules.forEach((rule: any) => {
    if (rule.oneOf) {
      rule.oneOf.forEach((r: any) => {
        if (r.test && r.test.toString().includes("swagger-ui-dist")) {
          r.use = [];
        }
      });
    }
  });
  return config;
}
```

这个方法会将分包和`swagger-ui-dist`的引入都移除掉，如果对体积要求不高可以使用，否则可以结合webpack的tree-shaking来优化这个问题。
