### ISSUE TITLE
🧐[问题 | question]proForm中使用disabled属性报错：不存在属性disabled

### ISSUE THREAD

**Issue by SilentRio** [ant-design/ant-design-pro#10286]
报错如图：
<img width="720" alt="image" src="https://user-images.githubusercontent.com/19779285/194990885-8036ee57-eaaf-4c52-835c-11b4b4526a6b.png">

使用的包版本如下：

<img width="312" alt="image" src="https://user-images.githubusercontent.com/19779285/194990904-504facb6-4ec5-461d-8ded-4a090b97d291.png">
<img width="242" alt="image" src="https://user-images.githubusercontent.com/19779285/194990917-ea88c137-0344-4cb3-8255-1713b1177eef.png">
<img width="487" alt="image" src="https://user-images.githubusercontent.com/19779285/194990928-e6f3eafa-7ed4-4805-a53d-3d869b14f41b.png">

**Comment by chenshuai2144** [comment]
不支持整体的disbale的，只支持一个有一个
