### ISSUE TITLE
🧐 新logo 图片自动加了宽度

### ISSUE THREAD

**Issue by smiletrl** [ant-design/ant-design-pro#10287]
### 🧐 问题描述 | Problem description

我们换了个新logo，然后不知道为什么，logo image 自动加了个width 22. 然后logo 就显示得很奇怪了

### 💻 示例代码 | Sample code

```
const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: '言林公众号管理台',
  pwa: false,
  logo: 'https://digitalyl-resources.oss-cn-shanghai.aliyuncs.com/yanlin/wechat-official.jpg',
  iconfontUrl: '',
};
```

### 🚑 其他信息 | Other information

<img width="829" alt="Screen Shot 2022-10-12 at 09 56 26" src="https://user-images.githubusercontent.com/2764799/195231239-72efc4f3-aba4-438b-ad5e-82eb8c0ce67e.png">

OS: 容器部署 `FROM nginx:1.13-alpine`

Node：14 

浏览器 | browser：chrome

**Comment by chenshuai2144** [comment]
修改了一下设置了一个高度，不然会导致了 img  撑开的特别大
