### ISSUE TITLE
🧐[问题 | question]怎样在getInitialState初始化数据并保存到redux中

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10285]
### 🧐 现在有个问题，就是我做了动态国际化多语言，想在一开始就调用，一开始是在getInitialState中调用的，但是我又想把数据保存在redux中，请问怎么做就能保证调用一次就可以

初始化要做的事：
1、把 locales 保存在 getInitialState 中
2、把 locales 保存在 redux 中
3、调用一次接口
4、在 getInitialState 中调用 dispatch 不生效，但也不报错
app.tsx
`
export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  loading?: boolean;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
  locales?: any
}> {
  // 初始化多语言
  const locales = await initLocalesLang()
  const umi_layout = window.localStorage.getItem('umi_layout')
  const fetchUserInfo = async () => {
    try {
      const msg = await queryCurrentUser({
        skipErrorHandler: true,
      });
      return msg.data;
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };
  // 如果不是登录页面，执行
  if (window.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: umi_layout && JSON.parse(umi_layout) || defaultSettings,
    };
  }
  return {
    fetchUserInfo,
    settings: defaultSettings,
    locales
  };
}
`
models/localesModel.ts
`
import { getAllLocalesLang } from '@/services/system/internationalization'; //获取国际化多语言层级对象

export default {
  // model 中的数据
  state: {
    locales: {},
  },
  // 异步 action，用来发送异步请求
  effects: {
    *initLocales({ payload }: any, { call, put }: any): any {
      const response = yield call(getAllLocalesLang, payload);
      yield put({
        type: 'changeLocales',
        payload: response.resData,
      });
      return response;
    },
  },
  // 同步 action，用来修改 state
  reducers: {
    changeLocales(state: any, { payload }: any) {
      return {
        ...state,
        locales: payload,
      };
    },
  },
  // 该选项中的函数自定义命名?函数的触发时机是初始时，主要用来初始化模块状态或者做一些准备性工作
  subscriptions: {
    loadData({ dispatch }: any) {
      dispatch({ type: 'initLocales', payload: {} });
    },
  },
};
`

### 🚑 其他信息 | Other information

ant-design-pro: 6.0.0-beta.1

OS:

Node：v16.16.0

浏览器 | browser：Google

**Comment by chenshuai2144** [comment]
两种数据流不要混用，用redux 就直接用redux
