### ISSUE TITLE
🐛 [BUG] Ant Design Pro 登录页面帐号密码登录后，控制台提示：Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by RainThinks** [ant-design/ant-design-pro#10283]
### 🐛 bug 描述

Ant Design Pro 登录页面帐号密码登录后，控制台提示：Warning: Can't perform a React state update on an unmounted component.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1291788/194893651-76a9e71c-e9a4-429a-9543-e1aa25e2c6e4.png">

### 📷 复现步骤 | Recurrence steps

```
$: node --version
# v16.17.1
$: pro --version
# 3.00
$: pro create demo
$: cd demo
$: tyarn
$: npm run start
```

在登录页面（/user/login）输入正确帐号密码登录。
正确登录并跳转到 welcome 页面，但控制台报错。

### 🏞 期望结果 | Expected results

控制台不应该报错。

**Comment by pkaq** [comment]
#10061 
[image](https://user-images.githubusercontent.com/4537450/185818822-160a187f-bdfa-4b5c-8a05-e4a28d89a18f.png)
如图可解决 之前也有人问 官方只解释了问题的原因就是众所周知得组件销毁了还在设置状态 并未给出解决方式以及框架层面得原因

**Comment by RainThinks** [comment]
@pkaq 谢谢回复

表层原因很显而易见，这个解决办法我也知道，但感觉只是个蹩脚补丁，不优雅也没必要。
提issue确实是想知道框架层面的原因和解决办法。看来只能自己挖了。

**Comment by RainThinks** [comment]
duplicated to #10061

**Comment by RainThinks** [comment]
@pkaq 
看了眼BaseForm的实现，里面把传入的onFinish方法又封了一次，在onFinish执行完毕后，有一个 setLoading(false)的操作。所以只要在onFinish方法里unmount组件，比如更改了路由，在执行到setLoading(false)的时候，就会报内存泄露错误。

目前看来是没有优雅的办法绕过去了，只能采用setTimeout的方法，或者就不去管那个报错。
