### ISSUE TITLE
🧐[问题 | question] StepsForm组件内ProFormSlider宽度不一致

### ISSUE THREAD

**Issue by yqcs** [ant-design/ant-design-pro#10289]
### 🧐 问题描述

如下图，在StepsForm组件中，ProFormSlider的宽度和ProFormText的宽度不一致，超出了很多。如何才能设置一样宽度？？

### 💻 示例代码
    <Card bordered={false}>
        <StepsForm
          containerStyle={{minWidth: "35%"}}
          current={current}
          onCurrentChange={setCurrent}>
          <StepsForm.StepForm
            labelCol={{
              flex: '120px',
            }}
            labelAlign="left"
            labelWrap
            layout="horizontal"
            formRef={formRef}
            title={intl.formatMessage({id: 'task.creat.baseInfo'})}
            onFinish={async (values) => {
              setStepData(values);
              return true;
            }}>
            <ProFormText
              label={"任务名"}
              width="md"
              name="task_name"
              rules={[{required: true}]}/>

            <ProFormSlider
              label={"线程"}
              name={'task_threads'}
              rules={[{required: true}]}
              width="md"
              marks={{
                50: <>默认</>,
                500: <>中</>,
                1500: {
                  style: {
                    color: '#f50',
                  },
                  label: <strong>高</strong>,
                },
              }}
              initialValue={300}
              max={1500}/>
            <ProFormTextArea
              label={"任务目标"}
              width="md"
              name="task_target"
              rules={[{required: true}]}/>
          </StepsForm.StepForm>
        </StepsForm>
      </Card>

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/32994290/194685027-86790d13-1934-4aa3-9d1a-76af535c8a27.png)

**Comment by chenshuai2144** [comment]
sidler 没有设置宽度，你可以设置 width="m" 设置一下
