### ISSUE TITLE
Parsing error: Cannot find module '@babel/plugin-proposal-decorators'

### ISSUE THREAD

**Issue by epubreader** [ant-design/ant-design-pro#10288]
vscode编辑器下会报错， 不能自动格式化代码， 应该跟eslint有关

Parsing error: Cannot find module '@babel/plugin-proposal-decorators'
Require stack:
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/core/lib/config/files/plugins.js
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/core/lib/config/files/index.js
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/core/lib/index.js
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/eslint-parser/lib/worker/babel-core.cjs
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/eslint-parser/lib/worker/handle-message.cjs
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/eslint-parser/lib/client.cjs
- /home/mason/test/ecommerce/dashboard/node_modules/@babel/eslint-parser/lib/index.cjs
- /home/mason/test/ecommerce/dashboard/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /home/mason/test/ecommerce/dashboard/node_modules/@eslint/eslintrc/lib/index.js
- /home/mason/test/ecommerce/dashboard/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/mason/test/ecommerce/dashboard/node_modules/eslint/lib/cli-engine/index.js
- /home/mason/test/ecommerce/dashboard/node_modules/eslint/lib/api.js
- /home/mason/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.jseslint

**Comment by chenshuai2144** [comment]
依赖问题， 重新安装一下把
