### ISSUE TITLE
新建的models文件无法使用

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#1028]
使用top_nav版本：

    新建了models "monitor.js", 在this.props对象里找不到monitor，还需要在其他地方配置吗？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/36956841-97a8453c-206b-11e8-81dd-75dbe26b4398.png)

需要这里加进去 namespace

**Comment by zhaxingaz** [comment]
嗯嗯，加进去就好了
