### ISSUE TITLE
🧐[问题 | question]请问如何在layout中增加自定义的异步权限校验功能？（v6.0.0-beta.1）

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#10298]
### 🧐 问题描述 | Problem description
如何在v6.0.0-beta.1的默认的layout中增加自定义的权限校验功能？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案 | Solution

在V6.0.0-beta.1中，权限校验流程已经变化，推荐使用[access](https://umijs.org/docs/access)进行权限控制。下面详细介绍如何在默认的layout中增加自定义的权限校验功能。

1. 首先在`src/app.tsx`中引入`access`。  

```javascript
// src/app.tsx 

import { useEffect } from 'react';
import { useAliveController } from 'react-activation';
import { Access } from 'umi';
import './app.less';
import 'nprogress/nprogress.css';

// 全局请求拦截器
```

2. 在`src/layouts/index.tsx`文件中，编写自定义的权限控制规则，通过返回`true`或`false`来决定该路由组件是否能够被当前用户访问。这里以一个简单的例子来说明。

```javascript
// src/layouts/index.tsx

import React from 'react';
import { Link } from 'umi';
import { useAliveController } from 'react-activation';
import { Access } from 'umi';
import styles from './index.less';

export default function Layout({ children }: { children: React.ReactNode }) {
  const { drop, dropScope } = useAliveController();

  // 自定义的权限控制规则
  const auth = {
    admin: true, // admin用户可以访问
    user: false, // 普通用户禁止访问
  };

  const links = ['/', '/login', '/user', '/admin', '/notfound'];

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <Link to="/">首页</Link>
        <Link to="/login">登录</Link>
        <Link to="/user">用户页</Link>
        <Link to="/admin">管理员页</Link>
        <Link to="/notfound">404页</Link>
      </header>
      {/* 将权限控制规则传递给Access */}
      <Access accessible={auth.admin}>
        <div className={styles.content}>{children}</div>
      </Access>
    </div>
  );
}
```

在上面的例子中，当`auth.admin`为`true`时，用户可以访问路由组件。如果`auth.admin`为`false`，则用户不能访问。可以根据自己的业务需求，编写自定义的权限控制规则。

3. 在路由组件中添加`access`属性，告诉`Access`当前组件需要进行权限校验。在这里我们使用`access`的默认值`true`。 

```javascript
// src/pages/admin/index.tsx

import React from 'react';

export default function Admin() {
  return (
    <div>
      <h1>管理员页</h1>
      <p>这是一个需要权限校验的页面</p>
    </div>
  );
}

// add access property，告诉 Access 当前组件需要进行权限校验
Admin.access = true;
```

在上面的代码中，我们使用了`Access`的默认值`true`，告诉`Access`当前组件需要进行权限校验。如果您需要更复杂的权限校验规则，可以将`access`设置为一个函数，该函数可以接受当前用户信息以及路由参数等参数，返回一个布尔值，以决定当前路由组件是否允许访问。具体使用可以参考[官方文档](https://umijs.org/docs/access-control)。

4. 运行应用，如果当前用户的权限允许访问该路由组件，则可以正常访问。如果当前用户的权限不允许访问该路由组件，则跳转到403页（如果已经设置了404页，则跳转到404页）。 

### 📚 参考文档 | Reference
- [access-control](https://umijs.org/docs/access-control)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


在Umi v6.0.0-beta.1中，可以通过自定义路由的方式来实现异步权限校验功能。下面是一个可能的解决方案：

1. 首先，在`src/layouts`目录下创建一个自定义的layout组件，例如`MyLayout.tsx`：

```typescript
import React from 'react';

const MyLayout: React.FC = ({ children }) => {
  // 在这里进行异步权限校验操作
  // ...

  return <div>{children}</div>;
};

export default MyLayout;
```

2. 然后，在`src/app.tsx`中，修改`layout`配置项，使用自定义的layout组件：

```typescript
import { createApp } from 'umi';
import MyLayout from './layouts/MyLayout';

const app = createApp({
  // ...
  layout: {
    name: 'MyLayout',
    layout: MyLayout,
  },
  // ...
});

// ...
```

通过以上步骤，你可以在自定义的layout组件中实现异步权限校验功能。请根据实际需求，在`MyLayout.tsx`中添加相应的权限校验逻辑。
