### ISSUE TITLE
npm run i18n-remove去除国际化为什么会报错🧐[问题 | question]

### ISSUE THREAD

**Issue by ehanblog** [ant-design/ant-design-pro#10299]
使用pro-cli初始化脚手架， 
npm run i18n-remove去除国际化时为什么会报如下错误

![image](https://user-images.githubusercontent.com/100177229/196156872-dadab323-76b4-4aec-98c4-48d3a1c875c4.png)

**Comment by 596094101** [comment]
同遇到，这个看起来像是依赖的某个包出现问题了

**Comment by kuretru** [comment]
这个问题至少已经出现一个半月了

**Comment by linyuxian** [comment]
就没人有靠谱的解决方案吗？

**Comment by fandych** [comment]
https://github.com/ant-design/ant-design-pro/issues/10273#issuecomment-1275424069

**Comment by mzcc666GtHb** [comment]
![image](https://user-images.githubusercontent.com/23158363/197913157-47843e5e-fa61-4b66-8307-b19c16f4c536.png)

**Comment by mzcc666GtHb** [comment]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/23158363/197913394-e4546e18-f9c9-4052-b29e-81cf592e0165.png">

**Comment by OZO-HTH** [comment]
> <img alt="image" width="1055" src="https://user-images.githubusercontent.com/23158363/197913394-e4546e18-f9c9-4052-b29e-81cf592e0165.png">

这个是关掉了报错能执行成功,但是该删除的locales文件他是一点也没删除

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


谢谢您提供的反馈。

根据提供的信息，我们初步判断可能是您的依赖包版本冲突或者安装缓存引起的问题。 您可以尝试以下方法来解决此问题：

1.  清空缓存：`npm cache clean --force`
2.  删除 `node_modules` 文件夹： `rm -rf node_modules`
3.  使用 `yarn` 代替 `npm`

如果上述方法无法解决问题，您可以升级相关依赖包的版本，或查看您项目中的配置是否正确。

如果问题还持续存在，欢迎继续咨询我，感谢您的支持。

**Comment by odetteasosborneas** [comment]
这个问题到现在没有解决。拉下代码后，pnpm install 完事儿后，执行 i18n-remove 依然这个错误。
