### ISSUE TITLE
🧐[问题 | question]高级表格的ProTable，上面需要的下拉框，为什么在表格表头也会出现，需要怎么删除

### ISSUE THREAD

**Issue by KyrieZHR** [ant-design/ant-design-pro#10291]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by KyrieZHR** [comment]
高级表格的ProTable，上面需要的下拉框，为什么在表格表头也会出现，需要怎么删除

**Comment by chenshuai2144** [comment]
请详细描述你的问题，你这样一行字谁能看懂
