### ISSUE TITLE
👑protable 如果修改指定的行数据而不是重新发送网络请求

### ISSUE THREAD

**Issue by wuchencm** [ant-design/ant-design-pro#10290]
### 🥰 需求描述 | Requirements description

protable 如何修改指定的行数据，而不是重新发送网络请求

根据官方建议，我的protable组件获取数据使用的是request+params的方式
`     params={{
          cluster: clusterkey,
        }}
        request={getDeployments}
  `    
以下是获取到的结果：
![image](https://user-images.githubusercontent.com/14210543/195524140-26449280-d26c-47fb-999d-e495ddc1c8ab.png)

2、此页面同时也加载了websocket，与后端建立通信，接收event事件

遇到的问题：
1、当收到event事件后，如何做到只更新指定的行数据，而不用重新发起整个网络请求（request）去获取完整的list表数据；
做到重新渲染event关联的行，整体页面不刷新

### 🚑 其他信息 | Other information

  "ant-design-pro" : "5.2.0",
   "antd": "^4.19.0",

**Comment by chenshuai2144** [comment]
最简单的办法 把 loading 一直设置为false，这样就察觉不到刷新了

**Comment by IsColin** [comment]
+1
