### ISSUE TITLE
🧐[问题 | question]为什么ant design pro的组件官网 https://procomponents.ant.design/ 404了？

### ISSUE THREAD

**Issue by lee528066** [ant-design/ant-design-pro#10292]
### 🧐 问题描述 | Problem description
为什么ant design pro的组件官网 https://procomponents.ant.design/ 404了？最近刚搭建了一个ant design pro的前端工程，结果发现没有参考的组件官网了，打开不开了。

**Comment by lee528066** [comment]
2022年10月13日 15点50分，可以打开了。神奇了

**Comment by chenshuai2144** [comment]
修复了，发挂了一次
