### ISSUE TITLE
使用pro-cli创建的项目，运行 npm run start 后报错

### ISSUE THREAD

**Issue by obiecane** [ant-design/ant-design-pro#10293]
使用pro-cli创建的项目，运行npm run start 后报错，请问下是什么原因呀？

D:\code\web_project\flatp-admin>npm run start

> ant-design-pro@6.0.0-beta.1 start
> cross-env UMI_ENV=dev max dev

Hello PRO
info  - [你知道吗？] max g tsconfig 可一键完成项目的 TypeScript 配置。
Using openapi Plugin
info  - Umi v4.0.25
info  - MFSU eager strategy enabled
[HPM] Proxy created: /api/  -> http://127.0.0.1:9999
[HPM] Proxy rewrite rule created: "^/api" ~> ""
event - [MFSU][eager] start build deps
info  - [MFSU] buildDeps since dependencies changed
        ╔════════════════════════════════════════════════════╗
        ║ App listening at:                                  ║
        ║  >   Local: http://localhost:8000                  ║
ready - ║  > Network: http://192.168.1.168:8000              ║
        ║                                                    ║
        ║ Now you can open browser with the above addresses↑ ║
        ╚════════════════════════════════════════════════════╝
(node:5172) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Hello PRO
info  - [你知道吗？] father 4 正式发布了，详见 https://zhuanlan.zhihu.com/p/558192063
Using openapi Plugin
info  - [MFSU][eager] worker init, takes 2720
info  - [MFSU][eager] build worker start to build
event - [Webpack] Compiled in 4781 ms (1691 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 331 ms (1617 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 174 ms (1617 modules)
(node:5172) [DEP_WEBPACK_CHUNK_GET_MODULES] DeprecationWarning: Chunk.getModules: Use new ChunkGraph API
error - ./node_modules/@playwright/test/lib/babelBundleImpl.js:2074:532-545
Module not found: Error: Can't resolve 'v8' in 'D:\code\web_project\flatp-admin\node_modules\@playwright\test\lib'
info  - [MFSU][eager] write cache
info  - [MFSU] buildDepsAgain
info  - [MFSU] skip buildDeps
error - ./node_modules/@playwright/test/lib/profiler.js:37:17-45
error - ./node_modules/playwright-core/lib/cli/driver.js:50:29-54
error - ./node_modules/playwright-core/lib/client/page.js:808:9-33
error - ./node_modules/playwright-core/lib/utils/index.js:36:32-45
error - ./node_modules/playwright-core/lib/webpack/recorder/index.html:1:0
error - [MFSU][eager] build worker failed Error: ERROR in ./node_modules/@playwright/test/lib/babelBundleImpl.js 2074:532-545
Module not found: Error: Can't resolve 'v8' in 'D:\code\web_project\flatp-admin\node_modules\@playwright\test\lib'
 @ ./node_modules/@playwright/test/lib/babelBundle.js 23:25-70 27:16-52 31:14-48 35:14-48 39:17-54 43:23-66
 @ ./node_modules/@playwright/test/lib/transform.js 206:8-32
 @ ./node_modules/@playwright/test/lib/testType.js 14:17-39
 @ ./node_modules/@playwright/test/lib/index.js 29:16-37
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/@playwright/test/lib/profiler.js 37:17-45
Module not found: Error: Can't resolve 'inspector' in 'D:\code\web_project\flatp-admin\node_modules\@playwright\test\lib'
 @ ./node_modules/@playwright/test/lib/cli.js 18:16-37
 @ ./node_modules/@playwright/test/lib/plugins/webServerPlugin.js 22:11-28
 @ ./node_modules/@playwright/test/lib/plugins/index.js 21:23-51
 @ ./node_modules/@playwright/test/lib/index.js 37:15-35
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/playwright-core/lib/cli/driver.js 50:29-54
Module not found: Error: Can't resolve '../../api.json' in 'D:\code\web_project\flatp-admin\node_modules\playwright-core\lib\cli'
 @ ./node_modules/playwright-core/lib/cli/cli.js 30:14-33
 @ ./node_modules/playwright-core/cli.js 17:0-41
 @ ./node_modules/@playwright/test/lib/cli.js 267:53-91
 @ ./node_modules/@playwright/test/lib/plugins/webServerPlugin.js 22:11-28
 @ ./node_modules/@playwright/test/lib/plugins/index.js 21:23-51
 @ ./node_modules/@playwright/test/lib/index.js 37:15-35
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/playwright-core/lib/client/page.js 808:9-33
Module not found: Error: Can't resolve 'inspector' in 'D:\code\web_project\flatp-admin\node_modules\playwright-core\lib\client'
 @ ./node_modules/playwright-core/lib/client/connection.js 24:12-29
 @ ./node_modules/playwright-core/lib/outofprocess.js 8:18-48
 @ ./node_modules/@playwright/test/lib/index.js 39:43-86
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/playwright-core/lib/utils/index.js 36:32-45
Module not found: Error: Can't resolve 'v8' in 'D:\code\web_project\flatp-admin\node_modules\playwright-core\lib\utils'
 @ ./node_modules/@playwright/test/lib/index.js 31:13-49
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/playwright-core/lib/webpack/recorder/index.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!--
|   Copyright (c) Microsoft Corporation.
|
 @ ./node_modules/playwright-core/lib/webpack/recorder/ sync ^\.\/.*$ ./index.html
 @ ./node_modules/playwright-core/lib/server/recorder/recorderApp.js 84:21-69
 @ ./node_modules/playwright-core/lib/server/debugController.js 14:19-52
 @ ./node_modules/playwright-core/lib/server/playwright.js 27:23-51
 @ ./node_modules/playwright-core/lib/browserServerImpl.js 16:18-48
 @ ./node_modules/playwright-core/lib/inProcessFactory.js 12:25-55
 @ ./node_modules/playwright-core/lib/inprocess.js 3:24-53
 @ ./node_modules/playwright-core/index.js 33:0-43
 @ ./node_modules/@playwright/test/index.js 18:19-45
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

MFSU compiled with 6 errors
    at D:\code\web_project\flatp-admin\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuilder.js:57:20
    at finalCallback (D:\code\web_project\flatp-admin\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:61758:32)
    at D:\code\web_project\flatp-admin\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:61822:17
    at D:\code\web_project\flatp-admin\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:75586:3
    at Hook.eval [as callAsync] (eval at create (D:\code\web_project\flatp-admin\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\code\web_project\flatp-admin\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:4851)
    at Cache.storeBuildDependencies (D:\code\web_project\flatp-admin\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:51280:37)
    at D:\code\web_project\flatp-admin\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:61818:19
    at Hook.eval [as callAsync] (eval at create (D:\code\web_project\flatp-admin\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:47:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\code\web_project\flatp-admin\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:4851)
Module not found: Error: Can't resolve 'inspector' in 'D:\code\web_project\flatp-admin\node_modules\@playwright\test\lib'
Module not found: Error: Can't resolve '../../api.json' in 'D:\code\web_project\flatp-admin\node_modules\playwright-core\lib\cli'
Module not found: Error: Can't resolve 'inspector' in 'D:\code\web_project\flatp-admin\node_modules\playwright-core\lib\client'
Module not found: Error: Can't resolve 'v8' in 'D:\code\web_project\flatp-admin\node_modules\playwright-core\lib\utils'
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!--
|   Copyright (c) Microsoft Corporation.
|

OS:  windows 10

Node：v16.18.0
Npm：8.19.2

**Comment by 172297555** [comment]
是的，我也刚遇到了相同的问题

**Comment by xxdd13** [comment]
我也遇到一样的问题，macOS上用yarn。
直接clone repo 也是一样报错。

我把playwright 相关的都移除后 这个问题就解决了，但是会遇到react hooks的问题
<img width="677" alt="image" src="https://user-images.githubusercontent.com/26791482/195729393-ba022772-ed1b-4162-998b-53bfe841ff13.png">

```jsvascript
ncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at Object.useEffect (react.development.js:1519:1)
    at ConfigProvider (index.js:188:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23620:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
mf-dep____vendor.730de18a.js:288825 The above error occurred in the <ConfigProvider> component:

    at ConfigProvider (http://localhost:8001/vendors-node_modules_umijs_preset-umi_node_modules_umijs_bundler-webpack_compiled_mini-css-ex-0fea69.async.js:5426:13)
    at _LocaleContainer (http://localhost:8001/src_umi_umi_ts.async.js:3519:115)
    at Provider (http://localhost:8001/src_umi_umi_ts.async.js:2190:74)
    at InitialStateProvider (http://localhost:8001/src_umi_umi_ts.async.js:2464:109)
    at Provider (http://localhost:8001/src_umi_umi_ts.async.js:4158:34)
    at ProviderWrapper (http://localhost:8001/src_umi_umi_ts.async.js:4373:106)
    at Browser (http://localhost:8001/mf-dep____vendor.730de18a.js:98762:68)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ mf-dep____vendor.730de18a.js:288825
scheduler.development.js:171 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at Object.useEffect (react.development.js:1519:1)
    at ConfigProvider (index.js:188:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23620:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```

**Comment by heroes2016** [comment]
我也是同样问题，mac系统，期待官方解答。

**Comment by loser1046** [comment]
遇到相同问题:
环境:windows
安装工具npm

![image](https://user-images.githubusercontent.com/22904669/195748404-85912cd8-7ec1-4ca0-811f-1caf02bc50b3.png)
`info  - [你知道吗？] 默认使用 esbuild 作为 JavaScript 压缩工具，也可通过 jsMinifier 配置项切换到 terser 或 uglifyJs 等，详见 https://umijs.org/docs/api/config#jsminifier-webpack
Using openapi Plugin
info  - [MFSU][eager] worker init, takes 10266
info  - [MFSU][eager] build worker start to build
event - [Webpack] Compiled in 16325 ms (1687 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 1696 ms (1613 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 658 ms (1613 modules)
(node:18996) [DEP_WEBPACK_CHUNK_GET_MODULES] DeprecationWarning: Chunk.getModules: Use new ChunkGraph API
error - ./node_modules/@playwright/test/lib/babelBundleImpl.js:2074:532-545
Module not found: Error: Can't resolve 'v8' in 'E:\project\umi-pro\node_modules\@playwright\test\lib'
info  - [MFSU][eager] write cache
info  - [MFSU] buildDepsAgain
info  - [MFSU] skip buildDeps
error - ./node_modules/@playwright/test/lib/profiler.js:37:17-45
error - ./node_modules/playwright-core/lib/cli/driver.js:50:29-54
error - ./node_modules/playwright-core/lib/client/page.js:808:9-33
error - ./node_modules/playwright-core/lib/utils/index.js:36:32-45
error - ./node_modules/playwright-core/lib/webpack/recorder/index.html:1:0
error - [MFSU][eager] build worker failed Error: ERROR in ./node_modules/@playwright/test/lib/babelBundleImpl.js 2074:532-545
Module not found: Error: Can't resolve 'v8' in 'E:\project\umi-pro\node_modules\@playwright\test\lib'
 @ ./node_modules/@playwright/test/lib/babelBundle.js 23:25-70 27:16-52 31:14-48 35:14-48 39:17-54 43:23-66
 @ ./node_modules/@playwright/test/lib/transform.js 206:8-32
 @ ./node_modules/@playwright/test/lib/testType.js 14:17-39
 @ ./node_modules/@playwright/test/lib/index.js 29:16-37
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/@playwright/test/lib/profiler.js 37:17-45
Module not found: Error: Can't resolve 'inspector' in 'E:\project\umi-pro\node_modules\@playwright\test\lib'
 @ ./node_modules/@playwright/test/lib/cli.js 18:16-37
 @ ./node_modules/@playwright/test/lib/plugins/webServerPlugin.js 22:11-28
 @ ./node_modules/@playwright/test/lib/plugins/index.js 21:23-51
 @ ./node_modules/@playwright/test/lib/index.js 37:15-35
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]

ERROR in ./node_modules/playwright-core/lib/cli/driver.js 50:29-54`

**Comment by loser1046** [comment]
遇到相同问题:
环境:windows
安装工具npm

![image](https://user-images.githubusercontent.com/22904669/195748404-85912cd8-7ec1-4ca0-811f-1caf02bc50b3.png)

>info  - [你知道吗？] 默认使用 esbuild 作为 JavaScript 压缩工具，也可通过 jsMinifier 配置项切换到 terser 或 uglifyJs 等，详见 https://umijs.org/docs/api/config#jsminifier-webpack
Using openapi Plugin
info  - [MFSU][eager] worker init, takes 10266
info  - [MFSU][eager] build worker start to build
event - [Webpack] Compiled in 16325 ms (1687 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 1696 ms (1613 modules)
wait  - [Webpack] Compiling...
event - [Webpack] Compiled in 658 ms (1613 modules)
(node:18996) [DEP_WEBPACK_CHUNK_GET_MODULES] DeprecationWarning: Chunk.getModules: Use new ChunkGraph API
error - ./node_modules/@playwright/test/lib/babelBundleImpl.js:2074:532-545
Module not found: Error: Can't resolve 'v8' in 'E:\project\umi-pro\node_modules\@playwright\test\lib'
info  - [MFSU][eager] write cache
info  - [MFSU] buildDepsAgain
info  - [MFSU] skip buildDeps
error - ./node_modules/@playwright/test/lib/profiler.js:37:17-45
error - ./node_modules/playwright-core/lib/cli/driver.js:50:29-54
error - ./node_modules/playwright-core/lib/client/page.js:808:9-33
error - ./node_modules/playwright-core/lib/utils/index.js:36:32-45
error - ./node_modules/playwright-core/lib/webpack/recorder/index.html:1:0
error - [MFSU][eager] build worker failed Error: ERROR in ./node_modules/@playwright/test/lib/babelBundleImpl.js 2074:532-545
Module not found: Error: Can't resolve 'v8' in 'E:\project\umi-pro\node_modules\@playwright\test\lib'
 @ ./node_modules/@playwright/test/lib/babelBundle.js 23:25-70 27:16-52 31:14-48 35:14-48 39:17-54 43:23-66
 @ ./node_modules/@playwright/test/lib/transform.js 206:8-32
 @ ./node_modules/@playwright/test/lib/testType.js 14:17-39
 @ ./node_modules/@playwright/test/lib/index.js 29:16-37
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]
ERROR in ./node_modules/@playwright/test/lib/profiler.js 37:17-45
Module not found: Error: Can't resolve 'inspector' in 'E:\project\umi-pro\node_modules\@playwright\test\lib'
 @ ./node_modules/@playwright/test/lib/cli.js 18:16-37
 @ ./node_modules/@playwright/test/lib/plugins/webServerPlugin.js 22:11-28
 @ ./node_modules/@playwright/test/lib/plugins/index.js 21:23-51
 @ ./node_modules/@playwright/test/lib/index.js 37:15-35
 @ ./node_modules/@playwright/test/index.js 17:12-34
 @ ./node_modules/@playwright/test/index.mjs 16:0-36 18:24-43 19:23-41 20:22-39 21:25-45 22:23-41 23:22-39 24:23-41 25:25-45 26:24-43 27:20-35 28:22-39 29:15-30
 @ ./node_modules/.cache/mfsu/mf-va_@playwright_test.js 1:0-33 2:15-16 3:0-33 3:0-33
 @ container entry ./@playwright/test[0]
ERROR in ./node_modules/playwright-core/lib/cli/driver.js 50:29-54`

**Comment by RainThinks** [comment]
一样的问题。回滚了yarn.lock，能跑起来了。

**Comment by zozopen** [comment]
> 一样的问题。回滚了yarn.lock，能跑起来了。

大佬可以把你的yarn.lock 文件发一下我吗，我误删了

**Comment by WenXin0405** [comment]
同样问题,6.0的yarn.lock谁发下可以用的被

**Comment by yuemaedu** [comment]
同样遇到的路过

**Comment by tianxiuali** [comment]
看到大家都一样我就放心了

**Comment by gleiyu** [comment]
等一个解决方案

**Comment by kalencaya** [comment]
尽快解决吧，已经影响了开发

**Comment by ksgt00857912** [comment]
遇到了同样的问题

**Comment by luCroc** [comment]
一样的问题，procli和直接clone下来的umi4的都跑不起来

**Comment by qiqizjl** [comment]
https://github.com/umijs/umi/issues/9522

在``config/config.ts``里添加
~~~ ts
  mfsu:{
    strategy:'normal'
  }
~~~
即可

**Comment by guotingchaopr** [comment]
+1

**Comment by chenshuai2144** [comment]
先关掉 mfsu 顶一下，等umi解决

**Comment by mushroomlb** [comment]
关闭mfsu果然很慢

**Comment by iYarnFog** [comment]
妈耶，我把依赖回退了三四个版本，lock文件删了，依赖下了删删了下，没想到竟然是 mfsu 的问题

**Comment by chenshuai2144** [comment]
修复了，重新安装吧
