### ISSUE TITLE
webpack.resolve.alias别名在按需加载的import中无效？

### ISSUE THREAD

**Issue by xaviertung** [ant-design/ant-design-pro#1029]
我想使用require.context方式类似动态获取model一样封装路由，写了一个scan方法如下：

```
function scanRouterConfig(app) {
  const context = require.context('./../routes', true, /router\.js$/);
  const routerConfigs = context.keys().map(key => {

    const currentRouterConfig = context(key).default;

    for(let routerPath of Object.keys(currentRouterConfig)) {
      const currentRouter = currentRouterConfig[routerPath];
      const { component, models=[] } = currentRouter;
      currentRouter['component'] = dynamicWrapper(app, models, () => { return component });
      delete currentRouter.models;
      currentRouterConfig[routerPath] = currentRouter;
    }

    return currentRouterConfig;
  });
  // const newConfig = Object.assign({}, routerConfig, ...routerConfigs);

  return routerConfigs;
}
```

我配置了alias别名，静态引入没问题，在common/router.js的dynamicWrapper方法里报错：

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

请问是webpack的alias在动态加载时没起作用，还是我配置有问题。路由太多写在一个文件里不太方便，有没有好的解决方案呢？

**Comment by chenshuai2144** [comment]
> Fully dynamic statements, such as import(foo), will fail because webpack requires at least some file location information. This is because foo could potentially be any path to any file in your system or project. The import() must contain at least some information about where the module is located, so bundling can be limited to a specific directory or set of files.


https://webpack.js.org/api/module-methods/#import-

cc

**Comment by xaviertung** [comment]
@chenshuai2144 我了解按需加载是根据import打包后调用时延迟加载的，相当于现在alias执行顺序在import打包之后的，所以没有解决alias别名。现在一个src/common/router.js写所以router不太优雅，有没有什么更好的方法做分布式配置呢？

**Comment by chenshuai2144** [comment]
分布式配置是什么意思？

**Comment by xaviertung** [comment]
@chenshuai2144 原来想以下面的形式合并routderConfig路由对象，：
`routerConfig = Object.assign({}, routerConfig, ...scanRouterConfig(app));`
发现程序运行时会报下面的错误：
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`
应该是子路由配置里的模块引用造成的，暂时没有什么好的方法，还是按照推荐的方式在中心配置文件里配置吧。
