### ISSUE TITLE
🐛 [BUG] DatePicker”不能用作 JSX 组件

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design-pro#10295]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/23204297/195777530-98e5d509-f311-4303-a049-6acee2f29485.png)

6.0.0 版本

参考 #9978 
也不能解决，已经升级版本

![image](https://user-images.githubusercontent.com/23204297/195777807-ebfa08a1-c814-479c-aa93-23c26b5bfa2f.png)

**Comment by zozopen** [comment]
升级对应版本即可

**Comment by liucys** [comment]
不是呀，不起作用呀，我升级版本报了更多的错误

**Comment by zozopen** [comment]
> 不是呀，不起作用呀，我升级版本报了更多的错误

为了这玩意，我现在项目都崩了
