### ISSUE TITLE
realDark 强制改变颜色

### ISSUE THREAD

**Issue by xiaqingping** [ant-design/ant-design-pro#10304]
我需要在realDark主题下的页面设置白色背景和其他亮色，但是主题会去更改我的颜色，且!important无法阻止，这让我很苦恼。我希望得到一个解决办法，谢谢！

**Comment by njfyueji** [comment]
navTheme: 'dark',同时在config里面的antd: { dark: true }，可以试一下是否达到你想要的效果。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，我的上一条回复有误。 `navTheme: 'realDark'` 是 Ant Design Pro V5 中的一个主题设置，它会根据用户设置的主题实时切换整个应用程序的颜色和样式。在实际开发中，如果您需要自定义某些组件的颜色和样式，建议采用以下方法：

1. 使用 `less` 变量，在 `less` 文件中设置自定义样式，并将其导入到需要的组件中。

2. 使用 `CSS Modules` 定义局部样式或使用内联样式。

例如，如果您需要将某个 `div` 的背景色设置为白色，可以按照以下步骤操作：

1. 在您的组件文件夹内新建一个 `index.less` 文件。

2. 在 `index.less` 文件中定义一个 `background-color` 变量，如下所示：

   ```less
   @backgroundColor: #fff;
   ```

3. 然后在需要设置背景颜色的组件文件中导入该变量：

   ```jsx
   import styles from './index.less';

   function MyComponent() {
     return <div className={styles.container}>Hello World!</div>;
   }
   ```

4. 最后，在组件的样式表中使用该变量：

   ```less
   .container {
     background-color: @backgroundColor;
   }
   ```

这样，您就可以自定义组件的样式并在 `realDark` 主题下正常工作了。

如果您希望了解更多关于 Ant Design Pro V5 的主题和样式定制的信息，请参阅官方文档：https://pro.ant.design/docs/style-cn。

**Comment by Jexecellent** [comment]
> navTheme: 'dark',同时在config里面的antd: { dark: true }，可以试一下是否达到你想要的效果。

翻了三天这个主题配置的issues   这么设置好用  ~
