### ISSUE TITLE
👑 [需求 | Feature] 适配 antd vnext

### ISSUE THREAD

**Issue by scrapstation** [ant-design/ant-design-pro#10300]
procomponents演示站已经在使用 antd next, 导致有些样式与实际开发有些出入

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢您的反馈。针对这个问题，您可以通过以下步骤来适配 antd vnext：

1.确保您的项目已经更新到了 antd v4.0+ 的版本，支持 vnext。可以参考 Ant Design 官方文档进行更新：https://ant.design/docs/react/migration-v4-cn

2.检查您的项目依赖是否正确。如果您在项目中引入了 procomponents 组件库，可以使用 npm 或者 yarn 等包管理工具，将 procomponents 更新到最新版本（1.28.8+）。
```
npm install @ant-design/pro-components@latest
或
yarn add @ant-design/pro-components@latest
```

3.在您的项目中使用 ProComponents 组件时，您需要相应地更改组件前缀。例如，以之前的 Table 组件为例，在 antd vnext 中，您需要使用 ProTable 组件。具体的前缀对照可以参考 ProComponents 文档：https://procomponents.ant.design/docs/getting-started-cn

4.如果您在使用组件时遇到了样式等问题，可以先检查是否引入了 antd 组件库的样式文件。在 antd vnext 中，您需要手动引入全局样式文件：
```
import 'antd/dist/antd.less';
import '@ant-design/pro-components/dist/ProLayout/style/index.less';
// 引入 ProComponents 组件的样式
```

5.如果您的问题还没有得到解决，可以通过 github 的 issue 页面提出问题，我们会竭力帮您解决。记得在问题描述中给出尽可能详细的信息，例如报错信息、代码示例等。
