### ISSUE TITLE
执行 npm start。报错 UnhandledPromiseRejectionWarning:pathname.match is not a function at Object.matchPath

### ISSUE THREAD

**Issue by lhC0** [ant-design/ant-design-pro#10308]
### 🧐 问题描述 | Problem description

antdv4 执行 npm start。报错 UnhandledPromiseRejectionWarning:pathname.match is not a function at Object.matchPath

### 🚑 其他信息 | Other information

<img width="499" alt="c86db363436115daead35d84df47870" src="https://user-images.githubusercontent.com/29115820/196883610-73b5bb67-e535-4ae9-ad62-935790b1d3d5.png">

OS:

Node：
<img width="245" alt="02939727891ab706230662d6f1a8a9b" src="https://user-images.githubusercontent.com/29115820/196883813-6dea7020-70dd-40e1-9403-c3f44dab6f4c.png">

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题看起来是和 React Router 有关，具体来说是 `matchPath` 方法没有被正确加载。这可能是由于 React Router 版本不兼容所导致的。

你可以尝试在项目目录下执行以下命令，更新 React Router 的版本：

```bash
npm install react-router-dom@latest
```

如果这个问题仍然存在，你可以检查你的代码，看是否有自定义的路由相关代码，特别是检查路由的加载位置和方式是否正确。

另外，React Router 官方文档提供了关于错误 `match is not a function` 的问题解决方案。你可以参考文档链接：[React Router - Troubleshooting - 'match' is not a function](https://reactrouter.com/web/guides/troubleshooting#match-is-not-a-function)。

**Comment by chenshuai2144** [comment]
升级一下 node 版本
