### ISSUE TITLE
🧐[V5 HeaderDropdown在手机size环境下会失灵]

### ISSUE THREAD

**Issue by kingseawu** [ant-design/ant-design-pro#10302]
### 💻 示例代码 | Sample code
代码是直接从ant design pro v5在github官网地址clone下来的。
GlobalHeaderRight:
<Space className={className}>
      <HeaderSearch
        className={`${styles.action} ${styles.search}`}
        placeholder="站内搜索"
        defaultValue="umi ui"
        options={[
          { label: <a href="https://umijs.org/zh/guide/umi-ui.html">umi ui</a>, value: 'umi ui' },
          {
            label: <a href="next.ant.design">Ant Design</a>,
            value: 'Ant Design',
          },
          {
            label: <a href="https://protable.ant.design/">Pro Table</a>,
            value: 'Pro Table',
          },
          {
            label: <a href="https://prolayout.ant.design/">Pro Layout</a>,
            value: 'Pro Layout',
          },
        ]}
        // onSearch={value => {
        //   console.log('input', value);
        // }}
      />
      <span
        className={styles.action}
        onClick={() => {
          window.open('https://pro.ant.design/docs/getting-started');
        }}
      >
        <QuestionCircleOutlined />
      </span>
      <Avatar />
      <SelectLang className={styles.action} />
    </Space>

### 🚑 其他信息 | Other information

![headerDropdown_issue](https://user-images.githubusercontent.com/82017224/196658291-3f987e80-c19c-446e-bbae-1fd5f540d426.jpg)

OS:
Windows, 
Node：

浏览器 | browser：Chrome 或者手机的browser

**Comment by xXAvoraXx** [comment]
you should change rightcontent component ->> https://ant.design/components/dropdown

**Comment by kingseawu** [comment]
Thank you for your efforts, but how to change rightcontent component with dropdown? Could you please provide more details?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Sure, I'd be happy to provide more details on how to change the `RightContent` component with the `Dropdown` component.

First, you'll need to import the `Dropdown` and `Menu` components from Ant Design:

```javascript
import { Dropdown, Menu } from 'antd';
```

Then, you can replace the existing `RightContent` component with the `Dropdown` component by setting the `overlay` prop to a `Menu` component:

```javascript
<Dropdown overlay={menu}>
  <div className={styles.right}>
    <NoticeIconView />
    <Avatar />
    <SelectLang className={styles.action} />
  </div>
</Dropdown>
```

Here, `menu` is a variable that holds the `Menu` component:

```javascript
const menu = (
  <Menu>
    <Menu.Item key="1">Option 1</Menu.Item>
    <Menu.Item key="2">Option 2</Menu.Item>
    <Menu.Item key="3">Option 3</Menu.Item>
  </Menu>
);
```

In this example, the `Menu` component has three menu items. You can customize these menu items as needed.

By using the `Dropdown` component, the dropdown menu will work correctly on mobile devices.
