### ISSUE TITLE
请问有办法能让antd pro支持ie9或者10吗

### ISSUE THREAD

**Issue by laozb** [ant-design/ant-design-pro#1030]
是技术栈中哪个不支持ie9 ie10导致antd pro不支持ie9 10啊

**Comment by kunhour** [comment]
IE10已经支持，IE9不能支持，flex布局不支持

**Comment by laozb** [comment]
试了一下， ie10是不行的，报错 对象不支持“createId”属性或方法

**Comment by chenshuai2144** [comment]
https://github.com/alibaba/BizCharts/issues/106

**Comment by laozb** [comment]
感谢。看了下antd的Layout部分文档，有两个布局，一个是Layout ,还有一个是Grid。Layout介绍上写了 协助进行页面级整体布局。但是用的是flex布局，不支持ie9，那请问要支持ie9的话能不能用栅格来进行页面整体布局，合适吗？

**Comment by wuzehao16** [comment]
@chenshuai2144  请问下，打包之后的文件，IE10和11报这个错误（SCRIPT1046: strict 模式下不允许一个属性有多个定义），IE9可以打开
