### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by wufu-fire** [ant-design/ant-design-pro#10301]
### 🐛 bug 描述

通过 
npm i @ant-design/pro-cli -g
pro create myapp
选择 umi@4
项目启动后，报错信息如下:
![image](https://user-images.githubusercontent.com/14272772/196613963-75c4caad-843d-4742-b29e-795044e65b63.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by webpon** [comment]
+1, 真是服了，初始化都能报错

**Comment by cgfeel** [comment]
没有安装依赖啊。。。。。看下报错信息吧

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您提供的截图显示，应该是缺少了`happypack`这个依赖，你需要安装好该依赖包才能正常运行项目。

你可以尝试使用以下命令安装：

```bash
npm install happypack --save-dev
```

安装好`happypack`之后，可以尝试重新启动项目，如果问题仍然存在，请提供问题复现代码和更多细节信息，这样我们才能更好地帮助您解决问题。
