### ISSUE TITLE
🐛 [BUG] 初始化项目后，启动报错

### ISSUE THREAD

**Issue by tilkofjin** [ant-design/ant-design-pro#10306]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
- Node 版本 v16.13.1

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/24365622/196859975-d39a70e7-13ed-41b7-93c1-175e020c8cbe.png)
![image](https://user-images.githubusercontent.com/24365622/196860411-92b44ae3-aea7-49bb-8669-d9f55530f2fe.png)
![image](https://user-images.githubusercontent.com/24365622/196860487-d225ba6d-fc50-42c6-9a7e-90c369495f7f.png)
![image](https://user-images.githubusercontent.com/24365622/196860569-b5614df8-554a-4e16-92c7-011df983226c.png)

**Comment by a2821272424** [comment]
> ### 🐛 bug 初始化项目后，启动报错
> ### 📷 复现步骤 | Recurrence steps
> ### 🏞 期望结果 | Expected results
> ### 💻 复现代码 | Recurrence code
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 4.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]
> * Node 版本 v16.13.1
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/24365622/196859975-d39a70e7-13ed-41b7-93c1-175e020c8cbe.png) ![image](https://user-images.githubusercontent.com/24365622/196860411-92b44ae3-aea7-49bb-8669-d9f55530f2fe.png) ![image](https://user-images.githubusercontent.com/24365622/196860487-d225ba6d-fc50-42c6-9a7e-90c369495f7f.png) ![image](https://user-images.githubusercontent.com/24365622/196860569-b5614df8-554a-4e16-92c7-011df983226c.png)

config.ts文件添加
mfsu: {
        strategy: 'normal'
    },

或者关闭mfsu即可；

**Comment by a2821272424** [comment]
config.ts文件添加
mfsu: {
strategy: 'normal'
},

或者关闭mfsu即可；

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对于 Ant Design Pro 这样的基于 umi 的项目，mfsu 是 webpack 5 新特性 Module Federation 的一种实现方式，旨在提高项目的打包速度和运行时的性能，但有一定的兼容性问题，可能会导致一些 bug。

因此，如果在项目启动时出现了类似的问题，可以尝试在 config.ts 文件中添加如下配置：`mfsu: { strategy: 'normal' }`，或者关闭 mfsu 功能。

具体可以参考 Ant Design Pro 的官方文档：https://pro.ant.design/zh-CN/docs/runtime-error-cn#%E8%A7%A3%E5%86%B3-mfsu-%E9%97%AE%E9%A2%98。
