### ISSUE TITLE
🐛 [BUG]umi3 mock功能不行

### ISSUE THREAD

**Issue by webpon** [ant-design/ant-design-pro#10310]
就·npm start后就不行了，是我操作问题还是其他什么原因
![image](https://user-images.githubusercontent.com/50807258/196927059-61de8c84-02f6-43df-a40f-f26faa0e3d44.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


看到您提供的截图，提示为503错误。这一般是因为接口无法连接或者服务端无法响应。为了确定问题，您可以按照以下方法进行排查：

1. 查看mock配置是否正确

如果您使用的是umi自带的mock功能，可以在.umirc.ts或者config/config.ts中配置mock，检查是否配置正确。示例如下：

```
// .umirc.ts 或者 config/config.ts
export default {
  mock: {
    // mock配置是否启用
    enable: true,
    // mock数据的根目录
    dir: 'mock',
    // 自定义拦截规则
    // 更多配置可查看官方文档：https://umijs.org/zh-CN/docs/mock
    mocker: {
      'GET /api/user': { name: '昵称', age: 18 },
    },
  },
};
```

2. 查看接口是否正确配置

检查您正在调用的接口地址是否正确，尝试在浏览器中访问该接口，看看是否能获得正确的响应。

3. 检查后端服务

您可以使用Postman等工具来检测接口是否可用，如果可用，说明服务端正常，如果不可用，说明服务端出现问题，联系服务端开发者进行排查。

如果以上方法都没有解决问题，您可以贴出您的代码片段和接口API，我们会尽力帮您解决问题。
