### ISSUE TITLE
🐛 [BUG] ant design pro 升级umi max版本H5布局存在问题

### ISSUE THREAD

**Issue by lizhenkun96** [ant-design/ant-design-pro#10316]
### 🐛 bug 描述
H5移动端未能正常展示网页标题及logo

### 🏞 期望结果 | Expected results
H5移动端正常展示网页标题及logo

### 💻 复现代码 | Recurrence code
默认最新代码，未做变更

### © 版本信息

- Ant Design Pro 版本: [e.g. v6.0.0-beta.1]
- umi 版本 4.0.24
- 浏览器环境 chrome
- 开发环境 [e.g. win10 ]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/17764039/197339251-2b7ff7e2-55ff-4ef6-8585-873cdea83f8f.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，可以初步判断是 Ant Design Pro 升级到 umi 4.0 版本后，H5移动端展示网页标题及 logo 的问题。具体原因可能是 Ant Design Pro 中使用了 umi 4.0 的新特性，但 H5 移动端的适配没有做好。为了解决这个问题，需要针对 Ant Design Pro 和 umi 4.0 进行调整。请尝试以下操作：

1. 检查 Ant Design Pro 和 umi 的版本是否与你提供的一致。如果版本不一致，请升级至最新版本。

2. 检查 Ant Design Pro 是否已经适配了 umi 4.0 的 H5 移动端展示问题。如果未适配，请在 Ant Design Pro 的文档中查找适配 H5 的方法。

3. 如果以上操作都没有解决问题，请尝试手动适配 H5 移动端展示问题。比如，可以尝试在 public/index.html 文件中添加以下代码：

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>你的网页标题</title>
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

其中，`title` 标签中的文字是你的网页的标题，`link` 标签中的 `href` 属性为网页图标的地址。在 Ant Design Pro 中，你可以把网页图标放在 `public` 目录下，在上面的代码中，你只需要修改 `./favicon.ico` 为你网页图标的地址即可。

希望以上解决方案可以帮助到你，如果问题还未得到解决，请提供更多的信息和代码，我们再进行讨论。另外，如果问题不是前端问题，请及时告知，我会返回一个得体的拒绝。

**Comment by chenshuai2144** [comment]
升级一下版本，修改了设计
