### ISSUE TITLE
项目代码本地能运行，push到远程后，拉取新代码后无法运行，控制台报错

### ISSUE THREAD

**Issue by doYbest** [ant-design/ant-design-pro#10318]
### 🐛 bug 描述

项目代码本地能运行，push到远程后，拉取新代码后无法运行，控制台报错，报错如下：
![image](https://user-images.githubusercontent.com/80409408/197348274-9a89c545-eb81-46dc-b9ee-62bb0da9355a.png)

### © 版本信息

    "@ant-design/pro-form": "^1.18.3",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
     谷歌

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据报错信息，是找不到 `moment` 模块。这可能是因为你在本地安装了该模块，但在远程仓库中并没有将其包含在内，当你拉取代码后，`moment` 模块无法被发现导致报错。

解决方案是：

1. 确保将 `moment` 模块已经被加入到了你的项目中，可以使用命令 `$ npm install moment --save` 或者 `$ yarn add moment` 安装。
2. 确保 `moment` 模块已经被纳入到你的依赖项中，并且 `node_modules` 文件夹已经被包含在了你的 `git` 仓库中。你可以使用命令 `$ npm install` 或者 `$ yarn install` 来确保该模块被安装到了 `node_modules` 文件夹中。
3. 如果以上两个步骤都已经完成，但仍然无法解决问题，可以考虑删除本地 `node_modules` 文件夹和 `package-lock.json` 或 `yarn.lock` 文件，然后重新运行 `$ npm install` 或 `$ yarn install` 命令重新安装依赖项。同时确保你的 `.gitignore` 文件已经将 `node_modules` 文件夹排除在了外。

附：

- `moment` 官网：https://momentjs.com/
- `moment` 在 npm 上的文档：https://www.npmjs.com/package/moment

**Comment by chenshuai2144** [comment]
库的版本太低了
