### ISSUE TITLE
🐛 [BUG]关于多页签配置： 刷新页面后显示一个多页签，切换页面/路由后多页签消失

### ISSUE THREAD

**Issue by zhouzhounice** [ant-design/ant-design-pro#10315]
### 🐛 bug 描述

跟着配置Tabs的文章一路配下来，虽然在页面刷新的时候显示了一次多页签。

![image](https://user-images.githubusercontent.com/68803762/197329975-5cbc86b9-9354-47c9-bf50-774337546982.png)

但是页面一切换，多页签就消失了。

![image](https://user-images.githubusercontent.com/68803762/197329989-90c744c0-117c-4e8b-99ba-b12158261c45.png)

### 📷 复现步骤 | Recurrence steps

**在config.ts中的配置**

![image](https://user-images.githubusercontent.com/68803762/197329770-117f9051-6add-46aa-b205-2244c1708dff.png)
**下载的插件的版本**

![image](https://user-images.githubusercontent.com/68803762/197329831-be0b283b-9586-4078-83db-5db7505f8ec4.png)
**在app.tsx里面的配置**

![image](https://user-images.githubusercontent.com/68803762/197329878-3eb7478a-73d4-4afb-847f-cde9d7cb243d.png)

### 🏞 期望结果 | Expected results

期望可以看到多页签能正常使用

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0-beta.1]
- umi 版本 :"@umijs/max": "^4.0.24",
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhouzhounice** [comment]
抱歉，已解决了 忘了配置运行时文件里的useKeepOutlets了

**Comment by li9269391** [comment]
为什么tabs在官方文档配置是找不到的，请问是得靠额外的文章吗？

**Comment by zhouzhounice** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GuanJdoJ** [comment]
> 为什么tabs在官方文档配置是找不到的，请问是得靠额外的文章吗？

是的，可以参考这篇文章：https://juejin.cn/post/7153525746751766559/#heading-21

**Comment by zhouzhounice** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
