### ISSUE TITLE
ProTable组件，对于查询表单，默认在不展开情况下，筛选项只有一行，我应该如何修改，才能使其变为2行或者n行呢？🧐[问题 | question]

### ISSUE THREAD

**Issue by liucys** [ant-design/ant-design-pro#10323]
### 🧐 问题描述 | Problem description
ProTable组件，对于查询表单，默认在不展开情况下，筛选项只有一行，我应该如何修改，才能使其变为2行或者n行呢？🧐[问题 | question]

### 💻 示例代码 | Sample code
<html>
<body>

filterType | 过滤表单类型 | 'query' \| 'light' | 'query'
-- | -- | -- | --
searchText | 查询按钮的文本 | string | 查询
resetText | 重置按钮的文本 | string | 重置
submitText | 提交按钮的文本 | string | 提交
labelWidth | 标签的宽度 | 'number' \| 'auto' | 80
span | 配置查询表单的列数 | 'number' \| 'ColConfig' | defaultColConfig
className | 封装的搜索 Form 的 className | string | -
collapseRender | 收起按钮的 render | (collapsed: boolean,showCollapseButton?: boolean,) => ReactNode | -
defaultCollapsed | 默认是否收起 | boolean | true
collapsed | 是否收起 | boolean | -
onCollapse | 收起按钮的事件 | (collapsed: boolean) => void; | -
optionRender | 自定义操作栏 | ((searchConfig,formProps,dom) => ReactNode[])\|false | -
showHiddenNum | 是否显示收起之后显示隐藏个数 | boolean | false

</body>
</html>

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：
filterType	过滤表单类型	'query' | 'light'	'query'
searchText	查询按钮的文本	string	查询
resetText	重置按钮的文本	string	重置
submitText	提交按钮的文本	string	提交
labelWidth	标签的宽度	'number' | 'auto'	80
span	配置查询表单的列数	'number' | ['ColConfig'](https://procomponents.ant.design/components/table/#ColConfig)	defaultColConfig
className	封装的搜索 Form 的 className	string	-
collapseRender	收起按钮的 render	(collapsed: boolean,showCollapseButton?: boolean,) => ReactNode	-
defaultCollapsed	默认是否收起	boolean	true
collapsed	是否收起	boolean	-
onCollapse	收起按钮的事件	(collapsed: boolean) => void;	-
optionRender	自定义操作栏	((searchConfig,formProps,dom) => ReactNode[])|false	-
showHiddenNum	是否显示收起之后显示隐藏个数	boolean	false

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，您可以通过自定义 CSS 样式来解决这个问题。以下是一个例子，展示了如何将展开的查询表单的行数从默认的一行增加到两行：

```css
// CSS 样式表
.ant-pro-table .ant-pro-table-toolbar .ant-form-item {
  flex-basis: 50%;
  max-width: 50%;
}
```

需要注意的是，这种方式可能存在一些兼容性问题或者被更改的风险。如果您决定使用这种方式，请谨慎操作，并且在需要的时候进行相应的修改。

更好的方式是，针对您的具体业务场景，可以对 ProTable 组件进行二次封装。可以通过在该组件中自定义查询表单的行数，来实现需要展示的查询表单行数的配置化。

具体来说，可以通过 `formProps` 对象的 `layout` 属性进行配置，例如：

```tsx
import ProTable, { ProTableProps } from '@ant-design/pro-table';
import { FormProps } from 'antd/lib/form';

export type MyProTableProps<T, U extends object = {}> = ProTableProps<T, U> & {
  formProps?: FormProps;
};

export const MyProTable = <T extends object, U extends object = {}>({
  formProps,
  ...proTableProps
}: MyProTableProps<T, U>) => {
  return (
    <ProTable<T, U>
      {...proTableProps}
      formProps={{ ...formProps, layout: 'vertical' }}
    />
  );
};
```

在这个例子中，我们对 `ProTable` 组件进行了二次封装，通过 `formProps` 对象来对 QueryForm 组件的布局进行配置。在这里，我们为 `formProps` 对象传入了 `layout: 'vertical'` 属性，该属性表示查询表单布局为垂直排列。由于垂直排列一行仅仅放置一个表单项，因此每个表单项在默认的 24 栅格布局下占据了 24 个格子，因此展开后无法显示多行内容。为了解决这个问题，我们需要修改每个表单项占据的栅格数。因此我们使用了 `formProps` 对象中的 `layout` 属性来设置表单项的样式，具体如下：

```tsx
export const MyProTable = <T extends object, U extends object = {}>({
  formProps,
  ...proTableProps
}: MyProTableProps<T, U>) => {
  const formLayout = formProps?.layout || 'horizontal';
  const formItemSpan = formLayout === 'vertical' ? 12 : undefined;
  const newFormProps = {
    ...formProps,
    labelCol: { span: 7 },
    wrapperCol: { span: 17 },
    layout: 'horizontal', // 保证 ProTable 默认样式不会被覆盖
    itemLayout: formLayout,
    labelAlign: 'right',
    colon: false,
    style: { marginBottom: 16 },
    ...formProps?.style,
  };
  return (
    <ProTable<T, U>
      {...proTableProps}
      formProps={newFormProps}
      search={{
        span: 8,
      }}
    >
      {/* 您的列定义 */}
      {/* ... */}
    </ProTable>
  );
};
```

在这里，我们通过判断 `formProps` 中的 `layout` 属性来确定每个表单项占据的栅格数。在垂直排列模式下，每个表单项占据的栅格数为 12。为了保证自定义样式不会覆盖掉 ProTable 的默认样式，我们使用了 `style` 属性来进行样式覆盖。需要注意的是，这种方式需要您对 ProTable 的二次封装以及样式的认知程度都要较高，否则有可能会引入额外的风险。
