### ISSUE TITLE
🧐[问题 | 请问怎么添加全局页面加载呢]

### ISSUE THREAD

**Issue by xyovo** [ant-design/ant-design-pro#10320]
### 🧐 问题描述 | Problem description

当请求currentUser接口时，响应比较慢的情况，页面就会出现白屏，如下图。我记得旧版的Ant Design Pro是有全局页面加载的，现在找不到了，我也不清楚在哪里添加，查看Pro Components文档也未发现。恳请有人可以帮我看一下，非常感谢！

### 🚑 其他信息 | Other information
yarn v1.22.19
Umi v4.0.9

![image](https://user-images.githubusercontent.com/28668830/197429158-8edd436e-928e-44ea-8d20-13c9a777d454.png)
OS:

Node：
node -v16.13.1
浏览器 | browser：chrome

**Comment by mwj610** [comment]
// config/config.ts
initialState: {
  loading: '@ant-design/pro-layout/es/PageLoading',
},

**Comment by yotcap** [comment]
> // config/config.ts initialState: { loading: '@ant-design/pro-layout/es/PageLoading', },

这个方法不太行，并且会有报错 #10233

**Comment by yotcap** [comment]
[https://preview.pro.ant.design/](https://preview.pro.ant.design/) 官网的预览版本网页源代码中往 div.root 中手动写入了一个 Spin ，但是目前的源码版本中没有相关的内容

**Comment by yotcap** [comment]
> https://preview.pro.ant.design/ 官网的预览版本网页源代码中往 div.root 中手动写入了一个 Spin ，但是目前的源码版本中没有相关的内容

https://github.com/ant-design/ant-design-pro/pull/4055 修改 `document.ejs` ，但是现在模板功能已经废弃了

**Comment by mwj610** [comment]
> > // config/config.ts initialState: { loading: '@ant-design/pro-layout/es/PageLoading', },
> 
> 这个方法不太行，并且会有报错 #10233

  initialState: {
    loading: '@/components/Loading',
  },

用自己的loading也不行吗？我这里可以

**Comment by yotcap** [comment]
> > > // config/config.ts initialState: { loading: '@ant-design/pro-layout/es/PageLoading', },
> > 
> > 
> > 这个方法不太行，并且会有报错 #10233
> 
> initialState: { loading: '@/components/Loading', },
> 
> 用自己的loading也不行吗？我这里可以

抱歉，一开始我理解错了，我是冲着首次加载白屏的问题来的 :(

**Comment by wenjianzhang** [comment]
#10347 可以解决你的问题，亲测有效
效果可以看看  https://antd6.go-admin.pro/

**Comment by liufashi-Mr** [comment]
@umi4 版本默认开启懒加载 loading效果需要再 src下新建loading.tsx  加入如下内容
export { PageLoading as default } from '@ant-design/pro-components';

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的回答，希望能帮助到更多用户。不过之前的问题已经有其他用户回答了，建议您可以看一下其他用户的解答，以免出现重复回答同一个问题的情况。
