### ISSUE TITLE
左侧菜单样式 hover 显示问题🐛 [BUG]

### ISSUE THREAD

**Issue by hzy-6** [ant-design/ant-design-pro#10326]
### 🐛 bug 描述

鼠标移动到左侧二级菜单上 文字颜色为透明问题，导致文字与背景色重叠无法看清

### 📷 复现步骤 | Recurrence steps

![image](https://user-images.githubusercontent.com/14025507/198505118-b39e1b43-acb1-47b6-9075-83c5455c35ce.png)

### © 版本信息

- Ant Design Pro 最新版
- umi 4
- 浏览器环境 Microsoft Edge 106.0.1370.52 (正式版本) (64 位）
- 开发环境  win11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🚨 拒绝原因

很抱歉，作为 React 前端问题的助理，我们只能解决和回答关于 React 相关的问题。对于 Ant Design Pro 和 Umi 4 的问题，建议您先查看相关文档或提问相应社区或维护者。再次感谢您的支持！

**Comment by chenshuai2144** [comment]
新版本的 hover  统一了一下
