### ISSUE TITLE
🧐[问题 | question] v4 - umi 3，build后，整体风格设置按钮和抽屉还在，请问如何关闭？

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#10322]
发布正式版，那个整体风格设置按钮和抽屉还在，请问在哪里配置可以在打包的时候关闭他？

问题：
![image](https://user-images.githubusercontent.com/12421552/197671371-86036585-54b9-47f8-bfa0-0e4d192a9e03.png)

开发版本：
![image](https://user-images.githubusercontent.com/12421552/197671408-8e2a4a4e-51be-42fa-99fb-bed8e8607b35.png)

**Comment by 21haoxingxiu** [comment]
怎么关来着，找了文档 半天没看到

**Comment by mac-boss** [comment]
我也没找到怎么关闭
