### ISSUE TITLE
🐛 [BUG]v5 - max版本 UI适配和出现的bug问题

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#10321]
1、抽屉第一个选项边还有拉手，导致抽屉可以左右拉动。
抽屉菜单未与pc模式下的样式相匹配。
![image](https://user-images.githubusercontent.com/12421552/197670218-383ec5b6-48c8-401e-bbd8-190acca0a46c.png)
![image](https://user-images.githubusercontent.com/12421552/197670255-4adb4b54-00d0-41a8-82ed-e3b5684bed4e.png)

2、用户头像名称信息栏未居中
![image](https://user-images.githubusercontent.com/12421552/197670349-49b21a40-0804-469f-9872-5560cfc6baa2.png)

3、点击头像后，退出等菜单栏覆盖头像
![image](https://user-images.githubusercontent.com/12421552/197670445-a32e8574-4995-4cd1-8bbc-46ed5c04894b.png)

**Comment by wenjianzhang** [comment]
我们项目只求chrome 是正常的 https://antd6.go-admin.pro/

**Comment by edifangyi** [comment]
> 我们项目只求chrome 是正常的 https://antd6.go-admin.pro/

我访问不进去哈

**Comment by wenjianzhang** [comment]
> > 我们项目只求chrome 是正常的 https://antd6.go-admin.pro/
> 
> 我访问不进去哈

账号：admin 密码：123456

**Comment by edifangyi** [comment]
> > > 我们项目只求chrome 是正常的 https://antd6.go-admin.pro/
> > 
> > 
> > 我访问不进去哈
> 
> 账号：admin 密码：123456

感谢，请问怎么开启的Tabs

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


开启 Tabs 非常简单，只需要在 Antd 的 Tabs 组件上添加属性 `type="card"` 即可。代码示例如下：

```jsx
import { Tabs } from 'antd';

const { TabPane } = Tabs;

function handleChange(key) {
  console.log(key);
}

function Demo() {
  return (
    <Tabs type="card" onChange={handleChange}>
      <TabPane tab="Tab 1" key="1">
        Content of Tab Pane 1
      </TabPane>
      <TabPane tab="Tab 2" key="2">
        Content of Tab Pane 2
      </TabPane>
      <TabPane tab="Tab 3" key="3">
        Content of Tab Pane 3
      </TabPane>
    </Tabs>
  );
}

export default Demo;
```

关于 Antd Tabs 组件的详细使用方法，可以参考 [Antd Tabs 文档](https://ant.design/components/tabs-cn/)。

**Comment by chenshuai2144** [comment]
全部修复了
