### ISSUE TITLE
🧐[问题 | 多环境变量配置不生效

### ISSUE THREAD

**Issue by AmilyCi** [ant-design/ant-design-pro#10329]
### 🧐 
在不同的config文件定义不同的BUILDENV变量，根据运行的指令不同，这个变量应该取值不一样，可是现在不论跑dev还是beta还是pro，最后变量的取值都是dev，除非我把config.dev.ts中的BUILDENV改变，控制台输出的BUILDENV才会变，感觉不论我运行什么指令，走的都是config.dev.ts里的配置

### 🚑 其他信息 | Other information
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/29225708/198824699-0817be47-1e7b-41fb-9e35-fbb5be14dee9.png">
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/29225708/198824715-0e43e7e5-59d2-49da-adeb-deac33899199.png">

大佬们，帮忙看看~

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您提供的信息，可以考虑以下解决方案：

1. 确认一下配置文件的路径和文件名是否正确，是否存在拼写错误等情况。

2. 确认一下在运行指令时是否传入了指定的环境变量，例如：`BUILDENV=beta npm run start`，如果没有传入，可能会默认读取dev的配置文件。

3. 如果在配置文件中引入了其他文件进行合并配置，可以检查一下是否有覆盖了原有配置的问题。

4. 可以尝试使用 `console.log(process.env.BUILDENV)` 打印一下环境变量值，看看是否能得到正确的结果，从而确定问题是否出现在配置文件中。

如果以上方法无法解决问题，可以考虑参考以下文档查找更多解决方案：

1. [Webpack多环境打包方案](https://www.jianshu.com/p/9929be9de9c8)
2. [环境变量和模式](https://create-react-app.dev/docs/adding-custom-environment-variables/)
3. [webpack4打包多环境配置](https://www.jianshu.com/p/305a82b063a5)

希望这些信息可以对您有所帮助！如果您还有其他问题或需要更多帮助，请随时提出。

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/guides/env-variables#umi_env

看看是不是被别的地方覆盖掉了。优先级有一些讲究
