### ISSUE TITLE
🐛 [BUG] config "alias" resets defaults

### ISSUE THREAD

**Issue by carlescamig** [ant-design/ant-design-pro#10328]
When I use the "alias" configuration parameter, the defaults aliases are lost

Example code:
export default defineConfig({
alias: {}
}
);

These are some of the  lost aliases
 '@@': '/src/.umi',
 '@': '/src',
etc

**Comment by qxz123456** [comment]
> +1, 求解答，本来通过issue找到了配置新增的paths，但是这样配置导致umi自带的@和@@路径都失效了

想知道你这个问题解决了吗，我也遇到相同的问题了， can`t resolve '@@plugin-request/request',类似这种写法的全都报错了

**Comment by HQDragon** [comment]
> > +1, 求解答，本来通过issue找到了配置新增的paths，但是这样配置导致umi自带的@和@@路径都失效了
> 
> 想知道你这个问题解决了吗，我也遇到相同的问题了， can`t resolve '@@plugin-request/request',类似这种写法的全都报错了

并没有，只能遵从它的官方指示，尽量把东西放在src和public里面

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


使用 `alias` 配置时，应该在配置中保留原有的 aliases，而不是直接重新定义一个空对象。具体来说，可以使用对象合并的方法来合并原有的 aliases 和你自己新增的 aliases，防止新定义的 aliases 覆盖掉原有的 aliases。

示例代码如下：

```javascript
import { defineConfig } from 'umi';

const myAlias = {
  // 在此处添加你需要新增的别名
}

export default defineConfig({
  alias: Object.assign(
    // 在此处合并你新增的别名和原有的别名
    {
       ...require('./alias.config'),
    },
    myAlias
  )
});
```

如果你只想新增一个别名而不需要保留原有的别名，也可以通过以下代码实现：

```javascript
import { defineConfig } from 'umi';

export default defineConfig({
  alias: {
    '@@': '/src/.umi',
    '@': '/src',
    // 在此处添加你需要新增的别名
  }
});
```

此外，如果你使用 `@` 和 `@@` 这两个特殊的别名，应该注意它们的用法。`@` 别名是指向 `/src` 目录的一个路径，而 `@@` 别名是指向 `/.umi` 目录的一个路径。为了避免不必要的错误，你需要先确定你的文件确实需要使用这两个别名，并且你的 umi 应用的目录结构与默认的目录结构相同。如果不是，你需要自行修改这些别名的路径。 

参考链接：[https://umijs.org/docs/config#alias](https://umijs.org/docs/config#alias)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


这个问题的解决方案如下：

1. 检查是否在配置文件中正确地定义了别名(alias)。确保在`defineConfig`配置对象中正确设置了`alias`属性。

2. 确保别名配置(alias)不会覆盖默认的别名。为了避免重置默认别名，可以使用`merge`函数将自定义别名(alias)合并到默认别名中。

   例如：

   ```javascript
   import { merge } from 'webpack-merge';

   export default defineConfig({
     alias: merge({
       // 自定义别名
       '@/components': '/src/components',
       // ...
     }, defaultAlias),
     // ...
   });
   ```

   上述代码中，`merge`函数将自定义别名与默认别名合并，确保不会丢失默认别名。

3. 如果确保上述配置正确的情况下，仍然存在别名丢失的问题，可能是由于其他插件或构建工具的影响。可以尝试禁用其他可能引起冲突的插件，或者检查是否存在其他配置文件中的冲突，比如`.babelrc`或`.eslintrc`等。

4. 如果仍然无法解决问题，建议查看Umi和antd的文档和社区，以寻求更具体的解决方案或提问。

以上是基于提供的信息给出的一般性解决方案，具体情况可能会因为项目的不同而有所差异。
