### ISSUE TITLE
根据文档提示配置openapi报错

### ISSUE THREAD

**Issue by Bill-sh** [ant-design/ant-design-pro#10331]
### 🧐 问题描述 | Problem description
<img width="560" alt="image" src="https://user-images.githubusercontent.com/56359932/198859983-c39db32f-2ac8-46be-acf7-83c5986f6aa3.png">

是不是我哪里配置漏了？？？

### 💻 示例代码 | Sample code
<img width="337" alt="image" src="https://user-images.githubusercontent.com/56359932/198860000-4d5d2106-2a24-4cc0-be41-626c4e05eb59.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/56359932/198860007-080dd366-b82c-4a50-94d5-6f2de79f733d.png">

### 🚑 其他信息 | Other information
<img width="247" alt="image" src="https://user-images.githubusercontent.com/56359932/198860012-67907590-2b08-4fc7-8eb1-7be6b23326c0.png">

"@umijs/max": "^4.0.28",

OS: windows 11

Node：v16.13.1

浏览器 | browser：edge

**Comment by zingwu** [comment]
同样问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题是因为 `@umijs/max` 需要安装 `open-api-generator-cli`，该命令行工具是用来生成 OpenAPI 模板代码的。你需要确保已经全局安装了 `open-api-generator-cli`。

你可以通过以下命令来全局安装该工具：

```bash
npm install @openapitools/openapi-generator-cli -g
```

或者：

```bash
yarn global add @openapitools/openapi-generator-cli
```

如果你已经按照以上方法安装了该工具，还是无法解决问题，那么你需要确认是否使用了正确的 `generatorOptions` 配置参数。可以参考官方文档：[Umi 最大伸缩（umi-plugin-max）](https://umijs.org/zh-CN/plugins/plugin-max)。

如果还有问题，你可以提供更多信息以便我们更好地帮助你解决问题。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，发现问题是在配置openapi时报错。根据提示文档可以尝试以下解决方案：

1. 检查是否正确安装了"@umijs/openapi"模块。可以通过运行命令`npm install @umijs/openapi`或`yarn add @umijs/openapi`来安装。

2. 检查是否正确配置了openapi。根据提供的示例代码，可以检查以下几个方面：
   - 确保在`.umirc.ts`或`config/config.ts`文件中正确配置了openapi：
   ```javascript
   export default defineConfig({
     openapi: [
       {
         requestLibPath: 'openapi',
         schemaPath: 'http://your.api/schema.json',
       },
     ],
   });
   ```
   - 确保`schemaPath`指向正确的openapi规范文件路径，可以尝试使用绝对路径。
   - 确保`requestLibPath`指向正确的请求库路径，比如`@umijs/openapi`。

3. 检查是否正确引入了"@umijs/max"模块。可以在项目的依赖中找到"@umijs/max"模块，并确保版本号为4.0.28。如果未安装该模块，可以通过运行命令`npm install @umijs/max@4.0.28 --save`或`yarn add @umijs/max@4.0.28`来安装。

4. 确保操作系统、Node.js和浏览器的版本符合要求。根据提供的信息，操作系统为Windows 11，Node.js版本为v16.13.1，浏览器为Edge。可以尝试更新Node.js版本或切换到其他支持的浏览器，如Chrome或Firefox
