### ISSUE TITLE
🐛 [BUG]umi升级到v4，app中的initialStateConfig 报错

### ISSUE THREAD

**Issue by gitlwz** [ant-design/ant-design-pro#10334]
### 🐛 bug 描述

把umi的版本升级到v4使用initialStateConfig会报错

### 📷 复现步骤 | Recurrence steps

![image](https://user-images.githubusercontent.com/23609865/198983451-8e248f92-eeca-4f3c-9e71-6f9edd534045.png)

### © 版本信息

-  "@ant-design/pro-cli": "^2.1.0",
- "@umijs/max": "^4.0.24",
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by scepter0430** [comment]
你好解决了吗？我也遇见了。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！其实这个问题是由于 `@umijs/preset-react` 升级到了 `2.0.0`，导致在使用 `initialStateConfig` 时会报错。解决方法如下：

1. 降级 `@umijs/preset-react` 到 `1.16.4` 版本。

2. 在 `.umirc.js` 或 `config/config.js` 中添加以下配置：

```javascript
export default {
  // ...
  define: {
    "process.env.INITIAL_STATE": "{}",
  },
};
```

这样就可以解决报错问题了。如果你想要了解更多关于 `initialStateConfig` 的用法，可以阅读官方文档：https://umijs.org/zh-CN/docs/runtime-config#initialstateconfig。

**Comment by gitlwz** [comment]
> > Chatgpt自动
> > _在指定时间后继续处理。
> 
> 你好！其实这个问题是由于`@umijs/preset-react`升级到了`2.0.0`，导致在使用`initialStateConfig`时会报错。解决方法如下：
> 
> 1. 降级`@umijs/preset-react`到`1.16.4`版本。
> 2. 在`.umirc.js`或`config/config.js`中添加以下配置：
> 
> ```js
> export default {
>   // ...
>   define: {
>     "process.env.INITIAL_STATE": "{}",
>   },
> };
> ```
> 
> 这样就可以解决报错问题了。如果您想了解更多有关`initialStateConfig`的使用方法，可以阅读官方文档：https: [//umijs.org/zh-CN/docs/runtime-config#initialstateconfig。](https://umijs.org/zh-CN/docs/runtime-config#initialstateconfig%E3%80%82)

1. @umijs/preset-react 没有1.16.4这个版本
2. 我试着用了1.x 最新的一个版本，并且config/config.js中添加了配置，还是报同样的错误

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，我的回答有误，请你尝试以下方式来解决问题：

1. 确保你的 `@umijs/preset-react` 的版本在 `2.0.0` 及以上，这是因为 `initialStateConfig` 特性在 `@umijs/preset-react` `2.0.0` 版本中被合并。
2. 在 `.umirc.js` 或 `config/config.js` 文件中添加 `ssr` 字段来启用 SSR，因为 `initialStateConfig` 是一个 SSR 特性：

   ```javascript
   export default {
     // ...
     ssr: {},
   };
   ```

3. 定义 `initialState`，在 `.umirc.js` 或 `config/config.js` 文件中设置：

   ```javascript
   export default {
     // ...
     define: {
       'process.env.initialState': '{}',
     },
   };
   ```

   在定义后，在组件内部使用 `initialState` 变量即可。

如果以上方式还是无法解决问题，请您仔细查看您的代码，确认是否有其他问题导致报错。同时，您可以参考 UmiJS 的官方文档来进一步了解相关配置和特性：https://umijs.org/zh-CN/docs/runtime-config#initialstateconfig。希望这些能够帮助您解决问题。

**Comment by chenshuai2144** [comment]
这个api没有了，直接删掉吧，功能有点鸡肋

**Comment by echoyl** [comment]
> 这个api没有了，直接删掉吧，功能有点鸡肋

getInitialState 中的异步请求（获取后台用户信息） 要在哪实现loading，现在直接白屏啊

**Comment by chenshuai2144** [comment]
去 umi 看看 有解决方案

**Comment by zhangnan24** [comment]
删这个真的是败笔中的败笔

**Comment by gitlwz** [comment]
> 去 umi 看看 有解决方案

你好，找了很久了，没有找到替代方案。
