### ISSUE TITLE
布局全乱了

### ISSUE THREAD

**Issue by chunzhuLiu** [ant-design/ant-design-pro#10338]
下载官网的源代码，或者用pro工具创建，都会出现布局混乱的问题

![818e33ca438949df965f17aa633b99e](https://user-images.githubusercontent.com/83159492/199379497-d70e366e-2106-4f8c-ab6d-0d05ac2f1b72.jpg)
![4411b190a8191476841384f3b0d5e92](https://user-images.githubusercontent.com/83159492/199379502-9758512b-7407-491d-abb2-582d693bf9eb.jpg)
![313346092309f528829ae556048da3c](https://user-images.githubusercontent.com/83159492/199379504-46fa5cdc-b95a-4f0d-bb29-5a4fa63b3b99.jpg)

**Comment by fanhaich** [comment]
我也遇到同样的问题，有哪位大神帮忙看一下吗？貌似pro的样式没有

**Comment by chao-smile** [comment]
你们是不是用的360浏览器极速模式🤣
![image](https://user-images.githubusercontent.com/105209201/200710368-c7a0a5e1-da21-46ec-b7a0-bcc7b83a76fe.png)
![image](https://user-images.githubusercontent.com/105209201/200710527-6523a648-08ed-4f6f-9ec2-f1f1107f6584.png)
![image](https://user-images.githubusercontent.com/105209201/200710622-775d4a1c-968c-4718-a862-66a3e95c574f.png)
以上分别是360、火狐、edge
使用官方网页测试了一下，最新版的[ProComponents](https://procomponents.ant.design/)不支持360浏览器
![微信图片_20221109090829](https://user-images.githubusercontent.com/105209201/200711347-a8f0257f-0971-4d23-8978-5aa60a117f94.jpg)
![image](https://user-images.githubusercontent.com/105209201/200711441-35f4f970-947b-444f-b4da-19a8bbfa1842.png)

**Comment by shujun222** [comment]
这个问题太难受了，因为想用umi4, 所以硬着头皮折腾了好久；
我是chrome85，用户还很多chrome65的
应该是@umijs/max中引入的@ant-desing/pro-layout 版本太新了，layout css都丢失了
作者用了 :where()语法，太新了
![image](https://user-images.githubusercontent.com/45231907/201255018-aa80a2f5-52b2-4856-a20d-943f69b0e0ae.png)

1. 尝试一：
   重新安装一个依赖  yarn add xxx@npm:@ant-desing/pro-layout@6.4.1
   然后src/layout/BaseLayout.tsx中引入xxx，根据官网重写布局代码，是没问题的。
2. 尝试二
    参考https://preview.pro.ant.design/，  在global.less中重写layout相关样式，也能行

最后还是期待作者尽快修复下这问题 ~

**Comment by a1exlism** [comment]
如果项目较小的话，可以尝试进行降级，pro 5.2.0, umi v3, 相当一部分代码不需要修改，其中 antd 的依赖可以更新至 4.23.x 以适应新的写法。
如楼上所说，pro-component 所用的代码至少需要 Chrome 88(2021年1月更新），Umi v4 也放弃支持 IE11 了。

**Comment by lovewinders** [comment]
同上我也碰到360极速浏览器兼容问题，目前360极速浏览器chromiun版本78

**Comment by lqliqi** [comment]
> 

解决了吗，今天我也遇到了同样的问题，用的 Umi max 基于  Ant Design Pro ,360急速浏览器样式全乱了

**Comment by Wangbaoqi** [comment]
1

**Comment by yotcap** [comment]
关键是安卓微信浏览器也是有兼容问题，难受

**Comment by GuanErShuiShou** [comment]
本身umi提供了配置但是对antd以及pro-layout都不生效，毕竟是一套生态系统这得兼容下吧

**Comment by lingkedu** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/55617889/b94533f4-9255-4429-9d83-34afa61e39e0)
大家可以看一看https://procomponents.ant.design/docs/faq
