### ISSUE TITLE
🧐[问题 |EditableProTable的展示数据来源]如何将不同来源数据放入同一个表中展示(内有详细场景描述)

### ISSUE THREAD

**Issue by hustwebh** [ant-design/ant-design-pro#10349]
### 🧐 问题描述 | Problem description

+ 场景需求是做近似Navicat的数据表建立(见图一)
+ 其中有一个从其他table导入数据的功能需求,我选择用树形组件实现,并通过数据处理获得被选中的数据(见图二)
+ 但是找不到合适的方法让他们显示在列表中
+ 换一个方式,已经设置request作为EditableProTable的数据来源了,怎么吧两个不同数据来源的数据都展示到表中

### 💻 示例代码 | Sample code

因为是方案询问,暂无代码

### 🚑 其他信息 | Other information
图一如下:
![图片](https://user-images.githubusercontent.com/76393033/200364938-04755f03-4ff8-4e68-a50e-2a4f5a392cd8.png)
图二如下:
![图片](https://user-images.githubusercontent.com/76393033/200365334-e1866897-0f21-4ba5-9bec-f3ab01d38dd2.png)

OS:archLinux

Node：v14.19.0

浏览器 | browser：firefox

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 📝 解决方案 | Solution

针对这个问题，可以考虑以下两种方案：

1. 将两种数据来源的数据合并为一个数组，然后将合并后的数据作为EditableProTable的数据源，这个方法比较简单。

   ```javascript
   const dataSource1 = [{ id: 1, name: "Jack", age: 28 }];
   const dataSource2 = [{ id: 2, name: "Tom", age: 30 }];

   const dataSource = [...dataSource1, ...dataSource2];

   // 设置dataSource为EditableProTable的数据源
   <EditableProTable dataSource={dataSource}>
     {/* columns */}
   </EditableProTable>
   ```

2. 在EditableProTable中设置一个数据源request，然后在请求数据前通过Redux或其它状态管理工具，将两种来源的数据先保存到store中，再通过request中的参数将保存在store中的数据返回给表格。

   ```javascript
   <EditableProTable
     request={async () => {
       const dataSource1 = // 通过Redux获取数据
       const dataSource2 = // 通过Redux获取数据
       const dataSource = [...dataSource1, ...dataSource2];
       return { data: dataSource };
     }}
   >
     {/* columns */}
   </EditableProTable>
   ```

以上两种方案都可以实现两种不同数据来源的数据合并后展示在同一个表格中，具体实现方式根据项目的实际需求来选择。同时，为了更好的理解EditableProTable的使用，可以参考Antd官网的相关文档：https://ant.design/components/table-cn/

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述，你想要在EditableProTable中展示来自两个不同数据来源的数据。你已经使用了一个树形组件来导入数据，并通过数据处理获取所选中的数据。现在你想知道如何将这些数据展示在同一个表中。

以下是可能的解决方案：

1. 将两个数据来源的数据合并成一个数据源：你可以在树形组件中选中数据后，将其放入一个数组或对象中。然后，在请求EditableProTable的数据时，将这个数组或对象作为一个请求参数一同发送到后端，后端根据参数来返回合并后的数据。这样，EditableProTable就可以展示来自两个不同数据来源的数据了。

2. 分别请求两个数据源的数据，并在前端进行数据合并：你可以在树形组件中选中数据后，分别请求两个数据来源的数据。然后，通过数据处理将两个数据源的数据合并成一个数组或对象。最后，将合并后的数据作为请求EditableProTable的数据，并展示在表中。

具体的实现方式取决于你的业务逻辑和数据结构，以及你使用的框架和库。以上是一些基本的解决方案，希望对你有帮助。
