### ISSUE TITLE
你们能不能把文档写好一点？

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design-pro#1034]
各种驴唇不对马嘴的地方，举个例子：

在目前（2018.3.6）的文档中，[图表](https://pro.ant.design/docs/graph-cn)里关于如何使用图表是这么描述的：

>Charts 图表套件是在 ant-design-pro/lib/Charts 包中，引用到项目就像使用其它组件一样

但是我现在用你们脚手架(pro 1.0.0)生成的项目（1.1.0）中，根本就没有安装 ant-design-pro 这个包，`package.json` 的依赖也没有

而根据你们项目里的 `src/routes/Dashboard/Analysis.js` 组件的实例，表的组件其实是来自`'../../components/Charts'`

最后又发现你们又安装了 `@antv` 这个图表组件

也就是你们的文档，和脚手架生成的项目实践，以及你们给开发者提供的类库根本是不统一的

能不能统一一下？把文档写好一点？

**Comment by afc163** [comment]
这一块关于 `ant-design-pro/lib/xxx` 的描述，文档确实应该再清晰一点。@nikogu

**Comment by nikogu** [comment]
@hh54188 首先感谢你的反馈，其次如果文档有不足的地方最好能够详细指出或者提交 mr，我们会尽快更改。

**Comment by xiaolongyuan** [comment]
说话戾气真重

**Comment by laozb** [comment]
喝点菊花茶降降火楼主。。。。
