### ISSUE TITLE
🐛 [BUG] - Nested route with components not working

### ISSUE THREAD

**Issue by nqhd3v** [ant-design/ant-design-pro#10344]
### 🐛 bug 描述
Hello everyone, I meet an issue "Nested route with components not working when adding wrapper component".

My issue looks like [this issue](https://github.com/ant-design/ant-design-pro/issues/5873), but not, it is different.

This is my routes configuration:
```ts
export default [
  // ...some routes without authenticating
  {
    path: '/',
    redirect: '/manage',
  },
  {
    path: '/manage',
    component: '../layouts/AuthWrapper',
    routes: [
      {
        path: '/manage',
        name: 'manage',
        icon: 'smile',
        component: './Welcome'
      },
      // ... some routes authenticated with firebase
      {
        path: '*',
        component: './404',
      },
    ],
  },
  {
    path: '*',
    layout: false,
    component: './404',
  },
]
```
My issue is the empty page when accessing to route "/manage". (This component is not called, I add a command in my component (`console.log('manage page')`), but it doesn't log anything. -> I guess that component `AuthWrapper` has an issue.  

After I go to `AuthWrapper`, this is my code:
```tsx
interface IAuthWrapper {
  children: React.ReactElement;
}

const AuthWrapper: React.FC<IAuthWrapper> = ({ children }) => {
  const [user, loading] = useAuthState(firebaseAuth);

  useEffect(() => {
    if (!user && !loading) {
      history.push('/login');
    }
  }, [user, loading]);

  if (loading) {
    return <LoadingPage />
  }
  console.log('wrap', children);

  return (
    <div className="">{children}</div>
  );
}

export default AuthWrapper;
```
It logged `wrap undefined`. I don't know why.

> Note, I wrapped `{children}` with `div`, to prevent it shows the error `AuthWrapper(...): Nothing was returned from render`.

Absolutely, I have tried to change my order of routes. However, when I removed `component: '../layouts/AuthWrapper',` in my routes configrations, it worked :) So I guess that something went wrong with `AuthWrapper.tsx`.

> Note, I installed it with the command `pro create ___` today.

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本
- 浏览器环境
- 开发环境 mac OS

**Comment by drizzlesconsin** [comment]
https://umijs.org/docs/guides/routes#routes

**Comment by nqhd3v** [comment]
Thank you so much!
