### ISSUE TITLE
antdpro demo couldn't be logged in 🐛 [BUG]

### ISSUE THREAD

**Issue by complete-fangzr** [ant-design/ant-design-pro#10346]
### 🐛 bug 描述

User name: admin, password: ant.design Failed to log inDescribe the bug in detail so that everyone can understand it

### 📷 复现步骤 | Recurrence steps

User name: admin, password: ant.design 

### 🏞 期望结果 | Expected results

Log in successfully

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="434" alt="image" src="https://user-images.githubusercontent.com/93582316/200223568-0ddd6282-d919-467e-9b74-657d47e83840.png">

**Comment by ngjuping** [comment]
try using `yarn start` instead, it worked for me. Username: `admin`, password: `ant.design`

**Comment by hyzx86** [comment]
从git 仓库拉取最新代码，cli更新可能不及时

https://github.com/ant-design/ant-design-pro/pull/10453

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


谢谢分享这个信息。从git仓库拉取最新代码确实可以解决一些问题，因为它更新的速度更快，cli更新可能需要一些时间才能生效。

另外，还需要注意使用与Ant Design Pro版本相应的umi版本和依赖项版本，以最大程度地避免出现问题。如果您有任何其他问题，可以尝试查看官方文档或在github上寻求帮助。
