### ISSUE TITLE
🐛 [BUG] [MFSU][eager]pro create创建的工程启动异常

### ISSUE THREAD

**Issue by DevilMayDead** [ant-design/ant-design-pro#10340]
### 🐛 bug 描述

pnpm 安装 pro crete创建的antd pro异常

error - [MFSU][eager] worker got Error Error: Cannot find module 'umi/dist/service/service'
Require stack:
- D:\私有项目\modulefeaderation\node_modules\.pnpm\@umijs+preset-umi@4.0.28_kpbq77yyfncz3hhtrfspxkahla\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\getConfig.js
- D:\私有项目\modulefeaderation\node_modules\.pnpm\@umijs+preset-umi@4.0.28_kpbq77yyfncz3hhtrfspxkahla\node_modules\@umijs\preset-umi\dist\commands\dev\depBuildWorker\depBuildWorker.js

**Comment by SofiaPetinova** [comment]
Hi! Did you find how to fix this problem?

**Comment by huliang1996618** [comment]
我也是，你怎么解决的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，从错误信息看似乎是找不到`umi/dist/service/service`模块，可能是模块没有被正确加载或者缺失。您可以尝试以下解决方案：

1. 确认是否通过npm或yarn等包管理工具安装了umi和antd pro中的所有依赖。
2. 如果依赖已安装，请运行以下命令清除缓存并重新安装依赖：

   ```bash
   # 使用npm
   npm cache clean --force
   npm install

   # 使用yarn
   yarn cache clean
   yarn install
   ```

3. 检查`config.ts`文件是否已正确配置，确保设置了正确的路径：

   ```typescript
   // config.ts
   const config = {
     // ...
     mfsu: {
       //...
     }
   }
   ```

   如果没有配置，请添加 mfsu 对象并设置 strategy 字段值为 'normal'，应该像这样：

   ```typescript
   // config.ts
   const config = {
     // ...
     mfsu: {
       strategy: 'normal'
     }
   }
   ```

   更多关于 mfsu 的信息和配置，可以参考 [umi 官方文档](https://umijs.org/zh-CN/config/#mfsu)。

如果以上方案均不能解决问题，您可以提交具体错误堆栈信息，以更好地帮助您解决问题。
