### ISSUE TITLE
🧐[问题 | question]最新版antd-pro 样式丢失问题

### ISSUE THREAD

**Issue by fanhaich** [ant-design/ant-design-pro#10342]
### 🧐 问题描述 | Problem description
按umi4官网步骤，创建项目，选择pnpm，antd pro，淘宝源，然后pnpm install安装依赖，pnpm dev启动项目，结果样式丢失了；
使用pro create 创建的antd pro项目，启动后，样式也是丢失的

![image](https://user-images.githubusercontent.com/14833527/199898780-53e19c2a-31a6-42ac-8ac4-644a75fcf48d.png)

补充一下，发现很多样式：**css-dev-only-do-not-override**

![image](https://user-images.githubusercontent.com/14833527/199903998-69dbc9fb-3a23-440b-bdec-41650f828ddb.png)

OS: windows10

Node：16.14.0

浏览器 | browser：chrome 87.0.4280.66

**Comment by wenjianzhang** [comment]
umi@3 项目升级umi@4 

操作步骤根据master分支按照版本迁移

yarn 包安装

目前问题不大，线上demo https://antd6.go-admin.pro/

**Comment by chao-smile** [comment]
@wenjianzhang 
这叫问题不大？😭

![image](https://user-images.githubusercontent.com/105209201/200713174-85c7daea-b106-4c7f-9860-2b410b98ae7e.png)
![image](https://user-images.githubusercontent.com/105209201/200713315-8a0d6b34-fc22-47eb-84a5-631231617ba3.png)

**Comment by JLoveI** [comment]
我也有同样的问题 不明白加入 css-dev-only-do-not-override的意义，影响了整体样式

**Comment by lovewinders** [comment]
我也在360浏览器碰到该问题，内核低于chromium88就会出现该问题，希望解决

**Comment by 426-330** [comment]
css-dev-only-do-not-override。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by yotcap** [comment]
安卓版的微信浏览器也会有兼容问题，内核有点低

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你们的反馈，这个问题可能是由于兼容性问题引起的，以下是一些可能的解决方案。

1. 确认浏览器的兼容性问题

首先，你们可以通过使用兼容性检测工具（例如CanIUse）来确定你们的浏览器是否兼容所使用的CSS样式。如果你们的浏览器版本太低而无法兼容特定的CSS属性或样式规则，那么该问题可能就是无法避免的。

2. 更新或更换浏览器

如果你们确定是浏览器兼容性问题，请考虑更新浏览器或更换为更新的浏览器，例如Chrome或Firefox。这些浏览器通常较为优化和兼容CSS样式，以确保在其上显示结果更加一致。

3. 查看css-dev-only-do-not-override代码

此外，如果你们可以将此问题反馈给开发人员，建议要求其提供有关“css-dev-only-do-not-override”代码的更多信息。这可能是某种自定义CSS样式规则，可能与特定浏览器版本有关，导致无法正确呈现页面中的某些元素。如果可以获得更多信息，就更有可能找到解决方案。

希望这些建议可以帮助你们找到解决该问题的方法。

**Comment by NieShiyi** [comment]
1. 我也按照官网文档umi4进行安装  安装命令如下`pnpm dlx create-umi@latest`
2. 选择模板时选择了antd design pro
3. 也发现了样式问题异常。我查看了一下当前我的 "@umijs/max": "^4.0.64" ，然后"@ant-design/pro-components": "^2.0.1"。我尝试着给@ant-design/pro-components升级成最新的"@ant-design/pro-components": "^2.4.4"后。样式就正常了。
建议：是不是当"@umijs/max"升级的时候，安装对应的 "@ant-design/pro-components"这些包也应该升级一下。不然会给用户不好的用户体验

**Comment by chenshuai2144** [comment]
更新下版本，应该是锁包了
