### ISSUE TITLE
🐛 [BUG] commit error info messy code

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design-pro#10357]
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本  4
- 浏览器环境
- 开发环境 [e.g. win11 OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26128706/200788261-bbf1a041-8255-4a96-8298-0c558b0dceb7.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的反馈，根据您提供的信息，发现您遇到的问题是提交代码时出现乱码的问题。

这个问题通常是由于系统编码与 git 的编码不一致导致的，在 Windows 系统中常见。您可以尝试采用以下方法解决：

1. 设置全局编码

您可以在 Git Bash 中执行以下命令，将 Git 的全局编码设置为 UTF-8：

```
git config --global core.quotepath false
git config --global i18n.commit.encoding utf-8
git config --global i18n.logoutputencoding utf-8
```

2. 设置项目级别编码

如果全局设置无效，您可以尝试在项目根目录下的 `.git` 文件夹中的 `config` 文件中添加以下语句：

```
[i18n]
    commitencoding = utf-8
```

您也可以通过编辑器的设置来修改项目编码，例如 VS Code 中可以通过设置 `files.encoding` 为 `utf8` 来解决。

希望以上方法能够解决您的问题，如果还有其他疑问或者问题，请随时联系我们并提供更多细节信息以便更好的帮助您。同时，我们也建议您参考 Git 官方文档进行更深入的学习和理解。
