### ISSUE TITLE
🧐[问题 | question]  proLayout 如何设定 token 自订样式?

### ISSUE THREAD

**Issue by tedshd** [ant-design/ant-design-pro#10358]
我这里有个问题想要请教
在初始化专案时是选 `umi@3` 和 `simple`
想要在 pro layout 设定 token 来自定义样式

但是在 src/app.tsx
看到和[文件](https://procomponents.ant.design/components/layout/)不一样
好像已经抽象化了 proLayout 元件
https://github.com/tedshd/antd_sample/blob/master/myapp/src/app.tsx#L53

有尝试在 config/config.ts 或 config/defaultSettings.ts 添加 token 的设定

但都没有生效

请问要如何使用?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好！根据您描述的问题，我理解您想要在使用 `umi@3` 和 `simple` 的项目中，通过设置 `proLayout` 中的 token 来自定义样式。

在 `umi@3` 中，官方推荐使用 `app.tsx` 文件进行全局配置，因此您可以在该文件中找到 `proLayout` 元件的设置代码，通过设置 `proLayout` 的 `menuHeaderRender` 属性来达到自定义样式的效果。以下是大致的代码示例:

```tsx
import { ProLayout } from '@ant-design/pro-layout';
import { history } from 'umi';

// 在这里声明您需要使用到的token
const token = '您的token'

const BasicLayout: React.FC = ({ children }) => (
  <ProLayout
    // menuHeaderRender为渲染头部的函数，可以自定义header中的样式
    menuHeaderRender={(logo, title) => (
        <a href="/">
          {logo}
          <span>{title}</span>
          <span>{token}</span> // 在这里加入token
        </a>
    )}
    {...其他属性}
  >
    {children}
  </ProLayout>
);

export default BasicLayout;
```

在上述代码示例中，我们声明了需要使用到的 `token`，并将其放入 `menuHeaderRender` 中，最终渲染在了 ProLayout 的 header 中。

值得注意的是，由于不清楚您尝试添加 token 设定的方法，因此无法给出具体的引导。不过，您可以尝试将 `token` 存储在全局变量或者通过 fetch 请求获取到，然后再在 `menuHeaderRender` 中使用。请确保 `token` 存在并且可以使用。

希望这能够帮助到您！
