### ISSUE TITLE
  hideInMenu: true,和hideInBreadcrumb: true,  从呈现效果上hideInBreadcrumb: true,有什么作用

### ISSUE THREAD

**Issue by cyp66** [ant-design/ant-design-pro#1036]
hideInMenu: true，是菜单隐藏，可以从菜单中看出一个菜单项隐藏掉了，
hideInBreadcrumb: true, 看不出什么效果，请大牛解释！

**Comment by ddcat1115** [comment]
hideInMenu 是在侧边栏菜单中隐藏，hideInBreadcrumb 是在页头的面包屑中隐藏这一级

**Comment by cyp66** [comment]
页头的面包屑是？

**Comment by pkaq** [comment]
![1](https://user-images.githubusercontent.com/4537450/37070733-ed247d8a-21f3-11e8-8d87-3c2aca38a089.jpg)

**Comment by cyp66** [comment]
知道了，非常感谢|！

**Comment by afc163** [comment]
@cyp66 建议以后自行关闭 issue。

**Comment by cyp66** [comment]
为什么




| |
崔玉萍
|
|
邮箱：cuiyuping66@126.com
|

签名由 网易邮箱大师 定制

在2018年03月07日 14:26，偏右 写道：

@cyp66 建议以后自行关闭 issue。

**Comment by pkaq** [comment]
。。。。。。。
始乱终弃，君子所恶，为人言之，不为尔曹言之也

**Comment by cyp66** [comment]
刚明白怎么用这个平台~

**Comment by cyp66** [comment]
@afc163 刚明白平台怎么用，以后会自行close
