### ISSUE TITLE
按需加载js

### ISSUE THREAD

**Issue by usertan** [ant-design/ant-design-pro#10369]
### webpack5 splitChunks 配置后并没有按需加载，而是全量加载 

config.optimization.splitChunks 配置了公共代码部分，打包加载时是同步加载，而并非按照菜单路由的加载而动态加载该路由需要的公共部分js 文件

### 💻 示例代码 | Sample code

config.optimization.splitChunks({
      chunks: "all",
      minSize: 20000, // 允许新拆出 chunk 的最小体积，也是异步 chunk 公共模块的强制拆分体积
      maxAsyncRequests: 6, // 每个异步加载模块最多能被拆分的数量
      maxInitialRequests: 6, // 每个入口和它的同步依赖最多能被拆分的数量
      enforceSizeThreshold: 50000, // 强制执行拆分的体积阈值并忽略其他限制
      cacheGroups: {
        libs: { // 第三方库
          name: "chunk-libs",
          test: /[\\/]node_modules[\\/]/,
          priority: 10,
          chunks: "initial" // 只打包初始时依赖的第三方
        },
        //其余异步加载包
        asynccommons: {
          chunks: 'async',
          minChunks: 2,
          name: 'asynccommons',
          priority: 9
        },
        //rc-components组件
        rccomponents: {
          name: 'rccomponents',
          test: /[\\/]node_modules[\\/]_?rc-(.*)/,
          priority: 50,
          chunks: 'async'
        },
        //项目公共组件
        components: {
          name: 'chunk_components',
          chunks: 'async',
          test: resolve('src/base'), // can customize your rules
          minChunks: 2, // minimum common number
          priority: 55,
          reuseExistingChunk: true
        },
       ...getPages(PAGES)
      },

    })
有很多的通用代码我也像上面的方式提出来
const getPages = (pagesList: string[])=>{
  const a = {}
  let i = 60;
  pagesList.forEach(item=>{
    a['pages_' + item] = {
      name: 'pages_' + item,
      chunks: 'async',
      test: resolve('src/pages/'+item), // can customize your rules
      minChunks: 2, // minimum common number
      priority: i,
      filename: 'pages_'+ item + '.async.js',
    }
    i+=5;
  })
  return a
}

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/14966409/201834053-a098b5a6-5c7b-4043-9715-814a3d0c79d2.png)

如上面 data.ts 或者其他 tsx ，ts 都是公共代码部分，还有很多的pages 下面业务代码部分都有公共代码部分，我都通过面向对象编程的方式提取出来了，但是提取出来后，无论在那个页面，那些公共代码部分都是一次性被加载出来了，这样很不科学。所以需要把业务代码的公共部分也按需加载，且加载一次，不知道怎么实现，求助！

OS:

win 10 
antd pro 5.2.0
Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您的描述，问题可能是由于缺少动态导入语法导致的。按需加载需要使用动态导入语法，即 `import()` 语法。将公共代码部分封装到单独的文件中，然后使用 `import()` 语法在需要的页面中按需加载。

例如，您可以将公共代码部分封装到 `common.js` 文件中：

```javascript
// common.js
export const common1 = () => {
  console.log('common1')
}

export const common2 = () => {
  console.log('common2')
}
```

然后在需要的页面中按需加载公共代码部分：

```javascript
// page.js
import(/* webpackChunkName: "common" */ './common').then(common => {
  const { common1 } = common
  common1()
})
```

其中 `webpackChunkName: "common"` 表示将公共代码打包到名为 `common` 的 chunk 中。

除此之外，您还需要配置 webpack 的 `output.chunkFilename` 选项，以指定按需加载的 chunk 的名称，例如：

```javascript
output: {
  filename: '[name].js',
  chunkFilename: '[name].chunk.js',
  path: path.resolve(__dirname, 'dist')
}
```

更多关于动态导入语法的信息，您可以参考官方文档：https://webpack.js.org/guides/code-splitting/#dynamic-imports

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决该问题的思路是使用React.lazy和Suspense来实现按需加载和动态渲染组件。具体步骤如下：

1. 首先，在每个需要按需加载的组件文件中，使用React.lazy函数来包裹组件的导入语句，示例如下：

```jsx
const MyComponent = React.lazy(() => import('./MyComponent'));
```

2. 在需要使用该组件的地方，使用Suspense组件来包裹懒加载组件，并设置fallback属性来指定在加载完成前显示的备用内容，示例如下：

```jsx
import React, { Suspense } from 'react';

function App() {
  return (
    <div>
      <Suspense fallback={<div>Loading...</div>}>
        <MyComponent />
      </Suspense>
    </div>
  );
}
```

3. 在webpack配置中，通过设置optimization.splitChunks来配置代码分割策略，示例如下：

```javascript
module.exports = {
  // ...其他配置
  optimization: {
    splitChunks: {
      chunks: 'async',
      minSize: 20000,
      maxSize: 0,
      minChunks: 1,
      maxAsyncRequests: 6,
      maxInitialRequests: 4,
      automaticNameDelimiter: '~',
      cacheGroups: {
        defaultVendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: -10
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true
        }
      }
    }
  },
};
```

4. 在Umi中，可以使用dynamic函数来实现按需加载组件。在配置文件config.js中，使用dynamic来包裹组件的import语句，示例如下：

```javascript
export default {
  routes: [
    {
      path: '/',
      component: dynamic(
        {
          loader: () => import('./pages/Home'),
          loading: LoadingComponent, // 加载过程中显示的组件
        }
      ),
    },
    //...其他路由配置
  ],
};
```

通过以上步骤，就可以实现按需加载js文件，并在路由切换时动态加载所需的公共代码部分。请根据您的具体项目进行配置和调整。
