### ISSUE TITLE
🐛 [BUG] Upload组件，按照官方案例写的代码，文件一直loading

### ISSUE THREAD

**Issue by yqz945** [ant-design/ant-design-pro#10361]
### 🐛 bug 描述

上传文件通常有后续处理，用到customRequest, 我按照官方案例写的上传，文件一直loading状态。从日志看progress已经100%， onSuccess也调用。 
官方案例：
https://github.com/react-component/upload/blob/master/docs/examples/customRequest.tsx

1.点击上传按钮选择文件上传
2.后台处理完成，上传完成。

### 🏞 期望结果 | Expected results

上传完成loading状态结束。

### 💻 复现代码 | Recurrence code

代码如下：
```
const props = {
    name: 'file',
    action: '/api/upload-data?code=' + dm_code,
    accept: 'file',
    data: {},
    exts: 'xlsx|xls',
    onStart(file) {
      console.log('onStart', file, file.name);
    },
    onSuccess(res, file) {
      console.log('onSuccess', res, file.name);
      message.success(`${file.name} file uploaded successfully`);
    },
    onError(err) {
      console.log('onError', err);
    },
    onProgress({percent}, file) {
      console.log('onProgress', `${percent}`, file.name);
    },
    customRequest({
                    action,
                    data,
                    file,
                    filename,
                    headers,
                    onSuccess,
                    onError,
                    onProgress
                  }) {
      const formData = new FormData();
      formData.append(filename, file);

      axios.post(
        action,
        formData,
        {
          headers,
          onUploadProgress: ({total, loaded}) => {
            onProgress({percent: Math.round((loaded / total) * 100).toFixed(2)}, file);
          },
        })
        .then(({data: response}) => {
          onSuccess(response, file);
        })
        .catch(onError);

      return {
        abort() {
          console.log('upload progress is aborted.');
        },
      };
    }
  };


<ModalForm
        title={dm.name + '数据上传'}
        open={modalVisit}
        onFinish={async () => {
          message.success('提交成功');
          return true;
        }}
        onOpenChange={setModalVisit}
      >
        <Upload {...props}>
          <Button icon={<UploadOutlined/>}>点击上传</Button>
        </Upload>
 </ModalForm>
```

### © 版本信息

- Ant Design Pro 版本: ant-design-pro@6.0.0-beta.1
- umi 版本 Umi v4.0.260.0-beta.1
- 浏览器环境 Edge 107.0.1418.35
- 开发环境 [e.g. mac OS]  win11

### 🚑 其他信息

![lenovo20221112111309](https://user-images.githubusercontent.com/73603335/201453921-d8fabd2f-d690-4005-bc0f-c46c2680cb4e.png)

**Comment by yqz945** [comment]
我发现这里的customRequest根本没有被调用。 我把customRequest注释掉了， 现象是一样的，文件依旧通过action上传了。用这个我感觉要靠猜

**Comment by yqz945** [comment]
如果我import {Upload} from "antd";
这会出现这个问题。

如果我改成 import Upload from 'rc-upload';
上传之后就没有文件列表了。
![lenovo20221112115352](https://user-images.githubusercontent.com/73603335/201455621-11b29285-a46d-4b91-aec1-6d05fc5bde58.png)

**Comment by yqz945** [comment]
注释掉customRequest方法，功能一样， customRequest没有被调用

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的信息，一种可能原因是antd Upload组件和rc-upload组件的props存在差异。

建议你检查antd Upload组件和rc-upload组件的props定义及使用方式是否一致。

如果问题仍然存在，可以尝试使用官方提供的rc-upload组件，但是需要手动实现文件列表展示。具体做法可以参考rc-upload的文档：

https://github.com/react-component/upload#customrequest

在customRequest函数中，你需要自己维护文件列表，例如通过useState()来维护一个文件对象数组。同时，在onSuccess回调中也需要根据response来更新文件列表。

另外，如果你使用的是antd Upload组件，建议你使用官方提供的customRequest示例代码，并将自己的需求适配进去。官方示例可以在这里找到：
https://github.com/ant-design/ant-design/blob/master/components/upload/demo/ajax.md#Upload-props

希望这些信息能帮助你解决问题。

**Comment by chenwll** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。↳
> 
> 根据你提供的信息，一种可能原因是antd Upload组件和rc-upload组件的props存在差异。
> 
> 建议你检查antd Upload组件和rc-upload组件的props定义及使用方式是否一致。
> 
> 如果问题仍然存在，可以尝试使用官方提供的rc-upload组件，但是需要手动实现文件列表展示。具体做法可以参考rc-upload的文档：
> 
> https://github.com/react-component/upload#customrequest
> 
> 在customRequest函数中，你需要自己维护文件列表，例如通过useState()来维护一个文件对象数组。同时，在onSuccess回调中也需要根据response来更新文件列表。
> 
> 另外，如果你使用的是antd Upload组件，建议你使用官方提供的customRequest示例代码，并将自己的需求适配进去。官方示例可以在这里找到： https://github.com/ant-design/ant-design/blob/master/components/upload/demo/ajax.md#Upload-props
> 
> 希望这些信息能帮助你解决问题。

https://github.com/ant-design/ant-design/blob/master/components/upload/demo/ajax.md#Upload-props 
pages not found

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉给你带来了困扰，该链接可能已经失效。在这种情况下，你可以查看Ant Design 的 Upload 组件文档，该文档提供了`customRequest`的示例代码和API参数说明。这是链接：

https://ant.design/components/upload-cn/#components-upload-demo-ajax

另外，如果你需要查看已经发布的版本的Upload组件，可以在github上直接找到它，该组件的所有示例和主要特性都在其中。这是Github链接：

https://github.com/ant-design/ant-design/tree/master/components/upload

在这里你可以找到最新版本的Upload组件文档以及演示代码。如果你使用的是这个库，请参考该文档以解决你的问题。感谢你的理解和耐心。

**Comment by chenshuai2144** [comment]
你需要受控的处理下fileList的状态。

```
{
      uid: '1',
      name: 'xxx.png',
      status: 'uploading',
      url: 'http://www.baidu.com/xxx.png',
      percent: 33,
    },
```

 status: 'uploading',  是上传中，  status: 'done', 就是上传完成了
