### ISSUE TITLE
🧐[问题 | question] Using qiankun in antd v6?

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#10362]
I'm trying to use qiankun in ant design pro version 6, but it doesn't work, can you help?
我正在尝试在ant design pro 6 中使用乾坤，但是它不起作用，你能帮忙吗？

**Master config.ts**

```
  mfsu: false,
  qiankun: {
    master: {
      apps: [
        {
          name: 'app-child',
          entry: '//localhost:8001',
        }
      ]
    }
  }
```

**Master routes.ts**

```
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './User/Login',
      },
    ],
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      {
        path: '/admin',
        redirect: '/admin/sub-page',
      },
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        component: './Admin',
      },
    ],
  },
  { path: '/app-child', microApp: 'app-child', name: 'app1Name', },
  {
    name: 'list.table-list',
    icon: 'table',
    path: '/list',
    component: './TableList',
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    path: '*',
    layout: false,
    component: './404',
  },
];
```

**Slave config.ts**

```
  mfsu: false,
  qiankun: {
    slave: {}
  }
```

Slave routes.ts
```
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './User/Login',
      },
    ],
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      {
        path: '/admin',
        redirect: '/admin/sub-page',
      },
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        component: './Admin',
      },
    ],
  },
  {
    name: 'list.table-list',
    icon: 'table',
    path: '/list',
    component: './TableList',
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    path: '*',
    layout: false,
    component: './404',
  },
];
```

**Comment by xXAvoraXx** [comment]
@chenshuai2144 Due to lack of documentation, I couldn't find exactly what I was doing wrong.
由于缺乏文档，我无法确切地找到我做错了什么。

**Comment by mac-boss** [comment]
我也是这样配置的结果报错了

底座 `config/config.ts` 里添加了

```
qiankun: {
    master: {
      apps: [
        {
          name: 'cashier',
          entry: '//localhost:8001',
        }
      ],
    },
  },
```

`routes.ts` 里添加了

```
{
    name: 'cashier',
    path: '/cashier/ant-design-pro/*',
    microApp: 'cashier',
  },
```

子应用 `config/config.ts` 里添加了
```
 qiankun: {
    slave: {},
  },
```

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/1262247/218943286-33fbf3fb-2abc-41fd-a19b-df0ab63728fc.png">

**Comment by mac-boss** [comment]
> I'm trying to use qiankun in ant design pro version 6, but it doesn't work, can you help? 我正在尝试在ant design pro 6 中使用乾坤，但是它不起作用，你能帮忙吗？
> 
> **Master config.ts**
> 
> ```
>   mfsu: false,
>   qiankun: {
>     master: {
>       apps: [
>         {
>           name: 'app-child',
>           entry: '//localhost:8001',
>         }
>       ]
>     }
>   }
> ```
> 
> **Master routes.ts**
> 
> ```
> export default [
>   {
>     path: '/user',
>     layout: false,
>     routes: [
>       {
>         name: 'login',
>         path: '/user/login',
>         component: './User/Login',
>       },
>     ],
>   },
>   {
>     path: '/welcome',
>     name: 'welcome',
>     icon: 'smile',
>     component: './Welcome',
>   },
>   {
>     path: '/admin',
>     name: 'admin',
>     icon: 'crown',
>     access: 'canAdmin',
>     routes: [
>       {
>         path: '/admin',
>         redirect: '/admin/sub-page',
>       },
>       {
>         path: '/admin/sub-page',
>         name: 'sub-page',
>         component: './Admin',
>       },
>     ],
>   },
>   { path: '/app-child', microApp: 'app-child', name: 'app1Name', },
>   {
>     name: 'list.table-list',
>     icon: 'table',
>     path: '/list',
>     component: './TableList',
>   },
>   {
>     path: '/',
>     redirect: '/welcome',
>   },
>   {
>     path: '*',
>     layout: false,
>     component: './404',
>   },
> ];
> ```
> 
> **Slave config.ts**
> 
> ```
>   mfsu: false,
>   qiankun: {
>     slave: {}
>   }
> ```
> 
> Slave routes.ts
> 
> ```
> export default [
>   {
>     path: '/user',
>     layout: false,
>     routes: [
>       {
>         name: 'login',
>         path: '/user/login',
>         component: './User/Login',
>       },
>     ],
>   },
>   {
>     path: '/welcome',
>     name: 'welcome',
>     icon: 'smile',
>     component: './Welcome',
>   },
>   {
>     path: '/admin',
>     name: 'admin',
>     icon: 'crown',
>     access: 'canAdmin',
>     routes: [
>       {
>         path: '/admin',
>         redirect: '/admin/sub-page',
>       },
>       {
>         path: '/admin/sub-page',
>         name: 'sub-page',
>         component: './Admin',
>       },
>     ],
>   },
>   {
>     name: 'list.table-list',
>     icon: 'table',
>     path: '/list',
>     component: './TableList',
>   },
>   {
>     path: '/',
>     redirect: '/welcome',
>   },
>   {
>     path: '*',
>     layout: false,
>     component: './404',
>   },
> ];
> ```

我试了，可以了。
在 master 项目里 config/config.ts 里 配置`mfsu: false,`

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈，如果你的问题已经得到解决，那很好，如果在使用过程中有其他问题，请随时联系。
