### ISSUE TITLE
🐛 [BUG]小屏H5下，没办法通过点击阴影关闭抽屉

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#10379]
![image](https://user-images.githubusercontent.com/12421552/203067338-90c1f9cb-9d73-47ec-84ed-9140c1e01fa0.png)

新建的项目。没办法通过点击阴影关闭抽屉
Chrome，版本 107.0.5304.88（正式版本） （64 位）

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题是由于抽屉展示的元素没有被关闭而导致的。你可以通过修改代码解决这个问题。以下是可能的解决方案：

1. 给遮罩添加点击事件，点击时调用关闭抽屉的方法。

```js
function Drawer({ isOpen, children, onClose }) {
  ...

  function handleClose() {
    if (isOpen && onClose) {
      onClose();
    }
  }

  return (
    <>
      {isOpen && (
        <div className="drawer-mask" onClick={handleClose}>
          <div className="drawer" style={{ transform: isOpen ? 'translateX(0%)' : 'translateX(-100%)' }}>
            {children}
          </div>
        </div>
      )}
    </>
  )
}
```

2. 使用 `react-modal` 组件，它提供了关闭模态框的方法。

```jsx
import ReactModal from 'react-modal';

function Drawer({ isOpen, children, onClose }) {
  ...

  return (
    <ReactModal
      isOpen={isOpen}
      onRequestClose={onClose}
      className="drawer"
      overlayClassName="drawer-mask"
    >
      {children}
    </ReactModal>
  )
}
```

需要注意的是，使用 `react-modal` 时需要在根组件中调用 `ReactModal.setAppElement` 来指定模态框所在的 DOM 元素，以确保模态框能正常展示。例如：

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import ReactModal from 'react-modal';
import App from './App';

ReactModal.setAppElement('#root');

ReactDOM.render(<App />, document.getElementById('root'));
``` 

希望这些解决方案能帮助你解决问题。如果有任何疑问，请随时问我。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


实际上的情况是，点击阴影关闭抽屉后，浮层会短暂关闭，但是又会再次弹出。

问题的解决方案如下：

1. 首先，需要确认抽屉组件的相关代码是否正确。检查抽屉组件的实现逻辑，确保点击阴影关闭抽屉的功能已经正确实现。

2. 如果抽屉组件的代码没有问题，那么可能是在使用抽屉组件的地方出现了错误。检查调用抽屉组件的代码，确保没有重复触发打开抽屉的逻辑。

3. 如果以上两点都没有问题，那么可能是浏览器兼容性导致的问题。尝试在其他浏览器中打开页面，查看是否同样存在该问题。

4. 如果问题在其他浏览器中也存在，那么可能是抽屉组件本身的问题。可以尝试查找抽屉组件的官方文档或社区中是否有相关的 bug 报告或解决方案。

5. 如果没有找到解决方案，可以考虑使用其他类似的组件替换抽屉组件，或者自己实现一个类似的功能。

6. 最后，如果以上方法都没有解决问题，可以尝试对页面进行调试，使用浏览器的开发者工具查看页面的 console 控制台和网络请求，以便更详细地了解问题所在，并尝试解决。
