### ISSUE TITLE
🐛 [BUG] Standalone Feature NPM package outdated dependencies

### ISSUE THREAD

**Issue by DsMaccy** [ant-design/ant-design-pro#10378]
### 🐛 bug 描述
Not entirely sure if this would be considered a feature gap, a bug, or just me doing something silly, but here's the basic situation:
I am currently using antd as defined in my package.json as copied below:
```
  ...
  "dependencies": {
    ...
    "antd": "^4.23.1",
```

I am also attempting to use the Login page as defined here: https://v2-pro.ant.design/components/login.

When looking at github, it seems that the latest release version for this repository is 6.0.0 beta, but when attempting to download the latest version off of npm, I get a much older version.  Npm attempts to download version 2.3.2 of ant-design-pro (`ant-design-pro@2.3.2`) which has an antd dependency 3.0.1 (`antd@"^3.0.1"`).  See *Actual results* Section for npm error output

### 📷 复现步骤 | Recurrence steps
1. Repository has antd version 4.23+.  
2. Attempting to run the following command:
`npm install ant-design-pro@latest --save`
as defined in this webpage: https://v2-pro.ant.design/docs/use-components-alone

### 🏞 期望结果 | Expected results
Expected to be able to download the latest dependency (either the 6.0.0 beta or the latest of major version 5

### 🏞 实际结果 | Actual results
(NOTE: For this section header, I tried to use google translate.  Please forgive if the translation is off)
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: {redacted}
npm ERR! Found: antd@4.24.3
npm ERR! node_modules/antd
npm ERR!   antd@"^4.23.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer antd@"^3.0.1" from ant-design-pro@2.3.2
npm ERR! node_modules/ant-design-pro
npm ERR!   ant-design-pro@"2.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See {redacted} for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     {redacted}\2022-11-20T23_16_44_038Z-debug.log
```

### 💻 复现代码 | Recurrence code
Not Applicable

### © 版本信息 | Version Information
OS: Windows 10
Package Manager: `npm` version `8.1.0`

### 🚑 其他信息 | Other Information
Attempted download date: 11/20/2022 3:13pm (Pacific Standard Time in United States)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好！感谢您的反馈。

根据您提供的信息，似乎是因为 `ant-design-pro` 的版本太旧，无法与您的 `antd` 版本兼容，所以出现了依赖冲突的问题。您可以尝试在安装 `ant-design-pro` 的时候加上 `--legacy-peer-deps` 这个选项，来允许旧版本的依赖项与新版本兼容，以解决这个问题：

```
npm install ant-design-pro@latest --save --legacy-peer-deps
```

另外，您也可以尝试手动升级依赖项来解决这个问题。可以先升级 `antd` 到最新版本，然后更新 `ant-design-pro` 的依赖项信息，以确保它们不会再出现版本冲突。升级依赖项也是一个非常好的做法，可以避免一些潜在的安全漏洞和其他问题。

为了更好的解决这个问题，您可以参考以下步骤：

1. 尝试运行以下命令，将 `antd` 升级到最新版本： 
```
npm install antd@latest --save 
```

2. 更新 `ant-design-pro` 的依赖项，将它们与你刚刚升级的 `antd` 版本匹配。
```
npm install ant-design-pro@latest --save
```

希望这个解决方案可以帮助您解决这个问题。如果您还有其他问题，请随时提问！
