### ISSUE TITLE
求教，@connect 是如何指定model进行关联的呢？

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-design-pro#1037]
@connect(({ list, loading }) => ({
  list,
  loading: loading.models.list,
}))
这个list，loading 是来自哪个model？
谢谢~

**Comment by yutingzhao1991** [comment]
loading 是 dva-loading 这个 dva 的插件内置的 model，可以看看 dva 相关文档。

**Comment by ddcat1115** [comment]
https://github.com/dvajs/dva

**Comment by ybning** [comment]
@wuyongdec  [https://github.com/sorrycc/blog/issues/62](https://github.com/sorrycc/blog/issues/62)

**Comment by zhaoqize** [comment]
这里的 `list ` 来自于 `model` 中的 `namespace`，且包裹了 `state` 对象
