### ISSUE TITLE
按照Get Start 创建的项目，6.0.0 Beta1 版本，登陆之后会报错，另外还有一个overlay的问题 🐛 [BUG]

### ISSUE THREAD

**Issue by cielu** [ant-design/ant-design-pro#10374]
创建新项目，目前是这两个问题。

这里也有人在艾特你，让你快看。

https://github.com/ant-design/pro-components/issues/6162

<img width="941" alt="image" src="https://user-images.githubusercontent.com/13715811/202422200-860ffde9-5ebc-41d5-94f9-e47bd0762b51.png">

<img width="910" alt="image" src="https://user-images.githubusercontent.com/13715811/202422100-f8590e18-a9ce-476d-ba3a-74713a61bce7.png">

**Comment by cielu** [comment]
我啥都没动，就是创建项目然后登陆。你打开控制台一眼就可以看到了

**Comment by cielu** [comment]
还有个问题，就是用着用着就挂了，断开连接了。。

**Comment by sorryjs** [comment]
> 我啥都没动，就是创建项目然后登陆。你打开控制台一眼就可以看到了

一样的问题

**Comment by zzzloving** [comment]
蹲个修复

**Comment by yuyihan666** [comment]
+1

**Comment by Capricair** [comment]
破案了
`/src/components/RightContent/AvatarDropdown.tsx`
里面`HeaderDropdown`的`overlay`改成`menu`
其他地方有用overlay的改成menu就行

**Comment by hfpp2012copy** [comment]
看我这个全部清掉 https://www.qiuzhi99.com/playlists/antdpro-prisma.html

**Comment by cielu** [comment]
> 看我这个全部清掉 https://www.qiuzhi99.com/playlists/antdpro-prisma.html

去你大爷的广告

**Comment by hfpp2012copy** [comment]
> > 看我这个全部清掉 https://www.qiuzhi99.com/playlists/antdpro-prisma.html
> 
> 去你大爷的广告

这么激动干啥，希望你以后被善待

**Comment by tomseanmy** [comment]
目前我想到的办法：
关于【Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.】这个问题，可以修改../src/components/RightContent/AvatarDropdown.tsx中的<HeaderDropdown>组件，用menu属性替换掉overlay属性的值，以及去掉HeaderDropdownProps中的overlay属性。

关于【Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.】这个警告，可以使用setTimeout()函数包裹history.push()解决，或者不在onFinish函数中直接调用history.push()。

**Comment by hyzx86** [comment]
> 目前我的解决办法是： 关于【Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.】这个问题，可以修改../src/components/RightContent/AvatarDropdown.tsx中的组件，用menu属性替换掉overlay属性的值，以及去掉HeaderDropdownProps中的overlay属性。
> 
> 关于【Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.】这个警告，可以使用setTimeout()函数包裹history.push()解决，或者不在onFinish函数中直接调用history.push()。

大拿能提个PR不？[搓手]😘

**Comment by athxx** [comment]
烦閪死了整天改语法, 一天一个语法, 弃用了

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，这里是两个问题，一个是在使用 ant-design/pro-components 6.0.0 Beta1 版本时登录后报错，另一个是 overlay 的问题。

针对登录报错的问题，可以按照下面的步骤来解决：

1. 首先，确认是否使用了正确的依赖版本。ant-design/pro-components 6.0.0 Beta1 可能还存在一些 bug，所以可以先尝试降级到稳定版本，例如 5.x 版本。

2. 检查你的登录逻辑，特别是与后端 API 的交互。确认是否正确地处理了登录请求和返回的数据。可以使用开发者工具查看网络请求和响应，确保登录接口正常工作。

3. 如果问题仍然存在，可以参考上述 GitHub Issue 链接中的讨论，看看是否有其他人报告了相似的问题，并且是否有解决方案或临时补丁可用。你也可以在该 Issue 中提出你遇到的问题，与其他人进行讨论。

针对 overlay 的问题，可以按照下面的步骤来解决：

1. 确认是否使用了正确的依赖版本。overlay 功能通常由 UI 组件库提供，例如 antd 的 Modal、Popover 等组件。确保你使用的是最新版本的 antd，并且没有与其他库产生冲突。

2. 检查你的代码中是否正确使用了 overlay 相关的组件。例如，在使用 Modal 组件时，确保正确传递了相关的 props，例如 visible 和 onOk/onCancel 等。可以参考 antd 官方文档中的示例和 API 文档。

3. 如果问题仍然存在，可以在 GitHub 上搜索相关问题，并查看是否有人遇到了相似的问题，并且是否有解决方案可用。你可以在 antd 的 GitHub 仓库中提出你遇到的问题。

总的来说，解决这些问题的关键是确保使用了正确的依赖版本，并且检查你
