### ISSUE TITLE
请问什么时候上正式的6版本

### ISSUE THREAD

**Issue by 13992094832** [ant-design/ant-design-pro#10380]

**Comment by huang-xiong** [comment]
I have the same question and hope to answer it. thanks.

**Comment by MUCZ** [comment]
Me wondering too, will the Ant Design 5.0 be integrated?

**Comment by yasz** [comment]
+1

**Comment by hfpp2012copy** [comment]
虽说是 beta 版本，已在用

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢分享！Ant Design 6.0 目前已经发布了 Beta 版本，但正式版发布时间还没有确定。根据官方的发布计划，Ant Design 6.0 的目标是在 2021 年中下旬发布正式版，如有变动会在官方社区和 GitHub 上发布相关信息。对于 Ant Design 的升级，你可以关注官方文档和社区发布的消息，及时了解升级细节和注意事项。

**Comment by RainingNight** [comment]
凉了？
