### ISSUE TITLE
🐛 [BUG] 使用less文档说明页面有个链接失效，需更新

### ISSUE THREAD

**Issue by ByYogi** [ant-design/ant-design-pro#10389]
Antd 相关issue： https://github.com/ant-design/ant-design/issues/38673
相关提交： https://github.com/ant-design/ant-design/commit/90a5a9f58393d1ba90f7118e99e70b165f503643
相关页面：https://pro.ant.design/docs/less
![LinkFailedEntry](https://user-images.githubusercontent.com/111735598/203894274-2a056192-d50a-408e-933e-f3438c8571b0.png)
![LinkFailed](https://user-images.githubusercontent.com/111735598/203894022-0b514a8c-5334-4337-84fe-cab8faae01ea.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢您的反馈，我们将及时处理此问题。为了帮助您解决该问题，您可以直接查看上文提供的提交链接，在其中找到以下代码片段：

```diff
- <a href="http://ant.design/components/steps-cn/#Step-Props" target="_blank">Antd Steps</a>
+ <a href="http://ant.design/components/steps-cn#Step-Props" target="_blank">Antd Steps</a>
```

该提交修复了链接中的一个错误字符，从而解决了链接失效的问题。您可以将这个修改应用到您的项目中，以使链接在您的项目中正常工作。

另外，如果您对Antd的使用有任何疑问，您可以查看Antd文档中有关steps组件的内容，以了解其使用方式：

https://ant.design/components/steps-cn/

希望以上内容能够解决您在使用过程中遇到的问题。如果您还有其他问题或需要进一步的帮助，欢迎继续与我们联系。
