### ISSUE TITLE
🐛 [BUG]每个TS,JS文件都会出现 Parsing error: Cannot find module '@babel/plugin-proposal-decorators' 文件标红，有没有大佬知道怎么解决？

### ISSUE THREAD

**Issue by sorryjs** [ant-design/ant-design-pro#10387]
![image](https://user-images.githubusercontent.com/23518734/203705515-631ade97-a772-47de-bfaf-2d1e44a4def3.png)
![image](https://user-images.githubusercontent.com/23518734/203706093-a7f6a2da-abd2-406a-93cc-1bc5e410f505.png)

文件标红，有没有大佬知道怎么解决？ 
看着难受，但是可以正常使用， npm i  @babel/plugin-proposal-decorators ,
下载了，也不好使，继续警告！！！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这似乎是 babel 的配置问题导致的，因为@babel/plugin-proposal-decorators 是 babel 的一个插件，用于支持装饰器语法。

你可以尝试以下方法：

1. 确认是否安装了@babel/core、@babel/preset-env、@babel/plugin-proposal-decorators、@babel/plugin-proposal-class-properties等相关的 babel 插件，在 package.json 文件中查看对应的版本是否正确。
    
2. 检查 babel 配置文件 .babelrc 或者 babel.config.js 中是否正确配置了插件，参考以下示例：

```json
{
  "presets": ["@babel/preset-env"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-proposal-class-properties"
  ]
}
```

关于 babel 的更多配置，可以参考官方文档： https://babeljs.io/docs/en/configuration

3. 如果以上方法都没解决问题，可以尝试删除 node_modules 文件夹并重新执行 npm install 命令。

希望以上方法能够帮到你，如果还有问题可以提供更多的详细信息给我。

**Comment by RRRRRRRRen** [comment]
文件夹层级不对，比如vscode打开的文件夹下有多个项目。直接从子项目的根目录启动vscode就可以了。
