### ISSUE TITLE
🧐[问题 | question] all-blocks 分支的代码 如何升级ant5   直接安装报错

### ISSUE THREAD

**Issue by AndrewLiuNet** [ant-design/ant-design-pro#10382]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉，您提供的问题缺少关键信息，无法进行回答。请提供更具体的问题描述、示例代码和其他相关信息。如果您的问题与 React 前端相关，请详细描述问题，并提供相关代码示例。谢谢！

**Comment by chenshuai2144** [comment]
更新一下，全部更新了
