### ISSUE TITLE
🧐[问题 | question] Protable reload 无法更新列表项目

### ISSUE THREAD

**Issue by iselt** [ant-design/ant-design-pro#10386]
### 🧐 问题描述 | Problem description

使用 ref.current?.reload，列表下面的总数成功更新，列表项目没有变化，

### 💻 示例代码 | Sample code

```typescript
//export default TableList
const TableList: React.FC = () => {
    const ref = useRef<ActionType>();
    return(
        <PageContainer>
            <ProTable<API.RuleListItem>
                actionRef={ref}
                request={async (
                //   params: {
                //     pageSize?: number | undefined;
                //     current?: number | undefined;
                //     keyword?: string | undefined;
                //   },
                //   sort,
                //   filter,
                ) => {return Promise.resolve(await load_items());}
                }
            >
...

//load_items()
return ({
    success: true,
    data: tableListDataSource, //type: API.RuleListItem[]
    total: tableListDataSource.length,
  })
```

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/101086473/203665061-765b6309-87f1-47e4-9930-1a1320de2bff.png)
reload后total可以更新，但data没有变化

OS: Windows 11

Node：v16.18.1

浏览器 | browser：Edge

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

看起来是数据没有更新，根据代码示例可以发现是 `load_items` 返回的数据没有更新，导致列表数据没有变化。可以将 `load_items` 改为一个状态，然后在需要更新的时候修改该状态并重新渲染组件。

```typescript
const [tableData, setTableData] = useState<API.RuleListItem[]>([]);

const loadItems = async () => {
  const res = await load_items();
  setTableData(res.data);
  return {
    data: res.data,
    success: res.success,
    total: res.total,
  };
};

return (
    <PageContainer>
      <ProTable<API.RuleListItem>
        actionRef={ref}
        request={async () => loadItems()}
        dataSource={tableData}
        columns={columns}
      />
    </PageContainer>
);
```

另外，`react` 的 `useState` 钩子与 `Protable` 的 `request` 方法有些冲突，可能会导致数据多次请求。所以可以将 `loadItems` 函数通过 `useCallback` 钩子进行优化，使组件中先前的状态和该钩子的引用保持一致。

```typescript
const loadItems = useCallback(async () => {
  const res = await load_items();
  setTableData(res.data);
  return {
    data: res.data,
    success: res.success,
    total: res.total,
  };
}, []);

return (
    <PageContainer>
      <ProTable<API.RuleListItem>
        actionRef={ref}
        request={() => loadItems()}
        dataSource={tableData}
        columns={columns}
      />
    </PageContainer>
);
```

另外，如果你需要自定义表格数据变化的回调函数，可以使用 `onChange` 属性进行配置，参考文档：[onChange | Protable](https://procomponents.ant.design/components/table/?category=v2-value#onChange)。
