### ISSUE TITLE
🐛 [BUG] Layout token is not loaded while on mobile screen.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#10392]
### 🐛 bug 描述

Layout token is not loaded while on mobile screen.

### 🏞 期望结果 | Expected results

The token defined in the layout must also be valid on the mobile screen.

### 💻 复现代码 | Recurrence code

![token](https://user-images.githubusercontent.com/6988989/203997737-c2676c53-0325-4555-89cf-de9a841db46f.PNG)
![notwork](https://user-images.githubusercontent.com/6988989/203997743-ecb394ce-794c-44dc-8c3b-254ca3d9605f.PNG)

### © 版本信息

- Ant Design Pro 版本: 4.23.3
- umi 版本: 4.0.24
- 浏览器环境: Chrome
- 开发环境: Windows

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案

1. 首先确认 Layout 组件是否被正确引入，确保代码中没有拼写错误或路径错误。

2. 如果 Layout 组件引入无误，检查代码中与移动端布局相关的部分，尤其是媒体查询的部分，看是否有相应的代码来适配移动端。

3. 如果仍无法解决问题，可以考虑在 `package.json` 文件中添加 `postcss-px-to-viewport` 插件，并对相应的 CSS 属性进行适配处理。

```json
"postcss": {
  "plugins": {
    "postcss-px-to-viewport": {
      "viewportWidth": 375, // 视窗的宽度，对应移动端设计稿的宽度，一般为750
      "viewportHeight": 667, // 视窗的高度，对应移动端设计稿的高度，一般也为750
      "unitPrecision": 3, // 转换后的精度，即小数点位数
      "viewportUnit": "vw", // 转换成的视窗单位
      "selectorBlackList": [".ignore", ".hairlines"], // 不转换的类名列表
      "minPixelValue": 1, // 小于等于 '1px' 不转换为视窗单位，可以设置为 '0.5px' 等
      "mediaQuery": false // 允许在媒体查询中转换 px
    }
  }
},
```


### 参考文档

- [Ant Design Pro 官方文档](https://pro.ant.design/)
- [postcss-px-to-viewport 官方文档](https://www.npmjs.com/package/postcss-px-to-viewport)

**Comment by chenshuai2144** [comment]
修复了，更新下依赖
