### ISSUE TITLE
🧐[问题描述] ant-design-pro-v4版本，启动报错405

### ISSUE THREAD

**Issue by dossweet** [ant-design/ant-design-pro#10395]
### 🧐 问题描述：ant-design-pro-v4版本，启动报错405

从github上拉取了ant-design-pro V4版本的代码（即@antd4分支的代码）。
![image](https://user-images.githubusercontent.com/38655923/204138068-cb4a6c33-c192-4560-85bd-3c6142893dce.png)

运行npm run dev时，浏览器里默认跳转至登录页面，点击登录按钮，报错405：
![image](https://user-images.githubusercontent.com/38655923/204137826-583f7ae2-e92c-4026-b6e6-906c907c239f.png)
运行npm run start，浏览器里打开网站报错如下：
![image](https://user-images.githubusercontent.com/38655923/204137922-c333eee5-fbc2-4f12-a265-86ae6bca23c4.png)
package.json文件里启动项目命令如下：
![image](https://user-images.githubusercontent.com/38655923/204137948-f5536e2f-bfea-4dad-9cc1-657395855d40.png)
拉下来的代码和github里的v4版本的源码完全一致。不知道什么原因导致的这个问题。

### 🚑 其他信息 | Other information

OS: win10

Node：v16.13.0

浏览器 | browser：Chrome，版本 107.0.5304.122（正式版本） （64 位）

**Comment by dossweet** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🧐[问题描述] ant-design-pro-v4版本，启动报错405 #10394](https://github.com/ant-design/ant-design-pro/issues/10394)][100%]

这个issue也是我提的，因为写法不规范给我自动close了。。。

**Comment by dossweet** [comment]
有没有人能来解答一下呀

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的信息，出现 405 错误通常是因为请求的方法不被允许，一般情况下是因为请求的方法和服务端的 API 不匹配。

针对你的问题，首先可以在线上问题出现的那个页面上，在浏览器的开发者工具中查看一下请求的具体 URL 和发送的请求方法。如果能看到请求头信息，最好同时截图，方便定位问题。

然后进入你本地项目的对应页面，检查发送的请求是否和在线上出错页面时的请求一致，这里需要特别注意 URL 的前缀是否正确，比如可能存在 `/api` 或 `/v1` 等前缀。

如果以上方法都无法解决问题，可以尝试查看一下服务端的代码，看是否有一些限制请求方法的设置。 

最后，你也可以在 ant-design-pro 的 GitHub issue 中提出你的问题，这样可能会更容易得到相关开发者的帮助。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题一：发请求时报错：405 Method not allowed

解决方案：这个错误提示表明服务器不支持发起的请求方法。造成这个问题的原因可能是请求方法不正确或者服务器没有正确地配置支持该请求方法。

1. 确保你的代码中的请求方法是否正确。比如，对于表单提交，应该使用POST方法而不是GET方法。你可以检查代码中的请求方法是否正确，并进行修正。

2. 检查服务器配置，确保服务器已经正确地配置支持所使用的请求方法。有些服务器可能会限制某些请求方法的访问，需要在服务器配置中进行相应的修改。如果你无法直接修改服务器配置，可以联系服务器管理员或者运维人员进行协助。

3. 如果你使用的是代理服务器，也需要检查代理服务器的配置，确保代理服务器正确地转发请求，并且没有对该请求方法进行限制。

4. 如果以上方法都没有解决问题，你还可以尝试使用其他的请求库或者工具发送请求，看是否能够正常地发送请求。

问题二：运行npm run start时，网站报错

解决方案：这个错误提示表明项目在启动过程中遇到了问题。可能是项目配置不正确或者依赖包没有正确安装。

1. 确保你已经正确安装了项目的依赖包。可以使用`npm install`命令来确保依赖包已经正确安装。

2. 检查项目的配置文件，比如`.env`文件或者`config`文件夹下的配置文件是否正确。可以尝试重新配置这些文件，并重启项目。

3. 如果错误提示中包含具体的错误信息，可以根据错误信息来查找解决方案。可以在搜索引擎或者项目的官方文档中查找错误信息相关的解决方法。

4. 如果以上方法都没有解决问题，你可以尝试重新拉取项目的代码，确保代码没有问题。可以尝试在其他环境中运行项目，看是否能够正常运行。

总结：以上是针对问题描述的一般解决方案，具体的解决方法可能需要根据具体情况进行调整。如果无法解决问题，建议查找相关的文档或者寻求相关领域的专业人士的帮助。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题一：发请求时报错：405 Method not allowed

解决方案：这个错误提示表明服务器不支持发起的请求方法。造成这个问题的原因可能是请求方法不正确或者服务器没有正确地配置支持该请求方法。

1. 确保你的代码中的请求方法是否正确。比如，对于表单提交，应该使用POST方法而不是GET方法。你可以检查代码中的请求方法是否正确，并进行修正。

2. 检查服务器配置，确保服务器已经正确地配置支持所使用的请求方法。有些服务器可能会限制某些请求方法的访问，需要在服务器配置中进行相应的修改。如果你无法直接修改服务器配置，可以联系服务器管理员或者运维人员进行协助。

3. 如果你使用的是代理服务器，也需要检查代理服务器的配置，确保代理服务器正确地转发请求，并且没有对该请求方法进行限制。

4. 如果以上方法都没有解决问题，你还可以尝试使用其他的请求库或者工具发送请求，看是否能够正常地发送请求。

问题二：运行npm run start时，网站报错

解决方案：这个错误提示表明项目在启动过程中遇到了问题。可能是项目配置不正确或者依赖包没有正确安装。

1. 确保你已经正确安装了项目的依赖包。可以使用`npm install`命令来确保依赖包已经正确安装。

2. 检查项目的配置文件，比如`.env`文件或者`config`文件夹下的配置文件是否正确。可以尝试重新配置这些文件，并重启项目。

3. 如果错误提示中包含具体的错误信息，可以根据错误信息来查找解决方案。可以在搜索引擎或者项目的官方文档中查找错误信息相关的解决方法。

4. 如果以上方法都没有解决问题，你可以尝试重新拉取项目的代码，确保代码没有问题。可以尝试在其他环境中运行项目，看是否能够正常运行。

总结：以上是针对问题描述的一般解决方案，具体的解决方法可能需要根据具体情况进行调整。如果无法解决问题，建议查找相关的文档或者寻求相关领域的专业人士的帮助。
