### ISSUE TITLE
🐛 [BUG]配置栏的页脚，关闭之后，再打开就没反应了

### ISSUE THREAD

**Issue by NARUTOyuyang** [ant-design/ant-design-pro#10399]
### 📷 复现步骤 | Recurrence steps
配置栏的页脚，关闭之后，再打开就没反应了，就无法显示出来

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22002078/204414501-9811ac0d-ea86-43f0-ad64-371405d9b6e5.png)

**Comment by hfpp2012copy** [comment]
为什么不用第五版本 https://www.qiuzhi99.com/movies/umi-v3-ant-design-pro-v5-2-from-scratch-enterprise-development-real-combat-video-tutorial-01-start-real-combat

**Comment by NARUTOyuyang** [comment]
> 为什么不用第五版本 https://www.qiuzhi99.com/movies/umi-v3-ant-design-pro-v5-2-from-scratch-enterprise-development-real-combat-video-tutorial-01-start-real-combat

你发的是啥玩意?我用的是官网的 demo

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我可能发错了链接。UMI 官方最新版本是 4，而 Ant Design Pro 正在使用 UMI 3，因此版本不兼容。另外，每个项目都有自己的需求和限制，选择适合自己的版本也是很重要的。

**Comment by chenshuai2144** [comment]
清空一来重新安装一下吧
