### ISSUE TITLE
🧐[umi4下自带的proLayout暗黑模式怎么开启]

### ISSUE THREAD

**Issue by JinLuhuan** [ant-design/ant-design-pro#10398]
### 🧐 问题描述 | Problem description

固定使用暗黑模式，不需要动态切换
antd的组件都生效了，proLayout、PageContainer这些组件不生效

### 💻 示例代码 | Sample code

`import { defineConfig } from '@umijs/max';
import routes from './routes';
import darkTheme from '@ant-design/dark-theme';
import theme from './theme';

export default defineConfig({
  antd: {
    dark: true, // antd的组件都生效了，proLayout、PageContainer这些组件不生效
  },
  theme: {
    ...darkTheme,
    ...theme,
  },
  routes,
});
`

**Comment by kokman** [comment]
The same problem also happened to me.

**Comment by yangjun2216** [comment]
请问楼主这个问题解决了吗

**Comment by zjfresh** [comment]
官方应该是用 dark reader 加的自定义css，可以自己对相应的 .class 加一下 bg-color 和border-color, color，工作量不大

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对于umi4.x中自带的proLayout暗黑模式的问题，可以通过下面的方式来解决。

首先，在config/config.js中可以设置antd的全局暗黑模式，配置如下：

```
export default {
  //...
  antd: {
    dark: true
  },
}
```

然后，如果是proLayout和PageContainer这样的组件没有生效，可以通过自定义CSS样式来解决。在index.html中添加一个新的style标签，在里面添加对应class名的CSS样式，例如：

```
<style>
  .pro-global-header {
    background-color: #212121; /* 设置header背景颜色 */
    border-color: #333; /* 设置header边框颜色 */
    color: #fff; /* 设置header里文本颜色 */
  }
</style>
```

其中，`.pro-global-header`是proLayout中头部的class名，可以根据需要替换成其他class名。通过添加对应的CSS样式，可以自定义proLayout的暗黑模式样式。
