### ISSUE TITLE
🐛 [BUG] Layout menu does not close when on mobile screen.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#10391]
### 🐛 bug 描述

Layout menu doesn't close when mobile is on screen size. There is no maskClosable property.

### 🏞 期望结果 | Expected results

The maskClosable property must be present.

### 💻 复现代码 | Recurrence code

![Capture111](https://user-images.githubusercontent.com/6988989/203997214-e4658f5a-b4ad-46c0-ac7a-731e43247eec.PNG)

### © 版本信息

- Ant Design Pro 版本: 4.23.3
- umi 版本: 4.0.24
- 浏览器环境: Chrome
- 开发环境 Windows

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


在 Ant Design Pro 中，Menu 组件的 maskClosable 属性是用来控制点击遮罩层是否关闭侧边菜单的。默认情况下，只有在非移动端（屏幕宽度大于 768px）才会开启该属性。

针对你提出的问题，你可以尝试在你的代码中手动添加该属性，以解决移动端点击遮罩层菜单不关闭的问题。具体操作如下：

1. 打开 src/layouts/BasicLayout.tsx 文件。

2. 导入 Menu 组件和 ConnectState 类型。

```tsx
import { Menu } from 'antd';
import type { ConnectState } from '@/models/connect';
```

3. 找到 Menu 组件的调用位置，并在 Menu 组件上添加 maskClosable 属性：

```tsx
<Menu
  ...
  maskClosable={true} // 添加 maskClosable 属性
>
  ...
</Menu>
```

4. 在 BasicLayout 组件的类型定义中，添加 ConnectState 类型：

```tsx
interface BasicLayoutProps extends RouteComponentProps, ConnectState {
  ...
}
```

5. 重新启动项目，查看侧边菜单在移动端是否能够正常关闭。

注：在 Ant Design Pro 官方 GitHub 仓库中也有针对此问题的 issue 讨论，你也可以查看其中的解决方案进行参考。

参考文档：

- Ant Design Pro 官方文档：https://pro.ant.design/components/layout-cn/
