### ISSUE TITLE
执行打包命令后，生成单个index.js文件体积2M多，会不会太大？

### ISSUE THREAD

**Issue by zhaoze1211** [ant-design/ant-design-pro#1039]
执行打包命令后，生成单个index.js文件体积2M多，会不会太大？

**Comment by chenshuai2144** [comment]
可以开个代码分割。
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD
