### ISSUE TITLE
🐛 [BUG] SettingDrawer is not hidden in production environment.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#10393]
SettingDrawer is not hidden in production environment.

```
    childrenRender: (children, props) => {
      // if (initialState?.loading) return <PageLoading />;
      return (
        <>
          {children}
          {!props.location?.pathname?.includes('/login') && (
            <SettingDrawer
              disableUrlParams
              enableDarkTheme
              settings={initialState?.settings}
              onSettingChange={(settings) => {
                setInitialState((preInitialState) => ({
                  ...preInitialState,
                  settings,
                }));
              }}
              themeOnly={true}
              prefixCls="custom"
            />
          )}
        </>
      );
    },
```

Version: ANT Design PRO V5
Package
    "@ant-design/pro-components": "^2.3.13",
    "antd": "^4.23.3",

Dependency
    "@ant-design/pro-cli": "^2.1.0",

**Comment by xXAvoraXx** [comment]
If you want to hide the settingdrawer, follow the instructions below.

```
              <SettingDrawer
                disableUrlParams
                enableDarkTheme
                settings={initialState?.settings}
                onSettingChange={(settings) => {
                  setInitialState((preInitialState) => ({
                    ...preInitialState,
                    settings,
                  }));
                }}
                prefixCls="customName"
                themeOnly
                hideCopyButton
                hideHintAlert
              />
```

Paste the code below into the global.less file.

```
.customName-setting-drawer-handle {
  visibility: hidden;
}
```

**Comment by gaojunxin** [comment]
我也遇到同样的问题，是否可以配置话处理这个问题。

**Comment by gaojunxin** [comment]
我也遇到同样的问题，是否可以配置话处理这个问题。

**Comment by xXAvoraXx** [comment]
> 我也遇到同样的问题，是否可以配置话处理这个问题。

I couldn't find any other solution. This seems to be the best solution for now.
我找不到任何其他解决方案。 这似乎是目前最好的解决方案。

**Comment by greenking19** [comment]
Me too

**Comment by xXAvoraXx** [comment]
> Me too

https://github.com/ant-design/ant-design-pro/issues/10393#issuecomment-1331353629

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对于这个问题，有一些可能的解决方案。

1. 升级 Ant Design Pro 版本：尝试升级到最新的版本，可能会修复这个问题。你可以在这里查看最新的版本和版本更新信息：https://github.com/ant-design/ant-design-pro/releases

2. 手动更新 SettingDrawer 样式：如果升级版本并不能解决问题，你可以手动更新 SettingDrawer 的样式。在你的全局样式文件中添加以下代码：

```css
.custom-setting-drawer-handle {
  display: none;
}
```

这会将 SettingDrawer 的手柄隐藏起来。

3. 检查你的代码：检查你的代码，特别是与 SettingDrawer 相关的部分，看看有没有可能出问题的地方。可能有一些代码错误或不完整，导致 SettingDrawer 不能正确地隐藏。

希望这些解决方案可以帮助你解决这个问题。如果仍然无法解决，请提供更多具体的信息，以便更好地帮助你解决问题。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题：SettingDrawer在生产环境中无法隐藏。

解决方案如下：

1. 在`src/app.tsx`文件中找到`childrenRender`函数，并注释掉`return <PageLoading />`的代码。这样可以确保加载完成后不会显示加载页面。

2. 在`return`语句中，判断当前页面是否为登录页面，如果不是，则渲染SettingDrawer组件。

3. 在SettingDrawer组件中，将`disableUrlParams`和`themeOnly`属性移除。

最终的代码如下：

```tsx | pure
childrenRender: (children, props) => {
  // if (initialState?.loading) return <PageLoading />;
  return (
    <>
      {children}
      {!props.location?.pathname?.includes('/login') && (
        <SettingDrawer
          enableDarkTheme
          settings={initialState?.settings}
          onSettingChange={(settings) => {
            setInitialState((preInitialState) => ({
              ...preInitialState,
              settings,
            }));
          }}
        />
      )}
    </>
  );
},
```

这样就可以在生产环境中隐藏SettingDrawer组件了。
