### ISSUE TITLE
🐛 [BUG] V6 config.ts theme 配置无效

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#10413]
### 🐛 bug 描述
````
theme: {
    // 如果不想要 configProvide 动态设置主题需要把这个设置为 default
    // 只有设置为 variable， 才能使用 configProvide 动态设置主色调
    'root-entry-name': 'variable',
    token: {
      colorTextDisabled: "#000"
    }
  },
````

**Comment by hihuangwei** [comment]
@chenshuai2144

**Comment by beautytea8** [comment]
同问，确实无效

**Comment by beautytea8** [comment]
@hihuangwei  后面你怎么解决的？

**Comment by hihuangwei** [comment]
@beautytea8 只能暂时使用局部应用

**Comment by beautytea8** [comment]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/13965190/208249268-bab4c955-cec1-4977-8e94-abace4875d68.png">
目前这种方式可以先解决问题

**Comment by chenshuai2144** [comment]
在 umi 跟踪吧，现在换了cssinjs 还没支持的很好。
推荐大家使用 configProvide 来修改，体验好很多

**Comment by hihuangwei** [comment]
> 在 umi 跟踪吧，现在换了cssinjs 还没支持的很好。 推荐大家使用 configProvide 来修改，体验好很多

局部使用 configProvide 没问题，有些要全局修改

**Comment by wushangwei** [comment]
试了一下在config.ts里的antd里是可以的：
`antd: {
    theme: {
      token: {
        colorPrimary: '#00b96b'
      }
    }
  },`

**Comment by hihuangwei** [comment]
@wushangwei 还是不会生效
