### ISSUE TITLE
🐛 [BUG] global.less height: 100%; 有何作用，在 layout: false 自定义页面会多出一行，是否可以去除 height: 100%;

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#10415]
### 🐛 bug 描述
````
html,
body,
#root {
  height: 100%;
  margin: 0;
  padding: 0;

````

![微信截图_20221205191252](https://user-images.githubusercontent.com/3166799/205623722-53ccf882-61e7-463e-a4f0-288eeaf5b3d7.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这段代码将页面的高度设置为100%，意味着整个页面都将填满屏幕。`layout: false` 是一个选项，用于禁用默认的布局，意味着该页面的渲染不会受到默认布局的影响。因此，在禁用默认布局的情况下，为HTML、body、#root元素设置100%高度会使内容多出一行。

如果你想要禁用默认布局，可以尝试去掉 `height: 100%;`，并将你的自定义布局放置在外层容器中，这样就能正确的设置高度并且避免出现多余的一行。如下所示：

```css
.container {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.content {
  flex: 1;
}
```

在模板中，你可以这样写：

```html
<%- include('header') %>
<div class="container">
  <div class="content">
    <%= locals.body %>
  </div>
</div>
```

这里，我们创建了一个`.container`元素，并设置其高度为100%，并将它的 `display` 属性设置为 `flex` 布局，并设置其主轴方向为垂直方向，即 `flex-direction: column;`。 这里的 `.content` 是一个flex项目，我们使用 `flex: 1;` 将它拉伸以填满容器。 通过这种方式，我们能够正确地设置页面高度，并避免出现多余的行。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题描述中的`global.less`文件中的`height: 100%;`的作用是将`html`、`body`和`#root`元素的高度都设置为100%。这个样式可能会导致在使用`layout: false`自定义页面时出现多出一行的问题。

解决方案如下：
1. 可以尝试去除`global.less`文件中的`height: 100%;`样式。
2. 如果需要保持元素高度为100%，可以在具体的自定义页面中添加自定义样式来设置元素的高度为100%。例如，在使用`layout: false`的自定义页面中添加以下样式：
   ```css
   body {
     height: 100%;
   }
   ```
3. 如果使用了React技术，并且使用了Umi和antd作为前端框架，可以考虑使用antd的`Layout`组件来实现页面布局，而不是手动设置元素的高度。这样可以更好地控制页面布局，并避免出现多余的问题。具体可以参考antd官方文档中的Layout组件的使用方法。

综上所述，可以根据具体情况选择适合的解
