### ISSUE TITLE
升级1.0后 开发环境和生产环境 打包没有0.2版本快了

### ISSUE THREAD

**Issue by waybi** [ant-design/ant-design-pro#1041]

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD

**Comment by waybi** [comment]
@afc163 主要是开发编译的时候 有时候需要等好几秒（起码5，6秒）webpack才Compile完成，以前一般来说1，2秒就能完成

**Comment by chenshuai2144** [comment]
这个应该不着急吧，，，，，大的项目的小半个小时的都有

**Comment by waybi** [comment]
@chenshuai2144 打包部署的时候还好 还能等 但是本地开发的时候 打包编译太慢 确实体验不好

**Comment by chenshuai2144** [comment]
起来之后就不会了，等 webpack4适配了可能快点
