### ISSUE TITLE
🧐[问题 | question] 为什么config.ts中的routes.ts不能给路由加一些自定义参数

### ISSUE THREAD

**Issue by 18046163690** [ant-design/ant-design-pro#10419]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤖 回复 | Solution

你好，感谢提出问题。在 `config.ts` 中的 `routes.ts` 中可以给路由加上一些自定义参数，但是需要满足以下两种情况的其中之一：

1. 路由组件需要接收这些自定义参数。
2. 这些自定义参数需要在渲染路由组件的时候传递，否则它们会被忽略。

你可以在这篇 [React-Router 官方文档](https://reactrouter.com/web/example/url-params) 中找到更多关于路由参数的信息。

假设现在我们有这样一个路由：

```typescript
{
  path: "/users/:id",
  component: User,
  customParam: "someValue" // 自定义参数 
}
```

对于第一种情况（路由组件需要接收这些自定义参数），你需要在路由组件中调用 `useLocation` 和 `useParams` 这两个 **hook**，然后可以从 `location` 中获取到完整的 url 信息，包括查询参数和哈希值，从 `params` 中获取到路由参数

以下是示例代码：

```typescript
import { useLocation, useParams } from "react-router-dom";

function User() {

  // 使用 useLocation 和 useParams hook，获取路由参数和自定义参数
  const { id } = useParams<{id: string}>(); // 从 params 中获取路由参数
  const location = useLocation(); // location 中包含了完整的 url 信息，包括查询参数和哈希值
  const customParam = location.state.customParam; // 从 location 中获取自定义参数

  // ... 其他的组件代码
}
```

对于第二种情况（需要在渲染路由组件时传递自定义参数），你可以使用 `history.push` 或者 `history.replace` 在路由跳转时传递自定义参数，以下是示例代码：

```typescript
import { useHistory } from "react-router-dom";

function goToUser(id: string, customParam: string) {

  // 通过 history.push 传递自定义参数
  const history = useHistory();
  history.push({
    pathname: `/users/${id}`,
    state: { customParam }
  });
}
```

希望这些代码能够帮到你，如果你还有其他问题，请继续追问。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


config.ts中的routes.ts文件是用来定义路由的，一般情况下是不需要给路由加一些自定义参数的。路由是用来定义页面之间的跳转关系和URL路径的映射关系的，一般来说不需要携带额外的参数。

如果你的需求是需要在路由之间传递一些自定义的参数，可以考虑以下两种解决方案：

1. 使用query参数：可以在URL中使用query参数来传递额外的参数。通过在URL中添加类似于`/path?param1=value1&param2=value2`的形式，可以将参数传递给下一个页面。在React中，可以使用`react-router`库来获取URL中的query参数。

2. 使用redux或者其他状态管理库：如果需要在路由之间传递的参数比较复杂或者需要在多个组件之间共享，可以考虑使用状态管理库，比如redux。通过将参数存储在全局的store中，可以在任何页面中获取和修改参数。

需要注意的是，config.ts中的routes.ts文件是在构建时进行处理的，它主要用来配置页面的路由信息，并不适合用来处理运行时的逻辑。如果需要在运行时动态获取参数，可以考虑使用其他的方式，比如在组件中进行异步请求获取参数。

总结一下，config.ts中的routes.ts文件不适合用来给路由加自定义参数，可以考虑使用query参数或者状态管理库来实现路由之间的参数传递。
