### ISSUE TITLE
🧐[问题 | question] 为什么config文件夹中的routes.ts不能给路由加一些自定义参数

### ISSUE THREAD

**Issue by 18046163690** [ant-design/ant-design-pro#10420]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供信息！

关于在 routes.ts 文件中给路由加一些自定义参数，可能需要简单了解一下 React 路由的一些基本知识。

首先，React 路由是由一个路由组件来管理路由的，最常用的是 react-router-dom 这个库。在使用这个库时，我们通常会用 Route 组件来定义路由。在 Route 组件中，我们可以传入一些 props 来配置当前路由的行为，包括 path（路由路径）、component（对应的组件）、exact（是否精确匹配）等等。如果我们需要给路由加一些自定义参数，则需要自己定义一些 props，并在路由组件中进行相应的操作。

例如，在我们的项目中，我们想要给一个名为 Home 的路由加上一个自定义参数 name，那么我们可以这样编写 routes.ts 文件：

```javascript
import React from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import Home from './pages/Home';

const AppRouter: React.FC = () => {
  return (
    <Router>
      <Switch>
         <Route exact path="/" component={Home} name="My Home" />
      </Switch>
    </Router>
  );
};

export default AppRouter;
```

在这个例子中，我们给 Home 路由的 component 属性传入了 Home 组件，并在 Route 组件中添加了一个自定义参数 name，并将这个参数的值设为了字符串 "My Home"。

这样，在 Home 组件中，我们就可以通过 props 的方式获取到这个值了。例如：

```javascript
import React from 'react';
import { RouteComponentProps } from 'react-router-dom';

interface Props extends RouteComponentProps<{name: string}> {
}

const Home: React.FC<Props> = ({match: {params: {name}}}) => {
  return (
    <div>
      <h1>{name}</h1>
      <p>Welcome to my home!</p>
    </div>
  );
};

export default Home;
```

在这个例子中，我们通过 props 的方式获取到了自定义参数 name，并将其显示在组件中。

希望这个例子能够帮到你解决问题。如果还有其他问题，请随时提出。
