### ISSUE TITLE
👑 [需求 | Feature] 升级到 antd 5.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#10427]
以及 procomponents 的最新设计风格。

**Comment by echoyl** [comment]
年底能出来吗？

**Comment by cui-xxu** [comment]
给个大致时间也好啊:-)

**Comment by joesdu** [comment]
看起来是快了, @chenshuai2144 大佬已经合并了,等一个文章.

**Comment by fullee** [comment]
圆角有个全局控制变量吗，还是喜欢方角:-)

**Comment by WuJiY** [comment]
> 圆角有个全局控制变量吗，还是喜欢方角:-)

有的

**Comment by beautytea8** [comment]
> simple 脚手架升级了，演示网站还需要一点时间

@chenshuai2144  大佬请问有发版计划吗

**Comment by joesdu** [comment]
每天都在关注发版,新项目都不敢创建项目,等着的🤣

**Comment by yangliuyu** [comment]
迎元旦发新版😄

**Comment by hpf0532** [comment]
期待新版本发布

**Comment by joesdu** [comment]
等发版后我就新建项目,打算写个全栈框架.😬

**Comment by fullee** [comment]
啥技术栈呐



---- 回复的原邮件 ----
| 发件人 | Joe ***@***.***> |
| 日期 | 2023年01月05日 14:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ant-design/ant-design-pro] 👑 [需求 | Feature] 升级到 antd 5.0 (Issue #10427) |

等发版后我就新建项目,打算写个全栈框架.😬

**Comment by xiexingen** [comment]
> abp 7 么

**Comment by joesdu** [comment]
> > abp 7 么

自己搭框架,ABP感觉太复杂了,不会用.

**Comment by chenshuai2144** [comment]
升级全部完成了

**Comment by echoyl** [comment]
> 升级全部完成了

大佬这主题设置咋没了？
[https://preview.pro.ant.design/](https://preview.pro.ant.design/)
