### ISSUE TITLE
🧐[问题 | 登录之后获取后端返回的菜单，但此时还没有进入到BasicLayout，导致跳转404，请问这个应该如何处理？

### ISSUE THREAD

**Issue by baiwumm** [ant-design/ant-design-pro#10423]
### 🧐 问题描述 | Problem description

1、登录成功之后获取用户信息和动态菜单，将数据放到 initialState

![image](https://user-images.githubusercontent.com/40554571/206342904-bd359905-47af-4897-9dfb-026a0daed2ea.png)

2、BasiLayout 里面塞入菜单数据
![image](https://user-images.githubusercontent.com/40554571/206343003-84ca2974-7678-4534-b28e-903dd10693ad.png)

3、但是此时登录页还没有跳转进来BasiLayout，无法触发第二步，导致跳转404

![image](https://user-images.githubusercontent.com/40554571/206343170-69600d5c-80a2-4f6e-8590-fe68fc376ec5.png)

![image](https://user-images.githubusercontent.com/40554571/206343211-252fc4bc-5bef-4171-930e-7b85b1ed5105.png)

4、请问这里我该如何处理，再登录成功即将跳转前把动态路由放到route里面

### 💻 示例代码 | Sample code

[github 仓库](https://github.com/Cyan-Xmw/Xmw-Admin/blob/Cyan/Xmw_web/src/pages/User/Login/index.tsx)

### 🚑 其他信息 | Other information

OS: window

Ant-pro：6.0.0-beta.1

浏览器 | browser：Google

**Comment by echoyl** [comment]
1.登录成功后 写入数据 await setInitialState((s) => ({ ...s, currentUser: res.userinfo }));
2.然后layout 的menu直接读取数据不再发送请求 
menu: {
      request: async (params, defaultMenuData) => {
        const newMenu = loopMenuItem(initialState?.currentUser?.menuData);
        return newMenu;
      },
    },

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的提醒和补充，确实在登录成功后要调用 `setInitialState` 方法去设置初始值，不过这一步已经在用户的代码示例中完成了。

接下来，我提供以下的思路作为参考，希望对用户解决问题有所帮助：

由于在路由跳转之前，页面组件已经渲染出来，我们可以考虑在 `componentDidMount` 生命周期函数中获取并设置菜单数据。

假设初始化的 state 如下：

```jsx
const [initialState, setInitialState] = useIntlProvider();
const [menuData, setMenuData] = useState([]); // 菜单数据
```

在 `componentDidMount` 生命周期中，我们可以获取并设置菜单数据：

```jsx
useEffect(() => {
  const { currentUser } = initialState;
  if (currentUser?.menuData) {
    const newMenu = loopMenuItem(currentUser?.menuData);
    setMenuData(newMenu);
  }
}, [initialState]);
```

这里我们通过 `if (currentUser?.menuData)` 判断用户菜单数据是否存在，如果存在我们就调用 `loopMenuItem` 方法去转化菜单数据，最后通过 `setMenuData` 方法去设置。

`loopMenuItem` 方法可以参考用户代码示例中的实现。

最后，在菜单组件中将得到的 `menuData` 设置到 Ant Design Pro 的菜单数据里即可：

```jsx
<Menu
  mode="inline"
  theme="dark"
  selectedKeys={[selectedKeys]}
  openKeys={openKeys}
  onOpenChange={onOpenChange}
>
  {menuData?.map((item) => {
    if (item.children) {
      return (
        <SubMenu
          key={item.path}
          title={
            <span>
              {item.icon && <IconFont type={item.icon} />}
              <span>{item.name}</span>
            </span>
          }
        >
          {item.children.map((child) => (
            <Menu.Item key={child.path}>
              <Link to={child.path}>
                {child.icon && <IconFont type={child.icon} />}
                <span>{child.name}</span>
              </Link>
            </Menu.Item>
          ))}
        </SubMenu>
      );
    }
    return (
      <Menu.Item key={item.path}>
        <Link to={item.path}>
          {item.icon && <IconFont type={item.icon} />}
          <span>{item.name}</span>
        </Link>
      </Menu.Item>
    );
  })}
</Menu>
```

希望这些思路能够对您有所帮助，如有任何问题或疑问欢迎继续向我提出。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


针对这个问题，你可以使用`onRouteChange`来监听路由的变化，在路由变化时进行相关处理。具体步骤如下：

1. 在`src/layouts/index.tsx`中，导入`useEffect`和`useModel`：
   ```tsx
   import { useEffect } from 'react';
   import { useModel, history } from 'umi';
   ```

2. 在`Layout`组件中，获取`initialState`和`initialLoaded`：
   ```tsx
   const { initialState, initialLoaded } = useModel('@@initialState');
   ```

3. 在`useEffect`中，监听路由的变化：
   ```tsx
   useEffect(() => {
     if (initialLoaded) {
       handleRouteChange();
     }
     return history.listen(handleRouteChange);
   }, [initialLoaded]);
   ```

4. 实现`handleRouteChange`方法，在路由变化时进行处理：
   ```tsx
   const handleRouteChange = () => {
     const { currentUser } = initialState;
     if (currentUser && !currentUser.menuLoaded) {
       // 请求后端获取菜单数据
       // 更新菜单数据到 initialState
       // 设置菜单加载状态为已加载
     }
   };
   ```

通过上述步骤，你可以在路由变化时判断当前用户是否已获取菜单数据，如果没有获取，则请求后端获取菜单数据，并更新到`initialState`中。这样，在进入`BasicLayout`之前就能获取到菜单数据，避免跳转404的问题。

**Comment by zhu0629** [comment]
加个状态撒, 如果没有获取到就Spin等等呀.
