### ISSUE TITLE
localhost,mock无法使用，Response status:404

### ISSUE THREAD

**Issue by xudan95** [ant-design/ant-design-pro#10439]

**Comment by hfpp2012copy** [comment]
你启动的时候，估计环境变量 MOCK=none 了 不过没必要使用 mock

**Comment by xudan95** [comment]
@hfpp2012copy 前后端分离，有mock会方便些

**Comment by zmm2tysu** [comment]
+1

**Comment by hooliy** [comment]
+1
上个版本还是好的，更新后不行了

**Comment by zmm2tysu** [comment]
@xudan95 @hooliy 把proxy下面的dev对像注释掉就好了我

**Comment by hooliy** [comment]
@zmm2tysu  3Q

**Comment by xudan95** [comment]
@zmm2tysu 3Q

**Comment by xudan95** [comment]
> > @hfpp2012copy 前后端分离，有mock会方便些
> 
> 肯定是前后端分离，可是你最后要不要接上 api，那你写 mock 有意义吗

有一定意义，项目初期，当接口文档先行接口未开发的时候就用得上了

**Comment by chn-lee-yumi** [comment]
+1，好坑。。。我直接初始化啥都没改就404.。。

**Comment by hfpp2012copy** [comment]
> > > @hfpp2012copy 前后端分离，有mock会方便些
> > 
> > 
> > 肯定是前后端分离，可是你最后要不要接上 api，那你写 mock 有意义吗
> 
> 有一定意义，项目初期，当接口文档先行接口未开发的时候就用得上了

初期连 api 接口都提供不了，做什么项目

**Comment by An0nymous0** [comment]
好像不行，今天刚刚初始化的项目 注释掉dev 一样是404

**Comment by tears008** [comment]
> 好像不行，今天刚刚初始化的项目 注释掉dev 一样是404

+1

**Comment by nasa1024** [comment]
> 好像不行，今天刚刚初始化的项目 注释掉dev 一样是404

@An0nymous0 @tears008 解决了吗，我刚刚也出现了这个问题

**Comment by yasz** [comment]
同问，最新版的问题？

**Comment by thensha** [comment]
在package.json里用start命令启动
