### ISSUE TITLE
🧐[问题 | question  我需要antd pro4.5 typescript版本 带实例页面的工程 

### ISSUE THREAD

**Issue by beijinghuzi** [ant-design/ant-design-pro#10437]
### 🧐 问题描述 | Problem description

我需要antd pro4.5 typescript版本 带实例页面的工程    麻烦作者或者 谁有 给到我份！   

**antd pro4.5 typescript版本  带实例页面的工程**

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。



### 🤖 解决方案 | Solution

你可以通过 GitHub 上的 ant-design/pro-blocks 仓库来获取 antd pro4.5 typescript 版本的带实例页面的工程。

步骤如下：

1. 克隆 `ant-design/pro-blocks` 仓库：

```
git clone https://github.com/ant-design/pro-blocks.git
```

2. 进入 `pro-blocks` 目录，使用 `git log` 命令查看仓库中的提交记录，找到对应版本的提交记录（以 tag 为例）：

```
git checkout tags/v4.5.0 -b v4.5.0
```

3. 在 `pro-blocks/ant-design-pro` 目录下，运行以下命令安装依赖：

```
npm install
```

4. 运行以下命令启动本地开发服务器：

```
npm start
```

5. 打开浏览器访问地址 `http://localhost:8000/`，你就可以看到 antd pro4.5 typescript 版本的示例页面了。

请注意，本地开发服务器需要使用 node 10.13 及以上版本，同时推荐使用最新版的 Chrome 浏览器来访问页面。

你也可以通过 pro-blocks 的文档来了解更多关于如何使用该仓库来快速搭建项目的信息：https://github.com/ant-design/pro-blocks#readme。
