### ISSUE TITLE
权限动态路由跳转

### ISSUE THREAD

**Issue by wboykron** [ant-design/ant-design-pro#10436]
### 🥰 需求描述 | Requirements description

文档中：服务端获取的菜单重定向不生效，重定向需要配置在路由中才会生效。有一个需求：后端根据权限返回菜单，配置中的重定向指向的路由又不在权限中的菜单，怎么办？比如：routes中配置，/order重定向/order/info，但是由于后端管理权限设置，/order应跳转/order/city，当前用户直接没有/order/info的权限，应该如何才能实现？

**Comment by WuJiY** [comment]
不知道有没有更好的办法，我是在onPageChage 里 做了循环判断

**Comment by wboykron** [comment]
> 不知道有没有更好的办法，我是在onPageChage 里 做了循环判断

这样的话，每个页面都要判断一次，跳转还是写死的，也不好实现！

**Comment by xcxiao7710** [comment]
这个问题11月23号 下载的代码  问题现在你们才处理 对于一个后端来说是一件多么痛苦的事

**Comment by hyzx86** [comment]
你说的哪个文档？

路由你必须定义动态路由，才可以匹配动态菜单

* 表示匹配任何页面 ，你在动态菜单里没有匹配任何路径的话就可以使用 动态路由节点接收

比如

``` json
[
  {// 动态页面 
    locale: false,
    hideInMenu: true,
    path: "menu/:id",
    name: "MenuPage",
    component: './amis/AmisDynamicPage',
  },
  //微前端容器
  {
    // 不展示顶栏
    headerRender: false,
    // 不展示页脚
    footerRender: false,
    layout: false,
    // 不展示菜单
    menuRender: false,
    // 不展示菜单顶栏
    menuHeaderRender: false,
    // 隐藏子菜单
    hideChildrenInMenu: true,
    // 隐藏自己和子菜单
    hideInMenu: true,
    // 在面包屑中隐藏
    hideInBreadcrumb: true,
    name: 'dpage',
    locale: false,
    path: '/dpage/:module/:subModule/:pageName',
    component: './amis/AmisDynamicPage',
  },
  {// 模块+子模块+动态页面
    locale: false,
    hideInMenu: true,
    name: 'dynamic_SubModulePage',
    path: '*',
    // path: '/:module/:subModule/:pageName',
    component: './amis/AmisDynamicPage',
  }]


```

**Comment by hyzx86** [comment]
> 不知道有没有更好的办法，我是在onPageChage 里 做了循环判断

在Menu 里面过滤一下，好使

**Comment by WuJiY** [comment]
> 

你的意思就是需要动态菜单了？

> > 不知道有没有更好的办法，我是在onPageChage 里 做了循环判断
> 
> 在Menu 里面过滤一下，好使

你的意思就是需要动态菜单了？

**Comment by hyzx86** [comment]
对啊 ，都可以，我是没搞明白这个 菜单权限有什么卵用。。 打开页面后再转到404？
或者要到 onPageChange 里面 手动call 一下？

**Comment by hyzx86** [comment]
不对， onPageChange 是每次调用，而动态菜单只调用一次
你可以监听 用户id 之类的东西 让它触发刷新

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


对的，onPageChange 和权限 handler 都是每次页面跳转都会触发的，而动态菜单只需要生成一次即可。

如果要让权限 handler 在每次页面跳转的时候自动调用，可以在路由配置中使用 HOC 来封装组件，将权限控制的逻辑放在 HOC 中，这样每次组件渲染时都会触发权限控制逻辑。例如：

```js
import PrivateRoute from 'path/to/PrivateRoute';

const routes = [
  {
    path: '/order',
    component: PrivateRoute(Order, { requiredRoles: ['order.admin'] }),
    redirect: '/order/city',
    routes: [
      {
        path: '/order/city',
        component: PrivateRoute(OrderCity, { requiredRoles: ['order.admin'] }),
      },
      {
        path: '/order/info',
        component: PrivateRoute(OrderInfo, { requiredRoles: ['order.info'] }),
      },
    ],
  },
  // other routes...
];
```

在 `PrivateRoute` 组件中，我们将权限逻辑封装起来，如果用户没有权限则返回一个 `Unauthorized` 组件进行处理。`PrivateRoute` 的实现可以参考 [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config) 中的 `renderRoutes` 函数的实现，使用递归进行遍历。同时我们可以在 `PrivateRoute` 中将菜单的 `path` 和 `redirect` 都设置成动态生成的，方便用户跳转。

至于动态菜单，我们可以在用户登录时请求一次后端接口获取拥有权限的菜单列表，然后根据这个菜单列表动态生成菜单。想要实现权限控制的菜单，可以将菜单节点的 `path` 和 `redirect` 都设置成动态生成的，与 `PrivateRoute` 中的菜单节点对应上。这样，在菜单项点击后就会自动跳转到对应的页面进行权限校验。

当用户的权限发生改变时，我们也可以将权限控制的菜单节点的 `path` 和 `redirect` 进行更新。同时可以通过监听用户权限的变化，在合适的时机触发菜单的重新渲染。
