### ISSUE TITLE
👑 [需求 | Feature] BasicLayout 去掉了rightContentRender配置，但是会有默认的头像

### ISSUE THREAD

**Issue by baiwumm** [ant-design/ant-design-pro#10431]
### 🥰 需求描述 | 如标题所示

1、我在BasicLayout 去掉了rightContentRender配置，加上了avatarProps和actionsRender
![image](https://user-images.githubusercontent.com/40554571/206663657-2a0afcbb-2b69-44df-842b-ba95b6f5044d.png)

2、实现的效果
![image](https://user-images.githubusercontent.com/40554571/206663688-d2cdd194-3f47-4f1f-8693-b2c2d497d9ac.png)
![image](https://user-images.githubusercontent.com/40554571/206663741-c4c882c7-a100-4aa8-9c63-33ac29691e11.png)

3、期望的效果，去掉默认的配置，期望如下
![image](https://user-images.githubusercontent.com/40554571/206663968-85ff4bc8-12e1-458b-b92b-0d03dc552a36.png)

4、菜单从后端默认返回，请问如何才能获取当前页面的配置？
![image](https://user-images.githubusercontent.com/40554571/206664449-4a8e3a02-2384-466c-9d46-5982d6bff909.png)

我想获取当前路由的菜单配置:

![image](https://user-images.githubusercontent.com/40554571/206665943-9a570bde-7841-470b-94b4-87fb75a6f1fe.png)

**Comment by woshihuxiangbo** [comment]
rightContentRender:false 才行

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你的需求描述，你可以尝试将 `rightContentRender` 设置为 `false`，这样 `avatarProps` 和 `actionsRender` 就不会显示了，从而达到你期望的效果。

关于获取当前页面的菜单配置，可以尝试使用 `pathToRegexp` 库将当前路由匹配到对应的菜单项，然后从菜单项中获取配置信息。示例代码如下：

```javascript
import { matchPath } from 'path-to-regexp';
import menuData from './menuData'; // 从后端获取的菜单数据

const currentRoute = window.location.pathname; // 获取当前路由

// 遍历菜单数据，找到匹配当前路由的菜单项
const currentMenu = menuData.find(item => {
  const match = matchPath(currentRoute, {
    path: item.path,
    exact: true,
  });
  return match !== null;
});

// 获取当前菜单的配置信息
const currentMenuConfig = currentMenu?.menuConfig;
```

这里使用了 `path-to-regexp` 库来将菜单项的路径和当前路由进行匹配，找到匹配的菜单项后，就可以直接从菜单项中获取配置信息了。

另外，由于你只能处理关于 React 的前端问题，如果你需要更多的后端接口或其它相关的信息，请向相应的团队或者开发者寻求帮助。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案如下：

1. 在BasicLayout中，添加两个新的配置项`avatarProps`和`actionsRender`，用于替换`rightContentRender`。其中，`avatarProps`用于设置头像的属性，`actionsRender`用于渲染右上角的操作按钮。

```tsx
import { Avatar, Menu, Dropdown } from 'antd';
import { UserOutlined, LogoutOutlined } from '@ant-design/icons';

// ...

const menu = (
  <Menu>
    <Menu.Item key="logout">
      <LogoutOutlined />
      退出登录
    </Menu.Item>
  </Menu>
);

const BasicLayout: React.FC = () => {
  // ...

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        {/* 渲染头像 */}
        <Avatar src={avatarProps?.src} />
        {/* 渲染操作按钮 */}
        {actionsRender && actionsRender()}
        {/* 渲染退出登录按钮 */}
        {logout && (
          <Dropdown overlay={menu}>
            <UserOutlined />
          </Dropdown>
        )}
      </div>
      {/* 渲染菜单和内容 */}
      {/* ... */}
    </div>
  );
};

export default BasicLayout;
```

2. 在入口文件（通常是`src/app.ts`）中，设置全局的初始化信息，包括用户名和头像。

```tsx
export function getInitialState() {
  return {
    name: 'Serati Ma',
    avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
  };
}
```

3. 如果希望自定义退出登录的逻辑，可以在入口文件中设置`logout`配置项。

```tsx
export const layout = {
  logout: () => {
    alert('退出登录成功');
  },
};
```

4. 如果以上配置不能满足需求，可以通过自定义`rightRender`配置项来完全自定义右上角的内容。

```tsx
import React from 'react';

export const layout = {
  rightRender: (initialState, setInitialState) => {
    // 自定义右上角的内容
    return (
      <>
        <Avatar src={initialState.avatar} />
        {/* 其他自定义内容 */}
      </>
    );
  },
};
```

5. 如果需要获取当前页面的菜单配置，可以使用`useLocation`和前端路由配置来获取。

```tsx
import { useLocation } from 'umi';

const BasicLayout: React.FC = () => {
  const location = useLocation();
  
  // 根据当前的 location 获取菜单配置
  const getMenuConfig = () => {
    // 获取当前路由的路径
    const path = location.pathname;

    // 根据路径获取对应的菜单配置
    const menuConfig = getMenuConfigByPath(path);

    return menuConfig;
  };

  // ...
};
```

通过以上步骤，您可以实现去掉默认的配置，自定义右上角的头像和操作按钮，并且获取当前页面的菜单配置。
