### ISSUE TITLE
🐛 [BUG]登录页，登录后返回404

### ISSUE THREAD

**Issue by wangwufan** [ant-design/ant-design-pro#10446]
### 🐛 bug 描述
登录后定向的页面不存在
![image](https://user-images.githubusercontent.com/12657738/207793639-12b59287-e65f-4db7-aba2-3b12f39cc6c7.png)

### 📷 复现步骤 | Recurrence steps
点登录按钮

### 🏞 期望结果 | Expected results

登录后，找个能访问的页面打开，别404

### 💻 复现代码 | Recurrence code

无需新代码

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本4
- 浏览器环境 chrome 100以上
- 开发环境 [windows]

**Comment by lzx020301** [comment]
我也一样，我用start启动也是这样的情况

**Comment by lzx020301** [comment]
我把代码回滚到十月三十号以前的版本，就可以正常运行了，最新版本的代码我也不知道怎么解决，先用以前的代码吧

**Comment by akrio714** [comment]
一样的问题

**Comment by sansheng741** [comment]
想问下，目前6版本能应用到prd环境吗？

**Comment by wangwufan** [comment]
我只想把我目前的v4项目升级到v5，官方到现在也没有给出v5版的全区块展示

**Comment by daviscyl** [comment]
我也遇到这个情况, 前两天明明还好好的, 不知道是不是 mock 被关了?

**Comment by imbyron** [comment]
一样的问题，Response status:404

**Comment by hfpp2012copy** [comment]
看你发送了啥请求，你应该还没对接好后端吧 https://www.qiuzhi99.com/playlists/antdprov5latest.html

**Comment by shanzhaozhen** [comment]
同样遇到这个问题，最新版本mock的配置方式改变了config.ts增加了 `requestRecord: {}` 配置选项。不过不知道为什么怎么配置，mock就是不生效，查umijs文档也找不到这个配置项。大佬麻烦看看 @chenshuai2144

**Comment by fsrm365** [comment]
我也遇到同样的问题。

**Comment by bluenergy** [comment]
参考：[#10439 ](https://github.com/ant-design/ant-design-pro/issues/10439#issuecomment-1350535122)
注释掉 config/proxy.ts 里的 dev: {}

**Comment by billychou** [comment]
> 参考：[#10439 ](https://github.com/ant-design/ant-design-pro/issues/10439#issuecomment-1350535122) 注释掉 config/proxy.ts 里的 dev: {}
好使

**Comment by daviscyl** [comment]
> 参考：[#10439 ](https://github.com/ant-design/ant-design-pro/issues/10439#issuecomment-1350535122)
> 注释掉 config/proxy.ts 里的 dev: {}

好使!

**Comment by rdmp2022** [comment]
> 参考：[#10439 ](https://github.com/ant-design/ant-design-pro/issues/10439#issuecomment-1350535122) 注释掉 config/proxy.ts 里的 dev: {}

好使！！！

**Comment by chen764763500** [comment]
> 参考：[#10439 ](https://github.com/ant-design/ant-design-pro/issues/10439#issuecomment-1350535122) 注释掉 config/proxy.ts 里的 dev: {}

好使！！！！！
