### ISSUE TITLE
🧐[问题 | question] emotion css 样式覆盖问题

### ISSUE THREAD

**Issue by shanzhaozhen** [ant-design/ant-design-pro#10449]
### 🧐 问题描述 | Problem description
升级到6.0后发现项目中的 `style.less` 等样式文件都被清除了，改用 `emotion css` 的方式写样式。但是该方式只能修改当前标签样式，请问用这种方式的话如何覆盖 `ant design` 的默认样式呢？

### 💻 示例代码 | Sample code

```
  :global {
    .ant-list-split .ant-list-item:last-child {
      border-bottom: 1px solid @border-color-split;
    }
    .ant-list-item {
      padding-top: 14px;
      padding-bottom: 14px;
    }
  }
```

**Comment by qxz123456** [comment]
这个问题解决了没，遇到相同的问题了，想覆盖原有的样式，加!important都不好使

**Comment by hpf0532** [comment]
蹲一个解决方案

**Comment by kimi119** [comment]
蹲一个解决方案

**Comment by qxz123456** [comment]
我在app.ts里加了这几行代码，把那个main标签多了的padding给干掉了
import { injectGlobal } from '@emotion/css'

injectGlobal`
.ant-pro .ant-pro-layout .ant-pro-layout-content {
    padding-block: 0;
    padding-inline: 0;
}`

**Comment by 4innocent** [comment]
Hi bro！I find a solution. `injectGlobal` is not elegant, it may cause other bugs.use mine.
兄弟，我知道怎么搞了，injectGlobal方式感觉有点傻，有可能有其他问题，用我这个。
![image](https://user-images.githubusercontent.com/39057551/218438495-81bb06a8-18fd-4b2d-8cb3-331d0b3e2bc4.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


好的，感谢分享你的解决方案。看起来你是使用了 `@emotion/react` 包里的 `css` 函数来实现样式覆盖的。这个函数可以接收一个 CSS 模板字符串作为参数，然后返回一个 CSS 类名，再将其通过 `className` 属性赋值给需要进行样式覆盖的组件即可生效。代码示例如下：

```jsx
import { css } from '@emotion/react'

const overrideStyles = css`
  .ant-list-split .ant-list-item:last-child {
    border-bottom: 1px solid @border-color-split;
  }
  .ant-list-item {
    padding-top: 14px;
    padding-bottom: 14px;
  }
`

function MyComponent() {
  return (
    <div css={overrideStyles}>
      {/* 这里是需要样式覆盖的组件内容 */}
    </div>
  )
}
```

这样就可以避免使用 `!important` 的方式覆盖样式，并且可以更好地维护你的样式代码。希望这个解决方案能够给你带来帮助。
