### ISSUE TITLE
登录页，输入指定用户密码后，登录返回404🐛 [BUG]

### ISSUE THREAD

**Issue by wangwufan** [ant-design/ant-design-pro#10445]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/208243118-6031e6eb-057a-4e9a-b0e7-f54c70c83f78.png)

该仓库最新代码。。。
npm run start 
api 没启动？？ 怎么才能启动啊？

**Comment by fsrm365** [comment]
我也遇到同样的问题

**Comment by bluenergy** [comment]
参考：https://github.com/ant-design/ant-design-pro/issues/10439#issuecomment-1350535122
注释掉 config/proxy.ts 里的 dev: {}

**Comment by chn-lee-yumi** [comment]
这bug还没修。。。

**Comment by hyzx86** [comment]
已经修复了啊

https://github.com/ant-design/ant-design-pro/pull/10453/files

**Comment by liuzhcn** [comment]
但是拉下来的，还是有这个bug。

**Comment by HZZformGD** [comment]
> 已经修复了啊
> 
> https://github.com/ant-design/ant-design-pro/pull/10453/files

我和 @liuzhcn  一样， pro create xxx 拉下来的代码一样有这个报错。 麻烦你们再仔细看看吧 @hyzx86

**Comment by hyzx86** [comment]
@HZZformGD 
PR 更新的是仓库，不是cli 

检查个卵 u can u up ，
我只是解决我的问题的同时，顺手推送下PR 而已， 相信你也可以
仓库是开源的，所有人都可以贡献代码


另外提示一下，目前6.0 还是beta 版本 有问题 可以提出来，不建议直接上生产
如果要上可以保持官方仓库和自己仓库的连接做合并更新，下次更新直接 merge下 变更就好

**Comment by Hank-Zhou** [comment]
![image](https://user-images.githubusercontent.com/18147623/210526740-d6a2f0e1-737a-404f-b9c4-ed88ef34a961.png)
![image](https://user-images.githubusercontent.com/18147623/210526927-fe495cbe-1067-460b-ba26-b6cad2a7784b.png)
注释完，报错是不报错了，但是还是进不去，网络里面显示这个
一个大厂搞的管理系统竟然连登录都进不去，哪怕是演示的

**Comment by hyzx86** [comment]
这不还在beta 呢。。 慌啥
你拉的最新源码么？

**Comment by haosx123** [comment]
> 但是拉下来的，还是有这个bug。
用“start”启动，不要用“start:dev”。当前的版本，我用“start:dev”就会出现这个问题。

**Comment by hyzx86** [comment]
我要吐血了。。 之前给客户看了 6.0  的布局
结果客户姥爷看上了。。
现在遇到一堆奇葩问题

**Comment by restlessfish** [comment]
没有后端，用start启动不要用dev
