### ISSUE TITLE
引入外部node导致build不通过

### ISSUE THREAD

**Issue by zfan40** [ant-design/ant-design-pro#1044]
环境：node 7 & 8， npm 5.7
系统：win7 macOSX
重现过程：

-  pull最新ant design pro项目,
-  `npm install @jscad/openjscad`
-  业务代码任意处粘贴以下代码

```

const jscad = require('@jscad/openjscad')
const fs = require('fs')

var script = `function main() {
   return [
      torus()
  ]
}`

// generate compiled version
var params = {}
jscad.compile(script, params).then(function(compiled) {
  var outputData = jscad.generateOutput('stlb', compiled)
  fs.writeFileSync('torus.stl', outputData.asBuffer())
})

```
可正常npm  run start
build 报错：Failed to minify the bundle. Error: index.79d6441a.js from UglifyJs
Unexpected token: name (staticTag)

尝试在其他项目可正常打包

求指点

**Comment by chenshuai2144** [comment]
感觉是因为你的库用的语法是 es6 的 
UglifyJs不支持

**Comment by zfan40** [comment]
有没有什么解决方法。。。比如替换uglify或者如何配置roadhog里的babel？
或者是否有计划在升级中加入对es6库的支持？？
感谢回复

**Comment by chenshuai2144** [comment]
@sorrycc  看一看 你应该做了这些的配置了吧

**Comment by zfan40** [comment]
roadhog默认babel exclude node_modules
.webpackrc配置增加extraBabelIncludes:['/node_modules/xxx']解决
可参考https://github.com/sorrycc/roadhog/issues/35
建议更新下文档...
