### ISSUE TITLE
🧐[问题 | question] 关掉i18n后，如何让日历和分页显示成中文的？

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#10450]
### 🧐 问题描述 | Problem description

关掉i18n后，如何让日历和分页显示成中文的？

版本如下
ant-design-pro@6.0.0-beta
Umi v4.0.34

**Comment by hfpp2012copy** [comment]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/39046778/208358894-e24eef44-6d24-4f02-b914-7095a761b06d.png">

config.ts 中的 locale 配成中文的呀 https://www.qiuzhi99.com/playlists/antdpro-prisma.html

**Comment by ideaviewes** [comment]
配置过locale后，控制台全部在报错
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/5431843/208614664-3a835a86-ead8-4d38-b76a-31afbdf762b1.png">
我这个项目不需要国际化，只需要都显示中文就可以了。

**Comment by hfpp2012copy** [comment]
> 配置过locale后，控制台全部在报错 <img alt="image" width="1070" src="https://user-images.githubusercontent.com/5431843/208614664-3a835a86-ead8-4d38-b76a-31afbdf762b1.png"> 我这个项目不需要国际化，只需要都显示中文就可以了。

<img width="804" alt="image" src="https://user-images.githubusercontent.com/39046778/208615614-2f2c4e4f-c031-4f5b-8d66-345afaa8c101.png">

在 default setting 里设置这个就可以

https://www.qiuzhi99.com/playlists/antdpro-prisma.html

**Comment by ideaviewes** [comment]
好的，谢谢，我买过您的课，前年5.0刚出的时候

**Comment by shanzhaozhen** [comment]
> ### 🧐 问题描述 | Problem description
> 关掉i18n后，如何让日历和分页显示成中文的？
> 
> 版本如下 [ant-design-pro@6.0.0-beta](mailto:ant-design-pro@6.0.0-beta) Umi v4.0.34

`config.ts` 加入下面这段配置就行

```
 /**
   * @name moment2dayjs 插件
   * @description 将项目中的 moment 替换为 dayjs
   * @doc https://umijs.org/docs/max/moment2dayjs
   */
  moment2dayjs: {
    preset: 'antd',
    plugins: ['duration'],
  },
```

**Comment by dlwstrong** [comment]
@shanzhaozhen 
config.ts里有这一部分，接下来该咋弄呢？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


在 `config.ts` 文件中可以找到如下代码段：

```js
import { Settings as LayoutSettings } from '@ant-design/pro-layout';

type WithFalse<T> = {
  [P in keyof T]?: T[P] | false;
};

export default {
  // ........... 一些其他的配置
  layout: {
        // ........... 其他的配置
        locale: false, // 国际化配置, 默认为true
      },
};
```

在 `layout` 字段下加上如下代码配置即可：

```js
import { Settings as LayoutSettings } from '@ant-design/pro-layout';

type WithFalse<T> = {
  [P in keyof T]?: T[P] | false;
};

export default {
  // .................. 其他配置
  layout: {
        // ........... 其他的配置
        locale: {
          language: 'zh-CN', // zh-CN表示设置语言是中文
        },
      },
};
``` 

具体可参考官方文档：

- ProLayout 组件：https://procomponents.ant.design/components/layout#%E5%9B%BD%E9%99%85%E5%8C%96
- locale配置项：https://procomponents.ant.design/components/layout#locale
