### ISSUE TITLE
🐛 [BUG] Request 使用默认method时不传递后还是取用’GET‘

### ISSUE THREAD

**Issue by GuanErShuiShou** [ant-design/ant-design-pro#10457]
### 🐛 bug 描述

在`config`设置了`request->method`的默认值，`plugin-request`还是默认没值的时候取用了`get`

### 📷 复现步骤 | Recurrence steps

直接可复现

### 🏞 期望结果 | Expected results
优先取用 `config` 配置中 然后再取用默认值 `get`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 6.0
- umi 版本 4.0.39
- 浏览器环境 chorme
- 开发环境 [e.g. mac OS] win

**Comment by GuanErShuiShou** [comment]
@chenshuai2144 能给看看嘛这个打算修复嘛

**Comment by GuanErShuiShou** [comment]
@chenshuai2144 app.tsx中设置了method：post不生效还是默认取用get

**Comment by chenshuai2144** [comment]
在HTTP请求中，当不指定HTTP方法时，通常默认为使用"GET"方法。这意味着如果您没有明确指定HTTP方法，那么服务器会默认为您使用"GET"方法来处理请求。

例如，如果您在浏览器中输入URL并按回车键，则浏览器将默认使用"GET"方法向服务器发送请求。另外，如果您在使用某些HTTP客户端库或工具时没有指定HTTP方法，则它们可能会默认使用"GET"方法。


你有可能是插件中设置了默认覆盖，检查一下 app.tsx  试试 


```
/** 退出登录接口 POST /api/login/outLogin */
export async function outLogin(options?: { [key: string]: any }) {
  return request<Record<string, any>>('/api/login/outLogin', {
    method: 'POST',
    ...(options || {}),
  });
}

```

**Comment by GuanErShuiShou** [comment]
> 在HTTP请求中，当不指定HTTP方法时，通常默认为使用"GET"方法。这意味着如果您没有明确指定HTTP方法，那么服务器会默认为您使用"GET"方法来处理请求。
> 
> 例如，如果您在浏览器中输入URL并按回车键，则浏览器将默认使用"GET"方法向服务器发送请求。另外，如果您在使用某些HTTP客户端库或工具时没有指定HTTP方法，则它们可能会默认使用"GET"方法。
> 
> 你有可能是插件中设置了默认覆盖，检查一下 app.tsx 试试
> 
> ```
> /** 退出登录接口 POST /api/login/outLogin */
> export async function outLogin(options?: { [key: string]: any }) {
>   return request<Record<string, any>>('/api/login/outLogin', {
>     method: 'POST',
>     ...(options || {}),
>   });
> }
> ```
我在app.tsx中设置覆盖了默认值为post但是默认值使用的还是get

![image](https://user-images.githubusercontent.com/34082148/219285287-1276f551-67c7-44e0-9ccd-f5b6cd64c04e.png)

**Comment by XSmarter** [comment]
+1

**Comment by chenshuai2144** [comment]
这是errorconfig ！

<img width="948" alt="image" src="https://user-images.githubusercontent.com/8186664/219285512-8b65c999-8794-47e3-8861-571cf4571bfc.png">

看这个文档

https://umijs.org/docs/max/request#requestinterceptors

**Comment by GuanErShuiShou** [comment]
> 这是errorconfig ！
> 
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/8186664/219285512-8b65c999-8794-47e3-8861-571cf4571bfc.png">
> 
> 看这个文档
> 
> https://umijs.org/docs/max/request#requestinterceptors

这个只是名字交errorconfig,我也可以叫request本质是`export const request`中的配置，只是当时参照官方迁移到v6版本就没有整改里面放的是整个request的配置
