### ISSUE TITLE
🐛 [BUG] 执行删除国际化命令报错

### ISSUE THREAD

**Issue by ZebraSu** [ant-design/ant-design-pro#10452]
### 🐛 bug 描述

执行 `i18n-remove` 终端报错 `Error: Failed to load config "prettier" to extend from.`

### 📷 复现步骤 | Recurrence steps

1、执行 `pro create ant-app`
2、选择 umi4
3、执行 `yarn install`
4、执行 `i18n-remove`
5、终端报错 `Error: Failed to load config "prettier" to extend from.`

### 🏞 期望结果 | Expected results

删除国际化相关配置

### © 版本信息

 - ant-design/pro-cli": "^2.1.0"
- umi 版本 umi4
- 浏览器环境 Chrome 
- 开发环境  mac OS

### 🚑 其他信息

package.json

```
{
  "name": "ant-design-pro",
  "version": "6.0.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 max build",
    "build": "max build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "max setup",
    "jest": "jest",
    "lint": "npm run lint:js && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src ",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"**/**.{js,jsx,tsx,ts,less,md,json}\" --end-of-line auto",
    "openapi": "max openapi",
    "prepare": "husky install",
    "prettier": "prettier -c --write \"**/**.{js,jsx,tsx,ts,less,md,json}\"",
    "preview": "npm run build && max preview --port 8000",
    "record": "cross-env NODE_ENV=development REACT_APP_ENV=test max record --scene=login",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev max dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev max dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev max dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev max dev",
    "test": "jest",
    "test:coverage": "npm run jest -- --coverage",
    "test:update": "npm run jest -- -u",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": ["prettier --write"]
  },
  "browserslist": ["> 1%", "last 2 versions", "not ie <= 10"],
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.3.37",
    "@ant-design/use-emotion-css": "1.0.4",
    "@umijs/route-utils": "^2.1.3",
    "antd": "^5.0.0",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.6.4",
    "rc-util": "^5.24.4",
    "react": "^18.0.0",
    "react-dev-inspector": "^1.8.1",
    "react-dom": "^18.0.0",
    "react-helmet-async": "^1.3.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@testing-library/react": "^13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.14",
    "@types/history": "^4.7.11",
    "@types/jest": "^29.2.1",
    "@types/lodash": "^4.14.186",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.5",
    "@umijs/lint": "^4.0.34",
    "@umijs/max": "^4.0.33",
    "cross-env": "^7.0.3",
    "eslint": "^8.0.0",
    "express": "^4.18.2",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "jest": "^29.2.2",
    "jest-environment-jsdom": "^29.2.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.7.1",
    "swagger-ui-dist": "^4.14.2",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4",
    "umi-presets-pro": "^2.0.0"
  },
  "engines": { "node": ">=12.0.0" }
}

```

【报错信息】
![image](https://user-images.githubusercontent.com/7994044/208362096-e34750ca-1a66-4159-983c-a161916524ef.png)

**Comment by ZebraSu** [comment]
执行 `yarn add eslint-config-prettier`
 `yarn add eslint-plugin-unicorn` 解决

**Comment by meihaoGit** [comment]
复现步骤 | Recurrence steps 相同
终端报错
Error: .eslintrc.js » /front-end/ant-app-v6/node_modules/@umijs/lint/dist/config/eslint/index.js:
        Environment key "es2022" is unknown

这个怎么解决?

**Comment by meihaoGit** [comment]
![image](https://user-images.githubusercontent.com/7076597/208427468-73132b96-b29d-4a5a-854c-a0d1f39db667.png)

**Comment by goddesses98** [comment]
node_modules/@umijs/lint/dist/config/eslint/index.js
// es2022: true 

这样能解决问题, 目前应该是依赖的 eslint 有版本问题

**Comment by wudalei** [comment]
请问官方脚手架新建项目什么时候能修复这个问题呢？

**Comment by helloJincheng** [comment]
执行 `yarn add eslint-config-prettier --dev
yarn add eslint-plugin-unicorn --dev `
然后修改node_modules/@umijs/lint/dist/config/eslint/index.js文件注释
`// es2022: true`可以解决问题

**Comment by PowerOfLov** [comment]
@helloJincheng ，抱歉我刚刚接触前端框架，请问这里您提到的“然后修改node_modules/@umijs/lint/dist/config/eslint/index.js文件注释”中文件注释是什么意思，我不明白应该怎么操作才算有效？是直接在文件中写入注释“// es2022: true”吗？

此外，在 env 中本身有 es2022:true 的语句，我尝试了改成 es2021:true，发现可以正常执行国家化移除，但在前端界面中的侧边栏内容也跟着被移除了。

原文件中的内容如下：
``` js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// src/config/eslint/index.ts
var import_recommended = __toESM(require("./rules/recommended"));
var import_setup = require("./setup");
module.exports = {
  parser: require.resolve("@babel/eslint-parser"),
  plugins: ["react", "react-hooks"],
  settings: {
    react: {
      version: "detect"
    }
  },
  env: {
    browser: true,
    node: true,
    es2022: true,
    jest: true
  },
  rules: import_recommended.default,
  overrides: [
    {
      parser: require.resolve("@typescript-eslint/parser"),
      plugins: ["@typescript-eslint/eslint-plugin"],
      files: ["**/*.{ts,tsx}"],
      rules: import_recommended.typescript
    },
    {
      settings: {
        jest: {
          version: detectJestVersion()
        }
      },
      files: ["**/*.{test,spec,unit,e2e}.{ts,tsx,js,jsx}"],
      plugins: ["jest"],
      rules: import_recommended.jest
    }
  ],
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    babelOptions: {
      babelrc: false,
      configFile: false,
      browserslistConfigFile: false,
      presets: [require.resolve("@umijs/babel-preset-umi")]
    },
    requireConfigFile: false
  }
};
function detectJestVersion() {
  try {
    const pkg = require.resolve("jest/package.json", {
      paths: [process.cwd()]
    });
    return require(pkg).version;
  } catch {
    return 29;
  }
}
```

**Comment by kisslove** [comment]
运行 i18n-remove 两个问题：
第一个：eslint的版本问题，可以尝试注释项目中.eslint.js的扩展部分跳过此错误。
第二个：会直接把默认的菜单配置移除掉,可以尝试在路由配置文件中加上name字段

**Comment by dlwstrong** [comment]
@PowerOfLov
这个问题最后该如何解决呢？

**Comment by dwyanedeng123** [comment]
> @helloJincheng ，抱歉我刚刚接触前端框架，请问这里您提到的“然后修改node_modules/@umijs/lint/dist/config/eslint/index.js文件注释”中文件注释是什么意思，我不明白应该怎么操作才算有效？是直接在文件中写入注释“// es2022: true”吗？
> 
> 此外，在 env 中本身有 es2022:true 的语句，我尝试了改成 es2021:true，发现可以正常执行国家化移除，但在前端界面中的侧边栏内容也跟着被移除了。
> 
> 原文件中的内容如下：
> 
> ```js
> var __create = Object.create;
> var __defProp = Object.defineProperty;
> var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
> var __getOwnPropNames = Object.getOwnPropertyNames;
> var __getProtoOf = Object.getPrototypeOf;
> var __hasOwnProp = Object.prototype.hasOwnProperty;
> var __copyProps = (to, from, except, desc) => {
>   if (from && typeof from === "object" || typeof from === "function") {
>     for (let key of __getOwnPropNames(from))
>       if (!__hasOwnProp.call(to, key) && key !== except)
>         __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
>   }
>   return to;
> };
> var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
>   // If the importer is in node compatibility mode or this is not an ESM
>   // file that has been converted to a CommonJS file using a Babel-
>   // compatible transform (i.e. "__esModule" has not been set), then set
>   // "default" to the CommonJS "module.exports" for node compatibility.
>   isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
>   mod
> ));
> 
> // src/config/eslint/index.ts
> var import_recommended = __toESM(require("./rules/recommended"));
> var import_setup = require("./setup");
> module.exports = {
>   parser: require.resolve("@babel/eslint-parser"),
>   plugins: ["react", "react-hooks"],
>   settings: {
>     react: {
>       version: "detect"
>     }
>   },
>   env: {
>     browser: true,
>     node: true,
>     es2022: true,
>     jest: true
>   },
>   rules: import_recommended.default,
>   overrides: [
>     {
>       parser: require.resolve("@typescript-eslint/parser"),
>       plugins: ["@typescript-eslint/eslint-plugin"],
>       files: ["**/*.{ts,tsx}"],
>       rules: import_recommended.typescript
>     },
>     {
>       settings: {
>         jest: {
>           version: detectJestVersion()
>         }
>       },
>       files: ["**/*.{test,spec,unit,e2e}.{ts,tsx,js,jsx}"],
>       plugins: ["jest"],
>       rules: import_recommended.jest
>     }
>   ],
>   parserOptions: {
>     ecmaFeatures: {
>       jsx: true
>     },
>     babelOptions: {
>       babelrc: false,
>       configFile: false,
>       browserslistConfigFile: false,
>       presets: [require.resolve("@umijs/babel-preset-umi")]
>     },
>     requireConfigFile: false
>   }
> };
> function detectJestVersion() {
>   try {
>     const pkg = require.resolve("jest/package.json", {
>       paths: [process.cwd()]
>     });
>     return require(pkg).version;
>   } catch {
>     return 29;
>   }
> }
> ```



> @helloJincheng ，抱歉我刚刚接触前端框架，请问这里您提到的“然后修改node_modules/@umijs/lint/dist/config/eslint/index.js文件注释”中文件注释是什么意思，我不明白应该怎么操作才算有效？是直接在文件中写入注释“// es2022: true”吗？
> 
> 此外，在 env 中本身有 es2022:true 的语句，我尝试了改成 es2021:true，发现可以正常执行国家化移除，但在前端界面中的侧边栏内容也跟着被移除了。
> 
> 原文件中的内容如下：
> 
> ```js
> var __create = Object.create;
> var __defProp = Object.defineProperty;
> var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
> var __getOwnPropNames = Object.getOwnPropertyNames;
> var __getProtoOf = Object.getPrototypeOf;
> var __hasOwnProp = Object.prototype.hasOwnProperty;
> var __copyProps = (to, from, except, desc) => {
>   if (from && typeof from === "object" || typeof from === "function") {
>     for (let key of __getOwnPropNames(from))
>       if (!__hasOwnProp.call(to, key) && key !== except)
>         __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
>   }
>   return to;
> };
> var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
>   // If the importer is in node compatibility mode or this is not an ESM
>   // file that has been converted to a CommonJS file using a Babel-
>   // compatible transform (i.e. "__esModule" has not been set), then set
>   // "default" to the CommonJS "module.exports" for node compatibility.
>   isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
>   mod
> ));
> 
> // src/config/eslint/index.ts
> var import_recommended = __toESM(require("./rules/recommended"));
> var import_setup = require("./setup");
> module.exports = {
>   parser: require.resolve("@babel/eslint-parser"),
>   plugins: ["react", "react-hooks"],
>   settings: {
>     react: {
>       version: "detect"
>     }
>   },
>   env: {
>     browser: true,
>     node: true,
>     es2022: true,
>     jest: true
>   },
>   rules: import_recommended.default,
>   overrides: [
>     {
>       parser: require.resolve("@typescript-eslint/parser"),
>       plugins: ["@typescript-eslint/eslint-plugin"],
>       files: ["**/*.{ts,tsx}"],
>       rules: import_recommended.typescript
>     },
>     {
>       settings: {
>         jest: {
>           version: detectJestVersion()
>         }
>       },
>       files: ["**/*.{test,spec,unit,e2e}.{ts,tsx,js,jsx}"],
>       plugins: ["jest"],
>       rules: import_recommended.jest
>     }
>   ],
>   parserOptions: {
>     ecmaFeatures: {
>       jsx: true
>     },
>     babelOptions: {
>       babelrc: false,
>       configFile: false,
>       browserslistConfigFile: false,
>       presets: [require.resolve("@umijs/babel-preset-umi")]
>     },
>     requireConfigFile: false
>   }
> };
> function detectJestVersion() {
>   try {
>     const pkg = require.resolve("jest/package.json", {
>       paths: [process.cwd()]
>     });
>     return require(pkg).version;
>   } catch {
>     return 29;
>   }
> }
> ```

我也会自动移除侧边栏，你最后怎么解决的？

**Comment by xuzhougeng** [comment]
@dlwstrong @dwyanedeng123  

简单的说就是，eslint跟当前的ant design pro不合。目前的解决方案总是有问题，会改掉route.tsx文件

这是修改前的route.tsx文件

```tsx
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './User/Login',
      },
    ],
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      {
        path: '/admin',
        redirect: '/admin/sub-page',
      },
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        component: './Admin',
      },
    ],
  },
  {
    name: 'list.table-list',
    icon: 'table',
    path: '/list',
    component: './TableList',
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    path: '*',
    layout: false,
    component: './404',
  },
];
```

这是修改后的文件

```tsx
export default [
  { path: '/user', layout: false, routes: [{ path: '/user/login', component: './User/Login' }] },
  { path: '/welcome', icon: 'smile', component: './Welcome' },
  {
    path: '/admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      { path: '/admin', redirect: '/admin/sub-page' },
      { path: '/admin/sub-page', component: './Admin' },
    ],
  },
  { icon: 'table', path: '/list', component: './TableList' },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];
```

对比会发现，中间少了好多好多东西。所以，大家还是退回到UMI v3吧。

**Comment by xinxinClean** [comment]
我也遇到了

**Comment by YOOYY** [comment]
所以目前为止,这个问题还没修复吗?

**Comment by kisslove** [comment]
@YOOYY 我的解决方法看我上面的方式。

**Comment by 5201314999** [comment]
按上面的方式处理了后运行还是报错

**Comment by 5201314999** [comment]
日期问题已经解决 antd v5 手工 import 'dayjs/locale/zh-cn'; umi4 配置无效

**Comment by Xiaofeng05** [comment]
> 执行 `yarn add eslint-config-prettier --dev yarn add eslint-plugin-unicorn --dev ` 然后修改node_modules/@umijs/lint/dist/config/eslint/index.js文件注释 `// es2022: true`可以解决问题

![image](https://github.com/ant-design/ant-design-pro/assets/84329269/1263339b-b318-4028-b305-e9a3f2523075)
没删干净是怎么回事

**Comment by JuvenileQ** [comment]
注释掉ESLint配置文件的拓展试试。（我是重新安装的依赖，然后注释掉的就可以了）
![image](https://github.com/ant-design/ant-design-pro/assets/39209399/7720665c-bc2f-4a15-8131-728f6575ffac)

**Comment by hateStudyy** [comment]
> 执行 `yarn add eslint-config-prettier --dev yarn add eslint-plugin-unicorn --dev ` 然后修改node_modules/@umijs/lint/dist/config/eslint/index.js文件注释 `// es2022: true`可以解决问题

遇到两次这个bug了 把 es2022: true 这行注释掉就行了（官方什么时候修复啊！）

**Comment by jwaychen33** [comment]
> 尝试

为什么我在路由加了name也反应呀

**Comment by XunHua2023** [comment]
> 
按这个方法解决了，谢谢

**Comment by yanqi17118357** [comment]
把node_modules删掉执行没有报错

**Comment by ideaviewes** [comment]
这都4202年了，还不解决这个bug吗

**Comment by Ray-56** [comment]
已经解决了嘛？有人知道么。我用了新版还是同样的问题

**Comment by mylc2010** [comment]
> 已经解决了嘛？有人知道么。我用了新版还是同样的问题

新版也有这个问题，还是一样的 yarn add eslint-config-prettier --dev yarn add eslint-plugin-unicorn --dev 哈，如果提示es2022有问题，跟上面那个一样注释

**Comment by DeMeng33** [comment]
<img width="802" alt="image" src="https://github.com/user-attachments/assets/08b92672-5dd9-4531-aa09-1d9b65807aca">

**Comment by qidaneix** [comment]
阿里裁员裁的ma都不认识了，哪还有功夫维护开源项目啊，散了散了都散了

**Comment by 1812005473** [comment]
怎么25年也没有修复😭
