### ISSUE TITLE
🧐[问题 | question]如何去掉打印info 你知道吗信息

### ISSUE THREAD

**Issue by eden1018** [ant-design/ant-design-pro#10459]
每次yarn install 或者  yarn run build 的时候，总有，

info  - [你知道吗？] 如果要支持低版本浏览器，
info  - [你知道吗？] 如果你有 MPA（多页应用）需求，

我想不让这些信息打印，看如何去解决

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个信息来自于 Yarn 自带的 "为你定制化消息输出" 组件，叫做 `yarnpkg-why`，可以显示有关 yarn 命令的提示信息。

想要去掉这种提示信息，可以通过设置 Yarn 配置文件 `.yarnrc` 来实现：

```
# 禁用常见提示
--no-default-rc
# 禁用yarnpkg-why组件输出
--no-emoji
--no-enable-colors  # optionally may not be writeable
--no-progress-bar
```
注意：使用禁用组件的方式，部分有用的信息也将被隐藏，如某些安全警告等。

另外，如果你只想禁用 "为你定制化消息输出" 组件的 "你知道吗？" 描述信息，可以通过设置环境变量 `YARN_ENABLE_INLINE_BUILD_MSGS`：

```
YARN_ENABLE_INLINE_BUILD_MSGS=false yarn install
```

以上内容仅供参考，具体使用需根据实际情况进行调整。关于 Yarn 的更多信息，可以查看 Yarn 官方文档：https://classic.yarnpkg.com/en/docs/cli/

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题：如何去掉打印info "你知道吗"信息？

解决方案：
要解决这个问题，可以通过修改日志输出级别来控制打印信息的内容。具体步骤如下：

1. 打开项目根目录下的配置文件，比如是`config/config.js`。
2. 在配置文件中找到`chainWebpack`属性，若没有则添加该属性。
3. 在`chainWebpack`中添加如下代码：
   ```javascript
   // 在这里修改日志输出级别为warn，即只打印警告和错误信息
   config.plugin('friendly-errors').tap(([options]) => {
     options.compilationSuccessInfo.messages = options.compilationSuccessInfo.messages.filter(msg =>
       !msg.includes('你知道吗')
     );
     return [options];
   });
   ```
4. 保存配置文件，并重新执行`yarn install`或者`yarn run build`命令。
5. 这样就不会再打印包含"你知道吗"的信息了。

需要注意的是，对于不同的项目或者构建工具，具体的配置文件位置和格式可能会有所不同。以上是一种常见的配置方式，具体可根据项目实际情况进行调整。

希望以上解决方案能够帮到你！如果还有其他问题，请随时提问。

**Comment by CoulTuring** [comment]
Set `DID_YOU_KNOW=none` in .env to prevent the "did-you-know" package from loading.

Because in the source code, there's `process.env.DID_YOU_KNOW !== "none" && require.resolve("@umijs/did-you-know/dist/plugin"),`

**Comment by odingit1** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/124782308/03d57a1f-5b4d-4ed5-ba5e-1c547d7a12bd)
这个info如何去掉，求助
