### ISSUE TITLE
🧐[问题 | question] What is the search engine algorithm of Ant Design Pro?

### ISSUE THREAD

**Issue by ngminhthanh12a3** [ant-design/ant-design-pro#10469]
### 🧐 问题描述 | Problem description

I am designing a documentation web based on Ant Design Pro and react-markdown. What should I do to design a search bar that can help me to search for keywords in my documentation web?

![search](https://user-images.githubusercontent.com/93377382/210088707-783ed896-f643-43e4-96d9-a282d205826c.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案 | Solution

Ant Design Pro provides several ways to implement search algorithm, one of them is using the umi-plugin-lucene package. This package is based on the Lucene search engine algorithm and can be easily integrated with Ant Design Pro.

You can follow these steps to implement the search bar:

1. Install the umi-plugin-lucene package by running the following command in your terminal:

```shell
npm install umi-plugin-lucene --save-dev
```

2. In your config/config.js file, add the following code to enable the plugin:

```javascript
export default {
  plugins: [
    ['umi-plugin-lucene', {
      locales: { // optional, list of locale code for multi-language search, default no multi-language
        en_US: 'en', // code: lang
        zh_CN: 'zh',
      },
      outputPath: 'public/indexes/search', // output dir of indexes, default public
      options: { /* those options below is lunr.js options */ }, // optional, see the detail in https://github.com/olivernn/lunr.js#simple-search
    }],
  ]
}
```

3. Create a search component in your project and import the necessary components:

```javascript
import React, { useState } from 'react';
import { Input, List } from 'antd';
import { connect } from 'dva';
import { Link } from 'umi';

const { Search } = Input;

const SearchBox = ({ dispatch, search }) => {

  const [query, setQuery] = useState('');

  const handleSearch = async (text) => {
    setQuery(text);
    await dispatch({
      type: 'search/searchDocs',
      payload: {
        q: text,
        limit: 10,
        onlyResults: true,
      },
    });
  };

  return (
    <div style={{ marginLeft: '1%' }}>
      <Search
        placeholder="input search text"
        onSearch={handleSearch}
        value={query}
        enterButton
      />
      <List
        dataSource={search.results}
        renderItem={(item) => (
          <List.Item>
            <Link to={item.path}>{item.title}</Link>
          </List.Item>
        )}
      />
    </div>
  );
};

export default connect((state) => ({
  search: state.search,
}))(SearchBox);
```

4. Add the search component to your project where you want to show the search bar.

This should help you implement a search functionality in your documentation web. You can also refer to the umi-plugin-lucene documentation for more options and configurations. 

Here is the documentation of umi-plugin-lucene: https://github.com/umijs/umi-plugin-lucene#readme.

**Comment by ngminhthanh12a3** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> ### 💡 解决方案 | Solution
> Ant Design Pro provides several ways to implement search algorithm, one of them is using the umi-plugin-lucene package. This package is based on the Lucene search engine algorithm and can be easily integrated with Ant Design Pro.
> 
> You can follow these steps to implement the search bar:
> 
> 1. Install the umi-plugin-lucene package by running the following command in your terminal:
> 
> ```shell
> npm install umi-plugin-lucene --save-dev
> ```
> 
> 2. In your config/config.js file, add the following code to enable the plugin:
> 
> ```js
> export default {
>   plugins: [
>     ['umi-plugin-lucene', {
>       locales: { // optional, list of locale code for multi-language search, default no multi-language
>         en_US: 'en', // code: lang
>         zh_CN: 'zh',
>       },
>       outputPath: 'public/indexes/search', // output dir of indexes, default public
>       options: { /* those options below is lunr.js options */ }, // optional, see the detail in https://github.com/olivernn/lunr.js#simple-search
>     }],
>   ]
> }
> ```
> 
> 3. Create a search component in your project and import the necessary components:
> 
> ```js
> import React, { useState } from 'react';
> import { Input, List } from 'antd';
> import { connect } from 'dva';
> import { Link } from 'umi';
> 
> const { Search } = Input;
> 
> const SearchBox = ({ dispatch, search }) => {
> 
>   const [query, setQuery] = useState('');
> 
>   const handleSearch = async (text) => {
>     setQuery(text);
>     await dispatch({
>       type: 'search/searchDocs',
>       payload: {
>         q: text,
>         limit: 10,
>         onlyResults: true,
>       },
>     });
>   };
> 
>   return (
>     <div style={{ marginLeft: '1%' }}>
>       <Search
>         placeholder="input search text"
>         onSearch={handleSearch}
>         value={query}
>         enterButton
>       />
>       <List
>         dataSource={search.results}
>         renderItem={(item) => (
>           <List.Item>
>             <Link to={item.path}>{item.title}</Link>
>           </List.Item>
>         )}
>       />
>     </div>
>   );
> };
> 
> export default connect((state) => ({
>   search: state.search,
> }))(SearchBox);
> ```
> 
> 4. Add the search component to your project where you want to show the search bar.
> 
> This should help you implement a search functionality in your documentation web. You can also refer to the umi-plugin-lucene documentation for more options and configurations.
> 
> Here is the documentation of umi-plugin-lucene: https://github.com/umijs/umi-plugin-lucene#readme.

Thank you so much! I will start to study this plugin.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


You're welcome! Don't hesitate to come back if you have any further questions. Good luck with your project!

**Comment by ngminhthanh12a3** [comment]
@chenshuai2144 I cannot access to umi-plugin-lucene repository now. I think it is private repo.
![image](https://user-images.githubusercontent.com/93377382/223421181-1404e8d6-9e22-4eb5-a9a7-c5f2cc4500a8.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


I apologize for the confusion. It looks like the umi-plugin-lucene repository has been made private. In that case, you can use other search packages like `lunr.js` or `elasticlunr.js` with Ant Design Pro. 

Here are the steps to implement search functionality with `lunr.js`: 

1. Install `lunr.js` package by running the following command in your terminal:

```shell
npm install lunr --save
```

2. Create a search index of your documents by adding the following code in your app.js:

```js
import lunr from 'lunr';
import { history } from 'umi';

let index;

if (typeof window !== 'undefined') {
  index = lunr(function () {
    this.ref('path');
    this.field('title');
    this.field('content');

    // Add your documents to the index
    const documents = [
      { path: '/', title: 'Home', content: 'Welcome to our documentation website' },
      { path: '/getting-started', title: 'Getting Started', content: 'Learn how to start using our product' },
      { path: '/api', title: 'API', content: 'Find all the available APIs and their parameters' },
      // add more documents as necessary
    ];

    documents.forEach((doc) => {
      this.add({
        path: doc.path,
        title: doc.title,
        content: doc.content,
      });
    });
  });
}

export function search(query) {
  if (!query || !index) {
    return [];
  }

  // Perform search on the index
  const results = index.search(query);

  // Map the search results to the document objects
  return results.map((result) => {
    const doc = documents.find((d) => d.path === result.ref);
    return {
      path: doc.path,
      title: doc.title,
      snippet: result.matchData.metadata.content.length > 0 ? result.matchData.metadata.content[0].snippet : '',
    };
  });
}

// Redirect to the document page on search
export function onSearch(value) {
  const results = search(value);
  if (results.length > 0) {
    const result = results[0];
    history.push(result.path);
  }
}
```

3. Create a search bar component:

```js
import React, { useState } from 'react';
import { Input, List } from 'antd';
import { onSearch } from '@/app';
import { Link } from 'umi';

const { Search } = Input;

export default function SearchBar() {
  const [query, setQuery] = useState('');

  function handleSearch(value) {
    setQuery(value);
    onSearch(value);
  }

  return (
    <Search
      placeholder="Search"
      onSearch={handleSearch}
      value={query}
      enterButton
    />
  );
}
```

4. Use the search bar component in your project wherever you need it.

This implementation uses `lunr.js` package and the search functionality can be added without any third-party plugin. You can also customize the search index and search bar component according to your needs.
