### ISSUE TITLE
发布上线后如何配置服务端API域名

### ISSUE THREAD

**Issue by Sayi** [ant-design/ant-design-pro#1046]
你好，参考[和服务端进行交互](https://pro.ant.design/docs/server-cn)，本地环境既可以从mock走，也可以与服务器交互。但是构建发布后，不知道如何制定服务端域名？(查阅了[构建和发布文档](https://pro.ant.design/docs/deploy-cn)，并没有这一块内容)

比如，构建后ant-pro前端页面的地址为：
```
http://f2e.xxx.com/index.html
默认内部api调用地址为http://f2e.xxx.com/api/login
```
服务端部署好后，接口地址为：
```
http://server.xxx.com/api/login
```
所以如何配置服务端域名server.xxx.com？使默认请求地址指向服务端？需要在前端服务器nginx上配置代理才行吗？

期待回复。

**Comment by afc163** [comment]
服务端不需要单独起域名，静态文件和接口统一用一个域名。

**Comment by Sayi** [comment]
好吧，我只是不希望前端和服务端部署在同一个地方。谢谢了。

**Comment by kunhour** [comment]
使用Nginx

**Comment by slamgundam** [comment]
@afc163 
我的也是！
想要前端跟服务端部署在不同的網域下

我目前也是沒解...

**Comment by chenshuai2144** [comment]
反向代理了解一下。可以问问你们的运维

**Comment by guoyangyang666** [comment]
这个问题解决了吗？我也有相同的问题

**Comment by slamgundam** [comment]
在 Nginx 的 網站.conf 檔案設定 proxy_pass 就可以了

我是在本地端測試，若正式發布，網址要改成正式網址

`location /api {
        proxy_pass http://XXXX.localhost;
    }`

**Comment by guoyangyang666** [comment]
好使了，太谢谢你了

**Comment by haywaa** [comment]
静态资源走CDN，API请求不走CDN，如何配置API调用的域名

**Comment by jiangzm** [comment]
+1 有同样的问题。
人家的需求就是要配置不同环境API域名，然后被要求静态资源和后台部署到一起，或者使用代理。
咱能不能有点解决问题的精神，别碰到问路的就让绕着走。前端部署到CDN和后台分开很正常啊，不同环境使用不同的域名也很正常啊，为啥一定要反向代理呢。

@Sayi 我目前做法是根据环境来设置`umi-request` 配置参数 `prefix`, 在config配置项找了一圈没有相关联的配置项。

**Comment by jiangzm** [comment]
> 反向代理了解一下。可以问问你们的运维

装啥呢

**Comment by gaspire** [comment]
> 反向代理了解一下。可以问问你们的运维
静态资源和后台API分开部署，现在是很正常的。装啥呢

**Comment by DestinyXie** [comment]
同样遇到，改本地的umi-request模块那个dist/index.es.js
fetch(this.url, this.options); 
=>
fetch(this.options.api ? this.options.api + this.url : this.url, this.options);
给umi-request配全局options的时候配上你自己的接口地址api就行了

**Comment by h1nson** [comment]
请问有人解决了吗？

**Comment by chenshuai2144** [comment]
建议用容器 比如 nginx 之类的解决，前端不要硬编码

**Comment by Kennytian** [comment]
这个问题解决了吗？我也有相同的问题

**Comment by steeeeps** [comment]
专职开发前端的同学理解不到楼主的痛点啊。

网上找一圈都是在proxy下配置dev的代理转发，也不看注释写的清清楚楚的只是在开发模式下使用，哈哈...

下面说说我得方法吧：

**环境ant design pro v6.0.0**

1. 利用[环境变量](https://pro.ant.design/zh-cn/docs/environment-manage/)配置开发模式和产品模式的api 地址(其他模式类似)，以`dev`和`prod`为例，**仅支持typescript**：
config.dev.ts
```
import { defineConfig } from '@umijs/max';
export default defineConfig({
  define: {
    BASE_URL: 'https://api.dev.com', // API地址
  },
});

```
config.prod.ts
```
import { defineConfig } from '@umijs/max';
export default defineConfig({
  define: {
    BASE_URL: 'https://api.prod.com', // API地址
  },
});

```
2. 在`typings.d.ts`中修改和添加以下内容：
```
declare const REACT_APP_ENV: 'test' | 'dev' | 'pre' | 'prod' | false;
declare const BASE_URL: string
```
3. 利用[拦截器](https://pro.ant.design/zh-cn/docs/request/)功能自定义拦截器，修改服务器地址或者其他需要传到服务器的数据，自定义一个`requestConfig.ts`文件。
```
import type { RequestConfig } from '@umijs/max';
/**
 * 自定义请求前拦截,根据环境变量修改baseUrl和token等信息
 * @param url
 * @param options
 * @returns
 */
export const beforeRequestInterceptor = (url: string, options: RequestConfig) => {

  const authHeader = { token: 'token' };
  return {
    url: `${BASE_URL}${url}`,
    options: { ...options, interceptors: true, headers: authHeader },
  };
};

```

4. 在`app.tsx `中引入上一文件，并修改`request`的配置：
```
export const request = {
  ...errorConfig,
  requestInterceptors: [
    beforeRequestInterceptor
  ]
};
```

5. 在`package.json script` 节点中添加产品模式编译脚本：
```
"build:prod": "cross-env UMI_ENV=prod max build",
```
6. 本地开发时使用`npm run start:no-mock`命令。

7. 产品上线编译时使用`npm run build:prod`命令。

**Comment by tashuo** [comment]
楼上第4步也可以将`BASE_URL`配置为`baseURL`: 

```typescript
# app.tsx
/**
 * @name request 配置，可以配置错误处理
 * 它基于 axios 和 ahooks 的 useRequest 提供了一套统一的网络请求和错误处理方案。
 * @doc https://umijs.org/docs/max/request#配置
 */
export const request = {
  ...errorConfig,
  baseURL: BASE_URL, // 增加这行
};
```

**Comment by lusfire** [comment]
今天我也遇到这个问题了，前面找了一圈没有资料，看了好久还是回到这里才搞明白，用反向代理接口才是最佳解决方案，本来就是为了跨域才这样设计的，前端人员不要画蛇添足了，只管开发就行，等部署的时候配置一下接口的代理就好了 @chenshuai2144 @slamgundam 已经说的很清楚了。我用的nginx，添加了一行
location /api { 
	proxy_pass http://192.168.1.87:8084;
}
这里是把所有以/api开头的请求（在F12里看到的是http://localhost:8080/api/xxx）转发到 http://192.168.1.87:8084/api/xxx，这里转发的地址不限于本机或者局域网内，所有能连通的地址都可以

**Comment by lusfire** [comment]
今天我也遇到这个问题了，前面找了一圈没有资料，看了好久还是回到这里才搞明白，用反向代理接口才是最佳解决方案，本来就是为了跨域才这样设计的，前端人员不要画蛇添足了，只管开发就行，等部署的时候配置一下接口的代理就好了 @chenshuai2144 @slamgundam 已经说的很清楚了。我用的nginx，添加了一行
location /api {
proxy_pass http://192.168.1.87:8084/;
}
这里是把所有以/api开头的请求（在F12里看到的是‘http://localhost:8080/api/xxx’）转发到‘http://192.168.1.87:8084/api/xxx’，这里转发的地址不限于本机或者局域网内，所有能连通的地址都可以。

**Comment by lusfire** [comment]
今天我也遇到这个问题了，前面找了一圈没有资料，看了好久还是回到这里才搞明白，用反向代理接口才是最佳解决方案，本来就是为了跨域才这样设计的，前端人员不要画蛇添足了，只管开发就行，等部署的时候配置一下接口的代理就好了 @chenshuai2144 @slamgundam 已经说的很清楚了。我用的nginx，添加了下面这行配置，将所有的接口访问代理到另一台服务器上
location /api {
    proxy_pass http://192.168.1.87:8084/;
}
这里是把所有以/api开头的请求（在F12里看到的是[http://localhost:8080/api/xxx]）转发到[http://192.168.1.87:8084/api/xxx]，这里转发的地址不限于本机或者局域网内，所有能连通的地址都可以。

**Comment by lusfire** [comment]
今天我也遇到这个问题了，前面找了一圈没有资料，看了好久还是回到这里才搞明白，用反向代理接口才是最佳解决方案，本来就是为了跨域才这样设计的，前端人员不要画蛇添足了，只管开发就行，等部署的时候配置一下接口的代理就好了 @chenshuai2144 @slamgundam 已经说的很清楚了。我用的nginx，添加了下面这行配置，将所有的接口访问代理到另一台服务器上
location /api {
    proxy_pass http://192.168.1.87:8084;
}
这里是把所有以/api开头的请求（在F12里看到的是[http://localhost:8080/api/xxx]）转发到[http://192.168.1.87:8084/api/xxx]，这里转发的地址不限于本机或者局域网内，所有能连通的地址都可以。

**Comment by lusfire** [comment]
今天我也遇到这个问题了，文档的部署章节没有仔细看，看了好久还是回到这里才搞明白，用反向代理接口才是最佳解决方案，本来就是为了跨域才这样设计的，前端人员不要画蛇添足了，只管开发就行，等部署的时候配置一下接口的代理就好了 @chenshuai2144 @slamgundam 已经说的很清楚了。我用的nginx，添加了下面这行配置，将所有的接口访问代理到另一台服务器上
location /api {
proxy_pass http://192.168.1.87:8084;
}
这里是把所有以/api开头的请求（在F12里看到的是[http://localhost:8080/api/xxx]）转发到[http://192.168.1.87:8084/api/xxx]，这里转发的地址不限于本机或者局域网内，所有能连通的地址都可以。
附：官网部署章节的说明 [https://pro.ant.design/zh-CN/docs/deploy#使用-nginx]

**Comment by IOLOII** [comment]
并不是说不能配置反向代理，而是在之前做到的项目中有通过使用不同的env配置文件，实现打包时差异出 开发 | 生产环境，这里的话只有看见 max build，还在查找是否官方支持读取env文件的配置方式
https://github.com/ant-design/ant-design-pro/issues/10239#issuecomment-1861232884

**Comment by IOLOII** [comment]
[jiangzm](https://github.com/jiangzm) 哈喽，想问下你后面找到类似的解决方法了吗？在官方模板中使用了react_app_env 和unmi_env两个环境变量，但是貌似不支持索引到对应的环境变量的.env文件下的配置

**Comment by IOLOII** [comment]
调试后，找到解决方法：
先贴图（打包后）
![image](https://github.com/ant-design/ant-design-pro/assets/34856171/06f7c282-07a8-4903-a85f-d1ac51fc94ab)
解决方法：（注意往下看）
```ts
require('dotenv').config({
  // path: `.env.${process.env.NODE_ENV}`,
  path: `.env.development`,
})
```
通过在config文件中使用dotenv插件去加载env文件，注意，这里也有问题：
如果使用环境变量 process.env.NODE_ENV 去动态拼，会发现这个变量要么development要么production，无法根据启动脚本时候 cross-env NODE_ENV=development 这种配置不生效，好像是在执行shell的时候在构建时输出producrion 在开发时输出development，这里如果修改NODE_ENV为其他值，就会发现本身这条指令里的传递NODE_ENV=othervalue 不生效（有兴趣可以试下）

所以我这边取REACT_APP_ENV作为命令行传递的环境变量参数，
```ts
require('dotenv').config({
  // path: `.env.${process.env.NODE_ENV}`,
  // path: `.env.development`,
  path: `.env.${process.env.REACT_APP_ENV}`,
})
```
对应还可以在defineConfig中定义：
```
export default defineConfig({
  define: {
    NODE_ENV:REACT_APP_ENV
  }
})
```

这样的话，就可以分环境变量加载不同的env配置文件了，也实现了不用反向代理直接请求到其他环境变量的服务地址
