### ISSUE TITLE
👑 [需求 | Feature] protable column 设置了initialValue 重置失效

### ISSUE THREAD

**Issue by ycshill** [ant-design/ant-design-pro#10460]
`{
      title: '产品UUID',
      dataIndex: 'uuid',
      ellipsis: true,
      initialValue: '1',
      align: 'center',
      width: 100,
    },`

点击重置 产品UUID 重置不了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的信息，可能是因为 initial value 的使用方式不正确导致的，可以按照以下方式进行使用：

1. 通过 Form.create 创建 form 实例，并在 column 的 render 函数中注入 getFieldDecorator 以渲染表单项。

```javascript
import { Form } from 'antd'

//...

const FormItem = Form.Item

//...

const columns = [
  {
    title: '产品UUID',
    dataIndex: 'uuid',
    ellipsis: true,
    align: 'center',
    width: 100,
    render: (text, record) => (
      <FormItem>
        {getFieldDecorator('uuid', {
          initialValue: record.uuid,
          rules: [
            /* 表单校验规则 */
          ],
        })(
          /* 渲染表单控件 */
        )}
      </FormItem>
    ),
  },
  // ...其他列
]
```

2. 重置表单时，通过 form.resetFields 方法重置表单项，使 initial value 生效。

```javascript
// 假设现在已有 this.props.form 实例，可以在方法中使用：
this.props.form.resetFields(['uuid'])
```

希望这些信息可以帮助您解决问题，如果还有疑问，请与我联系，感谢您的提问。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案：
1. 检查是否正确使用了 Protable 组件，并正确传递了 initialValue 属性。
2. 确保在点击重置按钮时，触发了重置操作的逻辑。

如果以上两点都没有问题，可以尝试以下解决方案：
1. 检查 Protable 组件的版本，确保使用的是最新版本。可以查看 Protable 的官方文档或 github 仓库，了解是否存在 initialValue 重置失效的已知问题，并查看是否有相关的修复。
2. 如果没有找到相关修复，可以尝试使用最新版本的 Protable，或者尝试升级相关依赖版本。
3. 如果问题依然存在，可以尝试手动重置 initialValue 的值。为重置按钮添加点击事件，并在事件处理函数中，将 initialValue 重新设置为想要的初始值。

请注意，在尝试以上解决方案之前，建议先备份你的代码，并确保你已经理解了代码的逻辑和作用。在修改代码之前，建议先在本地进行测试，并确保修改后的代码能够正常工作。
