### ISSUE TITLE
🐛 [BUG]  Dropdown protable overlayStyle 设置top left 第一次不生效

### ISSUE THREAD

**Issue by graphic-tech** [ant-design/ant-design-pro#10466]
### 🐛 bug 描述

<Dropdown  overlayStyle={{ top: copyPoint.copyPoint[1],left: copyPoint.copyPoint[0],}} overlay={menu}  open={showCopy}>
            <ProTable >
                 ....
            onRow={(record, rowIndex) => {
                return {
                  onContextMenu: event => {
                          setCopyPoint({copyPoint: [x, y], index: index})
                    ....
代码逻辑：
               * 触发onContextMenu设置我的Dropdown的位置 第一次Dropdown展示的位置不是setCopyPoint，但是第二次进行onContextMenu时候，overlayStyle里面的top left就是成功的
               * 重新刷新整个protable后，触发onContextMenu来设置setCopyPoint， 第一次Dropdown展示的位置不是setCopyPoint，还是重复以上逻辑，第二次就行
               * 滑动protable到底部后，触发onContextMenu设置setCopyPoint，overlayStyle里面的top left还是不对，第二次就是正确的

### 🏞 期望结果 | Expected results

希望第一次展示Dropdown的时候位置就是setCopyPoint传递的xy

### © 版本信息

- Ant Design Pro 版本:  "antd": "4.23.2",
- umi 版本
- 浏览器环境 Chrome 107.0.5304.110（正式版本） (arm64)
- 开发环境 mac OS Monterey 12.6

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的反馈！根据您的描述，您希望在Dropdown组件展示时，位置能够准确显示setCopyPoint传递的xy。可能是由于组件渲染时的异步渲染问题导致第一次展示时位置不正确。可以尝试在调用setCopyPoint改变状态后添加回调函数，并在回调函数中再次触发Dropdown展示，确保在状态改变完成后再进行组件渲染，例如：

```jsx
import { useRef } from 'react';
...
const dropdownRef = useRef();

onRow={(record, rowIndex) => {
  return {
    onContextMenu: event => {
      setCopyPoint({copyPoint: [x, y], index: index}, () => {
        dropdownRef.current?.rcDropdown?.setPopupVisible(true);
      });
    }
  }
}}
...
<Dropdown 
  ref={dropdownRef}
  overlayStyle={{ top: copyPoint.copyPoint[1],left: copyPoint.copyPoint[0],}} 
  overlay={menu}  
  open={showCopy}>
  <ProTable >...</ProTable>
</Dropdown>
```

另外，建议您检查代码中可能影响到Dropdown位置的其他因素，比如父级组件样式、滚动条等。希望这些信息能对您有所帮助！
