### ISSUE TITLE
问题：pro layout  左侧菜单 如何只允许打开一个子菜单 其他子菜单关闭

### ISSUE THREAD

**Issue by 787022161** [ant-design/ant-design-pro#10464]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by 787022161** [comment]
？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，根据您提供的信息，无法判断具体的前端问题和相关技术栈。请您提供更加具体的问题描述和示例代码，以便我们更好地为您提供解决方案和帮助。谢谢！
