### ISSUE TITLE
props 无法监听页面地址刷新  🐛 [BUG]

### ISSUE THREAD

**Issue by hyzx86** [ant-design/ant-design-pro#10470]
### 📷 复现步骤 | Recurrence steps
我定义了一个组件，它可以接收所有未匹配的路由
![image](https://user-images.githubusercontent.com/15613121/210152253-67b30b5b-f5c0-4f5e-b7d4-d8bd579e2573.png)
``` ts
 useEffect(() => {
 console.log('monitor: pageChanged', props);

},[props])
```
在5.x 版本中 
props 是可以监听地址变化的
但是6.0 版本只能 使用 useLocation 去监听。。
``` ts

  const localtion = useLocation();
 useEffect(() => {
 console.log('monitor: pageChanged', localtion );

},[localtion ])
```

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hyzx86** [comment]
问题不大，卡了很久，分享一下。。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢分享，提供了有用的信息，如果你还有其他问题，欢迎随时提出。

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/api/api#uselocation

import { useLocation } from 'umi';

```
function App() {
  const location = useLocation();
  React.useEffect(() => {
    ga('send', 'pageview');
  }, [location]);
  // ...
}

useAppData
useAppData 返回全局的应用数据。

类型定义如下：


declare function useAppData(): {
  routes: Record<id, Route>;
  routeComponents: Record<id, Promise<React.ReactComponent>>;
  clientRoutes: ClientRoute[];
  pluginManager: any;
  rootElement: string;
  basename: string;
  clientLoaderData: { [routeKey: string]: any };
  preloadRoute: (to: string) => void;
};
```
