### ISSUE TITLE
🧐[问题 | question] v6 app.tsx 中怎么获取isMobile 

### ISSUE THREAD

**Issue by GuanErShuiShou** [ant-design/ant-design-pro#10474]
### 🧐 问题描述 | Problem description

在app.tsx 中怎么获取 `isMobile`和`collapsed`的状态，需要根据状态对布局进行一些操作

**Comment by GuanErShuiShou** [comment]
@chenshuai2144 这个有办法获取嘛

**Comment by XSmarter** [comment]
+1

**Comment by chenshuai2144** [comment]
拿一下屏幕宽度自己算一下
不要在app.tsx 做太多事情，里面最好都是静态配置
