### ISSUE TITLE
🧐[问题 | question]登录后不管进那个界面，刷新下浏览器，就又回到登录界面了，有人清楚是什么情况吗

### ISSUE THREAD

**Issue by qxz123456** [ant-design/ant-design-pro#10477]
### 🧐 问题描述 | Problem description

登录后不管进那个界面，刷新下浏览器，就又回到登录界面了，/api/login/account这个请求是正常的，但是/api/currentUser这个请求404了，怀疑是这个404导致的，但是不知道为啥这个请求404了，有没有大佬帮忙看看

"antd": "^5.0.0",
"@umijs/max": "^4.0.33",
“ant-design-pro”：6.0.0
浏览器 | browser：

**Comment by JackDowson2003** [comment]
你可以尝试加上cookie

**Comment by Ben6501** [comment]
大佬好，问题解决了吗？我也是这种情况，刷新一下就到登录界面了。不过/api/currentUser倒是正常的。

**Comment by qxz123456** [comment]
我的这个问题原因就是因为/api/currentUser 404导致的，但是404这个问题没解决掉，为了调试，我把app.ts里fetchUserInfo这个方法里的catch分支里的代码注释掉了，问题算是暂时解决了。。。。。

**Comment by qxz123456** [comment]
你这个/api/currentUser请求正常的话，可以看下app.ts里layout中的onPageChange那个函数，我项目中这个函数里的代码全是注掉 的，你可以把那几行代码注掉试试

**Comment by Ben6501** [comment]
我的问题解决了，感谢啦~~! 👍

**Comment by Ben6501** [comment]
问题已解决。
app.tsx中fetchUserInfo()调用后端成功，返回前端的数据没接上，导致前端currentUser一直为undefined，调整一下就好了。
![image](https://user-images.githubusercontent.com/15306774/215313770-c925fd3a-9062-4d4b-8513-91c09aa6caeb.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


好的，看来你已经成功解决了问题，很棒！如果帮助到您，请记得采纳答案哦~如果您还有后续问题，请随时提问，我会尽力为您解答。
