### ISSUE TITLE
🐛 [BUG]控制台一直有多个警告

### ISSUE THREAD

**Issue by ZhiMaYiLian** [ant-design/ant-design-pro#10472]
### 🐛 bug 描述
Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.
Warning: [antd: Drawer] `visible` is deprecated which will be removed in next major version, please use `open` instead.
Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.
Warning: [antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly.

### 📷 复现步骤 | Recurrence steps
直接yarn，跑起来就可以在网页控制台看到

### 🏞 期望结果 | Expected results
清楚报错原因和解决方法

### 💻 复现代码 | Recurrence code
https://github.com/ZhiMaYiLian/Web.git

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本: [3.5.0]
- 浏览器环境: Microsoft Edge 版本 108.0.1462.54 
- 开发环境 [windows 11]

**Comment by dogeow** [comment]
这个提示不是很明显吗？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，这些警告信息都是来自于 Ant Design 的库。这些警告意味着你的代码中使用了已经被废弃的 API。所以建议你升级 Ant Design 的版本，以便避免这些警告信息的出现。

你的当前版本是 `Ant Design Pro 5.2.0`，也许升级到最新的版本可以解决这个问题。

如果你在升级后仍然遇到类似的问题，可以查看对应 API 的文档以及 API 的使用方式是否发生了变化。阅读更新日志也很有帮助，可以帮助你了解更新的细节和注意事项。

同时，如果你在使用旧版本的库，也可以查看官方文档或者相应版本的文档，了解如何避免这些警告，或者如何平稳地迁移到新版本。

**Comment by kokman** [comment]
我使用pro命令新创建的项目，也遇到类似的warnings

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，Ant Design 会不断更新和改进，部分 API 会被废弃，建议更新 Ant Design 版本以避免这些警告。

如果您使用的是 Ant Design Pro 创建的项目，可以通过以下命令升级依赖项：

```bash
$ yarn upgrade antd
```

这将自动将项目所依赖的 Ant Design 升级到最新版本，以避免警告。

如果您使用的是手动安装的 Ant Design 库，请确保您的依赖版本是最新的，可以使用以下命令升级：

```bash
$ yarn upgrade antd
```

在升级 Ant Design 后如果仍然遇到类似问题，可以查看对应 API 的文档以及 API 的使用方式是否发生了变化。可以查看更新日志，了解更新的细节和注意事项。

**Comment by chenshuai2144** [comment]
修复了，大家更新版本吧
