### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by Capricair** [ant-design/ant-design-pro#10487]
### 🐛 bug 描述

最新脚手架创建的 ant-design-pro 6 mock接口404

### 📷 复现步骤 | Recurrence steps

1. npm i @ant-design/pro-cli -g
2. pro create myapp
3. tyarn
4. npm run start

### 🏞 期望结果 | Expected results

mock接口正常

### 💻 复现代码 | Recurrence code

无

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本: 4
- 浏览器环境: Chrome 版本 107.0.5304.88（正式版本） （64 位）
- 开发环境: Windows 10 专业版

**Comment by xjchenhao** [comment]
注释掉`/config/proxy.ts`里的`dev: {},`就好了

**Comment by chaojiangcn** [comment]
还是404吧
