### ISSUE TITLE
👑 [需求 | Feature] 正式6版本有没有发布时间点？

### ISSUE THREAD

**Issue by BruceLeePH** [ant-design/ant-design-pro#10481]
大佬们，迫不及待了

**Comment by BruceLeePH** [comment]
sooooooooshit！！！！！！！！！！！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，你的问题不是关于 React 前端问题的。我建议你在相关仓库或社群中问这个问题，那里可能有更多人能够提供有用信息。祝你好运！
