### ISSUE TITLE
在我们首次拉下来去启动使用 npm install 然后 npm run start后没有使用mock数据🐛 [BUG]

### ISSUE THREAD

**Issue by JackDowson2003** [ant-design/ant-design-pro#10489]
### © 版本信息

- Ant Design Pro 版本: [戒指最近最新版]
- Umi v4.0.42
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/87301590/211452150-f12ad9e6-b8ea-48c5-978c-b1c6598eb76a.png)
我们去使用i18n去去除国际化组件时候
会报错
![image](https://user-images.githubusercontent.com/87301590/211452369-e3e4290b-fa08-487e-a08a-630f4ea783c6.png)

**Comment by lhy-innno** [comment]
一样的情况

**Comment by manooog** [comment]
这个问题好久了，官方不修一下？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能与您项目的具体环境有关，因此官方可能不会一次性修复所有用户的问题。但是，您可以尝试以下解决方案：

1. 确认您的 mock 文件夹中是否有正确的.ts文件。

2. 检查您的配置文件（.umirc.ts或config/config.ts）中是否正确配置了 mock 接口。例如：

```tsx
export default {
  mock: {
    exclude: [],
  },
  // ...其他配置
};
```

3. 检查您的项目是否正确继承了 antd-pro 的基础配置。例如：

```tsx
import { defineConfig } from 'umi';

export default defineConfig({
  // ...其他配置
  extend: [
    // antd-pro 基础配置
    // 需要安装 @umijs/preset-ui 插件
    '@umijs/preset-ui',
  ],
});
```

4. 如果您使用的是 TypeScript，可以尝试使用 require() 而不是 import 导入 mock 文件。在项目的根目录下创建 typings.d.ts 文件，并声明 mock 文件的类型。例如：

```tsx
declare module '*.ts' {
  const content: any;
  export default content;
}
```

```tsx
const mockData = require('@/mock/data.ts').default;
```

5. 如果问题仍然存在，请尝试查看您所使用的 Umi 和 antd-pro 版本是否有已知的相关问题并进行升级，或考虑向社区提出问题以获取更多帮助。

希望这些解决方案能帮助您解决问题。如果您需要更多帮助，请随时回复本消息。

**Comment by dongmenghao** [comment]
可以看下是不是 start:dev 命令启动的项目，需要把MOCK=none 去掉。
<img width="830" alt="image" src="https://user-images.githubusercontent.com/10722333/233776231-6d129b6f-9b23-470e-96b2-f0d83ea50e69.png">
