### ISSUE TITLE
🧐[问题 | question] 怎么查看官网预览的项目代码

### ISSUE THREAD

**Issue by Benleie** [ant-design/ant-design-pro#10484]
怎么查看官网预览的项目代码？

本仓库是个模板吧，我clone下来，本地执行npm run start，只能看到两个页面。

那我要在哪里找到线上的项目代码呢
![image](https://user-images.githubusercontent.com/24362871/210956460-d2c3bc47-ad48-427c-94b2-e69eab96f368.png)

**Comment by hpf0532** [comment]
#9057

**Comment by Benleie** [comment]
好的，感谢

**Comment by Benleie** [comment]
all-block分支
