### ISSUE TITLE
从 mock 直接切换到服务端请求?

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-design-pro#1048]
> 从 mock 直接切换到服务端请求#
> 通常来讲只要 mock 的接口和真实的服务端接口保持一致，那么只需要重定向 mock 到对应的服务端接口即可。
> // .roadhogrc.mock.js
> export default {
>   'GET /api/(.*)': 'https://your.server.com/api/',
> };
> 这样你浏览器里这样的接口 http://localhost:8001/api/applications 会被反向代理到 https://your.server.com/api/applications 下。
> 

**按照文档进行了配置，但是请求还是走的 localhost，没有反向代理呢**

```
Request URL:http://localhost:8000/api/rule?no=5555
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:8000
Referrer Policy:no-referrer-when-downgrade

```

**Comment by wuyongdec** [comment]
@valleykid @LKCheng 
`Response {type: "basic", url: "http://localhost:8000/test/", redirected: false, status: 200, ok: true, …}
body
:
ReadableStream
bodyUsed
:
true
headers
:
Headers
__proto__
:
Headers
ok
:
true
redirected
:
false
status
:
200
statusText
:
"OK"
type
:
"basic"
url
:
"http://localhost:8000/test/"
__proto__
:
Response`
按照你们的方法确实 java后台 tomcat 可以收到请求了，status也是200，但是怎么response没有json呢？我用postman 测试是有json的

**Comment by wuyongdec** [comment]
It's my fault . Sorry everybody.

**Comment by Liqiankun** [comment]
@wuyongdec 我的设置了怎么还是不对呢？
