### ISSUE TITLE
🧐[defaultSettings 升级后 primaryColor 变量为colorPrimary 页面主题颜色变为很透明的亮色了，请问如何设置主题颜色]

### ISSUE THREAD

**Issue by egene-huang** [ant-design/ant-design-pro#10486]
### 🧐 问题描述 | Problem description

升级了antd相关依赖后defaultSettings 变更了，根据声明文件修改后 主题变为亮色了，之前的拂晓蓝色没有了 请问如何设置回去呢？

### 💻 示例代码 | Sample code

代码版本：
老版本: 
 "@ant-design/charts": "1.3.5",
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-card": "1.15.3",
    "@ant-design/pro-descriptions": "1.9.6",
    "@ant-design/pro-form": "1.43.5",
    "@ant-design/pro-layout": "6.26.5",
    "@ant-design/pro-table": "2.62.7",
    "antd": "4.18.5",
升级后版本:
    "@ant-design/charts": "1.4.2",
    "@ant-design/icons": "4.8.0",
    "@ant-design/pro-card": "^2.1.8",
    "@ant-design/pro-descriptions": "^2.0.42",
    "@ant-design/pro-form": "^2.5.2",
    "@ant-design/pro-layout": "^7.5.2",
    "@ant-design/pro-table": "^3.2.10",
    "antd": "4.24.7",

另外 umi 版本需要升级吗？是否有兼容问题？目前版本为：
"umi": "3.5.20",

### 🚑 其他信息 | Other information

 "react": "^16.8.6",
  "react-dom": "^16.8.6",

OS: macos m1
Node： 12

浏览器 | browser： chrome 最新版本

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🙋 解决方案 | Solution

## 1. 关于主题颜色变更

你可以利用 `primaryColor` 变量进行主题颜色的配置，通过修改主题颜色的变量来改变页面色调。

首先，在 `defaultSettings.ts` 中找到如下代码：

```typescript
primaryColor: '#52C41A',
```

在这里，我们可以将 `primaryColor` 修改为我们所需要的颜色。如果你需要使用旧版本的拂晓蓝色，可以设置为 `#1890ff`，修改后的代码如下：

```typescript
primaryColor: '#1890ff',
```

## 2. 关于 umi 版本兼容性

根据官方文档，`@ant-design/pro-layout` 当前支持的 `umi` 版本为 `>=3.3.0`，因此你的 `umi` 版本可以直接使用，不需要升级。

## 3. 其他可能需要注意的问题

如果你在修改主题颜色后，发现页面中部分组件颜色并未随之改变，可能需要单独修改这些组件的颜色配置。

例如，在 `layout.tsx` 文件中，可以找到以下代码：

```typescript
<HeaderThemeBar onValuesChange={onValuesChange} />
```

如果你发现该组件颜色未随主题颜色变更，你可以手动设置其样式为：

```css
.ant-pro-header-menu-logo,
.ant-pro-header-right-menu-wrapper,
.ant-pro-header-language-menu,
.ant-pro-header-account,
.ant-pro-header-trigger {
  color: #fff; // 这里设置为你需要的颜色值
}
```

更多关于 antd 主题配置、组件样式修改等内容，可以参考官方文档：

- [Ant Design Pro 中自定义主题和样式](https://pro.ant.design/docs/style-cn)
- [Ant Design 组件样式定制](https://ant.design/docs/react/customize-theme-cn)

**Comment by chenshuai2144** [comment]
可以用 ProConfigProvider
```
import {
  LoginFormPage,
  ProConfigProvider,
  ProFormCaptcha,
  ProFormCheckbox,
  ProFormText,
} from '@ant-design/pro-components';


 <ProConfigProvider
      dark
      token={{
        colorPrimary: '#1890ff',
      }}
    >
      <Page />
    </ProConfigProvider>
```
