### ISSUE TITLE
🐛 [BUG]新建一个项目,好像只要执行了 i18n-remove 就无法看到菜单了.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#10483]
### 🐛 bug 描述

新建一个项目,执行i18n-remove后,菜单无法正常显示.重新添加i18n后依旧无法显示.

### 📷 复现步骤 | Recurrence steps

pro create myapp
yarn install
yarn i18n-remove
yarn start
之后进入页面菜单无显示.
![image](https://user-images.githubusercontent.com/13188169/210935131-7a5c8ece-1b96-4ac7-911e-627b8f12ce7f.png)

### 🏞 期望结果 | Expected results

移除i18n还是能够正常看到菜单.

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by GraciaMeng** [comment]
路由配置加上name字段就有了

**Comment by joesdu** [comment]
> 路由配置加上name字段就有了

好的,感谢,我周一试试.

**Comment by joesdu** [comment]
> 

我看了下路由默认的配置中有name字段啊
![image](https://user-images.githubusercontent.com/13188169/211226152-412baae1-3f87-46ac-9d9d-eb5e9be58f8f.png)

**Comment by joesdu** [comment]
欸,奇怪,这次删掉后,又没问题了.
