### ISSUE TITLE
清除浏览器缓存，路由没有重定向到登录页面？

### ISSUE THREAD

**Issue by zangxiaohui** [ant-design/ant-design-pro#1049]

**Comment by WuJiY** [comment]
我也是的 经常 没登录状态下 路由是过去了，页面 没跳转过去（是不是没刷新） 
![image](https://user-images.githubusercontent.com/183884/37185808-30412cb4-237d-11e8-912d-5ce0944d772e.png)
![image](https://user-images.githubusercontent.com/183884/37185820-42a89824-237d-11e8-9fc8-c6c4650df22f.png)

**Comment by chenshuai2144** [comment]
@WuJiY  你这个是代码报错了,缺了个数据。
做个判断就好了

**Comment by WuJiY** [comment]
是的，这个问题 感觉是 没跳转到login，路由是过去了，但是没刷新，登录拦截是在request.js里做的吗？
