### ISSUE TITLE
👑 [需求 | Feature] app.tsx 不能监听主题色 colorPrimary 的变化

### ISSUE THREAD

**Issue by baiwumm** [ant-design/ant-design-pro#10491]
### 🥰 需求描述 | Requirements description

在 app.tsx 里面使用 useEmotionCss 获取 主题色 colorPrimary，始终获取的都是初始值，不会随着切换 SettingDrawer 变化而变化，但在其他的页面就可以
![image](https://user-images.githubusercontent.com/40554571/211524662-03533678-a619-45e0-bfcd-aea8b23159da.png)

### 🧐 解决方案 | Solution

期望团队能改下这个问题，在 app.tsx 里面获取 useEmotionCss 的值也是最新的

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，很抱歉听到你遇到了这个问题。根据您的描述，我理解到您想要在 app.tsx 文件中监听主题色 colorPrimary 的变化。根据您提供的截图和信息，我建议您可以采用以下解决方案。

1. 在 app.tsx 中使用 useContext 获取主题色：
```typescript
import React, { useContext } from 'react';
import { ThemeContext } from '@emotion/react';

export default function App() {
  const theme = useContext(ThemeContext);

  return (
    <div css={{ backgroundColor: theme.colorPrimary }}>
      {/* your app content */}
    </div>
  );
}
```

通过使用 useContext 构造主题色的 Consumer，它会在主题色发生变化时进行重新渲染。

2. 使用 useEffect 监听主题色变化：
```typescript
import React, { useEffect, useState } from 'react';
import { useEmotionTheme } from '@emotion/react';

export default function App() {
  const theme = useEmotionTheme();
  const [backgroundColor, setBackgroundColor] = useState(theme.colorPrimary);

  useEffect(() => {
    setBackgroundColor(theme.colorPrimary);
  }, [theme.colorPrimary]);

  return (
    <div css={{ backgroundColor }}>
        {/* your app content */}
    </div>
  );
}
```

使用 useEffect 监听主题色变化，然后在回调函数中更新主题颜色。注意，将 useEffect 的依赖项设置为主题的 colorPrimary，以便发现主题颜色的变化。

希望这些方案能够帮到你解决问题。同时，我们也建议您查看相关文档以深入了解如何在 React 中处理主题，以及如何使用使用 Emotion 的主题。如果您需要进一步的帮助，请随时联系我们，我们很乐意为您提供支持。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决这个问题的可能方案如下：

1. 确保使用了正确的主题配置：首先，确保在 app.tsx 文件中正确导入并使用了主题配置文件，例如 theme.less。如果没有正确导入主题配置文件，那么获取的主题色就可能是初始值。

2. 使用 useEffect 监听变化：在 app.tsx 文件中，可以使用 React 的 useEffect 钩子函数来监听主题色的变化。在 useEffect 中注册一个监听器，当主题色变化时，更新相应的状态或执行相应的逻辑。

3. 使用 Context API：如果主题色是在 SettingDrawer 组件中进行切换的，可以考虑使用 React 的 Context API。在 SettingDrawer 组件中创建一个主题上下文，将主题色作为上下文的值，并在 app.tsx 文件中使用该上下文来获取最新的主题色。

4. 使用状态管理工具：如果应用中使用了状态管理工具（例如 Redux、Mobx），那么可以将主题色作为一个全局状态，并在 app.tsx 文件中订阅该状态。当主题色变化时，更新全局状态，从而使 app.tsx 文件中获取的主题色始终是最新的。

以上是一些可能的解决方案，可以根据具体情况选择适合的方案来解决 app.tsx 不能监听主题色变化的问题。
