### ISSUE TITLE
🐛 [BUG] Hyperlink fails in a Popover which is triggered in tree node 

### ISSUE THREAD

**Issue by y-zh** [ant-design/ant-design-pro#10496]
### 🐛 bug 描述
 Put a hyerlink in a Popover content in a tree node. Clicking the link will not invoke any link jump.

### 📷 复现步骤 | Recurrence steps
1. Create a Tree
2. in Tree node _titleRender_, put a button, whose clicking will trigger a Popover
3. In Popover conent, put a hyperlink.

4. Click the link in browser. Nothing happens.

### 🏞 期望结果 | Expected results
Clicking hyperlink will cause a new page coming out.

### 💻 复现代码 | Recurrence code
`<Card title="Service Catalog Index">
        This is service catalog index page.
        <Tree
          treeData={treeData}
          titleRender={(node) => {
            return (
              <>
                node.title
                <Popover
                  content={
                    <a href="https://www.taobao.com" target="_blank" rel="noopener noreferrer">
                      link
                    </a>
                  }
                  title="Links"
                  trigger="click"
                >
                  <Button>Click Me</Button>
                </Popover>
              </>
            );
          }}
        />
      </Card>`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by y-zh** [comment]
看上去 link 的 click 事件 和  tree node的 select 有冲突。 

将 Tree 的Selectable 设置为 false 后，link click就可以了。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很高兴能够帮到您，如果您对 React 或其他前端相关技术有疑问，可以随时联系我，我会尽力为您解答。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据描述，这个问题可能是由于Popover的触发方式为click导致的。当你点击Popover外的链接时，Popover会自动关闭，导致链接无法跳转。

解决方案如下：
1. 将Popover的触发方式改为hover，这样当鼠标移开时，Popover不会自动关闭。代码示例：
```jsx
<Popover
  content={
    <a href="https://www.taobao.com" target="_blank" rel="noopener noreferrer">
      link
    </a>
  }
  title="Links"
  trigger="hover"
>
  <Button>Click Me</Button>
</Popover>
```
2. 如果需要保持点击外部可关闭Popover的功能，可以使用React的`useState`和`useEffect`钩子来手动关闭Popover。代码示例：
```jsx
import React, { useState, useEffect } from 'react';

function MyComponent() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const handleDocumentClick = (e) => {
      if (!e.target.closest('.my-popover')) {
        setVisible(false);
      }
    };

    document.addEventListener('click', handleDocumentClick);

    return () => {
      document.removeEventListener('click', handleDocumentClick);
    };
  }, []);

  return (
    <>
      <Popover
        content={
          <div className="my-popover">
            <a href="https://www.taobao.com" target="_blank" rel="noopener noreferrer">
              link
            </a>
          </div>
        }
        title="Links"
        visible={visible}
        onVisibleChange={setVisible}
        trigger="click"
      >
        <Button>Click Me</Button>
      </Popover>
    </>
  );
}
```

这些解决方案可以解决点击链接无法跳转的问题，并根据具体需求选择适合的方式。
