### ISSUE TITLE
需要同步gitee和github 两边仓库

### ISSUE THREAD

**Issue by manooog** [ant-design/ant-design-pro#10493]
#10489 这个问题是由于proxy 设置导致的，github上已经修改了：
https://github.com/ant-design/ant-design-pro/blob/732581083c2812630ec5de4172170535e62b63b0/config/proxy.ts#L14

但在 ant-pro-cli 创建模版工程的时候， 会根据网络情况选择gitee或者github作为获取模版仓库的位置：

https://github.com/ant-design/ant-design-pro-cli/blob/34ed04859b2cbea49746d77d275ff9f64201b7d2/src/create/generators/ant-design-pro/index.js#L29

显然，大多数用户会被导向gitee。而gitee 的代码不是github上最新的～

https://gitee.com/ant-design/ant-design-pro/blob/master/config/proxy.ts#L13

所以，急需同步两端代码。

**Comment by manooog** [comment]
#10489

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


关于同步 GitHub 和 Gitee 两端代码，可以使用以下两种方法进行：

方法一：手动同步

通过 git 命令手动将 GitHub 代码同步到 Gitee 上，或者将 Gitee 代码同步到 GitHub 上。具体步骤如下：

1. 在本地 clone GitHub 上的代码：

```
git clone https://github.com/ant-design/ant-design-pro.git
```

2. 在本地设置 Git remote，添加 Gitee 仓库的地址：

```
cd ant-design-pro
git remote add gitee https://gitee.com/ant-design/ant-design-pro.git
```

3. 将代码推送到 Gitee 上：

```
git push gitee master
```

4. 或者将 Gitee 上的代码同步到 GitHub 上：

```
git push origin master
```

需要注意的是，手动同步代码需要手动处理冲突，比较繁琐。

方法二：使用自动同步工具

可以使用一些自动同步工具，将 GitHub 和 Gitee 上的代码实现自动同步。例如，可以使用 SyncGit 这个开源工具，它可以将代码库自动同步到多个 Git 托管服务上，包括 GitHub 和 Gitee。

SyncGit 的使用方法如下：

1. 安装 SyncGit：

```
npm install sync-git -g
```

2. 在项目根目录下创建 sync.config.js 文件，并设置需要同步的仓库地址：

```
module.exports = {
  remotes: {
    origin: "https://github.com/ant-design/ant-design-pro.git",
    gitee: "https://gitee.com/ant-design/ant-design-pro.git"
  }
}
```

3. 启动 SyncGit：

```
sync-git
```

运行后，SyncGit 会在后台自动同步代码，非常方便。

需要注意的是，在使用 SyncGit 之前，需要提前将 GitHub 和 Gitee 上的代码进行合并，否则可能会存在代码冲突的问题。

希望以上方法能够帮到你，如有不懂可以留言。同时，在 Github 上，你也可以在 issue 中提出此问题，向其他用户或开发者获取更多帮助。
