### ISSUE TITLE
🐛 [BUG] config.ts 设置了 locale: false 控制台报 missing message 错误

### ISSUE THREAD

**Issue by Capricair** [ant-design/ant-design-pro#10498]
### 🐛 bug 描述

/config/config.ts 中配置了 locale: false，但是控制台报 missing message 错误

![image](https://user-images.githubusercontent.com/6244446/212283451-93987dfd-5271-4251-82d1-afc85d50a71e.png)

菜单从接口请求的：
```
menu: [
  {
    name: '订单列表',
    icon: '/static/images/unordered-list.svg',
    path: '/list/order',
  },
  {
    name: '内容管理',
    icon: '/static/images/unordered-list.svg',
    children: [
      {
        name: 'Block管理',
        path: '/list/cms-block',
      },
      {
        name: 'Page管理',
        path: '/list/cms-page',
      },
    ],
  },
]
```

### 📷 复现步骤 | Recurrence steps

1. pro create my-app
2. tyarn
3. 路由数据从接口读取
4. 修改配置 locale: false
5. npm run start

### 🏞 期望结果 | Expected results

控制台无报错

### 💻 复现代码 | Recurrence code

// config/config.ts
```
layout: {
  locale: false,
  ...defaultSettings,
},
```

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本: 4.x
- 浏览器环境: Chrome
- 开发环境: node 16.16.0

### 🚑 其他信息

无

**Comment by mamba-in** [comment]
// config/config.ts
`
layout: {
  locale: false,
  ...defaultSettings,
},
`
`
locale: {
  default: 'zh-CN',
  antd: false,
  baseNavigator: true,
}
`

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


通过对你提供的信息的分析，发现该问题是 Ant Design Pro 的一个已知问题，解决方案如下：

在 config/config.ts 中，将配置改为：

```
locale: {
  default: 'zh-CN',
  baseNavigator: true
},
```

并在 app.tsx 中的初始化 APP 时，将组件的 locale 设置为 true：

```
...
<ConfigProvider {...configProps}>
  <ProLayout
    locale
    ...
  >
    {children}
  </ProLayout>
</ConfigProvider>
...
```

关于这个问题的详细解释可以参考 Ant Design Pro 官方提供的文档 [https://pro.ant.design/zh-CN/docs/faq-cn](https://pro.ant.design/zh-CN/docs/faq-cn)，查看“菜单 locale 报错，且与菜单数据有关”这一条，里面提供了更多的代码示例和解决方法。

同时，也可以参考 Ant Design 官方提供的 internationalization 文档 [https://ant.design/docs/react/i18n-cn](https://ant.design/docs/react/i18n-cn)，深入了解 Ant Design Pro 的语言国际化功能。
