### ISSUE TITLE
🐛 [BUG]第一次切换菜单，会出现短暂的空档期（Demo）

### ISSUE THREAD

**Issue by baiwumm** [ant-design/ant-design-pro#10490]
### 🐛 bug 描述

如标题所示：
![image](https://user-images.githubusercontent.com/40554571/211473486-e75b78af-6cc4-4e70-af9e-f53d96bf41f5.png)

### 📷 复现步骤 | Recurrence steps

登录后，点击没有打开过的菜单，如果页面复杂，停顿时间会更久

### 🏞 期望结果 | Expected results

增加一个loading，或者一点击菜单就能出显示

### 💻 复现代码 | Recurrence code

[Github仓库](https://github.com/Cyan-Xmw/Xmw-Admin/tree/Cyan/Xmw_web)

### © 版本信息

- Ant Design Pro 版本: ^6.0.0
- umi 版本: ^4.0.33
- 浏览器环境: Google Chrome
- 开发环境: window

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，看到你遇到了 Ant Design Pro 6.0 的一个问题，即点击没有打开过的菜单会出现短暂的空档期，可以考虑如下两个方案：

1. 加载动画：在点击菜单时，可以增加一个加载动画，当页面加载完毕后再隐藏它。可以使用 Ant Design Pro 内置的 Loading 组件，代码示例如下：
```jsx
import { useState } from 'react';
import { LoadingOutlined } from '@ant-design/icons';
import { Spin } from 'antd';

function MyComponent() {
  const [loading, setLoading] = useState(false);
  const handleClick = () => {
    setLoading(true);
    // 异步请求或其他耗时操作
    setLoading(false);
  }
  return (
    <div>
      <button onClick={handleClick}>点击菜单</button>
      {loading &&
        <div style={{position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)'}}>
          <Spin indicator={<LoadingOutlined style={{ fontSize: 24 }} spin />} />
        </div>
      }
    </div>
  );
}
```

2. 预加载组件：在页面加载完成后，可以异步请求需要渲染的组件并进行预加载（即将组件渲染到一个隐藏的 div 中），这样在点击菜单时，组件就已经加载完成了，不会有空档期。可以使用 react-loadable 库来实现，代码示例如下：
```jsx
import Loadable from 'react-loadable';
import { LoadingOutlined } from '@ant-design/icons';

const MyComponent = Loadable({
  loader: () => import('./MyComponent'),
  loading() {
    return (
      <div style={{position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)'}}>
        <Spin indicator={<LoadingOutlined style={{ fontSize: 24 }} spin />} />
      </div>
    )
  }
});

function MyPage() {
  return (
    <div>
      <MyComponent />
    </div>
  )
}
```

希望以上方案能够解决你的问题，如果还有什么疑问可以参考 Ant Design Pro 官方文档或者在 github 上提 issue，感谢你的支持！
