### ISSUE TITLE
🧐[问题 | question]执行pro create my-app出现异常

### ISSUE THREAD

**Issue by yyhLogin** [ant-design/ant-design-pro#10509]
### 🧐 问题描述 | Problem description
安装完npm i @ant-design/pro-cli -g之后执行pro create my-app出现错误

### 💻 示例代码 | Sample code

错误提示如截图

### 🚑 其他信息 | Other information
![QQ截图20230119145945](https://user-images.githubusercontent.com/19282994/213376369-c4a03ee6-e98b-451d-9584-bee537eaecf9.png)

OS:win11

Node：18.13.0

浏览器 | browser：Chrome

**Comment by coolrockin** [comment]
我也是

**Comment by wfrhwave** [comment]
> #10505

看这个Issue

**Comment by emyuan8github** [comment]
同样的问题，搜了一下，很多人都有同样的问题，建议的方法也不能真的解决问题，

**Comment by tnngo** [comment]
不知是不兼容npm，还是网络问题。

把`npm`改为`tyarn`就OK了。

**Comment by WoodMind** [comment]
> #10505

我查看了下，具体原因应该是sort这个依赖版本的问题，问题是在我需要快速搭建项目并启动时，哪怕修改了，也仍以最新版本的为准，还是会报这个错误

**Comment by yang-li-lab** [comment]
我也遇到了

**Comment by emyuan8github** [comment]
没办法，我直接从GitHub上下载了

**Comment by zhu-mingye** [comment]
遇到+1

**Comment by hanghang-6** [comment]
已解决
参照 https://github.com/ant-design/ant-design-pro/issues/9802

本人cmd未设置 git命令，参上修改完之后  
使用 git的bash     `pro create project-name`      进行项目初始化

**Comment by yangbinsoft** [comment]
参考楼上的，可以解决，谢谢大佬

> 已解决 参照 [#9802 (comment)](https://github.com/ant-design/ant-design-pro/issues/9802#issuecomment-1406706825)
> 
> 本人cmd未设置 git命令，参上修改完之后 使用 git的bash `pro create project-name` 进行项目初始化

**Comment by jimwong666** [comment]
参照 #9802 
感谢
