### ISSUE TITLE
🧐[问题 | question] table selectedRows 刷新问题

### ISSUE THREAD

**Issue by TernenceWu0702** [ant-design/ant-design-pro#10500]
### 🧐 问题描述 | Problem description
table 已勾选数据，从toolBarRender获取selectedRows，然后刷新table,获取到的selectedRows 还是之前的数据，并不是刷新后的数据，这个问题有好的解决办法吗

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 问题分析 | Analysis

根据问题描述可以看出，从 `toolBarRender` 中获取到 `selectedRows` 后刷新了表格，但是获取到的 `selectedRows` 仍然是旧的数据，应该是刷新表格后没有重新获取最新的选中数据。

### 🏃 解决方案 | Solution

可以通过监听表格的 `rowSelection` 属性中的 `onChange` 事件获取最新的选中数据，并将其传递给 `toolBarRender` 中的组件重新渲染。

```jsx
import React, { useState } from 'react';
import { Table } from 'antd';

const YourComponent = () => {
  const [selectedRows, setSelectedRows] = useState([]);

  // 监听onChange事件，更新选中数据
  const handleRowSelectionChange = (selectedRowKeys, selectedRows) => {
    setSelectedRows(selectedRows);
  };

  const tableColumns = [
    // 定义表格列
  ];

  const tableData = [
    // 表格数据
  ];

  const toolBarRender = () => {
    // 重新渲染控制台组件，并传入最新的选中数据
    return <YourToolBar selectedRows={selectedRows} />;
  };

  return (
    <Table
      rowSelection={{
        onChange: handleRowSelectionChange, // 监听onChange事件
      }}
      columns={tableColumns}
      dataSource={tableData}
      toolbar={toolBarRender}
    />
  );
};

const YourToolBar = (props) => {
  const { selectedRows } = props;

  // 其他处理逻辑

  return (
    // 控制台内容
  );
};
```

参考文档：

- [Ant Design Table - rowSelection](https://ant.design/components/table-cn/#components-table-demo-row-selection-custom)
- [Ant Design Table - toolbar](https://ant.design/components/table-cn/#components-table-demo-customized-columns)
- [React - useState](https://zh-hans.reactjs.org/docs/hooks-state.html)

**Comment by gongmin00** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> ### 🤔 问题分析 | Analysis
> 根据问题描述可以看出，从 `toolBarRender` 中获取到 `selectedRows` 后刷新了表格，但是获取到的 `selectedRows` 仍然是旧的数据，应该是刷新表格后没有重新获取最新的选中数据。
> 
> ### 🏃 解决方案 | Solution
> 可以通过监听表格的 `rowSelection` 属性中的 `onChange` 事件获取最新的选中数据，并将其传递给 `toolBarRender` 中的组件重新渲染。
> 
> ```js
> import React, { useState } from 'react';
> import { Table } from 'antd';
> 
> const YourComponent = () => {
>   const [selectedRows, setSelectedRows] = useState([]);
> 
>   // 监听onChange事件，更新选中数据
>   const handleRowSelectionChange = (selectedRowKeys, selectedRows) => {
>     setSelectedRows(selectedRows);
>   };
> 
>   const tableColumns = [
>     // 定义表格列
>   ];
> 
>   const tableData = [
>     // 表格数据
>   ];
> 
>   const toolBarRender = () => {
>     // 重新渲染控制台组件，并传入最新的选中数据
>     return <YourToolBar selectedRows={selectedRows} />;
>   };
> 
>   return (
>     <Table
>       rowSelection={{
>         onChange: handleRowSelectionChange, // 监听onChange事件
>       }}
>       columns={tableColumns}
>       dataSource={tableData}
>       toolbar={toolBarRender}
>     />
>   );
> };
> 
> const YourToolBar = (props) => {
>   const { selectedRows } = props;
> 
>   // 其他处理逻辑
> 
>   return (
>     // 控制台内容
>   );
> };
> ```
> 
> 参考文档：
> 
> * [Ant Design Table - rowSelection](https://ant.design/components/table-cn/#components-table-demo-row-selection-custom)
> * [Ant Design Table - toolbar](https://ant.design/components/table-cn/#components-table-demo-customized-columns)
> * [React - useState](https://zh-hans.reactjs.org/docs/hooks-state.html)

这个办法好像不行，因为你调用onChange里面的selectedRowKeys 也是旧的数据

**Comment by chenshuai2144** [comment]
自己重新 find 一下数据吧， selectedRowKeys  和 selectedRows 都是缓存的，不会因为表格数据变化而变化，只有重新勾选才会变化。如果可以的话，尽量销毁一下 table 然后重新设置
