### ISSUE TITLE
🐛 [BUG]pro create myapp fail

### ISSUE THREAD

**Issue by shangeyao** [ant-design/ant-design-pro#10505]
### 🐛 bug 描述

```
/usr/local/lib/node_modules/@ant-design/pro-cli/src/create/generators/ant-design-pro/index.js:10
const sortPackage = require('sort-package-json');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/@ant-design/pro-cli/node_modules/sort-package-json/index.js from /usr/local/lib/node_modules/@ant-design/pro-cli/src/create/generators/ant-design-pro/index.js not supported.
Instead change the require of /usr/local/lib/node_modules/@ant-design/pro-cli/node_modules/sort-package-json/index.js in /usr/local/lib/node_modules/@ant-design/pro-cli/src/create/generators/ant-design-pro/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/@ant-design/pro-cli/src/create/generators/ant-design-pro/index.js:10:21)
    at /usr/local/lib/node_modules/@ant-design/pro-cli/src/create/index.js:15:23
    at new Promise (<anonymous>)
    at runGenerator (/usr/local/lib/node_modules/@ant-design/pro-cli/src/create/index.js:8:10)
    at run (/usr/local/lib/node_modules/@ant-design/pro-cli/src/create/index.js:35:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@ant-design/pro-cli/cli.js:60:34) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v19.4.0
```

### 📷 复现步骤 | Recurrence steps

pro create myapp

### © 版本信息

- Ant Design Pro 版本: latest
- umi 版本
- 浏览器环境
- 开发环境 macOS

**Comment by DullBottle** [comment]
same error

**Comment by wangzilong1997** [comment]
same

**Comment by 2524514824** [comment]
I got the same error

**Comment by Faithree** [comment]
I got the same error

**Comment by eleven-ng** [comment]
same error

**Comment by Faithree** [comment]
npm i @ant-design/pro-cli -g
进入@ant-design/pro-cli  目录中
npm i sort-package-json@1.55.0 -D
重新创建项目pro create my-app 
![image](https://user-images.githubusercontent.com/21101396/212837463-6c85b0c1-5e2e-46d9-a651-6f0d1af8c604.png)

> I got the same error

**Comment by shangeyao** [comment]
> npm i sort-package-json@1.55.0 -D

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'yargs-parser'
Require stack:
- /usr/local/lib/node_modules/@ant-design/pro-cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@ant-design/pro-cli/cli.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/@ant-design/pro-cli/cli.js' ]
}
```

**Comment by erichow** [comment]
> npm i @ant-design/pro-cli -g 进入@ant-design/pro-cli 目录中 npm i sort-package-json@1.55.0 -D 重新创建项目pro create my-app ![image](https://user-images.githubusercontent.com/21101396/212837463-6c85b0c1-5e2e-46d9-a651-6f0d1af8c604.png)
> 
> > I got the same error

pro create myapp是好了，但在使用umi@3模板的时候又报错了。。。
![image](https://user-images.githubusercontent.com/5914802/212865662-220b9c73-b2eb-468f-8a25-1663ce7e4238.png)

**Comment by Shahjalal7311** [comment]
Node Version: v16.14.0
But I got the same error
pro create myapp

**Comment by framefunduser** [comment]
I too encountered the same error.

**Comment by digital-engineering-services-sample-app** [comment]
some error
os:win10
Node Version: V16.13.2
ant-design/pro-cli @3.0.1

**Comment by bigkozha** [comment]
Me too...

os:win10
Node Version: V16.13.2
ant-design/pro-cli @3.0.1

**Comment by js515990** [comment]
same error

**Comment by UsVfxArtia** [comment]
Same error, please help!

**Comment by testnet0** [comment]
Same error

**Comment by mectors** [comment]
same error

**Comment by DiF1202** [comment]
same error

**Comment by apprenticedyc** [comment]
same error

**Comment by Ivan-07** [comment]
> npm i @ant-design/pro-cli -g 进入@ant-design/pro-cli 目录中 npm i sort-package-json@1.55.0 -D 重新创建项目pro create my-app ![image](https://user-images.githubusercontent.com/21101396/212837463-6c85b0c1-5e2e-46d9-a651-6f0d1af8c604.png)
> 
> > I got the same error

Thks, it works for me.

**Comment by UsVfxArtia** [comment]
> ## Same error
> Update: step1.open ant-design folder cd /usr/local/lib/node_modules/@ant-design/pro-cli step2.install sort-package-json npm i sort-package-json@1.55.0 -D Follow the step,i have solved this problem.

this fixed! THANKS!

For windows:


Open VSCODE
1) Open folder C:\Users\USERNAME\AppData\Roaming\npm\node_modules\@ant-design\pro-cli
2) install : npm i sort-package-json@1.55.0 -D
3) Then freely use anywhere command
```
pro create my-app-name
```

**Comment by hienbase** [comment]
Same error :(

**Comment by Randomacy** [comment]
The fix doesn't work

**Comment by tnngo** [comment]
可能是不兼容npm，或还是网络问题。

把`npm`改为`tyarn`就OK了。

**Comment by JonasLang-dev** [comment]
same error

**Comment by okose-me** [comment]
Hi guys, I recommend you to take a look here for the installation;
https://v5-pro.ant.design/docs/getting-started/

**Comment by evanshi80** [comment]
> Hi guys, I recommend you to take a look here for the installation; https://v5-pro.ant.design/docs/getting-started/

这个方法似乎行，[首页的文档](https://pro.ant.design/zh-CN/docs/getting-started) 是不是有问题，需要修正？

**Comment by evanshi80** [comment]
> Hi guys, I recommend you to take a look here for the installation; https://v5-pro.ant.design/docs/getting-started/

我按这个方法最后出来的是umi的demo，明明选了ant design pro的。。。。

**Comment by borisalmonacid** [comment]
> Hi guys, I recommend you to take a look here for the installation; https://v5-pro.ant.design/docs/getting-started/

this instruction 'yarn run build' doesn't work in this tutorial

**Comment by lufinka** [comment]
same

**Comment by UsVfxArtia** [comment]
2 weeks and problem is not fixed, is ant pro archived?

**Comment by giabao1008** [comment]
i got same issue

**Comment by mironote** [comment]
same issue
