### ISSUE TITLE
🐛 [BUG]Antd Pro老项目重新安装包之后，界面出现异常

### ISSUE THREAD

**Issue by lkzwc** [ant-design/ant-design-pro#10503]
### 🐛 bug 描述
本来正常的：

![image](https://user-images.githubusercontent.com/84896877/212611929-bc20745f-7365-41bb-9805-511f9f617d2f.png)

重新拉取依赖之后
![image](https://user-images.githubusercontent.com/84896877/212612175-23a659a4-5520-49b5-8045-38fe9b242bb3.png)

大概分析之后目前觉的可能是@ant-design_pro-layout导致的问题，在版本6.38或者6.35的时候都是OK的，
node 18.0.0对应的 6.38版本
node 10版本对应的6.35
但是现在我本地依旧是node18.0.0但是安装依赖之后是7.5版本了，是pro_layout有升级吗，同样node版本安装的结果不一样的
![image](https://user-images.githubusercontent.com/84896877/212614441-a00925a4-5f22-452e-bfad-fd7699dbf394.png)

![image](https://user-images.githubusercontent.com/84896877/212613982-2439b0f6-387a-49f3-be4e-567121c0238d.png)

以下两种都是OK的
![image](https://user-images.githubusercontent.com/84896877/212614012-9a783800-339e-4851-a9e5-34d57655f346.png)
![image](https://user-images.githubusercontent.com/84896877/212614062-9c1844da-064e-4946-a49e-423f1a581047.png)

### © 版本信息
"name": "ant-design-pro",
 "version": "4.3.0",
 "private": true,

**Comment by lkzwc** [comment]
除过web网站header有变化，整个节目的border也有部分变化
![image](https://user-images.githubusercontent.com/84896877/212643430-d076f1f7-2ede-435a-8fca-d28cbda28f77.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的截图和描述，可能是由于 Ant Design Pro 更新后造成页面样式出现异常。

建议尝试以下解决方案：

1. 检查是否按照 Ant Design Pro 官方文档正确升级了依赖，特别是 pro-layout，可以使用 `npm list` 查看安装的版本，确保版本一致。

2. 检查是否存在自定义样式覆盖了 Ant Design Pro 的样式，可能导致页面显示不正常。可以通过浏览器的开发者工具检查元素和样式，调整样式优先级。

3. 也可以尝试重新生成 Ant Design Pro 项目的默认配置文件和页面，详见 [官方文档](https://pro.ant.design/docs/restart-cn)。

另外，如果还存在问题，可以提供更详细的错误信息和代码示例，以便更准确地帮助解决问题。
