### ISSUE TITLE
🐛 [BUG]热更新会报错 Uncaught ReferenceError: process is not defined，且页面卡住

### ISSUE THREAD

**Issue by Faithree** [ant-design/ant-design-pro#10507]
### 🐛 bug 描述

新建的项目，修改文件热更新，页面卡住，且报错 Uncaught ReferenceError: process is not defined

### 📷 复现步骤 | Recurrence steps

1. 新建一个项目 pro create bug-demo
2.  pnpm install
3. npm run start
4. 修改文件热更新，页面卡住，且报错 Uncaught ReferenceError: process is not defined

### 🏞 期望结果 | Expected results

正常热更新

### 💻 复现代码 | Recurrence code

https://github.com/Faithree/bug-demo

### © 版本信息

- Ant Design Pro 版本: "@ant-design/pro-cli": "^2.1.0",
- umi 版本: "@umijs/max": "^4.0.33",
- 浏览器环境:任意浏览器
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/21101396/212902567-1f19face-8b8a-4bab-84a7-cc7633d7ba97.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供复现步骤和代码。根据错误提示 `Uncaught ReferenceError: process is not defined`，可以猜测是在前端代码中使用了后端 `Node.js` 中的全局变量 `process`，导致浏览器环境不能识别。因为浏览器不支持 `Node.js` 的模块系统，所以不能直接在浏览器中使用 `Node.js` 中的全局变量。在前端代码中，如果需要获得类似于 `process.env.NODE_ENV` 的配置信息，可以使用 webpack 提供的 DefinePlugin 来定义全局变量。

在 antd pro 项目中，可以在 config/config.js 中配置 define 来定义全局变量，例如

```javascript
export default {
  define: {
    'process.env':
      process.env.NODE_ENV === 'production' ? prodEnv : devEnv,
  },
};
```

具体来看，这里导致的原因估计是因为调用了 polaris/react 的逻辑

```javascript
import {getLocale } from '@polaris/locales';

export const getAntdLocale = (): AntdLocale => {
    const localeDict = getLocale();
  // ...
}
```

而本人猜测可能是 Polarirs 向外导出了 Node.js 的模块系统需要，如果不是很要用到 @polaris相对应的Locale，可以将引用去掉或者通过 DefinePlugin 来避免 `process is not defined` 这种异常。

一般来说在前端，`process.env` 都是由构建工具提供的变量，如需手动定义你可以使用 webpack 将 env 中的变量进行打包。你可以在 DefinePlugin 中定义，例如：

```javascript
...
plugins: [
    // ...
    new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('production'),
    }),
],
...
```

参考文献：
- [react应用在浏览器端报错：Uncaught ReferenceError: process is not defined](https://blog.csdn.net/qq_40731511/article/details/102880274)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你提供的信息，这个问题可能是因为缺少了引入 `process` 的配置。下面是一个可能的解决方案：

1. 在项目根目录创建一个 `.umirc.local.js` 文件（如果已有请忽略这一步）。
2. 在 `.umirc.local.js` 文件中添加以下配置：
   ```javascript
   export default {
     define: {
       'process.env': {},
     },
   };
   ```
3. 重新启动项目，并尝试修改文件进行热更新，看看问题是否解决了。

这个解决方案使用了 Umi 的 define 配置来指定 `process.env` 是一个空对象，以解决 `process is not defined` 的报错。这样热更新应该能够正常工作了。

关于页面卡住问题，这可能是因为热更新过程中编译时间过长导致的。你可以尝试做一些前端性能优化，例如使用代码分割、按需加载等技术来减少页面加载时间，从而提升整体的性能。另外，你还可以使用 webpack-bundle-analyzer 工具来分析打包结果，找出页面卡住的具体原因。

**Comment by zmm2tysu** [comment]
参考这个我解决了
https://blog.zhouweibin.top/pitfall/react-hot-error/
