### ISSUE TITLE
🧐[问题 | question]ant design pro登录跳转不到主界面，需要手动刷新后再次登录才行

### ISSUE THREAD

**Issue by Ben6501** [ant-design/ant-design-pro#10504]
### 🧐 问题描述 | Problem description
Ant design pro登录跳转不到主界面，需要手动刷新后再次登录才行

### 💻 示例代码 | Sample code
![image](https://user-images.githubusercontent.com/15306774/212675602-41ec56ca-9356-491c-a83d-539a21c9580d.png)

login()和fetchUserInfo()都是执行成功了的。

**Comment by TianJianJun727** [comment]
跳转时可以使用location.href

**Comment by Ben6501** [comment]
问题已解决。
app.tsx中fetchUserInfo()调用后端成功，返回前端的数据没接上，导致前端currentUser一直为undefined，调整一下就好了。
![image](https://user-images.githubusercontent.com/15306774/215313618-5c764887-a026-4e64-aac6-c150df65c9fa.png)

**Comment by guwan** [comment]
你能不能具体说下怎么处理的？我参考下。我的也登录不了，弹出登录成功了。
