### ISSUE TITLE
could not determine executable to run🐛 [BUG]

### ISSUE THREAD

**Issue by 548705486** [ant-design/ant-design-pro#10508]
### 🐛 bug 描述

通过 pro create 创建好项目，提交到git远程仓库报错

### 📷 复现步骤 | Recurrence steps

1. pro create
2. 通过source tree 提交代码

### 🏞 期望结果 | Expected results

无报错，正常提交

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 最新pro create
- 浏览器环境 Chrome
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5135151/213066460-45853189-ce55-4ade-8ba9-5b59c800be50.png)

**Comment by edision** [comment]
一样，删除.git，.pnpm-store,重新初始化正常一阵，然后又不行了

**Comment by slarkzhu** [comment]
一样的问题，等待修复

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我理解了你的问题，你是在使用 Ant Design Pro 创建好项目后，在使用 SourceTree 提交到远程仓库时遇到了 could not determine executable to run 的错误。

根据您提供的错误信息，多数情况下这是 `husky` 工具的一个问题。您可以尝试通过以下步骤解决这个问题：

1. 在终端中使用以下命令安装 `husky`：

```shell
npm install husky --save-dev
```

2. 添加以下配置到 package.json 中：

```json
"husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
}
```

这将告诉 `husky` 在每次提交之前运行 `npm run lint` 命令来检查您的代码是否符合规范。

如果上述方法不能解决您的问题，您可以尝试重新初始化 git 仓库，如下所示：

1. 删掉 .git 目录：

```shell
rm -rf .git
```

2. 初始化新的 git 仓库：

```shell
git init
```

3. 添加并提交您的更改：

```shell
git add .
git commit -m "initial commit"
```

这应该可以解决您的问题。如果问题仍然存在，请提交一个[issue](https://github.com/ant-design/ant-design-pro/issues)，并尽可能详细地描述您遇到的问题和您在尝试解决问题时的所有步骤。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


重新初始化 git 仓库之后可以重新使用 `git remote` 命令将远程仓库添加到当前本地仓库中，并 push 本地仓库的内容到远程仓库中。具体步骤如下：

1. 在终端中进入到您的本地代码仓库的根目录。

2. 删除之前的 `.git` 文件夹：

```shell
rm -rf .git
```

3. 初始化新的 Git 仓库：

```shell
git init
```

4. 添加和提交您的更改： 

```shell
git add .
git commit -m "Initial commit"
```

5. 将本地 Git 仓库与远程仓库关联起来，并 push 本地代码到远程仓库：

```shell
git remote add origin <remote-repo-url>
git push -u origin master
```

这样您之前的 commit 记录就会被保留在您的远程仓库中了。请注意，由于您重新初始化了本地仓库，您的本地 commit 记录将被删除，只在远程仓库中保留。

**Comment by Cewr** [comment]
![image](https://user-images.githubusercontent.com/51740945/224634848-e190a1ad-b40a-4455-9bd5-81335a99dcd2.png)
大佬再麻烦看下~ 到push就失败了，用 push -f 远程仓库的commit 就也只剩1个了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的截图，似乎是使用了 git-lfs 上传大文件导致的问题。

Git-lfs 是一个 Git 扩展，用于存储大型二进制文件并跟踪文件指针，对限制存储容量的仓库特别有用。但是，在拉取和推送 Git 仓库时，您需要在本地和远程仓库中都安装并配置 Git-lfs。如果没有正确安装和配置，您可能会遇到各种各样的问题，如这个问题。

为了解决这个问题，您可以参考以下步骤：

1. 使用以下命令卸载 Git-lfs：

```shell
git-lfs uninstall
```

2. 删除本地和远程仓库中已经添加的 Git-lfs 管理的文件：

```shell
git rm --cached <large-file>
```

3. 提交并推送更改：

```shell
git commit -m "Remove large file"
git push
```

4. 确认删除操作：

```shell
git lfs ls-files
```

5. 重置本地修改并且拉取远程仓库内容：

```shell
git reset --hard origin/master
git pull
```

6. 重新上传大文件：

```shell
git lfs track "path/to/large/file"
git add path/to/large/file
git commit -m "Add large file"
git push
```

希望这些步骤可以帮助您解决问题。

**Comment by Cewr** [comment]
解决方法：
rm -rf .git/hooks
rm -rf .husky/commit-msg
npm run prepare

commit 可以正常通过，lint 也正常
