### ISSUE TITLE
🧐[base 路径设置无效，最新版本]

### ISSUE THREAD

**Issue by jmy2022** [ant-design/ant-design-pro#10513]
### 🧐 问题描述 | Problem description

config中的base 类似react 官方的 package中的homepage。 在umi4. 和ant-design-pro 中设置无效。
https://pro.ant.design/config/config

![Screenshot 2023-01-22 at 14 38 43](https://user-images.githubusercontent.com/116630592/213903957-0ce49585-b217-4e59-b6c1-ff23e09555eb.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🛠️ 解决方案 | Solution

如果你想为你的应用设置 `base` 路径，可以使用 `react-router-dom` 库中的 `BrowserRouter` 组件，并在其上设置 `basename` 属性。

例如：

```jsx
import React from 'react';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import Home from './pages/Home';
import About from './pages/About';

function App() {
  return (
    <BrowserRouter basename="/myapp">
      <Switch>
        <Route exact path="/" component={Home} />
        <Route path="/about" component={About} />
      </Switch>
    </BrowserRouter>
  );
}

export default App;
```

在这个例子中，我们将 `basename` 属性设置为 `/myapp`，因此所有相对于根路径的 URL 将以 `/myapp` 为前缀。例如，`/about` 将成为 `/myapp/about`。

在 Ant Design Pro 中使用 `BrowserRouter` 组件时，你需要修改 `routes.ts` 文件。在 `layout` 属性中，将 `component` 指定为 `BasicLayout` 组件，并将 `path` 属性设置为 `'/'`：

```tsx
import { BasicLayout } from '@ant-design/pro-layout';

export const routes: RouteConfig[] = [
  {
    path: '/',
    component: BasicLayout,
    // ... more config
  },
  // ... more routes
];
```

接着，将 `BasicLayout` 组件的定义文件 `BasicLayout.tsx` 中的 `BrowserRouter` 组件导入，并为其设置 `basename` 属性：

```tsx
import { BrowserRouter } from 'react-router-dom';

export default class BasicLayout extends React.Component<BasicLayoutProps> {
  render() {
    return (
      <BrowserRouter basename="/myapp">
        {/* ... */}
      </BrowserRouter>
    );
  }
}
```

现在，你的应用中应该已经成功设置了 `base` 路径。如果仍然无效，请确保你的 Ant Design Pro 版本是最新的。如果问题仍然存在，你可以到 Ant Design Pro 的 GitHub Issues 页面进行反馈。

**Comment by chenshuai2144** [comment]
base  不是  homepage，是用来部署二级路径的，homepage 是用来指示官网的。两个没有可比性
