### ISSUE TITLE
🧐[问题 | question] How to get dark nav bar like the preview?

### ISSUE THREAD

**Issue by riwu** [ant-design/ant-design-pro#10515]
On https://preview.pro.ant.design/dashboard/analysis the nav bar is dark but the rest of the theme is light:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/2226023/213968763-7ea0bfba-d1a8-4c77-9098-e226060fefe6.png">

What should the configuration be to achieve this?

**Comment by UsVfxArtia** [comment]
Hi, this may help https://procomponents.ant.design/en-US/components/layout#header-token

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hello! Thank you for reaching out. 

If you want to achieve a dark nav bar like the one in the preview you've shared, you can use the `token` property provided by `ProLayout` component of Ant Design Pro.

Here's an example configuration that you can apply to your code:

```
<ProLayout
  token={{
    header: {
      colorBgHeader: "dark",
      colorTextMenu: "white",
    },
  }}
>
  {/* Your page components */}
</ProLayout>
```

In this example, we specified the value of `colorBgHeader` as `"dark"` and `colorTextMenu` as `"white"` under the `header` token object. This will make the background color of the header dark and the color of the text in the menu white.

You can also play around with other token values to further customize your layout. You can find the complete list of token values in the Ant Design Pro documentation: https://procomponents.ant.design/en-US/components/layout#header-token.

Hope this helps! Let me know if you have further questions.

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


To achieve a dark navigation bar like the one in the preview, you can follow these steps:

1. Choose a dark theme for your project. This can be done by applying a dark color scheme to your project's stylesheets. You can either create a custom dark theme or use an existing theme library like antd's dark theme.

2. Use a navigation component that supports customization of the background color. In this case, you can use antd's Menu component to create the navigation bar. Set the theme prop of the Menu component to "dark" to apply the dark theme.

3. Customize the styles of the navigation bar to match the preview. You can modify the background color, text color, and other styles using CSS. You may also need to adjust the styles of other components on the page to ensure a consistent look.

4. Test and iterate on the design. Make sure to test the navigation bar in different browsers and devices to ensure a consistent and responsive experience.

By following these steps, you should be able to achieve a dark navigation bar like the one in the preview.
