### ISSUE TITLE
本地构建ok，在jenkins上构建时，报sh: umi: command not found

### ISSUE THREAD

**Issue by Petter-li** [ant-design/ant-design-pro#10510]
### 🧐 问题描述 | Problem description
centos服务器，使用jenkins服务，构建报错sh: umi: command not found

### 💻 示例代码 | Sample code
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/buildapp_html_service
The recommended git tool is: NONE
using credential c19ded43-5385-4d20-ab8d-1976ea63ebfc
 > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/buildapp_html_service/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:Petter-li/buildapp.git # timeout=10
Fetching upstream changes from git@github.com:Petter-li/buildapp.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress git@github.com:Petter-li/buildapp.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
Checking out Revision a7c64233164378268b000faa8253b8fae19b285b (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a7c64233164378268b000faa8253b8fae19b285b # timeout=10
Commit message: "first commit"
 > git rev-list --no-walk a7c64233164378268b000faa8253b8fae19b285b # timeout=10
[buildapp_html_service] $ /bin/bash -il /tmp/jenkins8099952900419964553.sh
bash: no job control in this shell
/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_16.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin:/root/bin:/root/bin
v16.18.1
8.19.2
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: dva-immer@1.0.0
npm WARN Found: dva@2.6.0-beta.22
npm WARN node_modules/@umijs/plugin-dva/node_modules/dva
npm WARN   dva@"^2.6.0-beta.20" from @umijs/plugin-dva@0.13.2
npm WARN   node_modules/@umijs/plugin-dva
npm WARN     @umijs/plugin-dva@"0.13.2" from @umijs/preset-react@2.1.6
npm WARN     node_modules/@umijs/preset-react
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer dva@"^2.5.0-0" from dva-immer@1.0.0
npm WARN node_modules/@umijs/plugin-dva/node_modules/dva-immer
npm WARN   dva-immer@"1.0.0" from @umijs/plugin-dva@0.13.2
npm WARN   node_modules/@umijs/plugin-dva
npm WARN 
npm WARN Conflicting peer dependency: dva@2.5.0-beta.2
npm WARN node_modules/dva
npm WARN   peer dva@"^2.5.0-0" from dva-immer@1.0.0
npm WARN   node_modules/@umijs/plugin-dva/node_modules/dva-immer
npm WARN     dva-immer@"1.0.0" from @umijs/plugin-dva@0.13.2
npm WARN     node_modules/@umijs/plugin-dva

> ant-design-pro@5.2.0 build
> umi build

sh: umi: command not found
tar: dist: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 问题分析 | Analysis

从日志看，像是缺失 umi 命令。在 Jenkins 上构建的网络环境与本地环境不同，导致命令无法使用。可能是因为 Jenkins 的构建环境中没有安装 umi ，或者 PATH 环境变量没有正确地配置导致。

### 🏆 解决方案 | Solution

1. 确认 Jenkins 配置 Node.js 环境是否正确，确保构建的 Node.js 版本与本地是否一致。
2. 确认 umi 是否已经全局安装。如果未安装，请在 Jenkins 中执行以下命令进行安装：

   `npm install -g umi`

   然后再次执行 Jenkins 任务。

3. 如果 umi 已经安装在特定项目环境下，则尝试在 Jenkins 中在构建任务之前先进入项目的目录，使其先执行特定项目的依赖安装命令。即：

   ```
   cd /path/to/project
   npm install
   umi build
   ```

4. 可以尝试在 Jenkins 的“全局工具配置”中设置 Node.js 和 npm ，并在 Jenkinsfile 中使用 tools 标记来指定 Node.js 和 npm 路径。这样可以确保 Jenkins 的构建时环境变量都已设置正确。

   ```
   tools {
       nodejs "NodeJS_16.18.1"
   }
   ```

### 🔎 参考资料 | References

- [Jenkins报错”command not found"](https://www.cnblogs.com/febby/p/10473859.html)
- [Node.js and npm](https://jenkins.io/doc/book/installing/#nodejs-and-npm)
- [How to use Jenkins tools](https://jenkins.io/doc/book/pipeline/using-tools/)
