### ISSUE TITLE
On top_nav Branch  , the navigation setting option 'top sdie' doesn't work

### ISSUE THREAD

**Issue by tianlinzx** [ant-design/ant-design-pro#1051]
On Branch top_nav , the navigation setting option 'top sdie' doesn't work.
And the icons for these three options can't display properly.
![tim 20180308150240](https://user-images.githubusercontent.com/1411754/37138385-ddfff5ea-22e4-11e8-83e7-374b2224f41a.png)

**Comment by tianlinzx** [comment]
![tim 20180308150240](https://user-images.githubusercontent.com/1411754/37138374-d1e179be-22e4-11e8-91fe-45bf9831489a.png)

**Comment by ddcat1115** [comment]
Thanks for reporting, we are still working on this, the `top_nav` branch is not stable yet.

**Comment by chenshuai2144** [comment]
fix

**Comment by tianlinzx** [comment]
The topside mode still doesn't work yet.
