### ISSUE TITLE
🐛 [BUG] 移除国际化后左侧的菜单栏内容消失

### ISSUE THREAD

**Issue by whoeverim5** [ant-design/ant-design-pro#10526]
### 🐛 bug 描述

首先，移除国际化时会出错，按照之前的issue处理后将国际化移除。

移除国际化后主页左侧的菜单栏内容消失。

同时，在开发工具webstorm中，**'app.tsx'**文件下的**'layout'**中的**'footerRender'**和**'onPageChange'**提示**未被使用**

删除src下的.umi并重新编译后无效，问题没解决。

在移除国际化之前菜单栏内容还在。

### 📷 复现步骤 | Recurrence steps

- pro create myapp

- pnpm install

- pnpm i18nremove

### 🏞 期望结果 | Expected results

左侧的内容还保留

### 💻 复现代码 | Recurrence code

无

### © 版本信息

- pro cli 版本 3.0.1
- Ant Design Pro 版本: 6.0.0
- umi 版本 4.0.44
- 浏览器环境 Google Chrome
- 开发环境 Windows11 64位

### 🚑 其他信息

左侧菜单栏为空

<img width="1280" alt="微信截图_20230201152129" src="https://user-images.githubusercontent.com/76519998/215977429-3d8c2416-45d1-41d5-9603-514716f219b7.png">

webstorm提示两个方法未被使用

<img width="1280" alt="微信截图_20230201152855" src="https://user-images.githubusercontent.com/76519998/215978698-3ec62266-fa0d-4e31-b3d0-c28a442d57f6.png">

**Comment by wudalei** [comment]
我也遇到了这个问题，请问有解决方案吗

**Comment by whoeverim5** [comment]
> 我也遇到了这个问题，请问有解决方案吗

路由文件中为每条路由添加上name属性

**Comment by leujanhv** [comment]
之前添加路由里添加name属性有用，现在有失效了

**Comment by BenshuYu** [comment]
在pnpm install之后不要启动项目，直接运行pnpm i18nremove，然后再启动项目试试。

**Comment by SYFlyyy** [comment]
> 在pnpm install之后不要启动项目，直接运行pnpm i18nremove，然后再启动项目试试。

感谢，问题解决了
