### ISSUE TITLE
🧐[使用远程菜单的疑问]

### ISSUE THREAD

**Issue by anhao** [ant-design/ant-design-pro#10529]
### 🧐 
使用远程菜单时，是不是还需要在 config 配置文件里面定义一遍路由呢，

**Comment by laosandegudai** [comment]
对，目前的回复是路由是路由，是既定的（umi的两种方式之一），菜单可以自由控制。社区有人提供菜单路由全部动态化方案。

**Comment by KYX1234** [comment]
patchClientRoutes这个好像可以
