### ISSUE TITLE
🐛 [BUG]LoginFormPage组件高度有问题

### ISSUE THREAD

**Issue by quarkcms** [ant-design/ant-design-pro#10521]
应该把高度100%去掉
![image](https://user-images.githubusercontent.com/60868863/215658722-e2f0d245-ea43-486c-8254-cc7a0a19f10c.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，感谢你向我提出了你的问题。

根据你提供的截图，LoginFormPage组件的高度是由父级元素设置为100%导致的。因此，将LoginFormPage组件的高度设置为自适应即可解决该问题。

实现方法1：

可以在LoginFormPage组件中将样式设置为height: auto，这样LoginFormPage组件的高度就会自适应其内容的高度。

```javascript
import React from 'react';

const LoginFormPage = () => {
  return (
    <div style={{ height: 'auto' }}>
        {/*LoginFormPage组件的内容*/}
    </div>
  );
}

export default LoginFormPage;
```

实现方法2：

可以将LoginFormPage组件的样式修改为position: absolute，并在父级元素设置position: relative。这样LoginFormPage组件就会相对于父级元素进行定位，高度也会自适应其内容高度。

```javascript
import React from 'react';

const LoginFormPage = () => {
  return (
    <div style={{ position: 'absolute' }}>
        {/*LoginFormPage组件的内容*/}
    </div>
  );
}

export default LoginFormPage;
```

更多关于React的用法，可以参考React官方文档：https://reactjs.org/docs/getting-started.html。希望这能解决你的问题。
