### ISSUE TITLE
🐛 [BUG] findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design-pro#10527]
### 🐛 bug 描述

findDOMNode is deprecated in StrictMode.

### 📷 复现步骤 | Recurrence steps

在严格模式下使用 ant-design-pro 会出现 warning: findDOMNode is deprecated in StrictMode.

### 🏞 期望结果 | Expected results

react 可能在某个版本的严格模式下正式移除 findDOMNode， 如果可以的话使用 ref 代替

### 💻 复现代码 | Recurrence code

![image](https://user-images.githubusercontent.com/30885718/216213189-40b62b4e-1e17-48ae-bb03-67e62d724c40.png)

### © 版本信息

- Ant Design Pro 版本:  latest
- umi 版本
- 浏览器环境
- 开发环境 : every

**Comment by yasz** [comment]
相同故障。。。

**Comment by noahge** [comment]
单独使用ProTable就会报错，怎么解决有人有方案吗？
