### ISSUE TITLE
在cmd中执行pro create app命令后进度卡住不动

### ISSUE THREAD

**Issue by DJX-A** [ant-design/ant-design-pro#10535]
### 🧐 问题描述 | Problem description

安装完@ant-design/pro-cli

在`cmd`中执行 `pro create myapp`

然后就卡住了，代码一直下载不下来

### 🚑 问题截图 | Screenshot of the problem

<img width="858" alt="Snipaste_2023-02-06_12-28-48" src="https://user-images.githubusercontent.com/82458810/216884641-34fee339-cf02-4d70-8c82-98848e2a397e.png">

### 👀 解决办法 | Solution

在git bash中运行上述命令即可解决
![image](https://user-images.githubusercontent.com/82458810/216884935-f1a4e817-693b-42a2-95ec-80fa232a06f7.png)

OS: Win11

Node：v16.15.1

浏览器 | browser：chrome

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于Windows自带的命令提示符（cmd）无法正确处理一些操作而导致的。安装git bash并在其中运行命令可能是一个解决方案。

如果仍然无法解决问题，请考虑检查网络连接是否正常以及是否有适当的权限运行该命令。您还可以尝试更新npm、升级到最新版本的@ant-design/pro-cli并尝试再次运行命令。

参考文档：
- [npm 更新命令](https://docs.npmjs.com/Updating-Packages-Interactively)
- [@ant-design/pro-cli 官方文档](https://pro.ant.design/docs/getting-started-cn)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你提供的信息，可以尝试以下解决方案：

1. 确保已经正确安装了`@ant-design/pro-cli`，可以使用命令`npm i @ant-design/pro-cli -g`进行全局安装。

2. 在cmd中执行`pro create myapp`命令后进度卡住不动的问题可能是由于网络原因导致代码无法下载。你可以尝试使用git bash来执行这个命令，git bash可能会更好的处理网络问题。在git bash中运行`pro create myapp`命令可以解决这个问题。

这是因为`pro-cli`使用了git仓库进行代码下载，而git bash对于git仓库的支持更好，能够更好地处理网络问题。

通过以上步骤的操作，应该可以解决代码下载一直卡住的问题。如果还有其他问题，请提供更多的信息以便我们能够更深入地帮助你解决问题。
