### ISSUE TITLE
🧐[问题 | question] 如何扩展devServer的mimeTypes？

### ISSUE THREAD

**Issue by whsqjss** [ant-design/ant-design-pro#10530]
### 🧐 问题描述 | Problem description
我尝试集成webassebly到项目中。但是启动后，浏览器报错
```
TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```
我尝试在config.ts通过chainWebpack配置devServer的mimeTypes，但是未生效，配置如下：
webpack5 配置参考的[这里](https://webpack.js.org/configuration/dev-server/#devserverdevmiddleware)
```
    memo.devServer.set('devMiddleware', {
      mimeTypes: { wasm: 'application/wasm' }
    })
```
尝试这样配置也不行
```
memo.devServer.port(9000).mimeTypes({ wasm: 'application/wasm' });
```

启动命令用的
```
yarn start
```
### 🚑 其他信息 | Other information

OS:
win10
Node：
v16.17.0
浏览器 | browser：
chrome

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 📝 解决方案 | Solution

根据文档描述，似乎`devServer.devMiddleware.mimeTypes`配置不生效。可以使用`webpack-dev-middleware`自定义设置mimeTypes。

在webpack.config.ts中配置webpack-dev-middleware，示例如下：

```typescript
// 引入webpack-dev-middleware
const webpackDevMiddleware = require('webpack-dev-middleware');

const config = defineConfig({
  // ...其他配置
  plugins: [],
  server: {
    open: true,
    // 自定义设置mimeTypes
    afterMiddleware: [
      webpackDevMiddleware(compiler, {
        mimeTypes: {
          wasm: 'application/wasm',
        },
      }),
    ],
  },
});

export default config;
```

除了`mimeTypes`配置外，`webpack-dev-middleware`还有其他可选参数，参考[官方文档](https://github.com/webpack/webpack-dev-middleware#options)。

至于为什么无法直接在`devServer.devMiddleware.mimeTypes`上设置，原因可能是`mimeTypes`是在`DevMiddleware`组件创建时设置的，而`DevMiddleware`组件是在`WebpackDevServer`创建时初始化的，`mimeTypes`配置可能在`WebpackDevServer`的初始化时已被忽略。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


在 Umi 4 中，不再支持直接配置 `devServer` 选项来修改 `mimeTypes`。但是你可以通过以下两种方式来实现类似的功能：

1. 使用 proxy 选项配置代理，并通过 `onProxyReq` 修改请求头信息。具体做法如下：

```javascript
// config/config.ts

export default {
  proxy: {
    '/': {
      target: 'http://localhost:9000',
      changeOrigin: true,
      onProxyReq(proxyReq, req, res) {
        proxyReq.setHeader('Content-Type', 'application/wasm');
      },
    },
  },
};
```

2. 编写项目级插件来插入 express 中间件，以实现对请求的修改。具体做法如下：

```javascript
// config/plugin.ts

import { IApi } from '@umijs/types';

export default function (api: IApi) {
  api.middleware((req, res, next) => {
    if (req.url.endsWith('.wasm')) {
      res.setHeader('Content-Type', 'application/wasm');
    }
    next();
  });
}
```

这两种方法可以帮助你修改请求头中的 `Content-Type`，从而解决 `Incorrect response MIME type` 错误。请根据你的具体需求选择其中一种方法进行实现。
