### ISSUE TITLE
删除数据，第二页数据为空后，分页显示正常，列表显示异常

### ISSUE THREAD

**Issue by ycshill** [ant-design/ant-design-pro#10545]
问题：
删除数据，第二页数据为空后，
分页显示最新的数据；列表显示空白，原因是current 没有变，total 变了，这个需要修复一下吧

**Comment by wangxing0204** [comment]
不知道我这部分代码是否能帮助你：
//调用
// 重置分页
resetPagination(actionRef);

//这部分是全局
export const resetPagination = (actionRef: React.MutableRefObject<ActionType | undefined>) => {
  // 获取当前分页信息
  const pageInfo = actionRef.current?.pageInfo;

  // 如果当前页是最后一页，删除数据后需要重新查询前一页的数据
  if (pageInfo && pageInfo.current > 1 && pageInfo.pageSize) {
    const total = pageInfo.total;
    const pageSize = pageInfo.pageSize;
    const newTotal = total - 1;
    const newCurrent = Math.ceil(newTotal / pageSize);

    // 设置新的分页信息，使页面跳转到前一页
    // @ts-ignore
    actionRef.current?.setPageInfo({
      pageSize,
      current: newCurrent,
      total: newTotal,
    });
  }
};

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供代码，根据您提供的代码可以看出您主要是在处理分页信息的问题。根据您的代码，实现了删除数据后保持当前页的展示，并且在需要的情况下自动跳转到前一页。如果您的分页列表出现了异常，可以尝试检查以下几个方面：

1.检查是否正确展示了删除后的数据：检查删除的数据是否已经成功地从数据库中删除，并且新的数据是否已经成功地更新到前端。这个过程可能需要检查后端的接口是否正确提供了删除数据的功能。

2.检查分页组件是否正确调用：检查分页组件是否正确地调用并设置了正确的current和total值。如果与分页组件相关的代码没有问题，您可以考虑检查一下前端的渲染是否与分页组件的预期相同。

3.检查分页组件是否正确调整：这个过程需要根据您的具体分页组件的实现方式来调整。您可以根据实际情况尝试调整分页组件的渲染逻辑，让它正确地处理组件重建的情况。在大多数情况下，分页组件的重新渲染可能与浏览器缓存有关，您可以考虑检查一下浏览器缓存是否正确设置或者是否需要手动更新缓存。

希望这些提供的信息能帮助您解决问题，如果您还有其他问题或者需要更详细的解决方案，欢迎继续咨询。
