### ISSUE TITLE
🐛 [BUG] 登录后空白页面

### ISSUE THREAD

**Issue by artjourney** [ant-design/ant-design-pro#10544]
### 🐛 bug 描述

登录后跳转到首页空白页面，JS报错。环境启用mfsu。

![1](https://user-images.githubusercontent.com/8003780/217434770-08810d3e-44e6-4d84-8a17-64ac26f4f9f4.png)

![2](https://user-images.githubusercontent.com/8003780/217434799-4ba00e48-c8a3-4782-86b2-ca8aba50cc81.png)

![3](https://user-images.githubusercontent.com/8003780/217434821-874fbd45-e72f-42df-a2ce-0837b90faa93.png)

### 📷 复现步骤 | Recurrence steps

tyarn install
tyarn add swagger-ui-react --save
touch /目录/ant-design-pro-6.0.0-beta.1/node_modules/.cache/mfsu/mf-va_remoteEntry.js
tyarn start

### 🏞 期望结果 | Expected results
正常登录。

### © 版本信息

- Ant Design Pro 版本: v6.0.0-beta.1
- umi 版本 Umi v4.0.50
- 浏览器环境 109.0.5414.120 64 位, 浏览器操作环境windows 11
- 开发环境 Ubutu 22
- Node version v16.19.0

**Comment by clour** [comment]
我操作下来倒是正常的

**Comment by artjourney** [comment]
使用master就可以。
