### ISSUE TITLE
Modal 弹出层中嵌套有子组件，外部按钮第一次打开Modal时无法获取子组件

### ISSUE THREAD

**Issue by davecat** [ant-design/ant-design-pro#1054]
![image](https://user-images.githubusercontent.com/21263055/37145836-9eb1df46-2287-11e8-8355-ffaffb45c769.png)
如题，第一次Modal打开时候，无法获取  this.channelForm  ,关闭后再次打开就可以了。感觉是不是组件没有渲染完毕？ 我想问下，这个有没有类似Vue的 nextTick 方法？

**Comment by ddcat1115** [comment]
demo 没有问题： https://codesandbox.io/s/ovxn242mlz

**Comment by davecat** [comment]
@ddcat1115  谢谢你的demo，大概意思差不多。不过我的意思不是说子组件不显示，例如如下代码，我在你代码的基础上写的，如下
![image](https://user-images.githubusercontent.com/21263055/37634407-570f5aec-2bc4-11e8-9777-8a922e5f633e.png)
打开modal的时候，需要获取this.form,即子组件，譬如我在打开modal时候需要填充这个form的需求，需要用到官方的  this.form. setFieldsValue();  图中log为undefind  ，我的问题正是在于此，请问你的方案是如何处理的？谢谢
