### ISSUE TITLE
yarn add @umijs/preset-ui -D执行没有效果

### ISSUE THREAD

**Issue by ji876** [ant-design/ant-design-pro#10546]
### 🧐 问题描述 | Problem description
项目正常启动后想要添加umi但是执行上述命令后没有效果

![image](https://user-images.githubusercontent.com/55964269/217846158-2e749a03-8fb7-4f2e-bed9-de20691c74e7.png)

![image](https://user-images.githubusercontent.com/55964269/217846291-ba3e32b5-bce8-4d0d-a4c3-bbbba952db05.png)

![image](https://user-images.githubusercontent.com/55964269/217846350-26651865-5a62-4339-b159-f79111b70c0b.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🧐 回答 | Answer

根据您提供的截图，`yarn add @umijs/preset-ui -D` 命令执行出错，错误提示中提到了 `Error: ENOENT: no such file or directory, open '/Users/benjaminwu/Desktop/tutorial/package.json'`，看样子是找不到 `package.json` 文件导致的。

请先确认您是否在项目的根目录下运行该命令，并且确保您的项目根目录下存在 `package.json` 文件。

如果确认了以上问题，还是无法运行命令，可以尝试以下步骤：

1. 清除 `yarn` 的缓存：

```bash
yarn cache clean
```

2. 重新执行安装命令：

```bash
yarn add @umijs/preset-ui -D
```

如果还不行的话，有可能是 `yarn` 版本的问题，您可以尝试升级 `yarn`，或者切换到 `npm`。

同时在使用 `umi` 的时候可以参考 [UmiJS 官方文档](https://umijs.org/zh-CN/docs/getting-started) 进行学习和使用。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你提供的问题描述，可能是以下几个原因导致执行`yarn add @umijs/preset-ui -D`无效：

1. 未正确安装 `@umijs/preset-ui`模块，可以尝试执行`yarn add @umijs/preset-ui -D`命令来重新安装。
2. 可能是网络问题，尝试使用 `yarn` 命令添加模块之前，可以先执行 `yarn cache clean` 清理缓存，然后再执行 `yarn add @umijs/preset-ui -D` 命令。
3. 可能是 `yarn` 版本过旧，建议升级到最新版本，可以通过执行 `yarn --version` 来查看当前 `yarn` 的版本，然后去官方网站下载最新版本并安装。
4. 可能是项目中已有 `@umijs/preset-ui` 的依赖冲突，可以尝试删除项目下的 `node_modules` 目录，然后再执行 `yarn install` 命令重新安装所有依赖。

另外，你提到使用的是 `yran` 命令，可能是打错了，正确的命令应该是 `yarn`。如果你确实使用的是 `yran` 命令，请安装 `yarn` 并使用 `yarn` 命令来添加依赖。

希望以上解决方案能够帮助你解决问题，如果问题仍然存在，请提供更多的细节信息，以便进一步排查和解决。
