### ISSUE TITLE
没有devServer，设置启动端口只能从packge.json里设置，不太直观

### ISSUE THREAD

**Issue by FIWE2030** [ant-design/ant-design-pro#10548]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


用户提出的需求是希望在没有 `devServer` 的情况下，可以通过配置的方式设置前端项目的启动端口。当前的方法是通过修改 `package.json` 文件中的 `scripts` 属性来实现，但是用户认为这种方式不太直观。用户希望能够有更简便的方式来设置启动端口。

**Comment by chenshuai2144** [comment]
使用环境变量也可以。你可以 设置 `PORT`

https://umijs.org/docs/guides/env-variables#port
