### ISSUE TITLE
ant design pro components 官网页面渲染错乱 🐛 [BUG]

### ISSUE THREAD

**Issue by wufang0829** [ant-design/ant-design-pro#10557]
<img width="1425" alt="截屏2023-02-17 10 53 24" src="https://user-images.githubusercontent.com/34531752/219538986-e8f8f715-e56e-43c7-8a9d-648907352353.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢你向我反馈这个问题，我能够理解这给你工作和学习带来的不便，我会尽力为你提供帮助。

根据你提供的信息和截图，这个问题可能是由于浏览器缓存或者网络问题导致的渲染错误。请尝试以下解决方法：

1. 清除浏览器缓存：在浏览器中按下「Ctrl + Shift + Delete」可以打开清除缓存的页面，选择清除「缓存图片和文件」，然后尝试刷新页面。

2. 使用其他浏览器打开页面：如果第一种方法无效，请尝试使用其他浏览器打开页面，比如 Chrome 或者 Firefox。

3. 检查网络连接：请确保你的网络连接正常，可以通过打开其他网站测试。

如果以上方法仍然无效，请提供更多详细信息，例如：

- 你使用的浏览器和版本
- 你的操作系统和版本
- 你的网络环境
- 是否只有这个页面出现问题，还是其他页面也有问题

同时，你也可以在 Ant Design Pro 和 React 社区寻找相关的解决方案。Ant Design Pro 官方文档提供了一些常见的问题和解决方案，可以先参考一下：https://pro.ant.design/docs/faq-cn#%E5%89%8D%E7%AB%AF。React 社区也有很多活跃的成员和资料，可以帮助你解决问题。

**Comment by chenshuai2144** [comment]
fixed
