### ISSUE TITLE
🧐[问题 | question]关于定制主题配置configProvider的迷惑行为大赏

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design-pro#10553]
这是我定制主题后生成的主题配置
```json
{
  "token": {
    "borderRadius": 3,
    "wireframe": false,
    "fontSize": 12,
    "colorPrimary": "#3c7dd7",
    "colorInfo": "#3c7dd7"
  }
}
```
而现在有三种配置方式 分别是 defaultsetting，app.tsx中添加RuntimeAntdConfig ，umi的config文件中配置 antd 插件

那么问题来了，其中colorPrimary必须要在defaultSetting中配置才能生效，其余两种不生效
剩余属性只有配置在app.tsx中添加RuntimeAntdConfig ， 并且 在umi的config文件中的antd 插件块配置一个空的configProvider才能生效 直接配置到 configProvider 块中也无法生效

也就是说要想使我定制的主题生效我至少要改

1.defaultSetting中设置  
   ` "colorPrimary": "#3c7dd7"`

2.app.tsx中增加RuntimeAntdConfig 
```typescript
export const antd: RuntimeAntdConfig = (memo: { theme: { algorithm: DerivativeFunc<SeedToken, MapToken>; }; }) => {
  memo.theme ||= {};
  memo.theme.algorithm = theme.compactAlgorithm;

  memo.theme.token = {
     borderRadius: 1,
     wireframe: false,
     fontSize: 12,
     colorInfo: "#3c7d",
  }
  return memo;
};
```

3.umi的config配置一个空块？
```json
  antd: {
    configProvider: {
    },
  },
```

难道是我的打开方式不对吗

**Comment by pkaq** [comment]
补充，使用的antd pro ， antd ， umi均为最新版本

**Comment by iscmcloud** [comment]
@pkaq 布局的紧凑模式你能生效吗？
按照文档设置compact: true貌似没起作用

**Comment by pkaq** [comment]
在app.tsx中配置可以生效 umi那个他们似乎还没改

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，可能是因为`configProvider`的配置项覆盖了`RuntimeAntdConfig `的设置，导致你的定制主题不生效。

可以先尝试通过更改`configProvider`中的`theme`属性来覆盖antd的默认主题配置。例如，在`config.js`中的`antd`选项下，加入以下配置：

```js
{
  antd: {
    theme: {
      'primary-color': '#3c7dd7',
      ...
    },
    ...
  }
}
```

如果还是不生效，可以尝试调整`configProvider`的初始化时机，是否确保在`app.tsx`中执行之前已经进行初始化（即在`defaultSettings.ts`中已经进行了初始化）。

如果还有问题，可以尝试在`app.tsx`中使用`runtimeTheme`来直接设置主题。例如：

```tsx
import { runtimeTheme } from '@ant-design/pro-layout';

// ...

const MyLayout: React.FC = ({ children }) => {
  runtimeTheme.theme = {
    'primary-color': '#3c7dd7',
    ...
  };

  return (
    // ...
  );
};
``` 

更多信息可以参考官方文档：

- [ConfigProvider 配置默认主题样式][1]
- [定制主题][2]

[1]:https://ant.design/components/config-provider-cn/#api
[2]:https://ant.design/docs/react/customize-theme-cn

**Comment by pkaq** [comment]
显然机器人无法很好的理解和回答呀 其实我只想在一个地方修改统一配置就好而已 而不是像现在七零八落的改几个地方才生效

**Comment by chenshuai2144** [comment]
因为antd@4 和  antd@5 
然后还有procomponents的问题，这个我会想办法搞下，顺便改改umi的用法

**Comment by pynctdkon00** [comment]
+1， 文档实在有点混乱

假如需要全局修改主题色（包含SettingDrawer组件），需要修改下面两个文件

-  `defaultSetting.ts`文件中的`colorPrimary`

```typescript
const Settings: ProLayoutProps & {
  pwa?: boolean;
  logo?: string;
} = {
  // navTheme: 'realDark',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: 'SZSK',
  pwa: true,
  logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  iconfontUrl: '',
  colorPrimary: '#2950b8',
  token: {
    // 参见ts声明，demo 见文档，通过token 修改样式
    //https://procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F
  },
};
```

- `config.ts`文件中
```typescript
  antd: {
    theme: {
      dark: true,
      token: {
        borderRadius: 4,
        colorPrimary: '#2950b8'
      },
      algorithm: theme.darkAlgorithm,
    }
  },
```

**Comment by iscmcloud** [comment]
> 因为antd@4 和 antd@5 然后还有procomponents的问题，这个我会想办法搞下，顺便改改umi的用法
请问这个有改吗

**Comment by KYX1234** [comment]
太逆天了，给我的感觉是很割裂，一会看pro文档一会看umi的，搞了半天也没清楚在哪，最后跑来看评论区。就不能统一到defaultSettings配置吗，配个圆角还要去config里，真的绝了

**Comment by ychy00001** [comment]
> 太逆天了，给我的感觉是很割裂，一会看pro文档一会看umi的，搞了半天也没清楚在哪，最后跑来看评论区。就不能统一到defaultSettings配置吗，配个圆角还要去config里，真的绝了

哈哈 一样，手头正在改一个开源应用框架，这框架用的ant-design-pro开发的前端，我自己还改了一部分样式。过了两个月，作者从4.x升级到了5.x，直接给我改蒙了。貌似还不是按照官方的方式升级改造的。现在查官网从ant-design到ant-design-pro到umi都看了个遍。改了一周了也改不完，样式哪哪都不对，慢慢来 - -！
