### ISSUE TITLE
V6考虑加多标签吗？ 

### ISSUE THREAD

**Issue by scepter0430** [ant-design/ant-design-pro#10550]
V6加多标签和区块吗？

**Comment by pkaq** [comment]
#220

**Comment by iscmcloud** [comment]
如果你用的V6，应该是可以支持的，多页签在ant design pro里讨论这么多年，umi用到了v4版本，终于有一位大佬写了个插件，比较好集成，参考下面这个链接：
https://juejin.cn/post/7153525746751766559

**Comment by hggq** [comment]
官方怎么不内置一个

**Comment by pkaq** [comment]
插件内置了 文档没写

**Comment by hggq** [comment]
> 插件内置了 文档没写

有没有例子，官方脚手架没有这个

**Comment by pkaq** [comment]
有 只是文档没写而已
加配置项就行了
```
  keepalive: [/./],
  tabsLayout: {
    hasDropdown: true,
  },
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


谢谢你提供的信息。

关于为什么官方没有内置多标签页的功能，官方可能是出于减少代码复杂度和不增加额外功能的考虑吧。因为多标签页的需求是不是每个用户都需要的，而且实现多标签页功能的方式也有多种，根据用户的需求不同，实现方式也可能不同。

同时，Ant Design Pro 是一个基于 `umi` 和 `antd` 的前端框架，旨在帮助开发者快速搭建企业级中后台应用，而不是为每个可能的需求提供一个解决方案，因此官方也鼓励开发者根据业务需求自己扩展功能。

至于如何实现多标签页的功能，感谢你提供的信息，下面我提供一些参考资料：

- Pro-Layout 官方文档： https://prolayout.ant.design/components/layout-cn/

  Pro-Layout 提供了类似于 Chrome 浏览器标签页的多页面布局，可以在 config 配置和页面的路由配置中选择开启和关闭多标签页功能。

- umi-plugin-tabs 官方文档： https://github.com/SimonSiefke/umi-plugin-tabs

  umi-plugin-tabs 是一个基于 umi 的插件，可以为页面添加多标签页功能。然后你可以在 `config/config.js` 中配置 `tabsLayout` 和 `keepalive` 选项来开启和配置多标签页功能，具体可参考该插件的文档说明和示例代码。

- multi-tabs-demo：https://github.com/xiaoyudeguang/multi-tabs-demo

  一个基于 umi 和 antd 的多标签页示例项目，可供参考。

希望这些资料能对你有所帮助。

**Comment by johanazhu** [comment]
> 

这个ai回答，第一个链接找半天没找到，第二个、第三个文档404

**Comment by Aaron52077** [comment]
体验下 https://wuli-admin.gitee.io/react-mat-pro/#/dashboard 是否满足呢

**Comment by chenshuai2144** [comment]
要等react的离屏渲染最好之后才会有比较好的解决方案，在这之前官方不会提供

**Comment by sodagreen574** [comment]
> 体验下 https://wuli-admin.gitee.io/react-mat-pro/#/dashboard 是否满足呢

老哥 是否能公开一下这个仓库https://wuli-admin.gitee.io/react-antd-template

**Comment by gatspy** [comment]
V6又没希望了

**Comment by lilongjiu** [comment]
2024-07-15: 还要继续等？
