### ISSUE TITLE
🐛 [BUG] proxy设置无效

### ISSUE THREAD

**Issue by crashsol** [ant-design/ant-design-pro#10558]
下载6.0的模板后，设置proxy dev节点，启动项目后，不会自动代理
 dev: {
    // localhost:8000/api/** -> https://preview.pro.ant.design/api/**
    '/api/': {
      // 要代理的地址
      target: 'https://preview.pro.ant.design',
      // 配置了这个可以从 http 代理到 https
      // 依赖 origin 的功能可能需要这个，比如 cookie
      changeOrigin: true,
    },
  },

![image](https://user-images.githubusercontent.com/17925647/219931708-30b78e87-5ac4-4469-b71b-2683d082d240.png)

**Comment by zuoyi615** [comment]
我也有这个问题，你这边设置成功了吗

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，可以根据您提供的信息来提供一些解决方案。首先，可以尝试在终端中手动设置http_proxy和https_proxy。使用以下命令：

```bash
export http_proxy=http://yourproxyaddress:proxyport
export https_proxy=http://yourproxyaddress:proxyport
```

如果您使用的是Windows，您可以执行：

```bash
set http_proxy=http://yourproxyaddress:proxyport
set https_proxy=http://yourproxyaddress:proxyport
```

另外，您也可以修改默认的.env文件，为其添加相应的代理：

```bash
HTTP_PROXY=http://yourproxyaddress:proxyport
HTTPS_PROXY=http://yourproxyaddress:proxyport
```

请注意，这个.env文件只需要放置在你的根目录，它会被自动加载到你的应用程序中。

如果您还是无法解决问题，我建议您翻看一下您的代理服务器是否支持https代理，因为您使用的是https代理。

相关文档资料供您参考：

1. [CRA官网代理的使用](https://create-react-app.dev/docs/proxying-api-requests-in-development/)
2. [手动设置proxy的方式](https://stackoverflow.com/questions/30668643/npm-behind-a-proxy-server)
3. [.env文件的使用](https://create-react-app.dev/docs/adding-custom-environment-variables/)

**Comment by TOUCHERS** [comment]
要代理的地址改成https://proapi.azurewebsites.net/成功，原来的地址请求不了了好像

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


好的，很高兴听到您成功地设置了代理。如果您将来遇到其他与React有关的问题，欢迎再次咨询。如果您回头发现以前设置的代理不可用，请检查一下代理服务器的配置是否还正确。

**Comment by crashsol** [comment]
感谢

**Comment by cnbillow** [comment]
这个问题解决了？
