### ISSUE TITLE
Will Antd Pro be updated to match the new 5.2.1 Ant design system?

### ISSUE THREAD

**Issue by 4amramen** [ant-design/ant-design-pro#10551]
Will the Antd Pro crm template be updated to match the new look of the 5.2.1 Ant design system?  I see the 5.2.1 system has rounded edges and looks more modern than the current antd pro theme.

Are there any plans to do this in the future or a planned release date?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! Thank you for your inquiry.

As an AI language model, I do not have access to the specific development plans or release dates for Antd Pro or its templates. However, generally speaking, Antd Pro is regularly updated to incorporate new features and improvements based on feedback from the community.

In terms of updating the CRM template to match the new look of the 5.2.1 Ant Design system, it is possible that this may be included in a future update. I suggest checking the Antd Pro GitHub repository or official documentation for any announcements or updates regarding this.

Alternatively, if you are interested in updating the look of the CRM template yourself, you can try customizing the theme in Antd Pro by following their documentation on theming. This will allow you to modify the colors, fonts, and other style elements to match the new design system as desired.

I hope this helps! If you have any other questions or concerns, feel free to ask.

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据Ant Design官方的发布文档，Ant Design 5.0.0版本于2022年11月18日发布。根据此消息，可以预期Antd Pro将会进行相应的更新来匹配新的5.2.1 Ant Design系统。

关于Antd Pro CRM模板是否会更新以匹配新的5.2.1 Ant Design系统的外观，目前没有明确的计划或发布日期。但是，考虑到5.0.0版本的发布，未来可能会有相关的更新计划。

对于Antd Pro的更新流程，一般可以参考以下步骤：
1. 确认Antd Pro当前所使用的Ant Design版本。
2. 监控Ant Design官方的更新和发布信息，特别关注是否有与Ant Design 5.2.1系统匹配的更新。
3. 更新Antd Pro依赖的Ant Design版本，可以通过修改项目中的package.json文件中的相关依赖版本号，然后运行npm install或yarn install来进行更新。
4. 根据Ant Design官方提供的更新文档，对Antd Pro的代码进行相应的调整，以适配新的Ant Design系统。可能需要修改样式、组件使用方式等。
5. 运行项目，并进行测试，确保更新后的Antd Pro在浏览器中正常运行并符合预期的外观和功能。

在这个过程中，前端工程化工具及框架如Umi和React可以提供便利，比如使用脚手架工具初始化项目、自动化构建、热更新等功能。

值得一提的是，前端性能优化也是一个重要的方面。在更新Antd Pro时，可以考虑优化项目的加载速度、减少不必要的资源请求等，以提高用户体验和整体性能。

总结来说，根据Ant Design官方发布的5.0.0版本，可以预期Antd Pro将会进行更新以匹配新的5.2.1 Ant Design系统的外观。虽然目前没有明确的计划或发布日期，但可以关注Ant Design官方的更新信息，并根据更新文档对Antd Pro进行相应的调整和优化。
