### ISSUE TITLE
@ant-design/pro-cli 和 create-umi 有什么区别

### ISSUE THREAD

**Issue by chentianxin** [ant-design/ant-design-pro#10569]
### 🧐 问题描述

pro-cli 和 create-umi 都能创建 antd-pro 项目，他们有什么区别呢，我应该用哪个或者推荐用哪个呢？

### 💻 示例代码
```sh
npm i @ant-design/pro-cli -g
pro create myapp
// 或者
pnpm dlx create-umi@latest
```

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 回答

pro-cli 和 create-umi 都是创建 antd-pro 项目的工具，旨在帮助开发者更快速地开始 antd-pro 项目。

它们的区别主要在以下方面：

1. 命令行工具语法不同

pro-cli 的语法是：

```sh
pro create <projectName>
```

create-umi 的语法是：

```sh
create-umi <projectName> --antd --preset ant-design/pro-blocks
```

2. pro-cli 提供了更多的插件选择

pro-cli 在创建项目时提供了更多插件选择，可以方便地选择所需要的插件进行安装。例如：

```sh
pro create myapp --use-npm --template simple --packageName @antv/g2 --packages @antv/data-set,@antv/g2-plugin-slider
```

create-umi 则仅提供了两个选项：antd 和 preset。

3. create-umi 可以生成更多类型的项目

除了 antd-pro 项目外，create-umi 还可以生成 umi 空项目、dva 项目等类型的项目。

综上所述，如果你只是需要快速生成一个 antd-pro 项目，推荐使用 pro-cli 工具。如果你需要创建不同类型的项目或者需要自定义更多的配置，可以使用 create-umi 工具。

更多关于 pro-cli 和 create-umi 的详细信息可以参考官方文档：

- [pro-cli](https://pro.ant.design/docs/getting-started-cn)
- [create-umi](https://umijs.org/zh-CN/docs/getting-started)

**Comment by chenshuai2144** [comment]
create-umi  主要还是方便 umi ，所以有很多模板可以选择

@ant-design/pro-cli 只支持 pro，推荐你用 @ant-design/pro-cli
