### ISSUE TITLE
🧐[问题 | question]安装脚手架无法运行

### ISSUE THREAD

**Issue by zhibo59** [ant-design/ant-design-pro#10566]
根据官方文档通过pro create myapp 下载
下来后运行npm install   
或者tyarn 进行安装就会在最后这一步报错，
报错信息如下： 
ant-design-pro@6.0.0 postinstall D:\2023work\antdProUmi4Template\myapp
> max setup

� Hello PRO
info  - [你知道吗？] 全局布局用 layout ，多层布局用 wrappers ，从文档了解更多路由的控制方法，详见 https://umijs.org/docs/guides/routes
Using openapi Plugin
info  - generate files
info  - Preparing...
fatal - TypeError: build is not a function
    at Hook.fn (D:\2023work\antdProUmi4Template\myapp\node_modules\@umijs\preset-umi\dist\features\prepare\prepare.js:67:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async D:\2023work\antdProUmi4Template\myapp\node_modules\@umijs\core\dist\service\service.js:182:15
fatal - A complete log of this run can be found in:
fatal - D:\2023work\antdProUmi4Template\myapp\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@6.0.0 postinstall: `max setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@6.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

OS:umi@4.02

Node：14.9

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很抱歉听到您的安装过程出了问题。根据报错信息来看，问题可能出现在 `@umijs/preset-umi` 这个包上。可以尝试升级这个包，并重新运行安装命令。

具体操作可以按照以下步骤进行：

1. 首先可以尝试清空本地的 npm 缓存，有时候缓存会导致安装问题。可以运行以下命令清空 npm 缓存：

   ```
   npm cache clean --force
   ```

2. 接下来升级 `@umijs/preset-umi` 包。可以运行以下命令升级这个包：

   ```
   npm install @umijs/preset-umi@latest
   ```

   或者

   ```
   yarn add @umijs/preset-umi@latest
   ```

3. 在升级完这个包后，重新运行安装命令：

   ```
   npm install 
   ```

   或者

   ```
   yarn 
   ```

如果以上操作无法解决问题，可以尝试重建项目，重新创建新的 react 项目。

如果问题依然存在，可以在 GitHub 上创建一个问题报告，以便开发人员帮助您解决问题。

同时，您需要掌握一定的 npm 和 Umi 的知识，以便更好地维护和管理您的应用程序。Documentation：https://umijs.org/docs/。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据报错信息和给出的环境信息，问题可能出现在以下几个方面：

1. 依赖安装不完整或者依赖冲突导致的错误。
   解决方案：可以尝试删除 `node_modules` 文件夹后重新执行 `npm install` 或者 `yarn` 来重新安装依赖。

2. 脚手架版本兼容性问题。
   解决方案：根据报错信息可以看到是 `ant-design-pro@6.0.0` 的 `postinstall` 脚本报错，可以尝试将脚手架版本降低，比如使用 `ant-design-pro@5.x.x` 版本。或者查看官方文档或者社区中是否有其他用户也遇到相同问题并且提供了解决方案。

3. 缺少必要的环境配置或者配置错误。
   解决方案：确保已经安装了正确的 Node.js 版本，并且已经配置好了相关的环境变量。同时，也可以查看是否有必要的项目配置文件（比如 `.umirc.js` 或者 `config/config.js`）是否存在且正确配置。

4. 其他问题。
   解决方案：根据报错信息查看有关的日志文档，尝试根据日志信息进一步定位问题。如果问题仍然存在，可以考虑在社区中提问或者向脚手架的维护者寻求帮助。

请根据具体情况逐步尝试以上解决方案，并检查是否能够解决问题。如果问题仍然存在，请提供详细的报错信息、环境信息和相关配置，以便进一步分析和定位问题。
