### ISSUE TITLE
🐛 [BUG]  Antd pro ProFormList 在 ModalForm中 alwaysShowItemLabel 属性行为不正确

### ISSUE THREAD

**Issue by sequarius** [ant-design/ant-design-pro#10568]
### 🐛 bug 描述
设置ProFormList  alwaysShowItemLabel  = {false} 依然会显示每行的的 label ，与设置为true行为一致。只在Ant Design Pro中使用会出现这个问题，单独使用ProFormList 无法复现。

### 📷 复现步骤 | Recurrence steps
1. 初始化pro项目
2. 创建ProFormList  
3. 设置alwaysShowItemLabel  = {false} 

### 🏞 期望结果 | Expected results
与单独使用ProFormList一致 可以使用 alwaysShowItemLabel  = {false}  关闭每行label

### 💻 复现代码 | Recurrence code
使用Ant Design Pro 无法隐藏单行label
https://github.com/sequarius/ant-design-pro/blob/master/src/pages/Welcome.tsx
单独使用ProFormList 正常
https://codesandbox.io/s/proform-list-forked-o275qn?file=/App.tsx

### © 版本信息

- Ant Design Pro 版本: "6.0.0"
- umi 版本 umijs/umi: "^4.0.52",
- 浏览器环境 Chrome 110.0.5481.177
- 开发环境 Windows NT 6.4

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/7238573/221403621-84062ae1-f924-46b2-9149-778bebcdf92e.png)

**Comment by echoyl** [comment]
同样碰到这个问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，关于该问题可能是Ant Design Pro框架的一个bug导致的，可以暂时采用以下两种方式来实现想要的效果：

方式一：通过重写CSS来隐藏每行的label

在你的样式文件中添加以下样式：

```
/* 隐藏label */
.ant-form-item-label > label {
  display: none;
}
```
这样每行就不会显示对应的label了。

方式二：通过重写ProFormList中的render函数来实现

实现代码如下：
```
<ProFormList
  alwaysShowAddButton
  name={['users']}
  fieldProps={{
    ...inputLayout,
    label: false,
    colon: false,
  }}
  {...formItemLayout}
>
  {(fields, { add, remove }) => {
    return (
      <>
        {fields.map((field, index) => (
          <div key={field.key}>
            <ProForm.Item label="姓名" {...formItemLayout}>
              <Input.Group compact>
                <Form.Item
                  {...field}
                  name={[field.name, 'first']}
                  fieldKey={[field.fieldKey, 'first']}
                  rules={[{ required: true, message: '必填' }]}
                >
                  <Input placeholder="姓" />
                </Form.Item>
                <Form.Item
                  {...field}
                  name={[field.name, 'last']}
                  fieldKey={[field.fieldKey, 'last']}
                  rules={[{ required: true, message: '必填' }]}
                >
                  <Input placeholder="名" />
                </Form.Item>
              </Input.Group>
            </ProForm.Item>
            {index !== fields.length - 1 && <Divider />}
          </div>
        ))}
        <ProForm.Item {...formItemLayout}>
          <Button type="dashed" onClick={() => add()} block>
            <PlusOutlined /> 添加用户
          </Button>
        </ProForm.Item>
      </>
    );
  }}
</ProFormList>
```
这种方法主要是通过设置fieldProps，将每行的label设为false，达到隐藏label的效果。

你可以根据实际需要来选择具体的实现方式。希望对你有所帮助。

**Comment by chenshuai2144** [comment]
是有这个问题，procomponents那边有相同的issue

https://github.com/ant-design/pro-components/issues/5200

**Comment by echoyl** [comment]
> 是有这个问题，procomponents那边有相同的issue
> 
> [ant-design/pro-components#5200](https://github.com/ant-design/pro-components/issues/5200)

跳到这个issue 更新了@ant-design/pro-components 还是无效
在 BetaSchemaForm使用 formList 没有出现每行都有label的问题
单独使用ProFormList 会出现这个问题
