### ISSUE TITLE
🐛 [BUG]添加 dynamicImport 配置以后打包报错

### ISSUE THREAD

**Issue by Pentium286** [ant-design/ant-design-pro#10567]
### 🐛 bug 描述

`/config/config.js`
配置了`dynamicImport`以后报错

### 📷 复现步骤 | Recurrence steps

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1262247/221118407-df847d5a-1fcd-4751-8cfa-968dbbbc7358.png">
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/1262247/221118448-611e2f50-0e19-47db-8f5d-e3d8d4a60873.png">

### 🏞 期望结果 | Expected results

可以正常打包

### 💻 复现代码 | Recurrence code

```
dynamicImport: {},
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 "@umijs/max": "^4.0.52",
- 浏览器环境 版本 110.0.5481.177（正式版本） (arm64)
- 开发环境 [e.g. mac OS] 13.2.1 (22D68)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的信息，似乎是缺少了相应的插件依赖。可以尝试检查是否已经安装了 `umi-plugin-react` 插件，并且确认是否在 `config.js` 中配置了这个插件。如果没有安装或者没有配置这个插件，可以按照以下步骤尝试解决问题：

1. 安装 `umi-plugin-react` 依赖

在终端中输入以下命令，安装 `umi-plugin-react`：

```shell
npm install --save-dev umi-plugin-react
```

2. 配置 `umi-plugin-react` 插件

在 `config.js` 文件中，添加以下配置：

```javascript
export default {
  plugins: [
    ['umi-plugin-react', {
      dynamicImport: {},
    }],
  ],
}
```

确保配置了插件依赖后，再次进行打包尝试。

希望这个解决方案对您有所帮助，更多关于 umi-plugin-react 的配置和使用可以参考官方文档：https://umijs.org/plugins/plugin-react.html#dynamicimport。
