### ISSUE TITLE
🐛 [BUG]missing: http://localhost:8000/mf-dep_vendors-node_modules_core-js_index_js.b33679d7.async.js

### ISSUE THREAD

**Issue by tianyuanzoe** [ant-design/ant-design-pro#10562]
### 🐛 bug 描述
import { RequestConfig } from 'umi';后出现该问题，已经删除.umi文件夹重启动很多次了，还是无法解决

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/116246552/220088293-776fc4cf-32aa-452d-8b21-47fb7be67827.png">

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据你提供的信息，我了解到你在使用 Ant Design Pro，遇到了关于 umi 的问题。谢谢你提供的截图，但是缺少详细的错误信息，所以我无法得知具体错误的原因。不过根据你提供的导入语句 `import { RequestConfig } from 'umi';` 看起来是和 umi 有关的问题。

首先，你可以尝试删除 `node_modules` 文件夹以及 `package-lock.json` 文件，再运行 `npm install` 命令，看看是否能够解决问题。如果这并没有起作用，你可以尝试更新 umi，运行 `npm update umi` 命令即可。如果仍然没有解决问题，可以尝试清除缓存再重新启动，执行以下命令：

```
npm cache clean --force
rm -rf node_modules
npm install
npm start
```

如果还是不行，可能需要考虑升级或者降级 Ant Design Pro 版本，或者向 Ant Design Pro 官方提出一份 issue 寻求帮助。

总之，这个问题可能会有多种不同的原因，需要根据具体情况具体分析，建议多尝试几种方案，以及多查看错误信息。祝你好运！

**Comment by chenshuai2144** [comment]
你需要把lock删除，并且 执行 `git clean -dfx`
