### ISSUE TITLE
v5版本打包 样式和本地不一样🧐[问题 | question]

### ISSUE THREAD

**Issue by YuDaChao** [ant-design/ant-design-pro#10578]
### 🚑 其他信息 | Other information

本地样式：
![13011677815107_ pic](https://user-images.githubusercontent.com/23699765/222627189-21c36131-9d7e-4b47-8633-44e5e7b3f467.jpg)
上线后的样式：
![13001677815096_ pic](https://user-images.githubusercontent.com/23699765/222627218-cbf0d451-0010-4eac-9e95-3790d4683cae.jpg)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 回答 | Answer

根据提供的信息可以看出，问题出现在打包后的样式和本地不一样。这个问题可能和 webpack 打包时的配置有关。可以尝试以下解决方案：

1. 确认 webpack 打包时是否已经压缩了样式。如果没有被压缩，可以添加 css 压缩插件，如 optimize-css-assets-webpack-plugin。

2. 确认 webpack 打包时是否已经使用了 css module。在组件中引用样式时加入 :local 即可使用 css module。

   示例：

   ```
   import styles from "./styles.module.css";

   <div className={styles.localClass}>使用 css module</div>
   ```

3. 如果以上两个方法不起作用，可以尝试在 webpack 的配置文件中添加 resolve.alias。将打包后的样式文件名与组件中引用时的文件名一致即可。

   示例：

   ```
   resolve: {
     alias: {
       "./styles.css$": "./styles.module.css"
     }
   }
   ```

   更多关于 webpack 的配置可以查看官方文档：https://webpack.js.org/configuration/

**Comment by chenshuai2144** [comment]
这个应该是版本的问题，你更新一下你的本地
