### ISSUE TITLE
👑 [需求 | Feature] 可否加一个开关用来控制build后是否开启代理？

### ISSUE THREAD

**Issue by wrote-code** [ant-design/ant-design-pro#10572]
### 🥰 需求描述 | Requirements description

目前版本中，antd pro 编译后代理配置不会生效，可否在将来版本中加一个开关，用来控制 build 后代理是否生效？

目前我在给自己写一个开箱即用的系统，前台使用 antd pro，后台使用 springboot。根据官方文档，只需要将 antd pro 编译产物复制到 springboot 的 `resources/static` 目录下，就可以在 springboot 中直接访问前台。由于打包后代理失效，因此 `/api/` 没有被替换掉，访问后台接口会报 404。

在实际开发中，通常会将前后台文件分开部署，此时替换 `/api/` 的功能由前台服务器实现。在我的系统中，我可以通过给后台接口增加上下文 `/api/` 来解决 404 问题。使用服务器的方案需要修改服务器配置，使用后台方案需要手动改代码（springboot 默认上下文是根目录），那么是否可以在前台增加一个开关，用来控制编译后代理是否生效，默认不生效？

另外，我直接复制前台文件到后台的原因是，希望我的系统下载下来就能用，而不需要配置一些乱七八糟的环境（对非程序员来说）。事实上还是需要下载 jre，但是对于第一次使用此系统的非程序员来说，比起同时配置 jdk+nginx，只配置一个 jdk 还是比较轻松的。另外，也可以通过启动脚本来实现什么都不用配置就可以一键启动的效果，这种情况下就需要通过第三方网盘发布包含了 jdk 的 zip 包，然后加入启动脚本。

**Comment by wrote-code** [comment]
深夜补充：经过刚才的多次验证，发现以下问题

首先，在开发环境下，前台用hash和browser，后台有五上下文，这两个条件随便搭配都可以正常使用，即接口调用正常，页面刷新后不会404，但是，当打包后，会出现以下情况：

| 路由 | 上下文 | 接口 | 刷新页面 |
| --- | --- | --- | --- |
| hash | / | 404 | 200 |
| hash | /api | 200 | 404 |
| browser | /api | 200 | 404 |
| browser | / | 404 | 404 |

其中，使用上下文后，首页直接404，使用 localhost:8080/api/+接口路径可以访问，但是首页都进不去，就算能访问接口也没什么用。一顿排列组合后，得出初步结论：三四列不会同时出现200 🤣🤣🤣

[前台代码](https://github.com/wrote-code/media-ui)，[后台代码](https://github.com/wrote-code/media)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供方案解决问题。根据您提供的信息，我们可以看出问题可能出现在路由的配置上。

在前台打包后，路由会根据缺省值来设置，需要调整路由的 base 属性。同时根据您提供的方案，也需要将 publicPath 设置为 /api/，这样才能让编译后的前台正确地发送请求。

在后台开启代理，路由上下文设置为 /api/，就可以正确地代理请求。如下所示：

```javascript
// 前台路由配置
{
  path: '/',
  component: Index,
  routes: [{ path: '/test', component: Test }]
}
// 生产环境
// 注意 publicPath 的值以 /api/ 结尾，下同
// 对于路径别名等自定义配置，请按照自己的情况修改
<BrowserRouter basename="/api/" />
// 对于 hash 路由，请将 above 改为下面这行
<HashRouter basename="/api/" />

// 后台代理配置
{
  context: '/api/*',
  target: 'http://localhost:8080/',
  changeOrigin: true
}
```

最后需要注意的是，由于使用了 /api/ 上下文，在生产环境下需要在后台代理配置上开启 pathRewrite，将请求路径中的 /api/ 替换掉，否则会出现重复的 /api/。如下所示：

```javascript
// 后台代理配置
{
  context: '/api/*',
  target: 'http://localhost:8080/',
  changeOrigin: true,
  // 将请求路径中的 /api/ 替换掉，这样前台就可以正确地发送请求
  pathRewrite: {
    '^/api': ''
  }
}
```

希望以上内容对您有所帮助。同时，建议在使用 antd pro 和 springboot 的时候，遵循官方文档建议，前后端部署分离，以避免此类问题的发生。

**Comment by chenshuai2144** [comment]
umi 只是个前端工具。作为一个服务器是不稳定的。我们也不会做这样的事情
