### ISSUE TITLE
修改主题 部分组件不生效🧐[问题 | question]

### ISSUE THREAD

**Issue by YuDaChao** [ant-design/ant-design-pro#10579]
### 🧐 问题描述 | Problem description
修改主题后，Button组件type=link 样式没有生效

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/23699765/222627501-f33a9e61-1ec8-420a-ae7e-08b0494dc09a.png)
![image](https://user-images.githubusercontent.com/23699765/222627781-353c8784-19c2-4e71-82e4-5e884793317f.png)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 回答 | Answer

这个问题可能跟在修改主题后没有重新编译项目有关，因为一些 CSS 文件需要重新生成，只有这样样式才会应用于你的组件。可以在你的终端中运行以下命令，重新编译项目并在浏览器中预览更改：

```bash
npm start
```

如果重新编译项目后问题仍未解决，请检查是否正确地引用了主题中的样式，以及样式是否与 Button 组件相关联。此外，你还可以通过使用浏览器开发者工具来进一步调试此问题。在谷歌浏览器或火狐浏览器中按 F12 进入开发者工具界面，可以检查元素的样式和应用到它的 CSS 规则。 

例如，以下代码应该被放到 `index.js` 中:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { ThemeProvider } from 'styled-components';

import Button from './Button';

const theme = {
  primaryColor: 'red',
  secondaryColor: 'blue',
};

ReactDOM.render(
  <ThemeProvider theme={theme}>
    <Button type="link">Link</Button>
  </ThemeProvider>,
  document.getElementById('root'),
);
```

请注意，`<ThemeProvider>` 组件应该包裹整个 App，而不仅仅是 Button 组件所在的文件。此外，你可以在组件中添加默认的 CSS 样式或使用 `styled-components` 来进一步管理你的样式，以确保样式与组件相匹配。例如：

```javascript
import styled from 'styled-components';

const Button = styled.button`
  background-color: ${props => props.theme.primaryColor};
  color: ${props => props.theme.secondaryColor};
  border: none;
  border-radius: 4px;
  padding: 10px 20px;
  text-decoration: none;
  &:hover {
    cursor: pointer;
    opacity: 0.8;
  }
`;

export default Button;
```

这应该放在独立的 `Button.js` 文件中，`index.js` 只需要引用 `Button` 组件即可。

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/max/antd#theme

https://ant.design/docs/react/customize-theme-cn

看这里 debug 下试试
