### ISSUE TITLE
AssertionError [ERR_ASSERTION]: filePath not found /node_modules/antd/es/theme

### ISSUE THREAD

**Issue by zFitness** [ant-design/ant-design-pro#10570]
### 📷 复现步骤 | Recurrence steps
使用 官方文档，新建的 UMI3 项目出现了问题。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zFitness** [comment]
这个 node_modules/antd/es/theme 是 antd5 才有的目录

**Comment by zFitness** [comment]
解决了，如下代码导致的, 这里的 代码是从 antd5粘贴的, antd4没有theme
```
import { theme } from 'antd';
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，确实，使用 `theme` 变量可以获取 antd 的主题变量，但是该变量在 antd4 中是不存在的，所以会报错找不到该路径。

解决方法：在 antd4 中不需要使用 `theme` 变量，如果需要自定义主题变量可以参考 antd4 官方文档的 [配置主题变量](https://ant.design/docs/react/customize-theme-cn) 部分。

下面是一个简单的 antd4 自定义主题变量的示例：

1. 在 `src` 目录下新建 `custom.less` 文件，写入以下内容：

   ```
   @import "~antd/dist/antd.less"; /* 引入 antd 的样式 */

   /* 自定义主题变量 */
   @primary-color: red;
   ```

2. 在 `config/config.js` 文件中配置下面的内容：

   ```
   export default {
     // ...
     chainWebpack(config) {
       // 引入 less 文件，注意文件路径根据自己实际情况进行修改
       config.module.rule('less')
         .use('less-loader')
         .tap(options => ({
           ...options,
           lessOptions: {
             modifyVars: { ...require('../src/custom.less') }, // 引入自定义主题变量
             javascriptEnabled: true,
           },
         }));
     },
   };
   ```

然后重新启动项目即可看到主题变量被自定义的效果。

**Comment by chenshuai2144** [comment]
antd@4 latest 版本增加了这个路径，升级一下 antd 就能好

**Comment by zFitness** [comment]
> antd@4 latest 版本增加了这个路径，升级一下 antd 就能好

可是我这里是 antd5 诶

**Comment by chenshuai2144** [comment]
antd5 不会有这个问题的，是不是没安装成功？

**Comment by zFitness** [comment]
> antd5 不会有这个问题的，是不是没安装成功？

我这里是 ant-design 脚手架生成的项目

**Comment by Deja-vuuu** [comment]
> > antd5 不会有这个问题的，是不是没安装成功？
> 
> 我这里是 ant-design 脚手架生成的项目

我也有这个问题 我就直接安装的 "antd": "^5.3.1",
<img width="962" alt="image" src="https://user-images.githubusercontent.com/27748682/225531320-4c9f712c-bea9-4199-a0ab-e39dd51005ec.png">

**Comment by flyingmylo** [comment]
> > > antd5 不会有这个问题的，是不是没安装成功？
> > 
> > 
> > 我这里是 ant-design 脚手架生成的项目
> 
> 我也有这个问题 我就直接安装的 "antd": "^5.3.1", <img alt="image" width="989" src="https://user-images.githubusercontent.com/27748682/225531482-23b2de64-d861-475d-bba5-3543ffcb8a13.png">

我也是同样的错误，请问解决了吗？

版本：
"antd": "^5.3.1"
"umi": "3.5.8"

![image](https://user-images.githubusercontent.com/22828986/225860673-e0d466ee-a515-4419-b31c-8560c58713a7.png)
