### ISSUE TITLE
🐛 [BUG] pro6黑暗模式下，左侧导航菜单栏在缩进后，弹出子菜单背景色不正确

### ISSUE THREAD

**Issue by iodeal** [ant-design/ant-design-pro#10589]
### 🐛 bug 描述

左侧导航菜单栏在缩进后，弹出子菜单背景色不正确

### 📷 复现步骤 | Recurrence steps
- pro create 新建项目并运行
- 点击右侧配置齿轮按钮，整体风格选择“暗色风格”，导航模式选择“混合模式”
- 点击左侧导航栏的缩进箭头，然后鼠标停留在“权限”的导航图标(王冠)上，弹出来的子菜单，呈白板状。

### 🏞 期望结果 | Expected results

左侧导航菜单缩进后，弹出子菜单适配主题色。

### © 版本信息

- Ant Design Pro 版本: 6 beta
- umi 版本  4
- 浏览器环境 Chrome Version 110.0.5481.177 (Official Build) (x86_64)
- 开发环境  mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/25092870/223029722-eaf4aa13-9ef8-46f5-94ee-0010c3fbd56c.png)

**Comment by crazyurus** [comment]
同样遇到了，定位了下应该是 `pro-components` 的问题，提了 PR https://github.com/ant-design/pro-components/pull/6721/files

**Comment by chenshuai2144** [comment]
已经修复了，等发布把
