### ISSUE TITLE
🧐[问题 | question] How to set the base border radius?

### ISSUE THREAD

**Issue by chuanhhoang** [ant-design/ant-design-pro#10584]
In config/config.ts I set this:

```
theme: {
    '@border-radius': 10
}
```

But it doesn't seem to change anything.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


To set the base border radius for your React project using Ant Design, you can customize the default theme variable `@border-radius`. However, in your case, it seems that the theme variable is not being applied correctly.

Here are some steps you can take to troubleshoot the issue:

1. Make sure that the `config/config.ts` file is being imported and used correctly in your project.
2. Confirm that you are using a version of Ant Design that supports theme customization. This feature was introduced in version 4.0.0.
3. Check that the `@border-radius` variable is a valid theme variable in your version of Ant Design. You can find a list of available variables in the Ant Design documentation.

Once you have confirmed these steps, you can try modifying the `@border-radius` variable in your `config/config.ts` file again. Here is an example of how to set the border radius to 10px:

```
// config/config.ts
export default {
  theme: {
    '@border-radius-base': '10px',
  },
};
```

After making these changes, you may need to run your project again to see the updated border radius.

You can find more information about customizing Ant Design theme variables in the documentation: https://ant.design/docs/react/customize-theme.
