### ISSUE TITLE
菜单栏收缩动画诡异🐛 [BUG]

### ISSUE THREAD

**Issue by tigerzhou-cool** [ant-design/ant-design-pro#10581]
V6 菜单栏是怎么回事？ 收缩动作诡异，二级菜单加了后 样式也太难看了吧，感觉有点敷衍了事的样子？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。




抱歉听到您遇到的问题。可以提供更多细节和代码示例吗？我需要更具体的信息来帮助您解决这个问题。

1. 关于菜单栏收缩动画诡异的问题，请提供你的代码以及你期望的效果。目前，我可以建议您使用CSS transition或CSS animation来创建菜单栏收缩动画。以下是一个基本的CSS transition示例：

```
ul {
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
}

ul.open {
  max-height: 1000px;
}
```

2. 关于样式问题的话，您也可以提供一些代码和更多细节。我们可以一起来解决这个问题。如果您想要增加二级菜单样式的话，建议使用CSS伪类来实现。以下是一个示例：

```
.nav > li:hover > ul {
  display: block;
}

.nav ul {
  display: none;
  position: absolute;
  top: 100%;
}

.nav ul li {
  float: none;
}
```

上述代码将隐藏二级菜单，直到鼠标悬停在一级菜单上时才显示出来。您可以自由更改样式以适应您的应用程序。

最后，如果您对React有任何疑问，请参阅React官方文档以获取更多信息。如果您对CSS或其他方面有任何疑问，请随时询问，我们将尽力为您解决问题。

**Comment by tigerzhou-cool** [comment]
V6 二级菜单选中后，收缩菜单再展开，2级菜单内容会出现在菜单栏左上角。 而且展开收缩动作 菜单会明显抖动一下，我直接安装了就是这样啊没有什么修改

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能与CSS样式设置有关。收缩菜单，展开菜单和选定某个菜单时，可能会导致元素重新布局，从而出现抖动的情况。你可以尝试在CSS中添加transform和transform-origin属性来避免元素重新布局。

以下是一个修改后的示例：

```
ul {
  max-height: 0;
  overflow: hidden;
  transition: max-height 0.2s ease-out;
  transform-origin: top left;
}

ul.open {
  max-height: 1000px;
  transform: scale(1); 
}
```

这里添加了transform和transform-origin属性。transform-origin属性指定了变换基点的位置，这里设置为左上角，从而减少了菜单抖动的情况。transform属性指定变换类型和参数，这里使用scale(1)来保持菜单的原始大小。

请注意，在以上示例中，transform-origin设置为top left只是适用于从上向下展开菜单的情况。如果你的菜单从下往上展开，你可能需要设置成bottom left。

关于二级菜单在左上角出现的问题，可能与CSS样式和JS代码有关。可以提供更多关于你的代码和CSS样式的细节吗？这样我们更能理解问题在哪里，然后一起找到解决方法。

**Comment by chenshuai2144** [comment]
antd的tooltip有个bug，等下修复

**Comment by TangDeYu** [comment]
https://github.com/ant-design/ant-design-pro/assets/52319042/ea7291e3-82ab-4c49-a20f-48d8fe27062e

目前已经影响使用了，暂时还没解决  @chenshuai2144
