### ISSUE TITLE
🧐[问题 | question] 如何通过 switch button 动态切换 light \ realDark

### ISSUE THREAD

**Issue by GuolongCyber** [ant-design/ant-design-pro#10585]
### 🧐 问题描述 | Problem description

想做一个通过 Switch 开关然后一键动态切换主题 （ light \ realDark）

该如何实现呢？

**类似官方文档 header的这个功能：**
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/83916371/222974556-cf5d0756-736d-4bac-84b9-0e135c061a5f.png">

附上链接：https://pro.ant.design/zh-CN/docs/dynamic-theme#pro-%E8%87%AA%E5%B8%A6%E7%9A%84%E7%BB%84%E4%BB%B6

**版本：Ant-design Pro V5 (5.2.0)**

谢谢

**Comment by iodeal** [comment]
import { Switch } from 'antd';
import React from 'react';
import { useModel } from '@umijs/max';
import { useEmotionCss } from '@ant-design/use-emotion-css';
import defaultSettings from '../../../config/defaultSettings';
const DarkSwitch: React.FC = () => {
    const darkSwitchClassName = useEmotionCss(({ token }) => {
        return {
            display: 'flex',
            top: '50%',
            transform: 'translate(0, -50%)',
        };
    });
    const {refresh, setInitialState } = useModel('@@initialState');
    return (
        <Switch
            className={darkSwitchClassName}
            checkedChildren="☀️"
            unCheckedChildren="🌙"
            defaultChecked={defaultSettings.navTheme != "realDark"}
            onClick={(checked: boolean) => {
                if (checked) {
                    defaultSettings.navTheme = "light"
                } else {
                    defaultSettings.navTheme = "realDark"
                }
                setInitialState((s) => ({ ...s, settings: defaultSettings }));
                refresh()
            }}
        />
    );
};

export default DarkSwitch;

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


针对你的问题，我这里提供一种实现方法。你可以先创建一个 Switch 组件，然后通过监听点击事件来动态修改主题。具体实现可以参考以下代码：

```jsx
import { Switch } from 'antd';
import React from 'react';
import { useModel } from 'umi';
import defaultSettings from '../../config/defaultSettings';

const ThemeSwitch: React.FC = () => {
  const { refresh, setInitialState } = useModel('@@initialState');

  const handleSwitchChange = (checked: boolean) => {
    const settings = { ...defaultSettings, navTheme: checked ? 'realDark' : 'light' };
    setInitialState((s) => ({ ...s, settings }));
    refresh();
  };

  const isRealDark = defaultSettings.navTheme === 'realDark';

  return (
    <Switch
      checkedChildren="🌜"
      unCheckedChildren="☀️"
      defaultChecked={!isRealDark}
      onClick={handleSwitchChange}
    />
  );
};

export default ThemeSwitch;
```

这里的默认配置是通过 defaultSettings.navTheme 来控制主题样式。你需要在 config/defaultSettings.ts 中进行配置。此外，我们使用了 umi 的 useModel 钩子来更新主题配置，刷新页面以加载新的主题。

使用该 Switch 组件时，只需要在需要的页面引入即可。例如：

```jsx
import React from 'react';
import ThemeSwitch from '@/components/ThemeSwitch';

const HomePage = () => {
  return (
    <div>
      <h1>Welcome to My Homepage</h1>
      <ThemeSwitch />
    </div>
  );
};
```

希望这个解决方案不仅对你的问题有帮助，也对 React 和 Antd 的使用有所启示。

**Comment by GuolongCyber** [comment]
解决了问题 感谢帮助！ @chenshuai2144 @iodeal  🙏

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


不客气，很高兴能帮到您!如果还有其他问题，随时欢迎提问。

**Comment by haobarry** [comment]
> 
代码不对
在umi4中 refresh()不起作用

**Comment by iodeal** [comment]
> 

就是在umi4中使用的。看看你的umi的插件有没有包含：initialState

**Comment by haobarry** [comment]
> > 
> 
> @haobarry 就是在umi4中使用的。看看你的umi的插件有没有包含：initialState

肯定有啊，没有就没办法设置更换initialState的值了，我其实之前我就做好切换主题的代码，不过有时候切换完主题后，page上css样式有失效，我看到上面的代码上有refresh()这个方法用来刷新，但是我使用后，切换主题的功能也失效了，查了下是umi3里的api

**Comment by chenduxiuhaha** [comment]
> ```js
> navTheme
> ```



> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 针对你的问题，我这里提供一种实现方法。你可以先创建一个 Switch 组件，然后通过监听点击事件来动态修改主题。具体实现可以参考以下代码：
> 
> ```js
> import { Switch } from 'antd';
> import React from 'react';
> import { useModel } from 'umi';
> import defaultSettings from '../../config/defaultSettings';
> 
> const ThemeSwitch: React.FC = () => {
>   const { refresh, setInitialState } = useModel('@@initialState');
> 
>   const handleSwitchChange = (checked: boolean) => {
>     const settings = { ...defaultSettings, navTheme: checked ? 'realDark' : 'light' };
>     setInitialState((s) => ({ ...s, settings }));
>     refresh();
>   };
> 
>   const isRealDark = defaultSettings.navTheme === 'realDark';
> 
>   return (
>     <Switch
>       checkedChildren="🌜"
>       unCheckedChildren="☀️"
>       defaultChecked={!isRealDark}
>       onClick={handleSwitchChange}
>     />
>   );
> };
> 
> export default ThemeSwitch;
> ```
> 
> 这里的默认配置是通过 defaultSettings.navTheme 来控制主题样式。你需要在 config/defaultSettings.ts 中进行配置。此外，我们使用了 umi 的 useModel 钩子来更新主题配置，刷新页面以加载新的主题。
> 
> 使用该 Switch 组件时，只需要在需要的页面引入即可。例如：
> 
> ```js
> import React from 'react';
> import ThemeSwitch from '@/components/ThemeSwitch';
> 
> const HomePage = () => {
>   return (
>     <div>
>       <h1>Welcome to My Homepage</h1>
>       <ThemeSwitch />
>     </div>
>   );
> };
> ```
> 
> 希望这个解决方案不仅对你的问题有帮助，也对 React 和 Antd 的使用有所启示。



> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 针对你的问题，我这里提供一种实现方法。你可以先创建一个 Switch 组件，然后通过监听点击事件来动态修改主题。具体实现可以参考以下代码：
> 
> ```js
> import { Switch } from 'antd';
> import React from 'react';
> import { useModel } from 'umi';
> import defaultSettings from '../../config/defaultSettings';
> 
> const ThemeSwitch: React.FC = () => {
>   const { refresh, setInitialState } = useModel('@@initialState');
> 
>   const handleSwitchChange = (checked: boolean) => {
>     const settings = { ...defaultSettings, navTheme: checked ? 'realDark' : 'light' };
>     setInitialState((s) => ({ ...s, settings }));
>     refresh();
>   };
> 
>   const isRealDark = defaultSettings.navTheme === 'realDark';
> 
>   return (
>     <Switch
>       checkedChildren="🌜"
>       unCheckedChildren="☀️"
>       defaultChecked={!isRealDark}
>       onClick={handleSwitchChange}
>     />
>   );
> };
> 
> export default ThemeSwitch;
> ```
> 
> 这里的默认配置是通过 defaultSettings.navTheme 来控制主题样式。你需要在 config/defaultSettings.ts 中进行配置。此外，我们使用了 umi 的 useModel 钩子来更新主题配置，刷新页面以加载新的主题。
> 
> 使用该 Switch 组件时，只需要在需要的页面引入即可。例如：
> 
> ```js
> import React from 'react';
> import ThemeSwitch from '@/components/ThemeSwitch';
> 
> const HomePage = () => {
>   return (
>     <div>
>       <h1>Welcome to My Homepage</h1>
>       <ThemeSwitch />
>     </div>
>   );
> };
> ```
> 
> 希望这个解决方案不仅对你的问题有帮助，也对 React 和 Antd 的使用有所启示。

这样做只会改变左侧侧边栏的主题，右侧内容区域始终是浅色，请问应该怎么做

**Comment by chenduxiuhaha** [comment]
这样做只会改变左侧侧边栏的主题，右侧内容区域始终是浅色，请问怎样让右侧内容区域主题也跟着变化

**Comment by chenduxiuhaha** [comment]
这样做只会改变左侧侧边栏的主题，右侧内容区域始终是浅色，请问怎样让右侧内容区域主题也跟着变化。 @chenshuai2144
