### ISSUE TITLE
请问如何用vs code 高效的调试

### ISSUE THREAD

**Issue by kitcoun** [ant-design/ant-design-pro#10586]
每次都会进入node_modules里面的文件，可以分享一下launch.json文件配置吗

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


当使用 VS Code 进行调试时，默认情况下会开启 Node.js 的所有源代码，包括 node_modules 目录下的代码。这会导致调试速度变慢、调试前的等待时间变长。

以下是如何避免调试进入 node_modules 文件的步骤：

1.打开 VS Code，并进入调试视图（在侧边栏中找到图标 )。

2.在调试视图中，点击“设置”按钮（齿轮图标）。

3.在“调试”选项卡下，找到“启动配置”部分，选择要编辑的配置文件（通常是“launch.json”）。

4.在“launch.json”文件中，找到您要配置的启动配置。如果您不确定要使用哪个配置，请只选择“启动程序”配置。

5.在所选配置中搜索“skipFiles”，然后将其值更改为以下内容：

```
"skipFiles": [
    "${workspaceFolder}/node_modules/**/*.js",
    "${workspaceFolder}/node_modules/**/**/*.js",
    "${workspaceFolder}/node_modules/**/**/**/*.js",
    "${workspaceFolder}/node_modules/**/**/**/**/*.js"
]
```

6.保存更改后的文件，然后重新启动调试会话即可。

请注意，这些变化适用于VS Code版本1.45.1。

希望这可以帮助提高您的调试效率！

**Comment by chenshuai2144** [comment]
这个还真没研究过，你有了解决办法可以在这里分享下。 我一般喜欢在 devtools 里面调试

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


要在VS Code中高效地调试项目，并避免进入node_modules文件夹中的文件，你可以通过配置launch.json文件来实现。在launch.json文件中，你可以定义不同的调试配置，以满足你的各种调试需求。

以下是一个示例的launch.json文件配置，可以帮助你实现高效调试，并跳过node_modules文件夹中的文件：

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**",
        "${workspaceFolder}/node_modules/**/*.js" // 跳过node_modules文件夹中的所有js文件
      ],
      "program": "${workspaceFolder}/index.js", // 你的入口文件路径
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ],
      "env": {
        "NODE_ENV": "development"
      }
    }
  ]
}
```

上述配置中，我们通过在"skipFiles"数组中添加`${workspaceFolder}/node_modules/**/*.js`来跳过node_modules文件夹中的所有js文件。这样，在调试时，VS Code将不会进入这些文件。

请确保将上述配置添加到你的项目的.vscode文件夹下的launch.json文件中。如果该文件不存在，你可以手动在.vscode文件夹下创建一个。

另外，你需要将"program"字段的值修改为你项目的入口文件路径，以便VS Code知道从哪里开始执行调试。

希望这个解决方案可以帮助到你！如果有任何问题，请随时提问。
