### ISSUE TITLE
🧐[问题 | question] 官方提供的默认风格，太单调了，我想问下官方有没有其他界面风格案列？或者推荐的案列？

### ISSUE THREAD

**Issue by pc110** [ant-design/ant-design-pro#10599]
### 🧐 问题描述 | Problem description
官方提供的默认风格，太单调了，我想问下官方有没有其他界面风格案列？或者推荐的案列？ 还是需要自己进行二次设计开发。如果我想调整界面风格，我该如何开始呢？ 没有资料提供？ 

### 💻 示例代码 | Sample code
目前是这样子，但感觉太简单，不好看。 
![1678369441833](https://user-images.githubusercontent.com/29336835/224043683-a9364e9d-8432-4cbc-95f8-f2ad5e3fa1b1.png)

如果想改成官网的预览版本风格，改如何调整？
![1678369831136](https://user-images.githubusercontent.com/29336835/224045492-85c49daf-e968-48d6-bd66-ce7068c3dff6.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

官方提供了 Ant Design Pro 来快速构建完整的前端界面，同时也提供了一些 UI 设计风格的案例供用户参考。你可以在 Ant Design 官网的 [案例页面](https://ant.design/docs/resource/cases-cn) 查看更多的界面设计案例。

如果你想自定义 Ant Design 的样式，可以通过自定义主题样式来实现。在 Ant Design 官方文档中提供了详细的[主题定制](https://ant.design/docs/react/customize-theme-cn)说明，你可以按照文档的指引，选择你需要的样式变量，自定义你的主题。

比如你可以添加以下代码到项目的 `src` 目录下的 `theme.less` 文件中，即可将 Ant Design 的主题改成预览版风格：

```less
// 引入 Ant Design 默认样式
@import '~antd/dist/antd.less';

// 自定义主题
@primary-color: #1890ff; // 全局主色
@link-color: #1890ff; // 链接色
@success-color: #52c41a; // 成功色
@warning-color: #faad14; // 警告色
@error-color: #f5222d; // 错误色
```

然后在应用程序的入口文件 `index.js` 中进行全局引入：

```javascript
import './theme.less';
```

这样就可以将 Ant Design 的主题样式改变为预览版风格。

希望以上信息能够解决你的问题，如有其他问题欢迎咨询。

**Comment by caice7** [comment]
我也被这问题困惑，为啥新版这么难看……

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Ant Design 4.x 版本相较于 3.x 版本的样式有了比较大的变化，部分用户可能会认为新版的样式不如旧版的美观。但是 Ant Design 4.x 引入了很多新的特性和优化，也提供了更多的组件和接口，从而提高了开发效率和代码质量。

当然，Ant Design 也在不断的更新和完善中，为用户提供更好的界面设计和使用体验。如果你有任何建议和意见，欢迎在 Ant Design 的 GitHub 仓库中提出 [issue](https://github.com/ant-design/ant-design/issues) 或者在 Ant Design 论坛中发帖反馈。

同时，Ant Design 仓库中也有来自社区贡献的样式主题，你可以在仓库的主题目录下查看并下载使用。如果你想自定义主题样式，也可以参考官方文档的主题定制章节。

最后，美观的 UI 设计也需要结合业务场景而定，建议在项目开发过程中，根据需求和设计原则选择合适的样式和组件。

**Comment by chenshuai2144** [comment]
https://ant.design/docs/react/customize-theme-cn

看看这个文档有很多可以通过 token 来设置

**Comment by caice7** [comment]
> 我也被这问题困惑，为啥新版这么难看……

找到方法了，不如看这里：https://procomponents.ant.design/components/layout#layout-%E7%9A%84-token
配置位置在app.tsx的layout方法下，新增token参数：
`
    token: {
      sider: {
        colorBgMenuItemSelected: '#e6f4ff',
        colorTextMenuSelected: '#1677ff',
        colorTextMenuItemHover: '#1677ff',
        colorTextMenuActive: '#1677ff',
      },
      header: {
        colorBgHeader: '#292f33',
        colorHeaderTitle: '#fff',
        colorTextMenu: '#dfdfdf',
        colorTextMenuActive: '#1677ff',
        colorBgMenuItemSelected: '#22272b',
      },
    }
`

**Comment by hyl1374961656** [comment]
能否提供一个官网预览的demo这样我们也好区分在哪里设置
