### ISSUE TITLE
🐛 [BUG] 官网例子BUG, 选中二级菜单。点击展开侧边栏按钮，标题出现在右上角

### ISSUE THREAD

**Issue by pc110** [ant-design/ant-design-pro#10592]
1. 选中二级菜单 
![image](https://user-images.githubusercontent.com/29336835/223079972-0bd9c670-9051-4a46-8bc3-8fa05e110d13.png)
2. 收起侧边栏
![image](https://user-images.githubusercontent.com/29336835/223080138-21bfc3ef-86d3-427b-87e8-2df25c174f12.png)
3. 再次展开侧边拦，菜单标题出现在右上角，随后消失

![image](https://user-images.githubusercontent.com/29336835/223079825-b4486c59-0bc4-4063-a771-3450bd2ac2fb.png)

 注： 选中一级菜单没有问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢反馈！

这是 Ant Design 官网的一个已知 bug，在选择侧边栏二级菜单时会出现这种情况。

解决方案：
可以在 `MenuItem` 上添加 `onClick={() => {history.push('/xxx')}` 属性，手动跳转路由而不是使用 `Link` 组件，即可规避此问题。

```
<Menu.Item onClick={() => {history.push('/xxx')}}>菜单项</Menu.Item>
```

详情可以参考 Ant Design 官方 issue 页面：https://github.com/ant-design/ant-design/issues/22984

**Comment by pc110** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 感谢反馈！
> 
> 这是 Ant Design 官网的一个已知 bug，在选择侧边栏二级菜单时会出现这种情况。
> 
> 解决方案： 可以在 `MenuItem` 上添加 `onClick={() => {history.push('/xxx')}` 属性，手动跳转路由而不是使用 `Link` 组件，即可规避此问题。
> 
> ```
> <Menu.Item onClick={() => {history.push('/xxx')}}>菜单项</Menu.Item>
> ```
> 
> 详情可以参考 Ant Design 官方 issue 页面：[ant-design/ant-design#22984](https://github.com/ant-design/ant-design/pull/22984)

**Comment by pc110** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 感谢反馈！
> 
> 这是 Ant Design 官网的一个已知 bug，在选择侧边栏二级菜单时会出现这种情况。
> 
> 解决方案： 可以在 `MenuItem` 上添加 `onClick={() => {history.push('/xxx')}` 属性，手动跳转路由而不是使用 `Link` 组件，即可规避此问题。
> 
> ```
> <Menu.Item onClick={() => {history.push('/xxx')}}>菜单项</Menu.Item>
> ```
> 
> 详情可以参考 Ant Design 官方 issue 页面：[ant-design/ant-design#22984](https://github.com/ant-design/ant-design/pull/22984)

<Menu.Item onClick={() => {history.push('/xxx')}}>菜单项</Menu.Item>
不好意思，我没明白这段代码需要加在哪里？ 是在app.tsx文件中吗? 菜单是通过routes自动创建的。 还请具体说明。

**Comment by chenshuai2144** [comment]
这个解决方案是骗人的，是个bug，我来修复一下

**Comment by chenshuai2144** [comment]
是 antd 的bug，等待antd 新版本来修复一下，在2023年 3 月14 号就可以修复
