### ISSUE TITLE
🐛 [BUG]官网安装v5.2.0版本的antdesign pro，npm install时一直报错 husky install  .git can't be found (see https://git.io/Jc3F9)

### ISSUE THREAD

**Issue by luckyTiamo** [ant-design/ant-design-pro#10594]
### 🐛 bug 描述

按照官网安装v5.2.0版本的antdesign pro，npm install时一直报错如下，按照网上的教程修改prepare也不行 
husky install

.git can't be found (see https://git.io/Jc3F9)

<img width="693" alt="image" src="https://user-images.githubusercontent.com/48179927/223307111-0a1950e1-03c0-452b-8960-531f26a2f27d.png">

### 📷 复现步骤 | Recurrence steps

npm i @ant-design/pro-cli -g
pro create myapp
选择 umi@3 simple

cd myapp && npm install

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本: 3
- 开发环境 [mac OS]
- node v14.20.1
- npm v6.14.17

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案

这个问题出现的原因在于没有安装 git 或者 git 地址未配置。husky 会在使用 git commit 提交代码时预先检查提交信息的合法性，所以它需要依赖 git 工具才能运行。

如果你已经通过 brew 安装了 git，但 husky 仍然无法找到 git，那么可以尝试在终端中输入以下命令：

```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```

这个命令会将 Xcode 工具链指向你的开发者文件夹中的 Xcode.app。这个命令应该能够让 husky 找到 git。

如果这个命令仍然不起作用，那么可以尝试手动配置 git 地址。找到项目中的 `.husky/pre-commit` 文件并打开它。在文件中找到以下代码：

```
if [ -f package.json ]; then
  . "$(dirname "$0")/husky.sh"

  npm run lint -- --fix
fi
```

在 `husky.sh` 前面添加 `export PATH="$PATH:/usr/local/git/bin/"`。这个命令告诉 husky 去 `/usr/local/git/bin/` 找 git。

修改后的代码如下：

```
if [ -f package.json ]; then
  export PATH="$PATH:/usr/local/git/bin/"
  . "$(dirname "$0")/husky.sh"

  npm run lint -- --fix
fi
```

尝试运行 `npm install`，这个问题应该就会解决了。

如果问题还是存在，那么可以尝试卸载并重新安装 husky。在项目根目录下运行以下命令：

```
npm uninstall husky --save-dev
npm install husky --save-dev
```

如果这些方法都不起作用，那么可以考虑重新安装 git 或者查找其他方法来解决这个问题。

### 🔗 参考链接
- [Git can't be found when installing husky on macOS #903](https://github.com/typicode/husky/issues/903)
- [Git clone failing on macOS Sierra (SSL certificate problem)](https://stackoverflow.com/questions/3987683/homebrew-install-behind-a-proxy-how-to-set-proxy-username-and-password/40851015#40851015)
