### ISSUE TITLE
🐛 [BUG]菜单颜色不会随主题色改变

### ISSUE THREAD

**Issue by baihech** [ant-design/ant-design-pro#10596]
### 🐛 bug 描述
菜单默认是灰色，使用SettingDrawer修改主题色，或者defaultSettings.ts设置colorPrimary都不会改变颜色

麻烦看清楚问题的描述，不是重写ProLayout，是用layout生成的菜单有bug。
`export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {}`
下面是菜单的实际样式，这个样式不会随theme改变值。
```
:where(.css-dev-only-do-not-override-1p8ii27).ant-pro-layout .ant-pro-base-menu .ant-menu-submenu-selected {
    color: rgba(0, 0, 0, 0.95);
}
```
![企业微信截图_16782401984242](https://user-images.githubusercontent.com/9922792/223599061-ac4310a5-dae6-4781-a19d-f63e92f3f153.png)

### 📷 复现步骤 | Recurrence steps
https://procomponents.ant.design/components/layout
https://preview.pro.ant.design/dashboard/analysis
[preview](https://preview.pro.ant.design/dashboard/analysis)的菜单颜色会改变，[高级布局](https://procomponents.ant.design/components/layout)的菜单颜色不会改变

### 🏞 期望结果 | Expected results
菜单颜色随主题色改变

### 💻 复现代码 | Recurrence code
`export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {}`

### © 版本信息

- Ant Design Pro 版本: :6.0.0
- umi 版本 @umijs/max": "^4.0.52"
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by baihech** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🐛 [BUG]菜单颜色不会随主题色改变 #10595](https://github.com/ant-design/ant-design-pro/issues/10595)][100%]

没有任何帮助，这个问题被ai直接close了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉对此造成了困扰。如果以上给出的链接没有解决问题，可能需要更多的信息才能找到相应的解决方案。以下是一些可能有助于解决问题的进一步建议：

1. 确认是否正确地集成了antd的主题配置，例如在webpack或less等构建工具中。可以查看[这里](https://ant.design/docs/react/use-with-create-react-app-cn#%E5%85%B6%E4%BB%96-react-%E8%84%9A%E6%9C%AC)找到与您的开发环境相适应的适当配置。
2. 确认是否正确导入了ProLayout和Menu组件，以及是否正确传递了主题信息到组件中。
3. 检查应用的样式表中是否存在可能与菜单颜色相关的规则，这些规则可以覆盖antd或ProLayout的默认样式表，从而导致问题。

如果这些建议仍无法解决问题，建议发帖详细描述问题，包括 setup.js, app.tsx，defaultSettings.ts 等相关文件的内容，并且提供完整的复现代码和截图，这样其他人才能更好地理解问题并提供帮助。

**Comment by chenshuai2144** [comment]
因为这个token没有被设置，是故意这么做的。可以看这两个文档来手动配置

https://ant.design/docs/react/customize-theme-cn
https://procomponents.ant.design/components/layout#token

**Comment by chenshuai2144** [comment]
我来看看

**Comment by gtt011029** [comment]
同， 所以有方案了吗
