### ISSUE TITLE
6.0正式版发布有计划吗？🧐[问题 | question]

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#10593]
6.0正式版发布有计划吗？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。




你好！感谢你在 GitHub 提出这个问题。关于 React 的 6.0 正式版发布计划，目前 React 官方团队并没有公开的具体时间表，但是他们会在发布前发布测试版供开发者体验测试。你可以通过关注 React 官方博客、GitHub 仓库以及社交媒体渠道来获取最新的信息。

另外，React 的更新历史和计划都会在官方文档中记录，你可以查看它们以便获得更多信息：

- React 更新记录：https://reactjs.org/versions/
- React 计划和路线图：https://reactjs.org/blog/2018/11/27/react-16-roadmap.html

希望这些信息可以帮助到你！如果你还有其他问题或需要更多的帮助，请随时在 GitHub 上提出。

**Comment by WuJiY** [comment]
🧐

**Comment by echoyl** [comment]
这真的是AI reply吗？ 太不ai了吧？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


是的，这是 ChatGPT 在尝试自动生成答复。ChatGPT 是一个基于人工神经网络训练的自然语言处理模型，可以根据输入的问题和语境自动生成答复。然而，由于其训练数据的局限性，以及它的生成算法等方面的不足，它可能会有一定的错误或不太符合实际情况。我们会尽力优化和改进它的表现，但完全消除其不足可能还需要更多的研究和努力。如果你有任何建议或反馈，欢迎随时告诉我们。

**Comment by WuJiY** [comment]
to：ChatGpt
我在问ant-design-pro的6.0正式版，不是react

**Comment by hfpp2012copy** [comment]
https://www.qiuzhi99.com/playlists/antdprov6menu.html

**Comment by chenshuai2144** [comment]
hhh 不要和机器人吵架啦，他回答不了未来的事情。

我现在还在做 less to cssinjs 的方案，预计是三月底

**Comment by yangliuyu** [comment]
@chenshuai2144 有进展吗？预计啥时候发布6.0正式版？

**Comment by yangliuyu** [comment]
@chenshuai2144 有什么进展吗？

**Comment by chenshuai2144** [comment]
还在等 antd/chart的新版本

**Comment by RainingNight** [comment]
Any news?

**Comment by coder-belong** [comment]
预计今年出官网文档吗
