### ISSUE TITLE
🐛 [BUG] PageContainer 面包屑 中使用了a标签嵌套a标签

### ISSUE THREAD

**Issue by tmzhenzheng** [ant-design/ant-design-pro#10603]
### 🐛 bug 描述
当菜单为二级菜单的时候
PageContainer 面包屑 中使用了a标签嵌套a标签

### © 版本信息

- Ant Design Pro 版本: [6.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="453" alt="image" src="https://user-images.githubusercontent.com/17843576/224293479-3b42dc90-e599-436d-a13c-7b138139cd1b.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案

这个问题可能是由于菜单的渲染方式导致的。你可以在 renderBreadcrumbItem 方法中使用 Link 组件来代替 a 标签解决这个问题。

```jsx
import React from 'react';
import { Link } from 'umi';

const renderBreadcrumbItem = (routes, params, routesLength) => {
  const itemRender = routes[params.index].breadcrumbName;
  if (params.index === routesLength - 1) {
    return (
      <span key={itemRender}>
        {itemRender}
      </span>
    );
  }
  return (
    <Link key={itemRender} to={routes.slice(0, params.index + 1).map(item => item.path).join('')}>
      {itemRender}
    </Link>
  );
};

export default function PageContainer({ children, ...rest }) {
  return (
    <div {...rest}>
      <Breadcrumb>
        <Breadcrumb.Item>
          <Link to="/">首页</Link>
        </Breadcrumb.Item>
        {routes &&
          routes.length > 0 &&
          routes.map((route, index) => (
            <Breadcrumb.Item key={route.path}>
              {index === routes.length - 1 ? (
                <span>
                  {route.breadcrumbName}
                </span>
              ) : (
                renderBreadcrumbItem(routes, { index }, routes.length)
              )}
            </Breadcrumb.Item>
          ))}
      </Breadcrumb>
      {children}
    </div>
  );
}
```

此外，我们建议您将这个 issue 提交给 Ant Design Pro 项目的 GitHub issue 中。

**Comment by chenshuai2144** [comment]
或者升级新版本会默认将 a 修改为 span 来绕过问题

**Comment by cyc2016** [comment]
截至到commit fd4a4a0183ead9863bcf3c700ae7eb7218660ff2
这个问题还存在，这会导致自定义面包屑导航有时会出现问题，例如我想禁用面包屑中某几个链接不能点击，现在无法做到：
```
itemRender={(route, params, routes, paths) => { return <Button disabled>{route.breadcrumbName}</Button> }}
```
@chenshuai2144
