### ISSUE TITLE
该页面代码已经看过了，想知道它从哪个文件读取的数据，map里的吗？

### ISSUE THREAD

**Issue by cyp66** [ant-design/ant-design-pro#1060]
https://preview.pro.ant.design/#/dashboard/analysis
该页面下的”门店销售额排名“里的数据是从哪个文件里读取出来的，

**Comment by cyp66** [comment]
我要修改数据

**Comment by valleykid** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/mock/chart.js

**Comment by cyp66** [comment]
工专路0号店
工专路1号店
工专路2号店
以上数据我要修改，请问从哪里更改？

**Comment by valleykid** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/routes/Dashboard/Analysis.js#L39-L42

**Comment by cyp66** [comment]
<div className={styles.salesRank}>
                      <h4 className={styles.rankingTitle}>门店销售额排名</h4>
                      <ul className={styles.rankingList}>
                        {rankingListData.map((item, i) => (
                          <li key={item.title}>
                            <span className={i < 3 ? styles.active : ''}>{i + 1}</span>
                            <span>{item.title}</span>
                            <span>{numeral(item.total).format('0,0')}</span>
                          </li>
                        ))}
                      </ul>
</div>

怎么改？

**Comment by cyp66** [comment]
找到了，多谢！
