### ISSUE TITLE
🧐[问题 | question] 请教Pro组件与antd组件的使用问题

### ISSUE THREAD

**Issue by cj2a7t** [ant-design/ant-design-pro#10600]
### 🧐 问题描述 | Problem description

**比如我使用了 ProFormTextArea组件，但是它没有antd TextArea showCount咋办？**
Pro组件
`<ProFormTextArea
  name="text"
  label="名称"
  placeholder="请输入名称"
  fieldProps={inputTextAreaProps}
/>
`
antd组件
`<TextArea showCount maxLength={100} onChange={onChange} />
`

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by cj2a7t** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🙋 解决方案 | Solution

Pro组件是基于antd进行的二次封装，可以使用antd的组件属性。对于showCount和maxLength等antd本身的属性，可以通过在fieldProps中传递该属性完成相关功能。

示例：

```
<ProFormTextArea
  name="text"
  label="名称"
  placeholder="请输入名称"
  fieldProps={{
    showCount: true,
    maxLength: 100,
    ...inputTextAreaProps,
  }}
/>
```

通过在fieldProps中传递showCount: true, maxLength: 100等属性即可实现显示字数提示和设置最大输入字数。

参考文档：

- [ProFormTextArea组件文档](https://procomponents.ant.design/components/form?locale=en-US#ProFormTextArea)
- [antd TextArea组件文档](https://ant.design/components/input/#TextArea)

希望对您有帮助！

**Comment by cj2a7t** [comment]
thanks
