### ISSUE TITLE
antd的版本降级

### ISSUE THREAD

**Issue by 13554599576** [ant-design/ant-design-pro#10607]
新版的antd pro默认是使用的5.2.2版本的antd。
当我降级为4.24.8版本的antd时，启动项目出现如下错误。
<img width="914" alt="image" src="https://user-images.githubusercontent.com/34908374/224609136-e630688f-4edc-4eb5-8279-1e2681598ab5.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可能是由于antd升级到4以上版本后，使用的Icon组件变更为@ant-design/icons而不是以前的@ant-design/icons-react。

您可以按照以下步骤进行处理：

1. 在package.json中将antd的版本降级为4.24.8：

```bash
npm install antd@4.24.8 --save
```

2. 将代码库中所有引用的@ant-design/icons-react替换为@ant-design/icons：

```
// Before:
import { Icon } from '@ant-design/icons-react'

// After:
import { Icon } from '@ant-design/icons'
```

3. 然后重新启动应用程序即可。

如果上述步骤不起作用，请确保您的代码库中没有其他依赖项使用了@ant-design/icons-react。如果存在这样的依赖项，您需要查看文档并调整代码以适应更新。同时，您可以参考antd更新日志对您的应用程序进行任何其他所需的更改。
