### ISSUE TITLE
defaultSettings中设置了样式，退出登陆后再进来样式就变了，刷新下页面就好，什么原因?

### ISSUE THREAD

**Issue by 13166079936** [ant-design/ant-design-pro#10614]
defaultSettings.ts
`import { Settings as LayoutSettings } from '@ant-design/pro-components'

const Settings: LayoutSettings & {
    pwa?: boolean;
    logo?: string;
} = {
    navTheme: 'light',
    primaryColor: '#1890ff',
    layout: 'mix',
    contentWidth: 'Fluid',
    headerHeight: 48,
    fixedHeader: false,
    fixSiderbar: false,
    colorWeak: false,
    title: '互联网医院管理端',
    pwa: false,
    logo: '/logo.svg',
    iconfontUrl: '',
    splitMenus: true,
}

export default Settings`

zhe这是退出登录再进来时打印的defaultSettings，这个配置是哪里来的呢？
![image](https://user-images.githubusercontent.com/42597185/224953640-7b20778d-ead5-472a-8143-953ff3e2024e.png)

刷新下页面 j就跟defaultSettings.ts里设置的一样了
![image](https://user-images.githubusercontent.com/42597185/224953852-8c1871b0-c203-4e5a-8820-f819eeb69130.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这可能是因为您的应用程序在退出登录后清除了默认设置，然后在重新登录时重新设置了值。 在默认设置填充时，您可以考虑从本地localStorage存储中获取上一次的设置，并将其与默认设置组合在一起，而不是通过清除原始默认值来再次设置。 以下是示例代码：

```typescript
import { Settings as LayoutSettings } from '@ant-design/pro-layout';

const defaultSettings: LayoutSettings = {
    // 默认设置
}

const previousSettings = JSON.parse(localStorage.getItem('userSettings') || '{}');

const settings: LayoutSettings = { ...defaultSettings, ...previousSettings };

// 设置上一次的设置，而不是覆盖默认设置
export default settings;
```

这样处理后，即使退出登录和重新登录，用户的设置也会在默认设置之上显示，直到他们主动更改或重置。 同时，建议您在应用程序文档中进行说明，以便用户明白如何更改它们的设置，并防止对默认设置进行更改。

**Comment by chenshuai2144** [comment]
是不是在url里面设置的？这种一般都是数据流的问题

**Comment by 13166079936** [comment]
好的谢谢！

**Comment by JJQuiet** [comment]
我也遇到了和题主类似的问题。

- 我是每次登录进来都是暗色菜单风格+侧边菜单布局，得再刷新一下才变成自己在defaultSetting.ts里设置得一样
-  这种写法没有用吧  const settings: LayoutSettings = { ...defaultSettings, ...previousSettings };因为这和直接写好配置到defaultSettings里面一样吧

请问该怎么解决

**Comment by JuvenileQ** [comment]
每次打开，或者刷新，左侧菜单都会成黑色主题

![image](https://github.com/ant-design/ant-design-pro/assets/39209399/70c4db75-a3f6-49b0-88bc-3f13e3516ff3)
