### ISSUE TITLE
🧐[问题 | question] 传到ProTable页面的参数，赋值到request中的params，怎么动态的在request里面请求分页接口

### ISSUE THREAD

**Issue by Mikey1502** [ant-design/ant-design-pro#10612]
### 🧐 问题描述 | Problem description

传到ProTable页面的参数，赋值到request中的params，怎么动态的在request里面请求分页接口
### 💻 示例代码 | Sample code
import { getByPage } from '@/api/user';
import { Status } from '@/constants/common';
import { Locked, Sex, Type } from '@/constants/user';
import { DateCompareNow } from '@/utils/user';
import type { ActionType, ProColumns } from '@ant-design/pro-components';
import { ProTable } from '@ant-design/pro-components';
import { Space, Tag } from 'antd';
import React, {useRef} from 'react';
// import {CountContext} from '../index'

const OrgPage: React.FC<Org.OrgTable> = (props) => {
  console.log('上面', props)
  const actionRef = useRef<ActionType>();
  // const a = useContext(CountContext);
  // console.log('上面a', a)
  const columns: ProColumns<User.User>[] = [
    {
      title: 'ID',
      dataIndex: 'id',
      hideInSearch: true,
      hideInTable: true,
      width: 48,
    },
    {
      title: '用户头像',
      dataIndex: 'avatar',
      ellipsis: true,
      hideInSearch: true,
      // render: (_, record) => {
      //   const uri = `/api/download?file=${record.avatar}`
      //   console.log(uri)
      //   return (
      //     <Space>
      //       <Avatar src={<img src={uri} alt="头像" />} />
      //     </Space>)
      // },
    },
    // {
    //   title: '所属组织',
    //   dataIndex: "org.name",
    //   ellipsis: true,
    //   hideInSearch: true,
    //
    // },
    {
      title: '用户名',
      dataIndex: 'username',
      copyable: true,
      ellipsis: true,
    },
    {
      title: '用户姓名',
      dataIndex: 'name',
      ellipsis: true,
    },

    {
      disable: true,
      title: '用户性别',
      dataIndex: 'sex',
      // filters: true,
      onFilter: true,
      ellipsis: true,
      // hideInSearch: true,
      valueType: 'select',
      valueEnum: Sex,
      width: 100,
      render: (_, record) => (
        <Space>
          {record.sex === 1 && (
            <Tag color="volcano" key={record.sex}>
              男
            </Tag>
          )}
          {record.sex === 2 && (
            <Tag color="orange" key={record.sex}>
              女
            </Tag>
          )}
        </Space>
      ),
    },
    {
      disable: true,
      title: '用户类型',
      dataIndex: 'type',
      // filters: true,
      onFilter: true,
      ellipsis: true,
      // hideInSearch: true,
      valueType: 'select',
      valueEnum: Type,
      width: 100,
      render: (_, record) => (
        <Space>
          {record.type === 1 && (
            <Tag color="blue" key={record.type}>
              站点管理员
            </Tag>
          )}
          {record.type === 2 && (
            <Tag color="green" key={record.type}>
              普通用户
            </Tag>
          )}
        </Space>
      ),
    },
    {
      disable: true,
      title: '是否锁定',
      dataIndex: 'isLocked',
      // filters: true,
      onFilter: true,
      ellipsis: true,
      // hideInSearch: true,
      valueType: 'select',
      valueEnum: Locked,
      render: (_, record) => (
        <Space>
          {record.isLocked === 1 && (
            <Tag color="green" key={record.isLocked}>
              正常
            </Tag>
          )}
          {record.isLocked === 2 && (
            <Tag color="red" key={record.isLocked}>
              锁定
            </Tag>
          )}
        </Space>
      ),
    },

    {
      title: '是否过期',
      dataIndex: 'expired',
      ellipsis: true,
      hideInSearch: true,
      render: (_, record) => <Space>{DateCompareNow(record.expired)}</Space>,
    },
    {
      disable: true,
      title: '用户状态',
      dataIndex: 'status',
      // filters: true,
      onFilter: true,
      ellipsis: true,
      // hideInSearch: true,
      valueType: 'select',
      valueEnum: Status,
      render: (_, record) => (
        <Space>
          {record.status === 0 && (
            <Tag color="green" key={record.status}>
              启用
            </Tag>
          )}
          {record.status === 1 && (
            <Tag color="red" key={record.status}>
              禁用
            </Tag>
          )}
        </Space>
      ),
    },
    {
      title: '创建时间',
      key: 'createAt',
      dataIndex: 'createAt',
      valueType: 'date',
      sorter: true,
      width: 110,
      hideInSearch: true,
    },
    {
      title: '修改时间',
      dataIndex: 'modifyAt',
      valueType: 'date',
      sorter: true,
      hideInSearch: true,
      width: 110,

      // search: {
      //   transform: (value) => {
      //     return {
      //       startTime: value[0],
      //       endTime: value[1],
      //     };
      //   },
      // },
    },
  ];
  return (
    <>
      <ProTable<User.User>
        columns={columns}
        actionRef={actionRef}
        cardBordered
        // @ts-ignore
        request={async (params = {}, sort, filter) => {
          console.log('props', props);
          const data = { ...params, orgId: props.orgId };
          const r = await getByPage(data, { ...sort, ...filter });
          return {
            ...r.data,
          };
        }}

        // columnsState={{
        //   persistenceKey: 'pro-table-singe-demos',
        //   persistenceType: 'localStorage',
        //   onChange(value) {
        //     console.log('valuex: ', value);
        //   },
        // }}
        rowKey="id"
        search={{
          labelWidth: 'auto',
        }}
        options={{
          setting: {
            listsHeight: 400,
          },
        }}
        pagination={{
          pageSize: 10,
          // onChange: (page) => console.log(page),
        }}
        dateFormatter="string"
      />
    </>
  );
};

export default OrgPage;

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by Mikey1502** [comment]
随着传入的props参数的改变，动态请求分页接口

**Comment by echoyl** [comment]
protable 里面有一个params 参数 可以把props的参数写到这里面 request就会重新请求了

**Comment by Mikey1502** [comment]
谢谢，已解决
