### ISSUE TITLE
🧐[问题 | question] Where is the source code for preview.pro.ant.design?

### ISSUE THREAD

**Issue by zxti** [ant-design/ant-design-pro#10619]
I can't seem to find the code for this demo site. I'd love to see how it was put together. When I just checkout this repo or start a new pro app, it doesn't have everything in that demo site. Thank you!

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👨‍💻 [回答 | answer] 

The source code for preview.pro.ant.design is available on GitHub at https://github.com/ant-design/ant-design-pro-site. This is a separate repo from the ant-design-pro repo that you might have checked out previously, which contains the core Ant Design Pro code.

To view the source code of preview.pro.ant.design, you can clone the repo and run it locally. Here are the steps:

1. Clone the repository:

```
git clone https://github.com/ant-design/ant-design-pro-site.git
```

2. Change into the directory:

```
cd ant-design-pro-site
```

3. Install dependencies:

```
npm install
```

4. Start the development server:

```
npm start
```

This should open the site in your browser at http://localhost:8000.

The code for the demo pages can be found in the `src/pages` directory. It's worth noting that the demo site uses Gatsby, so the pages are generated dynamically and may not match up exactly with the files in `src/pages`. 

In case you want to know more about Gatsby or Ant Design Pro, here are the documents which may help you:

- [Gatsby Documentation](https://www.gatsbyjs.com/docs/)
- [Ant Design Pro Documentation](https://pro.ant.design/docs/getting-started) 

I hope this helps! Let me know if you have any further questions.

**Comment by chenshuai2144** [comment]
At this branch https://github.com/ant-design/ant-design-pro/tree/all-blocks
