### ISSUE TITLE
🧐[问题 | question] How to make just the header or sider dark?

### ISSUE THREAD

**Issue by zxti** [ant-design/ant-design-pro#10618]
### 🧐 问题描述 | Problem description

Here's the demo at https://preview.pro.ant.design/dashboard/analysis

![image](https://user-images.githubusercontent.com/59713267/225437038-0c080da3-e3c6-4964-b829-9293aa957038.png)

The header bar is dark.
~
Here's the demo at https://ant.design/components/layout#components-layout-demo-side

![image](https://user-images.githubusercontent.com/59713267/225437129-a0f8a3a6-1460-4a01-92bf-f75a367609c6.png)

How do I configure the props to ProLayout to achieve this?

If I pass in navTheme of realDark, then the whole page becomes dark, not just the header or sider.

Thanks!

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

To make just the header or sider dark, you can use the `theme` prop of `ProLayout` component.

For example, to make the header bar dark, you can set `theme="dark"` like this:

```jsx
import ProLayout from '@ant-design/pro-layout';

<ProLayout
  theme="dark"
  // ...
>
  {/* your content */}
</ProLayout>
```

And to make the sider dark, you can set `theme="darkMenu"` like this:

```jsx
import ProLayout from '@ant-design/pro-layout';

<ProLayout
  theme="darkMenu"
  // ...
>
  {/* your content */}
</ProLayout>
```

By default, the `theme` prop is set to `light`, which makes the header and sider light in color.

You can find more information about the `theme` prop and other available values in the official documentation [here](https://prolayout.ant.design/docs/props-cn/#theme).

**Comment by chenshuai2144** [comment]
you can use token
```tsx
import { PageContainer, ProCard, ProLayout } from '@ant-design/pro-components';
import { useState } from 'react';

    <ProLayout
      splitMenus
      token={{
        colorBgAppListIconHover: 'rgba(0,0,0,0.06)',
        colorTextAppListIconHover: 'rgba(255,255,255,0.95)',
        colorTextAppListIcon: 'rgba(255,255,255,0.85)',
        sider: {
          colorBgCollapsedButton: '#fff',
          colorTextCollapsedButtonHover: 'rgba(0,0,0,0.65)',
          colorTextCollapsedButton: 'rgba(0,0,0,0.45)',
          colorMenuBackground: '#004FD9',
          colorBgMenuItemCollapsedHover: 'rgba(0,0,0,0.06)',
          colorBgMenuItemCollapsedSelected: 'rgba(0,0,0,0.15)',
          colorBgMenuItemCollapsedElevated: 'rgba(0,0,0,0.85)',
          colorMenuItemDivider: 'rgba(255,255,255,0.15)',
          colorBgMenuItemHover: 'rgba(0,0,0,0.06)',
          colorBgMenuItemSelected: 'rgba(0,0,0,0.15)',
          colorTextMenuSelected: '#fff',
          colorTextMenuItemHover: 'rgba(255,255,255,0.75)',
          colorTextMenu: 'rgba(255,255,255,0.75)',
          colorTextMenuSecondary: 'rgba(255,255,255,0.65)',
          colorTextMenuTitle: 'rgba(255,255,255,0.95)',
          colorTextMenuActive: 'rgba(255,255,255,0.95)',
          colorTextSubMenuSelected: '#fff',
        },
      }}
      location={{
        pathname,
      }}
    >
      <PageContainer
        extra={[
          <Button key="3">操作</Button>,
          <Button key="2">操作</Button>,
          <Button key="1" type="primary">
            主操作
          </Button>,
        ]}
        footer={[
          <Button key="3">重置</Button>,
          <Button key="2" type="primary">
            提交
          </Button>,
        ]}
      >
        <ProCard
          style={{
            height: '200vh',
            minHeight: 800,
          }}
        >
          <div />
        </ProCard>
      </PageContainer>
    </ProLayout>
  );
};
```

**Comment by zxti** [comment]
Thank you.

I see that pro-components has its own theming variables, and I also besides pro-components use some ant components directly.

For example, if I just use the code you showed, plus `<Menu theme="dark">` from Ant, I get:

![image](https://user-images.githubusercontent.com/44424944/228456745-de698865-6863-43cb-b96b-9ee1e7fb4662.png)

How should I ensure both of these match?

**Comment by zxti** [comment]
Thank you @chenshuai2144 .

I see that pro-components has its own theming variables, and I also besides pro-components use some ant components directly.

For example, if I just use the code you showed, plus `<Menu theme="dark">` from Ant, I get:

![image](https://user-images.githubusercontent.com/44424944/228456745-de698865-6863-43cb-b96b-9ee1e7fb4662.png)

How should I ensure both of these match?
