### ISSUE TITLE
🧐[问题 | 动态路由404]

### ISSUE THREAD

**Issue by ericzhao007** [ant-design/ant-design-pro#10610]
### 🧐 问题描述 | Problem description

[按照官方文档](https://pro.ant.design/zh-CN/docs/advanced-menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95)
创建的动态菜单可以在菜单栏里正常显示，但是跳转404
### 💻 示例代码 | Sample code
![image](https://user-images.githubusercontent.com/21306882/224660295-cf389fca-594c-4001-998c-17e211da6a6a.png)
组件地址就是默认的那个表格组件
### 🚑 其他信息 | Other information
在request中打印的最终结果
![image](https://user-images.githubusercontent.com/21306882/224660573-ddb204a7-3177-4e7e-86bc-ce1d554c8b52.png)

OS: Ubuntu

Node：v18.14.2

浏览器 | browser：Edge 110.0.1587.63

**Comment by echoyl** [comment]
没有动态路由，只有动态菜单，你的路由还是要先写进去才可以
可以默认写一个路由，然后在页面里面根据这个菜单的数据来显示数据，达到一定程度上的动态路由效果

**Comment by lcc908** [comment]
> 没有动态路由，只有动态菜单，你的路由还是要先写进去才可以 可以默认写一个路由，然后在页面里面根据这个菜单的数据来显示数据，达到一定程度上的动态路由效果

路由都在本地都写上去了，当我使用menu从后端获取动态菜单数据，但后台没有返回的路由却可以通过修改url来访问。。这个如何规避呢

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


如果动态菜单在前端没有对应的路由，那么访问这个菜单是无法正常显示内容的，这是正常的。如果你希望避免用户通过手动修改 URL 访问到没有开发的页面，可以在路由层面进行拦截。例如，可以在路由守卫中判断访问的路由是否存在于动态菜单中，如果不存在，则跳转到 404 页面。

以下是一个简单的路由守卫示例：

```javascript
// 在路由配置文件中进行路由守卫的配置
import router from './router'
import getMenuData from './getMenuData'

// 白名单，不需要拦截的路由
const whiteList = ['/login']

router.beforeEach(async (to, from, next) => {
  // 获取动态菜单数据
  const menuData = await getMenuData()
  // 根据菜单数据生成路由的权限表
  const permissionList = generatePermissionList(menuData)
  // 检查访问的路由是否在权限表中存在
  if (permissionList.includes(to.path)) {
    next() // 跳转到目标路由
  } else {
    // 如果对应菜单不存在，则跳转到 404 页面
    next('/404')
  }
})

// 利用动态菜单数据生成路由的权限表
function generatePermissionList(menuData) {
  const permissionList = []
  menuData.forEach(menu => {
    if (menu.path) {
      permissionList.push(menu.path)
      if (menu.children) {
        permissionList.push(...generatePermissionList(menu.children))
      }
    }
  })
  return permissionList
}
```

此外，在前端进行页面现实之前也可以在后端进行权限控制的判断和拦截，防止未授权的请求直接返回未经授权的内容。

**Comment by KYX1234** [comment]
> > 没有动态路由，只有动态菜单，你的路由还是要先写进去才可以 可以默认写一个路由，然后在页面里面根据这个菜单的数据来显示数据，达到一定程度上的动态路由效果
> 
> 路由都在本地都写上去了，当我使用menu从后端获取动态菜单数据，但后台没有返回的路由却可以通过修改url来访问。。这个如何规避呢

请问解决了吗，我也想知道这种动态菜单咋控制url的输入

**Comment by xiaofeisss** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 如果动态菜单在前端没有对应的路由，那么访问这个菜单是无法正常显示内容的，这是正常的。如果你希望避免用户通过手动修改 URL 访问到没有开发的页面，可以在路由层面进行拦截。例如，可以在路由守卫中判断访问的路由是否存在于动态菜单中，如果不存在，则跳转到 404 页面。
> 
> 以下是一个简单的路由守卫示例：
> 
> ```js
> // 在路由配置文件中进行路由守卫的配置
> import router from './router'
> import getMenuData from './getMenuData'
> 
> // 白名单，不需要拦截的路由
> const whiteList = ['/login']
> 
> router.beforeEach(async (to, from, next) => {
>   // 获取动态菜单数据
>   const menuData = await getMenuData()
>   // 根据菜单数据生成路由的权限表
>   const permissionList = generatePermissionList(menuData)
>   // 检查访问的路由是否在权限表中存在
>   if (permissionList.includes(to.path)) {
>     next() // 跳转到目标路由
>   } else {
>     // 如果对应菜单不存在，则跳转到 404 页面
>     next('/404')
>   }
> })
> 
> // 利用动态菜单数据生成路由的权限表
> function generatePermissionList(menuData) {
>   const permissionList = []
>   menuData.forEach(menu => {
>     if (menu.path) {
>       permissionList.push(menu.path)
>       if (menu.children) {
>         permissionList.push(...generatePermissionList(menu.children))
>       }
>     }
>   })
>   return permissionList
> }
> ```
> 
> 此外，在前端进行页面现实之前也可以在后端进行权限控制的判断和拦截，防止未授权的请求直接返回未经授权的内容。

这个路由配置文件  应该在哪写？app.tsx 还是？

**Comment by chenshuai2144** [comment]
app.tsx  是 runtime 的，需要根据用户的行为发生变化的都应该在runtime里面
