### ISSUE TITLE
👑 [需求 | Feature]  请求帮助 怎么让左侧的侧边栏一直处于收起的状态？ 只能改umi的plugin-layout吗 担心打包不能用

### ISSUE THREAD

**Issue by NaroXing** [ant-design/ant-design-pro#10623]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🥰 需求描述 | Requirements description

如何让左侧的侧边栏默认处于收起的状态。

### 🧐 解决方案 | Solution

在 `plugin-layout` 中，有一个配置项可以控制侧边栏的默认状态：`collapse`。可以在 `config/config.js` 中的 `layout` 配置中设置该项为 `true`，即可让侧边栏默认处于收起的状态：

```javascript
export default {
  // ...
  layout: {
    // ...
    collapse: true,
  },
};
```

### 🚑 其他信息 | Other information

打包是否可以使用，取决于你使用的打包工具和配置。在使用 `umi build` 打包时，如果没有自定义配置，应该是可以正常使用的。如果有特殊的打包配置，请确保该配置不会影响到 `plugin-layout` 的相关配置。 

更多关于 `plugin-layout` 的信息可以查看 [官方文档](https://umijs.org/plugins/plugin-layout)。
