### ISSUE TITLE
图标显示问题

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#1062]
离线部署pro后，所有menu前面的icon显示为方框，why？

**Comment by chenshuai2144** [comment]
我们的图标是走的我们的 cdn，
你需要部署图标到本地，具体看 ant.design的教程。
可以参考这个
https://github.com/ant-design/ant-design-pro/issues/882

**Comment by zhaxingaz** [comment]
我参考#882，在 public 目录下放置iconfont的文件，修改\src\theme.js 文件，增加了一行： '@icon-url': '"/antIconfont/iconfont"'

然而没有起作用，我用的是top_nav版本

**Comment by zhaxingaz** [comment]
刚才修改没有生效，重启以后生效了，现在正常显示了
