### ISSUE TITLE
🧐[问题 | question]路由添加layout属性，访问菜单会意外收起

### ISSUE THREAD

**Issue by lztbwlkj** [ant-design/ant-design-pro#10628]
### 🧐 问题描述 | Problem description

路由添加layout属性，访问菜单会意外收起，layout属性是控制某一页面显示不显示左侧路由菜单，不知道是我理解错了吗？
![1](https://user-images.githubusercontent.com/20568661/226189414-c8cf4e17-cc91-42aa-bd6b-f7ff5f483cb3.gif)

如截图等其他信息可以贴在这里

![image](https://user-images.githubusercontent.com/20568661/226186398-145d6dda-bc72-4fd3-8de9-b1d34906b0a2.png)

OS: Windows 11

Node：
浏览器 | browser：
谷歌浏览器
![image](https://user-images.githubusercontent.com/20568661/226186423-0e3a76cc-d1fc-442a-bac0-97ffd76f028d.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

这个问题可以通过设置 `hideMenu` 属性来实现，该属性的值为布尔类型，如果为 `true`，则不显示左侧菜单，如果为 `false`，则显示左侧菜单。

下面是示例代码：

```javascript
import React from 'react';
import { Layout, Menu } from 'antd';
import { Link } from 'react-router-dom';

const { Header, Content, Footer, Sider } = Layout;

class PageLayout extends React.Component {
  state = {
    collapsed: false,
  };

  onCollapse = (collapsed) => {
    console.log(collapsed);
    this.setState({ collapsed });
  };

  render() {
    const { children, hideMenu } = this.props;
    const { collapsed } = this.state;

    return (
      <Layout style={{ minHeight: '100vh' }}>
        {hideMenu ? null : (
          <Sider collapsible collapsed={collapsed} onCollapse={this.onCollapse}>
            <div className="logo" />
            <Menu theme="dark" defaultSelectedKeys={['1']} mode="inline">
              <Menu.Item key="1">
                <Link to="/">Home</Link>
              </Menu.Item>
              <Menu.Item key="2">
                <Link to="/about">About</Link>
              </Menu.Item>
            </Menu>
          </Sider>
        )}
        <Layout className="site-layout">
          <Header className="site-layout-background" style={{ padding: 0 }} />
          <Content style={{ margin: '0 16px' }}>
            <div style={{ padding: 24, background: '#fff', minHeight: 360 }}>{children}</div>
          </Content>
          <Footer style={{ textAlign: 'center' }}>React App ©2021 Created by You</Footer>
        </Layout>
      </Layout>
    );
  }
}

export default PageLayout;
```

在具体使用 `PageLayout` 布局时，根据需求传入 `hideMenu` 属性即可。例如：

```javascript
<PageLayout hideMenu={true}>
  <div>这是一个不含左侧菜单的页面</div>
</PageLayout>
```

更多关于 `Layout` 的信息可以参考 Ant Design 的文档：https://ant.design/components/layout/ 。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


针对路由隐藏部分布局，可以通过在路由配置中添加`layout`属性来实现。`layout`属性可以控制页面是否显示左侧菜单、导航头和页脚。

在`config/route.ts`文件中，可以添加一个`layout`对象来设置需要隐藏的布局元素。例如，如果需要隐藏左侧菜单，可以将`hideMenu`设置为`true`；如果需要隐藏导航头，可以将`hideNav`设置为`true`；如果需要隐藏页脚，可以将`hideFooter`设置为`true`。

示例代码如下：

```tsx
// config/route.ts
export default [
  {
    path: '/overview',
    component: 'Overview/index',
    name: 'overview',
    icon: 'testicon',
    layout: {
      hideMenu: false,   // 是否隐藏左侧菜单
      hideNav: false,    // 是否隐藏导航头
      hideFooter: false, // 是否隐藏页脚
    },
  },
];
```

通过在路由配置中添加`layout`属性，并设置相应的布局隐藏选项，即可实现根据路由隐藏左侧菜单、导航头和页脚的效果。
