### ISSUE TITLE
yarn run i18n-remove报错🐛 [BUG]

### ISSUE THREAD

**Issue by webguicai** [ant-design/ant-design-pro#10620]
### 🐛 bug 描述
yarn run i18n-remove 报错

### 📷 复现步骤 | Recurrence steps
pro create my-app
yarn
yarn run i18n-remove

### 🏞 期望结果 | Expected results
执行成功

### 💻 复现代码 | Recurrence code
无

### © 版本信息
Ant Design Pro 版本: 6.0.0
umi 版本: 4.x
浏览器环境: Chrome
开发环境: node 16.19.0

### 🚑 其他信息
⠋ ✂️  remove locale for src/app.tsx.C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:175
                throw new Error(message);
                ^

Error: .eslintrc.js » C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@umijs\lint\dist\config\eslint\index.js:
        Environment key "es2022" is unknown

    at C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:175:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:169:34)
    at ConfigValidator.validateConfigArray (C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:319:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:299:21)
    at CLIEngine.executeOnText (C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\node_modules\eslint\lib\cli-engine\cli-engine.js:889:47)
    at eslintJS (C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\src\i18n\eslintJs.js:10:25)
    at C:\Users\ASUS\Desktop\work\ant-design-pro\node_modules\@ant-design\pro-cli\src\i18n\index.js:63:32
    at Array.forEach (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌈 解决方案 | Solution

这是一个 eslint 的报错，报错信息为:

```
Environment key "es2022" is unknown
```

这个是因为 eslint 还没有支持 ES2022，而在 umi 4.x 的默认配置中，`.eslintrc.js` 中的 `env` 配置了 `es2022` 环境，导致了这个错误。

解决方案就是修改 `.eslintrc.js`，去掉 `env.es2022` 配置，或者将 `env` 配置改为：

```js
env: {
  es2021: true,
  browser: true,
  node: true,
},
```

详细的解决方案可参考官方文档 [ESLint Configuration](https://umijs.org/docs/config#eslint-configuration)。

如果问题还没有解决，建议检查 ant-design-pro、umi 的版本是否与文档一致。

**Comment by zphtown** [comment]
+1，把所有useInt的代码删除了，也是提示这个错，可以正常运行，但是多语言的代码还在，且layout左侧菜单是空的

**Comment by zphtown** [comment]
第一步，手动移除代码里useInt 的代码，
第二步，打开src/eslintrc.js文件， 注释 extends: [require.resolve('@umijs/lint/dist/config/eslint')],
第三步，npm run i18n-remove
第四步，给config/routes.js 的每一项加上name
完工

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常感谢您分享自己的成功经验，这样的经验分享可以帮助更多的开发者，同时也让社区变得更加活跃和健康。手动移除代码并且注释掉 `eslint` 的配置是比较有效的解决方案，对于小错误可以排查一下系统给出的错误提示，也可以通过 issue 的沟通来获得更多的帮助。再次感谢您的分享！

**Comment by chenshuai2144** [comment]
已经修复啦

**Comment by NCH-0404** [comment]
> 已经修复啦

好像没有哦

**Comment by q20010012001001** [comment]
> 已经修复啦

修复了个球

**Comment by jetsung** [comment]
我把依赖全部都升级了一遍，然后解决问题了。

```bash
 "dependencies": {
    "@ant-design/icons": "^5.2.5",
    "@ant-design/pro-components": "^2.6.11",
    "@ant-design/use-emotion-css": "^1.0.4",
    "@umijs/route-utils": "^4.0.1",
    "antd": "^5.8.2",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "querystring": "^0.2.1",
    "rc-menu": "^9.11.1",
    "rc-util": "^5.36.0",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.6",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^3.1.0",
    "@testing-library/react": "^14.0.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.17",
    "@types/history": "^5.0.0",
    "@types/jest": "^29.5.3",
    "@types/lodash": "^4.14.196",
    "@types/react": "^18.2.19",
    "@types/react-dom": "^18.2.7",
    "@umijs/fabric": "^4.0.1",
    "@umijs/lint": "^4.0.74",
    "@umijs/max": "^4.0.74",
    "cross-env": "^7.0.3",
    "eslint": "^8.46.0",
    "express": "^4.18.2",
    "gh-pages": "^5.0.0",
    "husky": "^8.0.3",
    "jest": "^29.6.2",
    "jest-environment-jsdom": "^29.6.2",
    "lint-staged": "^13.2.3",
    "mockjs": "^1.1.0",
    "prettier": "^3.0.1",
    "swagger-ui-dist": "^5.3.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6",
    "umi-presets-pro": "^2.0.3"
  },
```

**Comment by luosiqi73** [comment]
have not fixed the issue lol

**Comment by 764213522** [comment]
好像可以这个方法

**Comment by 764213522** [comment]
> 看了issuer的评论，分享下自己成功去掉多语言的操作步骤 第一步，手动移除代码里useInt 的代码， 第二步，打开src/eslintrc.js文件， 注释 extends: [require.resolve('@umijs/lint/dist/config/eslint')], 第三步，npm run i18n-remove 第四步，给config/routes.ts 的每一项加上name 还有一些小错误，要自己解决

这个方法好像可以

**Comment by mixuedongcang** [comment]
> 我把依赖全部都升级了一遍，然后解决问题了。
> 
> ```shell
>  "dependencies": {
>     "@ant-design/icons": "^5.2.5",
>     "@ant-design/pro-components": "^2.6.11",
>     "@ant-design/use-emotion-css": "^1.0.4",
>     "@umijs/route-utils": "^4.0.1",
>     "antd": "^5.8.2",
>     "classnames": "^2.3.2",
>     "lodash": "^4.17.21",
>     "moment": "^2.29.4",
>     "omit.js": "^2.0.2",
>     "querystring": "^0.2.1",
>     "rc-menu": "^9.11.1",
>     "rc-util": "^5.36.0",
>     "react": "^18.2.0",
>     "react-dev-inspector": "^1.8.6",
>     "react-dom": "^18.2.0",
>     "react-helmet-async": "^1.3.0"
>   },
>   "devDependencies": {
>     "@ant-design/pro-cli": "^3.1.0",
>     "@testing-library/react": "^14.0.0",
>     "@types/classnames": "^2.3.1",
>     "@types/express": "^4.17.17",
>     "@types/history": "^5.0.0",
>     "@types/jest": "^29.5.3",
>     "@types/lodash": "^4.14.196",
>     "@types/react": "^18.2.19",
>     "@types/react-dom": "^18.2.7",
>     "@umijs/fabric": "^4.0.1",
>     "@umijs/lint": "^4.0.74",
>     "@umijs/max": "^4.0.74",
>     "cross-env": "^7.0.3",
>     "eslint": "^8.46.0",
>     "express": "^4.18.2",
>     "gh-pages": "^5.0.0",
>     "husky": "^8.0.3",
>     "jest": "^29.6.2",
>     "jest-environment-jsdom": "^29.6.2",
>     "lint-staged": "^13.2.3",
>     "mockjs": "^1.1.0",
>     "prettier": "^3.0.1",
>     "swagger-ui-dist": "^5.3.1",
>     "ts-node": "^10.9.1",
>     "typescript": "^5.1.6",
>     "umi-presets-pro": "^2.0.3"
>   },
> ```

这个有用

**Comment by odetteasosborneas** [comment]
> 我把依赖全部都升级了一遍，然后解决问题了。
> 
>  "dependencies": {
>     "@ant-design/icons": "^5.2.5",
>     "@ant-design/pro-components": "^2.6.11",
>     "@ant-design/use-emotion-css": "^1.0.4",
>     "@umijs/route-utils": "^4.0.1",
>     "antd": "^5.8.2",
>     "classnames": "^2.3.2",
>     "lodash": "^4.17.21",
>     "moment": "^2.29.4",
>     "omit.js": "^2.0.2",
>     "querystring": "^0.2.1",
>     "rc-menu": "^9.11.1",
>     "rc-util": "^5.36.0",
>     "react": "^18.2.0",
>     "react-dev-inspector": "^1.8.6",
>     "react-dom": "^18.2.0",
>     "react-helmet-async": "^1.3.0"
>   },
>   "devDependencies": {
>     "@ant-design/pro-cli": "^3.1.0",
>     "@testing-library/react": "^14.0.0",
>     "@types/classnames": "^2.3.1",
>     "@types/express": "^4.17.17",
>     "@types/history": "^5.0.0",
>     "@types/jest": "^29.5.3",
>     "@types/lodash": "^4.14.196",
>     "@types/react": "^18.2.19",
>     "@types/react-dom": "^18.2.7",
>     "@umijs/fabric": "^4.0.1",
>     "@umijs/lint": "^4.0.74",
>     "@umijs/max": "^4.0.74",
>     "cross-env": "^7.0.3",
>     "eslint": "^8.46.0",
>     "express": "^4.18.2",
>     "gh-pages": "^5.0.0",
>     "husky": "^8.0.3",
>     "jest": "^29.6.2",
>     "jest-environment-jsdom": "^29.6.2",
>     "lint-staged": "^13.2.3",
>     "mockjs": "^1.1.0",
>     "prettier": "^3.0.1",
>     "swagger-ui-dist": "^5.3.1",
>     "ts-node": "^10.9.1",
>     "typescript": "^5.1.6",
>     "umi-presets-pro": "^2.0.3"
>   },

国际化确实没了。但侧边栏也没了。
