### ISSUE TITLE
umi提供的useRequest的ready无效

### ISSUE THREAD

**Issue by 13554599576** [ant-design/ant-design-pro#10629]
```javascript
  const [selectDataOpen, setSelectDataOpen] = useState(true);
  const layerGroupsRequest = useRequest(() => Promise.resolve(1), {
    ready: selectDataOpen,
    refreshDeps: [selectDataOpen],
    onSuccess: (data) => {
      console.log(data);
    },
  });
```

selectDataOpen从true变为false的情况下，即使设置了ready，依旧会触发请求。
但是当我不使用umi/max的useRequest，替换为ahooks的useRequest时候，则不会出现此bug。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


首先需要明确的是，useRequest是来自于 umi 项目所提供的数据请求 hooks。

根据您提供的代码示例，你在使用 useRequest 时提供了 ready 配置项，其作用是控制 useRequest 是否开启自动请求，当配置为 false 时不自动调用接口。

在您的代码中，当 selectDataOpen 由 true 转为 false 的时候，依旧会触发请求，可能是因为您在 selectDataOpen 变化的时候触发了代码块，而 useRequest 接口请求不会受到影响。

您可以将 setState 的修改逻辑放在 useRequest 里的 onSuccess 里面，如下代码：

```javascript
const layerGroupsRequest = useRequest(() => Promise.resolve(1), {
  manual: true,
  onSuccess: (data) => {
    console.log(data);
    setSelectDataOpen(false);
  },
});

useEffect(() => {
  if (selectDataOpen) {
    layerGroupsRequest.run();
  }
}, [selectDataOpen, layerGroupsRequest]);

```

以上代码的 useRequest 为 manual 模式，手动调用接口，onSuccess 里面可以控制接下来的操作。不使用 useRequest，换用 ahooks 的 useRequest 时没有出现此 bug，应该是 ahooks 内部处理逻辑不同。

关于 useRequest 的更多介绍，请查看官方文档：https://hooks.umijs.org/zh-CN/hooks/async#userequest

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据您提供的代码和描述，您遇到的问题是在使用`umi`中提供的`useRequest`时，即使设置了`ready`为`true`，当`selectDataOpen`从`true`变为`false`时，仍然触发了请求。但是当您改为使用`ahooks`的`useRequest`时，不会出现这个问题。

解决方案可能有以下几种可能：
1. 检查`umi`的版本是否为最新版本。有时候，某些`umi`版本的`useRequest`可能存在一些已知的问题，通过更新到最新版本可以解决这些问题。
2. 检查`ready`的使用方式是否正确。在您的代码中，`ready`被设置为`selectDataOpen`的值，这意味着当`selectDataOpen`为`true`时，`ready`为`true`，请求应该被触发。如果您想要在`selectDataOpen`为`false`时不触发请求，您可以将`ready`设置为`!selectDataOpen`，这样当`selectDataOpen`为`false`时，`ready`为`true`。
3. 如果您使用的`umi`版本确实存在问题，您可以考虑切换到`ahooks`的`useRequest`。`ahooks`是一个由阿里巴巴开发的React Hook库，提供了许多React Hooks，包括`useRequest`。根据您的描述，使用`ahooks`的`useRequest`没有出现同样的问题，所以您可以考虑替换为`ahooks`的`useRequest`来解决这个问题。
