### ISSUE TITLE
有二级菜单时，一级菜单的内容会变成当前打开页面的内容🐛 [BUG]

### ISSUE THREAD

**Issue by BadSmile01** [ant-design/ant-design-pro#10638]
### 🐛 bug 描述
1、当只有1级菜单时功能正常；
2、如果菜单有2级菜单，则一级菜单的显示内容会变成右边显示区域的的主体内容；

### 📷 复现步骤 | Recurrence steps

下载项目后，yarn install  然后 yarn start 启动，访问后台，菜单报错

### 🏞 期望结果 | Expected results
正常显示一级菜单

### 💻 复现代码 | Recurrence code

https://github.com/jetlinks/jetlinks-ui-antd  仓库的2.0分支

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本[3.5.0]
- pro-layout版本[6.27.2]
- 浏览器环境[谷歌浏览器]
- 开发环境 [windows vs]
- node版本[16.18.0]
- npm版本[8.19.2]
- yarn版本[1.22.19]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12042770/227475299-18cf8c82-656a-4973-ac91-b90d4fe7a850.png)

![image](https://user-images.githubusercontent.com/12042770/227475419-8ce9d7cb-05ad-422e-af1e-dabc638ef673.png)

![image](https://user-images.githubusercontent.com/12042770/227475626-add80994-256a-4862-8b39-7b4221ba3908.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，这似乎是一个已知的问题，它是由于左侧菜单栏的链接与右侧内容区域的路由不一致导致的。 以下是一些解决方案可以帮助你解决这个问题。

1.在左侧菜单中的 link 键值中添加redirect属性 。

例如：

```javascript
{
  path:'/',
  name: '首页',
  icon: 'dashboard',
  redirect: '/dashboard/analysis',
  component: './Layout/BlankLayout',
  ...
}
```

2.使用 ProLayout 组件的 location 属性来获取当前的路由地址，以便正确选中菜单栏

例如：

```javascript
const BasicLayout: React.FC<Props> = ({ children }: Props) => {
  const location = useLocation();

  // 这里进行菜单与路由的匹配
  const [pathname, setPathname] = useState(location.pathname);
  useEffect(() => {
    setPathname(location.pathname);
  }, [location.pathname]);

  return (
    <ProLayout>
      ...
      <SiderMenu
        ...
        selectedKeys={[pathname]}
        ...
      />
      ...
      {children}
      ...
    </ProLayout>
  );
};
```

希望这些解决方案能够帮助你解决问题。如果你觉得需要更多的帮助，请参考React官方文档中有关路由和菜单的章节或者Ant Design Pro官方文档中的相关章节。

**Comment by chenshuai2144** [comment]
注意下你的key不要相同，这种玄幻问题一般是 path 或者key相同了
