### ISSUE TITLE
🐛 [BUG] 路由权限设置access后 切换两个账号时需要手动刷新页面权限才生效

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design-pro#10636]
![image](https://user-images.githubusercontent.com/23204297/227416044-c0edf98b-4f3c-4bae-abe5-d3938df712f1.png)

刷新页面的话，是生效的，但是两个账号进行切换就会导致页面还是旧账号的权限
看了半天没看懂有什么解决方案

**Comment by xiaofeisss** [comment]
刷新可以生效，你可以看一下切换时销毁本地用户信息，登录后本地数据有没有更新。

**Comment by zozopen** [comment]
> 刷新可以生效，你可以看一下切换时销毁本地用户信息，登录后本地数据有没有更新。

目前是通过刷新refresh 后的回调然后再进行跳转，其实他就是因为异步导致的，已经解决了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


很好，那么问题已经解决了。如果在后续的代码中还遇到了类似的问题，可以考虑以下一些方案：

1. 在切换账号时，先清空本地数据，再重新获取更新过的数据。

2. 使用路由拦截器，在切换路由时进行一些逻辑操作，比如检查本地数据是否已经更新。

3. 使用 Vuex 管理本地的用户数据，保证数据的唯一性和正确性。

希望这些方案能够帮到你，如果还有什么问题，请随时提出。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述和参考文档，可能的解决方案如下：

1. 确保路由权限配置正确：检查路由配置文件，确认每个路由都有正确的权限配置（`access`字段）。

2. 使用动态路由：将路由配置从静态文件中移动到后端，使用动态路由来根据当前用户的权限动态生成路由配置。

3. 使用登录/注销事件：在登录和注销的时候，手动刷新路由或者重新加载权限配置，从而实现权限的动态更新。

4. 使用中间件或拦截器：在路由切换的前后，通过中间件或拦截器来检查当前用户的权限，并根据权限进行相应的处理。

5. 使用 localStorage 或者 sessionStorage：将当前用户的权限信息存储在 localStorage 或者 sessionStorage 中，每次路由切换时，先读取权限信息，然后根据权限信息来展示不同的组件或页面。

6. 使用异步加载组件：将权限相关的组件异步加载，当切换账号时，通过重新加载组件来更新权限。

需要根据具体业务场景和技术栈选择最合适的解决方案，并进行相应的调整和实现。另外，建议在项目中使用前端框架如 React，以及相关的库如 Umi 和 antd，来提高开发效率和代码质量。
