### ISSUE TITLE
🧐[问题 | question]preview.pro.ant.design的源码库是哪个？

### ISSUE THREAD

**Issue by dingshukai** [ant-design/ant-design-pro#10631]
### 🧐 问题描述 | Problem description
http://preview.pro.ant.design 这个页面有相当丰富的示例，但我没找到对应的源码库。
我看到2019年有人问过，下面的答案好像都不是。
https://github.com/ant-design/ant-design-pro/issues/4545

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by Chenxiangju** [comment]
根据文档安装脚手架 选择complete 完整版就可以了

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的问题。根据您提供的信息，可能是您在寻找 `preview.pro.ant.design` 的源码库。该网站实际上是由 `ant-design-pro` 提供的前端项目脚手架所构建的。

`ant-design-pro` 基于 `ant-design` 和 `umi` 框架，提供了一些组件和示例，可以快速构建出一个具有良好体验的企业级管理后台。您可以前往 `ant-design-pro` 的官网查看更多信息和文档：https://pro.ant.design/。

下面是在命令行中安装 `ant-design-pro` 脚手架的方式：

首先，确保您已经安装了 Node.js 和 Git。

然后，通过以下命令安装 `umi`：

```bash
npm install -g umi
```

接着，通过以下命令安装 `ant-design-pro`：

```bash
mkdir my-project && cd my-project
umi init
# 然后选择 complete 完整版即可
```

安装完成后，运行以下命令启动项目：

```bash
npm run start
```

希望以上内容能够对您有所帮助。如有疑问，可以随时提出。

**Comment by choi2k** [comment]
> > TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
> > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。
> 
> 感谢您的问题。根据您提供的信息，可能是您在寻找 `preview.pro.ant.design` 的源码库。该网站实际上是由 `ant-design-pro` 提供的前端项目脚手架所构建的。
> 
> `ant-design-pro` 基于 `ant-design` 和 `umi` 框架，提供了一些组件和示例，可以快速构建出一个具有良好体验的企业级管理后台。您可以前往 `ant-design-pro` 的官网查看更多信息和文档：[https://pro.ant.design/。](https://pro.ant.design/%E3%80%82)
> 
> 下面是在命令行中安装 `ant-design-pro` 脚手架的方式：
> 
> 首先，确保您已经安装了 Node.js 和 Git。
> 
> 然后，通过以下命令安装 `umi`：
> 
> ```shell
> npm install -g umi
> ```
> 
> 接着，通过以下命令安装 `ant-design-pro`：
> 
> ```shell
> mkdir my-project && cd my-project
> umi init
> # 然后选择 complete 完整版即可
> ```
> 
> 安装完成后，运行以下命令启动项目：
> 
> ```shell
> npm run start
> ```
> 
> 希望以上内容能够对您有所帮助。如有疑问，可以随时提出。

`umi init` 并不存在


Did you mean this command ?
 - lint

fatal - Error: Invalid command init, it's not registered.

**Comment by choi2k** [comment]
看起来是 umi@3 才有. 

https://pro.ant.design/docs/getting-started/

```
🐂 Use umi@4 or umi@3 ? (use arrow keys)
❯ umi@4
  umi@3
  
  🚀 Do you want the full amount or a simple scaffolding? (use arrow keys)
❯ simple
  complete
  
```

只有 umi3 才有 `complete` template 选项

**Comment by chenshuai2144** [comment]
现在还没支持 umi4，在 all-block 分支内
