### ISSUE TITLE
🧐[问题 | question]可以全局配置关闭 pageHeaderRender 吗

### ISSUE THREAD

**Issue by shiningstarts** [ant-design/ant-design-pro#10639]
### 🧐 问题描述 | Problem description

qiankun 的子应用为 antdesign，当前在 `app.tsx` 内只能配置 `pageTitleRender` 和 `breadcrumbRender`，最终渲染出来的结果是会留有空白的 pageHeader，效果如图：
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/22713311/227480796-5876b214-9b50-49c5-9bbc-aac06fe6726e.png">

当前可以去每个页面配置 `pageHeaderRender` 处理，请问有办法全局处理吗？

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 📝 回答 | Answer

可以通过修改 qiankun 的源代码来达到全局配置的效果。在 `micro-apps-utils` 中的 `render` 函数内，将代码：

```js
if (props.pageHeaderRender) {
  return props.pageHeaderRender({ ...props, ...childProps });
}
```

修改为：

```js
if (!props.pageHeaderRender) {
  const renderEmptyPageHeader = () => <PageHeader title={null} />;
  return renderEmptyPageHeader({ ...props, ...childProps });
}
if (props.pageHeaderRender) {
  return props.pageHeaderRender({ ...props, ...childProps });
}
```

这里做了两件事情：
1. 如果 `pageHeaderRender` 不存在，则渲染出一个空的 `PageHeader`。
2. 如果 `pageHeaderRender` 存在，则正常渲染页面的 `PageHeader`。

这里值得注意的地方是：由于 `render` 函数最终返回的是一个组件，因此我们需要将空的 `PageHeader` 也封装成一个组件。

最终的效果如下：
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/22713311/227711653-5a5c9089-eed2-4b35-a2c8-ace478938f1d.png">

### 🔗 参考链接 | Reference link

- qiankun 的 GitHub 仓库：https://github.com/umijs/qiankun
- antd 的 PageHeader 组件文档：https://ant.design/components/page-header-cn/
