### ISSUE TITLE
需要新建一个chart，看了一下A网址，不知如何部署到B网址“销售额类别占比”上？请写详细步骤。

### ISSUE THREAD

**Issue by cyp66** [ant-design/ant-design-pro#1063]
A：https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/other/cutomize-legend
B：https://preview.pro.ant.design/#/dashboard/analysis

**Comment by afc163** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
