### ISSUE TITLE
🧐[问题 | question] 不同路由页面第一次加载时候，Prolayout根据页面资源加载的自动loading不在了？

### ISSUE THREAD

**Issue by Lands-1203** [ant-design/ant-design-pro#10646]
![image](https://user-images.githubusercontent.com/61341868/227885587-ebf03764-80c2-4b43-a846-a1b8cd0f3703.png)

通过最新版本的pro create 命令生成的项目 第一次加载不同的路由时 自动loading不存在了？
请问怎么才能弄出来？

**Comment by hpf0532** [comment]
https://umijs.org/docs/guides/directory-structure#loadingtsxjsx

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据您提供的信息，解决这个问题需要修改 `src/layouts/index.tsx` 文件中的 loading 组件的引入方式。

具体来说，您需要在 `src/layouts/index.tsx` 文件开头添加以下代码：

```tsx
import Loading from '@/components/PageLoading';
```

然后，在 `return` 语句中，将 `<PageLoading/>` 组件改为 `<Loading/>` 组件，例如：

```tsx
return (
  <ProLayout
    {...settings}
    {...this.props}
    {...this.state}
    menuDataRender={memoizedMenuDataRender}
    onPageChange={this.handlePageChange}
    menuItemRender={this.menuItemRender}
    breadcrumbRender={this.breadcrumbRender}
    rightContentRender={this.rightContentRender}
    postMenuData={menuData => {
      this.setState({
        menuData
      });
    }}
    {...isMobile}
    {...headerRender}
    {...footerRender}
    {...menuProps} // 用于菜单 RTL
    loading={<Loading />}
  >
    {this.props.children}
  </ProLayout>
);
```

然后运行 `umi dev` 命令重新启动项目，这样在不同路由页面第一次加载时候，就可以根据页面资源加载的自动 loading 了。

如果您想了解更多有关 ProLayout 中 loading 的信息，请参考[官方文档](https://pro.ant.design/components/layout-cn/#description)。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题的解决方案如下：

1. 首先，需要确保项目中已启用了代码分割功能。可以在项目配置文件中检查`dynamicImport`选项是否已正确配置，示例如下：

```tsx
export default {
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  // other configurations...
}
```

2. 确保`@ant-design/pro-layout`模块已正确导入并安装。

3. 在代码中使用了`import()`语法动态导入组件时，确保导入的路径正确且组件文件存在。例如，检查路由配置文件中是否正确导入了页面组件。

4. 如果上述步骤都正确，但自动loading仍然不显示，可以尝试清除项目的编译缓存，然后重新构建项目。可以运行以下命令进行清除：

```bash
umi clean
```

然后重新运行项目：

```bash
umi dev
```

通过以上步骤，应该可以解决页面加载时自动loading不显示的问题。如果问题仍然存在，可以进一步检查项目的其他配置和代码逻辑，以确定是否有其他因素导致该问题的出现。
