### ISSUE TITLE
🧐[怎麼能跳過login頁面，也就是不需要登录页面]

### ISSUE THREAD

**Issue by codeHui** [ant-design/ant-design-pro#10640]
### 🧐 问题描述 | Problem description
怎麼能跳過login頁面，直接显示主页面？？
我想把web嵌入iframe到其他的系统，比如通过url里面的一个token去确定用户是admin，
我希望打开这个带着token的url时，就是直接到达主页面，而不是login页面。有办法吗，谢谢，我主要是后端强，前端一般般

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 📝 解决方案 | Solution
如果你想通过 URL 传递 token 避免需要登录，那么前端部分可以这么实现：

1. 将 token 进行编码或加密然后通过 URL 传递。

2. 当访问首页时，从 URL 解析 token。这可以通过 window.location.search 和 URLSearchParams 来解析 URL 中的参数。

3. 如果存在 token，就向服务器发送请求。这可以使用 axios 或 fetch 等 JavaScript 库来处理。根据返回的结果，如果认证通过，就把认证后的信息存储起来，以便后面使用。

下面是一个示例代码：

```javascript
import axios from 'axios';

// 将 url 中的参数解析为对象
function parseQuery(query) {
  return Object.fromEntries(new URLSearchParams(query));
}

// 从 URL 中解析 token
const { token } = parseQuery(window.location.search);

// 构建 axios 实例
const api = axios.create({
  baseURL: '<YOUR API BASE URL>',
});

// 发送认证请求
api.post('/auth', { token })
  .then(({ data }) => {
    // 认证通过，将认证后的信息存储到本地存储中
    localStorage.setItem('auth', JSON.stringify(data));
  })
  .catch((err) => {
    // 认证失败，重定向到登录页
    window.location.href = '/login';
  });
```

这个示例代码假设 API 路由 `/auth` 用于认证，它接收一个包含 token 的 POST 请求，如果认证通过，就返回一个包含认证信息的 JSON 对象。

当页面被加载时，从 URL 中解析出 token，然后通过 `api.post` 发送认证请求，如果认证通过，就将认证信息存储在本地存储中。如果认证失败，会重定向到登录页。

需要注意的是，这个示例代码只是一个简单的实现，还可以添加更多的错误处理、请求头设置等。

另外，如果你希望使用 React，可以通过创建一个高阶组件（HOC）来实现类似的功能。这样，你可以在需要认证的页面上使用这个 HOC，而无需在每个页面都写重复的认证逻辑。

**Comment by zxc125** [comment]
hello [可以根据umijs提供的API来解决这个问题？
[onRouteChange](https://umijs.org/docs/api/runtime-config#onroutechange-routes-clientroutes-location-action-basename-isfirst-)
![image](https://user-images.githubusercontent.com/54338748/229456738-e5b73900-d9a6-484c-a77b-f3954db91e7e.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以通过 UmiJS 提供的 `onRouteChange` 钩子来实现跳过登录页面的功能。`onRouteChange` 钩子会在路由变化时触发，你可以在钩子函数中根据需要进行一些处理。

下面是一个示例代码：

```javascript
// src/app.js

import { useHistory } from 'umi';

export function onRouteChange({ location }) {
  const history = useHistory();

  // 如果要访问的页面不是登录页，且用户还没有登录，则跳转到登录页
  if (location.pathname !== '/login' && !isAuthenticated()) {
    history.replace('/login');
  }
}

function isAuthenticated() {
  // 检查用户是否已经登录，可以从本地存储、cookie 或者服务端获取
  return false;
}
```

这个示例代码定义了一个 `onRouteChange` 钩子函数，它检查用户是否已经登录。如果要访问的页面不是登录页，且用户还没有登录，则跳转到登录页。

`onRouteChange` 钩子需要在 `src/app.js` 文件中定义，并且 UmiJS 会在运行时自动调用它。如果你需要获取更多关于 UmiJS 的信息，可以查看 [UmiJS 文档](https://umijs.org/docs/)。
