### ISSUE TITLE
是 antd 的bug，等待antd 新版本来修复一下，在2023年 3 月14 号就可以修复

### ISSUE THREAD

**Issue by pc110** [ant-design/ant-design-pro#10648]
是 antd 的bug，等待antd 新版本来修复一下，在2023年 3 月14 号就可以修复

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/10592#issuecomment-1465173336_
            
还是没有修复了？ 什么时候能修复啊？ 等着使用呀，大佬能安排下不。 非常感谢呀！

**Comment by sherfruit** [comment]
同等

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您的关注。针对您的问题，我们需要更具体的信息来查明问题所在及其解决方案。请您提供以下信息：

1. 您在使用 antd 时遇到了什么具体问题？可能包括错误提示、页面功能无法正常使用等。
2. 您在哪个版本的 antd 上出现了这个问题？如果您没有确定这一点，请在命令行中输入 `npm list antd`，然后将输出内容粘贴在回复中。
3. 您使用的是哪个 React 版本？请在命令行中输入 `npm list react`，然后将输出内容粘贴在回复中。
4. 如果您有任何相关的代码或截图，请在回复中提供。

根据提供的信息，我们将尽力为您提供解决方案。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉让您等待了这么久。关于您提到的Antd问题，我们需要更多的细节信息，以便更好地了解问题并提供有效的解决方案。

请您提供以下信息：

1. 您在使用 antd 时遇到了什么具体问题？可能包括错误提示，组件样式不正常，页面功能无法正常使用等。
2. 您在哪个版本的 antd 上出现了这个问题？您可以在命令行中输入 `npm list antd`，然后将输出内容粘贴在回复中。
3. 您使用的是哪个 React 版本？您可以在命令行中输入 `npm list react`，然后将输出内容粘贴在回复中。
4. 如果您有任何相关的代码或截图，请在回复中提供，这将更有助于我们理解问题。

拥有这些信息，我们可以更好地了解您遇到的问题并为您提供解决方案。感谢您的配合。

**Comment by chenshuai2144** [comment]
已经修复了
