### ISSUE TITLE
🐛 [BUG]控制台报错Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#10642]
### 🐛 bug 描述

控制台报错Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
### 📷 复现步骤 | Recurrence steps

npx pro create learn
tyarn start
登录后点到二级管理页面
控制台一大堆报错

### 🏞 期望结果 | Expected results

能够正常

### 💻 复现代码 | Recurrence code

无

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本  umi4
- 浏览器环境 chrome
- 开发环境 win

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/5431843/227702851-18b061ec-92af-4a92-9a44-75e41db1d756.png)
生成器生成的代码，自己什么都没改

**Comment by bairubing-xenera** [comment]
我也是这个问题

**Comment by matriox1003** [comment]
一样的问题

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，这个警告多数是由于出现嵌套的`<a>`标记引起的。你可以通过检查代码是否有多余的`<a>`标记来解决此警告。如果不是这个问题，那么可能是插件或库中的问题，需要进一步检查。

在这种情况下，根据你提供的信息和截图，似乎确实是因为面包屑中存在多个`<a>`标签导致的。你可以将面包屑中的某个或某几个`<a>`标记替换为`<span>`或`<div>`等其他标签，因为面包屑并不需要链接，而只需要显示导航路径即可。例如：

```jsx
<Breadcrumb.Item>
  <a href="#">首页</a>
</Breadcrumb.Item>
<Breadcrumb.Item>
  <span>二级页面</span>
</Breadcrumb.Item>
```

这样应该就可以避免该警告了。

另外，对于此类问题，你也可以通过修改 React 的配置来禁用此警告：

```jsx
import {unstable_createMuiStrictModeTheme} from '@material-ui/core';

// 如果配置了 webpack
module.exports = {
  // ...
  plugins: [
    new webpack.DefinePlugin({
      __REACT_STRICT_MODE__: false,
    }),
  ],
};

// 如果没有配置 webpack
import {unstable_createMuiStrictModeTheme} from '@material-ui/core';

window.__REACT_DEVTOOLS_GLOBAL_HOOK__.supportsFiber = true;
window.__REACT_DEVTOOLS_GLOBAL_HOOK__.rendererSupportsSchedulingProfiler = true;
window.__REACT_STRICT_MODE__ = false;
```

希望以上信息能够帮助你解决问题。

**Comment by ideaviewes** [comment]
@chenshuai2144 ，您好，面包屑导航是PageContainer自动生成的，它自动生成的有问题

**Comment by Cc28256** [comment]
@chenshuai2144 我也遇到了同样的问题 什么都没有更改源代码 直接生成就会出现这个报错在同样的二级管理页面 我尝试将页面的PageContainer去掉就不会报错了 我认为是你们的bug 你提供的方案无法解决我们的报错

**Comment by ideaviewes** [comment]
@Cc28256 ,这个答复感觉想使用chatgpt直接生成的，没有人工看这个问题具体是什么

**Comment by Cc28256** [comment]
@ideaviewes 哦哦确实是 没注意上面的标注 这bug都这么多天了都没人跟进 着实离谱。。ant desn的我当时提交他3分钟就回复我了 这个咋这么慢

**Comment by chenshuai2144** [comment]
修复了，换了个解决方案

**Comment by ideaviewes** [comment]
> 修复了，换了个解决方案

嗯，我之前给procomponent的组件库升级到最新版好了
