### ISSUE TITLE
🐛 [BUG]多标签功能显示异常（tabs、mix、splitMenus）

### ISSUE THREAD

**Issue by sciisc** [ant-design/ant-design-pro#10644]
### 🐛 bug 描述

在启用多标签功能后，设置splitMenus:true，多标签显示异常，关闭也有问题

### 📷 复现步骤 | Recurrence steps
1、config配置：
```
  keepalive: [/./],
  tabsLayout: {},
```
2、defaultSettings配置
```
layout: 'mix',
splitMenus: true,
```
3、菜单结构：
```
  {
    name: 'test1',
    path: '/jlkd',
    icon: 'codeSandbox',
    routes: [
      { path: '/jlkd', redirect: '/jlkd/opr' },
      {
        name: 'test2',
        path: '/jlkd/opr',
        icon: 'codeSandbox',
        component: './JianLiangKongDa/OrderPurifyingRod',
      },
    ],
  },
```
出现以下异常：
![image](https://user-images.githubusercontent.com/36366504/227817174-9ec53fc3-12b6-4a81-a3e2-9ede9e88817e.png)

menu.jlkd标签不期望出现，并且会遮挡test2标签的显示，在关闭menu.jlkd标签之前，test2标签不能正常关闭。

推测试二级菜单里的默认路由问题，这个菜单树里有两个相同path

### 🏞 期望结果 | Expected results

期望菜单能正常显示、关闭

### 💻 复现代码 | Recurrence code

见复现步骤

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0]
- umi 版本: 4.0.52
- 浏览器环境: chrome 105
- 开发环境 [e.g. win11]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi，感谢您的反馈。根据您提供的信息，我们发现问题可能是由于菜单树中的两个相同路径引起的冲突导致的。请尝试删除菜单树中的多余路径，并将 `routes` 数组改为 `menu` 数组。

修改之后的菜单结构如下：

```
{
  path: '/jlkd',
  name: 'test1',
  icon: 'codeSandbox',
  menu: [
    { 
      name: 'test2',
      path: '/jlkd/opr',
      icon: 'codeSandbox',
      component: './JianLiangKongDa/OrderPurifyingRod',
    }
  ],
}
```

同时，如果您需要启用 splitMenus 功能，请确保在 umi 配置文件 `config.ts` 中添加以下配置：

```
export default {
  keepalive: [/./],
  tabsLayout: {},
  menu: {
    // 只有开启 splitMenus 功能才需要配置这一项
    splitMenus: true,
  },
};
```

如果您的问题还未得到解决，请提供更多的信息或者代码片段，方便我们更好地定位问题。感谢您的支持！

**Comment by chenshuai2144** [comment]
官网不兼容多标签页 找响应的插件维护者解决吧

**Comment by gaoobin** [comment]
这个问题解决了没
