### ISSUE TITLE
🐛 [BUG]: Antd pro table converts some specific integer value to string itself.

### ISSUE THREAD

**Issue by BiswasRai** [ant-design/ant-design-pro#10653]
### 🐛 bug 描述

Hi, I'm using antd pro table to show some data, When I have integer value which is 23, 24, 25 it converts itself to string eg. Twenty Three etc.

### 📷 复现步骤 | Recurrence steps
1. Just add value 23, 24, 25 it converts to string.
![twenty_three_bug](https://user-images.githubusercontent.com/38395536/229304368-2aeb7ac2-af08-4aea-983e-28bdd1a191a0.gif)

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本 4
- 浏览器环境
- 开发环境 Linux, PopOs, Chrome

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您的提交，根据您的问题描述，可能是因为 antd pro table 自动将特定的数值转为了字符串展示。这种转换是 antd pro table 的内部实现，如果您想更改此功能，可以通过设置 `valueType` 属性来禁用此功能。

例如，如果您想要将所有数据值都展示为数字，可以在列配置中使用 `valueType: 'digit'`。以下是示例代码：

```jsx
const columns = [
  {
    title: 'Number',
    dataIndex: 'number',
    valueType: 'digit',
  },
  // 其他列配置
];

function ExampleTable(props) {
  const { data } = props;

  return <ProTable columns={columns} dataSource={data} />;
}
```

更多 `valueType` 可以参考 antd 文档：https://ant.design/components/table-cn/#valueType

希望这个解决方案可以帮到您。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


这个问题是关于 Antd Pro Table 将一些特定的整数值转换为字符串的问题。你提供的信息表明你使用的是 Ant Design Pro 版本 6.0.0 和 umi 版本 4。根据最新的 Ant Design Pro 更新日志（5.0.7），其中包括一些修复，可能会解决你遇到的问题。

解决方案是将 Ant Design Pro 升级到 5.0.7 版本。这个版本包含了修复 Slider 组件 Tooltip 动画丢失、Table 组件有边框且为空时出现横向滚动条、Popover 组件箭头背景色不随自定义颜色改变、Modal hooks 没有完全传递 ConfigProvider 配置、Radio 组件尺寸修改后不对齐等问题的修复。

你只需按照以下步骤进行升级：

1. 打开你的项目文件夹。
2. 找到 `package.json` 文件。
3. 找到 `"@ant-design/pro-table"` 的依赖项。
4. 修改 `"@ant-design/pro-table"` 的版本为 `"5.0.7"`。
5. 保存文件。
6. 在终端中运行 `npm install` 或 `yarn install` 来安装更新的依赖项。
7. 运行你的项目，并检查是否仍然存在转换为字符串的问题。

希望这个解决方案能够帮助你解决问题！如果问题仍然存在，请提供更多的细节和复现代码，以便我们能够更好地帮助你。
