### ISSUE TITLE
关于带参数页面路由的问题

### ISSUE THREAD

**Issue by lamjack** [ant-design/ant-design-pro#1065]
例如我路径是这样 /cms/news, /cms/news/:id，

菜单对应是 内容管理 - 新闻,

/cms/news/:id这层在菜单是不出现的，debug发现 /cms/news的路由 exact 是 true，

无论访问 /cms/news 还是 /cms/news/5 都是用 /cms/news 指向的component.

**Comment by ddcat1115** [comment]
/cms/news/:id 这层有配在 router.js 里么？

**Comment by lamjack** [comment]
有，去掉/cms/news这层/cms/news/:id就可以访问。

**Comment by ddcat1115** [comment]
> /cms/news/:id这层在菜单是不出现的，debug发现 /cms/news的路由 exact 是 true，

如果有配置 `/cms/news/:id`，`/cms/news` 解析出来不应该是 exact...

现在的问题应该是 `/cms/news/:id` 对应的组件没有正常渲染？猜你可能需要看下这个 [文档](https://pro.ant.design/docs/router-and-nav-cn#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA)

**Comment by lamjack** [comment]
举个栗子，我的路由配置是这样，getRouterData,
```
...
 const routerConfig = {
        '/': {
            component: dynamicWrapper(app, [''], () => import('../layouts/BasicLayout')),
        },
        '/cms/news': {
            component: dynamicWrapper(app, [''], () => import('../routes/Content/NewList')),
        },
        '/cms/news/:id': {
            component: dynamicWrapper(app, [], () => import('../routes/Content/NewsDetail')),
        },
    };
...
```

然后到了BasicLayout里面getRoutes，是这样的,
<Route path="/cms/news" exact={false} ... />
<Route path="/cms/news/:id" exact={false} ... />

导致无论访问/cms/news还是/cms/news/12 都是走第一条路由..

**Comment by ddcat1115** [comment]
如果 /cms/news/1 需要在 /cms/news 的组件里嵌套展示，就参照 [List](https://github.com/ant-design/ant-design-pro/blob/master/src/routes/List/List.js) 及其路由配置

如果不需要，就参照上面给出的文档里的方法。在 /cms/news 渲染的这一级，getRoutes 会把 /cms/news/1 这一级过滤掉。或者你也可以不用 getRoutes，直接拿 routerData 处理

**Comment by lamjack** [comment]
我稍微改了下getRoute方法，默认把所有的exact改为ture，然后getRenderArr方法里面只要不完全相同的路由就不过滤，这样的话如果我需要处理同级渲染就在路由里面配置下即可，@ddcat1115 谢谢回答。
