### ISSUE TITLE
🐛 [BUG] 移动端菜单token只有部分生效

### ISSUE THREAD

**Issue by CementSealing** [ant-design/ant-design-pro#10657]
### 🐛 bug 描述

token:
```
token: {
  sider: { colorMenuBackground: '#001529',colorBgMenuItemSelected: '#1890ff',colorTextMenuTitle: '#ffffff',colorTextMenu: '#a6adb4', colorTextMenuSelected: '#fff', colorTextMenuItemHover: '#fff', colorTextMenuActive: '#fff', },
}
```
电脑端菜单显示：
![image](https://user-images.githubusercontent.com/97492682/229728717-7b9c9213-4db6-4f5b-8646-29559a7b903f.png)

移动端菜单显示：
![image](https://user-images.githubusercontent.com/97492682/229728997-c6e6fc18-bb47-490a-8128-bd9696873b3d.png)

### 🏞 期望结果 | Expected results

移动端菜单token生效，移动端菜单显示与电脑端菜单显示一致

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这里提供一些初步的原因和可能的解决方案：

原因：可能是移动端菜单的 DOM 结构和电脑端菜单的 DOM 结构不同，导致 token 部分生效，部分不生效。

解决方案：
1. 可以在移动端的菜单代码中，查看具体的 DOM 结构，针对移动端菜单的 DOM 结构，修改需要生效的样式的选择器，以保证样式生效。
2. 如果移动端菜单代码是使用 antd 原生组件实现的，可以根据 antd 提供的 [样式覆盖](https://ant.design/docs/react/customize-theme-cn#%E8%A6%86%E7%9B%96%E6%A0%B7%E5%BC%8F) 方法，对需要修改的样式进行覆盖，并在移动端的菜单代码中引入自定义的样式文件即可。
3. 如果移动端菜单代码是使用自定义组件实现的，可以在组件所在的样式文件中，针对特定的选择器设置具体的样式即可。

需要注意的是，如果移动端的菜单代码和电脑端的菜单代码共用部分，可能也需要对共用部分的样式进行适当的适配，以避免出现不同样式之间的冲突。 

如果以上方案都不能解决问题，可以提供更多的代码和相关的信息，以便更好地帮助您解决问题。

**Comment by jby123** [comment]
pc 端有完整 可以先做到以下效果的
![image](https://github.com/ant-design/ant-design-pro/assets/46490104/0bc0f73f-3ab7-4f8f-b2a3-e84968c37d7f)

**Comment by Youmyin** [comment]
> pc 端有完整 可以先做到以下效果的 ![image](https://user-images.githubusercontent.com/46490104/238395913-0bc0f73f-3ab7-4f8f-b2a3-e84968c37d7f.png)

请问你的antd版本、pro-components版本分别是多少呀，我antd 4.23.3，pro-components是2.4.15，web端配置token也是部分生效

**Comment by jby123** [comment]
"@ant-design/pro-components": "^2.3.57",
"antd": "^5.2.2",

**Comment by jby123** [comment]
> > pc 端有完整 可以先做到以下效果的 ![image](https://user-images.githubusercontent.com/46490104/238395913-0bc0f73f-3ab7-4f8f-b2a3-e84968c37d7f.png)
> 
> 请问你的antd版本、pro-components版本分别是多少呀，我antd 4.23.3，pro-components是2.4.15，web端配置token也是部分生效

"@ant-design/pro-components": "^2.3.57",
"antd": "^5.2.2",

**Comment by chenshuai2144** [comment]
这个问题修复掉了，主要是背景颜色的问题
