### ISSUE TITLE
🧐[问题 | question] How to pass Table props through ProTable?

### ISSUE THREAD

**Issue by zxti** [ant-design/ant-design-pro#10650]
If I am using ProTable, but I want to pass Table props like `scroll`, how do I do that? Thanks!

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


To pass Table props like `scroll` through `ProTable`, you can use the `tableProps` attribute. 

Here's an example:

```javascript
import ProTable from '@ant-design/pro-table';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
  },
];

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
  },
];

const tableProps = {
  scroll: { x: 'max-content' },
};

const Demo = () => {
  return (
    <ProTable
      columns={columns}
      dataSource={data}
      tableProps={tableProps}
    />
  );
};
```

In this example, we passed a `scroll` property into `tableProps`, and set its value to an object with an x property of 'max-content'. This will enable horizontal scrolling for the table.

You can pass any Table props using this method. Please refer to the Ant Design documentation for a list of all available Table props: https://ant.design/components/table/.

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


要通过ProTable传递Table的props，你可以使用ProTable组件的props来覆盖Table的props。在这种情况下，你想传递scroll prop，你可以在ProTable组件中添加一个scroll prop。

下面是具体的解决方案：

```tsx
return (
  <ProTable<Member>
    columns={columns}
    request={(params, sorter, filter) => {
      console.log(params, sorter, filter);
      return Promise.resolve({
        data: memberList,
        success: true,
      });
    }}
    rowKey="id"
    pagination={{
      showQuickJumper: true,
    }}
    toolBarRender={false}
    search={false}
    scroll={{ x: '100%', y: 400 }} // 添加scroll prop
  />
);
```

在这个例子中，我们在ProTable组件上添加了一个scroll prop，它的值是一个对象，包含x和y属性。x属性设置为'100%'，表示水平滚动，y属性设置为400，表示垂直滚动。你可以根据你的需求来调整scroll的值。

这样，你就可以通过ProTable传递Table的props了。

希望对你有所帮助！
