### ISSUE TITLE
打包之后上线显示白屏,但是通过预览命令能正常运行.

### ISSUE THREAD

**Issue by HAjiMa666** [ant-design/ant-design-pro#10664]
🧐 问题描述 | 打包之后上线显示白屏,但是通过预览命令能正常运行.
刚用pro创建的项目,用LiveServer预览index.html同样是白屏,上线后还是白屏,只有在本地才是正常的,控制台没有任何报错

💻 示例代码 | Sample code
🚑 其他信息 | Other information
![image](https://user-images.githubusercontent.com/70849018/230823117-2ae7b0ef-8035-4d40-ae34-a5e689d76d94.png)
image
![image](https://user-images.githubusercontent.com/70849018/230823153-efd5d898-0b5a-4545-94dd-61a011c9d7c4.png)

OS:

Node：16.8

浏览器 | browser：chrome

**Comment by HAjiMa666** [comment]
解决了, antd-pro默认给你hash设置为了true,但是又没默认设置 history:{type:"hash"}，导致我这个新手看了半天没看出来问题，还是问了大佬才解决的。

**Comment by chenshuai2144** [comment]
这两个有啥关系，hash:true 是打开编译文件的hash`。history:{type:"hash"}`是路由的hash，你的问题应该是你部署的的容器不支持的浏览器路由吧。
