### ISSUE TITLE
🧐[问题 |在proLayout中配置面包屑不生效]

### ISSUE THREAD

**Issue by NinthMonee** [ant-design/ant-design-pro#10668]
### 🧐 问题描述 | Problem description

新建了一个umi4 + ant design pro v5的项目，根据文档在Prolayout 中 设置ProBreadcrumb不生效。

### 💻 示例代码 | Sample code
主要代码在app 的layout的配置中：
```
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    breadcrumbRender:() => {
      return <ProBreadcrumb/>
    },
    ...initialState?.settings,
  };
};
```

### 🚑 其他信息 | Other information

文档链接：https://procomponents.ant.design/components/page-container

OS: macos 11.7.1

Node：16.15.0

浏览器 | browser：chorme 112

**Comment by AlanJava** [comment]
解决了吗
