### ISSUE TITLE
🐛 [BUG]文档链接失效

### ISSUE THREAD

**Issue by hyl1374961656** [ant-design/ant-design-pro#10661]
![image](https://user-images.githubusercontent.com/56420042/230597443-2155a75b-a5a0-43cc-9425-c3e041d1c373.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，对于文档链接失效给您带来的不便，以下是解决方案。

1. 请先确认您提供的文档链接无误，如果该文档已被删除或者被移动，则建议您尝试通过搜索引擎或者阅读相关主题的官方文档以找到更准确的文档链接。

2. 如果找到正确的文档链接，请注意阅读文档中说明的相关特性和限制条件，建议您认真考虑后再尝试使用该功能。如果您还未找到正确的文档，请介绍您所遇到的问题和您的环境，以便我们能够更好地帮助您。

React 官方文档提供了广泛的资源和示例，在此建议您多参考官方文档：https://reactjs.org/docs/getting-started.html

此外，React 的 GitHub 社区也提供了大量有用的资源，您可以在此处阅读到一些有用的内容：https://github.com/facebook/react/issues

如果您对前端开发还有其他问题，欢迎继续咨询我们，我们将尽力给您提供帮助。

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout

文档看这里
