### ISSUE TITLE
🐛 [BUG]node:internal/crypto/hash:71

### ISSUE THREAD

**Issue by Roych13** [ant-design/ant-design-pro#10662]
### 🐛 bug 描述

启动时报错：

 INFO  Starting development server...
[92%] sealing (asset processing ThemeColorReplacer)
Extracted theme color css content length: 26565
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);

### 📷 复现步骤 | Recurrence steps

先后命令如下：
**ant-design-pro@5.2.0 postinstall** 
正常

**pro create myapp**
? 🐂 使用 umi@4 还是 umi@3 ? **umi@3**
? 🚀 要全量的还是一个简单的脚手架? **simple**
正常

**cd myapp && npm install**
出现 **npm WARN deprecated @formatjs**之类的警告

**npm run start**
出错：
**Webpack █████████████████████████ building (10%) 0/2 entries 2/2 dependencies 0/2 modules 2 active
 babel-loader » src\.umi\umi.ts

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported**

### 🏞 期望结果 | Expected results

描述你原本期望看到的结果
Describe what you expected to see

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本 3 simple
- 浏览器环境 chrome
- 开发环境 [Windows 11 家庭中文版 Insider Preview]
- Nodejs 18.15.0
### 🚑 其他信息

警告信息图片
![微信截图_20230410071416](https://user-images.githubusercontent.com/39145668/230800977-5128c7b8-0773-4d9a-a102-f864bd26d9a7.png)
启动报错图片
![微信截图_20230410071447](https://user-images.githubusercontent.com/39145668/230800978-8b5c1988-7cda-4912-97a6-7f8c9dd37ea3.png)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，错误是由于node的加密模块引起的。解决方案如下：

1. 在`package.json`中的`scripts`中的相关命令前添加以下设置：
```json
"dev": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
"build": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service build"
```

2. 运行以上命令时，会设置`NODE_OPTIONS`为`--openssl-legacy-provider`，这样就能在 Git Bash 和 VSCode 等工具中正常执行构建命令了。

需要注意的是，老版本的node.js并不支持`--openssl-legacy-provider`属性值，所以如果项目中有使用老版本的同事，他们将无法执行这个设置。这时可以考虑通过其他方式解决这个问题，或者升级他们的node.js版本。
