### ISSUE TITLE
🧐[问题 | question] Error esbuildHelperChecker after npm run build? 

### ISSUE THREAD

**Issue by haccoco99999** [ant-design/ant-design-pro#10665]
### 🧐 问题描述 | Problem description

Error esbuildHelperchecker show up after webpack successfully compiled

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/37260697/230823214-461ced16-d5e5-45c9-ab28-ab835ec52d89.png)

OS:Linux 

Node：19.8.1

浏览器 | browser：

**Comment by leafgit98** [comment]
一模一样的问题...

**Comment by leafgit98** [comment]
在config.ts 文件下添加 esbuildMinifyIIFE: true 试试

**Comment by leafgit98** [comment]
在config.ts 文件下添加 esbuildMinifyIIFE: true 试试

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述，你在构建项目的过程中遇到了`Error esbuildHelperChecker`的错误。这个错误通常是由于使用esbuild压缩器和异步分包同时使用导致全局变量命名冲突所引起的。

解决这个问题的方法是在项目的配置文件（通常是`.umirc.ts`或`config/config.ts`）中，添加一个名为`esbuildMinifyIIFE`的选项，并将其值设置为`true`。这个选项的作用是修复esbuild压缩器自动引入的全局变量导致的命名冲突问题。

示例代码如下：

```ts
export default {
  // other config options...
  esbuildMinifyIIFE: true, // enable esbuildMinifyIIFE
  // other config options...
}
```

添加这个选项后，重新运行`npm run build`命令，应该就能解决`Error esbuildHelperChecker`的问题了。

希望这个解决方案能帮到你，如果还有其他问题，请随时提问。

**Comment by leafgit98** [comment]
信件已收到，我会在第一时间查看并回复~~~祝您生活愉快！
