### ISSUE TITLE
🐛 [BUG] patchClientRoutes 动态路由左侧菜单点击颜色不渲染

### ISSUE THREAD

**Issue by YuZongYangHi** [ant-design/ant-design-pro#10660]
#### 版本:
 {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.3.57",
    "@ant-design/use-emotion-css": "1.0.4",
    "@umijs/route-utils": "^2.2.2",
    "antd": "^5.2.2",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.8.2",
    "rc-util": "^5.27.2",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.4",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0"
  }

#### 代码步骤
app.tsx
```
export const patchClientRoutes = ({ routes }) => {
  routes.forEach((item, index)=>{
    if (item.id === "ant-design-pro-layout") {
      routes[index].children = []
      extraRoutes.forEach(extraRoute => {
        routes[index].children.push({
          element: <App/>,
          path: `/channel/${extraRoute.id}`,
          name: extraRoute.title,
          key: extraRoute.id,
          icon: <MessageOutlined />,
          id: extraRoute.id,
          parentId: "ant-design-pro-layout"
        })
      })
      routes[index].children.push({
        element: <Welcome/>,
        path: "/",
        hideInMenu: true,
        key: "default",
        id: "default",
        parentId: "ant-design-pro-layout"
      })
    }
  })
  console.log(routes)
};

export function render(oldRender) {
  fetchChannelList().then(res=>{
    extraRoutes = res.data
    oldRender();
  })
}
```

#### 页面效果
<img width="815" alt="image" src="https://user-images.githubusercontent.com/35584408/230304534-dc3f5e6e-bfd3-4d73-9162-29d4c402b07e.png">

#### 疑问
左侧菜单颜色不渲染
<img width="612" alt="image" src="https://user-images.githubusercontent.com/35584408/230304696-a3bd61b7-beea-4628-992e-e642b3f881bb.png">

**Comment by YuZongYangHi** [comment]
看起来跟国际化有关系？动态路由的话，如何动态实现国际化menu.xxxx?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的信息，可以尝试添加 "formatMenu": false 到额外路由的参数中，以禁用 menuRender 的路由格式化处理。下面是修改后的代码片段：

```
extraRoutes.forEach(extraRoute => {
  routes[index].children.push({
    element: <App/>,
    path: `/channel/${extraRoute.id}`,
    name: extraRoute.title,
    key: extraRoute.id,
    icon: <MessageOutlined />,
    id: extraRoute.id,
    parentId: "ant-design-pro-layout",
    formatMenu: false  // 新添加的参数
  })
})
```

另外，可能需要将左侧菜单的选中项与路由匹配，例如在 YourLayout 组件中使用 useLocation 获取当前路由，并在菜单项上使用 selectedKeys 和 defaultSelectedKeys 来指定选中菜单项。具体示例可以参考 antd 的 Layout 组件文档，链接：https://ant.design/components/layout-cn/#header

Hope it helps!

**Comment by YuZongYangHi** [comment]
解决了，感谢回复，看了一下应该跟key的定义有关系，当我将key赋值去掉后就生效了。

**Comment by KYX1234** [comment]
> 解决了，感谢回复，看了一下应该跟key的定义有关系，当我将key赋值去掉后就生效了。

请问如果使用这个动态路由，是不是不需要配置routes了，菜单也可以根据路由自动获取

**Comment by PeiRunWu** [comment]
> 解决了，感谢回复，看了一下应该跟key的定义有关系，当我将key赋值去掉后就生效了。

我有问题请教下，为什么我动态路由之后，访问成404了，component 不生效了
