### ISSUE TITLE
🐛 [BUG] V6版本下使用多标签的一些问题

### ISSUE THREAD

**Issue by CementSealing** [ant-design/ant-design-pro#10666]
### 🐛 bug 描述

1、当倒数第二个标签页的URL中带有参数，关闭最后一个标签页，自动切换到倒数第二个标签页时，URL中的参数直接没有了。

![image](https://user-images.githubusercontent.com/97492682/230835413-e4a71ff5-d3a0-42d6-9402-fbb20307ed74.png)
关闭最后一个标签页后：
![image](https://user-images.githubusercontent.com/97492682/230835474-f19d1dd5-2dc7-42a6-bf6b-f0988defcf61.png)

2、项目开启标签页功能，并打包部署之后，访问项目并点击一个菜单，然后刷新浏览器，标签页标题直接显示英文标题没有国际化，并且再次点击原菜单不会切换到此英文标题标签页，而是重新打开一个标签页。

![image](https://user-images.githubusercontent.com/97492682/230836883-5fe99272-597e-49a5-adf7-5bf67237ce62.png)

刷新之后：

![image](https://user-images.githubusercontent.com/97492682/230836806-cd3661de-0c84-4ee4-b974-1edb066d6095.png)

再次点击原菜单：

![image](https://user-images.githubusercontent.com/97492682/230837131-5b7fb8c4-5f8f-41df-8733-3fadb33fdfea.png)

### 🏞 期望结果 | Expected results

1、关闭标签页造成标签页切换时，能保存URL参数

2、刷新浏览器后能正确显示标签页

### 💻 复现代码 | Recurrence code

```
config相关配置：
{
   // 其他配置
  ...
  keepalive: [/./],
  tabsLayout: {},
  history: {
    type: 'browser'
  },
  exportStatic: {},
}
```

### © 版本信息

- Ant Design Pro 版本:  6.0.0
- umi 版本 v4.0.59
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by CementSealing** [comment]
在多标签情况下，有时候重新登录之后，表格的一些样式会错乱。
正常：
![image](https://user-images.githubusercontent.com/97492682/231679798-9ac49fd6-5b92-4411-ab95-94eae9486b72.png)


错乱：

![image](https://user-images.githubusercontent.com/97492682/231678414-671bafd6-9eaf-462c-b460-4dd509214d6b.png)

![image](https://user-images.githubusercontent.com/97492682/231679201-26fc7574-65ff-472e-9066-3a3303e3ec3c.png)

**Comment by KYX1234** [comment]
他这个插件一刷新就没有了你是怎么处理的
