### ISSUE TITLE
左侧菜单没有 icon 的时候，收起菜单，hint 会多出一个字母

### ISSUE THREAD

**Issue by bbebse2** [ant-design/ant-design-pro#10672]
![屏幕截图 2023-04-11 141309](https://user-images.githubusercontent.com/88171202/231072121-48109940-9807-49a8-bba6-f40a48d9fb6c.png)
左侧菜单没有 icon 的时候，收起菜单，hint 会多出一个字母

**Comment by bbebse2** [comment]
> ![屏幕截图 2023-04-11 141309](https://user-images.githubusercontent.com/88171202/231072121-48109940-9807-49a8-bba6-f40a48d9fb6c.png) 左侧菜单没有 icon 的时候，收起菜单，hint 会多出一个字母

把 "@ant-design/pro-components" 降级到 "2.3.34" 可以解决这个问题

**Comment by chenshuai2144** [comment]
这个是 feature  ，设计师的设计
