### ISSUE TITLE
🧐[问题 | question]顶部菜单布局时修改导航栏选中颜色colorTextMenuSelected无效

### ISSUE THREAD

**Issue by EcoIris** [ant-design/ant-design-pro#10677]
### 🧐 问题描述 | Problem description

顶部菜单布局时修改导航栏选中颜色colorTextMenuSelected无效

### 💻 示例代码 | Sample code

```
  token: {
    header: {
      heightLayoutHeader: 72,
      colorBgHeader: '#2D2E42',
      colorTextMenu: '#fff',
      colorTextMenuSecondary: '#fff',
      colorTextMenuSelected: '#fff',
      colorTextMenuActive: '#fff',
    },
    pageContainer: {
      paddingBlockPageContainerContent: 0,
      paddingInlinePageContainerContent: 0
    }
  },
```

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/38517426/231635222-cd14a94e-b9d0-424d-8d18-bf423f0ebdd8.png)
选中修改为白色但仍然是主题色

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


更新一下版本好了，这是antd 改了token。pro 没跟进完成导致的
