### ISSUE TITLE
页面性能 violation

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#1067]
页面数据量很大，输入表单，提交表单都有点卡，控制台warning
[violation] input handler took 997ms
[violation]  react-invokeguardedcallback handler took 1886ms
这一般怎么优化啊，谢谢

**Comment by chenshuai2144** [comment]
分布表单

**Comment by ddcat1115** [comment]
除了LS提到的交互优化，还可以拆分模块，尽量使用 PureComponent

**Comment by TigerBill2016** [comment]
分布表单和拆分模块如何做呢

**Comment by chenshuai2144** [comment]
可以查看我们分步表单的例子，主要思想还是把一次渲染的表单，分成多段进行渲染，
前端最主要的性能瓶颈还是 dom 操作

**Comment by TigerBill2016** [comment]
好的， 谢谢
