### ISSUE TITLE
antd pro v5 控制台警告

### ISSUE THREAD

**Issue by tKlint** [ant-design/ant-design-pro#10674]
### 🧐 问题描述 | Problem description
export 'compareVersions' (imported as 'compareVersions') was not found in '@ant-design/pro-utils' 

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据您提供的问题描述，警告信息是“export 'compareVersions' (imported as 'compareVersions') was not found in '@ant-design/pro-utils'”。这是一个废弃警告，意味着在当前版本的 antd pro 中的 @ant-design/pro-utils 包中已经移除了 compareVersions 导出。

解决方案有两种：

第一种解决方案是更换为应该使用的新 API 或函数。您可以查看 antd pro 的文档或代码库，了解关于 compareVersions 的更改和相应的替代方案。可能有一个新的函数或库可以替代这个功能。

第二种解决方案是忽略该警告。您可以使用警告过滤器（Warning Filter）来屏蔽特定的警告，使其不再在控制台中显示。您可以参考 [Warning Filter RFC](https://github.com/ant-design/ant-design/discussions/44551) 中的说明，了解如何使用警告过滤器来处理这个问题。

总体来说，为了避免类似的问题，应该在升级任何库或框架之前，仔细查阅文档和更新说明，了解可能会影响到您现有代码的更改，并相应地进行调整。在前端开发中，了解并遵循最佳实践和规范，以及良好的版本管理和更新策略，都是非常重要的。
