### ISSUE TITLE
静态路由、使用了proTable 的syncToUrl, 会程序路由在参数后面例如 /admin/?current=1&pageSize=20#/admin/order/🐛 [BUG]

### ISSUE THREAD

**Issue by ahui4367** [ant-design/ant-design-pro#10670]
### 🐛 bug 描述
1、静态路由，defineConfig 设置 {hash:true}
2、proTable 使用了syncToUrl

**结果出现 https://xxx.com/admin/?current=1&pageSize=20#/admin/order/**

3、如果这时候在某个页面的条件下搜索，搜索条件永远挂在页面URL，除非手动删除，就是切换页面路由参数也不会发生改变

点击跳转到users 页面
**结果出现 https://xxx.com/admin/?current=1&pageSize=20&title=test#/admin/users*
点击退出跳转到登录页面
**结果出现 https://xxx.com/admin/?current=1&pageSize=20&title=test#/admin/login*

### 🏞 期望结果 
改变页面路由，?current=1&pageSize=20 这段应该删除。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案如下：

1. 静态路由，可以在 Umi 的配置文件（`config/config.ts`）中使用 `defineConfig` 设置 `hash: true`，即可开启 hash 路由模式。如下所示：

```typescript
import { defineConfig } from 'umi';

export default defineConfig({
  hash: true,
});
```

2. proTable 使用了 syncToUrl，即将表格的分页、排序等状态同步到 URL 中。这样在刷新页面或者通过 URL 进入页面时，可以恢复到之前的表格状态。如果希望在跳转页面时清除这些 URL 参数，可以在页面的 `componentWillUnmount` 方法中手动清除。如下所示：

```javascript
import React, { Component } from 'react';

class SomePage extends Component {
  componentWillUnmount() {
    const { history, location } = this.props;
    const params = new URLSearchParams(location.search);
    params.delete('current');
    params.delete('pageSize');
    history.replace({ search: params.toString() });
  }

  render() {
    // 页面内容
  }
}
```

这样在跳转到其他页面时，会自动将当前页面的 `current` 和 `pageSize` 参数从 URL 中删除。

注意：上述代码是基于类组件的写法，如果你使用的是函数组件，则可以使用 `useEffect` 钩子函数来达到同样的效果。

希望以上解决方案能够帮助到你，如有疑问请随时追问。

**Comment by zhangzhengyang27** [comment]
麻烦回复的时候看看文档
<img width="664" alt="Image" src="https://github.com/user-attachments/assets/a009bb26-c702-43eb-b843-184de3fcc2d8" />
