### ISSUE TITLE
🧐[问题 | question] dev环境下应该怎样取消where选择器？

### ISSUE THREAD

**Issue by xlszzck** [ant-design/ant-design-pro#10679]
已知在app.tsx添加如下配置，可以在生产环境取消where选择器，从而兼容老版本浏览器

```
export function rootContainer(container: React.ReactElement) {
  return React.createElement(
    StyleProvider,
    {
      hashPriority: 'high',
      transformers: [legacyLogicalPropertiesTransformer],
      autoClear: true,
    },
    container,
  );
}
```

但是Ant Design文档描述的如下方式，却无法在开发环境生效

```
import React from 'react';
import { StyleProvider } from '@ant-design/cssinjs';

// `hashPriority` 默认为 `low`，配置为 `high` 后，
// 会移除 `:where` 选择器封装
export default () => (
  <StyleProvider hashPriority="high">
    <MyApp />
  </StyleProvider>
);
```

这样就导致，开发环境和生产环境不一致

OS: macOS 13.3.1

Node：v18.15.0

浏览器 | browser：chrome 112.0.5615.49

**Comment by zhibo59** [comment]
解决了么

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题的解决方案是使用 `:where` 选择器。Ant Design 默认使用 `:where` 选择器降低 CSS Selector 优先级，但在低版本浏览器中的兼容性较差。如果需要支持旧版浏览器或解决优先级冲突，可以使用 `@ant-design/cssinjs` 的 StyleProvider 组件取消默认的降权操作。

首先，安装 `@ant-design/cssinjs`：

```bash
npm install @ant-design/cssinjs --save
```

然后，在需要取消默认降权的组件中，引入 StyleProvider 并设置 `hashPriority` 属性为 "high"：

```tsx
import React from 'react';
import { StyleProvider } from '@ant-design/cssinjs';

export default () => (
  <StyleProvider hashPriority="high">
    <MyApp />
  </StyleProvider>
);
```

这样，样式将从 `:where` 切换为类选择器，例如：

```diff
--  :where(.css-bAMboO).ant-btn {
++  .css-bAMboO.ant-btn {
      color: #fff;
    }
```

需要注意的是，取消 `:where` 降权后，可能需要手动调整一些样式的优先级。你可以使用 PostCSS 插件来提升样式的优先级，例如 `postcss-scopify`、`postcss-increase-specificity` 或 `postcss-add-root-selector`。

另外，如果想在生产环境取消 `:where` 选择器，可以配置 `rootContainer` 函数如下：

```tsx
export function rootContainer(container: React.ReactElement) {
  return React.createElement(
    StyleProvider,
    {
      hashPriority: 'high',
      transformers: [legacyLogicalPropertiesTransformer],
      autoClear: true,
    },
    container,
  );
}
```

这样配置后，在生产环境下 `:where` 选择器将被取消。但需要注意的是，上述配置可能在开发环境下无效。

综上所述，你可以根据你的具体需求选择使用 `StyleProvider` 组件取消 `:where` 选择器的降权操作，并在必要时手动调整样式的优先级。
