### ISSUE TITLE
关于 antd-pro ConfigProvider 自定义样式的疑惑

### ISSUE THREAD

**Issue by xiaqingping** [ant-design/ant-design-pro#10678]
在配置自定义样式时，antd组件会修改而pro组件部分不会修改这是怎么回事

![image](https://user-images.githubusercontent.com/49116631/231676081-8e6253ea-bed5-42b5-a46a-30e3806e0a6e.png)

![image](https://user-images.githubusercontent.com/49116631/231675559-44abf9e5-34a4-47ba-968e-bc2609a8b3b4.png)

ConfigProvider是antd文档提供的，那么要修改pro的主题该怎么改呢

**Comment by qln1994** [comment]
config.js里面修改antd吧？

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你的问题描述，你遇到了ConfigProvider修改主题时的疑惑。根据描述中的截图，第二张截图中可以看到ConfigProvider组件的代码，其中传入了一个theme属性。

要修改Pro组件的主题，可以按照以下步骤进行操作：

1. 首先，确保你已经在项目中引入了Pro组件库，并且在页面中正确使用了Pro组件。

2. 在你的项目中，找到Pro组件库的配置文件，通常是一个config文件或者一个theme文件，这个文件用于配置Pro组件的主题相关内容。

3. 在这个配置文件中，找到与主题相关的配置项，通常是一个名为"theme"的属性。

4. 当你找到了这个属性后，你可以根据你的需求将其修改为你想要的主题样式。如果你不确定如何修改主题样式，你可以参考Pro组件库的官方文档，文档中通常会提供一些主题相关的示例代码。

5. 在你修改完配置文件后，保存并重新编译你的项目。

6. 重新运行你的项目，然后打开你的页面，你应该能看到Pro组件的主题已经被修改了。

总之，要修改Pro组件的主题，你需要找到Pro组件库的配置文件，修改其中的主题配置项，然后重新编译并运行你的项目。希望我的回答对你有帮助！
