### ISSUE TITLE
openapi插件生成问题

### ISSUE THREAD

**Issue by Tomfish0902** [ant-design/ant-design-pro#10687]
参考google api规范，restful自定义方法建议用:方法名的形式，例如/permissions:batchDelete，采用此种方式生成的前端api代码是`/permissions:${batchDelete}`，暂未找到如何修复这个问题的选项，请问应该如何解决？ @chenshuai2144

**Comment by chenshuai2144** [comment]
https://github.com/chenshuai2144/openapi2typescript

可以在这个仓库里面提pr
