### ISSUE TITLE
🧐[问题 | question]官网加载慢

### ISSUE THREAD

**Issue by Ricky816845** [ant-design/ant-design-pro#10686]
### 🧐 问题描述 | Problem description

 https://pro.ant.design 打开就慢, 静态资源加载都慢
附带https://procomponent.ant.design
除非正常打开过一次

浏览器 | browser：
Edge,Chrome

**Comment by Ricky816845** [comment]
补充: 用的是移动的宽带

**Comment by chenshuai2144** [comment]
网络问题，我看看能不能搞个国内镜像
