### ISSUE TITLE
使用Fragment时，eslint报错

### ISSUE THREAD

**Issue by soolx** [ant-design/ant-design-pro#1068]
使用React的Fragment时，eslint报错，不清楚是不是eslintrc默认配置的问题
```
<>
<div>Example</div>
</>
```
eslint 报错 `'Strings must use singlequote. (quotes)'`
如果这个是eslint自身还不支持的话，请忽视我，哈哈^ ^

**Comment by soolx** [comment]
只是eslint报错，运行正常无影响。
```
<React.Fragment>
<div>Example</div>
</React.Fragment>
```
完整写法都正常

**Comment by chenshuai2144** [comment]
Eslint还不支持
等下个大版本
