### ISSUE TITLE
🧐[问题 | question]. 怎么设置右侧内容区的padding为0呀

### ISSUE THREAD

**Issue by l3yx** [ant-design/ant-design-pro#10682]
![image](https://user-images.githubusercontent.com/42339081/232066751-afa1510f-acae-45e9-b6de-f924e2959bf8.png)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题：怎么设置右侧内容区的padding为0呀？

解决方案：
1. 在样式文件中找到右侧内容区的选择器，可以通过类名、标签名或者ID来选择。
2. 在选择器中添加 `padding` 属性，并将值设置为 `0` 。
3. 如果存在其他样式规则可能会覆盖 `padding` 的设置，可以使用 `!important` 来确保该样式优先生效。
4. 在应用中刷新页面，即可看到右侧内容区的 `padding` 为0的效果。

注意：在确定样式的选择器和设置值之前，可以通过浏览器的开发者工具来查看元素的样式属性，确保选择器的准确性和优先级。
