### ISSUE TITLE
🧐[问题 | question]怎么让主内容表格的标签不跟随primaryColor

### ISSUE THREAD

**Issue by jvhuaxia** [ant-design/ant-design-pro#10683]
### 🧐 问题描述 | Problem description

我现在设置了primaryColor 或者是动态调整PrimaryColor 但是内容区域的表格里面的操作等A标签的颜色也会跟随primaryColor
我不想让他跟随这个颜色 我要怎么做

![image](https://user-images.githubusercontent.com/29006793/232360557-fc2e77e7-4df7-4e71-85f2-eaf29b7f29fa.png)

OS:

Node：

浏览器 | browser：

**Comment by jvhuaxia** [comment]
整半天 没找到在哪改

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


对于这个问题，你可以通过嵌套 `ConfigProvider` 组件来实现局部主题的更换。在子主题中未被改变的 Design Token 将会继承父主题。

具体实现如下：

```jsx
import React from 'react';
import { Button, ConfigProvider } from 'antd';

function App() {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: '#1677ff',
        },
      }}
    >
      <div className="App">
        <Button type="primary">Button</Button>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#00b96b',
            },
          }}
        >
          <div className="Content">
            {/* 此处是内容区域，可以放置表格等组件 */}
            <Button type="primary">Content Button</Button>
          </div>
        </ConfigProvider>
      </div>
    </ConfigProvider>
  );
}

export default App;
```

在嵌套的 `ConfigProvider` 中，你可以根据需要设置不同的 `colorPrimary`，以实现不同的主题。这样，内容区域中的按钮将根据所在的 `ConfigProvider` 的主题进行渲染，而不会跟随主页面的 `colorPrimary`。

希望能对你有所帮助！如果还有其他问题，请随时提问。
