### ISSUE TITLE
🧐[问题 | question]ProLayout自定义headertoken失效

### ISSUE THREAD

**Issue by EcoIris** [ant-design/ant-design-pro#10692]
### 🧐 问题描述 | Problem description

当我同时在defaultSetting中配置了colorTextMenu、colorTextMenuSecondary时，只有colorTextMenu生效了，二级的menuItem未生效，是我理解错了并不可以同时指定一级和二级的颜色？

### 💻 示例代码 | Sample code

defaultSetting的配置:
```
const Settings = {
  navTheme: 'light',
  colorPrimary: '#1890ff',
  layout: 'top',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: '中予国际',
  pwa: true,
  logo: '/logo.png',
  iconfontUrl: '',
  splitMenus: false,
  token: {
    header: {
      heightLayoutHeader: 72,
      colorBgHeader: '#2D2E42',
      colorTextMenu: '#FFFFFF',//menuItem 的字体颜色
      colorTextMenuSecondary: '#2D2E42',//menu 的二级字体颜色
      colorTextMenuSelected: '#D3AB85',
      colorTextMenuActive: '#D3AB85',
    },
    pageContainer: {
      paddingBlockPageContainerContent: 0,
      paddingInlinePageContainerContent: 0,
    }
  },
};
```

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/38517426/233043088-fd61b03c-cc1a-45c7-a67a-d2e5c38db986.png)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


可以通过使用ConfigProvider来自定义ProLayout的header的颜色配置。ConfigProvider是Ant Design提供的一个全局配置组件，可以用来统一配置Ant Design组件库的一些属性。

首先，在项目的入口文件（如src/index.js）中引入ConfigProvider组件：
```javascript
import { ConfigProvider } from 'antd';

ReactDOM.render(
  <ConfigProvider>
    <App />
  </ConfigProvider>,
  document.getElementById('root')
);
```

然后，在ProLayout组件的外层包裹ConfigProvider，并通过ConfigProvider的属性来配置header的颜色：
```jsx
import { ConfigProvider } from 'antd';

const customTheme = {
  header: {
    colorTextMenu: '#FFFFFF', // menuItem 的字体颜色
    colorTextMenuSecondary: '#2D2E42', // menu 的二级字体颜色
  },
};

ReactDOM.render(
  <ConfigProvider theme={customTheme}>
    <ProLayout>
      // ProLayout的其他配置
    </ProLayout>
  </ConfigProvider>,
  document.getElementById('root')
);
```

这样就可以实现自定义ProLayout的header的颜色配置了。注意，ConfigProvider的theme属性需要传入一个对象，其中的属性名对应需要配置的属性，属性值对应的是颜色值。可以根据实际需求来自定义配置。在这个例子中，我们只配置了colorTextMenu和colorTextMenuSecondary两个属性，其他属性会使用默认值。

通过这种方式，可以方便地自定义ProLayout的header的颜色配置，而不需要修改ProLayout的源代码。同时，也可以通过ConfigProvider来自定义其他Ant Design组件的样式配置。
