### ISSUE TITLE
无法安装js版本的的 ant-design-pro🐛 [BUG]

### ISSUE THREAD

**Issue by cg020616** [ant-design/ant-design-pro#10690]
### 🐛 bug 描述
我想选择ant-design-pro的js版本到现在都是默认安装ts是把js放弃了嘛
我到网上找了比较多的文档什么的都没有发现正确的js版本安装的文档

无法选择js版本
默认安装ts

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]

**Comment by tnngo** [comment]
没什么意义，ts只是js扩展，你在ts里照样可以写js。

就算antd pro有js版，你也不大可能去改源码，所以提供js版本意义就不大了。

**Comment by chenshuai2144** [comment]
不支持了，推荐全部用 ts
