### ISSUE TITLE
ant pro v5 umi@4的多环境配置问题 🐛 [BUG]

### ISSUE THREAD

**Issue by Jiexiansen** [ant-design/ant-design-pro#10691]
### 🐛 bug 描述

按照官方文档配置多环境功能，构建/启动项目时会被其它环境的配置文件所覆盖；
[文档](https://pro.ant.design/zh-CN/docs/environment-manage#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

### 📷 复现步骤 | Recurrence steps
1. pro create demo
2. tyarn
3. 增加多环境多文件配置（config.prod.ts）
4. npm run start:prod （cross-env REACT_APP_ENV=prod UMI_ENV=prod MOCK=none max dev）
5. “config.prod.ts”中 define 所配置的环境变量会被 “config.dev.ts” 中 define 所配置环境变量覆盖

代码：
1. config.dev.ts
<img width="441" alt="image" src="https://user-images.githubusercontent.com/26481272/233035933-6bf7b921-003a-418f-a5a3-7e71b9213371.png">

2. config.prod.ts
<img width="436" alt="image" src="https://user-images.githubusercontent.com/26481272/233036043-7c670ddc-d278-463a-9938-75640204e034.png">

截图示例：
1. 构建dev环境时，会加载prod环境配置
<img width="531" alt="image" src="https://user-images.githubusercontent.com/26481272/233035137-7a2cf966-bfe4-4d4d-803f-d6a6eba41206.png">
4. 运行prod环境时，会加载dev环境配置
<img width="574" alt="image" src="https://user-images.githubusercontent.com/26481272/233035538-f87f2232-0234-4e50-94b8-e67ee43af5da.png">

### 🏞 期望结果 | Expected results
多环境多文件功能正常使用

### 💻 复现代码 | Recurrence code
[github仓库：https://github.com/Jiexiansen/ant-pro-v5-demo](https://github.com/Jiexiansen/ant-pro-v5-demo)

### © 版本信息

- Ant Design Pro 版本: [6.0.0] ?
- umi 版本 [4.0.52]
- 浏览器环境 [chrome]
- 开发环境 [mac OS]

**Comment by peterleng** [comment]
+1

**Comment by funs-scaler** [comment]
+1

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据您提供的信息，问题出在多环境配置文件被覆盖的地方。解决方案是正确配置 `UMI_ENV` 环境变量。

首先，您需要在 `package.json` 文件的 `scripts` 部分添加不同环境的配置命令，示例如下：

```json
{
  "scripts": {
    "start": "cross-env REACT_APP_ENV=dev UMI_ENV=dev umi dev",
    "build": "cross-env REACT_APP_ENV=dev UMI_ENV=dev umi build",
    "start:prod": "cross-env REACT_APP_ENV=prod UMI_ENV=prod umi dev",
    "build:prod": "cross-env REACT_APP_ENV=prod UMI_ENV=prod umi build"
  }
}
```

然后，在项目的 `config` 文件夹下创建不同环境的配置文件，例如 `config.dev.ts` 和 `config.prod.ts`，分别对应开发环境和生产环境的配置。

示例代码如下：

```typescript
// config/config.dev.ts
import { defineConfig } from 'umi';

export default defineConfig({
  define: {
    API_URL: 'http://dev.api.example.com',
    // 其他开发环境变量
  },
});

// config/config.prod.ts
import { defineConfig } from 'umi';

export default defineConfig({
  define: {
    API_URL: 'http://prod.api.example.com',
    // 其他生产环境变量
  },
});
```

这样，在开发环境启动时使用 `npm run start`，在生产环境构建时使用 `npm run build:prod`，对应的配置文件就会被正确加载。

**Comment by Jiexiansen** [comment]
> > 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
> > 删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令
> 
> 根据您提供的信息，问题出在多环境配置文件被覆盖的地方。解决方案是正确配置 `UMI_ENV` 环境变量。
> 
> 首先，您需要在 `package.json` 文件的 `scripts` 部分添加不同环境的配置命令，示例如下：
> 
> ```json
> {
>   "scripts": {
>     "start": "cross-env REACT_APP_ENV=dev UMI_ENV=dev umi dev",
>     "build": "cross-env REACT_APP_ENV=dev UMI_ENV=dev umi build",
>     "start:prod": "cross-env REACT_APP_ENV=prod UMI_ENV=prod umi dev",
>     "build:prod": "cross-env REACT_APP_ENV=prod UMI_ENV=prod umi build"
>   }
> }
> ```
> 
> 然后，在项目的 `config` 文件夹下创建不同环境的配置文件，例如 `config.dev.ts` 和 `config.prod.ts`，分别对应开发环境和生产环境的配置。
> 
> 示例代码如下：
> 
> ```ts
> // config/config.dev.ts
> import { defineConfig } from 'umi';
> 
> export default defineConfig({
>   define: {
>     API_URL: 'http://dev.api.example.com',
>     // 其他开发环境变量
>   },
> });
> 
> // config/config.prod.ts
> import { defineConfig } from 'umi';
> 
> export default defineConfig({
>   define: {
>     API_URL: 'http://prod.api.example.com',
>     // 其他生产环境变量
>   },
> });
> ```
> 
> 这样，在开发环境启动时使用 `npm run start`，在生产环境构建时使用 `npm run build:prod`，对应的配置文件就会被正确加载。

我的写法跟您的一样，但还是不生效呢

**Comment by xllily** [comment]
本地 `dev` 服务，加载 `config.${UMI_ENV}.ts` 没问题，但是当你执行 build 打包 dist 的时候，其实需要`config/config.prod.${UMI_ENV}.ts` 才能"覆盖" 你的 `config.prod.ts` ,  如：`config/config.prod.test.ts`
