### ISSUE TITLE
🧐[问题 | question]看上去似乎不会再有v6正式版了？

### ISSUE THREAD

**Issue by tnngo** [ant-design/ant-design-pro#10693]
浏览了一些antd-design其他开源项目，看上去antd pro 好像没有解决好antd样式框架的融合。

我忘了是在哪个issus中浏览到问题好像出在了umi那边，也一直没解决。

而未使用umi的antd和procomponents，甚至其他未基于umi的库都在不停的更新版本。

要不antd内部讨论一下最佳实践pro，不再基于umi会不会更好点？🧐

**Comment by duwei54** [comment]
pro的微信群都解散了。

**Comment by RainingNight** [comment]
凉了？

**Comment by kala888** [comment]
凉了？

**Comment by lovewinders** [comment]
我觉得是不是该抛弃umi呢

**Comment by mindsfsdfwe** [comment]
这个工程后面还会继续维护吗？ 以及后期的版本计划，麻烦告知一下 ，因为正在做选型，感谢

**Comment by AburronKing** [comment]
2022年就停止了
