### ISSUE TITLE
🐛 [BUG]生成umi@4版本的项目好多引入的组件报错

### ISSUE THREAD

**Issue by Pentium286** [ant-design/ant-design-pro#10696]
### 🐛 bug 描述

<img width="948" alt="image" src="https://user-images.githubusercontent.com/1262247/233299375-d5a9253c-165e-46c3-99a7-49d483c8f97b.png">

生成的项目第三方引入的组件都报错

### 📷 复现步骤 | Recurrence steps

```
pro create myapp

选择了 ❯ umi@4
```

生成项目以后打开页面提示报错

### 🏞 期望结果 | Expected results

不报错

### 💻 复现代码 | Recurrence code

"dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.3.57",
    "@ant-design/use-emotion-css": "1.0.4",
    "@umijs/route-utils": "^2.2.2",
    "antd": "^5.2.2",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.8.2",
    "rc-util": "^5.27.2",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.4",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.5",
    "@testing-library/react": "^13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.17",
    "@types/history": "^4.7.11",
    "@types/jest": "^29.4.0",
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@types/react-helmet": "^6.1.6",
    "@umijs/fabric": "^2.14.1",
    "@umijs/lint": "^4.0.52",
    "@umijs/max": "^4.0.52",
    "cross-env": "^7.0.3",
    "eslint": "^8.34.0",
    "express": "^4.18.2",
    "gh-pages": "^3.2.3",
    "husky": "^7.0.4",
    "jest": "^29.4.3",
    "jest-environment-jsdom": "^29.4.3",
    "lint-staged": "^10.5.4",
    "mockjs": "^1.1.0",
    "prettier": "^2.8.4",
    "swagger-ui-dist": "^4.15.5",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5",
    "umi-presets-pro": "^2.0.2"
  },

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by tnngo** [comment]
重装电脑

**Comment by RogerPeng123** [comment]
我也是同样的问题，vscode在Mac上就会出现这个飘红，但是在win上就不会，搞不懂为什么，vscode的配置都是用的一样的

**Comment by RogerPeng123** [comment]
> ### 🐛 bug 描述
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/1262247/233299375-d5a9253c-165e-46c3-99a7-49d483c8f97b.png">
> 
> 生成的项目第三方引入的组件都报错
> 
> ### 📷 复现步骤 | Recurrence steps
> ```
> pro create myapp
> 
> 选择了 ❯ umi@4
> ```
> 
> 生成项目以后打开页面提示报错
> 
> ### 🏞 期望结果 | Expected results
> 不报错
> 
> ### 💻 复现代码 | Recurrence code
> "dependencies": { "@ant-design/icons": "^4.8.0", "@ant-design/pro-components": "^2.3.57", "@ant-design/use-emotion-css": "1.0.4", "@umijs/route-utils": "^2.2.2", "antd": "^5.2.2", "classnames": "^2.3.2", "lodash": "^4.17.21", "moment": "^2.29.4", "omit.js": "^2.0.2", "rc-menu": "^9.8.2", "rc-util": "^5.27.2", "react": "^18.2.0", "react-dev-inspector": "^1.8.4", "react-dom": "^18.2.0", "react-helmet-async": "^1.3.0" }, "devDependencies": { "@ant-design/pro-cli": "^2.1.5", "@testing-library/react": "^13.4.0", "@types/classnames": "^2.3.1", "@types/express": "^4.17.17", "@types/history": "^4.7.11", "@types/jest": "^29.4.0", "@types/lodash": "^4.14.191", "@types/react": "^18.0.28", "@types/react-dom": "^18.0.11", "@types/react-helmet": "^6.1.6", "@umijs/fabric": "^2.14.1", "@umijs/lint": "^4.0.52", "@umijs/max": "^4.0.52", "cross-env": "^7.0.3", "eslint": "^8.34.0", "express": "^4.18.2", "gh-pages": "^3.2.3", "husky": "^7.0.4", "jest": "^29.4.3", "jest-environment-jsdom": "^29.4.3", "lint-staged": "^10.5.4", "mockjs": "^1.1.0", "prettier": "^2.8.4", "swagger-ui-dist": "^4.15.5", "ts-node": "^10.9.1", "typescript": "^4.9.5", "umi-presets-pro": "^2.0.2" },
> 
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 4.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]
> 
> ### 🚑 其他信息

我在另一个地方找到了解决方案，大意是ts的版本问题
https://github.com/ant-design/pro-components/issues/6592#issuecomment-1501356548
