### ISSUE TITLE
🐛 [BUG]ProLayout Menu 渲染多一个字

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design-pro#10698]
### 📷 复现步骤 | Recurrence steps
https://procomponents.ant.design/components/layout?tab=api
你的demo上也出现，当你菜单是没有子菜单时没有ｉｃｏｎ时，菜单渲染多一个字

### 🏞 期望结果 | Expected results
没有子菜单时没有ｉｃｏｎ时 name不会多出一个字

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.24.3]
- umi 版本 ４
- 浏览器环境 chrome
- 开发环境 [window]

**Comment by bbebse2** [comment]
同样的问题: https://github.com/ant-design/ant-design-pro/issues/10672
把 "@ant-design/pro-components" 降级到 "2.3.34" 可以解决这个问题

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据描述的问题，你遇到了一个在ProLayout Menu中的一个bug，当菜单没有子菜单且没有图标时，会多渲染一个字。根据你提供的信息，通过更新依赖来解决这个问题。

解决方案是将Ant Design Pro的版本更新到5.0.3版本。在5.0.3版本中修复了Spin包裹模式的样式偏移问题，并且修复了Menu溢出时下拉菜单的样式问题。这应该可以解决你遇到的菜单渲染多一个字的问题。

你需要将Ant Design Pro的版本更新到5.0.3版本，然后重新运行你的应用程序，这个问题应该就会被解决了。

更新依赖的步骤如下：
1. 打开你的项目的package.json文件。
2. 找到"dependencies"部分，找到"ant-design/pro-layout"的依赖。
3. 修改"ant-design/pro-layout"的版本号为5.0.3。
4. 保存package.json文件。
5. 在项目根目录下运行命令`npm install`或者`yarn install`来安装更新后的依赖。

更新完依赖后，重新运行你的应用程序，这个BUG应该就被解决了。如果还有其他问题，请提供更多的详细信息以便我们进一步解决。
