### ISSUE TITLE
🐛 [BUG] 任意组件使用message时报warning: [antd: message]

### ISSUE THREAD

**Issue by lgcgo** [ant-design/ant-design-pro#10695]
### 🐛 bug 描述
任意组件使用message时报 以下提示
warning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

### 📷 复现步骤 | Recurrence steps
项目中任意组件，使用message.success('successfully');

### 🏞 期望结果 | Expected results
期待控制台无warning

### 💻 复现代码 | Recurrence code
`message.success('successfully');`

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本 umi@4 
- 浏览器环境 Google Chrome
- 开发环境 windows11

**Comment by WuJiY** [comment]
+1

**Comment by derrickxiang** [comment]
+1

**Comment by haobarry** [comment]
+11

**Comment by RogerPeng123** [comment]
+1

**Comment by lgcgo** [comment]
> +1 是不是应该到umi里问一问

我看了message是从antd包导出的，当前message组件打开时默认body写入导致报错，而JointContent应该是antd的事情应该没有提错吧

**Comment by QinZhen001** [comment]
+1

**Comment by doveq** [comment]
请问有解决方法了吗？

**Comment by lgcgo** [comment]
> 请问有解决方法了吗？
解决了，其实官方文档是给出了解决示例：https://ant-design.gitee.io/components/app-cn

**Comment by lgcgo** [comment]
解决示例：https://ant-design.gitee.io/components/app-cn

**Comment by lgcgo** [comment]
解决示例：https://ant-design.gitee.io/components/app-cn

**Comment by keepxs** [comment]
const [modal, contextHolder] = Modal.useModal(); 我使用的是这个方法

**Comment by 1275727217** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/38625419/61db4ea6-de44-4c15-8c3d-fbcfa79f2f6b)
6.0.0版本 我已经按照官方文档处理了  但是还是会出现这个错误

**Comment by omissyouyou** [comment]
> const [modal, contextHolder] = Modal.useModal(); 我使用的是这个方法

Argument type {okType: string, cancelText: string, centered: boolean, icon: JSX.Element, title: string, okText: string, content: string, onOk(): void} is not assignable to parameter type string | undefined  我也用了这个方法我的ide里会报这个

**Comment by qdxinrui** [comment]
我用的message.open({
      content: 'Loading',
      duration: 0,
      type: 'loading',
    }) ，暂时不报这个警告了
