### ISSUE TITLE
升级最新版后 ~antd/es/style/themes/index  找不到了

### ISSUE THREAD

**Issue by OnceCrazyer** [ant-design/ant-design-pro#10694]
如题，之前写的样式，再升级后，由于~antd/es/style/themes/index  不知道在哪引入，导致样式变了，求助，最新版对应的文件路径是什么

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


在最新版的antd中，样式定制的方式有所不同。最新版的antd采用了CSS-in-JS的方式来定制主题。

具体的定制方式请参考官方文档：https://ant.design/docs/react/customize-theme-cn

在新版的antd中，你需要通过引入`@import`语法来引入样式文件，而不再使用`~antd/es/style/themes/index`这种方式。

你可以通过以下步骤来解决问题：

1. 确保你已经升级到最新版的antd，并且已经按照官方文档的要求进行了相应的改动。

2. 确认你的样式文件的引入是否正确。在最新版的antd中，你需要在你的样式文件中使用`@import`语法来引入antd的样式文件。例如：

   ```css
   @import '~antd/dist/antd.css';
   ```

   如果你的样式文件是通过less或者sass等预处理器来编写的，你需要确保预处理器能够正确解析`@import`语法。

3. 重新编译你的代码，查看样式是否已经生效。

希望以上解决方案能够帮到你。如果还有其他问题，请随时提问。
