### ISSUE TITLE
openapi插件生成的方法重名如何解决？

### ISSUE THREAD

**Issue by Tomfish0902** [ant-design/ant-design-pro#10700]
后端是java，不同的controller里包含相同的方法名，插件生成的时候会按照methodName,methodName1生成前端方法名，请问大家是怎么解决的？

**Comment by yuyihan666** [comment]
opeanapi规范里面有个operationId 可以自己命名 @Operation(operationId = "xxxSave")

**Comment by chenshuai2144** [comment]
服务端不要老是瞎写名字，我们这边的后端也是。
项目里有 100 多个 getList
