### ISSUE TITLE
类似这样的动态表单怎么处理

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#1070]
![image](https://user-images.githubusercontent.com/183884/37238119-7ada0d9e-245a-11e8-87b6-24264447feb2.png)
点击添加基本信息 可以动态添加 日期和上传资料，像这样保存字段，有什么思路？

**Comment by chenshuai2144** [comment]
https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item

**Comment by WuJiY** [comment]
![image](https://user-images.githubusercontent.com/183884/37288050-3f61c0e8-2641-11e8-8636-d3075bff2ec9.png)

上面这种一层的动态添加按照官网的搞定了，现在这种嵌套的应该是怎么解决？
