### ISSUE TITLE
动态赋值Title 后  丢失🐛 [BUG]

### ISSUE THREAD

**Issue by hyzx86** [ant-design/ant-design-pro#10709]
### 🐛 bug 描述
之前提在umijs 里了 ，结果貌似是 procomponents 的问题，但是调用入口在这里

https://github.com/umijs/umi/issues/11022#event-9113921620

### 📷 复现步骤 | Recurrence steps

```ts
async function getSettings(): Promise<Partial<LayoutSettings>> {
  return {
    ...defaultSettings,
    title: '张三李四王麻子',
  }  as Partial<LayoutSettings>;
}

/**
 * @see  https://umijs.org/zh-CN/plugins/plugin-initial-state
 * */
export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  loading?: boolean;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    try {
      const msg = await queryCurrentUser({
        skipErrorHandler: true,
      });
      return msg.data;
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };
  // 如果不是登录页面，执行
  const { location } = history;
  if (location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: await getSettings(),
    };
  }
  return {
    fetchUserInfo,
    settings: await getSettings(),
  };
}
```

### 🏞 期望结果 | Expected results

Title 不应该被删除

### 💻 复现代码 | Recurrence code

https://github.com/ant-design/ant-design-pro/compare/master...hyzx86:ant-design-pro:titleLost
### © 版本信息

- Ant Design Pro 版本: latest

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据代码和问题描述，问题是在使用ProLayout组件时，动态赋值的title属性丢失了。解决方案如下：

1. 确保在ProLayout组件的props中正确传递title属性。例如：
```tsx
<ProLayout title={title} ... />
```

2. 确保getSettings函数正确返回title属性的值。可以通过在getSettings函数中加入console.log来调试。例如：
```ts
async function getSettings(): Promise<Partial<LayoutSettings>> {
  const settings = {
    ...defaultSettings,
    title: '张三李四王麻子',
  } as Partial<LayoutSettings>;
  console.log(settings.title); // 检查title的值
  return settings;
}
```

3. 如果可以确定上述两个步骤没有问题，那么可能是ProLayout组件存在其他问题或者版本兼容性问题。可以检查ProLayout组件的文档和GitHub仓库，查看是否有已知的bug或解决方案。

总结：动态赋值Title丢失的问题可能是由于ProLayout组件的使用不正确或存在其他问题导致的。可以通过检查传递给ProLayout组件的props和确认getSettings函数的返回值来解决问题。如果仍然无法解决，可以检查ProLayout组件的文档和GitHub仓库，或者提问者提到的相关issue来寻找解决方案。

**Comment by hyzx86** [comment]
@chenshuai2144 
这里把 title 清了：https://github.com/ant-design/pro-components/blob/b141035a6c7bd6cf83561b5d32f8e078a1f5675d/packages/layout/src/components/SettingDrawer/index.tsx#L130

**Comment by hyzx86** [comment]
发错了。。。忽略
