### ISSUE TITLE
萌新很迷；按照官方给的步骤一步一步来。为哈左边空白呢🐛 [BUG]

### ISSUE THREAD

**Issue by Fluox-Etine** [ant-design/ant-design-pro#10710]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/64512602/234877852-b0535aff-2ce5-4f58-88a7-a6f6f10d2a4d.png)
为啥那边有空白呢

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wppeng520** [comment]
我的也是，之前的项目重新yarn后左边变得和你这一样了
![38ce1aefed839e7f6a6af1bd4956b85](https://user-images.githubusercontent.com/70751511/234903670-8d068c10-d244-4d5c-a662-6c3853e4c9d3.png)

**Comment by lingting** [comment]
package.json里面的所有 ^ 换成 ~ 应该就解决了. 参考 https://github.com/ballcat-projects/ballcat-ui-react/commit/b9c4d6800c049bdb0328062c9f7bb041a923d5a2

**Comment by Fluox-Etine** [comment]
> package.json里面的所有 ^ 换成 ~ 应该就解决了. 参考 [ballcat-projects/ballcat-ui-react@b9c4d68](https://github.com/ballcat-projects/ballcat-ui-react/commit/b9c4d6800c049bdb0328062c9f7bb041a923d5a2)
升级下包就可以解决了
 yarn upgrade --latest
