### ISSUE TITLE
🧐想问一下版本在6.0的beta1就一直没有更新的情况

### ISSUE THREAD

**Issue by netSharks** [ant-design/ant-design-pro#10718]
### 🧐 问题描述 | Problem description

<img width="238" alt="image" src="https://user-images.githubusercontent.com/22738221/236415968-e84c2fc6-3ef5-487b-a913-bf71aca166b7.png">

### 💻 示例代码 | Sample code
无

### 🚑 其他信息 | Other information
想问一下版本在6.0的beta1就一直没有更新，是有什么阻碍了吗，还是后续有什么新的计划吗？

**Comment by zhangwudi886** [comment]
unkonwn

**Comment by RainingNight** [comment]
摆烂

**Comment by chenshuai2144** [comment]
脚手架没什么维护力度了，多看看 umi 和  nextjs
