### ISSUE TITLE
🐛 [BUG]yarn后左侧多了空白

### ISSUE THREAD

**Issue by wppeng520** [ant-design/ant-design-pro#10711]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![38ce1aefed839e7f6a6af1bd4956b85](https://user-images.githubusercontent.com/70751511/234905553-73718c25-c2cd-41b5-82e7-6d0f05b9a231.png)

**Comment by Pentium286** [comment]
我也遇到了，umi@4生成的项目会这样，umi@3不会

**Comment by z1811021** [comment]
same， 我也是一样的

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，我们可以看出这是一个前端组件的问题，左侧多出了空白。为了解决这个问题，我们可以按照以下步骤进行：

1. 查看代码，确认左侧空白的具体原因。可能是布局问题、样式问题或组件引用问题。
2. 修改代码，尝试去除多余的空白。可以通过调整布局、修改样式或调整组件引用方式来解决。
3. 在修改代码之前，先备份现有代码，以防止出现更严重的问题。
4. 如果修改代码后仍然无法解决问题，可以尝试重启项目、清除缓存或重新安装依赖项，以确保问题不是由这些原因引起的。
5. 如果以上步骤仍然无法解决问题，可以尝试寻求帮助。可以在相关的技术论坛、社区或开发者群体中提问，寻求其他开发者的帮助和意见。

此外，根据提供的信息，还可以额外注意以下几点：
- 版本信息：确认使用的 Ant Design Pro 版本和 umi 版本是否是最新版本，如果不是，可以尝试升级到最新版本。
- 浏览器环境：确认问题是否仅在特定的浏览器中出现，如果是，可以尝试在其他浏览器中验证问题。
- 开发环境：确认问题是否仅在特定的操作系统中出现，如果是，可以尝试在其他操作系统中验证问题。

总之，通过分析代码、尝试修改和寻求帮助，应该能够解决该问题。
