### ISSUE TITLE
🧐[问题 | question] 最新版的菜单选中如何修改背景色  啊

### ISSUE THREAD

**Issue by Fluox-Etine** [ant-design/ant-design-pro#10713]
### 🧐 问题描述 | Problem description
![image](https://user-images.githubusercontent.com/64512602/235423922-c3f0e961-8cc9-4060-93b0-2e34c124fe25.png)

我看到社区叫我该成 默认设置 
![image](https://user-images.githubusercontent.com/64512602/235424037-12363316-5055-4bf0-8d90-77a7f13f61cf.png)

### 🚑 其他信息 | Other information

"version": "6.0.0",

OS: Ubunut

Node：16

浏览器 | browser： 版本 112.0.5615.49（正式版本） （64 位）

**Comment by echoyl** [comment]
配置里面的token
token: {
    // 参见ts声明，demo 见文档，通过token 修改样式
    //https://procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F
  }
菜单选中背景色
token:{
   silder:{
      colorBgMenuItemSelected: 'rgba(186,224,255,0.45)'
   }
}

**Comment by Fluox-Etine** [comment]
> token:{
> silder:{
> colorBgMenuItemSelected: 'rgba(186,224,255,0.45)'
> }
> }

大佬；好像不起作用样

**Comment by oracle-fusion-middleware-team** [comment]
打错字了：silder -> sider

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你的问题描述，你想要修改菜单选中时的背景色。解决方案如下：

1. 确认菜单组件的版本号：你提供的信息中显示菜单组件的版本号为6.0.0，确保你使用的是最新版本的菜单组件。你可以通过检查官方文档或者查看菜单组件的Github仓库来确认最新版本。

2. 使用正确的选择器：在CSS中，使用正确的选择器来选择菜单选中时的DOM元素。根据你提供的截图，菜单选中时的DOM元素可能是一个`li`元素，或者它的父元素。你可以通过查看菜单组件的源码或者使用开发者工具来确认正确的选择器。

3. 修改背景色：一旦你确定了正确的选择器，你可以使用CSS来修改背景色。你可以在全局CSS文件中或者菜单组件的样式文件中添加以下代码来修改背景色：

```css
/* 全局CSS文件 */
.selected {
  background-color: #ff0000; /* 修改为你想要的背景色 */
}

/* 菜单组件的样式文件 */
.your-menu-class .selected {
  background-color: #ff0000; /* 修改为你想要的背景色 */
}
```

在上述代码中，`.selected`是你选择的DOM元素的类名，`#ff0000`是你想要的背景色。你可以将它们替换为适合你的实际需求的值。

请注意，在修改菜单选中时的背景色之前，确保你已经理解了菜单组件的API和样式定制方法，并且遵循了前端工程化的开发流程。另外，如果你使用的是React框架，可以考虑使用Ant Design的组件库，比如Menu组件，以获得更好的开发体验和效果。
