### ISSUE TITLE
🐛 [BUG]layout-side 布局左侧头像拉出的菜单浮动异常

### ISSUE THREAD

**Issue by lgcgo** [ant-design/ant-design-pro#10715]
### 🐛 bug 描述
当右侧内容超过浏览器显示高度，点击头像拉出了的菜单，并没有相对头像位置固定
![image](https://user-images.githubusercontent.com/42335782/235694765-2730debc-6250-4917-b8c2-032ea606ca71.png)

![image](https://user-images.githubusercontent.com/42335782/235694957-a45f86cf-811b-433f-9070-9e7bfab03f66.png)

### 📷 复现步骤 | Recurrence steps

layout:side

### 🏞 期望结果 | Expected results
拉出的菜单相对头像位置固定，即使右侧内容在滚动

### 💻 复现代码 | Recurrence code
无

### © 版本信息

- Ant Design Pro 版本: version 6.0.0
- umi 版本 4.0
- 浏览器环境 Google Chrome
- 开发环境 Window11 nodejs 18.14

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


这个问题的解决方案是在layout-side组件中设置菜单栏的定位方式为"fixed"，这样菜单栏会相对于头像位置固定，即使右侧内容滚动也不会改变菜单栏的位置。具体操作如下：

1. 打开layout-side的代码文件，找到菜单组件所在的位置。
2. 在菜单组件的样式中添加以下属性：

```css
position: fixed;
```

3. 保存文件并重新编译运行项目，查看效果。

这样，当点击头像拉出菜单时，菜单栏会相对于头像位置固定，并且不会随着右侧内容的滚动而改变位置。
