### ISSUE TITLE
🧐[问题 | question]/user/login的用户和密码是多少？

### ISSUE THREAD

**Issue by zsdili** [ant-design/ant-design-pro#10716]
### 🚑 其他信息 | Other information

OS:win11

Node：16.20.0

浏览器 | browser：chrome

**Comment by zsdili** [comment]
我试了一下在本地机器上，用yarn start，可以正常登录
但配置ngnix来访问，不能登录，请问这要如何登录？

**Comment by Alicehhhmm** [comment]
![image](https://user-images.githubusercontent.com/86783773/236132036-0592c9aa-6de2-450b-8bf2-0121283aff4a.png)
版本号："version": "6.0.0" 
Node：16.14.0
浏览器 ：chrome
问题：在登录页输入账号密码后404
尝试方法：在config/proxy.ts 配置中注释掉：// dev：{ ... } 没有解决问题

**Comment by Mask-MJ** [comment]
> ![image](https://user-images.githubusercontent.com/86783773/236132036-0592c9aa-6de2-450b-8bf2-0121283aff4a.png) 版本号："version": "6.0.0" Node：16.14.0 浏览器 ：chrome 问题：在登录页输入账号密码后404 尝试方法：在config/proxy.ts 配置中注释掉：// dev：{ ... } 没有解决问题

把/config/proxy.ts 中的 test 改为 dev 就可以了

**Comment by zsdili** [comment]
> 

还是没搞掂。

**Comment by zsdili** [comment]
![IMG_7821](https://user-images.githubusercontent.com/112945270/236684299-19e95146-af42-420e-9aaf-85a822b26380.png)
请各位前辈指点一下，谢谢

**Comment by creampnx-x** [comment]
解决办法：使用 `yarn start` 开启mock

**Comment by Alicehhhmm** [comment]
【已解决】这样确实可以
```js
  dev: {
    // localhost:8000/api/** -> https://preview.pro.ant.design/api/**
    '/api/': {
      target: 'https://proapi.azurewebsites.net',
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
  },
```

> > ![image](https://user-images.githubusercontent.com/86783773/236132036-0592c9aa-6de2-450b-8bf2-0121283aff4a.png) 版本号："version": "6.0.0" Node：16.14.0 浏览器 ：chrome 问题：在登录页输入账号密码后404 尝试方法：在config/proxy.ts 配置中注释掉：// dev：{ ... } 没有解决问题
> 
> 把/config/proxy.ts 中的 test 改为 dev 就可以了

**Comment by chenshuai2144** [comment]
登录失败能看到了

**Comment by 1029800858** [comment]
之前yarn run dev登录不上，改成yarn start 登录，亲测有效！
