### ISSUE TITLE
<IntlProvider> needs to exist in the component ancestry.🧐[问题 | question]

### ISSUE THREAD

**Issue by ciel0506** [ant-design/ant-design-pro#10719]
### 🧐 问题描述 | Problem description
写jest单元测试，会卡在国际化的useIntl,有大神知道怎么处理或者mock掉吗？

### 🚑 其他信息 | Other information

![图片](https://user-images.githubusercontent.com/132726714/236595511-b17228b3-cbc2-4fc3-9806-0c96bd84e696.png)

OS:

Node：

浏览器 | browser：无

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


- 首先，你可以尝试使用 `ConfigProvider` 组件来包裹你的应用，以切换语言。在 `ConfigProvider` 组件中，可以设置 `locale` 属性为 `zh_CN`，即中文语言包。示例代码如下：

```jsx
import { ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';

ReactDOM.render(
  <ConfigProvider locale={zhCN}>
    <App />
  </ConfigProvider>,
  document.getElementById('root')
);
```

- 如果上述方法仍未生效，你还可以尝试手动配置 `dayjs` 的语言设置。`antd` 使用了 `dayjs` 作为日期组件的底层库。你可以在应用入口文件中添加以下代码来设置中文语言包：

```jsx
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';

dayjs.locale('zh-cn');
```

确保你使用的 `dayjs` 版本和 `antd` 依赖的 `dayjs` 版本一致。这样你的日期组件应该能够正确显示中文日期了。

希望以上解决方案能帮到你。如果还有其他问题，请随时提问。
