### ISSUE TITLE
🐛 [BUG]生成umi@4的项目左侧菜单错位了

### ISSUE THREAD

**Issue by Pentium286** [ant-design/ant-design-pro#10712]
### 🐛 bug 描述

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1262247/235042760-16533108-935d-4f00-8244-df6677a81025.png">

> pro create myapp 

生成的项目左侧菜单错位了

### 📷 复现步骤 | Recurrence steps

```
pro create myapp

选择umi@4

npm run start
```

### 🏞 期望结果 | Expected results

菜单不错位，和umi@3生成的项目一样

### 💻 复现代码 | Recurrence code

```
pro create myapp

选择umi@4

npm run start
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 4.0.52
- 浏览器环境 112.0.5615.137
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1262247/235042760-16533108-935d-4f00-8244-df6677a81025.png">

**Comment by Sallyfafafa** [comment]
我也遇到了，我重新用 yarn install 了一下，然后就好了

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，问题是使用umi 4生成的项目左侧菜单错位了。解决方案如下：

1. 首先，确保你的依赖是最新的。可以运行`npm outdated`命令来检查你的依赖是否有更新。

2. 如果有依赖项需要更新，请运行`npm update`命令来更新它们。

3. 确保你的`umi`和`antd`的版本兼容。可以查看`package.json`文件中的依赖项版本，确保它们兼容。

4. 如果你的项目是基于`Ant Design Pro`创建的，可以尝试升级`Ant Design Pro`的版本。在`package.json`文件中，找到`@ant-design/pro-layout`的版本号，并尝试将其更新为最新版本。

5. 检查你的项目代码中是否有自定义样式或布局导致菜单错位。尤其是检查和菜单相关的样式和布局文件，查看是否有任何不一致的地方。

6. 如果问题仍然存在，可以尝试另外一个解决方案，即使用旧版本的umi。可以通过运行以下命令来创建一个使用umi@3的项目：
   ```
   npx create-umi@1 myapp
   ```

   然后运行`npm install`和`npm run start`来启动项目，查看菜单是否仍然错
