### ISSUE TITLE
🧐[问题 | question] 动态生成菜单，component 丢失了访问404

### ISSUE THREAD

**Issue by PeiRunWu** [ant-design/ant-design-pro#10714]
### 🧐 问题描述 | Problem description

 使用 动态生成菜单，菜单动态生成了，但是 component 丢失了，访问404

<img width="732" alt="image" src="https://user-images.githubusercontent.com/42695882/235658970-d31caab2-6402-4ea6-9af3-21442dd4c813.png">

`export async function getInitialState(): Promise<{
  currentUser?: SysUserType.CurrentUser;
  settings?: Partial<LayoutSettings>;
  fetchUserMenus?: () => Promise<ExtendedMenuDataItem[] | undefined>;
  menuData?: ExtendedMenuDataItem[];
  fetchUserInfo?: () => Promise<SysUserType.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    try {
      const response = await queryCurrentUser();
      return response.data;
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };

  const fetchUserMenus = async () => {
    try {
      const response = await queryCurrentUserMenus();
      return loopMenuItem(response.data || []);
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };

 
  const { location } = history;
  if (location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    const currentUserMenus = await fetchUserMenus();
    return {
      menuData: currentUserMenus,
      fetchUserInfo,
      currentUser,
      settings: defaultSettings as Partial<LayoutSettings>,
    };
  }

  return {
    menuData: [],
    fetchUserMenus,
    fetchUserInfo,
    settings: defaultSettings as Partial<LayoutSettings>,
  };
}
`

`export const layout: RunTimeLayoutConfig = ({
  initialState,
  setInitialState,
}) => {
  return {
    menu: {
      locale: false,
    },
    
    avatarProps: {
      src: initialState?.currentUser?.headUrl,
      title: initialState?.currentUser?.username,
      render: (_: any, avatarChildren: any) => {
        return <AvatarDropdown>{avatarChildren}</AvatarDropdown>;
      },
    },
    postMenuData: () => {
      return initialState?.menuData || [];
    },

    onPageChange: () => {
      const { location } = history;

      if (!initialState?.currentUser && location.pathname !== loginPath) {
        history.push(loginPath);
      }
    },

  
    actionsRender: () => [
      <GithubAction key="github" />,
      <GitlabFilled key="gitlabFilled" />,
      <Wechat key="wechatFilled" />,
      <AlipayCircleFilled key="alipayCircleFilled" />,
    ],

   
    footerRender: () => <Footer />,
   
    childrenRender: (children) => {
      return (
        <>
          {children}
          <SettingDrawer
            disableUrlParams
            enableDarkTheme
            settings={initialState?.settings}
            onSettingChange={(settings: Partial<LayoutSettings>) => {
              setInitialState((preInitialState) => ({
                ...preInitialState,
                settings,
              }));
            }}
          />
        </>
      );
    },
    ...initialState?.settings,
  };
};`  

我已经能动态生成菜单了，但是访问菜单直接报404，是什么原因导致的，component 也没有访问到

**Comment by Shhuy** [comment]
这个之前经过尝试，只能在菜单展示哪里生成对应的菜单展示，但是页面在路由中并没有定义，所以导致访问404。参考其他Issues有过类似的讨论，但是本人尝试不起作用，[参考Issues](https://github.com/ant-design/ant-design-pro/issues/9468) [参考Issues-动态菜单](https://github.com/ant-design/ant-design-pro/issues/9920)
个人想法：
我是在在 app.tsx 中生成侧边菜单栏。
然后路由中配置所有的路由，根据路由配置的 `access` 并且根据在src目录下的 `access.ts`配合动态的过滤服务端返回的路由。以达到动态路由的目的。

**Comment by zhangam** [comment]
+1啊，左侧菜单生成了，点击都是404，上面解决了么

**Comment by PeiRunWu** [comment]
> +1啊，左侧菜单生成了，点击都是404，上面解决了么

还得在路由这再写一份

**Comment by zhangam** [comment]
> > +1啊，左侧菜单生成了，点击都是404，上面解决了么
> 
> 还得在路由这再写一份

那不是知道路由地址哪怕没权限也可以直接放浏览器上进去？只不过是个障眼法？

**Comment by PeiRunWu** [comment]
> > > +1啊，左侧菜单生成了，点击都是404，上面解决了么
> 
> > 
> 
> > 还得在路由这再写一份
> 
> 
> 
> 那不是知道路由地址哪怕没权限也可以直接放浏览器上进去？只不过是个障眼法？

只能动态的去过滤该角色需要哪些路由地址，地址可以不写，但component需要写路由

**Comment by xXAvoraXx** [comment]
我需要有关如何动态加载路线和菜单的演示。

**Comment by xXAvoraXx** [comment]
> 我需要有关如何动态加载路线和菜单的演示。

https://github.com/ant-design/ant-design-pro/discussions/10898

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你提供的代码片段，我看到你正在使用 Umi 进行前端开发。根据问题描述，你已经能够动态生成菜单，但是访问菜单时出现了404错误。

根据Umi的约定式路由规则，你需要在`src/pages/`目录下创建一个`404.tsx`文件，用于处理404页面的渲染。这个文件需要返回一个React组件，你可以根据需求自定义404页面的样式和内容。

举个例子，假设你的目录结构如下：

```bash
.
└── pages
    ├── 404.tsx
    ├── index.tsx
    └── users.tsx
```

根据这个结构，Umi会自动生成以下路由：

```js
[
  { path: '/', component: '@/pages/index' },
  { path: '/users', component: '@/pages/users' },
  { path: '/*', component: '@/pages/404' },
]
```

这样，如果访问的是`/foo`路径，既不匹配`/`，也不匹配`/users`，就会fallback到404路由，并通过`src/pages/404.tsx`进行渲染。

需要注意的是，404页面只在约定式路由中自动生效，如果你使用的是配置式路由，需要手动配置404的通配路由。

希望这个解决方案对你有帮助！如有任何问题，请随时追问。
