### ISSUE TITLE
🧐[问题 | question]您好。我在用model.info控制台出现错误信息atic function can not consume context like dynamic theme. Please use 'App' component instead.

### ISSUE THREAD

**Issue by Fluox-Etine** [ant-design/ant-design-pro#10717]
### 🧐 问题描述 | Problem description
![image](https://user-images.githubusercontent.com/64512602/236353956-dc1b53fc-d525-44d5-9ad3-7a3fdeddcf11.png)

### 💻 示例代码 | Sample code
![image](https://user-images.githubusercontent.com/64512602/236353872-be111a43-beaf-43ac-bf25-af2b0f35b2ae.png)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by jiagoumengxiang** [comment]
我也同样提示了

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述，错误信息提示说`static function can not consume context like dynamic theme. Please use 'App' component instead.`，错误发生在使用`model.info`时，推测可能是`model.info`在使用上下文（context）的主题（theme）时出错。

解决方案是使用`App`组件来代替`model.info`，在v5版本中，`Ant Design`提供了`App`组件来解决这个问题。`App`组件本身带有DOM结构，并为其子节点添加了一些重置样式，并为`Modal`、`message`、`notification`等组件添加了`ContextHolder`。因此，开发者只需在应用的最外层添加`App`组件，就可以在代码中简单地使用它们。

你可以按照以下方式进行修改代码：

```tsx
import { App } from 'antd';

const Demo = () => {
  const { message } = App.useApp();

  React.useEffect(() => {
    message.success('Hello World');
  }, []);

  // ...
};
```

这样，在使用`model.info`时就可以使用`App`组件来代替，并且可以正常使用主题（theme）了。
