### ISSUE TITLE
🧐[问题 | question]安装第三方UI组件库运行期间报错postcss错误

### ISSUE THREAD

**Issue by mayunyi** [ant-design/ant-design-pro#10727]
### 🧐 问题描述 | Problem description

1. 在项目中安装`npm i cgxui`
2. 在config中添加
```  extraBabelPlugins:[
    [
      'babel-plugin-import',
      {
        libraryName: 'cgxui',
        libraryDirectory: 'es',
        style: true,
      }, 'cgxui'
    ],
  ],```
3. 在项目page中引入ui
```
import {Button as CgxiBtn} from 'cgxui'
...省略
return(<Button>demo</Button>)
```
### 💻 示例代码 | Sample code

<!--
一个最小可重现的代码，让开发者可以快速的定位问题
A minimal reproducible code that allows developers to quickly locate problems
-->


### 🚑 其他信息 | Other information


![image](https://github.com/ant-design/ant-design-pro/assets/26814094/997a4145-0c47-4e55-9798-494be7fa8cb0)
![image](https://github.com/ant-design/ant-design-pro/assets/26814094/283dabe5-3cf7-43af-aac1-aac8a66210e8)


OS:
mac os 11.7.4
Node：v16.20.0

浏览器 | browser：chrome 113.0.5672.92

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


**解决方案**

1. 首先，根据报错信息 "postcss" 错误，我们可以初步判断报错是因为 postcss 相关的配置出现了问题。

2. 查看项目中是否已安装了 postcss 相关的依赖。可以通过在命令行中执行以下命令来检查：

   ```shell
   npm ls postcss
   ```

   如果没有安装，则需执行以下命令进行安装：

   ```shell
   npm install postcss -D
   ```

   或者如果项目中已经安装了 postcss，但版本较旧，可以尝试更新 postcss 版本。

3. 如果安装了 postcss，并且版本也是最新的，那么问题可能出在配置上。你可以检查一下项目的 postcss 配置文件是否正确，比如 `.postcssrc` 或者 `.postcssrc.js`。

4. 在 `.postcssrc` 或者 `.postcssrc.js` 中，你可以尝试添加一些常用的插件，例如 `postcss-import` 和 `postcss-preset-env` 等。这些插件可以解决一些常见的兼容性问题。

   ```javascript
   module.exports = {
     plugins: {
       'postcss-import': {},
       'postcss-preset-env': {},
       // 其他插件配置...
     },
   };
   ```

5. 如果以上步骤都没有解决问题，可以考虑删除项目中的 `node_modules` 文件夹，并重新安装依赖：

   ```shell
   rm -rf node_modules
   npm install
   ```

   运行完以上命令后，再次尝试启动项目看看是否还会报错。

6. 如果问题依然存在，建议查看开发者工具中的控制台输出，看看是否有其他相关的错误信息，这些信息可能会给出更具体的问题描述，从而方便我们进一步解决问题。

总结来说，该问题可能是由于 postcss 配置有误或者缺少相关依赖引起的。根据报错信息和上述解决方案，我们可以逐步排查并解决问题。
