### ISSUE TITLE
ant-design-pro v6 使用 qiankun 在开发环境能正常使用，build 后 主应用 加载 子应用会报 initFocus is not a function 错误

### ISSUE THREAD

**Issue by yanthink** [ant-design/ant-design-pro#10725]
### 🧐 问题描述 | Problem description

![image](https://github.com/ant-design/ant-design-pro/assets/9098321/624a83a2-8083-44b3-bb0b-f74718f047c3)

主应用和子应用都使用 ant-design-pro 6.0.0 开发， dev 环境能正常使用，build 后 主应用 加载 子应用会报 initFocus is not a function 错误

### 💻 示例代码 | Sample code

主应用配置

`config/config.ts`

```js
qiankun: {
   master: {},
},
```

`src/app.tsx`

```js
export const qiankun = {
  apps: [
    {
      name: 'app1',
      entry: '//localhost:8888',
    },
  ],
  routes: [
    {
      path: '/app1/*',
      name: 'app1',
      microApp: 'app1',
      microAppProps: {
        autoCaptureError: true,
      },
    },
  ],
};
```

子应用配置

`config/config.ts`

```js
qiankun: {
    slave: {
      shouldNotModifyDefaultBase: true,
    },
 },
```

`src/app.tsx`

```js
export const qiankun = {
  bootstrap() {
    console.log('react app bootstraped');
  },
  mount(props) {
    console.log(props);
  },
  unmount(props) {
    console.log(props);
  },
  update(props) {
    console.log(props);
  },
};
```

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/9098321/17fd5b67-17d0-46eb-99f1-5e2cfd098e21)

OS: MacOS 13.0 (22A380)

Node：v19.7.0

浏览器 | browser：Chrome 113.0.5672.92

**Comment by yanthink** [comment]
umi 配置加上 [esbuildMinifyIIFE: true](https://umijs.org/docs/api/config#esbuildminifyiife) 就好了，建议官方在 umijs 微前端文档FAQ里加上，不然对新手太不友好了。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


主应用和子应用都使用 ant-design-pro 6.0.0 开发，在开发环境能正常使用，但是在build之后，主应用加载子应用时报错“initFocus is not a function”。

针对这个问题，可以尝试以下解决方案：

1. 在子应用的 `src/app.ts` 中导出 `qiankun` 对象，实现生命周期钩子。子应用运行时仅支持配置 `bootstrap`、`mount` 和 `unmount` 钩子。可以在子应用的 `src/app.ts` 文件中添加以下代码：

   ```ts
   export const qiankun = {
     // 应用加载之前
     async bootstrap(props) {
       console.log('app1 bootstrap', props);
     },
     // 应用 render 之前触发
     async mount(props) {
       console.log('app1 mount', props);
     },
     // 应用卸载之后触发
     async unmount(props) {
       console.log('app1 unmount', props);
     },
   };
   ```

   这样可以确保子应用的生命周期钩子正常执行。

2. 确保主应用和子应用的 `config/config.ts` 文件中的 qiankun 配置正确。根据提供的代码片段，主应用的配置中缺少一个 `slave` 配置项。可以在主应用的 `config/config.ts` 文件中添加以下代码：

   ```ts
   qiankun: {
     master: {},
     slave: {},
   },
   ```

   这样可以确保主应用正确加载子应用。

3. 检查主应用和子应用使用的 ant-design-pro 版本。确保主应用和子应用都使用的是相同的版本，以避免版本不兼容导致的问题。

如果以上解决方案不起作用，可以进一步检查主应用和子应用的代码和依赖项，以确定是否有其他问题导致了该错误。如果问题仍然存在，可以尝试创建一个简化的示例项目，并提供更多的错误信息和环境信息，以便更好地帮助解决问题。
