### ISSUE TITLE
and design pro 初始化错误  umi 4 ;clone repo url: https://gitee.com/ant-design/ant-design-pro 'git' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by sanqiu0625** [ant-design/ant-design-pro#10722]
? 🐂 使用 umi@4 还是 umi@3 ? umi@4
🧎🏻全量区块暂时不支持 umi@4
> clone repo url: https://gitee.com/ant-design/ant-design-pro
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
× An error occured while running #writing
C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 nianapi-forntend    at makeError (C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AntDesignProGenerator.writing (C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\src\create\generators\ant-design-pro\index.js:119:5) {
  shortMessage: 'Command failed with exit code 1: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 nianapi-forntend',
  command: 'git clone https://gitee.com/ant-design/ant-design-pro --depth=1 nianapi-forntend',
  escapedCommand: 'git clone "https://gitee.com/ant-design/ant-design-pro" "--depth=1" nianapi-forntend',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0

**Comment by wushangwei** [comment]
系统没装git吧

**Comment by HGD-jpg** [comment]
是已经安装了git的
![image](https://user-images.githubusercontent.com/85720400/237040973-43c1a76c-fd60-471d-802f-4ca60a3fb641.png)

**Comment by HGD-jpg** [comment]
> 系统没装git吧
是已经安装了git的
![image](https://user-images.githubusercontent.com/85720400/237041311-ff95e917-3724-4c41-b782-c1f6ba0f13d1.png)

**Comment by HGD-jpg** [comment]
我解决了 是因为下载了git但是没有做对应的环境变量配置。我是按照这个教程添加了配置之后成功的：https://www.cnblogs.com/ldq678/p/13287924.html

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的错误信息，我们以下的解决方案：

1. 首先，你需要将 `git` 添加到你的系统环境变量中。在命令行中输入 `git` 确认是否可用。如果出现错误提示 `git 不是内部或外部命令`，则说明没有将 `git` 添加到环境变量。

2. 确保你已经安装了 Node.js，并且版本是 v18.16.0。你可以在命令行中输入 `node -v` 来查看版本。如果版本不对，可以使用 nvm（Node.js 版本管理工具）进行版本切换。

3. 确保你已经全局安装了 `pro-cli`。在命令行中输入 `npm i @ant-design/pro-cli -g` 来安装。

4. 确保你已经克隆了 `ant-design-pro` 的仓库。在命令行中输入 `git clone https://gitee.com/ant-design/ant-design-pro` 来克隆。

5. 确保你选择了正确的 umi 版本。在命令行中输入 `umi -v` 来查看版本。如果版本不对，可以使用 `npx umi@4 create myapp` 来创建项目。

6. 你可以通过执行 `cd ant-design-pro` 进入项目文件夹。

7. 最后，执行 `npm install` 或 `yarn` 来安装项目依赖。

希望以上解决方案能够帮助你解决问题。如果还有其他问题，请随时向我提问。
