### ISSUE TITLE
🐛 [BUG]ProFormUploadDragger组件beforeUpload钩子拖拽上传第二个参数没有拿到全部文件

### ISSUE THREAD

**Issue by rswcbqs** [ant-design/ant-design-pro#10726]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的问题描述，我可以给出以下解决方案：

1. 初步分析：根据问题描述，ProFormUploadDragger组件的beforeUpload钩子拖拽上传时第二个参数没有拿到全部文件。首先，我们需要确认是否在ProFormUploadDragger组件的beforeUpload钩子中正确处理了文件参数。

2. 检查beforeUpload钩子：在ProFormUploadDragger组件的beforeUpload钩子中，确保正确使用了event对象中的参数。例如，可以使用event.target.files来获取拖拽上传的文件列表。

3. 检查文件处理逻辑：确认在beforeUpload钩子中是否正确处理了文件参数。可以使用console.log或者debugger来调试，查看文件参数的内容是否正确。

4. 检查组件调用：检查ProFormUploadDragger组件的使用方式，确保正确传入了必要的参数。例如，确认是否正确传入了beforeUpload钩子函数，并且在使用组件时没有覆盖该钩子函数。

5. 检查版本依赖：检查项目中使用的ProFormUploadDragger组件、Ant Design Pro、umi等的版本是否与官方文档要求的兼容。可能存在某些版本之间的兼容性问题，需要更新到兼容的版本。

6. 查找已知问题：查看ProFormUploadDragger组件的官方文档、GitHub仓库或者错误日志等，看是否有类似的问题已经被反馈并解决。

如果以上步骤仍未解决问题，可以尝试以下进一步的调试和解决方案：

7. 调试工具：使用浏览器的开发者工具，尝试调试和观察上传组件的执行过程，查看是否有错误信息或异常抛出。

8. 提交issue：如果以上步骤无法解决问题，可以将问题描述、复现步骤、代码示例等详细信息提交到组件的官方GitHub仓库的issue中，寻求开发者的帮助和反馈。

希望以上解决方案对你有帮助！如果还有其他问题，请随时提问。
