### ISSUE TITLE
Better url

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#1072]
- [x] user-profile => account
- [x] user-profile/userinfo => account/settings
- [x] safe => security
- [x] message => notification

<img width="339" alt="image" src="https://user-images.githubusercontent.com/507615/37249986-4035eefa-252d-11e8-94c8-c1393e04c740.png">

这些应该有独立地址。

**Comment by ddcat1115** [comment]
之前的详情页对应的就是 /profile/xxx ，那边也改个咯？
