### ISSUE TITLE
配置appList失效🧐[问题 | question]

### ISSUE THREAD

**Issue by LeongLRF** [ant-design/ant-design-pro#10723]
### 🧐 问题描述 | Problem description
配置appList不生效

### 💻 示例代码 | Sample code
   rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    appList: [
      {
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
        title: 'Ant Design',
        desc: '杭州市较知名的 UI 设计语言',
        url: 'https://ant.design',
      },
      {
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
        title: 'Ant Design',
        desc: '杭州市较知名的 UI 设计语言',
        url: 'https://ant.design',
      }
    ],

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题描述：配置appList不生效。

解决方案：
1. 首先，检查是否在正确的位置配置了appList。根据提供的代码片段，appList应该是在配置文件中的layout选项里面。

2. 然后，检查是否正确配置了routes文件。根据提供的信息，routes文件中的layout配置项可能不生效。

3. 最新版本的Umi已经对layout配置进行了更新。现在layout配置项已经移动到了app.ts文件中。你需要在app.ts文件中配置layout，并将appList放在配置项中。

4. 检查是否按照规定的格式设置appList。确保每个app都包括icon、title、desc和url属性，并且它们的值是有效的。

5. 最后，重新启动项目并检查appList是否生效。

以上是针对配置appList不生效的一般解决方案。如果问题仍然存在，请提供更多详细信息，以便我们能够更好地帮助你解决问题。
