### ISSUE TITLE
🐛 [BUG] 去除国家化，报错，有没有小伙伴和我一样的

### ISSUE THREAD

**Issue by butingxuexi** [ant-design/ant-design-pro#10724]
![Snipaste_2023-05-10_10-09-26](https://github.com/ant-design/ant-design-pro/assets/27430203/4dfe53db-4710-4b48-93fd-9748a1f99b79)
v5.2版本，v4.5我试了也是这样，求解决方案。

**Comment by chaofan2011** [comment]
我的也是 只能一个个删

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案如下：

1. 首先，你可以尝试使用 `npm run i18n-remove` 命令来删除全球化。这个命令是 ant-design-pro 提供的，可以帮助你删除项目中的全球化代码。

2. 但需要注意的是，`i18n-remove` 只是一个基础的测试工具，它主要适用于删除 ant-design-pro 自带的全球化代码。如果你的项目中使用了更高级的全球化特性，比如 `formatMessage({id: somevar})` 这种动态的代码，那么 `i18n-remove` 可能无法分析并删除这部分代码。

3. 如果你有更好的解决方案，可以尝试提交一个 pull request（pr）到 ant-design-pro-cli 项目，分享你的想法和实现方式。

总结来说，基于你提供的信息，尝试使用 `npm run i18n-remove` 命令来删除全球化代码，对于高级的全球化特性可能需要手动修改代码。

**Comment by mayongkang1** [comment]
> 我的也是 只能一个个删

![image](https://github.com/ant-design/ant-design-pro/assets/94114667/0f96fb44-72c9-4abf-902f-48b079614f5a)

**Comment by chenshuai2144** [comment]
这个是类型报错，不影响实际效果的

**Comment by chenshuai2144** [comment]
修复了，更新一下所有的依赖
