### ISSUE TITLE
🧐master分支的代码运行后没有找到设置暗黑菜单风格，只有亮色菜单和暗色风格

### ISSUE THREAD

**Issue by carson-repository** [ant-design/ant-design-pro#10736]
### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/42593750/e42159fe-892f-4036-a1b1-18c6962b9de4)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案如下：

1. 首先确认代码中是否有对暗黑菜单风格的设置。检查代码中是否有对应的配置项或者样式定义。

2. 如果代码中确实没有对暗黑菜单风格进行设置，可以按照以下步骤进行操作：

   - 确认使用的前端框架或库是否支持暗黑菜单风格。例如，如果使用的是 React 框架，可以参考相关文档或社区资源，查看是否有对应的组件或样式库支持。

   - 检查使用的 UI 组件库是否支持暗黑菜单风格，例如 Umi 和 Ant Design。查阅官方文档或社区资源，了解如何设置暗黑菜单风格的方法。

   - 如果没有直接支持暗黑菜单风格的选项，可以考虑自定义样式来实现。通过调整组件的样式或覆盖默认样式，将菜单的颜色设置为暗黑色或深色。

3. 如果确认代码中已经进行了暗黑菜单风格的设置，但运行后仍然没有效果，可以尝试以下操作：

   - 确保代码在运行前已经编译或打包。有些前端框架或工程化工具需要通过编译或打包过程才能应用样式设置。

   - 检查浏览器是否支持暗黑模式。某些浏览器可能需要用户手动开启暗黑模式才能显示对应的样式。

   - 清除浏览器缓存，然后重新加载页面。有时候缓存的样式文件可能导致旧的样式一直被使用。

   - 使用开发者工具检查元素的样式，确认是否有覆盖或冲突的样式。可能其他样式设置了优先级较高，导致暗黑菜单风格无法生效。

4. 如果以上操作都没有解决问题，可以尝试在开发环境中进行调试。通过打印日志、使用断点调试工具等方式，定位代码中可能存在的问题，例如样式文件是否加载成功，设置是否生效等。

5. 如果仍然无法解决问题，可以在相关的开发社区或论坛上寻求帮助。提供详细的问题描述、代码片段和运行环境等信息，有助于其他开发者更好地理解问题并提供解决方案。

**Comment by chenshuai2144** [comment]
不支持那个模式了，设计师觉得那个落伍了
