### ISSUE TITLE
主题色怎么没全局生效

### ISSUE THREAD

**Issue by qiaoshuai666** [ant-design/ant-design-pro#10735]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/ant-design-pro/assets/22763007/b34f3292-1d69-45ec-821c-1684fd5f9c31)

**Comment by xiaqingping** [comment]
这个是因为这里用的a标签改成button type=link 就可以跟随主题变化了

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据描述的情况，问题可能是由于缺少全局的主题配置导致主题色没有全局生效。可以通过以下步骤来解决问题：

1. 确保已经正确安装了 `antd` 和 `@umijs/preset-react` 的依赖包。

2. 在入口文件（一般是 `src/index.js` 或 `src/app.js`）中，引入 `ConfigProvider` 组件和主题配置文件。

   ```javascript
   import React from 'react';
   import ReactDOM from 'react-dom';
   import { ConfigProvider } from 'antd';
   import theme from './theme'; // 主题配置文件

   ReactDOM.render(
     <ConfigProvider theme={theme}>
       {/* 其他组件 */}
     </ConfigProvider>,
     document.getElementById('root')
   );
   ```

   注意：`theme` 变量是一个对象，
