### ISSUE TITLE
🧐[问题 | question] v6中less直接使用@primary-color不生效

### ISSUE THREAD

**Issue by wavesbig** [ant-design/ant-design-pro#10730]
### 🧐 问题描述 | Problem description

v6中设置了colorPrimary，在less中使用@primary-color显示颜色并不是colorPrimary设置的颜色

### 🚑 其他信息 | Other information
![image](https://github.com/ant-design/ant-design-pro/assets/34082148/60b98309-3028-416e-818e-89f330849971)
![image](https://github.com/ant-design/ant-design-pro/assets/34082148/3056a8c7-f8af-4e9b-be29-30f62fcd2081)
![image](https://github.com/ant-design/ant-design-pro/assets/34082148/e2012071-2ec6-4efe-b098-8862b3b5ccb2)

OS: win

Node：16.15.0

浏览器 | browser：chorme

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述，你在使用 v6 版本的 Ant Design 中，设置了 `colorPrimary`，但是在 less 中使用 `@primary-color` 并没有显示 `colorPrimary` 设置的颜色。

在 Ant Design v6 中，为了更好地支持主题定制和样式变量的管理，引入了 Design Token 的概念。Design Token 是一种抽象的样式变量，可以用于自定义主题和样式。

在 v6 中，如果你需要在 less 中直接使用 Design Token，可以使用静态方法 `getDesignToken` 导出样式变量，然后在 less 文件中使用。具体步骤如下：

1. 首先，从 `theme` 模块中导入 `getDesignToken` 方法。

```jsx
import { theme } from 'antd';

const { getDesignToken } = theme;
```

2. 然后，通过调用 `getDesignToken` 方法获取 Design Token。

```jsx
const globalToken = getDesignToken();
```

3. 最后，将 `globalToken` 变量应用到 less 编译器中。

```jsx
{
  loader: "less-loader",
  options: {
    lessOptions: {
      modifyVars: globalToken,
    },
  },
}
```

通过上述步骤，你就可以在 less 中使用 Design Token 了。

同时，如果你需要将其应用到静态样式编译框架，如 less，可以通过 less-loader 注入。具体配置如下：

```jsx
{
  loader: "less-loader",
  options: {
    lessOptions: {
      modifyVars: globalToken,
    },
  },
}
```

这样就可以在 less 文件中使用 Design Token，并且将其应用到静态样式编译中了。

如果你想了解更多关于 Design Token 的内容，可以参考 Ant Design 官方文档中的相关部分。
