### ISSUE TITLE
🧐[问题 | question]最新版ant design pro和umi4开启多tab之后，如果多个路由指向同一个component，会出现共用组件及刷新问题

### ISSUE THREAD

**Issue by lostinwind** [ant-design/ant-design-pro#10734]
### 🧐 问题描述 | Problem description

我用最新版本的ant design pro配合最新的umi4，然后在config.ts里增加了如下代码：
  keepalive: [/./],
  tabsLayout: {
    hasDropdown: true,
  },
多tab是开启了。但是当多个路由指向同一个component时，然后打开这些路由，发现切换这几个路由tab的时候，切换很慢，component在共用，会进行刷新操作。
配置的其中一部分路由如下：
  {
    path: '/data',
    name: '数据目录',
    icon: 'SlackOutlined',
    routes: [
      { path: '/data', key: 'data', redirect: '/data/todo' },
      { path: '/data/todo', key: 'data-todo', name: '待上报', component: './DataManager', exact: true },
      { path: '/data/done', key: 'data-done', name: '已上报', component: './DataManager', exact: true },
      { path: '/data/fail', key: 'data-fail', name: '上报异常', component: './DataManager', exact: true }
    ]
  },
如上，我打开了“待上报”、“已上报”、“上报异常”，然后切换这几个tab，就会出现反复刷新问题，好像在共用component

OS:
mac11.2
Node：
v16.13.2
浏览器 | browser：
chrome 113.0.5672.92

**Comment by lostinwind** [comment]
基于location.pathname设置不同参数的函数，包装useCallback就可以了

**Comment by fangqibin** [comment]
> 基于location.pathname设置不同参数的函数，包装useCallback就可以了

能不能提供一下示例代码
