### ISSUE TITLE
🧐[问题 | question] umijs4下为什么title文字过长会倾斜？

### ISSUE THREAD

**Issue by YuZongYangHi** [ant-design/ant-design-pro#10738]
<img width="390" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/35584408/7d098363-182e-4d2a-a891-3907107a2590">

```
{
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.3.57",
    "@ant-design/use-emotion-css": "1.0.4",
    "@umijs/route-utils": "^2.2.2",
    "antd": "^5.2.2",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.8.2",
    "rc-util": "^5.27.2",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.4",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0"
  }
```

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题: umijs4下为什么title文字过长会倾斜？

解决方案:

1. 首先，确定问题是否与样式相关。在浏览器中检查页面元素的样式，查看是否有倾斜的CSS属性或样式类。

2. 如果发现了相关的CSS属性或样式类，可以尝试以下解决方法：
   - 检查是否有写死的宽度限制或最小宽度限制，可以尝试调整宽度或最小宽度以适应长文字。
   - 检查是否有使用文字换行属性，例如`white-space: nowrap;`，可以尝试移除该属性或调整为适当的换行方式。
   - 检查是否有使用文字溢出属性，例如`text-overflow: ellipsis;`，可以尝试移除该属性或调整为适当的文字显示方式。

3. 如果以上方法没有解决问题，可以检查是否有其他UI库或组件库对标题样式进行了修改。可以尝试通过调整相关组件的样式或配置来解决问题。

4. 如果问题仍然存在，可以尝试在UMI的配置文件中进行一些调整，例如调整全局样式或字体设置。

5. 如果以上方法都没有解决问题，可以考虑提交一个issue给UMI的官方维护团队，详细描述问题并提供相关的代码和配置信息，以便他们能够更好地帮助解决问题。

请注意，以上解决方法是基于一般情况下出现问题的可能原因和解决方案。具体解决方法可能因实际情况而异，需要结合具体代码和配置来确定最佳解决方案。
