### ISSUE TITLE
vscode各种报错,项目可以正常运行🧐[问题 | question]

### ISSUE THREAD

**Issue by zhangyuanlin666** [ant-design/ant-design-pro#10737]
### 🚑 其他信息 | Other information

![Uploading image.png…]()

OS:

Node：

浏览器 | browser：

**Comment by zhangyuanlin666** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/66874263/bcb6926e-7caa-498a-bdd7-939880080501)

**Comment by drizzlesconsin** [comment]
用 pnpm (8.5.0) 安装试试

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


维护者：你好，我看到你说在使用vscode时遇到了各种报错，但是项目本身可以正常运行。首先，我建议您检查一下您的vscode是否是最新版本，以确保您能够使用最新的功能和修复的bug。

另外，您可以尝试以下解决方案：
1. 清除vscode的缓存：您可以尝试删除`%AppData%\Code\cache`目录和`%AppData%\Code\CachedData`目录，并重新启动vscode。
2. 检查项目依赖：确保您的项目依赖项已经正确安装并且没有冲突。您可以尝试删除`node_modules`目录，并重新运行`npm install`或`yarn`来重新安装依赖项。
3. 检查vscode的插件：有时候，某些vscode的插件可能会导致报错。您可以尝试禁用所有插件，然后逐个启用它们，以确定哪个插件导致了问题。
4. 更新.vscode/settings.json：您可以检查.vscode目录下的settings.json文件，并确保其中的配置项正确且没有错误。

如果您在尝试以上解决方案后仍然遇到问题，我建议您在vscode的官方论坛或社区中提问，以获得更多专业的帮助和支持。

希望这些解决方案能够帮助您解决问题！如果您有其他问题，请随时提问。
