### ISSUE TITLE
🐛 [BUG]RangePicker 组件Ranges 选定后value未更新

### ISSUE THREAD

**Issue by onsuper** [ant-design/ant-design-pro#10747]
### 📷 复现步骤 | Recurrence steps
RangePicker 组件 设置 Ranges 在组件会显示出Ranges 的配置如 当日,本月,本年等等
选择: 当日,或者 本年,或者本月之后不会将 bind-value数据未更新,

`<RangePicker TValue="DateTime?[]" @bind-Value="@_fillterDto.Times" Ranges="@RangePickerRangs.GetRangs()" />
              `

`/// <summary>
        /// 日期控件的时间选择
        /// </summary>
        /// <returns></returns>
        public static Dictionary<string, DateTime?[]> GetRangs()
        {
            var Ranges = new Dictionary<string, DateTime?[]>()
            {
                { "当天", new DateTime?[] { DateTime.Now.Date, DateTime.Now.Date.AddDays(1) } } ,
                { "昨天", new DateTime?[] { DateTime.Now.Date.AddDays(-1), DateTime.Now.Date } } ,
                { "前天", new DateTime?[] { DateTime.Now.Date.AddDays(-2), DateTime.Now.Date.AddDays(-1) } } ,

                { "本月", new DateTime?[] { new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1), new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(1) } } ,
                { "上月", new DateTime?[] { new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).AddMonths(-1), new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1) } } ,

                { "本年", new DateTime?[] { new DateTime(DateTime.Now.Year, 1, 1), new DateTime(DateTime.Now.Year, 1, 1).AddYears(1) } } ,
            };

            return Ranges;
        }`
### © 版本信息

- Ant Design Pro 版本: [0.14.4.1]
- umi 版本
- 浏览器环境
- 开发环境 [windows10 vs2022]

**Comment by ChanKingBooo** [comment]
哥们解决了吗？

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题的解决方案：

1. 首先，我们需要确认 `RangePicker` 组件的 `value` 属性是否正确绑定了数据。可以通过打印 `_fillterDto.Times` 来确认数据是否正确。

2. 如果数据绑定正确，但是选定后 `value` 未更新，可能是因为 `RangePicker` 组件的 `value` 是一个数组类型 `DateTime?[]`，需要确保在选择范围时，正确更新该数组的值。

3. 可以尝试使用 `onOk` 事件来监听用户确认选择范围的操作，然后在回调函数中更新 `value` 的值。

示例代码如下：

```jsx
<RangePicker
  TValue="DateTime?[]"
  @bind-Value="@_fillterDto.Times"
  Ranges="@RangePickerRangs.GetRangs()"
  @onOk="HandleRangeSelection"
/>
```

```c#
public void HandleRangeSelection(DateTime?[] selectedRange)
{
  _fillterDto.Times = selectedRange;
}
```

请确保在 `RangePicker` 组件中设置了 `@onOk` 事件，并在回调函数中更新 `value` 的值。

4. 如果以上步骤没有解决问题，可以尝试使用 `useState` 钩子来手动控制 `value` 的更新。

```jsx
import React, { useState } from 'react';

const [selectedRange, setSelectedRange] = useState([]);

<RangePicker
  TValue="DateTime?[]"
  Value={selectedRange}
  Ranges={RangePickerRangs.GetRangs()}
  onOk={() => {
    setSelectedRange(selectedRange);
  }}
/>
```

通过使用 `useState` 钩子来维护一个 `selectedRange` 的状态，并在 `onOk` 事件中更新该状态，以实现手动控制 `value` 的更新。

希望以上解决方案能够帮助到您。如果问题仍然存在，请提供更多的代码和相关信息，以便我们能够更好地帮助您解决问题。
