### ISSUE TITLE
🧐[问题 | question]v5使用自定layout无效

### ISSUE THREAD

**Issue by guozidashu** [ant-design/ant-design-pro#10749]
### 🧐 问题描述 | Problem description

官网中的自定义布局https://pro.ant.design/zh-CN/docs/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80
介绍在v4版本可行，但是在v5版本中无法正常运作；
### 💻 示例代码 | Sample code
路由代码
`  {
    path: '/test',
    name: 'test',
    icon: 'smile',
    layout: false,
    component: '../layouts/BaseLayout',
    routes: [
      {
        path: '/test/admin',
        redirect: '/admin/sub-page',
      },
      {
        path: '/test/sub-page',
        name: 'sub-page',
        component: './Admin',
      },
    ],
  },`
布局代码
`const layout = ({ children }) => {
    console.log('layout', children);
    return (
        <div>
            <h1>自定义布局</h1>
            {children}
        </div>
    )
};
export default layout;`

实际得到的结果 undefined
### 🚑 其他信息 | Other information

OS:win10

Node：16>

浏览器 | browser：

**Comment by enhezzz** [comment]
我也遇到了，请问解决了吗

**Comment by HP-283** [comment]
麻烦尽快解决一下. 我也遇到了. 升级不上去了.

**Comment by guozidashu** [comment]
@enhezzz 解决不了，只能用v4

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题的解决方案：

1. 首先，确认您的项目是否使用了 Umi 和 antd 的最新版本。可以通过运行 `npm list umi` 和 `npm list antd` 来检查版本号。

2. 确认您的路由配置是否正确。根据您提供的示例代码，路由配置似乎是正确的。但请确保路由配置中的组件路径是正确的，并且组件也存在于相应的路径中。

3. 检查您的布局组件是否正确导出。根据您提供的示例代码，布局组件似乎是正确的。但请确保布局组件是通过 `export default` 导出的，并且在路由配置中正确引入了。

4. 如果上述步骤都没有解决问题，可以尝试以下方案：

   - 确保您的项目已经安装了 `@umijs/preset-react` 包。可以运行 `npm install @umijs/preset-react --save` 来安装。

   - 在路由配置中，将布局组件的路径改为绝对路径，例如 `component: '@/layouts/BaseLayout'`。

5. 如果仍然无法解决问题，建议您查看 Umi 和 antd 的官方文档，以了解最新的使用方式和配置示例。您还可以在 Umi 和 antd 的 GitHub 仓库中提出 issue，寻求更多的帮助和解决方案。

以上是基于您提供的信息给出的解决方案。如果还有其他信息或问题，请提供更多详细信息，以便我们能够更准确地帮助您解决问题。

**Comment by chenshuai2144** [comment]
看啊看更新日志 不能用 children 了，要改成用相应的组件
