### ISSUE TITLE
> pc 端有完整 可以先做到以下效果的 ![image](https://user-images.githubusercontent.com/46490104/238395913-0bc0f73f-3ab7-4f8f-b2a3-e84968c37d7f.png)

### ISSUE THREAD

**Issue by jby123** [ant-design/ant-design-pro#10743]
> pc 端有完整 可以先做到以下效果的 ![image](https://user-images.githubusercontent.com/46490104/238395913-0bc0f73f-3ab7-4f8f-b2a3-e84968c37d7f.png)

请问你的antd版本、pro-components版本分别是多少呀，我antd 4.23.3，pro-components是2.4.15，web端配置token也是部分生效

"@ant-design/pro-components": "^2.3.57",
"antd": "^5.2.2",

**Comment by chenshuai2144** [comment]
去看  all-block 分支
