### ISSUE TITLE
🧐[问题 | question] 搜狗浏览器无法正常显示，其他浏览器可以

### ISSUE THREAD

**Issue by yjcvme89** [ant-design/ant-design-pro#10741]
### 🧐 问题描述 | Problem description

其他浏览器看都是正常的，搜狗浏览器样式不对
### 🚑 其他信息 | Other information

<img width="1072" alt="001" src="https://github.com/ant-design/ant-design-pro/assets/126061166/bf80399a-80a8-4227-a3b5-b5dd7f9d2e80">

OS:

Node：

浏览器 | browser：

**Comment by lovewinders** [comment]
搜狗浏览器内核低于88，所以访问效果不兼容

**Comment by chenshuai2144** [comment]
https://ant-design.antgroup.com/docs/react/compatible-style-cn

看这里
