### ISSUE TITLE
🧐[问题 | question] 还会继续有人维护这个项目吗？我看都已经 1 年没更新了。目前还是 6.0.0 beta1（2022年6月27日发版）

### ISSUE THREAD

**Issue by andrew-wx** [ant-design/ant-design-pro#10742]
<img width="276" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/48849446/f1a51995-5cb9-46cd-8e94-2db5599368b0">

如题

**Comment by 17LingShan** [comment]
现在看到的情况是直接拉取code下来甚至已经不能直接admin and ant.design登录的，可能已经没有人维护了
😂

**Comment by RainingNight** [comment]
尸体都凉透了

**Comment by WenLonG12345** [comment]
那么好的开源项目为什么没人维护了呢？

**Comment by Bojianye** [comment]
裁员了？

**Comment by seamanm** [comment]
KPI项目完成完成了

**Comment by seamanm** [comment]
6.0一年了都出不出来，难产了

**Comment by lovewinders** [comment]
再等等吧，说不定一年半载的就发布了，现在master分支6.0也能用

**Comment by ranvk** [comment]
收集到的消息是等预计是在等8月份的and/chart 2.0的发布

**Comment by wxuonline** [comment]
> 收集到的消息是等预计是在等8月份的and/chart 2.0的发布

靠谱吗，已经8月份了

**Comment by gaollg** [comment]
靠谱吗，已经 2023-08-21 了

**Comment by a1782680475** [comment]
2023-10-02了

**Comment by chenJJ-88** [comment]
2023-11-23了

**Comment by chenshuai2144** [comment]
维护还是维护的，主要能力全部在组件库那里。脚手架没什么好更新的了

**Comment by coder-belong** [comment]
2024-06-25了 还是beat版本

**Comment by SoftwareEngineerPalace** [comment]
没人管

**Comment by baiyuanyong** [comment]
用不了都，废了

**Comment by rushairer** [comment]
2024年12月18日了

**Comment by c-yi** [comment]
2025年04月14日了
