### ISSUE TITLE
🐛 [BUG]AntDesign.ProLayout.BasicLayout 的参数OnOpenChange事件无效 无法更新OpenKeys

### ISSUE THREAD

**Issue by onsuper** [ant-design/ant-design-pro#10748]
### 📷 复现步骤 | Recurrence steps
`<AntDesign.ProLayout.BasicLayout Logo="@("logo.svg")"
                                 MenuData="_menuData"
                                 OpenKeys="this.openKeys"
                                 OnOpenChange="this.onOpenChange">`

`    string[] openKeys = { "" };
    void onOpenChange(string[] openKeys)
    {
        var latestOpenKey = openKeys.FirstOrDefault(key => !this.openKeys.Contains(key));
        if (_menuData.ToList().Any(t => t.Key.Contains(latestOpenKey)))
        {
            this.openKeys = openKeys;
        }
        else
        {
            this.openKeys = !string.IsNullOrEmpty(latestOpenKey) ? new[] { latestOpenKey } : Array.Empty<string>();
        }
    }`

### 🏞 期望结果 | Expected results

[https://antblazor.com/zh-CN/components/menu#components-menu-demo-sider-current](url)

### © 版本信息

Ant Design Pro 版本: [0.14.4.1]
umi 版本
浏览器环境
开发环境 [windows10 vs2022]

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据您的描述，问题是"menuProps onOpenChange无法更新OpenKeys"。

解决方案如下：

1. 首先确认您使用的Ant Design Pro的版本是否为0.14.4.1。根据您提供的信息，Ant Design Pro的版本是0.14.4.1，所以版本没有问题。

2. 检查在`AntDesign.ProLayout.BasicLayout`组件中，`OpenKeys`属性是否正确传递了。根据您提供的代码片段，OpenKeys属性被正确传递了。

3. 检查`onOpenChange`方法是否被正确地定义和调用。根据您提供的代码片段，`onOpenChange`方法被正确地定义和调用了。

4. 检查`onOpenChange`方法内的逻辑是否正确。根据您提供的代码片段，`onOpenChange`方法的逻辑看起来是正确的。

5. 如果问题仍然存在，可以尝试升级Ant Design Pro的版本。根据您提供的信息，最新版本是5.3.3，可以尝试升级到该版本。

6. 如果问题仍然无法解决，可以去Ant Design Pro的GitHub仓库提交一个issue，描述您的问题并提供复现代码和相关环境信息。开发人员可以帮助您解决问题。

希望以上解决方案对您有帮助！如果您有其他问题，请随时提问。
