### ISSUE TITLE
table设置筛选时，分页会重置为默认值

### ISSUE THREAD

**Issue by DateLife** [ant-design/ant-design-pro#1074]
在表格的分页里设置好分页条件之后，点筛选功能时，分页条件会重置为默认值

**Comment by ddcat1115** [comment]
单纯的 Ant Design 组件使用问题请反馈到 https://segmentfault.com/t/antd ，bug 或建议请提交到 http://new-issue.ant.design

提供在线可重现 demo 可以帮助我们更好的定位问题 https://u.ant.design/codesandbox-repro 😃
