### ISSUE TITLE
v4升到v5后，less文件如何变成useEmotionCss

### ISSUE THREAD

**Issue by wjcwzh** [ant-design/ant-design-pro#10746]
.table {
  margin-top: 30px;
  .password {
    :global {
      .ant-form-item {
        margin-bottom: auto;
      }
    }
  }
}

.form {
  .group {
    margin-bottom: 20px;
  }
}
 global这段怎么实现啊？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/antd-style/blob/master/docs/guide/migrate-less-component.zh-CN.md

看看这个文档，能提供一个迁移工具
