### ISSUE TITLE
🧐[问题 | question] 用 antd pro 的脚手架直接搭的项目，在使用 protable 发现数据很快就拿到了，但是渲染很慢，loaidng 时间很长才会显示出来数据，直接用 table 就很快渲染出数据

### ISSUE THREAD

**Issue by NARUTOyuyang** [ant-design/ant-design-pro#10755]
### 🧐 问题描述 | Problem description

数据量很小，就 100 条
### 💻 示例代码 | Sample code

```
npm i @ant-design/pro-cli -g 
pro create myapp

//然后用的是 umi@3 版本

//使用 protable 的代码

const getList =async (params)=>{
   const res = await getListApi(params);
// 此时打印 res ,很快拿到数据，但是页面还是很慢才渲染出来
console.log(res)
  return {
      data: res.list,
      success: true,
      total: res.total,
    };
}

<ProTable
        columns={productColumns}
        rowKey={'id'}
        headerTitle={false}
        search={false}
        options={false}
        request={(params) => getList(params)}
        pagination={false}
      />


```
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


从问题描述中可以看出，使用Ant Design Pro脚手架搭建的项目，在使用ProTable组件时，虽然数据请求很快，但是渲染速度很慢，需要很长时间才能显示数据。然而，直接使用普通的table组件却能很快地渲染出数据。

这个问题可能是由于ProTable组件在处理数据时引入了一些额外的逻辑导致的。为了解决这个问题，可以尝试以下几个方案：

1. **检查数据量和渲染逻辑**：确保数据量较小，且渲染逻辑没有其他复杂操作，例如循环嵌套或递归等。如果数据量过大或渲染逻辑复杂，可能会导致渲染时间过长。

2. **检查网络请求**：确保网络请求的速度较快，没有阻塞或延迟。可以使用浏览器开发者工具检查网络请求的时间轴，查看请求是否存在延迟或阻塞。

3. **优化数据处理逻辑**：在`getList`方法中，可以尝试优化数据处理逻辑，例如使用`map`方法代替`for`循环，使用`filter`方法筛选数据等。确保数据处理逻辑高效，并且不会占用过多的计算资源。

4. **使用虚拟滚动**：如果表格中的数据量较大，可以考虑使用虚拟滚动技术来优化性能。虚拟滚动可以只渲染可见区域的数据，减少渲染的工作量，从而提高页面的渲染速度。

5. **使用React的性能优化技术**：可以尝试使用React的性能优化技术，例如React.memo、useMemo、useCallback等，来避免不必要的渲染和重新计算。

6. **尝试其他表格组件**：如果以上方法都没有解决问题，可以尝试使用其他的表格组件替代ProTable，例如Ant Design的Table组件或者其他第三方的表格组件。通过比较不同组件的性能和渲染速度，选择最适合项目需求的表格组件。

综上所述，可以通过检查数据量和渲染逻辑、优化数据处理逻辑、使用虚拟滚动、使用React的性能优化技术、尝试其他表格组件等方法来解决ProTable渲染速度慢的问题。根据具体情况，选择适合项目需求的解决方案。
