### ISSUE TITLE
🐛 [BUG] 升级antd@5.5.1报错

### ISSUE THREAD

**Issue by wavesbig** [ant-design/ant-design-pro#10758]
### 🐛 bug 描述

提示依赖`@rc-component/tour`版本`1.8.0`但是此依赖最新版本的为`1.7.1`

![image](https://github.com/ant-design/ant-design-pro/assets/34082148/a0501916-663e-4c02-8925-08106ae0e9b2)

### 🏞 期望结果 | Expected results

正确安装

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]6.0.0
- umi 版本 4.0.52
- 浏览器环境 chorme
- 开发环境 [e.g. mac OS] win

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案如下：

1. 首先尝试升级`@rc-component/tour`依赖到`1.8.0`版本，可以通过以下命令进行升级：

```bash
npm install @rc-component/tour@1.8.0
```

2. 如果`@rc-component/tour`没有提供`1.8.0`版本，可以尝试修改`package.json`文件，将`@rc-component/tour`的版本改为`1.7.1`，然后运行`npm install`重新安装依赖。

3. 如果以上两个步骤都没有解决问题，可以尝试查看`ant-design`官方的升级日志，找到最新的版本，并尝试升级到该版本，可能会修复此问题。

4. 如果还是无法解决问题，可以尝试升级整个Ant Design Pro项目的版本，确保与`antd`版本兼容的最新版本。

5. 如果仍然无法解决问题，可以尝试通过创建一个新的React项目，并按照官方文档的指导重新配置和安装依赖，然后将现有代码迁移到新项目中，以确保项目的正确运行。

请注意，以上解决方案仅供参考，具体的解决步骤可能需要根据实际情况进行调整。另外，如果以上方法仍然无法解决问题，建议在Ant Design Pro的GitHub仓库中提交一个issue，以寻求官方的帮助和支持。
