### ISSUE TITLE
🧐js代码不进行混淆以便进行调试

### ISSUE THREAD

**Issue by ognlyoptrbp5539** [ant-design/ant-design-pro#10751]
### 🧐  js代码不进行混淆以便进行调试

如何在ant-design-pro V6 打包后，js代码不进行混淆以便进行调试

### 💻 示例代码 | Sample code

config\config.ts中，添加了sourcemap以及不进行js压缩
devtool: 'source-map',
  jsMinifier: 'none',

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/120808582/02d70fd4-7374-4bd5-ad8d-bfa0561c23e2)

ant-design-pro V6

OS: window 10

Node：v18.13.0

浏览器 | browser：Chrome 版本 113.0.5672.93（正式版本） （64 位）

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


针对在 ant-design-pro V6 中需要对 js 代码进行调试的问题，你可以按照以下步骤进行操作：

1. 在 `config/config.ts` 文件中，找到 `devtool` 和 `jsMinifier` 的配置项。
2. 确保 `devtool` 的值为 `'source-map'`，这将生成一个对应的 source map 文件。
3. 确保 `jsMinifier` 的值为 `'none'`，这将禁用对 js 代码的压缩和混淆。
4. 重新运行打包命令，生成带有 source map 的未压缩的 js 代码。

此时，你将会得到未压缩的 js 代码以及对应的 source map 文件。你可以将这些文件拷贝到你的项目根目录中，用于调试。

接下来，你可以按照以下步骤进行调试：

1. 打开你的项目在开发环境中运行，确保你的浏览器开发者工具中启用了 source map 支持。
2. 在浏览器中打开你想要调试的页面，并打开开发者工具的 Source 面板。
3. 寻找对应的 js 文件，在文件中进行断点设置、变量查看等调试操作。
4. 刷新页面，触发相应的操作，使得代码执行到你设置的断点处。
5. 在开发者工具中进行调试操作，观察变量、调用堆栈等信息。

通过以上步骤，你可以在开发环境中进行对 ant-design-pro V6 打包后的 js 代码进行调试。记得在调试完成后，将原来的压缩混淆的 js 文件恢复到正常状态。
