### ISSUE TITLE
🐛 [BUG] 每次打开页面，先 loading 一下，这时候 loading 其实页面 protable 接口的数据都拿到了，但是又会 protable 的 loading 再执行一遍，就很奇怪啊

### ISSUE THREAD

**Issue by NARUTOyuyang** [ant-design/ant-design-pro#10756]
### 🐛 bug 描述

加载页面的时候 loading，接口数据都返回了，完了 protable 还要 loading，接口没有多余触发

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
hooks  总是慢半拍的，想要实现这个功能就需要提前去加载数据然后不走 loading 的逻辑
