### ISSUE TITLE
🧐切换主题导致样式丢失

### ISSUE THREAD

**Issue by xiaqingping** [ant-design/ant-design-pro#10769]
### 🧐 问题描述 | Problem description
在切换主题颜色时会出现样式丢失的问题
主要是来回切换light和realDark时会导致一些样式表丢失，最近才发现这个问题，可能是由于升级到v5才发生的，具体原因不明。
期望有遇到这个问题的朋友或者官方大佬可以给我一点建议和帮助，谢谢！

![image](https://github.com/ant-design/ant-design-pro/assets/49116631/4d6c0ffb-8786-4532-bfec-44e71ad3ec23)

![image](https://github.com/ant-design/ant-design-pro/assets/49116631/aa610fe9-08ee-4d98-952e-7945802359b4)

**Comment by zyc329** [comment]
类似+1
我是有几个页面单独写了layout
route配置layout:false
又的时候切换会丢失 但是无法百分百复现

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


对于切换主题导致样式丢失的问题，可以考虑以下解决方案：

1. 检查主题切换逻辑：首先检查主题切换的实现逻辑，确保没有遗漏或错误的代码。可以使用浏览器的调试工具检查是否有报错或警告信息。

2. 使用 CSS 变量管理主题颜色：考虑使用 CSS 变量来管理主题颜色，这样切换主题时只需要修改对应的 CSS 变量值，而不会影响其他样式。

3. 使用前端框架自带的主题切换功能：如果使用的前端框架（如React）有提供主题切换的功能，可以尝试使用框架自带的功能来实现主题切换，确保切换主题时不会丢失样式。

4. 使用前端工程化工具：可以考虑使用前端工程化工具（如Umi）来优化项目的构建和部署流程，确保代码的构建和发布过程没有问题。

5. 前端性能优化：对于卡顿或刷新问题，可以考虑进行前端性能优化，例如减少主题切换时的样式计算量、使用缓存或预加载等方式来提升页面性能和用户体验。

综上所述，以上是针对切换主题导致样式丢失的问题的一些解决方案，具体的实施方法可以根据具体情况进行调整和优化。
