### ISSUE TITLE
👑 [需求 | Feature] useModel是否可以提供一个获取实例的方法

### ISSUE THREAD

**Issue by weituwei** [ant-design/ant-design-pro#10764]
问题描述：
有些特殊组件或模块不能引入useModel，在开发环境下useModel实例挂在了window._umi_useModel_dev_tool下，但编译后自然在window下也就没有了。

需求：
是否可以像dva一样提供一个获取实例的方法 import {getDvaApp} from 'umi' ，这样可以在更多场景中使用到useModel数据

**Comment by chenshuai2144** [comment]
hooks 是不能脱离上下文使用的，你可以用 事件系统来 试试触发 model 更新
