### ISSUE TITLE
菜单的颜色高亮状态不是主题色，而是黑色·

### ISSUE THREAD

**Issue by gtt011029** [ant-design/ant-design-pro#10763]
![2023-06-01_15-19](https://github.com/ant-design/ant-design-pro/assets/45391413/2851c1ae-4d46-4c53-9a86-8dbe78b4fa45)
[https://github.com/ant-design/ant-design-pro/issues/10595](url)

**Comment by ChenZiyi921** [comment]
大佬，这个问题解决了吗

**Comment by YuZongYangHi** [comment]
umi4的话，默认就是灰色的，你得自己得defaultSetting里面定义
