### ISSUE TITLE
🧐[问题 | question] 如何在protable的单元格中显示多张图片？

### ISSUE THREAD

**Issue by hernan2021** [ant-design/ant-design-pro#10760]
### 🧐 问题描述 | Problem description
目前 valuetype='image'时可以正常显示一张图片，目前需求是如何在一个单元格中显示多张图片？

### 🚑 其他信息 | Other information
![mmexport1685415540386](https://github.com/ant-design/ant-design-pro/assets/79294262/2a161659-d31f-4621-9897-400acab48dcd)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


在一个表格的单元格中显示多张图片可以通过以下步骤来实现：

1. 首先，确保你的表格使用了支持自定义内容的组件，比如antd的Table组件。

2. 在表格数据中，将每个单元格的图片数据存储为一个数组。

3. 在渲染表格的时候，使用自定义的render函数来渲染单元格的内容。

4. 在render函数中，遍历图片数组，并使用img标签来显示每张图片。

下面是一个简单的示例代码：

```jsx
import { Table } from 'antd';

const dataSource = [
  {
    key: '1',
    images: ['https://example.com/image1.jpg', 'https://example.com/image2.jpg'],
  },
  {
    key: '2',
    images: ['https://example.com/image3.jpg', 'https://example.com/image4.jpg'],
  },
];

const columns = [
  {
    title: 'Images',
    dataIndex: 'images',
    key: 'images',
    render: (images) => (
      <div>
        {images.map((url) => (
          <img src={url} alt="image" key={url} style={{ width: '100px', height: '100px' }} />
        ))}
      </div>
    ),
  },
];

const MyTable = () => {
  return <Table dataSource={dataSource} columns={columns} />;
};

export default MyTable;
```

在这个示例中，我们使用了antd的Table组件来渲染表格，数据源是一个包含了每个单元格图片数组的dataSource数组。在columns中，我们定义了一个名为"Images"的列，使用render函数来自定义该列的显示内容。在render函数中，我们遍历图片数组，并使用img标签来显示每张图片。

这样，你就可以在一个表格的单元格中显示多张图片了。
