### ISSUE TITLE
🐛 [BUG] 用官网 pro create myapp ，使用umi3模板创建的项目，菜单切换执行了两次

### ISSUE THREAD

**Issue by LoveRecall** [ant-design/ant-design-pro#10774]
复现步骤：
1、初始刷新在路由对应的组件里面console 执行了一次。
2、切换到另一个路由后执行了一次
3、当再次换到被选中过的路由菜单上时，就会执行两次
A->B ,B->A ,这时在A组件里打印就执行了两次

**Comment by 429299291** [comment]
你用的node什么版本?

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的问题描述，可以看出在使用官网 pro 创建的 umi3 项目中，菜单切换会执行两次，需要解决这个问题。

下面是解决这个问题的步骤：

1. 确认是否是路由配置问题：首先需要确认菜单切换执行两次是否是由于路由配置问题导致的。可以检查路由配置文件，如 `config.routes.js` 或 `config/config.js` 等，看是否有重复的路由或者路由配置错误的情况。

2. 检查菜单组件的逻辑：如果确认路由配置没有问题，可以检查菜单组件的逻辑。可能是菜单组件在切换时触发了多次事件，导致执行了多次。

3. 调试打印语句：可以在菜单组件和对应的路由组件中添加打印语句，用于跟踪执行过程。在切换菜单时，观察打印的日志，确定哪些地方触发了多次执行。

4. 检查生命周期方法：检查路由组件或者菜单组件中的生命周期方法，如 `componentDidMount`、`componentDidUpdate` 等，是否有重复执行的情况。如果有，可以调整逻辑保证只执行一次。

5. 使用 React DevTools 工具：使用 Chrome 浏览器的 React DevTools 插件，查看组件的更新情况，看是否有多次更新的问题。

6. 检查是否有重复的事件绑定：可能是由于在切换菜单时，多次绑定了相同的事件，导致多次执行。可以检查事件绑定的代码，确保只绑定一次。

7. 使用 Umi 和 Ant Design 官方社区支持：如果以上步骤还未解决问题，可以到 Umi 和 Ant Design 的官方社区寻求帮助。在社区中可以提出问题，并得到开发者的帮助和解答。

总结：根据提供的问题描述，我们可以按照上述步骤逐一排查问题，并修复引起菜单切换执行两次的原因。如果以上方法都无法解决问题，建议提供更多详细的代码和错误信息，以便更好地定位和解决问题。
