### ISSUE TITLE
🧐[问题 | question]想了解下 有没有基于antdpro使用AbortController取消请求的案例可以参考下

### ISSUE THREAD

**Issue by songjingyang** [ant-design/ant-design-pro#10779]
### 🧐 问题描述 | Problem description
因为服务端接口请求时间过长想在切换菜单的时候取消上个页面的未请求完成的请求，看了umi的request的方案，暂时没有思路实现取消请求的功能，希望官方大大可以提供一个思路或者一个可以参考的demo.

### 💻 示例代码 | Sample code
这个是umi提供的方案，不太懂怎么接入到antdpro .
![image](https://github.com/ant-design/ant-design-pro/assets/37998341/6a724ef5-f695-466f-b057-b9e11d1b5207)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


基于antdpro使用AbortController取消请求的案例，你可以按照以下步骤进行实现：

1. 在你的页面组件中引入`useEffect`和`useState`钩子函数，并创建一个`AbortController`的实例：

```javascript
import React, { useEffect, useState } from 'react';

const YourPageComponent = () => {
  const [controller, setController] = useState(new AbortController());

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch('your_api_url', {
          signal: controller.signal, // 将controller.signal作为请求的signal参数
        });
        const data = await response.json();
        // 处理返回的数据
      } catch (error) {
        // 处理错误
      }
    };

    fetchData();

    return () => {
      controller.abort(); // 在组件卸载之前取消请求
    };
  }, []);

  return (
    <div>
      {/* Your page content */}
    </div>
  );
};

export default YourPageComponent;
```

2. 通过使用`controller.signal`作为请求的`signal`参数，可以将`AbortController`实例与请求关联起来，然后在组件卸载之前取消请求。

这样，在切换菜单时，当页面组件被卸载时，请求会被取消。

希望以上解决方案能帮到你！如果还有其他问题，请随时提问。
