### ISSUE TITLE
🧐[问题 | question]项目跑起来之后，antd的样式没加载

### ISSUE THREAD

**Issue by Ding95** [ant-design/ant-design-pro#10776]
### 🧐 问题描述 | Problem description

使用的是ant-design-pro V5.0.0，yarn install，yarn dev一套下来，成功跑起项目，但是发现antd的样式没加载，导致输入框clear icon一直存在，table样式也是错乱的。经过一番折腾，发现只要改动`globlal.less`，触发`[HMR] Reload all css`，样式就正常了，不知道大家有遇到吗？感觉是首次run起来没有去加载antd样式文件。

### 💻 示例代码 | Sample code

```
<ProFormText
      name="userName"
      fieldProps={{
        size: 'large',
        prefix: <UserOutlined className={styles.prefixIcon} />,
      }}
      placeholder='用户名'
      rules={[
        {
          required: true,
          message: '用户名是必填项',
        },
      ]}
    />
```

```
<ProTable<API.RuleListItem, API.PageParams>
        headerTitle={'查询表格'}
        actionRef={actionRef}
        rowKey="key"
        search={{
          labelWidth: 120,
        }}
        toolBarRender={() => [
          <Button
            type="primary"
            key="primary"
            onClick={() => {
              handleModalVisible(true);
            }}
          >
            <PlusOutlined /> 新建
          </Button>,
        ]}
        request={rule}
        columns={columns}
        rowSelection={{
          onChange: (_, selectedRows) => {
            setSelectedRows(selectedRows);
          },
        }}
      />
```

### 🚑 其他信息 | Other information
<img width="551" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/12723947/fb126ae7-d2eb-49a4-a255-0599821b0b59">

<img width="1445" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/12723947/b155ed9f-dac7-4cd6-9948-464e1a4bb27a">

改动`globlal.less`，触发`[HMR] Reload all css`之后：

<img width="1454" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/12723947/8f186b6c-823a-46fe-9cde-8b213c02ee42">

OS: macOS 13.3.1

Node：v14.21.1

浏览器 | browser：Google Chrome 114.0.5735.106（正式版本） (x86_64)

**Comment by Ding95** [comment]
build出来是正常的，无奈在`app.jsx`里面加这行 `isDev ? import('antd/dist/antd.less') : null`

**Comment by chenshuai2144** [comment]
用 antd@5 就没问题拉，umi 的新版本关掉了  antd  样式的自动加载要手动打开
