### ISSUE TITLE
🐛 [BUG]初始化项目以后启动报错了

### ISSUE THREAD

**Issue by Pentium286** [ant-design/ant-design-pro#10777]
### 🐛 bug 描述

pro create myapp

npm run start 

然后就报错了

<img width="3002" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/1262247/178b7f27-97b4-4baf-add2-680e875b66df">

### 📷 复现步骤 | Recurrence steps

pro create myapp

npm run start 

然后就报错了

### 🏞 期望结果 | Expected results

运行不报错

### 💻 复现代码 | Recurrence code

pro create myapp

npm run start 

### © 版本信息

- Ant Design Pro 版本: [6.0.0]
- umi 版本 4.x
- 浏览器环境  114.0.5735.106
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
清空依赖，重新安装一下，antd  版本和 pro 版本不搭配了
