### ISSUE TITLE
🧐[问题 | question]路由配置中如何配置问号开头的传参？

### ISSUE THREAD

**Issue by lightman0215** [ant-design/ant-design-pro#10778]
### 🧐 问题描述 | Problem description

我在config中的routes.ts中定义如下的路由：

### 💻 示例代码 | Sample code
 path: '/repair/repair-list?pageNo=1&pageSize=10',
name: '维修单列表',
component: './repair/repair-list/repair-list',

我这样配置会导致直接404，无法访问，请问目前支持这样的方式配置路由么？

OS:Mac OS 13.4
Node：16.13.0
浏览器 | browser：Chrome 114

"@umijs/route-utils": "^2.2.2",
"antd": "^5.2.2",

**Comment by lovewinders** [comment]
path里不需要写?pageNo=1&pageSize=10

**Comment by lightman0215** [comment]
> path里不需要写?pageNo=1&pageSize=10

那请问改怎么配置，我点击菜单的时候需要以问号的形式传参，而不是/:pageNo这样的

**Comment by WuJiY** [comment]
?pageNo=1&pageSize=10 这个在接口里调用 不是在路由里配置

**Comment by lightman0215** [comment]
> ?pageNo=1&pageSize=10 这个在接口里调用 不是在路由里配置

参数我是需要从地址栏获取，接口里我知道可以定义这个参数，但这个URL的参数会根据业务变动的，pageSize可能是15，也可能是20，我默认点击这个菜单需要跳转到的页面的路由地址就需要是xxx?pageNum=1&pageSize=10这样的

**Comment by WuJiY** [comment]
这个需求有点奇怪，为啥分页根据路由来？

**Comment by WuJiY** [comment]
你不会是没点击分页。跳转路由吧？

**Comment by lightman0215** [comment]
> 你不会是没点击分页。跳转路由吧？

可能我没表达清楚，上面的参数我只是举了个例子，这个pageNum和pageSize可以换成其他的参数，我想实现点击菜单跳转路由的地址是xxx?参数1=1&参数2=2这样形式的，

**Comment by lovewinders** [comment]
还有antd pro 中的ProTable组件提供有syncToUrl高阶属性能自动把维度条件转换到url中

**Comment by lightman0215** [comment]
> 还有antd pro 中的ProTable组件提供有syncToUrl高阶属性能自动把维度条件转换到url中

我希望我左侧的菜单点击跳转的时候URL是repair/repair-list?参数1=1&参数2=2，而不是repair/repair-list/参数1/参数2这样的

**Comment by WuJiY** [comment]
菜单 就直接写 repair/repair-list?参数1=1&参数2=2 这样好了啊

**Comment by lightman0215** [comment]
> 菜单路由 就直接写 repair/repair-list?参数1=1&参数2=2 这样好了啊

我写了，但是点击会直接报404

**Comment by WuJiY** [comment]
哦 我懂你什么意思了

**Comment by lightman0215** [comment]
> 哦 我懂你什么意思了

这么写点击会报404
{
    path: '/repair',
    name: '维修单管理',
    icon: 'crown',
    routes: [
      {
        path: '/repair/repair-list?pageNum=1&pageSize=10',
        name: '维修单列表',
        component: './repair/repair-list/repair-list',
      },
    ],
  },

**Comment by WuJiY** [comment]
不懂你为啥要这样写？你想实现啥

**Comment by WuJiY** [comment]
> > 不懂你为啥要这样写？你想实现啥
> 
> 业务需要啊，有时候菜单肯定是需要传一些默认的参数的，/:id/:xx这样的可读性不好。。。

你这个是路由参数啊，你在项目中想要传参方式很多啊 history.push(path,{....})很多种啊。不明白为啥要在路由表里配置成这种形式

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


路由配置中不支持直接在路径中添加问号开头的传参。如果你想传递参数，可以通过动态路由的方式来进行配置。

首先，在路由配置文件routes.ts中，将路径定义为动态路由格式，使用冒号（:）来表示参数，例如：

```typescript
{
  path: '/repair/repair-list/:pageNo/:pageSize',
  name: '维修单列表',
  component: './repair/repair-list/repair-list',
}
```

然后，在组件中通过props获取传递的参数：

```typescript
import { useParams } from 'umi';

const RepairList = () => {
  const { pageNo, pageSize } = useParams();

  // 使用获取到的参数进行相应的逻辑处理

  return (
    // 组件的 JSX 内容
  );
};

export default RepairList;
```

这样配置后，你可以通过`/repair/repair-list/1/10`的方式来访问，并且在组件中获取到`pageNo`和`pageSize`这两个参数的值。

如果你想要在URL中去掉问号和等号，并且希望使用这样的格式`/repair/repair-list/pageNo1/pageSize10`，可以使用一些工具函数来进行转换处理，比如`querystring`模块。

```typescript
import { stringify } from 'querystring';

const params = {
  pageNo: 1,
  pageSize: 10,
};

const path = `/repair/repair-list/${stringify(params, '/')}`;

// path 的值为 '/repair/repair-list/pageNo1/pageSize10'
```

这样生成的路径就符合你的要求了。在访问该路径时，依然可以在组件中通过`useParams`来获取参数的值。

**Comment by xwqqq** [comment]
首先路由里不用管问号后面的
然后假如链接是xxxx?id=3&name=321
就用下面这个函数获取search参数
    const urlObj = new URL(location.href);
    const id = urlObj.searchParams.get('id');
    const name = urlObj.searchParams.get('name');
