### ISSUE TITLE
🧐[问题 | question]pro的动态主题

### ISSUE THREAD

**Issue by jaydonshi** [ant-design/ant-design-pro#10783]
### 🧐 问题描述 | Problem description

目前有需求需要在运行时动态改变系统主题。看了下pro的preview示例，修改主题的功能，提示“配置栏只在开发环境用于预览，生产环境不会展现，请拷贝后手动修改配置文件”。请问pro可以实现完全的运行时切换主题吗？另外ant design v5采用了新的 CSS-in-JS 动态主题，pro是否也会使用此方案实现动态主题？
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E5%9F%BA%E6%9C%AC%E7%AE%97%E6%B3%95algorithm

看这里
