### ISSUE TITLE
🧐[问题 | question] 运行时添加的菜单, 如何隐藏 [React Intl] Missing message: 消息错误

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design-pro#10789]

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题：运行时添加的菜单，如何隐藏 [React Intl] Missing message: 消息错误null 问题？

解决方案：
1. 检查是否已经正确导入 React Intl 的相关组件和方法。确保已经正确安装和引入了 `react-intl` 包，并使用了 `intlProvider` 组件包裹整个应用。

2. 使用 `injectIntl` 或者 `useIntl` 方法来获取当前语言环境的国际化信息，并进行格式化。

3. 在运行时添加菜单时，使用 `formatMessage` 方法来格式化菜单项的文本。确保传入正确的 `id` 和 `defaultMessage` 参数。

4. 如果仍然出现 `[React Intl] Missing message: 消息错误null` 的问题，可能是因为当前语言环境下没有为该菜单项的文本提供对应的翻译消息。可以通过以下方法解决：

   a. 在国际化资源文件中添加对应的翻译消息。

   b. 检查菜单项的 `id` 是否正确，并与资源文件中的键名保持一致。

   c. 检查菜单项的 `defaultMessage` 是否正确，并与资源文件中的默认消息保持一致。

   d. 如果菜单项的文本不需要翻译，可以直接在 `formatMessage` 方法中传入 `defaultMessage` 参数，而不是 `id` 参数。

   e. 如果菜单项的文本是可选的，可以在菜单项渲染时先判断是否存在该翻译消息，如果不存在则使用默认文本。

5. 如果以上步骤仍无法解决问题，可以使用 `FormattedMessage` 组件来直接渲染国际化文本，而不使用 `formatMessage` 方法。

通过以上步骤，应该可以解决 `[React Intl] Missing message: 消息错误null` 的问题，并正确显示运行时添加的菜单的国际化文本。

**Comment by chenshuai2144** [comment]
线上不会有的们可以直接忽略的
