### ISSUE TITLE
🐛 [BUG] pro create myapp失败!!!!

### ISSUE THREAD

**Issue by 429299291** [ant-design/ant-design-pro#10791]
### 🐛 bug 描述

npm i @ant-design/pro-cli -g
这是安装报错
![image](https://github.com/ant-design/ant-design-pro/assets/29189973/9c33122b-58c8-4836-beb4-0e2da2b3cb29)

pro create myapp
之后选择umi4就报错了,node是最新的版本,18.16.0
创建了一个myapp文件夹,但是里面是空的
![image](https://github.com/ant-design/ant-design-pro/assets/29189973/9e140ecc-3315-4c7c-95b6-835ed9c8a09c)

**Comment by YuZongYangHi** [comment]
内存不够了吧

**Comment by 429299291** [comment]
> 内存不够了吧
不可能吧,新电脑,M2,内存占用很少的

**Comment by flylan** [comment]
我也是被pro create myapp劝退，各种奇奇怪怪的错误，不过也是很佩服，一个前端项目引入的第三方包，加起来的体积比一个操作系统还要大，想当年jquery走天下的时候，也就几百k的事情，现在一个前端项目随便动不动就上10G，而且打包巨慢。最后出来的效果跟以前jquery做的也没多大区别

**Comment by 429299291** [comment]
解决了,不能用最新版的node18,我现在用的node16.20

**Comment by xielii** [comment]
> 解决了,不能用最新版的node18,我现在用的node16.20
您好，我切换到16以后依旧不可以
<img width="570" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/134837635/5e687d58-1bfd-43de-b1b5-aba2f196c44e">
能指点一下我吗，谢谢

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据描述的问题，可能存在以下解决方案：

1. 确保已安装了 `@ant-design/pro-cli` ，可以尝试重新安装一次：
   ```bash
   npm i @ant-design/pro-cli -g
   ```

2. 如果仍然无法安装成功，可以查看安装报错的具体信息，可能是由于网络问题无法下载相关依赖。可以尝试添加 `--registry` 参数指定镜像源：
   ```bash
   npm i @ant-design/pro-cli -g --registry=https://registry.npm.taobao.org
   ```

3. 如果在使用 `pro create myapp` 创建项目时报错，可能是因为 `umi` 版本不兼容导致的。可以尝试选择使用 `umi@3` 版本：
   ```bash
   pro create myapp
   ? 🐂 使用 umi@4 还是 umi@3 ? (Use arrow keys)
   ❯ umi@3
     umi@4
   ```
   > 注意，选择 `umi@3` 版本后，可能无法使用全量区块。

4. 如果在选择完 `umi` 版本后，创建的 `myapp` 文件夹为空，可能是由于某些原因导致项目初始化中断。解决方案是手动进入 `myapp` 文件夹，并安装依赖：
   ```bash
   cd myapp
   tyarn
   # 或
   npm install
   ```

如果以上解决方案仍然无法解决问题，建议进一步查看错误提示并提供详细的错误信息以便定位问题。
