### ISSUE TITLE
安装umi4版本的项目，无法运行🐛 [BUG]

### ISSUE THREAD

**Issue by eightZone** [ant-design/ant-design-pro#10798]
### 🐛 bug 描述

拉取的新项目，启动报错。
### 📷 复现步骤 | Recurrence steps
![1686900935269](https://github.com/ant-design/ant-design-pro/assets/59357340/cef08a68-f134-46be-b2a3-f23672e3e475)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


升级到Umi 4版本的项目需要进行以下步骤：

1. 依赖处理：
   - 首先，需要将项目中的依赖升级到Umi 4版本支持的最新版本。可参考Umi的官方文档或GitHub上的changelog来查看最新版本，然后在项目的package.json文件中更新相关依赖的版本号。
   - 可使用以下命令升级依赖：
     ```
     npm install umi@4 --save-dev
     ```
   - 也可以使用yarn进行依赖安装：
     ```
     yarn add umi@4 --dev
     ```

2. 启动命令：
   - 在package.json中修改启动命令，将旧版本的umi命令修改为umi-4：
     ```
     "scripts": {
       "start": "umi-4 dev",
       ...
     }
     ```

3. 非官方插件升级：
   - 对于项目中使用的非官方插件，需要查看它们是否支持Umi 4版本，并进行相应的升级。可参考插件的官方文档或GitHub上的changelog来查看最新版本。

4. 配置层迁移：
   - Umi 4版本引入了新的配置层，需要将旧版本的配置迁移到新的配置层中。可参考Umi官方文档中的配置指南，逐项将配置内容从旧版本迁移至新版本。

5. 代码层修改：
   - 根据Umi 4版本的变化，可能需要在项目代码中进行一些修改以适应新版本的Umi。例如，修改路由配置、修改页面布局等。可参考Umi官方文档中的升级指南和示例代码进行相应修改。

完成以上步骤后，运行启动命令，即可运行升级后的Umi 4项目。如果还有报错，可以将报错信息提供出来，以便更好地帮助解决问题。
