### ISSUE TITLE
🧐[问题 | question]  5.0版本 主题只有亮色 和暗黑色吗 我想新增其他主题色应该在哪里设置

### ISSUE THREAD

**Issue by mattsmad1** [ant-design/ant-design-pro#10795]
主题只有亮色 和暗黑色吗 我想新增其他主题色应该在哪里设置

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，您想在Ant Design 5.0版本中新增其他主题色。在Ant Design 5.0中，您可以采用全新的定制主题方案来实现这个需求。以下是解决方案的步骤：

1. 创建一个新的主题文件。您可以在项目的根目录下创建一个名为`theme.js`（或者其他你喜欢的名字）的文件。

2. 在`theme.js`文件中导入Ant Design的主题变量，这些变量将用于定制主题。您可以通过以下方式导入主题变量：

   ```jsx
   import { generate } from '@ant-design/colors';
   import { createTheme } from '@ant-design/theme';
   ```

3. 使用`generate`函数生成新的主题变量。您可以根据需求生成新的主题色，例如：

   ```jsx
   const primaryColor = '#1890ff'; // 自定义主题色
   const themeVars = {
     // 使用generate函数生成新的主题变量
     ...createTheme(generate(primaryColor)),
   };
   ```

4. 将生成的主题变量应用到Ant Design组件中。您可以使用`ThemeProvider`组件将主题变量传递给Ant Design的组件树：

   ```jsx
   import { ThemeProvider } from '@emotion/react';

   function App() {
     return (
       <ThemeProvider theme={themeVars}>
         {/* 在这里编写您的组件 */}
       </ThemeProvider>
     );
   }
   ```

   您可以将`ThemeProvider`组件放在您的应用程序的根组件中，以确保整个应用程序都使用新的主题变量。

5. 使用新的主题色。现在您可以在您的组件中使用新的主题色。例如，您可以在Ant Design的组件上使用新的主题变量：

   ```jsx
   import { Button } from 'antd';

   function MyComponent() {
     return (
       <Button type="primary">使用新的主题色</Button>
     );
   }
   ```

通过以上步骤，您可以在Ant Design 5.0中新增其他主题色。请注意，这只是一个基本的示例，您可以根据您的需求进行定制和扩展。
