### ISSUE TITLE
🐛 [BUG]使用  pro create myapp 基于umijs3 创建 控制台一堆报错

### ISSUE THREAD

**Issue by wellsmitch** [ant-design/ant-design-pro#10790]
![1686823002228 - 副本](https://github.com/ant-design/ant-design-pro/assets/42932079/7bd27483-51ff-4a1d-ae20-6507891b9859)
创建出来的项目antd用4.24.10但是实际你集成的时候为什么要用<4.24.0 的版本呢 ，并且package.json中一旦把"antd": "^4.19.5"改为"antd": "~4.19.5"侧边菜单直接就不出来了。这是怎么回事，建议官网出一个pro的集成原理图及资源的依赖关系图

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


从问题描述来看，报错是在创建 umi 项目时出现的，而且还涉及到对 antd 版本的选择和侧边菜单无法显示的问题。解决方案如下：

1. 确认使用的 umi 版本：根据问题描述中的情况，你使用了 umijs3 来创建项目。这是一个比较旧的版本，可能存在一些兼容性问题。建议尝试使用 umi@4 版本来创建项目，执行以下命令：
  
   ```bash
   pro create myapp
   ```

   在选择 umi 版本时，选择 umi@4。

2. 检查 antd 版本：创建的项目中使用的是 antd@4.24.10 版本，但在集成时建议使用小于4.24.0的版本。这可能是因为在该版本之后，antd 的某些变化导致与你的代码不兼容。你可以将项目中的 antd 版本修改为较低的版本，例如"antd": "~4.19.5"。

   进入项目目录，并打开 package.json 文件，在 dependencies 中找到 "antd" 的依赖项，并将版本号修改为 "~4.19.5"。

   ```json
   "dependencies": {
     // ...
     "antd": "~4.19.5"
     // ...
   }
   ```

   保存文件后，重新安装项目的依赖：

   ```shell
   tyarn
   # 或
   npm install
   ```

3. 侧边菜单无法显示的问题：修改 antd 版本后，你提到的侧边菜单不显示的问题可能是因为 antd 的样式文件没有正确加载。在 umijs 项目中，通常需要在入口文件中引入 antd 的样式文件。请检查入口文件（通常是 src/app.js 或 src/app.tsx）中是否引入了 antd 的样式文件，例如：

   ```javascript
   // src/app.js

   import 'antd/dist/antd.css';
   ```

   如果没有找到这一行代码，请添加上述代码，并重新运行项目，确认是否解决了侧边菜单不显示的问题。

4. 关于 Pro 的集成原理图和资源依赖关系图：你提到了官方出一个 pro 的集成原理图和资源依赖关系图的建议。在 Pro 的官方文档中，有关于项目结构和配置的相关说明，你可以参考这些文档来理解 Pro 的集成原理和依赖关系。此外，你还可以参考 Umi 的官方文档和 antd 的官方文档来深入了解它们的使用和原理。

希望以上解决方案能帮到你解决问题。如果还有其他疑问，请继续追问。
