### ISSUE TITLE
更改主题颜色 为什么 路由菜单的颜色不会跟着主题色变了 是bug吗 还是需要调整哪里

### ISSUE THREAD

**Issue by mattsmad1** [ant-design/ant-design-pro#10796]
更改主题颜色 为什么 路由菜单的颜色不会跟着主题色变了 是bug吗 还是需要调整哪里  目前一直是灰色的

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决方案如下：

1. 使用 CSS 变量定义主题颜色。在根元素上定义全局的 CSS 变量，例如：`--primary-color: #1890ff;`，其中`primary-color`可以根据自己的需求进行定义。

2. 使用 CSS-in-JS 技术来动态修改主题颜色。通过在组件中使用 CSS-in-JS 库（例如 styled-components），可以将 CSS 属性设置为 CSS 变量，并通过修改根元素的 CSS 变量值来实现主题色的动态修改。例如：

```jsx
import styled from 'styled-components';

const Wrapper = styled.div`
  background-color: var(--primary-color);
`;
```

3. 在路由菜单组件中使用动态主题色。如果路由菜单的样式是通过 CSS 类来定义的，可以将 CSS 类的样式设置为使用 CSS 变量，例如：

```jsx
import styles from './Menu.module.css';

const Menu = () => {
  return (
    <ul className={styles.menu}>
      <li className={styles.item}>Item 1</li>
      <li className={styles.item}>Item 2</li>
      <li className={styles.item}>Item 3</li>
    </ul>
  );
};
```

```css
/* Menu.module.css */
.menu {
  background-color: var(--primary-color);
}

.item {
  color: var(--primary-color);
}
```

这样，当主题色变化时，路由菜单的样式也会跟着变化。

4. 调整antd样式主题。如果使用了 antd 组件库，可以使用 antd 提供的自定义主题能力来修改组件的样式。具体步骤如下：

   - 创建一个自定义主题文件（例如 `theme.less`），并在其中定义需要修改的样式变量，例如：

     ```less
     @primary-color: #1890ff;
     ```

   - 在应用的入口文件中引入自定义主题文件，例如：

     ```jsx
     // index.js
     import 'antd/dist/antd.less'; // 引入 antd 全局样式
     import './theme.less'; // 引入自定义主题文件
     ```

   - 执行 `npm` 或 `yarn` 命令重新编译应用，使自定义主题生效。

这样，使用了 antd 组件的路由菜单样式也会跟着主题色的变化而改变。

通过以上步骤，可以实现动态修改主题颜色，并使路由菜单的样式跟随主题色的变化。如果路由菜单的颜色仍然不会跟着主题色变化，可以检查是否正确地应用了主题色的样式和是否正确设置了使用主题色的变量。如果仍然存在问题，可能需要进一步调试并查看是否有其他样式覆盖了主题色的样式。
