### ISSUE TITLE
🧐[问题 | question]设置菜单国际化locale为false后仍然有报错提示

### ISSUE THREAD

**Issue by lightman0215** [ant-design/ant-design-pro#10800]
### 🧐 问题描述 | Problem description

我在config.ts里打开了国际化的配置，然后在defaultSetting.ts里设置了menu:{locale:false}，但为什么控制台还是会有这样的提示

或者说我关闭国际化，可以让datepicker这些组件正常显示中文，我尝试过关闭国际化，会导致datepicker显示成中英文混在一起的情况
[![pCl9K61.png](https://s1.ax1x.com/2023/06/17/pCl9K61.png)](https://imgse.com/i/pCl9K61)

### 💻 示例代码 | Sample code
[![pClCmE8.png](https://s1.ax1x.com/2023/06/17/pClCmE8.png)](https://imgse.com/i/pClCmE8)
[![pClCi3d.png](https://s1.ax1x.com/2023/06/17/pClCi3d.png)](https://imgse.com/i/pClCi3d)

OS:
Mac OS 13.4
Node：
18.16.0
umi 4
antd 5.6.1
浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据您的问题描述，您想要关闭菜单的国际化配置，但是在控制台仍然会有报错提示。您尝试关闭国际化配置后，发现`DatePicker`等组件显示成了中英文混在一起的情况。

首先，关于关闭菜单的国际化配置，您需要在`defaultSetting.ts`文件中设置`locale: false`，这样可以关闭菜单的国际化配置。

然而，关闭国际化配置后，一些组件（如`DatePicker`）可能仍然显示成中英文混在一起的情况。这是因为`Ant Design`的组件库中的一些组件默认会根据当前系统的语言环境进行国际化处理。为了解决这个问题，您可以通过以下两种方式之一来处理：

1. 使用`antd`提供的国际化配置。您可以在`app.ts`中使用`localeProvider`组件，并传入一个`antd`支持的语言包对象，以覆盖默认的语言环境。

```tsx
import { ConfigProvider } from 'antd';
import zhCN from 'antd/lib/locale/zh_CN'; // 引入中文语言包

export function rootContainer(container: React.ReactNode) {
  return React.createElement(ConfigProvider, { locale: zhCN }, container);
}
```

2. 自定义日期选择器的语言配置。您可以引入`moment.js`库，并在`app.ts`中设置`moment`的全局语言配置。然后，在使用`DatePicker`组件时，设置`locale`属性为`moment`实例。

```tsx
import moment from 'moment';
import 'moment/locale/zh-cn'; // 引入中文语言包

moment.locale('zh-cn'); // 设置全局的 moment 语言配置

// 在使用 DatePicker 组件时，设置 locale 属性为 moment 实例
<DatePicker locale={moment.localeData()} />
```

通过以上两种方式之一，您可以在关闭菜单的国际化配置的同时，正常显示中文的日期选择器等组件。

希望以上解决方案能帮助到您！如果还有其他问题，请随时提问。
