### ISSUE TITLE
🐛 [BUG]jest问题

### ISSUE THREAD

**Issue by 2Hq1** [ant-design/ant-design-pro#10803]
修改完 es2022后

继续执行npm run i18n-remove 后
Error: Failed to load plugin 'jest' declared in 'BaseConfig': Class extends value undefined is not a constructor or null 
    at Object.<anonymous>

![image](https://github.com/ant-design/ant-design-pro/assets/99543012/3b69a282-a19a-4025-9625-a9bde2434e89)

**Comment by nhilove** [comment]
npm i --save-dev eslint eslint-plugin-jest 
试一下看看能不能解决

**Comment by liangxiaowucai** [comment]
一样的问题，惆怅

**Comment by dianfengchen** [comment]
> 修改完 es2022后
> 
> 继续执行npm run i18n-remove 后 Error: Failed to load plugin 'jest' declared in 'BaseConfig': Class extends value undefined is not a constructor or null 错误：无法加载在“BaseConfig”中声明的插件“jest”：类扩展值未定义不是构造函数或 null at Object.  在对象。
> 
> ![image](https://private-user-images.githubusercontent.com/99543012/246660984-3b69a282-a19a-4025-9625-a9bde2434e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjAzNTYsIm5iZiI6MTcwMzMyMDA1NiwicGF0aCI6Ii85OTU0MzAxMi8yNDY2NjA5ODQtM2I2OWEyODItYTE5YS00MDI1LTk2MjUtYTliZGUyNDM0ZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA4MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MWFjZDM3OTc4ODI3ZTFlZGIxZGFhYzczYjBjZDVjNDc3OTJlZjgwZTc5NjAyOTY3MWRiZjY5MzI5YTQ1MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jWZuTwRlSSnvfmkt6t-40jcDHUyE6dK6FuHK48biU_k)

你好，请问解决了吗，我现在也是遇见了这个问题

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的问题描述，分析可能的解决方案如下：

1. 首先，我们需要检查项目的依赖是否正确安装，可以执行 `npm install` 或者 `yarn` 来重新安装项目依赖。

2. 如果依赖已经正确安装，那么可能是 jest 相关的配置问题。我们可以尝试以下步骤来解决：

   - 确保项目中已经正确配置 jest，可以检查 `package.json` 文件中的 `jest` 字段，确保配置正确。

   - 如果 jest 配置正确，那么可能是由于 babel 转译的问题导致的错误。可以检查项目中的 babel 配置文件（如 `.babelrc`、`babel.config.js`）是否正确配置了对 ES2022 语法的转译。

       - 如果没有配置，可以尝试添加对 ES2022 的转译规则，例如使用 `@babel/preset-env` 中的 `es2022` 预设。
   
   - 确保项目的依赖版本兼容，特别是与 jest 相关的依赖。可以检查项目中的 `package.json` 文件，查看 jest 相关的依赖是否有冲突或者版本不兼容的情况，尝试更新或降级依赖版本。

   - 如果以上步骤都没有解决问题，可以考虑升级或更换 jest 版本，并重新配置项目。

3. 如果以上步骤都没有解决问题，可以参考 jest 的官方文档或社区中的类似问题来获取更多帮助。也可以将详细的错误信息和项目配置信息提供给 jest 的开发者社区，寻求更专业的帮助。

总结起来，解决此问题的关键是确保项目依赖正确安装，并正确配置 jest 相关的配置文件和babel转译规则。如果问题仍然存在，可以尝试更新或更换依赖版本，并寻求更专业的帮助。

**Comment by yinxiangzhao** [comment]
> npm i --save-dev eslint eslint-plugin-jest 试一下看看能不能解决

按照这个操作，解决问题了，感谢！
