### ISSUE TITLE
能否支持360浏览器的兼容模式？（360极速模式已支持）

### ISSUE THREAD

**Issue by vison20080808** [ant-design/ant-design-pro#1080]
rt~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro#compatibility

**Comment by vison20080808** [comment]
360浏览器不在“Modern browsers and IE11. ”之列吗？很多企业内部使用

**Comment by afc163** [comment]
不了解 360 浏览器的兼容模式，但是只要是 IE11 应该支持的我们都会予以支持。

**Comment by vison20080808** [comment]
谢谢，但是360浏览器默认就是使用兼容模式的，打开https://pro.ant.design/index-cn，内容加载不出来，一片空白。。。挺影响使用的

**Comment by chenshuai2144** [comment]
360的ie内核和你系统有关系。你看看你的ie版本。
