### ISSUE TITLE
🧐[问题 | question] V6 (umi4)，选择语言的菜单上的图标如何删除？

### ISSUE THREAD

**Issue by mendellin** [ant-design/ant-design-pro#10805]
### 🧐 问题描述 | Problem description

如图所示，需要隐藏或不显示这个图标，要如何实现？谢谢
ant design pro v6 (umi4)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：
![image](https://github.com/ant-design/ant-design-pro/assets/5884945/4e5be2d0-7b1c-4585-9cf3-154a3190f4a5)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


要删除选择语言菜单上的图标，可以按照以下步骤进行操作：

1. 打开项目中的 `src/locales/zh-CN/menu.ts` 文件。

2. 找到对应的菜单项，一般是 `menu.lang` 或 `menu.locale`。

3. 在该菜单项中，将图标字段设为 `null` 或空字符串。

   例如，假设原先的代码是：
   ```javascript
   {
     key: 'lang',
     title: '多语言',
     icon: 'icon:global',
     ...
   }
   ```
   修改后的代码可以是：
   ```javascript
   {
     key: 'lang',
     title: '多语言',
     icon: '',
     ...
   }
   ```
   或者：
   ```javascript
   {
     key: 'lang',
     title: '多语言',
     icon: null,
     ...
   }
   ```

4. 重新编译和启动项目，查看选择语言菜单，图标应该已经被删除了。

请注意，该解决方案适用于基于 Ant Design Pro V6 (umi4) 的项目。如果你使用的是其他版本或框架，请参考相应的文档或官方指南进行操作。此外，如果你使用了自定义图标，可能需要进行额外的修改或配置。

**Comment by mendellin** [comment]
thanks a lot 发自我的华为手机-------- 原始邮件 --------发件人： 陈帅 ***@***.***>日期： 2024年1月3日周三 下午2:45收件人： ant-design/ant-design-pro ***@***.***>抄送： Taishan ***@***.***>, Author ***@***.***>主    题： Re: [ant-design/ant-design-pro] 🧐[问题 | question] V6 (umi4)，选择语言的菜单上的图标如何删除？ (Issue #10805)

值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令

要删除选择语言菜单上的图标，可以按照以下步骤进行操作：

打开项目中的 src/locales/zh-CN/menu.ts 文件。

找到对应的菜单项，一般是 menu.lang 或 menu.locale。

在该菜单项中，将图标字段设为 null 或空字符串。
例如，假设原先的代码是：
{
  key: 'lang',
  title: '多语言',
  icon: 'icon:global',
  ...
}
修改后的代码可以是：
{
  key: 'lang',
  title: '多语言',
  icon: '',
  ...
}
或者：
{
  key: 'lang',
  title: '多语言',
  icon: null,
  ...
}

重新编译和启动项目，查看选择语言菜单，图标应该已经被删除了。

请注意，该解决方案适用于基于 Ant Design Pro V6 (umi4) 的项目。如果你使用的是其他版本或框架，请参考相应的文档或官方指南进行操作。此外，如果你使用了自定义图标，可能需要进行额外的修改或配置。
