### ISSUE TITLE
🧐[问题 | question] V5 主题 我这边添加了许多组件如何将新增的组件也适配上 主题样式变化，只能通过useEmotionCss 一个一个写className 匹配上主题变化，但是这样太麻烦，是否有公共的办法解决

### ISSUE THREAD

**Issue by mattsmad1** [ant-design/ant-design-pro#10817]
### 🧐 问题描述 | Problem description
🧐[问题 | question] V5 主题 我这边添加了许多组件如何将新增的组件也适配上 主题样式变化，只能通过useEmotionCss 一个一个写className 匹配上主题变化，但是这样太麻烦，是否有公共的办法解决

**Comment by arvinxx** [comment]
https://github.com/ant-design/antd-style
