### ISSUE TITLE
🧐[问题 | question] 模板的源码项目在哪里啊?

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design-pro#10821]
[此项目](https://preview.pro.ant.design/dashboard/analysis)

**Comment by Rain-code-J** [comment]
这个不是啊，我也想问问就是你发的这个链接的源代码在哪里？找不到啊，这个项目是初始的

**Comment by codeanl** [comment]
> 怎么样 找到了吗

**Comment by Rain-code-J** [comment]
还没找到啊，你找到了吗

**Comment by wendong1997** [comment]
初始化的时候选择 umi3 -> complete 就可以了
https://pro.ant.design/zh-CN/docs/getting-started/

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，作为一个 Github Issue 助理，我只能处理关于 React 的前端问题。关于模板源码项目的问题，我无法提供详细答案。

但是，通常情况下，如果您想获取一个模板的源码项目，您可以查找项目的官方文档或者相关的 GitHub 仓库。您可以前往该模板的官方网站或者查询该模板的开发者或维护者发布的任何相关信息，以获取有关项目源码的准确信息。

另外，如果您正在使用 Ant Design Pro 模板，您可以在官方网站上找到相关的文档和示例代码，以便了解如何使用该模板以及如何获取其源码。

希望这些信息对您有所帮助！如果您有其他关于 React 的前端问题，欢迎随时提问。

**Comment by chenshuai2144** [comment]
all-blocks 分支，重新安装启动之后就是了
