### ISSUE TITLE
🧐[问题 | question] 如何切换两个菜单列表? 

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design-pro#10820]
<img width="1119" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/124666577/20e9677a-f5b7-4c1e-9b8f-cab490adf7e2">

我有两个菜单列表需要切换展示,请问支持吗?  如何实现呢?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢你的问题。

如果你希望在 React 中切换两个菜单列表的展示，可以通过状态管理的方式来实现。

首先，你需要在你的组件中定义一个状态来表示当前展示的菜单列表。你可以使用 `useState` 钩子来创建这个状态。

例如：

```jsx
import React, { useState } from 'react';

function MenuSwitcher() {
  const [showMenu1, setShowMenu1] = useState(true);

  return (
    <div>
      <button onClick={() => setShowMenu1(true)}>菜单1</button>
      <button onClick={() => setShowMenu1(false)}>菜单2</button>

      {showMenu1 ? (
        // 菜单1的内容
        <ul>
          <li>菜单项1</li>
          <li>菜单项2</li>
          <li>菜单项3</li>
        </ul>
      ) : (
        // 菜单2的内容
        <ul>
          <li>菜单项4</li>
          <li>菜单项5</li>
          <li>菜单项6</li>
        </ul>
      )}
      
      {/* 其他组件内容 */}
    </div>
  );
}
```

在这个例子中，我们使用了 `useState` 钩子创建了一个名为 `showMenu1` 的状态，并初始化为 `true`。点击按钮时，通过调用 `setShowMenu1` 函数来更新这个状态，从而实现切换菜单的功能。

根据 `showMenu1` 的值，我们在 JSX 中动态渲染不同的菜单内容，这样就能达到切换展示的效果。

以上仅为简单示例，请根据你的实际需求来调整代码。

同时，你可能会需要使用 CSS 来美化菜单的样式。你可以添加自定义的 CSS 类名，并在 CSS 文件中进行样式定义。

希望以上能帮到你！如果还有其他问题，请随时提问。
