### ISSUE TITLE
🐛 [BUG] 能不引入ProComponents这个组件依赖吗？ 只使用ant-design， 因为ProComponents这个组件库bug太多了，不稳定

### ISSUE THREAD

**Issue by pc110** [ant-design/ant-design-pro#10825]
能不引入ProComponents这个组件依赖吗？ 只使用ant-design， 因为ProComponents这个组件库bug太多了，非常不稳定。

**Comment by echoyl** [comment]
这个项目就是基于ProComponents

**Comment by davidhsing** [comment]
那你就基于 ant design 去做项目，别选用 Pro 就行了。
ant design pro 本来就是 ant design + Pro Components + UMI，去掉了你说会咋样。。。

**Comment by kaneruan** [comment]
pro components bug 真的很多，源码也是花里胡哨的，想改也改不动
