### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by 4amramen** [ant-design/ant-design-pro#10828]
### 🐛 bug 描述

Ant Design Pro with Umi3 no longer compiles.  Upon yarn install, and yarn start, it fails with @babel/helper-compilation-targets: 'opera_mobile' is not a valid target.   This has made our company's production app that we built off of the antd uim3 template unable to build anymore.

```
ERROR in ./src/components/index.md
Module build failed (from ./node_modules/@umijs/preset-dumi/lib/loader/index.js):
Error: [BABEL] /Users/ramesh/my-directory/myapp/src/components/index.tsx: @babel/helper-compilation-targets: 'opera_mobile' is not a valid target
- Did you mean 'opera'? (While processing: "/Users/my-directory/myapp/node_modules/@umijs/babel-preset-umi/app.js$0$0$39")
``` 

### 📷 复现步骤 | Recurrence steps

```
npm i @ant-design/pro-cli -g
pro create myapp
``` 

Select use umi@3

```
yarn install
yarn start
``` 

### 🏞 期望结果 | Expected results

Should have compiled and host at localhost:8000

### 💻 复现代码 | Recurrence code
<img width="1242" alt="Screen Shot 2023-07-04 at 6 09 37 PM" src="https://github.com/ant-design/ant-design-pro/assets/42975030/a64bb3d2-f729-4e0e-ac4a-0424ad2f0472">

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by braveblack** [comment]
这个问题解决了吗？

**Comment by whuwangyong** [comment]
> [把src/components/index.md 内容清空就可以了](https://github.com/umijs/dumi/issues/1766)

有用，感谢。另，nodejs不要装太新的版本，我用的16.20.1。

**Comment by fengshenhai-0727** [comment]
清空md文件在哪写
