### ISSUE TITLE
AntdProV6 怎么在本地routes.js  access字段不配置的情况 默认访问403呢？🧐[问题 | question]

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/ant-design-pro#10832]
### 🧐 问题描述 | Problem description
<img width="551" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/52319042/72c8297c-b3c6-429f-b0e5-270cbb3972e8">

菜单是通过后端接口获取。
如果本地routes.js 里面配置了对某个路由access字段。访问无权限的路由 则会自动渲染403页面。

那么我这边没配置access字段情况下在url上随便输入一个没有权限的路由 则是渲染空白页面不会渲染403。
![image](https://github.com/ant-design/ant-design-pro/assets/52319042/19bbc92e-665b-4a2a-ab51-6d1eef96befe)

请问这边403页面渲染的话必须要在本地routes里面添加吗？ 还是说有其他的配置项？

### 🚑 其他信息 | Other information

Node：V16+

浏览器 | browser：Google

**Comment by TangDeYu** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的描述，你想知道如何在本地的routes.js文件中，当未配置access字段时，默认访问返回403页面。

根据Ant Design Pro V6的文档，你可以通过以下两种方式来实现这个需求：

**方式一：使用约定的路由权限配置**

确保你的路由配置对象中的每个路由都包含一个名为access的字段。当你不希望某个路由被访问时，将access字段设置为false。

在你的routes.js文件中，可以这样配置：

```javascript
const routes = [
  {
    path: '/',
    component: '@/layouts/BasicLayout',
    routes: [
      {
        path: '/dashboard',
        component: '@/pages/Dashboard',
        access: 'canAccessDashboard', // 设置访问权限为true/false
      },
      // 其他路由配置...
    ],
  },
  // 其他配置...
];

export default routes;
```

当用户尝试访问未配置access字段的路由时，Ant Design Pro V6将默认渲染403页面。

**方式二：自定义权限控制**

如果你希望自定义权限逻辑，你可以在路由配置中使用authority字段，并在一个authority.js文件中编写自定义的权限控制逻辑。

在你的routes.js文件中，可以这样配置：

```javascript
import { check } from '@/authority';

const routes = [
  {
    path: '/',
    component: '@/layouts/BasicLayout',
    routes: [
      {
        path: '/dashboard',
        component: '@/pages/Dashboard',
        authority: ['admin'], // 自定义权限控制
      },
      // 其他路由配置...
    ],
  },
  // 其他配置...
];

export default routes;
```

然后，在authority.js文件中，你可以编写自定义的权限判断逻辑，例如：

```javascript
export function check(authority) {
  // 根据自己的业务逻辑判断权限
  const currentUser = getCurrentUser(); // 获取当前用户信息的函数，你需要根据具体情况实现

  if (currentUser.role === 'admin' && authority.includes('admin')) {
    return true;
  }

  return false;
}
```

当用户尝试访问某个路由时，Ant Design Pro V6将根据你自定义的权限逻辑进行判断，并决定是否渲染403页面。

这些是两种常见的实现方式，你可以根据具体需求选择适合你的方式。

希望对你有所帮助！如果你有任何疑问，请随时问我。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🎯 解决方案 | Solution

在 Antd Pro V6 中，默认情况下，访问一个没有权限的路由时，会渲染空白页面而不是403页面。如果你想要渲染403页面，你需要在本地的 `config/config.js` 文件中进行相应的配置。

首先，打开 `config/config.js` 文件，找到 `ssr` 配置项。这个配置项用于定义路由鉴权的功能。

然后，在 `ssr` 配置项下，添加一个 `noMatch` 属性，并设置其值为 `true`。这样，当访问没有权限的路由时，会自动渲染403页面。

以下是一个示例的 `config.js` 文件：

```javascript
export default {
  ssr: {
    // ...

    // 渲染403页面的配置
    noMatch: true,

    // ...
  },
};
```

请确保你的 Antd Pro V6 版本兼容该配置项。如果你使用的是旧版本，可能需要升级到支持该配置项的版本。可以参考 Antd Pro V6 的文档或查看相关的 GitHub 项目页面，以获取更多关于该配置项的信息和版本要求。

在配置完之后，重新启动你的应用程序，再次尝试访问没有权限的路由，应该会渲染403页面了。

希望这个解决方案能帮助到你！如果你还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
Antd Pro V6在本地的routes.js文件中，默认会渲染一个403页面来展示没有权限的路由。如果你想自定义403页面或者配置其他权限相关的操作，可以按照下面的步骤进行配置：

1. 在`src/app.ts`文件中，通过全局初始化信息来请求权限相关的初始化信息。具体可以参考文档中的示例代码，在`getInitialState`函数中请求并返回权限相关的数据。

2. 新增一个`src/access.ts`文件，用来定义权限。在该文件中，根据全局初始化信息（通过`InitialState`参数传入）来确定用户是否有权限访问某些路由。例如，你可以根据用户的身份或其他条件来判断是否具有读取文章
