### ISSUE TITLE
全局按钮点击后出现巨大边框🧐[问题 | question]

### ISSUE THREAD

**Issue by unStarCN** [ant-design/ant-design-pro#10839]
### 🧐 问题描述 | Problem description

今天编译时突然就这样, 重新运行也是一样, 没改样式代码, 不止出现一次了, 只要是一个按钮点击后都会出现, 侧边栏也会有
那个淡蓝色边框
### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/78009357/fc49d705-e446-4d11-b957-2732b0c9b676)
![image](https://github.com/ant-design/ant-design-pro/assets/78009357/e8ffd58d-45fc-414e-88f3-04508551e29a)

OS:

Node：

浏览器 | browser：谷歌浏览器

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 回答 | Answer

根据你提供的信息，这个问题可能是由于浏览器的默认样式引起的。当你点击按钮时，浏览器会给被点击的元素添加一个默认的焦点样式，这可能是为了提醒用户当前的焦点所在位置。

为了解决这个问题，你可以通过设置一些 CSS 样式来覆盖浏览器的默认样式。下面是一个可能的解决方案：

```css
button:focus,
a:focus {
  outline: none;
}
```

这样，当按钮被点击时，焦点样式就会被移除，不再显示巨大的边框。

如果你使用的是 React 框架，你可以将上述样式添加到你的全局样式表中，或者直接在你的组件中引入。

另外，如果你想添加自定义的焦点样式，你可以使用 box-shadow 属性来为按钮添加一个更细的边框，如下所示：

```css
button:focus,
a:focus {
  outline: none;
  box-shadow: 0 0 2px 2px #blue;
}
```

这样，当按钮被点击时，会显示一个细边框并保留焦点效果。

希望这些解决方案能对你有所帮助。如果问题仍然存在，请提供更多的代码和信息，以便我们能够更好地帮助你解决问题。另外，你也可以查阅浏览器文档以了解更多关于焦点样式的信息：

- [MDN 文档 - :focus 伪类](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:focus)
- [MDN 文档 - outline 样式](https://developer.mozilla.org/zh-CN/docs/Web/CSS/outline)

**Comment by chenshuai2144** [comment]
这个问题可能是由于你的样式代码中添加了不正确的样式导致的。为了解决这个问题，你可以尝试以下几个步骤：

1. 首先，确保你的样式代码中没有添加任何额外的边框样式。可能是你的代码中某个地方使用了 `border` 属性或者其他类似的属性导致了边框出现。

2. 如果你使用了某个 CSS 框架或者样式库，例如 Ant Design Pro，你可以查看相关的文档，看是否有提供一些全局样式配置的选项。你可以尝试找到这个淡蓝色边框的样式配置项，并将其设置为你想要的样式。

3. 另外，你还可以使用浏览器的开发者工具来查看这个淡蓝色边框的样式是如何被应用的，以便找到具体的样式代码位置。在开发者工具中，你可以在 Elements（元素）面板中选择这个按钮元素并查看应用在它身上的样式规则。

希望这些步骤可以帮助你解决问题！如果还有其他问题，请随时提问。
