### ISSUE TITLE
resource loss

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro#1083]
https://pro.ant.design/components/FooterToolbar-cn/

https://pro.ant.design/components/GlobalFooter-cn/

<img width="896" alt="2018-03-13 11 20 56" src="https://user-images.githubusercontent.com/7017767/37320676-bee5b220-26af-11e8-9d99-db52bc6578e7.png">

**Comment by chenshuai2144** [comment]
这个不影响使用。。。
@benjycui 的模板里面自带了这两个
我看一下 antd 不需要的话 就干掉他
