### ISSUE TITLE
配置了代理还是显示跨域问题

### ISSUE THREAD

**Issue by MuXueTianYin** [ant-design/ant-design-pro#10854]
配置了代理还是显示跨域问题！！
用的"start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev",启动项目的
  // 如果需要自定义本地开发服务器  请取消注释按需调整
  dev: {
    // localhost:8000/api/** -> https://preview.pro.ant.design/api/**
    '/api/': {
      // 要代理的地址
      target: 'http://localhost:8080',
      // 配置了这个可以从 http 代理到 https
      // 依赖 origin 的功能可能需要这个，比如 cookie
      changeOrigin: true,// 允许域名进行转换
    },
  },
在proxy里面配置了8080端口
在app.tsx里面配置了baseURl
export const request = {
  baseURL:"http://localhost:8080",
  ...errorConfig,
};
其他配置没变，用脚手架安装的umi4版本，用原版的request发起请求产生了跨域
register:1 Access to XMLHttpRequest at 'http://localhost:8080/api/login?token%20=%20123' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by lee13523947224** [comment]
解决了吗？我也遇到同样的问题
