### ISSUE TITLE
🐛 [BUG]暗黑模式下菜单颜色自定义的情况下做不到动态切换

### ISSUE THREAD

**Issue by happysmile12321** [ant-design/ant-design-pro#10859]
### 🐛 bug 描述

在暗黑模式下，用了antd 的组件都可以切换过来，但是在menu这里配置的时候做不到切换颜色。
我直接放图，你们好看一些。

![image](https://github.com/ant-design/ant-design-pro/assets/41978045/fc034f95-7020-4632-976a-ad164b67df65)
请看图

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案

这个问题可能是由于暗黑模式下，antd menu组件没有正确地响应主题切换引起的。为了解决这个问题，你可以尝试以下几个步骤：

1. 确保你已经正确地配置了暗黑模式，并且在切换主题时触发了更新。

2. 确认你的菜单组件引用的是antd的最新版本，如果不是，请升级到最新版本。

3. 确保你已经正确地配置了自定义颜色，并且在切换主题时更新了这些颜色。

4. 使用antd的主题切换方案来动态切换菜单颜色。你可以参考antd的[自定义主题文档](https://ant.design/docs/react/customize-theme-cn)来了解如何自定义主题。

下面是一个示例代码，展示了如何使用antd的主题切换方案来动态切换菜单颜色：

```jsx
import React, { useState } from 'react';
import { Button, Menu } from 'antd';

const App = () => {
  const [theme, setTheme] = useState('light');

  const handleThemeChange = () => {
    if (theme === 'light') {
      setTheme('dark');
    } else {
      setTheme('light');
    }
  };

  return (
    <div>
      <Button onClick={handleThemeChange}>切换主题</Button>
      <Menu theme={theme} mode="horizontal">
        <Menu.Item key="1">菜单项1</Menu.Item>
        <Menu.Item key="2">菜单项2</Menu.Item>
        <Menu.Item key="3">菜单项3</Menu.Item>
      </Menu>
    </div>
  );
};

export default App;
```

这是一个简单的示例，通过点击按钮来切换主题，菜单组件会根据主题自动更新颜色。

希望以上解决方案能够帮助你解决问题。如果仍然有疑问，请提供更多的代码和细节，我们会尽力帮助你解决。

**Comment by chenshuai2144** [comment]
你好！根据你的描述和截图，你想在暗黑模式下动态切换菜单的颜色，但是当前的配置方式并不能实现这个效果。我建议你使用动态的方式来设置颜色，使用 DesginToken 来替换固定的配置。你可以在 `app.ts` 文件中的 `layout` 方法中通过传入 `initalValues` 参数来动态设置菜单的颜色。这样就能实现在暗黑模式下动态切换菜单颜色的效果啦。

**Comment by Amazing-0921** [comment]
我有同样的问题，请问解决了吗
