### ISSUE TITLE
🐛 [BUG]v6版本暗色风格和色弱模式下的一些样式问题

### ISSUE THREAD

**Issue by ghuan** [ant-design/ant-design-pro#10863]
### 🐛 bug 描述
v6版本：
- 1. 暗色风格：
- - 1.  在多页签下，页签背景条颜色未修改，还是白色
- 2. 色弱模式：
- - 1. 在多页签+暗色风格下，页签背景条颜色未修改，还是黑色
- - 2. 在多页签下，配置hasFixedHeader: true（固定页签条） 失效
- - 3. 未开启多页签下，切换到色弱模式会有x轴滚动条短暂的出现，在多页签下，x轴滚动条就一直存在了
- - 4. 在内容页height过高时，不单单是table，最外层的背景色（高度没有自动调整）缺失

### 📷 复现步骤 | Recurrence steps

- 1. 暗色风格（开启暗色风格）：
- - 1.  开启多页签
- 2. 色弱模式（开启暗色风格）：
- - 1. 开启多页签，切换暗色风格
- - 2. 开启多页签，并配置hasFixedHeader: true，选个table内容多的，鼠标上下滚动，页签条不会固定在头部
- - 3. 未开启多页签下，切换到色弱模式会有x轴滚动条短暂的出现，在多页签下，x轴滚动条就一直存在了
- - 4. 在内容页height过高时，不单单是table，最外层的背景色（高度没有自动调整）缺失

### 🏞 期望结果 | Expected results

- 1. 暗色风格：
- - 1.  在多页签下，页签背景条颜色改为黑色
- 2. 色弱模式：
- - 1. 在多页签+暗色风格下，页签背景条颜色改为白色
- - 2. 在多页签下，配置hasFixedHeader: true（固定页签条） 使之有效
- - 3. 未开启多页签下，切换到色弱模式时不应有x轴滚动条出现
- - 4. 在内容页height过高时，不单单是table，外层的页面元素（高度自动调整）

### 💻 复现代码 | Recurrence code

多页签配置代码：
```
keepalive: [/./],
  tabsLayout: {
  hasDropdown: true,
  hasFixedHeader: true,
  },
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0]
- umi 4.0版本
- 浏览器环境 chorme
- 开发环境 [e.g. Windows10]

### 🚑 其他信息

![454508a1-b1e1-4c88-90b2-8a60d84c2da1](https://github.com/ant-design/ant-design-pro/assets/15809971/411078b1-9d04-498c-a32e-3723e33d076b)
![7410b9a5-20fb-4f75-b5cf-362428ba59b5](https://github.com/ant-design/ant-design-pro/assets/15809971/3f410271-5491-49c9-97d1-540ed3ccf09d)
![c4cf5f2f-b346-4918-8f85-448ef32bad8d](https://github.com/ant-design/ant-design-pro/assets/15809971/425f4b4f-324a-4870-ba78-a3d186b7e049)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你提供的问题描述，我理解到以下问题：

1. 在暗色风格下的多页签中，页签背景条的颜色未修改，仍然是白色。
2. 在色弱模式下的多页签中，页签背景条未根据暗色风格修改，仍然是黑色。
3. 在多页签下配置hasFixedHeader: true无效。
4. 切换到色弱模式时，如果未开启多页签，会出现短暂的x轴滚动条，开启多页签后，x轴滚动条会一直存在。
5. 内容页高度过高时，最外层背景色缺失，无法正确自动调整高度。

针对这些问题，我将为你提供相应的解决方案：

1. 在暗色风格下修改多页签的页签背景条颜色可以通过修改样式来实现。你可以找到多页签的 CSS 类名，然后针对该类名修改背景条颜色。例如：

```tsx
// 在全局样式或者相应的组件样式文件中添加以下代码
.your-tabs-class-name .ant-tabs-nav .ant-tabs-nav-wrap {
  background-color: black;
}
```

2. 在色弱模式下修改多页签的页签背景条颜色同样可以通过修改样式来实现。你可以针对不同的场景，使用伪类或其他选择器来指定不同的样式。例如：

```tsx
// 在全局样式或者相应的组件样式文件中添加以下代码
.your-tabs-class-name .ant-tabs-nav .ant-tabs-nav-wrap {
  background-color: white;
}
```

3. 在多页签下配置hasFixedHeader: true使之有效可能是由于样式冲突或其他原因导致的。你可以检查是否有其他样式文件覆盖了该属性，或者尝试在配置中添加更具体的选择器。例如：

```tsx
// 确保hasFixedHeader属性在选项卡容器上生效
.your-tabs-container-class-name .ant-tabs-nav {
  position: fixed;
}
```

4. 切换到色弱模式时出现x轴滚动条的问题可能是由于页面布局或样式设置不正确导致的。你可以通过检查页面布局和样式代码，确保元素的宽度和溢出设置正确。例如：

```tsx
// 检查是否有不正确的宽度设置或者溢出设置
.your-content-class-name {
  width: 100%; // 确保填充整个容器宽度
  overflow-x: hidden; // 隐藏水平溢出
}
```

5. 内容页高度过高导致最外层背景色缺失的问题可能是由于容器不正确的高度设置导致的。你可以通过修改容器的高度以确保正确的自动调整。例如：

```tsx
// 确保容器的高度正确自动调整
.your-container-class-name {
  height: auto; // 使用自动高度
  overflow-y: auto; // 添加垂直滚动条以滚动内容
}
```

这些是我对你描述的问题的初步解决方案，请根据你的具体情况进行尝试和适当调整。此外，你还可以参考Ant Design Pro的文档和GitHub仓库以获取更多关于上述问题的详细信息和解决方案。

Ant Design Pro文档：https://pro.ant.design/
Ant Design Pro GitHub仓库：https://github.com/ant-design/ant-design-pro

希望能对你有所帮助，如果你有更多的问题或需要进一步的帮助，请随时提问。

**Comment by chenshuai2144** [comment]
这些都是三方工能，你要去对应的仓库提问，官方不负责维护
