### ISSUE TITLE
🧐[问题 | question]设置layout配置中的target:'_self'之后菜单跳转依旧是在新标签页打开

### ISSUE THREAD

**Issue by HeLiYu0** [ant-design/ant-design-pro#10868]
### 🧐 问题描述 | Problem description
我在app.tsx中从服务端获取的菜单数据，path为url链接。在defaultSettings.ts文件中配置的target:'self'但是点击菜单跳转仍然是在新标签页打开

### 💻 示例代码 | Sample code
menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: {
        // userId: initialState
      },
      request: async (params: void, defaultMenuData: any) => {
        const menus = await getMenuList().then((res: any) => {
          return res.data[1].children.map((item: any) => {
            return {
              path: '/',
              name: item.title,
              icon: React.createElement(allIcons['SettingOutlined']),
              key: item.id,
              routes: item.children.map((element: any) => {
                return {
                  path: 'https://umijs.org/docs/api/runtime-config#layout',
                  //
                  name:element.title,
                  key: element.id,
                };
              }),
            };
          });
        });
        // initialState.currentUser 中包含了所有用户信息
        return menus;
      },
    },

### 🚑 其他信息 | Other information
antdPro版本:V6，umi版本：4

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 解决方案 | Solution

在Ant Design Pro中，菜单的跳转是通过路由实现的。设置`target: '_self'`只对链接有效，对于路由跳转无效。

要在同一标签页中打开菜单跳转，请确保路由的跳转方式为默认方式。在示例代码中，`path`直接设置为外部链接，所以会在新标签页打开。

要在同一标签页中打开菜单，请按照以下步骤操作：

1. 在路由配置文件（通常是`config.ts`中的`menu.ts`）中定义菜单项时，将`path`设置为自己定义的路由路径，如`/dashboard`。

例如：

```tsx
{
  path: '/dashboard', // 自定义的路由路径
  name: 'Dashboard',
  icon: <SettingOutlined />,
  key: 'dashboard',
  routes: [
    {
      path: '/dashboard/setting', // 自定义的子路由路径
      name: 'Setting',
      key: 'setting',
      component: './Dashboard/Setting', // 对应的组件文件路径
    },
  ],
}
```

2. 在组件中，使用`history.push()`或者`Link`来实现路由跳转。

例如，在点击菜单时，可以在`handleMenuClick`方法中使用`history.push()`：

```tsx
import { history } from 'umi';

// ...

handleMenuClick = (path: string) => {
  history.push(path); // 使用 history.push() 进行路由跳转
}

render() {
  return (
    <Menu onClick={this.handleMenuClick}>
      {/* 菜单项 */}
    </Menu>
  );
}
```

或者，在菜单项中使用`Link`组件：

```tsx
import { Link } from 'umi';

// ...

render() {
  return (
    <Menu>
      <Menu.Item>
        <Link to="/dashboard">Dashboard</Link>
      </Menu.Item>
    </Menu>
  );
}
```

这样设置后，点击菜单时将在相同的标签页中进行路由跳转。

更多关于路由配置和路由跳转的文档可以参考以下链接：

- [Ant Design Pro 路由配置](https://pro.ant.design/docs/router)
- [UmiJS 路由配置](https://umijs.org/zh-CN/docs/routing)
- [React Router 使用指南](https://reactrouter.com/web/guides/quick-start)

**Comment by chenshuai2144** [comment]
根据您提供的代码片段，我注意到您正在加载菜单数据并将其用作导航链接。您提到在设置`defaultSettings.ts`中的`target:'self'`后，菜单仍然在新标签页中打开。

根据您的描述，我假设您正在使用Ant Design Pro V6和umi V4。在Ant Design Pro V6中，默认情况下，菜单链接是在新标签页中打开的，而不受`defaultSettings.ts`中的配置影响。

要在当前标签页中打开菜单链接，您需要进行以下更改：

1. 打开`config.ts`文件。
2. 在`menu`配置中的每个菜单项中添加`target:'_self'`属性。

示例代码如下：

```typescript
export default [
  {
    path: '/',
    name: '菜单1',
    icon: 'icon1',
    target: '_self', // 添加target属性
  },
  {
    path: '/menu2',
    name: '菜单2',
    icon: 'icon2',
    target: '_self', // 添加target属性
  },
  // 其他菜单项...
];
```

通过将`target`设置为`'_self'`，您将告诉浏览器在当前标签页中打开链接。

请注意，这种更改将应用于所有菜单项。如果只想更改特定菜单项的行为，请在相应的菜单项中进行更改。

希望这能帮助解决您的问题！如果您有任何其他疑问，请随时问我。
