### ISSUE TITLE
🧐[问题 | question]退出登录后，再登录无法进入后台

### ISSUE THREAD

**Issue by guwan** [ant-design/ant-design-pro#10865]
### 🧐 问题描述 | Problem description

登录后成功后会自动返回登录页面。无法进入后台。

1，退出登录后
2，进入浏览器输入: http://localhost:8000/welcome
3，这时会跳转到登录页面: http://localhost:8000/user/login

第三步，我觉得应该跳转的页面应该是：http://localhost:8001/user/login?redirect=%2Fwelcome ，我觉得现在的跳转页面时错误的。
我的菜单是从后台获取的，所以我看了几个类似的issue解决方法，并不能解决我的问题。

### 💻 示例代码 | Sample code

// 登录
      const result = await login({...values});
      if (result.code === 200) {
        const defaultLoginSuccessMessage = intl.formatMessage({
          id: 'pages.login.success',
          defaultMessage: '登录成功！',
        });
        message.success(defaultLoginSuccessMessage);

        saveUserToken(result.data as string);

        const userInfoResult = await fetchUserInfo();
        const userMenuResult = await fetchUserMenu();

        const urlParams = new URL(window.location.href).searchParams;

        Promise.all([userInfoResult, userMenuResult]).then(() => {
          //console.log("登录成功,跳转到：",urlParams.get('redirect') || '/welcome')
          history.push(urlParams.get('redirect') || '/welcome');
        })

        return;
      }

### 🚑 其他信息 | Other information

OS: windows 10

Node：v16.16.0

浏览器 | browser： edge

**Comment by guwan** [comment]
我解决了，解决方式不太好。
如下，将fetchUserInfo和fetchUserMenu合并。
```
    const fetchUserInfoAndMenu = async (callback: () => void) => {
    const userInfo = await initialState?.fetchUserInfo?.();
    const userMenu = await initialState?.fetchUserMenu?.();
    if (userInfo) {
      flushSync(() => {
        setInitialState((s) => ({
          ...s,
          menu: userMenu,
          currentUser: userInfo,
        })).then(() => {
          callback()
        });
      })
    }
  };
```
然后在会调用跳转

```
      const urlParams = new URL(window.location.href).searchParams;
       await fetchUserInfoAndMenu(() => {
          history.push(urlParams.get('redirect') || '/welcome');
        })
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🎉 解决方案 | Solution

根据你提供的代码和问题描述，可以尝试以下解决方案：

1. 首先，确认确保 `fetchUserInfo` 和 `fetchUserMenu` 方法是正确实现的，可以从后台成功获取用户信息和菜单。

2. 将 `fetchUserInfo` 和 `fetchUserMenu` 合并成一个新的方法 `fetchUserInfoAndMenu`，以确保在登录成功后同时获取用户信息和菜单。你已经按照这个方向实现了一部分代码。

3. 根据你的需求，在 `fetchUserInfoAndMenu` 方法的实现中，将获取的用户信息和菜单进行设置，然后执行回调函数 `callback`。

4. 在登录成功后，使用 `fetchUserInfoAndMenu` 方法来获取用户信息和菜单，并在获取完成后执行回调函数，在回调函数中进行页面跳转。

以下是修改后的代码示例:

```javascript
const fetchUserInfoAndMenu = async (callback) => {
  const userInfo = await initialState?.fetchUserInfo?.();
  const userMenu = await initialState?.fetchUserMenu?.();
  if (userInfo) {
    flushSync(() => {
      setInitialState((s) => ({
        ...s,
        menu: userMenu,
        currentUser: userInfo,
      })).then(() => {
        callback();
      });
    });
  }
};

// 登录成功后
const result = await login({...values});
if (result.code === 200) {
  const defaultLoginSuccessMessage = intl.formatMessage({
    id: 'pages.login.success',
    defaultMessage: '登录成功！',
  });
  message.success(defaultLoginSuccessMessage);

  saveUserToken(result.data as string);

  const urlParams = new URL(window.location.href).searchParams;

  // 获取用户信息和菜单，并在获取完成后执行回调函数
  await fetchUserInfoAndMenu(() => {
    // 在回调函数中进行页面跳转
    history.push(urlParams.get('redirect') || '/welcome');
  });

  return;
}
```

这样，登录成功后，会先获取用户信息和菜单，然后再执行页面跳转，确保登录后正确进入后台页面。

### 📚 参考文档 | Reference Documentation

- [React API: useHistory](https://reactrouter.com/web/api/Hooks/usehistory)
  React Router 提供的 `useHistory` 钩子函数的文档，可以参考其中的示例代码来进行页面跳转。

- [React Documentation: useEffect](https://reactjs.org/docs/hooks-effect.html)
  React 提供的 `useEffect` 钩子函数的文档，可以了解更多关于在组件中使用异步操作的技巧。

记得在实现代码之前，先确认你的 `fetchUserInfo` 和 `fetchUserMenu` 方法能够正确返回用户信息和菜单。如果问题仍然存在，请提供更多细节和错误信息，以便我们能够帮助你更好地解决问题。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🛠 解决方案 | Solution

根据你的描述，问题似乎与登录后跳转的页面有关。你期望的跳转页面应该是 `http://localhost:8001/user/login?redirect=%2Fwelcome`，但实际上跳转到了 `http://localhost:8000/user/login`。

可能的原因之一是登录成功后没有正确设置跳转的 URL。在你的代码中，你尝试获取 URL 中的 `redirect` 参数或者使用默认的 `/welcome` 路径作为跳转目标。为了确保获取正确的 URL 参数，你可以尝试在登录成功后打印一下 `window.location.href` 和 `urlParams.get('redirect')` 的结果，看看是否获取到了正确的值。

除此之外，你还需要检查后台的登录验证逻辑。判断用户是否已经登录，并且在进行登录验证时，将正确的跳转 URL 传递给登录接口。

如果以上方法都没有解决问题，可能需要检查后台服务是否正常运行，以及相关页面和路由的配置是否正确。

希望以上解决方案能对你有所帮助。如果问题仍然存在，请提供更多的代码和错误信息，以便我们深入分析并提供更好的支持。

**Comment by chenshuai2144** [comment]
从你的描述中，我可以看出问题可能出在登录成功后页面跳转的逻辑上。根据你提供的代码片段，可以尝试以下解决方案：

1. 确保在退出登录后，清除用户凭证，以使登录状态失效。可以使用适当的方法来清除存储在浏览器中的用户凭证，如清除 LocalStorage 或使用其他方式。

2. 在登录成功后，获取用户信息和用户菜单。确保这两个请求都成功完成后再进行跳转。

3. 在跳转的时候，使用正确的登录页面链接。你提到应该是`http://localhost:8001/user/login?redirect=%2Fwelcome`，确保在跳转时使用正确的链接。

4. 在进行页面跳转之前，可以先通过 `console.log` 或其他方式检查一下 `urlParams.get('redirect')` 的值，确保它的值是正确的。

根据你提供的信息，这些是可能导致问题的原因。你可以尝试按照以上步骤进行排查，看是否能够解决登录后无法进入后台的问题。如果问题仍然存在，欢迎继续提供更多信息，以便我们进行进一步的排查和解决。
