### ISSUE TITLE
antdpro的prolayout鼠标移入一级菜单，显示二级菜单，如何实现鼠标移入一级菜单，显示一级与二级菜单

### ISSUE THREAD

**Issue by wangfeiyu2020** [ant-design/ant-design-pro#10873]
### 🧐 问题描述 | Problem description

antdpro的prolayout鼠标移入一级菜单，显示二级菜单，如何实现鼠标移入一级菜单，显示一级与二级菜单
### 💻 示例代码 | Sample code
<ProLayout
        {...Settings}
        {...SettingRoutes}
        collapsed={collapsed}
        onCollapse={setCollapsed}
        location={{
          pathname
        }}
        actionsRender={() => {
          return [];
        }}
        menuItemRender={(menuItemProps, defaultDom) => (
          <div
            style={{
              display: "flex",
              alignItems: "center"
            }}
            onClick={() => {
              setCollapsed(true);
              setPathname(menuItemProps.path || "/organizationaManage/companyInformation");
            }}
          >
            {menuItemProps.pro_layout_parentKeys &&
              menuItemProps.pro_layout_parentKeys.length > 0 &&
              menuItemProps.icon}
            <span>{defaultDom}</span>
          </div>
        )}
      >
        <div className={styles.headerContainer}>{pathname === "/systemTools/panel" && <ViewIndex />}</div>
      </ProLayout>

### 🚑 其他信息 | Other information

![图片](https://github.com/ant-design/ant-design-pro/assets/65601661/0e1585b6-436b-458d-8e18-ce1e22989e97)
![图片](https://github.com/ant-design/ant-design-pro/assets/65601661/a72b4c71-d20a-4f35-90ed-8665c2c8b7a3)

OS:

Node：

浏览器 | browser：firefox

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

要实现鼠标移入一级菜单时显示一级和二级菜单的效果，你可以使用antdpro中Menu组件的SubMenu子菜单。

首先，确保你已经引入了antdpro的Menu组件。

然后，你可以使用CSS的伪类:hover来实现鼠标移入一级菜单时显示二级菜单的效果。以下是示例代码：

```jsx
import React from 'react';
import { ProLayout, Menu } from '@ant-design/pro-layout';

const SubMenu = Menu.SubMenu;

const MyLayout = () => {
  return (
    <ProLayout
      menuRender={(props) => (
        <Menu
          mode="inline"
          theme="dark"
          selectedKeys={[props.location.pathname]}
          defaultSelectedKeys={[props.location.pathname]}
        >
          <SubMenu
            key="sub1"
            title={
              <span>
                <span>一级菜单</span>
              </span>
            }
          >
            <Menu.Item key="/page1">二级菜单1</Menu.Item>
            <Menu.Item key="/page2">二级菜单2</Menu.Item>
          </SubMenu>
        </Menu>
      )}
    >
      {/* 页面内容 */}
    </ProLayout>
  );
};

export default MyLayout;
```

在上述示例代码中，我们使用`Menu`组件的`SubMenu`来创建一级菜单，并在`SubMenu`中添加了二级菜单项。当鼠标移入一级菜单时，二级菜单项会显示出来。

你可以根据你的实际需求来修改菜单和页面内容。

关于antdpro中的Menu组件，你可以参考官方文档：[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

希望以上解决方案对你有所帮助！

**Comment by chenshuai2144** [comment]
如果你想实现鼠标移入一级菜单时显示二级菜单的效果，你可以借助Ant Design ProLayout组件的`onMouseEnter`和`onMouseLeave`事件来实现。

首先，在`<ProLayout>`组件上添加`onMouseEnter`和`onMouseLeave`事件处理函数。

```tsx
<ProLayout
  onMouseEnter={handleMouseEnter}
  onMouseLeave={handleMouseLeave}
>
  // 其他内容
</ProLayout>
```

然后，定义`handleMouseEnter`和`handleMouseLeave`函数来处理鼠标进入和离开一级菜单的事件。

```tsx
const handleMouseEnter = () => {
  // 显示二级菜单的逻辑
};

const handleMouseLeave = () => {
  // 隐藏二级菜单的逻辑
};
```

在`handleMouseEnter`函数中，你可以使用React的状态钩子来管理二级菜单是否显示的状态。

```tsx
const [showSubMenu, setShowSubMenu] = useState(false);

const handleMouseEnter = () => {
  setShowSubMenu(true);
};

const handleMouseLeave = () => {
  setShowSubMenu(false);
};
```

最后，你可以根据`showSubMenu`状态来决定是否显示二级菜单。

```tsx
{showSubMenu && (
  // 二级菜单的内容
)}
```

通过这种方式，当鼠标移入一级菜单时，二级菜单会显示出来，鼠标移出时，二级菜单会隐藏起来。希望对你有帮助！
