### ISSUE TITLE
不显示导航栏

### ISSUE THREAD

**Issue by xiaohe001** [ant-design/ant-design-pro#10870]
添加二级菜单后，左上角不显示导航栏

路由代码：
routes: [
      { path: '/admin/user-manage', name: '用户管理', icon: 'smile', component: './Admin/UserManage' },
      { component: './404' },
    ],

![image](https://github.com/ant-design/ant-design-pro/assets/130716764/41ff8a54-5ac6-4f49-a0ba-2f6fb4ed0e00)

**Comment by xiaohe001** [comment]
在return 中 用 PageContainer 将代码包起来 即可

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined
