### ISSUE TITLE
antd pro umi@4 布局模式

### ISSUE THREAD

**Issue by MelodyBlue** [ant-design/ant-design-pro#10875]
antd pro umi@4 这种布局模式应该怎么配置？配置不出来这种布局的

![微信截图_20230804175647](https://github.com/ant-design/ant-design-pro/assets/28422022/dce661e5-98fa-4de3-91d0-87a41a010488)

**Comment by wangzhoubin** [comment]
那个演示里面不是有吗

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
修改为 mix 模式就是了
