### ISSUE TITLE
请问这种几层嵌套的动态添加表单元素是如何解决的？

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#1087]
![image](https://user-images.githubusercontent.com/183884/37345804-aef8094a-2708-11e8-8276-9dd1a34ffc54.png)
目前按照官方的文档，第一层解决了，但是嵌套这一块 不知道怎么处理了？

**Comment by afc163** [comment]
建议自行探索，非 pro 代码本身的问题，建议到 http://segmentfault.com/ 或其他地方进行讨论。
