### ISSUE TITLE
🐛 [BUG] ModelForm 使用request会显示上一次的数据

### ISSUE THREAD

**Issue by gexin1** [ant-design/ant-design-pro#10871]
### 🐛 bug 描述

ModelForm 使用request会显示上一次的数据
查看request获取的值也是最新的
也使用了以下属性
```
 modalProps={{
          destroyOnClose:true,
  }}
```

### 📷 复现步骤 | Recurrence steps

点击第一条数据，modelForm 会显示第一条数据，
关闭modelForm
点击二条数据，modelForm 会显示第一条数据

### 🏞 期望结果 | Expected results

显示本次数据
### 💻 复现代码 | Recurrence code

https://codesandbox.io/s/json-lai-sheng-cheng-fen-bu-biao-dan-forked-dtkwrd?file=/App.tsx:752-766

### © 版本信息

```
 "@ant-design/pro-components": "2.6.10",
    "antd": "5.7.0",
```

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案

这个问题可能是由于 ModelForm 组件没有正确绑定新的数据。在每次打开 ModelForm 时，你可以通过在 Modal 的 `visible` 属性上添加一个唯一的 key，以确保每次打开时都会重新渲染 ModelForm 组件。

你可以尝试以下代码修改：

```jsx
import { Modal, Form, Input } from 'antd';

function ExampleModal({ visible, onCancel }) {
  const [form] = Form.useForm();

  // 这里假设你的数据是通过 props 传递的
  const data = {
    // 你的数据
  };

  const handleCancel = () => {
    form.resetFields(); // 取消后重置表单字段
    onCancel();
  };

  return (
    <Modal
      visible={visible}
      onCancel={handleCancel}
      destroyOnClose // 加上 destroyOnClose 属性确保每次关闭后都销毁 Modal 内容
      key={Date.now()} // 每次打开 Modal 时重新渲染
    >
      <Form form={form} initialValues={data}>
        <Form.Item name="fieldName" label="Field Label">
          <Input />
        </Form.Item>
        {/* 其他表单字段 */}
      </Form>
    </Modal>
  );
}
```

此外，确保你的 `data` 对象中的属性名和你的表单字段的 `name` 属性值相匹配。

更多关于 Ant Design Modal 组件的文档和示例可以在官方文档中找到：

- [Ant Design Modal 官方文档](https://ant.design/components/modal/)
- [Ant Design Form 官方文档](https://ant.design/components/form/)

**Comment by chenshuai2144** [comment]
这个问题似乎是由于 ModelForm 组件在每次关闭后没有销毁导致的。你可以尝试在 modalProps 中添加 destroyOnClose 属性并将其设置为true，这样每次关闭 ModelForm 后，下次打开时就会重新创建一个新的实例，而不会保留上一次的数据。你可以在代码中添加以下代码：

```tsx
modalProps={{
  destroyOnClose: true,
}}
```

另外，我注意到你的代码中引用的 "@ant-design/pro-components" 版本是"2.6.10"，
