### ISSUE TITLE
🐛 [BUG]使用pnpm安装依赖Button的hidden属性失效

### ISSUE THREAD

**Issue by endwalker** [ant-design/ant-design-pro#10889]
### 🐛 bug 描述

使用pnpm安装依赖Button的hidden属性失效，npm安装正常
![image](https://github.com/ant-design/ant-design-pro/assets/79031406/7b31d2dd-968a-4a23-920c-f0cb8857d915)
![image](https://github.com/ant-design/ant-design-pro/assets/79031406/a802fb80-c330-44dc-a4d3-ff1815ac3e35)

### 🏞 期望结果 | Expected results

使用pnpm安装能和npm安装效果一致

### © 版本信息

- Ant Design Pro 版本: 3.1.0
- umi 版本: 4.x
- 浏览器环境
- 开发环境: Windows
- node: 16.20.0
- pnpm: 8.6.12
- npm: 8.19.4

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据您的描述，看起来像是在使用pnpm安装依赖时，Button组件的hidden属性失效了。这可能是由于某些依赖项或配置的问题导致的。为了解决这个问题，您可以尝试以下几个步骤：

1. 确保您的项目已经安装了最新版本的Ant Design Pro和umi。
2. 检查您的pnpm版本是否最新，可以使用`pnpm -v`命令来查看。如果不是最新版本，请更新到最新版本。
3. 清除pnpm的缓存，可以使用`pnpm cache clear`命令来清除缓存。
4. 确保您的项目中没有其他引起冲突的依赖项。您可以尝试使用一个干净的项目来测试是否出现同样的问题。
5. 如果问题仍然存在，您可以尝试使用npm代替pnpm进行依赖安装，看看是否能正常工作。

此外，您还可以参考Ant Design Pro官方文档中关于Button组件的使用方法和属性说明来进一步调试和解决问题。以下是相关文档链接：

- [Ant Design Pro Button组件文档](https://procomponents.ant.design/components/button-cn/)

希望这些信息能对您有所帮助！如果您有任何进一步的问题，请随时向我提问。

**Comment by chenshuai2144** [comment]
pnpm  带了  lock，要更新可以  pnpm update  更新一下
