### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by lyck40012** [ant-design/ant-design-pro#10886]
### 🐛 bug 描述

我编辑商品编码的时候，想要设置商品名称的值，目前我发现setRowData是不生效的
  {
      title: '商品编码',
      dataIndex: 'mateSku',
      width: 120,
      align:"center",
      fieldProps: (form, config) => {
        return {
          options: goodsList,
          onChange:(val)=>{
            editorFormRef.current?.setRowData?.(config.rowIndex,{
              mateSkuName:123123
            })
          },
        }
      }
    },
  {
      title: (
        <div><span style={{color: 'red'}}>*</span>商品名称</div>
      ),
      dataIndex: 'mateSkuName',
      width: 200,
      align:"center",
      formItemProps: () => {
        return {
          rules: [{required: true, message: '此项为必填项'}],
        };
      },
    },

### © 版本信息

 "@ant-design/pro-components": "^2.3.57",
"antd": "^5.6.3",
- umi 4
- 浏览器环境
- Chrome

**Comment by lyck40012** [comment]
111

**Comment by markdashi** [comment]
没有解决，为什么关闭呢？

**Comment by lyck40012** [comment]
> 没有解决，为什么关闭呢？
我一共发了两个可能重复了吧

**Comment by markdashi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
