### ISSUE TITLE
editorFormRef.current?.setRowData方法不生效

### ISSUE THREAD

**Issue by lyck40012** [ant-design/ant-design-pro#10887]
### 🐛 bug 描述

EditableProTable表格中 当我改a输入框的值的时候，想要b输入框也跟着改

### © 版本信息

"@ant-design/pro-components": "^2.3.57",
umi4

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


尝试使用 `form.setFieldsValue` 方法来设置 `b` 输入框的值。
这是一个示例代码片段：

```jsx
import React, { useRef } from 'react';
import { Form, Input, Button } from 'antd';

const YourComponent = () => {
  const formRef = useRef();

  const handleInputChange = (value) => {
    formRef.current.setFieldsValue({
      b: value
    });
  };

  const onFinish = (values) => {
    console.log(values);
  };

  return (
    <Form ref={formRef} onFinish={onFinish}>
      <Form.Item name="a">
        <Input onChange={(e) => handleInputChange(e.target.value)} />
      </Form.Item>
      
      <Form.Item name="b">
        <Input />
      </Form.Item>

      <Form.Item>
        <Button type="primary" htmlType="submit">Submit</Button>
      </Form.Item>
    </Form>
  );
};

export default YourComponent;
```

在这个例子中，我们使用 `formRef` 来引用表单并将其设置为 `Form` 组件的 `ref` 属性。当 `a` 输入框的值改变时，我们调用 `handleInputChange` 方法来更新 `b` 输入框的值。这是通过调用 `formRef.current.setFieldsValue` 方法实现的，其中 `b` 是表单项的名称，`value` 是要设置的值。当提交表单时，你可以在 `onFinish` 回调中打印出表单的值。

你可以根据你自己的代码适应这个示例，并确保你引入了所需的库和组件。

关于 Ant Design 表单的更多信息，请参阅官方文档：[https://ant.design/components/form/](https://ant.design/components/form/)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！对于你描述的问题，可能是由于未正确使用`EditableProTable`的`editorFormRef`导致的。

首先，确保你已经正确地创建了`editorFormRef`的引用，例如：

```javascript
const editorFormRef = useRef(null);
```

然后，在`EditableProTable`中，你需要将`editorFormRef`传递给`editable`属性，如下所示：

```javascript
<EditableProTable
  // 其他属性...
  editable={{
    form: editorFormRef.current,
  }}
/>
```

最后，你可以尝试使用`editorFormRef.current.setFieldsValue()`方法手动设置`b`输入框的值以实现你的需求，示例如下：

```javascript
editorFormRef.current.setFieldsValue({
  b: newValue, // 设置b输入框的新值
});
```

请注意，确保在调用`setFieldsValue`之前，`editorFormRef`已经正确地引用了表单组件。另外，根据你的需求，你可能需要在`a`输入框值变化时触发该逻辑。

关于`EditableProTable`的使用和`editorFormRef`的更多信息，请参考官方文档：

- `EditableProTable`：[https://procomponents.ant.design/components/table#editableprotable](https://procomponents.ant.design/components/table#editableprotable)
- `editorFormRef`：[https://ant-design.github.io/form-cn/docs/react/getting-started](https://ant-design.github.io/form-cn/docs/react/getting-started)
