### ISSUE TITLE
change fonts source to local path

### ISSUE THREAD

**Issue by felipehsantos** [ant-design/ant-design-pro#1088]
Hi,
I would like to change the fonts file to a local file, however I could not do it properly. 

1. Downloaded font files ( https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.xxx )
2. I added to src/theme.js the line below
        'icon-url': 'http://localhost:8000/fonts/font_148784_v4ggb6wrjmkotj4i'

Is it possible to change the font source to a local directory?

Best Regards
Felipe

![image](https://user-images.githubusercontent.com/8118757/37364782-37b0d52a-26da-11e8-911b-23061cba490e.png)

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by felipehsantos** [comment]
According to https://pro.ant.design/docs/theme I should change the file **Scaffolding found in the directory below.src/theme.js** which I did with the example posted above. It did not work:

// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
module.exports = {
  // 'primary-color': '#10e99b',
  'card-actions-background': '#f5f8fa',
  'primary-color': '#d4380d',
  'icon-url': '../iconfont/iconfont',
};

**Comment by afc163** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/507615/37381546-ada96f14-2778-11e8-9362-8a44ca6cfdcd.png">

**Comment by felipehsantos** [comment]
Could you recend the link. It's an image instead of an url

**Comment by afc163** [comment]
The link is inside https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

I send the screenshot to make the point that you should notice the reference.

**Comment by felipehsantos** [comment]
Hi,
I read the references and still could not make this work. Reading through https://github.com/vision8tech/dvajs-user-dashboard/pull/2 (which is referenced at https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont) showed that I had to define **icon-url** between quotes ("), which I did but now I got compilation errors:

Configuration @ src/theme.js
![image](https://user-images.githubusercontent.com/8118757/37476362-bed340e0-2853-11e8-8550-f1218c75c228.png)

![image](https://user-images.githubusercontent.com/8118757/37476401-d4a1f07e-2853-11e8-90a0-1d8d8c1b8683.png)

**Ant Design Pro** is using https://github.com/sorrycc/roadhog instead of webpack.config in the root directory.  I did not know how to repplicate the solutions  this with .webpackrc.js and reading through roadhog docs it´s said that data in the **public** directory will be copied to **dist**.

1. Copy icont font to public directory

![image](https://user-images.githubusercontent.com/8118757/37476553-39c0c106-2854-11e8-9a8d-8487fe04d559.png)

2. Change configuration to:

![image](https://user-images.githubusercontent.com/8118757/37476626-631a144e-2854-11e8-8c8a-6e21237f96bf.png)

It worded.

**Comment by RanQiwu** [comment]
正确方法：
![image](https://user-images.githubusercontent.com/22112008/44038666-dd5f1ba2-9f49-11e8-8acc-d2fbfdec9c1a.png)
![image](https://user-images.githubusercontent.com/22112008/44038692-e808562c-9f49-11e8-88bc-443ae9e764cd.png)
![image](https://user-images.githubusercontent.com/22112008/44038724-fc9bbdcc-9f49-11e8-9c1b-94437982ad8e.png)

**Comment by changyu72** [comment]
@RanQiwu   thanks！
