### ISSUE TITLE
官方为啥不维护vue版本的

### ISSUE THREAD

**Issue by imaxun** [ant-design/ant-design-pro#10880]
官方为啥不维护vue版本的

**Comment by Alfred-Alan** [comment]
确实疑惑，vue版是另一个公司做的，只开放1.0后面都要收钱

**Comment by codedart2018** [comment]
你见过官方做过vue系的？？　官方一直走的react系的呀！

**Comment by pkaq** [comment]
压根就没有什么vue版本 人家一直是react技术体系的 vue说白了就是社区照着人家的UI山寨出来的

**Comment by WuJiY** [comment]
为啥要维护？😄😄😄

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
全公司都找不到一个擅长  vue 的，也不可能维护  vue  版本
