### ISSUE TITLE
🧐[问题 | question]登录成功后，再次访问登录页面时，页面不能自动跳转到home页面？

### ISSUE THREAD

**Issue by Orange-Yellow** [ant-design/ant-design-pro#10895]
### 🧐 问题描述 | Problem description

ant-design-pro6.0 登录成功后，再次访问登录页面时，仍然可以登录。如何配置登录成功后，访问登录页面自动跳转到home页面？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

要实现登录成功后，访问登录页面自动跳转到home页面，你可以在登录成功后，通过编程的方式进行页面跳转。下面是一种常见的实现方式。

#### Step 1: 在登录页面（`src/pages/login/Login.jsx`）中，使用 `history.push()` 方法进行页面跳转。

```jsx
import React from 'react';
import { Form, Input, Button, message } from 'antd';
import { useHistory } from 'react-router-dom';

const Login = () => {
  const history = useHistory();

  const handleLogin = (values) => {
    // 发起登录请求，验证用户名和密码等操作

    // 登录成功后，跳转到home页面
    history.push('/home');
  };

  return (
    <div>
      <h1>Login Page</h1>
      <Form onFinish={handleLogin}>
        {/* 表单项省略 */}
        <Button type="primary" htmlType="submit">
          Login
        </Button>
      </Form>
    </div>
  );
};

export default Login;
```

#### Step 2: 在路由配置文件（`src/routes/index.jsx`）中，确保 `/home` 路径对应的组件存在。

```jsx
import React from 'react';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import Login from '../pages/login/Login';
import Home from '../pages/home/Home';

const Routes = () => {
  return (
    <Router>
      <Switch>
        <Route exact path="/" component={Login} />
        <Route exact path="/home" component={Home} />
      </Switch>
    </Router>
  );
};

export default Routes;
```

这样，在登录成功后，页面将自动跳转到home页面。

### 📚 相关文档 | Related documentation

- React Router 路由器教程：[https://reactrouter.com/web/guides/quick-start](https://reactrouter.com/web/guides/quick-start)
- React Router useHistory 钩子文档：[https://reactrouter.com/web/api/Hooks/usehistory](https://reactrouter.com/web/api/Hooks/usehistory)
- antd `<Form>` 组件文档：[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

**Comment by Orange-Yellow** [comment]
点击登录后跳转home页这个已经实现了。我希望的是已经登录的状态，访问login页面，会自动重定向到home页

**Comment by chenshuai2144** [comment]
问题描述中提到，在ant-design-pro6.0中，登录成功后再次访问登录页面时，仍然可以登录。想要配置登录成功后访问登录页面自动跳转到home页面，可以使用以下步骤：


 在你的Login 文件夹 中，找到登录页面对应的组件，并添加一个重定向的路由规则。例如，如果你的登录页面对应的路由路径是`/login`，则可以在路由配置文件中添加如下代码：
   ```jsx
   import { Redirect } from 'umi';

   // other routes...

   // Redirect route for login page
     {isLoggedIn ? <Redirect to="/home" /> : <LoginPage />}
   // other routes...
   ```
   以上代码中，`isLoggedIn`是一个用于判断用户是否已经登录的状态变量。如果用户已经登录，则重定向到`/home`页面；如果用户未登录，则正常显示登录页面。
3. 确保在用户成功登录后，将`isLoggedIn`状态设置为`true`，以触发重定向。你可以根据你的具体登录逻辑进行相应的处理。

通过以上步骤，登录成功后再次访问登录页面时，页面会自动跳转到home页面。希望对你有帮助！如果还有其他问题，请随时提问。
