### ISSUE TITLE
只有上传图片的时候跨域,并且换成老项目实现跨域的上传 API 也会提示跨域,并且 POST 提交的时候,有时候会请求两次,有时候提交一次

### ISSUE THREAD

**Issue by luoandy** [ant-design/ant-design-pro#1089]
`Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by yesmeck** [comment]
CORS 了解一下 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS

**Comment by luoandy** [comment]
提交两次的解决了,但是上传的时候依然跨域,设置了代理可以上传,但是打包的时候代理貌似没用,我应该怎么设置呢
