### ISSUE TITLE
🐛[BUG] pnpm 工具安装依赖，ant design pro 模板无法正确配置关闭http2，yarn 安装可以

### ISSUE THREAD

**Issue by 5201314999** [ant-design/ant-design-pro#10891]
### 🐛 bug 描述

ant design pro 项目模板下，使用pnpm i 安装无法正确关闭http2
![image](https://github.com/ant-design/ant-design-pro/assets/13427449/8e41ee3b-0dc9-4c39-8547-971578b5cbe6)

### 📷 复现步骤 | Recurrence steps

1. npm i @ant-design/pro-cli -g     pro create myapp 新建项目
2. config.ts 配置 开启https，关闭http2
![image](https://github.com/ant-design/ant-design-pro/assets/13427449/3bf1f930-a62b-4854-aca8-880bf783a3b7)

3. 打开调试器,查看http2 是否改为http1.1

![image](https://github.com/ant-design/ant-design-pro/assets/13427449/8d06bc7d-55f0-40c1-831a-a87bb20f3e0b)

### 🏞 期望结果 | Expected results

![image](https://github.com/ant-design/ant-design-pro/assets/13427449/9fd1fabe-a2cd-4398-8604-3920e6b6df14)

### 💻 复现代码 | Recurrence code

根据官方说明初始化项目即可，修改config.ts 配置即可 https://ant-design.gitee.io/docs/react/getting-started-cn

### © 版本信息

- Ant Design Pro 版本: v6
- umi 版本 4
- 浏览器环境  chrome 115
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，我是 Github 的 issue 助理，专门处理关于 React 前端问题的。对于你描述的问题，我已经了解了。根据你的描述，你在使用 pnpm 工具安装依赖时，ant design pro 模板无法正确配置关闭 http2，而使用 yarn 安装则可以正常配置。

为了解决你的问题，你可以尝试以下步骤：

1. 确保你使用的是最新版本的 ant design pro 模板，可以使用以下命令更新：

```shell
npm i @ant-design/pro-cli -g
```

2. 在创建新项目时，可以使用以下命令：

```shell
pro create myapp
```

3. 在项目的 `config.ts` 文件中，确保你已经正确配置了关闭 http2 的选项。可以参考下面的示例代码：

```typescript
export default {
  // 其他配置...
  // 关闭 http2
  esbuild: {
    loader: 'gc.bundled'
  },
  // 其他配置...
};
```

4. 如果你在选择使用 pnpm 安装依赖时，仍然无法正确关闭 http2，可以尝试以下方法：

- 使用 npm 或 yarn 安装依赖。可以使用以下命令：
  
  ```shell
  npm install
  ```
  
  或
  
  ```shell
  yarn install
  ```
  
  然后再运行项目。

5. 如果以上步骤仍然无法解决问题，你可以尝试在项目根目录下创建一个 `.npmrc` 文件，并添加以下内容：

```plaintext
http2=false
```

这个文件可以禁用所有使用 pnpm 的项目的 http2 功能。

如果你遇到其他问题，或者以上方法无法解决你的问题，请提供更多的信息和错误日志，以便我能够更好地帮助你。

希望这些解决方案对你有帮助！如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
升级一下  umi 的版本就可以 了，因为 pnpm 带了 lock，执行  `pnpm update`

https://umijs.org/docs/api/config#https
