### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by Coder-p2c** [ant-design/ant-design-pro#10897]
### 🐛 bug 描述
const { info } = openAPIData;
                ^
TypeError: Cannot destructure property 'info' of 'openAPIData' as it is null.

在初始化后，进行了去国际化操作；然后使用openapi插件生成前端接口代码，报错

### 📷 复现步骤 | Recurrence steps
初始化项目模板，就只进行了移除国际化操作

### 🏞 期望结果 | Expected results
报错了没有在seevices目录下没有生成相应的接口

### © 版本信息

- Ant Design Pro 版本: [5.2.2]
- umi 版本 4
- 浏览器环境 edge
- 开发环境 [windows]

**Comment by Shuxinzsx** [comment]
您好，请问解决了吗？

**Comment by Seacolour** [comment]
今天刚碰到这个问题，因为后端项目没启动，后端项目运行再openAPI就行

**Comment by ANCB520** [comment]
先试试你的json链接浏览器中不能不打开，路径要swagger.json结尾，比如：http://127.0.0.1:5133/swagger/v1/swagger.json，

**Comment by XieMingH** [comment]
检查schemaPath路径对了没，我也是遇到这个问题，排查发现是因为路径
