### ISSUE TITLE
🧐[问题 | question]配置响应式布局断点无效。onBreakpoint是否可以使用？

### ISSUE THREAD

**Issue by HeLiYu0** [ant-design/ant-design-pro#10893]
### 🧐 问题描述 | Problem description

在defaultSettings.tsx中增加了响应式布局断点的配置。但是仍然时默认的配置。另外就是onBreakpoint在pro中是否还可以继续使用？

### 💻 示例代码 | Sample code

import { ProLayoutProps } from '@ant-design/pro-components';

/**
 * @name
 */
const Settings: ProLayoutProps & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  colorPrimary: '',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: true,
  fixSiderbar: true,
  colorWeak: false,
  title: '',
  // pwa: true,
  // logo: '',
  iconfontUrl: '',
  token: {
    // bgLayout: 'rgb(10,80,9)',
    header: {
      colorBgHeader: '#ff7676'
    },
    sider: {
      colorBgMenuItemCollapsedElevated:'red',
      colorMenuBackground: '#2f323e',
      colorTextMenu:'#fff',
      colorBgMenuItemSelected:'rgb(103,182,255)',
      colorTextMenuSelected:'#fff',
      colorTextMenuItemHover:'#fff',
    },
    // 参见ts声明，demo 见文档，通过token 修改样式
    //https://procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F
  },
  target: '_self',
  headerRender: undefined,
  // appList: [
  //   {
  //     title: '首页',
  //     url: 'https://procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F',
  //   },
  //   {
  //     title: '用户管理',
  //     url: '/users',
  //   },
  //   {
  //     title: '系统设置',
  //     url: '/settings',
  //   }, {
  //     title: '跨站点导航栏列表',
  //     url: '/settings',
  //   },
  // ],
  // breakpoint:false,
  // defaultCollapsed:true,
  collapsed:false,
  openKeys:[''],
  // defaultValue
  selectedKeys:[''],
  collapsedWidth:0,
  siderWidth:70,
  breakpoint:'xxl',

};
export default Settings;
### 🚑 其他信息 | Other information

OS:umi4，antd Pro V6

Node：

浏览器 | browser：edge

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👋 Hi! 感谢您使用 GitHub 的 issue 助理来解决您的问题。

关于您的问题，根据您提供的代码，您想要配置响应式布局断点，但是该配置似乎不起作用，同时您还想知道 `onBreakpoint` 在 ProLayout 中是否还可以继续使用。

首先，让我们来看一下您提供的代码。根据您的代码，我注意到您导入并使用了 `ProLayoutProps`。根据我的了解，通过 `ProLayout` 组件传递给它的配置项 `ProLayoutProps` 并不会直接用于配置响应式断点。

要在 Ant Design Pro 的 ProLayout 中配置响应式断点，您需要使用 `defaultLayouts` 或 `layouts` 参数。您可以根据不同的断点设置不同的布局。

以下是一个示例修改您的代码来配置响应式断点的示例：

```tsx
import { ProLayoutProps, BasicLayoutProps } from '@ant-design/pro-layout';

const Settings: ProLayoutProps & {
  pwa?: boolean;
  logo?: string;
} = {
  // 其他配置...
  breakpoits: {
    // 您可以根据需要设置不同的断点和对应的布局
    xs: {
      layout: 'side',
    },
    sm: {
      layout: 'top',
    },
    md: {
      layout: 'mix',
    },
    lg: {
      layout: 'mix',
    },
    xl: {
      layout: 'mix',
    },
    xxl: {
      layout: 'mix',
    },
  },
};

export default Settings;
```

注意，在这个示例中，我们使用了 `breakpoints` 参数来配置不同的断点和对应的布局。您可以根据需求调整这些设置。

关于 `onBreakpoint`，根据 Ant Design Pro 的文档，在 ProLayout 中可以继续使用 `onBreakpoint`。它会在响应式断点发生变化时被调用。您可以在 `ProLayout` 组件上设置 `onBreakpoint` 属性，如下所示：

```tsx
import ProLayout, { BasicLayoutProps } from '@ant-design/pro-layout';

const MyLayout: React.FC<BasicLayoutProps> = (props) => {
  const handleBreakpoint = (broken: boolean) => {
    // 在这里处理响应断点变化的逻辑
    console.log('响应断点：', broken);
  };

  return (
    <ProLayout
      // 其他配置...
      onBreakpoint={handleBreakpoint}
    >
      {props.children}
    </ProLayout>
  );
};

export default MyLayout;
```

通过以上的代码示例，您可以使用 `onBreakpoint` 来处理响应式断点的变化，并在发生变化时执行相应的操作。

希望这些信息能对您有所帮助！如果您还有任何疑问，请随时追问。
