### ISSUE TITLE
🐛 [BUG] layout为top，路由菜单背景变为透明了

### ISSUE THREAD

**Issue by wanglihuaya** [ant-design/ant-design-pro#10896]
### 🐛 bug 描述

创建最新的pro，`defaultSettings.ts` 设置 `layout` 为 `top`，当有多级路由菜单时，`menu` 背景变为 `(255,255,255,0,6)` 了 

### 📷 复现步骤 | Recurrence steps

同上

### 🏞 期望结果 | Expected results

和 组件 menu 一样

### 💻 复现代码 | Recurrence code

脚手架创建的最新本的ant-design-pro

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本: 4.0.52
- 浏览器环境: chrome 115
- 开发环境  mac OS

<img width="433" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/49522285/ac3a79e3-47c9-414c-98a3-56e152d54a1f">

**Comment by dqrjz** [comment]
+1

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
更新下 antd  和  pro 的版本，是不搭配导致的
