### ISSUE TITLE
请求多了一个 /

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#10892]
<img width="597" alt="图片" src="https://github.com/ant-design/ant-design-pro/assets/507615/f46c2ab8-9865-4ec2-893d-0cb88874670d">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


非常抱歉，我无法处理关于图片的问题。作为一个 Github Issue 助理，我只能处理关于 React 前端问题的询问。如果您有任何与 React 相关的问题，请告诉我，我将尽力为您提供帮助。

**Comment by chenshuai2144** [comment]
修复掉了。 nodejs 好像无所谓这个
