### ISSUE TITLE
v6版本多环境变量按照官网配置，不生效🐛 [BUG]

### ISSUE THREAD

**Issue by liosummer** [ant-design/ant-design-pro#10890]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您报告这个问题！根据您提供的信息，您在使用 Ant Design Pro v6 版本时遇到了环境变量不生效的问题。我将为您提供一些可能的解决方案。

首先，请确保您正确配置了多环境变量。在 Ant Design Pro v6 中，您可以通过在项目根目录下的 `.env` 文件中设置环境变量。确保您的 `.env` 文件位于正确的位置，并包含与您期望的环境对应的变量。例如，如果要使用 `dev` 环境的配置，确保您的 `.env` 文件中包含以下内容：

```plaintext
# .env
NODE_ENV=development
```

如果您已经正确配置了多环境变量，但仍然无法生效，请检查您运行项目时使用的命令。在 Ant Design Pro v6 中，使用 `umi` 命令来启动开发服务器。请确保您执行的命令是 `umi dev`，而不是其他命令。例如：

```shell
$ umi dev
```

如果您不确定是否使用了正确的命令，请检查项目的 `package.json` 文件中的 `"scripts"` 部分，查看是否有类似于以下内容的命令：

```json
"scripts": {
  "start": "umi dev"
}
```

如果以上操作都没有解决您的问题，您可以尝试重新安装项目的依赖。删除项目根目录下的 `node_modules` 文件夹，并执行以下命令重新安装依赖：

```shell
$ npm install
```

这些是常见的解决方案，希望能帮助您解决问题。如果问题仍然存在，请提供更多的代码示例和错误信息，以便我能够更好地帮助您。另外，您也可以查阅 Ant Design Pro v6 的官方文档，以了解更多关于配置环境变量的信息：[https://pro.ant.design/docs/devops-cn#%E9%85%8D%E7%BD%AE-Evn-%E5%8F%98%E9%87%8F](https://pro.ant.design/docs/devops-cn#%E9%85%8D%E7%BD%AE-Evn-%E5%8F%98%E9%87%8F)

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/guides/env-variables
