### ISSUE TITLE
🧐[问题 | question] PageContainer中token设置无效

### ISSUE THREAD

**Issue by bigflytime** [ant-design/ant-design-pro#10899]
### 🧐 问题描述 | Problem description

想修改pageContainer的边距
官方文档中https://pro-components.antdigital.dev/components/page-container#%E4%BF%AE%E6%94%B9-token说明使用：

token={{
  paddingBlockPageContainerContent: 20,
  paddingInlinePageContainerContent: 60,
}}
可以来调整边距，但是实际上页面刷新后并无效果。

### 💻 示例代码 | Sample code

可参考文档提供的示例https://codesandbox.io/s/hqw3s2?file=/App.tsx:290-322

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by bigflytime** [comment]
已解决。

在app.tsx的layout中设置可生效：
token: {
      pageContainer: {
        paddingBlockPageContainerContent: 20,
        paddingInlinePageContainerContent: 100
      }
    }

但是为什么在<PageContainer />中不生效呢？

**Comment by cdx111** [comment]
一样

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢您提供的信息。

从您提供的代码片段来看，您将token放在了PageContainer组件中，并且在刷新页面后发现样式没有生效。这是因为token需要在PageContainer的父组件中设置才能生效。

要在PageContainer中调整边距，您需要在其父组件的token属性中进行设置。例如，在app.tsx中的Layout组件中设置token属性：

```tsx
<Layout
  logo={logo}
  title="React Issue助理"
  contentWidth="Fluid"
  headerHeight={64}
  ... // 其他属性
  token={{
    pageContainer: {
      paddingBlockPageContainerContent: 20,
      paddingInlinePageContainerContent: 60,
    },
  }}
>
  <PageContainer // 这里是PageContainer组件
    ... // 其他属性
  >
    {/* 页面内容 */}
  </PageContainer>
</Layout>
```

通过将token属性直接传递给Layout组件，可以确保在整个布局中生效，包括内部的PageContainer组件。

希望这可以解决您的问题。如果有更多疑问，请随时提问。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 👋 嗨，感谢您向我们寻求帮助！根据您的描述，您在使用PageContainer组件时设置token属性无效并没有达到预期效果。

### 🛠 解决方案 | Solution

1. 首先，请确保您已经正确导入PageContainer组件，并且安装了所需的依赖。您可以使用以下命令来安装ProComponents库的最新版本：

   ```bash
   npm install @ant-design/pro-components@latest --save
   ```

2. 确保您在代码中正确设置了token属性。在您提供的示例代码中，可以通过修改`App.tsx`文件中的PageContainer组件来设置边距。请确保在您所需要的页面中也进行了类似的更改。

   ```jsx
   import { PageContainer } from '@ant-design/pro-layout';

   const App = () => {
     return (
       <div>
         <PageContainer
           token={{
             paddingBlockPageContainerContent: 20,
             paddingInlinePageContainerContent: 60,
           }}
         >
           {/* Your page content */}
         </PageContainer>
       </div>
     );
   };

   export default App;
   ```

3. 如果您的页面边距仍然没有生效，您可以尝试清除浏览器缓存并重新加载页面。有时候缓存的问题会导致样式没有实际应用。

6. 如果问题仍然存在，请确保您的前端项目正确引入了React和Ant Design，并且React和Ant Design的版本与PageContainer兼容。您可以查看官方文档来获取相关版本兼容信息。

### 📚 相关文档 | Documentation

- [Ant Design Pro Components - PageContainer](https://procomponents.ant.design/components/page-container/)
- [Ant Design Pro Components - Token](https://procomponents.ant.design/components/page-container/#Token)


希望这些解决方案对您有所帮助！如果您有任何其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令问题的

解决方案如下：

1. 确保您的代码中引入了 Umi 和 antd，并且已正确配置好了环境。

2. 在您的项目中使用 PageContainer 组件时，通过 token 属性来调整边距。例如：

```jsx
import { PageContainer } from '@ant-design/pro-layout';

// 在组件中使用
<PageContainer
  token={{
    paddingBlockPageContainerContent: 20,
    paddingInlinePageContainerContent: 60,
  }}
>
  // 页面内容...
</PageContainer>
```

3. 如果在页面刷新后边距设置仍然无效，可能是由于 token 设置被覆盖或者失效。在此情况下，可以尝试以下方案：

- 确保 PageContainer 组件是在使用 token 的组件的直接子组件中，并且没有其他组件层级嵌套。

- 检查项目中是否存在其他自定义样式或组件，可能会影响到 PageContainer 组件的样式。

- 确保您的代码中没有进行过其他的样式覆盖或者重写。

- 如果以上方案都没有解决问题，可以考虑使用开发者工具（如 Chrome 的开发者工具）来检查元素的样式，看是否有其他样式优先级较高导致 token 设置无效。

请注意，以上方案是基于一般情况下的解决方案，具体情况可能会有所不同。如果问题仍然存在
