### ISSUE TITLE
👑 [需求 | Feature] 初次进页面无法拿到 initialState，调用下refresh(),让登录成功不跳转说拜拜

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#10907]
### 🥰 需求描述 | Requirements description

本地开发的时候没有注意，因为当时地址上都带有路由或参数，但给客户的地址是一个干净地址，进去页面客户点击登录提示登录成功，但就是进不了后台。后来试了下确实也是不进入后台，然后在登录的时候打印了下initialState对象，发现是一个undefined,它当然无法调用fetchUserInfo无法跳转登录喽！

### 🧐 解决方案 | Solution

在登录页面useEffect里加个刷新，让它进入页面去调用下刷新initialState，让它不在是一个undefined

```
 const { initialState, refresh, setInitialState } = useModel('@@initialState');
  useEffect(() => {
    refresh();
  }, []);
```

### 🚑 其他信息 | Other information

如果还不能解决你问题的话，直接暴力写个方法调用，不去调用ininitalState.fetchUserInfo.

```

  const fetchUserInfo = async () => {
    //如果登录时候initialState 还是一个undefined 直接写一个方法调用代替它。
    const userInfo = await initialState?.fetchUserInfo?.();
    if (userInfo) {
      flushSync(() => {
        setInitialState((s) => ({
          ...s,
          currentUser: userInfo,
        }));
      });
    }
  };
```

**Comment by echoyl** [comment]
登录后回调中直接
`flushSync(() => {
              setInitialState((s) => ({
                ...s,
                currentUser: res.data.userinfo
              })).then(() => {
                const redirect = searchParams.get('redirect') || '/';
                history.push(redirect);
              });
            });`

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🥰 需求描述 | Requirements description

用户登录成功后，想要刷新 `initialState` 并将当前用户信息设置进去，然后跳转到指定页面。

### 🧐 解决方案 | Solution

可以在登录后的回调函数中利用 `setInitialState` 更新 `initialState` 对象，并在回调函数的 `then` 方法里进行页面跳转。

```jsx
const { setInitialState } = useModel('@@initialState');

// 假设用户登录成功后的回调函数
const handleLogin = async () => {
  // 调用登录接口或进行其他相关操作

  // 假设登录接口返回的响应数据中包含用户信息
  const res = await login();

  flushSync(() => {
    setInitialState((s) => ({
      ...s,
      currentUser: res.data.userinfo
    }));
  }).then(() => {
    const redirect = searchParams.get('redirect') || '/';
    history.push(redirect);
  });
};
```

这样，在登录成功后，会将用户信息设置到 `initialState` 的 `currentUser` 属性中，并跳转到指定页面。

### 📚 相关文档 | Related documentation

- [React Hooks 文档](https://reactjs.org/docs/hooks-intro.html)
- [React Router 文档](https://reactrouter.com/)
- [React useModel 文档](https://umijs.org/zh-CN/plugins/plugin-initial-state#usemodel)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi, 感谢你向我们提出问题。根据你的描述，你希望在初次进入页面时能够获取到 initialState，并且在登录成功后不跳转页面。

首先，确保你在页面中正确使用了 initialState。一般来说，你可以通过 `useModel` 钩子来获取到 initialState。

```jsx
const { initialState, refresh, setInitialState } = useModel('@@initialState');
```

然后，在登录页面的 `useEffect` 中，调用 `refresh` 方法来刷新 initialState。

```jsx
useEffect(() => {
  refresh();
}, []);
```

这样，当用户进入页面时，会自动调用 `refresh` 方法，使 initialState 得到刷新。

如果 `initialState` 仍然是 undefined，我们可以尝试直接调用另外一个方法来替代 `initialState.fetchUserInfo`。

```jsx
const fetchUserInfo = async () => {
  // 如果 initialState 还是 undefined，可以暴力写一个方法调用来替代它。
  const userInfo = await initialState?.fetchUserInfo?.();
  if (userInfo) {
    flushSync(() => {
      setInitialState((s) => ({
        ...s,
        currentUser: userInfo,
      }));
    });
  }
};
```

以上是一种可能的解决方案，希望能帮到你。如果问题还未解决，请提供更多代码和详细信息，我们会进一步帮助你解决问题。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there! 感谢您向我提出问题，我是这个 Github Issue 助理，专门处理与 React 前端相关的问题。根据您的需求描述，我理解到您遇到了一个涉及到 initialState 的问题。初始状态 initialState 是在调用登录操作之前获取的，但在该状态中，initialState 为 undefined，导致无法调用 fetchUserInfo 并跳转到登录成功页面。

为了解决这个问题，您可以尝试以下两种解决方案：

#### 解决方案一：

在登录页面的 useEffect 钩子中添加一段代码来刷新 initialState，使其不再为 undefined。

```jsx
import React, { useEffect } from 'react';
import { useModel } from 'umi';

const LoginPage = () => {
  const { initialState, refresh } = useModel('@@initialState');
  
  useEffect(() => {
    refresh();
  }, []);

  // ... 其他登录逻辑

  return (
    // ... 登录页面的 JSX
  );
}

export default LoginPage;
```

通过在 useEffect 钩子中调用 `refresh()` 方法，可以更新 initialState 以获取最新的用户信息，从而成功调用 fetchUserInfo 并跳转到登录成功页面。

#### 解决方案二：

如果上述解决方案不能解决您的问题，您可以尝试使用另一种更直接的方法来调用登录逻辑，而不依赖于 initialState.fetchUserInfo。

```jsx
import React, { useEffect } from 'react';
import { useModel } from 'umi';

const LoginPage = () => {
  const { initialState, setInitialState } = useModel('@@initialState');
  
  useEffect(() => {
    login(); // 调用登录方法
  }, []);

  const login = async () => {
    // 执行登录操作并获取用户信息
    const userInfo = await yourLoginMethod();
    
    // 更新 initialState
    setInitialState((s) => ({
      ...s,
      currentUser: userInfo,
    }));

    // 其他跳转逻辑
  }

  return (
    // ... 登录页面的 JSX
  );
}

export default LoginPage;
```

这种方法不再依赖于 initialState.fetchUserInfo，而是直接调用登录操作，并在成功登录后更新 initialState 的 currentUser 字段。

这些解决方案应该能解决您的问题。如果仍有其他疑问，请随时提问。希望对您有所帮助！
