### ISSUE TITLE
🧐[问题 | question] 为啥pro 脚手架生成的umi4模板不是最新的？

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design-pro#10909]
umi4脚手架生成的是最新的，但不符合最佳实战。pro创建的版本是5.22的。是不维护了吗？还是核心人员被裁了？最近感觉pro在走下坡路了！

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
脚手架这个品类本来就不太行了，你看看社区里面做的人就不多了。

多去 umi 那边了解吧
