### ISSUE TITLE
切换菜单时怎么添加loading

### ISSUE THREAD

**Issue by baiwumm** [ant-design/ant-design-pro#10902]
### 🧐 问题描述 | Problem description
![image](https://github.com/ant-design/ant-design-pro/assets/40554571/4cf4fdb8-6fac-46fa-be4a-789c0a59407d)

请问我该如何在切换菜单的时候添加一个 loading 状态

### 💻 示例代码 | Sample code
![image](https://github.com/ant-design/ant-design-pro/assets/40554571/db6b5ff9-82ae-4503-bcbe-fca2ffab7893)

我尝试在这里添加，但是我该如何改变 initialState?.loading 的状态，从 true 改成 false?

### 🚑 其他信息 | Other information

线上地址： https://react.baiwumm.com/

OS:

Node：

浏览器 | browser：

**Comment by MRXLDL** [comment]
实现了吗？ 同问...

**Comment by baiwumm** [comment]
> 实现了吗？ 同问...

添加这个文件即可：https://github.com/baiwumm/Xmw-Admin/blob/Cyan/Xmw_web/src/loading.tsx

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined
