### ISSUE TITLE
项目克隆到本地后登录不上🐛 [BUG]

### ISSUE THREAD

**Issue by WeijianLi-dve** [ant-design/ant-design-pro#10905]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="750" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/63589087/6c9e35d8-9cce-4bf5-9506-7dbed45077f6">

**Comment by TamLe54** [comment]
I got the same issue :'(

**Comment by haolf000** [comment]
You can try "pnpm start" to use mock, it is working for me. Refer to https://github.com/ant-design/ant-design-pro/issues/10716

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我只能解决关于 React 的前端问题。您遇到的登录问题可能不是前端问题，可能是后端或其他方面的问题。请尝试检查后端代码或确保登录接口正常运行。

如果您在前端方面遇到其他问题，我会很乐意帮助您解决，比如 React 组件使用、数据传递、状态管理等问题。请提供具体问题并尽可能提供代码示例和相应的文档，我将竭尽全力为您提供解决方案。

另外，如果您遇到的是关于 Ant Design Pro 或 Umi 的问题，请提供版本信息、复现代码和其他相关信息，这样我可以更好地理解和解决您的问题。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我只能处理关于 React 的前端问题。对于您提供的问题，由于缺乏具体的细节，我无法提供有效的帮助。如果你遇到了前端问题，特别是与 React 相关的问题，请提供更多的详细信息，包括复现步骤、期望的结果以及相关的代码示例。这样我将能够更好地理解您的问题，并为您提供解决方案。如果您的问题与前端无关，那么很抱歉，我无法提供帮助，建议您咨询相关领域的专家或寻求其他途径解决问题。感谢您的理解。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我只能处理关于 react 的前端问题。对于其他类型的问题，我无法提供帮助。如果您有关于 react 的前端问题，请提供具体的细节，我会尽力为您解答并提供相应的解决方案和代码示例。

请提供您遇到的具体问题、复现步骤、期望结果以及相关的代码。同时也请提供您使用的 Ant Design Pro 版本、umi 版本、浏览器环境和开发环境的信息，以便我更好地理解和解决您的问题。

如果您有其他关于 react 前端开发的问题，也欢迎提问。谢谢！
