### ISSUE TITLE
[Question] How how can I configure the CLI locale to use english?

### ISSUE THREAD

**Issue by TheBearodactyl** [ant-design/ant-design-pro#10906]
I'd like to use ant and its CLI, but I can't read a single thing that the CLI outputs. Is there an option I can set with the `pro` command, or a variable I can set in some sort of configuration file to have it output in english?

Translation if needed:
我想使用 ant 及其 CLI，但我无法读取 CLI 输出的任何内容。是否有一个我可以使用 pro 命令设置的选项，或者我可以在某种配置文件中设置一个变量以使其以英语输出？

(sorry if the translation doesn't make that much sense, I used google translate)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


[Answer] I understand that you want to configure the CLI locale of Ant to use English. Unfortunately, as a GitHub issue assistant, I can only handle frontend issues related to React. However, I can still provide you with some guidance.

To change the CLI locale of Ant, you can set the `LANG` environment variable to "en_US.UTF-8" or "en" (depending on your operating system). This will change the default language of the CLI to English.

For example, if you are using Unix/Linux/MacOS, you can open your terminal and run the following command before using Ant CLI:

```bash
export LANG=en_US.UTF-8
```

If you are using Windows, you can set the `LANG` environment variable through the command prompt using the following command:

```batch
set LANG=en
```

By setting the `LANG` environment variable, the CLI output should be displayed in English.

Please note that this solution assumes that you have already installed Ant and its CLI.

If you have any further questions or need more specific guidance, please feel free to ask!

**Comment by chenshuai2144** [comment]
To configure the CLI locale to use English with Ant Design, you can use the `--locale` option when running the CLI commands. For example, if you are using the `pro` command, you can set the locale to English by running `pro --locale=en-US`. This will make the CLI output in English.

If you want to change the default language of your components from English to Chinese, you can use the `ConfigProvider` component provided by Ant Design. Wrap your application with the `ConfigProvider` component and set the `locale` prop to `'zh_CN'`. This will ensure that the components are rendered in Chinese.

If the internationalization of the date components is still not working, make sure to also configure `dayjs.locale('zh-cn')` and check if the version of `dayjs` in your project and the version that `antd` depends on are consistent.

Remember to use the latest and recommended practices in your front-end development, such as using Design Tokens for styling, React Hooks for managing state, and avoiding libraries like DVA and Redux.
