### ISSUE TITLE
怎么好像很久没更新了

### ISSUE THREAD

**Issue by itzhoujun** [ant-design/ant-design-pro#10904]
不维护了吗

**Comment by echoyl** [comment]
这个pro是真的好久没更新了

**Comment by pkaq** [comment]
KPI结束了吧

**Comment by javalcl** [comment]
裁员裁多了  开源玩不下去了这是。。。

**Comment by epubreader** [comment]
是不是不能用这框架了， 之后还会更新吗？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
多去看看  umi 吧，脚手架这个市场已经变成了 框架的附庸，日落西山了
