### ISSUE TITLE
点击菜单之后，会出现白色渐变效果，请问怎么样去除该样式效果🧐[问题 | question]

### ISSUE THREAD

**Issue by 15975019972** [ant-design/ant-design-pro#10900]
### 🧐 问题描述 | Problem description

![image](https://github.com/ant-design/ant-design-pro/assets/65732500/7fbb0ca1-b7fa-45ab-a1fb-f7d4a64a1b01)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：
![image](https://github.com/ant-design/ant-design-pro/assets/65732500/8c0ab93f-26ad-439e-877c-bb92cf1a8f05)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 解决方案 | Solution

根据您的描述和截图，您想要去除菜单点击后的白色渐变效果。这个效果通常是由 CSS 的 `:active` 伪类所实现的。

要去除这个效果，您可以通过覆盖默认样式或者使用 `:active` 伪类的 `:focus` 同时生效来实现。以下是两种解决方案：

#### 1. 覆盖默认样式

您可以通过为菜单按钮添加 `:active` 状态的自定义样式来覆盖默认的白色渐变效果。以下是一个示例代码：

```css
.menu-item:active {
  background-color: transparent;
  box-shadow: none;
}
```

这个代码将为菜单的 `menu-item` 类添加自定义样式，使其在被点击时背景色为透明，并且去除阴影效果。您可以根据实际需要调整样式。

#### 2. 使用 `:focus` 伪类

另一种方法是使用 `:focus` 伪类来同时移除 `:active` 和 `:focus` 的样式效果。以下是一个示例代码：

```css
.menu-item:active,
.menu-item:focus {
  background-color: transparent;
  box-shadow: none;
}
```

这个代码将为菜单的 `menu-item` 类同时应用于 `:active` 和 `:focus` 伪类，使其在被点击或获取焦点时背景色为透明，并且去除阴影效果。

以上两种方法中的 `menu-item` 需要替换为您具体项目中菜单按钮的 CSS 类名。

### 📚 相关文档 | Related documentation

- [CSS :active 伪类](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:active)
- [CSS :focus 伪类](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:focus)

**Comment by chenshuai2144** [comment]
要去除点击菜单后出现的白色渐变效果，你可以通过修改CSS样式来实现。具体的步骤如下：

1. 打开开发者工具，找到菜单元素对应的CSS样式。
2. 在对应的CSS样式中找到渐变效果的部分，通常是通过`background`或`background-color`属性设置的。
3. 将渐变效果相关的CSS属性的值改为你想要的颜色，或者直接将这些属性删除，以去除渐变效果。
4. 保存修改并刷新页面，查看效果。

请注意，具体的CSS样式可能因项目而异。你可以根据菜单元素的选择器和相关的CSS属性来进行修改。如果你对CSS不太熟悉，可以提供更多关于菜单元素和相关CSS样式的代码片段，以便给出更具体的指导。
