### ISSUE TITLE
ant-design-pro应该搞个国内镜像站点

### ISSUE THREAD

**Issue by valleykid** [ant-design/ant-design-pro#1091]
类比ant-design，以应对会议期间厚重的墙~

**Comment by valleykid** [comment]
国内镜像：http://ant-design-pro.gitee.io/index-cn

**Comment by valleykid** [comment]
国内镜像：http://ant-design-pro.gitee.io/index-cn

**Comment by chenshuai2144** [comment]
也许应该更新一下readme文档

**Comment by ddcat1115** [comment]
https://github.com/ant-design/ant-design-pro/commit/5519345ba830b6ae703fa2cb5db7df8c9f93d778
