### ISSUE TITLE
所有的内容升级到 antd@5 和 @ant-design/charts

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#10911]
v6 发布 beta 已经有一段时间，antd@5 也已经发布。 @ant-design/charts 新版鸽了。接下来要将所有的 block 来升级到 antd@5。

要做的有两步：

* 使用 antd-style 替换到 less，完成换主题功能。
* 迁移到 antd@5 的用法，同时 umi 和 procomponents 一起升级。优化的时候修复小问题。

我已经使用脚本进行了一部分升级，代码在 v6-all-block，接下来的工作会基于这个版本，修改完成之后也要合并到这个分支。

##  需要修改的列表，如果需要领取请回复，pr 关联到这个 issue。

- [x] account @xieww  #10975
  - [x] center
  - [x] settings
- [x] dashboard
  - [x] analysis
  - [x] monitor
  - [x] workplace
- [x] exception @Zian502 
  - [x] 403
  - [x] 404
  - [x] 500
- [x] form @Wxh16144
  - [x] advanced-form
  - [x] basic-form
  - [x] step-form
- [x] list @kiner-tang #10938
  - [x] basic-list #10966
  - [x] card-list
  - [x] search #10970 #10971 
  - [x] table-list
  - [x] profile #10972
  - [x] advanced #10973
  - [x] basic
- [x] result @Zian502 #10941
  - [x] fail
  - [x] success
- [x] tableList @hms181231 
- [x] user @hms181231
  - [x]  login
  - [x]  register
  - [x]  register-result

## 原则

* demo 尽量像自己的业务，可以自由增加和删除
* 新增组件要受控模式
* 要支持 夜晚模式
* 不要使用 less
* 尽量使用 无状态组件
* 不要引入新的包

**Comment by Wxh16144** [comment]
我先来，我选择 form 部分

**Comment by Zian502** [comment]
我来简单的 result 和 exception

**Comment by hms181231** [comment]
我来搞下tableList和user

**Comment by kiner-tang** [comment]
我认领一下 list 部分

**Comment by kiner-tang** [comment]
@chenshuai2144 咱们这个任务有没有 deadline？

**Comment by hms181231** [comment]
@chenshuai2144   tableList和list里面的table-list的demo内容一样的并且tableList没有被router引用，还有user的内容是统一放在user下面还是User下面 看远端有两个文件夹各自放了一部分内容

**Comment by chenshuai2144** [comment]
tableList 吧，和 simple 一起用

**Comment by Zian502** [comment]
> 我来简单的 result 和 exception

https://github.com/ant-design/ant-design-pro/pull/10941

**Comment by xieww** [comment]
有时间要求吗？没有的话我可以来account @chenshuai2144

**Comment by chenshuai2144** [comment]
无要求 慢慢来都行

**Comment by xieww** [comment]
> 有时间要求吗？没有的话我可以来account @chenshuai2144

[account#10975](https://github.com/ant-design/ant-design-pro/pull/10975)

**Comment by chenshuai2144** [comment]
@Zian502  exception 也要开始干了

**Comment by Zian502** [comment]
> @Zian502 exception 也要开始干了



> @Zian502 exception 也要开始干了

https://github.com/ant-design/ant-design-pro/pull/11009

**Comment by chenshuai2144** [comment]
感谢大家，全部完成了

**Comment by duwei54** [comment]
> 感谢大家，全部完成了

啥时候发布呀@chenshuai2144

**Comment by zhaiguanjie7** [comment]
> > 感谢大家，全部完成了
> 
> 啥时候发布呀@chenshuai2144

看commit是不是还没做完呢？任务全发出去了，但是代码只改完一半
