### ISSUE TITLE
🐛 [BUG] 当前最新版本，在登录页面，点击输入框浏览器就崩溃。

### ISSUE THREAD

**Issue by fengshengxie** [ant-design/ant-design-pro#10929]
### 🐛 bug 描述
当前最新版本，在登录页面，点击输入框浏览器就崩溃。

### 📷 复现步骤 | Recurrence steps
```
git clone https://github.com/ant-design/ant-design-pro.git
cd ant-design-pro
tyarn
npm start
```
登录输入账号的地方输入内容就会造成浏览器崩溃

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fengshengxie** [comment]
找到原因了，昨天不知道为啥
@ant-design/pro-components
组件安装的版本是2.6.14
今天安装的是2.6.15，恢复正常了。

**Comment by kiner-tang** [comment]
问题已经在 https://github.com/ant-design/pro-components/pull/7599 中修复了
