### ISSUE TITLE
DatePicker 组件关闭国际化之后中英文混在一起🐛 [BUG]

### ISSUE THREAD

**Issue by unStarCN** [ant-design/ant-design-pro#10920]
### 🐛 bug 描述

项目用不到国际化, 就关掉了, 目前用的其它组件没有问题但是用DatePicker这个组件却出现中英文混入, 换成其它语言依旧是和其他语言一起混着

### 🏞 期望结果 | Expected results

![image](https://github.com/ant-design/ant-design-pro/assets/78009357/3f9b5862-3ff7-49e1-9308-1b31f1c5e33b)

### © 版本信息

 "@ant-design/pro-components": "^2.3.57",
  "antd": "^5.8.4",
"@umijs/max": "^4.0.52",
antdpro:6

### 🚑 其他信息

![image](https://github.com/ant-design/ant-design-pro/assets/78009357/3c46f1c3-9be3-4281-a707-26070f31b6b7)
![image](https://github.com/ant-design/ant-design-pro/assets/78009357/e2022b2d-a0c7-491a-9a21-48837aef1a7b)

**Comment by dongshuai777** [comment]
[#42170](https://github.com/ant-design/ant-design/issues/42170)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined
