### ISSUE TITLE
我想在点击menu的时候，生成一个tab页，我应该怎么做才能动态的加载tab，并且tab的内容也是加载出来的。

### ISSUE THREAD

**Issue by wyy19940829** [ant-design/ant-design-pro#1093]
我想在点击menu的时候，生成一个tab页，我应该怎么做才能动态的加载tab，并且tab的内容也是加载出来的。

**Comment by ddcat1115** [comment]
目前还没有类似的实现，你可以参考之前的讨论 https://github.com/ant-design/ant-design-pro/issues/848

**Comment by chenshuai2144** [comment]
我还蛮喜欢 tab 的方式的。我们也许需要讨论一下到底要不要做，
做成什么形式

**Comment by ddcat1115** [comment]
一般什么场景下会选择这种交互？和一般的 tab 切换有什么区别？

**Comment by chenshuai2144** [comment]
主要还是留存，在一些订单或者数据展示的时候很有可能需要对照，
我们用的编辑器也可以类比为一种业务。有tab可以更快的留存和切换。
一般的 tab 事固定的数量的标签，这种方式是不固定的 tab。

**Comment by chenshuai2144** [comment]
父任务打开一个标签页开始一个子标签页完成一个任务。这种强关联的情况

**Comment by ddcat1115** [comment]
记到 lark 里了

**Comment by afc163** [comment]
不建议做这个功能。

**Comment by hoozi** [comment]
就目前的react-route 似乎没有提供route keep功能

**Comment by chenshuai2144** [comment]
这个功能我试了一下 复杂度挺高。
我试了一下 react-router 和 tab 的对应就很麻烦

**Comment by roc2539** [comment]
@chenshuai2144 那官方不支持这种了？

**Comment by RivanLuo** [comment]
> 这个功能我试了一下 复杂度挺高。
> 我试了一下 react-router 和 tab 的对应就很麻烦

能否做出一个demo给广大的需求者，我看需求这个功能的人还蛮多的？

**Comment by zengyunchun** [comment]
这个不是很基本的功能吗，为什么都很难实现，后台管理系统很普遍都要tab切换吧，有没有什么好的做法 @chenshuai2144

**Comment by zengyunchun** [comment]
@chenshuai2144 不好意思打扰了，看到有实现这个多页标签的，https://github.com/kuhami/react-ant， 能否看下是否比较合理，有没有什么需要注意的，多谢
