### ISSUE TITLE
🐛 [BUG] master代码ts报错

### ISSUE THREAD

**Issue by LuckLin520** [ant-design/ant-design-pro#10932]
### 📷 复现步骤 | Recurrence steps
刚刚拉取master代码，装包运行，有ts报错originalKeywordKind 和identifierToKeywordKind(identifier)相关，与市场是降级ts到4.9，但是有报错模块“"@umijs/max"”没有导出的成员，项目可以正常运行，但是ts错误烦心

### 🏞 期望结果 | Expected results
不再显示以外的ts错误

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LuckLin520** [comment]
> ![image](https://user-images.githubusercontent.com/72405338/264546177-5d497e94-5869-42fb-8f23-51a63ba7bbb8.png) 类似这种吗

对
![image](https://github.com/ant-design/ant-design-pro/assets/33896086/8a5af4f1-0d01-4f57-a627-57345a02809e)

**Comment by dqrjz** [comment]
umi v4.0.79 已修复：https://github.com/umijs/umi/pull/11567

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined
