### ISSUE TITLE
关于网站皮肤切换，如何实现？

### ISSUE THREAD

**Issue by remotesc2** [ant-design/ant-design-pro#1094]
基于 antd-pro 的项目样式都是引自 default.less，这样在开发期间可以很方便的通过 theme.js 进行颜色修改。
但是上线项目的皮肤切换要怎么做？

我自己设想的：
1、在一套 css 中编写两套 class，然后网站通过动态切换 className，实现效果修改
2、参考 default.less，编写多套样式（比如 red.less、green.less），然后生成多套 css，网站再动态引用不同的 css 文件

方式2 感觉从代码层级上会更加成体系，但是还不清楚该如何操作

大家还有什么好的思路吗？

**Comment by chenshuai2144** [comment]
看看 antd 的实现。比较靠谱一点

**Comment by remotesc2** [comment]
```jsx
// antd 的代码片段
const menuClassName = classNames(className, `${prefixCls}-${theme}`, {
   [`${prefixCls}-inline-collapsed`]: this.getInlineCollapsed(),
});
```

从这块来看，antd 应该也属于动态修改 className 这个方案？

**Comment by chenshuai2144** [comment]
用的less 看看官网

**Comment by remotesc2** [comment]
是的，他在代码层级是有两套 less，最终生成一套 css

**Comment by remotesc2** [comment]
我看 antd-pro 的网站布局中，也有主题切换按钮，未来大体上也会是这一套思路吗？

**Comment by CrewS** [comment]
@chenshuai2144 是指antd官网那个主题颜色切换吗？请问这个有源码可以查阅吗

**Comment by chenshuai2144** [comment]
有的，只要利用了 less 的在线编译。
颜色文档拆分为一个专门的 less 在线实时编译来实现的。
主要是为了实现动态的不固定的颜色配置。
如果是固定数量的主题颜色，编译成不成 css 动态加载 是更好的办法

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/10007

**Comment by jackYouth** [comment]
ant的官网好像是通过currentColor这个css3的新特性实现的

**Comment by chenshuai2144** [comment]
是通过在浏览器编译 less 实现的

**Comment by 15502573620** [comment]
具体怎么实现啊....有没有详细一点的指导...

**Comment by 520Yanxiaofei** [comment]
@remotesc2 嗨你好，我也有这个需求方案，请问你实现了吗？
