### ISSUE TITLE
🧐[问题 | question]表格一页1000条数据，点击后面的操作按钮时（比如点击修改弹窗），弹窗会很卡

### ISSUE THREAD

**Issue by JasmineMoo** [ant-design/ant-design-pro#10946]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there!

感谢您向我提问关于表格页面卡顿的问题。根据您的描述，我理解到您在处理大量数据时遇到了性能问题。为了能够帮助您解决这个问题，我需要一些额外的信息：

1. 您使用的是哪个 React UI 组件库（如果有的话）？
2. 您是如何获取和渲染这1000条数据的？
3. 您的操作按钮是如何触发弹窗的？

请提供以上信息，我将尽力为您提供一个解决方案。
