### ISSUE TITLE
🧐[问题 | question] pro 6.0 必须用typescript吗？

### ISSUE THREAD

**Issue by epubreader** [ant-design/ant-design-pro#10944]
pro 6.0 必须用typescript吗？ 我想像5.0一样用javascript
下面这个命令创建都是typescript代码
npm i @ant-design/pro-cli -g

**Comment by Moveharder** [comment]
请教下，V5.0用什么命令才能使用javascript？我看官网的初始化命令是 pro create myapp，这个生成的项目就是ts/tsx

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！对于 ant-design/pro 的版本 6.0，它默认生成的项目是使用 TypeScript 的，但是你仍然可以在项目中使用 JavaScript 而不是 TypeScript。下面是一些步骤来创建一个使用 JavaScript 的 ant-design/pro 6.0 项目：

1. 首先，确保你已经全局安装了 `@ant-design/pro-cli`。如果没有安装，可以运行以下命令进行安装：

```
npm install @ant-design/pro-cli -g
```

2. 创建一个新的 ant-design/pro 项目，可以使用命令：

```
pro new myapp
```

这将会在当前目录下创建一个名为 `myapp` 的项目。

3. 进入到生成的项目目录中，可以使用以下命令：

```
cd myapp
```

4. 打开 `tsconfig.json` 文件，并将 `"strict"` 设置为 `false`。这将允许你在项目中使用 JavaScript。

```json
{
  "compilerOptions": {
    "strict": false,
    // 其他设置...
  }
}
```

5. 删除 `src` 目录下的 `*.tsx` 文件。

6. 创建一个新的 JavaScript 文件，比如 `index.js`，并在其中编写你的 JavaScript 代码。

7. 运行以下命令启动你的项目：

```
npm start
```

现在，你应该能够使用 JavaScript 编写你的 ant-design/pro 6.0 项目了。

关于 ant-design/pro 的详细文档，请参考官方文档：[https://pro.ant.design/](https://pro.ant.design/)

希望对你有帮助！如果还有其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢你的问题。

关于 ant-design/pro 6.0 是否必须使用 TypeScript 的问题，答案是不必须。Ant Design Pro 6.0 允许你选择使用 JavaScript 或 TypeScript 来开发。

对于你提到的创建命令 `npm i @ant-design/pro-cli -g`，这是用于全局安装 Ant Design Pro CLI 的命令，它用于快速创建 Ant Design Pro 项目。

如果你想使用 JavaScript 而不是 TypeScript 来创建项目，你可以使用以下命令：

```bash
$ npx @ant-design/pro-cli init my-app --template=ant-design-pro
```

这将会创建一个基于 JavaScript 的 Ant Design Pro 项目。

在创建了项目之后，你需要注意一些差异：

1. 在 `src` 目录下，默认会有一些 TypeScript 文件，你可以将它们替换为 JavaScript 文件，或者使用 JavaScript 编写新的 React 组件。
2. 如果你在 JavaScript 中使用了 TypeScript 特有的类型定义和语法，可能会出现错误。你可以通过在 `.ts` 或 `.tsx` 文件中使用 `@ts-ignore` 来忽略这些错误，或者逐渐将代码转换为 JavaScript。

在开始使用 Ant Design Pro 6.0 进行 JavaScript 开发之前，你可能需要了解 Ant Design Pro 的 JavaScript 文档。你可以查看 Ant Design 官方文档中的 "TypeScript 支持" 部分，其中包含了一些 TypeScript 和 JavaScript 混合使用的示例代码。

我希望这些信息对你有所帮助！如果你有任何其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！感谢您的问题。对于 Ant Design Pro 6.0，官方推荐使用 TypeScript 进行开发，但您也可以继续使用 JavaScript 进行开发，不过需要手动将 TypeScript 代码转换为 JavaScript。当然，这样可能会导致一些类型检查的缺失和其他 TypeScript 特性的不可用。

如果您想继续使用 JavaScript 进行开发，您可以按照以下步骤进行操作：

1. 首先，安装 Ant Design Pro CLI 工具：
   ```bash
   npm i @ant-design/pro-cli -g
   ```

2. 创建一个新的项目：
   ```bash
   pro new my-app
   ```

3. 进入项目目录：
   ```bash
   cd my-app
   ```

4. 修改 `tsconfig.json` 文件，将 `"strict"` 配置项改为 `false`：
   ```json
   {
     "compilerOptions": {
       "strict": false
     }
   }
   ```

5. 使用 JavaScript 进行开发，可以编写你的 JavaScript 代码了。

需要注意的是，使用 JavaScript 进行开发可能会限制一些 TypeScript 的功能和优势，例如类型检查和自动补全等。因此，建议您在可能的情况下使用 TypeScript 进行开发，以获得更好的开发体验和类型安全。

如果您想深入了解如何在 Ant Design Pro 6.0 中使用 TypeScript，您可以阅读官方文档 [使用 TypeScript](https://pro.ant.design/docs/use-typescript-cn) 获取更多信息和示例代码。

希望这些信息对您有所帮助！如果您有任何其他问题，请随时提问。

**Comment by chenshuai2144** [comment]
一定要用 ts 的。js 的版本的不维护了
