### ISSUE TITLE
🧐[问题 | question] ProTable的列设置按钮被设置后可以出现徽标数或高亮吗？

### ISSUE THREAD

**Issue by HaiJunCai8** [ant-design/ant-design-pro#10954]
### 🧐 问题描述 | Problem description

ProTable组件工具栏上列设置功能如果设置了某些列隐藏之后，可以让列设置按钮高亮或者出现徽标数吗？目的是提醒用户这里被设置了，有大佬知道怎么实现吗？急急急

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/106509695/70d6ecf0-4204-47b4-a166-43072e9e5c7d)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 😀 解决方案 | Solution

ProTable的列设置功能是Ant Design Pro提供的一个非常方便的功能。要实现列设置按钮高亮或者出现徽标数来提醒用户某些列被隐藏了，可以使用ProTable的API和一些自定义逻辑来实现。

#### 1. 使用徽标数Badge来提醒用户

可以使用Ant Design的`Badge`组件来实现徽标数的效果。在ProTable中，我们可以通过记录被隐藏的列的数量，并将其作为徽标数显示在列设置按钮上。以下是示例代码：

```jsx
import { Badge, ProTable } from 'ant-design-pro';
import { useState } from 'react';

const columns = [
  // 列定义...
];

const DemoTable = () => {
  const [hiddenColumns, setHiddenColumns] = useState([]);

  const handleColumnHide = (hiddenColumns) => {
    setHiddenColumns(hiddenColumns);
  };

  const renderColumnSetting = () => {
    const badgeCount = hiddenColumns.length;
    return (
      <Badge count={badgeCount}>
        <ProTable
          columns={columns}
          options={{
            columnSetting: {
              hideable: true,
              onColumnHide: handleColumnHide,
            },
          }}
        />
      </Badge>
    );
  };

  return renderColumnSetting();
};

export default DemoTable;
```

通过`useState`来维护被隐藏的列的列表，并在`handleColumnHide`回调函数中更新状态。然后，在列设置按钮外部使用`Badge`组件，将隐藏的列的数量作为徽标数进行展示。

#### 2. 使用样式来高亮列设置按钮

如果要实现高亮效果，可以通过自定义样式来实现。以下是示例代码：

```jsx
import { ProTable } from 'ant-design-pro';
import { useState } from 'react';

const columns = [
  // 列定义...
];

const DemoTable = () => {
  const [hiddenColumns, setHiddenColumns] = useState([]);
  const [highlight, setHighlight] = useState(false);

  const handleColumnHide = (hiddenColumns) => {
    setHiddenColumns(hiddenColumns);
    setHighlight(hiddenColumns.length > 0);
  };

  const renderColumnSetting = () => {
    const tableClass = highlight ? 'pro-table-highlight' : '';
    return (
      <div className={tableClass}>
        <ProTable
          columns={columns}
          options={{
            columnSetting: {
              hideable: true,
              onColumnHide: handleColumnHide,
            },
          }}
        />
      </div>
    );
  };

  return renderColumnSetting();
};

export default DemoTable;
```

在上述代码中，首先使用`useState`来维护被隐藏的列的列表和高亮状态。然后，在`handleColumnHide`回调函数中根据隐藏的列数量来决定是否要高亮展示。通过添加一个自定义的CSS类名来实现高亮的效果。

#### 3. 更多参考资料

- ProTable官方文档：[https://protable.ant.design/](https://protable.ant.design/)
- Ant Design文档 - Badge 徽标数：[https://ant.design/components/badge-cn/](https://ant.design/components/badge-cn/)
- Ant Design Pro官方文档：[https://pro.ant.design/](https://pro.ant.design/)

希望以上解决方案对你有帮助！如有其他疑问，请随时提问。

**Comment by HaiJunCai8** [comment]
我用的@ant-design/pro-components版本是2.3.59，ProTable组件里面options属性里面没有columnSetting属性设置

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🧐 问题解答 | Answer

ProTable组件的列设置功能默认情况下不会为隐藏的列添加徽标数或高亮。但是你可以通过自定义逻辑实现这个功能。

一种简单的方法是在每个被隐藏的列的`column`对象中添加一个`hidden`属性，并在工具栏的列设置按钮中计算隐藏列的数量，然后根据数量来设置徽标数或高亮。

以下是一个示例实现的代码：

```jsx
import React, { useState } from 'react';
import { Table, Button, Badge } from 'antd';

const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
  },
  // 添加一个hidden属性来标记列是否隐藏
  {
    title: '性别',
    dataIndex: 'gender',
    key: 'gender',
    hidden: false,
  },
];

const data = [
  {
    key: '1',
    name: '张三',
    age: 18,
    gender: '男',
  },
  {
    key: '2',
    name: '李四',
    age: 22,
    gender: '女',
  },
  {
    key: '3',
    name: '王五',
    age: 30,
    gender: '男',
  },
];

const ProTableDemo = () => {
  const [hiddenColumns, setHiddenColumns] = useState([]);

  const handleColumnHide = (column) => {
    setHiddenColumns((prevHiddenColumns) => [...prevHiddenColumns, column]);
  };

  const handleColumnShow = (column) => {
    setHiddenColumns((prevHiddenColumns) =>
      prevHiddenColumns.filter((col) => col !== column)
    );
  };

  // 计算隐藏列的数量
  const hiddenColumnsCount = hiddenColumns.length;

  // 自定义render方法用于显示隐藏列的徽标数
  const renderColumnTitle = (title, column) => {
    const isHidden = hiddenColumns.includes(column);

    return (
      <>
        {title}
        {isHidden && <Badge count={1} style={{ marginLeft: 8 }} />}
      </>
    );
  };

  return (
    <>
      <Table
        columns={columns.filter((column) => !hiddenColumns.includes(column))}
        dataSource={data}
      />
      <Button onClick={() => handleColumnHide(columns[2])}>隐藏列</Button>
      <Button onClick={() => handleColumnShow(columns[2])}>显示列</Button>
      {/* 显示隐藏列的徽标数 */}
      {hiddenColumnsCount > 0 && (
        <Badge count={hiddenColumnsCount} style={{ marginLeft: 8 }} />
      )}
    </>
  );
};

export default ProTableDemo;
```

在这个示例中，我们通过在列配置对象中添加了一个`hidden`属性，来标记列是否隐藏。然后我们使用`useState`来维护一个`hiddenColumns`的状态数组，用于存储所有被隐藏的列的配置对象。在`handleColumnHide`和`handleColumnShow`方法中，我们分别将被隐藏的列添加到`hiddenColumns`数组中或从中移除。

然后，在渲染表格列时，我们使用`filter`方法来排除被隐藏的列，并在列标题中使用`renderColumnTitle`方法为隐藏的列添加徽标数。

最后，我们在工具栏中显示了隐藏列的徽标数。

这只是其中的一种实现方法，你可以根据项目的具体需求进行调整。

### 📖 相关文档 | Documentation
- [Ant Design ProTable](https://procomponents.ant.design/components/table/)
- [React](https://reactjs.org/)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🧐 问题回答 | Answer

感谢您的问题！根据您的描述，您想在 ProTable 组件的列设置按钮中添加徽标数或高亮以提醒用户某些列已被设置隐藏。

要实现这个功能，您可以借助 [Ant Design](https://ant.design/) 提供的 `Badge` 组件和 React 的状态管理，比如使用 `useState` 来跟踪隐藏列的数量。以下是一个示例代码以供参考：

```jsx
import React, { useState } from 'react';
import { Table, Badge, Button } from 'antd';

const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
  },
  // 其他列...
];

const data = [
  {
    key: '1',
    name: '张三',
  },
  // 其他数据...
];

const App = () => {
  const [hiddenColumns, setHiddenColumns] = useState([]);

  const handleColumnChange = (hiddenColumns) => {
    setHiddenColumns(hiddenColumns);
  };

  return (
    <div>
      <Button type="primary" onClick={() => console.log(hiddenColumns)}>
        打印隐藏列
      </Button>
      <Badge count={hiddenColumns.length}>
        <Table
          columns={columns}
          dataSource={data}
          onChange={handleColumnChange}
          rowKey="key"
          scroll={{ x: 'max-content' }}
          expandable={{
            expandedRowRender: (record) => <p>{record.description}</p>,
          }}
        />
      </Badge>
    </div>
  );
};

export default App;
```

在上述示例代码中，我们使用 `Badge` 组件来显示徽标数，并通过 `useState` 来跟踪隐藏列的数量 `hiddenColumns`。通过 `handleColumnChange` 方法，您可以更新 `hiddenColumns` 的值。这样，每当列设置按钮被点击时，我们可以获取到最新的隐藏列并更新徽标数。

同时，我注意到您提到的 ProTable 组件的图片显示了一个高亮的效果。如果您想要为列设置按钮添加高亮的效果，您可以通过 CSS 来实现。例如，您可以为按钮添加一个类名，然后根据某些条件来设置该类名的样式。

希望以上信息能帮到您！如果还有任何疑问，请随时提问。

**Comment by chenshuai2144** [comment]
不支持哦，ProTable组件的列设置按钮在设置某些列隐藏之后，并不能高亮或者出现徽标数。如果你希望在列设置后有类似的效果，你需要自己进行定制实现。可以尝试通过自定义CSS样式来修改按钮的外观，或者使用JavaScript来监听列设置的变化并添加相应的样式或徽标数。希望可以帮到你！
