### ISSUE TITLE
npm安装ant design pro 卡住在执行 npm i @ant-design/pro-cli -g这个命令

### ISSUE THREAD

**Issue by sudashui123** [ant-design/ant-design-pro#10955]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


抱歉，我只能处理关于 React 的前端问题。你的问题似乎与安装 Ant Design Pro CLI 有关，但它不是一个前端问题。如果你有其他与 React 前端相关的问题，我会很高兴去帮助你解决它们。

**Comment by chenshuai2144** [comment]
你在执行 `npm i @ant-design/pro-cli -g` 这个命令时卡住了。这个问题可能是由于网络环境不佳所导致的。你可以尝试使用淘宝镜像源来安装。你可以先安装 `cnpm`（淘宝镜像源的命令行工具），然后使用 `cnpm i @ant-design/pro-cli -g` 命令来安装。安装完成后，你就可以继续使用了。

另外，推荐使用 npm、yarn 或 pnpm 这些工具来进行开发。这些工具不仅可以在开发环境中轻松调试，并且在生产环境中打包部署也很方便。如果你的网络环境不太好，可以尝试使用 cnpm 安装依赖。
