### ISSUE TITLE
🧐[问题 | question] pnpm安装依赖会出现不同项目引入的版本不一样

### ISSUE THREAD

**Issue by Chill7773** [ant-design/ant-design-pro#10959]
### 🧐 问题描述 | Problem description

首先使用pnpm安装项目，会出现以下两个版本的包：
![image](https://github.com/ant-design/ant-design-pro/assets/39217534/df74e967-5cf9-49c0-80ff-8058f8a70096)
但是在不同项目下会出现引入的版本不同：
<img width="672" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/39217534/a07aaa42-86f3-4943-8235-17258b806b7d">
![image](https://github.com/ant-design/ant-design-pro/assets/39217534/c222e444-0a2e-40d9-b2e9-341dc3cdd1eb)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🧐 问题分析 | Problem analysis

根据你描述的问题，pnpm 在不同项目下引入的包版本可能会不同。这可能是因为项目中的依赖关系没有被正确地处理或解析导致的。

### 💡 解决方案 | Solution

为了确保在不同项目中引入的包版本一致，请按照以下步骤进行操作：

1. 确保你的项目中使用了正确的依赖项。可以使用 `pnpm list` 命令来查看项目的依赖树，确保项目中的依赖项是正确的。

2. 确保项目中的 pnpm 版本一致。使用 `pnpm --version` 命令来检查 pnpm 的版本。如果版本不一致，可以尝试升级或降级到同一个版本。

3. 确保你的项目使用了正确的依赖管理文件。pnpm 支持使用 `package.json` 和 `pnpm-lock.yaml` 来管理依赖项。确保这两个文件与你的项目一致，并且正确地记录了依赖关系。

4. 如果你的项目使用了私有仓库或者自定义的源，请确保这些配置正确无误。可以通过 `pnpm config get registry` 命令来查看当前的仓库配置。

5. 确保你的项目中的依赖项都是从同一个仓库安装的。你可以使用 `pnpm why <package-name>` 命令来查看某个包是从哪个仓库安装的。

如果以上解决方案仍未解决您的问题，请提供更多的代码示例以及附带您的操作系统、Node 版本和浏览器版本的信息，这将有助于更详细地分析和解决您的问题。

### 📖 相关文档 | Related documentation

- [pnpm 官方文档 (Official Documentation)](https://pnpm.js.org/)
- [pnpm GitHub 仓库 (GitHub Repository)](https://github.com/pnpm/pnpm)
