### ISSUE TITLE
antd-pro两个页面之间传递参数，第一次跳转可以正常传递参数，但是一刷新页面，参数就为undefined了。

### ISSUE THREAD

**Issue by naWang1227** [ant-design/ant-design-pro#1096]
代码如下：
方法一：<Link
            to={{
              pathname: '/label/detail',
              query: {
                id: dataItem.id,
              },
            }}
            title="详情"
          >
            <Icon type="file-text" />详情
          </Link>,
方法二：
this.props.dispatch(routerRedux.push({
      pathname: '/label/detail',
      query: {
        id: id,
      },
    }));

两种方法页面第一次跳转可以正常传递参数，但是一刷新页面，参数就为undefined了。

**Comment by chenshuai2144** [comment]
保存在内存里的参数都会在刷新之后，内存会被回收的。
要保存可以试试持久化的方式 url传参这些的

**Comment by naWang1227** [comment]
谢谢解答。按照此方法已解决。

**Comment by fanbajiu** [comment]
有什么方式可以避免state传参刷新后为undefined吗？已配置browser，本地正常，一到线上刷新页面就undefined

**Comment by chenshuai2144** [comment]
改成 search ，而不是state
