### ISSUE TITLE
🐛 [BUG]mf-dep____vendor.397377eb.js:119662 Warning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

### ISSUE THREAD

**Issue by gaspire** [ant-design/ant-design-pro#10964]
### 🐛 bug 描述

mf-dep____vendor.397377eb.js:119662 Warning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

### 📷 复现步骤 | Recurrence steps

npm i @ant-design/pro-cli -g
pro create myapp
yarn start

打开浏览器控制台出现警告

### 🏞 期望结果 | Expected results
无警告
 
### © 版本信息

- Ant Design Pro 版本: 5.0
- umi 版本 4.0
- 浏览器环境 chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/discussions/41855

看这里
