### ISSUE TITLE
🧐[问题 | question] ant design pro 6.0 怎么修改端口号？

### ISSUE THREAD

**Issue by epubreader** [ant-design/ant-design-pro#10979]
ant design pro 6.0 怎么修改端口号？
我试过了修改package.json, 都不起作用

   "start": "cross-env UMI_ENV=dev PORT=8300 max dev",
   "start": "cross-env UMI_ENV=dev port=8300 max dev",****

**Comment by CyberQin** [comment]
在你的当前工程下，新建.env文件，并在文件内写入
PORT=8300

**Comment by joesdu** [comment]
"start": "cross-env PORT=8848 max dev"

**Comment by epubreader** [comment]
> "start": "cross-env PORT=8848 max dev"

谢谢， 可以了， 我之前是用npm run dev命令启动的，所以端口没有变，
dev 和start 命令什么区别？

**Comment by wangzhoubin** [comment]
> > "start": "cross-env PORT=8848 max dev"
> 
> 谢谢， 可以了， 我之前是用npm run dev命令启动的，所以端口没有变， dev 和start 命令什么区别？

看 命令 对应的内容，start:dev, start:test, start:prod,他对应的配置是不一样的，比如是否开启 mock 等，对比一下就知道了。 相当于一个快捷启动命令，你可以自己命名

**Comment by joesdu** [comment]
是的.

> > > "start": "cross-env PORT=8848 max dev"
> > 
> > 
> > 谢谢， 可以了， 我之前是用npm run dev命令启动的，所以端口没有变， dev 和start 命令什么区别？
> 
> 看 命令 对应的内容，start:dev, start:test, start:prod,他对应的配置是不一样的，比如是否开启 mock 等，对比一下就知道了。 相当于一个快捷启动命令，你可以自己命名

**Comment by wangzhoubin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by joesdu** [comment]
问题解决了的话,建议及时的关闭issues
