### ISSUE TITLE
fetchUserInfo 请求中，希望页面有个loading 👑 [需求 | Feature]

### ISSUE THREAD

**Issue by Statfine** [ant-design/ant-design-pro#10985]
### 🥰 需求描述 | Requirements description

fetchUserInfo请求可能因为环境影响比较慢，但是页面渲染又依赖fetchUserInfo的返回， 这就导致等待期间页面是白屏

### 🧐 解决方案 | Solution

期望增加fetchUserInfo请求状态的显示

**Comment by Statfine** [comment]
目前做法
```
// 动态添加loading，避免fetchUserInfo耗时
const loading = document.createElement('div');
const rootLoading = createRoot(loading);
rootLoading.render(loadingSpin);
document.body.appendChild(loading);

// fetchUserInfo  异步耗时请求
const currentUser = await fetchUserInfo();

// 返回后移除loading
document.body.removeChild(loading);
`

**Comment by WuJiY** [comment]
用 react-query 获取

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


可以通过在页面上添加一个loading状态来指示fetchUserInfo请求的进度。以下是一个简单的解决方案示例：

1. 在页面上创建一个loading组件，可以是一个loading图标或者动画。
2. 在fetchUserInfo请求开始前，将loading状态设为true，在请求结束后，将loading状态设为false，并且根据请求结果渲染页面内容。
3. 在组件中使用状态变量来控制loading组件的显示与隐藏。

下面是一个React函数组件的示例代码：

```javascript
import React, { useState, useEffect } from "react";

const UserInfo = () => {
  const [loading, setLoading] = useState(true);
  const [userInfo, setUserInfo] = useState(null);

  useEffect(() => {
    // 发起fetchUserInfo请求
    fetchUserInfo()
      .then((response) => {
        // 处理请求结果并更新状态
        setUserInfo(response.data);
      })
      .catch((error) => {
        console.error("请求出错：", error);
      })
      .finally(() => {
        // 请求结束，隐藏loading
        setLoading(false);
      });
  }, []);

  const fetchUserInfo = () => {
    // 进行fetchUserInfo请求的具体实现
    return fetch("https://api.example.com/userInfo")
      .then((response) => response.json())
      .catch((error) => {
        console.error("请求出错：", error);
      });
  };

  return (
    <div>
      {loading ? (
        <div>Loading...</div>
      ) : (
        <div>
          {userInfo ? (
            <div>
              <h1>{userInfo.name}</h1>
              <p>{userInfo.bio}</p>
            </div>
          ) : (
            <div>无用户信息</div>
          )}
        </div>
      )}
    </div>
  );
};

export default UserInfo;
```

请注意，上述代码中的fetchUserInfo函数只是一个示例，你需要根据实际情况进行实现和替换。此外，loading组件的样式和具体实现可以根据项目需要进行定制。

如果需要更多关于React的学习资源和文档，请参考官方文档：[React官方文档](https://reactjs.org/docs/getting-started.html)。

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 建议的解决方案 | Suggested Solution

在React中实现loading状态通常有两种常见的方式：
1. 使用状态管理库（例如Redux）来管理loading状态。
2. 使用React的内置特性（例如useState和useEffect）来处理loading状态。

下面我将为你提供使用useState和useEffect的示例代码：

#### 1. 使用useState和useEffect来管理loading状态

```jsx
import React, { useState, useEffect } from 'react';

function UserInfo() {
  const [loading, setLoading] = useState(true);
  const [userData, setUserData] = useState(null);

  useEffect(() => {
    async function fetchUserInfo() {
      try {
        // 等待fetchUserInfo请求的结果
        const response = await fetch('your-api-url');
        const data = await response.json();
        setUserData(data); // 更新用户数据
        setLoading(false); // 将loading状态设置为false，显示用户数据
      } catch (error) {
        console.error('Error fetching user info: ', error);
        setLoading(false); // 出错时也要将loading状态设置为false，停止loading状态
      }
    }

    fetchUserInfo();
  }, []); // 第二个参数用来避免useEffect在每次渲染时都重新运行

  return (
    <div>
      {loading ? (
        <p>Loading...</p>
      ) : (
        <div>
          {userData && (
            <div>
              <p>Name: {userData.name}</p>
              <p>Email: {userData.email}</p>
              {/* 其他用户信息 */}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default UserInfo;
```

在上面的代码中，我们使用了useState来管理loading状态和用户数据。当loading为true时，显示"Loading..."文本。当fetchUserInfo请求完成并成功获取到用户数据时，loading状态设置为false，显示用户数据。如果在获取数据时发生错误，也会将loading状态设置为false，停止loading状态。

请根据你自己的项目需求，将代码中的'your-api-url'替换为实际的API地址。

#### 2. 使用第三方库react-loading-skeleton实现loading效果

如果你希望在loading期间显示一个骨架屏效果，可以使用第三方库`react-loading-skeleton`。这个库提供了一种简单的方式来显示加载状态。

首先，安装`react-loading-skeleton`库：

```bash
npm install react-loading-skeleton
```

然后，使用以下代码实现loading状态的展示：

```jsx
import React, { useState, useEffect } from 'react';
import Skeleton from 'react-loading-skeleton';

function UserInfo() {
  const [loading, setLoading] = useState(true);
  const [userData, setUserData] = useState(null);

  useEffect(() => {
    async function fetchUserInfo() {
      try {
        // 等待fetchUserInfo请求的结果
        const response = await fetch('your-api-url');
        const data = await response.json();
        setUserData(data); // 更新用户数据
        setLoading(false); // 将loading状态设置为false，显示用户数据
      } catch (error) {
        console.error('Error fetching user info: ', error);
        setLoading(false); // 出错时也要将loading状态设置为false，停止loading状态
      }
    }

    fetchUserInfo();
  }, []); // 第二个参数用来避免useEffect在每次渲染时都重新运行

  return (
    <div>
      {loading ? (
        <div>
          {/* 骨架屏 */}
          <Skeleton height={50} count={3} />
        </div>
      ) : (
        <div>
          {userData && (
            <div>
              <p>Name: {userData.name}</p>
              <p>Email: {userData.email}</p>
              {/* 其他用户信息 */}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default UserInfo;
```

在上面的代码中，我们导入了`react-loading-skeleton`库，然后使用骨架屏组件替代原本的loading文本，以提供更好的用户体验。

以上是两种常见的解决方案，你可以根据你的项目需要选择其中之一，并根据实际情况进行调整。如果需要更多详细

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 方案一：使用loading组件

你可以在页面上添加一个loading组件来展示fetchUserInfo请求的加载状态。当fetchUserInfo请求发送时，展示loading组件，当请求返回时，隐藏loading组件。

下面是一个示例代码：

```jsx
import React, { useState, useEffect } from 'react';

function UserPage() {
  const [loading, setLoading] = useState(true);
  const [userInfo, setUserInfo] = useState(null);

  useEffect(() => {
    const fetchUserInfo = async () => {
      // 发送fetchUserInfo请求，这里假设使用fetch函数发送请求
      const response = await fetch('https://api.example.com/userinfo');
      const data = await response.json();
      setUserInfo(data);
      setLoading(false); // 请求返回后隐藏loading组件
    };

    fetchUserInfo();
  }, []);

  return (
    <div>
      {loading && <div>Loading...</div>}
      {!loading && userInfo && (
        <div>
          <h2>{userInfo.name}</h2>
          <p>{userInfo.email}</p>
        </div>
      )}
    </div>
  );
}
```

在上面的代码中，我们使用`useState`来创建`loading`和`userInfo`两个状态变量，`loading`用于控制加载状态的显示，`userInfo`保存fetchUserInfo请求返回的数据。

当fetchUserInfo请求发送时，`loading`为true，展示"Loading..."文本，当请求返回并且`userInfo`有值时，隐藏loading组件并展示用户信息。

你也可以使用第三方UI组件库中的loading组件来优化展示效果，比如[Ant Design](https://ant.design/)或者[Material-UI](https://material-ui.com/)等。

### 📖 相关文档 | Related documentation

- [React官方文档 - 使用Effect Hook](https://zh-hans.reactjs.org/docs/hooks-effect.html)
- [Ant Design - Spin Loading Component](https://ant.design/components/spin/)

---

### 🎉 解决方案二：使用CSS样式控制loading效果

你也可以使用CSS样式控制loading效果。下面给出一个简单的示例代码：

```jsx
import React, { useState, useEffect } from 'react';

function UserPage() {
  const [loading, setLoading] = useState(true);
  const [userInfo, setUserInfo] = useState(null);

  useEffect(() => {
    const fetchUserInfo = async () => {
      // 发送fetchUserInfo请求，这里假设使用fetch函数发送请求
      const response = await fetch('https://api.example.com/userinfo');
      const data = await response.json();
      setUserInfo(data);
      setLoading(false); // 请求返回后隐藏loading样式
    };

    fetchUserInfo();
  }, []);

  return (
    <div>
      {loading && <div className="loading">Loading...</div>}
      {!loading && userInfo && (
        <div>
          <h2>{userInfo.name}</h2>
          <p>{userInfo.email}</p>
        </div>
      )}
    </div>
  );
}
```

在上面的代码中，我们使用`useState`来创建`loading`和`userInfo`两个状态变量。当fetchUserInfo请求发送时，`loading`为true，在`loading`组件中添加一个CSS类名为`loading`，并在CSS文件或者内联样式中定义`loading`样式。

```css
.loading {
  /* 在这里定义loading样式 */
  /* 例如： */
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100px;
}
```

这个示例只是一个简单的loading样式示例，你可以根据自己的需求进一步定制样式。

### 📖 相关文档 | Related documentation

- [React官方文档 - 使用Effect Hook](https://zh-hans.reactjs.org/docs/hooks-effect.html)
- [React官方文档 - 条件渲染](https://zh-hans.reactjs.org/docs/conditional-rendering.html)

如果以上解决方案不能满足你的需求，请提供更具体的问题描述，我将尽力提供帮助。
