### ISSUE TITLE
umi build部署后，刷新页面会无法获页面资源🐛 [BUG]

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design-pro#10989]
### 🐛 bug 描述

构建时候不开启`exportStatic`，仅生成一个html。部署在static server (nginx/nest.js)时候，加载根路径没问题，但是一旦进入了子路由，再进行刷新时，就无法获取页面文件。

例如我的路由里有个/files的路由，切换到这个页面再刷新后，就会报如下错误。
<img width="642" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/6435874/c7754a8d-e43f-4085-a4fb-f7f3670e3932">

在调试模式下，不会出现该问题。

同时，若开启`exportStatic`，在用build构建导出后，会导致base url包含路由字段，例如在file页面访问public/logo.svg，其访问的是`http://localhost:3000/files/public/logo.svg`，而不是`http://localhost:3000/public/logo.svg`。

### 📷 复现步骤 | Recurrence steps

如上所述，umi 4.0.52进行build，并部署在静态服务器上

### © 版本信息

- Ant Design Pro 版本: [6.0.0]
- umi 版本 [4.0.52]
- 浏览器环境 [Chrome 117.0.5938.88]
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的描述，似乎是部署后刷新页面无法获取页面资源的问题。我可以提供一些解决方案给你尝试一下。

首先，关于刷新页面无法获取页面资源的问题，可能是因为路由配置导致的。你可以在路由配置中添加一个 `history` 属性，并设置为 `hash` 模式，以确保在刷新页面时仍能正确加载资源。示例代码如下：

```jsx
import { history } from 'umi';

export const dva = {
  config: {
    history: {
      type: 'hash',
    },
  },
};
```

关于 `exportStatic` 开启后导致 base URL 包含路由字段的问题，你可以尝试在路由配置中添加 `base` 属性，设置为你期望的 base URL，以确保正确的资源访问。示例代码如下：

```jsx
export default [
  {
    path: '/',
    component: '@/layouts/index',
    routes: [
      {
        path: '/files',
        component: '@/pages/files',
        routes: [],
      },
    ],
  },
];

export const base = '/'; // 设置你期望的 base URL
```

这样，即使开启了 `exportStatic`，访问 `/public/logo.svg` 时也会正确地使用 `http://localhost:3000/public/logo.svg`。

另外，如果问题仍然存在，你可以检查一下静态服务器的配置，确保它正确地处理子路由的资源请求。

希望以上解决方案能够帮助到你！如果有任何问题，请随时向我提问。此外，你还可以参考 Umi 官方文档（https://umijs.org/docs/deployment）了解更多关于部署的信息。
