### ISSUE TITLE
🧐[问题 | question] Question for blocks 

### ISSUE THREAD

**Issue by muhammedtalhacalis** [ant-design/ant-design-pro#10983]
🧐 问题描述 | Problem description
Hello everyone, i want use the ant-pro-blocks and templates like in this link https://v4-pro.ant.design/docs/block#block-and-template, 
but i couldn't. Please help me understand and use ant-blocks and templates. I setup already ant-design-pro-v4 but can't see any action point like in link (https://v4-pro.ant.design/docs/block#block-and-template)

![image](https://github.com/ant-design/ant-design-pro/assets/58453727/34238a94-f1dd-467a-8421-f57c28934b0c)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👋你好！感谢你的问题。根据你的描述，你想了解如何使用 ant-design-pro-v4 中的 ant-pro-blocks 和模板。我将为你提供解决方案。

首先，请确保你已经正确安装了 ant-design-pro-v4，并且项目能够正常运行。

使用 ant-pro-blocks 和模板的过程如下：

1. 在你的项目中，找到你希望添加 ant-pro-blocks 的页面文件，通常是在 `/src/pages` 目录下。

2. 在你选择的页面文件中，使用导入语句引入需要的 ant-pro-blocks 或者模板。例如，在你的文件头部添加如下代码：

```jsx
import { Card } from 'antd';
import { PageContainer } from '@ant-design/pro-layout';
import React from 'react';

const YourPageName = () => {
  // 这里是你的页面内容
  return (
    <PageContainer>
      <Card>
        {/* 这里是 ant-pro-blocks 的内容 */}
      </Card>
    </PageContainer>
  );
};

export default YourPageName;
```

3. 在 `YourPageName` 组件中，你可以将 ant-pro-blocks 的内容放在 `<Card>` 组件的内部。你可以根据你的需要选择不同的 ant-pro-blocks 或者自定义模板来填充 `<Card>` 组件的内容。

4. 根据你提供的链接看起来你想使用区块和模板来构建页面，其中的示例代码可能是这样的：

```jsx
import { PageContainer } from '@ant-design/pro-layout';
import { Card, Typography } from 'antd';

const YourPageName = () => {
  return (
    <PageContainer>
      <Card>
        <Typography.Title level={2}>Welcome to your page!</Typography.Title>
        <Typography.Paragraph>
          This is an example block content. Replace this with your own content.
        </Typography.Paragraph>
      </Card>
    </PageContainer>
  );
};

export default YourPageName;
```

在上面的示例代码中，我们使用了 `<Card>`、`<Typography.Title>` 和 `<Typography.Paragraph>` 分别来呈现标题和段落内容。

5. 你可以根据自己的需求修改和定制 `<Card>` 组件的样式和内容，和其他的 antd 组件一样，你可以查看 [antd 官方文档](https://ant.design/components/overview-cn/) 来了解更多可用组件和组件属性的信息。

请注意，ant-design-pro-v4 提供了丰富的 ant-pro-blocks 和模板供你使用。你可以在官方文档中找到各种不同种类的区块和模板，以及对应的示例代码。你可以在这里查看[区块和模板的文档](https://v4-pro.ant.design/docs/block#block-and-template)。

希望这个解决方案能帮到你！如果还有任何问题，请随时提问。

**Comment by chenshuai2144** [comment]
blocks  停止维护啦，建议不要使用
