### ISSUE TITLE
🧐[问题 | question] proxy 中 把 "/api/"改成"/"后，本地开发环境无法实时预览修改，且会展示上一次的修改。

### ISSUE THREAD

**Issue by hVenus** [ant-design/ant-design-pro#10986]
### 🧐 问题描述 | Problem description

proxy.ts 中 把 "/api/"改成"/"后，本地开发环境无法实时预览修改，且会展示上一次的修改。

### 💻 示例代码 | Sample code

```
   // 这是原代理设置
    '/api/': {
      // 要代理的地址
      target: 'http://api.myapi.cn/',
      // 配置了这个可以从 http 代理到 https
      // 依赖 origin 的功能可能需要这个，比如 cookie
      changeOrigin: true,
    },
```
由于服务器上的接口没有api前缀，于是我把 “/api/” 改成了 “/” ，如下

```
    '/': {
      // 要代理的地址
      target: 'http://api.myapi.cn/',
      // 配置了这个可以从 http 代理到 https
      // 依赖 origin 的功能可能需要这个，比如 cookie
      changeOrigin: true,
    },
```

接口地址如下：

```
export async function queryGoods(params?: any) {
  return request('/goods/listing', {
    params,
  });
}
```

这样做，虽然接口可以用。但是，本地开发环境无法实时预览修改后的结果，必须要编译之后，上传到服务器，本地开发环境刷新才能看到修改后的效果。
哪怕是多编译几次之后，不上传服务器，本地也刷不出最新结果。

然后，我试了很多次，重建了好几次项目代码，才发现这个问题。一开始以为是版本不对，或者是自己修改了什么核心文件，导致了这个问题。

今天终于发现跟这个proxy有关。

只要是 "/api/" 就没问题，一切正常。

就算是保留原来的 "/api/"设置，再加一条 “/”的设置，都不行，代码如下：

```
  dev: {
    // localhost:8000/api/** -> https://preview.pro.ant.design/api/**
    '/api/': {
      // 要代理的地址
      target: 'http://api.myapi.cn/',
      // 配置了这个可以从 http 代理到 https
      // 依赖 origin 的功能可能需要这个，比如 cookie
      changeOrigin: true,
    },
    '/': {
      // 要代理的地址
      target: 'http://api.myapi.cn/',
      // 配置了这个可以从 http 代理到 https
      // 依赖 origin 的功能可能需要这个，比如 cookie
      changeOrigin: true,
    },
  },
```

上面的设置一样出现这个问题。

你说必须要加个前缀，我能理解，到服务器上设置个转发也就行了。
可是文档里也没写这proxy必须要有前缀，就算必须要前缀，那么它不能实时预览修改了？不能实时预览修改也就算了，可它为什么会预览前一次的修改？代码都删了，甚至文件都删除了，它还是能显示。而且还是要上传到服务器，本地才能变更到当前修改。

不知道这是不是BUG,或者是我操作不得当，所以来问下。

因为，如果proxy必须要前缀，那么如果我对服务器没有操作权限，或者条件限制不能改服务器配置，这本地开发，跟部署不是有大问题？不见得改一下就上传一遍？这不得烦死？

### 🚑 其他信息 | Other information

OS: MacOS Ventura 13.5.2

Node：v16.20.2

浏览器 | browser：Chrome 116.0.5845.187

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 💡 解决方案 | Solution

根据你的描述，问题出现在将 `/api/` 改为 `/` 后，无法实时预览修改并且展示上一次的修改。这可能是由于缓存导致的问题。

一种解决方案是在代理设置中添加一个 `bypass` 函数来绕过缓存。这样，每次请求都将被发送到代理服务器，而不是从缓存中获取响应。你可以在 `devServer` 配置中添加以下代码：

```javascript
devServer: {
  proxy: {
    '/': {
      target: 'http://api.myapi.cn/',
      changeOrigin: true,
      bypass: function (req, res, proxyOptions) {
        if (req.headers.accept.indexOf('html') !== -1) {
          console.log('Skipping proxy for browser request.');
          return '/index.html';
        }
      },
    },
  },
},
```

上述代码中的 `bypass` 函数将会在每次请求时调用。如果请求的文件是 HTML 类型的，则绕过代理，返回 `/index.html` 文件，以确保每次请求都能实时预览修改。

另外，为了解决上一次的修改展示的问题，你可以在开发模式下，禁用浏览器的缓存设置。在 Chrome 浏览器中，按下 F12 打开开发者工具，点击 Network 选项卡，在 Disable cache 复选框中勾选上，然后刷新页面试试看。

希望以上解决方案能对你有所帮助！如果还有其他问题，请随时提问。

**Comment by XueMeijing** [comment]
看看是不是使用了devtool的override content覆盖接口，我碰到类似的，我覆盖的是xhr接口，结果不知道什么时候把css文件也给覆盖了，改了很多次都没效果

![image](https://github.com/ant-design/ant-design-pro/assets/35559153/66a43557-e142-456e-ac29-8af3e345c8e5)
