### ISSUE TITLE
🐛 [BUG]从服务器获取菜单，多tab模式下，tab上的icon图标是routes里的，并不是服务器返回的icon

### ISSUE THREAD

**Issue by xyylb** [ant-design/ant-design-pro#10984]
### 🐛 bug 描述
pro版本v6.0
从服务器获取菜单，多tab模式下，tab上的icon图标是routes里的，并不是服务器返回的icon

config.js
  //开启多tab布局
  keepalive: [/./],
  tabsLayout: {hasDropdown:true},

开启多tab布局的，另一个问题，当页面不用PageContainer包起来时候，左侧和上侧会多出来
按了下f12是因为这两个引起的，当用了PageContainer，会将padding设置成0
    padding-block: 32px;
    padding-inline: 40px;
![image](https://github.com/ant-design/ant-design-pro/assets/103179889/d46e094e-356b-4d52-a605-49bad71fc53e)

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0]
- umi 版本 4.0
- 浏览器环境 chrome

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


undefined

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案

根据你提供的信息，问题是在 Ant Design Pro 版本 6.0 下使用多标签模式时，从服务器获取的菜单图标未正确显示在选项卡上。另外，如果页面没有使用 PageContainer 组件包裹，会导致左侧和顶部多出一些间距。下面我将为你提供解决方案。

#### 1. 修复菜单图标显示问题

问题可能出现在配置文件中，请确保你的 `config.js` 文件中的 `tabsLayout` 选项正确设置，并且服务器返回的菜单数据中包含图标字段。你可以按照以下步骤检查和修复该问题：

1. 确保你的 `config.js` 文件中的 `tabsLayout` 设置为以下值：

```javascript
tabsLayout: { hasDropdown: true, iconRender: (tabProps) => tabProps.icon }
```

2. 确保你的服务器返回的菜单数据中包含图标字段，可以根据具体返回的数据结构进行调整。

3. 如果以上步骤都正确配置，但问题仍然存在，可能需要查看 `BasicLayout.js` 组件代码，确保选项卡的渲染逻辑正确。

#### 2. 修复页面布局问题

对于页面布局问题，你提到当没有使用 PageContainer 组件包裹时会多出一些间距。这是因为 PageContainer 组件会自动设置合适的内边距来适应页面布局，所以确保给每个页面使用 PageContainer 组件包裹起来即可解决该问题。例如：

```javascript
import { PageContainer } from '@ant-design/pro-layout';

export default () => {
  return (
    <PageContainer>
      {/* 页面内容 */}
    </PageContainer>
  );
}
```

确保每个页面都按照以上方式包裹起来，这样就能保证页面布局的一致性，并避免多余的间距出现。

#### 3. 相关文档

- Ant Design Pro 多选项卡布局：[https://pro.ant.design/docs/keep-alive-cn](https://pro.ant.design/docs/keep-alive-cn)
- Ant Design Pro 布局：[https://pro.ant.design/docs/layout-cn](https://pro.ant.design/docs/layout-cn)
- Ant Design Pro PageContainer 组件：[https://procomponents.ant.design/components/page-container](https://procomponents.ant.design/components/page-container)

通过检查和调整以上步骤，应该能够解决你遇到的问题。如果问题仍然存在，请提供更多详细的信息或代码示例，以便更好地帮助你解决问题。
