### ISSUE TITLE
在特定情况下跳转异常页面，点击返回首页，死循环

### ISSUE THREAD

**Issue by MorisHarA** [ant-design/ant-design-pro#1098]
如果menuData的第一个item配置authority，但是并没有拿到所需要的权限，那么将跳转至403页面，点击返回首页，getBashRedirect函数还是返回无权限的组件，导致死循环。

**Comment by chenshuai2144** [comment]
这个逻辑是对的吧？

你没有访问主页的权限就跳转到403页面
