### ISSUE TITLE
创建pro v5 版本时候选择simple SettingDrawer无法显示？ 🧐[问题 | question]

### ISSUE THREAD

**Issue by hcweb** [ant-design/ant-design-pro#10991]
### 🧐 问题描述 | Problem description
创建v5版本时候选择simple SettingDrawer无法显示，如果选怎complete是会显示的，这个要怎么处理

### 💻 示例代码 | Sample code
代码都没动过，才新建项目

### 🚑 其他信息 | Other information
暂无

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好！根据你的描述，问题可能是由于缺少必要的依赖或配置导致的。为了解决这个问题，你可以按照以下步骤进行尝试：

1. 确保你的项目中已安装了必要的依赖。可以使用以下命令检查并安装缺失的依赖：
```
npm install
```

2. 确保你的项目中已正确配置了设置抽屉相关的代码。你可以通过以下方式检查和配置：

- 首先，在你的项目里找到 `src/layouts/SettingsLayout.tsx` 文件，确保下面的代码段存在：

```jsx
import { SettingsDrawer } from 'pro-layout';

// ...

const BasicLayout: React.FC<BasicLayoutProps> = (props) => {
  // ...

  return (
    // ...
    <SettingsDrawer
      settings={settings}
      onSettingChange={onSettingChange}
    />
    // ...
  );
};
```

- 然后，在你的项目里找到 `src/defaultSettings.ts` 文件，确保下面的代码段存在：

```jsx
	export default {
	  // ...
	  navTheme: 'dark',
	  // ...
	  }
```

3. 如果以上步骤都已完成，并且问题仍然存在，请确保你的浏览器兼容性正常。你可以尝试在不同的浏览器中打开项目，检查是否有浏览器兼容性问题。

如果问题仍然存在，我建议你查阅 [pro-layout](https://github.com/ant-design/pro-layout) 相关的文档和社区讨论，以获取更详细和特定的解决方案。

**Comment by hcweb** [comment]
src/defaultSettings.ts还是config/defaultSettings.ts？   这些都存在  但是通过pro create创建选择的simple  SettingsDrawer默认是从@ant-design/pro-components中引入，另外请教大佬一个问题适配v5的依赖版本要如何更新到最新 比如antd版本  @ant-design/pro-table @ant-design/pro-layout等

**Comment by chenshuai2144** [comment]
pnpm update 就好了。

SettingsDrawer 是个组件，你当成一个组件来使用好了
