### ISSUE TITLE
🧐[问题 | question]我使用的动态路由，由服务端提供，这样我的登录或者其他页面如何不使用layout布局

### ISSUE THREAD

**Issue by liucaptainapp** [ant-design/ant-design-pro#10998]
### 🧐 问题描述 | Problem description

我使用的动态路由，有服务端提供，这样我的登录如何不使用layout布局，我开始是定义了一个登录的route数组，直接和服务端提供的路由放在一起（app.js的layput中），但是这样的话还是有layout样式在里面，比如上面有很明显的padding

### 💻 示例代码 | Sample code
`export default [<br>
  {
    name: '登录',
    path: '/login',
    parentId: null,
    layout: false,
    headerRender: false,
    footerRender: false,
    menuRender: false,
    menuHeaderRender: false,
    hideInMenu: true,
    hideChildrenInMenu: false,
    hideInBreadcrumb: false,
  }
];`

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser

**Comment by chenshuai2144** [comment]
pure:ture ，试试这个配置

**Comment by haobarry** [comment]
在路由里面配置

**Comment by liucaptainapp** [comment]
> pure:ture ，试试这个配置
我没有配置config里面的route，我所有的路由是通过appjs 里面Layout中的route配置的，没有找到不使用layout的配置属性，我之前旧版是通过Login.layout = false; 直接在页面组件中关掉layout样式，现在好像取消了这种写法。LeaseSaleRecordCenter.wrappers = ['@/wrappers/auth'];还有这种写法也没了
