### ISSUE TITLE
🧐[问题 | question]一级路由拥有子路由，一级路由无法点击跳转

### ISSUE THREAD

**Issue by EcoIris** [ant-design/ant-design-pro#10994]
### 🧐 问题描述 | Problem description

一组路由包括一级和二级，仅通过配置routes.js中的路由,是不是实现不了一级和二级都可以点击跳转的功能

```
  {
    path: '/school',
    name: 'school',
    component: './School',
    routes: [
      {
        path: 'activity',
        name: 'activity',
        component: './School/Activity',
      }
    ]
  },
```

### 🚑 其他信息 | Other information

如果配置路由实现不了是否可以通过subMenuItemRender自定义

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solution

根据您提供的路由配置，一级路由 `/school` 拥有一个子路由 `/school/activity`。如果一级路由无法点击跳转，可能是因为没有在相应的组件中正确渲染子路由链接。

首先，确保您在一级路由组件中使用了 `react-router-dom` 提供的导航链接组件 `Link` 或 `NavLink`。这样可以确保一级路由被点击时，能够正确导航到子路由。

例如，在 `./School` 组件中，您可以这样使用 `Link` 组件：

```jsx
import { Link } from 'react-router-dom';

const School = () => {
  return (
    <div>
      <h1>School</h1>
      <ul>
        <li>
          <Link to="/school/activity">Go to Activity</Link>
        </li>
      </ul>
    </div>
  );
};

export default School;
```

这样一级路由 `/school` 就可以点击跳转到子路由 `/school/activity`。

另外，如果您想自定义一级路由的导航链接，您可以使用 `Menu` 组件的 `subMenuItemRender` 属性。

```jsx
import { Menu } from 'antd';
import { NavLink } from 'react-router-dom';

const routes = [
  {
    path: '/school',
    name: 'school',
    component: './School',
    routes: [
      {
        path: '/school/activity',
        name: 'activity',
        component: './School/Activity',
      }
    ]
  },
];

const CustomMenu = () => {
  return (
    <Menu theme="dark" mode="horizontal">
      {routes.map((route) => (
        <Menu.Item key={route.name} >
          <NavLink to={route.path}>{route.name}</NavLink>
        </Menu.Item>
      ))}
    </Menu>
  );
};

export default CustomMenu;
```

这样您可以自定义一级路由的导航链接样式和行为。

请确保在您的组件中正确导入了相关的库（如 `react-router-dom` 和 `antd`）并安装了这些库的依赖。

### 📖 文档参考 | Documentation references

- `react-router-dom` 文档：[https://reactrouter.com/web/guides/quick-start](https://reactrouter.com/web/guides/quick-start)
- `antd` Menu 组件文档：[https://ant.design/components/menu/](https://ant.design/components/menu/)
