### ISSUE TITLE
关于路由配置的问题

### ISSUE THREAD

**Issue by liumin1128** [ant-design/ant-design-pro#110]
项目刚发布果断入坑，然后就遇到了问题，望解答，非常感谢O(∩_∩)O。
1. 在BasicLayout布局下，两个不同的目录，有两个相同的list路径，这两个会同时标记为激活状态。
2. 目前这种配置，视乎没办法做一个页面，但又不在侧边中显示出来...比如404，我并不希望404显示在侧边中（不换布局的情况下）

```
{
        name: '分类管理',
        icon: 'dashboard',
        path: 'fenlei',
        children: [
          {
            name: '分类审核',
            path: 'list',
            component: FenleiList,
          },
        ],
      },
      {
        name: '新闻管理',
        icon: 'dashboard',
        path: 'news',
        children: [
          {
            name: '新闻审核',
            path: 'list',
            component: Exception404,
          },
        ],
      },
```
我在想，现在的方案，应该是是从侧边的配置项，反向抽出路由配置吧？这个视乎有点颠倒了。如果从路由配置项里，抽出需要显示在侧边中的可能会清新一些（我是这样做的）。

**Comment by ddcat1115** [comment]
目前路由和菜单栏都是从同一份数据 [nav.js](https://github.com/ant-design/ant-design-pro/blob/master/src/common/nav.js) 中生成的，BasicLayout 里默认会把所有数据生成菜单栏，如果有些页面不用展现在菜单中，需要自己对 BasicLayout 中的生成菜单逻辑进行一些改造，可以配合 nav.js 里打标。如果路由和菜单结构真的很不一样，也可以考虑分成两份数据，这个得根据实际需求来了，脚手架里路由和菜单结构类似，也为了方便增删，所以只用了一份数据。

**Comment by gebilaoman** [comment]
是不是说，以后这块路由和菜单不会进行拆分了，也就是说不会维护这块的功能开发了。如果不维护的话，我就开始着手自己改BasicLayout的代码了

**Comment by linhanyang** [comment]
我看了下，可以不给name值就不会显示在左侧菜单。

**Comment by gebilaoman** [comment]
我试过了，治标不治本，title会显示undefiend。正在改这块代码，menu和nav分离

**Comment by linhanyang** [comment]
😔

**Comment by ddcat1115** [comment]
@gebilaoman 脚手架里暂时不会拆分，你可以根据需求自己修改

**Comment by linzehuan** [comment]
在 BasicLayout.js 方法 getNavMenuItems 添加可否在菜单显示的逻辑即可
