### ISSUE TITLE
🧐[问题 | question] ModalForm表单里有多个提交按钮，该怎么处理

### ISSUE THREAD

**Issue by epubreader** [ant-design/ant-design-pro#11000]
我在表单里新增了一个publish按钮， 想调用onApprove方法，而不是onSubmit, 这代码该怎么写
`
  const onSubmit = async (values: FormValueType) => {

  };

  const onApprove = async (values: FormValueType) => {
  };

  <ModalForm
      formRef={formRef}
      title="Edit Post"
      open={props.updateModalOpen}
      onOpenChange={props.handleUpdateModalOpen}
      onFinish={onSubmit}
      submitter={{
        render: (props, defaultDoms) => {
          return [
            ...defaultDoms,
            <Button
              key="ok"
              type="primary"
              onClick={() => {
                props.submit();
              }}
            >
              Publish
            </Button>,
          ];
        },
      }}
    >

    </ModalForm>
`

**Comment by liujianguang-gz** [comment]
在submitter那隐藏默认点击按钮。
  submitter={{
    submitButtonProps: {
      style: {display: 'none'}
    }
  }}

**Comment by youcame** [comment]
在<ModalForm>标签中设置footer属性为null，隐藏底部默认按钮
```
footer={null}
```
