### ISSUE TITLE
使用antd pro 构建打包的过程中，报如下UglifyJs错误。求大佬们帮助

### ISSUE THREAD

**Issue by sunfuyue** [ant-design/ant-design-pro#1100]
E:\barcoder-web>npm run build

> ant-design-pro@0.2.0 build E:\barcoder-web
> roadhog build

Creating an optimized production build...
Failed to compile.

index.js from UglifyJs
Unexpected token name «i», expected punc «;» [index.js:86711,10]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@0.2.0 build: `roadhog build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SFY\AppData\Roaming\npm-cache\_logs\2018-03-15T02_28_08_965Z-debug.log

下面是debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node\\node.exe',
1 verbose cli   'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@0.2.0~prebuild: ant-design-pro@0.2.0
6 info lifecycle ant-design-pro@0.2.0~build: ant-design-pro@0.2.0
7 verbose lifecycle ant-design-pro@0.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@0.2.0~build: PATH: D:\node\node_modules\npm\bin\node-gyp-bin;E:\barcoder-web\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\node\;C:\Program Files\Git\cmd;C:\Users\SFY\AppData\Local\Microsoft\WindowsApps;;D:\Microsoft VS Code\bin;C:\Users\SFY\AppData\Roaming\npm;C:\Users\SFY\AppData\Local\Programs\Fiddler
9 verbose lifecycle ant-design-pro@0.2.0~build: CWD: E:\barcoder-web
10 silly lifecycle ant-design-pro@0.2.0~build: Args: [ '/d /s /c', 'roadhog build' ]
11 silly lifecycle ant-design-pro@0.2.0~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@0.2.0~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@0.2.0 build: `roadhog build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\node\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\node\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid ant-design-pro@0.2.0
15 verbose cwd E:\barcoder-web
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@0.2.0 build: `roadhog build`
22 error Exit status 1
23 error Failed at the ant-design-pro@0.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
#1082 重复了

**Comment by sunfuyue** [comment]
#1082没有说明怎么解决啊
