### ISSUE TITLE
👑如何创建和官网演示站点V5一样的代码？

### ISSUE THREAD

**Issue by hcweb** [ant-design/ant-design-pro#11004]
### 🥰 需求描述 | Requirements description

按照文档创建了几十个项目了，simple和complete都创建过，总是和演示站点不一样，请问如何拉取和演示站点一样的代码？

### 🧐 解决方案 | Solution

没有找到 解决方案，寻求官方帮助

### 🚑 其他信息 | Other information

![微信截图_20231010210301](https://github.com/ant-design/ant-design-pro/assets/12317944/00559d53-d890-4b5a-8965-4ca3bbbe4987)

**Comment by chenshuai2144** [comment]
complete 就是了，预览有些时间没更新了，以最新的为准
