### ISSUE TITLE
🧐[问题 | question] 菜单的path信息中需要包含动态路由参数该怎么处理呢

### ISSUE THREAD

**Issue by songchengen** [ant-design/ant-design-pro#11006]
### 🧐 问题描述 | Problem description
我想在菜单的path中设置动态路由参数，比如：点击dashboard菜单，跳转到：/tenant/:tenantId/dashboard，这里的这个tenantId是根据用户信息填充的，应该怎么处理呢。

我现在的路由配置如，示例代码所示

### 💻 示例代码 | Sample code

```
{
    path: '/tenant/:tenant',
    wrappers: ['@/wrappers/user'],
    flatMenu: true,
    routes: [
      {
        path: '/tenant/:tenant/',
        redirect: '/tenant/:tenant/dashboard',
      },
      {
        name: 'dashboard',
        icon: 'dashboard',
        path: '/tenant/:tenant/dashboard',
        component: './tenant/dashboard',
      },
  ]
}
```

### 🚑 其他信息 | Other information

OS:

Node：v18

浏览器 | browser：chrome

**Comment by XueMeijing** [comment]
据我经历umi3的routes.js貌似只有第一层有效果，子路由 routes: [] 需要在文件里定义，然后props里拿数据

![image](https://github.com/ant-design/ant-design-pro/assets/35559153/b47fb68e-ae64-407f-b19d-c9d34e0e3f3f)

![image](https://github.com/ant-design/ant-design-pro/assets/35559153/b57ea780-e6de-49c8-b7b2-7dc0560ed616)

![image](https://github.com/ant-design/ant-design-pro/assets/35559153/0e2402f2-f249-400f-9314-4c020e981bd3)

**Comment by wuchencm** [comment]
同问，我现在也遇到这样的问题了，该怎么解决呢？

**Comment by chenshuai2144** [comment]
现在是不支持，建议在 menuItemRender 里面自行处理一下

`menuItemRender =(({path})=>{  return path })`

这里可以读取一下用户信息注入进去

**Comment by chenyu1990** [comment]
`useParams`
https://umijs.org/docs/api/api#useparams
