### ISSUE TITLE
🐛 [BUG] 页面布局样式偶发错乱

### ISSUE THREAD

**Issue by Tomfish0902** [ant-design/ant-design-pro#11007]
![image](https://github.com/ant-design/ant-design-pro/assets/19299002/4a859f76-7270-4050-bc55-e547ef71a3a4)

强制刷新会恢复正常，有时候又会出现样式错乱

  "antd": "^5.2.2",
   "@ant-design/pro-components": "^2.3.57",

**Comment by Tomfish0902** [comment]
初步试了下，好像与history.push有关，找不到问题所在，官方可以给个答复么

**Comment by coding-hui** [comment]
我与遇到同样的问题

**Comment by Nodecmj** [comment]
我也出现这个问题了，官方呢，怎么不解决一下？

**Comment by chenshuai2144** [comment]
antd 的问题，升级一下antd的版本就可以解决了
