### ISSUE TITLE
🧐[问题 | question] How can I use it in an electron app? is there a boilerplate/template/cli?

### ISSUE THREAD

**Issue by MiniSuperDev** [ant-design/ant-design-pro#11008]
Hi, I want to use ant-design-pro in an https://www.electronjs.org/ app.
There is a boilerplate or template or cli option?
Also there is a guide/tutorial?
Thank you

**Comment by WangJM001** [comment]
基于Umi的Electron框架，一行命令(pnpm create poros)生成Electron应用，快速开发、打包， 集成了各种功能，方便好用，感兴趣的可以看下，欢迎Star，项目还在不断迭代中。
https://github.com/porosjs/poros
