### ISSUE TITLE
🧐[问题 | question] ant-design-pro目前有打算升级到antd@5吗？ 

### ISSUE THREAD

**Issue by wuchencm** [ant-design/ant-design-pro#11003]
![image](https://github.com/ant-design/ant-design-pro/assets/14210543/6cc3d42a-c96a-43b8-af8f-9786c7fb93f4)
这是我项目目前使用的版本

**Comment by wangzhoubin** [comment]
你拉去一下最新的项目，就是最新的ant@5的，你可以先把本地的4改成5，然后试一下有没有界面问题

**Comment by chenshuai2144** [comment]
已经做完了，你拉下最新的代码
