### ISSUE TITLE
右侧content固定宽高，非流式🧐[问题 | question]

### ISSUE THREAD

**Issue by 404area** [ant-design/ant-design-pro#11010]
### 🧐 问题描述 | Problem description
<img width="1511" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/50036307/d3b9af8f-3666-46db-8cad-15ed882db802">
如上图所示，我想固定这个区域的宽高，而不是右侧一滚动就到hader下盖住，请问怎么弄？

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
fixHeader 去掉呢？
如果想要滚动条修改，可以用calc 计算一下高度，限制死 容器的内容，然后overflow：auth
