### ISSUE TITLE
🧐[问题 | question]V6版本404页面默认显示的是英文，如何设置成中文

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#11014]
### 🧐 问题描述 | Problem description

V6版本404页面默认显示的是英文，如何设置成中文?

### 🚑 其他信息 | Other information

OS: windows 10 x64

Node：v18.16.0

浏览器 | browser：chrome

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/max/i18n#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9%E9%85%8D%E7%BD%AE

看这里 

defaultLocale: string
