### ISSUE TITLE
react 在纯的js文件中调用怎么调用message

### ISSUE THREAD

**Issue by rankaifeng** [ant-design/ant-design-pro#11016]
![image](https://github.com/ant-design/ant-design-pro/assets/16712359/2e34ba0f-2bc7-4d97-9eb7-95a24b5f30c4)
比如我想要在这里调用message！我在全局也已经用App包裹了

**Comment by chenshuai2144** [comment]
https://ant-design.antgroup.com/components/message-cn#%E5%85%A8%E5%B1%80%E6%96%B9%E6%B3%95

看这里
