### ISSUE TITLE
🧐[问题 | question]openApi配置，hook的用法

### ISSUE THREAD

**Issue by kujianhua** [ant-design/ant-design-pro#11012]
### 🧐 问题描述 | Problem description

```
openAPI: [
    {
      namespace: 'type名',
      projectName: '文件夹名',
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'url',
      mock: true,
      apiPrefix:'api前缀',
    },
   {
      namespace: 'type名',
      projectName: '文件夹名',
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'url',
      mock: true,
      apiPrefix:'api前缀'
    },
]
```

### 💻 示例代码 | Sample code

其中还有一个hook属性，有什么用法？

### 🚑 其他信息 | Other information

默认文件夹名

![DCC9CB6B-A0C2-4F82-8183-6201785078D4](https://github.com/ant-design/ant-design-pro/assets/22991816/9d92c229-19c0-4f58-a2d5-2aa942ada57c)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
hook 是用来监控生成是进程的。不二次开发是不需要配置的
