### ISSUE TITLE
🧐[问题 | question]

### ISSUE THREAD

**Issue by wn0x00** [ant-design/ant-design-pro#11018]
### 🧐 问题描述 | Problem description

维护老项目出现问题，下载v1分支代码，install之后，start运行不起来，提示./src/index.js
Module build failed: Error: "pipelineOperator" requires "proposal" option whose value must be one of: "minimal", "fsharp", "hack", "smart".
    at parser.next (<anonymous>)
    at normalizeFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by angleneo** [comment]
the same question
