### ISSUE TITLE
routes中一级路由拥有component，子集的component被覆盖，无法显示🧐[问题 | question]

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#11028]
代码如图：
如果给一级路由配置component:'./cues/home'，那么每次从顶部导航栏点击“线索报送”都是配置的component'./cues/home'，点击左侧menu菜单，切换了路径，始终是该component:'./cues/home'，其他页面都不会显示出来

![image](https://github.com/ant-design/ant-design-pro/assets/12421552/db05f9d8-4162-4629-8454-0a49778c6275)

![image](https://github.com/ant-design/ant-design-pro/assets/12421552/c0d5fdfa-fdab-4b6d-b400-cd6e8cf88203)

结果：
![image](https://github.com/ant-design/ant-design-pro/assets/12421552/e8d51d56-27a2-4366-be2a-fc0426d1ea9e)

如果不给一级路由配置component，那么每次从顶部导航栏点击“线索报送”都是空白页
如图：
![image](https://github.com/ant-design/ant-design-pro/assets/12421552/fcf78f6b-2cca-403b-adbe-4eabb4187ba9)

想要的效果或者结果：
1、点击“线索报送”，可以进到一个新页面，切换子菜单，互相不影响。
2、点击“线索报送”，默认进子菜单的第一个也可以。

**Comment by XueMeijing** [comment]
给你看看我的，你应该在 ./cues 文件夹下弄个index.js，判断pathname是不是等于/cues。是的话就展示home，不是的话pathname就匹配子组件/cues/topic这种，需要嵌套路由 Switch Route这些，都不能匹配到就404 

![image](https://github.com/ant-design/ant-design-pro/assets/35559153/ce5619f9-b764-4d61-bb1a-d52f988e16ae)
![image](https://github.com/ant-design/ant-design-pro/assets/35559153/2169d22c-06c1-4cf7-9e54-3e1aa08fce5d)

**Comment by edifangyi** [comment]
> 给你看看我的，你应该在 ./cues 文件夹下弄个index.js，判断pathname是不是等于/cues。是的话就展示home，不是的话pathname就匹配子组件/cues/topic这种，需要嵌套路由 Switch Route这些，都不能匹配到就404
> 
> ![image](https://user-images.githubusercontent.com/35559153/282027452-ce5619f9-b764-4d61-bb1a-d52f988e16ae.png) ![image](https://user-images.githubusercontent.com/35559153/282027649-2169d22c-06c1-4cf7-9e54-3e1aa08fce5d.png)

哈，那左侧的菜单是自己做吗

**Comment by XueMeijing** [comment]
> > 给你看看我的，你应该在 ./cues 文件夹下弄个index.js，判断pathname是不是等于/cues。是的话就展示home，不是的话pathname就匹配子组件/cues/topic这种，需要嵌套路由 Switch Route这些，都不能匹配到就404
> > ![image](https://user-images.githubusercontent.com/35559153/282027452-ce5619f9-b764-4d61-bb1a-d52f988e16ae.png) ![image](https://user-images.githubusercontent.com/35559153/282027649-2169d22c-06c1-4cf7-9e54-3e1aa08fce5d.png)
> 
> 哈，那左侧的菜单是自己做吗

是啊，说实话我对umi不是很了解，但是项目里有很多用到嵌套路由的地方，只用umi的routes.js应该配不出来的
