### ISSUE TITLE
页面保活

### ISSUE THREAD

**Issue by xuwenxiang1030** [ant-design/ant-design-pro#11029]
我想用react-activation做一个页面保活(页面缓存),但是我没有找到你的布局里面的内容区是在哪里。我在app.tsx里面找到layout，但是里面只有headerRender和footerRender
![image](https://github.com/ant-design/ant-design-pro/assets/106908804/fd30a363-b49f-4a97-ac5a-ccef4448841b)
，然后在src/umi/core/plugin.locale/locale/tsx里面找到
![38a00e03f960d638f9ae13f75657d887](https://github.com/ant-design/ant-design-pro/assets/106908804/443e1b80-cdaa-49ff-bf8d-9d9fcc689d66) 但是编译前的找不到，有没有可以解答的

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args

试试这个，如果不能满足需求，你就要去plugin的源码里面找了
