### ISSUE TITLE
🧐[问题 | question] 在网络差的情况下，如何在切换页面的时候显示 Loading 状态

### ISSUE THREAD

**Issue by houkunlin** [ant-design/ant-design-pro#11020]
### 🧐 问题描述 | Problem description
在移动网络或者网络差的情况下，如何在切换页面的时候显示 Loading 状态？

例如，在使用谷歌浏览器开发的时候，开启【低速3G】网络模拟网络不佳的场景下切换页面，会出现一段时间的页面空白，之后才正常显示，如何在页面加载的过程中显示页面加载Loading状态

最新版本代码。

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by ZhollowShell** [comment]
在src下新建loading.tsx  内容 `export { PageLoading as default } from '@ant-design/pro-components';`

**Comment by ZhollowShell** [comment]
[https://umijs.org/docs/guides/directory-structure#loadingtsxjsx](url)

**Comment by houkunlin** [comment]
> https://umijs.org/docs/guides/directory-structure#loadingtsxjsx

感谢，之前找了很久的文档，但是一直忽略了目录结构的文档，一直在找路由、app.tsx、运行时配置的文档都没有找到
