### ISSUE TITLE
可以在app.tsx里面使用valtio  状态管理嘛？

### ISSUE THREAD

**Issue by wangJacker** [ant-design/ant-design-pro#11023]
### 💻 示例代码 | Sample code
import Footer from '@/components/Footer';
import { Question, SelectLang } from '@/components/RightContent';
import { LinkOutlined } from '@ant-design/icons';
import type { Settings as LayoutSettings } from '@ant-design/pro-components';
import { SettingDrawer } from '@ant-design/pro-components';
import { RunTimeLayoutConfig, useSnapshot } from '@umijs/max';
import { history, Link } from '@umijs/max';
import { Button, Dropdown, Menu, Tabs, Layout } from 'antd';
import { useIntl } from 'umi';
import defaultSettings from '../config/defaultSettings';
import { errorConfig } from './requestErrorConfig';
import { currentUser as queryCurrentUser } from './services/ant-design-pro/api';
import React, { useEffect } from 'react';
import { AvatarDropdown, AvatarName } from './components/RightContent/AvatarDropdown';
import {
    CloseOutlined,
    EllipsisOutlined,
    ReloadOutlined,
    UserOutlined,
    VerticalLeftOutlined,
    VerticalRightOutlined,
} from '@ant-design/icons';
import { store } from '@/models' // 这里引出

import { XzgApp } from '@/components';
import { getAll } from '@/services/user/login';

const { Footer: AntdFooter } = Layout;
const isDev = process.env.NODE_ENV === 'development';
const loginPath = '/user/login';
const { TabPane } = Tabs;
/**
 * @see  https://umijs.org/zh-CN/plugins/plugin-initial-state
 *
 * */
// export async function getInitialState(): Promise<{
//     settings?: Partial<LayoutSettings>;
//     currentUser?: API.CurrentUser;
//     loading?: boolean;
//     fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
// }> {
//     const fetchUserInfo = async () => {
//         try {
//             const msg = await queryCurrentUser({
//                 skipErrorHandler: true,
//             });
//             return msg.data;
//         } catch (error) {
//             history.push(loginPath);
//         }
//         return undefined;
//     };
//     // 如果不是登录页面，执行
//     const { location } = history;
//     if (location.pathname !== loginPath) {
//         const currentUser = await fetchUserInfo();
//         return {
//             fetchUserInfo,
//             currentUser,
//             settings: defaultSettings as Partial<LayoutSettings>,
//         };
//     }
//     return {
//         fetchUserInfo,
//         settings: defaultSettings as Partial<LayoutSettings>,
//     };
// }

// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = (a) => {
    console.log(a)
    // const state = useSnapshot(userStore);

    return {
        actionsRender: () => [<Question key="doc" />, <SelectLang key="SelectLang" />],
        avatarProps: {
            src: 11,
            title: <AvatarName />,
            render: (_, avatarChildren) => {
                return <AvatarDropdown>{avatarChildren}</AvatarDropdown>;
            },
        },
        waterMarkProps: {
            content: "444",
        },
        // footerRender: () => {
        //     return (
        //         <AntdFooter>
        //             < Footer />
        //         </AntdFooter>
        //     )
        // },
        // onPageChange: () => {
        // const { location } = history;
        // 如果没有登录，重定向到 login

        // if (!initialState?.currentUser && location.pathname !== loginPath) {
        //     history.push(loginPath);
        // }
        // },
        getCustomTabs: () => {
            console.log(444)
        },
        layoutBgImgList: [
            {
                src: 'https://mdn.alipayobjects.com/yuyan_qk0oxh/afts/img/D2LWSqNny4sAAAAAAAAAAAAAFl94AQBr',
                left: 85,
                bottom: 100,
                height: '303px',
            },
            {
                src: 'https://mdn.alipayobjects.com/yuyan_qk0oxh/afts/img/C2TWRpJpiC0AAAAAAAAAAAAAFl94AQBr',
                bottom: -68,
                right: -45,
                height: '303px',
            },
            {
                src: 'https://mdn.alipayobjects.com/yuyan_qk0oxh/afts/img/F6vSTbj8KpYAAAAAAAAAAAAAFl94AQBr',
                bottom: 0,
                left: 0,
                width: '331px',
            },
        ],
        links: isDev
            ? [
                <Link key="openapi" to="/umi/plugin/openapi" target="_blank">
                    <LinkOutlined />
                    <span>OpenAPI 文档</span>
                </Link>,
            ]
            : [],
        menuHeaderRender: undefined,
        // 自定义 403 页面
        // unAccessible: <div>unAccessible</div>,
        // 增加一个 loading 的状态
        childrenRender: (children) => {
            // if (initialState?.loading) return <PageLoading />;
            return (
                <>
                    {children}
                    {/* {
                         <SettingDrawer
                        disableUrlParams
                        enableDarkTheme
                        settings={initialState?.settings}
                        onSettingChange={(settings) => {
                            setInitialState((preInitialState) => ({
                                ...preInitialState,
                                settings,
                            }));
                        }}
                    />
                    } */}

                </>
            );
        },
        // ...initialState?.settings,
        ...defaultSettings as Partial<LayoutSettings>
    };
};

export function rootContainer(container: React.ReactNode) {
    return React.createElement(XzgApp, null, container);
}

export function render(oldRender: () => void) {
// 理想在这里使用，但是会报异常 在layout一样异常
    getAll().then((result) => {
        if (result.session.userId) {
            if ( location.pathname === loginPath) {
                history.push("/");
            }
        } else {
            oldRender()
            history.push(loginPath);
        }
    })
}

### 🚑 其他信息 | Other information
错误信息： TypeError: Cannot read properties of undefined (reading 'proxy')

![image](https://github.com/ant-design/ant-design-pro/assets/33062942/7ba294f7-d374-4b0a-b726-fc98322204e0)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
他是个方法不是个组件，不能用hooks的，如果要操作，建议挂个组件，在组件的 useEffect 里面调用 hooks
