### ISSUE TITLE
npm run build 502 error

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#1102]
![image](https://user-images.githubusercontent.com/12181423/37447614-d7943634-285d-11e8-94fd-7d9e79ab8f73.png)
记得以前运行时 会有一个  404 的异常，今天打包的时候发现了一个502

**Comment by chenshuai2144** [comment]
这是我们roadhog 依赖的一个底层库，是不影响使用的。

**Comment by hqwlkj** [comment]
以后会修复这些问题吗？

**Comment by chenshuai2144** [comment]
包一更新就没了

**Comment by hqwlkj** [comment]
好的谢谢。

**Comment by hqwlkj** [comment]
@chenshuai2144  升级到 roadhog 2.30 之后，运行项目出错了
![image](https://user-images.githubusercontent.com/12181423/37579302-688431a4-2b78-11e8-86e2-37ab409532c2.png)
请问这是什么原因？

**Comment by hqwlkj** [comment]
问题已经排除处理，原因是 因为："babel-plugin-import": "^1.6.3", 版本低了，升级到 "babel-plugin-import": "^1.6.7", 之后。就不出现此类问题了。
