### ISSUE TITLE
🐛 bug 描述 ：登录页用户名密码登录还是会出现404

### ISSUE THREAD

**Issue by JasonCC0706** [ant-design/ant-design-pro#11027]
> ### 🐛 bug 描述 ：登录页用户名密码登录还是会出现404
> ![image](https://user-images.githubusercontent.com/82009891/278962248-a20f7b2a-1b8c-4341-b96d-41987cc84a01.png)
> 
> ### 📷 复现步骤 | Recurrence steps
> 代码拉下来 安转node_modules pnpm dev 启动后 直接按提示登录就会出现
> 
> ### 🏞 期望结果 | Expected results
> 能够登录成功
> 
> ### 💻 复现代码 | Recurrence code
> ### © 版本信息
> * Ant Design Pro 版本: [6.0.0]
> * umi 版本: [4.0.0]
> * 浏览器环境
> * 开发环境 [window]
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/82009891/278963043-3528de0c-3956-4fb5-a9b1-c9d650b91f73.png) 刚在https://github.com/ant-design/ant-design-pro 下直接下载斗zip文件 解压后重新下载包 运行启动登录页还是报刚刚的错

**Comment by selicens** [comment]
直接运行start命令是可以的，start:dev不行

**Comment by wangzhoubin** [comment]
看代理

**Comment by xingren23** [comment]
> 直接运行start命令是可以的，start:dev不行

start:dev 中mock数据关闭了，所以找不到 /api/login/account 的路由
