### ISSUE TITLE
🧐[问题 | question] 请教关于错误处理的逻辑

### ISSUE THREAD

**Issue by idaoyu** [ant-design/ant-design-pro#11038]
### 🧐 问题描述 | Problem description

当提交表单时，产生异常。后端返回 showType = 2。预期弹出错误提示。
但不仅仅弹出了错误提示，还弹出了 bizException 的错误页面
如果在 调用接口处 增加 try catch 能够解决该问题
想请教这里的设计原则，是否有更优雅的解决方案。

### 🚑 其他信息 | Other information
![image](https://github.com/ant-design/ant-design-pro/assets/140868193/f9572dc6-44b4-4330-9996-38f711a0e847)
![image](https://github.com/ant-design/ant-design-pro/assets/140868193/25d0e081-123e-4f8d-8b83-3ac988dd3582)

**Comment by chenshuai2144** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/8186664/c258ab27-7a0e-43d7-b759-9faf08f45ce5)

这个页面只有dev才会显示，你在调用的时候 trycatch 一下也能绕开
