### ISSUE TITLE
antd pro6多页签模式下，怎么设置页签的标题

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/ant-design-pro#11030]
由于同一个路由，通过路由参数发布了多个菜单，启用了多页签，页签标题全部为路由的名称，怎么设置为菜单的名称！

![image](https://github.com/ant-design/ant-design-pro/assets/35764692/4f84fe21-bb7d-4915-b716-e0a8e0606c9b)

**Comment by robert-xiao** [comment]
请问怎么打开多页签模式呀？
