### ISSUE TITLE
使用pro create myapp 结果显示参数有误🧐[问题 | question]

### ISSUE THREAD

**Issue by michaelbennn** [ant-design/ant-design-pro#11035]
### 🧐 问题描述 | Problem description

ubuntu系统下，安装完pro-cli后，使用pro create 报错 
usage: pro <command> [flags]
argument : invalid choice: 'create' (choose from 'attach', 'api', 'auto-attach', 'collect-logs', 'config', 'detach', 'disable', 'enable', 'fix', 'security-status', 'help', 'refresh', 'status', 'version', 'system')

### 🚑 其他信息 | Other information

OS:
ubuntu20.04
Node：
18.10.0
浏览器 | browser：

**Comment by Lvshujun0918** [comment]
同样的问题 好像Ubuntu自带的pro命令有冲突

**Comment by chenshuai2144** [comment]
覆盖一下 Ubuntu 自带的 pro 命令吧

**Comment by Osub** [comment]
怎么处理的？
