### ISSUE TITLE
Export 'SelectLang' is not defined. (11:27)

### ISSUE THREAD

**Issue by youn921** [ant-design/ant-design-pro#11034]
1. 删除国际化：
![image](https://github.com/ant-design/ant-design-pro/assets/96363844/20b22ece-b157-43d1-aeff-8a873b4fba70)
2. 在删除国际化后，重新npm start，报错：
```
wait  - [Webpack] Compiling...
error - ./src/components/index.ts
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):   
SyntaxError: G:\GithubRepo\Project\younBI-frontend\src\components\index.ts: Export 'SelectLang' is not defined. (11:27)

   9 | import { Question } from './RightContent';
  10 | import { AvatarDropdown, AvatarName } from './RightContent/AvatarDropdown';
> 11 | export { Footer, Question, SelectLang, AvatarDropdown, AvatarName };
     |                            ^
  12 |
    at constructor (G:\GithubRepo\Project\younBI-frontend\node_modules\@umijs\bundler-utils\compiled\babel\index.js:51396:19)
    at TypeScriptParserMixin.raise (G:\GithubRepo\Project\younBI-frontend\node_modules\@umijs\bundler-utils\compiled\babel\index.js:54263:19)
``` 
3. 如图所示：
![image](https://github.com/ant-design/ant-design-pro/assets/96363844/f4381931-518c-4661-ac2e-a57b9f6c7d1d)
在这个路径代码：..\src\components\index.ts
![image](https://github.com/ant-design/ant-design-pro/assets/96363844/71c89aba-c485-470b-8f6b-d94bb13ea686)
start页面也进不去
![image](https://github.com/ant-design/ant-design-pro/assets/96363844/2536718f-dc68-4f19-80cc-9cdda965cfed)

**Comment by xXAvoraXx** [comment]
++

**Comment by chenshuai2144** [comment]
手动删除一下 SelectLang 吧，数据结构改了，他不知道了

**Comment by bomologo** [comment]
打开文件 src/components/index.ts，找到以下代码：
export { AvatarDropdown, AvatarName, Footer, Question, SelectLang };
将其修改为：
export { AvatarDropdown, AvatarName, Footer, Question };
