### ISSUE TITLE
流水线打包突然报错，本地没有问题。咋回事？

### ISSUE THREAD

**Issue by cuiliming666** [ant-design/ant-design-pro#11032]
### 🧐 问题描述 | Problem description
之前打包都正常，突然流水线就无法部署了，请教下大佬们什么情况

## 💻 示例代码 | Sample code
![image](https://github.com/ant-design/ant-design-pro/assets/69189717/a2885b7b-7cdd-4e64-9b39-0e8f7b1d8b24)

**Comment by XueMeijing** [comment]
上面说了，期望使用node版本 >=16.14.0，但是当前是16.12.0。可能有人改了服务器的node版本，也可能是你自己改了 package.json 的 engines内部的node版本
