### ISSUE TITLE
🧐[问题 | question]想问下使用ant pro的layout 的menu 路由怎么给他增加个状态，Badge

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design-pro#11049]
### 🧐 问题描述 | Problem description

![image](https://github.com/ant-design/ant-design-pro/assets/25116493/f84f464d-dd4b-4080-b4d1-93dfcf26c8a7)
怎么在路由上增加个小圆点呢

### 💻 示例代码 | Sample code
使用的是ant pro自带的menu路由

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
lable 上面加个 bage ，不过不能在config.ts 里面配置了

**Comment by cangsnage** [comment]
> lable 上面加个 bage ，不过不能在config.ts 里面配置了

文档没有写label 这个api是不是title？

**Comment by cangsnage** [comment]
> > lable 上面加个 bage ，不过不能在config.ts 里面配置了
> 
> 文档没有写label 这个api是不是name？
![image](https://github.com/ant-design/ant-design-pro/assets/25116493/a9d2d28f-d680-4b00-8b9d-dfd3a343014f)
name 支持字符串的格式其他的格式不支持的
