### ISSUE TITLE
🐛 [BUG]npm run i18n-remove无效

### ISSUE THREAD

**Issue by zo-no** [ant-design/ant-design-pro#11041]
### 🐛 bug 描述

![image](https://github.com/ant-design/ant-design-pro/assets/97882316/6700d1f3-fd5a-44f5-ab8a-3abd92d534e2)

### 📷 复现步骤 | Recurrence steps

安装后运行npm run i18n-remove，换其他包管理器也没有用

### 🏞 期望结果 | Expected results

运行成功

### © 版本信息

- Ant Design Pro 版本:6.0.0
- umi 4
- Node.js v20.9.0

### 🚑 其他信息

麻了

**Comment by chenshuai2144** [comment]
修改一下eslint的配置试试，看起来是有个配置过时了

**Comment by ideaviewes** [comment]
@chenshuai2144 ,具体是怎么修改，改成什么呢，能说的详细一点吗？
