### ISSUE TITLE
plugin-locale SelectLang definitions are empty. 🐛 [BUG]

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#11048]
### 🐛 bug 描述
plugin-locale SelectLang definitions are empty.

### 📷 复现步骤 | Recurrence steps
![image](https://github.com/ant-design/ant-design-pro/assets/6988989/345446e2-0814-4f3b-bba6-e1cf2e28d69d)

### © 版本信息

- Ant Design Pro 版本: 5.9.4
- umi 版本: 4.0.88
"@ant-design/pro-components": "^2.6.42",
- 开发环境 Windows 11

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/blob/v4.0.88/packages/plugins/src/locale.ts

看看这里的逻辑，应该是你的 locales 文件夹不在

**Comment by xXAvoraXx** [comment]
> https://github.com/umijs/umi/blob/v4.0.88/packages/plugins/src/locale.ts
> 
> 看看这里的逻辑，应该是你的 locales 文件夹不在

我找到了问题所在，因为系统中只有一种语言，所以无法显示组件。
