### ISSUE TITLE
🧐抱歉，萌新想请教大佬们一个弱智问题

### ISSUE THREAD

**Issue by wansuiasdn** [ant-design/ant-design-pro#11042]
在使用ant-design-pro的时候，保存代码会自动清除未使用到的Import引入，请问这个是在哪里配置的呀，感谢感谢！

**Comment by HaiYangHuX** [comment]
这是vscode的配置

**Comment by wansuiasdn** [comment]
> 这是vscode的配置

感谢您的回复，我在其他项目里并没有出现这样的功能，在本地vscode首选项setting里也并没有找到保存相关的格式化配置，所以我在想有可能是antd pro 生成地项目里的某个地方做了相关配置

**Comment by chenshuai2144** [comment]
prettier 的  prettier-plugin-organize-imports 


https://www.npmjs.com/package/prettier-plugin-organize-imports
