### ISSUE TITLE
🧐[问题 | question]线上部署完成后，页面不刷新的情况下点击路由跳转，会报loading chunk 6046 failed

### ISSUE THREAD

**Issue by wh940816** [ant-design/ant-design-pro#11045]
### 🧐 问题描述 | Problem description
使用了antd pro开发项目，线上部署完成后，页面不刷新的情况下点击路由跳转，会报loading chunk 6046 failed，怀疑是部署完成后，静态资源的hash值改变了，但是前端没有刷新，请求的还是旧的资源，强刷页面后就恢复正常了。

像这种错误除了不走缓存，可不可以捕获这个错误，然后自动刷新一下页面？ 如果可以捕获，该如何捕获？

chrome  119.0

**Comment by chenshuai2144** [comment]
修改下nginx 的缓存，给每个文件搞个hash。顺便关掉 index.html 的缓存就能解决这个问题

**Comment by taofeifanIT** [comment]
nginx配置不是很懂，有改的位置截图吗
