### ISSUE TITLE
ant pro的导航 menu 不支持ant design 的menu的inlineCollapsed手动收缩的api？

### ISSUE THREAD

**Issue by MrNative** [ant-design/ant-design-pro#11040]
### 🧐 问题描述 | Problem description
ant pro的导航 menu 不支持ant design 的menu的inlineCollapsed手动收缩的api？

### 🚑 其他信息 | Other information

怎么让ant pro支持用户自动来进行menu 的收缩功能。

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
不支持，
直接用 collpase ，没必要用这么底层的api
