### ISSUE TITLE
🧐[问题 | The error of : Uncaught (in promise) Parsing failed]

### ISSUE THREAD

**Issue by xyu-io** [ant-design/ant-design-pro#11050]
### 🧐 问题描述 | Problem description

初始化完成并启动项目后，F12控制台一堆报错，应该怎么解决

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/60706871/587d98f7-9f95-4a5c-818a-54109369ec1b)

OS: windows11

Node：20.1

浏览器 | browser：Edge

**Comment by chenshuai2144** [comment]
看起来是antd的版本问题。

Uncaught (in promise) Parsing failed]  一般是接口有问题，搞个更详细报错日志吧
