### ISSUE TITLE
mac编译很慢

### ISSUE THREAD

**Issue by wgwxf** [ant-design/ant-design-pro#1105]
之前的版本编译正常，合并到最新版本后，mac编译很慢，改个页面10s左右才编译完成，windows没问题。
两台mac+两台windows做的比较

**Comment by ApophisX** [comment]
我windows也超级慢

**Comment by ApophisX** [comment]
改动一处热更新好慢，基本在5S左右，有什么办法吗

**Comment by afc163** [comment]
试试开启代码分割：https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD

**Comment by bobbychan** [comment]
开启了还是很慢

**Comment by liumin1128** [comment]
同编译慢，而且总是返回错误结果

**Comment by liumin1128** [comment]
一直在报一个很久之前的语法错误，重启都没用
好像是加了什么存缓，专门把错误存缓下来了

**Comment by xiaolongyuan** [comment]
巨慢 +1

**Comment by lyingd** [comment]
非常慢，与roadhog1.3的年代比，慢了10倍

**Comment by mutouzdl** [comment]
我最近也发现修改代码后编译挺慢的，还以为是代码多了的问题...

**Comment by afc163** [comment]
@sorrycc 看看？

**Comment by hoozi** [comment]
我是喜欢ctrl+s的人，平均5S+

**Comment by zsux** [comment]
慢

**Comment by stringStar** [comment]
mac确实慢，我mac正常编译13S左右，家里的台式机4s左右，台式机配置要好些

**Comment by stringStar** [comment]
补一句，添加了builddll后，mac编译大概为5s，台式机为1s左右，还需要把extraBabelPlugins里面的antd注释掉，不然antd还是会被编译，mac开发现在很难受 ，求帮助，现在的项目改一下就等20s。

**Comment by zhumingzhen** [comment]
修改完文件不会自动编译了 怎么解决

**Comment by chenshuai2144** [comment]
升级一下最新的 roadhog 试试

**Comment by shadiniao** [comment]
我windows也很慢,上个月下的代码,每次保存一下,页面响应效果至少10秒

**Comment by gaoxiaosong1113** [comment]
@chenshuai2144  我这边也遇到了修改完文件不会自动编译的问题。
