### ISSUE TITLE
🧐[问题] 如何清除 ProTable里Card和Toolbar的padding？

### ISSUE THREAD

**Issue by chenyu1990** [ant-design/ant-design-pro#11055]
如何清除 ProTable里Card和Toolbar的padding？

**Comment by chenshuai2144** [comment]
要清除 ProTable 中 Card 和 Toolbar 的 padding，可以使用 cardProps 属性来设置。具体的使用方式如下：

```jsx
<Portable
  // 其他属性...
  cardProps={{
    bodyStyle: { padding: 0 },
  }}
/>
```

通过在 cardProps 中设置 bodyStyle 的 padding 为 0，可以清除 Card 组件中的 padding。而在 toolbarProps 中设置 style 的 padding 为 0，可以清除 Toolbar 组件中的 padding。这样就能达到清除 ProTable 中 Card 和 Toolbar 的 padding 的效果。
