### ISSUE TITLE
如何把app.tsx文件封装成组件导出

### ISSUE THREAD

**Issue by Reputation-Liberty** [ant-design/ant-design-pro#11059]
![image](https://github.com/ant-design/ant-design-pro/assets/67351888/d3fd813b-982e-4c2f-a6e4-f55203b808cd)

**Comment by chenshuai2144** [comment]
要将app.tsx文件封装成组件并导出，你可以按照以下步骤操作：

1. 首先，在`src/components`目录下创建一个新的文件`app.tsx`。
2. 在`app.tsx`文件中编写你的组件代码。
3. 在`src/components/index.tsx`文件中添加以下代码：

```tsx
export { default as App } from './app';
```

4. 确保你的组件代码在`app.tsx`文件中被导出为默认导出。
5. 现在，你可以在其他文件中使用`import`语句来导入你的自定义组件了，例如：

```tsx
import { App } from './components';
```

这样，你就成功将`app.tsx`文件封装成了一个可导出的自定义组件。
