### ISSUE TITLE
🧐[问题 | 表格列ellipsis属性不生效]

### ISSUE THREAD

**Issue by Crush0916** [ant-design/ant-design-pro#11058]
### 🧐 问题描述 | Problem description
表格列设置ellipsis: true,表格数据悬浮可以正常展开...内容，但是表头不行，但是我看antd4x官网的demo案例是可以实现的，是protable中的ellipsis: true和antd table的有区别吗

### 💻 示例代码 | Sample code
![微信截图_20231124162055](https://github.com/ant-design/ant-design-pro/assets/97590431/88b11fbc-c0bb-4b11-ad31-70971b620a90)
![微信截图_20231124162039](https://github.com/ant-design/ant-design-pro/assets/97590431/d2ed538e-87ba-46a4-8c4e-7a63de4da7e3)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
是的， protable的 ellipsis 是对内容生效的，对表头不生效，算个bug，但是不知道怎么修
