### ISSUE TITLE
🧐[问题 | question]

### ISSUE THREAD

**Issue by Anstars** [ant-design/ant-design-pro#11053]
### 🧐 问题描述 | Problem description

执行配置文件openAPI报错

### 💻 示例代码 | Sample code

         const { info } = openAPIData;
                ^

TypeError: Cannot destructure property 'info' of 'openAPIData' as it is null.

### 🚑 其他信息 | Other information

![openAPI_Error](https://github.com/ant-design/ant-design-pro/assets/92664101/c4cf7f0e-ed75-4e2c-9b72-ee119906a9df)

已经移除国际化

OS:Windows 11 专业版

Node：

浏览器 | browser：Chornm

**Comment by Shuxinzsx** [comment]
您好，请问解决了吗？
