### ISSUE TITLE
🧐[问题 | question] ProFormDateTimeRangePicker 返回的值有办法获取到 dayjs 类型 而不是字符串类型的么

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design-pro#11069]
### 🧐 问题描述 | Problem description

看到 antd [date-picker](https://ant.design/components/date-picker-cn#%E5%85%B1%E5%90%8C%E7%9A%84-api)
传入和拿到的是 dayjs[] 类型
<img width="755" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/16385443/06a24d51-1b42-4b55-a8a4-e78cc2991c7f">

而 pro 这里变为字符串了, 
<img width="1518" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/16385443/842249ec-0ee4-4125-9add-9f68dae56fc0">
有办法拿到 dayjs 类型么, 想着直接可以用 dayjs 类型的 format 转为自己想要的格式, 而不是拿着字符串重新传入 dayjs().format()

### 💻 示例代码 | Sample code

https://codesandbox.io/s/ri-qi-biao-dan-forked-73dl68

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by xuoutput** [comment]
bump

**Comment by xuoutput** [comment]
bump

**Comment by chenshuai2144** [comment]
ProFormDateTimeRangePicker 返回的值是字符串类型，而不是 dayjs 类型。如果你希望获取 dayjs 类型的值，可以使用 dayjs() 方法将字符串转换为 dayjs 对象，然后再进行格式化等操作。

你可以像这样将返回的字符串转换为 dayjs 对象：

```javascript
import dayjs from 'dayjs';

const range = ['2022-01-01', '2022-01-10']; // 假设这是 ProFormDateTimeRangePicker 返回的值

const rangeDayjs = range.map(date => dayjs(date));

console.log(rangeDayjs); // [dayjs object, dayjs object]
```

然后，你就可以使用 dayjs 对象进行各种操作了，比如使用 format 方法格式化日期：

```javascript
const formattedRange = rangeDayjs.map(date => date.format('YYYY-MM-DD'));

console.log(formattedRange); // ['2022-01-01', '2022-01-10']
```

这样，你就可以获取到 dayjs 类型的值，并且可以使用 dayjs 提供的各种方法对日期进行操作和格式化了。

或者可以配置  ProForm 的   `dateFormatter={false}` 也可以关掉默认修改
