### ISSUE TITLE
菜单主题色不生效，页面内容生效 🐛 [BUG]

### ISSUE THREAD

**Issue by lijiufa27** [ant-design/ant-design-pro#11066]
### 🐛 bug 描述

菜单主题色不生效，页面内容生效

正常按照官网教程启动项目，在配置里更换主题，菜单主题色不生效

### 🏞 期望结果 | Expected results
期望菜单主题色正常生效
![image](https://github.com/ant-design/ant-design-pro/assets/68176480/db43998b-1e73-4d65-a127-8326c6888e3a)

### © 版本信息

- Ant Design Pro 版本: 3.1.0
- umi 版本 4.0
- 浏览器环境 Google Chrome 版本 119.0.6045.160（正式版本） （64 位）
- 开发环境 windows
<img width="923" alt="11e2f2beec27678fba4eb9815a6bde4" src="https://github.com/ant-design/ant-design-pro/assets/68176480/afbc5b3b-601b-4b56-b7b4-187473e3f619">

**Comment by chenshuai2144** [comment]
两边用的不是一个 token，菜单那边现在都不带颜色了
