### ISSUE TITLE
自定义布局及路由问题

### ISSUE THREAD

**Issue by wuchencm** [ant-design/ant-design-pro#11078]
目前使用的是ant design pro v6的版本，想实现一个自定义布局的功能

这是我的自定义布局的代码
`
const CustomLayout: React.FC<ProLayoutProps> = (props) => {

  
 // const menuDataRender = () => [
 //       {
 //          name:'概览',
 //           path:'/appstack/app/:appName/overview',
 //           component: './AppStack/index.tsx',
 //         },
 //        {
 //          name:'研发流程',
 //          path:'/appstack/app/:appName/workflow',
 //          component: './AppStack/index.tsx',
 //         },
 //         {
 //           name:'变更',
 //           path:'/appstack/app/:appName/changes',
 //           component: './AppStack/index.tsx',
 //         },
 //         {
 //           name:'环境',
 //           path:'/appstack/app/:appName/envs',
 //           component: './AppStack/index.tsx',
 //         },
 //   ];

    return (
        <ProLayout
            {...props}
            logo={false}
            title={false}
            layout='mix'
            headerRender={false}
            // menuDataRender={menuDataRender}
            // fixSiderbar={true}
            // menuItemRender={(menuItemProps, defaultDom) => {
            //     if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) {
            //         return defaultDom;
            //     }
            //     return <Link to={menuItemProps.path}>{defaultDom}</Link>;
            // }} // 使用自定义的菜单数据渲染
        >
            {props.children}
          adadad
        </ProLayout>
    );
}`
这是我的routes.ts 配置：
![image](https://github.com/ant-design/ant-design-pro/assets/14210543/8af9d8dd-6549-4ff2-a0f8-5c79b220f00e)
遇到的问题是：
![image](https://github.com/ant-design/ant-design-pro/assets/14210543/431b5e7f-8369-474d-81bf-587f2c813883)

这个菜单数据在自定义布局文件中配置的话是可以展示的，难道不能接收routes里的数据吗？

**Comment by guwan** [comment]
我遇到同样的问题，请问有没有解决这个问题呢？

**Comment by guwan** [comment]
@wuchencm 我解决了你这个问题，现在需要使用<Outlet/>来代替{props.children}了
`
<ProLayout
    >
      <div>
        MainLayout page
        <div>
          <Outlet/>
        </div>
      </div>
    </ProLayout>
`

**Comment by wuchencm** [comment]
> @wuchencm 我解决了你这个问题，现在需要使用来代替{props.children}了 `<ProLayout > <div> MainLayout page <div> <Outlet/> </div> </div> </ProLayout>`

是的，Outlet确实可以，但是怎么才能将routes里定义的路由信息呢

**Comment by chenshuai2144** [comment]
根据你提供的代码和问题描述，看起来你希望在自定义布局文件中使用`routes`中定义的菜单数据。但是在你的代码中，将`menuDataRender`注释掉了，这导致自定义布局文件没有菜单数据进行渲染。

要解决此问题，你可以取消注释`menuDataRender`函数，并根据`routes`中的数据来返回菜单数据。在你的`menuDataRender`函数中，你可以使用`routes`中的数据来动态生成菜单数据，如下所示：

```javascript
const menuDataRender = () => {
  // 获取routes配置中的数据
  const routes = [
    {
      path: "/",
      name: "首页",
      icon: "home",
      routes: [
        {
          path: "/dashboard",
          name: "Dashboard",
        },
        // 其他路由配置...
      ],
    },
    // 其他顶级路由配置...
  ];

  // 处理路由数据，生成菜单数据
  const formatMenuData = (routes) => {
    return routes.map((route) => {
      const { path, name, icon, routes: subRoutes } = route;
      const menuData = {
        path,
        name,
        icon,
      };

      // 如果有子路由，递归处理子路由
      if (subRoutes && subRoutes.length > 0) {
        menuData.routes = formatMenuData(subRoutes);
      }

      return menuData;
    });
  };

  return formatMenuData(routes);
};
```

然后在`ProLayout`组件中使用`menuDataRender`函数来渲染菜单数据，取消注释相关代码，如下所示：

```javascript
<ProLayout
  {...props}
  logo={false}
  title={false}
  layout="mix"
  headerRender={false}
  menuDataRender={menuDataRender}
>
  {props.children}
</ProLayout>
```

这样就可以让自定义布局文件根据`routes`中的数据来渲染菜单了。希望这个回答对你有所帮助！如果还有其他问题，请随时提问。
