### ISSUE TITLE
🐛 [BUG] 按照欢迎首页 tyarn add @ant-design/pro-components 报错

### ISSUE THREAD

**Issue by MilkywayVainB** [ant-design/ant-design-pro#11070]
### 🐛 bug 描述

如题，在首页有提示使用 yarn add @ant-design/pro-components，我更换为tyarn后使用命令，启动项目一直卡在登录界面，web的console报错如下：
mf-va_remoteEntry.js:702 Uncaught (in promise) Error: Module "./antd/dist/antd.less" does not exist in container.
while loading "./antd/dist/antd.less" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:702:11

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="1509" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/44825367/1578764a-6829-4f6d-8441-69f239cf002d">

**Comment by chenshuai2144** [comment]
不要引入  less 了，antd 的新版本去掉了

**Comment by chenshuai2144** [comment]
根据您提供的信息，这个错误是由于找不到`"./antd/dist/antd.less"`模块引起的。这可能是由于在使用`tyarn`替换`yarn`后，项目没有正确地安装相关依赖包引起的。

您可以尝试重新安装项目的依赖包，可以使用以下命令来清理和安装依赖：

```shell
tyarn install --clean-cache
```

如果问题仍然存在，可能是由于版本不兼容或其他配置问题导致的。您可以查看项目的文档或向项目的开发者寻求帮助以解决该问题。您还可以在Ant Design Pro的GitHub仓库中提出该问题，以获取更多的帮助和解决方案。

同时，根据您提供的错误信息，建议您在报告bug之前，先搜索已有的issue和阅读项目的常见问题，以确保您的问题没有被其他人提过，并且可以提供重现的步骤和环境信息来更好地帮助开发者定位和解决问题。
