### ISSUE TITLE
🧐[问题 | question] 在app.tsx中如何主动触发 children主动重新渲染或者刷新，想让当前children里面的组件重新请求一次数据

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-pro#11071]
### 🧐 问题描述 | Problem description

在app.tsx中如何主动触发 children主动重新渲染或者刷新
### 💻 示例代码 | Sample code
`childrenRender: (children) => {
      // if (initialState?.loading) return <PageLoading />;
      return (
        <>
          {children}
        </>
      );
    },`

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/42193371/5f63f575-fc8f-4514-99fb-de8a36ef1ccf)

OS:

Node：

浏览器 | browser：

**Comment by KYX1234** [comment]
听说改变initailstate的值会自动重新渲染layout,你可以试试

**Comment by taofeifanIT** [comment]
> 听说改变initailstate的值会自动重新渲染layout,你可以试试

打印了一下，确实会再进来，就是里面的组件为什么不会重新初始化请求数据呢
![image](https://github.com/ant-design/ant-design-pro/assets/42193371/6a9c2d7c-162a-4cc0-88b9-d1baa47d7aa9)
![image](https://github.com/ant-design/ant-design-pro/assets/42193371/3d2c4039-ef7b-4e6a-8d5d-50011609556a)

**Comment by taofeifanIT** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/42193371/dc058ae6-9945-491b-bc1e-47b424ff515e)

**Comment by KYX1234** [comment]
> ![image](https://private-user-images.githubusercontent.com/42193371/286828750-dc058ae6-9945-491b-bc1e-47b424ff515e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjU3NzYsIm5iZiI6MTcwMTMyNTQ3NiwicGF0aCI6Ii80MjE5MzM3MS8yODY4Mjg3NTAtZGMwNThhZTYtOTk0NS00OTFiLWJjMWUtNDdiNDI0ZmY1MTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MjQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzY2E2Yzk1YzZlYzQ0ODMwYzE2ZDk0MTgyOTQxODVhY2IyZWNlMWQzNWZlZTBkMGIzOTAzMWU3NTMxZjZlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2sBOqKwkUf9qdkV33qzTEpahvKf1hLOo_MFd7E8ls_k)

有个按钮控制loading状态，loading改变，渲染loading组件或者页面

**Comment by chenshuai2144** [comment]
在app.tsx中，要想主动触发子组件重新渲染或刷新，可以通过以下几种方式实现：

1. 使用React的`setState`函数：在父组件中定义一个状态，并在需要重新渲染子组件的时候，调用`setState`函数来更新该状态。这将导致父组件重新渲染，进而触发子组件的重新渲染。

2. 使用`key`属性：给子组件设置一个唯一的`key`属性，当`key`发生变化时，React会认为这是一个新的组件，会销毁旧组件并重新创建新的组件，从而触发子组件的重新渲染。

3. 使用`forceUpdate`函数：在父组件中调用子组件的`forceUpdate`函数，强制子组件重新渲染。但是需要注意，React并不推荐使用`forceUpdate`函数，因为它会绕过组件的正常更新机制，可能会导致一些不可预知的问题。

根据你提供的示例代码，如果你想让子组件重新请求数据，可以使用上述方法中的任意一种，在父组件中触发相应的操作来重新渲染子组件。
