### ISSUE TITLE
点击页面的一个链接如何打开一个新的浏览器页签来显示链接页面？

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#1107]
当我在http://127.0.0.1:8000/member/member-manager/list页面点击一个链接为
http://127.0.0.1:8000/member/member-manager/info时想打开新页签来展示这个页面，尝试用超链接或者window.open打开时最终打开的新页签地址为
http://127.0.0.1:8000/member/member-manager/info#/member/member-manager/list
又跳回了当前页面，怎么办？

**Comment by zhaxingaz** [comment]
没有人回复吗？急急急

**Comment by chenshuai2144** [comment]
百度一下！
我们的点击文档也是打开标签页

**Comment by zhaxingaz** [comment]
按照点击文档的写法后，我点击a页的一个链接b(路由地址)，想打开标签页显示b，但是打开标签页后的地址后面又多了#a导致新打开的标签页显示的还是a页面，这块我没搞懂怎么去修改

**Comment by zhaxingaz** [comment]
不知道我说明白了没有？

**Comment by zhaxingaz** [comment]
已经解决了，忘了加#号
