### ISSUE TITLE
antd pro 后面应该不会更新了，大家有用过字节的前端框架吗？好用吗？

### ISSUE THREAD

**Issue by tnngo** [ant-design/ant-design-pro#11080]
看作者回复，后面应该不会更新了，字节的怎么样，大家用过没》

**Comment by zhangwudi886** [comment]
哪里说不会更新了？

**Comment by tnngo** [comment]
@zhangwudi886 有的，你多翻翻就能找到

**Comment by echoyl** [comment]
这个只是一个架子啊， antd，procomponents 还是一直都有更新啊

**Comment by chenshuai2144** [comment]
试试  nextjs ，用的很爽

**Comment by semmywong** [comment]
> 试试 nextjs ，用的很爽

那可以出一个nextjs版本的ant-design-pro
