### ISSUE TITLE
🧐[问题 | question]为什么使用 ant pro 的 proformselect的分组为什么不能跟 ant 一样进行搜索筛选呢？

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design-pro#11082]
### 🧐 问题描述 | Problem description

为什么使用 ant pro 的 proformselect的分组为什么不能跟 ant 一样进行搜索筛选呢？

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
在Ant Design Pro的ProFormSelect组件中，分组的搜索筛选功能与Ant Design的Select组件不同是因为它们是基于不同的设计原则和用途而开发的。ProFormSelect是为了在Ant Design Pro中更好地支持表单设计而开发的，它的分组功能是为了更好地组织和展示选项。

如果你需要在ProFormSelect中实现搜索筛选功能，你可以考虑使用其他的解决方案，比如根据搜索关键字动态过滤显示的选项。你可以利用ProFormSelect的onSearch属性来捕获用户输入的搜索关键字，然后在处理函数中对选项进行过滤，并更新ProFormSelect的选项列表。

具体的实现方式可以根据你的项目需求和设计要求自行调整，你可以参考Ant Design Pro的文档和示例代码来帮助你更好地理解和使用ProFormSelect组件。如果你在实现过程中遇到具体的问题，可以提供更多的代码和错误信息，我们会继续帮助你解答。
