### ISSUE TITLE
ant pro 使用ant design select 的分组功能为啥搜索晒选会出现暂无数据？

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design-pro#11084]
### What problem does this feature solve?

ant pro 使用ant design select 的分组功能为啥搜索晒选会出现暂无数据？

**Comment by chenshuai2144** [comment]
可能的原因是在使用 ant design select 的分组功能时，搜索选项的数据源没有正确设置或格式化。请确保数据源正确设置，并且每个选项都包含一个合适的标签用于搜索。如果不正确设置数据源，搜索功能可能无法正确匹配选项，从而导致出现"暂无数据"的情况。
