### ISSUE TITLE
🧐[问题 | question]pro i18n-remove --locale=zh-CN --write

### ISSUE THREAD

**Issue by zhaozhenlove** [ant-design/ant-design-pro#11089]
### 💻 示例代码 | Sample code
![image](https://github.com/ant-design/ant-design-pro/assets/118148850/9168dabb-c3d3-4eae-abc3-c57447f774bc)

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by hhjesse** [comment]
一样的问题，请问怎么解决的
