### ISSUE TITLE
🐛 [BUG] 右侧的目录把左侧的元素挡住了，是否有显示的问题？

### ISSUE THREAD

**Issue by Henrycheheng** [ant-design/ant-design-pro#11086]
### 🐛 bug 描述

[BUG] 右侧的目录把左侧的元素挡住了，是否有显示的问题？
### 📷 复现步骤 | Recurrence steps

鼠标一直往下拉即可看到目录挡住了下面的部分元素
https://pro.ant.design/zh-CN/docs/getting-started#i18n-remove
![image](https://github.com/ant-design/ant-design-pro/assets/48849602/45be7bc5-db21-45bd-a9db-058c5e0e3c8f)

### 🏞 期望结果 | Expected results

当移动到底部模块时，应该右边的目录有个最大y轴触底的距离，接近底部元素时，目录隐藏会不会好一点
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/ant-design-pro/assets/48849602/f67f4988-1743-474e-8d48-0f20b91b1bee)

**Comment by chenshuai2144** [comment]
footer 没关系的，不重要
