### ISSUE TITLE
🧐[问题 | question] antd-pro v5 的5xx、4xx接口报错提示在哪配置？都是手写的吗

### ISSUE THREAD

**Issue by yutuan11** [ant-design/ant-design-pro#11091]
### 🧐 问题描述 | Problem description

项目信息：antd-pro 脚手架 选择umi3 、simple版本

写业务代码，当接口报错404或者5xx 时，页面没有反应，得去控制台看请求才知道是接口报错了。我怎么配置报错信息呢？

我看其他人的utils/request.ts https://github.com/umijs/umi-request/issues/201 里有 配置这类消息，但是我本地的umi/plugin-request 里没有。

难道这些都是手写的吗？ 因为我在仓库里也没找到对应code

### 🚑 其他信息 | Other information

OS: mac

Node：16.20.1

浏览器 | browser：

**Comment by zhangwudi886** [comment]
都是自己写的拦截方法

**Comment by liuxuewei** [comment]
您好，我是刘学炜，谢谢您的邮件，我会尽快查收并回复。祝您生活愉快

**Comment by chenshuai2144** [comment]
antd-pro v5的5xx、4xx接口报错提示可以通过配置统一的错误处理来实现。

在最佳实践中，antd-pro定义了一套接口格式和错误处理的规范。默认的接口格式如下：

```tsx
export interface response {
  success: boolean; // if request is success
  data?: any; // response data
  errorCode?: string; // code for errorType
  errorMessage?: string; // message display to user
  showType?: number; // error display type： 0 silent; 1 message.warn; 2 message.error; 4 notification; 9 page
  traceId?: string; // Convenient for back-end Troubleshooting: unique request ID
  host?: string; // onvenient for backend Troubleshooting: host of current access server
}
```

当出现HTTP错误或者返回的数据中`success`为`false`的情况下，request会抛出一个异常。你可以通过使用`useRequest`的`onError`方法或者`error`对象来自定义处理。大部分情况下，你不需要关心异常的情况，统一的错误处理会做统一的错误提示。

你可以使用`import { request } from 'umi';`来使用antd-pro内置的请求方法来获得该能力。此外，你还可以通过在`app.tsx`中暴露的`request`的运行时配置来修改或者自定义自己项目的一些逻辑，具体参考`@umijs/plugin-request`的文档。

希望能帮到你！
