### ISSUE TITLE
🧐[问题 | question]TS7006: Parameter 'children' implicitly has an 'any' type

### ISSUE THREAD

**Issue by TDawnLG** [ant-design/ant-design-pro#11094]
### 🧐 问题描述 | Problem description

app.tsx下childrenRenderchildrenRender: (children, props) 报错

Node：16.0.0

**Comment by chenshuai2144** [comment]
针对你的问题，TS7006错误的具体含义是参数"children"在没有指定类型的情况下隐式地被推断为"any"类型。为了解决这个问题，你可以在代码中使用@ts-ignore，以暂时忽略这个错误，如下所示:

```tsx
// @ts-ignore
childrenRender: (children, props) => {
  // ...
}
```

此外，当遇到需要使用"any"类型的情况时，不必担心使用它。在处理动态代码时，也可以使用"as unknown as XXX"来避免类型错误。这样做可以节省很多时间。希望对你有所帮助！
