### ISSUE TITLE
npm run i18n-remove 报错

### ISSUE THREAD

**Issue by 1470397673** [ant-design/ant-design-pro#11097]
![image](https://github.com/ant-design/ant-design-pro/assets/87465517/3a30283e-3216-46b2-99ad-9a7f78d1580f)
网上找了好多版本的情况都没有看到我这种情况，希望求解

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，应该是在升级 `@ant-design/pro-cli` 的过程中导致了报错。可以尝试以下解决方案：

1. 首先确保 `@ant-design/pro-cli` 已经安装成功，并且版本号为 3.2.0。

2. 检查项目根目录下的 `package.json` 文件，查看是否有 `i18n-remove` 相关的依赖。

   如果没有，可以尝试手动安装 `i18n-remove`，运行命令 `npm install i18n-remove --save`。

   如果已经安装了 `i18n-remove`，则尝试删除 `node_modules` 文件夹，并重新执行 `npm install` 命令。

3. 如果以上步骤都没有解决问题，可以尝试移除 `package-lock.json` 文件，并重新执行 `npm install` 命令。

4. 如果依然存在问题，可以尝试升级 `npm` 或 `node` 的版本，以确保使用的是最新的稳定版本。

5. 如果还是无法解决问题，建议在官方的仓库或社区中提问，获取更多帮助。
