### ISSUE TITLE
🐛初始化项目就有版本冲突问题

### ISSUE THREAD

**Issue by sishen654** [ant-design/ant-design-pro#11090]
### 🐛 bug 描述

使用脚手架进行项目初始化，使用 npm 下载依赖就有版本冲突问题

![image](https://github.com/ant-design/ant-design-pro/assets/65691266/a792b8c0-2140-4859-8c80-5642240227ea)

### 📷 复现步骤 | Recurrence steps

pro create antd-pro-app
umi@3
complete

### 🏞 期望结果 | Expected results

使用 npm i 直接下载，无版本冲突问题

**Comment by sishen654** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/65691266/a800f464-911a-487d-8e0a-ca9c05c5b431)
![image](https://github.com/ant-design/ant-design-pro/assets/65691266/53c2d751-755a-4f10-abc7-786e78945aad)
![image](https://github.com/ant-design/ant-design-pro/assets/65691266/05dfd8cc-8ec1-45ba-ba2e-166425f5591a)

这...

**Comment by chenshuai2144** [comment]
试试最新的，去掉这个库了，太老了

**Comment by sishen654** [comment]
> 试试最新的，去掉这个库了，太老了

OK感谢大佬
