### ISSUE TITLE
Ant Design Pro 怎样登录拦截?

### ISSUE THREAD

**Issue by liuboBobo** [ant-design/ant-design-pro#111]
Ant Design Pro 怎样登录拦截?

**Comment by afc163** [comment]
建议有空阅读下 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。

**Comment by gebilaoman** [comment]
自己写

**Comment by afc163** [comment]
这种太泛的问题没有办法回答。
