### ISSUE TITLE
🐛 [BUG]我配了一个pro的环境，为了切换测试和生产地址，yarn start:dev 没问题，yarn start:pro 就出问题了

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-pro#11108]
### 🐛 bug 描述

我配了一个pro的环境，为了切换测试和生产地址，yarn start:dev 没问题，yarn start:pro 就出问题了
fatal - Error: Invalid command pro, it's not registered.
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://github.com/ant-design/ant-design-pro/assets/42193371/ac9c2b16-c67d-486c-8c38-fdaeeefb67dc)
![image](https://github.com/ant-design/ant-design-pro/assets/42193371/95d117df-2534-4423-a78a-940e1aeb62f7)
![image](https://github.com/ant-design/ant-design-pro/assets/42193371/9342cc63-d5de-4a33-972f-a92fc73b0ed7)

**Comment by chenshuai2144** [comment]
根据你提供的信息，问题出在 `yarn start:pro` 这个命令上，报错信息是 `Invalid command pro, it's not registered.`。

这个问题可能是因为在 `package.json` 中没有配置 `start:pro` 这个命令。你可以检查一下 `package.json` 文件中的 `scripts` 字段，确保里面有类似下面的配置：

```json
{
  "scripts": {
    "start:dev": "cross-env SERVE_ENV=dev umi dev",
    "start:pro": "cross-env SERVE_ENV=pro umi dev"
  }
}
```

如果没有的话，你可以手动在 `scripts` 字段中添加这个命令。

然后，你可以使用 `yarn start:pro` 运行项目，并且根据你配置的 `serveUrlMap` 中的环境变量来切换测试和生产地址。

希望以上回答对你有帮助，如果还有其他问题，请随时提问。
