### ISSUE TITLE
🧐[问题 | question] 切换页面的时候页面资源一直‘待处理’ 

### ISSUE THREAD

**Issue by zj91zj** [ant-design/ant-design-pro#11105]
请问有人遇到这样的问题吗？
![微信图片_20231227095058](https://github.com/ant-design/ant-design-pro/assets/41497368/97872ab5-03dc-4d9e-982a-701bd25c9df2)

**Comment by zj91zj** [comment]
直接在这个页面刷新，又是可以加载出来的。

**Comment by chenshuai2144** [comment]
这个问题的解决方法可能与资源加载有关。当切换页面时，可能由于页面中的资源较多，导致页面一直处于待处理状态。以下是一些可能的解决办法：

1. 调整资源加载顺序：将关键资源（如样式表和脚本）放在文档头部加载，将辅助资源（如图像和视频）放在文档主体的底部加载，以最小化页面加载时间。
2. 压缩资源：压缩和合并脚本和样式表文件，以减少文件大小，从而提高加载速度。
3. 使用异步加载：对于非关键资源，可以使用异步加载的方式，即在页面加载完毕后再加载这些资源，以避免阻塞页面渲染。
4. 利用浏览器缓存：将资源文件设置为可缓存，这样在切换页面时就可以从缓存中加载资源，而不需要重新下载。
5. 优化服务器响应时间：如果服务器响应时间较慢，可以考虑对服务器进行优化，以提高响应速度。

希望以上方法能够帮助到你解决问题。如果还有其他问题，
