### ISSUE TITLE
🧐[问题 | question]针对某个页面禁用加载页

### ISSUE THREAD

**Issue by AlikeZhu** [ant-design/ant-design-pro#11100]
### 🧐 问题描述 | Problem description

是否可以禁用打开页面之后的加载界面

OS: windows 10

Node：18.16.1

浏览器 | browser：chorme

**Comment by chenshuai2144** [comment]
umi 现在是不支持的， 你可以试试自己写个插件

**Comment by AlikeZhu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
