### ISSUE TITLE
🧐[问题 | question] Module '"@ant-design/pro-components"' has no exported member XXXX.

### ISSUE THREAD

**Issue by ksdaylight** [ant-design/ant-design-pro#11101]
### 🧐 问题描述 | Problem description

你好，在vscode 里，所有从 @ant-design/pro-components这个包里导出的组件均报错：

**Module '"@ant-design/pro-components"' has no exported member 'XXX'.**

无尝试无论是用@ant-design/pro-cli，还是直接clone 本仓库，乃至pnpm i --frozen-lockfile，但均显示这个错误
但奇怪的是，我几个月之前的ant design pro项目是好样的
### 💻 示例代码 | Sample code
无

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/31586684/ade3419a-3392-42c2-ba2c-cccf5647e996)
![image](https://github.com/ant-design/ant-design-pro/assets/31586684/f84db1b8-6fb4-42d2-a4f1-7ff63e69040a)

OS:
debian 11
vscode : 1.85.1
Node：

浏览器 | browser：

**Comment by ksdaylight** [comment]
很可能是pnpm的问题，我用的pnpm 是 8.12.1.
我之后直接用npm 添加就好了.

**Comment by ksdaylight** [comment]
再用yarn测试安装，也可以成功
就pnpm不行

**Comment by chenshuai2144** [comment]
这个问题可能是由于版本兼容性或导入错误导致的。你可以尝试以下解决方案：

1. 确保你的项目中已经正确安装了"@ant-design/pro-components"包，并且版本是最新的。
2. 检查你的导入语句是否正确，确保你使用了正确的导出成员名称。
3. 如果是版本兼容性问题，你可以尝试降低"@ant-design/pro-components"的版本，或者升级你的项目依赖项来解决冲突。
4. 如果你的项目是从旧版本迁移过来的，可能是因为新版本的"@ant-design/pro-components"中移除了一些导出成员，你需要查看官方文档或者代码库的变更日志，了解哪些成员被删除或重命名了。
5. 如果以上步骤都没有解决问题，你可以尝试创建一个新的项目，仅仅导入"@ant-design/pro-components"包，并尝试使用其中的组件。这样可以确认是否是项目环境的问题。

希望这些解决方案能够帮助你解决问题！如果还有其他问题，请随时提问。
