### ISSUE TITLE
🐛 [BUG] 下载最新ant design pro 本地启动后在安卓版的chrome浏览器上打开报错mfsu-virtual-entry/umi.js

### ISSUE THREAD

**Issue by zj91zj** [ant-design/ant-design-pro#11111]
![微信图片_20240102142340](https://github.com/ant-design/ant-design-pro/assets/41497368/92a78f2b-7daa-411e-bf0e-beda3cd5e1da)

**Comment by chenshuai2144** [comment]
根据你提供的问题，看起来你正在尝试在安卓版的Chrome浏览器上打开最新的Ant Design Pro代码时遇到了一个错误。然而，需要注意的是，手机端浏览器并不适合进行开发工作，并且可能会关闭一些先进的功能。如果你想在手机上预览项目代码，我建议你使用serve命令来访问编译之后的代码。

另外，请确保你已经了解一些基础的前端知识，以及对umi和Ant Design有一定的了解。如果你是一个纯粹的新手，我建议你先阅读一下Ant Design Pro的新手指南，这样可以更好地理解和应用项目。

希望这些信息对你有帮助，如果你有任何进一步的问题，请随时提问。
