### ISSUE TITLE
🧐[问题 | question] https://preview.pro.ant.design/ 页面找不到拷贝设置的位置

### ISSUE THREAD

**Issue by PaleNeutron** [ant-design/ant-design-pro#11118]
### 🧐 问题描述 | Problem description

https://pro.ant.design/zh-CN/docs/title-landing#%E6%A0%87%E9%A2%98%E5%92%8C-logo 这里提到可以去preview页面拷贝设置，但是实际访问 https://preview.pro.ant.design/ 的时候没有配置的按键

感觉preview页面比 `pro create`的样式先进很多，请问如何获得和preview一致的样式？

### 🚑 其他信息 | Other information
![image](https://github.com/ant-design/ant-design-pro/assets/8296331/1526cba9-53e3-4513-91fa-d393ce6f46e9)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
已经去掉了，没有这个功能了
