### ISSUE TITLE
🐛 [BUG] Layout 错误边界问题

### ISSUE THREAD

**Issue by lynn1286** [ant-design/ant-design-pro#11117]
### 📷 复现步骤 | Recurrence steps
<img width="991" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/40122311/1924c347-4f69-4c08-bfff-cb46aa4296f1">

配置 ErrorBoundary 后，在页面不报错的场景下，渲染的依旧是 错误边界组件。
<img width="1955" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/40122311/6602f56f-4c83-4485-9e63-1cef48242e53">

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lynn1286** [comment]
复现视频： 

https://github.com/ant-design/ant-design-pro/assets/40122311/427f38bb-83eb-49b1-af7c-1a17686f0e0d

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据描述和截图，可以看出这个问题是关于使用 Ant Design Pro 的 Layout 组件时出现的错误边界问题。下面是一个解决方案：

1. 确认错误边界组件是否已正确配置。错误边界组件是用来处理子组件抛出的错误的组件。在 Ant Design Pro 中，可以使用 ErrorBoundary 组件作为错误边界组件。请确保 ErrorBoundary 组件已正确配置，如文档所示。

2. 确认页面是否存在其他报错。根据描述和截图，可以看到在页面不报错的情况下，依然渲染的是错误边界组件。这可能是由于页面存在其他报错导致的。请检查页面中的其他组件是否存在报错，并尝试解决这些报错。

3. 确认错误边界组件是否正确处理子组件的错误。在 Ant Design Pro 的错误边界组件中，可以使用 componentDidCatch 方法来处理子组件抛出的错误。请确保 componentDidCatch 方法已正确实现，并能够正确处理子组件的错误。

4. 确认是否需要更新 Ant Design Pro 版本。根据描述中提供的信息，可以看到使用的是 Ant Design Pro 1.0.0 版本。在这个版本中可能存在一些已知的问题和 bug。请考虑升级 Ant Design Pro 到最新版本，以获取最新的修复和改进。

总结：解决这个问题需要确认错误边界组件的配置和实现是否正确，并检查页面中的其他报错。如果问题仍然存在，可以尝试升级 Ant Design Pro 版本。

**Comment by GoldenLavine** [comment]
antdesignpro  基本上都是函数组件，我也遇到了上述问题，在函数组件中如何处理，有详细点的过程么

**Comment by 521guyu** [comment]
> antdesignpro 基本上都是函数组件，我也遇到了上述问题，在函数组件中如何处理，有详细点的过程么

您最后有解决吗？ 我本来是想屏蔽 prolayou自己的ErrorBoundary 。ErrorBoundary：false 。然后自己写一个，判断路由变化就隐藏错误边界组件。但我发现，我自己写的，无法捕获到 错误。我是在 childrenRender 里 包裹一个自己写的 错误边界组件。

**Comment by 521guyu** [comment]
> 复现视频：
> 
>  iShot_2024-01-08_17.46.03.mp4

您最后怎么解决的？
