### ISSUE TITLE
🐛 [BUG]  更新源代码后，MFSU 构建过程中无法解析 react-error-overlay 依赖

### ISSUE THREAD

**Issue by ivanioi** [ant-design/ant-design-pro#11110]
### 🐛 bug 描述
更新页面后，启动开发服务器，提示无法解析 react-error-overlay 依赖。但是我看相关路径下是有该依赖的，并且重新下载该依赖问题仍然存在。

### 📷 复现步骤 | Recurrence steps
我只是修改了一些页面而已，没有其它特殊操作

### © 版本信息

- Ant Design Pro 版本: 6.0.0
- umi 版本 v4.0.90

### 🚑 其他信息

![image](https://github.com/ant-design/ant-design-pro/assets/87262618/306eefed-c8af-4083-982f-c7613ab9bfc8)

**Comment by chenshuai2144** [comment]
这个bug可能是由于更新源代码后，MFSU在构建过程中无法解析react-error-overlay依赖导致的。你可以尝试以下解决方法：

1. 确保你的项目中的相关路径下确实存在react-error-overlay依赖。可以通过检查package.json文件或者node_modules目录来确认。

2. 如果确保依赖存在，尝试重新安装依赖。可以执行`npm install`或者`yarn`命令来重新下载依赖。

3. 如果重新下载依赖后问题仍然存在，可能是由于项目的某个依赖的不合理的实现导致的。你可以尝试在项目的配置文件中，比如.umirc.js或者config.js中，将这个包配置进mfsu.exclude字段中，以排除该依赖的影响。

希望以上方法能够解决你的问题。如果还有其他疑问，请随时提问。

**Comment by chenshuai2144** [comment]
根据你提供的信息，问题出现在更新源代码后，MFSU 构建过程中无法解析 react-error-overlay 依赖。尽管你已经确认相关路径下存在该依赖，并重新下载了该依赖，问题仍然存在。

这可能是由于两种场景引起的问题。首先，你可能依赖了 Bigfish 插件相关的功能，即引用了 `.umi` 目录下的内容，并且在开启 MFSU 后，项目可能无法正常编译。解决这个问题的方法是将这个包配置进 `mfsu.exclude` 字段中。

另外，还有可能是项目中的某个依赖的实现不合理，导致了无法解析 react-error-overlay 依赖的问题。你可以尝试以下方法进行解决：

1. 确保你的依赖版本和 Ant Design Pro 版本、umi 版本兼容。
2. 在项目根目录下运行 `npm install` 或 `yarn install`，以确保所有依赖项都被正确安装。
3. 尝试删除 `node_modules` 文件夹，并重新运行 `npm install` 或 `yarn install`。
4. 如果问题仍然存在，可以尝试更新相关依赖的版本或者联系依赖包的维护者寻求帮助。

希望这些方法可以帮助你解决问题！如果问题仍然存在，请提供更详细的错误信息或者源代码片段，以便我们更好地帮助你解决问题。
