### ISSUE TITLE
🐛 [BUG] antd4动态主题切换，按照官网上做，生成并引入modified.css文件，再通过ConfigProvider修改 prefixCls: 'custom',结果布局样式错乱

### ISSUE THREAD

**Issue by chenduxiuhaha** [ant-design/ant-design-pro#11114]
### 🐛 bug 描述

根据官网操作的，附上官网链接：https://4x-ant-design.antgroup.com/docs/react/customize-theme-variable-cn

然后发现布局样式错乱了。请问如何解决布局样式错乱的问题。以及后续通过ConfigProvider去修改prefixCls的值，页面样式却不刷新，如何做到修改prefixCls的值后页面自动刷新。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


### 布局样式错乱的问题解决方案：

1. 首先，请确保您已按照官方文档正确地生成并引入了modified.css文件。
2. 请检查您的modified.css文件是否包含与布局相关的样式，例如容器的宽度、高度、边距等。如果没有，请根据您的布局需求在modified.css中添加相应的样式。
3. 如果您的页面布局样式仍然错乱，可能是由于样式冲突导致的。您可以使用浏览器的开发者工具来检查具体的样式冲突，并进行相应的调整。可以通过调整CSS的选择器权重或使用!important关键字来解决样式冲突问题。

### 页面样式不刷新的问题解决方案：

1. 首先，请确保您已经正确地配置了ConfigProvider，并修改了prefixCls的值。可以在根组件的入口文件中进行配置。
2. 确保您的修改已经生效，可以通过在浏览器控制台打印出ConfigProvider的配置项来进行验证。
3. 如果页面样式没有自动刷新，可能是由于React的重新渲染机制导致的。您可以尝试使用React的强制更新机制来解决此问题。可以在修改prefixCls的地方调用`this.forceUpdate()`来强制组件重新渲染，从而使页面样式得到更新。

同时，可以考虑使用Umi和antd提供的一些工具和插件来简化前端开发流程，例如Umi的自动化构建和路由配置，以及antd提供的丰富的组件库和样式定制方案。此外，在前端工程化方面，可以使用Webpack等构建工具进行打包和优化，以提升前端性能。并且，在React技术方面，可以结合使用Hooks和函数式组件等特性，以提升代码的可读性和可维护性。

**Comment by chenshuai2144** [comment]
prefixCls 很难做到自动刷新的，推荐你在 layout 的children render里面做做手脚，每次修改的时候把所有的children 都销毁掉
