### ISSUE TITLE
🧐[问题 | question] Pro6启动后，不显示umi ui小图标，请教各位大神如何解决呢？

### ISSUE THREAD

**Issue by 2019-yingqiu** [ant-design/ant-design-pro#11112]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by 2019-yingqiu** [comment]
创建的时候，选择的是umi4，可能不支持吧。

**Comment by 2021Null** [comment]
> 创建的时候，选择的是umi4，可能不支持吧。

现在好像创建时候默认就是umi4，请问有啥解决方法吗，创建umi3

**Comment by 2021Null** [comment]
> 创建的时候，选择的是umi4，可能不支持吧。

现在好像创建时候默认就是umi4，请问有啥解决方法吗，创建umi3
