### ISSUE TITLE
🧐[问题 | question] 如何设置某些页面，在未登录的情况下，可以直接访问

### ISSUE THREAD

**Issue by OnceCrazyer** [ant-design/ant-design-pro#11119]
如题

**Comment by houkunlin** [comment]
设置 `layout: false` 路由配置，参考登录页面路由配置。
![image](https://github.com/ant-design/ant-design-pro/assets/12333292/88cf42cf-5204-4ae8-88ef-c0d9a95d1e72)

在 `app.tsx` 里面搜索 `history.push` ，改相关配置判断当前路由路径忽略不 `history.push`
