### ISSUE TITLE
🐛 [BUG] 使用最新版的ant design pro 模板进行开发时如果开启标签页，主题设置为暗黑模式，标签页样式未适配

### ISSUE THREAD

**Issue by OnceCrazyer** [ant-design/ant-design-pro#11126]
<img width="1730" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/16172911/0fd48ecc-8e27-48b2-a0b2-9039b5cd3de2">

**Comment by chenshuai2144** [comment]
这个不是 官方支持的，去对应的库里面找下

**Comment by tangjiali** [comment]
> <img alt="image" width="1730" src="https://private-user-images.githubusercontent.com/16172911/296678488-0fd48ecc-8e27-48b2-a0b2-9039b5cd3de2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzQ2NzcsIm5iZiI6MTcxNzEzNDM3NywicGF0aCI6Ii8xNjE3MjkxMS8yOTY2Nzg0ODgtMGZkNDhlY2MtOGUyNy00OGIyLWEwYjItOTAzOWI1Y2QzZGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1NDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZDdiNmJmOWQxOTAwOGRlNWMyYjE2Yzc4OTQ4MDhkZGE1ZWM1YTU5ZmU1ZDEwZDY3M2JhYTEyZTMxYjc3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7GmrBnPe-1jBHeTEDGf2R3K3bGSzwT4Q2-HR-hz46Uk">

这个问题找到解决方法了吗，还有请教下如何通过事件关闭某个页签？
