### ISSUE TITLE
Login Page is not included ChildrenRender in app.ts

### ISSUE THREAD

**Issue by NguyenThinh-17001510** [ant-design/ant-design-pro#11128]
I just console log inside the function childrenRender in app.ts. When i redirect to My Page Login, console.log is not running. 
![z5081495460702_6edd878443baeecc274b44ccc6b55fe1](https://github.com/ant-design/ant-design-pro/assets/56266382/b0f07bd6-2324-4e76-8f03-336bbc480597)
![z5081498124248_76ae216f72566c892633cb7366e0e707](https://github.com/ant-design/ant-design-pro/assets/56266382/7d5a73fb-29a0-4358-a8d5-4acafe5fc0ed)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的问题和情况，解决方案如下：

由于 login 页面没有被 layout 包裹，你可以在 `src/app.tsx` 中使用 `childrenRender` 配置项来包裹所有页面，具体配置如下：

首先，你需要在 `src/app.tsx` 中导入 `RunTimeLayoutConfig`、`BasicLayoutProps` 和 `LayoutSettings`，代码如下：

```tsx
import React from 'react';
import { RunTimeLayoutConfig } from 'umi';
import { BasicLayoutProps, Settings as LayoutSettings } from '@ant-design/pro-layout';
```

然后，在 `src/app.tsx` 文件的末尾，新增一个 `layout` 函数，配置 `childrenRender`，代码如下：

```tsx
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    // 其他 layout 配置项
    childrenRender: (children) => {
      return <div>{children}</div>;
    },
  };
};
```

最后，在 `src/app.tsx` 文件中导出 `layout` 函数，代码如下：

```tsx
export default layout;
```

完成以上步骤后，login 页面会被包裹在 layout 中，`childrenRender` 函数会被调用，并且 console.log 语句会打印输出。

希望能够帮助到你！如果还有其他问题，欢迎继续提问。

**Comment by echoyl** [comment]
> 因为 login 没有被 layout 包裹，想要配置所有的的页面被包裹可以试试
> 
> https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args
> 
> ```
> export function rootContainer(container) {
>   return React.createElement(ThemeProvider, null, container);
> }
> ```

如果使用这个方法 rootContainer 里面包含的组件中无法使用useModel('@@initialState');

TypeError: Cannot read properties of null (reading 'dispatcher')
