### ISSUE TITLE
👑 [需求 | Feature]

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-pro#11125]
### 🥰 需求描述 | Requirements description
openapi自动生成的配置参数没有isCamelCase

我看@umijs/openapi这个插件是有isCamelCase这个参数，默认值是true
但是ant design pro在config里面的配置openAPI是不能配置这个参数的，导致我原来是大写开头的，现在变为小写了。
### 🧐 解决方案 | Solution
1、希望配置里面可以支持跟@umijs/openapi这个插件的配置一样
@umijs/openapi文档地址：https://www.npmjs.com/package/@umijs/openapi

**Comment by sine-hx** [comment]
请问问题什么时候解决呢？
