### ISSUE TITLE
🧐[问题 | question] fetchUserInfo是怎么获取到用户信息的，怎么传参的

### ISSUE THREAD

**Issue by aammjian** [ant-design/ant-design-pro#11124]
### 🧐 问题描述 | Problem description

  const fetchUserInfo = async () => {
    const userInfo = await initialState?.fetchUserInfo?.();
    if (userInfo) {
      await setInitialState((s) => ({
        ...s,
        currentUser: userInfo,
      }));
    }
  };
很想知道Pro里面的Login页面他登录成功后，有个await fetchUserInfo();但是不明白他是怎么获取到用户信息的。

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


为了理解`fetchUserInfo`是如何获取用户信息的，我们需要回顾一下前端开发流程和前端工程化。

前端开发流程一般包括需求分析、UI设计、前端开发、测试和上线部署等环节。在前端开发中，我们通常会使用一些框架和库来提高开发效率，比如React、Umi和Ant Design等。

前端工程化是为了提高前端开发效率和项目可维护性而出现的一种开发方式。它包括构建工具、模块化开发、自动化测试、代码规范和性能优化等方面。

在React开发中，我们通常使用状态管理库（比如Redux）来管理应用的状态。在Umi框架中，使用Model来管理应用的状态。`fetchUserInfo`很可能是一个定义在Model中的异步函数，用来获取用户信息。

根据代码片段:

```tsx | pure
const fetchUserInfo = async () => {
  const userInfo = await initialState?.fetchUserInfo?.();
  if (userInfo) {
    await setInitialState((s) => ({
      ...s,
      currentUser: userInfo,
    }));
  }
};
```

`fetchUserInfo`首先通过`initialState?.fetchUserInfo?.()`来调用Model中的`fetchUserInfo`函数，然后将返回的用户信息通过`setInitialState`更新到应用的初始化状态中。

那么问题来了，`initialState`是怎么来的呢？

根据代码片段:

```tsx | pure
export async function getInitialState(): Promise<{
  currentUser?: API.CurrentUser;
}> {
  // 如果是登录页面，不执行
  const currentUser = await fetchUserInfo();
  return {
    currentUser,
  };
}
```

可以看到，`getInitialState`是一个在Umi框架中定义的函数，它用来获取初始化数据。在这个函数中，我们可以执行一些异步操作，比如发送请求获取用户信息。

通过调用`fetchUserInfo`函数来获取用户信息，然后将当前用户信息作为`currentUser`的值返回。

而`getInitialState`函数会在应用启动时被调用，并将返回的初始化数据作为应用的初始状态。

所以，`fetchUserInfo`实际上是在`getInitialState`函数中通过调用Model中的`fetchUserInfo`函数来获取用户信息的。

希望这个解决方案对你有所帮助！如果还有其他问题，请随时提问。

**Comment by aammjian** [comment]
十分感谢你的回答。
其实最难理解的就是示例代码中的这个fetchUserInfo，在app.tsx中加载user信息，但是他是通过登录成功之后才会获取信息，但是代码中没有任何查询user信息的触发啊，所以一直不明白他代码里面的user信息是哪儿来的。

**Comment by aammjian** [comment]
上面的能再帮看看么

**Comment by chenshuai2144** [comment]
搜一下吧
