### ISSUE TITLE
🐛 [BUG] yarn start项目启动后，F12 console中发现js渲染存在问题

### ISSUE THREAD

**Issue by huangkenicole** [ant-design/ant-design-pro#11122]
## 问题
- 最新版本v6.0.0下，当我 `yarn start`后，渲染页面为空白。查看network的api部分所有均正常运行，console部分渲染异常如下：

![image](https://github.com/ant-design/ant-design-pro/assets/112435311/6cdb990a-18de-4f02-b3b3-9664d8128a39)

## 我的解决方案
我不确定我的解决方案是否正确，所以po上来看下是否是我本地存在问题。我修改部分为下面代码 （`config/routes.ts`文件）
![image](https://github.com/ant-design/ant-design-pro/assets/112435311/4eb5a98e-11d0-44b5-a2dd-766363487232)

**Comment by NguyenThinh-17001510** [comment]
i just need to change   component: '404' => './404'

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据你描述的问题，可能有以下解决方案：

1. 首先，确保你的项目依赖已经安装完整，可以尝试重新安装依赖：
   ```shell
   $ yarn install
   ```

2. 如果安装依赖后仍然存在问题，可以尝试升级 `react-scripts` 版本：
   ```shell
   $ yarn upgrade react-scripts
   ```

3. 如果升级 `react-scripts` 后仍然存在问题，可以尝试清除缓存并重新启动项目：
   ```shell
   $ yarn cache clean
   $ yarn start
   ```

4. 如果上述方法仍然无效，可以尝试删除 `node_modules` 目录并重新安装依赖：
   ```shell
   $ rm -rf node_modules
   $ yarn install
   $ yarn start
   ```

5. 如果以上方法都没有解决问题，可以尝试检查你的代码是否存在错误或者语法规范问题。可以通过 ESLint 来进行代码检查，运行以下命令：
   ```shell
   $ npm run lint
   ```

   如果有错误提示，按照提示进行修改。

6. 如果问题依然存在，可以尝试查看浏览器控制台错误信息的具体内容，并针对性地进行修复。

以上是一些常见的解决方案，如果问题还未解决，建议提供更多细节或者错误信息，以便进一步定位问题。
