### ISSUE TITLE
v6  混合模式 点击顶部菜单时 左侧菜单怎么显示被点击的菜单名称

### ISSUE THREAD

**Issue by Snow670** [ant-design/ant-design-pro#11127]
如图   怎么设置才能显示 网络 这个名字

![img](https://github.com/ant-design/ant-design-pro/assets/62977594/ef8f2836-88d8-4b60-aa1d-23a3cf63b15e)

**Comment by chenshuai2144** [comment]
根据您提供的代码片段，您正在创建一个名为 `layout` 的布局配置，并希望在 `menuProps` 中配置 `onSelect`，并将数据存储到 `initialValues` 中，然后通过 `menuTitleRender` 进行配置。

以下是一个示例，展示了如何在 `layout` 中完成这些配置：

```jsx
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  const onSelect = (selectedKeys) => {
    // 在这里处理选中菜单项的逻辑
    console.log('Selected keys:', selectedKeys);
    // 在这里更新 initialState 中的数据
    setInitialState((prevState) => ({
      ...prevState,
       selectedKeys: selectedKeys,
      },
    }));
  };

  const menuTitleRender = (menuItemProps, defaultDom) => {
    // 在这里自定义菜单标题的渲染
    return <div>{defaultDom}</div>;
  };

  return {
    menuProps: {
      onSelect: onSelect,
    },
    menuTitleRender: menuTitleRender,
  };
};
```

在上面的示例中，我们首先定义了一个名为 `onSelect` 的函数，用于处理选中菜单项的逻辑。在该函数内部，您可以根据需要对选中的菜单项进行处理，并将选中的键（selectedKeys）存储到 `initialValues` 中，以便后续使用。

接下来，我们定义了一个名为 `menuTitleRender` 的函数，用于自定义菜单标题的渲染。

最后，在 `layout` 函数的返回值中，我们将 `onSelect` 函数配置到 `menuProps` 的 `onSelect` 属性中，并将 `menuTitleRender` 配置为 `menuTitleRender`。

请注意，上述示例代码中的 `RunTimeLayoutConfig` 是假设的类型，您可能需要根据您的实际情况进行调整。此外，您还需要根据您的具体需求进行进一步的配置和调整，以确保代码能够正确运行并满足您的要求。
