### ISSUE TITLE
在AuthorizedRoute中打印rest.path，点击切换两个路由页面，为什么都要过一遍 '/'

### ISSUE THREAD

**Issue by MorisHarA** [ant-design/ant-design-pro#1112]
![1521171772422](https://user-images.githubusercontent.com/22467182/37502709-46bdd2e8-290f-11e8-88a2-dfea16e29415.jpg)

**Comment by chenshuai2144** [comment]
所有的页面都是 ‘'/' 中挂载的

**Comment by MorisHarA** [comment]
是哪段代码的导致的呢，我找了好久没看出来@chenshuai2144

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/bacc2031482e16d64243ef29aca181e6d3e2361e/src/layouts/BasicLayout.js#L186
