### ISSUE TITLE
🧐[问题 | question]【求助】如何正确部署到tomcat中，刷新就会报404。

### ISSUE THREAD

**Issue by uaena001** [ant-design/ant-design-pro#11129]
### 🧐 问题描述 | Problem description

这是我的pro版本：
ant-design-pro@6.0.0 build
info  - Umi v4.0.88

在运行npm run build之后将打包出来的dist中全部文件移动到tomcat的ROOT文件夹下后，不论哪个页面都只可以访问一次，只要在当前页刷新就会报404，搜了以前的issue和官方文档，开启[exportStatic]之后build会报错，以前的issue已经不适用最新版的pro了吧。

### 💻 示例代码 | Sample code

config/config.ts中加了配置：
{
    publicPath:'ROOT/',
    base: 'ROOT/',
}

OS:win 11

Node：18.18.2

浏览器 | browser：google

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题描述：
在运行npm run build之后将打包出来的dist中全部文件移动到tomcat的ROOT文件夹下后，不论哪个页面都只可以访问一次，只要在当前页刷新就会报404，搜了以前的issue和官方文档，开启[exportStatic]之后build会报错，以前的issue已经不适用最新版的pro了吧。

解决方案：
1. 确保publicPath和base配置正确：
   在config/config.ts中，将publicPath和base配置均修改为'/'而不是'ROOT/'。
   ```
   {
      publicPath: '/',
      base: '/',
   }
   ```
2. 确保Tomcat的配置正确：
   - 在conf/server.xml文件中，确认Context标签的docBase属性设置为Tomcat中dist目录的绝对路径。
   - 重新启动Tomcat服务器。

3. 检查Tomcat的web.xml配置：
   - 确认web.xml中是否存在以下配置：
     ```
     <error-page>
       <error-code>404</error-code>
       <location>/index.html</location>
     </error-page>
     ```
   - 如果不存在该配置，可以手动添加到web.xml文件中。

4. 检查URL Rewrite配置（如果有）：
   - 如果你使用了URL Rewrite规则，确保规则正确配置，并且不会导致404错误。

5. 检查前端路由配置：
   - 在使用React和Umi进行前端路由配置时，确保路由配置正确，没有遗漏或错误的路由配置。

6. 构建并部署项目：
   - 运行npm run build重新构建项目。
   - 将打包生成的dist文件夹中的所有文件移动到Tomcat的ROOT目录下。
   - 重新启动Tomcat服务器。

如果以上步骤仍然无法解决问题，建议进一步检查Tomcat的日志和浏览器的开发者工具，查看是否有其他错误提示，以便进一步排查和解决问题。
