### ISSUE TITLE
在登录页里判断跳转到根路径页面会引起循环 🐛 [BUG]

### ISSUE THREAD

**Issue by ldh97** [ant-design/ant-design-pro#11133]
### 🐛 bug 描述

在登录页里判断跳转到根路径页面会引起死循环，反复在/ 和 /user/login之间跳转

### 📷 复现步骤 | Recurrence steps

在 User/Login/index.tsx 加上这段逻辑就会出现
![image](https://github.com/ant-design/ant-design-pro/assets/29684412/79f6efe4-fadb-40da-9fda-f1ba4d0fff1e)

### 🏞 期望结果 | Expected results

如果已经登陆，再次访问登陆页面时需要跳转到根页面

### © 版本信息

- Ant Design Pro 版本: 6.0
- umi 版本 4.1.1
- 浏览器环境 chrome
- 开发环境 windows

**Comment by wlzscn** [comment]
您好 请教一下这个问题解决了么 我也想解决这个问题

**Comment by ldh97** [comment]
> 您好，请教一下这个问题解决了吗？我也想解决这个问题

没有解决，我直接把登录页改成一级路由就能正常跳转了

**Comment by wlzscn** [comment]
> > 您好，请教一下这个问题解决了吗？我也想解决这个问题
> 
> 没有解决，我直接把登录页改成一级路由就能正常跳转了

好的 感谢

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据提供的信息，判断登录页跳转到根路径页面会引起循环的问题可能是因为登录页的逻辑判断不准确，导致在每次访问登录页时都会被重定向到根路径页面。

解决这个问题的思路如下：

1. 确保登录页只在未登录状态下显示，已登录状态下需要跳转到根路径页面。
2. 在登录页的逻辑判断中，使用合适的条件来判断用户是否已经登录。
3. 如果用户已经登录，使用合适的方式进行页面跳转，确保不会引起循环重定向。
4. 在页面跳转时，可以使用 React 的 useHistory 或 UmiJS 的 history 对象来实现跳转功能。
5. 验证修改后的代码逻辑是否正确，通过在登录页中输入不同的登录信息进行测试，确保已登录状态下能够正确跳转到根路径页面。
6. 可以根据具体的业务需求对登录页的逻辑进行扩展，例如增加记住密码、忘记密码等功能。

具体的代码修改和实现逻辑，需要进一步了解前端项目的具体实现和框架技术（如 React 和 UmiJS）以及登录页的具体代码结构。根据以上的思路和提供的问题描述，可以尝试按照这个思路进行修改和调试，再根据具体情况来细化实现。

**Comment by ldh97** [comment]
> > 意思是百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
> > 删除 'node_modules' 文件夹 -> 删除 'package-lock.json' 或 'pnpm-lock.yaml'文件 -> 运行 'pnpm install' 或 'npm install' 命令
> 
> 根据提供的信息，判断登录页面跳转到根路径页面会引起循环的问题可能是因为登录页面的逻辑判断不准确，导致在每次访问登录页面时都会被重定向到根路径页面。
> 
> 解决这个问题的思路如下：
> 
> 1. 确定登录页面只在未登录状态下显示，已登录状态下需要跳转到根路径页面。
> 2. 在登录页的逻辑判断中，使用适当的条件来判断用户是否已经登录。
> 3. 如果用户已经登录，使用正确的方式进行页面跳转，确保不会引起循环跳转。
> 4. 在页面跳转时，可以使用React的useHistory或UmiJS的history对象来实现跳转功能。
> 5. 验证修改后的代码逻辑是否正确，通过在登录页面中输入不同的登录信息进行测试，确保已登录状态下能够正确跳转到根路径页面。
> 6. 可以根据具体的业务需求对登录页的逻辑进行扩展，例如增加记住密码、忘记密码等功能。
> 
> 具体的代码修改和实现逻辑，需要进一步了解前端项目的具体实现和框架技术（如React和UmiJS）以及登录页面的具体代码结构。根据以上的思路并提供问题的描述，尝试可以按照这个思路修改进行和调试，再根据具体情况来细化实现。



> > > 您好，请教一下这个问题解决了吗？我也想解决这个问题
> > 
> > 
> > 没有解决，我直接把登录页改成一级路由就能正常跳转了
> 
> 好的 感谢

找到原因了
1、app.tsx里 getInitialState 方法 如果是登录页的时候就不会 调用fetchUserInfo方法加载 currentUser，此时initialState.currentUser为空
2、从登录页面跳转根页面的时候会加载 app.tsx 中的 layout组件并触发 onPageChange 回调
![image](https://github.com/ant-design/ant-design-pro/assets/29684412/a2110a71-e1a8-4a9d-99af-83217f68f014)
此时 getInitialState 还没有被再次调用，initialState.currentUser 还是空的，会跳转到登录页，从而引起循环
