### ISSUE TITLE
请问菜单从服务端获取，为什么还要在 routes 配置好全部，否则就不能正常解析

### ISSUE THREAD

**Issue by ft20082** [ant-design/ant-design-pro#11137]
### 🧐 问题描述 | Problem description

请问菜单从服务端获取，为什么还要在 routes 配置好全部，否则就不能正常解析

比如，客户端的配置项 layout ,   component ，在服务端 menuDataRender 里的是不提供配置的

从服务端获取的菜单如果不包含本地已有的路由，如果浏览器里输入，还是能够正常访问，

那从服务端获取菜单的意义是什么？只是重新渲染下菜单的内容？难道不应该以服务端获取的菜单列表作为限制？

**Comment by chenshuai2144** [comment]
这个问题涉及到前端开发流程和前端工程化的概念。

首先，从服务端获取菜单的意义在于动态生成菜单，使得菜单内容可以随着服务端数据的变化而变化。这样可以减少前端代码的维护成本，同时也能够在后台管理系统中灵活地配置菜单。

但是，为什么还要在routes配置全部，否则就不能正常解析呢？这是因为前端路由是用来控制页面的展示和跳转的，如果某个路由在routes中没有配置，那么就无法根据该路由来渲染对应的页面。

**Comment by wavesbig** [comment]
> 这个问题涉及到前端开发流程和前端工程化的概念。
> 
> 首先，从服务端获取菜单的意义在于动态生成菜单，使得菜单内容可以随着服务端数据的变化而变化。这样可以减少前端代码的维护成本，同时也能够在后台管理系统中灵活地配置菜单。
> 
> 但是，为什么还要在routes配置全部，否则就不能正常解析呢？这是因为前端路由是用来控制页面的展示和跳转的，如果某个路由在routes中没有配置，那么就无法根据该路由来渲染对应的页面。
> 
> 路由决定页面要不要被打包，菜单只是给了个入口

有没有提供个更好的方法使用后台的数据进行加载页面组件喃
