### ISSUE TITLE
disableDynamicImport 无效了 因为我把目录结构改了。。。

### ISSUE THREAD

**Issue by denggy** [ant-design/ant-design-pro#1113]
![image](https://user-images.githubusercontent.com/3114067/37506614-a658eb8c-2925-11e8-8a73-878984fbee78.png)
如图 我把disableDynamicImport参数改为false 但是页面无法动态加载了
我的目录结构如下
![image](https://user-images.githubusercontent.com/3114067/37506682-fa84834c-2925-11e8-811e-ec4f53d28e24.png)

请问各位 各位大佬 我该怎么改 能让项目支持 点击页面的时候 动态加载内容

**Comment by chenshuai2144** [comment]
disableDynamicImport 关掉之后才会动态加载

**Comment by denggy** [comment]
@chenshuai2144 disableDynamicImport:false 不是关掉 吗

问题是我关掉了  也不会动态加载了  因为我把目录结构改了

**Comment by denggy** [comment]
@chenshuai2144 认真的看下问题好不好呢

**Comment by chenshuai2144** [comment]
这个和目录结构没有关系的。
你打包之后出来的是几个文件？

**Comment by denggy** [comment]
我现在打包4个js文件
他好像无法根据业务拆分了
我感觉指定跟目录结构有关系的

**Comment by chenshuai2144** [comment]
show code？

**Comment by denggy** [comment]
我上面的截图 就是我目前的目录结构
其他的地方我都没改
show code 你想看哪块的代码呢？？

**Comment by chenshuai2144** [comment]
Common layout

**Comment by denggy** [comment]
common里面什么都没有了 我把菜单和路由 数据改成从后台获取了    
layouts里基本没改 
就是说 我没改目录结构  按照 models routes services 就是原始的项目结构  是可以动态加载的
后来我按照业务分了  有个modules文件夹 就是modules下有每个业务文件夹 然后下面 包含models pages services  也就是如图的样子  。。。 结果就不行了
（PS：公司的代码是在git上的  但是私有的 所以不能给你地址看 sorry啊）
