### ISSUE TITLE
🐛 [BUG]renderFormItem中是用defaultRender时，校验提示文案出现双份。

### ISSUE THREAD

**Issue by dakani** [ant-design/ant-design-pro#11135]
### 📷 复现步骤 | Recurrence steps
输入非法的数字，是输入框校验不通过，并出现错误提示。此时错误提示会出现双份。

### 🏞 期望结果 | Expected results
期望结果是： 只出现一份错误校验的提示文案
![image](https://github.com/ant-design/ant-design-pro/assets/13744382/f3c15ded-4131-49f6-b1fa-0ecd6dd37040)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


根据问题描述，问题出现在 renderFormItem 中使用 defaultRender 时，校验提示文案出现双份。解决方案如下：

1. 检查校验提示文案是否是重复生成，可以在 renderFormItem 中打印一下 schema 字段或者提示文案的值，确认是否生成了两次。
2. 检查是否存在重复的校验规则或者错误提示的配置。可以在 schema 中查看是否有重复的 rules 字段或者 validateMessages 字段。
3. 可以尝试使用 antd 的 Form.Item 组件自带的 validateTrigger 属性进行校验触发的控制，避免重复校验。可以将 validateTrigger 设置为 onBlur 或者其他适合的触发时机。
4. 可以尝试将校验提示文案提取到外部的变量或者常量中，保证只生成一份提示文案，然后在 renderFormItem 中引用该变量或者常量，避免重复生成。
5. 如果以上方案都无效，可以尝试升级 Ant Design Pro 或者 umi 的版本，以确保使用的是最新的稳定版，可能存在已知的 bug 和解决方案。

以上是一些可能的解决方案，根据具体情况选择相应的方案进行尝试。如果问题仍然存在，建议提供更多的代码片段或者错误提示的具体信息，以便更好地分析和定位问题。
