### ISSUE TITLE
👑 [需求 | Feature] v5预览版的暗黑模式怎么启用？

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design-pro#11130]
### 🥰 需求描述 | Requirements description

启用 https://preview.pro.ant.design/ 的暗黑模式

**Comment by chenshuai2144** [comment]
https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98

看这个文档，觉得麻烦直接用   SettingDrawer
