### ISSUE TITLE
🐛 [BUG]开启  tabsLayout: {     hasCustomTabs: true,   } /.umi/plugin-keepalive/context.tsx文件中会报图标没有找到VerticalRightOutlined is not defined

### ISSUE THREAD

**Issue by liqiushi720** [ant-design/ant-design-pro#11138]
### 🐛 bug 描述

项目中开启
  keepalive: [/./],
  tabsLayout: {
    hasCustomTabs: true,
  },
### 🏞 期望结果 | Expected results
可以正确的自定义tabs

### 💻 复现代码 | Recurrence code

![image](https://github.com/ant-design/ant-design-pro/assets/97832155/439e6a16-bfda-42d3-906c-55a93143a6b7)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
找一下这个插件的作者解决吧，这个不是我们的插件
