### ISSUE TITLE
🧐[问题 | question] 在React中使用Ant Design Pro最新版时，在defaultSettings.ts中配置了colorPrimary，怎么在.less文件中使用该主题色（求不要贴GPT回复）

### ISSUE THREAD

**Issue by xiohuchi** [ant-design/ant-design-pro#11131]
### 🧐 问题描述 | Problem description

在React中使用Ant Design Pro V5版本时，在defaultSettings.ts中配置了colorPrimary，怎么在.less文件中使用该主题色？

`
    .title {
        color: @primary-color;
    }
`
 上面less文件中，使用了主题色，但是不行

**Comment by chenshuai2144** [comment]
现在不通了，推荐使用 cssinjs  的方案，不然动态变化没法做了

**Comment by xiohuchi** [comment]
哎，less都不能愉快的玩耍了
