### ISSUE TITLE
🐛 [BUG] 在v6 框架中，Table组件设置sticky属性后，表头浮动在手机端不兼容。

### ISSUE THREAD

**Issue by Mr-amw** [ant-design/ant-design-pro#11132]
### 🐛 bug 描述
Table组件在设置sticky属性后，电脑端表头浮动显示正常，切换到手机端时，浮动效果失效。如果设置sticky={{offsetHeader: 56}}，电脑端正常，手机端的表头会向下偏移56px，遮挡前几行的数据。
ProTable也有一样的问题。

### 📷 复现步骤 | Recurrence steps
随便一个表格都行，框架中自带的表格也可以复现。只要切换到手机屏幕，浮动效果就会消失。
### 🏞 期望结果 | Expected results
请告知如何修复，或能否解决

### 💻 复现代码 | Recurrence code
```
import { Table }from 'antd';

const Demo: React.FC = () => {

    const columns = [
        {
            title: 'ID',
            dataIndex: 'id',
            key: 'id',
        },
        {
            title: '标示',
            dataIndex: 'name',
            key: 'name',
        },
        {
            title: '描述',
            dataIndex: 'desc',
            key: 'desc',
        },
    ];

    const data = []

    for (let i = 0; i < 50; i++) {
        data.push({
            id: i,
            name: `标示${i}`,
            desc: `描述${i}`,
        })
    }  
    return (
        <Table
            size='small'
            dataSource={data}
            columns={columns}
            pagination={false}
            style={{ marginTop: 5 }}
            sticky={{ offsetHeader: 56 }}
        />
    );
  };
  
  export default Demo;
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0]
- umi 版本 ：v4.0.87
- 浏览器环境：chrome最新版本
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
手机端异常表象如下
![20240119154035_rec_](https://github.com/ant-design/ant-design-pro/assets/61767755/8c16f1b8-cba9-4327-8cd6-099b2415f0a8)
电脑端正常显示如下
![20240119154219_rec_](https://github.com/ant-design/ant-design-pro/assets/61767755/c68689da-3c83-4382-b955-35d77082552d)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题的解决方案：

1. 问题分析：根据bug描述，Table组件设置sticky属性后，在电脑端表头浮动显示正常，但在手机端浮动效果失效，并且设置sticky={{offsetHeader: 56}}会导致手机端表头的偏移问题。

2. 解决方案：根据问题分析，可以采用以下解决方案：

   - 用JavaScript判断当前设备是否为手机端，如果是手机端，则不使用sticky属性，而是使用一种手机端兼容的方式实现表头浮动效果。

   - 可以使用CSS的position属性和overflow属性来实现表头的浮动效果。

   下面给出一个基于React和antd的解决方案示例代码：

   ```javascript
   import React from 'react';
   import { Table } from 'antd';

   const isMobile = () => {
     const userAgent = navigator.userAgent;
     return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(userAgent);
   }

   const StickyTable = () => {
     const columns = [
       {
         title: 'ID',
         dataIndex: 'id',
         key: 'id',
       },
       {
         title: '标示',
         dataIndex: 'name',
         key: 'name',
       },
       {
         title: '描述',
         dataIndex: 'desc',
         key: 'desc',
       },
     ];

     const data = [];

     for (let i = 0; i < 50; i++) {
       data.push({
         id: i,
         name: `标示${i}`,
         desc: `描述${i}`,
       });
     }

     const tableProps = {
       size: 'small',
       dataSource: data,
       columns: columns,
       pagination: false,
       style: { marginTop: 5 },
     };

     return (
       <React.Fragment>
         {isMobile() ? (
           <div style={{ overflowX: 'auto' }}>
             <table>
               <thead>
                 <tr>
                   {columns.map((column) => (
                     <th key={column.key} style={{ position: 'sticky', top: 0, background: '#fff' }}>
                       {column.title}
                     </th>
                   ))}
                 </tr>
               </thead>
               <tbody>
                 {data.map((record) => (
                   <tr key={record.id}>
                     {columns.map((column) => (
                       <td key={column.key}>{record[column.dataIndex]}</td>
                     ))}
                   </tr>
                 ))}
               </tbody>
             </table>
           </div>
         ) : (
           <Table {...tableProps} sticky={{ offsetHeader: 56 }} />
         )}
       </React.Fragment>
     );
   };

   export default StickyTable;
   ```

   上述代码中，我们通过isMobile函数判断当前设备是否为手机端，如果是手机端，则使用纯CSS实现表头的浮动效果；如果不是手机端，则使用antd的Table组件，并设置sticky属性为{offsetHeader: 56}。

   通过以上方案，可以在保持电脑端的表头浮动效果不变的情况下，实现手机端的兼容性。

**Comment by Mr-amw** [comment]
已经找到是哪里导致的不兼容了。在框架内的src目录下有个global.less文件，将.ant-table内的overflow-x删掉（如下图），手机端的表头浮动和错位的问题就都解决了。目前没发现这行样式删除后的副作用。你们判断下如此修改是否可行以及修复git内的代码。
![image](https://github.com/ant-design/ant-design-pro/assets/61767755/2ba89933-dd48-4a4e-bde3-ddd5264dde52)


> > 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
> > 删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令
> 
> 问题的解决方案：
> 
> 1. 问题分析：根据bug描述，Table组件设置sticky属性后，在电脑端表头浮动显示正常，但在手机端浮动效果失效，并且设置sticky={{offsetHeader: 56}}会导致手机端表头的偏移问题。
> 2. 解决方案：根据问题分析，可以采用以下解决方案：
>    
>    * 用JavaScript判断当前设备是否为手机端，如果是手机端，则不使用sticky属性，而是使用一种手机端兼容的方式实现表头浮动效果。
>    * 可以使用CSS的position属性和overflow属性来实现表头的浮动效果。
>    
>    下面给出一个基于React和antd的解决方案示例代码：
>    ```js
>    import React from 'react';
>    import { Table } from 'antd';
>    
>    const isMobile = () => {
>      const userAgent = navigator.userAgent;
>      return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(userAgent);
>    }
>    
>    const StickyTable = () => {
>      const columns = [
>        {
>          title: 'ID',
>          dataIndex: 'id',
>          key: 'id',
>        },
>        {
>          title: '标示',
>          dataIndex: 'name',
>          key: 'name',
>        },
>        {
>          title: '描述',
>          dataIndex: 'desc',
>          key: 'desc',
>        },
>      ];
>    
>      const data = [];
>    
>      for (let i = 0; i < 50; i++) {
>        data.push({
>          id: i,
>          name: `标示${i}`,
>          desc: `描述${i}`,
>        });
>      }
>    
>      const tableProps = {
>        size: 'small',
>        dataSource: data,
>        columns: columns,
>        pagination: false,
>        style: { marginTop: 5 },
>      };
>    
>      return (
>        <React.Fragment>
>          {isMobile() ? (
>            <div style={{ overflowX: 'auto' }}>
>              <table>
>                <thead>
>                  <tr>
>                    {columns.map((column) => (
>                      <th key={column.key} style={{ position: 'sticky', top: 0, background: '#fff' }}>
>                        {column.title}
>                      </th>
>                    ))}
>                  </tr>
>                </thead>
>                <tbody>
>                  {data.map((record) => (
>                    <tr key={record.id}>
>                      {columns.map((column) => (
>                        <td key={column.key}>{record[column.dataIndex]}</td>
>                      ))}
>                    </tr>
>                  ))}
>                </tbody>
>              </table>
>            </div>
>          ) : (
>            <Table {...tableProps} sticky={{ offsetHeader: 56 }} />
>          )}
>        </React.Fragment>
>      );
>    };
>    
>    export default StickyTable;
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    上述代码中，我们通过isMobile函数判断当前设备是否为手机端，如果是手机端，则使用纯CSS实现表头的浮动效果；如果不是手机端，则使用antd的Table组件，并设置sticky属性为{offsetHeader: 56}。
>    通过以上方案，可以在保持电脑端的表头浮动效果不变的情况下，实现手机端的兼容性。
