### ISSUE TITLE
🐛 [BUG]  devScripts.js:6523 Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.

### ISSUE THREAD

**Issue by Dssssds** [ant-design/ant-design-pro#11140]
### 🐛 bug 描述

Bug 提示： 
* devScripts.js:6523 Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.
* Warning: [antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly.

### © 版本信息

- Ant Design Pro 版本: "antd": "^4.20.0",
- umi 版本   "umi": "^3.5.0"
- 浏览器环境 ： chrome
- 开发环境   mac os

### 🚑 其他信息

![image](https://github.com/ant-design/ant-design-pro/assets/17268259/32da230e-152d-4ff7-b5ca-67a514540f1f)

**Comment by chenshuai2144** [comment]
查一下哪个插件用了这个功能，umi的最新版本已经升级了。
