### ISSUE TITLE
为什么我clone下来 跟preview的差别这么大 少了这么多菜单

### ISSUE THREAD

**Issue by lihong1232** [ant-design/ant-design-pro#11159]
![image](https://github.com/ant-design/ant-design-pro/assets/10403261/2a2929d0-26bc-4401-b0a6-693c536ba907)
![image](https://github.com/ant-design/ant-design-pro/assets/10403261/e27b7c44-681d-47ef-b01f-7ef975b7757c)

**Comment by a00316105** [comment]
You need to install the complexed framework ,not the simple.

**Comment by lihong1232** [comment]
How can I install the complexed framework? I just run "npm install" command.

**Comment by lihong1232** [comment]
first I clone this project to my local . second , I run "npm  install " command , third , I run "npm run start" command, then the simple page will be running , how can I install the complexed framework?

**Comment by Heee17** [comment]
初始化脚手架时候 选 umi3 吧 再选 complete ，应该

**Comment by iscmcloud** [comment]
直接拉 all-blocks 这个分支试试看

**Comment by lihong1232** [comment]
> 初始化脚手架时候 选 umi3 吧 再选 complete ，应该

初始化的时候 npm install 并没有选择 umi3这个选项呀。

**Comment by lihong1232** [comment]
I know , the answer is in the document.
