### ISSUE TITLE
🧐[问题 | question]项目部署的时候提示commander依赖的node版本必须大于18，为什么低版本的也会收到这个影响

### ISSUE THREAD

**Issue by liubaoquan-914** [ant-design/ant-design-pro#11154]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by zhangwudi886** [comment]
babel的依赖问题，使用安装最新的包。包的版本限制是18，因为我本地有lock，所以本地没问题。但是线上出现了这个问题。npm或者yarn的时候使用ignore-engines 纯上线的话可以加上这个。忽略了就行。本地的话。估计得限制一下版本

**Comment by HookAder** [comment]
请问解决了嘛？

**Comment by liubaoquan-914** [comment]
感谢，已经好了，在package.json中限制一下这个依赖的版本号就可以了。

**Comment by HookAder** [comment]
@liubaoquan-914 请问是通过"resolutions": { "**/mockjs/commander": "x.x.x" }, 限制的吗？

**Comment by liubaoquan-914** [comment]
是的

**Comment by liubaoquan-914** [comment]
<img width="409" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/74593688/e297ef82-5737-4aaa-a3ee-7ac0372b6d27">
