### ISSUE TITLE
最新版本的Pro在install完成之后无法运行

### ISSUE THREAD

**Issue by OliverJason** [ant-design/ant-design-pro#1116]
把antd pro项目拉下来之后，执行了install，所有包已经下载下来了。
然后连续出现几个问题：
    1、找不到webpack，于是cnpm install webpack，安装成功；
    2、找不到address，于是cnpm install address，安装成功；
    3、找不到@babel/core，cnpm install babel，提示已经安装
之后就没有继续了，失望。。。

**Comment by chenshuai2144** [comment]
你的npm是不是坏了？

**Comment by OliverJason** [comment]
没问题的，我自己的项目都能运行，就是pro不行

**Comment by OliverJason** [comment]
![image](https://user-images.githubusercontent.com/20814213/37510608-b1cd5bb8-2936-11e8-92a9-54292ba235d3.png)
跟这个有关吗

**Comment by afc163** [comment]
把你的安装和运行的完整日志贴出来。

**Comment by OliverJason** [comment]
换了一个文件目录，又可以了。。。
