### ISSUE TITLE
👑 [需求 | Feature]是否可以用 json-schema-faker 代替 mockjs

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design-pro#11175]
### 🥰 需求描述 | Requirements description

看了下 mockjs 的 npm 仓库，最后一个版本已经是四年前的了，仓库貌似也不维护了，如果是针对 openapi 实现数据模拟的话，是不是可以使用 https://github.com/json-schema-faker/json-schema-faker 来代替 mockjs

**Comment by vini123** [comment]
虚幻之物对应着冥冥之路！：《羽》
