### ISSUE TITLE
🐛 [BUG] cli 搭建项目运行报路由错误

### ISSUE THREAD

**Issue by MomoKiller** [ant-design/ant-design-pro#11171]
### 🐛 bug 描述

使用cli 搭建的项目，安装好依赖后运行。报以下路由信息错误。
Uncaught Error: Absolute route path "/*" nested under path "/user" is not valid. An absolute child route path must start with the combined path of all its parent routes.

### 📷 复现步骤 | Recurrence steps
1. 使用cli 搭建的项目，安装好依赖后运行。报以下路由信息错误。
![image](https://github.com/ant-design/ant-design-pro/assets/8392161/84669dac-a8bc-489c-8562-a8efcea2c4cf)
2. 在 config/routees.ts 文件中找到 /user 下的子路由 /* ，并注释掉后项目正常运行
![image](https://github.com/ant-design/ant-design-pro/assets/8392161/9ac1bdf9-e390-4978-a88b-fe384ed8cfb4)

### 🏞 期望结果 | Expected results
项目正常运行，通过账号密码登录进项目首页

### 💻 复现代码 | Recurrence code
config/routees.ts 文件中 /user 子路由中有路由会报错，注释掉后正常
```
{
        component: '404',
        path: '/*',
      },
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ldawson951** [comment]
遇到同样的问题了，我想知道为什么会出现这样子的问题
我的软件版本如下：
node：v18.16.1
npm：9.5.1
yarn：1.22.22

然后根据你的指示解决了问题，但是发现修改代码后，直接访问localhost:8000根本不需要登录就直接帮你登录好了，我一开始以为是浏览器cookie和session问题，于是我清除了cookie和session，也用了无痕浏览器进行访问依旧是直接帮你登录好了，这是为什么呢？

**Comment by mylc2010** [comment]
同样遇到@ldawson951 的这个问题，修改以后直接就跳过了登录页面

**Comment by BJERGSEN97** [comment]
同样遇到@ldawson951 的这个问题，修改以后直接就跳过了登录页面
