### ISSUE TITLE
🧐[问题 | question]：createStyles在WebStorm中报红线

### ISSUE THREAD

**Issue by mayongkang1** [ant-design/ant-design-pro#11172]
antdPro版本：3.1.0
虽然不影响什么，但是看着很烦
求解
![image](https://github.com/ant-design/ant-design-pro/assets/94114667/07ee3b96-23ac-4ab5-801c-fb675781af7c)

**Comment by passallcode** [comment]
![32cbf32f79f9bdd3c048741e026eb97](https://github.com/ant-design/ant-design-pro/assets/147292285/dfef8b48-fbad-4778-b5c0-27932d1b4179)
这样试试

**Comment by SongZX0106** [comment]
你好，请问是怎么解决的呢，我也遇到了这个问题
