### ISSUE TITLE
async/await，应该成对出现啊？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#1118]
在**\src\service\xx.js**中有**function**中都加了**async**，但没有看到**await**，**async/await**是不是应该成对出现啊？
@afc163

**Comment by u3u** [comment]
没有规定 `async` 函数中必须使用 `await` 语句
但是 `await` 语句只能在 `async` 函数中使用

**Comment by afc163** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/507615/37511438-c97ca8f6-2939-11e8-97a6-2657d8f91d76.png">

**Comment by afc163** [comment]
这种问题不应该再这里开 issue。
