### ISSUE TITLE
新版的 dynamicWrapper 方法 如何实现多级的路由？

### ISSUE THREAD

**Issue by wind13** [ant-design/ant-design-pro#1119]
相关的文档太少，没找到。

需求：
/compony    ---> <CompanyList>  点击某个 公司 进入公司详情
/company/:id --->  <Company> 点击产品列表 进入产品列表
/company/:id/product --->  <ProductList> 点击某个产品进入 产品详情
/company/:id/product/:id  ----> <Product> 产品详情

看了半天源代码，完全不知道怎么设置那个 routeConfig， 能否给出一些示例？特别是面包屑这块儿怎么实现？

谢谢！

**Comment by ddcat1115** [comment]
如果你的次级路由（/company/:id）需要嵌套在父级路由（/compony）组件中渲染，可以参考脚手架中搜索列表相关的[配置](https://github.com/ant-design/ant-design-pro/blob/master/src/common/router.js#L118) 及组件实现，如果不需要嵌套，请参考[文档-嵌套路由同级展示](https://pro.ant.design/docs/router-and-nav-cn#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA) 或直接用 routerData 进行渲染（不使用 getRoutes）

**Comment by ddcat1115** [comment]
相关 -> https://github.com/ant-design/ant-design-pro/issues/1065

**Comment by tuibian** [comment]
@ddcat1115 getRouterData函数是怎么把path和组件绑定在一起的呢？比如下图：
![image](https://user-images.githubusercontent.com/14135471/37558457-8ebbd572-2a4f-11e8-9143-607c167d459d.png)
怎么匹配/user/login到Login组件的

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js
在这个文件里面。185L

**Comment by tuibian** [comment]
@chenshuai2144 明白了 谢谢你的解答
