### ISSUE TITLE
这个工程后面还会继续维护吗？ 以及后期的版本计划，麻烦告知一下 ，因为正在做选型，感谢

### ISSUE THREAD

**Issue by mindsfsdfwe** [ant-design/ant-design-pro#11213]
这个工程后面还会继续维护吗？ 以及后期的版本计划，麻烦告知一下 ，因为正在做选型，感谢

**Comment by CyberQin** [comment]
目前观察到 @chenshuai2144 大大仍然在频繁commit到ant design和pro components。
估计是组件库基础设施的活还没忙完，ant design pro这种上层建筑无法锁版。
v6应该主要是基于ant design的样式模式改造而更新的。本身前端框架已经没什么特别需要更新的了，毕竟react18.2已经锁版号2年了。
ant design pro其实已经算比较完整稳定的框架，短时间内不更新也没问题，而且技术选型定了以后，最好是不升级吧。

**Comment by sansheng741** [comment]
v6已经用了一年了确实没有遇到特别严重的问题

**Comment by CyberQin** [comment]
更新自己的观点：
1、为了追求稳定，现在应该直接使用当前方案锁版开发，因为目前react生态将面临v19的革命，各种warning和error。
2、阿里巴巴进行了大规模拆中台，该项目归类为中台项目，估计人员和资源面临紧张或者直接被转移的问题。
