### ISSUE TITLE
是否存在有process.env.NODE_ENV === "development" 的环境变量提供判断？

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design-pro#1123]
Hi！我刚接触AntDesign-Pro这个项目，但是因为开发过程中会写一些开发才执行的代码，需要一个类似process.env.NODE_ENV这样的值来判断。   
尝试了以下代码到.webpackrc.js里面，结果行不通
```js
{
   "define": {
       // set env here
   }
}
```
同时还翻遍了.roadhog和Ant Deisgn Pro的文档和Issue，也没能找到关于这方面的实际解决办法，希望开发者解答一下，谢谢！

**Comment by chenshuai2144** [comment]
`export NODE_ENV=development&&yarn start`

**Comment by LaiHuanMin** [comment]
@chenshuai2144  谢谢回复！ 但是我尝试了一下好象不太行，我的操作系统是Ubuntu16.04 LTS，使用的浏览器是 Chromium 64.0.3282.167。  
我希望能在src/index.js文件里添加一个开发和生产的判断，但在console.log(process)的结果process.env是一个空的对象。我还尝试了.webpackrc.js的define，好像也不能奏效。  
这是我做的一个demo仓库https://github.com/LaiHuanMin/issue-antDesignPro-process/，您看下

**Comment by chenshuai2144** [comment]
process.env.NODE_ENV 是 node 的环境变量， 浏览器中是没有的。

**Comment by LaiHuanMin** [comment]
@chenshuai2144  嗯，但是在create-react-app的脚手架里面可以输出process.env.NODE_ENV是“development”，但是在roadhog的脚手架里面我看不到有process.env.NODE_ENV的值，即使是设置了define也还是行不通。    
您的意思是不是说，process.env.NODE_ENV只能在.webpackrc.js这些配置文件里面使用，但是不能在src下面的代码里面使用？

**Comment by chenshuai2144** [comment]
只能在node.js 的环境中使用. 代码是运行在浏览器里面的。
你可以学学 react 的方式 注入一个env.NODE_ENV 对象

**Comment by LaiHuanMin** [comment]
好的，谢谢。我写了个shell脚本来控制Env了
