### ISSUE TITLE
请教下这段代码---Code Problem

### ISSUE THREAD

**Issue by laozb** [ant-design/ant-design-pro#1124]
首先，下面的代码位置在   src/routes/Dashboard/Analysis.js下

@connect(({ chart, loading }) => ({
  chart,
  loading: loading.effects['chart/fetch'],
}))

1.loading里存放什么，有什么用？

2.传入connect的箭头函数有个参数 chart。这个chart参数里是包含了models下chart.js中export的内容吗。

3.传入connect方法的是个怎样的对象，应该是app.model注册过的model都会作为属性放在里面吧？

4.dynamicWrapper方法主要的作用是什么，，看到调用了app.model方法。。其他的还有什么作用

please help me。。。万分感谢各位大大😭😭😭🙏🙏🙏

**Comment by chenshuai2144** [comment]
redux 的语法。学习一下 redux 就懂了
