### ISSUE TITLE
authority

### ISSUE THREAD

**Issue by ynnyh** [ant-design/ant-design-pro#1127]
现在的权限管理是登陆后本地保存一个用户角色，那么能不能在登陆时保存多个角色这样子，刚才试了不行

**Comment by chenshuai2144** [comment]
可以使用传入 fucntion 来自定义

**Comment by iblilife** [comment]
文档里面是有可以自己定义函数: 
`RenderAuthorized: (currentAuthority: string | () => string) => Authorized`
传入一个返回string的函数, 多个角色的情况需要按照什么格式构建这个string?

**Comment by chenshuai2144** [comment]
Authorized 组件可以使用 function  
RenderAuthorized 是用来生成Authorized，暂时不支持多角色
