### ISSUE TITLE
🧐[问题 | question]build后首次白屏的问题，headScripts 中设置了loading.js

### ISSUE THREAD

**Issue by echoyl** [ant-design/ant-design-pro#11288]
已经在config中设置了 headScripts 的loading.js
这个loading.js 会在构建后的index.html 的head标签里面，这个时候 const _root = document.querySelector('#root')的_root是没有的，所以不会执行loading。需要把这个loading的js放到dom后面才会执行。
问下这个有什么解决方法吗？
如果设置在 config的 scripts 中 这个js虽然被放到了body里面 但是是在 umi.js 后面还是要等它加载完才会执行，所以还是无效。

**Comment by ali-upgrade** [comment]
我们也遇到了这个问题：在开启umi的分包策略之后  
`  codeSplitting: {
    jsStrategy: 'granularChunks',
  },`
build产物之后，不出现loading效果了，打印loading.js时拿不到_root

**Comment by echoyl** [comment]
> 我们也遇到了这个问题：在开启umi的分包策略之后 ` codeSplitting: { jsStrategy: 'granularChunks', },` build产物之后，不出现loading效果了，打印loading.js时拿不到_root

暂时只能 build后修改index.html 把loading.js 放到 body中的root后面 umi.js的前面

**Comment by ali-upgrade** [comment]
我们时采用了umi的插件机制将loading.js放入rootdiv下解决的
`import { IApi } from "umi";

export default (api: IApi) => {
  api.modifyHTML(($) => {
    $("#root").append([
      `
     <style>
        html,
        body,
        #root {
          height: 100%;
          margin: 0;
          padding: 0;
        }
        #root {
          background-repeat: no-repeat;
          background-size: 100% auto;
        }

        .loading-title {
          font-size: 1.1rem;
        }

        .loading-sub-title {
          margin-top: 20px;
          font-size: 1rem;
          color: #888;
        }

        .page-loading-warp {
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 26px;
        }
        .ant-spin {
          position: absolute;
          display: none;
          -webkit-box-sizing: border-box;
          box-sizing: border-box;
          margin: 0;
          padding: 0;
          color: rgba(0, 0, 0, 0.65);
          color: #1890ff;
          font-size: 14px;
          font-variant: tabular-nums;
          line-height: 1.5;
          text-align: center;
          list-style: none;
          opacity: 0;
          -webkit-transition: -webkit-transform 0.3s
            cubic-bezier(0.78, 0.14, 0.15, 0.86);
          transition: -webkit-transform 0.3s
            cubic-bezier(0.78, 0.14, 0.15, 0.86);
          transition: transform 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86);
          transition: transform 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86),
            -webkit-transform 0.3s cubic-bezier(0.78, 0.14, 0.15, 0.86);
          -webkit-font-feature-settings: "tnum";
          font-feature-settings: "tnum";
        }

        .ant-spin-spinning {
          position: static;
          display: inline-block;
          opacity: 1;
        }

        .ant-spin-dot {
          position: relative;
          display: inline-block;
          width: 20px;
          height: 20px;
          font-size: 20px;
        }

        .ant-spin-dot-item {
          position: absolute;
          display: block;
          width: 9px;
          height: 9px;
          background-color: #1890ff;
          border-radius: 100%;
          -webkit-transform: scale(0.75);
          -ms-transform: scale(0.75);
          transform: scale(0.75);
          -webkit-transform-origin: 50% 50%;
          -ms-transform-origin: 50% 50%;
          transform-origin: 50% 50%;
          opacity: 0.3;
          -webkit-animation: antspinmove 1s infinite linear alternate;
          animation: antSpinMove 1s infinite linear alternate;
        }

        .ant-spin-dot-item:nth-child(1) {
          top: 0;
          left: 0;
        }

        .ant-spin-dot-item:nth-child(2) {
          top: 0;
          right: 0;
          -webkit-animation-delay: 0.4s;
          animation-delay: 0.4s;
        }

        .ant-spin-dot-item:nth-child(3) {
          right: 0;
          bottom: 0;
          -webkit-animation-delay: 0.8s;
          animation-delay: 0.8s;
        }

        .ant-spin-dot-item:nth-child(4) {
          bottom: 0;
          left: 0;
          -webkit-animation-delay: 1.2s;
          animation-delay: 1.2s;
        }

        .ant-spin-dot-spin {
          -webkit-transform: rotate(45deg);
          -ms-transform: rotate(45deg);
          transform: rotate(45deg);
          -webkit-animation: antrotate 1.2s infinite linear;
          animation: antRotate 1.2s infinite linear;
        }

        .ant-spin-lg .ant-spin-dot {
          width: 32px;
          height: 32px;
          font-size: 32px;
        }

        .ant-spin-lg .ant-spin-dot i {
          width: 14px;
          height: 14px;
        }

        @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
          .ant-spin-blur {
            background: #fff;
            opacity: 0.5;
          }
        }

        @-webkit-keyframes antSpinMove {
          to {
            opacity: 1;
          }
        }

        @keyframes antSpinMove {
          to {
            opacity: 1;
          }
        }

        @-webkit-keyframes antRotate {
          to {
            -webkit-transform: rotate(405deg);
            transform: rotate(405deg);
          }
        }

        @keyframes antRotate {
          to {
            -webkit-transform: rotate(405deg);
            transform: rotate(405deg);
          }
        }
      </style>

      <div style="
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100%;
        min-height: 362px;
      ">
        <div class="page-loading-warp">
          <div class="ant-spin ant-spin-lg ant-spin-spinning">
            <span class="ant-spin-dot ant-spin-dot-spin">
              <i class="ant-spin-dot-item"></i>
              <i class="ant-spin-dot-item"></i>
              <i class="ant-spin-dot-item"></i>
              <i class="ant-spin-dot-item"></i>
            </span>
          </div>
        </div>
        <div class="loading-title">
          正在加载资源
        </div>
        <div class="loading-sub-title">
          初次加载资源可能需要较多时间 请耐心等待
        </div>
      </div>`,
    ]);
    return $;
  });
};`
[https://github.com/umijs/umi/issues/8442#issuecomment-1176960539](url)参考了这个

**Comment by echoyl** [comment]
在antdesign pro项目里面添加plugin.ts 文件，但是没有作用。请问下还有哪里需要配置下

**Comment by ali-upgrade** [comment]
在根目录添加plugin.ts文件的情况下，在开发环境chrome控制台的产物中查看是否添加成功
![image](https://github.com/user-attachments/assets/f3a115ce-03a0-42cc-b0a6-1b50da998272)

**Comment by echoyl** [comment]
> > 在antdesign pro项目里面添加plugin.ts 文件，但是没有作用。请问下还有哪里需要配置下
> 
> 请问这个问题解决了吗？

修改产物index.html 把loading.js 放到 body中的root后面 umi.js的前面
