### ISSUE TITLE
🐛 [BUG] 多语言，默认指定英文 en-us ，项目启动后还是中文

### ISSUE THREAD

**Issue by mmzzli** [ant-design/ant-design-pro#11317]
### 🐛 bug 描述

多语言，默认指定英文 en-us ，项目启动后还是中文，localstorage 中的 key 已经删除，默认还是中文。
### 📷 复现步骤 | Recurrence steps
通过 pro create xxx 创建的项目，把 config.ts 中的 Locale 的 default 修改为 en-US.

![telegram-cloud-photo-size-1-5055726444050754967-y](https://github.com/user-attachments/assets/8256a2b7-fadf-4e04-b653-c03b56cb7fee)

### 🏞 期望结果 | Expected results
期望默认是英文，打开就是英文

期望默认是英文
![image](https://github.com/user-attachments/assets/d7657a1b-15d5-4a1d-be68-015b2edb86a6)

### 💻 复现代码 | Recurrence code

https://github.com/mmzzli/test-umi-pro

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4
 "@ant-design/pro-components": "^2.6.48",
    "@umijs/route-utils": "^2.2.2",
    "antd": "^5.13.2",
- umi 版本 
    "@umijs/max": "^4.1.1",
- 浏览器环境
![image](https://github.com/user-attachments/assets/0e6d14d5-3c4b-4abc-acd1-d755c3b10cd2)
- 开发环境 [e.g. mac OS]
![image](https://github.com/user-attachments/assets/81e341a3-d02d-473a-a3fc-2a0f5957feac)

**Comment by nathanlao** [comment]
Could try using  [ConfigProvider](https://ant.design/components/config-provider) in antd to provide Internationalization configuration to your React components, exmaple usage:

```javascript
import { ConfigProvider, enUSIntl } from '@ant-design/pro-table';

<ConfigProvider value={{ intl: enUSIntl }}>
	<YourReactComponent>
</ConfigProvider>
```

**Comment by xyovo** [comment]
我觉得应该是因为你浏览器是中文语言，你可以试试把`baseNavigator`配置改为`false`，这样`default`应该会生效
https://umijs.org/docs/max/i18n#%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6
![image](https://github.com/user-attachments/assets/30f87ba7-ddbe-4b31-9c41-401709142271)
