### ISSUE TITLE
🧐[问题 | question] 官方文档真是忒么的一坨大便

### ISSUE THREAD

**Issue by silengzi** [ant-design/ant-design-pro#11337]
### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by xyovo** [comment]
能不能文明一些？本来就是开源项目，不喜欢可以不用，自己去从0搭一个框架。请尊重开源项目

**Comment by silengzi** [comment]
> 能不能文明一些？本来就是开源项目，不喜欢可以不用，自己去从0搭一个框架。请尊重开源项目

跟是不是开源项目没关系，我就问你这文档能用吗，看了半天基本都是错的，不喜欢可以不用，你要是看不爽也可以不看，尊重开源项目，但文档写的这么烂就是要说
