### ISSUE TITLE
希望在antdpro中通过拖拽实现手动排序功能，不知antd是否已有解决方案或最佳实践？

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/ant-design-pro#1135]
希望在antdpro中通过拖拽实现手动排序功能，不知antd是否已有解决方案或最佳实践？
如果没有，我想集成使用react-dnd但不知如何下手。

**Comment by chenshuai2144** [comment]
还没有需要自己写了 
只是手动排序难度不是很大

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#components-table-demo-drag-sorting
看看这个
