### ISSUE TITLE
希望 <顶部搜索框> 组件能暴露出默认打开的配置

### ISSUE THREAD

**Issue by zhujun24** [ant-design/ant-design-pro#1136]
目前的 <顶部搜索框> 组件是默认关闭的，需要点击搜索 icon 才能打开输入框，看了源码，该组件内部 state 的 searchMode 属性默认为 false，外部不可配置这个参数，内部 click 事件触发 enterSearchMode 方法改变 searchMode，所以希望能在 props 里传递这个参数，优雅的实现默认打开。

**Comment by ddcat1115** [comment]
欢迎 pr~

**Comment by zhujun24** [comment]
最好还能有一个常开的输入框，这个可配置就更好了，有空pr~
