### ISSUE TITLE
图表组件canvas的width计算错误，超出了父组件Col定义的width

### ISSUE THREAD

**Issue by Sayi** [ant-design/ant-design-pro#1137]
![image](https://user-images.githubusercontent.com/1394854/37641662-9b604710-2c55-11e8-9ff0-29fbb887f740.png)

如图，图表组件右侧部分显示不了，无法显示12月份。当我把左侧导航菜单收起再重新打开的时候，显示一切正常。
其中父组件(父组件改成Card元素，也会超出)样式宽度：
![image](https://user-images.githubusercontent.com/1394854/37641798-05c12b38-2c56-11e8-9247-de4483af6db6.png)

图表组件宽度：
![image](https://user-images.githubusercontent.com/1394854/37641808-10c1734e-2c56-11e8-9a66-a50d3be365cf.png)

代码如下，我是把workspace.js的渲染改成了如下代码：
```javascript
return (
      <PageHeaderLayout
        content={pageHeaderContent}
        extraContent={extraContent2}
      >
        <Row>
          <Col xl={24} lg={24} md={24} sm={24} xs={24}>
            <div className={styles.salesBar}>
              <Bar height={400} title="销售额趋势" data={salesData} />
            </div>
          </Col>
        </Row>
```
浏览器版本 65.0.3325.162（正式版本） （64 位），试了很多分辨率都显示不了右侧部分。我猜可能是计算宽度的时候是不是计算了左侧导航的宽度？？？

期待回答。

**Comment by ddcat1115** [comment]
应该跟这个类似 https://github.com/ant-design/ant-design-pro/issues/720

**Comment by Sayi** [comment]
谢谢，是一个问题。没有用关键词搜索到另一个问题。。
