### ISSUE TITLE
路由参数修改参数不会重新刷新页面

### ISSUE THREAD

**Issue by Sayi** [ant-design/ant-design-pro#1138]
router.js配置带参数的路由：
```javascript
'/account/info/:id': {
  component: dynamicWrapper(app, ['user'], () => import('../routes/Account')),
},
```
浏览器访问，http://localhost:8000/#/account/info/ada1，一切正常。
但是：
1. 当我手动修改浏览器的url，把ada1改成其它其它用户id，比如ada2，然后键盘Enter，页面并不刷新。

2. 问题1对用户倒可以接受，但是如果我在/#/account/info/ada1页面内，正好有个链接，是/#/account/info/ada2，点击这个链接，页面也并不刷新，但是url会修改成/#/account/info/ada2.
备注：浏览器Network上也看不到发送任何获取ada2数据的网络请求，应该是页面没刷新。
其中页面内跳转ada2的代码如下：
```javascript
const url = `/account/info/${currentUser.id}`;
this.props.dispatch(routerRedux.push(url));
```
 期待回复。

**Comment by chenshuai2144** [comment]
`componentWillReceiveProps`？

**Comment by Sayi** [comment]
@chenshuai2144 感谢提醒，问题1和2重写componentWillReceiveProps即可。
```javascript
  componentWillReceiveProps(nextProps) {
    const { dispatch, match } = this.props;
    if (nextProps.match.params.id && match.params.id !== nextProps.match.params.id) {
      dispatch({
        type: 'user/fetchUser',
        payload: {
          id: nextProps.match.params.id,
        },
      });
    }
  }
```

**Comment by yoyo837** [comment]
写个redirect中间页来replace回来如何？
