### ISSUE TITLE
"npm run build" have some error on centos7 

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design-pro#1140]
> ant-design-pro@1.1.0 build /home/appadmin/paydayloanapp-frontal
> cross-env ESLINT=none roadhog build

Failed to compile.

Module not found: Error: Can't resolve 'components/StandardFormRow' in '/home/appadmin/paydayloanapp-frontal/src/routes/List'

[graceful-process#33796] exit with code:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.1.0 build: `cross-env ESLINT=none roadhog build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/appadmin/.npm/_logs/2018-03-21T06_52_20_765Z-debug.log

**Comment by chenshuai2144** [comment]
看起来像是 alias 的问题。
你升级一下你的 roadhog 版本
