### ISSUE TITLE
Dangerous property 'dangerouslySetInnerHTML' found

### ISSUE THREAD

**Issue by andy1247008998** [ant-design/ant-design-pro#1142]
src/components/Charts/ChartCard/index.js
14:48  warning  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger

**Comment by chenshuai2144** [comment]
@nikogu   为什么要这么写呢？ 我发现了好几个

**Comment by nikogu** [comment]
@chenshuai2144 需要展示特殊字符啊...这个是 warning 不是 error，就是开发者自己要注意，你如果用不到特殊字符，你就可以改成直接显示的方式。

https://github.com/ant-design/ant-design-pro/blob/master/src/routes/Dashboard/Analysis.js#L255
https://github.com/ant-design/ant-design-pro/blob/master/src/components/Charts/ChartCard/index.js#L14

**Comment by afc163** [comment]
组件里最好不要用 dangerouslySetInnerHTML，有安全风险。

**Comment by nikogu** [comment]
倒是从来没遇到过什么安全问题，执行标签如 `script` 即使在 `dangerouslySetInnerHTML ` 也并没有什么作用。

抽离出来，交给用户自己决定好了。
