### ISSUE TITLE
侧边栏收起后，侧边栏的定制icon与title发生冲突

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design-pro#1143]
1.侧边栏收起后，title应该隐藏
![image](https://user-images.githubusercontent.com/28672197/37699213-794b7ae2-2d21-11e8-976d-2092065391d5.png)
2.tooltip应该只展示title而不展示icon
![image](https://user-images.githubusercontent.com/28672197/37699229-897a0320-2d21-11e8-8d45-b745b2819a75.png)
要如何解决？

**Comment by chenshuai2144** [comment]
用span标签包起来title 就可以隐藏了。

![image](https://user-images.githubusercontent.com/8186664/37700043-0b0f8b1e-2d25-11e8-8eb0-8ad8ca2ad870.png)

**Comment by chenshuai2144** [comment]
show code 让我看看

**Comment by yupeilin123** [comment]
定制的icon（选择器不同）不能把title隐藏吧？。
