### ISSUE TITLE
更新之后脚手架明显变慢的问题

### ISSUE THREAD

**Issue by liumin1128** [ant-design/ant-design-pro#1144]
脚手架的反应很慢，编译如果出错，哪怕代码立刻纠正了，页面也需要等很久才能刷新出来，这个速度明显比之前要慢。编译结果是否使用了存缓，请问如何关闭或清空存缓，因为经常会一直使用上一次错误的编译结果，哪怕代码已经改正（不同于上面的是，这种情况即使重开进程也依然报错）。重现方法：在index.js里引用一个不存在的modal。

**Comment by xiaolongyuan** [comment]
是的 我的也很慢  xps 9560顶配

**Comment by lyingd** [comment]
相同问题，之前用roadhog1.3，后来roadhog升级为2.3之后，速度骤降，编译速度能差10倍

**Comment by liumin1128** [comment]
看到大家都很慢，我的mbp保住了

**Comment by lyingd** [comment]
我的是联想T450s，非常慢，mbp倒是神速……

**Comment by chenkang084** [comment]
window是有些慢，不过，在linux上面，速度还可以

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/issues/552

**Comment by tuihou123321** [comment]
很慢，而且经常报：FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 错误

**Comment by jogasa** [comment]
经常只是引用文件路径问题，然后服务就崩了，也没指出哪里出错，一脸问号…… 而且速度奇慢无比，重新启动服务又要等很久
