### ISSUE TITLE
列表页点击某列跳转到详情页

### ISSUE THREAD

**Issue by huchlo** [ant-design/ant-design-pro#1147]
如题，这过程是怎么传值的...或者说是怎么实现的...

官网的示例网页没看到例子...

![image](https://user-images.githubusercontent.com/30746406/37712277-58c1a94a-2d4e-11e8-9ce4-cedb42fa38cc.png)

**Comment by chenshuai2144** [comment]
Url传参比较合适

**Comment by huchlo** [comment]
https://127.0.0.1:8000/#/profile/basic?id=123456；这样传吗？又怎么取id的值喃

**Comment by huchlo** [comment]
@chenshuai2144 最好有代码例子么- -！

**Comment by chenshuai2144** [comment]
https://reacttraining.com/react-router/web/example/url-params 
尽量不要问常识性问题！

**Comment by 533001** [comment]
修改要去其他页面么? 不应该是在本页面完成么? 
比如 弹框/或者 编辑table 的这两种方式么?
