### ISSUE TITLE
调试无法开启css sourcemap

### ISSUE THREAD

**Issue by happier2** [ant-design/ant-design-pro#1150]
下载最新的ant-design-pro，npm install && npm start后，使用chrome devtools查看元素样式，样式都是<style>样式，没有开启css sourcemap。
查看roadhog配置文件，提到使用`disableCSSSourceMap: false`配置，可以开启css sourcemap，加入新的配置到.webpackrc，重新npm start后，还是无法开启css sourcemap。

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/pull/463
