### ISSUE TITLE
路由问题，求指教

### ISSUE THREAD

**Issue by karakiel** [ant-design/ant-design-pro#1151]
`<Switch>
          <Route
            path="/user"
            component={UserLayout}
          />
          <AuthorizedRoute
            path="/"
            render={props => <BasicLayout {...props} />}
            authority={['admin', 'user']}
            redirectPath="/user/login"
          />
        </Switch>`
路由选择的应该是/user吧，那为什么没先加载{UserLayout}，这块实在是不明白，这个到底是怎么个过程，新手耽误大家点时间求指教

**Comment by chenshuai2144** [comment]
重定向？

**Comment by karakiel** [comment]
src下面的route.js里面的，我看不懂这个路由的怎么选择的

**Comment by ddcat1115** [comment]
只有当 location.path 为 `/user(/xxx)` 的时候才能进 UserLayout，其他 `/(xxx)` 都进 BasicLayout，没问题啊

**Comment by karakiel** [comment]
这块还是看不懂，我自己慢慢学习吧，谢谢你们的回复
