### ISSUE TITLE
为何Ant-Design-Pro的Form，必填域没有label的星号提示呢？

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design-pro#1152]
如图，在Ant-Design-Pro（3.1.0）是没有星号提示，但是在Ant-Design（3.3.0）就有，不太明白为啥会这样，添加hideRequiredMark为false也无效，求解答，谢谢！

![image](https://user-images.githubusercontent.com/24793529/37753976-7a572ef4-2dda-11e8-91eb-1bb636c5ea9e.png)

**Comment by chenshuai2144** [comment]
Ant design有这个属性配置

**Comment by LaiHuanMin** [comment]
好吧，刚刚没看仔细，不好意思
