### ISSUE TITLE
TimelineChart 数值显示位置有误

### ISSUE THREAD

**Issue by codercatmomi** [ant-design/ant-design-pro#1153]
https://pro.ant.design/components/Charts-cn/

![image](https://user-images.githubusercontent.com/8371019/37755851-21d9cb44-2de2-11e8-9656-b331e7b877c2.png)

官网的例子中，
X轴刻度中的20：03  和 tooltip中的20：03  位置存在明显的偏差

请问如何修复呢

**Comment by nikogu** [comment]
https://github.com/antvis/data-set/issues/27

g2 那边的 date-set 会在四月重构，会修复这个问题

**Comment by codercatmomi** [comment]
好的 感谢
