### ISSUE TITLE
在 .roadhog.rc.js 中配置服务端代理，无法处理 post 请求

### ISSUE THREAD

**Issue by xiezhenye** [ant-design/ant-design-pro#1154]
在 .roadhog.rc.js 中配置服务端代理，无法处理 post 请求。
GET 请求能正常代理，POST 请求都 404 

试过 

'/api/sys/(.*)': 'http://127.0.0.1:8080/api/sys/',

'POST /api/sys/(.*)': 'http://127.0.0.1:8080/api/sys/',

都不行

**Comment by GoatherdNaN** [comment]
在 .webpackrc.js 中配置了proxy后，就无法在npm start时使用mock了啊，要啷个整？
