### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by fyuncn** [ant-design/ant-design-pro#1157]
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.

npm ERR! Unexpected end of JSON input while parsing near '...s":"^14.2.2-alpha.22b'

最新版的有问题啊

**Comment by fyuncn** [comment]
get clone 后，npm install装载直接报错，以下是log：
silly fetchPackageMetaData error for jest-resolve@^22.4.3 Unexpected end of JSON input while parsing near '...s":"^14.2.2-alpha.22b'
请问下该如何解决呢？

**Comment by afc163** [comment]
你的网络有问题，建议使用 cnpm。
