### ISSUE TITLE
关于全局数据的问题

### ISSUE THREAD

**Issue by saipanno** [ant-design/ant-design-pro#1158]
在项目中碰到一个需求，有些基本不变的数据希望用户加载页面时 load 一次后在多个页面可以公用，不再每次重新加载，除非用户刷新页面

看代码有一个 global 的 model，以为这里定义的都是全局可用的，但发现后来这里的方法还是在各个组件里通过 dispatch 调用的，

由于前端了解的不多，还请帮忙解惑，谢谢

**Comment by chenshuai2144** [comment]
redux 了解一下
