### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by chengnuo** [ant-design/ant-design-pro#116]
截了图，不会发。 
command+r（刷新）的时候，第二三秒左右的时候，会出现css样式加载不过来（白屏）。然后又可以了。但是官网的demo没有白屏的问题，是我召唤问题吗？

**Comment by dxhuii** [comment]
这个是开发的时候吧，因为CSS要等JS加载完才能加载CSS，正式打包的话，会把CSS和JS分开打包，就不会有这样的情况了，演示站，是因为已经是打包后的代码。

**Comment by chengnuo** [comment]
@dxhuii 谢谢回答我压压惊。

**Comment by nikogu** [comment]
track: https://github.com/dvajs/dva/issues/1300

开发环境注意下就好，不会影响线上的
