### ISSUE TITLE
roadhogrc.mock.js拆分

### ISSUE THREAD

**Issue by machao95** [ant-design/ant-design-pro#1161]
我想将roadhogrc.mock.js拆分成多个文件A,B,C,在roadhogrc.mock.js中使用Object.assign合并， 但在拆分出的ABC文件中无法使用 import。。。

SyntaxError: Unexpected token import

**Comment by kunhour** [comment]
使用展开运算符

**Comment by MorisHarA** [comment]
我的可以的啊
