### ISSUE TITLE
关于package.json的作者栏位

### ISSUE THREAD

**Issue by finch185277** [ant-design/ant-design-pro#1163]
Hi @ant-design 大大们您好，
我是 [CDNJS](https://github.com/cdnjs/cdnjs) 的成员之一，我们想要收录这个 library 到 CDNJS 中。
CDNJS 是一个前端的资源库，我们目前已经收录了 3327 个 library ，这数字还会再持续成长中。

收录这个 library需要package.json来自动更新，
但因为GitHub提供的[package.json](https://github.com/ant-design/ant-design-pro/blob/master/package.json)作者栏是空的，
纠结了很久之后
于是在此透过issue来询问各位大大意愿如何?

若以上有不妥之处，还请您见谅。
期待您的回覆。
谢谢！

cdnjs/cdnjs#12548
cdnjs/cdnjs#12577

**Comment by chenshuai2144** [comment]
@afc163

**Comment by finch185277** [comment]
Thanks!
