### ISSUE TITLE
怎么直接在项目中启动访问  http://dev-xxx.xxx.com 替代 localhost:8000

### ISSUE THREAD

**Issue by mrandpz** [ant-design/ant-design-pro#1165]
怎么修改环境变量

**Comment by mrandpz** [comment]
启动成功的时候会出现
`You can now view Your App in the browser.
 Local:            http://localhost:8000/`

我想把这个localhost:8000 修改成自己想要的域名和端口

**Comment by mrandpz** [comment]
修改好了。谢谢！在npm run start的时候加上HOST 和 PORT 就好了，有其他办法可以告知下哈。

**Comment by chenkang084** [comment]
@mrandpz 直接通过自己的ip+host就可以实现，无需任何配置，因为，默认监听的是127.0.0.1

**Comment by xiaodin1** [comment]
> 修改好了。谢谢！在npm run start的时候加上HOST 和 PORT 就好了，有其他办法可以告知下哈。

HOST=0.0.0.0 npm start
or
HOST=0.0.0.0 yarn start
