### ISSUE TITLE
setDefaultLoadingComponent这个问题，loading在哪里修改，原有dva-loading修改配置获取loading方式不能获取

### ISSUE THREAD

**Issue by lettywiterock** [ant-design/ant-design-pro#1166]
你好，请教一下，dva-loading的修改和获取方式在pro里面，怎么进行调用实现？
组件传值发现没有loading参数。
感谢。

**Comment by ddcat1115** [comment]
setDefaultLoadingComponent?

https://github.com/ant-design/ant-design-pro/blob/master/src/router.js#L12

https://github.com/dvajs/dva/issues/1332
