### ISSUE TITLE
Hash route parameter reservation

### ISSUE THREAD

**Issue by wujingacross** [ant-design/ant-design-pro#1167]
Hash routing page form submission, and paging page refresh problem, how to retain the request parameters.
e.g.:
The page list is paged, refreshes on the second page, and remains on the second page after the refresh is desired.

**Comment by wujingacross** [comment]
Before using browser routing, you can use:
dispatch(routerRedux.push({
        pathname: '/template',
        state: values,
}));
But after changing the hash route, it will warn:
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack
So can't use route jump

**Comment by ddcat1115** [comment]
try `routerRedux.replace`

https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward

**Comment by wujingacross** [comment]
Thank you, this can indeed be a request within the page, but using routerRedux.replace (location), when the page is refreshed, there is no state value in the location.

**Comment by ddcat1115** [comment]
Data in the state can not be reserved after refresh, maybe you can choose `search`, to pass the parameter through url.

https://github.com/ReactTraining/history/blob/v3/docs/Location.md#location

**Comment by wujingacross** [comment]
However, when the Browser routing, the value of state in routerRedux.push(location) still exists after the refresh. Do you not know why the hash route was changed?

**Comment by ddcat1115** [comment]
Don't quite understand what you mean. In general, if you want to reserve a value after refreshing, you can use `search` to pass the parameter, if not, just `state` is ok.

**Comment by wujingacross** [comment]
OK, thank you, I know. I meant that I used browser routing before. I saved the data in location.state during the switch, and it still existed after the refresh, but now I changed to hash routing. Use the route to replace and refresh the page. The data stored in location.state does not exist.
