### ISSUE TITLE
disableDynamicImport为false的时候，request401的时候，先跳入bashboard界面，再到login界面

### ISSUE THREAD

**Issue by chenkang084** [ant-design/ant-design-pro#1168]
问题重现条件：
1.**webpackrc.js**中，设置`disableDynamicImport: false`，从而实现按需异步加载；  
2.将https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/Authorized.js#L8 处设置为request 请求后台的api，查看当前状态是否登陆，如果没有登陆，返回401；

原因分析：
由于`disableDynamicImport: false`，为按需加载，如果直接访问`/`，先加载`PromiseRender`，出现loading的小圆圈，返回401，然后执行[dispatch](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js#L80)，按需加载，其实现在login的model没有被加载，执行dispatch -->login/logout是不生效的，且当前promise返回的是resolved，所以会执行到[then内的方法](https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/PromiseRender.js#L21)，当前target其实就是[BasicLayout](https://github.com/ant-design/ant-design-pro/blob/master/src/router.js#L30:31)，所以回先跳转到dashboard，然后，稍后会执行dispatch logout。

修改建议(方法有2种)：
1.在[index.js](https://github.com/ant-design/ant-design-pro/blob/master/src/index.js#L22)中始终加载models/login，dispatch是异步的，可能还会有问题，不推荐。
2.在request的最后，继续抛出error，在PromiseRender中，就会进入catch方法，这样既符合逻辑，也解决了上述问题，如果思路正确，我可以提供pull request

**Comment by chenshuai2144** [comment]
抛出error 开发起来会很蛋疼的，每个请求都有 try catch 一下

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/v2/src/layouts/LoadingPage.js
我觉得这种的解决办法比较好

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/v2/src/layouts/LoadingPage.js
我觉得这种的解决办法比较好

**Comment by chenkang084** [comment]
@chenshuai2144 这个方式也是可以的。但是，我还是认为直接`throw e`比较好，因为，本来就是reject，现在变为resolved了不太符合流程。其次，这个地方`throw e`并不是每个地方都需要catch的，因为，在request的catch里面，都执行了dispatch，所以，不会有问题。我目前使用良好。
这个问题可以先hold住，观察一段时间看看也行。

**Comment by chenshuai2144** [comment]
我记得有个蛮难受的事情来着 等我试一试.再来看看 throw error 更符合流程一点

**Comment by WuJiY** [comment]
最终怎么解决的，lodingpage吗？

**Comment by chenshuai2144** [comment]
lodingpage 比较简单一些

**Comment by WuJiY** [comment]
如果登录失效的情况下，还是会出现错误

**Comment by chenshuai2144** [comment]
v2将解决

**Comment by huangshunping** [comment]
@chenshuai2144 v2依然有这个问题，因为按需加载，dispatch logout没有效果
