### ISSUE TITLE
引入PageHeader报错

### ISSUE THREAD

**Issue by xaasu** [ant-design/ant-design-pro#1169]
错误信息:
/node_modules/_ant-design-pro@1.2.0@ant-design-pro/lib/PageHeader/index.js
Module not found: Can't resolve '../utils/pathTools' in '%PATH%\node_modules\_ant-design-pro@1.2.0@ant-design-pro\lib\PageHeader'****，

查看node_modules目录下ant-design-pro/lib/PageHeader目录第44行
var _pathTools = require('../utils/pathTools');

但是未在lib目录下发现utils文件夹，不知道是否是这个问题。该如何解决？

独立使用pro组件和直接引入pro组件文件目录对比图：
![image](https://user-images.githubusercontent.com/24312839/37904014-cc682f5e-312c-11e8-9d26-4f5b1ee521e3.png)
![image](https://user-images.githubusercontent.com/24312839/37904022-d5a98dba-312c-11e8-8383-cd709d7dc87a.png)

**Comment by ddcat1115** [comment]
utils 没打进去，@nikogu 看看呢

**Comment by nikogu** [comment]
应该是这里没加 https://github.com/ant-design/ant-design-pro-site/blob/master/config/components/components.config.js

导致包没打进去， @chenshuai2144

**Comment by chenshuai2144** [comment]
fixed
`npm install ant-design-pro@1.2.1`
