### ISSUE TITLE
独立使用ant-desigin-pro需要把antd更新到哪个版本

### ISSUE THREAD

**Issue by SecretCastle** [ant-design/ant-design-pro#117]
我的依赖
```json
"ant-design-pro": "^0.2.2-rc.1",
"antd": "^2.13.9",
```

使用官方给的例子`Charts`报错

<img width="800" alt="qq20171106-171152 2x" src="https://user-images.githubusercontent.com/12498143/32433357-a3d64628-c315-11e7-8cdf-2c521f4cf6dd.png">

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq#%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Ant-Design-Pro%EF%BC%9F
