### ISSUE TITLE
antd-pro 编译过程报错

### ISSUE THREAD

**Issue by sven0726** [ant-design/ant-design-pro#1171]
![image](https://user-images.githubusercontent.com/4318521/37916952-c07b851a-314f-11e8-9602-a2e92c5bbc02.png)

看了相关issue，感觉还是没有解决。尝试着定位，发现都是引用的代码。无从下手

**Comment by chenshuai2144** [comment]
这个一般是你引用的库的问题，有些库发布的时候没有编译。
换一个库吧

**Comment by chenshuai2144** [comment]
#1082

**Comment by sven0726** [comment]
引用的是ali-oss。 我通过下面配置避免了编译问题：

 "extraBabelIncludes":["./node_modules/ali-oss"],

**Comment by mineMineGo** [comment]
同样的错误，你怎么解决的
