### ISSUE TITLE
还有很多文件需要perttier来格式化

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#1178]
vscode相关的文件是否要提交上来？
![qq 20180327154314](https://user-images.githubusercontent.com/18542211/37953481-943ee9d4-31d5-11e8-833c-e9109d40e008.png)

**Comment by kaoding** [comment]
mock\geographic\city.json

**Comment by chenshuai2144** [comment]
ant-design-pro\src\layouts\Footer.js
ant-design-pro\src\layouts\Header.js
这个是2.0的

**Comment by kaoding** [comment]
1. vscode我是觉得不要提交上来，我看你提交了
2. 既然用了perttier格式化，我认为mock数据代码风格也应该保持一致比较好

**Comment by chenshuai2144** [comment]
看到了  我的忽略跪了

**Comment by kaoding** [comment]
使用npm install时会修改package.json，使用yarn install就不会，针对格式化，这个要怎么处理？还是就这样？

**Comment by chenshuai2144** [comment]
尊重一下 npm 自己吧！
好久没用 npm 了，竟然做了个这
