### ISSUE TITLE
npm start:no-proxy 不可用

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#1181]
`npm start`  是可以的， `npm start:no-proxy` 提示命令不存在。

> Usage: npm <command>
> 
> where <command> is one of:
>     access, adduser, bin, bugs, c, cache, completion, config,
>     ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
>     explore, get, help, help-search, i, init, install,
>     install-test, it, link, list, ln, login, logout, ls,
>     outdated, owner, pack, ping, prefix, profile, prune,
>     publish, rb, rebuild, repo, restart, root, run, run-script,
>     s, se, search, set, shrinkwrap, star, stars, start, stop, t,
>     team, test, token, tst, un, uninstall, unpublish, unstar,
>     up, update, v, version, view, whoami
> 
> npm <command> -h     quick help on <command>
> npm -l           display full usage info
> npm help <term>  search for help on <term>
> npm help npm     involved overview
> 
> Specify configs in the ini-formatted file:
>     /Users/admin/.npmrc
> or on the command line via: npm <command> --key value
> Config info can be viewed via: npm help config
> 
> npm@5.6.0 /usr/local/lib/node_modules/npm

**Comment by yutingzhao1991** [comment]
`npm run xxx` 只有 start 和 test 不需要 run

**Comment by MEEllis** [comment]
npm run start:no-proxy
