### ISSUE TITLE
Mac 运行项目

### ISSUE THREAD

**Issue by packjie** [ant-design/ant-design-pro#1183]
mac运行项目报错，cross-env的问题，如何解决呀？

**Comment by chenshuai2144** [comment]
详细的截图？

**Comment by packjie** [comment]
我将cross 插件去掉了，然后运行还是报错
./src/index.js
Module build failed: Error: Cannot find module 'eslint-config-prettier'
Referenced from: /Users/suiyingjie/Desktop/work/demo/pro-demo/ant-design-pro-master/.eslintrc
    at Array.reduceRight (<anonymous>)

**Comment by chenshuai2144** [comment]
重新安装一下包。

**Comment by packjie** [comment]
重新安装了之后
Module build failed: Error: Cannot find module 'babel-plugin-transform-decorators-legacy' from '/Users/suiyingjie/Desktop/work/demo/pro-demo/my-project/test2'
    at Array.map (<anonymous>)
这歌插件我也安装了但还是报错

**Comment by packjie** [comment]
使用了yarn，也将node_modules删除了，到那时问题还是存在，有没有遇到过相同问题的？

**Comment by chenshuai2144** [comment]
这都是很基础的包。。。。

应该依赖的时候自己打进去了。 换源了吗？

**Comment by packjie** [comment]
找到问题了，原因是本地环境变量的问题，导致了package.json中的devDependencies全部没有加载，执行了npm install --dev之后就可以运行了

**Comment by binghaiwang** [comment]
执行了npm install --dev 这种方式还是启动不了  一直卡住不动
