### ISSUE TITLE
进入框架加载数据

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#1184]
现在需要进入框架时，给下拉框加载数据源，因为这些数据其他页面也可能用到，所以保存在 global 的 model中。
问题model这些数据是异步的，当我进入这些页面，会先拿这些数据中的某项作为参数查相应的API，有时候会取不到。
有什么方法可以等数据源加载完，在加载具体的页面，谢谢。

**Comment by quaider** [comment]
这些数据存入redux即可
