### ISSUE TITLE
Bug: Gauge Chart cannot detect width properly.

### ISSUE THREAD

**Issue by imakou** [ant-design/ant-design-pro#1186]
Hi,

Just struggled this problem for a morning.
Initially, Gauge Chart always detect more width than current parent's container.

So that, it causes the chart cannot be centered by default.
PS: I just call the ```{Gauge}``` individually from antd-pro and use it on my project which is base on antd.
![screen shot 2018-03-27 at 2 43 21 pm](https://user-images.githubusercontent.com/1507950/37987873-667dcec8-31cd-11e8-8258-f4fd2b64e3cb.png)

There is my example code:

```javascript
        <Content>
          <Row>
            <Col span={24}>
              <Card bodyStyle={{ padding: 0 }}>
                <Gauge title="核销率" height={164} percent={87} />
              </Card>
            </Col>
          </Row>
          <Row>
            <Col span={24}>
              <div style={{ textAlign: "center" }}>
                <WaterWave height={161} title="补贴资金剩余" percent={34} />
              </div>
            </Col>
          </Row>
        </Content>
```

ENV:

ANTD:3.3.3,
ANTD-PRO: 1.2.0.

**Comment by ddcat1115** [comment]
duplicate #858 #720
