### ISSUE TITLE
更新最新版本1.2.1，在触发401的时候，报错了

### ISSUE THREAD

**Issue by litcto** [ant-design/ant-design-pro#1188]
![image](https://user-images.githubusercontent.com/6800277/38007100-5475912c-327a-11e8-8bb5-e30da0894c31.png)

**Comment by 290352095** [comment]
把那个triggerResizeEvent  的函数 定义的位置改成 es5的写法试试

**Comment by chenshuai2144** [comment]
我今天早上也碰见了。。。
感觉像是什么库更新 改了 api 了

**Comment by chenshuai2144** [comment]
fixed  因为 eslint 报错，加了个箭头函数
注解不支持箭头函数 所以报错了

**Comment by chenshuai2144** [comment]
箭头函数比较麻烦。规范里面没有说要支持。
可以用@Bind 注解 解决问题
