### ISSUE TITLE
使用脚手架退出登录后出现错误

### ISSUE THREAD

**Issue by eoeac** [ant-design/ant-design-pro#1189]
TypeError: this.triggerResizeEvent.cancel is not a function. (In 'this.triggerResizeEvent.cancel()', 'this.triggerResizeEvent.cancel' is undefined)

componentWillUnmount
src/components/GlobalHeader/index.js:13

export default class GlobalHeader extends PureComponent {
  12 |   componentWillUnmount() {
> 13 |     this.triggerResizeEvent.cancel();
  14 |   }
  15 |   getNoticeData() {
  16 |     const { notices = [] } = this.props;

**Comment by 290352095** [comment]
我也刚准备提交这个错误  不过发现了解决办法   在triggerResizeEvent 这个函数那里 不要用箭头函数 改为es5的函数写法就可以成功退出了

**Comment by ddcat1115** [comment]
duplicate #1188
