### ISSUE TITLE
Mac初始化项目

### ISSUE THREAD

**Issue by beyondonly** [ant-design/ant-design-pro#1191]
1、不管通过Git下载还是通过cli脚手架初始化，启动访问会出现下面问题
![image](https://user-images.githubusercontent.com/5237702/38014387-35e824ec-329b-11e8-97fd-13ddc17ed0c3.png)
2、通过Cli脚手架，会出现包不完整，使用环境是MAc

**Comment by chenshuai2144** [comment]
是不是网络问题。。
最近这种事情好多呀！

**Comment by beyondonly** [comment]
我用Windows是可以的，同样的网络 Mac 我两种方式都不行 cli方式是缺少包，git下载是
![image](https://user-images.githubusercontent.com/5237702/38015079-49d54f32-329d-11e8-8a37-68fd58c5db0b.png)

**Comment by chenshuai2144** [comment]
这个也是少包呀。

**Comment by beyondonly** [comment]
我查一下原因，主要是我使用cnpm所有的包都是安装完了 ，你们的回复很快   感谢感谢 太强大了

**Comment by JediBai** [comment]
我是Mac 环境下，github下载zip包然后npm install后，能够运行pro

**Comment by fyuncn** [comment]
git clone之后 你用cnpm试试
