### ISSUE TITLE
Proxy Config

### ISSUE THREAD

**Issue by JoeyKo** [ant-design/ant-design-pro#1193]
网站域名： https://exampleA.com/
代理配置：
```
 "proxy": {
    "/admin/v1": {
      "target": "https://exampleB.com/",
      "changeOrigin": true
    }
  },
```
目前fetch: https://exampleA.com/admin/v1/...

期望的fetch:  https://exampleB.com/admin/v1/...
请教应该如何配置

**Comment by chenshuai2144** [comment]
你已经部署了吗？

**Comment by JoeyKo** [comment]
@chenshuai2144 是的，部署后发现借口指向的地址是网站的域名

**Comment by chenshuai2144** [comment]
[反向代理](https://www.zhihu.com/question/24723688)
