### ISSUE TITLE
请问子组件如何修改Route.js 中 LocaleProvider 的 local参数

### ISSUE THREAD

**Issue by chencanbin** [ant-design/ant-design-pro#1194]
![image](https://user-images.githubusercontent.com/6744909/38018735-5909f88a-32a8-11e8-94a7-fa76430c3558.png)
请问如何动态修改LocalProvider的local

**Comment by chenshuai2144** [comment]
https://ant.design/components/locale-provider-cn/
放到 redux 里面 或者自己搞个全局的方法

**Comment by chencanbin** [comment]
那怎么样才能在BasicLayout 这个组件中 修改 <LocalProvider >的local属性呢？

**Comment by chencanbin** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
放到 redux 是最简单的办法
