### ISSUE TITLE
框架结构问题，多页应用

### ISSUE THREAD

**Issue by beyondonly** [ant-design/ant-design-pro#1196]
您好！我想问一下，我想实现类型的结构，在后台应用中实现多页应用，效果如下，每个tab子页不从新加载内容，但是用户可以觉得是否刷新内容的交互
![image](https://user-images.githubusercontent.com/5237702/38020925-189118be-32ae-11e8-877b-5e2745645760.png)

**Comment by hoozi** [comment]
官方似乎暂时没有提供，自己撸一个，乐趣无穷

**Comment by beyondonly** [comment]
恩 类似于  vue2.0提供了一个keep-alive组件

**Comment by beyondonly** [comment]
React-Keeper 这个也是类似，但是不知道能否集成到 dva底层路由

**Comment by beyondonly** [comment]
1. 页面缓存
在移动开发中，我们经常会遇到这样的场景：在一个列表页浏览了很久，点击一项进入详情页，然后再返回到列表页，这时候我们希望列表页能保留在之前的状态（滚动位置、临时操作等），React-Router无法解决这个问题，在返回后列表页的DOM要重新加载，所以我们不得不重新手动找回之前的状态（滚动到之前的位置）。

**Comment by ddcat1115** [comment]
这个模式正在设计中，可以先看下之前的讨论  #1093 #848 

感觉主要工作在：

1. 对 SiderMenu 的改造，需要修改点击响应方式，并根据当前 tabs 决定是否新开 tab
2. 页面可能需要暂存状态

**Comment by hoozi** [comment]
深入下去的话 实现似乎有点复杂

**Comment by chenshuai2144** [comment]
关了这个吧 相关的看#1093

**Comment by beyondonly** [comment]
好的，感谢  我查看一下  这种交互还是比较常用，比较方便的

**Comment by beyondonly** [comment]
好的 感谢  我研究一下
