### ISSUE TITLE
问个低级问题，关闭mock后 后端接收不到post请求参数的问题

### ISSUE THREAD

**Issue by fyuncn** [ant-design/ant-design-pro#1200]
关闭mock后 后端接收不到post请求参数的问题，请问这个如何解决呢？

**Comment by fyuncn** [comment]
.roadhogrc.mock.js 反向代理之后 也是收不到参数

**Comment by fyuncn** [comment]
擦 我自己的问题 后台接受的时候加个@RequestBody注解就好了

**Comment by 290352095** [comment]
@fyuncn 参数格式和请求头的问题，都设置一下就行了
