### ISSUE TITLE
FooterToolbar page error

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro#1201]
https://pro.ant.design/components/FooterToolbar-cn/

<img width="870" alt="2018-03-29 2 42 02" src="https://user-images.githubusercontent.com/7017767/38073609-5e6a35a4-335e-11e8-833c-38c62460fbdc.png">

**Comment by chenshuai2144** [comment]
react 版本是15.6 
里面用了 fragment 所以跪了吧

**Comment by ddcat1115** [comment]
是markdown的问题。。。顺便升了下版本

**Comment by ddcat1115** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/a195d0cb13c81a0b8bf5bb0c16ed4d45f01e81e0

https://github.com/ant-design/ant-design-pro/commit/6b7b454298a80f48985cda77ea6f4a040b9ffdae
