### ISSUE TITLE
Would you like to run the app on another port instead?

### ISSUE THREAD

**Issue by Miaoza** [ant-design/ant-design-pro#1202]
> ant-design-pro@1.0.1 start /xx/xx/xx/xx
> cross-env DISABLE_ESLINT=true PORT=3000 roadhog dev

404

? message

Would you like to run the app on another port instead? (Y/n)

404是什么原因呀？
端口号为什么指定不了？

**Comment by u3u** [comment]
你的 3000 端口被占用了呗

**Comment by chenkang084** [comment]
你的300端口被占用了，提示你，是否需要换一个端口

**Comment by Miaoza** [comment]
试了几个端口号都一样的

**Comment by chenshuai2144** [comment]
端口号占用。。
kill 一下试试

**Comment by Miaoza** [comment]
检测过了，端口号没有被占用，试过几个端口号，都一样的

**Comment by rccoder** [comment]
@Miaoza  https://github.com/umijs/umi/pull/327  rooadhog beta 版本已经修复了

**Comment by secretconfidence** [comment]
build [==                  ] 10%，使用node启动不知道为什么就这样卡着不动了

**Comment by guancr** [comment]
> build [==] 10％，使用node启动不知道为什么就这样卡着不动了

解决了吗

**Comment by guancr** [comment]
怎么解决的？

**Comment by xiaohuoni** [comment]
@guancr 都更新到最新，还不行重开一个iss吧

**Comment by a515978292** [comment]
我也是  
build [== ] 10%  然就就不懂了

**Comment by a515978292** [comment]
我也是
build [== ] 10%，然后就卡着不动了
