### ISSUE TITLE
/ 是怎么默认路由到 /dashboard/analysis的？能否稍微解释一下？

### ISSUE THREAD

**Issue by tianlinzx** [ant-design/ant-design-pro#1203]
BasicLayout 中这段话怎么理解? 如果要改默认/的路由重定向，在哪里改？
请高手指教。谢谢。
`getBashRedirect = () => {
    // According to the url parameter to redirect
    // 这里是重定向的,重定向到 url 的 redirect 参数所示地址
    const urlParams = new URL(window.location.href);

    const redirect = urlParams.searchParams.get('redirect');
    // Remove the parameters in the url
    if (redirect) {
      urlParams.searchParams.delete('redirect');
      window.history.replaceState(null, 'redirect', urlParams.href);
    } else {
      const { routerData } = this.props;
      // get the first authorized route path in routerData
      const authorizedPath = Object.keys(routerData).find(
        item => check(routerData[item].authority, item) && item !== '/'
      );
      return authorizedPath;
    }
    return redirect;
  };`

**Comment by chenkang084** [comment]
@tianlinzx [getMenuData()](https://github.com/ant-design/ant-design-pro/blob/a982dedfcc0601627a133e180f35acddf276d087/src/layouts/BasicLayout.js#L39)获取菜单的from,保存到redirectData。
在switch里面其实是放了各种重定向即Redirect ，通过你提到的函数，获取当前的[pathname](https://github.com/ant-design/ant-design-pro/blob/a982dedfcc0601627a133e180f35acddf276d087/src/layouts/BasicLayout.js#L136)，最后在匹配到该pathname的时候，重定向到/dashboard/analysis

**Comment by chenkang084** [comment]
@tianlinzx 就是用你上面贴的函数，获取当前redirect的值，如果有，则执行跳转（重定向）https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L129；并删除从url中redirect原有的值；  
如果没有值则执行`/`,[/](https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L226)，获取[authorizedPath](https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L133:13) 会执行redirect，重定向到ashboard/analysis

**Comment by tianlinzx** [comment]
@chenkang084 谢谢回复，或者请教一下，如果想把/默认定向到/dashboard/analysis改成其他路径，在哪里改呢？谢谢。

**Comment by ddcat1115** [comment]
```js
const authorizedPath = Object.keys(routerData).find(
  item => check(routerData[item].authority, item) && item !== '/'
);
```
这里会去取 routerData 中第一个有权限的路由地址，其实不一定是 `/dashboard/analysis`。如果要改成其他的固定路径，直接在 else 中 return 这个地址就好了

**Comment by whateveryoudo** [comment]
貌似在Basiclayout中 生成route前面会取出所有redirect路径,但是 不知道  Redirect中 的exact作用是什么？？` {redirectData.map(item => (
                <Redirect key={item.from} exact from={item.from} to={item.to} />
              ))}`
