### ISSUE TITLE
How to Avoid Conflicts with Upstream Changes?

### ISSUE THREAD

**Issue by robert-claypool** [ant-design/ant-design-pro#1204]
Your README gives two usage options, `git clone [url] --depth=1` and `pro new` (from `ant-design-pro-cli`).

My goal is to build a new app using Ant Design Pro as a "starter project". For that, I could run `pro new`, but then I won't have shared history in which to pull upstream changes; therefore `git clone` is the better choice.

Assuming I clone/fork this repo as a starter project, what are some strategies to avoid merge conflicts as my application grows while development also continues here? Do you have any guidance on choosing a project structure which will exist nicely alongside new releases of `ant-design-pro`?

For comparison, ASP.NET MVC has a feature called "Areas" to split out independent sections of an application. Do you recommend a similar pattern for React and applications based on `ant-design-pro`?

**Comment by chenshuai2144** [comment]
Temporarily not, good advice。

**Comment by robert-claypool** [comment]
Sorry @chenshuai2144, I don’t understand.

**Comment by chenshuai2144** [comment]
We don't have such a great tool！

**Comment by afc163** [comment]
I am afraid you have to resolve the conflicts manually.
