### ISSUE TITLE
登录权限

### ISSUE THREAD

**Issue by pingGuoNiki** [ant-design/ant-design-pro#1206]
现在需要做多个用户，每个用户的权限不同，在框架中如何去处理

**Comment by chenshuai2144** [comment]
There is already a permission switch.

**Comment by pingGuoNiki** [comment]
你指的是在menu.js 中设置 authority: 'admin'吗？但是如果导航的菜单名字是后台接口提供的动态数据（不同的用户所看到的菜单名字是不同的），这种情况怎么去控制权限呢？能否说得详细一些呢？

**Comment by chenshuai2144** [comment]
login的时候 返回一下 然后重新 render 。
我们的代码里有这一块的

**Comment by wunayou** [comment]
这个问题 我以前考虑过，
一种解决办法 在登陆的时候 把他的权限就保存在本地，
缺点：如果管理员改变该人权限，要那个时候得到通知呢？

另一个办法，每一次进入的时候，请求后台，得到权限列表数据

其它：请求我是放在GLOBAL里面，因为其它所有组件都可以得到权限数据，包括每一个按钮的权限

好像以前有贴子写这类似的代码

**Comment by pingGuoNiki** [comment]
非常感谢你的回复，能否帮忙提供一下你上面说的写有关代码的帖子参考一下。

**Comment by pingGuoNiki** [comment]
@wunayou  你这个GLOBAL文件指的是？

**Comment by pingGuoNiki** [comment]
@wunayou  你的第二个方法是可行的，但是能否具体描述相关的操作呢？ 谢谢!
