### ISSUE TITLE
查询表格的查询功能有一个小Bug

### ISSUE THREAD

**Issue by mutouzdl** [ant-design/ant-design-pro#1209]
https://preview.pro.ant.design/#/list/table-list

当按照以下顺序操作时，查询结果不正确：

1. 在表格上筛选状态字段
2. 查询规则编号
3. 第一步的状态筛选失效

![image](https://user-images.githubusercontent.com/3509249/38130918-7d3b5a56-3437-11e8-8c29-4be72c67ce74.png)

其实我是想学习一下怎么做查询的处理，偶然发现以上的Bug。

**Comment by ddcat1115** [comment]
Table filter 是对当前表格数据进行过滤，重新查询时数据已经变化了，所以 filter 不生效是正常，但这里应该重置 filter 的高亮和选中状态，我修改下~

**Comment by mutouzdl** [comment]
@ddcat1115 也对…我一直在想怎么让查询的时候筛选也生效，看来是我想多了…谢谢

**Comment by ddcat1115** [comment]
发现之前的实现切换筛选项也会去重新取数据，就还是改成重新查询时筛选保持有效了 😂

**Comment by mutouzdl** [comment]
@ddcat1115 我还有个问题想请教一下，我看你修改的是加了一个onFilter，这样算是在客户端进行筛选吗？

**如果我希望把查询条件和筛选条件都做成由服务端来筛选，怎么做比较好？**

目前我是把查询和筛选条件保存在model里，但是这么做的话，在不同页面中调用同一个model的查询请求时会出现查询条件冲突的情况。
比如A页面调用了 rule/fetch，rule的model里保存了gz=1的条件；切换到B页面时，也调用rule/fetch，就会读取了gz=1的查询条件，实际上B页面是不希望进行查询的。

我想过在离开页面时清除model里的查询条件，但由于实际情况会复杂很多，清除的操作会变得比较复杂（页面里还有详情页、弹窗页等，会涉及到很多个model），也不好维护。

是不是我思路错了？我是做后端的，现在要兼顾前端，思维上可能有点转换不过来，见笑了。
