### ISSUE TITLE
Stuck docker build, memory overflow issue?

### ISSUE THREAD

**Issue by alexlobanov** [ant-design/ant-design-pro#1213]
Hi, 

Thanks a lot for this great product and all related stuff like `roadhog` and so on.
Currently have only one big issue.. Not sure if my issue connected to #1208 issue or not.

So currently I had VSTS build agent that build Docker images and then push it into some prod environment.
And for Ant-Design-PRO build always stuck and `npm start build` take more then 6h and still not completed.
For local machine it's also same 100% CPU usage, **more then 7GB memory usage** and after ~4 hours is still not complete. As local machine I use iMAC late 2013 with high spec. 
![screen shot 2018-03-30 at 20 05 40](https://user-images.githubusercontent.com/10769847/38146291-0caffe4e-3456-11e8-8701-65db985a6964.png)

But please notice, that outside of docker containers, I mean on macos terminal -> `npm run build` is working fine and take around 60 seconds to complete.

Could you please suggest something and probably how to resolve this issue?

Thanks again!

Best regards,
Alex

**Comment by chenshuai2144** [comment]
@sorrycc  
天天有人报性能问题，是不是需要大力解决一下

**Comment by chenshuai2144** [comment]
try  external ！

**Comment by colinzhy** [comment]
I also got an issue on `npm run build`, it's work in my local machine and building in jenkins server, but when I tried to build it in docker container, I cannot get it completed. It's hangup in the output of environment variable, and never goes continue.

**Comment by scottming** [comment]
I have the same problem. Is there someone tell me how to use docker to build an ant-design-pro server?

**Comment by ParadeTo** [comment]
Same problem!

**Comment by alexlobanov** [comment]
@chenshuai2144 Is the issue already fixed?

**Comment by chenshuai2144** [comment]
https://webpack.js.org/configuration/externals/
This is the only way

**Comment by liuhua-1991** [comment]
I fixed it with disabled the 'html css support' plugin and 'css peek' plugin
