### ISSUE TITLE
npm start后卡在cross-env ESLINT=none roadhog dev

### ISSUE THREAD

**Issue by zhtx1992** [ant-design/ant-design-pro#1214]
前几天还可以运行，删除过一次项目，之后重新clone下来运行就一直卡在这儿不继续往下了

**Comment by lee-li** [comment]
同样问题

**Comment by chenshuai2144** [comment]
#1183 看看这个
应该是少包里

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/issues/647

**Comment by zhtx1992** [comment]
@chenshuai2144 把roadhog版本换到2.2.0可以运行了，多谢

**Comment by zhangjichengcc** [comment]
当代码中头部import模块出错或引用node包出错的时候，npm start编译时会经常卡住，也不会报错。我是回头检查模块引用或用编译器检查代码，错误修复后就可以了。

**Comment by markfredchen** [comment]
同样问题。npm start的时候，build进度条卡在91%，也不知道是什么错误

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1520

**Comment by Vuchan** [comment]
@markfredchen 同样的问题，`yarn start` build进度条卡在91%，也不提示是什么错误。
