### ISSUE TITLE
MiniArea和MiniBar鼠标移动在边缘位置会报错，提示：TypeError: evtObj.toElement is null，图表页面就变得非常卡

### ISSUE THREAD

**Issue by firemonth** [ant-design/ant-design-pro#1218]
![20180401015739](https://user-images.githubusercontent.com/778526/38166102-b4d78100-3550-11e8-8968-29d6d97a782f.png)

**Comment by ddcat1115** [comment]
没有重现，你的系统和浏览器版本？ 直接看官网也会报错么？
