### ISSUE TITLE
怎么将文件上传到ant自己的服务器目录里？

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#1219]
我尝试将文件上传地址指向ant服务器的地址，但是服务端收到上传请求后不知如何接收文件，是要用node吗？

**Comment by chenshuai2144** [comment]
[后台开发](http://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=%20%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%20%E5%90%8E%E5%8F%B0&oq=%25E4%25B8%258A%25E4%25BC%25A0%25E6%2596%2587%25E4%25BB%25B6%2520%25E5%2590%258E%25E7%25AB%25AF&rsv_pq=e4c95ec6000248a5&rsv_t=f5d5zpfkL3Ob8Y9H6YIGtQ6hG8ieTz%2FIAWXZqXRP0U1KrsSxgubb0z1ygH4&rqlang=cn&rsv_enter=1&inputT=5855&rsv_sug3=29&rsv_sug1=25&rsv_sug7=100&rsv_sug2=0&rsv_sug4=6175)了解一下！

不推荐把 github 当技术论坛用。。。。
会被喷的

**Comment by zhaxingaz** [comment]
@chenshuai2144 您好，我想知道ant能不能将页面上传的文件接收到自己的服务目录？

**Comment by chenshuai2144** [comment]
前端没有io能力
