### ISSUE TITLE
在 Ant Design Pro 中使用前端路由切换为createHistory问题

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design-pro#122]
import createHistory from 'history/createBrowserHistory'
const app = dva({
  history: createHistory(),
});
切换为上述代码后#被去掉，但是在浏览器中直接访问/dashboard/analysis为白页面，访问/能被解析，访问/dashboard也能被解析，实在搞不懂

**Comment by sbyps** [comment]
https://github.com/ant-design/ant-design-pro-site/blob/master/docs/deploy.md#%E5%9C%A8-ant-design-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1
这个方案也不好用

**Comment by afc163** [comment]
browserHistory 需要后端支持。

**Comment by sbyps** [comment]
@afc163 使用HtmlWebpackPlugin应该可以吧

**Comment by afc163** [comment]
没有试过，看看文档和 http://react-china.org/t/react-router-hashhistory-browserhistory/6799/5 吧。
