### ISSUE TITLE
考虑出个webpack版本的吗

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design-pro#1223]
roadhog虽然省了很多配置 但是也不够灵活

**Comment by u3u** [comment]
https://github.com/sorrycc/roadhog/issues/636#issuecomment-372974811

**Comment by chenshuai2144** [comment]
roadhog 是用来替代 webpack 的。。。
如果需要可以自己搞一个。

**Comment by jiangzm** [comment]
@chenshuai2144 roadhog固然好，但也有很多不适用的场景，能提供切换到webpack配置入口就更好了
希望roadhog能早日加上eject 命令

**Comment by liangxinwei** [comment]
希望提供eject 命令，这样我们可以自由扩展，也更灵活。

**Comment by heya-aron** [comment]
@liangxinwei 我同意
