### ISSUE TITLE
SiderMenu展开项只匹配menu.js中的path，其他不同path如何灵活展开？

### ISSUE THREAD

**Issue by patientayo** [ant-design/ant-design-pro#1224]
RT, eg.'/user/update'展开'/user/list'项。

**Comment by ddcat1115** [comment]
具体需求场景是什么？单看描述挺奇怪的。。。

**Comment by patientayo** [comment]
@ddcat1115 
比如
用户列表路径/user/list
用户修改不在menu.js，路径/user/update，入口在用户列表中
所以当path时/user/update的时候，需要将菜单中的用户列表选中
