### ISSUE TITLE
The logon request error 404 goes straight to the blank page.

### ISSUE THREAD

**Issue by zwjun** [ant-design/ant-design-pro#1225]

**Comment by zwjun** [comment]
部署项目后，登录请求返回404时，直接跳转空白页了。

**Comment by chenshuai2144** [comment]
有报错信息吗？

**Comment by zwjun** [comment]
build部署后，mock接口不起作用的问题。

**Comment by kingmoumoumou** [comment]
页面某个js报错后, 当前页面会白屏. 如何在xiangm项目上线后屏蔽这种情况!

![image](https://user-images.githubusercontent.com/8298993/39981462-3a0d2d4e-5783-11e8-9dac-3450e8dbf72b.png)

**Comment by chenshuai2144** [comment]
@kingmoumoumou  try catch
