### ISSUE TITLE
登录请求返回404时，登录按钮一直loading，无法再次点击登录

### ISSUE THREAD

**Issue by zwjun** [ant-design/ant-design-pro#1226]

**Comment by chenshuai2144** [comment]
我们的预览页面吗？

**Comment by zwjun** [comment]
不是预览界面，在开发环境下，模拟了一个不存在的登陆接口，

**Comment by chenshuai2144** [comment]
报错信息给一下？

**Comment by zwjun** [comment]
请求错误 404: 
http://localhost:8000/api/login/account1
发出的请求针对的是不存在的记录，服务器没有进行操作。

POST http://localhost:8000/api/login/account1 404 (Not Found)

只是将原来的登录接口换了一个不存在的接口

**Comment by chenshuai2144** [comment]
开发环境因为 try file 的原因  没有404 会返回 index.html.

**Comment by AirmaZ** [comment]
> 开发环境因为 try file 的原因 没有404 会返回 index.html.
> post 也会返回一个 html。问题应该出在这里。

如果针对XHR请求避免这个返回html呢？因为有的时候没有写mock，本地开发的时候接口会一直返回index.html造成json解析失败

**Comment by Dragon201701** [comment]
出现新的问题：src/services/user.js 尝试使用谷歌firebase获取用户信息，登录成功后无法导向主页
export async function queryCurrent() {
  
  let userPromise = firebase.auth().onAuthStateChanged(function(user) {
    if (user) {
      // User is signed in.
      console.log('User is signed in: ', user)
    } else {
      // No user is signed in.
    }
  });
  /*let req = request('/api/currentUser');
  console.log('Query current user: ', req)
  return req*/
  return userPromise
  
}
