### ISSUE TITLE
自定义请求接口，传了POST，最后请求还是默认的Request Method:OPTIONS

### ISSUE THREAD

**Issue by zlxls** [ant-design/ant-design-pro#1230]
![1](https://user-images.githubusercontent.com/32283731/38283286-b9c7988c-37e7-11e8-9c2b-d1f1300f245e.png)
![2](https://user-images.githubusercontent.com/32283731/38283288-bccb0a5a-37e7-11e8-89b1-819d351098e2.png)

**Comment by chenshuai2144** [comment]
跨域了发起post会先发option

**Comment by ybning** [comment]
[HTTP访问控制（CORS）](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS)
