### ISSUE TITLE
以独立组件的方式使用Login组件，会导致分步表单页及搜索列表页出现样式错乱

### ISSUE THREAD

**Issue by lyingd** [ant-design/ant-design-pro#1239]
以独立组件的方式使用Login组件，会导致分步表单页及搜索列表页出现样式错乱。
查看生成的css，是antd的关键样式，在自定义样式的后面，导致使用:global覆盖antd样式不成功。
如果直接使用Login的源码，则无此问题，自定义样式会在antd原有样式之后。
具体原因未明，目前只能暂时以源码的方式使用Login解决此问题。
补充：以上问题仅存在production版本，development版本没问题

错误情况: https://github.com/lyingd/antd-pro-standalone/commit/4f04d781e4e28de3f9ea3d109bc99b6eded5a4f1
![](https://github.com/lyingd/antd-pro-standalone/blob/4f04d781e4e28de3f9ea3d109bc99b6eded5a4f1/public/LoginComponentStyleErrorImage/projects-error.png?raw=true)
![](https://github.com/lyingd/antd-pro-standalone/blob/4f04d781e4e28de3f9ea3d109bc99b6eded5a4f1/public/LoginComponentStyleErrorImage/stepform-error.png?raw=true)

正常情况: https://github.com/lyingd/antd-pro-standalone/commit/9e22606bee801f62d889f0e407a9abad79dbdd91
![](https://github.com/lyingd/antd-pro-standalone/blob/4f04d781e4e28de3f9ea3d109bc99b6eded5a4f1/public/LoginComponentStyleErrorImage/projects.png?raw=true)
![](https://github.com/lyingd/antd-pro-standalone/blob/4f04d781e4e28de3f9ea3d109bc99b6eded5a4f1/public/LoginComponentStyleErrorImage/stepform.png?raw=true)

**Comment by chenshuai2144** [comment]
v2会一起解决的
