### ISSUE TITLE
请问如何在某个effects中刷新页面

### ISSUE THREAD

**Issue by Leskur** [ant-design/ant-design-pro#1241]
`*changeStatus({ payload: { id, status } }, { call, put, }) {`
`yield call(editMember, id, {`
`status,`
`});`
`// 如何在这里刷新页面，url参数不变`
`},`

**Comment by afc163** [comment]
`window.location.reload()`

**Comment by chenshuai2144** [comment]
为什么会有 Refresh 的需求？
