### ISSUE TITLE
node.js 内存溢出

### ISSUE THREAD

**Issue by CherryaMao** [ant-design/ant-design-pro#1244]
npm start时报FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory，node 的版本为8.1.1；有大神知道怎么解决的吗？

**Comment by chenshuai2144** [comment]
externals 一下吧。

**Comment by CherryaMao** [comment]
怎么个externals法？

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog#configuration

**Comment by CherryaMao** [comment]
我先在src下创建了一个文件.webpackrc里面的内容为{
  "externals": { "react": "window.React" }
}，然后在到.roadhogrc中的添加了最后两条"externals": {
    "g2": "G2",
    "g-cloud": "Cloud",
    "g2-plugin-slider": "G2.Plugin.slider",
    "react": "window.React",
    "react-dom": "window.ReactDOM"
  },
后来把"externals"中的后两条去掉也不行。
然后在npm start 仍报内存溢出的错。

**Comment by ybning** [comment]
@CherryaMao 
[https://hackmd.io/YHK_yuRtT0ePPVLY0_kUzw](https://hackmd.io/YHK_yuRtT0ePPVLY0_kUzw)

**Comment by heyguo** [comment]
直接在node_modules/.bin/umi.cmd文件中扩展内存,prov2可行。

@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.ex**e" --max_old_space_size=8192  "%~dp0\..\umi\bin\umi.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node --max_old_space_size=8192  "%~dp0\..\umi\bin\umi.js" %*
)

**Comment by Mh2336393** [comment]
> 直接在node_modules/.bin/umi.cmd文件中扩展内存,prov2可行。
> 
> @if EXIST "%~dp0\node.exe" (
> "%~dp0\node.ex**e" --max_old_space_size=8192 "%~dp0..\umi\bin\umi.js" %*
> ) ELSE (
> @SETLOCAL
> @set PATHEXT=%PATHEXT:;.JS;=;%
> node --max_old_space_size=8192 "%~dp0..\umi\bin\umi.js" %*
> )

服务器在服务器打包你怎么做这操作？

**Comment by Mh2336393** [comment]
都不是可行的方法 我们是流水线出包 不止打包你一个客户端

**Comment by heyguo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我这个用的时候是prov2, 小项目都是本地打包
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1365584707
                            
                    
                        
                            
                                    1365584707@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年11月12日 19:35，Mh2336393<notifications@github.com> 写道： 






直接在node_modules/.bin/umi.cmd文件中扩展内存,prov2可行。

@if EXIST "%~dp0\node.exe" (

"%~dp0\node.ex**e" --max_old_space_size=8192 "%~dp0..\umi\bin\umi.js" %*

) ELSE (

@SETLOCAL

@set PATHEXT=%PATHEXT:;.JS;=;%

node --max_old_space_size=8192 "%~dp0..\umi\bin\umi.js" %*

)



服务器在服务器打包你怎么做这操作？



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by heyguo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    用的时候比较早，都是本地解决方法，觉得有问题的解答可以删除掉
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1365584707
                            
                    
                        
                            
                                    1365584707@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年11月12日 19:45，Mh2336393<notifications@github.com> 写道： 




都不是可行的方法 我们是流水线出包 不止打包你一个客户端



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
