### ISSUE TITLE
启动页的URL修改

### ISSUE THREAD

**Issue by x19990416** [ant-design/ant-design-pro#1245]
请问下，antd pro 启动的时候指向的是 127.0.0.1:8000/这个路径
我想让antd pro 的url路径改为 127.0.0.1:8000/antd 
不知该如何修改，

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L226

设置这儿就可以了

**Comment by x19990416** [comment]
@chenshuai2144 那个是修改layout的路径
我是想要加一个根目录。
比如，一开始是http://127.0.0.1:8000/#/user/login 我想要http://127.0.0.1:8000/1234/user/login

**Comment by chenshuai2144** [comment]
<Redirect exact from="/" to={"/1234/user/login"} />

**Comment by x19990416** [comment]
@chenshuai2144 url里面那个#还在，有啥办法可以去掉么，感觉应该是个配置问题

**Comment by chenshuai2144** [comment]
use hash router
https://github.com/ant-design/ant-design-pro/blob/master/src/index.js#L5

**Comment by x19990416** [comment]
@chenshuai2144 
找到了，修改router.js

**Comment by x19990416** [comment]
@chenshuai2144 我觉得这个应该是顶层路由设置的问题？但是实在不知道如何设置路由
