### ISSUE TITLE
部署服务器后请求问题

### ISSUE THREAD

**Issue by fyuncn** [ant-design/ant-design-pro#1250]
你好，最近遇到一个问题，打包后上传服务器，无法请求到接口的问题，本地都是好的，一开始是报405错误,去掉NG限制后报js错误，还是无法请求到后台

**Comment by chenshuai2144** [comment]
show config?

**Comment by chenshuai2144** [comment]
r部署之后没有roadhogrc了

**Comment by chenshuai2144** [comment]
是的 需要专门的代理

**Comment by afc163** [comment]
.roadhogrc.mock.js 应该还是有的
