### ISSUE TITLE
SSO 登录的解决方案

### ISSUE THREAD

**Issue by saipanno** [ant-design/ant-design-pro#1253]
想了解下有没有同学尝试过对接 SSO 登录。
由于 SSO 登录是走 302 跳转实现，所以这块儿我在前面的 nginx 里做了相关逻辑，可以正确获取到登录用户信息，然后存储在 cookies 里供 web 读取。

但是目前的问题是 Pro 里的用户信息、权限设置相关的逻辑都是在 login/logout 里做的，现在 SSO 跳过这一块儿了，还有什么地方可以做从 cookies 里读出用户信息来做 reloadAuthorized 等逻辑呢？

我现在能想到的是每个组件都重复做这个事情。。别的没想到什么方法。

谢谢。

**Comment by chenshuai2144** [comment]
现在没有支持这个的 功能排期

**Comment by b9AobJ** [comment]
这个问题有好的实现思路吗？如果有，请指点指点
