### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by CherryaMao** [ant-design/ant-design-pro#1256]
我先在src下创建了一个文件.webpackrc里面的内容为{
"externals": { "react": "window.React" }
}，然后在到.roadhogrc中的添加了最后两条"externals": {
"g2": "G2",
"g-cloud": "Cloud",
"g2-plugin-slider": "G2.Plugin.slider",
"react": "window.React",
"react-dom": "window.ReactDOM"
},
后来把"externals"中的后两条去掉也不行。
然后在npm start 仍报内存溢出的错。

**Comment by chenshuai2144** [comment]
可能是你的代码导入了什么很大的东西。
vscode 可以试试这个插件
https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost
