### ISSUE TITLE
Endless loop due to Ellipsis's bug

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design-pro#1258]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/Ellipsis/index.js#L67
CASE：
非webkit浏览器中(Firefox/59.0)
行高19.5被parseInt为19
（lines=1）=> （targetHeight=19）
同时totalHeight=20（content一行足以显示）
导致bisection中sh<=th一直true，bisection死循环页面挂掉

重构版：https://github.com/qiaoyixuan/ant-design-pro/commit/9912debfce27dcead9ecc01f7f15bdd8fdb8856d

**Comment by chenshuai2144** [comment]
可以 pr 一下

**Comment by nikogu** [comment]
应该向上取整

**Comment by nikogu** [comment]
这个我明天来搞下吧
