### ISSUE TITLE
antd pro 加载 flash 的疑问

### ISSUE THREAD

**Issue by hehuasa** [ant-design/ant-design-pro#1259]
关于项目加载flsah（将swf文件作为静态文件去加载），目前遇到了一些问题：

```
import React, { PureComponent } from 'react';
import flash from '../../assets/flash/TrueMapExplorer.swf';
import config from './lib/config.xml';

......
export default class TrueMap extends PureComponent {
......
  render() {
    return (
      <div id="flashContent" style={{ width: 400, height: 400 }} >
        <embed
          type="application/x-shockwave-flash"
          src={flash}
          width="100%"
          height="100%"
          id="TME"
          name="TME"
          ref="TME"
          bgcolor="#ffffff"
          quality="high"
          menu="false"
          wmode="windows"
          allowscriptaccess="always"
          allowFullScreen="true"
        />
      </div>
    );
  }
```
本地环境运行后，浏览器调试发现swf文件没有被加载：

![tim 20180409161532](https://user-images.githubusercontent.com/26007057/38487086-9be1ead8-3c11-11e8-8c9d-70510bec3315.png)
![tim 20180409161540](https://user-images.githubusercontent.com/26007057/38487087-9c2ec72c-3c11-11e8-8a6c-a234d3a61e06.png)

由于加载flash不把文件放一起，处理起跨域问题比较麻烦；所以还是想尽量放一起。
请问大家有没有类似的经验呢？？

**Comment by hehuasa** [comment]
恩，上午试过了，还是有问题。刚刚又试了一下，不确定了。。。
因为flash挂载完成，拿到flash对象后（这里也是个坑，componentDidMount中，flash并没有加载完成，这时是拿不到flash对象的，不知道要怎么判断flash加载完成~~~~，暂时用了个setTimeout），还要加载一个 config.xml 配置文件。
config.xml文件放服务器上也存在跨域问题，放本地又不能作为静态资源使用，直接import，貌似被框架直接变成了一个数据流。。。 
大家有遇到过类似的问题吗？？

**Comment by hehuasa** [comment]
将config.xml文件和swf文件都放public下，用相对路径来加载，问题解决了。
谢谢 @chenshuai2144 。

**Comment by hehuasa** [comment]
另外请问大家 ：
加载flash时，在componentDidMount中，flash并没有加载完成，这时是拿不到flash对象的。大概要延迟一段时间（根据浏览器的渲染速度），不知道要怎么判断flash加载完成~~~~。请问大家有遇到过类似问题吗？？

**Comment by chenshuai2144** [comment]
可以在 `componentDidMount` 轮询

**Comment by hehuasa** [comment]
好的，我试试。谢谢了
