### ISSUE TITLE
在由dva-cli搭建的环境中使用ant-design-pro,单独使用组件，没有样式？

### ISSUE THREAD

**Issue by smallchicken** [ant-design/ant-design-pro#126]
我用dva-cli的环境中单独使用组件，antd的组件没有问题，但是ant-design-pro的所有的组件都没有样式

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/3ef3318e0d168329d34e887cd9ebfce9ad7a0175
