### ISSUE TITLE
关于apache部署转发

### ISSUE THREAD

**Issue by x19990416** [ant-design/ant-design-pro#1261]
我在apache上配置转发到antd的服务器上配置如下

```
ProxyPass /wewalk/crm http://10.1.31.225:8000/wewalk/crm
ProxyPassReverse /wewalk/crm http://10.1.31.225:8000/wewalk/crm
```

检测到/wewalk/crm时转发到 225的wewalk/crm目录下
但是 在请求是会发现 index.js是的请求为 http://host/index.js，不知上述情况该如何处理

**Comment by chenshuai2144** [comment]
控制台截图？

**Comment by x19990416** [comment]
@chenshuai2144 
![default](https://user-images.githubusercontent.com/9440757/38490149-dadcd474-3c1a-11e8-9313-cbbd468d8434.png)

**Comment by x19990416** [comment]
@chenshuai2144 我是从233重定向到225，直接访问225是ok的

**Comment by chenshuai2144** [comment]
我感觉没有问 访问 根目录下面的 index.js 你不在根目录？

**Comment by x19990416** [comment]
index.js在/srcls根目录下，直接访问225是ok的

![default](https://user-images.githubusercontent.com/9440757/38491292-0df0fae0-3c1e-11e8-9bd1-3d8f073dde29.png)
![default](https://user-images.githubusercontent.com/9440757/38491375-40b97f9c-3c1e-11e8-8f96-63d5d9c1c494.png)

**Comment by chenshuai2144** [comment]
index.js 回去跟目录下面找的。。
你要放到别的地方 试试配置 public
