### ISSUE TITLE
help，pro项目怎么roadhog配置webpack？

### ISSUE THREAD

**Issue by lettywiterock** [ant-design/ant-design-pro#1265]
[https://github.com/sorrycc/roadhog/issues/664](url)

关于外部swiper插件引入，build报错问题

**Comment by lettywiterock** [comment]
I quoted swiper plug-in outside, NPM run build, wrong information:

Creating an optimized production build...
Failed to compile.

19.400dbb9d.async.js from UglifyJs
Unexpected token: operator (>) [19.400dbb9d.async.js:64602,43]

49.504adf06.async.js from UglifyJs
Unexpected token: operator (>) [49.504adf06.async.js:5765,43]

···································································································
I checked that the solution to swiper plug-in is:

In case you use it as an ES module make sure:

you have enabled Babel or Buble to transpile it to ES5 syntax,
you have enabled node modules resolving for Swiper as it uses Dom7 as a dependency.

module: {
  rules: [
    {
      test: /\.js$/, // Check for all js files
      exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
      loader: 'babel-loader'
    }
  ]
}
···································································································

I want to ask how roadhog is configured？

**Comment by chenshuai2144** [comment]
Without this function.

**Comment by chenshuai2144** [comment]
Your problem is to use a package that is not use babel compiled.

**Comment by lettywiterock** [comment]
But start can't be build!

**Comment by lettywiterock** [comment]
extraBabelIncludes
Define an additional list of file matches that need to be transformed with babel, the format is Array.

这个怎么使用呢？
