### ISSUE TITLE
ant-design-pro.gitee.io国内网站预览打不开

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design-pro#1266]
ant-design-pro.gitee.io国内网站预览打不开

![image](https://user-images.githubusercontent.com/4488399/38533649-e27e48c4-3cac-11e8-8343-1d5f569b36f6.png)

**Comment by afc163** [comment]
建议翻墙

**Comment by baonanhai** [comment]
现在国内的网站，预览的也很多404.
![image](https://user-images.githubusercontent.com/1573149/62914007-e5e6f600-bdc0-11e9-9249-933c12184ed2.png)

**Comment by afc163** [comment]
@baonanhai #4705
