### ISSUE TITLE
权限是数组的话不行

### ISSUE THREAD

**Issue by mrandpz** [ant-design/ant-design-pro#1267]
`
export function getAuthority () {
  return ['admin', 'user', 'scmSupplierManager'];
}
`
这样子就直接报错了

**Comment by chenshuai2144** [comment]
不支持这种用法！
可以传入function自己判断

**Comment by mrandpz** [comment]
@chenshuai2144 谢谢回答，请问我把权限改成 String  `'admin,user'`   然后在 CheckPermissions.js  对string进行处理
 `if (typeof authority === 'string') {
    if (currentAuthority.indexOf(authority) > -1) {
      console.log(authority, currentAuthority)
      return target;
    }
    return Exception;
  }`
还是一样报错，能否指点一下，后台返回权限数组的情况
