### ISSUE TITLE
roadhog dev 多个环境怎么操作

### ISSUE THREAD

**Issue by packjie** [ant-design/ant-design-pro#1270]
现在除了开发生产还想添加两个测试环境，但是使用roadhog dev后自己配置的process.env.NODE_ENV 无论本地环境变量改成什么，代码都是读取的development。
```
const address = {
    development: "127.0.0.1:3000",
    production: "****",
    staging: "***",
    test: "***"
};
```
有谁知道如何解决吗？

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#env 
现在好像不能配置！可以去 roadhog 提一下 issue
