### ISSUE TITLE
关于standardtable的问题

### ISSUE THREAD

**Issue by 290352095** [ant-design/ant-design-pro#1277]
1、直接写在组件的render里面，用Form标签包住，提交时，提交不了列中的表单！
2、使用Form.create创建表单，可以提交理想数据，但是复选功能会失效，每次复选会重新渲染form！
3、单独把standardtable和form创建一个组件引入，复选功能正常，提交的数据会包括父组件中的其他表单！
不知还有何万全之策，还请各位指点一二，谢谢

**Comment by ddcat1115** [comment]
StandardTable 只是对 Table 的简单封装，你想要实现的是什么需求？最好提供 demo 或代码，再针对性的说明问题~

**Comment by 290352095** [comment]
@ddcat1115 我想把Standardtable   中的某一列设为输入框  这列中所有的输入框单独在一个form中   点击提交按钮对这列的数据进行提交，不影响页面中的其他form

**Comment by ddcat1115** [comment]
如果需要跟其他表单项隔离，可以把 StandardTable 单独用一个 Form 再封装下单独提交，类似 [CreateForm](https://github.com/ant-design/ant-design-pro/blob/master/src/routes/List/TableList.js#L36)

如果遇到问题请提供下在线可重现 demo，可以 fork 并编辑 https://codesandbox.io/s/jnw46698m3

另外如果不需要 StandardTable 的统计展示功能，直接用 antd Table 来做更简单

**Comment by chenshuai2144** [comment]
table 现在不适合和 form 做结合的。
有很多问题

**Comment by 290352095** [comment]
@chenshuai2144 那好吧，谢谢您了，我只能自己取出想要的东西了
