### ISSUE TITLE
jest的globals配置无法生效？

### ISSUE THREAD

**Issue by mutouzdl** [ant-design/ant-design-pro#1279]
**我的操作步骤如下：**
 
- 我希望在单元测试中使用全局变量，给package.json添加了以下配置：
`"jest": {
    "globals": {
      "__Dev__": true
    }
}`

 - 编写了一个简单的测试（demo.test.js）：
`
test('demo', () => {
  console.log('__Dev__:', __Dev__);
});
`

 - 运行命令：npm test demo.test.js

- 结果报错，__Dev__未定义：
![image](https://user-images.githubusercontent.com/3509249/38653837-36640e68-3e3f-11e8-94b8-48ab5a3831fa.png)

**使用的是两天前拉的master代码，除了以上操作，没有做其他改动。
然后我尝试把scripts里的test改为jest就没问题了：**
![image](https://user-images.githubusercontent.com/3509249/38654019-0bee7226-3e40-11e8-9251-33d8e3f9200d.png)

**运行结果：**
![image](https://user-images.githubusercontent.com/3509249/38654065-3097a35e-3e40-11e8-9af8-179a4589001d.png)

**是不是我的使用方式不对？**

**Comment by chenshuai2144** [comment]
去 roadhog 问一下吧。
可能有什么特殊操作吧

**Comment by mutouzdl** [comment]
好的，我去问问

**Comment by mutouzdl** [comment]
https://github.com/sorrycc/roadhog/issues/672#issuecomment-387336136
