### ISSUE TITLE
三级路由，PageHeader显示链接问题

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design-pro#128]
当第三级菜单展开的时候，PageHeaderLayout的路由面包屑会显示链接。如图：

此问题在参数路由（非菜单）的情况下也会存在。如图。
![image](https://user-images.githubusercontent.com/26354664/32479036-f4d85f90-c3c2-11e7-8d19-e10e0524d1ef.png)

**Comment by int2d** [comment]
+1

**Comment by gebilaoman** [comment]
问题解决了？

**Comment by ddcat1115** [comment]
fixed
