### ISSUE TITLE
控制台大面积输出

### ISSUE THREAD

**Issue by 290352095** [ant-design/ant-design-pro#1280]
![image](https://user-images.githubusercontent.com/23628090/38654483-283b1c5c-3e42-11e8-97a5-73c30e92541d.png)
控制台大面积报这个  是哪里出了问题呀

**Comment by chenshuai2144** [comment]
看起来是个插件

**Comment by 290352095** [comment]
@chenshuai2144 嗯嗯  找到问题了  谢啦
