### ISSUE TITLE
给TextArea或Input绑定任何方法，无法回调得到正确的值

### ISSUE THREAD

**Issue by moker-monkey** [ant-design/ant-design-pro#1284]
是这样绑定的
onChange={e=>TextAreaIpt(e)}
但是e值的都不是触发的值
![image](https://user-images.githubusercontent.com/23519198/38675100-48a33104-3e89-11e8-898f-8c157b58ad09.png)

**Comment by chenshuai2144** [comment]
https://reactjs.org/docs/forms.html
