### ISSUE TITLE
npm start  cross-env ESLINT=none roadhog dev  No response

### ISSUE THREAD

**Issue by hkl921010** [ant-design/ant-design-pro#1286]
![image](https://user-images.githubusercontent.com/23328281/38678821-b80e8e84-3e94-11e8-837c-c3e2f33bc2c5.png)

**Comment by hkl921010** [comment]
卡住了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1214
重复了
