### ISSUE TITLE
和服务端交互返回500错误是不是根本就没请求到正确的服务端接口

### ISSUE THREAD

**Issue by Uhaiping** [ant-design/ant-design-pro#1288]
我是刚开始用这个项目的，按照官网教程上，还是没看懂怎么从 mock 直接切换到服务端请求，大神可以讲一下具体怎么改.roadhogrc.mock.js文件吗

**Comment by chenshuai2144** [comment]
500是服务器出错了
你的参数给错了 或者 服务器执行代码出错了

**Comment by chenshuai2144** [comment]
`yarn start:no-proxy`
就可以不用 mock 的

**Comment by Uhaiping** [comment]
服务端我用之前的框架测试过，没错的，就是不知道在.roadhogrc.mock.js中怎么改为我的服务端地址

**Comment by chenshuai2144** [comment]
你可以代理到你的服务器的

**Comment by Uhaiping** [comment]
怎么代理？我是这么改的
![image](https://user-images.githubusercontent.com/33239901/38714523-3cb7ebb6-3f09-11e8-9155-fe7340fa0f20.png)

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog#proxy

**Comment by Uhaiping** [comment]
还有就是每次npm start都要等好久

**Comment by Uhaiping** [comment]
之前项目是这么用的，现在是用的webpackrc.js不知道还行不行
"proxy": {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}

**Comment by chenshuai2144** [comment]
看一下 roadhog 的文档吧

**Comment by Uhaiping** [comment]
是不是不能这么改呢，我把上面那个图中的最后一行替换成这样了
![image](https://user-images.githubusercontent.com/33239901/38714865-cee5a838-3f0a-11e8-81a9-283105242644.png)
