### ISSUE TITLE
配置ngnix后，老是提示Disconnected from the devServer, trying to reconnect...

### ISSUE THREAD

**Issue by mrandpz** [ant-design/ant-design-pro#1289]
需要不停的重新打开新标签页

**Comment by chenshuai2144** [comment]
为什么要用 nginx？
你的问题是因为 nginx 需要特殊配置才支持转发 socket 的原因

**Comment by mrandpz** [comment]
因为后台的接口需要涉及到登陆校验，接口登陆后，我的页面还没登陆会导致跨域，那ngnix需要怎么特殊配置，这是我配置的Nginx
![image](https://user-images.githubusercontent.com/20697372/38721251-f6d00cb4-3f2b-11e8-9b58-dd3b88a1b56f.png)

配置转发只的是http://www.bubuko.com/infodetail-2350212.html  ？

**Comment by chenshuai2144** [comment]
百度一下 你就知道

**Comment by mrandpz** [comment]
好的。thx

**Comment by ChimingPhang** [comment]
@mrandpz 请问你解决了吗
