### ISSUE TITLE
Absolute imports in .less files

### ISSUE THREAD

**Issue by chillyistkult** [ant-design/ant-design-pro#1292]
Can someone explain me why absolute imports in .less files are not working? It looks like webpack resolve.alias is ignored in .less and alias in .babelrc is not working anyway.

I need absolute imports because I'd like to overwrite @import "~antd/lib/style/themes/default.less"; in each and every component, since the theme.js option described on https://ant.design/docs/react/customize-theme is inconvenient for bigger projects.

**Comment by chenshuai2144** [comment]
2.0 will support。
