### ISSUE TITLE
按文档 不能使用 独立使用组件

### ISSUE THREAD

**Issue by chujc** [ant-design/ant-design-pro#1295]
对于没有使用这套脚手架的开发者，我们提供了一种方式来调用这套内建组件。

默认业务组件会发布到 npm 的 ant-design-pro 上。

$ npm install ant-design-pro --save
import 'ant-design-pro/dist/ant-design-pro.css'; // 统一引入样式
然后你就可以像使用 Ant Design 组件一样调用 pro 组件了。

import Result from 'ant-design-pro/lib/Result';

ReactDOM.render(<Result type="success" />, mountNode);

100% 按照如上做的  之后去看  没有在ant-design-pro 下面找到 dist 和lib两个文件夹

如果使用 import Result from 'ant-design-pro/src/components/Result';  又爆
Cannot find module "./index.less"
我应该如何做 才能单独使用  ant-design-pro

**Comment by afc163** [comment]
有这两个文件夹哦：https://unpkg.com/ant-design-pro@1.2.1/

**Comment by chenshuai2144** [comment]
需要通过 npm 包安装的。。。。
你 get 了什么神奇的用法

**Comment by chujc** [comment]
![image](https://user-images.githubusercontent.com/22972932/38813633-0e41cf0c-41c2-11e8-86ea-256da954c966.png)
mac os 下面 就算把file:ant-design-pro 修改为 对应的版本号 ^1.2.1 在执行npm 还是不行
