### ISSUE TITLE
图表组件TimelineChart数值有误

### ISSUE THREAD

**Issue by darrenCoding** [ant-design/ant-design-pro#130]
![TB1TL0FbLDH8KJjy1XcXXcpdXXa](https://img.alicdn.com/tfs/TB1TL0FbLDH8KJjy1XcXXcpdXXa-2790-850.png)

如图所示，**加购成功数是110，明显y轴数值显示有误**

**Comment by nikogu** [comment]
@darrenCoding 先确保一下你的数据值为：number 而不是 string，g2 2.0 在数据类型解析上不够容错，3.0 应该会改进

**Comment by darrenCoding** [comment]
**已经确认了是number类型，麻烦帮忙看一下。**@nikogu
![TB1a1qMbRHH8KJjy0FbXXcqlpXa](https://img.alicdn.com/tfs/TB1a1qMbRHH8KJjy0FbXXcqlpXa-990-508.png)

**Comment by nikogu** [comment]
好的，我看看

**Comment by nikogu** [comment]
修复了，下个版本发布

**Comment by darrenCoding** [comment]
好的，非常感谢。
