### ISSUE TITLE
Pie chart render only after screen resolution change

### ISSUE THREAD

**Issue by sahar922** [ant-design/ant-design-pro#1301]
Hey :)
I'm using latest ant-d & ant pro versions, trying to use the [Pie Chart](https://pro.ant.design/components/Charts/#scaffold-src-components-Charts-demo-pie),
I copied the example from the link above. The legend appearing well, also the title and the total props, but the chart doesn't appear, as you can see in the image below : 
 
![screen shot 2018-04-16 at 11 51 28 am](https://user-images.githubusercontent.com/12861093/38799327-dbf8b524-416c-11e8-8572-5da15eb662b2.png)

Only after I made any changes in the screen size (for example clicking the minimize icon, so the screen became smaller) the chart appearing well.

![screen shot 2018-04-16 at 11 56 04 am](https://user-images.githubusercontent.com/12861093/38799429-2bb12fce-416d-11e8-8803-e3e6ac777d00.png)

any ideas why?

Thanks a lot

Update : 
I realized that also if you're trying to test the Pie chart component for different screen sizes, it looks bad, and after changing again the screen size it's going well.

**Comment by nikogu** [comment]
https://github.com/dvajs/dva/issues/1300

i think it's only in dev environment, you can set a timeout to fix it, but it's a trick.

**Comment by bgold0** [comment]
Why was this closed? How do we fix?
