### ISSUE TITLE
npm run build之后怎么访问mock数据呢

### ISSUE THREAD

**Issue by magicly** [ant-design/ant-design-pro#1302]
有时候只想要展示个demo， 不想要连真实的数据库（甚至后端都没写好）， `npm start`可以访问mock数据， 但是`npm run build`之后mock数据是没有打包进去的， 有没有办法把mock数据整合进去呢。

需求跟https://github.com/ant-design/ant-design-pro/issues/992 差不多

https://github.com/sorrycc/roadhog/issues/334 说貌似不支持。

但是我看https://preview.pro.ant.design 就是没有发api请求， 请问是怎么做的呢？ 谢谢~

**Comment by u3u** [comment]
### 静态站点生成

项目根目录，运行：

```bash
roadhog-api-doc static
```

会生成三个文档站点静态文件：api.html、api.js、api.css，你可以将其部署到自己的站点中供线上访问，这里的数据已经被静态化（转换网络请求为代码数据）。

https://pro.ant.design/docs/api-doc-cn

**Comment by chenshuai2144** [comment]
接口静态化？

**Comment by magicly** [comment]
@u3u 你好， 3x， 我看了https://pro.ant.design/docs/api-doc-cn，
```bash
$ roadhog-api-doc build
```
这个最后会生成api.html, api.js, api.css， 我单独部署了之后， 然后要怎么才能跟ant-design-pro build之后的静态文件一起使用呢，  怎么才能部署成像https://preview.pro.ant.design/ 这样， 不需要访问外部的api呢？

**Comment by magicly** [comment]
@chenshuai2144 你好， 想请问怎么才能部署成像https://preview.pro.ant.design/ 这样， 不需要访问外部的api呢？

**Comment by u3u** [comment]
@magicly 我不是已经说了么

项目根目录，运行：

```bash
$ roadhog-api-doc static
```

执行之后会静态化 mock 数据，你只需要部署 `dist` 目录即可

```bash
serve -s dist
```

**Comment by chenshuai2144** [comment]
楼上说的对

**Comment by magicly** [comment]
@u3u @chenshuai2144 弄好了， 谢谢~   😅， 昨天理解错了， 以为是`roadhog-api-doc static`只生成了api.html, api.js, api.css三个文件， 然后把这三个copy出来跟之前用`npm run build`生成的文件部署在一起😯。    原来是`roadhog-api-doc static`就生成了所有需要的文件。。  thanks~

**Comment by aeolusheath** [comment]
@u3u   你好，请问这个 

`roadhog-api-doc static`

命令是 ant 团队 定制化的吗？ 我想在一个用roadhog创建的app build之后使用mock data..

**Comment by gaoqiang19514** [comment]
> @magicly 我不是已经说了么
> 
> 项目根目录，运行：
> 
> ```shell
> $ roadhog-api-doc static
> ```
> 
> 执行之后会静态化 `mock` 数据，你只需要部署 `dist` 目录即可
> 
> ```shell
> $ serve -s dist
> ```

找不到`roadhogrc.mock.js`文件，求助

**Comment by lifecreater** [comment]
第一版还有.roadhogrc.mock.js这个文件，v2就没了。 @u3u 麻烦更新一下解决方法。
