### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by mogmog** [ant-design/ant-design-pro#1303]
I am struggling to integrate user authentication. 

In the mocked example I see currentUser always returns userid 00000001 - is there an example somewhere of a real backend api integrated with ant design? Is cookies or local storage the prefered implementation?

**Comment by chenshuai2144** [comment]
This is just an example so we will return 00000001 by default. 
The actual situation is not like this.
you can try return real user info and includes authentication information.

**Comment by mogmog** [comment]
Yeah all good now. I was trying to use the currentuser api the wrong way by passing the user id on the url. I have now implemented  a sessions table in my backend and it integrates nicely with ant design.
