### ISSUE TITLE
想知道从后台获得权限这里要怎么弄

### ISSUE THREAD

**Issue by shadiniao** [ant-design/ant-design-pro#1306]
模版中是登录后直接就返回admin或者user,把这两个作为权限放在localStorage中

实际项目中先要去拿到token,再根据token去拿用户权限
文档中说使用 localstorage 模拟权限角色，实际项目中可能需要从后台读取。

这是要把getAuthority, RenderAuthorized 都改成async方法吗?

**Comment by shadiniao** [comment]
我现在把utils\authority.js的getAuthority改成这样
```
export async function getAuthority() {
	const accessToken = getAccessToken();
	try {
		const response = await fetch(`http://localhost:9595/user?access_token=${accessToken}`);
		return await response.json();
	} catch (e) {
		return [ 'user', 'admin' ];
	}
}
```

renderAuthorize改成这样
```
const renderAuthorize = (currentAuthority) => {
	if (currentAuthority) {
		if (currentAuthority.constructor.name === 'Function') {
			CURRENT = currentAuthority();
		}
		if (currentAuthority.constructor.name === 'String') {
			// CURRENT = currentAuthority;
			CURRENT = [ currentAuthority ];
		}
		if (currentAuthority.constructor.name === 'Array') {
			CURRENT = currentAuthority;
		}
		if (currentAuthority.constructor.name === 'Promise') {
			currentAuthority.then((result) => {
				CURRENT = result;
			});
		}
	} else {
		// CURRENT = ['NULL'];
		CURRENT = [];
	}
	return Authorized;
};
```

checkPermissions时currentAuthority都还是空的

**Comment by wscodinglover** [comment]
在src文件下的顶层路由router.js 可以配置所有的权限  
function RouterConfig({ history, app }) {
  const routerData = getRouterData(app);
  const UserLayout = routerData['/user'].component;
  const BasicLayout = routerData['/'].component;
  return (
    <LocaleProvider locale={zhCN}>
      <ConnectedRouter history={history}>
        <Switch>
          <Route path="/user" component={UserLayout} />
          <AuthorizedRoute
            path="/"
            render={props => <BasicLayout {...props} />}
            **authority={['admin', 'user','teacher']}**  ————所有权限
            redirectPath="/user/login"
          />
        </Switch>
      </ConnectedRouter>
    </LocaleProvider>
  );
}

common /menu.js 可以配置 **authority: 'admin'**,做权限辨识

**Comment by wscodinglover** [comment]
setAuthority 会将login时的权限保存到localstorage中，顶层路由中有个权限数组是判断准入原则的，进入后，路由配置menu中的权限是配置侧边栏的数据，权限匹配就展示，单个权限配置成字符串，多个权限配成数组，没有权限配置就是默认都加载

**Comment by LKCheng** [comment]
文档中说使用 localstorage 模拟权限角色,这个没有任何问题吧。确实是你用token 去取到用户权限后，然后保留就可以了，不知道你们的问题在哪里？我们公司的ERP信息平台，10多种身份的权限控制，以及内容板块的控制，都没啥问题。不得不说ant design 组件确实写的很不错。给力

**Comment by roc2539** [comment]
@yjy8749  你的权限是放在sessionStorage中的还是。 直接放到store里面的？

**Comment by roc2539** [comment]
@yjy8749 你每次需要权限更新的地方都重新取权限？还是在登录的时候缓存了权限？

**Comment by roc2539** [comment]
噢，明白了。 @yjy8749

**Comment by ilaipi** [comment]
![image](https://user-images.githubusercontent.com/1689135/39955668-9eddaa20-5605-11e8-848c-98346f3914bb.png)


根据我的思路实现了一个版本，[我的fork](https://github.com/ilaipi/ant-design-pro)

我去掉了原有的`Authorized`相关的组件，在`BasicLayout`中，传给`SiderMenu`的菜单配置，是经过`filter`的。

用户具有的权限，保存在`currentUser.privilage`（写错了，应该是privilege。。），这个值可以在用户登录后一并由后端返回。

**Comment by shadiniao** [comment]
@yjy8749 你这样存在变量中的实现跟存在sessionStorage中的效果是一样的吧.

在这个标签页中登录了,如果我copy路径,再打开一个新标签页又会跳到登录界面了.

我现在是把权限保存在cookie中了

**Comment by shadiniao** [comment]
@ilaipi antd pro这个demo判断的是角色,我觉得你不应该删掉Authorized相关组件,而是修改getRouterData方法,将方法中之前写死的路径和权限通过后端加载

**Comment by ilaipi** [comment]
@shadiniao 我要删掉`Authorized`相关的组件，我是改了整个的认证机制，不需要前端来对每个菜单再做权限判断。后端返回给前端的是完整的用户拥有的权限。所以过滤后的`menuData`，就是用户可操作的菜单，不再需要前端再根据角色来判断（不然前端还要维护菜单和角色的关系）。  

我觉得权限可以分两层来。一层是菜单级，就是用户能操作哪些菜单。第二层是每个菜单能操作的操作项，比如某个按钮要不要显示。第二层配置也让后端传过来。  

从更安全的角度，后端可以再对请求做一次权限认证。如果用户没有权限，可以返回`403`，前端统一处理，碰到`403`就跳转到登录。

**Comment by yjy8749** [comment]
@shadiniao 不会的，重新打开一个标签页的话，这时候会重新调用 fetchCurrent 重新初始化 Authorize

**Comment by mcmf** [comment]
@ilaipi  我也觉得应该后端处理  他们非把权限用前端处理  你这个影响面包屑吗

**Comment by ilaipi** [comment]
@mcmf 不影响的，你看我的截图，就是我实现出来的样子。最新的提交我已经修复了菜单老是不按照权限加载的问题。

**Comment by USTCLX** [comment]
@yjy8749 你好，按照你的这种方法，已经登陆成功后，刷新页面，此时先加载'./src/router.js'，里面使用了AuthorizedRoute组件来判断权限，并决定是否重定向至‘/user/login’，此时还来得及*fetchCurrent，因此AuthorizedRoute还没有被更新，因此，肯定会被重定向，无法做到记住登陆了。囧

**Comment by yjy8749** [comment]
@USTCLX 我这边是做了这样的处理的,如果 fetchCurrent 没有完成,整个页面都会显示加载中,只有等到 fetchCurrent 执行完成后, 才会渲染页面

**Comment by liuliansen** [comment]
权限就不应该由前端来控制

**Comment by elevensky** [comment]
> @shadiniao 我要删掉`Authorized`相关的组件，我是改了整个的认证机制，不需要前端来对每个菜单再做权限判断。后端返回给前端的是完整的用户拥有的权限。所以过滤后的`menuData`，就是用户可操作的菜单，不再需要前端再根据角色来判断（不然前端还要维护菜单和角色的关系）。
> 
> 我觉得权限可以分两层来。一层是菜单级，就是用户能操作哪些菜单。第二层是每个菜单能操作的操作项，比如某个按钮要不要显示。第二层配置也让后端传过来。
> 
> 从更安全的角度，后端可以再对请求做一次权限认证。如果用户没有权限，可以返回`403`，前端统一处理，碰到`403`就跳转到登录。

你这个也只是菜单的过滤，本地的routes，还是渲染了react-router-dome的Route的。

**Comment by ilaipi** [comment]
> > @shadiniao 我要删掉`Authorized`相关的组件，我是改了整个的认证机制，不需要前端来对每个菜单再做权限判断。后端返回给前端的是完整的用户拥有的权限。所以过滤后的`menuData`，就是用户可操作的菜单，不再需要前端再根据角色来判断（不然前端还要维护菜单和角色的关系）。
> > 我觉得权限可以分两层来。一层是菜单级，就是用户能操作哪些菜单。第二层是每个菜单能操作的操作项，比如某个按钮要不要显示。第二层配置也让后端传过来。
> > 从更安全的角度，后端可以再对请求做一次权限认证。如果用户没有权限，可以返回`403`，前端统一处理，碰到`403`就跳转到登录。
> 
> 你这个也只是菜单的过滤，本地的routes，还是渲染了react-router-dome的Route的。

那就是要想办法在渲染Route之前把权限加载进来。看看官方能不能支持从后端加载权限配置，可以选择是写在前端还是从后端获取
