### ISSUE TITLE
为什么在ant design  pro中更改端口号后会报错

### ISSUE THREAD

**Issue by pingGuoNiki** [ant-design/ant-design-pro#1311]
package.json中更改为 "start": "cross-env DISABLE_ESLINT=true set port=8008 && roadhog server",
启动服务后会报错 ，报错内容如下
 Line 113:  Expected linebreaks to be 'LF' but found 'CRLF'                              linebreak-style

**Comment by afc163** [comment]
```diff
- cross-env DISABLE_ESLINT=true set port=8008 && roadhog server
+ cross-env DISABLE_ESLINT=true port=8008 && roadhog server
```
