### ISSUE TITLE
项目中超过10kb的静态图片在编译后怎么访问呢

### ISSUE THREAD

**Issue by zhuaizhuaixi** [ant-design/ant-design-pro#1312]
超过10KB的图片会在build后出现在/dist/static目录下，当项目部署到服务器时，需要怎么访问static里的静态图片呢

另外，这个默认的10KB是否是可设置的呢，如果可以，需要再哪里设置呢？看了一些资料发现需要在webpack里修改，但项目使用的是roadhog，没找到可以设置url-loader的地方。请指教

**Comment by chenshuai2144** [comment]
会访问 /static/hash.img 的

**Comment by zhuaizhuaixi** [comment]
@chenshuai2144 
查看network后的确是访问了，但是报了404
访问的地址是 192.168.111.11:8086/static/name.hash.jpg
我的确将static目录放在与index.html同个目录下，但访问不到，需要在哪里配置static的访问地址吗

**Comment by chenshuai2144** [comment]
public  path  有这个选项的
