### ISSUE TITLE
目标：自定义左边导航图标

### ISSUE THREAD

**Issue by qingjiaowochengzd** [ant-design/ant-design-pro#1314]
import BizIcon from './myicon.js';
{
        name: '门店商品',
        path: 'storegoods',
        icon: <BizIcon type="dingdan" />,
},
在menu文件中引入icon组件，<BizIcon type="dingdan" />报错'React' must be in scope when using JSX (react/react-in-jsx-scope)，

看了源码getIcon注释说明：
// Allow menu.js config icon as string or ReactNode
//   icon: 'setting',
//   icon: 'http://demo.com/icon.png',
//   icon: <Icon type="setting" />
那我这么写应该没问题啊，求解，我在页面组件中这么引用是可以显示图标的。

**Comment by afc163** [comment]
需要在顶部加上 `import React from 'react'`

**Comment by qingjiaowochengzd** [comment]
@afc163 menuData的icon字段是不是不能这么写？icon： <BizIcon type="dingdan">
还是报错，语法报错  Unexpected token, expected "}"

**Comment by afc163** [comment]
你的 `：` 是中文冒号。

**Comment by afc163** [comment]
另外，建议使用 Ant Design Pro 前，先系统学习一下 React。
