### ISSUE TITLE
独立使用组件方式 的样式问题？

### ISSUE THREAD

**Issue by lusess123** [ant-design/ant-design-pro#1317]
独立使用组件，比如 TagSelect , 会引用antd 的默认样式，
`require('antd/lib/icon/style/css');

require('antd/lib/tag/style/css');`

这样导致的后果是， 无法做换肤功能 ？ 
而源码版并没有此问题，为什么独立发布包版要做这样的处理？

**Comment by chenshuai2144** [comment]
这个暂时没有解决办法。。。
虽然提供了 less 但是pro 依赖了 css.
无法实现你的功能了。你可以试试直接 copy 源码到自己的项目

**Comment by lusess123** [comment]
为什么不学antd  一样，把 样式和js  分开，这样也好换肤，另外 我独立使用pro的es6版本，编译不过去，无法编译jsx 语法 和 装饰器语法

**Comment by afc163** [comment]
less 的问题 v2 里应该解决的。@chenshuai2144

https://github.com/ant-design/ant-design-pro/issues/882#issuecomment-363337504

**Comment by chenshuai2144** [comment]
这个需求看来还是需要搞。
模仿 antd 搞一下

**Comment by lusess123** [comment]
为什么不支持  从npm 包直接源码打包， 我看 @vue/cli-service  就支持得很好， 可以  直接读取第三方包的.vue文件， 里面还支持ts ,tsx,less

**Comment by scfido** [comment]
这个问题目前没法解决，ant pro发布的代码中硬编码引用了ant的css，图标url已经写死了alicdn。已经在项目中去掉ant pro的组件了。

**Comment by afc163** [comment]
这是个大问题，@yesmeck @chenshuai2144 @ddcat1115 2.0 争取搞一个优雅的解决方案出来。

**Comment by lusess123** [comment]
直接换成less ,不就好了吗

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/173

看这里 ，问题很复杂的 不只是 less

**Comment by yoyo837** [comment]
Waiting for something new...

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/use-components-alone-cn#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD

试试 2.0.0-beta.1
`npm install ant-desgin-pro@beta --save`

**Comment by dyun8080** [comment]
@afc163 @chenshuai2144 @ 期待大神们的解决办法。 ^_^

**Comment by chenshuai2144** [comment]
2.0已发布
