### ISSUE TITLE
如何不用mock数据代理到服务器地址？

### ISSUE THREAD

**Issue by mantianrefeng** [ant-design/ant-design-pro#1319]
>>框架的数据来源是mock数据，
>>官方文档说：npm start:no-proxy可以进行代理，但运行这个命令的时候会有错误
>>我的配置是.roadhogrc.mock.js里面有个
![image](https://user-images.githubusercontent.com/25834502/38929135-ef7562c8-433d-11e8-95c1-68a344a0cbb2.png)
>>这个东西在括号里面加上我的服务器地址，但是并没有作用？
如何真正解决这个问题

**Comment by chenshuai2144** [comment]
start:no-proxy 不能使用吗？ 
报错是什么

**Comment by mantianrefeng** [comment]
![image](https://user-images.githubusercontent.com/25834502/38982480-89b123fc-43f4-11e8-97af-409a7ce3fa49.png)
>>是这个错误
>>但是后来经过尝试：用npm run start:no proxy可行

**Comment by qingjiaowochengzd** [comment]
也是这样

**Comment by ddcat1115** [comment]
`npm run start:no-proxy` run 不能省略
