### ISSUE TITLE
Antd-Pro 微信互助群

### ISSUE THREAD

**Issue by no13bus** [ant-design/ant-design-pro#132]
大家好，我是个后端工程师，因为业务需要最近开始写管理后台的页面，经由前端工程师介绍，接触了dva这个易于上手的框架，然后一路学习了ant-desgin, es6, react, redux等知识点。现在发现了ant-desgin-pro这个后台利器，觉得我们做后台的有福了。
然后我创建了一个群，想着对antd-pro感兴趣的同学可以进来一起讨论下，要是有能力和时间的话，还可以帮忙解决下issue，对自我的成长也是很有帮助的。
跟 @afc163  邮件沟通了下，得到其允许贴出这个issue。目前群人数已经超过100人了，如果想进群，请加我微信号(**no13bus**)，我拉你进去即可。

> 2017.11.18更新
原来的群快满500人了，新建了个群，目前可以扫码进，后面进不了的时候还是照常加我微信即可。
![](http://cdn.no13bus.com/17-11-25/88589319.jpg)

> 2017.11.25更新: 新增telegram入群链接  `https://t.me/joinchat/F9T5tkttuzZ6v9cmLj6Idg`

**Comment by no13bus** [comment]
目前群人数已经超过100人了，如果想进群，请加我微信号(no13bus)，我拉你进去即可。

**Comment by Lyndon001** [comment]
Give Me Five
他救不如自救，👍思考和行动

**Comment by no13bus** [comment]
@Lyndon001 来来来。进群说。

**Comment by Alixiaodian** [comment]
求更新二维码，求拉群

**Comment by LJerRRy** [comment]
@no13bus 过期了，加不了了，求加微信

**Comment by Frank1e0927** [comment]
求加微信。求更新一次

**Comment by no13bus** [comment]
@LJerRRy @Frank1e0927 看issue里面的信息就知道了

**Comment by Yuanwei1992** [comment]
进不了  求加微信

**Comment by LJerRRy** [comment]
@Yuanwei1992 请加微信号no13bus
