### ISSUE TITLE
与后台数据连接问题

### ISSUE THREAD

**Issue by CherryaMao** [ant-design/ant-design-pro#1320]
当修改.roadhogrc.mock.js 为
export default {
  'GET /(.)': '192.168.1.102:8080/ ',
  'POST /(.)': '192.168.1.102:8080/',
};时Visual Studio Code编辑器提示我下面这个错
Error occurred while trying to proxy request /currentUser from localhost:8000 to 192.168.1.102:8080/ (ENOTFOUND)；
也修改了.roadhogrc中的
"proxy": {
  "/api": {
    "target": "192.168.1.102:8080/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  },还是不能请求到数据。
怎么样才能接上真实的后台数据？

**Comment by CherryaMao** [comment]
加上之后Visual Studio Code编辑器  不   提示我下面这个错
Error occurred while trying to proxy request /currentUser from localhost:8000 to 192.168.1.102:8080/ (ENOTFOUND)；
但是还是没有跟后台链接起来。能告诉我还有没有其他什么地方要改的。

**Comment by lyingd** [comment]
没有更多消息吗？404或者其他的

**Comment by CherryaMao** [comment]
没有其他什么消息，我是不是改了以上讲的两个文件后，是不是我的 Request URL: 该路径应该变成我的http：//192.168.1.102:8080,但是没有变，所以我想说是不是这个代理没有改成功？

**Comment by lyingd** [comment]
这个代理是前台数据发到代理，代理转发给真正的服务器，对于前台来说，是透明的，只改proxy应该就好了

**Comment by chenshuai2144** [comment]
你的错误应该是和192.168.1.102 联通不了造成的

**Comment by CherryaMao** [comment]
你的意思是说是因为没有和 http://192.168.1.102/ 这个链接上才没有获取到数据的吗？

**Comment by mushroomlb** [comment]
npm run start:no-proxy
