### ISSUE TITLE
 新增models和service需要配置什么吗？

### ISSUE THREAD

**Issue by Uhaiping** [ant-design/ant-design-pro#1322]
新增models和service需要配置什么吗？我新增后不能请求到models中的数据

**Comment by chenshuai2144** [comment]
不需要配置的。。。
只需要注意一下增加路由的时候载入一下！

`component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/BasicForm')`

form 就是你的 model 名字

**Comment by Uhaiping** [comment]
嗯，谢谢，刚自己摸索出来了
