### ISSUE TITLE
想把 0.1 脚手架生成的项目升级为 1.0 脚手架生成的代码，有升级指南吗？

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design-pro#1326]
需要把一个 0.1 版本的项目和 1.0 版本的项目做整合，
所以需要把 0.1 版本的项目进行代码升级，有升级指南吗？

**Comment by chenshuai2144** [comment]
现在是没有的。。。
路由改动很大。
可以看看别的 issue 里面的土办法
