### ISSUE TITLE
.webpackrc.js 中env 下的参数如何获取？

### ISSUE THREAD

**Issue by yanweitao** [ant-design/ant-design-pro#1327]
.webpackrc.js 中env下的参数可以自定义吗？比如说我像把server端的请求域名放在这里，根据环境的不同可以拿到不同的域名。可以做吗？
如果可以，那如何获取.webpackrc.js中env 下的参数？如何指定加载的环境

**Comment by packjie** [comment]
我也有这个问题，您解决了吗？

**Comment by chenshuai2144** [comment]
当前 node.js 使用就好了
