### ISSUE TITLE
为什么在request.js里面的store只能在fetch.catch里面用？

### ISSUE THREAD

**Issue by Hadroning** [ant-design/ant-design-pro#1329]
为什么在request.js里面的store只能在fetch.catch里面用？
在request方法里面打印store为undefined，但是当请求出现问题在catch里面就能获取到store，这是为什么
![1524157665320](https://user-images.githubusercontent.com/20159065/39007130-a829d2f0-4437-11e8-8d96-495fdfad7bd1.jpg)

**Comment by Hadroning** [comment]
。。。没人么

**Comment by chenshuai2144** [comment]
因为还没初始化成功
都是异步的

**Comment by Hadroning** [comment]
那需要怎么写才能在request方法里使用呢🤕

**Comment by chenshuai2144** [comment]
不推荐直接在request 中使用。。。你是什么场景？

**Comment by Hadroning** [comment]
想dispatch一个全局的loading状态，每次在action里put loading有点麻烦...

**Comment by chenshuai2144** [comment]
dva-loading 有这个库的，用它就好了

**Comment by Hadroning** [comment]
谢谢，我去看看

**Comment by codercatmomi** [comment]
我要在 request 文件里面加一个 “
凡是任意接口返回 某个code,
都请求 dispatch({ type: 'login/loginout'})
"
要怎么做呢
