### ISSUE TITLE
New Component EllipsisText

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#133]
http://plus.antd.alipay.net/?selectedKind=EllipsisText%20%E6%96%87%E5%AD%97%E7%9C%81%E7%95%A5%E6%98%BE%E7%A4%BA&selectedStory=%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B&full=0&down=0&left=1&panelRight=0

<img width="268" alt="image" src="https://user-images.githubusercontent.com/507615/32527446-fc675c74-c468-11e7-90c4-dd227bbedc87.png">

https://www.npmjs.com/package/react-multiline-ellipsis
https://www.npmjs.com/package/react-lines-ellipsis
https://github.com/CezaryDanielNowak/React-dotdotdot

There will be a tooltip to show rest word when hover `...`.

**Comment by nikogu** [comment]
👍

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/pull/135
