### ISSUE TITLE
热加载重新编译慢

### ISSUE THREAD

**Issue by zsux** [ant-design/ant-design-pro#1333]
现在已经用ant-design-pro做实际项目了,对我们项目提升很大,但最大的问题在于,随着我们写的业务模块的增加,热加载一次非常慢,请问这个如何破?

**Comment by afc163** [comment]
尝试开启动态加载。

**Comment by zsux** [comment]
@afc163 动态加载 怎么开?

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD

**Comment by zsux** [comment]
我说的是 热加载重新编译慢 不是动态加载

**Comment by shizhiqian** [comment]
@zsux 我也遇到这个问题了,请问你是如何解决的? 上面的连接打不开了

**Comment by fuxiangduan** [comment]
me too 改下代码好久才能看到效果 痛苦。。。

**Comment by MEEllis** [comment]
我也是， 改一下代码，需要10~12秒才生效 ， 真心痛苦 @fuxiangduan

**Comment by callmez** [comment]
热编译是真的效率差. 为此我还从 13 Air 换了新的15 rmbp.  开发时照样风扇飞转.   有时甚至卡到代码都写不懂.  真的需要考虑下优化编译效率.

**Comment by callmez** [comment]
可以开启这个issue么

**Comment by secreter** [comment]
mark,体验了一下确实慢

**Comment by myemperor** [comment]
都这个年代了，慢的让人崩溃
