### ISSUE TITLE
修改了登陆请求的URL和MOCK文件中对应的URL后，404了

### ISSUE THREAD

**Issue by zuwensong** [ant-design/ant-design-pro#1334]
修改services/app.js中的fakeAccountLogin请求URL： /api/login/account 改成 /api/login/account1
对应的.roadhogrc.mock.js的请求路径也修改，从 POST /api/login/account 改成 POST /api/login/account1
然后登陆的时候就报404找不到资源了，请问还有哪个地方欠考虑了吗

**Comment by chenshuai2144** [comment]
show code

**Comment by zuwensong** [comment]
.roadhogrc.mock.js這個改了之後沒有重新啓動，導致了404
