### ISSUE TITLE
Circular dependency detected 警告 ！

### ISSUE THREAD

**Issue by billgo** [ant-design/ant-design-pro#1336]
已经排查出了原因是入口文件 `export default app._store` 被 `utils/request` 引用了，
`request -> services -> models -> index -> request `，
这里会引发一个 Circular dependency detected 警告，
有什么思路可以解决掉 ？

**Comment by chenshuai2144** [comment]
你可以把 app._store 放到另外的地方。。。
理论上不会循环引用的。
这些都是有先后的

**Comment by billgo** [comment]
@chenshuai2144 但是这个app 是在 index 入口文件里面初始化出来的，不管是放在哪都会引发这个循环引用吧。除非还有别的机制能拿到这个 store.

**Comment by chenshuai2144** [comment]
用 connect 也可以拿到的。
