### ISSUE TITLE
文件更新后页面反应不过来，还是之前的代码导致报错

### ISSUE THREAD

**Issue by qingjiaowochengzd** [ant-design/ant-design-pro#1339]
![222](https://user-images.githubusercontent.com/30749028/39081741-36dc2dc6-4579-11e8-8262-e17c86b426ce.png)
就比如我想打印的数据是platformList，但编译出来的一直是platformL,然后就一直报错，刷新也没用，要重启服务

**Comment by mutouzdl** [comment]
我也经常遇到，通常是两次修改间隔太短的时候会出现，有点难受

**Comment by chenshuai2144** [comment]
这个是浏览器机制和 roadhog 共同作用的原因。
可能需要清空一下缓存什么的。。。
尽量写好之后再 save
