### ISSUE TITLE
【建议】关于引入dva-loading的建议

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design-pro#134]
import createLoading from 'dva-loading';

// 2. Plugins
app.use(createLoading());

现在所有的model都在自己管理loading，建议尽早引入loading管理器，让已经入坑的开发者能与ant-design-pro的代码尽量的保持同步更新。

**Comment by afc163** [comment]
dva-loading 的 loading 不够精确，如果做全局 loading 是没问题，精确到区块还是需要自己管理状态。

**Comment by liumin1128** [comment]
dva-loading可以精确到effect，还挺方便的
```
   addDescLoading: state.loading.effects['agent/addAdminDesc']
```

**Comment by afc163** [comment]
暂时先不考虑。

**Comment by gebilaoman** [comment]
已经增加
