### ISSUE TITLE
更新版本 ie 登录页面显示异常

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design-pro#1342]
直接上图
![qq 20180423094756](https://user-images.githubusercontent.com/34823990/39103228-15604f4c-46dc-11e8-92f0-e1cf85427071.png)
![qq 20180423094816](https://user-images.githubusercontent.com/34823990/39103229-15ad61ec-46dc-11e8-856e-3617bb19e601.png)

**Comment by MinHongwei** [comment]
第一个ie 11  第二个 谷歌

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1172
