### ISSUE TITLE
请教下：Link 组件 与 路由跳转 刷新页面问题

### ISSUE THREAD

**Issue by robin536180** [ant-design/ant-design-pro#1343]
Link 组件链接的地址  与 当前页面的地址 相同，但是参数有变化，页面还是不能刷新，只是地址栏url变了，页面并没有因为url的参数变化而重新加载页面。 @andriijas @sorrycc @luolonghao             

1. 例如 页面当前 url : localhost:8000/#/user/123/info
   <Link to={'/user/344/info'}>AAA</Link>
   点击link的时候 只是 url变成  localhost:8000/#/user/344/info 但是没有发送请求 只是url变了
   所以 想 请教下，有没有好的方法处理

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1138
