### ISSUE TITLE
The new decorators proposal is not supported yet

### ISSUE THREAD

**Issue by captain-xu** [ant-design/ant-design-pro#1344]
You must pass the `"legacy": true` option to `@babel/plugin-proposal-decorators`

**Comment by xjchenhao** [comment]
我也遇到了 什么情况。。 不会要去改`node_modules`里的代码吧？

**Comment by sam-dingkang** [comment]
今天刚发现，不知道是不是这个babel-plugin-transform-decorators-legacy插件升级了，我去找官方同学看下

**Comment by acpplife** [comment]
同问~

**Comment by captain-xu** [comment]
change the roadhog version to  2.2.0, and try again @xjchenhao @sam-dingkang @acpplife

**Comment by xjchenhao** [comment]
= = 着不算解决了吧 希望官方能够看到 在下一版中能够修复。

**Comment by sam-dingkang** [comment]
已经修复了，https://github.com/sorrycc/roadhog/issues/682
