### ISSUE TITLE
启动报错 error

### ISSUE THREAD

**Issue by sam-dingkang** [ant-design/ant-design-pro#1346]
早上先出现这个，https://github.com/sorrycc/roadhog/issues/682 ，然后现在

![image](https://user-images.githubusercontent.com/15643321/39107541-a167b48a-46f5-11e8-932e-a98916c0ed43.png)
cnpm install 
cnpm  start 

![image](https://user-images.githubusercontent.com/15643321/39107607-f2f46f0a-46f5-11e8-8856-299da8479a9b.png)

**Comment by hnsylitao** [comment]
我也是，@babel 蛮多插件 解析器升级了 从 7.0.0-beta.44 到 7.0.0-beta.45 所以出现了这个问题

**Comment by sam-dingkang** [comment]
@hnsylitao 我看你在roadhog那边提了issue,The new decorators proposal is not supported yet. You must pass the `"legacy": true`这个解决了吗？pro依赖了这个

**Comment by sorrycc** [comment]
## 2. Property right of AssignmentExpression expected node to be of a type ["Expression"]

### 报错

```
Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
```

### 解决

删除 `.webpackrc.js` 里的 `transform-decorators-legacy`。

### 参考

https://github.com/ant-design/ant-design-pro/pull/1345
