### ISSUE TITLE
如何将未登录用户和已登录用户访问的页面拆分到不同的js中？

### ISSUE THREAD

**Issue by yijingping** [ant-design/ant-design-pro#1348]
目前Pro版本，使用 [按需加载](https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD)，routes下面的文件会被拆分按需加载，但是model和service文件会被打包进index.[hash].js。  
所以即使是未登录用户，也可以看到service里面的所有api接口，这样给恶意用户暴露了太多的信息，降低了分析的门槛。 参考文章：[现代前端框架的信息泄露问题
](https://0x0d.im/archives/info-leak-problem-in-modern-front-end-framework.html)

请问，如何将未登录用户和已登录用户访问的页面拆分到不同的js中？
我看到webpack支持多页面入口的功能，可以实现。 但在Pro中，具体该如何配置呢？

**Comment by chenshuai2144** [comment]
这个不应该是前端考虑的问题。
后端会做相应的处理。方法更多更安全。前端代码默认就是完全暴露的
