### ISSUE TITLE
请问这个脚手架有eslint语法检查吗？ 为什么我自己写的组件每次commit都会报错，如果有，如何关闭呢？

### ISSUE THREAD

**Issue by blockmood** [ant-design/ant-design-pro#1352]
补充一下截图
![1c5f03b8-da7c-4248-8a67-bf10d8e227a5](https://user-images.githubusercontent.com/22879524/39161185-1400d394-47a2-11e8-9853-0ee0fd8cd690.png)

**Comment by pkaq** [comment]
参考 `package.json`中的"precommit": "npm run lint-staged",

**Comment by afc163** [comment]
http://pro.ant.design/docs/faq
