### ISSUE TITLE
登录权限的问题

### ISSUE THREAD

**Issue by anghuang** [ant-design/ant-design-pro#1354]
开发中需要从后台拿到token，如果token失效的话直接跳转到登录页，而不是现在只要localStorage保存有就直接跳转到图表页，如果在AuthorizedRoute配置authority为一个Promise的话，接口写在Promise里面也只会调用一次，怎么做这方面的验证token是否失效

**Comment by chenshuai2144** [comment]
你可以不要保存在localStorage。
没有权限的时候让后台给一个401  如果是401 你跳转去登录如何。
![image](https://user-images.githubusercontent.com/8186664/39163418-f726d4ac-47ac-11e8-978f-ef3b27949d7f.png)

**Comment by anghuang** [comment]
我是在AuthorizedRoute配置authority为一个Promise，然后在PromiseRender里面写了一个全局的判断接口，每次都会调用一次这样的，成功了，你的这种的话，感觉有点麻烦

**Comment by chenshuai2144** [comment]
后台工作量比较大。前端就是一个401判断

**Comment by WuJiY** [comment]
![image](https://user-images.githubusercontent.com/183884/39193526-5ac1a8f0-480e-11e8-8333-3b43140c2e71.png)
超时这边跳不过去
![image](https://user-images.githubusercontent.com/183884/39193598-8597a656-480e-11e8-8257-efdd423ffc0e.png)

**Comment by Nuoky** [comment]
token过期时还是会进入页面“闪一下”后才会被后端返回的401退回登录界面，体验不是很好...
