### ISSUE TITLE
pro new 在windows下无法使用

### ISSUE THREAD

**Issue by zlq960222** [ant-design/ant-design-pro#1356]
![f36ec044-3408-45b7-af15-c58197d63818](https://user-images.githubusercontent.com/23473716/39162291-674af9a8-47a7-11e8-8f43-dbd88771cf5d.png)

pro new的时候出现如图问题 如何解决？

**Comment by chenshuai2144** [comment]
先全局安装一下 roadhog

**Comment by zlq960222** [comment]
![201803931](https://user-images.githubusercontent.com/23473716/39164877-4a1c7be2-47b4-11e8-8c6b-1b5d693fec56.jpg)
全局安装roadhog后仍然无法启动

**Comment by zlq960222** [comment]
并且之前的项目重新安装依赖包后启动报错
![02b6812b-7bdb-410b-a8bb-7b7f80f3c9cc](https://user-images.githubusercontent.com/23473716/39164975-c616bfb4-47b4-11e8-8b70-fbfd7e86c9f9.png)

**Comment by chillyistkult** [comment]
@ziq960222 Just update ant-design-pro. Your error was fixed in #1345.
