### ISSUE TITLE
Authorized组件中PromiseRender组件源码分析遇到难点，求大神指导

### ISSUE THREAD

**Issue by Joyeuxman** [ant-design/ant-design-pro#1357]
//以下代码位于Authorized组件中PromiseRender文件中，  由于该PromiseRender组件render中根据起组件内部状态state中component的有无判断渲染Component还是div>Spin，而Component属性会在componentDidMount和componentWillReceiveProps生命周期中分别进行设置，处理如下：
将正常渲染和异常渲染的内容都判断一下是否实例化，根据React.isValidElement来判断传递进来的渲染内容是否为React元素，若为React元素可以直接渲染，如果不是React元素，是React组件之类的，要将其放入函数中返回其组件。问题就在这个地方，为什么所传递进来的渲染内容是一个组件的话，为什么不能直接进行渲染，而是要将其放入一个函数中并返回呢？
我不知道以上分析是否正确，哪位大神指导下，多谢！
// Determine whether the incoming component has been instantiated
  // AuthorizedRoute is already instantiated
  // Authorized  render is already instantiated, children is no instantiated
  // Secured is not instantiated
  checkIsInstantiation = target => {
    if (!React.isValidElement(target)) {
      console.log(`${target}组件不是一个合法的React元素，即用React.createElement来创建的元素`)
      return target;
    }
    return () => target;
  };

**Comment by chenshuai2144** [comment]
先去学习一下 markdown

**Comment by Joyeuxman** [comment]
> 以下代码位于Authorized组件中PromiseRender文件中， 由于该PromiseRender组件render中根据起组件内部状态state中component的有无判断渲染Component还是div>Spin，而Component属性会在componentDidMount和componentWillReceiveProps生命周期中分别进行设置，处理如下：
 将正常渲染和异常渲染的内容都判断一下是否实例化，根据React.isValidElement来判断传递进来的渲染内容是否为React元素，若为React元素可以直接渲染，如果不是React元素，是React组件之类的，要将其放入函数中返回其组件。问题就在这个地方，为什么所传递进来的渲染内容是一个组件的话，为什么不能直接进行渲染，而是要将其放入一个函数中并返回呢？
 我不知道以上分析是否正确，哪位大神指导下，多谢！
```
  // Determine whether the incoming component has been instantiated
  // AuthorizedRoute is already instantiated
  // Authorized render is already instantiated, children is no instantiated
  // Secured is not instantiated
  checkIsInstantiation = target => {
    if (!React.isValidElement(target)) {
        console.log(${target}组件不是一个合法的React元素，即用React.createElement来创建的元素)
        return target;
      }
      return () => target;
 };
 ```

**Comment by Joyeuxman** [comment]
第一次提问题，忘记还有md语法，不好意思

**Comment by chenshuai2144** [comment]
你可以删掉试一试，会报错的。
`Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`

**Comment by Joyeuxman** [comment]
>Component 作为组件来使用时即<Component />形式的时候，Component可以为两种形式
- 1、不合法的React元素即React.isValidElement('test') === false;
- 2、函数中返回合法React元素


可以这样理解吗？

 ```
    const ReactElement =  React.createElement(
      'div',
      null,
      'test'
    )
    const FuncElement = ()=>{
      return 'test';
    }
    class ReactComponent extends PureComponent {
      render(){
        return 'test';
      }
    }
    console.log(React.isValidElement('test'));//false
    console.log(React.isValidElement('<span>test</span>'));//false
    console.log(React.isValidElement(FuncElement));//false
    console.log(React.isValidElement(ReactComponent));//false
    console.log(React.isValidElement(<span>test</span>));//true
    console.log(React.isValidElement(ReactElement));//true
