### ISSUE TITLE
为什么使用的antd-pro代码回访问网址https://kcart.alipay.com/web/bi.do

### ISSUE THREAD

**Issue by naWang1227** [ant-design/ant-design-pro#1358]
为什么使用的antd-pro代码回访问网址：https://kcart.alipay.com/web/bi.do?BIProfile=merge&d=%5B%7B%22pg%22%3A%22http%3A%2F%2Flocalhost%3A8000%2F%23%2Ffirst%22%2C%22r%22%3A1524538780191%2C%22g2%22%3Atrue%2C%22version%22%3A%223.0.5-beta.4%22%2C%22page_type%22%3A%22syslog%22%7D%5D

**Comment by chenshuai2144** [comment]
打点.
为了更好服务用户，G2 会将打点监控，将 URL 等信息发送回 AntV 服务器，BizCharts 没有关闭这个请求：https://kcart.alipay.com/web/bi.do

**Comment by naWang1227** [comment]
明白了，谢谢咯！

**Comment by afc163** [comment]
@naWang1227 我没明白

**Comment by naWang1227** [comment]
track(false);  关闭那个请求不就可以了。

**Comment by afc163** [comment]
那就是我们没问题，你自己本地删掉了这行代码是么？

**Comment by naWang1227** [comment]
是的。是我本地没有加这行代码的原因。嘿嘿，多谢啦

**Comment by chenshuai2144** [comment]
我们需要默认关掉吗？BizCharts 关一下就好了
