### ISSUE TITLE
代理到正式接口后， 后台$_POST HE &_FILES都接受不到参数，  content-type都设置正确的

### ISSUE THREAD

**Issue by yxz13918824623** [ant-design/ant-design-pro#1360]
![image](https://user-images.githubusercontent.com/38681825/39169222-91efb5aa-47c9-11e8-9fd6-9f0f562e5c19.png)

**Comment by chenshuai2144** [comment]
上传文件好像一直有问题，看看相关的 issue 吧。

**Comment by yxz13918824623** [comment]
网上没有相关的解决办法，现在能想到的就是这一块iframe一个单独的页面进来，估计是roadhog里面的问题，你们这个问题近期考虑修复么
