### ISSUE TITLE
npm start Failed to compile

### ISSUE THREAD

**Issue by dragonishare** [ant-design/ant-design-pro#1362]
@sorrycc 
使用命令行工具ant-design-pro-cli，在本地clone了ant design pro项目代码，本地开发完之后，提交到github,在另外一台电脑上拉去代码，npm install 之后，npm start报如下错误：

Failed to compile.

./src/routes/List/CardList.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
at Array.map ()

![image](https://user-images.githubusercontent.com/5707662/39170179-2b4cd310-47cd-11e8-8e09-00c0ab0f13e1.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/1345
