### ISSUE TITLE
ie10 兼容性报错

### ISSUE THREAD

**Issue by myGitZone** [ant-design/ant-design-pro#1363]

**Comment by chenshuai2144** [comment]
请补充说明

**Comment by myGitZone** [comment]
Warning: The <AuthorizedRoute /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change AuthorizedRoute to extend React.Component instead.

**Comment by myGitZone** [comment]
![ie10](https://user-images.githubusercontent.com/19903630/39171073-4ed781d8-47d0-11e8-9455-afe7972c6b54.png)

**Comment by myGitZone** [comment]
我只是想了解下这个是不是因为某个插件升级造成的，前段时间是没问题。谢谢

**Comment by afc163** [comment]
@myGitZone 帮助排查一下吧，抱歉没有精力提供支持。
