### ISSUE TITLE
侧滑菜单最顶部的文字在哪里修改？

### ISSUE THREAD

**Issue by LPJXLOVE** [ant-design/ant-design-pro#1366]
侧滑菜单最顶部的默认文字"ant design pro"在哪里修改？,找了半天。。。。

**Comment by chillyistkult** [comment]
In `src/components/SiderMenu/SiderMenu.js`. You can also just search for "Ant Design Pro" in the source code and you will see where it is defined.

**Comment by afc163** [comment]
不要问这种问题。
