### ISSUE TITLE
roadhog搭建工具很多BUG，许多语法和作用域的错误要到实际用户点击了才会报错，希望能改进

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design-pro#1368]
我目前遇到的问题如下：
1. 语法和作用域明显错误的情况，不能及时全屏显示错误，而是要等到执行到该代码（比如点击事件）才报错
2. 模块更改的时候没有反应，我采用的是linux Ubuntu LTS16.04的操作系统，不知道是不是fs.watch这个问题
3. 修改代码的时候 dynamic require的对应组件，修改居然不能对roadhog进行触发重新compile
4. 在浏览器查看的代码没有map.js，看得代码的确不太方便，debugger也很痛苦

希望能改进，谢谢！

**Comment by chenshuai2144** [comment]
去roadhog 提问吧。 你提到的问题。issue 里面有解决的办法
