### ISSUE TITLE
BasicLayout.js里的getBashRedirect可以改成更少的代码？

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design-pro#1370]
new URL() 只对BrowserHistory有效 。
在BrowserHistory情况下，始终重定向到`/dashboard/analysis`。
在HashHistory情况下，只要在url后不加`?redirect`也始终会重定向到`/dashboard/analysis`。
即便在HashHistory情况下，url后加了redirect也删除redirect。
这样`const redirect = urlParams.searchParams.get('redirect')`没有作用。
方法`getBashRedirect`可以再优化

**Comment by chenshuai2144** [comment]
欢迎 pr
