### ISSUE TITLE
在运行时候遇到【分配表达式的属性】的问题

### ISSUE THREAD

**Issue by YoRenChen** [ant-design/ant-design-pro#1371]
情景：在运行之后会出现如下报错
`
./src/routes/Exception/triggerException.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)
`
  ##这个模块是自身携带，查询一些资料说是babel编译问题，但不排除是否存在“魔术手”的操作方法或者其他。是否大家也有遇到这种情况？

**Comment by chenshuai2144** [comment]
注意看 issue。。。
这个问题被问了好几遍了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/1345
