### ISSUE TITLE
Silder菜单是从后台接口取得，如何能和组件关联到一起？

### ISSUE THREAD

**Issue by cytGitHub** [ant-design/ant-design-pro#1372]
我的菜单是从后台接口取的，我想把取回来的菜单 关联到组件上，应该如何操作？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/v2/src/layouts/LoadingPage.js

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/388d804ec083aa648dc2f3d0f44c2d817fa0a32a/src/layouts/LoadingPage.js#L90
