### ISSUE TITLE
将项目build完之后放在tomcat上运行，首页找不到构建后的css文件

### ISSUE THREAD

**Issue by xzk821649509** [ant-design/ant-design-pro#1373]
今天把项目做好了，想把项目build完后放到tomcat运行，结果访问发现一片空白。原来是构建后的index.html找不到css。
如图
![image](https://user-images.githubusercontent.com/28725954/39232799-11d92f80-48a1-11e8-938e-889b7911f553.png)
回去看了构建好的index.html文件 发现它是这样加载的css的
`<link href="/index.c0a6e2df.css" rel="stylesheet">`
但是我是讲构建好的文件发布到app这个文件夹里
css要`<link href="/app/index.c0a6e2df.css" rel="stylesheet">`才能取到
请问作者要怎么修改？

**Comment by xzk821649509** [comment]
并且我还发现如果我改了.webpackrc.js文件里面的`publicPath: "./",` 就会出现以下情况
![image](https://user-images.githubusercontent.com/28725954/39238170-26477080-48b0-11e8-9341-f48be57bc262.png)

**Comment by chenshuai2144** [comment]
不能这么写的。。 改成 '/app'之类的
相对路径很容易挂

**Comment by xzk821649509** [comment]
但是改成/app之后 我在本地编译后又不能加载到css和js

**Comment by chenshuai2144** [comment]
做个判断就好了。判断是  开发环境还是生产环境

**Comment by xzk821649509** [comment]
`export default {
  entry: "src/index.js",
  define: {
    'process.env': {},
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.API_ENV': process.env.API_ENV,
  },
  extraBabelPlugins: [
    "transform-decorators-legacy",
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],
  env: {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    }
  },
  ignoreMomentLocale: true,
  theme: "./src/theme.js",
  html: {
    "template": "./src/index.ejs"
  },
  publicPath: "./",
  disableDynamicImport: false,
  hash: true
}`
我按之前的一个讨论区去设置开发环境 在本地运行是没问题的 但我放到测试环境就出现问题了 
![image](https://user-images.githubusercontent.com/28725954/39238660-64ffa71a-48b1-11e8-9e2c-32c01bce2345.png)

**Comment by xzk821649509** [comment]
我想问清楚，这个方向究竟是否可行，编译好的静态资源是否可以放在tomcat上运行？

**Comment by afc163** [comment]
https://stackoverflow.com/questions/40030580/how-to-run-a-react-app-on-tomcat
