### ISSUE TITLE
独立使用组件的问题

### ISSUE THREAD

**Issue by SadCreeper** [ant-design/ant-design-pro#1374]
![image](https://user-images.githubusercontent.com/19741140/39235895-ca951608-48a9-11e8-9d0e-901c698f2d50.png)
如上图，使用按需加载的方式引入独立组件，但是多了3M多..是怎么回事？没有按需加载吗？

把第二行注释掉，会少3M多
```
import { ChartCard, Field, MiniArea } from 'ant-design-pro/lib/Charts';
```

第三行的 antd 同样的写法就实现了按需加载

**Comment by afc163** [comment]
因为 Charts 就是有这么大。

**Comment by chenshuai2144** [comment]
我们用的g2  g2 很大。
