### ISSUE TITLE
antd pro中 假数据和真数据如何自由切换

### ISSUE THREAD

**Issue by curry-wxj** [ant-design/ant-design-pro#1375]
.roadhogrc.mock 中 	'GET /api/waterQualmock': mockData,  //定义api
services 中 
import request from '../utils/request';
export async function otherCharge(params) {
  params.operType = 'getOtherExpenses';
  return http.post({
    svn: 'JSYY_SVR',
    path: 'other-expenses-manage.do',
    data: params,
  });
  // return request('/api/otherChargeMock'); // 假数据
}
这样只能通过 注释掉services层中的假数据 改为post请求。来切换 假数据， 这样services层所有的数据切换都要 这样很麻烦，请问一下如何一次性切换所有的假数据

**Comment by chenshuai2144** [comment]
start:no-proxy
