### ISSUE TITLE
求助： 如何修改Basiclayout中enquireScreen触发时的尺寸？

### ISSUE THREAD

**Issue by Ykeng** [ant-design/ant-design-pro#1376]
![image](https://user-images.githubusercontent.com/13504029/39237943-907e59a6-48af-11e8-85db-96e5c04bfa96.png)

目前似乎当屏幕尺寸小于768时，会触发 **enquireScreen** 方法，假如触发时机是860 或者其他值时，该如何修改？

不知是否写法错误，尝试覆盖default.less 中`@screen-md` 没有效果 

谢谢~

**Comment by chenshuai2144** [comment]
https://github.com/jljsj/enquire-js
