### ISSUE TITLE
AntD-pro requires bizcharts-plugin-slider, but the version of react conflict.

### ISSUE THREAD

**Issue by iofu728** [ant-design/ant-design-pro#1377]
As we can see, for AntD-Pro，We need dependency 
> "bizcharts-plugin-slider": "^2.0.1",

and
> "react": "^16.2.0",

But for bizcharts-plugin-slider, We need another dependency

> "react": "^15.0.0 || ^16.0.0"

Now, It maybe have no way to solve this problem, Can you broaden the limit of react version?
Thank you!

**Comment by chenshuai2144** [comment]
https://github.com/alibaba/BizCharts/issues/287
