### ISSUE TITLE
【建议】手机端界面的菜单最好能缺省隐藏起来

### ISSUE THREAD

**Issue by huangxingpark** [ant-design/ant-design-pro#138]
手机端展示界面：

![_-_ant_design_pro](https://user-images.githubusercontent.com/8498206/32536405-58ecdb9c-c499-11e7-9ea6-1281ffa2df14.jpg)

这样比较占地方。

建议类似这样：

![antd_admin1](https://user-images.githubusercontent.com/8498206/32536431-731ae770-c499-11e7-88ac-7d5729970869.jpg)

![antd_admin](https://user-images.githubusercontent.com/8498206/32536433-76f11e00-c499-11e7-94df-3beb7036b5e5.jpg)

**Comment by afc163** [comment]
可以考虑。

**Comment by szwork2013** [comment]
确实应该采纳！

**Comment by Lyndon001** [comment]
@momozzzxy

**Comment by chenshuai2144** [comment]
#463  这个算不算解决了?

**Comment by afc163** [comment]
对，已经解决。
