### ISSUE TITLE
只能加载 less 不能加载 css 吗？

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#1381]
pro 使用了 xterm.js ，运行之后发现 css 文件没有被加载，是不是只能加载 less， 而不是加载 css 文件呢？

**Comment by chenshuai2144** [comment]
你是在 js 里面 import 的 css 吗？
如果是可能是被 css_module搞掉了

**Comment by afc163** [comment]
如果不是 pro 自身代码导致的，你需要自己排查了。有需要改进的地方欢迎 PR。

**Comment by FunnyWolf** [comment]
> @chenshuai2144 直接 `npm install xterm --save` 的。

你好,请问这个问题找到解决方案了吗?
