### ISSUE TITLE
How do I send custom data in goBack method like push and replace methods?

### ISSUE THREAD

**Issue by qqnp1100** [ant-design/ant-design-pro#1382]
A->B->C
怎么回退后获取上一个页面的数据？（返回到B时获取C的数据）

尝试过使用`replace()`,虽然可以把数据传递到上一个界面，但是在返回的时候就要`goback()`两次，放弃。。

在C中`this.props.dispatch(routerRedux.push('/b',data));`
B中可以通过location获得数据，但是需要点2次返回才到A。

通过redux是可以，但是挺麻烦，有没有好的实现?

**Comment by chenshuai2144** [comment]
复杂数据 redux 是最好的 最优的实现。
如果只是一个简单字符串，可以试试 url 参数

**Comment by qqnp1100** [comment]
比如很多表单都要联系人选择，选择完之后返回上一界面更新选择的联系人。
@chenshuai2144 怎么返回时通过url传参？

**Comment by chenshuai2144** [comment]
[React-router  路由参数](https://reacttraining.com/react-router/web/example/url-params)
上不了请翻墙

**Comment by qqnp1100** [comment]
@chenshuai2144 
这个我知道，只能跳到下一个界面传值啊。。。
好像不能返回上一层路由传值吧
