### ISSUE TITLE
ant-design 与 ant-design-pro 区别

### ISSUE THREAD

**Issue by lnz604429058** [ant-design/ant-design-pro#1383]
如何在现有antDesign 项目中使用 ant-design-pro.
ant-design与ant-design-pro区别

**Comment by afc163** [comment]
RTFM: http://pro.ant.design/docs/faq-cn

**Comment by LiangZugeng** [comment]
@afc163 我们用了很长时间的ant design，目前看到ant design pro的页面效果很不错，想用起来。我们的项目从17年1月就开始开发了，是基于webpack/react/react-router/redux/typescript/antd的技术栈，一直在保持更新，现在所有的项目依赖都是最新版本（包括antd）。

我的问题其实和 @BenLakes 一致：如何在现有的项目引入ant design pro，看了Getting Started和FAQ，除了使用umi命令创建脚手架全新开始一个项目之外，ant design pro的Layout和其它组件怎么引入现有项目，我们的项目已经具备完整的路由/后端数据交互/安全/公共组件等东西，如何在此类项目中引入ADP？有什么Instructions文档可以看吗？
