### ISSUE TITLE
每次npm start 都要等超级久的，十几二十分钟，大家都是这样的吗

### ISSUE THREAD

**Issue by Uhaiping** [ant-design/ant-design-pro#1384]
![image](https://user-images.githubusercontent.com/33239901/39343424-4d07e1a4-4a0f-11e8-8cd4-4ad2f8dbd30c.png)

**Comment by shizhiqian** [comment]
我这边npm start也是这么久,每次热更新1分多钟,但是npm run build半个多小时,至今不知道如何解决,会不会和我代码多有关系?

**Comment by roc2539** [comment]
确实会比较慢。不知道怎么优化

**Comment by chenshuai2144** [comment]
也许说得对。你需要升级你的硬件了。
我的电脑上大概30s 左右

**Comment by JoeyKo** [comment]
mbp

**Comment by LKCheng** [comment]
有图表的pro 热更新确实有点慢（预计7s左右）
电脑配置 
![image](https://user-images.githubusercontent.com/10054789/39517265-f0a68a38-4e31-11e8-8992-bb1461177c9f.png)

**Comment by chenshuai2144** [comment]
试着关掉代码分割。
的确是很慢，需要排查一下为什么会这么慢

**Comment by lyingd** [comment]
现在run start根本启动不来，卡在开始那里(cross-env ESLINT=none roadhog dev)几十分钟也没起来

**Comment by sorrycc** [comment]
`TS_CONFIG_PATHS_PLUGIN=none npm start` 试试关闭 ts config path plugin ?

**Comment by ShallowGreen** [comment]
@Uhaiping 你好，问一下热更新需要配置什么吗？我mbp 怎么弄都是无法热更新，根本没法开发，头疼，求解决

**Comment by chenshuai2144** [comment]
喜爱个版本会做一些优化

**Comment by ShallowGreen** [comment]
热加载不生效如何解决，怎么也没看到别人有这个问题 :(

**Comment by reb00t2018** [comment]
我这边代码也一样，等30分钟以上，调试很不方便😭
