### ISSUE TITLE
I  have querstion about Authority 

### ISSUE THREAD

**Issue by a854363956** [ant-design/ant-design-pro#1385]
1.  How can I dynamically determine if the current identity can log in, and record the identity of the current login person? 
If I use the traditional way 
```js
var re = $.ajax(url,{username:"1",password:"2"});
if(re.size() == 0){
  alert("login error");
}else{
 window.location.href ="xxx"
}
```
but my use ant design pro , what should I do? 

can you explain in detail how his permissions are configured in the code?

**Comment by roc2539** [comment]
https://pro.ant.design/docs/authority-management-cn

**Comment by a854363956** [comment]
@roc2539  
If a menu allows multiple characters to log in, it can be written like this ?
```js
'/dashboard/workplace': {
  component: dynamicWrapper(app, ['project', 'activities', 'chart'], () => import('../routes/Dashboard/Workplace')),
  authority: ['admin','admin1','admin2',.....], 
},
```

**Comment by roc2539** [comment]
en

**Comment by a854363956** [comment]
@roc2539  Thanks
