### ISSUE TITLE
关于打包的问题

### ISSUE THREAD

**Issue by doocal** [ant-design/ant-design-pro#1388]
测试一下官方的build，build 后就4个文件其中JS文件2.3M。这样虽着功能的增加单文件的体积就太大了。

**Comment by afc163** [comment]
打开 code split ：https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD

**Comment by shizhiqian** [comment]
你没有设置按需加载,   .webpackrc.js 中的"disableDynamicImport"设置为false

**Comment by doocal** [comment]
嗯，嗯，是文档没有细看。抱歉。。。。
