### ISSUE TITLE
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null     at Array.map (native)

### ISSUE THREAD

**Issue by Agagy** [ant-design/ant-design-pro#1389]
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (native)

**Comment by Agagy** [comment]
这个是什么问题？好心累。。。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/search?q=AssignmentExpression&type=Issues

提问前先搜索。
