### ISSUE TITLE
分步表单页中的收款账户元素未对齐

### ISSUE THREAD

**Issue by doterme** [ant-design/ant-design-pro#139]
![image](https://user-images.githubusercontent.com/12495369/32539813-9f0dfe9c-c4a5-11e7-89bc-833fb5332c7a.png)
如上图，收款账户元素中的下拉和输入框未对齐。

环境：13寸mac Chrome 62

**Comment by afc163** [comment]
Thx for report it! The demo will be updated until a new beta of antd 3.x released.
