### ISSUE TITLE
npm run  build出错

### ISSUE THREAD

**Issue by zllkyo** [ant-design/ant-design-pro#1390]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs8\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--userconfig=C:\\Users\\Administrator\\.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@1.3.0~prebuild: ant-design-pro@1.3.0
6 info lifecycle ant-design-pro@1.3.0~build: ant-design-pro@1.3.0
7 verbose lifecycle ant-design-pro@1.3.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@1.3.0~build: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\nodejs8\node_modules\npm\myppp\myTest\node_modules\.bin;D:\nodejs8\node_modules\.bin;D:\Python34\Lib\site-packages\PyQt5;C:\ProgramData\Oracle\Java\javapath;C:\Java\jdk1.8.0_161\bin;D:\Python27\Lib\site-packages\PyQt4;D:\Python27\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\VisualSVN Server\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Graphviz2.28\bin;%OSG_ROOT%\bin;C:\OpenSSL-Win32\bin;C:\QGIS\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;D:\Qt\Qt5.5.1\5.5\msvc2013_64\bin;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\CMake\bin;C:\scala2.12\bin;D:\spark\spark-2.2.0\bin;D:\spark\spark-2.2.0\sbin;D:\spark\hadoop-2.7.4\bin;D:\spark\hbase-1.2.6\bin;D:\spark\apache-hive-2.3.3-bin\bin;D:\maven\apache-maven-3.3.9\bin;D:\apache-tomcat-8.5.24\bin;D:\spark\apache-ant-1.10.3/bin;C:\Git\cmd;D:\nodejs8\;;D:/QGIS/gis/software/Desktop/Bin_5.5.1;D:/QGIS/gis/software/Desktop/Bin_5.5.1/3rdParty;;D:/DTIS8.1/Desktop/Bin_vc10_5.5.1;D:/DTIS8.1/Desktop/Bin_vc10_5.5.1/3rdParty;D:/DTIS8.1/Desktop/BinD_vc10_5.5.1;D:/DTIS8.1/Desktop/BinD_vc10_5.5.1/3rdParty;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle ant-design-pro@1.3.0~build: CWD: D:\nodejs8\node_modules\npm\myppp\myTest
10 silly lifecycle ant-design-pro@1.3.0~build: Args: [ '/d /s /c', 'cross-env ESLINT=none roadhog build' ]
11 silly lifecycle ant-design-pro@1.3.0~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@1.3.0~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@1.3.0 build: `cross-env ESLINT=none roadhog build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ant-design-pro@1.3.0
15 verbose cwd D:\nodejs8\node_modules\npm\myppp\myTest
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\nodejs8\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\Administrator\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@1.3.0 build: `cross-env ESLINT=none roadhog build`
22 error Exit status 1
23 error Failed at the ant-design-pro@1.3.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
https://www.zybuluo.com/bellorchid/note/61496
试试？

**Comment by a854363956** [comment]
Please execute the following commands
```sh
npm cache clean 
npm i
```
