### ISSUE TITLE
ant-design-pro在IE9、IE10上加载报错，有没有什么解决办法

### ISSUE THREAD

**Issue by eppluto** [ant-design/ant-design-pro#1396]
![image](https://user-images.githubusercontent.com/10136539/39390919-67ea2ab2-4ace-11e8-860c-e2a10317f2a4.png)

**Comment by chenshuai2144** [comment]
https://reactjs.org/docs/react-dom.html#browser-support

看看这些。pro 里面有一些新的语法糖你可能需要删除一下。
比如重载运算符

**Comment by chenshuai2144** [comment]
由于人力和精力的原因，我们不承诺兼容ie11以下。
抱歉不能提供支持
