### ISSUE TITLE
收起菜单后出现的小问题

### ISSUE THREAD

**Issue by xhuanlee** [ant-design/ant-design-pro#140]
收起菜单后子菜单显示不出来，点击菜单再收起之后又正常了。
![menu_error](https://user-images.githubusercontent.com/22806759/32548911-74a8c8ae-c4c2-11e7-8565-91b7d80fa94e.jpg)

**Comment by afc163** [comment]
好像重新不出来，请提供详细的重现步骤。

**Comment by xhuanlee** [comment]
在菜单展开状态时将所有子菜单收起来，然后再把整个菜单栏收起来就可以重现

**Comment by mochazzxx** [comment]
我也遇到了：所有菜单不展开的状态下，收缩菜单栏，然后第一次点图标会展开子菜单而不是tooltip形式
