### ISSUE TITLE
可以提供下独立组件的主题定制

### ISSUE THREAD

**Issue by suiyi8760** [ant-design/ant-design-pro#1401]
项目没有完全使用pro进行开发，所以只引入了部分需要的pro组件使用，但是发现roadhog的theme配置没对独立引入的pro组件生效，目前是针对pro组件样式做:global处理

**Comment by chenshuai2144** [comment]
v2 会解决这个问题

https://github.com/ant-design/ant-design-pro-site/pull/173  具体见这里有讨论的
