### ISSUE TITLE
Add codesandbox button in demo

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#1404]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/507615/39408027-624a46ca-4c02-11e8-9823-55bc07676511.png">

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/8c82a9b473fcda056b6a3aabb6ed7f86b2b90abc
fixed
