### ISSUE TITLE
怎样能不用typescript？

### ISSUE THREAD

**Issue by ilaipi** [ant-design/ant-design-pro#1406]
第一次用，尝试最新版`1.3.0`

在`cnpm i`过程中看到装了`typescript`，请问怎么能去掉这个库呢？

个人不喜欢用ts

**Comment by ilaipi** [comment]
还不够稳定吗？一直`cnpm i`不能完全成功，依赖貌似太多了

**Comment by chenshuai2144** [comment]
没用 typescript 是 antd 依赖的。对你没有影响

**Comment by HHH-Disguiser** [comment]
同问，在安装的时候怎么选择不安装ts
