### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by xiangfeiying** [ant-design/ant-design-pro#1407]
一个人修改过这个项目之后，打包给我，我执行了npm install时会有一些警告，待依赖安装完成之后我就执行npm install,就会出现如标题一样的编译失败（./src/routes/List/Projects.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)），请问这是为什么？

**Comment by yaoyuande** [comment]
同问，我也碰到这个 问题了。

**Comment by chenshuai2144** [comment]
日经问题了  看看以前的 issue

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/1345

**Comment by xiangfeiying** [comment]
多谢！
----- 原始邮件 -----
发件人：陈帅 <notifications@github.com>
收件人：ant-design/ant-design-pro <ant-design-pro@noreply.github.com>
抄送人：xiangfeiying <xiangfeiying_77@sina.com>,  Author <author@noreply.github.com>
主题：Re: [ant-design/ant-design-pro] Failed to compile (#1407)
日期：2018年05月02日 10点50分

#1345

&mdash;
