### ISSUE TITLE
表单页的分步表单面包屑存在问题

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design-pro#1409]
如何复现
1.打开https://preview.pro.ant.design/#/form/step-form/info
   或者点击侧边栏的表单页下的分布表单
2.刷新页面
发现面包屑由，首页/表单页/分步表单 -> 首页/表单页/分步表单/分步表单（填写转账信息）
3.进去其他页面后，在返回表单页下的分布表单，
发现面包屑变为，首页/表单页/分步表单

问题在于：
面包屑的生成在render里。
当点击首页/表单页/分步表单发生重定向时，面包屑已经生成了。
并且PageHeader继承PureComponent，组件的 props 和 state 都没发生改变， render 方法就不触发，
所以还是之前的面包屑，并不是重定向后的面包屑。
至于刷新后面包屑归于正常，是因为整个PageHeader基于当前的location_path重新render

**Comment by afc163** [comment]
来个 PR ？

**Comment by chenshuai2144** [comment]
我记得我已经修了这个 bug 了，我在排查一下

**Comment by CCCYANG** [comment]
![image](https://user-images.githubusercontent.com/25678262/39741904-27460b4a-52ce-11e8-9c15-981be20f99e0.png)
同求，搜索列表里面也有这样的问题。

**Comment by chenshuai2144** [comment]
这个 bug 放到2.0里面修改，使用新的 context api 将会更加简单。
这个版本我做个脏处理好了

**Comment by zhangyu921** [comment]
@chenshuai2144  请问这个脏处理是如何做的，应该如何更新我的项目呢？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/63fcc3d97950d3c0dd14ec4ee2f1f88028b31067  看看这个 很简单的
