### ISSUE TITLE
【建议】手机端界面的菜单或许可以固定不动

### ISSUE THREAD

**Issue by HuangQiii** [ant-design/ant-design-pro#141]
如图，手机端的菜单在很上上面，
![default](https://user-images.githubusercontent.com/11797760/32584777-0d8cd516-c535-11e7-8f6c-70af1a79f1fa.PNG)
如果要换个模块，要滑动很久才能到菜单

或者可以换一种思路，菜单栏不显示，因为手机端本来就空间狭窄，可以通过类似drawer的方式呈现菜单，
![drawerlayoutandroid](https://user-images.githubusercontent.com/11797760/32584924-cdbfe2b0-c535-11e7-9eed-af4fd8bb60a9.png)

**Comment by ronggang** [comment]
左边导航栏固定比较好，不管是否在手机端。
类似于帮助文档那样的很长的内容，左边栏应该固定，要不然就只能不停的来回滚动鼠标 😄

**Comment by afc163** [comment]
Duplicate of #141
