### ISSUE TITLE
请问下, 这个项目 你们后台是用什么管理啊?..  

### ISSUE THREAD

**Issue by qingaoti** [ant-design/ant-design-pro#1410]
我试下了 pm2  和 jendkins  管家,都失败了
不知道是不是我设置问题,, 感觉不是很好管理

**Comment by dengfuping** [comment]
一般服务器端才需要监控访问日志的，有监控前端页面访问需求的话一般是做埋点

**Comment by qingaoti** [comment]
@dengfuping 谢谢你的耐心回答~

**Comment by wangzf-no1** [comment]
For example, the back has not been developed yet, and the front first presents the client with simulated data.     pm2 be useful
