### ISSUE TITLE
模块太多，项目启动和打包失败

### ISSUE THREAD

**Issue by yuanjiahui** [ant-design/ant-design-pro#1412]
![image](https://user-images.githubusercontent.com/5235098/39510834-ba9cce2a-4e1d-11e8-9063-aaa79ad5d4e3.png)
这个问题有解决方法吗？

**Comment by zhang0ZGC** [comment]
我是npm start测试正常，打包完了运行错误..

**Comment by chenshuai2144** [comment]
把大型的库 放到 cdn 上面去吧

**Comment by yuanjiahui** [comment]
我的router.js的路由太多，约有200多个，启动和打包报上述错误

**Comment by yuanjiahui** [comment]
![image](https://user-images.githubusercontent.com/5235098/39523906-c7c1d2cc-4e49-11e8-871a-1d546c39b890.png)
在网上查的是由于node的内存使用有限制，增加启动参数调大内存
https://segmentfault.com/a/1190000010437948

**Comment by syaivin** [comment]
@yuanjiahui 好的，我试试，谢谢您.

**Comment by syaivin** [comment]
@yuanjiahui 尴尬了，按你的设置还是一样的

![qq 20180503094544](https://user-images.githubusercontent.com/13479047/39557029-438387c6-4eb7-11e8-9ec9-429f9bd23eb6.png)

**Comment by taoqianbao** [comment]
最好的方案，还是，能有一个 拆分子项目的功能；       一个大工程，其实做业务的时候，都是具体到业务，共同的部分，只有头部，菜单导航这些；还有登录，会话状态， 不知道阿里，现在是怎么做的？
