### ISSUE TITLE
关于路由问题

### ISSUE THREAD

**Issue by WarrenJones** [ant-design/ant-design-pro#1413]
![image](https://user-images.githubusercontent.com/8704779/39517556-bdee3f5e-4e32-11e8-96c8-1bf2c3b1ed92.png)
我设置了这两个路由，但是每次都匹配不到带id那个，请问还是需要做那些处理吗？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/router-and-nav-cn#%E5%B8%A6%E5%8F%82%E6%95%B0%E7%9A%84%E8%B7%AF%E7%94%B1/%E8%8F%9C%E5%8D%95

**Comment by WarrenJones** [comment]
@chenshuai2144 I saw the document,but I mean to go to the detail page from the list page like a from a bloglist to a blog detail,This do not need to apper in the menu,But need to config the router,And the result is it still stick at the blog list page thought the url has changed to like url/blog/001
