### ISSUE TITLE
SiderMenu/index.less Typo

### ISSUE THREAD

**Issue by Patrick-Yangqiyu** [ant-design/ant-design-pro#1415]
https://github.com/ant-design/ant-design-pro/blob/a5907a306f5f09bed82fbe9906da0c161530a616/src/components/SiderMenu/index.less#L32

Here is a typo. Should be light. 
这有一个错别字。应该是light。

**Comment by chenshuai2144** [comment]
?

**Comment by Patrick-Yangqiyu** [comment]
错别字，light 不是ligth，这样导致light主题有问题

**Comment by chenshuai2144** [comment]
v2？

**Comment by Patrick-Yangqiyu** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/SiderMenu/index.less 
就是现在这个

**Comment by Patrick-Yangqiyu** [comment]
https://github.com/ant-design/ant-design-pro/blob/a5907a306f5f09bed82fbe9906da0c161530a616/src/components/SiderMenu/index.less#L32

**Comment by chenshuai2144** [comment]
fixed 了

**Comment by afc163** [comment]
没看到提交？

**Comment by afc163** [comment]
应该在 master 上修复。

**Comment by Patrick-Yangqiyu** [comment]
应该每个都有问题，建议安装错别字识别插件...
