### ISSUE TITLE
没法通过module增加新的less-loader,如果想配置less-loader，增加exclude的less文件，如何处理

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design-pro#1418]

**Comment by chenshuai2144** [comment]
If you really need to try webpack.config.js

```
export default webpackConfig => {
  // change less loader
  return webpackConfig;
};
```

**Comment by zjscy666** [comment]
Thanks for your time!
then I import webpack.config.js to .webpackrc.js,but what is the key likes env, alias,how I can use webpack.config.js in the file .webpackrc.js 
this is demo about .webpackrc:
export default {
  entry: 'src/index.js',
  extraBabelPlugins: [
    // 'transform-decorators-legacy',
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  alias: {
    components: path.resolve(__dirname, 'src/components/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport: true,
  publicPath: '/',
  hash: true,
};
