### ISSUE TITLE
IE10以下：Cannot call a class as a function

### ISSUE THREAD

**Issue by zfzhengfeng** [ant-design/ant-design-pro#1419]
![image](https://user-images.githubusercontent.com/17020216/39556739-20cc8040-4eb5-11e8-8773-ea244e730981.png)

重新npm install之后，打包后的项目在IE10、IE9下报错，之前IE9以上都没有问题。
测试1：用同事之前安装的node_moudle运行，IE10、IE9不报错
测试2：删除node_moudle后重新安装打包，报错
测试3：克隆官网最新项目，打包报错

**Comment by chenshuai2144** [comment]
试着回滚一下 babel 的版本

**Comment by zfzhengfeng** [comment]
不好意思，应为babel和其他依赖了解很有限，下来尝试了很多办法，没有解决问题，还会引起其他错误，如运行的依赖版本冲突等。
能否修复ant-design-pro官网例子，使其支持IE9、IE10，下来我在自己对照升级？

**Comment by afc163** [comment]
我们不对 IE9/10 进行官方支持，你可以帮助我们排查并 PR。
