### ISSUE TITLE
饼图组件Pie在首次渲染position错误

### ISSUE THREAD

**Issue by jzoe** [ant-design/ant-design-pro#1421]
![image](https://user-images.githubusercontent.com/11612990/39558888-e7c72c9a-4ec4-11e8-9d55-a458e823ea1e.png)

在第一次渲染时，饼图的位置有问题。在resize触发重新渲染后，才会正确渲染。

![image](https://user-images.githubusercontent.com/11612990/39558928-2091ccd8-4ec5-11e8-9c6e-09af91d35746.png)

这个问题也是 https://github.com/dvajs/dva/issues/1300 导致的吗？还是没有正确计算位置导致的？

**Comment by jzoe** [comment]
这个有什么解决办法吗？ https://github.com/ant-design/ant-design-pro/issues/1301 中说的这个 timeout 如何设置呢？

**Comment by nikogu** [comment]
@jzoe 在 product 环境没事的，你可以在 render 的时候，延迟渲染一下，这样等页面结构都 ok 了样式就对了，目前没有什么好办法，你有空的话可以深入研究下

**Comment by bgold0** [comment]
> @jzoe 在 product 环境没事的，你可以在 render 的时候，延迟渲染一下，这样等页面结构都 ok 了样式就对了，目前没有什么好办法，你有空的话可以深入研究下

This is not true. In Production it does not work either.
