### ISSUE TITLE
npm run 报错

### ISSUE THREAD

**Issue by ZCLegendary** [ant-design/ant-design-pro#1422]
Starting the development server...

[babel-plugin-dva-hmr][INFO] got routerPath ./router
Failed to compile.

./src/routes/List/Projects.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)

**Comment by CnVicky** [comment]
我也遇到了，一样的错

**Comment by zfzhengfeng** [comment]
![image](https://user-images.githubusercontent.com/17020216/39564643-a381e1f6-4ee7-11e8-81ac-01e99ea57269.png)
把这句话去掉试试
https://github.com/ant-design/ant-design-pro/pull/1345

**Comment by CnVicky** [comment]
非常感谢，果然可以了

**Comment by Lpbzzz** [comment]
大佬，我的 webpackrc.js里没有这行代码也会  报  [babel-plugin-dva-hmr][INFO] got routerPath ./router ....
