### ISSUE TITLE
如何在render方法里使用this.setState方法

### ISSUE THREAD

**Issue by xzk821649509** [ant-design/ant-design-pro#1423]
现在项目里有需要在render()方法里组合后端传过来的数据，然后放到state里面，但是我一旦在render使用了this.setState方法就立即崩溃了，请问这要怎么解决

**Comment by zfzhengfeng** [comment]
state和props的变化会引起render函数执行，你这样就死循环了。你应该在其他地方处理。

**Comment by afc163** [comment]
先学习 React。
