### ISSUE TITLE
Function name typo: getMeunMatcheys -> getMeunMatchKeys

### ISSUE THREAD

**Issue by AlanWei** [ant-design/ant-design-pro#1424]
There is a function name typo in `SiderMenu.js`.

Should be `getMeunMatchKeys` instead of `getMeunMatcheys`.

The corresponding test file `SiderMenu.test.js` has the same typo as well.

**Comment by afc163** [comment]
PR is welcome~

**Comment by AlanWei** [comment]
PR is here: https://github.com/ant-design/ant-design-pro/pull/1427
🙂
