### ISSUE TITLE
roadhog-api-doc static 之后如何同时能访问外网api数据

### ISSUE THREAD

**Issue by loveacat** [ant-design/ant-design-pro#1426]
由于需要演示，因此用roadhog-api-doc static 之后把dist文件上传到正式服务器，但是开发页面其他正常的访问外网的请求貌似也被拦截了，如果能同时使用mock 数据和真实外网api请求

**Comment by chenshuai2144** [comment]
这个并不影响吧。只有不和 api/*重叠

**Comment by taoqianbao** [comment]
I have the same problem , cannot visit the api.  boz seems . roadhog change request method;

**Comment by taoqianbao** [comment]
I have checked the roadhog-api-doc sourcecode,  when you build at static mode, it will replace Request.JS from utils.    so I added an new request2.js which is used for the API server and the old one used for mock data;   it's solved;

**Comment by b9AobJ** [comment]
@taoqianbao thanks at all, U help me and save me!!!
