### ISSUE TITLE
redux数据清除问题

### ISSUE THREAD

**Issue by dlamon** [ant-design/ant-design-pro#1430]
# Redux数据清除问题
## 问题描述：
在表单页->分步表单 交易中，在Step1页面将转账金额从500修改为5000，点击下一步，进入Step2页面，不进行交易提交，点击菜单中任意一个其他交易后再进入分步表单交易，会发现默认的转账金额从500变更为上一次输入的脏数据5000。

## 问题代码：
我查阅了数据流，发现models->form.js中，有以下代码段：
![image](https://user-images.githubusercontent.com/31594192/39609771-fc791e3c-4f7d-11e8-9f97-3792ad138104.png)
分步表单在点击下一步后会将step数据存储在redux中的，但是不会进行数据清除，导致下一次进入分步表单交易后从redux中获取上一次的step数据来进行页面组件初始化。
代码在routes->Forms->StepForm->Step1.js中：
![image](https://user-images.githubusercontent.com/31594192/39609856-9afba552-4f7e-11e8-8675-a8627f3ee426.png)
这种脏数据在实际开发过程中可能会带来大量的不可预知的问题。

如果需要清除数据，那么数据的清除代码应该写在什么地方？在什么时机进行数据清除？
在开发过程中，假定每一个菜单项都对应一个交易，能否在redux中申请一个交易级别的专用数据区域，在新交易进入时由框架进行交易级数据区域的清空操作。

**Comment by chenshuai2144** [comment]
If you do not need to remember the data.
You should reset in `componentWillUnmount`

**Comment by dlamon** [comment]
在某些场景下我需要存储这些数据，比如分步表单，或者是一个交易提交失败后跳转到失败页面，失败页面提供一个返回修改的按钮跳转到输入页面并展现上一次的输入数据提供给用户修改，所以在这些场景下不能使用componentWillUnmount来清除这些暂存数据。
