### ISSUE TITLE
如何使用dispatch的回调函数？

### ISSUE THREAD

**Issue by xzk821649509** [ant-design/ant-design-pro#1435]
routes的代码如下：
`const { dispatch } = this.props;
    dispatch({
      type: 'account/register',
      payload: fieldsValue,
    })
    .then((data) => {
      console.log(data);
    })`
最终打印出来的结果为undefined
models的代码如下：
`*register({ payload }, { call, put }) {
      const response = yield call(boRegister, payload);
      yield put({
        type: 'result',
        payload: response,
      });
      if (response.code === 1) message.success(response.msg);
      else message.error(response.msg);
    }`

`result(state, action) {
      return {
        ...state,
        result: action.payload,
      };
    },`
请问是什么原因？

**Comment by chenyu1990** [comment]
```
   dispatch({
      type: 'config/patch',
      callback: () => {
        console.log('ok');
      }
    });
```
