### ISSUE TITLE
登录流程问题，登录成功后为什么还需要请求 /api/currentUser

### ISSUE THREAD

**Issue by dragonishare** [ant-design/ant-design-pro#1439]
不是很懂这个登录流程是怎么设计的，登录成功后跳转到首页到时候，还要再请求获取当前用户信息到接口；
我的理解：
如果登录的时候只是拿到了用户的id等基本信息，想需要获取更多相关信息的时候是要发起请求的，但是问题是，我在.roadhogrc.mock.js文件中，没看到对应的“/api/currentUser”请求，有什么入参？
感觉这个登录流程真的是。。。

**Comment by chenshuai2144** [comment]
在很多系统中 鉴权系统和用户管理系统是分开的。
事实证明分开是个很好的实践
