### ISSUE TITLE
dva使用router4，怎么解决页面缓存问题？例如：tab的切换，不触发页面的渲染？

### ISSUE THREAD

**Issue by JesterCheung** [ant-design/ant-design-pro#144]

**Comment by nikogu** [comment]
@JesterCheung 具体场景？参看 https://preview.pro.ant.design/#/list/filter-card-list

**Comment by JesterCheung** [comment]
是的，就是这个场景。但是这个场景是：tab切换之后，页面会重新渲染。我想要的效果是，例如我浏览了标签页“文章”，再访问下一个标签页“应用”之后，再倒回去访问“文章”这个标签页，我希望这个时候“文章”这个标签页面不重新渲染。

**Comment by JesterCheung** [comment]
是的，就是这个场景。但是这个场景是：tab切换之后，页面会重新渲染。我想要的效果是，例如我浏览了标签页“文章”，再访问下一个标签页“应用”之后，再倒回去访问“文章”这个标签页，我希望这个时候“文章”这个标签页面不重新渲染。 @nikogu

**Comment by nikogu** [comment]
@JesterCheung 你可以组件里面判断就好了，`shouldComponentUpdate`

**Comment by AlberZ1989** [comment]
@nikogu 你好，我也遇到了类似的需求。请问具体该怎么实现呢？这个判断该怎么写？

**Comment by roc2539** [comment]
怎么写？
