### ISSUE TITLE
代理访问后端不成功,求助

### ISSUE THREAD

**Issue by gxshmm** [ant-design/ant-design-pro#1440]
在.roadhogrc.mock.js中配置了不用代理请求后端的地址
`export default (noProxy ? {'/*':'http://localhost:8080/'} : delay(proxy, 1000));`
start:no-proxy启动为啥打开以后还是会去请求localhost:8000?
![_20180505135106](https://user-images.githubusercontent.com/16116192/39660153-673b0fb2-506b-11e8-8257-93e75cdd3744.png)

**Comment by kunhour** [comment]
不用代理的启动方式是
npm run start:no-proxy

**Comment by kunhour** [comment]
在webpackc.js里配置代理。

**Comment by chenshuai2144** [comment]
webpackc.js 里面配置的代理一定会起作用的。
