### ISSUE TITLE
RangePicker 控件在表单提交时GET附带了太多参数

### ISSUE THREAD

**Issue by camry** [ant-design/ant-design-pro#1441]
RangePicker 控件在表单提交时GET附带了太多参数，POST是正常的。

各位大佬，请问如何解决？

GET 请求时：
created_at[0][_isAMomentObject]:true
created_at[0][_isUTC]:false
created_at[0][_pf][empty]:false
created_at[0][_pf][overflow]:-2
created_at[0][_pf][charsLeftOver]:0
created_at[0][_pf][nullInput]:false
created_at[0][_pf][invalidMonth]:
created_at[0][_pf][invalidFormat]:false
created_at[0][_pf][userInvalidated]:false
created_at[0][_pf][iso]:false
created_at[0][_pf][meridiem]:
created_at[0][_pf][rfc2822]:false
created_at[0][_pf][weekdayMismatch]:false
created_at[0][_locale][_calendar][sameDay]:[今天]LT
created_at[0][_locale][_calendar][nextDay]:[明天]LT
created_at[0][_locale][_calendar][nextWeek]:[下]ddddLT
created_at[0][_locale][_calendar][lastDay]:[昨天]LT
created_at[0][_locale][_calendar][lastWeek]:[上]ddddLT
created_at[0][_locale][_calendar][sameElse]:L
created_at[0][_locale][_longDateFormat][LTS]:HH:mm:ss
created_at[0][_locale][_longDateFormat][LT]:HH:mm
created_at[0][_locale][_longDateFormat][L]:YYYY/MM/DD
created_at[0][_locale][_longDateFormat][LL]:YYYY年M月D日
created_at[0][_locale][_longDateFormat][LLL]:YYYY年M月D日Ah点mm分
created_at[0][_locale][_longDateFormat][LLLL]:YYYY年M月D日ddddAh点mm分
created_at[0][_locale][_longDateFormat][l]:YYYY/M/D
created_at[0][_locale][_longDateFormat][ll]:YYYY年M月D日
created_at[0][_locale][_longDateFormat][lll]:YYYY年M月D日 HH:mm
created_at[0][_locale][_longDateFormat][llll]:YYYY年M月D日dddd HH:mm
created_at[0][_locale][_invalidDate]:Invalid date
created_at[0][_locale][_relativeTime][future]:%s内
created_at[0][_locale][_relativeTime][past]:%s前
created_at[0][_locale][_relativeTime][s]:几秒
created_at[0][_locale][_relativeTime][ss]:%d 秒
created_at[0][_locale][_relativeTime][m]:1 分钟
created_at[0][_locale][_relativeTime][mm]:%d 分钟
created_at[0][_locale][_relativeTime][h]:1 小时
created_at[0][_locale][_relativeTime][hh]:%d 小时
created_at[0][_locale][_relativeTime][d]:1 天
created_at[0][_locale][_relativeTime][dd]:%d 天
created_at[0][_locale][_relativeTime][M]:1 个月
created_at[0][_locale][_relativeTime][MM]:%d 个月
created_at[0][_locale][_relativeTime][y]:1 年
created_at[0][_locale][_relativeTime][yy]:%d 年
created_at[0][_locale][_months][0]:一月
created_at[0][_locale][_months][1]:二月
created_at[0][_locale][_months][2]:三月
created_at[0][_locale][_months][3]:四月
created_at[0][_locale][_months][4]:五月
created_at[0][_locale][_months][5]:六月
created_at[0][_locale][_months][6]:七月
created_at[0][_locale][_months][7]:八月
created_at[0][_locale][_months][8]:九月
created_at[0][_locale][_months][9]:十月
created_at[0][_locale][_months][10]:十一月
created_at[0][_locale][_months][11]:十二月
created_at[0][_locale][_monthsShort][0]:1月
created_at[0][_locale][_monthsShort][1]:2月
created_at[0][_locale][_monthsShort][2]:3月
created_at[0][_locale][_monthsShort][3]:4月
created_at[0][_locale][_monthsShort][4]:5月
created_at[0][_locale][_monthsShort][5]:6月
created_at[0][_locale][_monthsShort][6]:7月
created_at[0][_locale][_monthsShort][7]:8月
created_at[0][_locale][_monthsShort][8]:9月
created_at[0][_locale][_monthsShort][9]:10月
created_at[0][_locale][_monthsShort][10]:11月
created_at[0][_locale][_monthsShort][11]:12月
created_at[0][_locale][_week][dow]:1
created_at[0][_locale][_week][doy]:4
created_at[0][_locale][_weekdays][0]:星期日
created_at[0][_locale][_weekdays][1]:星期一
created_at[0][_locale][_weekdays][2]:星期二
created_at[0][_locale][_weekdays][3]:星期三
created_at[0][_locale][_weekdays][4]:星期四
created_at[0][_locale][_weekdays][5]:星期五
created_at[0][_locale][_weekdays][6]:星期六
created_at[0][_locale][_weekdaysMin][0]:日
created_at[0][_locale][_weekdaysMin][1]:一
created_at[0][_locale][_weekdaysMin][2]:二
created_at[0][_locale][_weekdaysMin][3]:三
created_at[0][_locale][_weekdaysMin][4]:四
created_at[0][_locale][_weekdaysMin][5]:五
created_at[0][_locale][_weekdaysMin][6]:六
created_at[0][_locale][_weekdaysShort][0]:周日
created_at[0][_locale][_weekdaysShort][1]:周一
created_at[0][_locale][_weekdaysShort][2]:周二
created_at[0][_locale][_weekdaysShort][3]:周三
created_at[0][_locale][_weekdaysShort][4]:周四
created_at[0][_locale][_weekdaysShort][5]:周五
created_at[0][_locale][_weekdaysShort][6]:周六
created_at[0][_locale][_abbr]:zh-cn
created_at[0][_locale][_config][calendar][sameDay]:[今天]LT
created_at[0][_locale][_config][calendar][nextDay]:[明天]LT
created_at[0][_locale][_config][calendar][nextWeek]:[下]ddddLT
created_at[0][_locale][_config][calendar][lastDay]:[昨天]LT
created_at[0][_locale][_config][calendar][lastWeek]:[上]ddddLT
created_at[0][_locale][_config][calendar][sameElse]:L
created_at[0][_locale][_config][longDateFormat][LTS]:HH:mm:ss
created_at[0][_locale][_config][longDateFormat][LT]:HH:mm
created_at[0][_locale][_config][longDateFormat][L]:YYYY/MM/DD
created_at[0][_locale][_config][longDateFormat][LL]:YYYY年M月D日
created_at[0][_locale][_config][longDateFormat][LLL]:YYYY年M月D日Ah点mm分
created_at[0][_locale][_config][longDateFormat][LLLL]:YYYY年M月D日ddddAh点mm分
created_at[0][_locale][_config][longDateFormat][l]:YYYY/M/D
created_at[0][_locale][_config][longDateFormat][ll]:YYYY年M月D日
created_at[0][_locale][_config][longDateFormat][lll]:YYYY年M月D日 HH:mm
created_at[0][_locale][_config][longDateFormat][llll]:YYYY年M月D日dddd HH:mm
created_at[0][_locale][_config][invalidDate]:Invalid date
created_at[0][_locale][_config][relativeTime][future]:%s内
created_at[0][_locale][_config][relativeTime][past]:%s前
created_at[0][_locale][_config][relativeTime][s]:几秒
created_at[0][_locale][_config][relativeTime][ss]:%d 秒
created_at[0][_locale][_config][relativeTime][m]:1 分钟
created_at[0][_locale][_config][relativeTime][mm]:%d 分钟
created_at[0][_locale][_config][relativeTime][h]:1 小时
created_at[0][_locale][_config][relativeTime][hh]:%d 小时
created_at[0][_locale][_config][relativeTime][d]:1 天
created_at[0][_locale][_config][relativeTime][dd]:%d 天
created_at[0][_locale][_config][relativeTime][M]:1 个月
created_at[0][_locale][_config][relativeTime][MM]:%d 个月
created_at[0][_locale][_config][relativeTime][y]:1 年
created_at[0][_locale][_config][relativeTime][yy]:%d 年
created_at[0][_locale][_config][months][0]:一月
created_at[0][_locale][_config][months][1]:二月
created_at[0][_locale][_config][months][2]:三月
created_at[0][_locale][_config][months][3]:四月
created_at[0][_locale][_config][months][4]:五月
created_at[0][_locale][_config][months][5]:六月
created_at[0][_locale][_config][months][6]:七月
created_at[0][_locale][_config][months][7]:八月
created_at[0][_locale][_config][months][8]:九月
created_at[0][_locale][_config][months][9]:十月
created_at[0][_locale][_config][months][10]:十一月
created_at[0][_locale][_config][months][11]:十二月
created_at[0][_locale][_config][monthsShort][0]:1月
created_at[0][_locale][_config][monthsShort][1]:2月
created_at[0][_locale][_config][monthsShort][2]:3月
created_at[0][_locale][_config][monthsShort][3]:4月
created_at[0][_locale][_config][monthsShort][4]:5月
created_at[0][_locale][_config][monthsShort][5]:6月
created_at[0][_locale][_config][monthsShort][6]:7月
created_at[0][_locale][_config][monthsShort][7]:8月
created_at[0][_locale][_config][monthsShort][8]:9月
created_at[0][_locale][_config][monthsShort][9]:10月
created_at[0][_locale][_config][monthsShort][10]:11月
created_at[0][_locale][_config][monthsShort][11]:12月
created_at[0][_locale][_config][week][dow]:1
created_at[0][_locale][_config][week][doy]:4
created_at[0][_locale][_config][weekdays][0]:星期日
created_at[0][_locale][_config][weekdays][1]:星期一
created_at[0][_locale][_config][weekdays][2]:星期二
created_at[0][_locale][_config][weekdays][3]:星期三
created_at[0][_locale][_config][weekdays][4]:星期四
created_at[0][_locale][_config][weekdays][5]:星期五
created_at[0][_locale][_config][weekdays][6]:星期六
created_at[0][_locale][_config][weekdaysMin][0]:日
created_at[0][_locale][_config][weekdaysMin][1]:一
created_at[0][_locale][_config][weekdaysMin][2]:二
created_at[0][_locale][_config][weekdaysMin][3]:三
created_at[0][_locale][_config][weekdaysMin][4]:四
created_at[0][_locale][_config][weekdaysMin][5]:五
created_at[0][_locale][_config][weekdaysMin][6]:六
created_at[0][_locale][_config][weekdaysShort][0]:周日
created_at[0][_locale][_config][weekdaysShort][1]:周一
created_at[0][_locale][_config][weekdaysShort][2]:周二
created_at[0][_locale][_config][weekdaysShort][3]:周三
created_at[0][_locale][_config][weekdaysShort][4]:周四
created_at[0][_locale][_config][weekdaysShort][5]:周五
created_at[0][_locale][_config][weekdaysShort][6]:周六
created_at[0][_locale][_config][abbr]:zh-cn
created_at[0][_d]:2018-05-05T09:32:06.790Z
created_at[0][_isValid]:true
created_at[1][_isAMomentObject]:true
created_at[1][_isUTC]:false
created_at[1][_pf][empty]:false
created_at[1][_pf][overflow]:-2
created_at[1][_pf][charsLeftOver]:0
created_at[1][_pf][nullInput]:false
created_at[1][_pf][invalidMonth]:
created_at[1][_pf][invalidFormat]:false
created_at[1][_pf][userInvalidated]:false
created_at[1][_pf][iso]:false
created_at[1][_pf][meridiem]:
created_at[1][_pf][rfc2822]:false
created_at[1][_pf][weekdayMismatch]:false
created_at[1][_locale][_calendar][sameDay]:[今天]LT
created_at[1][_locale][_calendar][nextDay]:[明天]LT
created_at[1][_locale][_calendar][nextWeek]:[下]ddddLT
created_at[1][_locale][_calendar][lastDay]:[昨天]LT
created_at[1][_locale][_calendar][lastWeek]:[上]ddddLT
created_at[1][_locale][_calendar][sameElse]:L
created_at[1][_locale][_longDateFormat][LTS]:HH:mm:ss
created_at[1][_locale][_longDateFormat][LT]:HH:mm
created_at[1][_locale][_longDateFormat][L]:YYYY/MM/DD
created_at[1][_locale][_longDateFormat][LL]:YYYY年M月D日
created_at[1][_locale][_longDateFormat][LLL]:YYYY年M月D日Ah点mm分
created_at[1][_locale][_longDateFormat][LLLL]:YYYY年M月D日ddddAh点mm分
created_at[1][_locale][_longDateFormat][l]:YYYY/M/D
created_at[1][_locale][_longDateFormat][ll]:YYYY年M月D日
created_at[1][_locale][_longDateFormat][lll]:YYYY年M月D日 HH:mm
created_at[1][_locale][_longDateFormat][llll]:YYYY年M月D日dddd HH:mm
created_at[1][_locale][_invalidDate]:Invalid date
created_at[1][_locale][_relativeTime][future]:%s内
created_at[1][_locale][_relativeTime][past]:%s前
created_at[1][_locale][_relativeTime][s]:几秒
created_at[1][_locale][_relativeTime][ss]:%d 秒
created_at[1][_locale][_relativeTime][m]:1 分钟
created_at[1][_locale][_relativeTime][mm]:%d 分钟
created_at[1][_locale][_relativeTime][h]:1 小时
created_at[1][_locale][_relativeTime][hh]:%d 小时
created_at[1][_locale][_relativeTime][d]:1 天
created_at[1][_locale][_relativeTime][dd]:%d 天
created_at[1][_locale][_relativeTime][M]:1 个月
created_at[1][_locale][_relativeTime][MM]:%d 个月
created_at[1][_locale][_relativeTime][y]:1 年
created_at[1][_locale][_relativeTime][yy]:%d 年
created_at[1][_locale][_months][0]:一月
created_at[1][_locale][_months][1]:二月
created_at[1][_locale][_months][2]:三月
created_at[1][_locale][_months][3]:四月
created_at[1][_locale][_months][4]:五月
created_at[1][_locale][_months][5]:六月
created_at[1][_locale][_months][6]:七月
created_at[1][_locale][_months][7]:八月
created_at[1][_locale][_months][8]:九月
created_at[1][_locale][_months][9]:十月
created_at[1][_locale][_months][10]:十一月
created_at[1][_locale][_months][11]:十二月
created_at[1][_locale][_monthsShort][0]:1月
created_at[1][_locale][_monthsShort][1]:2月
created_at[1][_locale][_monthsShort][2]:3月
created_at[1][_locale][_monthsShort][3]:4月
created_at[1][_locale][_monthsShort][4]:5月
created_at[1][_locale][_monthsShort][5]:6月
created_at[1][_locale][_monthsShort][6]:7月
created_at[1][_locale][_monthsShort][7]:8月
created_at[1][_locale][_monthsShort][8]:9月
created_at[1][_locale][_monthsShort][9]:10月
created_at[1][_locale][_monthsShort][10]:11月
created_at[1][_locale][_monthsShort][11]:12月
created_at[1][_locale][_week][dow]:1
created_at[1][_locale][_week][doy]:4
created_at[1][_locale][_weekdays][0]:星期日
created_at[1][_locale][_weekdays][1]:星期一
created_at[1][_locale][_weekdays][2]:星期二
created_at[1][_locale][_weekdays][3]:星期三
created_at[1][_locale][_weekdays][4]:星期四
created_at[1][_locale][_weekdays][5]:星期五
created_at[1][_locale][_weekdays][6]:星期六
created_at[1][_locale][_weekdaysMin][0]:日
created_at[1][_locale][_weekdaysMin][1]:一
created_at[1][_locale][_weekdaysMin][2]:二
created_at[1][_locale][_weekdaysMin][3]:三
created_at[1][_locale][_weekdaysMin][4]:四
created_at[1][_locale][_weekdaysMin][5]:五
created_at[1][_locale][_weekdaysMin][6]:六
created_at[1][_locale][_weekdaysShort][0]:周日
created_at[1][_locale][_weekdaysShort][1]:周一
created_at[1][_locale][_weekdaysShort][2]:周二
created_at[1][_locale][_weekdaysShort][3]:周三
created_at[1][_locale][_weekdaysShort][4]:周四
created_at[1][_locale][_weekdaysShort][5]:周五
created_at[1][_locale][_weekdaysShort][6]:周六
created_at[1][_locale][_abbr]:zh-cn
created_at[1][_locale][_config][calendar][sameDay]:[今天]LT
created_at[1][_locale][_config][calendar][nextDay]:[明天]LT
created_at[1][_locale][_config][calendar][nextWeek]:[下]ddddLT
created_at[1][_locale][_config][calendar][lastDay]:[昨天]LT
created_at[1][_locale][_config][calendar][lastWeek]:[上]ddddLT
created_at[1][_locale][_config][calendar][sameElse]:L
created_at[1][_locale][_config][longDateFormat][LTS]:HH:mm:ss
created_at[1][_locale][_config][longDateFormat][LT]:HH:mm
created_at[1][_locale][_config][longDateFormat][L]:YYYY/MM/DD
created_at[1][_locale][_config][longDateFormat][LL]:YYYY年M月D日
created_at[1][_locale][_config][longDateFormat][LLL]:YYYY年M月D日Ah点mm分
created_at[1][_locale][_config][longDateFormat][LLLL]:YYYY年M月D日ddddAh点mm分
created_at[1][_locale][_config][longDateFormat][l]:YYYY/M/D
created_at[1][_locale][_config][longDateFormat][ll]:YYYY年M月D日
created_at[1][_locale][_config][longDateFormat][lll]:YYYY年M月D日 HH:mm
created_at[1][_locale][_config][longDateFormat][llll]:YYYY年M月D日dddd HH:mm
created_at[1][_locale][_config][invalidDate]:Invalid date
created_at[1][_locale][_config][relativeTime][future]:%s内
created_at[1][_locale][_config][relativeTime][past]:%s前
created_at[1][_locale][_config][relativeTime][s]:几秒
created_at[1][_locale][_config][relativeTime][ss]:%d 秒
created_at[1][_locale][_config][relativeTime][m]:1 分钟
created_at[1][_locale][_config][relativeTime][mm]:%d 分钟
created_at[1][_locale][_config][relativeTime][h]:1 小时
created_at[1][_locale][_config][relativeTime][hh]:%d 小时
created_at[1][_locale][_config][relativeTime][d]:1 天
created_at[1][_locale][_config][relativeTime][dd]:%d 天
created_at[1][_locale][_config][relativeTime][M]:1 个月
created_at[1][_locale][_config][relativeTime][MM]:%d 个月
created_at[1][_locale][_config][relativeTime][y]:1 年
created_at[1][_locale][_config][relativeTime][yy]:%d 年
created_at[1][_locale][_config][months][0]:一月
created_at[1][_locale][_config][months][1]:二月
created_at[1][_locale][_config][months][2]:三月
created_at[1][_locale][_config][months][3]:四月
created_at[1][_locale][_config][months][4]:五月
created_at[1][_locale][_config][months][5]:六月
created_at[1][_locale][_config][months][6]:七月
created_at[1][_locale][_config][months][7]:八月
created_at[1][_locale][_config][months][8]:九月
created_at[1][_locale][_config][months][9]:十月
created_at[1][_locale][_config][months][10]:十一月
created_at[1][_locale][_config][months][11]:十二月
created_at[1][_locale][_config][monthsShort][0]:1月
created_at[1][_locale][_config][monthsShort][1]:2月
created_at[1][_locale][_config][monthsShort][2]:3月
created_at[1][_locale][_config][monthsShort][3]:4月
created_at[1][_locale][_config][monthsShort][4]:5月
created_at[1][_locale][_config][monthsShort][5]:6月
created_at[1][_locale][_config][monthsShort][6]:7月
created_at[1][_locale][_config][monthsShort][7]:8月
created_at[1][_locale][_config][monthsShort][8]:9月
created_at[1][_locale][_config][monthsShort][9]:10月
created_at[1][_locale][_config][monthsShort][10]:11月
created_at[1][_locale][_config][monthsShort][11]:12月
created_at[1][_locale][_config][week][dow]:1
created_at[1][_locale][_config][week][doy]:4
created_at[1][_locale][_config][weekdays][0]:星期日
created_at[1][_locale][_config][weekdays][1]:星期一
created_at[1][_locale][_config][weekdays][2]:星期二
created_at[1][_locale][_config][weekdays][3]:星期三
created_at[1][_locale][_config][weekdays][4]:星期四
created_at[1][_locale][_config][weekdays][5]:星期五
created_at[1][_locale][_config][weekdays][6]:星期六
created_at[1][_locale][_config][weekdaysMin][0]:日
created_at[1][_locale][_config][weekdaysMin][1]:一
created_at[1][_locale][_config][weekdaysMin][2]:二
created_at[1][_locale][_config][weekdaysMin][3]:三
created_at[1][_locale][_config][weekdaysMin][4]:四
created_at[1][_locale][_config][weekdaysMin][5]:五
created_at[1][_locale][_config][weekdaysMin][6]:六
created_at[1][_locale][_config][weekdaysShort][0]:周日
created_at[1][_locale][_config][weekdaysShort][1]:周一
created_at[1][_locale][_config][weekdaysShort][2]:周二
created_at[1][_locale][_config][weekdaysShort][3]:周三
created_at[1][_locale][_config][weekdaysShort][4]:周四
created_at[1][_locale][_config][weekdaysShort][5]:周五
created_at[1][_locale][_config][weekdaysShort][6]:周六
created_at[1][_locale][_config][abbr]:zh-cn
created_at[1][_d]:2018-05-18T09:32:06.790Z
created_at[1][_isValid]:true

POST请求：
created_at[0]:2018-05-05T09:32:06.790Z
created_at[1]:2018-05-18T09:32:06.790Z

**Comment by afc163** [comment]
提交行为是你自己控制的，请自行过滤数据。
