### ISSUE TITLE
AuthorizedRoute 在IE10下面报错

### ISSUE THREAD

**Issue by nixinhua001** [ant-design/ant-design-pro#1442]
备注：首先我知道antd pro是支持IE11的，但我想不使用Layout布局组件的情况下是不是可以的？

在ie10（ie11 仿真模式下选ie11）下面报下面的错误：
`Warning: The <AuthorizedRoute /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change AuthorizedRoute to extend React.Component instead.`

`SCRIPT5022: 引发了异常但未捕获`

`The above error occurred in the <AuthorizedRoute> component:
    in AuthorizedRoute (created by DvaRoot)
    in Switch (created by DvaRoot)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by DvaRoot)
    in LocaleProvider (created by DvaRoot)
    in Provider (created by DvaRoot)
    in DvaRoot

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.`

这个有办法解决吗？
（我直接预览官方的demo，在这种模式下是正常的。）

**Comment by gamemore** [comment]
我用 IE10 看 這裡是正常的 https://preview.pro.ant.design

**Comment by nixinhua001** [comment]
@gamemore 是在开发环境下报错

**Comment by zhuozp** [comment]
https://preview.pro.ant.design 打不开，空白
浏览器：360极速浏览器
IE版本：IE11
报错信息如下：
TypeError: 对象不支持“find”属性或方法 
Unhandled promise rejection TypeError: 对象不支持“find”属性或方法
