### ISSUE TITLE
吐槽一下form组件

### ISSUE THREAD

**Issue by ilaipi** [ant-design/ant-design-pro#1443]
不知道我对不对。示例中，`form`组件的`namespace=form`，但是`From.create()`好像也会生成一个`form`的`prop`，然后在`connect`的时候，不能传`form`，传了的话`form`的一些方法就没有了。

但是不传，在reducer中的数据就拿不到了。

**Comment by dengfuping** [comment]
@ilaipi `connect` 的时候可以把传入的 `props` 名改一下避免重名就行：

```
function mapStateToProps({ form }) {
  return {
    formProp: form,
  };
}
```

然后通过 `this.props.formProp` 访问即可。

**Comment by ilaipi** [comment]
@dengfuping 谢谢，我是直接从外面把`namespace`给改了。当时比较晕了，没想到这招。谢谢啦
