### ISSUE TITLE
Throw error when testing dva wrapped components

### ISSUE THREAD

**Issue by kofwang** [ant-design/ant-design-pro#1444]
What I've done was following document like this:
`import React from 'react';
import { shallow } from 'enzyme';
import MyPage from './MyPage';

it('renders MyPage', () => {
  // Use the wrapped components
  const wrapper = shallow(
    <MyPage.WrappedComponent user={{ list: [] }} />
  );
  expect(wrapper.find('Table').props().dataSource).toEqual([]);
});`

It throws a error:
`
TypeError: this.props.dispatch is not a function

      12 |   componentDidMount() {
      13 |     const { match } = this.props;
    > 14 |     this.props.dispatch({
      15 |       type: 'product/fetch',
      16 |       payload: { name: match.params.service },
      17 |     });
`
What am I suppose to fix this issue? It seems like this.props doesn't have function dispatch.

**Comment by afc163** [comment]
```js
const mockDispatch = jest.fn();
const wrapper = shallow(
<MyPage.WrappedComponent user={{ list: [] }} dispatch={mockDispatch} />
);
```
