### ISSUE TITLE
Ellipsis optimize cover style

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#145]
use: https://developer.mozilla.org/en-US/docs/Web/CSS/calc ?

it seems can't @afc163

**Comment by afc163** [comment]
https://medium.com/mofed/css-line-clamp-the-good-the-bad-and-the-straight-up-broken-865413f16e5

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/commit/b6570f15fc614b1480e072e37cb09458f4a66abb
