### ISSUE TITLE
NoticeIcon.Tab样式丢失

### ISSUE THREAD

**Issue by keithWSY** [ant-design/ant-design-pro#1450]
![image](https://user-images.githubusercontent.com/25559566/39695128-13d288ca-521c-11e8-986b-b9063e361442.png)
如题，使用了最新的NoticeIcon组件，发现样式失效，是我使用的方式不对么？ 
ps:( import NoticeIcon from 'ant-design-pro/lib/NoticeIcon'; 直接引用然后使用的demo数据 )

**Comment by keithWSY** [comment]
发现从npm中获取 NoticeList.less 和 index.less 和 github 上的文件名不同 
![image](https://user-images.githubusercontent.com/25559566/39698556-e442d298-5227-11e8-905d-63e46a504e38.png)
本地使用的是1.3.0 版本

**Comment by chenshuai2144** [comment]
全局引入css?
