### ISSUE TITLE
src\index.ejs: SyntaxError: Unexpected token  Error

### ISSUE THREAD

**Issue by Lubyam** [ant-design/ant-design-pro#1453]
1、 git clone https://github.com/ant-design/ant-design-pro.git --depth=1
2、modify some file.
3、commit and push ( selected  Run Git hooks)
![1](https://user-images.githubusercontent.com/7630366/39734764-3094cce0-52ab-11e8-9ef0-abe12dc4f36b.png)

**Comment by chenshuai2144** [comment]
i will fix it

**Comment by Lubyam** [comment]
thank you
