### ISSUE TITLE
Configuration in eslint, restrict file extension to .js

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design-pro#1455]
https://github.com/ant-design/ant-design-pro/blob/c92252f91281fe976e2e0e066113a6999bc91346/.eslintrc.js#L16

I'm wondering why restricting file extension to .js only? Because using .jsx should be more intuitive.

**Comment by afc163** [comment]
There is no need to diff from '.js' and '.jsx', it is all JavaScript.
