### ISSUE TITLE
使用request请求文件下载的接口后不会下载文件，是不是被什么配置拦截了？

### ISSUE THREAD

**Issue by zhuaizhuaixi** [ant-design/ant-design-pro#1456]
### 在api里写了个request请求一个后台的下载：

![api](https://user-images.githubusercontent.com/25663763/39752719-de881e68-52ee-11e8-8733-3afcd42508bd.png)

### 点击调用该api后，查看F12中的Network的确有请求成功，但不会出现下载：

![image](https://user-images.githubusercontent.com/25663763/39753071-22adb4c6-52f0-11e8-9827-f12f433c2e70.png)

### 但直接在浏览器地址输入的话，就能成功下载：
![image](https://user-images.githubusercontent.com/25663763/39753139-51714458-52f0-11e8-996e-e7f2f05f80ef.png)
![image](https://user-images.githubusercontent.com/25663763/39753207-8b7054be-52f0-11e8-9a2f-ca8d2b83e848.png)

**Comment by chenshuai2144** [comment]
use window.open

**Comment by zhuaizhuaixi** [comment]
@chenshuai2144 用window.open的话会跳出一个窗口，而且只接受get请求，请问有别的解决办法吗。

**Comment by friendlove** [comment]
@zhuaizhuaixi 遇到同样的问题，请问您解决了吗，求教

**Comment by zhuaizhuaixi** [comment]
@friendlove 我后来用隐藏表单提交的方式实现了，你可以网上查查，有相关代码

**Comment by xsy19960608** [comment]
request.interceptors.response.use(async response => {
  const data = await response.clone().json();

**Comment by chenshuai2144** [comment]
看看这个把，fetch 下载文件比较麻烦，不如用传统的方式

https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API

**Comment by xsy19960608** [comment]
谢谢！
