### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by ChenGeroge** [ant-design/ant-design-pro#1459]
./src/routes/List/List.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)

**Comment by ChenGeroge** [comment]
试过 重新install很多次 ，缓存也清了，node也重装过，仍然这个错误。

**Comment by afc163** [comment]
先搜索一下：https://github.com/ant-design/ant-design-pro/pull/1345
