### ISSUE TITLE
自定义的webpack.config.js  如何引入到项目中 使得配置生效

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design-pro#1461]
Can't add new less-loader through module. If you want to configure less-loader, add excluded less file, how to deal with？
the author says this way: add a flie named webpack.config.js
export default webpackConfig => {
  // change less loader
  return webpackConfig;
};
But I have a new problem!
Thanks for your time!
then I import webpack.config.js to .webpackrc.js,but what is the key likes env, alias,how I can use webpack.config.js in the file .webpackrc.js
this is demo about .webpackrc:
```
export default {
entry: 'src/index.js',
extraBabelPlugins: [
// 'transform-decorators-legacy',
['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
],
env: {
development: {
extraBabelPlugins: ['dva-hmr'],
},
},
alias: {
components: path.resolve(__dirname, 'src/components/'),
},
ignoreMomentLocale: true,
theme: './src/theme.js',
html: {
template: './src/index.ejs',
},
disableDynamicImport: true,
publicPath: '/',
hash: true,
};
```

**Comment by chenshuai2144** [comment]
like this

```
export default webpackConfig => {
  //do some things
  return webpackConfig;
};
```

**Comment by zsl1549** [comment]
https://github.com/ant-design/ant-design-pro/issues/1461#issuecomment-387927271

**Comment by zsl1549** [comment]
It doesn't say where it comes from, right?
