### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by taoqianbao** [ant-design/ant-design-pro#1463]
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)

**Comment by taoqianbao** [comment]
Failed to compile.

./src/routes/List/Projects.js

**Comment by afc163** [comment]
Search issues before creating new issue.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/search?q=AssignmentExpression&type=Issues
