### ISSUE TITLE
chrome devtools 出现  error"There is no clipping info for given tab " ?  

### ISSUE THREAD

**Issue by billychou** [ant-design/ant-design-pro#1464]
这个报错具体是什么造成的?  求解.
![image](https://user-images.githubusercontent.com/3585362/39804373-700605be-53a6-11e8-90c1-ac6a404ac7d0.png)

**Comment by chenshuai2144** [comment]
it looks like chrome got an error.
You can ask questions on  StackOverflow.

**Comment by sncer** [comment]
It's raised by Evernote Web Clipper, disable this extension will make chrome get rid of this error.

**Comment by billychou** [comment]
Thanks.
