### ISSUE TITLE
Could you tell me the font in the term2 ? It's so beautiful

### ISSUE THREAD

**Issue by Oscar-ren** [ant-design/ant-design-pro#1465]
![image](https://user-images.githubusercontent.com/9464221/39808539-c6783aba-53b1-11e8-883c-1dc69b40da47.png)

Sorry, I don't find the way to resolve my question, so I submit an issue.

Thanks.

**Comment by afc163** [comment]
<img width="125" alt="image" src="https://user-images.githubusercontent.com/507615/40064404-095045c8-5892-11e8-8177-0556732f4e87.png">
