### ISSUE TITLE
编译机器最低配置问题

### ISSUE THREAD

**Issue by mingjunyang** [ant-design/ant-design-pro#1466]
问题描述
在1核2g内存的云主机上做自动构建配置（jenkins限制最大500m内存，还有一些其他服务，构建使用的内存约1g左右）。

npm run build 之后未能构建出dist文件夹，结果显示如下：
```text
# 忽略前面信息。
dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2952 packages in 93.523s
+ npm run build
> ant-design-pro@1.3.0 build /home/xxxx/.jenkins/workspace/ant_build_test
> cross-env ESLINT=none roadhog build

(node:3014) ExperimentalWarning: The fs.promises API is experimental
Finished: SUCCESS
```

1. 使用 nodejs 9.11.1 失败。
2. 使用 nodejs 10.1.0 失败。（上面的失败信息是用 10.1.0 时候显示的）
3. 构建过程中cpu和内存都跑满了。

请问有人测试过编译机器的最低配置么？

正常构建成功会显示构建出来的文件列表和生成dist文件夹。

**Comment by mingjunyang** [comment]
补充信息：重新开了一台2核4g的机器能编译成功。整个编译过程cpu占用大约50%，内存使用最高大约1.3g。

![image](https://user-images.githubusercontent.com/2757223/39828599-4003d394-53ee-11e8-805c-7d6512e3aa6e.png)


![image](https://user-images.githubusercontent.com/2757223/39828766-d1f3d0ce-53ee-11e8-90bf-13f2ec75ba41.png)

**Comment by wunayou** [comment]
这个有意思  我也想知道 解决方案

**Comment by mingjunyang** [comment]
掏钱加内存，简单粗暴。

**Comment by chenshuai2144** [comment]
这个暂时无解 主要是因为 压缩代码的原因。
