### ISSUE TITLE
报错页会出现中文乱码

### ISSUE THREAD

**Issue by callmez** [ant-design/ant-design-pro#1467]
新建的一个测试项目. 出错页中文会乱码

![image](https://user-images.githubusercontent.com/1625891/39848540-12ae23c6-543a-11e8-8c47-de85bb0323b7.png)

**Comment by callmez** [comment]
只是希望能修复

**Comment by chenshuai2144** [comment]
试着改一下命令行的字符编码到 utf-8

**Comment by callmez** [comment]
mac下的终端 就是utf-8的吧?  是mac环境出现的乱码..
