### ISSUE TITLE
[高级表单]  Input(仓库域名) Display abnormally

### ISSUE THREAD

**Issue by smk0621** [ant-design/ant-design-pro#1468]
Input(仓库域名) is used  prototype addonAfter and addonBefore, but the display of page is abnormal.

form .ant-input-group, form .ant-input-group-wrapper {
    display: flex; inline-block  //本行的影响，注释后式样正常
    vertical-align: middle;
    position: relative;
    top: -1px;
}

Would you please fix this issue?
![input display error](https://user-images.githubusercontent.com/9047380/39851389-1d3b8892-5449-11e8-99ad-756376ff57e8.png)

**Comment by chenshuai2144** [comment]
You can support it yourself
weclom pr.

**Comment by afc163** [comment]
Fixed in antd@3.5.1

**Comment by smk0621** [comment]
Thank you for fixed it in antd@3.5.1

Comment:
If do not want to update antd@3.5.1, it could be override the css style:
:global {
  form .ant-input-group, form .ant-input-group-wrapper {
    display: inline-table !important;
  }
}
