### ISSUE TITLE
API proxy route configuration

### ISSUE THREAD

**Issue by Colstuwjx** [ant-design/ant-design-pro#1469]
Hi team,

我这边设置了roadhog的proxy:

```
  "proxy": {
    "/api/v1": {
      "target": "http://127.0.0.1:8080",
      "changeOrigin": true
    }
  },
```

但是发现可能由于common/router.js的部分，导致`/api/v1/*`的请求会被重定向，例如：`http://localhost:8000/api/v1/applications/all`会变成`http://localhost:8000/api/v1/applications/all#/application/builds`

请问应该如何设置api route？谢谢！

**Comment by chenshuai2144** [comment]
You should use a different route than api
