### ISSUE TITLE
logout 后 localhost:8000/#/home 怎么都打不开

### ISSUE THREAD

**Issue by CherryaMao** [ant-design/ant-design-pro#1473]
页面正常的时候，点了头部右上角的退出登录后，localhost:8000/#/home怎么都打不开，直接跳的了http://localhost:8000/#/user/login这个上面，控制台的警告为Warning: You tried to redirect to the same route you're currently on: "/user/login"；

问题是：点击退出怎么跳到登录页面，然后怎么直接localhost:8000/#/home这个页面？

**Comment by chenshuai2144** [comment]
权限组件控制的。。你为什么需要退出登录去访问home？
