### ISSUE TITLE
antd-pro的组件的字体库和antd组件的字体库是用的一个吗？

### ISSUE THREAD

**Issue by emmmpro** [ant-design/ant-design-pro#1474]
我在本地设置了antd组件访问本地字体，具体方法https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont，但是当我引用antd-pro组件时又访问了云端的字体库https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.woff。

**Comment by chenshuai2144** [comment]
yes
