### ISSUE TITLE
egg-ant-design-pro 很多问题

### ISSUE THREAD

**Issue by doocal** [ant-design/ant-design-pro#1475]
egg-ant-design-pro 这个整合的项目本地跑不起来，有不少错误。也不方便升级，合并的项目里面的路径相关都换了。建议自家的产品能很方便的整合和升级。

./app/assets/routes/List/List.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/search?q=AssignmentExpression&type=Issues

提问前先搜索。

#1345 

另外，egg-ant-design-pro 的问题建议提到 egg-ant-design-pro。

**Comment by doocal** [comment]
@afc163 
这里只是说明一下问题，还有未解决或已解决的错误未贴出来，egg-ant-design-pro 项目是不接受提交问题的。
