### ISSUE TITLE
HearderSearch组件中，实现后台数据查询，查询后打开其他相关的功能页面显示对应数据问题

### ISSUE THREAD

**Issue by bobenut** [ant-design/ant-design-pro#1476]
HearderSearch组件是GloabalHeader组件中的搜索部分。
1.现在需求想是在搜索框中查询应用支持的功能，这部分查询需要从后台获取，是不是可以像routes下面的各个路由组件绑定model，用dispatch的方式从后台获取数据。或者有没有推荐的其他方法。
2.在搜索框中查询到期望的功能后，点击某个功能，是不是可以通过hashHistory.push一个路由进行跳转，但是如果还要带点参数传到被路由的组件里该如何。

**Comment by chenshuai2144** [comment]
> .现在需求想是在搜索框中查询应用支持的功能，这部分查询需要从后台获取，是不是可以像routes下面的各个路由组件绑定model，用dispatch的方式从后台获取数据。或者有没有推荐的其他方法。

这个办法就不错了

> 在搜索框中查询到期望的功能后，点击某个功能，是不是可以通过hashHistory.push一个路由进行跳转，但是如果还要带点参数传到被路由的组件里该如何

react-router 支持 params

**Comment by bobenut** [comment]
在组件的顶上用connect 关联model就可以了？
