### ISSUE TITLE
New component: Search Input.

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#1477]
like antd Search Input.

#### feature 
-    history list
-    support select 

<img width="420" alt="2018-05-11 10 33 20" src="https://user-images.githubusercontent.com/8186664/39903643-c37a46e0-5506-11e8-9616-bf8906dde89a.png">

**Comment by zhang0ZGC** [comment]
没有重置么。。。

**Comment by heya-aron** [comment]
。。。这是否仍然需要？

**Comment by chenshuai2144** [comment]
如果你愿意pr，我们很欢迎

**Comment by heya-aron** [comment]
Do you have examples of History List? Do you mean most recent search?
