### ISSUE TITLE
ie(10+) will have an error when i user an antd component in onError of index.js

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design-pro#1481]
if i add onError() in index.js like this:
````
import { message } from 'antd'
import '@babel/polyfill';
import 'url-polyfill';
import dva from 'dva';

import createHistory from 'history/createHashHistory';
const app = dva({
  history: createHistory(),
  onError(e, dispatch){
    console.log(e.msg);
    e.preventDefault();
    message.error("sdfasdfasd");
  },
});
````
if i use "message.error('sdfasdfasd')" in onError, ie(10+) will have an error and the page is blank like this:
![image](https://user-images.githubusercontent.com/4796185/39955023-fd888978-55fb-11e8-8e67-8bb2d91c7217.png)

but when I delete the import of antd and void to user antd component here. it works normal.I think this is a  bug!

**Comment by chenshuai2144** [comment]
Due to the lack of personnel, we do not promise to support ie10.
You can  PR to solve this problem

**Comment by chenshuai2144** [comment]
I will try！

**Comment by chenshuai2144** [comment]
https://reactjs.org/docs/error-decoder.html?invariant=143

It does not seem to be our fault. You may need to wait for a while before using it.

**Comment by junliuxian** [comment]
I also met, how to solve it?
