### ISSUE TITLE
ant design pro  案例中没有使用富文本编辑  那么大家用什么富文本编辑器呢？

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#1482]
大家 都用什么富文本编辑  推荐 让我们这种菜鸟  少进坑   

例如我找到这二个 还没有测试 
1 draft.js 
2 react-draft-wysiwyg

**Comment by ilaipi** [comment]
编辑器的话 建议单独使用百度的 [ueditor](http://ueditor.baidu.com/website/)

**Comment by chenshuai2144** [comment]
draft 需要很高的技术实力。
你可以试试 wangeditor 这些的

**Comment by wunayou** [comment]
为什么关掉呢？ 我这个钓鱼贴 还没有钓到啊，哎呀 算了 还是我一个一个 去测试去
