### ISSUE TITLE
SiderMenu中的menuData不能随点击事件改变 

### ISSUE THREAD

**Issue by 290352095** [ant-design/ant-design-pro#1487]
点击按钮，改变menuData的数据，打印出来数据已经变了 ，但是菜单内容不变，怎么 处理下，或者有什么其他办法？

**Comment by chenshuai2144** [comment]
为什么需要改变？

**Comment by 290352095** [comment]
@chenshuai2144    想要在globalHeader的中间加上一级菜单  然后sliderMenu用作二级菜单，二级菜单要根据一级菜单的变化而变化

**Comment by 290352095** [comment]
@chenshuai2144 
![qq 20180515091310](https://user-images.githubusercontent.com/23628090/40031052-611c5818-5820-11e8-8adb-964e88995a68.png)

**Comment by chenshuai2144** [comment]
getMenuData = () => formatter(menuData)
把这个重写掉！

**Comment by 290352095** [comment]
@chenshuai2144   谢谢指导 我看一下

**Comment by 290352095** [comment]
@chenshuai2144 其实问题不在那个方法，二三级的菜单结构不变，在外面套了一层而已，问题在于slidermenu组件中  this.getNavMenuItems(this.menus)  这个写法，这样写，slider中的数据不会随外面的传进来的menuData的改变而改变，写成this.getNavMenuItems(this.props.menuData)  就可以同步变化了

**Comment by 290352095** [comment]
@chenshuai2144 写成this.getNavMenuItems(this.props.menuData)  有什么弊端吗？
