### ISSUE TITLE
刚下载新的Pro代码，npm run build失败

### ISSUE THREAD

**Issue by streamlong** [ant-design/ant-design-pro#1488]
我的操作流程是：先通过官网提供的命令：git clone, 然后在项目里面执行npm install ->  npm run build, 结果就出现了下面的错误提示，请问这种该怎么解决？我之前也下载过，都没有出现过这种情况，就今天下载出现了这个问题。

Failed to compile.

./src/routes/Dashboard/Analysis.js
Syntax error: /src/routes/Dashboard/Analysis.js: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (53:0)

  51 |   loading: loading.effects['chart/fetch'],
  52 | }))
> 53 | export default class Analysis extends Component {
     | ^
  54 |   state = {
  55 |     salesType: 'all',
  56 |     currentTabKey: '',

[graceful-process#843] exit with code:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.3.0 build: `cross-env ESLINT=none roadhog build`
npm ERR! Exit status 1

**Comment by xjchenhao** [comment]
我也遇到了 项目一直使用jenkins build的 今天突然就build失败了 可能是模块依赖更新了吧 求合理的处理方式。。

**Comment by liuyuqian365** [comment]
我也遇到了！顶起

**Comment by Viin-zx** [comment]
第一次使用，也遇到了这种情况

**Comment by zhaohejing** [comment]
Failed to compile.

./src/routes/Dashboard/Analysis.js
Syntax error: D:\projects\ant-design-pro\src\routes\Dashboard\Analysis.js: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (53:0)

  51 |   loading: loading.effects['chart/fetch'],
  52 | }))
> 53 | export default class Analysis extends Component {
     | ^
  54 |   state = {
  55 |     salesType: 'all',
  56 |     currentTabKey: '',


同样遇到了。

**Comment by streamlong** [comment]
把本地lock文件删除了，node_modules删除，然后在重新执行yarn install ->  yarn build -> yarn start，可以访问了，然后我又重新新建了一个目录测试，在从官网拉取代码，install， build，start，一路顺到底。感觉应该是跟本地环境有关系，大家遇到同类问题，可以试试这一笨方法，😄

**Comment by xjchenhao** [comment]
我啥都没做 已经能用了...

**Comment by bartly** [comment]
怎么我就是3.5.2但还是不行呢

**Comment by Viin-zx** [comment]
@bartly  用 @streamlong 说的 yarn 可以。

**Comment by chenshuai2144** [comment]
国内网络有波动 尽量是用 cnpm 或者换成淘宝源

**Comment by FeengQi** [comment]
@xjchenhao jenkins部署失败的问题解决了么
