### ISSUE TITLE
关于roadhog  mock  Proxy中post请求的body问题

### ISSUE THREAD

**Issue by zhongxx** [ant-design/ant-design-pro#149]
期望是以form-data的形式将参数提交到后端，类似于jquery的$.post("url",{value:321})
可是经过代理转发出去的请求，却无法在后端正确的收到请求参数，后端收到的request.getParameterMap()中显示key:value已经变为了"{value:321}":""，而不是预期的"value":"321"。

**Comment by nikogu** [comment]
最好提供下 chrome network 的截图，看看你的请求的输入输出

**Comment by zhongxx** [comment]
跟了跟代码，最终发现是roadhog的mock.js中使用了body-parser。
转换前body内容：testValue=23211
body-parser将其转换为{"testValue":"321"}
因为我将headers中的content-type改为application/x-www-form-urlencoded; charset=UTF-8
最终后端接收到的request.getParameterMap()将body内容均识别为key，而内容是空的。
对body-parse了解不深，不知道有没有办法跳过转换的相关配置

**Comment by zhongxx** [comment]
@nikogu   request.js中不打算支持form-data提交吗？

**Comment by nikogu** [comment]
@zhongxx 那个 `request.js` 是封装的，你先可以自行修改成需要兼容的方式

参看：https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js#L32，都是可以配置的

**Comment by hezhijun** [comment]
可以用axios吗？

**Comment by ndc411** [comment]
@nikogu 自己写了兼容处理，将对象用了qs.stringfy做了转换，但是后台接受的数据却成了这个样子：FormData{values={{"mobile":"13900000001","password":"123456","answer":"exb3","type":"account"}=[io.undertow.server.handlers.form.FormData$FormValueImpl@54d729cc]}}，不符合预期啊

**Comment by chenshuai2144** [comment]
你的处理错了把。。。这个把FormData 直接穿过去了。

**Comment by ndc411** [comment]
@chenshuai2144 
这是我做的处理，你看有什么异常么？
![1516683719633](https://user-images.githubusercontent.com/18413131/35258927-b86ac6b2-003d-11e8-8522-95800ebf988c.jpg)

**Comment by chenshuai2144** [comment]
看看这个  
https://developer.mozilla.org/zh-CN/docs/Web/API/FormData/Using_FormData_Objects
FormData 不用qs。但是需要把头信息修改为multipart/form-data

**Comment by Aruna1990** [comment]
@zhongxx 这个问题最后怎么解决的，我碰到了同样的问题

**Comment by chenshuai2144** [comment]
cc #973

**Comment by wuyongdec** [comment]
同问一下请求格式是：Content-Type:application/json，该怎么写？

**Comment by BeAce** [comment]
`.webpackrc.js`
```javascript
proxy: {
    "/api": {
      "target": "https://mpki-test.trustasia.com/api/",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
}
```
参考 [roadhog](https://github.com/sorrycc/roadhog#proxy)
