### ISSUE TITLE
Using the export keyword between a decorator and a class is not allowed

### ISSUE THREAD

**Issue by bartly** [ant-design/ant-design-pro#1490]
hi ：
    there is a question in my local env , "Using the export keyword between a decorator and a class is not allowed", is there any help for me? I did not modified any code in the original demo. Just do as steps below:
    1, clone the code from github
    2, npm install
    3, npm start
then it happened , can anybody figure it out?
Syntax error: /Users/bartly/hqBackend/src/routes/Dashboard/Analysis.js: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead (53:0)

  51 |   loading: loading.effects['chart/fetch'],
  52 | }))
> 53 | export default function Analysis extends Component {
     | ^
  54 |   state = {
  55 |     salesType: 'all',
  56 |     currentTabKey: '',
^C

**Comment by Q956164483** [comment]
我的也是，今天下载最新的，直接yarn 然后 run start就报这个错

**Comment by bartly** [comment]
I figured it out:
1, npm remove antd
2,npm install antd --save
3,rm all code downloaded before, than git clone it 
4,npm install
5,npm start 
6,then it worked
