### ISSUE TITLE
使用pro new无法下载脚手架

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design-pro#1491]
![image](https://user-images.githubusercontent.com/4182865/40042349-9c314b7e-5853-11e8-8eda-faf475d546c7.png)

**Comment by nikogu** [comment]
@chenshuai2144 你把那两个分支都给删了吗。。。。。。 💢

**Comment by nikogu** [comment]
@wzlee 升级到 1.0.0 就可以了，现在只有标准的脚手架，其它的暂时不支持了哈
