### ISSUE TITLE
页面一直停留加载，并且点击查询没有调用接口。

### ISSUE THREAD

**Issue by qingming418** [ant-design/ant-design-pro#1492]
![image](https://user-images.githubusercontent.com/20061205/40054629-265a73ec-5878-11e8-8600-d32a04d05554.png)
该问题也是偶然性出现，重新刷新下该界面又可以了。但是不定时的会出现某些页面，出现后后台也没返回错误，然后再也不能调用后台数据接口了。

**Comment by afc163** [comment]
业务代码问题请自行排查。

**Comment by qingming418** [comment]
有时候某个api返回错误后，以后这个api都调不了，也就是以后都不能发起请求，这是fetch阻塞，还是其他什么原因呢？
