### ISSUE TITLE
固定行列的时候，在size="small"，bordered=true的情况下，少了一个边框线。

### ISSUE THREAD

**Issue by roc2539** [ant-design/ant-design-pro#1496]
Table
            columns={columns}
            dataSource={data}
            scroll={{ x: 1500, y: 300 }}
            size="small"
            bordered

![111](https://user-images.githubusercontent.com/22289965/40095551-4843e664-58ff-11e8-9bd9-59164085b08d.png)

**Comment by roc2539** [comment]
![111](https://user-images.githubusercontent.com/22289965/40095530-360af30c-58ff-11e8-88fb-70e4c63b535c.png)

**Comment by chenshuai2144** [comment]
should go to antd ask questions
