### ISSUE TITLE
查询表格的查询功能还有一个小Bug

### ISSUE THREAD

**Issue by mutouzdl** [ant-design/ant-design-pro#1497]
以前提过一次：#1209  ，后来修复了，但是又有新问题了，重现步骤：
- 进入官网查询表格页面
- 对状态进行筛选，选择【关闭】状态
- 对规则编号进行搜索，搜索条件为【1】
- 实际上只有5条数据，但分页组件出现了2页
![image](https://user-images.githubusercontent.com/3509249/40098984-a15b9664-5910-11e8-92d3-639cc5cdcd96.png)

**Comment by mutouzdl** [comment]
@chenshuai2144 限制条件倒没有，但是操作顺序一定要先筛选，然后再搜索。
这个是每次都会的，不是偶然发生，所以应该能重现的，注意顺序。

**Comment by zhang0ZGC** [comment]
只要是勾选了状态筛选然后搜索任意值，都会出现这情况哎

**Comment by mutouzdl** [comment]
我之前看了一下，筛选功能是在客户端进行的（不知道后来改了没）。
这样会导致：如果有10条以上的数据过来，但是显示的时候做了筛选，看起来就只有几条数据。而实际上分页之类的还是按照实际数量来控制的，这样就会出现这个Bug。

在查询这一块，我没有按照官方的套路来，但是我自己处理的不是很好，总有一些小冲突需要特殊处理，希望antd pro能给个比较好的参考。
目前参考的意义不是很大，在涉及到进入详情页然后返回、弹出Modal并且Modal里又调用了相同的查询接口等比较复杂的情况的处理都没有展现出来。

如果大家能讨论一下就太好了，我作为一个兼顾前端的后端人员，只能抱大家的大腿了...

**Comment by chenshuai2144** [comment]
我们也有做成真正后台的想法 现在是静态化的

**Comment by mutouzdl** [comment]
期待官方的实现，辛苦了

**Comment by chenshuai2144** [comment]
fixed in v2 
look https://beta.preview.pro.ant.design/#/dashboard/analysis
