### ISSUE TITLE
问题请教：后台管理系统越来越大，如何把工程拆分成小项目

### ISSUE THREAD

**Issue by taoqianbao** [ant-design/ant-design-pro#1498]
这里面如果用ant-design的话，我就是不太好处理，比如，菜单部分的共同的部分组件；如何设计？   

有没有比较好的案例分享？

**Comment by chenshuai2144** [comment]
你可以把分支代码打包成.js 
在主项目里面直接引用

**Comment by taoqianbao** [comment]
hi,  can help me , how to use the js from the main project ?

**Comment by chenshuai2144** [comment]
Just an idea！
But all big projects have similar plans~
