### ISSUE TITLE
Module build failed: Error: Cannot use decorators and decorators2 plugin together

### ISSUE THREAD

**Issue by meluo** [ant-design/ant-design-pro#1499]
Module build failed: Error: Cannot use decorators and decorators2 plugin together! why?

**Comment by NickFranceschina** [comment]
same

**Comment by cesar-blog** [comment]
I hava the same problem.

Env:
node:10.0.0
yarn:1.6.0
ant-design-pro:1.1.0

system env:
mac os 10.13.4

console print:
./src/index.js
Module build failed: Error: Cannot use decorators and decorators2 plugin together

**Comment by chenshuai2144** [comment]
https://github.com/babel/babel/issues/2691
Is this helpful to you?

**Comment by taoqianbao** [comment]
when i use :"roadhog-api-doc start",  it shows the same error; 
but it's ok for "npm run start", 
I'm sure I have already remove  "transform-decorators-legacy"

**Comment by CareyToboo** [comment]
@taoqianbao  you can see the same code in the source code of `roadhog-api-doc` project. Maybe for resolve this problem, you should commit a issue to  `roadhog-api-doc` project. and then change the new version of `roadhog-api-doc` in your package dependencies.
https://github.com/nikogu/roadhog-api-doc/blob/f07739a0936dca5d13bb0b6cc7adaee87229f14a/boilerplate/.webpackrc#L3-L6

**Comment by ldw21cn** [comment]
> @meluo @cesar-blog I also had met the same problem.
> 
> there is the code in `.webpackrc.js` at old version .
> 
> ```
> extraBabelPlugins: [
>     'transform-decorators-legacy',
>     [
>       'import',
>       {
>         libraryName: 'antd',
>         libraryDirectory: 'es',
>         style: true,
>       },
>     ],
>   ],
> ```
> now , it has updated at new relase.
> 
> [ant-design-pro/.webpackrc.js](https://github.com/ant-design/ant-design-pro/blob/ec8f082284becca5dad63672beadd6ae6a3777ac/.webpackrc.js#L5-L7)
> 
> Lines 5 to 7 in [ec8f082](/ant-design/ant-design-pro/commit/ec8f082284becca5dad63672beadd6ae6a3777ac)
> 
>  extraBabelPlugins: [ 
>    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }], 
>  ], 
> So, I resolve it with the ` 'transform-decorators-legacy,'` line removed.
> Hope it can help.




我通过更改这个解决了。

{
  "entry": "src/index.js",
  "extraBabelPlugins": [
     ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],

**Comment by dengtingsheng** [comment]
thanks
