### ISSUE TITLE
关于打包发布的问题

### ISSUE THREAD

**Issue by QAKill** [ant-design/ant-design-pro#1502]
打包发布时e2e的测试用例是否会打入包内.
我现在的需求是这样的 将本地的项目打包后放到服务器上,但是不需要和服务器做交互,只是演示用的Demo.
但是放到服务器上后我发现他是真的在请求接口而不是使用测试用例.
我是做Android的 不太懂这些. 有没有大佬可以帮助我一下哈.
![d7c656a1736252aada34fbdacaba8c02](https://user-images.githubusercontent.com/34436821/40156325-6acf32b6-59cb-11e8-8997-19ad13148076.jpg)

**Comment by chenshuai2144** [comment]
use `roadhog-api-doc static`

**Comment by QAKill** [comment]
不好意思 我不太明白咋使用这个 ,您能说详细点嘛, 麻烦了.

**Comment by QAKill** [comment]
我看了 这个不是生成文档嘛  我是想要数据啊
