### ISSUE TITLE
如何将项目发布后仍使用测试数据.

### ISSUE THREAD

**Issue by QAKill** [ant-design/ant-design-pro#1503]
目前只是做测试demo,在修改了几个页面的UI后,使用npm run build 后将生产的dist文件夹下面的文件放到外网服务器上访问,页面正常打开,但在进行登录操作室提示如下.
![d7c656a1736252aada34fbdacaba8c02](https://user-images.githubusercontent.com/34436821/40158260-0e144ede-59d6-11e8-8162-dff9bf90fab5.jpg)
如何继续使用测试数据继续访问呢.

**Comment by chenshuai2144** [comment]
请认真看！https://github.com/nikogu/roadhog-api-doc
历史issue里面也有说明
