### ISSUE TITLE
如何在服务端使用mock数据.

### ISSUE THREAD

**Issue by QAKill** [ant-design/ant-design-pro#1505]
我是真没搞懂 
 使用roadhog-api-doc static能解决?
还是部署到服务端后只能用真是数据

**Comment by chenshuai2144** [comment]
你为什么不愿意试一试再来提问？你运行一下命令就能看见结果了。
而且 github 并不是提问的地方。如果要弄懂原理请去 https://stackoverflow.com/

**Comment by QAKill** [comment]
不好意思 跟您添麻烦了  我试了 但是可能是我弄错了过程.
刚刚成功了 谢谢您的指导 .
