### ISSUE TITLE
请问如果API SERVER有多台，如何使编译后的js文件包含Proxy的API地址

### ISSUE THREAD

**Issue by meccain** [ant-design/ant-design-pro#1507]
比如
proxy:{"/auth/userAuth":{target:"xxx.xxx.xxx.xxx:8080"}
          “/news/newsfeed”:{target:"yyy.yyy.yyy.yyy:8081"}
          }
在api.js并不包含接口的host信息，如何通过编译（build）之后的静态文件中能将proxy的host地址保留。

多谢！

**Comment by chenshuai2144** [comment]
nginx 反向代码

**Comment by MartinLongYW** [comment]
使用nginx去代理，不是在前端处理的。使用nginx去分发

**Comment by ChimingPhang** [comment]
@MartinLongYW nginx代理之后，好慢，请问你怎么解决的？
