### ISSUE TITLE
fetch is very slow

### ISSUE THREAD

**Issue by wi-cuckoo** [ant-design/ant-design-pro#1508]
最近发现项目请求 API 的时间变得非常慢，通常一个1k 左右的请求需要花费 170ms 之多，如图：
![image](https://user-images.githubusercontent.com/10881737/40175387-812cc246-5a0a-11e8-8a60-84a4b8e58794.png)

点进某个请求发现主要耗时在 content downloading 阶段：
![image](https://user-images.githubusercontent.com/10881737/40175419-a20f5172-5a0a-11e8-9f50-3e196b04714e.png)

检查后端接口，使用 postman 来请求，耗时只在 30ms 以下。找了一圈不知道原因出在哪，我没用动 request.js 文件，所有请求都是用仓库封装好的 request 库发起的，希望能在这里得到解答下

**Comment by chenshuai2144** [comment]
是不是开了代理？

**Comment by wi-cuckoo** [comment]
@chenshuai2144 本地是有代理，但没道理同一个请求，放 postman 就只要 30ms，页面发出来就得要 170ms呀

**Comment by wi-cuckoo** [comment]
@chenshuai2144 

从页面发出的请求：
```
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,ru;q=0.6,ja;q=0.5
Connection:keep-alive
Cookie:xxx
Host:my.host.com
Referer:https://my.host.com/apps?page=0&qs=&tags[0]=3&sortBy=gitlabProjectUpdateTime
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
```

浏览器直接 get 请求：
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,ru;q=0.6,ja;q=0.5
Cache-Control:max-age=0
Connection:keep-alive
Cookie: xxx
Host:my.host.com
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
```

这块我最初也想到了，但是没发现什么重要的差异

**Comment by chenshuai2144** [comment]
你自己写个原声 fetch 试试

**Comment by wi-cuckoo** [comment]
![image](https://user-images.githubusercontent.com/10881737/40216179-a4da4410-5a97-11e8-9089-48e3ee1b20b4.png)
我直接注释了这行 fetch 引入，下面应该就是原生调用 fetch 了，但是请求耗时没有改观。

**Comment by wi-cuckoo** [comment]
@chenshuai2144 想来想去，可能不是 fetch 本身的问题，是被什么其他东西影响到 fetch 接收数据了

**Comment by afc163** [comment]
这种问题和前端有关系的可能性很小。
