### ISSUE TITLE
npm start过后就一直是这个页面

### ISSUE THREAD

**Issue by wang5909912** [ant-design/ant-design-pro#1509]
![image](https://user-images.githubusercontent.com/26141772/40214572-1ffc0b38-5a8e-11e8-9b6a-7f5f39acfdd3.png)
一直这个页面，我也不知道配置了什么，求问这个怎么解决呢

**Comment by chenshuai2144** [comment]
删除 node module 然后用 cnpm 重新安装

**Comment by wang5909912** [comment]
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)


现在每个js都报这个错是为什么呢

**Comment by chenshuai2144** [comment]
看一下历史 issue

**Comment by JerryChenQue** [comment]
删除了node module 然后用 cnpm 重新安装之后  下次打开项目还是会出现这个问题

**Comment by JerryChenQue** [comment]
删除之后  重装还是卡在那里  根本没用

**Comment by wang5909912** [comment]
我重装了就好了，要用淘宝的镜像
