### ISSUE TITLE
How to get my app translated (International: Built-in i18n solution)

### ISSUE THREAD

**Issue by bar-maley** [ant-design/ant-design-pro#151]
How to get the "ant-design-pro" translated (International: Built-in i18n solution)? 
is react-intl needed (like this)
`this.renderMessage(<FormattedMessage id="login.wrong_account_or_password" defaultMessage="账户或密码错误"  />)`

or it have another built-in solution like:
`
this.renderMessage(i18n{'login.wrong_account_or_password'})
`

Thank you!

**Comment by bar-maley** [comment]
oh, sorry, i haven't seen, that i18n is not implemented yet

[i18n.md: 将会在下一个版本实现。](https://github.com/ant-design/ant-design-pro-site/blob/master/docs/i18n.md)

**Comment by nikogu** [comment]
you can help us : https://github.com/ant-design/ant-design-pro/issues/120
