### ISSUE TITLE
使用antd的Upload组件手动上传文件时，后端接收不到参数

### ISSUE THREAD

**Issue by sandm1227** [ant-design/ant-design-pro#1510]
前端代码：
![default](https://user-images.githubusercontent.com/25194203/40218128-79b9478a-5aa2-11e8-81d0-89446a8d1a36.png)

后端报空指针异常
![default](https://user-images.githubusercontent.com/25194203/40218549-423ba0d0-5aa4-11e8-9ba2-335b74765b7c.png)

**Comment by chenshuai2144** [comment]
chrome 控制台截图？

**Comment by sandm1227** [comment]
![qq 20180519200008](https://user-images.githubusercontent.com/25194203/40268512-5494013e-5ba1-11e8-8b32-24b984de24cd.png)

**Comment by sandm1227** [comment]
有传参数
![canshu](https://user-images.githubusercontent.com/25194203/40268574-bfc4fc5a-5ba2-11e8-8d4d-de91117b7f15.png)

**Comment by chenshuai2144** [comment]
看看你的后台吧 应该使用 file 作为参数名接收数据

**Comment by sandm1227** [comment]
把项目打包后dist文件放到服务上也是可以正常请求接口的，说明接口是正常的，发现问题是出现在了.roadhogrc.mock.js这里的代理问题
![default](https://user-images.githubusercontent.com/25194203/40300838-fbabe230-5d1c-11e8-97a3-d8e1f679c18e.png)

**Comment by sandm1227** [comment]
开始代理写在roadhogrc.mock.js里面，请求时后端会得不到数据
![default](https://user-images.githubusercontent.com/25194203/40640876-6ac6f604-634a-11e8-9245-ba1d9463e272.png)
直接在.webpackrc里面做代理就可以了：
![default](https://user-images.githubusercontent.com/25194203/40640951-a16866f2-634a-11e8-9258-98defc5197ca.png)
