### ISSUE TITLE
Use umi instead of roadhog

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#1512]
Roadhog is out of date
Umi is the future.

- [x] 路由
- [x] 样式
- [x] dva model
- [x] 主题切换
- [x] eslint 切换到 eslint-config-umi
- [x] mock 数据
- [x] 静态资源
- [x] 单元测试使用 umi test
- [x] 动态加载
- [x] 文档
- [x] 国际化相关
- [x] 权限，权限路由
- [x] 404 页面
- [x] title
- [x] menu
- [x] 个人页
- [x] 设置页
- [x] 登录注册页
- [x] 布局样式错误，页面过窄时下方留白
- [x] 初始化页面（路由 / 对应的页面）
- [x] 冲突 fix
- [x] mock 改为约定式（去掉 umirc.mock.js）
- [x] 删除注释的老代码
- [x] e2e test
- [x] build
- [x] /trigger
- [x] 优化 common/menu 和 common/router 代码
- [x] 分布表单

https://github.com/umijs/umi/
预览地址  http://beta.preview.pro.ant.design/dashboard/analysis

**Comment by tianlinzx** [comment]
cool.

**Comment by kaoding** [comment]
支持换上Umi

**Comment by szwork2013** [comment]
@chenshuai2144 Umi 不适合复杂路由，建议作出说明或分不同版本。

**Comment by IceBay** [comment]
@szwork2013 怎样的路由算复杂？

**Comment by szwork2013** [comment]
@IceBay 跟打包后部署服务器，服务器带有变量的路由等这些问题有关。当然严格来说跟umi无关，只是说她没有能够解决这方面的场景而已。
https://umijs.org/docs/zh-Hans/deploy.html

**Comment by DuduStyle** [comment]
cool

**Comment by WuJiY** [comment]
cool

**Comment by xiaoxiangmoe** [comment]
@chenshuai2144 umi 的改动比较大，有改动的规划吗？`help wanted`> 是我们可以做一些pull request的意思咩？需要注意什么咩？

**Comment by chenshuai2144** [comment]
先提上来我们评审就好了

**Comment by 533001** [comment]
666

**Comment by afc163** [comment]
https://github.com/umijs/umi/tree/master/packages/umi-plugin-datahub

**Comment by 533001** [comment]
持续关注中

**Comment by sunny920406** [comment]
我自己的webpack4用来替换roadhog的配置，https://github.com/sunny920406/roadhogWebpack4

**Comment by tolerance-go** [comment]
感觉是个体力活呢

**Comment by xiaohuoni** [comment]
不知道你们说的怎样的路由，用umi无法实现？

**Comment by focus0802** [comment]
有没有个准信儿啊，现在用antd-pro开发的话，切换到umijs了会不会是个迁移大工程

**Comment by xiaohuoni** [comment]
旧的pro项目迁移到新的umi应该是一个比较容易的过程。可以参考这个项目的commit 。https://github.com/umijs/umi-antd-admin。基本上组件部分都不需要修改。基本处理路由配置那一部分的内容还有webpack的配置就可以了

**Comment by chenshuai2144** [comment]
@yutingzhao1991  过来看看，可以和 @xiaohuoni 合作搞一搞

**Comment by yutingzhao1991** [comment]
可以，直接开撸吧！ @chenshuai2144  往 v2 这个分支提 PR？

@xiaohuoni 要来一起做这个迁移吗？

**Comment by chenshuai2144** [comment]
对的

**Comment by xiaohuoni** [comment]
可以的。不过我这几天回老家。电脑没带。大概三天时间（捂脸）

**Comment by xiaohuoni** [comment]
@yutingzhao1991 你可以加下我微信 yu_xiaohu

**Comment by xiaoxiangmoe** [comment]
@yutingzhao1991 有加 TypeScript 支持的想法吗？

**Comment by tulies** [comment]
再集成个富文本编辑器吧， markdown的最好。

**Comment by unrealsmart** [comment]
难得一见的更新233
