### ISSUE TITLE
antd Upload组件request和pro的request组件统一

### ISSUE THREAD

**Issue by callmez** [ant-design/ant-design-pro#1514]
antd的Upload组件是自成一个request. 
pro已经统一了request调用. Upload已经提供了customRequest接口, 能否把upload的request统一进来. 
好处是 便于管理, 监控. 统一接口.
  
谢谢提供Pro这么好的快速进入中后台项目开发. 如果在这些细节上能尽量减少一些开发相信能让用户更专注于业务逻辑.

**Comment by chenshuai2144** [comment]
Upload 应该使用FormData ，而request使用的是 json，
两者其实不兼容

**Comment by callmez** [comment]
统一入口, 流程监控. 错误处理.

**Comment by chenshuai2144** [comment]
fetch 现在有很多缺点，还替代不了 ajax，比如 还不支持进度条 你可以随时留意最新的进展，
