### ISSUE TITLE
Npm vulnerability, https://nodesecurity.io/advisories/577 

### ISSUE THREAD

**Issue by spideeee** [ant-design/ant-design-pro#1519]
https://nodesecurity.io/advisories/577

Versions of lodash before 4.17.5 are vulnerable to prototype pollution.

The vulnerable functions are 'defaultsDeep', 'merge', and 'mergeWith' which allow a malicious user to modify the prototype of Object via __proto__ causing the addition or modification of an existing property that will exist on all objects.

Remediation
Update to version 4.17.5 or later.

**Comment by chenshuai2144** [comment]
thanks
