### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design-pro#152]
在切换页面的时候有卡顿现象，其中从一个页面切换到`监控页`的时候尤其明显。

[Profile-20171110T010031.zip](https://github.com/ant-design/ant-design-pro/files/1458485/Profile-20171110T010031.zip)

**Comment by afc163** [comment]
监控页用了比较多的重型图表，性能主要损耗在图表的渲染上了，期待后面 G2 的升级能够优化一些。https://github.com/ant-design/ant-design-pro/issues/19

如果有 React 方面的性能损耗，欢迎 PR ~

**Comment by sunfutao** [comment]
如何压缩打包后umi.js和vendors.async.js体积,打包前应注意什么
