### ISSUE TITLE
路由出现/?并且异常刷新的问题？有人遇到过么？

### ISSUE THREAD

**Issue by ceser-x** [ant-design/ant-design-pro#1522]
在登录和浏览是分别匹配的是/user和/两个路由，应该是browserHistory，然后匹配到/#/step-form这种hashHistory时候，点击提交按钮。莫名跳转到/?#/step-form的页面。不知道是怎么个情况，有人遇到过吗？

**Comment by afc163** [comment]
form onSubmit 时需要用 `e.preventDefault()` 禁用浏览器默认行为。
