### ISSUE TITLE
roadhog-api-doc build Failed to minify the bundle. Error: api.js from UglifyJs

### ISSUE THREAD

**Issue by taoqianbao** [ant-design/ant-design-pro#1523]
hi, when i run command "roadhog-api-doc build", 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle roadhog-api-doc-boilerplate@~prebuild: roadhog-api-doc-boilerplate@
6 info lifecycle roadhog-api-doc-boilerplate@~build: roadhog-api-doc-boilerplate@
7 verbose lifecycle roadhog-api-doc-boilerplate@~build: unsafe-perm in lifecycle true
8 verbose lifecycle roadhog-api-doc-boilerplate@~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/peter/works/github/ant-design/ant-design-pro/_roadhog-api-doc/node_modules/.bin:/usr/local/mysql/bin/:/usr/local/Cellar/gradle/4.4.1/bin:/Users/peter/Applications/phantomjs-2.1.1/bin:/Users/peter/.rvm/gems/ruby-2.3.0/bin:/Users/peter/.rvm/gems/ruby-2.3.0@global/bin:/Users/peter/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbin:/bin:/Users/peter/.nvm/versions/node/v7.10.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/maven/bin:/usr/local/mysql/bin/:/usr/local/Cellar/gradle/4.4.1/bin:/Users/peter/Applications/phantomjs-2.1.1/bin:/Users/peter/.rvm/gems/ruby-2.3.0/bin:/Users/peter/.rvm/gems/ruby-2.3.0@global/bin:/Users/peter/.rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/Users/peter/.rvm/bin:/Users/peter/.rvm/bin
9 verbose lifecycle roadhog-api-doc-boilerplate@~build: CWD: /Users/peter/works/github/ant-design/ant-design-pro/_roadhog-api-doc
10 silly lifecycle roadhog-api-doc-boilerplate@~build: Args: [ '-c', 'roadhog build' ]
11 silly lifecycle roadhog-api-doc-boilerplate@~build: Returned: code: 1  signal: null
12 info lifecycle roadhog-api-doc-boilerplate@~build: Failed to exec build script
13 verbose stack Error: roadhog-api-doc-boilerplate@ build: `roadhog build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid roadhog-api-doc-boilerplate@
15 verbose cwd /Users/peter/works/github/ant-design/ant-design-pro/_roadhog-api-doc
16 verbose Darwin 16.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error roadhog-api-doc-boilerplate@ build: `roadhog build`
22 error Exit status 1
23 error Failed at the roadhog-api-doc-boilerplate@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
升级最新的 roadhog-api-doc
