### ISSUE TITLE
希望DescriptionList组件内部能支持动态渲染

### ISSUE THREAD

**Issue by YanYuanFE** [ant-design/ant-design-pro#1525]
![image](https://user-images.githubusercontent.com/17774285/40348527-89884d46-5dd6-11e8-9957-398881cd63e1.png)
当值为false的时候，会返回null，导致DescriptionList组件内部使用React.cloneElement(child, { column })渲染出错，因为null不是一个React元素。
如下：

![_301](https://user-images.githubusercontent.com/17774285/40348880-7ea2e764-5dd7-11e8-8ec3-977ae0ad952a.png)

**Comment by chenshuai2144** [comment]
欢迎 pr 一个。我们暂时没有精力

**Comment by YanYuanFE** [comment]
https://github.com/ant-design/ant-design-pro/pull/1428，已解决
