### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by gucciwu** [ant-design/ant-design-pro#1526]
![image](https://user-images.githubusercontent.com/6937570/40349317-e2412c1c-5dd8-11e8-9826-e75ac0105238.png)
colorWeak=colse => colorWeak=close?

**Comment by chenshuai2144** [comment]
fixed https://github.com/ant-design/ant-design-pro/commit/84315b3ab90ed0e49d84388f71bfdba03373a543
