### ISSUE TITLE
2.0.0-beta.1版本使用antd tree官网例子出错。

### ISSUE THREAD

**Issue by diangong** [ant-design/ant-design-pro#1527]
![20180522231816](https://user-images.githubusercontent.com/28615031/40372259-e2c194f4-5e16-11e8-93e7-1fecf8916648.png)
1.Warning: '0-0-0' does not exist in the tree.  
2.无法点选复选框

**Comment by chenshuai2144** [comment]
这个应该和pro没有关系

**Comment by diangong** [comment]
pro1.3.0版本试过没有这个问题，2.0.0-beta.1出现这个情况

**Comment by afc163** [comment]
提问要给出重现。

**Comment by chenshuai2144** [comment]
无法再现
