### ISSUE TITLE
为什么我yarn start:no-proxy 会build到91进度就没反应了？

### ISSUE THREAD

**Issue by blockmood** [ant-design/ant-design-pro#1529]
![48b30ed87f400b72823ac943b92d7e02](https://user-images.githubusercontent.com/22879524/40400462-cfa09ba0-5e74-11e8-88fc-d95170696e8c.jpg)

**Comment by xiaoquanWu** [comment]
我也是， 不知道为什么

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1520

**Comment by wangzf-no1** [comment]
I reappear, but I don't know why, my colleague's code is in my case.

**Comment by kingofhawks** [comment]
me too.

**Comment by wangzf-no1** [comment]
I seem to know the reason for my code, syntax errors, or import package exceptions

**Comment by kingofhawks** [comment]
After upgrade roadhg to 2.3, it resolved my issue.

**Comment by blockmood** [comment]
@wangzf-no1  You can try to try to have a look at your rely on package
