### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Liberxue** [ant-design/ant-design-pro#1530]
websocket 没有渲染的速度快。。。。 老提示 ``“SyntaxError: Unexpected end of JSON input
” ``
不会是让我延时websocket吧/::-| 
除了延时有没有更好的方法啊
![image](https://user-images.githubusercontent.com/5831248/40407838-45578c8c-5e98-11e8-8899-0c1e4465747c.png)

```
Error: connect ECONNREFUSED 127.0.0.1:8013
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```
![image](https://user-images.githubusercontent.com/5831248/40407980-aacb7ac4-5e98-11e8-98bc-931a7fb92353.png)

一般情况不会报错 shift+command+r 就重现了

**Comment by chenshuai2144** [comment]
<img width="203" alt="default" src="https://user-images.githubusercontent.com/8186664/40409926-f1518064-5e9e-11e8-93d6-cb0a8efe8d47.png">

问题在这里！ 你判断一下这个地方。
而且 一般不要用JSON.parse。 理一下你的业务吧
