### ISSUE TITLE
v2版本菜单错误

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#1532]
当前状态在除了第一个之外的其他菜单。
图一
![image](https://user-images.githubusercontent.com/183884/40431626-60e3ced8-5eda-11e8-92b4-3c6921f60585.png)

点击设置
图一高亮应该在第一个菜单上而现在的高亮依然在之前的状态，按道理讲应该是基本设置高亮
![image](https://user-images.githubusercontent.com/183884/40431691-858e18a6-5eda-11e8-9039-1955e2f405bb.png)

**Comment by afc163** [comment]
帮忙修复一下？
