### ISSUE TITLE
为何最近的版本，都不能npm install 了

### ISSUE THREAD

**Issue by jiankian** [ant-design/ant-design-pro#1534]
直接克隆的最新版，或者下载release最新版，都不能安装依赖？

**Comment by chenshuai2144** [comment]
有报错吗？

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。
