### ISSUE TITLE
Ant Design Pro 项目，最后编译出来有将近13M，请问这是正常的么？还可以怎么优化？

### ISSUE THREAD

**Issue by Moonlightwsn** [ant-design/ant-design-pro#1536]
.webpackrc.js里有配置
extraBabelPlugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
和
disableDynamicImport: false，
build出来一共43个文件，12.7M
虽然服务端开启了gzip压缩但是感觉似乎还是项目的体积太大了？
这是正常的么

**Comment by afc163** [comment]
是合理的，去掉 disableDynamicImport 以后，有些文件会重复打包的。而且有了动态加载，进入页面只会加载一部分。

**Comment by Moonlightwsn** [comment]
@afc163 那重复打包的第三方库可以提取出来么？roadhog我看有commons配置项，但没搞太明白要怎么配。或者说对一般项目而言没有必要这么做？

**Comment by Moonlightwsn** [comment]
@chenshuai2144 确实小很多。本来以为开了代码分割会比较好，这样每进一个页面才会去加载对应的文件。但是现在看起来，好像没有必要这样

**Comment by chenshuai2144** [comment]
其实每次页面的加载还是小了，除非每个点一下不然总比全量笑

**Comment by afc163** [comment]
@Moonlightwsn https://github.com/sorrycc/roadhog#commons
