### ISSUE TITLE
npm start出现错误

### ISSUE THREAD

**Issue by lianghaoSZ** [ant-design/ant-design-pro#1537]
Failed to compile.

Cannot read property '0' of undefined

**Comment by chenshuai2144** [comment]
如何复现？

**Comment by MinHongwei** [comment]
我也是碰到了这个问题

**Comment by MinHongwei** [comment]
新下载的项目

**Comment by MinHongwei** [comment]
之前是可以的  我的nonde  是8.5的版本 自带的npm 我有安装cnpm

**Comment by MinHongwei** [comment]
[cnpm i 的时候.txt](https://github.com/ant-design/ant-design-pro/files/2042345/cnpm.i.txt)

**Comment by chenshuai2144** [comment]
@MinHongwei 你这里面全是网络错误呀

**Comment by roovit008** [comment]
我也是这错误 删了依赖重新cnpm install  还是一样  同win10系统
[2018-5-29.txt](https://github.com/ant-design/ant-design-pro/files/2047368/2018-5-29.txt)

**Comment by uni-zheng** [comment]
@ceser-x 有隐藏配置文件

**Comment by chenshuai2144** [comment]
看一下别名配置

**Comment by SeptemberMaples** [comment]
所以，大家是如何解决的这个问题？
