### ISSUE TITLE
关于@Form.create() 怎么在一个组件里面多个不同form

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design-pro#154]
官方框架上，TableList 上用@Form.create() 可以把两个搜索框的表格关联在一起，现在我想在Modal上获取表格进行校验该怎么解决？

**Comment by beeant0512** [comment]
个人感觉这个是个BUG，在Modal中的form设定校验规则（不为空）后，在查询的form中规则被同样生效了。

代码如下：

`<Card bordered={false}>`
    ` <div className={styles.tableList}>`
            `<div className={styles.tableListForm}>`
             ` {this.renderForm()}`
            `</div>`
        `  </div>`
       ` </Card>`
        `<Modal`
          `visible={modalVisible}`
        `  onOk={this.handleAdd}`
         ` onCancel={() => this.handleModalVisible()}`
        `>`
          `{this.handleModalForm()}`
        `</Modal>`

handleModalForm片段如下
`<FormItem>`
`{getFieldDecorator('providerShortname', {`
`rules: [{ required: true, message: '简称不能为空!' }],`
`})(<Input placeholder="请输入供卡商简称" />)}`
`</FormItem>`

renderForm片段如下：
`<FormItem label="简称">`
`{getFieldDecorator('providerShortname')(`
`<Input placeholder="请输入" />`
`)}`
`</FormItem>`

**Comment by afc163** [comment]
http://segmentfault.com/markdown

**Comment by afc163** [comment]
不要使用重复的 field name

**Comment by beeant0512** [comment]
你这只是解决了冲突问题 本质上的bug却还在，不可能所有这种场景都换field name吧

**Comment by stduolc** [comment]
+1 同需求。需要在一个route页面里面。使用多个form。
