### ISSUE TITLE
dispatch 怎么获取返回信息

### ISSUE THREAD

**Issue by baifeifei** [ant-design/ant-design-pro#1540]
this.props.dispatch({
      type: 'register/sendCode',
      payload: this.props.form.getFieldValue('phone'),
    }).then((res)=>{
      console.log(res);
    })

   *sendCode({payload}, { call, put }) {
      return res = yield call(sendCode,payload);
    },

需要根据返回信息来进行下一步操作，但是获取的返回一直是undefined

**Comment by xujycode** [comment]
dispatch返回的不是promise对象，根据返回信息来进行下一步操作的代码应该写在model的effects中

**Comment by JoeyKo** [comment]
You should modify state in reducers, then use `this.props.xxx` to get the value.

**Comment by chenshuai2144** [comment]
楼上正解

**Comment by colinzhy** [comment]
貌似跟这个问题有点类似，楼主可以参考一下：https://github.com/dvajs/dva/issues/1671
