### ISSUE TITLE
请问 词云TagCloud 的 ToolTip 怎么才能显示？

### ISSUE THREAD

**Issue by x1nGoo** [ant-design/ant-design-pro#1541]
词云TagCloud 图标设置了toolTip怎么不显示？
bizchart的官网的toolTip是显示的，但ant-design-pro demo里面的不显示，
bizchart里词云显示的值是怎么算出来的，也不是源数据的value值

**Comment by nikogu** [comment]
看下代码呢，最好有个 codePen
