### ISSUE TITLE
update list according to the operate

### ISSUE THREAD

**Issue by ilaipi** [ant-design/ant-design-pro#1544]
what is the best way to update a list?

e.g. list on a page, when click `disable` button on a row, the status of this row should be set to `disabled`. So how to update the list?

use :
[immutability-helper](https://github.com/kolodny/immutability-helper)

[immer](https://github.com/mweststrate/immer)

??

thanks.

**Comment by chenshuai2144** [comment]
If the amount of data is relatively small, no need to use plug-in
