### ISSUE TITLE
Error Installing async-validator

### ISSUE THREAD

**Issue by sebasalvarado** [ant-design/ant-design-pro#1545]
**System and Versions:**
- OS: Mac OSX High Sierra
```
node -v
v8.11.1
```

```
npm -v
5.6.0
```

**Problem:**

After cloning the project and trying `npm install` I got the following error: 

```
npm ERR! fetch failed https://registry.npmjs.org/async-validator/-/async-validator-1.8.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404`
```
After researching this problem online I found this way to fix it: https://stackoverflow.com/questions/50540965/npm-err-404-not-found-async-validator-while-installing-element-ui/50541278 

I had to ```npm install https://github.com/yiminghe/async-validator/archive/1.8.2.tar.gz``` and that added it as a dependency to my package.json. Afer doing that step, I was able to succesfully run `npm install`.  I'm not sure which package depends on `async-validator` but that is not allowing me run the project. After I installed it separately I tried `npm start` and this is what I'm getting now:

```
Failed to compile.

./node_modules/async-validator/index.js
Module parse failed: Unexpected token (1:20)
You may need an appropriate loader to handle this file type.
| export default from './src/';|
```

I think is a webpack or babel issue that I'm not sure how to fix. Can we fix the link for `async-validator` so that my `npm install` works?

**Comment by afc163** [comment]
Fixed in https://github.com/npm/registry/issues/329#issuecomment-392231959 now.
