### ISSUE TITLE
如何使得src/theme.less 修改的时候roadhog能自动刷新less变量？

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design-pro#1546]
我想修改主题色，通过覆盖less变量，但是比较头疼每一次修改roadhog都不会自动刷新，只有当我重新编译的时候才可以。    这样对开发者太不友好了，效率也难以提升，是否是我设置方面的问题呢？请赐教，谢谢！

**Comment by chenshuai2144** [comment]
你是需要在线修改主题功能吗？

**Comment by LaiHuanMin** [comment]
@chenshuai2144 不好意思前几天太忙。 我不用在线的动态修改主题功能，我是需要将ant-design-pro的布局以及色调等等重新进行配置成另外一个风格。 其实我可以直接用less写css代码进行覆盖指定类的颜色， 但是覆盖less变量会更加快捷有效。   
现在问题就是roadhog，在修改less变量之后（theme.less）不会进行重新编译，除非你kill掉再运行一遍，如果能监听到我修改less变量修改并编译页面呈现就好了！
