### ISSUE TITLE
input 组件的addonBefore元素样式变形

### ISSUE THREAD

**Issue by Christydeng** [ant-design/ant-design-pro#1547]
<Col {...colLayout.input}>
            <FormItem>
              <InputGroup compact>
                {getFieldDecorator('keyword', {
                  initialValue: ''
                  })(
                    <Input style={{ top: 0 }}  addonBefore={selector} placeholder="请输入查询条件" />
                )}
              </InputGroup>
            </FormItem>
          </Col>

**Comment by afc163** [comment]
You should create issue to http://github.com/ant-design/ant-design
