### ISSUE TITLE
npm run build CSS 失效

### ISSUE THREAD

**Issue by moker-monkey** [ant-design/ant-design-pro#1548]
clone了ant-design-pro 项目后，build之后放置到自己的服务器的静态文件夹下之后，访问index.html，发现只有js没有css样式，查看Chrome控制台的source，发现css已经加载，但是并没有渲染，然后在source中的css中随便添加一个分号，就能够正常显示，但在打包后的css中添加符号，并没有效果。

**Comment by chenshuai2144** [comment]
build 出来的物料？

**Comment by moker-monkey** [comment]
物料？我用的npm run build 命令build出来的dist文件夹下的文件

**Comment by chenshuai2144** [comment]
对 里面有什么

**Comment by moker-monkey** [comment]
![image](https://user-images.githubusercontent.com/23519198/40604491-c7b75926-6291-11e8-912c-dfd41dcf8530.png)

**Comment by chenshuai2144** [comment]
这应该是没有问题的  你丢了什么东西的样式？

**Comment by moker-monkey** [comment]
是整个样式都没有呢，难道是因为后台连接报错导致的吗？
![image](https://user-images.githubusercontent.com/23519198/40605550-4e1be57e-6295-11e8-8be5-7effbe613aff.png)

**Comment by moker-monkey** [comment]
才留意到，有一个警报，应该是后端发送数据类型不对导致的
![image](https://user-images.githubusercontent.com/23519198/40605904-53334a9c-6296-11e8-92c7-4bae522858cc.png)
