### ISSUE TITLE
强烈建议建议

### ISSUE THREAD

**Issue by apchenjun** [ant-design/ant-design-pro#155]
第一。建议小屏幕下有个固定导航条在顶部，左边菜单完全隐藏通过顶部导航条的菜单按钮显示菜单，这个也是目前主流网站模板的标配。
第二，目前页面样式模板太少，多一些企业级和商务级的模板样例。
第三，登陆注册样式多一点。

**Comment by afc163** [comment]
1. #141
2/3、略伸手党了，不过还是欢迎持续关注。

**Comment by gebilaoman** [comment]
@apchenjun 欢迎把项目交给我们来做，这样都不用敲代码
