### ISSUE TITLE
请教一下，假设一级菜单中含有二级菜单，当点击一级菜单时如何刷新右侧页面

### ISSUE THREAD

**Issue by hy9125** [ant-design/ant-design-pro#1550]
![image](https://user-images.githubusercontent.com/15630871/40606886-605d1718-6299-11e8-85b0-95e6752fabbb.png)

当我点选列表时，我想展示所有用户的信息，当点用户A时，我展示用户信息

现在点 列表 ，只是展开，没有页面跳转的动作

**Comment by uni-zheng** [comment]
在 BasicLayout.js 中修改 getRedirect 函数的内部逻辑 增加对一级菜单的路由重定向

**Comment by hy9125** [comment]
@uni-zheng 
感谢，我去试试

**Comment by uni-zheng** [comment]
@hy9125  sorry 我今天也是刚下了框架在学，我刚又看了一下 直接输入一级路由能跳转到二级，证明重定向函数已经生效了，应该是一级菜单的 click 事件没有绑定上去。

**Comment by hy9125** [comment]
@uni-zheng 那这个应该怎么绑定呢？

**Comment by uni-zheng** [comment]
@hy9125 SiderMenu.js 中 Menu 组件，对应 ant design 看一下文档，有 onClick 属性

**Comment by hy9125** [comment]
@uni-zheng 能否给个实例（有点伸手党了。。），感谢

**Comment by chenshuai2144** [comment]
最好不用这种功能，菜单就是用来导航的，你可以用用户列表来完成这个功能

**Comment by hy9125** [comment]
@chenshuai2144 Hi,感谢回复，主要这个是领导要求的。如果做的话有什么好办法吗？

**Comment by chenshuai2144** [comment]
~~反驳你的领导告诉他这是不对的！~~
就想楼上说的你可以监听 click 事件。但是这样你需要自己维护菜单了，不能用我们的框架了

**Comment by hy9125** [comment]
@chenshuai2144 好的，感谢
