### ISSUE TITLE
是否支持 webpack 配置多入口：entry: {...} 或...

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design-pro#1552]
请问：

要同时开发两个样式功能相似但是业务逻辑不同的小项目，部署在两个地方，同时开启两套 antd-pro 但是维护一套公共代码显得代价很高。

有没有方法可以支持 webpack 配置多入口？或者通过别的方法实现需求？

**Comment by chenshuai2144** [comment]
去 roadhog 看看。我们最近会迁移 umi
