### ISSUE TITLE
从两个月前的版本升级到当前版本，编译进度停留到91后卡死

### ISSUE THREAD

**Issue by lvyuanying** [ant-design/ant-design-pro#1556]
从旧版迁移到当前版本，跑start后，进度停留到91就卡住了，等了很久提示处理内存不足什么的。打包到生产环境却没有问题，百思不得其解。旧版本跑得是很正常的，可是现在回不去了。

**Comment by lvyuanying** [comment]
build [========= ] 91%    怀疑是语法报错，卡住了线程

**Comment by chenshuai2144** [comment]
#1520
