### ISSUE TITLE
Ellipsis组件文本为汉字时，设置length时有bug

### ISSUE THREAD

**Issue by DuduStyle** [ant-design/ant-design-pro#1557]
假设此时article为“曲盈盈”
如果人名超过2个字，即显示为（曲...），代码如下
`<Ellipsis length={2}>{article}</Ellipsis>`
显示的实际效果为"..."

### 重现地址：
[https://codesandbox.io/s/p2wj89wr0](url)

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/Ellipsis/index.js#L19

应该是 length 把 ... 算上了，这个后面要改下，所以现在得每个加 3 个字符，比如 2 + 3 =5...
