### ISSUE TITLE
菜单设置bug

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design-pro#156]
BasicLayout.js [#L50](https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L50) 这一行，
```javascript
this.menus = getNavData().reduce((arr, current) => arr.concat(current.children), []);
```
reduce 里面是返回 current.children , 是不是就意味着每个主菜单必须有子菜单？
感觉这个不怎么合理，最好是下面这种方式
```javascript
this.menus = getNavData().reduce((arr, current) => arr.concat(current.children || []), []);
```

**Comment by zjxpcyc** [comment]
还有就是请教下，如果我有一个路由，但是不是必须在菜单内, 也就是比如是 list 跳转过去的详情页，不是放在菜单里面的，这种路由，在哪里加？ 是不是也在  nav.js 里面，然后 name 等属性随便设置个假的?

**Comment by gebilaoman** [comment]
你说的是路由参数问题。
Duplicate of #104

**Comment by ddcat1115** [comment]
@zjxpcyc  这里只是要求每级 Layout 下有children，并不是每个菜单下有子菜单，你可以在 nav.js 里改下试试。

所有要加入路由的信息都应该在 nav.js 里配置，目前默认逻辑是 nav 里配置了的都会放在菜单里，你可以自己修改下 BasicLayout.js 生成菜单的相关逻辑，配合 nav.js 里打标来实现

**Comment by zjxpcyc** [comment]
@ddcat1115 我按照我上面的方法修改了。

> 这里只是要求每级 Layout 下有children

是我理解错了, 我以为第一层级就是主菜单呢。
