### ISSUE TITLE
Android 浏览器打开白屏问题

### ISSUE THREAD

**Issue by xiaocjin** [ant-design/ant-design-pro#1560]
Android 浏览器打开白屏（魅蓝note6 android 7.1.2 & 华为waterplay平板 android 7），但是用react-native webview封装的app打开却可以访问（android 原生封装的app也可以）。
测试使用的是ant-design-pro-cli生成的新项目

**Comment by chenshuai2144** [comment]
chrome 呢？  国产厂商自带的浏览器都魔改过了

**Comment by xiaocjin** [comment]
@chenshuai2144 chrome可以的

**Comment by jingkeke** [comment]
感觉@chenshuai 把所有的Android 浏览器白屏问题都给关闭了,说支持现代手机................我的华为Android8 也不支持....华为的手机用户量还挺大的吧............

**Comment by xiaohuoni** [comment]
@jingkeke 不是所有安卓浏览器问题都给关闭了，是特殊的浏览器兼容，可以尝试使用配置
https://umijs.org/zh/config/#targets 一般这些魔改过的浏览器，直接设置ie9，可以处理，如果不行可以尝试一下，chrome 49.

**Comment by jingkeke** [comment]
> @jingkeke 不是所有安卓浏览器问题都给关闭了，是特殊的浏览器兼容，可以尝试使用配置
> https://umijs.org/zh/config/#targets 一般这些魔改过的浏览器，直接设置ie9，可以处理，如果不行可以尝试一下，chrome 49.

嗯,谢谢. 当时是查的华为的android8自带的浏览器内核版本还是chrome40多...理解你们说的魔改是啥意思了....当时是改成`  targets: {ie: 9,android: 4,  },`   然后好了.
