### ISSUE TITLE
@connect model 引入了 但是loading中没有这个model

### ISSUE THREAD

**Issue by SDgaoqiang** [ant-design/ant-design-pro#1562]

**Comment by ybning** [comment]
请研习，redux的connect

https://redux.js.org

**Comment by neevany** [comment]
loading model is not defined in the starter.

The article doesn't explain how the `loading.models.user` is working, 

Can you explain it or point me to an explanation @ybning 
Did you figure out how it works @SDgaoqiang

**Comment by zieen** [comment]
最后你整明白了么？ loading.models.user 哪来的？

**Comment by chenshuai2144** [comment]
@zieen  dva-loading 这个插件给的

**Comment by zieen** [comment]
@chenshuai2144 谢啦
