### ISSUE TITLE
mock接口地址为什么一直没有数据返回

### ISSUE THREAD

**Issue by zongwong** [ant-design/ant-design-pro#1565]
export default {
  'GET /api/getAdList': 'http://localhost/index.php/Sns/Info/infolist'
};
http://localhost/index.php/Sns/Info/infolist 本地接口，直接打开就有数据了，但是代理了就不行。为什么？

**Comment by yoyo837** [comment]
使用proxy吧，我现在是mock和proxy各配了个npm script
