### ISSUE TITLE
WaterWave 组件：数据和reducer或state 动态绑定， 在fetch后图形没法重新渲染

### ISSUE THREAD

**Issue by AndyZhangChuan** [ant-design/ant-design-pro#1568]
我看了WaterWave这个组件的源代码，并进行的了调试，如下

```
componentDidMount() {
    this.renderChart();
    this.resize();
    window.addEventListener('resize', this.resize);
  }
```

结果发现： 使用Canvas绘制Chart（renderChart方法）是在componentDidMount这个节点执行， 实际上这个节点在首次render执行后会调用一次， 但是后续有prop更新， render方法会重新执行， 但是componentDidMount则不会在重新执行。 表现结果是：组件没法根据后端异步fetch到的数据绘制Canvas图形

PS： 是不是我的使用方式有问题

**Comment by nikogu** [comment]
@AndyZhangChuan 确实，其实应该是需要的，后面改下，你可以先用强制刷新让他每次更新都渲染：

```
render() {
  const WaterWaveGen = () => <WaterWave />;
  return ... <WaterWaveGen /> ...;
}
```

**Comment by AndyZhangChuan** [comment]
好的， 了解了
