### ISSUE TITLE
WaterWave组件导致CPU占用非常高

### ISSUE THREAD

**Issue by zhangfu-git** [ant-design/ant-design-pro#1569]
在Mac上用chrome打开页面，发现CPU占用一直在100%以上
```
<WaterWave
   height={600}
   title='xxx'
   percent={50}
/>
```

**Comment by chenshuai2144** [comment]
详细原因？正常使用是不会的

**Comment by zhangfu-git** [comment]
我就引入WaterWava组件，希望绘制一个600高度waterWave，但CPU占用100%以上。通过改变height发现，height的值越大cpu占用就越高。

**Comment by liuhua-1991** [comment]
I fixed the high cpu question with disable the 'html css support' plugin and 'css peek' plugin
