### ISSUE TITLE
dev下接口mock和服务器proxy配置共存

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design-pro#1577]
针对一个接口，是否能支持如果配置有mock则使用mock数据，如果没配置mock则通过proxy配置调用开发服务器数据（已配置proxy）？

**Comment by chenshuai2144** [comment]
默认就是这样的吧
`    "start": "cross-env ESLINT=none roadhog dev",`

**Comment by yoyo837** [comment]
并不是，如果.webpackrc.js配置了proxy，则mock配置会被忽略，始终走代理调用

**Comment by F-loat** [comment]
不使用 `webpack` 的 `proxy`，而是在 `.roadhogrc.mock.js` 文件的最后添加转发规则即可
``` js
'POST /api/(.*)': 'http://localhost:7001/api',
```

**Comment by yoyo837** [comment]
@F-loat 
`'/api/(.*)': 'http://localhost:7001/api',`

试了一下可以，但无法省略POST来同时支持POST, 需要单独配置一条
`'/api/(.*)': 'http://localhost:7001/api',`
`POST '/api/(.*)': 'http://localhost:7001/api',`

**Comment by jackxiaodev** [comment]
@chenshuai2144 
在proxy设置里面有没有办法增加一个额外的参数，例如accessToken来做server to server的验证，例如请求 http://localhost:8000/api/users 将会反向代理到 http://api.com/api/users?accessToken=xxxxx. 在用户的角度，不会看到accessToken

**Comment by jackxiaodev** [comment]
@F-loat 
proxy设置可以加header?麻烦告知如何备置，在.webpackrc.js的proxy设置如下
proxy:{
         "/api":{
             target: 'http://api.com/api',
             changeOrigin:true,
             pathRewrite:{"^/api/":""},
         }
    }

**Comment by chenshuai2144** [comment]
直接在请求的时候加head不行吗，

**Comment by mushroomlb** [comment]
@yoyo837  这个方法是正确的，需要根据post和get单独设置

**Comment by yoyo837** [comment]
@mushroomlb OK, 如果没有更推荐的做法，那分别按方法设置代理就是最佳实践了。

**Comment by F-loat** [comment]
不写方法名理论上是对所有方法都生效？ [roadhog#mock](https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#mock)
