### ISSUE TITLE
precommit 不管用了？

### ISSUE THREAD

**Issue by nvsky** [ant-design/ant-design-pro#1581]
![image](https://user-images.githubusercontent.com/8436965/40782518-2eccd0d2-6512-11e8-94f0-f7b2f771d8e3.png)
![image](https://user-images.githubusercontent.com/8436965/40782562-4b770db0-6512-11e8-8c83-6259d8b91b28.png)

**Comment by nvsky** [comment]
`{
  "name": "ss-rdap",
  "version": "2.0.0-beta.1",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "cross-env ESLINT=none roadhog dev",
    "start:no-proxy": "cross-env NO_PROXY=true ESLINT=none roadhog dev",
    "build": "cross-env ESLINT=none roadhog build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "cross-env ANALYZE=true roadhog build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "roadhog test",
    "test:component": "roadhog test ./src/components",
    "test:all": "node ./tests/run-tests.js",
    "prettier": "prettier --write ./src/**/**/**/*"
  },
  "dependencies": {
    "@antv/data-set": "^0.8.0",
    "@babel/polyfill": "^7.0.0-beta.36",
    "antd": "^3.4.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-runtime": "^6.9.2",
    "bizcharts": "^3.1.5",
    "bizcharts-plugin-slider": "^2.0.1",
    "classnames": "^2.2.5",
    "dva": "^2.2.3",
    "dva-loading": "^1.0.4",
    "dva-model-extend": "^0.1.2",
    "enquire-js": "^0.2.1",
    "eslint-plugin-jest": "^21.15.1",
    "less": "2.7.2",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.4.1",
    "moment": "^2.19.1",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.1.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "rc-drawer-menu": "^0.5.0",
    "react": "^16.2.0",
    "react-container-query": "^0.9.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.2.0",
    "react-fittext": "^1.0.0",
    "rollbar": "^2.3.4",
    "url-polyfill": "^1.0.10"
  },
  "devDependencies": {
    "babel-eslint": "^8.1.2",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-module-resolver": "^3.1.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.1.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.0.1",
    "faker": "^4.1.0",
    "gh-pages": "^1.0.0",
    "husky": "^0.14.3",
    "lint-staged": "^6.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "1.11.1",
    "pro-download": "^1.0.1",
    "redbox-react": "^1.5.0",
    "regenerator-runtime": "^0.11.1",
    "roadhog": "^2.3.0",
    "roadhog-api-doc": "^1.0.2",
    "stylelint": "^8.4.0",
    "stylelint-config-prettier": "^3.0.4",
    "stylelint-config-standard": "^18.0.0"
  },
  "optionalDependencies": {
    "puppeteer": "^1.1.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run eslint",
      "pre-add": "yarn lint"
    }
  },
  "lint-staged": {
    "**/*.{js,jsx,less}": [
      "prettier --write",
      "git add"
    ],
    "**/*.{js,jsx}": "lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}
`

**Comment by nvsky** [comment]
{
  "name": "ss-rdap",
  "version": "2.0.0-beta.1",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "cross-env ESLINT=none roadhog dev",
    "start:no-proxy": "cross-env NO_PROXY=true ESLINT=none roadhog dev",
    "build": "cross-env ESLINT=none roadhog build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "cross-env ANALYZE=true roadhog build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "roadhog test",
    "test:component": "roadhog test ./src/components",
    "test:all": "node ./tests/run-tests.js",
    "prettier": "prettier --write ./src/**/**/**/*"
  },
  "dependencies": {
    "@antv/data-set": "^0.8.0",
    "@babel/polyfill": "^7.0.0-beta.36",
    "antd": "^3.4.3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-runtime": "^6.9.2",
    "bizcharts": "^3.1.5",
    "bizcharts-plugin-slider": "^2.0.1",
    "classnames": "^2.2.5",
    "dva": "^2.2.3",
    "dva-loading": "^1.0.4",
    "dva-model-extend": "^0.1.2",
    "enquire-js": "^0.2.1",
    "eslint-plugin-jest": "^21.15.1",
    "less": "2.7.2",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.4.1",
    "moment": "^2.19.1",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.1.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "rc-drawer-menu": "^0.5.0",
    "react": "^16.2.0",
    "react-container-query": "^0.9.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.2.0",
    "react-fittext": "^1.0.0",
    "rollbar": "^2.3.4",
    "url-polyfill": "^1.0.10"
  },
  "devDependencies": {
    "babel-eslint": "^8.1.2",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-module-resolver": "^3.1.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.1.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.0.1",
    "faker": "^4.1.0",
    "gh-pages": "^1.0.0",
    "husky": "^0.14.3",
    "lint-staged": "^6.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "1.11.1",
    "pro-download": "^1.0.1",
    "redbox-react": "^1.5.0",
    "regenerator-runtime": "^0.11.1",
    "roadhog": "^2.3.0",
    "roadhog-api-doc": "^1.0.2",
    "stylelint": "^8.4.0",
    "stylelint-config-prettier": "^3.0.4",
    "stylelint-config-standard": "^18.0.0"
  },
  "optionalDependencies": {
    "puppeteer": "^1.1.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run eslint",
      "pre-add": "yarn lint"
    }
  },
  "lint-staged": {
    "**/*.{js,jsx,less}": [
      "prettier --write",
      "git add"
    ],
    "**/*.{js,jsx}": "lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}

**Comment by chenshuai2144** [comment]
这个难道不是已经通过了？

**Comment by nvsky** [comment]
@chenshuai2144 代码有错误格式的没报出来，全No staged files match，难道husky、lint-staged与我后装的eslint-plugin-prettier插件有冲突导致commit hook失效了？

**Comment by yoyo837** [comment]
@nvsky 
我改了这个
`"**/*.{js,jsx}": "yarn run lint-staged:js",`
or
`"**/*.{js,jsx}": "npm run lint-staged:js",`

**Comment by nvsky** [comment]
![image](https://user-images.githubusercontent.com/8436965/40819407-7fbfb02e-658d-11e8-9d94-8798d37b9ab9.png)
这是eslint-plugin-prettier插件配置

**Comment by yoyo837** [comment]
@nvsky 直接clone过来的库，此位置我按 https://github.com/ant-design/ant-design-pro/issues/1581#issuecomment-393746272 这样改了下，造一个错误，提交时就能够报错，其他的我没深究了

**Comment by nvsky** [comment]
直接克隆的husky确实生效，我这里用[eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)稍加改造了
![image](https://user-images.githubusercontent.com/8436965/40819822-b70e761c-658f-11e8-9822-53a4d4e1f40f.png)结果precommit失效了
![image](https://user-images.githubusercontent.com/8436965/40819859-e4005bb8-658f-11e8-9499-16b8ed2eaf3e.png)
不管有多少错误都这个熊样
