### ISSUE TITLE
Description中children存在判断有误

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design-pro#1582]
https://github.com/ant-design/ant-design-pro/blob/a144bbd06e08dd9379735ea185286ffa146ea4a2/src/components/DescriptionList/Description.js#L13

在这里如果`children`的值为数字0的话会被判断为false，从而导致没有包裹`<div class="detail></div>`进而样式出错。

感觉主动判断不等于`null`和`undefined`就行了？

**Comment by afc163** [comment]
PR is welcome~
