### ISSUE TITLE
Request Headers add Authorization return 401  

### ISSUE THREAD

**Issue by zerrol** [ant-design/ant-design-pro#1585]
在headers 中添加 Autorization，发送请求。

发送请求时会先弹出“请进行身份验证”。

![image](https://user-images.githubusercontent.com/9137993/40818297-13f4e5a2-6589-11e8-9b4f-319687af48ed.png)

点击取消后返回401错误

![image](https://user-images.githubusercontent.com/9137993/40818316-3398ccc0-6589-11e8-86ab-a809f5780089.png)

preview中返回信息为空

发送请求的代码

```
export async function fakeAccountLogin(token) {
  return request('/user', {
    method: 'GET',
    headers: {
      'Authorization': token,
    },
  });
}
```

**Comment by chenshuai2144** [comment]
这是业务方面的吧。和我们有关？

**Comment by zerrol** [comment]
不是业务，发请求的时候由于headers中加了 Authorization，结果浏览器会自动弹出“需要进行身份验证”。点击取消请求就被直接拦截掉了，也没有发送给后端。正常情况请求应该是直接发出去的，不应该验证的弹窗啊

**Comment by zerrol** [comment]
@chenshuai2144

**Comment by zerrol** [comment]
刚发现和Authorization没有关系，只要在GET请求中设置了headers，在发送请求的时候就会弹出“需要身份验证”的弹窗

**Comment by zerrol** [comment]
在账号密码正确的时候是好的，错误的时候会弹出这个验证框

**Comment by afc163** [comment]
和 antd-pro 无关。
