### ISSUE TITLE
models 下面的model能否用二级目录来管理

### ISSUE THREAD

**Issue by zmayor** [ant-design/ant-design-pro#1586]
项目比较大, 页面比较多, 单个`model`里面代码量很大, 拆分成多个`model`, `model`文件数又很多, 可以分目录管理`model`吗?

**Comment by nvsky** [comment]
![image](https://user-images.githubusercontent.com/8436965/40824112-7d29896c-65a5-11e8-984e-52b54e30dde2.png)
![image](https://user-images.githubusercontent.com/8436965/40824167-ba9a2fea-65a5-11e8-85b1-997d36c59e96.png)
我是这么实现的，你参考下

**Comment by nvsky** [comment]
@zmayor 按我方案实现可以closed此问题了

**Comment by zmayor** [comment]
3q, 确实可以的, 舒服了
