### ISSUE TITLE
预览页无法登录

### ISSUE THREAD

**Issue by gapsaras** [ant-design/ant-design-pro#1588]
https://preview.pro.ant.design/#/user/login

没有用户名和密码输入框，只有一个登录按钮，改版为默认登录了吗？可是点击登录并没有反应，请帮忙查看原因

**Comment by yoyo837** [comment]
正如我发现的一个新大陆 https://github.com/ant-design/ant-design-pro/issues/1442#issuecomment-393754220 ，估计是谁开发中的私有branch部署上去了，并不是git repo里面代码体现一致的。

**Comment by chenshuai2144** [comment]
fix
