### ISSUE TITLE
Ant-Design-Pro 能否考虑更改Webpack编译工具呢？

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design-pro#1590]
操作系统: Ubuntu18.04 LTS
NodeJS版本:  8.4.0
Npm版本:  5.3.0
Roadhog: 2.3.0

在使用Antd-Design-Pro开发了几个项目后，我觉得Roadhog相比create-react-app之类的还是不太稳定，比如说module改动的时候不能准确稳定地监听并进行重新编译，无法定义前端页面变量来判断是dev还是prod，在修改src/theme.js的less变量时必须重启roadhog之后才能起作用等等。   
  
在我看来工具就是为了业务去服务的，对开发者来说稳定好用才是胜过一切，roadhog你们觉得是一个成熟稳定的工具吗？有经过完整的测试吗？ 如果不是，那为什么不采用前端业界普遍的更多人使用的搭建工具呢？一定要自己造一个并不稳定成熟的轮子呢？

可能你会说了，少抱怨，多贡献自己的代码。 但是我现在是站在一个普通开发者的角度来说，并不是每一个开发者都有时间为开源项目奋斗的，Antd-Design本身就是一个很好的UI库，dva也是一个比redux+redux-saga更方便的状态管理库，这些我用了都感觉良好。但唯独就是roadhog，用起来太折腾了，用起来就像是一个测试版本。说好的开箱即用呢？为什么我开箱之后先要对付着各种roadhog带来的问题呢？前端开源工具不应该就是为了更好的服务开发者吗？

因为被roadhog折腾到心累了，特意跑来这里发个issue。 如果你觉得我的想法幼稚的话，那就当我今天在这里吐个槽吧。我准备下一个项目使用create-react-app了，good bye roadhog!

**Comment by afc163** [comment]
Trace #1512
