### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by tiantian000** [ant-design/ant-design-pro#1591]
从git上clone的，npm start 为什么会报这个错误呢？

$ npm start

> ant-design-pro@2.0.0-beta.1 start E:\test\ant-design-pro
> cross-env ESLINT=none roadhog dev

'cross-env' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0-beta.1 start: `cross-env ESLINT=none roadhog dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.0.0-beta.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by chenshuai2144** [comment]
你需要先npm install
