### ISSUE TITLE
这两句顺序是不是反了

### ISSUE THREAD

**Issue by yanthink** [ant-design/ant-design-pro#1593]
https://github.com/ant-design/ant-design-pro/blob/95dbbf9f6cf49226adbf8b40619f05488e4448b3/src/utils/utils.js#L119-L121

**Comment by yanthink** [comment]
假如路由顺序写反了会导致404呢，例如 routes = [‘foo/bar’, 'foo'] 这样

**Comment by chenshuai2144** [comment]
你有兴趣 pr 一个 修复这个 bug 吗？
