### ISSUE TITLE
Add an update description component

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#1594]
Like the app's update log. use modal display.
Many of our features are non-perceived and require special clicks
What are your opinions?

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/40878367-b839019a-66c2-11e8-9134-f928b1bfa119.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/40878374-c1f2f2cc-66c2-11e8-8c88-5d576a20465c.png)

**Comment by chenshuai2144** [comment]
![default](https://user-images.githubusercontent.com/8186664/40878729-b8739486-66c7-11e8-9d59-842e23d49058.PNG)

**Comment by afc163** [comment]
没必要来这个，直接写 changelog https://pro.ant.design/docs/changelog-cn

然后和 antd 发布新版一样就好了，给个链接去看更新日志。

<img width="502" alt="image" src="https://user-images.githubusercontent.com/507615/41145191-dee28078-6b31-11e8-9509-4ba8f2caf24b.png">
