### ISSUE TITLE
instead of dynamicWrapper using react-loadable

### ISSUE THREAD

**Issue by veeramarni** [ant-design/ant-design-pro#1595]
Have you guys tried with [react-loadable](https://github.com/jamiebuilds/react-loadable.git) for dynamically rendering the components?

**Comment by chenshuai2144** [comment]
Welcome pr

**Comment by wanghche** [comment]
`const render = (loaded, props) => {
  const Component = loaded.default;
  if (!routerDataCache) {
    routerDataCache = getRouterData();
  }

  return createElement(Component, {
    ...props,
    routerData: routerDataCache,
  });
};

export const getRouterData = app => {
  const routerConfig = {
    '/': {
      component: Loadable({
        loader: () => import('../layouts/BasicLayout'),
        render,
        loading,
      }),
    },`

**Comment by chenshuai2144** [comment]
@wanghche  可以搞个 pr 吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/1781
