### ISSUE TITLE
如何删除统计链接

### ISSUE THREAD

**Issue by ivenabc** [ant-design/ant-design-pro#1596]
http://www.jietu365.com/prt/tmj.htm?u=u71272acf4164a87b99dcd20d51a0329&c=chrome-ty-jtds&v=1.0.1.8&v1=1.0.1.8&v2=1.0.1.8&s=2&ss%5B%5D=jtds&t=14&sd=10&tms=1528000755952&r=&d=http%3A%2F%2Flocalhost%3A9099%2Fstatic.html%23%2Fdashboard%2Ftasks

**Comment by chenshuai2144** [comment]
是你的Google插件
