### ISSUE TITLE
请问build如何能给js和css加上hash值？

### ISSUE THREAD

**Issue by zhangzheyuan** [ant-design/ant-design-pro#160]
roadhog build并不会给js和css加上hash值，请问要如何配置才能加上？

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog#hash

**Comment by zhangzheyuan** [comment]
这样配置index.html引用的js和css并不会加上hash

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog/issues/386
