### ISSUE TITLE
Cannot find name 'function' in typescript

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design-pro#1602]
_ant-design-pro@1.3.0@ant-design-pro\lib\Charts\ChartCard\index.d.ts
`export interface IChartCardProps {  
  title: React.ReactNode;    
  action?: React.ReactNode;
  total?: React.ReactNode | function | number;
  footer?: React.ReactNode;
  contentHeight?: number;
  avatar?: React.ReactNode;
  style?: React.CSSProperties;
}`
ant-design-pro\lib\Charts\ChartCard\index.d.ts
`export interface IChartCardProps {
  title: React.ReactNode;
  action?: React.ReactNode;
  total?: React.ReactNode | function | number;
  footer?: React.ReactNode;
  contentHeight?: number;
  avatar?: React.ReactNode;
  style?: React.CSSProperties;
}`
_ant-design-pro@1.3.0@ant-design-pro\lib\Charts\Pie\index.d.ts
`export interface IPieProps {
  animate?: boolean;
  color?: string;
  height: number;
  hasLegend?: boolean;
  padding?: [number, number, number, number];
  percent?: number;
  data?: Array<{
    x: string | string;
    y: number;
  }>;
  total?: string | function;
  title?: React.ReactNode;
  tooltip?: boolean;
  valueFormat?: (value: string) => string | React.ReactNode;
  subTitle?: React.ReactNode;
}`
ant-design-pro\lib\Charts\Pie\index.d.ts
`export interface IPieProps {
  animate?: boolean;
  color?: string;
  height: number;
  hasLegend?: boolean;
  padding?: [number, number, number, number];
  percent?: number;
  data?: Array<{
    x: string | string;
    y: number;
  }>;
  total?: string | function;
  title?: React.ReactNode;
  tooltip?: boolean;
  valueFormat?: (value: string) => string | React.ReactNode;
  subTitle?: React.ReactNode;
}`

Errors exist in these files， I just install the latest version

**Comment by chenshuai2144** [comment]
尽快修复！

**Comment by chenshuai2144** [comment]
试试 2.0.0-beta.1
