### ISSUE TITLE
关于antdpro权限验证的问题

### ISSUE THREAD

**Issue by RanranLiu111** [ant-design/ant-design-pro#1606]
为什么使用 npm  start时没有 admin和user的权限就能直接到主页面而不是跳回 /user/login路由页面

**Comment by wangyun122** [comment]
```javascript
export function getAuthority() {
  return localStorage.getItem('antd-pro-authority') || 'admin';
}
```

**Comment by wangyun122** [comment]
[src/utils/authority.js](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/authority.js)
antd pro的权限存在localStorage的key为'antd-pro-authority'。getAuthority这个方法就是获取权限。默认如果没有权限获取的就是'admin'。不知道你们问的是不是这个。。

**Comment by RanranLiu111** [comment]
哦，是在这个地方有默认设置啊，理解了，谢谢
