### ISSUE TITLE
文件命名太糟糕了

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design-pro#1609]
这个不是功能BUG！！！！我是来吐槽的。

这么牛逼的一个框架，看源码的时候简直要疯了。就拿认证来说吧。

- 无数的`authorized`来袭。

不仅是文件名，还是变量。举例说明：
`component/Authorized/`， `component/Authorized/Authorized`（PS：`component/Authorized/`这个目录底下还有`index.js`，），`utils/Authorized`（PS；写成`utils/AuthorizedUtil`不是更好吗），`utils/authority`

- 导出类和使用名称不一样

`components/index.js` 导出
```
export default renderAuthorize;
```
`utils/Authorized.js` 导入
```JS
// 为什么要加个 d 
import RenderAuthorized from '../components/Authorized';
```

**Comment by chenshuai2144** [comment]
是时候提一个 pr 了

**Comment by afc163** [comment]
Authorized 表示被动语态，应该就是一个命名偏好。

**Comment by ganxunzou** [comment]
只是吐槽一下，今天先看一下这个是如何实现路由校验的。代码从上往下是很好查找的，但是从下网上找（查找对谁调用他）就比较麻烦了，然后命名有增加了阅读的成本。

仅是吐槽。问题我自己关闭了。
