### ISSUE TITLE
怎么把this.state.data在src使用中，使src正常显示

### ISSUE THREAD

**Issue by lingxiaoxin** [ant-design/ant-design-pro#1612]
`<iframe src="http://．．．?from=now-6h&var-cluster=xxx&var-exchange=xxx&var-product=xxx&var-contract={**this.state.data**}&theme=light" width="100%" height="350" frameBorder="0"></iframe>`
我现在把数据放进src中，如上，数据都能够打印出来，但是在页面中不能显示，请问如何使src取到调用值，使它能在页面中显示出来？？

**Comment by lingxiaoxin** [comment]
data是一个数据
console.log(this.state.data) 打印出来是　hsi10

**Comment by chenshuai2144** [comment]
string?
