### ISSUE TITLE
重复使用pie chart出现第二个pie不渲染的问题

### ISSUE THREAD

**Issue by hawaiiey** [ant-design/ant-design-pro#1615]
如下图所示：
![2018-06-05 9 09 40](https://user-images.githubusercontent.com/25291779/40978832-c9aca4fe-6906-11e8-9857-86eb1fad794b.png)

在重复使用pie chart之后
第二个pie不渲染

ps: 好像还会影响到我后面的图形的渲染情况

**Comment by jackywq** [comment]
我遇到的问题和你一样，请问问题解决了么？
