### ISSUE TITLE
使用v2版本，编译十分缓慢

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#1617]
最近使用了新版的v2，编译时有进度显示，但是每次修改单个文件都要编译10到30秒，等编译完成后浏览器页面又要等10到20秒左右才能显示，编译这块有没有优化的方法呢，感觉这样太浪费时间了。

**Comment by chenshuai2144** [comment]
试试最新的！速度会快一些

**Comment by zhaxingaz** [comment]
我是前两天刚下载的版本，难道不是最新的吗？

**Comment by zhaxingaz** [comment]
还有npm start 有时会出现报错：
Error: watch /home/bruce/ant-design-pro-2/.roadhogrc.mock.js ENOSPC

**Comment by okool** [comment]
希望官方优化一下,整体动画太顿不流畅.

**Comment by 533001** [comment]
最新版,不在了,怎么体验
