### ISSUE TITLE
如何搭建一套完善的开发工具, 能够解决 自动导入, 和 组件重命名,和路径智能感知这些痛点?

### ISSUE THREAD

**Issue by dengyakui** [ant-design/ant-design-pro#1619]
如何搭建一套完善的开发工具, 能够解决 自动导入, 和 组件重命名,和路径智能感知这些痛点?

之前用了vscode 来写, 装了20多个插件, 
 但是很多时候,自动import没有效果,还要手写import,
特别是编辑器会把 ant 中内置的 Form 组件 和html 原生的 form 作为一个东西对待,,每次用到都要手动去import ,影响效率,大家开发时有遇到同样的问题吗

**Comment by chenshuai2144** [comment]
vscode 使用 typescript 就可以实现你的需求

**Comment by dengyakui** [comment]
请问typescript 的支持是长期的吗 会一直更新吗?
