### ISSUE TITLE
在typescript中，common/router.js 中第37行报错

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design-pro#1621]
ERROR in \src\common\nav.ts(37,5)

`return dynamic({
    app,
    models: () =>
      models.filter(model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return component().then(raw => {
        const Component = raw.default || raw;
        return props =>
          createElement(Component, {
            ...props,
            routerData: routerDataCache,
          });
      });
    },
  });`

app这个对象的定义错误，其实这个是dva的错误。。。
      TS2345: Argument of type '{ app: any; models: () => any; component: () => any; }' is not assignable to parameter of type '(value?: PromiseLike<any>) => void'.
  Object literal may only specify known properties, and 'app' does not exist in type '(value?: PromiseLike<any>) => void'.

**Comment by wanliyunyan** [comment]
dynamic 的第一个参数 app

**Comment by chenshuai2144** [comment]
any 大法好！

**Comment by wanliyunyan** [comment]
@chenshuai2144 我还是去找作者吧。。。确实是dva 中 dynamic 定义类型的错误，在这题issue，确实也不解决问题。。。

**Comment by ravencrown** [comment]
> @chenshuai2144 我还是去找作者吧。。。确实是dva 中 dynamic 定义类型的错误，在这题issue，确实也不解决问题。。。

所以这个问题最后怎么解决呢？

**Comment by wanliyunyan** [comment]
@chenshuai2144 没下文了，我已经不打算用dynamic，用react自带的lazy

**Comment by chenshuai2144** [comment]
@wanliyunyan react的 lazy 的确很好用。
