### ISSUE TITLE
About the understand of code process about the login and register 

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#1626]
As a green hands of ant-design-pro, I don't understand the route about the login and the register process.
I also couldn't understand the route relation of the showing page after I login. Could anybody help me understand the process? Or anybody has anything recommended information about ant-design-pro? I could not find some valuable information about the code explanation .

Best Wishes! 
Thank you.

**Comment by chenshuai2144** [comment]
Is controlled by permissions

**Comment by m26597** [comment]
Thanks for your helping. I will try my best to understand the constitute of dva and try to do contrubute code to the community.
