### ISSUE TITLE
本地引入三方 iconfont 不成功

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design-pro#1628]
使用的 iconmoon 导出本地字体文件，使用后界面只显示白框。

<img width="782" alt="2018-06-07 2 34 44" src="https://user-images.githubusercontent.com/9986421/41082189-0790c6ba-6a60-11e8-8a2c-9250ce57e844.png">

<img width="878" alt="2018-06-07 2 37 22" src="https://user-images.githubusercontent.com/9986421/41082380-b76676e8-6a60-11e8-93c9-8abebb795c3e.png">

看上去 css 都正常加载了，但字体文件却没有正常渲染。不知道哪里出了问题。
官方文档的引入三方字体只介绍了 CDN 的方式。

**Comment by chenshuai2144** [comment]
脚手架还是组件？

**Comment by uni-zheng** [comment]
@chenshuai2144 你说的名词我不太能准确理解。但我猜你想知道，我这边使用的是 antd pro。

**Comment by chenshuai2144** [comment]
不是很懂的你的用法，代码层面呢？

**Comment by uni-zheng** [comment]
1. 在主样式入口添加了 iconfont(实际是 iconmoon 提供的文件) 样式文件
<img width="634" alt="2018-06-08 9 45 14" src="https://user-images.githubusercontent.com/9986421/41134787-c271e900-6b00-11e8-97aa-f288a10dd5a0.png">

2. iconfont 文件中有对字体的引入 class 的设置，字体的 class
<img width="747" alt="2018-06-08 9 45 34" src="https://user-images.githubusercontent.com/9986421/41134819-f3e8aece-6b00-11e8-8837-103947f14eb2.png">

3. 在使用的地方，class 已经正常匹配上了
<img width="878" alt="2018-06-07 2 37 22" src="https://user-images.githubusercontent.com/9986421/41134837-0f5baad0-6b01-11e8-97cf-504599775f54.png">

4. 但仍然显示白框
<img width="480" alt="2018-06-08 9 45 48" src="https://user-images.githubusercontent.com/9986421/41134902-60ead4c0-6b01-11e8-991f-9224a02db722.png">

**Comment by chenshuai2144** [comment]
字体加载回来了？

**Comment by afc163** [comment]
最好给重现的 repo，这样提问基本上没法解决。

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。

**Comment by uni-zheng** [comment]
## 我以为我描述的够清楚了。不过我还是读了一下提问的智慧。为了进一步找到问题的原因，我又做出了以下操作：

@chenshuai2144 @afc163
为了排除无关的干扰，我从新 clone 了一个 ant-design-pro 项目，从 iconfont.cn 创建了一个新项目。
并按照 antd-pro 的文档「文档->进阶->业务图标」尝试了一下CDN的方式引入，可以正常显示图标。但下载后使用本地文件仍然不显示。

1. 下载 iconfont 并放入 src/assets 中
<img width="968" alt="2018-06-08 4 57 21" src="https://user-images.githubusercontent.com/9986421/41149217-9de6b178-6b3d-11e8-9441-32c3216474d7.png">

2. 在 index.less 中引入 iconfont.css 文件
<img width="569" alt="2018-06-08 5 02 11" src="https://user-images.githubusercontent.com/9986421/41149282-bf9f8042-6b3d-11e8-8207-41f5722e68ed.png">

3. 在 Analysis.js 文件中使用 iconfont，分别用 unicode 和 font-class 方式加入图标
<img width="497" alt="2018-06-08 5 03 18" src="https://user-images.githubusercontent.com/9986421/41149345-e834a280-6b3d-11e8-9d80-70553fb4c7ff.png">

4. 不显示
<img width="804" alt="2018-06-08 5 04 54" src="https://user-images.githubusercontent.com/9986421/41149424-1a62ff0e-6b3e-11e8-8c37-e04a17c59d55.png">


fork 了一个项目 并提交了一个 commit
https://github.com/uni-zheng/ant-design-pro.git

**Comment by pkaq** [comment]
直接使用飞冰物料即可
[dynamic-icon](https://www.npmjs.com/package/dynamic-icon)

**Comment by uni-zheng** [comment]
@pkaq 谢谢，看了，但我们项目没法使用 CDN

**Comment by uni-zheng** [comment]
@chenshuai2144 @afc163 你好 目前有什么建议么

**Comment by chenshuai2144** [comment]
给个重现地址吧

**Comment by afc163** [comment]
发了 PR：https://github.com/uni-zheng/ant-design-pro/pull/1

基本上，你需要参考 https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont 和了解本地部署 iconfont 的原理。
