### ISSUE TITLE
导航设置为顶部导航后，菜单超出后换行

### ISSUE THREAD

**Issue by liuzm** [ant-design/ant-design-pro#1629]
导航设置为顶部导航后，菜单超出后换行：如图
![1528365216721](https://user-images.githubusercontent.com/17808435/41092565-bc7ebdd2-6a7b-11e8-9d10-20efc3f04f8a.jpg)
能超出后隐藏或者滚动导航吗

**Comment by xchengguang** [comment]
请教下，怎么把侧边栏隐藏掉或者去除掉，我只有一个单页面

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/717

**Comment by chenshuai2144** [comment]
2.0已发布，其中加入了这个功能
