### ISSUE TITLE
request 请求Method为PATCH，怎么变成OPTIONS了？

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-design-pro#1633]
![20180608_104142](https://user-images.githubusercontent.com/7280016/41136501-25548a2a-6b09-11e8-8a19-7fe14a560bce.png)

**Comment by afc163** [comment]
跨域问题，请自行 google 解决。

**Comment by wuyongdec** [comment]
我用Post man 测试了一下，请求正常，没有403。我之前的POST 和 GET 都没有问题

**Comment by chenshuai2144** [comment]
这是跨域的逻辑，先发一个option ，成功了就会发送真正的请求

**Comment by wuyongdec** [comment]
我PATCH Request URL 写错了，没有进反向代理。
改过就好了，谢谢大佬解答

**Comment by ybning** [comment]
@wuyongdec 
#### [HTTP访问控制（CORS）](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS)
