### ISSUE TITLE
TagSelect 从后台取回数据 默认值设置不了

### ISSUE THREAD

**Issue by x1nGoo** [ant-design/ant-design-pro#1634]
dipatch 从后台取回数据 然后设置 默认值 defaultValue， 没有效果，value 输出还是空数组,
直接静态设置就可以，该怎么解决？

**Comment by dengfuping** [comment]
@x1nGoo `defaultValue` => `value`

**Comment by x1nGoo** [comment]
@dengfuping 没懂
