### ISSUE TITLE
menu 配置问题

### ISSUE THREAD

**Issue by baifeifei** [ant-design/ant-design-pro#1639]
我在登陆成功后会将 用户信息存入cookie  然后在menu.js中获取cooike中的用户信息 并查询对应的menus

但是menu.js 只会在项目启动时加载一次，再layout中import menu.js 并调用getMenuData() 并不会重新加载menu,js 导致无法获取menu , 只有刷新页面才会再次加载menu.js

**Comment by chenshuai2144** [comment]
有几个地方依赖了 this.menu.
