### ISSUE TITLE
v2 Select PaickerDate组件样式问题

### ISSUE THREAD

**Issue by zwjun** [ant-design/ant-design-pro#1640]
v2版本采用herder sider固定布局，Select PaickerDate组件展示选择列表，滚动页面时没有紧贴输入框滚动。
https://beta.preview.pro.ant.design/#/form/advanced-form

**Comment by afc163** [comment]
@chenshuai2144 固定侧边栏/顶部的实现最好不要修改滚动区域，保持 body 滚动是最简单的。

**Comment by chenshuai2144** [comment]
ok  我想个办法

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/ant-design-pro/commit/904ca0aeffa8f8eb643449e8c336e57fcf9e88db
