### ISSUE TITLE
使用pro时候 我想请求 使用 我的服务器接口地址 但是更改了之后 无效 无论怎么改都是请求到了localhost

### ISSUE THREAD

**Issue by zhaohongwei978** [ant-design/ant-design-pro#1642]
我设置了 proxy 
// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';
让 noProxy ＝ture  
export default noProxy ? {
  'GET /api/(.*)': 'http://111.231.136.62/dcsns/api/',
  'POST /api/(.*)':'http://111.231.136.62/dcsns/api/',
} : delay(proxy, 1000);

一直 切不到我自己的 服务器地址 已经搞了 2天了

但是 都无效 request.js:80 POST http://localhost:8000/api/common/login 400 (Bad Request) 
每次 都这么错误

**Comment by F-loat** [comment]
http://111.231.136.62/dcsns/api/ -> http://111.231.136.62/dcsns/api

**Comment by chenshuai2144** [comment]
试试把代理写在 webpackrc 中
