### ISSUE TITLE
run build 后放入nginx，login 成功了为何路由不跳转呢？

### ISSUE THREAD

**Issue by wuyongdec** [ant-design/ant-design-pro#1645]
在开发环境登陆成功跳转没有问题。

**Comment by chenshuai2144** [comment]
报错？可重现地址？

**Comment by wuyongdec** [comment]
没报错，难道要用browserHistory？

**Comment by chenshuai2144** [comment]
是不是改了什么东西？

**Comment by wuyongdec** [comment]
NGINX 我这样配置的：
```
location /api { 
                proxy_pass   http://localhost:8080/api;
            }
location /login { 
                proxy_pass   http://localhost:8080/login;
            }

```
![20180611_142341](https://user-images.githubusercontent.com/7280016/41215558-7b0e411e-6d83-11e8-928f-1623cdf28c61.png)

**Comment by chenshuai2144** [comment]
明显是没有问题的、问题应该在你的代码逻辑里面

**Comment by wuyongdec** [comment]
也没有什么特别的操作
login 成功了，我就调用了
```
 reloadAuthorized();
 yield put(routerRedux.push('/list/new'));
```
开发环境没有问题，在nginx 不报错也不跳转 ;(

**Comment by chenshuai2144** [comment]
试试改成 

 `yield put(routerRedux.push('/list/new'))`

**Comment by wuyongdec** [comment]
改成：
`yield put(routerRedux.push('/'))
`
也和之前一样。
感觉是NGINX 和Redux 哪里需要配置一下

**Comment by uk0** [comment]
编译完成了 放入 nginx 无法加载样式 遇到过么
