### ISSUE TITLE
setting 数据的存储

### ISSUE THREAD

**Issue by lawrence-peng** [ant-design/ant-design-pro#1647]
看到把 setting 的 state 数据存在 url 上，感觉好别扭，我个人觉得存在 storage 会不会更合适。

**Comment by chenshuai2144** [comment]
为了方便分享 
setting 本身不应该存在于开发环境

**Comment by lawrence-peng** [comment]
* 这个应该是个性化设置吧，个性化的数据存在自己本地，也属正常，这些设置我感觉没有必要分享，自己设置一下也很快搞定的嘛。
* 如果放在 URL 上，用户下次打开时，就会丢失上次的设置，还得再重新设置一遍，不友好。
