### ISSUE TITLE
setting panel 

### ISSUE THREAD

**Issue by lawrence-peng** [ant-design/ant-design-pro#1649]
* setting 有滚动条时，有一个小问题，如下图所示。
![image](https://user-images.githubusercontent.com/13516546/41230184-6557f288-6db1-11e8-9a3a-29820e115f43.png)
* 我在打开 setting 状态时，即：collapse=true 时，我 F5 刷新页面，发现面板没有收缩，但 collapse 的图标是 齿轮 不是 x 。

**Comment by lawrence-peng** [comment]
![image](https://user-images.githubusercontent.com/13516546/41230504-a5926486-6db2-11e8-8e28-d32428326212.png)

**Comment by F-loat** [comment]
第二个问题好像没有复现

**Comment by lawrence-peng** [comment]
对的，好像有点偶然性，多整几回吧

**Comment by chenshuai2144** [comment]
@F-loat  有兴趣搞这个吗？

**Comment by F-loat** [comment]
@chenshuai2144 第一个问题提了个 pr 了，第二个暂时没复现，晚点我再看看

**Comment by F-loat** [comment]
@lawrence-peng 你在这个页面试下 https://beta.preview.pro.ant.design ，目前应该不会保留设置面板的打开状态，没有那个问题了吧

**Comment by chenshuai2144** [comment]
可能是在线编译 less 的原因吧

**Comment by lawrence-peng** [comment]
@chenshuai2144  是的。选择主题后，再试就容易重现问题

**Comment by F-loat** [comment]
和缓存可能也有关系，试了下先调用这个 `window.less.refresh()`，但是太慢了，可以给 `colorChange` 加个回调来再关一次 collapse ？

**Comment by F-loat** [comment]
嗯，我在 #1652 加了一个 commit，你们可以试下看看，性能问题应该是我标签页开太多导致的。。`colorChange` 里有个延时好像没什么必要，我先去掉了

**Comment by chenshuai2144** [comment]
那个延时是为了先把 loading 显示出来 不然会卡住

**Comment by F-loat** [comment]
我这边目前应该是没什么问题的

**Comment by chenshuai2144** [comment]
我这边有时候会卡住。估计和 chrome 的进程太多有关系

**Comment by F-loat** [comment]
那把延时保留着吧

**Comment by lawrence-peng** [comment]
![image](https://user-images.githubusercontent.com/13516546/41340934-15d051a8-6f2b-11e8-9eae-54471b61d245.png)
![image](https://user-images.githubusercontent.com/13516546/41340969-299e5ffe-6f2b-11e8-8ebe-7554df214493.png)
对这个 less 加载机制不太了解，为什么下面那两个主题颜色没有改变呢。 @F-loat

**Comment by chenshuai2144** [comment]
配置问题 我正在想办法解决这个问题
