### ISSUE TITLE
动态载入Select的Option导致报错

### ISSUE THREAD

**Issue by huangjiaxing** [ant-design/ant-design-pro#165]
使用Select组件，如果是普通的写法
`<Select>
  <Option value='1'>xx</Option>
</Select>`
没有问题。但是如果Option是动态载入的，比如初始化从服务器读取，
`{
      allNames.map((value) => {
        return `<Option value="${value.id}">${value.name}</Option>`;
            })
         }`
就会报错。提示 
Select.js?feca:845 Uncaught TypeError: Cannot read property 'isSelectOptGroup' of undefined

**Comment by afc163** [comment]
建议有空阅读下 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。信息提供的太少了。

**Comment by huangjiaxing** [comment]
好的，感谢你的及时回复。我之后会注意
是我写代码粗心了，返回jsx格式我写成string了，关闭吧
