### ISSUE TITLE
左侧导航的路由带参数

### ISSUE THREAD

**Issue by zywcode** [ant-design/ant-design-pro#1651]
![image](https://user-images.githubusercontent.com/4060640/41236766-8183d856-6dc4-11e8-852b-fb31c1e5aa6e.png)
![image](https://user-images.githubusercontent.com/4060640/41236811-9bb2a66c-6dc4-11e8-924f-f3213682872d.png)

想在左侧导航的路由中加参数，这种应该怎么解决？

**Comment by chenshuai2144** [comment]
带参数是动态路由，不应该出现在菜单中的

**Comment by zywcode** [comment]
![image](https://user-images.githubusercontent.com/4060640/41273975-389f2408-6e4e-11e8-86e3-d69b9e83b25e.png)

@chenshuai2144 文档里就是这样写的，支持带参数的路由和菜单。

**Comment by chenshuai2144** [comment]
你理解错了，参数是动态的，你不能通过静态调用他

**Comment by zywcode** [comment]
@chenshuai2144 那在文档中菜单加参数还有什么意义呢？就像`/:list/table-list`菜单。

**Comment by chenshuai2144** [comment]
参数路由，顾名思义 是用来传递参数的。
去了解一下 react-router 和 rest url 吧

**Comment by zywcode** [comment]
@chenshuai2144 我知道参数路由是用来传参数，路由中这样配置没有问题。我的意思是菜单没法接收参数变成动态菜单，那这样配置菜单参数还有什么意义？

**Comment by chenshuai2144** [comment]
菜单是固定的 路由才是动态的

**Comment by warmhug** [comment]
推荐增加个 列表 -> 详情 更实际点的示例。比如 列表页的列表项有个
`<a href={`#/coa/newCoaTree?type=1&treeId=${record.treeId}`}>详情</a>`
详情页面 newCoaTree 的 router 怎么写？怎么能同时支持 browser history 和 hash history ？最好能有个最佳实践 demo
