### ISSUE TITLE
如何在增删改后直接刷新页面？

### ISSUE THREAD

**Issue by nnzbz** [ant-design/ant-design-pro#1653]
增删改查我参考了查询表格的写法，但是这个Demo在增删改的时候是直接返回一个列表的，
我是后端的架构师，前端不太扎实
可我知道这在我的架构里是非常不合理的，因为接口在其它情况下没必要返回这么多无用的元素，想在增删改后再由客户端发出刷新的请求，这样既合理又简单
该怎么做呢？

**Comment by baifeifei** [comment]
增删改 后只刷新操作过的数据？

**Comment by nnzbz** [comment]
只刷新当前页面就可以了

**Comment by chenshuai2144** [comment]
重新请求一下查询？

**Comment by nnzbz** [comment]
对，如何重新请求查询？能具体些吗？

**Comment by chenshuai2144** [comment]
如果你是用的 redux ，直接调用 action 就好了

**Comment by nnzbz** [comment]
我是用的redux，因为我没有大改ant design pro的架构，可是在哪个文件的哪个方法调用 action，怎么调用，能稍微具体一点吗？

**Comment by chenshuai2144** [comment]
看具体业务。dva 了解一下
这个很简单的，我们不能帮你写代码的。

**Comment by zhang0ZGC** [comment]
只要props变了，页面不就是刷新了么

**Comment by WuJiY** [comment]
在model里  如果更新成功里  调用一下  yield put({ type: 'fetch' })

**Comment by superwuman** [comment]
> 只要props变了，页面不就是刷新了么

props数据变了，页面数据也不变，这是什么情况
