### ISSUE TITLE
BUG: utils/request.js

### ISSUE THREAD

**Issue by nnzbz** [ant-design/ant-design-pro#1654]
50行
if (newOptions.method === 'POST' || newOptions.method === 'PUT') {
改为
if (newOptions.method === 'POST' || newOptions.method === 'PUT' || newOptions.method === 'DELETE') {
否则，DELETE方式的request时body将失效

**Comment by chenshuai2144** [comment]
pr 一个？

**Comment by nnzbz** [comment]
PR了

**Comment by lawrence-peng** [comment]
PATCH呢？
