### ISSUE TITLE
upgrade deps

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#1659]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/507615/41288155-e8a53c06-6e77-11e8-9904-39b712b0becf.png">

**Comment by chenshuai2144** [comment]
v2经常更新的，master有点老了

**Comment by afc163** [comment]
都更新一遍好了。

**Comment by chenshuai2144** [comment]
已经 ok 了
