### ISSUE TITLE
单独使用ant-design-pro包，出现编译问题

### ISSUE THREAD

**Issue by JaniceLian** [ant-design/ant-design-pro#166]
- 根据[Use Pro Components Alone](https://pro.ant.design/docs/use-components-alone)描述，在项目中install了ant-design-pro包；

- 在页面开发中，引用pro的组件，类似antd组件写法，如下：
```
import {  Trend, NumberInfo, } from 'ant-design-pro';
```

- 启动项目，会出现编译错误，如下：
```
./node_modules/ant-design-pro/es/TagSelect/index.js
Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
| 
| const TagSelectOption = ({ children, checked, onChange, value }) => (
|   <CheckableTag
|     checked={checked}
|     key={value}
```

是需要添加其他什么配置吗？

**Comment by nikogu** [comment]
@JaniceLian 你是自己的项目吧，这个要加 babel 的，参看：https://github.com/ant-design/ant-design-pro/blob/master/package.json#L79

**Comment by JaniceLian** [comment]
@nikogu 嗯，这个有加的。目前是在ant-design-pro的脚手架项目上进行修改的，我在项目里install了ant-design-pro，页面上的使用路径不是从components下面引用，直接
```
import {  ChartCard,  MiniBar, TimelineChart, } from 'ant-design-pro';
```
这样就编译不通过了

**Comment by afc163** [comment]
不要这么引用，按文档的引用方式来。

**Comment by JaniceLian** [comment]
找到解决办法了，删掉es文件夹，或者重命名es文件夹，使它不被调用到，调用lib下面的版本，目前测试了几个可以通过。

**Comment by JaniceLian** [comment]
@afc163 按照文档是每个组件一个个引用吗？
```
import Result from 'ant-design-pro/lib/Result';
```
这样？

**Comment by afc163** [comment]
对的。

**Comment by JaniceLian** [comment]
@afc163 👍确实是你说的这种使用比较好！这样不会把整个包build进去，按需加载。

**Comment by anwfr** [comment]
Hello,
I had similar issue. For using ant-design-pro as an external library, you need to use "transform-class-properties" and ""transform-decorators-legacy".
This can be done by adding the following rule in webpack config:

```
rules: [
    {
        test: /\.js$/, // Required to compile ant-design-pro
        include: [/node_modules\/ant\-design\-pro/],
        loader: 'babel-loader',
        query:
          {
            cacheDirectory: true,
            plugins:
              [
                "transform-class-properties",
                "transform-decorators-legacy"
              ],

          }
      },
]
```
