### ISSUE TITLE
建议修改，登录判断用户是否为空，否则样例会抛异常

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-pro#1661]
/src/components/GlobalHeader/index.js

124 行
            count={currentUser.notifyCount}
建议修改为
            count={currentUser ? currentUser.notifyCount : 0}

152 行
          {currentUser.name ? (
建议修改为
          {currentUser && currentUser.name ? (

**Comment by chenshuai2144** [comment]
有兴趣帮忙 pr 一个吗？
