### ISSUE TITLE
请问使用 node 8.11.2打包出这个错是啥原因啊？谢谢

### ISSUE THREAD

**Issue by cnhans** [ant-design/ant-design-pro#1663]
Failed to compile.

./src/routes/List/TableList.js
Module build failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Array.map (<anonymous>)

**Comment by chenshuai2144** [comment]
babel 新版本的搞的鬼，看一看历史 issue

**Comment by cnhans** [comment]
ok 多谢
