### ISSUE TITLE
项目更新问题

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design-pro#1664]
现在我们碰到一个情况是我们自己的项目没法同步template的bug修复，比如[#1428](https://github.com/ant-design/ant-design-pro/pull/1428)这一个，我们是碰到了问题才主动查看template代码修改才知道这里的bug已经被修复了。

所以我们通过copy template新建了一个项目，但是之后template是一直在更新并修复bug的，我们如何同步这些bug到我们自己的项目中？

**Comment by chenshuai2144** [comment]
搞一个新的 remote 一直 merge 就好了，
暂时没有很大的改动了

**Comment by chenshuai2144** [comment]
因为我们其实不是一个组件。设计的代码改动有太多太多。

**Comment by yoyo837** [comment]
我的做法是，clone下来每日关注commit，人工同步到自己的项目中

**Comment by lawrence-peng** [comment]
@yoyo837 也是在用这样的办法
