### ISSUE TITLE
waterwave图形出错

### ISSUE THREAD

**Issue by HelenGuohx** [ant-design/ant-design-pro#1668]
你好，我在用waterwave的时候，由于percent为0时，图形不会显示，因此我修改了一下源码，把percent拆分成两个变量，控制图形水量的percent改为total，字段，其余不变。但是文件在某一版本可行，另一个版本不可行。还有就是当我比较两个版本的时候发现都是1.3.0这个版本，但是代码却不一样。请指教。
<img width="595" alt="2018-06-13 2 47 07" src="https://user-images.githubusercontent.com/35051874/41335444-6727c820-6f1b-11e8-8945-e41da8571d8d.png">
![111](https://user-images.githubusercontent.com/35051874/41335453-6d195208-6f1b-11e8-845b-418a75117c23.jpeg)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/1658
look

**Comment by HelenGuohx** [comment]
谢谢，水波图可以。但是饼图也出现了同样的问题

**Comment by chenshuai2144** [comment]
是时候 pr 一个了
