### ISSUE TITLE
项目老是停止要重启

### ISSUE THREAD

**Issue by lovemegowin** [ant-design/ant-design-pro#1671]
RT  

不知道是不是我配置有问题还是其他什么原因 改动几段代码之后项目就停止了  然后要重启 重启又要启动30秒左右  这样开发感觉蛮费时的  有没有遇到过这个问题的前辈 帮忙指点下  谢谢！

**Comment by chenshuai2144** [comment]
试着升级最新的 roadhog 稳定很多了
