### ISSUE TITLE
有没有可能修改加载chunk js文件的url

### ISSUE THREAD

**Issue by steem** [ant-design/ant-design-pro#1672]
disableDynamicImport设置为false后，routes下的模块会打包成chunk文件，默认的url格式是http://localhost:8000/x.async.js，x是一个数字编号。

我的问题是，有没有可能修改这个url，想达到的效果是：
http://localhost:8000/0.async.js 变为 http://ip:port/?chunk=0.async.js

其中ip可以是域名或IP地址，port是端口号

**Comment by chenshuai2144** [comment]
场景是？

**Comment by steem** [comment]
没有模块权限的时候，chunk文件不允许下载。
通过http://ip:port/?chunk=0.async.js 可以实现控制是否能下载。

**Comment by steem** [comment]
通过web服务器的rewrite功能可以做到。通过这种修改url的方式是否可行？
