### ISSUE TITLE
可不可以增加一些业务模板，比如左树右表格的模板

### ISSUE THREAD

**Issue by w3286879** [ant-design/ant-design-pro#1676]
可不可以增加一些业务模板，比如左树右表格的模板

**Comment by w3286879** [comment]
是的， 希望能多增加这样的业务模板由个参考。

**Comment by pkaq** [comment]
二楼是自动翻译机器人；）

**Comment by tianlinzx** [comment]
这个确实是个常用场景。支持增加

**Comment by ybning** [comment]
![2](https://user-images.githubusercontent.com/3725612/41728776-2eb3fcbc-75aa-11e8-9695-a4882bbcace0.png)
左树右表格，是个常用场景。
其实自己写也不费事。毕竟antd已经提供了tree和table

**Comment by w3286879** [comment]
@ybning   有时候发觉自己做出来的很丑 用Card来做。。。所以希望有个范例。

**Comment by chenshuai2144** [comment]
这个设计师暂时没有计划
