### ISSUE TITLE
有办法改造一下支持IE9吗

### ISSUE THREAD

**Issue by lichengfei911** [ant-design/ant-design-pro#1679]
请问有没有支持IE9的解决办法

**Comment by chenshuai2144** [comment]
你可以先列出来哪里不能用

**Comment by lichengfei911** [comment]
整个项目在IE9下都运行不了，页面都打不开

**Comment by wangyun122** [comment]
@lichengfei911 
[#83](https://github.com/dvajs/dva/issues/83)
首先`dva/fetch` 就不支持ie9。你可以先把这个处理看看看。

**Comment by yoyo837** [comment]
不用IE9，支持到IE10比较理想

**Comment by lichengfei911** [comment]
项目要求ie9,  ant-design不是可以支持i9吗，ant-design-pro,没有办法支持到ie9吗

**Comment by kunhour** [comment]
flex 没办法解决还有其他未知。

**Comment by yoyo837** [comment]
IE10模拟有这个：Cannot call a class as a function

**Comment by yoyo837** [comment]
好像和dva [这个](https://github.com/dvajs/dva/blob/df17bf5756c733bb58f1f86334e8fd3b26b258ae/packages/dva/src/dynamic.js#L14) 代码相关，调用堆栈此处的上一步是React中`mountIndeterminateComponent`的
  [`value = fn(props, context);`](https://github.com/facebook/react/blob/aeda7b745d9c080150704feb20ea576238a1b9a1/packages/react-reconciler/src/ReactFiberBeginWork.js#L605)

![image](https://user-images.githubusercontent.com/6134547/41948487-97535a6c-79ef-11e8-9db8-ff5f4b22527c.png)

**Comment by yoyo837** [comment]
最终的 See umijs/umi#544
