### ISSUE TITLE
<Selector> 默认值

### ISSUE THREAD

**Issue by edeity** [ant-design/ant-design-pro#168]
根据`Select`的[官方实例](http://design.alipay.com/develop/web/components/select/#components-select-demo-label-in-value)

```javascript
import { Select } from 'antd';
const Option = Select.Option;

function handleChange(value) {
  console.log(value);  // { key: "lucy", label: "Lucy (101)" }
}

ReactDOM.render(
  <Select labelInValue defaultValue={{ key: 'lucy' }} style={{ width: 120 }}>
    <Option value="jack">Jack (100)</Option>
    <Option value="lucy">Lucy (101)</Option>
  </Select>
, mountNode);
```

可以知道，当组件初始化的时候，显示的是`lcuy`对应的`Lucy(101)`；

但当Option是动态变更时， 如

```javascript
setTimeOut(() => {
  this.setState({
    children: (<Option value="jack">Jack (100)</Option>
    <Option value="lucy">Lucy (101)</Option>)
}))}, 100)

// ....

ReactDOM.render(
  <Select labelInValue defaultValue={{ key: 'lucy' }} style={{ width: 120 }}>
    {children}
  </Select>
, mountNode);
```

key显示的`lucy`；（我的期望是：`Lucy(101)`）

假如`defaultValue`仅代表初始化行为，那我要怎样才能做，才能在`Option`变更时，仍然显示的是`Lucy（101）`而不是`lucy`呢；我在现有的API中貌似找不到实现方式;

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

---

维护者精力所限，React 和 antd 使用类问题建议到 stackoverflow 和 segmentfault 上提问。
