### ISSUE TITLE
页面报错

### ISSUE THREAD

**Issue by wangyun122** [ant-design/ant-design-pro#1684]
这个页面报错:[卡片列表](https://beta.preview.pro.ant.design/#/list/card-list)
beta是v2版本吗？本地跑倒是没问题。

**Comment by chenshuai2144** [comment]
应该是 api 静态化造成的问题。因为写法不是很标准我搞了一下。

**Comment by wangyun122** [comment]
我还以为是有人报提过的`currentUser`的问题呢

**Comment by chenshuai2144** [comment]
那个已经合了  有个 pr

**Comment by chenshuai2144** [comment]
fixed
