### ISSUE TITLE
设置publicPath后路由匹配问题

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design-pro#1686]
.webpackrc.js设置publicPath为`/next/` 后，再修改路由配置以`/next/`开头，除了next的根路径其他都无法匹配，是否有这一块的指导文档或案例？

**Comment by chenshuai2144** [comment]
/next/next?

**Comment by yoyo837** [comment]
publicPath:  `/next/`
路由配置：`/next/user/login`   
默认访问`/next/` 进来后权限拦截到登录页`/next/user/login` , 刷新页面无法正常显示： `Cannot GET /next/user/login`

**Comment by chenshuai2144** [comment]
用hash路由就可以解决了？你用的nginx的话  试试配置tryfile

**Comment by yoyo837** [comment]
@chenshuai2144 dev试了下hash路由可以，意思是设置publicPath 没办法用history模式？
>你用的nginx的话 试试配置tryfile
意思是nginx配置tryfile能在线上使用history模式吗？

**Comment by chenshuai2144** [comment]
可以的 去了解一下router 
有很多这方面的配置 几乎所有的静态容器都有这样的配置

**Comment by yoyo837** [comment]
开发环境不使用静态容器如何使用history呢？roadhog上没寻到有用信息...

**Comment by chenshuai2144** [comment]
webpack server

**Comment by xietongjian** [comment]
配置nginx子目录失败，求解决方案。
