### ISSUE TITLE
如何使用 Browser History 运行在非根路径的后端服务上？（如 spring boot）

### ISSUE THREAD

**Issue by octopusthu** [ant-design/ant-design-pro#1687]
Spring Boot 运行在非根路径上，如：localhost:8080/context 。
与 Ant Design Pro 配合使用，有如下两个问题：

1. 前端跳转时直接跳向了根路径，如 /workplace 直接访问到了localhost:8080/workplace ，而非期望的 localhost:8080/context/workplace ；
2. API访问直接跳向了根路径，如 /api/fetchABC 直接访问到了localhost:8080/api/fetchABC ，而非期望的 localhost:8080/context/api/fetchABC 。

请问是否有通用的方法解决以上问题？

**Comment by chenshuai2144** [comment]
public path

**Comment by octopusthu** [comment]
在 .webpack.js 配置了 publicPath ，但并不解决上述两个问题。请仔细阅读一下问题。

**Comment by chenshuai2144** [comment]
解决办法就是代码中搞一个public path
