### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#1689]
src\assets\logo.png: SyntaxError: Unexpected character ' ' (1:1)
[error] > 1 |  PNG
[error]     | ^
[error]   2 | 
[error]   3 | 

这是什么情况，我这图片有什么问题吗？

**Comment by chenshuai2144** [comment]
更详细一点

**Comment by codepandy** [comment]
我就加了一个图片，提交就提交不了了

**Comment by chenshuai2144** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。

**Comment by codepandy** [comment]
问题解决了，prettier的配置引起的
修改.prettierignore文件
添加
```
**/*.png
```
