### ISSUE TITLE
decorators warning in VSCode

### ISSUE THREAD

**Issue by topwood** [ant-design/ant-design-pro#169]
decorators warning in VSCode.

> [js] Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

**Comment by afc163** [comment]
> Set the 'experimentalDecorators' option to remove this warning.

The hint is quite clear.

**Comment by topwood** [comment]
I fixed this warning by creating an file named jsconfig.json and put "experimentalDecorators" : true.
Thank you anyway.

**Comment by chenkang084** [comment]
i also have the problem, my solution is **User settings** -> `"javascript.implicitProjectConfig.experimentalDecorators": true`
