### ISSUE TITLE
How to use Redex DevTools to replace the console.log operation and the debugger?

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#1691]
I've learned the Redex DevTools that could make the dev process easier, but I don't know some using method of replacing the console.log operation and debuging with the breakpoing. Is there some detail handbook ? I've read the offical guide but don't receive much. Please help me, Thank you.

**Comment by chenshuai2144** [comment]
Are you sure you shouldn't ask Redex DevTools?

**Comment by m26597** [comment]
All right. Thank you.
