### ISSUE TITLE
打包后如何继续使用开发中创建的mock数据啊？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#1694]
###问题描述
打包后用node把静态文件启动起来了，但是数据都获取不到。
###问题
* 打包后如何继续使用原来的mock数据？
* .roadhogrc.mock.js文件还需要copy到打包文件中吗？

**Comment by chenshuai2144** [comment]
没那么简单！
你可以先用这个
https://github.com/chenshuai2144/pro-server

**Comment by codepandy** [comment]
这个server为什么不和ant design pro的mock保持一致呢？
这里面不支持es6的import，我把我的mock数据copy到mock文件夹后，把所有文件都又改成了commonjs的写法才能运行[笑哭]

**Comment by codepandy** [comment]
分享下使用方法：
* 把mock数据copy到mock文件夹下
* 把es写法改成commonjs的语法
