### ISSUE TITLE
npm  run  build error 

### ISSUE THREAD

**Issue by changyu72** [ant-design/ant-design-pro#1695]
Failed to minify the bundle. Error: index.34b8df31.js from UglifyJs
Unexpected token: name (Log) [index.34b8df31.js:1861,6]

**Comment by chenshuai2144** [comment]
是不是使用了 没编译的包。这个是 UglifyJs 无法打包 es6语法报错

**Comment by changyu72** [comment]
npm start 没问题，如何检测出哪个包未编译呢
