### ISSUE TITLE
如何使用axios代替dva/fetch?

### ISSUE THREAD

**Issue by okool** [ant-design/ant-design-pro#1696]
因为所有项目统一使用axios作数据请求.
dva默认使用fetch,换成axios或ajax后没法使用代理作API的mock?
请问如何统一封装request.js,自由更换网络请求库,而不产生影响呢?

**Comment by chenshuai2144** [comment]
可以是用 mock 的

**Comment by yoyo837** [comment]
换掉request.js实现就可以了

**Comment by pkaq** [comment]
@okool https://github.com/pkaq/ant-design-pro/blob/adam/src/core/utils/request.js

**Comment by DuduStyle** [comment]
@pkaq 您好，咨询您一个问题，有些页面的数据请求较多，可能某一条请求因为服务端的错误，报了500，这种情况都跳转到500页面会不会不好，这种情况您是怎么考虑的？

**Comment by yoyo837** [comment]
扩展请求调用传参，自己控制

**Comment by chenshuai2144** [comment]
@DuduStyle 那个代码主要是为了测试，我建议真实情况不要用

**Comment by DuduStyle** [comment]
@chenshuai2144 嗯
