### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 

### ISSUE THREAD

**Issue by sjpl3** [ant-design/ant-design-pro#1699]
router.js添加了 一个新的router
'/card/item':{
      component: dynamicWrapper(app, ['list'], () => import('../routes/Card/Item')),
    },
然后..运行项目就会报错....如果改成 '/dashboard/item/'则不会报错. 
顶层路由需要单独设置? 但是并没有在官方文档中找到相关内容.

**Comment by chenshuai2144** [comment]
需要一个 class 或者 function  但是你给了一个 object
