### ISSUE TITLE
没有登录不能进后台，怎么配置这个逻辑

### ISSUE THREAD

**Issue by jiankian** [ant-design/ant-design-pro#170]
如何实现需要登录成功才能进到后台的路由

**Comment by windzxa** [comment]
同问

**Comment by hqwlkj** [comment]
以下代码是我的处理方式，希望能够帮助到你，
`/权限验证(是否登录)
const handleAuth = function () {
  if (SS.get(Config.USER_TOKEN) === null) {
    fakeAuth.signout();
  }else{
    fakeAuth.authenticate();
  }
}

const fakeAuth = {
  isAuthenticated: false,
  authenticate() {
    this.isAuthenticated = true;
  },
  signout() {
    this.isAuthenticated = false;
  }
};


const PrivateRoute = ({ component: Component, ...rest }) => (
  <Route {...rest} render={props => (
    fakeAuth.isAuthenticated ? (
      <Component {...props}/>
    ) : (
      <Redirect to={{
        pathname: '/user/login',
        state: { from: props.location }
      }}/>
    )
  )}/>
)

function RouterConfig({ history }) {
  handleAuth();
  return (
    <LocaleProvider locale={zhCN}>
      <Router history={history}>
        <Switch>
          <Route path="/user" component={UserLayout} />
          <PrivateRoute path="/" component={BasicLayout}/>
          <Redirect to="/" />
        </Switch>
      </Router>
    </LocaleProvider>
  );
}`

你一可以参考官网的列子：https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by zhuanglong** [comment]
@hqwlkj 怎样在这里读取到dva中models

**Comment by hqwlkj** [comment]
@zhuanglong   你可以先去pull最新的代码来看看。新版的已经修改了nav.js 的结构。
