### ISSUE TITLE
Add service worker and other improment

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#1701]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/507615/41695750-f9272414-7542-11e8-8a6c-3c4537f9c8e8.png">

Our score in lighthouse is too low.

@chenshuai2144 @sorrycc

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/41695855-8f7792d2-7543-11e8-9dcb-c3da8b4a4dc6.png)

我做过一些优化，发布之后会好一点。
pro 的定位需要 Progressive Web App 吗？

**Comment by chenshuai2144** [comment]
PWA 已经搞了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/3542
