### ISSUE TITLE
HeaderSearch 组件中 onKeydown 方法中处理防抖的疑惑

### ISSUE THREAD

**Issue by RunningCoderLee** [ant-design/ant-design-pro#1703]
请问这个方法中的 `Fix duplicate onPressEnter` 是解决什么问题呢，是在处理防抖吗？

我在测试中发现无论是快速敲击 `Enter` 键，还是长按`Enter` 键，貌似都没有体现出防抖的特性。

OS： macOS High Sierra 10.13.5
浏览器：chrome 67.0.3396.87

代码如下：

https://github.com/ant-design/ant-design-pro/blob/9b08f2ea3ee954bc9afb4fc863de6ee41da65c93/src/components/HeaderSearch/index.js#L35-L41

**Comment by chenshuai2144** [comment]
这个代码应该删掉，其实是没有作用的

**Comment by RunningCoderLee** [comment]
那类似这种防抖的需求，你们更倾向于在组件内部处理还是交由使用的父组件去处理呢？

**Comment by chenshuai2144** [comment]
Loadsh 有专门的函数 注解一下就就好le

**Comment by RunningCoderLee** [comment]
那我用lodash中的debounce提一个增加防抖特性的PR是否有意义？

**Comment by chenshuai2144** [comment]
可以
