### ISSUE TITLE
可否将router,menu 动态化，在服务端配置，登录后获取到客户端后动态构建路由表及菜单

### ISSUE THREAD

**Issue by changyu72** [ant-design/ant-design-pro#1706]
1. router,menu 动态化，在服务端配置，登录后获取到客户端后动态构建路由表及菜单
2. 关于pro中的实现思路，mock 提供json（包括路由，菜单信息），通过接口获取后动态构建路由表及菜单，目前的实现将router与menu耦合在了一起，比较难用由于实际项目

**Comment by mushroomlb** [comment]
@ant-design-bot 英文翻译一遍是什么意思

**Comment by chenshuai2144** [comment]
机器人 方便外国人看
