### ISSUE TITLE
打包文件过大，公共库如何提取，按需加载

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#1711]
我打出来的包，光index,js 就有15M。我使用了官网的配置 disableDynamicImport：false  ，一个index.js变成了37个 async .js 文件。。这还没完，，关键的问题是。。本来一个index.js是15M。现在37个 async.js文件变成了 108M了。。。。而且我用roadhog的 commons 这个属性无效。。

环境如下：
roadhog 2.1.0（roadhog版本）
Nodejs and Npm version（Nodejs 和 Npm 版本）
nodejs v6.11.2 npm 3.10.10
Operating environment (e.g. OS name) and its version（操作系统版本）:
win10 专业版本

**Comment by chenshuai2144** [comment]
你用了什么？
会变得这么夸张

**Comment by xgj1988** [comment]
@chenshuai2144  我估计是把所有的node_modules都打进去了。。我就在想怎么分离。。还有就是按需打包。。我没用到的组件就不打包。。把通用组件放在一个包下面，还有就是roadhog是否可以用dll。

**Comment by chenshuai2144** [comment]
16m 一般 是用了很多重复的库

**Comment by chenshuai2144** [comment]
分析一下，然后用https://webpack.js.org/configuration/externals/
将一些不经常更新的库上一下 cdn

**Comment by chenshuai2144** [comment]
看我的最新提交 
搞掉了1m

**Comment by 520Yanxiaofei** [comment]
你好，请问你是怎么优化的呢，我的问题跟你是一样的，感觉心里有疙瘩 @xgj1988

**Comment by xgj1988** [comment]
@520Yanxiaofei  并没有解决
