### ISSUE TITLE
在fetch下使用FormData对form表单元素进行数据封装后进行post提交至服务器，其格式被转为了WebKitFormBoundary模式，怎么处理

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#1713]
![image](https://user-images.githubusercontent.com/12181423/41756280-55d2cb48-760e-11e8-9259-c632f3b163de.png)

请教一下这个问题怎么处理，在线等待。

**Comment by chenshuai2144** [comment]
服务器处理就好了 这个是完全标准的。
后端很容易就能识别
