### ISSUE TITLE
默认路由页的问题

### ISSUE THREAD

**Issue by neove** [ant-design/ant-design-pro#1714]
现在遇到的一个问题：开发环境本地调试的时候，默认路由是可以的，但是走生产环境打包后，就进不去默认路由页了，这个问题大家遇到过么
![image](https://user-images.githubusercontent.com/18530075/41756837-2a930f08-7611-11e8-8982-127ea37b8631.png)
![image](https://user-images.githubusercontent.com/18530075/41756841-30f4c21a-7611-11e8-932e-05f382404370.png)

**Comment by chenshuai2144** [comment]
感觉是你的版本库问题，这个代码不是业务代码吧

**Comment by neove** [comment]
对的，这不是业务代码报出来的，是第三方库里的

**Comment by chenshuai2144** [comment]
更新一下库试试
