### ISSUE TITLE
整体风格设置应该是一个整体

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#1715]
现在的整体风格设置只是把菜单由dark和light之间变换，叫整体风格设置应该全部跟着变.
如下图示意：
![default](https://user-images.githubusercontent.com/18542211/41758848-ce0003e2-761d-11e8-85b3-3585269f7223.png)
![1](https://user-images.githubusercontent.com/18542211/41758849-d1109c04-761d-11e8-800d-9ff766c1ca63.png)

**Comment by kaoding** [comment]
antd就一个菜单有dark和light风格，其它组件都没有风格。

**Comment by chenshuai2144** [comment]
你可以去 antd 搞一搞，
我们内部也会评议一下

**Comment by kaoding** [comment]
设计顺序：风格设计->主题设计->组件设计

**Comment by kaoding** [comment]
这个是应该到antd里去搞的。

**Comment by afc163** [comment]
2.0 的主题暂时不会提供 dark 版本，目前只是亮色主题的风格切换，可以基于 antd 主题自行尝试配置，做的好了甚至可以 PR 给 pro。

另外 https://ng.ant.design/ 那边搞过一个暗色系主题配置，看了效果不错，也可以去催他们开源出来。
