### ISSUE TITLE
登录页面的输入框中的内容死活去不掉

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#1716]
这个内容是在哪设置的？
全局搜了也没找到在哪设置

**Comment by chenshuai2144** [comment]
截图！

**Comment by codepandy** [comment]
<img width="367" alt="_20180622133424" src="https://user-images.githubusercontent.com/16410281/41759434-20af2a34-7621-11e8-9def-cd061d066f0d.png">

**Comment by chenshuai2144** [comment]
你要删掉什么？

**Comment by codepandy** [comment]
输入框中的admin和密码框中的内容

**Comment by chenshuai2144** [comment]
直接删除就好了。
https://preview.pro.ant.design/?redirect=%2Fdashboard%2Fanalysis#/user/login
如果是 
![image](https://user-images.githubusercontent.com/8186664/41759533-9d429f4a-7621-11e8-8ff4-dbd902efd279.png)
去了解一下https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by codepandy** [comment]
不是placeholder，placeholder的内容我已经改了，并且是对是，上面的显示的是value

**Comment by WuJiY** [comment]
那是浏览器 记住了

**Comment by afc163** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
https://gist.github.com/runspired/b9fdf1fa74fc9fb4554418dea35718fe

**Comment by a810950448** [comment]
placeholder ='' 试试

**Comment by codepandy** [comment]
就是浏览器的缓存引起的，不好意思
