### ISSUE TITLE
IE下面打开时空白

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#1719]
在IE下面打包为空白。项目地址 ：http://system.xyzy.online/system/login/index 。。

**Comment by chenshuai2144** [comment]
ie 多少？

**Comment by xgj1988** [comment]
11.65.16299.0 
关键是我打开你们的 的网站是可以用IE看的。。但是我自己的就不行。。

**Comment by xgj1988** [comment]
@chenshuai2144  可以解决吗？

**Comment by chenshuai2144** [comment]
看样子是你的打包配置有问题。
你修改过脚手架？

**Comment by xgj1988** [comment]
{
  "entry": "src/index.js",
  "commons": [
      {
         "name": "app",
         "async": true,
         "children": true,
         "minChunks":3
      }
   ],
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    }
  },
  "proxy": {
      "/api": {
          "target": "http://localhost:8080/",
          "pathRewrite": {"^/api" : ""},
          "changeOrigin": true
      }
  },
  //生产环境删除
  "devtool":"eval-source-map",
  "ignoreMomentLocale": true,
  "theme": "./src/theme.js",
  "html": {
    "template": "./src/index.ejs"
  },
  "publicPath": "/",
  "disableDynamicImport": false,
  "hash": true
}

**Comment by xgj1988** [comment]
@chenshuai2144  帅哥，这是配置文件 ，，我都不敢动你们这里面的东西。。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/41901862-96c49a1a-7964-11e8-9810-7fc90aeba9bb.png)

react 的版本也没有打包对

**Comment by KellyWuz** [comment]
我好像也遇到这个问题，要怎么解决？

**Comment by xgj1988** [comment]
@chenshuai2144 大哥  怎么处理嘛、关键是。

**Comment by chenshuai2144** [comment]
把你魔改掉的东西回滚一下，官网是没有这个问题的。

**Comment by xgj1988** [comment]
@chenshuai2144  魔。。哪个魔。。大哥

**Comment by chenshuai2144** [comment]
不可能帮你写代码的。
你排查一下吧，提示很明显的

**Comment by xgj1988** [comment]
@KellyWuz  你的搞定没？？

**Comment by xgj1988** [comment]
@chenshuai2144  大哥。我直接把你github 的代码拉下来运行 都不行。。看一下嘛。

**Comment by KellyWuz** [comment]
@xgj1988 还没有，我的也是没有任何更改，直接不行

**Comment by xgj1988** [comment]
@KellyWuz  加个QQ 30756500 你有结果，或者我有结果，互相讲一下。

**Comment by KellyWuz** [comment]
@xgj1988 好，#1748这里也提出了一样的问题

**Comment by xgj1988** [comment]
@chenshuai2144  大哥，你把你坐标给我们嘛。，我和 @KellyWuz  商量好了， 我们来找你，请你吃饭。
