### ISSUE TITLE
pro里的组件不能与antd 2.x 搭配用？

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design-pro#172]
用了 charts
Module not found: Error: Can't resolve 'antd/lib/divider/style/css' in 'E:\workspace\vc_code\git\wx_platform\node_modules\_ant-design-pro@0.2.3-rc.0@ant-design-pro\lib\Charts\Pie'

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq#%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Ant-Design-Pro%EF%BC%9F
