### ISSUE TITLE
and design build 出来的一个js 2.3MB？

### ISSUE THREAD

**Issue by woradmen** [ant-design/ant-design-pro#1724]
and design build 出来的一个js 2.3MB，vue-cli 也是根据不同js 去编译的， 你们这demo...

**Comment by afc163** [comment]
Gzipped 后是 700K

**Comment by woradmen** [comment]
不可以根据不同的js去编译吗？

**Comment by chenshuai2144** [comment]
按需加载是可以的

**Comment by woradmen** [comment]
怎么去配置的，有这方面的说明 吗？

**Comment by chenshuai2144** [comment]
antd官网了解一下

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD
