### ISSUE TITLE
请教一下ant-design-pro是不是要转umi了？

### ISSUE THREAD

**Issue by AnInputForce** [ant-design/ant-design-pro#1726]
我在umi文档中看到：

> antd-pro 官方版本计划在 2.0 之后切换到 umi，还需等待一些时间

此项目我看Latest release已经在2018.5.6放出2.0.0-beta.1。
请教下大神，如果项目选型，基于ant-design-pro到时候方便切换到umi么？

**Comment by AnInputForce** [comment]
谢谢大神回复。能否得出这个结论：
AntDesign pro2.0 release后不再维护或者说功能不再增加了？
须或建议尽快迁移至Umi？

**Comment by liumin1128** [comment]
OMG，不是吧又要折腾

**Comment by kaoding** [comment]
一直没有发pro2.0就是为了迁移到umi上吗？

**Comment by chenshuai2144** [comment]
2.0h有很多问题和功能没有实现

**Comment by kaoding** [comment]
功能性除了换umi和完善文档，好像没有别的功能吧。其它就是修复问题了。

**Comment by 533001** [comment]
换 umi是好事.赞!!
大约多久可以迁移到 umi呢.
现在的测试的时候每次改动,加载时间实在是太长了.

**Comment by dengfuping** [comment]
@DrakeXiang 2.0 正式版会转 umi，现在 2.0 还是 beta 版。

**Comment by DrakeXiang** [comment]
@dengfuping  谢谢，那我如何建1.x的项目呢，现在我们项目马上就要开动了，从pro的git上下来的是2.0beta的

**Comment by chenshuai2144** [comment]
项目内容还是1.0的，，

版本号上去了，果然不应该搞版本号，我修一下

**Comment by AnInputForce** [comment]
请教大神，我在 @xiaohuoni 的xiaohuoni/umi-antd-pro项目， realse中看到：

> 由于官方Antd-Pro已经在更新umi版本，所以这个项目后续可能不会再更新
> @xiaohuoni xiaohuoni released this 5 days ago
> 
> Assets
>  Source code (zip)
>  Source code (tar.gz)
> 这个项目，最开始是因为群里很多朋友问：antd-pro有没有umi版本的。
> 所以我拷贝了antd-pro然后整理了一下umi版本的，并在我们公司的一个项目中实践，可用。
> 才有了这个项目。
> 现在antd-pro官方已经再着手umi版本的开发
> 预计在下周发布umi版本的。
> 所以这个项目后续可能不再更新
> 欢迎大家给我提一些不通用非大众的需求
> 可以在这个项目中实现
> 
> 另：多多关注Umi，这是一个很有趣的框架哦


是不是下周就要放出来 AntDesign Pro的UMI版本？

**Comment by xiaohuoni** [comment]
@AnInputForce 我说的是官方有了，就不维护了。具体发布时间，还是要看antd项目组内部的情况而定的。大家都在推进这个事情，相信很快就会发布的

**Comment by AnInputForce** [comment]
@xiaohuoni 抱歉，是我理解错了。
多谢各位大神的推进！

**Comment by dengnan123** [comment]
期待官方的umi-antd-pro
