### ISSUE TITLE
使用 BrowserHistory ，退出后再登录，没法重定向到之前的页面

### ISSUE THREAD

**Issue by sam-dingkang** [ant-design/ant-design-pro#1728]
目前pro是使用的HashHistory,退出再登录会重定向的到之前的页面，如果改成使用BrowserHistory，退出后在登录怎么能重定向到之前的页面？
routerRedux.push('/user/login')在使用BrowserHistory时没带上redirect

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/41842656-fc7b54ce-789d-11e8-829c-29cc0d933a3d.png)
主要逻辑在这里

**Comment by sam-dingkang** [comment]
![image](https://user-images.githubusercontent.com/15643321/41849712-78427356-78b4-11e8-9e3c-c35fcaa878e0.png)
用BrowserHistory时history.replaceStat设置redirect没法成功，所以getBashRedirect()就获取不到redirect；用hashHistory就可以，具体原因还没查清楚

**Comment by chenshuai2144** [comment]
fixed
