### ISSUE TITLE
模块动态加载分布表单页面显示问题

### ISSUE THREAD

**Issue by yuanjiahui** [ant-design/ant-design-pro#173]
![20171114133735](https://user-images.githubusercontent.com/5235098/32764611-7d8da394-c941-11e7-811a-f3c0a2c3bf91.png)

win10、Chrome62

**Comment by afc163** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/507615/32781511-428f4fce-c980-11e7-8d10-13290c545f7d.png">

未能重现。
