### ISSUE TITLE
本地第一次热加载能成功，刷新一次就报错

### ISSUE THREAD

**Issue by xchengguang** [ant-design/ant-design-pro#1733]
不知道哪一步出了错，每次第一次热加载之后就成功，再刷新网页就会报错，要把假数据的相关代码替换后加载再替换成调用真实数据的代码再热加载又会成功一次，部署好之后访问网址直接会失败
![1a1f2448d19c2e92b7bbf133b1e5cdd](https://user-images.githubusercontent.com/27409719/41892022-40b52ea2-7949-11e8-84bd-55aebd58a604.png)

**Comment by chenshuai2144** [comment]
竟然是 ie 试试用 google 调试一下
看你的报错应该是数据为空

**Comment by xchengguang** [comment]
用chrome的也试过，数据的确是为空，但是第一次加载是有数据的，再刷新一次就没有了。链路感觉没有问题啊。。。
![image](https://user-images.githubusercontent.com/27409719/41898432-995a0d6c-795c-11e8-8050-84351ae3834a.png)
![image](https://user-images.githubusercontent.com/27409719/41898454-a9470e3c-795c-11e8-8774-253f026efb96.png)
![image](https://user-images.githubusercontent.com/27409719/41898482-bd41279c-795c-11e8-9a04-ca06e7d20657.png)

**Comment by chenshuai2144** [comment]
估计是低级错误用 network和 debug 排查一下
