### ISSUE TITLE
v2高级表单的成员管理无法新增和编辑

### ISSUE THREAD

**Issue by wangyun122** [ant-design/ant-design-pro#1740]
[高级表单](https://beta.preview.pro.ant.design/#/form/advanced-form)下面成员管理的table，新增时无法输入，编辑点击也无效。

**Comment by mgss** [comment]
@chenshuai2144  刚用v2的时候同样发现了这个问题，表单无法输入，编辑按钮也无效，master分支的好像也有问题，点击添加按钮出来新的一条，输入数据然后点击添加按钮，按钮变成了保存，但是输入框还在，而且点击取消按钮无反应
