### ISSUE TITLE
upload组件上传不了图片

### ISSUE THREAD

**Issue by Moonphy** [ant-design/ant-design-pro#1745]
一直报POST http://localhost:8000/ 404 (Not Found)这个错误，action我试过设置不同的URL都是报这个错误，在proxy设置指向也不行。。。
------WebKitFormBoundaryw5BLgWpIVBGTLuAw
Content-Disposition: form-data; name="shopImage"; filename="logo.png"
Content-Type: image/png
------WebKitFormBoundaryw5BLgWpIVBGTLuAw--

**Comment by chenshuai2144** [comment]
PostMan 先试试？

**Comment by Moonphy** [comment]
![image](https://user-images.githubusercontent.com/10614892/42022046-c72782e0-7aee-11e8-80fc-0e46fa562b77.png)
为什么action里填的/api/v1/uploadFild并没有带过去。。。接口是没问题的

**Comment by Moonphy** [comment]
搞定了搞定了，非常感谢哈！祝生活愉快 @chenshuai2144

**Comment by Aresona** [comment]
加上 method="get"方式解决
