### ISSUE TITLE
How to dynamic create Col Component

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#1746]
I want to dynamic create Col Component by the props parameter and set the className of the Col. I've tried to joint the String but it doesn't work. Or could anybody tell me how to set the props of the Col that I can use to compare with the props I passed so that I can set the assigned Col's class.

Expected Result: 
    the Col lessthan the num of props would be set the special class and the Col  more than the num of props would not be set the special class.

Maybe I asked the wrong place but help the poor white boy, Please!
Thanks!

**Comment by m26597** [comment]
Besides:
   The Col I want to change class is different from others. Is there any method that I can filter the Col through any props I can added to the Col?

**Comment by chenshuai2144** [comment]
You can go to [antd](https://github.com/ant-design/ant-design/issues) to ask questions.
My suggestion, you can use the flex layout directly
