### ISSUE TITLE
Master 版本 IE11 安装依赖 0修改 start 报错

### ISSUE THREAD

**Issue by sealvrain** [ant-design/ant-design-pro#1748]
步骤如下，git拉取代码，安装依赖，start，就会出现这个问题，请帮忙看一下，我也遇到了同样的问题。 怀疑需要配置“babel-polyfill”，不太确定，请官方帮忙解决一下。
--
![default](https://user-images.githubusercontent.com/15939094/42019345-7e38e8aa-7ae7-11e8-9399-609ee619a9ec.png)
![default](https://user-images.githubusercontent.com/15939094/42019352-8352204a-7ae7-11e8-9896-9b182a044551.png)

=============================================================
问题更新，build的静态文件却可以运行，start 起的会报如上错误。

**Comment by xgj1988** [comment]
我和你一样的问题。

**Comment by chenshuai2144** [comment]
先去看看报错是什么？ 
给了个 url

**Comment by sealvrain** [comment]
需要local的 还是外网访问的？
