### ISSUE TITLE
is it possible complex parameter routing?

### ISSUE THREAD

**Issue by LeeGeonho** [ant-design/ant-design-pro#1749]
I need complex parameter routing.
eg. /app/**:projectid**/message/push/edit/**:id**

I saw below code and read the doc. but i don't understand how to use.

https://github.com/ant-design/ant-design-pro/blob/e7b603e88281f46c3523da85e1e481bc1926fb55/src/common/router.js#L193

please, help me
Thanks.

**Comment by chenshuai2144** [comment]
What problem did you encounter?
