### ISSUE TITLE
如何在VS code上debug问题

### ISSUE THREAD

**Issue by tao31** [ant-design/ant-design-pro#175]
launch.json应该如何配置
![tim 20171114144049](https://user-images.githubusercontent.com/9251048/32766426-dfe4051c-c949-11e7-82c5-197a0e758d37.png)
![tim 20171114144130](https://user-images.githubusercontent.com/9251048/32766449-edcb9a32-c949-11e7-847d-31fd4446f201.png)

**Comment by afc163** [comment]
不了解 vs-code。
