### ISSUE TITLE
打包导致color.less 引用失败

### ISSUE THREAD

**Issue by jdongdong** [ant-design/ant-design-pro#1754]
配置了publicPath为/ad/，但是生成的index.html中color.less地址不对
![image](https://user-images.githubusercontent.com/11850305/42077122-6b9935e2-7baa-11e8-97f4-900f2bf93c9d.png)
![image](https://user-images.githubusercontent.com/11850305/42077241-cef67352-7baa-11e8-9978-621898292a44.png)

**Comment by wangyun122** [comment]
真巧。我刚想提这个issues就看到了这个。
在`antd-theme-webpack-plugin`的[index.js](https://github.com/mzohaibqc/antd-theme-webpack-plugin/blob/ad03a9e0ece608480feb55c9382e168cbf988eb9/index.js#L25)写的是
``` html
 <link rel="stylesheet/less" type="text/css" href="/color.less" />
```
不知道有没有什么好的解决方法。

**Comment by chenshuai2144** [comment]
这个插件现在不支持配置。我去作者那里搞个 pr

**Comment by jdongdong** [comment]
ths，等待更新....

**Comment by chenshuai2144** [comment]
https://github.com/mzohaibqc/antd-theme-webpack-plugin/pull/7

**Comment by jdongdong** [comment]
fixed

**Comment by BuDongDong** [comment]
我升级到1.2.0还是没有添加publicPath,这是什么问题

**Comment by BuDongDong** [comment]
> 升级

我已经把antd-theme-webpack-plugin升级到1.2.0了，需要升级到哪个版本呀

**Comment by BuDongDong** [comment]
> [mzohaibqc/antd-theme-webpack-plugin#7](https://github.com/mzohaibqc/antd-theme-webpack-plugin/pull/7)

我已经把antd-theme-webpack-plugin升级到1.2.0了，publicPath还是没有添加
