### ISSUE TITLE
在手机端打开页面页面布局混乱的问题

### ISSUE THREAD

**Issue by ceu** [ant-design/ant-design-pro#1755]
列表页-》标准列表  和 详情页-》基础详情页，在手机端打开，页面布局混乱！
![img_3565](https://user-images.githubusercontent.com/13114273/42087595-39c365be-7bc9-11e8-874c-fd419986aa3a.PNG)
![img_3564](https://user-images.githubusercontent.com/13114273/42087603-3d9a47ca-7bc9-11e8-9c99-877f75cc9c38.PNG)

**Comment by chenshuai2144** [comment]
这个页面没有优化，所以比较混乱，表格不是很好解决优化问题

**Comment by ybning** [comment]
表格混乱的优化，可以参考antd-admin

**Comment by chenshuai2144** [comment]
欢迎 pr！

**Comment by lifanhaha** [comment]
嗯嗯，，好的，，，谢谢你的指点! @ybning

**Comment by lifanhaha** [comment]
antd-admin 的滑动解决方案不是我们想要的，请问官方有自适应手机端显示的解决方案吗？ @chenshuai2144

**Comment by chenshuai2144** [comment]
手机端不适合用 table 的，尤其是比较长的

**Comment by yoyo837** [comment]
antd table 的 scroll 了解一下

**Comment by lifanhaha** [comment]
好的，，谢谢  @yoyo837

**Comment by ybning** [comment]
手机端，用纵向列表展示比用table展示更好
@lifanhaha

**Comment by afc163** [comment]
业务上可以加上这段代码：https://github.com/ant-design/ant-design/commit/bd9fba9f456e3be7a9e367f62a0e35abdc1bfe1f

由于某些原因回滚了：https://github.com/ant-design/ant-design/commit/dd3f7f2da139bc7def137d6962f70e9d02785559

**Comment by chenshuai2144** [comment]
已经稍微处理了一下

**Comment by vaynevayne** [comment]
@afc163  请问在如今 antd5.x 里, 移动端兼容的方案是什么? 依然增加这段代码吗?
