### ISSUE TITLE
向服务器post,服务器接受不到post数据

### ISSUE THREAD

**Issue by songming43** [ant-design/ant-design-pro#1756]
1. 修改了.roadhogrc.mock.js最后一行代码如下:
`export default {
  'GET /(.*)': 'http://web.meiliancheng.com/',
  'POST /(.*)': 'http://web.meiliancheng.com/',
};`

2. get请求方式没问题，但是post请求，后台http状态码为200，但是接受不到数据？

这是为什么？该怎么配置？

**Comment by chenshuai2144** [comment]
我们默认是使用 json 传输请确保的你的后台支持
