### ISSUE TITLE
版本1.1.0 到 2.0.0-beta.1 使用externals 启动找不到包，打开页面报错。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#1757]
系统:windows 10 64 bit 专业版
node：10.5.0
npm : 6.1.0

我以前的版本是1.1.0.现在把我的package里面的roadhog 和webpack.json（现在是webpackrc.js）的数据都改成了新版本的了。。现在我启动，控制台不报错，但是打开界面。出现如下错误：

ReferenceError: rollbar is not defined
(anonymous function)
E:/workspace/gitlab_repo/manager-xyzy-antd/external "rollbar":1
> 1 | module.exports = rollbar;
  2 | 
  3 | 
  4 | //////////////////
View compiled
__webpack_require__
internal:/webpack/bootstrap ed9ec8d8256fb58c1ddd:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
internal:/webpack/bootstrap ed9ec8d8256fb58c1ddd:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
module.exports
E:/workspace/gitlab_repo/manager-xyzy-antd/src/rollbar.js:1
> 1 | import Rollbar from 'rollbar';
  2 | 
  3 | // Track error by rollbar.com
  4 | if (location.host === 'preview.pro.ant.design') {....

但是删除
 externals: {
    '@antv/data-set': 'DataSet',
    bizcharts: 'BizCharts',
    rollbar: 'rollbar',
  },
则正常。

**Comment by afc163** [comment]
You should provide a reproducible repo or nothing we can help.

**Comment by chenshuai2144** [comment]
认真看一下 index.ejs, Externals是需要配套使用的

**Comment by xgj1988** [comment]
@afc163  你好。我在包里面用了pinyin库。。但是如何转换呢？？出现一下报错。 我估计是要让bebel 转换pinyin库。但是由于antd pro 用的是roadog,roadhog用的又是af-webpack。我不知道哪里配置bebel了。。文档也没介绍的。

Failed to minify the bundle. Error: index.f08593f9.js from UglifyJs
Unexpected token name «i», expected punc «;» [index.f08593f9.js:85415,11]

**Comment by xgj1988** [comment]
@chenshuai2144  以后的版本升级后，能否给你一个升级的文档，这样我们也好看哪里是需要修改的。

**Comment by chenshuai2144** [comment]
这个版本还没发布

**Comment by xgj1988** [comment]
@chenshuai2144  哦。大哥，在IE下面空白的那个问题，真的可以看一下。 。我们都是直接 clone下来运行，用IE打开就不行了。。IE11。很多人都遇到了这个问题，
