### ISSUE TITLE
项目在ie10下报错，但ie11是正常的

### ISSUE THREAD

**Issue by Moonlightwsn** [ant-design/ant-design-pro#1758]
报错如图：
![ant design pro ie10](https://user-images.githubusercontent.com/19282267/42134439-902dc3f8-7d6e-11e8-84cb-bace9bc06fa3.PNG)

这是我哪里的使用方式不对么？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1748
同类型问题

**Comment by sealvrain** [comment]
![image](https://user-images.githubusercontent.com/15939094/42143218-9fa0ea68-7de6-11e8-9930-e81f8ea8e20d.png)

**Comment by sealvrain** [comment]
开启开发者模式会显示如下
![image](https://user-images.githubusercontent.com/15939094/42143259-cdcd9f62-7de6-11e8-9d48-7dbcd498b8b4.png)
@chenshuai2144

**Comment by sealvrain** [comment]
在其他的机器上也测试过，存在此问题，是否我的环境存在问题？

**Comment by Moonlightwsn** [comment]
@sealvrain 这位同学，我昨晚尝试重新npm install ant-design-pro-cli -g，并且pro new一个新的项目（version:2.0.0-beta.1），然后对比自己的项目中的package.json，把相关的依赖和业务代码更新了一下，build出来后，在ie11和ie10都可以运行了，但ie10中，有的页面可以打开，有的页面就会报错，所以我怀疑自己的业务代码有问题，有待排查。
