### ISSUE TITLE
How to fetch data in the routes page

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#1759]
In a method function I want to fetch data from server through request url and to use the result in the method. I've tried to save the result into state but it seems that I can't get the result from this.state or this.props in the function. And it seems that I either couldn't directly to use the service's function in the routes page. How could I do to resolve this? Could I return a reuslt in dispatch and receive that in the place where I dispatch?

**Comment by chenshuai2144** [comment]
show code

**Comment by m26597** [comment]
the  function of getting data
```
getData = (id) => {
    const { dispatch } = this.props;
    const payload = { id};
    //get data and could save  data into state
     dispatch({
      type: 'moduleData/getData',
      payload: { ...payload },
    });
    //couldn't get data
     const data = this.state.data;
  }
```

**Comment by m26597** [comment]
I've found the problem that I pointed a wrong route, now the problem has solved. Thank you
