### ISSUE TITLE
更新之后报错

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#1760]

**Comment by drduan** [comment]
![2018-07-02_153954](https://user-images.githubusercontent.com/7875572/42151038-39861f1e-7e0e-11e8-8c62-3558b7367af3.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/42152846-f8296656-7e13-11e8-8a69-cc6f33b59183.png)

matser moment 版本
