### ISSUE TITLE
 dynamicWrapper方法中判断require还是import

### ISSUE THREAD

**Issue by zhengchangshun** [ant-design/ant-design-pro#1761]
根据代码中的注释，通过if (component.toString().indexOf('.then(') < 0)判断是require引入文件还是import引入文件。这个判断的意思应该是 动态加载component的方法是都含有Promise的then方法。但实际上routerConfig中所有的路由component动态加载都是不含带then方法的。
该判断条件是否有误？望解答。

**Comment by chenshuai2144** [comment]
看编译出来的代码

**Comment by zhengchangshun** [comment]
dynamicWrapper 的定义如下：
```

const dynamicWrapper = (app, models, component) => {
  // () => require('module')
  // transformed by babel-plugin-dynamic-import-node-sync
  if (component.toString().indexOf('.then(') < 0) {
    models.forEach(model => {
      if (modelNotExisted(app, model)) {
        // eslint-disable-next-line
        app.model(require(`../models/${model}`).default);
      }
    });

    return props => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return createElement(component().default, {
        ...props,
        routerData: routerDataCache,
      });
    };
  }
  // () => import('module')
  return dynamic({
    app,
    models: () =>
      models.filter(model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return component().then(raw => {
        const Component = raw.default || raw;
        return props =>
          createElement(Component, {
            ...props,
            routerData: routerDataCache,
          });
      });
    },
  });
};
```


引用的地方代码如下：

`component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),`


在实际的运行过程中，并没有实现按需加载，所有的model都在路由生成时注册啦。已下例为证明：稍微修改了一下BasicLayout的connect方法

```
function mapStateToProps(state) {
  console.log(state);
  const {user, global, loading} = state
  return {
    currentUser: user.currentUser,
    collapsed: global.collapsed,
    fetchingNotices: loading.effects['global/fetchNotices'],
    notices: global.notices,
  }
}

export default connect(mapStateToProps)(BasicLayout);

```
此时console.log输出的所有model。如果按需加载的话，此时state中的model，应该只包含BasicLayout依赖的model--- ['user', 'login']。如图所示：
![111](https://user-images.githubusercontent.com/19727234/42441243-62784dfc-839a-11e8-9965-15769b7b7df5.png)


因此建议dynamicWrapper方法修改如下：
const dynamicWrapper = (app, models, component) => {
  return dynamic({
    app,
    models: () =>
      models.filter(model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return props =>
        createElement(component().default, {
          ...props,
          routerData: routerDataCache,
        });
    },
  });
};

**Comment by Panamer** [comment]
想知道改了没

**Comment by fancyluo88** [comment]
这样是动态

> dynamicWrapper 的定义如下：
> 
> ```
> 
> const dynamicWrapper = (app, models, component) => {
>   // () => require('module')
>   // transformed by babel-plugin-dynamic-import-node-sync
>   if (component.toString().indexOf('.then(') < 0) {
>     models.forEach(model => {
>       if (modelNotExisted(app, model)) {
>         // eslint-disable-next-line
>         app.model(require(`../models/${model}`).default);
>       }
>     });
> 
>     return props => {
>       if (!routerDataCache) {
>         routerDataCache = getRouterData(app);
>       }
>       return createElement(component().default, {
>         ...props,
>         routerData: routerDataCache,
>       });
>     };
>   }
>   // () => import('module')
>   return dynamic({
>     app,
>     models: () =>
>       models.filter(model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)),
>     // add routerData prop
>     component: () => {
>       if (!routerDataCache) {
>         routerDataCache = getRouterData(app);
>       }
>       return component().then(raw => {
>         const Component = raw.default || raw;
>         return props =>
>           createElement(Component, {
>             ...props,
>             routerData: routerDataCache,
>           });
>       });
>     },
>   });
> };
> ```
> 引用的地方代码如下：
> 
> `component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),`
> 
> 在实际的运行过程中，并没有实现按需加载，所有的model都在路由生成时注册啦。已下例为证明：稍微修改了一下BasicLayout的connect方法
> 
> ```
> function mapStateToProps(state) {
>   console.log(state);
>   const {user, global, loading} = state
>   return {
>     currentUser: user.currentUser,
>     collapsed: global.collapsed,
>     fetchingNotices: loading.effects['global/fetchNotices'],
>     notices: global.notices,
>   }
> }
> 
> export default connect(mapStateToProps)(BasicLayout);
> ```
> 此时console.log输出的所有model。如果按需加载的话，此时state中的model，应该只包含BasicLayout依赖的model--- ['user', 'login']。如图所示：
> ![111](https://user-images.githubusercontent.com/19727234/42441243-62784dfc-839a-11e8-9965-15769b7b7df5.png)
> 
> 因此建议dynamicWrapper方法修改如下：
> 
> ```
> const dynamicWrapper = (app, models, component) => {
>   return dynamic({
>     app,
>     models: () =>
>       models.filter(model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)),
>     // add routerData prop
>     component: () => {
>       if (!routerDataCache) {
>         routerDataCache = getRouterData(app);
>       }
>       return props =>
>         createElement(component().default, {
>           ...props,
>           routerData: routerDataCache,
>         });
>     },
>   });
> };
> ```
> 修改的model加载如下:
> 
> ![222](https://user-images.githubusercontent.com/19727234/42441718-70cc79ae-839b-11e8-8a4f-685e3c3db983.png)

这样是动态注册model了 但是没有离开那个路由的时候 动态注销model吧
