### ISSUE TITLE
Ask: Parameter routing in side menu does not replace/substitute the parameters in the path

### ISSUE THREAD

**Issue by kristiankyvik** [ant-design/ant-design-pro#1763]
Hi, 

I am having troubles using the side menu to access routes with parameters. When I click on the menu in order to access the profile, I am redirected to the route: '/patients/:patient_id/profile', and the parameter not being substituted. My question is how and where I need to tell the menu to substitute the path parameter variable :patient_id with the actual value of the the patient_id so that I get redirected to for example  '/patients/123214/profile', instead.

menu.js
```
  {
    name: 'Paciente',
    icon: 'team',
    path: 'patients',
    children: [
      {
        name: 'Perfil',
        icon: 'user',
        path: ':patient_id/profile',
      },
      {
        name: 'Pims',
        icon: 'fork',
        path: ':patient_id/pims',
        children: [],
      },
    ],
  },
```

router.js
```
 '/patients/:patient_id/profile': {
    component: dynamicWrapper(app, ['patient'], () => import('../routes/Patient/Profile')),
  },
 '/patients/:patient_id/pims': {
      component: dynamicWrapper(app, ['user', 'pim', 'patient'], () =>
        import('../routes/Patient/CreatePim')
      ),
    },
```

Any help guidance will be appreciated. I have read though all the existing issues and docs without finding the solution.

**Comment by chenshuai2144** [comment]
It is not recommended to use routing parameters in the menu.
Parameter routing is not suitable for navigation, more suitable for page use.
you can user `  path: '1234/profile',`

**Comment by kristiankyvik** [comment]
hi @chenshuai2144, thanks for your response. I understand. In that case, how can I dynamically change the balue of this path, depending on the id of user that is currently logged in!?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/6984ac0503746613e2936d39509b989040f673f7/src/components/SiderMenu/SiderMenu.js#L88

look here

**Comment by kristiankyvik** [comment]
thanks, I will look into it.

**Comment by kristiankyvik** [comment]
Hi again @chenshuai2144, that worked like a charm! Thanks again for your suggestion!
