### ISSUE TITLE
同行输入框大小设置成默认，导致同行输入框错位。

### ISSUE THREAD

**Issue by YanXiaoChen** [ant-design/ant-design-pro#1766]
![image](https://user-images.githubusercontent.com/23149320/42175326-9ea63228-7e57-11e8-82c2-62b0c89053d5.png)
如图所示，注册页面，同行输入框去掉size="large" 导致同行输入框错位。

**Comment by chenshuai2144** [comment]
给个复现地址？

**Comment by afc163** [comment]
诶？..
