### ISSUE TITLE
使用Sider时出现在柱形图Bar显示问题

### ISSUE THREAD

**Issue by jolinlizhihua** [ant-design/ant-design-pro#1768]
使用Layout中Sider时，当Sider收起时Bar柱形图组件的宽度没有变大（Bar组件的外层包含有一个Card组件），请问是为什么。图1为
![2](https://user-images.githubusercontent.com/30651709/42195384-326c7e42-7eab-11e8-867e-828b8ba46d4d.PNG)
原始状态，图2 为Sider收起时的状态
![1](https://user-images.githubusercontent.com/30651709/42195346-0524a496-7eab-11e8-9da5-2e3d17345dea.PNG)

**Comment by chenshuai2144** [comment]
因为Sider监听的是window 宽度变化，你可以重新渲染一下

**Comment by jolinlizhihua** [comment]
每次打开和关闭图形的state都没有变化呢，您的意思是 每次打开、关闭sider的时候重新去fetch一下图形的数据吗

**Comment by chenshuai2144** [comment]
你可以把宽和高做成 state

**Comment by jolinlizhihua** [comment]
我将Layout和content的宽 设置成state 样式已经生效 可以还是不行

**Comment by chenshuai2144** [comment]
你得控制 render,看看 chartCard

**Comment by jolinlizhihua** [comment]
我开始在图表外面用的Card现在改用成ChartCard还是不行，具体要控制什么属性和状态呢？

**Comment by chenshuai2144** [comment]
监听宽度变化重新渲染

你被什么卡住了？

**Comment by jolinlizhihua** [comment]
你的意思是监听Card的宽度变化然后渲染组件？但是我的柱形图用的是Bar，它的高度我设定了，宽度由于使用了forceFit所以无法设置，没有什么状态的变化组件也无法重新渲染啊

**Comment by jolinlizhihua** [comment]
解决了我在Bar\index.js中添加了
componentWillUnmount() {
    window.removeEventListener('resize', this.resize);
 }
就好了

**Comment by jolinlizhihua** [comment]
问题解决了，我在Bar\index.js文件中加入了如下代码：
componentDidUpdate() {
    window.dispatchEvent(new Event('resize'));
  }
