### ISSUE TITLE
关于路由按需加载的问题

### ISSUE THREAD

**Issue by EthanWan** [ant-design/ant-design-pro#1771]
roadhog 中有babel-plugin-dynamic-import-node-sync 插件，将()=>import('model') 转化成了()=>required('model') 是不是这样就没有去进行按需加载路由组件，并且npm run build 没有生成额外的chunk。 这是一个bug吗？

**Comment by chenshuai2144** [comment]
这是个 feature

**Comment by EthanWan** [comment]
@chenshuai2144  能请问下在哪里配置吗  看了下文档没发现 : (

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD

**Comment by EthanWan** [comment]
@chenshuai2144 谢谢🙏

**Comment by EthanWan** [comment]
@chenshuai2144 再请教一下 加入配置项 是因为开启动态路由严重导致了webpack的打包速度减慢吗？包括开发的时候热加载变慢 如果是这样的话 是不是可以考虑一下配置个环境变量 只有npm run build 的时候才开启按需加载。😄

**Comment by chenshuai2144** [comment]
可以根据环境变量来判断的
