### ISSUE TITLE
Unexpected key "global" found in previous state received by the reducer

### ISSUE THREAD

**Issue by meiyouqing** [ant-design/ant-design-pro#1772]
在生产环境不会出现，刷新也不会出现，只在开发调试中，保存一个文件（modal文件和utils/request)， 经常会报这个错：
`Unexpected key "global" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "routing", "@@dva", "loading", "login", ... Unexpected keys will be ignored.`
好像是combineReducer的问题

**Comment by chenshuai2144** [comment]
加个 if 判断一下 
我记得有个 pr 解决了这个问题。

**Comment by meiyouqing** [comment]
@chenshuai2144 
在哪儿加了？我试过在connect加判断，但又会出现新的问题：BasicLayout会报数据类型错误

**Comment by meiyouqing** [comment]
我看到最新的BasicLayout这里有个小小的更新，应该就是解决这个问题的了：
```
connect(({ global = {}, ...}) => ({...})
```

**Comment by meiyouqing** [comment]
我试着这样改了，还是会报一样的错，不过页面没有collapse，这样就足够：）
