### ISSUE TITLE
用nginx部署在次级域名路径（如a.com/sub/）

### ISSUE THREAD

**Issue by xietongjian** [ant-design/ant-design-pro#1773]
你好，有这样一个需求，需要将项目部署到已有域的次级路径下。配置完build后遇到这样的问题：
![image](https://user-images.githubusercontent.com/16096832/42210761-677b4968-7ee4-11e8-9d15-0b0feb133218.png)
webpackrc.js配置:
```js
publicPath: process.env.NODE_ENV === 'production' ? '/portalui/' : '/',
```
nginx配置：
```nginx
	location /portalui/ {
	    root D:\\workspace\\study\\dist;
	    index index.html index.htm index.shtml;
	    try_files $uri $uri/ /index.html;
	}
```
请问怎么解决？

**Comment by chenshuai2144** [comment]
是因为404了，你确定portalui/***.js 存在？

**Comment by xietongjian** [comment]
run build出来的，全都在一个目录中，难道要手动创建portalui这个目录吗？

**Comment by xietongjian** [comment]
问题解决了，我明白了，确实是这个目录不存在的原因。谢谢提示
