### ISSUE TITLE
Can't use the ztree-for-react component

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#1776]
Hi,

Because the `ant design` tree component can't edit on the treenode, I want to use the `ztree`.

I use the `ztree-for-react` component, the demo can run, but when I import it in ant design pro, there is a error:

```
Element type is invalid: expected a string (for built-in components) or a class/function 
(for composite components) but got: undefined. You likely forgot to export your component
from the file it's defined in, or you might have mixed up default and named imports.
```

the below is my code:
```
import ReactZtree  from 'ztree-for-react';
```

if the `ztree` can be use, how to make the ant design tree can edit on the node?

**Comment by afc163** [comment]
I think it is more like a ztree-for-react's issue.
