### ISSUE TITLE
sider侧边栏256太宽了，请问如果我改下应该在哪里改

### ISSUE THREAD

**Issue by lsdiao** [ant-design/ant-design-pro#178]
`<div class="sider___2u3fw ant-layout-sider" style="flex: 0 0 256px; max-width: 256px; min-width: 256px; width: 256px;">`
此处的代码应该是计算出来的，我想问下这个要改哪个文件里的基础值，还有我改了rc-menu组件下MenuMixin.js 的初始padding-left值
```
  getDefaultProps: function getDefaultProps() {
    return {
      prefixCls: 'rc-menu',
      className: '',
      mode: 'vertical',
      level: 1,
      inlineIndent: 12, //原为24
      visible: true,
      focusable: true,
      style: {}
    };
  },
```
请问我改怎么生效他

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/search?utf8=%E2%9C%93&q=256&type=

Search the code...

**Comment by lsdiao** [comment]
好吧，这么大的字我尽然没注意，请问改了rc-menu组件下MenuMixin.js 的初始padding-left值怎么生效
