### ISSUE TITLE
CORS disabled

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#1780]
Failed to load : Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8003' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by chenshuai2144** [comment]
Using google will get the answer faster
