### ISSUE TITLE
select跟Cascader组件会存第一次选中的值，修改props后本来应该为空的却出现默认值

### ISSUE THREAD

**Issue by Moonphy** [ant-design/ant-design-pro#1786]
![image](https://user-images.githubusercontent.com/10614892/42272125-b82f9e76-7fb7-11e8-82c8-efb99af4106c.png)
开始props传数组三个元素，遍历是正确的（如上图），修改props传数组只有一个空对象，却保留了第一次传过来的第一个元素的值（如下图）（数据是更新的了，数组第一次三个元素，修改后一个元素）
![image](https://user-images.githubusercontent.com/10614892/42272383-85e0d9e8-7fb8-11e8-8357-3adaf216d26f.png)
![image](https://user-images.githubusercontent.com/10614892/42272483-c9e14628-7fb8-11e8-9190-da44e4e313a8.png)
Cascader组件也是，选中值后，后面再传默认值就永远显示第一次进入的值。。跟上面select的情况一样，不知怎么回事

调了一天了，不管是用redux传值还是state然后componentWillReceiveProps都解决不了

**Comment by chenshuai2144** [comment]
求再现地址，而且这个问题是 antd 的吧

**Comment by ybning** [comment]
@Moonphy 
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item

**Comment by Moonphy** [comment]
解决问题了，只是因为defaultValue引起的，改成value什么问题都没了，我的天啊，真没想到一点点的差别就天差地别，非常感谢两位，祝工作顺利生活愉快 @chenshuai2144 @ybning

**Comment by changyuanchn** [comment]
> ，只是因为defaultValue引起的，改成value什么问题都没了，我的天啊，真没想到一点点的差别就天差地别，非常感谢两位，祝工作顺利生活愉快 @chenshuai2144 @ybning

我也是用了defaultValue，坑了一下午
