### ISSUE TITLE
如何修改，能支持在地址栏带上参数？

### ISSUE THREAD

**Issue by liuhaoliang** [ant-design/ant-design-pro#1789]
因为使用react的传参方式，一刷新页面，上个页面传来的参数就没有了。所以我想在地址栏带上参数。
我是这样修改model和router文件的，但是实际应用中找不到这个组件。求指教：

```
  detailPage({ payload }, { call, put }) {
      yield put(routerRedux.push({
        pathname: '/store/point-info?from=1&to=10',
        state: payload
      }));
    },
```

    '/store/point-info': {
      component: dynamicWrapper(app, ['pointInfo'], () => import('../routes/Store/PointInfo')),
    },

**Comment by chenshuai2144** [comment]
学习一个 markdown 吧！

```
 yield put(routerRedux.push({
        pathname: '/store/point-info?from=1&to=10',
       search:"code=123"
      }));
```

**Comment by liuhaoliang** [comment]
谢谢您，完美解决！嘿嘿，我会好好学习markdown的 ：） @chenshuai2144
