### ISSUE TITLE
代码分割后,登录页感觉还是太大了

### ISSUE THREAD

**Issue by shadiniao** [ant-design/ant-design-pro#1794]
![image](https://user-images.githubusercontent.com/14309730/42315462-14cd809a-807a-11e8-9546-2cb570c47b71.png)
这是分割后的代码,index.js依然还是有1m多,之前是2m

进入登录页加载这个js文件时间还是要4.95秒

而且你们的说明文档也太省了,设置分割要改.webpackrc.js文件中的disableDynamicImport: false,提都不提一下,在issue里找半天才知道

**Comment by chenshuai2144** [comment]
请仔细阅读文档！
