### ISSUE TITLE
请求方法为DELETE时，一直返回403

### ISSUE THREAD

**Issue by kongliang94** [ant-design/ant-design-pro#1797]
1、不使用mock，而且用request.js请求，报403: '用户得到授权，但是访问是被禁止的。'
2、使用mock，DELETE请求可能执行
3、直接通过postman测试，后台可以执行DELETE请求。

初次使用pro，请指教下怎么处理？先提前感谢。

**Comment by chenshuai2144** [comment]
图？

**Comment by kongliang94** [comment]
![image](https://user-images.githubusercontent.com/24951997/42367495-06aedcf8-8137-11e8-8ba7-e82afe15d906.png)

**Comment by kongliang94** [comment]
![image](https://user-images.githubusercontent.com/24951997/42367596-567857c8-8137-11e8-9ab4-1e7444914df6.png)

**Comment by kongliang94** [comment]
会不会是我的mock配置的问题？
![image](https://user-images.githubusercontent.com/24951997/42371805-18943484-8143-11e8-8837-b761fa786317.png)

**Comment by kongliang94** [comment]
![image](https://user-images.githubusercontent.com/24951997/42372253-51293636-8144-11e8-9e6f-1163286484c9.png)
这一步还可以，下一步直接403.

**Comment by chenshuai2144** [comment]
给个请求截图呗 你给代码没有用的

**Comment by kongliang94** [comment]
![image](https://user-images.githubusercontent.com/24951997/42373360-4185e5a0-8147-11e8-862d-b6f06e12031c.png)
您说得请求截图，上面有了啊。还是说您需要看postman的请求截图？

**Comment by kongliang94** [comment]
![image](https://user-images.githubusercontent.com/24951997/42373561-d6a4afcc-8147-11e8-9279-9368cf9bf975.png)
您看看这个。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/42373976-0e17b7be-8149-11e8-9307-bbf1781f5bca.png)

**Comment by kongliang94** [comment]
![image](https://user-images.githubusercontent.com/24951997/42374501-e7b2783c-814a-11e8-81bd-26c9fd955581.png)
可能是跨域？？我问问后台设置没。。为啥post可以？

**Comment by kongliang94** [comment]
竟然是后台禁止了跨域delete，抱歉了，占用您的时间，辛苦。
