### ISSUE TITLE
父组件触发render()方法时，子组件会触发componentDidMount() 

### ISSUE THREAD

**Issue by xzk821649509** [ant-design/ant-design-pro#1798]
今天做项目的时候遇到一个很奇葩的问题，当子组件请求数据的时候，触发了父组件的render()方法（因为数据是从父组件传到子组件的），这时候会突然触发了子组件的componentDidMount() 方法，子组件被重新渲染，导致了state被清空。我想问一下这是什么问题？是bug吗？

**Comment by chenshuai2144** [comment]
你把子组件销毁了吗？

**Comment by xzk821649509** [comment]
没有的。我在网上查了一下，说是使用了antd的Tabs组件时会出现，而我也确实是使用了Tabs组件，这是不是bug啊？

**Comment by chenshuai2144** [comment]
Table 好像是会删除一下，去 antd 提个 issue，
你可以使用 TabBar 自己控制组件
