### ISSUE TITLE
不知道算不算响应式的样式问题？

### ISSUE THREAD

**Issue by yihuishou** [ant-design/ant-design-pro#1799]
![qq 20180706161720](https://user-images.githubusercontent.com/26241263/42369476-ab786312-813c-11e8-88d6-009164f1e0a9.png)

**Comment by chenshuai2144** [comment]
算，欢迎 pr

**Comment by chenshuai2144** [comment]
@yoyo837  可以 pr 一个看看效果吗？

**Comment by yoyo837** [comment]
好啊

**Comment by yoyo837** [comment]
@chenshuai2144 预览站挂了，弄一下呗，不new issue了

**Comment by chenshuai2144** [comment]
http://beta.preview.pro.ant.design/ 这个吗？

**Comment by yoyo837** [comment]
https://preview.pro.ant.design/

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/42429670-0156353e-836d-11e8-8c19-ccb0cf75e8ec.png)

```css
[class*='ant-col-'],
.ant-btn,
div.vt-spacing {
  margin-top: 5px;
}
```

这代码你收吗？

**Comment by chenshuai2144** [comment]
可以包一个吗？
做一个组件出来就叫 bar，表现就是 bar 下面的元素都有 margin。
margin 的距离按照 antd 的规范来 都是8好了

**Comment by yoyo837** [comment]
可以的，不过可能晚...

**Comment by yoyo837** [comment]
其实有蛮多地方，比如`ant-pagination-item` ，分页组件，真的要写Bar吗？`antd-design` 是否考虑直接处理？

**Comment by chenshuai2144** [comment]
design 可能不会直接处理，我们可以提供这样一个能力，
叫 toolbar 之类的。
现在表格前面的按钮写起来的却很麻烦。每次都要人肉设置margin

**Comment by yoyo837** [comment]
自行组织排版的使用这个包装组件确实可行，一些antd 组件内部的深层结构的margin 是不是还是得写样式？比如我前面举例的由table 产生的 分页组件。
<img width="283" alt="image" src="https://user-images.githubusercontent.com/6134547/42434591-4d6f5306-8386-11e8-941c-2fb4ef3ea446.png">

**Comment by chenshuai2144** [comment]
这个只要搞成 mini 就可以了

**Comment by yoyo837** [comment]
好主意，就是不知道还有没有类似的场景而“mini”不了的...先加再说也行。
