### ISSUE TITLE
求助~roadhog-api-doc不能正确运行

### ISSUE THREAD

**Issue by kstar11** [ant-design/ant-design-pro#180]
![qq 20171114171049](https://user-images.githubusercontent.com/25189126/32771826-f793fa90-c95e-11e7-9c63-b74ce6d7a044.png)

错误提示如图~已手动安装cross-env

**Comment by nikogu** [comment]
对，这个要在文档里面说明一下，windows 确实需要手动安装 cross-env 的依赖，我稍后补充上去

**Comment by afc163** [comment]
他的问题貌似是手动安装了 cross-env 还是报错。

**Comment by nikogu** [comment]
哦哦，酱紫，我看看

**Comment by afc163** [comment]
另外，cross-env 安装到 devDependencies 里应该就够了，不需要手动安装。

**Comment by nikogu** [comment]
@kstar11 try `0.2.10`
