### ISSUE TITLE
求教关于index.ejs 中引用的问题？

### ISSUE THREAD

**Issue by yihuishou** [ant-design/ant-design-pro#1800]
![qq 20180706173150](https://user-images.githubusercontent.com/26241263/42371593-7e7eb158-8142-11e8-84f7-62159440ff78.png)

我在无联网环境中使用的时候应该替换成什么？

还有这个几个库为什么没有被一起打包呢？

**Comment by chenshuai2144** [comment]
下载下来，相对路径引用，这几个包用的不多，个头却很大， 就用 cdn 了

**Comment by yihuishou** [comment]
问题是中间两个压缩混淆的包不知道是什么…
不明不白的引入不太好吧？
这几个包影响哪些模块呢？可不可去除掉？

**Comment by chenshuai2144** [comment]
一个图表 一个统计

**Comment by yihuishou** [comment]
如果也想打包到一个js文件中的话，我是要改哪个的说？
