### ISSUE TITLE
build 发布到nginx服务器，http post 访问服务器的api报405错误

### ISSUE THREAD

**Issue by weixpb** [ant-design/ant-design-pro#1801]

**Comment by chenshuai2144** [comment]
配置问题

**Comment by zwl2222** [comment]
@cindyZhang4 兄弟，你那个问题解决了吗？

**Comment by chenshuai2144** [comment]
405 表示的是不允许用当前的 method 来访问这个 api，他可能是个 get 方法，或者 你 url 配置错误，造成了跨域，发起了一个 option 请求

**Comment by zwl2222** [comment]
你好，我在本地调试的时候没有问题，他是一个post的方法，参数那些也正确，我就怀疑是我的nginx配置有问题，还有我想咨询一下，后端的api端口一定要求是api/开头的吗？在api的前面加个名称  例如 XXX/api/


我的nginx配置：





------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 下午5:53
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "CoCaCola"<376122531@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] build 发布到nginx服务器，http post 访问服务器的api报405错误 (#1801)




405 表示的是不允许用当前的 method 来访问这个 api，他可能是个 get 方法，或者 你 url 配置错误，造成了跨域，发起了一个 option 请求
