### ISSUE TITLE
这玩意好难用啊！

### ISSUE THREAD

**Issue by guodong** [ant-design/ant-design-pro#1804]
一个简单的登录复杂到要改5个文件，10分钟工作量硬生生变成48小时，登录项用map.js提出来，是打算复用还是咋地？
加个route还要改2个页面，route既然都封装了，为什么遗留如下代码的第三个参数不能兼容字符串或者function？
```
'/': {
      component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    },
```

还有这种丑陋的代码
```
Login.Tab = LoginTab;
Login.Submit = LoginSubmit;
Object.keys(LoginItem).forEach(item => {
  Login[item] = LoginItem[item];
});
```

**Comment by chenshuai2144** [comment]
有兴趣可以提 pr，你可以改变掉这些现状

**Comment by AnInputForce** [comment]
> 如果你不知道为啥要用redux，那就是你不需要redux

同理可证：可能你目前的项目不适合引入antdesign pro

**Comment by guodong** [comment]
好的

**Comment by chenshuai2144** [comment]
pro 更多的是一个样板代码。使用了业内的很多最佳实践。
不可否认的确实有很多脏代码，但是由于维护人员的精力和时间有限，可能任由其存在。
希望可以 社区可 pr 解决掉。让 pro 越来越好

**Comment by afc163** [comment]
我们也不是神，代码是靠社区一起维护才会越来越好。

**Comment by 533001** [comment]
如果不满意,就证明给 1w+的小伙伴儿 看,什么是好代码
