### ISSUE TITLE
请教一下支持跨域数据源SSE通信吗？有人成功过吗？

### ISSUE THREAD

**Issue by lisong66** [ant-design/ant-design-pro#1805]
这样写的话，看起来连接是建立成功了，但是eventstream是空的，没有数据推送过来，请教各位大佬应该怎么写呀？（数据源没问题）
eventSourcetmp = new EventSource('http://172.21.2.40:7001/zuulx/calls', { withCredentials: true });
			  eventSourcetmp.onmessage = message =>{
			  	cnosole.log(message.data);
			  } 
连接成功：
![image](https://user-images.githubusercontent.com/39253372/42408183-05e7be2e-81fb-11e8-9f2d-02d658b3e72d.png)
数据为空：
![image](https://user-images.githubusercontent.com/39253372/42408195-43fc75e2-81fb-11e8-84ac-e86b242c72b8.png)
另一个项目中调用此接口可以正常返回eventstream：
![image](https://user-images.githubusercontent.com/39253372/42408213-9c8acfba-81fb-11e8-829a-1763d36bbb0f.png)

**Comment by chenshuai2144** [comment]
看来没人搞过这个
