### ISSUE TITLE
Fetch 400 之后没有respones data

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#1807]
![image](https://user-images.githubusercontent.com/12181423/42428211-2abec88a-8365-11e8-8ef5-aab4f0da5b61.png)

![image](https://user-images.githubusercontent.com/12181423/42428218-380d7504-8365-11e8-8873-abbaa238b324.png)

**Comment by chenshuai2144** [comment]
400表示服务器觉得你发送的数据是错的。当然不会返回。
是不是 get post 用错了

**Comment by hqwlkj** [comment]
@chenshuai2144   没有，确认过了。

**Comment by hqwlkj** [comment]
@chenshuai2144  后端日志显示我是成功访问了的，并且还返回了数据的。

**Comment by chenshuai2144** [comment]
400 本来就是后端返回的。你应该监听一下后端给返回了什么。
400错误在联调中很常见，一般都是参数格式有误。

**Comment by hqwlkj** [comment]
处理好了，我将request.js 中的处理顺序调整了一下，
![image](https://user-images.githubusercontent.com/12181423/42429116-ee050cec-8369-11e8-8b92-16c54924a261.png)


![image](https://user-images.githubusercontent.com/12181423/42429130-fd0a0b20-8369-11e8-9be9-075b972f1630.png)

将处理放在前面了。

**Comment by wangyun122** [comment]
浏览器的network有respones但是你在代码里log没有？

**Comment by flyyang** [comment]
这个时候应该抓包
