### ISSUE TITLE
关掉mock后访问后台报Failed to fetch的错

### ISSUE THREAD

**Issue by Rocky1073** [ant-design/ant-design-pro#181]
前后端都是本地，前端8000，后端8080
后台服务器跨域都是打开的
前台浏览器network里是有返回的，但就是前端就是一直报Failed to fetch

![3c7d57a3f97006db0559598b57f2918](https://user-images.githubusercontent.com/33660387/32783124-a3a63b7e-c985-11e7-8f3d-bee0abd8d443.png)
![7da3edb0b12bd560a3156190ba73e1c](https://user-images.githubusercontent.com/33660387/32783126-a41c021e-c985-11e7-9944-a9c9b8f03eaa.png)
![1510667284 1](https://user-images.githubusercontent.com/33660387/32814097-7a427a96-c9e8-11e7-89ba-595401e9fe4e.jpg)
![e3d2ed23e7694955c3ca2a390526a76](https://user-images.githubusercontent.com/33660387/32814098-7abec9a2-c9e8-11e7-95ac-8083d4347489.png)
![e86178340e31314b553d77d2bdec49f](https://user-images.githubusercontent.com/33660387/32814099-7b1243ca-c9e8-11e7-9d42-3b07463d05d5.png)

**Comment by nikogu** [comment]
@Rocky1073 你可以先自己调试下 `request.js`

**Comment by Rocky1073** [comment]
@nikogu 调试过，还是一样的错，找不到问题

**Comment by nikogu** [comment]
后面两个图挂了，贴下具体的报错信息

**Comment by Rocky1073** [comment]
@nikogu 抱歉，现在已经好了，你看

**Comment by nikogu** [comment]
@Rocky1073 这个很好调的：https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js#L49

是这里显示的错误信息，你把 error 打出来看一下就知道了应该

**Comment by Rocky1073** [comment]
@nikogu 我试过，但程序是在第一行fetch(url, newOptions)就直接炸掉了，后面的所有代码都没有执行，所以错误信息也打印不出来。

 return fetch(url, newOptions)
    .then(checkStatus)
    .then(response => response.json())
    .catch((error) => {

**Comment by LuoShengMen** [comment]
为什么我执行npm run start:no-proxy会报
![image](https://user-images.githubusercontent.com/21194931/32817156-4b511184-c9f7-11e7-9d79-ecff3bbaee39.png)这个错啊

**Comment by LuoShengMen** [comment]
怎么关闭掉mock,连接我自己的服务呢？？按照官网的来不行啊

**Comment by afc163** [comment]
windows 的环境变量不是这样绑定的。

```
set NO_PROXY=true && roadhog server
```

**Comment by Rocky1073** [comment]
@LuoShengMen 改成set NO_PROXY=true&&roadhog server

**Comment by LuoShengMen** [comment]
嗯，好的，谢谢

**Comment by Rocky1073** [comment]
@afc163 加了&&不去左右空格.roadhong.mock.js取值时会多取一个空格的吧

**Comment by nikogu** [comment]
@Rocky1073 不对呀，看你提示信息，应该走到了 `catch` 里面，所以是可以拿到 `error` 的

**Comment by Rocky1073** [comment]
@nikogu 已解决，去掉include就行了

**Comment by afc163** [comment]
@Rocky1073 LuoShengMen https://github.com/ant-design/ant-design-pro/commit/a67a951496ca9ecdc5c262a18007dcb972d35cba 这样改下应该就好了。

**Comment by afc163** [comment]
@LuoShengMen

另外，建议不要在别人的 issue 下讨论无关问题，很不礼貌。。。

**Comment by LuoShengMen** [comment]
@afc163 好，不好意思，没注意，另外你那个方法好像不行，

**Comment by LuoShengMen** [comment]
@afc163 你那个方法是对的，我看错了

**Comment by LuoShengMen** [comment]
@Rocky1073 你好！请问一下你是怎么将服务替换成自己服务

**Comment by Rocky1073** [comment]
@LuoShengMen 关掉mock后就可以直接写路径访问了

**Comment by LuoShengMen** [comment]
@Rocky1073 
![image](https://user-images.githubusercontent.com/21194931/32818695-c0c6eb66-c9ff-11e7-90a9-cf894136832c.png)是直接这样吗

**Comment by Rocky1073** [comment]
@LuoShengMen 嗯，你按文档来吧

**Comment by LuoShengMen** [comment]
@Rocky1073 @afc163  解决了，谢谢您
