### ISSUE TITLE
antd pro eslint 报错 

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#1812]
npm 版本 5.6.0
windows 64位 专业版
报错代码如下：

Error: E:\workspace\github_repo\ant-design-pro\node_modules\_eslint-config-airbnb@17.0.0@eslint-config-airbnb\rules\react.js:
	Configuration for rule "react/jsx-no-target-blank" is invalid:
	Value [{"enforceDynamicLinks":"always"}] should NOT have more than 0 items.

Referenced from: E:\workspace\github_repo\ant-design-pro\node_modules\_eslint-config-airbnb@17.0.0@eslint-config-airbnb\index.js
Referenced from: E:\workspace\github_repo\ant-design-pro\.eslintrc.js

Error: E:\workspace\github_repo\ant-design-pro\node_modules\_eslint-config-airbnb@17.0.0@eslint-config-airbnb\rules\react.js:
	Configuration for rule "react/jsx-no-target-blank" is invalid:
	Value [{"enforceDynamicLinks":"always"}] should NOT have more than 0 items.

Referenced from: E:\workspace\github_repo\ant-design-pro\node_modules\_eslint-config-airbnb@17.0.0@eslint-config-airbnb\index.js
Referenced from: E:\workspace\github_repo\ant-design-pro\.eslintrc.js

**Comment by xgj1988** [comment]
搞定 。是从1.0升级上来文件没改的问题。

**Comment by xgj1988** [comment]
还是不行。。

**Comment by chenshuai2144** [comment]
善用搜索引擎
https://github.com/codeclimate/codeclimate-eslint/issues/355

**Comment by xgj1988** [comment]
@chenshuai2144  惭愧
