### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by lichenghu520** [ant-design/ant-design-pro#1813]
Failed to download Chromium r564778! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.
字面意思是设置环境变量跳过下载，怎么设置环境变量，在哪里设置，求大佬解答

**Comment by chenshuai2144** [comment]
这是因为puppeter下载失败，试试翻墙吧

**Comment by lichenghu520** [comment]
那为什么从github拉的代码可以？这个项目是之前的项目

**Comment by moooofly** [comment]
@lichenghu520 

That is what i did
```
echo "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install -g puppeteer" | sudo sh
```
