### ISSUE TITLE
打包build之后无法运行

### ISSUE THREAD

**Issue by zjhiphop** [ant-design/ant-design-pro#1822]
hi， 最近我在用版本（2.0.0-beta.1）开发后台管理平台， 在未打包的情况下，一切运行正常。但是使用`disableDynamicImport: true`打包之后，出现了异常错误。
错误发生的原因是Router 组件 Connect 的model值始终返回空， 并且在dispatch之后不会发送请求拿新的model值。

请问这种情况有可能是什么问题导致的？ 谢谢

**Comment by chenshuai2144** [comment]
能给个可重现的例子吗？

**Comment by zjhiphop** [comment]
找到问题了， 路由依赖没有指定model， 在未打包之前因为是全量加载， 所以不会报错

**Comment by weishijun14** [comment]
@zjhiphop 能告诉下如何解决的吗？

**Comment by rainjm** [comment]
我也遇到，build之后，redux开发工具能看到该条model数据，但是props找不到。
求解决方法。 @zjhiphop @chenshuai2144

**Comment by rainjm** [comment]
![image](https://user-images.githubusercontent.com/9592236/50508323-623ff980-0abc-11e9-95bd-bdca67b14d2f.png)
![image](https://user-images.githubusercontent.com/9592236/50508347-78e65080-0abc-11e9-8110-24ef4b4101bb.png)
