### ISSUE TITLE
react项目中使用pro是否必须要依赖dva?

### ISSUE THREAD

**Issue by tilamisu520114** [ant-design/ant-design-pro#183]

**Comment by fordguo** [comment]
前序准备

你的本地环境需要安装 node 和 git。我们的技术栈基于 ES2015+、React、dva、g2 和 antd，提前了解和学习这些知识会非常有帮助。

**Comment by afc163** [comment]
目前是绑定的，改造成其他应用框架成本略高且只会让代码更复杂。如果你需要使用自己的应用框架，你可以通过拷贝来复用 routes 和 components 的 UI 部分。
