### ISSUE TITLE
呼吁官方出一个页面原型设计工具

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#1830]
由于需求的不确定性，需要快速画出口述需求的页面让甲方确认是不是他想要的功能，有什么好的办法？

**Comment by dengfuping** [comment]
@zhaxingaz https://github.com/ant-design/kitchen

**Comment by afc163** [comment]
http://library.ant.design

**Comment by zhaxingaz** [comment]
好的，谢谢大家
