### ISSUE TITLE
`fixSiderbar` causes menu data to be displayed completely

### ISSUE THREAD

**Issue by lucasleelz** [ant-design/ant-design-pro#1831]
If using `fixSiderbar`
When there is too much data on the left menu, the left menu will not be displayed completely. I hope the left menu can be scrolled.

- version: "2.0.0-beta.1"

**Comment by chenshuai2144** [comment]
v2分支？

**Comment by lucasleelz** [comment]
@chenshuai2144 yes~

**Comment by chenshuai2144** [comment]
I will try

**Comment by chenshuai2144** [comment]
I found this problem, but it is not recommended to display many options in the menu, use the second level menu to hide better.

**Comment by chenshuai2144** [comment]
I found this problem, but it is not recommended to display many options in the menu, use the second level menu to hide better.

**Comment by lucasleelz** [comment]
Thanks, it seems that I need to implement it myself.
