### ISSUE TITLE
POST，body的参数问题

### ISSUE THREAD

**Issue by NorthNothing** [ant-design/ant-design-pro#1832]
我使用URLSearchParams把参数拼成key=value的形式，但是传到后台后，会把整个参数当成key值，因为后台需要的参数必须是要
![image](https://user-images.githubusercontent.com/16818104/42625567-a603861a-85fa-11e8-9e3e-12f3dbb1fe4a.png)这样一种格式。所以想知道为什么会把整个参数当成key值，但是在chorme控制台里是正确的参数

**Comment by chenshuai2144** [comment]
可能是 webpack proxy 的 bug。
你按照官网的依赖包，更新一下吧
