### ISSUE TITLE
路由点击无效，不能跳转到对应的路由

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#1834]
![image](https://user-images.githubusercontent.com/12181423/42626883-03b50f24-85fe-11e8-96c7-41dd2233caeb.png)

在订单列表中，点击查看进入详情，浏览器的地址栏变了，但是内容页面没有任何变化。

![image](https://user-images.githubusercontent.com/12181423/42626935-28daf0fc-85fe-11e8-89d9-d00ded998cf4.png)

**Comment by chenshuai2144** [comment]
看文档，三级菜单有专门的写法

**Comment by xuliuzhu1834** [comment]
没看到文档里有说三级路由的事啊?
````
'/': {
      component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    },
    '/customs/list': {
      component: dynamicWrapper(app, [], () => import('../routes/Customs/list/customs')),
    },
    '/customs/list/edit': {
      name: '添加编辑客户信息',
      component: dynamicWrapper(app, [], () => import('../routes/Customs/edit/customsEdit')),
    },
````

点击这个 /customs/list/edit 地址变了 但是面包屑和页面均无反应

**Comment by hqwlkj** [comment]
@xuliuzhu1834   将你的路由写成如下代码看看
`
'/': {
      component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    },
'/customs/list': {
      component: dynamicWrapper(app, [], () => import('../routes/Customs/list/customs')),
    },
'/list/edit': {
      name: '添加编辑客户信息',
      component: dynamicWrapper(app, [], () => import('../routes/Customs/edit/customsEdit')),
    },
`
