### ISSUE TITLE
在request中处理数据，不管用是怎么回事？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#1835]
我想在请求前判断是否有token，但是在request中设置的的`debugger`却没用。

始终进不去，但是请求已经发出去了。这是怎么回事？

**Comment by chenshuai2144** [comment]
show code

**Comment by chenshuai2144** [comment]
I can't reproduce.

**Comment by codepandy** [comment]
Hi @Be-Human ,
It be imported from `utils/request`;
