### ISSUE TITLE
Configuration item lessLoaderOptions is not valid, please remove it

### ISSUE THREAD

**Issue by Nuoky** [ant-design/ant-design-pro#1838]
使用版本：
https://github.com/ant-design/ant-design-pro/commit/2a761d4d916c48dbd2cc77522b426968ec1da6cd

运行命令：
`npm run start`

提示：
`Configuration item lessLoaderOptions is not valid, please remove it.`

删除.webpackrc.js的lessLoaderOptions后恢复正常

**Comment by chenshuai2144** [comment]
you can upgrade roadhog

**Comment by Nuoky** [comment]
Hi @chenshuai2144 
The roadhog version should be the latest.
`"roadhog": "^2.4.2" `

**Comment by chenshuai2144** [comment]
> yarn upgrade

**Comment by Nuoky** [comment]
抱歉，没注意到npm上roadhog版本改了...
