### ISSUE TITLE
请教下最新master下index.ejs多了几个js作用是什么？

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design-pro#1840]
不好意思，不知道这里问这个问题合不合适。
发现最新master分支下的index.ejs里比原来的多了下面几个js。请问下这几个js作用是什么呢。
```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script src="https://gw.alipayobjects.com/os/rmsportal/nGVBgVyXzzmbAqevIAPy.js"></script>
<script src=" https://gw.alipayobjects.com/os/rmsportal/TKSqiyoUxzrHoMwjViwA.js "></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/data-set/0.8.7/data-set.min.js"></script>
```
因为我们这网络有些问题，cdn.polyfill.io这些域名我们这经常回访问不通。。 如果作用不大的话，我想把这几个js去掉，请问下该如果去掉啊？
我这边去掉后会报下面这种错误：
<img width="782" alt="default" src="https://user-images.githubusercontent.com/8286897/42672043-0ce7c8c8-8696-11e8-8516-387a54805371.png">

有点迷茫，，不知道该如何下手，哪位兄弟帮忙给点思路。。谢谢。

**Comment by afc163** [comment]
@chenshuai2144 https://cdn.polyfill.io/v2/polyfill.min.js 这个不能用，网络环境不好。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/42677176-8dbe9122-86ad-11e8-9fed-f302ccf96903.png)
把这个删除了

**Comment by chenshuai2144** [comment]
> @chenshuai2144 https://cdn.polyfill.io/v2/polyfill.min.js 这个不能用，网络环境不好。
正在处理

**Comment by tulies** [comment]
@chenshuai2144 谢谢。

**Comment by chenshuai2144** [comment]
已经删除！
