### ISSUE TITLE
branch v2 编译特别缓慢

### ISSUE THREAD

**Issue by JoeyKo** [ant-design/ant-design-pro#1842]
![42687333-221179ee-86cb-11e8-8ca9-af3bea986126](https://user-images.githubusercontent.com/16659637/42687808-8f750536-86cc-11e8-95d7-6b9388548ad9.png)

**Comment by chenshuai2144** [comment]
因为使用了 umi？

**Comment by JoeyKo** [comment]
@chenshuai2144 是的

**Comment by JoeyKo** [comment]
@sorrycc umi版本热更新缓慢

**Comment by chenshuai2144** [comment]
周三会发布一个新版本，然后在试试

**Comment by tianlinzx** [comment]
什么时候发布新版本啊？

**Comment by yuzexing** [comment]
非常的慢...越编越慢

**Comment by chenshuai2144** [comment]
fix in umi
