### ISSUE TITLE
build打包时，是否有参数设置，可以将本地的测试数据也打包进去，方便项目演示？

### ISSUE THREAD

**Issue by zangnan** [ant-design/ant-design-pro#1843]
build打包时，是否有参数设置，可以将本地的测试数据也打包进去，方便项目演示。
而不需要真正调用后端服务接口。

**Comment by pkaq** [comment]
... 你打进去也没有mockserver阿

**Comment by chenshuai2144** [comment]
need a serve，look https://github.com/chenshuai2144/pro-server
