### ISSUE TITLE
"Required field mark (*)" doesn't shows up in required fields

### ISSUE THREAD

**Issue by efuentesp** [ant-design/ant-design-pro#1845]
I don't know why "*" doesn't shows up in fields marked with rules required.
[https://preview.pro.ant.design/#/form/basic-form](https://preview.pro.ant.design/#/form/basic-form)
I shaw this example and I don't know what are the differences
[https://ant.design/components/form/](https://ant.design/components/form/)
Does anybody knows??

**Comment by chenshuai2144** [comment]
hideRequiredMark
