### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by guohuihuiguo** [ant-design/ant-design-pro#1846]
请问如何在头部切换语言，使全局组件都可以使用呢，我配置了没有配置成功请指教

**Comment by afc163** [comment]
https://ant.design/docs/react/i18n-cn

**Comment by guohuihuiguo** [comment]
这个例子我已经试过了，主要问题是我按照这个脚手架搭建的‘然后我在header写toggle值不会再次刷新

**Comment by afc163** [comment]
可以再研究一下：https://github.com/yahoo/react-intl

**Comment by chenshuai2144** [comment]
先写在localStorage,然后 location.reload()
