### ISSUE TITLE
npm install 完整性验证错误，错误具体看

### ISSUE THREAD

**Issue by andotorg** [ant-design/ant-design-pro#1847]
npm ERR! code EINTEGRITY
npm ERR! sha1-ffjh6dBG1jHGUJ9+UxNX1K3CSqM= integrity checksum failed when using sha1: wanted sha1-ffjh6dBG1jHGUJ9+UxNX1K3CSqM= but got sha1-sA4XlwVcv9Wy87jt/FEd4h/bMRQ=. (2701943 bytes)

**Comment by chenshuai2144** [comment]
try `npm cache clean`
