### ISSUE TITLE
fetch post 请求获取参数问题

### ISSUE THREAD

**Issue by xietongjian** [ant-design/ant-design-pro#1848]
#### 1、通过tomcat启动端口（8088）发送请求：
```javascript
fetch('http://127.0.0.1:8088/portal/api/process/saveSp.jhtml', {
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Accept': 'application/json, text/javascript, */*; q=0.01'
    },
    method: 'POST',
    mode: 'cors',
    body: "taskId=8888888888888"
})
```
Controller可以获取数据:
![_20180715225352](https://user-images.githubusercontent.com/16096832/42735170-0d1bfd94-8882-11e8-8738-ef4b1024d459.png)

#### 2、通过ant design pro 配置的proxy 启动的端口（8000）Controller获取不到数据
```javascript
// .roadhogrc.mock.js 文件配置：
export default(noProxy ? {
        ...
        'POST /portal/api/(.*)': 'http://127.0.0.1:8088/portal/api/'
        ...    
}: delay(proxy, 200));
```
```javascript
fetch('http://127.0.0.1:8000/...'  省略
```
![_20180715230810](https://user-images.githubusercontent.com/16096832/42735309-1c63ee68-8884-11e8-8902-0b4fd4e41726.png)
请问怎么解决？

**Comment by chenshuai2144** [comment]
我们的 request 默认不是` 'Content-Type': 'application/x-www-form-urlencoded',`
你可能需要修改一下

**Comment by xietongjian** [comment]
改了试过，也没有效果。各种类型都试过了。

**Comment by xiaohuoni** [comment]
不知道你用的是哪个版本的，可以考虑是mock和proxy调用顺序引起的问题。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/492

**Comment by xietongjian** [comment]
发现jquery的ajax可以获取到值。

**Comment by xietongjian** [comment]
其实就是proxy的问题，这个问题很影响开发，开发的时候不好调试真实数据。 
同样的请求，同样的Content-Type配置  
http://127.0.0.1:8088/portal/api/process/saveSp.jhtml   -- tomcat启动的端口（8088）正常获取参数
http://127.0.0.1:8000/portal/api/process/saveSp.jhtml   -- npm run start:no-proxy 启动的端口（8000）获取不到参数

**Comment by guoyangyang666** [comment]
这个问题解决了吗？我也遇到了这个问题，用ajax可以用post传参，用antdesignpro里封装的post后台就获取不到前端传入的参数

**Comment by githubmann** [comment]
ant design prop 用了 http-proxy-middleware 插件，而这个插件默认不是代理 body 的


https://github.com/chimurai/http-proxy-middleware/issues/202
