### ISSUE TITLE
2.0的Release版本会不会将models分拆到各自的pages目录，按module组织代码？

### ISSUE THREAD

**Issue by gucciwu** [ant-design/ant-design-pro#1852]
请问2.0的Release版本会不会将models分拆到各自的pages/xxx目录，按module组织代码？貌似这种代码组织方式是umi推荐的

**Comment by kaoding** [comment]
使用roadhog按角色组织或者按功能组织差不多，但使用umi、按功能组织个人感觉更好一些。
