### ISSUE TITLE
npm install 报错npm ERR! Unexpected end of JSON input while parsing near '...mock-13.2.1.tgz"}},"1'

### ISSUE THREAD

**Issue by zspandroid** [ant-design/ant-design-pro#1856]
将项目clone下后,直接install,就报这个错误
npm ERR! Unexpected end of JSON input while parsing near '...mock-13.2.1.tgz"}},"1'
有什么好的解决办法么,

**Comment by chenshuai2144** [comment]
npm clear cache

**Comment by weishijun14** [comment]
npm cache clean --force
