### ISSUE TITLE
Mobile Compatibility? 

### ISSUE THREAD

**Issue by Indyandie** [ant-design/ant-design-pro#186]
While testing the demo I noticed that it's not mobile compatible. Is there a plan for the select dropdown to use native pickers?

**Comment by afc163** [comment]
Ant Design Pro will focus on desktop expierence and provide a decent mobile responsive interface only. We won't provide fully mobile compatibility support now.

**Comment by superlbr** [comment]
Well, I click menu with no router change using chrome/firefox/safari (all latest version).Unfriendly
