### ISSUE TITLE
根据服务器返回的代码提示重复显示怎么办？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#1862]
添加时需要服务器验重，如果已存在则返回一个状态吗，如果记录已存在，则提示记录存在。
我在页面上放了一个`Modal.Warning`,根据服务返回到状态设置一个变量VisibleStatus来表示是否显示，结果每次和服务端交互后，会被render好几次，放到didupdate中也不行，这种情况你们怎么解决的？

**Comment by chenshuai2144** [comment]
Did not understand，
show code？

**Comment by chenshuai2144** [comment]
说明你的 页面中数据变了好多次。
和 pro 无关

**Comment by codepandy** [comment]
@chenshuai2144 
你们没这个问题吗？现在只要和服务器交互，页面就会render很多次，即使知识更新一次state。
