### ISSUE TITLE
请问如何隐藏整个面包屑？

### ISSUE THREAD

**Issue by mengxin-FE** [ant-design/ant-design-pro#1863]
请问如何隐藏整个面包屑？hideInBreadcrumb: true, 只隐藏了当前的。 想隐藏整条面包屑
![image](https://user-images.githubusercontent.com/14139852/42758483-46a78fba-8936-11e8-8cab-44a4f17a1fb0.png)
![image](https://user-images.githubusercontent.com/14139852/42758495-54c33a5e-8936-11e8-8035-8beda5493770.png)

**Comment by chenshuai2144** [comment]
`breadcrumbList ={[]}`

https://pro.ant.design/components/PageHeader-cn/

**Comment by mengxin-FE** [comment]
试过了，无效呢。
![image](https://user-images.githubusercontent.com/14139852/42880571-594b73d8-8ac7-11e8-99a3-3575382d8263.png)
![image](https://user-images.githubusercontent.com/14139852/42880583-6200035e-8ac7-11e8-8b8f-592cc6b1bc78.png)
@chenshuai2144

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/PageHeader/index.js#L68
粗暴一点 删掉这个方法
