### ISSUE TITLE
PageHeaderLayout  content中有使用到Dropdown时

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design-pro#1866]
React.Children.only expected to receive a single React element child.

×
←→1 of 2 errors on the page
React.Children.only expected to receive a single React element child.
▼ 28 stack frames were expanded.
invariant
E:/ant/myworkvrsm/ifire-fe/node_modules/_fbjs@0.8.17@fbjs/lib/invariant.js:42
onlyChild [as only]
E:/ant/myworkvrsm/ifire-fe/node_modules/_react@16.4.1@react/cjs/react.development.js:998
Dropdown.render
E:/ant/myworkvrsm/ifire-fe/node_modules/_antd@3.6.4@antd/es/dropdown/dropdown.js:56
finishClassComponent
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:13193
updateClassComponent
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:13155
beginWork
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:13824
performUnitOfWork
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:15863
workLoop
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:15902
HTMLUnknownElement.callCallback
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:100
invokeGuardedCallbackDev
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:138
invokeGuardedCallback
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:187
replayUnitOfWork
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:15310
renderRoot
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:15962
performWorkOnRoot
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16560
performWork
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16482
performSyncWork
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16454
requestWork
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16354
scheduleWork$1
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16218
scheduleRootUpdate
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16785
updateContainerAtExpirationTime
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16812
updateContainer
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16839
ReactRoot.render
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:17122
(anonymous function)
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:17262
unbatchedUpdates
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:16679
legacyRenderSubtreeIntoContainer
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:17258
render
E:/ant/myworkvrsm/ifire-fe/node_modules/_react-dom@16.4.1@react-dom/cjs/react-dom.development.js:17317
render
E:/ant/myworkvrsm/ifire-fe/node_modules/_dva@2.3.1@dva/lib/index.js:115
start
E:/ant/myworkvrsm/ifire-fe/node_modules/_dva@2.3.1@dva/lib/index.js:81
▲ 28 stack frames were expanded.
(anonymous function)
E:/ant/myworkvrsm/ifire-fe/src/index.js:28
  25 | app.router(require('./router').default);
  26 | 
  27 | // 5. Start
> 28 | app.start('#root');
  29 | 
  30 | export default app._store; // eslint-disable-line
  31 | 
View compiled
▶ 6 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by chenshuai2144** [comment]
show code

**Comment by MinHongwei** [comment]
const pageHeaderContent = (
      <div className={styles.pageHeaderContent}>
        <div className={styles.avatar}>
          <Avatar
            size="large"
            src={require('../../../assets/ifp/ifpProject/typecode1.png')}
          />
        </div>
        <div className={styles.content}>
          <div>项目信息</div>
          <div className={styles.contentTitle}>
            <div className={styles.contentTitleSmall}>
              <Dropdown overlay={menu} placement="bottomRight">
              项目名称：{pageHeaderContentData[0]}
              </Dropdown>
            </div>
            <div className={styles.contentTitleSmall1}>项目地址：{pageHeaderContentData[1]}</div>
          </div>
        </div>
      </div>
    );
<PageHeaderLayout content={pageHeaderContent} extraContent={extraContent}>
。。。。。
</PageHeaderLayout>

**Comment by MinHongwei** [comment]
return (
      <PageHeaderLayout content={pageHeaderContent} extraContent={extraContent}>

**Comment by MinHongwei** [comment]
"version": "1.3.0",

**Comment by chenshuai2144** [comment]
发生了什么？
