### ISSUE TITLE
求问为什么我在request添加自定义h，会出现500的报错

### ISSUE THREAD

**Issue by xiaosusyc** [ant-design/ant-design-pro#1869]
![image](https://user-images.githubusercontent.com/25654163/42807561-be8a36ce-89e3-11e8-97a3-1d1c0e9fab5d.png)

这样是不会报错，但是如果变成这样。
![image](https://user-images.githubusercontent.com/25654163/42807623-e2f306bc-89e3-11e8-9368-d32bfd1cb8f3.png)

会出现这样的错误

![image](https://user-images.githubusercontent.com/25654163/42807700-10f431c6-89e4-11e8-9896-1d5bb9f48ed2.png)

**Comment by chenshuai2144** [comment]
你的后端有校验吧 最好和后端沟通一下
