### ISSUE TITLE
Pie控件title和total不居中

### ISSUE THREAD

**Issue by zhu-** [ant-design/ant-design-pro#1875]
pie其他显示都很正常，但title和total不是居中的，特别难看。
哪位大神能帮忙看一下，在下拜谢。

<img width="888" alt="image" src="https://user-images.githubusercontent.com/10358699/42876564-a8ed9384-8ab9-11e8-9db2-a1979eed1355.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/10358699/42876946-c91b6ebe-8aba-11e8-9332-075884e531e2.png">

**Comment by chenshuai2144** [comment]
是不是 css 污染，最好给个重现地址
