### ISSUE TITLE
点击登陆菜单报错，基于最新commit的版本Fix dynamic component remount, #114

### ISSUE THREAD

**Issue by renyi818** [ant-design/ant-design-pro#188]
提示：
UserLayout.js?17bb:43 Uncaught TypeError: Cannot read property 'path' of undefined
    at UserLayout.getRouteComponent (UserLayout.js?17bb:43)

**Comment by afc163** [comment]
这个 PR 还未合并，你应该回复到 #184 下，而不是新开一个 issue。

**Comment by renyi818** [comment]
ok

**Comment by afc163** [comment]
我搞错了，我以为你说的是 #184 的问题。

**Comment by afc163** [comment]
anyway，#184 正在重构这种写法。

**Comment by renyi818** [comment]
ok : )
