### ISSUE TITLE
嵌套子表格组件，能否（非手动js）实现手风琴效果的功能？

### ISSUE THREAD

**Issue by Henery002** [ant-design/ant-design-pro#1880]
antd原生的嵌套子表格组件，是可以将表格每一行都点击详情展开的，现在需求是能否实现点击某一展开项时收起其他项的功能（非手动写js实现）？类似于这样（此处是手写的js强制实现的，但是存在bug，就是有时候每一项必须点击两下才能展开）：
http://pc3y2nwj1.bkt.clouddn.com/antd%E5%B5%8C%E5%A5%97%E5%AD%90%E8%A1%A8%E6%A0%BC%E6%89%8B%E9%A3%8E%E7%90%B4%E6%95%88%E6%9E%9C.gif

**Comment by chenshuai2144** [comment]
去 antd 请求新的功能吧
