### ISSUE TITLE
Ellipsis组件在firefox下页面加载直接卡死了，报错InternalError: "too much recursion"

### ISSUE THREAD

**Issue by weichunyan** [ant-design/ant-design-pro#1882]

**Comment by jieliu218** [comment]
if (sh <= th) {
            shadowNode.innerHTML = text.substring(0, mid + 1) + suffix;
            sh = shadowNode.offsetHeight;
            if (sh > th) {
                return mid;
            } else {
                begin = mid;
                mid = Math.floor((end - begin) / 2) + begin;

                return this.bisection(th, mid, begin, end, text, shadowNode);
            }

if  end is 9 and begin is 8, then begin is always 8

**Comment by sbyps** [comment]
还有一个问题，
componentWillReceiveProps(nextProps) {
    const { lines } = this.props;
    if (lines !== nextProps.lines) {
      this.computeLine();
    }
  }

如果组件的children更新了，组件不会被更新；

**Comment by sbyps** [comment]
@nikogu

**Comment by nikogu** [comment]
@weichunyan @jieliu218 最好能给个 demo 重现。

**Comment by nikogu** [comment]
@sbyps 这个 `componentWillReceiveProps ` 跟子组件更新没有什么关系吧，给个 demo？

**Comment by jieliu218** [comment]
@nikogu 
![image](https://user-images.githubusercontent.com/3033810/43189392-24e0cc28-8fff-11e8-926f-1049dad5cb0d.png)

比如我这一行能 展示超过20个汉字， 但是现在标题只有 八个汉字


if (sh <= th) {
shadowNode.innerHTML = text.substring(0, mid + 1) + suffix;
sh = shadowNode.offsetHeight;
if (sh > th) {
return mid;
} else {
begin = mid;
mid = Math.floor((end - begin) / 2) + begin;
 return this.bisection(th, mid, begin, end, text, shadowNode);
 }

最终 th = 8， sh = 7，  mid = Math.floor((end - begin) / 2) + begin;  mid 永远 等于7 ，  然后继续调用
 this.bisection 就会是死循环

因为我是单独抽取了这个组件来用，我把代码简单改了一下
![image](https://user-images.githubusercontent.com/3033810/43189713-e6453bc4-8fff-11e8-9993-3e5dc643a4e7.png)

**Comment by nikogu** [comment]
@jieliu218 按照你提供的方式把 Ellipsis 改了下
