### ISSUE TITLE
BizCharts支持按需加载了，pro是不是也跟进一下

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design-pro#1884]
现在打包体积BizCharts比较大，希望优化

**Comment by chenshuai2144** [comment]
地址？

**Comment by YinRenjie1993** [comment]
https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/needload.md

**Comment by YinRenjie1993** [comment]
@chenshuai2144 https://github.com/alibaba/BizCharts/blob/master/doc/tutorial/needload.md

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
pro 无法使用，打算上 cdn
