### ISSUE TITLE
ie浏览器出现SCRIPT1046错误

### ISSUE THREAD

**Issue by hantailala** [ant-design/ant-design-pro#1885]
SCRIPT1046: strict 模式下不允许一个属性有多个定义

**Comment by hantailala** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>xxx</title>
    <link rel="icon" href="/favicon.png" type="image/x-icon">

</head>

<body>
  <div id="root"></div>
<script type="text/javascript" src="/index.js"></script></body>
</html>

**Comment by chenshuai2144** [comment]
这个一般是协发布规范

https://github.com/zhongxia245/blog/issues/23
