### ISSUE TITLE
请问如何使用阿里妈妈MUX的矢量图标？

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#189]
#### Environment(required) | 环境（必填）

- roadhog version（roadhog版本）:
1.3.1
- Nodejs and Npm version（Nodejs 和 Npm 版本）:
Node Version: 8.8.1,
Npm Version:5.4.2
- Operating environment (e.g. OS name) and its version（操作系统版本）:
 macOS Sierra v10.12.6

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

Source
`@font-face {
  font-family: 'carme-icon';  /* project id 265558 */
  src: url('//at.alicdn.com/t/font_265558_g02ko1kw1k2zkt9.eot');
  src: url('//at.alicdn.com/t/font_265558_g02ko1kw1k2zkt9.eot?#iefix') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_265558_g02ko1kw1k2zkt9.woff') format('woff'),
  url('//at.alicdn.com/t/font_265558_g02ko1kw1k2zkt9.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_265558_g02ko1kw1k2zkt9.svg#carme-icon') format('svg');
}`

#### What do you expected?（预期的正常效果）
This is the expected effect
![image](https://user-images.githubusercontent.com/12181423/32759407-e2596eb8-c8ae-11e7-931d-98459326a608.png)

#### What happen?（发生了何种非正常现象）
The font icon does not display properly
![image](https://user-images.githubusercontent.com/12181423/32759318-756b9e3e-c8ae-11e7-9fe9-0c9a08a54315.png)

#### Re-producible online demo (可复现的在线demo)
Gitlub: http://gitlab.parsec.com.cn/Yanghc/DracoMobile 

<!--
Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

**Comment by w3286879** [comment]
我想问下你们头像是图片还是根据首字母生成的？

**Comment by hqwlkj** [comment]
@w3286879  这个是在用户没有设置头像的时候就用用户名的首字 来生成。
