### ISSUE TITLE
如何把url里面的#号给删除了？

### ISSUE THREAD

**Issue by tang-yue** [ant-design/ant-design-pro#1891]
比如：localhost:8000/#/form/basic-form   里面的 # 号

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88
