### ISSUE TITLE
v2 service-worker throw error

### ISSUE THREAD

**Issue by xiaozhouwu** [ant-design/ant-design-pro#1893]
service-worker.js:1 Uncaught SyntaxError: Unexpected token <

![image](https://user-images.githubusercontent.com/21081809/43013987-4a4662f0-8c7d-11e8-90e3-0ef28b26d90e.png)

![image](https://user-images.githubusercontent.com/21081809/43014042-75dfbb50-8c7d-11e8-8de8-bf83521a03d3.png)

so what is going on with PWA?

**Comment by chenshuai2144** [comment]
耐心等待
