### ISSUE TITLE
pro 的geohey问题

### ISSUE THREAD

**Issue by omigaZ** [ant-design/ant-design-pro#1896]
geohye的地图控件加载需要在componentDidMount里。我在这里和componentWillMount分别加载了api的数据如图
![image](https://user-images.githubusercontent.com/26153946/43055872-a2f61748-8e6b-11e8-81ef-9941d541bfbb.png)
但是在图片控件里打印数据this.props结果没有任何数据，但是在render里却能打印到。所以这时该怎么才能把数据渲染到地图的组件里呢？求大神指导。

**Comment by chenshuai2144** [comment]
代码详细点？
