### ISSUE TITLE
如何去掉url 里面的#

### ISSUE THREAD

**Issue by tang-yue** [ant-design/ant-design-pro#1898]
urll 会自动跳到带#的路由，想去掉#，如何去掉

**Comment by Jeepeng** [comment]
使用 BrowserHistory

https://github.com/ant-design/ant-design-pro/blob/ae3857515dee4956e6a919aac185fa420116a728/src/index.js#L5-L6

**Comment by tang-yue** [comment]
@Jeepeng   
Thank you very much, I just solved this problem according to your method.
