### ISSUE TITLE
请问如何改变打包路径，打包到dist/xxxx 目录下，现在是在dist 目录下。

### ISSUE THREAD

**Issue by tang-yue** [ant-design/ant-design-pro#1899]
我在 webpackrc.js 中这样配output。
 output: {
    publicPath: '/dist/assit/'
  },
但是提示 该output配置无效。

**Comment by chenshuai2144** [comment]
publicPath 直接用这个

roadhog 了解一下

**Comment by codepandy** [comment]
解决了吗？

**Comment by tang-yue** [comment]
@codepandy  解决了

**Comment by niugengyun** [comment]
> @codepandy 解决了

怎么解决的

**Comment by tang-yue** [comment]
在 .webpackrc.js 文件中
```
export default {
   outputPath: "./dist/xxxx/",
   env: {
      production: {
          publicPath: "/xxxx"
      }
   }
}
```
以上满足了我的需求， 不知道你是不是也是要打包这样。
我的项目需求是， 测试环境，要调用嵌一个目录下的js 和css.
@codepandy @niugengyun

**Comment by niugengyun** [comment]
谢谢您的热心回复。

我的目的是要把css放到  dist/css , js 放到dist/js ，请问应该怎么配置

**Comment by tang-yue** [comment]
打包完了应该会在,  
```
  -------- dist
               -----xxxx
                       -------js
                       -------css
```
如上就是我上面所说得打包完了之后。
如果要打包到dist/css 和dist/js   ,你直接就这样 outputPath:"./dist/"。
自己试着变变，应该没有几种方式。
@niugengyun

**Comment by niugengyun** [comment]
我用的 2.0，按照您说的试了，不行的

代码全部打包在了dist的根目录了

`  outputPath: "./dist",
`

**Comment by tang-yue** [comment]
```
 export default {
   outputPath: "./dist/xxxx/",
   env: {
      production: {
          publicPath: "/xxxx"
      }
   }
}
```
那你把xxxx 换成 dist 不就行了
@niugengyun

**Comment by kele527** [comment]
> ```
>  export default {
>    outputPath: "./dist/xxxx/",
>    env: {
>       production: {
>           publicPath: "/xxxx"
>       }
>    }
> }
> ```
> 
> 那你把xxxx 换成 dist 不就行了
> @niugengyun

你这个方式不行的， 从你的配置中没看到区分js和css， 如果不区分， js和css不就输出到同一个目录了？
