### ISSUE TITLE
Upgrade G2 to 3.0

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#19]
- 包：[@antv/g2@3.0.0-rc5](https://www.npmjs.com/package/@antv/g2)   [@antv/data-set@0.5.0](https://www.npmjs.com/package/@antv/data-set)

**Comment by nikogu** [comment]
待定，等 XXXCharts 开源之后再做升级

**Comment by afc163** [comment]
Consider http://recharts.org/ too.

**Comment by topwood** [comment]
Consider https://www.highcharts.com/ too.

**Comment by afc163** [comment]
@topwood Nope, highcharts is not a commercial-free project.

**Comment by topwood** [comment]
@afc163 OK，3Q anyway

**Comment by WhatAKitty** [comment]
why not echarts?

**Comment by yesmeck** [comment]
May be we can create a G2 renderer by using the new react-reconciler lib.

**Comment by viztor** [comment]
G2@3 is now officially released.
