### ISSUE TITLE
StandardTable 翻页多选BUG

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#1900]
###  StandardTable 翻页多选BUG
StandardTable 翻页多选
  handleSelectRows = rows => {
    //处理添加的rows
    // rows =  this.appendRows(rows);
    console.log(rows);
    this.setState({
      selectedRows: rows,
      selectedOrgIds: rows.map(row => row.seq)
    });
  };
- 只有前端数据的时候，数据是正确的
- npm run build 后数据直接就只传最后一页选中的记录

**Comment by chenshuai2144** [comment]
因为是个demo，试试 https://beta.preview.pro.ant.design/

**Comment by yemaozi5518** [comment]
我想找到源码，根据需求该几个name值，和dispach参数  @chenshuai2144    https://beta.preview.pro.ant.design/ 看到的是 run build 后的俩静态文件

**Comment by yemaozi5518** [comment]
- 只有前端数据的时候，是mock的数据，一次查询就查出所有的List记录，在翻页的时候只是更新了pagenation的current 属性。所以 this.state.selectedRows 没有被清空。
- npm run build 后，每次翻页都是一次查询，只查询出对应的pageSize和current的数据。所以有什么可以保存selectedRows的方法没有？ @chenshuai2144

**Comment by yemaozi5518** [comment]
我想看到翻页选中多条记录，在删除或者其他批量操作时，F12，对应操作的network，对应的requestBody里的数据。

**Comment by yemaozi5518** [comment]
handleStandardTableChange = (pagination, filtersArg, sorter) => {
    const {dispatch} = this.props;
    const {formValues} = this.state;

    const filters = Object.keys(filtersArg).reduce((obj, key) => {
      const newObj = {...obj};
      newObj[key] = getValue(filtersArg[key]);
      return newObj;
    }, {});

    const params = {
      currentPage: pagination.current,
      pageSize: pagination.pageSize,
      ...formValues,
      ...filters
    };
    if (sorter.field) {
      params.sorter = `${sorter.field}_${sorter.order}`;
    }
    dispatch({
      type: 'adminUser/fetch',
      payload: params
    });
// 加入了打印this.state.selectedRows
//翻页后，run build 之后只打印，最后一次选择所在页，选中的rows
    console.log(this.state.selectedRows);
  };

**Comment by yemaozi5518** [comment]
我是不是可以认为  table_list  的  checkbox 和 selectedRows 不同步？ @chenshuai2144

**Comment by yemaozi5518** [comment]
前端的显示，翻页选中什么的没有任何问题。
-  选中一行后 ，单击按钮进行操作，传递的只是当前页的选中项rows
-  翻页，单击按钮进行操作，传递的最后一次选择所在页，选中的rows

可以尝试下master的前后端run build 实现吗？

**Comment by yemaozi5518** [comment]
200 和 304 的区别就是run build 前后翻页dispatch的区别

**Comment by chenshuai2144** [comment]
304 代表缓存，200是正常成功

**Comment by yemaozi5518** [comment]
npm  run build 前后翻页就是这样  
仅仅前端  翻页是304
npm  run build 后  翻页是200

**Comment by chenshuai2144** [comment]
是 http 的策略，这个不是区别。
run build是把接口静态化了

**Comment by WALLE729** [comment]
可勾选的table表格，在第a页勾选几条数据，在b页再勾选几条数据，selectedRowKeys可以累加，但是selectedRows的值会重新记录，只有当前页面的数据

**Comment by 308787520huanhuan** [comment]
![111](https://user-images.githubusercontent.com/3348828/51586791-91aa2080-1f19-11e9-921d-6996f2f208a2.png)
![22222](https://user-images.githubusercontent.com/3348828/51586794-92db4d80-1f19-11e9-9ed2-fca2d6285bab.png)

**Comment by HiroTang** [comment]
虽然selectedRowKeys是实时的，但是不懂得在StandardTable或Table内维护这个选中的行记录，因此目前是在用到表的组件内维护一个每页selectedRows的对象数组。。。。
