### ISSUE TITLE
build 后图片路径错误

### ISSUE THREAD

**Issue by hllhui** [ant-design/ant-design-pro#1902]
我引入图片的方式是这样的：
import logo from '../assets/logo.png';
logo={logo}

当我build之后，在public/static 生成了一张图片 ‘logo.bde1a9a9.png’
打开网页报错
‘logo.bde1a9a9.png:1 GET http://localhost:7001/app/publicstatic/logo.bde1a9a9.png 404 (Not Found)’
正确的路径应该是http://localhost:7001/public/static/logo.bde1a9a9.png，我是哪里导致路径出错了？

**Comment by chenshuai2144** [comment]
publicPath 配置了吗？

**Comment by hllhui** [comment]
在config.default.js 这样写的
<js> config.assets = {
    publicPath: '/public',
    devServer: {
      command: 'roadhog dev',
      port: 8000,
      env: {
        BROWSER: 'none',
        DISABLE_ESLINT: true,
        SOCKET_SERVER: 'http://localhost:8000',
        PUBLIC_PATH: 'http://localhost:8000',
      },
      debug: true,
    },
  };</js>

.webpackrc.js 里面是这样的
<js>  publicPath: 'app/public',
  outputPath: 'app/public',</js>

**Comment by hllhui** [comment]
找到原因了，.webpackrc.js 里面的publicPath错了，应该是
publicPath: '/public/',
