### ISSUE TITLE
不用input.search 怎么用外部按钮获取到 input的值从而搜索

### ISSUE THREAD

**Issue by FaFamylove** [ant-design/ant-design-pro#1906]
使用了refs 结果获取到的是这样的内容：

![1532403824 1](https://user-images.githubusercontent.com/35513966/43115791-9850e3d2-8f37-11e8-99ef-e41f1f768190.jpg)
![1532403893 1](https://user-images.githubusercontent.com/35513966/43115817-a715feb6-8f37-11e8-82b6-ace74b8454f2.jpg)
找了props中的value 没发现获取方式 求助

**Comment by chenshuai2144** [comment]
[controlled-components](https://reactjs.org/docs/forms.html#controlled-components)

**Comment by FaFamylove** [comment]
我使用的是ant D的input组件 并不是 input标签 现在是想用Input 组件的情况下获取value

**Comment by afc163** [comment]
onChange

**Comment by FaFamylove** [comment]
感谢你们的指导，我使用了onKeyDown解决了问题
