### ISSUE TITLE
请教一下，打包发布后的路径问题

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#1915]
问题描述：
有没有谁遇到过这一个问题：打包发布后  用户要求访问的地址是  http://example.com/dev/admin/#/home  
第一次访问的时候没有问题，但是刷新的时候就变成了 http://example.com/#/home  ，服务器就直接404 了，有谁遇到过么？

服务器部署目录结构：
![image](https://user-images.githubusercontent.com/12181423/43177653-dc972e56-8ffb-11e8-867e-72b2228871cb.png)

测试web访问地址：https://wxapp.ketomall.cn/?env=staging

**Comment by hllhui** [comment]
我之前也遇到路径问题，是我.webpackrc 里面的publicPath写错了

**Comment by JevonYang** [comment]
修改publicPath和baseUrl配置即可。例如，publicPath=/dev/admin, baseUrl=/dev/admin，此时再部署到nginx里，就能够正确访问路径以及css等静态文件了。

**Comment by hqwlkj** [comment]
@JevonYang   谢谢，这样写是能访问了，也只能使用 hash路由了。

**Comment by hqwlkj** [comment]
@chenshuai2144   配置了 baseUrl 和 publicPath 部署之后出现一个问题，就是路径在重定向之后会多一级hash路由，正常的应该是这样的地址：https://wxapp.ketomall.cn/staging/admin/ 根路径地址  ，这时候没有登录，登录之后会多出一级路由 https://wxapp.ketomall.cn/staging/admin/#/staging/admin/ ，这是怎么回事呢？  


账号密码为：admin  可以登录测试

**Comment by hqwlkj** [comment]
此问题 自己已经处理。

**Comment by cindyZhang4** [comment]
> 此问题 自己已经处理。

请问怎么处理的？

**Comment by hqwlkj** [comment]
@cindyZhang4  我上面已经贴出代码的。
