### ISSUE TITLE
在BasicLayout组件中，后端获取菜单数据，正确更新state，但是菜单组件中的数据不能刷新

### ISSUE THREAD

**Issue by JevonYang** [ant-design/ant-design-pro#1916]
想实现从后台请求菜单数据，数据可以正确获取，并且state改变也是正确的，但是在页面渲染的时候，并不能将数据加载到菜单组件中。

但是再次进行登录，由于state中已经有了菜单数据，所以可以正确加载菜单以及数据。

获取菜单数据部分，我是写入componentWillMount函数中。不知道这么写对不对，请大神指教。
```
class BasicLayout extends React.PureComponent {
    ……

  componentWillMount() {
    const { dispatch } = this.props;
    dispatch({
      type: 'user/fetchMenu',
    });
  }

    ……
}
```

**Comment by 693614965** [comment]
要在登录的时候，返回 菜单 信息。保存 到  LocalStorage  然后再 BasicLayout  获取 。菜单的加载，好像不支持 异步 获取

**Comment by JevonYang** [comment]
@693614965 感谢。
这样同样带来一个问题。登录的时候，请求菜单信息，往往还没有获取到菜单信息，菜单内容已经开始渲染，就会导致报错。

**Comment by JevonYang** [comment]
根据#1555 
> src/components/SiderMenu/SiderMenu.js 组件constructor里初始化了this.menus = props.menuData，直接用props.menuData替换this.menu

可以正确显示菜单，但是不能正确展开菜单，点击某菜单，整个菜单会立即收起。
