### ISSUE TITLE
手机号 登录，怎么给服务器 发送 验证码

### ISSUE THREAD

**Issue by 693614965** [ant-design/ant-design-pro#1917]
登录 页面，手机号，登录，不输入 手机号，应该 就不能 点击 获取验证码 才对啊。要不然 验证码 发送 到 哪个 手机 号 呢？还有 就是 onGetCaptcha  都没有定义，不知道怎么在Login.js 页面，向 服务器 发送 验证码 的请求

**Comment by 533001** [comment]
有小伙伴儿 贴一下 demo么

**Comment by chenshuai2144** [comment]
学习一下基本功？
https://github.com/facebook/react
