### ISSUE TITLE
.webpackrc.js 设置proxy代理无效

### ISSUE THREAD

**Issue by Lin-YingYu** [ant-design/ant-design-pro#1918]
ant-design-pro version：1.3.0
antd version：3.7.0
dva version:：2.3.1
.webpackrc.js proxy配置如下：
`proxy: {`
     `"/admin": {`
      `"target": "http://my.xxx.com",`
      `"changeOrigin": true,`
      `"pathRewrite": { "^/admin" : "" },`
   ` },`
  `},`
api.js 接口定义：
`export async function fakeAccountLogin(params) {`
 ` return request('/admin/login', {`
    `method: 'POST',`
    `headers: {`
      `'Content-Type': 'application/x-www-form-urlencoded',`
   ` },`
   ` body: stringify(params),`
  `});`
`}`
启动命令如下：
`yarn start:no-proxy`

**Comment by JevonYang** [comment]
启动命令应该是用yarn start

**Comment by Lin-YingYu** [comment]
yarn start 也尝试过。
yarn start:no-proxy 这个只是禁用mock的吧!

**Comment by QunxingHu** [comment]
有什么解决方案不，npm start， proxy也是不生效, 依然走本地

**Comment by Lin-YingYu** [comment]
启动命令：yarn start:no-proxy
.webpackrc.js proxy：
`proxy: {`
     `"/admin": {`
       `"target": "http://my.xxx.com/",`
       `"changeOrigin": true,`
       `"pathRewrite": { "^/admin" : "" },`
   ` },`
`},`
api.js 接口定义：（提交form data格式）
`export async function fakeAccountLogin(params) {`
    `const formdata = new FormData();`
     `const { username, password } = params;`
    `formData.append("username", username);`
   ` formData.append("password", password);`
   `return request('/admin/login', {`
       `method: 'POST',`
       `body: formdata,`
   ` });`
`}`
之前form data 格式搞错了。~亲测有效，代理成功！

**Comment by qingming418** [comment]
"/admin/**": { .... }
