### ISSUE TITLE
table分页到第2页， 查询框从新筛选后，数据从新渲染回第一页的数据， 分页器还停在第2页

### ISSUE THREAD

**Issue by lishuai1021** [ant-design/ant-design-pro#1920]
handleSearch = () => {    //绑定Input.Search  onchange
    let page = this.state.page;
    page.currPage = 1;
    page.limit = 10;
    this.setState({ page: page });

    this.search({ page: page, filter: this.state.filter });
  }
 handleableChange = (pagination, filters) => {  //绑定 Table onchange
    const { dispatch } = this.props;
    const { formValues } = this.state;
    let temp_page = this.state.page;
    temp_page.currPage = pagination.current;
    temp_page.limit = pagination.pageSize;
    let filter = {
      ...formValues,
    };
    this.setState({
      page:temp_page,
      filter: filter,
    });
    const params = {
      page:temp_page,
      filter:filter,
    };
    this.search(params);
  };

**Comment by lishuai1021** [comment]
...

**Comment by chenshuai2144** [comment]
试试这里 
https://beta.preview.pro.ant.design/
