### ISSUE TITLE
There is a bug in the basic-list

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design-pro#1922]
in the basic-list,I add a tag component to ListContent of List,The tag will blink once each time the render is triggered.

上面的给外国人的看的，就是basic-list页面中，<List>组件里定义了
![image](https://user-images.githubusercontent.com/10751248/43239144-c69db6ce-90c3-11e8-98cc-9f5a7262a3e3.png)
每次触发render 的时候，tag 都会闪烁一次，我这不方便给出一个演示链接，就给截图了
![image](https://user-images.githubusercontent.com/10751248/43239286-35a4eac4-90c4-11e8-9e4f-106381e7f493.png)
![image](https://user-images.githubusercontent.com/10751248/43239313-4cbc7498-90c4-11e8-8ffd-a75dbfef68be.png)

这里写onChange事件就是为了触发render，没有别的意义
你们试一试就知道了，这个真是不方便给出演示的链接，希望能尽快修改这个bug

**Comment by wanliyunyan** [comment]
![image](https://user-images.githubusercontent.com/10751248/43243439-55337904-90d9-11e8-8769-16437036337d.png)
最简单的方案就是不把这堆代码提出来，而是写到一起就好了
@chenshuai2144

**Comment by afc163** [comment]
最好还是能给个重现。

**Comment by wanliyunyan** [comment]
@afc163 哥们，你在你自己的pro项目里试一下就知道了，我现在还不会怎么在codepen 上面搞一个完整的项目。。。。search 里 加个 onChange 事件 发送dispatch就行，然后就能触发render，就能看到效果

**Comment by afc163** [comment]
fork 一个 antd，把改动 push 上来。

**Comment by wanliyunyan** [comment]
https://github.com/wanliyunyan/ant-design-pro  @afc163 ，好了，你看一眼吧

**Comment by xialvjun** [comment]
@wanliyunyan https://codepen.io/ 不好做完整的项目。。。但是 https://codesandbox.io/  和 https://stackblitz.com/ 这两个做完整项目展示倒是很方便的

**Comment by afc163** [comment]
感谢反馈和帮忙重现。

在 https://github.com/ant-design/ant-design-pro/commit/56a07488bfc9fad783281afd3414dee0ff7fdbf0 里修复了，原来的写法性能有很大问题。

**Comment by wanliyunyan** [comment]
@xialvjun 谢谢，一直不太了解这些网站
