### ISSUE TITLE
Modal组件显示隐藏时候会闪动

### ISSUE THREAD

**Issue by qianxuemin** [ant-design/ant-design-pro#1927]
Modal组件显示隐藏时候会闪动，可能是什么问题？

**Comment by fairySusan** [comment]
我说一下我怎么解决的：
我是因为在自己的css文件中写了 .fade-enter, .fade-enter-active 的样式导致弹窗闪烁的，以后遇到这个问题的人可以查看一下自己的css文件有没有类似的代码重写了ant的css
