### ISSUE TITLE
nav.js菜单数据后台对接问题

### ISSUE THREAD

**Issue by panlingfeng** [ant-design/ant-design-pro#193]
请问，nav.js中const data数据不是标准的json数据，后台怎么对接，后台使用spring boot 返回标准的json菜单数据，莫非需要自己将后台返回的json处理成不标准的给data

**Comment by Rocky1073** [comment]
同求

**Comment by nikogu** [comment]
菜单数据现在后台也要管理了吗，如果是这样，中间多一层转换就好，然后最终生成类似 `nav.js` 中的数据结构即可。

**Comment by lawrence-peng** [comment]
做权限分配，菜单数据一般都是有做管理的。

**Comment by Rocky1073** [comment]
思路知道，具体怎么写

**Comment by renyi818** [comment]
同问，java服务器后端传递有权限的菜单数据集到前端展现还是比较常见的，希望能有相应的案例。

**Comment by afc163** [comment]
尝试把这里的 navData 换成 redux store 里的数据即可。

https://github.com/ant-design/ant-design-pro/blob/5cce044192684535c93a23952ec831529b71f350/src/layouts/BasicLayout.js#L50

**Comment by panlingfeng** [comment]
感谢@afc163提供一个可行的思路！！！

**Comment by ityao** [comment]
怎么替换成redux的数据呢, 那是构造函数, model数据还没获取到吧

**Comment by wgwxf** [comment]
nav.js前台写死，加上auth:'user:manage'这样的权限code，登陆时返回当前用户的所有权限，渲染BasicLayout的时候判断有没有菜单权限。
