### ISSUE TITLE
antd pro can not support multiple tabs（antd pro能不能实现多页应用）

### ISSUE THREAD

**Issue by RivanLuo** [ant-design/ant-design-pro#1935]
we need to open multiple independent tab and different tabs are also edited at the same time.

我想知道antd pro能不能实现多页应用，我需要同时打开多个页面，而且是相互独立的，页签来回切换仍然可以保持页面的最终状态。请问，是否可以实现，如果可以，希望提供一些demo或者思路。
![default](https://user-images.githubusercontent.com/13898695/43385678-f056194a-9413-11e8-9bc5-796ed3e810f1.PNG)

**Comment by chenshuai2144** [comment]
搜一下 issue，有这方面的思考

**Comment by RivanLuo** [comment]
能给我链接吗？没有找到这方面的思考哦！谢谢

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues?utf8=%E2%9C%93&q=%E5%A4%9A%E6%A0%87%E7%AD%BE%E9%A1%B5

**Comment by huangshiqiang** [comment]
这个多页签的功能使用场景很多，有计划在antd pro框架中提供吗？我看很多朋友也在咨询多页签的功能。
