### ISSUE TITLE
ant 如何独立使用Pro组件，通过npm install ant-design-pro --save，发现样式有问题

### ISSUE THREAD

**Issue by wucj21** [ant-design/ant-design-pro#1936]
通过npm install ant-design-pro --save 安装后，使用HeaderSearch组件
代码如下： 
`
import HeaderSearch from 'ant-design-pro/lib/HeaderSearch';
<HeaderSearch
            placeholder="站内搜索"
            dataSource={['搜索提示一', '搜索提示二', '搜索提示三']}
            onSearch={(value) => {
              console.log('input', value); // eslint-disable-line
            }}
            onPressEnter={(value) => {
              console.log('enter', value); // eslint-disable-line
            }}
          />
`
展示的效果如下：
![image](https://user-images.githubusercontent.com/25993934/43385458-6399b994-9413-11e8-8911-d161f5753739.png)

**Comment by chenshuai2144** [comment]
你的版本是？ pro 的版本？

**Comment by wucj21** [comment]
@chenshuai2144  我使用的antd，通过npm install ant-design-pro --save 下载的 pro组件，独立使用组件的时候无效

**Comment by afc163** [comment]
https://pro.ant.design/docs/use-components-alone-cn

**Comment by wucj21** [comment]
@afc163 我是按照官方引入的，可否指导一下
![image](https://user-images.githubusercontent.com/25993934/43448003-59915688-94df-11e8-8785-9b100d10c3db.png)怎么引入呢

**Comment by chenshuai2144** [comment]
你使用的pro 版本是多少？

**Comment by wucj21** [comment]
@chenshuai2144 "ant-design-pro": "^2.0.0-beta.2",

**Comment by chenshuai2144** [comment]
那就都用 beta 试试！
https://beta.pro.ant.design/docs/use-components-alone-cn
试试按需加载
