### ISSUE TITLE
ant design pro打包后发布地址和接口调用地址不是一个，请求数据报404

### ISSUE THREAD

**Issue by xiangpitang** [ant-design/ant-design-pro#1938]
打包上传之后，登录页面调取接口， 报404错误，调用接口地址后面多了一个api，是为什么

**Comment by chenshuai2144** [comment]
默认使用的就是 api！

**Comment by xiangpitang** [comment]
但是接口调用路径是https://ryjf.*****.top/api/cms/rule,这样路径就报404，后台接口中没有这个api，这个要怎么修改

**Comment by xiangpitang** [comment]
现在是后台请求接口是在https://www.*****.store这个地址，但是上传的地址是在https://ryjf.*****.top，现在怎么将这个后台的接口内容代理到这个上传地址里呢？我看文档写在.webpackrc.js里配置publicPath: 'https://ryjf.*****.top',但是没什么用，我这个要怎么修改呢

**Comment by xiaosusyc** [comment]
同样遇到这样的问题，Api的地址，和打包上线请求的地址不一致，代理都不行，很奇怪，求解答

**Comment by xiangpitang** [comment]
这个问题解决了，是因为前台写的代理，但是也需要后台配置一个代理，前后台都把代理配置在同一个地址就可以得到数据了

**Comment by cindyZhang4** [comment]
> 这个问题解决了，是因为前台写的代理，但是也需要后台配置一个代理，前后台都把代理配置在同一个地址就可以得到数据了

请问后台代理是怎么配置的？
