### ISSUE TITLE
修改 .roadhogrc.mock.js 后请求没能指向真实服务器

### ISSUE THREAD

**Issue by xiaoNiuNew** [ant-design/ant-design-pro#194]
按官网教程修改了.roadhogrc.mock.js的export部分。修改为
`export default {
  'GET /api/*': 'http://localhost:62078/',
};`
但重新启动网站或者刷新页面，从chrome里看到的请求依然是
`http://localhost:8000/api/xxxx` 并返回400错误
前端新手，若是低级错误请见谅

**Comment by xiaoNiuNew** [comment]
是在windows下

**Comment by Rocky1073** [comment]
用start:no-proxy启动

**Comment by Molloh** [comment]
+1 遇到了同样的问题，用start:no-proxy 启动也无法解决

**Comment by xiaoNiuNew** [comment]
通过验证，linux下是正常的，只是用firefox的监视工具看到的地址还是localhost:8000。win下也许真的有问题

**Comment by happyhuizai** [comment]
+1

**Comment by Gjb7598189** [comment]
+1

**Comment by JinfengZhang** [comment]
遇到同样的问题，linux下ok，Windows下无效

**Comment by yesmeck** [comment]
@xiaoNiuNew  你没理解这个 proxy 的意思，这个 proxy 是反向代理。

> `export default { 'GET /api/*': 'http://localhost:62078/', };`

这条规则的意思是说前端访问 `http://localhost:8000/api/*` 的时候，本地的开发服务器会去代理访问 `http://localhost:62078/api/*`，所以你在浏览器看到的请求还是看到的 `http://localhost:8000/api/*` 是正确的。

windows 不生效的问题建议反馈到 https://github.com/sorrycc/roadhog/issues

**Comment by xiaoNiuNew** [comment]
理解了

**Comment by jayguojianhai** [comment]
npm start:no-proxy 启动失败
![image](https://user-images.githubusercontent.com/15603321/34557128-31139766-f174-11e7-9c0d-a633b142ea90.png)

**Comment by jayguojianhai** [comment]
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/jayguo/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.5.1 /usr/local/lib/node_modules/npm

**Comment by afc163** [comment]
`npm run start:no-proxy`

**Comment by jayguojianhai** [comment]
@afc163 谢谢

**Comment by mushroomlb** [comment]
https://pro.ant.design/docs/server-cn
