### ISSUE TITLE
运行报错 × ReferenceError: rollbar is not defined ？？

### ISSUE THREAD

**Issue by Christydeng** [ant-design/ant-design-pro#1940]

**Comment by chenshuai2144** [comment]
index.ejs 里面引入的

**Comment by Christydeng** [comment]
另外想问个问题， 就是跑了命令npm run-script build 后， 生成的js和css文件是不是都只有一个
@chenshuai2144

**Comment by Christydeng** [comment]
代码这样不是在最前面引入用吗
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ant Design Pro</title>
  <link rel="icon" href="/favicon.png" type="image/x-icon">
  <script src="https://cdn.bootcss.com/rollbar.js/2.4.0/rollbar.min.js"></script>
  <script src="https://gw.alipayobjects.com/os/antv/assets/data-set/0.8.7/data-set.min.js"></script>
</head>

**Comment by chenshuai2144** [comment]
看 master分支，
没开代码分割就都是一个

**Comment by Christydeng** [comment]
不太理解代码分割是怎么分割呢
@chenshuai2144

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD
