### ISSUE TITLE
npm install need to update package version

### ISSUE THREAD

**Issue by believeZJP** [ant-design/ant-design-pro#1943]
first clone the code.

then run npm install.

a lot of packages are not in the  same version 

![_20180801110500](https://user-images.githubusercontent.com/15198091/43498716-c584893c-957a-11e8-9c43-50e76cda3fba.png)

**Comment by chenshuai2144** [comment]
upgrading babel is a very dangerous thing

**Comment by believeZJP** [comment]
so ,what can I do? just ignore this?
