### ISSUE TITLE
在request.js 文件中引入  uras这个加密插件

### ISSUE THREAD

**Issue by fx35792** [ant-design/ant-design-pro#1944]
编译不通过
`
import fetch from 'dva/fetch';
import {notification} from 'antd';
import {routerRedux} from 'dva/router';
import store from '../index';
import config from '../../config/index'
// import CryptoJS from 'crypto-js';
import ursa from 'ursa';
import crypto from 'crypto';

const rsaPubKey = ursa.createPublicKey(config.api.rsa);//调用地方
`

`
Compiled with warnings.
./node_modules/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression

./node_modules/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
`

**Comment by chenshuai2144** [comment]
循环引用？你引入的包有问题吧

**Comment by fx35792** [comment]
问题解决了
import ursa from 'ursa';
import crypto from 'crypto';

改为了
import CryptoJS from 'crypto-js';
import forge from 'node-forge';

上面两个是针对node的加密的插件
