### ISSUE TITLE
roadhog do not support 'resolve.alias' like webpack

### ISSUE THREAD

**Issue by topwood** [ant-design/ant-design-pro#195]
https://github.com/sorrycc/roadhog/issues/121

ant-design-pro项目中能否加下resolve.alias这个功能，以免在项目结构过于复杂时出现很多../../

**Comment by afc163** [comment]
可以有，起码 `components` 可以统一去掉。

**Comment by remotesc2** [comment]
sorrycc/roadhog#121 里写的，推荐使用 babel-plugin-module-resolver
