### ISSUE TITLE
生产环境，请求的服务器地址如何变成真是地址？

### ISSUE THREAD

**Issue by xiaosusyc** [ant-design/ant-design-pro#1950]
如题，求问，非常感谢

**Comment by wangyun122** [comment]
代理只有在dev模式下有用啊,你npm start的时候其实起了一个express的服务器，你build之后就只是一些静态文件,你要自己用nginx代理。

**Comment by chenshuai2144** [comment]
https://github.com/chenshuai2144/pro-server
