### ISSUE TITLE
npm run test 报错

### ISSUE THREAD

**Issue by qeeleilei** [ant-design/ant-design-pro#1951]
# 描述

按照官网提供的 `使用命令行工具` 方式进行了安装，然后进入项目目录执行 `npm run test` 命令时报错。

![2018-08-01 4 46 47](https://user-images.githubusercontent.com/31684176/43513631-d6824644-95b0-11e8-967b-0988dba5f81e.png)

# 环境

- Ant Design Pro: 1.3.0

- OS: macOS Sierra 10.12.6

- Node: 8.10.0

- NPM: 5.6.0

**Comment by chenshuai2144** [comment]
需要先启动项目

**Comment by qeeleilei** [comment]
感谢答复，在启动项目之后运行 `npm run test` 时也会报这些错误，并且运行 `npm run test:component` 和 `npm run test:all` 都没有报错 @chenshuai2144

**Comment by afc163** [comment]
https://pro.ant.design/docs/ui-test-cn#%E8%BF%90%E8%A1%8C%E7%94%A8%E4%BE%8B

<img width="686" alt="image" src="https://user-images.githubusercontent.com/507615/43946484-f7214040-9cb7-11e8-9300-667ffb119429.png">
