### ISSUE TITLE
Ability to use Cascader in HeaderSearch instead of AutoComplete

### ISSUE THREAD

**Issue by salarzobir** [ant-design/ant-design-pro#1953]
I want to use Cascader instead of AutoComplete in HeaderSearch, but cannt change it easily.

My scenario is: 

1. When user selects item from Cascader popup i will submit Cascader value to my search api.
2. If user start typing not numeric in Cascader i will use showSearch prop and search in items.
3. If user start typing numbers i will not show popup and i will submit the text value written in Cascader's input element to api.

Can you help me for this please?

**Comment by chenshuai2144** [comment]
Please go to antd to ask
