### ISSUE TITLE
使用Trend组件配置reverseColor属性时报错

### ISSUE THREAD

**Issue by xieww** [ant-design/ant-design-pro#1954]
报错信息如下所示：![23e61783-ea3a-4cf6-ba2e-891d11507d83](https://user-images.githubusercontent.com/26969239/43560684-447c9150-9646-11e8-964d-5cbf5779a976.png)

环境
Ant Design Pro: 1.3.0

OS: macOS Sierra 10.13.5

Node: 10.2.1

NPM: 6.1.0

**Comment by xieww** [comment]
代码如下
    switch (types) {
      case '已解决':
        upOrDownItem = <Trend flag="up" reverseColor >{data.workOrderId}</Trend>
        break;
      default:
        upOrDownItem = <Trend flag="up">{data.workOrderId}</Trend>
    }
    return upOrDownItem;

错误信息：
Warning: React does not recognize the `reverseColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `reversecolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Trend)
    in Trend (created by TableCell)
    in td (created by TableCell)
    in TableCell (created by TableRow)
    in tr (created by BodyRow)
    in BodyRow (created by TableRow)
    in TableRow (created by Connect(TableRow))
    in Connect(TableRow) (created by ExpandableRow)
    in ExpandableRow (created by Connect(ExpandableRow))
    in Connect(ExpandableRow) (created by BaseTable)
    in tbody (created by BaseTable)
    in table (created by BaseTable)
    in BaseTable (created by Connect(BaseTable))
    in Connect(BaseTable) (created by BodyTable)
    in div (created by BodyTable)
    in BodyTable (created by ExpandableTable)
    in div (created by ExpandableTable)
    in div (created by ExpandableTable)
    in ExpandableTable (created by Connect(ExpandableTable))
    in Connect(ExpandableTable) (created by Table)
    in Provider (created by Table)
    in Table (created by LocaleReceiver)
    in LocaleReceiver (created by Table)
    in div (created by Spin)
    in AnimateChild (created by Animate)
    in div (created by Animate)
    in Animate (created by Spin)
    in Spin (created by Table)

**Comment by chenshuai2144** [comment]
你可能需要同步一下代码了，这个是后来加的，你可能不支持
