### ISSUE TITLE
又改版了，能不能加点注释啊，直观点，简单点

### ISSUE THREAD

**Issue by zl612** [ant-design/ant-design-pro#196]

**Comment by afc163** [comment]
@WhatAKitty

**Comment by afc163** [comment]
我们增加了动态路由，这样项目性能和可扩展性都会更好。https://github.com/ant-design/ant-design-pro/pull/150 #184

欢迎来帮忙优化代码结构。

**Comment by WhatAKitty** [comment]
@afc163 我等会吧文档修改下
