### ISSUE TITLE
Unable to customize the Captcha button of Login component??

### ISSUE THREAD

**Issue by foubei** [ant-design/ant-design-pro#1960]
Hello **Antd** Team,

Is there anyway to change the **Captcha** button value (_获取验证码_) of the **Login** component? If not, do you consider customize it for the next release?

Best Regards,
Fouzi Tahir
[**Dznova**](http://dznova.com/)

**Comment by chenshuai2144** [comment]
yes!
I will pay attention to this

**Comment by foubei** [comment]
Thank for your reply. Do you have any date for next release including this feature?

**Comment by chenshuai2144** [comment]
Are you using the components?

**Comment by foubei** [comment]
Yes, using the latest version **2.0.0-beta.2**

**Comment by chenshuai2144** [comment]
you can use 1.4.0
https://github.com/ant-design/ant-design-pro/commit/189e6c5c599b1cf23570d15b016704ec36793056

**Comment by chenshuai2144** [comment]
you can use 1.4.0
