### ISSUE TITLE
node包已经安装完了，npm start报错

### ISSUE THREAD

**Issue by oooofeiger** [ant-design/ant-design-pro#1965]
报错信息：
D:\fabric-explorer>npm start
'CALL "D:\node\\node.exe" "D:\node\\node_modules\npm\bin\npm-cli.js" prefix -g' 不是内部或外部命令，
也不是可运行的程序
或批处理文件。

> ant-design-pro@1.3.0 start D:\fabric-explorer
> cross-env ESLINT=none roadhog dev

npm ERR! file C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools
npm ERR! path C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools
npm ERR! ant-design-pro@1.3.0 start: `cross-env ESLINT=none roadhog dev`
npm ERR! spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools ENOENT
npm ERR!
npm ERR! Failed at the ant-design-pro@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\node\node_modules\npm\node_cache\_logs\2018-08-03T10_02_21_110Z-debug.log

求助这是什么情况？

**Comment by oooofeiger** [comment]
日志信息：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node\\node.exe',
1 verbose cli   'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ant-design-pro@1.3.0~prestart: ant-design-pro@1.3.0
6 info lifecycle ant-design-pro@1.3.0~start: ant-design-pro@1.3.0
7 verbose lifecycle ant-design-pro@1.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@1.3.0~start: PATH: D:\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\fabric-explorer\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;%JAVA_HOME%\bin;D:\apache-tomcat-9.0.0.M4\bin;D:\work\apache-maven-3.3.9\bin;C:\Python27;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;D:\Program Files\Git\cmd;D:\Program Files\Microsoft VS Code\bin;D:\node\node.exe;D:\node\;C:\Program Files\Bandizip\;D:\node;C:\Users\dev2\AppData\Roaming\npm
9 verbose lifecycle ant-design-pro@1.3.0~start: CWD: D:\fabric-explorer
10 silly lifecycle ant-design-pro@1.3.0~start: Args: [ '/d /s /c', 'cross-env ESLINT=none roadhog dev' ]
11 info lifecycle ant-design-pro@1.3.0~start: Failed to exec start script
12 silly lifecycle ant-design-pro@1.3.0~start: Returned: code: -4058  signal: null
13 info lifecycle ant-design-pro@1.3.0~start: Failed to exec start script
14 verbose stack Error: ant-design-pro@1.3.0 start: `cross-env ESLINT=none roadhog dev`
14 verbose stack spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools ENOENT
14 verbose stack     at _errnoException (util.js:992:11)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
14 verbose stack     at onErrorNT (internal/child_process.js:372:16)
14 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
14 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
15 verbose pkgid ant-design-pro@1.3.0
16 verbose cwd D:\fabric-explorer
17 verbose Windows_NT 6.1.7601
18 verbose argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.11.3
20 verbose npm  v5.6.0
21 error file C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools
22 error path C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools
23 error code ELIFECYCLE
24 error errno ENOENT
25 error syscall spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools
26 error ant-design-pro@1.3.0 start: `cross-env ESLINT=none roadhog dev`
26 error spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools ENOENT
27 error Failed at the ant-design-pro@1.3.0 start script.
27 error This is probably not a problem with npm. There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by suosuoshigesuosuo** [comment]
+1

**Comment by chenshuai2144** [comment]
用 cnpm 重装一般就会解决

**Comment by oooofeiger** [comment]
@chenshuai2144 cnpm install报错信息：
puppeteer@^1.4.0 optional error: Error: spawn C:\Windows\system32\cmd.exe;C:\Use
ld-tools ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)；

然后我cnpm install puppeteer@latest又报如下错误 ：
Error: post install error, please remove node_modules before retry!
spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

之前也删掉过node_modules包重新安装过但是仍有报错。现在重新删除再cnpm install一次报错如下：
puppeteer@^1.4.0 optional error: Error: spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-bui
ld-tools ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
× Install fail! Error: post install error, please remove node_modules before retry!
spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools ENOENT
Error: post install error, please remove node_modules before retry!
spawn C:\Windows\system32\cmd.exe;C:\Users\dev2\.windows-build-tools ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

如果我npm install puppeteer@latest -d错误又不一样：
npm ERR! enoent ENOENT: no such file or directory, access 'D:\fabric-explorer\node_modules\extract-z
ip\node_modules\debug'
我在该路径下找到了这个文件夹，有完全控制的权限，不知道为什么报这个错误
![image](https://user-images.githubusercontent.com/19513353/43717786-302ab6a0-99bb-11e8-813d-bb78219b1dac.png)

吐血求助。。。

**Comment by oooofeiger** [comment]
@chenshuai2144 感谢回复，但应该不是这个原因，我直接重装系统了，不想折腾了，然后一切正常了
