### ISSUE TITLE
带参数的菜单实现

### ISSUE THREAD

**Issue by cindyZhang4** [ant-design/ant-design-pro#1967]
<img width="862" alt="default" src="https://user-images.githubusercontent.com/35737417/43701356-7f19c0cc-9988-11e8-8d02-7a75153ded3a.png">

如图，需求是这样的菜单是从后台动态取得指向的页面是一个，点击菜单根据参数决定页面内容，菜鸟一只，想知道怎么才能将菜单路由加上参数呢？

**Comment by chenshuai2144** [comment]
你可以直接把 meunitem 的事件可以处理了，默认是 跳页，你可以用 js 控制

**Comment by cindyZhang4** [comment]
ok，谢谢大佬~

**Comment by tyyzqmf** [comment]
@cindyZhang4 怎么实现的？
