### ISSUE TITLE
Import default g2 config in components/charts

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#197]
https://github.com/ant-design/ant-design-pro/blob/master/src/g2.js

**Comment by lvjzijin** [comment]
html文件引入g2的加载时间很长，采用延迟加仍然很慢，有没有好的办法啊

**Comment by nikogu** [comment]
抽离 g2 默认配置到图表组件中，如果用户需要根据自己的业务定制，可以直接用 `Bizcharts` 的 `setTheme`
