### ISSUE TITLE
关于跨项目url传参query string，有解决办法吗？

### ISSUE THREAD

**Issue by ceser-x** [ant-design/ant-design-pro#1974]
遇到一个跨项目的问题，比如说我在项目a中跳转至项目b，www.a.com-->www.b.com。但是我想带个url参数所以跳转过来是window.location.href=“www.b.com?from=a”
但是路由配置生效后，url变成了www.b.com/?from/#/index/page。这个样子。我期望querystring放在后面，需要怎么做呢？

**Comment by ceser-x** [comment]
找到了一种临时解决的办法，知道要跳转的路由是，可以精确的跳转到对应路由上，再在后面拼参数
`window.location.href="www.b.com/#/index/page?from=a"`
但是有没有更好的方式呢？

**Comment by chenshuai2144** [comment]
```
this.props.dispatch(
      routerRedux.push({
        pathname: path + '/performance/data',
        search: querystring.stringify({
          ObRegionGroup: 'all',
          ObRegion: name,
          ObServer: 'all',
        }),
      })
    );
```
