### ISSUE TITLE
 刚刚使用了以下1.4.4版本 报错了

### ISSUE THREAD

**Issue by zimskybo** [ant-design/ant-design-pro#1977]
./node_modules/ant-design-pro/es/Charts/Pie/index.js
Module parse failed: Unexpected character '@' (14:0)
You may need an appropriate loader to handle this file type.
| 
| /* eslint react/no-danger:0 */
| @autoHeight()
| export default class Pie extends Component {
|   state = {

请问如何解决

**Comment by chenshuai2144** [comment]
不要使用es 目录，es 下面的代码没有编译。使用 lib
