### ISSUE TITLE
点击按钮查询并将结果渲染到弹窗

### ISSUE THREAD

**Issue by ak47wyh** [ant-design/ant-design-pro#1978]
如下图所示
1.点击对应位置按钮无法实现获取数据并渲染到弹窗操作
2.参考文档未找到实现方法
![image](https://user-images.githubusercontent.com/10624817/43875047-a281e8d8-9bc1-11e8-9c04-2b9768dafc8f.png)

**Comment by afc163** [comment]
建议去 stackoverflow 或者 segmentfault 提问。
