### ISSUE TITLE
菜单栏异步获取后，如何让common/router.js 可以获取menuData

### ISSUE THREAD

**Issue by kateli** [ant-design/ant-design-pro#1980]
源码中common/router.js
中是这样获取menuData的
之前是写死的menuData
换成异步获取后，这个地方该如何修改呢

![image](https://user-images.githubusercontent.com/8436428/43887363-33cfc434-9bf1-11e8-9104-cbfafe906ed0.png)

**Comment by afc163** [comment]
自行尝试，代码已经在你手里了。

**Comment by kateli** [comment]
我自己回答吧
终于解决了：
看common/router.js中，你会发现，这个文件中是把menuData和routerData进行了合并
然后再提供给router.js中的routerConfig，再提供给最外层的index.js中去进行路由注册的。
很显然，如果菜单栏数据通过接口的方式获取的话，不能按照之前demo里面的思路来了，要不然，routerData第一次获取到的数据，除了component之外，其他的都为undefined，其他页面有用到routerData的地方  都会出现预期之外的问题。
解决思路如下：
将menuData和routerDatahe合并后，再传递给其他组件
这样，其他页面可以直接通过this.props这种方式，获取到这个页面对应的任何数据
有更好的idea的小伙伴，欢迎指教
![image](https://user-images.githubusercontent.com/8436428/44254988-299f3200-a237-11e8-99f3-0fa51f4798f7.png)
![image](https://user-images.githubusercontent.com/8436428/44255046-581d0d00-a237-11e8-9e4c-b92ecdc77772.png)
![image](https://user-images.githubusercontent.com/8436428/44255076-6e2acd80-a237-11e8-8501-00b0380104d3.png)
