### ISSUE TITLE
\src\components\NoticeIcon\index.d.ts TypeScript Error

### ISSUE THREAD

**Issue by thiefo** [ant-design/ant-design-pro#1981]
old (1.4.1 version)

```javascript
import React from 'react';
```
error:
Build:Module '"/node_modules/@types/react/index"' has no default export.

change:

```javascript
 import * as React from 'react';
```

working :+1:

**Comment by chenshuai2144** [comment]
You can use  `allowSyntheticDefaultImports ` it first, waiting for us to send the version.
