### ISSUE TITLE
PageHeader 不能重新渲染

### ISSUE THREAD

**Issue by huang6349** [ant-design/ant-design-pro#1982]
我正在使用 Antd 和 Antd Pro 拓展一个管理系统布局组件，组件中涉及到页面内容面包屑自动匹配的功能，我使用了PageHeader作为页头组件，当路由发生了变化了以后，我发现PageHeader不能重新渲染，页头中的面包屑没有发生变化，我试着打印了我的loaction的值，确定了location的值是发生了变化的。后来我又试着把管理系统布局组件 link 到了一个真实的项目中去，如果，我将PageHeader放在全局布局中，PageHeader是不会重新渲染的，但是我将PageHeader放到路由界面中去，PageHeader显示的就是根据路由生成面包屑，因为这时候是第一次渲染，location和breadcrumbNameMap都是有值的，这个问题在 pro 1.4.4 和 2.0.0-bata.4 中都存在。

[这是我的页头组件源码](https://github.com/huang6349/simple-materials-lib/blob/master/packages/manage-layout/src/Page.PageHeader.js)

[这是我的DEMO源码](https://github.com/huang6349/simple-materials-lib/blob/master/packages/manage-layout/demo/src/index.js)

**Comment by chenshuai2144** [comment]
location 是个很深的对象，react 可能没有发现他已经发生了改变，
这里有个hack 的办法。
<PageHeader tabActiveKey={Date.now()} />

**Comment by huang6349** [comment]
@chenshuai2144 非常感谢大神的帮助，问题已经解决了
