### ISSUE TITLE
请问 ant-design-pro 是用什么方式，让打包的js体积减少的。

### ISSUE THREAD

**Issue by tang-yue** [ant-design/ant-design-pro#1983]
目前我是根据 ant-design-pro 进行改装。
删除了一些文件，代码。
最近打包体积达到了650多kb， 其中发现bizcharts 这个包有170多kb，但是又不能不用。
但是你们的这个项目也是同样的用了bizchats 这个包，但打包的js体积，并没有很大。
求解方法。
现在项目遇到的主要问题是，刷新url的时候，加载页面实在是太慢了。着手优化，
请问有什么好的建议？

**Comment by chenshuai2144** [comment]
我们没有解决这个问题，只是开了 gzip

**Comment by ch-liuzhide** [comment]
> 我们没有解决这个问题，只是开了 gzip

   @@@怎么开的呀，我知道要在ngnix配置一下，昨天了解到代码中也可以配一下，我尝试了一下，没有报错，就是不知道对不对
@
```
export default config => {
  // if (process.env.NODE_ENV === 'production') {
  config.merge({
    plugins: {
      install: {
        plugin: require('uglifyjs-webpack-plugin'),
        args: [{
          sourceMap: false,
          uglifyOptions: {
            compress: {
              drop_console: true,
            },
            output: {
              beautify: false,
              comments: false,
            },
          },
        }],
      },
      compression: {
        install: {
          plugin: require('compression-webpack-plugin'),
          asset: '[path].gz[query]',
          algorithm: 'gzip',
          test: new RegExp(
            '\\.(js|css)$',    // 压缩 js 与 css
          ),
          threshold: 10240,
          minRatio: 0.8,
        },
      },
    },
}）
}
```

**Comment by AsuraZhu** [comment]
> > 我们没有解决这个问题，只是开了 gzip
> 
> gzip怎么开呢，我知道要在ngnix配置一下，昨天了解到代码中也要配一下，我尝试了一下，没有报错，就是不知道对不对@chenshuai2144
> 
> ```
> export default config => {
>   // if (process.env.NODE_ENV === 'production') {
>   config.merge({
>     plugins: {
>       install: {
>         plugin: require('uglifyjs-webpack-plugin'),
>         args: [{
>           sourceMap: false,
>           uglifyOptions: {
>             compress: {
>               drop_console: true,
>             },
>             output: {
>               beautify: false,
>               comments: false,
>             },
>           },
>         }],
>       },
>       compression: {
>         install: {
>           plugin: require('compression-webpack-plugin'),
>           asset: '[path].gz[query]',
>           algorithm: 'gzip',
>           test: new RegExp(
>             '\\.(js|css)$',    // 压缩 js 与 css
>           ),
>           threshold: 10240,
>           minRatio: 0.8,
>         },
>       },
>     },
> }）
> }
> ```
不需要的 只要nginx配置了就行了  代码不需要再额外进行gzip打包
