### ISSUE TITLE
import()参数问题

### ISSUE THREAD

**Issue by lore520** [ant-design/ant-design-pro#1984]
在抽离comm/router.js文件中的routerConfig对象到别的文件时，使用了模板字符串语法，出现了编译错误,请问怎么解决！
代码如下：
dynamicWrapper(app, models, () => import(`${component}`))

另外：若将 import(`${component}`)改为import(`../routes/${component}`)，可以载入，但终端会有一个
index.ejs问题提示：
./src/index.ejs
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

**Comment by chenshuai2144** [comment]
webpack不支持动态路径

**Comment by lore520** [comment]
明白了，感谢！
