### ISSUE TITLE
antd pro中的列表页-搜索列表-文章，articles.js如果改变List.js中的内容

### ISSUE THREAD

**Issue by bxbacn** [ant-design/ant-design-pro#1985]
比如在list.js 中的state,和 箭头函数，在头部点击某个按钮，改变state中的visible:true，就弹出一个Drawer抽屉

现在我希望在articles.js中，点击某个按钮，也弹出来，而不是在重写一次List.js中的代码

https://preview.pro.ant.design/#/list/search/articles

**Comment by chenshuai2144** [comment]
redux就是为了解决这个问题的，去了解一下
