### ISSUE TITLE
components 下组件样式 全局重写无效

### ISSUE THREAD

**Issue by HappyLeiLei** [ant-design/ant-design-pro#199]
![image](https://user-images.githubusercontent.com/25144943/32868969-8dd77800-caaf-11e7-830a-ffd58a3bfdf6.png)
![image](https://user-images.githubusercontent.com/25144943/32869171-8cd90e54-cab0-11e7-8beb-aa680c0c6e51.png)

源码中 .tableListForm  中的 ：global .ant-form-item 设置无效  只有去掉 .tableListForm 这层才生效 而且其他页面的组建也会收到影响
请问如何解决 只想重置当前页面某个模块组件默认样式 不影响其他当前页面 其他部分默认组件样式呢

**Comment by afc163** [comment]
Please make sure your issue having a readble format.

**Comment by HappyLeiLei** [comment]
@afc163 截图重传代码 其他页面组建 添加自己的styles.less 在内部直接使用：global｛｝代码会影响所有其他页面组件默认值， 如果在：global｛｝外层添加自定义class｛｝则：global｛｝内代码无效

**Comment by afc163** [comment]
http://segmentfault.com/markdown

**Comment by HappyLeiLei** [comment]
@afc163 我已经截图说明了问题现象了 为何还要让我用 md ？

**Comment by afc163** [comment]
艺多不压身，后面也用得上。

**Comment by HappyLeiLei** [comment]
**@afc163 谢谢 我会学的** 

- 我现在想知道 官方的那种写法是否可以有效的重置页面局部默认ant样式

- 官方事例中的代码测试并未生效 不知为何

**Comment by nikogu** [comment]
@HappyLeiLei 参看官方 demo 就好了，官方是正常运行样例

**Comment by HappyLeiLei** [comment]
@nikogu 官方事例中的就是无效的 所以想来问问

**Comment by nikogu** [comment]
![image](https://user-images.githubusercontent.com/1179603/32869665-33ca0248-cab3-11e7-9cc6-633e2f09a852.png)

我本地跑了下，正常的呀

**Comment by HappyLeiLei** [comment]
@nikogu 我晕了 难道是我这版本问题么。 我发布的官方版本 这段代码不生效 我去git在拉取一次 谢谢你先

**Comment by nikogu** [comment]
应该一直是好的，你是直接用的脚手架？然后改的代码不生效？还是说你是照着 pro 的写法在写，但是项目还是自己的项目？你用了 css module 吗

**Comment by afc163** [comment]
注意 tableListForm 并没有在 Modal 的外层，Modal 是会单独被提到 body 下渲染的。

**Comment by afc163** [comment]
你需要给 Modal 或 Modal 内的元素单独绑定 className。
