### ISSUE TITLE
手机端的GlabalHeader中的Dropdown有一定几率无法展开。

### ISSUE THREAD

**Issue by whyuan1976** [ant-design/ant-design-pro#1998]
使用手机访问官网的demo，右上角的Dropdown有时点击无法展开。

bug重现操作如下：
1）通过菜单进入工作台页面
2）点击面包屑上的首页连接，回到首页。
3）这时点击Dropdown菜单，无相应。

**Comment by chenshuai2144** [comment]
fixed
