### ISSUE TITLE
pro打包为什么会包含typescript，而且占了很大的体积

### ISSUE THREAD

**Issue by DrakeXiang** [ant-design/ant-design-pro#1999]
通过anaylize分析ts占了1.75m，打包出来不应该都转成es5了么

**Comment by chenshuai2144** [comment]
包含typescript？不可能的！
最大的是图标库里面的 g2

**Comment by DrakeXiang** [comment]
@chenshuai2144 真的哇，十几个页面的pro打包出来3.88m，不知道是不是正常水平
https://imgchr.com/i/PRAmuD

**Comment by chenshuai2144** [comment]
你估计打包哪里错误了，typescript 只是开发中用的而已。

**Comment by DrakeXiang** [comment]
只能先暂时这么用着了。。

**Comment by chenshuai2144** [comment]
排查一下，我们是不依赖 typpescript 的

**Comment by DrakeXiang** [comment]
@chenshuai2144 感谢。。果然搜了一下typescript，发现是一个同事的vscode在写的时候自动引入了ts的一个方法。。。
