### ISSUE TITLE
Add Rich Text Editor

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#20]
http://antd-admin.zuiidea.com/UIElement/editor

感觉这个还挺有用的，二期可以考虑加上

**Comment by afc163** [comment]
404

**Comment by viztor** [comment]
Rich Text Editor?

**Comment by zjxpcyc** [comment]
这个绝对是刚需

**Comment by chenshuai2144** [comment]
富文本编辑器是个大坑呀...
难度很大呀.但是每个项目有.
刚需

**Comment by topwood** [comment]
mark

**Comment by xiaosongxiaosong** [comment]
mark

**Comment by stduolc** [comment]
+1

**Comment by patilreena** [comment]
+1

**Comment by WhatAKitty** [comment]
* [neditor](https://github.com/notadd/neditor)
* [draftjs](https://draftjs.org/)
* [react-quill](https://github.com/zenoamaro/react-quill)

可以考虑集成这几个。

**Comment by zjxpcyc** [comment]
支持使用 quill

**Comment by 533001** [comment]
++1  确实. 非常刚需

**Comment by luopeihai** [comment]
Richtext is just needed
