### ISSUE TITLE
js 缓存问题

### ISSUE THREAD

**Issue by kkfnui** [ant-design/ant-design-pro#200]
碰到一个问题，
打包后 引用的 index.js ， js 文件更新后，很容易被中间的代理或者浏览器缓存，导致修改最终不能更新到用户。

是否可以将 index.js 、index.css 改成 index.js.{md5} 这样的命名呢？

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog#hash

**Comment by kkfnui** [comment]
多谢，现在 js 和 css 文件修改后文件名会修改了。
```
index.d912f4de.js
index.f8c84afa.css
index.html
```

但还是有个问题， index.html 引入的 文件名并未同步修改，是否有什么设置可以保持两者同步呢？

**Comment by kkfnui** [comment]
https://github.com/sorrycc/roadhog/issues/386

找到之前的讨论了，看来还是个蛮常见的问题。
为什么默认不设置成hash 的呢？

**Comment by afc163** [comment]
确实应该默认设为 hash。

**Comment by Ycheck521** [comment]
打包完设置hash后 index。html引入的文件名如何同步呢

**Comment by afc163** [comment]
Thx to @happier2 , we have hash entry now!
