### ISSUE TITLE
想问一下在antd pro 上面加载tabs 标签 如何实现

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#2001]
就好比 浏览器的tabs选项卡一样，可以记录打开的地址，我实现了一般，但是比如我现在打开的是A菜单，再打开B菜单，回来点A菜单的时候，会进行重新load A菜单的 组件，导致很卡。请问是否有办法解决。。谢谢。

**Comment by chenshuai2144** [comment]
缓存？

**Comment by xgj1988** [comment]
是的。。我不是打开左边的菜单嘛。。然后 现在是 右边的主区域就刷新了，，我想把历史打开的标签都搞一个tabs 固定在右边区域上面。。 参考地址：https://cipchk.github.io/ng-alain/

**Comment by chenshuai2144** [comment]
这样前端会很重的。而且状态不好管理

**Comment by xgj1988** [comment]
明白你的意思 但是客户要求要这个功能 而且也说得合情合理 他们要分别看几张报表对比数据。

**Comment by chenshuai2144** [comment]
那就把报表放到一个界面上好了

**Comment by afc163** [comment]
而且浏览器新 tab 打开是一样的。可预见的未来都不会做这个功能。

**Comment by xgj1988** [comment]
@afc163  嗯。这个确实可以解决，但是我们这里有个问题就是，我们是用electron 打包的。。而且我也没看到 electron 可以有多tab 的API

**Comment by afc163** [comment]
多个 browserWindow。

**Comment by xgj1988** [comment]
好吧

**Comment by ChineseGril** [comment]
在5里面可否加个这个配置，就是在页面里面，内容区域的头部加个tab标签设置，点击菜单，我们可以把子菜单的东西放在内容区的上面，这样最快速的定位，现在是找不到配置的地方
