### ISSUE TITLE
样式问题:本地开发正常显示，打包部署线上样式丢失

### ISSUE THREAD

**Issue by xieww** [ant-design/ant-design-pro#2003]
环境：
**ant-design-pro: "^2.0.0-beta.2"**
**antd: "^3.8.0",**
**macOS 10.13.6**

**图1：**![a2a9e6ff-1ffd-414e-acb6-d3cfb224dcc4](https://user-images.githubusercontent.com/26969239/44194208-dd38f100-a167-11e8-8958-33f66543e6d5.png)

**图2：**
![44194328-3b65d400-a168-11e8-8a32-6d00ae5e5340](https://user-images.githubusercontent.com/26969239/44199225-19734e00-a176-11e8-92d7-21ab045f6604.png)

**代码:**
<img width="948" alt="6485cb30-01f5-455f-b7f6-fc8ace85cf78" src="https://user-images.githubusercontent.com/26969239/44194707-67ce2000-a169-11e8-8205-78774eee8634.png">

```
        <Row gutter={{ md: 6, lg: 24, xl: 48 }}>
          <Col md={6} sm={24}>
            <FormItem label="公司名称/名称">
              {getFieldDecorator('companyName')(<Input placeholder="请输入名称"  />)}
            </FormItem>
          </Col>
          <Col md={6} sm={24}>
            <FormItem label="时间范围">
              {getFieldDecorator('datePeriod',{initialValue: ''})(
                <Select placeholder="请选择时间范围" style={{width: '100%'}}>
                  {
                    TimeLimit.map(item => (
                      <Option key={item.key} value={item.key}>{item.value}</Option>
                    ))
                  }
                </Select>
              )}
            </FormItem>
          </Col>
          <Col md={6} sm={24}>
            <FormItem label="状态">
              {getFieldDecorator('issueState')(
                <Select placeholder="请选择状态" style={{ width: '100%' }}>
                  {
                    WorkOrderStatus.map(item => (
                      <Option key={item.key} value={item.key}>{item.value}</Option>
                    ))
                  }
                </Select>
              )}
            </FormItem>
          </Col>
```

线上环境的搜索栏下拉选择框样式丢失，页设置<select>标签width为‘100%’，本地开发样式没有问题，打包之后样式丢失，这个问题在其他页面也存在。

**请问这个问题可能是什么原因导致的？**

**Comment by chenshuai2144** [comment]
比对一下 css 就能知道

**Comment by Apa7-zero** [comment]
老哥3年了解决了么，我也遇到了

**Comment by 12914hh** [comment]
4年了 。。解决了吗  大佬们！！！

**Comment by Apa7-zero** [comment]
> 4年了 。。解决了吗 大佬们！！！

换个博客工具吧，这个完成度太低了

**Comment by 12914hh** [comment]
> > 4年了 。。解决了吗 大佬们！！！
> 
> 换个博客工具吧，这个完成度太低了
啥意思。。。   这个不是阿里搞的么

**Comment by Apa7-zero** [comment]
> > > 4年了 。。解决了吗 大佬们！！！
> > 
> > 
> > 换个博客工具吧，这个完成度太低了
> > 啥意思。。。   这个不是阿里搞的么

不好意思，看错项目了。贼尴尬

**Comment by chenyu1990** [comment]
我也遇到这个问题，打包后，各种漏东西，有的还不知道漏了啥。比如我本地可以切换暗黑模式，线上切换了，只有小部分组件变。调试都不知道如何下手。
