### ISSUE TITLE
v2 documentation upgrade

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#2007]
v2的发布含苞欲出，但是文档工作还没有展开，是时候认领一波了

* 入门
    * [x] 开始使用(@yutingzhao1991)
    * [x] 开始使用（蚂蚁金服用户）(@zinkey)
    * [x] 布局（@afc163）https://github.com/ant-design/ant-design-pro-site/pull/197
    * [x] 路由和菜单（@chenshuai2144）
    * [x] 新增页面（@yutingzhao1991）
    * [x] 新增业务组件（@zombieJ）
* 样式
    * [x] 和服务端进行交互 （@yesmeck）
    * [x] 构建和发布（@yesmeck）
    * [x] 引入外部模块（@sorrycc）https://github.com/ant-design/ant-design-pro-site/pull/189
* 进阶
    * [x] 图表（@zombieJ）
    * [x] 业务图标  (@HeskeyBaozi)
    * [x] Mock 和联调（@sorrycc）
    * [x] 国际化（@chenshuai2144）
    * [x] 更换主题 (@chenshuai2144)
    * [x] UI 测试 (@sorrycc)
    * [x] 独立使用 Pro 组件(@chenshuai2144)
    * [x] 错误处理 (@chenshuai2144)
    * [x] 使用 CLI 工具（@sorrycc）https://github.com/ant-design/ant-design-pro-site/pull/189
    * [x] 权限管理 (@afc163) https://github.com/ant-design/ant-design-pro-site/pull/197
* [x] 升级文档 (@yutingzhao1991)
* [x] 发布软文 （@chenshuai2144）

**Comment by afc163** [comment]
直接分配吧。

**Comment by robert-claypool** [comment]
I cannot find a v2 roadmap. How many weeks (estimated) until completion?

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/717 @robert-claypool

**Comment by chenshuai2144** [comment]
大家提交到这个分支吧
https://github.com/ant-design/ant-design-pro-site/tree/beta

**Comment by yutingzhao1991** [comment]
@chenshuai2144 所有的 PR 都提到 beta 分支吗？还是说只是文档。

**Comment by chenshuai2144** [comment]
这个是文档的 pr

**Comment by afc163** [comment]
我已经在写了。https://github.com/ant-design/ant-design-pro-site/pull/197/files

**Comment by afc163** [comment]
All done! https://medium.com/ant-design/beautiful-and-powerful-ant-design-pro-2-0-release-51358da5af95
