### ISSUE TITLE
去掉url 里面的#以后 直接复制访问会进入404页面，怎么防止这

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design-pro#2010]
去掉url 里面的#以后 直接复制访问会进入404页面，怎么防止这种情况发生。

**Comment by ynnyh** [comment]
先看官方文档，路由分为hashHistory和browserHistory,去了解一下吧

**Comment by steem** [comment]
根据自己的业务逻辑要求，访问"/"时，全局model初始化后，跳转到其他页面。可参考https://github.com/steem/qwp-antd-pro/blob/master/src/models/main.js，由服务器端指定访问"/"时自动跳转到相应的页面

**Comment by MinHongwei** [comment]
@steem  你这个页面也是404.。。

**Comment by MinHongwei** [comment]
@ynnyh  谢谢指点。
