### ISSUE TITLE
局域网部署失败，有外链网络

### ISSUE THREAD

**Issue by prefectLee** [ant-design/ant-design-pro#2011]
在src/index.ejs中引入了
<script src="https://cdn.bootcss.com/rollbar.js/2.4.0/rollbar.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/data-set/0.8.7/data-set.min.js"></script>
等第三方网络资源，在局域网部署时引发rollbar定义失败问题，请问Ant Design Pro是否支持离线开发部署。

**Comment by MinHongwei** [comment]
这个很简单  你把他们去了，把 rollbar.js的引用注调，

**Comment by MinHongwei** [comment]
src/index,js 里面的 import './rollbar';

**Comment by prefectLee** [comment]
<script src="../node_modules/rollbar/dist/rollbar.min.js"></script>
<script src="../node_modules/@antv/data-set/dist/data-set.min.js"></script>
我把引用改成成node_modules中对应的js就可以了，
谢谢你的回复。
