### ISSUE TITLE
配置主题icon-url后 引用无效。。。或者是我不会引用

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design-pro#2013]
我已经参考了 https://github.com/vision8tech/dvajs-user-dashboard/pull/2
http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8cf4382a&helptype=code
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

我的theme.js配置 
// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
module.exports = {
  // 'primary-color': '#10e99b',
  'card-actions-background': '#f5f8fa',
  'icon-url': '"https://at.alicdn.com/t/font_717533_2yiz9xidgt1"',
};
我的图标引用测试。
import React, { Component } from 'react';
import { Icon } from 'antd';
import styles from './index.less';

export default class app extends Component {
  render() {
    return (
      <div>
        <font className={styles.test} >asdasdadd</font>
        <Icon type="tongzhi" />
        <Icon type="#icon-tongzhi" />
        <i className="iconfont icon-tongzhi" />
        111
        <svg className={styles.icon} aria-hidden="true">
          <use xlinkHref="#icon-tongzhi" />
        </svg>
        <Icon type="delete" />
      </div>
    );
  }
}

结果是一个图标都没有在页面出现、 我还是没能发现自己家的错误。 我能确定 配置的icon-url页面是有加载的，我通过 notwork 查看到了他

**Comment by MinHongwei** [comment]
因为 我的图标测试发出来  会被git翻译。所有我将他们注释了 
import React, { Component } from 'react';
import { Icon } from 'antd';
import styles from './index.less';

export default class app extends Component {
  render() {
    return (
      // <div>
      //   <font className={styles.test} >asdasdadd</font>
      //   <Icon type="tongzhi" />
      //   <Icon type="#icon-tongzhi" />
      //   <i className="iconfont icon-tongzhi" />
      //   111
      //   <svg className={styles.icon} aria-hidden="true">
      //     <use xlinkHref="#icon-tongzhi" />
      //   </svg>
      //   <Icon type="delete" />
      // </div>
    );
  }
}

**Comment by MinHongwei** [comment]
https://codesandbox.io/s/r1yzqkj52o

**Comment by afc163** [comment]
Please learn markdown format first. https://segmentfault.com/markdown

**Comment by MinHongwei** [comment]
`import React, { Component } from 'react';
import { Icon } from 'antd';
import styles from './index.less';

export default class app extends Component {
  render() {
    return (
      <div>
        <font className={styles.test} >asdasdadd</font>
        <Icon type="tongzhi" />
        <Icon type="#icon-tongzhi" />
        <i className="iconfont icon-tongzhi" />
        111
        <svg className={styles.icon} aria-hidden="true">
          <use xlinkHref="#icon-tongzhi" />
        </svg>
        <Icon type="delete" />
      </div>
    );
  }
}
`
@afc163  Thank you very much for your introduction

**Comment by MinHongwei** [comment]
`import React, { Component } from 'react';
import { Icon } from 'antd';
import styles from './index.less';

export default class app extends Component {
  render() {
    return (
      [<div>
        <font className={styles.test} >asdasdadd</font>
        <Icon type="tongzhi" />
        <Icon type="#icon-tongzhi" />
        <i className="iconfont icon-tongzhi" />
        111
        <svg className={styles.icon} aria-hidden="true">
          <use xlinkHref="#icon-tongzhi" />
        </svg>
        <Icon type="delete" />
      </div>]
    );
  }
}
`

**Comment by MinHongwei** [comment]
`import React, { Component } from 'react';
import { Icon } from 'antd';
import styles from './index.less';

export default class app extends Component {
  render() {
    return (
```
      <div>
        <font className={styles.test} >asdasdadd</font>
        <Icon type="tongzhi" />
        <Icon type="#icon-tongzhi" />
        <i className="iconfont icon-tongzhi" />
        111
        <svg className={styles.icon} aria-hidden="true">
          <use xlinkHref="#icon-tongzhi" />
        </svg>
        <Icon type="delete" />
      </div>
```
    );
  }
}
`

**Comment by MinHongwei** [comment]
```
.icon {
  width: 1em; height: 1em;
  vertical-align: -0.15em;
  fill: currentColor;
  overflow: hidden;
}

.test {
  color: red;
}
```
