### ISSUE TITLE
Support ant-design-pro.d.ts please

### ISSUE THREAD

**Issue by andycall** [ant-design/ant-design-pro#202]
Please provide .d.ts files for typescript users

**Comment by afc163** [comment]
Did you mean the usage of `import Xxx from 'ant-design-pro/lib/Xxx'`?

**Comment by nikogu** [comment]
@chenshuai2144 take a look

**Comment by chenshuai2144** [comment]
我已经提交了你们含有文档组建的d.ts. 
现在是需要提供
import Xxx from 'ant-design-pro/lib/Xxx' 的支持?

**Comment by chenshuai2144** [comment]
@nikogu  全部组件都支持 style 属性?
