### ISSUE TITLE
beta 版本样式问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#2027]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/507615/44414351-2215bb00-a5a0-11e8-9d31-0f08bac95e5e.png">

切换布局后，logo 文字没了。如果是有意干掉的，menu 是不是应该向左移动一点，现在间距太大了。

**Comment by afc163** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/507615/44414446-66a15680-a5a0-11e8-8aca-e8cc9ed00677.png">

按钮直接贴住了边缘。

**Comment by afc163** [comment]
<img width="177" alt="image" src="https://user-images.githubusercontent.com/507615/44414556-a6683e00-a5a0-11e8-940d-1cc71388bad2.png">

这个感觉有点偏大了，而且左右不居中。

https://iczer.gitee.io/vue-antd-pro/#/detail/basic 这个魔改版本的就好一点。

**Comment by afc163** [comment]
favicon 没有了。

**Comment by afc163** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/507615/44414667-ee876080-a5a0-11e8-84c7-d0f6ab06137f.png">

PageHeader 对齐有问题。

**Comment by chenshuai2144** [comment]
> 这个感觉有点偏大了，而且左右不居中。

设计稿是这样的。。。。 别样的美感？

**Comment by chenshuai2144** [comment]
>  PageHeader 对齐有问题。

PageHeader默认是个通栏，不会定宽

**Comment by chenshuai2144** [comment]
感觉这样也很好看。。。 一个大大栏

**Comment by afc163** [comment]
对，主题拷贝代码那里要放一个说明链接，不然用户拷贝完都不知道粘贴到哪。

**Comment by chenshuai2144** [comment]
这个已经 ok 了！
