### ISSUE TITLE
为何没有使用dva/dynamic 配置路由呢？

### ISSUE THREAD

**Issue by Yunfly** [ant-design/ant-design-pro#203]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/pull/150

先问是不是，再问为什么。

**Comment by Yunfly** [comment]
额，没有看到昨天的版本更新了这个，还是沿用的之前的

**Comment by mgcnrx11** [comment]
FYI: upgrade from 0.2.2,  have to yarn upgrade dva to 2.1.0, otherwise the console.error

```
TypeError: _dynamic2.default.setDefaultLoadingComponent is not a function
```
