### ISSUE TITLE
Affix组件把按钮固定后，在零界点 点击的时候，位置错乱

### ISSUE THREAD

**Issue by kateli** [ant-design/ant-design-pro#2033]
这个按钮用发affix组件
![image](https://user-images.githubusercontent.com/8436428/44456113-5934ac80-a632-11e8-8dcc-22ab7fc76d39.png)
在这个临界点点击后  惊喜来了  位置跑偏了
![image](https://user-images.githubusercontent.com/8436428/44456154-6c477c80-a632-11e8-8d5c-1570670b6dfd.png)

**Comment by kateli** [comment]
折叠后，重新设置sider的宽度后，上面的问题依然存在

`<Sider 
        trigger={null} 
        className={styles.Sider} 
        collapsible 
        collapsed={collapsed} 
        collapsedWidth='40px' 
        width={collapsed ? '40px' : '200px'} 
      >`

**Comment by xiaohuoni** [comment]
@kateli 你好，这有个demo看看？怎么样算零界点
