### ISSUE TITLE
if proxy can ignore GET and POST

### ISSUE THREAD

**Issue by believeZJP** [ant-design/ant-design-pro#2035]
![image](https://user-images.githubusercontent.com/15198091/44467826-74b1ae80-a656-11e8-98ac-c24517862dc3.png)
 

when proxy for real server, the interface is support GET and POST. why GET and POST can't ignore?

**Comment by chenshuai2144** [comment]
can be ignore

**Comment by chenshuai2144** [comment]
可省略 == can be ignored

**Comment by believeZJP** [comment]
The fact is it can't ignore.

**Comment by chenshuai2144** [comment]
Try to delete it
`export default (noProxy ? {} : delay(proxy, 1000));`

**Comment by believeZJP** [comment]
If remove this, export what?
```javascript
esport default realProxy;
```
![image](https://user-images.githubusercontent.com/15198091/44708583-182d1400-aada-11e8-92c6-a677c5b32552.png)

It's not working.
