### ISSUE TITLE
v2 service work 本地调试报错

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-pro#2038]
![image](https://user-images.githubusercontent.com/1061968/44504682-8daa7600-a6cf-11e8-8197-be7795dd099e.png)

返回了 html

**Comment by chenshuai2144** [comment]
umi 暂时好像不错了。删掉这个吧

**Comment by afc163** [comment]
没必要删掉吧。

**Comment by chenshuai2144** [comment]
v2中已删除
