### ISSUE TITLE
重新npm install出错 

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#2040]
![image](https://user-images.githubusercontent.com/7875572/44506645-f26ace00-a6d9-11e8-8274-fc244381e0c4.png)
![image](https://user-images.githubusercontent.com/7875572/44506651-f991dc00-a6d9-11e8-911a-f866be6e3007.png)
![image](https://user-images.githubusercontent.com/7875572/44506783-86d53080-a6da-11e8-8f39-e67755c7a2e8.png)

**Comment by drduan** [comment]
猜想是 roadhog 出问题了   所以代理转发请求这样

**Comment by drduan** [comment]
版本  2.4.5

**Comment by drduan** [comment]
@yesmeck 应该是编辑修改 roadhog文件 有一定几率 重现

**Comment by ybning** [comment]
#2054   
我也遇到了这个问题

**Comment by ybning** [comment]
@drduan 
https://github.com/ant-design/ant-design-pro/issues/2043#issuecomment-416822570
