### ISSUE TITLE
右侧显示区域，根据内容显示横向滚动条？

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#2042]

**Comment by koupeng** [comment]
![image](https://user-images.githubusercontent.com/6110684/44514126-d541f980-a6f1-11e8-85c6-8761efded191.png)

**Comment by koupeng** [comment]
如上图，内容区域使用了Table。列较多，我设置了scroll={{x:3000,y:500}}  但是这样会出现三个滚动条。使用起来不友好。

**Comment by chenshuai2144** [comment]
简单的使用问题。
复习一下盒模型好了

**Comment by Wmstone** [comment]
@koupeng 有什么好的方法么？
