### ISSUE TITLE
The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.

### ISSUE THREAD

**Issue by jinzita007** [ant-design/ant-design-pro#2043]
当npm start的时候不能启动完成后会自动打开浏览器访问，后来报错的是The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
怎么解决报错信息呢？

**Comment by chenshuai2144** [comment]
目测是babel的问题 
cnpm试一试

**Comment by jinzita007** [comment]
@chenshuai2144 第一种是使用cnpm命令行工具有报错了，但是第二种方式直接 clone git 仓库正常打开访问的，没有报错的。

**Comment by dingzhenke** [comment]
我也遇到这种情况了，怎么解决？

**Comment by shao7936626** [comment]
我的情况和你一模一样呢

**Comment by afc163** [comment]
@dead-horse 看看？tnpm 和 cnpm 都有问题，npm 是好的，pro 的 master 下载下来 install 和 start 就能重现。

**Comment by fish267** [comment]
同上, 一样的问题.
cnpm tnpm 都有报错

**Comment by ybning** [comment]
尝试使用npm安装，安装成功。但请求接口时，proxy失败：
![image](https://user-images.githubusercontent.com/3725612/44702975-6b966680-aac8-11e8-94eb-a0478617c5f3.png)

**Comment by ybning** [comment]
@afc163

**Comment by zinkey** [comment]
package.json 试试：
{
  "tnpm": {
    "mode": "npm"
  }
}

**Comment by ql434** [comment]
依赖的模块要统一锁下版本

**Comment by sorrycc** [comment]
使用 cnpm/tnpm 的可以尝试删除 stylelint，stylelint 依赖了 @babel/core@rc，和 roadhog@2.x 依赖的 @babel/core@beta 在 cnpm/tnpm 下提升依赖时有冲突。

**Comment by sorrycc** [comment]
@ql434 roadhog@2.x 依赖的 @babel 是锁了版本的。

**Comment by batistutaluke** [comment]
这个问题有明确的解决办法了吗？

**Comment by batistutaluke** [comment]
我们的环境目前只能用cnpm，这个问题可以解决吗？

**Comment by crazzyHuang** [comment]
我这里使用 npm install 也出现这个问题了

**Comment by acpplife** [comment]
同问，已尝试删除stylelint相关，安装依赖之后还是不能启动。请问有没有临时解决的方案呢？

**Comment by afc163** [comment]
看 @zinkey 的回复。

**Comment by wanliyunyan** [comment]
https://github.com/babel/babel/issues/8562

**Comment by ybning** [comment]
@sorrycc   npm install正常后的代理问题，有临时解决方案吗？

**Comment by zuwensong** [comment]
@ybning 重新npm install后，在.webpackrc.js中配置proxy才能生效，原先在.roadhogrc.mock.js中的配置方法失效。
.webpackrc.js：新增代理：
  proxy: {
    "/lesson": {
      "target": "http://localhost:8080/teach",
      "changeOrigin": true,
      "pathRewrite": {"^/lesson": ""}
    },
  },

.roadhogrc.mock.js中以前的写法：
const noProxy = true;
const apiurl="http://localhost:8080";
export default (noProxy ? {
    'GET /lesson/(.*)': apiurl+'/teach/',
    'POST /lesson/(.*)': apiurl+'/teach/',
  } : delay(proxy, 1000));

api.js：
export async function fakeAccountLogin(params) {
  return request('/lesson/manage/login', {
    method: 'POST',
    body: params,
  });
}
具体原因还未知。

**Comment by lxy224** [comment]
检查package.json中是否存在一下依赖
"stylelint"
"stylelint-config-prettier"
"stylelint-config-standard"
删除后试试

**Comment by lxy224** [comment]
检查package.json中是否存在一下依赖
"stylelint"
"stylelint-config-prettier"
"stylelint-config-standard"
删除后试试

**Comment by hexl21** [comment]
@lxy224 还是你说的对 感谢

**Comment by zgbbiao** [comment]
什么都没做， 把node_modules删除了再重新Npm i 就好了>O.0<

**Comment by jinrichardJIN** [comment]
@lxy224 删除这个没什么影响嘛？

**Comment by chenfpp** [comment]
我删除了node_modules，采用 npm i 安装之后就好了

**Comment by kateli** [comment]
我也遇到这样的问题了
npm i 的时候就已经报错了
![image](https://user-images.githubusercontent.com/8436428/44970814-e27aa600-af85-11e8-9541-5287d24d8cd7.png)

然后运行cnpm i    ok
然后运行npm  start  报错
![image](https://user-images.githubusercontent.com/8436428/44970560-e659f880-af84-11e8-99a9-27b947b6ce68.png)

怎么回事儿呢

**Comment by kateli** [comment]
已解决：
npm set registry https://registry.npmjs.org/
rm -rf node_modules/
npm cache clean --force
npm cache verify
npm install

**Comment by xct24** [comment]
尝试了将cnpm换回npm 报新的错误
```
/var/jenkins_home/workspace/bi-web/node_modules/webpack/lib/Chunk.js:829
		throw new Error("Chunk.entrypoints: Use Chunks.addGroup instead");
```

没有使用stylelint只有用eslint，而且只在devDep里

**Comment by Gamehu** [comment]
删除models之后用npm

**Comment by sorrycc** [comment]
遇到问题的朋友可以试下 `roadhog@2.5.0-beta.1`。

**Comment by ms20hj** [comment]
@lxy224 删除那三个工程直接报错了

**Comment by ms20hj** [comment]
@sorrycc 解决了，谢谢

**Comment by RanranLiu111** [comment]
我的也出现同样的问题，请问是怎么解决的

**Comment by RanranLiu111** [comment]
@sorrycc 谢谢 安装 `roadhog@2.5.0-beta.1`  后解决了

**Comment by Journey0911** [comment]
@sorrycc 安装roadhog@2.5.0-beta.1完美解决，赞一个，多谢~

**Comment by jsw0528** [comment]
唉，Basement 构建失败，原来这里这么多人遇到。。。

**Comment by 527242007** [comment]
@sorrycc perfect

**Comment by m26597** [comment]
@sorrycc @kateli EWWhen I check out the antd project and npm install, it shows:
![default](https://user-images.githubusercontent.com/39291213/46060538-4e6fb900-c196-11e8-8008-dba6ad7d9f59.png)
I've installed roadhog@2.5.0-beta.1 but it still failed@sorry
I've tried the steps,but it doesn't work@kateli

**Comment by kateli** [comment]
@m26597    先更新npm再试试
npm i -g npm

然后
npm set registry https://registry.npmjs.org/
rm -rf node_modules/
npm cache clean --force
npm cache verify
npm install

**Comment by 1232209** [comment]
这个问题貌似还没有比较好的解决方案，请大神出来解决一下

**Comment by kalaersun** [comment]
![qq 20181007130226](https://user-images.githubusercontent.com/15727904/46578358-497df580-ca31-11e8-9545-d9f165b58c87.png)
注意红色的字 这个transform是专门给babel6的
7就安装下面的

`{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
  ]
}`
这么写
`npm install`
就好了
还是要详细的看文档

**Comment by chenguihua1005** [comment]
遇到问题的朋友可以试下 roadhog@2.5.0-beta.1，亲自试了下可以解决这个问题。

**Comment by aleafo** [comment]
roadhog@2.5.0-beta.1 works for me.

**Comment by m26597** [comment]
在项目中使用roadhog@2.5.0-beta.1 测试版是不是八成要废啊，会有什么影响么@sorrycc

**Comment by wteam-xq** [comment]
> 已解决：
> npm set registry https://registry.npmjs.org/
> rm -rf node_modules/
> npm cache clean --force
> npm cache verify
> npm install

已解决：使用 cnpm 出现， 删除 node_modules 所有文件再使用 npm 重新安装依赖。

**Comment by 18011904** [comment]
我也出现了这个问题，我用官方的脚手架生成的packa.json文件里面有@babel/core和babel-core都有，只需要把babel-core卸载就可以了，用npm un babel-core

**Comment by guozhengzhongGit** [comment]
新入职公司，是用 pro 魔改的项目，里面还用什么 antd-bsc，升级以后也是报这个错误，采用上面@kateli的方法，删除了npm cache 以后，用 npm 安装就好了～

**Comment by Renee98** [comment]
@sorrycc 
👍

**Comment by lianglei-git** [comment]
> 遇到问题的朋友可以试下 `roadhog@2.5.0-beta.1`。
nice

**Comment by z494627** [comment]
删除node_modules
修改roadhog为 roadhog@2.5.0-beta.1@2.5.0-beta.1
npm i
解决
