### ISSUE TITLE
表单必填项label上的红色*号是怎么出现的？

### ISSUE THREAD

**Issue by baiyulong** [ant-design/ant-design-pro#2044]
我在 ant design的组件上看只要验证规则required：true前面就会出现红色*号，表示必填，但是 ant design pro上面的表单就不行，这个要具体怎么写吗？

**Comment by chenshuai2144** [comment]
https://ant.design/components/form-cn/#Form

```
hideRequiredMark | 隐藏所有表单项的必选标记 | Boolean | false
```

**Comment by baiyulong** [comment]
感谢，看到这标记好多次了，没明白后面的说明，现在明白了。
