### ISSUE TITLE
tags标签删除后，会出现一个空div

### ISSUE THREAD

**Issue by shunzizhan** [ant-design/ant-design-pro#2048]
在使用tags时，删掉第一个tags后，发现后面的tags会跑到第二行去，审查元素，发现是删除之后，有一个空div

[Tag标签](https://ant.design/components/tag-cn/),第一个示例，删除`Tag2`，即可复现

**Comment by chenshuai2144** [comment]
一个神奇的 bug

**Comment by chenshuai2144** [comment]
@afc163  这个修了吗？

**Comment by shunzizhan** [comment]
我暂时的做法，是给tags的标签套一个class，通过样式解决这个问题，具体源码还没去分析
```bash
.tags-bug{
		div:not(.ant-tag){
			float: left;
		}
	}
```

**Comment by afc163** [comment]
修了的会关掉的。

**Comment by shunzizhan** [comment]
我解决了这个问题，但是怎么提交不上去呢？@afc163

**Comment by chenshuai2144** [comment]
null 会造成动画的问题，我已经发了 pr 了

**Comment by shunzizhan** [comment]
哦哦，刚准备问你为啥不用null的
