### ISSUE TITLE
PageHeader 和官方演示不一致

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design-pro#205]
![image](https://user-images.githubusercontent.com/8358236/32871326-576bec86-cabb-11e7-8d49-b1c5913b9913.png)

[code address](https://github.com/hengkx/note/blob/master/packages/web/src/components/Project/Detail.js)

**Comment by hengkx** [comment]
![pro](https://user-images.githubusercontent.com/8358236/32875144-525ef51a-cad1-11e7-965a-084be191aa8d.png)
对比是多了个 `antd-pro-tabs` 导致的

**Comment by afc163** [comment]
官网没问题的话，需要你自己排查下问题所在。

**Comment by hengkx** [comment]
我直接引用的组件，和你们官方 预览 生成的 `class`不一样 看上面图

**Comment by afc163** [comment]
@nikogu 前缀有问题。导致组件下的 css 会互相影响：https://github.com/ant-design/ant-design-pro/blob/44d2c7bbd9e67ebc42f0b64ac04d47fe7a1b660d/src/components/NoticeIcon/index.less#L21

应该是 PageHeader 下的 css 统一加 `.antd-pro-PageHeader`，NoticeIcon 下的加 `.antd-pro-NoticeIcon` 这样。（现在只加了 `.antd-pro`）

**Comment by hengkx** [comment]
表格的样式 应该 也有问题 具体的 我没有 去查看 ，还有什么时候可以支持 自定义主题
![image](https://user-images.githubusercontent.com/8358236/32877944-dbcd6658-cade-11e7-957d-3a662ffb4719.png)

**Comment by nikogu** [comment]
之前用的 atool-build 用来打包 pro 的 umd，不过因为它是基于 webpack 1.x ，而以 function 的方式修改 className 的 name 需要 webpack 2.x，所以打算升级打包工具，使用 antd-tool，顺道一起改：https://github.com/ant-design/ant-design-pro-site/issues/125

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/8a39604b2e6b2001f455f9ff4ffc00b7c3b2cfc8
