### ISSUE TITLE
font链接失效，所有icon 都不能正常显示

### ISSUE THREAD

**Issue by Gkytbn** [ant-design/ant-design-pro#2056]
antd icon 页面
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

**Comment by chenshuai2144** [comment]
你使用了 antd 的 beta 版本吗？ 请不要使用，

**Comment by Gkytbn** [comment]
正常版本，连官方的说明，和demo自己都不显示了 ，[https://preview.pro.ant.design/](url)

**Comment by chenshuai2144** [comment]
请学习一个 markdown，你让我很困扰

**Comment by chenshuai2144** [comment]
应该是你的网络问题，我们最近没有修改主分支
