### ISSUE TITLE
components 下的 _utils 放到 src/utils 里面

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-pro#2058]
总感觉 components 下面有一个 _utils 怪怪的，为什么不同意放到 src/utils 里面？

**Comment by chenshuai2144** [comment]
_utils 会发布到组件中去

**Comment by yutingzhao1991** [comment]
嗯 你这么一说 component 算是比较独立的组件放到这里面也合理，只是 _utils 这个下划线看着有点别扭。
