### ISSUE TITLE
图表联动问题

### ISSUE THREAD

**Issue by sj279811799** [ant-design/ant-design-pro#206]
拿饼图Pie组件举例，如果`subTitle`参数传值是一个`ReactNode`类型，那么`componentWillReceiveProps`中在判断`props`变化时，`equal`会返回`false`，进而造成`renderChart`调用。`equal`函数里面没有对`object`类型进行判断。

**Comment by nikogu** [comment]
目前没有对 object 判断是因为 object 判断太慢了，还不如直接渲染更新
