### ISSUE TITLE
Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.

### ISSUE THREAD

**Issue by fengjiajia2017** [ant-design/ant-design-pro#2062]
**系统： win10    环境：node v8.11.4**
刚开始用，使用ant-design-pro-cli创建的项目，npm start报这个错：
**错误信息：**
> ant-design-pro@1.4.4 start D:\GIT\my-ant-pro\pro-web
> cross-env ESLINT=none roadhog dev
  build [==                  ] 10%
Starting the development server...
Build completed in 1.898s
Failed to compile.
./src/index.js
Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.

**Comment by fengjiajia2017** [comment]
在楼下看到相同问题

**Comment by Justu-saxc** [comment]
怎么解决的
