### ISSUE TITLE
重刷畫面後，state清空了

### ISSUE THREAD

**Issue by king804** [ant-design/ant-design-pro#2065]
如果保留所有state原先的資料？

下面是我的index.js
import './polyfill';
import dva from 'dva';

import createHistory from 'history/createHashHistory';
// user BrowserHistory
// import createHistory from 'history/createBrowserHistory';
import createLoading from 'dva-loading';
import 'moment/locale/zh-cn';
import './rollbar';
import { browserHistory } from 'dva/router';

import './index.less';
// 1. Initialize
const app = dva({
  history: createHistory(),
});
// 2. Plugins
app.use(createLoading());

// 3. Register global model
app.model(require('./models/global').default);
// 4. Router
app.router(require('./router').default);

// 5. Start
app.start('#root');

export default app._store; // eslint-disable-line

**Comment by chenshuai2144** [comment]
这是正常的操作，可以看一下相关 issue 怎么做持久化

**Comment by king804** [comment]
我打了很久都找不到相關issue
可以有link給我嗎？ 
Many thanks!
