### ISSUE TITLE
v2 导航横过来的时候 UI 有 bug

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-pro#2066]
![image](https://user-images.githubusercontent.com/1061968/44721593-03ae4300-aafd-11e8-8fa8-c88ba55cb662.png)

**Comment by yutingzhao1991** [comment]
还要加上风格是白色

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1629
