### ISSUE TITLE
ant design pro 只有刷新才会判断是否登录和权限

### ISSUE THREAD

**Issue by Captain-G** [ant-design/ant-design-pro#2069]
登录的时候会获取currentUser， Authority，但是进入到正式页面之后，只要不刷新页面，将不会再获取currentUser和Authority，也不会判断是否登录和是否有权限，只有刷新的时候才会重新调用，获取登录用户在BasicLayout中的ComponentDidMount方法中，不刷新就只会调用一次

**Comment by Captain-G** [comment]
@afc163

**Comment by Captain-G** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
`location.reload(false)`?

**Comment by chenshuai2144** [comment]
你可以basicLayout之上再封装一下，或者在update 的时候再取一次 currentUser，
把 currentUser 放到 state 里面好了

**Comment by Captain-G** [comment]
现在我是在componentWillRecieveProps里面重新获取了一下，这个重新获取是否有必要加载项目里面去？真正用的时候每个人应该都会遇到这个问题

**Comment by afc163** [comment]
应该用 https://oauth.net/2/ 的方式在每一个 Restful 接口进行鉴权，不应该依赖前序前端状态，不靠谱。
