### ISSUE TITLE
框架内使用switch开关点击切换时出现异常

### ISSUE THREAD

**Issue by xiayu1986** [ant-design/ant-design-pro#2071]
我在这个框架里面使用antd提供的Switch开关组件，点击切换开关的时候会在控制台输出如下异常信息， 
TypeError: Argument 1 of Node.removeChild is not an object.
 wave.js:100
resetEffect
wave.js:100

onClick wave.js:51，但是单独在antd项目中使用没有这个问题，是什么原因？

**Comment by afc163** [comment]
Please upgrade to 3.8.4
