### ISSUE TITLE
TimelineChart折线图控件中的titleMap没有显示，x轴渲染不完全

### ISSUE THREAD

**Issue by cleverwo** [ant-design/ant-design-pro#2073]
TimeLineChart中的titleMap设置了y1 和y2 数值，在图表渲染时 图表中的折线图显示了，但图表上方的注释信息没有显示，导致无法使用点击注释信息使图表显示y1 或y2 的信息； x轴渲染时没有全部显示dateSource中的x数据，只显示了一部分。
![image](https://user-images.githubusercontent.com/38303901/44764452-50882d00-ab82-11e8-99b1-a464e7273cd4.png)
![image](https://user-images.githubusercontent.com/38303901/44764469-6c8bce80-ab82-11e8-9713-634d11944ede.png)

**Comment by afc163** [comment]
去 G2 或者 bizcharts 提问。
