### ISSUE TITLE
How to create QA, staging & production build using "roadhog build"

### ISSUE THREAD

**Issue by rajeshk-in** [ant-design/ant-design-pro#2078]
Hi, 

We use ant design pro in our project. It is configured to create a production build using "roadhog build". 

How can we configure build for QA & Staging environment along with production? 
Roadhog build automatically takes "production" env setting in webpackrc.js.

Thanks
Rajesh

**Comment by chenshuai2144** [comment]
@sorrycc

**Comment by sorrycc** [comment]
Roadhog has only two states, development and production. You can define additional environment variables yourself and pass the environment variables to the code via the `define` configuration in `.webpackrc.js`.
