### ISSUE TITLE
组件动画不够流畅，卡顿明显

### ISSUE THREAD

**Issue by Qint** [ant-design/ant-design-pro#2085]
不知道是性能问题还是动画设置不合理，导航菜单的展开卡顿太明显了。

**Comment by chenshuai2144** [comment]
图表太多，antd 的将会重写组件，增强性能

**Comment by koupeng** [comment]
@chenshuai2144 感觉不只是图表太多的问题，，，Table页面数据太多的时候也是很卡啊。。

**Comment by EliShaXu** [comment]
Table页面数据多的时候，我看了在展开动画开始到结束 table render 并没有走。

**Comment by liu-dongyu** [comment]
导航栏展开关闭确实卡顿明显，有什么建议么？

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/3544

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
