### ISSUE TITLE
Manged unsaved data on TableForm as It get cleared on Change

### ISSUE THREAD

**Issue by chapskev** [ant-design/ant-design-pro#2091]
I have dug myself in a deep rabbit hole and was hoping someone can pull me out of the rabbit hole or point me in the right direction.

The problem in reference is in context to Antd Pro example of Advanced Form. I have a similar Form on my app where you have the header and the details. If you have a look at the form there is a funny behaviour on the form. 

### How to replicate the issue

- Go to Antd Pro preview then [Advanced form ](https://preview.pro.ant.design/#/form/advanced-form)
- Click on Add Member 
- Add the Member details then don't save instead, Click on the header details outside Tableform component. Onchange on the above details clears the table form data.

How can I prevent or manage this or how can I communicate to the user that they need to save before making other changes?

Thank you in advance :) 
To the contributes and maintainers of Antd pro than you for your time in making a great product.

**Comment by chenshuai2144** [comment]
This is a bug, you can check out this pr https://github.com/ant-design/ant-design-pro/pull/2100
