### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by 5123095** [ant-design/ant-design-pro#2099]
环境：
操作系统：win10
node: 8.11.4
npm:  5.6.0

---------------------------------------------------------------------------------------------
npm start
> ant-design-pro@1.4.4 start C:\Users\hasee\program\workplace\react\oa
> cross-env ESLINT=none roadhog dev

  build [==                  ] 10%

Starting the development server...

Build completed in 1.977s
Failed to compile.

./src/index.js
Module build failed: Error: Cannot find module 'babel-plugin-import' from 'C:\Users\hasee\program\workplace\react\oa'
    at Array.map (<anonymous>)

**Comment by chenshuai2144** [comment]
缺包 重新装一下
