### ISSUE TITLE
0.2.2 throw error in IE11 

### ISSUE THREAD

**Issue by DingLiPlus** [ant-design/ant-design-pro#210]
![image](https://user-images.githubusercontent.com/22953156/32872665-ac0f9bf0-cac2-11e7-9dd4-eff1cba59964.png)
提示语法错误，页面显示空白。

**Comment by yesmeck** [comment]
![14_47_30__11_22_2017](https://user-images.githubusercontent.com/465125/33113979-a30b41c6-cf95-11e7-8c44-86719e13a2ff.jpg)

缺少 Promise 的 polyfill。

**Comment by yesmeck** [comment]
<img width="1083" alt="20171122150558" src="https://user-images.githubusercontent.com/465125/33114208-c0dfbe1a-cf96-11e7-8c22-bdeae005ec79.png">

缺少 es6-shim

**Comment by afc163** [comment]
Edge 为啥会需要 es6-shim

**Comment by yesmeck** [comment]
这是 11 😅

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog/issues/419

**Comment by afc163** [comment]
https://github.com/dvajs/dva/issues/1233

**Comment by afc163** [comment]
- 开发环境：引入了 webpack-dev-server 的 HMR 导致 IE 报错，暂时没找到合适的解决方案：https://github.com/dvajs/dva/issues/1233#issuecomment-346360689
- 生产环境：引入了 polyfill 解决这个问题，报出另外一个问题：https://rollbar.com/afc163/ant-design/items/4/

**Comment by yesmeck** [comment]
polyfill 我直接用 `<script />` 引入 `es6-promise` 好像没问题。

**Comment by afc163** [comment]
现在报的是 React 的渲染问题，本地 IE11 下依然没法看，所以比较难排查。

**Comment by yesmeck** [comment]
应该是某个页面 React 的渲染问题？我引入 `es6-promise` 后看了下大部分页面都是好的。

**Comment by afc163** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/507615/33132922-0d3edf2c-cfd6-11e7-818e-0f1e2612e8c7.png">

**Comment by afc163** [comment]
你本地 IE11 可以调试？

**Comment by yesmeck** [comment]
可以啊，虚拟机。

**Comment by afc163** [comment]
见鬼了，明天来看看。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/index.js polyfill 要加最前面，dva 前面。

**Comment by yesmeck** [comment]
还有加了 `babel-polyfill` 的话其他 polyfill  就不需要了吧。

**Comment by afc163** [comment]
http://preview.pro.ant.design/ 在 IE 11 下已经可用，调试环境的问题还在解决。

**Comment by afc163** [comment]
https://github.com/facebookincubator/create-react-app/pull/2692

**Comment by yesmeck** [comment]
开发环境，暂时不要用 IE 吧。。。

**Comment by dai875939260** [comment]
ie语法错误，是roadhog的问题 [roadhog 1.2.2 在开发环境下js文件中有非业务代码的箭头函数导致IE浏览器报语法错误](https://github.com/sorrycc/roadhog/issues/497) ,先自己本地改node_modules里的东西，等roadhog更新。。

**Comment by johnnychen** [comment]
@yesmeck 开发环境看IE主要是看浏览器兼容性等问题

**Comment by chenshuai2144** [comment]
这个还用修吗？

**Comment by yesmeck** [comment]
要靠 https://github.com/umijs/es5-imcompatible-versions 了

**Comment by yesmeck** [comment]
pro 没啥好做的，关了吧

**Comment by chenshuai2144** [comment]
ok，好久了   看着难受

**Comment by xiaohuozi500** [comment]
@babel/polyfill  引入这个还是报错

**Comment by amarbalu** [comment]
Hi, Just add inside <body> tag in index.html
<script src=”https://cdn.polyfill.io/v2/polyfill.min.js"></script>
