### ISSUE TITLE
关于Form组件如何提交multipart/form-data的问题

### ISSUE THREAD

**Issue by shao7936626** [ant-design/ant-design-pro#2102]
在antd的官方例子里面https://ant.design/components/form-cn/ 只有打印所有的values值；
在react-compont/form的官方例子里面https://github.com/react-component/form/blob/master/examples/file-input.js ，
有关于文件的输入，他是New了一个formdata()来提交的，但是我本地测试这个formdata提交不成功，不知道为何，求哪位大神告知一下，如何用antd的form组件提交文字和图片到后台

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/b7e7983661eb5e53dc807452e9653e93e74276d4/src/utils/request.js#L63-L67
