### ISSUE TITLE
升级v2之后  怎么使用roadhog 做服务器的代理呢

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#2107]
升级v2之后  怎么使用roadhog 做服务器的代理呢

**Comment by chenshuai2144** [comment]
v2 要使用 umi

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/44965344-915bb980-af67-11e8-817e-63d7f2d32bf2.png)

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/44965349-9a4c8b00-af67-11e8-8254-15d4cdaffb3c.png)

**Comment by drduan** [comment]
我这样配置之后没有走代理 还是请求了mockjs

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/44968480-da693900-af7a-11e8-9e09-4674dfb30d48.png)

**Comment by drduan** [comment]
两种方法都不行

**Comment by xiaohuoni** [comment]
@drduan 配置文件不在这里了吧？

**Comment by drduan** [comment]
@xiaohuoni  我刚刚在webpackrc.js里配置的，然后再config.js也配置过

**Comment by drduan** [comment]
@xiaohuoni  ok 是再route.js里配置的

**Comment by shaopeng1** [comment]
@drduan 在哪个文件配置的？V2我都没有看到route.js文件啊

**Comment by shaopeng1** [comment]
![1535958085 1](https://user-images.githubusercontent.com/29971876/44972014-47d09600-af8a-11e8-8176-ea15e75e7f81.jpg)
你改的是这个下面的文件吧

**Comment by shaopeng1** [comment]
@drduan 你改的是这个下面的文件吧
![1535958085 1](https://user-images.githubusercontent.com/29971876/44972042-62a30a80-af8a-11e8-994d-324acc7237a7.jpg)

**Comment by libertyAlone** [comment]
@drduan 配置文件应该是这个吧 `config/config.js`

**Comment by shaopeng1** [comment]
楼上正解

**Comment by bjlhx15** [comment]
@libertyAlone  如果配置这里  config/config.js  如何配置代理地址呢

**Comment by bjlhx15** [comment]
@drduan 
在这个config/config.js配置
`"proxy": {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}`

在config/config.js文件中，最上面提示：// https://umijs.org/config/  查看这里的配置应该都可以配置到这里

**Comment by drduan** [comment]
已经解决了 好用
