### ISSUE TITLE
Table组件某一列加render渲染函数后排序问题

### ISSUE THREAD

**Issue by lishuai1021** [ant-design/ant-design-pro#2120]
{
  title: '名称’,
  dataIndex: '',
  sorter: true,
  render: (text) => {
   const name = text.name ==null ? <span>已删除</span> : text.name;
  return name;
}
名称这一列通过render自定义渲染，sorter设为true可排序，点击排序后无法实现排序 ，dataIndex写成name也会报错

**Comment by fabripeco** [comment]
Hi all,
Same error here using ajax data (sorted server-side by name) in a Table component

`const columns = [
      {
        title: 'Name',
        dataIndex: 'name',
        sorter: true,
        defaultSortOrder: 'ascend',
        render: (text, record) => <a onClick={() => this.onEdit(record.id)}>{text}</a> 
      },
      {
        title: 'Business Name',
        dataIndex: 'fields.businessName',
        key: 'businessName',
        sorter: true,
      },
      {
        title: 'Email',
        dataIndex: 'fields.email',
        key: 'email',
        sorter: true,
      },
      {
        title: 'Contact Name',
        dataIndex: 'fields.contactName',
        key: 'contactName',
        sorter: true,
      },
    ];

.....

<Card
            className={styles.listCard}
            bordered={false}
            title="Suppliers"
            style={{ marginTop: 24 }}
            bodyStyle={{ padding: '0 32px 40px 32px' }}
            extra={extraContent}
          >
            <Table
              columns={columns}
              dataSource={results}
              rowKey="id"
              loading={loading}
              pagination={paginationProps}
              onChange={this.handleTableChange}
            />
          </Card>
`
Cannot sort only once on "name" column. By removing the render function in that column, sorting works correctly.

Any ideas? 
Thanks for your reply and for your great framework!

**Comment by fabripeco** [comment]
It was fixed in ant d v3.10.4 https://github.com/ant-design/ant-design/issues/12870
