### ISSUE TITLE
vscode 报错 expression expected

### ISSUE THREAD

**Issue by momogugu** [ant-design/ant-design-pro#2122]
如题，修饰器在vscode中报错。
![image](https://user-images.githubusercontent.com/20534564/44972882-4fde0500-af8d-11e8-9e7c-fecf9e11a83f.png)
将export default 移到修饰器后面后报错消失。
请问有其他方法吗...还是我vscode缺少什么配置项？

**Comment by yoyo837** [comment]
这个报错不影响使用，不过也想知道咋去掉

**Comment by chenshuai2144** [comment]
我的 vscode 不显示，是不是因为这个
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}

```

**Comment by yoyo837** [comment]
@chenshuai2144 都有你这个一样的配置

**Comment by momogugu** [comment]
@chenshuai2144 这个配置是有的，但是还是会报错，不影响使用，就是强迫症看着难受....

**Comment by chenshuai2144** [comment]
看起来是 lint 的问题。
@yoyo837  有兴趣搞个 pr，把这些代码修一波吗？

**Comment by yoyo837** [comment]
缓一缓，或者其他同志先上...
