### ISSUE TITLE
设置主色后的细节问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#2123]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/507615/44973332-c16a8300-af8e-11e8-97d4-df8f900b0eb5.png">

@outline-color 变量貌似失效了。

**Comment by chenshuai2144** [comment]
@outline-color 应该也是算出来的吧

**Comment by afc163** [comment]
是的，看 antd 应该是没问题的。

**Comment by cnchore** [comment]
@afc163 哥，rules、layout插件在市场上名称是什么呀

**Comment by xiaohuoni** [comment]
关注。设置主题色之后，只有主题色变量有效，其他变量应该都无效了。再次设置只有主题色变化。https://github.com/umi-cli-test/theme-plugin

**Comment by afc163** [comment]
Fixed by #5336
