### ISSUE TITLE
切换到顶部导航模式,ui变形

### ISSUE THREAD

**Issue by huachaoliu** [ant-design/ant-design-pro#2124]
![bug](https://user-images.githubusercontent.com/15731831/44973729-1ce94080-af90-11e8-96ab-75809c696713.png)

**Comment by shaopeng1** [comment]
在线预览不会有这样的问题，本地会这样

**Comment by huachaoliu** [comment]
这是官网的浏览地址

**Comment by ergoulee** [comment]
![2018-09-05 10 27 43](https://user-images.githubusercontent.com/15899945/45067554-5b007480-b0f6-11e8-9839-e5349d8e9278.png)

顶部导航时, Menu.Item和Menu.SubMenu的高度会不一致

**Comment by chenshuai2144** [comment]
@ergoulee  你这个是怎么重现？

**Comment by ergoulee** [comment]
config/router.config.js
`    routes: [
      { path: '/', redirect: '/task' },
      { path: '/task', name: 'task', icon: 'form', component: './task/index' },
      { path: '/pinList', name: 'pinList', icon: 'mail', component: './pinList/index' },
      // forms
      {
        path: '/form',
        icon: 'form',
        name: 'form',
        routes: [
          {
            path: '/form/basic-form',
            name: 'basicform',
            component: './Forms/BasicForm',
          },
          {
            path: '/form/step-form',
            name: 'stepform',
            component: './Forms/StepForm',
            hideChildrenInMenu: true,
            routes: [
              {
                path: '/form/step-form',
                name: 'stepform',
                redirect: '/form/step-form/info',
              },
              {
                path: '/form/step-form/info',
                name: 'info',
                component: './Forms/StepForm/Step1',
              },
              {
                path: '/form/step-form/confirm',
                name: 'confirm',
                component: './Forms/StepForm/Step2',
              },
              {
                path: '/form/step-form/result',
                name: 'result',
                component: './Forms/StepForm/Step3',
              },
            ],
          },
          {
            path: '/form/advanced-form',
            name: 'advancedform',
            component: './Forms/AdvancedForm',
          },
        ],
      }]`

**Comment by ergoulee** [comment]
```
router.config.js
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    routes: [
      { path: '/', redirect: '/task' },
      { path: '/task', name: 'task', icon: 'form', component: './task/index' },
      { path: '/pinList', name: 'pinList', icon: 'mail', component: './pinList/index' },
      // forms
      {
        path: '/form',
        icon: 'form',
        name: 'form',
        routes: [
                  ....
         ],
      }
```
