### ISSUE TITLE
APP_TYPE 不是内部或外部命令

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#2126]
![image](https://user-images.githubusercontent.com/7875572/44976803-e3690300-af98-11e8-9cf4-91dfeedb69a7.png)

**Comment by drduan** [comment]
是否前边需要加set ?

**Comment by drduan** [comment]
@luzhang2016  加cross env

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/commit/3b513a652d848d1839df99d6f76dc93dcff5d9ff
