### ISSUE TITLE
cnpm start 异常 unnamed compat plugin  & Tapable.plugin is deprecated 

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#2127]
![image](https://user-images.githubusercontent.com/7875572/44977243-195ab700-af9a-11e8-9782-84364d7bdd0c.png)

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/44984671-35695300-afb0-11e8-9e43-c9bc71b46d4a.png)

**Comment by chenshuai2144** [comment]
感觉你的包，没装好。删除了重装？

**Comment by drduan** [comment]
解决了

**Comment by AirmaZ** [comment]
> 解决了

求问怎么解决的，我也发生这样的问题

**Comment by shenggen1987** [comment]
> 解决了

请问怎么解决的，我也经常出现
