### ISSUE TITLE
Document text error

### ISSUE THREAD

**Issue by daidaishuo** [ant-design/ant-design-pro#2130]
<img width="763" alt="wx20180903-175638 2x" src="https://user-images.githubusercontent.com/19766840/44980616-f84a9400-afa2-11e8-980b-169695e62326.png">
<img width="763" alt="wx20180903-175733 2x" src="https://user-images.githubusercontent.com/19766840/44980617-f97bc100-afa2-11e8-84a5-fcc4d742a472.png">

**Comment by afc163** [comment]
PR is welcome~

<img width="396" alt="image" src="https://user-images.githubusercontent.com/507615/44981110-3ac0a080-afa4-11e8-955e-4ba7695b7e04.png">

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/ant-design-pro-site/pull/207
