### ISSUE TITLE
Tooltip didn't display in Ant Design Pro v2.0

### ISSUE THREAD

**Issue by Anderson-Liu** [ant-design/ant-design-pro#2131]
Expected behavior(shot from https://v1.preview.pro.ant.design/#/dashboard/analysis):
![image](https://user-images.githubusercontent.com/8468372/44981414-0994a000-afa5-11e8-8af7-7ca50067be9c.png)
Issue(shot from  https://preview.pro.ant.design/dashboard/analysis):
![image](https://user-images.githubusercontent.com/8468372/44981469-33e65d80-afa5-11e8-9ccb-c6eac71d5658.png)

Tooltip should display when mouse hover or click,  but it does not appear as expect.
I have check it in latest version of Chrome, Firefox and Safari, and none of them can work properly.

**Comment by chenshuai2144** [comment]
fixed

**Comment by Anderson-Liu** [comment]
@chenshuai2144 Can you share how to fix it? Like share the which commit fix this issue?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/c4b6dafb64c9284a52face3f3aa5f04f3ba5420f
