### ISSUE TITLE
请问v2版本怎么通过不同账户实现菜单权限控制

### ISSUE THREAD

**Issue by jonerose** [ant-design/ant-design-pro#2132]

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/authority-management-cn

**Comment by CasperMXP** [comment]
v2如何实现从后端动态加载路由数据而不是去router.config.js配置文件读？

**Comment by gatinul** [comment]
> https://pro.ant.design/docs/router-and-nav-cn#%E8%8F%9C%E5%8D%95

这样改动menuData获取，好像只能实现菜单动态读取啊，如果直接拼路径访问，还是会访问到，请问这个怎么处理呢。比如菜单中没有工作台但是拼接路径 `/dashboard/workplace`依然能访问，因为没有authority属性，在权限控制时就返回所有了
