### ISSUE TITLE
AvatarList.Item usage of Avatar

### ISSUE THREAD

**Issue by NoureldeanSaed** [ant-design/ant-design-pro#2133]
https://github.com/ant-design/ant-design-pro/blob/02e811083bbc01f099ceb016b1812dce4c97cde6/src/components/AvatarList/index.js#L32

Why aren't you using the full abilities of antd's `Avatar`? You could simply do:
```jsx
const Item = ({ src, size, tips, children, onClick = () => {} }) => {
  const cls = classNames(styles.avatarItem, {
    [styles.avatarItemLarge]: size === 'large',
    [styles.avatarItemSmall]: size === 'small',
    [styles.avatarItemMini]: size === 'mini',
  });

  return (
    <li className={cls} onClick={onClick}>
      {tips ? (
        <Tooltip title={tips}>
          <Avatar src={src} size={size} style={{ cursor: 'pointer' }} >{children}</Avatar>
        </Tooltip>
      ) : (
        <Avatar src={src} size={size} >{children}</Avatar>
      )}
    </li>
  );
};
```
That would make more use of what `AvatarList.Item` can do and how much can it use antd's `Avatar`.

**Comment by chenshuai2144** [comment]
The components in the pro are more to meet the needs of the pro, we will remove it in the near future. Using antd directly is the best choice
