### ISSUE TITLE
编译报错的话一闪而过看不到问题

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design-pro#2136]
只能看见:
```
 DONE  Compiled successfully in 415ms                                                                                                                    20:17:30


  App running at:
  - Local:   http://localhost:8000/
  - Network: http://192.168.1.107:8000/
```

页面也没有错误堆栈报告。

另外，是否考虑提供 2.0升级指导文档？

**Comment by springleng** [comment]
<img width="1006" alt="1" src="https://user-images.githubusercontent.com/1900972/44987969-a5310b00-afbb-11e8-99bd-b317b19c90de.png">

一闪而过的截图，control+c才能看见。

**Comment by yoyo837** [comment]
不是启动的时候，启动的时候我可以准备control+c，是保存的时候，来不及按。稍后上gif图

**Comment by springleng** [comment]
package.json里有"@babel/runtime"啊？

{
  "name": "ant-design-pro",
  "version": "2.0.0",
...

  "dependencies": {
    "@antv/data-set": "^0.9.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "antd": "^3.9.0",

环境MacOS 10.13.6 (17G65)
node 8.11.4
npm 5.6.0

**Comment by springleng** [comment]
@ant-design-bot @afc163

**Comment by yoyo837** [comment]
![umi-error](https://user-images.githubusercontent.com/6134547/44988676-1e316200-afbe-11e8-9558-78fc1d239b8c.gif)

**Comment by chenshuai2144** [comment]
不是阻塞性问题，都会一闪而过

**Comment by sorrycc** [comment]
已在 master 里修复。
