### ISSUE TITLE
Authorized

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#2142]
pages里有Authorized.js，utils里也有Authorized.js和authority.js，这个是不是应该合一啊？

**Comment by Tan90Qian** [comment]
pages里的是在路由组件被渲染前进行判定用的，而utils的两个是工具。1.x的时候权限是通过src/router.js文件中的AuthorizedRoute组件来全局控制，2.0将路由改为纯配置文件后，1.x的方案无法使用，只能单独加一个并注入到配置文件中。

**Comment by chenshuai2144** [comment]
写的很棒，有没有兴趣提个 pr，我们加入到文档中

**Comment by Tan90Qian** [comment]
怎么做？萌新一枚  没提过pr

**Comment by Tan90Qian** [comment]
关于最后一点，我个人觉得可以用“交集”来处理，就是lodash提供的`intersection `函数，并且参数中剔除undefined的那些项
```javascript
// ...
import intersection from 'lodash/intersection';
// ...
export default ({ children, route, location }) => {
  // ...
  let authorities = [];
  routes.forEach(item => {
    if (Array.isArray(item.route.authority) && item.route.authority.length) {
      authorities.push(item.route.authority);
    } else if (typeof item.route.authority === 'string' && item.route.authority) {
      authorities.push([item.route.authority]);
    }
  });
  // ...
  return (
    <Authorized
      authority={authorities.length === 0 ? undefined : intersection(...authorities)}
      noMatch={noMatch}
    >
      {children}
    </Authorized>
  );
};
```

**Comment by CasperMXP** [comment]
@Tan90Qian 我clone的新项目,启动起来，怎么直接就进入了首页了？而不是进入登录页面了？

**Comment by Tan90Qian** [comment]
@CasperMXP 因为getAuthority函数在localStorage中不存在目标字段的时候是当作admin处理的。方便功能预览，而路由配置中有这样一段`{ path: '/', redirect: '/dashboard/analysis' },`，所以会直接当作已登陆来处理

**Comment by CasperMXP** [comment]
@Tan90Qian 明白了，谢谢。咨询哈你[官网文档权限设置](https://pro.ant.design/docs/authority-management-cn)中
`  path: '/form',
  icon: 'form',
  name: 'form',
  children: [{
    path: '/form/basic-form',
    name: 'basicform',
    component: './Forms/BasicForm',
  }
`
用的是children而实际代码中router.config.js中用的routes，这个是怎么回事了？

**Comment by Tan90Qian** [comment]
2.0刚上没几天，文档更新不及时

**Comment by CasperMXP** [comment]
@Tan90Qian  能不能分析哈router.config.js怎么被解析的了，我看了半天只知道被config.js读取了，谢谢了。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/router-and-nav-cn#%E8%8F%9C%E5%8D%95

**Comment by chenshuai2144** [comment]
@Tan90Qian  在 https://github.com/ant-design/ant-design-pro-site 这里 pr 就好了

**Comment by CasperMXP** [comment]
@Tan90Qian @chenshuai2144  我按照文档讲menuData修改从mock中读取数据后，加上权限字段，设置的是admin，用admin账户登录也不显示菜单，是不是数据结构不对额，大佬些。
`export default {
  'GET /api/menus': [
    {
      path: '/dashboard',
      name: 'dashboard',
      icon: 'dashboard',
      locale: 'menu.dashboard',
      authority:["admin"],
      children: [
        {
          path: '/dashboard/analysis',
          name: 'analysis',
          locale: 'menu.dashboard.analysis',
        },
        {
          path: '/dashboard/monitor',
          name: 'monitor',
          locale: 'menu.dashboard.monitor',
        },
        {
          path: '/dashboard/workplace',
          name: 'workplace',
          locale: 'menu.dashboard.monitor',
        },
      ],
    },
    ]
}
`

**Comment by CasperMXP** [comment]
@Tan90Qian @chenshuai2144  我按照文档讲的将menuData从mock中读取，但是加了权限字段，设置成admin,admin账户登录进去也不显示，是不是menuData数据结构不对？大佬些。
export default {
  'GET /api/menus': [
    {
      path: '/dashboard',
      name: 'dashboard',
      icon: 'dashboard',
      locale: 'menu.dashboard',
      authority:["admin"],
      children: [
        {
          path: '/dashboard/analysis',
          name: 'analysis',
          locale: 'menu.dashboard.analysis',
        },
        {
          path: '/dashboard/monitor',
          name: 'monitor',
          locale: 'menu.dashboard.monitor',
        },
        {
          path: '/dashboard/workplace',
          name: 'workplace',
          locale: 'menu.dashboard.monitor',
        },
      ],
    },
    ]
}

**Comment by Tan90Qian** [comment]
@chenshuai2144 我之前在这里提了：https://github.com/ant-design/ant-design-pro/pull/2170
check有2个出错了，不知道什么原因。还需要在ant-design-pro-site重新提么？

**Comment by chenshuai2144** [comment]
需要的。ant-design-pro-site 是文档站

**Comment by chenshuai2144** [comment]
@CasperMXP 返回 router.config.js 里面的内容就好了
