### ISSUE TITLE
umi mock如何重定向？

### ISSUE THREAD

**Issue by yaoleiroyal** [ant-design/ant-design-pro#2144]
你们官网原话是：你可以直接返回数据，也可以通过函数处理以及重定向到另一个服务器。

但是我没看到具体的例子。默认生成的工程中都是使用mock的，我现在希望我自己新加的请求，能直接访问我的后台服务，该怎么配置呢？

**Comment by chenshuai2144** [comment]
https://umijs.org/guide/mock-data.html#mock-data

**Comment by yaoleiroyal** [comment]
非常感谢，搞定了！
