### ISSUE TITLE
水波图数据更新BUG

### ISSUE THREAD

**Issue by 521zzp** [ant-design/ant-design-pro#2146]
水波图数据根据store里面的变化有异常。
我的水波图数据时根据store里面的数据渲染的，有以下情况：
1.当store里面的percent初始化为undefeind时，从后台接受到数据，更新store后，水波图文字显示percet是store里面的数据，然而却并没有画出水波；
2.当store里面的percetn初始化为0是，从后台接收到数据，更新store后，水波图文字显示percent是store里面的数据，水波图有图像，但是水波显示高度和文本指示内容不同，只有一点点（0的意思）；
3.当初始化percet为0，页面加载，请求到数据80，更新store，水波图文字内容显示80%，水波高度只有一点点（接近于0）。然后切换到其他页面，在切换回来，此时请求后台得到数据30，更新store，水波图文字内容显示30%，但高度却是80%，多次切换，发现水波高度和文字不符，高度总是上一次的数据；
4.当传入水波图percetn为固定40，不随sotre变化，水波图正常。

个人解决办法：
我是这样引入的
``
import { WaterWave } from 'ant-design-pro/lib/Charts';
``
找到源码位置： ant-design-pro/lib/Charts/WaterWave/index,js
添加代码，在 _createClass 内添加 componentWillReceiveProps 生命周期函数：
``
{
    key: 'componentWillReceiveProps',
    value: function componentWillReceiveProps(props) {
    	if (props.percent !== this.props.percent) {
    		this.renderChart(props); 
    	}
    }
},
``
然后在 renderChart 方法里面修改：
`
function renderChart(new_props) {
var _props = new_props ? new_props : this.props,
......
}
`
这里在接受到新的props是重新进行绘图，原来的方法是
var _props = this.props；这样的props还是上一次的数据，我们要用新的props绘图；

这样水波图就正常了！

希望能修复一下，如果哪里写的不好请指正~

**Comment by chenshuai2144** [comment]
done
