### ISSUE TITLE
[React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design-pro#2149]
由于有OCX插件，头部必须加上标签
\<meta http-equiv="X-UA-Compatible" content="IE=5; IE=10" \/\>

polyfills: ['ie11']

然后就报异常了
[React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/
umi.js (56691,5)

The above error occurred in the <IntlProvider> component:
    in IntlProvider (created by _default)
    in LocaleProvider (created by _default)
    in _default (created by _default)
    in _default
    in Provider (created by DvaContainer)
    in DvaContainer
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by beeant0512** [comment]
\<meta http-equiv="X-UA-Compatible" content="IE=10" \/\>  同样有问题

**Comment by xutaogit** [comment]
@linchinghao 
理论上迁移到umi之后直接改配置里的polyfills就能实现IE兼容吧，但刚在config.js文件里修改后编译是成功了，但IE控制台切到10或者9还是跑不起来。如果还是要通过安装polyfill来实现hack且布局仍然乱的，是不是表示目前版本还不可用。。。头大Orz

**Comment by JevonYang** [comment]
@xutaogit  在html模板里加入以下内容，即可简单适配有侧边栏的布局（来源ant-design某个issue）。完美适配，可能就要重新写layout了。
``

**Comment by afc163** [comment]
pro 不支持 IE11 以下的版本。

**Comment by drduan** [comment]
手机端打开报错 
![image](https://user-images.githubusercontent.com/7875572/48681623-94695c00-ebde-11e8-9265-8432e33da383.png)

**Comment by PipiHua** [comment]
> 在IE10下面没有Intl API, 需要polyfill. 我用下面的方法解决了。
> 第一步：
> 
> ```shell
> $ npm install --save intl @babel-polyfill
> ```
> 
> 第二步：在src下新建 global.js
> 
> ```js
> import '@babel/polyfill';
> 
> global.Intl = require('intl'); 
> window.Intl = require('intl');
> ```
> 
> ![2018-09-04_142257](https://user-images.githubusercontent.com/35265061/45013562-1caf7a80-b04e-11e8-81d4-f6147b64bec0.png)
> 
> 在IE9+上都可以跑了，不过布局都乱了。。flex布局不支持IE9以及部分支持IE10。

此方法可行，ie11以下不支持Intl接口，通过这样添加intl polyfill可解决
https://formatjs.io/docs/guides/runtime-requirements
