### ISSUE TITLE
npm install报错：'..' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by gucciwu** [ant-design/ant-design-pro#215]
E:\misc\ant-design-pro-site-master>npm install

> ant-design-pro-site@0.0.1 preinstall E:\misc\ant-design-pro-site-master
> cd ./scaffold && ../tool/bin/i

'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro-site@0.0.1 preinstall: `cd ./scaffold && ../tool/bin/i`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro-site@0.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gucci\AppData\Roaming\npm-cache\_logs\2017-11-16T07_46_55_079Z-debug.log

**Comment by nikogu** [comment]
@gucciwu windows 这个我稍后改下，你可以先自行修改下 `script` 单独安装

**Comment by afc163** [comment]
ant-design-pro-site 不是脚手架，原则上官方不提供支持。若有需求，你可以直接 PR 帮助我们改善。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/issues/102

**Comment by gucciwu** [comment]
OK, got it, thanks~~~
