### ISSUE TITLE
2.0新建项目如何只保留需要的模块？

### ISSUE THREAD

**Issue by anshengme** [ant-design/ant-design-pro#2151]
现在创建的项目，包含了太多了的页面了，很多都是不需要的，可能我只需要在创建的时候保留登录页，和统计页，其他的页面可以根据需求慢慢添加。

**Comment by yoyo837** [comment]
先删除page下不需要的，然后核对删除路由配置，然后搜索componets里没有被引用文件夹删除之，就差不多了

**Comment by yoyo837** [comment]
最后删除package.json不需要的依赖

**Comment by anshengme** [comment]
@yoyo837 是的，我现在就是这样做的，但还是感觉很麻烦，如果pro cli能够提供精简版的pro就好了
