### ISSUE TITLE
npm start 启动服务之前有很多 warning 输出

### ISSUE THREAD

**Issue by springleng** [ant-design/ant-design-pro#2152]
✔ success webpack compiled in 35s 707ms

 WARNING  Compiled with 44 warnings                                                                                                                                          14:30:03

 warning

chunk vendors [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/list/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/divider/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/alert/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/tooltip/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/menu/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/icon/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/grid/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/tabs/style/index.less
 * css ./node_modules/css-loader??ref--18-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--18-4!./node_modules/antd/es/card/style/index.less

 warning ......

chunk vendors [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--17-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--17-4!./src/components/Result/index.less
 * css ./node_modules/css-loader??ref--17-2!./node_modules/postcss-loader/src??postcss!./node_modules/af-webpack/node_modules/less-loader/dist/cjs.js??ref--17-4!./src/components/PageHeaderWrapper/index.less

  App running at:
  - Local:   http://localhost:8000/ (copied to clipboard)
  - Network: http://192.168.1.6:8000/

**Comment by anshengme** [comment]
一样遇到了

**Comment by shaopeng1** [comment]
#2114

**Comment by afc163** [comment]
+1
