### ISSUE TITLE
升级2.0后，原Switch方式 变更为 this.props.children 参数怎么往下传

### ISSUE THREAD

**Issue by panshiyu** [ant-design/ant-design-pro#2154]
原方案父组件 /list/search
`<PageHeaderLayout >
          <Switch>
            {getRoutes(match.path, routerData).map(item => {
              return (
                <AuthorizedRoute
                  key={item.key}
                  path={item.path}
                  component={item.component}
                  exact={item.exact}
                  authority={item.authority}
                  redirectPath="/exception/403"
                  参数1=""
                  参数2=""
                />
              );
            })}
          </Switch>
        </PageHeaderLayout>`

现改为Pro 2.0 方案后 父组件 /list/search
`<PageHeaderLayout>
          {children}
</PageHeaderLayout>`

对应路由参考
`   {
            path: '/list/search',
            name: 'searchlist',
            component: './List/List',
            routes: [
              {
                path: '/list/search/articles',
                name: 'articles',
                component: './List/Articles',
              }
            ],
          }`

原来父组件的 参数1，参数2  要如何 传到子组件，React.cloneElement 方法已尝试，路由后，并非在colone的那个子组件上，而是在children.props, 请问有提供什么方法可以下传吗？

**Comment by chenshuai2144** [comment]
加到 `routes` 配置就可以了。现在全部是中心化的
