### ISSUE TITLE
[version 2.0] How to redirect to login page if not logged in?

### ISSUE THREAD

**Issue by digz6666** [ant-design/ant-design-pro#2157]
In version 1.x it redirects to login page when not logged in, how to do it in version 2.0?

There's only page/Authorized.js (https://github.com/ant-design/ant-design-pro/blob/master/src/pages/Authorized.js) which shows 403 when user has no permission.

Couldn't find the config to redirect like in src/router.js (https://github.com/ant-design/ant-design-pro/blob/v1/src/router.js) in version 1.x.

**Comment by chenshuai2144** [comment]
Is our negligence, we will add jump

**Comment by digz6666** [comment]
Related issue #2158

**Comment by digz6666** [comment]
In the meantime I made following changes.

1. src/utils/authority.js
```js
@ -8,8 +8,6 @@ export function getAuthority() {
    } else {
      authority = [authority];
    }
  } else {
    authority = ['admin'];
  }
  return authority;
}
```

2. src/pages/Authorized.js
```js
@@ -1,37 +1,45 @@
import React from 'react';
import { Redirect } from 'react-router-dom';
import RenderAuthorized from '@/components/Authorized';
import Exception from '@/components/Exception';
import { matchRoutes } from 'react-router-config';
import uniq from 'lodash/uniq';
import { formatMessage } from 'umi/locale';
import Link from 'umi/link';
import { getAuthority } from '@/utils/authority';

const Authorized = RenderAuthorized(['admin', 'user']);

export default ({ children, route, location }) => {
  const routes = matchRoutes(route.routes, location.pathname);
  let authorities = [];
  routes.forEach(item => {
    if (Array.isArray(item.route.authority)) {
      authorities = authorities.concat(item.route.authority);
    } else if (typeof item.route.authority === 'string') {
      authorities.push(item.route.authority);
    }
  });
  const noMatch = (
    <Exception
      type="403"
      desc={formatMessage({ id: 'app.exception.description.403' })}
      linkElement={Link}
      backText={formatMessage({ id: 'app.exception.back' })}
    />
  );
  return (
    <Authorized
      authority={authorities.length === 0 ? undefined : uniq(authorities)}
      noMatch={noMatch}
    >
      {children}
    </Authorized>
  );
  const authority = getAuthority();

  if (authority) {
    const routes = matchRoutes(route.routes, location.pathname);
    let authorities = [];
    routes.forEach(item => {
      if (Array.isArray(item.route.authority)) {
        authorities = authorities.concat(item.route.authority);
      } else if (typeof item.route.authority === 'string') {
        authorities.push(item.route.authority);
      }
    });
    const noMatch = (
      <Exception
        type="403"
        desc={formatMessage({ id: 'app.exception.description.403' })}
        linkElement={Link}
        backText={formatMessage({ id: 'app.exception.back' })}
      />
    );
    return (
      <Authorized
        authority={authorities.length === 0 ? undefined : uniq(authorities)}
        noMatch={noMatch}
      >
        {children}
      </Authorized>
    );
  }

  return <Redirect to='/login/login'/>;
};
```

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2234

**Comment by yupeilin123** [comment]
没有authority就重定向到login，其余不变
```
Authorized.js

getAuthority() ? (
      <Authorized
        authority={authorities.length === 0 ? undefined : intersection(...authorities)}
        noMatch={noMatch}
      >
        {children}
      </Authorized>
    ) : <Redirect to='/user/login' />
```

**Comment by alpha-hxb** [comment]
getAuthority() 登录一次之后不是就一直有值了吗？
@yupeilin123

**Comment by digz6666** [comment]
@yupeilin123 If you look at src/utils/authority.js it always returns authority.

**Comment by yupeilin123** [comment]
可以用一个sessionStorage来判断是否已登录 ， `getIsLogin( )`
@alpha-hxb

**Comment by yupeilin123** [comment]
You can modify files. It is not necessary to refer to v2.
你可以修改文件。不一定要参照v2.
目前我的做法是通过`sesstionLocalstorget`来判断是否已登录，如果登录走`basicLayout', 否则走`userLayout`。
@digz6666

**Comment by NickFranceschina** [comment]
should `getAuthority` really return `['admin']` as a final fallback?  

https://github.com/ant-design/ant-design-pro/blob/231e725abd99c91c4304001fbf784f426f85925e/src/utils/authority.js#L16

**Comment by NickFranceschina** [comment]
or why does `checkPermission` default to "View all by default"?

https://github.com/ant-design/ant-design-pro/blob/231e725abd99c91c4304001fbf784f426f85925e/src/components/Authorized/CheckPermissions.js#L22-L26

**Comment by digz6666** [comment]
> should `getAuthority` really return `['admin']` as a final fallback? if nothing is set in localStorage, shouldn't it default to `'guest'` maybe?
> 
> [ant-design-pro/src/utils/authority.js](https://github.com/ant-design/ant-design-pro/blob/231e725abd99c91c4304001fbf784f426f85925e/src/utils/authority.js#L16)
> 
> Line 16 in [231e725](/ant-design/ant-design-pro/commit/231e725abd99c91c4304001fbf784f426f85925e)
> 
>  return authority || ['admin'];

@NickFranceschina I think it shouldn't.

**Comment by digz6666** [comment]
> or why does `checkPermission` default to "View all by default"?
> 
> [ant-design-pro/src/components/Authorized/CheckPermissions.js](https://github.com/ant-design/ant-design-pro/blob/231e725abd99c91c4304001fbf784f426f85925e/src/components/Authorized/CheckPermissions.js#L22-L26)
> 
> Lines 22 to 26 in [231e725](/ant-design/ant-design-pro/commit/231e725abd99c91c4304001fbf784f426f85925e)
> 
>  // 没有判定权限.默认查看所有 
>  // Retirement authority, return target; 
>  if (!authority) { 
>    return target; 
>  }

For this instance you can customize whatever you want :)

**Comment by NickFranceschina** [comment]
> @NickFranceschina I think it shouldn't.

oh I see you already pointed this out above... apologies :smile:

**Comment by mushroomlb** [comment]
![image](https://user-images.githubusercontent.com/1701771/46218362-f04dfc00-c376-11e8-80be-5c0e929e0b16.png)
