### ISSUE TITLE
v2 如何设置默认进入登录页面

### ISSUE THREAD

**Issue by Justu-saxc** [ant-design/ant-design-pro#2158]
v2 如何设置默认进入登录页面

**Comment by chenshuai2144** [comment]
默认设置的权限是 admin，你可以改成 user ，就不会自动登录了

**Comment by Justu-saxc** [comment]
authority.js
export function getAuthority() {
  // return localStorage.getItem('antd-pro-authority') || ['admin', 'user'];
  let authority = localStorage.getItem('antd-pro-authority');
  if (authority) {
    if (authority.includes('[')) {
      authority = JSON.parse(authority);
    } else {
      authority = [authority];
    }
  } else {
    authority = ['user'];
  }
  return authority;
}
修改成user 或guest 都不起作用

**Comment by Tan90Qian** [comment]
因为2.0默认的权限功能有坑。。。

**Comment by chenshuai2144** [comment]
重复了 #2157
