### ISSUE TITLE
金额格式化异常

### ISSUE THREAD

**Issue by davy-gan** [ant-design/ant-design-pro#2165]
![image](https://user-images.githubusercontent.com/21240946/45068269-41acf780-b0f9-11e8-98bf-6ddadbd9a188.png)
大额金额格式化出现异常如：92233720368547760

**Comment by afc163** [comment]
PR is welcome~

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/ant-design-pro/commit/5fcbc84c463f5d16952fe6a7227c01a9bc9d621b

**Comment by davy-gan** [comment]
好粗暴的解决方式呀

**Comment by chenshuai2144** [comment]
相当有效

**Comment by afc163** [comment]
@chenshuai2144 要养成习惯用 commit message 关 issue。https://help.github.com/articles/closing-issues-using-keywords/

**Comment by chenshuai2144** [comment]
这个是 愚道提给我的，，，写完之后才发现社区也有 issue

**Comment by afc163** [comment]
好~
