### ISSUE TITLE
umi 配置项 define 在入口 document.ejs 中不生效

### ISSUE THREAD

**Issue by Atlaswimming** [ant-design/ant-design-pro#2167]
V1 版本中，通过 .webpackrc.js 增加的 define 配置项，能正常传递给 DefinePlugin，从而替换原入口文件 index.ejs 中的变量。
V2 版本，umi 的配置文件 /config/config.js 中设置的 define 项，其中定义的变量无法修改 document.ejs 文件。
该配置可以对其他 js 文件生效，问题只存在于 入口 ejs 文件。

**Comment by sorrycc** [comment]
document.ejs 直接写就好了，为啥还要配变量？

**Comment by Atlaswimming** [comment]
1. 公司有一些基础服务，需要在<head>里添加小段的 <script> 做配置，这些配置项是根据公司 CI 的环境有不同的值，我在构建过程中取环境变量，向 ejs 模板中注入不同的值。
2. 我在 V1 的基础上包装了脚手架，可以让开发者通过命令行键入一些项目基本信息，生成新项目，其中将开发者输入的信息保存为 json 文件，并在原 .webpackrc.js 中读取、注入到代码中。

**Comment by sorrycc** [comment]
可以配置 [context](https://umijs.org/zh/config/#context)，然后在 document.ejs 里通过 `<%= context.xxx` 引用。
