### ISSUE TITLE
antd pro登录页 保存用户名和密码

### ISSUE THREAD

**Issue by lishuai1021** [ant-design/ant-design-pro#2169]
要实现antd prop登录页面保存用户名和密码的功能
 <Checkbox checked={this.state.autoLogin} onChange={this.changeAutoLogin} style={{float: 'left', color: '#fff'}}>自动登录</Checkbox>
这样加一个复选框没有作用 应该怎么实现？需要自己保存用户名和密码吗

**Comment by yupeilin123** [comment]
浏览器提示是否保存用户名和密码。不建议开发者自行保存密码。

**Comment by lishuai1021** [comment]
没有提示保存 antd Login组件中封装了保存登录信息 还是需要自己写方法比如localstorage

**Comment by chenshuai2144** [comment]
最好自己写localstorage保存用户名。
一般这个还是交给浏览器和后端案板
