### ISSUE TITLE
环境装过tnpm，如何不执行tnpm 的 intsall

### ISSUE THREAD

**Issue by Frank1e0927** [ant-design/ant-design-pro#217]
用的ant pro 的脚手架进行new pro：如下

⠋ Auto installing...use npm: tnpm
⠦ Auto installing...

一直无法正常安装
有没有办法更改一下目标方法，替换成cnpm或者npm...

**Comment by afc163** [comment]
ctrl + c 取消掉，手动安装。

@nikogu 或许需要加一个 `--no-autoinstall` 参数。

**Comment by yesmeck** [comment]
用内外网判断吧 `is-ali-env`

**Comment by nikogu** [comment]
@yesmeck 通过内外网判断也不准确，可以设置一个超替换或者手动模式

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-cli#025
