### ISSUE TITLE
vscode自动格式化失效

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#2178]
原来使用pro来做项目，vscode会根据eslint进行自动格式化，当时配置的是保存时自动格式化，并且格式化成eslint要求的格式，现在换了个机器，自动格式化的配置都设置成true，格式化管用，但是格式化的结果不是eslint要求的，格式化话后还提示，不符合规则。

我这需要装什么插件或配置什么吗？
原来的机器什么也没弄啊，一直以为是ant design pro里面配置的，看来不是啊。这个有人知道吗？

**Comment by chenshuai2144** [comment]
prettier 你需要这个插件

**Comment by codepandy** [comment]
这个项目中安装了，验证起作用了，就是不会自动格式化成它要求的格式。
你说的是vscode需要安装这个吗？但是中vscode中搜不到这个插件啊。

**Comment by chenshuai2144** [comment]
https://github.com/prettier/prettier-vscode

**Comment by AlexanderChen1989** [comment]
安装了prettier-vscode还是没有

**Comment by codepandy** [comment]
我安装的prettier-Code formatter,然后就管用了。

**Comment by bruceeewong** [comment]
有可能是vscode有多个formatter插件，ctrl+shfit+p > format document 可以选择 prettier 插件作为选择，会自动识别项目的prettier配置； 接着配置 vscode preferences > settings.json；
```
{
  "editor.formatOnSave": true,
}
```
两个配好就可以实现 vscode 保存自动格式化了
