### ISSUE TITLE
栅格式布局过程中出现错位问题

### ISSUE THREAD

**Issue by Double517** [ant-design/ant-design-pro#218]
栅格式布局过程中出现
![74794619-a59d-44fd-b933-6e7d55441cdb](https://user-images.githubusercontent.com/11642282/32923968-611aa406-cb75-11e7-8d1a-edf3488b01b2.png)
`代码如下：`
![image](https://user-images.githubusercontent.com/11642282/32924315-ff70a55a-cb76-11e7-8ad1-5ba22ea9249d.png)

除非在换行处加上<Row gutter={Gutter}>才可以实现正常显示,是一定要加上Row标签么，希望能够通过参数实现列可自动调整

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us?

**Comment by Double517** [comment]
demo我用附件上传了，就是原始的项目相同的打开方式。其次针对pro来说想知道提供案例中如何实现外部保存按钮实现form组件的提交等事件呢
[ant-design-pro#218.zip](https://github.com/ant-design/ant-design-pro/files/1480859/ant-design-pro.218.zip)

**Comment by afc163** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/507615/32927074-8ae312fe-cb85-11e7-8de8-f6705b169890.png">

你给的包跑不起来。

**Comment by Double517** [comment]
[ant-design-pro#218-2.zip](https://github.com/ant-design/ant-design-pro/files/1481051/ant-design-pro.218-2.zip)
抱歉，上午上传的忘记把隐藏文件上传了，刚刚重新弄了一下，本地测试可以运行了的。
辛苦辛苦。 @afc163

**Comment by Double517** [comment]
发现这个问题貌似在mac下出现，windows下貌似正常显示，是由于浏览器内核原因么?

**Comment by afc163** [comment]
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/507615/32977624-fc4fa1dc-cc6b-11e7-858b-ec3fea3fc283.png">

没能重现，建议直接给出在线可预览可以重现的地址，确保重现后我会 reopen 。
