### ISSUE TITLE
Error: Reducer "node" returned undefined during initialization. 

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design-pro#2181]
按步骤升级，从2.0beta升级，看了好几遍应该没有遗漏？还是发生下面情况是为什么

![ant0](https://user-images.githubusercontent.com/24719296/45079793-fa892b80-b125-11e8-9a16-9239ae8f53fa.png)

**Comment by chenshuai2144** [comment]
更新一下你的包，感觉是 redux 的依赖问题

**Comment by Veigar-C** [comment]
没有redux包，dva和umi是最新的 @chenshuai2144

**Comment by chenshuai2144** [comment]
删除 node_mudlue 然后重新安装呢？

**Comment by Veigar-C** [comment]
试过了 ，我的包如下：
![ant1](https://user-images.githubusercontent.com/24719296/45086430-b69e2280-b135-11e8-9616-f7070a1e15e3.png)

@chenshuai2144

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/45129892-d88cb900-b1b8-11e8-804e-cc71f4c1929b.png)
这个也升级到 rc

**Comment by Veigar-C** [comment]
也不行，这个好像是兼容，和redux没关系？ @chenshuai2144

**Comment by Veigar-C** [comment]
解决了，是一个mode为空的导致，不过报错报的看不懂 ，谢了 @chenshuai2144

**Comment by Veigar-C** [comment]
2.0.0beta空的model倒是不报错，翻了下2.0多个DvaContainer目录，记录下
