### ISSUE TITLE
顶部菜单布局，没有子菜单的项位置太靠下

### ISSUE THREAD

**Issue by yansuan** [ant-design/ant-design-pro#2182]
![image](https://user-images.githubusercontent.com/18570764/45080547-b1d27200-b127-11e8-9fe1-3f3c23d053b2.png)

 hideChildrenInMenu: true,

**Comment by afc163** [comment]
Try reinstall node_modules.

**Comment by yansuan** [comment]
重新下载，配置，还是同样的问题
`{
        path: '/workplace',
        name: 'workplace',
        icon: 'dashboard',
        hideChildrenInMenu: true,
        hideInMenu: false,
        routes: [
          {
            path: '/workplace',
            name: 'manage',
            component: './Dashboard/Workplace',
          },
        ]
      },`

**Comment by wangshoukai** [comment]
comoonents文件夹,TopNavHeader  index.js  文件下   <BaseMenu {...this.props} style={{ border: 'none', height: 64 }} />  改下height

**Comment by yansuan** [comment]
感谢 @wangshoukai ,把64改成55就好了。

**Comment by ergoulee** [comment]
![2018-09-19 10 15 33](https://user-images.githubusercontent.com/15899945/45727169-0b8d6e80-bbf5-11e8-8d1e-dbad81283b75.png)
还是有问题,顶部导航的高度还是64
