### ISSUE TITLE
JSON contains pictures, arrays and other information, background can not be received, parsed

### ISSUE THREAD

**Issue by TieHongPo** [ant-design/ant-design-pro#2185]
使用框架将图片转为base64、还有数组等等信息，全部转为json格式提交到后台，但是后台无法接收、解析
报错部分信息：Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.alibaba.fastjson.JSONObject: no String-argument constructor/factory method to deserialize from String value
前台json数据:{"id":"","orgName":"","mobilePhone":"","orgTelephone":"","registerAddr":"","manageAddr":"","orgEmails":"","orgLicense":{"file":{"uid":"rc-upload-1536137942284-4","lastModified":1535786567617,"lastModifiedDate":"2018-09-01T07:22:47.617Z","name":"timg.jpg","size":85009,"type":"image/jpeg","percent":100,"originFileObj":{"uid":"rc-upload-1536137942284-4"},"status":"error","thumbUrl":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAgFBgcGBQgHBgcJCAgJDBMMDAsLDBgREg4THBgdHRsYGxofIywlHyEqIRobJjQnKi4vMTIxHiU2OjYwOiwwMTD/2wBDAQgJCQwKDBcMDBcwIBsgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDD/wAARCAQ4B4ADASIAAhEBAxEB/8QAHAABAAEFAQEAAAAAAAAAAAAAAAECAwQGBwUI/8QARhAAAgEDAwMDAwEFBwIEBQIHAAECAwQRBQYhEjFBB1FhEyJxMhRCgZGhCBUjUrHB0RYzJGJy8CV

**Comment by chenshuai2144** [comment]
上传文件最好用 https://developer.mozilla.org/zh-CN/docs/Web/API/FormData
