### ISSUE TITLE
effects  reject 出错的问题

### ISSUE THREAD

**Issue by rockwong** [ant-design/ant-design-pro#2187]
1. 当在effects 异步中 yield 后面的Promise 返回 reject时，期望的是停止执行后续代码，而现在会报错。

2. 尝试通过在dva 的配置中增加 onError 钩子捕捉错误，但是无法找到dva 配置的正确位置，网站上也没找到配置的地方，PS ： src/pages/.umi 中有dva的配置，但是修改后立马或 npm start 后 会被覆盖还原成修改前的状态

不知道那一步有问题，还请帮忙查看。

**Comment by chenshuai2144** [comment]
去 dva 社区看一下吧

**Comment by rockwong** [comment]
在umi 社区找到。

https://umijs.org/zh/guide/with-dva.html#faq 

create `src/dva.js`, export `config method` for hook usage, for example:

```js
import { message } from 'antd';

export function config() {
  return {
    onError(err) {
      err.preventDefault();
      message.error(err.message);
    },
    initialState: {
      global: {
        text: 'hi umi + dva',
      },
    },
  };
}
```
