### ISSUE TITLE
roadhog-api-doc start 8000 看不到启动内容

### ISSUE THREAD

**Issue by apersonw** [ant-design/ant-design-pro#219]
http://js.189808.top/error.png
后面什么都看不到，请问是什么问题呢？

**Comment by nikogu** [comment]
@apersonw 尝试用 cnpm 重新安装下自己项目的依赖，npm 安装的项目用 roadhog-api-doc 有点问题，还在调

**Comment by apersonw** [comment]
谢谢你了，好的，非常期待最新版本呢！
