### ISSUE TITLE
V2, Config proxy not working

### ISSUE THREAD

**Issue by TranDucBlog** [ant-design/ant-design-pro#2192]
I add
 `proxy: {
    "/api": {
      "target": "http://jsonplaceholder.typicode.com/",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  },` 
to config.js but not working.

**Comment by chenshuai2144** [comment]
https://umijs.org/config/#proxy
umi

**Comment by TranDucBlog** [comment]
@chenshuai2144 I added the proxy to the config.js file, so that is not correct? What should I do to make it work?

**Comment by mailbaoer** [comment]
@TranDucBlog try start npm without mock
```shell
npm run start:no-mock
```

**Comment by TranDucBlog** [comment]
@mailbaoer I want to use the api from the server, instead of localhost: 8000 using domain.com/api, is my method correct, or do I have to do it differently?

**Comment by yoage** [comment]
@TranDucBlog 
hello,it's work. this is my configure
added into /config/config.js
``` 
 proxy: {
    '/api': {
      target: 'http://api.car.local/',
      changeOrigin: true,
      pathRewrite: {
        '^/api': ''
      }
    }
  }
```

service api 
/src/services/api.js 
```
export async function fakeAccountLogin(params) {
  return request('/api/wechat/member/sign-in', {
    method: 'POST',
    body: params,
  });
```

the origin API "http://api.car.local/wechat/member/sign-in"

and then run without mock 
```
npm run start:no-mock
```

**Comment by lhwu** [comment]
when i run without mock
```
npm run start:no-mock
```
then my page are not found, redirect to 404 error page

**Comment by GuXiangFly** [comment]
> when i run without mock
> 
> ```
> npm run start:no-mock
> ```
> then my page are not found, redirect to 404 error page

I encountered the same problem， do you know how to fix it ？

**Comment by xXAvoraXx** [comment]
Same Problem, After Build, 404 page error.

**Comment by xXAvoraXx** [comment]
> @TranDucBlog
> hello,it's work. this is my configure
> added into /config/config.js
> 
> ```
>  proxy: {
>     '/api': {
>       target: 'http://api.car.local/',
>       changeOrigin: true,
>       pathRewrite: {
>         '^/api': ''
>       }
>     }
>   }
> ```
> 
> service api
> /src/services/api.js
> 
> ```
> export async function fakeAccountLogin(params) {
>   return request('/api/wechat/member/sign-in', {
>     method: 'POST',
>     body: params,
>   });
> ```
> 
> the origin API "http://api.car.local/wechat/member/sign-in"
> 
> and then run without mock
> 
> ```
> npm run start:no-mock
> ```

I try this one good work on localhost but, when I umi build the project, It not work.
