### ISSUE TITLE
谷歌浏览器样式错乱

### ISSUE THREAD

**Issue by shaopeng1** [ant-design/ant-design-pro#2193]
内容区域宽度“定宽”，“流式”在线编辑页面显示错乱，重新刷新后就好了
![1536194685 1](https://user-images.githubusercontent.com/29971876/45128621-99a73500-b1b1-11e8-8727-949e731521d8.jpg)

**Comment by chenshuai2144** [comment]
你的屏幕分辨率？

**Comment by shaopeng1** [comment]
1680*1550（推荐）  和最高1920*1080都是这样的效果
