### ISSUE TITLE
The scroll about modal

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#2194]
When I open a modal with some message, the scroll just shows at the middle of the modal. How could I set the scroll at th top of the modal? 
Thanks, I know it should be a question in ant-design, but I can only pull bug or feature requests. And the  StackOverflow or SegmentFault  could not gives me answer in time. So, please help me.

**Comment by m26597** [comment]
After a period time I've tried to resolved this question, I find that the modal is normal at the first time. But when I reopen the modal, it would remember the position last time. I've tried the destroyOnClose prop but it didn't work

**Comment by chenshuai2144** [comment]
dom.scrollTop=0

**Comment by Symous** [comment]
`document.getElementsByClassName('ant-modal-wrap')[0].scrollTo(0, 0)`
