### ISSUE TITLE
ant-design-pro里面  mock和本地服务器请求可以同时配置吗

### ISSUE THREAD

**Issue by kateli** [ant-design/ant-design-pro#2195]
在开发的时候
先用mock把项目完成后
后台提供了部分接口
在联调的时候
如果启用了start:no-proxy 命令  页面就会不走mock  大量报错，毕竟有些接口 是没有的
但是如果启用了npm start   开启本地mock    就会走本地的mock了  不会走指定服务器的请求
可以满足一个项目里面  既能用mock  也能向指定服务器发送请求嘛

**Comment by xiaohuoni** [comment]
你可以开启mock，然后，部分有本地服务的加个前缀使用proxy。
等全部接口调试完毕，不需要mock时再关闭测试一下。
这样应该可以满足你的要求

**Comment by kateli** [comment]
@xiaohuoni   
是这样吗
发现不好使儿呢
![1](https://user-images.githubusercontent.com/8436428/45203304-4ff04480-b2ae-11e8-8e93-4cc97034a9ed.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#proxy
