### ISSUE TITLE
2.0 win环境下安装依赖ssri报错

### ISSUE THREAD

**Issue by LareinaH** [ant-design/ant-design-pro#2198]
41451 warn react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
41452 warn react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
41453 warn rollup-plugin-commonjs@9.1.6 requires a peer of rollup@>=0.56.0 but none is installed. You must install peer dependencies yourself.
41454 warn rollup-plugin-babel@4.0.3 requires a peer of rollup@>=0.60.0 <1 but none is installed. You must install peer dependencies yourself.
41455 warn babel-plugin-dva-hmr@0.4.1 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
41456 verbose stack Error: sha1-GANKhZmv7Z8iHCrHz22fmuoMmNQ= integrity checksum failed when using sha1: wanted sha1-GANKhZmv7Z8iHCrHz22fmuoMmNQ= but got sha1-9wI4GaL1bRvohPkMZjppSY6KVK0=. (6270008 bytes)
41456 verbose stack     at Transform.on (D:\nodeenv\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
41456 verbose stack     at emitNone (events.js:111:20)
41456 verbose stack     at Transform.emit (events.js:208:7)
41456 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
41456 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
41456 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
41457 verbose cwd D:\rubbish\ant-design-pro-2.0.0
41458 verbose Windows_NT 6.1.7601
41459 verbose argv "D:\\nodeenv\\nodejs\\node.exe" "D:\\nodeenv\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
41460 verbose node v8.11.1
41461 verbose npm  v5.6.0
41462 error code EINTEGRITY
41463 error sha1-GANKhZmv7Z8iHCrHz22fmuoMmNQ= integrity checksum failed when using sha1: wanted sha1-GANKhZmv7Z8iHCrHz22fmuoMmNQ= but got sha1-9wI4GaL1bRvohPkMZjppSY6KVK0=. (6270008 bytes)
41464 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
请描述清楚问题

**Comment by digz6666** [comment]
Clean cache and install again.
```
npm clean cache
npm install
```
