### ISSUE TITLE
Authorized 是否应该放到 render 函数里呢？

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design-pro#2199]
https://github.com/ant-design/ant-design-pro/blob/e47d4b12b6e4e76fb0d3e03a23f3edee29ddca9a/src/pages/Authorized.js#L10

重新登录后，Authorized 的当前权限没有被改变吧

**Comment by chenshuai2144** [comment]
RenderAuthorized 一下就好了

**Comment by tolerance-go** [comment]
https://github.com/ant-design/ant-design-pro/blob/e47d4b12b6e4e76fb0d3e03a23f3edee29ddca9a/src/utils/Authorized.js#L4

RenderAuthorized 的话是不是应该用 utils 下的这个组件

**Comment by chenshuai2144** [comment]
这个好像是为了解决循环引用的问题
