### ISSUE TITLE
V2 版本的代理怎么设置呢?

### ISSUE THREAD

**Issue by iskyshy** [ant-design/ant-design-pro#2203]
我在config/config.js 文件中添加此配置
 proxy: {
    "/api": {
      "target": "http://127.0.0.1:8080",
      "changeOrigin": true,
      "pathRewrite": {"^/api": ""}
    }
  },
启动时使用的命令npm run start:no-mock  命令启动,默认使用的是8000端口,我在设置代理后,后台服务器8080端口不能接收到请求?请问能否详细说明一下应该怎么配置?

**Comment by liyanhuadev** [comment]
我也遇到同样问题，发现是target url的路径没写全 `http://127.0.0.1:8080/context-path`

**Comment by xiaohuoni** [comment]
理解一下
```
"pathRewrite": {"^/api": ""}
```
会将请求地址重的'/api'去掉。
所以你请求的地址是/api/user
可能你需要的是http://127.0.0.1:8080/api/user
但实际代理的是http://127.0.0.1:8080/user
你真实可访问的服务接口是什么？

**Comment by xiaohuoni** [comment]
https://umijs.org/config/#proxy
```
"proxy": {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}
```
然后访问/api/users就能访问到http://jsonplaceholder.typicode.com/users的数据

**Comment by iskyshy** [comment]
我真实可访问的接口地址是 http://127.0.0.1:8080/api/user   http://127.0.0.1:8080/api/adduser 这样的

**Comment by xiaohuoni** [comment]
设置"changeOrigin": false试试

**Comment by iskyshy** [comment]
这个参数表示我跨域请求,现在的原因是同样的代码,在一台机器上能同时运行前后台调试,另外一个同时就不能执行.

**Comment by xiaohuoni** [comment]
试着换个端口看看……^_^

**Comment by iskyshy** [comment]
都试了,都不行另外一个..

**Comment by TaylorZun** [comment]
我的本地代理远程代理都写在了config/config.js里面，接口配置写在另一个文件里，但是貌似不能用。之前的版本是config.js配置接口，在roadhogrc配置代理呢，现在该怎么迁移修改呢~~

**Comment by yoage** [comment]
请问这个问题解决了吗？接口地址 真的不知道怎样配置？新手真无奈

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#proxy

**Comment by 693614965** [comment]
config.js 文件，这样 配置 
cssnano: {
    mergeRules: false,
  },
  proxy: {
    '/api': {
      'target': 'http://localhost:8080/',
      'changeOrigin': true,
      'pathRewrite': { '^/api': '' },
    },
  },

好像 没有效果啊。到底 咋个 玩嘛！

**Comment by jduizhang** [comment]
proxy: {
    '/api': {
      target: 'http://127.0.0.1:8080/',
      changeOrigin: true,
      pathRewrite: {'/api': ''}
    }
  },我这样配置的可以

**Comment by lhwu** [comment]
> 设置"changeOrigin": false试试

设置为false，在config/config.js中配置的这个proxy，通过npm run start 启动的话，proxy不生效，不会调配置的proxy。如果通过no-mock启动，则页面都是会跳转到404的错误页面
