### ISSUE TITLE
打包之后的 css 类名不是哈希而是路径？

### ISSUE THREAD

**Issue by lovemegowin** [ant-design/ant-design-pro#2206]
![image](https://user-images.githubusercontent.com/25566683/45145943-6df96e80-b1f4-11e8-8099-6904b80f46eb.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/config/config.js#L55
删掉这个就好了，但是换主题会坏掉

**Comment by lovemegowin** [comment]
@chenshuai2144 也就是说目前的一个解决方案是 我在主题换好之后再删掉 ？谢谢回复

**Comment by codercatmomi** [comment]
2018-12-18 下载最新的pro代码还是有这个问题。55行是啥？

**Comment by xiaohuoni** [comment]
@codercatmomi win环境吗？

**Comment by codercatmomi** [comment]
@xiaohuoni 是的

**Comment by xiaohuoni** [comment]
@codercatmomi 你说的这个问题已经处理了

**Comment by codercatmomi** [comment]
@xiaohuoni 感谢~
