### ISSUE TITLE
npm start 无反应

### ISSUE THREAD

**Issue by xchao0213** [ant-design/ant-design-pro#2207]
前几天下载了2.0，在本地npm start后跑了起来，看着项目很赞。每天打开代码学习一下，准备下个项目用上。
今天打开npm start却没有反应了。只出来一句 Starting the development server.... 就没有了，打开localhost:8000也打不开。
看了以前的issues，说什么node占用CPU100%什么，我这儿倒是没有。
还有一句一闪而过的话，拍了录像，发现是[umi-plugin-dll] file list is equal don't generate the dll file，查了一下，应该也没关系。
大家有碰到吗？
node v8.11.1
macOs 10.12.6

**Comment by chenshuai2144** [comment]
```
rm -rf node_module
npm install
```

**Comment by codercatmomi** [comment]
@xchao0213 楼主后来有解决吗
我今天也突然遇到这个问题。前几天都好的
