### ISSUE TITLE
[bug] 在侧边栏缩进的情况下点击/account 子路由会把侧边栏打开

### ISSUE THREAD

**Issue by lovemegowin** [ant-design/ant-design-pro#2209]
RT
复现方法可参考线上预览版本

**Comment by chenshuai2144** [comment]
@sorrycc  还是那个问题，组件重定向会重新渲染整个页面，所有的状态全部清空了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2259
