### ISSUE TITLE
三级菜单面包屑，配置了children属性才能正常显示

### ISSUE THREAD

**Issue by mutouzdl** [ant-design/ant-design-pro#221]
我看到了这个Issue：https://github.com/ant-design/ant-design-pro/issues/128
说是解决了三级路由的问题，但是我配置了三级菜单后，面包屑还是显示了路径。

## 问题重现：
**nva.js配置如下：**
![image](https://user-images.githubusercontent.com/3509249/32926807-30af7c88-cb84-11e7-9b48-7d0069c024ce.png)

**效果如下：**
![image](https://user-images.githubusercontent.com/3509249/32926860-8373ce4c-cb84-11e7-9602-9e7d2281f84f.png)

**后来发现在三级菜单里加上children属性就正常了：**
![image](https://user-images.githubusercontent.com/3509249/32926999-3f31a0dc-cb85-11e7-9aca-df9a6dffdaf5.png)

**效果：**
![image](https://user-images.githubusercontent.com/3509249/32926991-32c3c26c-cb85-11e7-9990-fba7aea451db.png)

## 疑问：
请问，三级菜单确实需要加上children属性吗？
或者说，是我的配置不正确？（源码是昨天拉的）

**Comment by ddcat1115** [comment]
配置有一点问题，如果单纯作为菜单，『查询表格』这一级是不应该有 componnet 的，去掉后（如下配置）面包屑和组件渲染均正常（主贴提到的加上 children 其实不对，BasicList 组件是没有渲染出来的）

```js
name: '列表页',
        path: 'list',
        icon: 'table',
        children: [
          {
            name: '查询表格',
            path: 'table-list',
            children: [{
              name: '测试',
              path: 'test',
              component: dynamicWrapper(app, ['list'], import('../routes/List/BasicList')),
            }],
          },
```

如果这一级（比如这儿的『查询表格』）除了菜单功能，还需要渲染一部分内容，就需要自己在这一级组件内增加路由了，类似 BasicLayout 的做法，需要了解一些 react-router@4 的知识。[前序知识](https://pro.ant.design/docs/router-and-nav-cn#前序知识)

**Comment by mutouzdl** [comment]
@ddcat1115 明白了，谢谢！
