### ISSUE TITLE
NoticeIcon.Tab title automatically adding a count

### ISSUE THREAD

**Issue by Emsu** [ant-design/ant-design-pro#2216]
I have a NoticeIcon.Tab where the title is "Notifications".

I'm passing it a list of 10 notifications however I don't want the number 10 to show up. Right now the title is showing "Notifications (10)". How can I override this?

The use case is that I want the count to be based off of the number of unread notifications. So even though I'm showing 10, I want the count to be 0. And since I'm paginating the data, there's actually hundreds of hidden notifications so the number 10 makes no sense. Ideally I could just not show a count on the `NoticeIcon.Tab` and show the count only on the `NoticeIcon` count prop

**Comment by jakubknejzlik** [comment]
Seems to be already implemented: https://github.com/ant-design/ant-design-pro/pull/2862

**Comment by Emsu** [comment]
@jakubknejzlik ah awesome! seems like it got implemented recently

thanks @chenshuai2144!

I'll close it now
