### ISSUE TITLE
pro2.0直接build完之后，启动webservices服务，刷新路由就down了

### ISSUE THREAD

**Issue by freedomljt** [ant-design/ant-design-pro#2219]
pro2.0直接build完之后，启动webservices服务，刷新路由就down了。

**Comment by freedomljt** [comment]
![wechatimg34](https://user-images.githubusercontent.com/3245574/45195503-7308fd00-b28a-11e8-913a-f48be9bcfc48.jpeg)

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88

**Comment by mushroomlb** [comment]
nginx 配置如下，后端也需要配置
server{
    listen 80;
    server_name _;
    location / {
      root /xxx/;
      index index.html;
      try_files $uri /index.html;
    }
    location /api {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host:80;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }
}
