### ISSUE TITLE
最新版 0.2.3-rc.1 导航样式显示有问题

### ISSUE THREAD

**Issue by jiechud** [ant-design/ant-design-pro#222]
### 导航显示有问题 （0.2.3-rc.1）

1.  样式 z-index 有问题
![image](https://user-images.githubusercontent.com/9709396/32927355-0c473b58-cb87-11e7-9868-a1f65864e7bc.png)

2.  当前选中的导航样式
![image](https://user-images.githubusercontent.com/9709396/32927388-341ee716-cb87-11e7-8f29-f6c676a4a3d4.png)

**Comment by DingLiPlus** [comment]
导航栏收起状态下的确是存在这个问题，而且在垂直菜单弹出的时候比较卡顿。

**Comment by zjp2007** [comment]
在0.3.0上有新问题，收缩后菜单长度有问题
![image](https://user-images.githubusercontent.com/20635787/33107788-c5ed672c-cf73-11e7-995c-a2a0e15a49bb.png)

**Comment by afc163** [comment]
Reinstall node_modules.

**Comment by afc163** [comment]
Reinstall node_modules.
