### ISSUE TITLE
为什么在src下的代码中读取环境变量，读不到

### ISSUE THREAD

**Issue by xiaoquanWu** [ant-design/ant-design-pro#2222]
在package.json 如下
` "scripts": {
    "start": "cross-env ENV_PATH=abc BROWSER=none HARD_SOURCE=none ESLINT=none roadhog dev",
    "start:no-proxy": "cross-env NO_PROXY=true ESLINT=none roadhog dev",
    "build": "cross-env ESLINT=none roadhog build && gulp build:pro",
    ....
  },`

为什么  `console.log(process.env.NODE_ENV)` 有值（为"development"）， 而console.log(process.env.ENV_PATH) 为 **undefined**

**Comment by chenshuai2144** [comment]
环境变量是 node 中的，可以看看 webpack 相关的介绍

**Comment by afc163** [comment]
我们是不是没加 https://webpack.js.org/plugins/define-plugin/

**Comment by afc163** [comment]
哦对，其他环境变量不应该默认传递进去。

**Comment by afc163** [comment]
https://umijs.org/zh/config/#define
