### ISSUE TITLE
dispatch 发送后，会重新渲染一次？

### ISSUE THREAD

**Issue by shaodawei2017** [ant-design/ant-design-pro#2223]
dispatch 发送到 model 层的effects函数中，该effect是个空函数，并没有往后台发送请求，也没用使用put调用reducers改变状态，为什么回重新渲染组件？
因此，如果调用后台，拿到返回值并更改model层状态，会渲染两次。

**Comment by afc163** [comment]
如果是 dva 的问题，建议提到 https://github.com/dvajs/dva

**Comment by zhuanglong** [comment]
可能是 dva-loading
