### ISSUE TITLE
pro2.0本地build之后，启动webservice，首次进入页面成功，直接刷新页面，直接失效；

### ISSUE THREAD

**Issue by freedomljt** [ant-design/ant-design-pro#2224]
<img width="781" alt="wechatimg35" src="https://user-images.githubusercontent.com/3245574/45203637-5c28d180-b2af-11e8-92b7-7b06fda4c9cf.png">
<img width="801" alt="wechatimg36" src="https://user-images.githubusercontent.com/3245574/45203638-5c28d180-b2af-11e8-9d74-5b79140d4e32.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/2219#issuecomment-419309422

**Comment by freedomljt** [comment]
按照教程其实也没有说明白问题，完全不知道问题出在哪里？@afc163

**Comment by freedomljt** [comment]
@afc163 项目直接启动的时候，首次进入是正常的，在里面点击跳转也没问题，但是直接刷新，就直接404了～

**Comment by afc163** [comment]
https://react-guide.github.io/react-router-cn/docs/guides/basics/Histories.html
