### ISSUE TITLE
v2版本部署后 401错误未正常登出

### ISSUE THREAD

**Issue by sp0cket** [ant-design/ant-design-pro#2225]
在本地返回401错误的时候能够正常dispatch`login/logout`，但是在部署到服务器上之后这个dispatch没有任何反应

**Comment by chenshuai2144** [comment]
请给出一个重现，官方 demo 表现正常

**Comment by sp0cket** [comment]
就是antd-pro修改的，在本地debug时表现也很正常，在nginx服务器上部署之后`window.g_app._store.dispatch`这行代码执行无效，控制台没有报错信息，在1.x中通过store.dispatch没有任何问题

**Comment by sp0cket** [comment]
https://github.com/umijs/umi/issues/516 应该和这个有关，但是没找到更多资料

**Comment by sp0cket** [comment]
@chenshuai2144 刚刚重新clone了一下仓库 ，修改了一下request.js中的url，让其指向一个会返回401的地址，发布到nginx之后访问也仅仅只是弹窗报了401错误，并没有触发dispatch
nginx配置如下：
```
location / {
             try_files $uri /index.html;
}
```

**Comment by huangshunping** [comment]
我也遇到了相同的问题，就是本地都正常（umi dev是对的），umi build后

**Comment by chenshuai2144** [comment]
将 login store 提到 全局就好了。

**Comment by lisztj** [comment]
我这边加了setTimeOut就拿到sotre里的dispath了
 `setTimeout(() => {
          console.log(window.g_app);
          window.g_app._store.dispatch({
            type: "login/logout"
          });
        }, 200);
`
![E2F24CD1-F1F4-45A4-9FE6-0C1D9A2C31EE](https://user-images.githubusercontent.com/14845217/97544509-ac6dcb00-1a04-11eb-8d15-8f5a4412f2a3.png)
