### ISSUE TITLE
如何获得store呢

### ISSUE THREAD

**Issue by leftluoyi** [ant-design/ant-design-pro#2227]
以前有个dva的[问题](https://github.com/dvajs/dva/issues/1761)，主要是关于回调函数如何generator的。一直没有最终的解决方法，所以我用的是

```
      store.runSaga(function* () {
        yield put({type:'something', payload: retVal})
      })
```

这个代码来解决，一直没有出现问题。现在升级到了antd pro 2.0，dva的不用自己来生成了，那要如何才能获取到store，从而手动来`runSaga`呢？

**Comment by ergoulee** [comment]
我看以前的utils/request.js里
`import store from '../index';`
现在的
`window.g_app._store`
这个_store是怎么来的?

**Comment by sp0cket** [comment]
@ergoulee https://github.com/umijs/umi/blob/0413c1b65287551b9dbf48096f5f0578f3ebf549/docs/zh/guide/with-dva.md#如何访问到-store-或-dispatch-方法

**Comment by leftluoyi** [comment]
@ergoulee 感谢
