### ISSUE TITLE
bug！打开-整体风格设置-固定侧边菜单选项 在screen-xs适配下  有pandding-left:80px

### ISSUE THREAD

**Issue by soonnyt** [ant-design/ant-design-pro#2230]
![image](https://user-images.githubusercontent.com/17094098/45229129-9fa72e00-b2f7-11e8-9997-549b1d899945.png)
![image](https://user-images.githubusercontent.com/17094098/45229148-aafa5980-b2f7-11e8-86f9-970ff9644962.png)

**Comment by Warden-Thresh** [comment]
在 #2175 中已经提过, #2215 中已经修复
