### ISSUE TITLE
v2.0权限验证不通过跳转到登录页

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design-pro#2234]
之前是在src/route下大概：
          <Route path="/user" component={UserLayout} />
          <AuthorizedRoute
            path="/"
            render={props => <BasicLayout {...props} />}
            authority={['admin', 'user']}
            redirectPath="/user/login"
          />
现在在config里面怎么配，还有怎么从后台获取动态生成菜单与权限？

**Comment by zhuanglong** [comment]
![baidushurufa_2018-9-9_12-25-27](https://user-images.githubusercontent.com/19422011/45261080-8dc6a780-b42b-11e8-8d0e-8a3d1ebd3fd7.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2157
