### ISSUE TITLE
Bug滚动条进度会在页面间传递，导致打开新页面不定位到页面顶部

### ISSUE THREAD

**Issue by Warden-Thresh** [ant-design/ant-design-pro#2235]
滚动到一个页面到底部时，打开另一个页面进度会传递过去，打开的页面不会在top位置，会滚动到中间位置，该情况发生在再次打开之前的页面时，第一次打开页面则不会出现这种情况。卡片列表和标准列表每次打开都回到top，但是查询表格就会受到之前页面影响，这是什么原因。

**Comment by chenshuai2144** [comment]
可以加一个 `document.documentElement.scrollTop=0`
