### ISSUE TITLE
怎么把antdesign和antdesign-pro 里的icon结合在一起使用

### ISSUE THREAD

**Issue by daniel0115** [ant-design/ant-design-pro#2237]
在我的富文本编辑器里我使用antdesign的icon去设计图标，但我发现bold这个icon是pro，然后bars这个icon是ant-design有的。 现在我遇到问题是antdesign-pro里面的icon显示不出来。
```
<Icon type=“bars” theme="outlined" />
```
这是效果：
![image](https://user-images.githubusercontent.com/42552513/45257124-e166c180-b355-11e8-80e1-5e96b56c8ff5.png)

`<Icon type="bold" theme="outlined" />`
这是效果：
![image](https://user-images.githubusercontent.com/42552513/45257142-3acef080-b356-11e8-9dd2-b8d2ccda369b.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/biz-icon-cn
