### ISSUE TITLE
子路由引入的models，没有生效

### ISSUE THREAD

**Issue by superWendell** [ant-design/ant-design-pro#224]
![tim 20171117111153](https://user-images.githubusercontent.com/23741156/32927551-32b8dbb0-cb88-11e7-8e8b-58e96e52ecf7.jpg)
参照例子写的一个，在文件中这样使用不行
 console.log(this.props.project);
 const { project, activities, chart } = this.props;
如果我放在了主路由上一起加载就可以，子路由不行

**Comment by afc163** [comment]
@WhatAKitty 帮忙看看？

**Comment by superWendell** [comment]
是不是这种引入不能在入口INDEX.jsj里面传递，必须在Info里面，因为这个是子路由，我外面还有一层INDEX 参照的是你们的分布表单

**Comment by nikogu** [comment]
@superWendell 你自组件 `connect` 了吗。。。

**Comment by superWendell** [comment]
@nikogu 
![tim 20171117111153](https://user-images.githubusercontent.com/23741156/32927916-44c9e34c-cb8a-11e7-8af0-0046d234e254.jpg)

**Comment by superWendell** [comment]
@nikogu 
![tim 20171117112723](https://user-images.githubusercontent.com/23741156/32927944-683afdac-cb8a-11e7-97ea-f5dd9cd7867e.jpg)
这是写在index.js里面的

**Comment by WhatAKitty** [comment]
用的是dva吗？

**Comment by WhatAKitty** [comment]
还有就是有没有simple的样例，直接这样看，看不出来
