### ISSUE TITLE
1.4.4升级至v2版本后的白屏问题

### ISSUE THREAD

**Issue by Nuoky** [ant-design/ant-design-pro#2241]
在1.4.4版本localStorage中antd-pro-authority值为`guest`（v2中为`"guest"`），在更新了v2后，在utils/authority.js中会直接用`JSON.parse()`对其值进行转换，造成白屏异常。
![image](https://user-images.githubusercontent.com/24731549/45262107-8c54a980-b442-11e8-8ac6-61b444349f61.png)

如果用户不主动更改/清空localStorage，问题就会一直存在。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2218
