### ISSUE TITLE
菜单路由从服务器获取？

### ISSUE THREAD

**Issue by xiaolan-it** [ant-design/ant-design-pro#2242]
菜单路由从服务器获取？ 文档不够细 ，按着router.config.js里面数据结构，从model中请求后台获取，在BasicLayout.js getMenuData方法里获取，菜单显示不了，希望在写细一些文档

**Comment by pkaq** [comment]
#https://github.com/umijs/umi/issues/944

**Comment by chenshuai2144** [comment]
看相关 issue 吧，太多了
