### ISSUE TITLE
SyntaxError: Unexpected token a in JSON at position 0

### ISSUE THREAD

**Issue by scotty595** [ant-design/ant-design-pro#2243]
Brand new installation using ant-design-pro-cli - nothing changed from install - any fixes?

`index.js:2178 SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at getAuthority (authority.js:9)
    at Object../src/utils/Authorized.js (Authorized.js:4)
    at __webpack_require__ (bootstrap:772)
    at fn (bootstrap:130)
    at Object../src/models/login.js (login.js:6)
    at __webpack_require__ (bootstrap:772)
    at fn (bootstrap:130)
    at Object../src/pages/.umi/DvaContainer.js (DvaContainer.js:15)
    at __webpack_require__ (bootstrap:772)
    at fn (bootstrap:130)
    at render (umi.js:16)
    at umi.js:27`

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2218

**Comment by GithubGoldMiner** [comment]
@scotty595 I just found that #2218 doesn't have any English answer. So I will answer you here:
This seems to be a LocalStorage issue, I fixed this issue by clearing the localStorage in my browser and everything will be able to work. :)

**Comment by scotty595** [comment]
> @scotty595 I just found that #2218 doesn't have any English answer. So I will answer you here:
> This seems to be a LocalStorage issue, I fixed this issue by clearing the localStorage in my browser and everything will be able to work. :)

That's fine - I can read it :) 

I followed @yrhgame's suggestion and changed line 9 in \src\utils\authority.js from `authority = [JSON.parse(authority)]`; to `authority = [authority];` which worked for me

**Comment by jensamunch** [comment]
Yep that worked. For the next person who sees this:

Put this into the URL on Chrome:
chrome://settings/siteData

Then clear data from 
https://preview.pro.ant.design/

Thanks

**Comment by afc163** [comment]
Check newest `authority.js` in master: https://github.com/ant-design/ant-design-pro/commit/0f15cfc9e7170b2268ce71dccb162bdc20f97e87

**Comment by chandlerq** [comment]
@afc163 I understand we're trying to make it backwards compatible, why not just using a new property name like `antd-pro-role` in new version instead of extending the current code to handle `admin`/`guest`?

**Comment by afc163** [comment]
@chandlerq Changing `antd-pro-role` name may confuse some people, the code is still easy to understand IMO. 😀
