### ISSUE TITLE
V2.0菜单权限怎么加？

### ISSUE THREAD

**Issue by baiyulong** [ant-design/ant-design-pro#2247]

**Comment by afc163** [comment]
https://pro.ant.design/docs/authority-management-cn

**Comment by gatinul** [comment]
> https://pro.ant.design/docs/authority-management-cn

请问这个 `authority: ['admin', 'user']` 菜单权限能否不写死在router.config.js中，而是从服务端读取

**Comment by ybning** [comment]
#3452 https://github.com/ant-design/ant-design-pro/issues/3452
