### ISSUE TITLE
一直报Syntax error: Decorators are not officially supported yet in 6.x pending a proposal update.

### ISSUE THREAD

**Issue by masonyeh** [ant-design/ant-design-pro#225]
.babelrc文件也设置了，babel-plugin-transform-decorators-legacy也安装了，就是一直报以下错误。。。

./src/routes/Forms/StepForm/index.js
Syntax error: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
    

  11 | 
  12 | @Form.create()
> 13 | class StepForm extends PureComponent {
     | ^
  14 |   getCurrentStep() {
  15 |     const { location } = this.props;
  16 |     const { pathname } = location;

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/5cce044192684535c93a23952ec831529b71f350/.roadhogrc#L5

**Comment by masonyeh** [comment]
babelrc 一开始就是没有添加也一样报错的！！@afc163

**Comment by masonyeh** [comment]
因为我这边是按官网上的步骤走的，安装好了 一运行就报这个错误，不管怎么设置都报这个错。npm 5.3.0

**Comment by afc163** [comment]
@masonyeh 你试试 clone master 的跑一下，我们本地都是好的。
