### ISSUE TITLE
是否考虑添加一个生成纯的脚手架命令

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#2250]
实际使用 Pro 时，Pro 提供的范例过多，基本上都需要全部删掉，然后实现自己的业务，删除的过程很麻烦，尤其是认证那一块，相互依赖。对于我来讲，只需要 Pro + antd，其它的使用范例掌握了方法之后没有使用的需求。

是不是可以考虑实现一个纯的 Pro，不包含这些样例，或者每个文件夹下只包含一个样例，比如 model/index component/index 等等。

**Comment by xiaohuoni** [comment]
@zhangjie2012 参考一下https://github.com/xiaohuoni/dva-umi  自己安装一个pro模块，应该满足你的这个需求

**Comment by zhangjie2012** [comment]
@afc163 这项目半年多没更新了···

**Comment by zhuanglong** [comment]
+1

**Comment by huangjianke** [comment]
+1

**Comment by huangshunping** [comment]
+1

**Comment by zengyunchun** [comment]
+1， 现在看源码剥离还是有点痛苦的

**Comment by yutingzhao1991** [comment]
可以关注下 https://github.com/umijs/umi/issues/1350 这个。到时候会把 pro 的没有页面做成一个物料。

**Comment by find456789** [comment]
+1

**Comment by yanwenjia** [comment]
+1

**Comment by a854363956** [comment]
+1

**Comment by LayGit** [comment]
+1

**Comment by anshengme** [comment]
+1

**Comment by yutingzhao1991** [comment]
后面在 https://github.com/ant-design/ant-design-pro/issues/2809 这里跟进。

**Comment by redclown** [comment]
+1
