### ISSUE TITLE
 npm install 报错  No value found for key version at 1:12322 npm ERR! eta.45":{"name":"@babel/plugin-transform-modules-commonjs"

### ISSUE THREAD

**Issue by liukefu2050** [ant-design/ant-design-pro#2251]
git clone最新的代码，install就报错，需要安装什么吗？node.js git是安装好的
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! No value found for key version at 1:12322
npm ERR! eta.45":{"name":"@babel/plugin-transform-modules-commonjs","version":
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2018-09-10T05_42_21_677Z-debug.log
尝试安装ant-design-pro-cli 也报错
$ npm install ant-design-pro-cli -g
$ npm install ant-design-pro-cli -g
npm ERR! Unexpected end of input at 1:6008
npm ERR! dora-plugin-webpack","version":"0.6.6","dependencies":{"chalk":"^1.1.
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2018-09-10T05_47_53_343Z-debug.log

**Comment by afc163** [comment]
网络问题，建议使用 cnpm

**Comment by esofar** [comment]
I have the same problem with you.

**Comment by liukefu2050** [comment]
first you need install cnpm
then run "cnpm install " in command windows
