### ISSUE TITLE
最新版本官网ant-design-pro运行报错

### ISSUE THREAD

**Issue by ShaoFei10027** [ant-design/ant-design-pro#2252]
![image](https://user-images.githubusercontent.com/25678734/45285794-9c3dbd80-b516-11e8-95ef-f365ad40ab05.png)

**Comment by xiaoxiangmoe** [comment]
see https://github.com/ant-design/ant-design-pro/issues/2218

**Comment by afc163** [comment]
node 版本太老了，升级上来。https://stackoverflow.com/questions/40421825/how-to-use-object-values-on-server-side-in-node-js
