### ISSUE TITLE
Redirect 引发整个页面重绘

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#2259]
从 Menu 点击切换进入这个页面 https://preview.pro.ant.design/form/step-form/info

会导致 BasicLayout 的 componentDidMount 再次触发。

**Comment by siyu77** [comment]
同样的问题, redirect 使 BasicLayout 组件重新构造了.

**Comment by sorrycc** [comment]
@yutingzhao1991 redirect 根据 bigfish 的传统，提到了页面最顶层，所以会 redirect 。

**Comment by yutingzhao1991** [comment]
当时提到前面是有原因的，不然可能会另外的一个问题：

如果跳转放到后面那么比如类似下面的路由：

```js
const routes = [
{
  path: '/admin',
  component: 'Admin',
},
{
  path: '/',
  component: 'BasicLayout',
  routes: [{
    path: '/redirect',
    redirect: '/admin',
  }]
}];
```

这种情况下如果访问 `/redirect`，那么 BasicLayout 会被先挂载，然后再跳转。

cc @zinkey 除了这个还有其他原因吗？

bigfish 之前我有提一个 issue： http://gitlab.alipay-inc.com/bigfish/bigfish/issues/198
