### ISSUE TITLE
全局属性collapsed不起作用

### ISSUE THREAD

**Issue by yaoleiroyal** [ant-design/ant-design-pro#2261]
在models目录下的global.js文件中，有一个控制侧边栏是不是收缩的属性，我设置为true之后，侧边栏仍然没有收缩。
麻烦查一下原因，我看了一下Sider里的代码，好像有什么判断，自动把侧边栏展开了。

**Comment by afc163** [comment]
Sider 会根据 breakpoint 的设置和浏览器窗口宽度自动触发 onCollapse 。

你可以去掉 `breakpoint`：https://github.com/ant-design/ant-design-pro/blob/9e6266030a6bfc39403c8d344c84e5b9e9d6e520/src/components/SiderMenu/SiderMenu.js#L104
