### ISSUE TITLE
日历在中文模式下有问题

### ISSUE THREAD

**Issue by yaoleiroyal** [ant-design/ant-design-pro#2262]
看一下预览“https://preview.pro.ant.design/form/basic-form”网页，表单中关于日期的展示，在中文模式下，并没有全部展示成中文，像星期等都还是英文。

**Comment by GithubGoldMiner** [comment]
@yaoleiroyal 我记得在v1的时候还有一个`antd`提供的`localeProvider`可以解决这个问题, 针对你的问题我搜了搜v2 preview的代码库似乎里面并没有控制form control和breadcrumb的本地化调控机制，似乎`'config/config.js'`和`'umi/locale'`里的`setLocale()`和`getLocale()`也并不能调控components的语言。请管理员大哥确认下我的理解是否正确

**Comment by afc163** [comment]
你们这些家伙，有空先搜一下 issue 不行么，哼😒

https://github.com/ant-design/ant-design-pro/issues/2184#issuecomment-419308664

**Comment by GithubGoldMiner** [comment]
@afc163 咳咳 :pray: :kissing_heart: :pray:
