### ISSUE TITLE
npm install 获取antd-with-locales.js.map失败

### ISSUE THREAD

**Issue by a401554998** [ant-design/ant-design-pro#2264]
如题：今天拉取最新版本，npm install 执行过程中下载antd-with-locales.js.map 失败。
npm  6.4.0 (registry设置的是：http://registry.npm.taobao.org/)
system win10
![20180911100324](https://user-images.githubusercontent.com/26255660/45333664-fcca0a80-b5a9-11e8-927a-abab2c32aac6.png)

**Comment by chenshuai2144** [comment]
看起来像是权限问题。 删除所有的包试试

**Comment by a401554998** [comment]
应该不是这个错误，我独立安装antd 是能通过的，先关闭吧，我也想不来是为什么
