### ISSUE TITLE
yarn build之后的版本 还有 SettingDrawer 

### ISSUE THREAD

**Issue by kalsolio** [ant-design/ant-design-pro#2269]
使用yarn build 打开的页面还带配置按钮
>         {rendering && process.env.NODE_ENV === 'production' ? null : ( // Do show SettingDrawer in production
>           <SettingDrawer />
>         )}

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/commit/b91626801f56073f76308825fb443f21b753a26f

**Comment by liuqiiiiiii** [comment]
怎么去掉这个 SettingDrawer 呢，总在右侧的居中位置，看起来好烦啊。
![image](https://user-images.githubusercontent.com/32216634/47276396-482ff980-d5e9-11e8-93bd-e9c177a78696.png)

删除了很多 defaultSetting 和 SettingDrawer 路径，但都不行，是我没找对地方吗？
![image](https://user-images.githubusercontent.com/32216634/47276494-dc9a5c00-d5e9-11e8-93ae-440c1a5844b2.png)
