### ISSUE TITLE
Preview is broken

### ISSUE THREAD

**Issue by jensamunch** [ant-design/ant-design-pro#2270]
Hey,

https://preview.pro.ant.design/
Does not show anything on latest Chrome.

<img width="1440" alt="screen shot 2018-09-11 at 11 03 31" src="https://user-images.githubusercontent.com/1650140/45353274-57676480-b5b2-11e8-82be-328766e0da3a.png">

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2243#issuecomment-420283433

look this

**Comment by GithubGoldMiner** [comment]
@jensamunch Can you try to clear your localStorage in your broswer and try it again?

**Comment by afc163** [comment]
@chenshuai2144 加个兼容重新部署一下 preview 吧，省得这么多提问。
