### ISSUE TITLE
cnpm install error

### ISSUE THREAD

**Issue by effortComeOn** [ant-design/ant-design-pro#2271]
deprecate puppeteer@1.8.0 › debug@^3.1.0 `debug` versions 3.2.0-3.2.2 break Node 4. Users of node LTS and onward (modern Node versions): please upgrade to `debug@4` or above as soon as possible. Node 4 users: please pin to `debug@>=3.2.3 <4` as it will be the last version range that supports Node@4.
Recently updated (since 2018-09-04): 3 packages (detail see file C:\react.js\ant-design-pro\node_modules\.recently_updates.txt)
  Today:
    → puppeteer@1.8.0 › debug@^3.1.0(3.2.4) (17:12:30)
    → puppeteer@1.8.0 › https-proxy-agent@2.2.1 › agent-base@4.2.1 › es6-promisify@5.0.0 › es6-promise@^4.0.3(4.2.5) (06:10:11)

**Comment by GithubGoldMiner** [comment]
@effortComeOn Is it possible that this error is related to your Node version? Can you try to update your Node runtime to 8.12.0 and try again?

**Comment by afc163** [comment]
I don't see any error in your log.
