### ISSUE TITLE
config proxy代理配置问题。

### ISSUE THREAD

**Issue by sm0king** [ant-design/ant-design-pro#2273]
当我们有时候，我们会遇到这种情况：
['/a','/b','/c','/d']  这四个接口访问， 1.1.1.1这个服务器。
['/e','/f','/g','/h']  这四个接口访问， 2.2.2.2这个服务器。
 我们进行prox代理设置的时候，使用  context 来配置，需要大概这么写：
proxy: [{
   context: ['/a','/b','/c','/d'],
   target: '//1.1.1.1'
 },
{
   context: ['/e','/f','/g','/h'],
   target: '//2.2.2.2'
 }]
这个，webpack的 devServer也是可以这么写的。
可是，现在我们在运行的时候却报错：
watch handler failed, since 配置 proxy 校验失败, The proxy config must be Plain Object, but got [object Object],[object Object]

**Comment by chenshuai2144** [comment]
去 umi 发起一个 pr 吧，现在 umi 不支持
