### ISSUE TITLE
Login组件state中的tabs值不正确

### ISSUE THREAD

**Issue by baicx1987** [ant-design/ant-design-pro#2274]
1. 不知道Login组件state中的tabs数组是什么作用
2. 向子组件传入的tabUtil对象中的addTab作用是为tabs添加数据，但调用的setState函数为异步函数，渲染多个LoginTabs会同时调用，导致tabs数据不正确
3. Login组件调用过程会多次调用render方法，且首次渲染tabs为空数组，不知道有什么意图
4. 本人初学者，学习过程中遇到的疑问

**Comment by chenshuai2144** [comment]
Login的设计的确不够优雅。欢迎 pr。
