### ISSUE TITLE
有bug 在mac 谷歌浏览器最新 版本 ui 有变化的那个 谷歌版本 69.0.3497.92  

### ISSUE THREAD

**Issue by sowdf** [ant-design/ant-design-pro#2276]
index.js:2178 SyntaxError: Unexpected token a in JSON at position 0 出现这个bug  我在safari  下可以打开  麻烦帮忙看下   我更新到 版本 70.0.3538.9（正式版本）dev （64 位） 的谷歌浏览器 也是不行的  同样的错误

**Comment by sowdf** [comment]
突然发现不是这个谷歌浏览器的原因  好像是写着写着 就出bug 了

**Comment by sowdf** [comment]
![image](https://user-images.githubusercontent.com/16848523/45396739-ae7f3f00-b66f-11e8-9afd-9f3ed4929087.png)
这个问题不知道什么原因

**Comment by sowdf** [comment]
换个域名就可以了

**Comment by chenshuai2144** [comment]
清空localStorage

**Comment by sowdf** [comment]
有bug 修一下
你们都发现这个bug le 
我还以为 那个 有问题

**Comment by sowdf** [comment]
http://5qpyp3na.sowdf.com/user/login?redirect=http%3A%2F%2F5qpyp3na.sowdf.com%2Fdashboard%2Fmonitor

**Comment by sowdf** [comment]
我还以为谷歌浏览器有问题

**Comment by sowdf** [comment]
![image](https://user-images.githubusercontent.com/16848523/45396914-4aa94600-b670-11e8-88b4-4fa3f708d94d.png)
权限问题是吗
