### ISSUE TITLE
v2 Remove the Hard coding

### ISSUE THREAD

**Issue by bluebu** [ant-design/ant-design-pro#2278]
Remove the Hard coding, or put it to the config.js. It will cause 1s delay to call  remote server API

https://github.com/ant-design/ant-design-pro/blob/9e6266030a6bfc39403c8d344c84e5b9e9d6e520/src/utils/utils.js#L182

https://github.com/ant-design/ant-design-pro/blob/9e6266030a6bfc39403c8d344c84e5b9e9d6e520/src/utils/request.js#L69

https://github.com/ant-design/ant-design-pro/blob/9e6266030a6bfc39403c8d344c84e5b9e9d6e520/src/utils/request.js#L107

**Comment by chenshuai2144** [comment]
这个是为了防止坑业务线。
