### ISSUE TITLE
浏览器标签显示问题

### ISSUE THREAD

**Issue by Captain-G** [ant-design/ant-design-pro#2284]
第一次加载的时候浏览器标签显示ant design pro
进入之后显示分析页-ant design pro
右上角退出登录，标签页显示localhost:8081/user/login?redirect……
![f679a705-a9f7-4cad-86cf-b8ddc3eeb98c](https://user-images.githubusercontent.com/29189543/45460874-8d335700-b732-11e8-9491-877f9aad96d0.png)
![319f90ab-3392-40ec-ac73-a9febeca78e4](https://user-images.githubusercontent.com/29189543/45460875-8dcbed80-b732-11e8-8fea-d58befa376a7.png)
![eb3eb31a-95a4-4f81-8b19-40d8475c8f51](https://user-images.githubusercontent.com/29189543/45460876-8dcbed80-b732-11e8-82f1-86eb3a8c630d.png)

**Comment by chenshuai2144** [comment]
UserLayout 也应该加一个。
@zhuanglong  有兴趣 pr 吗？

**Comment by zhuanglong** [comment]
@ 还不会使用 pr 。

**Comment by chenshuai2144** [comment]
google 一下，还是很简单的
