### ISSUE TITLE
在服务器上运行run build的时候 Tapable.plugin is deprecated.

### ISSUE THREAD

**Issue by wlexhell** [ant-design/ant-design-pro#2285]
(node:5051) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daguan/.npm/_logs/2018-09-12T09_50_16_397Z-debug.log
ERROR: Job failed: exit status 1
查询了很多解决方案 运行过npm install --save-dev extract-text-webpack-plugin@next都不成功
还是一样

**Comment by tjones0808** [comment]
how was this fixed? i am having this issue

**Comment by wlexhell** [comment]
> how was this fixed? i am having this issue
just try npm install --save-dev extract-text-webpack-plugin@next 
If the operation is not successful
Check your code. Case size may cause error.

**Comment by tjones0808** [comment]
ah yes, i upgrade my npm and nodejs and all is good. thank you
