### ISSUE TITLE
[请教]route信息是如何读到props中，是什么机制？

### ISSUE THREAD

**Issue by JevonYang** [ant-design/ant-design-pro#2287]
在BasicLayout.js和Authorization.js看到route数据，这些数据是从什么地方读到的（router.config.js?）? 是如何读到的？

>// BasicLayout.js 
getMenuData() {
    const {
      route: { routes },
    } = this.props;
    return formatter(routes);
  }

>// Authorization.js 
export default ({ children, route, location }) => {
  const routes = matchRoutes(route.routes, location.pathname);
  ……
};

请教各位大神一下，感谢。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L23

**Comment by JevonYang** [comment]
@chenshuai2144 感谢。
formatter 我理解的是从this.props.route.routes格式化成菜单信息，我想知道的是props.route是怎么来的？

**Comment by afc163** [comment]
在 umi 中注入的，其实就是 react-router，详细可以看 umi 源码。
