### ISSUE TITLE
关于查询表格的筛选功能

### ISSUE THREAD

**Issue by WhaleZ** [ant-design/ant-design-pro#229]
列表页下面的查询表格中，在“状态”那一列中筛选数据时只能选择一种类型的数据进行有效筛选，而不能筛选两种以上的数据，比如我不能筛选出同时选中“关闭”和“运行中”的数据

**Comment by nikogu** [comment]
@WhaleZ 这个是 mock 数据的逻辑，demo 已经修复，不过你自己用的话，需要自己改服务端的处理逻辑
