### ISSUE TITLE
路由权限控制问题

### ISSUE THREAD

**Issue by dlamon** [ant-design/ant-design-pro#2291]
# 重现步骤
1、使用账号 user/123456 登入https://preview.pro.ant.design/
2、菜单中【表单页】子菜单显示正确，需要admin权限的【高级表单】菜单项不可见。
3、直接输入https://preview.pro.ant.design/form/advanced-form/ 访问，
    【高级表单】页面被显示，没有出现403 异常页面。

**Comment by Veigar-C** [comment]
src/util/authority ?

**Comment by afc163** [comment]
@chenshuai2144 重新部署下吧。
