### ISSUE TITLE
ant-design-pro@^2.0.0版本@antv/data-set和bizcharts冲突

### ISSUE THREAD

**Issue by aijle** [ant-design/ant-design-pro#2292]
ant-design-pro@^2.0.0依赖于
"@antv/data-set": "^0.9.0"--"@antv/util": "~1.1.1"
"bizcharts": "^3.1.10"--"@antv/g2": "3.2.7"-"@antv/util": "~1.0.12"
完全加载没有问题，使用按需加载bizcharts的时候出错，临时解决方法是自己添加依赖
"@antv/data-set": "^0.8.7",
"@antv/util": "^1.0.12"

**Comment by chenshuai2144** [comment]
可以使用 pro 导出的bizcharts
