### ISSUE TITLE
page\account中是不是没有上传base.js

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#2295]
![image](https://user-images.githubusercontent.com/7875572/45475033-c5a45680-b76d-11e8-82d7-89e73c035910.png)
![image](https://user-images.githubusercontent.com/7875572/45475054-d3f27280-b76d-11e8-8d3a-d41ad79a2d45.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/45528321-4ddc3780-b812-11e8-9fab-714133c14f49.png)


检查一下你的 router 配置吧，以master为准
