### ISSUE TITLE
hashhistory +按需加载打包后私有model下的subscriptions执行顺序问题

### ISSUE THREAD

**Issue by Nuoky** [ant-design/ant-design-pro#2296]
版本：
v2

构建配置：
hashhistory、按需加载

问题：
开启按需加载后在浏览器地址栏改变URL的query参数后，私有modle下的subscriptions执行顺序低于页面的componentWillReceiveProps，开发环境或不开按需加载时是没有问题的。

举例：
models/global.js
```
...
subscriptions: {
 setup({ dispatch, history }) {
      history.listen(({ pathname, search }) => {
        console.log('Run-global-history.listen');
        ...
      });
  },
}
```
pages/Profile/models/profile.js
```
...
  subscriptions: {
    setup({ history }) {
      history.listen(({ pathname, search }) => {
        console.log('Run-profile-history.listen');
      });
    },
  },
```
pages/Profile/BasicProfile.js
```
...
componentWillReceiveProps(nextProps) {
    console.log('Run-BasicProfile-componentWillReceiveProps');
}
...
```

访问：
http://xxxx.com/#/profile/basic?start_date=2018-09-10&end_date=2018-09-12

更改浏览器地址栏query：
http://xxxx.com/#/profile/basic?start_date=2017-09-10&end_date=2018-09-12

开发环境/非按需加载构建后，devtool：
Run-global-history.listen
Run-profile-history.listen
Run-BasicProfile-componentWillReceiveProps

按需加载构建后，devtool：
Run-global-history.listen
Run-BasicProfile-componentWillReceiveProps
Run-profile-history.listen

这时如果我想在subscriptions中监听存储query，再去componentWillReceiveProps中发起请求就没办法获取最新的query。

**Comment by chenshuai2144** [comment]
@yutingzhao1991

**Comment by chenshuai2144** [comment]
如果需要在多处使用，将 modal 移到 src/models 即可
