### ISSUE TITLE
Modal content does not work with FormattedMessage

### ISSUE THREAD

**Issue by tommyspot** [ant-design/ant-design-pro#2297]
Currently, I'm developing a project base on Ant Design v2, I have a problem when applying i18n into Modal.

>   
     Modal.confirm({
        type: CONFIRM_MODAL_TYPE.delete,
        title: formatMessage(messages.deleteContactTitle),
        content: (
          <FormattedMessage
            {...messages.deleteContactContent}
            values={{ name: <span className={Styles.highlight}>{deletedContact.name}</span> }}
          />
        ),
        okText: 'Delete',
        cancelText: 'Cancel',
        onOk(closeModal) {
          return new Promise(() => handleDelete(deletedContact, closeModal)).catch(() => {});
        },
        onCancel() {},
      });

When I declare FormattedMessage tag, I get an error on console log:

> [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

<img width="893" alt="screen shot 2018-09-13 at 3 37 53 pm" src="https://user-images.githubusercontent.com/7645519/45477140-0fd80880-b76b-11e8-8577-8561876113ff.png">

I use formatMessage, it works normally, but FormattedMessage not. Do you have any solution?

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/i18n

use `formatMessage `

**Comment by tommyspot** [comment]
Hi @chenshuai2144,
Regarding formatMessage, I want to add a variable in defaultMessage as below example (https://github.com/yahoo/react-intl/wiki/API#formatmessage):

const messages = defineMessages({
    greeting: {
        id: 'app.greeting',
        defaultMessage: 'Hello, {name}!',
        description: 'Greeting to welcome the user to the app',
    },
});

formatMessage(messages.greeting, {name: 'Eric'}); // "Hello, Eric!"

Currently, I recognize it does not work.
