### ISSUE TITLE
更新到2.0，用IE访问 : 对象不支持“assign”属性或方法

### ISSUE THREAD

**Issue by roy-sun** [ant-design/ant-design-pro#2298]
![20180913200640](https://user-images.githubusercontent.com/20795539/45487309-8dfad600-b790-11e8-885a-6aba4916fb8c.png)

**Comment by afc163** [comment]
@chenshuai2144 找绝云升级下 data-set 的打包。

**Comment by chenshuai2144** [comment]
done https://github.com/ant-design/ant-design-pro/commit/9fff7f84eeb560de1fdf4a557a64d5bdeab04569
