### ISSUE TITLE
Tiny English Typo

### ISSUE THREAD

**Issue by codesignist** [ant-design/ant-design-pro#2299]
**Glue** should **Blue**.
https://github.com/ant-design/ant-design-pro/blob/9ef3ce09d98ae6af03fb50917549ae7c35fef6e3/src/locales/en-US.js#L172

Btw, do you need Turkish Localize file? I have already prepared one.

**Comment by chenshuai2144** [comment]
yes,you can start working.
very thx!

**Comment by afc163** [comment]
I don't think we should add other locale built-in, you can create another repository as third resource that we can recommend in our documentation.

**Comment by codesignist** [comment]
@chenshuai2144 I would be honoured.

@afc163 Okay. Maybe I create another repo in the future.

Thank you.
