### ISSUE TITLE
登录页如果未加载的情况下，点击退出登录时。  yield put(routerRedux.push('/user/login'));）似乎不起作用

### ISSUE THREAD

**Issue by lanke** [ant-design/ant-design-pro#230]
只有主动点击jia'zai加载下登录页， 再点退出登录才能起作用

**Comment by ddcat1115** [comment]
不太明白，『登录页未加载』指什么？请提供下具体的重现步骤及问题表现，能有截图之类的就更好了

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/commit/0688459ba17259dc28626c47ee53a46b2f444dc9
