### ISSUE TITLE
config 文件中配置proxy无效

### ISSUE THREAD

**Issue by jeffrey-bin** [ant-design/ant-design-pro#2302]
![s2d5__ 3 g h3ou yto9](https://user-images.githubusercontent.com/23428596/45544823-01f9b480-b84b-11e8-8da5-e098efd89c41.png)
![1536920460 1](https://user-images.githubusercontent.com/23428596/45544825-02924b00-b84b-11e8-9d00-d78ac133868f.jpg)

**Comment by superbervin** [comment]
文档里面没有说明如何切换proxy，请问是通过在配置文件里面加proxy选项切换proxy的么？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2303

**Comment by chenshuai2144** [comment]
提问之前先搜一下历史 issue

**Comment by xiaohuoni** [comment]
配置了就生效，但不好说是切换，因为proxy和mock可以一起使用。

**Comment by superbervin** [comment]
关键是拉的v2最新的代码配置不生效，搞了半天，不知道啥原因，运行npm run start:no-mock 也一样不行，还是跑的localhost:8000，看了一下之前的issue没有起作用

**Comment by xiaohuoni** [comment]
配置代理，从浏览器查看，请求的地址是不会变化的。只有服务代理了，不是请求路径代理

**Comment by superbervin** [comment]
那我要如何改变请求路径呢？之前v1是可以的啊

**Comment by xiaohuoni** [comment]
一直是这样子的

**Comment by superbervin** [comment]
那请问如何同真实的服务端交互呢？umi的文档就是这么配置接口ip的啊

**Comment by superbervin** [comment]
我看其他isuue这么配置然后npm run start：no_mock就可以了，很绝望，难道要对每一个mock文件都做一个重定向配置吗

**Comment by Hamburg96** [comment]
@superbervin 怎么解决的

**Comment by cccclx** [comment]
你解决了吗   现在我也遇到这个问题了

**Comment by SimonAlong** [comment]
解决了嘛，同问

**Comment by xiaohuoni** [comment]
不懂你们什么问题没解决？

**Comment by zhangWeiZhuang** [comment]
各位大神，关于代理的问题。有进展吗？小弟目前也遇到了这样的问题不知道如何解决，还请各位有经验的分享一下。谢谢~

**Comment by chenshuai2144** [comment]
你们碰到了什么问题？

**Comment by zhangWeiZhuang** [comment]
> 你们碰到了什么问题？

你好，我目前遇到的代理的问题，本地环境代理是可以正常访问到我设置的代理服务器上。但是我打包部署后，却访问的是我网站的接口路径；
![image](https://user-images.githubusercontent.com/44084004/56778564-67624a80-6809-11e9-853a-9349ba06ff67.png)
我用的是 iis部署的，你看，我这边是需要在iis上做什么设置吗？

**Comment by chenshuai2144** [comment]
http://pro.ant.design/docs/deploy-cn#%E5%8F%91%E5%B8%83

**Comment by A-birdFlyHigner** [comment]
remote adress也不会变？

**Comment by Liqiankun** [comment]
@zhangWeiZhuang 我也出现这个问题怎么解决？@chenshuai2144 文档上根本不清楚。

**Comment by emyuan8github** [comment]
我也是一直无效的，不过问题还是可以解决的，就是URL重定向
iis可以安装url重写，不同服务器都可以配置，就是把路径'\api\'拦截，重定向到另一个端口或ip

**Comment by RickyJia2018** [comment]
什么垃圾东西
