### ISSUE TITLE
Ellipsis 组件使用在antd的tootlip组件中时，当children变化，组件tooltip不变

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design-pro#2305]
Ellipsis 组件使用在antd的tootlip组件中时，当children变化，组件tooltip不变
此问题在firefox下能出现，text的高度没有计算对，height为0

如下：
当title发生变化时，tooltip并没有改变
   `
<Tooltip
      title={
        <Ellipsis lines={10}>
          {title}
        </Ellipsis>
      }
    >
      {title}
    </Tooltip>
`

**Comment by chenshuai2144** [comment]
Ellipsis  的 render 被 Tooltip 接管了，你需要手动更新一下。
