### ISSUE TITLE
点击一级菜单（不点击二级跳转页面的菜单）右侧页面里的数据重新loading一下

### ISSUE THREAD

**Issue by zw900420** [ant-design/ant-design-pro#231]
点击一级菜单（不点击二级跳转页面的菜单）右侧页面里的数据重新loading一下，我本地上运行的是这样的，官网例子正常；这是怎么回事？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/commit/5a61434c2453a8bf5607160cb4227a846bc88168

尝试同步一下 master。
