### ISSUE TITLE
Fresh clone: login test fail

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design-pro#2310]
Test is failing on fresh clone of antd pro v2.0.0.

$ git clone https://github.com/ant-design/ant-design-pro.git --depth=1
$ cd ant-design-pro
$ yarn
$ yarn test

> yarn run v1.9.4
> $ umi test
>  PASS  src/components/Ellipsis/index.test.js
>  PASS  src/components/Authorized/CheckPermissions.test.js
>  PASS  src/components/PageHeader/index.test.js
>  PASS  src/components/SiderMenu/SiderMenu.test.js
>  PASS  src/pages/Result/Success.test.js
>  PASS  src/utils/authority.test.js
>  PASS  src/components/_utils/pathTools.test.js
>  FAIL  src/e2e/login.e2e.js (8.847s)
>   ● Login › should login with failure
> 
>     TimeoutError: waiting for selector "#userName" failed: timeout 2000ms exceeded
> 
>       18 | 
>       19 |   it('should login with failure', async () => {
>     > 20 |     await page.waitForSelector('#userName', {
>          |                ^
>       21 |       timeout: 2000,
>       22 |     });
>       23 |     await page.type('#userName', 'mockuser');
> 
>       at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:862:28)
>       at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:753:12)
>       at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:711:17)
>       at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1043:29)
>       at Object.waitForSelector (src/e2e/login.e2e.js:20:16)
>       at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
>       at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
>       at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
>       at asyncGeneratorStep (src/e2e/login.e2e.js:7:103)
>       at _next (src/e2e/login.e2e.js:9:194)
>       at src/e2e/login.e2e.js:9:364
>       at Object.<anonymous> (src/e2e/login.e2e.js:9:97)
> 
>   ● Login › should login successfully
> 
>     TimeoutError: waiting for selector "#userName" failed: timeout 2000ms exceeded
> 
>       28 | 
>       29 |   it('should login successfully', async () => {
>     > 30 |     await page.waitForSelector('#userName', {
>          |                ^
>       31 |       timeout: 2000,
>       32 |     });
>       33 |     await page.type('#userName', 'admin');
> 
>       at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:862:28)
>       at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:753:12)
>       at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:711:17)
>       at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1043:29)
>       at Object.waitForSelector (src/e2e/login.e2e.js:30:16)
>       at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
>       at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
>       at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
>       at asyncGeneratorStep (src/e2e/login.e2e.js:7:103)
>       at _next (src/e2e/login.e2e.js:9:194)
>       at src/e2e/login.e2e.js:9:364
>       at Object.<anonymous> (src/e2e/login.e2e.js:9:97)
> 
>  FAIL  src/e2e/home.e2e.js (20.725s)
>   ● Homepage › it should have logo text
> 
>     Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.
> 
>       2 | 
>       3 | describe('Homepage', () => {
>     > 4 |   it('it should have logo text', async () => {
>         |   ^
>       5 |     const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
>       6 |     const page = await browser.newPage();
>       7 |     await page.goto('http://localhost:8000', { waitUntil: 'networkidle2' });
> 
>       at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
>       at Suite.it (src/e2e/home.e2e.js:4:3)
>       at Object.describe (src/e2e/home.e2e.js:3:1)
> 
> Test Suites: 2 failed, 7 passed, 9 total
> Tests:       3 failed, 40 passed, 43 total
> Snapshots:   0 total
> Time:        24.871s
> Ran all test suites.
> (node:73681) UnhandledPromiseRejectionWarning: Error: Jest failed
>     at _jest.default.runCLI.then.result (/Users/a/Desktop/Github/consumption-tracker/web/node_modules/umi-test/lib/index.js:65:16)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:73681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:73681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ✨  Done in 28.52s.

**Comment by chenshuai2144** [comment]
need first open server
'yarn start'
