### ISSUE TITLE
page/global.js

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#2312]
不加 page/global.js 在IE 11上会报错

![image](https://user-images.githubusercontent.com/18542211/45592865-db9f5a80-b9ab-11e8-82f3-6e3f09011c14.png)

import  "babel-polyfill";

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/2125#issuecomment-418238737

这里应该已经修复了，确认下？

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/pull/2139

**Comment by afc163** [comment]
可以报一下具体问题，理论上不需要 pro 再独自引用 polyfill。

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/45592920-d393ea80-b9ac-11e8-9b92-00895959b14b.png)

**Comment by afc163** [comment]
@sorrycc

**Comment by chenshuai2144** [comment]
这个是我上次提交增加的。

**Comment by afc163** [comment]
find 方法也不应该有问题吧。

**Comment by chenshuai2144** [comment]
ie11不支持的，忘记支持了，加个 polyfill 把

**Comment by afc163** [comment]
这个应该 umi 支持的，pro 里不需要单独加 polyfill。

**Comment by chenshuai2144** [comment]
fixed
