### ISSUE TITLE
2.0 版本 macOS不能跑？

### ISSUE THREAD

**Issue by jiankian** [ant-design/ant-design-pro#2313]
我在macOS上跑提示 dll umi依赖没安装，今天到win10下可以跑。

**Comment by chenshuai2144** [comment]
全局装一下umi好了。理论上不需要的

**Comment by jiankian** [comment]
> 全局装一下umi好了。理论上不需要的


安装了umi的，umi dev命令跑就报错了。macOS不行，win10可以，过程没错，用yarn  cnpm  npm安装依赖试了几次都不行。

**Comment by sanwjt** [comment]
These dependencies were not found:

* babel-runtime in dll umi
* cpy-cli in dll umi

To install them, you can run: npm install --save babel-runtime cpy-cli
一样的问题哦

**Comment by jiankian** [comment]
win10上没问题，macOS就不能跑2.0，1.4.4是可以跑的。唉
哪位大神指点下
![wx20180918-040609](https://user-images.githubusercontent.com/9036838/45647382-51b0d800-baf8-11e8-943e-10f467d25f49.png)

**Comment by NickFranceschina** [comment]
having same issue!

```ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                              17:46:34

This dependency was not found:

* @babel/runtime in dll umi

To install it, you can run: npm install --save @babel/runtime
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
() Guido:~/dev/ddyn/platform-client $ npm install --save babel-runtime
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by NickFranceschina** [comment]
@jiankian ... it appears to work if you clone the latest from the repo ( "release 2.0" is broken)

**Comment by panzj** [comment]
> @jiankian ... it appears to work if you clone the latest from the repo ( "release 2.0" is broken)

安装了其他依赖之后就会出现这个报错？为什么直接关闭issue ，全局装一下umi， 这不是正确解决问题的方式

**Comment by xiaomai7758** [comment]
macOS 10.13.0 ant-design-pro v2.1.1
安装成功,运行失败
- npm i umi -g 还是不行
- npm install --save check-prettier 也不行

**Comment by chenshuai2144** [comment]
有报错吗？

**Comment by dean20160218** [comment]
2.0.0 windows 可以跑 ，mac不行，
![image](https://user-images.githubusercontent.com/17306894/51010796-c371cd80-1590-11e9-980b-fb8e72ec9f35.png)

**Comment by dean20160218** [comment]
2.0.0 windows 可以跑 ，mac不行，
![image](https://user-images.githubusercontent.com/17306894/51011054-e3ee5780-1591-11e9-9346-f7d9df6023f5.png)
To install it, you can run: npm install --save @babel/runtime
还是没用

**Comment by tauruswang** [comment]
c^CJerryWs-MacBook-Pro:my_project jerryw$ pnpm install umi
 WARN  umi > umi-build-dev > af-webpack > eslint-config-umi: eslint-config-react-app@3.0.8 requires a peer of babel-eslint@9.x but version 10.0.1 was inst
alled.
Already up-to-date
Resolving: total 1469, reused 1469, downloaded 0, done
JerryWs-MacBook-Pro:my_project jerryw$ pnpx  umi dev

✖ Webpack
  Compiled with some errors in 11.30s

 ERROR  Failed to compile with 1 errors                                                                                                         2:55:27 PM

This dependency was not found:

* babel-runtime in dll umi

To install it, you can run: npm install --save babel-runtime
JerryWs-MacBook-Pro:my_project jerryw$ pnpm install --save-dev babel-runtime
Already up-to-date
Resolving: total 3, reused 2, downloaded 0, done

dependencies:
- babel-runtime ^6.26.0

devDependencies:
+ babel-runtime ^6.26.0

JerryWs-MacBook-Pro:my_project jerryw$ pnpx  umi dev

✔ Webpack
  Compiled successfully in 11.15s

 DONE  Compiled successfully in 11147ms                                                                                                         2:56:23 PM

File sizes after gzip:

  1.98 MB   umi-dlls/umi.dll.js
  26.73 KB  umi-dlls/umi.css

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb

[umi-plugin-dll] Build dll done
Starting the development server...


✖ Webpack
  Compiled with some errors in 6.25s

Extracted theme color css content length: 7117
 ERROR  Failed to compile with 2 errors                                                                                                         2:56:30 PM

These dependencies were not found:

* regenerator-runtime/runtime in ./src/pages/.umi/polyfills.js
* umi-plugin-locale in ./src/pages/.umi/LocaleWrapper.jsx

To install them, you can run: npm install --save regenerator-runtime/runtime umi-plugin-locale
^C
JerryWs-MacBook-Pro:my_project jerryw$ pnpm install --save-dev regenerator-runtime
Already up-to-date
Resolving: total 1, reused 1, downloaded 0, done
 WARN  There's a directory in node_modules without package.json: /Users/jerryw/MyCode/StudyJS/umidev_dva/my_project/node_modules/umi-dlls

devDependencies:
+ regenerator-runtime 0.13.2

JerryWs-MacBook-Pro:my_project jerryw$ pnpx  umi dev
[umi-plugin-dll] File list is equal, don't generate the dll file.
Starting the development server...


✖ Webpack
  Compiled with some errors in 5.51s

Extracted theme color css content length: 7117
 ERROR  Failed to compile with 1 errors                                                                                                         2:57:45 PM

This dependency was not found:

* umi-plugin-locale in ./src/pages/.umi/LocaleWrapper.jsx

To install it, you can run: npm install --save umi-plugin-locale
 WAIT  Compiling...                                                                                                                             2:57:45 PM


✖ Webpack
  Compiled with some errors in 213.02ms

Extracted theme color css content length: 7117
 ERROR  Failed to compile with 1 errors                                                                                                         2:57:45 PM

This dependency was not found:

* umi-plugin-locale in ./src/pages/.umi/LocaleWrapper.jsx

To install it, you can run: npm install --save umi-plugin-locale
^C
JerryWs-MacBook-Pro:my_project jerryw$ pnpm install --save-dev umi-plubin-locale
 ERROR  404 Not Found: umi-plubin-locale (via https://registry.npmjs.org/umi-plubin-locale)
JerryWs-MacBook-Pro:my_project jerryw$ pnpm install --save-dev umi-plugin-locale
Resolving: total 38, reused 38, downloaded 0, done
Already up-to-date
 WARN  There's a directory in node_modules without package.json: /Users/jerryw/MyCode/StudyJS/umidev_dva/my_project/node_modules/umi-dlls

devDependencies:
+ umi-plugin-locale 2.8.3

JerryWs-MacBook-Pro:my_project jerryw$ pnpx  umi dev
[umi-plugin-dll] File list is equal, don't generate the dll file.
Starting the development server...


✔ Webpack
  Compiled successfully in 5.45s

Extracted theme color css content length: 7117
 DONE  Compiled successfully in 5561ms                                                                                                          2:58:58 PM


  App running at:
  - Local:   http://localhost:8000/ (copied to clipboard)
  - Network: http://192.168.0.105:8000/

 WAIT  Compiling...                                                                                                                             2:58:59 PM


✔ Webpack
  Compiled successfully in 264.79ms

Extracted theme color css content length: 7117
 DONE  Compiled successfully in 270ms                                                                                                           2:58:59 PM

**Comment by AirmaZ** [comment]
同问，我也是这种情况。mac下各种报错。win10就没问题

**Comment by iambocai** [comment]
把dependencies中的` "@babel/runtime": "^7.0.0",` 这行移动到devDependencies 下，重新执行npm install，再启动就可以了
