### ISSUE TITLE
关于Message被Header覆盖的问题

### ISSUE THREAD

**Issue by jason5149** [ant-design/ant-design-pro#2319]
当我在页面头部fixed的时候使用message组件会出现被头部遮住的问题

实际上fixedHeader的z-index: 1061，而message的z-index: 1010
如下图：
![image](https://user-images.githubusercontent.com/10546404/45607696-c811f380-ba80-11e8-8263-e1608644314b.png)

![image](https://user-images.githubusercontent.com/10546404/45607751-0d362580-ba81-11e8-9430-322126807077.png)

希望看一下这个问题哈

**Comment by chenshuai2144** [comment]
会回滚这个操作

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/2ed7ecaa846af27e052687ee0b5d3d6f001f12d9
