### ISSUE TITLE
"npm run build" (roadhog build) question 

### ISSUE THREAD

**Issue by tnngo** [ant-design/ant-design-pro#232]
OS:MAC

npm run build == npm run analyze

@afc163 Sorry,It's too late now, my brain will stop work.I'll pay attention to that next time

**Comment by yesmeck** [comment]
So, what's you question?

**Comment by tnngo** [comment]
@yesmeck In document, "npm run build" will create index.js、index.css、index.html.
But the same as that "run build analyze", create many analyze js

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design-pro/pull/150, these `async.js` files called "code splitting", not analyze file.

**Comment by tnngo** [comment]
@yesmeck  HO,too late and my error.
But, I did not found how to close that in Roadhog's document about chunkFilename. 
Do I need to create webpack.config.js for chunkFilename?
This is troubling in Electron for native App

**Comment by yesmeck** [comment]
https://webpack.js.org/configuration/output/#output-chunkfilename

I don't think you need code splitting if you are building a Electron app.

**Comment by tnngo** [comment]
@yesmeck You are right,,i want to close.
I'm surprised Roadhog did not wrote about how to close chunkfilename.
So,i will try the previous Webpack configuration.
