### ISSUE TITLE
日期选择国际化中文显示不完整

### ISSUE THREAD

**Issue by freecnpro** [ant-design/ant-design-pro#2321]
如下图，日期选择器中文国际化不完整。
<img width="633" alt="2018-09-17 20 20 22" src="https://user-images.githubusercontent.com/3022374/45622713-8486ac00-bab7-11e8-874d-9eb7a6c6600b.png">

**Comment by shaopeng1** [comment]
早就有人提过了

**Comment by freecnpro** [comment]
@shaopeng1 没有搜到，所以新提了个，如果已有请关联并关闭。

**Comment by javaFather** [comment]
import 'moment/locale/zh-cn'; 加这个就好了

**Comment by freecnpro** [comment]
@Nuoky @javaFather 感谢你们解决方法

**Comment by afc163** [comment]
@yutingzhao1991 这个问题不是在 umi 里解决过了么，我看 https://preview.pro.ant.design/dashboard/analysis 这里还是挂的。

**Comment by yutingzhao1991** [comment]
https://github.com/umijs/umi/pull/1029

@sorrycc 发个版本？

**Comment by yutingzhao1991** [comment]
fixed in umi 2.1.0（umi-plugin-react 1.1.0）

**Comment by zmayor** [comment]
@yutingzhao1991 升级后,我把`config/config.js`中的`polyfills`改成`targets`, 编译出来的代码是`es6`的.

**Comment by zmayor** [comment]
> 
> 
> @yutingzhao1991 升级后,我把`config/config.js`中的`polyfills`改成`targets`, 编译出来的代码是`es6`的.

#2448
