### ISSUE TITLE
如何设置动态路由和菜单（后端数据库加载）

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#2330]
![image](https://user-images.githubusercontent.com/37643958/45673069-5313ec00-bb5c-11e8-93c9-c234367b3ab0.png)
![image](https://user-images.githubusercontent.com/37643958/45673089-5f984480-bb5c-11e8-921f-3d498bb7fb9e.png)
![image](https://user-images.githubusercontent.com/37643958/45673105-6c1c9d00-bb5c-11e8-8579-941d249ac37e.png)
![image](https://user-images.githubusercontent.com/37643958/45673134-78085f00-bb5c-11e8-839a-9255892fa375.png)

**Comment by zhuguangyue** [comment]
> 你试试把reducers放effects上面，我放在下面一点效果都没有， 换了下位置才可以

兄弟，请指教一下

**Comment by pengshaomin** [comment]
> reducers

BasicLayout
Render的时候先判断下菜单是否加载完成  if(menu.isLoading) return <Spin /> 
路由应该动态加载不了，菜单还可以

**Comment by maytake** [comment]
![image](https://user-images.githubusercontent.com/13763352/45798821-e6285f80-bcdd-11e8-9358-b86f27f48d06.png)

**Comment by mushroomlb** [comment]
结论是什么，到底能不能动态路由啊

**Comment by chenshuai2144** [comment]
能

**Comment by mushroomlb** [comment]
可视还是报这个错误，服务端返回的数据要和router.config.js一样吗
![image](https://user-images.githubusercontent.com/1701771/46259289-21ab0100-c50a-11e8-9e7f-ac8145ec76b4.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95%EF%BC%9F

**Comment by afc163** [comment]
@chenshuai2144 这上面的文档貌似还是 1.x 的内容。

**Comment by linyuliang** [comment]
@chenshuai2144 这个是动态菜单吧，菜单可以动态，但是还是可以直接通过url来访问页面

**Comment by linyuliang** [comment]
我是这么实现动态路由的，首先上面的动态菜单getMenuData要修改，然后注释掉初始化里面的记忆缓存
`  constructor(props) {
    super(props);
    this.getPageTitle = memoizeOne(this.getPageTitle);
    // this.getBreadcrumbNameMap = memoizeOne(this.getBreadcrumbNameMap, isEqual);
    this.breadcrumbNameMap = this.getBreadcrumbNameMap();
    this.matchParamsPath = memoizeOne(this.matchParamsPath, isEqual);
  }`
再然后，在新路由里面找不到path的，都直接重定向到404
`          <Content style={this.getContentStyle()}>
            {
              routerConfig.path?(
                <Authorized authority={routerConfig.authority} noMatch={<Exception403 />}>
                {children}
                </Authorized>
              ):(<Route component={Exception404} />)
            }
          </Content>`
