### ISSUE TITLE
roadhog 2.0.0之后 extraBabelIncludes 这个功能就不能使用呢

### ISSUE THREAD

**Issue by tz310200** [ant-design/ant-design-pro#2331]
我用了ckeditor5 ,但是它不提供es5版本, roadhog2.0之后 extraBabelIncludes 这个功能虽然文档还有,但我看代码中没有相关配置,想问有可替代的配置吗?

**Comment by chenshuai2144** [comment]
This should be done with cdn.

**Comment by chenshuai2144** [comment]
https://umijs.org/config/#extrababelincludes
