### ISSUE TITLE
Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by panshiyu** [ant-design/ant-design-pro#2332]
![img](http://dytued.oss-cn-hangzhou.aliyuncs.com/test/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-09-19%20%E4%B8%8A%E5%8D%888.52.27.png)

生产环境打包失败，本地环境打包可以，使用extract-text-webpack-plugin@4.0.0-beta.0 也不行，这个要怎么改才能正常编译打包？

**Comment by tjones0808** [comment]
having same problem what was the fix?

**Comment by longhaiyan** [comment]
@panshiyu 请问你解决了么？我也遇到了这个问题
