### ISSUE TITLE
ant-design-pro 会考虑支持keep alive吗

### ISSUE THREAD

**Issue by raclen** [ant-design/ant-design-pro#2339]
如题，请问有排期支持吗

**Comment by afc163** [comment]
pro 是前端项目，和 keep alive 无关。

**Comment by raclen** [comment]
/笑哭  react-router 难道是后端项目吗
https://github.com/CJY0208/react-router-cache-route/issues/3

**Comment by afc163** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/507615/45738602-879eab00-bc23-11e8-8d18-68e2f68a1a24.png">

你用了一个让人误解的通用词汇。

**Comment by raclen** [comment]
抱歉 ，我知识范围窄了，从vue那听到的这个，原来 http也有这个，我看 react-router V4后有一些钩子可以实现这个了，请问ant-design-pro会考虑集成这个功能吗

**Comment by afc163** [comment]
暂时没有这个计划。

**Comment by geek4go** [comment]
https://github.com/Sam618/react-keep-alive  这个库

**Comment by xiaohuoni** [comment]
这个功能在umi的调研列表里面。等待后续umi的决定。

**Comment by jdfdcc** [comment]
+1

**Comment by angelporo** [comment]
+1
