### ISSUE TITLE
router.config.js中如何为菜单添加外部链接？

### ISSUE THREAD

**Issue by code-hero** [ant-design/ant-design-pro#2341]
比如下面的代码, 如何点击home的菜单跳转到对应外部链接，比如 https://pro.ant.design/index-cn

```
{
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [
      { path: '/', redirect: '/home' },
      {
        path: '/home',
        name: 'home',
        icon: 'home'
      }
    ],
  }
```

**Comment by shirleyYing** [comment]
修改BasicLayout.js中增加更新menu函数
```
updateMenuData = (discoverUrl,menuData) => {
    if(discoverUrl){
      // discoverUrl 为外部地址
      const index = menuData.findIndex(item=>item.locale === 'xxx');
      menuData[index].path = discoverUrl;
    }
  }
```

**Comment by code-hero** [comment]
谢谢你的建议，根据代码的描述，感觉你的意思是改变的menu的path属性。这是是否等同于在router中加上一个path属性。但是我尝试了后发现菜单真实地址是 http://localhost:8000/manage/**discoverUrl**

期待有更好的解决方法～

···
 Routes: [
      { path: '/', redirect: '/home' },
      {
        Path: '/home',
        Name: 'home',
        Icon: 'home',
        path: **discoverUrl**
      }
    ],
···

**Comment by code-hero** [comment]
谢谢你的建议，我看了BaseMenu的源码。
http和https我都尝试了，但是没有效果，最终通过浏览器生成的 a 标签的href为 "/manage/https:/www.baidu.com",
感觉源码地址的处理http或https这块的js方法有点问题，我改成了如下的代码解决了我的问题：

组件中 BaseMenu 作如下修改：

修改后的代码

```
  if(itemPath.indexOf("http")>0){
      return (
        <a href={itemPath.substr(itemPath.indexOf("http"))} target={target}>
          {icon}
          <span>{name}</span>
        </a>
      );
    }
```

修改前的代码：

```
  // Is it a http link
    if (/^https?:\/\//.test(itemPath)) {
      return (
        <a href={itemPath} target={target}>
          {icon}
          <span>{name}</span>
        </a>
      );
    }
```

**Comment by louisluckydoggie** [comment]
> 谢谢你的建议，我看了BaseMenu的源码。
> http和https我都尝试了，但是没有效果，最终通过浏览器生成的 a 标签的href为 "/manage/https:/www.baidu.com",
> 感觉源码地址的处理http或https这块的js方法有点问题，我改成了如下的代码解决了我的问题：
> 
> 组件中 BaseMenu 作如下修改：
> 
> 修改后的代码
> 
> ```
>   if(itemPath.indexOf("http")>0){
>       return (
>         <a href={itemPath.substr(itemPath.indexOf("http"))} target={target}>
>           {icon}
>           <span>{name}</span>
>         </a>
>       );
>     }
> ```
> 修改前的代码：
> 
> ```
>   // Is it a http link
>     if (/^https?:\/\//.test(itemPath)) {
>       return (
>         <a href={itemPath} target={target}>
>           {icon}
>           <span>{name}</span>
>         </a>
>       );
>     }
> ```

你这个返回的是 https:/www.baidu.com 吧，源码吐出来的 path 是 `/manage/https:/www.baidu.com`

**Comment by code-hero** [comment]
浏览器是可以自动识别https:/www.baidu.com/ 。但是为了严谨性，代码还是用正则替换下。

**Comment by code-hero** [comment]
浏览器是可以自动识别https:/www.baidu.com/ 的,为了严谨性，修改BaseMenu中方法conversionPath,将正则表达式 /\/+/g, '/' 替换为 /\/+/g, '//'

组件中 BaseMenu 作如下修改：
修改前代码：
```
conversionPath = path => {
    if (path && path.indexOf('http') === 0) {
      return path;
    }
    return `/${path || ''}`.replace(/\/+/g, '//');
  };
```
修改后代码

```
conversionPath = path => {
    if (path && path.indexOf('http') === 0) {
      return path;
    }
    return `/${path || ''}`.replace(/\/+/g, '/');
  };
```

**Comment by afc163** [comment]
来个 PR 支持下？

**Comment by afc163** [comment]
#2762
