### ISSUE TITLE
IE 11 需要polyfill

### ISSUE THREAD

**Issue by qinhuaihe** [ant-design/ant-design-pro#2344]
`v2` 这个在`ie11`上还有很多兼容性问题啊, `preview`就打不开啊.

**Comment by afc163** [comment]
@sorrycc

**Comment by cqlishun1011** [comment]
我npm start 之后再IE11上面打开，报ES6方面的错，对象不支持“find”属性或方法；这是怎么回事啊

**Comment by zmayor** [comment]
@cqlishun1011 就是有一些方法`ie`不支持, 需要做兼容性处理, 可以在`document.ejs`里面加上`<script src="https://cdn.bootcss.com/babel-polyfill/7.0.0-beta.49/polyfill.min.js"></script>`, 先用着, 然后等他们解决好了再去掉.

**Comment by cqlishun1011** [comment]
@zmayor 引用之后再IE11下是没问题了，谢谢！。但是如果想要兼容到IE10、IE9呢

**Comment by tsl196865614** [comment]
我ie11打开https://preview.pro.ant.design一片空白呀, 说好的兼容ie9以上呢

**Comment by xiaohuoni** [comment]
@tsl196865614 已经加了array.find preview还没更新

**Comment by lusonghe0313** [comment]
@zmayor  我引用了也不行，IE11页面没有报错，就是一片空白，什么都没有

**Comment by xgj1988** [comment]
@lusonghe0313  我和你一样。一样不行。

**Comment by linonetwo** [comment]
根据 https://babeljs.io/docs/en/babel-polyfill ，现在应该这样加：

```js
import "core-js/stable";
import "regenerator-runtime/runtime";
```

polyfill 加在哪个文件里？有没有一个像 CRA 一样的入口点？

**Comment by xiaohuoni** [comment]
现在配置 [targets](https://umijs.org/zh/config/#targets) 就可以了，如果你还是需要自己添加，那你可以写在[src/global.j|ts](https://umijs.org/zh/guide/app-structure.html#src-global-js-ts)
