### ISSUE TITLE
水波图

### ISSUE THREAD

**Issue by HelenGuohx** [ant-design/ant-design-pro#2345]
![2018-09-20 11 21 26](https://user-images.githubusercontent.com/35051874/45794117-aeaeb880-bcc7-11e8-9f63-4d6a44b98ad5.png)
水波图图形和数据不符合

**Comment by shaopeng1** [comment]
我也有同样的问题，第一次刷新是对的，然后不刷新页面获取数据就不对了

**Comment by huachaoliu** [comment]
@shaopeng1 我以前也遇到过,在列表中做排序,就不会重新渲染,好像是因为props状态更改后,canvas不会重绘,需要在接收到新的props时,重置一下canvas的宽高.

**Comment by chenshuai2144** [comment]
可以下载我最新的代码，因为 canvase 没有清空的原因
