### ISSUE TITLE
npm start 报错 Cannot find module '@/utils/utils.less'

### ISSUE THREAD

**Issue by willsame** [ant-design/ant-design-pro#2346]
npm start 后总是报  Cannot find module '@/utils/utils.less' 这个错误 
![dkaq 3 l ugx5rh4y5w0](https://user-images.githubusercontent.com/19715001/45794508-a35c8c80-bcc9-11e8-9adb-39959fb2c8d5.png)

**Comment by caesar-cat** [comment]
我也是碰到同样的问题，有没有人来解答一下？

**Comment by caesar-cat** [comment]
@willsame  我解决了  引用的路径要用单引号包裹，不能用双引号

**Comment by yutingzhao1991** [comment]
用单引号能解决问题，但是这个问题很诡异，还要在看看。好像是别名和 less-loader 一起用会有问题。外面用双引号来引的话 webpack 会在识别别名的时候带上不必要的单引号。

**Comment by willsame** [comment]
@caesar-cat @yutingzhao1991 果然单引号可以，感谢感谢

**Comment by willsame** [comment]
@caesar-cat @yutingzhao1991 但是有个很奇怪的问题，我修改为单引号过后，git commit 提交本地的话，它有自动改回去了，变为双引号了，知道什么原因么？

**Comment by chenshuai2144** [comment]
@yutingzhao1991  @sorrycc 和 prettier 冲突了，

**Comment by xgj1988** [comment]
@chenshuai2144  能否解释一下，为什么要用单引号。。

**Comment by logmannn** [comment]
Try: `@import '~@/`
It worked for me.

**Comment by AnthonyJen** [comment]
> Try: `@import '~@/`
> It worked for me.

Useless

**Comment by ximeng123** [comment]
Useless too.

**Comment by niming175** [comment]
我也遇到该问题，且还没解决

**Comment by niming175** [comment]
> @willsame 我解决了 引用的路径要用单引号包裹，不能用双引号
亲测，无效

**Comment by chenshuai2144** [comment]
用相对路径吧，别名已经不支持的

**Comment by dc-itboy** [comment]
修改plugin.config.js 内MergeLessPlugin插件的入口 保持入口路径和别名@一致即可 const stylesDir = path.join(__dirname, '@')
