### ISSUE TITLE
 菜单切换的时候，比如从 工作台，切换到 分析页 会卡顿个几毫秒。是怎么回事？

### ISSUE THREAD

**Issue by maytake** [ant-design/ant-design-pro#2349]
![image](https://user-images.githubusercontent.com/13763352/45799281-859a2200-bcdf-11e8-9621-36c78e334ef8.png)

 菜单切换的时候，比如从 工作台，切换到 分析页 会卡顿个几毫秒。是怎么回事？

**Comment by maytake** [comment]
![Uploading NZYW5}DHUUY0VNE(~DZOW1W.png…]()

**Comment by chenshuai2144** [comment]
g2图表太多了。渲染卡线程了

**Comment by maytake** [comment]
直接从github拉取本地打开的，我试了下，如果是图表页面造成的，把图表页面换成最简单的一段字，菜单蓝色的也会卡顿。但是我看官网预览的就会流畅很多。

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/issues/2085
