### ISSUE TITLE
固定导航页时,触发异常,导航会遮挡到notification浮框

### ISSUE THREAD

**Issue by huachaoliu** [ant-design/ant-design-pro#2351]

**Comment by huachaoliu** [comment]
![bug1](https://user-images.githubusercontent.com/15731831/45803341-fba48600-bceb-11e8-9729-e78000b162f2.png)

**Comment by huachaoliu** [comment]
点击搜索提示被遮挡.
![bug2](https://user-images.githubusercontent.com/15731831/45803517-635ad100-bcec-11e8-9957-23832cc6eefd.png)

**Comment by chenshuai2144** [comment]
已修复，问问题之前请先搜相关 issue
