### ISSUE TITLE
List 如果存在pagination，loading时的spin不会覆盖分页组件

### ISSUE THREAD

**Issue by T-Flynn** [ant-design/ant-design-pro#2354]
List 如果存在pagination，loading时的spin不会覆盖分页组件

**Comment by chenshuai2144** [comment]
重现？

**Comment by T-Flynn** [comment]
> 重现？

![ant](https://user-images.githubusercontent.com/32189234/45857600-18909600-bd8c-11e8-9037-6bc003d676cd.jpg)

**Comment by chenshuai2144** [comment]
antd  的问题
