### ISSUE TITLE
Error: please specify the canvas container Id !

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#236]
https://sentry.io/ant-design/ant-design-pro/issues/406780079/

```
Error: please specify the canvas container Id !
  at o (/as/g/:22:460)
  at l (/as/g/:22:1051)
  at y (/as/g/:22:1285)
  at value/</< (/0.async.js:1:431007)
  at r (/as/g/:24:10502)
...
(3 additional frame(s) were not displayed)
```

**Comment by afc163** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/507615/32980969-0075e58e-ccab-11e7-96d3-860da932b8ce.png">

**Comment by nikogu** [comment]
断点看了下是 g2-slider 的 bug，我去找相关同学问问源码哪里看

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/pull/370
