### ISSUE TITLE
.gitignore 忽略了 jsconfig.json 配置文件

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design-pro#2364]
.gitignore 忽略了 jsconfig.json 配置文件，项目中的代码上传git服务器后，他人使用因缺该文件会造成 vscode 等 IDE 会有代码引入错误提示。

![image](https://user-images.githubusercontent.com/13798931/45860305-05d08e00-bd99-11e8-9c8c-3751037ec60d.png)

**Comment by afc163** [comment]
来个 PR~

**Comment by tomgao365** [comment]
PR #2366
