### ISSUE TITLE
Nginx生产环境报404，405错误，help~~

### ISSUE THREAD

**Issue by cindyZhang4** [ant-design/ant-design-pro#2367]
npm run start 后丢到nginx上就404了，
webpackrc配置如下：
`const path = require('path');

export default {
  entry: 'src/index.js',
  extraBabelPlugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  env: {
    development: {
      extraBabelPlugins: ['dva-hmr'],
    },
  },
  proxy: {
    //登录地址
    "/": {
      "target": "http://139.219.0.45:444",
      "changeOrigin": true,
      "pathRewrite": { "^/" : "" }
    },
  },
  alias: {
    components: path.resolve(__dirname, 'src/components/'),
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs',
  },
  disableDynamicImport: true,
  publicPath: '/',
  hash: true,
};`

nginx也配置了try_files $uri /index.html;  访问错误变成了404，
```
location / {
        root   /home/www/dist;
        index  index.html index.htm;
        try_files $uri /index.html;
    }
```
想请问下到底该怎么配置

**Comment by cindyZhang4** [comment]
nginx也配置了try_files $uri /index.html; 访问错误是变成了405

**Comment by chenshuai2144** [comment]
明显是你反了低级错误，请认真排查

**Comment by chenshuai2144** [comment]
所以需要排查，你的信息太小了

**Comment by cindyZhang4** [comment]
> 所以需要排查，你的信息太小了

主要排查哪些文件，是否有相似的配置可以推荐下看看呢？找了一圈，凡是类似问题都回复配置问题，具体是哪部分的配置问题呢？

**Comment by chenshuai2144** [comment]
nginx 的配置。
你至少需要把文件结构和配置贴出来

**Comment by cindyZhang4** [comment]
> nginx 的配置。
> 你至少需要把文件结构和配置贴出来
我们现在的配置是这个样子的。
server {
    listen       80;
    server_name  localhost;
    location / {
        root   /home/www/dist;
        index  index.html index.htm;
	#try_files $uri /index.html;
	try_files $uri $uri/ /index.html;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

**Comment by cindyZhang4** [comment]
> nginx 的配置。
> 你至少需要把文件结构和配置贴出来

我们现在的配置是这个样子的。
server {
    listen       80;
    server_name  localhost;


    location / {
        root   /home/www/dist;
        index  index.html index.htm;
	#try_files $uri /index.html;
	try_files $uri $uri/ /index.html;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

**Comment by chenshuai2144** [comment]
你的文件目录在哪里？看你的配置是没有问题，
只要 /home/www/dist/index.html 存在就 ok

**Comment by cindyZhang4** [comment]
![11](https://user-images.githubusercontent.com/35737417/45995046-0040b400-c0c9-11e8-97e8-069f554fdb4e.jpg)


> 你的文件目录在哪里？看你的配置是没有问题，
> 只要 /home/www/dist/index.html 存在就 ok
文件目录
![11](https://user-images.githubusercontent.com/35737417/45995062-151d4780-c0c9-11e8-8ec1-d304c131d259.jpg)

登录的时候错误
![222](https://user-images.githubusercontent.com/35737417/45995362-6417ac80-c0ca-11e8-900b-8c3765d0880e.jpg)

publicPath需要设置吗？

**Comment by chenshuai2144** [comment]
这和前端没有关系呀。你的后端接口地址在哪里
是后端404

**Comment by cindyZhang4** [comment]
> 这和前端没有关系呀。你的后端接口地址在哪里
> 是后端404

后端接口地址就是
 proxy: {
    "/": {
      "target": "http://139.219.0.45:444",
      "changeOrigin": true,
      "pathRewrite": { "^/" : "" }
    },
  },
设置过了，然后开发环境也是可以访问的，所以我现在不知道是哪一个地方没有配置，导致在Nginx的接口出现这个错误

**Comment by chenshuai2144** [comment]
nginx 也要配置代理

**Comment by cindyZhang4** [comment]
> nginx 也要配置代理

太感谢了，问题解决了~感谢您如此耐心的解答我的问题

**Comment by mushroomlb** [comment]
nginx 配置如下，后端也需要配置
server{
    listen 80;
    server_name _;
    location / {
      root /xxx/;
      index index.html;
      try_files $uri /index.html;
    }
    location /api {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host:80;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     }
}

**Comment by cindyZhang4** [comment]
> nginx 配置如下，后端也需要配置
> server{
> listen 80;
> server_name _;
> location / {
> root /xxx/;
> index index.html;
> try_files $uri /index.html;
> }
> location /api {
> proxy_pass http://127.0.0.1:8080;
> proxy_set_header Host $host:80;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> }
> }

嗯嗯，谢谢~~后来是让管理员这样配置了，之前一直未配置location/api这块，因为他们想的是用端口号去访问，最后改成了您发的这样子的
