### ISSUE TITLE
V2版本Mock还可以直接设置代理吗

### ISSUE THREAD

**Issue by HelloSetsuna** [ant-design/ant-design-pro#2373]
> 在 V1版本的时候我还可以在 ./.roadhogrc.mock.js 中做如下修改配置代理

![tim 20180921184637](https://user-images.githubusercontent.com/19373382/45876905-b60cb980-bdce-11e8-8830-d1018e662993.png)

> 在 V2版本的时候我尝试像V1一样设置代理,尝试在例子上修改了下,但是编译的时候报了错误

![tim 20180921185818](https://user-images.githubusercontent.com/19373382/45877468-7ba41c00-bdd0-11e8-8cd1-10a2403b0089.png)

![tim 20180921190515](https://user-images.githubusercontent.com/19373382/45877703-5368ed00-bdd1-11e8-9e21-e42f13648569.png)

个人认为开发的时候mock可以直接proxy请求还是挺实用的,不知道有没有提供一些别的类似功能以方便测试的时候和服务器联调

**Comment by shirleyYing** [comment]
在 `config/config.js`中设置
```
 proxy: { 
    '/api': { target: 'http://xxx', changeOrigin: true } 
  },
```

**Comment by HelloSetsuna** [comment]
@shirleyYing 多谢,我试下

**Comment by Eric-Zhong** [comment]
基于 2.1.1 版，还要在启动时，用 npm run start:no-mock 来启动系统。
