### ISSUE TITLE
UnhandledPromiseRejectionWarning TypeError: content.match is not a function

### ISSUE THREAD

**Issue by komorebi-san** [ant-design/ant-design-pro#2375]
Hi Guys, 

I got an error while compiling. Can't figure out what causing it.

(node:3443) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: content.match is not a function
(node:3443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Got an error while compiling, stuck at 95%.

● webpack █████████████████████████ emitting (95%) unnamed compat plugin

**Comment by chenshuai2144** [comment]
try remove antd-pro-theme-webpack-plugin in config/plugin.config.js

**Comment by komorebi-san** [comment]
> try remove `antd-pro-theme-webpack-plugin` in config/plugin.config.js

Thanks!
