### ISSUE TITLE
BUG: Latest Ant-Design-Pro 2.0 <Select> onChange event doesn't trigger for mobile/tablet

### ISSUE THREAD

**Issue by komorebi-san** [ant-design/ant-design-pro#2378]
BUG: 
**Ant-Design-Pro 2.0 Select onChange event doesn't trigger for mobile/tablet**

Reproduce: 
**Clone the latest version, npm install and run. Open your Developer Tools and choose iPad. Go to Search List(articles) and change the "owner" by selecting multiple names, but none can't be selected. Similar you can use an actual iPad to try it out.**

Platform:
**Mac OS**

Node:
**8.6.0**

The same bug have been described here. 

https://github.com/ant-design/ant-design-pro/issues/2326

**edit : include short gif**

![](https://i.imgur.com/mlhI9oK.gif)

**Comment by chenshuai2144** [comment]
无法在线

**Comment by komorebi-san** [comment]
@chenshuai2144 Did you tried with a mobile browser?

**Comment by chenshuai2144** [comment]
yep

**Comment by komorebi-san** [comment]
What OS are you using and what node version? 

This is another short gif for other select boxes.

![](https://i.imgur.com/gIQis7U.gif)

**Comment by Ivocin** [comment]
What's your Google Chrome version, mine is 69.0.3497.100 and in Mac OS everything is OK

**Comment by komorebi-san** [comment]
> What's your Google Chrome version, mine is 69.0.3497.100 and in Mac OS everything is OK

@Ivocin 

My version is the same as yours. Can you try using Mouse to click instead of Trackpad? I realise that it works with trackpad but not mouse. 

You can see the gif below.

![](https://im4.ezgif.com/tmp/ezgif-4-37fddf484c.gif)

**Comment by tanszepin** [comment]
Add to the following styles into the component works for me.

style={{ cursor: 'pointer' , pointerEvents: 'auto'}}

**Comment by komorebi-san** [comment]
> Add the following styles into the component works for me.
> 
> style={{ cursor: 'pointer' , pointerEvents: 'auto'}}

Thanks.
