### ISSUE TITLE
antd pro2.0 执行npm run build 报错。。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#2379]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle xyzy@2.0.0~prebuild: xyzy@2.0.0
6 info lifecycle xyzy@2.0.0~build: xyzy@2.0.0
7 verbose lifecycle xyzy@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle xyzy@2.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.jenkins/workspace/XYZY/XYZY-MANGER-ANTD/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/chengxun/tools/jdk1.8.0_121/bin:/root/bin:/chengxun/tools/jdk1.8.0_121/bin:/chengxun/tools/maven-3.3.9/bin:/usr/local/ruby/bin
9 verbose lifecycle xyzy@2.0.0~build: CWD: /root/.jenkins/workspace/XYZY/XYZY-MANGER-ANTD
10 silly lifecycle xyzy@2.0.0~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle xyzy@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle xyzy@2.0.0~build: Failed to exec build script
13 verbose stack Error: xyzy@2.0.0 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid xyzy@2.0.0
15 verbose cwd /root/.jenkins/workspace/XYZY/XYZY-MANGER-ANTD
16 verbose Linux 3.10.0-862.3.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error xyzy@2.0.0 build: `umi build`
22 error Exit status 1
23 error Failed at the xyzy@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by xgj1988** [comment]
Compiling

● webpack █████████████████████████ building modules (22%) 102/116 modules 14 active
  node_modules/@babel/runtime/helpers/defineProperty.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xyzy@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xyzy@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-22T10_36_05_702Z-debug.log
[root@toolserver XYZY-MANGER-ANTD]# less /root/.npm/_logs/2018-09-22T10_36_05_702Z-debug.log

**Comment by derekng622** [comment]
> route.config.js的 route 的component 大小写西措了。所以在Windows 下面没有问题。但是linux 下面有问题

我也遇到这个问题，一开始在windows上面开发，在router.config.js里面一个component写成全大写了，windows编译没问题，放到jenkins的centos环境下编译报错，话说这个异常报错也太诡异了，没有指出哪里出错。

**Comment by xgj1988** [comment]
@derekng622  用一个插件可以解决这个问题
