### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8000/index.css".

### ISSUE THREAD

**Issue by lofzefjg** [ant-design/ant-design-pro#238]
是不是打包的时候没有把css生成到public文件，我是新手请大家帮帮忙

**Comment by nikogu** [comment]
问题是什么，是有报错还是？打包的文件在 `dist` 下

**Comment by lofzefjg** [comment]
直接clone下来的项目，public/index.html里面引用了index.css,我一开始以为是脚手架生成的时候打包漏了css，后来看src/index.less样式生效，才知道是index.html里面多添加了一行引用代码：<link rel="stylesheet" href="index.css" />  
谢谢你们及时的回复！！牛人牛框架

**Comment by nikogu** [comment]
虽然没看懂你说的，但是问题好像解决了...
