### ISSUE TITLE
Where should I init parse sdk?

### ISSUE THREAD

**Issue by pcegarra** [ant-design/ant-design-pro#2385]
I need to init the parse js sdk in some file, where is the correct place?
The code looks like:

```
Parse.initialize("YOUR_APP_ID", "YOUR_JAVASCRIPT_KEY"");
Parse.serverURL = 'http://YOUR_PARSE_SERVER:1337/parse'
```

Normally i put this in the App.js but I dont know where should I put it here.
Any idea?

**Comment by chenshuai2144** [comment]
`src/global.js`

Add this file and execute it in it
