### ISSUE TITLE
npm run build 之后文件都在一个目录，有办法把css、js分开吗？

### ISSUE THREAD

**Issue by niugengyun** [ant-design/ant-design-pro#2387]
umi文档看了，没找到再那里配置

我想把css放到 dist/css

我想把js放到 dist/js

我想把图片放到 dist/images

**Comment by chenshuai2144** [comment]
暂时好像没有办法，为什么有这个需求，最后出来只有一个 css，图片什么的最好应该上 cdn

**Comment by waveheart** [comment]
同问。
webpack的方式写配置会报错。

**Comment by afc163** [comment]
可以自行分类的。

**Comment by niugengyun** [comment]
怎么分类

**Comment by afc163** [comment]
构建完自行处理文件列表。
