### ISSUE TITLE
在IE11下打不开，关于ES6方面报错

### ISSUE THREAD

**Issue by cqlishun1011** [ant-design/ant-design-pro#2391]
从git上面clone之后没有修改任何代码，npm start 后，在IE上面打开直接报错，对象不支持“find”属性或方法

**Comment by chenshuai2144** [comment]
等待修复

**Comment by cqlishun1011** [comment]
可以通过自己配置babel-polyfill来解决吗

**Comment by chenshuai2144** [comment]
可以

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2344
