### ISSUE TITLE
当导航栏是topmenu时，如果菜单没有子选项，会出现这样的效果？？？ 

### ISSUE THREAD

**Issue by nianalang** [ant-design/ant-design-pro#2402]
![image](https://user-images.githubusercontent.com/30745206/46050777-84964400-c168-11e8-9019-84212098f300.png)

**Comment by louisluckydoggie** [comment]
需要手动添加类似：
```
<Menu.Item key="mail">
     <Icon type="mail" />Navigation One
</Menu.Item>
```
Pro 里是全部放到了 SubMenu 中，样式错位。

**Comment by nianalang** [comment]
它是有子菜单才放到 SubMenu里，没有子菜单直接放Menu.Item里
![image](https://user-images.githubusercontent.com/30745206/46064542-40279a00-c1a2-11e8-921e-75088335efbe.png)

**Comment by louisluckydoggie** [comment]
针对 ant-menu-item 加一个样式：
```
.ant-menu-item{
      height: 100%;
      padding-top: 9px;
}
```

**Comment by chenshuai2144** [comment]
master 已经修复
