### ISSUE TITLE
request里的cache阻止页面自动更新

### ISSUE THREAD

**Issue by yinxuan1128** [ant-design/ant-design-pro#2406]
2.0以前，我保存更新数据后，会更改组件一个props值让组件重新渲染，升级到2.0后这个方法就失效了。把request.js里fetch函数里的
    .then(response => cachedSave(response, hashcode))
注释掉就可以了。
有别的方法即可以利用cache又能让组件重新渲染更新吗？

**Comment by chenshuai2144** [comment]
数据不更新组件自然不会重新渲染
