### ISSUE TITLE
请问 BasicLayout 中 route 属性是从哪里获取的？

### ISSUE THREAD

**Issue by louisluckydoggie** [ant-design/ant-design-pro#2409]
[源码](https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L137)
看了一圈生命周期中没有获取过，是从 React.PureComponent 当中继承过来的吗？

**Comment by nianalang** [comment]
从调试的结果看，route里的内容是config下的router.config.js下的内容，可能是这个框架的某个地方将他们联系在一起了

![image](https://user-images.githubusercontent.com/30745206/46065791-9f3ade00-c1a5-11e8-9eaf-911695c71be2.png)

**Comment by louisluckydoggie** [comment]
针对 ant-menu-item 加一个样式：
```
.ant-menu-item{
      height: 100%;
      padding-top: 9px;
  }
```

**Comment by chenshuai2144** [comment]
在 BasicLayout 里面
