### ISSUE TITLE
有办法独立使用 pro 的主题吗？

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design-pro#241]
我很喜欢 antd 组件和 pro 版本的主题，但是如果连同脚手架一起使用的话会与我们当前的项目并不兼容，我们有自己的脚手架

所以请问一下能否在不使用整套pro脚手架的单独的使用 pro 主题，当然应用页面是使用 antd 组件搭建的

**Comment by nikogu** [comment]
你可以单独使用组件：https://pro.ant.design/docs/use-components-alone-cn

不过需要注意，都是基于 `antd 3.0` 的
