### ISSUE TITLE
npm install errors after checking out the antd project

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#2410]
npm install errors after checking out the antd project:
the error : 
![default](https://user-images.githubusercontent.com/39291213/46064664-98f73280-c1a2-11e8-9161-d4bfa10f85a2.png)
I've deleted node_modules and  npm cache clean -f but it doesn't work
I've installed the "roadhog": "^2.5.0-beta.1" but it doesn't work
And it seems that a few people also occured the same problem.
And any other has resolved the problem?

**Comment by chenshuai2144** [comment]
How about using cnpm?

**Comment by m26597** [comment]
And I've tried cnpm, but it doesn't work. I'm confused that since the issue hasn't been resolved, how could you close the issue?@chenshuai2144
