### ISSUE TITLE
现在最新下载这个项目，安装依赖一直安装不上呢？需要改什么文件么

### ISSUE THREAD

**Issue by MaoGirlsQueen** [ant-design/ant-design-pro#2411]
安装的用npm、yarn  也用了就是安装不上，下载的有一半但是不全。

**Comment by zxl78585** [comment]
@MaoGirlsQueen 用cnpm吧，cnpm好使

**Comment by MaoGirlsQueen** [comment]
@zxl78585 umi  跟这个有关系么  我们单位是限制网络用了代理了，都设置了，包括webstorm npm  都设置代理了 也是不好使 还是报错 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@^1.6.0 (node_modules\puppeteer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 407 Proxy Authorization Required: puppeteer@^1.6.0

npm ERR! code E407
npm ERR! 407 Proxy Authorization Required: @antv/data-set@^0.8.7
你遇见过没  我在家安装也是安装不上  你下载完了 能安装上依赖么

**Comment by chenshuai2144** [comment]
puppeteer 需要翻墙的，使用cnpm 就好了。或者直接删除

**Comment by MaoGirlsQueen** [comment]
@chenshuai2144 用的本地源 就好使啦 谢谢

**Comment by kennylbj** [comment]
puppeteer被墙了

**Comment by SilentFlute** [comment]
@chenshuai2144 
你好，最近在看你们的antd-pro，准备用它来写一个管理后台，然后我也遇到了大家依赖装不上的问题，cnpm以及科学上网都试过，时好时坏，考虑到目前暂不需要测试，以及我司也是用的jenkins部署，因此想一劳永逸的删掉puppeteer，本想重新开一个issue，但是浏览puppeteer的相关issue的时候看到了这个issue，刚好你也提到了删除，因此特来询问如何删除，以下是我做过的尝试，但是没有成功，依然安装了puppeteer:
删除了如下测试相关的文件，以及我不需要的文件：
![image](https://user-images.githubusercontent.com/28900312/61874092-21a54300-af1a-11e9-899c-31ad8a38deb4.png)
删除了package.json中jest和puppeteer相关的依赖：
![image](https://user-images.githubusercontent.com/28900312/61874142-40a3d500-af1a-11e9-86c3-d38a8c29476a.png)
希望你能指点迷津
