### ISSUE TITLE
Couldn't start to use antd

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#2419]
![default](https://user-images.githubusercontent.com/39291213/46131622-b98cbe80-c26e-11e8-9bb2-55620eccedab.png)

When I npm install antd --save, errors occured. The info is below :

error code EINTEGRITY
3461 error sha512-YeDW/WubTP8IgAwIkBJYPZ1kzzC8Qt9upRiy+bvKWLKP8lB2VHISOyPAiQ+5jPqIJqE7vT0DguMYv6U2XIpHRg== integrity checksum failed when using sha512: wanted sha512-YeDW/WubTP8IgAwIkBJYPZ1kzzC8Qt9upRiy+bvKWLKP8lB2VHISOyPAiQ+5jPqIJqE7vT0DguMYv6U2XIpHRg== but got sha512-T6MwVtfHjfNv5JJcIa3NaC9XXOUcyXy8MDujgwE++j/jmuJ0fIuJrEX8RFQJc5HK6iQaa3IwScqu/sSG+G715Q==. (662592 bytes)
3462 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
网络问题，使用 cnpm
