### ISSUE TITLE
files for ant-design-pro package

### ISSUE THREAD

**Issue by JaniceLian** [ant-design/ant-design-pro#242]
ant-design-pro（0.2.3-rc.3） package.json中css-module.js是用来配置什么的？
```
"scripts": {
    "cp": "cp ./.babelrc ../../scaffold && cp ./css-module.js ../../scaffold",
    ...
  },
```
线上有该文件吗？

**Comment by nikogu** [comment]
@JaniceLian 这个是：https://github.com/ant-design/ant-design-pro-site 这里面的代码，跟 pro 没关系，这个是用来给 pro 组件打包的

**Comment by JaniceLian** [comment]
@nikogu 谢谢！
