### ISSUE TITLE
请教下loading使用问题

### ISSUE THREAD

**Issue by willsame** [ant-design/ant-design-pro#2420]
如下图，红线框出来的 loading: loading.models.monitor,               loading: loading.effects['chart/fetch'],是啥含义？
刚学习前端，不太明白这个。求解答，非常感谢

![loading_1](https://user-images.githubusercontent.com/19715001/46131848-4172c880-c26f-11e8-87b5-b76e443b2615.png)
![loading_2](https://user-images.githubusercontent.com/19715001/46131849-420b5f00-c26f-11e8-9543-8c99b008fbc6.png)

**Comment by xiaohuoni** [comment]
这里的loading使用的是[dva-loading](https://github.com/dvajs/dva/tree/master/packages/dva-loading)
这里的connect简单的理解为绑定，就是绑定了你当前的loading状态。
这里的loading状态类似这样子的。
```
loading: {
  global: false,
  models: {
    users: false,
    todos: false,
    ...
  },
}
```
比如你现在在users页面发起一个请求，那你需要将上面配置改成``users:true``，
然后在请求结束之后，你又要将将上面配置改成``users:false``
而将loading状态connect之后，你就不需要做这个事情了，dva-loading会自动帮你管理这些状态。
你可以先简单的这么理解。更完善的信息，可以查看[dvajs](https://github.com/dvajs)和[dva-loading](https://github.com/dvajs/dva/tree/master/packages/dva-loading)
