### ISSUE TITLE
菜单和面包屑不匹配

### ISSUE THREAD

**Issue by sskcal** [ant-design/ant-design-pro#2426]
面包屑有4层：面包屑：首页/表单页/分步表单/分步表单（填写转账信息）
实际菜单只是3层：首页/表单页/分步表单

![image](https://user-images.githubusercontent.com/19920998/46140294-4c375880-c283-11e8-8347-569a43bee3c1.png)

**Comment by sskcal** [comment]
有强迫症。。。。

**Comment by chenshuai2144** [comment]
这是故意的，你点一下步还会变化
