### ISSUE TITLE
最新版本的“注销登录”存在问题，首次进入时点击注销登录无效，只有进入登录页，模拟登录一次以后才会起作用

### ISSUE THREAD

**Issue by renyi818** [ant-design/ant-design-pro#243]
最新版本的首页上“注销登录”存在问题，启动服务器后，首次进入时点击注销登录无效，只有进入登录页，模拟登录一次以后才会起作用，但是如果再在浏览器地址栏里重新打开首页，再次点注销登录，一样无效。

通过日志可以发现，每次点击无效时，页面上的logout有触发，但是没有进入model/login.js下的logout方法。
我这边删除重新下载了项目几次都会出现这样的问题，还请确认。

另外每次npm install都会出现下面这个，长时间执行不完，我都会中止掉，应该不影响吧？
> electron@1.7.9 postinstall
> node install.js

**Comment by astoryiceandfire** [comment]
我也遇到了。。

**Comment by nikogu** [comment]
秒修复 ＝。-

**Comment by nikogu** [comment]
@renyi818 你用什么 `install` 的，是 `npm` 还是 `cnpm`

**Comment by renyi818** [comment]
👍 
用的是cnpm

**Comment by Chinajiyong** [comment]
Hi @renyi818 你当时提出这个问题的ant design版本是2.0.0么？我现在也遇到这个问题
