### ISSUE TITLE
@imort relative less file fail

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design-pro#2432]
![image](https://user-images.githubusercontent.com/5092728/46190155-f3b89780-c324-11e8-82b1-ebd8224f087d.png)

tip error message: 
```
[Error: './a.less' wasn't found. Tried - ./a.less,D:\workspace_js\my-project\node_modules\antd\lib\style\a.less,D:\workspace_js\my-project\src\a.less,a.less]
```
根据提示，我将a.less移动到`src`目录。依旧报错。

![image](https://user-images.githubusercontent.com/5092728/46190245-6295f080-c325-11e8-8437-573005f5604a.png)

然后我做了另外一个测试，就是`a.less`放到`src`, 在`index.less`引用的时候直接写:'./a'。依旧会报错：
![image](https://user-images.githubusercontent.com/5092728/46190339-cddfc280-c325-11e8-8440-a415c82ad9d6.png)

前面两个错感觉是框架层出来。后面那个错误是less找不到文件出来的。是否是框架层的bug？求解？

**Comment by chenshuai2144** [comment]
感觉是umi的问题，./a.less呢

**Comment by ganxunzou** [comment]
./a.less 直接编译不过的。需要加引号

**Comment by chenshuai2144** [comment]
cc in https://github.com/ant-design/ant-design-pro/issues/2346
