### ISSUE TITLE
config中配置base之后退出登陆，再登陆，跳转有问题

### ISSUE THREAD

**Issue by wakaryry** [ant-design/ant-design-pro#2433]
在config/config.js中添加`base`设置：
```
base: '/admin/',
```
所有的页面路由都正常。

不过退出登陆之后，重新进行登陆，这个时候会在url上多处一个admin。

**问题再现：**
从退出登陆之后的带redirect的登陆页面url， 比如：http://localhost:8000/admin/user/login?redirect=http%3A%2F%2Flocalhost%3A8000%2Fadmin%2Fdashboard%2Fanalysis
重新登陆进入，URL为http://localhost:8000/admin/admin/dashboard/analysis。

期望：http://localhost:8000/admin/dashboard/analysis

**Comment by chenshuai2144** [comment]
base 不是这么用的。

**Comment by wakaryry** [comment]
对这些不太懂。
我想在所有的URL上加个base url， 比如`/admin/`。然后利用`nginx`来服务build出来的静态文件，直接通过`location /admin/`来对资源进行定位。

不知道需要配置哪些地方。
对前台开发不熟，尤其是一堆的配置，只会使用。

**Comment by wakaryry** [comment]
@chenshuai2144 根据umi文档，实现这个不是配置base莫。

![default](https://user-images.githubusercontent.com/7576559/46200048-3a1cef00-c343-11e8-9035-e9395ad039ee.png)

而且页面都正常，就是在点击退出登陆，自动跳转到登陆页面（页面跳转到登陆页面，这时URL上面有个redirect），然后在这个页面上登陆，成功之后自动跳转到的URL上面多了一个admin(存在两个admin)。

理应是http://localhost:8080/admin/dashboard/analysis，实际上http://localhost:8080/admin/admin/dashboard/analysis

**Comment by chenshuai2144** [comment]
你可能需要修改一下 redirect 的逻辑了。
具体代码在这里 `src/models/login.js`
