### ISSUE TITLE
当安装了其他依赖之后就出现 These dependencies were not found

### ISSUE THREAD

**Issue by panzj** [ant-design/ant-design-pro#2435]
1. 安装了其他的包，`npm install --save egg-view-assets egg-view-nunjucks` 
2. 重新执行`npm start` 报一下错误

```
ERROR  Failed to compile with 2 errors                                               16:12:56

These dependencies were not found:

* egg-view-assets in dll umi
* egg-view-nunjucks in dll umi

To install them, you can run: npm install --save egg-view-assets egg-view-nunjucks
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

#2313 也是同样问题，全局安装umi不能解决问题，也不是正确的解决方式

**Comment by xiaohuoni** [comment]
``npm install --save--dev egg-view-assets egg-view-nunjucks``
试试这个行不行

**Comment by panzj** [comment]
> `npm install --save--dev egg-view-assets egg-view-nunjucks`
> 试试这个行不行

不行，实际已经安装，经排查是umi-plugin-dll 的问题，他会将dependencies的包打包到umi-dlls, 以加速webpack构建重启，而egg-view-nunjucks 等包的package.json 没有设置main的入口文件，因此找不到此包。
解决办法：
暂时先关闭dll插件：/config/config.js  注释 dll 一段，或将不能编译到dll的包添加到 exclude: [...]

**Comment by xiaohuoni** [comment]
应该要include的才会被打包到dll吧？

**Comment by panzj** [comment]
> 应该要include的才会被打包到dll吧？

看源码是include + dependencies， 所以dependencies且只用在服务端、没有index文件、没有配置 main 属性的这种npm 包，需要排除掉

**Comment by xiaohuoni** [comment]
@sorrycc
