### ISSUE TITLE
Changing the head title

### ISSUE THREAD

**Issue by makaaboune** [ant-design/ant-design-pro#2440]
I'm using the And design pro templates, and I want to change title of my App. in simple react app it is located here: public/index.html , I know that is configured Dynamically in ant design pro template but i dont know how to change it! 
I what also to know how ant design pro start ( what is first file executed) because it is no index.html file.
Thanks...

**Comment by wakaryry** [comment]
You could change title in layouts/UserLayout, layouts/BasicLayout.

It uses `react-document-title`.

```js
import DocumentTitle from 'react-document-title'
```

Example in UserLayout:
```
class UserLayout extends React.PureComponent {
  // @TODO title
  getPageTitle() {
    const { routerData, location } = this.props;
    const { pathname } = location;
    let title = '小确幸';
    if (routerData && routerData[pathname] && routerData[pathname].name) {
      title = `${routerData[pathname].name}-小确幸`;
    }
    return title;
  }

  render() {
    const { children } = this.props;
    return (
      <DocumentTitle title={this.getPageTitle()}>
        <div className={styles.container}>
          <div className={styles.content}>
            <div className={styles.top}>
              <div className={styles.header}>
                <Link to="/">
                  <img alt="logo" className={styles.logo} src={logo} />
                  <span className={styles.title}>小确幸</span>
                </Link>
              </div>
              <div className={styles.desc}>有你，真好啊啊啊啊啊</div>
            </div>
            {children}
          </div>
          <GlobalFooter links={links} copyright={copyright} />
        </div>
      </DocumentTitle>
    );
  }
}
```

**Comment by xiaohuoni** [comment]
If you want to revise init title ，you can modify the file ``/src/pages/document.ejs``
```html
  <title>Ant Design Pro</title>
```
and if you want dynamically modify the title,you can use [react-helmet](https://github.com/nfl/react-helmet) or [react-document-title](https://github.com/gaearon/react-document-title)
[how-to-dynamically-modify-the-title](https://umijs.org/guide/faq.html#how-to-dynamically-modify-the-title)
``In addition to many features in the Ant Design Pro 2.0 release, we also upgraded the front-end build tool from roadhog to UmiJS (referred to as umi). ``  [pro upgrade-v2](https://pro.ant.design/docs/upgrade-v2)

**Comment by makaaboune** [comment]
Problem solved! Thanks....

**Comment by geraldus** [comment]
@wakaryry thank you.  Your answer was really helpful
