### ISSUE TITLE
services里面的default关键字问题，检查机制推荐加上default关键字，但是一旦加上，就导致从model.js里面调用services里面的函数时，识别不了，找不到这个函数

### ISSUE THREAD

**Issue by streamlong** [ant-design/ant-design-pro#2443]
// 去掉default 关键字，从model.js里面访问services时，可以找到这个函数

> 
export async function queryItemSkuByBatchId(params) {
    console.log('params', params);
    return request(`/api/itemSku/get?${stringify(params)}`);
}

// 加上default关键字，从model.js里面访问services时，找不到这个函数（且default关键字是推荐加上的）

> 
export **default** async function queryItemSkuByBatchId(params) {
    console.log('params', params);
    return request(`/api/itemSku/get?${stringify(params)}`);
}
完整如下图：
![image](https://user-images.githubusercontent.com/32262375/46240240-f07de400-c3d6-11e8-9948-5065ccaad4bb.png)

这是何故？

**Comment by chenshuai2144** [comment]
都是`default`了，不需要找。
直接 
`import queryItemSkuByBatchId from './queryItemSkuByBatchId';`
不加需要
` import { queryItemSkuByBatchId } from './queryItemSkuByBatchId';`
