### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by freestyledash** [ant-design/ant-design-pro#2444]
* 操作：
按照文档 https://pro.ant.design/docs/getting-started 操作
```
$ git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project
$ cd my-project
$ npm install
$ npm start
```

* 控制台报错：
```
> ant-design-pro@2.0.0 start /Users/zhangyanqi/WebstormProjects/ant-design-pro
> cross-env APP_TYPE=site umi dev


WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.


/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/hard-source-webpack-plugin/index.js:105
  );
  ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._compile (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:579:10)
    at Object.newLoader [as .js] (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object._default [as default] (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/af-webpack/lib/getConfig/dev.js:26:45)
    at _default (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/af-webpack/lib/getConfig/index.js:226:29)
    at Object._default [as default] (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/umi-build-dev/lib/getWebpackConfig.js:35:33)
    at Service.run (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/umi-build-dev/lib/Service.js:335:65)
    at Object.<anonymous> (/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/umi/lib/scripts/realDev.js:28:47)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhangyanqi/.npm/_logs/2018-09-29T03_25_22_825Z-debug.log
```

* 日志
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ant-design-pro@2.0.0~prestart: ant-design-pro@2.0.0
6 info lifecycle ant-design-pro@2.0.0~start: ant-design-pro@2.0.0
7 verbose lifecycle ant-design-pro@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zhangyanqi/WebstormProjects/ant-design-pro/node_modules/.bin:/Users/zhangyanqi/smart_shell:/Users/zhangyanqi/repos/bin:/Users/zhangyanqi/repos/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/usr/local/mysql/bin:/usr/local/Homebrew/bin
9 verbose lifecycle ant-design-pro@2.0.0~start: CWD: /Users/zhangyanqi/WebstormProjects/ant-design-pro
10 silly lifecycle ant-design-pro@2.0.0~start: Args: [ '-c', 'cross-env APP_TYPE=site umi dev' ]
11 silly lifecycle ant-design-pro@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.0.0~start: Failed to exec start script
13 verbose stack Error: ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid ant-design-pro@2.0.0
15 verbose cwd /Users/zhangyanqi/WebstormProjects/ant-design-pro
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v6.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by wakaryry** [comment]
多试几次就可以了

**Comment by freestyledash** [comment]
> 多试几次就可以了

试了好几次了，依然失败；并且，多试几次这种做法在开发的时候也不妥吧

**Comment by wakaryry** [comment]
升级一下你的node，重新拉一次

**Comment by xiaohuoni** [comment]
@freestyledash 按你的步骤，重现不了你这个问题。
```bash
WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.
```
这个警告不用理会。
你看看你node的版本是多少

**Comment by chenshuai2144** [comment]
看起来是 node 不支持语法的问题

**Comment by WG-Com** [comment]
```
 node --version
v10.11.0
> umi build


WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.




Compiling

● webpack █████████████████████████ building modules (26%) 138/142 modules 4 active
  node_modules/_umi-plugin-locale@2.1.1@umi-plugin-locale/lib/locale.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-29T16_24_44_917Z-debug.log

```

**Comment by SinghKhalsa** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ant-design-pro@2.1.1~prestart: ant-design-pro@2.1.1
6 info lifecycle ant-design-pro@2.1.1~start: ant-design-pro@2.1.1
7 verbose lifecycle ant-design-pro@2.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.1.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;
9 verbose lifecycle ant-design-pro@2.1.1~start: CWD: F:\project\puncars\app\ant-design-pro
10 silly lifecycle ant-design-pro@2.1.1~start: Args: [ '/d /s /c', 'cross-env APP_TYPE=site umi dev' ]
11 silly lifecycle ant-design-pro@2.1.1~start: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.1.1~start: Failed to exec start script
13 verbose stack Error: ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ant-design-pro@2.1.1
15 verbose cwd F:\project\puncars\app\ant-design-pro
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.14.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tommyspot** [comment]
Hi, currently I'm facing the same warning. Have anyone resolved this problem?

![screen shot 2018-12-09 at 4 53 47 pm](https://user-images.githubusercontent.com/7645519/49695830-3c1ced00-fbd3-11e8-8691-2eb058b3537b.png)

**Comment by Wayxuan** [comment]
> ```
>  node --version
> v10.11.0
> > umi build
> 
> 
> WARNING!!
> umi-plugin-polyfills is deprecated, use config.targets instead.
> 
> 
> 
> 
> Compiling
> 
> ● webpack █████████████████████████ building modules (26%) 138/142 modules 4 active
>   node_modules/_umi-plugin-locale@2.1.1@umi-plugin-locale/lib/locale.js
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ant-design-pro@2.0.0 build: `umi build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ant-design-pro@2.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-09-29T16_24_44_917Z-debug.log
> ```

你好 这个怎么解决的呀
