### ISSUE TITLE
在侧边栏样式问题

### ISSUE THREAD

**Issue by rockwong** [ant-design/ant-design-pro#2445]
1. 将主题设为亮色，固定头部和固定侧边栏时，侧边栏出现横向滚动条
2. 在高级表单页面中，较小窗口下（手机视窗大小），头部和底部 toolbar 出现宽度计算错误。

**Comment by xiaohuoni** [comment]
pro有支持手机吗？

**Comment by chenshuai2144** [comment]
欢迎 pr 一波，很小的 css 问题。
