### ISSUE TITLE
Mac上执行npm install报错

### ISSUE THREAD

**Issue by iwin4aids** [ant-design/ant-design-pro#2446]
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! Unexpected end of JSON input while parsing near '...ck-core":"~0.6.0","we'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jiangkun/.npm/_logs/2018-09-29T06_56_48_901Z-debug.log

**Comment by iwin4aids** [comment]
mac下载最新的2.0.0 release版本 npm install无法完成，报错说说json解析的问题，看截图：

**Comment by chenshuai2144** [comment]
用最新的 npm，最好先删除 node_module。
也有可能你全局装装的某个包更新了

**Comment by iwin4aids** [comment]
> 用最新的 npm，最好先删除 node_module。
> 也有可能你全局装装的某个包更新了

这个是我的错误日志：

4639 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...t":"next","globby":"^'
4639 verbose stack     at JSON.parse (<anonymous>)
4639 verbose stack     at parseJson (/usr/local/Cellar/node@8/8.12.0/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
4639 verbose stack     at consumeBody.call.then.buffer (/usr/local/Cellar/node@8/8.12.0/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
4639 verbose stack     at <anonymous>
4639 verbose stack     at process._tickCallback (internal/process/next_tick.js:189:7)
4640 verbose cwd /Users/jiangkun/frontend/antd-pro-demo
4641 verbose Darwin 18.0.0
4642 verbose argv "/usr/local/Cellar/node@8/8.12.0/bin/node" "/usr/local/opt/node@8/bin/npm" "install"
4643 verbose node v8.12.0
4644 verbose npm  v6.4.1
4645 error Unexpected end of JSON input while parsing near '...t":"next","globby":"^'
4646 verbose exit [ 1, true ]

我所有方法都试过，依然不行，这个错误提示是解析json的问题
我的node是最新的lts版本8.12，npm是6.4.1
这2个都是主流版本

**Comment by ideacco** [comment]
遇到同样的问题和情况：
MAC系统 
node版本8.12，npm是6.4.1
