### ISSUE TITLE
Ant Design Pro 2.0中不能下载高德地图的插件，执行命令npm install --save react-amap后安装失败，请问这个为什么呢？

### ISSUE THREAD

**Issue by pingGuoNiki** [ant-design/ant-design-pro#2449]

**Comment by xiaohuoni** [comment]
这个应该完全和pro无关，但还是试了一下，可以的。你可以看看你的网络，或者看一下安装错误提示。发问题的时候，最好能附上错误信息。^ _ ^
<img width="705" alt="wx20180929-180218 2x" src="https://user-images.githubusercontent.com/11746742/46244473-d57c9580-c411-11e8-90d6-ecb833f65170.png">
