### ISSUE TITLE
是我用的姿势不对吗？加个page这么痛苦

### ISSUE THREAD

**Issue by fantasticsoul** [ant-design/ant-design-pro#2458]
v2迁移到umi了，文档好像准备的不太完善？~/config/router.config.js 文件里新增
```
      // new-page
      {
        path: 'new',
        name: 'new',
        icon: 'plus-square',
        component: 'NewPage',
      }
```
~/src/pages 下新增文件NewPage.js,内容为：
```
export default () => {
  return <div>New Page</div>
};
```

好的，保存编译，然后界面上404 not found

不是按照约定的套路走吗？？？ 倒在这里一早上，晕了

**Comment by OliverJason** [comment]
> path: '/new',
> ...,
> component: './NewPage/'

./NewPage/这样默认是src/pages/NewPage/index.js
