### ISSUE TITLE
TypeError: /root/my-project/src/utils/Yuan.js: Duplicate declaration "React"

### ISSUE THREAD

**Issue by davidvexel** [ant-design/ant-design-pro#2467]
Hi there, has anybody else get this error when running `npm run build`? 

I started getting error like these using v1, then I thought using v2 should solve it but it didn't.

Here is an screenshot, I'm getting the same error either in Ubuntu or MacOS, running Node 8.11 and 9.10

<img width="815" alt="screen shot 2018-10-01 at 7 17 47 pm" src="https://user-images.githubusercontent.com/8060793/46323121-4e1a5800-c5b2-11e8-93d1-f68f41d8565a.png">

Thanks in advance.

**Comment by Leocardoso94** [comment]
Same error here

**Comment by Leocardoso94** [comment]
Running the following command the error stopped for me:

`rm yarn.lock && rm -rf node_modules && yarn && yarn build`

**Comment by davidvexel** [comment]
@Leocardoso94 Worked for me as well, thanks a lot!.

**Comment by davidvexel** [comment]
@arxae May be related with a webpack dependency, very strange indeed.

**Comment by howletz** [comment]
Same error for me with v1.

**Comment by nicolaslair** [comment]
Same error here as well - digging in the dependency hell :)

**Comment by wangh09** [comment]
temporarily fixed by remove some unused import React, and move some other "import React from 'react'" to "import ReactC from 'react'" then change the corresponding use in the code.

**Comment by cenkai88** [comment]
related to this one: https://github.com/umijs/umi/pull/1187

**Comment by cenkai88** [comment]
guys you can delete the `require.resolve('babel-plugin-react-require'),` in `babel-preset-umi/lib/index.js` and retry building.

this plugin imports another react object into context, causing it conflict with the original one in ant design's code

**Comment by wangh09** [comment]
> guys you can delete the `require.resolve('babel-plugin-react-require'),` in `babel-preset-umi/lib/index.js` and retry building.
> 
> this plugin imports another react object into context, causing it conflict with the original one in ant design's code

Thanks! BTW, I'm wondering if there's a more graceful way to fix that? cause it may be inconvenient to delete code in CI&CD.
