### ISSUE TITLE
pro 2.0版本权限设置function无效！

### ISSUE THREAD

**Issue by atishoo** [ant-design/ant-design-pro#2469]
在config/router.config.js中定义的权限配置为function，但是在src/pages/Authorized.js中并未读取到配置的authority属性，不知道是不是一个bug

**Comment by chenshuai2144** [comment]
look here https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/CheckPermissions.js

**Comment by atishoo** [comment]
好吧，我还是贴一下代码吧，我是看了你说的才发了这个

**Comment by atishoo** [comment]
![image](https://user-images.githubusercontent.com/7723403/46457835-4cd17100-c7e6-11e8-941b-2c38b5d2fdd8.png)

我在authority里定义了一个验证权限的function

然后在/src/pages/Authorized.js的children.props.route.authority这个打印出来的是undefined，定义的function被消除了，所以也不会再传到components/Authorized的组件里，更不会过CheckPermissions.js这个文件里的方法，是一开始就是无效的问题，不是组件的毛病，组件是没问题的
