### ISSUE TITLE
Feature request - HeaderSearch, option to keep the text box open

### ISSUE THREAD

**Issue by sahar922** [ant-design/ant-design-pro#2470]
Hi :)
Regards to [this](https://pro.ant.design/components/HeaderSearch/) component,
I'd add a prop to keep the text area always open.

Thanks!

**Comment by chenshuai2144** [comment]
look here https://pro.ant.design/components/HeaderSearch/。

open | The input box is displayed | booelan | false

**Comment by sahar922** [comment]
Open prop keep the Combo box (input options) open.

I suggest to keep the ability to type (before the icon close the text box)

**Comment by chenshuai2144** [comment]
I don't understand very well, but you can pr
