### ISSUE TITLE
关于refs的一个问题

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design-pro#2478]
我在BasicLaoyt做全局tabs时，类似下面加载一个tabs
switch (pane.key) {
      case '/monitor/topologyMonitor':
        return <TopologyMonitor />
      default:
        return null;
 }
TopologyMonitor里面写了一个倒计时：
根据refs获取节点，getID也试了，然后调用innerHtml，后台打印倒计时是准确的，
网页上倒计时却是没动过。
之前没做全局tabs时还是可以的，打印下获取节点也可以获取到，
还有如果在 页面加入任意代码，热启动后倒计时居然又动了，
我想问这是BasicLayout里面获取节点的问题还是什么？

**Comment by chenshuai2144** [comment]
了解一下生命周期
