### ISSUE TITLE
怎么在一个less文件中import另一个less文件

### ISSUE THREAD

**Issue by yinhunfeixue** [ant-design/ant-design-pro#2483]
1、创建less文件  src/a.less，内容如下
`@color: red;`

2、创建less文件  src/layouts/BasicLayout.less，内容如下
```
@import '../a.less';
.title {
  color: red;
}
```

3、在 src/layouts/BasicLayout.js中引入import styles from './BasicLayout.less';

4、npm start，提示如下错误
```
Error { [Error: '../a.less' wasn't found. Tried - ../a.less,/Users/xujunjie/Desktop/aa/node_modules/antd/lib/a.less,/Users/xujunjie/Desktop/aa/a.less,../a.less]
  type: 'File',
  filename: 'input',
  index: 41543,
  line: 1773,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract:
   [ '',
     '@import \'../a.less\';',
     '.antd-pro-layouts-basic-layout-title {' ],
  message:
   '\'../a.less\' wasn\'t found. Tried - ../a.less,/Users/xujunjie/Desktop/aa/node_modules/antd/lib/a.less,/Users/xujunjie/Desktop/aa/a.less,../a.less',
  stack: undefined }
```

**Comment by yinhunfeixue** [comment]
@import '../a.less';

@import '~/a.less';

@import '~/src/a.less';

都试过，都报错

**Comment by JoshuaYang** [comment]
同問

**Comment by daiyu7hao** [comment]
同问，咋没人回答啊？搜过的答案都没用

**Comment by wkeylin** [comment]
同问，初步猜测应该是插件的问题吧

**Comment by lancelixiang** [comment]
不启用主题色修改的话是正常的，但如果启用，less变量只能定义到src/utils/utils.less中，否则就会报文件找不到。
原因未知

**Comment by chalbo** [comment]
问题在.temp 文件里的@import "XXXXXXnode_modules/antd/lib/style/themes/default.less";
antd-pro-merge-less 这个玩意 半成品。坑不少人。
里面代码写死了
const replacedefaultLess = lessPath => {
  const fileContent = fs.readFileSync(lessPath).toString();
  let lessString = fileContent;
  if (lessString.includes("@import '~antd/lib/style/themes/default.less'")) {
    lessString = lessString.replace("@import '~antd/lib/style/themes/default.less';", '');
  }
  return lessString.replace(/@import '.*\/utils.less';/, '');
};

**Comment by chenshuai2144** [comment]
@chalbo 你说的对，删掉这个组件

**Comment by afc163** [comment]
这里提到的升级示例里还有 `antd-pro-merge-less` 的代码，会坑到。https://pro.ant.design/docs/upgrade-v2-cn

**Comment by afc163** [comment]
貌似不是 `antd-pro-merge-less` 的问题，我删掉了 `antd-theme-webpack-plugin` 就好了。

**Comment by chjiyun** [comment]
贼坑，昨天搞到半夜，找不出原因，我还以为路径写错了，到这里来看原来受害者这么多啊，一个功能都不能自定义配置关闭，这不就是半成品么。

**Comment by afc163** [comment]
@chjiyun 来帮我们完善吧，开源项目需要大家一起努力。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/blog/change-theme-cn
https://github.com/ant-design/ant-design-pro/pull/4289
