### ISSUE TITLE
在react-developer-tools下报错，无法查看组件树

### ISSUE THREAD

**Issue by chenguzhen87** [ant-design/ant-design-pro#2486]
？？是什么问题呢

**Comment by chenguzhen87** [comment]
![image](https://user-images.githubusercontent.com/28331609/46674648-46d8f700-cc0f-11e8-8c56-9bc65191da3f.png)
![image](https://user-images.githubusercontent.com/28331609/46674720-77b92c00-cc0f-11e8-9a0a-89347b0cd6f2.png)

**Comment by Ivocin** [comment]
我大概是9月份遇到过这个问题，使用umi@2版本会遇到，经过测试，使用create-umi创建的工程也会报这个错误。
解决方法是安装最新版的react-developer-tools，我目前的版本是3.4.0。
<img width="408" alt="2018-10-10 7 28 21" src="https://user-images.githubusercontent.com/16836801/46733413-d12e6300-ccc2-11e8-9504-f22fc2b974dd.png">
原因还不是很清楚， @sorrycc 不知道有没有注意过这个问题。
