### ISSUE TITLE
ant design pro 在IE下报错

### ISSUE THREAD

**Issue by sorryxc** [ant-design/ant-design-pro#2487]
![20181008162324](https://user-images.githubusercontent.com/43484514/46602211-16675f00-cb22-11e8-81e9-9a3e5b06cc49.png)
![20181008174523](https://user-images.githubusercontent.com/43484514/46602212-16675f00-cb22-11e8-86bd-a5a70aea5bd4.png)

**Comment by chenshuai2144** [comment]
配置了 ie9 也不可能支持到 ie9的

**Comment by sorryxc** [comment]
用win7的IE浏览器切换到edge和IE10打开都不行

**Comment by chenshuai2144** [comment]
ie11 和 edge 测试过的，可以的。
能给个开发环境的报错吗？

**Comment by sorryxc** [comment]
![image](https://user-images.githubusercontent.com/43484514/46658002-352e2a00-cbe4-11e8-8985-5c334728cd73.png)
![image](https://user-images.githubusercontent.com/43484514/46658095-77576b80-cbe4-11e8-821b-815cd8eeef90.png)
![image](https://user-images.githubusercontent.com/43484514/46658068-67d82280-cbe4-11e8-8404-0997bfedd5cc.png)
![image](https://user-images.githubusercontent.com/43484514/46658137-95bd6700-cbe4-11e8-9966-d9f58a86a423.png)


pull的最新代码，然后重新安装的npm包，还是这个问题

**Comment by sorryxc** [comment]
> ie11 和 edge 测试过的，可以的。
> 能给个开发环境的报错吗？

我的电脑是win7的系统，最高只有IE10和默认的edge

**Comment by chenshuai2144** [comment]
win7 怎么会有 edge？
这个好像是箭头函数的问题，你修改一下试试？

**Comment by afc163** [comment]
IE10 不支持的。IE10 里的 edge  模式不是 Edge，两回事。
