### ISSUE TITLE
打开页面空白 js控制台报错 Cannot read property 'authority' of undefined

### ISSUE THREAD

**Issue by suifan** [ant-design/ant-design-pro#2488]
打开页面空白 js控制台报错Cannot read property 'authority' of undefined

**Comment by afc163** [comment]
清空一下 localStorage 再试。

**Comment by suifan** [comment]
![qq 20181008180833](https://user-images.githubusercontent.com/18431787/46603324-511ec680-cb25-11e8-8f07-80470d24bfdf.png)

**Comment by afc163** [comment]
哪个页面？

**Comment by suifan** [comment]
> 哪个页面？所有的页面都这样，我刚才重新下载了最新的，build后上传到服务器还是报那个错

**Comment by afc163** [comment]
给个重现的步骤。

**Comment by suifan** [comment]
好的 您看这是怎么回事呢， 是我node版本的问题还是什么问题呢 直接npm start 是可以正常运行的

**Comment by chenshuai2144** [comment]
你竟然没有 '/' 这个路由。

**Comment by suifan** [comment]
什么意思呢？我现在应该怎么做呢？

**Comment by chenshuai2144** [comment]
按照这个来改 https://github.com/ant-design/ant-design-pro/commit/023984875f8fcedd84e5f8fd7695b6aa127256e5

**Comment by suifan** [comment]
修改后 还是同样报错打不开页面

**Comment by suifan** [comment]
能加您个联系方式吗 我想尽快的解决这个问题

**Comment by suifan** [comment]
我换了台电脑 重新从官网下载的 build后又报这个错误了  
![521](https://user-images.githubusercontent.com/18431787/46662830-0b2e3500-cbef-11e8-8467-7f5c71bc31fa.png)

**Comment by chenshuai2144** [comment]
这是把国际化干掉了
你最好不要做太大的删改

**Comment by suifan** [comment]
我什么都没修改啊，直接从官网下载的什么都没改啊，大神 我明天有个项目要给客户看 能不能帮忙现在给解决下

**Comment by chenshuai2144** [comment]
再试试重新 clone

**Comment by jerryzhengsz** [comment]
我也遇到了同样的问题。
![image](https://user-images.githubusercontent.com/6711439/56409781-228c6000-62ad-11e9-96ff-37c7648de45e.png)

**Comment by zsl1549** [comment]
一样

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/62464474-496c9480-b7bf-11e9-8c6c-6f95b10893a0.png)
