### ISSUE TITLE
Pie can't work with Modal

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design-pro#249]
Put Chart component such as ```Pie``` into Modal will cause rendering error.

### Version
"ant-design-pro": "^0.3.0"
"antd": "^3.0.0-beta.1",

### Environment
OS: macOS High Sierra
browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Minimal example
```js
render() {
  return (
    <Modal
      title='Mytitle'
      visible={visible}
      onCancel={handleCancel}
      width={832}
      footer={null}
    >
      <Pie
        hasLegend
        data={data}
        height={180}
      />
    </Modal>
  )
}

```

### Steps to reproduce
1. Click visible button to open modal. ```Pie``` will render normally in this case.
2. Close the modal and re-open it. ```Pie``` will not be rendered now.

### Conclusion
This issue can be resolved by giving a **unique key** to modal each time it is opened. And this solution is inelegant. 

It's probable because ```Pie``` should have done some ```mount and unmount``` operations which didn't be done in case of modal feature (reusable) when closing: 
```js
componentDidMount() {
    this.renderChart();
    this.resize();
    window.addEventListener('resize', this.resize);
  }
componentWillUnmount() {
    window.removeEventListener('resize', this.resize);
    if (this.chart) {
      this.chart.destroy();
    }
}
```

**Comment by nikogu** [comment]
@kennylbj it is no relationship between with `mount and unmount`.

The reason is when props change the charts will be rerender, but the Modal has `open animation` witch cause the `g2` compute the wrong size.

you can do this to solve it.

```
this.setState({
  visible: true,
}, () => {
  this.setState({
    data: chartsData,
    title: chartsTitle,
  });
});
```

**Comment by kennylbj** [comment]
Then how to explain the normal behavior when the first time modal is mounted or if we give a unique key to that modal?  Both of those situations will perform a correct rendering with modal ```open animation```.

**Comment by nikogu** [comment]
i think the true reason is about `g2 render compute`, but the deep detail that i did not to checked yet.
