### ISSUE TITLE
V2版本根据路由初始化对应的state如何实现

### ISSUE THREAD

**Issue by TerryChenUI** [ant-design/ant-design-pro#2495]
V1版本通过可以通过dynamicWrapper，那么当进入该路由时，默认就有对应的state初始化数据
```
component: dynamicWrapper(app, ['authUser', 'authRole', 'organzation'], () => import('../routes/AuthUser/Index')),
```

V2版本应该如何配置呢

**Comment by chenshuai2144** [comment]
state 是组件的？还是 dva 得？

**Comment by chenshuai2144** [comment]
可以设置 model 的默认值的。

**Comment by laozhu** [comment]
@Evanlai8 

之前我也遇到这个问题了，将应用里各 model 的 initialState 抽出来集中定义，注册一个名为 RESET 的 reducer 来重置，详细的看下面的链接。

<https://github.com/dvajs/dva/issues/907#issuecomment-446483703>
