### ISSUE TITLE
G2是否可以考虑本地加载

### ISSUE THREAD

**Issue by zjp2007** [ant-design/ant-design-pro#250]
可不可以通过本地文件加载不用https请求这种方式？

<script src="https://gw.alipayobjects.com/as/g/??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js"></script>

**Comment by afc163** [comment]
可以自行处理，去掉 excludes 即可。
