### ISSUE TITLE
给个重现的步骤。

### ISSUE THREAD

**Issue by suifan** [ant-design/ant-design-pro#2500]
_Originally posted by @afc163 in https://github.com/ant-design/ant-design-pro/issues/2488#issuecomment-428073640_就是我下载最新版本的什么都不改直接 npm run build 将生成dist文件夹内的文件上传到服务器 通过网址访问就报这个错http://light.8009.org/index.html#

**Comment by afc163** [comment]
直接回复原帖，不要建新 issue。

**Comment by suifan** [comment]
好的  您看这是怎么回事呢， 是我node版本的问题还是什么问题呢  直接npm start 是可以正常运行的
