### ISSUE TITLE
代码提交验证问题

### ISSUE THREAD

**Issue by lhwu** [ant-design/ant-design-pro#2518]
1. 提交前校验，说有个地方需要空14格，但是空了16格，不允许提交
2. 修改错误的地方，再次提交
3. 报错依然，再看代码，修改过的代码回到了原先的地方
4. 死循环中

日志如下：
![日志](https://user-images.githubusercontent.com/20239035/46730901-de941f00-ccbb-11e8-802e-61fa7bee6c7a.png)

**Comment by chenshuai2144** [comment]
可以给看看代码吗？

**Comment by lhwu** [comment]
![image](https://user-images.githubusercontent.com/20239035/46774241-04f5a100-cd34-11e8-9521-d696190ef393.png)
这两行一commit，报错后就又被改回去了

**Comment by lhwu** [comment]
同批次提交的代码，其他有报错的，修改之后能提交。就这个出问题

**Comment by lhwu** [comment]
刚才改了下，提交成功了
![image](https://user-images.githubusercontent.com/20239035/46774472-26a35800-cd35-11e8-88e5-dd853182e292.png)

**Comment by chenshuai2144** [comment]
这个规则不应该冲突吧

**Comment by lhwu** [comment]
图二是我修改过后的，但还是校验失败，错误信息在图一
