### ISSUE TITLE
windows10 npm install 报错

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design-pro#2521]
```
5811 error Unexpected end of input at 1:2630
5811 error "^2.0.0","remark-preset-wooorm":"^1.0.0","tape":"^4.5.1","xo":"^0.17.
```
![image](https://user-images.githubusercontent.com/12553638/46778457-51e27300-cd46-11e8-8be6-efe25b4e4c75.png)

**Comment by mushroomlb** [comment]
从Windows中删除Node.js：
先卸载，然后手动删除如下目录或文件

C:\Program Files (x86)\Nodejs
C:\Program Files\Nodejs
C:\Users\{User}\AppData\Roaming\npm（或%appdata%\npm）
C:\Users\{User}\AppData\Roaming\npm-cache（或%appdata%\npm-cache）
删除代理 C:\Users\用户\xxx.npmrc
