### ISSUE TITLE
button style is lost on mac?

### ISSUE THREAD

**Issue by kalsolio** [ant-design/ant-design-pro#2524]
yarn
yarn start
got this.
![image](https://user-images.githubusercontent.com/14342288/46786233-d80eb180-cd66-11e8-9483-18ff2d5e217a.png)

**Comment by chenshuai2144** [comment]
css 没有加载成功？

**Comment by zxj963577494** [comment]
@kalsolio 如何解决mac下按钮样式无法应用的问题的？

**Comment by kalsolio** [comment]
@zxj963577494 
注释掉config/config.js下一些配置
```
            // dll: {
            //   include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
            //   exclude: ['@babel/runtime'],
            // },
            // hardSource: true,
```

**Comment by zxj963577494** [comment]
@kalsolio 非常感谢

**Comment by kalsolio** [comment]
@chenshuai2144 @afc163 为什么呢 我其实也不知道 只是感觉是这里的问题 注释掉就好了 
在比较新的版本中 貌似已经没有这个问题了

**Comment by xiaohuoni** [comment]
hardSource 插件有问题，基本上umi已经废弃了这东西！
