### ISSUE TITLE
当登录时输入的账号和密码不正确时(不是默认的)f12控制台会报错，原因应该是开发人员马虎所致，线上也是有问题的，虽然问题已解决，但是希望开发人员在源码中更正

### ISSUE THREAD

**Issue by sunxiaochuan** [ant-design/ant-design-pro#2525]
具体的两条报错信息：
[React Intl] Missing message: "app.message-login.invalid-credentials" for locale: "zh-CN"[React Intl] Cannot format message: "app.message-login.invalid-credentials", using message id as fallback.

解决方法：
将 `src\pages\User\Login.js` 中的 `app.message-login.invalid-credentials` 改为 `app.login.message-invalid-credentials` 即可

**Comment by afc163** [comment]
提 issue 不如提 PR~

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/ant-design-pro/pull/2532
