### ISSUE TITLE
antd-pro中已开启的css模块化后，引入.css样式文件无效

### ISSUE THREAD

**Issue by l2en** [ant-design/ant-design-pro#2526]
antd-pro项目中已开启的css模块化后，怎样才能使用.css样式？

**Comment by chenshuai2144** [comment]
```
const style = requre("./index.css")

<div className={style.main}/>
```

**Comment by l2en** [comment]
> ```
> const style = requre("./index.css")
> 
> <div className={style.main}/>
> ```

感谢回复！~ 因为整合项目，原css比较多，不知能否让css与模块化共存？

**Comment by chenshuai2144** [comment]
可以设定忽略一些文件夹的

**Comment by l2en** [comment]
> 可以设定忽略一些文件夹的

设置忽略后，我如下引入
```
import './public/main.css'

<div className='fontStyle'>........</div>
```
但测试后还是无法使用T_T

**Comment by l2en** [comment]
非常感谢！ 已经解决，在.css改成less文件后，加上全局:global就行了

**Comment by lddlww** [comment]
请问，这个要怎么配置？
