### ISSUE TITLE
V2.0 切换主题报错，

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#2528]
V2,0切换主题报错，，但是在本地调试又没问题，build 出来就有问题。
Failed to update theme ParseError: Unrecognised input in http://erp.jo365.cn/color.less on line 1, column 1: 1

**Comment by afc163** [comment]
生产环境不要使用动态构建主题。

<img width="277" alt="image" src="https://user-images.githubusercontent.com/507615/46796566-94747180-cd7f-11e8-92a1-e3a2a9f5be81.png">

**Comment by xgj1988** [comment]
但是我另外一个项目 在生产环境 构建 就没有问题，，不知道为什么。。

**Comment by chenshuai2144** [comment]
看起来像是 less 的格式不对

**Comment by xgj1988** [comment]
@chenshuai2144  如何定位呢。。而且这个color.less 不是我生成的。。也不知道哪个地方生成的。。

**Comment by xgj1988** [comment]
@chenshuai2144  我现在把我另外一个生产环境的color.less 拷贝到 这个报错的项目下面 ，，也不行。。应该不是color问题吧。

**Comment by chenshuai2144** [comment]
http://erp.jo365.cn/color.less
你的路由有问题

**Comment by xgj1988** [comment]
@chenshuai2144  谢谢，果然是nginx 拦掉了。

**Comment by xgj1988** [comment]
@chenshuai2144  帅哥。问一下你，为什么不建议在生产环境下面使用呢？我发现并没什么问题撒。

**Comment by chenshuai2144** [comment]
卡

**Comment by xgj1988** [comment]
@chenshuai2144  如果不平凡切换并不会卡撒。。一般主题没人有事没事就切换撒。

**Comment by afc163** [comment]
1. less 的在线编译有性能和兼容性问题，具体见：http://lesscss.org/usage/#using-less-in-the-browser
2. `不建议使用` 意味着出了问题需要你自己排查，我们是不管的。

**Comment by xgj1988** [comment]
@afc163  好的。谢谢。

**Comment by RivanLuo** [comment]
@afc163 想实现在线切换主题的功能，有什么方案或者demo吗

**Comment by RivanLuo** [comment]
这个问题如何解决 [https://github.com/ant-design/ant-design-pro/issues/2847](url)
