### ISSUE TITLE
Table 组件的更新问题

### ISSUE THREAD

**Issue by lifegit** [ant-design/ant-design-pro#2530]
Table 组件在更新后，现在点击表头将会触发onChange，因为通常在onChange里进行过滤排序等业务，并且会向后台去请求新数据。现在这样触发onChange，即使没有新的过滤排序等业务条件，也会发起请求，并且table会进入loading，用户反馈体验很不好。希望点击表头不会触发onChange！当然更新后点击表头后，此列会灰，这个功能很nice，谢谢。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/12515
