### ISSUE TITLE
pro2.0版中，Card组件的title属性使用栅格（Row,Col）无效

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#2534]

**Comment by chenshuai2144** [comment]
title 是用栅格是什么操作？有重现地址吗？

**Comment by linzelong95** [comment]
感谢回复。Card组件的title使用布局，这在pro v1.0是可行的，但我迁移到pro v2.0后，title中栅格布局会失效。这是半个月前的提问，不知问题是否得到了修复。代码及结果展示如下图。
![code](https://github.com/linzelong95/aboutGit/blob/master/%E8%AE%A2%E5%8D%95.png)
![result](https://github.com/linzelong95/aboutGit/blob/master/%E8%AE%A2%E5%8D%952.png)

**Comment by xiaohuoni** [comment]
@linzelong95 我这里看不到图

**Comment by linzelong95** [comment]
@xiaohuoni  
你好，点击蓝色链接“result”可以看到图片，很抱歉我还不知道如何才能让图片直接在回复区中显示出来
