### ISSUE TITLE
设置proxy后登录，浏览器弹出登录对话框

### ISSUE THREAD

**Issue by linyongfu2013** [ant-design/ant-design-pro#2536]
![1539330040853](https://user-images.githubusercontent.com/4011963/46855040-37d38e00-ce35-11e8-8104-0f0939cf0349.jpg)

proxy & api 设置如下：
```
  proxy: {
    "/api": {
      "target": "http://10.0.0.106:8102/inner-admin",
      "changeOrigin": true
    }
  },

export async function signin(params) {
  return request('/api/v1/global/signin', {
    method: 'POST',
    body: params,
  });
}
```

是什么问题？

**Comment by chenshuai2144** [comment]
和后端沟通一下你们的登录权限方式吧
这是默认的一种登录方式

**Comment by linyongfu2013** [comment]
> 和后端沟通一下你们的登录权限方式吧
> 这是默认的一种登录方式

怎么就close 了啊？？这么粗暴的吗？

后端也是我写的啊，后端都没接收到请求，在浏览器就被block 掉了。

**Comment by chenshuai2144** [comment]
HTTP协议中的Basic Authentication

**Comment by chenshuai2144** [comment]
这种 基础知识，建议去掘金之类的社区问
