### ISSUE TITLE
Wrong path/cmd published at pro.ant.design

### ISSUE THREAD

**Issue by ieow** [ant-design/ant-design-pro#2538]
I am not sure if I should submit the issue here but..
Wrong path/cmd published at pro.ant.design

```
$ git clone git@github.com:ant-design/ant-design-pro.git --depth=1
$ cd ant-design-pro
$ npm install
$ npm start # open browser and visit http://localhost:8000
```

It should be git clone `https://github.com/ant-design/ant-design-pro.git` --depth=1

**Comment by afc163** [comment]
PR is welcome~

**Comment by ieow** [comment]
I dont think it is part of the repo.
The Landing Page [https://pro.ant.design](https://pro.ant.design)
