### ISSUE TITLE
动态路由加载问题

### ISSUE THREAD

**Issue by ityao** [ant-design/ant-design-pro#254]
在model中去重定向一个页面, 例如下面这样
`yield put(routerRedux.push('/user/register'));  `
就会报错

warning.js?0eb7:33 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the DynamicComponent component.
printWarning @ warning.js?0eb7:33
warning @ warning.js?0eb7:57
warnAboutUpdateOnUnmounted @ react-dom.development.js?6241:12045
scheduleUpdateImpl @ react-dom.development.js?6241:13202
scheduleUpdate @ react-dom.development.js?6241:13124
enqueueSetState @ react-dom.development.js?6241:9646
ReactComponent.setState @ react.development.js?9875:218
(anonymous) @ dynamic.js?2420:99
Promise resolved (async)
load @ dynamic.js?2420:96
DynamicComponent @ dynamic.js?2420:82
constructClassInstance @ react-dom.development.js?6241:9760
updateClassComponent @ react-dom.development.js?6241:10215
beginWork @ react-dom.development.js?6241:10605
performUnitOfWork @ react-dom.development.js?6241:12573
workLoop @ react-dom.development.js?6241:12682
callCallback @ react-dom.development.js?6241:1299
invokeGuardedCallbackDev @ react-dom.development.js?6241:1338
invokeGuardedCallback @ react-dom.development.js?6241:1195
performWork @ react-dom.development.js?6241:12800
scheduleUpdateImpl @ react-dom.development.js?6241:13185
scheduleUpdate @ react-dom.development.js?6241:13124
enqueueSetState @ react-dom.development.js?6241:9646
ReactComponent.setState @ react.development.js?9875:218
(anonymous) @ dynamic.js?2420:99
Promise resolved (async)
load @ dynamic.js?2420:96
DynamicComponent @ dynamic.js?2420:82
constructClassInstance @ react-dom.development.js?6241:9760
updateClassComponent @ react-dom.development.js?6241:10215
beginWork @ react-dom.development.js?6241:10605
performUnitOfWork @ react-dom.development.js?6241:12573
workLoop @ react-dom.development.js?6241:12682
callCallback @ react-dom.development.js?6241:1299
invokeGuardedCallbackDev @ react-dom.development.js?6241:1338
invokeGuardedCallback @ react-dom.development.js?6241:1195
performWork @ react-dom.development.js?6241:12800
scheduleUpdateImpl @ react-dom.development.js?6241:13185
scheduleUpdate @ react-dom.development.js?6241:13124
scheduleTopLevelUpdate @ react-dom.development.js?6241:13395
updateContainer @ react-dom.development.js?6241:13425
(anonymous) @ react-dom.development.js?6241:17105
unbatchedUpdates @ react-dom.development.js?6241:13256
renderSubtreeIntoContainer @ react-dom.development.js?6241:17104
render @ react-dom.development.js?6241:17129
render @ index.js?7620:126
start @ index.js?7620:68
(anonymous) @ index.js?1fdf:31
(anonymous) @ index.js:3214
__webpack_require__ @ index.js:708
fn @ index.js:113
(anonymous) @ index.js:2851
__webpack_require__ @ index.js:708
(anonymous) @ index.js:806
(anonymous) @ index.js:809

**Comment by afc163** [comment]
有没有具体（非常具体）的重现步骤。

**Comment by ddcat1115** [comment]
现在就有这样做，没有发现问题 https://github.com/ant-design/ant-design-pro/blob/master/src/models/login.js#L24

有进一步问题再 reopen
