### ISSUE TITLE
导航跳转到一个新页面(不包含在menu中),如何保留显示menu菜单栏？

### ISSUE THREAD

**Issue by ryr1990** [ant-design/ant-design-pro#2541]

**Comment by baiyulong** [comment]
这个问题我能看明白，给你说一下我的解决方案
```javascript
{
  path: '/xxx/tab',
  name: '高亮菜单',
  component: './xxx/tab/layout',
  hideChildrenInMenu: true,
  routes: [
    {
      path: '/xxx/tab',
      redirect: '/xxx/tab/page',
    },
    {
      path: '/xxx/tab/page',
      name: 'page',
      component: './xxx/tab/Page1',
    },
    {
      path: '/xxx/tab/page2',
      name: 'page2',
      component: './xxx/tab/Page2',
    },
    {
      path: '/xxx/tab/page3',
      name: 'page3',
      component: './xxx/tab/Page3',
    },
  ],
},
```
其中layout的内容按需求写，如果 page 1，2，3没有公共内容，都是单独页面，那么layout就很简单

```javascript
import React, { Component, Fragment } from 'react';
import { connect } from 'dva';

@connect()
class layout extends Component {
  render() {
    const { children } = this.props;
    return (
      <Fragment>
        {children}
      </Fragment>
    );
  }
}
export default layout;
```
如果有公共内容，在layout中自己添加需要的
这样就解决了页面跳转到 Page1，Page2，Page3的时候菜单 "高亮菜单" 都是高亮的
不知道你说的问题是不是这个，请做参考

**Comment by codedart2018** [comment]
> 这个问题我能看明白，给你说一下我的解决方案
> 
> ```js
> {
>   path: '/xxx/tab',
>   name: '高亮菜单',
>   component: './xxx/tab/layout',
>   hideChildrenInMenu: true,
>   routes: [
>     {
>       path: '/xxx/tab',
>       redirect: '/xxx/tab/page',
>     },
>     {
>       path: '/xxx/tab/page',
>       name: 'page',
>       component: './xxx/tab/Page1',
>     },
>     {
>       path: '/xxx/tab/page2',
>       name: 'page2',
>       component: './xxx/tab/Page2',
>     },
>     {
>       path: '/xxx/tab/page3',
>       name: 'page3',
>       component: './xxx/tab/Page3',
>     },
>   ],
> },
> ```
> 
> 其中layout的内容按需求写，如果 page 1，2，3没有公共内容，都是单独页面，那么layout就很简单
> 
> ```js
> import React, { Component, Fragment } from 'react';
> import { connect } from 'dva';
> 
> @connect()
> class layout extends Component {
>   render() {
>     const { children } = this.props;
>     return (
>       <Fragment>
>         {children}
>       </Fragment>
>     );
>   }
> }
> export default layout;
> ```
> 
> 如果有公共内容，在layout中自己添加需要的
> 这样就解决了页面跳转到 Page1，Page2，Page3的时候菜单 "高亮菜单" 都是高亮的
> 不知道你说的问题是不是这个，请做参考

没试，晚上回去试试。但我感觉这个是跟据路由来的，如果路由不是　/xxx/tab 下的路由应该不会高亮吧。
