### ISSUE TITLE
chart里的MiniProgress tooltip没有用

### ISSUE THREAD

**Issue by mmmaomao21** [ant-design/ant-design-pro#2543]
ant-design-pro": "^2.0.0",
没有tooltip

**Comment by chenshuai2144** [comment]
MiniProgress 没有 tooltip 这个属性的，你需要增加一个？

**Comment by mmmaomao21** [comment]
@chenshuai2144 需要把 感觉那个target也需要显示具体值

**Comment by chenshuai2144** [comment]
去看看 g2 的 api。或者可以给提供一个 pr

**Comment by mmmaomao21** [comment]
@chenshuai2144 无法提issue了？ 提完成功了但是页面上没有的

**Comment by mmmaomao21** [comment]
@chenshuai2144 chart中Gauge值有bug
源代码中为什么对值先除10-->var data = [{ value: percent / 10 }];
然后又乘以10---》 + data[0].value * 10 + '%\n   ？？？

传入值为11.1时，显示为11.099999999999998

**Comment by bgold0** [comment]
https://github.com/ant-design/ant-design-pro/issues/3761
