### ISSUE TITLE
Failed to execute 'setItem' on 'Storage': Setting the value of 'xxx' exceeded the quota.

### ISSUE THREAD

**Issue by keroroqingwa** [ant-design/ant-design-pro#2547]
chrome浏览器：
![image](https://user-images.githubusercontent.com/21325125/46902817-84cf6700-cefe-11e8-9d11-3ccba9879915.png)

好像是内容比较多的时候会出现这个异常
我现在暂时把 “.then(response => cachedSave(response, hashcode))” 这一行注释了就没出问题。

我的问题是：
1. 出现这个问题的原因？
2. 我暂时注释了上面那段代码算不算是很好的解决方案？
3. 对于这个异常，有什么建议给到我吗？

**Comment by keroroqingwa** [comment]
> 太大的建议不要保存在浏览器里，缓存是真珍贵的

我明白这个。可是这个是框架本身做的处理，我没得选择啊，所以我现在也只能暂时注释  “.then(response => cachedSave(response, hashcode))” 这一行代码

**Comment by chenshuai2144** [comment]
可以某些请求关掉的，不过删掉也挺好的

**Comment by keroroqingwa** [comment]
那我还是先注释掉吧 ...

**Comment by afc163** [comment]
@chenshuai2144 这是你的 fetch 缓存导致的吧？

**Comment by chenshuai2144** [comment]
是，缓存的大小是有限的
