### ISSUE TITLE
Typescript definition is error TS2714

### ISSUE THREAD

**Issue by rohmanhm** [ant-design/ant-design-pro#2549]
I have problem with typescript definition in your `lib/index.d.ts`

![image](https://user-images.githubusercontent.com/7524911/46907090-94b76d00-cf37-11e8-8702-d04876d84f00.png)
I also tried to import with this way
But it throws the same error.
```ts
import { Result } from 'ant-design-pro';
```

The error is
```bash
/home/romsy/Code/Projects/lumpang/office/node_modules/ant-design-pro/lib/index.d.ts
(21,16): error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.
```

I think the error is coming from your type definition. Here's I inspect into your type def.

![pro ant error](https://user-images.githubusercontent.com/7524911/46907148-6ab27a80-cf38-11e8-913e-396475b80bc2.png)

Here's my `tsconfig.json` config
```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": false,
    "noImplicitThis": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["./node_modules/@types", "./typings"],
    "baseUrl": "src",
    "paths": {
      "~/*": ["*"]
    }
  },
  "include": ["./src/**/*", "./typings"],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}

```

Any solution will be apreciated. 
Thanks

**Comment by chenshuai2144** [comment]
i will fixed in new version

**Comment by chenshuai2144** [comment]
fix in  https://github.com/ant-design/ant-design-pro-site/pull/228

**Comment by rohmanhm** [comment]
Thanks for your quick response.
Can't wait to implement it soon.

**Comment by chenshuai2144** [comment]
Can try to upgrade 2.1

**Comment by rohmanhm** [comment]
Now it throws 2 errors,

![image](https://user-images.githubusercontent.com/7524911/46999732-b5a6da80-d150-11e8-940c-0fee3f436cc8.png)


```bash
A 'declare' modifier is required for a top level declaration in a .d.ts file.
```

and 

```bash
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.
```

**Comment by rohmanhm** [comment]
Moved to https://github.com/ant-design/ant-design-pro-site/issues/229
