### ISSUE TITLE
Form表单 initialValue取值类型

### ISSUE THREAD

**Issue by lishuai1021** [ant-design/ant-design-pro#2552]
绑定textarea文本域，后台返回一文本——访问链接:https://pro.ant.design/index-cn，我把这段文本分割拼成访问链接: + <a>https://pro.ant.design/index-cn</a>的形式，后面的a链接部分在页面中渲染成[object Object]。
问题是initialValue只能用string吗

**Comment by afc163** [comment]
textarea 只支持 string。
