### ISSUE TITLE
Authorization Sub Route Problem

### ISSUE THREAD

**Issue by codesignist** [ant-design/ant-design-pro#2554]
Authorization works great for menu.

I have a routing like this:

```JavaScript
// design
      {
        path: '/design',
        icon: 'edit',
        name: 'design',
        component: './Design/Modeling/Modeling',
        authority: ['admin', 'designer'],
      },
// produce
      {
        path: '/produce',
        icon: 'table',
        name: 'produce',
        authority: ['admin', 'designer', 'staff'],
      },
```

A user with a 'staff' authority can not access
**/design**
but, can access
**/design/draw**
route.

What should we do?

**Comment by chenshuai2144** [comment]
you can use https://pro.ant.design/components/Authorized-cn/#scaffold-src-components-Authorized-demo-AuthorizedFunction

**Comment by codesignist** [comment]
In the previous version of Ant Design Pro; sub routes can inheritance parent route authentication.
But now, sub pages returns undefined authentication.

If the page route like this:

Works (admin)
- List
-- All
-- Detail

Normal user can not see **Works** and **Works/List** but can see **Works/List/All**.

Authority can not inheritance to grand children, only affects children.

**Comment by chenshuai2144** [comment]
`@Secured('admin')` 
Can this meet the requirements?
