### ISSUE TITLE
[请教]v2添加新页面失败

### ISSUE THREAD

**Issue by TempoPain** [ant-design/ant-design-pro#2555]
在router.config.js中添加新页面时，会报404。
即使更改原有的路由路径，也会报404。
如：
        path: '/dashboard1',
        name: 'dashboard1',
        icon: 'dashboard',
        routes: [
          {
            path: '/dashboard1/analysis',
            name: 'analysis',
            component: './Dashboard/Analysis',
          }
          .......
或这样：
       name: 'single-plane',
        icon: 'user',
        path: '/single-plane',
        routes: [
          { path: '/single-plane', redirect: '/single-plane/monitor1' },
          {
            path: '/single-plane/monitor1',
            name: 'monitor1',
            component: './SinglePlane/Monitor1',
          }
          .......
此时，菜单栏正确生成菜单，但点进去是404。
仔细翻阅文档，初步学习了umi，尝试不同的component、不同的path，发现只要path不是原有的dashboard、forms、list等，在菜单之中点进去就会报404,找了很久也没有找到是哪里的问题，多谢解答🙏🙏🙏

**Comment by whq361** [comment]
我也发现有这个问题了。每次start运行之后，umi 下router.js 会发生版本回退

**Comment by chenshuai2144** [comment]
single-plane  umi 支持 -吗？

**Comment by TempoPain** [comment]
> single-plane umi 支持 -吗？

换成singleplane同样不行，似乎仅仅在router.config.js中添加，能够正确路由，但是不能找到指定的component，
因为我复制了已有的路由，可以正确显示，但给已有的路由如dashboard、list等改个名字，就不能用了，好像在哪里还有一层代码一样，但我没找到

**Comment by TempoPain** [comment]
> 我也发现有这个问题了。每次start运行之后，umi 下router.js 会发生版本回退

是刚升级到v2吗？   问题解决了吗？  我在v1下一切都正常，升级到v2之后连新增页面这一个最简单的操作都做不成，且我不是专业的前端开发，没有前端debug能力，折腾几天仍没有找到原因

**Comment by chenshuai2144** [comment]
你的项目地址能给我们看一下吗？

**Comment by whq361** [comment]
> > 我也发现有这个问题了。每次start运行之后，umi 下router.js 会发生版本回退
> 
> 是刚升级到v2吗？ 问题解决了吗？ 我在v1下一切都正常，升级到v2之后连新增页面这一个最简单的操作都做不成，且我不是专业的前端开发，没有前端debug能力，折腾几天仍没有找到原因

我也没找到哈，之前V1确实都没问题，第一次用V2就发现有这个问题了。

**Comment by chenshuai2144** [comment]
试试升级全局的 npm 包

**Comment by TempoPain** [comment]
> 试试升级全局的 npm 包

谢谢解答，已经解决。
解决方式：重新clone了一份最新代码，把我的代码贴进去，一切全部正常了。
很遗憾没有找到之前的问题，只记得上次clone的代码应该是两三周甚至更久之前，那时候v2版的文档还没有完全更改完成。
