### ISSUE TITLE
如何将2.0.0升级到2.1.0，项目已经基于2.0.0开发一部分了

### ISSUE THREAD

**Issue by wy-ang** [ant-design/ant-design-pro#2556]
如题，求大佬给个不是按照官方推荐的对比文件的解决方案，对比文件工作量太大了。

**Comment by wy-ang** [comment]
而且项目也在2.0.0的基础上又进行了适合业务逻辑的修改

**Comment by chenshuai2144** [comment]
git 是最好的办法了。
暂时 没有更棒的方案

**Comment by wy-ang** [comment]
> git 是最好的办法了。
> 暂时 没有更棒的方案

直接git pull https://github.com/ant-design/ant-design-pro合并，然后解决冲突？

**Comment by chenshuai2144** [comment]
是的，pro 的耦合性太高了

**Comment by chenshuai2144** [comment]
不过2.1改动不是很多，你可以试着 merge 一下

**Comment by wy-ang** [comment]
@chenshuai2144 试了，几十个文件，上百处需要merge 的 ，工作量太大。

**Comment by shaopeng1** [comment]
感觉是比较麻烦，用的2.0现在2.1想平滑的升级过去没有个简单的方案

**Comment by wy-ang** [comment]
@shaopeng1 对，现在我打算重写了。不过这终究不是长久之计，还是希望官方有一套平滑的简单的升级方案
