### ISSUE TITLE
What is the recommend way of getting the updates?

### ISSUE THREAD

**Issue by amirkenar** [ant-design/ant-design-pro#2560]
First of all, thank you for the great work. I might have missed it but what is the best practice for getting the updates. I only found the approach by cloning the repo but just wondering if there are any better ways to do so? I suspect everyone wants to develop their own app but also get the updates and bug fixes.

**Comment by kennylbj** [comment]
Merge the upstream's updates each time you need to update if you app is **similar enough** to ant-design-pro.
```cmd
git remote add upstream https://github.com/ant-design/ant-design-pro.git

git fetch upstream

git checkout master

git rebase upstream/master
```

Or just patching commits manually if your app is quite **different** from pro (Recommended).

**Comment by kennylbj** [comment]
@chenshuai2144 okay
