### ISSUE TITLE
如何修改根目录，使得build后的文件的引用路径是相对路径

### ISSUE THREAD

**Issue by wedjg** [ant-design/ant-design-pro#2564]
目前build后dist目录下的文件引用路径基本都是绝对路径，build后直接打开index.html会提示许多文件的路径不对。尝试过在package.json中添加"homepage":".",也没有效果。

**Comment by wedjg** [comment]
补充一下，部署到apache服务器中也提示路径错误

**Comment by chenshuai2144** [comment]
publicPath

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#publicpath
