### ISSUE TITLE
选中菜单用户管理，菜单没有变为选中状态的颜色为什么？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#2566]
![_20181016142655](https://user-images.githubusercontent.com/37643958/46996851-990aa280-d150-11e8-806e-5d5cbf20b3e7.png)

**Comment by chenshuai2144** [comment]
菜单根据 url 进行选中，
试试最新的代码
https://github.com/ant-design/ant-design-pro/commit/f473b000f7cfd3a83d8f04b729cdb2b7c2e0136d

**Comment by baiyulong** [comment]
你也许需要这个
https://github.com/ant-design/ant-design-pro/issues/2541#issuecomment-433189629
