### ISSUE TITLE
请问如何在菜单嵌入外部http地址？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#2568]
![_20181016143622](https://user-images.githubusercontent.com/37643958/46997551-8db87680-d152-11e8-8280-fe5fbeedbcfe.png)

**Comment by afc163** [comment]
@chenshuai2144 应该要有通用的解决方案。

**Comment by pkaq** [comment]
新建一个组件 这个组件里面是个iframe 把外部链接传给这个iframe

**Comment by m4jing** [comment]
@pkaq 如果就是想要往外跳转呢？比如：博客的友情链接那样的。

**Comment by quanpower** [comment]
嗯，现在也碰到这个需求，两个后台间互相跳转

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/2762

**Comment by chenshuai2144** [comment]
外部和内部的区别不大呀。
@zhuguangyue 你要详细秒速你碰到的问题，这样才有可能得到解决方案
