### ISSUE TITLE
IHeaderSearchProps导致ts编译不通过

### ISSUE THREAD

**Issue by fanlide** [ant-design/ant-design-pro#2569]
![default](https://user-images.githubusercontent.com/20534139/46999789-39fd5b80-d159-11e8-81c3-6f8eebf756de.png)

ant-design-pro：2.1.0

defaultOpen、open 必填导致ts编译不通过

**Comment by chenshuai2144** [comment]
有兴趣搞一个 pr吗？

**Comment by fanlide** [comment]
@chenshuai2144 好的 🤓
