### ISSUE TITLE
高级表单成员管理表格编辑输入问题

### ISSUE THREAD

**Issue by Molloh** [ant-design/ant-design-pro#257]
当编辑一行中的第二或第三个输入框时，会自动聚焦到第一个输入框上
去除输入框的autoFocus属性就无法连续输入
官网上的预览页面时没有问题的，但是新的工程下npm start后就会出现这个问题

**Comment by Molloh** [comment]
```
  handleFieldChange(e, fieldName, key) {
    const newData = [...this.state.data];
    const target = this.getRowByKey(key);
    if (target) {
      target[fieldName] = e.target.value;
      this.setState({ data: newData });
    }
  }
```
这段代码里面每次都因为Input的改变更新了state，导致组件重新渲染，无法正常接受下一个输入

貌似是这个原因 @afc163

**Comment by afc163** [comment]
本地无法重现，请确保和 master 版本的代码一致。

**Comment by xiaqingping** [comment]
我好像有个类似的问题，我的ProFormDigit始终无法手动聚焦，只能table切换来输入，始终找不到原因，可能和pro组件嵌套有关联，希望有知道原因的大佬可以给出指点
![image](https://github.com/ant-design/ant-design-pro/assets/49116631/66f06c2c-0ce9-497d-8e13-19dffb2144f8)
