### ISSUE TITLE
表格全选框使用selections之后的对齐问题

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#2572]
table使用selections之后，设置table的size="middle"，这时表格的复选框不能对齐，默认表格大小可以对齐

![default](https://user-images.githubusercontent.com/39291213/47005661-c8c4a500-d166-11e8-9b02-a4307a0abf9c.png)

**Comment by afc163** [comment]
antd 问题请提到这里：http://new-issue.ant.design/?repo=ant-design
