### ISSUE TITLE
穿梭框中搜索内容重置后不能清空，或者其他方式也不能清空问题

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#2573]
示例：
![default](https://user-images.githubusercontent.com/39291213/47005849-396bc180-d167-11e8-95bc-d8bd6416b4f9.png)

**Comment by chenshuai2144** [comment]
你是受控模式吗？

**Comment by m26597** [comment]
怎样设置受控模式，设置之后通过field.reset就可以重置了么？

**Comment by chenshuai2144** [comment]
你可能需要学习一下 react 的基础知识
