### ISSUE TITLE
编译时出现 Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by ergoulee** [ant-design/ant-design-pro#2575]
![2018-10-16 5 35 17](https://user-images.githubusercontent.com/15899945/47007022-de879980-d169-11e8-93e4-f17c1484f755.png)
一大堆,但不影响结果.
貌似和history: 'hash',有关?

**Comment by changxiao** [comment]
发生了同样问题

**Comment by chenshuai2144** [comment]
官方的无法复现，是 umi 的版本原因吗？

**Comment by HughSunny** [comment]
我也遇到了，重新install一下才可以

**Comment by sorrycc** [comment]
hardSource 的问题，删除 `./node_modules/.cache` 后重启。

**Comment by lp4298707** [comment]
> hardSource 的问题，删除 `./node_modules/.cache` 后重启。

删除之后 重启  没出现  改了东西热更新之后又出现了
