### ISSUE TITLE
ant design pro2.1.0版本，如何使用线上服务器接口

### ISSUE THREAD

**Issue by hepf888** [ant-design/ant-design-pro#2576]
用网上下载下来的最新代码，在config.js文件里打开proxy把接口切换到线上，为何不起作用，关闭了mock也不骑作用，还需要修改什么地方吗，才能走线上的接口地址啊？？

**Comment by mushroomlb** [comment]
npm run start:no-mock

**Comment by bookman920** [comment]
问题1：如果一半接口在mock中，一半已经迁移到了线上，这在调测阶段经常出现，那么关不关mock都很纠结...

问题2：实测结果是，在不用环境变量关闭mock、删除Mock文件中相应接口的情况下，在config.js中设置proxy，出现GET切到线上，而POST仍旧无法切换的情况，是proxy的写法问题吗？
```js
  proxy: {
    "/api/execute/*": {
      "target": "http://localhost:8080",
      "changeOrigin": true,
      "pathRewrite": { "^/api/execute" : "" }
    }
  },
```

**Comment by secreter** [comment]
不能实现api 级别的mock吗？全盘mock 的场景几乎没有
