### ISSUE TITLE
antd pro fecth提交服务端怎么保持session一致

### ISSUE THREAD

**Issue by linqunshan** [ant-design/ant-design-pro#2578]
antd pro fecth提交服务端怎么保持session一致

**Comment by chenshuai2144** [comment]
前后端分离应该使用 auth 模式来进行 session 校验

**Comment by linqunshan** [comment]
auth 模式是没有问题，但antd1.2的版本还是用sessionid来校验，升级后就不能用了，好像是fecth方法有升级了

**Comment by chenshuai2144** [comment]
应该不会的。session 是根据 cookie 来保持的，你可以排查一下 cookie
