### ISSUE TITLE
Pro 1.0 升级2.0 出现一些模块和依赖未找到，报错如下，大概是什么原因？

### ISSUE THREAD

**Issue by lusonghe0313** [ant-design/ant-design-pro#2579]
ERROR  Failed to compile with 18 errors09:39:45

These dependencies were not found:

* @components/Result in ./src/pages/Process/Result/Error.js
* components/Result in ./src/pages/Result/Success.js, ./src/pages/Result/Error.js
* components/StandardTable in ./src/components/Selector/UserSelector.js
* components/StandardTable/ProcessTable in ./src/components/Selector/ProcessSelector.js, ./src/components/Selector/Section/DeptTree.js and 4 others
* rc-drawer-menu in ./src/components/SiderMenu/index.js
* rc-drawer-menu/assets/index.css in ./src/components/SiderMenu/index.js

To install them, you can run: npm install --save @components/Result components/Result components/StandardTable components/StandardTable/ProcessTable rc-drawer-menu rc-drawer-menu/assets/index.css

These relative modules were not found:

* ../../../index in ./src/pages/Process/Result/Success.js
* ../../routes/Process/ProcessFormPrint in ./src/components/PrintHeader/index.js
* ../index in ./src/utils/requestAjax.js
* ../routes/Exception/404 in ./src/layouts/PrintLayout.js, ./src/layouts/MainLayout.js and 1 other

**Comment by chenshuai2144** [comment]
umi 升级了吗？

**Comment by lusonghe0313** [comment]
升级了，相关模块的问题我解决了，相关依赖的问题不知道什么原因， @chenshuai2144

**Comment by lusonghe0313** [comment]
我按照文档说明上一步一步升级2.0版本的

**Comment by chenshuai2144** [comment]
@components 是个别名
rc-drawer-menu 这个应该可以删掉了，新版本项目里面已经没有这个了

**Comment by chenshuai2144** [comment]
components 换了位置了，你修改一下路径就好了

**Comment by lusonghe0313** [comment]
我现在项目运行起来了，在页面显示一些错误  首行写着  
[app.model] namespace should be unique  这大概是什么原因？

**Comment by lusonghe0313** [comment]
@chenshuai2144 
我现在项目运行起来了，在页面显示一些错误  首行写着  
[app.model] namespace should be unique   
这大概是什么原因？

**Comment by chenshuai2144** [comment]
model 重复了
