### ISSUE TITLE
急！发布正式环境后，代理配置无效。

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#258]
我在项目中使用的是：.roadhogrc.js 配置方式。

> 配置如下：

`
export default {
  entry: "src/index.js",
  extraBabelPlugins:[
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties",
    ["import", { "libraryName": "antd-mobile", "libraryDirectory": "lib", "style": true }]
  ],
  extraPostCSSPlugins: [
    require('postcss-pxtorem')({
      rootValue: 100,
      propWhiteList: []
    })
  ],
  autoprefixer:{
    browsers: ['last 2 versions', 'Firefox ESR', '> 1%', 'ie >= 8', 'iOS >= 8', 'Android >= 4'],
  },
  svgSpriteLoaderDirs:[
    require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
    // path.resolve(__dirname, 'src/assets/svg'),  // 业务代码本地私有 svg 存放目录
  ],
  env:{
    development: {
      extraBabelPlugins: [
        "dva-hmr"
      ]
    },
    production: {}
  },
  externals:{
    "g2": "G2",
    "g-cloud": "Cloud",
    "g2-plugin-slider": "G2.Plugin.slider"
  },
  ignoreMomentLocale:true,
  theme: "./src/theme.js",
  proxy: {
    "/api": {
      target: "http://115.29.239.213:9002/",// 服务器地址
      changeOrigin: true,
      secure: false
    }
  }
}
`

在执行：npm run build 之后发布到服务器上，访问的接口不是我配置的代理服务器的接口。

@sorrycc  @请问我的这个配置有什么问题吗？

**Comment by nikogu** [comment]
@hqwlkj 这个....代理是本地 server 的服务，你 build 以后，怎么还有代理功能呢，你连服务都没有

**Comment by afc163** [comment]
代理配置是用于本地调试阶段，部署后走的都是你源码的逻辑。

**Comment by hqwlkj** [comment]
@nikogu   @afc163   你们 发布 到服务器不是将build后的代码直接上传到服务器的吗？那你们又是在服务器上做的处理呢？

**Comment by xufei** [comment]
那是在开发阶段，启动了一个“临时”的服务器来做的，构建结果是脱离这个服务器的。你构建完之后，放真实环境，当然是要去调用真实的服务 api，跟整个这套东西都是无关的。

你仔细想想，服务端 api 在每个步骤下，到底是谁在提供。发布之后，这套框架就是纯客户端的，没有任何服务端逻辑，服务端 api 要你自己建立。

**Comment by hqwlkj** [comment]
@nikogu @afc163 @xufei    谢谢，我用自己的方式已经处理好了。

**Comment by codepandy** [comment]
@hqwlkj 分享下解决方法啊
