### ISSUE TITLE
ant design pro 2.0 增加publicPath发布问题

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design-pro#2580]
在`config/config.js`中增加`publicPath`之后, 打包没有自动创建publicPath目录，资源路径也不对。

![image](https://user-images.githubusercontent.com/5092728/47057471-809f9400-d1f3-11e8-97c6-9600c6267b65.png)

**Comment by chenshuai2144** [comment]
publicPath 要配合 base 一起使用

**Comment by ganxunzou** [comment]
好的，我试试

**Comment by ganxunzou** [comment]
@chenshuai2144   增加了`base`的设置后，还是不对。

![wechatimg2](https://user-images.githubusercontent.com/5092728/47057915-58b13000-d1f5-11e8-8f7e-c3c4de04e4af.jpeg)

**Comment by chenshuai2144** [comment]
输出路径是根据 outputPath 来修改的

**Comment by chenshuai2144** [comment]
publicPath 地址是静态文件的地址

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#outputpath 先看看文档

**Comment by yansuan** [comment]
![image](https://user-images.githubusercontent.com/18570764/47061825-d41add80-d205-11e8-8539-0b94d3e6cd5b.png)
config/config.js文件

**Comment by ganxunzou** [comment]
其实我的目标很简单，传统的B/S项目，都有一个`WebContext`目录，所以我想那就加`publicPath`吧，但是遇到的如下问题。
（PS： 当然我可以选择不加WebContext，用Nginx直接代理，但是这就脱离了这个问题本身了。）

@chenshuai2144  如果有空，建议好好看看我的问题，我知道你们应该很忙，但是这个问题应该挺普遍的。

整理一下遇到的问题：
- 问题1：开发环境publicPath没生效（`图1`）
- 问题2：不参与编译的静态资源问题问题（`图2`）
- 问题3：publicPath配置成相对目录（`图3`）

`图1`
![1 publicpath](https://user-images.githubusercontent.com/5092728/47066602-39c49500-d219-11e8-8c4e-373167a6f728.png)

`图2`
![2](https://user-images.githubusercontent.com/5092728/47066603-39c49500-d219-11e8-9d14-fa54a46a62aa.png)

`图3`
![image](https://user-images.githubusercontent.com/5092728/47066567-20bbe400-d219-11e8-8987-81be26da0527.png)

**Comment by sorrycc** [comment]
看下这篇能不能帮你解决问题，https://umijs.org/zh/guide/deploy.html

**Comment by ganxunzou** [comment]
@sorrycc 大神， base: '/static/' 解决了另外一个问题，react-router 路由映射问题。但是上面的三个问题依旧存在。


我现在的解决办法（配置依旧和上面一样）：
1. 所有不参与编译的静态资源放到 `public/static` 目录下
2. 开发中使用：`<img src="/static/logo.png" />`
3. `npm run build ` 编译成功后，手动将"/dist/static/static/" 目录的所有资源剪切到："/dist/static"。 

这样问题算是解决了（后续考虑，看看是否可以用`copy`动态做第三步）。

**Comment by sorrycc** [comment]
> 问题1：开发环境publicPath不完全生效（图1）

dev 时 publicPath 是 `/`，不允许配置。

> 问题2：不参与编译的静态资源问题问题（图2）

模板里用 `<%= context.publicPath %>` 表示 publicPath 路径，参考 https://umijs.org/guide/html-template.html#configure-the-template

> 问题3：publicPath配置成相对目录（图3）

通常情况下，不要用相对路径。

**Comment by lambert666** [comment]
> config.js

想问下，为什么我的 config/ 目录下，没有 config.js 。这改如何配置 base、publicPath ?
