### ISSUE TITLE
无法通过authority实现服务端控制权限

### ISSUE THREAD

**Issue by bnez** [ant-design/ant-design-pro#2582]
按照文档去修改utils/authority.js里面的getAuthority()，在其中加上了service调用，但是request是异步调用，没等出结果，getAuthority函数就返回了。如果我给getAuthority加上async，其他调用getAuthority的地方好像也不会等到getAuthority的返回，直接就判断无权限，给我跳转到login去了。

**Comment by chenshuai2144** [comment]
getAuthority 没出来之前让整个页面 loading 就好了

**Comment by bnez** [comment]
> getAuthority 没出来之前让整个页面 loading 就好了

这样就跳转到login去了
不过，现在是打算用这个思路，先同步返回一个最小权限的authority确保页面加载，然后componentDisMount的里面加上真正的权限异步调用和菜单刷新

**Comment by chenshuai2144** [comment]
最外层加一个 loading
