### ISSUE TITLE
下载后npm install无法安装依赖

### ISSUE THREAD

**Issue by aiyuekuang** [ant-design/ant-design-pro#2583]
warning dva > react-router-redux@5.0.0-alpha.9: This project is no longer mainta
ined.
warning antd-theme-webpack-plugin > antd-theme-generator > less > request > hawk
 > hoek@2.16.3: The major version is no longer supported. Please update to 4.x o
r newer
warning antd-theme-webpack-plugin > antd-theme-generator > less > request > hawk
 > sntp > hoek@2.16.3: The major version is no longer supported. Please update t
o 4.x or newer
warning antd-theme-webpack-plugin > antd-theme-generator > less > request > hawk
 > boom > hoek@2.16.3: The major version is no longer supported. Please update t
o 4.x or newer
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer
 supported. Contact support@npmjs.com for more info.
warning merge-umi-mock-data > rollup-plugin-node-builtins > browserify-fs > leve
l-js > xtend > object-keys@0.4.0:
warning merge-umi-mock-data > rollup-plugin-node-builtins > browserify-fs > leve
l-filesystem > level-sublevel > xtend > object-keys@0.2.0: Please update to the
latest object-keys
warning umi > umi-build-dev > af-webpack > hard-source-webpack-plugin > jsonlint
 > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more
 info.
warning umi > umi-build-dev > af-webpack > webpack-bundle-analyzer > bfj-node4@5
.3.1: Switch to the `bfj` package for fixes and new features!
warning umi > umi-build-dev > atool-monitor > urllib > proxy-agent > socks-proxy
-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to
avoid a serious bug with socket data flow and an import issue introduced in 2.1.
0
warning umi-plugin-react > umi-plugin-dva > dva > react-router-redux@5.0.0-alpha
.9: This project is no longer maintained.
[3/5] Fetching packages...
error eslint@5.7.0: The engine "node" is incompatible with this module. Expected
 version "^6.14.0 || ^8.10.0 || >=9.10.0".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information p
rovided in "D:\\react\\antd_pro\\one\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.
报这么一堆错

**Comment by chenshuai2144** [comment]
node 版本不对

**Comment by aiyuekuang** [comment]
我的是node9.3.0，不支持？

**Comment by chenshuai2144** [comment]
"^6.14.0 || ^8.10.0 || >=9.10.0".

**Comment by chenshuai2144** [comment]
要么使用正式版，要么使用最新的
