### ISSUE TITLE
Hot Reload时而不生效是什么原因呢

### ISSUE THREAD

**Issue by eric379990** [ant-design/ant-design-pro#2586]
麻烦请问下，2.0的版本基础上做开发，现在用npm start启动项目之后，修改代码，有时候热加载会生效，有时候却不工作，terminal上看到了保存代码之后重新编译了，但是Chrome里页面就是不刷新，手动刷新也没用，重新编译也没有出错。请教有没有解决的思路。

**Comment by sorrycc** [comment]
停止 `npm start`，删除 `node_modules/.cache`，重新 `npm start` 试试。

**Comment by eric379990** [comment]
> 停止 `npm start`，删除 `node_modules/.cache`，重新 `npm start` 试试。

这两天各种试，整个把node_modules目录删了也试过，还是会出现。

**Comment by sorrycc** [comment]
缓存都清空了，为啥还是会不生效呢？页面上显示的还是老的代码？

**Comment by sorrycc** [comment]
那就奇怪了，这个 `接口列表1` 是哪里来的呢。。给复现步骤吧。

**Comment by eric379990** [comment]
原来代码里的<PageHeaderWrapper title="接口列表">，我把它改成了“接口列表1”，页面刷新成功，然后我又把1改成2，就变成了现在这个样子，代码里已经是“接口列表2”了，页面上什么反应都没有，还是“接口列表1”，有时候重新npm start也还是“接口列表1”，不能更新到2，感觉浏览器就没有感知到代码变化了。

**Comment by chenshuai2144** [comment]
你需要升级一下 config.js 了

**Comment by gaoxiaosong1113** [comment]
我也有同样的问题

**Comment by ypli0629** [comment]
+1

**Comment by wonderFF** [comment]
+1

**Comment by 2865724220** [comment]
terminal没有编译是什么原因呢

**Comment by rizshivalli** [comment]
+1
