### ISSUE TITLE
配置完jest.config.js中的moduleNameMapper后，单元测试开始报错

### ISSUE THREAD

**Issue by yuquanwang** [ant-design/ant-design-pro#2587]
我对jest进行了moduleNameMapper配置：
```javascript
module.exports = {
  testURL: 'http://localhost:8000',
  moduleNameMapper: {
    "\\.(css|less)$": "<rootDir>/mock/style.js",
    "\\.(gif|ttf|eot|svg)$": "<rootDir>/mock/file.js"
  }
};
```
以上的mock文件是有新建的。
之后运行npm run test:component开始报错，以下为报错信息：
![image](https://user-images.githubusercontent.com/16618169/47072082-de4dd380-d227-11e8-9b7c-684d5d1f9403.png)

请问如何进行jest的配置？
另：如何进行babel的配置？

**Comment by chenshuai2144** [comment]
你把 umi 的别名弄坏了，去看看 umi 的文档吧。
