### ISSUE TITLE
请问各位大神，为什么我添加弹框的时候，如果弹框中有password类型密码输入框，就会导致弹框中输入字段文本框和搜索上面的文本框输入框冲突？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#2588]
![_20181017144721](https://user-images.githubusercontent.com/37643958/47068526-100e6c80-d21f-11e8-843f-89a4d035bab1.png)

**Comment by DezineLeo** [comment]
你的描述不是很清楚，最好贴上相关代码，只能从你的报错提示中看出你的命名出现重复了。

**Comment by chenshuai2144** [comment]
key 重复了
