### ISSUE TITLE
页面加载时css渲染问题

### ISSUE THREAD

**Issue by yuanfuwang** [ant-design/ant-design-pro#259]
用Ant design pro开发，页面显示时，会先出现没有加载样式 的页面，然后再加载并且渲染css，画面出现闪烁，请问怎么解决？

**Comment by hqwlkj** [comment]
同问 +1

**Comment by nikogu** [comment]
@yuanfuwang 这个只有在 dev 才会出现，发布就不会了，暂时还在等待 roadhog 升级
