### ISSUE TITLE
pro从1.0升级2.0 ，项目跑成功后，在页面显示一些错误，namespace should be unique

### ISSUE THREAD

**Issue by lusonghe0313** [ant-design/ant-design-pro#2590]
invariant
node_modules/invariant/browser.js:38
  35 | } else {
  36 |   var args = [a, b, c, d, e, f];
  37 |   var argIndex = 0;
> 38 |   error = new Error(
  39 |     format.replace(/%s/g, function() { return args[argIndex++]; })
  40 |   );
  41 |   error.name = 'Invariant Violation';
View compiled
checkModel
node_modules/dva-core/lib/checkModel.js:28
  25 | 
  26 | (0, _invariant.default)(typeof namespace === 'string', "[app.model] namespace should be string, but got ".concat((0, _typeof2.default)(namespace))); // 并且唯一
  27 | 
> 28 | (0, _invariant.default)(!existModels.some(function (model) {
  29 |   return model.namespace === namespace;
  30 | }), "[app.model] namespace should be unique"); // state 可以为任意值
  31 | // reducers 可以为空，PlainObject 或者数组
View compiled
model
node_modules/dva-core/lib/index.js:84
  81 | 
  82 | function model(m) {
  83 |   if (process.env.NODE_ENV !== 'production') {
> 84 |     (0, _checkModel.default)(m, app._models);
  85 |   }
  86 | 
  87 |   var prefixedModel = (0, _prefixNamespace.default)((0, _objectSpread2.default)({}, m));
View compiled
./src/pages/.umi/initDva.js
src/pages/.umi/initDva.js:27
  24 | app.model({ namespace: 'main', ...(require('D:/YS-project/ys-ui-beta/src/models/main.js').default) });
  25 | app.model({ namespace: 'monitor', ...(require('D:/YS-project/ys-ui-beta/src/models/monitor.js').default) });
  26 | app.model({ namespace: 'process.bac', ...(require('D:/YS-project/ys-ui-beta/src/models/process.bac.js').default) });
> 27 | app.model({ namespace: 'process', ...(require('D:/YS-project/ys-ui-beta/src/models/process.js').default) });
  28 | app.model({ namespace: 'processForm', ...(require('D:/YS-project/ys-ui-beta/src/models/processForm.js').default) });
  29 | app.model({ namespace: 'products', ...(require('D:/YS-project/ys-ui-beta/src/models/products.js').default) });
  30 | app.model({ namespace: 'profile', ...(require('D:/YS-project/ys-ui-beta/src/models/profile.js').default) });
View compiled
__webpack_require__
webpack/bootstrap:724
  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;
View compiled
fn
webpack/bootstrap:101
   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {
View compiled
./src/pages/.umi/umi.js
src/pages/.umi/umi.js:15
  12 | });
  13 | window.g_plugins.use(require('../../../node_modules/umi-plugin-dva/lib/runtime'));
  14 | 
> 15 | require('@tmp/initDva');
  16 | 
  17 | // render
  18 | let oldRender = () => {
View compiled
__webpack_require__
webpack/bootstrap:724
  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;
View compiled
fn
webpack/bootstrap:101
   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {
View compiled
0
http://localhost:8000/umi.js:249553:18
__webpack_require__
webpack/bootstrap:724
  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

**Comment by chenshuai2144** [comment]
排查你的 model  ，name 重复了
