### ISSUE TITLE
将导航模式从侧边改为顶部，并将内容区域宽度改为流式之后再将导航模式改为侧边，布局中有一小部分重叠

### ISSUE THREAD

**Issue by moon-t** [ant-design/ant-design-pro#2591]
![image](https://user-images.githubusercontent.com/15901247/47074536-2d4a3780-d22d-11e8-9004-2b2f5f86f435.png)

**Comment by shaopeng1** [comment]
#2193

**Comment by chenshuai2144** [comment]
升级一下最新的就好了
