### ISSUE TITLE
2.0 无法使用装饰器

### ISSUE THREAD

**Issue by stefaniepei** [ant-design/ant-design-pro#2593]
ant-design-pro 1.0可以通过配置在webpackrc.js里extraBabelPlugins正常使用装饰器，官方文档和UMI文档没有内容参考（https://umijs.org/zh/config/#extrababelplugins）

**Comment by chenshuai2144** [comment]
2.0可以使用的。pro 项目里有一堆

**Comment by stefaniepei** [comment]
不好意思，个人失误，没有引入dva的connect就直接在使用connect了
