### ISSUE TITLE
DELETE method should support return json

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design-pro#2597]
```js
// request.js
return fetch(url, newOptions)
    .then(checkStatus)
    .then(response => cachedSave(response, hashcode))
    .then(response => {
      // DELETE and 204 do not return data by default
      // using .json will report an error.
      if (newOptions.method === 'DELETE' || response.status === 204) {
        return response.text();
      }
      return response.json();
})
```
在request.js中，如果方法是DELETE，返回的body会被解析成字符串，这里有什么依据吗？

我使用场景是删除后，response body返回被删除的对象，这样方便在reducer中更新状态列表。

[RCF](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7/)中也没有说DELETE只能返回字符串。原文如下
> The DELETE method requests that the origin server delete the resource identified by the Request-URI. This method MAY be overridden by human intervention (or other means) on the origin server. The client cannot be guaranteed that the operation has been carried out, even if the status code returned from the origin server indicates that the action has been completed successfully. However, the server SHOULD NOT indicate success unless, at the time the response is given, it intends to delete the resource or move it to an inaccessible location.
>
>A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.
>
>If the request passes through a cache and the Request-URI identifies one or more currently cached entities, those entries SHOULD be treated as stale. Responses to this method are not cacheable.

同见[Is a response-body allowed for a HTTP-DELETE-request?
](https://stackoverflow.com/questions/6581285/is-a-response-body-allowed-for-a-http-delete-request) 这个讨论。

**Comment by chenshuai2144** [comment]
你可以自己修改的
按照标准 Delete 应该返回空

**Comment by kennylbj** [comment]
以下是[stackoverflow](https://stackoverflow.com/questions/6581285/is-a-response-body-allowed-for-a-http-delete-request)上的讨论

> It is explicitly mentioned here in the RFC
>
> The short answer is:
>
> You should include a response body with an entity describing the deleted item/resource if you return 200.
>
> 202 is something like an asynchronous request/response return status.
>
> 204 says explicitly that you do not include a response body.


也就是说，
1. 如果删除成功，返回200和已经删除的资源
2. 如果要删除已经被删除或者不存在的资源，返回204 No Content
