### ISSUE TITLE
pages中页面如何通过路由切换动态加载对应model?

### ISSUE THREAD

**Issue by chenguzhen87** [ant-design/ant-design-pro#2604]
![image](https://user-images.githubusercontent.com/28331609/47166880-bf3a6900-d32f-11e8-8ba3-62a0fef17de6.png)

**Comment by chenshuai2144** [comment]
图文不相关

**Comment by chenguzhen87** [comment]
在开发环境下，期望根据页面加在对应model，今天在umijs上看到sorrycc说开发环境不支持。。。。
