### ISSUE TITLE
生产环境下，pages文件夹下面不同模块之间无法共享modal数据

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#2608]
1、需求：在下面VipManagement页面中获取上面UserManagement页面对应model中的state数据，例如vipList
2、开发环境：能正常获取到vipList
3、生产环境：报错，显示vipList is undefined，生产环境测试多次该问题都存在

![1539921714887](https://user-images.githubusercontent.com/20454290/47197127-cc3e7300-d396-11e8-8ad1-4f86d4c209b0.jpg)

**Comment by chenshuai2144** [comment]
提到modal目录就好了
