### ISSUE TITLE
使用pro2.0,项目运行之后出现如下错，是什么原因 

### ISSUE THREAD

**Issue by lusonghe0313** [ant-design/ant-design-pro#2610]
Error { [Error: '../../../../../node_modules/antd/lib/style/themes/default.less' wasn't found. Tried - ../../../../../node_modules/antd/lib/style/themes/default.less,D:\YS-project\node_modules\antd\lib\style\themes\default.less,D:\node_modules\antd\lib\style\themes\default.less,..\..\..\..\..\node_modules\antd\lib\style\themes\default.less]
  type: 'File',
  filename: 'input',
  index: 96742,
  line: 4464,
  callLine: NaN,
  callExtract: undefined,
  column: 0,
  extract: 
   [ '',
     '@import \'../../../../../node_modules/antd/lib/style/themes/default.less\';',
     '' ],
  message: '\'../../../../../node_modules/antd/lib/style/themes/default.less\' wasn\'t found. Tried - ../../../../../node_modules/antd/lib/style/themes/default.less,D:\\YS-project\\node_modules\\antd\\lib\\style\\themes\\default.less,D:\\node_modules\\antd\\lib\\style\\themes\\default.less,..\\..\\..\\..\\..\\node_modules\\antd\\lib\\style\\themes\\default.less',
  stack: undefined }

**Comment by codepandy** [comment]
npm install 
试试

**Comment by diorwjy** [comment]
把绝对路径改为相对路径， ''../../../../../node_modules/antd/lib/style/themes/default.less“  =>  ''~antd/lib/style/themes/default.less'
