### ISSUE TITLE
js桥与webview交互在最新的ios12.0.1的系统js桥的回调函数没有执行，而用vue写的页面在这个系统上却可以

### ISSUE THREAD

**Issue by caobo001** [ant-design/ant-design-pro#2612]
this.timer = setInterval(function() {
      console.log("获取YLJsBridge。。。")
      if(window.YLJsBridge){
        console.log(12)
        clearInterval(that.timer)
        console.log(window.YLJsBridge.call)
        window.YLJsBridge.call('getAgentId',{},function(data){
          console.log(data)
          if(data.code==0){
              alert(3)
              addSessionData("xiyiAgentsId",data.value)
              that.getMyToken()
            }else{
              alert("获取商家信息失败")
            }
          })
      }
},500)
参数data莫有打印，后面的代码都莫有执行，用vue写的页面却执行了，app提供是同一套api

**Comment by afc163** [comment]
提错地方了。
