### ISSUE TITLE
menu里配置外链，生成path错误

### ISSUE THREAD

**Issue by quanpower** [ant-design/ant-design-pro#2613]
在用umi与antd pro 2的时候，想在pro的菜单里点下跳转到其他后台。现在在pro的路由配置route.config.js配置如下 {
path: '/status',
icon: 'block',
name: 'status',
routes: [
{
path: 'http://www.baidu.com',
name: 'configure',
// component: './Status/Status',

      },

然而得到的route为：

exact: true
name: "configure"
path: "/status/http:/www.baidu.com"

修改哪里可以在判断为外链绝对路径的时候不再拼接路径，直接把设置的http://www.baidu.com返回？谢谢！

**Comment by chenshuai2144** [comment]
这个是umi的

**Comment by chenshuai2144** [comment]
我正在修改最近会发pr

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/1293

**Comment by chenshuai2144** [comment]
fixed
