### ISSUE TITLE
Test suite failed to run TypeError: Cannot read property 'Tab' of undefined

### ISSUE THREAD

**Issue by kolko91** [ant-design/ant-design-pro#2615]
![image](https://user-images.githubusercontent.com/32207299/47221923-3c142400-d3be-11e8-9e22-25c8535a7445.png)

Test setup:
![image](https://user-images.githubusercontent.com/32207299/47221952-4fbf8a80-d3be-11e8-9474-e625924e6237.png)

Test: 
![image](https://user-images.githubusercontent.com/32207299/47222009-6b2a9580-d3be-11e8-9c15-b26dd59ba0d6.png)

Jest Config: 
![image](https://user-images.githubusercontent.com/32207299/47222078-9319f900-d3be-11e8-9754-8e7867df3fe1.png)

**Comment by chenshuai2144** [comment]
感觉像是 别名坏掉了

**Comment by chenshuai2144** [comment]
@sorrycc

**Comment by kolko91** [comment]
Fixed:
tsconfig.test.json add `"esModuleInterop": true`
