### ISSUE TITLE
为什么@connect引入model数据时，命名空间需要写两次？

### ISSUE THREAD

**Issue by tsj11** [ant-design/ant-design-pro#2616]
求助，写代码遇到一件很奇怪的事情，我的`model`定义如下：
![image](https://user-images.githubusercontent.com/10185019/47256482-d7d38c00-d4b3-11e8-9b5f-4d5b30b85415.png)
在`@connect()`时，为什么要写`domains.domians.domainsData`才行？正常不应该是`domains.domainsData`就可以了吗？
![image](https://user-images.githubusercontent.com/10185019/47256495-0b161b00-d4b4-11e8-9648-b8a43b821f52.png)

**Comment by tsj11** [comment]
我尝试看了一下`domians`里面都有啥，结果让我什么困惑……
![image](https://user-images.githubusercontent.com/10185019/47256556-d9ea1a80-d4b4-11e8-97eb-c0916bdbb631.png)

![image](https://user-images.githubusercontent.com/10185019/47256563-19b10200-d4b5-11e8-94c8-b5a8e00b3aba.png)

我定义的`domains`为什么会混入其它的`model`，求大神指点

**Comment by yoyooyooo** [comment]
你这domains没用大括号包起来解构，，其实是state.domians.domainsData

**Comment by tsj11** [comment]
> 你这domains没用大括号包起来解构，，其实是state.domians.domainsData

卧槽！原来如此……是我智障了
