### ISSUE TITLE
FormItem里面的Select控件，initialValue应该需要map到对应的option标题

### ISSUE THREAD

**Issue by tianzhou** [ant-design/ant-design-pro#2619]
假设model里存的一个ENUM状态，0代表关闭，1代表运行中

const state = ['关闭', '运行中''];

<FormItem>
{getFieldDecorator('state', {
  initialValue: currentState,
 })(
  <Select>
    <Option value="0">关闭</Option>
    <Option value="1">运行中</Option>
   </Select>
)}
</FormItem>

如上代码，假设currentState是0，下拉框一开始会显示0，如果选择了下拉框一项后，下拉框才会正确显示为对应的中文状态

**Comment by chenshuai2144** [comment]
建议自己实现以下，这是 select 的逻辑。

**Comment by FanFanJUN** [comment]
动态显示select下拉数据，设置initialValue属性  如你所说 也是先显示默认initialValue值  再显示值所对应的option

**Comment by tianzhou** [comment]
> 建议自己实现以下，这是 select 的逻辑。

又试了一下，当<Select>嵌套在<FormItem>里时，Select的defaultValue设置是无效的，如果说是建议自己实现的话，请提供一下更加具体的建议。

**Comment by chenshuai2144** [comment]
你让后端吧默认的 value 和 key 都可以传回来就好了。
默认有一条下拉框，这样就可以命中了
