### ISSUE TITLE
点击退出登录没有反馈和报错

### ISSUE THREAD

**Issue by icxcat** [ant-design/ant-design-pro#262]
![image](https://user-images.githubusercontent.com/22029390/33107355-d9f064b0-cf71-11e7-84ee-446c9f835e2d.png)
![image](https://user-images.githubusercontent.com/22029390/33107406-1b6a19ae-cf72-11e7-99cc-d49cab892e3a.png)
![image](https://user-images.githubusercontent.com/22029390/33107414-22dbbbde-cf72-11e7-86da-fb5d493a455d.png)
有人遇到点击退出登录没效果吗？但官网的demo是可以登出的。另外没对接真实请求之前，如果登录不出，访问demo的登录页，admin 888..登录完可触发登出事件，这是什么原因啊

**Comment by renyi818** [comment]
@icxcat 这个问题我之前提过，当时处理后，我这边是可以了，你确定是更新的最新版本？见这里 #243

**Comment by icxcat** [comment]
@renyi818 非常感谢，之前没注意到
