### ISSUE TITLE
How can I create a wait-until-response-come-back system in JS?

### ISSUE THREAD

**Issue by jinyuanchun** [ant-design/ant-design-pro#2626]
import { routerRedux } from 'dva/router';
import { stringify } from 'qs';
import { UserAccountLogin, getFakeCaptcha } from '@/services/api';
import { setAuthority } from '@/utils/authority';
import { getPageQuery } from '@/utils/utils';
import { reloadAuthorized } from '@/utils/Authorized';

export default {
  namespace: 'login',

  state: {
    status: undefined,
  },

  effects: {
    *login({ payload }, { call, put }) {
      const response = yield call(UserAccountLogin, payload);
      yield put({
        type: 'changeLoginStatus',
        payload: response,
      });
    },
  },

  reducers: {
    changeLoginStatus(state, { payload }) {
      console.log(payload);                               --     undefined
      setAuthority(payload.currentAuthority);
      return {
        ...state,
        status: payload.status,
        type: payload.type,
      };
    },
  },
};
As I've commented in the code above, apparently that console.log() will be executed as the first line, So it always throws undefined.

As far as I know about dva, firstly effects will be executed and then passes the response to the reducers. But my code doesn't wait until the response come back. Anyway, how can I make a wait-until const response = yield call(UserAccountLogin, payload); get finished and them execute yield put({ system ?

**Comment by chenshuai2144** [comment]
use promise
