### ISSUE TITLE
TableForm.js中点击触发的toggleEditable函数，请问这个是怎么把 editable 属性加到数据中的

### ISSUE THREAD

**Issue by billychou** [ant-design/ant-design-pro#2629]
案例中，TableForm.js中点击触发的toggleEditable函数，怎么把 editable: true 添加到 newData 中的。求解释`const newData = data.map(item => ({ ...item }));`

```  javascript
  toggleEditable = (e, key) => {
    e.preventDefault();
    const { data } = this.state;
    const newData = data.map(item => ({ ...item }));
    const target = this.getRowByKey(key, newData);
    if (target) {
      // 进入编辑状态时保存原始数据
      if (!target.editable) {
        this.cacheOriginData[key] = { ...target };
      }
      target.editable = !target.editable;
      this.setState({ data: newData });
    }
  };
```

**Comment by chenshuai2144** [comment]
`const newData = data.map(item => ({ ...item }));`

是浅拷贝了一份新的数组

**Comment by billychou** [comment]
> `const newData = data.map(item => ({ ...item }));`
> 
> 是浅拷贝了一份新的数组

这个地方逻辑浅拷贝会增加一个 editable 的属性吗？ 这个地方有点疑惑
![image](https://user-images.githubusercontent.com/3585362/47328370-7bcf5a00-d6a3-11e8-8a11-a8ad79bfbf00.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/EditableItem/index.js
