### ISSUE TITLE
左侧当前菜单匹配问题

### ISSUE THREAD

**Issue by 604587986** [ant-design/ant-design-pro#2630]
- 当菜单只有一级的时候，将屏幕缩小至菜单消失，再出现时，匹配不到当前的路由（一级菜单），没有高亮效果。

- 经过观察，发现BaseMenu里的getSelectedMenuKeys函数匹配到的路由数组有问题。
```
  // Get the currently selected menu
  getSelectedMenuKeys = pathname =>
    urlToList(pathname).map(itemPath => getMenuMatches(this.flatMenuKeys, itemPath).pop());
```

- 如果只有一级路由，第二次render的时候，返回的是underfined，若直接使用urlToList函数则能匹配到正确的路由，
```
    // let selectedKeys = this.getSelectedMenuKeys(pathname);   一级路由返回[underfined]
    let selectedKeys = urlToList(pathname);                                    返回正确的路径
```
希望官方在原来的基础上修改一下getSelectedMenuKeys 函数。
bug demo：https://web.q-huan.com/reactadmin

**Comment by chenshuai2144** [comment]
已经发现了，会很快修正
