### ISSUE TITLE
请问V2 版本中如何关闭mock,将请求切换至服务端接口？

### ISSUE THREAD

**Issue by blue-bone** [ant-design/ant-design-pro#2632]

**Comment by blue-bone** [comment]
https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E4%BB%A3%E7%90%86%E5%88%B0%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%9F

**Comment by blue-bone** [comment]
1.设置代理

https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E4%BB%A3%E7%90%86%E5%88%B0%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%9F

2.npm run start:no-mock

**Comment by lianjt** [comment]
非常感谢
