### ISSUE TITLE
request.js - response undefined when status code = 422

### ISSUE THREAD

**Issue by TranDucBlog** [ant-design/ant-design-pro#2635]
My solution:
```
if (response.status >= 200 && response.status < 300 || response.status === 422) {
    return response;
 }
```
Do I do that right?

**Comment by chenshuai2144** [comment]
What problem have you encountered?

**Comment by TranDucBlog** [comment]
> What problem have you encountered?

status code 422 returns validate content, i want to get it to display the message.

**Comment by chenshuai2144** [comment]
you can remove it, 422 should not be returned
