### ISSUE TITLE
编译很慢，开发时每次改动需要100+秒，打包需要300+秒

### ISSUE THREAD

**Issue by YouCaiChina** [ant-design/ant-design-pro#2638]

**Comment by chenshuai2144** [comment]
老版本可以使用externals 来提升编译速度
https://webpack.js.org/configuration/externals/

建议把 react ,g2 bizchart 全部搞掉

**Comment by YouCaiChina** [comment]
老版本没有看到webpack的配置文件在哪里   先升到1.0版本再用这个方法试试
