### ISSUE TITLE
配置publicPath部署后访问报错

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#2642]
在config.js配置
publicPath: '/xxx/',
部署到服务器 访问
http://xx.xx.com/xxx/
报如下错误
Uncaught (in promise) TypeError: Cannot read property 'model' of undefined

**Comment by chenshuai2144** [comment]
base 配置了吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2580
