### ISSUE TITLE
怎么配置接口代理呀 ？ 求助

### ISSUE THREAD

**Issue by wangjunwei531** [ant-design/ant-design-pro#2643]
问题说明：需要请求服务器的数据，修改了 config.js 中的proxy设置，并且运行 npm run start:no-mock  结果仍然请求的是本地的接口地址，求助~~

**Comment by chenshuai2144** [comment]
请先了解`反向代理`

**Comment by wangjunwei531** [comment]
@chenshuai2144   大神，已解决，可以正常请求数据了，谢谢

**Comment by hang333** [comment]
> @chenshuai2144 大神，已解决，可以正常请求数据了，谢谢

请问你使用了什么方案？
之前旧的 ant design 可以
```
export default {
  'GET /api/(.*)': 'http://127.0.0.1:7001/api/',
  'POST /api/(.*)': 'http://127.0.0.1:7001/api/'
};
```
就直接代理了， 非常方便..

**Comment by hang333** [comment]
啊啊找到了， 是 config.js 里的 proxy 物件

**Comment by ti-xian-mu-ou** [comment]
> @chenshuai2144 大神，已解决，可以正常请求数据了，谢谢

请问你是如何解决的？

**Comment by hang333** [comment]
> > @chenshuai2144 大神，已解决，可以正常请求数据了，谢谢
> 
> 请问你是如何解决的？

config.js 中的 proxy 参数

**Comment by zhangWeiZhuang** [comment]
> 问题说明：需要请求服务器的数据，修改了 config.js 中的proxy设置，并且运行 npm run start:no-mock 结果仍然请求的是本地的接口地址，求助~~



> @chenshuai2144 大神，已解决，可以正常请求数据了，谢谢

你好。请问你是怎么解决的，可以分享一下吗？或者贴下代码。 谢谢~

**Comment by junhui75165** [comment]
@chenshuai2144 请教一下build之后的请求地址配置是如何设置的
