### ISSUE TITLE
部分手机报错[React Intl] The Intl APIs must be available in the runtime, and do not appear to be built-in. An Intlpolyfill should be loaded.

### ISSUE THREAD

**Issue by zlq960222** [ant-design/ant-design-pro#2644]
尝试过iss上的方法，无法执行npm install --save intl @babel-polyfill
并且
在src下新建 global.js

import '@babel/polyfill';

global.Intl = require('intl'); 
window.Intl = require('intl');
提示安装@babel/polyfill 并且无法打包
是否有正确的解决方案处理该问题
或者说我不使用国际化可解决该问题

**Comment by chenshuai2144** [comment]
Intl 有自己的polyfill.
https://formatjs.io/guides/runtime-environments/
