### ISSUE TITLE
独立使用PageHeader组件的问题

### ISSUE THREAD

**Issue by xxxsimons** [ant-design/ant-design-pro#2646]
我在自己的项目中单独使用`PageHeader`组件，但是配置面包屑的时候遇到一点点问题。

我使用的路由是`react-router v4`，文档中没有具体提到`breadcrumbNameMap`各个配置参数的含义，我根据`ant-design-pro`的实例做了如下配置。

```js
const breadcrumbNameMap = {
  '/': { path: '/', exact: true, locale: 'menu', redirect: '/list', name: '首页' },
  '/list': {
    name: '列表',
    path: '/list',
    children: {},
  },
  '/list/detail': {
    name: '详细',
    path: '/list/detail',
  },
};

const BPageHeader = ({ location }) => {
  return (
    <PageHeader
      title={breadcrumbNameMap[location.pathname].name}
      location={location}
      breadcrumbNameMap={breadcrumbNameMap}
    />
  );
};

export default withRouter(BPageHeader);
```

但是显示的时候却出现了这样的情况，
![image](https://user-images.githubusercontent.com/25195267/47345014-56127700-d6dc-11e8-962c-b73dde42d41d.png)

有如下问题：
~~1. 第一个跟我配置的不对应，总是为`Home`而不是我配置的`首页`。（可能是我配置的不对）~~
2. 点击面包屑跳转的时候，整个页面会重新渲染，而不是局部更新。（可能跟路由为`react-router v4`有关）

有什么解决办法嘛？是否要自己改写组件？

第一个问题已解决，没看清文档。。。

**Comment by chenshuai2144** [comment]
试试这个 linkElement，改成你使用 Link

**Comment by xxxsimons** [comment]
> 试试这个 linkElement，改成你使用 Link

解决了，非常感谢！我自己没认真看文档哭泣

**Comment by drdevelop** [comment]
@chenshuai2144 你好，这个title不要这个属性，占着的位置能不能去掉

**Comment by sophieChenyx** [comment]
你好 改成link 是什么意思 这里不能用嵌套的routes吗
我这边配置的 menuLIst  和 route.config 都是嵌套 
然后递归进去的
