### ISSUE TITLE
authority is Promise

### ISSUE THREAD

**Issue by lanxxg** [ant-design/ant-design-pro#2647]
请问是这样写吗？权限判断返回Promise时一直在loading。

![image](https://user-images.githubusercontent.com/26108613/47353131-15bbf480-d6ee-11e8-9cdc-21917b3b83da.png)

**Comment by chenshuai2144** [comment]
你那个是 function ，需要直接返回Promise

hava Promise()

**Comment by lanxxg** [comment]
你是说`authority={havePermission()}`吗?试了还是一直loading

在PromiseRender.js生命周期componentDidUpdate里会无限循环。

我看api文档写着authority参数是function时可以返回Promise, 在`CheckPermissions.js`里也有这样的判断
![image](https://user-images.githubusercontent.com/26108613/47408923-b31d3400-d793-11e8-940a-7c86b5437b6d.png)
其次直接定义一个Promise,如

```
const p = new Promise((resolve, reject) => {
     setTimeout(function() {
       resolve();
     }, 1000);
});
```
然后传给authority`authority={p}`还是一样的问题。

**Comment by lanxxg** [comment]
@awakenin 我把PromiseRender.js生命周期componentDidUpdate去掉了，不考虑new props

**Comment by jzoe** [comment]
@lanxxg 去掉 componentDidUpdate ，子组件就没法正常更新了吧。例如访问 /，重定向到 /home，那么到 /home 页后就是空白页了。

这个promise在文档中也没有说明，是因为本身有bug吗 @chenshuai2144

**Comment by dushaobindoudou** [comment]
修改成这样试试吧，做测试遇到这个问题，都不敢用了：

```
componentDidUpdate(nextProps) {
    if (nextProps.ok === this.props.ok && nextProps.error === this.props.error) {
        return false;
    } else {
        this.setRenderComponent(nextProps);
    }
  }
```
