### ISSUE TITLE
v2版线上构建报错

### ISSUE THREAD

**Issue by yanlong147** [ant-design/ant-design-pro#2648]
<img width="1280" alt="_20181023182409" src="https://user-images.githubusercontent.com/44398505/47354265-e22e9980-d6f0-11e8-835f-652ee3d4a496.png">
问题如上

**Comment by yanlong147** [comment]
已安装umi

**Comment by afc163** [comment]
明显是 npm install 安装时的网络问题，和 pro 无关。
