### ISSUE TITLE
发布后页面404报错

### ISSUE THREAD

**Issue by yanlong147** [ant-design/ant-design-pro#2652]
![_20181024105441](https://user-images.githubusercontent.com/44398505/47403260-6594cd00-d77b-11e8-9a1f-4c9f8c1b0f78.png)

**Comment by chenshuai2144** [comment]
请认真阅读文档。
https://pro.ant.design/docs/deploy-cn#%E4%BD%BF%E7%94%A8-nginx

**Comment by yanlong147** [comment]
按文档配置后
数据交互报500错

**Comment by yanlong147** [comment]
location /admin {
        proxy_pass 服务器地址;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
