### ISSUE TITLE
注册bug

### ISSUE THREAD

**Issue by wkeylin** [ant-design/ant-design-pro#2653]
在注册页面判断是否注册成功是在该组件的生命周期中判断，会造成注册成功后返回注册页面，输入时会触发路由跳转，model里保存的status未重置，或者直接在model中进行路由跳转比较好
![t c z 05d 5pr83sprv dlu](https://user-images.githubusercontent.com/21221921/47404920-d212ca80-d781-11e8-89ef-86e58eef7045.png)

**Comment by chenshuai2144** [comment]
你不应该这么写，注册是否成功应该在 请求完成之后判断
didupdate  干这种事肯定会出事

**Comment by wkeylin** [comment]
> 你不应该这么写，注册是否成功应该在 请求完成之后判断
> didupdate 干这种事肯定会出事

这是antdpro里面这样写的
