### ISSUE TITLE
Can open a new room for English in Gitter?

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design-pro#2654]
It is better to standardize the entire project using English communication.

**Comment by n-sikka** [comment]
Please do. If you do please share the link here @xyy94813

**Comment by xyy94813** [comment]
https://gitter.im/ant-design-pro-english/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link @n-sikka

**Comment by afc163** [comment]
https://gitter.im/ant-design/pro-english
