### ISSUE TITLE
Module parse failed: Unexpected character '#' (1:0)

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#2655]
npm 版本 6.4.1

> ant-design-pro@2.1.0 start /Users/lewin/Documents/workspace/sourcecode/enterprise-bank-web
> cross-env APP_TYPE=site umi dev

[hardsource:64522fc6] Writing new cache 64522fc6...
[hardsource:64522fc6] Tracking node dependencies with: package-lock.json, yarn.lock, .umirc.js, .umirc.local.js, config/*.
✔ success webpack compiled in 11s 975ms

 ERROR  Failed to compile with 1 errors                              下午1:04:35

 error  in ./node_modules/npm/bin/npm-cli.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| ;(function () { // wrapper in case we're in module_context mode
|   // windows: running "npm blah" in this folder will invoke WSH, not node.

 @ ./node_modules/npm/lib/npm.js 472:4-32
 @ dll umi

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.1.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lewin/.npm/_logs/2018-10-24T05_04_35_794Z-debug.log

**Comment by LewinJun** [comment]
直接clone demo下来报的错

**Comment by chenshuai2144** [comment]
更新你的 node版本
