### ISSUE TITLE
run build之后不能正确触发 login/logout的问题

### ISSUE THREAD

**Issue by page1990** [ant-design/ant-design-pro#2656]
在dev 模式下，点击用户退出登录，执行`dispatch({type: 'login/logout',});`是可以正确的退出登录的。但是每次运行npm run build之后，在生产环境下面，点击退出登录有没有反应了。需要先用户登录成功后，然后重新点击退出登录才可以。

**Comment by chenshuai2144** [comment]
官方 demo 是 ok 的。

**Comment by page1990** [comment]
> 官方 demo 是 ok 的。

我知道官方demo是ok的，我使用npm start的方式启动，是可以正常的登录登出。但是我运行npm run build之后，在生产环境中点击这个退出登录没有反应了。需要先进入到用户登录界面，登录完成后，才可以正常的退出登录。

**Comment by zula1994** [comment]
我也出现这个问题了。。。
