### ISSUE TITLE
项目打包部署在nginx服务器上(非根目录),静态资源文件(css,js文件)404

### ISSUE THREAD

**Issue by zhichao8756** [ant-design/ant-design-pro#2660]
打包文件放在nginx服务器的根目录下可以正常运行,二级目录就无法获取静态资源文件,是不是跟nginx的配置有关?
![image](https://user-images.githubusercontent.com/24514251/47419078-08fed580-d7ae-11e8-91e4-f7f5c41fd6cd.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/config/#publicpath
https://umijs.org/config/#base

**Comment by yanhao98** [comment]
> https://umijs.org/config/#publicpath
> https://umijs.org/config/#base

这两个配置了以后生成的index.html文件中有一个color.less的目录还是访问根目录，请问这个访问不到文件有什么影响吗？

**Comment by pxim** [comment]
> > https://umijs.org/config/#publicpath
> > https://umijs.org/config/#base
> 
> 这两个配置了以后生成的index.html文件中有一个color.less的目录还是访问根目录，请问这个访问不到文件有什么影响吗？

你这个问题怎么解决的，我现在图片资源也会访问根目录
