### ISSUE TITLE
发布后调用后台接口报500的错

### ISSUE THREAD

**Issue by xiouluo** [ant-design/ant-design-pro#2662]
location /admin {
        proxy_pass 后台地址;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }

**Comment by chenshuai2144** [comment]
请详细说明

**Comment by xiouluo** [comment]
如上配置自己的服务器，前端调用接口报500错
