### ISSUE TITLE
关于BasicLayout建议

### ISSUE THREAD

**Issue by rudyzou** [ant-design/ant-design-pro#2665]
实际项目中，很多功能还是需要直接修改BasicLayout的代码。
比如
1、getPageTitle返回前缀是 ant-design-pro，但实际项目是要返回自己的项目名称的。
2、消息提醒，有可能只要消息，没有待办和通知，现在是必须修改  GlobHeader里面的RightContent里面的代码。
3、又比如HeaderSearch
4、又比如菜单需要从服务器获取，必须更改BasicLayout的代码  等。

但是BasicLayout这个组件 antd-pro团队是在不断优化的，我想在我们项目中可以不断的更新得到这些升级优化，可以无缝升级。现在很难做到，升级一次需要整理BasicLayout的代码，很费时间。

希望antd-pro团队考虑下这个问题。

**Comment by afc163** [comment]
脚手架的意义在于用户可以随意修改代码，我们也推荐你这么做。如果希望修改并和上游保持一致，欢迎探索通用的解决方案并给我们 PR。
