### ISSUE TITLE
Modal.confirm 样式混乱

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#2667]
￼
￼
![1540435479697](https://user-images.githubusercontent.com/22336356/47472924-000c1380-d843-11e8-95a0-070881aed4d9.jpg)

**Comment by ffalconjs** [comment]
antd pro应用到confirm的样式有误 ant-confirm-body ant-confirm-btns
而独立antd是正确的ant-modal-confirm-body ant-modal-confirm-btns

**Comment by zhuanglong** [comment]
我也遇到过一次，删除 node_modules，重新 install 就好了

**Comment by chenshuai2144** [comment]
估计是 antd 有两个版本
用 npm ls

**Comment by ShuBuShao** [comment]
我这边页也遇到了, 排查到问题是演样式没有加载 , bable配置的问题

引入babel-plugin-import
`["import", {
            "libraryName": "antd",
            "style": "css"
        }]`
