### ISSUE TITLE
less 热更新问题

### ISSUE THREAD

**Issue by zuimeiaj** [ant-design/ant-design-pro#2669]
npm start 启动项目后 less 热更新正常，但是用一会后修改less文件就无法更新了，console里面显示 [HMR] css reload http://localhost:8000/umi.css，但是样式实际没有变，只有全局刷新才行。
修改global.less里面的样式始终有效
os : mac
ant-design-pro :2.1.0
webpack :4.19.1

**Comment by chenshuai2144** [comment]
感觉是我的插件问题。

**Comment by A-birdFlyHigner** [comment]
ant-design-theme 这个插件注释掉确实也就好了

**Comment by CrassusX** [comment]
> onfig/plugin.config.js

说那么多不使用那里面的插件，也不说清楚不用哪个插件，禁用ant-design-theme这个就行
