### ISSUE TITLE
umi build 出现 insert google analytics

### ISSUE THREAD

**Issue by ZevveZ** [ant-design/ant-design-pro#2672]
如何去掉google的统计，使用umi dev没有这个问题。

**Comment by afc163** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
删除 ga 的配置就好了。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/config/config.js#L40

**Comment by afc163** [comment]
按之前的讨论，用环境变量来配置 config 里的这个插件吧。
