### ISSUE TITLE
Exception 的 linkElement 的类型有误

### ISSUE THREAD

**Issue by kostark** [ant-design/ant-design-pro#2674]
```
export interface IExceptionProps {
  ...
  linkElement?: React.ReactNode;  // -> linkElement?: React.ComponentType | string
  ...
}
```

**Comment by chenshuai2144** [comment]
fixed

**Comment by RunningCoderLee** [comment]
在 `tsconfig` 文件中开启 `strict` 模式后，依然会报错，如下：

![image](https://user-images.githubusercontent.com/13218863/54018616-19937380-41c4-11e9-9265-95a385dbccdd.png)

完整报错内容如下： 

> 不能将类型“typeof Link”分配给类型“string | ComponentClass<{}, any> | FunctionComponent<{}> | undefined”。
  不能将类型“typeof Link”分配给类型“ComponentClass<{}, any>”。
    参数“props”和“props” 的类型不兼容。
      Property 'to' is missing in type '{}' but required in type 'Readonly<LinkProps>'.ts(2322)
index.d.ts(48, 5): 'to' is declared here.
index.d.ts(8, 3): The expected type comes from property 'linkElement' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Exception> & Readonly<IExceptionProps> & Readonly<{ children?: ReactNode; }>'
