### ISSUE TITLE
v2 global.less样式丢失

### ISSUE THREAD

**Issue by linyuliang** [ant-design/ant-design-pro#2675]
dev开发中刷新浏览器会造成global.less中样式丢失，这个时候保存一下global.less编译一次才能生效。
编译后，global.less里面的样式不生效
umi中已解决，issues链接如下：
[https://github.com/umijs/umi/issues/1002](https://github.com/umijs/umi/issues/1002)

**Comment by chenshuai2144** [comment]
坐等发版本吧
