### ISSUE TITLE
使用独立的 PRO 组件如何进行国际化？

### ISSUE THREAD

**Issue by huang6349** [ant-design/ant-design-pro#2677]
如题，

组件库版本 V2.1.0，我在node的安装包中并没有看见国际化的语言包

**Comment by chenshuai2144** [comment]
组件库为什么需要国际化？

**Comment by huang6349** [comment]
因为我在使用独立组件的时候，默认都是英文，Antd通过配置就能显示中文了，我也想PRO的独立组件通过配置就能显示中文，但是我在独立组件的node安装目录下并没有发现语言的配置文件

**Comment by chenshuai2144** [comment]
pro 的组件可以配置为中文，大部分文字都有相应的属性配置的。
