### ISSUE TITLE
如何添加IDE对src目录别名的支持？

### ISSUE THREAD

**Issue by Ding-Jun** [ant-design/ant-design-pro#2679]
> alias: umi 中默认会添加 @/ 的别名到 src 目录。

V2后使用别名，IDE无法进行代码提示.。
IDE为Intellij IDEA，需要进行怎样配置？

**期望结果**：
`import { queryRule, removeRule, addRule, updateRule } from '@/services/api';`
当我在大括号内输入`add`提示`addRule`

**Comment by chenshuai2144** [comment]
Intellij 也有相关配置的
