### ISSUE TITLE
主题配置插件，下滑时隐藏头部

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#2680]
按我的理解应该时下滑时隐藏，现在是下滑触底了才隐藏。
![1540535164494](https://user-images.githubusercontent.com/11746742/47548272-1f7e6b80-d92b-11e8-9cfe-8b9532563a6a.jpg)

**Comment by chenshuai2144** [comment]
有一个阈值的

**Comment by xiaohuoni** [comment]
要完全触底才会隐藏。

**Comment by chenshuai2144** [comment]
这个页可能太低了。

**Comment by xiaohuoni** [comment]
<img width="1418" alt="wx20181026-143034 2x" src="https://user-images.githubusercontent.com/11746742/47548459-b9deaf00-d92b-11e8-896b-39ed3b0ae0ba.png">

**Comment by xiaohuoni** [comment]
差一点点都不会隐藏

**Comment by xiaohuoni** [comment]
理解了，阈值是按页面长度算的。
有另外一个疑问，隐藏头部是为了不遮挡当前屏幕吧，那应该与当前屏幕显示内容相关，而不是与整个页面流长度相关吧？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/47548695-5a34d380-d92c-11e8-8817-d1a504e3e244.png)


你可以看这个代码

**Comment by xiaohuoni** [comment]
在比较长的页面，勾选下滑时隐藏头部，多切换几个页面，在比较短的页面里面触底也不会触发隐藏。
比如在高级详情页开启，切换几个页面。到监控页面，不会触发隐藏。
在监控页面开启，触底可以触发隐藏

**Comment by chenshuai2144** [comment]
看来这个代码有什么 bug，排查一下？
