### ISSUE TITLE
打包编译后，文件超级大，如何破解

### ISSUE THREAD

**Issue by taoqianbao** [ant-design/ant-design-pro#2689]
![image](https://user-images.githubusercontent.com/2980733/47631004-ea6a5700-db7e-11e8-8559-013897c8ed73.png)

**Comment by xiaohuoni** [comment]
是多大？

**Comment by taoqianbao** [comment]
路由文件，有1.39MB，APP文件有2MB，目前只能尽可能的用 CDN，+GZIP压缩；但是单个文件，还是大； 也要有100KB（GZIP后）

**Comment by xiaohuoni** [comment]
总的项目文件是多大？

**Comment by chenshuai2144** [comment]
这个大小并不算大
