### ISSUE TITLE
NoticeIcon添加点击关闭属性

### ISSUE THREAD

**Issue by wingsico** [ant-design/ant-design-pro#2690]
现在的情况：

除了点击NoticeIcon组件的Icon和其他空白处会关闭NoticeIcon的下拉列表，点击其他均不会关闭NoticeIcon的下拉列表。

需求：

点击列表项之后可以关闭当前下拉列表，点击清除通知也可以关闭。

**Comment by afc163** [comment]
赞，来个 PR~

**Comment by wingsico** [comment]
@afc163 #2716
