### ISSUE TITLE
打包后css样式覆盖问题

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design-pro#2691]
这两天将项目升级到了2.0，用了umi来打包，发现打包后css的样式有点问题，截图如下

*这是本地dev运行时的css*
![screen shot 2018-10-29 at 15 38 16](https://user-images.githubusercontent.com/8097548/47635856-5bb30580-db91-11e8-8742-53e405238eb7.png)

*这是打包后在服务器运行时的css*
![screen shot 2018-10-29 at 16 08 03](https://user-images.githubusercontent.com/8097548/47636878-da5d7200-db94-11e8-8d2f-054503f8b6aa.png)

*这是写的`less`文件*
![screen shot 2018-10-29 at 15 38 24](https://user-images.githubusercontent.com/8097548/47635988-cebc7c00-db91-11e8-843b-f5a3bc6bef0c.png)

可以发现vendor css中`background-image`的图片做了base64的转码，但是在`<style>`中又重新去找asset中的图片，然而本地跑的时候没有这个问题

还发现好像除了`width`, `height`, `float`这种没有以外，`background`, `color`等都会在打包后出现重复样式的问题，我的umi config文件和pro的是一样的

**Comment by chenshuai2144** [comment]
关闭掉 plugin.config.js 里面的东西就好了

**Comment by zhilianbi520** [comment]
@chenshuai2144  关掉plugin.config.js 中的哪个配置啊？

**Comment by GGwujun** [comment]
@zhilianbi520 你这个问题解决了嘛？

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/blob/d9793524b7a1061cb4eb5887b12633716d796570/config/config.js#L113 注释

**Comment by GGwujun** [comment]
@xiaohuoni 😂，是的，后面还是把这个注释了
