### ISSUE TITLE
关于前后端分离

### ISSUE THREAD

**Issue by lanlan1128** [ant-design/ant-design-pro#2693]
你好：
请问ant pro提供的前后端分离的思想跟用nodejs做中间件实现的思想之间的关联和区别是怎样的。
nodejs前后端分离实践参考：https://www.kancloud.cn/kancloud/midway/48195

**Comment by chenshuai2144** [comment]
pro 作为一个纯前端，是没有思想的。
很多处理都是标准的前后端分离实践。
