### ISSUE TITLE
Antd Design Pro2 中如何动态获取路由替换掉config/route.config.js

### ISSUE THREAD

**Issue by joeyFuck** [ant-design/ant-design-pro#2699]
文档中就一句话，把menudata变成state。有这么容易吗？比如 / 的重定向，这个设置还会有用吗？

**Comment by joeyFuck** [comment]
现在只能通过在route.config.js中添加所有的路由，然后菜单的数据通过请求获取过滤后的routeData.总觉得别扭，而且菜单项的高亮还没了。

**Comment by chenshuai2144** [comment]
为什么菜单高量会消失？
路由总是要配置的，不然你无法知道该加载哪些 js；
