### ISSUE TITLE
0.3.0版本  dashboard 分析页，销售额柱状图最小化页面后无法显示

### ISSUE THREAD

**Issue by zjp2007** [ant-design/ant-design-pro#270]
如图所示
![image](https://user-images.githubusercontent.com/20635787/33121287-3c31e8e6-cfaf-11e7-9aa9-259fcc4c24e0.png)

**Comment by afc163** [comment]
> 最小化页面后

这个指的是？

**Comment by zjp2007** [comment]
![image](https://user-images.githubusercontent.com/20635787/33121531-009e8784-cfb0-11e7-85e8-d03e5a1bc98b.png)

**Comment by ityao** [comment]
测了可以出现啊

**Comment by zjp2007** [comment]
![image](https://user-images.githubusercontent.com/20635787/33121765-addc43b4-cfb0-11e7-8744-6564b58bde23.png)
bar不出现后切换tab有个报错

**Comment by zjp2007** [comment]
这问题并不仅限于柱状图
![image](https://user-images.githubusercontent.com/20635787/33155748-11a93208-d02e-11e7-9572-cd76504b2c0f.png)

**Comment by afc163** [comment]
Mac 下没有问题，需要找台 windows 试一下。

**Comment by nikogu** [comment]
@zjp2007 看下有没有报错信息，麻烦提供系统，浏览器的相关信息

**Comment by ddcat1115** [comment]
@zjp2007

**Comment by chenshuai2144** [comment]
window没有问题...

**Comment by chenshuai2144** [comment]
无法再现
