### ISSUE TITLE
“销售额类别占比”标题与“全部渠道|线上|门店”有部分重叠

### ISSUE THREAD

**Issue by mygodwzy** [ant-design/ant-design-pro#2702]
在【Dashboard->分析页】中的【销售额类别占比】统计图块中，“销售额类别占比”标题与“全部渠道|线上|门店”有部分重叠，在【官方演示站https://preview.pro.ant.design/dashboard/analysis 】上也存在同一问题，请问有什么修改建议/策略吗？
![- ant design pro - google chrome 10_30_2018 10_11_19](https://user-images.githubusercontent.com/2985939/47691336-a33a9f80-dc2c-11e8-8b26-db120839789e.png)

**Comment by mygodwzy** [comment]
#2701

**Comment by chenshuai2144** [comment]
已修复了，antd的样式调整了
