### ISSUE TITLE
waterwave插件有时候变成方形

### ISSUE THREAD

**Issue by Captain-G** [ant-design/ant-design-pro#2707]
![image](https://user-images.githubusercontent.com/29189543/47705159-af405480-dc60-11e8-90ec-405d422865e0.png)

实际应用中是定时刷新，刷新之后有一定几率变方，请问是什么原因？

**Comment by chenshuai2144** [comment]
源码是一个简单的算法，你可以看一下

**Comment by annilq** [comment]
> ![image](https://user-images.githubusercontent.com/29189543/47705159-af405480-dc60-11e8-90ec-405d422865e0.png)
> 
> 实际应用中是定时刷新，刷新之后有一定几率变方，请问是什么原因？

这个问题有解决方案吗？

**Comment by CooCleC** [comment]
> 这个问题有解决方案吗？

这个当时应该是在update生命周期中加了什么逻辑，然后重新画了一遍，现在这个组件不知道修复没，没有的话就翻一下源码看看更新逻辑就行
