### ISSUE TITLE
关于使用 spring boot部署的问题

### ISSUE THREAD

**Issue by MrHeer** [ant-design/ant-design-pro#2709]
我按照要求构建了项目，然后将编译后的文件放到`/src/main/resources/static`目录下，我启动spring-boot后显示为空白（spring-boot还没有实现获取数据的接口），浏览器Console信息如下：
```
umi.js:1 TypeError: n.load is not a function
    at new r (umi.js:1)
    at Zo (umi.js:1)
    at Ma (umi.js:1)
    at Oa (umi.js:1)
    at ai (umi.js:1)
    at ii (umi.js:1)
    at Bi (umi.js:1)
    at Yi (umi.js:1)
    at Ii (umi.js:1)
    at fi (umi.js:1)
Pa @ umi.js:1
Ia.n.callback @ umi.js:1
Lo @ umi.js:1
Ho @ umi.js:1
Ki @ umi.js:1
Bi @ umi.js:1
Yi @ umi.js:1
Ii @ umi.js:1
fi @ umi.js:1
$i @ umi.js:1
ec @ umi.js:1
ac.render @ umi.js:1
(anonymous) @ umi.js:1
Qi @ umi.js:1
lc @ umi.js:1
render @ umi.js:1
i @ umi.js:1
(anonymous) @ umi.js:1
(anonymous) @ umi.js:1
Promise.then (async)
KyW6 @ umi.js:1
i @ umi.js:1
1 @ umi.js:1
i @ umi.js:1
+0iv @ umi.js:1
(anonymous) @ umi.js:1
```

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88

**Comment by MrHeer** [comment]
@afc163 我看了这个文档，但是还是不清楚。我能够访问index.html，但是里面什么都没有，是一个空的

**Comment by MrHeer** [comment]
我使用原始的项目构建后，放到spring-boot中好像没有问题。我就改了一些文件，而且通过npm start调试的时候都是正常的，太奇怪了

**Comment by MrHeer** [comment]
`为了方便做整合，最好使用 hash 路由`，能不能详细解释下？

**Comment by MrHeer** [comment]
我已经参考文档解决了。但是里面很多问题还是不清楚

**Comment by linyongfu2013** [comment]
你好，你是怎么整合的，我按文档操作，报404无法访问

**Comment by xiaohuoni** [comment]
@MrHeer 不使用hash的时候，服务端配置路由 fallback 到 index.html
可以看看是不是https://github.com/umijs/umi/issues/246#issuecomment-375218765

**Comment by MrHeer** [comment]
@xiaohuoni 我两种都用过，感觉hash要方便一些，我现在也是用的hash路由

**Comment by xiaohuoni** [comment]
没注意看时间，应该要@linyongfu2013 这个兄dei

**Comment by duzhi** [comment]
spring boot 空白原因：
```
@RequestMapping(value="/**", method=HTTPMethod.GET)
这个把js，css也匹配到了，导致 js,css 资源的请求实际返回的是 index.html
```

解决方法一：index.html增加前缀路径；
- @RequestMapping(value="/**", method=HTTPMethod.GET)
+ @RequestMapping(value="/spa/**", method=HTTPMethod.GET)
public String index(){
    // 注意 index.html 页面要放到 templates 目录，使用 thymeleaf 模板（不用改动 index.html）
    return "spa/index";
}

解决方法二：index.html 页面匹配指定正则表达式；
- @RequestMapping(value="/**", method=HTTPMethod.GET)
// 匹配“英文字母数字_-”，这样 .js,.css 会访问静态资源目录。"/" 没有匹配，会默认去 index.html
+ @RequestMapping(value="/**/{regex2:[a-zA-Z0-9_-]+}", method=HTTPMethod.GET)
public String index(){
    // 注意 index.html 页面要放到 templates 目录，使用 thymeleaf 模板（不用改动 index.html）
    return "index";
}
