### ISSUE TITLE
请问pro2.0是如何搭建eslint的

### ISSUE THREAD

**Issue by curry-wxj** [ant-design/ant-design-pro#2711]
umi2.0版本 是不支持eslint的。  pro2.0中就只看到了.eslintrc.js文件 和这些依赖。 
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-compat": "^2.6.2",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.11.1",
请问是如何实现的， 是在哪里配置的eslint-loade  读取的 .eslintrc.js

**Comment by curry-wxj** [comment]
请问如何 配置 当eslint校验不通过时 npm start提示报错， 不让正常编译

**Comment by yutingzhao1991** [comment]
umi 1.0 是有这样的功能的，2.0 没了。 这个有需求可以提到 umi 。
