### ISSUE TITLE
pro 2.0项目在Linus上打包成功，却访问报错,在windows项目打包dist后放到Linux服务器可以正常访问

### ISSUE THREAD

**Issue by lusonghe0313** [ant-design/ant-design-pro#2718]
this reation model was not fond：  ../Exception/TriggerException in ./src/.umi/router.js

13 verbose stack Error: ys-ui@2.0.0 build: `cross-env ESLINT=none NODE_ENV=production umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/data/soft/node/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/data/soft/node/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

怎么解决？

**Comment by yutingzhao1991** [comment]
感觉可能是大小写的原因，检查下 TriggerException 这个文件。

**Comment by lusonghe0313** [comment]
感谢，确实是大小写的问题，现在Pro项目在windows项目打包dist后放到linux服务器可以正常访问，但是直接在Linus上打包成功，却访问不了，这是什么情况？报错如下:
umi.2661487d.js:1 Error: Reducer "index" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined. If you don't want to set a value for this reducer, you can use null instead of undefined.
@yutingzhao1991
