### ISSUE TITLE
Table 中的 sorter 每次触发返回值相同 即排序方式无变化

### ISSUE THREAD

**Issue by DezineLeo** [ant-design/ant-design-pro#2719]
如题，看到 #2120 中有人提出类似问题，但没找到解决方案。 

补充说明 ----

![issue](https://user-images.githubusercontent.com/24782674/47989109-017cec00-e11f-11e8-8773-f3e71ed83629.jpeg)

目的实现远程获取排序数据，通过 model 更新数据，但 sorter 返回值不变。尝试去掉远程获取部分，空运行后 sorter 返回值更新。

Debug 之后，发现红圈标注的两个对象始终不相等，猜测 column 的引用对象在 Table 重新渲染后改变了，空运行下等式成立。 

看了下项目的 antd 是3.9.2，更新到最新版本看到这个问题已经被修复了，但是我运行项目后，在 debugger 中看到没有更新引用，清了波 npm 的缓存，无效，删除 node_modules 之后重新安装后总算搞定。但不明原理，大佬关闭 issue 的同时能否解释下更新 npm 包后在开发环境中没更新的问题吗？ @sorrycc

**Comment by fabripeco** [comment]
Yes it was fixed in ant d v3.10.4 ant-design/ant-design#12870

**Comment by afc163** [comment]
开发环境里可能有 package-lock.json 导致安装版本始终是老的。
