### ISSUE TITLE
更换页面右上角头像

### ISSUE THREAD

**Issue by windzxa** [ant-design/ant-design-pro#272]
在BasicLayout.js里有个
Avatar size="small" className={styles.avatar} src={currentUser.avatar} 
显示页面右上角头像,
我在assets目录下新增一个user.png图片.然后这里改成
Avatar size="small" className={styles.avatar} src="../assets/user.png"
图片并没有显示出来.然后各种路径地址我都尝试了,还是无法显示.
请问这里如何使用本地图片作为头像呢?

**Comment by windzxa** [comment]
改成src={require('../assets/user.png')}解决了....

**Comment by zjhken** [comment]
也能直接在上面import pic from "../assets/user.png"
将着直接就 src={pic}
