### ISSUE TITLE
使用antd-design-pro中的TimelineChart，曲线显示溢出问题

### ISSUE THREAD

**Issue by zhdfly** [ant-design/ant-design-pro#2727]
如题，缩放窗口即恢复正常
 `<Col span={18}>
            <TimelineChart
              height={400}
              data={chartData}
              titleMap={{ y1: '客流量', y2: '支付笔数' }}
            />
          </Col>`
![image](https://user-images.githubusercontent.com/7023067/47772931-44a41d00-dd23-11e8-83e4-fe2a079621ce.png)

**Comment by zhdfly** [comment]
什么情况？

**Comment by chenshuai2144** [comment]
机器人比较傻。。。

**Comment by chenshuai2144** [comment]
你的问题是渲染太早了，你加个延迟就好了

**Comment by zhdfly** [comment]
> 你的问题是渲染太早了，你加个延迟就好了

在数据获取上添加延时吗？

**Comment by zhdfly** [comment]
> 你的问题是渲染太早了，你加个延迟就好了
已经解决了，多谢
