### ISSUE TITLE
Pro 2.0，config文件alias属性无效

### ISSUE THREAD

**Issue by zhimiQi** [ant-design/ant-design-pro#2730]
Pro 2.0版本，设置alias：
```
alias: {
    components: path.resolve(__dirname, 'src/components/'),
    mycomp: path.resolve(__dirname, 'src/mycomp'),
    utl : `${__dirname}/src/utils`,
  },
```
在CustView.js中使用
import Check from 'mycomp/Check';
启动的时候错误如下：
These dependencies were not found:
mycomp/DictBadge in ./src/pages/TaskList.js
utl/utils in ./src/pages/Project/CustView.js

我是由Pro1.x版本升级过来的，这个配置以前在webpack可以正常使用。
如果在CustView.js中改为: '@/utils/utils'可以正常编译。

**Comment by xiaohuoni** [comment]
升级直接搬过来应该可用

**Comment by llh1187** [comment]
> Pro 2.0版本，设置alias：
> 
> ```
> alias: {
>     components: path.resolve(__dirname, 'src/components/'),
>     mycomp: path.resolve(__dirname, 'src/mycomp'),
>     utl : `${__dirname}/src/utils`,
>   },
> ```
> 
> 在CustView.js中使用
> import Check from 'mycomp/Check';
> 启动的时候错误如下：
> These dependencies were not found:
> mycomp/DictBadge in ./src/pages/TaskList.js
> utl/utils in ./src/pages/Project/CustView.js
> 
> 我是由Pro1.x版本升级过来的，这个配置以前在webpack可以正常使用。
> 如果在CustView.js中改为: '@/utils/utils'可以正常编译。

您好~ 请问您解决这个问题了吗？
