### ISSUE TITLE
Pro 2.0  怎么让项目默认打开是登陆界面呢？而不是首页脚手架默认的首页。

### ISSUE THREAD

**Issue by iskyshy** [ant-design/ant-design-pro#2732]

**Comment by Slebee** [comment]
router.config.js把/对应的路由改成想要的就行

**Comment by weiqiang0225** [comment]
不知道是不是最合适的方式：
更改src/utils/authority.js中getAuthority函数返回return authority || ['admin'];为return authority，这样用户角色就是guest,就会重定向到login页面。

**Comment by iskyshy** [comment]
> 不知道是不是最合适的方式：
> 更改src/utils/authority.js中getAuthority函数返回return authority || ['admin'];为return authority，这样用户角色就是guest,就会重定向到login页面。

此方法是pro 1.0 的方法吧。2.0的找不到你说的这个
