### ISSUE TITLE
Ellipsis inside Table not working in Firefox

### ISSUE THREAD

**Issue by fgiarritiello** [ant-design/ant-design-pro#2735]
Repro steps:

1. Create table and render an Ellipsis for one of the columns
2. Make sure your screen is wide enough so that the column does not show the ellipsis
3. Resize down the screen to shrink the table columns
Observe:
Chrome: Everything works as expected
FireFox: The Ellipsis doesn't show up when resizing. Notice: If you resize down the screen and then refresh the browser the Ellipsis shows up

Link:
https://codesandbox.io/s/5z5kplz5nl

**Comment by zhaocz2015** [comment]
come here and look look 
![image](https://user-images.githubusercontent.com/10446523/47830309-51c61800-ddc6-11e8-908f-5e7ee463d87e.png)

**Comment by zhaocz2015** [comment]
![image](https://user-images.githubusercontent.com/10446523/47830381-9e115800-ddc6-11e8-98a9-2b3f6f7b3b3f.png)

**Comment by fgiarritiello** [comment]
I can’t use the length prop because the requirement is to show the whole text if the column is wide enough.

**Comment by chenshuai2144** [comment]
Looks like the feature of Firefox.
We use css, you can start from here
