### ISSUE TITLE
能不能在特定情况下关闭cachedSave

### ISSUE THREAD

**Issue by chairy11** [ant-design/ant-design-pro#2736]
Hi, 我在使用echarts画图表，部分json数据量过大，页面会报错如下

```
×
Unhandled Rejection (QuotaExceededError): Failed to execute 'setItem' on 'Storage': Setting the value of 'c4568795ec082d6a7627e25e70ab4eb8260550eb59fe9f1e805f2f64ec8ba46c' exceeded the quota.
(anonymous function)
src/utils/request.js:52
  49 |     .clone()
  50 |     .text()
  51 |     .then(content => {
> 52 |       sessionStorage.setItem(hashcode, content);
  53 |       sessionStorage.setItem(`${hashcode}:timestamp`, Date.now());
  54 |     });
  55 | }
View compiled

```

不知道是否有一种机制，在普通request时按ant-design-pro正常的cachedSave，保存缓存。
如果设置某个参数false， 则某个request不启用cachedSave?

**Comment by chenshuai2144** [comment]
{
cached:false
}
就好了

**Comment by chairy11** [comment]
@chenshuai2144 
@afc163 
我现在的做法是改《src/utils/request.js》, 自己加了个叫needCache参数来判断

'''
const cachedSave = (response, hashcode, newOptions) => {
...
 if (newOptions.needCache && contentType && contentType.match(/application\/json/i)) {
    response
      .clone()
      .text()
      .then(content => {
        sessionStorage.setItem(hashcode, content);
        sessionStorage.setItem(`${hashcode}:timestamp`, Date.now());
      });
  }
  return response;
};


 const defaultOptions = {
    credentials: 'include',
    needCache: true,               // 是否需要缓存，默认开启。
  };

'''

在service请求时数据时
'''
export async function queryChartData() {
  return request('/data500.json', { needCache: false });
}
'''

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/b042b09754522677e816853723c7806555fe88f0/src/utils/request.js#L68

默认关闭的。

**Comment by sunkaigoon** [comment]
@afc163 
https://github.com/ant-design/ant-design-pro/blob/b042b09754522677e816853723c7806555fe88f0/src/utils/request.js#L106
我看expirys只是控制是否从缓存中取数据，并没有控制是否进行缓存操作。
https://github.com/ant-design/ant-design-pro/blob/b042b09754522677e816853723c7806555fe88f0/src/utils/request.js#L52
有时候因为数据超长会缓存失败。
