### ISSUE TITLE
路由配置可以根据不同的权限redirect到不同地址吗？

### ISSUE THREAD

**Issue by Zhaojing0987** [ant-design/ant-design-pro#2739]

**Comment by chenshuai2144** [comment]
可以的。我们现在只搞了 admin 和 guest

**Comment by Zhaojing0987** [comment]
@chenshuai2144 是在router.config里吗，比如我的一级菜单是/user，当点击这个菜单的时候，如果权限是admin，就redirect到/user/admin页面，如果权限是guest，就redirect到/user/guest这个页面，这是两个单独的页面，可以的话是怎么实现的？pro里面有案例吗？

**Comment by Zhou-Bill** [comment]
这要怎么做？

**Comment by yutingzhao1991** [comment]
https://umijs.org/zh/api/#umi-redirect
