### ISSUE TITLE
开发环境 Analysis页面渲染过慢

### ISSUE THREAD

**Issue by rudyzou** [ant-design/ant-design-pro#2740]
开发环境 Analysis页面渲染过慢
场景前提：
修改过Layout
 修改过Header
修改过 RightContent
页面表现：
点开消息面板是要6秒左右的时间
大量输出一下日志，导致页面渲染过慢，不知是否正常
![image](https://user-images.githubusercontent.com/4281891/47841826-d8deb480-ddf5-11e8-81cd-20658cbe9e41.png)

**Comment by chenshuai2144** [comment]
现在的办法是减少一点图表，这个都是异步任务超市的问题。不过6s 还是太夸张了
