### ISSUE TITLE
上线后请求后台接口报500错

### ISSUE THREAD

**Issue by xiouluo** [ant-design/ant-design-pro#2746]
按文档配置nginx
location /admin { proxy_pass ss http://api.*****.cn/admin; 
pro proxy_set_header X-Forwarded-Proto $scheme; 
proxy_set_header Host $http_host; 
proxy_set_header X-Real-IP $remote_addr; 
}
是不是这样？

**Comment by chenshuai2144** [comment]
500错误一般是服务器错误，配置nginx错误一般是504
