### ISSUE TITLE
下载最新版本在config/config.js中配置proxy失效

### ISSUE THREAD

**Issue by lqxion** [ant-design/ant-design-pro#2748]
按照umijs/配置文档说明 配置proxy
![image](https://user-images.githubusercontent.com/10972638/47892221-8357e580-de91-11e8-8b35-972032de5f69.png)
；在项目目录下输入yarn start 重启
发现访问接口地址并没有代理成功如一下实例
访问登录接口
api/login/account->希望访问代理的接口结果还是访问 localhost:8001

**Comment by shaopeng1** [comment]
代理不会修改url

**Comment by rellyCheng** [comment]
楼主解决了吗?我也遇到这样的问题了,求解答

**Comment by shaopeng1** [comment]
以后台有没有接受到请求为准，而不是以url有没有修改为你需要的url为准 @rellyCheng

**Comment by zerlous** [comment]
yarn start:no-mock

**Comment by LBC100** [comment]
![Snip20190402_14](https://user-images.githubusercontent.com/38514123/55411180-c1b81480-5597-11e9-89fa-ff9bc16650d1.png)
nginx.conf
