### ISSUE TITLE
共享model报错是怎么回事？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#2749]
我有一个获取字典列表的方法，因为在原来一个模块写过，所以在现在这个模块直接使用了。
在同一个模块中引用了多个model，model1是该页面自己的model，代码如下：
```
@connect(({ model1,model2 loading }) => ({
  model1,
model2,
  loading: loading.models.model1
}))
exprot default class UserInfo extends PureComponent{
componentDidMount() {
this.props.dispatch({
     type:'model2/getNames'
});
}
render(){
const {models:{names:[]}}=this.props;
return ....
}
}

```
在本地联调没问题。打包后放到测试环境和正式环境，model2的names都识别不了。看状况是model2没加载成功。

错误如下：
```
umi.js:1 TypeError: Cannot read property 'names' of undefined

14.async.js:1 Uncaught (in promise) TypeError: Cannot read property 'names' of undefined

```

**Comment by yutingzhao1991** [comment]
开了按需加载？共享的 model 应该放到最外层的 models 文件夹。

**Comment by codepandy** [comment]
在哪配置按需加载？

**Comment by yutingzhao1991** [comment]
https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

**Comment by codepandy** [comment]
我觉的这是这个框架的bug吧，多个model加载有问题。

**Comment by yutingzhao1991** [comment]
不算是 bug 吧，你要多个页面直接共用的 model 就是要保证在全局 model 文件夹里面。

**Comment by chenshuai2144** [comment]
this is a feature.

**Comment by sunslj** [comment]
请问各位大神，全局中的model，在A页面获取的数据，在B页面无法获取是什么情况？

**Comment by yeluoqiuzhi** [comment]
我也有这样的问题，因为不能共用，所以我放到了两个model的共同父级，成功加载了，但是componentDidmount后马上dispatch没效果。。。setTimeout就有效果了，也没查到原因。因为这个model仅仅是列表界面和详情编辑界面共用一下，其它地方根本不用的，所以不想放到全局model，求指教

**Comment by xiashei** [comment]
> 我也有这样的问题，因为不能共用，所以我放到了两个model的共同父级，成功加载了，但是componentDidmount后马上dispatch没效果。。。setTimeout就有效果了，也没查到原因。因为这个model仅仅是列表界面和详情编辑界面共用一下，其它地方根本不用的，所以不想放到全局model，求指教

在另一个地方看到过解释，官方设计就是这样。dev环境没问题是为了便于开发，build以后不行。只能放在全局model
