### ISSUE TITLE
请问表格filter图标旁的点从何而来，如何去除？

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#2750]
如图，请热心网友帮忙看看，谢谢！
![result](https://user-images.githubusercontent.com/40480550/47893127-5c4fe280-de96-11e8-84c8-c502cf221322.png)
![code](https://user-images.githubusercontent.com/40480550/47893130-5e19a600-de96-11e8-86a7-7502abc111ae.png)

**Comment by chenshuai2144** [comment]
估计是低级错误

**Comment by linzelong95** [comment]
@chenshuai2144 
感谢你的回复。
这也许是个低级错误，但仔细查找原因，仍然不知问题所在。
当我注释掉filterDropdown和filterIcon两个属性，图标旁边的点随之消失，于是我推测是在这两个属性的书写过程中出错。
可当我把这两行代码复制到其他表格的其他colum，显示结果没有任何问题，这又说明书写这两个属性时，代码并没有写错，这与上面的推测相悖。
最后，我选择将其他表现正常的columns复制过来，只更改title、dataIndex以及key，但这个“点”又出现。
我，百思不得其解。
