### ISSUE TITLE
NoticeIcon.Tab 是否可以支持标签页文字自定义消息总条数？？？

### ISSUE THREAD

**Issue by ningzhenyi** [ant-design/ant-design-pro#2751]
如图：
![image](https://user-images.githubusercontent.com/26025135/47894568-8c02e880-de9e-11e8-8e44-59b3be636189.png)

在实际使用中 NoticeIcon.Tab.list 的数据一般是最新的5条，所以导致文字提示一直都是5，但是实际的条数可能会是很多

**Comment by ningzhenyi** [comment]
![image](https://user-images.githubusercontent.com/26025135/47894688-1b100080-de9f-11e8-9803-23c90e773c8a.png)

**Comment by chenshuai2144** [comment]
不支持的，你有兴趣提个pr吗？

**Comment by jakubknejzlik** [comment]
This seems to be already implemented: https://github.com/ant-design/ant-design-pro/pull/2862 ... also please keep the conversation in english 🙏 :)

**Comment by chenshuai2144** [comment]
fix in #2862
