### ISSUE TITLE
[2.0] How do you import relative less files?

### ISSUE THREAD

**Issue by jwmann** [ant-design/ant-design-pro#2755]
### Versions:
```
    "umi": "^2.0.1",
    "umi-plugin-react": "^1.0.1"
```

I've looked at #2346 and #2432 and #2306 and it still doesn't work.

### I'm importing from:
`app/src/components/Foo/Bar/index.less`

### I'm trying to import:
`app/src/variables.less`

### I've tried:
`@import '../../../variables.less';`
`@import '/variables.less';`
`@import '/src/variables.less';`
`@import '~/variables.less';`
`@import '~variables.less';`
`@import '~@/variables.less';`
`@import '~@variables.less';`

I also tried to change the `varFile` in [https://github.com/ant-design/ant-design-pro/blob/master/config/plugin.config.js](https://github.com/ant-design/ant-design-pro/blob/master/config/plugin.config.js) to the `../src/variables.less` and that didn't work either.

Nothing works.
How do I fix this?

**Comment by chenshuai2144** [comment]
sorry,this is my error.
you can remove plugin.config.js

**Comment by chenshuai2144** [comment]
and need remove  ` chainWebpack: webpackPlugin,`

**Comment by codesignist** [comment]
Then why do we use `plugin.config.js` file. Let's remove it permanently.

**Comment by logmannn** [comment]
`@import '~@/`
Ended up working for me

**Comment by Newbit13** [comment]
> sorry,this is my error.
> you can remove plugin.config.js

work
