### ISSUE TITLE
生产环境Analysis页面报错

### ISSUE THREAD

**Issue by misome** [ant-design/ant-design-pro#2759]
从github拉最新的master分支代码未作任何改动，使用node V10.13.0 npm V6.4.1 编译，在生产环境部署后访问报错。
![antderror](https://user-images.githubusercontent.com/18189766/47959809-365a4780-e028-11e8-963e-365f21c7f942.png)

请问是什么原因？

**Comment by misome** [comment]
Uncaught TypeError: Cannot read property 'Graph' of undefined

Uncaught (in promise) ReferenceError: DataSet is not defined

**Comment by chenshuai2144** [comment]
you can import DataSet .

`  <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js"></script>`

**Comment by yutingzhao1991** [comment]
最好直接用 umi 构建出来的 HTML，不然可能有的内容会丢失。

**Comment by wsdqr001** [comment]
如果不用CDN，dataset.min.js要如何导入才能兼容开发环境和生产环境呢？ 谢谢。@chenshuai2144
