### ISSUE TITLE
生产环境访问Analysis页面报错

### ISSUE THREAD

**Issue by misome** [ant-design/ant-design-pro#2760]
从github拉最新的master分支代码，只修改过config/config.js增加了base,publicPath,history，其余代码未作任何改动，使用node V10.13.0 npm V6.4.1 编译，将dist目录下的所有文件拷贝到生产环境部署后访问报错。
![antderror](https://user-images.githubusercontent.com/18189766/47960037-44ab6200-e02e-11e8-9a58-51ea8b448fb6.png)
经验证data-set.min.js已引用且客户端能正常访问，umi.js也能正常访问。
![antderror1](https://user-images.githubusercontent.com/18189766/47960045-7c1a0e80-e02e-11e8-99ef-84a5a0a2c641.png)
看起来像是data-set.min.js中某个对象为undefined，导致无法访问其Graph属性，umi.js中的Dataset未定义，不知道该如何解决？

**Comment by misome** [comment]
![antderror2](https://user-images.githubusercontent.com/18189766/47960075-3e69b580-e02f-11e8-8210-3e09e44c4983.png)
![antderror3](https://user-images.githubusercontent.com/18189766/47960076-40337900-e02f-11e8-9187-87f020de3b04.png)

**Comment by chenshuai2144** [comment]
这个就是 DataSet 没找到呀。
你直接在控制台访问一下

**Comment by qianduanMortal** [comment]
问题是data-set库里面的报错。  这就完全无法解决了。
