### ISSUE TITLE
How can i add custom font?

### ISSUE THREAD

**Issue by mrkhedri** [ant-design/ant-design-pro#2761]
I need to add my custom font to the project.
I tried some ways like add my font files in `src` directory. This way worked very well in development mod, But when i want create build, I get the following error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'assets/fonts/my-font.woff2' in '.......\src'
```
antd-pro v2
umi v2

**Comment by chenshuai2144** [comment]
you can insert in[ document.ejs](https://github.com/ant-design/ant-design-pro/blob/master/src/pages/document.ejs)

**Comment by kovalevroman** [comment]
@chenshuai2144  What you need to write to the document.ejs?
