### ISSUE TITLE
登录、注册等相关页面的URL地址显示不对

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#2763]
登录界面显示为 https://preview.pro.ant.design/User/Login  
注册界面显示为 https://preview.pro.ant.design/User/Register

应该后面是小写的才对。

**Comment by chenshuai2144** [comment]
在哪看到的？

**Comment by chenshuai2144** [comment]
看到了 @xiaohuoni  顺便给大写了。
