### ISSUE TITLE
菜单折叠时,渲染出错

### ISSUE THREAD

**Issue by zhichao8756** [ant-design/ant-design-pro#2764]
![image](https://user-images.githubusercontent.com/24514251/47975383-8dbfec80-e0e8-11e8-990f-94057be67538.png)

**Comment by yutingzhao1991** [comment]
我这里访问 https://preview.pro.ant.design/dashboard/analysis 是好的，你的那是什么环境？

**Comment by zhichao8756** [comment]
这个是我刚刚clone下来的,在本地运行

**Comment by xiaopanghhh** [comment]
MacOs Chrome 版本 70.0.3538.77（正式版本） （64 位）

**Comment by zhichao8756** [comment]
MacOs Chrome 版本 70.0.3538.77（正式版本） （64 位）

**Comment by afc163** [comment]
Duplicate of #2783
