### ISSUE TITLE
异步请求问题

### ISSUE THREAD

**Issue by StriveTeam** [ant-design/ant-design-pro#2767]
脚手架中，异步请求，如果返回值中又包裹了一层，即，response.json()读取的的值为{code:200,data:[],message:'sdasdada'}，根据cede来判断请求或返回是否正确，在哪里做判断？
在做了删除或者修改的时候，需要调用列表接口来获取最新列表，在哪里添加回调，在effects里吗？

**Comment by chenshuai2144** [comment]
response.json().then(()=>Promise);

在 modal 里面会比较好
