### ISSUE TITLE
上线后报错

### ISSUE THREAD

**Issue by xiouluo** [ant-design/ant-design-pro#2768]
服务器配置
server {
    listen 80;
    server_name me backhome.****.cn;
  ;
    root /var/www/worldparking-backhome/dist;
    index ex index.html;
  ;
    location /admin {
        proxy_pass ss http://****.cn;
   
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location / {
        # 用于配合 browserHistory使用
        try_files $uri $uri/ // /index.html;
  ;
    }
}

前端代理
proxy: {
    '/admin': {
      target: 'http://*****.cn/admin',
      changeOrigin: true,
      pathRewrite: { '^/admin': '' },
    },
  },

**Comment by xiouluo** [comment]
500报错

**Comment by xiouluo** [comment]
日志
<img width="1280" alt="_20181105155635" src="https://user-images.githubusercontent.com/44430926/47988401-1193cc00-e11d-11e8-88ab-f56e873d1e87.png">

**Comment by chenshuai2144** [comment]
500报错 一般是服务器错误，先定位一下服务器是不是有什么特别配置 比如 host refer
