### ISSUE TITLE
git commit 无法提交

### ISSUE THREAD

**Issue by archerU** [ant-design/ant-design-pro#2769]
<img width="465" alt="2018-11-05 1 47 31" src="https://user-images.githubusercontent.com/13237958/47980198-69bcd500-e101-11e8-80dc-174708205dfa.png">
直接clone master 的库，执行了，
```
npm i 
npm start
git add .
git commit 的时候就报错了
```

**Comment by chenshuai2144** [comment]
看起来像是 node 的问题。

**Comment by slashvortal** [comment]
I'm having the same error after a new clone! @archerU did you find the cause?
