### ISSUE TITLE
Uncaught (in promise) ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by xyunsh** [ant-design/ant-design-pro#277]
在utlis中增加一个index.js文件，导出utils中的所有函数：
export * from './utils';

引用dashboard/Analysis.js中引用
import { getTimeDistance } from '../../utils/index';

会报错
`Uncaught (in promise) ReferenceError: exports is not defined
    at eval (webpack-internal:///1355:10)
    at Object.<anonymous> (0.async.js:2875)
    at __webpack_require__ (index.js:708)
    at fn (index.js:113)
    at eval (webpack-internal:///655:116)
    at Object.<anonymous> (0.async.js:6)
    at __webpack_require__ (index.js:708)
    at fn (index.js:113)
    at <anonymous>
:8000/#/dashboard/analysis:1 `

**Comment by afc163** [comment]
https://github.com/59naga/babel-plugin-add-module-exports/issues/40

**Comment by afc163** [comment]
@sorrycc

**Comment by nikogu** [comment]
@xyunsh 贴一下你 `index.js` 的代码

**Comment by yesmeck** [comment]
我觉得作为新项目不应该再用 `babel-plugin-add-module-exports` 了，新项目应该跟着标准走。

**Comment by xyunsh** [comment]
@nikogu 就一句话

`export * from './utils';
`

**Comment by afc163** [comment]
那 roadhog 需要给一个 add-module-exports 的配置开关。

**Comment by yesmeck** [comment]
roadhog 2 已经去掉 babel-plugin-add-module-export

**Comment by sorrycc** [comment]
babel@7 好像不支持这个插件的。
