### ISSUE TITLE
我在page的目录下面建立的models文件夹，redux中并没有这个状态，需要配置什么嘛？

### ISSUE THREAD

**Issue by jinrichardJIN** [ant-design/ant-design-pro#2771]
我在page的目录下面建立的models文件夹，redux中并没有这个状态，需要配置什么嘛？或者说在src/model下面和在page目录下面的区别是什么？在redux插件中，并没有看到page下面的那些state

**Comment by chenshuai2144** [comment]
page 下面的是按需加载，
model 下面是全局的
