### ISSUE TITLE
关于离线开发环境下Dataset引用

### ISSUE THREAD

**Issue by 15502573620** [ant-design/ant-design-pro#2773]
如题，现在的dataset是通过外部引用的，如果在我想把依赖包下到本地在离线情况下可以使用应该怎么做呢？

`<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js">`

**Comment by chenshuai2144** [comment]
直接放到public 目录

**Comment by ZJane** [comment]
thanks

**Comment by qianduanMortal** [comment]
没能成功，  库本身报错。

**Comment by BEWINDOWEB** [comment]
> 直接放到public 目录
> 
> <script src="/data-set.min.js">
也猜到是这个文件，搞了好久，放到各种目录都不行，终于放到public改成/的路径就可以了。
感谢。
