### ISSUE TITLE
线上404等页面展示问题

### ISSUE THREAD

**Issue by qq490507385** [ant-design/ant-design-pro#2774]
看文档的时候有这么一句话   “为了方便展示 404 等页面，我们在 request.js 中封装了根据状态跳转到相应页面的逻辑,建议在线上环境中删除这个逻辑”

为什么线上建议删除这个逻辑，这个逻辑删除的话 404 等页面如何展示

**Comment by chenshuai2144** [comment]
我们现在 fetch 404 就会跳转404 ，html 的404 不是这样使用的。
路由中没有的再使用404
