### ISSUE TITLE
官方demo预览页面，查询表格page，时间控件有值时，查询报错

### ISSUE THREAD

**Issue by joeyFuck** [ant-design/ant-design-pro#2777]
自己使用时，时间控件有值时，查询会带上一堆data（看下图）。

本想在官方demo预览页看下，没想导不仅还是带上一堆data，还直接报错了。

![image](https://user-images.githubusercontent.com/19240640/48045742-883bd280-e1cc-11e8-8bf8-7a50995c34b6.png)

![image](https://user-images.githubusercontent.com/19240640/48045726-7a864d00-e1cc-11e8-8e2e-39d4d95b5750.png)

**Comment by chenshuai2144** [comment]
请自行转化。默认使用 moment
