### ISSUE TITLE
为什么你们的预览界面可以在线切换主题颜色，而我把源码下下来不可以

### ISSUE THREAD

**Issue by supconlc** [ant-design/ant-design-pro#2778]
我看到你们的预览可以流畅的切换主题颜色，为什么我的不可以，这个需要联网吗

**Comment by xiaohuoni** [comment]
需要
```
https://gw.alipayobjects.com/os/lib/less.js/3.8.1/less.min.js
```

**Comment by supconlc** [comment]
> 需要
> 
> ```
> https://gw.alipayobjects.com/os/lib/less.js/3.8.1/less.min.js
> ```

这个如何引入啊，可以直接在本地新建一个文件，复制内容吗

**Comment by xiaohuoni** [comment]
应该可以放到publish，在setting的model里面要对应改一下引用路径

**Comment by supconlc** [comment]
> 应该可以放到publish，在setting的model里面要对应改一下引用路径
非常感谢~

**Comment by Warden-Thresh** [comment]
无论怎么更改setting 的model，执行build编译出的index.html中该js的src不会发生变化，如下图
![image](https://user-images.githubusercontent.com/22620409/50583666-8c6f2e00-0ea5-11e9-81a0-7d64f019d7ae.png)

**Comment by xiaohuoni** [comment]
@Warden-Thresh 在setting的model 的47行修改 https://github.com/ant-design/ant-design-pro/blob/2f51506c63d94b9a374aee49ba8b0c13dcaa0c76/src/models/setting.js#L47

**Comment by Warden-Thresh** [comment]
修改了没有用我才提问的，无论改成什么都会变成图上那个
