### ISSUE TITLE
求助!!!proxy代理不成功,期望请求发送到代理的地址

### ISSUE THREAD

**Issue by rellyCheng** [ant-design/ant-design-pro#2779]
![image](https://user-images.githubusercontent.com/22974879/48049353-63019100-e1d9-11e8-85c4-1b1a320fd42f.png)
![image](https://user-images.githubusercontent.com/22974879/48049385-77de2480-e1d9-11e8-8cbb-28a3b647460e.png)
![image](https://user-images.githubusercontent.com/22974879/48049412-8debe500-e1d9-11e8-8f36-0c3aa89c50b0.png)

**Comment by xiaohuoni** [comment]
只是服务请求代理，这个地址是不会变的。

**Comment by rellyCheng** [comment]
@xiaohuoni 谢谢你, 我懂了,被以前的开发思维给定住了

**Comment by xiaohuoni** [comment]
原理可以简单的理解为，在本地启了一个服务，你先请求了本地的服务，本地的服务转发了你的请求到实际服务器。所以你在浏览器上看到的请求地址还是http://localhost:8000/xxx

**Comment by LBC100** [comment]
不对哦

**Comment by LBC100** [comment]
![Snip20190402_14](https://user-images.githubusercontent.com/38514123/55410856-2888fe00-5597-11e9-8110-fe95d56fd45a.png)
这样才对.在nginx.conf添加

**Comment by junhui75165** [comment]
请教一下文件build之后的请求地址配置的话，是在哪里进行配置

**Comment by chenshuai2144** [comment]
@junhui75165 
https://pro.ant.design/docs/deploy-cn

**Comment by Liqiankun** [comment]
@junhui75165 这个问题最后怎么解决的？

**Comment by junhui75165** [comment]
> @junhui75165 这个问题最后怎么解决的？

需要服务端做配置，打包的不是纯静态页面

**Comment by Liqiankun** [comment]
我搞明白了#5795

**Comment by qweasd25** [comment]
这个不对吧 还不是服务器地址 没有跑通啊

**Comment by xiaohuoni** [comment]
开发的时候代理是在本地配置的，部署的时候，代理是服务端配置的。上面的小哥提到的是服务端代理的事情。和开发代理原理是一样的，但是事情需要前端来做。

**Comment by httol** [comment]
如何抓到通过代理请求的返回数据，报错后，errorHandler里看不到代理返回的错误
![image](https://user-images.githubusercontent.com/4971746/104126432-77cca700-5397-11eb-8f2d-070f19c4442c.png)
