### ISSUE TITLE
Pro 从1.x更新到2.x后手机浏览器不能正常访问了

### ISSUE THREAD

**Issue by lynxkor** [ant-design/ant-design-pro#2780]
Pro 从1.x更新到2.x后手机浏览器不能正常访问了；
尝试用手机浏览器访问官方https://preview.pro.ant.design 也是同样的页面白屏；

**Comment by xiaohuoni** [comment]
兼容性问题。可以设置target后再试试

**Comment by lynxkor** [comment]
没用，连访问官网演示站点https://preview.pro.ant.design 也是同样的页面白屏；

**Comment by chenshuai2144** [comment]
@lynxkor  可能是 intl 的问题，不过太低的浏览器我们并没有精力支持，可以使用 chrome

**Comment by afc163** [comment]
直接给我们 PR 吧。

**Comment by jingkeke** [comment]
我用的华为M5 ,Android8 自带的浏览器也白屏.........看官网说加` import '@babel/polyfill';` 也不行..........
