### ISSUE TITLE
自定义菜单图标时收起菜单导致文字不隐藏

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design-pro#2782]
*现象以下截图所示*
![image](https://user-images.githubusercontent.com/8097548/48053233-20de4c80-e1e5-11e8-809a-31d1628699bb.png)
*这是用自定义icon时的DOM结构*
![image](https://user-images.githubusercontent.com/8097548/48053245-2e93d200-e1e5-11e8-9a84-0007f2882fb6.png)
*这是用antd自带的icon时的DOM结构*
![image](https://user-images.githubusercontent.com/8097548/48053259-394e6700-e1e5-11e8-993f-b1c9338cf573.png)
*这是隐藏菜单文字的css*
![image](https://user-images.githubusercontent.com/8097548/48053272-4408fc00-e1e5-11e8-9ff1-97f6f6095f7b.png)

可以看到隐藏是通过`.anticon+span`找到的，但是用自定义icon的时候元素是`<img>`所以会找不到

**Comment by afc163** [comment]
Duplicate of #2782

**Comment by Puuuudding** [comment]
我又看了一下#2783，我觉得不是duplicate，默认在收起后会隐藏一级菜单的文字，因为icon上有`.anticon`class，而如果用自定义图片的话就没有这个class，导致一级菜单的文字不会隐藏

**Comment by sjx1995** [comment]
@Puuuudding 说的没错，可以在自定义图标外面加上一个`.anticon`的span来解决
