### ISSUE TITLE
预览页面（https://preview.pro.ant.design）左侧菜单收缩时异常

### ISSUE THREAD

**Issue by coderben2017** [ant-design/ant-design-pro#2783]
![](http://ww1.sinaimg.cn/large/005PwPq7ly1fwygd6tr95j30b30f60t5.jpg)
![](http://ww1.sinaimg.cn/large/005PwPq7ly1fwygdpp5bhj30650famxb.jpg)

**Comment by afc163** [comment]
正在排查中。

@picodoth

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/5e12b0a5ca3730d2e99d1e9160025e4ebf3620d8

antd 这里改挂了，正在找解决方案。

**Comment by jinyaqiao1102** [comment]
@afc163 这个问题何时能够修复？

**Comment by afc163** [comment]
本周五 antd 会发 patch 修复。

**Comment by jinyaqiao1102** [comment]
这个问题好像在一个多月前就存在

**Comment by Instanced** [comment]
#2806

**Comment by chenshuai2144** [comment]
fix in antd@3.10.7
