### ISSUE TITLE
不支持flow?  可以加入flow吗？start 不支持 a: number

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#2785]
function foo(x: number): number {
  return x + 10
}

Syntax Error: SyntaxError: /Users/lewin/Documents/workspace/sourcecode/enterprise-bank-web/src/pages/Merchant/Manager/Manager.js: Unexpected token, expected "," (177:14)

  175 | }
  176 |
> 177 | function foo(x: number): number {
      |               ^
  178 |   return x + 10
  179 | }
  180 |

node v11

**Comment by chenshuai2144** [comment]
typescript 才是最棒的
