### ISSUE TITLE
为什么在线切换主题颜色时别的都切换成功，但主题切换的那个设置的颜色还是默认的篮色

### ISSUE THREAD

**Issue by supconlc** [ant-design/ant-design-pro#2787]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2791

**Comment by supconlc** [comment]
什么意思？

**Comment by supconlc** [comment]
这个是什么意思？发自我的iPhone------------------ 原始邮件 ------------------发件人: 陈帅  <notifications@github.com>发送时间: 2018年11月12日 10:16收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com>抄送: supconlc <lichan618@126.com>, Author <author@noreply.github.com>主题: 回复：[ant-design/ant-design-pro] 为什么在线切换主题颜色时别的都切换成功，但主题切换的那个设置的颜色还是默认的篮色 (#2787)#2791

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ant-design/ant-design-pro","title":"ant-design/ant-design-pro","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ant-design/ant-design-pro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chenshuai2144 in #2787: https://github.com/ant-design/ant-design-pro/issues/2791"}],"action":{"name":"View Issue","url":"https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275",
"url": "https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ant-design/ant-design-pro] 为什么在线切换主题颜色时别的都切换成功，但主题切换的那个设置的颜色还是默认的篮色 (#2787)",
"sections": [
{
"text": "",
"activityTitle": "**陈帅**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@chenshuai2144",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ant-design/ant-design-pro\",\n\"issueId\": 2787,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406907839\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by supconlc** [comment]
什么意思啊，没搞懂发自我的iPhone------------------ 原始邮件 ------------------发件人: 陈帅  <notifications@github.com>发送时间: 2018年11月12日 10:16收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com>抄送: supconlc <lichan618@126.com>, Author <author@noreply.github.com>主题: 回复：[ant-design/ant-design-pro] 为什么在线切换主题颜色时别的都切换成功，但主题切换的那个设置的颜色还是默认的篮色 (#2787)#2791

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ant-design/ant-design-pro","title":"ant-design/ant-design-pro","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ant-design/ant-design-pro"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chenshuai2144 in #2787: https://github.com/ant-design/ant-design-pro/issues/2791"}],"action":{"name":"View Issue","url":"https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275",
"url": "https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ant-design/ant-design-pro] 为什么在线切换主题颜色时别的都切换成功，但主题切换的那个设置的颜色还是默认的篮色 (#2787)",
"sections": [
{
"text": "",
"activityTitle": "**陈帅**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@chenshuai2144",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ant-design/ant-design-pro\",\n\"issueId\": 2787,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ant-design/ant-design-pro/issues/2787#issuecomment-437731275"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406907839\n}"
}
],
"themeColor": "26292E"
}
]
