### ISSUE TITLE
启动控制台一大堆警告 [hardsource:5ec540cb] Could not freeze。。。

### ISSUE THREAD

**Issue by zhouzixing** [ant-design/ant-design-pro#2789]
hardsource:5ec540cb] Could not freeze ./src/components/SelectLang/index.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/SettingDrawer/BlockChecbox.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/SettingDrawer/ThemeColor.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/SettingDrawer/index.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/SiderMenu/BaseMenu.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/SiderMenu/SiderMenu.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/SiderMenu/index.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/StandardFormRow/index.js: Cannot read property 'hash' of undefined
[hardsource:5ec540cb] Could not freeze ./src/components/StandardTable/index.js: Cannot read property 'hash' of undefined

**Comment by KejieLiu** [comment]
咋忽略？

**Comment by roc2539** [comment]
@chenshuai2144 更新到2.3.5 还是一堆报错。

**Comment by roc2539** [comment]
配置文件里面把 hardsource 设置为false
