### ISSUE TITLE
nav.js中动态import组件的问题

### ISSUE THREAD

**Issue by kstar11** [ant-design/ant-design-pro#279]
由于nav.js中返回的就是一个数组,由各个对象组成,我理解为层对象
层对象中包含children既是各个页面的组件,路由和model
因为这部分值非常相似,所以打算用数据库管理起来
然而在dynamicWarpper中,import引入总是不正确
此处item是我map获取到的ajax返回值,差不多就是
 {
    "layout": "BasicLayout",
    "name": "首页",
    "path": "/",
    "component": "BasicLayout",
    "model":["user","login"],
    "children": [
      {
        "name": "Dashboard",
        "icon": "dashboard",
        "path": "dashboard",
        "children":[
            {
              "name": "分析页",
              "path": "analysis",
              "model":["chart"],
              "component": "Dashboard/Analysis"
            },
            {
              "name": "分析页",
              "path": "analysis",
              "model":["chart"],
              "component": "Dashboard/Analysis"
            }
        ]
      }
  ]
}
async () => await import('../layouts/'+item.component));
这里import似乎不能这样字符串拼变量,只有字符串可以用,有没有什么办法呢?

**Comment by benaheng** [comment]
同问

**Comment by WhatAKitty** [comment]
这样做没尝试过，不过理论上应该可以实现，
你说的：

> 这里import似乎不能这样字符串拼变量,只有字符串可以用

这样做，会抛出什么异常吗？还是没有什么反应？

**Comment by viztor** [comment]
@WhatAKitty 我猜是 webpack 没法理解 run-time 的语法。dynamic loading 的打包很可能是通过静态分析实现的。

**Comment by kstar11** [comment]
@viztor 对,正如阁下所说,dynamic打包是通过静态分析去实现,在路径中拼接任何变量参数都不能识别

**Comment by WhatAKitty** [comment]
https://github.com/webpack/webpack/issues/4993
