### ISSUE TITLE
如果服务端请求如果报401，导致页面加载问题

### ISSUE THREAD

**Issue by rudyzou** [ant-design/ant-design-pro#2793]
如果服务端请求如果报401，会redirect到登录页面，这个时候当前组件页面没完全挂载，导致重新登录后回到该页面，永远是loading中。
这个问题 #1549 有提过，但是你们没get到点。

**Comment by 0zhengjie0** [comment]
试试，SRC目录下增加app.js，由于我修改了src/config/request.js（使用了axios组件，fetch应该也一样）,返回promise对象的时候在catch里面reject
app.js代码

export const dva = {
  config: {
    onError(e) {
      e.preventDefault();
      console.error(e.message);
    },
  },
};

**Comment by yoyo837** [comment]
自己改 request.js 应该可以解决

**Comment by zhilianbi520** [comment]
> 自己改 request.js 应该可以解决

request中如何修改。。求解。
