### ISSUE TITLE
Ellipsis 组件对文本省略和未省略的情况，显示的文本高度不同。

### ISSUE THREAD

**Issue by Strikersb** [ant-design/ant-design-pro#2796]
![image](https://user-images.githubusercontent.com/14834081/48110020-dc09f280-e284-11e8-9343-213fe9046a8c.png)

本来是做的一个Card的列表，其中有一处用了Ellipsis组件，发现布局乱了。

经过查证，是Ellipsis组件，对文本省略和未省略的情况，文本高度不同。

随后设置了一下高度，然后解决了问题。

![image](https://user-images.githubusercontent.com/14834081/48110069-08257380-e285-11e8-9f85-85190f3f7e2e.png)

设置了20px高度，然后bug消失。

![image](https://user-images.githubusercontent.com/14834081/48110078-18d5e980-e285-11e8-8878-2562503901eb.png)

**Comment by chenshuai2144** [comment]
最好自己确认一下高度。css 的高度计算很迷
