### ISSUE TITLE
request请求超时时间设置

### ISSUE THREAD

**Issue by 308787520huanhuan** [ant-design/ant-design-pro#2798]
项目有一个接口因为是和第三方接口交互 耗时比较长 用的ant design pro2.0 封装的request  不同浏览器上 请求每次都在两分钟的时候挂掉  另外用ajax请求测试都是正常的 想请问请求超时时间是在哪儿设置的？

**Comment by chenshuai2144** [comment]
fetch 是不会超时的。你的问题估计是信息头的问题。

**Comment by afc163** [comment]
这种一般都是在 nginx 里配置的。

**Comment by 308787520huanhuan** [comment]
我是直接拉的ant design pro2.0脚手架 在脚手架里面改的代码 没有自己配置 nginx 也没找到任何跟2分钟有关的配置 所以想问问你们 这个问题到现在也没找到原因 捂脸(*/ω＼*)

**Comment by 308787520huanhuan** [comment]
![image](https://user-images.githubusercontent.com/3348828/57355132-e65b6980-719f-11e9-9128-9ef9e9df3e4b.png)
我想说我解决了 好坑  应该是webpack有默认的链接超时

**Comment by fivefog** [comment]
用的V5版本，同问题，参考楼上的已解决
```tsx
'/device/': {
      target: 'http://192.xxxx:xx', 
      timeout: 1800000, // 请求超时，设置30分钟
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
```
