### ISSUE TITLE
如何让每次部署后访问页面获取的是最新的代码不是缓存中的？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#2799]
使用webconfig可以配置生成文件的名字，这样每次部署后就可以读取最新的文件，而不是读取缓存中的文件。
在pro v2中该如何配置？

**Comment by longzhaobi** [comment]
如果修改了代码，编译后的文件名称都不一样了啊。

**Comment by codepandy** [comment]
@longzhaobi 能发下你生成文件的格式吗？我这都是一样的

**Comment by chenshuai2144** [comment]
打开 hash 就好了，你估计关掉了
https://umijs.org/zh/config/#hash

**Comment by codepandy** [comment]
@chenshuai2144 完美！就是这个，哈哈;
不过Pro里面默认是关闭的，没有配置这个属性。
