### ISSUE TITLE
pro初始化项目 `npm start` 运行错误

### ISSUE THREAD

**Issue by FrendEr** [ant-design/ant-design-pro#280]
本地环境：node@8.1.2 npm@5.0.3

是否有版本兼容问题呢？请说明下

```
./node_modules/antd/es/grid/row.js
Module not found: Can't resolve 'enquire.js' in 'project/node_modules/antd/es/grid'
```

**Comment by FrendEr** [comment]
发现问题所在，项目依赖 `antd`，`antd` 里面的 grid/row.js 依赖 `enquire.js`，但是在 `antd` 里面 `enquire.js` 是写在 `devDependcies` 里面的，导致外部组件执行 `npm install` 的时候不会安装 `enquire.js`

**Comment by afc163** [comment]
Fixed in antd@3.0.0-rc.4
