### ISSUE TITLE
Header breaks when user name is too large

### ISSUE THREAD

**Issue by rayronvictor** [ant-design/ant-design-pro#2800]
![captura de tela 2018-11-07 as 17 20 29](https://user-images.githubusercontent.com/1683922/48159410-da0b5800-e2b3-11e8-835a-7395e45575f7.png)

**Comment by chenshuai2144** [comment]
Username should also be too long to omit

**Comment by rayronvictor** [comment]
I solved this issue by never showing the username in the header and turning the first menu item on the link to the profile.

![captura de tela 2018-11-08 as 09 08 38](https://user-images.githubusercontent.com/1683922/48197905-ec2dda80-e335-11e8-91df-e12df08e69ca.png)

**Comment by chenshuai2144** [comment]
you can use [Ellipsis](https://pro.ant.design/components/Ellipsis/) in header

**Comment by rayronvictor** [comment]
I found also that, when using iPad in landscape with Navigation Mode option setted to Top Menu Layout the `RightContent` breaks and account settings stay inaccessible.

![captura de tela 2018-11-12 as 09 20 53](https://user-images.githubusercontent.com/1683922/48347166-3b3c7e00-e65c-11e8-85d8-4d0064912da0.png)
