### ISSUE TITLE
Custom theme is overwritten by default in production

### ISSUE THREAD

**Issue by ilanus** [ant-design/ant-design-pro#2801]
```
module.exports = {
  navTheme: 'light', // theme for nav menu
  primaryColor: '#00d4a0', // <-- custom color
  layout: 'topmenu', // nav menu position: sidemenu or topmenu
  contentWidth: 'Fixed', // layout of content: Fluid or Fixed, only works when layout is topmenu
  fixedHeader: true, // sticky header
  autoHideHeader: false, // auto hide header
  fixSiderbar: false, // sticky siderbar
  collapse: true,
};
```
<img width="320" alt="screenshot 2018-11-07 at 22 43 11" src="https://user-images.githubusercontent.com/9677898/48163170-40f23680-e2df-11e8-882b-37d7d402186d.png">

**Comment by codesignist** [comment]
I came across with the same issue. 2 weeks ago it was okay. But now it is not working properly.
I have searched a lot but I could not find source of the problem.

**Comment by chenshuai2144** [comment]
Looks like a load order problem

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2791
