### ISSUE TITLE
单页应用只要是重新部署后，刚好用户正在浏览的页面，却不知道你部署了，如何更新缓存？

### ISSUE THREAD

**Issue by ChasonHong** [ant-design/ant-design-pro#2803]
因为更新频繁，且在使用高峰期更新发布，如果正在使用应用的用户并没有刷新页面，访问的都是缓存的旧页面（单页应用index.html只有一个问题就出现在用户切换路由时js,css等打包是新的带hash但html入口文件不刷新是不会改变的），请问如何解决这个问题？

**Comment by chenshuai2144** [comment]
服务端更新之后更改一下头信息就好了，没必要纠结这些东西，客户端应用和浏览器的应用不是一回事。
