### ISSUE TITLE
Can I access request.cookies in Mock.js?

### ISSUE THREAD

**Issue by rockallite** [ant-design/ant-design-pro#2808]
#2794 tells us how to send a cookie in response.

However, when I try to access `req.cookies['some-key']` in Mock.js, something goes wrong in terminal:

`TypeError: Cannot read property 'some-key' of undefined`

According to the [API reference of Express 4.x](http://expressjs.com/en/api.html#req.cookies), it seems that [cookie-parser](https://www.npmjs.com/package/cookie-parser) middleware isn't loaded.

How can I load cookie-parser, or what's the right way to parser cookies in Mock.js? Thank you.

**Comment by rockallite** [comment]
After reading the [docs](https://umijs.org/plugin/develop.html) and the [source](https://github.com/umijs/umi/blob/umi%402.2.5/packages/umi-build-dev/src/plugins/mock/index.js), I finally figure it out how to load cookie-parser. Of course, it's a process of trial and error.

1. First, install cookie-parser:

    `$ npm i -D cookie-parser`

2. Then create a file named `plugins/umi-plugin-cookie-parser.js`:
    ```
    import cookieParser from 'cookie-parser';

    export default (api, opts) => {
      console.log('umi-plugin-cookie-parser loaded');
      // https://umijs.org/plugin/develop.html#addmiddlewarebeforemock
      // Add cookie-parser middleware before the mock, so req.cookies is accessible in Mock.js
      api.addMiddlewareBeforeMock(cookieParser);
    };
    ```

3. Add the plugin in `config/config.js`:

    ```
    const plugins = [
      [
        'umi-plugin-react',
        {
          // Options omitted for brevity...
        },
      ],
      // Add the plugin here
      './plugins/umi-plugin-cookie-parser',
    ];
    ```

4. Try to access `req.cookies` in `mock/user.js`:

    ```
    'GET /api/currentAuthority': (req, res) => {
      res.send({
        currentAuthority: req.cookies.authority || 'guest',
      });
    },
    ```

**Comment by chenshuai2144** [comment]
You are strong！ 👍

**Comment by rockallite** [comment]
BTW, if you want to avoid adding extra weight of `cookie-parser` to each request, you can parse cookies individually. Just run `npm i -D cookie` and write the mock like this:

  ```
  import cookie from 'cookie';

  export default {
    'GET /api/currentAuthority': (req, res) => {
      const cookies = cookie.parse(req.headers.cookie || '');
      res.send({
        currentAuthority: cookies.authority || 'guest',
      });
    },
  };
  ```

Reference [here](https://github.com/expressjs/cookie-parser/blob/master/index.js) and [here](https://github.com/jshttp/cookie)
