### ISSUE TITLE
搜索列表显示问题

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design-pro#281]
![image](https://user-images.githubusercontent.com/4178729/33191591-c36c2f1e-d0f5-11e7-97a9-a912a1b05e35.png)

这边显示错位。

环境：
Chrome 62.0.3202.94
MacOS 10.13.1

**Comment by ityao** [comment]
恩, 我也有这个问题

**Comment by chenshuai2144** [comment]
https://gw.alipayobjects.com/zos/rmsportal/gLaIAoVWTtLbBWZNYEMg.png 
这张图片有问题.
图片比例和别的不一样 差了两个像素.
希望修改一下图片
