### ISSUE TITLE
安装最新的ant design pro会出现编译阻塞，只有两个warning,却没有错误提示   20181108

### ISSUE THREAD

**Issue by wiki-wiki** [ant-design/ant-design-pro#2813]
**主要信息：**
os: win10   64位
npm: 6.4.1
node: v10.13.0
package.json中主要信息： 
  version: 2.1.1
 "start": "cross-env APP_TYPE=site umi dev","
 "umi": "^2.2.1",

**现象：**
npm  start，第一次能正常展示，修改一些文件之后，就会出现阻塞，编译始终在进行，等很久也没有反应。删除node_modules，用 npm /cnpm/yarn 重装也是一样编译阻塞。一般出现编译阻塞，项目再也启动不了。 显示如下信息

$ npm  start

> ant-design-pro@2.1.1 start D:\coach-test\ant-design-pro
> cross-env APP_TYPE=site umi dev

(node:7752) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Starting the development server...

Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
****

**期待结果：**
正常提示语法错误

**复现步骤:**
git clone https://github.com/ant-design/ant-design-pro.git
进入 ant-design-pro 目录, npm install

ctrl + c 结束开发模式
重新 npm run start， 显示始终如上信息，始终阻塞

在进行中项目中发现的，可稳定在 ant-design-pro 中复现

**Comment by chenshuai2144** [comment]
@sorrycc  cc

**Comment by sorrycc** [comment]
首次 npm start 正常？ctrl + c 后重启重现？

**Comment by unrealsmart** [comment]
确实有这个问题，首次 `npm install` 时，`puppeteer` 是无法正常安装（有可能是墙的缘故）
即使之后成功安装，仍然会有错误提示，在每一次`npm install`时：
![image](https://user-images.githubusercontent.com/11688458/48311409-58c90380-e5da-11e8-92d9-649915143476.png)

**Comment by chenshuai2144** [comment]
puppeteer 可以用 cnpm 安装解决

**Comment by damujiangr** [comment]
现在上手文档里默认 clone 的是 master 分支，经过验证，现在的 master 分支确实有 `jest-puppeteer ` 引发的问题，Mac 上同样会报错。只要在 clone 的时候用 release 分支就没有问题
```
git clone https://github.com/ant-design/ant-design-pro.git --depth=1 -b "2.1.1"
```

**Comment by sorrycc** [comment]
有问题再 reopen 吧。

**Comment by xf564246963** [comment]
![image](https://user-images.githubusercontent.com/18362264/49909639-adea8480-feba-11e8-9a22-0f80af968844.png)
最新代码仍然有这个问题

**Comment by xf564246963** [comment]
> 有问题再 reopen 吧。

![image](https://user-images.githubusercontent.com/18362264/49909670-cd81ad00-feba-11e8-9c33-28b67ea21d60.png)

最新代码仍然有这个问题
