### ISSUE TITLE
本地开发环境,页面刷新一直处于loading状态

### ISSUE THREAD

**Issue by zhichao8756** [ant-design/ant-design-pro#2814]
静态页面刷新之后一直处于loading状态,重新编译热加载之后才恢复正常,请问一下这是什么原因?
![image](https://user-images.githubusercontent.com/24514251/48255343-626e3200-e447-11e8-912e-ac85e0d9198a.png)

**Comment by chenshuai2144** [comment]
感觉像是组件没有挂载，有重现的地址吗？

**Comment by zhichao8756** [comment]
@chenshuai2144 感谢,查了一遍所有组件,确实是有一个组件没有挂载,谢谢!
