### ISSUE TITLE
Authorized 如何控制页面中具体按钮权限

### ISSUE THREAD

**Issue by happylys** [ant-design/ant-design-pro#2815]
本人一直做后台(java，springBoot,jsp)开发；因系统需要，想引入我们的这套框架来开发前端，对React不熟悉，所以，有个问题请教下：
1.比如有个功能，主页面有工具栏及表格，工具栏放置相关的按钮，要如何做到根据后台开放的权限来控制具体按钮的显示与否，比如，添加(form:add)，删除(form:delete)的按钮，springBoot使用shiro的标签来实现，我们的框架如何实现？
我尝试着用AuthorizedFunction的方式，但不知道如何将按钮级的权限(form:add,form:delete)传入

**Comment by happylys** [comment]
我自己实现了，只不过实现的没有那么优雅

**Comment by shaolei** [comment]
@happylys 讲讲你是怎么实现的

**Comment by mxthd** [comment]
@happylys   大佬讲讲怎么实现的呗

**Comment by noxue** [comment]
实现方案在这里：https://umijs.org/plugins/plugin-access#children
