### ISSUE TITLE
Authorized 可以禁掉吗？

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#2817]
为啥 Pro 版本越做越复杂了呢？提供这些组件真的都有人在用吗？Authorized 越来越复杂了，删都要删半天，关联这么多东西，可以直接禁掉吗？一般公司都有自己的鉴权系统，真正需要权限的，前端鉴权根本不能满足需求啊

**Comment by Warden-Thresh** [comment]
前后端都需要鉴权啊

**Comment by yutingzhao1991** [comment]
鉴权是必要的功能，关于这个问题其实是一个 pro 中普遍存在的问题，pro 中的各个页面和各个模块能否做成可插拔的。不仅仅是权限这块，还有国际化，动态主题这些。

当前 pro 的页面计划通过 umi block 来解决（https://github.com/ant-design/ant-design-pro/issues/2809），认证还有国际化这些还没有比较好的方案。

**Comment by hardywu** [comment]
Authorized 应该用通用的包
