### ISSUE TITLE
最新版中，List组件的分割线位置异常

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#2823]
图一是最新pro2（11.12 pull的代码）List组件内部的分割线示意图，位置在所有item的最下边，好像不对？设置split={false}无法去除分割线。且在List组件只有一个item的情况下，分割线依然存在。
图二是旧版pro2  List组件内部的分割线位置示意图，位置在相邻两个item的中间，应该是正常的。
图三是代码。
另外：最新pro2修复了card组件的title属性采用栅格布局异常的bug[#2534](https://github.com/ant-design/ant-design-pro/issues/2534)，此问题可关闭。
![new](https://user-images.githubusercontent.com/40480550/48329526-296ed100-e684-11e8-9e5e-4cfba7cde2f5.png)
![old](https://user-images.githubusercontent.com/40480550/48329533-2c69c180-e684-11e8-99a0-f422a42efe66.png)
![code](https://user-images.githubusercontent.com/40480550/48329536-2ecc1b80-e684-11e8-965d-3747f5747834.png)

**Comment by chenshuai2144** [comment]
你看看是不是 css 设置的边框线，pro 不会做这些处理的

**Comment by linzelong95** [comment]
@chenshuai2144 
hi，我找到了分割线的样式表达，如图。不知为何会出现这样的样式设置。另外，card组件title属性的栅格布局又失效了，bug[#2534](https://github.com/ant-design/ant-design-pro/issues/2534)复现，然而，在这期间我并没有修改任何代码。
![result2](https://user-images.githubusercontent.com/40480550/48603546-c47fe780-e9b1-11e8-92b4-3f80917b1c11.png)
