### ISSUE TITLE
如何在查询列表中实现点击某条数据，进入此条数据的详情页面？

### ISSUE THREAD

**Issue by jinyuanchun** [ant-design/ant-design-pro#2824]
需求：
1、在左边菜单中，需要显示详情页面
2、通过点击查询列表中某个单元格数据，页面跳转到此条数据的详情页面
3、路由：例如——/list/projetList/某个项目

**Comment by shaopeng1** [comment]
要点击的单元格外面包个链接就行了啊。

**Comment by chenshuai2144** [comment]
render:(text)=><Link>{text}<Link>
