### ISSUE TITLE
热更新经常失效

### ISSUE THREAD

**Issue by zhouzixing** [ant-design/ant-design-pro#2829]
太痛苦了 热更新 为啥有时候可以，有时候又会失效，而且失效的时候页面怎么刷新也没有用，求帮助

**Comment by yutingzhao1991** [comment]
什么环境？什么浏览器？是修改什么的时候会出这个问题？

**Comment by zhouzixing** [comment]
mac上 node是10.13 在chrome 72上面 有时候无效怎么刷都更新不了，刷新网页也没用。实在不行告诉我如何关闭热更新，让我刷新页面可以也行，要不然实在无法调试

**Comment by zhouzixing** [comment]
![1542009821804](https://user-images.githubusercontent.com/16719955/48334153-9ab68000-e694-11e8-982a-bf839d4b0506.jpg)
这是每次按保存后瞬间刷出的 然后热更新就不起作用了

**Comment by yutingzhao1991** [comment]
看看 https://github.com/ant-design/ant-design-pro/issues/2494 这个问题好像是一样的？

**Comment by zhouzixing** [comment]
> 看看 #2494 这个问题好像是一样的？

是的 我在那也留言了 这个问题他其实还没解决掉

**Comment by yutingzhao1991** [comment]
按照 issue 里面说的把 plugin.config.js 这个里面逻辑屏蔽掉就好了。

**Comment by zhouzixing** [comment]
> 按照 issue 里面说的把 plugin.config.js 这个里面逻辑屏蔽掉就好了。
已经去掉了 还是不见效 这个问题看他们描述好像mac下面 出现还挺多的

**Comment by sansx** [comment]
同在mac下，已屏蔽plugin.config.js  
>node版本`v8.11.3`,chrome版本`70.0.3538.77`
修改less样式之后，热更新时有时无
之前因为控制台报`Cannot read property 'hash' of undefined`，把umi重新安装了一遍

**Comment by zhouzixing** [comment]
> 同在mac下，已屏蔽plugin.config.js
> 
> > node版本`v8.11.3`,chrome版本`70.0.3538.77`
> > 修改less样式之后，热更新时有时无
> > 之前因为控制台报`Cannot read property 'hash' of undefined`，把umi重新安装了一遍

你说的这两个问题我同样存在，不过控制台报错那个只要更新下就可以了 npm update
热更新还是没法解决，蚂蚁金服的大神能否帮忙指点下

**Comment by LJZJIANG** [comment]
> mac上 node是10.13 在chrome 72上面 有时候无效怎么刷都更新不了，刷新网页也没用。实在不行告诉我如何关闭热更新，让我刷新页面可以也行，要不然实在无法调试

朋友，你的问题解决了么，我也遇到了。还没有解决。

**Comment by zhouzixing** [comment]
没有呢 很悲催

**Comment by jerryyan1990** [comment]
我也一样经常热更卡在98%，还一直有 hash undefined 的问题，脑壳痛

**Comment by playdelphi** [comment]
我也是同样的情况

**Comment by jerryyan1990** [comment]
再回复，屏蔽plugin.config.js也无效，经常自动失效，失效后改 js 不刷新，改 less 不刷新，重启服务不刷新，删除缓存再重启才有效果....

**Comment by playdelphi** [comment]
我在Mac下，没有发现有热更新功能。无论清没清缓存都一样。我现在只能在windows虚拟机下开发。

**Comment by xiaohuoni** [comment]
Mac 下，出现这个问题，就会导致热更新失效。
修复步骤，关掉umi dev，删除.cache文件夹，删除.umi文件夹，重新开启umi dev，
没发现什么重现步骤。
<img width="710" alt="20181128170516" src="https://user-images.githubusercontent.com/11746742/49140658-ccd00f00-f32f-11e8-9daa-953d9eb4d7f0.png">

**Comment by playdelphi** [comment]
> Mac 下，出现这个问题，就会导致热更新失效。
> 修复步骤，关掉umi dev，删除.cache文件夹，删除.umi文件夹，重新开启umi dev，
> 没发现什么重现步骤。
> <img alt="20181128170516" width="710" src="https://user-images.githubusercontent.com/11746742/49140658-ccd00f00-f32f-11e8-9daa-953d9eb4d7f0.png">

删除.umi hmr生效

**Comment by playdelphi** [comment]
> Mac 下，出现这个问题，就会导致热更新失效。
> 修复步骤，关掉umi dev，删除.cache文件夹，删除.umi文件夹，重新开启umi dev，
> 没发现什么重现步骤。
> <img alt="20181128170516" width="710" src="https://user-images.githubusercontent.com/11746742/49140658-ccd00f00-f32f-11e8-9daa-953d9eb4d7f0.png">

建议 删除.umi 工作在启动 umi dev 时自动完成。可以加入scripts 中。清理.cache大部分老鸟都清楚，但没人具备.umi的经验。要求程序员在上手前看全部issue和使用文档，不现实。自动完成这个工作有助于框架的易用性。

**Comment by xiaohuoni** [comment]
@paranoidjk 你好，我给的这个是现象，不是给解决方案，不要误会。这个问题后面会处理的。

**Comment by kltk** [comment]
> mac上 node是10.13 在chrome 72上面 有时候无效怎么刷都更新不了，刷新网页也没用。实在不行告诉我如何关闭热更新，让我刷新页面可以也行，要不然实在无法调试

看起来像我之前碰到的问题，可以试一下清空 chrome 开发者工具的设置，（开发者工具右上角菜单-> settings -> preference -> Restore defaults and reload）
--
ps: 我是搜 unnamed compat plugin 来的

**Comment by HAYWAEL** [comment]
同一个项目，有些页面可以正常更新，有些页面不更新。其中不更新的页面 每次webSocket接收到的hash值都是同一个
<img width="704" alt="2018-12-11 8 31 00" src="https://user-images.githubusercontent.com/15700512/49801041-0408dc00-fd84-11e8-8ddd-7dada0b98d71.png">

**Comment by HAYWAEL** [comment]
> 同一个项目，有些页面可以正常更新，有些页面不更新。其中不更新的页面 每次webSocket接收到的hash值都是同一个
> <img alt="2018-12-11 8 31 00" width="704" src="https://user-images.githubusercontent.com/15700512/49801041-0408dc00-fd84-11e8-8ddd-7dada0b98d71.png">

找到问题了 很蠢的一个问题 ，router.config.js 中的component 路径配置的大小写有问题

**Comment by xiaohuoni** [comment]
@HAYWAEL 
> 找到问题了 很蠢的一个问题 ，router.config.js 中的component 路径配置的大小写有问题

什么问题？欢迎PR

**Comment by HAYWAEL** [comment]
> @HAYWAEL
> 
> > 找到问题了 很蠢的一个问题 ，router.config.js 中的component 路径配置的大小写有问题
> 
> 什么问题？欢迎PR

umi 当路由是走配置的时候 开发模式 启动的时候 大小写不敏感 ，可以正常渲染页面；热更新的时候大小写是敏感的，保存后 ，页面不会自动刷新。mac上出现，windows 不会。太具体的原因我也没深究，查到 webpack 引用的 chokidar 包。

**Comment by Maxim-HSP** [comment]
> 试了一下，不是百分百触发失效。都会触发
> 
> ```shell
> [hardsource:21374fc1] Using 45 MB of disk space.
> [hardsource:21374fc1] Last compilation did not finish saving. Building new cache.
> ```

这个issue下描述的应该是两个问题。

热更新失效：基本上是如楼上所说，应该是由配置式路由的路径大小写与实际的文件路径大小写不匹配导致的，hmr更新的总是同一个hash值。至少我自己修改了路由配置和文件路径之后可以恢复正常

hardSource频繁的freeze报错：目前实际测试AntD Pro、create-umi创建的AntD Pro或者project在开启hardSource的情况下基本是在二次刷新代码的时候100%出现。比对了依赖和提交记录，发现umi 2.3.0左右 才固定包括 umi-build-dev 在内的主要依赖版本号（之前都是上尖号，意味着2.3.0以下重新安装依赖包你也是在次要版本上自动升级的，我还以为是我配置出错，浪费了很多时间），而 umi-build-dev 下 依赖的 af-webpack 升级了 hardSource 到 0.13.1（与之前0.12.0版本差距大概5个月？），在我自己的项目直接改lock文件安装hardSource 0.12.0版本，目前暂时一切正常，没有报错，正常缓存。

蚂蚁的大佬们要不要考虑下把af-webpack的hardSource版本降一下，或者看看有没有什么其他方法。

**Comment by xiaohuoni** [comment]
@sorrycc 老大

**Comment by sorrycc** [comment]
和 hard-source 版本有关？

**Comment by Maxim-HSP** [comment]
> 和 hard-source 版本有关？

是的，降回0.12.0一切正常。（且freeze报错基本和less文件有关，猜测可能是0.13对于less兼容性不好？）

**Comment by Delete540** [comment]
关闭hardsource,less编译越来越慢

**Comment by AngelName** [comment]
更新umi后就好了

**Comment by b9AobJ** [comment]
1、修改UMI为当前2.4.2版本
2、
rm -rf node_modules
rm package-lock.json
npm cache clear --force
npm install（用了cnpm）
然后现在可以了、可以了，我也不清楚这样子能不能帮到大家

**Comment by ximendatie** [comment]
> > 试了一下，不是百分百触发失效。都会触发
> > ```shell
> > [hardsource:21374fc1] Using 45 MB of disk space.
> > [hardsource:21374fc1] Last compilation did not finish saving. Building new cache.
> > ```
> 
> 这个issue下描述的应该是两个问题。
> 
> 热更新失效：基本上是如楼上所说，应该是由配置式路由的路径大小写与实际的文件路径大小写不匹配导致的，hmr更新的总是同一个hash值。至少我自己修改了路由配置和文件路径之后可以恢复正常
> 
> hardSource频繁的freeze报错：目前实际测试AntD Pro、create-umi创建的AntD Pro或者project在开启hardSource的情况下基本是在二次刷新代码的时候100%出现。比对了依赖和提交记录，发现umi 2.3.0左右 才固定包括 umi-build-dev 在内的主要依赖版本号（之前都是上尖号，意味着2.3.0以下重新安装依赖包你也是在次要版本上自动升级的，我还以为是我配置出错，浪费了很多时间），而 umi-build-dev 下 依赖的 af-webpack 升级了 hardSource 到 0.13.1（与之前0.12.0版本差距大概5个月？），在我自己的项目直接改lock文件安装hardSource 0.12.0版本，目前暂时一切正常，没有报错，正常缓存。
> 
> 蚂蚁的大佬们要不要考虑下把af-webpack的hardSource版本降一下，或者看看有没有什么其他方法。

之前路由配置大小写错了，修改之后问题解决

**Comment by xiaohuoni** [comment]
现在暂时能知道的有三个原因：
1、hardsource 删掉hardsource的相关配置---最新的umi已经废弃这个
2、路由配置大小写，不敏感，写错大小写也能允许，很难定位是哪个页面
3、less 文件里面出错，没有正确中止和报错
最明显和最容易重现的是hardsource，建议更新umi版本。还有问题再reopen。

**Comment by skjgithub950423** [comment]
解决了我的问题 感谢！

**Comment by FrankFan** [comment]
同样遇到热更新hmr失效问题，排查了好长时间终于解决了。


开发环境： Mac Pro
```bash
$ node -v # v11.11.0
$ umi -v # 2.6.8 (特意升级到最新版本)
```

经过在issue中查找，定位到我的问题是 `路由配置大小写`， 具体说来就是在 `router.config.js`中写写的 `component` 路径大小写和实际文件大小写不一致，改成一致就好了。 🤦‍♂️

**Comment by LukerSpringtree** [comment]
> > 同一个项目，有些页面可以正常更新，有些页面不更新。其中不更新的页面 每次webSocket接收到的hash值都是同一个
> > <img alt="2018-12-11 8 31 00" width="704" src="https://user-images.githubusercontent.com/15700512/49801041-0408dc00-fd84-11e8-8ddd-7dada0b98d71.png">
> 
> 找到问题了 很蠢的一个问题 ，router.config.js 中的component 路径配置的大小写有问题

我觉得你这个是正解
就是 component 虽然 写错的 导致的 热更新不能刷新的问题
虽然 写成小写的 UI 能展示出来但是  就不支持热更新了.
我觉 umi 可以把 这个Component 支持 判断 大小写 写错就不让显示了.

@sorrycc

**Comment by Lumend** [comment]
> > > 试了一下，不是百分百触发失效。都会触发
> > > ```shell
> > > [hardsource:21374fc1] Using 45 MB of disk space.
> > > [hardsource:21374fc1] Last compilation did not finish saving. Building new cache.
> > > ```
> > 
> > 
> > 这个issue下描述的应该是两个问题。
> > 热更新失效：基本上是如楼上所说，应该是由配置式路由的路径大小写与实际的文件路径大小写不匹配导致的，hmr更新的总是同一个hash值。至少我自己修改了路由配置和文件路径之后可以恢复正常
> > hardSource频繁的freeze报错：目前实际测试AntD Pro、create-umi创建的AntD Pro或者project在开启hardSource的情况下基本是在二次刷新代码的时候100%出现。比对了依赖和提交记录，发现umi 2.3.0左右 才固定包括 umi-build-dev 在内的主要依赖版本号（之前都是上尖号，意味着2.3.0以下重新安装依赖包你也是在次要版本上自动升级的，我还以为是我配置出错，浪费了很多时间），而 umi-build-dev 下 依赖的 af-webpack 升级了 hardSource 到 0.13.1（与之前0.12.0版本差距大概5个月？），在我自己的项目直接改lock文件安装hardSource 0.12.0版本，目前暂时一切正常，没有报错，正常缓存。
> > 蚂蚁的大佬们要不要考虑下把af-webpack的hardSource版本降一下，或者看看有没有什么其他方法。
> 
> 之前路由配置大小写错了，修改之后问题解决

还有引入的组件，路径大小写错了，热更新会生效，但页面也不会改变。

**Comment by Vanyoo** [comment]
有没有大佬来说下原理，这样也容易解决一些。。。哪怕是暂时的。

- 在没有开启磁盘大小写敏感的Mac上没问题，但是在开启大小写的磁盘上就有问题。

- 路径我检查是正确的。

然后就没有头绪了。

**Comment by xiaoheikejj** [comment]
> > 试了一下，不是百分百触发失效。都会触发
> > ```shell
> > [hardsource:21374fc1] Using 45 MB of disk space.
> > [hardsource:21374fc1] Last compilation did not finish saving. Building new cache.
> > ```
> 
> 这个issue下描述的应该是两个问题。
> 
> 热更新失效：基本上是如楼上所说，应该是由配置式路由的路径大小写与实际的文件路径大小写不匹配导致的，hmr更新的总是同一个hash值。至少我自己修改了路由配置和文件路径之后可以恢复正常
> 
> hardSource频繁的freeze报错：目前实际测试AntD Pro、create-umi创建的AntD Pro或者project在开启hardSource的情况下基本是在二次刷新代码的时候100%出现。比对了依赖和提交记录，发现umi 2.3.0左右 才固定包括 umi-build-dev 在内的主要依赖版本号（之前都是上尖号，意味着2.3.0以下重新安装依赖包你也是在次要版本上自动升级的，我还以为是我配置出错，浪费了很多时间），而 umi-build-dev 下 依赖的 af-webpack 升级了 hardSource 到 0.13.1（与之前0.12.0版本差距大概5个月？），在我自己的项目直接改lock文件安装hardSource 0.12.0版本，目前暂时一切正常，没有报错，正常缓存。
> 
> 蚂蚁的大佬们要不要考虑下把af-webpack的hardSource版本降一下，或者看看有没有什么其他方法。

我的项目也出现了这个问题，我刚刚排查了一下是路径大小写的问题，谢谢大佬

**Comment by xinyanxing** [comment]
我也遇到了这个问题,编译了,但是页面没有更新,卡在99% 不动了,找了两天耽误开发进度太坑了,最后发现是umi mfsu 这个配置影响(mfsu 挺坑的),antdPro 默认开启的 ,关掉mfsu ,可以热更新,问题解决.希望可以帮助到大家

**Comment by MuLoo** [comment]
> 我也遇到了这个问题,编译了,但是页面没有更新,卡在99% 不动了,找了两天耽误开发进度太坑了,最后发现是umi mfsu 这个配置影响(mfsu 挺坑的),antdPro 默认开启的 ,关掉mfsu ,可以热更新,问题解决.希望可以帮助到大家

Works for me ！
love from china ❤️
