### ISSUE TITLE
 0.3.0 The package file cannot run！

### ISSUE THREAD

**Issue by remotesc2** [ant-design/ant-design-pro#283]
我用 0.3.0 版本，本身 npm start 没有问题，但是如果将 npm run build 后的 dist 文件，放到 jetty 下运行，会出现如下异常

![123](https://user-images.githubusercontent.com/9023036/33194825-a52a398e-d10d-11e7-8201-63258cdae812.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/847cb50bcfa11578584686fe0071c8962a2958d5#diff-ef860daacd753531645fa756fbe5b836R62
