### ISSUE TITLE
input 和 getFieldDecorator 结合双向绑定问题

### ISSUE THREAD

**Issue by zhouzixing** [ant-design/ant-design-pro#2830]
我是在render 中的return前打印的
![1](https://user-images.githubusercontent.com/16719955/48338376-719bec80-e6a0-11e8-9841-48164e33159c.jpg)
循环代码如下
![3](https://user-images.githubusercontent.com/16719955/48338423-93956f00-e6a0-11e8-98a6-2e0f93142059.jpg)
界面预期是 第一行 都为空 第二行有值
实际，两行都有值
![2](https://user-images.githubusercontent.com/16719955/48338456-aad45c80-e6a0-11e8-9cb3-6427b1eafe8f.jpg)

**Comment by zhouzixing** [comment]
form.setFieldsValue({'areaPhone': ''});  我是通过这样解决的 但是还是没有搞明白原因

**Comment by chenshuai2144** [comment]
这样太黑了，你应将这个逻辑再处理一下。变得易懂一点
