### ISSUE TITLE
antd-pro 打包后所设置的主题颜色不生效

### ISSUE THREAD

**Issue by jinyaqiao1102** [ant-design/ant-design-pro#2831]
当我在defaultSettings.js中修改了primary-color后构建出来的文件引入了Color.less 导致我设置的主题颜色没有生效，不知道如何处理此问题？难道这是一个bug

**Comment by afc163** [comment]
构建后不应该引入 Color.less。

**Comment by jinyaqiao1102** [comment]
需要修改什么配置吗？目前官方demo  npm run build 也会出现这种情况

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2791
看起来是同一个问题
