### ISSUE TITLE
How can i clear all app state on logout?

### ISSUE THREAD

**Issue by pkegashira** [ant-design/ant-design-pro#2832]
How can i hook in to the store to clear all state when a logout effect is dispatched?

**Comment by chenshuai2144** [comment]
reload?

**Comment by pkegashira** [comment]
i am already calling `reloadAuthorized` but still the container retains data. i wanted to achieve somthing like this https://t.co/rxNrd8limH

**Comment by chenshuai2144** [comment]
location.reload();

**Comment by charithjayasanka** [comment]
location.reload(); Works

**Comment by charithjayasanka** [comment]
> location.reload();

Works
