### ISSUE TITLE
什么时候可以支持 ie 11和 edge

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#2834]
什么时候可以支持 ie 11和 edge

**Comment by xgj1988** [comment]
@afc163  我把你们的2.0 的界面用IE 11和 edge 打开，都是白板哦。

**Comment by xgj1988** [comment]
@afc163  就是 https://preview.pro.ant.design/dashboard/analysis 这个地址。

**Comment by xgj1988** [comment]
@afc163  为什么我这个地址打开是 空白呢？https://system.xyzy.online

**Comment by xgj1988** [comment]
@afc163  我知道了。是因为pinyin 这个包，我想问一下大神，你知道有支持IE11的拼音转换包吗？

**Comment by yutingzhao1991** [comment]
@xgj1988 pinyin 这个包有什么问题？如果是代码没有转成 es5 的话可以通过把这个包加到 https://github.com/umijs/es5-imcompatible-versions 这个里面解决。

**Comment by xgj1988** [comment]
@yutingzhao1991 这个包是把中文转换成拼音的。

**Comment by xgj1988** [comment]
@yutingzhao1991  

  extraBabelIncludes: [
    'node_modules/pinyin',
  ],

我加上这个也不行也，。

**Comment by xiaohuoni** [comment]
@xgj1988 
```
extraBabelIncludes:[/pinyin/]
```
https://webpack.js.org/configuration/module/#condition

**Comment by xgj1988** [comment]
@xiaohuoni  不需要加  node_modules吗？

**Comment by xgj1988** [comment]
@xiaohuoni  出现  `” SCRIPT5009: “Promise”未定义  umi.js (101960,1)  ` 这个是怎么回事呢？

**Comment by xgj1988** [comment]
不知道是不是我.umi下面生成的文件少了。问题地址。参考 https://github.com/umijs/umi/issues/1457

**Comment by yutingzhao1991** [comment]
了解下 https://umijs.org/zh/config/#targets 这个配置。

**Comment by xgj1988** [comment]
@yutingzhao1991  这个我知道，这个配置我写了的，就和antd design pro 写的一样。。现在 
又报 如下错误了。
`// https://umijs.org/plugin/umi-plugin-react.html#dynamicimport
var _default = () => _react.default.createElement("div", {
  style: {
    paddingTop: 100,
    textAlign: 'center'
  }
}, _react.default.createElement(_spin.default, {
  size: "large"
}));`

**Comment by xiaohuoni** [comment]
> 不需要加 node_modules吗？
我这么写是一个正则判断

**Comment by xgj1988** [comment]
@xiaohuoni  你加QQ嘛。。30756500 。这个比较复杂。麻烦了。

**Comment by xgj1988** [comment]
@xiaohuoni 如果QQ不方便，钉钉也可以 13554783576

**Comment by xiaohuoni** [comment]
@xgj1988 已加丁丁

**Comment by xgj1988** [comment]
我还是有问题。 ie 下面报错
SCRIPT1002: 语法错误
umi.js (100198,19)
var _default = () => _react.default.createElement("div", {
