### ISSUE TITLE
ant-design-pro1.0去哪里下载

### ISSUE THREAD

**Issue by joeyFuck** [ant-design/ant-design-pro#2836]
额，不好意思在这里提问。
因为项目要支持ie10,看了下好像1.0是支持的，但不知道去哪里下载？
谢谢

**Comment by yutingzhao1991** [comment]
1.0 也不支持 IE10，会有样式问题（和 2.0 一样的问题）。你可以 1.0 的代码可以在 https://github.com/ant-design/ant-design-pro/tree/v1 这里拿到代码试试。

1.0 中兼容 ie10 的 2.0 里面也兼容，建议使用 2.0，如果需要兼容那只能自行处理了 。
