### ISSUE TITLE
与springboot 整合后部署到tomcat 无法访问

### ISSUE THREAD

**Issue by linyongfu2013** [ant-design/ant-design-pro#2837]
RT，项目整合后打包成 war ，放到tomcat 下启动无法访问，静态资源报404，如下图，求助如何解决？

![wechate25fb764d5a4e1e9983975b3a2d58f2c](https://user-images.githubusercontent.com/4011963/48397117-b33b9e80-e757-11e8-87f9-d72d2fe89f6a.png)

**Comment by 33ilike** [comment]
https://umijs.org/zh/config/#publicpath

**Comment by linyongfu2013** [comment]
@33ilike 谢谢，最简单的办法，把打包好的项目放 tomcat 的 ROOT 目录下就行了
