### ISSUE TITLE
Ant Design Pro 如何动态修改路由配置文件config/router.config.js

### ISSUE THREAD

**Issue by csdwd** [ant-design/ant-design-pro#2839]
Ant Design Pro 如何实现登录成功后从后台获取路由配置文件
及如何动态修改 `config/router.config.js` 里的配置文件, 在登录成功后, 从后台获取到用户对应的路由信息和权限
因为在路由中实现了用户权限判断, 由于权限类别太多, 无法从前端进行管理

**Comment by chenshuai2144** [comment]
router.config.js 在服务器生成现在是做不到的。因为 router 还要设置加载哪些文件。

**Comment by csdwd** [comment]
@chenshuai2144 那`router.config.js`中的 `authority` 字段是否可以根据后台的数据动态修改呢?

**Comment by chenshuai2144** [comment]
你可以自己写一个逻辑出来，现在的逻辑默认是通过，你可以默认是不通过
