### ISSUE TITLE
如何保持同步更新

### ISSUE THREAD

**Issue by jimtang9527** [ant-design/ant-design-pro#284]
ant-design-pro挺好的脚手架，我采用了后，它在不停更新。就会有一个同步更新的问题，请问有好的解决方案吗？谢谢

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0-Ant-Design-Pro%EF%BC%9F
