### ISSUE TITLE
关于数据交互

### ISSUE THREAD

**Issue by zoey1994** [ant-design/ant-design-pro#2840]
我看到脚手架的layouts/Header.js中connect组件之后的currentUser属性，找不到代码中是在何处触发了全局model里user.js的fetchCurrent这个异步动作来初始化currentUser，求大神告知是脚手架里是在何处触发了这个动作

**Comment by xiaohuoni** [comment]
Header.js里面这个应该没用了。
触发的话，应该是BasicLayout.js里面的componentDidMount
```
  componentDidMount() {
    const { dispatch } = this.props;
    dispatch({
      type: 'user/fetchCurrent',
    });
   ...
  }
```

**Comment by zoey1994** [comment]
> > Header.js里面这个应该没用了。
> > 触发的话，应该是BasicLayout.js里面的componentDidMount
> > ```
> >   componentDidMount() {
> >     const { dispatch } = this.props;
> >     dispatch({
> >       type: 'user/fetchCurrent',
> >     });
> >    ...
> >   }
> > ```
我之前标记结果竟忘了。谢谢哈！ 还有一个问题，就是BasicLayout.js里面的props的collapsed这个值，在移动端的时候自动变为true来将菜单收进去，我也是找不到这个动作是在哪里触发的

**Comment by chenshuai2144** [comment]
silder 的 tirgger

**Comment by zoey1994** [comment]
> silder 的 tirgger

我指的是BasicLayout.js里面SiderMenu菜单在移动端的时候自动收进去了，查看redux devtool发现collapsed变为true了，找不到你说的silder

**Comment by xiaohuoni** [comment]
全局搜索isMobile

**Comment by zoey1994** [comment]
> 全局搜索isMobile

我之前也在好几个相关文件搜isMobile，但是也找不到触发的动作

**Comment by zoey1994** [comment]
> silder 的 tirgger

我看到silder组件的一些参数<Sider
        trigger={null}
        collapsible
        collapsed={collapsed}
        breakpoint="lg"
        onCollapse={onCollapse}
        width={256}
        theme={theme}
        className={siderClassName}
      >
在mobile模式下触发断点改变collapsed值，然后触发onCollapse函数，onCollapse事件会给该函数传递这样一组参数(collapsed, type)是吗？我在文档里看到onCollapse类型是这样的(collapsed, type) => {}
