### ISSUE TITLE
下载Chromium失败

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2841]
下载Chromium失败（已经设置淘宝镜像）

    D:\workspace\www\ant-design-pro-learning
    λ yarn
    yarn install v1.12.3
    //...
    Directory: D:\\workspace\\www\\ant-design-pro-learning\\node_modules\\puppeteer
    Output:
    ERROR: Failed to download Chromium r599821! Set \"PUPPETEER_SKIP_CHROMIUM_DOWNLOAD\" env variable to skip download.
    { Error: connect ETIMEDOUT 172.217.161.176:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
      errno: 'ETIMEDOUT',
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '172.217.161.176',
    success Saved lockfile.
    Done in 343.80s.

可以手动下载Chromium吗？从`https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/`可以下载,问题是下载后放在什么目录？

**Comment by chenshuai2144** [comment]
cnpm
