### ISSUE TITLE
尝试React 16.7用带Hook的函数组件重写Class组件，this.props该怎么处理？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2842]
尝试React 16.7用带Hook的函数组件重写Class组件，this.props该怎么处理？
比如umi-antd-mobile中的BasicLayout.js文件第22行：
https://github.com/jinjinwa/umi-antd-mobile/blob/master/src/layouts/BasicLayout.js
   
像下面这样写对吗？但是不太清楚改写后props该传什么值？
```
function BasicLayout(props) {
//...
  const { children, location, loading } = props;
//...
}
```

**Comment by chenshuai2144** [comment]
这样是对的

**Comment by zwl1619** [comment]
@chenshuai2144  函数组件使用时props传什么值？

**Comment by chenshuai2144** [comment]
和 this.props 是一样的
