### ISSUE TITLE
functions和scripts文件夹里面是放什么文件？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2845]
functions和scripts文件夹里面是放什么文件？  
文档中没有说到这两个目录https://pro.ant.design/docs/getting-started-cn   
![image](https://user-images.githubusercontent.com/13177997/48466026-94a0da80-e81f-11e8-825f-16700601edc2.png)

**Comment by chenshuai2144** [comment]
firebase function 和测试脚本
