### ISSUE TITLE
没有像app.js这种所谓的入口文件吗？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2846]
ant-design-pro没有像app.js这种所谓的入口文件吗？

**Comment by chenshuai2144** [comment]
global.js

**Comment by zwl1619** [comment]
@chenshuai2144 搜了一下，有很多个，但不在根目录和src目录，是哪一个？

**Comment by chenshuai2144** [comment]
src目录下的是一个约定

**Comment by zwl1619** [comment]
@chenshuai2144 有点疑惑，src目录下并没有这个文件

**Comment by chenshuai2144** [comment]
对呀 因为pro不用呀

**Comment by zwl1619** [comment]
@chenshuai2144 那上面说的global.js是指哪一个目录的global.js？

**Comment by chenshuai2144** [comment]
> src目录下的,是一个约定

**Comment by xiaohuoni** [comment]
https://umijs.org/zh/guide/app-structure.html#src-global-j-t-sx

**Comment by zwl1619** [comment]
@xiaohuoni  src目录下只有src/global.less，没有src/global.(j|t)sx，上面说“是一个约定”，意思是它不需要存在，只要约定它存在，它就存在？是这个意思？
![image](https://user-images.githubusercontent.com/13177997/48528710-287bb080-e8cb-11e8-9c06-9132ec728868.png)

**Comment by xiaohuoni** [comment]
@zwl1619 不是约定她存在，它就存在。是约定它存在就使用它。如果你不需要在全局js里面写任何东西，那就不需要这个文件。如果你需要，那你新建这个文件，就好了。

**Comment by xiaohuoni** [comment]
@zwl1619 src/global.(j|t)sx 这个的意思是，这个文件可以是global.js global.jsx global.ts global.tsx适用于各种情况
