### ISSUE TITLE
自定义组件不能跟着主题切换？

### ISSUE THREAD

**Issue by RivanLuo** [ant-design/ant-design-pro#2847]
为什么2.0切换主题这个功能，自定义组件的主题不能跟着切换，也引用了less变量的，只有antd的组件才可以切换

![local](https://user-images.githubusercontent.com/13898695/48468871-1268e400-e828-11e8-9f17-6b1abc715fb7.png)
![default](https://user-images.githubusercontent.com/13898695/48468872-1268e400-e828-11e8-9013-bef19aa943ee.png)

**Comment by RivanLuo** [comment]
一图是我本地，二图的官网，好像antd pro components中的组件主题都不能跟着切换

**Comment by chenshuai2144** [comment]
最近有个bug。

**Comment by RivanLuo** [comment]
> 最近有个bug。
意思是说，我提的这个问题是一个bug？

**Comment by chenshuai2144** [comment]
#2791
