### ISSUE TITLE
content的权限问题

### ISSUE THREAD

**Issue by zoey1994** [ant-design/ant-design-pro#2848]
BasicLayout.js文件中

<Content style={this.getContentStyle()}>
            <Authorized
              authority={routerConfig && routerConfig.authority}
              noMatch={<Exception403 />}
            >
              {children}
            </Authorized>
 </Content>

Authorized的准入权限为['admin']，而routerConfig && routerConfig.authority 是undefined，为什么还能通过权限验证。

**Comment by chenshuai2144** [comment]
undefined 是任何人都可以的意思
