### ISSUE TITLE
umi 2.2.6版本 build 错误：Cannot find module 'antd-pro-merge-less'

### ISSUE THREAD

**Issue by huangdou0204** [ant-design/ant-design-pro#2849]
umi 2.2.6版本 build 错误：Cannot find module 'antd-pro-merge-less'
umi 2.2.4 无问题

**Comment by xiaohuoni** [comment]
antd-pro-merge-less 这个是pro自己装的module和umi无关，重新install吧

**Comment by Evan-Future** [comment]
发现问题虽然是 缺少了module模块，但是是因为在umi中引用了这个模块
我的Jenkins 脚本是因为执行了 umi -v  再 npm install 的。原因就是umi -v 读取了 项目根目录下的config/config.js配置文件，文件中引用了antd-pro-merge-less模块导致。
所以顺序应该是先 npm i  再 umi -v， 或者去掉 umi -v

**Comment by xiaohuoni** [comment]
那你描述问题的时候，可以详细点，比较随意的，会直接被关了

**Comment by Evan-Future** [comment]
> 那你描述问题的时候，可以详细点，比较随意的，会直接被关了

这并不是随意的问题，是因为之前遇到时并没有找到问题所在，所以才来求助。后续找到原因了知道了解决方案，所以来做个反馈，希望对后续遇到的朋友可以给个帮助
