### ISSUE TITLE
ant-design-pro怎么加入多标签导航

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/ant-design-pro#2850]
ant-design-pro怎么加入多标签导航？公司业务急需，恳请告知，谢谢

**Comment by RivanLuo** [comment]
> pro不会加的。你可以看看历史issue

首先多页签能不能做？其次做了会有问题吗？再次，pro不会加，能给我合理的解释吗？
目前确实是很多用户都有类似的需求。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/220

**Comment by gclsoft** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/README.zh-CN.md
为什么不支持呢? vue-element-admin就支持啊

**Comment by Fengly0503** [comment]
公司项目也有多标签功能的需求，看了各位的实现感觉还是不太满足自己的需求，就自己写了一个基于Ant design pro 4 + 路由拦截的方案，解决了一些标签切换、关闭、路由关联、相同类型不同数据详情页、url直接访问指定标签等问题，有兴趣的兄弟可以瞅瞅 [多标签实现地址](https://github.com/Fengly0503/ant_pro_tabs)

![demo-1](https://user-images.githubusercontent.com/7435119/77248172-5cf73d80-6c72-11ea-9c71-202cc79a6450.jpg)
![demo-2](https://user-images.githubusercontent.com/7435119/77248174-5ec10100-6c72-11ea-8898-a01b1915e2a8.jpg)
![demo-3](https://user-images.githubusercontent.com/7435119/77248175-5f599780-6c72-11ea-9b5b-ab30f9d46908.jpg)
