### ISSUE TITLE
NoticeIcon > Clear tab items > Broken

### ISSUE THREAD

**Issue by michaelpeterlee** [ant-design/ant-design-pro#2851]
Version
2.1.1

Environment
OSX 10.13.6 > Chrome 70.0.3538.77

Reproduction link
https://pro.ant.design/components/NoticeIcon/#scaffold-src-components-NoticeIcon-demo-popover

Steps to reproduce
In your documentation the 'Clear *' links at bottom of tabs do not work, present 'undefined' in the console. It also behaves like this when we implement this component standalone ant-design-pro 2.1.1. with antd 3.9.3. It worked in ant-design-pro 1.4.4.

What is expected?
myCallback = (tabName) =>{console.log(tabName);}
<NoticeIcon ... onClear={myCallback} />

tabName should display in console.

What is actually happening?
const myCallback = (tabName) =>{console.log(tabName);};
<NoticeIcon ... onClear={myCallback} />

undefined is displayed in console.

We upgraded the standalone component from 1.4.4 to 2.1.1. to take advantage of the new 'bell' argument, and saw this regression.

**Comment by jakubknejzlik** [comment]
I think this should be as easy as this:
https://github.com/ant-design/ant-design-pro/compare/master...jakubknejzlik:patch-1

**Comment by chenshuai2144** [comment]
fix in 2.2.0

**Comment by michaelpeterlee** [comment]
This issue still persists in 2.2.1

**Comment by imhele** [comment]
> I think this should be as easy as this:
> [master...jakubknejzlik:patch-1](https://github.com/ant-design/ant-design-pro/compare/master...jakubknejzlik:patch-1)

This has already been handled in [index.js#L94](https://github.com/jakubknejzlik/ant-design-pro/blob/master/src/components/NoticeIcon/index.js#L94)

**Comment by chenshuai2144** [comment]
@imhele PR 一个？

**Comment by imhele** [comment]
> @imhele PR 一个？

官网的示例是直接在 https://github.com/ant-design/ant-design-pro/blob/master/src/components/NoticeIcon/demo/popover.md 改吗？

**Comment by chenshuai2144** [comment]
对的。改了重新部署就好了
