### ISSUE TITLE
windows部署pro有问题

### ISSUE THREAD

**Issue by RivanLuo** [ant-design/ant-design-pro#2852]
在windows上部署有问题？会报错，linux正常

报错入如下图
![error](https://user-images.githubusercontent.com/13898695/48523727-9ff41480-e8b8-11e8-8aa9-53856e2b04de.png)

**Comment by jinyaqiao1102** [comment]
这个问题没有遇到过，建议你还是检查下你代码，这种问题一般都是自己写的代码导致的

**Comment by xiaohuoni** [comment]
可以给个demo，看看

**Comment by RivanLuo** [comment]
> 可以给个demo，看看

没有可用demo，没有mock数据，需要后台接口

**Comment by shaopeng1** [comment]
那你也要搞个可以重现的地方，或者你能知道是哪里问题，不然没有办法定位的
