### ISSUE TITLE
线上环境国际化在指定电脑上不生效

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-pro#2853]
1. 在其他电脑上正常访问，手机上也正常访问
2. windows Chrome 70.0

![image](https://user-images.githubusercontent.com/26456842/48525121-dc763f00-e8bd-11e8-96ad-671cc5a8e0c6.png)

**Comment by jx-zyf** [comment]
火狐可以正常访问

version: 2.1.1

**Comment by chenshuai2144** [comment]
地址》

**Comment by jx-zyf** [comment]
现在可以正常访问了，是浏览器语言设置的原因。之前默认是英语，感谢回复

![image](https://user-images.githubusercontent.com/26456842/48535646-fed08280-e8e6-11e8-8394-1b350db0dac1.png)

**Comment by jx-zyf** [comment]
```js
      locale: {
        enable: true, // default false
        default: 'zh-CN', // default zh-CN
        baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
      },
```
应该是baseNavigator配置的原因
