### ISSUE TITLE
jest-puppeteer找不到

### ISSUE THREAD

**Issue by Captain-G** [ant-design/ant-design-pro#2854]
This dependency was not found:

* jest-puppeteer in dll umi

To install it, you can run: npm install --save jest-puppeteer

**Comment by Pillar-Zhang** [comment]
我也遇到这个问题了 怎么都装不上

**Comment by Pillar-Zhang** [comment]
![image](https://user-images.githubusercontent.com/17920354/48526487-c9b23900-e8c2-11e8-845a-4322df4e9b95.png)

**Comment by chenshuai2144** [comment]
删除 node-modlue

**Comment by Captain-G** [comment]
@chenshuai2144 早就试过了，并没有解决

**Comment by yuquanwang** [comment]
我也遇到了

**Comment by zhilianbi520** [comment]
同遇到。。。

**Comment by zhilianbi520** [comment]
同遇到。

**Comment by PascalSun** [comment]
缺了包，安装一下：
`npm install --save-dev jest-puppeteer puppeteer jest`

**Comment by Hyg900928** [comment]
我也遇到了这个问题，反复无解， yarn  npm  cnpm  都试过了， 一运行 npm start 就报错

**Comment by PascalSun** [comment]
> 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错

试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 jest

**Comment by Hyg900928** [comment]
> > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> 
> 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 je

> > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> 
> 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 jest

嗯嗯， 好了， 已经解决

**Comment by zhilianbi520** [comment]
puppeteer 安装不成功。。报错

**Comment by zhilianbi520** [comment]
> > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> 
> 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 jest
装 puppeteer 报错//

**Comment by zhilianbi520** [comment]
> > > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> > 
> > 
> > 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 je
> 
> > > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> > 
> > 
> > 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 jest
> 
> 嗯嗯， 好了， 已经解决

你安装成功了？啥环境啊。

**Comment by PascalSun** [comment]
> > > > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> > > 
> > > 
> > > 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 je
> > 
> > 
> > > > 我也遇到了这个问题，反复无解， yarn npm cnpm 都试过了， 一运行 npm start 就报错
> > > 
> > > 
> > > 试试我说的那个，一共缺三个包，那个提示只告诉你装了一个，还要装 puppeteer 和 jest
> > 
> > 
> > 嗯嗯， 好了， 已经解决
> 
> 你安装成功了？啥环境啊。

你这个显示是安装 chromium 失败，是不是网络问题？
那个还挺大的。。

**Comment by billychou** [comment]
jest-puppeteer puppeteer jest 这三个包都装一下就没问题了。
