### ISSUE TITLE
如果菜单是服务端获取的，如果实现国际化?

### ISSUE THREAD

**Issue by curry-wxj** [ant-design/ant-design-pro#2859]
服务端获取的菜单信息。 构成出菜单后。  还需要在locale文件中配置。 可数据是服务端获取的。有没有可以 动态添加 到locale中的方法。 可以直接把 服务端获取的数据 配置到locale文件中

**Comment by mushroomlb** [comment]
将本地选择的语言传到服务器，服务器做多语言返回结果

**Comment by chenshuai2144** [comment]
现在就是可以的，只要你返回 intl 的 id 就好了，{name:intlId }

**Comment by curry-wxj** [comment]
好的 谢谢~

**Comment by jiankian** [comment]
大神们 怎么动态设置左边导航菜单啊 只能写死在配置文件吗 异步服务器怎么获取怎么写

**Comment by songkeith** [comment]
可不可以给一个例子？
