### ISSUE TITLE
输入框加上默认validator思路探讨

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design-pro#286]
使用场景：不同页面间都需要使用IP输入框，希望为该输入框加上默认的validator的rules，减少代码，实现功能复用
代码实现如下：
`import checkIP from 'utils/rules'`
`<FormItem label="IP" key="ip" {...formItemLayout}>`
`{getFieldDecorator('ip', {`
`rules: [{ required: true, message: 'Please input your ip!' },{validator: checkIP}]`
`})(<Input />)}`
`</FormItem>`
如果希望在每个页面都使用IP输入框，就需要在每个页面都填上这些默认的rules，想过使用高阶组件默认为每个form加上ruleDecorator，然后在props里面取rules，但好像也不是很好，请问有别的思路么？
有没有什么实现方案能够做成这样：
`{getFieldDecorator('ip')(<InputIp />)}`
@afc163 希望能探讨一下这种在企业内部进行配置的通用场景

**Comment by WhatAKitty** [comment]
没啥必要，每个组件页面对于不同的输入框可能都有不同的业务需要，即不同的业务场景。默认对输入框做默认校验我觉得不合适，特别是某些输入框并不需要验证。

**Comment by sbyps** [comment]
@WhatAKitty 这里说的就是相同的输入，比如两个页面都是IP输入框或者email输入框，且必填

**Comment by sbyps** [comment]
[#5540](https://github.com/ant-design/ant-design/issues/5540)
这也是一种解决思路

**Comment by WhatAKitty** [comment]
你指的是通用Input组件吗？

**Comment by afc163** [comment]
可以用 ` {getFieldYourDecorator('ip')(<InputIp />)}` 这种 HOC 的思路去统一做一层封装，getFieldYourDecorator 里把 getFieldDecorator 直接封装掉。

**Comment by sbyps** [comment]
@afc163 
类似这样？
const InputIp = ({ form, index }) => {
  const options = {
    rules: [...],
  }
  return form.getFieldDecorator(index, options)(<Input />)
}
{InputIp({ form, index: 'index' })}

**Comment by WhatAKitty** [comment]
不过，我觉得有种过度封装的感觉

**Comment by sbyps** [comment]
就是不想在各个页面都重复写相同的validator

**Comment by swdenglian** [comment]
可以维护一份默认配置文件。其他组件的默认配置都可以维护在里面。

**Comment by afc163** [comment]
自己提成高阶组件就好。
