### ISSUE TITLE
目前pro仓库最新的代码(e876ec2) 编译后,dist/index.html,无法正常访问

### ISSUE THREAD

**Issue by jaysg** [ant-design/ant-design-pro#2860]
1.git clone
2.npm i
3.npm build
4.dist/index.html不能正常访问

![image](https://user-images.githubusercontent.com/28700250/48530240-c8d4d380-e8d1-11e8-97f0-6d2aa79fb855.png)

1.index.html中的引用路径缺少'.'     example:"/umi.js"  ==> "./umi.js"
2.index.html中包含了less的引用

发现了这两个问题,应该是改配置文件config/config.js,但是尝试着改了没达到预期的效果,希望能够得到帮助.

**Comment by afc163** [comment]
要放在根域名下。

**Comment by afc163** [comment]
@chenshuai2144 看看 umi 有没有自定义文件路径的方法。

**Comment by yutingzhao1991** [comment]
有 https://umijs.org/zh/config/#publicpath publicPath 这个配置。

**Comment by yanwenjia** [comment]
找到解决办法了没有

**Comment by chenshuai2144** [comment]
没有 http 服务，我们现在好像跑不起来。需要做个解决方案了

**Comment by xiaohuoni** [comment]
要起一个服务访问。

**Comment by yanwenjia** [comment]
http-server

**Comment by jaysg** [comment]
改hosts，加一条  127.0.0.1 xxx.xxx.xxx，
然后 nginx，修改配置 server =>root 指向本地目录 | listen 改成8000
然后访问xxx.xxx.xxx @yanwenjia 這是我目前的解决方案 你可以看看
@chenshuai2144 希望大佬可以拿出一个不用http服务的解决方案，新人太难搞这个

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1874

**Comment by kennylbj** [comment]
在config.js中添加2个配置：
```js
// config/config.js
history: 'hash'
publicPath: './',
```

**Comment by tnngo** [comment]
> 在config.js中添加2个配置：
> 
> ```js
> // config/config.js
> history: 'hash'
> publicPath: './',
> ```

verry good, tky.
