### ISSUE TITLE
npm run build failed on CentOS 7.3

### ISSUE THREAD

**Issue by royliudl** [ant-design/ant-design-pro#2863]
## 版本
- "name": "ant-design-pro", "version": "2.0.0"
- node
![image](https://user-images.githubusercontent.com/11811240/48541912-bde16980-e8f8-11e8-845d-90203de17b76.png)

## 问题
- npm run build 失败，且没有任何提示信息，仅输出Killed。
OS: CentOS 7.3
![image](https://user-images.githubusercontent.com/11811240/48532890-320e1400-e8dd-11e8-97de-a0f550e77bb6.png)
## 相关信息
- Mac系统下可以build成功。
- 已经区分大小写，使用了case-sensitive-paths-webpack-plugin插件。
- 安装依赖时有error出现，不知道与这个错误有没有关系？
[fsevents@^1.2.2] optional install error
![image](https://user-images.githubusercontent.com/11811240/48542567-765bdd00-e8fa-11e8-8f12-2479930d7577.png)

**Comment by chenshuai2144** [comment]
代码压缩的时候出了问题，是代码不规范吗？

**Comment by zhouhuiquan** [comment]
这个问题虽然我没有遇到过,但是我直接把官方代码git到服务器ubuntu,yarn装完依赖然后npm run build 也是卡在这里,好久没反应.

**Comment by chenshuai2144** [comment]
node 的版本呢？。

**Comment by royliudl** [comment]
> node 的版本呢？。

8.10.0

**Comment by royliudl** [comment]
> 代码压缩的时候出了问题，是代码不规范吗？
Mac下没问题，Mac下build的时候应该也进行代码压缩了吧？如果不规范，Mac下应该也有问题。安装依赖包的时候有错误发生，不知是否和这个错误有关？
请参考上面issue的相关描述
