### ISSUE TITLE
如何新增身份？比如默认的是user，admin，现在想增加身份ABC怎么做？

### ISSUE THREAD

**Issue by yanwenjia** [ant-design/ant-design-pro#2864]

**Comment by shaopeng1** [comment]
你找到user admin在哪加的就解决了

**Comment by yanwenjia** [comment]
> 你找到user admin在哪加的就解决了

这个也找不到奥，我只知道配置路由的时候有个authority: ['admin', 'user'],但是这个应该是当前路由允许进入的身份，我想知道的是整个系统的所有身份在哪里配置？

**Comment by chenshuai2144** [comment]
用户用一个身份，默认是 admin
['admin', 'user'] 是可以随意写的
