### ISSUE TITLE
打包生成的index.html 为什么还要引入外部资源

### ISSUE THREAD

**Issue by jassonxian** [ant-design/ant-design-pro#2866]
![image](https://user-images.githubusercontent.com/21199561/48534087-e27e1700-e8e1-11e8-9fe8-7b7ecdf28004.png)
![image](https://user-images.githubusercontent.com/21199561/48534107-edd14280-e8e1-11e8-8f66-3e10c8c58232.png)

**Comment by jassonxian** [comment]
已解决，感谢！

**Comment by zhongjiewu** [comment]
请问repo中为什么要用这一项外部引入？是为了做功能示范吗？

**Comment by zsl1549** [comment]
请问大佬你说的2处都注释了 还是会引入资源。
![image](https://user-images.githubusercontent.com/32888522/63223523-6fdff600-c1e9-11e9-9908-2e5623ac1d56.png)

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/63223532-969e2c80-c1e9-11e9-90e4-a9db82c8d456.png)
难受大哥
