### ISSUE TITLE
自动化部署,服务器打包出现问题

### ISSUE THREAD

**Issue by zhouhuiquan** [ant-design/ant-design-pro#2868]
在本地win7和mac打包没有问题,但是在服务器打包有问题,基本都是在46%-48%的样子

有时候报错的具体的代码的pages,有时候 停在这个这个位置
 webpack █████████████████████████ building modules (48%) 323/351 modules 28 active
  node_modules/@babel/runtime/helpers/interopRequireWildcard.js

感觉是依赖的问题,但是npm yarn pnpm cnpm 都试过了,全部都有问题,pnpm也从来没有打包成功过;
用yarn装依赖有时候没有任何问题,但是打包还是失败

对了,服务器是centOS 和 ubuntu 都试过了.基本是一样的问下

node版本也没问题都在8.12之后,用过node10,node11 都有问题.

**Comment by chenshuai2144** [comment]
https://github.com/vuejs/vue-cli/issues/716
找到了这个，你试一试

**Comment by zhouhuiquan** [comment]
> [vuejs/vue-cli#716](https://github.com/vuejs/vue-cli/issues/716)
> 找到了这个，你试一试

这个我看了下,应该不是一个问题,那个dev应该是开发模式的问题.
每次也都删了node_modules文件夹

**Comment by zhouhuiquan** [comment]
找到了问题所在,是路径大小写错误.router中有个组件的名开头误写成了小写.还有个文件夹名把小写写成大写,代码中引用的路径又是小写..

说个题外话,这个大小写问题同样会影响git的版本控制.
