### ISSUE TITLE
input跟select高度有px误差

### ISSUE THREAD

**Issue by jassonxian** [ant-design/ant-design-pro#2870]
![image](https://user-images.githubusercontent.com/21199561/48538780-59baa780-e8f0-11e8-8b70-db0fead18351.png)
![image](https://user-images.githubusercontent.com/21199561/48538821-748d1c00-e8f0-11e8-87a1-0b8f573a9ce9.png)

**Comment by jassonxian** [comment]
这种情况必须一行用Row包裹吗

**Comment by chenshuai2144** [comment]
建议这种的外面都包一个固定高度的 box
