### ISSUE TITLE
deploy problem built with umi

### ISSUE THREAD

**Issue by epochchaser** [ant-design/ant-design-pro#2871]
Hi.
i just built scaffolded ant-design-pro project from here.
and i tried build then got /dist folder with index.html, umi.css, umi.js, chunks.

and i typed 'node ./dist/umi.js/'
but it's not working with this message.
"ReferenceError: window is not defined"

i think there is problem when bundle apps.
how do i solve it?

**Comment by sontx** [comment]
Hi @epochchaser,
You can try with `serve`: `npm i -g serve` and then cd to the dist dir and run `serve`

**Comment by epochchaser** [comment]
> Hi @epochchaser,
> You can try with `serve`: `npm i -g serve` and then cd to the dist dir and run `serve`

thank you. it is working well.
but when i run app with server, there is 404 error almost every request.

**Comment by chenshuai2144** [comment]
you need  service！
look https://preview.pro.ant.design/api/currentUser

**Comment by thangphan205** [comment]
I have similar issue with @epochchaser .
I use external API, and config proxy in config/config.js
Everything works fine when I run ant design pro with : npm run start:no-mock
But when I deploy in production:
```
npm run build
serve -s dist
```
- when I access: localhost:5000/user/login : It's OK, but the login request do not send to API server. It uses API on localhost.
- with nginx, when I access my domain: It shows nothing. It seems nginx cannot find the right directory.
Please help.
![ant-design-pro](https://user-images.githubusercontent.com/17825728/54020176-b43d8380-41bf-11e9-9013-363c1f776af7.png)

**Comment by dliracogent** [comment]
I have the similar issue, some solution ?

**Comment by dliracogent** [comment]
> I have similar issue with @epochchaser .
> I use external API, and config proxy in config/config.js
> Everything works fine when I run ant design pro with : npm run start:no-mock
> But when I deploy in production:
> 
> ```
> npm run build
> serve -s dist
> ```
> 
> * when I access: localhost:5000/user/login : It's OK, but the login request do not send to API server. It uses API on localhost.
> * with nginx, when I access my domain: It shows nothing. It seems nginx cannot find the right directory.
>   Please help.
>   ![ant-design-pro](https://user-images.githubusercontent.com/17825728/54020176-b43d8380-41bf-11e9-9013-363c1f776af7.png)

do you have any solution ?

**Comment by xXAvoraXx** [comment]
+++
