### ISSUE TITLE
Less file during build

### ISSUE THREAD

**Issue by bwoutersvaa** [ant-design/ant-design-pro#2873]
During the build of our AntD pro project de dist folder includes a color.less file. 
This file contains the default Pro color "#1890ff" and not our custom color specified in the defaultSettings.js

There is a umi.css and a couple other css files which do include our custom color code. But every style is overwritten by the color.less file.

How is this possible and what can we do to fix it? We use the npm run build script to build our production environment. 

![image](https://user-images.githubusercontent.com/45063312/48543275-74c1f300-e8c1-11e8-8458-06546158d0d8.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/77357aeefefed3460b1ed07bb050c992f078dad4
