### ISSUE TITLE
建议官方加点详细的注释，对我们这些菜鸟来说，看起来没那么空难

### ISSUE THREAD

**Issue by yanwenjia** [ant-design/ant-design-pro#2877]
如题

**Comment by a854363956** [comment]
@chenshuai2144  关于ant pro v2 的路由这一块,还是不是很理解，我在路由里面添加页面，但是我无法进行修改为动态路由，以及动态菜单，这些让我很困惑。虽然在issues里面提到过很多解决方案，但是一直没有得到官网的支持。   
> 如果可以的话，我希望能够详细的介绍下整个框架

**Comment by zhangjie2012** [comment]
是有这个问题，1.0 之前的 menu 跟 router 是分开的，2.0 之后全部合并到了 `router.config.js`，业务稍微复杂一些，简直就是噩梦

**Comment by 8pig** [comment]
> @chenshuai2144 关于ant pro v2 的路由这一块,还是不是很理解，我在路由里面添加页面，但是我无法进行修改为动态路由，以及动态菜单，这些让我很困惑。虽然在issues里面提到过很多解决方案，但是一直没有得到官网的支持。
> 
> > 如果可以的话，我希望能够详细的介绍下整个框架， 比如国际化，菜单，路由等等。。。

https://pro.ant.design/docs/getting-started

**Comment by LKCheng** [comment]
哈哈，还是感觉v1版本清楚点，用了umi的话，感觉很多工程都自动化了。

**Comment by a854363956** [comment]
@LKCheng  其实只是学习成本上升,用了UMI后更加简洁了,只是文档似乎没有跟上,例子比较少,只能靠自己摸索,其实大部分都还是比较萌新的ヾ(=ﾟ･ﾟ=)ﾉ喵♪
