### ISSUE TITLE
This relative module was not found:  * ../Forms/Test in ./src/pages/.umi/router.js

### ISSUE THREAD

**Issue by jiangwr** [ant-design/ant-design-pro#2879]
在Forms文件夹下新建Test文件夹，component修改为 './Forms/Test'有如下报错
![kr15gxe2o t7d ovy xkat](https://user-images.githubusercontent.com/19362571/48596109-73143000-e992-11e8-9bb8-5feac32c7cb2.png)
![3hf k nds q0bbo 8qh e](https://user-images.githubusercontent.com/19362571/48596124-8921f080-e992-11e8-93a6-96f99bb3966c.png)

**Comment by Jiangwr** [comment]
> Forms/Test 应该基于 page

component: '../Forms/StepForm'是正常编译的，此时StepForm和Test不是都处于Forms文件夹下嘛

**Comment by Jiangwr** [comment]
> Test是文件夹呀。而且尽量不要用这种看起来像是关键字的名字

嗯，谢谢命名的提醒，但是StepForm不也是一个文件夹嘛，没明白什么区别

**Comment by chenshuai2144** [comment]
StepForm 里面会有个 index.js的文件

**Comment by Jiangwr** [comment]
> StepForm 里面会有个 index.js的文件

非常感谢
