### ISSUE TITLE
雷达图在特定的数据下会出现js浮点数计算错误并显示如660.00000000000000001

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design-pro#2881]
版本：Ant Design Pro V2
测试数据：
const data = [
  { name: '名称1', label: '列表1', value: 0 },
  { name: '名称1', label: '列表2', value: 0 },
  { name: '名称1', label: '列表3', value: 0 },
  { name: '名称1', label: '列表4', value: 0 },
  { name: '名称1', label: '列表5', value: 167 },
  { name: '名称2', label: '列表1', value: 0 },
  { name: '名称2', label: '列表2', value: 0 },
  { name: '名称2', label: '列表3', value: 0 },
  { name: '名称2', label: '列表4', value: 0 },
  { name: '名称2', label: '列表5', value: 90 },
  { name: '名称3', label: '列表1', value: 1 },
  { name: '名称3', label: '列表2', value: 0 },
  { name: '名称3', label: '列表3', value: 0 },
  { name: '名称3', label: '列表4', value: 0 },
  { name: '名称3', label: '列表5', value: 609 },
];
问题组件：Radar
问题描述：
雷达图坐标轴的数字，虽然传递的都是整数，但是却出现了
如660.00000000000000001，440.00000000000000006，220.00000000000000003这样的刻度，
影响了图表的美观性。
问题解决方法：
经过一系列测试，是当默认的tickCount，tickCount  = 4时才会发生这个问题。
比如当tickCount修改为0或者5时，坐标轴正常显示。

**Comment by tianqihang-public** [comment]
这个问题我Fork了最新版的BizCharts后，按照Ant Design Pro的Radar组件修改其Demo，成功复现。
可能是BizCharts的Chart组件的问题。但是可以通过修改Ant Design Pro组件参数的方式避免这个问题。
建议把默认的tickCount修改为5。
