### ISSUE TITLE
router.config.js中添加权限，别的权限的人还是能够访问到页面！

### ISSUE THREAD

**Issue by adam0420** [ant-design/ant-design-pro#2885]
我给dashboard添加了admin权限可以访问。但user用户可以通过
http://localhost:8000/dashboard/myroute/myroute1
访问到页面

`

      // dashboard
      { path: '/', redirect: '/dashboard/analysis' },
      {
        path: '/dashboard',
        name: 'dashboard',
        icon: 'dashboard',
        authority: ['admin'],
        routes: [
          {
            path: '/dashboard/analysis',
            name: 'analysis',
            component: './Dashboard/Analysis',
          },
          {
            path: '/dashboard/monitor',
            name: 'monitor',
            component: './Dashboard/Monitor',
          },
          {
            path: '/dashboard/workplace',
            name: 'workplace',
            component: './Dashboard/Workplace',
          },
          {
            path: '/dashboard/myroute',
            name: 'myroute',  
            routes: [
              {
                path: '/dashboard/myroute',
                redirect: '/dashboard/myroute/myroute1',
              },
              {
                path:'/dashboard/myroute/myroute1',
                component: './Dashboard/Workplace',
              },
              {
                path:'/dashboard/myroute/myroute2',
                component: './Dashboard/Workplace',
              },
            ]
          },
        ],
      },
`

**Comment by chenshuai2144** [comment]
最新的解决了这个问题，权限原来是不继承，有个 pr 帮忙解决了

**Comment by adam0420** [comment]
> 最新的解决了这个问题，权限原来是不继承，有个 pr 帮忙解决了

怎么解决的？我下载的最新代码修改的。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/2861
