### ISSUE TITLE
如何缓存路由跳转前的页面状态

### ISSUE THREAD

**Issue by sansx** [ant-design/ant-design-pro#2886]
我现在有个多页列表，
当我在第五页点击跳转到详情页之后，再返回之前的列表页，页数回到了第一页。
因为这种类型的页面很多，所以想请问一下有什么简单的解决办法。
是否有一个类似vue-router的keep-alive组件，可以在返回之前页面后保持第五页的状态。

**Comment by chenshuai2144** [comment]
存在 redux里面来就好了
