### ISSUE TITLE
在ant-design-pro里面怎么接收和保存后端返回的JWT token？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2887]
在ant-design-pro里面怎么接收和保存后端返回的JWT token？在哪个文件里面写代码，有示例可以看看吗？
目前ant-design-pro官方示例使用的什么认证方式？

**Comment by chenshuai2144** [comment]
sessionStorage 应该是个很不错的方案

**Comment by yesmeck** [comment]
https://www.zhihu.com/question/301253397/answer/547887208
