### ISSUE TITLE
npm run build 默认生成的文件是这样的么

### ISSUE THREAD

**Issue by songhua-river** [ant-design/ant-design-pro#2889]
2018/11/16  17:13             1,616 1.async.js
2018/11/16  17:13             2,267 11.async.js
2018/11/16  17:13             1,230 11.chunk.css
2018/11/16  17:13            12,213 12.async.js
2018/11/16  17:13             1,814 12.chunk.css
2018/11/16  17:13             7,216 13.async.js
2018/11/16  17:13               983 13.chunk.css
2018/11/16  17:13             1,385 14.async.js
2018/11/16  17:13               485 14.chunk.css
2018/11/16  17:13            42,525 15.async.js
2018/11/16  17:13            13,957 15.chunk.css
2018/11/16  17:13            19,358 16.async.js
2018/11/16  17:13             5,411 16.chunk.css
2018/11/16  17:13            10,333 17.async.js
2018/11/16  17:13             1,512 17.chunk.css
2018/11/16  17:13             8,213 18.async.js
2018/11/16  17:13             6,707 18.chunk.css
2018/11/16  17:13             6,494 19.async.js
2018/11/16  17:13             1,493 2.async.js
2018/11/16  17:13             1,532 20.async.js
2018/11/16  17:13             4,529 21.async.js
2018/11/16  17:13             3,032 22.async.js
2018/11/16  17:13             2,198 23.async.js
2018/11/16  17:13            16,048 24.async.js
2018/11/16  17:13               649 24.chunk.css
2018/11/16  17:13            18,250 25.async.js
2018/11/16  17:13             1,321 25.chunk.css
2018/11/16  17:13             8,988 26.async.js
2018/11/16  17:13             4,598 26.chunk.css
2018/11/16  17:13             3,822 27.async.js
2018/11/16  17:13             2,592 27.chunk.css
2018/11/16  17:13             1,626 28.async.js
2018/11/16  17:13             6,162 29.async.js
2018/11/16  17:13               542 29.chunk.css
2018/11/16  17:13             2,202 3.async.js
2018/11/16  17:13             4,432 30.async.js
2018/11/16  17:13             5,537 31.async.js
2018/11/16  17:13             4,251 32.async.js
2018/11/16  17:13               122 32.chunk.css
2018/11/16  17:13            10,782 33.async.js
2018/11/16  17:13               917 33.chunk.css
2018/11/16  17:13             4,474 34.async.js
2018/11/16  17:13             2,145 35.async.js
2018/11/16  17:13               471 36.async.js
2018/11/16  17:13               471 37.async.js
2018/11/16  17:13             1,662 38.async.js
2018/11/16  17:13               151 38.chunk.css
2018/11/16  17:13             5,895 39.async.js
2018/11/16  17:13             1,862 39.chunk.css
2018/11/16  17:13             1,107 4.async.js
2018/11/16  17:13             1,899 40.async.js
2018/11/16  17:13               189 40.chunk.css
2018/11/16  17:13             2,849 41.async.js
2018/11/16  17:13             1,613 42.async.js
2018/11/16  17:13             3,114 43.async.js
2018/11/16  17:13             1,977 43.chunk.css
2018/11/16  17:13             8,768 44.async.js
2018/11/16  17:13             2,435 44.chunk.css
2018/11/16  17:13             3,095 45.async.js
2018/11/16  17:13             2,154 46.async.js
2018/11/16  17:13             1,728 47.async.js
2018/11/16  17:13               467 48.async.js
2018/11/16  17:13               777 5.async.js
2018/11/16  17:13               676 6.async.js
2018/11/16  17:13             1,304 7.async.js
2018/11/16  17:13               654 8.async.js
2018/11/16  17:13             1,010 9.async.js
2018/11/16  17:13             2,854 asset-manifest.json
2018/11/16  17:13             2,849 favicon.png
2018/11/16  17:13    <DIR>          icons
2018/11/16  17:13               620 index.html
2018/11/16  17:13               278 manifest.json
2018/11/16  17:13             5,917 precache-manifest.3de38f820dc9331be0a9ae24505402cd.js
2018/11/16  17:13             6,611 pwacompat.min.js
2018/11/16  17:13             2,124 service-worker.js
2018/11/16  17:13            61,680 umi.css
2018/11/16  17:13         1,273,654 umi.js
2018/11/16  17:13         1,386,018 vendors.async.js
2018/11/16  17:13           308,478 vendors.chunk.css
2018/11/16  17:13    <DIR>          workbox-v3.6.3

**Comment by chenshuai2144** [comment]
开了代码分割就是这样的
