### ISSUE TITLE
b.exports antd-theme-webpack-plugin colors.less inline style issue 

### ISSUE THREAD

**Issue by ilanus** [ant-design/ant-design-pro#2891]
Inline style failing:

<img width="1315" alt="screenshot 2018-11-16 at 12 04 07" src="https://user-images.githubusercontent.com/9677898/48617937-13208800-e998-11e8-8bb8-d6a7ae3f52a0.png">

<img width="443" alt="screenshot 2018-11-16 at 12 07 57" src="https://user-images.githubusercontent.com/9677898/48618027-5aa71400-e998-11e8-9f42-ec7076f99207.png">

**Comment by ilanus** [comment]
Related: https://github.com/mzohaibqc/antd-theme-webpack-plugin/issues/16

**Comment by xiaohuoni** [comment]
Related:https://github.com/mzohaibqc/antd-theme-webpack-plugin/pull/20
