### ISSUE TITLE
npm install 一大堆警告正常么

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design-pro#2892]
npm WARN ajv-errors@1.0.0 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-dva-hmr@0.4.1 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-babel@4.0.3 requires a peer of rollup@>=0.60.0 <1 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-commonjs@9.2.0 requires a peer of rollup@>=0.56.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@1.10.0 (node_modules/puppeteer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: puppeteer@1.10.0 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

node版本 v10.13.0
npm版本 6.4.1

看着就难受。。。。 大家都是这样么？

之前用的是antd pro 1.x的项目 今天npm install的时候警告更多， start运行也报错。。 真是头大。

**Comment by chenshuai2144** [comment]
在中国是正常的。

**Comment by tulies** [comment]
> 在中国是正常的。

我也翻墙了啊。。。
