### ISSUE TITLE
ant-design-pro增加不用登录就能访问的页面，操作步骤是什么？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2899]
ant-design-pro增加不用登录就能访问的页面，操作步骤是什么？还没太梳理清楚各文件之间的衔接，所以请大佬指导一下。

**Comment by chenshuai2144** [comment]
参见权限 https://pro.ant.design/docs/authority-management-cn

**Comment by ybning** [comment]
@zwl1619 给你一个思路
src/router.js
![image](https://user-images.githubusercontent.com/3725612/49067568-68457f00-f25f-11e8-959a-2b08abba4a2c.png)
