### ISSUE TITLE
Module parse failed: Unexpected character '#' (1:0)

### ISSUE THREAD

**Issue by huangdou0204** [ant-design/ant-design-pro#2900]
环境：Node: 10.13.0 , umi: 2.2.6
删除 node_modules后重新install 也无效

 ERROR  Failed to compile with 1 errors                                                                                                          10:21:55 AM

 error  in ./node_modules/antd-pro-merge-less/index.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| /**
|  * 这个方法用来处理 css-modlue

 @ dll umi

npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by chenshuai2144** [comment]
干掉那个plugin.config.js

**Comment by huangdou0204** [comment]
> 干掉那个plugin.config.js

还是不行，删掉plygin.config.js， 在config.js注释掉相关配置，执行：rm -rf node_modules/ &&  npm install && npm start

还是一样报错，但是在linux上没问题，好诡异

**Comment by huangdou0204** [comment]
> antd-pro-merge-less 只在 plugin. config.js 中使用的

我的粗暴处理办法是把antd-pro-merge-less下的index.js文件第一行 #开头的删除就没问题了，但这不能解决根本问题，上面的方法我尝试了几次都无效，缓存都清除过

**Comment by xiaohuoni** [comment]
@huangdoe0204 有问题的是mac吗？

**Comment by huangdou0204** [comment]
> @huangdoe0204 有问题的是mac吗？

是的，Linux(CentOS7，Jenkins部署)没问题

**Comment by huangdou0204** [comment]
> @huangdou0204 你加个换行，验证一下行不行
> 
> ```js
> #!/usr/bin/env node
> 
> /**
>  * 这个方法用来处理 css-modlue
>  * 由于没有开源插件，所以自己撸了一个
>  */
> ```

我刚还原了代码今天又可以了，很诡异，不知道为啥，所以你这个换行也无法验证了，下次遇到我再试试

**Comment by chenshuai2144** [comment]
难道是字符串编码的不同？

**Comment by xiaohuoni** [comment]
可能的原因是，他的文件行尾系列是CRLF即*/r/n*,你编辑文件时候行尾系列是LF*/n*，所以就会出错。
所以一般在这个位置加一行空行，就不会有这个问题。

**Comment by varrant** [comment]
此问题又出现了。mac10.13.6。

**Comment by Evan-Future** [comment]
> 此问题又出现了。mac10.13.6。

尝试下上面的解决方式

**Comment by ityangyang** [comment]
> 此问题又出现了。mac10.13.6。

是不可以通过重新安装这个包antd-pro-merge-less来解决

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4289

这个可以解决掉所有的问题

**Comment by liangjz92** [comment]
> #4289
> 
> 这个可以解决掉所有的问题

没看明白，怎么解决的？今天遇到了一模一样的问题

**Comment by sunfutao** [comment]
一样的问题 mac 报这个错误，windows没问题，pro v2版本的
`error  in ./node_modules/pro-cli/src/pro.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
|
| 'use strict';

 @ dll umi

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vc-pay@1.0.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vc-pay@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Viamcc/.npm/_logs/2020-01-09T01_53_48_810Z-debug.log`

**Comment by CheKey30** [comment]
同样的问题，换行没用，重装也没用，mac系统，报错文件是 ./node_modules/netlify-lambda/bin/cmd.js,详情https://github.com/ant-design/ant-design-pro/issues/7301

**Comment by CheKey30** [comment]
已经解决，#4289有用
