### ISSUE TITLE
关于插件 antd-theme-webpack-plugin 中 hoek 插件的风险提示

### ISSUE THREAD

**Issue by sunguoxing0628** [ant-design/ant-design-pro#2901]
**版本**

Ant Design Pro `2.1.1`

**开发环境**

`macOS; Google Chrome,Safari`

**问题**

使用`Ant Design Pro`的项目中运行`npm audit`，提示`hoek`插件`Prototype pollution`风险，推荐更新到`5.0.3`或以上，参考[NPM](https://www.npmjs.com/advisories/566)和[versions](https://www.npmjs.com/advisories/566/versions)

> ![image](https://user-images.githubusercontent.com/27573161/48682754-edd48980-ebe4-11e8-84f0-4f3c5edb6245.png)
> ![image](https://user-images.githubusercontent.com/27573161/48682763-f6c55b00-ebe4-11e8-8278-f6c4e66641be.png)
> ![image](https://user-images.githubusercontent.com/27573161/48682770-fdec6900-ebe4-11e8-8e2a-647a19a48230.png)
> ![image](https://user-images.githubusercontent.com/27573161/48682776-05137700-ebe5-11e8-8e14-3e1135a81670.png)
>

**Comment by chenshuai2144** [comment]
https://github.com/mzohaibqc/antd-theme-webpack-plugin
