### ISSUE TITLE
按需加载右侧页面组件的问题（仅仅需要右侧页面独立组件，其他的都不需要）

### ISSUE THREAD

**Issue by ctq123** [ant-design/ant-design-pro#2904]
![image](https://user-images.githubusercontent.com/12124169/48692132-e7a7d280-ec0f-11e8-829c-746a49d40f2e.png)

比如上图，我只需要红色方框中的内容组件，不需要头部组件，有没有什么方法，比如在路径加个什么参数可以加载我所需的内容组件或者隐藏头部组件

解决需求：我们系统的页面内嵌入其他的系统中

**Comment by a854363956** [comment]
@ctq123 我不知道你为什么要这样做,你可以设置css "ant-layout-header" visibility为none 
但是我更加推荐的方式是  
设置src/defaultSettings.js  
```js
{
  "navTheme": "dark",
  "primaryColor": "#1890FF",
  "layout": "topmenu",
  "contentWidth": "Fluid",
  "fixedHeader": true,
  "autoHideHeader": true,
  "fixSiderbar": false,
  "collapse": true
}
```  
> 设置autoHideHeader=true

**Comment by ctq123** [comment]
@a854363956 
首先非常感谢你的及时回答，我试了下，但实际结果似乎与我预期的结果有点出入，如图
![image](https://user-images.githubusercontent.com/12124169/48693860-b03c2480-ec15-11e8-9b77-4f6abfe3254a.png)
 
**实际结果：**
设置autoHideHeader=true
只能在我将滚动条下拉到一定的程度后，才自动隐藏头部

**预期结果：**
点击这个菜单的时候，页面出来的时候，就已经隐藏头部
（点击动作由外部系统执行，直接调用这个路由URL）

实际业务场景：
假设我们新的系统基于Ant Design Pro脚手架上搭建的话，我们系统的某些页面会内嵌入其他系统，其他系统只需展示我们系统的内容页Body，不需要展示我们系统的头部Header，因此才有这个奇葩的需求

**Comment by ctq123** [comment]
在config/router.config.js 新建一个页面，如同../layouts/UserLayout 一样
这种方式可以解决，谢谢~
