### ISSUE TITLE
如果删除菜单中的权限判断，你们觉得如何？

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#2910]
@afc163 @chenshuai2144 @yutingzhao1991 
我想删除菜单里面的**Authorized={Authorized}**，用类似isShow属性，替代。
这里的Authorized是不是只是为了判断子菜单是否显示？还是说有其他的考虑。
现在的Authorized是从最外面往子组件传参，传了三次，到BaseMenu里面对菜单项做了一个过滤判断。
想着如果把这个判断移到最外层，是不是会好管理一点？
感觉将菜单和权限解绑的话，处理动态路由，是不是会轻松一点？
你们觉得如何？

**Comment by ibmsoft** [comment]
是不是就支持动态权限数据从后台获取了？

**Comment by xiaohuoni** [comment]
@ibmsofy 可以参考https://github.com/ant-design/ant-design-pro/pull/2928 正在看看有没有更好的设置方法。
