### ISSUE TITLE
手机端菜单样式 bug

### ISSUE THREAD

**Issue by yanhao98** [ant-design/ant-design-pro#2914]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/37316281/48747752-5720cf00-ecaf-11e8-9698-da7423ad7f37.png">
亮色风格的 logo 的 div 的 box-shadow 样式应该为 

`box-shadow: 0px 1px 0 0 #e8e8e8;`

**Comment by chenshuai2144** [comment]
欢迎 pr

**Comment by afc163** [comment]
@yanhao98 ❓

**Comment by yanhao98** [comment]
> @yanhao98 ❓

???

**Comment by afc163** [comment]
这个问题应该还没解决。

**Comment by imhele** [comment]
@yanhao98 检查一下这里的 overflow 有没有生效

![image](https://user-images.githubusercontent.com/32428655/50044679-456df400-00c2-11e9-9574-a58435084c5e.png)

**Comment by yanhao98** [comment]
> @yanhao98 检查一下这里的 overflow 有没有生效
> 
> ![image](https://user-images.githubusercontent.com/32428655/50044679-456df400-00c2-11e9-9574-a58435084c5e.png)

现在的版本最新代码生效了的。
但是还是应该是 `0px 1px 0 0 `，x 坐标不应该偏移？不然左边会空1px。
或者是border-bottom？
<img width="449" alt="image" src="https://user-images.githubusercontent.com/37316281/50062362-b8ba5780-01e1-11e9-8dc7-f1dc49a406d5.png">
