### ISSUE TITLE
mac按步骤，启动失败

### ISSUE THREAD

**Issue by wangchao117** [ant-design/ant-design-pro#2915]
chaodeMacBook-Pro:ant-design-pro chaowang$ npm start

> ant-design-pro@2.1.1 start /Volumes/MyFiles/Coding/MyGit/ant-design-pro
> cross-env APP_TYPE=site umi dev

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ant-design-pro@2.1.1 start: `cross-env APP_TYPE=site umi dev`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ant-design-pro@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chaowang/.npm/_logs/2018-11-20T03_36_18_479Z-debug.log

node版本10.13.0

**Comment by afc163** [comment]
你没按步骤，漏了 npm install 安装。

**Comment by wangchao117** [comment]
我有npm install,Mac上不行，但在win上没问题

**Comment by afc163** [comment]
用 cnpm 安装试试，应该是安装过程网络有问题。

**Comment by gaoqiang19514** [comment]
新来的同事的mac，遇到跟你一样的问题，怎么解决的？

**Comment by xiaohuoni** [comment]
@gaoqiang19514 确认插件都正确安装就好，yarn，科学上网啥的，尝试以下

**Comment by lipichang** [comment]
请问有解决吗 macos不行啊 还是报错
