### ISSUE TITLE
如何根据后端接口返回的菜单动态加载路由呢

### ISSUE THREAD

**Issue by xiayu1986** [ant-design/ant-design-pro#2916]
在使用ant pro的过程中发现动态设置菜单是可以，但是仍然可以访问到左侧菜单中未显示(想通过权限做控制)的页面，目前页面的访问权限只控制到了角色这个维度，实际生产环境的需求是角色+用户，不同的角色菜单权限不同，不同的账号权限也不一样，如果有遇到跟我一样问题的烦请支个招。

**Comment by yemaozi5518** [comment]
是在basiclayout组件 的  siderMenu 页面渲染的菜单吗？
如果是，就在componentDidMount  dispatch 的 callback里重新设置setState{menuData : response.menuData}
甚至在 个人设置页的 Info.js 组件可以控制，页面菜单的显示

**Comment by yemaozi5518** [comment]
不好意思，我的菜单不是从后端读的，是在route.config 里读的，根据后台数据，限制或者不渲染特定模块的功能

**Comment by netbird** [comment]
初次使用 本来想再global里面添加菜单的内容。然后在某个位置添加初始化逻辑，发现不太靠前。初始化面包屑的地方有问题。后来在最前面index.html里面 直接由后台程序返回。然后修改BasicLayout.js里面的菜单的地方。即document.ejs
```
      const menuTree = <?php echo json_encode($menu_data); ?>; 
     // const menuTree = [];  // test env
      const visitPermissions = [];
```

在具体功能页面 进入没有关系。具体功能页面的所有数据接口，在server端都有验证权限。

**Comment by xiaohuoni** [comment]
@xiayu1986 @netbird 看看https://github.com/ant-design/ant-design-pro/pull/2928

**Comment by zuohe** [comment]
> 不好意思，我的菜单不是从后端读的，是在route.config 里读的，根据后台数据，限制或者不渲染特定模块的功能

你好,请问一下你是怎么实现根据后台数据不渲染指定模块呢
