### ISSUE TITLE
windows下编译正常，放在服务器上编译就报错，大小写的方法试了没用

### ISSUE THREAD

**Issue by yigu** [ant-design/ant-design-pro#2918]
`0 info it worked if it ends with ok
1 verbose cli [ '/var/tmp/node-v8.12.0-linux-x64/bin/node',
1 verbose cli   '/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.1.1~prebuild: ant-design-pro@2.1.1
6 info lifecycle ant-design-pro@2.1.1~build: ant-design-pro@2.1.1
7 verbose lifecycle ant-design-pro@2.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.1.1~build: PATH: /var/tmp/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/jenkins/jenkins_home/workspace/homepage.front.prod/node_modules/.bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle ant-design-pro@2.1.1~build: CWD: /data/jenkins/jenkins_home/workspace/homepage.front.prod
10 silly lifecycle ant-design-pro@2.1.1~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.1.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.1.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.1.1 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/var/tmp/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/var/tmp/node-v8.12.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ant-design-pro@2.1.1
15 verbose cwd /data/jenkins/jenkins_home/workspace/homepage.front.prod
16 verbose Linux 3.10.0-862.3.3.el7.x86_64
17 verbose argv "/var/tmp/node-v8.12.0-linux-x64/bin/node" "/bin/npm" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.1.1 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by messi2094** [comment]
请问问题解决了吗？
