### ISSUE TITLE
登陆页面提示为英文？

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design-pro#2921]
翻了下login组件，只有个rules=>object[]，加了个
[ { required: true,message: '请输入用户名！'}],
好像也无效的？

**Comment by chenshuai2144** [comment]
切换一下语言。

**Comment by Veigar-C** [comment]
语言是zh-CN没错了，菜单都是中文的

**Comment by chenshuai2144** [comment]
感觉是 rule 被覆盖了，修改一下代码试试

**Comment by Veigar-C** [comment]
是有国际化的吗，我翻了翻Login组件，在components/Login/map.js，rules下的message是英文的
