### ISSUE TITLE
如何实现less以模块的方式导入？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#2923]
在pro中调用样式时，像一个对象一样,如下
```
import styles from './index.less'

<div className={styles.name}></div>
```
这个是怎么实现的？我在使用create-react-app时，只能写class名才管用，上面的写法不管用；
如何像pro中的这种方式调用呢？是装了什么插件吗？
```
import styles from './index.less'

<div className="name"></div>
```

**Comment by dengfuping** [comment]
[css-modules](http://www.ruanyifeng.com/blog/2016/06/css_modules.html)
