### ISSUE TITLE
color，background  这些属性会被覆盖。

### ISSUE THREAD

**Issue by GGwujun** [ant-design/ant-design-pro#2931]
![image](https://user-images.githubusercontent.com/17949342/48814842-5eabab00-ed77-11e8-935e-6eafdee83458.png)

图片路径找的还是assets目录

**Comment by chenshuai2144** [comment]
为什么会有重复的？

**Comment by GGwujun** [comment]
![image](https://user-images.githubusercontent.com/17949342/48823019-2e293880-ed9a-11e8-9775-ab06f2f45699.png)

在color.less中还是用的这种路径。
在打包的chunk.css中使用的是

![image](https://user-images.githubusercontent.com/17949342/48823086-6c265c80-ed9a-11e8-9afd-7ca379b7ad92.png)

**Comment by xiaohuoni** [comment]
@chenshuai2144 build的时候setting那些文件都不需要吧

**Comment by GGwujun** [comment]
其实看了下主要是如下处理造成：
![image](https://user-images.githubusercontent.com/17949342/48826405-2622c600-eda5-11e8-9715-f185606a15a8.png)

在生成ant-design-pro.less的时候采用的是antd-pro-merge-less插件，但是并没有对less里面的图片资源路径做处理
![image](https://user-images.githubusercontent.com/17949342/48826482-5cf8dc00-eda5-11e8-9a6a-5a2c6495d46c.png)

![image](https://user-images.githubusercontent.com/17949342/48827233-a9ddb200-eda7-11e8-91a8-db5c7af413f3.png)

直接把ant-design-pro.less中的less文件合并到color.less中了，然后直接放到index.html中，就把样式覆盖掉了。

**Comment by GGwujun** [comment]
![image](https://user-images.githubusercontent.com/17949342/48827488-5d46a680-eda8-11e8-8b54-41e17d0047bd.png)

感觉这个models不需要把 @chenshuai2144 @xiaohuoni

**Comment by chenshuai2144** [comment]
不需要换主题
