### ISSUE TITLE
提供 sofa 版本

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#2932]
类似 https://github.com/eggjs/egg-ant-design-pro

https://github.com/alipay/sofa-boot

**Comment by afc163** [comment]
目录划分合理的话，定期无脑拷贝应该就可以了。

**Comment by chenshuai2144** [comment]
sofa 没有目录划分的，应该是 build 成功之后拷贝进去吧

**Comment by xiaohuoni** [comment]
这个关了吗？
