### ISSUE TITLE
语雀上的《Ant Design 实战教程（beta 版）》好多“”符号

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2933]
语雀上的《Ant Design 实战教程（beta 版）》好多“”（口）符号，能解决吗？
https://www.yuque.com/ant-design/course

**Comment by zwl1619** [comment]
@yutingzhao1991 

![image](https://user-images.githubusercontent.com/13177997/48821191-38940400-ed93-11e8-9f70-c3889ebdd2b1.png)
其他页面也有。我用的chrome70，默认编码，没有修改编码相关的设置。

**Comment by chenshuai2144** [comment]
win操作系统吗？

**Comment by zwl1619** [comment]
@chenshuai2144  是的，win10

**Comment by chenshuai2144** [comment]
win10 的edge 和 ie11都是ok的，感觉是你的编码问题

**Comment by zwl1619** [comment]
好吧，那就不管它了。
用edge和360试了一下，edge有，360没有但仍有个空白符。
![snipaste_2018-11-24_15-10-12](https://user-images.githubusercontent.com/13177997/48965626-df7ad900-effb-11e8-94b1-ef1990b5a5ff.png)
