### ISSUE TITLE
 不能推送到新的远程仓库

### ISSUE THREAD

**Issue by wenJonSnow** [ant-design/ant-design-pro#2935]
git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project 这样加了  --depth=1  参数 clone 下来的代码  ，不能推送到新的远程仓库，查了很久，原因是 --depth参数是浅clone  推送新远程时 被限制， 希望作者 能在文档里去掉这个参数 ， 虽然clone下来的文件大一点

**Comment by chenshuai2144** [comment]
你可以自己修改的，这种问题和框架无关的

**Comment by kinizumi** [comment]
@wenJonSnow @gclsoft 是不是想去除ali的git然后重新推送到你自己的remote？？
如果是的话呢
clone下来后，rm -rf .git， 然后 git init
把project配置成你自己的repository
push
done
