### ISSUE TITLE
Error in Unexpected token import

### ISSUE THREAD

**Issue by huguangju** [ant-design/ant-design-pro#294]
`npm start` 后报错: 

Failed to parse mock config.

Error in Unexpected token import
.roadhogrc.mock.js:1

```
(function (exports, require, module, __filename, __dirname) { import mockjs from 'mockjs';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

环境
- node: v8.9.1
- MacOS: 10.12.1

**Comment by afc163** [comment]
Works fine on my machine.

**Comment by nikogu** [comment]
@huguangju let me see your `.roadhogrc` file

**Comment by huguangju** [comment]
@nikogu 没有改动过，[新clone的](https://github.com/ant-design/ant-design-pro/blob/master/.roadhogrc)。

我又换了一台机子，clone并运行后没有问题（node版本一致，8.9.1）。对比了两台机子的 `~/.babel.json` 文件，发现成功的那台写入了该项目的[babel配置信息](https://gist.github.com/huguangju/8a50def90b0daa72023f81f013a650f4)，而失败的这台没有，还不清楚是不是babel的原因。

**Comment by nikogu** [comment]
目测是 babel 依赖安装不完全的问题，既然解决了就关了，如果有问题再重启

**Comment by PebblerWon** [comment]
@huguangju  我也出现了同样的问题,请问 你说的那个 .babel.json配置文件在哪里 啊？这个问题应该怎样修复呢？

**Comment by chenshuai2144** [comment]
@PebblerWon  跟目录..  重新安装babel得依赖就好了.
