### ISSUE TITLE
git commit 错误 `Unable to resolve path to module 'puppeteer'`

### ISSUE THREAD

**Issue by sansx** [ant-design/ant-design-pro#2940]
git commit 错误：
```
/Users/maitianer/Documents/work/ant-design-pro/src/e2e/userLayout.e2e.js
1:23  error  Unable to resolve path to module 'puppeteer'  import/no-unresolved
```

我个人的解决方法是通过修改`.eslintrc.js`文件下面的一段，
'import/no-unresolved': [2, { ignore: ['^@/', '^umi/'] }],
为--->
'import/no-unresolved': [2, { ignore: ['^@/', '^umi/', 'puppeteer'] }],
不知是否有更好的解决方案

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/faq-cn#npm-%E5%AE%89%E8%A3%85-puppeteer-%E5%A4%B1%E8%B4%A5
