### ISSUE TITLE
下载@types/lodash包后(可能下载新的npm包都会有这种问题)，npm start重新启动一直报错

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design-pro#2943]
![image](https://user-images.githubusercontent.com/22948077/48886327-8a598e80-ee66-11e8-97ca-615138c6683a.png)

**Comment by rookie-luochao** [comment]
![image](https://user-images.githubusercontent.com/22948077/48886388-c391fe80-ee66-11e8-83e1-7df34ede5e7c.png)
我是有下载@types/lodash包的

**Comment by rookie-luochao** [comment]
我cnpm和npm install重新下载所有npm包后都无法解决这个问题，希望能给出解决方案

**Comment by afc163** [comment]
@sorrycc @chenshuai2144 又是这种问题。

**Comment by yutingzhao1991** [comment]
需要从 dll 的配置里面 exclude 掉 https://github.com/ant-design/ant-design-pro/blob/master/config/config.js#L35

另外 @types 应该放到 devDep 里面吧？


---


是不是 umi 的 dll 这个插件做成显示的指定某些包添加到 dll 中会比较好。

**Comment by rookie-luochao** [comment]
@yutingzhao1991 谢谢您的解答，意思是每增加一个npm包就去exclude一次？关键是哪些包需要exclude，哪些需要include，完全没有这种概念

**Comment by chenshuai2144** [comment]
只要用了 node api的都放到 devDep

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/1525
