### ISSUE TITLE
本地调试情况下，修改 less 文件，编译速度非常慢

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#2947]
修改 JS 文件还好，修改 less 之后经常需要一分钟左右，有办法优化吗？

1.0 没有这个问题，升级到 2.0 之后就有问题了。

**Comment by chenshuai2144** [comment]
删除 plugin.config.js

**Comment by zhangjie2012** [comment]
为啥呢？删掉会不会有其它问题？

**Comment by chenshuai2144** [comment]
换主题不能用了，less 每次都要全量编译，cpu 不好的话速度会很慢

**Comment by zhangjie2012** [comment]
@chenshuai2144 

好的，我试试，谢谢

**Comment by SuperKieran** [comment]
> 删除 plugin.config.js

删除后 less 热更新好像不能用了

**Comment by long-zhuge** [comment]
@SuperKieran 将 plugin.config.js 中的 export default config => {} 中的代码注释掉就快了。不要删除整个文件，亲测有效。

**Comment by chuyinweilai** [comment]
@long-zhuge 有效。cpu消耗也比之前低了，谢谢

**Comment by chenshuai2144** [comment]
https://beta.pro.ant.design/blog/change-theme
