### ISSUE TITLE
请教个关于嵌套路由的问题。

### ISSUE THREAD

**Issue by ChenAt** [ant-design/ant-design-pro#2949]
![image](https://user-images.githubusercontent.com/13502799/48897452-1a0e3580-ee85-11e8-8bdf-6679c96d1065.png)

请问菜单 path 一定需要与父 path 一层一层相加吗？ 拿这个 Articles 页面举例子，我 path 能不能写个绝对路径，比如  /aaa/bbb/ccc 呢？ 但是又要保持嵌套关系，用于菜单生成以及看起来比较直观。

我们公司之前有个旧的 react 项目，现在想集成 antd pro 的方式，但希望页面旧路径能保留，请问有什么思路吗？

这个问题应该是属于 umi 的，貌似提错地方了。

**Comment by chenshuai2144** [comment]
这是pro规定的，其实是不需要，但是这样可以做到自动匹配url和自动生成面包屑

**Comment by ChenAt** [comment]
> 这是pro规定的，其实是不需要，但是这样可以做到自动匹配url和自动生成面包屑

那请问有什么好的方法可以兼容旧链接，同时引入 pro 的模式吗？

**Comment by my1229** [comment]
借楼问个问题，请问pro里，<PageHeaderWrapper 怎么实现自定义面包屑

**Comment by chenshuai2144** [comment]
既然需要更改方案，完全重写是个好办法。
或者你可以直接使用，但是将匹配菜单的算法自己重写一波

**Comment by chenshuai2144** [comment]
`PageHeaderWrapper `
props传入就好了

**Comment by ChenAt** [comment]
> 既然需要更改方案，完全重写是个好办法。
> 或者你可以直接使用，但是将匹配菜单的算法自己重写一波

路由是 umi 生成的，请问有什么办法可以改变匹配逻辑？

**Comment by chenshuai2144** [comment]
router.config.js 生成的。现在用的 path 来进行的匹配，你可以修改一下 key
