### ISSUE TITLE
能不能去掉eslint和editorconfig中linebreak-style的设置？

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design-pro#295]
目前 设置的代码风格`end_of_line = lf`

导致在windows上用`vscode`打开项目一片红色警告

![default](https://user-images.githubusercontent.com/29558970/33248385-a5c09560-d35f-11e7-869e-a01ea85517a9.PNG)

**Comment by afc163** [comment]
https://www.zhihu.com/question/35074609

如果需要可以本地自行修改。

**Comment by yunxifd** [comment]
通过参考 https://github.com/cssmagic/blog/issues/22 

发现原来是`git` 自作聪明的转换了换行符造成的

禁用自动转换
```bash
git config --global core.autocrlf false
```
再拉取下代码即可

当然本地开发的时候，最好设置下IDE，团队统一换行符标准

最后，设置git 的换行符检查功能，来保证换行符风格统一
```bash
# 提交时
# false - 不做任何检查
# warn - 在提交时检查并警告
# true - 在提交时检查，如果发现混用则拒绝提交
git config --global core.safecrlf true
```
