### ISSUE TITLE
Dashboard 里监控页，分析页，工作台页面无法显示

### ISSUE THREAD

**Issue by JeremyDa** [ant-design/ant-design-pro#2951]
![image](https://user-images.githubusercontent.com/8288208/48924971-b1ad6b80-eef9-11e8-8f6b-6674ca07c04e.png)

本地部署master分支代码后，Dashboard里监控页，分析页，工作台页面无法显示，报错如上图。
有人碰到吗，怎么解决？

**Comment by chenshuai2144** [comment]
感觉是环境的问题。删除你的包再装一次

**Comment by JeremyDa** [comment]
本地加载data-set.min.js的路径写错了，修改成下图这样就解决了
![image](https://user-images.githubusercontent.com/8288208/48964021-8b133180-efda-11e8-9aa2-aff971e623b4.png)
