### ISSUE TITLE
为什么src/models的effects里面都是用Generator函数，不能用async函数吗？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2954]
为什么src/models的effects里面都是用Generator函数，不能用async函数吗？

**Comment by yutingzhao1991** [comment]
model 是 dva 的 model ， dva 基于 redux-saga，可以看看他们为啥不切 async+await，https://github.com/redux-saga/redux-saga/issues?q=is%3Aissue+sort%3Aupdated-desc+await+is%3Aclosed

**Comment by GreenMashimaro** [comment]
> model 是 dva 的 model ， dva 基于 redux-saga，可以看看他们为啥不切 async+await，https://github.com/redux-saga/redux-saga/issues?q=is%3Aissue+sort%3Aupdated-desc+await+is%3Aclosed

可以参考下Andarist的回答：https://github.com/redux-saga/redux-saga/issues/7#issuecomment-360428095
