### ISSUE TITLE
src/services/api.js文件里面有两个method字段的值是`update`，不应该是`PUT/PATCH`吗？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2958]
`src/services/api.js`文件里面有两个函数，`updateRule()`和`updateFakeList()`，`method`字段的值是`update`，没看懂`update`是什么意思，不应该是`PUT/PATCH`吗？

![image](https://user-images.githubusercontent.com/13177997/48940469-aaff1280-ef52-11e8-94c6-fee00d7a971d.png)

![image](https://user-images.githubusercontent.com/13177997/48940455-9589e880-ef52-11e8-8239-e05c141e0a12.png)

**update:**
但是它又是放在body中的，好像又不是请求方法。它是什么意思？

**Comment by xiaohuoni** [comment]
只是接口需要的一个参数而已。不是指请求方式
```
 case 'update':
      tableListDataSource = tableListDataSource.map(item => {
        if (item.key === key) {
          Object.assign(item, { desc, name });
          return item;
        }
        return item;
      });
      break;
```
