### ISSUE TITLE
src/services/ 里面的请求url支持restful的写法吗？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2959]
src/services/ 里面的请求url是这样写的，用问号带参数：

![image](https://user-images.githubusercontent.com/13177997/48945102-18676f00-ef64-11e8-8fe4-7df0e3b0e34f.png)

可以用像下面这样的restful写法吗？
![image](https://user-images.githubusercontent.com/13177997/48945231-8d3aa900-ef64-11e8-88fc-bf61e90a67ca.png)

**Comment by yutingzhao1991** [comment]
这个地址是你自己拼接的，按照你的需求拼接就好，比如 `/photos/${photo}`。
