### ISSUE TITLE
Upgrade BizCharts

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#296]
https://github.com/alibaba/BizCharts

**Comment by afc163** [comment]
#19 重复了？

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/issues/19

**Comment by nikogu** [comment]
https://github.com/alibaba/BizCharts/issues/22

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/pull/370
