### ISSUE TITLE
这段代码中的dataSource是什么意思？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#2963]
没看懂下面红框中的`dataSource`，哪里来的`cloneWithRows()`方法？
![image](https://user-images.githubusercontent.com/13177997/48976271-86747900-f0bf-11e8-8082-59bb7a3a8a10.png)

代码来自：
https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body

打开链接，选择“body容器”的全屏按钮，即可看到完整代码。

**Comment by chenshuai2144** [comment]
这是react-native 提供的方法，你输出一波就好了。
react-native dataSource 是一种新的数据结构，方便提升性能的
而且你问错地方了。
