### ISSUE TITLE
Breadcrumbs issue

### ISSUE THREAD

**Issue by alexinfurs** [ant-design/ant-design-pro#2964]
After #2911 (remove menu authorized) commit, sometimes breadcumbs seem to not work as expected.
Inspecting the memory, the problem seems to be lying in the empty menuData  in getBreadcrumbNameMap() function. Maybe it's related to the new async way to get the menuData values.

Way to reproduce the issue: refresh the page in a submenu page

**Comment by laozhu** [comment]
I have the same problem, I got menuData from API, render is OK but the `getPageTitle` method can't generate correct page title based on an empty menuData.

**Comment by xiaohuoni** [comment]
刚看到@我，我看看哈
