### ISSUE TITLE
查询表格点击配置弹出的Modal关闭时没有渐隐效果

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/ant-design-pro#2965]
[https://preview.pro.ant.design/list/table-list](https://preview.pro.ant.design/list/table-list)

点击 配置 ，弹出model， 点击取消或x， 直接消失了，没有渐隐效果
```
 {stepFormValues && Object.keys(stepFormValues).length ? (
    <UpdateForm
       {...updateMethods}
       updateModalVisible={updateModalVisible}
       values={stepFormValues}
   />
 ) : null}
```
关闭的时候直接清除元素了，遇到这种情况是不是需要把清除数据放到afterClose里面去？

**Comment by linzelong95** [comment]
感觉跟stepFormValues && Object.keys(stepFormValues).length 这个条件判断有关
