### ISSUE TITLE
想在项目添加monaco-editor，安装 react-monaco-editor 以后重新运行项目出现一些组件样式错误，组件无法使用的问题

### ISSUE THREAD

**Issue by Nearjin** [ant-design/ant-design-pro#2969]
问题：
想在项目添加monaco-editor使用，在网上查了有别人封装好的 react-monaco-editor ，安装这个依赖后没有任何操作，重新运行 yarn start 后，项目一些组件出现样式错乱的问题，例如按钮组件的样式不见了、a标签会出现下划线等。会出现一些组件功能无法正常使用、例如点击按钮显示弹框，安装后点击按钮反应

环境：
电脑: macbook pro
系统: mac os 10.13.6
浏览器：chrome 70.0.3538.102
antd pro版本：2.1.1

下面是没安装正常的图片
![1543217957070](https://user-images.githubusercontent.com/20437586/48999412-8cd32580-f191-11e8-8c80-665a507b9ab0.jpg)

安装后有问题的图片
![1543217667388](https://user-images.githubusercontent.com/20437586/48999421-9b214180-f191-11e8-9a20-670eb1e33bd6.jpg)

希望能给出解决问题的方法或者修复这个问题，谢谢！

**Comment by chenshuai2144** [comment]
给个重现？

**Comment by gitbotsman** [comment]
哥们，你用react-monaco-editor 代码高亮吗，我看官方还得安装monaco-editor-webpack-plugin，并且设置webpack.config.js ，我在ant-design-pro 没有找到这个文件。

**Comment by afc163** [comment]
`yarn add react-monaco-editor`

你这重现不科学，`react-monaco-editor` 都没用。

**Comment by chenshuai2144** [comment]
还需要专门设置 webpack.

**Comment by SuperKieran** [comment]
我在plugin.config.js文件里加了webpack的配置
``` javascript
// plugin.config.js
import MonacoWebpackPlugin from 'monaco-editor-webpack-plugin'

export default config => {
  config.plugin('monaco-editor').use(MonacoWebpackPlugin, [
    {
      // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
      languages: ['json']
    }
  ])
}
```
如上所示
还是和上面的同志一样，ant design pro的样式部分会失效
感觉哪里冲突了...

**Comment by bbeas** [comment]
@SuperKieran 请问问题最后怎么解决的？我最近使用Monaco Editor也遇到了同样的问题，配置完webpack仍然报错，谢谢

**Comment by leiysky** [comment]
@afc163 确实是没有用到，仅仅是安装`react-monaco-editor`就会导致样式被污染。

**Comment by leiysky** [comment]
@bbeas 我这边解决了，看起来是umi打包的问题，把`config`里面关于`dll`的那部分注释掉就好了

**Comment by gitbotsman** [comment]
> @bbeas 我这边解决了，看起来是umi打包的问题，把`config`里面关于`dll`的那部分注释掉就好了

我注释以后就无法使用MonacoEditor组件了。请问具体注释什么？多谢！

**Comment by wangchong19940101** [comment]
大佬，请问样式冲突的问题解决了吗？我也有同样的问题

**Comment by wangchong19940101** [comment]
@Nearjin

**Comment by wangchong19940101** [comment]
@all
有哪位大佬解决这个问题了吗？
