### ISSUE TITLE
fetch报错

### ISSUE THREAD

**Issue by yuanfuwang** [ant-design/ant-design-pro#297]
代码：
return request(`/Basic/user/login?${stringify(params)}`, {
        method: 'POST',
    });
调用request时，以post的形式进行param传递参数，参数传递正确时，接口调用成功，正常。
参数错误时，接口返回参数错误，正常
以同样的参数再次调用，fetch出现异常，异常信息为：
Cannot convert string to ByteString because the character at index 0 has value 30331 which is greater than 255.
请问这是什么原因引起的，谢谢

**Comment by nikogu** [comment]
这个更像是后端服务的错误，建议通过 chrome 调试器的网络请求，看看接口的请求和返回情况

**Comment by yuanfuwang** [comment]
已解决，是我自己代码问题，谢谢
