### ISSUE TITLE
关于Row、Col与form一起使用在谷歌火狐产生不同效果的疑问

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#2975]
相同的一份代码，在不同的浏览器表现的结果不同。图一是火狐浏览器的截图，符合个人的预期，即两个Col-12是排在一块；图二是谷歌浏览器的截图，本应该并排的Col，却出现了换行。请问如何解决？
![firefox](https://user-images.githubusercontent.com/40480550/49053861-e6d4f900-f22c-11e8-98f6-78a739ff61f3.png)
![chrome](https://user-images.githubusercontent.com/40480550/49053867-ea688000-f22c-11e8-80d1-38938ca62c80.png)

**Comment by chenshuai2144** [comment]
min-height
