### ISSUE TITLE
config.js 设置代理 无效

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#2985]
![image](https://user-images.githubusercontent.com/32530210/49121985-88bc1a80-f2ed-11e8-8507-8ec59f43cbf1.png)

这个我在ant design pro 2里面的 config.js，设置代理，但怎么也走不到API服务器。还是在用本地的MOCK。还请各位指点下！

**Comment by illmm** [comment]
应该是优先走MOCK，把MOCK注释掉试试

**Comment by yutingzhao1991** [comment]
https://umijs.org/zh/guide/env-variables.html#mock 可用 MOCK 环境变量

**Comment by xyzabc0004** [comment]
谢谢，谢谢。环境变量也不知道在哪里加，搞半天没搞出来。我直接把MOCK文件夹删了，也有效果。

**Comment by estn** [comment]
"start:no-mock": "cross-env MOCK=none umi dev",  使用package里面的这个命令运行

**Comment by xyzabc0004** [comment]
我发觉Mock 不关也没事。MOCK有的请求会找mock，后面新加的请求mock没有的会自动找到代理那里。不知道是不是这么个理。

**Comment by xiaohuoni** [comment]
是的

**Comment by xyzabc0004** [comment]
多谢，多谢各位了！
