### ISSUE TITLE
高级表单下面的TableForm.js有bug

### ISSUE THREAD

**Issue by 308787520huanhuan** [ant-design/ant-design-pro#2986]
![qq 20181128094938](https://user-images.githubusercontent.com/3348828/49123354-4a295e80-f2f3-11e8-8231-368a92e0890d.png)

**Comment by 308787520huanhuan** [comment]
点击两次新建成员 但是只保存了第一个 点击页面底部提交的时候 拿的却是全部数据 即使最后一行没有输入
![11](https://user-images.githubusercontent.com/3348828/49123465-a42a2400-f2f3-11e8-81f7-9efb4682d740.png)
 const { onChange } = this.props;
还有就是这里的onChange不知道是哪儿来的

**Comment by yemaozi5518** [comment]
需要加校验的，不是有编辑状态吗

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks
