### ISSUE TITLE
权限控制有问题

### ISSUE THREAD

**Issue by helloAVBD** [ant-design/ant-design-pro#2987]
const routerConfig = this.matchParamsPath(pathname);
BasicLayout.js里面获取routerConfig有问题，刷新浏览器拿到的routerConfig 为undefined，会导致子组件的权限控制无效

**Comment by xiaohuoni** [comment]
抱歉，我的错。https://github.com/ant-design/ant-design-pro/issues/2998
正在考虑怎么处理
