### ISSUE TITLE
官网个人信息按钮在手机浏览器某些情况点击失效

### ISSUE THREAD

**Issue by maxlzc** [ant-design/ant-design-pro#2988]
点击个人信息那个头像(那个有个人中心，个人设置的下拉框)，再点击网页空白处且不引起网页重新渲染情况下，此时个人信息弹出下拉列表消失，再次点击个人信息按钮，按钮颜色变深，下拉框不出现。【必现】

**Comment by chenshuai2144** [comment]
浏览器详情？

**Comment by maxlzc** [comment]
> 浏览器详情？chrome 手机浏览器70.0.3538.75 ios  版本

**Comment by chenshuai2144** [comment]
样式进行了更新，已经不会出现这个问题了
