### ISSUE TITLE
请问index.ejs如何引入assets目录下的js文件？

### ISSUE THREAD

**Issue by zhangzheyuan** [ant-design/ant-design-pro#299]
1、<script src="/assets/slider.js"></script>
这样引入slider.js不行
2、如何把项目中所有的远程资源替换为本地资源？包括index页面中的图片和js、antd的样式与字体资源

**Comment by afc163** [comment]
1. 需要放在 public 目录里。https://pro.ant.design/docs/getting-started-cn#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84
2. https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%9B%BE%E7%89%87%E7%AD%89%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%EF%BC%9F

**Comment by afc163** [comment]
可以参考 https://github.com/ant-design/ant-design-pro/commit/52c14ea1b5b52a329009801c051d63f5cd6a5b1b

**Comment by zhangzheyuan** [comment]
谢谢，静态资源知道怎么加载了。
但是antd加载的资源如https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg(举个栗子)
类似这样的antd源码中加载的远程资源如何替换为本地静态资源？

**Comment by afc163** [comment]
就是 2
