### ISSUE TITLE
官方文档“构建和发布”中对发布的描述不完整

### ISSUE THREAD

**Issue by qzcool** [ant-design/ant-design-pro#2991]
比如用[express发布](https://pro.ant.design/docs/deploy-cn#%E4%BD%BF%E7%94%A8-express)，只有寥寥几行，对之前无上手经验的开发者来说操作的难度仍然很大。建议可以完善此部分。

**Comment by qzcool** [comment]
要的要的，这是我正在做的工作。这并不排斥咱们从文档的目的角度考虑，应该是服务最广大的受众，这样也有利于降低ADP的门槛，况且增加的文本应该也不会很多。

理想的是step-by-step那样的指导。如果我有幸学会了，我也许会开个PR。

**Comment by afc163** [comment]
可以看这篇文档：https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/

**Comment by hfqf** [comment]
同样的想法，搞了半天还是没过去。

**Comment by afc163** [comment]
https://facebook.github.io/create-react-app/docs/deployment

create-react-app 对这块有非常详尽的描述，可以参考一下，原理是一样的。
