### ISSUE TITLE
很抱歉，我新增了一个bug：非授权页面无法重定向

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#2998]
背景：
为了能够比较良好的实现，从服务端动态获取菜单列表这个问题。
我将菜单中的授权过滤信息移动到了model里面。
原本觉得菜单和路由权限应该没有多大关系，但是事实上现有的逻辑中，这部分分离的不是很理想。

现在存在的问题：
把菜单数据放到了model里面，没有权限的路由做了过滤，所以，当访问的路由都不在菜单内时，无法判断是因为权限不足过滤了，还是因为路由不需要在菜单中。
举例子说明：
使用user登录，访问**/form/advancedform**(高级表单)和**/account/center/articles**(个人页的文章选择卡)，获取路由配置都为空。
```    
const routerConfig = this.matchParamsPath(pathname, breadcrumbNameMap);
```
现有的路由权限有效逻辑
```
<Authorized authority={routerConfig && routerConfig.authority} noMatch={<Exception403 />}>
    {children}
</Authorized>
```
此处的authority都为空。

想要的结果
高级表单页无法访问，个人页的文章选择卡，可以正常访问。

扩展：不在菜单列表中的授权页面能够正常访问。

**Comment by herry-zhang** [comment]
你好，请问这个问题怎么解决？

**Comment by zhangshuai0101** [comment]
请问这个问题解决了吗？我动态获取路由之后，菜单栏不显示去除掉的菜单后，路由重定向还是能访问到

**Comment by xiaohuoni** [comment]
@herry-zhang @zhangshuai0101 看最新的提交

**Comment by yoyo837** [comment]
@xiaohuoni 很好，我都是自己clone后改成动态菜单和权限，#3052 对我很有用，我这边还没升v2.x.
