### ISSUE TITLE
Improve roadhog-api-doc

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#30]
- [x] Copy CNAME to gh-pages when npm run site
- [x] Add GA according to a config in this repo

**Comment by nikogu** [comment]
啥意思。。。 😢

**Comment by nikogu** [comment]
add `.ga.json` file in root.

```json
{
  "code": "UA-72788897-5",
}
```

**Comment by afc163** [comment]
换成 UA-72788897-6 GA 上我建过。

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/commit/ae1f594ff850079e043f812123f02265c9d22fcd

**Comment by xiaoxiangmoe** [comment]
@nikogu @afc163  `.ga` 文件是什么作用啊

**Comment by nikogu** [comment]
@xiaoxiangmore 存统计信息的
