### ISSUE TITLE
document.ejs的data-set.min.js明明可以删除，为什么要保留呢？

### ISSUE THREAD

**Issue by ifblooms** [ant-design/ant-design-pro#3001]
页面中使用DateSet的地方都是通过依赖包引入的
`import DataSet from '@antv/data-set';`
为什么要在html模板保留data-set.min.js？
同时删掉document.ejs的data-set.min.js和config.js的
`externals: {
    // '@antv/data-set': 'DataSet',
  },`
页面并没有问题。
疑问？？

**Comment by afc163** [comment]
data-set 很大，提到 externals 可以提高本地开发和构建的性能。
