### ISSUE TITLE
请问如果不想大改 config/router.config.js 我们有什么好的办法实现 主页 指向一个 public page

### ISSUE THREAD

**Issue by xmanjack** [ant-design/ant-design-pro#3008]
请问如果不想大改 config/router.config.js 我们有什么好的办法实现 主页 指向一个 public page

```
{
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: '/user', redirect: '/user/login' },
      { path: '/user/login', component: './User/Login' },
      { path: '/user/register', component: './User/Register' },
      { path: '/user/register-result', component: './User/RegisterResult' },
    ],
  },
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [
      // dashboard
      { path: '/', redirect: '/dashboard/analysis' },
      {
...
```
在ant-design-pro 基础下做二次开发，最近无法设置public page。最近发现新的 ant-design-pro 都必须 登录才能看到 dashboard 内部的网页.

比如 http://localhost:8000/dashboard/analysis. 如果是private page，这是我们想要的结果。

可是大多数的网站都有 public page 跟 private page。 而且一般  http://localhost:8000/  是指向一个 public page，然后如果客户想登陆，才会去login。 请问如果不想大改 config/router.config.js 我们有什么好的办法实现这个功能吗？

English Brief:

Without a big change of config/router.config.js, how do we point “/“ to a public page and when user need to login, we bring them to a private page?

**Comment by kennylbj** [comment]
可以在user路由下新增页面，比如增加一个Guest页面
```js
// user
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: '/user', redirect: '/user/login' },
      { path: '/user/login', component: './User/Login' },
      { path: '/user/register', component: './User/Register' },
      { path: '/user/register-result', component: './User/RegisterResult' },
      { path: '/user/guest', component: './Guest/index' },
    ],
  },
```

**Comment by xmanjack** [comment]
登出的时候是指向了：

http://localhost:8000/user/guest?redirect=http%3A%2F%2Flocalhost%3A8000%2Fdashboard

但是如果去 http://localhost:8000 还是被拉到 登陆页面

**Comment by xmanjack** [comment]
```
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [
```

不知道在设计的时候，所有 App 都是 / 下面是不是导致这了问题。

我们是不是应该吧 //app （或者 private 的东西） 都挪到 （ /app ） 下面？

**Comment by kennylbj** [comment]
> 但是如果去 http://localhost:8000 还是被拉到 登陆页面

改了```{ path: '/user', redirect: '/user/guest' },```应该就不会出现这个情况了。

具有权限的东西都放到app里。

**Comment by xmanjack** [comment]
改了。还是有同样的问题

https://github.com/xmanjack/ant-design-pro/compare/testpublic?expand=1

**Comment by kennylbj** [comment]
授权页面也需要改一下
```js
// pages/Authorized.js
noMatch={<Redirect to="/user/guest" />
```

**Comment by xmanjack** [comment]
👍 工作了！
感谢
