### ISSUE TITLE
cnpm install安装失败

### ISSUE THREAD

**Issue by s7v7nislands** [ant-design/ant-design-pro#301]
➜  pro pro new --no-auto-install
? which type of scaffold do you want to new ? standard (All functional Ant Design Pro scaffold)
? input project name:
? witch directory do you want to init to ? (default is current directory ./):
Success to download repo https://github.com/ant-design/ant-design-pro#master to /private/tmp/pro/
➜  pro cd ant-design-pro-template
➜  ant-design-pro-template cnpm install
⠦ [42/56] Installing roadhog@^1.3.1[roadhog-api-doc@afc163/roadhog-api-doc#fix-babel-resolve] install roadhog-api-doc from git github:afc163/roadhog-api-doc#fix-babel-resolve, may be very slow, please keep patience
⠧ [47/56] Installing raw-body@^2.1.7download tarball failed: GET https://github.com/afc163/roadhog-api-doc/tarball/fix-babel-resolve response 404 status, try to clone repository now.
git clone https://github.com/afc163/roadhog-api-doc.git /private/tmp/pro/ant-design-pro-template/node_modules/.tmp/7806f16a-06cd-482b-84cb-283a28d738da
Cloning into '/private/tmp/pro/ant-design-pro-template/node_modules/.tmp/7806f16a-06cd-482b-84cb-283a28d738da'...
⠋ [48/56] Installing amdefine@>=0.0.4remote: Counting objects: 100, done.
⠸ [48/56] Installing whatwg-url@^4.3.0remote: Total 100 (delta 0), reused 0 (delta 0), pack-reused 100
Receiving objects: 100% (100/100), 15.18 KiB | 81.00 KiB/s, done.
Resolving deltas: 100% (45/45), done.
git checkout fix-babel-resolve
⠼ [48/56] Installing postcss-selector-parser@^2.0.0error: pathspec 'fix-babel-resolve' did not match any file(s) known to git.
✖ Install fail! Error: [roadhog-api-doc@afc163/roadhog-api-doc#fix-babel-resolve] Run "sh -c git checkout fix-babel-resolve" error, exit code 1
Error: [roadhog-api-doc@afc163/roadhog-api-doc#fix-babel-resolve] Run "sh -c git checkout fix-babel-resolve" error, exit code 1
    at module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:51:11)
    at module.exports.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npminstall version: 3.2.1
npminstall args: /usr/local/Cellar/node/8.9.1/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/s7v7nislands/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org
➜  ant-design-pro-template

**Comment by afc163** [comment]
oops.

重新安装即可。

**Comment by afc163** [comment]
@nikogu roadhog-api-doc 可以发个新版，把 pro 里的版本也改掉。
