### ISSUE TITLE
ts文件里面如何引入js模块？

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design-pro#3012]
![image](https://user-images.githubusercontent.com/22948077/49202972-728f8680-f3e1-11e8-8771-0dd0fe6207a0.png)

**Comment by rookie-luochao** [comment]
请问umi相关库为何不生成.d.ts文件，或者@types支持

**Comment by chenshuai2144** [comment]
已经有了，只要安装了 umi 就会有
