### ISSUE TITLE
已经安装umi，但是在ts里面引入'umi/locale'还是会提示找不到模块

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design-pro#3013]
umi/local 欢迎 pr，主创没有写

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/3012#issuecomment-442719918_

**Comment by rookie-luochao** [comment]
@chenshuai2144

**Comment by yutingzhao1991** [comment]
https://github.com/umijs/umi/pull/1499 有一个 PR 了，但是还不确定要不要这么处理，还要讨论下。

**Comment by rookie-luochao** [comment]
@yutingzhao1991 看到了，请问你们有想好怎么样合理解决这个问题？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/1675
