### ISSUE TITLE
静态资源引入的问题

### ISSUE THREAD

**Issue by qianduanMortal** [ant-design/ant-design-pro#3019]
项目部署在了二级目录下，我有一批图片，放在了public/images下， 那么每次引入的时候，都要写
`<img src={`${publicPath}images/xx.png`}>`
这种体验很怪。
此外，  setting中通过link标签添加的color.less,  less.min.js以及document.ejs中的的favicon.icon路径都有问题，并且无法修正。
希望有解决方案出来。

**Comment by chenshuai2144** [comment]
const img = require("./xx.ong");
这样不好吗？
