### ISSUE TITLE
global.less如何随着主题切换颜色

### ISSUE THREAD

**Issue by RivanLuo** [ant-design/ant-design-pro#3020]
比如要修改下图中翻页按钮的颜色和形状，要全局修改？请给出修改思路
![1543484743](https://user-images.githubusercontent.com/13898695/49213290-e7bd8480-f3fe-11e8-8fa0-7f0564e7376e.jpg)

**Comment by xiaohuoni** [comment]
# 局部覆盖antd 样式
```js
.wrapper {
    height: 500px;
     :global {
        .am-button-text {
            padding: 6px;
        }
    }
}
```
# 全局覆盖antd样式
在gobal.less中覆盖ant的样式
在开发环境下，有效。
build之后，发现ant的样式会覆盖写在gobal.less中的样式
```js
暂时的处理是给样式强制 ！important
```

**Comment by RivanLuo** [comment]
目前就是这么做的，在 **`gobal.less  :global`** 中直接加样式不起作用，必须包在#root中才可以.
但是又有一个问题，这样做的话样式不会跟着主题切换，我使用了 **`@primary-color`** 变量

![1543494736](https://user-images.githubusercontent.com/13898695/49222146-0ed38080-f416-11e8-9e42-ed37ac72bb48.jpg)

**Comment by xiaohuoni** [comment]
在global里面不需要:global
全局覆盖，直接写.ant-pagination-next a ,这样就不用包在#root了。
至于使用less变量的问题，你可以试试，不行就提个bug。

**Comment by RivanLuo** [comment]
刚测试了一下，:global确实不需要，但是必须放在#root内部，才生效，直接写是不生效的。
#root到底是怎么用的，为什么加在这个里面就可以了？
谢谢

**Comment by chenshuai2144** [comment]
@RivanLuo  css优先级 
https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity

**Comment by RivanLuo** [comment]
> @RivanLuo css优先级
> https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity

这个优先级是清楚地，pro中global.less 的优先级和antd组件样式的优先级谁高谁低怎么确定，global.less中直接覆盖样式不生效，难道它小于antd样式优先级。还有一个问题没有解决，主题切换的功能无效，已使用了less变量？

**Comment by RivanLuo** [comment]
现在我的需求是：要能够自定义antd组件样式，样式使用了less变量，还要能跟着主题切换？

**Comment by xiaohuoni** [comment]
先加important处理，umi中开启按需加载，css加载顺序有问题

**Comment by RivanLuo** [comment]
> 先加important处理，umi中开启按需加载，css加载顺序有问题

你的解决方法是ok的，其他把样式包在#root中就可以了，当务之急是怎么解决随着主题切换颜色？

**Comment by xiaohuoni** [comment]
@chenshuai2144 https://github.com/umijs/umi/issues/1559#issuecomment-443070116

**Comment by chenshuai2144** [comment]
global.less 里面修改了还需要跟着改变颜色是什么需求，陈述一下？

**Comment by RivanLuo** [comment]
> global.less 里面修改了还需要跟着改变颜色是什么需求，陈述一下？

应用了pro切换主题的功能，比如说上图中翻页的按钮，我自定义了翻页按钮颜色，使用了less变量 @primary-color，但是切换主题后，不会跟着改变。
还有其他的antd组件我需要去自定义样式，使用less变量，需要跟着主题的色调一起切换。

**Comment by RivanLuo** [comment]
我这个需求就是，antd组件的默认样式不满足我们的需要，我们需要重新去自定义覆盖组件样式，但是为了保持色调统一，所以样式中都使用了less变量。

**Comment by chenshuai2144** [comment]
小本本记下了
换主题这部分我会重新写一个

**Comment by chenshuai2144** [comment]
wait 
https://github.com/ant-design/ant-design/pull/13242

**Comment by xiaohuoni** [comment]
已合并

**Comment by wst18115** [comment]
> 刚测试了一下，:global确实不需要，但是必须放在#root内部，才生效，直接写是不生效的。 #root到底是怎么用的，为什么加在这个里面就可以了？ 谢谢



> 我这个需求就是，antd组件的默认样式不满足我们的需要，我们需要重新去自定义覆盖组件样式，但是为了保持色调统一，所以样式中都使用了less变量。如下图，我主题切换为红色，翻页的按钮总不能是默认的蓝色吧！ ![1543555184 1](https://user-images.githubusercontent.com/13898695/49270045-d9c13f80-f4a2-11e8-91f0-54f8021dacef.jpg)
我也遇到这个问题，请求您后面怎么解决的呢？

> 比如要修改下图中翻页按钮的颜色和形状，要全局修改？请给出修改思路 ![1543484743](https://user-images.githubusercontent.com/13898695/49213290-e7bd8480-f3fe-11e8-8fa0-7f0564e7376e.jpg)

你好，我也遇到这个问题勒，请求您后面是怎么解决的呢

**Comment by wst18115** [comment]
> 我这个需求就是，antd组件的默认样式不满足我们的需要，我们需要重新去自定义覆盖组件样式，但是为了保持色调统一，所以样式中都使用了less变量。如下图，我主题切换为红色，翻页的按钮总不能是默认的蓝色吧！ ![1543555184 1](https://user-images.githubusercontent.com/13898695/49270045-d9c13f80-f4a2-11e8-91f0-54f8021dacef.jpg)

我也遇到同样的问题，请问您后面如何解决的呢？
