### ISSUE TITLE
linux 下 build 不过，报错

### ISSUE THREAD

**Issue by StriveTeam** [ant-design/ant-design-pro#3025]
node:9.1.0  npm : 5.5.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.1.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
......

本地 node:9.1.0  npm : 5.5.1，一直都可以，部署到服务器上，执行npm run build 一直build 不过

**Comment by chenshuai2144** [comment]
升级到node10试一试
