### ISSUE TITLE
Refactor: Presentational and Container Components

### ISSUE THREAD

**Issue by qzcool** [ant-design/ant-design-pro#3026]
ADP是否会考虑用这种React写法的最佳实践来重构现有的Components？

Correct me if I am wrong, thanks!

**Comment by chenshuai2144** [comment]
No, there is no such plan for the time being.
You can let us see, useful, we will follow up

**Comment by qzcool** [comment]
Got it! It's not a necessity as more components could reduce to higher chaos.
