### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by kaiserzeng** [ant-design/ant-design-pro#3028]
可以官方给出一份各个配置文件都是做什么的简单讲解嘛？
比如.firebaserc和appveyor.yml等配置文件，哪怕简单讲解也好
之前修改GIt提交的语法检查和自动格式化的时候，才认真的去看里面的各种配置文件，不过发现没有官方资料，然后一点去查，有些没查到。

**Comment by afc163** [comment]
不如来写篇文章分享一下。

**Comment by chenshuai2144** [comment]
在 v4 中删除了用户不需要的文档。已经变得相当干净了
