### ISSUE TITLE
本地可以，自动构建 build 失败

### ISSUE THREAD

**Issue by StriveTeam** [ant-design/ant-design-pro#3030]
node :8.9.1 npm ：5.5.1

npm verb lifecycle live@2.1.0~build: CWD: /home/jenkins/workspace/clive.mt-cloud-ms.master.40306/vms-web
npm info lifecycle live@2.1.0~build: Failed to exec build script
npm verb stack Error: live@2.1.0 build: `umi build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/export/servers/node/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/export/servers/node/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:927:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid live@2.1.0
npm verb cwd /home/jenkins/workspace/clive.mt-cloud-ms.master.40306/vms-web
npm verb Linux 3.10.0-327.28.3.el7.x86_64
npm verb argv "/export/servers/node/bin/node" "/export/servers/node/bin/npm" "run" "build"
npm verb node v8.4.0
npm verb npm  v5.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! live@2.1.0 build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the live@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

**Comment by chenshuai2144** [comment]
一般都是 node 版本太低造成的

**Comment by StriveTeam** [comment]
> node8.10试试

是因为路由文件里，引用组件的大小写问题。已经解决。之前切换过node为高版本没有效果

**Comment by StriveTeam** [comment]
> 一般都是 node 版本太低造成的

是因为路由文件里，引用组件的大小写问题。已经解决。之前切换过node为高版本没有效果
