### ISSUE TITLE
router.config.js 怎么使用自定义的icon

### ISSUE THREAD

**Issue by CarryM** [ant-design/ant-design-pro#3034]

**Comment by CarryM** [comment]
求助大佬

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/router-and-nav-cn#%E5%9C%A8%E8%8F%9C%E5%8D%95%E4%B8%AD%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-icon

**Comment by CarryM** [comment]
发自我的 iPhone

**Comment by mstao** [comment]
我也想自定义svg图标，怎么用？

**Comment by CarryM** [comment]
用在线的……

发自我的 iPhone

**Comment by mstao** [comment]
我看了下官方文档，暂时不支持本地的，这个后面会考虑支持吗

**Comment by zhang0ZGC** [comment]
> 我看了下官方文档，暂时不支持本地的，这个后面会考虑支持吗
> https://pro.ant.design/docs/router-and-nav-cn#%E5%9C%A8%E8%8F%9C%E5%8D%95%E4%B8%AD%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-icon

antd支持[自定义svg图标](https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-SVG-%E5%9B%BE%E6%A0%87)
所以我想可以不可以也像支持iconfont的`icon-`前缀一样搞个特殊处理呢哈哈
![image](https://user-images.githubusercontent.com/10346399/53536131-22d76d00-3b40-11e9-8e53-fd4009151003.png)

**Comment by mstao** [comment]
@zhang0ZGC 这个已经支持了 [增加IconFont组件、菜单图标可以使用自己的IconFont项目图标 ](https://github.com/ant-design/ant-design-pro/pull/3517)

**Comment by zhang0ZGC** [comment]
> @zhang0ZGC 这个已经支持了 [增加IconFont组件、菜单图标可以使用自己的IconFont项目图标 ](https://github.com/ant-design/ant-design-pro/pull/3517)

我知道的，iconfont的支持不是在线图标么，你说的是本地图标
