### ISSUE TITLE
在config.js配置了proxy，java后端也开启了，但是请求状态一直是404

### ISSUE THREAD

**Issue by weisfds** [ant-design/ant-design-pro#3038]
![default](https://user-images.githubusercontent.com/39016416/49340218-cd421000-f677-11e8-8686-690be73e1011.JPG)
我修改了登陆的请求路径
之前有一次请求的时候，Java后端接受的请求了，但是获取不到参数值

**Comment by weisfds** [comment]
我修改了我后端的代码
`原先是这样的
@RequestMapping(value = "/login",method = RequestMethod.POST)
    public JSONResult login(@RequestParam(name = "userName")String username,
                            @RequestParam(name = "password")String password){
        System.out.println(username+"  "+password);
        System.out.println("test login");

        return JSONResult.success(new Test());
    }
现在改成这样才能成功接受前端的请求
@RequestMapping(value = "/login",method = RequestMethod.POST)
    public JSONResult login(@RequestBody Map<String,Object> params){
        System.out.println(params);
        System.out.println("test login");

        return JSONResult.success(new Test());
    }

**Comment by xiaohuoni** [comment]
看不出来，这个和proxy有什么关系

**Comment by chenshuai2144** [comment]
这个是因为 spring mvc 对 java 参数的支持问题，你需要加一个注解。
