### ISSUE TITLE
三级菜单面包屑显示还是有问题

### ISSUE THREAD

**Issue by sangxiaolong** [ant-design/ant-design-pro#304]
最新版本
刷新第三步页面面包屑还是不能正确显示

<img width="791" alt="screen shot 2017-11-27 at 5 30 27 pm" src="https://user-images.githubusercontent.com/77712/33260120-e4026e9a-d399-11e7-8d4b-5afc1e4b3f7e.png">

**Comment by Mellonta** [comment]
不只是面包屑，超过三层参数路由也不能work
