### ISSUE TITLE
按需引入CountDown组件编译报错

### ISSUE THREAD

**Issue by wkl007** [ant-design/ant-design-pro#3040]
`import {CountDown } from 'ant-design-pro'`

控制台报没有找到CountDown下的style文件夹

`Module not found: Can't resolve 'ant-design-pro/lib/CountDown/style' in 'D:\webProject\React\react-ant-design\src\pages\dashboard'`

只能使用`import CountDown from 'ant-design-pro/lib/CountDown`这种方法

**Comment by chenshuai2144** [comment]
这个是因为CountDown 没有 style，但是组件生成代码自动生成的。
抱歉，是我的疏忽

**Comment by xiaosongxiaosong** [comment]
使用过程碰到这个问题了，暂时自己实现了一个简易版本的 CountDown，等问题修复后修改回来

**Comment by chenshuai2144** [comment]
fix in 2.2.0
