### ISSUE TITLE
ant-design-pro用npm  run  build打包完打开index页面空白页

### ISSUE THREAD

**Issue by kangzhaorui** [ant-design/ant-design-pro#3041]
![22](https://user-images.githubusercontent.com/41569132/49358794-024d7180-f70f-11e8-8fb2-a16505f90ddd.gif)

**Comment by liugangtaotie** [comment]
如果你是Nginx做代理，直接:

root:   /var/www/****  ->**** 这里放打包文件

location ^~ / {
            try_files $uri /index.html;
        }

**Comment by kangzhaorui** [comment]
> 如果你是Nginx做代理，直接:
> 
> root: /var/www/**** ->**** 这里放打包文件
> 
> location ^~ / {
> try_files $uri /index.html;
> }

这个是在哪里配置呢？刚用这个框架，换都不太熟悉，我打包时没有关闭mock数据，这个会影响吗？？？谢谢

**Comment by liugangtaotie** [comment]
这个配置是服务器Nginx配置，打包时没有关闭mock数据暂时没有影响

**Comment by kangzhaorui** [comment]
> 这个配置是服务器Nginx配置，打包时没有关闭mock数据暂时没有影响

现在页面情况是一直是loading转圈，控制台报这个错，那报的这个错是前端的错吗？？？他前端还没有放到服务器，打完包直接在前端打开的页面报的错.前端用ant-design-pro这个框架前端直接npm   run build打包好就可以不需要配置其他东西吧。谢谢

**Comment by chenshuai2144** [comment]
你这个错误是没有 http 容器造成的。你的访问方式有问题。
先去学习一下 nginx 怎么用？

**Comment by kangzhaorui** [comment]
> 你这个错误是没有 http 容器造成的。你的访问方式有问题。
> 先去学习一下 nginx 怎么用？

好的 ，我是个前端对于nginx不是很熟悉，我在找找原因，谢谢啊

**Comment by chenshuai2144** [comment]
官方提供了 nginx 的 docker，你可以试一下，你要通过  http 访问的。
http://localhost:8000 这样的。不能直接打开 index.html 访问

**Comment by kangzhaorui** [comment]
> 官方提供了 nginx 的 docker，你可以试一下，你要通过 http 访问的。
> http://localhost:8000 这样的。不能直接打开 index.html 访问

好的 ，谢谢。再问一句，这个怎么关闭mock数据在打包啊

**Comment by chenshuai2144** [comment]
打包不会把 mock 数据带进去的

**Comment by kangzhaorui** [comment]
> 打包不会把 mock 数据带进去的

好的  ，感谢

**Comment by chenshuai2144** [comment]
可以看看我的打包脚本的，里面很全。

**Comment by kangzhaorui** [comment]
> 可以看看我的打包脚本的，里面很全。嗯呢，感谢
