### ISSUE TITLE
this.setState不从新渲染页面数据

### ISSUE THREAD

**Issue by xiouluo** [ant-design/ant-design-pro#3044]
代码如下
![_20181203181333](https://user-images.githubusercontent.com/44430926/49367546-56645000-f727-11e8-91bb-249752c15207.png)
data数据
![_20181203181339](https://user-images.githubusercontent.com/44430926/49367580-7136c480-f727-11e8-82e9-8975952d7e9e.png)
record数据
![_20181203181344](https://user-images.githubusercontent.com/44430926/49367604-83186780-f727-11e8-8be8-a42d5800620a.png)

**Comment by chenshuai2144** [comment]
```
this.setState({
data:{...data}
})
```

**Comment by xiouluo** [comment]
谢谢解答
