### ISSUE TITLE
在layout中通过cloneElement给props.children传递参数，children中获取为undefined

### ISSUE THREAD

**Issue by freedomljt** [ant-design/ant-design-pro#3045]
React.Children.map(children, child => {
      return React.cloneElement(
        child,
        null,
        React.Children.map(child.props.children, c => {
          return React.cloneElement(c, { test: 'test'});
        } ),
      );
    });

已经双层clone了，但是还是不能获取到传递进来的props；

**Comment by chenshuai2144** [comment]
这种做法并不可取，你为什么要这么做？

**Comment by freedomljt** [comment]
@chenshuai2144 因为我想在layout中定义一些公共的方法，让每一个children都能调用，那么有什么好的建议么？求指教。

**Comment by chenshuai2144** [comment]
你可以新建一个context

**Comment by freedomljt** [comment]
我是想要传递方法，context能满足么

**Comment by chenshuai2144** [comment]
可以的。任何东西都是对象

**Comment by freedomljt** [comment]
除了context，还有其他方法么，为什么cloneelement不行？求解

**Comment by freedomljt** [comment]
如果需要在比较深的路由中获取clonrelement进去的参数，从开始路由到目标路由每一个都要用一次cloneelement两次的形式来渲染children，才能正常获取

**Comment by freedomljt** [comment]
![image](https://user-images.githubusercontent.com/3245574/49411863-720e3b80-f7a5-11e8-8757-003b4123e8ef.png)
![image](https://user-images.githubusercontent.com/3245574/49411895-8eaa7380-f7a5-11e8-8e72-d5ce7744c647.png)
这样子，中间缺省的component不上一个用于接收并传递参数给children， children才能获取得到。 @chenshuai2144

**Comment by freedomljt** [comment]
`import React, { PureComponent } from 'react';

class PropsLayout extends PureComponent {
  renderChildren = children => {
    return React.Children.map(children, child => {
      return React.cloneElement(
        child,
        null,
        React.Children.map(child.props.children, c => {
          return React.cloneElement(c, { ...this.props });
        })
      );
    });
  };

  render() {
    const { children } = this.props;
    return this.renderChildren(children);
  }
}

export default PropsLayout;
`

`{
        path: '/dashboard',
        name: 'dashboard',
        icon: 'dashboard',
        // component: '../layouts/BlankLayout',
        component: '../layouts/PropsLayout',
        routes: [
          { path: '/dashboard/test', name: 'test', component: './Dashboard/demo' },
          {
            path: '/dashboard/analysis',
            name: 'analysis',
            component: './Dashboard/Analysis',
          },`
