### ISSUE TITLE
ant design pro权限验证问题

### ISSUE THREAD

**Issue by xiayu1986** [ant-design/ant-design-pro#3046]
使用的ant pro 版本是1.4.4，想在每次页面路由发生变化时通过后端接口拦截用户是否登录以及用户的权限，如果没有登录就跳转到登录页面，如果已经登录就正常跳转，这个功能该写在哪里好呢？我目前是在CheckPermissions中做的,但是路由发生变化时页面不停地发验证请求，请帮忙出个主意，谢谢！

**Comment by yanhao98** [comment]
models/global.js

```
  subscriptions: {
    setup({ history }) {
      // Subscribe history(url) change, trigger `load` action if pathname is `/`
      return history.listen(({ pathname, search }) => {
        if (typeof window.ga !== 'undefined') {
          window.ga('send', 'pageview', pathname + search);
        }
      });
    },
  },
```

**Comment by xiayu1986** [comment]
> 
> 
> models/global.js
> 
> ```
>   subscriptions: {
>     setup({ history }) {
>       // Subscribe history(url) change, trigger `load` action if pathname is `/`
>       return history.listen(({ pathname, search }) => {
>         if (typeof window.ga !== 'undefined') {
>           window.ga('send', 'pageview', pathname + search);
>         }
>       });
>     },
>   },
> ```

谢谢您的回复，这个方法我已经尝试过了，是有问题的，如果校验用户没有权限，还是可以看到页面的但瞬间就跳转了，用户体验有问题。

**Comment by yanhao98** [comment]
@xiayu1986 你具体需要一个什么样的校验？正常的是登录后，后端会返回 身份认证信息回来（比如 token）。和权限列表。然后你的 router.config.js 里面给每个 path 设置了 authority。如果没有对应的 authority 系统以及处理了跳转了。

> pages/Authorized.js

```
  <Authorized authority={children.props.route.authority} noMatch={<Redirect to="/user/login" />}>
    {children}
  </Authorized>
```

**Comment by zjafei** [comment]
他的意思估计是要动态的修改前端的路由表 做出对应的权限管理

**Comment by yanhao98** [comment]
> 因为需要处理从老系统过来的链接，它会带个token过来，我拿这个token验证老系统的账号是否登录身份是否合法，就类似单点登录

你的问题描述的不清楚，我是看不懂。什么老系统新系统又出来了。

**Comment by ergoulee** [comment]
@xiayu1986 你看能不能这样
老系统验证失败,返个401
src/utils/request.js 里面就会处理401
```
    .catch(e => {
      const status = e.name;
      if (status === 401) {
        // @HACK
        /* eslint-disable no-underscore-dangle */
        window.g_app._store.dispatch({
          type: 'login/logout',
        });
        return;
      }

```

**Comment by xiayu1986** [comment]
谢谢大家，我已经找到解决方案：
1、先在router.js中传入promise目的是触发CheckPermissions.js中对promise的判断逻辑
![default](https://user-images.githubusercontent.com/13351108/49983290-cdf27480-ff9c-11e8-99dc-c866db072fa8.png)
2、修改PromiseRender.js
![default](https://user-images.githubusercontent.com/13351108/49983344-245fb300-ff9d-11e8-8eeb-a2d25c221a05.png)

**Comment by hanwenbo** [comment]
@xiayu1986 有没有登陆直接用token去验证就行 我是这么干的
