### ISSUE TITLE
右侧SettingDrawer设置Mask为false没有遮罩层时，点击出现时会从左侧闪现一下

### ISSUE THREAD

**Issue by meccain** [ant-design/ant-design-pro#3047]
操作步骤：
右侧SettingDrawer设置Mask属性为false，没有遮罩层

点击右侧悬浮Icon滑出右侧sidebar
现象：左侧会闪现一下sidebar

**Comment by meccain** [comment]
Hi，很容易复现的一个问题哈，请帮忙看一哈！
右侧SettingDrawer设置Mask为false没有遮罩层，placement和默认为right，驻留在屏幕右侧，点击左侧button出现时抽屉会在屏幕左侧闪现一下。

**Comment by chenshuai2144** [comment]
已知问题，没想好应该怎么改，是为了兼容 ie导致的。可以去 rc-drawer 提问试试

**Comment by alvinzxf** [comment]
我也碰到这个问题了，闪一下的同时左侧下半部分是透明的，闪动消失后左侧遮造层正常，请问有解决方案吗?
