### ISSUE TITLE
app.settings.notification.todo 的中文翻译不对

### ISSUE THREAD

**Issue by Eric-Zhong** [ant-design/ant-design-pro#3048]
在 zh-CN.js 中的一处翻译不对。

是不是应该修改成如下这个内容：
  'app.settings.notification.todo': '待办任务',
  'app.settings.notification.todo-description': '待办任务将以站内信的形式通知',

原翻译为：
  'app.settings.notification.todo': '账户密码',
  'app.settings.notification.todo-description': '账户密码',

**Comment by chenshuai2144** [comment]
Welcome to Pr

**Comment by chenshuai2144** [comment]
我觉得你是对的
