### ISSUE TITLE
ant-design-pro最新版本的代理问题？

### ISSUE THREAD

**Issue by kangzhaorui** [ant-design/ant-design-pro#3049]
我想把前去访问我们自己的后台服务器，官方文档只给定了mock数据，在网上看的文档大部分是在.roadhogrc.mock.js中配置，最新版本2.x中已经没有了这个文件，我是在config下的config中配置，不知道为什么数据还在访问mock的数据。请问我这设置错了吗？？？先谢谢了

![default](https://user-images.githubusercontent.com/41569132/49412272-d382da00-f7a6-11e8-9d2e-b14cbbbcfec8.jpg)

**Comment by chenshuai2144** [comment]
你所有的请求都是/server 开头的？

**Comment by kangzhaorui** [comment]
> 你所有的请求都是/server 开头的？

我改成以api开头的了，

**Comment by kangzhaorui** [comment]
> 无mock启动试一试



> 无mock启动试一试

可以啦，我把缓存关了，之前还是有数据是不是因为这个缓存的事啊？？？
![default](https://user-images.githubusercontent.com/41569132/49419394-8fe99980-f7c1-11e8-9c4f-1a616bb926a3.png)
