### ISSUE TITLE
 dynamicWrapper 有问题

### ISSUE THREAD

**Issue by ityao** [ant-design/ant-design-pro#305]
user model 里面调用
yield put({type: 'saveCurrentUser',payload: data});
然后在 saveCurrentUser 的reducer方法里面写console发现会重复调用了4次

**Comment by nikogu** [comment]
本地未重现，需要注意的是有嵌套关系的组件当然不要重复 `import` 同一个 `model`

**Comment by ityao** [comment]
@nikogu dva里面有判断model的唯一性, 我检查app._models也是正确的, 奇怪这个4次重复调用怎么来的

**Comment by nikogu** [comment]
@ityao 你可以往上推算，看看调用 `dispatch` 的地方是否因为自身代码原因被重复调用

**Comment by ityao** [comment]
@nikogu 没有呢, 这是很简单的代码

**Comment by nikogu** [comment]
贴下代码吧，或者仓库

**Comment by ityao** [comment]
不知道为啥问题又消失了
