### ISSUE TITLE
[求助] npm run build 编译后，如何部署到 tomcat 下某一个文件加下？

### ISSUE THREAD

**Issue by shenyinabcd** [ant-design/ant-design-pro#3051]
npm run build 编译后，将 dist 文件夹下的文件拷贝到 tomcat 中的某一个文件夹，比如 “myproj”, 然后访问 http://localhost:8080/myproj/  ，看到后台有错误。我应该用什么样的命令行编译成 myproj 工程? 谢谢

**Comment by chenshuai2144** [comment]
[publicpath](https://umijs.org/zh/config/#publicpath)
[base](https://umijs.org/zh/config/#base)
文档里竟然没写，疏忽了

**Comment by shenyinabcd** [comment]
谢谢！问了同事，第二个应该不是编译相关的问题。我再看看吧，谢谢！

**Comment by longzhaobi** [comment]
我就是部署到tomcat的，具体步骤如下：
1.把publicPath改成："./"后，打包。
2.把dist目录改成你想要的目录，比如front,然后丢到tomcat的webapps目录下。
3.如果你后端的地址是：http://localhost:8080/abc/currentUser，abc是webapps下的后端目录。那你前端的请求后端地址配置成 /abc/currentUser就可以了。必须是同一个tomcat下。

**Comment by shenyinabcd** [comment]
谢谢！@longzhaobi  我目前没法部署 Api 端的代码，我只写前端的。所以可能就没办法了，谢谢

**Comment by longzhaobi** [comment]
@shenyinabcd 你只要知道后端部署的目录就行了。就是改前端有点麻烦而已。

**Comment by chenshuai2144** [comment]
@longzhaobi 你有兴趣在 site faq 文档下面增加一个部署二级目录的条目吗？

**Comment by qiming0113** [comment]
请问，如何指定dist输出路径，比如：到maven的main/resources/static下。
