### ISSUE TITLE
antd pro 2.1.1 eslint与prettier有冲突

### ISSUE THREAD

**Issue by zjafei** [ant-design/ant-design-pro#3054]
### 代码如下
![1](https://user-images.githubusercontent.com/8189405/49423085-1c4f8880-f7d1-11e8-8a92-c1c302741766.png)
### eslint 报错 
```
Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.
```
### 修改代码如下
![5](https://user-images.githubusercontent.com/8189405/49423221-b0b9eb00-f7d1-11e8-9431-87dd601cd970.png)

### 关键是我在commit的时候 git hook 运行的 npm run lint-staged 里面的
![4](https://user-images.githubusercontent.com/8189405/49423367-376ec800-f7d2-11e8-9a08-e91b2e78e1d3.png)
### 把代码又改回去了变为
![1](https://user-images.githubusercontent.com/8189405/49423085-1c4f8880-f7d1-11e8-8a92-c1c302741766.png)
### 还有就是ts的规则似乎与eslint的规则又冲突
![7](https://user-images.githubusercontent.com/8189405/49423606-ffb45000-f7d2-11e8-957e-1b1e56e27de7.png)

**Comment by chenshuai2144** [comment]
不要挣扎了
拆分出来
export default  BasicLayout.

**Comment by zjafei** [comment]
真的 机智的我就是这样做的
