### ISSUE TITLE
关于路由前缀

### ISSUE THREAD

**Issue by mamumu123** [ant-design/ant-design-pro#3056]
由于某些原因，需要在前端路由加一个共同的前缀，如/dashboard, /form 需要改为/xxx/dashboard./xxx/form.那么在/config中必须一个一个改吗？有什么其他简便的方法吗？

**Comment by chenshuai2144** [comment]
base

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3051
