### ISSUE TITLE
我按照官方文档添加新页面，路由和菜单，但是总是报错

### ISSUE THREAD

**Issue by weisfds** [ant-design/ant-design-pro#3059]
我看不懂为什么在router.config.js配置的都是英文，但是页面显示的都是中文，我添加了新页面，在router.config.js添加了新路由，但是显示却总是有错
![default](https://user-images.githubusercontent.com/39016416/49492745-8bda7c00-f894-11e8-80fe-1901565669e1.JPG)

虽然我刚接触dva和umi，但是我也看了基本的相关文档，ant-design-pro还是有很多看不懂的地方，感觉相当的不人性化，尤其是官网文档，感觉好像随便写写的感觉，。

**Comment by chenshuai2144** [comment]
pro做了全球化，如果不需要删掉他。
https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js#L25
name 修改成 name就好了

**Comment by chenshuai2144** [comment]
文档每个人都会遇到不同的问题。知识水平也不一样。我们是按照懂相关技术栈的思路写的。

**Comment by weisfds** [comment]
那我很对不起，说实话我在这方面还是个新手，

**Comment by chenshuai2144** [comment]
可以去了解一下
react-init g2 umi
