### ISSUE TITLE
页面加载之后有几百毫秒样式错乱

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#306]
![image](https://user-images.githubusercontent.com/8186664/33274029-f5882fd0-d3c9-11e7-8024-b3b050395abd.png)
具体效果见图!

**Comment by afc163** [comment]
问题不大，只是调试环境问题。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/259
