### ISSUE TITLE
菜单面板折叠后，toolTips的位置不能跟随目标元素移动

### ISSUE THREAD

**Issue by kateli** [ant-design/ant-design-pro#3065]
如图：
图1：
![image](https://user-images.githubusercontent.com/8436428/49497078-7409f480-f8a2-11e8-9b48-df9b0e95eee1.png)
图2：
![image](https://user-images.githubusercontent.com/8436428/49497109-884df180-f8a2-11e8-9c88-2ea40af62a25.png)

**Comment by chenshuai2144** [comment]
{position: relative;}

**Comment by kateli** [comment]
是在哪个上面加position relative 呢
![image](https://user-images.githubusercontent.com/8436428/49498814-3360aa00-f8a7-11e8-993c-e26f17868f21.png)
这么试了一下  不好使诶
在icon 和  tooltips标签上加relative  也不好使诶
![image](https://user-images.githubusercontent.com/8436428/49498830-46737a00-f8a7-11e8-9644-2f096aa0130c.png)

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F

**Comment by chenshuai2144** [comment]
getPopupContainer 设置到当前的 dom 上，默认在 body 上面
