### ISSUE TITLE
url中输入query后，重定向时能否把query删除再重定向

### ISSUE THREAD

**Issue by wang5909912** [ant-design/ant-design-pro#3068]
`http://localhost:8000/?code=abc`
例如这个地址登录后，在basicLayout.js的getBashRedirect事件中重定向到了
 `http://localhost:8000/?code=abc#/Overview ` 这个url，
能否重定向到
`http://localhost:8000#/Overview` 这个url下呢？
就是吧query删除掉

**Comment by chenshuai2144** [comment]
先表达通顺一点，一堆乱码和错误的 url

**Comment by xiaohuoni** [comment]
我编辑了一下问题！🙄

**Comment by wang5909912** [comment]
@xiaohuoni 谢咯，哈哈哈，没怎么注意

**Comment by chenshuai2144** [comment]
location.search=""
