### ISSUE TITLE
Route authority attribute behavior

### ISSUE THREAD

**Issue by rayronvictor** [ant-design/ant-design-pro#3072]
What's the behavior of the `authority` attribute in `router.config`?

```javascript
// minimal routes example
const routes = [{
    path: '/',
    routes: [
      {
        path: '/a',
        authority: ['r1'],
        routes: [
          { path: '/a/a' },
          { path: '/a/b', authority: ['r1.1'] },
          {
            path: '/a/:route',
            authority: ['r1.2'],
            routes: [
              { path: '/a/:route/a', authority: ['r1.2.1', 'r1.2.2'] },
              { path: '/a/:route/b' },
              { path: '/a/:route/c', authority: [] }
            ]
          },
        ]
      },
    ]
  }];
```
**Question 01**: What should be the authority for route `/a/123/b`?
1. `null` (**anyone can access**, even though `/a/123` require `['r1.2']`) or
2. `['r1.2']` (as no authority was set, use the last authority defined in the parent route) or
3. `['r1', 'r1.2']` (cumulative from parent route)

Option 01 has the current solution, what can be problematic. For example, if we set the authority for route `/account/settings` to `['admin']`, but not set authority for child route `/account/settings/security` users with `currentAuthority=['user']` can access `/account/settings/security`. Suppose `/account/settings` have info that only `[admin]` can see...

I think option 2 has the best solution because it does not require that we define the authority on subsequent child routes.

**Question 02**: If I set the authority for route `/a` as `['r1']` I need set it again for route `/a/a`?

What if we use the last authority defined in the parenting route and only change if we override?
In this case `/a/:route/c` will override it to not have authority. Again, Option 02 for Question 01 solve this problem. 

**The current implementation is returning undefined for routes with parameters like `/a/:route/a`
https://github.com/ant-design/ant-design-pro/blob/4e392e43e6feeb04dbda04f7f068bb27e59c7241/src/layouts/BasicLayout.js#L99-L113

I implemented a solution for option 2.
Obs: I converted the function from recursive to iterative for better understanding
```javascript
// utils.js
/**
 * Get the route authority. If the route don't have
 * authoriry, get the parent route authority, and so on.
 *
 * @param {string} pathname the route pathname
 * @param {array} routeData routes
 * @returns {string[]} the authority list for that route
 */
export function getRouteAuthority (pathname, routeData) {
  const routes = routeData.slice(); // clone
  let authorities;

  while (routes.length > 0) {
    const route = routes.shift();
    // check partial route
    if (pathToRegexp(`${route.path}(.*)`).test(pathname)) {
      if (route.authority) {
        authorities = route.authority;
      }
      // is exact route?
      if (pathToRegexp(route.path).test(pathname)) {
        break;
      }

      if (route.routes) {
        route.routes.forEach(r => routes.push(r));
      }
    }
  }

  return authorities;
}
```

```javascript
// utils.test.js
describe('getRouteAuthority tests', () => {
  const routes = [{
    path: '/',
    routes: [
      {
        path: '/a',
        authority: ['r1'],
        routes: [
          { path: '/a/a' },
          { path: '/a/b', authority: ['r1.1'] },
          {
            path: '/a/:route',
            authority: ['r1.2'],
            routes: [
              { path: '/a/:route/a', authority: ['r1.2.1', 'r1.2.2'] },
              { path: '/a/:route/b' },
              { path: '/a/:route/c', authority: [] }
            ]
          },
        ]
      },
    ]
  }];

  it('should return the route authority', () => {
    expect(getRouteAuthority('/', routes)).toBeUndefined();
    expect(getRouteAuthority('/a', routes)).toEqual(['r1']);
    expect(getRouteAuthority('/a/a', routes)).toEqual(['r1']);
    expect(getRouteAuthority('/a/b', routes)).toEqual(['r1.1']);
    expect(getRouteAuthority('/a/123', routes)).toEqual(['r1.2']);
    expect(getRouteAuthority('/a/123/a', routes)).toEqual(['r1.2.1', 'r1.2.2']);
    expect(getRouteAuthority('/a/123/b', routes)).toEqual(['r1.2']);
    expect(getRouteAuthority('/a/123/c', routes)).toEqual([]);
  });
});
```

**Comment by chenshuai2144** [comment]
@xiaohuoni  recently seems to have solved

**Comment by xiaohuoni** [comment]
@rayronvictor Is this what you want? #3190
