### ISSUE TITLE
analysis页的effects loading问题

### ISSUE THREAD

**Issue by DanylZhang** [ant-design/ant-design-pro#3073]
我仿照analysis页改造了一下，加入了自己的业务逻辑，主要是增加了三个有先后依赖顺序的dispatch，第二个dispatch要依赖第一个dispatch获得的数据，对应后台的三个异步请求，每个dispatch对应一块区域渲染，也即对应的三个loading。  

问题是:  analysis页的component unmount里执行model里的state clear后，如果后期再次路由到analysis页，由于之前对相应的loading由undefined->true->false，那么再次路由到analysis页由于loading为false，会去渲染已无数据的model state，然后页面报model里state xxx 的 undefined错误（之前被clear掉了）；
那么如果不在component unmount时clear，再次路由到analysis页会显示之前的数据，而业务实际是再次路由回来带的参数不一样，不期望显示那些过期的数据，希望像刚打开网页一样loading是undefined，解构this.props时可以给loading一个true的初值，这样就可以等待加载然后显示正确的数据，不知大神都是如何优雅的处理类似的问题？

**Comment by chenshuai2144** [comment]
loading: dashboard.loading
