### ISSUE TITLE
发现了一个小bug，当窗口宽度缩放到最小时，需要点击展开菜单按钮两次，才能弹出左侧菜单栏

### ISSUE THREAD

**Issue by zhangshuai0101** [ant-design/ant-design-pro#3074]

**Comment by chenshuai2144** [comment]
无法重现

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis

**Comment by zhangshuai0101** [comment]
> https://preview.pro.ant.design/dashboard/analysis

进入页面的时候直接去缩放浏览器窗口宽度，就会出现点击两次的情况，还有个问题想请教您，陈老师，就是上午您给我解答的，登录成功后进入不同的页面的时都会重新渲染BasicLayout组件，但是他每次都是调用componentDidMount里面的方法，我只想调用一次就好

**Comment by zhangshuai0101** [comment]
登录成功后进入不同的页面的时都会重新渲染BasicLayout组件，但是他每次都是调用componentDidMount里面的方法 问题已解决，是由于重定向引起的
