### ISSUE TITLE
新添加的页面在显示的时候都会报错

### ISSUE THREAD

**Issue by weisfds** [ant-design/ant-design-pro#3077]
![default](https://user-images.githubusercontent.com/39016416/49568934-6ff6d900-f96d-11e8-890c-c7b6ec42cb3a.JPG)

**Comment by chenshuai2144** [comment]
react intl 了解一下。

**Comment by weisfds** [comment]
嗯

**Comment by weisfds** [comment]
我前天问过这个问题，那时候有人叫我修改了一行代码，去除国际化，但是没解决，现在忘了那时候修改的是哪里

**Comment by weisfds** [comment]
现在我的菜单都是英文的

**Comment by chenshuai2144** [comment]
那个人就是我，你找到消息继续改一下就好了。在 modal/menu.js 里面
