### ISSUE TITLE
只有一级菜单的情况下页面刷新后没有选中样式

### ISSUE THREAD

**Issue by xiaomoziyi** [ant-design/ant-design-pro#3078]
原本：
![wechatimg484](https://user-images.githubusercontent.com/32298068/49571097-56589000-f973-11e8-8793-38b954242c36.png)

页面刷新后:
![wechatimg483](https://user-images.githubusercontent.com/32298068/49571106-5ce70780-f973-11e8-94fe-5c7bf0fac89b.png)

**Comment by xiaomoziyi** [comment]
> https://preview.pro.ant.design/list/table-list?layout=topmenu&contentWidth=Fixed
> 无法重现。
> 已经更新了最新的代码吗？

更新了最新代码，打开方式不对，要删去二级菜单，
![image](https://user-images.githubusercontent.com/32298068/49626163-86f00680-fa13-11e8-96e0-dac4e769713e.png)

例如删去基础详情页和高级详情页，保留详情页，详情页应该选中，背景色为蓝色，页面刷新后，选中状态不见了

**Comment by m4jing** [comment]
@xiaomoziyi 我这里不用删除二级菜单也可以复现。
官方在线预览却似乎没有这个问题…

**Comment by ergoulee** [comment]
@xiaomoziyi 
#3114 我的情况和你类似
你可以试试先注释掉能不能解决问题

**Comment by xiaomoziyi** [comment]
> @xiaomoziyi
> #3114 我的情况和你类似
> 你可以试试先注释掉能不能解决问题

注释什么，选中样式吗

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/3120
