### ISSUE TITLE
Webpack Failed to compile: ModuleNotFoundError

### ISSUE THREAD

**Issue by byFadili** [ant-design/ant-design-pro#3081]
λ npm run build

> ant-design-pro@2.1.0 build C:\Projects\front
> umi build

[11:44:42] webpack compiled in 41s 397ms
 ERROR  Failed to compile with 1 errors                                                                      

 error  in ./src/pages/Home/Home.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'ajax-loader.gif' in 'C:\Projects\front\node_modules\slick-carousel\slick'

**Comment by chenshuai2144** [comment]
是这个什么包？里面竟然加了gif

**Comment by byFadili** [comment]
its a carousel plugin: https://github.com/kenwheeler/slick
it seems that webpack can resolve the static file ".gif" referenced in "slick-theme.css" css file inside node_modules.

**global.less**:
``` javascript
@import '~slick-carousel/slick/slick.css';
@import '~slick-carousel/slick/slick-theme.css';

html,
body,
#root {
  height: 100%;
  font-family: @Raleway;
  color: @text-color;
  font-weight: 500;
}
```

**Comment by chenshuai2144** [comment]
sorry，i am not sure if umi supports importing git in css.
you can add new webpack plugin in plugin.config.js
https://umijs.org/zh/config/#chainwebpack
