### ISSUE TITLE
权限 保存

### ISSUE THREAD

**Issue by malongwei1** [ant-design/ant-design-pro#3082]
您好，我现在遇到一个问题，如果角色权限保存在localstoage里，担心被修改不安全。如果权限保存在变量里，刷新页面的时候，权限也空了，进入不到页面里进行重新获取权限。
重新获取权限是一个Promise，不知道在哪里调用合适。
我试着在 布局页面 调用获取权限，会导致刷新后登录页闪过然后直接回到主页， 重定向为空。

**Comment by yanhao98** [comment]
第一，前端对于权限不可能做到完全控制，还是要后端来做。
第二，你担心的存在 localstoage 里会被修改的问题，存在变量也可以修改。
第三，刷新页面重新获取权限的问题，我这里暂时是这样处理的：

> 新增一个 jump 页面，浏览器刷新后，匹配不到权限，跳转到 jump 页面。
> 在 jump 页面获取并设置权限，设置完后再跳转回去。

**Comment by xiaohuoni** [comment]
前端的权限只是一个页面拦截手段，有安全要求的，应该在接口级别去做限制。
比如他修改了权限能够访问路由，也访问不到数据。

**Comment by malongwei1** [comment]
好，明白了，谢谢大家。
