### ISSUE TITLE
ant design pro中如何在退出登录状态的情况下将所有组件的state和model里面的state状态恢复到初始状态？

### ISSUE THREAD

**Issue by pingGuoNiki** [ant-design/ant-design-pro#3086]
因为现在后台接口有做一个限时间的登录操作，长时间没有操作的情况下，系统自动退出到登录页面。现在的问题是重新登录进去之后之前的状态还存在，比如对话框之前打开了，此时对话框会在登录的时候跳出，但是对话框上的数据全部都没有了。现在希望在退出操作的时候，状态能回到初始状态。

**Comment by chenshuai2144** [comment]
location.reload();
