### ISSUE TITLE
Ellipsis 浏览器兼容问题

### ISSUE THREAD

**Issue by yanhao98** [ant-design/ant-design-pro#3093]
重现地址：[https://codesandbox.io/s/ojjw28n4qq](https://codesandbox.io/s/ojjw28n4qq)

如重现地址代码演示 ，Firefox 浏览器下出现问题。
点击 SetArticle 后，页面重新 render 后，出现如图问题。
![image](https://user-images.githubusercontent.com/37316281/49684327-b1be8580-fb0d-11e8-87ab-98748b980579.png)

**Comment by chenshuai2144** [comment]
你可能需要自己管理一下生命周期
