### ISSUE TITLE
怎么修改标题和logo

### ISSUE THREAD

**Issue by zhangweitao521** [ant-design/ant-design-pro#3094]
![qq 20181208173849](https://user-images.githubusercontent.com/22015641/49684588-c2bcc600-fb10-11e8-8d72-7d18701b3ec0.png)
登录页面这里无法改变标题，所有页面都没有显示logo

**Comment by yanhao98** [comment]
favicon 图标：`public/favicon.png`
页面标题：在`BasicLayout.js`和`UserLayout.js`两个Layout中的`DocumentTitle`组件。

**Comment by leeyinghui1107** [comment]
现在的路径是 src/defaultsetting.js，可以改这个标题；不过还有个问题没解决，就是网页刷新的时候，初始显示依然是Ant Design Pro，刷新后，会变成设置的内容，。

**Comment by skysuka** [comment]
> 现在的路径是 src/defaultsetting.js，可以改这个标题；不过还有个问题没解决，就是网页刷新的时候，初始显示依然是Ant Design Pro，刷新后，会变成设置的内容，。

在pages/document.ejs中可以设置~

**Comment by leeyinghui1107** [comment]
> > 现在的路径是 src/defaultsetting.js，可以改这个标题；不过还有个问题没解决，就是网页刷新的时候，初始显示依然是Ant Design Pro，刷新后，会变成设置的内容，。
> 
> 在pages/document.ejs中可以设置~

已解决，谢谢

**Comment by frank-liu** [comment]
> 刷新的时候，初始
是在config/defaultSettings.ts

**Comment by guang678** [comment]
刷新页面时 标题如下图
![图片](https://user-images.githubusercontent.com/24949424/105677349-b3827780-5f26-11eb-9a34-79273ba46ef8.png)
然后我再点了下左边的菜单，标题就没了，请问大佬这个要怎么解决
![图片](https://user-images.githubusercontent.com/24949424/105677382-bda47600-5f26-11eb-9e22-8c0752c0bfe0.png)

**Comment by tianyunperfect** [comment]
> 刷新页面时 标题如下图
> ![图片](https://user-images.githubusercontent.com/24949424/105677349-b3827780-5f26-11eb-9a34-79273ba46ef8.png)
> 然后我再点了下左边的菜单，标题就没了，请问大佬这个要怎么解决
> ![图片](https://user-images.githubusercontent.com/24949424/105677382-bda47600-5f26-11eb-9e22-8c0752c0bfe0.png)

这个问题我一直都没有解决过，一直都有
