### ISSUE TITLE
路由权限问题

### ISSUE THREAD

**Issue by qteamcheng** [ant-design/ant-design-pro#3097]
![image](https://user-images.githubusercontent.com/38239481/49709470-805dcb00-fc6f-11e8-9dea-1e7cc884918b.png)

在BasicLayout.js 中Authorized 组件判断似乎没作用，普通用户直接可以看到高级表单，如上图。

感觉没必要在客户端进行这样的权限限制。是否可以考虑直接去掉？

另外，目前BasicLayout.js 中的getBreadcrumbNameMap 函数貌似没用了。代码做删除？

**Comment by yanhao98** [comment]
你自己的问题！

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/37316281/49710184-f7e12980-fc72-11e8-8e56-c1d4acaa3916.png">
<img width="294" alt="image" src="https://user-images.githubusercontent.com/37316281/49710208-0b8c9000-fc73-11e8-913f-551849fbcf88.png">

**Comment by qteamcheng** [comment]
我昨天刚下的代码是这样的，其他人看一下吧。

**Comment by qteamcheng** [comment]
@yanhao98 ，我的问题，代码不够新。
