### ISSUE TITLE
modal内加table问题

### ISSUE THREAD

**Issue by INTMIN** [ant-design/ant-design-pro#3098]
有没有人碰到这种情况，在modal框内要加一个table，然后里面的分页你们怎么控制的，modal内的内容是form.create()出来的，dispatch不能放在modal里，怎么获取当前页面的信息，页码

**Comment by linyongping** [comment]
数据获取与控制可以在model里面配置啊

**Comment by INTMIN** [comment]
@linyongping 主要就是要一个分页信息也要可以选择，可以让设置每页的条数，model内的state状态怎么控制？我现在请求和数据什么的主要是放在外面的父组件，通过props传值进去
