### ISSUE TITLE
Request fetch JSON number format with "。 json 上传 数字 还是有引号。

### ISSUE THREAD

**Issue by xmanjack** [ant-design/ant-design-pro#3099]
最近在 编 一个基于 ant-design-pro 做的web app：

发现 ant-design-pro 分步表单 上传 POST 的 json 文件的数字 （float) 也是 用 （string ) 代表的：

比如：

`{"payAccount":"ant-design@alipay.com","receiverAccount":"test@example.com","receiverName":"Alex","amount":"500","password":"123456"}`

这里的 Amount (请输入转账金额)： 应该写成 `"amount":500 `没有双引号。在form 表里面也写的是金额，所以必须是数字。
`design@alipay.com","receiverAccount":"test@example.com","receiverName":"Alex","amount":500,"password":"123456"}`
 具体解释可以看[https://www.w3schools.com/js/js_json_datatypes.asp](https://www.w3schools.com/js/js_json_datatypes.asp)

大家可以在 src/utils/request.js 的97 行 加 
`console.log(newOptions.body);` 就可以看到。

这个问题导致 golang 无法正确做 json 的处理。

不知道有哪位大神帮助看看？

**Comment by xmanjack** [comment]
写了一个 PR， 请大家看看？

**Comment by chenshuai2144** [comment]
good，golang 竟然不能自动转化。

**Comment by xiaohuoni** [comment]
我觉得数据出口强转一下类型，会不会比较好
