### ISSUE TITLE
基于create-react-app搭的具有ant-design-pro框架的脚手架

### ISSUE THREAD

**Issue by sunnut** [ant-design/ant-design-pro#3100]
Github: [react-easy-start](https://github.com/sunnut/react-easy-start)

## React Easy Start
常用的React脚手架，create-react-app太轻，用它搭建需要对react生态的各个知识点掌握好。相反，ant-design-pro太重，维护其代码还是挺复杂的，很多功能根本不需要，去掉也很有很大的工作量。本脚手架基于create-react-app加了具备ant-design-pro的框架功能(如下图，麻雀虽小，五脏俱全)，开发人员只需关注自己的业务功能。
## 主要解决的问题
* React、Redux、React-Router-V4等整合
* [组件](https://zhuanlan.zhihu.com/p/40134493)按功能划分
* [国际化](https://zhuanlan.zhihu.com/p/40176138)
* [服务器交互](https://zhuanlan.zhihu.com/p/40512216)
* [侧边栏](https://zhuanlan.zhihu.com/p/41111300)更易配置
* [样式](https://zhuanlan.zhihu.com/p/50837353)使用局部结合全局
* 全局等待效果 & 局部组件加载等待
* ...

**Comment by chenshuai2144** [comment]
添加到我们的文档里如何，增加一个 使用其他脚手架 文档。

**Comment by sunnut** [comment]
@chenshuai2144 好啊 O(∩_∩)O

**Comment by yintiankuaile** [comment]
怎么基于create-react-app定制自己的脚手架
