### ISSUE TITLE
Terminal color reset

### ISSUE THREAD

**Issue by codesignist** [ant-design/ant-design-pro#3101]
https://github.com/ant-design/ant-design-pro/blob/3bece1fc73b7f3019f6728819a77352d010e0485/scripts/lint-prettier.js#L35
Need to reset color after line end.
```javascript
console.log(`\x1b[31m ${file} is no prettier, please use npm run prettier and git add !\x1b[0m`); 
```

**Comment by afc163** [comment]
PR is welcome~

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/3107
