### ISSUE TITLE
关于‘’用户权限‘’和‘’路由配置‘’的实现

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3103]
@qteamcheng ：现在菜单数据放到modal 中好多了。感谢。
但是‘’用户权限‘’和‘’路由配置‘’耦合性还是比较大啊，现在角色权限放在router.config.js 中，实际项目角色及权限都是在服务端可配置的。 能否考虑剥离一下啊，现在的权限判断应该是 登录用户 和 路由权限 的比对，能否先改成判断 当前path是否在menuData 中，如过不在，就403。并把这些代码全部放到modal中，以后再改就好整了。

不知道说清楚了没。：）

**Comment by qteamcheng** [comment]
@xiaohuoni 小聪， 说说我的理解，不知道对不

路由：路由是 资源地址 和内容的对应关系，在pro中就是path -> component 或者跳转等等。在项目中可以是静态的，所以放置在配置文件router.config.js中。

权限：权限是资源和角色的对应关系，权限可能是菜单、按钮、数据、接口都行。在项目中这个是动态的，在数据库中保存，可以随时调整。

我们把路由和权限解耦设计，路由中资源地址不在权限中时，就403。 我原来是这么想的。

你说的监听路由变化，判断这个是准备咋解决，指导指导 ：）

**Comment by xiaohuoni** [comment]
类似
```js
subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
        dispatch({
          type: 'check',
          payload: {
            pathname,
          },
        });
      });
    },
  },
effects: {
    *check({ type, payload }, { put, call, select }){
      const {initRoutes} = yield select(_=>_.app)
      checkAuth(payload.pathname,initRoutes)
    },
}
```

**Comment by Anonymity94** [comment]
@xiaohuoni 
### 问题由来
关于后端返回菜单，返回的数据格式应该是啥。看了太多 issues 把自己看晕了

### 问题分析
1. 官网（不知道是不是未更新）说返回一个 json 即可 ，并给出了一个示例。
https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95%EF%BC%9F

2. 我看到你优化过一次菜单权限 #2911 ，现在直接操作 ``modals/menu.js`` 即可。并翻看了你的 ``umi-antd-pro``，此处返回的是 ``router.config.js``  里面的内容。
https://github.com/xiaohuoni/umi-antd-pro/blob/master/src/models/menu.js#L106

### 我的问题是
后端返回的应该是 1. 处官网说的 json 结构数据，还是应该返回 ``router.config.js`` 一样的内容 ？
这是使用 **配置式路由**  和 **约定式路由**  的区别？

### 另外
我觉得你的想法是有道理的。

>  不在并不表示没有权限，可能仅仅表示，不在菜单中显示而已。
> ...
> 我感觉如果直接监听路由变化，判断，不知道是不是更简单一点

**Comment by denglinyi7** [comment]
> @xiaohuoni 小聪， 说说我的理解，不知道对不
> 
> 路由：路由是 资源地址 和内容的对应关系，在pro中就是path -> component 或者跳转等等。在项目中可以是静态的，所以放置在配置文件router.config.js中。
> 
> 权限：权限是资源和角色的对应关系，权限可能是菜单、按钮、数据、接口都行。在项目中这个是动态的，在数据库中保存，可以随时调整。
> 
> 我们把路由和权限解耦设计，路由中资源地址不在权限中时，就403。 我原来是这么想的。
> 
> 你说的监听路由变化，判断这个是准备咋解决，指导指导 ：）

1. 前端框架通过路由把组件映射成path，菜单通过配置path、名称和图标等构成菜单项
2. 作为前后端分离的前端框架，需要后端分配菜单、按钮，前端用户登录时获取菜单项和菜单对应页面的按钮，在用户点击菜单时，展示组件页面和对应的按钮。
3. 避免端后未在菜单path下的path路径，前端打开组件页面，可以监听路由path是在用户菜单path中。后端可以在数据获取和提交判断业务操作，接受或拒绝请求。

**Comment by xiaohuoni** [comment]
@Anonymity94 这个返回什么格式，看你接收数据之后要做什么操作。只要最终能正确解析成menu需要的数据就可以
