### ISSUE TITLE
2.0 版本 build 生成的 js 和 css 去掉了 hash 值，导致版本更新后需要强制刷新才能生效

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#3105]
旧版本，`build` 后的 js 名字是包含一个变更的 hash 值的，这样 nginx 只需要配置 `index.html` 不缓存就行了，新版本更新之后是及时生效的（因为 index.html 加载发现 js 文件变更了就重新加载了）。

新版本，`build` 后的生成的是固定的 `index.html`，`umi.css`，`umi.js`，那么即便 `nginx` 设置了 `index.html` 不缓存，因为 `index.html` 关联的 `umi.css` 和 `umi.js` 名字并没有改变，所以新版本更新之后用户只有强制刷新浏览器才行。

不知道有没有其他的解决办法？我看了 umi 的部署文档，似乎没有针对这种情况的解释。

**Comment by afc163** [comment]
https://umijs.org/config/#hash
