### ISSUE TITLE
Master版本下表格过滤BUG

### ISSUE THREAD

**Issue by Gaion** [ant-design/ant-design-pro#3108]
从master导出，【列表页】→【查询表格】，第四列的【状态】在筛选中【确定】、【取消】按钮无法点击，浏览器Chrome 70.0.3538.110.

**Comment by Gaion** [comment]
直接用文档中的这个命令导出的
```
git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project
```
查了CSS，是多了这一块，看官网的没有这个
![image](https://user-images.githubusercontent.com/7481093/49844935-b0d46f00-fdff-11e8-9415-93084a971e9b.png)

**Comment by crazycheese** [comment]
+1

**Comment by chenshuai2144** [comment]
antd 最近的更新造成的吗？

**Comment by niugengyun** [comment]
是的。。。

**Comment by yanhao98** [comment]
我的没有问题。

**Comment by yanhao98** [comment]
镜像源问题？

**Comment by zhuleili** [comment]
+1  怎么解决的

**Comment by afc163** [comment]
antd 问题不要提到 pro 里。
