### ISSUE TITLE
与后端做登录功能，用了两次payload，登录不成功

### ISSUE THREAD

**Issue by GIn-Liu** [ant-design/ant-design-pro#3109]
如题，登录不成功，
![image](https://user-images.githubusercontent.com/45278962/49801885-695dcc80-fd86-11e8-875f-fcef457356de.png)  在reduce里加空格，或者console。log保存后就正常登陆了，用到两次payload是应为要接收两次服务器数据

**Comment by yanhao98** [comment]
1.问题描述不清楚。

**Comment by chenshuai2144** [comment]
没听懂

**Comment by GIn-Liu** [comment]
没事，解决了，是我重复调用了这个changeLoginStatus产生的，我把changeAuthority和changeStatus分开处理就好了，后台是先验证token和loginId再返回Status的，谢谢回复
