### ISSUE TITLE
如何引入第三方原生js插件

### ISSUE THREAD

**Issue by SpiritLiftedHigh** [ant-design/ant-design-pro#311]
之前使用antd时，有的原生js插件没有使用export导出，所以直接在入口文件index.html中引入就行，现在使用ant-design-pro有个ejs文件，在里面通过<script>标签引入报错，请问应该如何引入

**Comment by afc163** [comment]
1. 不建议 script 引入，现在是 ES201x 的时代，直接 import 即可。
2. https://github.com/ant-design/ant-design-pro/issues/299

**Comment by afc163** [comment]
> 在里面通过<script>标签引入报错

报了什么错？

**Comment by SpiritLiftedHigh** [comment]
我clone的那个ant-design-pro里面没有public文件夹，这是为什么

**Comment by afc163** [comment]
我这里补充了 https://github.com/ant-design/ant-design-pro/commit/52c14ea1b5b52a329009801c051d63f5cd6a5b1b
