### ISSUE TITLE
2.0代理设置问题？

### ISSUE THREAD

**Issue by zhangweitao521** [ant-design/ant-design-pro#3110]
我只想切换某个接口的数据到自己的服务器，其他的还是使用mock，已经配置了代理，采用npm start或者npm run start:no-mock都没有用，都调用的是  http://localhost:8000/的数据，而且request中的缓存已经注调了
![qq 20181211210909](https://user-images.githubusercontent.com/22015641/49802822-091c5a00-fd89-11e8-94b3-d2ab4af2f83e.png)

**Comment by xiaohuoni** [comment]
proxy和mock同时使用的话，使用不同的请求前缀，会清晰一些
