### ISSUE TITLE
nginx发布后502 bad gateway 

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#3111]
各位好，ant design pro 2我用npm start 运行，
config.js代理代码如下：
![image](https://user-images.githubusercontent.com/32530210/49805725-ceb6bb00-fd90-11e8-9812-9357aee7502a.png)
访问数据一切都正常。

可是npm run build ，dist文件放到nginx后如现如下错误：
所有的API都是502，
![image](https://user-images.githubusercontent.com/32530210/49805804-10dffc80-fd91-11e8-9d76-bfff1170558b.png)
在nginx里面我也是这样配置的：
![image](https://user-images.githubusercontent.com/32530210/49805940-62888700-fd91-11e8-90ba-8226f3dcf231.png)
![image](https://user-images.githubusercontent.com/32530210/49805987-7d5afb80-fd91-11e8-8366-b435738b4cda.png)

弄了几天还是出不来效果，还请大家指点下，谢谢！

**Comment by xiaohuoni** [comment]
build之后，proxy无效，你要在前端，直接请求正确的服务器地址

**Comment by xyzabc0004** [comment]
没错啊，前端的的后台请求，都是api/*，然后我就是在nginx里面加了个proxypass，  可是最后还是502。

**Comment by chenshuai2144** [comment]
502是服务器错误，和前端无关的

**Comment by xyzabc0004** [comment]
打包出来之后还是192.168，
这个是啥意思。

**Comment by xyzabc0004** [comment]
做了无数的实验，终于明白一点你的意思了。

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/49935458-0ac25b00-ff0c-11e8-8d22-a6e9d48c0905.png)

终于有效果了，官方文档的这一句话，不能加。

**Comment by xyzabc0004** [comment]
我错了，现在按上面的，怎么搞都是对的了。

**Comment by jiazil** [comment]
@xyzabc0004   后面怎么弄出来？？？
