### ISSUE TITLE
某些情况下导航菜单menu的selectedKeys为空

### ISSUE THREAD

**Issue by ergoulee** [ant-design/ant-design-pro#3114]
我个人的配置是顶部导航,一级菜单.不确定其他配置会不会有这个问题.
发现有时刷新后菜单没有高亮.
断点后发现,渲染顺序 

BasicLayout(menuData = [])
TopNavHeader(menuData = [])
BaseMenu(flatMenuKeys = [])
BasicLayout(menuData = [{…}])
TopNavHeader(flatMenuKeys = ["/pinlist"], menuData = [{…}])
然后因为BaseMenu
```
export default class BaseMenu extends PureComponent {
  constructor(props) {
    super(props);
    this.getSelectedMenuKeys = memoizeOne(this.getSelectedMenuKeys, isEqual);
  }
```
this.getSelectedMenuKeys = memoizeOne(this.getSelectedMenuKeys, isEqual);
这个导致不会渲染菜单高亮,注释后符合预期.
请大佬看看

**Comment by ergoulee** [comment]
@chenshuai2144 我不清楚怎么做不会影响性能,我现在是把constructor注释掉了

**Comment by chenshuai2144** [comment]
那点性能如果造成 bug，就没有必要了，可以注释掉
