### ISSUE TITLE
关于菜单及路由权限配置的问题

### ISSUE THREAD

**Issue by fishjar** [ant-design/ant-design-pro#3117]
现在的菜单配置封装的太费解了，太不灵活了。

既然`menu`都放到`models`了，为什么不一步到位，
将`router.config.js`中与菜单相关的部分路由移到`mock`数据，
通过异步接口获取呢？

`menu.js`中的`routes`数据来自`BasicLayout.js`，
`BasicLayout.js` 中，`routes`数据来自父组件，
但是父组件是哪个？怎样调用`router.config.js`的呢？

只查到`config.js`中引用了该配置。。
那`config.js`又是在什么时机，哪里被调用呢？

```js
// BasicLayout.js
  componentDidMount() {
    const {
      dispatch,
      route: { routes, authority }, // 这里的route是父组件包装过的了？
    } = this.props;
    dispatch({
      type: 'menu/getMenuData',
      payload: { routes, authority },
    });
  }
```

```js
//router.config.js
export default [
  // user
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [],
  },
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [
    // 建议将这部分移到mock
    ],
  },
];
```

补充：
经测试，直接在`menu.js`中使用如下结构的数据好像也可以，
这个和`BasicLayout.js`传过来的`routes`有什么区别吗？
如果没有区别是不是意味着可以直接使用mock获取菜单及权限数据
```
// menu.js
      const { routes, authority } = payload;
      const testRoutes = [
        { path: '/', redirect: '/dashboard/index' },
        {
          path: '/dashboard',
          name: 'dashboard',
          icon: 'dashboard',
          routes: [],
        },
        {
          component: '404',
        },
      ];
      const menuData = filterMenuData(memoizeOneFormatter(testRoutes, authority));
```

**Comment by yanhao98** [comment]
你说的问题也太费解了。
<img width="909" alt="image" src="https://user-images.githubusercontent.com/37316281/49853100-0a00ca80-fe21-11e8-9d99-c339d8b25c50.png">

**Comment by fishjar** [comment]
> 你说的问题也太费解了。
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/37316281/49853100-0a00ca80-fe21-11e8-9d99-c339d8b25c50.png">

1、`menuData`已经是`redux`数据流，可以动态改变，没有必要修改为`state`了吧？
2、我主要不确定，如果从服务器请求菜单，数据结构是否需要和`router.config.js`中的一样？

从服务器获取的菜单列表一般是一维数组，那么`menu.js`中的`formatter`就不适用了吧，比如：
```js
[
  {
    id: 1,
    path: '/index',
    name: 'index',
  },
  {
    id: 2,
    parent_id: 1,
    path: '/index/sub',
    name: 'sub',
  },
],
```

**Comment by superbervin** [comment]
其实我也好奇这些字段是怎么传进来的。。
![image](https://user-images.githubusercontent.com/23428596/49983171-f9c12a80-ff9b-11e8-8365-ae6777e3527c.png)
![image](https://user-images.githubusercontent.com/23428596/49983180-034a9280-ff9c-11e8-8a86-fb1d147f6728.png)

**Comment by tianyu94** [comment]
其实还有一个问题，通过后端获取路由的话，那个component要怎么填充呢，后端肯定是存储的字符串（component相对路径）

**Comment by gaoqiang19514** [comment]
> 其实我也好奇这些字段是怎么传进来的。。
> ![image](https://user-images.githubusercontent.com/23428596/49983171-f9c12a80-ff9b-11e8-8365-ae6777e3527c.png)
> ![image](https://user-images.githubusercontent.com/23428596/49983180-034a9280-ff9c-11e8-8a86-fb1d147f6728.png)

用`connect`向`BasicLayout`注入的
```
export default connect(({ global, setting, menu: menuModel }) => ({
  loadFlag: menuModel.loadFlag,
  collapsed: global.collapsed,
  layout: setting.layout,
  menuData: menuModel.menuData,
  breadcrumbNameMap: menuModel.breadcrumbNameMap,
  ...setting,
}))(props => (
  <Media query="(max-width: 599px)">
    {isMobile => <BasicLayout {...props} isMobile={isMobile} />}
  </Media>
));
```
