### ISSUE TITLE
Antd表单组件用React Hooks重写，怎么获取表单的值？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#3123]
Antd表单组件用React Hooks重写，怎么获取表单的值？比如antd-mobile的[TextareaItem][1]组件，
用React Hooks重写它，半成品代码如下：

    import React, { useState, useEffect} from "react"
    import { List, TextareaItem } from 'antd-mobile';
    import { createForm } from 'rc-form';
    
    
    function TextareaItemExample {
    
      useEffect(() => {
        //this.autoFocusInst.focus();
      });
    
      return (
        <div>
          <List renderHeader={() => 'Customize to focus'}>
            <TextareaItem
              title="title"
              placeholder="auto focus in Alipay client"
              data-seed="logId"
              ref={el => this.autoFocusInst = el}
              autoHeight
            />
            <TextareaItem
              title="content"
              placeholder="click the button below to focus"
              data-seed="logId"
              autoHeight
            />
          </List>
        </div>
      );
    }
    
    const TextareaItemExampleWrapper = createForm()(TextareaItemExample);
    
    export default TextareaItemExampleWrapper;

**问题：**
1、怎么获取表单的值？获取值后好用于发送ajax请求。这里有个自定义Hook库[react-use-form-state][2]，但是它用于原生html表单，怎么在antd表单上做同样的事？

 
   
2、 class组件改成function组件后， `this.autoFocusInst.focus();` 这个语句应该怎么写?

  [1]: https://mobile.ant.design/components/textarea-item/
  [2]: https://github.com/wsmd/react-use-form-state

**Comment by zhouhuiquan** [comment]
这是我自己弄个一个,可能很low,没办法react就接触了半年时间
`import React, { Component } from 'react';
import { Form, Button, Input, Select, Cascader, DatePicker, Checkbox } from 'antd';

const { Item: FormItem } = Form;

@Form.create()
export default class SearchForm extends Component {
  state = {
    data: {},
  };

  componentDidMount() {
    const {
      form: { getFieldsValue },
    } = this.props;
    const data = getFieldsValue();
    this.setState({
      data,
    });
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.isChanged) {
      const {
        form: { setFieldsValue },
        onChange,
      } = this.props;
      const { data } = this.state;
      setFieldsValue(data);
      if (onChange) {
        onChange();
      } else {
        console.log(
          'onChange方法必须写,onChange是为了修改父组件中isChange的值为false,否则会造成死循环'
        ); // eslint-disable-line
      }
    }
  }

  handleReset = () => {
    const {
      form: { resetFields, getFieldsValue },
      formOptions: { searchHandler = () => {}, resetHandler = () => {} },
    } = this.props;
    resetFields();
    const data = getFieldsValue();
    // console.log(data)
    this.setState({
      data,
    });
    searchHandler({}, true);
    resetHandler();
  };

  handleSearch = () => {
    const {
      formOptions: { searchHandler = () => {} },
      form: { getFieldsValue },
    } = this.props;
    const value = getFieldsValue();
    this.setState({
      data: {
        ...value,
      },
    });
    searchHandler(value, true);
  };

  render() {
    const {
      form: { getFieldDecorator },
      formOptions: { formData = [], hasReset = true } = {},
    } = this.props;
    const FormItems = [];
    formData.forEach(item => {
      switch (item.type) {
        case 'Select':
          FormItems.push(
            <FormItem className="w120 fl mr16" {...item.itemOptions} key={item.name + item.type}>
              {getFieldDecorator(item.name)(
                <Select allowClear {...item.typeOptions}>
                  {item.children}
                </Select>
              )}
            </FormItem>
          );
          break;
        case 'Cascader':
          FormItems.push(
            <FormItem className="w150 fl mr16" {...item.itemOptions} key={item.name + item.type}>
              {getFieldDecorator(item.name)(<Cascader {...item.typeOptions} />)}
            </FormItem>
          );
          break;
        case 'RangePicker':
          FormItems.push(
            <FormItem className="w220 fl mr16" {...item.itemOptions} key={item.name + item.type}>
              {getFieldDecorator(item.name)(<DatePicker.RangePicker />)}
            </FormItem>
          );
          break;
        case 'Checkbox':
          FormItems.push(
            <FormItem className="fl mr16" {...item.itemOptions} key={item.name + item.type}>
              {getFieldDecorator(item.name, {
                // initalValue: false,
                valuePropName: 'checked',
              })(<Checkbox {...item.typeOptions}>{item.children || '复选'}</Checkbox>)}
            </FormItem>
          );
          break;
        default:
          FormItems.push(
            <FormItem className="w150 fl mr16" {...item.itemOptions} key={item.name + item.type}>
              {getFieldDecorator(item.name)(
                <Input {...item.typeOptions} onPressEnter={this.handleSearch} />
              )}
            </FormItem>
          );
          break;
      }
    });
    FormItems.push(
      <FormItem className="w82 fl mr16" key="searchbutton">
        <Button type="primary" icon="search" onClick={this.handleSearch}>
          搜索
        </Button>
      </FormItem>
    );
    if (hasReset) {
      FormItems.push(
        <FormItem className="w64 fl" key="resetbutton">
          <Button onClick={this.handleReset}>重置</Button>
        </FormItem>
      );
    }
    return <Form className="cf">{FormItems}</Form>;
  }
}
`

**Comment by zwl1619** [comment]
@zhouhuiquan  这是什么哟？hooks呢？

**Comment by donkeyqiu** [comment]
function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` points to the mounted text input element
    inputEl.current.focus();
  };
  return (
    <>
      <input ref={inputEl} type="text" />
      <button onClick={onButtonClick}>Focus the input</button>
    </>
  );
}

**Comment by donkeyqiu** [comment]
`function FancyInput(props, ref) {
  const inputRef = useRef();
  useImperativeMethods(ref, () => ({
    focus: () => {
      inputRef.current.focus();
    }
  }));
  return <input ref={inputRef} ... />;
}
FancyInput = forwardRef(FancyInput);`

**Comment by z-lionel** [comment]
请问问题解决了吗? 该如何处理?

**Comment by z-lionel** [comment]
> @zhouhuiquan 这是什么哟？hooks呢？
> 我的哥，走错门了吗？能不能把答案删了？

请问这个问题解决了吗? 该如何处理?

**Comment by sroctop** [comment]
兄弟，你好。请问下哈，怎么在hooks中调用antd pro封装的redux方法和调用接口呢

**Comment by z-lionel** [comment]
> 兄弟，你好。请问下哈，怎么在hooks中调用antd pro封装的redux方法和调用接口呢

可以将dispatch传到子组件

**Comment by eastFang** [comment]
hooks写的组件没有实例，没有this
