### ISSUE TITLE
A small bug: .ant-input:focus { border-color }

### ISSUE THREAD

**Issue by imhele** [ant-design/ant-design-pro#3128]
## Version
Preview site.

## Environment
Windows 10, Chrome 70.0

## Reproduction link
https://preview.pro.ant.design/form/basic-form?primaryColor=%23FA541C

## What is actually happening?
When changing the theme color, .ant-input:focus { border-color } has not changed. So you can see that the shadow of input box is still light blue.

**Comment by chenshuai2144** [comment]
这是 换主题插件的错误，近期会有升级
