### ISSUE TITLE
脚手架内使用redux-persist在开发环境下可以把models里的state取到，生产环境下只能取到models目录下的state，pages目录下的models目录里的state无法存储

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#3135]
![wechatimg6282](https://user-images.githubusercontent.com/16549630/49070612-156fc580-f267-11e8-9e3a-1a1f034e7b44.jpg)
![wechatimg6283](https://user-images.githubusercontent.com/16549630/49070635-1f91c400-f267-11e8-9da5-ed0ec53f218c.jpg)
利用的是ant design pro v2.0脚手架

**Comment by chenshuai2144** [comment]
放到 src 里的 modal 就好了

**Comment by zhilianbi520** [comment]
> 放到 src 里的 modal 就好了

好的。

**Comment by jiamianmao** [comment]
哥，同问，你最后如何解决的?
