### ISSUE TITLE
umi test 报错

### ISSUE THREAD

**Issue by superbervin** [ant-design/ant-design-pro#3137]
![image](https://user-images.githubusercontent.com/23428596/49933261-2460a400-ff06-11e8-8a5a-dd6dd02a56f4.png)
查了一下，没找到这个报错的解决办法

**Comment by chenshuai2144** [comment]
pupputer 没安装。

**Comment by superbervin** [comment]
我已经安装了依旧不行，还有一个问题：我只测试.test.js文件，并没有测试.e2e文件，为啥也要跑pupputeer；

**Comment by superbervin** [comment]
![image](https://user-images.githubusercontent.com/23428596/49980142-3f2a2b80-ff8d-11e8-8080-a565e65d99d9.png)

**Comment by chenshuai2144** [comment]
用 cnpm 试试

**Comment by Mark-rover-myh** [comment]
同遇到

**Comment by Mark-rover-myh** [comment]
降到Tag2.1.1 可以用了
@superbervin @chenshuai2144 
补充一下 环境 win10 x64  node 11.4.0   npm  6.4.1（应该没啥关系）

**Comment by superbervin** [comment]
你说的Tag包版本在哪里修改？@Mark-rover-myh

**Comment by Mark-rover-myh** [comment]
> 你说的Tag包版本在哪里修改？@Mark-rover-myh

git checkout 可以搜一下从某Tag建立新分支 

`git checkout -b branch_name tag_name`

这样在git clone 时的depth就不要设置为1了 正常clone @superbervin

**Comment by superbervin** [comment]
@chenshuai2144  是不是要在master分支解决一下？使用了cnpm依旧如此

**Comment by chenshuai2144** [comment]
使用 cnpm 直接安装一下pupputer试试呢？

**Comment by chenshuai2144** [comment]
升级到最新的 pupputer 就可以了
