### ISSUE TITLE
发现一枚超级无语的BUG

### ISSUE THREAD

**Issue by rellyCheng** [ant-design/ant-design-pro#3138]
路由地址不能包含worker,点击左侧栏进入页面,没有问题, 当F5刷新页面报404

点击左侧路由进入页面:     正常!
![image](https://user-images.githubusercontent.com/22974879/49937058-93db9100-ff10-11e8-98ba-7921b2fe8f9d.png)

F5刷新页面后: 报错!

![image](https://user-images.githubusercontent.com/22974879/49937181-ee74ed00-ff10-11e8-8e24-23e24f5d4c54.png)

仔细检查代码后没有一点问题,当我把路由地址改成workers111
![image](https://user-images.githubusercontent.com/22974879/49937325-5cb9af80-ff11-11e8-8589-c0ec2bd57290.png)
同样是点击左侧路由可以正常访问页面,F5刷新后页面404
正常页面的404应该是这样的
![image](https://user-images.githubusercontent.com/22974879/49937405-912d6b80-ff11-11e8-8d33-9d9ccb934252.png)

最后我把路由改成work111ers
![image](https://user-images.githubusercontent.com/22974879/49937716-a060e900-ff12-11e8-8e0f-59398e1fe647.png)
BUG消失!!!!

**Comment by chenshuai2144** [comment]
试着重启一下呢？

**Comment by rellyCheng** [comment]
@chenshuai2144 试过项目重启, 不行的, 同事的电脑上的项目也试了一下, 同样的问题

**Comment by chenshuai2144** [comment]
worker 估计是个关键字了，去 umi 问问
