### ISSUE TITLE
locale问题

### ISSUE THREAD

**Issue by qjekingstar** [ant-design/ant-design-pro#3139]
是否可以将locale相关的js分开打包？现在打出来的umi.js会把所有语言的都打进去导致体积非常大

**Comment by afc163** [comment]
我们貌似正有这个计划。

**Comment by yutingzhao1991** [comment]
国际化是基于 umi-plugin-locale 这个插件实现的。后面在 umi 中跟进，https://github.com/umijs/umi/issues/1638
