### ISSUE TITLE
是否可以增加一列文档

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#314]
增加必须非必需参数.
可以让查看更加方便.

**Comment by nikogu** [comment]
@chenshuai2144 应该也没有必选参数，必选参数一般都有 `defaultValue`

**Comment by chenshuai2144** [comment]
@nikogu 有些地方不清晰.高度属性我就分不清.只能看源码

**Comment by afc163** [comment]
从 antd 的实践来看，这列属性不是特别重要。必选的属性一般用的时候都能看出来，例如 Table 的 dataSource 和 columns 这种。

**Comment by nikogu** [comment]
> 有些地方不清晰.高度属性我就分不清.只能看源码

这个确实是组件实现的一个问题，其实应该在代码里面动态计算出默认值的
