### ISSUE TITLE
最新的antdp demo下载，install 失败

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#3142]
E:\antdp\ant-design-pro\ant-design-pro-master>npm  install
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! Unexpected end of JSON input while parsing near '...+L7wXsajpTJUMePUOyK7G'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zkjw\AppData\Roaming\npm-cache\_logs\2018-12-14T03_03_54_740Z-debug.log
![image](https://user-images.githubusercontent.com/30460433/49980839-240ceb00-ff90-11e8-89ef-916e6b6003b1.png)

**Comment by chenshuai2144** [comment]
cnpm 是你的好朋友

**Comment by yemaozi5518** [comment]
![image](https://user-images.githubusercontent.com/30460433/49987724-51b55c80-ffaf-11e8-8e14-8e34b702c000.png)

**Comment by yemaozi5518** [comment]
@chenshuai2144
