### ISSUE TITLE
config\config.js第15行和59行都有targets: { ie: 11, }，是否重复？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-pro#3145]
config\config.js第15行和59行都有targets: { ie: 11, }，是否重复？

另外，在[umi-plugin-react](https://umijs.org/zh/plugin/umi-plugin-react.html)  文档中说，“这是官方封装的一个插件集，包含 13 个常用的进阶功能。”，这13个里面也没有targets这一项：
![image](https://user-images.githubusercontent.com/13177997/49991220-5bdd5800-ffbb-11e8-837e-a0095a546632.png)

**Comment by chenshuai2144** [comment]
是的，可以帮忙 pr 一个吗？

**Comment by chenshuai2144** [comment]
多谢帮忙删除
