### ISSUE TITLE
选择系统设置的主题色时页面卡顿，导致页面不能渲染。

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#3147]
修改系统主题设置的时候，其他功能都正常，但是在选择 `主题色` 页面卡顿，导致页面不能正常渲染。问题详情请看视频
![image](https://user-images.githubusercontent.com/12181423/49995515-5980fb00-ffc7-11e8-821d-c20e95b6cb2d.png)

![image](https://user-images.githubusercontent.com/12181423/49995492-44a46780-ffc7-11e8-8ecc-131b73a9114b.png)

[QQ20181214-173634-HD.mp4.zip](https://github.com/ant-design/ant-design-pro/files/2679430/QQ20181214-173634-HD.mp4.zip)

**Comment by chenshuai2144** [comment]
见过同样的问题，但是我这里无法再现。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/3183
看看和这个有关吗？
