### ISSUE TITLE
ant-design-pro 配置使用hashHistory后，页面使用特定模板有问题，应该是很严重的bug

### ISSUE THREAD

**Issue by tgy3300** [ant-design/ant-design-pro#3151]
如题，使用ant design pro来做项目，项目配置使用hashHistory模式后，页面配置指定使用自己的特有模板时，访问有问题，地址为：localhost:8000/#/home/rukou  这样的，非要localhost:8000/home/rukou#/home/rukou这样访问，页面特定模板才会生效，生效后，页面再链接跳转到其他页面时，其他页面也会跟着使用/home/rukou的特有模板生成页面。

browserHistory模式下正常，只有hashHistory下才有这问题

**Comment by ergoulee** [comment]
不会啊,我也用的history: 'hash',没有遇到这个问题啊,你设置base了?

**Comment by ergoulee** [comment]
最新的master

**Comment by tgy3300** [comment]
你页面配置了特定模板了，可有生效

**Comment by ergoulee** [comment]
你的模版指什么?布局还是页面?我还是用的BasicLayout做用户布局,页面自己重写的

**Comment by imhele** [comment]
> 你的模版指什么?布局还是页面?我还是用的BasicLayout做用户布局,页面自己重写的

html 模板，AntD Pro 直接用的同一个 document.ejs ，不会有问题。
