### ISSUE TITLE
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in 'D:\bc\workspace\mgr\node_modules\react-redux\es\components'

### ISSUE THREAD

**Issue by kongqingfei** [ant-design/ant-design-pro#3156]
之前的ant-design-pro项目，执行了npm install，然后就报这个
感觉应该是哪个包的版本出问题了，求解

Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in 'D:\bc\workspace\mgr\node_modules\react-redux\es\components'

**Comment by chenshuai2144** [comment]
删除，重新安装就好了
