### ISSUE TITLE
打包部署后IE浏览器异常

### ISSUE THREAD

**Issue by eevin** [ant-design/ant-design-pro#3158]
使用ant-design-pro 2.0，IE兼容模式设置成IE9，调整了部分不兼容IE9的样式。
经测试在开发模式下一切正常。
打包发布后发生错误：

![image](https://user-images.githubusercontent.com/21354993/50072508-647a9c00-0210-11e9-8eb7-bc5f56978119.png)

经过反复测试，任何简单页面都无法访问，现在只想用pro 2.0作为基础架构，能否有解决办法？

**Comment by chenshuai2144** [comment]
我们是不支持ie9的，抱歉
