### ISSUE TITLE
开启pwa遇到的问题

### ISSUE THREAD

**Issue by ergoulee** [ant-design/ant-design-pro#3159]
我设置了  base: '/public/newt2/', publicPath: 'https://domain/newt2/',
然后开启pwa
1.manifest.json会build到publicPath下,引起跨域.可是已经设置了manifest,是pwa修改这个了?
```
manifest: {
    basePath: '/',
  }
```
2.在dist/service-worker.js里precache的预缓存路由,就是precache-manifest.js里面
,会把index.html的路由也处理成publicPath/index.html,造成页面打不开.

晕,试了一下是umi的问题...

**Comment by ergoulee** [comment]
是umi的问题,我转过去了

**Comment by cindyZhang4** [comment]
> 是umi的问题,我转过去了

所以请问问题解决了么？
