### ISSUE TITLE
最新版本2.1.1布局页面样式问题

### ISSUE THREAD

**Issue by Lzw2016** [ant-design/ant-design-pro#3161]
问题演示如下

![image 1](https://user-images.githubusercontent.com/19291563/50125737-2085a680-02a5-11e9-955c-1d411c335033.png)

![gif](https://user-images.githubusercontent.com/19291563/50125744-25e2f100-02a5-11e9-849a-9d4b350620b9.gif)

**Comment by chenshuai2144** [comment]
无法再现

**Comment by Lzw2016** [comment]
请使用 window系统的谷歌或者火狐，mac 可能没有问题，这个问题很容易出现
