### ISSUE TITLE
antdPro 使用dva全局loading作为组件渲染条件会多次渲染

### ISSUE THREAD

**Issue by stringStar** [ant-design/ant-design-pro#3162]
fetch data在didmount时触发，loading也在didmount时触发，会造成组件渲染两次，如：
`<Card title={ <FormattedMessage id="app.monitor.popular-searches" defaultMessage="Popular Searches" /> } loading={loading} bordered={false} bodyStyle={{ overflow: 'hidden' }} > <TagCloud data={tags} height={161} /> </Card>` 其中TagCloud会先被渲染然后被loading替换

**Comment by stringStar** [comment]
fetch data在didmount时触发，loading也在didmount时触发，会造成组件渲染两次，如：          
 ` <Card               title={                 <FormattedMessage                   id="app.monitor.popular-searches"                   defaultMessage="Popular Searches"                 />               }               loading={loading}               bordered={false}               bodyStyle={{ overflow: 'hidden' }}             >               <TagCloud data={tags} height={161} />             </Card>`

**Comment by chenshuai2144** [comment]
应该使用自己 modal的 loading
