### ISSUE TITLE
关于动态菜单和权限问题

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design-pro#3164]
小弟新入手ant design pro ，动态菜单也根据各前辈方法实现了（不同用户角色显示不同菜单项），但只要访问路由设置的地址依然可以访问页面，我把issues看了个遍也没能入手实现权限问题，突然想起ant可以处理返回的http状态，我尝试在服务端通过JWT认证用户权限并返回403，不知是否可以，会不会影响别的？

**Comment by jeffmxzhao** [comment]
这个交给后端拦截就好了吧，个人认为不宜把过多逻辑放在前端

**Comment by chenshuai2144** [comment]
前端没有安全可言的，放到后端是更好的办法
