### ISSUE TITLE
菜单刷新后无法自动高亮选中当前菜单

### ISSUE THREAD

**Issue by jeffmxzhao** [ant-design/ant-design-pro#3165]
修改model/menu.js,menuData从后台动态返回菜单,刷新界面后，无法像demo一样高亮显示当前菜单
```js
effects: {
    *getMenuData({ payload }, { call, put }) {
      const { authority } = payload;
      const response = yield call(getUserMenu);
      const menuData = filterMenuData( memoizeOneFormatter(response.data, authority));
      const breadcrumbNameMap = memoizeOneGetBreadcrumbNameMap(menuData);
      yield put({
        type: 'save',
        payload: { menuData, breadcrumbNameMap },
      });
    },
  },
```
测试过程中发现只要在`getMenuData`方法里请求任意数据，包括Demo中的mock数据，都会出现此现象

**Comment by chenshuai2144** [comment]
没听懂。详细一点？

**Comment by jeffmxzhao** [comment]
> 没听懂。详细一点？

如点击左边菜单Dashboard->分析页，`分析页`为蓝底反白选中状态，F5刷新后,`分析页`依然是蓝底反白
但在修改model/menu.js,menuData从后台动态返回菜单,F5刷新后，菜单无法蓝底反白显示

**Comment by jeffmxzhao** [comment]
> 是的这个问题我也是，从github拉取下来就这样 刷新完之后左侧菜单不会像演示站一样自动展开

@hanwenbo 发现只要在那里请求后台数据就会这样，哪怕是请求项目中已有的mock数据也会这样

**Comment by hanwenbo** [comment]
@jeffmxzhao 我解决了  我看官方更新了BaseMenu组件 您替换下看看是否能解决  我刚才尝试了 已经解决

**Comment by jeffmxzhao** [comment]
@hanwenbo 感谢，更新后解决。

**Comment by hanwenbo** [comment]
@jeffmxzhao 不客气~

**Comment by zsl1549** [comment]
@hanwenbo 更新哪里 可否具体点，谢谢。

**Comment by vainly** [comment]
@hanwenbo jeffmxzhao 具体更新哪个组件呢，可否指点一下，谢谢啊
