### ISSUE TITLE
[app.model] namespace should be unique，v2

### ISSUE THREAD

**Issue by niukui** [ant-design/ant-design-pro#3166]
![image](https://user-images.githubusercontent.com/21176188/50150701-b5b28a80-02f9-11e9-894e-bb9bfe56fca1.png)
router配置如上图，然后在pages中
![image](https://user-images.githubusercontent.com/21176188/50150754-d7ac0d00-02f9-11e9-86b5-3a765ccfa3f3.png)
bug不管我将studentServce.js中的namespace改成什么，都会提示
![image](https://user-images.githubusercontent.com/21176188/50150789-f8746280-02f9-11e9-8047-efb44b6285ad.png)

**Comment by yutingzhao1991** [comment]
看看可能是别的地方 model 的 namespace 重复了。

**Comment by niukui** [comment]
> 看看可能是别的地方 model 的 namespace 重复了。

我已经全局搜索过了没有重复，如果是别的地方重复那项目之前不就会报错了吗？可是现在是只要我在上图路径下的models中添加文件，就会报错

**Comment by niukui** [comment]
> 还要看你引用的地方，让周围的同事帮你review下代码，或者换个名字 试试

我是全局搜索的，没有重复，而且换名字肯定是没用的。情况是只要我添加任意名字的文件他都会报这个错，我找其他办法解决了，还是谢谢您

**Comment by RainManGO** [comment]
> 我是全局搜索的，没有重复，而且换名字肯定是没用的。情况是只要我添加任意名字的文件他都会报这个错，我找其他办法解决了，还是谢谢您

怎么解决的
