### ISSUE TITLE
Where is <GlobalHeader />?

### ISSUE THREAD

**Issue by AkA84** [ant-design/ant-design-pro#3167]
I can see that https://preview.pro.ant.design/dashboard/analysis is using a component called `<GlobalHeader />` and that this component is [present](https://github.com/ant-design/ant-design-pro/tree/master/src/components/GlobalHeader) in the source code as well, but I can't find it either on the [components list page](https://pro.ant.design/components/AvatarList/) nor in the package i get via 

```
$ npm install ant-design-pro@latest --save
```

same thing applies for [`<HeaderDropdown />`](https://github.com/ant-design/ant-design-pro/tree/master/src/components/HeaderDropdown)

Are these components available for use?

**Comment by afc163** [comment]
Here is all available components: https://pro.ant.design/components/AvatarList-cn

**Comment by AkA84** [comment]
@afc163 sorry, but how does that answer my question? I linked to https://pro.ant.design/components/AvatarList myself to point out that the component is not there even though it's obviously being used in the demo page https://preview.pro.ant.design/dashboard/analysis

Could you please provide some clarification? Is `<GlobalHeader />` available or not? If not, why is it showcased in the demo page and present in the source code?

**Comment by afc163** [comment]
We don't publish all components in `src/components` to npm now.

**Comment by AkA84** [comment]
thanks @afc163 for your answer, does it mean that at the moment it's not possible to, for example, fully recreate https://preview.pro.ant.design/dashboard/analysis with [ant-design-pro](https://www.npmjs.com/package/ant-design-pro) , that is by [using the pro components alone](https://pro.ant.design/docs/use-components-alone)? The only way to be able to fully recreate the demo page is to adopt the whole Pro "bundle" by cloning the repo as instructed [here](https://pro.ant.design/docs/getting-started#Installation)?

**Comment by AkA84** [comment]
@afc163 could you confirm that what i wrote above is correct? What if i pointed my package.json to use use a specific tag, like
```json
"ant-design-pro": "ant-design/ant-design-pro#2.1.1"
```
so that I would get the source code on the repo instead of the one you publish via npm. Do you see any potential problem with that?
