### ISSUE TITLE
pro 2.1.1打包之后index.html中多了一行less.mini.js的引入，导致样式混乱

### ISSUE THREAD

**Issue by zhangsai02** [ant-design/ant-design-pro#3169]
2.1.1版本npm run build之后index.html里怎么多了这一句
**<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>**
导致界面样式丢失

**Comment by chenshuai2144** [comment]
plugin.config.js 
删除里面的插件就好了

**Comment by zhangsai02** [comment]
// config.plugin('ant-design-theme').use(AntDesignThemePlugin, [
  //   {
  //     antDir: path.join(__dirname, '../node_modules/antd'),
  //     stylesDir,
  //     varFile: path.join(__dirname, '../node_modules/antd/lib/style/themes/default.less'),
  //     mainLessFile: outFile, //     themeVariables: ['@primary-color'],
  //     indexFileName: 'index.html',
  //   },
  // ]);
删了之后会对后续的样式有影响吗

**Comment by shotforsky** [comment]
我也遇到这个问题，注释了 plugin.config.js 中 ant-design-theme 插件，执行 npm run build 打包出来的 index.html 中就没有指向 less.min.js 的引用了。

观察页面是正常的。

![image](https://user-images.githubusercontent.com/14038117/55224079-a7ee9880-524a-11e9-86ea-51c236ed9bab.png)

**Comment by zsl1549** [comment]
@chenshuai2144 删除里面的插件就好了  就不能具体点吗？大哥 ？
