### ISSUE TITLE
Can't import Charts (Use pro components alone)

### ISSUE THREAD

**Issue by prapansak** [ant-design/ant-design-pro#317]
ERROR in `./node_modules/ant-design-pro/lib/Charts/Pie/index.js`
Module not found: Error: Can't resolve `antd/lib/divider`

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq-cn#%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Ant-Design-Pro%EF%BC%9F
