### ISSUE TITLE
新项目拉取之后报警告

### ISSUE THREAD

**Issue by ytxbnahn** [ant-design/ant-design-pro#3170]
index.js:2178 Warning: Failed value type: The value `isRequired` is marked as required in `Select`, but its value is `undefined`.

index.js:2178 Warning: Failed defaultValue type: The defaultValue `isRequired` is marked as required in `Select`, but its value is `undefined`.

**Comment by ytxbnahn** [comment]
node v10.9.0
npm v6.4.1

**Comment by chenshuai2144** [comment]
rc-select 用了 react 的新 api 造成的。因为你用的不是受控模式

**Comment by jeffmxzhao** [comment]
> rc-select 用了 react 的新 api 造成的。因为你用的不是受控模式
> 可以直接忽略

@chenshuai2144 看着难受

**Comment by sunlili810** [comment]
怎样去掉warning
