### ISSUE TITLE
手机浏览器打开白屏的问题

### ISSUE THREAD

**Issue by autotrans** [ant-design/ant-design-pro#3171]
官方预览的Demo同样会出现这样的问题。
https://preview.pro.ant.design/dashboard/analysis
手机浏览器打开白屏(已测试的手机包括一加5 小米8 华为荣耀8的自带浏览器 )，
在手机端，qq，微信，苹果Safari直接打开是没有问题的，
在pc端，chrome，ie，edge，qq浏览器都是没有问题。

为了兼容ie浏览器做了polyfill处理同样会出现这样的问题，不知道大家是怎么解决的？

**Comment by chenshuai2144** [comment]
用 vconsole 什么的看一看是什么 js 报错了，我们不承诺支持哪些很老的浏览器。

**Comment by autotrans** [comment]
直接白屏vconsole的按钮也是显示不出来的 这个不是支不支持很老浏览器的问题 市面上的Android手机几乎都遇到了这个问题 :(

**Comment by yemaozi5518** [comment]
华为荣耀10也出现这样的问题，怎么解决的 @autotrans @chenshuai2144

**Comment by yemaozi5518** [comment]
华为荣耀10安装的qq浏览器也是白页

**Comment by Happy4Java** [comment]
安卓QQ浏览器都有问题

**Comment by chenshuai2144** [comment]
小米浏览器可以，我这里没有华为的手机，我试试 qq 浏览器
