### ISSUE TITLE
单独项目可以跑，放在后台的static文件夹下报错

### ISSUE THREAD

**Issue by Jiangwr** [ant-design/ant-design-pro#3174]
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "index.html", template might not exist or might not be accessible by any of the configured Template Resolvers
![image](https://user-images.githubusercontent.com/19362571/50211113-c1ae5300-03b2-11e9-990b-0807b28e969b.png)

**Comment by netbird** [comment]
这个与ant design pro无关，与自身的框架有关吧。一个写着hello world空的html文件可以执行吗？简单来说编译后的文件，就是比hello world多了几个js 和css的引用。

**Comment by chenshuai2144** [comment]
二级目录需要单独配置

**Comment by Jiangwr** [comment]
> 二级目录需要单独配置

请问下需要ant design pro哪里配置呢

**Comment by Jiangwr** [comment]
> 这个与ant design pro无关，与自身的框架有关吧。一个写着hello world空的html文件可以执行吗？简单来说编译后的文件，就是比hello world多了几个js 和css的引用。

这个问题还是没有解决，另外两人打包的内容放在Spring Boot static文件夹下是可以跑的，我这边打包出来放在Spring Boot就不行，就很奇怪,前端代码重新拉过还是不行，然后基于这个报错，谷歌搜到的都是Spring boot相关，依照我这个情况，后台应该没有问题

**Comment by Jiangwr** [comment]
> 二级目录需要单独配置

修改完一个菜单名称之后，打包放到后台也出现这样的错误
