### ISSUE TITLE
如何与单点登陆系统集成

### ISSUE THREAD

**Issue by mushroomlb** [ant-design/ant-design-pro#3176]
当前后端是spring boot做的API接口，前端是ant-design-pro,用户打开系统时需要跳转到单点登陆系统，在单点登陆系统中登陆成功后单点登陆系统会调用spring boot 提供的callback,返回认证token，spring boot通过token到单点登陆系统获取用户信息并加载本系统数据库中的权限列表，返回到前端展示页面。
现在的问题：
1 前端页面如何跳转到单点登陆页面，试过直接用Authorizedzhogn加判断若没有权限则跳转到sso登陆页，但是url没有在路由中配置会出现问题。
2 spring boot 获取用户信息并加载本地数据库中的权限列表后，如何返回到前端展示页面。

**Comment by netbird** [comment]
这个登录是后端的。  如你在请求index的时候，如果登录了，返回index的内容。如果没登录 后端做个302跳转到认证中心页面(附上回调地址)。登录完成后，在跳回回调地址的url，url里面根据ticket信息，登录，返回用户对应的信息页面如index.html。然后加载js，初始化功能。还有不一定用路由。还可以用window.open(url); 这种方式，不是在前端路由里面，而是整体刷新页面式请求。

**Comment by mushroomlb** [comment]
@netbird 我现在是在前端判断是否已经登录，没有登录就跳转到认证中心，认证中心登录成功后调用我后端的callback，但是后端如何再返回到前端呢

**Comment by netbird** [comment]
@mushroomlb 前端页面也不是单独存在的吧 也是你请求http://hostname/abc/def 返回的，或者请求http://hostname/index 前端跳转到/abc/def生成的，没有登录跳转过去完成认证后，再跳回来，请求http://hostname/abc/def 就行了

**Comment by mushroomlb** [comment]
完成认证后，认证中心调用后端的callback，后端获取token和用户信息，在ant design pro 这个框架下如何将用户信息返回到前端阿。
现在做的是用户打开网站时通过currentUser跟后端交互，若后端返回403就跳转到单点登陆中心，完成登陆，单点登陆调用后端callback，后端完成获取信息后就不知道怎么做了，直接调用前端的地址，还是没有权限。
后端使用springboot + spring security

**Comment by mushroomlb** [comment]
已经可以了，现在是在Authorized.js中判断本地是否已经登陆，没有登陆就跳转到单点登陆中心，这里想改成从后端获取当前的登陆状态，不知道有没有解决方法 @netbird .用currentUser获取时就已经出来界面了，想在Authorized.js中实现，但是不知道props怎么传递过去

**Comment by netbird** [comment]
从后端获取？我是在请求http://host.com 第一个index页面的时候从后端计算，作为一个参数传到页面的一个变量里，然后在需要的地方menu=这个变量（原来是从config/route.config里面获得的）。
如：在document.ejs里面加入：
生产环境
const menuTree = <?php echo json_encode($menu_data); ?>;
如测试数据：
const menuTree = [{"id":"1","name":"test","authority":["op_node_1"],"icon":"tool"}];

在src/layouts/BasicLayout里面getMenuData方法 用这个变量就可以了。
window.menuTree
也许还有其他更好的方法吧，我只介绍我的做法，希望对你有用。

**Comment by zhang0ZGC** [comment]
我是在BasicLayout外面套了一个高阶组件，然后就是显示个loading，组件初始化时，就去验证用户是否登录，没权限就再跳到公司统一登录页，有权限就返回BasicLayout组件

**Comment by kuroismith** [comment]
> 我是在BasicLayout外面套了一个高阶组件，然后就是显示个loading，组件初始化时，就去验证用户是否登录，没权限就再跳到公司统一登录页，有权限就返回BasicLayout组件

请问如何验证用户是否登录?
