### ISSUE TITLE
动态菜单获取时，传入name值，会自动走国际化 查找对应key值，如何取消掉呢？

### ISSUE THREAD

**Issue by iquanzhan** [ant-design/ant-design-pro#3178]
进行动态菜单获取时，设置的name值，默认会走国际化formatterMessage方法，导致某些菜单打开时，会报如下错误：

> [React Intl] Missing message: "XXXX" for locale: "zh-CN" __stack_frame_overlay_proxy_console__ @ index.js:2178 index.js:2178 
> [React Intl] Cannot format message: "XXXX", using message id as fallback.

具体应该如何处理掉这个错误呢？刚接触，万分感谢

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js#L25
换掉这一样

**Comment by iquanzhan** [comment]
> https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js#L25
> 换掉这一样

const result = {
        ...item,
        name: item.name,
        locale,
        authority: item.authority || parentAuthority,
      };

此处已经修改为item.name,依旧提示如上问题

**Comment by iquanzhan** [comment]
> https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js#L25
> 换掉这一样

同时，BasicLayout文件中getPageTitle也修改了formatterMessage方法

**Comment by iquanzhan** [comment]
> @iquanzhan 配好后，是不报错了，但是不走国际化了。

是的，我的还是依旧有这个问题。修改后还是会有报错现象。还没有解决方案

**Comment by chengnuo** [comment]
> > @iquanzhan 配好后，是不报错了，但是不走国际化了。
> 
> 是的，我的还是依旧有这个问题。修改后还是会有报错现象。还没有解决方案

我在basiclayout 把
`
const pageName = formatMessage({
      id: currRouterData.locale || currRouterData.name,
      defaultMessage: currRouterData.name,
    });
`
改成
`
const pageName = {
      id: currRouterData.locale || currRouterData.name,
      // defaultMessage: currRouterData.name,
    };
`
虽然不报错了。但是国际化就没了。

**Comment by iquanzhan** [comment]
> > > @iquanzhan 配好后，是不报错了，但是不走国际化了。
> > 
> > 
> > 是的，我的还是依旧有这个问题。修改后还是会有报错现象。还没有解决方案
> 
> 我在basiclayout 把
> `const pageName = formatMessage({ id: currRouterData.locale || currRouterData.name, defaultMessage: currRouterData.name, });`
> 改成
> `const pageName = { id: currRouterData.locale || currRouterData.name, // defaultMessage: currRouterData.name, };`
> 虽然不报错了。但是国际化就没了。

你是想实现，如果国际化中找不到时，再走自定义的中文。还是？

**Comment by chengnuo** [comment]
@iquanzhan 我是想实现直接找中文（类似官网原生需求），我现在在debug了。一起加油

**Comment by chengnuo** [comment]
@iquanzhan 兄弟，我debug出来了。
```javascript
子集没有 locale: "menu.system"，这个属性，想办法解决这个就可以跟国际化关联了。
{
    "id": 18,
    "path": "/system",
    "name": "系统管理",
    "menuname": "系统管理",
    "pid": 0,
    "locale": "menu.system",
    "children": [
        {
            "id": 19,
            "path": "/user",
            "name": "user",
            "menuname": "用户管理",
            "pid": 18,
            "children": [
                {
                    "id": 20,
                    "path": "/system/UserList",
                    "name": "userList",
                    "menuname": "用户列表",
                    "pid": 19
                }
            ]
        },
        {
            "id": 21,
            "path": "/role",
            "name": "role",
            "menuname": "角色管理",
            "pid": 18,
            "children": [
                {
                    "id": 22,
                    "path": "/system/RoleList",
                    "name": "roleList",
                    "menuname": "角色列表",
                    "pid": 21
                }
            ]
        }
    ],
    "authority": [
        "admin",
        "user"
    ]
}
```

**Comment by chengnuo** [comment]
我已经解决了。
修改src/menu/models/menu.js formatter方法里面的 locale 属性。
动态获取的 item.children 没有 locale 属性，我现在是写死测试的。（源码是获取item.route来组装数据）
现在来记录，以便后面的人遇到问题可以得到思路并且解决。
