### ISSUE TITLE
Data lost in Pie while swicthing data category

### ISSUE THREAD

**Issue by HiroTang** [ant-design/ant-design-pro#3179]
![image](https://user-images.githubusercontent.com/39959321/50259572-9cb3f180-043f-11e9-97f8-d8b716542e71.png)

In Ant Design Pro Demo, the pie in home page(dashboard/analysis).
I clicked the first three items in legend and the pie changed to the rest items.
Then I switched the category above, the pie also show the rest three items.

![image](https://user-images.githubusercontent.com/39959321/50259756-527f4000-0440-11e9-8f2b-b41c54d86968.png)

Then I changed the category above to the old one, the first three items are gone. I have to refresh the whole page to bring them back.
![image](https://user-images.githubusercontent.com/39959321/50259817-996d3580-0440-11e9-9f8a-bece287b96fc.png)

Is this a problem? Or is it designed to this?
I hope all the data is correct when switching the category without refreshing the whole page.

**Comment by 133922249** [comment]
我的解决方案是给Pie增加一个属性key 每次data发生变化时 改变key 这样组件就会重置
