### ISSUE TITLE
This is bug?

### ISSUE THREAD

**Issue by wellorange** [ant-design/ant-design-pro#318]
![default](https://user-images.githubusercontent.com/24599707/33364023-9866caf0-d51d-11e7-9048-d76ed83bce37.PNG)

**Comment by MrPeak** [comment]
这个是响应式问题，你在比较窄的空间展示过多的元素，并且没有做挤压处理，所以就乱了，你可以自己处理，或者像 `pro` 的 demo 一样，通过空间区分来处理响应式
