### ISSUE TITLE
一个关于获取权限的问题

### ISSUE THREAD

**Issue by songhua-river** [ant-design/ant-design-pro#3182]
src\utils\authority.js 
这里的注释是说真是环境权限从后端获取，想问的是，登陆后就能拿到用户的当前权限在store中，但是怎么传入进来呢。 权限直接存在localestorage中合理么

**Comment by wangxulong** [comment]
![image](https://user-images.githubusercontent.com/8357515/50274887-187e6000-0479-11e9-8e64-e5397e159b5e.png)
![image](https://user-images.githubusercontent.com/8357515/50274898-1f0cd780-0479-11e9-857d-785ec27ae4be.png)

**Comment by peterlxb** [comment]
这里也只是从后端返回了在页面上渲染的路由
在route.config里面定义的路由还是会生效 ，在地址栏输入url地址还是能访问

**Comment by tqcc** [comment]
什么狗几把玩意 
弄的这么复杂 也没文档
真他妈操蛋

**Comment by xiaohuoni** [comment]
@tqcc 
想要控制权限，控制menu model里面的routerData，想要控制菜单，控制menu model里面的menuData。在https://github.com/ant-design/ant-design-pro/pull/3587 这次提交之后，这个问题应该可以很容易的处理了。如果你有更好的方案，或者看到更好的方案，欢迎分享和推荐。然后pro这么好的产品，请给个star！

**Comment by lemoncy** [comment]
@xiaohuoni 这久关注的动态路由和动态菜单，终于有官方的解决方案了，之前弄了个差不多的方案也是model增加路由和菜单，但是对pro不太熟悉，就搁浅等着了。
，使用pro没多久，觉得阿里的这个开源项目很赞。感谢你们的奉献！
@tqcc 言辞过激，有点过分了啊，你可以选择不用，都有一个过程的。得亏蚂蚁金服的开发人员有素质。

**Comment by afc163** [comment]
@lemoncy 不是每个维护者都是阿里/蚂蚁的，比如 @xiaohuoni 就是来自社区的核心开发人员。

**Comment by lemoncy** [comment]
@afc163 嗯嗯，多谢哈。感谢你们的努力！

**Comment by tqcc** [comment]
@lemoncy 老子就是素质低，操你娘个死逼

**Comment by afc163** [comment]
@xiaohuoni 没必要删，挂着挺好的。

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/264
