### ISSUE TITLE
pro 的 table 可以实现服务器多列排序吗?

### ISSUE THREAD

**Issue by maomft** [ant-design/ant-design-pro#3185]
如题,谢谢

**Comment by chenshuai2144** [comment]
和 antd 的是一样的，当然可以

**Comment by maomft** [comment]
> 和 antd 的是一样的，当然可以

https://github.com/ant-design/ant-design/edit/master/components/table/demo/reset-filter.md
这边提到了只支持单列排序。
我有点迷茫，不知如何实现。
-------
原文引用（
> 1. columns 中定义了 filteredValue 和 sortOrder 属性即视为受控模式。
> 2. 只支持同时对一列进行排序，请保证只有一列的 sortOrder 属性是生效的。
> 3. 务必指定 `column.key`。
）

**Comment by afc163** [comment]
目前不支持多列。

**Comment by maomft** [comment]
> 目前不支持多列。

谢谢您的解答
