### ISSUE TITLE
面包屑刷新页面后显示异常

### ISSUE THREAD

**Issue by jeffmxzhao** [ant-design/ant-design-pro#3186]
antd pro: 2.1.1
拉下代码后，添加从后台请求菜单: `getUserMenu`
修改models/menu.js
```js
import { getUserMenu } from '../services/admin';
```
```js
*getMenuData({ payload }, { call, put }) {
      const { routes, authority } = payload;
      const response = yield call(getUserMenu);
      console.log(response);
      const menuData = filterMenuData(memoizeOneFormatter(routes, authority));
      const breadcrumbNameMap = memoizeOneGetBreadcrumbNameMap(menuData);
      yield put({
        type: 'save',
        payload: { menuData, breadcrumbNameMap },
      });
    },
```
访问`详情页`->`基础详情页`:
基础详情页面包屑正常显示:`首页/详情页/基础详情页`
按F5刷新界面后,面包屑显示异常`首页`,后面的`详情页/基础详情页`不见了

**Comment by jeffmxzhao** [comment]
@hanwenbo 不知道你有没有遇到这个问题

**Comment by chenshuai2144** [comment]
第一次进入会有问题？

**Comment by jeffmxzhao** [comment]
@chenshuai2144 我发现设置`Table`->`defaultExpandAllRows`属性值为`true`,刷新页面后也会出现此问题

![](https://github.com/jeffmxzhao/images/blob/master/antd/table-defaultExpandAllRows.gif?raw=true)

还有之前的问题好像都是刷新后出现异常 [#3165](https://github.com/ant-design/ant-design-pro/issues/3165)

**Comment by cxlong89** [comment]
> @chenshuai2144 如图所示，第一次没有异常，刷新后出现的，
> ![](https://github.com/jeffmxzhao/images/blob/master/antd/breadcrumb.gif?raw=true)

一开始 menuData 还没取到值时，获取面包屑时 被memoizeOne缓存了

**Comment by wangxulong** [comment]
@jeffmxzhao 
![image](https://user-images.githubusercontent.com/8357515/50501077-5e967d80-0a90-11e9-8d64-d85473f142aa.png)

**Comment by hanwenbo** [comment]
@jeffmxzhao 您好 刚看到  我没遇到 因为我把面包屑删除了 这次没用到，看下官方提交的记录 保持更新

**Comment by jeffmxzhao** [comment]
@afc163 同步至最新代码，问题依旧
@wangxulong 用你的方法，问题得到解决，谢谢，另外`Table`中的`defaultExpandAllRows`设置为`true`，刷新后是否是这样的情况
![](https://github.com/jeffmxzhao/images/blob/master/antd/table-defaultExpandAllRows.gif?raw=true)
