### ISSUE TITLE
登陆页面设置成根目录后主页面访问不到

### ISSUE THREAD

**Issue by XuWuDeAi** [ant-design/ant-design-pro#3193]
我把user和Admin的根目录路由路径调换了，发现Admin路劲下的页面都访问不到
` // user
  {
    path: '/',
    component: '../layouts/UserLayout',
    routes: [     
      { path: '/',redirect: '/user/login'},
      { path: '/user/login', component: './User/Login' },
      { path: '/user/register', component: './User/Register' },
      { path: '/user/register-result', component: './User/RegisterResult' },
    ],
  },
 
  // app
  {
    path: '/Admin',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [     
      // dashboard
      { path: '/Admin/page/Home',  name: '首页设置',icon: 'dashboard',component:"./Admin/page/Home" },
      { path: '/Admin/page/Shop',  name: '商品上传',icon: 'dashboard',component:"./Admin/page/Shop" },
      { path: '/Admin/page/book',  name: '商品管理',icon: 'dashboard',component:"./Admin/page/book" },
      { path: '/Admin/page/Search', name: '搜索',icon: 'dashboard',component:"./Admin/page/Search" },
      { path: '/Admin/page/Order',  name: '订单管理',icon: 'dashboard',component:"./Admin/page/Order"},`

**Comment by chenshuai2144** [comment]
解决了吗？你的配置看起来没有问题
