### ISSUE TITLE
项目打包部署在nginx服务器上(非根目录), history browserHistory 模式下 404

### ISSUE THREAD

**Issue by 2248157705** [ant-design/ant-design-pro#3195]

**Comment by 2248157705** [comment]
突然又正常了

**Comment by Pancho2wang** [comment]
我也遇到了，不描述一下么？

**Comment by HQ1363** [comment]
同样遇到了，都是启用browserHistory模式后，服务端没有配合更新ng配置导致，导致前端无法知道如何路由了。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88
