### ISSUE TITLE
icon在不同的设备上显示的不一致

### ISSUE THREAD

**Issue by kateli** [ant-design/ant-design-pro#3198]
发现了一个很奇怪的问题
<Icon type="info-circle" style={{ fontSize: '16px', color: '#08c' }} />
icon是这么写的
但是在同事和我的电脑上看的时候不一样
同事的电脑上显示的是空心的
我的电脑上显示的是实心的
结果发布到测试和正式环境中  也出现了两套不一样的ui
线上环境是空心的icon
测试环境是实心的icon
同事：
![image](https://user-images.githubusercontent.com/8436428/50396177-3dd5db80-07a3-11e9-8cde-790beae0e3dc.png)
我的：
![image](https://user-images.githubusercontent.com/8436428/50396186-4c23f780-07a3-11e9-858f-74f3bcd32863.png)

**Comment by chenshuai2144** [comment]
https://ant.design/components/icon/#API

试着固定一下 theme
