### ISSUE TITLE
一个mobx版本的antd-pro

### ISSUE THREAD

**Issue by gzgogo** [ant-design/ant-design-pro#3199]
自己抽时间总结了一个mobx版本的，喜欢用mobx的可以参考一下，链接：https://github.com/gzgogo/antd-pro-mobx

**Comment by xiaohuoni** [comment]
@chenshuai2144 这些要不要统一发一个iss管理，还是写到官方文档里面？

**Comment by xiaohuoni** [comment]
加个社区版本？

**Comment by chenshuai2144** [comment]
加个 社区推荐的文档好了
