### ISSUE TITLE
import原生css不起作用，只能使用less吗？

### ISSUE THREAD

**Issue by SpiritLiftedHigh** [ant-design/ant-design-pro#320]

**Comment by afc163** [comment]
master 实测没问题。

**Comment by ldwonday** [comment]
其实他的意思是问，css因为引入会被模块化，但是不想模块化怎么办，比如我想引入iconfont.css，模块化会使得iconfont的class不起作用了！

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/issues/89
