### ISSUE TITLE
圣诞Button特效?

### ISSUE THREAD

**Issue by rellyCheng** [ant-design/ant-design-pro#3200]
![image](https://user-images.githubusercontent.com/22974879/50408157-f1c97c00-0820-11e9-8684-3d9c879f1b05.png)
定时器?还是说Button是远程调用的?

**Comment by zhichao8756** [comment]
目测应该是定时器

**Comment by Lubyam** [comment]
![image](https://user-images.githubusercontent.com/7630366/50408475-c301d480-0825-11e9-9f2a-f8bd323a9e8c.png)
![image](https://user-images.githubusercontent.com/7630366/50408477-c5642e80-0825-11e9-952b-53b9d74a9826.png)

**Comment by zhongdechan** [comment]
这个太坑人了！早上起来就被客户骂了~~~~

**Comment by estn** [comment]
![b3d8d5df9991a7864655044d75cb775b](https://user-images.githubusercontent.com/1539613/50408742-25f46b00-0828-11e9-9921-0be6ebc864d6.jpg)

**Comment by fanyingmao** [comment]
别搞这种彩蛋，这样怎么放心用。

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design/issues/13098

**Comment by lucas270** [comment]
> ![image](https://user-images.githubusercontent.com/22974879/50408157-f1c97c00-0820-11e9-8684-3d9c879f1b05.png)
> 定时器?还是说Button是远程调用的?

代码里面写死的，每年12.25都这样

**Comment by lenvo222** [comment]
彩蛋很棒

**Comment by Ivocin** [comment]
> > ![image](https://user-images.githubusercontent.com/22974879/50408157-f1c97c00-0820-11e9-8684-3d9c879f1b05.png)
> > 定时器? 还是说 Button 是远程调用的?
> 
> 高版本代码里面写死的，每年 12.25 都这样，将版本降到 3.92 以下就没有了

今年是第一年吧

**Comment by lucas270** [comment]
> > > ![image](https://user-images.githubusercontent.com/22974879/50408157-f1c97c00-0820-11e9-8684-3d9c879f1b05.png)
> > > 定时器? 还是说 Button 是远程调用的?
> > 
> > 
> > 高版本代码里面写死的，每年 12.25 都这样，将版本降到 3.92 以下就没有了
> 
> 今年是第一年吧

是鸭，估计也就只有今年了吧，现在卖声一片

**Comment by xiaohuoni** [comment]
已经回滚了。更新版本就好了https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c

**Comment by sidifen** [comment]
中奖了。。。happy every day, 真好~~
