### ISSUE TITLE
关于圣诞效果 今天能不能尽快出一个修正更新啊 并去除里面的其他彩蛋？

### ISSUE THREAD

**Issue by kalsolio** [ant-design/ant-design-pro#3202]
不要发一个致歉声明么，让跟圣诞节日有仇恨的民族如何好好做一个前端

**Comment by jiechud** [comment]
找到编译后的源码删除一下就可以了

**Comment by wyf0727** [comment]
Merry Christmas 单词还拼错了,我想问下,要是到清明节了,按钮会变成什么样子?

**Comment by xiaohuoni** [comment]
已回滚，更新版本
https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c

**Comment by dikang123** [comment]
npm update antd --save
