### ISSUE TITLE
babel plugin import

### ISSUE THREAD

**Issue by niukui** [ant-design/ant-design-pro#3205]
既然 [umi-plugin-react](https://umijs.org/zh/plugin/develop.html) 中默认配置了antd 为true，那为什么启动ant design pro的时候仍然提示
![image](https://user-images.githubusercontent.com/21176188/50410614-0a439180-0835-11e9-908e-55d132698d15.png)
1. 请问我如何确定这是默认配置未生效还是说这个warning有问题？
2. 如果自己在umi的config中增加配置
`plugins: [
    [
      'babel-plugin-import',
       {
        "libraryName": "antd",
        style: "css" ,
       }
    ],]`
还是有如上的warning，请问是我添加的方法有问题吗

**Comment by niukui** [comment]
> umi-plugin-react 中配置了 antd 应该就行了。怎么复现？是不是你引用的其他包全量打包了 antd ？

我只添加了react-image-lightbox，react-sortable-tree两个依赖，config里的配置都是ant pro默认的没有动过，如果像上边那样自己手动重新加babel-plugin-import也没起作用，是不是加错了

**Comment by chenshuai2144** [comment]
可以查一查打包的 antd 版本，是不是因为 cdn 什么的引入了

**Comment by afc163** [comment]
最好提供下重现，不然猜来猜去。

**Comment by Veigar-C** [comment]
我也有这个问题，找了package里面也没找到其他有关antd其他的库，也没发现cdn什么的引入。。
