### ISSUE TITLE
高级详情页没有了

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-pro#3208]
应该是有一个 https://preview.pro.ant.design/profile/advanced 这个的，现在没了。

![image](https://user-images.githubusercontent.com/1061968/50420842-519d4280-0874-11e9-88d0-d825cfe42caa.png)

**Comment by afc163** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
感觉权限的问题

**Comment by chenshuai2144** [comment]
重新登录试试。我这里是有的。

**Comment by afc163** [comment]
我也有诶

**Comment by chenshuai2144** [comment]
@yutingzhao1991 可能是他最近搞区块，权限搞错了

**Comment by yutingzhao1991** [comment]
看了下，删除下面这个 localStorage 就好了：

**Comment by chenshuai2144** [comment]
admin 才能看见的

**Comment by yutingzhao1991** [comment]
哦... 不过总觉得怪怪的，管理页权限感觉可以用一个示例来体现就好了~

**Comment by afc163** [comment]
权限是不是要在哪里加个标志，不然现在都不知道是啥权限。
