### ISSUE TITLE
关于带参数路由问题

### ISSUE THREAD

**Issue by icxcat** [ant-design/ant-design-pro#321]
**在这里请教各位大佬一个问题，本人刚接触react.. 基础和路由没掌握到位，只看了看dva。。项目比较急，所以来请教学习如何code这部分业务**
![5121511962076_ pic_hd](https://user-images.githubusercontent.com/22029390/33377783-a40f8506-d54d-11e7-8961-ad454916db5c.jpg)
![5131511962091_ pic_hd](https://user-images.githubusercontent.com/22029390/33377786-a6c69db6-d54d-11e7-9d6d-d268ee7923a1.jpg)
**这个是我用Vue实现的一个点击ID，然后路由跳转到更新页，获取到url中的id**
![5181511962187_ pic](https://user-images.githubusercontent.com/22029390/33378440-bdf63850-d54f-11e7-955e-c871e91257af.jpg)
![5161511962147_ pic](https://user-images.githubusercontent.com/22029390/33378432-b85d1062-d54f-11e7-89d2-28d2da4e17af.jpg)
现在我用Ant design pro实现了大部分业务，增删改查分页等//
现在需要点击跟踪按钮，拿到id，跳转到新页面去fetch数据
![5211511962309_ pic_hd](https://user-images.githubusercontent.com/22029390/33378456-cac0aaac-d54f-11e7-8dfb-a1412d7a342f.jpg)
**我尝试的方式是：**
1.在nav里配置一个页面，把name删掉，这样会隐藏
2.通过handler事件，获取record的id,利用路由push到详情页，使用query/search query的话是隐式的，url中没有出现id=xxx,可以使用location获取，但不太符合我的业务，使用search可以在url出现，但要怎么抓取 原生js么？
3.通过看最近的issue，nav里配置带参数路由，删掉name会出现面包屑问题，很困扰。感觉绕弯了。项目比较急，求教这里的业务到底怎么写code. 感谢。

**Comment by nikogu** [comment]
1. 创建对应路由的页面以及路由配置，`xxx/:id` https://github.com/ant-design/ant-design-pro/issues/104#issuecomment-343790174
2. 给 `跟踪` 添加点击事件
3. 点击事件里面用 `dispatch(routerRedux.push('xxx/:id'))` 跳转，具体可以参看 Pro 源码
4. 这类问题不属于 Pro 的『问题 & Bug』，下次请到 https://stackoverflow.com/ 或者 https://segmentfault.com/ 提问

**Comment by myyyy** [comment]
@nikogu 能不能麻烦写个实例，页面带参数跳转成功，但是不知道怎么把参数拿出来，看了源码，然后也搞不清楚，
这个地方没有实例，太难受了@

**Comment by chenshuai2144** [comment]
@myyyy 取参数是react-router得内容..

**Comment by stduolc** [comment]
我觉得G站当Q&A用也没啥，只要把issue打好分类，这种Q&A贴直接分到Q&A好了。G站连IM都有了，多个QA也不是不行。
