### ISSUE TITLE
如何设置网页地址栏前面的标志favicon图标,去除图标

### ISSUE THREAD

**Issue by jaunemmechine** [ant-design/ant-design-pro#3210]

**Comment by tomgao365** [comment]
如果想移除，修改 **scr/pages/document.ejs** 的代码
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ant Design Pro</title>
  <link rel="icon" href="/favicon.png" type="image/x-icon">
  <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js"></script>
</head>
<body>
  <noscript>Sorry, we need js to run correctly!</noscript>
  <div id="root"></div>
</body>
</html>
```
想更改，替换 **public/favicon.png** 文件

**Comment by wangxulong** [comment]
@tomgao365  注释后，刷新页面，初始化没有显示图标，一会又自动显示了，，是什么黑科技
![image](https://user-images.githubusercontent.com/8357515/50465664-9390ca80-09d3-11e9-9aae-bfba978457d9.png)
![image](https://user-images.githubusercontent.com/8357515/50465669-a1465000-09d3-11e9-81ba-396bbad9bd92.png)

**Comment by chenshuai2144** [comment]
是缓存。你需要先清理缓存

**Comment by wangxulong** [comment]
@chenshuai2144  大佬，不是缓存的问题吧，，缓存已经清理，，过去一晚上还是有问题，，，，，


![image](https://user-images.githubusercontent.com/8357515/50499828-b8df1080-0a87-11e9-9b9a-c13fe7ab9244.png)

**Comment by mstao** [comment]
重新编译一下就好了
