### ISSUE TITLE
umi build后缺少11.chunk.css和11.async.js

### ISSUE THREAD

**Issue by dropbug** [ant-design/ant-design-pro#3211]
使用ant design pro,打包后访问登录页面提示缺少文件。
打包的日志：
> ant-design-pro@2.1.1 build /Users/leo/VSCodeProjects/目录名/应用名
> umi build

[10:18:15 AM] webpack compiled in 15s 624ms
 DONE  Compiled successfully in 15631ms                                                                                                          10:18:15 AM

File sizes after gzip:

  387.9 KB   dist/vendors.async.js
  385.83 KB  dist/umi.js
  38.02 KB   dist/vendors.chunk.css
  10.51 KB   dist/umi.css
  9.99 KB    dist/14.async.js
  4.17 KB    dist/15.async.js
  3.95 KB    dist/23.async.js
  3.88 KB    dist/24.async.js
  3.83 KB    dist/50.async.js
  3.34 KB    dist/13.async.js
  3.23 KB    dist/32.async.js
  2.95 KB    dist/25.async.js
  2.83 KB    dist/16.async.js
  2.74 KB    dist/43.async.js
  2.39 KB    dist/pwacompat.min.js
  2.24 KB    dist/47.async.js
  2.24 KB    dist/17.async.js
  2.24 KB    dist/49.async.js
  2.12 KB    dist/14.chunk.css
  2.01 KB    dist/28.async.js
  1.9 KB     dist/38.async.js
  1.7 KB     dist/30.async.js
  1.65 KB    dist/18.async.js
  1.54 KB    dist/31.async.js
  1.47 KB    dist/29.async.js
  1.41 KB    dist/20.async.js
  1.4 KB     dist/26.async.js
  1.26 KB    dist/precache-manifest.80ecd1f07b19e06a3fc7beaca0b4e58f.js
  1.24 KB    dist/21.async.js
  1.12 KB    dist/42.async.js
  1.06 KB    dist/33.async.js
  1.04 KB    dist/17.chunk.css
  1.03 KB    dist/40.async.js
  1.01 KB    dist/15.chunk.css
  880 B      dist/12.async.js
  858 B      dist/44.async.js
  858 B      dist/service-worker.js
  852 B      dist/27.async.js
  851 B      dist/22.async.js
  822 B      dist/39.async.js
  805 B      dist/48.async.js
  764 B      dist/19.async.js
  757 B      dist/41.async.js
  755 B      dist/37.async.js
  741 B      dist/45.async.js
  728 B      dist/34.async.js
  713 B      dist/3.async.js
  707 B      dist/25.chunk.css
  701 B      dist/46.async.js
  628 B      dist/26.chunk.css
  624 B      dist/2.async.js
  529 B      dist/38.chunk.css
  525 B      dist/42.chunk.css
  524 B      dist/12.chunk.css
  511 B      dist/1.async.js
  510 B      dist/6.async.js
  510 B      dist/4.async.js
  500 B      dist/47.chunk.css
  484 B      dist/43.chunk.css
  468 B      dist/16.chunk.css
  463 B      dist/8.async.js
  435 B      dist/5.async.js
  433 B      dist/9.async.js
  423 B      dist/7.async.js
  420 B      dist/13.chunk.css
  406 B      dist/10.async.js
  319 B      dist/32.chunk.css
  317 B      dist/35.async.js
  316 B      dist/36.async.js
  314 B      dist/51.async.js
  287 B      dist/24.chunk.css
  268 B      dist/23.chunk.css
  205 B      dist/28.chunk.css
  137 B      dist/39.chunk.css
  116 B      dist/37.chunk.css
  116 B      dist/31.chunk.css
------------------- 分割线 ------------------------
![image](https://user-images.githubusercontent.com/10541081/50429620-87850a00-08fa-11e9-97dd-2b3f919210c3.png)

**Comment by yutingzhao1991** [comment]
看上去是开启了动态加载，你需要配置 https://umijs.org/zh/config/#publicpath 才能让网站正确的找到你的 JS。

**Comment by dropbug** [comment]
解决了。
服务器nginx配置中的sendfile是on,缓存了一些文件。
