### ISSUE TITLE
在彩蛋问题后，升级到antd 3.11.6后，antd pro 中的语言 为英文，且改变不了

### ISSUE THREAD

**Issue by xtgss007** [ant-design/ant-design-pro#3212]
antd Version
3.11.6

antd pro Version
2.1.1

Environment
Win10 X64、Chrome

问题描述
在彩蛋问题后，升级到antd 3.11.6后，antd pro 中的语言 为英文，且改变不了

设置：

![1](https://user-images.githubusercontent.com/7730781/50430570-acc84700-08ff-11e9-9bcf-dd6416473bf8.png)

结果：
![2](https://user-images.githubusercontent.com/7730781/50430584-b94c9f80-08ff-11e9-9f3b-00c5ee7b7795.png)
![3](https://user-images.githubusercontent.com/7730781/50430585-b9e53600-08ff-11e9-93da-80eacffa870f.png)
![4](https://user-images.githubusercontent.com/7730781/50430586-b9e53600-08ff-11e9-8276-4c08496975e8.png)

**Comment by Anonymity94** [comment]
我用 antd pro Version 2.1.1 测试了一下

antd Version
测试结果如下：
3.10.10、3.11.1、3.11.2 -- 正常
3.11.3、3.11.4，3.11.5，3.11.6 都出现了上述问题

你可以先锁定版本到 3.10.10

**Comment by xtgss007** [comment]
@Anonymity94 谢谢排查及指出 问题

**Comment by yutingzhao1991** [comment]
这个问题已经在 umi 中兼容掉了，升级 umi 即可 https://github.com/umijs/umi/pull/1703

**Comment by dargonpaul** [comment]
> ### 处理办法
> 升级 `umi` 和 `umi-plugin-react`的版本
> 
> ```
> "umi": "^2.2.9"
> "umi-plugin-react": "^1.2.4"
> ```

问题已解决，谢谢猴哥。

**Comment by dargonpaul** [comment]
@Anonymity94   昨天升级umi 和 umi-plugin-react版本后，出现了开发时，代码编译导致服务崩溃，报错信息  path.replace is not a function， 还有一个问题，代码中使用未定义的变量，编译时不再报错，这种情况

**Comment by ch-liuzhide** [comment]
so?到底解决了吗 @dargonpaul

**Comment by jjwong1991** [comment]
> @Anonymity94 昨天升级umi 和 umi-plugin-react版本后，出现了开发时，代码编译导致服务崩溃，报错信息 path.replace is not a function， 还有一个问题，代码中使用未定义的变量，编译时不再报错，这种情况

看下 #3230 
升级最新版umi，然后start命令改成
`cross-env APP_TYPE=site PROGRESS=none umi dev`
