### ISSUE TITLE
手机上不显示页面

### ISSUE THREAD

**Issue by sanrentai** [ant-design/ant-design-pro#3214]
当我在手机浏览器上输入  https://preview.pro.ant.design这个地址，显示一个空白的页面。
当我把这个地址转换成二维码后，使用微信的扫一扫，能够打开页面。但使用支付宝的扫一扫无法打开页面。
UC浏览器白屏，1加手机自带浏览器白屏。

**Comment by chenshuai2144** [comment]
pro 只支持现代浏览器，版本比较低的 chrome 也可能不支持的

**Comment by wuyinggui** [comment]
我也发现了这个问题，我们是做钉钉通知，点击后展示的页面（钉钉内置浏览器内打开和浏览器打开）用的是ant design pro，v2版本的不展示，v1的展示正常，而且也是响应式布局，另外微信的内置浏览器能打开v2版本，谷歌浏览器也能，不明白为啥1.0的支持，2.0的不支持，急求兼容方案
