### ISSUE TITLE
build 到线上, 登录报错

### ISSUE THREAD

**Issue by mofengfs** [ant-design/ant-design-pro#3216]
线下版本可以登录, 但是打包上线之后就不可以登录了, 数据和逻辑都没改, 都是用antd pro mock版本的数据和逻辑.

**Comment by mofengfs** [comment]
@imhele 
数据也是没改动过的, 都是antd pro 自带的数据
![image](https://user-images.githubusercontent.com/16655229/50439264-63dab780-092c-11e9-9de0-6bc559b08581.png)
![image](https://user-images.githubusercontent.com/16655229/50439299-7fde5900-092c-11e9-839d-a59294ecbffc.png)

**Comment by imhele** [comment]
build 不会把 mock 文件打包进去。[umijs - mock](https://umijs.org/zh/guide/mock-data.html) 的文档是这样描述的：
> 本地启动的 umi dev 会跟此配置文件匹配请求路径以及方法，如果匹配到了，就会将请求通过配置处理
也就是只有开发环境才使用 mock

**Comment by mofengfs** [comment]
@imhele 
如果我有特殊需求 ,  需要mock的在线支持怎么办呢 ?

**Comment by imhele** [comment]
用 node 另起一个 http server

**Comment by shuizhongyueming** [comment]
如果都是用的antd pro的样例里面的mock数据而且没有做任何改动的话

官网的[构建和发布](https://pro.ant.design/docs/deploy-cn#%E4%BD%BF%E7%94%A8-nginx)里面有这种需求的满足方法

以nginx的配置为例

```
    location /api {
        proxy_pass https://preview.pro.ant.design;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
```

这样所有请求到/api的请求，会交由`preview.pro.ant.design`来处理

**Comment by mofengfs** [comment]
@imhele @shuizhongyueming 
虽然你们说的我目前实现起来有困难, 但是还是非常感谢二位的解答

**Comment by eggachecat** [comment]
理论上把request的部分换成promise+把mock的内容复制过来就可以了
感觉这个可以自动化放在umi吗?
