### ISSUE TITLE
build之后，js文件请求路径出错

### ISSUE THREAD

**Issue by soolx** [ant-design/ant-design-pro#322]
已经在.roadhogrc中添加
 ` "publicPath": "/api/file"`
index.html请求的js和css正常`**/api/file/**.js`
然后动态加载别的js文件时，路径变成`**/api/file**.js`
不会在file后面添加 “/”

**Comment by nikogu** [comment]
try "publicPath": "/api/file" -> "publicPath": "/api/file/"

**Comment by soolx** [comment]
尝试过 `"publicPath": "/api/file/"`，问题依旧

**Comment by afc163** [comment]
你需要把你的具体问题描述清楚，必要的时候给截图。

**Comment by afc163** [comment]
信息不够。

给出可重现的 repo 吧，我会 reopen。
