### ISSUE TITLE
pro 有tab页和锚点结合的例子吗 页面滚动是tab也会跟着切换

### ISSUE THREAD

**Issue by wssgchungang** [ant-design/ant-design-pro#3220]

**Comment by dazxcd** [comment]
FullPage.tsx

import { ConnectProps } from '@/models/connect';
import { connect } from 'dva';
import React, { Component } from 'react';
import FullPageLess from './FullPage.less';

interface FullPageProps extends Required<ConnectProps> {
  loading: boolean;
}

@connect()
class FullPage extends Component<FullPageProps> {

  init(){

  }

  componentWillUnmount() {
    document.body.addEventListener('touchmove', this.leave,true);
  }

  leave(){

  }

  render() {
    return (
      <div className={FullPageLess.pure}>
        <div id="pureFullPage" className={FullPageLess.pureFullPage}>
          <div className={FullPageLess['page']}>
            <p>Page 1</p>
          </div>
          <div className={FullPageLess.page}>
            <p>Page 2</p>
          </div>
          <div className={FullPageLess.page}>
            <p>Page 3</p>
          </div>
          <div className={FullPageLess.page}>
            <p>Page 4</p>
          </div>
        </div>
      </div>
    );
  }

  componentDidMount() {
    // 创建全屏滚动实例，并初始化
    document.getElementsByTagName('html')[0].style.overflow = 'hidden'
    this.init();
    new PureFullPage().init();

  }
}

export default FullPage;

/**
 * utils 为工具函数对原生API做兼容性处理及提取公共方法
 */
const utils = {
  // 鼠标滚轮事件
  getWheelDelta(event) {
    if (event.wheelDelta) {
      // 第一次调用之后惰性载入
      this.getWheelDelta = event => event.wheelDelta;

      // 第一次调用使用
      return event.wheelDelta;
    }
    // 兼容火狐
    this.getWheelDelta = event => -event.detail;
    return -event.detail;
  },
  // 防抖动函数，method 回调函数，context 上下文，event 传入的时间，delay 延迟函数
  // 调用的时候直接执行，注意和 throttle 在使用的时候的区别
  debounce(method:{tId:any,call:any}, context:any, event:any, delay:number) {
    clearTimeout(method.tId);
    method.tId = setTimeout(() => {
      method.call(context, event);
    }, delay);
  },
  // 截流函数，method 回调函数，context 上下文，delay 延迟函数，
  // 返回的是一个函数
  throttle(method:any, context:any, delay:number) {
    let wait = false;
    return function(...args) {
      if (!wait) {
        method.apply(context, args);
        wait = true;
        setTimeout(() => {
          wait = false;
        }, delay);
      }
    };
  },
  // 删除 类名
  deleteClassName(el:React.ElementType<any>, className:string) {
    if (el.classList.contains(className)) {
      el.classList.remove(className);
    }
  },
  // polyfill Object.assign
  polyfill() {
    if (typeof Object.assign !== 'function') {
      Object.defineProperty(Object, 'assign', {
        value: function assign(target:any) {
          if (target == null) {
            throw new TypeError('Cannot convert undefined or null to object');
          }
          const to = Object(target);
          for (let index = 1; index < arguments.length; index++) {
            const nextSource = arguments[index];
            if (nextSource != null) {
              for (const nextKey in nextSource) {
                if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
                  to[nextKey] = nextSource[nextKey];
                }
              }
            }
          }
          return to;
        },
        writable: true,
        configurable: true,
      });
    }
  },
};




class PureFullPage {
  options: {
    isShowNav: boolean,
    delay: number,
    definePages(): void
  };
  container:any;
  containerOffsetTop:number;
  pagesNum:number;
  navDots:any[];
  viewHeight:number;
  currentPosition:number;
  DELAY:number;
  startY:number|undefined;
  constructor(options:any) {
    // 默认配置
    const defaultOptions = {
      isShowNav: true,
      delay: 1000,
      definePages: () => {},
    };
    utils.polyfill();
    // 合并自定义配置
    this.options = Object.assign(defaultOptions, options);
    // 将用户自定义函数绑定到实例 this
    this.options.definePages = this.options.definePages.bind(this);
    // 获取翻页容器
    this.container = document.querySelector('#pureFullPage');
    // 获取翻页容器初始高度差
    this.containerOffsetTop = document.querySelector('#pureFullPage').offsetTop|0;
    // 获取总页数，创建右侧点导航时用
    this.pagesNum = document.querySelectorAll('.antd-pro-pages-test-full-page-page').length;
    // 初始化右侧点导航，以备后用
    this.navDots = [];
    // 获取当前视图高度
    this.viewHeight = document.documentElement.clientHeight;
    // 当前位置，负值表示相对视图窗口顶部向下的偏移量
    this.currentPosition = 0;
    // 截流/间隔函数延迟时间，毫秒
    this.DELAY = this.options.delay;
    // 检测滑动方向，只需要检测纵坐标
    this.startY = undefined;
  }
  // window resize 时重新获取位置
  getNewPosition() {
    this.viewHeight = document.documentElement.clientHeight;
    this.container.style.height = `${this.viewHeight}px`;
    let activeNavIndex:number = 0;
    this.navDots.forEach((e, i) => {
      if (e.classList.contains(FullPageLess.active)) {
        activeNavIndex = i;
      }
    });
    this.currentPosition = -(activeNavIndex * this.viewHeight);
    this.turnPage(this.currentPosition);
  }
  handleWindowResize(event:any) {
    // 设置防抖动函数
    utils.debounce(this.getNewPosition, this, event, this.DELAY);
  }
  // 页面跳转
  turnPage(height:number) {
    this.container.style.top = `${height}px`;
  }
  // 随页面滚动改变样式
  changeNavStyle(height:number) {
    if (this.options.isShowNav) {
      this.navDots.forEach(el => {
        utils.deleteClassName(el, FullPageLess.active);
      });

      const i = -(height / this.viewHeight);
      //防止报错
      if(i<0||i>this.pagesNum){
        return;
      }
      this.navDots[i].classList.add(FullPageLess.active);
    }
  }
  // 创建右侧点式导航
  createNav() {
    const nav = document.createElement('div');
    nav.className = FullPageLess.nav;
    this.container.appendChild(nav);

    // 有几页，显示几个点
    for (let i = 0; i < this.pagesNum; i++) {
      nav.innerHTML += '<p class="nav-dot"><span></span></p>';
    }

    const navDots = document.querySelectorAll('.nav-dot');
    this.navDots = Array.prototype.slice.call(navDots);

    // 添加初始样式
    this.navDots[0].classList.add(FullPageLess.active);

    // 添加点式导航点击事件
    this.navDots.forEach((el, i) => {
      el.addEventListener('click', () => {
        // 页面跳转
        this.currentPosition = -(i * this.viewHeight);
        // 处理用户自定义函数
        this.options.definePages();
        this.turnPage(this.currentPosition);

        // 更改样式
        this.navDots.forEach(el => {
          utils.deleteClassName(el, FullPageLess.active);
        });
        el.classList.add(FullPageLess.active);
      });
    });
  }
  goUp() {
    // 只有页面顶部还有页面时页面向上滚动
    if (-(this.container.offsetTop-this.containerOffsetTop) >= this.viewHeight) {
      // 重新指定当前页面距视图顶部的距离 currentPosition，实现全屏滚动，currentPosition 为负值，越大表示超出顶部部分越少
      this.currentPosition = this.currentPosition + this.viewHeight;

      this.turnPage(this.currentPosition);
      this.changeNavStyle(this.currentPosition);
      // 处理用户自定义函数
      this.options.definePages();
    }
  }
  goDown() {
    // 只有页面底部还有页面时页面向下滚动
    if (-(this.container.offsetTop-this.containerOffsetTop) <= this.viewHeight * (this.pagesNum - 2)) {
      // 重新指定当前页面距视图顶部的距离 currentPosition，实现全屏滚动，currentPosition 为负值，越小表示超出顶部部分越多
      this.currentPosition = this.currentPosition - this.viewHeight;

      this.turnPage(this.currentPosition);
      this.changeNavStyle(this.currentPosition);

      // 处理用户自定义函数
      this.options.definePages();
    }
  }
  // 鼠标滚动逻辑（全屏滚动关键逻辑）
  scrollMouse(event: React.MouseEvent) {
    const delta = utils.getWheelDelta(event);
    // delta < 0，鼠标往前滚动，页面向下滚动
    if (delta < 0) {
      this.goDown();
    } else {
      this.goUp();
    }
  }
  // 触屏事件
  touchEnd(event: React.MouseEvent) {
    const endY = event.changedTouches[0].pageY;
    if (endY - this.startY < 0) {
      // 手指向上滑动，对应页面向下滚动
      this.goDown();
    } else {
      // 手指向下滑动，对应页面向上滚动
      this.goUp();
    }
  }
  // 初始化函数
  init() {
    this.container.style.height = `${this.viewHeight}px`;
    // 创建点式导航
    if (this.options.isShowNav) {
      this.createNav();
    }
    // 设置截流函数
    const handleMouseWheel = utils.throttle(this.scrollMouse, this, this.DELAY);

    // 鼠标滚轮监听，火狐鼠标滚动事件不同其他
    if (navigator.userAgent.toLowerCase().indexOf('firefox') === -1) {
      document.addEventListener('mousewheel', handleMouseWheel);
    } else {
      document.addEventListener('DOMMouseScroll', handleMouseWheel);
    }

    // 手机触屏屏幕
    document.addEventListener('touchstart', event => {
      this.startY = event.touches[0].pageY;
    });
    const handleTouchEnd = utils.throttle(this.touchEnd, this, 500);
    document.addEventListener('touchend', handleTouchEnd);
    document.addEventListener('touchmove', event => {
      event.preventDefault();
    });

    // 窗口尺寸变化时重置位置
    window.addEventListener('resize', this.handleWindowResize.bind(this));
  }
}

FullPage.less

@import '~antd/lib/style/themes/default.less';
@import '~@/utils/utils.less';

.page {
  display: flex;
  justify-content: center;
  align-items: center;
  width:100%;height:100%;
      & p {
        font-size: 66px;
      }

      &:nth-child(1) {
        background: lightpink no-repeat center/cover;
      }

      &:nth-child(2) {
        background: lightgreen no-repeat center/cover;
      }

      &:nth-child(3) {
        background: lightskyblue no-repeat center/cover;
      }

      &:nth-child(4) {
        background: lightgray no-repeat center/cover;
      }
}

.pure{
  padding:0;margin:0;overflow:hidden
}

.pureFullPage{
  position:relative;top:0;transition:all 1s ease;
  .nav{
    position:fixed;top:50%;right:39px;width:18px;transform:translateY(-50%);
    p{
      width:18px;height:20px;padding:14px 0;margin:0 auto;cursor:pointer;
      span{
        display:block;position:relative;top:50%;transform:translateY(-50%);width:6px;height:12px;margin:0 auto;background-color:rgba(255,255,255,.6);border-radius:12px;transition:all 150ms ease-in-out
      }
      &:hover{
        span{
          width:8px;height:16px;background-color:#fff;
        }
      }
    }
  }
}

.active{
  span{
    width:10px!important;height:20px!important;background-color:#fff!important;
  }
}

landaima仅供参考
