### ISSUE TITLE
在手机端预览时，侧边菜单样式问题

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#3224]
问题如图：
![image](https://user-images.githubusercontent.com/12181423/50464190-8a4f3000-09ca-11e9-9aa5-1db7bb7966b0.png)

**Comment by chenshuai2144** [comment]
赞，绑定一下这个 issue

**Comment by hqwlkj** [comment]
是的

**Comment by nextglabs** [comment]
It seems like this issue is back again, here is a proof from the latest version shown on the preview website
<img width="612" alt="antd-pro-bug-side-drawer-padding" src="https://user-images.githubusercontent.com/42464680/70810903-e28e6600-1dc4-11ea-9d71-76596cbadae5.png">
