### ISSUE TITLE
报错：Uncaught SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by chengnuo** [ant-design/ant-design-pro#323]
报错：Uncaught SyntaxError: Unexpected token )

- 浏览器：搜狗浏览器6.2.5
- 报错定位，最新骨架。
- 如何重现 点击 https://github.com/ant-design/ant-design-pro/archive/master.zip 下载到本地后解压。

但是在搜狗6.2.5官网的demo是没问题的。
https://preview.pro.ant.design/
尝试过debug，因为太卡，无法定位。

**Comment by nikogu** [comment]
内核是 ie 吗

**Comment by yesmeck** [comment]
应该是同一个问题 https://github.com/ant-design/ant-design-pro/issues/210
