### ISSUE TITLE
项目跑起来后隔一段时间就自动挂了

### ISSUE THREAD

**Issue by Fntys** [ant-design/ant-design-pro#3230]
![qdpp mqnbw3 9 b t wy50](https://user-images.githubusercontent.com/13896710/50468792-9516be80-09e4-11e9-8b50-0b9313cf43bd.png)

**Comment by chenshuai2144** [comment]
@sorrycc  看一下

**Comment by sorrycc** [comment]
等今天发布新版后再试试。

**Comment by jjwong1991** [comment]
![image](https://user-images.githubusercontent.com/15044929/50589630-5d1aea00-0ec2-11e9-9202-219a2bce2810.png)
已升级umi最新版，问题依旧存在

**Comment by sorrycc** [comment]
加 `PROGRESS=none` 试试。

**Comment by jjwong1991** [comment]
@Fntys 大哥这个是cross-env的参数 加在cross-env 和 umi 之间，而且port最好也用cross-env处理一下，不然win和linux环境可能会出现命令不兼容的情况，像下面这样
cross-env APP_TYPE=site PROGRESS=none PORT=800 umi dev

**Comment by Fntys** [comment]
> 这个问题解决了吗？我这7，8个项目总崩，我以为电脑出问题，都准备换电脑了

cross-env APP_TYPE=site PROGRESS=none PORT=800 umi dev 
这样我可以了，你试下

**Comment by sorrycc** [comment]
@Fled8617 你也是 windows 电脑？

**Comment by Fled8617** [comment]
> @Fled8617 你也是 windows 电脑？

是的

**Comment by hankaibo** [comment]
今天(2019/2/20)，依然出现此问题。
