### ISSUE TITLE
ant-design-pro/scripts/lint-prettier.js 文件报错

### ISSUE THREAD

**Issue by yafanz** [ant-design/ant-design-pro#3231]
刚刚更新了最新的代码，更新了本地node_modules，代码提交到git的时候报了error，/ant-design-pro/scripts/lint-prettier.js:46
  .finally(() => {
          ^

TypeError: Promise.all(...).then(...).catch(...).finally is not a function

咋整 ？ 怎么处理

**Comment by chenshuai2144** [comment]
可以给个截图吗？

**Comment by yafanz** [comment]
> 可以给个截图吗？

![image](https://user-images.githubusercontent.com/32256182/50477889-5cd5a700-0a09-11e9-9bc6-848eb346da3b.png)

**Comment by yafanz** [comment]
> 升级一波 node.js试试

原来的node版本是8.10，升级到11之后是ok的，建议在package.json中对node版本进行声明

**Comment by sxh2000251** [comment]
升级到10.15也好了

**Comment by xiaoshui222** [comment]
> > 升级一波 node.js试试
> 
> 原来的node版本是8.10，升级到11之后是ok的，建议在package.json中对node版本进行声明，感谢回复
我的node是11，不行哎

**Comment by GodEngine** [comment]
同样的问题，node版本是8.11.2的也不行，醉了。

**Comment by GodEngine** [comment]
> > > 升级一波 node.js试试
> > 
> > 
> > 原来的node版本是8.10，升级到11之后是ok的，建议在package.json中对node版本进行声明，感谢回复
> > 我的node是11，不行哎

你的后来咋解决的？

**Comment by GodEngine** [comment]
好吧，结果在另一个issue里找到了最简单的处理方法https://github.com/ant-design/ant-design-pro/issues/3601。。。
