### ISSUE TITLE
`npm run test:all` doesn't stop the development server after tests

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ant-design/ant-design-pro#3232]
Steps to reproduce:

1. Run `npm run test:all`, all tests pass.
2. Run `npm run test:all` again.

Expected behavior: the second run should run all tests and the tests should pass.

Actual behavior: the output is `Something is already running on port 8000.`, the script exits without running any tests.

Ant Design Pro version: a5d1979
Platform: Ubuntu 18.10

**Comment by EvgenyOrekhov** [comment]
@chenshuai2144 I run `npm run test:all` multiple times per day. I write code, then I run `npm run test:all`, I write code, then `npm run test:all`... If the `run-tests.js` script starts the development server, then it should clean up after itself by shutting it down after the tests.

**Comment by chenshuai2144** [comment]
you can run npm run start ,then npm run test

**Comment by EvgenyOrekhov** [comment]
@chenshuai2144 My CI (GitLab Runner) doesn't ever restart, so I have the same problem on my CI.

**Comment by chenshuai2144** [comment]
Ok. Are you interested in perfecting this script?
I can't leave now.
I think there is a problem here.
https://github.com/ant-design/ant-design-pro/blob/b06edf351f595e77e83a343c3ac9175dab15db99/tests/run-tests.js#L20

**Comment by EvgenyOrekhov** [comment]
Yes, I am. I submitted a pull request https://github.com/ant-design/ant-design-pro/pull/3233. I tested my fix on my machine and it works, but it fails on your CircleCI and I don't know why. I need help with `Error: spawn lsof ENOENT`: https://circleci.com/gh/ant-design/ant-design-pro/2146?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

**Comment by chenshuai2144** [comment]
you can kill(process.env.PORT || 8000) in start

**Comment by EvgenyOrekhov** [comment]
@chenshuai2144 It didn't help, still getting `Error: spawn lsof ENOENT`.

**Comment by chenshuai2144** [comment]
Because the ci image does not have the lsof command
