### ISSUE TITLE
运行 npm  test报错

### ISSUE THREAD

**Issue by songhua-river** [ant-design/ant-design-pro#3235]
Homepage › test pages /message-manager/notification/editform

net::ERR_CONNECTION_REFUSED at http://localhost:8000/message-manager/notification
是哪里配置的有问题

**Comment by songhua-river** [comment]
> 你保证你这个 router 是存在的吗？
存在的是路由里面配置的

**Comment by chenshuai2144** [comment]
你的这个错误是代码超时的问题，你本地启动了一个服务吗？
这个是 e2e 测试
