### ISSUE TITLE
关于标题和默认颜色问题

### ISSUE THREAD

**Issue by zhangweitao521** [ant-design/ant-design-pro#3238]
1.无法国际化登录页面的标题；
2.切换为顶部菜单布局后，标题出现了Ant Design Pro;
3.建议官方将标题设置为一个字段；
4.默认颜色更改后，有些地方的颜色没有变过来，在设置中更换是正常的；
![qq 20181227200117](https://user-images.githubusercontent.com/22015641/50479900-e7230880-0a13-11e9-820d-305f22601521.png)
![qq 20181227200953](https://user-images.githubusercontent.com/22015641/50479905-eb4f2600-0a13-11e9-8fd7-75b4bd998f1d.png)
![qq 20181227202940](https://user-images.githubusercontent.com/22015641/50480317-2fdbc100-0a16-11e9-9301-36cfaf852738.png)

**Comment by afc163** [comment]
>  3.建议官方将标题设置为一个字段；

更多 Pro 的配置就出来了。cc @chenshuai2144

**Comment by chenshuai2144** [comment]
title 是根据
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L208
这一行修改的，你可以修改这里。

>更多 Pro 的配置就出来了 

的确应该搞更多配置

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/3309
加了一个新的配置
