### ISSUE TITLE
拉取最新master，启动直接报错 commit b06edf35

### ISSUE THREAD

**Issue by super-ppx** [ant-design/ant-design-pro#3241]
代码未作任何修改

![image](https://user-images.githubusercontent.com/16098143/50507419-7eda3280-0ab8-11e9-87b9-cf0246abd79b.png)

**Comment by afc163** [comment]
控制台里看看是不是有 js 没加载成功。

**Comment by super-ppx** [comment]
确认了，dataset没加载到，gw.alipayobjects.com 这个域名可能被公司封掉了

**Comment by afc163** [comment]
😂

**Comment by chenshuai2144** [comment]
g2他们发个 npm 多好。
