### ISSUE TITLE
关于生命周期以及store值的调用问题

### ISSUE THREAD

**Issue by mofengfs** [ant-design/ant-design-pro#3243]
**有这么一个场景:**
1.某个(以下简称A页面)页面在加载的时候不带参数向服务端发送默认数据请求;
2.A页面的下拉选择, 选择某个value之后, 以这个value作为参数向服务端发送数据请求;
3.用的都是同一个数据接口和effects业务逻辑;
4.当选择过value以后, 下次再打开这个页面, 就不要再发送不带value的数据请求给服务端了.

**需要解决的问题:**
5.目前在生命周期componentDidMount中, 是获取不到更新后的value值的, 我拿不到value就无法做限制性的判断条件.

**请问如何解决这个问题 ? 我的主要代码如下:** 
![1](https://user-images.githubusercontent.com/16655229/50510549-252c3500-0ac5-11e9-8809-3bf2ad01780c.png)
![2](https://user-images.githubusercontent.com/16655229/50510554-29585280-0ac5-11e9-9dab-c71e1bfe649c.png)

**Comment by chenshuai2144** [comment]
设置默认值。或者去componentDidUpdate里面判断
