### ISSUE TITLE
采用Webpack4重写Antd配置，发现less的merge操作没法进行

### ISSUE THREAD

**Issue by DaqingFeng** [ant-design/ant-design-pro#3244]
配置信息如图，
![issue](https://user-images.githubusercontent.com/10512467/50511941-84d90f00-0aca-11e9-81df-2e8cfd93d245.png)

报错如图，
![webpack](https://user-images.githubusercontent.com/10512467/50511926-7c80d400-0aca-11e9-8897-b13766c3c7c3.png)

这两个plugin我看路径也都ok，请问怎么修复比较好，谢谢！

**Comment by chenshuai2144** [comment]
建议使用 umi,这个插件是我为了满足需求写的，健壮性很差

**Comment by DaqingFeng** [comment]
好的，如果用其它开源工具来操作这套框架就会显得笨拙，所以想改个版，谢谢
