### ISSUE TITLE
关于antd pro在不同用户角色之间切换的问题

### ISSUE THREAD

**Issue by Stayup379** [ant-design/ant-design-pro#3246]
我们在使用antd pro进行项目开发的时候碰到一点问题，就是刚开始用【老师】身份登录的时候，有一个“代录”按钮点进去可以切换到【学生】的身份进行信息代录，两种角色的界面是不一样的，我们已经把不同的用户身份和界面的authority设置好了，接下来该怎么实现角色的切换，和界面的重新渲染呢？

**Comment by imhele** [comment]
```js
import { setAuthority } from '@/utils/authority';
import { reloadAuthorized } from '@/utils/Authorized';
setAuthority('student');
reloadAuthorized();
```

**Comment by Stayup379** [comment]
> ```js
> import { setAuthority } from '@/utils/authority';
> import { reloadAuthorized } from '@/utils/Authorized';
> setAuthority('student');
> reloadAuthorized();
> ```

多谢~
