### ISSUE TITLE
npm start broken with errlop@1.1.0 on node@8

### ISSUE THREAD

**Issue by fobbyal** [ant-design/ant-design-pro#3247]
pining errlop to 1.0.3 seems to have fixed this

![screenshot 51](https://user-images.githubusercontent.com/7818365/50521867-dadf8f80-0a95-11e9-9c5a-e06d767642ff.jpg)

node v8.11.4

**Comment by afc163** [comment]
用 cnpm 可以暂时解决：https://github.com/cnpm/bug-versions/pull/31

**Comment by fobbyal** [comment]
我不知道需不需要修， 我在國外所以暫時吧 errlog 強行控制了在1.0.3 反正就是1.1.0用了就報錯。

**Comment by afc163** [comment]
作者应该已经修复了：https://github.com/bevry/errlop/issues/2
