### ISSUE TITLE
怎么从mock直接切换到服务端请求

### ISSUE THREAD

**Issue by muhawo** [ant-design/ant-design-pro#325]
roadlog运行在本地8001端口
在本地开了REST服务，端口是3007
怎么将service中的请求指向REST服务呢？
比如service中的注册接口：
![image](https://user-images.githubusercontent.com/4066427/33416842-9a8bb310-d5d9-11e7-8b3f-9e4f1ee0625a.png)
在修改了.roadhogrc或修改.roadhogrc.mock.js之后都没有效果
.roadhogrc：
![image](https://user-images.githubusercontent.com/4066427/33416766-35dbe890-d5d9-11e7-8d62-0d4656432c56.png)
.roadhogrc.mock.js
![image](https://user-images.githubusercontent.com/4066427/33416774-403fbd2a-d5d9-11e7-8293-e0867606af1b.png)

修改后请求没有指向3007端口，还是指向的8001：
![image](https://user-images.githubusercontent.com/4066427/33416899-e6f089d8-d5d9-11e7-9733-515a89cca1bc.png)

**Comment by Sunnyson303** [comment]
可以直接在 `.roadhogrc`上加
```
"proxy": {
    "/api": {
      "target": "http://localhost:5000/api",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  }

```

**Comment by nikogu** [comment]
@muhawo 这个是个 bug，你升级下 [roadhog-api-doc](https://github.com/nikogu/roadhog-api-doc) 到 `0.3.3`

**Comment by muhawo** [comment]
@nikogu 你头像的妹子是谁？

**Comment by muhawo** [comment]
@nikogu 升级到0.3.3也没用，还是跟之前一样，roadhog-api-doc会影响到这个问题？

**Comment by Bobcui001** [comment]
@nikogu 已升级，问题依然存在。

**Comment by baiheinet** [comment]
原来是bug[问答](https://segmentfault.com/q/1010000012254747)

**Comment by jiejieHome** [comment]
@Bobcui001 这个问题解决了吗？碰到同样问题

**Comment by Darcy-FzR** [comment]
直接在.roadhogrc.mock.js中配置 如 **'GET /api/app/list': "https://cnodejs.org/api/v1/topics"**, response会把这个本应该转发到的地址当作string处理。升级roadhog-api-doc 至0.3.3也无济于事。

**Comment by adwerrd** [comment]
我也遇到了。。@nikogu

**Comment by nikogu** [comment]
@muhawo 你这个问题搞定没，你用 chrome 网络工具调一下，看看请求头和返回体是什么

**Comment by nikogu** [comment]
@adwerrd 你 `roadhog-api-doc` 版本用的 `0.3.3` 吗？

**Comment by muhawo** [comment]
现在好像是可以了 但我还没搞明白是怎么好的 搞明白了再回来说一下吧

**Comment by muhawo** [comment]
@nikogu

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design-pro-site/commit/504a28a0d74e2e6ebaa193d247ab5f683dbeecc9

---

原来的文档是有问题的。如果你这么写：

```
'GET /api/*': 'https://your.server.com/api/',
```

那么 http://localhost:8001/api/xxx 会被转发到 http://localhost:8001/api/api/xxx，实际上是把前面的路径拼到后面的路径上。

需要改成下面这样：

```
'GET /api/(.*)': 'https://your.server.com/api/',
```

或者

```
'GET /api/*': 'https://your.server.com/',
```

这样 http://localhost:8001/api/xxx 会被转发到 http://localhost:8001/api/xxx

更多信息：https://segmentfault.com/q/1010000012511821/a-1020000012522260

**Comment by moveStar** [comment]
const noProxy = (process.env.NO_PROXY === 'true');
'GET /api/currentUser': {

$desc: "获取当前用户接口",
$params: {
  pageSize: {
    desc: '分页',
    exp: 2,
  },
},
$body: {
  name: 'Serati Ma',
  avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png',
  userid: '00000001',
  notifyCount: 12,
},
},
...
export default (noProxy
? { "/*": "http://test.servcer.com" }
: delay(proxy, 1000));

这样配置后请求还是发送到localhost:8080该如何配置

**Comment by moveStar** [comment]
const noProxy = true；
'GET /api/currentUser': {

$desc: "获取当前用户接口",
$params: {
  pageSize: {
    desc: '分页',
    exp: 2,
  },
},
$body: {
  name: 'Serati Ma',
  avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png',
  userid: '00000001',
  notifyCount: 12,
},
},
...
export default (noProxy
? { "/*": "http://test.servcer.com" }
: delay(proxy, 1000));

这样配置后请求还是发送到localhost:8080如何修改

**Comment by helloyoucan** [comment]
代理有问题
#####我的配置
```
//export default noProxy ?{}:
//  delay(proxy, 500);
export default {
  'GET /(.*)': 'http://localhost:8085/',
};

export async function login(params) {
  return request(`/login?username=${params.username}&password=${params.password}`);
}
```
访问报了400错误

**Comment by Yuanwei1992** [comment]
`export default noProxy
  ? {"/*": "http://192.168.6.88"}
  : delay(proxy, 1000);`
这样配置后请求还是发送到localhost:8080   报404
