### ISSUE TITLE
Can't login to dashboard after build 

### ISSUE THREAD

**Issue by makaaboune** [ant-design/ant-design-pro#3250]
Hy,

When I finished the development, I use npm run build to build my application, I get this error when I try to login : 
error 404: http://localhost:8001/api/login/account !
I still using the fack login data.
For server integration I use Express ranning on port 8001 :
 
app.use(express.static(path.join(__dirname, 'dist')));

app.get('/*', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});

**Comment by chenshuai2144** [comment]
try [proxy](https://github.com/villadora/express-http-proxy#readme)

**Comment by makaaboune** [comment]
@chenshuai2144 , this doesn't  work for me :
app.use('/api/login/account', proxy('localhost:8001'));
I get in response : Cannot POST /api/login/account 
Any solution please ?
