### ISSUE TITLE
请问有没有完整的多环境配置支持？

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3251]

**Comment by chenshuai2144** [comment]
umi 有环境变量

**Comment by yutingzhao1991** [comment]
https://umijs.org/guide/env-variables.html#umi-env

**Comment by mstao** [comment]
Thanks.

**Comment by farzer** [comment]
可以配置 多环境env吗？like https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables
