### ISSUE TITLE
Is there a bug in render when I using 'Modal‘？

### ISSUE THREAD

**Issue by jeffmxzhao** [ant-design/ant-design-pro#3253]
antd pro: V2.1.1

1. 使用Form.create创建`Modal`
```js
const AddUpdateForm = Form.create()(props => {
  const { form, handleAddUpdate, handleModalVisible, modalVisible, editType, current, addLoading, updateLoading } = props;

  const okHandle = () => {
    ...
    });
  };
  return (
    <Modal>      
    ...
    </Modal>
  );
});
```
2. 将`Modal`放入组件render
```js
render() {
  <AddUpdateForm current={current} ... />
}
```
3. `current`为当前`Table`选中行的数据

问题：
按确定时会重新`render`,这时会发生一个问题，因为`Modal`中绑定的是`current`的值，按确定后触发`render`,这时会把我在`Modal`中修改的值变成了修改之前的值
![](https://github.com/jeffmxzhao/images/blob/master/antd/modal_render2.gif?raw=true)

**Comment by chenshuai2144** [comment]
```
 <Modal>
     <From/>
 </Modal>
```
试试这样

**Comment by jeffmxzhao** [comment]
@chenshuai2144 非常感谢您的回复，我照样做了，还是一样的，还有其他的办法么？

**Comment by jeffmxzhao** [comment]
破案了，`form.resetFields();`

**Comment by jeffmxzhao** [comment]
破案了,`form.resetFields();`
