### ISSUE TITLE
如何自定义ESlint的规则

### ISSUE THREAD

**Issue by Tzng** [ant-design/ant-design-pro#3254]
我需要在开启eslint的一些配置，但是在我设置成错误的时候，代码还是正常运行
比如说配置no-unused-vars
```
        // 定义过的变量必须使用
        'no-unused-vars': [
            2,
            {
                vars: 'all',
                args: 'after-used'
            },
        ],
```

项目中只是提示
![image](https://user-images.githubusercontent.com/26215888/50532855-95d16100-0b5a-11e9-9c21-4c190dafcf74.png)
然后，项目正常运行，，，我应该如何让项目报错，不执行呢

**Comment by chenshuai2144** [comment]
不用的变量删掉的

**Comment by Tzng** [comment]
> 不用的变量删掉的

不是，我想着，要是能有个地方输出所有的错误就好了，在import的时候，好多代码引入了但是没有使用

**Comment by Tzng** [comment]
@xiaohuoni 
> 错误是设成1吧
1是警告呢，或者设置成error
