### ISSUE TITLE
你们的演示页面挂了啊喂

### ISSUE THREAD

**Issue by Shirley89** [ant-design/ant-design-pro#3258]
![image](https://user-images.githubusercontent.com/5310516/50536096-d85f6180-0b8b-11e9-8862-16f624b98d0d.png)

**Comment by yutingzhao1991** [comment]
确实有问题 https://preview.pro.ant.design/dashboard/analysis 更新后就出这个错了 @chenshuai2144

**Comment by chenshuai2144** [comment]
我这里没有诶。依赖的某个包更新了吗？

**Comment by chenshuai2144** [comment]
已修复
