### ISSUE TITLE
yarn 无法安装成功

### ISSUE THREAD

**Issue by cdrlee** [ant-design/ant-design-pro#3261]
试了两次，到最后都是卡住不进行了。
_系统 macOS 最新。_

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/faq-cn#npm-%E5%AE%89%E8%A3%85-puppeteer-%E5%A4%B1%E8%B4%A5

**Comment by chenshuai2144** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1246
