### ISSUE TITLE
PageHeader Tablist Options

### ISSUE THREAD

**Issue by davidpanzarella** [ant-design/ant-design-pro#3265]
I'm currently thinking about bringing Pro into my Ant Design integration that I have now. Is there no way to pass a smarter TabList to PageHeader? I have logic in place for my existing page navigation that allows me to disable certain tabs. However, if I use PageHeader as the means to show that nav through its internal way of showing Tabs, it seems I can't pass in any other details to the Tabs even though they take such props as `disabled`.  Is there any other way to do this? 

I'd imagine something more along the lines like this:

`
    {
        key: PROJECT_MENU_ITEMS.SETTINGS,
        tab: {
          title: PROJECT_MENU_ITEMS.SETTINGS,
          link: withId(PROJECT_SETTINGS, projectID),
          disabled: false
        }
      }
`

Thanks in advance!

**Comment by chenshuai2144** [comment]
Sorry, there is no one now.
You may need this
https://github.com/ant-design/ant-design/pull/13637

**Comment by davidpanzarella** [comment]
How close is that PR? How do you imagine `footer` working? With the way you guys have routes working, it's confusing to see how tab panes load new components onto the page. In our project, we're using React Router and Redux, which is handling links differently than the way that dva is doing for you guys.
