### ISSUE TITLE
LoginPage中没有找到作用域为user的store,不应该是登录成功后就调用用户的接口吗 ?

### ISSUE THREAD

**Issue by mofengfs** [ant-design/ant-design-pro#3270]

**Comment by mofengfs** [comment]
![image](https://user-images.githubusercontent.com/16655229/50578608-0e942e00-0e77-11e9-980d-34c61abcd7b0.png)



不应该是登录成功后就调用user的接口吗? 没有找到相关代码

**Comment by imhele** [comment]
第一个参数在函数中没有用到，又不希望 lint 提示 `已声明“xxx”，但从未读取其值` ，就用下划线占个位。

**Comment by imhele** [comment]
> @imhele
> 谢谢, 现在的情况是我拿login成功的数据作为参数给到BasicLayout调用user的数据, 但是页面一刷新, 当前登录的login数据就没了, 请问是否是在login拿登录信息的数据 ? 需要注意哪些情况

你可以用任何你期望的时机和方式来获取登录信息的数据，那现在的问题是如何持久化数据。
- 需要持久化的数据如果结构比较简单，可以直接用 `localStorage` ，AntD Pro 的权限信息就是这样处理的。 [相关代码戳这里](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/authority.js#L5) 
- 如果数据结构比较复杂可以考虑使用 [`redux-persist`](https://github.com/rt2zz/redux-persist) 。另外 `request.js` 也做了缓存，可以参考 [源码](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js#L40-L57) 找找灵感。

**Comment by mofengfs** [comment]
@imhele 
是的, 在login拿登录信息的数据, 拿到之后作为参数调用effects.fetchCurrent
