### ISSUE TITLE
typescript 独立引用ant-design-pro的Login组件时出现问题

### ISSUE THREAD

**Issue by heavenlian** [ant-design/ant-design-pro#3271]
按照文档发现
import Login from 'ant-design-pro/lib/Login';
const { Tab, UserName, Password, Mobile, Captcha, Submit } = Login;
render时：
```
<UserName name="username" />
<Password name="password" />
```
等
从antd-design-pro引用过来的，都会出现：
JSX 元素类型“UserName”不具有任何构造签名或调用签名。

**Comment by chenshuai2144** [comment]
我们写的类型有问题，
试试 as 大法吧

**Comment by heavenlian** [comment]
@chenshuai2144 , 没用啊。

**Comment by chenshuai2144** [comment]
`const { Tab, UserName, Password, Mobile, Captcha, Submit } = Login as any;`

**Comment by liu-dongyu** [comment]
@chenshuai2144 按需加载那个写法，`as any`大法好像报错了，显示`Login is not defined`
```javascript
import { Login } from 'ant-design-pro';
const { UserName, Password, Captcha, Submit } = Login as any;
....
<UserName name="username" />
<Password name="password" />
```

**Comment by chenshuai2144** [comment]
按需加载我这周会修复

**Comment by chenshuai2144** [comment]
fix in 2.2.0

**Comment by liu-dongyu** [comment]
@chenshuai2144 已更新至2.2.1，错误依旧，请问我是遗漏了什么吗 ？
```javascript
import { Login } from 'ant-design-pro';

// 报Login is not defined
const { UserName } = Login as any;

// 报JSX 元素类型“UserName”不具有任何构造签名或调用签名。
const { UserName } = Login;
```

**Comment by chenshuai2144** [comment]
https://unpkg.com/ant-design-pro@2.2.1/lib/Login/index.d.ts

试试 `Login. UserName`

**Comment by liu-dongyu** [comment]
> https://unpkg.com/ant-design-pro@2.2.1/lib/Login/index.d.ts
> 
> 试试 `Login. UserName`

下面的都报 不具有任何构造签名或调用签名
```
<Login.UserName />
```
```
const UserName = Login.UserName;
<UserName />
```
这样写倒是可以
```
const UserName:any = Login.UserName;
<UserName />
```

**Comment by chenshuai2144** [comment]
先这样试试，我找找什么愿意

**Comment by liu-dongyu** [comment]
> 问题是这个 https://unpkg.com/ant-design-pro@2.2.1/lib/Login/LoginItem.d.ts
> 这个没有 default

试了试，加上default可以了 👍
