### ISSUE TITLE
Unit test fails when checking the simulation of buttons

### ISSUE THREAD

**Issue by suthanJ** [ant-design/ant-design-pro#3272]
const mockFunction = jest.fn();
const wrapper = shallow(
          <Subscribers.WrappedComponent  create={mockFunction}/>
        );
wrapper.find('#create').simulate('click');
expect(mockFunction).toHaveBeenCalledTimes(1);

Test fails for the above case, it says jest.fn() is called zero times. 

Could you please provide a example to test the button simulations ?

**Comment by chenshuai2144** [comment]
you maby nedd  `node --inspect-brk`
