### ISSUE TITLE
使用transfer点击选择左右穿梭数据时报错了

### ISSUE THREAD

**Issue by jiangxuefeng521** [ant-design/ant-design-pro#3273]
Uncaught TypeError: sourceSelectedKeys.includes is not a function
The above error occurred in the <Transfer> component:
    in Transfer (created by TransferForm)
    in div (created by Dialog)
    in div (created by Dialog)
    in div (created by LazyRenderBox)
    in LazyRenderBox (created by Dialog)
    in AnimateChild (created by Animate)
    in Animate (created by Dialog)
    in div (created by Dialog)
    in div (created by Dialog)
    in Dialog (created by DialogWrap)
    in Portal (created by DialogWrap)
    in DialogWrap (created by Modal)
    in Modal (created by TransferForm)
    in TransferForm (created by Form(TransferForm))
    in Form(TransferForm) (created by Connect(Form(TransferForm)))
    in Connect(Form(TransferForm)) (created by CheckoutForm)
    in div (created by CheckoutForm)
    in CheckoutForm (created by Form(CheckoutForm))
    in Form(CheckoutForm) (created by .........................

**Comment by chenshuai2144** [comment]
再现地址？

**Comment by chenshuai2144** [comment]
看的报错应该是sourceSelectedKeys 有问题造成的，sourceSelectedKeys必须要为 string
或者 array

**Comment by afc163** [comment]
也有可能是 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

**Comment by jiangxuefeng521** [comment]
在2.1.1版本没问题，在2.0.0版本出现这个问题，怀疑是不是版本不同有影响

**Comment by jiangxuefeng521** [comment]
> 看的报错应该是sourceSelectedKeys 有问题造成的，sourceSelectedKeys必须要为 string
> 或者 array

**Comment by jiangxuefeng521** [comment]
@chenshuai2144 在2.1.1版本没问题，在2.0.0版本出现这个问题，怀疑是不是版本不同有影响

**Comment by jiangxuefeng521** [comment]
@afc163 不是浏览器问题

**Comment by chenshuai2144** [comment]
这个和 pro 版本应该没有关系的，这个组件是 antd 原生的
给我们一个最小实践，让我们看一下

**Comment by jiangxuefeng521** [comment]
@chenshuai2144 我用谷歌打开的，是浏览器的版本问题，但是之前在其他ant-design-pro项目版本，这个版本浏览器都可以。为了统一版本做了代码迁移，才出现上面的问题。暂时看到是本地谷歌浏览器版本问题，算是个解决途径。
