### ISSUE TITLE
build之后，接口域名无法返回数据

### ISSUE THREAD

**Issue by hanwenbo** [ant-design/ant-design-pro#3275]
开发模式下一点问题没有，build完，接口地址也不出数据了 都是前端的index.html内容，不理解为什么，官方的demo也是同样

**Comment by chenshuai2144** [comment]
mock 和 proxy 是不会带到编译后的代码中的，
你需要在容器中自己配置代理。
https://pro.ant.design/docs/deploy-cn#%E5%8F%91%E5%B8%83

**Comment by afc163** [comment]
mock 数据只是给调试用的，生产环境你需要真实的 API 才能跑得起来。

**Comment by LBC100** [comment]
![Snip20190402_14](https://user-images.githubusercontent.com/38514123/55411110-9fbe9200-5597-11e9-9d50-028225ce955f.png)
nginx.conf
