### ISSUE TITLE
部署到nginx后出现TypeError: n.load is not a function

### ISSUE THREAD

**Issue by lifeixiang027** [ant-design/ant-design-pro#3281]
重现步骤
1、编译antd pro
git clone https://github.com/ant-design/ant-design-pro.git
cd ant-design-pro
npm run build

2、将dist文件夹内容复制到nginx的html文件夹下
3、启动nginx
4、访问localhost

错误现象：
Chrome控制台出现错误
![image](https://user-images.githubusercontent.com/18546370/50622395-af521e80-0f47-11e9-8f6c-15f3f560ca15.png)

**Comment by chenshuai2144** [comment]
url 是？
我无法再现，你也许可以试试打开 sourcemap

**Comment by lifeixiang027** [comment]
> 问题找到了吗？

问题原因还是不清楚，不过反复重新安装nodejs和依赖，问题暂时解决了。

**Comment by DongLee0504** [comment]
在cmd中npm build可以解决问题，试过。
