### ISSUE TITLE
如何在项目中引入第三方库（JQWidgets），卡一个星期了

### ISSUE THREAD

**Issue by ssf2015** [ant-design/ant-design-pro#3282]
公司一定要用JQWidgets，但是引入总是报错，求解决方案，

**Comment by afc163** [comment]
建议参考 JQWidgets 的文档：https://www.jqwidgets.com/reactjs-components-documentation/ 并去他们的渠道进行提问，应该会比这里要靠谱。

**Comment by xiaohuoni** [comment]
@ssf2015 https://www.jqwidgets.com/reactjs-components-documentation/documentation/create-react-app/index.htm?search=
看起来只是一个组件，引入就行了吧。报什么错呢？
