### ISSUE TITLE
手机端 菜单样式 padding:24px bug

### ISSUE THREAD

**Issue by j787701730** [ant-design/ant-design-pro#3283]
![image](https://user-images.githubusercontent.com/23625690/50625630-5775e080-0f64-11e9-9e8e-e288871c42ea.png)

**Comment by xiaohuoni** [comment]
是有这个问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/pull/3225

**Comment by xiaohuoni** [comment]
最新的预览页面还有这个问题。最新的代码没有这个问题了
