### ISSUE TITLE
Unhandled Rejection (Error): Loading chunk vendors failed.

### ISSUE THREAD

**Issue by flg717** [ant-design/ant-design-pro#3284]
![image](https://user-images.githubusercontent.com/19221801/50631824-c3664200-0f80-11e9-838c-18dc1f34f386.png)
重新更新node_models后，启动就编程这个样子，怀疑过package.json依赖有问题，但是全部依赖都恢复了官方脚手架，依然是这个问题，有大神知道怎么回事吗？

**Comment by chenshuai2144** [comment]
这个看起来是因为代码包没有加载成功，你可以试试关掉代码分割

**Comment by flg717** [comment]
@chenshuai2144 问题找到了，是因为umi升级后2.3.1后，配置polyfills: ['ie11']失效，导致的，修改为
targets: {
    ie: 11,
  },
就正常了。
您提到的关闭代码分割，用umi怎么配置呢， 我找了一圈，没找到

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport
在这里

**Comment by dongkeng001** [comment]
> @chenshuai2144 问题找到了，是因为umi升级后2.3.1后，配置polyfills: ['ie11']失效，导致的，修改为
> targets: {
> ie: 11,
> },
> 就正常了。
> 您提到的关闭代码分割，用umi怎么配置呢， 我找了一圈，没找到

我是在360浏览器切换到兼容模式下会报跟你同样的错误，但我在config.js文件里面也跟你一样设置targets: {ie: 11},也没解决，还是一样会报这个错，umi版本是2.4.4的
