### ISSUE TITLE
Tab好像不支持react-loadable 组件，我想做一个tab管理component很难实现

### ISSUE THREAD

**Issue by DaqingFeng** [ant-design/ant-design-pro#3285]
![react-loadable](https://user-images.githubusercontent.com/10512467/50638328-578fd380-0f98-11e9-802f-ddaf9180d1b9.png)

这里采用loadable方式载入页面，不过tab总没办法渲染。

**Comment by DaqingFeng** [comment]
已解决，谢谢

**Comment by afc163** [comment]
有时间的话可以把遇到的问题和解决方案抛出来造福后来人。
