### ISSUE TITLE
chrome 空白页

### ISSUE THREAD

**Issue by lifegit** [ant-design/ant-design-pro#3286]
华为自带的浏览器访问pro预览(https://preview.pro.ant.design/dashboard/analysis) ，显示空白页，但访问V1版本正常显示。目前一个项目是改的pro，客户没法使用了。感谢。
UA： 
Mozilla/5.0 (Linux; U; Android 8.0.0zh-cn;
KNT-AL20 Build/HUAWEIKNT-AL20)
AppleWebKit/537.36 (KHTML, like
Gecko)Version/4.0 Chrome/57.0.2987.132
MQQBrowser/8.1 Mobile Safari/537.36

**Comment by lifegit** [comment]
@xiaohuoni 尝试过，  targets: {ie: 11, chrome: 49, firefox: 45, safari: 10, edge: 13, ios: 10 }, 依旧不行

**Comment by chenshuai2144** [comment]
试试 vcoonsole 或者使用调试工具调试以下。
只要找到报错就会很好解决

**Comment by wzshiming** [comment]
chrome 下 service-worker.js 加载失败 就 空白了

**Comment by chenshuai2144** [comment]
是因为pwa的问题吗？

**Comment by wzshiming** [comment]
看起来是的  我用的 chrome 71

**Comment by chenshuai2144** [comment]
service-worker.js 是pwa的功能，官网也会出这个问题吗？

**Comment by wzshiming** [comment]
官网是好的
我本地自己启动的 
chrome 空白
firefox 能正常访问 没看到 加载 service-worker.js

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3437
感觉是这个问题
