### ISSUE TITLE
网站标题不同步的问题

### ISSUE THREAD

**Issue by shatian114** [ant-design/ant-design-pro#3287]
如果我直接访问首页http://localhost:8000/pwuye，然后点击导航，网站标题title就会根据导航变化
如果我直接访问导航路径http://localhost:8000/pwuye/#/jiBenXinXi/xiaoQu，标题title上则没有导航的名字

**Comment by afc163** [comment]
目测 master 没有这样的问题，所以建议你先自行排查一下有什么区别。

**Comment by afc163** [comment]
提问要带重现地址，否则互相摸瞎。

**Comment by shatian114** [comment]
> 提问要带重现地址，否则互相摸瞎。

好的，我下次注意
上午对比了修改，将修改的恢复了以后，问题没有解决
改的地方比较多，可能恢复的不到位
我现在想搞清楚这块的逻辑，但是基础不行，实在看不懂，麻烦你能不能指导一下？
下面是我调试的结果
BasicLayout.js文件里面的getPageTitle方法
getPageTitle = (pathname, breadcrumbNameMap) => {
	  //下面这行，打印出breadcrumbNameMap是undefined
	console.log(pathname, breadcrumbNameMap);
	const currRouterData = this.matchParamsPath(pathname, breadcrumbNameMap);

    if (currRouterData) {
      return currRouterData.name + '-' + petGlobal.webName;
    }
	return petGlobal.webName;
    
  };

**Comment by shatian114** [comment]
> 这个是根据 props 生成的，如果修改不同步，应该是报错或者有 cache 的原因吧。
> 你可以一下这个方法的返回有什么的？

没有报错的，就是搞不清楚这块的数据是怎么个流向，BasicLayout应该是最外层的组件了，它的props是哪里给传的呢？本人初学，水平太次，请大佬指教一下

**Comment by chenshuai2144** [comment]
BasicLayout 的 pro 是 umi 给的，其实就是 modal 和 umi 的一些数据。

**Comment by shatian114** [comment]
> BasicLayout 的 pro 是 umi 给的，其实就是 modal 和 umi 的一些数据。

好吧，modal属于dva的东西吧，正好这俩我都没怎么学，文档看了一遍，忘光了，重新学
