### ISSUE TITLE
饼图组件pie属性设置问题

### ISSUE THREAD

**Issue by quchwe** [ant-design/ant-design-pro#3288]
![image](https://user-images.githubusercontent.com/17445015/50670119-4b416000-1004-11e9-8cb3-f87d57831711.png)

在版本2.1.1中，根据bizchart API如果用于 响应鼠标点击事件的目的[](https://bizcharts.net/products/bizCharts/api/geom)，该属性应为select，如果不是，那该属性在api中找不到相应意义

**Comment by afc163** [comment]
建议提给 bizchart
