### ISSUE TITLE
开发环境可以获取到公网api的数据, 生产环境（IIS服务器）获取不到公网api的数据, 是什么原因 ?

### ISSUE THREAD

**Issue by mofengfs** [ant-design/ant-design-pro#3291]
@afc163 @sorrycc @chenshuai2144 @imhele 
可否帮忙看一下这个问题的解决办法,
这是antd-pro存在的缺陷吗 ? 是不是无解了 ?

**Comment by mofengfs** [comment]
1.开发环境启动项目npm run start:no-mock;
2.可以get到公网api的数据;
3.打包部署到windows服务器,get不到公网api的数据.
4.proxy:
![image](https://user-images.githubusercontent.com/16655229/50681859-e576c780-1047-11e9-868f-8e164706c8ce.png)

开发环境:
![image](https://user-images.githubusercontent.com/16655229/50681761-992b8780-1047-11e9-8fb3-eea7eef47cda.png)
![image](https://user-images.githubusercontent.com/16655229/50681780-a9dbfd80-1047-11e9-9dee-a53a5ad68a84.png)

生产环境:
![image](https://user-images.githubusercontent.com/16655229/50681825-cbd58000-1047-11e9-9949-585db4253ae9.png)
![image](https://user-images.githubusercontent.com/16655229/50681831-d1cb6100-1047-11e9-95af-52890171e4f7.png)

**Comment by soolaugust** [comment]
后端也要配置代理

可参考： [Nginx生产环境报404，405错误，help~~ ](https://github.com/ant-design/ant-design-pro/issues/2367#issuecomment-425474385)

**Comment by mofengfs** [comment]
@soolaugust 
我的是IIS服务器

**Comment by soolaugust** [comment]
@mofengfs 控制台有报什么错么？

**Comment by mofengfs** [comment]
@soolaugust 
控制台没有报错
![image](https://user-images.githubusercontent.com/16655229/50725661-a3c74900-113b-11e9-8a8d-c578e5e12655.png)

**Comment by soolaugust** [comment]
@mofengfs  
这边没有办法测试，不够IIS服务器应该也要设置代理吧， 试一下下面这个方案呢？
[在IIS和Nginx上通过代理部署基于ant-design-pro前端框架开发的应用](https://www.cnblogs.com/yuzhihui/p/9335035.html)

**Comment by mofengfs** [comment]
@soolaugust 
![url](https://user-images.githubusercontent.com/16655229/50738682-fa06bb80-1211-11e9-8e1d-65a8859d7b6b.png)
![webconfig](https://user-images.githubusercontent.com/16655229/50738683-fa06bb80-1211-11e9-8e2d-6290fe354a88.png)
![default](https://user-images.githubusercontent.com/16655229/50738684-fb37e880-1211-11e9-8f48-9ce913157d7a.png)
重启服务，还是没有获取到数据

**Comment by soolaugust** [comment]
@mofengfs 原生的build命令是有no-mock选项的，应该不会指向mock数据。

**Comment by soolaugust** [comment]
@mofengfs 可以参考这个 [umi](
https://umijs.org/guide/deploy.html#deploy-html-to-a-non-root-directory)， 配置一下bade

**Comment by mofengfs** [comment]
@soolaugust 
谢谢,那么早
我看了这个umi部署, 没有参考价值

**Comment by shaopeng1** [comment]
打包后的代理配置线上是不生效的

**Comment by mofengfs** [comment]
@shaopeng1 
是的, 所以才用服务器代理嘛, 可是并没有成功

**Comment by imhele** [comment]
你在 proxy 把 `api` replace 成了空字符串，proxy 最终的 URL 是 `http://proxy.domain.com/bins/11y5is` ，IIS 不能通过 match url `api` 做转发。试试 build 时注释掉 `pathRewrite` 。

**Comment by mofengfs** [comment]
@imhele 
还是不行, 注释掉pathRewrite且api中去掉/api和保留/api两种方式都打包部署尝试了, 依然没有变化.
![image](https://user-images.githubusercontent.com/16655229/50748556-06703000-1275-11e9-9e75-53fe3f66d6a0.png)
![image](https://user-images.githubusercontent.com/16655229/50748567-11c35b80-1275-11e9-92cb-a38f63c6c5cf.png)
![image](https://user-images.githubusercontent.com/16655229/50748572-1b4cc380-1275-11e9-8dff-86c32416396e.png)

**Comment by mofengfs** [comment]
@chenshuai2144 @imhele 
我不知道你们有没有在IIS服务器上做过测试,相关的文档也很少,现在都是靠自己去测试排除原因,现在还没找到问题的根源在哪,如何解决.

**Comment by soolaugust** [comment]
请求的服务器那边可以看到log么？是没收到请求还是收到了但是没回复？

**Comment by mofengfs** [comment]
@soolaugust 
服务端log上面没有, 因为根本就没法出去, 所以服务端收不到请求.

**Comment by mofengfs** [comment]
我IIS代理的配置规则如上面的图所示, 
[](https://github.com/ant-design/ant-design-pro/issues/3291#issuecomment-451754251)

**Comment by afc163** [comment]
@mofengfs 这是个前端 spa 项目，理论上和任何 webserver 天然兼容。IIS 的问题需要你自行排查服务端。

**Comment by afc163** [comment]
你可以参考下文档 https://facebook.github.io/create-react-app/docs/deployment#serving-apps-with-client-side-routing

**Comment by superlbr** [comment]
@mofengfs
  就目前来看，apache的url重写并未如预期生效。
  1. 看Response里的content-type就看出来了，一个是json，一个是html
  2. 怀疑跟https有关，要设置ssl，参考https://serverfault.com/questions/84821/apache-proxypass-with-ssl

**Comment by mofengfs** [comment]
@superlbr 
http的接口也测试过的,不单单https

**Comment by TopGuo** [comment]
楼上兄弟好了没

**Comment by zhangWeiZhuang** [comment]
> @soolaugust
> **在站点下重写URL,重启服务，还是没有获取到数据，有个重要的问题是，抓包抓不到对应的请求，是否打包上线之后，请求还是指向了mock？这个我确定不了，文档中相关资料太少了。**
> 1.
> ![url](https://user-images.githubusercontent.com/16655229/50738682-fa06bb80-1211-11e9-8e1d-65a8859d7b6b.png)
> 2.
> ![default](https://user-images.githubusercontent.com/16655229/50739306-3d185d00-1219-11e9-9b55-dc6cde58223d.png)
> 3.
> ![webconfig](https://user-images.githubusercontent.com/16655229/50739308-43a6d480-1219-11e9-87e0-c65211792a1b.png)

你好。请问关于iis代理的问题，你这边有解决方案了吗

**Comment by fujianbo** [comment]
> @superlbr
> http的接口也测试过的,不单单https

请问你这个问题最终解决了吗？怎么解决的呢？
我也碰到同样的问题

**Comment by fujianbo** [comment]
> **1.开发环境启动项目**`npm run start:no-mock` **可以get到公网api的数据**;
> **2.打包部署到IIS服务器,get不到公网api的数据，抓包的时候根本就没抓取到对应的请求。**.
> **3.proxy**:
> ![image](https://user-images.githubusercontent.com/16655229/50681859-e576c780-1047-11e9-868f-8e164706c8ce.png)
> **4.request**:
> ![image](https://user-images.githubusercontent.com/16655229/50681991-574f1100-1048-11e9-8510-40df2cc96de9.png)
> 
> **开发环境**:
> ![image](https://user-images.githubusercontent.com/16655229/50681761-992b8780-1047-11e9-8fb3-eea7eef47cda.png)
> ![image](https://user-images.githubusercontent.com/16655229/50681780-a9dbfd80-1047-11e9-9dee-a53a5ad68a84.png)
> 
> **生产环境:**
> ![1](https://user-images.githubusercontent.com/16655229/50721610-6d6ad900-10fd-11e9-8ca2-9697fce97125.png)
> ![2](https://user-images.githubusercontent.com/16655229/50721613-72c82380-10fd-11e9-8366-f86979bb0c7e.png)
> ![image](https://user-images.githubusercontent.com/16655229/50681831-d1cb6100-1047-11e9-95af-52890171e4f7.png)

请问你这个问题最终解决了吗？是怎么解决的呢？
我也碰到同样的问题

**Comment by chenshuai2144** [comment]
试着吧  /api 改成 /api/
