### ISSUE TITLE
please help me to optimize my Vendor.async.js && umi.js

### ISSUE THREAD

**Issue by ch-liuzhide** [ant-design/ant-design-pro#3293]
![image](https://user-images.githubusercontent.com/44251801/50680757-d2fa8f00-1043-11e9-8450-900d4d6ac746.png)

### 靠，太大了，我一定是哪里搞错了。
我已经从一个相似问题中得出cdn可以转移走部分脂肪，但我并不想这么做。
疑惑的是，vendors这个文件的作用是什么，希望有谁提供我一份说明。
还有umi.js为什么也这么大，有办法优化吗.

**Comment by chenshuai2144** [comment]
你是全量加载！所有的库都在里面

**Comment by ch-liuzhide** [comment]
> 你是全量加载！所有的库都在里面
我使用了antd-pro
所以应该怎么搞呢,按理说umi已经集成了 babel-plugin-import，这个我就不用管它了吧？

另外我参考umi的webpackChain
![image](https://user-images.githubusercontent.com/44251801/50688636-4d85d780-1061-11e9-9355-d5f76c28d61a.png)
![image](https://user-images.githubusercontent.com/44251801/50688783-f6cccd80-1061-11e9-8041-5f6f09fd5fbe.png)
`交流群里有群友发了如下代码，在router.config
```
`  const ChunkGroups = (chunkList) => {
    let chunkMap = {};
    chunkList.forEach((chunkKey) => {
      chunkMap[chunkKey] = {
        name: chunkKey,
        test: (module) => {
          const reg = new RegExp(`node_modules[\\\\\\/]${chunkKey}$`);
          return reg.test(module.context);
        },
        priority: 3,
        minSize: 0,
        minChunks: 1,
        enforce: true,
        chunks: 'async',
        maxAsyncRequests: 5,
        maxInitialRequests: 3,
        reuseExistingChunk: true
      };
    });
    return chunkMap;
  };

  config.merge({
    optimization: {
      splitChunks: {
        chunks: 'async',
        minSize: 0,
        minChunks: 1,
        cacheGroups: {
          ...ChunkGroups(['antd', 'bizcharts', '@antv','jsoneditor','brace','draft-js','braft-editor'])
        }
      }
    },
````
想借此把antv,bizcharts等干掉，在线等挺急的（en!）
