### ISSUE TITLE
不要用 PureComponent

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-pro#3294]
大部分组件并不是 pure component，但是却都继承了 PureComponent [[1](https://github.com/ant-design/ant-design-pro/blob/2f51506c63d94b9a374aee49ba8b0c13dcaa0c76/src/components/PageHeaderWrapper/GridContent.js#L5)], [[2](https://github.com/ant-design/ant-design-pro/blob/01fc86deb6abf6312aa21647ad78f5f7f239b56e/src/pages/Forms/StepForm/index.js#L8)]。PureComponent 并不一定会提升性能，滥用反而会降低性能。

发现业务项目中 PureComponent 也被滥用了，估计也是参考了这里。

参考：

https://github.com/facebook/react/issues/14463#issuecomment-448829902
https://github.com/facebook/react/issues/7379#issuecomment-270117281
https://staltz.com/is-your-javascript-function-actually-pure.html

**Comment by xiaohuoni** [comment]
这个修复了
