### ISSUE TITLE
大神们求推荐jenkins配置方案

### ISSUE THREAD

**Issue by junjunsoul** [ant-design/ant-design-pro#3295]

**Comment by zhangshuai0101** [comment]
你是要通过jenkins来构建吧？

**Comment by junjunsoul** [comment]
是的，是的，想做自动化部署

**Comment by junjunsoul** [comment]
> 你是要通过jenkins来构建吧？
是的，是的，想做自动化部署

**Comment by junjunsoul** [comment]
是的，是的，想做自动化部署

**Comment by wangyun122** [comment]
其实很简单的啊 没几行代码 要不你留个联系方式 我私聊跟你说吧

**Comment by junjunsoul** [comment]
嗯嗯，看过一些，但是还是一头雾水，之前的项目部署都是跟后端一起部署，现在想分开部署，搞前后端彻底分离。
联系方式QQ:651900822,微信:JunJunSoul 看您方便加我哪一个

**Comment by junjunsoul** [comment]
嗯嗯，看过一些，但是还是一头雾水，之前的项目部署都是跟后端一起部署，现在想分开部署，搞前后端彻底分离。
联系方式QQ:651900822,微信:JunJunSoul 看您方便加我哪一个

**Comment by gaspire** [comment]
> 其实很简单的啊 没几行代码 要不你留个联系方式 我私聊跟你说吧

分享下
