### ISSUE TITLE
2.0如何引用iconfont上的自定义图标啊

### ISSUE THREAD

**Issue by dongkang1993** [ant-design/ant-design-pro#3298]
2.0如何引用iconfont上的自定义图标啊，在global.less里引用不起作用

**Comment by zhangshuai0101** [comment]
参考这个即可https://www.jianshu.com/p/2934316a5899

**Comment by dongkang1993** [comment]
在globaol.less文件中引入iconfont上的css，为何失败 @zhangshuai0101

**Comment by afc163** [comment]
https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-font-%E5%9B%BE%E6%A0%87

**Comment by dongkang1993** [comment]
搞定了，多谢 @afc163 @zhangshuai0101
