### ISSUE TITLE
在menu.js中请求服务器后 ， 面包屑在刷新页面后不生效

### ISSUE THREAD

**Issue by fengshengde** [ant-design/ant-design-pro#3299]
effects: {
    *fetchMenuData({ payload }, { call , put }) {
      const { routes, authority } = payload;

      const response = yield call(fetchMenuDataService , payload);
      const tempMenuData = response.list;

      const menuData = filterMenuData(memoizeOneFormatter(routes, authority));
      const breadcrumbNameMap = memoizeOneGetBreadcrumbNameMap(menuData);

      console.log(menuData);
     
      yield put({
        type: 'fetchMenuDataReducer',
        payload: { menuData, breadcrumbNameMap },
      });      
    },
  },

**Comment by zhangshuai0101** [comment]
返回数据格式是否和路由配置文件中的一致

**Comment by chenshuai2144** [comment]
你的代码需要和 master 保持最新的，旧的代码中有缓存机制。
