### ISSUE TITLE
优化分析页的销售额趋势图表

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#33]
- [x] 图表加载前加一个 spin ，第一眼会舒服一点。

**Comment by anlia260** [comment]
- [ ] 圆形图表内部的文字长度需要做处理，可否改变下字号或者Hover展示？

![image](https://user-images.githubusercontent.com/11311553/32145328-a1021ad6-bd01-11e7-9a96-9705d3c36b55.png)

**Comment by afc163** [comment]
@anlia260 强刷一下，应该已经优化了。

**Comment by anlia260** [comment]
@afc163 ，没有看到改变。已经禁掉Cache了。是不是Cdn？

**Comment by afc163** [comment]
忘记 push 了，现在应该好了。

**Comment by nikogu** [comment]
- [x] 柱状图响应式优化
