### ISSUE TITLE
React v16.2.0: Improved Support for Fragments

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#330]
[React v16.2.0](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)
Fragments look like empty JSX tags. They let you group a list of children without adding extra nodes to the DOM:
```
render() {
  return (
    <>
      <ChildA />
      <ChildB />
      <ChildC />
    </>
  );
}
```
Supportive feeling is OK.
Do you need to change the empty div in ANT DESIGN PRO?
There are about 35 empty div..

**Comment by chenshuai2144** [comment]
需要使用babel7.0.  

[babel7.0](https://babeljs.io/blog/2017/09/12/planning-for-7.0)

**Comment by dai875939260** [comment]
@chenshuai2144 你啥时候更新这个呢，这个特性真的挺好的

**Comment by chenshuai2144** [comment]
roadhog发布了2.0之后吧

**Comment by chenshuai2144** [comment]
roadhog 升级2.0之后就可以着手做这个事情了

**Comment by chenshuai2144** [comment]
eslint 还不支持<></>
