### ISSUE TITLE
如何动态路由，根据接口返回数据进行挂载

### ISSUE THREAD

**Issue by zhuoxiaoqiang** [ant-design/ant-design-pro#3301]
umi development 404 page
There's not a page yet at /app1/page1.

Create a React.js component in your pages directory at src/pages/app1/page1.js and configuire the route in config file then this page will automatically refresh to show the new page component you created.

**Comment by xiaohuoni** [comment]
什么意思，你想实现怎么样的功能呢？

**Comment by pkaq** [comment]
他是想根据返回的菜单数据实现动态路由吧

**Comment by zhuoxiaoqiang** [comment]
是的，就是想实现动态路由，现在是在router.config.js里面配置的。比如里面的path，可能根据后端返回的去变化

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/pull/3317

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/264
