### ISSUE TITLE
父路由设置权限，它下面的子路权限不继承

### ISSUE THREAD

**Issue by xiaochunyu** [ant-design/ant-design-pro#3302]
例如：
// dashboard
      {
        path: '/dashboard',
        name: 'dashboard',
        icon: 'dashboard',
        authority: ['admin'],
        routes: [
          {
            path: '/dashboard/analysis',
            name: 'analysis',
            component: './Dashboard/Analysis',
          },
          {
            path: '/dashboard/monitor',
            name: 'monitor',
            component: './Dashboard/Monitor',
          },
          {
            path: '/dashboard/workplace',
            name: 'workplace',
            component: './Dashboard/Workplace',
          },
        ],
      }

这里的这个路径：/dashboard在没有权限的情况下，会跳转403，可是它下面的子路由路径仍然可以访问。

**Comment by chenshuai2144** [comment]
@xiaohuoni  看一看？

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/pull/3190
这个处理的就是这个问题吧！

**Comment by xiaohuoni** [comment]
上次不是在讨论要用这个还是用小哥的那个函数

**Comment by chenshuai2144** [comment]
用一下小哥那个函数吧
加几个测试还是很 ok

**Comment by xiaohuoni** [comment]
你加吧，我不喜欢while（捂脸）

**Comment by chenshuai2144** [comment]
fix https://github.com/ant-design/ant-design-pro/pull/3522
