### ISSUE TITLE
2.1.1号版本 打包经常报错

### ISSUE THREAD

**Issue by Fea-Sin** [ant-design/ant-design-pro#3304]
![error](https://user-images.githubusercontent.com/15316066/50758814-37b12600-129e-11e9-8c3a-3c162ab86a37.png)

上述错误并不是每次都会出现，当修改文件，特别是 less 文件保存后经常会报上述错误并中断
只能再次 npm start 

node   8.12.0
npm    6.4.1
win7

**Comment by chenshuai2144** [comment]
没有权限？你可能需要设置 temp 文件夹权限为 777

**Comment by Fea-Sin** [comment]
应该不是权限问题，已经将权限设置为 “完全控制”，还是经常报错

![error-1](https://user-images.githubusercontent.com/15316066/50805507-b1442500-132d-11e9-946f-323d09325e09.png)

**Comment by chenshuai2144** [comment]
删掉换主题的插件试试
在 plugin.config.js中

**Comment by Fea-Sin** [comment]
/config/plugin.config.js
注释掉插件后，测试确实管用

![test-1](https://user-images.githubusercontent.com/15316066/50820434-98586580-1367-11e9-85c0-260e47823edb.png)

thanks!
