### ISSUE TITLE
config app after build

### ISSUE THREAD

**Issue by hamid07ss** [ant-design/ant-design-pro#3305]
Hi.

I want to config my app after build!
we create admin panels for some special users that let to admin to config app from a file in app root folder.

some configs like:
```
api_url
auth_url
audit_url
```

or some extra configs like:
```
ReportPageSize
ExportMaxCount
LiveChartIntervalTime
```

or anything else...

how I can do this???

**Comment by chenshuai2144** [comment]
You need a configuration center to access via ajax

**Comment by sorrycc** [comment]
The contents of config.json are packaged in umi.js after build, and the dist/config.json file is useless. To configure after the build, you can do it in html, or make a js file and reference it in all html files.
