### ISSUE TITLE
IE浏览器是否不打算支持IE11以下的版本了?

### ISSUE THREAD

**Issue by qjekingstar** [ant-design/ant-design-pro#331]
antd可以兼容到IE9,所以想问下为什么ant-design-pro是只兼容IE11?

**Comment by afc163** [comment]
因为在布局上我们更多的使用了 flex，并且对中后台项目来说 IE9-10 占比是非常少的。

antd 支持 IE9 是因为 antd 有部分前台产品的应用场景。
