### ISSUE TITLE
误删引用，页面一直处在loadding中，没有报错

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3311]
重现步骤：
1.启动项目
2.打开 `src/components/GlobalHeader/RightContent.js`
3.修改
```diff
-  import React, { PureComponent } from 'react';
```
4.保存，页面一直在loadding
![image](https://user-images.githubusercontent.com/11746742/50806891-8ceb4700-1333-11e9-8973-59dcf73af6d5.png)
终端也没有报错
![image](https://user-images.githubusercontent.com/11746742/50806905-9eccea00-1333-11e9-9db9-307a6f4b09ba.png)
5.试着重启dev，项目依旧能够启动。但是一直处于loading中。
![image](https://user-images.githubusercontent.com/11746742/50807034-0b47e900-1334-11e9-9230-3cc632d120dc.png)
感觉这个问题定位起来非常困难。

**Comment by xiaohuoni** [comment]
老大，这个应该算是umi的问题吧！@sorrycc

**Comment by sorrycc** [comment]
这是运行时错误，会报在控制台里。

**Comment by xiaohuoni** [comment]
pro最新的代码！
<img width="1437" alt="qq20190109-085837 2x" src="https://user-images.githubusercontent.com/11746742/50868933-d21f7f80-13ec-11e9-86bc-ae1853bb289b.png">

**Comment by sorrycc** [comment]
重装依赖试试，我下午跑过没有问题了。

**Comment by xiaohuoni** [comment]
```
Unhandled Rejection (ReferenceError): PureComponent is not defined
Module../src/components/GlobalHeader/index.js
src/components/GlobalHeader/index.js:7
   4 | import styles from './index.less';
   5 | import RightContent from './RightContent';
   6 | 
>  7 | export default class GlobalHeader extends PureComponent {
   8 |   componentWillUnmount() {
   9 |     this.triggerResizeEvent.cancel();
  10 |   }
```
最新的代码，会触发报错
