### ISSUE TITLE
卡片高度不对齐

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#3312]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/507615/50812162-97660a80-134c-11e9-8d79-b8661b4b3bbe.png">

**Comment by afc163** [comment]
https://preview.pro.ant.design/dashboard/analysis

问题还存在。

**Comment by chenshuai2144** [comment]
这个问题记得修了好几次了。。

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/pro-blocks/commit/17e8977e589a7c4b2fbb8795ed70c124dbe1ac33
