### ISSUE TITLE
表单提交问题

### ISSUE THREAD

**Issue by zhouguanglong** [ant-design/ant-design-pro#3313]
访问网页后复制地址，不退出登录，而是关闭浏览器，然后在浏览器地址栏输入刚才存储的地址，点击表单提交，出现刷新页面的情况，这个怎么解决啊？

**Comment by chenshuai2144** [comment]
你的描述我们没法确定问题是什么？
有在线方式吗？

**Comment by a854363956** [comment]
@zhouguanglong  开源社区提问方式
一. 准确的提出问题的情况描述,以及使用的版本信息.
1. 浏览器版本
2. 操作系统的版本
3. ant-design-pro的版本
4. ant-design 版本

二. 最小化资源,只包含基本组件,然后重现BUG,如果能重现将此代码放在github并且把带上地址


> PS: 你这样问环境什么的都不知道谁能回答你? 就算你在公司这样问也没有人回答的了你.
