### ISSUE TITLE
AvatarList的maxLength不起作用

### ISSUE THREAD

**Issue by gc654321** [ant-design/ant-design-pro#3319]
AvatarList设置maxLength后不起作用。https://codesandbox.io/s/42omlv12xw

**Comment by chenshuai2144** [comment]
好像还没有发过版本，最好直接在脚手架中使用，这周我会发一个版本

**Comment by gc654321** [comment]
excessItemsStyle 属性会报错，按照文档上的用法。https://codesandbox.io/s/42omlv12xw 看下console.log

**Comment by chenshuai2144** [comment]
fix in 2.1

**Comment by gc654321** [comment]
好的，感谢
