### ISSUE TITLE
Dependent on script from gw.alipay.com

### ISSUE THREAD

**Issue by khayalan-mathew** [ant-design/ant-design-pro#332]
I saw ant-design-pro is dependent on a script from gw.alipay.com (https://github.com/ant-design/ant-design-pro/blob/master/src/index.ejs#L12). It would be nice to remove this kind of "dependency". 

I looked into it myself, but couldn't get anything valuable, since i can't understand chinese.

**Comment by nikogu** [comment]
`//:gw.alipay.com` is cdn service of Alipay, it is stable & strong, u can use it fearless.

> I looked into it myself, but couldn't get anything valuable, since i can't understand chinese

what does this means ?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/250

**Comment by khayalan-mathew** [comment]
@afc163 thanks
