### ISSUE TITLE
提示This dependency was not found: in dll umi

### ISSUE THREAD

**Issue by yrcourage** [ant-design/ant-design-pro#3321]
![image](https://user-images.githubusercontent.com/8166413/50831727-cc8f4e80-1386-11e9-8e63-3a93c8dd8aad.png)
明明已经安装了

**Comment by chenshuai2144** [comment]
使用了 node api 的包应该在 dev 里面。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3266
