### ISSUE TITLE
关于前后端协作的问题

### ISSUE THREAD

**Issue by junjunsoul** [ant-design/ant-design-pro#3324]
想了解各位前后端是怎么协作的？

- 问题场景：

     前端独立部署通过nginx 代理接口服务。
     前端彻底分离的情况下，后端是如何获取前端的代码进行本地调试的？
     我知道与后端联调可以通过代理后端本地服务进行调试。
     但是如果后端在家里办公，或者后期**多人维护报表**的时候 后端需要前端界面调数据 就不是很方便了。

- 我想到方案是：

     前端在部署时生成dist目录的zip文件推送到cdn让后端下载，进行本地部署调试。
     但是这样感觉还是不够方便，每次后端本地调试都要去下载然后部署前端。

**Comment by xiaohuoni** [comment]
如果处理了CORS问题，那前端就可以在项目中直接请求服务端接口。
然后使用now工具部署一个外网链接提供给后端测试使用。

后端不可用的情况下，前端可以通过mock数据等技术，继续开发。

然后联调的时候，后端凭什么回家！

**Comment by xiaohuoni** [comment]
（黑人？？？）

**Comment by dengfuping** [comment]
- 具体做法: 将构建产物 (`.js` 和  `.css` 文件) 发布到 `cdn` 上，每次迭代都对应一个特定的版本号 `package.version` ，然后通过项目名称 和去保证唯一性，测试环境可覆盖，生产环境无法覆盖。后端直接引入 `cdn` 链接即可，这样前后端可以最大程度的减少耦合。
- 本质上要解决的是 `前端部署` 问题，可能还会涉及到前端的 `基础设施建设` 问题。可以试着推动公司去建立这样的一套前端研发体系和流程，以保障研发和上线流程，增强可控性。

**Comment by junjunsoul** [comment]
> 如果处理了CORS问题，那前端就可以在项目中直接请求服务端接口。
> 然后使用now工具部署一个外网链接提供给后端测试使用。
> 
> 后端不可用的情况下，前端可以通过mock数据等技术，继续开发。
> 
> 然后联调的时候，后端凭什么回家！

如果有多个后端同时需要前端界面调试他本地的报表数据，部署测试外网貌似不行呢

**Comment by junjunsoul** [comment]
> * 具体做法: 将构建产物 (`.js` 和  `.css` 文件) 发布到 `cdn` 上，每次迭代都对应一个特定的版本号 `package.version` ，然后通过项目名称 和去保证唯一性，测试环境可覆盖，生产环境无法覆盖。后端直接引入 `cdn` 链接即可，这样前后端可以最大程度的减少耦合。
> * 本质上要解决的是 `前端部署` 问题，可能还会涉及到前端的 `基础设施建设` 问题。可以试着推动公司去建立这样的一套前端研发体系和流程，以保障研发和上线流程，增强可控性。

这种方案是前端和后端一起部署，在部署的时候把构建产物推到cdn通过，然后在网站index.html 直接引入cdn链接，这方案不错，但是如果后端是纯接口的，独立部署的呢

**Comment by junjunsoul** [comment]
> （黑人？？？）

哈哈，暂时没有黑人同事

**Comment by roc2539** [comment]
> （黑人？？？）

哈哈
