### ISSUE TITLE
关于targets

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design-pro#3326]
edge17上： Unable to get property 'currentAuthority' of undefined or null reference
代码是这样的：
    login.js：
      const response = yield call(adminLogin, loginParams);
      yield put({
        type: 'changeLoginStatus',
        payload: response,
      });
     
changeLoginStatus(state, { payload }) {
      setAuthority(payload.currentAuthority);
      return {
        ...state,
        loginStatus: payload.loginStatus,
        type: payload.type,
      };
    },
试着输出了changeLoginStatus的payload居然再edge上是undefined
config.js已经是配了targets的。
edge14上没问题，
IE9和10是不支持吗，IE仿真模式调到9和10都有以下报错：
This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.

**Comment by 1927344728** [comment]
This browser lacks typed array (Uint8Array) support which is required by buffer v5.x. Use buffer v4.x if you require old browser support.

请问下，这个问题，你解决了吗? @Veigar-C

**Comment by theDoinb** [comment]
没有，好像pro是不承诺支持ie11以下的，我们现在是要求客户得使用谷歌或火狐浏览器了 @1927344728

**Comment by Veigar-C** [comment]
https://github.com/ant-design/ant-design-pro/issues/1396#issuecomment-385190329

@1927344728

**Comment by 1927344728** [comment]
> [#1396 (comment)](https://github.com/ant-design/ant-design-pro/issues/1396#issuecomment-385190329)
> 
> @1927344728

好的。 谢谢
