### ISSUE TITLE
自己添加Layout导致路由出错

### ISSUE THREAD

**Issue by GIn-Liu** [ant-design/ant-design-pro#3328]
自己创建了一个HomeLayout.js引用之后，component: '../layouts/HomeLayout',
routes: [
      { path: '/', redirect: '/home/home' },
      { path: '/home', redirect: '/home/home' },
      { path: '/home/home', component: './Home/Home' },
    ],
输入http://localhost:8000/页面不会议跳到http://localhost:8000/home/home 而且数据也不会显示但会显示
HomeLayout.js里的

**Comment by GIn-Liu** [comment]
使用原有的BlankLayout.js,UserLayout.js等都没有问题

**Comment by hqwlkj** [comment]
@GIn-Liu  你的`router.config.js`配置有问题，请参考以下代码进行配置。
```
// user
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: '/user', redirect: '/user/login' },
      { path: '/user/login', component: './User/Login' },
      { path: '/user/register', component: './User/Register' },
      { path: '/user/register-result', component: './User/RegisterResult' },
    ],
  },
```

**Comment by GIn-Liu** [comment]
> `router.config.js`配置有问题
这是我的配置，问题应该不在这里，
// home
  {
    path: '/',
    component: '../layouts/HomeLayout',
    routes: [
      { path: '/', redirect: '/home/home' },
      { path: '/home', redirect: '/home/home' },
      { path: '/home/home', component: './Home/Home' },
    ],
  },

**Comment by GIn-Liu** [comment]
我用的UserLayout保留整体，只改变return下的div达到了目的
