### ISSUE TITLE
在ant-design-pro使用Affix的一个问题

### ISSUE THREAD

**Issue by zhichao8756** [ant-design/ant-design-pro#3330]
Affix固钉组件默认监听的是body的滚动,但是ant-design-pro页面的滚动实际上是Layout组件,Affix可以使用target属性,但是如何才能监听到Layout组件的滚动?或者改为body滚动?Anchor锚点组件也有同样的疑问

**Comment by afc163** [comment]
ant-design-pro 默认应该是 body 滚动。

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis
pro现在就是 body 滚定的，可以告诉我们是哪个页面吗？

**Comment by xiaohuoni** [comment]
有问题再reopen
