### ISSUE TITLE
部署到IIS服务器,可以访问到页面,但是跳转页面的时候报404, 包括直接输入想要去到的页面路径,也会报404

### ISSUE THREAD

**Issue by hublulu** [ant-design/ant-design-pro#3331]
![image](https://user-images.githubusercontent.com/46511487/50875183-297c1a80-1402-11e9-805a-2b4826bf814f.png)
![image](https://user-images.githubusercontent.com/46511487/50875204-4284cb80-1402-11e9-8374-f1d8e601fef8.png)

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88

**Comment by hublulu** [comment]
@afc163 谢谢, 其实不用hash也可以, 只是将dist内的文件复制粘贴到站点根目录就行
不过有个问题是, 我api请求报错404, 且我配置了IIS代理还是一样报错.
配置规则如下:
![image](https://user-images.githubusercontent.com/46511487/50878289-e83f3700-1410-11e9-836c-d6b194a75f33.png)
![image](https://user-images.githubusercontent.com/46511487/50878301-00af5180-1411-11e9-99ea-4813fa298935.png)
![image](https://user-images.githubusercontent.com/46511487/50878305-115fc780-1411-11e9-9a3e-887fed7314d5.png)
