### ISSUE TITLE
Tabs 动画切换导致错误，竖直tabs样式不生效

### ISSUE THREAD

**Issue by jerryyan1990** [ant-design/ant-design-pro#3333]
**版本：**
"ant-design-pro": "^2.1.1"
"antd": "^3.12.1"

**代码：**
```
import React, { Component } from 'react'
import { Tabs, Radio } from 'antd'

const TabPane = Tabs.TabPane

class Test extends Component {
  state = {
    mode: 'top',
  }

  handleModeChange = (e) => {
    const mode = e.target.value
    this.setState({ mode })
  }

  render () {
    const { mode } = this.state
    return (
      <div>
        <Radio.Group onChange={this.handleModeChange} value={mode} style={{ marginBottom: 8 }}>
          <Radio.Button value="top">Horizontal</Radio.Button>
          <Radio.Button value="left">Vertical</Radio.Button>
        </Radio.Group>
        <Tabs
          defaultActiveKey="1"
          tabPosition={mode}
          style={{ height: 220 }}
        >
          <TabPane tab="Tab 1" key="1">Content of tab 1</TabPane>
          <TabPane tab="Tab 2" key="2">Content of tab 2</TabPane>
          <TabPane tab="Tab 3" key="3">Content of tab 3</TabPane>
          <TabPane tab="Tab 4" key="4">Content of tab 4</TabPane>
          <TabPane tab="Tab 5" key="5">Content of tab 5</TabPane>
          <TabPane tab="Tab 6" key="6">Content of tab 6</TabPane>
          <TabPane tab="Tab 7" key="7">Content of tab 7</TabPane>
          <TabPane tab="Tab 8" key="8">Content of tab 8</TabPane>
          <TabPane tab="Tab 9" key="9">Content of tab 9</TabPane>
          <TabPane tab="Tab 10" key="10">Content of tab 10</TabPane>
          <TabPane tab="Tab 11" key="11">Content of tab 11</TabPane>
        </Tabs>
      </div>
    )
  }
}

export default Test
```

**问题描述：**

使用antd tabs组件官方demo，不能达到预期效果。
 1、tabs组件开启动画切换，切换标签不显示内容，在切换到标签1，点过的标签内容都显示在标签1 内。关闭动画选项后，切换标签正常显示对应内容。
2、tabPosition设置为‘left’或者‘right’，依旧显示为top，不能竖直显示tab。

通过比对生成代码发现
官方Demo页面生成代码为：
`<div role="tablist" class="ant-tabs-bar ant-tabs-left-bar" tabindex="0">`
ant pro页面生成代码为：
`<div role="tablist" class="ant-tabs-bar" tabindex="0">`

**预期：**

可以像官方demo一样，tabPosition设置为left或right，可以竖直显示tab。开启动画选项切换tab可以正确显示相关内容。
![7](https://user-images.githubusercontent.com/12929365/50876439-048aa600-1408-11e9-893c-20c6a32728a8.png)

**图片说明：**

![1](https://user-images.githubusercontent.com/12929365/50876388-c097a100-1407-11e9-8879-37df87105f80.png)
demo初始显示正常

![2](https://user-images.githubusercontent.com/12929365/50876482-3dc31600-1408-11e9-82c5-6339aee04b45.png)
点击tab2 不显示对应内容

![3](https://user-images.githubusercontent.com/12929365/50876490-4e738c00-1408-11e9-8974-ec7d83031d9f.png)
点击tab3不显示对应内容

![4](https://user-images.githubusercontent.com/12929365/50876504-5af7e480-1408-11e9-8b3b-529d72b523a2.png)
点击tab1 显示了tab1，tab2，tab3的内容

![5](https://user-images.githubusercontent.com/12929365/50876518-6fd47800-1408-11e9-8c32-4382b4e8fe00.png)
切换为竖直tab，tab依然显示为横着，同时点击tab不能正确显示相关内容，再点击tab1会显示点过的tab内容。

**Comment by zhangshuai0101** [comment]
[
![image](https://user-images.githubusercontent.com/40013310/50887481-37479500-142e-11e9-98ad-a214d4be984e.png)
](url)
未发现你说的问题

**Comment by zhangshuai0101** [comment]
版本是3.10.10

**Comment by jerryyan1990** [comment]
> [ ![image](https://user-images.githubusercontent.com/40013310/50887481-37479500-142e-11e9-98ad-a214d4be984e.png) ](url)
> 未发现你说的问题，版本是：3.10.10

谢谢，可能是版本问题，那我降级个版本试试
