### ISSUE TITLE
多级菜单下，如何让子菜单不显示，能在面包屑中正常显示？

### ISSUE THREAD

**Issue by doterme** [ant-design/ant-design-pro#3334]
用了最新master分支的代码，现在想实现子菜单在左侧菜单列表中不显示，能在面包屑中正常显示，同时跳转到到子菜单页面后，父菜单能够高亮显示，求教怎么设置。

**Comment by yuzexing** [comment]
![beedb7f8-c4fc-4323-9ca0-caf786bf8d62](https://user-images.githubusercontent.com/17453944/50884158-0f9fff00-1425-11e9-82c8-b75779d24547.png)
是这个效果吗

**Comment by doterme** [comment]
> ![beedb7f8-c4fc-4323-9ca0-caf786bf8d62](https://user-images.githubusercontent.com/17453944/50884158-0f9fff00-1425-11e9-82c8-b75779d24547.png)
> 是这个效果吗

对的

**Comment by yuzexing** [comment]
我是把这里的代码↓
https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js#L102
改成这样了↓
![e9979271-9285-4522-ada2-764769b025eb](https://user-images.githubusercontent.com/17453944/50884945-48d96e80-1427-11e9-9660-9256e7af4e53.png)

面包屑和菜单栏改为使用了两套筛选的条件。
实在没办法可以这样改，我没找到官方改法...

**Comment by doterme** [comment]
> 我是把这里的代码↓
> https://github.com/ant-design/ant-design-pro/blob/master/src/models/menu.js#L102
> 改成这样了↓
> ![e9979271-9285-4522-ada2-764769b025eb](https://user-images.githubusercontent.com/17453944/50884945-48d96e80-1427-11e9-9660-9256e7af4e53.png)
> 还需要配合router.config 中配置 hideInMenu: true
> 
> 面包屑和菜单栏改为使用了两套筛选的条件。
> 实在没办法可以这样改，我没找到官方改法...

thks，我试一下

**Comment by zhangshuai0101** [comment]
现在不就是这样吗？

**Comment by doterme** [comment]
> 现在不就是这样吗？

现在菜单如果设置了hideInMenu: true，在面包屑中也会不显示。

**Comment by doterme** [comment]
@chenshuai2144 大佬，有官方解决方案吗？

**Comment by chenshuai2144** [comment]
官方没有提供，因为 menu 是一切数据的源头。
只提供了hideInBreadcrumb 来在面包屑中隐藏。
@yuzexing  的方法是对的，pro 是比较自由的，可以直接改代码实现

**Comment by luopeihai** [comment]
用猥琐路线重定义 面包屑:

封装 Breadcrumb
import { Link } from 'umi';

export const renderBreadcrumb = (routers) => {
  return (
    <div className="ant-pro-grid-content">
      <div className="ant-page-header has-breadcrumb ant-page-header-ghost">
        <div className="ant-breadcrumb">
          {routers.map((item) => {
            return (
              <span>
                <span class="ant-breadcrumb-link">
                  {item.path ? (
                    <Link to={item.path}>{item.breadcrumbName}</Link>
                  ) : (
                    <span>{item.breadcrumbName}</span>
                  )}
                </span>
                <span class="ant-breadcrumb-separator">/</span>
              </span>
            );
          })}
        </div>
      </div>
    </div>
  );
};
引用 breadcrumb
import { renderBreadcrumb } from '@/components/Breadcrumb';

const CommentView: React.FC<> = (props) => {
  useEffect(() => {}, []);

  const pageHeaderRender = (routersInfo) => {
    let {
      breadcrumb: { routes },
    } = routersInfo;

    routes = [
      ...routes,
      { path: '/post/comment', breadcrumbName: '评论列表' },
      { breadcrumbName: '评论详情' },
    ];
    return renderBreadcrumb(routes);
  };

  return (
    <PageHeaderWrapper pageHeaderRender={pageHeaderRender} title={false}>
      评论详情
    </PageHeaderWrapper>
  );
};

export default CommentView;
