### ISSUE TITLE
请问能关闭Service-Worker么？

### ISSUE THREAD

**Issue by cindyZhang4** [ant-design/ant-design-pro#3336]
如题，因为Service-Worker导致了一些问题，请问有办法关闭么？

**Comment by yuzexing** [comment]
同求，但是如果关闭不了，可以把你的问题贴出来看看

**Comment by cindyZhang4** [comment]
> 同求，但是如果关闭不了，可以把你的问题贴出来看看
主要就是图片里红框那块是跟网站同一个域名下绝对路径引用的别的页面，现在开了Service-Worker一直就找不到这个页面，目测域名更新后这块还是一直取得缓存里的旧东西，现在也是有解决方案，但是还是想了解有木有办法关闭这个Service-Worker，额，不知道我描述的清不清楚
![20190109](https://user-images.githubusercontent.com/35737417/50942451-b89d3700-14c3-11e9-8048-2bc3a04f8542.jpg)

**Comment by chenshuai2144** [comment]
只要关掉 pwa 就可以了

**Comment by chenshuai2144** [comment]
在 config.js里面删掉 pwa 配置就好了

**Comment by rainjm** [comment]
@chenshuai2144 但是之前的资源还是 from ServiceWorker，怎么处理

**Comment by cindyZhang4** [comment]
> @chenshuai2144 但是之前的资源还是 from ServiceWorker，怎么处理

清除下浏览器缓存

**Comment by cwtuan** [comment]
cmd+shift+R强刷，可以取得最新内容:

![image](https://user-images.githubusercontent.com/3455798/53684403-d3fc2400-3d47-11e9-9083-2df511c2b97b.png)

问题是，强刷后，下次进来，不是应该取最新内容，怎么还是从worker取老的内容？之前已经重刷成功了

![image](https://user-images.githubusercontent.com/3455798/53684398-c5157180-3d47-11e9-8a7f-d16d697a02f7.png)

**Comment by xahy123** [comment]
> cmd+shift+R强刷，可以取得最新内容:
> 
> ![image](https://user-images.githubusercontent.com/3455798/53684403-d3fc2400-3d47-11e9-9083-2df511c2b97b.png)
> 
> 问题是，强刷后，下次进来，不是应该取最新内容，怎么还是从worker取老的内容？之前已经重刷成功了
> 
> ![image](https://user-images.githubusercontent.com/3455798/53684398-c5157180-3d47-11e9-8a7f-d16d697a02f7.png)

你好请问你有解决吗
