### ISSUE TITLE
ant design pro 2 动态菜单

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#3337]
我想把ant design pro 2的菜单，路由，权限 做活掉，
网上都找不到什么资料，
还请各位专家指点下，谢谢了！

**Comment by xiaohuoni** [comment]
菜单可以修改 src/models/menu.js
路由我尝试了几种方式，好像都还不行，方案待定吧。
权限可以参考 https://github.com/ant-design/ant-design-pro/pull/2928
后续官网的文档上会体现。

**Comment by xyzabc0004** [comment]
后续官网上会有更新这一部分？！ @xiaohuoni

**Comment by xiaohuoni** [comment]
肯定会的吧，问的人这么多

**Comment by xyzabc0004** [comment]
真希望如此！ @xiaohuoni

**Comment by a854363956** [comment]
> 菜单可以修改 src/models/menu.js
> 路由我尝试了几种方式，好像都还不行，方案待定吧。
> 权限可以参考 #2928
> 后续官网的文档上会体现。

其实我感觉他们关注的动态菜单,而不是动态路由,动态路由放在后台个人感觉意义不大. - - !!

**Comment by luzhongchang** [comment]
按照上面的说法，其实本地都要配置好路由然后在menu中配置是否显示吧，我这边有这么一个需求，就是menu 全部是指向同一个component只是参数不同 ，然后我配置好了，当点击menu的时候 路由参数是变了 但是页面还是原来的那个页面，没有动，有什么办法可以解决 点击menu后 重新刷新页面

**Comment by xiaomai7758** [comment]
菜单用了dva的model,但SiderMenu组件中还是用的React.memo(对这个不了解)
这样导致我在model.menu中修改menuData的数据不会实时生效,得点一下折叠菜单才可以.
我把React.memo改成React.Component了,这样比较好
> model/menu.js 加两行
```
// 1.顶部引入
import { getFlatMenuKeys } from '@/components/SiderMenu/SiderMenuUtils';
// 2.reducers中 
save(state, action) {
      // 这里加一行处理
      state.tree = getFlatMenuKeys(action.payload.menuData);
      return {
        ...state,
        ...action.payload,
      };
    },
```
> src/components/SiderMenu/index.js
```js
import React from 'react';
import { Drawer } from 'antd';
import SiderMenu from './SiderMenu';
import { getFlatMenuKeys } from './SiderMenuUtils';
import { connect } from 'dva';

// const SiderMenuWrapper = React.memo(props => {
//   const { isMobile, menuData, collapsed, onCollapse } = props;
//   const flatMenuKeys = getFlatMenuKeys(menuData);
//   return isMobile ? (
//     <Drawer
//       visible={!collapsed}
//       placement="left"
//       onClose={() => onCollapse(true)}
//       style={{
//         padding: 0,
//         height: '100vh',
//       }}
//     >
//       <SiderMenu {...props} flatMenuKeys={flatMenuKeys} collapsed={isMobile ? false : collapsed} />
//     </Drawer>
//   ) : (
//     <SiderMenu {...props} flatMenuKeys={flatMenuKeys} />
//   );
// });

@connect(({ menu }) => ({ menu }))
class SiderMenuWrapper extends React.Component {
  render() {
    return this.props.isMobile ? (
      <Drawer
        visible={!this.props.collapsed}
        placement="left"
        onClose={() => this.props.onCollapse(true)}
        style={{
          padding: 0,
          height: '100vh',
        }}
      >
        <SiderMenu {...this.props} flatMenuKeys={this.props.menu.tree} collapsed={this.props.isMobile ? false : this.props.collapsed} />
      </Drawer>
    ) : (
        <SiderMenu {...this.props} flatMenuKeys={this.props.menu.tree} />
      );
  }
}

export default SiderMenuWrapper;
```

**Comment by xiaomai7758** [comment]
> > 按照上面的说法，其实本地都要配置好路由然后在menu中配置是否显示吧，我这边有这么一个需求，就是menu 全部是指向同一个component只是参数不同 ，然后我配置好了，当点击menu的时候 路由参数是变了 但是页面还是原来的那个页面，没有动，有什么办法可以解决 点击menu后 重新刷新页面
> 
> 可以的,在页面中获取当前URL的参数,如果发现不对就重新刷新页面,目前想到的解决方案,但是不够优雅

子菜单是同一组件,我加的route都是404...

**Comment by a854363956** [comment]
> > > 按照上面的说法，其实本地都要配置好路由然后在menu中配置是否显示吧，我这边有这么一个需求，就是menu 全部是指向同一个component只是参数不同 ，然后我配置好了，当点击menu的时候 路由参数是变了 但是页面还是原来的那个页面，没有动，有什么办法可以解决 点击menu后 重新刷新页面
> > 
> > 
> > 可以的,在页面中获取当前URL的参数,如果发现不对就重新刷新页面,目前想到的解决方案,但是不够优雅
> 
> 子菜单是同一组件,我加的route都是404...

404 表示你没有注册对应的route,你检查你的route.config

**Comment by kzabc** [comment]
@xiaohuoni 不知道各位大佬是否有了解决方案

**Comment by xiaohuoni** [comment]
@kzabc 你说的是啥？

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/264
