### ISSUE TITLE
在查询表格里插入一条描述很长的数据，会把表格撑到外面去。

### ISSUE THREAD

**Issue by vxzhong** [ant-design/ant-design-pro#3339]
查询表格，新建，然后描述，填写：
rtsp://115.233.21.38/PLTV/88888913/224/3221227767/10000100000000060000000000304156_0.smil?rrsip=220.191.136.24&icpid=SSPID&accounttype=1&limitflux=-1&limitdur=-1&accountinfo=:20181013144253,158010977526,116.30.198.187,20181013144253,20002000000000010000000002770617,9F9869A7A6BCBC7B818B1DA24CAC748A,-1,0,1,,,2,,,,2,END

然后表格后面的列就被撑到屏幕外面去了。貌似设置width也不生效。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
