### ISSUE TITLE
最新版build nginx部署非根目录 刷新404

### ISSUE THREAD

**Issue by Pancho2wang** [ant-design/ant-design-pro#3340]
最新版build nginx部署非根目录 刷新404
![default](https://user-images.githubusercontent.com/6365417/50894207-982a9980-143d-11e9-9e79-8b81ad474853.png)
版本是2.1.1
antd版本为 3.11.6

config配置：
![default](https://user-images.githubusercontent.com/6365417/50894438-39195480-143e-11e9-9235-765dfca47594.png)
![default](https://user-images.githubusercontent.com/6365417/50894455-40d8f900-143e-11e9-82b9-30b1e25dbc61.png)

nginx 配置：
![default](https://user-images.githubusercontent.com/6365417/50894325-e8096080-143d-11e9-9a86-0e2993395b65.png)

但是antd版本为3.10.4的版本是正确的
![default](https://user-images.githubusercontent.com/6365417/50894387-0ff8c400-143e-11e9-8b8c-aad176062577.png)

**Comment by Pancho2wang** [comment]
在src/service-worker.js中修改：
workbox.routing.registerNavigationRoute('/index.html')
成
workbox.routing.registerNavigationRoute('/antd/index.html')
重新打包，清楚缓存，就能刷出来了。这里是注册引导路径文件。
pwa相关配置 workbox

**Comment by zssjz** [comment]
非根目录下访问 "/", 重定向到页面是可以访问的，单独访问配置的路由就是404 ，楼上的后来怎么处理的

**Comment by zssjz** [comment]
后来用了hash，解决了
