### ISSUE TITLE
打开官网报错Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by shepiguai** [ant-design/ant-design-pro#3341]
![11](https://user-images.githubusercontent.com/25193960/50898125-1e98a880-1449-11e9-960e-d9dfbc536d7c.png)
在无痕模式下浏览没有问题

**Comment by chenshuai2144** [comment]
试着删除一下权限呢？

**Comment by a854363956** [comment]
如果在无痕模式下浏览没有问题,那么按 CTRL+ALT+DELETE 清除浏览器缓存即可!

**Comment by my1229** [comment]
同问，fork的pro 2.0,  本地 umi dev不会出现，服务器build后就会出现这个。。。
所以每次都要清缓存吗？    求大神指点

**Comment by zhangyanan0525** [comment]
我也遇到了这个问题。本地开发没事，线上报错。请大神指点下

**Comment by chenshuai2144** [comment]
应该只需要清理一次，我需要知道怎么重现，这样可以再代码中修正它

**Comment by xiaohuoni** [comment]
其实每次发布的时候，建议修改，存储的key值：antd-pro-authority
