### ISSUE TITLE
背景图片在页面审查时，与传入的url地址不同

### ISSUE THREAD

**Issue by catherinejing** [ant-design/ant-design-pro#3345]
同时使用一个变量来作为img 的src属性能够正常加载，但是作为div的backgroundImage的url就不能正常加载，通过审查元素，发现其地址与img的src地址不同。请问下这是什么原因？

 "version": "1.0.1"

![image](https://user-images.githubusercontent.com/23182362/50907647-d71f1600-1462-11e9-85b5-96374c692779.png)

**Comment by chenshuai2144** [comment]
感觉不是框架的问题，是不是变量缓存的问题？

**Comment by catherinejing** [comment]
> 感觉不是框架的问题，是不是变量缓存的问题？

您好，非常感谢您抽空帮我看问题，确实与框架无关，是文件路径的原因，里面包含反斜杠。
再次感谢您的帮助，谢谢
