### ISSUE TITLE
electron 无法直接运行 antd pro 编译后的静态文件的解决方案

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design-pro#3346]
umi 2.x 打包的文件貌似只能在 http server 下运行

翻遍 [awesome-electron](https://github.com/sindresorhus/awesome-electron) 找到一个 [electron-serve](https://github.com/sindresorhus/electron-serve) 库，可以支持运行 umi 2.x 编译的静态文件

umi 配置 config/config.js 或 .umirc.js 添加或修改 chainWebpack 属性来支持 electron-renderer 

```js
export default {
  chainWebpack(config, { webpack }) {
    config.target('electron-renderer');
  },
};
```

**Comment by chenshuai2144** [comment]
pro 默认会按照 web 应用来打包的
https://github.com/ant-design/ant-design-pro/issues/1874

**Comment by harryzzp** [comment]
> pro 默认会按照 web 应用来打包的
> #1874

请问有没有官方的electron打包配置最佳实践，如果目前没有，是否有计划？
谢谢！

**Comment by lemonc747** [comment]
> umi 2.x 打包的文件貌似只能在 http server 下运行
> 
> 翻遍 [awesome-electron](https://github.com/sindresorhus/awesome-electron) 找到一个 [electron-serve](https://github.com/sindresorhus/electron-serve) 库，可以支持运行 umi 2.x 编译的静态文件
> 
> umi 配置 config/config.js 或 .umirc.js 添加或修改 chainWebpack 属性来支持 electron-renderer �
> 
> ```js
> export default {
>   chainWebpack(config, { webpack }) {
>     config.target('electron-renderer');
>   },
> };
> ```

我使用的是antd-pro，无http服务启动成功了，我测试的结果如下：
1. 可以不用配置webpack.target（如果要配置，一样的，在antd-pro中config/plugin.config.js添加config.target('electron-renderer');）
2. 需要配置hashhistory，因为没有后端路由跳转，只能识别静态文件。在config.config.js中添加history: 'hash',
3. 配置静态文件路径，在config/config.js中配置publicPath: './'。默认是绝对路径'/'。

新手尝试不知道这种方式对不对，如果有更好的解决方案也@一下我啊，谢谢0 0

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by scucat** [comment]
没有plugin.config.js文件呀
