### ISSUE TITLE
最新版的Pro中css样式文件不起作用？

### ISSUE THREAD

**Issue by Yoping** [ant-design/ant-design-pro#3348]
我clone最新版的pro之后把之前写的的一些代码迁移到这个项目上来，pro中使用的是less，但是我之前的代码是直接使用的css样式，拷过来之后css样式不起作用了，请问一下怎么让less和css共存？看了其他人提的问题，但是还是没有解决，是css_module导致css不起作用的吗？改怎么做呢？请大神指教！

**Comment by chenshuai2144** [comment]
在 golbal.less中引用就好了，
或者直接在 ejs 中引入

**Comment by Yoping** [comment]
首先感谢回复！在golbal.less引入？import？有点懵。。CSS文件很多，逐个引入吗？还是说引入一个什么配置文件就行了？或者，开关？不好意思，本人小白，不是很清楚，可否贴一下代码，或者截个图？也方便其他的同学一起学习，非常感谢！
这是我的golbal.less文件：
html,
body,
#root {
  height: 100%;
}

.colorWeak {
  filter: invert(80%);
}

.ant-layout {
  min-height: 100vh;
}

canvas {
  display: block;
}

body {
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.globalSpin {
  width: 100%;
  margin: 40px 0 !important;
}

ul,
ol {
  list-style: none;
}

**Comment by Yoping** [comment]
OK，解决了，在config文件里面的css模块化加载规则中添加这一行“context.resourcePath.includes('.css') ||”，排除后缀为.css的文件就可以了。
cssLoaderOptions: {
    modules: true,
    getLocalIdent: (context, localIdentName, localName) => {
      if (
        context.resourcePath.includes('node_modules') ||
        context.resourcePath.includes('.css') ||
        context.resourcePath.includes('ant.design.pro.less') ||
        context.resourcePath.includes('global.less')
      ) {
        return localName;
      }
      const match = context.resourcePath.match(/src(.*)/);
      if (match && match[1]) {
        const antdProPath = match[1].replace('.less', '');
        const arr = slash(antdProPath)
          .split('/')
          .map(a => a.replace(/([A-Z])/g, '-$1'))
          .map(a => a.toLowerCase());
        return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
      }
      return localName;
    },
  },
