### ISSUE TITLE
TimelineChart引用错误

### ISSUE THREAD

**Issue by andy1247008998** [ant-design/ant-design-pro#3352]
TypeError: data.sort is not a function
TimelineChart.render
src/components/Charts/TimelineChart/index.js:29
  26 |   ],
  27 | } = this.props;
  28 | 
> 29 | data.sort((a, b) => a.x - b.x);
     | ^  30 | 
  31 | let max;
  32 | if (data[0] && data[0].y1 && data[0].y2) {

**Comment by andy1247008998** [comment]
TimelineChart缺少对空数据状态的处理。当图表刚刚加载data为空数组时，就会导致这个问题。

**Comment by imhele** [comment]
在 `data.sort()` 前有对 `undefined` 的处理，是没有生效吗？
```js
const {
data = [
    {
      x: 0,
      y1: 0,
      y2: 0,
    },
  ],
} = this.props;
```

**Comment by chenshuai2144** [comment]
他只会判断 key in props ，给赋值一个 `undefined `是无法处理的

**Comment by imhele** [comment]
我在 https://github.com/ant-design/ant-design-pro/blob/master/src/pages/Dashboard/OfflineData.js#L51 
直接赋值 `undefined` 不会报错，可能传入了 `null` 或者其它非 `Array` 类的值，我加一下判断。
