### ISSUE TITLE
antd pro按需加载报错

### ISSUE THREAD

**Issue by lwfwind** [ant-design/ant-design-pro#3353]
import {Ellipsis} from 'ant-design-pro';
**报错堆栈**
ERROR in ./node_modules/ant-design-pro/node_modules/@antv/data-set/build/data-set.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "@babel/preset-env" relative to directory "D:\\gitlab\\DWD-Test-cola\\node_modules\\ant-design-pro\\node_modules\\@antv\\data-set"
    at D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\gitlab\DWD-Test-cola\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\gitlab\DWD-Test-cola\node_modules\babel-loader\lib\index.js:50:20)
 @ ./node_modules/ant-design-pro/lib/Charts/TimelineChart/index.js 35:15-40
 @ ./node_modules/ant-design-pro/lib/Charts/index.js
 @ ./node_modules/ant-design-pro/lib/index.js
 @ ./src/pages/DashBoard/views/index.js
 @ ./src/pages/DashBoard/index.js
 @ ./src/pages/router.js
 @ ./src/pages/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8001 (webpack)/hot/dev-server.js ./src/index.js
i ｢wdm｣: Failed to compile.

**我的babelrc配置**
```javascript
{
  "presets": [
    "react",
    [
      "env",
      {
        "targets": {
          "node": "current"
        }
      }
    ]
  ],
  "comments": false,
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-object-rest-spread",
    ["import", {
      "libraryName": "antd",
      "style": true
    },"import", {
      "libraryName": "ant-design-pro",
      "libraryDirectory": "lib",
      "style": true,
      "camel2DashComponentName": false
    }]
  ]
}
```

**我的package.json**
```javascript
{
  "name": "dwd-test-hermes",
  "version": "1.0.0",
  "description": "DWD-Test-Hermes",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --hot --watch --port=8001 --open",
    "build": "webpack --config webpack.production.js && npm run upload",
    "upload": "node upload.js",
    "node": "pm2 start ./index.js --watch"
  },
  "keywords": [],
  "author": "jaja",
  "license": "ISC",
  "dependencies": {
    "@antv/data-set": "0.9.0",
    "@antv/g2": "^3.2.8",
    "@koa/cors": "2",
    "ant-design-pro": "^2.1.1",
    "antd": "^3.11.0",
    "axios": "^0.18.0",
    "babel-core": "^6.26.3",
    "babel-plugin-import": "^1.7.0",
    "babel-polyfill": "^6.26.0",
    "babel-register": "^6.26.0",
    "bizcharts": "3.2.2",
    "clean-webpack-plugin": "^0.1.19",
    "config": "^1.30.0",
    "immutable": "^3.7.4",
    "koa": "^2.5.1",
    "koa-bodyparser": "^4.2.0",
    "koa-json": "^2.0.2",
    "koa-logger": "^3.2.0",
    "koa-onerror": "^4.0.0",
    "koa-proxy": "^0.9.0",
    "koa-router": "^7.4.0",
    "koa-static": "^4.0.2",
    "koa-webpack": "^3.0.2",
    "less": "^3.0.2",
    "lodash": "^4.17.10",
    "moment": "^2.22.1",
    "path-to-regexp": "2.4.0",
    "rc-editor-mention": "^1.1.6",
    "react": "^16.6.3",
    "react-css-modules": "^4.7.8",
    "react-dom": "^16.6.3",
    "react-highlight-words": "^0.15.0",
    "react-hot-loader": "^4.1.3",
    "react-redux": "6.0.0-beta.2",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0",
    "redux-thunk": "2.3.0",
    "styled-components": "^2.2.1",
    "numeral": "^2.0.6",
    "xml2js": "^0.4.19"
  },
  "devDependencies": {
    "ali-oss": "^5.3.0",
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-remove-strict-mode": "^0.0.2",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "co": "^4.6.0",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.9.1",
    "less-loader": "^4.1.0",
    "postcss-loader": "^2.1.4",
    "redux-immutable-state-invariant": "^1.2.4",
    "redux-logger": "^3.0.6",
    "rimraf": "^2.6.2",
    "source-map-loader": "^0.2.3",
    "style-loader": "^0.21.0",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.15",
    "webpack-dev-server": "^3.1.3",
    "webpack-manifest-plugin": "^2.0.3"
  }
}
```

**Comment by chenshuai2144** [comment]
这是一个标准的包没找到的报错.试着用cnpm重新安装一下

**Comment by afc163** [comment]
麻烦提问的时候格式化一下 issue，现在没法正常阅读。

**Comment by lwfwind** [comment]
> 这是一个标准的包没找到的报错.试着用cnpm重新安装一下
重新安装过了，还是一样的错
我的package依赖里本身不包括@babel/preset-env 而包含了"babel-preset-env": "^1.7.0",另外@babel/preset-env和babel-preset-env啥区别？

**Comment by lwfwind** [comment]
> 麻烦提问的时候格式化一下 issue，现在没法正常阅读。

感觉蛮清晰了哈，我稍微格式化了下

**Comment by afc163** [comment]
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by afc163** [comment]
`@babel/preset-env` 是 babel 7 的插件，`babel-preset-env` 是 babel 6 的插件。

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by lwfwind** [comment]
> `@babel/preset-env` 是 babel 7 的插件，`babel-preset-env` 是 babel 6 的插件。

多谢，但我用的babel 6，antd pro 的依赖@antv/data-set用的是babel 7， 有没有workaround的方案呢

**Comment by lwfwind** [comment]
> https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

已经更新

**Comment by afc163** [comment]
`@antv/data-set` 是个前端库，不会依赖 babel。

https://github.com/antvis/data-set/blob/66bc152fb961dc3c7a8c1149d089ff471b44cb53/package.json#L93-L111

**Comment by afc163** [comment]
```jsx
    ["import", {
      "libraryName": "antd",
      "style": true
    }],
    ["import", {
      "libraryName": "ant-design-pro",
      "libraryDirectory": "lib",
      "style": true,
      "camel2DashComponentName": false
    }]
```

**Comment by lwfwind** [comment]
> `@antv/data-set` 是个前端库，不会依赖 babel。
> 
> https://github.com/antvis/data-set/blob/66bc152fb961dc3c7a8c1149d089ff471b44cb53/package.json#L93-L111
> 
> 应该和这个没关系，你最好直接提供可重现的最小化 git repo。

这个地址的devDependencies 不是有"@babel/preset-env": "^7.0.0",

**Comment by lwfwind** [comment]
> ant-design-pro

这个配置是根据https://pro.ant.design/docs/use-components-alone-cn

**Comment by afc163** [comment]
依赖的 devDependencies 是不会被安装的。

**Comment by afc163** [comment]
> 这个配置是根据https://pro.ant.design/docs/use-components-alone-cn

你格式写错了，仔细比较下我的写法和你的写法。

**Comment by lwfwind** [comment]
> 不太一样哦，你再仔细比较下。
> 
> 如果还搞不定，提供一个可重现的最小化 git repo，我直接给你发 PR。

https://github.com/lwfwind/antd_pro_babel_issue，请查看

**Comment by afc163** [comment]
https://github.com/lwfwind/antd_pro_babel_issue/pull/1
