### ISSUE TITLE
关于less.min的问题

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design-pro#3359]
打包后再nginx，
setting.js：
import lessMin from '../../public/less.min'

lessScriptNode.src = lessMin;
或
lessScriptNode.src = '/less.min.js';

都会去加载：https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js？

**Comment by Veigar-C** [comment]
刚看了看，打包后index.html引入了：
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
what?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/config/plugin.config.js#L29
那个是插件的默认行为

**Comment by Veigar-C** [comment]
lessUrl: '/less.min.js'
