### ISSUE TITLE
实现了动态菜单，但是如何根据服务端返回的path，去加载我的component？

### ISSUE THREAD

**Issue by heyanfeng** [ant-design/ant-design-pro#3360]
1.因为我的系统是通过后端根据登陆人的身份去拉取不同权限的菜单，所以前端不存在菜单权限控制。
2.根据官网提示，在menu.js里面通过请求取拉取了菜单数据，并修改为了类似的数据结构，前端顺利将菜单渲染出来了。
3.本地的router.config.js里面通过component挂载了相应的path和component的映射关系
4.但是怎么将路由挂载到我的动态菜单呢。。。？也就是访问不同的path，要展示不同的component，看了很多相关issue，好像没看到关键，或者是我没看明白。。。

**Comment by roc2539** [comment]
前端菜单写死。根据后端的传来的用户权限来控制是否显示就好了。

**Comment by heyanfeng** [comment]
> 前端菜单写死。根据后端的传来的用户权限来控制是否显示就好了。

是的，我刚和后端沟通了，可以这么做，就是好奇，如果是传过来的动态菜单，怎么动态挂载组件

**Comment by heyanfeng** [comment]
> 你可以理解成一个，组件已经全部打包了，只是根据path展示显示而已
> `(path)=>compentent`

如果只是后端传回来的菜单，访问那个path，这个怎么去找page下面的component

**Comment by heyanfeng** [comment]
> 这个在router.config.js里面已经规定好了
明白了

**Comment by gaoqiang19514** [comment]
> > 前端菜单写死。根据后端的传来的用户权限来控制是否显示就好了。
> 
> 是的，我刚和后端沟通了，可以这么做，就是好奇，如果是传过来的动态菜单，怎么动态挂载组件

没什么实际意义，除非你的组件也是动态传过来，并且映射好关系，一起发给前端
