### ISSUE TITLE
TimelineChart 如何 用ds 控制 max、min

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design-pro#3371]
Slider 修改区间时希望最大最小重新计算

**Comment by chenshuai2144** [comment]
感觉你好像问错地方了。
>ps 我很讨厌用dataset

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/51094072-c7962900-17e4-11e9-8b2a-ba4bef36cc2d.png)
