### ISSUE TITLE
表单提交导致应用重新加载

### ISSUE THREAD

**Issue by YunzhiWei** [ant-design/ant-design-pro#3373]
在页面上的表单提交数据后，整个单页应用被重新加载了，而不是只是单单执行表单提交的指定动作。

问题的复现：

1. 复现环境：ant-design-pro 2.1.1，Chrome 浏览器 版本 71.0.3578.98
2. 复现步骤：

步骤 1. 打开源文件：src/pages/Account/Settings/BaseView
步骤 2. 为 BaseView 组件增加 handleSubmit 函数

```
  handleSubmit = () => {
    console.log('hello world');
  }
```

步骤 3. 修改表单提交按钮的属性（增加 htmlType='submit'），使其能够触发表单提交动作，也就是刚刚添加的 handleSubmit 函数

```
<Button type="primary" htmlType='submit'>
```

步骤 4. 运行 and-design-pro，登陆，进入程序主界面
步骤 5. 进入 “个人设置” 页面（路由地址为：http://localhost:8000/account/settings/base）
步骤 6. 点击 ”更新基本信息“ 按钮

期望结果：期望在浏览器的开发者工具的 console 终端中，能够看到调试信息输出：hello world，而且 调试信息会停在那里，之后如果反复执行步骤 6 （点击 ”更新基本信息“ 按钮） 会看到更多的 hello world

实际结果：调试信息 hello world 一闪而过，整个 web 应用似乎被重新加载了，程序重新初始化了。

**Comment by chenshuai2144** [comment]
默认的提交按钮就是会刷新页面，相当于发起了一个get请求。只需要
```
handleSubmit = (e) => {
  e.preventDefault();
}
```

**Comment by YunzhiWei** [comment]
谢谢回复，确认问题已解决！

响应速度相当快，👍
