### ISSUE TITLE
how to handle i18n in util function?

### ISSUE THREAD

**Issue by hardfist** [ant-design/ant-design-pro#3374]
<img width="554" alt="2019-01-13 10 43 07" src="https://user-images.githubusercontent.com/8898718/51086697-bcabac00-1784-11e9-932e-829b7b61e37f.png">
It seems that some prompts are  hardcode as chinese in https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js, how to handle I18n in util functions?

**Comment by chenshuai2144** [comment]
use `formatMessage `

```
import { formatMessage } from 'umi/locale';
const message = formatMessage({id:""})

```

**Comment by hardfist** [comment]
> use `formatMessage `
> 
> ```
> import { formatMessage } from 'umi/locale';
> const message = formatMessage({id:""})
> ```

does it work for server side environments? It seems that setLocale and formatMessage needs to be called in the same call stack, otherwise other user's call `setLocale` may influence the locale context.
