### ISSUE TITLE
组件国际化后单元测试报错

### ISSUE THREAD

**Issue by fengsx** [ant-design/ant-design-pro#3376]
比如我直接修改 ant design pro 初始化后的的 `src/components/AvatarList/index.js`，如下
![image](https://user-images.githubusercontent.com/7709602/51104485-38f3cd00-1821-11e9-91e2-fb49bd17eb22.png)

接着运行`npm run test:component`，结果如图：

![image](https://user-images.githubusercontent.com/7709602/51104499-43ae6200-1821-11e9-9997-a1664a9b518d.png)

如果组件里有 `formatMessage`，黄色警告，如果有 `<FormattedMessage /> ` 红色报错。

**Comment by linyongping** [comment]
检查一下
```src/config```
中的
 ```    
  locale: {
        enable: true, // default false
        default: 'zh-CN', // default zh-CN
        baseNavigator: false, // default true, when it is true, will use `navigator.language` overwrite default
      }
```
enable设为true试试

**Comment by imhele** [comment]
format 开头的函数本身是一个空函数，只有实际启动项目之后才会从 ReactIntl Provider 的 context 里拿到，实际项目运行应该是没问题的，这里可能需要改一下单元测试的逻辑，等我看看

**Comment by yutingzhao1991** [comment]
国际化的插件会在最外层封装一些组件，如果直接测试组件国际化是无法生效的，就类似在组件的单测用你无法测试 dva 的 model 一样的道理。设计到相关测试的或者使用 e2e 测试，或者 mock 掉这些方法把。
