### ISSUE TITLE
path.replace(cwd,'') is not function

### ISSUE THREAD

**Issue by jaysg** [ant-design/ant-design-pro#3377]
![_20190114112825](https://user-images.githubusercontent.com/28700250/51095425-92db9f00-17ef-11e9-934e-b7033368e1b5.png)
###问题
dev环境下,在编辑器修改代码触发浏览器刷新会出现path.replace(cwd,'') is not function
错误代码指向node_modules文件夹
###复现
条件不确定.
编辑器:VSCode
浏览器:QQ浏览器,谷歌,火狐均会出现

**Comment by sorrycc** [comment]
`webpackbar/dist/utils/index.js` 57 行打印下看看 path 给的是什么。

**Comment by jaysg** [comment]
@sorrycc 在这个地方加console.log没有在devtool和terminal看到输出,

**Comment by jaysg** [comment]
![Uploading image.png…]()

**Comment by jaysg** [comment]
![_20190118144505](https://user-images.githubusercontent.com/28700250/51369761-b5432480-1b2f-11e9-8905-1ec484c191c5.png)
找到问题了,捕捉到了一个时间戳

**Comment by painoBoy** [comment]
老哥 你这个时间戳捕捉到后又是什么问题呢
我这有时候也会有这种错误
