### ISSUE TITLE
SiderMenu样式的问题

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design-pro#3382]
线上预览版跟本地版有点不一样，本地版了多了‘ant-drawer-header’
![_20190115114752](https://user-images.githubusercontent.com/9401913/51157594-802e9c00-18bb-11e9-9db5-15aebf766060.png)
![_20190115114818](https://user-images.githubusercontent.com/9401913/51157597-84f35000-18bb-11e9-97e9-a6fa00eb3c03.png)

**Comment by imhele** [comment]
Fixed in antd@3.12.2 https://github.com/ant-design/ant-design/pull/14264
