### ISSUE TITLE
Input 怎样禁止输入不合验证规则的值？

### ISSUE THREAD

**Issue by zhouguanglong** [ant-design/ant-design-pro#3384]
想做一个在form的getFieldDecorator中验证金额的输入框，禁止输入非数字或小数点的值，不使用InputNumber，该怎么做呢？框架中可以提供这种功能组件吗？

**Comment by a854363956** [comment]
可以根据pattern属性来进行正则表达式来进行校验

详细请查看 https://ant.design/components/form-cn/   

更多高级用法可研究 [async-validator](https://github.com/yiminghe/async-validator)。

**Comment by whateveryoudo** [comment]
尝试下getValueFromEvent  获取到event对象, 可以在这个方法里面做判断  感觉和 onchange类似

**Comment by whateveryoudo** [comment]
监听错误是什么意思？  你传入方法  在这个方法里面判断啊, `getValueFromEvent : formatInput`   formatInput的参数列表能够取到event,这里用正则判断,不过不知道如何获取原始值（感觉可以取state里面的）；通过就return e.target.value  否则返回原始值

**Comment by a854363956** [comment]
> pattern 监听可以，禁止输入不行，使用getValueFromEvent 时，监听老是错误

监听错误值得是什么? onchange事件不应该会出这个问题.或者whateveryoudo 的getValueFromEvent,这些都可以实现

**Comment by whateveryoudo** [comment]
要么你这个field不用getFieldDecorator  包装,  使用onchange  到时候提交 同步下数据就完了。

**Comment by zhouguanglong** [comment]
<InputNumber style={{width:'100%'}} formatter={limitDecimals} parser={limitDecimals} placeholder="请输入" autoComplete="off"/>
export function limitDecimals(value){
	    const reg = /^(\-)*(\d+)\.(\d\d).*$/;
	    if( value && typeof value === 'string') {
					if( !isNaN(Number(value))  ){
						  if( Number(value) < 1000000000 ){
						  	  message.destroy()
							  return value.replace(reg, '$1$2.$3')
						  }else{
						  	message.warning('最多9位整数，2位小数')
						  	  return value.slice(0,value.length-1)
						  }
						
					}else{
						message.warning('只能输入数字或小数点')
						return value.slice(0,value.length-1)
					}
    	}
  };
这样 使用 InputNumber 解决的，使用了 getFieldDecorator  包装，也监听了 value,但是还有个 bug，如果有小数且小数点后 为一个0或者两个0的话会自动去除小数点保留整数

**Comment by zhouguanglong** [comment]
组件：<InputNumber style={{width:'100%'}} formatter={limitDecimals} parser={limitDecimals} placeholder="请输入" autoComplete="off"/>
函数：
export function limitDecimals(value){
	    const reg = /^(\-)*(\d+)\.(\d\d).*$/;
	    if( value && typeof value === 'string') {
					if( !isNaN(Number(value))  ){
						  if( Number(value) < 1000000000 ){
						  	  message.destroy()
							  return value.replace(reg, '$1$2.$3')
						  }else{
						  	message.warning('最多9位整数，2位小数')
						  	  return value.slice(0,value.length-1)
						  }
						
					}else{
						message.warning('只能输入数字或小数点')
						return value.slice(0,value.length-1)
					}
    	} 
  };
这样解决的，使用了 getFieldDecorator 包装，监听也起作用，可以使用 message 提示，总感觉这样提示不好，还有个 bug，就是 有小数且 小数点后 为一个0或者两个0 的话 会自动删掉小数点后的0而取整

**Comment by zhouguanglong** [comment]
`export function limitDecimals(value){
          const reg = /^(-)(\d+).(\d\d).$/;
          if( value && typeof value === 'string') {
                 if( !isNaN(Number(value)) ){
                         if( Number(value) < 1000000000 ){
                                 message.destroy()
                                 return value.replace(reg, '$1$2.$3')
                          }else{
                                  message.warning('最多9位整数，2位小数')
                                 return value.slice(0,value.length-1)
                          }
                   }else{
		          message.warning('只能输入数字或小数点')
		          return value.slice(0,value.length-1)
	            }
	} 
};`
这样解决的，使用了 getFieldDecorator 包装，监听也起作用，可以使用 message 提示，总感觉这样提示不好，还有个 bug，就是 有小数且 小数点后 为一个0或者两个0 的话 会自动删掉小数点后的0而取整

**Comment by linyongping** [comment]
```
getFieldDecorator('id',{ normalize: normalize }  )(<InputNumber /> )
function normalize(value) {
  // 可以对输入的值做处理后返回field
    return value + 1
}
```
