### ISSUE TITLE
[RP] 提一个页面css主界面美化的建议

### ISSUE THREAD

**Issue by a854363956** [ant-design/ant-design-pro#3387]
滚动条  

在主界面下滚动条直接显示的是原始的滚动条的样式,这个不是很美观 . 如下图   

![图片](https://lh3.googleusercontent.com/Ke8e8-cekJJxvfOF09BuWstrm3oOnOop8gpvxnTAJUlintBHq2Kgqk0GopO0gxJsnXlvsPxIy_0ser8NxC_Nm0HjZ4AdpIKNUPi1xI9WEXFVZjAA8CpTGaidch9DFHJpJclxCc-ygPeWNpdBfNbrqv0Y6WKN7_2vyJCoGuA03yS3akwIKBRYK_y-_vApbCQinohl4wh8U07XDT3PRAbe6Af0h4SALmUawd8B948puiT1Oxgwq0QR6xrYwe5a8GC5oYXTVduwmCJYK9Vtd_A-Ba0vrT5F_om7BqNH4lEn1f_y344yjmDZS1dBFzEADC_6ehyGaJXUsfgKaMEDy0Qw2wqsCp-fLXM7vG7uCeqrH7oAbiMtRwOcaQpLHkZnEMid-fJzsaht95AqSF5nfFMeQAknl9crDQ5VSX_ou-F-1qszz4IdwsF9PkXY4eh9c5VDCsB4O0fXG-oh9CPNK-y5BCMgdE-ZEMsO9Vkn2YP5dPmSAqk5doh8tRSogwEPFQ-UhghdgcnzGRTvAizmhnUtsI1SV4jwIJQx0cZgbzdhh6ozHSjNpbVu6CcC43LwAidxJ12tBCzggAwHsHnfjNeYr5IIgDHlddGGAXiMRHZ9xn1WNKyZ9owU0eAVlQeQm8h-0k5UL13jWfZ4g1-ADyNPamNO-tjCdWsOFYhnVlDBsEGhbbND6Bq7HiIrZEuuNPooisxtmFeenIER63TG=w1884-h943-no)

在滚动条进行滚动的时候,左边的菜单栏也跟着滚动了

期待结果: 

一. 滚动条的样式美化一下,修改为比较好看的样式,而不是默认样式
二. 在滚动条进行滚动的时候应该固定左边的菜单栏,不随着滚动右边的菜单栏

复现地址: https://preview.pro.ant.design/dashboard/analysis?fixedHeader=1

复现环境
 
1. 操作系统: Window10    
2. 浏览器 Google Chrome 版本 71.0.3578.98（正式版本） （64 位）  
3. Ant design pro 版本  2.1.1

**Comment by liweitao92** [comment]
![image](https://user-images.githubusercontent.com/30191996/51171671-7709f300-18ec-11e9-85e4-dce9e121b0d7.png)
