### ISSUE TITLE
开启base后，生成版本每次刷新URL中都会再加一次base

### ISSUE THREAD

**Issue by wsdqr001** [ant-design/ant-design-pro#3388]
因为业务需求，需要在生成环境开启base配置。但是每刷新一次网页，URL都会多一个base，从而导致404报错。举例：如果base设置为'/atlas'，则每次刷新/atlas/home页面，URL都会变成/atlas/atlas/home。

为了解决这个问题，按照官网配置，开启了hashHistory选项。history: 'hash',但是没有效果，刷新时路由仍然会自动变化。/atlas/#/ 会自动变成 /atlas/#/atlas/

@andriijas

**Comment by chenshuai2144** [comment]
试试让名字不要相等

**Comment by wsdqr001** [comment]
Done
