### ISSUE TITLE
与后台交互，不能发起api请求，不知道是不是更新的问题，还是代码的问题呢？

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design-pro#3391]
与后台交互，不能发起api请求，不知道是不是更新的问题，还是代码的问题呢？
![Uploading WTPD]0O[OL5IOS{[([U_$)G.png…]()
![xixh660ybo55qg5e je6 qv](https://user-images.githubusercontent.com/22407253/51223040-31483b80-197b-11e9-9759-fc25e71f54f7.png)
![f uv rt y iin1_87 1hs](https://user-images.githubusercontent.com/22407253/51223044-3311ff00-197b-11e9-918f-9154de7e9ece.png)
![f k37 s 1 iypavj 5](https://user-images.githubusercontent.com/22407253/51223045-34dbc280-197b-11e9-89df-111a9dcb79e5.png)

**Comment by shaopeng1** [comment]
问题描述太笼统了吧？你是怎么写的？症状呢？

**Comment by wangyuan0108** [comment]
我上传了图，就是 fetch请求没有拿到数据，也没有发起 network

**Comment by wangyuan0108** [comment]
@shaopeng1

**Comment by wangyuan0108** [comment]
不好意思，同事改的代码，改出问题了，已经解决，多谢了
