### ISSUE TITLE
关于`BasicLayout.js`中做页面鉴权的问题

### ISSUE THREAD

**Issue by cadleo** [ant-design/ant-design-pro#3396]
操作步骤如下：
1. 用admin账户登录，可以看到左侧菜单栏有（结果页）一级菜单，点击它可以看到它的二级菜单
2. 在`router.config.js`中的162行添加`authority: ['user'],`即，将（结果页）一级菜单隐藏，按照正常的逻辑，此时是不可以访问它的二级菜单所指向的页面的
3. 项目编译完成以后，（结果页）一级菜单确实被隐藏，但是如果在导航手动敲`/result/success`，我们可以进入该页面，而不是显示403

定位问题后发现，在文件`BasicLayout.js`中，查找权限相关代码如下（第99行开始），代码中没有子路由权限继承父路由的逻辑：
```js
  getRouterAuthority = (pathname, routeData) => {
    let routeAuthority = ['noAuthority'];
    const getAuthority = (key, routes) => {
      routes.forEach(route => {
        if (route.path && pathToRegexp(route.path).test(key)) {
          routeAuthority = route.authority;
        } else if (route.routes) {
          // 当前代码没有做相关继承
          routeAuthority = getAuthority(key, route.routes);
         // 个人进行了如下修改，需求可达成
         // const routesList = route.routes.map(i => {
         //   const item = { ...i };
         //   item.authority = item.authority || route.authority; 
         //   return item;
         // })
         // routeAuthority = getAuthority(key, routesList);
        }
        return route;
      });
      return routeAuthority;
    };
    return getAuthority(pathname, routeData);
  };
```
总结：在`router.config.js`中，如果只在一级菜单写了`authority`字段，那么二级菜单的权限配置依然是空的，具体的表现就是，左侧菜单栏不显示该一级菜单及从属于它的二级菜单，但是如果手动在导航输入url是可以访问二级菜单指向的页面的，不清楚这是feature还是bug，如果是feature，能否把这么设计的原因讲一下，拜谢，@chenshuai2144 代码貌似是大佬合的？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3072
