### ISSUE TITLE
2.2.0版本build之后在服务器运行报错

### ISSUE THREAD

**Issue by lilililee** [ant-design/ant-design-pro#3397]
![image](https://user-images.githubusercontent.com/24242242/51239059-4fca2900-19b3-11e9-8f85-64fd0aabd3e7.png)

直接在release中下载的2.2.0版本，未修改任何东西build后运行静态服务器,无法打开页面，请问大家有碰到这种情况吗？
操作系统：win10
浏览器： chrome69
node: 8.11.2

**Comment by pointshd** [comment]
me too

**Comment by lilililee** [comment]
找到原因了，开发环境有api接口，而build之后部署没有，接口报错造成json解析报错。
