### ISSUE TITLE
请问这个怎么解决

### ISSUE THREAD

**Issue by wangpeishihang** [ant-design/ant-design-pro#3398]
我是直接打包的项目，没有任何改动，放在我的服务器上，会报错
![image](https://user-images.githubusercontent.com/24558232/51239862-738e6e80-19b5-11e9-9fe4-aa5bdad10f6e.png)

**Comment by ch-liuzhide** [comment]
我刚也去部署了一下，将proxy注释去掉直接部署，结果和你一样。

**Comment by wangpeishihang** [comment]
> 我刚也去部署了一下，将proxy注释去掉直接部署，结果和你一样。

你现在解决了吗，解决了分享一下

**Comment by chenshuai2144** [comment]
这个是因为我们引入了一个新的接口，你们需要增加一个这个接口

**Comment by wangpeishihang** [comment]
> 这个是因为我们引入了一个新的接口，你们需要增加一个这个接口

哪个接口，能详细一点吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/3402
