### ISSUE TITLE
默认支持了懒加载，如何支持服务端渲染 SSR 呢

### ISSUE THREAD

**Issue by shengxinjing** [ant-design/ant-design-pro#340]
RT，如何支持服务端渲染 SSR 呢

**Comment by chenshuai2144** [comment]
理论上说  后台界面是不希望被搜索引擎爬到的.

**Comment by shengxinjing** [comment]
@chenshuai2144 也不一定局限于后台界面吧，比如我觉得 antd-pro 做博客系统挺好的啊

**Comment by shengxinjing** [comment]
@chenshuai2144 如果做博客的话 还是挺希望被搜索引擎爬吧

**Comment by afc163** [comment]
目前主要面向前后端分离的中后台项目，暂时不会尝试 ssr 方案。
