### ISSUE TITLE
Primay Color change is not reflecting when build 

### ISSUE THREAD

**Issue by saqueib** [ant-design/ant-design-pro#3401]
I am using version `2.1.0` and everything working great, I tried to change the primary color for theme so I updated the `config/config.js` with 

```js
 theme: {
    'primary-color': '#E00000',
  },
```

now when I run `npm start` I can see the newly defined color. 

Now when I run `npm run build` to generate dist folder which I can upload for production I am getting default **blue** color, my custom color is not being used. 

I also update color info in `src/defaultSettings.js` but still same issue

```
primaryColor: '#E00000', // primary color of ant design
```

please help

**Comment by chenshuai2144** [comment]
remove this file https://github.com/ant-design/ant-design-pro/blob/master/config/plugin.config.js

**Comment by saqueib** [comment]
@chenshuai2144 Thanks for quick response

once deleted I am getting an error on `npm run build`

```
> umi build

{ Error: Cannot find module './plugin.config'
```

**Comment by chenshuai2144** [comment]
also remove https://github.com/ant-design/ant-design-pro/blob/acd67d21e7a5cd85d81ff5bfae102027ee402236/config/config.js#L4

**Comment by saqueib** [comment]
Great 👍 finally got it working. Here are steps I took

1. Deleted `config/plugin.config.js`
2. Updated `config/config.js`
```
// remove it
// import webpackPlugin from './plugin.config';
...
// remove it
// chainWebpack: webpackPlugin,
```

thanks @chenshuai2144
