### ISSUE TITLE
cutomize menuData from server.

### ISSUE THREAD

**Issue by epochchaser** [ant-design/ant-design-pro#3403]
Hi. i am currently using antd-pro.
There is menuData generated from router.config.js now.
but i want to fetch menuData from my server and parse it.

but i cannot find example like that.
thank you!

**Comment by pangafu** [comment]
After some try, maybe author's solution is :

edit  mock/route.js

export default {
  '/api/auth_routes': {
-    '/form/advanced-form': { authority: ['admin', 'user'] },
+    '/form/advanced-form': { authority: ['admin'] },
  },
};

You can see the menu of user and admin changed.

**Comment by epochchaser** [comment]
Thanks for reply.
But there is no way if i dont use route file?
I want to control in code behind.

Thank you:)

2019년 1월 17일 (목) 오후 12:55에 pangafu <notifications@github.com>님이 작성:

**Comment by pangafu** [comment]
But if I need more dyminac menu, the solution is not OK.

For example, I make a dashboard in server, and use 
```
/dashboard?id=1  -> dashboard1
/dashboard?id=2  -> dashboard2
/dashboard?id=3  -> dashboard3
```

So the menu I need is : 
```
+dashboard
   |-dashboard1
   |-dashboard2
   |-dashboard3
```

And when I made dashboard4 for user, the dashboard menu append a dashboard4 menu node, How to handle it in current antd-pro framework?

**Comment by pangafu** [comment]
And I found the /api/auth_routes is load before login, the mean we can't make different menu/route for different user, all user should get full menu/route patch?

**Comment by epochchaser** [comment]
i just solve it by fetching from server and pre-manipulate inside route.config.js file.

**Comment by pangafu** [comment]
@epochchaser do you solved different menu for different user(same usergroup)

**Comment by epochchaser** [comment]
> @epochchaser do you solved different menu for different user(same usergr

i just hardcoded menu list in the route.config.js file.
and put authority from server.

but it's not perfect solution ...huh.
is there other ways to set route.config.js file before loading it?

**Comment by jhimanjhi** [comment]
Hi @epochchaser , I'm having similar problem and couldn't find a solution or example on internet until I found this thread. So may I know if you have already found a solution for this (the fetching of full menu data from server)? or you still hardcoded all of the routes on the config file? Btw, I'm using UmiJs for the configuration.
