### ISSUE TITLE
关于路由重定向V2

### ISSUE THREAD

**Issue by 15531400827** [ant-design/ant-design-pro#3405]
不同权限的用户登陆后主页也可能不一样， 比如
admin  =>  '/user/main'
user => '/dashboard/analysis'
我在router.config.js中配置只能写一个  { path: '/', redirect:  '/dashboard/analysis' }
如何在不同用户登录的时候redirect是其对应的地址呢

**Comment by chenshuai2144** [comment]
你可以让每个人都跳到一个空页面，然后在空页面里面通过 js 来控制他们跳转到哪里

**Comment by 15531400827** [comment]
@chenshuai2144 谢谢， 不过这样做感觉有点low。。。
