### ISSUE TITLE
v2权限问题

### ISSUE THREAD

**Issue by yuzexing** [ant-design/ant-design-pro#3411]
使用user权限的账号登录pro，/profile/advanced页面是无法看到并访问的，但是可以看到并访问/form/advanced-form，这两个页面的权限配置都是authority: ['admin']，为什么表现不同呢?
https://github.com/ant-design/ant-design-pro/blob/master/config/router.config.js#L85
https://github.com/ant-design/ant-design-pro/blob/master/config/router.config.js#L153

**Comment by pangafu** [comment]
系统在登录时，访问了/api/auth_routes，给路由打了patch... (我觉得这个方案很差。。。)

mock/route.js

export default {
  '/api/auth_routes': {
    '/form/advanced-form': { authority: ['admin', 'user'] }
  },
};

**Comment by yuzexing** [comment]
> 系统在登录时，访问了/api/auth_routes，给路由打了patch... (我觉得这个方案很差。。。)
> 
> mock/route.js
> 
> export default {
> '/api/auth_routes': {
> '/form/advanced-form': { authority: ['admin', 'user'] }
> },
> };

原来如此...谢了
