### ISSUE TITLE
打包发布后，请求mock接口404

### ISSUE THREAD

**Issue by WEIZE97** [ant-design/ant-design-pro#3413]

**Comment by shaopeng1** [comment]
mock数据线上貌似不打包进去的

**Comment by WEIZE97** [comment]
![image](https://user-images.githubusercontent.com/45985188/51305175-1f4ac380-1a75-11e9-8c25-2691271183e8.png)
那么，现在的静态页面无法发布至网上吗？

**Comment by shaopeng1** [comment]
mock 数据只是给调试用的，生产环境你需要真实的 API 才能跑得起来

**Comment by WEIZE97** [comment]
好的
