### ISSUE TITLE
设置为动态菜单后model会报错：Reducer "model" returned undefined during initialization. （已解决，close）

### ISSUE THREAD

**Issue by hana333** [ant-design/ant-design-pro#3414]
router.config.js不设置默认routes的话动态菜单可以渲染成功，对应component则不显示；router.config.js设置了默认routes刷新的时候会报错：Reducer "model" returned undefined during initialization. 

![24](https://user-images.githubusercontent.com/26453488/51304807-160d2700-1a74-11e9-8b5e-eebd54a2eeb5.png)

**Comment by pangafu** [comment]
如何设置为动态菜单？

**Comment by chenshuai2144** [comment]
解决方案 show 一下？

**Comment by doterme** [comment]
@hana333 分享一下呗？

**Comment by yangdachu** [comment]
@hana333 请问下怎么解决的？能分享一下吗
