### ISSUE TITLE
打开官网报错-BizCharts is not defined

### ISSUE THREAD

**Issue by cjmafei** [ant-design/ant-design-pro#3420]
如题

**Comment by yutingzhao1991** [comment]
![image](https://user-images.githubusercontent.com/1061968/51361999-cf1f4000-1b0c-11e9-9d29-c66ed5bcc574.png)

我这里是好的

**Comment by cjmafei** [comment]
> ![image](https://user-images.githubusercontent.com/1061968/51361999-cf1f4000-1b0c-11e9-9d29-c66ed5bcc574.png)
> 
> 我这里是好的

https://pro.ant.design/index-cn 试试这个地址

**Comment by cjmafei** [comment]
@yutingzhao1991 这个问题会修复吗。现在还是报错，文档看不了

**Comment by chenshuai2144** [comment]
你的网路是不是连不上
`https://cdn.jsdelivr.net/`

**Comment by cjmafei** [comment]
@chenshuai2144 是的

**Comment by cjmafei** [comment]
现在好了

**Comment by chenshuai2144** [comment]
我换了一下 cdn。换成了阿里的，虽然感觉不应该这样做

**Comment by cjmafei** [comment]
周末在家的时候也是打不开报这个错。我也不清楚是因为什么。

**Comment by chenshuai2144** [comment]
因为 cdn 在 npm 上面，你的网络可能上不了 npm

**Comment by cjmafei** [comment]
我怎么查看能不能上npm呢

**Comment by chenshuai2144** [comment]
https://www.jsdelivr.com/

**Comment by zhouguanglong** [comment]
官网访问不报错，为什么自己引用就报错呢？
ReferenceError: BizCharts is not defined
bizcharts
external "BizCharts":1
