### ISSUE TITLE
common/router 下面的路由中 name 怎么动态变化？

### ISSUE THREAD

**Issue by zhouguanglong** [ant-design/ant-design-pro#3422]
//  6~9：补汇转余额、负数应收转余额、补汇退款、负数应收退款
    '/income/business/detail1': {
		  component: dynamicWrapper(app, [], () => import('../routes/Income/Business/Detail1')),
		  name:''
		},
项目中common/router里面这里的name 怎么 根据 不同的值（6~9） 来显示不同呢？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L116

**Comment by chenshuai2144** [comment]
这个可能需要自定义面包屑的 props 了
