### ISSUE TITLE
npm run build  ant design pro报错

### ISSUE THREAD

**Issue by LiboliboLibolibo** [ant-design/ant-design-pro#3427]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.1.1 build: `umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by LiboliboLibolibo** [comment]
本地build可以推到远端别人clone就是这样，我自己再clone到另一个目录下build也报这个，本以为是代码问题，新建一个仓库把代码push进去再当下来build还是报这个错

**Comment by chenshuai2144** [comment]
详细一点？上面得不到任何信息

**Comment by MinTate** [comment]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.2.0
3 info using node@v10.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.1.1~prebuild: ant-design-pro@2.1.1
6 info lifecycle ant-design-pro@2.1.1~build: ant-design-pro@2.1.1
7 verbose lifecycle ant-design-pro@2.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.1.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/min/Desktop/workspace/nodejs/resourceplus/node_modules/.bin:/Users/min/Library/Android/sdk/ndk-bundle:/Users/min/Library/Android/sdk/tools:/Users/min/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle ant-design-pro@2.1.1~build: CWD: /Users/min/Desktop/workspace/nodejs/resourceplus
10 silly lifecycle ant-design-pro@2.1.1~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.1.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.1.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.1.1 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid ant-design-pro@2.1.1
15 verbose cwd /Users/min/Desktop/workspace/nodejs/resourceplus
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.7.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.1.1 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

我也遇到相同的问题，这是详细的Log，感谢～

**Comment by afc163** [comment]
https://segmentfault.com/markdown#articleHeader1

**Comment by MinTate** [comment]
```shell
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.2.0
3 info using node@v10.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.1.1~prebuild: ant-design-pro@2.1.1
6 info lifecycle ant-design-pro@2.1.1~build: ant-design-pro@2.1.1
7 verbose lifecycle ant-design-pro@2.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.1.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/min/Desktop/workspace/nodejs/resourceplus/node_modules/.bin:/Users/min/Library/Android/sdk/ndk-bundle:/Users/min/Library/Android/sdk/tools:/Users/min/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle ant-design-pro@2.1.1~build: CWD: /Users/min/Desktop/workspace/nodejs/resourceplus
10 silly lifecycle ant-design-pro@2.1.1~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.1.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.1.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.1.1 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid ant-design-pro@2.1.1
15 verbose cwd /Users/min/Desktop/workspace/nodejs/resourceplus
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/Cellar/node/10.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.7.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.1.1 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Sorry, 我的错，没有提前预览～

**Comment by Agagy** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v11.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.2.1~prebuild: ant-design-pro@2.2.1
6 info lifecycle ant-design-pro@2.2.1~build: ant-design-pro@2.2.1
7 verbose lifecycle ant-design-pro@2.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.2.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/agagy/Projects/mtk_cloud_ initial/node_modules/.bin:/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/Users/agagy/.npm-global/bin
9 verbose lifecycle ant-design-pro@2.2.1~build: CWD: /Users/agagy/Projects/mtk_cloud_ initial
10 silly lifecycle ant-design-pro@2.2.1~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.2.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.2.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.2.1 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid ant-design-pro@2.2.1
15 verbose cwd /Users/agagy/Projects/mtk_cloud_ initial
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v11.2.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.2.1 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
@chenshuai2144 大佬，这个哪里能看到解决办法啊？

**Comment by abserari** [comment]
确实，这个解决方法是什么？

**Comment by chenshuai2144** [comment]
看起来是node 版本的问题，升级一下 node 的版本把

**Comment by abserari** [comment]
> 看起来是node 版本的问题，升级一下 node 的版本把

多谢, 我尝试了很多 node 版本, 都不行.

最后把现有的程序逐步搬到 antd 2.2 的官方模板下才编译成功的. 一点一点移动 pages 里面的东西, 应该是某一个组件或者页面不兼容了.

https://github.com/ant-design/ant-design-pro/releases/tag/2.2.0 链接留在这里, 不过时间支持的话还是尽量换成现在的 v4, v5 版本吧.

**Comment by xiaocaimeng007** [comment]
npm err! ant-design-pro@5.1.0 build: `umi build`
