### ISSUE TITLE
想问一下2.0版本对node的版本要求？

### ISSUE THREAD

**Issue by xiangmeng** [ant-design/ant-design-pro#3428]
目前2.0需要的node.js版本是什么？比如，哪些版本可以运行，哪些版本不支持。

**Comment by chenshuai2144** [comment]
正式版本就可以
https://github.com/ant-design/ant-design-pro/blob/da173d6092791b2957646da960ca2a014c17ac67/scripts/lint-prettier.js#L44
但是这行代码需要 node11
