### ISSUE TITLE
在处理不支持手机浏览器X5内核，新增了BUG

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#3437]
### 手机浏览器X5内核
- npm install --save intl @babel/polyfill
- src 下新增  global.js
   - import '@babel/polyfill';
   - global.Intl = require('intl'); 
   - window.Intl = require('intl');

### 新增BUG(浏览器 谷歌41)
- Uncaught TypeError: Cannot assign to read only property 'Intl' of [object global]

**Comment by yemaozi5518** [comment]
能不能在global.js 加上校验，是手机端在加  global.Intl = require('intl');window.Intl = require('intl');
求大神指导

**Comment by chenshuai2144** [comment]
如果需要，建议你在 ejs 中直接引入。

**Comment by yutingzhao1991** [comment]
是用了 umi-plugin-react/locale 吗？国家化插件会自动做 polyfill 的引入的，https://github.com/umijs/umi/blob/master/packages/umi-plugin-locale/src/index.js#L72 这里有一个列表，配置下 targets 即可，如果没有包含对应的浏览器，可以提 PR 加上缺少的即可。

**Comment by yemaozi5518** [comment]
![image](https://user-images.githubusercontent.com/30460433/51449799-ab583600-1d68-11e9-9f5f-a383b27b1d87.png)
是这里吗？  @chenshuai2144

**Comment by yemaozi5518** [comment]
感谢！很好的解决方案。我不知道怎么提PR，我的问题也不知道是不是出现的概率大。 @yutingzhao1991

**Comment by yemaozi5518** [comment]
###  解决方案
 - 首先我确认我使用的antdp的版本是可以使用 谷歌41访问的
 - 解决华为手机浏览器X5内核才引起的BUG
参考文档 --https://blog.csdn.net/Jason_WangYing/article/details/70739736

![image](https://user-images.githubusercontent.com/30460433/51451512-a5665300-1d70-11e9-949b-eb294cfaa95d.png)
