### ISSUE TITLE
如何升级最新版本

### ISSUE THREAD

**Issue by linhanyang** [ant-design/ant-design-pro#344]
请问如何升级版本？？？

**Comment by chenshuai2144** [comment]
什么升级?
ant-design-pro 最近是没有新版本的.
要是追求最新的 
可以clone master分支

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0-Ant-Design-Pro%EF%BC%9F
