### ISSUE TITLE
打开某个路由页面，浏览器刷新地址后，侧边栏收起了，是哪里配置的不对吗

### ISSUE THREAD

**Issue by ximanWang** [ant-design/ant-design-pro#3441]
点击左侧菜单某个子项目，http://localhost:8000/?id=123#/basic/info ，刷新这个地址后，左侧菜单收起了

**Comment by Bubbleinpit** [comment]
完整的复现过程？个人猜测你的页面宽度比较小，所以一开始侧边栏就是折叠状态，然后你手动点开，然后点击子项路由跳转，然后你再刷新，侧边栏当然又会自动收起。你要么把浏览器页面宽度拉长，要么配置一下媒体查询里定义的侧边栏收起对应的宽度（应该是再BasicLayout中调整）。

**Comment by zhang0ZGC** [comment]
你是不是说目录的子菜单被折叠呀？
确实是有这个情况，ant pro也是的，我看在BaseMenu里面有个openKeys的prop应该是控制它的，正常点击比如/list/basic-list时，openKeys就是:`["/","/list","/list-basic-list"]`，一旦刷新页面，openKeys打印出来只剩下`["/"]`了

**Comment by ximanWang** [comment]
> 你是不是说目录的子菜单被折叠呀？
> 确实是有这个情况，ant pro也是的，我看在BaseMenu里面有个openKeys的prop应该是控制它的，正常点击比如/list/basic-list时，openKeys就是:`["/","/list","/list-basic-list"]`，一旦刷新页面，openKeys打印出来只剩下`["/"]`了
> 这个openKeys跟`flatMenuKeys`有关系，第一次flatMenuKeys是空的。。

是的，刷新页面的时候子菜单折叠了

**Comment by ximanWang** [comment]
> > > 你是不是说目录的子菜单被折叠呀？
> > > 确实是有这个情况，ant pro也是的，我看在BaseMenu里面有个openKeys的prop应该是控制它的，正常点击比如/list/basic-list时，openKeys就是:`["/","/list","/list-basic-list"]`，一旦刷新页面，openKeys打印出来只剩下`["/"]`了
> > > 这个openKeys跟`flatMenuKeys`有关系，第一次flatMenuKeys是空的。。
> > 
> > 
> > 是的，刷新页面的时候子菜单折叠了
> 
> 正好今天我也遇见了:)，我用的V2版本，刚刚研究了一下，在src/components/SiderMenu/SiderMenu.js文件的getDerivedStateFromProps方法:
> 
> ```js
> static getDerivedStateFromProps(props, state) {
>     const { pathname } = state;
>     if (props.location.pathname !== pathname) {
>       return {
>         pathname: props.location.pathname,
>         openKeys: getDefaultCollapsedSubMenus(props),
>       };
>     }
>     return null;
>   }
> ```
> 
> 第一次的时候props.flatMenuKeys值其实是空的，openKeys结果会有一个["/"]，但是这个时候pathname已经被设置到state了，等到props.flatMenuKeys有值的时候，
> 
> ```js
> props.location.pathname !== pathname
> ```
> 
> 这个条件已经不满足了，所以不会去更新openKeys了。
> 
> (有问题。。删了吧。。)
> ![tim 20190128142400](https://user-images.githubusercontent.com/10346399/51818071-699b3280-2308-11e9-96f3-21cd9f54cc20.gif)

👍定位的很准确，我之前没有仔细看他的实现，感谢
