### ISSUE TITLE
Upload aliyun oss server signature direct transmission

### ISSUE THREAD

**Issue by qqqqqqq1995** [ant-design/ant-design-pro#3445]
Upload, I want to implement Aliyun oss server signature direct transmission, how can I do it, that is, how do I get the data from the server and add it to the submission parameters before uploading?

**Comment by chenshuai2144** [comment]
I don't know what you want to do, it sounds like a simple ajax request.

**Comment by qqqqqqq1995** [comment]
Thank you, I implemented the upload myself in the upladBefrore method.
