### ISSUE TITLE
如何解决Form表单提交以后 getFieldDecorator 的initialValue失效的问题?

### ISSUE THREAD

**Issue by rellyCheng** [ant-design/ant-design-pro#3446]
![image](https://user-images.githubusercontent.com/22974879/51517656-68748c00-1e56-11e9-91d5-15dbe8289256.png)
initialValue是个动态的值,当我提交表单以后,再次触发this.state.areaCode改变时,initialValue还是提交表单以前的值永远不会改变了
![image](https://user-images.githubusercontent.com/22974879/51517759-d4ef8b00-1e56-11e9-9fa8-069f5c378171.png)
当我zhu注释了getFieldDecorator这一块之后,  触发this.state.areaCode改变时,就能如我所愿可以随意改变了.找到了原因但是不知道怎么来解决.特地来寻求大佬的帮助,谢谢

**Comment by linyongping** [comment]
你用错了， 被```getFieldDecorator```包装过的组件value会被form接管。，你要动态修改被```getFieldDecorator``` 包装过的组件value 使用form.setFieldsValue。
