### ISSUE TITLE
pro v2动态menu有一个bug该如何解决呢？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#3452]
### 情景描述
就是需要根据不同的人显示不同的menu，所以现在是从服务端获取menu的json信息。

### 问题描述
因为umi是自动生成的menu或者需要手动配置的，所以不包含在从服务端返回的menu，也是能访问的。

### 例子
比如总共有A、B、C三个menu，用户张三只能访问A,但是由于在config.js中已经配置了所有的路由，虽然menu中不显示B、C，但是通过连接地址还是可以访问的（已验证）。

### 尝试方法
虽然可以添加`authority`可以解决，但是`authority`在浏览器的localstorage中是可以修改的。

**Comment by a854363956** [comment]
理论上,好像只能修改路由,动态注册路由才能达到你的效果,可是路由似乎也可以在前段进行修改.
1. 如果是为了网站安全建议不采用在前段控制权限,而是在后端进行请求的URL进行权限验证
2. 前段只是屏蔽对应的没有权限的页面 (PS:即使进入了页面也因为没有权限所以无法访问后台方法)

> PS: 不要相信前端的任何操作,总结在authority里面设置就行了

**Comment by codepandy** [comment]
@sorrycc 能帮忙给个方案吗？

**Comment by chenshuai2144** [comment]
这个是无解的，前端就是这样的。
最好的最稳妥的办法，就是在后端直接限制接口的权限，即使进去了也什么都无法操作

**Comment by sorrycc** [comment]
权限的控制肯定得在后端，权限路由是正确的解法。

**Comment by sorrycc** [comment]
权限的控制肯定得在后端，权限路由是正确的解法。

**Comment by codepandy** [comment]
@sorrycc 嗯，是放在后端，但现在想做的是服务端返回什么menu，就能操作那些menu，不返回的即使在浏览器中直接输入链接，也不会路由过去。
由于umi的路由是提前配置好的，虽然有的服务端没有返回，在页面上看不到，但是通过输入url地址还是能访问到的。
至于umi上说的权限路由，没看明白，在路由中加了Routes，编译都通不过。

现在从服务端拿来的只是`菜单`，如何让路由也根据服务端返回的数据来生成？

**Comment by codepandy** [comment]
@chenshuai2144 这个我觉的是umi的问题，并不是无解的，ant design pro之前的版本就可以，没用umi之前，路由是可以根据服务端返回的来生成的。

**Comment by ybning** [comment]
权限的控制得在后端，这个是没错，同时也想做成后端返回用户看的到的menu。

@chenshuai2144

**Comment by ybning** [comment]
> 同时也像v1一样支持后端返回menu生成菜单。

好像v2，v4舍去了
