### ISSUE TITLE
 ie11请求缓存

### ISSUE THREAD

**Issue by painoBoy** [ant-design/ant-design-pro#3453]
ie11下token验证失效后跳转到登录页，登录成功后验证还是失效，发现是ie是从缓存里拿的数据， 已经注释掉request.js里  .then(response => cachedSave(response, hashcode,newOptions))了 
![qq 20190123012250](https://user-images.githubusercontent.com/22983379/51553303-79042100-1ead-11e9-8154-f499d23b9939.jpg)

![qq 20190123012202](https://user-images.githubusercontent.com/22983379/51553294-6ee22280-1ead-11e9-9cd3-2053b164930a.png)
还是有这种问题

**Comment by painoBoy** [comment]
现在我是加了时间戳来解决的

**Comment by chenshuai2144** [comment]
把请求改成 post
