### ISSUE TITLE
关于左侧菜单栏 小屏幕显示关闭按钮

### ISSUE THREAD

**Issue by EssenRoc** [ant-design/ant-design-pro#3457]
![image](https://user-images.githubusercontent.com/12685126/51585706-5f96bf80-1f15-11e9-99b0-f38b24312b24.png)

感觉很不自然，这是否是预期结果？

**Comment by imhele** [comment]
或许线上版本需要升级一下 antd ，这个问题已经在 antd@3.12.2 修复

**Comment by EssenRoc** [comment]
了解
