### ISSUE TITLE
eslint 报错 Cannot read property 'recommended' of undefined

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#3458]
Pro version: `2.1.1`

eslint version: `v4.19.1`

使用 eslint 报错：

`TypeError: Cannot read property 'recommended' of undefined`

重新安装了  eslint-plugin-compat 没有解决问题

**Comment by zhai** [comment]
我也碰到了这问题，之前没问题，可能是什么升级了导致的

**Comment by chenshuai2144** [comment]
有可能是个全局的 eslint 的冲突了。
试着全部删除试试

**Comment by zhai** [comment]
找到原因了，
我从当前的组件 connect到当前文件夹下的models/model.js 是可以找到变量 的，但是connect到其他的文件夹下面的 othermodels/other.js 就找不到定义在other.js中的变量

是不支持跨文件夹 connect 吗？ 新手

@connect(({model, loading}) => ({
  model,
  loading: loading.models.model,
}))  这样可以

@connect(({other, loading}) => ({
  other,
  loading: loading.models.other,
}))  这样不可以

**Comment by zhangjie2012** [comment]
应该不是同一个问题。
