### ISSUE TITLE
项目打包之后，无法运行，报错，开发环境正常

### ISSUE THREAD

**Issue by chenguzhen87** [ant-design/ant-design-pro#3459]
![image](https://user-images.githubusercontent.com/28331609/51601463-620e0f00-1f3f-11e9-974e-d4007367c63e.png)

**Comment by chenshuai2144** [comment]
尝试升级一下 umi，或者清空一下 localStorage

**Comment by chenguzhen87** [comment]
尝试删除依赖，重新装依赖，然后清除浏览器缓存，可以解决这个问题
