### ISSUE TITLE
项目打包更新过后、访问页面、感觉页面被缓存了，换个浏览器访问就是最新的。

### ISSUE THREAD

**Issue by sir-ran** [ant-design/ant-design-pro#3460]
1、请问下、、这个是、怎么回事啊？各种ctrl+f5 都不行、、第二天来访问、莫名就行了。
2、请问下、、项目打包过后
![image](https://user-images.githubusercontent.com/26730748/51602546-36d8ef00-1f42-11e9-9887-62eb2e2b1e2f.png) 出现的这个workbox...这个文件夹是正常的嘛？

**Comment by sir-ran** [comment]
缓存这个，，已经解决了、、清楚一下浏览器数据就可以了。。。但是不晓得为什么、强制刷新都不行

**Comment by zhangyanan0525** [comment]
我现在也有同样的问题：项目打包更新过后，访问页面，页面被缓存了。总不能每次让用户去清除浏览器数据吧。请大佬指点
