### ISSUE TITLE
手机模式下，固定侧边栏，收起时有阴影

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design-pro#3463]
手机模式下，固定侧边栏，收起时有阴影
![_20190124135305](https://user-images.githubusercontent.com/9401913/51657333-70136c80-1fdf-11e9-9f33-a0cde955e16e.png)

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/ant-design-pro/commit/189c5882c30dd8388f3a581dc010c3e3cd18eecf
