### ISSUE TITLE
点击父级路由实现跳转

### ISSUE THREAD

**Issue by painoBoy** [ant-design/ant-design-pro#3465]
![tim 20190124164301](https://user-images.githubusercontent.com/22983379/51665652-3babaa80-1ff7-11e9-8c08-28ccc1476fc2.png) 可以点击父级路由实现跳转么？在父级路由里添加了组件就报错了

**Comment by chenshuai2144** [comment]
没有听懂你想表达什么

**Comment by doterme** [comment]
@chenshuai2144 他的意思是父菜单可以点击，现在ant design pro的父菜单是不能点击的。

**Comment by chenshuai2144** [comment]
我们暂时不会支持这种方式的，不符合菜单的标准定义。
