### ISSUE TITLE
pwacompat.min.js:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#3466]
当需要将项目部署到非根目录时，在config.js增加如下配置
history: 'hash',
  base: '/nScreen',
  publicPath: '/nScreen/',
  outputPath: './nScreen',

执行npm start
在浏览器控制台报错
pwacompat.min.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by ffalconjs** [comment]
pwacompat.min.js 这个文件antd pro原工程生成的 不修改部署路径是能够正常生成一段js，修改部署路径后才会出错。

**Comment by chenshuai2144** [comment]
看来是 pwa 生成的。参照
https://github.com/ant-design/ant-design-pro/pull/3508 关掉 pwa 好了

**Comment by ffalconjs** [comment]
关掉还是会生成pwa相关文件，自动生成的html文件中，还是引入了pwa
pwa: false,

**Comment by mathcw** [comment]
pwa:false 依然存在本问题

**Comment by jing-wu** [comment]
经测试，pwa:false确实还是存在这个问题

**Comment by kuhami** [comment]
我把 pwa设置成false，问题已解决！

**Comment by kuhami** [comment]
> 当需要将项目部署到非根目录时，在config.js增加如下配置
> history: 'hash',
> base: '/nScreen',
> publicPath: '/nScreen/',
> outputPath: './nScreen',
> 
> 执行npm start
> 在浏览器控制台报错
> pwacompat.min.js:1 Uncaught SyntaxError: Unexpected token <

#jing-wu 你把 publicPath: '/nScreen/', 删掉就ok了

**Comment by boyongjiong** [comment]
@jing-wu @ffalconjs @mathcw 
我这边 ant-design-pro 版本为：2.2.1
将 defaultSettings.js 中 pwa 设置为 false 之后不起作用的原因是 config.js 文件中配置 pwa 的代码为如下
```
pwa: pwa
        ? {
            workboxPluginMode: 'InjectManifest',
            workboxOptions: {
              importWorkboxFrom: 'local',
            },
          }
        : {},
```
修改为：
```
pwa: pwa
        ? {
            workboxPluginMode: 'InjectManifest',
            workboxOptions: {
              importWorkboxFrom: 'local',
            },
          }
        : false,
```
即三目运算后面的配置为 false 而不是 空对象
