### ISSUE TITLE
IE11 Blank Page and “umi” Undefined Error

### ISSUE THREAD

**Issue by eucheeyuen** [ant-design/ant-design-pro#3468]
I already git clone the code ,npm install ,npm start...

This is my npm start info：

$ npm start
> ant-design-pro@2.2.1 start /Users/myname/projects/ant-design-pro
> cross-env APP_TYPE=site umi dev

[umi-plugin-dll] File list is equal, don't generate the dll file.
(node:2458) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Starting the development server...

✔ Webpack
  Compiled successfully in 21.92s

Theme generated successfully
 DONE  Compiled successfully in 22517ms                                                                                        10:16:33

  App running at:
  - Local:   http://localhost:8000/ (copied to clipboard)

But  I used IE11(win10 1809) accessed this address  then got a blank page

F12 debugging，I got some error message：

SCRIPT1053: Must be initialized Const
umi.dll.js (89306,16)
SCRIPT5009: “umi” Undefined
umi.js (34926,1)

How can I solve this problem, thanks！

**Comment by chenshuai2144** [comment]
开发环境好像是不支持 ie11的，编译完之后才可以。
@sorrycc

**Comment by xiaohuoni** [comment]
就是这么设计的。
