### ISSUE TITLE
The Search List style is wrong

### ISSUE THREAD

**Issue by blackboy1987** [ant-design/ant-design-pro#3469]
![1234](https://user-images.githubusercontent.com/6405701/51722701-4024a180-2091-11e9-920f-3e86598393e1.png)

**Comment by soolaugust** [comment]
The newest codes shows as normal.

![image](https://user-images.githubusercontent.com/10558124/51894120-dd5d3e00-23e1-11e9-9938-a3412feec7a2.png)

maybe official website didn't use newest codes. please check it. @chenshuai2144

**Comment by chenshuai2144** [comment]
I deployed a new official website, caused by antd
