### ISSUE TITLE
DescriptionList 能否由开发者完全控制col属性

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design-pro#3474]
![image](https://user-images.githubusercontent.com/23520283/51782312-34a0ab80-2161-11e9-86ef-5d2ee5b844e0.png)

是否提供一个属性由开发者完全控制`col`，因为可能有类似下图的使用场景

![image](https://user-images.githubusercontent.com/23520283/51782334-7b8ea100-2161-11e9-82eb-09fcaae0a62a.png)
此时因为响应式就会有样式问题
![image](https://user-images.githubusercontent.com/23520283/51782359-d9bb8400-2161-11e9-9143-13f1896f7cb9.png)

**Comment by imhele** [comment]
可以试着为 Description 组件设置 `restProps` 来覆盖默认的 Col 组件 `props`

**Comment by Liu-Ya** [comment]
> 可以直接在 Description 组件添加 Col 组件的属性来覆盖默认值

`Description`本身是一个`Col`，这样的话就需要
```jsx
<Description term="客户姓名" xs={24} sm={24}>
    {client && client.name}
</Description>
```
感觉这样并不太好，代码会比较繁琐

**Comment by imhele** [comment]
> > 可以直接在 Description 组件添加 Col 组件的属性来覆盖默认值
> 
> `Description`本身是一个`Col`，这样的话就需要
> 
> ```js-jsx
> <Description term="客户姓名" xs={24} sm={24}>
>     {client && client.name}
> </Description>
> ```
> 
> 感觉这样并不太好，而且代码会比较繁琐

你希望怎样使用呢？

**Comment by Liu-Ya** [comment]
> > > 可以直接在 Description 组件添加 Col 组件的属性来覆盖默认值
> > 
> > 
> > `Description`本身是一个`Col`，这样的话就需要
> > ```
> > <Description term="客户姓名" xs={24} sm={24}>
> >     {client && client.name}
> > </Description>
> > ```
> > 感觉这样并不太好，而且代码会比较繁琐
> 
> 你希望怎样使用呢？想一次性为 DescriptionList 下的 Description 都添加上共同的属性吗？

```jsx
<DescriptionList size="small" col={width > 1200 ? 2 : 1} custom={true} >
  <Description term="客户姓名">{client && client.name}</Description>
  <Description term="客户号码">{client && client.phone}</Description>
  <Description term="客户来源">{client && client.source}</Description>
  <Description term="客户标签">{client && client.tag}</Description>
  <Description term="邮箱地址">{client && client.email}</Description>
  <Description term="微信">{client && client.wechat}</Description>
</DescriptionList>
```
类似这样？只是觉得通用的规则应该体现在父级元素上，只需要为特殊项单独配置，而不是每一项都配置该属性

**Comment by imhele** [comment]
)你想要修改的属性应该在 [这里](https://github.com/ant-design/ant-design-pro/blob/master/src/components/DescriptionList/responsive.js)
把文件修改为这样
```js
const responsive = {
  1: { xs: 24 },
  2: { xs: 24, sm: 12 },
  3: { xs: 24, sm: 12, md: 8 },
  4: { xs: 24, sm: 12, md: 6 },
};
export const getResponsive = () => responsive;
export const setResponsive = (value, index) => {
  responsive[index] = {
    ...responsive[index],
    ...value,
  };
};
export default responsive;
```
然后在 index.js 加一句
```js
export { getResponsive, setResponsive } from './responsive';
```
在你刚刚的场景下调用 `setResponsive`
```js
setResponsive({ xs: 24, sm: 24, xl: 12 }, 2);
```
应该可以实现你的需求

**Comment by chenshuai2144** [comment]
DescriptionList 最后会放到 antd 中，这里暂时不会支持的
