### ISSUE TITLE
dva中state数据变少一条，页面table中的数据没变化是为什么

### ISSUE THREAD

**Issue by superwuman** [ant-design/ant-design-pro#3475]
reducers:{
    save(state, action) {
      console.log(action.payload);
      return {
        ...action.payload
      };
    },
  }
这里打日志数据已经变了，可是页面table中的数据还是没变化，这是为什么

deleteStep = (id) => {
    // this.setState({ delkey: id });  如果我在页面中加一个随便改变组件stage值的语句页面就会刷新数据，这是为什么
    this.props.delStepData(this.props.list,id);
  };

**Comment by chenshuai2144** [comment]
你把数据放到了 state 中吗？

**Comment by superwuman** [comment]
> 你把数据放到了 state 中吗？

我把数据放入model中state了，然后注入进组件用props.data取的

**Comment by chenshuai2144** [comment]
你的删除是怎么做的，感觉是因为 react 不觉得你的数据更新了。

**Comment by linyongping** [comment]
放完整点的代码上来看看

**Comment by superwuman** [comment]
> 你的删除是怎么做的，感觉是因为 react 不觉得你的数据更新了。

刚开始我使用数组.splice截数组的，这样子不刷新页面
后来改成数组.filter过滤数据，然后页面就刷新了，好奇怪哦

**Comment by linyongping** [comment]
Splice会修改原数组，filter 方法是不会修改原数组的，
