### ISSUE TITLE
关闭 mock 之后，出现服务器错误。

### ISSUE THREAD

**Issue by worldzb** [ant-design/ant-design-pro#3478]
当我使用
```npm run start:on-mock```
启动应用时，出现如下错误
![image](https://user-images.githubusercontent.com/24642015/51810364-4fe6f480-22e2-11e9-93c9-caa7b64cea2e.png)
此时，是没有开启 proxy ，而当开启 proxy 时，也会  fetch('/api/auth_routes') 失败。从而导致 fetch().then()里面的 json 解析错误，最终导致应用无法启动。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3483
