### ISSUE TITLE
'Description' in 'Description List' doesn't have style attribution.

### ISSUE THREAD

**Issue by soolaugust** [ant-design/ant-design-pro#3481]
https://github.com/ant-design/ant-design-pro/blob/464912e7d0b610f35f1b5c7190843ab26ae8e64d/src/components/DescriptionList/Description.js#L9-L10

'Description' doesn't have style attribution and will use default style (styles.term & styles.detail).

What should I do to change 'Description'   style instead of change component code?

**Comment by chenshuai2144** [comment]
If you use components, you can override the css style.

**Comment by soolaugust** [comment]
@chenshuai2144 thanks for answering, I think your advice will work, could you share more details or reference for this. I try by myself but could get working.

**Comment by chenshuai2144** [comment]
https://unpkg.com/ant-design-pro@2.3.1/lib/PageHeader/style/index.css 
this is a css class list

**Comment by soolaugust** [comment]
that helps, thx 👍
