### ISSUE TITLE
项目build内存溢出

### ISSUE THREAD

**Issue by playedclass** [ant-design/ant-design-pro#3482]
<--- Last few GCs --->

[6103:0x102802400]  1326729 ms: Mark-sweep 1403.1 (1527.0) -> 1403.1 (1525.5) MB, 1649.8 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1760 ms) last resort GC in old space requested
[6103:0x102802400]  1328354 ms: Mark-sweep 1403.1 (1525.5) -> 1403.1 (1525.5) MB, 1624.0 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x18ff68325879 <JSObject>
    2: _visit [0x18ff327822d1 <undefined>:1337] [bytecode=0x18ffbe4bbcb9 offset=12](this=0x18ffc3865311 <TreeWalker map = 0x18ff84c30d51>,node=0x18ff15ce6c91 <AST_SymbolVar map = 0x18ff3ae11879>,descend=0x18ff327822d1 <undefined>)
    3: arguments adaptor frame: 1->2
    4: _walk [0x18ff327822d1 <undefined>:480] [bytecode=0x18ffbe4bde59 offset=7](this=0x18ff15ce6c91 <AST_SymbolVar map = 0x18ff3a...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 4: v8::internal::Factory::NewCodeRaw(int, bool) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, int) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::TurboAssembler*, v8::internal::EhFrameWriter*, v8::internal::CompilationInfo*,v8::internal::Handle<v8::internal::Object>) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 7: v8::internal::compiler::CodeGenerator::FinalizeCode() [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 8: v8::internal::compiler::PipelineImpl::FinalizeCode() [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
 9: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
10: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
11: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
12: v8::internal::StackGuard::HandleInterrupts() [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
13: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/seadon/.nvm/versions/node/v8.12.0/bin/node]
14: 0x273a2e2042fd
15: 0x273a2e3078e7

**Comment by playedclass** [comment]
项目越来越大后，就构建出错了

**Comment by chenshuai2144** [comment]
找一下是什么包这么大，把他扔到 cdn 上面

**Comment by playedclass** [comment]
> 找一下是什么包这么大，把他扔到 cdn 上面

关键是看不到，项目里对antd的一些组件有过二次开发，用的ts文件，原来都问题
找了下roadhog的配置，没发现有调试的参数，原来有个--debug，应该不起作用

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/d8a026f293989c22ad6bd4cb3ec19725a1357e82/package.json#L12

**Comment by playedclass** [comment]
> [ant-design-pro/package.json](https://github.com/ant-design/ant-design-pro/blob/d8a026f293989c22ad6bd4cb3ec19725a1357e82/package.json#L12)
> 
> Line 12 in [d8a026f](/ant-design/ant-design-pro/commit/d8a026f293989c22ad6bd4cb3ec19725a1357e82)
> 
>  "analyze": "cross-env ANALYZE=1 umi build",

还没用到umi，用的2.0beta，打算项目结束后，开个分支再升级umi试试

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/b7e7983661eb5e53dc807452e9653e93e74276d4/package.json#L12

**Comment by playedclass** [comment]
> [ant-design-pro/package.json](https://github.com/ant-design/ant-design-pro/blob/b7e7983661eb5e53dc807452e9653e93e74276d4/package.json#L12)
> 
> Line 12 in [b7e7983](/ant-design/ant-design-pro/commit/b7e7983661eb5e53dc807452e9653e93e74276d4)
> 
>  "analyze": "cross-env ANALYZE=true roadhog build",

报的是一样的错误，这两个命令一直在用

**Comment by playedclass** [comment]
下午我先排查下，看能不能定位问题，build的时间有点长，都15分钟了

**Comment by playedclass** [comment]
用increase-memory-limit插件解决问题，后续再性能优化~
