### ISSUE TITLE
api/auth_routes 这个已经严重影响到发布

### ISSUE THREAD

**Issue by b9AobJ** [ant-design/ant-design-pro#3483]
![image](https://user-images.githubusercontent.com/4596723/51887969-73886880-23d0-11e9-84bb-334b94d6a185.png)

同样在npm run start:no-mock情况下出现
请问下，这个需要我怎么配置？
项目初期阶段并不需要通过服务器来动态验证权限

**Comment by yutingzhao1991** [comment]
这个和动态路由没关系，就是接口没有正确返回 json 格式的数据。

**Comment by afc163** [comment]
@xiaohuoni

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3478

**Comment by b9AobJ** [comment]
https://github.com/ant-design/ant-design-pro/commit/5a9d3c079c183357757111e807ffa5b11087250e

解决！

**Comment by BingXiong1995** [comment]
我是直接在dist的根目录建了了api/auth_routes，然后把这个接口的数据直接放了进去。。。

**Comment by xiaohuoni** [comment]
不需要在appjs里面删除就好了
