### ISSUE TITLE
table 展开问题

### ISSUE THREAD

**Issue by my1229** [ant-design/ant-design-pro#3486]
本地展开没问题；但是部署到环境后，会出现展开超框，

请教一下应该怎么解决？谢谢🙏

打开前：
![1](https://user-images.githubusercontent.com/16729788/51898719-7f822380-23ec-11e9-9e3f-da0d19b94f33.png)

打开后：
![2](https://user-images.githubusercontent.com/16729788/51898751-958fe400-23ec-11e9-80fa-efdc6f8a2acf.png)

**Comment by chenshuai2144** [comment]
感觉是antd 的版本不一样，样式差距好大

**Comment by my1229** [comment]
> 感觉是antd 的版本不一样，样式差距好大

是这个问题...... 谢谢 👍
