### ISSUE TITLE
下拉框选中内容点击保存后，再点击修改，不显示刚才选中的内容

### ISSUE THREAD

**Issue by supconlc** [ant-design/ant-design-pro#3489]

**Comment by supconlc** [comment]
> 给个最小实现，或者代码
一个可编辑表格，点击新增，其中一列可以通过下拉框进行选择，选择后点击保存，保存后可以正常显示选择的内容，如果想修改表格内容，点击编辑后，有下拉框的那一页就只显示下拉框，不显示刚才选中的内容，代码如下：
        return {
          ...col,
          onCell: record => ({
            record,
            inputType: col.dataIndex === 'nodeTypeName'
              ? 'select'
              : 'text',
            dataIndex: col.dataIndex,
            title: col.title,
            editing: this.isEditing(record)
          })
        };

**Comment by supconlc** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
感觉是因为 key 问题，所以造成组件没有更新。做好给个在线demo
