### ISSUE TITLE
补充路由文档

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#349]
- [ ] 如何添加三级菜单项
- [ ] 如何添加不在菜单中的路由 #227

**Comment by wunayou** [comment]
我现在就是需要这个路由的知识 

还有一个路由问题 你们的DEMO分步表单  第二步表单 应该是需要保护 不能直接输入就可以进来的 

很期待你们的写法

**Comment by wunayou** [comment]
三级路由 不是这样添加的吗？
 {
            name: '分步表单',
            path: 'step-form',
            component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm')),
            children: [
              {
                path: 'confirm',
                component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step2')),
              },
              {
                path: 'result',
                component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step3')),
              },
            ],
          },

**Comment by wunayou** [comment]
如何添加不在菜单的路由不是这个判断吗？  <Menu
            theme="dark"
            mode="inline"
            {...menuProps}
            onOpenChange={this.handleOpenChange}
            selectedKeys={this.getCurrentMenuSelectedKeys()}
            style={{ margin: '16px 0', width: '100%' }}
          >
            {this.getNavMenuItems(this.menus)}
          </Menu>

**Comment by wunayou** [comment]
有空帮我写一个  你们的DEMO分步表单 第二步表单 应该是需要保护 不能直接输入就可以进来的

还是router不同页面之间的传参 谢谢了

**Comment by ddcat1115** [comment]
路由和菜单已整体更新，[新的路由/菜单 文档](https://github.com/ant-design/ant-design-pro-site/blob/9ee824beab6497e39109eb8dc63bd8584ad41d4c/docs/router-and-nav.md)
