### ISSUE TITLE
Select 的的dropdownRender 不管用

### ISSUE THREAD

**Issue by zhouguanglong** [ant-design/ant-design-pro#3491]
```
<Select
    defaultValue="lucy"
    style={{ width: 120 }}
    dropdownRender={menu => (
      <div>
        {menu}
        <Divider style={{ margin: '4px 0' }} />
        <div style={{ padding: '8px', cursor: 'pointer' }}>
          <Icon type="plus" /> Add item
        </div>
      </div>
    )}
  >
    <Option value="jack">Jack</Option>
    <Option value="lucy">Lucy</Option>
  </Select>
```
dropdownRender不起作用啊

**Comment by zhouguanglong** [comment]
import React, { PureComponent,Fragment } from 'react';
import {
    Card,
    Button,
    Form,
    Select, Icon, Divider
} from 'antd';
import { createHashHistory } from 'history';
import PageHeaderLayout from '../../layouts/PageHeaderLayout';  // 引入头部组件
const history = createHashHistory();
const Option = Select.Option;

 class BasicList123 extends PureComponent {
  state = {
  	  
  }	
	
  componentDidMount() {
  	 
  }


  render() {

    return (
    	<div>
    	   <PageHeaderLayout />
    	   <Card title="扩展下拉列表">
			    <Select
				    defaultValue="lucy"
				    style={{ width: 120 }}
				    dropdownRender={menu => (
				      <div>
				        {menu}
				        <Divider style={{ margin: '4px 0' }} />
				        <div style={{ padding: '8px', cursor: 'pointer' }}>
				          <Icon type="plus" /> Add item
				        </div>
				      </div>
				    )}
				  >
				    <Option value="jack">Jack</Option>
				    <Option value="lucy">Lucy</Option>
				  </Select>
    	   </Card>
        </div>
    );
    
    
  }
}

const BasicList = Form.create({

})(BasicList123);

export default BasicList
这是在 antd pro 里面 单列出来的一个 js 页面，就是把官网上扩展菜单 的代码 粘贴过来的，为什么dropdownRender 没有效果呢？

**Comment by zhouguanglong** [comment]
是不是跟版本有关系？ 我用的是 v3.3.0 版本，官网上 dropdownRender 有效果，自己项目中没效果

**Comment by chenshuai2144** [comment]
3.9之后才加的 api
