### ISSUE TITLE
跨域请求时，前端的请求怎么加withCredentials:true

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3495]
目前浏览器无法把cookie发给后端，后端session一直变化，在ajax需要加上：

```
xhrFields: {
      withCredentials: true
 }
```
请问ant-design-pro怎么加这个？

**Comment by imhele** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/WindowOrWorkerGlobalScope/fetch#%E5%8F%82%E6%95%B0

在参数里配置 `credentials = 'include'`

**Comment by mstao** [comment]
我的前端代码 request.js  包含了`credentials = 'include'`，访问时如下图所示：

![snipaste_2019-01-31_16-33-50](https://user-images.githubusercontent.com/23411433/52041650-01ea1f00-2576-11e9-9650-dd51cc0c65e3.png)

我的浏览器是google chrome，这样的是cookie没法像服务端发送了吧

**Comment by imhele** [comment]
> 我的前端代码 request.js 包含了`credentials = 'include'`，访问时如下图所示：
> 
> ![snipaste_2019-01-31_16-33-50](https://user-images.githubusercontent.com/23411433/52041650-01ea1f00-2576-11e9-9650-dd51cc0c65e3.png)
> 
> 我的浏览器是google chrome，这样的是cookie没法像服务端发送了吧

控制台报错了没？

**Comment by mstao** [comment]
控制台没有报错，后台是Java，每次请求Session会刷新

**Comment by imhele** [comment]
> 控制台没有报错，后台是Java，每次请求Session会刷新

Response header 中有没有设置 `Access-Control-Allow-Origin: *` 和 `Access-Control-Allow-Credentials: true` 呢？

**Comment by mstao** [comment]
> > 控制台没有报错，后台是Java，每次请求Session会刷新
> 
> Response header 中有没有设置 `Access-Control-Allow-Origin: *` 和 `Access-Control-Allow-Credentials: true` 呢？

设置过了
```
    response.addHeader("Access-Control-Allow-Origin", request.getHeader("Origin"));
    response.addHeader("Access-Control-Allow-Credentials", "true");
```

**Comment by imhele** [comment]
不应该呀，你的 request content-type 是什么？

**Comment by mstao** [comment]
> 不应该呀，你的 request content-type 是什么？

就是普通的get请求，并未设置

![snipaste_2019-01-31_17-58-49](https://user-images.githubusercontent.com/23411433/52046531-e08f3000-2581-11e9-8348-5f1ddcd0cff2.png)

**Comment by mstao** [comment]
后台我改为redis存储了，暂时不用考虑session问题了。
Thanks @imhele

**Comment by chenshuai2144** [comment]
跨域的时候是没有 cookie 的

**Comment by mstao** [comment]
> 跨域的时候是没有 cookie 的，session 是基于 cookie 的最好使用代理

昨天试了一下，确实是没有cookie，所以目前的解决方式: 后端生成图形验证码的key，将key和图形码的字符串存入redis，同时将图片base64编码，连同key传给前端，验证时通过key和输入的验证码去后端验证。这样就是完全不使用cookie和session，对分布式应用感觉更好点。

谢谢大家~

**Comment by chenshuai2144** [comment]
不安全，你应该让自己和网关同源。
https://harttle.land/2016/12/28/cors-with-cookie.html
