### ISSUE TITLE
antd-theme-webpack-plugin 惊天bug （about canvas height & width）

### ISSUE THREAD

**Issue by weishijun14** [ant-design/ant-design-pro#3497]
情景重现： 

react-particles-js 是 particles.js 的react 实现。
https://github.com/Wufe/react-particles-js
这个particles应该有人用过吧。

![image](https://user-images.githubusercontent.com/20705423/52105638-77172c00-262a-11e9-83a0-9792ba17926c.png)

ok， 我把这个particles用在了login 的背景中。

直到昨天，我发现测试服务器上的login page的f5会导致particles不渲染了。（但是每次构建好的第一次加载是好的？？只要f5了，就丢失了）

本来这样：（构建完成后第一次加载）
![image](https://user-images.githubusercontent.com/20705423/52108547-51dbeb00-2635-11e9-8d88-a0b54d5ee1ec.png)

现在这样：（第二次，使用f5刷新之后）
![image](https://user-images.githubusercontent.com/20705423/52108562-5ef8da00-2635-11e9-849d-c60e7a95de8b.png)

于是我打开源码查看：
```javascript
<Particles
    height='1000px'
    width='900px'
    params={particlesParams}
    style={{ position: 'fixed', background: '#efefef'}}
 />
```
没毛病啊，官网也是这么用的啊？

然后我检查下chrome dev tools，发现canvas 的width 和 height 属性全都是0.
```
<canvas width='0' height='0' ...>
```
**最诡异的是，同样的设置，在本地是好的？？**
```
// in localhost:
<canvas width='1920' height='980' ...>
```

于是我朝着canvas如何设置宽高的方向找去。这一找就是**数十个小时**，
包含了从gitlab --> jenkins 构建的时间。

但是，无论我如何设置canvas的宽高，最后的一下f5，依然会使得canvas的width,height归零。
我陷入了深深的绝望（思考...

在最后的一次实验中， 我使用如下的骚操作：
```javascript
componentDidMount() {
    this.updateWindowDimensions();
    window.addEventListener('resize', this.updateWindowDimensions);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.updateWindowDimensions);
  }

  updateWindowDimensions = () => {
    this.setState({
      width: `${1920}px`,
      height: `${938}px`,
    });
  };

  componentDidUpdate = (prevProps, prevState) => {
    const dom = document.getElementsByTagName('canvas');
    console.log(dom, 'dom');
    if (dom[0]) {
      // console.log(this.state.height, 'state.height');
      dom[0].width = 400;
      dom[0].height = 200;
      console.log(dom[0].height, dom[0]);
    }
  };
```

然而，并没有起作用，然而，心思细腻的我发现一个小插曲：

每次构建完，第一次的console中，**这个console.warn都是在第一行显示：**
![image](https://user-images.githubusercontent.com/20705423/52106538-24d80a00-262e-11e9-9170-a2ebf894d120.png)

然而，后面的几次f5，**会导致console.warn显示在最后一排：**

![image](https://user-images.githubusercontent.com/20705423/52106548-31f4f900-262e-11e9-8e3b-1cea51c3c253.png)

会不会是这个原因？？
根据现象的表征，每次构建完，抑或是强刷之后的一次，都可以正常显示（清空了缓存）,而之后的
几次f5都无法正常显示（缓存读取），也符合逻辑？？
我决定试一试去深挖一下这个console.warn到底是什么：
![image](https://user-images.githubusercontent.com/20705423/52106247-0b828e00-262d-11e9-92d5-aed8b2b7415f.png)

也就是这个：
![image](https://user-images.githubusercontent.com/20705423/52106268-1806e680-262d-11e9-8ac9-2add5c05cdc8.png)

那么，离真相很近了：
src/config/plugin.config.js:

![image](https://user-images.githubusercontent.com/20705423/52106301-31a82e00-262d-11e9-993f-9a7694240f76.png)

注释掉红框内的，构建 --> 随意f5 ， **大功告成**！

注： 本地之所以是好的：

![image](https://user-images.githubusercontent.com/20705423/52106434-b72bde00-262d-11e9-82a6-c4588cd79868.png)

是因为本地没有存在这个less.min.js。

总结： 这个东东，导致了我整个canvas崩溃。恕我无知，不知道具体是什么原因。希望有关大神，可以查探一番。
或是less.min.js中有东西能强制改变canvas的宽高。

**Comment by chenshuai2144** [comment]
写的很棒，应该深入一下 less.js 的内部是不是搞了什么东西

**Comment by leonway** [comment]
我是另一个引入.less 编译失败的问题 不过直接把你圈出来的注释掉后 就可以用了
