### ISSUE TITLE
form中域赋值的问题

### ISSUE THREAD

**Issue by anizephyr** [ant-design/ant-design-pro#3505]
react新手请教一下。。。
场景描述：我的form中域是根据用户选择动态生成的，有input也有datepicker，从后台获取关联在用户下的初始数据(objs)后要赋值到form中供用户检查修改并提交。
现在的问题是，我是用fieldKeys.forEach(key=>form.setFieldsValue({key:objs[key]}))这种方式赋值的，虽然我知道每个key对应的域到底是input还是datepicker，但是每次挑选key用以生成form的组合都可能是不同的，不能把所有datepicker的key全列在那里一一判断，那样很蠢，有没有类似以往框架中通过key可以获取到form中控件类型的方法用来决定赋值的时候要不要套上moment。
感谢！

**Comment by chenshuai2144** [comment]
这个是因为 antd 的日期组件内部使用了 moment。你可以在 onSubmit 中进行修改。
