### ISSUE TITLE
从mock切换到后台数据接口

### ISSUE THREAD

**Issue by kstar11** [ant-design/ant-design-pro#351]
似乎这个问题很多人问过,看了好多文档,现在还是懵逼状态,所以求解
我理了一下,大体步骤是否应为:
1.使用npm run start:no-proxy启动工程
2.修改roadhogrc.mock.js,将export的导出修改为服务器地址
![qq 20171204152605](https://user-images.githubusercontent.com/25189126/33540777-7b76f38c-d907-11e7-8772-b306f81555ec.png)
3.修改.roadhogrc文件,添加proxy属性
  "proxy":{
    "/api":{
      "terget":"http://localhost:8866/",
      "changeOrigin":true,
      "pathRewrite":{"^/api":""}
    }
  }
4.将 各处数据请求指向 设定好的地址
目前报错是 504,Gateway Timeout
![qq 20171204152930](https://user-images.githubusercontent.com/25189126/33541009-62e930a4-d908-11e7-8b63-89e553d49be9.png)

不知是哪一步出错,求指导解惑!~

**Comment by nikogu** [comment]
1. npm run start:no-proxy

这一步就挂了，`no-proxy` 意思是不要代理。。。

看这个：https://pro.ant.design/docs/server-cn#从-mock-直接切换到服务端请求

之前的问题是因为底层工具 roadhog-api-doc 有个 bug，已经修复更新最新版即可。

**Comment by kstar11** [comment]
傻了,target写成terget的,所以才报了gateway timeout
no-proxy的问题我是没说清楚,不过现在已经OK了
3Q very much

**Comment by afc163** [comment]
@kstar11 You can close it if the problem is resolved.
