### ISSUE TITLE
Is this appropriate parse response to json directly?

### ISSUE THREAD

**Issue by soolaugust** [ant-design/ant-design-pro#3513]
Logic in `request.js` will parse response to json directly. Is this appropriate as there are responses with other types?

https://github.com/ant-design/ant-design-pro/blob/bb045ead169a227387ca24dc0a2f60c249c63b35/src/utils/request.js#L130

**Comment by chenshuai2144** [comment]
This is our recommended behavior and json is a good way to do it.
As a scaffold, you can change it yourself.

**Comment by soolaugust** [comment]
I see, thanks 👍
