### ISSUE TITLE
Ant Design components

### ISSUE THREAD

**Issue by diogomaiacaetano** [ant-design/ant-design-pro#3519]
Hello!
I'm having an issue on finding one component.
This component I want is a dropdown, where I can have a multi select. The thing is that I haven't found one that can keep the same place holder that the dropdown already has.
Can you help me please?
Best Regards

**Comment by chenshuai2144** [comment]
sorry，
I don't know why multiple selections can't solve your problem. Can you describe it in detail?

**Comment by xiaohuoni** [comment]
like this。No this Component

![image](https://user-images.githubusercontent.com/11746742/52618832-de5e9700-2eda-11e9-93fc-2ef183382dbf.png)

**Comment by diogomaiacaetano** [comment]
Good morning,

I not sure if there is a component that is a 100% fit or not. I’m using a dropdown, in which the placeholder Will always be the same, and my idea is that by opening the dropdown I’ll be able to select a couple of options.
But yeah, similar like in the image you sent 😉

Cheers,

Diogo Maia Caetano

**Comment by chenshuai2144** [comment]
You can customize your own style with `dropdownRender`.
https://ant.design/components/select/#Select-props
