### ISSUE TITLE
0.3.0 打包之后的文件，不能运行

### ISSUE THREAD

**Issue by lsqlebai** [ant-design/ant-design-pro#352]
关联文件路径不对， 打包生成的index.html内容
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ant Design Pro</title>
  <link rel="icon" href="/favicon.png" type="image/x-icon">
<link href="/index.3be8a28e.css" rel="stylesheet"></head>
<body>
  <div id="root"></div>
  <script src="https://gw.alipayobjects.com/as/g/??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js"></script>
<script type="text/javascript" src="/index.11d9bd52.js"></script></body>
</html>

src="/index...”之类浏览器之类报错找不到文件

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。

**Comment by chenshuai2144** [comment]
@afc163  是不是应该增加提问模板?

**Comment by lsqlebai** [comment]
![image](https://user-images.githubusercontent.com/3232118/33544517-099c3aa6-d916-11e7-9485-82eef616a423.png)

上面那个问题加一个publicPath可以解决，又出一个新的问题

**Comment by chenshuai2144** [comment]
@lsqlebai  自定义的组件有没有加default

**Comment by lsqlebai** [comment]
@chenshuai2144 就是使用
$ npm install ant-design-pro-cli -g
$ mkdir pro-demo && cd pro-demo
$ pro new
选standard
直接打包出来运行dist下index.html 本地chrome 就报错。 
环境是 win7 node.js v8.7.0 cnpm 5.1.1 npm 5.5.1

**Comment by chenshuai2144** [comment]
@lsqlebai  试着直接clone 主分支,然后再试试

**Comment by lsqlebai** [comment]
@chenshuai2144 
master也有同样问题
v0.2.3也有同样
v0.2.2是ok的

他们 的区别就是一个打包老版本打包出来就3个文件。 新版本有很多1.sync,2.sync的文件，就这里报错了

**Comment by chenshuai2144** [comment]
我就是直接打包出来的是没有问题.是不是chrome的问题?

**Comment by lsqlebai** [comment]
**环境： os ： win7  chorme：版本 61.0.3163.91**
@chenshuai2144
再次下载master => npm install => npm run build
（没有任何修改,如果增加在.roadhogrc中增加"publicPath":"",可以解决第一个问题，文件找不到，就会出现之后的问题）

生成dist放在github上供参考：
https://github.com/lsqlebai/ant-design-pro-test

**Comment by shykhy** [comment]
有個疑問，就是新版本的ant-design-pro （下載位置：https://github.com/ant-design/ant-design-pro/archive/master.zip）
有沒辦法將npm run build生成的所有js文件打包
像如下文件：
0.8838f1cb.async.js
1.df8d2039.async.js
2.aaa435a3.async.js
打包在index.js中呢?
