### ISSUE TITLE
退出登陆后，title变成url

### ISSUE THREAD

**Issue by zhanghouji** [ant-design/ant-design-pro#3520]

**Comment by zhanghouji** [comment]
<img width="258" alt="2019-02-12 12 01 37" src="https://user-images.githubusercontent.com/39083848/52611085-c547ed00-2ebe-11e9-8c9d-7c739bd930f7.png">

**Comment by chenshuai2144** [comment]
login 没有设置 title 的问题，有兴趣搞个 pr吗？

**Comment by zhanghouji** [comment]
我也没找到问题根源，不知道怎么改，退出登陆会变，但是一刷新就好了。

**Comment by xiaohuoni** [comment]
UserLayout 里面加上 DocumentTitle 就可以了
