### ISSUE TITLE
表单页面，当离开时添加离开确认提示？

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3521]
表单界面，如果用户添加了很多数据，用户点击按钮跳页面或者关闭该页面，需要离开确认，在 表单class中这样写：

```
  componentDidMount() {
    window.onbeforeunload = function(e) {
      e = e || window.event;
      if (e) {
        e.returnValue = '确定离开？'
      }
      return '确定离开？'
    }
  }

  componentWillUnmount(){
    window.onbeforeunload = undefined
  }
```

上面的代码的效果只支持关闭/刷新该页面时（浏览器tab关掉）会有确认提示，请问如何在当前页面销毁之前进行确认提示呢？（单页面应用）

**Comment by chenshuai2144** [comment]
这个需要 react-router 的支持了。
你可以用componentWillUnmount 然后使用 alert 来进行提示

**Comment by mstao** [comment]
componentWillUnmount这个钩子函数在组件卸载前调用，它并不能阻止当前组件的卸载。所以如果在这个方法处理了，当前组件还是会卸载

**Comment by chenshuai2144** [comment]
你使用的是 dva 吗？这个需要改动业务流程了。
你可以在 redux 中监控 url 的变化，然后进行提示

**Comment by mstao** [comment]
是的，还有就是url不变化，仅通过按钮来控制界面，这个不知道怎么控制

**Comment by xiaohuoni** [comment]
按钮在点击事件里面管理应该可以吧。离开页面的方法，umi好像有一个钩子吧，看看 umi/prompt 能不能满足你。
```js
import Prompt from 'umi/prompt';

export default () => {
  return (
    <>
      <h1>Prompt</h1>
      <Prompt
        when={true}
        message={(location) => {
          return window.confirm(`confirm to leave to ${location.pathname}?`);
        }}
      />
    </>
  );
}
```
https://github.com/umijs/umi/pull/1267

**Comment by mstao** [comment]
现在就是在按钮的点击事件里进行控制的，这个是可以的，我试试umi/prompt

多谢~

**Comment by mstao** [comment]
测试了，当路由变化时，umi/prompt是ok的

![snipaste_2019-02-13_15-44-46](https://user-images.githubusercontent.com/23411433/52694993-51810f80-2fa6-11e9-9edf-c042536f6513.png)

**Comment by xiaohuoni** [comment]
棒棒哒！

**Comment by xwg2015** [comment]
> 测试了，当路由变化时，umi/prompt是ok的
> 
> ![snipaste_2019-02-13_15-44-46](https://user-images.githubusercontent.com/23411433/52694993-51810f80-2fa6-11e9-9edf-c042536f6513.png)
 哥 umi/prompt为什么我一直安装不上 求解

**Comment by xiaohuoni** [comment]
@xwg2015 没这个库，如果是 umi@2 装了 umi 就有。如果是 umi@3  `import { Prompt } from 'umi';`
