### ISSUE TITLE
table 编辑单元格中 可以编辑多个单元格吗  有单元格是DatePicker 有的是Input

### ISSUE THREAD

**Issue by painoBoy** [ant-design/ant-design-pro#3523]

**Comment by chenshuai2144** [comment]
可以的，都是在 render 中判断的，根据需求来就好了

**Comment by painoBoy** [comment]
> 可以的，都是在 render 中判断的，根据需求来就好了
可以给个列子吗 ，试了很久效果也没有做出来

**Comment by painoBoy** [comment]
> 可以的，都是在 render 中判断的，根据需求来就好了

可以给个列子吗，试了很久效果也没有出来-.-

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/EditableItem/index.js
看这个组件
