### ISSUE TITLE
cachedSave

### ISSUE THREAD

**Issue by sunkaigoon** [ant-design/ant-design-pro#3524]
@afc163 
https://github.com/ant-design/ant-design-pro/blob/b042b09754522677e816853723c7806555fe88f0/src/utils/request.js#L106
我看expirys只是控制是否从缓存中取数据，并没有控制是否进行缓存操作。
https://github.com/ant-design/ant-design-pro/blob/b042b09754522677e816853723c7806555fe88f0/src/utils/request.js#L52
有时候因为数据超长会缓存失败。

_Originally posted by @sunkaigoon in https://github.com/ant-design/ant-design-pro/issues/2736#issuecomment-457057409_

**Comment by chenshuai2144** [comment]
如果在正式环境，我建议你删掉这个逻辑，这个逻辑是为了优化我们网站的流量
