### ISSUE TITLE
Menu兼容问题

### ISSUE THREAD

**Issue by chengnuo** [ant-design/ant-design-pro#353]
问题：
safari 版本 10.1.2 (12603.3.8) 移动上子menu，移动不上去。
谷歌是可以的。我用的antd-pro,3.0.0beta版本，升级到最新版本也不可以。

如何定位：
![image](https://user-images.githubusercontent.com/13076859/33546107-1a08159a-d91b-11e7-9276-50501b108ea8.png)

debug:
在antd 2.13.11是可以的。https://ant.design/components/menu-cn/
在 https://preview.pro.ant.design/#/dashboard/analysis 就不可以了。

寻求帮助：
- 怎么修改antd源码，我先改源码解决
- 有什么思路可以解决。

**Comment by chengnuo** [comment]
![image](https://user-images.githubusercontent.com/13076859/33546066-fb5feaf0-d91a-11e7-927e-39a9c12fffcd.png)

**Comment by zim-lee** [comment]
I have the same problem

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/8453

**Comment by afc163** [comment]
It is fixed in `dom-align@1.6.6`, try to reinstall node_modules.
