### ISSUE TITLE
Optimize page speed

### ISSUE THREAD

**Issue by NorthFoxz** [ant-design/ant-design-pro#3530]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpreview.pro.ant.design%2Fdashboard%2Fanalysis

The preview page only scores 14 on Google PageSpeed, it's quite low.
Any idea on how to optimize page load?

**Comment by chenshuai2144** [comment]
Now js is still very large, we hope to be able to load through the cache, if it is an admin, the loading speed after the cache is still very fast, about 0.5s will display the interface
