### ISSUE TITLE
ant design pro 项目 启动报错

### ISSUE THREAD

**Issue by AppleAndAngel** [ant-design/ant-design-pro#3533]
哪位大神知道这是什么情况吗？
按照官网步骤拉取了最新代码，并npm install安装好了依赖，执行npm start时报错了，报错信息如下：

![image](https://user-images.githubusercontent.com/28129850/52691487-df0b3200-2f9b-11e9-8c13-095d47125ee4.png)

**Comment by AppleAndAngel** [comment]
动手搜了半天，依然没有头绪.......
还望不吝赐教，万分感谢！！！

**Comment by chenshuai2144** [comment]
额 这怎么可能是最新的，roadhog 已经被淘汰了

**Comment by xiaohuoni** [comment]
拉这个https://github.com/ant-design/ant-design-pro.git

**Comment by AppleAndAngel** [comment]
谢谢两位！！刚刚重新拉取代码，又安装了一遍可以正常打开。其实我最先拉取的确实是最新的代码，图上的的项目是我后来拉取的，最先的代码启动的时候报错： ERROR: spawn umi ENOENR 日志如下：
![image](https://user-images.githubusercontent.com/28129850/52694129-af602800-2fa3-11e9-96d1-326e6d76209f.png)

不清楚是不是网不好安装依赖出现了问题，哈哈哈，现在没报错了。

@chenshuai2144 @xiaohuoni
