### ISSUE TITLE
希望把使用umi的说明写到首页醒目的位置上！

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3536]
公司其他部门的同事，老是说他们使用的是antd-pro，没用过umi！
找了一下官网和首页，确实都没有说明！
![image](https://user-images.githubusercontent.com/11746742/52695664-0f58cd80-2fa8-11e9-8be0-8055b5cd16f8.png)

**Comment by chenshuai2144** [comment]
umi 做个 bage 吧

**Comment by xiaohuoni** [comment]
@sorrycc 老大！打广告的时候来啦！

**Comment by sorrycc** [comment]
👍，用这个吧。

[![](https://img.shields.io/badge/built--with-umi-blueviolet.svg)](https://github.com/umijs/umi)

```
[![](https://img.shields.io/badge/built--with-umi-blueviolet.svg)](https://github.com/umijs/umi)
```

**Comment by afc163** [comment]
[![](https://img.shields.io/badge/build%20with-umi-028fe4.svg?style=flat-square)](https://github.com/umijs/umi)

```
[![](https://img.shields.io/badge/build%20with-umi-028fe4.svg?style=flat-square)](https://github.com/umijs/umi)
```

**Comment by chenshuai2144** [comment]
蓝色好看点

**Comment by sorrycc** [comment]
@chenshuai2144 可以，用蓝色吧。

**Comment by xiaohuoni** [comment]
首页的bage，有些有圆角有些没有！
