### ISSUE TITLE
Login.js 登录组件保存密码后刷新当前页面render函数会执行2次

### ISSUE THREAD

**Issue by sosout** [ant-design/ant-design-pro#354]
登录组件正常情况render函数会执行一次，如果记住密码会导致render函数执行2次，这是由于记住密码重新赋值导致的吗？
![11](https://user-images.githubusercontent.com/22269613/33545395-0cd86cfa-d919-11e7-83de-8a93e6a425a3.png)
![222](https://user-images.githubusercontent.com/22269613/33545464-3d298ede-d919-11e7-8e91-3916902458b3.png)

**Comment by chenshuai2144** [comment]
点一下记住密码会setState   当然会render两次的
