### ISSUE TITLE
开发环境更换主题后报错 window.less.modifyVars is not a function

### ISSUE THREAD

**Issue by Hansuku** [ant-design/ant-design-pro#3541]
开发环境切换主题 刷新页面后会显示正在编译主题 然后报错
![image](https://user-images.githubusercontent.com/28286561/52755953-b5551800-303a-11e9-89d7-3bf2fd2964d3.png)

**Comment by Hansuku** [comment]
系统版本：MacOS Mojave 10.14.3 
Chrome版本：版本 71.0.3578.98（正式版本） （64 位）

**Comment by Hansuku** [comment]
似乎是
```
// src/models/setting.js
setTimeout(() => {
      window.less
        .modifyVars({
          '@primary-color': primaryColor,
        })
        .then(() => {
          hideMessage();
        })
        .catch(() => {
          message.error('Failed to update theme');
          hideMessage();
        });
    }, 200);
```
这里在编译之前就执行了 如果把延时改到2000毫秒就没有问题了。

**Comment by xiaohuoni** [comment]
用延时控制异步流程有点奇怪！

**Comment by chenshuai2144** [comment]
less 加载速度比较慢吗？

**Comment by ldw21cn** [comment]
> 似乎是
> 
> ```
> // src/models/setting.js
> setTimeout(() => {
>       window.less
>         .modifyVars({
>           '@primary-color': primaryColor,
>         })
>         .then(() => {
>           hideMessage();
>         })
>         .catch(() => {
>           message.error('Failed to update theme');
>           hideMessage();
>         });
>     }, 200);
> ```
> 这里在编译之前就执行了 如果把延时改到2000毫秒就没有问题了。


确实如此，谢谢您。我改成300毫秒就可以了。
