### ISSUE TITLE
菜单背景问题

### ISSUE THREAD

**Issue by unrealsmart** [ant-design/ant-design-pro#3544]
亮色菜单下如图
![image](https://user-images.githubusercontent.com/11688458/52828248-f7e22780-3102-11e9-98fb-bd6a331dab72.png)

黑色菜单下如图
![image](https://user-images.githubusercontent.com/11688458/52828176-b3ef2280-3102-11e9-819e-9ca430f2932a.png)

`.ant-menu-submenu-popup` 所形成的元素框在亮色菜单下会出现暂留，影响动画效果

具体效果在官方预览站点中：
选择亮色菜单->收起菜单->移入移出具有子菜单的菜单项目->观察子菜单动画

解决办法例如：
添加
```
.ant-menu-light.ant-menu-submenu-popup {
    background: transparent;
}
```
背景设置为同黑色菜单下的透明色，本地个人测试在两种布局下均没有问题

**Comment by chenshuai2144** [comment]
应该推动 antd 做更新了
