### ISSUE TITLE
table能否支持嵌套拖拽？自己写的demo会导致拖拽时不能判断是否可以拖拽

### ISSUE THREAD

**Issue by qinyuhua** [ant-design/ant-design-pro#3545]
![image](https://user-images.githubusercontent.com/28893646/52829994-d2a4e780-3109-11e9-97b8-985dd52ceb54.png)

希望嵌套的子表格的拖拽只可以在它嵌套的那个范围内移动，别的地方不允许拖拽过去

**Comment by chenshuai2144** [comment]
antd 提供了 demo，你可以参考 antd 的 [demo](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

**Comment by qinyuhua** [comment]
> antd 提供了 demo，你可以参考 antd 的 [demo](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

demo没有嵌套两层都可以拖拽，

**Comment by chenshuai2144** [comment]
现在是没有这个 demo 的，你参考一下，最好提供一个可重现地址

**Comment by vivty** [comment]
> > antd 提供了 demo，你可以参考 antd 的 [demo](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)
> 
> demo没有嵌套两层都可以拖拽，

我想请问一下，这个功能你实现了吗，我现在也遇到这个问题
