### ISSUE TITLE
ant design pro的定位不清晰

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design-pro#3547]
ant design 和 ant design pro 这样的命名，99%的国外用户一开始都会觉得pro是收费版。比如：https://www.reddit.com/r/reactjs/comments/9kl22e/whats_the_difference_between_ant_design_and_ant/

随便浏览了一下文档，没找到什么地方明确强调pro是免费的。虽然license是MIT，但是因为仍然有很多页面是中文，github上也充斥着中文，可能会吓跑一些英语用户。

提议：
- FAQ页面强调一下 antd 和 pro都是免费的
  https://pro.ant.design/docs/faq
- readme开头强调一下完全免费的。
- npm页面的readme不应该是空白
  https://www.npmjs.com/package/ant-design-pro

**Comment by xiaohuoni** [comment]
* npm页面的readme不应该是空白
  https://www.npmjs.com/package/ant-design-pro

**Comment by zzyyzz1992** [comment]
有道理，可以考虑ant design kit

**Comment by rinick** [comment]
antd的Icon页面也有一个类似的问题
https://ant.design/components/icon/
带红点的icon应该是是新图标的意思吧？ 但是对于熟悉fontawesome的用户来说，很容易联想到带红点是收费图标的意思。在这个页面也找不到红点代表什么意思的说明。

**Comment by ztplz** [comment]
好像是，这名字好像容易让人误会。一般pro都是某个免费基础版本的加强版，还是收费的。别人就会误以为这是antd的收费功能加强版。

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
