### ISSUE TITLE
每一次npm start时都会有Mock files parse success

### ISSUE THREAD

**Issue by ccccccode** [ant-design/ant-design-pro#3549]
不管是start或者修改代码保存时都会有很多条的Mock files parse success出现，而且速度非常的慢，不清楚时什么原因
![4_ v 3mfmk i bzam q_wi](https://user-images.githubusercontent.com/41566488/52878577-f1ea5600-3197-11e9-81bf-f1616531ef8e.png)

**Comment by ccccccode** [comment]
用的是本地的api

**Comment by chenshuai2144** [comment]
你使用什么奇怪的语法吗？

**Comment by ccccccode** [comment]
没有，就按照官方的文档在router.config.js中加了一个路由，保存之后就编程这样子了，其他的地方都没有修改过
![e3b2i8 69gecf 41 w o](https://user-images.githubusercontent.com/41566488/52901854-abeacc00-3243-11e9-8cd4-138dd820aab6.png)

**Comment by ccccccode** [comment]
刚开始写还好，到了后面写的东西多了，cpu直接100%，npm start 最慢的一次花了好几分钟

**Comment by NgeKaworu** [comment]
遇到同样的问题
我是win10用户

**Comment by ccccccode** [comment]
我也是win10，但是之前没有遇到过这种问题，这俩天写个新的出现这种问题

**Comment by chenshuai2144** [comment]
新版本增加的输出
