### ISSUE TITLE
Module not found: Can't resolve 'antd/lib/divider'

### ISSUE THREAD

**Issue by ohmountain** [ant-design/ant-design-pro#355]
把ant-design-pro从0.2.1更新为0.2.2后出先问题

问题： `Module not found: Can't resolve 'antd/lib/divider'`

文件：`./node_modules/ant-design-pro/lib/Charts/Pie/index.js '。`

ant-design-pro 版本：0.2.2

antd: 2.13.6

`node_modles/antd/lib`下面着实没有`devider`

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq-cn#%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Ant-Design-Pro%EF%BC%9F

**Comment by selmansamet** [comment]
I updated the antd version to last version (3.3.3) and fixed.
