### ISSUE TITLE
怎样测试 dva connect的组件

### ISSUE THREAD

**Issue by Koopos** [ant-design/ant-design-pro#3550]
怎样测试 dva connect的组件？
`<Dashboard.WrappedComponent />`官网都不解释下这个

**Comment by chenshuai2144** [comment]
和 redux是一样的。
https://hackernoon.com/unit-testing-redux-connected-components-692fa3c4441c

`<Dashboard.WrappedComponent />` 指的是？

**Comment by Koopos** [comment]
被connect装饰的组件啊

**Comment by Koopos** [comment]
Dashboard就是返回的@connect()(Dashboard)

**Comment by afc163** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md#componentwrappedcomponent

https://pro.ant.design/docs/ui-test-cn#%E6%B5%8B%E8%AF%95-dva-%E5%8C%85%E8%A3%85%E7%BB%84%E4%BB%B6

**Comment by shuai4983958** [comment]
没看懂
