### ISSUE TITLE
在使用表格固定头部时样式问题

### ISSUE THREAD

**Issue by berry-bear** [ant-design/ant-design-pro#3553]
在使用表格时，使用scroll属性，一旦增加了y轴属性，表头和内容就出现错位现象，单独fixed列则没有问题。（各列的宽度都已经指定）

**Comment by xiaohuoni** [comment]
提供给可复现的例子吧

**Comment by berry-bear** [comment]
解决了，把antd的版本锁在3.10.10

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
