### ISSUE TITLE
Authorized 权限编码 通配符

### ISSUE THREAD

**Issue by duwei54** [ant-design/ant-design-pro#3556]
看了一下  antd 的权限貌似不支持通配符的code  像这样[user.*]可以匹配 [user.add][user.update]这种.之前后端权限一直这么设计的.  有没有啥办法可以前端支持呢?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/CheckPermissions.js

代码在这里，你可以修改这里的判断规则

**Comment by duwei54** [comment]
好呢,那自己撸一个吧
