### ISSUE TITLE
Authorized组件传入Promise页面会卡死

### ISSUE THREAD

**Issue by xiayu1986** [ant-design/ant-design-pro#3558]
使用场景，需要从后端验证用户权限并获取用户信息、菜单，所以修改了pages目录下的Authorized.js传了个promise给authority，但是发现这样做了之后会卡死页面，后来发现会疯狂地执行PromiseRender.js中的setRenderComponent方法，是不是我的用法有问题？我的ant pro版本是：2.2.1

代码如下：

import React from 'react';
import RenderAuthorized from '@/components/Authorized';
import { getAuthority } from '@/utils/authority';
import Redirect from 'umi/redirect';
import { GLOBAL_INDEX } from '../constant/global';

const Authority = getAuthority();
const Authorized = RenderAuthorized(Authority);

const authorityPromise = () => {
  return new Promise((resolve,reject) => {
    resolve();
  });
};

export default ({ children }) => {
  return (
    <Authorized authority={authorityPromise} noMatch={<Redirect to={GLOBAL_INDEX}/>}>
      {children}
    </Authorized>
  );
}

**Comment by chenshuai2144** [comment]
code?

**Comment by xiayu1986** [comment]
不好意思！！截图没传成功，一会儿到家我重新贴下代码。

**Comment by dushaobindoudou** [comment]
componentDidUpdate() {
    if (nextProps.ok === this.props.ok && nextProps.error === this.props.error) {
        return false;
    } else {
        this.setRenderComponent(nextProps); // 原来会一直出发render
    }
}

**Comment by yiyizym** [comment]
> 使用场景，需要从后端验证用户权限并获取用户信息、菜单，所以修改了pages目录下的Authorized.js传了个promise给authority，但是发现这样做了之后会卡死页面，后来发现会疯狂地执行PromiseRender.js中的setRenderComponent方法，是不是我的用法有问题？我的ant pro版本是：2.2.1
> 
> 代码如下：
> 
> import React from 'react';
> import RenderAuthorized from '@/components/Authorized';
> import { getAuthority } from '@/utils/authority';
> import Redirect from 'umi/redirect';
> import { GLOBAL_INDEX } from '../constant/global';
> 
> const Authority = getAuthority();
> const Authorized = RenderAuthorized(Authority);
> 
> const authorityPromise = () => {
> return new Promise((resolve,reject) => {
> resolve();
> });
> };
> 
> export default ({ children }) => {
> return (
> <Authorized authority={authorityPromise} noMatch={}>
> {children}
> 
> );
> }

`authorityPromise` 这个是 Function ，不是 Promise ，你应该直接这样写：

```
const authorityPromise = Promise.resolve(true)
```

不过我想说的是，传入 Promise 确实会不断执行 `setRenderComponent` ，导致页面卡死

**Comment by yiyizym** [comment]
我暂时重写了 PromiseRender.js 里面 `componentDidUpdate` 的内容

```
var PromiseRender = function (_React$PureComponent) {
...省略...
{
    key: 'componentDidUpdate',
    value: function componentDidUpdate(prevProps) {
      // new Props enter
      if(this.props.promise === prevProps.promise
        && this.props.ok === prevProps.ok
        && this.props.error === prevProps.error) return;
      this.setRenderComponent(prevProps);
    }

    // set render Component : ok or error

  }
...省略...
}
```

**Comment by dushaobindoudou** [comment]
参考一下这个pr吧
https://github.com/ant-design/ant-design-pro/pull/3616
promise ok来判断貌似可能会有问题

**Comment by xiaohuoni** [comment]
这个pr修复了 https://github.com/ant-design/ant-design-pro/pull/3813
