### ISSUE TITLE
关于扩展表格bug的求解

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#3559]
在可扩展的主表格中，点击扩展符时，默认不做逻辑处理，此时会出现从表（扩展表格）的数据会复制一份到主表的bug？如图一。
当我把从表格关闭，主表格的展示又恢复正常，如图二。
猜测：从表的展开影响了主表的DataSource。
疑惑：并没有重写点击扩展符所触发的函数逻辑，为何会影响主表的DataSource？从表展开，主表异常；从表收起，主表正常。一切的异常发生在展开的过程，可是，该如何解决。
求解，谢谢。
![table1](https://user-images.githubusercontent.com/40480550/52934575-d9de2680-3391-11e9-921f-ce5b32bcae60.jpg)
![table2](https://user-images.githubusercontent.com/40480550/52934590-e2366180-3391-11e9-999a-5ee03a5b2c7e.png)

**Comment by chenshuai2144** [comment]
最好使用不可变数据，普通的 js 对象都是引用，= 并不是 copy 一份，只是引用了一下，
你的问题很像数据引用被修了
