### ISSUE TITLE
npm start报错：decorators are not officially supported yet in 6.x pending a proposal update.

### ISSUE THREAD

**Issue by Alixiaodian** [ant-design/ant-design-pro#356]
今天刚开始使用ant-design-pro
按照官网上介绍开始一个新工程，3种方法：
![default](https://user-images.githubusercontent.com/18227599/33551872-c6307a9e-d92d-11e7-882c-9a3cefb11462.png)

其中直接下载压缩包，npm start起来会报错
![2](https://user-images.githubusercontent.com/18227599/33551913-fae68d28-d92d-11e7-9d26-8338820362aa.png)

是什么原因？

**Comment by Alixiaodian** [comment]
用直接clone git仓库的方法安装是可以的，但把项目代码拷出来到某个指定的目录下都会出这个问题，所以项目代码跟其所在路径有什么依赖关系吗？

**Comment by afc163** [comment]
node_modules...

**Comment by Alixiaodian** [comment]
@afc163 为什么？貌似项目代码不能放在根目录下，必须多加一层才行，有点奇怪

**Comment by Alixiaodian** [comment]
代码复制丢了文件导致，已解决
