### ISSUE TITLE
组件引入自定义样式（variables.less）编译报错 v2.0ban

### ISSUE THREAD

**Issue by leonway** [ant-design/ant-design-pro#3560]
![image](https://user-images.githubusercontent.com/30642375/52938777-807bf480-339d-11e9-923b-c0e24b683082.png)
![image](https://user-images.githubusercontent.com/30642375/52938794-8a9df300-339d-11e9-8373-e9b6d016fd2d.png)
variables.less 里面定义了我组件的一些风格 但是引入就会编译失败

**Comment by fifsky** [comment]
一样，如果在less里面使用@import 自己的less文件，就报错，我是使用ant landing page的时候报错

**Comment by leonway** [comment]
> 一样，如果在less里面使用@import 自己的less文件，就报错，我是使用ant landing page的时候报错

![image](https://user-images.githubusercontent.com/30642375/53317145-7f027d00-3905-11e9-81c2-ebfa81fb4422.png)
像这样 ~@/ 代替src/ 就可以用了
