### ISSUE TITLE
.ant-form-explain-holder::before 中content: '\A0';是否是专门设置的一个占位符

### ISSUE THREAD

**Issue by mo-om** [ant-design/ant-design-pro#3561]
.ant-form-explain-holder::before {
    content: '\A0';
    display: inline-block;
    width: 0;
    overflow: hidden;
}
content: '\A0'; 直接占了一个行高，影响样式

**Comment by chenshuai2144** [comment]
@zombieJ  来解答一下

**Comment by zombieJ** [comment]
这个已经 revert 掉了，安装最新的 antd 就行了。
