### ISSUE TITLE
求大神指教，Cannot read property 'call' of undefined，页面手动刷新后可以渲染成功

### ISSUE THREAD

**Issue by LightStarlight** [ant-design/ant-design-pro#3563]
antd pro开发完成发布之后，首页进来后没有问题，但是点击页面异步渲染时就渲染报错，报错如下图
![image](https://user-images.githubusercontent.com/9716889/52949556-94345480-33b7-11e9-8770-b823be0d8ad9.png)
![image](https://user-images.githubusercontent.com/9716889/52949564-9eeee980-33b7-11e9-8be1-c621006bda05.png)

**Comment by xiaohuoni** [comment]
给个可重现例子吧

**Comment by chenshuai2144** [comment]
这个我也碰到过，我是因为依赖的包打包失败了
