### ISSUE TITLE
使用bash启动  更改less文件语法出错，渲染的进度条一直卡到95% 没有任务反应

### ISSUE THREAD

**Issue by mouxiaohuan** [ant-design/ant-design-pro#3565]
修改pages里面的文件时候，当不小心改了less格式不正确时候，热渲染就卡主不动弹了，一直卡在95%

**Comment by mouxiaohuan** [comment]
也不提示任何语法错误

**Comment by mouxiaohuan** [comment]
比如：
body{
background-color:10px
color:red 
}
中间少了一个分号；就一直卡着不动了，需要重启

**Comment by chenshuai2144** [comment]
。。我的插件的锅，你可以删除 plugin.config.js

**Comment by xd19831203** [comment]
遇到了和你同样的问题，LESS如果写错了，就编译不过去，到95就卡住，也不报错……
