### ISSUE TITLE
FormItem中label过长，能否换行显示？

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3566]
设置过formItemLayout，但效果不理想，如下图所示：

![snipaste_2019-02-19_14-21-43](https://user-images.githubusercontent.com/23411433/52994306-12ddd000-3452-11e9-9767-27cbed761e79.png)

当FormItem中label过长，怎么换行处理？效果图如下：

![snipaste_2019-02-19_14-22-15](https://user-images.githubusercontent.com/23411433/52994417-710ab300-3452-11e9-9771-29a7dcfb97a7.png)

**Comment by xiaohuoni** [comment]
可以自己覆盖ant-form-item-label

**Comment by mstao** [comment]
嗯， 这样可以
