### ISSUE TITLE
解析scss问题 为啥解析不了

### ISSUE THREAD

**Issue by Imhemers** [ant-design/ant-design-pro#3568]
安装 gantt-for-react 模块后 编译出如下错误:

--------------
./node_modules/frappe-gantt/src/gantt.scss
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
| $bar-color: #b8c2cc !default;
| $bar-stroke: #8D99A6 !default;
| $border-color: #e0e0e0 !default;
-------------

应该是scss解析不了, 这个我该怎么配置下呢
望大佬赐教

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#sass
