### ISSUE TITLE
防止CSRF

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#3569]
### AntDesignPro 有没有以下集成的解决方案？
后台使用的是SpringBoot，官网解决CSRF的方案，
CSRF token 会放置到
1.Ajax 和JSON 放到header
2.JSP 放进parameters 
### 3.AntDesignPro  应该怎么解决（所有的非get请求）
utils 里的request.js 具体该怎么实现？求大神指点（暂时不考虑路由带参）

**Comment by chenshuai2144** [comment]
你可能需要发起一个请求来获取CSRF，并且保存一下
