### ISSUE TITLE
Feature request:  include api token management 

### ISSUE THREAD

**Issue by andriijas** [ant-design/ant-design-pro#357]
It would be nice if this project includes how to work with api tokens, when user login it can be saved in app model or user model and somehow used with services / utils/request 

thanks

**Comment by chenshuai2144** [comment]
like [redux-auth](https://github.com/lynndylanhurley/redux-auth)?

**Comment by andriijas** [comment]
nah i was thinking something simpler to get the current login in ant pro working. redux auth is overhaul for this project, includes material forms and other unnecessary stuff which will make it confusing for antd users.

**Comment by chenshuai2144** [comment]
ui of course use antd. Function similar? 
A simple manager？

**Comment by andriijas** [comment]
yes, with example login guest/guest or similar, right now you can login by just going to url and even 404 is on logged in pages.

what do you think of adding basic auth that secures logged in pages, otherwise redicting to login and keep auth state in app model or similar. then api can subscribe to model state if there is auth token in there.

**Comment by andriijas** [comment]
```

  namespace: 'login',

  state: {
    status: undefined,
    token: ............
  },

```

other model:

```
  import { fakeChartData } from '../services/api';
      const response = yield call(fakeChartData, payload);
```

How can I wrap fakeChartData to send token from login model?

**Comment by lawrence-peng** [comment]
see #298 @andriijas
