### ISSUE TITLE
上传组件 upload 代理成功,但是前端请求status为canceled

### ISSUE THREAD

**Issue by rellyCheng** [ant-design/ant-design-pro#3572]
![image](https://user-images.githubusercontent.com/22974879/53071724-0d4dbc00-351e-11e9-9567-72db620d5954.png)
调试了一下请求也进来了

但是前端请求状态为 canceled
![image](https://user-images.githubusercontent.com/22974879/53071814-471ec280-351e-11e9-90d0-0c2ba75153c2.png)

代码：
![image](https://user-images.githubusercontent.com/22974879/53072027-e479f680-351e-11e9-9670-99d6c9974c89.png)

请大佬帮我看看是什么原因。这个上传功能昨天还是好的。。。好气哦

**Comment by rellyCheng** [comment]
解决了 
修改前：
https://user-images.githubusercontent.com/22974879/53072027-e479f680-351e-11e9-9670-99d6c9974c89.png
修改后：
![image](https://user-images.githubusercontent.com/22974879/53073912-56087380-3524-11e9-8219-a573fac4ff1b.png)
就改了一下button 的是否隐藏的写法  就正常了
反复确认了好多遍  就是因为这个写法的原因,
但是不明白是为什么,因为老的写法昨天还是正常的

**Comment by afc163** [comment]
升级 antd 到最新版本即可。
