### ISSUE TITLE
如何根据接口返回的结果，做出合适的提示

### ISSUE THREAD

**Issue by doterme** [ant-design/ant-design-pro#3574]
项目中我有一些新增/修改/删除操作，执行成功之后我想给用户一些提示，我原来把提示的代码放到了effects中，ESLint提示不要把UI的代码放到model中，那我如何在页面中能根据后台返回的结果做出不同的提示呢？前提是满足ESlint

**Comment by uv-w** [comment]
在传参数时，同时可以传一个callback

**Comment by chenshuai2144** [comment]
你的提示写的很复杂吗？
`message.error("")` 这种的是不会出发 eslint 的

**Comment by xiaohuoni** [comment]
如果是统一的错误，可以在request处理，如果是单个业务的逻辑可以类似
ui
```js
this.props.dispatch(action).then(data=>{
     // 在这里处理
})
```
model effect
```js
*effect-name({ payload: parameter }, { call, put, select }) {
  return data;
},
```

**Comment by doterme** [comment]
@xiaohuoni 谢大佬
