### ISSUE TITLE
向服务端发请求，请求没有cookie

### ISSUE THREAD

**Issue by adlabin03** [ant-design/ant-design-pro#3575]
已经成功配置proxy，可以向服务端发起请求，服务端也可以正常接收请求并响应。服务端采用spring boot+shiro验证。
问题：pro登录成功后，发起一个获取当前用户的信息，服务端从session获取当前用户并返回。pro端发起的请求并没有带cookie，所以shiro验证过不了，也没法获取判断当前登录用户，获取session。
是跨域造成的问题还是别的什么问题？前端小白，请大神指教。

**Comment by yinbanghui** [comment]
遇到同样的问题

**Comment by yinbanghui** [comment]
@sorrycc

**Comment by yinbanghui** [comment]
代理到后端服务器后，本地起的服务为localhost:8080,代理后的url地址也是localhost:8080，URL无法自动带上Cookie参数。解决办法，修改hosts文件配置一个域名
比如： 127.0.0.1            dev.develop.com
然后直接访问dev.develop.com:8080
由于接口地址已经改为有个假的域名，Cookie就能带上，问题解决。
@adlabin03

**Comment by chenshuai2144** [comment]
跨域是没有 cookie 的。

**Comment by adlabin03** [comment]
采用了ngnix反向代理
1.ngnix配置
server {
        listen       8001;
        server_name  localhost  ;
        location /server {
	    proxy_redirect off;
            proxy_set_header Host  $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
            proxy_pass  http://localhost:4030/server;  #请求转向服务端地址	
        }
		
	location  / {  
	    proxy_redirect off;
            proxy_set_header Host  $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_pass  http://localhost:8000;  #请求pro地址
      
        } 
    }
2.pro项目中proxy配置注释掉
访问localhost:8001/server/xxx 获取的是服务端数据
访问localhost:8001/xxxx  获取的是mock数据（xxxx !='server'）
访问localhost:8000/xxxx 获取的都是mock数据（xxxx 任意）
@yinbanghui 

不过有一点点问题，有时候登录特慢，还会有一些xhr? eventsource? 之类的请求

**Comment by xiaohuoni** [comment]
好像跨域cookie可以通过设置头部Access-Control-Allow-Credentials，没有真正用过，不知道行不行

**Comment by Fea-Sin** [comment]
打开跨域貌似不能解决问题
ant-design-pro 如何配置 webpack 启动时打开ip地址和端口呢
devServer: { 
  host:’xxxx’, 
  port:8083
},
配置了N多遍，尝试好多种方法都不行，包括 
umi start --port=8080 --allow-hosts xxxx 等，求大神指示

**Comment by xiaohuoni** [comment]
@Fea-Sin 
```sh
PORT=3000 umi dev
```
这是你要的吗https://umijs.org/zh/guide/env-variables.html

**Comment by Fea-Sin** [comment]
@xiaohuoni 

启动时的 host 如何配置呢，因为我们接口是通过ip地址形式提供的，我想将页面启动 host 配置成跟后端一样的ip，这样登陆后浏览器就会携带cookies

ant-design-pro 默认启动是localhost，这个配置在哪里呢，如何配置呢，请教大神

**Comment by xiaohuoni** [comment]
host指的是你文件存放的位置，配置host是什么意思？你要和服务端同源，需要服务端提供容器。好像需要build之后，转移过去。或者服务端在你本地启动。我的理解没错误的话，你这需求有问题

**Comment by Fea-Sin** [comment]
@xiaohuoni  
你理解的没有问题，可以把应用打包后部署测试，但是在开发体验很差，修改内容必须部署测试
我需求的是 webpack 会启动本地服务器，默认是地址是localhost，更改默认配置应该是修改webpack-dev-server，
`devServer: { 
   host:’172.23.0.1’, 
   port:80883
},
`
 因为ant-design-pro 默认是用 umi 打包，umi 集成了weback配置，很多配置细节都隐藏了，我想问ant-design-pro 中如何配置 webpack-dev-server， 默认以 http://172.23.0.1:8083 启动本地服务。谢谢

**Comment by xiaohuoni** [comment]
```sh
HOST=xxx umi dev
```
这个我刚刚发给你的里面就可以配置了。https://umijs.org/zh/guide/env-variables.html#host

**Comment by Fea-Sin** [comment]
@xiaohuoni  谢谢
