### ISSUE TITLE
使用BlankLayout建立新界面报错

### ISSUE THREAD

**Issue by JerryMissTom** [ant-design/ant-design-pro#3579]
使用提供的BlankLayout新建页面，页面很简单，就是显示几个字。console里报错如下：
<img width="1421" alt="123" src="https://user-images.githubusercontent.com/15966403/53150935-c4186d80-35ec-11e9-96cf-a7525c56327f.png">

我猜测是BlankLayout的Bug，
```
import React from 'react';

export default props => <div {...props} />;  // 这里解构赋值，而props包括了children，history，location，staticContext等属性，故报错：React does not recognize the `staticContext` prop on a DOM element.
```
我将其代码修改如下：
```
import React, { PureComponent } from 'react';

class BlankLayout extends PureComponent {
    render() {
        return (<div>{this.props.children}</div>);
    }
}

export default props => <BlankLayout {...props} />;

```
则可以解决此问题。

**Comment by chenshuai2144** [comment]
这个是 react 的 warning，因为你把 react 的 props 赋值给了 dom。dom 是没有这个属性的。
算是一个约定，建议不要 
`export default props => <div {...props} />;`

**Comment by JerryMissTom** [comment]
@chenshuai2144  你们的代码是`export default props => <div {...props} />;`应该需要修改。
