### ISSUE TITLE
eslintrc问题？

### ISSUE THREAD

**Issue by zhuanglong** [ant-design/ant-design-pro#358]
我使用了promise，eslintrc出现以下提示
'Promise is not supported in Opera Mobile 12.1, Opera Mini all, IE Mobile 10, IE 11, Blackberry Browser 7 (compat/compat)'

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/.eslintrc#L55-L57

https://github.com/amilajack/eslint-plugin-compat

**Comment by sunnysk** [comment]
@afc163 还是有同样问题

**Comment by xiaofengqqcom123** [comment]
@sunnysk 最后你是怎么解决的啊？安装了一个插件吗

**Comment by Nemo0915** [comment]
ant-design-pro/.eslintrc
` 
"settings": { 
   "polyfills": ["fetch", "promises"] 
 }`
这样就没问题了

**Comment by tommyspot** [comment]
> ant-design-pro / .eslintrc
> ` "settings": { "polyfills": ["fetch", "promises"] }`
> so that's no problem

Should be ` "settings": { "polyfills": ["fetch", "Promise"] }`
