### ISSUE TITLE
Charts图表的<Pie />组件中，当percent={100}时，图上有一条缝

### ISSUE THREAD

**Issue by GroupOfStar** [ant-design/ant-design-pro#3581]
### 问题描述：

Charts图表的<Pie />组件中，当`percent={100}`即占比为100%时，在饼图中间会有一条缝（鼠标悬停在上面，才会消失）。

### Demo地址：

https://codesandbox.io/s/m36znoj1xp

### 环境

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | v16.6.3 |
| System | Window 10 |
| Browser | Google Chrome 版本 70.0.3538.110（正式版本） （64 位） |

### 期待

1. 占比为100%时，样式正常显示，无缝；
2. 另外，建议 加一个属性能控制：“鼠标点击占比饼图时，图形会移动的交互特效”；

**Comment by harry0071** [comment]
+1，我也有同样的问题。
当percent={100}时，Pie不能完全闭合，会有条缝。

**Comment by chenshuai2144** [comment]
使用最新的 g2 或者 bizchart 就好了。
https://github.com/ant-design/ant-design-pro/blob/master/src/components/Charts/AsyncLoadBizCharts.js
