### ISSUE TITLE
Login组件关于回车的问题

### ISSUE THREAD

**Issue by coppyC** [ant-design/ant-design-pro#3585]
提交按钮的类型是 submit ，可是在Login.UserName之类的组件按下回车，却没有触发Login的表单提交事件，按H5的默认事件来说，应该是会触发的。
像，如果在Login里面加一个普通的input，或antd的Input，都是可以触发的
而现在像Login.Password却要通过onPressEnter，来做这些事件.
我想知道这是用了什么魔法，让它失去原本默认的行为。
翻了半天代码也没找到问题的关键，只能来这里问问看了。

**Comment by coppyC** [comment]
https://github.com/ant-design/ant-design-pro/blob/6e97ea9299a83f2b261f276d1d32bff018ffc5a8/src/components/Login/LoginItem.js#L122

打到原因了
``` jsx
      <FormItem>
        {getFieldDecorator(name, options)(<Input {...customprops} {...otherProps} />)}
      </FormItem>

```
中 otherProps 有form对象，传入Input 后，导致其失去默认行为。

而antd 中又通过otherProps继续传递参数
https://github.com/ant-design/ant-design/blob/fb6a493f1180b109fbacb288e7175deac942665d/components/input/Input.tsx#L290
```jsx
      <input
        {...otherProps}
        value={fixControlledValue(value)}
        onChange={this.handleChange}
        className={classNames(this.getInputClassName(prefixCls), {
          [className!]: className && !addonBefore && !addonAfter,
        })}
        onKeyDown={this.handleKeyDown}
        ref={this.saveInput}
      />
```

**Comment by qzmer1104** [comment]
怎么关了呢？我也想知道

**Comment by coppyC** [comment]
@qzmer1104 好像我在2楼说的挺明白的了，andpro内部有个form字段传给antd的input ，然后antd又把from传给原声组件，然而input的form是有其他含义的，可以在ndm上面查，然后回车就不会提交到这个表单了

**Comment by ycloud** [comment]
> 怎么关了呢？我也想知道

ant-design-pro/src/components/Login/LoginItem.js
把 form 给覆盖了，重设为 undefined，这样生成出来 的dom就没有form属性，可以直接回车提交
![image](https://user-images.githubusercontent.com/2016768/57218924-2e0bb500-7029-11e9-84ac-4d29dd7d5379.png)
