### ISSUE TITLE
注册页面，同行输入框错层

### ISSUE THREAD

**Issue by Mantak** [ant-design/ant-design-pro#359]
如题

**Comment by nikogu** [comment]
最好配个截图

**Comment by Mantak** [comment]
[
![jietu20171205-232534](https://user-images.githubusercontent.com/63792/33614963-c2cb6e2c-da13-11e7-8a40-52399db932f2.jpg)
](url)

**Comment by lvhaohua** [comment]
![image](https://user-images.githubusercontent.com/27878751/33647283-526425b2-da8f-11e7-9f10-d6c37991e212.png)

**Comment by lvhaohua** [comment]
这么明显的显示问题 居然还发正式版。。。 也太水了吧

**Comment by chenshuai2144** [comment]
@Mantak 
环境是

**Comment by afc163** [comment]
http://localhost:8000/#/user/login

https://github.com/ant-design/ant-design/pull/8415/

@ddcat1115 这种情况有问题。

**Comment by afc163** [comment]
same as #8459

**Comment by Mantak** [comment]
@ chenshuai2144  mac node 1.9.2 yarn 1.3.2 firefox浏览器 ， clone下载，yarn && yarn start就这样

**Comment by chenshuai2144** [comment]
@Mantak   firefox版本了  最新的firefox是没有问题.

**Comment by Mantak** [comment]
@chenshuai2144  firefox是最新版的，并且chrome里也是错层，错误的效果很统一，所以，可以肯定的是，不是浏览器的问题

**Comment by chenshuai2144** [comment]
@Mantak  访问我们的预览页面也是这样的?

**Comment by Mantak** [comment]
前天，你们刚升3.0的时候，我好像访问过是错层的，现在好了。昨天clone的项目，装上还是错层。

另外问一个问题，你们的import styles from ‘xx.less’。这个功能是用的哪个包，我好像见过，给忘记了，还望指点

**Comment by chenshuai2144** [comment]
@Mantak  [css-modules](https://github.com/css-modules/css-modules)

**Comment by Mantak** [comment]
@chenshuai2144  谢谢。 刚才pull了一下项目，还是错层，但是你们官方演示版本是正确的

**Comment by chenshuai2144** [comment]
@Mantak   也许是你的配置问题.
你可以删除 然后重新clone.

**Comment by Mantak** [comment]
@chenshuai2144  刚新装过，启动以后，还是错层
 git clone https://github.com/ant-design/ant-design-pro.git --depth=1 pro2
cd pro2
yarn 
![jietu20171207-115616](https://user-images.githubusercontent.com/63792/33698155-ad8981a6-db45-11e7-8c3d-9292fb56067f.jpg)

**Comment by chenshuai2144** [comment]
@Mantak   再现了这个问题, thanks

**Comment by chenshuai2144** [comment]
@afc163  按照他的方式运行之后.
![image](https://user-images.githubusercontent.com/8186664/33698336-ccda40b2-db46-11e7-8d67-4cb576cd1e9c.png)


左边的下拉选择框,向上浮动了4个像素.
也许是ant.design的问题.

**Comment by Mantak** [comment]
@chenshuai2144  您客气了，谢谢你们伟大的工作，谢谢您的热情指导

**Comment by ebilegsaikhan** [comment]
just remove the top distance.
```
form {
  :global {
    .ant-input-lg, .ant-input-number-lg, .ant-cascader-picker-large, .ant-select-lg, .ant-calendar-picker-large, .ant-time-picker-large, .ant-radio-group-large, .ant-input-group-wrapper-lg .ant-input-group-addon {
      top: 0;
    }
  }
}

```

**Comment by afc163** [comment]
我下午改一下。

**Comment by LayGit** [comment]
+1 就是那个 `-4px` 的问题，烦请尽快修改，目前暂时采用极不优雅的覆盖方式。

**Comment by chenshuai2144** [comment]
@LayGit  给input组建 也设置 size="larger" 会好很多

**Comment by ddcat1115** [comment]
- input group 错位的问题在这里已修复 https://github.com/ant-design/ant-design-pro/commit/907f1a5cea39cb3f4c10fb07bf87aa6b2a0b4eaf

- button 与 input 对不齐，以及 input 前后缀上下不居中是同一个问题，在 antd 中修复 https://github.com/ant-design/ant-design/pull/8495   本周发布 patch 之后重新 install 即可

**Comment by afc163** [comment]
Fixed in antd@3.0.1
