### ISSUE TITLE
why back to antd 3.13.0 from 3.13.5

### ISSUE THREAD

**Issue by eric-vv** [ant-design/ant-design-pro#3595]
I notice that  the antd is back to  3.13.0 version in the last master  of ant d pro, why?

**Comment by afc163** [comment]
Can you understand what you typed here..?

**Comment by ericfct** [comment]
In the latest download of Ant design-pro, version antd changed from 3.13.5 to 3.13.0.

**Comment by afc163** [comment]
It is not true, we don't change antd version back to any version.

**Comment by eric-vv** [comment]
I'm a user of Ant design pro. I'm just confused about something I don't understand. Although your reply is a little rude, it also solves my problem.  Thank you !
