### ISSUE TITLE
How to add a category level in sideNav(在导航中添加类别)

### ISSUE THREAD

**Issue by Doug44444444** [ant-design/ant-design-pro#3596]
Hi Team,

I have a question related to the sideNav. Is it possible to have a category level within Ant Design pro so that it will not hide the lower level and also don't have any link? Any params can do this in router.config? Similar to the attached your office website(Introduction, Advanced).

我有一个关于边导航栏的问题，请问是否可以在routes中设置参数而把顶级level改为一个类别的名字，但并不是真正的导航，而且也不会设置自导航折叠，而是直接显示出来。就像在附件中你们官方网站中的Introduction和Advanced。

Thanks.

![screen shot 2019-02-24 at 10 24 15 pm](https://user-images.githubusercontent.com/13776051/53318142-268a9b80-3883-11e9-8c9e-40f2e2c99f5c.png)

**Comment by chenshuai2144** [comment]
增加一个 type 参数，然后 分组他们就好了。但是需要改动的代码很多。
