### ISSUE TITLE
打包之后的文件太大

### ISSUE THREAD

**Issue by xitele007** [ant-design/ant-design-pro#3598]
1、npm run build之后的文件太大
ant design pro 2.1.1打包之后，单单umi.js就1.5M，vendors.async更是快3M，请问有什么办法可以尽量压缩到1M以内么？
2、应用版本更新问题
 生产环境用的nginx，打包之后文件发布到nginx（nginx关闭缓存）之后。如果应用有新的更新。打包后的文件覆盖之前发布的文件。刷新页面还是老的页面。除非清除浏览器缓存才起作用

**Comment by xitele007** [comment]
![qq 20190225162848](https://user-images.githubusercontent.com/36128836/53323951-82543380-391a-11e9-89c9-9768bb052f94.png)
附npm run analyze的结果

**Comment by vellengs** [comment]
gzip 了吗？

**Comment by xitele007** [comment]
> gzip 了吗？发布到 nginx （nginx 启用了Gzip)

启用了，启用之后，vendors.async+umi.js也有1M多

**Comment by chenshuai2144** [comment]
可以试试我们最新的代码。bizichart 就很昂贵

**Comment by xitele007** [comment]
问题始终没有解决，看样子这东西用的人不多。。

**Comment by Topgt** [comment]
官网示例umi.js才400k，直接build master分支后的umi.js 1M多，这是什么情况啊，![图片](https://github.com/Topgt/base/blob/master/WechatIMG1.jpeg?raw=true),![图片](https://github.com/Topgt/base/blob/master/WechatIMG2.jpeg?raw=true)

这个问题有解决方案吗，这东西要是1M多没发上线啊

**Comment by chenshuai2144** [comment]
官方的 umi 开了 gzip 。gzip可以减少 百分90 的大小

**Comment by HHH-Disguiser** [comment]
![image](https://user-images.githubusercontent.com/20159237/67448303-28db0a80-f649-11e9-8401-5a7ce1636608.png

**Comment by jinyu73** [comment]
新公司项目，打包后文件54M。。。。。。
