### ISSUE TITLE
错误页图片被拉伸

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#36]
http://preview.pro.ant.design/#/exception/403
http://preview.pro.ant.design/#/exception/404
http://preview.pro.ant.design/#/exception/500

**Comment by nikogu** [comment]
![image](https://user-images.githubusercontent.com/1179603/32153254-572827c0-bcf7-11e7-99be-299e1f0e5101.png)


还有这个..

**Comment by ddcat1115** [comment]
加了一些响应式样式，屏幕太小时采用竖版

<img width="977" alt="2017-10-31 5 21 56" src="https://user-images.githubusercontent.com/7017767/32216928-5eb4a0a2-be61-11e7-863a-1cdc62a9272b.png">
<img width="374" alt="2017-10-31 5 25 47" src="https://user-images.githubusercontent.com/7017767/32216929-5efba844-be61-11e7-9cc8-5a5ace28c907.png">

**Comment by afc163** [comment]
在 Firefox 58 下仍然有拉伸问题。

https://preview.pro.ant.design/#/exception/403

**Comment by afc163** [comment]
@ddcat1115
