### ISSUE TITLE
tabs多标签问题 请教一下帅哥 @chenshuai2144

### ISSUE THREAD

**Issue by zhangshuai0101** [ant-design/ant-design-pro#3603]
目前遇到的问题如下
![tabs](https://user-images.githubusercontent.com/40013310/53403681-0c6dcc00-39ef-11e9-8769-ddb7514aa31d.gif)
当点击table时，因为router配置的文件直接指向当前路由，不会出现任何问题，当点击分步表单时，路由会经过一次重定向，页面无法加载，并且控制台报 Warning
![image](https://user-images.githubusercontent.com/40013310/53403846-666e9180-39ef-11e9-929b-d88cd68e4c5a.png)
想问一下大家有没有解决思路？

**Comment by chenshuai2144** [comment]
我们现在是不支持的多标签页的。

**Comment by zhangshuai0101** [comment]
帅哥 ， 帮忙给个思路吧？ @chenshuai2144

**Comment by zhangshuai0101** [comment]
> 我们现在是不支持的多标签页的。

咱们有计划做这个吗？

**Comment by chenshuai2144** [comment]
暂时没有。我们主要的工作是 v4

**Comment by Unsell** [comment]
@zhangshuai0101 你好，我想请问下你这个修改tabs展示实现了吗？可以发给我学习一下吗？

**Comment by donkeyqiu** [comment]
> > 我们现在是不支持的多标签页的。
> 
> 咱们有计划做这个吗？

我觉得有一个方法可以做，把数据存在redux里面，然后做一个tab组件（只起到显示作用，页面还是重新加载），tablist里面判断有没有存在这个tab,有的话就直接redux里提取数据，这样感觉也没违背原来的理论

**Comment by Fengly0503** [comment]
公司项目也有多标签功能的需求，看了各位的实现感觉还是不太满足自己的需求，就自己写了一个基于Ant design pro 4 + 路由拦截的方案，解决了一些标签切换、关闭、路由关联、相同类型不同数据详情页、url直接访问指定标签等问题，有兴趣的兄弟可以瞅瞅 [多标签实现地址](https://github.com/Fengly0503/ant_pro_tabs)

![demo-1](https://user-images.githubusercontent.com/7435119/77248172-5cf73d80-6c72-11ea-9c71-202cc79a6450.jpg)
![demo-2](https://user-images.githubusercontent.com/7435119/77248174-5ec10100-6c72-11ea-8898-a01b1915e2a8.jpg)
![demo-3](https://user-images.githubusercontent.com/7435119/77248175-5f599780-6c72-11ea-9b5b-ab30f9d46908.jpg)
