### ISSUE TITLE
Mac 样式有问题，在mac上开发样式出现问题

### ISSUE THREAD

**Issue by AngelName** [ant-design/ant-design-pro#3605]
mac os 10.14.3 
ant-design-pro：  "version": "2.1.1",
解决方案 注释根据系统是苹果而优化的代码
  ? {
          // dll: {
          //   include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
          //   exclude: ['@babel/runtime'],
          // },
          hardSource: false,
        }
不知道什么原因希望大神看一下 hardSource 也会报错，网上说可能是hardsource版本问题

**Comment by chenshuai2144** [comment]
你可能需要同步一下新的配置了。
样式出现了什么问题？

**Comment by usercao** [comment]
我也出现了这个问题
