### ISSUE TITLE
修改base后redirect无法正常工作

### ISSUE THREAD

**Issue by anizephyr** [ant-design/ant-design-pro#3607]
在config里配置了base路径后，在系统中退出登陆带出的redirect会包含base的值
再次登陆后会重复base的值导致访问路径不正确
<img width="692" alt="2019-02-27 00 10 39" src="https://user-images.githubusercontent.com/26772673/53427887-b61b8000-3a24-11e9-9dd9-6cf10cac0615.png">
<img width="856" alt="2019-02-27 00 11 21" src="https://user-images.githubusercontent.com/26772673/53427891-b9167080-3a24-11e9-9674-a158069b8b22.png">

<img width="414" alt="2019-02-27 00 11 42" src="https://user-images.githubusercontent.com/26772673/53427906-bd428e00-3a24-11e9-9e8e-dd667d3cbc70.png">
#2865 并没有解决问题

**Comment by chenshuai2144** [comment]
你可能需要排查一下问题的出现在哪里，我已经无法再现

**Comment by anizephyr** [comment]
if (**redirectUrlParams.hash === '' &&** redirectUrlParams.origin === urlParams.origin) {
            redirect = redirect
              .substr(urlParams.origin.length)
              **.substr(urlParams.pathname.replace('/user/login', '').length);**
            if (redirect.match(/^\/.*#/)) {
              redirect = redirect.substr(redirect.indexOf('#') + 1);
            }
          } else {
            window.location.href = redirect;
            return;
          }

**Comment by chenshuai2144** [comment]
有兴趣搞个 pr 吗？

**Comment by zkamisama** [comment]
you can try
`
const base = window.routerBase || '/'
if (redirect) {
          const redirectUrlParams = new URL(redirect);
          console.log(redirectUrlParams)
          if (redirectUrlParams.origin === urlParams.origin) {
            redirect = redirect.substr(urlParams.origin.length);

            if (redirect.match(/^\/.*#/)) {
              redirect = redirect.substr(redirect.indexOf('#') + 1);
            }
            if(base)
            {
              redirect = redirect.replace(base, '/')
            }
          } else {
            window.location.href = redirect;
            return;
          }
        }`

**Comment by zkamisama** [comment]
@anizephyr 我也遇到同样的问题， 我是这样解决的

    const base = window.routerBase || '/'
    if (redirect) {
        const redirectUrlParams = new URL(redirect);
        console.log(redirectUrlParams)
        if (redirectUrlParams.origin === urlParams.origin) {
        redirect = redirect.substr(urlParams.origin.length);

        if (redirect.match(/^\/.*#/)) {
            redirect = redirect.substr(redirect.indexOf('#') + 1);
        }
        if(base)
        {
            redirect = redirect.replace(base, '/')
        }
        } else {
        window.location.href = redirect;
        return;
        }
    }
