### ISSUE TITLE
在 tsx 文件中使用 as 语法断言类型报错

### ISSUE THREAD

**Issue by RunningCoderLee** [ant-design/ant-design-pro#3608]
在项目中直接创建 `.tsx` 文件后使用 `as` 语法断言类型时会抛出解析错误的提示，如下图

![image](https://user-images.githubusercontent.com/13218863/53458913-d70ac200-3a72-11e9-8c24-75219bbe979a.png)

貌似是因为 eslint 的 `parser` 没有设置成 `typescript` 的原因，但是如果将 `babel-eslint` 换为 `typescript` 后又会出现其他错误，请问这个有没有什么好的解决方案？

**Comment by chenshuai2144** [comment]
用 tslint，pro 中已经增加了。或者看这个文章
https://medium.com/palantir/tslint-in-2019-1a144c2317a9
