### ISSUE TITLE
Pie 图表在手机模式下，存在自适应的问题

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#361]
如图：
![image](https://user-images.githubusercontent.com/12181423/33585800-1760993a-d9a1-11e7-8602-be78a0911154.png)

**Comment by liumin1128** [comment]
不太建议直接用于移动端，有专门的antd-mobile

**Comment by nikogu** [comment]
@hqwlkj 这个建议直接将三个竖直排列吧，这么小，字太小了也看不清

**Comment by hqwlkj** [comment]
@nikogu   OK
