### ISSUE TITLE
hard-source-webpack-plugin 编译 .less 文件打印警告

### ISSUE THREAD

**Issue by Hubmeat** [ant-design/ant-design-pro#3610]
部分报错信息如下

[hardsource:dc97bdf3] Could not freeze ./node_modules/_antd@3.13.6@antd/es/time-picker/style/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./node_modules/_antd@3.13.6@antd/es/tooltip/style/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./node_modules/_antd@3.13.6@antd/es/tree/style/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./node_modules/_antd@3.13.6@antd/es/upload/style/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./node_modules/_react-quill@1.3.3@react-quill/dist/quill.snow.css: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./node_modules/_umi-build-dev@1.5.5@umi-build-dev/lib/plugins/404/NotFound.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/ChartCard/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/Field/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/MiniProgress/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/Pie/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/Radar/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/TagCloud/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/TimelineChart/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/WaterWave/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Charts/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Exception/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/GlobalFooter/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/GlobalHeader/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/HeaderSearch/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Login/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/MemberInfo/baseInfo.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/MemberInfo/capitalInformation.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/MemberInfo/capitalPackage.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/MemberInfo/kycInfo.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/NoticeIcon/NoticeList.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/NoticeIcon/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/NumberInfo/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/PageHeader/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/PageHeaderWrapper/GridContent.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/PageHeaderWrapper/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Result/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/SettingDrawer/ThemeColor.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/SettingDrawer/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/SiderMenu/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/TopNavHeader/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/components/Trend/index.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/global.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/layouts/Header.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/layouts/UserLayout.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/pages/ExchangeArea/AnnouncementManagement/AnnouncementPublish/announcementPublish.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/pages/ExchangeArea/AnnouncementManagement/SortManagement/sortManagement.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/pages/ExchangeArea/AuthManagement/RoleManagement/roleManagement.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/pages/ExchangeArea/AuthManagement/UserManagement/userManagement.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/pages/ExchangeArea/ClienteleService/OrderManagement/orderManagement.less: Cannot read property 'hash' of undefined
[hardsource:dc97bdf3] Could not freeze ./src/pages/ExchangeArea/ContractManagement/ProductConfiguration/productConfiguration.less: Cannot read property 'hash' of undefined

**Comment by chenshuai2144** [comment]
pro 已经删除 hardcode，他造成了一些无法修复的问题。
https://github.com/ant-design/ant-design-pro/pull/3358
