### ISSUE TITLE
关于主题配置问题

### ISSUE THREAD

**Issue by XYCodeTerminator** [ant-design/ant-design-pro#3611]
src/defaultSettings.js 文件为什么用 module.exports ,  为什么用 export default 会报错

**Comment by chenshuai2144** [comment]
src/defaultSettings.js 是通过 require 来获取的。用的
最新的 umi 已经支持了，甚至可以用 ts

**Comment by XYCodeTerminator** [comment]
> src/defaultSettings.js 是通过 require 来获取的。自然需要用 node 的模块方式。
> 最新的 umi 已经支持了，甚至可以用 ts

还是不太懂，为什么 config/router.config.js 可以用 module.exoports ？ 而且在 config.js 中都是用 import 引入的。

**Comment by xiaohuoni** [comment]
这个问题，好像是之前umi上的config加载的文件需要是es5的。你现在可以改成
export default，但是需要文件放到config目录下面，因为还有一个问题。https://github.com/umijs/umi/issues/2037
