### ISSUE TITLE
输入域名端口加public文件路径访问到静态资源这是如何实现的？

### ISSUE THREAD

**Issue by bobsivian** [ant-design/ant-design-pro#3612]
在地址栏中输入域名端口+public目录下的文件路径就能够直接访问到public目录下的文件，请问这是如何实现的？
如public目录下有文件：/img/demo.jpg;
输入：http://localhost:8000/img/demo.jpg
就能获取到demo.jpg这是如何做到的？
相关核心代码在哪里？
能否详细说下原理？

**Comment by xiechao1211** [comment]
webpack的静态资源目录，被封装到了umi当中

**Comment by chenshuai2144** [comment]
webpack static
