### ISSUE TITLE
ReferenceError: BizCharts is not defined

### ISSUE THREAD

**Issue by chenqq86** [ant-design/ant-design-pro#3614]
打算自己二次封装图表组件，用官方的代码先试下，然后一直报 **ReferenceError: BizCharts is not defined**

打开 https://cdn.jsdelivr.net/  都正常的

`import React, { PureComponent }  from 'react';
import { Chart, Geom, Axis, Tooltip, Legend } from 'bizcharts';

class Attendance extends PureComponent {

  render() {

    // 数据源
    const data = [
      { genre: 'Sports', sold: 275, income: 2300 },
      { genre: 'Strategy', sold: 115, income: 667 },
      { genre: 'Action', sold: 120, income: 982 },
      { genre: 'Shooter', sold: 350, income: 5271 },
      { genre: 'Other', sold: 150, income: 3710 }
    ];

    // 定义度量
    const cols = {
      sold: { alias: '销售量' },
      genre: { alias: '游戏种类' }
    };

    return(
      <div>
        <Chart width={600} height={400} data={data} scale={cols}>
          <Axis name="genre" />
          <Axis name="sold" />
          <Legend position="top" dy={-20} />
          <Tooltip />
          <Geom type="interval" position="genre*sold" color="genre" />
        </Chart>
      </div>
    )
  }
}

export default Attendance;
`

最的注释掉
config.js里面的就可以了
externals: {
    '@antv/data-set': 'DataSet',
    // bizcharts: 'BizCharts',
  },

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/Charts/AsyncLoadBizCharts.js

https://github.com/ant-design/ant-design-pro/blob/master/src/pages/Dashboard/Workplace.js

看看这两个的用法 bizchart 是很大的包，打进去对体积影响很大

**Comment by lucoxlee** [comment]
@chenshuai2144 你好，但是放在externals为什么会报错

**Comment by LukerSpringtree** [comment]
> @chenshuai2144 你好，但是放在externals为什么会报错

import { AsyncLoadBizCharts } from '@/components/Charts/AsyncLoadBizCharts';
我知道 为什么 你   BizCharts is not defined
因为 旧版本的 antd-pro 异步加载 的
他有一个 高阶 组件名为 AsyncLoadiBizCharts
你在调用 UI组件的 时候没有 用这样的一个组件

**Comment by dadawanan** [comment]
问下BizCharts externals 应该怎么配置，不管怎么弄都是`bizcharts is not defined`

**Comment by tommyspot** [comment]
Anybody has a solution to resolve this issue?
