### ISSUE TITLE
在浏览器地址栏直接输入无权访问页面的url，授权拦截会失败

### ISSUE THREAD

**Issue by 54huanan** [ant-design/ant-design-pro#3617]
在浏览器地址栏直接输入无权访问页面的url，授权拦截会失败，会显示无权访问的页面。
Basiclayout.js中
const routerConfig = this.matchParamsPath(pathname, breadcrumbNameMap)
上述方法中不应该用breadcrumbNameMap，应该用原始的router.config.js的数据。breadcrumbNameMap是过滤之后的，未授权的entry被filter out了，routerConfig会返回undefined。

**Comment by Jiangwr** [comment]
请问一下，能否控制某个页面不经过登录的权限验证直接进入的
![image](https://user-images.githubusercontent.com/19362571/53537138-eb6abf80-3b43-11e9-8df9-26af40f29773.png)

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/pull/3587 这个提交之后，没有这个问题了
