### ISSUE TITLE
jest error

### ISSUE THREAD

**Issue by SevenGuns** [ant-design/ant-design-pro#3626]
MacOS 10.14.1, NodeJS v10.15.1
cnpm i
npm run test:all
`Validation Error:

  Options: setupTestFrameworkScriptFile and setupFilesAfterEnv cannot be used together.
  Please change your configuration to only use setupFilesAfterEnv.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html`
![20190227205523](https://user-images.githubusercontent.com/23354928/53491810-3e0b9380-3ad2-11e9-9b75-b4af2d67f8d7.png)

_Originally posted by @SevenGuns in https://github.com/ant-design/ant-design-pro/issues/3543#issuecomment-467852125_

**Comment by chenshuai2144** [comment]
感觉像是依赖包不匹配，试着重新安装呢？

**Comment by xiaohuoni** [comment]
哇，这个背景是怎么搞出来的？

**Comment by SevenGuns** [comment]
> 感觉像是依赖包不匹配，试着重新安装呢？

重新安装过了，您这边直接clone下来npm run test:all不会出现这种情况吗？

**Comment by chenshuai2144** [comment]
已经修复了，重新安装一下
