### ISSUE TITLE
请问一下，能否控制某个页面不经过登录的权限验证直接进入的

### ISSUE THREAD

**Issue by Jiangwr** [ant-design/ant-design-pro#3627]
![image](https://user-images.githubusercontent.com/19362571/53537706-d5f69500-3b45-11e9-94f4-b84c5fd407eb.png)

**Comment by Jiangwr** [comment]
就是把此页面公开，游客也可访问

**Comment by Jiangwr** [comment]
还有一个问题是，如果页面可以访问了，页面中所需的参数，如何传递比较合适呢

**Comment by chenshuai2144** [comment]
页面如果需要分享，最好使用 url 传参

> 把此页面公开，游客也可访问，你可以设置一个默认权限就好了

**Comment by xiaohuoni** [comment]
现在的登录页面，不就是所有人都能访问吗？这一样的吧？

**Comment by Jiangwr** [comment]
> 页面如果需要分享，最好使用 url 传参
> 
> > 把此页面公开，游客也可访问
> 
> 你可以设置一个默认权限，每个人都有这个权限

我现在是这样操作的，跳转登录页面的时候在url加了一个参数，如果有该参数，则默认登录，并且登录返回的角色为游客。

**Comment by Jiangwr** [comment]
> 现在的登录页面，不就是所有人都能访问吗？这一样的吧？

是的，我再看看应该在哪里设置

**Comment by xiaohuoni** [comment]
现在的是在路由配置里面。
