### ISSUE TITLE
如何在组件之外的作用域获取react-router中的location,history,match等信息

### ISSUE THREAD

**Issue by litao1993** [ant-design/ant-design-pro#3628]

**Comment by imhele** [comment]
window.location

**Comment by litao1993** [comment]
> `window.location`

改了下标题，其实我想获取的是这个信息

**Comment by chenshuai2144** [comment]
这样就不符合 react 的理念了，
你可以在 redux 中管理。https://www.npmjs.com/package/react-router-redux
