### ISSUE TITLE
请问：npm run build 如何不压缩js？使用COMPRESS=none umi build 报错

### ISSUE THREAD

**Issue by xiaojiazu** [ant-design/ant-design-pro#3633]
![image](https://user-images.githubusercontent.com/16448103/53548808-67c5c880-3b6d-11e9-949e-ffeb23102d6f.png)

C:\work\ant-design-pro-master>npm run build

> ant-design-pro@2.2.1 build C:\work\ant-design-pro-master
> COMPRESS=none umi build

'COMPRESS' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.2.1 build: `COMPRESS=none umi build `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-02-28T07_27_00_031Z-debug.log

**Comment by chenshuai2144** [comment]
用这个配置好了
https://umijs.org/zh/config/#uglifyjsoptions

**Comment by xiaojiazu** [comment]
![image](https://user-images.githubusercontent.com/16448103/53566027-13830e80-3b96-11e9-92ab-7cfc8f049ca2.png)

@chenshuai2144 我对这个配置文件不是很熟悉，我配置成   uglifyJSOptions(opts) {
    opts.compress ={};//=false  =none 都试过了
    return opts;
  }, 这样不行，请问我应该改哪个参数？   uglifyOptions: {
    parse: {
      ecma: 8,
    },
    compress: {
      ecma: 5,
      warnings: false,

      // turn off flags with small gains to speed up minification
      arrows: false,
      collapse_vars: false, // 0.3kb
      comparisons: false,
      computed_props: false,
      hoist_funs: false,
      hoist_props: false,
      hoist_vars: false,
      inline: false,
      loops: false,
      negate_iife: false,
      properties: false,
      reduce_funcs: false,
      reduce_vars: false,
      switches: false,
      toplevel: false,
      typeofs: false,

      // a few flags with noticable gains/speed ratio
      // numbers based on out of the box vendor bundle
      booleans: true, // 0.7kb
      if_return: true, // 0.4kb
      sequences: true, // 0.7kb
      unused: true, // 2.3kb

      // required features to drop conditional branches
      conditionals: true,
      dead_code: true,
      evaluate: true,
    },
    mangle: {
      safari10: true,
    },
    output: {
      ecma: 5,
      comments: false,
      ascii_only: true,
    },
  },
  sourceMap: false,
  cache: true,
  parallel: true,
};

**Comment by pxim** [comment]
> 用这个配置好了 https://umijs.org/zh/config/#uglifyjsoptions

https://github.com/umijs/umi/issues/7644 大佬，能不能帮我看下这个问题，我也是 build 压缩出问题；但是奇怪的是，压缩后，在PC端正常，mobile端不正常；要是不压缩 COMPRESS=none，就都正常；

我想既压缩，又想2端都正常，
