### ISSUE TITLE
在Analysis页面中的clearTimeout(this.timeoutId);有啥用

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3637]
https://github.com/ant-design/ant-design-pro/blob/master/src/pages/Dashboard/Analysis.js#L42

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/commit/7c18b657116b4b679104d840d23864e4a0f3e02d#diff-26da869cc44562254aad8a768f8cd46d
```js
this.timeoutId = setTimeout(() => {
        this.setState({
          loading: false,
        });
}, 600);
```

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/commit/27562512414337ad368a622fe7ca22eaf248cf76#diff-26da869cc44562254aad8a768f8cd46d
```diff
- this.timeoutId = setTimeout(() => {
-        this.setState({
-          loading: false,
-        });
-}, 600);
```

**Comment by chenshuai2144** [comment]
是为了让图表慢点渲染.

**Comment by xiaohuoni** [comment]
这个代码不是被你删除了吗？
