### ISSUE TITLE
Include @types/react so IDEs do not show errors

### ISSUE THREAD

**Issue by adam-s** [ant-design/ant-design-pro#364]
The TypeScript files in the Components directory show errors because variables attached to the React object do not resolve. The solution is to `yarn add @types/react` so they are discoverable. (https://www.npmjs.com/package/@types/react)

**Comment by afc163** [comment]
I think you should install `@types/react` cause you have to in a React-TypeScript project, even your don't use `antd` or `ant-design-pro`.
