### ISSUE TITLE
pro.ant.design示例通过添加redirect登陆可被重定向制定网站

### ISSUE THREAD

**Issue by dongkang1993** [ant-design/ant-design-pro#3641]
https://preview.pro.ant.design/user/login?redirect=https://baidu.com
![image](https://user-images.githubusercontent.com/20965177/53613698-dcead980-3c11-11e9-95d1-16393379e987.png)

输入密码后跳到指定网站

![image](https://user-images.githubusercontent.com/20965177/53613741-ff7cf280-3c11-11e9-8afc-1b3fe52084c4.png)

**Comment by xiaohuoni** [comment]
然后呢？这有什么问题？🤦‍♂️

**Comment by afc163** [comment]
要加域名白名单，不然可能有安全风险。

**Comment by dongkang1993** [comment]
> 然后呢？这有什么问题？🤦‍♂️

可能被利用，跳到钓鱼网站或其他不好的

**Comment by chenshuai2144** [comment]
可以加一个设置，只允许跳转相对路径好了，不允许带 https

**Comment by xiaohuoni** [comment]
好像有点道理？
