### ISSUE TITLE
请问要替换页面加载loading图标，具体要改哪些地方

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3642]

**Comment by mstao** [comment]
包括页面加载loading图标，表格数据加载等

**Comment by imhele** [comment]
不使用表格自带的 `loading` 属性，在外面包一层 `<Spin />` 并指定 `indicator` 属性
https://ant.design/components/spin-cn/#components-spin-demo-custom-indicator

**Comment by mstao** [comment]
https://github.com/ant-design/ant-design/issues/15132 我找到了
