### ISSUE TITLE
V2.0部署之后，点击菜单页面空白

### ISSUE THREAD

**Issue by xuwenjin** [ant-design/ant-design-pro#3645]
V2.0部署之后，可以登录进来，但是点击左侧菜单，右边显示空白。控制台没有任何报错，也没发送请求。在本地开发是正常的

**Comment by xiaohuoni** [comment]
点击左侧菜单，url有没有变化？

**Comment by chenshuai2144** [comment]
感觉是你的路由配置错了，没有命中任何 page

**Comment by xuwenjin** [comment]
> 点击左侧菜单，url有没有变化？

点击左侧菜单，url有变化。本地开发都是正常的
