### ISSUE TITLE
请教打包，npm run build 如何不压缩js，使用uglifyJSOptions不生效。

### ISSUE THREAD

**Issue by xiaojiazu** [ant-design/ant-design-pro#3646]
![image](https://user-images.githubusercontent.com/16448103/53631121-c9109900-3c4c-11e9-88fc-dd10579cb2c6.png)
打完包后依旧是压缩后的js

**Comment by zhongjiewu** [comment]
https://umijs.org/config/#uglifyjsoptions

**Comment by zhongjiewu** [comment]
我猜是应该需要些写hash而不是函数？
