### ISSUE TITLE
开发环境访问页面，提示TypeError: _this.load is not a function

### ISSUE THREAD

**Issue by yanghc9** [ant-design/ant-design-pro#3647]
运行npm start ，编译成功，但在浏览器（Google Chrome 版本 72.0.3626.119（正式版本））运行时提示如下错误：
TypeError: _this.load is not a function
new DynamicComponent
node_modules/dva/lib/dynamic.js:67
  64 |     AsyncComponent: null
  65 |   };
  66 | 
> 67 |   _this.load();
     | ^  68 | 
  69 |   return _this;
  70 | }
View compiled
constructClassInstance
node_modules/react-dom/cjs/react-dom.development.js:11312
  11309 |   }
  11310 | }
  11311 | 
> 11312 | var instance = new ctor(props, context);
        | ^  11313 | var state = workInProgress.memoizedState = instance.state !== null && instance.state !== undefined ? instance.state : null;
  11314 | adoptClassInstance(workInProgress, instance);
  11315 | 
View compiled
updateClassComponent
node_modules/react-dom/cjs/react-dom.development.js:14483
  14480 |     workInProgress.effectTag |= Placement;
  14481 |   }
  14482 |   // In the initial pass we might need to construct the instance.
> 14483 |   constructClassInstance(workInProgress, Component, nextProps, renderExpirationTime);
        | ^  14484 |   mountClassInstance(workInProgress, Component, nextProps, renderExpirationTime);
  14485 |   shouldUpdate = true;
  14486 | } else if (current$$1 === null) {
View compiled
beginWork
node_modules/react-dom/cjs/react-dom.development.js:15440
  15437 |     var _Component2 = workInProgress.type;
  15438 |     var _unresolvedProps = workInProgress.pendingProps;
  15439 |     var _resolvedProps = workInProgress.elementType === _Component2 ? _unresolvedProps : resolveDefaultProps(_Component2, _unresolvedProps);
> 15440 |     return updateClassComponent(current$$1, workInProgress, _Component2, _resolvedProps, renderExpirationTime);
        | ^  15441 |   }
  15442 | case HostRoot:
  15443 |   return updateHostRoot(current$$1, workInProgress, renderExpirationTime);
View compiled
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:19108
  19105 |   startProfilerTimer(workInProgress);
  19106 | }
  19107 | 
> 19108 | next = beginWork(current$$1, workInProgress, nextRenderExpirationTime);
        | ^  19109 | workInProgress.memoizedProps = workInProgress.pendingProps;
  19110 | 
  19111 | if (workInProgress.mode & ProfileMode) {
View compiled
workLoop
node_modules/react-dom/cjs/react-dom.development.js:19148
  19145 | if (!isYieldy) {
  19146 |   // Flush work without yielding
  19147 |   while (nextUnitOfWork !== null) {
> 19148 |     nextUnitOfWork = performUnitOfWork(nextUnitOfWork);
        | ^  19149 |   }
  19150 | } else {
  19151 |   // Flush asynchronous work until there's a higher priority event
View compiled
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:149
  146 |     window.event = windowEvent;
  147 |   }
  148 | 
> 149 |   func.apply(context, funcArgs);
      | ^  150 |   didError = false;
  151 | }
  152 | 
View compiled
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:199
  196 | // Synchronously dispatch our fake event. If the user-provided function
  197 | // errors, it will trigger our global error handler.
  198 | evt.initEvent(evtType, false, false);
> 199 | fakeNode.dispatchEvent(evt);
      | ^  200 | 
  201 | if (windowEventDescriptor) {
  202 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:256
  253 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  254 |   hasError = false;
  255 |   caughtError = null;
> 256 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  257 | }
  258 | 
  259 | /**
View compiled
replayUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:18374
  18371 | // Replay the begin phase.
  18372 | isReplayingFailedUnitOfWork = true;
  18373 | originalReplayError = thrownValue;
> 18374 | invokeGuardedCallback(null, workLoop, null, isYieldy);
        | ^  18375 | isReplayingFailedUnitOfWork = false;
  18376 | originalReplayError = null;
  18377 | if (hasCaughtError()) {
View compiled
renderRoot
node_modules/react-dom/cjs/react-dom.development.js:19264
  19261 | if (true && replayFailedUnitOfWorkWithInvokeGuardedCallback) {
  19262 |   if (mayReplay) {
  19263 |     var failedUnitOfWork = nextUnitOfWork;
> 19264 |     replayUnitOfWork(failedUnitOfWork, thrownValue, isYieldy);
        | ^  19265 |   }
  19266 | }
  19267 | 
View compiled
performWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:20138
  20135 |   // $FlowFixMe Complains noTimeout is not a TimeoutID, despite the check above
  20136 |   cancelTimeout(timeoutHandle);
  20137 | }
> 20138 | renderRoot(root, isYieldy);
        | ^  20139 | finishedWork = root.finishedWork;
  20140 | if (finishedWork !== null) {
  20141 |   // We've completed the root. Commit it.
View compiled
performWork
node_modules/react-dom/cjs/react-dom.development.js:20050
  20047 |   }
  20048 | } else {
  20049 |   while (nextFlushedRoot !== null && nextFlushedExpirationTime !== NoWork && minExpirationTime <= nextFlushedExpirationTime) {
> 20050 |     performWorkOnRoot(nextFlushedRoot, nextFlushedExpirationTime, false);
        | ^  20051 |     findHighestPriorityRoot();
  20052 |   }
  20053 | }
View compiled
performSyncWork
node_modules/react-dom/cjs/react-dom.development.js:20024
  20021 | }
  20022 | 
  20023 | function performSyncWork() {
> 20024 |   performWork(Sync, false);
  20025 | }
  20026 | 
  20027 | function performWork(minExpirationTime, isYieldy) {
View compiled
requestWork
node_modules/react-dom/cjs/react-dom.development.js:19893
  19890 | 
  19891 | // TODO: Get rid of Sync and use current time?
  19892 | if (expirationTime === Sync) {
> 19893 |   performSyncWork();
        | ^  19894 | } else {
  19895 |   scheduleCallbackWithExpirationTime(root, expirationTime);
  19896 | }
View compiled
scheduleWork
node_modules/react-dom/cjs/react-dom.development.js:19707
  19704 | // ...unless this is a different root than the one we're rendering.
  19705 | nextRoot !== root) {
  19706 |   var rootExpirationTime = root.expirationTime;
> 19707 |   requestWork(root, rootExpirationTime);
        | ^  19708 | }
  19709 | if (nestedUpdateCount > NESTED_UPDATE_LIMIT) {
  19710 |   // Reset this back to zero so subsequent updates don't throw.
View compiled
scheduleRootUpdate
node_modules/react-dom/cjs/react-dom.development.js:20368
  20365 | 
  20366 |   flushPassiveEffects();
  20367 |   enqueueUpdate(current$$1, update);
> 20368 |   scheduleWork(current$$1, expirationTime);
  20369 | 
  20370 |   return expirationTime;
  20371 | }
View compiled
updateContainerAtExpirationTime
node_modules/react-dom/cjs/react-dom.development.js:20396
  20393 |     container.pendingContext = context;
  20394 |   }
  20395 | 
> 20396 |   return scheduleRootUpdate(current$$1, element, expirationTime, callback);
  20397 | }
  20398 | 
  20399 | function findHostInstance(component) {
View compiled
updateContainer
node_modules/react-dom/cjs/react-dom.development.js:20453
  20450 |   var current$$1 = container.current;
  20451 |   var currentTime = requestCurrentTime();
  20452 |   var expirationTime = computeExpirationForFiber(currentTime, current$$1);
> 20453 |   return updateContainerAtExpirationTime(element, container, parentComponent, expirationTime, callback);
  20454 | }
  20455 | 
  20456 | function getPublicRootInstance(container) {
View compiled
ReactRoot../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render
node_modules/react-dom/cjs/react-dom.development.js:20749
  20746 |   if (callback !== null) {
  20747 |     work.then(callback);
  20748 |   }
> 20749 |   updateContainer(children, root, null, work._onCommit);
  20750 |   return work;
  20751 | };
  20752 | ReactRoot.prototype.unmount = function (callback) {
View compiled

**Comment by xiaohuoni** [comment]
你好，是windows吗？还有能否提供重现步骤或者demo

**Comment by yanghc9** [comment]
@xiaohuoni 你好，谢谢您的回复。操作系统 windows 10 。经过反复验证，使用visual studio code终端执行npm start时，就会出现此问题，使用dos命令行则没问题。

**Comment by chenshuai2144** [comment]
是因为 powershell 的问题吗？

**Comment by yanghc9** [comment]
是因为 powershell 的问题，但深层的原因我就不清楚了。

**Comment by xiaohuoni** [comment]
我用windows的时候也是使用VS Code启动的项目，好像没有遇到遇到这个问题

**Comment by Nemo0915** [comment]
同样的问题，但是我是mac上面出现的，在Item2中npm start没问题，打开页面就是白屏，控制台报错 _this.load() is not a function，我打断点进去发现 _this里的确是没有load这个方法，求解答

**Comment by Nemo0915** [comment]
自问自答吧，的确是版本的问题，将dva的版本降到2.2.3，roadhog版本保持2.3.0之后，就不再报这个错误了。疑惑的一点是，这是版本不匹配导致的呢还是dva升级了版本之后在dynamic.js中不支持_this.load()这个方法了呢？

**Comment by xiazhangli** [comment]
为什么我使用cmd npm start编译成功了，也还是报这个错误？

**Comment by danielshicn** [comment]
我全新git clone，也存在此问题。我特意重新安装了环境，清空了npm和yarn的cache，，问题依旧出现。我的环境如下：

- Windows 10.0.17134
- Node: 10.15.3 x64
- NPM: 6.4.1
- Yarn: 1.15.2 （windows msi 安装）
- Rev: eee76430bace69ac77620b38e5974856546dfba4
- Shell: Windows CMD

**Comment by danielshicn** [comment]
自答一个，修改package.json，dva为2.5.0-beta.2 （与umi所依赖的dva一致），就可以解决此问题

**Comment by CheerySlowbro** [comment]
> 自答一个，修改package.json，dva为2.5.0-beta.2 （与umi所依赖的dva一致），就可以解决此问题

如何确认**与umi所依赖的dva一致**？

**Comment by chenshuai2144** [comment]
npm ls

**Comment by VRspace4** [comment]
Had this same problem, but after closing down VSCode completely, reopened, and `npm start` again, it worked.

**Comment by forresthu** [comment]
I am having the same problem. My environment is Windows 10, try to build project under Dos command environment. 
After following @VRspace4 's suggestion, closing down VSCode , reopen, and then build project under VSCode's terminal. It is working now.

**Comment by BigKongfuPanda** [comment]
> 自答一个，修改package.json，dva为2.5.0-beta.2 （与umi所依赖的dva一致），就可以解决此问题

多谢，按照你说的这个解决了
