### ISSUE TITLE
对网络请求的一些想法

### ISSUE THREAD

**Issue by yy6597988** [ant-design/ant-design-pro#3648]
现在页面的如果想要通过接口获取数据，需要在models新建effetcs，然后页面通过dispatch去发出请求，拿到结果后去更新reducers，把数据放在redux中，页面再通过props获取数据，感觉很繁琐哎。

为什么不采用另一种方式。

页面里直接引入service，在页面里发出请求，request把结果返回给每个页面，页面根据自己的需要，如果某些数据是全局的，就自己dispatch到全局，models作为一个纯粹的全局数据仓库，

**Comment by soulmatecm** [comment]
感觉有点封装过头

**Comment by zhongjiewu** [comment]
这样不就又多了一个带状态的service？如果请求到一半用户等不及去别的页面了，这个pending request谁管？

**Comment by chenshuai2144** [comment]
建议先去读一下 redux 的范式。这些东西都是有其存在的必要的。
实际项目中可以做一些取舍，但是会造成的别的问题。
http://cn.redux.js.org/docs/introduction/ThreePrinciples.html
