### ISSUE TITLE
Webpack Chunk设置建议

### ISSUE THREAD

**Issue by zhongjiewu** [ant-design/ant-design-pro#3649]
见PR： https://github.com/ant-design/ant-design-pro/pull/3650

**Comment by chenshuai2144** [comment]
详细描述一下？

**Comment by zhongjiewu** [comment]
@chenshuai2144 稍等。习惯了IDE的cmd+enter换行，结果github里面经常还在写的时候就发布了。

**Comment by zhongjiewu** [comment]
@chenshuai2144 写完了。

**Comment by zhongjiewu** [comment]
@chenshuai2144 建了一个PR https://github.com/ant-design/ant-design-pro/pull/3650
