### ISSUE TITLE
Use @babel

### ISSUE THREAD

**Issue by viztor** [ant-design/ant-design-pro#365]
according to babeljs.org
'babel-' prefix is no longer in use.
all future upgrades will live under '@babel'

**Comment by yesmeck** [comment]
After roadhog 2 releasing we will use babel 7 eventually.

**Comment by chenshuai2144** [comment]
@yesmeck  什么时候发布? 我用了React.Fragments
```
 <>
    <ChildA />
    <ChildB />
    <ChildC />
 </>
```
想从 creat-react-app迁移到roadhog.. 但是暂时不支持...

**Comment by yesmeck** [comment]
@chenshuai2144 You should ask in https://github.com/sorrycc/roadhog

**Comment by sorrycc** [comment]
> 什么时候发布?

计划下周。

**Comment by chenshuai2144** [comment]
@sorrycc 最近下周太多.  让我想起了服务员的 菜马上就好了.

仍然表示非常期待.
希望可以疯狂迁移
