### ISSUE TITLE
引入antd的default.less热更新会非常慢

### ISSUE THREAD

**Issue by SevenGuns** [ant-design/ant-design-pro#3651]
我想使用antd的默认样式变量
@import '~antd/lib/style/themes/default.less'
引入之后的副作用就是热更新从10秒变为2分钟

**Comment by SevenGuns** [comment]
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by chenshuai2144** [comment]
可以试着把在线换主题的插件删除

**Comment by SevenGuns** [comment]
> 可以试着把在线换主题的插件删除
去掉以后果然快了很多！非常感谢！

**Comment by long-zhuge** [comment]
@SevenGuns 请问下哪个是主题的插件？我这边也是改了样式后，更新非常慢。感谢
