### ISSUE TITLE
登录成功后重定向到指定路由的页面实现问题

### ISSUE THREAD

**Issue by lishuai1021** [ant-design/ant-design-pro#3652]
复制一个页面的url——localhost:3000/#/model/experiment/123abc，在登录页地址栏中使用其替换掉localhost:3000/#/user/login，输入用户名密码，怎么能直接跳转到model/experiment/123abc页面。使用Switch登录后还是跳到首页，代码 如下：
const BasicLayout = routerData['/'].component;
const ModelComponent= routerData['/model/experiment/:modelId'].component;
<Switch>
   <Route path="/" component={BasicLayout}>
            <Route path="/model/experiment/:modelId" component={ModelComponent} />
   </Route>
  <AuthorizedRoute
            path="/"
            render={props => <BasicLayout {...props} />}
            redirectPath="/user/login"
          />
<Switch>

**Comment by chenshuai2144** [comment]
pro 的方式是加了一个 参数用来指示退出登录之后重新登录需要的地址。可以试试这个地址
https://preview.pro.ant.design/user/login?redirect=https%3A%2F%2Fpreview.pro.ant.design%2Fprofile%2Fadvanced
