### ISSUE TITLE
怎么去掉url中的#号？

### ISSUE THREAD

**Issue by zhouguanglong** [ant-design/ant-design-pro#3654]
有回答的说看文档，路径根本访问不了，官方文档说 hashhistory 改为 browerhistory，且需要后台配合，但未说明怎么改啊，回答请按步骤写下来，谢谢！

**Comment by deleezhang** [comment]
https://pro.ant.design/docs/deploy-cn    看关于发布的内容，有详细介绍和各种后端协作处理hashhistory 和browerhistory  问题 。

**Comment by zhouguanglong** [comment]
我用的是 1.0版本，不是2.0的

**Comment by zhouguanglong** [comment]
1.0 和 2.0 解决方法相同？？？  求1.0 解决方法，2.0 同事组有用的，很容易的去掉了#，但是1.0也去不掉

**Comment by zhangshuai0101** [comment]
改为 browerhistory，你构建下放到nginx上看看但是不能刷新页面

**Comment by chenshuai2144** [comment]
可以去看看 1.0的文档。
https://v1.pro.ant.design/ 也不是很难

**Comment by zhouguanglong** [comment]
就是看的1.0的文档，按照文档改的，说是要后台配合，java后台我就不知道咋整了，反正是没搞好

**Comment by afc163** [comment]
https://facebook.github.io/create-react-app/docs/deployment#serving-apps-with-client-side-routing

**Comment by afc163** [comment]
https://stormpath.com/blog/spring-boot-stormpath-react-sdk#reroute-through-spring-boot
