### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by wangxiangchn** [ant-design/ant-design-pro#3656]
打包之后，浏览器报如下错误，页面置空。
![image](https://user-images.githubusercontent.com/37130472/53717542-6d841c80-3e93-11e9-9c0f-c59448c25b20.png)

**Comment by wangxiangchn** [comment]
该如何解决呢。求指教

**Comment by chenshuai2144** [comment]
你这个是网络问题，不是打包问题。
你是怎么部署的呢？

**Comment by wangxiangchn** [comment]
> 你这个是网络问题，不是打包问题。
> 你是怎么部署的呢？

是我没有改为 hash  已经解决,感谢
