### ISSUE TITLE
在pro中使用 dragact，当安装依赖之后antd pro部分样式失效

### ISSUE THREAD

**Issue by zhangshuai0101** [ant-design/ant-design-pro#3657]
目前解决方法需重新clone代码，未查明原因寻求帮助。
![image](https://user-images.githubusercontent.com/40013310/53718224-92798f00-3e95-11e9-9ce8-51e4ca218f65.png)

**Comment by zhangshuai0101** [comment]
@chenshuai2144 帅哥能帮忙看下吗

**Comment by zhangshuai0101** [comment]
帮忙定位一下问题吧？我在package中删除了dragact ，样式恢复正常，但是在其他人使用的时候是正常的

**Comment by zhangshuai0101** [comment]
目前定位到的问题可能是由ts引起的，但未找到解决办法

**Comment by xiaohuoni** [comment]
@zhangshuai0101 是指https://www.npmjs.com/package/dragact 这个吗

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/3670 在这里回复
