### ISSUE TITLE
NoticeIcon component enhencement

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design-pro#366]
建议NoticeIcon.Tab组件可以增加一个```clearable```属性，默认为true，当设置为false时，不显示清空栏。某些使用场景还是不希望能够一次性清空消息，而是让用户手动解决每个消息后自动清空的。

```js
<NoticeIcon.Tab
  list={data}
  title='notices'
  clearable={false}
/>
```

**Comment by nikogu** [comment]
你可以先用 `css` 把清空隐藏掉，我们这边讨论下是否有必要提供这个属性。

**Comment by kennylbj** [comment]
好的。
我的使用场景是：没有独立的```通知```实体，而是由其他实体计算出来的。例如订单实体具有一个截止日期，如果接近或者超过这个日期就可以计算出一组通知。这个时候清空这组通知没有什么作用，因为消息源头不是它。相反，用户应该去对订单采取一些操作（例如延长截止时间），此时通知就被自动清空了。

**Comment by chenshuai2144** [comment]
看来不会做了。。。。
你可以提个 pr

**Comment by afc163** [comment]
@kennylbj 来个 PR 吧
