### ISSUE TITLE
PageHeader 组件 d.ts 属性定义不完整

### ISSUE THREAD

**Issue by summer789** [ant-design/ant-design-pro#3661]
见图
location breadcrumbNameMap 这个两个定义没有在对应的d.ts文件中看到
![image](https://user-images.githubusercontent.com/20252366/53775568-09626680-3f2e-11e9-9eaf-b30a840d1d35.png)
![image](https://user-images.githubusercontent.com/20252366/53775570-0e271a80-3f2e-11e9-8334-e547a46c2337.png)

**Comment by chenshuai2144** [comment]
antd 的 pageheader 已经发布，可以去试试那个，这个已经疏于维护了

**Comment by chenshuai2144** [comment]
https://ant.design/components/page-header-cn/
