### ISSUE TITLE
ServiceWorker无法关闭，已在congfig文件中去除掉相关配置了但是还是会从ServiceWorker读取

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#3664]
![11_16_11__03_05_2019](https://user-images.githubusercontent.com/16549630/53778556-22701500-3f38-11e9-9d6c-cd8cfd9ff9b2.jpg)
已在config文件中去除相关配置，但是ServiceWorker还是处于生效状态，

**Comment by chenshuai2144** [comment]
设置 pwa 为 false
https://github.com/ant-design/ant-design-pro/blob/master/src/defaultSettings.js

**Comment by zhilianbi520** [comment]
@chenshuai2144 好的。

**Comment by zhilianbi520** [comment]
@chenshuai2144 已配置还是不生效。。。还是从ServiceWorker拿的，还需要配置哪里？

**Comment by zhilianbi520** [comment]
![12_39_58__03_05_2019](https://user-images.githubusercontent.com/16549630/53781446-d75bff00-3f43-11e9-9a12-1b37898ef12a.jpg)
fetch请求会有2遍，第一遍从ServiceWorker拿的第二遍是发送给后端的。

**Comment by zhilianbi520** [comment]
ant design pro版本为2.1.1

**Comment by afc163** [comment]
@zhilianbi520 用 master 最新版本

**Comment by zhilianbi520** [comment]
@afc163  项目已上生产换环境能具体标注下改哪几个配置文件嘛。。。这要是统一替换，这工作量有点儿大啊。

**Comment by zhilianbi520** [comment]
可以具体描述改哪些配置项嘛？项目内很多文件都已修改过，使用现在的最新版覆盖，不确定会不会造成不良影响 @afc163

**Comment by zhilianbi520** [comment]
pwacompat.min.js可以不生成嘛？
![15_57_00__03_05_2019](https://user-images.githubusercontent.com/16549630/53789448-57dc2900-3f5f-11e9-825a-eb5d7b74f6ac.jpg)
![20190305155556](https://user-images.githubusercontent.com/16549630/53789454-5ad71980-3f5f-11e9-9a70-3ec20c8061e9.jpg)
这两个配置项已配。。。对照最新版本的感觉设置一样，求解。

**Comment by chenshuai2144** [comment]
把 config.js里面pwa 删除，就可以解决问题了。
如果不起作用试着清一下缓存

**Comment by zhilianbi520** [comment]
强刷没有这个问题会读取新的资源，一般刷新还是会读取ServiceWorker

**Comment by zhilianbi520** [comment]
> 把 config.js里面pwa 删除，就可以解决问题了。
> 如果不起作用试着清一下缓存

参照上面方案已解决此问题，可以关闭这个问题了。多谢～🙏

**Comment by zhilianbi520** [comment]
> 把 config.js里面pwa 删除，就可以解决问题了。
> 如果不起作用试着清一下缓存

好的～！

**Comment by afc163** [comment]
之前应该是这个问题：https://github.com/ant-design/ant-design-pro/pull/3749
