### ISSUE TITLE
Antd Pro v2: Custom build folder after running "yarn build"

### ISSUE THREAD

**Issue by tommyspot** [ant-design/ant-design-pro#3667]
Hi all,

Currently, I'm using Antd Pro v2 to implement my project. After running `yarn build`, I want to structure the `dist` folder as below
```
dist
-- css
    -- 1.chunk.css
    -- 2.chunk.css
    -- .....
    -- umi.css
-- js
    -- 1.async.js
    -- 2.async.js
    -- .....
    -- umi.js
```

I read some topic about **webpack** configuration. I know antd pro using **webpack-chain**. I changed in config/plugin.config.js as below:

![screen shot 2019-03-05 at 2 58 12 pm](https://user-images.githubusercontent.com/7645519/53789518-23fd0580-3f57-11e9-8744-f6625cbe6640.png)

So, I built **js** folder successfully, But about **css**, I'm using **mini-css-extract-plugin**, I failed when building it.

Do you have any idea about that? Please help me, thanks!

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#extrapostcssplugins
 try this

**Comment by chenshuai2144** [comment]
Why do you need to do this?

**Comment by tommyspot** [comment]
Hi @chenshuai2144,
I need to collect it to clear cache on my server after deploying.

**Comment by chenshuai2144** [comment]
Sorry, it is not supported now.
Thank you for your use
