### ISSUE TITLE
v2版本如何在线上使用mock

### ISSUE THREAD

**Issue by 15531400827** [ant-design/ant-design-pro#3669]
看过  #1302 中说的办法， 但是那是v1版本中的解决办法，现在v2中使用umi， 有什么方法可以实现吗？

希望能实现一部分模块用mock， 一部分用真实接口。

**Comment by xiaohuoni** [comment]
尝试一下umi-serve

**Comment by xiaohuoni** [comment]
如果有定制化的需求，可以参考一下https://github.com/xiaohuoni/antd-pro-server 其实就是搭建了一个简单的express服务

**Comment by 15531400827** [comment]
@xiaohuoni 谢谢回答， 我尝试一下

**Comment by chenshuai2144** [comment]
可以看看 https://github.com/ant-design/ant-design-pro/tree/master/functions 
这个里面提供一个转化 mock 的工具。

**Comment by gaoqiang19514** [comment]
如果能在`config.js`加一个配置，让`npm run build`也能把`mock`打包进去就好了

**Comment by yutingzhao1991** [comment]
@gaoqiang19514

> 如果能在config.js加一个配置，让npm run build也能把mock打包进去就好了

你可以参考 https://github.com/umijs/umi-plugin-block-dev/blob/master/src/index.js#L45 这个自己实现个 umi 插件。

**Comment by gaoqiang19514** [comment]
> @gaoqiang19514
> 
> > 如果能在config.js加一个配置，让npm run build也能把mock打包进去就好了
> 
> 你可以参考 https://github.com/umijs/umi-plugin-block-dev/blob/master/src/index.js#L45 这个自己实现个 umi 插件。

![Snipaste_2019-03-14_17-17-13](https://user-images.githubusercontent.com/13738577/54344980-07f71380-467d-11e9-9b75-b589c2475cc6.png)
