### ISSUE TITLE
在pro中使用dragact导致antd样式失效，效果如下

### ISSUE THREAD

**Issue by zhangshuai0101** [ant-design/ant-design-pro#3670]
![image](https://user-images.githubusercontent.com/40013310/53794683-70ead700-3f6b-11e9-94d5-2557c98f7e31.png)
代码如下
![image](https://user-images.githubusercontent.com/40013310/53794748-8b24b500-3f6b-11e9-9ea8-cf24c727fd22.png)

**Comment by zhangshuai0101** [comment]
@xiaohuoni  是的 https://www.npmjs.com/package/dragact  这个造成的 尚未定位到问题原因

**Comment by afc163** [comment]
https://github.com/umijs/umi/issues/2055#issuecomment-469615258
https://github.com/Foveluy/Dragact/issues/53

**Comment by zhangshuai0101** [comment]
> [umijs/umi#2055 (comment)](https://github.com/umijs/umi/issues/2055#issuecomment-469615258)
> [Foveluy/Dragact#53](https://github.com/Foveluy/Dragact/issues/53)

我有尝试按您说的原因摘出生产依赖放到dev中并重新npm publish，但是还是造成了样式冲突 antd部分样式不生效
