### ISSUE TITLE
formatMessage失效

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3671]
在utils文件夹下，新建一个`constants.js`的文件，文件的内容如下：

```
import { formatMessage } from 'umi/locale';

/** 前端状态显示值 */
export const STATUS = {
  ONLINE: formatMessage({ id: 'common.table.content.enabled' }),
  OFFLINE: formatMessage({ id: 'common.table.content.disabled' }),
};
```

发现formatMessage引入不进来，国际化无效，这是怎么原因，`umi/locale` 在哪些地方是不能导入的，能告知一下吗？

**Comment by afc163** [comment]
看看是不是这个没开启：https://github.com/ant-design/ant-design-pro/blob/master/config/config.js#L19

**Comment by mstao** [comment]
开启了，比如pages里的页面国际化都没有问题。前段时间`constants.js`的国际化还好使，但当我在request.js文件引入constants.js的常量时，constants.js的国际化也会无效

**Comment by 15531400827** [comment]
@mstao 这个我也遇到过， 感觉是引入在页面加载之前， 也不太理解， 反正改成函数的形势应该就好了， 别写成常量。

**Comment by afc163** [comment]
formatMessage 要在 IntlProvider 内部使用：https://github.com/yahoo/react-intl/blob/96a11032768fb3087dcdbe5be0b9e0ba90accb89/src/components/message.js#L22

**Comment by 15531400827** [comment]
@afc163 #3669 这个问题帮看下呢， 有没有解决方案， 谢谢

**Comment by mstao** [comment]
> formatMessage 要在 IntlProvider 内部使用：https://github.com/yahoo/react-intl/blob/96a11032768fb3087dcdbe5be0b9e0ba90accb89/src/components/message.js#L22

在ant-design-pro 中，pages下页面应该被IntlProvider包裹了，其他的就不清楚怎么用

**Comment by afc163** [comment]
https://github.com/yahoo/react-intl/wiki/API#injectintl

**Comment by mstao** [comment]
我把`constants.js`放在与pages文件夹同级的一个文件夹下，就可以了，目前还不是非常理解，多谢解答~
