### ISSUE TITLE
preview.pro.ant.design throws errors

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#3672]
- url: https://preview.pro.ant.design/dashboard/analysis
- browser: Firefox Developer Edition 66.0b12 (64-bit)

```jsx
Object { message: "Inline JavaScript is not enabled. Is it set in your options?", stack: undefined, type: "Syntax", filename: "https://preview.pro.ant.design/color.less", index: 3889, line: 113, column: 0, callLine: NaN, callExtract: undefined, extract: (3) […], … }
less.min.js:13:1566
Error: "Loading CSS chunk 36 failed.
(/36.chunk.css)"
    onerror https://preview.pro.ant.design/umi.js:1
umi.js:1:209780
The script from “https://preview.pro.ant.design/36.async.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More] analysis
SyntaxError: expected expression, got '<'[Learn More] 36.async.js:1
Unhandled promise rejection Error: "Loading CSS chunk 36 failed.
(/36.chunk.css)"
    onerror https://preview.pro.ant.design/umi.js:1
umi.js:1:443552
bizCharts load success
```

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/507615/53799694-f1aed080-3f75-11e9-9b36-06cda870baf1.png">

It works after refreshing forcely.

**Comment by chenshuai2144** [comment]
@sorrycc  这个加载时有某种缓存机制吗？

**Comment by sorrycc** [comment]
缓存机制？没有的。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/53853308-e7d1af80-3fff-11e9-91e9-3f6047169e6d.png)
抛的是 less 的 warning，应该和自定义主题有关。

**Comment by afc163** [comment]
https://preview.pro.ant.design/36.chunk.css
https://preview.pro.ant.design/36.async.js

这两个文件有问题。

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/507615/53853578-04221c00-4001-11e9-8ccc-6d80de4162d7.png">

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/507615/53853597-100dde00-4001-11e9-9973-18d76b8d97b5.png">

**Comment by sorrycc** [comment]
部署问题？是不是 36 文件没传上去？

**Comment by chenshuai2144** [comment]
published

**Comment by cindyZhang4** [comment]
> published

请问下是什么原因呢？目前不同的文件遇到了同样的问题。
