### ISSUE TITLE
静态主页跳转到ant-design-pro生成页面之后无法返回

### ISSUE THREAD

**Issue by fatefate0727** [ant-design/ant-design-pro#3673]
从项目静态页跳转到ant-design-pro生成页面之后，浏览器Cache-Storage及IndexedDB中将缓存大量文件，并导致除使用清除浏览器数据以外的常规手段无法再返回主页
以下为C# + ant-design-pro的Demo项目
https://github.com/fatefate0727/TestProject

**Comment by chenshuai2144** [comment]
使用 hash 路径呢？

**Comment by fatefate0727** [comment]
> 使用 hash 路径呢？

非常感谢，问题已解决

**Comment by fatefate0727** [comment]
> 使用 hash 路径呢？

很遗憾的是，当我进行ant-design-pro项目修改并打包之后，该问题再次出现了

**Comment by chenshuai2144** [comment]
清除一下缓存就好了
