### ISSUE TITLE
动态菜单已从mock获取，新菜单，路由无法跳转，点击 404

### ISSUE THREAD

**Issue by lemoncy** [ant-design/ant-design-pro#3674]
### mock新加菜单数据：menuData.js，与router.config.js一致，按格式追加新增菜单：系统管理。
 menu.js 动态获取 菜单数据：
` const dynamicMenuData = yield call(getMenuData);`
 ## 问题：点件新菜单后，跳转至404。
![image](https://user-images.githubusercontent.com/3096214/53802622-38ec8f80-3f7d-11e9-8b47-b94b5a6d4b1a.png)

如果再router.config.js配置文件新增菜单，.umi 文件 router.js 自动加入菜单就可以访问新菜单。
请问动态生成菜单，在何处生成新的路由？

**Comment by yumanman1994** [comment]
你这里是如何实现的
