### ISSUE TITLE
如何实现点击菜单，强制刷新。

### ISSUE THREAD

**Issue by gh-0** [ant-design/ant-design-pro#3676]
比如，我当前在 “分析页”，当我再次点击 菜单栏中的 “分析页” 时，数据都要重新在服务端获取

**Comment by imhele** [comment]
自己给 menu 加一个 onClick 事件，判断 click 的路由和当前路由相同就 refresh browser

**Comment by gh-0** [comment]
> 自己给 menu 加一个 onClick 事件，判断 click 的路由和当前路由相同就 refresh browser

好的，谢谢
