### ISSUE TITLE
 Error: EPERM: operation not permitted, open 'D:\project\sk_platform_admin_home\.temp\ant-design-pro.less'

### ISSUE THREAD

**Issue by gaoxiaosong1113** [ant-design/ant-design-pro#3678]
(node:8596) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, open 'D:\project\sk_platform_admin_home\.temp\ant-design-pro.less'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at loopAllLess.then (D:\project\sk_platform_admin_home\node_modules\antd-pro-merge-less\index.js:64:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:8596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![image](https://user-images.githubusercontent.com/16183057/53862092-1b710180-4021-11e9-9721-50893ad0ce01.png)

**Comment by chenshuai2144** [comment]
删除 plugin.config.js 就可以解决
