### ISSUE TITLE
高级表单页面的底部信息无法完全显示

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3681]
<img width="318" alt="wx20190307-001738 2x" src="https://user-images.githubusercontent.com/11746742/53896263-a2989680-406e-11e9-87ea-0d4a14e6ddad.png">

我知道是为什么，但是这样显示一半，就是觉得别扭

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/53896387-e25f7e00-406e-11e9-8d06-028008e7046a.png)

**Comment by chenshuai2144** [comment]
这应该是个 bug 把。竟然显示了1/2

**Comment by xiaohuoni** [comment]
不是，是因为那个提交布局固定在页面底部。所以挡住了一半
