### ISSUE TITLE
路由使用的hashHistry,需求--首页path不带#

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#3683]
#### 尝试1：
   {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      {path: '/', name: 'portalHomeIndex', component: './User/LoginIndex'},
    ],
  },  
仅前端运行，可以但是 path 在路由器显示是：域名+项目+‘/#/’，
#### 尝试2：
 注释config.js 的  history: 'hash',
前端运行正常（npm start）,前后端（npm run  build）联调后，仅展示BlankLayout内容，LoginIndex 页面不展示。需要后台配合，暂不采纳。

### 探索：find 渲染path 的过程，path = props.location.path ，props属性修改不易
哪位资深前端帮忙看看解决，或者有充足的理由反驳这样得需求？感谢

**Comment by chenshuai2144** [comment]
hash 必须要带 # 号
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web  hash是根据片段标识符来进行路由切换的
