### ISSUE TITLE
日期选择国际化中文显示不完整，填入默认值国际化显示完整，不填入默认值显示不完整

### ISSUE THREAD

**Issue by xiaochunyu** [ant-design/ant-design-pro#3685]
传入默认值默认情况：
![image](https://user-images.githubusercontent.com/2617418/53932328-0bfec080-40d4-11e9-8d8d-aee0b1d3fdeb.png)
![image](https://user-images.githubusercontent.com/2617418/53932331-13be6500-40d4-11e9-9ea6-6223c0e58710.png)
不传入默认值情况：
![image](https://user-images.githubusercontent.com/2617418/53932348-20db5400-40d4-11e9-817c-298ed6770f7f.png)
![image](https://user-images.githubusercontent.com/2617418/53932353-246edb00-40d4-11e9-9da9-135737e6c0dd.png)

**Comment by xiaochunyu** [comment]
测试了几次：
发现是因为安装包导致的，我使用yarn install, cnpm install 重新安装了几次都并无我上面所说的问题。

但是使用npm install 就会出现这个问题。
macOS Mojave 10.14.1 (18B75)
node v10.12.0
npm 6.8.0

![image](https://user-images.githubusercontent.com/2617418/53937060-ec24c800-40e6-11e9-990d-496736bfca31.png)
![image](https://user-images.githubusercontent.com/2617418/53937202-68b7a680-40e7-11e9-8f02-02a727d35c8a.png)
![image](https://user-images.githubusercontent.com/2617418/53937235-7f5dfd80-40e7-11e9-84cd-8052fc08ceeb.png)

![image](https://user-images.githubusercontent.com/2617418/53937319-b3392300-40e7-11e9-9378-b51f5e64338f.png)

**Comment by xiaochunyu** [comment]
ant design pro版本为 2.1.1

**Comment by JerryMissTom** [comment]
@afc163 这个Bug 我今天也遇到了，采用楼主说的方法，使用yarn install安装依赖包后解决

**Comment by afc163** [comment]
@JerryMissTom 统一一下 moment 的版本，依赖了多个 moment 也会有问题。

**Comment by JerryMissTom** [comment]
@afc163 谢谢解答
