### ISSUE TITLE
2.2版本logout以后，点浏览器后退，还能再退回logout之前的页面？

### ISSUE THREAD

**Issue by zhy19712** [ant-design/ant-design-pro#3686]
之前的版本到/user/login就停住了，2.2怎么还能一直后退呢？

**Comment by chenshuai2144** [comment]
原来是判断没有登录，强制跳转到 login，现在没有这个功能了

**Comment by xiaohuoni** [comment]
https://preview.pro.ant.design
在这里看了，没有这个问题了，有问题再reopen
