### ISSUE TITLE
大家有没有遇到样式表重复的问题？

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#369]
问题如图：
![image](https://user-images.githubusercontent.com/12181423/33598103-83199074-d9dc-11e7-8341-28e3b999be49.png)

当前版本："dva": "^2.0.3", "roadhog": "^1.3.1",

请问图上的问题如何解决？

**Comment by chenshuai2144** [comment]
有可能是动态加载组件的问题.

**Comment by fgprodigal** [comment]
![qq20171205-183504](https://user-images.githubusercontent.com/769910/33602702-18d4ccba-d9eb-11e7-9728-618e1900c206.png)

就是这样，当初困扰了我一天，我各种改roadhog配置，以为是roadhog的问题

**Comment by fgprodigal** [comment]
@hqwlkj 然而我就是这么配置的，只要import了ant design pro的exception就自动加载css

**Comment by hqwlkj** [comment]
@fgprodigal   好的谢谢

**Comment by afc163** [comment]
something related about vendor config of roadhog: https://github.com/sorrycc/roadhog/issues/370

**Comment by clverpanda** [comment]
一样有这个问题，我配置了modifyVar来使用本地的图标文件，可是ant-design-pro又引入了antd\lib\style\index.css导致又会下载cdn上的图标文件。

**Comment by fordguo** [comment]
也碰到重复css的问题
是单独使用ant-pro组件方式，版本是1.1.0
dev模式没有问题，build发布后，出现antd的css重复，不知道是不是roadhog的build问题 :(
