### ISSUE TITLE
v2.2.1 没做登录拦截吗？

### ISSUE THREAD

**Issue by zwdgit** [ant-design/ant-design-pro#3692]
自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态

**Comment by GIn-Liu** [comment]
src/utils/authority下面
export function getAuthority(str) {
  // return localStorage.getItem('antd-pro-authority') || ['admin', 'user'];
  const authorityString =
    typeof str === 'undefined' ? localStorage.getItem('antd-pro-authority') : str;
  // authorityString could be admin, "admin", ["admin"]
  let authority;
  try {
    authority = JSON.parse(authorityString);
  } catch (e) {
    authority = authorityString;
  }
  if (typeof authority === 'string') {
    return [authority];
  }
  return authority || ['admin'];
}
将最后的admin改为guest就可以了

**Comment by gaoqiang19514** [comment]
> src/utils/authority下面
> export function getAuthority(str) {
> // return localStorage.getItem('antd-pro-authority') || ['admin', 'user'];
> const authorityString =
> typeof str === 'undefined' ? localStorage.getItem('antd-pro-authority') : str;
> // authorityString could be admin, "admin", ["admin"]
> let authority;
> try {
> authority = JSON.parse(authorityString);
> } catch (e) {
> authority = authorityString;
> }
> if (typeof authority === 'string') {
> return [authority];
> }
> return authority || ['admin'];
> }
> 将最后的admin改为guest就可以了

没用啊，用户还是可以随便进入，删除`localStorage`中的`antd-pro-authority`也一样

**Comment by xiaohuoni** [comment]
@gaoqiang19514 看我的提交

**Comment by gaoqiang19514** [comment]
> @gaoqiang19514 看我的提交

没找见，老哥，给个链接

**Comment by afc163** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/507615/54021932-4186d500-41cc-11e9-8271-ac6b84735b3b.png">

**Comment by gaoqiang19514** [comment]
@xiaohuoni @afc163 谢谢耐心！

**Comment by zhuguangyue** [comment]
> 自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态

请问你是如何解决登录拦截失效的啊？

**Comment by zwdgit** [comment]
> > 自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态
> 
> 请问你是如何解决登录拦截失效的啊？

最新提交的代码应该是已经解决了

**Comment by zhuguangyue** [comment]
> > > 自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态
> > 
> > 
> > 请问你是如何解决登录拦截失效的啊？
> 
> 最新提交的代码应该是已经解决了

最新提交的代码还是没有拦截登录状态，请问你是如何解决的啊？根据你上面的解决方案都没效果

**Comment by zwdgit** [comment]
1.修改config/router.config.js  
// dashboard
{ path: '/', redirect: '/dashboard/Workplace', authority:['admin'] },
2.修改src/utils/authority.js
Line16: return authority;


| |
朱卫东
17862979705@163.com
|
签名由网易邮箱大师定制


在2019年03月11日 14:47，zhuguangyue<notifications@github.com> 写道：

自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态

请问你是如何解决登录拦截失效的啊？

最新提交的代码应该是已经解决了

最新提交的代码还是没有拦截登录状态，请问你是如何解决的啊？根据你上面的解决方案都没效果

**Comment by zhuguangyue** [comment]
> 1.修改config/router.config.js // dashboard { path: '/', redirect: '/dashboard/Workplace', authority:['admin'] }, 2.修改src/utils/authority.js Line16: return authority; | | 朱卫东 17862979705@163.com | 签名由网易邮箱大师定制 在2019年03月11日 14:47，zhuguangyue<notifications@github.com> 写道： 自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态 请问你是如何解决登录拦截失效的啊？ 最新提交的代码应该是已经解决了 最新提交的代码还是没有拦截登录状态，请问你是如何解决的啊？根据你上面的解决方案都没效果 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

新pull下来的代码，按你说的改好像还是不行哦

**Comment by zwdgit** [comment]
我的是没问题的


| |
朱卫东
17862979705@163.com
|
签名由网易邮箱大师定制


在2019年03月12日 14:00，zhuguangyue<notifications@github.com> 写道：

1.修改config/router.config.js // dashboard { path: '/', redirect: '/dashboard/Workplace', authority:['admin'] }, 2.修改src/utils/authority.js Line16: return authority; | | 朱卫东 17862979705@163.com | 签名由网易邮箱大师定制 在2019年03月11日 14:47，zhuguangyuenotifications@github.com 写道： 自己部署的项目和预览项目都是可以直接跳转到 dashboard 页面，没有拦截登录状态 请问你是如何解决登录拦截失效的啊？ 最新提交的代码应该是已经解决了 最新提交的代码还是没有拦截登录状态，请问你是如何解决的啊？根据你上面的解决方案都没效果 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

新pull下来的代码，按你说的改好像还是不行哦

**Comment by youngsailor** [comment]
未授权时登陆首页好像会有瞬间的跳转，先跳转到基本布局页再瞬间跳转到到登陆页。

**Comment by zhuguangyue** [comment]
> 用后台返回菜单和权限，未授权时进入内部组件地址好像会有瞬间的跳转，先跳转到基本布局页再瞬间跳转到到登陆页，不可以直接跳转到登陆页么？

请问你这个问题解决了吗，有什么解决方法吗？
