### ISSUE TITLE
表格的column筛选排序状态重置问题

### ISSUE THREAD

**Issue by qinvz** [ant-design/ant-design-pro#3695]
表格设置了排序以及筛选之后, 当我们从外部点击按钮刷新data时,数据列表实际并没有经过筛选排序,

**Comment by VitorGultzgoff** [comment]
Could you please detail more your scenario ? Usually the filter and sorter works at all.

**Comment by qinvz** [comment]
![gif](https://i.loli.net/2019/03/18/5c8fa3b791118.gif) 先筛选, 后点击刷新数据, 结果如下

**Comment by qinvz** [comment]
当然解决办法就是在外面维护排序以及筛选等状态, 就是麻烦点了, 如果表格能出重置状态的方法就很方便了

**Comment by youngjuning** [comment]
ant design中table组件的filter和sorter，如何在外部控制？：https://blog.csdn.net/my_wings/article/details/90236080
