### ISSUE TITLE
antdp 自动提示升级的机制，运用到本系统；

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#3698]
### 每次antdp升级，对应的preview 就会弹框提示升级？ 怎么运用到系统？或者讲解一下实现过程？感谢

**Comment by chenshuai2144** [comment]
这是 [pwa](https://www.google.com/search?q=pwa+mdn&oq=pwa+mdn&aqs=chrome..69i57.2794j0j7&sourceid=chrome&ie=UTF-8) 的能力。
具体代码在 https://github.com/ant-design/ant-design-pro/blob/master/src/global.js 中，你可以简单的看一下

**Comment by yemaozi5518** [comment]
好的
