### ISSUE TITLE
以后会用 Fish Redux替代Dva吗?

### ISSUE THREAD

**Issue by firemoon2000** [ant-design/ant-design-pro#3699]
AntdPro一直使用的Dva, 目前也习惯了Dva使用起来很方便.
但是最近开源了Fish Redux, 说是参考了Redux 和 Dva.

1.这是 @sorrycc 之前视频演讲中提到的Dva改进么?
2.以后AntdPro中会使用FishRedux替代Dva吗?
望答复.感谢

**Comment by imhele** [comment]
![2019-03-08](https://user-images.githubusercontent.com/32428655/54021901-2ae07e00-41cc-11e9-9a34-6bf6df34601c.png)

**Comment by afc163** [comment]
这是给 flutter 用的，好像和 React 社区没啥关系。

**Comment by xiaohuoni** [comment]
演讲提到的是dva3，不是其他替代方案。
