### ISSUE TITLE
config.js配置了dll导致部分样式丢失

### ISSUE THREAD

**Issue by jdongdong** [ant-design/ant-design-pro#3700]
加入如下配置后，导致部分样式丢失
![image](https://user-images.githubusercontent.com/11850305/54021319-d25cb100-41ca-11e9-94d0-b0dd4375ca32.png)
错误：
![image](https://user-images.githubusercontent.com/11850305/54021645-96761b80-41cb-11e9-8636-e78cd05c4fa5.png)

正常：
![image](https://user-images.githubusercontent.com/11850305/54021536-52831680-41cb-11e9-9735-3e42be58c8f0.png)

操作系统：Mac
```json
    "umi": "^2.6.1",
    "umi-plugin-react": "^1.6.0"
```

**Comment by jdongdong** [comment]
关闭之后的字体样式也有问题

**Comment by jdongdong** [comment]
关闭之后的字体样式也有问题

**Comment by jdongdong** [comment]
关闭dll之后的字体也有问题
错误：![image](https://user-images.githubusercontent.com/11850305/54022758-392f9980-41ce-11e9-949a-8cde8576c8dc.png)
正常![image](https://user-images.githubusercontent.com/11850305/54022806-4fd5f080-41ce-11e9-97b6-13a436dde3ab.png)
看控制台发现同样的样式引用了两次
![image](https://user-images.githubusercontent.com/11850305/54023768-c2e06680-41d0-11e9-93c4-03cd4ace47c0.png)
一个是从es/styles中引用，一个是从lib/style中引用

**Comment by adwerrd** [comment]
+1

**Comment by chenshuai2144** [comment]
dll 会导致 global.less 中的所有 less 丢失，我们正在寻找问题出现在哪里。

**Comment by hnsylitao** [comment]
我碰到了同样的问题，但是为什么官方示例没有出现这样的问题呢

**Comment by hnsylitao** [comment]
我检查了一下
umi-dll-plugin 把package.json dependencies 的模块都打包进了 dll plugin 
而有些 dependencies 的模块中有引入 css 的模块
就会导致 样式缺失

但是为什么会缺失没有找到

**Comment by xiaohuoni** [comment]
@sorrycc

**Comment by topwood** [comment]
遇到了类似的问题，引用一个三方的组件包，即便只有在package.json里声明并下载了依赖，在代码里面没有引用 也会出现这个问题，看了下调试的时候umi.css里面的样式没了，换成了这个三方组件包的css。去掉package.json里面的该依赖之后恢复正常。希望能尽快解决。
![image](https://user-images.githubusercontent.com/13791267/57666631-2d7bab80-7633-11e9-8201-af6e53eb27e1.png) @sorrycc

**Comment by hnsylitao** [comment]
@topwood 
相同问题，可以通过umi config dllplugin exclude 排除掉第三方组件库，来保证dll plugin 样式不出来的问题~~

**Comment by topwood** [comment]
@hnsylitao 也不知道这个exclude支持不支持function或者正则（反正在文档里面是没说明），我这边这种依赖不少，每个都写一遍太麻烦，干脆把dll注释掉了
