### ISSUE TITLE
Don't prefix interface with I

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-pro#3706]
由于我们正在从 JavaScript 到 TypeScript 做[迁移](https://github.com/ant-design/ant-design-pro/pull/3702)，所以我想提一下这个问题。虽然在 tslint 推荐的规则中，默认会要求接口有 I 前缀，但是他们已经认识到了这个错误，并且[准备不再推荐这么做](https://github.com/palantir/tslint/issues/1520#issuecomment-435619104)。

鉴于这个项目对于业务项目的指导意义，我不希望看到这个习惯被带到大量的业务项目中。

不要给接口带 I 前缀的原因：https://stackoverflow.com/a/41967120

**Comment by xiaohuoni** [comment]
好的

**Comment by xiaohuoni** [comment]
望多指教！
