### ISSUE TITLE
逻辑设计思路请教（关于tabs）#help wanted

### ISSUE THREAD

**Issue by zzyyzz1992** [ant-design/ant-design-pro#3707]
我现在的业务需求中，
比如：**下订单**时，需要有一个动态搜索下拉加载**客户列表**的autoComplete，
如果下单的客户不存在，autocomplete的最后一行显示一个button，提示用户**新建客户**。
我目前认为最好的解决方法是类似dva-boot-admin那样新建一个创建客户的tab，创建完成后可以自动关闭tab，随即切换回下订单的业务逻辑。
理论上来说modal一个也是可以的，但是存在一个问题，如果创建客户的页面，需要添加客户的一些同样需要用到autoComplete的属性，比如**所属区域**（只要是动态属性都有涉及到，这里仅举个例子），这个区域也是可以动态添加的，那么按照这个逻辑，就需要再加一层modal。
我感觉这样设计太重了，看到之前关于tabs的讨论，开发人员说tabs不符合内部的设计逻辑，那么请问如果不使用tabs，怎样实现最优雅？谢谢！

**Comment by zzyyzz1992** [comment]
如果我描述的应用场景不好理解，我重新举个例子：
创建订单的页面，订单项中的商品名称（autoComplete组件动态搜索），如果之前没有创建，需要弹出一个新的页面创建商品，于此同时，在这个新的创建商品的页面中，仍然有可能需要填写之前不存在的属性（autoComplete），比如商品的规格，厂家名称等等等等。
恕我愚钝，我用antd pro写的框架原型是利用modal弹出对话框实现创建商品的，如果需要再新建新的属性，则再叠加一层modal。
所以我想这种业务需求对于有订单系统的ERP应该比较常见，所以请问各位大神，在现有antd pro框架下，如何优雅的实现？如果不能，请问是否针对这种场景添加tabs模式？
PS，之前一直搞后端和移动端，前端的设计思路确实不太清楚，但是这个问题我也思考了许久而不得解，不得已写个issue来请教各位，如能指教小弟，不胜感激！

**Comment by kuhami** [comment]
> modal

Tabs 场景： https://github.com/kuhami/react-ant-pro 望采纳！

**Comment by kuhami** [comment]
> 如果我描述的应用场景不好理解，我重新举个例子：
> **创建订单**的页面，**订单项**中的**商品名称**（autoComplete组件动态搜索），如果之前没有创建过，搜索不到，需要弹出一个新的页面**创建商品**，于此同时，在这个新的创建商品的页面中，仍然有可能需要填写之前没有创建过的属性内容（同样使用autoComplete组件），比如**商品的规格**，**厂家名称**等等等等（**即需要新建一个新的商品规格或者新建一个新的厂家**）。
> 恕我愚钝，我用antd pro写的框架原型是利用modal弹出对话框实现创建商品的，如果需要再新建新的属性，则再叠加一层modal。
> 所以我想这种业务需求对于有订单系统的ERP应该比较常见，所以请问各位大神，在现有antd pro框架下，如何优雅的实现？如果不能，请问是否针对这种场景添加tabs模式？
> PS，之前一直搞后端和移动端，前端的设计思路确实不太清楚，但是这个问题我也思考了许久而不得解，不得已写个issue来请教各位，如能指教小弟，不胜感激！

Tabs 场景： https://github.com/kuhami/react-ant-pro 望采纳！

**Comment by zzyyzz1992** [comment]
@kuhami 谢谢，感觉做的很棒！
我提出这个issue其实主要是想询问**antd pro官方人员**
1）对于这种场景需求，在之前的关于tabs的issue中有官方人员回复说tabs不符合他们的业务设计理念，所以我想询问，按照他们官方的设计理念，怎样实现这一需求？
2）如果他们的设计理念不能很好的满足这个需求，是否考虑后加tabs组件？

毕竟我这边也考虑未来组件的更新维护的问题，肯定是官方项目可以得到最长久的维护。
但是现在看来我只能选择非官方的fork来实现了。

**Comment by zzyyzz1992** [comment]
@chenshuai2144

**Comment by zzyyzz1992** [comment]
> > 如果我描述的应用场景不好理解，我重新举个例子：
> > **创建订单**的页面，**订单项**中的**商品名称**（autoComplete组件动态搜索），如果之前没有创建过，搜索不到，需要弹出一个新的页面**创建商品**，于此同时，在这个新的创建商品的页面中，仍然有可能需要填写之前没有创建过的属性内容（同样使用autoComplete组件），比如**商品的规格**，**厂家名称**等等等等（**即需要新建一个新的商品规格或者新建一个新的厂家**）。
> > 恕我愚钝，我用antd pro写的框架原型是利用modal弹出对话框实现创建商品的，如果需要再新建新的属性，则再叠加一层modal。
> > 所以我想这种业务需求对于有订单系统的ERP应该比较常见，所以请问各位大神，在现有antd pro框架下，如何优雅的实现？如果不能，请问是否针对这种场景添加tabs模式？
> > PS，之前一直搞后端和移动端，前端的设计思路确实不太清楚，但是这个问题我也思考了许久而不得解，不得已写个issue来请教各位，如能指教小弟，不胜感激！
> 
> Tabs 场景： https://github.com/kuhami/react-ant-pro 望采纳！
还有一个月才正式敲定前端框架，
期待你的[基于pro 2.0的版本](https://github.com/kuhami/react-ant)
