### ISSUE TITLE
跨域session问题

### ISSUE THREAD

**Issue by che8987** [ant-design/ant-design-pro#3710]
服务端已经允许跨域请求，现在的问题是，每次请求服务端服务，会生成新的session，如何保证每次i请求的session一致？我试过jquery和纯js的ajax请求，通过设置withCredentials=true，crossDomain=true就可以实现，不知道ant怎么设置，版本v1.3

**Comment by chenshuai2144** [comment]
使用代理就可以保留 session。这个是推荐的方案。
跨域 session 看这里 https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch#%E5%8F%91%E9%80%81%E5%B8%A6%E5%87%AD%E6%8D%AE%E7%9A%84%E8%AF%B7%E6%B1%82
