### ISSUE TITLE
Ant Design Pro （2.1.0） 怎么实现无痕升级？

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#3711]
### 关于升级问题的总结
1.从beta 版本升级到2.1.0是通过两种方法：按照升级API，由于不是实时更新的，中间总会出现未知BUG；通过新 download的版本代码，一点点重构，很耗时；
2.现在又要升级了，作为国内的封装前端的框架，感觉升级总是很费劲（使用的初衷是：开箱即用，快速开发）。小白建议： 新增的模块定制在某个文件夹（model,component,页面class）,更新时忽略更新；其他固有的组件，直接替换；需要修改的地方就一些配置文件和import引入方式等其他微量的修改。
3.自动提示升级  https://github.com/ant-design/ant-design-pro/issues/3698

**Comment by chenshuai2144** [comment]
脚手架和框架升级的确是一个很苦难的事情，现在最好的方式是 git diff
包括 create react app 在内的脚手架都是通过封装成包来解决的，一旦 inject 就无法再次升级。
pro 的底层 umi 升级还是比较容易的，脚手架的内容，比如 menu 和 compents 也是比较容易的，难点在于 page，但是我们没有想到更好的方案，区块是我们最新的尝试，也是希望可以解决的这个问题

**Comment by chenshuai2144** [comment]
4.0 已经发布
