### ISSUE TITLE
请教一下各位这个问题如何解决啊？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#3712]
![image](https://user-images.githubusercontent.com/37643958/54098524-e7665980-43ef-11e9-882c-b93e15dba67f.png)

**Comment by GIn-Liu** [comment]
先检查一下有没有方法同名，在同一个.js文件。有的话改掉一个，先试试这样

**Comment by blackboy1987** [comment]
400:说明你的参数格式跟后台不一致
下面一个：Input 的maxlength值是数组格式：<Input maxlength=3 />就可以了。如果是动态传：<Input maxlength={maxlength} />

**Comment by xiaohuoni** [comment]
感觉是参数设定错误，可以查阅官方文档，进行校对
