### ISSUE TITLE
请问一下，页面和model用connect连接时，model是怎么被加载进来的

### ISSUE THREAD

**Issue by HoneMengA3** [ant-design/ant-design-pro#3714]
因为我发现，页面也没有引入，是默认加载src/model中的所有文件吗？

**Comment by yemaozi5518** [comment]
看下react  的  生命周期  ， didMount  WillMount 里 dispatch ，也会在加载时，引入model

**Comment by HoneMengA3** [comment]
> 看下react 的 生命周期 ， didMount WillMount 里 dispatch ，也会在加载时，引入model
因为antd-pro应该对dva做了一些封装，所以只看dva的教程有些地方对不上，之前在用redux的时候我知道是在页面入口将所有的store加载进来，包裹了整个app组件，但是在这个架构中，我不知道页面connect是连接到哪了，毕竟有好多model，还分全局model的和页面model

**Comment by yemaozi5518** [comment]
不要太在意局部还是全局的，page 下的 .umi 文件夹下 initdva

**Comment by HoneMengA3** [comment]
> 不要太在意局部还是全局的，page 下的 .umi 文件夹下 initdva

看了一下这个文件，我再src/models添加一个model之后，已经自动引入了，但是我在page.js文件中connect还是报错，找不到关联的model。    这是我的写法 
export default connect(({ products }) => ({
	products,
}))(Products);
但是我看示例的页面好像都用了一个@connect

**Comment by yemaozi5518** [comment]
你看下官网的 newPage  的例子，不要着急？或者度娘下报错，或者截个图

**Comment by HoneMengA3** [comment]
> 你看下官网的 newPage 的例子，不要着急？或者度娘下报错，或者截个图

**Comment by HoneMengA3** [comment]
> > 你看下官网的 newPage 的例子，不要着急？或者度娘下报错，或者截个图

报错信息很简单的

> > 你看下官网的 newPage 的例子，不要着急？或者度娘下报错，或者截个图

我又试了几下，页面和model成功连接了，我想问一下初始化某个mode的state应该在哪里定义呢？

**Comment by yemaozi5518** [comment]
我不会再回你信息了，自己官网找demo 吧

**Comment by HoneMengA3** [comment]
> 我不会再回你信息了，自己官网找demo 吧

好的，谢谢你
