### ISSUE TITLE
菜单折叠异常

### ISSUE THREAD

**Issue by ifzm** [ant-design/ant-design-pro#3716]
如下图，折叠菜单出现异常，preview.pro.ant.design 收起时不会出现这个 菜单Tip，请问这是什么原因？

![a](https://user-images.githubusercontent.com/12740295/54109956-0fb77d80-441b-11e9-9f91-14d18ba5fd2b.gif)

**Comment by wyfnet** [comment]
同问，昨天clone最新的代码下来就这样了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15321
