### ISSUE TITLE
切换mock至服务无效

### ISSUE THREAD

**Issue by zhangweitao521** [ant-design/ant-design-pro#3717]
求指导，我是做Android的，想学习这个框架；
1.照着官方文档走一遍，设置无效（用两个命令都试了）；
![图片1](https://user-images.githubusercontent.com/22015641/54110898-8b1a2e80-441d-11e9-950d-70d70bf5853f.jpg)
2.只有当输入完整的地址的时候才可以访问到，
![图片2](https://user-images.githubusercontent.com/22015641/54110947-a8e79380-441d-11e9-908c-c8aceda288df.jpg)

**Comment by imhele** [comment]
是在本地开发环境失效的吗？

**Comment by zhangweitao521** [comment]
是的，还没有打包，只是在本地调用接口

**Comment by imhele** [comment]
给一下重现吧
> 这个跟环境有关系吗

proxy 只在 umi dev 下有效

**Comment by qianli8811** [comment]
![image](https://user-images.githubusercontent.com/6313040/54288339-47245680-45e2-11e9-868a-7a6288ee4fc3.png)
我也遇到了这个问题，就是进不了后台，还是走mock

**Comment by travonf** [comment]
修改src/.env
增加MOCK=none
config里面proxy确保配置正确
重启
