### ISSUE TITLE
升级到2.2.1菜单收缩问题

### ISSUE THREAD

**Issue by anyukj** [ant-design/ant-design-pro#3727]
收缩的时候打开的菜单会显示在外面，延迟还有点长，效果不好看。

![图片](https://user-images.githubusercontent.com/31227879/54171174-70df5f80-44b4-11e9-94f0-51ce309272cf.png)

![图片](https://user-images.githubusercontent.com/31227879/54171200-8bb1d400-44b4-11e9-9939-7faa158d4761.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15321
