### ISSUE TITLE
在ant design pro中使用gg-editor样例中的FlowPage组件，样式不对 

### ISSUE THREAD

**Issue by lvzheng0404** [ant-design/ant-design-pro#3728]
在ant design pro中使用gg-editor样例中的FlowPage组件，样式不对 
如下图：
![image](https://user-images.githubusercontent.com/35189771/54171434-3e823200-44b5-11e9-80bc-7a4d8d5910aa.png)
正常的应该是下面这样：
![image](https://user-images.githubusercontent.com/35189771/54171470-5d80c400-44b5-11e9-88e5-e2a10b6d96e2.png)

**Comment by chenshuai2144** [comment]
这个是因为 css 没有加载造成的，你可能需要做一些修改

**Comment by lvzheng0404** [comment]
@chenshuai2144 看了好久，就是不知道为啥样式没有生效，能帮忙看下为什么吗？

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/pull/3810
