### ISSUE TITLE
后台菜单数据，求大神帮个忙

### ISSUE THREAD

**Issue by Nickynodejs** [ant-design/ant-design-pro#373]
const menu =[
  {menuId:1,parentId:0,name:'数据中心',path:'dashboard',layout:'BasicLayout',},
  {menuId:2,parentId:0,name:'类目管理',path:'category'},
  {menuId:3,parentId:0,name:'用户管理',path:'UserManagement'},
  {menuId:5,parentId:1,name:'分析页',path:'analysis',address:'../routes/Dashboard/Analysis'},
  {menuId:6,parentId:1,name:'监控页',path:'monitor',address:'../routes/Dashboard/Monitor'},
  {menuId:7,parentId:1,name:'工作台',path:'workplace',address:'../routes/Dashboard/Workplace'},
  {menuId:8,parentId:2,name:'类目树图',path:'category',address:'../routes/Category/CategoryTree'},
  {menuId:9,parentId:3,name:'用户列表',path:'UserManagement',address:'../routes/UserManagement/UserManagement'},

]

后台大致给的动态菜单数据，address我用了dva的dynamic添加到component中加载不出来菜单对应的路由页面。不知道该如何解决。希望给点思路。

**Comment by nikogu** [comment]
有空读下：https://github.com/seajs/seajs/issues/545  然后贴代码请格式化。

因为你用的是动态加载，这样直接给变量的 path 是不行的，而且为什么后台服务器会存前端路由的 `address` 这种属性。

解决思路就是自己根据后台传递的标识信息（如这里的 path），然后通过前端匹配 __已经配置好的路由信息__ 比如：

```js
{
  analysis: dynamicWrapper(app, ['chart'], () => import('../routes/Dashboard/Analysis')),
}
```

构建你的路由就好了。

**Comment by Nickynodejs** [comment]
谢谢指点

**Comment by ychow** [comment]
@Nickynodejs     可以说说你是如何获取菜单数据，然后渲染的吗？ 我在menu.js里通过API拿到数据后，视图始终不更新。。

**Comment by seeyoumr** [comment]
@ychow 能把你在menu.js里面通过API拿到数据的代码粘一下吗？ O(∩_∩)O谢谢

**Comment by ychow** [comment]
@seeyoumr  在项目启动前，去请求就行。

**Comment by seeyoumr** [comment]
@ychow 谢谢，已实现。

**Comment by seeyoumr** [comment]
@MEEllis 在index.js里面预先加载菜单数据，存储在本地，后面的用到的地方就可以随便用了
