### ISSUE TITLE
在antd pro中打开色盲模式会出现的bug

### ISSUE THREAD

**Issue by qy394163797** [ant-design/ant-design-pro#3730]
hi，我发现在antd pro 中开启色弱模式，并且设置抽屉打开收起，会导致页面出现横向滚动条和幕布遮挡不正确，
![111](https://user-images.githubusercontent.com/29668722/54178075-6da59d00-44cf-11e9-9046-4094480fadeb.png)
![222](https://user-images.githubusercontent.com/29668722/54178152-c7a66280-44cf-11e9-99fa-8ed319bc46fc.png)

**Comment by xiaohuoni** [comment]
色弱模式的时候，右侧的悬浮按钮会跟随页面滚动。

**Comment by xiaohuoni** [comment]
@chenshuai2144 
色弱模式只是增加了滤镜，没定位到bug
```
.colorWeak {
  filter: invert(80%);
}
```

**Comment by chenshuai2144** [comment]
这个不是 bug，是别的原因。

**Comment by chenshuai2144** [comment]
是浏览器渲染模式的 bug，这个让人蛋疼，会破坏掉 flex

**Comment by chenshuai2144** [comment]
v4 fix

**Comment by backhamm** [comment]
.colorWeak {
  filter: invert(80%);
}
pro项目中的filter属性是绑定到#app上的，把这个类名绑定到html上就行了
