### ISSUE TITLE
请问各位前端大神约定路由配置router.config.js能否实现运行时通过mock接口动态加载路由，完全去除router.config.js？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#3731]

**Comment by afc163** [comment]
日经帖。@xiaohuoni @chenshuai2144 赶紧写个文档。

**Comment by zhuguangyue** [comment]
兄弟，如何？

**Comment by chenshuai2144** [comment]
做不到的，umi 需要 router.config.js 来生成 react-router 配置

**Comment by xiaohuoni** [comment]
@zhuguangyue 约定路由不需要配置router.config.js，看这个提交https://github.com/ant-design/ant-design-pro/commit/a22d400328a7a391ed5e5a5f2bba1a5fecf9fad7

**Comment by yutingzhao1991** [comment]
运行时可以通过 https://umijs.org/zh/guide/runtime-config.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9C%89%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE%EF%BC%9F 这个来修改路由，不过不是很推荐，这样会导致一些和路由配置相关的功能失效。

**Comment by jianshengzhao** [comment]
你这是想做动态权限吗
