### ISSUE TITLE
关于login组件的声明报错问题

### ISSUE THREAD

**Issue by mongofeng** [ant-design/ant-design-pro#3732]
![TIM截图20190312173130](https://user-images.githubusercontent.com/24306873/54189506-eb2bd600-44ec-11e9-8daf-0be4b23564a5.png)
![TIM截图20190312173248](https://user-images.githubusercontent.com/24306873/54189534-f7b02e80-44ec-11e9-9b99-fb4c788efdda.png)

**Comment by chenshuai2144** [comment]
很抱歉出现这个问题。
本周我闲下来了一些，我会发布一个新的版本。来解决这个问题
