### ISSUE TITLE
ts 的 antdpro 似乎没有给 action 定义类型

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design-pro#3734]
https://github.com/ant-design/ant-design-pro/blob/v3-typescript-and-maybe-hooks/src/models/list.ts

这样类型提示少了很多

**Comment by xiaohuoni** [comment]
你好，这个只是参考。ts版本请查看v4分支。正在开始完善。还有不足的地方。希望都加进来一起修改

**Comment by xiaohuoni** [comment]
ts相关的，在v4中处理，请关注https://github.com/ant-design/ant-design-pro/issues/3789
