### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by EnochHuan** [ant-design/ant-design-pro#3738]
` ERROR  Failed to compile with 12 errors                                                                        11:42:47

These relative modules were not found:

* ../404 in ./src/pages/.umi/router.js
* ../Account/Center/Applications in ./src/pages/.umi/router.js
* ../Account/Settings/BaseView in ./src/pages/.umi/router.js
* ../Dashboard/Analysis in ./src/pages/.umi/router.js
* ../Exception/403 in ./src/pages/.umi/router.js
* ../Forms/AdvancedForm in ./src/pages/.umi/router.js
* ../Forms/StepForm/Step1 in ./src/pages/.umi/router.js
* ../List/Applications in ./src/pages/.umi/router.js
* ../pages/Exception/403 in ./src/layouts/BasicLayout.js
* ./pt-BR/analysis in ./src/locales/pt-BR.js
* ./zh-CN/analysis in ./src/locales/zh-CN.js
* ./zh-TW/analysis in ./src/locales/zh-TW.js`

**Comment by Wine-in-June** [comment]
我的也是改路由都改不了
