### ISSUE TITLE
Table组件设置defaultExpandAllRows后初次加载树节点未展开

### ISSUE THREAD

**Issue by zwdgit** [ant-design/ant-design-pro#3739]
`<Table
              columns={this.columns}
              dataSource={list}
              defaultExpandAllRows  />,`

按照官方文档，Table组件配置了 defaultExpandAllRows ，数据 list 是请求后台存到redux中后，从redux拉到页面。

目前的问题是 在首次加载的时候，节点并未展开，重新加载一次页面后才正常

**Comment by szbboss** [comment]
我临时的解决方案：
list.length > 0 ？ (<Table columns={this.columns} dataSource={list} defaultExpandAllRows />) : (<div>no data</div>)

**Comment by zwdgit** [comment]
谢老哥！这个方案可以满足我的需求


| |
朱卫东
17862979705@163.com
|
签名由网易邮箱大师定制


在2019年03月13日 15:27，szbboss<notifications@github.com> 写道：

我临时的解决方案：
list.length > 0 ？ (

) : (
no data
)

**Comment by zwdgit** [comment]
> 我临时的解决方案：
> `list.length > 0 ？ (<Table columns={this.columns} dataSource={list} defaultExpandAllRows />) : (<div>no data</div>)`

谢老哥！这个方案可以满足我的需求
