### ISSUE TITLE
提出一下建议

### ISSUE THREAD

**Issue by liuhong1happy** [ant-design/ant-design-pro#374]
阅读了部分源码，提出一下建议：
1. 配置文件未独立提取出来，不方便后期部署。
2. .roadhogrc.mock.js和src/services/api.js 中所有api的代码混在一起，强烈建议分开（至少要分文件），这样有利于引导初次使用ant-design-pro开发者养成良好的习惯。拆分这些api为多个文件，也有利于协同开发。
3. api联调，有可能是逐个api进行调试的，建议组件中加入这样的配置文件。

期望能将组件做大做强，让更多人感受到ant-design-pro的强大之处。
伟大的背后往往更应该注重细节，加油！

**Comment by afc163** [comment]
@liuhong1happy 非常合理的建议，欢迎一起参与贡献。

**Comment by pkaq** [comment]
其实可以参考下 github.com/zuiidea/antd-admin 这个项目 很多地方还是比官方放出来的这个pro要优雅的 感觉官方放出来的就是个组件组合展示demo

**Comment by LayGit** [comment]
赞同 @pkaq ，特别是 `权限控制` 这块是管理后台很重要的功能，希望在 `Ant Design Pro` 中也能看见一些优雅的设计思路。

**Comment by afc163** [comment]
trace #394
