### ISSUE TITLE
打包后，怎么动态修改访问ip和端口

### ISSUE THREAD

**Issue by jiangwangfa** [ant-design/ant-design-pro#3740]
如何可配置的修改ip和端口，不用每次换个服务器(ip)，要重新修改打包？

**Comment by xiaohuoni** [comment]
打包和部署不是一个东西

**Comment by jiangwangfa** [comment]
ip可以采用配置文件获取吗？ 项目移动服务器还要重新修改ip打包，实在太麻烦了。 1044985235 邮箱：1044985235@qq.com 签名由 网易邮箱大师 定制 在2019年03月18日 10:34，陈小聪 写道： 打包和部署不是一个东西 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jiangwangfa** [comment]
> 打包和部署不是一个东西

ip可以采用配置文件获取吗？ 项目移动服务器还要重新修改ip打包，实在太麻烦了。

**Comment by chenshuai2144** [comment]
使用 nginx 进行配置，这种情况一般使用网关。

**Comment by xiaohuoni** [comment]
他这问题应该是指，项目里面http 的请求地址。这个好像都要一直改了重新发包。或者写在html里面。

**Comment by Free-Qi** [comment]
我们解决的是在public下写个配置文件，因为public下的文件在打包时是不被编译进去的，所以生成dist后任然可以修改这个public下的配置文件，之前项目在圣诞彩蛋那个版本（没记错好像是2.1.0）亲测好用！后续的话暂时没用过
