### ISSUE TITLE
404错误页面

### ISSUE THREAD

**Issue by Gaion** [ant-design/ant-design-pro#3741]
浏览器直接输入不存在的地址时（如：https://preview.pro.ant.design/user/1），页面内容空白
![image](https://user-images.githubusercontent.com/7481093/54267582-758b3d00-45b4-11e9-835f-7ebac988cb9c.png)

**Comment by wyfnet** [comment]
可以在/user的子路由routes下面加上{component: '404'}就可以解决空白的问题

**Comment by afc163** [comment]
@chenshuai2144 应该修一下。

**Comment by JerryMissTom** [comment]
建议在每个routes的最后加一个{component: '404'}用来兜底
