### ISSUE TITLE
proxy 代理问题

### ISSUE THREAD

**Issue by qianli8811** [ant-design/ant-design-pro#3743]
proxy这个问题，大家提了 这么多，为什么不修改一下呢？
![image](https://user-images.githubusercontent.com/6313040/54291101-0da21a00-45e7-11e9-93b0-2d40e11667bd.png)
![image](https://user-images.githubusercontent.com/6313040/54291115-12ff6480-45e7-11e9-8205-b0ca76493058.png)

**Comment by chenshuai2144** [comment]
proxy 本身没有问题。跨域作为前端基本功，虽然大家一直再问，主要还是用法问题， session  cookie jwt这些都不仅仅是前端的问题。
比如 cookie无法跨域这是 chrome 的逻辑。
