### ISSUE TITLE
从2.1.1升级到2.2.0后, 在非model目录下的model文件无法被识别

### ISSUE THREAD

**Issue by tianzhou** [ant-design/ant-design-pro#3744]
我在基于ant-design-pro构建应用的时候，把自己添加的文件单独分开来，比如说我的应用名叫做foo。那么我会在src下自建一个目录
foo/
   models/
   components/
   services/
   pages/

这样说为了方便升级ant-design-pro。但是当我从2.1.1升级到2.2.0后发现，本来在foo/models/下定义的model无法被识别了

**Comment by chenshuai2144** [comment]
升级一下 umi？
非 src/models/下面的 modal 将会被异步加载，你可能不能全局使用它
