### ISSUE TITLE
ant design pro  table表格每秒动态添加删除行， 十几分钟后浏览器崩溃

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design-pro#3747]
ant design pro  table表格每秒动态添加删除行， 二十分钟后浏览器崩溃，chrome进行监控，jsheap为2088383472，请问如何在重新刷新后清除js缓存，或者有什么更好的方法。

**Comment by afc163** [comment]
可能有轻微的内存泄漏，我们比较少这种场景，@m26597 可以帮忙深入排查一下。

**Comment by m26597** [comment]
非常稳定，每两秒浏览器内存增加1M，有什么思路么，可以从哪入手？

**Comment by m26597** [comment]
刚拍了heap快照，object数1925990个，总计占有内存167867472Byte，又继续跑了5min浏览器就崩溃了。

**Comment by m26597** [comment]
页面实时功能有近千个自定义组件，调试发现，如果控制每一个组件中不是所有字段都变化，那么内存就不会上涨，如果控制组件中所有字段都变化重新绘制的话内存就上涨不停

**Comment by chenshuai2144** [comment]
可以把你的 table 的代码给我们看一下吗，
我猜测可能是 render 的问题

**Comment by m26597** [comment]
稍等，最近忙着开发新功能，等功能点做好之后我会提供个demo

**Comment by AimLuo** [comment]
几分钟就炸了，这就有点难受了。我上次的项目由于用的定时器保持通信跑四个小时会炸掉，排查太恶心了。最后让浏览器跑两小时就reload。😂

**Comment by xiaohuoni** [comment]
你们这样搞的我很好奇！

**Comment by AimLuo** [comment]
> 你们这样搞的我很好奇！

没什么好奇的，location.reload()之后，网页会被回收，内存会被释放。我这是最低级的做法，没有从根本上解决问题。像你的需求肯定就不能这样了，只能找内存泄漏点。

**Comment by xiaohuoni** [comment]
@m26597 帮忙给个重现
