### ISSUE TITLE
主菜单收缩的宽度为80，我看有个变量@menu-collapsed-width，但是没什么关联好像 

### ISSUE THREAD

**Issue by yuanguandong** [ant-design/ant-design-pro#3748]
期望可以定义主菜单收缩起来的宽度，80目前来看太宽了，我们想窄一点，40 或50，  观察了menu, 并没有这样一个属性，我也向react-menu提了这个。
这个应该属于menu的一个属性，collapsedWidth, 
谢谢！！

**Comment by chenshuai2144** [comment]
@menu-collapsed-width 是 less 变量，你可以先通过 css 自定义。

**Comment by lsq2020** [comment]
![WechatIMG20](https://user-images.githubusercontent.com/21995612/55061258-3d085a80-50ae-11e9-9701-c46b237fdb5d.png)
![image](https://user-images.githubusercontent.com/21995612/55061434-bd2ec000-50ae-11e9-8c38-fad5f685f4e5.png)

1.设置Layout.Sider 的 collapsedWidth
2. @menu-collapsed-width 也要设置，不然logo不会居中显示

**Comment by yuanguandong** [comment]
good job , thanks
