### ISSUE TITLE
fetch 请问这个东西 兼容IE9吗？你们添加的垫片可以解决这个问题吗？

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#375]
因为我需要兼容IE9所以问了这个问题 

如果不兼容 你们有写一个AJAX promise吗？ 不然我写一个给你推上去（你们应该不会要）

**Comment by afc163** [comment]
pro 只支持 IE11 及以上，如果需要 polyfill 可以自行添加。
