### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#3750]
![image](https://user-images.githubusercontent.com/7875572/54345318-c9ae2400-467d-11e9-9bed-0ab8492db3be.png)

```
  33 | }
  34 | export default connect(({ menu: menuModel, login: loginModel }) => ({
  35 |   routerData: menuModel.routerData,
> 36 |   status: loginModel.status,
  37 | }))(AuthComponent);
```

**Comment by VitorGultzgoff** [comment]
Actually what's the namespace of your _login_ **model** ?
Before open an issue, try to make a description about it and detail technically and conceptually.

Just guessing without context informations that you'd fix with the below code: 

```
export default connect(({ menuModel, loginModel }) => ({
routerData: menuModel.routerData,
status: loginModel.status,
}))(AuthComponent);
```
