### ISSUE TITLE
Component - Bar chart - Issue in Scale

### ISSUE THREAD

**Issue by VitorGultzgoff** [ant-design/ant-design-pro#3753]
During the development of a specific business scenario in a project, I needed to switch in a Dashboard page between _Pie_ and _Bar_ charts that represents the same data in different forms.

```
<Pie
  animate={true}
  hasLegend
  total={() => {generalChartData[actualOccurrenceTypeKey].reduce((pre, now) => now.y + pre, 0)}}
  data={generalChartData[actualOccurrenceTypeKey]}
  height={248}
  lineWidth={4} />
```

```
<Bar data={generalChartData[actualOccurrenceTypeKey]} height={248} />
```

Initially I had received "_bizcharts error_" which analysing, I figure out that the component _Bar_ only receives **data** that contains the parameter _x_ in the _date format_ forced by the scale. So based on that fact, the component isn't prepared to used as [Basic bar chart](https://bizcharts.net/products/bizCharts/demo/detail?id=bar-basic).

**Suggestion to fix**

- An optional **prop** _scale_ would helps to turn into dynamic content and will resolve this issue.
- An optional **prop** _hasScale_ will defines whether to use the default scale or not and will resolve this issue.

I've already tested those suggestions.

**Comment by chenshuai2144** [comment]
Welcome to your public relations

**Comment by VitorGultzgoff** [comment]
Actually, I analyzed and the project which I'm working on has this issue because uses an **old version** of _Ant Design Pro_, nowadays the **scale** of the _master_ in the _Pie_ component works perfectly.

Sorry for this issue, closing...
