### ISSUE TITLE
权限组件的文档 上面的代码有bug.请知晓修改.

### ISSUE THREAD

**Issue by LukerSpringtree** [ant-design/ant-design-pro#3754]
权限组件: 中secured demo used 的示范如下:

import RenderAuthorized from 'ant-design-pro/lib/Authorized';
import { Alert } from 'antd';

const { Secured } = RenderAuthorized('user');

@Secured('admin')
class TestSecuredString extends React.Component {
  render() {
    <Alert message="user Passed!" type="success" showIcon />;
  }
}
ReactDOM.render(
  <div>
    <TestSecuredString />
  </div>,
  mountNode,
);

其中:
TestSecuredString 这一组件中的render 方法 需要有 return

**Comment by afc163** [comment]
来 PR

**Comment by LukerSpringtree** [comment]
@afc163 
提了 第一次提 PR 哈哈  请多多包涵

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/pull/3757

Thx! @LukerSpringtree
