### ISSUE TITLE
Can't Remove MiniProgress tooltip

### ISSUE THREAD

**Issue by bgold0** [ant-design/ant-design-pro#3761]
This is a bug as you can't change it or remove it.
`<MiniProgress color="#FDBB32" percent={3} strokeWidth={15} target={10} />`

![Screen Shot 2019-03-15 at 1 38 07 PM](https://user-images.githubusercontent.com/4645400/54450776-a63fb380-4727-11e9-9d39-f9658134a7e4.png)

**Comment by VitorGultzgoff** [comment]
Analysing the component I realized that piece of the tooltip title it's static and might need to fix it:

" <Tooltip title={`目标值: ${target}%`}> "

**Comment by chenshuai2144** [comment]
May need your own calculations。
Welcome to your pr
