### ISSUE TITLE
求 配置，打包到 dist / static 方法

### ISSUE THREAD

**Issue by golangpkg** [ant-design/ant-design-pro#3762]
前后端，开发。找不到 配置 static 静态文件的方法。
打包生成的文件都放到 dist 目录下面，没有按照 js css 区分，也没有放到 static 目录。
配置半天也没有配置成功。

**Comment by chenshuai2144** [comment]
可以用这个
https://umijs.org/zh/config/#outputpath

> 没有按照 js css 区分

这个暂时做不到

**Comment by mtianyan** [comment]
@chenshuai2144  过去这么久了， 这个现在可以做到了么？我尝试用chainWebpack 来弄，没有搞成。
```
  chainWebpack: (config) => {
    config.module.rule('js').use('babel-loader').loader('babel-loader').tap(options=>{
      options[0] ={
        filepath : '../static/'
      }
      return options;
    })
  }
```
