### ISSUE TITLE
抽屉中使用下拉菜单弹出对话框，会造成下拉菜单失效

### ISSUE THREAD

**Issue by zwdgit** [ant-design/ant-design-pro#3763]
问题描述：

在项目中使用抽屉(Drawer)，底部添加了一个下拉菜单(Dropdown)，通过点击下拉菜单中的按钮弹出确认对话框(Modal.confirm)，但是当关闭对话框之后，下拉菜单就会失效，也就是不再显示各项菜单按钮

<img width="778" alt="WX20190316-085748@2x" src="https://user-images.githubusercontent.com/28926324/54468659-e35c8200-47c9-11e9-88e5-3394a58ca3bd.png">

**Comment by chenshuai2144** [comment]
感觉是 z-index 的问题，有一个可重现的 demo 吗？
