### ISSUE TITLE
生产环境如何隐藏控制台信息, 坐等!

### ISSUE THREAD

**Issue by wangxiangchn** [ant-design/ant-design-pro#3766]
生产环境如何隐藏控制台信息,大佬们,帮帮忙

**Comment by DanesFu** [comment]
母鸡啊

**Comment by DanesFu** [comment]
大佬快来回答一下

**Comment by chenshuai2144** [comment]
重写掉 console.log就好了 最简单

**Comment by JerryMissTom** [comment]
@wangxiangchn 
```
  // 生产环境去掉console日志
if( isProduction ){
    window.console.log = function(){};
    window.console.info = function(){};
    window.console.warn = function(){};
    window.console.error = function(){};
    window.console.debug = function(){};
  }

```

**Comment by afc163** [comment]
https://stackoverflow.com/questions/41040266/remove-console-logs-with-webpack-uglify

**Comment by wangxiangchn** [comment]
> @wangxiangchn
> 
> ```
>   // 生产环境去掉console日志
> if( isProduction ){
>     window.console.log = function(){};
>     window.console.info = function(){};
>     window.console.warn = function(){};
>     window.console.error = function(){};
>     window.console.debug = function(){};
>   }
> ```

这个有点太暴力了吧

**Comment by wangxiangchn** [comment]
> https://stackoverflow.com/questions/41040266/remove-console-logs-with-webpack-uglify

好的,感谢

**Comment by wangxiangchn** [comment]
// 1
$ npm install babel-plugin-transform-remove-console -D

// 2、config.prod.js
export default {
  extraBabelPlugins: [
    ['transform-remove-console', { exclude: [ 'error', 'info' ] }],
  ],
};


// 3 package.json
"build": "UMI_ENV=prod umi build"

问题已解决,采用 umi群中大佬给的方案
