### ISSUE TITLE
less文件问题，导致webpack卡死

### ISSUE THREAD

**Issue by huayu611** [ant-design/ant-design-pro#3767]
ant design 团队：
    你好，
  return Promise.resolve(
    prettier.format(content, {
      parser: "less"
    })
  );
loopAllLess.js
如果less文件有问题，prettier.format会卡死，导致promiss后面的生成文件 无法走下去。后面在读取less组件中会卡死。使整个webpack卡住不动。

建议优化一下，使用回显提示一下。

多谢！

**Comment by chenshuai2144** [comment]
你可以先删除这个插件。他的主要功能是换主题。

**Comment by uv-w** [comment]
good

**Comment by chenshuai2144** [comment]
https://beta.pro.ant.design/blog/change-theme-cn
