### ISSUE TITLE
拉最新的代码编译启动后，页面无法访问

### ISSUE THREAD

**Issue by mosswang** [ant-design/ant-design-pro#3768]

**Comment by mosswang** [comment]
刚才拉了最新的代码，编译启动出现了一个警告，但是访问页面报错了，错误如下。

启动时候，出现的一个异常：
![image](https://user-images.githubusercontent.com/10702492/54474436-c0f55380-481f-11e9-9a5f-9e32d054bca3.png)



浏览器输入 http://localhost:8000/
![image](https://user-images.githubusercontent.com/10702492/54474456-f7cb6980-481f-11e9-88f9-8f865a9a6bfe.png)

**Comment by RootAnt** [comment]
Pleas follow #3765

**Comment by mosswang** [comment]
> Please follow #3765

thanks.
