### ISSUE TITLE
Antd-pro的 pages/Authorized.js 文件代码有错

### ISSUE THREAD

**Issue by LukerSpringtree** [ant-design/ant-design-pro#3772]
1. getRouteAuthority 会返回 undefined 这个值
如果返回undefined这个值
Authorized的 authority 属性值就是 undefined
就是说页面是不需要 权限监控的.  个人感觉这边处理有误.

2.  noMatch={isLogin ? <Redirect to="/exception/403" /> : <Redirect to="/user/login" />}
这边的 Redirect  403  一直 报错:

`umi.js:17990 Warning: You tried to redirect to the same route you're currently on: "/exception/403"`

**Comment by lpx7788** [comment]
我也是这样的问题
