### ISSUE TITLE
fdmap-0.2.js:72 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.通过document添加cript标签加载js报这个错，请问该如何在解决？在网上有搜到类似问题，但是解决方案都不行，有没有可以在文档生成前配置添加外部js的地方

### ISSUE THREAD

**Issue by jiejieHome** [ant-design/ant-design-pro#3773]

**Comment by xiaohuoni** [comment]
不要把标题当正文，看了半天标题，没理清楚问题是啥！抱歉！

**Comment by jiejieHome** [comment]
这个问题我不是已经关闭了吗，您说的第一个问题，我会改正，但是我是有点好奇，你们阿里的人说话都是喜欢用祈使句的吗？！也许对于我这种描述问题不清楚的人，你们就应该建立一个黑名单，把我拉进去，也不必回复我，浪费你们宝贵时间！


| |
liujunjie
|
|
邮箱：jiejie_home@163.com
|

Signature is customized by Netease Mail Master

在2019年03月18日 10:00，陈小聪 写道：

不要把标题当正文，看了半天标题，没理清楚问题是啥！抱歉！

**Comment by xiaohuoni** [comment]
@jiejieHome 你咋啦？我说了啥你不高兴？我又不是阿里人！

**Comment by xiaohuoni** [comment]
[二哈]！！！

**Comment by afc163** [comment]
@jiejieHome  Ant Design 的维护者不都是阿里人。
