### ISSUE TITLE
如何移除国际化和权限系统

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#3775]
很多项目不需要这两个功能，但是移除起来会很麻烦，希望提供方便的可插拔方法，至少有文档可以操作。

**Comment by xiaohuoni** [comment]
@yutingzhao1991 权限还是挺好移除的，现在的，配置是的只要去掉config里面的所有权限配置，约定式的，去掉权限插件就可以。国际化可选择，这个是v4的需求。不知道愚导师，打算怎么搞。

**Comment by imhele** [comment]
准备想试一下这种：prettier 一遍，再 lint 一遍，然后在文件顶部找从 umi-plugin-locale 引用了哪些 locale 功能，再以类似 `formatMessage({` 和 `})` 的组合，用 template 替换成 `ANY_PREFIX_${id}` ，再从 locales 文件里全局替换一遍

**Comment by afc163** [comment]
目标是要提供文档，减少答疑的压力。

**Comment by yutingzhao1991** [comment]
在 V4 中，初始化脚手架通过 cli 来处理，是否要权限和国际化都可以直接在 cli 中选择。区块应该是和权限那块分离的，国际化的话可以通过在 umi-plugin-pro-block 这里面通过 umi 的插件实现。技术上感觉就是通过 AST 或者简单点字符串匹配就可以。

文档的话，应该建一个 FAQ，另外内容上可以考虑和 umi 的 FAQ 一起建设，有大部分问题都是重复的。应该是 umi 先有一个 FAQ，pro 的 FAQ 应该包含 umi 的。

**Comment by yutingzhao1991** [comment]
umi 现在有一个 ISSUE 作为 FAQ https://github.com/umijs/umi/issues/1421 这样感觉并不好浏览，也不好维护。

是不是想想找个地方统一的建一个结构化的 FAQ，语雀？github wiki，https://umijs.org ？ @sorrycc

**Comment by xiaohuoni** [comment]
移除国际化，这个还要再看看

**Comment by afc163** [comment]
- [ ] 移除国际化

**Comment by xiaohuoni** [comment]
- [ ] 增加权限系统配置

**Comment by imhele** [comment]
> umi 现在有一个 ISSUE 作为 FAQ [umijs/umi#1421](https://github.com/umijs/umi/issues/1421) 这样感觉并不好浏览，也不好维护。
> 
> 是不是想想找个地方统一的建一个结构化的 FAQ，语雀？github wiki，https://umijs.org ？ @sorrycc

感觉可以把语雀的讨论板块用起来？https://www.yuque.com/ant-design/topics

**Comment by pkaq** [comment]
终于我也遇到了需要移除国际化的一天 umi里的enable形同虚设啊

**Comment by imhele** [comment]
刚刚做完了编译和合并国际化文案，发现 menu 的国际化是这样用的
![image](https://user-images.githubusercontent.com/32428655/55087265-cc306500-50e4-11e9-8e10-2608a39fe4d0.png)
以及移除国际化需要移除 GlobalHeader 中的 SelectLang ，现在想到的一种最简单的方法就是在这些地方写注释，用 tsdoc 解析之后处理这部分内容：
```tsx
<div>
  {/* if-locale-enable-next-line */}
  <SelectLang className={styles.action} />
</div>
```
```ts
  /* if-locale-enable*/
  const pageName = menu.disableLocal
    ? currRouterData.name
    : formatMessage({
        id: currRouterData.locale || currRouterData.name!,
        defaultMessage: currRouterData.name,
      });

  return `${pageName} - ${title}`;
  /* else-locale-enable*/
  return `${currRouterData.name} - ${title}`;
  /* endif-locale-enable*/
```

**Comment by xiaohuoni** [comment]
感觉增加一点逻辑会不会简单一点，加一个国际化的开关。

**Comment by imhele** [comment]
增加开关需要在 umi 做，主要是需要移除对 umi-plugin-locale 的所有引用

**Comment by xiaohuoni** [comment]
在umi里面加其实没什么作用，业务层级的，应该在pro的配置文件里面加吧？
https://github.com/ant-design/ant-design-pro/pull/3848

**Comment by imhele** [comment]
> 在umi里面加其实没什么作用，业务层级的，应该在pro的配置文件里面加吧？
> #3848

好像是，在 block 可以不使用 locale 特性，避免外界没有开启 locale，主要就是 pro 的配置了

**Comment by imhele** [comment]
目前可以移除 `formatMessage` 了
![image](https://user-images.githubusercontent.com/32428655/55128489-b6578a00-514e-11e9-97d6-74c767683c92.png)
![image](https://user-images.githubusercontent.com/32428655/55128519-d4bd8580-514e-11e9-8007-4c038958f923.png)

**Comment by LukerSpringtree** [comment]
我手动 把所有关于 local 相关的 还有 set...  相关的代码全部删除掉了

**Comment by afc163** [comment]
需要写一个脚本 `npm run remove-locale` 一键清除。

**Comment by imhele** [comment]
> 需要写一个脚本 `npm run remove-locale` 一键清除。

需要用到 typescript 依赖来编译一遍文件，放到 pro-cli 里会比较合适，以后也可以用来选择性的编译 ts 给 js 用户使用

**Comment by xiaohuoni** [comment]
我在想一键清除之后，能不能一键添加？我们有一个项目，开发完了，快上线的时候，临时增加了国际化的要求，我分到了23个文件的intl（总的有400多个），因为明天要的，所以临时一点点的整理，我就在想，其实我并不关心国际化对应的key值，通过检测文字为中文，自动提取国际化标示，自动添加国际化代码，好像可以实现一键添加国际化的需求。

**Comment by imhele** [comment]
> 我在想一键清除之后，能不能一键添加？我们有一个项目，开发完了，快上线的时候，临时增加了国际化的要求，我分到了23个文件的intl（总的有400多个），因为明天要的，所以临时一点点的整理，我就在想，其实我并不关心国际化对应的key值，通过检测文字为中文，自动提取国际化标示，自动添加国际化代码，好像可以实现一键添加国际化的需求。

https://github.com/alibaba/kiwi

**Comment by xiaohuoni** [comment]
手动替换，果然是非常愚蠢的，我高估了自己的耐心

**Comment by xiaohuoni** [comment]
https://github.com/jianfenkezhan/i18njs

**Comment by pkaq** [comment]
其实可以出一个纯洁版 反正clone到pro的代码之后 不仅仅是要删国际化 pages下的几乎都要删 处理菜单 处理token blabla

**Comment by xoptimal** [comment]
这个问题还没有一个合理的解决方案吗

**Comment by chenshuai2144** [comment]
umi-local 这个插件做一个方法吧。
设置 locale 就把 formatMessage 变成 <></>

**Comment by imhele** [comment]
> umi-local 这个插件做一个方法吧。
> 设置 locale 就把 formatMessage 变成 <></>
> 
> ```
> const formatMessage = (id)=>{
>    if(!locale){
>        return id
>    }
> }
> ```

最好不直接关掉 locale ，可能还有人需要 locale 一键开启 antd 的本地化。判断条件可以改成 locales 文件夹下没有国际化文案文件则原样返回，或者新增一个配置

**Comment by xiaohuoni** [comment]
子给自足，一键增加国际化。
https://github.com/alitajs/umi-plugin-cn-intl

**Comment by Thyiad** [comment]
打包之后怎么成了英文啊。。代码里locale设置成了zh-CN的

**Comment by Thyiad** [comment]
还有个baseNavigator配置，会自动取navigator.language的值

**Comment by jianfenkezhan** [comment]
国际化有点难移除 建议出个纯洁版本。另外，我觉得词条的 Key 是什么不太重要，但被转化成 a.b.c 这样反而有点难受了，很烦恼。不能完成快速国际化

**Comment by kennylbj** [comment]
我建议弄一个cli，通过配置的方式来生成项目
支持用户选择：启用国际化、支持electron、需要启用哪些页面这样。

**Comment by zywkuo** [comment]
目前v4版本移除全球化是不是更加麻烦了，formatMessage在好多个页面都使用了，还需要一个个删除。。

**Comment by Hansuku** [comment]
> 还有个baseNavigator配置，会自动取navigator.language的值

把locale的 enable 和 baseNavigator 都关了就可以默认中文了。。。

**Comment by chenshuai2144** [comment]
https://github.com/chenshuai2144/umi-remove-locale
写了这个库。现在只支持删除 区块的 locale，近期会支持脚手架的删除

**Comment by puretang** [comment]
新项目的话，没那么麻烦了。在 BasicLayout 里把所有使用 formatMessage 方法的地方干掉就可以了。
// import { formatMessage } from 'umi-plugin-react/locale';

**Comment by pkaq** [comment]
其实权限也几无卵用 一块出个 unauth 吧

**Comment by LukerSpringtree** [comment]
> 其实权限也几无卵用 一块出个 unauth 吧

你不配就好了就当全权限了 而且也不影响开发.

**Comment by yucccc** [comment]
目前有方案了吗 头大 国际化本就是个例需求 怎么就默认集成到项目里了呢 头秃...

**Comment by afc163** [comment]
@chenshuai2144 来回复一个当前解决方案。

**Comment by puretang** [comment]
@yucccc 如果 package.json 里有 "i18n-remove": "pro i18n-remove --locale=zh-CN --write",可以尝试运行 npm run i18n-remove

**Comment by yucccc** [comment]
@puretang 会报.eslintrc.js的错 执行不了

**Comment by chenshuai2144** [comment]
现在已经很好移除了

**Comment by afc163** [comment]
> 现在已经很好移除了

你需要提供一个傻瓜式的解决方案，而不是回复一句现在可以了。

**Comment by shx996** [comment]
@afc163 而且我发现官方提供的 i18n-remove 命令执行完后，再执行test ，一大堆错误。

**Comment by afc163** [comment]
@shx996 可以到 https://github.com/chenshuai2144/umi-remove-locale/issues 这里反馈一下，提供一下重现步骤。

**Comment by shwzh** [comment]
> > 需要写一个脚本 `npm run remove-locale` 一键清除。
> 
> 需要用到 typescript 依赖来编译一遍 `locales/*.ts` 文件，放到 pro-cli 里会比较合适，以后也可以用来选择性的编译 ts 给 js 用户使用

请问功能是否已经实现，能否借鉴一下，谢谢

**Comment by shwzh** [comment]
> js

@yucccc 如何解决的 解决了吗
