### ISSUE TITLE
npm run lint-staged 出错

### ISSUE THREAD

**Issue by jassonxian** [ant-design/ant-design-pro#3780]
通过create-umi  选择ant-design-pro，创建一个简单项目，就添加了一个less文件，在run lint-staged时出错
![image](https://user-images.githubusercontent.com/21199561/54515397-e3f64380-4996-11e9-8d75-6f4e5381a8f9.png)
执行run prettier后依然如此
node v8.15.1

**Comment by chenshuai2144** [comment]
找到这个文件，然后去 prettier 一下。
他应该会自动帮你修改的

**Comment by jassonxian** [comment]
![image](https://user-images.githubusercontent.com/21199561/54576200-1f921b80-4a32-11e9-8587-dc10e4868d3f.png)
prettier 成功，还是会这样

**Comment by afc163** [comment]
直接用 ant-design-pro 的 master 试试？

**Comment by xiaohuoni** [comment]
@jassonxian 加了什么文件，加载什么位置，里面是什么？

**Comment by chenshuai2144** [comment]
这个应该是因为你的文件本身有语法错误才会造成这个问题
