### ISSUE TITLE
为什么Ant Design Pro官网上的例子跑不起来了

### ISSUE THREAD

**Issue by wqqiangwang** [ant-design/ant-design-pro#3781]
cnpm i;
cnpm start
之后报错：
1.Uncaught TypeError: Cannot read property 'Consumer' of undefined

![image](https://user-images.githubusercontent.com/37586244/54516775-de026180-499a-11e9-9239-2cf0bc39af96.png)

**Comment by rebornchris** [comment]
Please follow #3765

**Comment by wqqiangwang** [comment]
The problem has not been solved.

**Comment by xiaohuoni** [comment]
固定一下react-router的版本4.3

**Comment by wqqiangwang** [comment]
ok!ok!  The problem has been solved. Thanks!
