### ISSUE TITLE
umi.js:1 TypeError: Cannot read property 'Consumer' of undefined

### ISSUE THREAD

**Issue by Quanzhitong** [ant-design/ant-design-pro#3782]
本地锁定 react-router-dom版本为4.3.1；npm start，项目启动本地没有问题，但是构建发布之后，线上访问，就显示白屏，报错
umi.js:1 TypeError: Cannot read property 'Consumer' of undefined；
构建日志里查到
1016 warning in ./node_modules/react-router-dom/esm/react-router-dom.js
1017"export '__RouterContext' was not found in 'react-router'

**Comment by liangjz92** [comment]
我也遇到了同样的问题

**Comment by CarolineJason** [comment]
同问，今天下午遇到的这个问题，上礼拜我还是好好的。 怎么解决，降版本行吗？

**Comment by jdfdcc** [comment]
我也遇到了 咋解决啊

**Comment by wqjiao** [comment]
我也遇到了,刚clone下来，然后安装运行就报了这个错误呢

**Comment by imhele** [comment]
#3781

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/3783

**Comment by sorrycc** [comment]
参考 https://github.com/sorrycc/blog/issues/82

**Comment by Quanzhitong** [comment]
> 我也遇到了,刚clone下来，然后安装运行就报了这个错误呢



> 参考 [sorrycc/blog#82](https://github.com/sorrycc/blog/issues/82)

此处是正解，感谢~
