### ISSUE TITLE
npm run build构建问题

### ISSUE THREAD

**Issue by xaruy** [ant-design/ant-design-pro#3783]
不管是用 cnpm还是npm 打包项目，都会报下面的错误
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in '/Users/zou/Project/js/qc_bussiness_web/node_modules/_react-router-dom@4.4.0@react-router-dom/esm'
删除node_modules重新打包也是一样，网上也没找到答案。

**Comment by xiaohuoni** [comment]
react-router的相关版本全部锁定在4.3,就没有这个问题。

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/3782 这里维护了

**Comment by sorrycc** [comment]
参考 https://github.com/sorrycc/blog/issues/82
