### ISSUE TITLE
V3 && V4

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#3784]
个人建议

- V3版本：将antd pro组件更换为antd组件

- V4版本：应用区块，搞一个从零搭建的框架

发版本的周期太长，影响社区的积极性

**Comment by afc163** [comment]
V3 很快就会合流到 V4 里了。

cc @xiaohuoni @imhele

**Comment by yutingzhao1991** [comment]
V3 不太再适合做大的调整了，不然后面合并到 V4 会比较麻烦。是不是可以把 V4 的可用性弄上来，然后把主分支切换到 V4，鼓励在 V4 上迭代走起来。

**Comment by kaoding** [comment]
做一个广告：有兴趣一起创业的兄弟不，坐标上海张江，最缺前端，使用这套（ antd pro + umi + dva）包打天下的，欢迎联系我，一起来“怼”。

**Comment by xiaohuoni** [comment]
V3里面有用的已经合并到V4去，V3按实际意义上来说，只有后面往pro-block转移代码的时候，能够提供一点参考，之外已经没有其他意义了。
建议有什么想法直接在v4的基础上面讨论。

**Comment by yutingzhao1991** [comment]
https://github.com/ant-design/ant-design-pro/issues/3789 Just Do It!
