### ISSUE TITLE
ant-design-pro是否支持三级菜单

### ISSUE THREAD

**Issue by mosswang** [ant-design/ant-design-pro#3785]

**Comment by mosswang** [comment]
下载了官网例子，在摸索中想起了配置一个三级菜单做一下实践，但是发现报错。
router.config.js代码片段:

{
        name : '系统管理',
        icon : 'setting',
        path : '/system',
        routes : [
          {
            name : '参数管理',
            icon : 'compass',
            path : '/params',
            routes : [
              {name : '系统参数管理', path : '/system/params/sysparams/list', component : './System/Params/SystemParams/SystemParamsList'},
              {name : '新增', hideInMenu : true, path : '/system/params/sysparams/add'},
              {name : '修改', hideInMenu : true, path : '/system/params/sysparams/edit'},
              {name : '删除', hideInMenu : true, path : '/system/params/sysparams/delete'},

              {name : '应用参数管理', path : '/system/params/appparams/list'},
              {name : '新增', hideInMenu : true, path : '/system/params/appparams/add'},
              {name : '修改', hideInMenu : true, path : '/system/params/appparams/edit'},
              {name : '删除', hideInMenu : true, path : '/system/params/appparams/delete'},
              {
                component: '404',
              },
            ]
          }

组件js位置如下:
![image](https://user-images.githubusercontent.com/10702492/54527812-ffbd1200-49b5-11e9-96af-47ae08af626b.png)


菜单可以显示，但是点击页面会报错:
![image](https://user-images.githubusercontent.com/10702492/54527408-cafc8b00-49b4-11e9-8f47-2b6c434d1ca0.png)

请问我是哪里配置错误了吗？

**Comment by chenshuai2144** [comment]
你的组件呢？

**Comment by mosswang** [comment]
修改成这样既可:
{
        name : '系统管理',
        icon : 'setting',
        path : '/system',
        routes : [
          {
            name : '参数管理',
            icon : 'compass',
            path : '/system/params',
            routes : [
              //{path: '/system/params', redirect: '/system/params/sysparams/list'},
              {name : '系统参数管理', path : '/system/params/sysparams/list', component : './System/Params/SystemParams/SystemParamsList'},
            ]
          },
          {component: '404'},
        ]
      },
二级菜单的path要带上第一级的路径。

**Comment by GIn-Liu** [comment]
system下的params改为/system/params试试
