### ISSUE TITLE
windows下dev以后是空白页面

### ISSUE THREAD

**Issue by longearshortail** [ant-design/ant-design-pro#3786]
按照教程 https://pro.ant.design/docs/getting-started-cn

yarn start或者build之后也没有报错，自动打开了页面，但是是空白页面。

系统是win7 64位

地址直接输入页面也是空白页面
http://localhost:8000/my-project/user
http://localhost:8000/user

![image](https://user-images.githubusercontent.com/32356094/54530647-49a9f600-49be-11e9-8bed-4a820c3179c8.png)

这种该怎么确定问题出在哪里呢？

**Comment by xiaohuoni** [comment]
看报错是啥

**Comment by xch1029** [comment]
#3764
