### ISSUE TITLE
SpringBoot 如何拦截并重定向到 Ant Design Pro 的前台错误页面？

### ISSUE THREAD

**Issue by wuchunfu** [ant-design/ant-design-pro#3788]
我现在有一个问题，我现在尝试了很多方法，但是我无法通过 `SpringBoot` 的拦截器拦截并重定向到 `Ant Design Pro` 的前台错误页面，或者如何通过 `Ant Design Pro` 的前台页面拦截并重定向到错误页面。

**Comment by chenshuai2144** [comment]
全部交给前端，后台做一个 resturl 的服务器就好了，
返回相应的状态码让前端处理

**Comment by wuchunfu** [comment]
我们现在是在做一个 `License` 的功能，如果 `License` 过期的话，点击后台管理页面上的所有菜单都重定向到 `License` 过期的页面，我之前想过你给我的建议的做法，但是我不知道如果去实现拦截并重定向到 
`License` 过期的页面，期望您能帮到我。

**Comment by chenshuai2144** [comment]
你可以用 response.sendRedirect 来重定向 url，重定向到前端的页面就好了。
比如 response.sendRedirect('https://preview.pro.ant.design/exception/404')

**Comment by wuchunfu** [comment]
你现在的做法是使用 `SpringBoot` 的拦截器进行重定向还是通过前台 `effects` 进行重定向，然后还有你这个重定向的地址是前台页面的完整地址还是前台页面的路由地址？

**Comment by chenshuai2144** [comment]
SpringBoot 的拦截器比较好。
是前台页面的路由地址。相对路径

**Comment by wuchunfu** [comment]
我今天也是这么做的但是没有成功实现页面拦截和重定向，以下是我的后台代码
```java
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        if (request.getRequestURI().equals("/users/getAll/") ||
                request.getRequestURI().equals("/users/getAll")) {
            response.sendRedirect("/HomePage/Index");
            return false;
        } else {
            return true;
        }
    }
```
其中 `/HomePage/Index` 是我的前台的一个路由地址，是我想要重定向的页面，我不知道我现在的问题是在哪儿，我希望能得到您的帮助。

**Comment by ylooq** [comment]
> 我今天也是这么做的但是没有成功实现页面拦截和重定向，以下是我的后台代码
> 
> ```java
>     @Override
>     public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
>         if (request.getRequestURI().equals("/users/getAll/") ||
>                 request.getRequestURI().equals("/users/getAll")) {
>             response.sendRedirect("/HomePage/Index");
>             return false;
>         } else {
>             return true;
>         }
>     }
> ```
> 
> 其中 `/HomePage/Index` 是我的前台的一个路由地址，是我想要重定向的页面，我不知道我现在的问题是在哪儿，我希望能得到您的帮助。

应该要用前台路由路径吧

**Comment by wuchunfu** [comment]
这种重定向的方式好像不是太适合前后端分离的项目，如果不重定向的话，那如何将 `preHandle` 方法的返回值或数据返回到 `Controller` 层呢？

**Comment by xiaohuoni** [comment]
你可以尝试一下，如果数据很少的话，可以通过url传参数，如果数据很多，可以通过url传参数再请求服务端的方式来获取数据

**Comment by 13856093240** [comment]
请问，前后端分离，后端通过过滤器拦截请求，如何没有认证通过，后端重定向到一个第三方系统等我，这个时候，前端会报跨域问题，请问这个你们怎么解决的啊？

**Comment by 13856093240** [comment]
请问，前后端分离项目，后端发起重定向到统一登录页面，前端如何处理跨域问题？
