### ISSUE TITLE
V4 alpha prepare

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-pro#3789]
为了能够让 V4 尽快达到一个可用状态，使得 V4 能够活跃起来，重点把一些影响到可用性的点处理掉，这样使得可以推动 V4 尽快向前走：

- [x] V3 以及 master 的修改合并到 pro-blocks
- [x] branch update
  - [x] v4 合并到 master，删除 v4 分支
  - [x] master 改为 v2 分支
- [x] TypeScript 完整支持，当前有部分是 JS，部分是 TS 的，最好能够全部迁移到 TS，包括 pro-blocks
- [x] 相应更新 https://pro.ant.design/ 内的所有文档
  - [x] 创建方式的变化（umi create 和 ts/js 语言可选)
  - [x] v2 -> v4 的升级文档
  - [x] pro-layout 在 pro.ant.design 上的文档（代码备注）
- [x] 老版本 https://v2-pro.ant.design/ 
- [x] 新网站上要有回到 v1 v2 的链接 https://beta.pro.ant.design/
- [x] 升级依赖链到最新版本
- [x] create-umi 更新 https://github.com/umijs/create-umi/pull/62
- [x] 把 TypeScript/区块 加到 README
- [ ] 发布日志/软文
  - [ ] README 同步更新
- [x] 现有文档排查更新
- [ ] CI 要跑过

### 可选

- [ ] 文档如何配置 dark 主题 https://github.com/ant-design/ant-design-pro/pull/2946
  - [ ] 让设计师过一遍，现有 Dark 颜色略怪异
- [ ] 部分实现用 antd 的新组件重构 PageHeader、Descriptions 等等
- [ ] 如何移除国际化和权限系统的方案 https://github.com/ant-design/ant-design-pro/issues/3775
- [ ] Bigfish 脚手架更新

**Comment by xiaohuoni** [comment]
现在的v4就是一个完整的版本了，并不需要从v3合并过去吧？v3剩余的有用的，可以合并到pro-blocks

**Comment by yutingzhao1991** [comment]
@xiaohuoni 修改了。

**Comment by xiaohuoni** [comment]
# v3 to pro blocks record
https://github.com/ant-design/pro-blocks
* [ ] AccountCenter	 
* [ ] AccountSettings	 
* [ ] AdvancedForm	 
* [ ] AdvancedProfile	 
* [ ] Analysis	 
* [ ] BasicForm	 
* [ ] BasicList	 
* [ ] BasicProfile	 
* [ ] CardList	 
* [ ] Exception403	 
* [ ] Exception404	 
* [ ] Exception500	 
* [ ] Monitor	 
* [ ] ResultFail	 
* [ ] ResultSuccess	 
* [ ] SearchListApplications	 
* [ ] SearchListArticles	 
* [ ] SearchListProjects	 
* [ ] StepForm	 
* [ ] TableList	 
* [ ] UserLogin	 
* [ ] UserRegister	 
* [ ] UserRegisterResult	 
* [ ] Workplace

**Comment by jameslouiz** [comment]
Does https://v4.pro.ant.design/ exist? I am unable to access it

**Comment by AimLuo** [comment]
话说，怎么做了 。

> 现在的v4就是一个完整的版本了，并不需要从v3合并过去吧？v3剩余的有用的，可以合并到pro-blocks

v4可以用到项目了？最近想把项目迁移到pro上。

**Comment by xiaohuoni** [comment]
最好是不要，框架基本可用，不过没有页面。没有完整跑过，感觉很多坑

**Comment by AimLuo** [comment]
umi群有人说你们弃坑了。😭。。

**Comment by imhele** [comment]
> umi群有人说你们弃坑了。😭。。

哪儿有？
- v2 的补丁工作
  - https://github.com/ant-design/ant-design-pro/pull/3815
  - https://github.com/ant-design/ant-design-pro/issues/3870
- 官网文档完善
  - https://github.com/ant-design/ant-design-pro-site/pull/264
  - https://github.com/ant-design/ant-design-pro-site/pull/267
- v3 的 typescript 完善
  - https://github.com/ant-design/ant-design-pro/pull/3849
  - https://github.com/ant-design/ant-design-pro/pull/3876
- 将 v3 迁移到 [pro-blocks](https://github.com/ant-design/pro-blocks)
  - https://github.com/ant-design/pro-blocks/pull/11
- Pro CLI 的尝试
  - https://github.com/ant-design/ant-design-pro/issues/3775

**Comment by imhele** [comment]
> Does https://v4.pro.ant.design/ exist? I am unable to access it

@jameslouiz It will come soon, please wait a few days.

**Comment by qiqizjl** [comment]
V4 alpha预计多久发布？

**Comment by kaoding** [comment]
V4 alpha预计多久发布？

**Comment by vellengs** [comment]
热盼期待中...

**Comment by redclown** [comment]
期待

**Comment by lucoxlee** [comment]
期待

**Comment by tomgao365** [comment]
有没有时间节点？😀

**Comment by doterme** [comment]
V4有发布计划吗？现在的版本中很多东西都不是我需要的，清理依赖很麻烦，清理完又面临升级问题。希望早点用上V4

**Comment by tomgao365** [comment]
@xiaohuoni  ant-design-pro 和 [alita](https://github.com/alitajs/alita) 有什么区别或关系么？

**Comment by tomgao365** [comment]
😂 每天早中晚，都要多次看看开发进度，期待可用。

**Comment by xiaopanghhh** [comment]
> 😂 每天早中晚，都要多次看看开发进度，期待可用。

同样同样，今天测试现在 V4 版本可以正常运行了。

**Comment by kaoding** [comment]
希望快点把 V4 变成 master

**Comment by vellengs** [comment]
看上去工作量，应该还有不少。

**Comment by xiaopanghhh** [comment]
从各个项目的Commits上来看，ant-design-pro-layout  和 ant-design-pro 的 V4 完成了。blocks 也全部变成 V4 的了。接下来可能就是各种 CLI 了。还有就是一些测试了。估计离正式发布也用不了多久了。

**Comment by crashsol** [comment]
每天都看看，期望早点发版

**Comment by kaoding** [comment]
这个月能发v4吗？

**Comment by tomgao365** [comment]
> 这个月能发v4吗？

悬，官方一直没有正式地公布具体发布时间的消息。

**Comment by ileadall42** [comment]
据说2.3是最后一个版本，不知道是不是2的最后一个版本，我猜是的。
![image](https://user-images.githubusercontent.com/27263086/57298615-346f5f00-7105-11e9-8695-ef56aab6656e.png)

**Comment by afc163** [comment]
@chenshuai2144 这句话有歧义，要改的精确一点。

**Comment by tomgao365** [comment]
日常催更，上来看看。

**Comment by evanyangg** [comment]
发起赞助，会加快更新么

**Comment by afc163** [comment]
可以考虑在 antd 和 antd-pro 官网都弹个框。

**Comment by mgss** [comment]
v2 -> v4的迁移指南不要忘了哇~~~

**Comment by tomgao365** [comment]
> v2 -> v4的迁移指南不要忘了哇~~~

想多了，现在还不知道v4猴年马月才能发布呢😂

**Comment by asktalk** [comment]
什么时候发布V4？希望更新

**Comment by evanyangg** [comment]
@tomgao365 @asktalk  感觉V4版本可用了，是幻觉么

**Comment by afc163** [comment]
#3143 这里的 dark theme 有着落了么？

**Comment by tomgao365** [comment]
🤩，进展好快，看来这个月可以用了

**Comment by zhangyu1818** [comment]
加油啊大佬们，迫不及待了~

**Comment by afc163** [comment]
@zombieJ @chenshuai2144 还有 8 个勾。

**Comment by zombieJ** [comment]
今天合并版本了，master 不接收新的 PR。

**Comment by doterme** [comment]
如何移除国际化和权限系统的方案，强烈要求这个。

**Comment by yoyo837** [comment]
还有的勾在merge后的master上弄么？

**Comment by zombieJ** [comment]
嗯，v4 branch 已经清了。

**Comment by afc163** [comment]
ci 没过

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4311

**Comment by pkaq** [comment]
好吧 开始学ts吧

**Comment by crashsol** [comment]
学起来
