### ISSUE TITLE
关于model问题？

### ISSUE THREAD

**Issue by zhuanglong** [ant-design/ant-design-pro#379]
我想用initialState来恢复本地保存的登录信息
const app = dva({
  initialState: { login: { status: 'ok'  } },
});

那么就必须要先在入口处注册login model，这样会导致 common/nav.js 配置的动态加载的login model重复加载报错，然后我在nav.js删掉有['login']这样就不会报错了，但是如果对login model进行修改会触发热加载，导致以下错误：
Unexpected key "login" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "@@dva", "global", "user". Unexpected keys will be ignored.

**Comment by afc163** [comment]
感觉提到 dva 上会更合适？
