### ISSUE TITLE
如何设置在提交前进行debugger等的检测？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#3790]
记得以前的版本提交前都可以进行debugger的检测，现在的版本没有了，如何配置啊？

**Comment by xiaohuoni** [comment]
哪个版本？

**Comment by codepandy** [comment]
现在的版本

**Comment by xiaohuoni** [comment]
我问的是，哪个版本可以

**Comment by codepandy** [comment]
谁知道你隐藏的意思，没有用umi的时候可以

**Comment by chenshuai2144** [comment]
提交前进行debugger等 详细秒速一下。 ajax 提交之前的 filter 吗？

**Comment by codepandy** [comment]
@chenshuai2144 不是，就是github的hook，想在提交之前进行一些规则的检测，比如如果程序里面有debugger关键字就commit失败，或者自动删除所有的debugger，然后再提交。

**Comment by chenshuai2144** [comment]
husky
https://github.com/typicode/husky
