### ISSUE TITLE
Form表单的labelAlign不起作用，并且报错

### ISSUE THREAD

**Issue by jiejieHome** [ant-design/ant-design-pro#3793]
设置<Form>标签的labelAlign属性，报错iWarning: React does not recognize the `labelAlign` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelalign` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by jiejieHome** [comment]
设置的代码如下`<Form labelAlign='left' onSubmit={this.handleSubmit}>
                <FormItem wrapperCol={{span:24}}>
                  {getFieldDecorator('name', {
                    initialValue: formData.name,
                  })(
                    <Input.Search
                      placeholder="请输入设施名称..."
                      onSearch={nameChange}
                      enterButton
                    />
                  )}
                </FormItem>`

**Comment by chenshuai2144** [comment]
写一个最小可重现的 demo 把。 感觉这个 props 被透传了

**Comment by jiejieHome** [comment]
没明白什么意思？被透传是什么意思？

**Comment by chenshuai2144** [comment]
写一个最小可重现的 demo 把  
这个比较重要

**Comment by jiejieHome** [comment]
在当前环境下就是报错，但是我把工程下的config,src文件夹和package.json整个复制到新的环境下，就不会存在这个问题，其他的文件应该都是自动生成的了吧，按理说应该没影响啊，不知道有什么差别，所以这个最小demo我也写不出来

**Comment by jiejieHome** [comment]
我知道哪个文件引起的了，是package-lock.json，我的环境下的package-lock.json这个文件老一些，换个环境，重新安装依赖时，生成的package-lock.json这个文件新一些，就不报错了，总之，还是谢谢你
