### ISSUE TITLE
关于动态切换theme的疑问

### ISSUE THREAD

**Issue by 662** [ant-design/ant-design-pro#3796]
近期我在摸索生产环境实现antd组件库的动态theme切换，遇到一些问题，特来请教，还望指点一二

我搜索过已有issues，也看过pro的代码，发现pro的开发环境theme切换存在一些问题以及一些疑问

1. antd-theme-generator生成出来的less仅适用于className="myclass"这样的全局样式，无法和css modules（className={styles.myclass}）的工作逻辑达成一致，但是pro预览站似乎没这个问题，想请教一下是怎么做到的；

2. antd-theme-generator生成出来的less中的各种资源文件路径有问题，无法和webpack契合工作，生成真实的文件路径，例如：url('../assets/logo.png')，webpack打包时会根据各种配置产生一个类似 url('/static/logo.png')这样的生产环境路径，而antd-theme-generator创建的color.less却是原始的url('../assets/logo.png')这显然不符合预期；这个问题可能各位大厂玩家会告诉我用cdn，这里先谢过了，条件有限，用不上cdn；想请教一下有办法解决吗

3. antd-theme-generator生成出来的less包含了所有的antd组件less和本地less，体积非常的大，我仅仅需要生成和颜色有关的样式表就能满足需求了；想请教一下如何仅生成和color有关的less.

4. 综上，运行时修改less变量编译样式表存在诸多需要解决的问题，我想放弃这种方式，改用生成两套独立的antd组件样式表，这样的话有什么方法可以做到呢，而且任然会面临 3 的问题

真心求助，望各位大佬帮助

**Comment by chenshuai2144** [comment]
postcss 了解一下，可以通过操作语法树方式来进行，效果还是很棒的

**Comment by zhuzz11** [comment]
@662 你的问题2解决了么？
