### ISSUE TITLE
manifest.json这个请求在哪里？

### ISSUE THREAD

**Issue by jeremyChenMing** [ant-design/ant-design-pro#3797]
项目总会请求根目录下的manifest.json文件，请问这个可以关闭吗？怎么关闭？

**Comment by jeremyChenMing** [comment]
还有一个这个方法，没有找到在哪里调用的
export function render(oldRender) {
  
  fetch('/api/auth_routes')
    .then(res => res.json())
    .then(
      ret => {
        authRoutes = ret;
        oldRender();
      },
      () => {
        oldRender();
      }
    );
}

请求这个是为了什么，表示没有看懂，谁能解答一下。

**Comment by chenshuai2144** [comment]
manifest.json 是打开 pwa 之后，浏览器自己去请求的，是一个默认行为。

**Comment by LukerSpringtree** [comment]
> 还有一个这个方法，没有找到在哪里调用的
> 
> ```
> export function render(oldRender) {
>   
>   fetch('/api/auth_routes')
>     .then(res => res.json())
>     .then(
>       ret => {
>         authRoutes = ret;
>         oldRender();
>       },
>       () => {
>         oldRender();
>       }
>     );
> }
> ```
> 在app.js里面请求这个是为了什么，表示没有看懂，谁能解答一下。

[https://github.com/ant-design/ant-design-pro/issues/3797#issuecomment-474660367](url)

详读 umi 这端文档

@chenshuai2144 
强烈建议 在 antd-pro   src/app.js

头部加上说明和umi 的链接.
我觉得这样 项目的可读性更高

我遇到了同样的问题:
[https://github.com/ant-design/ant-design-pro/issues/3864#issue-426346092](url)

**Comment by LukerSpringtree** [comment]
> 项目总会请求根目录下的manifest.json文件，请问这个可以关闭吗？怎么关闭？

学习一下 PWA
就能理解这边的 src/mainfest.json 和 src/service-worker.js 以及 src/global.js 的作用了
