### ISSUE TITLE
node版本相同，服务器上无法build，本地可以build

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#3800]
![image](https://user-images.githubusercontent.com/20454290/54655850-57ff2b80-4afe-11e9-825c-46fd1aec04ff.png)

服务器上install后，再build（原来的服务器环境一样且可以build，换了新服务器就不行了，最新版本的node也是出现这个问题）

![image](https://user-images.githubusercontent.com/20454290/54655864-69e0ce80-4afe-11e9-838a-39b679e483f8.png)

![image](https://user-images.githubusercontent.com/20454290/54656182-a234dc80-4aff-11e9-91ff-9ef0521f5329.png)

请问能帮忙解答一下吗？

**Comment by GitHubJiKe** [comment]
遇到了相同的问题，core-js单独安装了也是说找不到依赖。暂时还没找到解决方案

**Comment by GitHubJiKe** [comment]
@419280377 哥们，我的问题解决了，升级antd 到3.15.1之后，然后用npm 替换cnpm,并且执行npm audit fix [npm audit fix](https://blog.csdn.net/weixin_40817115/article/details/81007774) 就奇妙的好了。

猜测可能是antd pro 对于低版本的antd存在兼容问题，还有就是淘宝镜像的cnpm 安装某些依赖的时候有问题。

**Comment by 419280377** [comment]
> @419280377 哥们，我的问题解决了，升级antd 到3.15.1之后，然后用npm 替换cnpm,并且执行npm audit fix [npm audit fix](https://blog.csdn.net/weixin_40817115/article/details/81007774) 就奇妙的好了。
> 
> 猜测可能是antd pro 对于低版本的antd存在兼容问题，还有就是淘宝镜像的cnpm 安装某些依赖的时候有问题。

我单独安装依赖@babel/polyfill就build成功了，感觉这个问题每个人的解决方案并不一样呀！

**Comment by yutingzhao1991** [comment]
umi 发了新版本兼容了这个问题 https://github.com/umijs/umi/pull/2136
