### ISSUE TITLE
新克隆下来的安装完依赖无法启动

### ISSUE THREAD

**Issue by zlq960222** [ant-design/ant-design-pro#3801]
部分报错如下

(node:6156) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Starting the development server...

Theme generated successfully
 ERROR  Failed to compile with 119 errors                                        14:46:33

These dependencies were not found:

* core-js/modules/es6.array.copy-within in ./src/pages/.umi/polyfills.js
* core-js/modules/es6.array.fill in ./src/pages/.umi/polyfills.js
* core-js/modules/es6.array.find in ./src/pages/.umi/polyfills.js
* core-js/modules/es6.array.find-index in ./src/pages/.umi/polyfills.js
* core-js/modules/es6.array.from in ./src/pages/.umi/polyfills.js
* core-js/modules/es6.array.iterator in ./src/pages/.umi/polyfills.js

**Comment by yutingzhao1991** [comment]
重新更新下 node_modules

**Comment by wangjian1119** [comment]
同样的问题， 别用cnpm安装，用npm 安装就没事了，你可以试试

**Comment by shuai1123** [comment]
我也遇到了同样的问题 npm install 也报错

**Comment by xpxs** [comment]
安装 core-js 版本为2.6.5，删除原来的node_modules，重新更新下node_modules

**Comment by fengchenzhihun1** [comment]
怎么解决

**Comment by xpxs** [comment]
> 怎么解决

cnpm i core-js@2.6.5 --save   然后重新更新下node_modules 记得把node_modules先删掉 我是这么处理的

**Comment by chenshuai2144** [comment]
rm -rf  node_modules

cnpm 可以使用 cnpm update

**Comment by fanguangjian** [comment]
可用

**Comment by jinyaqiao1102** [comment]
@chenshuai2144  这个东西真坑，我这用着用着起不来了

**Comment by chenshuai2144** [comment]
babel 更新了。一直更新一直爽

**Comment by Fengoo23** [comment]
> > 怎么解决
> 
> cnpm i core-js@2.6.5 --save 然后重新更新下node_modules 记得把node_modules先删掉 我是这么处理的

cnpm i core-js@2.6.8 --save  最低要求到2.6.8了

**Comment by jsdocker** [comment]
现在又有遇到，最终方案是什么呢

**Comment by LegendarySSS** [comment]
一样的问题

**Comment by jinyaqiao1102** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
