### ISSUE TITLE
条形图

### ISSUE THREAD

**Issue by msadu** [ant-design/ant-design-pro#3802]

**Comment by msadu** [comment]
能画条形图吗？找了半天发现好像不行，需要bizchats？

**Comment by travonf** [comment]
bizcharts上面很多可用图表
他这个也是封装的bizcharts
bizcharts封装的G2
都是组件化的

**Comment by chenshuai2144** [comment]
我们使用的都是 [bizcharts](https://bizcharts.net/index)
