### ISSUE TITLE
有完整的echats使用的教程吗？

### ISSUE THREAD

**Issue by msadu** [ant-design/ant-design-pro#3803]

**Comment by msadu** [comment]
有完整的ant-design-pro集成echats使用的教程吗？

**Comment by Quekie** [comment]
图表太便捷了 ， 就是文档不够基础 ， 看了下面几个链接应该差不多了 。
相关链接：
- https://pro.ant.design/docs/graph-cn
- https://pro.ant.design/components/Charts-cn/
- https://bizcharts.net/products/bizCharts/demo

**Comment by chenshuai2144** [comment]
我们不会官方使用echarts，试试 [g2](https://antv.alipay.com/zh-cn/g2/3.x/index.html) 吧。
