### ISSUE TITLE
在window环境下,npm run build正常, 在linux环境下, 项目无法build,进度到65%,build自动中断

### ISSUE THREAD

**Issue by gaohui1994** [ant-design/ant-design-pro#3804]
![build_error](https://user-images.githubusercontent.com/23376886/54729533-18e4df00-4bbf-11e9-8dd3-ba5c931d7bc5.jpg)

**Comment by gaohui1994** [comment]
![build_error](https://user-images.githubusercontent.com/23376886/54729507-f226a880-4bbe-11e9-89d1-980df139884c.jpg)

**Comment by chenshuai2144** [comment]
试着使用 powershell 呢，node 的生态对 win 不是很友好。
如果是 win10 推荐使用  linux bash
