### ISSUE TITLE
如何让某个页面不带menu的？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#3805]
现在需要一个页面像登录一样，不需要menu，该怎么设置呢？

**Comment by afc163** [comment]
放到其他 Layout 里，比如建一个 BlankLayout。

**Comment by afc163** [comment]
放到其他 Layout 里，比如 BlankLayout：https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BlankLayout.js

https://github.com/ant-design/ant-design-pro/blob/63e632eeda18ea2a81d2227c846f2ce37b76ce92/config/router.config.js#L5
