### ISSUE TITLE
使用umi脚手架创建的ant pro工程  如果出现带参数路由，router.push 的时候 URL改变但是不会触发UI渲染

### ISSUE THREAD

**Issue by luoandy** [ant-design/ant-design-pro#3806]
如题 ， 

ant pro 版本为2.1.1 

我在路由里面配置带参数路由，从上一个页面触发跳转到下一个路由(此路由为带参数路由),URL发生了改变但是不触发UI渲染

![image](https://user-images.githubusercontent.com/20121275/54730873-349fb380-4bc6-11e9-8df9-320c26f657bd.png)

![image](https://user-images.githubusercontent.com/20121275/54730878-39646780-4bc6-11e9-8d55-74d2a63aeba1.png)
  
BasicLayout.js

![image](https://user-images.githubusercontent.com/20121275/54730889-484b1a00-4bc6-11e9-8a57-a53d34ddb91c.png)

**Comment by afc163** [comment]
要 dispatch 上去。

**Comment by luoandy** [comment]
@afc163 router.push那里dispatch吗

**Comment by chenshuai2144** [comment]
`dispatch(router.push())`
因为路由交给 redux 管理了

**Comment by VeChar** [comment]
@chenshuai2144 4.0目前出现同样的问题使用

`dispatch(router.push())`

会报错

`
×
TypeError: Cannot read property 'type' of undefined

  10 | return function (next) {
  11 |   return function (action) {
  12 |     if (action.type !== CALL_HISTORY_METHOD) {
  13 |       return next(action);
  14 |     }
  15 | 
  16 |     var _action$payload = action.payload,
`

该如何解决呢？

**Comment by ToNewDay** [comment]
遇到了相同问题
