### ISSUE TITLE
ant design pro脚手架集成electron后的打包问题

### ISSUE THREAD

**Issue by reddingit** [ant-design/ant-design-pro#3807]
ant design pro脚手架集成electron后，打包生成桌面客户端后，使用的是file:///协议，许多文件加载不到，请问有没有解决方案？

**Comment by drduan** [comment]
我也想这个问题呢 、希望有解决方案

**Comment by tomgao365** [comment]
@reddingit @drduan #3346 试试呢

**Comment by chenshuai2144** [comment]
需要配置一下 webpack 的 [target](https://webpack.js.org/configuration/target/)

**Comment by reddingit** [comment]
> 需要配置一下 webpack 的 [target](https://webpack.js.org/configuration/target/)

在plugin.config.js里配吗？ 
新手求指导

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#chainwebpack

**Comment by heytheww** [comment]
mark
