### ISSUE TITLE
打包之后刷新页面，请求地址错误，请求的是ant design pro的路由

### ISSUE THREAD

**Issue by ccccccode** [ant-design/ant-design-pro#3809]
打包完再线上发布之后，刷新页面的时候，会直接报404。

在network中发现，刷新之后请求的地址是ant design pro中的路由地址，并不是api地址。

但是点击菜单栏请求的地址是api地址，请求是正确的

**Comment by ccccccode** [comment]
![(O11@MJ93D)2WC RE}OR7G](https://user-images.githubusercontent.com/41566488/54737523-71ca6c80-4beb-11e9-9d01-e991d8b70fd3.png)

这是不刷新页面，点击菜单的请求

**Comment by ccccccode** [comment]
![US Z$JKU7DEO5U%9~RQDUAM](https://user-images.githubusercontent.com/41566488/54737568-ab02dc80-4beb-11e9-92bf-24393b4b5cf0.png)

这是直接刷新页面的请求，会直接404

**Comment by ccccccode** [comment]
请问一下，这一块应该怎么修改？

**Comment by chenshuai2144** [comment]
look here https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88
