### ISSUE TITLE
菜单栏收起时，hover上去，一级菜单pop出来的无法点击跳转

### ISSUE THREAD

**Issue by mmmaomao21** [ant-design/ant-design-pro#3811]
![image](https://user-images.githubusercontent.com/23095457/54752365-c59f7a80-4c18-11e9-8009-1bb33d9d5ae2.png)
![image](https://user-images.githubusercontent.com/23095457/54752383-d3550000-4c18-11e9-82c6-744a45c1fcf9.png)

option1是一级菜单，pop出来的和有子级的菜单不同，在操作上很难移过去进行点击操作，且也不能点击，这里应该怎么设置能达到收起后，弹出的一级菜单也能点击跳转？

**Comment by chenshuai2144** [comment]
有子集的菜单不能点是一种规范。
你为什么需要能点呢？
