### ISSUE TITLE
关于Table使用过滤功能会影响到排序功能的疑惑

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#3820]
如图，当我使用过滤功能，触发排序时，不管怎么点击，打印出来的order永远是ascend，而当我注释掉过滤功能时，排序恢复正常。请问这是我代码问题吗？

![info](https://user-images.githubusercontent.com/40480550/54802300-abf84480-4ca5-11e9-8f12-e7c463b612d9.png)

**Comment by afc163** [comment]
给 column 加个 key 试试。

**Comment by linzelong95** [comment]
@afc163 
谢谢，加了key，问题就解决了。
