### ISSUE TITLE
npm run build 错误

### ISSUE THREAD

**Issue by BestVoice** [ant-design/ant-design-pro#3822]
+ npm run build

> ant-design-pro@1.1.0 build /var/jenkins_home/workspace/jaxim-web-management-platform-card-rule
> cross-env ESLINT=none roadhog build

Failed to compile.

Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/extends' in '/var/jenkins_home/workspace/jaxim-web-management-platform-card-rule/node_modules/history/esm'

**Comment by chenshuai2144** [comment]
国内推荐使用 cnpm

**Comment by BestVoice** [comment]
https://github.com/sorrycc/blog/issues/82  This will solve the problem

**Comment by CarolineJason** [comment]
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in '/root/app/node_modules/react-router-dom/esm '   发布的时候遇到这样的问题，是什么原因
