### ISSUE TITLE
ie 兼容性问题

### ISSUE THREAD

**Issue by lkkk123** [ant-design/ant-design-pro#3823]
小哥哥，你好： 
目前我通过配置  
 targets: {
    ie: 11,
  },
可以支持到 ie11, 但是继续往下兼容就不行了呢，请问能兼容ie10和ie9吗？

**Comment by chenshuai2144** [comment]
不兼容，你可以需要严格一些功能

**Comment by lkkk123** [comment]
小哥哥 严格一些功能？是什么意思呢， 我没太懂

**Comment by afc163** [comment]
<img width="699" alt="图片" src="https://user-images.githubusercontent.com/507615/54877511-b445b080-4e5a-11e9-9807-d423fe00145c.png">
