### ISSUE TITLE
TreeSelect和Tree使用同一份数据时候报错

### ISSUE THREAD

**Issue by wangxulong** [ant-design/ant-design-pro#3825]
1.加载树形列表，正常显示
![image](https://user-images.githubusercontent.com/8357515/54820614-cd275800-4cda-11e9-9cfb-fcd8594ab488.png)
2.添加弹出框上，使用TreeSelect，报错，可以正常显示，但是无法选中标签
![image](https://user-images.githubusercontent.com/8357515/54820693-fd6ef680-4cda-11e9-9d28-cad2353354eb.png)
3.传输数据格式如下：
![image](https://user-images.githubusercontent.com/8357515/54820841-6eaea980-4cdb-11e9-8d45-976cd23a066e.png)

**Comment by 904492381** [comment]
怎么解决的啊  我也是这样

**Comment by wangxulong** [comment]
=

> 怎么解决的啊 我也是这样

数据问题，把model提了出来

**Comment by 904492381** [comment]
数据啥问题  能具体一点吗 谢谢

**Comment by 904492381** [comment]
怎么使用同一个数据呀 具体咋解决的呀

**Comment by 904492381** [comment]
> =
> 
> > 怎么解决的啊我也是这样
> 
> 数据问题，把模型提了出来

老哥详细点呀 谢谢  我是在Table里也用了这个数据没事  treeselect就不行了  深拷贝也试了 什么原因呀到底 晕死了

**Comment by wangxulong** [comment]
> > =
> > > 怎么解决的啊我也是这样
> > 
> > 
> > 数据问题，把模型提了出来
> 
> 老哥详细点呀 谢谢 我是在Table里也用了这个数据没事 treeselect就不行了 深拷贝也试了 什么原因呀到底 晕死了



我的情况和你的一样不？ 我是把数据弄错了，没有返回唯一的key赋值给组件。  多个Page页上的组件公用一个tree的数据，把数据文件model.js提取models（和page文件夹同级别）文件夹中，这样的多个组件共享。（我的是一个Page页一个文件夹）

**Comment by 904492381** [comment]
> > > =
> > > > 怎么解决的啊我也是这样
> > > 
> > > 
> > > 数据问题，把模型提了出来
> > 
> > 
> > 老哥详细点呀 谢谢 我是在Table里也用了这个数据没事 treeselect就不行了 深拷贝也试了 什么原因呀到底 晕死了
> 
> 我的情况和你的一样不？ 我是把数据弄错了，没有返回唯一的key赋值给组件。 多个Page页上的组件公用一个tree的数据，把数据文件model.js提取models（和page文件夹同级别）文件夹中，这样的多个组件共享。（我的是一个Page页一个文件夹）

我treeselect里面每条key都不一样  但是和table里的key是一样的  而且我也试着把treeselect和table的key该不同 还是同样报错       你最后一句话什么意思   数组放model.js里的state里 table和treeselect都取这个的意思吗？
