### ISSUE TITLE
如何添加垫片 (我需要兼容到IE9）

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#383]
```
"extraBabelPlugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties",
    "es5-shim",
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],
```
垫片是在这里添加吗？

**Comment by chenshuai2144** [comment]
**对于 IE 系列浏览器，需要提供 es5-shim 和 es6-shim 等 Polyfills 的支持。
如果你使用了 babel，强烈推荐使用 babel-polyfill 和 babel-plugin-transform-runtime来替代以上两
个 shim。**

[兼容性](https://ant.design/docs/react/getting-started-cn#兼容性)
take a look

**Comment by afc163** [comment]
可以。。。你需要自行探索。

**Comment by samwangdd** [comment]
最后实现兼容性了吗？

**Comment by samwangdd** [comment]
请问最后实现兼容行了吗？@wunayou
