### ISSUE TITLE
讨论:关于图形编辑器

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3832]
https://preview.pro.ant.design/editor/flow
![image](https://user-images.githubusercontent.com/11746742/54863924-c73c8000-4d89-11e9-96da-7d5a9070e8ba.png)

刚开始，我觉得这很棒。
但是看了一天之后，我总觉得很奇怪，pro的示例都是用于中后台管理平台的。
这个图形编辑器，在这的定位很模糊？
总感觉和pro很难联系上，不知道你们怎么看？

**Comment by xiaohuoni** [comment]
@gaoli

**Comment by MRStruggle** [comment]
麻烦问下  你的流程图组建是 什么？可以交流下吗

**Comment by xiaohuoni** [comment]
@MRStruggle 我们的业务里面没有用到流程图，我就是觉得可能我没不常见这个需求，所以只有我这么觉得，所以才发了这个讨论。

**Comment by gaoli** [comment]
@xiaohuoni 后台应用中还有是很多业务会用到图形编辑器的，例如：网络管理，流程编排，路由系统 ...

正是因为集团内外都有大量的业务使用且很多都是基于 Antd pro，所以才会做此次的集成。

去年 @chenshuai2144 就有 [计划](https://github.com/ant-design/ant-design-pro/pull/2957) 集成，只是苦于没有时间 :)

**Comment by gaoli** [comment]
> 麻烦问下 你的流程图组建是 什么？可以交流下吗

@MRStruggle 现在 pro 里面集成的是 [GGEditor](https://github.com/gaoli/GGEditor) :)

**Comment by wangxingkang** [comment]
会存在此类需求，但比例会较低吧

**Comment by chenshuai2144** [comment]
在政务领域用的比较多一些。

**Comment by MRStruggle** [comment]
> @MRStruggle 我们的业务里面没有用到流程图，我就是觉得可能我不常见这个需求，所以只有我这么觉得，所以才发了这个讨论。

嗯，我用到了，但是没有接，纠结接入哪一个，目前后台写死了

**Comment by weiweiyx** [comment]
这个流程图案例怎么没有保存按钮  需要保存流程图呢@gaoli

**Comment by gaoli** [comment]
@weiweiyx 参照这个 [DEMO](https://codesandbox.io/s/r4kzkn441m) :)

**Comment by weiweiyx** [comment]
@gaoli 
![image](https://user-images.githubusercontent.com/22810806/58948231-3a1b9b80-87bc-11e9-8eeb-5a2cab0ca481.png)左边的节点不能直接通过label改变圆圈里面的文案嘛

**Comment by gaoli** [comment]
> @gaoli
> ![image](https://user-images.githubusercontent.com/22810806/58948231-3a1b9b80-87bc-11e9-8eeb-5a2cab0ca481.png)左边的节点不能直接通过label改变圆圈里面的文案嘛

这是图片哟，如果要自定义的话，可以直接编辑 svg 文件

**Comment by junshengBUPT** [comment]
GG editor能在antd vue中使用吗？

**Comment by chenshuai2144** [comment]
GG edito 不依赖react

**Comment by xiaohuoni** [comment]
真香

**Comment by Lawrence51** [comment]
请问这个是编辑视图中的流程图吗？在哪里有文档或者demo可以看，这个组件去哪里找？麻烦了

**Comment by h0730303779** [comment]
其实 楼主想说 功能太少了是么 我也觉得    还有拓扑编辑器..怎么自定义上图?

**Comment by mxy2316868975javascript** [comment]
如何支持动态锚点、以及如何获取锚点与锚点之间的依赖关系，可否支持一下

**Comment by gaoli** [comment]
> 如何支持动态锚点、以及如何获取锚点与锚点之间的依赖关系，可否支持一下

@mxy2316868975javascript 3.1.0 版本支持锚点的关系配置，可能参照这个 [Demo](https://github.com/alibaba/GGEditor/blob/master/examples/component-item-panel/index.tsx#L150) :)
