### ISSUE TITLE
启动项目 有如下警告是怎么会是

### ISSUE THREAD

**Issue by MRStruggle** [ant-design/ant-design-pro#3833]
[umi-plugin-dll] File list is equal, don't generate the dll file.
(node:762) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by chenshuai2144** [comment]
一个是使用了过时的api，是那个进度条插件，
另外一个是提醒你，以来文件相同，没有重新生成dll

都是可以忽略的

**Comment by MRStruggle** [comment]
> 一个是使用了过时的api，是那个进度条插件，
> 另外一个是提醒你，以来文件相同，没有重新生成dll
> 
> 都是可以忽略的

感谢 感谢 ，我看下进度条的api
