### ISSUE TITLE
开启PWA之后,想把应用图标保存到桌面该怎么实现?

### ISSUE THREAD

**Issue by LukerSpringtree** [ant-design/ant-design-pro#3834]
我想使用到PWA的一个用途, 就是把应用保存到桌面上,该怎么实现?
就算 antd-pro 官网demo: `https://preview.pro.ant.design/user/login`

点击: chrome 里面的 application => Manifest 中的 Add to homescreen按钮也会报错如下:
Site cannot be installed: no matching service worker detected. You may need to reload the page, or check that the service worker for the current page also controls the start URL from the manifest.

我改怎么配置 和使用, 才能实现 把图标保存到桌面? 谢了
@chenshuai2144

**Comment by xiaohuoni** [comment]
官网demo，在手机上用safari保存成功了。

**Comment by LukerSpringtree** [comment]
> 官网demo，在手机上用safari保存成功了。

我是mac,是不是说mac 不行 啊 还是怎么说?

**Comment by chenshuai2144** [comment]
需要 https 的，是必备条件，如果有https菜单中就会出现保存在桌面的按钮

**Comment by LukerSpringtree** [comment]
> 需要 https 的，是必备条件，如果有https菜单中就会出现保存在桌面的按钮

这个我是知道的
官网是https 吧
还是不行 https://preview.pro.ant.design/user/login
是不是我浏览器的问题?

**Comment by chenshuai2144** [comment]
我这里是 ok 的，你的手机是不是阉割掉了这个功能，试试最新的 chrome
