### ISSUE TITLE
存在多个 redirect= 的时候 每次登录之后 只跳转了一次 还在登录页面上

### ISSUE THREAD

**Issue by kalsolio** [ant-design/ant-design-pro#3835]
登录状态丢失之后 redirect的值里面可能还会存在redirect

比如 
https://test-manage.staging.test.com/user/login?redirect=https%3a%2f%2ftest-manage.staging.test.com%2ftest%2fuserlist%3fredirect%3dhttps%3a%2f%2ftest-manage.staging.test.com%2fuser%2flogin%3fredirect%3dhttps%3a%2f%2ftest-manage.staging.test.com%2ftest%2fuserlist

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/pull/3830
这次提交之后，就没有这个问题了，你可以重试一下
