### ISSUE TITLE
新手求问：document.ejs引入的https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js是干什么的

### ISSUE THREAD

**Issue by ghdestiny** [ant-design/ant-design-pro#3837]
请问这个js是做什么用的，我看了最新的document.ejs里面没有引入这个js，可以告诉我怎么去掉吗？
  <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js"></script>

**Comment by chenshuai2144** [comment]
是为了使用g2，如果你没有使用图表可以删掉。具体可以看这个 pr
https://github.com/ant-design/ant-design-pro/pull/3650
