### ISSUE TITLE
怎么实现菜单的动态id路由

### ISSUE THREAD

**Issue by luhexcp** [ant-design/ant-design-pro#3839]
我需要上级页面通过 id 定位到子级页面中菜单的某项，类似的路由url 为： http://localhost:8000/24/xxx/25/keys 。所以在 router 配置为
```
  {
        path: ':x_id/',
        component: '../layouts/BasicLayout',
        routes: [
          {
            path: 'xxx/:id/',
            name: 'XXX',
            icon: 'warning',
            component: './XXX/List',
            routes: [
             {
               path: 'keys',
               name: 'keys',
            },
            ],
          }
     ]
}
```
上级页面能正常跳转到子级页面，但每次在子级页面的菜单点击都会是 http://localhost:8000/:x_id/xxx/:id/keys ，怎么才能实现子级菜单页面跳转为 http://localhost:8000/24/xxx/25/keys

**Comment by chenshuai2144** [comment]
你不能再静态路由配置中注入动态参数的。

**Comment by luhexcp** [comment]
> 你不能再静态路由配置中注入动态参数的。
> 你可以通过 history.back() 退回去
history.back() 退回去 是能够退回，但是希望是菜单项都能带上级 id 的信息，因为是归属上级页面下的功能

我们呢现在是这样做的，获取到 url 然后解析 x_id = 24，id = 25 ，再获取静态配置中的 menu data 进行动态注入修改，感觉实现方式不太优雅。我觉得菜单动态路由是一个比较常见的场景，理论上有更合适的实现方式。

**Comment by chenshuai2144** [comment]
动态菜单不应该在菜单里的，菜单里的应该固化的。
除非你的菜单是随时生成的

**Comment by luhexcp** [comment]
> 动态菜单不应该在菜单里的，菜单里的应该固化的。
> 除非你的菜单是随时生成的

**Comment by luhexcp** [comment]
菜单的功能项是固定的，只是菜单里面的路由是由上级页面传过来生成的。就比如一个列表点击详情页，跳转到一个带有菜单的管理后台，每个详情页对应的管理后台的功能是一样的，但是菜单中的路由 id 是不一样的，我感觉框架可以设计成根据上层 url 的 id 将下层路由菜单 id 自动渲染

**Comment by chenshuai2144** [comment]
我不是很认同这种方式，详情页应该通过 list 页或者某个按钮点击进入。
