### ISSUE TITLE
如何获取 build 后的资源依赖表

### ISSUE THREAD

**Issue by shengxinjing** [ant-design/ant-design-pro#384]
rt，能和获取到 build 后，异步的 router 对应的 js 文件名吗？以及主js 和 css 的文件名？

**Comment by chenshuai2144** [comment]
这是webpack的活.
具体看这里:
[介绍 roadhog](https://github.com/sorrycc/blog/issues/15)
[roadhog#配置 ](https://github.com/sorrycc/roadhog#%E9%85%8D%E7%BD%AE)

**Comment by shengxinjing** [comment]
@chenshuai2144 之前研究了一下roadhog，没看到可以添加自定义pulgin 的方法 囧 只能加 babel 的 pulgin

**Comment by shengxinjing** [comment]
@chenshuai2144 看到了。可以自定义webpack.config.js  3Q

**Comment by chenshuai2144** [comment]
@shengxinjing 
![image](https://user-images.githubusercontent.com/8186664/33711935-ba46c86e-db80-11e7-8dde-f2833d74def4.png)

很简单的.
