### ISSUE TITLE
讨论：有没有方案可以替代puppeteer

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#3840]
puppeteer安装太慢了，有科学上网安装也停慢的，没有科学上网，使用cnpm也经常安装不下来。
![image](https://user-images.githubusercontent.com/11746742/54908471-efabb200-4f22-11e9-900b-dcceb48b6362.png)

**Comment by chenshuai2144** [comment]
没有的，你可以全局安装一个的，然后就不用每次这么痛苦了

**Comment by xiaohuoni** [comment]
我用yarn安装过一次之后，还好。
是有好几个网友，问我为什么clone了pro的代码，npm i && npm start 跑不起来，
搞半天最后是这个模块没装好
