### ISSUE TITLE
内网环境下使用bizcharts组件问题

### ISSUE THREAD

**Issue by ypwy** [ant-design/ant-design-pro#3843]
内网环境下是进行图表组件或者bizcharts组件的调用，页面加载一直空白。采用官方示例也不行
ant-design pro version: 2.1.1
bizcharts version: 3.5.1
antd version: 3.15.1
![111](https://user-images.githubusercontent.com/18670718/54965258-c5053c00-4faa-11e9-8c70-6f95a50d109d.PNG)

import React from "react";
import {
  G2,
  Chart,
  Geom,
  Axis,
  Tooltip,
  Coord,
  Label,
  Legend,
  View,
  Guide,
  Shape,
  Facet,
  Util
} from "bizcharts";
import DataSet from "@antv/data-set";

class ChartsTest extends React.Component {
  render() {
    const { DataView } = DataSet;
    const data = [
      {
        item: "事例一",
        count: 40
      },
      {
        item: "事例二",
        count: 21
      },
      {
        item: "事例三",
        count: 17
      },
      {
        item: "事例四",
        count: 13
      },
      {
        item: "事例五",
        count: 9
      }
    ];
    const dv = new DataView();
    dv.source(data).transform({
      type: "percent",
      field: "count",
      dimension: "item",
      as: "percent"
    });
    const cols = {
      percent: {
        formatter: val => {
          val = val * 100 + "%";
          return val;
        }
      }
    };
    return (
      <div>
        <Chart
          height={window.innerHeight}
          data={dv}
          scale={cols}
          padding={[80, 100, 80, 80]}
          forceFit
        >
          <Coord type="theta" radius={0.75} />
          <Axis name="percent" />
          <Legend
            position="right"
            offsetY={-window.innerHeight / 2 + 120}
            offsetX={-100}
          />
          <Tooltip
            showTitle={false}
            itemTpl="<li><span style=&quot;background-color:{color};&quot; class=&quot;g2-tooltip-marker&quot;></span>{name}: {value}</li>"
          />
          <Geom
            type="intervalStack"
            position="percent"
            color="item"
            tooltip={[
              "item*percent",
              (item, percent) => {
                percent = percent * 100 + "%";
                return {
                  name: item,
                  value: percent
                };
              }
            ]}
            style={{
              lineWidth: 1,
              stroke: "#fff"
            }}
          >
            <Label
              content="percent"
              formatter={(val, item) => {
                return item.point.item + ": " + val;
              }}
            />
          </Geom>
        </Chart>
      </div>
    );
  }
}

export default ChartsTest;
![222](https://user-images.githubusercontent.com/18670718/54965264-cafb1d00-4faa-11e9-8d25-c5bedd43e268.PNG)

**Comment by chenshuai2144** [comment]
bizchart 和网络没有关系的。
钉钉联系？  期贤

**Comment by afc163** [comment]
百度的同学？

**Comment by ypwy** [comment]
@afc163 我的操作有问题？

**Comment by chenshuai2144** [comment]
竟然不是阿里的同学，我们用了alicdn ，你看看是不是网络被拦截了，
如果被拦截了，关掉 externals

**Comment by ZY2071** [comment]
这真是个大坑
