### ISSUE TITLE
proxy.config.js的配置问题

### ISSUE THREAD

**Issue by suguer** [ant-design/ant-design-pro#3847]
请问一下,在config/proxy.config.js的代理服务,是只能在npm start生效的吗?我在npm run build编译部署后好像就没有效果了

**Comment by xiaohuoni** [comment]
proxy build之后都没有效果。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88
