### ISSUE TITLE
bug,时间组件使用在搜索条件时出现的bug,如图!!

### ISSUE THREAD

**Issue by liyangchiyue** [ant-design/ant-design-pro#385]
hello，厉害的开发者，我在运用的时候遇到一个麻烦。在表单提取字段时，把时间组件里边存储的东西都提取出来了。

![1](https://user-images.githubusercontent.com/8132004/33713441-2e6013b8-db86-11e7-910d-a771c4f21aab.png)
@luolonghao

**Comment by nikogu** [comment]
@liyangchiyue 你这个是自己拼上去的吧。。。看起来像是你传了个 `object`

**Comment by afc163** [comment]
没有足够的信息，看上去不像是我们的问题，提供了我们会 reopen。

**Comment by liyangchiyue** [comment]
@nikogu @afc163 help，点击查询，会触form表单的onSubmit事件，然后触发这个函数。这是官方的demo,也是比较常见的写法,help...
`  handleSearch = (e) => {
    e.preventDefault();

    const { dispatch, form } = this.props;

    form.validateFields((err, fieldsValue) => {
      if (err) return;
      console.log(fieldsValue);

      const values = {
        ...fieldsValue,
        updatedAt: fieldsValue.updatedAt && fieldsValue.updatedAt.valueOf(),
      };

      this.setState({
        formValues: values,
      });

      dispatch({
        type: 'user_admin_model/fetch',
        payload: values,
      });
    });
  }`

**Comment by chenshuai2144** [comment]
```
onChange | 时间发生变化的回调 | function(date: moment, dateString: string) | 无
```
是因为这个原因...
很多时候大家需要的是dateString 而不是 moment..

**Comment by chenshuai2144** [comment]
@liyangchiyue 
你可以暂时先这么封装一下.就能解决你的问题了.
```
class MyDatePicker extends PureComponent {
  render() {
    return (<DatePicker
      {...this.props}
      value={moment(this.props.value)}
      onChange={(data, dateString) => {
      this.props.onChange(dateString);
    }}
    />);
  }
}
```

```
<Col md={8} sm={24}>
    <FormItem label="更新日期">
       {getFieldDecorator('date')(
        <MyDatePicker  style={{ width: '100%' }} placeholder="请输入更新日期" />
      )}
     </FormItem>
</Col>
```

**Comment by liyangchiyue** [comment]
Thinks @chenshuai2144  @nikogu  @afc163

**Comment by chenshuai2144** [comment]
@liyangchiyue  注意一下markdown 的格式  
\` 是单行
\`\`\`  是多行

**Comment by afc163** [comment]
没必要这么做，提交到后台前把 moment 对象处理成字符串即可。

**Comment by liyangchiyue** [comment]
@chenshuai2144  好的，谢谢。

**Comment by chenshuai2144** [comment]
@afc163  master 分支的查询列表 现在就是直接发送了moment.
```
 fieldsValue.date = fieldsValue.date.format('YYYY-MM-DD');
 const values = {
     ...fieldsValue,
     updatedAt: fieldsValue.updatedAt && fieldsValue.updatedAt.valueOf(),
};
```

这样太丑了!

**Comment by liyangchiyue** [comment]
由于自身业务比较简单。提供一种手动解决方案
``` handleSearch = (e) => {
    e.preventDefault();

    const { dispatch, form } = this.props;

    form.validateFields((err, fieldsValue) => {
      if (err) return;

      const values = {
        ...fieldsValue,
        updatedAt: fieldsValue.updatedAt && fieldsValue.updatedAt.valueOf(),
        createtime:[fieldsValue.createtime&&fieldsValue.createtime[0].format('YYYY-MM-DD'),fieldsValue.createtime&&fieldsValue.createtime[1].format('YYYY-MM-DD')]
      };

      this.setState({
        formValues: values,
      });

      dispatch({
        type: 'user_admin_model/fetch',
        payload: values,
      });
    });
  }```

**Comment by liyangchiyue** [comment]
由于自身业务比较简单，提供一种手动解决方案:
`  handleSearch = (e) => {
    e.preventDefault();

    const { dispatch, form } = this.props;

    form.validateFields((err, fieldsValue) => {
      if (err) return;

      const values = {
        ...fieldsValue,
        updatedAt: fieldsValue.updatedAt && fieldsValue.updatedAt.valueOf(),
        createtime:[fieldsValue.createtime&&fieldsValue.createtime[0].format('YYYY-MM-DD'),fieldsValue.createtime&&fieldsValue.createtime[1].format('YYYY-MM-DD')]
      };

      this.setState({
        formValues: values,
      });

      dispatch({
        type: 'user_admin_model/fetch',
        payload: values,
      });
    });
  }`

**Comment by liyangchiyue** [comment]
由于自身业务比较简单，提供一种手动解决方案
```
  handleSearch = (e) => {
    e.preventDefault();

    const { dispatch, form } = this.props;

    form.validateFields((err, fieldsValue) => {
      if (err) return;

      const values = {
        ...fieldsValue,
        updatedAt: fieldsValue.updatedAt && fieldsValue.updatedAt.valueOf(),
        createtime:[fieldsValue.createtime&&fieldsValue.createtime[0].format('YYYY-MM-DD'),fieldsValue.createtime&&fieldsValue.createtime[1].format('YYYY-MM-DD')]
      };

      this.setState({
        formValues: values,
      });

      dispatch({
        type: 'user_admin_model/fetch',
        payload: values,
      });
    });
  }
```

**Comment by chenshuai2144** [comment]
不够优雅!😄

**Comment by liyangchiyue** [comment]
的确,哈哈:smile:
