### ISSUE TITLE
ubuntu 18.04 Npm install报错

### ISSUE THREAD

**Issue by hznuksco** [ant-design/ant-design-pro#3850]
![2019-03-26 21-30-16屏幕截图](https://user-images.githubusercontent.com/27288263/55000876-696c9a00-500e-11e9-9123-8b26df73805a.png)

**Comment by navono** [comment]
源换成 `cnpm` 试试

**Comment by chenshuai2144** [comment]
尽量不要使用中文路径，并且使用国内源
cnpm 欢迎你
