### ISSUE TITLE
想问一下ant design pro的文件书写规范方面的问题

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#3853]
[https://github.com/ant-design/ant-design-pro/blob/master/src/pages/List/TableList.js](url)
1. tableList中将列表/CreateForm/UpdateForm放在同一个文件里，这样书写起来不会感觉整个文件代码有点多吗？

https://github.com/ant-design/ant-design-pro/tree/master/src/pages/List
2. src/pages/List下面的文件为什么没有多一级的文件夹来梳理？

上面两个问题，希望大佬讲解一下，不胜感激。

**Comment by chenshuai2144** [comment]
其实我们没有什么书写逻辑。
pro 项目开发时间很长，主力人员也换了好几批。都是按照各自的习惯来的。
