### ISSUE TITLE
Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by ZylFrank** [ant-design/ant-design-pro#3854]
![image](https://user-images.githubusercontent.com/30528319/55060259-04678180-50ac-11e9-8eb7-bf3c52ba1a51.png)

![image](https://user-images.githubusercontent.com/30528319/55060743-1c8bd080-50ad-11e9-813c-f72c30720400.png)

### 问题描述
页面中查询部分为子组件 使用 export default Form.create()(Filter); 创建Form，Modal中使用@Form.create()。
当我给密码输入框添加 
```<Input type="password" />```时就会出现上图的警告，如果写成```<Input />```就正常了。

个人感觉不是Input的问题 但是也没找到其他问题。

**Comment by chenshuai2144** [comment]
不要同时使用两个@Form.create() props传递会出问题
