### ISSUE TITLE
dispatch effect catch 不到错误

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/ant-design-pro#3856]
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/app.js#L3-L9

为什么onError 需要加上 err.preventDefault(); 
如果这样的话
dispatch 的catch 就捕获不到了，这里删出 err.preventDefault(); 有影响么

**Comment by xiaohuoni** [comment]
应该没什么影响，这里是模拟了，捕获错误的流程

**Comment by chenshuai2144** [comment]
catch 了的就是需要你自己处理的。
因为 dva  dispatch 报错之后，整个进程都会挂掉 ，除非刷新界面不然下次dispatch也没有用

**Comment by hnsylitao** [comment]
但是这样的话，对应的在component 里面想针对 不同地方调用dispatch 做不同的catch

**Comment by chenshuai2144** [comment]
难以两全，js 是个单线程执行的。最好的办法是各自 catch

**Comment by hnsylitao** [comment]
现在是全局的onError 影响到了局部的catch 我注释掉了全局的catch 会不会有什么影响
