### ISSUE TITLE
nginx发布后502 bad gateway

### ISSUE THREAD

**Issue by jiazil** [ant-design/ant-design-pro#3859]
server {
    listen 80;
    # gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    server_name _;
    root /usr/share/nginx/html;

    location / {
        # try_files $uri /index.html;
        try_files $uri $uri/ /index.html;

    }

    location /rpc {
        proxy_pass http://backenIP;

        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}

![image](https://user-images.githubusercontent.com/15866105/55121373-353fc900-5135-11e9-853e-0ddd4ad0d2fd.png)

**Comment by jiazil** [comment]
折腾了好多天，求救！！！

**Comment by tsj11** [comment]
请问是访问哪个路由会出现502？你这个location写的顺序是不是不太对哦

**Comment by zwl2222** [comment]
@jiazil 兄弟解决了吗？
