### ISSUE TITLE
.ant-form-item 样式出现`display: inline-block`，导致样式错乱

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#3860]
在官方的[查询表格](https://preview.pro.ant.design/list/table-list)演示中，下面的这段CSS不起作用，搜索表格样式正常显示：

```
.ant-form-inline .ant-form-item {
    display: inline-block;
    margin-right: 16px;
    margin-bottom: 0;
}
```
如下所示：

![Snipaste_2019-03-28_09-27-53](https://user-images.githubusercontent.com/23411433/55123091-3b857380-513c-11e9-9715-56403af52ce6.png)

在项目中，发现上面的样式又起作用了，https://github.com/ant-design/ant-design-pro/blob/master/src/pages/List/TableList.less#L15 这段代码反而失效了，而且是全局失效，如下所示：

![Snipaste_2019-03-28_09-28-54](https://user-images.githubusercontent.com/23411433/55123136-67a0f480-513c-11e9-81c4-79930e4a75eb.png)

请问有什么操作是影响这个的，目前在项目代码中尙没有找到原因。

**Comment by jjwong1991** [comment]
没有复现问题。
同级样式后者覆盖前者，应该是在你的本地环境样式文件加载顺序不一致导致的
删除node_modules重新npm install一下试试呢

**Comment by mstao** [comment]
刚才找到了问题原因， https://github.com/ant-design/ant-design-pro/blob/master/src/pages/List/TableList.js#L513  这个form 有个 layout=“inline”样式，有时会出现重写的.ant-form-item样式失效，把这个去掉就好了

**Comment by chenshuai2144** [comment]
看起来是css加载顺序的问题,增加一下这段css的权重就好了
```
.ant-form-inline .ant-form-item {
    display: inline-block;
    margin-right: 16px;
    margin-bottom: 0;
}
```
