### ISSUE TITLE
v1 版本更新了一下antd的包，报错‘Cannot read property 'compilation' of undefined’

### ISSUE THREAD

**Issue by songhua-river** [ant-design/ant-design-pro#3863]
package.json 中，antd 版本是3.6.4的版本 在哪里可以下到

**Comment by chenshuai2144** [comment]
定位的错误是为什么？ antd最近没有不兼容改动

**Comment by TP026787** [comment]
我也遇到了同样的问题，很奇怪我其他的项目构建就没有这个问题，同样的依赖包

**Comment by chenshuai2144** [comment]
删除 yarn.lock  package.lock 什么的再重新试试如何？

**Comment by songhua-river** [comment]
> 删除 yarn.lock package.lock 什么的再重新试试如何？
这个是很久之前一点几的版本，单独更新antd就会包编译错误，不知道是不是更新了相关依赖。下一个干净的历史版本，初始化之后业务代码覆盖进去就能用。
