### ISSUE TITLE
为什么我感觉AntdPro 的权限系统很不友好?

### ISSUE THREAD

**Issue by LukerSpringtree** [ant-design/ant-design-pro#3864]
/api/auth_routes
这个 mock 数据的  接口在哪里被调用的 我看了半天也没找到.
还是我太蠢了?

app 文件下面有一个 render 方法. 但是这个方法在哪边被调用的呢?
```

export function render(oldRender) {
  fetch('/api/auth_routes')
    .then(res => res.json())
    .then(
      ret => {
        authRoutes = ret;
        oldRender();
      },
      () => {
        oldRender();
      }
    );
}
```

**Comment by ergoulee** [comment]
[umi运行时配置](https://umijs.org/zh/guide/runtime-config.html#render)

**Comment by LukerSpringtree** [comment]
> [umi运行时配置](https://umijs.org/zh/guide/runtime-config.html#render)

tks

后来其实我也猜到了.

**Comment by LukerSpringtree** [comment]
个人建议把 
umi运行时配置
这个链接 写在 app.js  的文件的顶部, 增加代码可读性啊

@ergoulee

**Comment by lovelock** [comment]
给你加把劲, 我刚踩了这个坑, 花了一晚上的时间才搞明白, 这个问题坑了不少人
