### ISSUE TITLE
index.js:1 TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#3867]
![image](https://user-images.githubusercontent.com/7875572/55201395-c4181880-51fd-11e9-8b99-74936d889f5f.png)
#

**Comment by drduan** [comment]
![image](https://user-images.githubusercontent.com/7875572/55201511-50c2d680-51fe-11e9-8004-564db3037a8d.png)

**Comment by chenshuai2144** [comment]
这个一般都是包没有安全号造成的，
使用 cnpm 并且升级你的 node 版本，一般都能解决

**Comment by zhaolixiang** [comment]
![image](https://user-images.githubusercontent.com/16216595/55397328-8e19c200-5578-11e9-9ae9-990ace057b3b.png)

**Comment by facku** [comment]
I have the same problem, any fix for that?

**Comment by hardwork91** [comment]
Also have the same issue
