### ISSUE TITLE
typescript环境使用HeaderSearch组件报 _@types_react@16.8.8@@types/react/index"' has no default export   

### ISSUE THREAD

**Issue by yuanxiaoyu** [ant-design/ant-design-pro#3868]
C:/Users/HYdata/Desktop/editor/node_modules/_ant-design-pro@2.3.1@ant-design-pro/lib/HeaderSearch/index.d.ts
(1,8): Module '"C:/Users/HYdata/Desktop/editor/node_modules/_@types_react@16.8.8@@types/react/index"' has no default export.

发现该组件 index.d.ts 引入react 方式错误  改为import * as React from 'react' 即可

**Comment by imhele** [comment]
你的 typescript 版本是？

**Comment by imhele** [comment]
https://github.com/yannickcr/eslint-plugin-react/issues/2187#issuecomment-468993877
