### ISSUE TITLE
预览页面显示不正常~

### ISSUE THREAD

**Issue by Gaion** [ant-design/ant-design-pro#387]
![image](https://user-images.githubusercontent.com/7481093/33731705-00872eca-dbbf-11e7-9bb8-ff666dbab3e8.png)

**Comment by nikogu** [comment]
![image](https://user-images.githubusercontent.com/1179603/33747084-e3bb4942-dbfb-11e7-8ea5-56238736d6f5.png)

这个是响应式的设计。。。宽度太小，环比显示不全，所以换行

![image](https://user-images.githubusercontent.com/1179603/33747100-f2df2812-dbfb-11e7-8227-05999a28343c.png)

这个未重现，方便给下出问题的窗口宽度吗，顺便检查下是否浏览器缩放。

**Comment by Gaion** [comment]
桌面分辨率：1280*800
浏览器：chrome 63.0.3239.84     safari 11.0.1     360安全浏览器

**Comment by afc163** [comment]
窗口宽度

**Comment by Gaion** [comment]
没有启用浏览器缩放，浏览器窗口，chrome 1280*680  safari  1280*740

**Comment by Gaion** [comment]
chrome 1280 \* 680 
safari 1280 \* 740

**Comment by afc163** [comment]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/507615/33752822-eff43016-dc1e-11e7-8f01-bd446f3bff7e.png">

chrome 63.0.3239.84 未能重现

**Comment by afc163** [comment]
你的截图里的文案为啥还是『门店访问量』，建议你强刷一下试试。

**Comment by chenshuai2144** [comment]
我的google也没有重现..
倒是edge 
![image](https://user-images.githubusercontent.com/8186664/33752886-4654caf6-dc1f-11e7-80ef-cb0028993cad.png)

双重滚动条...


Microsoft Edge 41.17025.1000.0
windows 10 171020

**Comment by Gaion** [comment]
@afc163 你刚刚那个截图，切换一个tab试试
![image](https://user-images.githubusercontent.com/7481093/33753121-c1ae6f76-dc20-11e7-856b-9e1303d20923.png)

**Comment by afc163** [comment]
发现了。

**Comment by chenshuai2144** [comment]
@afc163 我改吧 找到问题了.

**Comment by Gaion** [comment]
这个？
![image](https://user-images.githubusercontent.com/7481093/33753517-a76d0b16-dc22-11e7-8ed5-2c3da3fa3e07.png)

**Comment by chenshuai2144** [comment]
@Gaion  这个是什么环境和屏幕大小!

**Comment by Gaion** [comment]
跟刚才一样~

**Comment by Gaion** [comment]
图标没了~
![image](https://user-images.githubusercontent.com/7481093/33753640-452e3c94-dc23-11e7-8272-7235ce1db170.png)

**Comment by chenshuai2144** [comment]
@nikogu  图表你看看,

**Comment by chenshuai2144** [comment]
@Gaion 1276的宽度正好出现这个问题.

**Comment by Gaion** [comment]
问一下，这种小屏幕下的图表文字问题，有啥好的解决办法没有？折腾图表的时候经常预见~
![image](https://user-images.githubusercontent.com/7481093/33753928-ed4ec316-dc24-11e7-8907-9415d497bd03.png)

**Comment by chenshuai2144** [comment]
@Gaion   试试  [f2](https://antv.alipay.com/zh-cn/f2/3.x/index.html)

**Comment by Gaion** [comment]
@chenshuai2144 好的，我试试，多谢~
