### ISSUE TITLE
[WIP] [v2] 一小部分未修复的类型定义

### ISSUE THREAD

**Issue by imhele** [ant-design/ant-design-pro#3870]
目前在 https://github.com/imhele/ant-design-pro/tree/v3 修改，完成后统一 pr
### NoticeIcon
- [x] props 可选
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/NoticeIcon/NoticeIconTab.d.ts#L24-L27
- [x] `NoticeIconData` 泛型支持
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/NoticeIcon/NoticeIconTab.d.ts#L17
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/NoticeIcon/index.d.ts#L10
- [x] `clickClose` 缺失
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/NoticeIcon/NoticeIconTab.d.ts#L4

### HeaderDropdown
- [x] 多余的定义
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/HeaderDropdown/index.d.ts#L8-L9

### Exception
- [x] `typeof Link`
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/Exception/index.d.ts#L17

### models/menu
- [ ] 多余的参数，https://github.com/ant-design/ant-design-pro/commit/b7b675acf8dfb000743e5dfcfe1af8bd6c756508 修复方式错误
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/models/menu.js#L112-L113

### HeaderSearch
- [x] `value: SelectValue`
https://github.com/ant-design/ant-design-pro/blob/5af79375f204622b3c73caccbd236d33caeef974/src/components/HeaderSearch/index.d.ts#L7-L10

**Comment by chenshuai2144** [comment]
组件会去掉 不需要太费精力

**Comment by xiaohuoni** [comment]
去掉这些问题可以提到antd吧？

**Comment by imhele** [comment]
这是 v3 迁移到 blocks 顺带记录的问题，不会再专门花费精力找 v2 的 bug 了
