### ISSUE TITLE
本地正常，打包发布后显示 Uncaught TypeError: Object(...) is not a function 

### ISSUE THREAD

**Issue by cc20140820** [ant-design/ant-design-pro#3872]
![image](https://user-images.githubusercontent.com/25069568/55207843-d783ad80-5216-11e9-8069-2e0cc1546bb7.png)

**Comment by cc20140820** [comment]
request.js中的问题

**Comment by zhaolixiang** [comment]
请问是怎么解决的，我也遇到了这个问题

**Comment by carrollcai** [comment]
我也遇到同样的问题。本地不报错，生产报错。把两个import引入注释了，就没问题。非常诡异

**Comment by liugui123** [comment]
请问是怎么解决的，我也遇到了这个问题
