### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by chinaxiaoyy** [ant-design/ant-design-pro#3873]
<img width="673" alt="WX20190329-123245@2x" src="https://user-images.githubusercontent.com/20460743/55209684-cccd1680-521e-11e9-8169-4cda7533f6cd.png">
npm: 6.4.1  node: 10.15.3

.webpackrc.js:
export default {
  entry: 'src/index.js',
  extraBabelPlugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
    ["module-resolver", {
      "root": ["./src"],
      "alias": {
        "~": "./src",
      }
    }]
  ],
  env: {
    development: {
      extraBabelPlugins: [
        'dva-hmr'
      ]
    }
  },
  ignoreMomentLocale: true,
  theme: './src/theme.js',
  html: {
    template: './src/index.ejs'
  },
  publicPath: '/',
  hash: true,
  copy: [{
    from: 'iconfont',
    to: 'iconfont'
  }],
  proxy: {
    '/api': {
      target: 'http://172.18.28.248:5556/',
      changeOrigin: true,
      pathRewrite: { '^/api': '' },
      secure: false
    }
  }
}

package.json:
{
  "name": "hive",
  "version": "0.1.0",
  "description": "hive dashboard",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "node node_modules/cross-env/dist/bin/cross-env.js ESLINT=none NO_PROXY=true roadhog dev",
    "start:no-proxy": "cross-env NO_PROXY=true roadhog dev",
    "build": "COMPRESS=none roadhog build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "ANALYZE=true roadhog build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "jest",
    "test:comps": "jest ./src/components",
    "test:all": "node ./tests/run-tests.js"
  },
  "dependencies": {
    "@antv/data-set": "^0.8.6",
    "@babel/polyfill": "^7.0.0-beta.36",
    "antd": "^3.15.1",
    "axios": "^0.17.1",
    "babel-runtime": "^6.9.2",
    "bizcharts": "^3.5.1",
    "bizcharts-plugin-slider": "^2.0.1",
    "brace": "^0.11.0",
    "classnames": "^2.2.5",
    "dva": "^2.1.0",
    "dva-loading": "^1.0.4",
    "enquire-js": "^0.1.1",
    "fastclick": "^1.0.6",
    "is-url": "^1.2.4",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.4.1",
    "moment": "^2.19.1",
    "npm": "^6.0.1",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "rc-drawer-menu": "^0.5.0",
    "react": "^16.8.0",
    "react-ace": "^5.9.0",
    "react-container-query": "^0.9.1",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.2.0",
    "react-fittext": "^1.0.0",
    "react-mixin": "2",
    "url-polyfill": "^1.0.10"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.37",
    "@babel/preset-env": "^7.0.0-beta.36",
    "@babel/preset-react": "^7.0.0-beta.36",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.1.2",
    "babel-jest": "^22.0.4",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "eslint": "^4.14.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-html": "^4.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.0.1",
    "gh-pages": "^1.0.0",
    "husky": "^0.14.3",
    "jest": "^22.0.4",
    "js-base64": "^2.5.1",
    "jsdom": "^11.5.1",
    "jsencrypt": "^3.0.0-rc.1",
    "lint-staged": "^6.0.0",
    "mockjs": "^1.0.1-beta3",
    "pro-download": "^1.0.1",
    "react-test-renderer": "^16.2.0",
    "redbox-react": "^1.5.0",
    "roadhog": "^2.5.0-beta.1",
    "roadhog-api-doc": "^0.3.4",
    "rollbar": "^2.3.4",
    "stylelint": "^8.4.0",
    "stylelint-config-standard": "^18.0.0"
  },
  "optionalDependencies": {
    "nightmare": "^2.10.0"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "transform-class-properties"
    ]
  },
  "jest": {
    "setupFiles": [
      "<rootDir>/tests/setupTests.js"
    ],
    "testMatch": [
      "**/?(*.)(spec|test|e2e).js?(x)"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/tests/jasmine.js",
    "moduleFileExtensions": [
      "js",
      "jsx"
    ],
    "moduleNameMapper": {
      "\\.(css|less)$": "<rootDir>/tests/styleMock.js"
    }
  },
  "lint-staged": {
    "**/*.{js,jsx}": "lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "theme": {
    "primary-color": "#1088ae"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}

**Comment by chinaxiaoyy** [comment]
紧急求助

**Comment by chinaxiaoyy** [comment]
@afc163 帮忙给看看呗，谢谢了

**Comment by chenshuai2144** [comment]
eslint出错了 看看eslint得配置

**Comment by chenshuai2144** [comment]
"eslint-plugin-compat" 这个包最近有更新 你可以锁包

**Comment by chinaxiaoyy** [comment]
.eslintrc:
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "plugins": ["compat"],
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "mocha": true,
    "jest": true,
    "jasmine": true
  },
  "rules": {
    "no-console": "off",
    "generator-star-spacing": [0],
    "consistent-return": [0],
    "react/forbid-prop-types": [0],
    "react/jsx-filename-extension": [1, { "extensions": [".js"] }],
    "global-require": [1],
    "import/prefer-default-export": [0],
    "react/jsx-no-bind": [0],
    "react/prop-types": [0],
    "react/prefer-stateless-function": [0],
    "react/jsx-wrap-multilines": ["error", {
      "declaration": "parens-new-line",
      "assignment": "parens-new-line",
      "return": "parens-new-line",
      "arrow": "parens-new-line",
      "condition": "parens-new-line",
      "logical": "parens-new-line",
      "prop": "ignore"
    }],
    "no-else-return": [0],
    "no-restricted-syntax": [0],
    "import/no-extraneous-dependencies": [0],
    "no-use-before-define": [0],
    "jsx-a11y/no-static-element-interactions": [0],
    "jsx-a11y/no-noninteractive-element-interactions": [0],
    "jsx-a11y/click-events-have-key-events": [0],
    "jsx-a11y/anchor-is-valid": [0],
    "no-nested-ternary": [0],
    "arrow-body-style": [0],
    "import/extensions": [0],
    "no-bitwise": [0],
    "no-cond-assign": [0],
    "import/no-unresolved": [0],
    "comma-dangle": ["error", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "ignore"
    }],
    "max-len": ["error", 800],
    "no-param-reassign": [0],
    "no-underscore-dangle": "error",
    "semi": ["error", "never"],
    "no-unused-vars": ["error", { "args": "none" }],
    "no-unused-expressions": ["error", { "allowShortCircuit": true, "allowTernary": true }],
    "object-curly-newline": [0],
    "function-paren-newline": [0],
    "no-restricted-globals": [0],
    "require-yield": [1],
    "linebreak-style": [0 ,"error", "windows"],
    "prefer-destructuring": ["error", {"object": true, "array": false}]
  },
  "parserOptions": {
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "settings": {
    "polyfills": ["fetch", "promises"]
  }
}
@chenshuai2144 辛苦帮忙定位下问题

**Comment by chenshuai2144** [comment]
看master 锁一下包

**Comment by chinaxiaoyy** [comment]
好的，辛苦

**Comment by hocko333** [comment]
你好，请问你最后怎么解决的？
我也是设置了`"semi": [2, "never"]`，并且运行了`yarn lint:fix`，将所有分号去除后，却无法`git commit`，git hooks告诉我`Extra semicolon`
