### ISSUE TITLE
关于列表页和详情页的交互

### ISSUE THREAD

**Issue by soulmatecm** [ant-design/ant-design-pro#3874]
例如：列表路由 /device/list和详情路由/device/:id，希望点击列表中的项时跳转到详情页面（hideInMenu），但是仍然高亮当前的列表路由，有什么优雅一点的做法吗？详情字段比较多，通过Modal交互不太合适。

**Comment by imhele** [comment]
不如使用路由 /device/list/:id

**Comment by soulmatecm** [comment]
> 不如使用路由 /device/list/:id

ok，谢谢
