### ISSUE TITLE
Switch 使用Model.confirm() 二次确认后再改变状态，如果取消确认，Switch不改变状态，Switch需要怎么做

### ISSUE THREAD

**Issue by enjoyass** [ant-design/ant-design-pro#3875]
`

   // table columns
     columns = [{  
        &nbsp; &nbsp; &nbsp; &nbsp;title: '开关',  
        &nbsp; &nbsp; &nbsp; &nbsp;dataIndex: 'open_status',
        &nbsp; &nbsp; &nbsp; &nbsp;render:(val, record)=>(<Switch checkedChildren="开" unCheckedChildren="关" defaultChecked={Boolean(val)} onClick={(checked)=>this.callChange(checked,record.data,event)} />),
    },];
   // callback function
    callChange = (checked,data,event) => {
     &nbsp; &nbsp;Modal.confirm({
       &nbsp; &nbsp; &nbsp; &nbsp;title: `really?`,
       &nbsp; &nbsp; &nbsp; &nbsp;content: 'When clicked the OK button, this dialog will be closed after 1 second',
       &nbsp; &nbsp; &nbsp; &nbsp;onOk() {
         &nbsp; &nbsp; &nbsp; &nbsp;this.handleCloseTable(checked,data)
       &nbsp; &nbsp; &nbsp; &nbsp;},
       &nbsp; &nbsp; &nbsp; &nbsp;onCancel() {
        &nbsp; &nbsp; &nbsp; &nbsp;console.log(event)
       &nbsp; &nbsp; &nbsp; &nbsp;},
    &nbsp; &nbsp;});
  }
`

**Comment by chenshuai2144** [comment]
这个用redux可以轻松做到的。
你需要把状态托管给第三方去做处理。弹框是一个异步的过程

**Comment by zhangxin6683** [comment]
还是同样的问题，自己还是没有写出来，请大佬求教

**Comment by zhangxin6683** [comment]
> `
> 
> // table columns
> columns = [{
>        title: '开关',
>        dataIndex: 'open_status',
>        render:(val, record)=>(<Switch checkedChildren="开" unCheckedChildren="关" defaultChecked={Boolean(val)} onClick={(checked)=>this.callChange(checked,record.data,event)} />),
> },];
> // callback function
> callChange = (checked,data,event) => {
>    Modal.confirm({
>        title: `really?`,
>        content: 'When clicked the OK button, this dialog will be closed after 1 second',
>        onOk() {
>        this.handleCloseTable(checked,data)
>        },
>        onCancel() {
>        console.log(event)
>        },
>    });
> }
> `

请问handleCloseTable这个方法里面该怎么写语句啊，因为运行后报错说缺少handleCloseTable方法

**Comment by enjoyass** [comment]
@zhangxin6683 handleCloseTables是自己定义的方法，你自己可以定义，也可以去掉

**Comment by zhangxin6683** [comment]
@enjoyass 去掉的话，switch就不能确认后再改变状态了，请问这个方法里面是不是该写表达语句啊

**Comment by enjoyass** [comment]
@zhangxin6683 我还没写，建议你可以看下switch模块的源码，自己尝试修改实现下。

**Comment by enjoyass** [comment]
@zhangxin6683 如果你单独的一个switch,应该很好实现，在onOk之前，让checked状态回复到之前的值。Ok后在改变值。我这边主要是嵌套在table中的。

**Comment by zhangxin6683** [comment]
@enjoyass 因为我刚接触这个，写了好久，自己也想过用state的方法，可是不知道该怎么下手，该怎么写，难受

**Comment by zhangxin6683** [comment]
@enjoyass 主要还是不会用state吧

**Comment by enjoyass** [comment]
@zhangxin6683 我抽空实现个demo，共享出来。

**Comment by zhangxin6683** [comment]
@enjoyass 谢谢了

**Comment by dmdoit** [comment]
上边 @chenshuai2144 说了，在redux可以轻松做到，我刚好也遇到这个功能，就想了方法， 因为modal是异步的，所以Switch不要用onChange和onClick事件，直接通过checked为true和false显示开关。在redux里定义一个state，判断checked为true和false的条件是根据这个state，当点击modal的确定按钮时，发送请求，然后改变redux里state的值
