### ISSUE TITLE
多小组协同开发：公用菜单导航，各建项目写page

### ISSUE THREAD

**Issue by Smith-Jefferson** [ant-design/ant-design-pro#3879]
你好，作为一个大的管理系统，有一个共用的菜单，统一管理权限等，各个pages下的业务代码由每个小组分开创建一个project分开开发。
想请教一下怎样将各个project组合起来呢？是菜单栏所在的项目引用其他project？还是其他project引用菜单栏的project？具体怎么做呢？
（关于第一种方案，如果各小组所有的项目全写成block，似乎很繁琐，菜单栏所在project的代码最后非常庞大，如果不是用使用block，怎样让引入的page和对应的model关联起来，以及在路由配置文件中写路由，也是问题 ）
希望大牛指点下解决方案，谢谢

**Comment by jianghongtao0228** [comment]
同问，如果其他项目不全是前后台分离的前端项目，比如其中包含传统的jsp开发的页面 应该怎么操作呢？

**Comment by wangxingkang** [comment]
关注

**Comment by zhangshuai0101** [comment]
我是从一个主工程里拉出三个分支，各自开发各自的业务，最后通过脚本把三个分支的业务代码合并到主工程

**Comment by Smith-Jefferson** [comment]
> 我是从一个主工程里拉出三个分支，各自开发各自的业务，最后通过脚本把三个分支的业务代码合并到主工程

这个方案我们在c#写界面时代实践过，最后代码膨胀到1G以上，各种代码混合在一起（很多代码随着需求改变没用了），最后很所时候不敢删除、不敢轻易改变，测试起来周期也长了，无论是写代码、合并、到发布都很痛苦。所以后来可劲的拆。经历过这个过程以后，再也不想搞大集合了

**Comment by zhangshuai0101** [comment]
> 过程



> > 我是从一个主工程里拉出三个分支，各自开发各自的业务，最后通过脚本把三个分支的业务代码合并到主工程
> 
> 这个方案我们在c#写界面时代实践过，最后代码膨胀到1G以上，各种代码混合在一起（很多代码随着需求改变没用了），最后很所时候不敢删除、不敢轻易改变，测试起来周期也长了，无论是写代码、合并、到发布都很痛苦。所以后来可劲的拆。经历过这个过程以后，再也不想搞大集合了

都是组件化开发，每个业务无非对应1个文件夹，就算没用了，直接删除不就好了

**Comment by topwood** [comment]
mark

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-plugin-qiankun

**Comment by fanhualei** [comment]
如果是多人协作的大项目，需要有一个总的架构师来维护各个开发工作的平衡，而不能依赖框架来解决。
另外框架也解决不了，因为实际项目中都是业务之间的耦合，框架根本不了解业务，当然也无法对业务进行解耦处理。

架构师负责把各个模块分解及抽象出来。
1：规定好命名规范，以及冲突解决方法。
2：提出公用的函数，组件，避免大家重复劳动。
3：提供demo实例
4：日常检查代码
5：提前进行部署版本依赖测试。

**Comment by chenshuai2144** [comment]
关注 https://github.com/umijs/umi-plugin-qiankun 吧
