### ISSUE TITLE
导航菜单收起后safari浏览器点不到菜单

### ISSUE THREAD

**Issue by GaliMU** [ant-design/ant-design-pro#388]
收起状态，鼠标悬浮在导航菜单图标时隐藏的子菜单可以显示。但是把鼠标移动到子菜单的时候，子菜单就消失了。目前只发现safari（版本11.0.2）存在这个问题，chrome（ 版本62.0.3202.94）火狐（版本57.0 ）可以点击。safari效果如下：
![aa](https://user-images.githubusercontent.com/17948137/33749336-2574142a-dc08-11e7-8b3b-3e5689b90692.gif)

**Comment by afc163** [comment]
Duplicate of #353
