### ISSUE TITLE
setState后Select组件的value值并没有更新

### ISSUE THREAD

**Issue by chinaxiaoyy** [ant-design/ant-design-pro#3880]
[Select组件bug.zip](https://github.com/ant-design/ant-design-pro/files/3025363/Select.bug.zip)
由于在本机环境下可以复现，但是官网文档不存在这个问题，所以录了屏，大佬们帮忙看看

**Comment by zhangshuai0101** [comment]
this.forceUpdate() 试一下呢

**Comment by chenshuai2144** [comment]
最好给一个 codebox。给个 gif 毫无意义。
我猜测是你是不是用PrueCompontent

**Comment by ldw21cn** [comment]
yield put({ type: 'fetch' })

试下这个。
