### ISSUE TITLE
请求参数带#符号

### ISSUE THREAD

**Issue by losewayman** [ant-design/ant-design-pro#3885]
如果请求参数中有#符号，#后面（包括#）的参数会直接被截掉，请求只会携带#前面的参数

**Comment by chenshuai2144** [comment]
？？？没懂你说的是什么详细描述一下？

**Comment by losewayman** [comment]
假如我dispatch一个请求，携带一个参数，这个参数中有#这个符号，然后从effects到servers/api.js再到request.js 中参数都是完整的，但是请求发出去以后，在控制台上看请求携带参数发现#符号以后的参数都没了，携带的参数从#以后截断了

**Comment by losewayman** [comment]
> ？？？没懂你说的是什么详细描述一下？
假如我dispatch一个请求，携带一个参数，这个参数中有#这个符号，然后从effects到servers/api.js再到request.js 中参数都是完整的，但是请求发出去以后，在控制台上看请求携带参数发现#符号以后的参数都没了，携带的参数从#以后截断了

**Comment by chenshuai2144** [comment]
了解一下编码解码相关功能
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/decodeURI
