### ISSUE TITLE
代码更新后页面老是跳转到登录

### ISSUE THREAD

**Issue by qingfeng9595** [ant-design/ant-design-pro#3889]
之前热更新还是没有问题的，这几天突然热更新老是跳转到登录页面，而且发现只有配置了页面元素权限的页面才会如此，请问是什么原因导致的？
以下是我的问题页面代码：
import React, { PureComponent, Fragment } from 'react';
import RenderAuthorized from '@/components/Authorized';
import { connect } from 'dva';
import moment from 'moment';
import Appconst from '@/utils/appconst';
import { getCurrentUserRole } from '@/utils/authority'
import { sortFlowNode,completeNodeDom,currentNode,getOptionListKey,getOptionList } from '@/utils/utils'
import {
  Row,
  Col,
  Card,
  Form,
  Input,
  Select,
  Spin,
  Icon,
  Button,
  InputNumber,
  DatePicker,
  Modal,
  message,
  Radio,
  Tree,
  Collapse,
  Table,
  Divider,
  Upload,
  Alert
} from 'antd';
import styles from './PriceApproval.less';
import FileUpload from '@/components/FileUpload';
const Panel = Collapse.Panel;
const FormItem = Form.Item;
const { TextArea } = Input;
const Option = Select.Option;
@Form.create()
class ApprovalContent extends PureComponent{
  render(){
    const {
      form,
      logData,
    } = this.props
    // const Authorized = RenderAuthorized(userRole[0]);
    // const noMatch = <Alert message="No permission." type="error" showIcon />;
    const formLayout = {
      labelCol: { span: 2 },
      wrapperCol: { span: 22 },
    };
    return (
      <Fragment>
        <Form layout="inline" className="formInline">
          <Row>
            <Col sm={24}>
              {completeNodeDom(logData,form)}
            </Col>
          </Row>
        </Form>
      </Fragment>
    )
  }
}
/**
 * 当前操作节点渲染
 */
@Form.create()
class CurrentApproval extends PureComponent{
  render(){
    const {
      form,
      userRole,
      current
    } = this.props
    const Authorized = RenderAuthorized(userRole[0]);
    // const noMatch = <Alert message="No permission." type="error" showIcon />;
    const formLayout = {
      labelCol: { span: 2 },
      wrapperCol: { span: 22 },
    };
    return(
      <Fragment>
        <Form layout="inline" className="formInline">
          <Authorized authority={userRole}>
            <Row>
              <Col sm={24} >
                <FormItem label={current.nodeName} {...formLayout}>
                  {form.getFieldDecorator('remarks')(
                    <TextArea minLength={2} />  
                  )}
                </FormItem>
              </Col>
            </Row>
          </Authorized>
        </Form>
      </Fragment>
    )
  }
}
@connect(({ priceApproval, loading }) => ({
  priceApproval,
  loading: loading.models.priceApproval,
}))
@Form.create()
export default class PriceApprovalFlow extends PureComponent{
  // constructor(props){
    // super(props)
    // console.log(this.props.location.state)
    // this.setState({
    //   orderDetails:this.props.location.state
    // })
  // }
  state = {
    materialData:[],
    orderDetails:{},
    modalVisible:false,
    updateModalVisible:false,
    record:{},
    userRole:[],
    optionItemData:[],
    expandedRowKeys:[],
    loading:true,
    current:{},
    priceRange:[],
    isBussine:false,
    margin:'',
    margin2:'',
    // estimatedFactoryTime:new Date(),
  }

  optionItemColumns = [
    {
      title:'选配项',
      dataIndex:'optionItem',
      key:'optionItem',
    },
    {
      title:'选配项名称',
      dataIndex:'itemName',
      key:'itemName',
    },
    {
      title:'表价',
      dataIndex:'optionPrice',
      key:'tablePrice',
      // with:'15%'
    },
    {
      title:'选配件折扣',
      dataIndex:'optionDiscount',
      key:'optionDiscount',
      // with:'15%'
    },
  ]
  materialColumns = [
    {
      title:'规格型号-物料名称',
      dataIndex:'specificationType',
      key:'specificationType',
      with:'20%',
      editable: true,
    },
    {
      title:'表价',
      dataIndex:'tablePrice',
      key:'tablePrice',
      with:'15%'
    },
    {
      title:'折扣',
      dataIndex:'discount',
      key:'discount',
      with:'15%',
      editable: true,
    },
    {
      title:'折扣后单价（取整）',
      dataIndex:'discountPrice',
      key:'discountPrice',
      with:'20%'
    },
    {
      title:'数量',
      dataIndex:'number',
      key:'number',
      with:'15%',
      editable: true,
    },
    {
      title:'金额',
      dataIndex:'totalSum',
      key:'totalSum',
      with:'15%'
    },
  ]
  flowNodeColumns = [
    {
      title:'序号',
      dataIndex:'sortNo',
      key:'sortNo',
      width:'80px'
    },
    // {
    //   title:'审批节点',
    //   dataIndex:'nodeCode',
    //   key:'nodeCode',
    //   width:'20%',
    // },
    {
      title:'节点名称',
      dataIndex:'nodeName',
      key:'nodeName',
      width:'20%',
    },
    {
      title:'审批人',
      dataIndex:'operator',
      key:'operator',
    },
    {
      title:'审批状态',
      dataIndex:'status',
      key:'status',
      width:'10%',
      render:val=>{
        if(val=='Activate')return "激活"
        else if(val == 'Wait')return '等待'
        else if(val == 'Complete')return '完成'
        else if(val == 'Return')return '退回'
        else if(val == 'Cancel')return '作废'
        else return '无效' 
      }
    },
  ]
  logColumns = [
    {
      title:'操作节点',
      dataIndex:'operationNode',
      key:'operationNode',
      width:'20%'
    },
    {
      title:'操作人',
      dataIndex:'operator',
      key:'operator',
      // width:'20%'
    },
    {
      title:'审批状态',
      dataIndex:'status',
      key:'status',
      width:'10%',
      render:val=>{
        if(val=='Activate')return "激活"
        else if(val == 'Wait')return '等待'
        else if(val == 'Complete')return '完成'
        else if(val == 'Return')return '退回'
        else if(val == 'Cancel')return '作废'
        else return '无效' 
      }
    },
    {
      title:'操作内容',
      dataIndex:'operationContent',
      key:'operationContent',
      width:'20%'
    },
    {
      title:'操作时间',
      dataIndex:'operationTime',
      key:'operationTime',
      render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
      // width:'20%'
    }
  ]
 componentWillMount(){
  console.log(this.props.location.state)
  let orderDetails = this.props.location.state;
  this.setState({
    orderDetails,
  })
 }
 
  componentDidMount(){
    const {orderDetails} = this.state
  // console.log(this.props.location.state)
  // let orderDetails = this.props.location.state;
  if(orderDetails.nodecode == 'Node_BusinessSupervisor' || orderDetails.nodecode == 'Node_BusinessSupervisor2'){
    this.setState({
      isBussine:false
    })
  }else{
    this.setState({
      isBussine:true
    })
  }
  if(orderDetails.flowName.indexOf('Lar') >= 0){
    this.handleRequestMagin();
  }
  // this.setState({
  //   orderDetails,
  // })
  this.handleGetUser();
  this.handleRequest(orderDetails.key);
  this.handleApprovalFlow(orderDetails.key);
  this.handleApprovalLog(orderDetails.key);
 }
 /**
  * 获取登录人角色
  */
 handleGetUser = ()=>{
  let userRole = getCurrentUserRole();
  console.log(userRole)
  this.setState({
    userRole
  })
 }

/**
 * 判断流程类型，在商务节点时获取价格区间
 * @param {string} flowName
 */
handleRequestMagin=()=>{
  const { dispatch } = this.props;
  dispatch({
    type:'priceApproval/fetchPriceRange',
  }).then(()=>{
    const { 
      priceApproval:{data},
      loading
     } = this.props
     console.log(data)
     this.setState({
       priceRange:data
     })
  })
}
 /**
  * 保存提交
  */
 handleSubmit = ()=>{
  this.setState({
    loading:true
  })
  let currentApproval = this.currentApproval.props.form.getFieldsValue();
  const { 
    current,
    orderDetails,
    margin,
    margin2,
    fileList
   } = this.state;
  currentApproval.key = orderDetails.key;
  currentApproval.nodeCode = current.nodeCode;
  currentApproval.margin = margin;
  currentApproval.margin2 = margin2;
  currentApproval.fileId = fileList;
  if(this.state.estimatedFactoryTime){
    currentApproval.estimatedFactoryTime = this.state.estimatedFactoryTime;
  }
  // if(currentAppr){}
  // console.log(current)
  console.log(currentApproval)
  const { dispatch } = this.props;
  dispatch({
    type:'priceApproval/approvalDiscountApplications',
    payload:currentApproval
  }).then(()=>{
    const {
      priceApproval:{data},
      loading
    } = this.props 
    console.log(data)
    if(data.success){
      message.success('提交成功！这在跳转...');
      setTimeout(()=>{
        window.location.href = '/eorder/priceApproval/pending'
      },1000)
    }else{
      message.error(data.message)
    }
  })
  // message.success('提交成功！这在跳转...');
  // setTimeout(()=>{
  //   this.props.history.push('/priceApproval/viewList')
  // },1000)
 }
 /**
  * 订货信息
  * @param key 此审批单guid
  */
 handleRequest=(key)=>{
  this.setState({
    loading:true
  })
  const { dispatch } = this.props;
  dispatch({
    type:'priceApproval/fetchDiscountProductById',
    payload:{key}
  }).then(()=>{
    const {
      priceApproval: { data },
      loading,
    } = this.props;
    if(data.success){
      let materialData = data.result;
      let optionItemData = data.result.optionItems;
      this.setState({
        materialData,
        optionItemData,
        loading:false
      })
    }else{
      message.error(data.message)
    }
  })
 }

/**
 * 返回按钮
 */
handleBack = ()=>{
  window.location.href = '/eorder/priceApproval/pending'
}

/**
 * 退回
 */
handleReturnModalVisible=()=>{
  let _that = this;
  const { orderDetails } = this.state;
  Modal.confirm({
    title:`确认退回${orderDetails.reportNo}折扣号审批?`,
    // content:'你确定学会了react了吗？',
    onOk(){
      _that.returnOkHandle(orderDetails.key)
    },
    onCancel(){
      // console.log("cancel")
    }
  })
}
/**
 * 退回执行
 * @param { string } key
 * @param { string } nodeCode
 * @param { string } remarks
 */
returnOkHandle=(key)=>{
  this.setState({
    loading:true
  })
  let currentApproval = this.currentApproval.props.form.getFieldsValue();
  const { current } = this.state;
  currentApproval.key = key;
  currentApproval.nodeCode = current.nodeCode;
  console.log(currentApproval)
  const { dispatch } = this.props;
  dispatch({
    type:'priceApproval/returnDiscountApplications',
    payload:currentApproval
  }).then(()=>{
    const {
      priceApproval:{data},
      loading
    } = this.props
    if(data.success){
      message.success('退回成功！正在跳转...');
      setTimeout(()=>{
        window.location.href = '/eorder/priceApproval/pending'
      },1000)
    }else{
      message.error(data.message)
    }
  })
}

/**
 * 点击展开图标时间
 * @param expanded {boolean} 展开为true，闭合为false
 * @param record 此行数据信息
 */
onExpand=(expanded, record)=>{
  if(expanded){
    this.setState({
      expandedRowKeys:[record.key],
      optionItemData:record.optionItems
    })
  }else{
    this.setState({
      expandedRowKeys:[],
    })
  }
}
/**
 * 获取审批流程
 * @param key 此审批单guid
 * 接口直接返回数据未添加失败响应,dto加key字段避免react错误
 */
handleApprovalFlow = (key)=>{
  this.setState({
    loading:true
  })
  const { dispatch } = this.props;
  dispatch({
    type:'priceApproval/fetchFlowNodeByKey',
    payload:{key}
  }).then(()=>{
    const {
      priceApproval:{data},
      loading
    } = this.props
    if(data.success){
      let flowNodeData = sortFlowNode(data.result);
      let current = currentNode(flowNodeData)
      console.log(data)
      this.setState({
        current,
        flowNodeData,
        loading:false
      })
    }else{
      message.error(data.message)
    }
  })
}
/**
 * 获取操作日子
 * @param key 此审批单guid
 * 接口直接返回数据未添加失败响应,dto加key字段避免react错误
 */
handleApprovalLog = (key)=>{
  this.setState({
    loading:true
  })
  const { dispatch } = this.props;
  dispatch({
    type:'priceApproval/fetchLogByKey',
    payload:{key}
  }).then(()=>{
    const {
      priceApproval:{data},
      loading
    } = this.props
    if(data.success){
      console.log(data)
      let logData = data.result
      this.setState({
        logData,
        loading:false
      })
    }else{
      message.error(data.message)
    }
  })
}
/**
 * 大电流价格区间change事件
 */
handleMaginChange=(value,option)=>{
  console.log(value) 
  this.setState({
    margin:value
  })
}
/**
 * 非标价格区间change事件
 */
handleNonMaginChange=(e)=>{
  console.log(e.target.value)
  this.setState({
    margin2:e.target.value
  })
}
/**
 * 判断大电流价格区间权限
 */
handleLargePermission=()=>{
  const { orderDetails } = this.state;
  if(orderDetails.flowName.indexOf("Lar") == -1){return false}
  if(
  orderDetails.nodecode == 'Node_BusinessSupervisor' ||
  orderDetails.nodecode == 'Node_SalesDirector' ||
  orderDetails.nodecode == 'Node_GeneralManager' 
  ){
    return true
  }else{
    return false
  }
}
/**
 * 判断预计出厂时间权限
 */
handleEstimatedPermission=()=>{
  const { orderDetails } = this.state;
  if(orderDetails.flowName.indexOf("Non") != -1){
    if(orderDetails.nodecode == 'Node_Salesman3'){
        return true
      }else{
        return false
    }
  }else{
    if(orderDetails.nodecode == 'Node_Salesman2'){
      return true
    }else{
      return false
  }
  }
}
/**
 * 判断非标价格区间权限
 */
handleNonPermission=()=>{
  const { orderDetails } = this.state;
  let arr = ['Node_BusinessSupervisor','Node_BusinessSupervisor2','Node_SalesDirector','Node_GeneralManager','Node_FinancialBusiness','Node_CFO']
  if(orderDetails.flowName.indexOf("Non") == -1){return false}
  if(arr.includes(orderDetails.nodecode)){
      return true
    }else{
      return false
    }
}
/**
 * 预计出厂时间change事件
 */
handleDatePickerChange=(value)=>{
  let estimatedFactoryTime = moment(value).format('YYYY-MM-DD');
  console.log(estimatedFactoryTime);
  this.setState({
    estimatedFactoryTime
  })
}
/**
 * 附件上传
 */
handleUploadChange = (info)=>{
console.log(info.file, info.fileList);
  this.setState({fileList:[info.file]});
  console.log(info.file.response);
}
/**
 * 判断是否经销商申请
 */
handleIsDealerApplicant = ()=>{
  const { orderDetails } = this.state;
  if(orderDetails.applicantRole == 'Dealers'){
    return true
  }
  return false
}
/**
 * 判断是否技术节点
 */
handleProjectDesignNoPermission =()=>{
  const { orderDetails } = this.state;
  if(orderDetails.flowName.indexOf("Non") == -1){return false}
  if(orderDetails.nodecode == 'Node_Teach'){
    return true
  }
}
  render(){
    const Authorized = RenderAuthorized(this.state.userRole[0]);
    const isDealer = this.handleIsDealerApplicant();
    const customPanelStyle = {
      background: '#fff',
      borderRadius: 4,
      marginBottom: 24,
      border:0,
      overflow: 'hidden',
    };
    const formLayout = {
      labelCol: { span: 7 },
      wrapperCol: { span: 17 },
    };
    const { form } = this.props
    const uploadColumns = [
      {
        title:'操作',
        key:'edit',
        render: (text, record) => (
          <Fragment>
            <a><Icon type='delete' theme="filled"></Icon></a>
          </Fragment>
        ),
      },
      {
        title:'文件名称',
        dataIndex:'fileName'
      },
      {
        title:'上传时间',
        dataIndex:'uploadTime',
        key:'uploadTime',
      },
      {
        title:'上传人员',
        dataIndex:'uploadPerson',
        key:'uploadPerson',
      }
    ]
    const approvalContentProps = {
      logData:this.state.logData,
    }
    const currentApprovalProps = {
      userRole:this.state.userRole,
      current:this.state.current
    }
    const { current,priceRange,isBussine,orderDetails } = this.state
    const expandedRowRender = ()=>{
      return (
        <Table
          columns={this.optionItemColumns}
          dataSource={this.state.optionItemData}
          pagination={false}
        />
      );
    }
    return(
      <Spin spinning={this.state.loading}>
        <Collapse bordered={false} defaultActiveKey={['11','12','13','14','15']} style={{background:'transparent'}}>
          <Panel header="基本信息" key="11" style={customPanelStyle} className="panel-hook">
            <Form onSubmit={this.handleSearch} layout="inline" className="formInline">
              <Row>
                <Col md={8} sm={24}>
                  <FormItem label="申请人" {...formLayout}>
                    {form.getFieldDecorator('applicant',{
                      initialValue:orderDetails.applicant
                    })(
                      <Input disabled />
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="申请时间" {...formLayout}>
                    {form.getFieldDecorator('applicantTime',{
                      initialValue:moment(orderDetails.applicantTime)
                    })(
                      <DatePicker disabled style={{width:'100%'}}/>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="报备号" {...formLayout}>
                    {form.getFieldDecorator('reportNo',{
                      initialValue:orderDetails?orderDetails.reportNo:null
                    })(
                      <Input disabled/>
                    )}
                  </FormItem>
                </Col>
              </Row>
              <Row>
                <Col md={8} sm={24}>
                  <FormItem label="申请单位" {...formLayout}>
                    {form.getFieldDecorator('partnerDealer',{
                      initialValue:orderDetails.partnerDealer
                    })(
                      <Input disabled />
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="单位联系人" {...formLayout}>
                    {form.getFieldDecorator('dealerContacts',{
                      initialValue:orderDetails.dealerContacts
                    })(
                      <Input disabled />
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="联系方式" {...formLayout}>
                    {form.getFieldDecorator('contactWay',{
                      initialValue:orderDetails.contactWay
                    })(
                      <Input disabled />
                    )}
                  </FormItem>
                </Col>
              </Row>
              <Row>
                <Col md={8} sm={24}>
                  <FormItem label="是否黑名单" {...formLayout}>
                    {form.getFieldDecorator('inBlackList',{
                      initialValue:orderDetails.isBlacklist?'是':'否'
                    })(
                      <Input disabled />
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="项目所在地" {...formLayout}>
                    {form.getFieldDecorator('projectLocation',{
                      initialValue:orderDetails.projectLocation
                    })(
                      <Input disabled />
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="成本估算表号" {...formLayout}>
                    {form.getFieldDecorator('costEstimationNo',{
                      initialValue:orderDetails.costEstimationNo
                    })(
                      <Input disabled/>
                    )}
                  </FormItem>
                </Col>
              </Row>
              <Row>
                <Col sm={24}>
                  <FormItem label="项目名称" labelCol={{ span: 2 }} wrapperCol={{ span: 22 }}>
                    {form.getFieldDecorator('projectName',{
                      // initialValue:orderDetails?orderDetails.projectName:null
                      initialValue:orderDetails.projectName
                    })(
                      <TextArea minLength={2} disabled style={{width:'99%',marginLeft:'1.3%'}}/>
                    )}
                  </FormItem>
                </Col>
              </Row>
              <Row>
                <Col md={8} sm={24}>
                  <FormItem label="期望交货日期" {...formLayout}>
                    {form.getFieldDecorator('deliveryDate', {
                      initialValue: orderDetails?orderDetails.deliveryDate:null,
                    })(
                      <Input disabled/>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="提货方式" {...formLayout}>
                    {form.getFieldDecorator('deliveryMethod', {
                      initialValue:orderDetails?orderDetails.deliveryMethod:null,
                    })(
                      <Select placeholder='请选择' disabled>
                        <Option value="送货到需方指定地点">送货到需方指定地点</Option>
                        <Option value="客户自提">客户自提</Option>
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="运输方式" {...formLayout}>
                    {form.getFieldDecorator('transportMethod', {
                      initialValue: '汽运',
                    })(
                      <Select disabled>
                        <Option value="汽运">汽运</Option>
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="包装方式" {...formLayout}>
                    {form.getFieldDecorator('packageMethod', {
                      initialValue: '标准木箱单台包装',
                    })(
                      <Select disabled>
                        <Option value="标准木箱单台包装">标准木箱单台包装</Option>
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="收货省份" {...formLayout}>
                    {form.getFieldDecorator('shippingProvinces', {
                      initialValue:orderDetails.shippingProvinces,
                    })(
                      <Select placeholder="请选择" disabled onChange={this.handleProvinceChange}>
                        { getOptionList(this.state.provinces) }
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="收货城市" {...formLayout}>
                    {form.getFieldDecorator('shippingCity', {
                      initialValue: orderDetails.shippingCity,
                    })(
                      <Select placeholder="请选择" disabled onChange={this.handleShippingCityChange}>
                        { getOptionList(this.state.shippingCity) }
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="收货详细地址" {...formLayout}>
                    {form.getFieldDecorator('receivingAddress', {
                      initialValue: orderDetails?orderDetails.receivingAddress:null,
                    })(<Input placeholder="请输入" disabled />)}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="物流天数" {...formLayout}>
                    {form.getFieldDecorator('arrivalTime', {
                      initialValue: orderDetails.arrivalTime,
                    })(
                    <InputNumber 
                      placeholder="请输入" 
                      min={1} 
                      formatter={value => `${value}天`}
                      style={{width:'100%'}}
                      disabled
                    />)}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="收货联系人" {...formLayout}>
                    {form.getFieldDecorator('receiver', {
                      initialValue:orderDetails? orderDetails.receiver:null,
                    })(<Input placeholder="请输入" disabled/>)}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="收货联系人电话" {...formLayout}>
                    {form.getFieldDecorator('receiverPhone', {
                      initialValue: orderDetails?orderDetails.receiverPhone:null,
                    })(<Input placeholder="请输入" disabled />)}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="是否非标" {...formLayout}>
                    {form.getFieldDecorator('isTechnology',{
                      initialValue:orderDetails.isTechnology?'是':'否',
                      rules: [
                        {
                          required: isDealer,
                          message: '请选择是否非标！',
                        },
                      ],
                    })(
                      <Select placeholder='请选择' disabled={!isDealer} >
                        <Option value="是">是</Option>
                        <Option value="否">否</Option>
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="行业" {...formLayout}>
                    {form.getFieldDecorator('industry',{
                      initialValue:orderDetails.industry,
                      rules: [
                        {
                          required: isDealer,
                          message: '请选择行业！',
                        },
                      ],
                    })(
                      <Select placeholder='请选择' disabled={!isDealer}>
                        <Option value="BLD">BLD</Option>
                        <Option value="IND">IND</Option>
                        <Option value="UT">UT</Option>
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Col md={8} sm={24}>
                  <FormItem label="付款条件" {...formLayout}>
                    {form.getFieldDecorator('paymentTerm', {
                      initialValue: orderDetails?orderDetails.paymentTerm:null,
                      rules: [
                        {
                          required: isDealer,
                          message: '收货联系人电话不能为空！',
                        },
                      ],
                    })(
                      <Select placeholder="请选择" disabled={!isDealer}>
                        { getOptionList(this.state.paymentTerm) }
                      </Select>
                    )}
                  </FormItem>
                </Col>
                <Authorized authority={this.handleProjectDesignNoPermission} >
                  <Col md={8} sm={24}>
                    <FormItem label="非标核算表项目号" {...formLayout}>
                      {form.getFieldDecorator('projectDesignNo',{
                        initialValue:orderDetails.projectDesignNo?orderDetails.projectDesignNo:'TNP'
                      })(
                        <Input placeholder="请输入" />
                      )}
                    </FormItem>
                  </Col>
                </Authorized>
                <Authorized authority={this.handleEstimatedPermission} >
                  <Col md={8} sm={24}>
                    <FormItem label="预计出厂时间" {...formLayout}>
                      {form.getFieldDecorator('estimatedFactoryTime',{
                        initialValue:orderDetails.estimatedFactoryTime=='0001-01-01T00:00:00'?"":moment(orderDetails.estimatedFactoryTime)
                      })(
                        <DatePicker style={{width:'100%'}}  onChange={this.handleDatePickerChange}/>
                      )}
                    </FormItem>
                  </Col>
                </Authorized>
                <Authorized authority={this.handleLargePermission} >
                  <Col md={8} sm={24}>
                    <FormItem label="价格区间" {...formLayout}>
                      {form.getFieldDecorator('margin',{
                        initialValue:orderDetails.margin?orderDetails.margin:null,
                        rules:[
                          {
                            required:!isBussine,
                            message:'请选择价格区间！'
                          }
                        ]
                      })(
                        <Select disabled={isBussine} onChange={this.handleMaginChange}>
                          { getOptionListKey(priceRange) }
                        </Select>
                      )}
                    </FormItem>
                  </Col>
                </Authorized>
                <Authorized authority={this.handleNonPermission} >
                  <Col md={8} sm={24}>
                    <FormItem label="价格区间" {...formLayout}>
                      {form.getFieldDecorator('margin2',{
                        initialValue:orderDetails.margin2?orderDetails.margin2:null,
                        rules:[
                          {
                            required:!isBussine,
                            message:'请填写价格区间！'
                          }
                        ]
                      })(
                        <Input disabled={isBussine} onChange={this.handleNonMaginChange} />
                      )}
                    </FormItem>
                  </Col>
                </Authorized>
              </Row>
              <Row>
                <Col md={8} sm={24}>
                  <FormItem label="附件上传" {...formLayout}>
                    {form.getFieldDecorator('fileId',{
                      initialValue:orderDetails.fileId
                    })(
                      <FileUpload />
                    )}
                  </FormItem>
                </Col>
              </Row>
            </Form>
          </Panel>
          <Panel header="订货信息" key="12" style={customPanelStyle} className="panel-hook">
            <Table 
              className="components-table-demo-nested"
              columns={this.materialColumns}
              dataSource={this.state.materialData}
              pagination={false}
              expandedRowRender={expandedRowRender}
              onExpand={this.onExpand}
              expandedRowKeys={this.state.expandedRowKeys}
            />
          </Panel>
          <Panel header="审批" key="14" style={customPanelStyle} className="panel-hook">
            <ApprovalContent {...approvalContentProps}  />
            {/* {orderDetails.status == 'Return'? null :
            <CurrentApproval {...currentApprovalProps} wrappedComponentRef={(inst)=>{this.currentApproval = inst;}}/>
            } */}
            <CurrentApproval {...currentApprovalProps} wrappedComponentRef={(inst)=>{this.currentApproval = inst;}}/>
            <Button type='primary' onClick={this.handleBack} style={{marginRight:10,marginTop:10}}>返回</Button>
            {orderDetails.status == 'Return'? null :
              <Fragment>
                <Button type='primary' onClick={this.handleReturnModalVisible} style={{marginRight:10,marginTop:10}}>退回</Button>
                <Button type='primary' onClick={this.handleSubmit}>提交</Button>
              </Fragment>
            }
          </Panel>
          <Panel header="审批节点" key="13" style={customPanelStyle} className="panel-hook">
            <Table 
              columns={this.flowNodeColumns}
              dataSource={this.state.flowNodeData}
              pagination={false}
            />          
          </Panel>
          <Panel header="节点操作日志" key="15" style={customPanelStyle} className="panel-hook">
            <Table 
              columns={this.logColumns}
              dataSource={this.state.logData}
              pagination={false}
            />          
          </Panel>
        </Collapse>
      </Spin>
    )
  }
}

**Comment by chenshuai2144** [comment]
给个 mini demo 吧。这么多代码我们也看不过来
