### ISSUE TITLE
Pie组件金额不显示小数点

### ISSUE THREAD

**Issue by lvzheng0404** [ant-design/ant-design-pro#3893]
antd在使用Pie组件时，金额不显示小数点，实际金额是有两位小数的
![image](https://user-images.githubusercontent.com/35189771/55375264-19299680-553e-11e9-93e5-63b41202d1c5.png)

**Comment by chenshuai2144** [comment]
你是用的pro 组件库还是在自己的项目里面？

**Comment by lvzheng0404** [comment]
pro组建库


来自 魅族 16th Plus

-------- 原始邮件 --------
发件人：陈帅 <notifications@github.com>
时间：2019年4月2日 12:02
收件人：ant-design/ant-design-pro <ant-design-pro@noreply.github.com>
抄送：吕铮 <lvzheng0404@sina.com>,Author <author@noreply.github.com>
主题：Re: [ant-design/ant-design-pro] Pie组件金额不显示小数点 (#3893)

**Comment by chenshuai2144** [comment]
这个就比较麻烦了，推荐放到自己的项目中。
不然只能等待组件修复了

**Comment by lvzheng0404** [comment]
@chenshuai2144 我的是ant design pro 项目，使用的是components/Charts/Pie组件，其实应该不是Pie组件的问题，我看金额用了一个Yuan组件，里面用了components/Charts的yuan方法，问题应该出在这里，这有什么好的解决方案吗？

**Comment by chenshuai2144** [comment]
pie中应该没有使用 yuan，感觉有点奇怪
