### ISSUE TITLE
官方demo登陆页面404并一直重定向

### ISSUE THREAD

**Issue by sunfutao** [ant-design/ant-design-pro#3894]
https://ant-design-pro.netlify.com/user/login
![image](https://user-images.githubusercontent.com/35865208/55375967-d4ebc580-5540-11e9-9e8d-50471ce2bbfc.png)

**Comment by chenshuai2144** [comment]
这个页面很奇怪。
https://preview.pro.ant.design/ 这才是我们的官方域名

**Comment by chenshuai2144** [comment]
感觉是重定向的问题，现在应该不会了

**Comment by yatessss** [comment]
依然存在  一直404 
![image](https://user-images.githubusercontent.com/13636879/60331279-e2d9a700-99c6-11e9-8ba2-36b80e5f164a.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4656 

强刷一把，在控制台中关闭 pwa。
