### ISSUE TITLE
build时 页面model需要引入其他页面的model,不提升为全局model,有其他方法吗？

### ISSUE THREAD

**Issue by sir-ran** [ant-design/ant-design-pro#3896]
我看到UMI.JS  有这么说：
**model 注册**
model 分两类，一是全局 model，二是页面 model。全局 model 存于 /src/models/ 目录，所有页面都可引用；页面 model 不能被其他页面所引用。

规则如下：
src/models/**/*.js 为 global model
src/pages/**/models/**/*.js 为 page model
global model 全量载入，page model 在 production 时按需载入，在 development 时全量载入
page model 为 page js 所在路径下 models/**/*.js 的文件
page model 会向上查找，比如 page js 为 pages/a/b.js，他的 page model 为 pages/a/b/models/**/*.js + pages/a/models/**/*.js，依次类推
约定 model.js 为单文件 model，解决只有一个 model 时不需要建 models 目录的问题，有 model.js 则不去找 models/**/*.js

[https://umijs.org/zh/guide/with-dva.html#%E4%BD%BF%E7%94%A8](url)

请问一下，现在我有个公共的model在pages/X/models/x 下，
其他好几个页面都需要引入这个公共的model。
不提升为全局的model，有其他方法能让其他页面能使用这个公共的model吗？因为我发现上面【page model 在 production 时按需载入】一样，在开发预览时，其他页面都能使用这个公共model，但是build时，就不行了。

**Comment by xiaohuoni** [comment]
dev环境，是全量加载的，build之后才按需加载的。
可以通过关闭按需加载的功能，来达到你的目的。
https://umijs.org/zh/plugin/umi-plugin-react.html#dva

**Comment by sir-ran** [comment]
我关闭了按需加载，但是，打包过后umi.js文件有点大。
我现在只有一个公共的model，还是想按需加载，但是又能解决我现在的问题，
 有没有其他方法呀，我看到有人说 window.g_app.model(your model);手动注册model。这个方法可行吗？

**Comment by xiaohuoni** [comment]
不推荐吧，有公用的移到全局维护，没有其他成本的话，比较推荐这么做
