### ISSUE TITLE
权限问题咨询

### ISSUE THREAD

**Issue by TrumanDu** [ant-design/ant-design-pro#3898]
```
import RenderAuthorized from 'ant-design-pro/lib/Authorized';
RenderAuthorized('admin');
```
```"ant-design-pro": "^2.3.1",```
如上在login登录后，并没有重新渲染页面，还是上次操作账户的菜单，需要强制刷新后，才更改菜单，请问这里应该怎么调用?

我看文档跳转的地址是旧代码逻辑，在util里面reloadAuthorized。原理都一样，前端新手，使用场景是在飞冰中集成权限

**Comment by chenshuai2144** [comment]
menu 现在在 model 里面 ，dispath 一下就好了
model/menu.js

**Comment by TrumanDu** [comment]
在飞冰组件中，没有这个的，这该怎么处理。之前用util方式没问题，换成2.X版本就不工作了。

**Comment by xiaohuoni** [comment]
没跑过飞冰，给个最小demo，我帮你加看看吧

**Comment by TrumanDu** [comment]
@xiaohuoni 好的，明天我写个demo,感谢回复

**Comment by TrumanDu** [comment]
@xiaohuoni @chenshuai2144 感谢二位回复，我重新写个demo，没有问题。之前存在问题是因为将1.0与2.0混用，所以产生问题，感谢二位。
