### ISSUE TITLE
使用了Ellipsis火狐和谷歌会出现不同的层级结构并且展示的内容也是不同的，图一为火狐，图二为谷歌

### ISSUE THREAD

**Issue by lzloglee** [ant-design/ant-design-pro#3899]
![image](https://user-images.githubusercontent.com/34827955/55397830-afc77900-5579-11e9-93e3-dee9159cb7b7.png)
![image](https://user-images.githubusercontent.com/34827955/55397810-a3dbb700-5579-11e9-8163-d5e010dbc63c.png)

**Comment by chenshuai2144** [comment]
google下用 css实现。火狐用的是js。建议使用 antd 的 Ellipsis。pro中的组件将会去掉
https://ant.design/components/typography-cn/#components-typography-demo-ellipsis
