### ISSUE TITLE
在antd pro2.0版本里如何正确添加react-dnd，react-dnd-html5-backend

### ISSUE THREAD

**Issue by wenmine** [ant-design/ant-design-pro#3900]
目前想实现tabs页拖拽功能，但是不知道该将 `HTML5Backend`放置在哪个组件。

` 
<DragDropContextProvider backend={HTML5Backend}></DragDropContextProvider>
`

添加到`basicLayout`上会报 `Cannot have two HTML5 backends at the same time.`

添加到实际上tab所在的页面上:
![image](https://user-images.githubusercontent.com/14882982/55401934-c0c9b780-5584-11e9-9ae0-bfdcedba88db.png)
也会报错。求各位大神帮忙告知如何解决，感激不尽！

**Comment by wenmine** [comment]
看了一下umi的文档，好像可以自己创建src/app.js。然后在里面获取到根元素

**Comment by xiaohuoni** [comment]
```js
import React from "react";
import HTML5Backend from "react-dnd-html5-backend";
import { DragDropContext } from "react-dnd";
const DropContext = ({ children }) => {
  return <div>{children}</div>;
};

export default DragDropContext(HTML5Backend)(DropContext);
```

**Comment by xiaohuoni** [comment]
```js
export default {
  plugins: [
    ['umi-plugin-dnd'],
  ],
}
```

**Comment by wenmine** [comment]
@xiaohuoni  抱歉抱歉，昨天一直在忙其他事情，没来得及试。今天试了，不知道是不是我操作不对，报错了：
![image](https://user-images.githubusercontent.com/14882982/55526252-e5c64380-56c6-11e9-83d0-807e69ed568d.png)


我是在config/config里引用的，引用方式是：

> ` plugins: [['umi-plugin-dnd']];
`

然后我的页面是用 [(https://ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar-node]这里的代码，就是去掉了

> `<DragDropContextProvider backend={HTML5Backend}></DragDropContextProvider>`

这层。

**Comment by xiaohuoni** [comment]
我晚上看下，现在✈️上

**Comment by xiaohuoni** [comment]
看起来应该是发包的时候文件没上传

**Comment by wenmine** [comment]
@xiaohuoni 恩恩没关系，你先忙你的~我用第一个方法解决啦。就是下面的那个方法，之前是我写的有问题。谢谢大神帮忙！！！等回头你有空了把包重新上传我再试试。

`import React from "react";
import HTML5Backend from "react-dnd-html5-backend";
import { DragDropContext } from "react-dnd";
const DropContext = ({ children }) => {
  return <div>{children}</div>;
};

export default DragDropContext(HTML5Backend)(DropContext);`
