### ISSUE TITLE
Tree shaking of chart components

### ISSUE THREAD

**Issue by rhap5ody** [ant-design/ant-design-pro#3902]
![Screenshot from 2019-04-03 05-48-42](https://user-images.githubusercontent.com/6686226/55451669-34df7c00-55d4-11e9-8f79-25d063cf0e2b.png)

I am using a couple of Ant design pro charts alongside Ant Design, but this is the output from the analysis of my bundle. Bizcharts is imported as a whole by Ant design pro even though I am using only one/two charts. I see that it's an UMD build, but I searched for ES build but there isn't one. I am using the components like this:

```
import {Bar} from "ant-design-pro";

// webpack.config.js
plugins: [
            ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true}, 'ant'],
            ['import',  {libraryName: 'ant-design-pro', libraryDirectory: 'lib', style: true,camel2DashComponentName: false}, 'pro'],
          ]
```
Is there any possibility to use only some of the charts? The whole Bizcharts library takes 1.51MB which is a lot.

**Comment by chenshuai2144** [comment]
bizchart use g2，g2 is large。
There is no good way for the time being. very sorry
