### ISSUE TITLE
加了pageheader后在Breadcrumb有keys重复问题

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#3904]
加了pageheader后在Breadcrumb有keys重复问题

**Comment by liangfeng998** [comment]
index.js:1 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by Context.Consumer)
    in Breadcrumb (created by Context.Consumer)
    in div (created by Context.Consumer)
    in PageHeader (created by Context.Consumer)
    in div (created by PageHeaderWrapper)
    in PageHeaderWrapper (created by Connect(PageHeaderWrapper))
    in Connect(PageHeaderWrapper) (created by TableList)
    in TableList (created by Form(TableList))
    in Form(TableList) (created by Connect(Form(TableList)))
    in Connect(Form(TableList)) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Route)
    in Switch (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Component)
    in Switch (created by Component)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Media)
    in Media
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by DynamicComponent)
    in DynamicComponent (created by Component)
    in Component (created by Component)
    in Authorized (created by AuthComponent)
    in AuthComponent (created by Connect(AuthComponent))
    in Connect(AuthComponent) (created by Component)
    in Component (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by ret)
    in ret (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by DvaContainer)
    in DvaContainer

**Comment by xiaohuoni** [comment]
+1

**Comment by TnWah** [comment]
+1    一开始还以为我删减出问题了，最后重新clone一份测试依然存在

**Comment by chenshuai2144** [comment]
Breadcrumb 竟然用BreadcrumbName当 key。我的BreadcrumbName 是个 object。蛋疼

**Comment by gregoryforel** [comment]
Hello @afc163 - Currently, when using `Breadcrumb` with a `route` prop, if we have 2 `breadcrumb` with the same `breadcrumbName`, it fails with the error message `Encountered two children with the same key`.

As @chenshuai2144 mentioned, `breadcrumbName` is used as the key. Is there an option to pass a different key?
