### ISSUE TITLE
不跳转登录

### ISSUE THREAD

**Issue by singlesuisui** [ant-design/ant-design-pro#3906]

**Comment by singlesuisui** [comment]
新试用V2,发现访问页面时，没有登录状态也不会跳转登录

**Comment by LukerSpringtree** [comment]
@singlesuisui 你可以自己补上 相应的逻辑, 因为每个项目判断是否登录的方法不一样.
你可以加上适合你项目的  跳转代码

**Comment by chenshuai2144** [comment]
我们主要是 demo，在这个修改 4cc44151 中，专门做成了不用登陆就可以使用
