### ISSUE TITLE
直接运行没有问题，但是打包后部署到本地nginx，提示：TypeError: Object(o["a"]) is not a function. (In 'Object(o["a"])()', 'Object(o["a"])' is an instance of Object)

### ISSUE THREAD

**Issue by zhaolixiang** [ant-design/ant-design-pro#3909]
页面显示空白，日志打印：
![image](https://user-images.githubusercontent.com/16216595/55466357-997cf400-5631-11e9-868b-cacab59a34ac.png)

**Comment by chenshuai2144** [comment]
试着用 匿名模式浏览一下

**Comment by zhaolixiang** [comment]
> 试着用 匿名模式浏览一下

您好，匿名模式浏览指的是什么。。。

**Comment by zhaolixiang** [comment]
> 试着用 匿名模式浏览一下

如何您说的匿名模式浏览是指浏览器的匿名浏览，我试了还是不行。。。

**Comment by chenshuai2144** [comment]
试着打包带sourcemap的包出来看看原因。看起来像是访问了一个没定义方法
