### ISSUE TITLE
Cannot read property 'breadcrumbList' of undefined in file breadcrumb.js

### ISSUE THREAD

**Issue by shlyren** [ant-design/ant-design-pro#3910]
文件**src/components/PageHeaderWrapper/breadcrumb.js**第96行代码`return conversionFromProps();`需要传入参数**props**

**Comment by shlyren** [comment]
此页面有一个bug, `conversionFromProps`方法应返回map类型, 否则自定义面包屑无效

**Comment by chenshuai2144** [comment]
我修一下，光顾着给 v4 修了
