### ISSUE TITLE
相同代码，相同的操作，windows下正常，但ubuntu下就会出错，错误“TypeError: Cannot read property 'deptData' of undefined”

### ISSUE THREAD

**Issue by XNTongXue** [ant-design/ant-design-pro#3917]
报错没有发现'deptData'属性，
错误如下：
TypeError: Cannot read property 'deptData' of undefined
DataAuthModal.render
src/pages/Data/Public/DataAuthModal.js:177
  174 | }
  175 | 
  176 | 
> 177 | render() {
         | ^  178 |   const {Sider,Content}=Layout;
  179 |   const { menus : { deptData }} = this.props;
  180 |   const {dataSource}=this.state;

**Comment by chenshuai2144** [comment]
const { menus : { deptData }} = this.props; 加一个if判断一下。看看menus是什么
