### ISSUE TITLE
ERROR in ./mock/matchMock.js

### ISSUE THREAD

**Issue by wangningbo93** [ant-design/ant-design-pro#3919]
ERROR in ./mock/matchMock.js
Module not found: Error: Can't resolve './api' in 'E:\workspace\react-sy @ ./mock/matchMock.js 5:17-33
 @ ./api.js``

**Comment by wangningbo93** [comment]
npm run build

**Comment by zhangshuai0101** [comment]
提示找不到这个文件 你看下工程里有没有这个文件
