### ISSUE TITLE
请问Tree组件有什么办法可以让checkedKeys在节点全部渲染完后再进行选中？

### ISSUE THREAD

**Issue by zwdgit** [ant-design/ant-design-pro#3920]
目前遇到的问题，checkedKeys 属性中的值是常量数组，而子节点是通过递归方法生成的，我目前的写法会造成很多警告，请问有什么解决方法？

![WX20190404-151706](https://user-images.githubusercontent.com/28926324/55536912-91828a00-56ed-11e9-9d21-73db123bf733.png)

![WX20190404-151757](https://user-images.githubusercontent.com/28926324/55536913-921b2080-56ed-11e9-998f-dbc3f16f66e8.png)

**Comment by chenshuai2144** [comment]
你的递归是异步的吗？

**Comment by zwdgit** [comment]
> 你的递归是异步的吗？

递归的数据和选中的节点是同时异步获取到的

**Comment by chenshuai2144** [comment]
有个简单的办法， 数据获取完成之后再去渲染树，先展示一个 loading
