### ISSUE TITLE
请教个build问题

### ISSUE THREAD

**Issue by zhangshuai0101** [ant-design/ant-design-pro#3922]
发现最近的打包方式和之前有所改变，增加了离线，但是想知道现在打包方式是怎么按文件名打包出对应文件 
![image](https://user-images.githubusercontent.com/40013310/55542819-75391a00-56fa-11e9-8263-e763375d9e77.png)
之前的是这样的
![image](https://user-images.githubusercontent.com/40013310/55542890-900b8e80-56fa-11e9-9ff4-7e74dc9715b6.png)

@chenshuai2144  shuai帅哥能告知下吗

**Comment by chenshuai2144** [comment]
umi暂时不支持这个功能的。
为什么要分文件夹？

**Comment by zhangshuai0101** [comment]
> umi暂时不支持这个功能的。
> 为什么要分文件夹？

帅哥 这个是我们自己去实现的吗？我现在的项目是通过三个分工程合到主工程里，所以后续需要这方面的支持

**Comment by chenshuai2144** [comment]
有个 publicpath 和 base。这两个配和能实现你的需求。
https://umijs.org/zh/config/#outputpath

**Comment by zhangshuai0101** [comment]
> 有个 publicpath 和 base。这两个配和能实现你的需求。
> https://umijs.org/zh/config/#outputpath
> 
> > **[配置 | UmiJS](https://umijs.org/zh/config/#outputpath)**🌋 可插拔的企业级 react 应用框架。

帅哥 还有就是怎么打包出的文件是自己定义的文件名字，而不是数字这样排序 谢谢了

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport
用这个配置
