### ISSUE TITLE
url直接输入一级目录会显现路由路径

### ISSUE THREAD

**Issue by longearshortail** [ant-design/ant-design-pro#3925]
比如直接输入
http://localhost:8000/dashboard
会显示如下图，把路由路径直接显现出来了。

![image](https://user-images.githubusercontent.com/32356094/55663466-d246e400-5850-11e9-9060-cbbf707c1876.png)

**Comment by chenshuai2144** [comment]
这是404界面，为了方便你进行调试，只有在dev中会这样显示，编译完之后会直接显示你设置的404
