### ISSUE TITLE
IE下双滚动条问题

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design-pro#393]
BasicLayout.less :
`:global {
  .ant-layout {
    overflow-x: hidden;
  }
}
`
需要改成overflow: hidden;
![image](https://user-images.githubusercontent.com/6057326/33757485-54dfd67c-dc35-11e7-9b7c-5b7f6c162fac.png)

**Comment by chenshuai2144** [comment]
edge 也是  #387
