### ISSUE TITLE
PageHeaderWrapper 面包屑自定义分隔符属性(breadcrumbSeparator)无效

### ISSUE THREAD

**Issue by shlyren** [ant-design/ant-design-pro#3935]
如果我没记错的话，`PageHeaderWrapper`在使用**antd**的组件`PageHeader`之前是可以通过`breadcrumbSeparator`自定义分隔符的。

**Comment by chenshuai2144** [comment]
可以在 pageHeader  的 breadcrumb 中配置 separator

**Comment by chenshuai2144** [comment]
https://ant.design/components/breadcrumb-cn/#API

**Comment by shlyren** [comment]
我想起来了， 当时是我自己加的
