### ISSUE TITLE
主题设置固定Header时，Header部分会遮挡住form表单的校验范围

### ISSUE THREAD

**Issue by yihai8721** [ant-design/ant-design-pro#3936]
![image](https://user-images.githubusercontent.com/11973605/55705217-e20d2680-5a10-11e9-9e1c-5be0e5a67c4d.png)

**Comment by chenshuai2144** [comment]
你有好的方案吗？

**Comment by yihai8721** [comment]
配置文件defaultSettings增加一个向上偏移的属性offsetValue，fixedHeader固定时候取值65否则取值为0；
校验时候设置偏移量：
import { offsetValue } from '../../defaultSettings';
validateFieldsAndScroll({ scroll: {offsetTop: offsetValue } }

**Comment by yihai8721** [comment]
> 你有好的方案吗？

你觉得可行么？

**Comment by chenshuai2144** [comment]
应该是 fixedHeader 时直接设置，不需要进行配置
