### ISSUE TITLE
PageHeaderWrapper组件顶部面包屑模块无效

### ISSUE THREAD

**Issue by TnWah** [ant-design/ant-design-pro#3937]
最新版的Pro，start后打开效果与官网不一致，
![image](https://user-images.githubusercontent.com/27721311/55707149-81341d00-5a15-11e9-89cf-50b150a9a4f0.png)
![image](https://user-images.githubusercontent.com/27721311/55707165-8abd8500-5a15-11e9-818d-5961f2840534.png)

**Comment by TnWah** [comment]
这里是特意更改的title && content   判断么？
![image](https://user-images.githubusercontent.com/27721311/55707384-0fa89e80-5a16-11e9-8305-ed370576479a.png)

**Comment by chenshuai2144** [comment]
没有 title 直接就不显示了是故意的

**Comment by chenshuai2144** [comment]
这个有点问题，只判断 title 就好了，有兴趣修一下吗？

**Comment by TnWah** [comment]
提交pull requests修复这个么？

**Comment by chenshuai2144** [comment]
是的

**Comment by TnWah** [comment]
我这边试试做个提交，第一次参与这种工作。。
