### ISSUE TITLE
菜单栏目如何加入动态id

### ISSUE THREAD

**Issue by liutao** [ant-design/ant-design-pro#3941]
比如我们项目分10个板块。每个板块相当于一个子项目，然后每个子项目进去之后，左侧是一个菜单，10个板块菜单栏都一样，不一样的地方就是需要传递的板块ID不一样。
如果不能动态传id，那岂不是要开10个重复的项目。
类似于这个https://github.com/ant-design/ant-design-pro/issues/3839，这种需求肯定有啊

**Comment by chenshuai2144** [comment]
在 geMenuData 中拼接一个。菜单的路径应该是固定的。
