### ISSUE TITLE
想吐槽现在的依赖

### ISSUE THREAD

**Issue by tsj11** [ant-design/ant-design-pro#3942]
有没有同志觉得现在的项目依赖安装起来好麻烦，经常出错，有时候莫名其妙出错，每次install的时候都要下载一遍Chromium r641577，142M，至少要5分钟……往往还会因为各种问题安装不成功，即便用cnpm也不能解决所有问题……到底是我自己的问题（网络、设置等），还是项目只能做成这样，有没有可能解决一下这个令人心累的依赖问题？

**Comment by chenshuai2144** [comment]
为了e2e测试，你删除 puppetter 就好了。
cnpm 速度很快的。
