### ISSUE TITLE
你的预览网址出现了错误，一直打不开

### ISSUE THREAD

**Issue by LiShaoLong123** [ant-design/ant-design-pro#3944]
![微信图片_20190409102805](https://user-images.githubusercontent.com/30816758/55769135-3ae0cb80-5ab2-11e9-81ab-b22405b16195.png)

**Comment by xiaohuoni** [comment]
https://preview.pro.ant.design/dashboard/analysis
我的可以，你是什么浏览器？

**Comment by LiShaoLong123** [comment]
谷歌浏览器

**Comment by xiaohuoni** [comment]
@chenshuai2144 我的也是谷歌，我这不会。你试试

**Comment by LiShaoLong123** [comment]
好的，我试一下

**Comment by yihai8721** [comment]
我的也是一样

**Comment by chenshuai2144** [comment]
使用  隐身模式试一下呢

**Comment by superchow** [comment]
> 使用 隐身模式试一下呢

什么原理？

**Comment by chenshuai2144** [comment]
可能是localStorage 造成的问题
