### ISSUE TITLE
2.3.1Request

### ISSUE THREAD

**Issue by Free-Qi** [ant-design/ant-design-pro#3948]
pro升级到2.3.1之后使用了umi-request，再request.js文件中不能统一配置请求头了么？我把登录之后的token存在了localStorage里，当我再次发其他业务请求，我是在request.js里取localStorage然后后放入请求头中，却一直取得是上次登录的token，之前pro用fetch时候一直都是这个逻辑去发送请求，现在换成umi-request后这个方法不好用了。我现在只能把每个请求的请求头每一个都写在services那一层里。。。每一个都写，感觉很麻烦啊，请问有什么好的意见么？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-request
```
// response interceptor, handling response
request.interceptors.response.use((response, options) => {
  response.headers.append('interceptors', 'yes yo');
  return response;
});
```
