### ISSUE TITLE
Move "react" & "react-dom" to peerDependency

### ISSUE THREAD

**Issue by johntran** [ant-design/ant-design-pro#3950]
Hello,

I'm unable to use React hooks because there are multiple copies of React when using `ant-design-pro`. Moving "react" and "react-dom" to peerDependencies will fix this.

See following for informaiton
- https://github.com/facebook/react/issues/8026#issuecomment-255363991

This is done in ant-design already
- https://github.com/ant-design/ant-design/blob/master/package.json#L40

Thank you!

**Comment by chenshuai2144** [comment]
Ant-design-pro will not release the version again. If you need to use it, it's best to clone it into your own project.
