### ISSUE TITLE
关于面包屑的位置

### ISSUE THREAD

**Issue by xiaminxi** [ant-design/ant-design-pro#3952]
![image](https://user-images.githubusercontent.com/37994820/55792507-60da9000-5af3-11e9-844a-d95d92b07c08.png)
 能不能让我们自己来决定面包屑的位置， 还是说本身可以放到Header里面，而我不知道怎么用

**Comment by chenshuai2144** [comment]
代码就在你的手中。
我不推荐这种用法。 header 不应该承载这么复杂的东西。面包屑的本意是为了在多个页面之间跳转

**Comment by li305263** [comment]
> 代码就在你的手中。
> 我不推荐这种用法。 header 不应该承载这么复杂的东西。面包屑的本意是为了在多个页面之间跳转

能说一下怎么改吗..
