### ISSUE TITLE
面包屑抛异常

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#3955]
src/components/PageHeaderWrapper/index.js
```
breadcrumb={conversionBreadcrumbList({
                  ...value,
                  ...restProps,
                  home: <FormattedMessage id="menu.home" defaultMessage="Home" />,
                })}
```
这里设置面包屑时，breadcrumbNameMap是有可能为空的（比如menu data为异步），这种情况通过返回的面包屑routes中会出现null，但是Breadcrumb组件中routes中出现null 会抛异常
./node_modules/antd/es/breadcrumb/Breadcrumb.js
crumbs = routes.map(function (route) {
          route.path = route.path || '';

**Comment by chenshuai2144** [comment]
breadcrumbNameMap 默认设置为 {}

**Comment by shlyren** [comment]
此问题刚刚我也遇到了， 我是出现在通过location转化为面包屑的问题， 如果`breadcrumbNameMap`存在`hideChildrenInMenu `为true时，`conversionFromLocation()`方法内的`pathSnippets.map()`返回的是null，但最终`extraBreadcrumbItems`未对这个null做处理

**Comment by chenshuai2144** [comment]
https://github.com/zhang0ZGC/ant-design-pro/commit/566a32e29c4d0d4088f974d08d233f50e56c3f96
