### ISSUE TITLE
工程直接复制到没有联网的电脑上，报cross-env 不是内部或者外部命令

### ISSUE THREAD

**Issue by caogaofeng0** [ant-design/ant-design-pro#3957]
因业务需要，需要在没有联网电脑上开发。前期我是在有网的电脑开发的用的苹果的电脑。联调就把工程直接拷贝的没有联网的window上。node 已经安装好了。但是 npm run start ,包 cross-env 不是内部或外部命令，也不是可运行的程序或批处理文件。 试了其他的 比如 npm run test , 报 umi 不是内部或外部命令。 请指导

**Comment by hst-Sunday** [comment]
npm i 装好该装的东西  然后在运行

**Comment by chenshuai2144** [comment]
npm i 是必须的。你可以把整个node-modlue 拷贝过去
