### ISSUE TITLE
pro要停止迭代了？

### ISSUE THREAD

**Issue by Tan90Qian** [ant-design/ant-design-pro#3958]
```
2.3.0 将会是 pro 的最后的一个版本，主要用于修正 ts 错误，此后将不接受 master 的功能添加。
```

目前pro的更新日志里对2.3的描述是最后一个版本，而仓库中不管是release还是tag都没有2.3这一版本，但package.json中版本号显示为2.3.1

请问：pro目前的状态是什么？接下来还继续维护迭代么？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/3143
https://github.com/ant-design/ant-design-pro/issues/3789
