### ISSUE TITLE
查询表格  按条件过滤查询完，点击重置，然后再翻页，会按之前的查询条件过滤

### ISSUE THREAD

**Issue by bingfengblog** [ant-design/ant-design-pro#396]
![image](https://user-images.githubusercontent.com/20056436/33777782-1cb09d08-dc81-11e7-8b28-b40300341644.png)
![image](https://user-images.githubusercontent.com/20056436/33777798-2801427a-dc81-11e7-98e3-3d4f4d1524fa.png)
翻页
![image](https://user-images.githubusercontent.com/20056436/33777812-362095a4-dc81-11e7-8d6e-18d99c51c5cf.png)
![image](https://user-images.githubusercontent.com/20056436/33777838-4624ccf4-dc81-11e7-98f3-38844887d1f8.png)

**Comment by chenshuai2144** [comment]
已经重现,有这样的问题.
