### ISSUE TITLE
const request = extend({..., headers: {'Authorization': `Bearer ${localStorage.getItem('token')}`}}出现无法取到token问题

### ISSUE THREAD

**Issue by dreamLxy** [ant-design/ant-design-pro#3962]
登录成功时，向localStorage中设置token，此时会重定向到dashboard界面，然后这个界面我设置的请求api是需要带上token的，我直接在最底层'@/utils/request'中设置了向localStorage中取token。 实际情况是无法在登录成功时第一次重定向dashboard时生效，dashboard中无法携带上token。 然后，因为localStorage已经成功设置了token，所以我手动输入http://localhost:8000/dashboard，进入该页面却又可以正常获取到token。求助求助~
\src\models\login.js：
```
effects: {
    *login({ payload }, { call, put }) {
      const response = yield call(fakeAccountLogin, payload);
      yield put({
        type: 'changeLoginStatus',
        payload: response,
      });
      // Login successfully
      if (response.errcode === 0) {
        **localStorage.setItem('token', response.data.token)** // 这里设置token
        reloadAuthorized();
        const urlParams = new URL(window.location.href);
        const params = getPageQuery();
        let { redirect } = params;
        if (redirect) {
          const redirectUrlParams = new URL(redirect);
          if (redirectUrlParams.origin === urlParams.origin) {
            redirect = redirect.substr(urlParams.origin.length);
            if (redirect.match(/^\/.*#/)) {
              redirect = redirect.substr(redirect.indexOf('#') + 1);
            }
          } else {
            redirect = null;
          }
        }
        yield put(routerRedux.replace(redirect || '/'));
      }
    },
```

/utils/request：
```
/**
 * 配置request请求时的默认参数
 */
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  headers: {
    'Authorization': `Bearer ${localStorage.getItem('token')}`
  }
});

```

**Comment by chenshuai2144** [comment]
extend 只会执行一次。你应该使用use

**Comment by dreamLxy** [comment]
我在/utils/request最后加了请求拦截器，可以正常使用了
```
request.interceptors.request.use((url, options) => {
  options.headers = {
    ...options.headers,
    'Authorization': `Bearer ${localStorage.getItem('token')}`
  }
  return (
    {
      url: `${url}&interceptors=yes`,
      options: {
        ...options,
        interceptors: true,
      },
    }
  );
});
```

**Comment by hedy0111** [comment]
> 我在/utils/request最后加了请求拦截器，可以正常使用了
> 
> ```
> request.interceptors.request.use((url, options) => {
>   options.headers = {
>     ...options.headers,
>     'Authorization': `Bearer ${localStorage.getItem('token')}`
>   }
>   return (
>     {
>       url: `${url}&interceptors=yes`,
>       options: {
>         ...options,
>         interceptors: true,
>       },
>     }
>   );
> });
> ```

能把完整的request代码发出来看一下吗

**Comment by dreamLxy** [comment]
/src/utils/request.js
```
/**
 * request 网络请求工具
 * 更详细的api文档: https://bigfish.alipay.com/doc/api#request
 */
import { extend } from 'umi-request';
import { notification } from 'antd';
import router from 'umi/router';

const codeMessage = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
};

/**
 * 异常处理程序
 */
const errorHandler = error => {
  const { response = {} } = error;
  const errortext = codeMessage[response.status] || response.statusText;
  const { status, url } = response;

  if (status === 401) {
    notification.error({
      message: '未登录或登录已过期，请重新登录。',
    });
    // @HACK
    /* eslint-disable no-underscore-dangle */
    window.g_app._store.dispatch({
      type: 'login/logout',
    });
    router.push('/user/login')
    return;
  }
  notification.error({
    message: `请求错误 ${status}: ${url}`,
    description: errortext,
  });
  // environment should not be used
  if (status === 403) {
    router.push('/exception/403');
    return;
  }
  if (status <= 504 && status >= 500) {
    router.push('/exception/500');
    return;
  }
  if (status >= 404 && status < 422) {
    router.push('/exception/404');
  }
};

/**
 * 配置request请求时的默认参数
 */
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
});

request.interceptors.request.use((url, options) => {
  options.headers = {
    ...options.headers,
    'Authorization': `Bearer ${localStorage.getItem('token')}`
  }
  return (
    {
      url: `${url}&interceptors=yes`,
      options: {
        ...options,
        interceptors: true,
      },
    }
  );
});

export default request;
```

**Comment by fanhualei** [comment]
为什么要添加：&interceptors=yes interceptors: true。 不加会出错吗？

return (
    {
      url: `${url}&interceptors=yes`,
      options: {
        ...options,
        interceptors: true,
      },
    }
  );

**Comment by xiaoshui222** [comment]
> /src/utils/request.js
> 
> ```
> /**
>  * request 网络请求工具
>  * 更详细的api文档�: https://bigfish.alipay.com/doc/api#request
>  */
> import { extend } from 'umi-request';
> import { notification } from 'antd';
> import router from 'umi/router';
> 
> const codeMessage = {
>   200: '服务器成功返回请求的数据。',
>   201: '新建或修改数据成功。',
>   202: '一个请求已经进入后台排队（异步任务）。',
>   204: '删除数据成功。',
>   400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
>   401: '用户没有权限（令牌、用户名、密码错误）。',
>   403: '用户得到授权，但是访问是被禁止的。',
>   404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
>   406: '请求的格式不可得。',
>   410: '请求的资源被永久删除，且不会再得到的。',
>   422: '当创建一个对象时，发生一个验证错误。',
>   500: '服务器发生错误，请检查服务器。',
>   502: '网关错误。',
>   503: '服务不可用，服务器暂时过载或维护。',
>   504: '网关超时。',
> };
> 
> /**
>  * 异常处理程序
>  */
> const errorHandler = error => {
>   const { response = {} } = error;
>   const errortext = codeMessage[response.status] || response.statusText;
>   const { status, url } = response;
> 
>   if (status === 401) {
>     notification.error({
>       message: '未登录或登录已过期，请重新登录。',
>     });
>     // @HACK
>     /* eslint-disable no-underscore-dangle */
>     window.g_app._store.dispatch({
>       type: 'login/logout',
>     });
>     router.push('/user/login')
>     return;
>   }
>   notification.error({
>     message: `请求错误 ${status}: ${url}`,
>     description: errortext,
>   });
>   // environment should not be used
>   if (status === 403) {
>     router.push('/exception/403');
>     return;
>   }
>   if (status <= 504 && status >= 500) {
>     router.push('/exception/500');
>     return;
>   }
>   if (status >= 404 && status < 422) {
>     router.push('/exception/404');
>   }
> };
> 
> /**
>  * 配置request请求时的默认参数
>  */
> const request = extend({
>   errorHandler, // 默认错误处理
>   credentials: 'include', // 默认请求是否带上cookie
> });
> 
> request.interceptors.request.use((url, options) => {
>   options.headers = {
>     ...options.headers,
>     'Authorization': `Bearer ${localStorage.getItem('token')}`
>   }
>   return (
>     {
>       url: `${url}&interceptors=yes`,
>       options: {
>         ...options,
>         interceptors: true,
>       },
>     }
>   );
> });
> 
> export default request;
> ```

可是为什么要加&interceptors=yes interceptors: true这个

**Comment by xyzabc0004** [comment]
谢谢，谢谢，学习了。

**Comment by waylon-edmodo** [comment]
options.headers = {

这种lint检查会报错呀。关掉检查吗
