### ISSUE TITLE
less编译出错

### ISSUE THREAD

**Issue by KejieLiu** [ant-design/ant-design-pro#3963]
写了一段
      .common{
        display: flex;
        justify-content: center;
        align-items: center;
        width: 15%;
        margin: 0 3px;
      }
      .month {
        color: #FFF;
        background-color: #999;
        .common;
      }
但是编译出错
Error { [Error: .common is undefined]
  message: '.common is undefined',
  stack: undefined,
  type: 'Name',
  filename: 'input',
  index: 118377,
  line: 5348,
  column: 8,
  callLine: NaN,
  callExtract: undefined,
  extract:
   [ '        background-color: #999;',
     '        .common;',
     '      }' ] }

我把plugin.config.js中的
config.plugin('ant-design-theme')....
这个插件删掉，就可以了。不知道是为什么，求问。还有就是这个插件配置导致修改less的热更新异常的慢。

**Comment by chenshuai2144** [comment]
ant-design-theme这个插件写的并不好，你可以删掉他，他是一个换主题的功能

**Comment by KejieLiu** [comment]
> ant-design-theme这个插件写的并不好，你可以删掉他，他是一个换主题的功能

ok，我仔细差了以前的issue，发现less那个要加括号，不是很清楚怎么和less官方有点不一样。

**Comment by chenshuai2144** [comment]
这个是css-moudle

**Comment by chjiyun** [comment]
怎么关闭在线主题切换功能啊，找不到开关在哪。怎么会有这么反人类的设计呢，less 里面引用其他less  就报错，官方都不测下的吗，靠！

**Comment by KejieLiu** [comment]
> 怎么关闭在线主题切换功能啊，找不到开关在哪。怎么会有这么反人类的设计呢，less 里面引用其他less 就报错，官方都不测下的吗，靠！

在plugin.config.js里面注释，这个注释掉的话less里 应该可以正常引用。类复用 建议加()
