### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/ant-design-pro#3964]
1. 步骤:
npm install
npm run build
2. 命令行显示如下:
![微信图片_20190411114916](https://user-images.githubusercontent.com/18478530/55929672-4bc74380-5c50-11e9-941c-f910dfb8a12b.png)
可以回复下我吗？谢谢。

**Comment by chenshuai2144** [comment]
是我的错。我写的脚本不支持 win

**Comment by hst-Sunday** [comment]
@chenshuai2144 现在怎么解决呢？ 直接umi build可以吗？

**Comment by layaCoder** [comment]
遇到同样问题，麻烦请问解决方法~

**Comment by lucoxlee** [comment]
you can use mac,-_-

**Comment by hst-Sunday** [comment]
@incoxlee 
Oh no. I can't. I don't have enough money to buy MAC, although I like it very much.

**Comment by supperchong** [comment]
问题在merge-umi-mock-data包里面的index.js
```js
const importMockFiles = (mockFiles, mockPath) => {
  const importString = [];
  const dataString = [];
  mockFiles.forEach(filePath => {
    const fileName = filePath.replace(".js", "");
    importString.push(
      `import ${fileName} from "${path.join(mockPath, filePath)}";`
    );
    dataString.push(`...${fileName}`);
  });
  return `
${importString.join("\n")}

const data = {${dataString.join(",")}};

export default data;
`;
};
```
其中
```js
importString.push(
      `import ${fileName} from "${path.join(mockPath, filePath)}";`
    );
```
改为
```js
importString.push(
      `import ${fileName} from "${path.join(mockPath, filePath).replace(/\\/g,'\\\\')}";`
    );
```

**Comment by hst-Sunday** [comment]
@supperchong 
![微信截图_20190412140946](https://user-images.githubusercontent.com/18478530/56015764-b5b51b00-5d2c-11e9-8d34-495d8c535701.png)
好像是可以了，不过还有个警告，我有强迫症，哈哈哈。

**Comment by chenshuai2144** [comment]
@supperchong  帮忙 pr 一个？

**Comment by supperchong** [comment]
@chenshuai2144 好的，提了个[pr](https://github.com/chenshuai2144/merge-umi-mock-data/pull/3)

**Comment by lucoxlee** [comment]
> 问题在[merge-umi-mock-data](https://github.com/chenshuai2144/merge-umi-mock-data/blob/master/index.js#L49)包里面的index.js
> 
> ```js
> const importMockFiles = (mockFiles, mockPath) => {
>   const importString = [];
>   const dataString = [];
>   mockFiles.forEach(filePath => {
>     const fileName = filePath.replace(".js", "");
>     importString.push(
>       `import ${fileName} from "${path.join(mockPath, filePath)}";`
>     );
>     dataString.push(`...${fileName}`);
>   });
>   return `
> ${importString.join("\n")}
> 
> const data = {${dataString.join(",")}};
> 
> export default data;
> `;
> };
> ```
> 
> 其中
> 
> ```js
> importString.push(
>       `import ${fileName} from "${path.join(mockPath, filePath)}";`
>     );
> ```
> 
> 改为
> 
> ```js
> importString.push(
>       `import ${fileName} from "${path.join(mockPath, filePath).replace(/\\/g,'\\\\')}";`
>     );
> ```

wow,pretty cool

**Comment by chenshuai2144** [comment]
@supperchong 感谢你的贡献
@hst-Sunday  重新安装包即可支持 windows

**Comment by hst-Sunday** [comment]
@supperchong @chenshuai2144 感谢两位大佬!!!
