### ISSUE TITLE
BUG 列表页 查询表格页面，如果内容太长，后面的操作根本看不到

### ISSUE THREAD

**Issue by TLOVET** [ant-design/ant-design-pro#3967]
![image](https://user-images.githubusercontent.com/3888718/55942263-9f4c8800-5c76-11e9-8bfc-8ec4a46c1740.png)
![image](https://user-images.githubusercontent.com/3888718/55942282-aa071d00-5c76-11e9-9a75-fe8a2e9ab079.png)
两个demo的对比，手机端的适配也不太友好，大家有什么好的解决方案

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by VanXueHan** [comment]
建议参考elementUI Table的show-overflow-tooltip
就是Table里显示带省略号的简短内容  hover的时候显示完整内容

**Comment by kuhami** [comment]
我在ant Table组件做了修改可以解决一些问题，希望能帮到你 https://github.com/kuhami/AntTableFinder
![](https://raw.githubusercontent.com/kuhami/AntTableFinder/master/image/antTable.jpeg)
