### ISSUE TITLE
RTL Suport

### ISSUE THREAD

**Issue by hakhsin** [ant-design/ant-design-pro#3969]
Hi, is this template compatible with RTL language?

**Comment by xiaohuoni** [comment]
what is 'RTL'?

**Comment by hakhsin** [comment]
Hi, it is a direction of writing system. [wikipedia](https://en.wikipedia.org/wiki/Right-to-left)

**Comment by hakhsin** [comment]
> 
> 
> what is 'RTL'?

Hi, it is a direction of writing system. wikipedia

**Comment by hakhsin** [comment]
Hello @xiaohuoni!
It is a direction of writing system. wikipedia

**Comment by kiaxseventh** [comment]
is this template support RTL language? for example slide menu show and open on right of screen side ?

**Comment by imhele** [comment]
@xiaohuoni Maybe we can try to make it configurable at the next version antd-pro@4?

**Comment by ayox** [comment]
Any update on this issue ?

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
