### ISSUE TITLE
性能问题，很卡

### ISSUE THREAD

**Issue by jwang0512** [ant-design/ant-design-pro#397]
就我一个有这感觉吗？
macbook pro，i5处理器，16G内存，safari和chrome下访问官方的预览页面 
 https://preview.pro.ant.design/。
操作左侧的菜单展开就有点卡了，动画不流畅。
点击菜单项更卡，快速切换菜单会卡死几秒。用chrome的performance查看性能很差。
这真能商用？

**Comment by chenshuai2144** [comment]
菜单的确很卡。需要优化。。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/33792679-5066646a-dce1-11e7-8f48-7fdfac45a3a7.png)


性能瓶颈主要出现在 图表的渲染部分

**Comment by nikogu** [comment]
> 主要是因为g2图表的问题

这个底层升级成 BizCharts 以后就会有所改善，他们应该做了优化

**Comment by chenshuai2144** [comment]
@nikogu   我最近也在想这个事情,
有点像我的项目. 同时渲染 开销太大了.所以做了一个渲染的序列.大家排队渲染.
屏幕外面的组件没必要渲染.

**Comment by chenshuai2144** [comment]
@nikogu   等你的新功能好了,我再修改吧.....
需要改动底层了...

**Comment by hayderGo** [comment]
依然感觉肉眼可见的卡，比如列表页 https://preview.pro.ant.design/list/basic-list ，这貌似不是图表渲染的问题吧
