### ISSUE TITLE
当expandTable展开时会导致fixed列错位

### ISSUE THREAD

**Issue by anizephyr** [ant-design/ant-design-pro#3970]
![1536923587](https://user-images.githubusercontent.com/26772673/55958039-560e2f80-5c9a-11e9-968e-60ebdc2f8244.jpg)
如图，fixed列展开的高度与expandedTable不一致导致fixed列完全错位了

**Comment by chenshuai2144** [comment]
这种时候需要手工设置 height 了

**Comment by kuhami** [comment]
> ![1536923587](https://user-images.githubusercontent.com/26772673/55958039-560e2f80-5c9a-11e9-968e-60ebdc2f8244.jpg)
> 如图，fixed列展开的高度与expandedTable不一致导致fixed列完全错位了

我在ant Table组件做了修改可以解决一些问题，希望能帮到你 https://github.com/kuhami/AntTableFinder
![](https://raw.githubusercontent.com/kuhami/AntTableFinder/master/image/antTable.jpeg)
