### ISSUE TITLE
 不知道为什么，用了antd  3.16.x 版本后有问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#3971]
不知道为什么，用了antd  3.16.x 版本后有问题，

我的登录界面，文本框输入没反应。。。

**Comment by xgj1988** [comment]
我测试了一下。同样的代码 。antd 3.13.6  没问题，3.15.X有问题。

我的package.json 

`
{
  "name": "bzlvj-cms",
  "version": "2.0.0",
  "description": "遵义市播州区旅游局后端",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "cross-env PORT=8000 APP_TYPE=dev umi dev",
    "start:no-mock": "cross-env MOCK=none umi dev",
    "build": "umi build",
    "site": "npm run presite && cross-env APP_TYPE=dev npm run build && firebase deploy",
    "analyze": "cross-env ANALYZE=true umi build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "umi test",
    "test:component": "umi test ./src/components",
    "test:all": "node ./tests/run-tests.js",
    "prettier": "prettier --write ./src/**/**/**/*"
  },
  "dependencies": {
    "@antv/data-set": "0.9.6",
    "@babel/runtime": "7.1.5",
    "antd": "3.13.6",
    "bizcharts": "3.2.2",
    "bizcharts-plugin-slider": "2.0.3",
    "braft-editor": "1.9.7",
    "classnames": "2.2.6",
    "dva": "2.4.0",
    "enquire-js": "0.2.1",
    "hash.js": "1.1.5",
    "linked-map": "2.2.2",
    "lodash": "4.17.10",
    "lodash-decorators": "6.0.0",
    "memoize-one": "4.0.0",
    "moment": "2.24.0",
    "nprogress": "0.2.0",
    "numeral": "2.0.6",
    "nzh": "1.0.3",
    "omit.js": "1.0.0",
    "path-to-regexp": "2.4.0",
    "pinyin": "2.8.3",
    "prop-types": "15.5.10",
    "qs": "6.5.2",
    "rc-animate": "2.4.4",
    "react": "^16.8.6",
    "react-container-query": "0.11.0",
    "react-copy-to-clipboard": "5.0.1",
    "react-dnd": "2.6.0",
    "react-dnd-html5-backend": "2.6.0",
    "react-document-title": "2.0.3",
    "react-dom": "16.5.1",
    "react-fittext": "1.0.0",
    "react-router-dom": "4.3.1",
    "xlsx": "0.13.2",
    "react-geetest": "3.0.2",
    "react-resizable": "1.7.5",
    "react-media": "1.8.0"
  },
  "devDependencies": {
    "@types/react": "^16.4.11",
    "@types/react-dom": "^16.0.6",
    "antd-pro-merge-less": "^0.0.9",
    "antd-theme-webpack-plugin": "^1.1.8",
    "babel-eslint": "^9.0.0",
    "case-sensitive-paths-webpack-plugin": "^2.1.2",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.4.4",
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-compat": "^2.5.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.11.1",
    "gh-pages": "^2.0.0",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.0",
    "merge-umi-mock-data": "^0.0.3",
    "mockjs": "^1.0.1-beta3",
    "prettier": "1.14.2",
    "pro-download": "^1.0.1",
    "stylelint": "^9.4.0",
    "stylelint-config-prettier": "^4.0.0",
    "stylelint-config-standard": "^18.0.0",
    "umi": "^2.2.1",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-react": "^1.2.0"
  },
  "lint-staged": {
    "**/*.{js,jsx,less}": [
      "git add"
    ],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}

`

**Comment by chjiyun** [comment]
我也感觉有些组件都有点问题，没以前稳定了

**Comment by chenshuai2144** [comment]
有可重现的 demo 吗？

**Comment by xgj1988** [comment]
@chenyunchen  你可以远程我的电脑不，钉钉ID:xgj1988，因为这个工作量有点大，，我在codesandbox 上面还不好搞。

**Comment by chenshuai2144** [comment]
@xgj1988 给一个github的仓库地址就好了

**Comment by xgj1988** [comment]
@chenshuai2144  
github 地址：
[git@github.com:xgj1988/ant_pro_login_error.git](git@github.com:xgj1988/ant_pro_login_error.git)

你把antd的版本改成 3.13.6 就可以了。。有点诡异。。

**Comment by chenshuai2144** [comment]
@xgj1988  非常感谢你的帮助，pro中用法是错误的。antd最近修复了一个bug，pro中错误的用法不能使用了。我们会尽快修复

**Comment by afc163** [comment]
看看是哪个问题。

**Comment by xgj1988** [comment]
@chenshuai2144  不用谢。。你会发现我的项目的package.json的版本都把 ^ 这个符号去掉了。不敢升级啊，，有时候会出现莫名的问题。。希望ant 和 ant design pro 越来越好。

**Comment by xgj1988** [comment]
@chenshuai2144  你们修复好了之后 请说明一下，我这边也好升级。，谢谢。

**Comment by chenshuai2144** [comment]
好的，是我们基于 bug 做了一个 feature ，然后 bug 修了 我们的 feature 变成了 bug

**Comment by xgj1988** [comment]
@chenyunchen BUG修了吗？

**Comment by chenyunchen** [comment]
@xgj1988 tag錯人囉? :)

**Comment by xgj1988** [comment]
@chenyunchen  sorry

**Comment by xgj1988** [comment]
@chenshuai2144  帅神，，我的意思是你是不是已经把这个问题搞忘了。。还有 顺便看看这个嘛：
[](https://github.com/ant-design/ant-design-pro/issues/4037)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks/tree/master/UserLogin
sorry。这里用 ts 重写了。你再试试

**Comment by xgj1988** [comment]
@chenshuai2144  谢谢帅神，，第二个问题是否能帮我把把脉。。

**Comment by xgj1988** [comment]
@chenshuai2144  大神，我直接把antd pro 的 Login 覆盖我现在的可以吗？

**Comment by xgj1988** [comment]
@chenshuai2144  你给我的这个，我不会用啊。。我本来就不是搞前端的。。我们这里也没有懂这个typescript的，我的意思是我就用以前的那个，但是我把你最新的antd pro 的Login复制到我这里面都不行。
" ERROR  Failed to compile with 2 errors09:13:35

 error  

[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.

 @ ./src/pages/System/Login/Login.js 34:36-65
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

 error  in ./src/components/Login/index.tsx"

**Comment by chenshuai2144** [comment]
把 tsconfig.json 也拷贝一下。并且升级一下antd

**Comment by xgj1988** [comment]
@chenshuai2144 我拷贝过去了。然后 antd 也搞成3.17.0了。还是不行。

**Comment by chenshuai2144** [comment]
我在项目中已经测试过了。不会有问题，你可以看看pro的官方预览，也是ok得。你是不是有什么的别的黑科技

**Comment by xgj1988** [comment]
@chenshuai2144 我真的不敢用其他什么东西哟。。这样嘛。我一会在我的github  #上面（就是上次给的那歌地址）把代码改一下，如果不行的话，到时候还麻烦你拉下来看看可以不

**Comment by xgj1988** [comment]
@chenshuai2144   大神，你看嘛。我这里还是不行，改成你说的那种了的。。
github 地址：
git@github.com:xgj1988/ant_pro_login_error.git

你把antd的版本改成 3.13.6 就可以了。。有点诡异。。

登录地址：
http://localhost:8000/system/login/index

**Comment by xgj1988** [comment]
@chenshuai2144  Login组件的 LoginItem.js 文件里面的Input 只要加上 getFieldDecorator。就不行了。。

**Comment by xgj1988** [comment]
@chenshuai2144  有没有可能是package.json里面的某些包要升级。

**Comment by xgj1988** [comment]
把我用到的package.json里面的所有包升级了都不行。

**Comment by chenshuai2144** [comment]
@xgj1988  给个 https 的 git 地址吧，。最近忙的否没空管 github 了

**Comment by xgj1988** [comment]
@chenshuai2144    帅哥   还是要关心一下github撒 。。
https://github.com/xgj1988/ant_pro_login_error.git

你把antd的版本改成 3.13.6 就可以了。。有点诡异。。

登录地址：
http://localhost:8000/system/login/index

**Comment by xgj1988** [comment]
额，。问题找到了

**Comment by chenshuai2144** [comment]
@xgj1988  秀出来让大家都知道一下

**Comment by xgj1988** [comment]
@chenshuai2144  把reac-dom 版本升级一下。  "@types/react-dom": "^16.8.4",    "react-dom": "^16.8.4", 
这两个。升级到16.8.4以上就可以了。
