### ISSUE TITLE
前后端联调 请求后端接口返回的是编译过的首页index.html ,没有返回后端接口

### ISSUE THREAD

**Issue by caogaofeng0** [ant-design/ant-design-pro#3972]
用 npm run start:no-mock ,请求后端接口 返回的是编译首页index.html ,没有到后端，状态码是200，再次请求同一个接口 状态码是304. host 也配置了。我直接输入后端接口 加域名 是可以连接到。请问 如果解决这个问题？？

**Comment by caogaofeng0** [comment]
配置 config.js 里面的 proxy 以后 请求接口 报500 ，报错为 connot read property 'split' of null

**Comment by caogaofeng0** [comment]
> 用 npm run start:no-mock ,请求后端接口 返回的是编译首页index.html ,没有到后端，状态码是200，再次请求同一个接口 状态码是304. host 也配置了。我直接输入后端接口 加域名 是可以连接到。请问 如果解决这个问题？？

配置config.js 里面的proxy以后 请求接口报500 ，报错为 connot read property 'split' of null

**Comment by caogaofeng0** [comment]
> > 用 npm run start:no-mock ,请求后端接口 返回的是编译首页index.html ,没有到后端，状态码是200，再次请求同一个接口 状态码是304. host 也配置了。我直接输入后端接口 加域名 是可以连接到。请问 如果解决这个问题？？
> 
> 配置config.js 里面的proxy以后 请求接口报500 ，报错为 connot read property 'split' of null
找到原因 是因为 config.js  proxy targert 直接配的服务器地址，没有加 http://  导致的

**Comment by chenshuai2144** [comment]
非常好的 debug 过程
