### ISSUE TITLE
用的组件好多都是不再维护的和alpha版本的，难道就没人升级一下吗？

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design-pro#3973]
用的组件好多都是不再维护的和alpha版本的，难道就没人升级一下吗？
![2019-04-12_10-13-52](https://user-images.githubusercontent.com/3994941/56007600-e173d900-5d0b-11e9-9545-c57a017662e4.png)

**Comment by afc163** [comment]
warning 无视就好了，npm 社区就是这样的。
