### ISSUE TITLE
各位大神，哪位集成过文本编辑器，提供个案例来借鉴一下？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#3975]

**Comment by chjiyun** [comment]
社区有braftjs组件，不过有一些坑，编辑表格可能会有问题

**Comment by zhuguangyue** [comment]
> 社区有braftjs组件，不过有一些坑，编辑表格可能会有问题

我目前使用react-quill，但是效果不太理想，存在一些bug

**Comment by ehsanbay** [comment]
[用这个看看[https://jpuri.github.io/react-draft-wysiwyg/](url)

**Comment by zhaocz2015** [comment]
https://github.com/margox/braft-editor

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
