### ISSUE TITLE
请教下怎么查询表格，参数怎么带到浏览器地址呢？

### ISSUE THREAD

**Issue by laiyiyi** [ant-design/ant-design-pro#3976]
请教下怎么查询表格，参数怎么带到浏览器地址呢？

**Comment by chenshuai2144** [comment]
umi包装了 react-router 的代码。 react-router 又使用了 [history](https://github.com/ReactTraining/history) 这个库。具体详细可以看 [window.history](https://developer.mozilla.org/en-US/docs/Web/API/Window/history)
示例代码：

```
export interface RouteData { pathname: string, query?:{[key:string]:any}, search?: string, state?: any }
import router from 'umi/router';
router.push({
   pathname:"string",
   query: JSONObject
})
```
