### ISSUE TITLE
https://preview.pro.ant.design 挂了一周没人管？

### ISSUE THREAD

**Issue by tcper** [ant-design/ant-design-pro#3982]
这个站没人管？
还是技术实力不行？

**Comment by afc163** [comment]
没挂，能访问。https://downforeveryoneorjustme.com/preview.pro.ant.design

**Comment by Thyiad** [comment]
根本不是翻墙的问题。翻不翻墙都无法访问

**Comment by Thyiad** [comment]
![image](https://user-images.githubusercontent.com/3324812/56358741-2323e880-6212-11e9-8e14-8a5e57389be4.png)
控制台爆这种错误

**Comment by chenshuai2144** [comment]
试着清空一下你的网站数据呢？
