### ISSUE TITLE
suggest,Can you increase the folding function

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design-pro#399]
In the area where the red line is drawn, the folding function can be supported.
thanks.
![image](https://user-images.githubusercontent.com/26354664/33793982-8cf665da-dcfd-11e7-8240-e80b71194ea5.png)

**Comment by chenshuai2144** [comment]
Why have this demand?
What should we do?

**Comment by gebilaoman** [comment]
@chenshuai2144 
First of all, this is a dispensable idea.
Secondly, because I want to hide the details of the above page when I am doing the project, I can operate the functional area below.
The bottom of my page is a pure operating area, similar to editing.
That way, the page is friendly.
Of course, this is just an idea. You can do it best

**Comment by chenshuai2144** [comment]
@gebilaoman  
You can do it yourself, or welcome to pr.
This is not a common feature
