### ISSUE TITLE
本地无任何错误信息，build到线上后报错umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by LinQinTao** [ant-design/ant-design-pro#3995]
![image](https://user-images.githubusercontent.com/17447722/56080951-05cdd380-5e3a-11e9-803e-f4fb49f71c6d.png)

**Comment by xiaohuoni** [comment]
要么提供重现步骤，要么提供demo，不然这个就智能你自己排查了。

**Comment by chenshuai2144** [comment]
感觉出现了很多次。
相关 issue 很多。但是一般我们问了不回。应该是低级错误。

**Comment by LinQinTao** [comment]
很有意思的是windows打包没问题，mac 10.14.3 打包就会报这个错误，尴尬的很

**Comment by xiaohuoni** [comment]
可以给一个最小demo看看，感觉要是能定位到是个低级错误的话，可以FAQ里面加个提醒

**Comment by yihai8721** [comment]
![image](https://user-images.githubusercontent.com/11973605/56125390-6a5c7000-5fab-11e9-9ae7-57ed48575b7e.png)
![image](https://user-images.githubusercontent.com/11973605/56125423-76483200-5fab-11e9-946b-a49d146b36bb.png)
预览pro.ant.design也是同样问题，浏览器版本如上图

**Comment by chenshuai2144** [comment]
试着清空一下 applition

**Comment by yihai8721** [comment]
> 试着清空一下 applition

嗯嗯，可以了，不知道啥原因

**Comment by chenshuai2144** [comment]
感觉是因为我们的 localStorage

**Comment by mt3925** [comment]
https://github.com/webpack/webpack/issues/8996

**Comment by mt3925** [comment]
如果负载均衡的两台分别build应该也会有这种问题，低级错误的一种。

**Comment by chenshuai2144** [comment]
最近一直无法重现，先关了
