### ISSUE TITLE
在线预览里面的设置主题样式的那个功能没了？

### ISSUE THREAD

**Issue by xiongchun** [ant-design/ant-design-pro#3996]
在线预览里面的设置主题样式的那个功能没了？
https://preview.pro.ant.design/dashboard/analysis

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/56102842-3dd03600-5f62-11e9-9017-9ed8e7fb0edf.png)

**Comment by afc163** [comment]
确实没了。

**Comment by xiongchun** [comment]
你这图是本地抓取的还是官方在线预览的。我的本地图片也有那主题设置按钮的，但是官方在线预览没有。看下图。
----------------------------------------------------

**Comment by chenshuai2144** [comment]
修复了，变量修改部署工具没有跟进造成的。

**Comment by xiongchun** [comment]
看见了。我的小眼睛太亮了，居然被我发现了。

**Comment by xiaohuoni** [comment]
可是我这个是线上的截图耶🤔
