### ISSUE TITLE
代理后端服务器

### ISSUE THREAD

**Issue by chy89310** [ant-design/ant-design-pro#3998]
我的前端项目和后台服务器是部署在同一个环境里面的。但我现在调用后端服务器的api的时候都需要使用真实IP或者域名来访问后端服务器，有办法前端项目通过本地方式访问后端服务器么？

**Comment by xiaohuoni** [comment]
如果前端是部署在后端提供的容器里面，可以通过请求相对路径的方式访问

**Comment by chy89310** [comment]
但前端和後端是分離的，只是部署在同一個服務器上而已

**Comment by chenshuai2144** [comment]
proxy 有配置的。
https://webpack.js.org/configuration/dev-server/#devserverproxy

<blockquote><img src="/aad9d51e01a0dcc2caf5bee43dc8e647.svg" width="48" align="right"><div><img src="/bc3effb418df77da9e04825c48a58a49.ico" height="14"> webpack</div><div><strong><a href="https://webpack.js.org/configuration/dev-server/#devserverproxy">DevServer | webpack</a></strong></div><div>webpack is a module bundler. Its main purpose is to bundle JavaScript files for usage in a browser, yet it is also capable of transforming, bundling, or packaging just about any resource or asset.</div></blockquote>

**Comment by xiaohuoni** [comment]
> 但前端和後端是分離的，只是部署在同一個服務器上而已

那还是需要当两个项目处理了，这也不是同源
