### ISSUE TITLE
`Form.Item` cannot generate `validateStatus` and `help` automatically

### ISSUE THREAD

**Issue by Mantak** [ant-design/ant-design-pro#400]
下载项目 yarn start 以后，
访问 http://localhost:8000/#/form/basic-form，
console里报错，
问题是因为最后一排 “目标公开” 这排的内容一起的，
官方在线演示版，没有报错，有什么建议吗？

![jietu20171209-203331](https://user-images.githubusercontent.com/63792/33795648-7373730a-dd20-11e7-8d74-b2afba7ec3b1.jpg)

**Comment by chenshuai2144** [comment]
你可以看看这个 
[issues #5052](https://github.com/ant-design/ant-design/issues/5052)

**Comment by chenxiaochun** [comment]
那个demo对付一般情况没问题。可是，如果用了`Input.Group`在样式上就有问题了。ps：那个帖子还被锁了，只能评论在这里了

![image](https://user-images.githubusercontent.com/1744713/72123915-d71b6400-339d-11ea-929c-40db586327ca.png)
