### ISSUE TITLE
官方文档 太简陋了 一些组件用法都没有介绍

### ISSUE THREAD

**Issue by Lee981265** [ant-design/ant-design-pro#4000]
希望大佬们把文档完善一些

**Comment by xiongchun** [comment]
感觉还可以啊  算是写得不错的了。我正在看。具体组件用法我觉得需要自己动手去尝试了，结合antd的文档。

**Comment by chenshuai2144** [comment]
pro的组件以来ant的组件，我们这方面建设的的确不好，没有做一些详细的说明，如果有机会欢迎pr
