### ISSUE TITLE
文档有缺陷：入门->构建和发布->构建

### ISSUE THREAD

**Issue by xiongchun** [ant-design/ant-design-pro#4002]
文档有缺陷：入门->构建和发布->构建
-------------------------------------------
文档里说执行如下命令完成构建，

> $ npm run build

后面又说构建打包只需一个`umi build`
到底是哪个呢，还是两个都要执行。  

不好意思，我是小白啊，别回复我：你自己不会试一下啊。
文档不就是写个入门小白看的么？感觉这里看了不是很清楚。

**Comment by zhangshuai0101** [comment]
只需要执行npm run build就可以了

**Comment by xiongchun** [comment]
哦哦  好像明白了  $ npm run build 说的就是umi的build命令。谢谢。

**Comment by xiongchun** [comment]
> 只需要执行npm run build就可以了

哦哦 好像明白了 $ npm run build 说的就是umi的build命令。谢谢。
