### ISSUE TITLE
登录时，浏览器F12，network 能够查询明文的登录名和密码

### ISSUE THREAD

**Issue by yemaozi5518** [ant-design/ant-design-pro#4004]
感觉这样很不安全，想要实现antdesignpro加密，后端解密

**Comment by xiaohuoni** [comment]
这只是一个演示项目，真实场景，有强调安全的，自己实现就好

**Comment by xiaohuoni** [comment]
这只是一个演示项目，真实项目中，需要自己加加密

**Comment by yemaozi5518** [comment]
@xiaohuoni    看了一些资料，可以每次在发起请求的时候，拦截（登录）路径，请求公钥，加密，后端解密

**Comment by yemaozi5518** [comment]
@xiaohuoni   有最新的加密方法吗？

**Comment by xiaohuoni** [comment]
一般是看后端方案，来定

**Comment by imhele** [comment]
其实一般的情况用了 http 不需要加密，除非用户使用的浏览器比较古董，有人抓包的话浏览器都会提示证书不安全。最简单的加密就直接哈希，加时间戳的 salt ，把 account, signature 和 timestamp，后端校验时间与当前相差不超过 60 秒，并且 hash 结果一致，就基本无解
```js
const timestamp = Math.floor(Date.now() / 1000);
const signature = hmacSha256(`${timestamp}${account}`, payload.psw);
```

**Comment by yemaozi5518** [comment]
@imhele   有稍微全一点的代码吗？

**Comment by imhele** [comment]
https://github.com/imhele/bjtu-papms/blob/master/src/models/login.ts#L49-L50
https://github.com/imhele/bjtu-papms/blob/master/serve/app/middleware/auth.ts#L36-L40
https://github.com/imhele/bjtu-papms/blob/master/serve/app/service/user.ts#L80-L86

**Comment by yemaozi5518** [comment]
@imhele   感谢，我的仔细看看

**Comment by yemaozi5518** [comment]
@imhele   ts  和 es  差别大吗？

**Comment by imhele** [comment]
> @imhele ts 和 es 差别大吗？

不大，去掉类型定义都一样

**Comment by yemaozi5518** [comment]
@imhele   好的 ，感谢

**Comment by xiongchun** [comment]
> 其实一般的情况用了 http 不需要加密，除非用户使用的浏览器比较古董，有人抓包的话浏览器都会提示证书不安全。最简单的加密就直接哈希，加时间戳的 salt ，把 account, signature 和 timestamp，后端校验时间与当前相差不超过 60 秒，并且 hash 结果一致，就基本无解
> 
> ```js
> const timestamp = Math.floor(Date.now() / 1000);
> const signature = hmacSha256(`${timestamp}${account}`, payload.psw);
> ```

感觉只要用了https就能保证传输过程的安全了。似乎后面的步骤没啥意义，多余的？

**Comment by imhele** [comment]
> 感觉只要用了https就能保证传输过程的安全了。似乎后面的步骤没啥意义，多余的？

钓鱼 WiFi 可以替换成自签证书，浏览器只会提示“访问的站点不安全”，用户仍然可以点击“继续访问”，比如 Edge，`后面的步骤`起码可以保证密码在 http 过程中不会明文暴露，逆向加了时间戳的哈希或者建彩虹表的成本极大，普通站点目前用这种方式处理已经足够了
![image](https://user-images.githubusercontent.com/32428655/56183775-764b3f00-604a-11e9-9637-bbcf3cf8223c.png)

**Comment by yemaozi5518** [comment]
@imhele  仅仅想做一个前端传递密码加密，后端解密。后端密码的数据存储用的是org.springframework.security.crypto.password.PasswordEncoder. 我看了你的demo,但是貌似是单向的

**Comment by imhele** [comment]
> @imhele 仅仅想做一个前端传递密码加密，后端解密。后端密码的数据存储用的是org.springframework.security.crypto.password.PasswordEncoder. 我看了你的demo,但是貌似是单向的

嗯，这种安全性稍微低一点，上面的 demo 是不可逆加密，对称加解密其实差不多的

**Comment by xiongchun** [comment]
@imhele 怎么你的bjtu-papms里的文件都是.ts呢，antd-pro是.js?
