### ISSUE TITLE
菜单顶部导航模式下的页面布局混乱问题

### ISSUE THREAD

**Issue by xiongchun** [ant-design/ant-design-pro#4005]
当我把菜单布局调整为顶部导航以后，部分页面的面包屑区域并没有固定宽度，还是水平拉伸的效果。如下图。（图一是正常的，图二是不正常的）

**图一正常**
![2019-04-15_205026](https://user-images.githubusercontent.com/4091000/56134183-af3ed180-5fc0-11e9-9e38-1859110ca3e2.jpg)

**图二不正常**
![2019-04-15_205100](https://user-images.githubusercontent.com/4091000/56134198-b665df80-5fc0-11e9-9e2b-7d12797eface.jpg)

**Comment by xiongchun** [comment]
补充：找出规律了，所有带面包屑那块区域的页面在顶部导航菜单模式下面包屑区域不能居中。

**Comment by chenshuai2144** [comment]
面包屑是设计的覆盖整个屏幕的

**Comment by afc163** [comment]
这个设计不好，建议改掉。

**Comment by chenshuai2144** [comment]
面包屑 一整个屏幕会更加美观一些

**Comment by xiongchun** [comment]
> 面包屑 一整个屏幕会更加美观一些

不是很美观，建议改掉。建议团队内部将专业UI视觉设计师和程序员的权责分离。

**Comment by weicong** [comment]
Header 也无法显示出backIcon

**Comment by chenshuai2144** [comment]
pro 中 PageHeader 不会显示 backIcon 的。

**Comment by zombieJ** [comment]
找设计师再对一下，看看怎么优化一下。

**Comment by xiongchun** [comment]
感觉页面在这种BoxLayout模式下，页面上的UI元素在Box范围内进行对其排版应该是广泛的基本需求和大多数模版脚手架的处理方式吧。参考：[https://osworks.gitee.io/ui/admindesigns/layout_boxed.html](https://osworks.gitee.io/ui/admindesigns/layout_boxed.html)

**Comment by weicong** [comment]
面包屑除了首页，其他的都不会加上链接，大概看了一下，是通过判断有无component，而component属性没有传入。

**Comment by slashvortal** [comment]
JFYI - PageHeader's className={styles.pageHeader} in not exist in PageHeaderWrapper's index.less
So you may want to clean up the code

**Comment by xiongchun** [comment]
能把官方的demo演示栗子改对吗

**Comment by chenshuai2144** [comment]
我认为这样是对的。还没有讨论出结果。

**Comment by zhgqthomas** [comment]
所以这个是故意改成这样的吗？ 那麻烦将官网的演示页面更改一下吧，否则真的会以为是个bug。 希望可以把这个属性增加个开关来选择性的开启，个人比较倾向于官网目前的样式

**Comment by xiongchun** [comment]
为了有个比较直观的体验，我把两种效果贴在一张图上了，希望能提供居中对齐的方式，提供个非官方的优雅点的修改方式也行。
=======================
![未命名-1](https://user-images.githubusercontent.com/4091000/57517773-28281380-734a-11e9-8dab-c64f151ea8c4.png)

**Comment by afc163** [comment]
@xiongchun 第一个图两边加上留白就对了

**Comment by xiongchun** [comment]
> @xiongchun 第一个图两边加上留白就对了

嗯嗯  你的小眼睛很亮  就是这意思

**Comment by chenshuai2144** [comment]
@xiongchun  
我更倾向这种方案。 https://github.com/ant-design/ant-design-pro/pull/4187

**Comment by xiongchun** [comment]
> @xiongchun
> 我更倾向这种方案。 #4187

嗯嗯  我也倾向。 期待完善。

**Comment by guanrongjia** [comment]
怎么设置顶部菜单布局啊
