### ISSUE TITLE
如何跳过登陆页面，可以直接进入首页

### ISSUE THREAD

**Issue by MalavitaC** [ant-design/ant-design-pro#4007]
目前的需求不需要登陆页面，想访问/直接进入首页，要怎么设置呢？？？

**Comment by yuejie89** [comment]
把全局路由配置文件里的login配置路径注释掉或者移到下面， 还有要给你设的首页权限 （具体参考 Authorized）

**Comment by chenshuai2144** [comment]
楼上正解

**Comment by f7753** [comment]
当前V4版本SecurityLayout中也有跳转login页面的，也要处理下
