### ISSUE TITLE
seems to be useless code

### ISSUE THREAD

**Issue by timmyz** [ant-design/ant-design-pro#4011]
https://github.com/ant-design/ant-design-pro/blob/123f46d79dcfaa9bf0500eb2d814deacbaf321c0/src/components/Charts/Pie/index.js#L149-L154
since
https://github.com/ant-design/ant-design-pro/blob/123f46d79dcfaa9bf0500eb2d814deacbaf321c0/src/components/Charts/Pie/index.js#L149
so `data` here will never be null or undefined, right? this line seems to be useless?
https://github.com/ant-design/ant-design-pro/blob/123f46d79dcfaa9bf0500eb2d814deacbaf321c0/src/components/Charts/Pie/index.js#L154

**Comment by chenshuai2144** [comment]
js 并没类型配置。用户可以传入任何参数

**Comment by afc163** [comment]
确实多余了，可以来个 PR
