### ISSUE TITLE
是否可以将 ant-design-pro 当中的组件也独立一个项目

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4012]
是否可以将 ant-design-pro 当中的组件也独立一个项目，就像目前的 ant-design-pro-layout 一样。
例如：Charts、Exception、Result、PageLoading、SelectLang、TagSelect、AvatarList等。
这样在开发Block的时候省去了同样的组件需要Copy到不同的Block当中。
另外，也可以提高基于 ant-design-pro 所开发的应用的后期维护。

**Comment by chenshuai2144** [comment]
组件将会逐步抽离到 antd 中，或者基于 antd 做一下定制
