### ISSUE TITLE
官方文档打开白屏

### ISSUE THREAD

**Issue by qflchina1234** [ant-design/ant-design-pro#4014]

**Comment by Cleam** [comment]
![7771555466924_ pic_hd](https://user-images.githubusercontent.com/4132185/56256660-3b094880-60fc-11e9-871b-f08c102f9e94.jpg)

**Comment by Thyiad** [comment]
目测挂了

**Comment by xiaopanghhh** [comment]
好了。

**Comment by afc163** [comment]
好了！
