### ISSUE TITLE
想请教一下大佬们,关于ant design pro项目自动化部署到nginx服务器上,有什么好的解决方案?

### ISSUE THREAD

**Issue by zhichao8756** [ant-design/ant-design-pro#4015]
目前部署是这样一套流程:执行npm run build,打包 => 远程到服务器上,删除旧的文件包,然后将新的文件拖拽到nginx的html目录下.每次这样一套下来感觉很繁琐.想请问下大佬们有没有在用的前端自动化部署的解决方案?

**Comment by qflchina1234** [comment]
使用docker方式

**Comment by chenshuai2144** [comment]
pro 中有 docker 的配置。你可以看一下。
npm run docker-hub:build

**Comment by guozhengzhongGit** [comment]
妈耶，是直接放到 nginx 上的嘛
