### ISSUE TITLE
新增页面配置路由的问题。版本：antdpro v2.3

### ISSUE THREAD

**Issue by guozhengzhongGit** [ant-design/ant-design-pro#4016]
为什么在 `/config/router.config.js` 里新增页面只能在 ‘/’ 的配置对象里新增，如果想增加一个跟 /user 和 / 同级别的页面呢？我试了好像不支持。目前这个配置导出的是一个数组，里面有两个对象，一个 /user，一个/，可以再增加一个吗？或者在文档的什么地方有提到相关的操作？

**Comment by chenshuai2144** [comment]
放到/ 的前面就可以了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3994

**Comment by guozhengzhongGit** [comment]
@chenshuai2144 啊，懵圈了，一开始只是照着文档的那个例子去配置的，把 /new 放到了 / 的后面，一直不生效，今天早上突然灵机一动，想到了以前手动配置 react-router 的时候，/ 要放到最后，就试了一下，结果好了，哈哈～准备上来关 issues 的，没想到大佬已经回复了～感谢感谢，辛苦大佬，哈哈
