### ISSUE TITLE
请教：如何在iframe里的页面拿到全局的global model

### ISSUE THREAD

**Issue by wenmine** [ant-design/ant-design-pro#4019]
### 场景： 

`BasicLayout`所在的路由为根目录路由，即首页。在`BasicLayout`里有一些`header`,`footer`的公共组件，内部要嵌入`iframe`，`iframe`里的组件是基于`lankLayout`的路由组件。

`BasicLayout`里的`header`会去请求公共数据并保存在全局的`models`里的`global.js`，`iframe`里的组件需要共用

### 问题： 

目前遇到的问题是`iframe`里面的`BlankLayout`在`models/global`触发修改时并不会更新，发现`iframe`里的`global store`和外层的`store`无法共用。想请教下各路大神有没有遇到这个问题...

**Comment by chenshuai2144** [comment]
唯一的办法就是postMessage了
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/postMessage
