### ISSUE TITLE
IE支持

### ISSUE THREAD

**Issue by codingtest1981** [ant-design/ant-design-pro#402]
我现在使用IE11，打不开 ant design pro本地工程，如果使用IE浏览器打开，我需要做什么配置？

**Comment by kunhour** [comment]
目前在生产环境的可以支持导IE10+，
IE9由于不支持flex 。
开发环境目前不行，不知道roadhog需要怎么配置，我在roadhog提了issuele

**Comment by afc163** [comment]
duplicated of #210
