### ISSUE TITLE
请教： 怎么自定义request的错误处理

### ISSUE THREAD

**Issue by Jackay1990** [ant-design/ant-design-pro#4020]
接口文档https://bigfish.alipay.com/doc/api#request打不开，然后遇到一个问题，
我的API返回的数组如下
{
    message: "该终端名字已经存在"
    status_code: 409
}

http 状态码为 409， 然后想弹出错误信息为 message 的文字，而不用默认的，请问在 request.js 怎么处理

**Comment by TnWah** [comment]
request.interceptors.response.use(async response => {
  const data = await response.clone().json();
 console.log(data);
  return response;
});

**Comment by TnWah** [comment]
我是这样处理的    你试试看
