### ISSUE TITLE
请教一下，我想做一个国际化项目，怎么标准化日期

### ISSUE THREAD

**Issue by zhangfugui727** [ant-design/ant-design-pro#4022]
我需要做一个多时区的国际化项目
### 传递至后台的日期数据也为`2019-04-17T15:00:00.000+0000`
列表（Table）渲染可以用moment在render时处理，但是表单需要传递moment对象，因此我需要在数据获取时手动处理，但是如果我层级较深，且包含数组的数据，我应该怎么做才更规范优雅。

或者有更好的建议方案？

**Comment by chenshuai2144** [comment]
用Data.now,提交的时候再处理可以吗？

**Comment by zhangfugui727** [comment]
@chenshuai2144 这样也是一个思路，但是我也需要把字符串转为日期。后台字符串是这样的`2019-04-17T15:00:00.000+0000`，JSON反序列化的时候，他不会变为日期格式。

**Comment by chenshuai2144** [comment]
那你可以这样都用 date.now 前端展示的转化

**Comment by xiaopanghhh** [comment]
建设后到前，和前到后都固定一个日期格式， yyyy-MM-dd HH:mm:ss , 在前面model里面用字符串类型来处理，在 DatePicker、MonthPicker、RangePicker, WeekPicker  等组件当中设置 moment 的 locale ，

**Comment by zhangfugui727** [comment]
@xiaopanghhh 我还有些疑问：
如果服务器部署在中国，但是客户端可能在世界各地，例如github。

- 前端传递数据给后端，就需要转为服务器支持的时区格式，而不能用前端本地的

- 并且后端传递到前端的日期，前端也需要先根据服务器的时区转为日期，才能使用本地时区格式化

**Comment by xiaopanghhh** [comment]
那你在确定前后端交互的时候，在格式格式后面加入  Z 就好了呀。  yyyy-MM-dd HH:mm:ss  Z

**Comment by chenshuai2144** [comment]
服务器存储毫秒数应该是最好的办法。
前端根据不同的时区去分别展示。

**Comment by xiaopanghhh** [comment]
固定格式以后存日期格式，和存毫秒数 都可以解决这个问题，但是也是应项目而定。如果存毫秒数的话，在查询的过程当中，一些好用的 API 就不可以用了像 DAYDIFF 等等。 另外就是存毫秒数的话，在后期数据维护的过程当中，对维护人员不是很友好。

如果这个字段并非常规维护字段，如   创建时间、修改时间、等 时间缀 可以用 毫秒数
如果这个字段是常规的业务字段，如   会议开始时间、车辆出发时间  等建议用 datatime 。

**Comment by zhangfugui727** [comment]
@xiaopanghhh @chenshuai2144 
我现在采用的就是包含时区的固定格式`yyyy-MM-ddTHH:mm:ss.SSSZZ`，现在的好处就是前后台交互不用做特别的特殊处理。

  但是我发现，所有的方案都绕不开前台需要解析特殊处理的问题，列表循环可以这样
`render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>`
但是如果复杂的数据集，很难处理，例如
```
users: [{
  code: 'xxx'
  updateDate:  '2019-04-17T15:00:00.000+0000',
  work:[{
    name: 'xx公司',
    startDate:  '2018-04-17T15:00:00.000+0000',
    endDate:  '2019-04-17T15:00:00.000+0000'
  }]
}]
```
如果是单对象的我可以这样处理，如果是刚才复杂的我就没有很好的办法
`res.birthday = moment(res.birthday)`

**Comment by Krocsky** [comment]
应该前后端规范统一，传UTC的时间戳，前端可以用moment的 with-locale 做时区处理，一般都是这样做。
