### ISSUE TITLE
有没有哪位兄弟在react 里面弄个word，现在word的格式要求很严格，能在线编辑的  预览 ，有啥思路建议方便提供下吗

### ISSUE THREAD

**Issue by MRStruggle** [ant-design/ant-design-pro#4024]
有没有哪位兄弟在react 里面弄个word，现在word的格式要求很严格，能在线编辑的  预览 ，有啥思路建议方便提供下吗

**Comment by chenshuai2144** [comment]
可以试着去接入office 365.或者使用 永中家的。
免费的解决方案是没有的

**Comment by MRStruggle** [comment]
最纠结的 这些文档 不想放到公网上，微软有一套 ，但是必须公网域名

**Comment by chenshuai2144** [comment]
买私有的。

**Comment by MRStruggle** [comment]
加钱 谁的比较好些呢

**Comment by chenshuai2144** [comment]
我记得微软有私有化部署的东西。
国内有永中和 wps

**Comment by xiaopanghhh** [comment]
@MRStruggle 
以前我用过的是用的控件， http://www.ntko.com/  用的他们家的控件。
