### ISSUE TITLE
在pro中如何做到动态挂载 models？

### ISSUE THREAD

**Issue by superchow** [ant-design/ant-design-pro#4026]
即在conncet时，才会在 window.g_app._models 中挂载

**Comment by chenshuai2144** [comment]
这个是自动的，只要将models放到 pages 文件夹下即可

**Comment by superchow** [comment]
就是要实现，连接时自动啊

**Comment by chenshuai2144** [comment]
umi 中已经实现了，我们理解可能出现了一点偏差。
umi 中现在实现的是在  每个 Page 会打成一个js，只有加载 js 的时候 modal 才会加载。

**Comment by superchow** [comment]
明白了，习惯性放在外面的 models 里了
