### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by bobosbenben** [ant-design/ant-design-pro#4027]
1、2019-04-16日从GitHub上clone了antdPro的项目

2、npm start启动正常，页面展示正常

3、发现在BasicLayout加载时，会去请求currentUser
`dispatch({
      type: 'user/fetchCurrent',
    });`
mock/user.js会返回一个模拟的currentUser。

4、以上操作中我未对任何原项目的代码做修改。接下来，我想让BasicLayout请求currentUser时返回401状态，所以修改mock/user中的代码：
`'GET /api/currentUser': (req, res) => {
      res.status(401).send({
        timestamp: 1513932555104,
        status: 401,
        error: 'Unauthorized',
        message: 'Unauthorized',
      });
  },`

5、在地址栏中输入：http://localhost:8000/dashboard/analysis   此时，BasicLayout加载时，会首先去请求currentUser。然后mock会返回一个401的状态。然后antdPro的request会统一处理401状态，让页面跳转到Login页面。

6、这时，就会报一个内存泄漏的警告：
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

7、以上操作中，我对antdPro的原项目只修改了mock/user.js。让原来是返回模拟currentUser的函数，现在返回一个401状态。

8、求一个解决方法。我的想法是，BasicLayout的props发生变化，导致SideMenu的state会发生变化。但是因为路由跳转，SideMenu已卸载，导致更新state不成功。

**Comment by bobosbenben** [comment]
有什么替代的解决方案吗？
我只是想实现以下想法：用户直接输入 http://localhost:8000/ 的时候，判断用户是否已经登录，即在服务端的session是否已经失效。如果用户未登录(服务端session失效)，则跳转到登录页。
@chenshuai2144

**Comment by chenshuai2144** [comment]
@bobosbenben  解决办法其实是多封装一层

**Comment by bobosbenben** [comment]
是的，为了实现业务，已经采用多封装一层的方式解决了。
坐等官方的解决方法。

**Comment by bobosbenben** [comment]
可以考虑用三元表达式的方式，对约定路由也没有影响

**Comment by TSywan** [comment]
您是怎么封装的呢？大佬 @bobosbenben  能不能看一下呢:smile:

**Comment by Hyg900928** [comment]
@bobosbenben 请问你解决了吗

**Comment by Hyg900928** [comment]
@chenshuai2144 你说的封装, 能给个例子吗?

**Comment by chenshuai2144** [comment]
来这里
https://github.com/ant-design/ant-design-pro/issues/3808

**Comment by bobosbenben** [comment]
参照#3808，要么在componentDidMount里加一个判断，要么封装一个AuthBasicLayout。我一开始是用的在componentWillMount里加判断的方式,后来改成了类似于3808issue中所说的AuthBasicLayout方式  @Hyg900928     我试过了，在didMount里加判断然后跳转不会内存溢出@TSywan
