### ISSUE TITLE
更新最新版本后 PageHeaderWrapper 组件的 action 属性失效了， 以后还会支持这个属性吗

### ISSUE THREAD

**Issue by yafanz** [ant-design/ant-design-pro#4028]
更新最新版本后 PageHeaderWrapper 组件的 action 属性失效了， 以后还会支持这个属性吗

**Comment by chenshuai2144** [comment]
https://ant.design/components/page-header-cn/
可以看这个，是个 bug

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/81e86060
