### ISSUE TITLE
ant design pro 报错

### ISSUE THREAD

**Issue by honourfuture** [ant-design/ant-design-pro#4029]
今天执行 npm install dingtalk-jsapi --save
dingtalk-jsapi 是阿里钉钉一个h5微应用包
就导致项目不能打包
后删除了package-lock.js
后重新安装.

补充了xlsx包就导致如下报错:

×
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Adapter`.

**Comment by chenshuai2144** [comment]
ant design pro 里面用了钉钉 还是钉钉里面用了 pro。

**Comment by honourfuture** [comment]
> ant design pro 里面用了钉钉 还是钉钉里面用了 pro。

ant design pro 里面install 了一个钉钉官方提供的组件

**Comment by chenshuai2144** [comment]
dingtalk-jsapi 这个东西是小程序用的吧？执行环境都不一样。

**Comment by honourfuture** [comment]
> dingtalk-jsapi 这个东西是小程序用的吧？执行环境都不一样。

https://open-doc.dingtalk.com/microapp/dev/welcome-to-lark

我看是h5微应用也可以用

**Comment by chenshuai2144** [comment]
可能不支持 webpack 打包需要做特殊处理。你的这个报错感觉是 react 的问题，

**Comment by honourfuture** [comment]
> 可能不支持 webpack 打包需要做特殊处理。你的这个报错感觉是 react 的问题，

恩. 感觉也和 dingtalk-jsapi 没有什么关系
可以提供一个排查思路吗. 
不太懂 前端小白

**Comment by chenshuai2144** [comment]
他期望是一个类或者 function 但是你给了一个 object，你可以看一下是不是有什么东西未定义
