### ISSUE TITLE
build失败?

### ISSUE THREAD

**Issue by kstar11** [ant-design/ant-design-pro#403]
执行npm run build时报错,报错截图如下:

![qq 20171211111155](https://user-images.githubusercontent.com/25189126/33814290-30938b98-de64-11e7-8d51-8dae248640bb.png)

求解答,已经更新到最近版本的package.json,并重新安装依赖

**Comment by chenshuai2144** [comment]
环境?
使用的npm 安装的吗?

**Comment by kstar11** [comment]
对,刚下又重新使用cnpm install 安装依赖了
还是报错~

**Comment by chenshuai2144** [comment]
你的webpack 版本?

**Comment by kstar11** [comment]
重试了几次,最后莫名其妙好了~
搞不懂

**Comment by chenshuai2144** [comment]
试着重装你的全局webpack吧
