### ISSUE TITLE
为什么禁止未使用变量的提示？

### ISSUE THREAD

**Issue by Symous** [ant-design/ant-design-pro#4032]
tsconfig.json文件内的noUnusedLocals属性默认为true，导致在vscode等编辑器下无法显示未引用的变量（灰色）。很不方便。这个是出于什么考虑的呢？

**Comment by chenshuai2144** [comment]
这个应该交给 tslint 去做，而且` function(state,{put}){ put(xxx)}`这中的也会因为 state，没用到报错

**Comment by afc163** [comment]
state 可以写成 `_`？
