### ISSUE TITLE
使用本地svg图标报错

### ISSUE THREAD

**Issue by jianghongtao0228** [ant-design/ant-design-pro#4035]
我再antd pro项目中使用本地svg图标。
我的项目路径如下：
src
-assets/menu/back.svg
-components/SiderMenu/SiderMenu.js
我在SiderMenu.js中使用：import back from '../../assets/menu/back.svg'; 进行对back.svg图标的引入，并使用：< I c o n component={back}/  > 进行使用。发现有报错，报错信息如下：

**Comment by jianghongtao0228** [comment]
index.js:1 Warning: <data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTBweCIgaGVpZ2h0PSIxMHB4IiB2aWV3Qm94PSIwIDAgMTAgMTAiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDQ5LjMgKDUxMTY3KSAtIGh0dHA6Ly93d3cuYm9oZW1pYW5jb2RpbmcuY29tL3NrZXRjaCAtLT4KICAgIDx0aXRsZT5SZWN0YW5nbGUgMjwvdGl0bGU+CiAgICA8ZGVzYz5DcmVhdGVkIHdpdGggU2tldGNoLjwvZGVzYz4KICAgIDxkZWZzPjwvZGVmcz4KICAgIDxnIGlkPSLooaXlhYXmlYjmnpwiIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgICAgIDxnIGlkPSLmlLbotbciIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xOC4wMDAwMDAsIC02MTUuMDAwMDAwKSIgc3Ryb2tlPSIjNzE3RDg5Ij4KICAgICAgICAgICAgPGcgaWQ9Im5hdiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMDAwMDAsIDQwLjAwMDAwMCkiPgogICAgICAgICAgICAgICAgPGcgaWQ9ImJhY2siIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAwMDAwLCA1NjAuMDAwMDAwKSI+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0iTTIwLjg5MDM4ODIsMTUuNSBMMTguNjQwMzg4MiwyNC41IEwyMywyNC41IEMyNS40ODUyODE0LDI0LjUgMjcuNSwyMi40ODUyODE0IDI3LjUsMjAgQzI3LjUsMTcuNTE0NzE4NiAyNS40ODUyODE0LDE1LjUgMjMsMTUuNSBMMjAuODkwMzg4MiwxNS41IFoiIGlkPSJSZWN0YW5nbGUtMiI+PC9wYXRoPgogICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4= /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    in data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTBweCIgaGVpZ2h0PSIxMHB4IiB2aWV3Qm94PSIwIDAgMTAgMTAiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDQ5LjMgKDUxMTY3KSAtIGh0dHA6Ly93d3cuYm9oZW1pYW5jb2RpbmcuY29tL3NrZXRjaCAtLT4KICAgIDx0aXRsZT5SZWN0YW5nbGUgMjwvdGl0bGU+CiAgICA8ZGVzYz5DcmVhdGVkIHdpdGggU2tldGNoLjwvZGVzYz4KICAgIDxkZWZzPjwvZGVmcz4KICAgIDxnIGlkPSLooaXlhYXmlYjmnpwiIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgICAgIDxnIGlkPSLmlLbotbciIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xOC4wMDAwMDAsIC02MTUuMDAwMDAwKSIgc3Ryb2tlPSIjNzE3RDg5Ij4KICAgICAgICAgICAgPGcgaWQ9Im5hdiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMC4wMDAwMDAsIDQwLjAwMDAwMCkiPgogICAgICAgICAgICAgICAgPGcgaWQ9ImJhY2siIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAwMDAwLCA1NjAuMDAwMDAwKSI+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0iTTIwLjg5MDM4ODIsMTUuNSBMMTguNjQwMzg4MiwyNC41IEwyMywyNC41IEMyNS40ODUyODE0LDI0LjUgMjcuNSwyMi40ODUyODE0IDI3LjUsMjAgQzI3LjUsMTcuNTE0NzE4NiAyNS40ODUyODE0LDE1LjUgMjMsMTUuNSBMMjAuODkwMzg4MiwxNS41IFoiIGlkPSJSZWN0YW5nbGUtMiI+PC9wYXRoPgogICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4= (created by Icon)
    in i (created by LocaleReceiver)
    in LocaleReceiver (created by Icon)
    in Icon (created by SiderMenu)
    in button (created by Context.Consumer)
    in Wave (created by Context.Consumer)
    in Button (created by SiderMenu)
    in Suspense (created by SiderMenu)
    in div (created by Context.Consumer)
    in aside (created by Context.Consumer)
    in Sider (created by SiderMenu)
    in SiderMenu
    in Unknown (created by BasicLayout)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by Media)
    in Media
    in Unknown (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by DvaContainer)
    in DvaContainer

**Comment by jianghongtao0228** [comment]
我如果使用：<Icon component={() => <embed src={back} />} /> 图片是能加载出来的(说明这个图片已经引入到这个页面中了，但是没办法改变颜色)。请问这块应该如何正确使用这个图片呢，我参考的是https://ant.design/components/icon-cn/#%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2 最下方的使用方式

**Comment by chenshuai2144** [comment]
你的脚手架是 umi 吗/

**Comment by jianghongtao0228** [comment]
是的，我是基于antd pro 做的开发更改。

**Comment by jianghongtao0228** [comment]
> 你的脚手架是 umi 吗/

是在antd pro基础上进行的开发，请问这个问题有办法解决吗

**Comment by chenshuai2144** [comment]
我看这个是个 warning，你的问题应该不是 这个造成的。
将 svg 发布成 cdn，使用 img 标签载入试试呢？

**Comment by jianghongtao0228** [comment]
@chenshuai2144  使用img标签能够载入图标。但是还是不能改svg的颜色

**Comment by chenshuai2144** [comment]
@sorrycc umi 现在应该支持直接引入 svg 了吧

**Comment by chenshuai2144** [comment]
已支持这个特性。
