### ISSUE TITLE
请教一下关于命名与代码书写规范的事情

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4036]
各位好，
      首先感谢提供了这么好的开源框架，本人是一后端研发人员，对于前端是小白，一直跟进着 pro 转 TypeScript 的进度，以及自己尝试了一下基于 TS 改进一些小模块。但是在作的过程当中，有一些地方在命名的时候以及书写规范的时候感觉有一些不太明白的地方请教一下。
    1： 业务对象文件的命名  （原名叫 model.js  现在改为 schema.ts ）， 一般一个业务模块一个 model.ts 里面导出多个业务对象的 interface . 
    2:  状态机部分现修改为   （ 原名xxxStore.js  现在改为 models/xxxx.ts )  一般一个业务对象一个 model文件，有特殊业务会整合多个业务对象到一个 model
    3:  api 部分主要是处理 http 请求还有存本地的缓存数据的读写。
    4:  界面部分基本上没有太多的改变。

下面是我一个简单的项目（组织机构管理）的文件组织
```
src/
     /models/
           menu.ts    -- 菜单数据
           accounts.ts  --  登录后的用户信息
           commonOrganization.ts     ----  StaffSelect  和 DepartmentSelect 用的部分数据
     /pages/
           /Organization/    -- 组织机构管理模块
                  schema.ts   --- 描述了 Company、SubCompany 等业务对象的接口
                  service.ts   --- 组织机构相关 HTTP 的 API 的封装
                  Index.ts     ---- 组织机构的管理界面，左边树型、右边根据点击树节点自动变化。
                  /models/
                         organization.ts   -- 组织机构通用业务的model, 包括组织机构树型结构调取，分类数据调取等
                  /Company/   --- 总公司维护
                          /models/
                               company.ts   ---- 对总公司的CRUD的业务处理
                          List.ts      总公司列表界面
                          Edit.ts         总公司单个维护界面
                          BatchEdit.ts        总公司批量维护列表界面
                          View.ts        总公司单个内容显示界面
                   /SubCompany/   --- 分公司维护
                          /models/
                               subCompany.ts   ---- 对分公司的CRUD的业务处理
                          List.ts      分公司列表界面
                          Edit.ts         分公司单个维护界面
                          BatchEdit.ts        分公司批量维护列表界面
                          View.ts        分公司单个内容显示界面
                 /Department    部门维护展开如总公司维护一样
                 /Staff                员工维护展开如总公司维护一样
                 /WorkGroup     工作组维护展开如总公司维护一样
                 /Common
                        StaffSelect.ts ---  选择员工的组件
                        DepartmentSelect.ts  ---  选择部门的组件

```
目前打算将 Organization 单独维护为一个 block 。
疑问如下：
1：这种命名是否规范与合理，希望大家给出一点儿建议
2：如果将 Organization 修改为一个 block 的话，当中的部分组件 service, model, pages下的部分组件如何能够变为全局的，方便其它模块直接用。
3：Component 与 PureComponet 的选择，啥时候用Component啥时候用PureComponet
4：extends Component 与 React.SFC 的选择，啥样的业务场景用那种方式更好。
5：@connect   与   connect函数   的选择，啥样的业务场景用那种方式更好。

**Comment by superchow** [comment]
关于第二点
>>>shouldComponentUpdate(nextProps, nextState) ，函数一般不需要实现, 如果你的组件性能比较差或者渲染比较耗时，你可以考虑使React.PureComponent 重新实现该组件，PureComponent默认实现了一个版本的shouldComponentUpdate会进行state和props的比较。当然如果你有自信，可以自己实现比较nextProps和nextState是否发生了改变。

**Comment by superchow** [comment]
是第三点，不知为啥上面的无法编辑
