### ISSUE TITLE
FooterToolbar组件导致form的validateFieldsAndScroll不滚动BUG。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#4037]
github 地址：
git@github.com:xgj1988/ant_pro_login_error.git

运行地址
http://localhost:8000/footerbarerror

然后 你发发现滚动一屏之后的内容报错的话不会自动滚动到哪里，把 FooterToolbar去掉就行老

**Comment by xgj1988** [comment]
测试为FooterBarError.js

**Comment by xgj1988** [comment]
@chenshuai2144  这个问题是否可以看看。

**Comment by chenshuai2144** [comment]
https://github.com/yiminghe/dom-scroll-into-view#function-parameter
你可以需要控制一下滚动的 dom

**Comment by xgj1988** [comment]
谢谢。
