### ISSUE TITLE
table 组件 如果分多页，第一页选择3条，第二页选择3条，然后不管取消第一页的3条还是第二页的3条，都会导致所有选择的全部取消了。有哪位兄弟遇到过？

### ISSUE THREAD

**Issue by MRStruggle** [ant-design/ant-design-pro#4042]
table 组件 如果分多页，第一页选择3条，第二页选择3条，然后不管取消第一页的3条还是第二页的3条，都会导致所有选择的全部取消了。有哪位兄弟遇到过？
ant 版本^3.13.3",

**Comment by kuhami** [comment]
> table 组件 如果分多页，第一页选择3条，第二页选择3条，然后不管取消第一页的3条还是第二页的3条，都会导致所有选择的全部取消了。有哪位兄弟遇到过？
> ant 版本^3.13.3",

本来想解决问题的结果我也发现点问题 https://codesandbox.io/s/7ml7j9rqyj
