### ISSUE TITLE
[bug&fix]legend of pie chart bug

### ISSUE THREAD

**Issue by Thomstrong** [ant-design/ant-design-pro#4046]
* ## bug description
when use legend in pie component which folder is `src/components/Charts/Pie`,  filter and switch radio will cause the bug. the gif as follow:
![电脑端](https://user-images.githubusercontent.com/25574519/56470019-be67c880-6473-11e9-91a2-a3dd6eba521c.gif)

* ## solution
modify the 93 line of `/src/components/Charts/Pie/index.js` as follow
```
   this.setState({
      legendData,
-    });
+    }, () => this.chart.filter('x', null));
```
* because of the change of chart filter won't render the chart immediately (probably a `bizchart` bug), we can clear the chart filter after `legendData` render and next time call `this.getLegendData()` will get all the data of this radio or new radio data, and set a new chart filter.
* ## fixed page
* fixed component gif as follow:
![电脑端](https://user-images.githubusercontent.com/25574519/56470155-734eb500-6475-11e9-9568-e7e9e04dab2f.gif)

**Comment by ChhXin** [comment]
遇见了同一个问题

**Comment by chenshuai2144** [comment]
try to https://github.com/ant-design/pro-blocks/tree/master/Analysis

**Comment by diw1** [comment]
请问这个bug还会在ant pro里面修复吗？如果不会的话，是不是后续的更新只能通过umi block来调用？
