### ISSUE TITLE
pwa无法关闭？

### ISSUE THREAD

**Issue by ynnyh** [ant-design/ant-design-pro#4047]
控制台出现workbox提示，想要关掉pwa结果将defaultsetting和config中的pwa改为false后并没有起作用，请问怎么解决这个问题呢

**Comment by chenshuai2144** [comment]
pwa 设置为 false，应该就是关掉的。
打开 DevTools-> application-> clear site data。试一试

**Comment by ynnyh** [comment]
问题解决了，但是不是通过这种方式，我们是把config里面的代理设置为将/api去掉这种方式（比如/api/login，经过proxy后请求到/login），这样出现的问题，然后我们回复到修改之前就没问题了，即/api必须存在。。。

**Comment by xiaoshui222** [comment]
> pwa 设置为 false，应该就是关掉的。
> 打开 DevTools-> application-> clear site data。试一试

我们这里调查的结果猜测可能是，用了pwa后再关掉应该对service-worker反注册一下，不然浏览器还是对service-worker缓存
