### ISSUE TITLE
chrom开启自动翻译时，会导致部分使用`List`的页面报错

### ISSUE THREAD

**Issue by hldzlk** [ant-design/ant-design-pro#4049]
## chrom开启自动翻译时，会导致部分使用`List`的页面报错

直接在官方示例页面就可以重现此问题
### 重现步骤：
1.chrom开启自动翻译
2.进入`标准列表`
3.进入`搜索列表(文章)`
**备注：如果第3步页面没有白屏，先进其他页面，再进入`搜索列表(文章)`**

![image](https://user-images.githubusercontent.com/3941672/56488623-8020e680-6511-11e9-94ec-cd5170faf655.png)

![image](https://user-images.githubusercontent.com/3941672/56488688-b9595680-6511-11e9-8fe5-1e022746bc9f.png)

**Comment by chenshuai2144** [comment]
可以代开 sourcemap 看一下？看起来像是 react 寻找这个 dom 无法找到。

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#devtool

**Comment by hldzlk** [comment]
![image](https://user-images.githubusercontent.com/3941672/56572066-d749b880-65f0-11e9-97d7-2704d420eff0.png)

@chenshuai2144  确实是react-dom报的错

只有chrom开着自动翻译才会出现，目前还是没什么解决思路

**Comment by chenshuai2144** [comment]
把文档用 div包裹一下

**Comment by hldzlk** [comment]
```jsx
<div>
  <List/>
</div>
```

```jsx
 <List
  renderItem={item=>(
    <div> xxxxx </div>
  )}
/>
```

@chenshuai2144 是上面那样么,还是其他意思？    上面2个试了还是报错的

**Comment by chenshuai2144** [comment]
这个问题，暂无解法。虚拟 dom 和真实 dom 直接有偏差。reactdom 不知道怎么处理。

**Comment by hldzlk** [comment]
嗯，影响不是很大  只能先放着不管了

**Comment by chenshuai2144** [comment]
这个其实三大 框架都有问题。vue 和 react 的问题可能严重一点
