### ISSUE TITLE
src/components/PageHeaderWrapper/index.d.ts文件内容有误？

### ISSUE THREAD

**Issue by mutouzdl** [ant-design/ant-design-pro#4056]
PageHeaderWrapper组件的index.d.ts文件的内容，是不是写错了？
class名称写成Result了，以及，type变量是多余的吧？

![image](https://user-images.githubusercontent.com/3509249/56494983-c2a0ee00-6526-11e9-963d-5db77253cd59.png)

代码地址：
https://github.com/ant-design/ant-design-pro/blob/master/src/components/PageHeaderWrapper/index.d.ts

**Comment by chenshuai2144** [comment]
现在可以使用 https://github.com/ant-design/ant-design-pro-layout 中的 PageHeaderWrapper 了
