### ISSUE TITLE
删除pwa导致页面不能刷新

### ISSUE THREAD

**Issue by gk525152097** [ant-design/ant-design-pro#4058]
pro版本 2.1.1
config问题把pwa注释掉后
部署到服务器上
页面刷新F5不成功 不能显示页面

**Comment by chenshuai2144** [comment]
有详细的报错或者可重现的地址吗？

**Comment by gk525152097** [comment]
没有详细报告 因为F5刷新 直接刷新掉了
部署问题 不能复现

**Comment by chenshuai2144** [comment]
打开 DevTools-> application-> clear site data
通过这种方式呢
