### ISSUE TITLE
请教下我该如何从redux中给弹窗组件里面的input赋值

### ISSUE THREAD

**Issue by Nickynodejs** [ant-design/ant-design-pro#406]
我把弹窗单独写成组件之后，就没法用`this.props.form.setFieldsValue`这个方法给input赋值了，看了[rc-form@2.1.5](http://react-component.github.io/form/examples/redux.html)之后,多了一层value。

**Comment by chenshuai2144** [comment]
代码付上来....
我们再厉害也猜不到的  ..........

**Comment by Nickynodejs** [comment]
`render(){
    const {type} = this.state;
    const { getFieldDecorator} = this.props.form;
    const {rule:{visible1,editUser:{managerLoginName}}} = this.props
    console.log(managerLoginName)
    const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 5 },
        offset:2
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 12 },
        md: { span: 10 },
      }
    }

    return(
      <Modal
        title = "编辑管理员"
        visible = {visible1}
        onOk = {this.handleUser}
        onCancel = {this.handleUserCancel}
      >
        <Form onsubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label="管理员登录名">
            {getFieldDecorator('managerLoginName',{
              rules:[{
                required:true, message:'请您输入管理员登录名'
              }]
            })(
              <Input placeholder="请您输入管理员登录名"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员姓名">
            {getFieldDecorator('managerNameCn',{
              rules:[{
                required:true, message:'请您输入管理员姓名'
              }]
            })(
              <Input placeholder="请您输入管理员姓名"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员邮箱">
            {getFieldDecorator('managerEmail',{
              rules:[{
                required:true, message:'请您输入管理员邮箱'
              },{
                type:'email', message:'邮箱格式错误'
              }]
            })(
              <Input placeholder="请您输入管理员邮箱"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员电话">
            {getFieldDecorator('managerMobile',{
              rules:[{
                required:true,message:'请您输入管理员电话'
              },{
                pattern:/^[1][3,4,5,7,8][0-9]{9}$/, message:'手机号格式错误'
              }]
            })(
              <Input placeholder="请您输入管理员电话"/>
            )}
          </FormItem>
        </Form>
      </Modal>
    )
  }`
我在点击编辑的时候把table那行数据存储在redux里面，然后想赋值在弹层上面。

**Comment by Nickynodejs** [comment]
`render(){
    const {type} = this.state;
    const { getFieldDecorator} = this.props.form;
    const {rule:{visible1,editUser:{managerLoginName}}} = this.props
    console.log(managerLoginName)
    const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 5 },
        offset:2
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 12 },
        md: { span: 10 },
      }
    }

    return(
      <Modal
        title = "编辑管理员"
        visible = {visible1}
        onOk = {this.handleUser}
        onCancel = {this.handleUserCancel}
      >
        <Form onsubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label="管理员登录名">
            {getFieldDecorator('managerLoginName',{
              rules:[{
                required:true, message:'请您输入管理员登录名'
              }]
            })(
              <Input placeholder="请您输入管理员登录名"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员姓名">
            {getFieldDecorator('managerNameCn',{
              rules:[{
                required:true, message:'请您输入管理员姓名'
              }]
            })(
              <Input placeholder="请您输入管理员姓名"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员邮箱">
            {getFieldDecorator('managerEmail',{
              rules:[{
                required:true, message:'请您输入管理员邮箱'
              },{
                type:'email', message:'邮箱格式错误'
              }]
            })(
              <Input placeholder="请您输入管理员邮箱"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员电话">
            {getFieldDecorator('managerMobile',{
              rules:[{
                required:true,message:'请您输入管理员电话'
              },{
                pattern:/^[1][3,4,5,7,8][0-9]{9}$/, message:'手机号格式错误'
              }]
            })(
              <Input placeholder="请您输入管理员电话"/>
            )}
          </FormItem>
        </Form>
      </Modal>
    )
  }`

**Comment by Nickynodejs** [comment]
` render(){
    const {type} = this.state;
    const { getFieldDecorator} = this.props.form;
    const {rule:{visible1,editUser:{managerLoginName}}} = this.props
    console.log(managerLoginName)
    const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 5 },
        offset:2
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 12 },
        md: { span: 10 },
      }
    }

    return(
      <Modal
        title = "编辑管理员"
        visible = {visible1}
        onOk = {this.handleUser}
        onCancel = {this.handleUserCancel}
      >
        <Form onsubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label="管理员登录名">
            {getFieldDecorator('managerLoginName',{
              rules:[{
                required:true, message:'请您输入管理员登录名'
              }]
            })(
              <Input placeholder="请您输入管理员登录名"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员姓名">
            {getFieldDecorator('managerNameCn',{
              rules:[{
                required:true, message:'请您输入管理员姓名'
              }]
            })(
              <Input placeholder="请您输入管理员姓名"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员邮箱">
            {getFieldDecorator('managerEmail',{
              rules:[{
                required:true, message:'请您输入管理员邮箱'
              },{
                type:'email', message:'邮箱格式错误'
              }]
            })(
              <Input placeholder="请您输入管理员邮箱"/>
            )}
          </FormItem>
          <FormItem {...formItemLayout} label="管理员电话">
            {getFieldDecorator('managerMobile',{
              rules:[{
                required:true,message:'请您输入管理员电话'
              },{
                pattern:/^[1][3,4,5,7,8][0-9]{9}$/, message:'手机号格式错误'
              }]
            })(
              <Input placeholder="请您输入管理员电话"/>
            )}
          </FormItem>
        </Form>
      </Modal>
    )
  } `

**Comment by chenshuai2144** [comment]
写法应该没有问题...
你还有别的信息能补充吗?

**Comment by Nickynodejs** [comment]
我点编辑的时候把table的一行数据放到redux里面，到弹层这边就不能把值放到input里面了。

**Comment by chenshuai2144** [comment]
没有看见你的redux和from 赋值的代码呀!

**Comment by Nickynodejs** [comment]
我用`this.props.form.setFieldsValue` 赋值放不上去，都是死循环，redux的值就是`edituser`下面的`managerLoginName`

**Comment by chenshuai2144** [comment]
找个有经验的同事 看看吧 .
你估计是redux绑定的有问题.
这儿不好解决.

**Comment by Nickynodejs** [comment]
` componentDidUpdate() {
    const {rule:{editUser:{managerLoginName}}} = this.props
    this.props.form.setFieldsValue({
      managerLoginName:managerLoginName
    })
  }`

**Comment by Nickynodejs** [comment]
` componentDidUpdate() {
    const {rule:{editUser:{managerLoginName}}} = this.props
    this.props.form.setFieldsValue({
      managerLoginName:managerLoginName
    })
  }`

**Comment by chenshuai2144** [comment]
双向绑定死锁了的感觉...[issue](https://github.com/ant-design/ant-design/issues/2985)
找你们同事看看把....
[issue](https://github.com/ant-design/ant-design/issues/2985)

**Comment by Nickynodejs** [comment]
公司就我一个人做没有其他人能帮忙- -！

**Comment by chenshuai2144** [comment]
那里多看看文档吧,我还以为是bug
我关了问题了......
太没营养了...

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2985

**Comment by chenshuai2144** [comment]
@afc163  已经付给他了...😥

**Comment by Nickynodejs** [comment]
@chenshuai2144  我是用的0.2.2版本的pro,用`Form.createFormField `会报错，需要引入rc-form用里面的`createFormField`

**Comment by chenshuai2144** [comment]
直接升级吧.....不推荐使用未真是发布版本,,现在还不稳定.

**Comment by Nickynodejs** [comment]
@chenshuai2144 谢谢指点，工作量太大没时间换了- -！

**Comment by x1nGoo** [comment]
@Nickynodejs  请问下怎么解决的？ 编辑时 怎么把 后台返回的值 传给 弹窗组件的input？
