### ISSUE TITLE
create-react-app依赖冲突

### ISSUE THREAD

**Issue by qjekingstar** [ant-design/ant-design-pro#4062]
`create-react-app`构建后`yarn add ant-design-pro`
`yarn start` 会报webpack依赖冲突
`npm ls webpack` 看了下
pro依赖af-webpack导致的
目前只能`SKIP_PREFLIGHT_CHECK=true`来解决
还是希望pro能分离出像antd一样纯粹的组件版本，谢谢

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks
这里有一些区块，用这些会更好，pro 的组件不是很合适
