### ISSUE TITLE
官方预览页显示空白

### ISSUE THREAD

**Issue by hujiulong** [ant-design/ant-design-pro#4063]
https://preview.pro.ant.design/

控制台有报错

![image](https://user-images.githubusercontent.com/13267437/56628028-dd847700-667a-11e9-98f6-3d36ae473bc4.png)

**Comment by hujiulong** [comment]
恢复了

**Comment by chenshuai2144** [comment]
antd 并没有 设置  externals ,你可能需要刷新一下
