### ISSUE TITLE
npm start可以正常运行，但是浏览器控制台报错 

### ISSUE THREAD

**Issue by HoChine** [ant-design/ant-design-pro#4064]
puer.client.js:1 Uncaught SyntaxError: Unexpected token <
main.5547aef7.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by HoChine** [comment]
项目克隆下来之后，没有进行的任何修改

**Comment by chenshuai2144** [comment]
配置一下 devtool。
https://umijs.org/zh/config/#devtool
看一下具体是哪里？ 
https://github.com/ant-design/ant-design-pro/pull/4059
