### ISSUE TITLE
ant-design-pro 在IE 11 下白屏

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4068]
各位大神好：

   小弟今天刚下载ant-design-pro 源码 用IE11浏览器访问出现白屏现象。
![QQ截图20190424155431](https://user-images.githubusercontent.com/44084004/56642141-631f1b80-66a9-11e9-9073-dd7749d39b95.png)
经调试工具发现由于js报错已经，附上js报错内容图片
![QQ截图20190424155458](https://user-images.githubusercontent.com/44084004/56642193-7d58f980-66a9-11e9-9de4-5626275450f3.png)
![微信截图_20190424155516](https://user-images.githubusercontent.com/44084004/56642188-7a5e0900-66a9-11e9-8b46-bee4381250a4.png)
请各位大神给予一些 解决方案。
谢谢！

**Comment by yutingzhao1991** [comment]
你有做修改吗？还是完全是 pro 现在 master 上的代码？

**Comment by zhangWeiZhuang** [comment]
> 你有做修改吗？还是完全是 pro 现在 master 上的代码？
你好！ 没有修改过！我直接npm start 运行的。

**Comment by chenshuai2144** [comment]
我这边是可以的，如果你说的是开发模式，现在是不支持的
umi 的 target 只支持编译时自动增加 polyfill。

**Comment by zhangWeiZhuang** [comment]
> 我这边是可以的，如果你说的是开发模式，现在是不支持的
> umi的目标只有支持编译时自动增加polyfill。

你好！是否使用webpack打包部署后，就可以了呢？

**Comment by zhangWeiZhuang** [comment]
> 我这边是可以的，如果你说的是开发模式，现在是不支持的
> umi的目标只有支持编译时自动增加polyfill。

你好！ 是需要我打包吗？

**Comment by zhangWeiZhuang** [comment]
部署后IE11下可以正常访问。谢谢各位指导！
