### ISSUE TITLE
umi/router如果父路由不配置重定向到子路由

### ISSUE THREAD

**Issue by johnsken-jerry** [ant-design/ant-design-pro#4069]
umi/router中如果父路由不配置重定向到子路由，父路由只有图标、名称、路径，那么一访问父路由的时候，将显示空白页面，然后怎么获取到当前路由渲染的状态呢？
在开发环境中会提示404，但目前没找到说可以获取到这个404的问题的方法

```
umi development 404 page
There's not a page yet at /dealer.

Create a React.js component in your pages directory at src/pages/dealer.js and configure the route in config file then this page will automatically refresh to show the new page component you created.
```

各位有好的解决办法吗？

**Comment by johnsken-jerry** [comment]
此场景是当菜单为接口获取的，需求是点击了一级菜单后自动重定向到第一个子菜单，而这个子菜单的重定向是不能写死的。

**Comment by johnsken-jerry** [comment]
前几天已经解决了，思路就是在菜单组件里render 判断是否有菜单数据进来，如果有，先选择数组第一个元素，如果有子菜单，就接着继续往下找，直至第一个子节点没有孙节点之后，跳转路由。

**Comment by chenshuai2144** [comment]
这几乎是唯一的办法了。
在正式环境可以在 404 中进行判断。

**Comment by ruofeng086** [comment]
v5版本的pro-layout，要怎么写？没有写自定义layout的情况下。

**Comment by chenshuai2144** [comment]
试试childrenRender
