### ISSUE TITLE
npm run build 打包时间有点长

### ISSUE THREAD

**Issue by waybi** [ant-design/ant-design-pro#407]
npm run build 打包时间有点长

**Comment by chenshuai2144** [comment]
无所谓吧!
都要部署了   时间长点怕啥.

**Comment by waybi** [comment]
@chenshuai2144 有时候需要发beta 或者 release 环境 测试，而且发的频率很高（比如修bug），这样子就等得蛋疼了

**Comment by chenshuai2144** [comment]
@waybi  [roadhog build过慢]( https://github.com/sorrycc/roadhog/issues/330) 
看看这个能不能帮到你.

**Comment by waybi** [comment]
@chenshuai2144  roadhog build --debug --max_old_space_size=4096 跑这个命令确实快了点

**Comment by shizhiqian** [comment]
@waybi 我运行这个roadhog build --debug --max_old_space_size=4096,还是很慢

**Comment by guonanci** [comment]
是不是图片太多会影响打包速度，max_old_space_size=12000都没用，，，打包一个小时，，，图片大，图片多是不是要放在图片服务器上，，，不要放在代码仓库里，，
