### ISSUE TITLE
怎么clone 1.4 版本的带码？

### ISSUE THREAD

**Issue by zooeyking** [ant-design/ant-design-pro#4070]
公司项目是1.4+版本的， 现在要熟悉项目，可是  clone 下来的都是2.0+版本的   怎么clone  一份1.0+版本的代码？

**Comment by zooeyking** [comment]
打算clone 一份 1.4版本的当参照，对比公司的项目代码，这样熟悉项目会快一点

**Comment by chenshuai2144** [comment]
`git checkout -b 1.4.0`

[git tag](https://git-scm.com/book/zh/v1/Git-%E5%9F%BA%E7%A1%80-%E6%89%93%E6%A0%87%E7%AD%BE)

**Comment by zooeyking** [comment]
checkout  -b 这是本地新建并切换到新分支哇， 不对吧!

**Comment by zooeyking** [comment]
git clone -b v4.1.0 仓库地址
哈哈  找到了，谢谢啦
