### ISSUE TITLE
BUG：退出登录，后台返回401。无限弹出notification。半分钟挤爆内存。

### ISSUE THREAD

**Issue by lemoncy** [ant-design/ant-design-pro#4074]
描述：【Pro已用代理连接后台】
【操作】
1、启动前端默认进入分析主页（没修改默认权限）。
2、点击退出，调用后台。（因使用token。此时未登录，前端还未缓存token，后台返回401。）
【问题】
1、Pro无限调用request.js 以下代码，弹出通知。自动关闭后任然持续弹出。
`notification.error({
    message: `请求错误 ${response.status}: ${response.url}`,
    description: errortext,
  });`

请问这个是哪里出了问题。是权限的初始的问题，这一块不是很清楚，麻烦哪个大佬清楚给解释下。

备注：authority.js 要如何设置权限，才不会启动就默认进入首页。还有直接输入对应路径也可随意进入对应资源，是不是也是权限相关。

![image](https://user-images.githubusercontent.com/3096214/56704319-3d445600-673f-11e9-94ab-464a58ac04b0.png)

**Comment by chenshuai2144** [comment]
401 之后应该跳转的，为什么会无限的调用接口？
可以给一个可供再现的仓库吗？

**Comment by lemoncy** [comment]
@chenshuai2144  
正常的登录，退出没问题。没登录直接进入首页，点退出，后台设置返回401到Pro，就无限调sys/logout后台接口。
暂时没有仓库，我不用后台代理，前端mock模拟401看下先。

**Comment by lemoncy** [comment]
@chenshuai2144 问题找到了，我参考了你request.js最新的代码 401的处理了，本身就是退出，就重复调用，打算判断下，如果本身是退出操作，token验证出现问题直接跳转登录页。其他的按照你的逻辑处理。
`  if (status === 401) {
    notification.error({
      message: '未登录或登录已过期，请重新登录。',
    });
    // @HACK
    /* eslint-disable no-underscore-dangle */
    window.g_app._store.dispatch({
      type: 'login/logout',
    });
    return;
  }`
