### ISSUE TITLE
Ant Design Pro 项目打包部署后，api数据接口访问404

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4075]
各位大神你们好

小弟从 Ant Design Pro 下载了源码打包发布后，目前出现了一个api404的问题。还希望各位大神指点一下！
![QQ截图20190425113309](https://user-images.githubusercontent.com/44084004/56708163-50aaed80-674e-11e9-8449-45341725586f.png)

**Comment by zhangWeiZhuang** [comment]
![image](https://user-images.githubusercontent.com/44084004/56708585-d67b6880-674f-11e9-9356-fe9c7aedd0fb.png)
这个是我打包部署的内容

**Comment by wangxingkang** [comment]
源码只包含mock接口 ，部署后 接口肯定是访问不到的

**Comment by zhangWeiZhuang** [comment]
> 源码只包含mock接口 ，部署后 接口肯定是访问不到的

谢谢指导！

**Comment by chenshuai2144** [comment]
可以读一下这个
http://pro.ant.design/docs/deploy-cn
