### ISSUE TITLE
请问 2.3.0发布后，不再更新新功能了吗？

### ISSUE THREAD

**Issue by cnhans** [ant-design/ant-design-pro#4076]
2.3.0 将会是 pro 的最后的一个版本，主要用于修正 ts 错误，此后将不接受 master 的功能添加。

请问 2.3.0发布后，不再更新新功能了吗？

**Comment by yutingzhao1991** [comment]
2.0 不再接受新的 feature 了。可以关注下 v4 https://github.com/ant-design/ant-design-pro/issues/3143
