### ISSUE TITLE
Ant design pro 2.0如何重定向代理到目标服务器

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4078]
各位大神你们好 ：

- 我这边下载 Ant design pro 源码 ，小弟想通过 代理接口配置，接口域名更改 的方式从其他服务器获取接口数据

- config.js 目前已经开放了proxy配置，代理到 Ant 官网下https://preview.pro.ant.design/
![image](https://user-images.githubusercontent.com/44084004/56716726-9aef9700-676d-11e9-98b0-f919595f6d42.png)

- 但目前开发环境我在登陆的时候，我依然发现登陆接口调用的路径依然是本地路径。
![image](https://user-images.githubusercontent.com/44084004/56716839-e2762300-676d-11e9-9a96-2fd21220c4d6.png)

- 我百度过这个代理问题，有人说代理不会修改Url ，有人说需要反向代理。不是很明白问题所以然。希望有这方面的各位大神能指点一下。感谢！

**Comment by zhang0ZGC** [comment]
因为你登录访问的地址是/api/login啊，并不是/server/api/

你要把[https://github.com/ant-design/ant-design-pro/blob/master/src/services/api.js#L107](https://github.com/ant-design/ant-design-pro/blob/master/src/services/api.js#L107)
这行改成/server/api/login才可以代理到ant官网

**Comment by zhangWeiZhuang** [comment]
> server

你好。

- 我按照你的方式调整，好像也不可以哦。
![image](https://user-images.githubusercontent.com/44084004/56718665-c2e0f980-6771-11e9-95c2-bbe0ed335d66.png)
![image](https://user-images.githubusercontent.com/44084004/56718673-c83e4400-6771-11e9-92a1-01688f3e70db.png)
![image](https://user-images.githubusercontent.com/44084004/56718640-bb215500-6771-11e9-9119-d4bcadb537e3.png)

**Comment by zhangWeiZhuang** [comment]
> 因为你登录访问的地址是/api/login啊，并不是/server/api/
> 
> 你要把
> [ant-design-pro/src/services/api.js](https://github.com/ant-design/ant-design-pro/blob/327d696b955b593534fa907ad990620279d716f0/src/services/api.js#L106-L111)
> 
> Lines 106 to 111 in [327d696](/ant-design/ant-design-pro/commit/327d696b955b593534fa907ad990620279d716f0)
> 
>  export async function fakeAccountLogin(params) { 
>    return request('/api/login/account', { 
>      method: 'POST', 
>      data: params, 
>    }); 
>  } 
> 这行改成/server/api/login才可以代理到ant官网

你好。
我按照你的方式调整，好像也不行哦
![image](https://user-images.githubusercontent.com/44084004/56718736-edcb4d80-6771-11e9-8655-f4621dc60b31.png)
![image](https://user-images.githubusercontent.com/44084004/56718762-fde32d00-6771-11e9-84af-fae9638af4d7.png)
![image](https://user-images.githubusercontent.com/44084004/56718768-00458700-6772-11e9-918f-596fba7d8a08.png)

**Comment by chenshuai2144** [comment]
你看看 node 控制台的输出，这里有详细的内容
https://webpack.docschina.org/configuration/dev-server/

**Comment by zhang0ZGC** [comment]
@zhangWeiZhuang 你看Response了么。。反向代理就是这样啊。。地址又不会变，本地dev服务器内部ziji 做的反代，换成其它地址拿到的就是其他内容啊

**Comment by zhangWeiZhuang** [comment]
> 你看看 node 控制台的输出，这里有详细的内容
> https://webpack.docschina.org/configuration/dev-server/

你好！
我看过 devServer.proxy 我看过这个文章。配置与 源码所配置的内容无大差异
![image](https://user-images.githubusercontent.com/44084004/56719738-f02ea700-6773-11e9-9f71-7ce15a6ff65f.png)

**Comment by zhangWeiZhuang** [comment]
> @zhangWeiZhuang 你看Response了么。。反向代理就是这样啊。。地址又不会变，本地dev服务器内部ziji 做的反代，换成其它地址拿到的就是其他内容啊

你好。
如果是因为地址不变的话，我是否可以通过浏览器的控制台看到实际访问的接口路径呢？如果有，能告诉下方法吗。
![image](https://user-images.githubusercontent.com/44084004/56719883-2a984400-6774-11e9-9ab5-e35f5b826f07.png)
我这边看不出来

**Comment by zhang0ZGC** [comment]
。。。没有，想都不要想。。，真实路径你已经在target里面指定了。。

`http://localhost:8803/server/api/login/account` -> `https://preview.pro.ant.design/api/login/account`

也没啥为啥，因为服务器的反向代理干的就是这种事

**Comment by jhoneybee** [comment]
> same problem here! :/ But I realized that it's calling my server but showing the local server address. How can I change that? how is this going to work in prod env?

real server address  http://127.0.0.1:8080/api/login
address requested by browser http://127.0.0.1:8000/api/login

Then you need to modify the reverse proxy

```json
  devServer: {
    proxy: {
      '/api': 'http://127.0.0.1:8080'
    }
  }
```

link 

+ https://webpack.docschina.org/configuration/dev-server/

**Comment by Helaiqu** [comment]
我后端接口java写的，放在centOS-tomcat下，传统多页项目ajax随便调通，react这一套就是调不通。请问后端需要配置什么东西才能让前端调通接口？

**Comment by jvcjunior** [comment]
How is this going to work in production?

I changed my proxy config to prod url. Then ran `npm run build`, deployed into my server. But, it's not working :/

Any idea why? 

How can I disable the proxy and use direct the dev or prod url?

**Comment by chenshuai2144** [comment]
in product ,
you can use nginx. 
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

**Comment by sipudi** [comment]
> 。。。没有，想都不要想。。，真实路径你已经在target里面指定了。。
> 
> `http://localhost:8803/server/api/login/account` -> `https://preview.pro.ant.design/api/login/account`
> 
> 也没啥为啥，因为服务器的反向代理干的就是这种事

怎样知道有没有代理成功

**Comment by zhang0ZGC** [comment]
> > 。。。没有，想都不要想。。，真实路径你已经在target里面指定了。。
> > `http://localhost:8803/server/api/login/account` -> `https://preview.pro.ant.design/api/login/account`
> > 也没啥为啥，因为服务器的反向代理干的就是这种事
> 
> 怎样知道有没有代理成功

随便改点内容，看返回结果不就知道了

**Comment by Shhuy** [comment]
本地起来的node后台服务，更改代理路径无法访问到后台：
![TIM截图20191023160444](https://user-images.githubusercontent.com/42715523/67371601-39d73d80-f5af-11e9-96fe-42e988f5fb95.png)
然后server中的请求
![server](https://user-images.githubusercontent.com/42715523/67371694-5d9a8380-f5af-11e9-9616-58b618f5d906.png)
无法请求到自己的后台服务器。需要怎么解决吗？
