### ISSUE TITLE
xs屏幕下PageHeaderWrapper的外边距疑问

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/ant-design-pro#4079]
在v1和稍早之前的v2版本中在screen-xs下，PageHeaderWrapper外边距是显示的
![BaiduShurufa_2019-4-25_15-16-20](https://user-images.githubusercontent.com/10346399/56716758-b5297500-676d-11e9-98ab-f7760727e177.png)

最近发现这个边距没有消失
![BaiduShurufa_2019-4-25_15-16-37](https://user-images.githubusercontent.com/10346399/56716762-b6f33880-676d-11e9-937a-424a46f5d866.png)

这个情况是故意为之的嘛？看着有点浪费空间。。:joy:

**Comment by chenshuai2144** [comment]
来一个pr?
