### ISSUE TITLE
渲染上一次的数据

### ISSUE THREAD

**Issue by basicfu** [ant-design/ant-design-pro#408]
请问这是什么情况，当编辑一条数据的后再次编辑其他数据，随便每次修改一下就会渲染上一次操作的数据，这个问题在我移除了之前安装的依赖后重新cnpm install新的依赖后发生，依赖版本都和demo一致，开发了2个月了都没出现这种情况，就今天重新装了下依赖发生的，不理解
![i0r06-v7h3q](https://user-images.githubusercontent.com/26153901/33829813-b1aa11be-deac-11e7-81e5-a5b638382ed8.gif)

**Comment by chenshuai2144** [comment]
额  这个不是我们官方的界面吧..

**Comment by afc163** [comment]
应该提到 ant design 并给出可重现的在线例子。

**Comment by basicfu** [comment]
@chenshuai2144 是官方的ui啊

**Comment by basicfu** [comment]
@afc163 好的，谢谢，确实是应该提到ant dsign
