### ISSUE TITLE
线上的pro Demo进不去了

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design-pro#4083]
https://preview.pro.ant.design/   进不去
![image](https://user-images.githubusercontent.com/20419163/56731995-8ec80180-678e-11e9-8877-47ab074047ac.png)
![image](https://user-images.githubusercontent.com/20419163/56732014-a1423b00-678e-11e9-8f8f-b8856a6bf673.png)
几天下来都是这样

**Comment by kevinpursuing** [comment]
强制刷新之后可以了，再次刷新后又不行了

**Comment by chenshuai2144** [comment]
试试这个， @sorrycc  能看到这个错误具体是什么吗?
![image](https://user-images.githubusercontent.com/8186664/56732375-b53a6c80-678f-11e9-832d-d19ac3e9df01.png)

**Comment by chenshuai2144** [comment]
@sorrycc  能看到这个错误具体是什么吗?

**Comment by chenshuai2144** [comment]
https://deploy-preview-4055--ant-design-pro.netlify.com 
master 好像被推送了这个分支的代码。我看到有个html loading。
这个分支只有翻墙才能看的到内容

**Comment by sorrycc** [comment]
我试了下 https://preview.pro.ant.design/dashboard/analysis 正常，应该是 pwa 缓存的问题吧。

**Comment by kevinpursuing** [comment]
通过chenshuai2144上面的方法可以进去了，不过也不能让每个浏览者都这样操作一遍吧~，如果这个问题能从你们那边去解决就好了，因为可能其他人也会有这个情况 @chenshuai2144 @sorrycc

**Comment by chenshuai2144** [comment]
我打算关掉 pwa 了，要正确的使用 pwa 真是一个困难的事情
