### ISSUE TITLE
拦截器Token失效刷新

### ISSUE THREAD

**Issue by liuxiawang** [ant-design/ant-design-pro#4084]
请问在座的大佬，在response拦截器中拦截到401错误，如果是token失效想要使用refreshtoken更新token，并再次调用原先请求做到用户无感知的完成操作，这个该怎么做？

**Comment by chenshuai2144** [comment]
umi-requset 中有 errorHandler，你可以在 errorHandler 中监控，并且重新发起请求

**Comment by liuxiawang** [comment]
errorHandler中好像拿到post请求带过去的参数哦，请问这个怎么解决？

**Comment by jianghongtao0228** [comment]
同问 关注一下

**Comment by chenshuai2144** [comment]
```
request.interceptors.response.use(async (response) => {
  const data = await response.clone().json();
  if(data && data.NOT_LOGIN) {
    location.href = 'login url';
  }
  return response;
})
```

**Comment by waylon-edmodo** [comment]
> ```
> request.interceptors.response.use(async (response) => {
>   const data = await response.clone().json();
>   if(data && data.NOT_LOGIN) {
>     location.href = 'login url';
>   }
>   return response;
> })
> ```

这个回答没看到方案呀。 如果return response，改为return其他的，errorHandler会得到空值。
