### ISSUE TITLE
DatePicker 月份的显示是英文月份

### ISSUE THREAD

**Issue by peterlxb** [ant-design/ant-design-pro#4088]
在本地开发环境月份显示正常，代码构建后发布到测试环境月份也是显示中文的，最后上线到线上环境显示英文，关键是Month 用在好几个独立的组件中，之前的正常显示，新功能上线要选择月份，出现这样的问题

**Comment by kuhami** [comment]
> 本地
应该是moment版本的问题

**Comment by cnchore** [comment]
本地开发环境没问题，那就是你发布上线打包配置有问题

**Comment by peterlxb** [comment]
我上线到测试服务器和线上服务器代码都是是一样的，线上测试地址是好的，线上测试环境有问题

**Comment by peterlxb** [comment]
一半month显示中文，一半显示英文 
升级 umi umi-plugin-react 到最新貌似恢复正常

**Comment by chenshuai2144** [comment]
@peterlxb 原来用的是多少版本的？

**Comment by chenshuai2144** [comment]
> 一半month显示中文，一半显示英文
升级 umi umi-plugin-react 到最新貌似恢复正常

@sorrycc 
这可能是个风险点。怎么保证插件和umi的版本是匹配的
