### ISSUE TITLE
选择和输入框好像升级了antd3.0后位置有问题

### ISSUE THREAD

**Issue by ityao** [ant-design/ant-design-pro#409]
测试页面可见
https://preview.pro.ant.design/#/user/register

获取验证码按钮在输入框右下4个像素, 之前好像没这个问题, 是不是升级antd 3.0出现的?

![image](https://user-images.githubusercontent.com/832215/33831878-bf462f80-deb4-11e7-8796-cc974fac7a4c.png)

**Comment by chenshuai2144** [comment]
#359
重复了

**Comment by afc163** [comment]
Fixed in 3.0.1
