### ISSUE TITLE
登录拦截不生效，先进入主页（currentUser触发了），再重定向回登录页

### ISSUE THREAD

**Issue by hedy0111** [ant-design/ant-design-pro#4092]
每次启动都是先进入主页,并且请求一下currentUser,然后再重定向回登陆

**Comment by unrealsmart** [comment]
这个问题的主要原因就是`models/user.js` 文件 `*fetchCurrent`中的 `yield call(queryCurrent);`
这个函数会进行长时操作，就会导致先渲染页面，用户验证失败时就会跳转的问题。

因为没啥时间，我是通过`jwt`在登录时保存用户信息，`*fetchCurrent`进行判断的简单方式实现的，此方法尚有缺陷，慎用。

![image](https://user-images.githubusercontent.com/11688458/56848247-2bb6a600-6919-11e9-8e0b-16a4d4f8cf19.png)

可以考虑在`basicLayout`页面渲染前判断或重新验证用户登录是否有效。
或者在issues中搜索`登录`，不过目前似乎没有什么比较完善的解决方式。

静待解决方法。。

**Comment by Tzng** [comment]
我是让后台加上了currentUser这个接口，就是用来获取下用户信息的

**Comment by hedy0111** [comment]
> 我是让后台加上了currentUser这个接口，就是用来获取下用户信息的

我有这个接口,但是是需要传参数的,再没登陆前,这个参数是没有的,然后就会报错

**Comment by Tzng** [comment]
> > 我是让后台加上了currentUser这个接口，就是用来获取下用户信息的
> 
> 我有这个接口，但是是需要传参数的，再没登陆前，这个参数是没有的，然后就会报错

这里你需要配置一下，什么时候进行请求，我这个版本在app.js中，有一个render函数，我对这个方法进行了修改，你看看你那个是不是也有这个函数
```
export function render(oldRender) {
    // 未登录的情况设置成游客
    if (!sessionStorage.getItem('usertoken')) {
        // 设置成游客
        authRoutes = ['visitor'];
        oldRender();
        return;
    }
    // 如果当前地址是登录操作
    if (window.location.href.indexOf('/user/')) {
        oldRender();
        return;
    }
    // 获取用户数据
    request(API_URL + '/api/comm/currentUser', {
        method: 'POST',
    }).then((res) => {
        authRoutes = [res.usertype];
        oldRender();
    }, () => {
        oldRender();
    });
}
```

**Comment by unrealsmart** [comment]
@Tzng 的方式是可以的，你完全可以在所有页面渲染前判断权限或者验证登录信息

修改 `src/app.js`文件
```
export function render(oldRender) {
  // 页面加载
  ReactDOM.render(<PageLoading />, document.getElementById('root'));

  // 登录失败处理
  const loginFailed = () => {
    setAuthority([]); // [] or ['guest']
    reloadAuthorized();
    router.replace('/login');
    oldRender();
  };

  // 发送 HTTP 请求，用于判断用户权限或登录令牌等
  request('/api/user', {
    method: 'POST'
  })
    .then(res => {
      if (res.status === 'ok') {
        setAuthority(res.authority); // res.authority = ['admin', 'user']
        reloadAuthorized();
        oldRender();
      } else {
        loginFailed();
      }
    })
    .catch(() => {
      loginFailed();
    });

  console.log('rendering');
}
```
注释掉`oldRender();`就不会挂载任何页面元素，嗯。。。这里似乎是可以尽情发挥，例如：页面加载
（如果不想显示任何东西可以注释掉页面加载）

注意：
路由可以使用 `umi/router`代替
权限可以使用`src/utils/authority.js`代替（`setAuthority`和`getAuthority`是基于`storage`，没有什么问题，`reloadAuthorized()`尚不能确定于`oldRender`有什么影响，也许会重载？嗯……好像问题不大）

**Comment by hedy0111** [comment]
> > > 我是让后台加上了currentUser这个接口，就是用来获取下用户信息的
> > 
> > 
> > 我有这个接口，但是是需要传参数的，再没登陆前，这个参数是没有的，然后就会报错
> 
> 这里你需要配置一下，什么时候进行请求，我这个版本在app.js中，有一个render函数，我对这个方法进行了修改，你看看你那个是不是也有这个函数
> 
> ```
> export function render(oldRender) {
>     // 未登录的情况设置成游客
>     if (!sessionStorage.getItem('usertoken')) {
>         // 设置成游客
>         authRoutes = ['visitor'];
>         oldRender();
>         return;
>     }
>     // 如果当前地址是登录操作
>     if (window.location.href.indexOf('/user/')) {
>         oldRender();
>         return;
>     }
>     // 获取用户数据
>     request(API_URL + '/api/comm/currentUser', {
>         method: 'POST',
>     }).then((res) => {
>         authRoutes = [res.usertype];
>         oldRender();
>     }, () => {
>         oldRender();
>     });
> }
> ```
不行,都已经设置成游客了,还是会先进入主界面,再跳转到登陆界面,我最后的解决方案是,在basicLayout里面,componentDidMount先请求是否是登陆状态,是的话,再继续执行fetchCurrent等数据请求,不是的话,就直接返回到登陆界面,不会继续请求数据了

**Comment by unrealsmart** [comment]
@hedy0111 
判断成功之后再进行`oldReader()`

失败时应该 **清除权限！** **清除权限！** **清除权限！** `setAuthority(['guest'])`
然后跳转到登录页`router.replace('/user/login')`
不要忘了`oldReader()`

即使失败之后更改了路由，也不要忘了进行渲染

**Comment by Tzng** [comment]
> @hedy0111
> 判断成功之后再进行`oldReader()`
> 
> 失败时应该 **清除权限！** **清除权限！** **清除权限！** `setAuthority(['guest'])`
> 然后跳转到登录页`router.replace('/user/login')`
> 不要忘了`oldReader()`
> 
> 即使失败之后更改了路由，也不要忘了进行渲染

这

> > > > 我是让后台加上了currentUser这个接口，就是用来获取下用户信息的
> > > 
> > > 
> > > 我有这个接口，但是是需要传参数的，再没登陆前，这个参数是没有的，然后就会报错
> > 
> > 
> > 这里你需要配置一下，什么时候进行请求，我这个版本在app.js中，有一个render函数，我对这个方法进行了修改，你看看你那个是不是也有这个函数
> > ```
> > export function render(oldRender) {
> >     // 未登录的情况设置成游客
> >     if (!sessionStorage.getItem('usertoken')) {
> >         // 设置成游客
> >         authRoutes = ['visitor'];
> >         oldRender();
> >         return;
> >     }
> >     // 如果当前地址是登录操作
> >     if (window.location.href.indexOf('/user/')) {
> >         oldRender();
> >         return;
> >     }
> >     // 获取用户数据
> >     request(API_URL + '/api/comm/currentUser', {
> >         method: 'POST',
> >     }).then((res) => {
> >         authRoutes = [res.usertype];
> >         oldRender();
> >     }, () => {
> >         oldRender();
> >     });
> > }
> > ```
> 
> 不行,都已经设置成游客了,还是会先进入主界面,再跳转到登陆界面,我最后的解决方案是,在basicLayout里面,componentDidMount先请求是否是登陆状态,是的话,再继续执行fetchCurrent等数据请求,不是的话,就直接返回到登陆界面,不会继续请求数据了



> > > > 我是让后台加上了currentUser这个接口，就是用来获取下用户信息的
> > > 
> > > 
> > > 我有这个接口，但是是需要传参数的，再没登陆前，这个参数是没有的，然后就会报错
> > 
> > 
> > 这里你需要配置一下，什么时候进行请求，我这个版本在app.js中，有一个render函数，我对这个方法进行了修改，你看看你那个是不是也有这个函数
> > ```
> > export function render(oldRender) {
> >     // 未登录的情况设置成游客
> >     if (!sessionStorage.getItem('usertoken')) {
> >         // 设置成游客
> >         authRoutes = ['visitor'];
> >         oldRender();
> >         return;
> >     }
> >     // 如果当前地址是登录操作
> >     if (window.location.href.indexOf('/user/')) {
> >         oldRender();
> >         return;
> >     }
> >     // 获取用户数据
> >     request(API_URL + '/api/comm/currentUser', {
> >         method: 'POST',
> >     }).then((res) => {
> >         authRoutes = [res.usertype];
> >         oldRender();
> >     }, () => {
> >         oldRender();
> >     });
> > }
> > ```
> 
> 不行,都已经设置成游客了,还是会先进入主界面,再跳转到登陆界面,我最后的解决方案是,在basicLayout里面,componentDidMount先请求是否是登陆状态,是的话,再继续执行fetchCurrent等数据请求,不是的话,就直接返回到登陆界面,不会继续请求数据了

你也可以不设置成游客，如果当前访问不是登录页面，并且用户也没有登录，就直接给重定向到登录去，我等会去把我的修改成这样

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/3808
试试这个

**Comment by saltdg** [comment]
额，我很暴力的在BasicLayout中的 componentDidMount()中处理的， 判断是否已经登录，没有登录就直接跳转到登录页：
`if (!localStorage.getItem('token')) {
      router.push('/user/login');
      return;
    }`

**Comment by truewq** [comment]
> @Tzng 的方式是可以的，你完全可以在所有页面渲染前判断权限或者验证登录信息
> 
> 修改 `src/app.js`文件中的`render(oldRender)`函数
> 
> ```
> export function render(oldRender) {
>   // 页面加载
>   ReactDOM.render(<PageLoading />, document.getElementById('root'));
> 
>   // 登录失败处理
>   const loginFailed = () => {
>     setAuthority([]); // [] or ['guest']
>     reloadAuthorized();
>     router.replace('/login');
>     oldRender();
>   };
> 
>   // 发送 HTTP 请求，用于判断用户权限或登录令牌等
>   request('/api/user', {
>     method: 'POST'
>   })
>     .then(res => {
>       if (res.status === 'ok') {
>         setAuthority(res.authority); // res.authority = ['admin', 'user']
>         reloadAuthorized();
>         oldRender();
>       } else {
>         loginFailed();
>       }
>     })
>     .catch(() => {
>       loginFailed();
>     });
> 
>   console.log('rendering');
> }
> ```
> 
> 注释掉`oldRender();`就不会挂载任何页面元素，嗯。。。这里似乎是可以尽情发挥，例如：页面加载
> （如果不想显示任何东西可以注释掉页面加载）
> 
> 注意：
> 路由可以使用 `umi/router`代替
> 权限可以使用`src/utils/authority.js`代替（`setAuthority`和`getAuthority`是基于`storage`，没有什么问题，`reloadAuthorized()`尚不能确定于`oldRender`有什么影响，也许会重载？嗯……好像问题不大）

谢谢，用你提供的方法解决问题了。
