### ISSUE TITLE
关于pwa

### ISSUE THREAD

**Issue by superchow** [ant-design/ant-design-pro#4093]
在使用 nginx配置时，pwa所依赖的 manifest.json 文件被重写为 index.html 了
![image](https://user-images.githubusercontent.com/24707978/56790726-e8383b00-6837-11e9-860e-30822f9d672b.png)

js、css文件就能正确被加载，请问是哪里写错了吗？

**Comment by chenshuai2144** [comment]
只有在文件不存在的时候才会触发 try_files 
应该是你没有  manifest.json

**Comment by superchow** [comment]
try_files 

> 只有在文件不存在的时候才会触发 try_files
> 应该是你没有 manifest.json

try_files 已经被注释掉了哦， 因为我按Pro示例配置 刷新还是不行，所以用了 rewrite 实现的
manifest.json 肯定是有的，打包的文件里面能找到
用 postname 能拿到，但是在浏览器中会返回 index.html 了

**Comment by chenshuai2144** [comment]
你的描述感觉还是 nginx 的配置问题，先用 pro 中的 nginx 配置试试呢
