### ISSUE TITLE
整个程序的入口在哪里? 怎么判断进入时跳转登录还是主页?

### ISSUE THREAD

**Issue by FloaJa** [ant-design/ant-design-pro#4094]
每次进入后都会跳转主页, 然后401 闪回登录, 右边还会出来个大红叉, 非常不友好, 就不能直接判断本地token是否存在来决定跳转哪里吗?  特别是账号被别人顶掉之后的反应, 跟出BUG了一样.

**Comment by unrealsmart** [comment]
[#4092](https://github.com/ant-design/ant-design-pro/issues/4092)
