### ISSUE TITLE
router跳转时候如何缓存component

### ISSUE THREAD

**Issue by ismumu** [ant-design/ant-design-pro#4096]
想实现A页面跳转到B页面再返回A页面时候，A页面记住之前的状态；
现在返回A页面，A页面的component都会重载。

**Comment by chenshuai2144** [comment]
这个可以通过 redux 将状态记录，然后重置回去。
如果你想component 不要重挂载，可能实现不了或者需要改写 react-router

**Comment by ismumu** [comment]
@chenshuai2144 umi的routes配置项只支持数组，本来找了一个包（react-router-cache-route）但是umi不支持配置。。。

**Comment by chenshuai2144** [comment]
可以写个umi的插件来搞一搞,这个东西容易搞爆内存
