### ISSUE TITLE
上传组件，上传多个文件问题

### ISSUE THREAD

**Issue by MRStruggle** [ant-design/ant-design-pro#4097]
上传一个文件  后台也能接收，上传2个文件，后台只能接收一个，前台调试 发现第二个文件格式不对，如果上传3个  那么后台就可以接收2个文件，第3个接收不了，文件格式也不对，
最后一个附件的文件格式不是一个File，但是里面有一个属性 是附件，很想知道为啥，
![image](https://user-images.githubusercontent.com/29857641/56802951-fdbb5e00-6853-11e9-8712-ee8df8f2081d.png)

**Comment by sunguoxing0628** [comment]
@MRStruggle  我在使用`upload`组件上传多文件时候发现了一个问题，就是会调用多次，但是经常会出现第一次调用就已经把所有文件提交了，现在我使用的`reqwest`进行上传的，服务端可以一次性获取文件集合。
```
  handleUpload = () => {
    const { uploadFileList } = this.state;
    const formData = new FormData();
    uploadFileList.forEach((file) => {
      formData.append('file', file);
    });

    reqwest({
      data: formData,
      method: 'post',
      url: `${ip}/picture/upload`,
      processData: false,
      success: (response) => {
        ··· ···
      },
      error: () => {
        ··· ···
      },
    });
  };
```
其中`uploadFileList`是`upload`的`fileList`，目前我使用的这个曲线救国的方式。
