### ISSUE TITLE
热更新失效，只有重启服务才能生效更改

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#4102]
mac 版本 10.14.4
chrome 版本 73.0.3683.103
antd pro 2.1.1版本
umi版本 2.6.16

开发时，无法引起页面热刷新，需要重启本地服务才能更新到代码～！

**Comment by zhilianbi520** [comment]
找到原因了。。。路由配置的大小写问题～！

**Comment by jsuper1980** [comment]
bingo

**Comment by freya0608** [comment]
> 找到原因了。。。路由配置的大小写问题～！

请问这是啥意思？

**Comment by 521guyu** [comment]
我也是不起作用必须重启，您指的路由配置大小写是什么意思？

**Comment by pikaOuba** [comment]
我也是路由大小写的原因

**Comment by chenshuai2144** [comment]
路由是小写，但是写成了大写

**Comment by lmxyjy** [comment]
我也是这个原因导致的。在我的项目中使用的是umi2.2.8。建议遇到的朋友都检查一些路由配置文件中。引入的文件夹的大小写是否存在写错的问题。

**Comment by jackieli123723** [comment]
good
