### ISSUE TITLE
代理问题：配置代理调用接口失败，实际postman是成功的。

### ISSUE THREAD

**Issue by Helaiqu** [ant-design/ant-design-pro#4105]
**算了算了。我用create-react-app写了。这东西成功劝退。**

请各位大佬解惑：
我后端接口java写的，放在centOS-tomcat下，传统多页项目ajax随便调通，react这一套就是调不通。
前端配置proxy：{'/ api'：' http：//127.0.0.1 ：8080' }这些东西该搞的全都搞了。
**我有在网上搜索，基本上全是让配置proxy**
或者请问后端需要配置什么东西才能让前端调通接口？

（如图所示，proxy是服务器地址，postman可以调通接口，但实际操作无法正确调到该调的接口。）：
![7`_H9VODZE6@C63`K2~UB7J](https://user-images.githubusercontent.com/16275345/56863531-db5b4900-69e9-11e9-8f0d-5989558defe5.png)

![O8GX$QRXG1CKL9E%HI V$MM](https://user-images.githubusercontent.com/16275345/56863547-1eb5b780-69ea-11e9-92c5-2360d086b864.png)

![J4DBI8$ T 1N@B56PK{OYMG](https://user-images.githubusercontent.com/16275345/56863449-faa5a680-69e8-11e9-8cda-433ea0418b14.png)

![25WCA$H{4Q6K(AUXCYPBANO](https://user-images.githubusercontent.com/16275345/56863492-5bcd7a00-69e9-11e9-918d-9104181400c0.png)
![R}BMO22PXXL CMS%679ZGK](https://user-images.githubusercontent.com/16275345/56863496-5e2fd400-69e9-11e9-84cf-20737f18a719.png)

谢谢！

**Comment by zhangWeiZhuang** [comment]
你好，你这个需要配置代理。我前几天也遇到过。

**Comment by zhangWeiZhuang** [comment]
我是打包部署到iis上，需要在iis站点下加入反向代理就可以解决你的问题
https://www.cnblogs.com/yuzhihui/p/9335035.html 可以参考这个

**Comment by Helaiqu** [comment]
> 我是打包部署到的iis上，需要在iis的下站点加入反向代理就可以解决你的问题
> https://www.cnblogs.com/yuzhihui/p/9335035.html可以参考这个

我现在是开发环境啊。

**Comment by chenshuai2144** [comment]
400是传值错误，你是不是应该用 get

**Comment by Bigmuggle** [comment]
你这边解决这个问题了吗，我也类似这个问题

**Comment by Bigmuggle** [comment]
看起来是localhost：8000  其实上调用成功了，你再看一下，我刚才模拟了一下，是能拿到的，只是显示上不对

**Comment by Helaiqu** [comment]
> 看起来是localhost：8000 其实上调用成功了，你再看一下，我刚才模拟了一下，是能拿到的，只是显示上不对

请问我后端接口需要配置什么东西吗？后端接口就是java写的，放在centOS-tomcat下，后端需要配置什么我前端才能调通接口，传统多页网站一个ajax一下就调通了。用react这一套就是调不通。

**Comment by Bigmuggle** [comment]
> > 看起来是localhost：8000其实上调用成功了，你再看一下，我刚才模拟了一下，是能拿到的，只是显示上不对
> 
> 请问我后端接口需要配置什么东西吗？后端接口就是java的写的，放在的CentOS-tomcat的下，后端需要配置什么我前端才能调通接口，传统多页网站一个AJAX一下就调通了。用反应这一套就是调不通。

后台我不懂，我只是按照官方文档那样子写的配置，我就能请求到了，常规ajax可以的话，那这个应该也可以

**Comment by diangong** [comment]
同楼主一样问题。v4
