### ISSUE TITLE
How to change umi-request baseUrl?

### ISSUE THREAD

**Issue by sergiodanilo** [ant-design/ant-design-pro#4106]
Ex: Modify from 'http:localhost:8000/api/v1' to 'myserver.com/api/v1'.

**Comment by Thomstrong** [comment]
configure [proxy](https://umijs.org/config/#proxy) in `config/config.js`

**Comment by grim-bees** [comment]
Try to use interceptors, and register it in RequestConfig on app.tsx


```
const baseURLInterceptor = (url: null | string, options: RequestOptionsInit) => {
  return {
    url: `http://test/${url}`,
    options: { ...options, interceptors: true}
  }
}

export const request: RequestConfig = {
  requestInterceptors: [ baseURLInterceptor ],
  errorHandler,
};
```

**Comment by effapp** [comment]
> Try to use interceptors, and register it in RequestConfig on app.tsx
> 
> ```
> const baseURLInterceptor = (url: null | string, options: RequestOptionsInit) => {
>   return {
>     url: `http://test${url}`,
>     options: { ...options, interceptors: true}
>   }
> }
> 
> export const request: RequestConfig = {
>   requestInterceptors: [ baseURLInterceptor ],
>   errorHandler,
> };
> ```

你好，按照例子配置了拦截器后，.net core webapi接收不到参数了，这是怎么回事呢？
umi 3.2.3
pro 5.1

**Comment by xiaohuoni** [comment]
> configure [proxy](https://umijs.org/config/#proxy) in `config/config.js`

这是正解

**Comment by WLyKan** [comment]
> configure [proxy](https://umijs.org/config/#proxy) in `config/config.js`

注意：proxy 配置仅在 dev 时生效。

**Comment by zqran** [comment]
> 在 app.ts 里面设置 prefix 就好了，https://umijs.org/plugins/plugin-request#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE
> 
> ```
> export const request = {
>   prefix: '', // 这里
>   errorHandler: (error: ResponseError) => {
>     // 集中处理错误
>     console.log(error);
>   },
> };
> ```

umi 的 @umijs/plugin-request 文档中提到了一句话：`除了 errorConfig 和 middlewares 以外其它配置都是直接透传 umi-request 的全局配置`，所以，这个用法应该是从这里来的吧。

但是，如果有 axios 使用经验的人来看，应该会想到用*请求拦截器*来处理，比如下面的示例：

```ts
// app.ts 中：
export const request: RequestConfig = {
  errorHandler: (error: any) => {},
  requestInterceptors: [
    (url, options) => {
      return {
        url,
        options: {
          ...options,

          // 注意：此处无效！
          prefix: 'http://xxx.com/',
        },
      }
    },
  ],
}
```
注意：这种用法无效！正确方式是 @xiaohuoni  上面提到，直接加给 request 对象，而不是加给请求拦截器的 options。

虽然这种用法无效，但是，TS 类型却允许！因为 options 的类型是：`RequestOptionsInit`，该接口类型中定义了 `prefix`

这就是让人迷惑的地方！既然请求拦截器中的 prefix 无效，是不是可以在类型上严谨一些~ 避免一些误导~

**Comment by snyang** [comment]
可以在请求拦截器中使用 `baseURL`
```ts
export const request: RequestConfig = {
  requestInterceptors: [
    (url, options) => {
      options.baseURL = 'http://127.0.0.1:8080';
      return { url, options };
    },
  ],
};
````
