### ISSUE TITLE
关于上传问题请教

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-pro#4108]
系统在文档管理模块下选择文件上传后，切换页面不影响正在上传的文件，这些上传中的文件统一放到一个系统全局容器中，可以查看上传进度，功能类似google云盘
![image](https://user-images.githubusercontent.com/20501316/56873652-7b56b800-6a66-11e9-8110-7c5305d713f9.png)

现在用Antd的Upload组件不知道如何实现，有没有大神能给点思路，谢谢！

**Comment by chenshuai2144** [comment]
在 loayout 中注册一个上传组件好了，上传切换路由本身就不会打断，但是界面和事件被注销了。

**Comment by WangJM001** [comment]
我在文档模块下通过按钮触发了文件上传，怎么把这些信息放到我layout中的组件中了，Upload组件有什么方法支持么

**Comment by chenshuai2144** [comment]
和 Upload 无法的 ，上传应该是一种状态，你可以用 redux 来传递

**Comment by WangJM001** [comment]
谢谢，我先试试
