### ISSUE TITLE
新克隆下来安装依赖，husky报错，无法启动 FailureMessage Object: 000000A9E7EFD330

### ISSUE THREAD

**Issue by hayderGo** [ant-design/ant-design-pro#4109]
安装时的报错信息如下，主要应该是 **65667** 开始
- 65656 warn bizcharts-plugin-slider@2.1.1-beta.1 requires a peer of bizcharts@>=3.2.3 but none is installed. You must install peer dependencies yourself.
- 65657 warn react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
- 65658 warn react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
- 65659 warn eslint-config-react-app@3.0.8 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
- 65660 warn babel-plugin-dva-hmr@0.4.1 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
- 65661 warn rollup-plugin-babel@4.3.2 requires a peer of rollup@>=0.60.0 <2 but none is installed. You must install peer dependencies yourself.
- 65662 warn rollup-plugin-commonjs@9.3.4 requires a peer of rollup@>=0.56.0 but none is installed. You must install peer dependencies yourself.
- 65663 warn chai-as-promised@7.1.1 requires a peer of chai@>= 2.1.2 < 5 but none is installed. You must install peer dependencies yourself.
- 65664 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
- 65665 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
- 65666 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
- 65666 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
- 65666 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
- 65666 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
- 65667 verbose stack Error: husky@1.3.1 install: `node husky install`
- 65667 verbose stack Exit status 3221225477
- 65667 verbose stack     at EventEmitter.<anonymous> (D:\Dev\nvm\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
- 65667 verbose stack     at EventEmitter.emit (events.js:196:13)
- 65667 verbose stack     at ChildProcess.<anonymous> (D:\Dev\nvm\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
- 65667 verbose stack     at ChildProcess.emit (events.js:196:13)
- 65667 verbose stack     at maybeClose (internal/child_process.js:1000:16)
- 65667 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
- 65668 verbose pkgid husky@1.3.1
- 65669 verbose cwd D:\Project\my-project
- 65670 verbose Windows_NT 10.0.17763
- 65671 verbose argv "D:\\Dev\\nodejs\\node.exe" "D:\\Dev\\nvm\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
- 65672 verbose node v12.0.0
- 65673 verbose npm  v6.9.0
- 65674 error code ELIFECYCLE
- 65675 error errno 3221225477
- 65676 error husky@1.3.1 install: `node husky install`
- 65676 error Exit status 3221225477
- 65677 error Failed at the husky@1.3.1 install script.
- 65677 error This is probably not a problem with npm. There is likely additional logging output above.
- 65678 verbose exit [ 3221225477, true ]

npm start启动时报错如下
![002](https://user-images.githubusercontent.com/23020389/56874262-62043a80-6a6b-11e9-89b4-eddb9cc96ab9.png)

**Comment by chenshuai2144** [comment]
试试用 cnpm 呢

**Comment by hayderGo** [comment]
> 试试用 cnpm 呢
我刚尝试删除node_modules，切换用了v10.15.3版本的node，重新install后能够跑通了，和node版本有关系？

**Comment by chenshuai2144** [comment]
最好最新的
