### ISSUE TITLE
[V4] v4 加入菜单以后点击无效

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4110]
如图，加入路由配置以后，点击菜单，界面不跳转。
![image](https://user-images.githubusercontent.com/24469601/56890325-b7603c00-6aab-11e9-91fe-b9597efe4fcb.png)

**Comment by chenshuai2144** [comment]
v4 该需要进行一些修改才能使用。
建议你等一等

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4130
来看一下
