### ISSUE TITLE
help!Error: Loading chunk 8 failed.

### ISSUE THREAD

**Issue by shenyiling** [ant-design/ant-design-pro#4111]
添加新菜单路由后，打包部署后找不到部分js文件，
![image](https://user-images.githubusercontent.com/25818722/56939576-b37bfa80-6b3b-11e9-91bb-4fd1fefb846d.png)
该文件直接通过url访问也是能看到源码的，本地运行正常，取消该菜单后部署也是正常的，之前页面组件用js写的，新的页面用ts写的，请问是哪里配置不对吗？thanks!

**Comment by shenyiling** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个看起来是加载 page 的 js 错误了。考虑一下刷新缓存

**Comment by shenyiling** [comment]
not work...看了下  部署文件夹下 是有这些js文件的。不知道为啥加载不出来，删掉新的菜单就好了，奇了怪了。。。555

**Comment by chenshuai2144** [comment]
缓存了吧，你开了 pwa 吗？

**Comment by shenyiling** [comment]
注释掉pwa 清理了缓存了 一样的啊0v0

**Comment by shenyiling** [comment]
确实是缓存文件的问题，前面没有清理干净！！My fault,多谢 @chenshuai2144
