### ISSUE TITLE
Dashboard中子菜单切换控制台报错

### ISSUE THREAD

**Issue by TSywan** [ant-design/ant-design-pro#4112]
npm start运行项目时，在Dashboard中子菜单来回切换，控制台会报一些错误
有时会打印这个
![image](https://user-images.githubusercontent.com/26398012/56940042-9b59aa80-6b3e-11e9-9f7f-918bdaa6ab4a.png)
有时就是
`
Uncaught TypeError: Cannot read property 'forceFit' of null

    at ResizeObserver.<anonymous> (BizCharts.js:51312)

    at d (BizCharts.js:56295)

    at S (BizCharts.js:56342)

    at M (BizCharts.js:56330)`

倒是不耽误项目运行，就是想知道为什么:smile:

**Comment by chenshuai2144** [comment]
emmm,这个是我的锅，具体可以看这个 pr。
https://github.com/alibaba/BizCharts/pull/807

**Comment by TSywan** [comment]
> emmm,这个是我的锅，具体可以看这个 pr。
> [alibaba/BizCharts#807](https://github.com/alibaba/BizCharts/pull/807)

没事，期待早日更新 :smile::smile:

**Comment by chenshuai2144** [comment]
fixed

**Comment by afc163** [comment]
Fixed in #4209
