### ISSUE TITLE
请问改成hash模式后登录#前面要带一个问号是什么机制

### ISSUE THREAD

**Issue by MangGoDio** [ant-design/ant-design-pro#4113]
http://localhost:8000/#/user/login
如果用之前的登录地址登录成功后调用router跳转至工作台
然后会立马跳转至登录页并生成带问号的URL
http://localhost:8000/?#/user/login
如果直接用这个带问号的URL登录就不会跳转是能正常登录的

**Comment by shenyiling** [comment]
登陆按钮使用的submit类型的button？如果是的话，应该是form的action没有设置地址，之前有遇到过。

**Comment by MangGoDio** [comment]
> 登陆按钮使用的submit类型的button？如果是的话，应该是form的action没有设置地址，之前有遇到过。

确实是这个问题，非常感谢！

**Comment by wanderers-blip** [comment]
在onSubmit的方法里加这句 e.preventDefault();
