### ISSUE TITLE
 UMI SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by jieliu218** [ant-design/ant-design-pro#4116]
Create react app  + Ant design pro 

Jest test

 Details:

    /Users/****/Desktop/project/***/***/*****/node_modules/umi/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as Link } from './lib/link';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

**Comment by chenshuai2144** [comment]
try update your node.js

**Comment by chenshuai2144** [comment]
rm umi/link in  src/components/Ellipsis/index.test.js

**Comment by EvgenyOrekhov** [comment]
@chenshuai2144 There is no `umi/link` in [src/components/Ellipsis/index.test.js](https://github.com/EvgenyOrekhov/ant-design-pro/blob/e04bb9aeb78e7a4894f1dad76fe08d4a89d47618/src/components/Ellipsis/index.test.js).

The problem is that it is impossible to test components that use `umi/link` or `umi/router`.

**Comment by jieliu218** [comment]
@chenshuai2144 Exactly, the problem is that it is impossible to test components that use umi/link or umi/router.

The solution I used at the moment is import css manually like: 

import Login from 'ant-design-pro/lib/Login';
import 'ant-design-pro/lib/Login/style';

This way can pass in Jest. 

@EvgenyOrekhov

**Comment by chenshuai2144** [comment]
已经过时了 v4 中没有这些文件了

**Comment by petro-shkuratenyuk** [comment]
why was this issue closed? where is description of its solution???

**Comment by vadymhimself** [comment]
still have the same issue in 3.5.36
