### ISSUE TITLE
ant design pro注销再登录后页面问题

### ISSUE THREAD

**Issue by kwladmin** [ant-design/ant-design-pro#4120]
pro 点击管理员用户权限的页面菜单  然后注销再登录普通用户时  还是之前未注销时的管理员页面

**Comment by TSywan** [comment]
pro里边注销登录后再次登录后会跳转到退出页面，可以在login中将它注释掉就可以了

**Comment by xhuanlee** [comment]
不知道是不是和我一样的问题:
现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单；

**Comment by kwladmin** [comment]
models  /login方法 里面修改自己判断




------------------ 原始邮件 ------------------
发件人: "xhuanlee"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午2:14
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "asd"<1141918803@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] ant design pro注销再登录后页面问题 (#4120)




不知道是不是和我一样的问题:
 现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单；

**Comment by 160905** [comment]
> 不知道是不是和我一样的问题:
> 现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单；

兄弟你的问题和我一样请看:

[https://github.com/ant-design/ant-design-pro/issues/4139](url)

**Comment by kwladmin** [comment]
已经解决了
在登录的models那里加判断就好了


------------------ 原始邮件 ------------------
发件人: "zzn"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 晚上11:09
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "asd"<1141918803@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] ant design pro注销再登录后页面问题 (#4120)



 
不知道是不是和我一样的问题:
 现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单；
  
兄弟你的问题和我一样请看:
 
https://github.com/ant-design/ant-design-pro/issues/4139

**Comment by 160905** [comment]
> 已经解决了 在登录的models那里加判断就好了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "zzn"<notifications@github.com>; 发送时间: 2019年5月7日(星期二) 晚上11:09 收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>; 抄送: "asd"<1141918803@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [ant-design/ant-design-pro] ant design pro注销再登录后页面问题 (#4120) 不知道是不是和我一样的问题: 现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单； 兄弟你的问题和我一样请看: #4139 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

你的这个问题 我知道什么原因 就是退出时 记录了当前页面的 pathname 在登录时重定向了

**Comment by 160905** [comment]
> 不知道是不是和我一样的问题:
> 现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单；

你这个问题 解决了 吗

**Comment by chenshuai2144** [comment]
dispatch 一下 menu 就能解决这个问题。
https://github.com/ant-design/ant-design-pro/blob/fbeb545a0fd050e701924cba4b8889398e474525/src/layouts/BasicLayout.js#L58

**Comment by pkaq** [comment]
> > 不知道是不是和我一样的问题:
> > 现象：管理员登录，显示的菜单是管理员的菜单，退出，再用普通用户登录，显示的还是管理员菜单，浏览器刷新显示普通用户菜单；
> 
> 你这个问题 解决了 吗

https://github.com/dvajs/dva/issues/907
