### ISSUE TITLE
BizChats  Cannot read property 'forceFit' of null

### ISSUE THREAD

**Issue by TnWah** [ant-design/ant-design-pro#4122]
![image](https://user-images.githubusercontent.com/27721311/57190663-7eaedf80-6f4f-11e9-8474-ef74c6a463a7.png)
官方demo就有这个报错

**Comment by TnWah** [comment]
虽然好像没有影响功能

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4112

**Comment by afc163** [comment]
Fixed in #4209
