### ISSUE TITLE
pro2.2.1登录页报错：[app.model] namespace should be unique

### ISSUE THREAD

**Issue by huagnshiren2014** [ant-design/ant-design-pro#4123]
![image](https://user-images.githubusercontent.com/22445536/57191891-18c95480-6f5d-11e9-881f-3f404d198887.png)
项目原来是在Pro1.3写的，现在迁移到pro2.2.1，五一前还是好好的，节后回来就报这个错误，登录框出不来没法登录，手动在localstorage添加token可以正常访问网页，build后放到测试上登录页没有问题，怎么解决这个问题呢？

**Comment by yutingzhao1991** [comment]
再继续检查下 model 的 namespace 吧，umi 的插件会默认把 models 下的文件都当做 model，如果没有指定 namespace 的话会用文件名作为 namespace。

**Comment by huagnshiren2014** [comment]
> 再继续检查下 model 的 namespace 吧，umi 的插件会默认把 models 下的文件都当做 model，如果没有指定 namespace 的话会用文件名作为 namespace。

和同事已经检查了几遍了，models文件夹下文件的namespace和文件名都相同，主要是节前都没有问题，也没有代码的更改

**Comment by chenshuai2144** [comment]
你是不是用了什么特殊的 namespace 
比如 global 之类的

**Comment by huagnshiren2014** [comment]
> 你是不是用了什么特殊的 namespace
> 比如 global 之类的

确实是有一个global，ant-design-pro提供的，这个有影响吗？

**Comment by chenshuai2144** [comment]
应该不影响。redux 不会提示是哪个冲入也是个问题

**Comment by huagnshiren2014** [comment]
> 应该不影响。redux 不会提示是哪个冲入也是个问题

是啊，提示太简单了，无法定位问题，快要崩溃了

**Comment by chenshuai2144** [comment]
你找到问题了吗

**Comment by huagnshiren2014** [comment]
找到了，确实是有重复的namespace，项目升级ant-design-pro留下来的bug

陈帅 <notifications@github.com> 于2019年6月24日周一 下午3:02写道：
