### ISSUE TITLE
Upload组件获取http响应状态码

### ISSUE THREAD

**Issue by haozhenwei** [ant-design/ant-design-pro#4125]
在使用Upload组件上传文件时，服务端可能会返回一个非200的状态码，且要求对不同的响应状态码进行不同的处理。目前想了解如何获取在文件上传时服务端的响应状态码？谢谢

**Comment by chenshuai2144** [comment]
那你可以能需要[手动上传](https://ant.design/components/upload-cn/#components-upload-demo-upload-manually)

**Comment by haozhenwei** [comment]
好的，谢谢，我先试试

**Comment by haozhenwei** [comment]
在错误情况下，可根据file.error.status字段获取http响应状态码
