### ISSUE TITLE
关于less中的className对应Component的问题

### ISSUE THREAD

**Issue by KiritoStudio** [ant-design/ant-design-pro#4126]
你好，我想问一下less文件下的那些className是怎么对应到component的？
比如 https://github.com/ant-design/ant-design-pro/blob/master/src/pages/List/TableList.less 中的ant-form-item，ant-form-item-label，ant-form-item-control是怎么对应到对应的component去的？在项目中搜了一下文本只搜索到less文件

**Comment by chenshuai2144** [comment]
ant-form-item-control ant-form-item-label 这些都是 antd 的 classname。
我猜你想了解的是 css-modlue

**Comment by KiritoStudio** [comment]
我看一下，非常感谢
