### ISSUE TITLE
权限存储在 localstorage

### ISSUE THREAD

**Issue by 160905** [ant-design/ant-design-pro#4128]

**Comment by chenshuai2144** [comment]
？ 你想表达什么不安全吗？

**Comment by 160905** [comment]
刚才没写完呢就提交了.

我觉得不是很安全啊 如果手动修改存入的值会影响实际的权限控制

**Comment by dmdoit** [comment]
> 刚才没写完呢就提交了.
> 
> 我觉得不是很安全啊 如果手动修改存入的值会影响实际的权限控制

没关系啊，后端会去验证请求的权限的

**Comment by chenshuai2144** [comment]
前端的请求只能展示一下界面而已。操作的权限都是后端为准的。即使是 get 请求。
localstorage 存储只是因为 pro 没有后端

**Comment by 160905** [comment]
那我明白了
最终的鉴权还是后端

**Comment by chenfd99** [comment]
如何不从localstorage  而从currentUser中获取用户的权限呢
