### ISSUE TITLE
本地运行怎么safrai浏览器首页都浏览不了！！

### ISSUE THREAD

**Issue by songxh2** [ant-design/ant-design-pro#413]
[今天版本更新后，safrai浏览器首页都浏览不了！！
![1513043114320](https://user-images.githubusercontent.com/3102495/33863118-3596f266-df21-11e7-89a8-31bbf496de51.jpg)

**Comment by nikogu** [comment]
我这边看的没问题，提供下报错信息之类的吧

**Comment by songxh2** [comment]
看图片

**Comment by chenshuai2144** [comment]
环境问题吧 ,我们项目里面没有使用过eval,试试重装环境

**Comment by songxh2** [comment]
我删除项目后又重新下载antd pro了，在项目环境npm install后仍然出现这个问题，难道是我的npm global环境出问题了？
![1513043288325](https://user-images.githubusercontent.com/3102495/33863407-7fe97f72-df22-11e7-8361-b67028d2d12b.jpg)

**Comment by songxh2** [comment]
chrome 浏览没有问题

**Comment by chenshuai2144** [comment]
神奇....我也找个mac去看看

**Comment by songxh2** [comment]
eval 估计是工具生成的js代码吧

**Comment by songxh2** [comment]
https://preview.pro.ant.design/  这个远程地址 safari能看的

**Comment by afc163** [comment]
和 https://github.com/ant-design/ant-design-pro/issues/210 问题一样，safari 版本估计太老了。

**Comment by songxh2** [comment]
这个safari版本又多老？是否是safari浏览器本地浏览权限问题？
![wx20171212-101144](https://user-images.githubusercontent.com/3102495/33863881-ef9d0148-df24-11e7-8b4a-ff5d96c42001.png)

**Comment by songxh2** [comment]
但 https://preview.pro.ant.design/ 这个远程地址 safari能看的，就本地看不了？怎么解释？

**Comment by afc163** [comment]
请阅读和跟踪 #210，一样的问题。
