### ISSUE TITLE
在models里怎么取到401报错的信息

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design-pro#4131]
登录接口，输入错误的用户名密码，后台返回401错误，
我想把后台返回的提示：“用户名错误”或“密码错误”显示在前端页面，内容如下：

![image](https://user-images.githubusercontent.com/19385704/57217215-93a97280-7024-11e9-91eb-f2a2a73f5c7c.png)

![image](https://user-images.githubusercontent.com/19385704/57217322-dcf9c200-7024-11e9-8cd2-8ed169b9864d.png)

![image](https://user-images.githubusercontent.com/19385704/57217580-96f12e00-7025-11e9-9792-b5d6f3f8ba77.png)

**问题**
**在login的models里response是**undefined**，我要怎么拿到这个401的错误信息**

![image](https://user-images.githubusercontent.com/19385704/57217810-3adad980-7026-11e9-8fc0-c3d83bc2c4ca.png)

**Comment by chenshuai2144** [comment]
errorHandler 中 处理了401.
你可以处理之后继续返回  error.类似这样
```js
const errorHandler = error => {
 ....something
 return error;
};
```

**Comment by dmdoit** [comment]
> [errorHandler](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js) 中 处理了401.
> 你可以处理之后继续返回 error.类似这样
> 
> ```js
> const errorHandler = error => {
>  ....something
>  return error;
> };
> ```

返回的response 要取到后端返回数据里的message是这样处理吗？
> ```js
> response.json().then(res => {  })
> ```
这里是一个Promise ，有没有其他方法可以更快捷的取到response里的后端message信息呢

**Comment by chenshuai2144** [comment]
直接request中处理，或者登陆错误就不要给401 给个200.然后说明原因

**Comment by Lind-pro** [comment]
@chenshuai2144  那意思是在models中是无法处理除了200以外的错误吗？难道不应该谁调用谁处理异常吗？怎么可以做到谁调用谁处理？

**Comment by chenshuai2144** [comment]
删除掉 request 中的错误处理就好了。

**Comment by dongkeng001** [comment]
> [errorHandler](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js) 中 处理了401.
> 你可以处理之后继续返回 error.类似这样
> 
> ```js
> const errorHandler = error => {
>  ....something
>  return error;
> };
> ```

发布测试环境上，登录接口请求成功，并且状态码都是200的，不知道为什么会进去errorHandler方法里面提示请求错误，本地开发环境却没问题，请问这是什么原因呢
