### ISSUE TITLE
login redirect issue

### ISSUE THREAD

**Issue by leegang79** [ant-design/ant-design-pro#4134]
ant-design-pro/src/models/login.js

Sometimes url been encoded, like:
http://localhost:8010/user/login?redirect=http%3A%2F%2Flocalhost%3A8000%2Fdashboard

This will cause redirect failed after login, user need click multi times to get login success.

```
        let { redirect } = params;
        if (redirect) {
          {/* add below line */}
          redirect = decodeURI(redirect);

```

Should add decodeURL line to make sure redirect success after each time login.

**Comment by chenshuai2144** [comment]
在 block 中 增加一个pr？
