### ISSUE TITLE
在Login组件中如果过滤Mobile组件空格 

### ISSUE THREAD

**Issue by wqjiao** [ant-design/ant-design-pro#4136]

**Comment by wqjiao** [comment]
不支持getValueFromEvent方法

**Comment by chenshuai2144** [comment]
submit 的时候再去做呢？

**Comment by wqjiao** [comment]
我在失去焦点时调用了setFieldsValue解决了（onChange时修改控件的值不起作用的）。但是如果这个组件能够暴露类似getValueFromEvent这个方法去修改控件的值就好了，仅仅建议哈

**Comment by chenshuai2144** [comment]
onChange 是不可能用的。最好的办法还是在redux中管理

**Comment by wqjiao** [comment]
嗯嗯，在LoginItem组件中暴露一个getValueFromEvent方法是可以的
