### ISSUE TITLE
dependence electron in the project?

### ISSUE THREAD

**Issue by fishenal** [ant-design/ant-design-pro#4137]
npm install will install a 50.33MB electron, I want to know which dependence use this?

**Comment by chenshuai2144** [comment]
Are  Puppeteer?

**Comment by fishenal** [comment]
ok, I think it's from `nightmare`

**Comment by fishenal** [comment]
> Are Puppeteer?

yes, v2 is puperteer, v1 i used is nightmare, 
I dont understand why default install optional dependency
