### ISSUE TITLE
如何控制yield call异步请求的顺序

### ISSUE THREAD

**Issue by sunfutao** [ant-design/ant-design-pro#4138]
![TIM图片20190507115019](https://user-images.githubusercontent.com/35865208/57270570-83de6c80-70be-11e9-89b1-fc85c290dcb7.png)

如上图想要控制2在1之后发起请求

**Comment by dmdoit** [comment]
请问你是怎么处理的呢？

**Comment by chenshuai2144** [comment]
[yield](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/yield)  本身就是同步的。
