### ISSUE TITLE
菜单更新问题

### ISSUE THREAD

**Issue by 160905** [ant-design/ant-design-pro#4139]
![企业微信20190507023950](https://user-images.githubusercontent.com/22002759/57277103-04f52e00-70d6-11e9-9d40-271388313cf3.png)

这个componentDidMount 在更换另一个账户登录时，不会触发执行导致菜单没有更新过来 需要手动刷新一下才会更新

**Comment by 160905** [comment]
`const {
      dispatch,
      route: { routes, path, authority },
    } = this.props;`

这里的 routes 在 model 模块中无法获取到

不知道你遇到过这个问题没有

`// yield put(routerRedux.push(redirect || '/'));`
` window.location.href = `${window.location.origin}${redirect || '/'}`

目前我才用这这种方式

**Comment by chenshuai2144** [comment]
都是一个state 是可以在modal中获得的

**Comment by 160905** [comment]
在modal中真的无法获取到 routes

**Comment by 160905** [comment]
![企业微信20190507031138](https://user-images.githubusercontent.com/22002759/57278978-6fa86880-70da-11e9-82ec-b55d47101886.png)




这是我刚起的服务

model没有找到 routes

**Comment by 160905** [comment]
![企业微信20190507044212](https://user-images.githubusercontent.com/22002759/57286062-1b57b580-70e7-11e9-9a8a-cec4088d93d1.png)

 这里我拿到 了routes 下面的警告意思是必须 在组建 mounted后  在 model 还是不行啊
locale.js:35 [umi-plugin-locale] formatMessage not initialized yet, you should use it after react app mounted.

**Comment by TSywan** [comment]
获取routes 生成菜单 这个是根据你router.config.js中配置生成的
![{1D908661-2BF5-4B89-B1F5-40E6B00808D5}_20190507165617](https://user-images.githubusercontent.com/26398012/57288369-e9951d80-70eb-11e9-9b2b-56e68ac4a5e4.jpg)
![{A392649F-CB8D-402A-B5DC-2D6D7058CC65}_20190507165510](https://user-images.githubusercontent.com/26398012/57288403-fade2a00-70eb-11e9-9b31-93a13b56ee92.jpg)

如果你要从后台获取菜单 可以这样请求 
![{4B249EE9-2682-4AED-8880-9E634C96ADD8}_20190507170050](https://user-images.githubusercontent.com/26398012/57288444-0df0fa00-70ec-11e9-86ba-0fa18c7a2aa7.jpg)

这样就会根据后台返回给你的数据生成不同的侧边栏菜单

**Comment by 160905** [comment]
> 获取routes 生成菜单 这个是根据你router.config.js中配置生成的
> ![{1D908661-2BF5-4B89-B1F5-40E6B00808D5}_20190507165617](https://user-images.githubusercontent.com/26398012/57288369-e9951d80-70eb-11e9-9b2b-56e68ac4a5e4.jpg)
> ![{A392649F-CB8D-402A-B5DC-2D6D7058CC65}_20190507165510](https://user-images.githubusercontent.com/26398012/57288403-fade2a00-70eb-11e9-9b31-93a13b56ee92.jpg)
> 
> 如果你要从后台获取菜单 可以这样请求
> ![{4B249EE9-2682-4AED-8880-9E634C96ADD8}_20190507170050](https://user-images.githubusercontent.com/26398012/57288444-0df0fa00-70ec-11e9-86ba-0fa18c7a2aa7.jpg)
> 
> 这样就会根据后台返回给你的数据生成不同的侧边栏菜单




你没理解我遇到的问题

我的菜单不是通过后台数据生成的 是本地的

问题是: 两个不用角色的用户在切换登录时 最后一个登录的用户 不会执行baselayout 里的 componentDidMount钩子, 导致菜单不能实时更新,

所以我目前的解决方式是在登录后通过这种 `window.location.href =${window.location.origin}${redirect || '/'}`  登录到首页

**Comment by TSywan** [comment]
好像这个本地菜单列表的显示是根据每个路由的authority权限来生成的，不同的权限生成不同的菜单；
我刚才分别测试了一下admin用户登录和user用户登录，生成的是不同的侧边栏菜单，倒是没有出现你说的 componentDidMount钩子不执行的情况；

**Comment by 160905** [comment]
![企业微信20190507081340](https://user-images.githubusercontent.com/22002759/57298381-a5624700-7104-11e9-9983-aa56e336e583.png)


大致找到原因了

是每个菜单的 children 没有重新生成

至于为什么还不是很清楚

**Comment by pkaq** [comment]
确实是这样

**Comment by mengyang1229** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn
