### ISSUE TITLE
React16的componentDidCatch无法正常捕获到错误信息

### ISSUE THREAD

**Issue by longzhaobi** [ant-design/ant-design-pro#414]
我抛出一个异常信息：Error msg，捕获到的却是：Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.

我后来使用create-react-app脚手架创建的项目能正常捕获到错误信息。
用dva-cli创建了一个也无法捕获到，是不是dva的问题？

**Comment by chenshuai2144** [comment]
应该是 [roadhog ](https://github.com/sorrycc/roadhog)的问题...
去那边提问吧.

**Comment by longzhaobi** [comment]
@chenshuai2144 谢谢，去那边提问了。。
