### ISSUE TITLE
路由太多导致登录慢

### ISSUE THREAD

**Issue by luyunzi** [ant-design/ant-design-pro#4140]
路由文件router.js中随着功能越来越多配置路由太多时，会导致登录非常慢，因为登录前会配置路由表花费很长时间，请问有什么优化办法吗？

**Comment by chenshuai2144** [comment]
路由是在编译的时候确定的，
你的问题是菜单太多造成的渲染缓慢吗？

**Comment by luyunzi** [comment]
> 路由是在编译的时候确定的，
> 你的问题是菜单太多造成的渲染缓慢吗？

就是编译时间太久吧，点击登录后会停留在登录页面很长时间，路由减少会好很多。希望能够根据用户动态配置路由，而不是每次登录都是编译全量路由。

**Comment by chenshuai2144** [comment]
这个不可能的，router 的本质是源码。如果你的项目实在是非常大的话，可以尝试一下拆分项目。
> 点击登录后会停留在登录页面很长时间

用 devtools 监控一下什么东西在浪费时间，页面出来之后不应该会继续加载路由的

**Comment by luyunzi** [comment]
> 这个不可能的，router 的本质是源码。如果你的项目实在是非常大的话，可以尝试一下拆分项目。
> 
> > 点击登录后会停留在登录页面很长时间
> 
> 用 devtools 监控一下什么东西在浪费时间，页面出来之后不应该会继续加载路由的

那怎么解释路由注掉部分速度会变快呢，登录之后首页加载之前过程不知道什么地方在耗时，大概15s以上，定位好像不在页面上。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/0bbbcc72633ed744950bd830e1bbd8df6dd53665/config/config.js#L28
开启这个试试。最好用控制台看看在干什么，是不是有什么路由依赖了异步的逻辑

**Comment by luyunzi** [comment]
> https://github.com/ant-design/ant-design-pro/blob/0bbbcc72633ed744950bd830e1bbd8df6dd53665/config/config.js#L28
> 
> 
> 开启这个试试。最好用控制台看看在干什么，是不是有什么路由依赖了异步的逻辑

1.0没有config.js这个文件呢，要怎么开启异步呢

**Comment by chenshuai2144** [comment]
1.0可能无法开启。。。 
看看腾讯这篇 http://www.alloyteam.com/2016/02/code-split-by-routes/
