### ISSUE TITLE
为什么一刷新页面,state中的数据就没有了

### ISSUE THREAD

**Issue by wj15510151110** [ant-design/ant-design-pro#4141]
例如我登录成功之后想保存登录信息,然后保存state中,在所有页面共享这个数据,可是一刷新页面,这些数据就清空了.基本所有的数据,只要一刷页面就会消失,为什么啊,大神请指教

**Comment by uv-w** [comment]
因为都是存的内存里呀  刷一下  内存清啦

**Comment by wj15510151110** [comment]
> 因为都是存的内存里呀 刷一下 内存清啦

我记得可以持久化的啊,以前没用dva 的时候,只用Redux的时候,怎么刷新都没事的啊,

**Comment by chenshuai2144** [comment]
> 我记得可以持久化的啊，以前没用 dva 的时候，只用 Redux 的时候，怎么刷新都没事的啊，

有这么强的方案吗？求推荐

**Comment by wj15510151110** [comment]
> > 我记得可以持久化的啊，以前没用 dva 的时候，只用 Redux 的时候，怎么刷新都没事的啊，
> 
> 有这么强的方案吗？求推荐

redux-persist

**Comment by chenshuai2144** [comment]
这个只能存 redux。如果能存 react 就牛逼了
