### ISSUE TITLE
提交代码时/scripts/lint-prettier.js报错

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design-pro#4142]
0 files committed, 1 file failed to commit: 测试 husky > pre-commit (node v8.11.3) > ant-design-pro@2.3.1 lint-staged /Users/fengran/projectKing/gateway/gateway_web > lint-staged Stashing changes... [started] Stashing changes... [skipped] → No partially staged files found... Running linters... [started] Running tasks for **/.less [started] Running tasks for **/.{js,jsx} [started] Running tasks for **/.{js,ts,tsx,json,jsx,less} [started] Running tasks for **/.less [skipped] → No staged files match **/.less npm run lint-staged:js [started] node ./scripts/lint-prettier.js [started] node ./scripts/lint-prettier.js [failed] → Running tasks for **/.{js,ts,tsx,json,jsx,less} [failed] → npm run lint-staged:js [completed] Running tasks for **/*.{js,jsx} [completed] Running linters... [failed] ✖ node ./scripts/lint-prettier.js found some errors. Please fix them and try committing again. /Users/fengran/projectKing/gateway/gateway_web/scripts/lint-prettier.js:44 .finally(() => { ^ TypeError: Promise.all(...).then(...).catch(...).finally is not a function at files.forEach.file (/Users/fengran/projectKing/gateway/gateway_web/scripts/lint-prettier.js:44:13) at Array.forEach ( ) at Object. (/Users/fengran/projectKing/gateway/gateway_web/scripts/lint-prettier.js:18:7) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Function.Module.runMain (module.js:693:10) at startup (bootstrap_node.js:191:16) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! ant-design-pro@2.3.1 lint-staged: lint-staged npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the ant-design-pro@2.3.1 lint-staged script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! /Users/fengran/.npm/_logs/2019-05-07T10_55_07_817Z-debug.log husky > pre-commit hook failed (add --no-verify to bypass)

**Comment by chenshuai2144** [comment]
升级一下 node.js 的版本。到 10 就可以。

.finally 这个支持的比较晚。
