### ISSUE TITLE
关于使用dva model结合blob类型实现文件下载的问题

### ISSUE THREAD

**Issue by SnoozeWtg** [ant-design/ant-design-pro#4144]
### 求助！ 使用window.URL.createObjectURL(blob)在chrome浏览器中下载文件超过1800M报错：内存不足，render process gone ，求大佬指点一下，找不到解决办法，或者antd pro文件下载的推荐做法是哪种呢？如何处理跨域，前后端分离的问题？

详细描述如下：

本人java后端，需要在antd pro中实现常见的下载功能，搜索了issues和博客之后，找到几种方式：

- 1.使用window.open()打开下载链接
- 2.使用window.location.href='下载链接'
- 3.http请求时设置responseType : 'blob'让后端返回blob数据，再使用window.URL.createObjectURL(blob)下载文件

由于项目前后端分离，开发时又启用了本地代理，1，2两种方式应该会存在跨域等其他问题，所以尝试使用第3种方式实现，感觉会优雅一点（前端菜鸟感觉可能不太靠谱：）。。）

实现步骤：

- service中定义请求，设置返回类型为blob：
```
export async function download(params){
  return request(`/api/knowledge/download?${stringify(params)}`,{responseType : 'blob'});
}
```

- model effects中定义两个方法实现下载：
```
effects: {

*download({ payload }, { call, put }) {
      const response = yield call(download, payload);
      yield put({
        type: 'saveFile',
        payload: { blob: response, fileName: 'downLoadFileName' },
      });
    },

saveFile({ payload: { blob, fileName } }) {
      if (window.navigator.msSaveOrOpenBlob) {
        navigator.msSaveBlob(blob, fileName);
      } else {
        const link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        link.download = fileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }
    },

}
```
- page中定义按钮点击通过dispatch调用*download方法实现下载

### 结果：小文件下载没有问题，但是下载一个3G多的文件时，每次下载到1800多M，chrome崩溃

![截图](https://user-images.githubusercontent.com/20106449/57346807-8e623a00-7182-11e9-88b8-a1a7def24ae9.png)

网上查询找不到相关案例，实现之后发现这种方式除了会导致内存不足的情况外，还存在一个问题，在createObjectUrl的过程中，浏览器没有任何交互提示，下载大文件时体验很不好，暂时没有想办法解决。希望各位能不吝赐教，指点一种好的实现方式，也好给后面issuse搜索相关问题的同学一个参考~

**Comment by chenshuai2144** [comment]
1800m 的文件 应该直接让后端处理完成
然后 window.open 打开一个链接去下载

**Comment by SnoozeWtg** [comment]
@chenshuai2144 谢谢指点~，使用window.open测试了一下，一切顺利，能够被代理转发，不存在跨域问题和其他问题，之前是我想多了，反而挑错了方式。。。
代码如下：
![图片](https://user-images.githubusercontent.com/20106449/57353696-e9545b00-719b-11e9-9aac-854003c4b406.png)

**Comment by dmdoit** [comment]
因为我们导出必须在登录的情况下，所以我选择的你的第一种方式，但是我在 *download 里打印 response 显示的是undefined，

![image](https://user-images.githubusercontent.com/19385704/59591943-974f0f80-9121-11e9-84fe-3fbbf4d5232d.png)

下边是后端返回的数据
![image](https://user-images.githubusercontent.com/19385704/59591988-b188ed80-9121-11e9-93a2-301ed78dac1e.png)

**请问是什么问题呢？**
