### ISSUE TITLE
关于proxy两种环境的问题

### ISSUE THREAD

**Issue by fatefate0727** [ant-design/ant-design-pro#4145]
代码截图：
![@RM@0Q3SAGKL4C6Y(E_A)_A](https://user-images.githubusercontent.com/42198858/57347259-3f1d0900-7184-11e9-8b07-9e86688124b6.png)
![8M@%5{}CY$5BX%MGHUKT NW](https://user-images.githubusercontent.com/42198858/57347261-3fb59f80-7184-11e9-86b7-2e45554ee3ce.png)
![WSDG6Q25YJXH09MG7336Z)6](https://user-images.githubusercontent.com/42198858/57347262-3fb59f80-7184-11e9-8ef9-c735b30f79e3.png)

以上代码在start时可以正常访问，但是在build之后使用，访问EP代理的接口全部返回生成的主页面代码，已多次复现此问题

是否是我这边配置的问题？能否提供一些解决方案

**Comment by chenshuai2144** [comment]
config.js 是 node 环境可以用 环境变量的。

**Comment by fatefate0727** [comment]
@chenshuai2144 业务上来说，这是个集中管理的项目。所以，能否配置多个代理，类似下面这样的
![6A@39FZM76@7L~%ZKGIJPN1](https://user-images.githubusercontent.com/42198858/57359909-73f08680-71ab-11e9-946b-5d05e80889d8.png)

**Comment by chenshuai2144** [comment]
可以的，看这里
https://webpack.js.org/configuration/dev-server/

**Comment by fatefate0727** [comment]
依旧无法在build之后使用

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn
