### ISSUE TITLE
预览地址好像挂了哦，打开空白页

### ISSUE THREAD

**Issue by sunmorg** [ant-design/ant-design-pro#4146]
预览地址好像挂了哦，打开空白页，有报错

**Comment by chenshuai2144** [comment]
没图没真相呀

**Comment by sunmorg** [comment]
![image](https://user-images.githubusercontent.com/36916538/57357375-60dab800-71a5-11e9-83bb-6b4d10c2042a.png)

**Comment by kuhami** [comment]
https://preview.pro.ant.design 没问题啊

**Comment by chenshuai2144** [comment]
你这个缓存的版本非常旧。刷新一把试试

**Comment by sunmorg** [comment]
我刚刚清一遍缓存好了，具体问题不知道是为啥，很久之前看过一次，不知道是不是因为缓存的问题

**Comment by sunmorg** [comment]
感谢
