### ISSUE TITLE
官网 Landing 页命令报错

### ISSUE THREAD

**Issue by Ynewtime** [ant-design/ant-design-pro#4148]
<img width="860" alt="屏幕快照 2019-05-08 17 12 32" src="https://user-images.githubusercontent.com/27655771/57363944-b4a0cd80-71b4-11e9-9a49-240b2e44acf0.png">
<img width="719" alt="屏幕快照 2019-05-08 17 14 48" src="https://user-images.githubusercontent.com/27655771/57364000-d69a5000-71b4-11e9-877f-7364c6045f9e.png">

正确的方式应该是[这里](http://pro.ant.design/docs/getting-started-cn#%E5%AE%89%E8%A3%85)给出的方法，可以更新一下。

**Comment by chenshuai2144** [comment]
权限错误。
这个仓库是公开的仓库，你的 git 有什么特殊的配置吗？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/138

**Comment by chenshuai2144** [comment]
默认修改为 https 方式吧。 我把 landing 也改一下

**Comment by Ynewtime** [comment]
看 Landing 已经修改了，这条 issue 我先关闭了。
