### ISSUE TITLE
使用localhost:8000访问网站会报403错误，使用IP地址正常显示，这是什么回事？

### ISSUE THREAD

**Issue by sipudi** [ant-design/ant-design-pro#4149]
使用localhost:8000访问网站会报403错误，使用IP地址正常显示，这是什么回事？

**Comment by Ynewtime** [comment]
检查一下系统 host 配置，把 localhost 指向到 127.0.0.1

**Comment by sipudi** [comment]
已经指向了，但是运行脚本npm start:no-mock之后就开始出现403报错，无权访问，不是无法访问

**Comment by chenshuai2144** [comment]
dev 环境怎么会有 403。是不是有别的项目监听了 8000

**Comment by sipudi** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/10289155/57422046-042cdb00-7241-11e9-9186-42028674a775.png)

**Comment by sipudi** [comment]
有什么方法可以调试

**Comment by chenshuai2144** [comment]
chrome 看看头信息从哪里来的

**Comment by sipudi** [comment]
![image](https://user-images.githubusercontent.com/10289155/57422475-cd57c480-7242-11e9-927b-d1ece0e763c0.png)

**Comment by sipudi** [comment]
@chenshuai2144 问题已解决了，是由于身份认证失败导致访问后台首页时候报错403（无权访问），在控制台执行localStorage.clear()清除localStorage后就可以正常访问了。
