### ISSUE TITLE
请问fetch 请求发送的是options请求而不是真实的POST获取GET请求

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#415]
问题描述：请问fetch 请求发送的是options请求而不是真实的POST获取GET请求.
使用的是  [ant-design-pro](https://github.com/ant-design/ant-design-pro) 项目下的[utils/request.js](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.js)

![image](https://user-images.githubusercontent.com/12181423/33865753-1ff424f8-df2e-11e7-8141-0d2c267089dd.png)

![image](https://user-images.githubusercontent.com/12181423/33865743-0d3f77ea-df2e-11e7-8a49-a6e509602b28.png)

浏览器请求截图：
![image](https://user-images.githubusercontent.com/12181423/33865796-4df865ee-df2e-11e7-91f5-49f89d51e93e.png)
![image](https://user-images.githubusercontent.com/12181423/33865908-d6ca6e76-df2e-11e7-9fa9-8f0f56e47c15.png)

**Comment by neewbee** [comment]
https://developer.mozilla.org/zh/docs/Web/HTTP/Access_control_CORS

**Comment by afc163** [comment]
跨域了，不是 pro 的问题。

**Comment by luohow** [comment]
要怎么解决？貌似他这个fetch没有相关问题

**Comment by chenshuai2144** [comment]
跨域用代理
