### ISSUE TITLE
可以在ant-design-pro里使用redux-saga吗

### ISSUE THREAD

**Issue by pasBone** [ant-design/ant-design-pro#4150]
因为项目特殊性，需要在ant-design-pro里使用redux-saga等。
![image](https://user-images.githubusercontent.com/18027183/57376275-32bf9d00-71d2-11e9-8649-9c1238a5dfda.png)
目前加了一层provider，但是store里还是读取不到redux的state。
请问怎么能实现目的呢

**Comment by pasBone** [comment]
为了兼容就项目的代码，所以需要在外面引用一次

**Comment by chenshuai2144** [comment]
我们已经带进去了。如果再次加载可能会出问题。
@sorrycc  有快速的迁移方式吗

**Comment by sorrycc** [comment]
引用 redux-saga 的什么方法？

**Comment by pasBone** [comment]
是这样的，项目之前是用的redux-saga,  reducers这些都是分开写的， 现在要换成antd-pro想直接兼容老的代码，就想直接在外层引用redux-saga, 不做大的改动以达到升级的目的 ，但是没有想到好的办法

**Comment by sorrycc** [comment]
那比较麻烦，umi 目前没有提供官方的 redux 插件，有需要可以参考 umi-plugin-dva 实现一个。
