### ISSUE TITLE
跳转路由，滚动条会停在上一个页面的位置，请问有什么整体调整方法么？

### ISSUE THREAD

**Issue by Cancerbin** [ant-design/ant-design-pro#4151]

**Comment by Cancerbin** [comment]
我现在是通过document.getElementById('root').scrollIntoView(true);这句来强制置顶的

**Comment by chenshuai2144** [comment]
这个是浏览器的行为为了提升你的体验，
使用 hash 模式的话严格上来说你的路径并没有改变，浏览器会记住滚动条的位置。

> 我现在是通过document.getElementById('root').scrollIntoView(true);这句来强制置顶的

你找到了正确的解法。

**Comment by Cancerbin** [comment]
> 这个是浏览器的行为为了提升你的体验，
> 使用 hash 模式的话严格上来说你的路径并没有改变，浏览器会记住滚动条的位置。
> 
> > 我现在是通过document.getElementById('root').scrollIntoView(true);这句来强制置顶的
> 
> 你找到了正确的解法。

好的，谢谢您的回答，我只是看到了最新的预览界面没有这种情况，所以想了解一下的。

**Comment by wo-de-ping-er** [comment]
> 我现在是通过document.getElementById('root').scrollIntoView(true);这句来强制置顶的

使用这种方案的话   页面跳转会出现刷新无法回到顶部的问题    不知道你是否碰到过？
