### ISSUE TITLE
使用 dva/fetch 后端允许跨域，还是失败

### ISSUE THREAD

**Issue by caogaofeng0** [ant-design/ant-design-pro#4154]
跨域 dva/fetch
前端设置了 mode:'cors', 后端设置了 可以跨域 res.header("Access-Control-Allow-Origin", "*");
还是报错 提示跨域 报错 如下
Access to fetch at 'http://127.0.0.1:3003/json/index.json' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '' when the request's credentials mode is 'include'.

**Comment by chenshuai2144** [comment]
这种情况应该使用代理。header 头有很多，你应该是没有色设置全，或者是 只处理了 get post 请企业

**Comment by caogaofeng0** [comment]
> 这种情况应该使用代理。header 头有很多，你应该是没有色设置全，或者是 只处理了 get post 请求

您好！感谢您的回复，开发环境已经使用了代理，可以使用了。上线版本 怎么做呢？ 是直接在 url 前拼接 后端ip地址和端口吗？ 期待您的回复

**Comment by chenshuai2144** [comment]
线上可以用 nginx 或者 tomcat 之类的容器配置代理。
https://pro.ant.design/docs/deploy-cn
