### ISSUE TITLE
为啥npm run build 放到spring mvc应用下面，左侧导航栏只显示dashboard

### ISSUE THREAD

**Issue by q6413260** [ant-design/ant-design-pro#4163]
![image](https://user-images.githubusercontent.com/11553677/57511034-d2983a80-733a-11e9-8f11-4af07ac6a65f.png)

**Comment by chenshuai2144** [comment]
dev情况下是正常的吗?
可能是默认权限的问题

**Comment by q6413260** [comment]
@chenshuai2144 3q，问题已经解决了
