### ISSUE TITLE
table表格排序功能

### ISSUE THREAD

**Issue by TSywan** [ant-design/ant-design-pro#4165]
我在columns中某一列添加了一个 `sorter: true`, 
![lie](https://user-images.githubusercontent.com/26398012/57513118-13468280-7340-11e9-9c60-b9bb800f26b7.jpg)

然后在页面中点击排序时，顺序一直是` "ascend"  - "descend" - false , `

在页面表格列中出现的 这两个按钮；
![QQ浏览器截图20190510162724](https://user-images.githubusercontent.com/26398012/57513340-92d45180-7340-11e9-8f55-e440c356bd22.png)

每一次第一次点击都是 `ascend` ，即使点击`descend`的按钮也还是 `ascend`, ，并不能像 Ant Design 中 Table 的示例一样；

**Comment by chenshuai2144** [comment]
来个重现的demo

**Comment by TSywan** [comment]
> 来个重现的demo

官网上的表格也是这样

**Comment by chenshuai2144** [comment]
官网上表现是正常的。 你再check一下？

**Comment by TSywan** [comment]
> 官网上表现是正常的。 你再check一下？

我的也可以排序。 主要是我测试的时候第一次点击 `descend` 按钮的时候排序方式是`ascend`，后来在Ant Design官网Table排序示例中点击`descend`按钮排序方式就是`descend`，所以以为是有点问题。 
刚才我去Ant Design 官网仔细看了一下，排序是一样的没有问题。 
不好意思啊 😅 谢谢 @chenshuai2144 大佬的解答😀
