### ISSUE TITLE
官网一片空白

### ISSUE THREAD

**Issue by MakerGYT** [ant-design/ant-design-pro#4167]
pro.ant.design可以加载，但是没有内容

**Comment by chenshuai2144** [comment]
来个报错截图。

**Comment by MakerGYT** [comment]
![image](https://user-images.githubusercontent.com/16568561/57594772-4cffcf00-7574-11e9-92e2-50f0f74909ad.png)

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/2398
