### ISSUE TITLE
breadcrumb.js route.component always be undefined

### ISSUE THREAD

**Issue by thiscallback** [ant-design/ant-design-pro#4169]
`return last || !route.component ? ( // route.component always be undefined
    <span>{route.breadcrumbName}</span>
  ) : (
    <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
  );`

The conditional statement seem to be never goto the 'else' statement.

**Comment by chenshuai2144** [comment]
breadcrumb form config.js.
you can look modal/menu.js

**Comment by thiscallback** [comment]
@chenshuai2144  There is no link(href) on breadcrumb

**Comment by chenshuai2144** [comment]
obsolete
