### ISSUE TITLE
mock proxy的multipart/* form文件上传错误

### ISSUE THREAD

**Issue by yueisme** [ant-design/ant-design-pro#417]
版本：ant-pro 0.3.0

我的服务端是用node-formidable处理文件上传，在使用<Upload/>组件上传的时候抛出错误
`Error: MultipartParser.end(): stream ended unexpectedly: state = START_BOUNDARY`

这是我的配置
![image](https://user-images.githubusercontent.com/6147380/33874476-e4ee0f14-df59-11e7-9ed3-a814b985509f.png)

我用了其他http client测试均无问题，多次调试之后我把<Upload/>的action参数直接写成后端host问题消失，说明这个mock的代理是存在问题的，各位在开发的时候要注意这个坑。

这个问题在之前就有人在roadhog提过类似的issue: https://github.com/sorrycc/roadhog/issues/325 至今还是未解决。

**Comment by francisfeng** [comment]
我今天也遇到了这个问题，还以为是接口出了问题，和后端捣鼓了一下午。

roadhog的proxy不会原样转发body。目前看来，会在body不是可解析的JSON时，把body强制转为JSON格式再发送，但此时在Chrome的Dev Tools里是看不出异常的……

**Comment by LaiHuanMin** [comment]
omg，我也碰到这个坑了，现在解决了吗？头疼

**Comment by callmez** [comment]
找了一圈...

**Comment by yangxin114** [comment]
我也遇到了这个问题，查了2天，前端后端均不报错，后端java的controller就是无法接受到form data的file，后来才发现好像是代理问题。。有什么好的解决办法么？

**Comment by yangxin114** [comment]
解决了，换代理，改在.webpackrc.js里配置代理
  //配置代理
  proxy:{
    "/api":{
      "target":"http://xxxx:8080/",
      "changeOrigin":true,
      "pathRewrite":{"^/api":""}
    }
  }
