### ISSUE TITLE
使用未定义的函数，浏览器控制台和页面都没有报错信息

### ISSUE THREAD

**Issue by Eric1326** [ant-design/ant-design-pro#4171]
新克隆，未做任何修改的代码，在 api.js 文件下 fakeAccountLogin 函数内 console('test')，在浏览器页面和控制台都没有任何报错信息。或者在 models/login.js 文件中，在第17行添加 abc('xxx')，浏览器页面和控制台也不会有任何报错信息 
![image](https://user-images.githubusercontent.com/39052887/57564640-86ec9c00-73e1-11e9-899e-e604bbd11566.png)
![image](https://user-images.githubusercontent.com/39052887/57564647-a683c480-73e1-11e9-8f34-3ea70158b0eb.png)

**Comment by chenshuai2144** [comment]
因为这些方法还没有执行。js是一种脚本语言，不是编译型的语言。
