### ISSUE TITLE
typescript: tslint如何集成es7+相关的特性

### ISSUE THREAD

**Issue by liuyuan6088** [ant-design/ant-design-pro#4172]
项目使用ts改造，发现无法识别es7+的新特性：
<img width="578" alt="屏幕快照 2019-05-11 上午11 37 40" src="https://user-images.githubusercontent.com/34789095/57564689-7ab50e80-73e2-11e9-9682-bfc8ff1619f3.png">
在tsconfig.json文件中将 "lib": ["es6", "dom"], 替换成 "lib": ["es7", "dom"]后无效
请问下该如何配置？

**Comment by chenshuai2144** [comment]
更新一下ts。这个api已经支持了
