### ISSUE TITLE
在华为浏览器打开白屏

### ISSUE THREAD

**Issue by a137653558** [ant-design/ant-design-pro#4174]
已经用服务器部署好了之后，pc端能正常运行，部分手机也能运行。
用 华为meta 10 的浏览器打开网站就白屏，
但是在微信里打开网站是好的

**Comment by chenshuai2144** [comment]
华为浏览器基于 chrome35，不知道最近是多少。
这么低的浏览器，pro 并不支持

**Comment by a137653558** [comment]
华为手机里的 qq浏览器 也是白屏
