### ISSUE TITLE
多标签页

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#4176]

**Comment by afc163** [comment]
Duplicate of #220

**Comment by Fengly0503** [comment]
公司项目也有多标签功能的需求，看了各位的实现感觉还是不太满足自己的需求，就自己写了一个基于Ant design pro 4 + 路由拦截的方案，解决了一些标签切换、关闭、路由关联、相同类型不同数据详情页、url直接访问指定标签等问题，有兴趣的兄弟可以瞅瞅 [多标签实现地址](https://github.com/Fengly0503/ant_pro_tabs)

![demo-1](https://user-images.githubusercontent.com/7435119/77248172-5cf73d80-6c72-11ea-9c71-202cc79a6450.jpg)
![demo-2](https://user-images.githubusercontent.com/7435119/77248174-5ec10100-6c72-11ea-8898-a01b1915e2a8.jpg)
![demo-3](https://user-images.githubusercontent.com/7435119/77248175-5f599780-6c72-11ea-9b5b-ab30f9d46908.jpg)
