### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by pingfangushi** [ant-design/ant-design-pro#4179]
![image](https://user-images.githubusercontent.com/44340237/57600095-63fdeb80-758b-11e9-9990-7fcd8f9c0cc4.png)

**Comment by weidadaGG** [comment]
我也是这问题，我使用的是npm安装的，npm 6.9.0  node 10.15.3,后续使用淘宝cnpm install 还是不行

**Comment by chenshuai2144** [comment]
warning 可以忽略掉，npm 的生态就是这样。期待 github package 能做一些优化
