### ISSUE TITLE
界面右上角消息框中的List中的图标在360浏览器极速模式下覆盖文字

### ISSUE THREAD

**Issue by ligx100** [ant-design/ant-design-pro#418]
搜狐、谷歌浏览器没问题

![image](https://user-images.githubusercontent.com/18524121/33875880-afb3483c-df5e-11e7-8d48-4aec512b5e8b.png)

**Comment by chenshuai2144** [comment]
上图

**Comment by ligx100** [comment]
@chenshuai2144 大神帮忙看看

**Comment by chenshuai2144** [comment]
应该是flex布局的问题.  你的极速浏览器版本?

**Comment by ligx100** [comment]
@chenshuai2144 360浏览器版本8.1.1.240 ，极速模式下样式就错了

**Comment by nikogu** [comment]
> 应该是flex布局的问题. 你的极速浏览器版本

应该不是，因为 list 也用了 flex，他截图下面的 list 是好的。

**Comment by chenshuai2144** [comment]
极速版 chrome 45的版本号.
@nikogu  我们兼容45吗?

@ligx100 升级浏览器把 最新的9.1是55版本就没有问题.

**Comment by ligx100** [comment]
@chenshuai2144 内核45版本是有问题的，内核55版本是好的。去antd官网看了，List是不兼容45的。

![image](https://user-images.githubusercontent.com/18524121/33922531-5b58561c-e006-11e7-807f-81fd76bdfbd3.png)

**Comment by afc163** [comment]
请升级浏览器，只支持现代浏览器的最新两个版本。

**Comment by chenshuai2144** [comment]
@ligx100  升级浏览器把..我们是基于antd的 或者去antd上面提个issue
