### ISSUE TITLE
build后生成一个配置文件，然后配置接口地址

### ISSUE THREAD

**Issue by liuyanming9551** [ant-design/ant-design-pro#4180]
有一种需求就是我的接口地址不是写好去打包的，而是在build后去由一个配置文件来动态的生成，这种情况我想请问一下有没有好的思路，麻烦给我提供一个思路。

**Comment by chenshuai2144** [comment]
你可以用 nginx 的反向代理来做，修改 nginx 的配置文件就可以修改请求的地址，前端也不需要改动
