### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

### ISSUE THREAD

**Issue by pingfangushi** [ant-design/ant-design-pro#4181]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

**Comment by chenshuai2144** [comment]
The best way is to put the state into redux instead of using this.setState

**Comment by pingfangushi** [comment]
这个错误是在控制台切换到别的菜单的时候报的，在下面还有这个 Uncaught TypeError: Cannot read property 'forceFit' of null

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4112

**Comment by afc163** [comment]
Fixed in #4209
