### ISSUE TITLE
可以通过配置来关闭热更新吗？

### ISSUE THREAD

**Issue by huangyiming9228** [ant-design/ant-design-pro#4182]
我不太喜欢改几行代码就自动加载，电脑很慢，卡哭了，或者能够ctrl+S保存的时候再触发热更新吗？

**Comment by chenshuai2144** [comment]
现在就是` ctrl+S`然后热更新。

**Comment by huangyiming9228** [comment]
> 现在就是` ctrl+S`然后热更新。

是的，ctrl+s也会触发更新，我现在的版本是2.3.1，总是会在文件中键入几个字符短暂停顿后就触发更新，
![image](https://user-images.githubusercontent.com/34177347/57623772-0e453580-75c3-11e9-834d-8b92309cbec0.png)
我需要做什么升级或者配置来关闭这个功能吗？

**Comment by chenshuai2144** [comment]
这个还真没有
@sorrycc  有什么办法可以关掉吗？这位同学的需求还是很有意思的，我也有这个毛病，我打一个字 按一下 `crtl+s`

**Comment by sorrycc** [comment]
通过环境变量 `HMR=none` 试试。

**Comment by huangyiming9228** [comment]
> 通过环境变量 `HMR=none` 试试，https://umijs.org/guide/env-variables.html#hmr

已解决，谢谢。

**Comment by pcxxiaoxiao** [comment]
> 通过环境变量 `HMR=none` 试试，https://umijs.org/guide/env-variables.html#hmr

感谢大佬，困扰我几天的问题终于解决了
