### ISSUE TITLE
二、三级菜单问题独立显示的问题

### ISSUE THREAD

**Issue by SiroSong** [ant-design/ant-design-pro#4184]
二级菜单和三级菜单都分别指向一个功能完整的页面，三级页面作为二级页面的详情页面，三级页面不显示导航，高亮还停留在二级导航上，这个可以实现吗？看见antd-pro里面的demo都是二三级页面共同存在组成一个完整页面，也没有这个问题的相关做法，，所以，这种效果怎样才可以实现呢？？？

**Comment by chenshuai2144** [comment]
可以的，只要路径是包含的关系。
不显示的菜单中可以使用 hideInMenu来配置

**Comment by SiroSong** [comment]
> 可以的，只要路径是包含的关系。
> 不显示的菜单中可以使用 hideInMenu来配置

可是，我已经尝试过在配置中将路径改写为包含关系，因为二级页面是有组件的，不写{this.props.children}就不显示三级组件，写了，三级组件跑到二级组件的下面去了。。。

**Comment by chenshuai2144** [comment]
做成平级的但是url 是嵌套的就好了吧。

```js
[
  {
    path: "/list"
  },
  {
    path: "list/item/:id"
  }
];

```

**Comment by SiroSong** [comment]
> 做成平级的但是url 是嵌套的就好了吧。
> 
> ```js
> [
>   {
>     path: "/list"
>   },
>   {
>     path: "list/item/:id"
>   }
> ];
> ```

嗯嗯，是可以的，thanks~
