### ISSUE TITLE
TableList.tsx里面的子组件报错。

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4185]
![image](https://user-images.githubusercontent.com/18098618/57614973-2447fb80-75ad-11e9-8900-3c1115ebf901.png)

**Comment by Lind-pro** [comment]
Type '{ updateModalVisible: boolean; values: Partial<RuleItem>; handleUpdateModalVisible: (flag?: boolean | undefined, record?: RuleItem | undefined) => void; handleUpdate: (fields: Partial<RuleItem>) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<FormComponentProps<any>, "wrappedComponentRef">, any, any>> & Readonly<Pick<FormComponentProps<any>, "wrappedComponentRef">> & Readonly<...>'.

  Property 'updateModalVisible' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<FormComponentProps<any>, "wrappedComponentRef">, any, any>> & Readonly<Pick<FormComponentProps<any>, "wrappedComponentRef">> & Readonly<...>'.ts(2322)

TableList.tsx 的第745行。
开发工具是VS code

**Comment by Lind-pro** [comment]
![image](https://user-images.githubusercontent.com/18098618/57615712-ef3ca880-75ae-11e9-9b82-533fd81ea877.png)

**Comment by chenshuai2144** [comment]
look here https://github.com/ant-design/pro-blocks/blob/master/TableList/src/index.tsx

**Comment by liuzeyang** [comment]
I also encountered this problem, how to solve it?

**Comment by chenshuai2144** [comment]
download new code
