### ISSUE TITLE
创建css变量文件variable.less，如何引用这个变量文件？

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#4186]
1. 创建variable.less文件
![image](https://user-images.githubusercontent.com/19780441/57623498-747d8880-75c2-11e9-9970-b970c658c790.png)

2. 引入文件
![image](https://user-images.githubusercontent.com/19780441/57623292-0df86a80-75c2-11e9-926b-9659b0c1f9e0.png)

3. 项目启动报错
![image](https://user-images.githubusercontent.com/19780441/57623351-29637580-75c2-11e9-970d-9c5b0d641d3b.png)
如何处理这个问题？

**Comment by chenshuai2144** [comment]
直接使用相对路径就好了。

 > It's important to only prepend it with ~, because ~/ resolves to the home-directory. webpack needs to distinguish between bootstrap and ~bootstrap, because CSS and Less files have no special syntax for importing relative files. Writing @import "file" is the same as @import "./file";

~ 是less-loader的约定，会强行定位到 '/ '目录 只有使用第三方库才会用到它。 

参考资料 https://github.com/webpack-contrib/less-loader#webpack-resolver

**Comment by rodchen-king** [comment]
![image](https://user-images.githubusercontent.com/19780441/57663700-a117bb80-7627-11e9-89c1-b3d2982fb902.png)
1. 请看这个图片的第二个css文件，这个是当前项目的css文件，并不是第三方的文件。
2. css变量文件如果只能使用相对路径的话，多层级的代码如何去引用css变量文件？按层级找相对路径？
3. 我将当前路径改成相对路径，还是会报错
![image](https://user-images.githubusercontent.com/19780441/57663787-023f8f00-7628-11e9-9302-ec5b45f64054.png)

**Comment by rodchen-king** [comment]
@chenshuai2144

**Comment by Aledenn** [comment]
我也遇到这个问题 相对路径没用 @chenshuai2144

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/57666398-59e2f800-7632-11e9-9ba8-899f6c65e887.png)
报错是因为这个

**Comment by Aledenn** [comment]
目标文件:src/styles/varfile.less

**Comment by rodchen-king** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/57666398-59e2f800-7632-11e9-9ba8-899f6c65e887.png)
> 报错是因为这个
什么意思？不太了解。

还有一个为问题是：第二个css文件，如果我改了文件名称，在改了调用处的css文件名，也会报找不到文件的错。
![image](https://user-images.githubusercontent.com/19780441/57666709-7cc1dc00-7633-11e9-924d-f813ec96ce98.png)

**Comment by rodchen-king** [comment]
> src/styles/varfile.less
这个不行的，我试了一下。

**Comment by Aledenn** [comment]
@chenshuai2144 
目标文件: src/styles/varfile.less
所在文件: src/pages/Dashboard/home.less
我分别使用了:
@import 'styles/varfile.less';
![image](https://user-images.githubusercontent.com/19233912/57666829-ef32bc00-7633-11e9-90e4-7b64f1587640.png)

@import ''../../styles/varfile.less"
![image](https://user-images.githubusercontent.com/19233912/57666888-30c36700-7634-11e9-98ff-227c3a688fbf.png)

@import '../../../src/styles/varfile.less';

@import 'src/styles/varfile.less';

...都失败了

**Comment by Aledenn** [comment]
@rodchen-king 成功了 使用
@import '~@/styles/varfile.less';
~@代替表示src

**Comment by Aledenn** [comment]
@rodchen-king 话说你是在做浏览器在线换肤的功能吗 我目前只能改antd组件的颜色 改不了自定义的变量 可以问问你能做到吗

**Comment by rodchen-king** [comment]
@Aledenn 你这个成功只是第一层级： 你的项目是ant design pro吗？我用了你的方式没成功

**Comment by Aledenn** [comment]
@rodchen-king 是的 使用了ant desigin pro 你可能路径写错了？ 发出来看看

**Comment by rodchen-king** [comment]
> @rodchen-king 话说你是在做浏览器在线换肤的功能吗 我目前只能改antd组件的颜色 改不了自定义的变量 可以问问你能做到吗

我不是做在线换肤的，我是做项目提取css变量文件的。规范css的。

**Comment by rodchen-king** [comment]
> @rodchen-king 是的 使用了ant desigin pro 你可能路径写错了？ 发出来看看

1. css文件：
![image](https://user-images.githubusercontent.com/19780441/57668220-2eafd700-7639-11e9-8ce7-9807af7ba9cb.png)

2. 引用文件 src/dashboard/Analysis.css
![新建位图图像 (2)](https://user-images.githubusercontent.com/19780441/57668301-7e8e9e00-7639-11e9-8d01-3ae244aad73d.jpg)

3. 报错
![image](https://user-images.githubusercontent.com/19780441/57668334-91a16e00-7639-11e9-9d0a-25efc13bbaa1.png)

**Comment by Aledenn** [comment]
@rodchen-king 建议：
如果没有在线换肤的需求 
把config文件夹下的plugin.config.js中的那2个插件给注释了，然后就可以愉快的用相对路径引入less了 然后还可以解决less编译速度慢的问题
![image](https://user-images.githubusercontent.com/19233912/57668899-96672180-763b-11e9-9aa8-fbc842554d9a.png)

**Comment by rodchen-king** [comment]
> @rodchen-king 建议：
> 如果没有在线换肤的需求
> 把config文件夹下的plugin.config.js中的那2个插件给注释了，然后就可以愉快的用相对路径引入less了 然后还可以解决less编译速度慢的问题
> ![image](https://user-images.githubusercontent.com/19233912/57668899-96672180-763b-11e9-9aa8-fbc842554d9a.png)
我最感兴趣的是有一个utils.less文件，如果改了文件夹下的文件名称，再改调用处的名称，也会报错。你试过吗？
![新建位图图像 (2)](https://user-images.githubusercontent.com/19780441/57669098-463c8f00-763c-11e9-9a25-e88bfe7f71db.jpg)

**Comment by Aledenn** [comment]
@rodchen-king 没试过 但是我估计是这2插件的作用...

**Comment by rodchen-king** [comment]
> @rodchen-king 建议：
> 如果没有在线换肤的需求
> 把config文件夹下的plugin.config.js中的那2个插件给注释了，然后就可以愉快的用相对路径引入less了 然后还可以解决less编译速度慢的问题
> ![image](https://user-images.githubusercontent.com/19233912/57668899-96672180-763b-11e9-9aa8-fbc842554d9a.png)

但是这个还是想问一下ant design pro做了什么处理？为什么不行？为什么utils.less可以？改了utils.less的名字之后也不行？

**Comment by Aledenn** [comment]
@rodchen-king https://beta.pro.ant.design/blog/change-theme-cn 看下大大写的文章 估计是合并less的插件写得有问题

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4289

**Comment by rodchen-king** [comment]
> #4289

Ok, thanks

**Comment by chenshuai2144** [comment]
删除实现方式现在已经不会出现这个问题了
