### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by pengxin58578970** [ant-design/ant-design-pro#4189]
https://pro.ant.design/docs/getting-started-cn 按照官网文档安装会报错，需按github下Use bash安装，希望可以把官网文档改进一下。

**Comment by chenshuai2144** [comment]
报错什么？ npm 安装失败

**Comment by pengxin58578970** [comment]
官网上的git指令和github里面的不一致，报错原因我稍后电脑运行回复------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 中午11:17
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "pengxin58578970"<403630101@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] 安装问题 (#4189)



报错什么？ npm 安装失败
 
&mdash;

**Comment by pengxin58578970** [comment]
code ELIFECYCLE
ant-design-pro@2.3.1 start: `cross-env ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION=site umi dev`
Exit status 1
Failed at the ant-design-pro@2.3.1 start script.
This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pengxin58578970** [comment]
按照github上的git下来不会有问题，官网文档中方法会报这个错

**Comment by chenshuai2144** [comment]
全一点
没看见具体的报错的信息

**Comment by zhucp** [comment]
是不是这个问题啊
> umi dev

'umi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.3.1 start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.3.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by chenshuai2144** [comment]
需要 npm i / yarn
