### ISSUE TITLE
Maintain/Save/Restore scroll position when returning to a list or table

### ISSUE THREAD

**Issue by jonahfang** [ant-design/ant-design-pro#419]
Does ant-design-pro solve this problem?

**Comment by chenshuai2144** [comment]
没大懂你的意思,你是希望保存当前的scroll 状态?

**Comment by nikogu** [comment]
we do not have `scrollTo` component, but we have this: https://ant.design/components/anchor/

**Comment by afc163** [comment]
You can try https://github.com/josepot/react-redux-scroll

**Comment by jonahfang** [comment]
@chenshuai2144 谢谢关注此问题，我的使用场景是这样的：
1.用户在一个长列表中选择某一项；
2.界面离开了列表，显示一个表单（注意不是弹出窗口的形式，是显示了另外一个页面）
3.用户在表单界面中选择保存或取消按钮，界面要回到原来的列表。
4.用户希望在列表中仍然看到操作过的项（也就是要让列表自动滚动到改项）

**Comment by chenshuai2144** [comment]
@jonahfang   这个是个好办法吧?
> You can try https://github.com/josepot/react-redux-scroll
你可以将列表top/height 比例保存下来.
返回列表的时候再次赋值

**Comment by jonahfang** [comment]
@chenshuai2144 我认为这是一个很一般和用户需要的需求吧，能否集成到ant-design-pro呢？

**Comment by jonahfang** [comment]
或者有更好的做法？

**Comment by chenshuai2144** [comment]
并不觉得很常用.
一般而言会避开这种事情的. 弹框才是最好的解决方案

**Comment by jonahfang** [comment]
好吧，谢谢  @chenshuai2144

**Comment by WangJM001** [comment]
同样需求，列表页进入详情页后再返回，希望保留原来状态。。。
目前还没找到好的办法
