### ISSUE TITLE
希望推出一个精简版本

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#4192]
,可以参考vue-element-admin 和 vue-template-admin

**Comment by aprilyzl0405** [comment]
等V4就好了，随便减剪简

**Comment by yutingzhao1991** [comment]
https://www.yuque.com/ant-design/ant-design-pro/lmgc46

**Comment by chenshuai2144** [comment]
https://github.com/umijs/create-umi/pull/62
