### ISSUE TITLE
Docker部署，接口请求404【mock/实际服务端接口】

### ISSUE THREAD

**Issue by Emmavv** [ant-design/ant-design-pro#4194]
Docker部署后，接口请求全部返回404
![image](https://user-images.githubusercontent.com/47776704/57694144-896b2200-767d-11e9-8343-8dcebef695e2.png)

nginx.conf配置：
![image](https://user-images.githubusercontent.com/47776704/57694225-c0413800-767d-11e9-9465-23421085a6f4.png)

本地开发环境配置代理，可以正常访问：
![image](https://user-images.githubusercontent.com/47776704/57694191-a69ff080-767d-11e9-87ac-e28aec0ac666.png)

**Comment by afc163** [comment]
pro 只是前端项目，所有的服务端接口需要你自行对接和实现。

**Comment by Emmavv** [comment]
开发环境已经调通，我的nginx的配置是不是配置错误? 给出了 nginx.conf 和 config.js 的代理截图

**Comment by Emmavv** [comment]
> pro 只是前端项目，所有的服务端接口需要你自行对接和实现。

开发环境已经调通，我的nginx的配置是否配置错误? 给出了 nginx.conf 和 config.js 的代理截图

**Comment by chenshuai2144** [comment]
你在 nginx 中没有配置  pathwirte
