### ISSUE TITLE
新拉下来的ant-design-pro项目，从“查询表格”页面点击「规则名称」字段进入「基础详情页」，基础详情页会有报错

### ISSUE THREAD

**Issue by frontendWangqun** [ant-design/ant-design-pro#4195]
新拉下来的ant-design-pro项目，从“查询表格”页面点击「规则名称」字段进入「基础详情页」，基础详情页会有报错；如下：

```
index.js:1 Warning: Encountered two children with the same key, `基础详情页`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by Context.Consumer)


```

**Comment by chenshuai2144** [comment]
这应该是你的逻辑造成的吧。https://preview.pro.ant.design/profile/basic/TradeCode%200 并没有报错

**Comment by frontendWangqun** [comment]
> 这应该是你的逻辑造成的吧。https://preview.pro.ant.design/profile/basic/TradeCode%200 并没有报错

我看了很多次线上的，线上的没报错哦，但是呢，我又重新拉几次项目下来，就会报那个错误，这个是报错图片
![image](https://user-images.githubusercontent.com/43572671/57835568-62356180-77f1-11e9-8968-878110c205b8.png)，你可以试一下

**Comment by k983551019** [comment]
我也遇到了这个问题，还有另一个问题，从分析页，监控页，工作台 点击到其他页面会出现内存泄漏的报错和Cannot read property 'forceFit' of null 的报错。 我昨天也是重新拉取了几次项目 都出现了这个问题。

**Comment by afc163** [comment]
确实有这两个问题，我来修一下。

**Comment by frontendWangqun** [comment]
> 确实有这两个问题，我来修一下。

大佬修复好了告知一下

**Comment by frontendWangqun** [comment]
> 确实有这两个问题，我来修一下。

大佬，这个问题没有报错了，麻烦你看一下这个问题，困扰了很久https://github.com/ant-design/ant-design-pro/issues/4173

**Comment by frontendWangqun** [comment]
> 确实有这两个问题，我来修一下。

我也遇到了这个问题，还有另一个问题，从分析页，监控页，工作台 点击到其他页面会出现内存泄漏的报错和Cannot read property 'forceFit' of null 的报错。 我昨天也是重新拉取了几次项目 都出现了这个问题。


这个问题还没修复啊

**Comment by k983551019** [comment]
> > 确实有这两个问题，我来修一下。
> 
> 我也遇到了这个问题，还有另一个问题，从分析页，监控页，工作台 点击到其他页面会出现内存泄漏的报错和Cannot read property 'forceFit' of null 的报错。 我昨天也是重新拉取了几次项目 都出现了这个问题。
> 
> 这个问题还没修复啊

修复了，获取最新的就行了

**Comment by frontendWangqun** [comment]
> > > 确实有这两个问题，我来修一下。
> > 
> > 
> > 我也遇到了这个问题，还有另一个问题，从分析页，监控页，工作台 点击到其他页面会出现内存泄漏的报错和Cannot read property 'forceFit' of null 的报错。 我昨天也是重新拉取了几次项目 都出现了这个问题。
> > 这个问题还没修复啊
> 
> 修复了，获取最新的就行了

![image](https://user-images.githubusercontent.com/43572671/58009432-06d0df80-7b21-11e9-8655-e70d424ee873.png)
我an按照这个修改的还是有报错的

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/pull/4209/files
