### ISSUE TITLE
服务器更新页面，正在打开使用的页面切换路由报错。

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#4196]
服务器更新项目，刚好用户正在浏览页面，此时切换页面一直loading中，
控制台报错：
![20190514202851](https://user-images.githubusercontent.com/16549630/57697934-ee774580-7686-11e9-8e7d-a80a9e4fff81.jpg)

原因是服务的资源已更新，旧的资源已读取不到。如何能够捕获到控制台的报错，利用window.location.reload(true);重新获取新的资源。pwa的service-worker方式，缓存太严重了。还有别的方式嘛？

相关问题：
https://github.com/ant-design/ant-design-pro/issues/3150
https://github.com/ant-design/ant-design-pro/issues/1365

**Comment by chenshuai2144** [comment]
pwa 的基本就是保证用户就旧的情况下也是可用的。不然就会碰到像我们 pro 前几天碰到的问题一样，你可能需要关掉 pwa，或者在 代码中对任何情况进行catch。 pwa 并不保证什么时候会更新

**Comment by zhilianbi520** [comment]
> pwa 的基本就是保证用户就旧的情况下也是可用的。不然就会碰到像我们 pro 前几天碰到的问题一样，你可能需要关掉 pwa，或者在 代码中对任何情况进行catch。 pwa 并不保证什么时候会更新

@chenshuai2144 pwa的配置已关掉。我可以在哪里catch到这个情况？现在我的问题就是不知道在哪里去catch这个报错，希望可以提供个思路或者解决方案～！

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/34f1c4f86b361453bc89f6bc5a1133e30a553036/src/global.js#L61
加上这个 ，再用 pwa的方式

**Comment by zhilianbi520** [comment]
@chenshuai2144  收到～！已捕获到相关异常。多谢～

**Comment by xiaoshui222** [comment]
> pwa 的基本就是保证用户就旧的情况下也是可用的。不然就会碰到像我们 pro 前几天碰到的问题一样，你可能需要关掉 pwa，或者在 代码中对任何情况进行catch。 pwa 并不保证什么时候会更新

我们的系统是http没有service worker缓存问题，但是换成https就缓存很严重，不知有没有什么解决办法

**Comment by chenshuai2144** [comment]
@xiaoshui222  http 不会开启 pwa 的。
如果你希望用户可以尽快收到更新，建议关掉 pwa

**Comment by xiaoshui222** [comment]
> @xiaoshui222 http 不会开启 pwa 的。
> 如果你希望用户可以尽快收到更新，建议关掉 pwa

我在defaultSettings里把pwa置为false后页面刷新后还是显示有service worker 有点诡异
