### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design-pro#4199]

**Comment by CrazyCoderShi** [comment]
我也想问这个问题，为啥没eslint功能了，但是GitHub上master分支是有这些配置的？
麻烦给新手一个简洁的解释:joy:

**Comment by chenshuai2144** [comment]
没eslint功能? 你是指功能表现不正常吗？

**Comment by CrazyCoderShi** [comment]
我是直接git clone的项目，clone下来的项目目录里面没有eslint配置

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/34f1c4f86b361453bc89f6bc5a1133e30a553036/.eslintrc.js
不存在这个文件？

**Comment by CrazyCoderShi** [comment]
是的

**Comment by CrazyCoderShi** [comment]
![image](https://user-images.githubusercontent.com/12297224/57760478-31d8bf00-772e-11e9-9c78-d644013552e8.png)

**Comment by chenshuai2144** [comment]
你可能需要打开一下显示隐藏文件

**Comment by CrazyCoderShi** [comment]
我试过，依然没有....

**Comment by chenshuai2144** [comment]
. 开头的你都没有。你肯定是忽略了一些文件，你可以在资源管理器中打开看一下

**Comment by CrazyCoderShi** [comment]
在Mac环境下，`shift + cmd + . ` 可以快捷的开关查看 `.` 开头的文件，依然查看不到的...

**Comment by CrazyCoderShi** [comment]
建议大佬，执行一次README中的那个git clone命令看看

**Comment by CrazyCoderShi** [comment]
我使用下载方式，直接下载zip包，就有这些文件，我把zip包里的copy过去了😂

**Comment by CrazyCoderShi** [comment]
Done

![image](https://user-images.githubusercontent.com/12297224/57761643-80875880-7730-11e9-9474-6c9c59784704.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/57762097-6732dc00-7731-11e9-931e-ec77cbc1ae01.png)

**Comment by CrazyCoderShi** [comment]
我仔细回想了一下，应该是我的问题😂(先别打我...

**Comment by CrazyCoderShi** [comment]
我中间有一次文件夹迁移，没有把隐藏文件迁移过去😂
