### ISSUE TITLE
菜单栏优化建议

### ISSUE THREAD

**Issue by 1242832592** [ant-design/ant-design-pro#420]
![image](https://user-images.githubusercontent.com/18162123/33882527-5cb1e6c4-df73-11e7-86d2-e59444ab532e.png)

在手机端展现时页面菜单是否可以如上方式展示，节约屏幕空间

**Comment by chenshuai2144** [comment]
#463正在改进.

**Comment by chenshuai2144** [comment]
pr merge 了再合并把

**Comment by chenshuai2144** [comment]
#463 已经修改
