### ISSUE TITLE
Build Failed in 95%

### ISSUE THREAD

**Issue by andreasflic18** [ant-design/ant-design-pro#4200]
i've try so many times to start but always stop progrees in 95% 

![image](https://user-images.githubusercontent.com/48192109/57747797-4ce10a00-7701-11e9-8e70-7ed749053527.png)

help!

**Comment by andreasflic18** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
删除 webpack plugin 呢？  
https://beta.pro.ant.design/blog/change-theme

**Comment by andreasflic18** [comment]
nah, because there is missing operator and semicolon in style.less
and webpack module (Hot Reload) cant handle that error, so I think you must improve for that bugs

Thanks

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/4200
https://github.com/ant-design/ant-design-pro/issues/4050
https://github.com/ant-design/ant-design-pro/issues/3565
https://github.com/ant-design/ant-design-pro/issues/3597
