### ISSUE TITLE
文档内容不同步

### ISSUE THREAD

**Issue by gaoqiang19514** [ant-design/ant-design-pro#4201]
访问地址：https://v1.pro.ant.design/docs/authority-management-cn

控制菜单显示
如需对某些菜单进行权限控制，只须对菜单配置文件 menu.js 中的菜单项设置 authority 属性即可，代表该项菜单的准入权限，菜单生成文件中会默认调用 Authorized.check 进行判断处理

编辑地址：https://github.com/ant-design/ant-design-pro-site/edit/master/docs/authority-management.zh-CN.md

控制菜单和路由显示
如需对某些页面进行权限控制，只须在路由配置文件 router.config.js 中设置 Routes 属性即可，代表该路由的准入权限，pro 的路由系统中会默认包裹 Authorized 进行判断处理。

**Comment by chenshuai2144** [comment]
v1 的编辑也到了 master，所以造成了这个问题。

**Comment by afc163** [comment]
文档里链接都要按 <kbd>Y</kbd> 固定 url 才行。

**Comment by neekey** [comment]
吐个槽，authority 这个模块写的真的是非常的绕，而且UI的登录验证状态更新，通过的是`reloadAuthorized()` 来更新`utils/Authorized` 中的默认导出模块变量，并配合后续路由变化来使得 `pages/Authorized` 重新渲染来刷新 `utils/Authorized` 的渲染... 且`reloadAuthorized()` 是在model层调用来更改一个ui层的变量...hmm..挺反模式的；

`components/Authorized` 里面`renderAuthorize` 这个名字在多个模块中重复使用，这块代码读起来非常费劲。

另外，authority-management 这块的文档太过简单，也完全没有点到使用 `utils/authority` 中的 `getAuthority` 跟 `setAuthority`，感觉基本上要了解流程，必须得自己读一遍代码，这块文档需要更加详细才行。
