### ISSUE TITLE
PageHeaderWrapper 中使用 breadcrumbList 的bug

### ISSUE THREAD

**Issue by superchow** [ant-design/ant-design-pro#4202]
在PageHeaderWrapper 中使用 breadcrumbList 时， breadcrumbList 的内容是异部数据渲染的，数据变化了但页面不会更新界面

`Pro: "2.1.1" `
`antd: "^3.11.6"`

**Comment by superchow** [comment]
暂时给 PageHeaderWrapper  加 loading 状态，异部数据完成后，`loading=true` 解决

**Comment by chenshuai2144** [comment]
` breadcrumbList =[...breadcrumbList]`
你需要让 react 知道你的数据已经更新了

**Comment by superchow** [comment]
> breadcrumbList

这种也用过了

**Comment by superchow** [comment]
> ` breadcrumbList =[...breadcrumbList]`
> 你需要让 react 知道你的数据已经更新了

这种也用过了

**Comment by chenshuai2144** [comment]
已过时
