### ISSUE TITLE
请问2.1.1版本生产模式，为啥按F5刷新就报404呢？

### ISSUE THREAD

**Issue by cnhans** [ant-design/ant-design-pro#4203]
版本：2.1.1 tag
比如：
https://www.xx.com/weixin/profiles/list

我使用https://www.xxx.com 然后回车就可以访问，然后里面也可以点路由，访问相应的功能。
但只要我用f5刷新，或者用浏览器地址栏输入https://www.xx.com/weixin/profiles/list
回车，就报404，有人碰到这样的问题吗，我部署到nginx，谢谢。dev环境下不会有这个问题。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88
你需要的估计是这个

**Comment by cnhans** [comment]
新版要这样配置啊，了解了，谢谢
