### ISSUE TITLE
NoticeIcon 点击 “查看更多” 没有关闭浮层方法

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design-pro#4207]
[NoticeIcon](https://pro.ant.design/components/notice-icon-cn) 组件显示带浮层卡片的通知，点击 “查看更多”  跳转到通知列表页之后，浮层没有隐藏，影响体验。

建议新增一个 viewMoreClose 属性，在触发 onViewMore 时关闭浮层

**Comment by caijf** [comment]
暂时改用清空按钮实现了 

`locale.clear` 设为 `查看更多` ，但还是会多一个标题（显示“查看更多 通知”）
`onClear ` 用来跳转通知列表页
`clearClose ` 设为 `true`

**Comment by chenshuai2144** [comment]
NoticeIcon 组件不会再次更新了，如果有需求，建议拷贝源码到项目中

**Comment by caijf** [comment]
> 暂时改用清空按钮实现了
> 
> `locale.clear` 设为 `查看更多` ，但还是会多一个标题（显示“查看更多 通知”）
> `onClear ` 用来跳转通知列表页
> `clearClose ` 设为 `true`

这种方式有个问题，当通知列表都为已读时，清空按钮会消失。

现在是拷贝源码到项目中使用！
