### ISSUE TITLE
建议-图表组件事件监听

### ISSUE THREAD

**Issue by 1242832592** [ant-design/ant-design-pro#421]
在使用图标组件的时候有时需要对图表进行下钻上卷操作，例如柱状图柱状图默认按年为x坐标显示，点开某一个柱子时展开到月级别，这就需要监听图表的点击事件获取图表的X坐标值。
希望大牛们能够实现这种事件监听，组件向外传值得功能，对于数据分析展现将有很大帮助。

**Comment by chenshuai2144** [comment]
这个需要等g2来实现.或者你自己用dateset实现一下..
下钻现在g2正在实现中.
