### ISSUE TITLE
如果CSS模块遇到冲突，在哪里单独配置css-loader?

### ISSUE THREAD

**Issue by wangchong19940101** [ant-design/ant-design-pro#4211]
比如说安装了react-monaco-editor，样式冲突了，如下图

![image](https://user-images.githubusercontent.com/30942709/57899367-54361e00-788f-11e9-8ab7-c91114a87416.png)

**Comment by wangchong19940101** [comment]
求大佬们解答。。。

![image](https://user-images.githubusercontent.com/30942709/57901642-94e66500-7898-11e9-9d3f-41bc90f5981a.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#cssmodulesexcludes
你需要的是这个吗？

**Comment by wangchong19940101** [comment]
@chenshuai2144 
根据官方给的文档如下图
![image](https://user-images.githubusercontent.com/30942709/57906460-a0dc2200-78ac-11e9-9660-ec4229850804.png)
而我在ant-design-pr 2.3.0里的config是这样配置的如下图
![image](https://user-images.githubusercontent.com/30942709/57906502-cf59fd00-78ac-11e9-818b-d82ef61c1282.png)
跪求大佬指点！

**Comment by wangchong19940101** [comment]
但是并没有生效，样式还是被monaco-editor覆盖。而且下载了react-monaco-editor包后，并没有使用，样式就被覆盖了
@chenshuai2144

**Comment by wangchong19940101** [comment]
css中 .ant-btn-primary不见了 @chenshuai2144 
![image](https://user-images.githubusercontent.com/30942709/57908645-1f3bc280-78b3-11e9-892a-0f8c95bf4bd6.png)

**Comment by chenshuai2144** [comment]
应该是 less 转化失败了，通过 umd 的方式不可以加载吗？

**Comment by wangchong19940101** [comment]
怎么用umd的方式加载？恕小白无知

**Comment by yoyo837** [comment]
直接script 进来试试

**Comment by wangchong19940101** [comment]
没明白什么意思呢？请大佬细聊

**Comment by wangchong19940101** [comment]
@yoyo837

**Comment by yoyo837** [comment]
umd 的包直接传统script 标签引入

**Comment by wangchong19940101** [comment]
@yoyo837 
15510772290是我的微信，麻烦大佬加我下，恕小弟愚昧

**Comment by wangchong19940101** [comment]
你说umd的包是指哪些？不太懂

**Comment by wangchong19940101** [comment]
请问大佬们，这段代码注释有影响吗？@all
![image](https://user-images.githubusercontent.com/30942709/57996791-1c7fde00-7afc-11e9-8d66-c7a3ca1ccf63.png)

**Comment by tong233** [comment]
请问解决了吗？遇到同样的问题。

**Comment by yoyo837** [comment]
@wangchong19940101 有没有问题，有没有影响，亲自试试就知道啦。

**Comment by wangchong19940101** [comment]
https://github.com/ant-design/ant-design-pro/issues/4034
@tong

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/2236
