### ISSUE TITLE
加载model串错

### ISSUE THREAD

**Issue by shijuanjuan93** [ant-design/ant-design-pro#4212]
同一个model 里面有两个get方法，返回格式一样,. 我两个js分别调用其中一个方法，发交易串了。（例如a.js 调其中a方法，b.js调用b方法，但是会报错，data数据串开）

**Comment by chenshuai2144** [comment]
> 同一个model 里面有两个get方法

为什么要这样呢？至少要保证名字不一样

**Comment by shijuanjuan93** [comment]
我是自己造的mock数据，因为返回的数据根据场景做的不一样，我就把两个查询方法写到一个model里面了,不明白为什么会出现这种情况？ 

- 我想了下 是不是 componentdidMount在render后执行造成的，但是我换了componentWillMount 依然是这种情况

**Comment by chenshuai2144** [comment]
show you code
