### ISSUE TITLE
ant-design-pro 中封装的ChartCard组件，迷你柱形图和迷你区域图，频繁切换移入移出，气泡不消失

### ISSUE THREAD

**Issue by kimmerchen** [ant-design/ant-design-pro#4216]
![image](https://user-images.githubusercontent.com/20125299/57913343-00dbc400-78bf-11e9-81c2-b346ebb57471.png)

**Comment by afc163** [comment]
这是 g2 的问题，我们不太好解决，建议提给 g2。
