### ISSUE TITLE
siderMenu宽度问题，宽度减少后不居中，如图

### ISSUE THREAD

**Issue by dangyanglim** [ant-design/ant-design-pro#4217]
怎么修改啊
把宽度由默认的80改成60的样子
collapsedWidth={60}

`
![7777](https://user-images.githubusercontent.com/16640185/57920923-c8dc7d00-78ce-11e9-978f-571f87526b12.jpg)

`

**Comment by dangyanglim** [comment]
好像是ant库里面这个控制的，怎么在外面控制
.ant-layout-sider-zero-width-trigger {
  position: absolute;
  top: 64px;
  right: -36px;
  width: 36px;
  height: 42px;
  color: #fff;
  font-size: 18px;
  line-height: 42px;
  text-align: center;
  background: #001529;
  border-radius: 0 4px 4px 0;
  cursor: pointer;
  -webkit-transition: background 0.3s ease;
  transition: background 0.3s ease;
}

**Comment by dangyanglim** [comment]
谁知道怎么覆盖调整宽度不？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/6e59e7767f30c11f10bdb95990d080b26ca1442c/components/style/themes/default.less#L368
