### ISSUE TITLE
全局中的model，在A页面获取的数据，在B页面connect model后，state被刷新

### ISSUE THREAD

**Issue by sunslj** [ant-design/ant-design-pro#4218]

**Comment by chenshuai2144** [comment]
没懂你说的是什么？全局model必须要要放到 src/model 中

**Comment by sunslj** [comment]
@chenshuai2144  我有一个‘search’ model 在 src/model中，我在A页面中绑定search，获取到数据存到state/data。
从A页面跳转到B页面（也绑定了search）,不能调用刚才在A页面获取的数据（此时search model中的state为初始化状态）

**Comment by chenshuai2144** [comment]
show you code

**Comment by sunslj** [comment]
@chenshuai2144 
search 
`
import { queryDataSet,getDetectionList } from '@/services/api';
import { message } from 'antd';

export default {
  namespace: 'search',

  state: {
    detection: [],
    data:[],
  },

  effects: {
    *fetch({ payload }, { call, put })  {
      const response = yield call(queryDataSet,payload);
      if (response.message_code === 0){
        yield put({
          type: 'save',
          payload: Array.isArray(response.result) ? response.result : [],
        });
      }else {
        message.error(response.message, 3);
      }
    },
    *getDetection({ payload }, {call, put })  {
      const response = yield call(getDetectionList,payload);
      if (response.message_code === 0){
        yield put({
          type: 'saveDetail',
          payload: Array.isArray(response.result) ? response.result : [],
        });
      }else {
        message.error(response.message, 3);
      }
    },
  },

  reducers: {
    save(state, action) {
      return {
        ...state,
        data: action.payload,
      };
    },
    saveDetail(state, action) {      
      return {
        ...state,
        detection: action.payload,
      };
    },
  },
};

`

**Comment by sunslj** [comment]
@chenshuai2144 
这是 search model 文件
```js
import { queryDataSet,getDetectionList } from '@/services/api';
import { message } from 'antd';

export default {
  namespace: 'search',

  state: {
    detection: [],
    data:[],
  },

  effects: {
    *fetch({ payload }, { call, put })  {
      const response = yield call(queryDataSet,payload);
      if (response.message_code === 0){
        yield put({
          type: 'save',
          payload: Array.isArray(response.result) ? response.result : [],
        });
      }else {
        message.error(response.message, 3);
      }
    },
    *getDetection({ payload }, {call, put })  {
      const response = yield call(getDetectionList,payload);
      if (response.message_code === 0){
        yield put({
          type: 'saveDetail',
          payload: Array.isArray(response.result) ? response.result : [],
        });
      }else {
        message.error(response.message, 3);
      }
    },
  },

  reducers: {
    save(state, action) {
      return {
        ...state,
        data: action.payload,
      };
    },
    saveDetail(state, action) {      
      return {
        ...state,
        detection: action.payload,
      };
    },
  },
};

```

**Comment by chenshuai2144** [comment]
看起来没有问题。 可以输出一下这地方，看看 state 是不是被改变了。或者使用 [redux dev ](https://github.com/zalmoxisus/redux-devtools-extension)工具，可以直观的看到数据的改动 
```
 saveDetail(state, action) {      
      return {
        ...state,
        detection: action.payload,
      };
    },
```

**Comment by sunslj** [comment]
@chenshuai2144 
search 的state，初始值就是空的

**Comment by sunslj** [comment]
@chenshuai2144 
找到问题了，我原来在A页面是通过 <a> 跳转到B页面的，我换成 routerRedux 跳转之后，B页面就有数据了

**Comment by chenshuai2144** [comment]
emmm
