### ISSUE TITLE
设置权限setAuthority是不是有个小bug？

### ISSUE THREAD

**Issue by Iscrdr** [ant-design/ant-design-pro#4219]
src/utils/authority.js

```
export function setAuthority(authority) {
  const proAuthority = typeof authority === 'string' ? [authority] : authority;
  return localStorage.setItem('antd-pro-authority', JSON.stringify(proAuthority));
}
```
这段代码支持 authority 是字符串类型，如果是单个字符串的话，比如“admin”是没有问题的，但是如果是json字符串的话就会出现bug，比如"['admin','add','query','user']" .执行没有问题，但是结果却是错误的。

**Comment by chenshuai2144** [comment]
这行代码并没有涉及到所有的情况  json string 的确是没有好的处理方式

**Comment by Iscrdr** [comment]
我还没有完全弄明白 ant design pro的逻辑，等我弄明白后，测试没有问题在 pull request
