### ISSUE TITLE
为什么git提交每次都会格式化(之前是压缩过的)我的文件?

### ISSUE THREAD

**Issue by LukerSpringtree** [ant-design/ant-design-pro#4223]
我在 .eslintignore 和 .prettierignore 里面都加了目标文件夹的路径

还是不行!

这是 git 推送记录

git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/g9/vf1m76yx4vg41qrfck6s0h3r0000gn/T/SourceTreeTemp.HoHml9 
Can't find node in PATH, trying to find a node binary on your system
husky > pre-commit (node v10.8.0)

> ant-design-pro@2.2.1 lint-staged /Users/luker/gitlab/zunbao-cms
> lint-staged

Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running linters... [started]
Running tasks for **/*.{js,ts,tsx,json,jsx,less} [started]
Running tasks for **/*.{js,jsx} [started]
Running tasks for **/*.less [started]
Running tasks for **/*.less [skipped]
→ No staged files match **/*.less
node ./scripts/lint-prettier.js [started]
npm run lint-staged:js [started]
npm run lint-staged:js [completed]
Running tasks for **/*.{js,jsx} [completed]
node ./scripts/lint-prettier.js [completed]
git add [started]
git add [completed]
Running tasks for **/*.{js,ts,tsx,json,jsx,less} [completed]
Running linters... [completed]
Can't find node in PATH, trying to find a node binary on your system
Can't find node in PATH, trying to find a node binary on your system
Can't find node in PATH, trying to find a node binary on your system

git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --set-upstream origin refs/heads/master:refs/heads/master 
Pushing to git@10.192.0.179:springtree/zunbao-cms.git
Can't find node in PATH, trying to find a node binary on your system
To 10.192.0.179:springtree/zunbao-cms.git
   4c99470..b9d664d  master -> master
updating local tracking ref 'refs/remotes/origin/master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
Completed successfully

是不是 哪个 tasks 里面有 格式的任务. 怎么改!
求帮助. 查了好久了

**Comment by chenshuai2144** [comment]
我们用了 [husky](https://github.com/husky/husky)
https://github.com/ant-design/ant-design-pro/blob/fbeb545a0fd050e701924cba4b8889398e474525/package.json#L37
