### ISSUE TITLE
request.js 第一次获取不到Storage作用率的值

### ISSUE THREAD

**Issue by mxthd** [ant-design/ant-design-pro#4224]
用户登录成功后,我将token存在localStorage中,request.js使用localStorage.getItem("token")时没有获取到数据,但是我在其他组件内是可以获取到的.

但是h5刷新浏览器后就可以获取到了,

详细:https://yq.aliyun.com/ask/496797

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/57992825-c2295200-7ae8-11e9-91d4-3008da7cab25.png)


这个只有在初始化的时候才会去调用，你应该使用 use 。
```
// response interceptor, handling response
request.interceptors.response.use((response, options) => {

  response.headers.append('interceptors', 'my-key');
  return response;
});
```

**Comment by mxthd** [comment]
@chenshuai2144  你好,将这段代码粘贴到request.js中报错

**Comment by chenshuai2144** [comment]
我不会帮你写代码的，我只会告诉你错误在哪里。

**Comment by mxthd** [comment]
@chenshuai2144  刚接触前端很多都有点不懂, 现在解决了,谢谢你.

**Comment by xyzabc0004** [comment]
我刚也碰到这个问题了。

**Comment by xyzabc0004** [comment]
咋整的？

**Comment by tangniyuqi** [comment]
request.interceptors.request.use((url, options) => {
  options.headers = {
    ...options.headers,
    'Authorization': `Bearer ${localStorage.getItem('access_token')}`
  }
  return (
    {
      url: `${url}`, // &interceptors=yes
      options: {
        ...options,
        interceptors: true,
      },
    }
  );
});

**Comment by tangniyuqi** [comment]
`request.interceptors.request.use((url, options) => {
  options.headers = {
    ...options.headers,
    'Authorization': `Bearer ${localStorage.getItem('access_token')}`
  }
  return (
    {
      url: `${url}`, // &interceptors=yes
      options: {
        ...options,
        interceptors: true,
      },
    }
  );
});`

**Comment by tangniyuqi** [comment]
不能格式化代码，将就看吧

request.interceptors.request.use((url, options) => {
  options.headers = {
    ...options.headers,
    'Authorization': `Bearer ${localStorage.getItem('access_token')}`
  }
  return (
    {
      url: `${url}`, // &interceptors=yes
      options: {
        ...options,
        interceptors: true,
      },
    }
  );
});
