### ISSUE TITLE
注释config.js里的dll那段代码对项目有影响吗？

### ISSUE THREAD

**Issue by wangchong19940101** [ant-design/ant-design-pro#4225]
如下图所示
![image](https://user-images.githubusercontent.com/30942709/57998715-3d98fc80-7b05-11e9-96d4-a739a749ec5b.png)

**Comment by chenshuai2144** [comment]
看这里 没有影响
https://webpack.js.org/plugins/dll-plugin/

**Comment by wangchong19940101** [comment]
好的，谢谢大佬
