### ISSUE TITLE
PageHeaderWrapper默认不添加 Title 时仍然会占行高度

### ISSUE THREAD

**Issue by zhangpp2019** [ant-design/ant-design-pro#4227]
![123](https://user-images.githubusercontent.com/46835893/58001836-3f67bd80-7b0f-11e9-92ee-b58dd942707e.png)

**Comment by chenshuai2144** [comment]
是 antd 那边的问题 我来修一把

**Comment by perany** [comment]
这个问题我也有遇到，自己覆盖样式给修掉了

**Comment by chenshuai2144** [comment]
fix in Layout

**Comment by Miss-violet** [comment]
关联一下 commit？不然不知道怎么改。

**Comment by nuptcheng** [comment]
> 这个问题我也有遇到，自己覆盖样式给修掉了

你好，我也碰到这个问题请问具体是如何操作的？谢谢

**Comment by afc163** [comment]
升级一下 @ant-design/pro-layout 到最新版本。
