### ISSUE TITLE
本地无任何错误信息，build到线上后报错umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by allenZhengchangjin** [ant-design/ant-design-pro#4230]
已经试过配置一些参数，但是没有效果

**Comment by chenshuai2144** [comment]
打开一下 devtools 配置。

https://github.com/ant-design/ant-design-pro/blob/a194dda616dd777a24957cf6e2e29243e15ac089/config/config.js#L73

**Comment by lahvey** [comment]
```js
umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at i (umi.js:1)
    at Module.lY8q (p__Chart__Analysis.async.js:1)
    at i (umi.js:1)
    at async Promise.all (index 3)
```

到目前还没解决，
是umi的问题，https://github.com/umijs/umi/issues/1551
还是是webpack的问题：https://github.com/webpack/webpack/issues/8996

**Comment by kuckboy1994** [comment]
![image](https://user-images.githubusercontent.com/19633245/60637958-1301c980-9e4f-11e9-9199-06515b15d3cf.png)

也遇到了这个问题

**Comment by ThienMD** [comment]
same issue

**Comment by shanjuqiuming2019** [comment]
这个问题有人解决了吗？
我遇到这个
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at i (umi.js:1)
    at Object.pIUS (vendors.async.js:1)
    at i (umi.js:1)
    at Object.G4Sq (vendors.async.js:1)
    at i (umi.js:1)
    at Module.m8Tn (layouts__BasicLayout.async.js:1)
    at i (umi.js:1)
    at async Promise.all (index 0)

**Comment by shanjuqiuming2019** [comment]
> 打开一下 devtools 配置。
> 
> https://github.com/ant-design/ant-design-pro/blob/a194dda616dd777a24957cf6e2e29243e15ac089/config/config.js#L73

这个是什么意思

**Comment by zkqiang** [comment]
昨晚也遇到这个问题，但后来我发现更换浏览器是没问题的，如果你也是如此，可以尝试清除浏览器缓存。

**Comment by maifine** [comment]
升级到webpack 2019年4月13号发布的v4.30.0及以后的版本就好

**Comment by mstao** [comment]
> 升级到webpack 2019年4月13号发布的v4.30.0及以后的版本就好
> 
> ## v4.30.0
> ## Bugfixes
> fix generating a null id when concatenating an entry module in a different chunk
> fix unneeded chunk references when splitting modules from chunks
> fix parsing of function name in function scope

webpack 是4.41.1，生产环境还是偶尔会出现这个问题

**Comment by maifine** [comment]
> > 升级到webpack 2019年4月13号发布的v4.30.0及以后的版本就好
> > ## v4.30.0
> > ## Bugfixes
> > fix generating a null id when concatenating an entry module in a different chunk
> > fix unneeded chunk references when splitting modules from chunks
> > fix parsing of function name in function scope
> 
> webpack 是4.41.1，生产环境还是偶尔会出现这个问题

检查是不是有子包使用了旧版本的webpack，查看下package-lock文件中所有webpack的版本号
