### ISSUE TITLE
升级后遇到的router问题

### ISSUE THREAD

**Issue by chinaxiaoyy** [ant-design/ant-design-pro#4231]
升级到Pro 2.x版本后，router.push()，url变了，但是UI没有更新的问题

一步步按照https://github.com/ant-design/ant-design-pro/commit/dc2118db78f9b2b7072051fea558e8d1386ce34c进行了配置

使用配置式路由
![WX20190521-131844](https://user-images.githubusercontent.com/20460743/58070366-5ff54d80-7bcb-11e9-9b18-074afd6a7e26.png)
![WX20190521-131925](https://user-images.githubusercontent.com/20460743/58070368-5ff54d80-7bcb-11e9-859d-9e351e79cf66.png)

**Comment by chenshuai2144** [comment]
pro 现在不支持三级目录，你可以需要将二级目录打平一下。
将所有的提到二级

**Comment by chinaxiaoyy** [comment]
好的  我试试 @chenshuai2144 送你小花花
