### ISSUE TITLE
value of InputNumber component automatically converted to a wrong value

### ISSUE THREAD

**Issue by xlszzck** [ant-design/ant-design-pro#4232]
I am using the InputNumber component without max property. 
`<InputNumber/>`
When I input '1234567890123456789012345678901234567890', the value automatically converted to '1.2345678901234568e+39'. That's wrong format. 
`<InputNumber max={9999} />`
If I set the max property, the value will automatically convert to correct format. I don't know why.

**Comment by chenshuai2144** [comment]
这是浏览器的默认行为，为了让大数更加可读。
你可以直接在控制台中输出，会得到同样的结果。
你的项目需要这个大的数字吗？

**Comment by xlszzck** [comment]
> 这是浏览器的默认行为，为了让大数更加可读。
> 你可以直接在控制台中输出，会得到同样的结果。
> 你的项目需要这个大的数字吗？

确实不需要那么大的数字，但测试人员会把这个算作BUG。
我已经改用Input组件，用正则表达式来控制了字符长度了。
谢谢解答！
