### ISSUE TITLE
npm install 报错：Downloading Chromium

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4233]
考虑一下国内的用户 除了翻墙，还有其他的办法没？  未来的墙会越来越不好翻了

用cnpm也被卡在4%

Downloading Chromium 不安装是不是也没有啥问题，不影响开发？

**Comment by chenshuai2144** [comment]
cnpm 是最好的方式。他可以解决的掉百分之 99 的问题。
