### ISSUE TITLE
独立使用Login组件Captcha设置buttonText属性失效

### ISSUE THREAD

**Issue by dumbbell0720** [ant-design/ant-design-pro#4234]
如题，有人知道这是啥情况吗？

[https://codesandbox.io/embed/kwzpoq6km7](https://codesandbox.io/embed/kwzpoq6km7)

**Comment by asanlu** [comment]
**同** 

设置`buttonText`后提示`Warning: React does not recognize the `buttonText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `buttontext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

后下载ant-design-pro，再查看到没设置`buttonText`，包里设置的是`getCaptchaButtonText`：
`              <Button
                disabled={count}
                className={styles.getCaptcha}
                size="large"
                onClick={this.onGetCaptcha}
              >
                {count ? `${count} ${getCaptchaSecondText}` : getCaptchaButtonText}
              </Button>`

`buttonText`改成用`getCaptchaButtonText`的话就行了
