### ISSUE TITLE
Warning: `defaultValue` is invalid for `getFieldDecorator` will set `value`, please use `option.initialValue` instead.

### ISSUE THREAD

**Issue by sampsonliu** [ant-design/ant-design-pro#424]
![qq 20171213103545](https://user-images.githubusercontent.com/15682051/33919018-6ba1ab8c-dff1-11e7-8102-98a4ce1c5997.png)
出现这个警告，怎么替换呢，文档没有说明哦

**Comment by chenshuai2144** [comment]
注意看[文档...](https://ant.design/components/form-cn/#components-form-demo-dynamic-rule)

**Comment by sampsonliu** [comment]
![qq 20171213104346](https://user-images.githubusercontent.com/15682051/33919237-8e865b10-dff2-11e7-81e0-03ad538b3ab0.png)
哦，正确用法是这样吧，非常感谢！
