### ISSUE TITLE
win10操作系统360浏览器兼容模式下报错？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design-pro#4246]
![lALPDgQ9qs4-YNvNAV3NA0o_842_349](https://user-images.githubusercontent.com/23158766/58146131-5c270100-7c87-11e9-9e82-80b0c7f9317a.png)

**Comment by chenshuai2144** [comment]
你配置了 target 吗？

**Comment by wo-de-ping-er** [comment]
![image](https://user-images.githubusercontent.com/23158766/58233302-4a6c5900-7d6e-11e9-8e32-f6aaaddeb1c9.png)
config.js里面进行了配置

**Comment by wo-de-ping-er** [comment]
![image](https://user-images.githubusercontent.com/23158766/58234847-1a26b980-7d72-11e9-852a-894f25a27027.png)
打包到线上  在360浏览器兼容模式下   同样会出现这样的问题

**Comment by wo-de-ping-er** [comment]
> 你配置了 target 吗？
![image](https://user-images.githubusercontent.com/23158766/58234944-5bb76480-7d72-11e9-893f-311b628f4b9e.png)
config.js里面进行了配置

**Comment by wo-de-ping-er** [comment]
![image](https://user-images.githubusercontent.com/23158766/58234971-6b36ad80-7d72-11e9-9559-a16400f8430e.png)
打包到线上 在360浏览器兼容模式下 同样会出现这样的问题

**Comment by wo-de-ping-er** [comment]
> 你配置了 target 吗？
![image](https://user-images.githubusercontent.com/23158766/58234997-7c7fba00-7d72-11e9-90b5-2e2938cd07f0.png)

打包到线上 在360浏览器兼容模式下 同样会出现这样的问题

**Comment by afc163** [comment]
看上去是网络问题？

**Comment by wo-de-ping-er** [comment]
> 看上去是网络问题？

应该不是吧。   因为我将360浏览器切换到极速模式，就可以正常显示了。

**Comment by chenshuai2144** [comment]
应该是某个 api 不支持。关掉动态分割试试

**Comment by wo-de-ping-er** [comment]
360浏览器兼容模式无法打开，经过测试发现官网提供的demo，在360浏览器兼容模式下也是无法打开的，而且360兼容模式内核使用的是IE11的内核，想问一下，这有木有解决方案啊？

**Comment by wo-de-ping-er** [comment]
> 应该是某个 api 不支持。关掉动态分割试试
经过测试发现，pro官网提供的demo，在360兼容模式下，也是无法打开的，且使用的是IE11的内核，请问一下，有木有相应的解决方案啊？

**Comment by wo-de-ping-er** [comment]
> 应该是某个 api 不支持。关掉动态分割试试

想问一下   动态分割如何关闭？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L29

**Comment by wo-de-ping-er** [comment]
> https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L29

![image](https://user-images.githubusercontent.com/23158766/59250295-75551900-8c59-11e9-8b99-1d094c88e8be.png)
我把项目里面webpackChunkName的值改为了false，360兼容模式下就可以打开了，这个属性umi官网解释只有一句话，看不太懂，请问一下，把这个属性改为false，会不会有其他影响啊？

**Comment by wo-de-ping-er** [comment]
> https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L29

![image](https://user-images.githubusercontent.com/23158766/59251914-7f791680-8c5d-11e9-8585-5ae3aae09bce.png)
解决方案：level属性值和项目内部路由配置层级保持一致或者大于项目路由层级配置即可解决360浏览器和IE11无法打开项目报错的问题。

**Comment by tudinger** [comment]
这个配置是v4的标配，并不能解决问题 @wo-de-ping-er 你有没有可以ie上可以跑的项目发我一份呢？

**Comment by wo-de-ping-er** [comment]
> 这个配置是v4的标配，并不能解决问题 @wo-de-ping-er 你有没有可以ie上可以跑的项目发我一份呢？

是这样的，我上面的解决方案将level层级大于本身路由层级设置后，项目可以在IE11或360兼容模式下打开，但是在接下来测试过程中，发现导致最初项目在浏览器打不开的原因是我项目里面使用的一个npm包不支持IE，才导致整个项目在IE浏览器里面打不开。项目的话，这个不能给你，很抱歉。个人建议检查一下：项目里面是否存在IE不支持的npm包或API。

**Comment by comiscienceknight** [comment]
> > 这个配置是v4的标配，并不能解决问题 @wo-de-ping-er 你有没有可以ie上可以跑的项目发我一份呢？
> 
> 是这样的，我上面的解决方案将level层级大于本身路由层级设置后，项目可以在IE11或360兼容模式下打开，但是在接下来测试过程中，发现导致最初项目在浏览器打不开的原因是我项目里面使用的一个npm包不支持IE，才导致整个项目在IE浏览器里面打不开。项目的话，这个不能给你，很抱歉。个人建议检查一下：项目里面是否存在IE不支持的npm包或API。

谢谢你的回复。我使用的是ant design pro v4的原项目，没有经过任何修改，他就是不能在ie11上跑。很奇怪....

**Comment by tudinger** [comment]
> 这个配置是v4的标配，并不能解决问题 @wo-de-ping-er 你有没有可以ie上可以跑的项目发我一份呢？
> 
> 是这样的，我上面的解决方案将level层级大于本身路由层级设置后，项目可以在IE11或360兼容模式下打开，但是在接下来测试过程中，发现导致最初项目在浏览器打不开的原因是我项目里面使用的一个npm包不支持IE，才导致整个项目在IE浏览器里面打不开。项目的话，这个不能给你，很抱歉。个人建议检查一下：项目里面是否存在IE不支持的npm包或API。

谢谢你的回复。我使用的是ant design pro v4的原项目，没有经过任何修改，他就是不能在ie11上跑。很奇怪....  哭啊，我好像不是一个人...

**Comment by wo-de-ping-er** [comment]
> > 这个配置是v4的标配，并不能解决问题 @wo-de-ping-er 你有没有可以ie上可以跑的项目发我一份呢？
> > 是这样的，我上面的解决方案将level层级大于本身路由层级设置后，项目可以在IE11或360兼容模式下打开，但是在接下来测试过程中，发现导致最初项目在浏览器打不开的原因是我项目里面使用的一个npm包不支持IE，才导致整个项目在IE浏览器里面打不开。项目的话，这个不能给你，很抱歉。个人建议检查一下：项目里面是否存在IE不支持的npm包或API。
> 
> 谢谢你的回复。我使用的是ant design pro v4的原项目，没有经过任何修改，他就是不能在ie11上跑。很奇怪.... 哭啊，我好像不是一个人...

[#4405](https://github.com/ant-design/ant-design-pro/issues/4405)    可以尝试一哈

**Comment by miaozilong** [comment]
我的还是不行   谁能搞定的  加下我微信  有偿帮适配下IE11

**Comment by miaozilong** [comment]
我已经试过各种方式了,加targets:{ie:11}   改dynamicImport  更新所有包  等等  都不行

**Comment by miaozilong** [comment]
WIN7  WIN10 都试过了  不行

**Comment by miaozilong** [comment]
现在我再安装虚拟机  搞一台新系统  测试

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59515771-75bc1100-8ef2-11e9-8904-9faa312fa8ee.png)

**Comment by wo-de-ping-er** [comment]
> 我已经试过各种方式了,加targets:{ie:11} 改dynamicImport 更新所有包 等等 都不行

你使用的是什么版本？

**Comment by afc163** [comment]
https://wectest1.wisedu.com/e-classroom/static/pc/layouts__BasicLayout.async.js

403 是权限问题吧？

**Comment by wo-de-ping-er** [comment]
> https://wectest1.wisedu.com/e-classroom/static/pc/layouts__BasicLayout.async.js
> 
> 403 是权限问题吧？静态文件不应该有权限。

**Comment by wo-de-ping-er** [comment]
> https://wectest1.wisedu.com/e-classroom/static/pc/layouts__BasicLayout.async.js
> 
> 403是权限问题吧？静态文件不应该有权限。

这个地址是公司测试环境地址   老哥   地址直接放在这里麻烦删除一下    上面的图片我已经删除了
