### ISSUE TITLE
在写block的过程当中，如何直接使用ant-design-pro/lib/ 当中的组件

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4247]
在写block的过程当中，如何直接使用ant-design-pro/lib/ 当中的组件，看https://github.com/ant-design/pro-blocks当中的block，是将lib下面的组件的代码Copy到block当中了。只有这么一种方式吗，还是有方法可以直接在block当中引用ant-design-pro/lib/ 中的组件呢？

另外在block当中，如何配置多路由。

**Comment by chenshuai2144** [comment]
blocks 应该只有一个页面。
我们期望停止使用 pro 的组件，转而使用 antd 中的

**Comment by xiaopanghhh** [comment]
我现在将，一个系统模块作成一个 blocks。里面包含 CRUD 。这种方式暂时没有办法通过blocks实现吗。将来有没有可能支持的可能性。
