### ISSUE TITLE
源代码中的2个小问题

### ISSUE THREAD

**Issue by qsg1215** [ant-design/ant-design-pro#4252]
第一个问题: 文件位置: src/components/Login/LoginItem.js
行号:  37行 
```
const result = onGetCaptcha ? onGetCaptcha() : null;

    if (result === false) {
      return;
    }

这样是阻止不了的result === false 得到值是false

第二个问题:在验证码登录的界面在没有输入电话的情况下的时候, 页面有个没有捕获的验证错误, 不知道是否是有意这样写的, 目的是让开发人员一眼就看到验证错误,还是出于其他原因
文件位置: src/components/Login/LoginItem.js
行号:  44行 
```
 if (result instanceof Promise) {
      result.then(this.runGetCaptchaCountDown).catch(err => {
        //这里应该有个catch
      });
    } else {
      this.runGetCaptchaCountDown();
    }

**Comment by chenshuai2144** [comment]
帮忙来个 pr？

**Comment by chenshuai2144** [comment]
已过时
