### ISSUE TITLE
Deploy request proxy_pass nginx not working

### ISSUE THREAD

**Issue by tranducit95** [ant-design/ant-design-pro#4253]
i'm using:
Backend: Laravel, environment with laradock.

The way I deploy:
I build ant pro to dist folder, use laradock's nginx to configure and run the frontend, everything is fine besides I can't request to laravel server, I don't know where I'm wrong, please help me.

p/s: I want to run the project with 2 different containers, but conflicts with port 80 and laravel, ant pro all use nginx, I don't know how to handle it, help me to run the backend laravel, frontend ant pro use docker -compose, thank you.

ant-pro.conf
```
server {
    listen 80;
    # gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    server_name admin.local;
    root /var/www/dist;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://api.local;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}
```
I tried many ways, but did not make the request to `http: // api.local`.

**Comment by chenshuai2144** [comment]
I only tell your that you config is right.
the rest can be checked by yourself.
I like to use curl to troubleshoot the problem with the proxy.
