### ISSUE TITLE
最新版的ant-design-pro，如何解决umi-request解决大的数字的精度问题

### ISSUE THREAD

**Issue by GrowingMonkey** [ant-design/ant-design-pro#4254]
后台服务端返回的id为数值类型，在数字大的情况下，返回的数据umi-request会丢失精度。如何在不修改后台的情况下解决精度丢失的问题

**Comment by chenshuai2144** [comment]
这个听起来和umi没有关系 不行转成string

**Comment by GrowingMonkey** [comment]
> 这个听起来和umi没有关系 不行转成string

是和umi没关系，这是axios本身的bug，
![image](https://user-images.githubusercontent.com/24692542/58219777-ae772900-7d3e-11e9-882b-c6ba3fc55861.png)，重写这里好像是没有用
![image](https://user-images.githubusercontent.com/24692542/58220162-5fca8e80-7d40-11e9-85e1-e906f7e8ec6f.png)
