### ISSUE TITLE
打包后在login页面重复请求/api/currentUser

### ISSUE THREAD

**Issue by zbka** [ant-design/ant-design-pro#4256]

**Comment by zbka** [comment]
为什么在登录页就会执行BasicLayout里面的方法

**Comment by SiroSong** [comment]
我的解决方法屏蔽掉相应的dispatch，让他不在请求，因为我发现当前操作用户根本也没有每次都要请求的必要。。。。。目前还没发现这样有什么不妥 ：)

**Comment by SiroSong** [comment]
> 为什么在登录页就会执行BasicLayout里面的方法

我的解决方法屏蔽掉相应的dispatch，让他不在请求，因为我发现当前操作用户根本也没有每次都要请求的必要。。。。。目前还没发现这样有什么不妥 ：)

**Comment by chenshuai2144** [comment]
权限是在BasicLayout中控制的。所以会造成这个问题。我们会再次封装
