### ISSUE TITLE
关于PageHeader组件中tabList的使用建议

### ISSUE THREAD

**Issue by tyyzqmf** [ant-design/ant-design-pro#426]
## 现在的使用方式：
```
const tabList = [{
  key: '1',
  tab: '页签一',
}, {
  key: '2',
  tab: '页签二',
}, {
  key: '3',
  tab: '页签三',
}];

<PageHeader
      ...
      tabList={tabList}
    />
```
## 问题
没有把<TabPane>的内容封装进去，点击tab没有内容变化（参考https://preview.pro.ant.design/#/profile/advanced）

## 解决方案
```
<Tabs
  className={styles.tabs}
  defaultActiveKey={(tabDefaultValue && tabDefaultValue.key)}
  onChange={this.onChange}
  >
  {
    tabList.map(item => <TabPane tab={item.tab} key={item.key}>{item.content}</TabPane>)
    }
</Tabs>
```
[例子](https://github.com/tyyzqmf/ant-design-pro/blob/366afd1ecec93143bbfe8cc478092e092975c779/src/components/PageHeader/index.js#L144-L152)

```
const tabList = [{
  key: 'detail',
  tab: '详情',
  connect: (<div>详情</div>),
}, {
  key: 'rule',
  tab: '规则',
  connect: (<div>规则</div>),
}];
```
[例子](https://github.com/tyyzqmf/ant-design-pro/blob/366afd1ecec93143bbfe8cc478092e092975c779/src/routes/Profile/AdvancedProfile.js#L62-L70)

## 建议
这样虽然能解决问题，但是感觉会使PageHeader组件变得很重，是否考虑单独抽一个Tab组件出来？

**Comment by chenshuai2144** [comment]
点击tab之后通过redux 或者react-router来渲染是最好的办法.方便刷新页面之后也能回到这一页.

**Comment by tyyzqmf** [comment]
@chenshuai2144 有参考例子吗

**Comment by tyyzqmf** [comment]
类似这种？https://preview.pro.ant.design/#/list/cover-card-list

**Comment by chenshuai2144** [comment]
@tyyzqmf  对..这样更好一点.你不想刷新页面,可以单独配置路由的content上.

**Comment by tyyzqmf** [comment]
感觉怪怪的，这与Tab的概念都不一致了，变成了跳转页面的形式了

**Comment by chenshuai2144** [comment]
PageHeader 本来就不是个标准的tab .

**Comment by tyyzqmf** [comment]
好的  谢谢你   几种方法我都试试

**Comment by jiahaodongt** [comment]
``
