### ISSUE TITLE
面包屑不会变成的链接问题

### ISSUE THREAD

**Issue by chenzhenjia** [ant-design/ant-design-pro#4262]
路由配置为 
```
{
    name: '管理',
    icon: 'snippets',
    path: '/table',
    routes: [
        {
            name: '列表',
            path: '/table/list',
            component: './Table/List',
        },
        {
            name: '详情',
            path: '/table/list/detail',
            component: './Table/Detail',
            hideInMenu: true,
        },
    ],
},
```
但是发现面包屑的列表不能点击，发现是 `src/components/PageHeaderWrapper/breadcrumb.js`  的bug,我把 `breadcrumb.js` 改了两个地方 [第19行](https://github.com/chenzhenjia/ant-design-pro/blob/2de6122ff43714a29b2b5d526711653d1e63e3d7/src/components/PageHeaderWrapper/breadcrumb.js#L19) 和 [第83行](https://github.com/chenzhenjia/ant-design-pro/blob/2de6122ff43714a29b2b5d526711653d1e63e3d7/src/components/PageHeaderWrapper/breadcrumb.js#L83)，然后就可以根据以上路由配置显示链接。

**Comment by chenshuai2144** [comment]
是故意这么做的没，如果你的业务需要自行改动就好了

**Comment by 1009466147** [comment]
但是设置了component的path也没有生成链接，如下路由

**Comment by 1009466147** [comment]
` routes: [
                {
                  path: '/userManage/userList',
                  name: '用户列表',
                  component: '../layouts/BlankLayout',
                  routes: [
                    
                    {
                      path: '/userManage/userList/userDetail/:userId?',
                      name: '用户详情',
                      hideInMenu:true,
                      component: './userManage/userList/userDetail',
                    },
                    {
                      component: './userManage/userList'
                    }
                  ]`

**Comment by 1009466147** [comment]
` {
              path: '/userManage',
              name: '用户',
              icon: 'user',
              
              routes: [
                {
                  path: '/userManage/userList',
                  name: '用户列表',
                  component: '../layouts/BlankLayout',
                  routes: [
                    
                    {
                      path: '/userManage/userList/userDetail/:userId?',
                      name: '用户详情',
                      hideInMenu:true,
                      component: './userManage/userList/userDetail',
                    },
                    {
                      component: './userManage/userList'
                    }
                  ]
                },
                {
                  path: '/main/account',
                  name: '领地列表',
                  component: './main/account',
                },
                {
                  path: '/main/loginlog',
                  name: '机器人列表',
                  component: './main/loginlog',
                },
              ],
            }`

**Comment by www521lq** [comment]
第19行 和 第83行  改了什么？
