### ISSUE TITLE
在BasicLayout里加入转场动画，使用TransitionGroup和CSSTransition在console里会报redirect错，请问下怎么解决呢~

### ISSUE THREAD

**Issue by ZhangXY-Magic** [ant-design/ant-design-pro#4264]
在BasicLayout里加入TransitionGroup包裹children后，跳转页面console里面报You tried to redirect to the same route you're currently on: "/dashboard"类似的错误，尝试在AuthorizedRoute中用Switch包裹Route没作用，请问下如何能解决这种问题呢~

**Comment by chenshuai2144** [comment]
@sorrycc   umi 现在有转场动画的方案吗？

**Comment by sorrycc** [comment]
https://umijs.org/guide/router.html#route-transition-effects

**Comment by a88053443** [comment]
@sorrycc  按照umi的配置在children外包裹的TransitionGroup和CSSTransition，会报出
**Check the render method of `TransitionGroup`.**
umi的路由动效在pro这里是不是不适用？

**Comment by ZhangXY-Magic** [comment]
@chenshuai2144 请问下 现在antd pro有预计做路由动效的计划么~

**Comment by chenshuai2144** [comment]
暂时没有，路由动效感觉华而不实。我们更希望加快加载速度

**Comment by websmallrabbit** [comment]
跪求专场动画

**Comment by websmallrabbit** [comment]
@sorrycc 自己做umi 插件可以实现转场动画么
