### ISSUE TITLE
卡片列表 操作按钮 文字换为Icon图标 样式错乱

### ISSUE THREAD

**Issue by leitongda** [ant-design/ant-design-pro#4265]
![image](https://user-images.githubusercontent.com/22727241/58236346-4bed4f80-7d75-11e9-91ea-ee879d4b7c1b.png)

**Comment by leitongda** [comment]
![image](https://user-images.githubusercontent.com/22727241/58236867-6d027000-7d76-11e9-82cf-ea23f015d4f2.png)


`\src\pages\List\CardList.js`76行，加代码：
```
<Card hoverable className={styles.card} actions={[<a>操作一</a>, <a>操作二</a>, item.id === "fake-list-2" ? <Icon type="close" /> : null]}>
```

**Comment by chenshuai2144** [comment]
用 css 处理一下高度，设置为定高
