### ISSUE TITLE
无法注册pro.ant.design用户

### ISSUE THREAD

**Issue by Bupterambition** [ant-design/ant-design-pro#4266]
https://preview.pro.ant.design/user/register 无法注册用户，手机验证码一直收不到

**Comment by wangchong19940101** [comment]
具体逻辑还需要自己写。人家好像都没有发起请求吧

**Comment by afc163** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/507615/58242388-4eee3d00-7d81-11e9-9f94-913fe64fa555.png">
