### ISSUE TITLE
基于Tab建立三级路由，跳转不过去

### ISSUE THREAD

**Issue by wangchong19940101** [ant-design/ant-design-pro#4267]
![image](https://user-images.githubusercontent.com/30942709/58240145-f9b02c80-7d7c-11e9-90a2-360859612b5f.png)
![image](https://user-images.githubusercontent.com/30942709/58240471-9d99d800-7d7d-11e9-8b69-3931f1cda83f.png)

**Comment by wangchong19940101** [comment]
具体需求为在当前Tab下，进入详情页，父级tab不变，内容变化

**Comment by wangchong19940101** [comment]
请大佬指教

**Comment by chenshuai2144** [comment]
pro 这个例子很明显吧

**Comment by wangchong19940101** [comment]
我建立了这层路由，但是并没有跳转，大佬 @chenshuai2144 
![image](https://user-images.githubusercontent.com/30942709/58392964-05e30500-806f-11e9-877f-1730e31889f1.png)

**Comment by wangchong19940101** [comment]
const {children} = this.props;这是不是需要和children搭配
