### ISSUE TITLE
DatePicker 在 model="year"时无法选中

### ISSUE THREAD

**Issue by superchow** [ant-design/ant-design-pro#4268]
"antd": "^3.11.6"

**Comment by superchow** [comment]
"antd": "^3.11.6"

**Comment by chenshuai2144** [comment]
l来个可重现的 demo

**Comment by superchow** [comment]
> l来个可重现的 demo

[Date-picker-bug.zip](https://github.com/ant-design/ant-design-pro/files/3230335/Date-picker-bug.zip)

选中年份无法回填值

**Comment by chenshuai2144** [comment]
需要一个在线的， 用 codebox 之类的搞一个。最好用最新的 antd。旧版本的 bug 我们也无法修正

**Comment by superchow** [comment]
> 需要一个在线的， 用 codebox 之类的搞一个。最好用最新的 antd。旧版本的 bug 我们也无法修正

用的旧版本😵

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15572#issuecomment-475476135
