### ISSUE TITLE
错误代码，仍能编译成功

### ISSUE THREAD

**Issue by LittleBreak** [ant-design/ant-design-pro#4269]
![image](https://user-images.githubusercontent.com/16707072/58248683-5a486500-7d8f-11e9-92a0-6d123644162f.png)

src\layouts\BasicLayout.js
例：这里添加一个未定义的函数，编译仍能成功。只能在浏览器里看到错误信息。

为什么可以编译成功呢，是有参数控制吗？

**Comment by chenshuai2144** [comment]
js 是一个脚本语言，他在需要使用的时候才会进行编译和解释。
https://zh.wikipedia.org/zh-hans/%E8%84%9A%E6%9C%AC%E8%AF%AD%E8%A8%80

**Comment by LittleBreak** [comment]
对这块不太了解，这种级别的错误可不可以通过eslint等相关的功能禁止编译成功呢

**Comment by afc163** [comment]
看下我们的 eslint 配置是不是有问题。@chenshuai2144

**Comment by chenshuai2144** [comment]
yarn dev 的时候不会触发 eslint 的检查的，他的 ide 也没装 eslint 插件。

**Comment by afc163** [comment]
可以开启一下。https://umijs.org/guide/env-variables.html#eslint

**Comment by LittleBreak** [comment]
@afc163 好的，谢谢
