### ISSUE TITLE
按照文档中使用 G2 绘制图表,配置后系统运行报错

### ISSUE THREAD

**Issue by kingmoumoumou** [ant-design/ant-design-pro#427]
??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22 Uncaught Error: please specify the canvas container Id !
    at o (??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22)
    at l (??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22)
    at Object.y [as Chart] (??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22)
    at Analysis.renderChart (Analysis.js?56ca:104)
    at Analysis.componentDidMount (Analysis.js?56ca:43)
    at commitLifeCycles (react-dom.development.js?cada:8770)
    at commitAllLifeCycles (react-dom.development.js?cada:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)
o @ ??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22
l @ ??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22
y @ ??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22
renderChart @ Analysis.js?56ca:104
componentDidMount @ Analysis.js?56ca:43
commitLifeCycles @ react-dom.development.js?cada:8770
commitAllLifeCycles @ react-dom.development.js?cada:9946
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
commitRoot @ react-dom.development.js?cada:10050
performWorkOnRoot @ react-dom.development.js?cada:11017
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise resolved (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise resolved (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
scheduleTopLevelUpdate @ react-dom.development.js?cada:11193
updateContainer @ react-dom.development.js?cada:11231
(anonymous) @ react-dom.development.js?cada:15226
unbatchedUpdates @ react-dom.development.js?cada:11102
renderSubtreeIntoContainer @ react-dom.development.js?cada:15225
render @ react-dom.development.js?cada:15290
render @ index.js?4380:126
start @ index.js?4380:68
(anonymous) @ index.js?1fdf:28
(anonymous) @ index.js:3685
__webpack_require__ @ index.js:708
fn @ index.js:113
(anonymous) @ index.js:3341
__webpack_require__ @ index.js:708
(anonymous) @ index.js:806
(anonymous) @ index.js:809
react-dom.development.js?cada:9747 The above error occurred in the <Analysis> component:
    in Analysis (created by Connect(Analysis))
    in Connect(Analysis) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by BasicLayout)
    in Switch (created by BasicLayout)
    in div (created by BasicLayout)
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter (created by BasicLayout)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route
    in Switch
    in Router
    in LocaleProvider
    in Provider
    in Unknown

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?cada:9747
captureError @ react-dom.development.js?cada:10540
commitRoot @ react-dom.development.js?cada:10058
performWorkOnRoot @ react-dom.development.js?cada:11017
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise resolved (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise resolved (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
scheduleTopLevelUpdate @ react-dom.development.js?cada:11193
updateContainer @ react-dom.development.js?cada:11231
(anonymous) @ react-dom.development.js?cada:15226
unbatchedUpdates @ react-dom.development.js?cada:11102
renderSubtreeIntoContainer @ react-dom.development.js?cada:15225
render @ react-dom.development.js?cada:15290
render @ index.js?4380:126
start @ index.js?4380:68
(anonymous) @ index.js?1fdf:28
(anonymous) @ index.js:3685
__webpack_require__ @ index.js:708
fn @ index.js:113
(anonymous) @ index.js:3341
__webpack_require__ @ index.js:708
(anonymous) @ index.js:806
(anonymous) @ index.js:809
??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22 Uncaught (in promise) Error: please specify the canvas container Id !
    at o (??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22)
    at l (??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22)
    at Object.y [as Chart] (??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22)
    at Analysis.renderChart (Analysis.js?56ca:104)
    at Analysis.componentDidMount (Analysis.js?56ca:43)
    at commitLifeCycles (react-dom.development.js?cada:8770)
    at commitAllLifeCycles (react-dom.development.js?cada:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js?cada:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:581)
    at invokeGuardedCallback (react-dom.development.js?cada:438)
o @ ??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22
l @ ??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22
y @ ??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js:22
renderChart @ Analysis.js?56ca:104
componentDidMount @ Analysis.js?56ca:43
commitLifeCycles @ react-dom.development.js?cada:8770
commitAllLifeCycles @ react-dom.development.js?cada:9946
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
commitRoot @ react-dom.development.js?cada:10050
performWorkOnRoot @ react-dom.development.js?cada:11017
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise resolved (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
enqueueSetState @ react-dom.development.js?cada:6212
Component.setState @ react.development.js?99ee:237
(anonymous) @ dynamic.js?9a9f:99
Promise resolved (async)
load @ dynamic.js?9a9f:96
DynamicComponent @ dynamic.js?9a9f:82
constructClassInstance @ react-dom.development.js?cada:6355
updateClassComponent @ react-dom.development.js?cada:7839
beginWork @ react-dom.development.js?cada:8225
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
requestWork @ react-dom.development.js?cada:10878
scheduleWorkImpl @ react-dom.development.js?cada:10732
scheduleWork @ react-dom.development.js?cada:10689
scheduleTopLevelUpdate @ react-dom.development.js?cada:11193
updateContainer @ react-dom.development.js?cada:11231
(anonymous) @ react-dom.development.js?cada:15226
unbatchedUpdates @ react-dom.development.js?cada:11102
renderSubtreeIntoContainer @ react-dom.development.js?cada:15225
render @ react-dom.development.js?cada:15290
render @ index.js?4380:126
start @ index.js?4380:68
(anonymous) @ index.js?1fdf:28
(anonymous) @ index.js:3685
__webpack_require__ @ index.js:708
fn @ index.js:113
(anonymous) @ index.js:3341
__webpack_require__ @ index.js:708
(anonymous) @ index.js:806
(anonymous) @ index.js:809
warning.js?6327:33 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the Analysis component.

**Comment by kingmoumoumou** [comment]
文档地址: https://pro.ant.design/docs/graph-cn

**Comment by chenshuai2144** [comment]
查看 #236, 重复了哥们
