### ISSUE TITLE
问题：ant design pro是不是不再区分开发和生产的构建？Question: are there different build for development and production?

### ISSUE THREAD

**Issue by ericxinzhang** [ant-design/ant-design-pro#4271]
直接用webpack的项目一般都会有两个配置文件，一个是对开发环境的，build的时候会包括source map等，另一个是对production环境的，会最小化js和source map等。

ant design pro里貌似只有一个构建命令了？是不是假设开发环境就是用umi dev, 而build就是生产的构建？我也查看了umi的文档，只是提到可以针对不同环境有不同的config.js 但是没有给出具体的例子，只在https://umijs.org/zh/guide/env-variables.html 里提到了一些环境变量。

作为一个webpack的用户，我能否找到一些具体的例子，怎么才能在config.js里进行细粒度的设置，例如source map, uglify等等。谢谢！

-------------

For projects using webpack, we usually have two config files, one for development and one for production. They provide fine-grained config for development / production build & bundling.

However in Ant Design Pro I see only one build NPM command. Can I assume in development environment we just use `npm start` which runs `umi dev`, while `npm run build` does the build for production? I also checked the umi document, it only mentions that we can have multiple config.js, one for each env but does not provide detailed examples, with a few environment variables provided at https://umijs.org/zh/guide/env-variables.html.

As a developer familiar with webpack, I am wondering if you could provide some examples on how I could do the fine-grained config (such as source map, uglify, etc) like what I can do in webpack config. 

Thank you very much for your help.

**Comment by chenshuai2144** [comment]
umi 希望用户对这些无感的。 如果不是非常必要使用默认的也是完全 ok 的。
congfig.js 中可以用环境变量的。
https://github.com/ant-design/ant-design-pro/blob/a194dda616dd777a24957cf6e2e29243e15ac089/config/config.js#L10

**Comment by ericxinzhang** [comment]
> umi 希望用户对这些无感的。 如果不是非常必要使用默认的也是完全 ok 的。
> congfig.js 中可以用环境变量的。
> https://github.com/ant-design/ant-design-pro/blob/a194dda616dd777a24957cf6e2e29243e15ac089/config/config.js#L10

谢谢你的回答。config里面可以用环境呢变量我知道，我再仔细看一遍umi config有哪些可以设置吧：https://umijs.org/zh/config/
