### ISSUE TITLE
request docs cannot be open 

### ISSUE THREAD

**Issue by qxchen6** [ant-design/ant-design-pro#4272]
## 1.docs missing
we need docs .
[this url cannot be open](https://bigfish.alipay.com/doc/api#request)
## 2.how to handle OPTIONS request ?
how to handle OPTIONS request when using CORS ? 'request' tool did not send the real request after receiving the response of OPTIONS ......

**Comment by qxchen6** [comment]
the doc url is written in ant-design-pro:@/src/utils/request.js , at the top of file .

OPTIONS request are not recognized .

so,where can i find the docs of ant-design-pro's request tool ?

and how to send CORS request ?

there is no problem when i'm using js-fech api   , but the ant-design-pro's request tool can not continue when the OPTIONS request responded .

**Comment by chenshuai2144** [comment]
This is our intranet link, you should use[  npm/umi-request](https://github.com/umijs/umi-request)
