### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by dengyao** [ant-design/ant-design-pro#4273]
v2.3.1 npm install 出现
code E404
npm ERR! 404 Not Found - GET https://cdn.npm.taobao.org/electron-to-chromium/-/electron-to-chromium-1.3.137.tgz
npm ERR! 404 
npm ERR! 404  'electron-to-chromium@^1.3.133' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ant-design-pro'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
Not Found - GET https://cdn.npm.taobao.org/electron-to-chromium/-/electron-to-chromium-1.3.137.tgz

**Comment by afc163** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1469
https://github.com/cnpm/cnpm/issues/287

**Comment by fengmk2** [comment]
fixed
