### ISSUE TITLE
如何在一个页面下的models去触发另一个页面的model

### ISSUE THREAD

**Issue by zbka** [ant-design/ant-design-pro#4274]

**Comment by rodchen-king** [comment]
1. 组件调用model方式
![image](https://user-images.githubusercontent.com/19780441/58397932-9a586200-8085-11e9-8a30-ecc94f47a9d1.png)

2. 在model调用方式将dispatch改为put
![image](https://user-images.githubusercontent.com/19780441/58397964-b3f9a980-8085-11e9-9fb7-c8c7b662fbfd.png)
