### ISSUE TITLE
build上线后请求不到后端接口

### ISSUE THREAD

**Issue by mxthd** [ant-design/ant-design-pro#4277]
我把build后的文件上传到静态空间后,网页无法请求到后端接口

本地使用`npm start`启动是正常的

**Comment by mxthd** [comment]
@chenshuai2144 Hi

**Comment by mxthd** [comment]
![image](https://user-images.githubusercontent.com/15605929/58306810-5cfa9700-7e2f-11e9-9135-9d6bc6313780.png)
![Uploading image.png…]()

请求是404,返回的内容是: Sorry, we need js to run correctly!

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn

**Comment by mxthd** [comment]
> https://pro.ant.design/docs/deploy-cn

@chenshuai2144  你好,我是使用 `npm run build` 打包后将dist文件夹的内容上传到了静态服务器

且前端界面能正常打开,但是请求后端时报404

**Comment by mxthd** [comment]
![image](https://user-images.githubusercontent.com/15605929/58322972-2b94c200-7e55-11e9-8377-e9f7f985d073.png)

**Comment by chenshuai2144** [comment]
。。。api 是要自己实现的 build 的出来的只有前端

**Comment by mxthd** [comment]
@chenshuai2144  昨天晚上已经好了,原因是后端的请求还需要nginx去代理到后端

> 对于发布来讲，只需要将最终生成的静态文件，也就是通常情况下 dist 文件夹的静态文件发布到你的 cdn 或者静态服务器即可

我以为把生成的静态文件部署到 oss 纯静态空间就行了,没想到请求后端的还需要nginx去代理

已解决,Thank ~
