### ISSUE TITLE
Modal 内嵌table，rowSelection checkBox选中状态缓存清除不掉

### ISSUE THREAD

**Issue by mysky621** [ant-design/ant-design-pro#4279]
const menuRowSelection = {
      selectedMenuRowKeys,
      onChange: this.onSelectChange,
    };
    return (
      <Modal
        title="添加菜品"
        closable={false}
        visible={visible}
        onCancel={()=> this.onHandleCancel()}
        onOk={()=> this.onHandleOk()}
        // footer={[]}
        keyboard='true'
        width={800}
      >
        <Button type="primary" onClick={()=> this.setState({selectedMenuRowKeys: [] })}>
          Reload
        </Button>
        <Table
          rowKey="id"
          columns={menuVarietieColumns}
          rowSelection={menuRowSelection}
          dataSource={varietieList && varietieList}
        />
      </Modal>
清除：  
<Button type="primary" onClick={()=> this.setState({selectedMenuRowKeys: [] })}>
         Reload
 </Button>
menuRowSelection 对象：
 const menuRowSelection = {
      selectedMenuRowKeys,
      onChange: this.onSelectChange,
   };
onSelectChange 选中：
  onSelectChange = selectedMenuRowKeys => {
    this.setState({ selectedMenuRowKeys });
  };
点击Reload，表格中checkBox选中状态清除不掉
不内嵌在model中是正常的，已测试！！！！
求大佬解惑。。。。。

**Comment by rodchen-king** [comment]
selectedMenuRowKeys你用的哪个版本的ant design，没见过这个属性。
