### ISSUE TITLE
umi:not found

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design-pro#4282]
从淘宝源切到npm insatll 后打包错误，umi：not found 是什么原因啊

**Comment by Lind-pro** [comment]
你要安装UMI吧。。https://umijs.org/zh/guide/getting-started.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87

**Comment by chenshuai2144** [comment]
安装 umi 失败了。你可以用 cnpm install --by=npm
