### ISSUE TITLE
向后端传字符串出现两个引号问题

### ISSUE THREAD

**Issue by lemoncy** [ant-design/ant-design-pro#4285]
ant-design-pro 向后端传输String，多出一个引号。
请问这是什么原因导致。我这边使用PostMan测试是正常的。

以下为ant-design-pro 向后端传输String：
![image](https://user-images.githubusercontent.com/3096214/58325836-9ba74600-7e5d-11e9-903f-003b062cfe71.png)

![image](https://user-images.githubusercontent.com/3096214/58325881-bc6f9b80-7e5d-11e9-8871-7eda55f2a4aa.png)

以下postMan 向后端传输String：
![image](https://user-images.githubusercontent.com/3096214/58325793-7c101d80-7e5d-11e9-91a4-0cd109117d75.png)

![image](https://user-images.githubusercontent.com/3096214/58325748-55ea7d80-7e5d-11e9-970d-a2669841fc3f.png)

**Comment by chenshuai2144** [comment]
你的传输的 key 怎么不见了。要用 `{id:"xxxxx"}`，
至于多了 ""，是因为使用 json.stringify。会把字符串给格式化一下，加上 json 规范中的""

**Comment by lemoncy** [comment]
@chenshuai2144 好的，谢谢哈。

**Comment by ryr1990** [comment]
> 你的传输的 key 怎么不见了。要用 `{id:"xxxxx"}`，
> 至于多了 ""，是因为使用 json.stringify。会把字符串给格式化一下，加上 json 规范中的""
请教下，使用 json.stringify后，首尾多余的双引号如何去掉？ 后端报无法转换成Json对象
