### ISSUE TITLE
如何实现根据后端指定path和component生成动态路由

### ISSUE THREAD

**Issue by mxthd** [ant-design/ant-design-pro#4286]
类似问题: https://github.com/ant-design/ant-design-pro/issues/3360

后端会把path和component等路由信息返回给前端, 然后生成路由 ,而不是写在router.config.js

**Comment by mxthd** [comment]
一般解决方法是 [动态菜单] 和 给[路由权限] 不满足我的需求

**Comment by rodchen-king** [comment]
> 一般解决方法是 [动态菜单] 和 给[路由权限] 不满足我的需求

动态菜单不满足，你的意思是：后台返回的并不是一个可以直接使用的数据结构，还是什么意思？

**Comment by mxthd** [comment]
> > 一般解决方法是[动态菜单]和给[路由权限]不满足我的需求
> 
> 动态菜单不满足，你的意思是：后台返回的并不是一个可以直接使用的数据结构，还是什么意思？

后台返回的是router.config.js的结构,然后生成路由

**Comment by rodchen-king** [comment]
1. 那你直接将这个数据赋值到src\layouts\BasicLayout.js中的getMenuData不行吗？
2. 我之前做页面权限，是将具体页面取一个资源代码存在后台，然后用户登陆的时候再过来遍历处理那些页面可以显示
![image](https://user-images.githubusercontent.com/19780441/58398046-194d9a80-8086-11e9-9b52-362e888d448a.png)

**Comment by mxthd** [comment]
> 1. 那你直接将这个数据赋值到src\layouts\BasicLayout.js中的getMenuData不行吗？
> 2. 我之前做页面权限，是将具体页面取一个资源代码存在后台，然后用户登陆的时候再过来遍历处理那些页面可以显示
>    ![image](https://user-images.githubusercontent.com/19780441/58398046-194d9a80-8086-11e9-9b52-362e888d448a.png)

这样是可以动态菜单, 但是不是动态路由. ps:貌似ant design pro也就支持配置式路由和约定式路由, 不知道vue版的是如何实现动态路由的,我不会vue

**Comment by rodchen-king** [comment]
@mxthd 好吧，我一开始的理解有问题。

**Comment by mxthd** [comment]
> @mxthd 好吧，我一开始的理解有问题。

看来目前只能用动态菜单解决啦 ~  谢谢大哥

**Comment by exvu** [comment]
@mxthd 你现在解决这个问题了吗，我的需求和您一样，也是希望提供运行后手动更新routes的方法，

**Comment by mxthd** [comment]
> @mxthd 你现在解决这个问题了吗，我的需求和您一样，也是希望提供运行后手动更新routes的方法，

看了chenshuai2144对类似帖的回复，应该是做不到这种机制，只能 实现约定书路由

**Comment by mxthd** [comment]
后面能解决的话更好 ~
