### ISSUE TITLE
我就想问有没有和asp.net core一起的实例

### ISSUE THREAD

**Issue by haoljp** [ant-design/ant-design-pro#4287]
我就想问有没有和asp.net core一起的实例

**Comment by chenshuai2144** [comment]
最好陈述一下你遇到了什么问题，我们不可能每个语言都加一个说明的。

**Comment by haoljp** [comment]
我意思有没有asp.net core作为后台服务， ant design pro作前端调用的demo参考学习下。

**Comment by afc163** [comment]
https://www.zhihu.com/question/57766078
