### ISSUE TITLE
水波图不能用呀 圖出不來呀

### ISSUE THREAD

**Issue by kinkievan** [ant-design/ant-design-pro#429]
水波图不能用呀
"ant-design-pro": "^0.3.0",
"antd": "^3.0.0",
出不來呀

**Comment by chenshuai2144** [comment]
报错日志?
是否pull最新的项目实现?
图标正在重构...你也可以耐心等待.

**Comment by kinkievan** [comment]
有更新
![default](https://user-images.githubusercontent.com/14817714/33925748-45df550a-e016-11e7-8ba4-d115321b4dea.PNG)

**Comment by chenshuai2144** [comment]
@nikogu 来看看....

**Comment by kinkievan** [comment]
等你回覆 謝謝

**Comment by nikogu** [comment]
@kinkievan 浏览器版本？

**Comment by kinkievan** [comment]
![default](https://user-images.githubusercontent.com/14817714/33975823-2471aeca-e0cc-11e7-8884-9b0862d69da7.PNG)

**Comment by kinkievan** [comment]
![default](https://user-images.githubusercontent.com/14817714/33975841-3e8d1b78-e0cc-11e7-96a8-5948e699d741.PNG)

**Comment by nikogu** [comment]
@kinkievan 你访问官网是好的吗，目测感觉是因为浏览器样式渲染在 js 执行之后的问题

**Comment by kinkievan** [comment]
官網沒問題

**Comment by kinkievan** [comment]
![default](https://user-images.githubusercontent.com/14817714/34242815-8e37ea4a-e658-11e7-8e37-ee791aaa3f8d.PNG)

**Comment by ddcat1115** [comment]
chrome 下测试 ok 的

**Comment by nikogu** [comment]
@kinkievan 你用 build 以后的代码试试，然后本地加个 setTimeout 延迟调试下，看看是否是因为样式加载在 js 之后的原因

**Comment by hqwlkj** [comment]
我也遇到过这个问题，我感觉是 pro 官网没有问题，应为是 数值是写固定的；若果是从服务端动态获取之后就会出现类似的问题。

@nikogu

**Comment by kinkievan** [comment]
何時才能修好呢

**Comment by joeyFuck** [comment]
试着自己改改呗

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34551688-235c3f64-f157-11e7-961f-3fcd3a250a28.png)

有点错位

**Comment by nikogu** [comment]
@hqwlkj 官网也不是固定的，一样是异步的。

**Comment by nikogu** [comment]
已经升级 Bizcharts，如果有问题再 reopen。

**Comment by YuZongYangHi** [comment]
这个问题貌似我又浮现了:

 "antd": "^4.12.0"
 "bizcharts": "^4.1.9",
 "bizcharts-plugin-slider": "^2.1.1-beta.1",


![image](https://user-images.githubusercontent.com/35584408/112811649-dd832200-90ae-11eb-9812-2c0b28b3b415.png)

**Comment by YuZongYangHi** [comment]
> 已经升级 Bizcharts，如果有问题再 reopen。

按照官网的例子复制， 发现只能绘制出一半
