### ISSUE TITLE
git commit的prettier设置问题，注释自动换行的情况。

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#4292]
1. 如图：代码注释的位置并不是紧跟着代码的后面
![image](https://user-images.githubusercontent.com/19780441/58392049-c4505b00-806a-11e9-9c82-33281be50912.png)

2. 如图：当我git commit代码，注释会自动换行
![image](https://user-images.githubusercontent.com/19780441/58392184-62442580-806b-11e9-919f-f7442c4f8eb8.png)

3. printWidth设置了200
![image](https://user-images.githubusercontent.com/19780441/58392192-6e2fe780-806b-11e9-9804-b03ba8fc37ad.png)

所以想问一下，这个现象是由于什么原因导致的？

**Comment by chenshuai2144** [comment]
prettier 的规范是注释在要注释的内容上方

```
// this is  user name
const name= "Jack"
```

**Comment by chenshuai2144** [comment]
prettier 的规范是注释在要注释的内容上方

```
// this is  user name
const name= "Jack"
```
