### ISSUE TITLE
ts中我form组件设置conf参数，提示问题

### ISSUE THREAD

**Issue by liuzeyang** [ant-design/ant-design-pro#4296]
![image](https://user-images.githubusercontent.com/15833097/58404918-dc3ed380-8098-11e9-88a1-7a0aa9c05eb9.png)
报错，我在basictable中createForm，然后提示报错。

**Comment by chenshuai2144** [comment]
你需要将原来的 FromProps 作为泛型传入 create 方法
```
const App = Form.create<UserFormProps>({
  // ...
})(UserForm);

```
