### ISSUE TITLE
各位大神能否提供一个定时任务表达式组件？或者帮忙改写一下，ant不太熟识？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#4297]
![image](https://user-images.githubusercontent.com/37643958/58407632-d2b86a00-809e-11e9-843d-6fb9ea15958b.png)
预览地址：https://1615450788.github.io/vue-cron/dist/index
vue版本代码：https://github.com/1615450788/vue-cron

react不太熟识，哪位大神能提供或者帮忙改写一下cron表达式组件，万分感谢各位！

**Comment by lweizhoucn** [comment]
https://github.com/liudongrong/cron-editor
