### ISSUE TITLE
how to hide or remove only cancel button modal popup 

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#4298]
i just want to remove only cancel button on modal popup , i have tried giving footer={null} but here , both ok and cancel button are getting hidden please suggest some good solution

**Comment by rodchen-king** [comment]
You should customize the footer button with adding save button in footer, like following:

![新建位图图像 (2)](https://user-images.githubusercontent.com/19780441/58444060-d690ce80-8128-11e9-93c8-1617bc235e9b.jpg)

**Comment by THARAKS** [comment]
ok thank you :)
