### ISSUE TITLE
Support fixed menu and header

### ISSUE THREAD

**Issue by lawrence-peng** [ant-design/ant-design-pro#43]
滚动条出现全屏的滚动的区域不够友好

**Comment by nikogu** [comment]
这个具体指的是？

**Comment by lawrence-peng** [comment]
比如说：dashboard->分析页 
滚动条应该控制在分析页里出现，而不是在body出现

**Comment by lawrence-peng** [comment]
总结来说，就是左边的Menu单独滚动，右边的部分，应该在面包屑下面正文滚动。

**Comment by tryrefine** [comment]
嗯，同意 @lawrence-peng 的观点，左边的菜单和顶部的菜单部分，应该固定住。
建议页面布局：
1. 整体分上下两部分，上面是 logo 跟一些必要的，跟左边菜单不一样的导航菜单。
2. 下面又分左右两部分，左边菜单，右边是页面变更的主要区域。
3. 下面的右边部分，其实又分上下两部分，最下面是 footer，footer 跟页面正文一起滚动。就跟现在是一样的。看起来是一部分而已。

**Comment by afc163** [comment]
这个其实是一种设计抉择，并不是说哪一种就一定更好。例如 https://adminlte.io/preview 就是和我们类似，当然也有 admin 是和 @lawrence-peng 描述的一致。我们会再内部讨论一下。

**Comment by tryrefine** [comment]
如果能参考 adminlte 的可配置的方式，当然就更加完善了，adminlte 可配置菜单的上面部分和左面是否固定，另外还可以换肤。这些功能都加上的话，那就太太太太....赞了，希望能参考一下 adminlte 的这种可配置的方式。

 adminlte 的配置，大概是这样子的：

Layout Options

Fixed layout
Activate the fixed layout. You can't use fixed and boxed layouts together

**Comment by afc163** [comment]
@tryrefine 这块在我们的计划中。

**Comment by tryrefine** [comment]
哦，那就好，那就好，期待越来越强大越来越完美，感谢你们！

**Comment by mantou-kk** [comment]
这个有道理分享一个我见过点得最爽的页面

**Comment by jabezGit** [comment]
左边菜单和导航条是否滚动做成可配置的多好呀，期待期待。。。

**Comment by WuJiY** [comment]
期待

**Comment by chenshuai2144** [comment]
#717 二期中有个子选项实现了这个功能

**Comment by chenshuai2144** [comment]
v2版本会解决。
尽请期待

**Comment by tudinger** [comment]
确实~ 这个暂时只能自己调整css弄了
