### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#4300]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/507615/58471015-82600b80-8175-11e9-9bb1-874aa080222e.png">

**Comment by keke122765** [comment]
解决了吗？

**Comment by chenshuai2144** [comment]
无法在线，估计是在转化 ts 的时候顺便好了

**Comment by keke122765** [comment]
我是在ie10上出现的这个问题，chrome 没问题

**Comment by chenshuai2144** [comment]
我试试火狐先

**Comment by chenshuai2144** [comment]
无法复现。神奇。

**Comment by afc163** [comment]
在 https://github.com/ant-design/ant-design/issues/12649 这里修掉了。
