### ISSUE TITLE
本地开发，添加publicPath时候，访问静态资源时候没有加上

### ISSUE THREAD

**Issue by wangxulong** [ant-design/ant-design-pro#4301]
本地：
![image](https://user-images.githubusercontent.com/8357515/58478261-336fa180-8188-11e9-846d-d359ea3ecba7.png)

线上：
![image](https://user-images.githubusercontent.com/8357515/58478304-4f734300-8188-11e9-8ad4-f53a55c32e11.png)

**Comment by chenshuai2144** [comment]
没懂你的点？详细说明一下

**Comment by wangxulong** [comment]
@chenshuai2144 
1.配置publicPath，为 /expo
![image](https://user-images.githubusercontent.com/8357515/58605635-0972c800-82cb-11e9-8e3e-9c21668beac8.png)
2.yarn start
3.访问页面，没有静态路径前边没有 /expo
![image](https://user-images.githubusercontent.com/8357515/58605700-4f2f9080-82cb-11e9-964b-2a1ba7ec8773.png)

**Comment by superchow** [comment]
是这样的

**Comment by chenshuai2144** [comment]
@sorrycc  看起来他们用的没有问题。

**Comment by sorrycc** [comment]
本地开发的 publicPath 是写死 `/` 的。
