### ISSUE TITLE
After I have upgrading ant design pro from version 2.2.1 to 2.3.1 , application is  not starting , I have used  this approach  git pull https://github.com/ant-design/ant-design-pro

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#4302]
I have accepted latest changes and resolved conflicts manually and did npm i, and npm start , you can refer the attached screen shots , please kindly help me thank you
![logs-of-npm start script](https://user-images.githubusercontent.com/15693408/58483172-76784780-817d-11e9-88be-e75d80638f49.png)

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design-pro/issues/3789

**Comment by chenshuai2144** [comment]
You can try it again
