### ISSUE TITLE
配置带参数的路由，使用 browser history放入spring boot,访问会被当成后端接口

### ISSUE THREAD

**Issue by stephanieDL** [ant-design/ant-design-pro#4303]
我的router.config.js文件如下：
export default [
  // 分析页
  {
    path: '/openPage/filedId=:filedId',
    hideInMenu: true,
    name: 'openPage',
    component: './XX/XXX/XXXXXOpenPage',
  },
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    routes: [
      // dashboard
      { path: '/', redirect: '/welcome' },
     {
        path: '/welcome',
        component: './welcomePage/welcomePage',
      },
    ],
  },
];

使用的是browser history，放在了spring boot的static文件夹下，spring boot项目启动后带导航栏和菜单的页面一切正常，我配置的带参数的页面，独立导航栏那种会被后端认为是接口，直接404报错，求指导，非常感谢！

**Comment by superchow** [comment]
页面跳转404？

**Comment by stephanieDL** [comment]
> 页面跳转404？
就是我这个路由/openPage/filedId=:filedId下的页面读取不到，会被后端直接当成接口（我后端没有这个接口），然后就404了TAT

**Comment by kaoding** [comment]
方案1：:filedId是path的情况（filedId=:filedId 不要等号），在spring boot里要用@PathVariable
方案2：:filedId是param的情况 （一般不要在router.config.js配置），，在spring boot里要用@RequestParam 
@stephanieDL

**Comment by stephanieDL** [comment]
> 方案1：:filedId是path的情况（path/:filedId 不要等号），在spring boot里要用@PathVariable
> 方案2：:filedId是param的情况 （一般不要在router.config.js配置），，在spring boot里要用@RequestParam
> @stephanieDL

hello ,非常感谢您的解答，我这边有些不是很懂，或者我描述可能不清晰TAT，前端的路由需要由后端控制的？@PathVariable和@RequestParam 这个是放到cotroller里面直接是做restful接口获取url参数的呢？我是想通过配置单独的路由，跳过有导航栏的页面，带参数OK的说。我之前用hash history没问题，但是由于某种原因被大佬强制要用browser history,求有没有更好的方法呢？非常感谢(*^__^*)

**Comment by kaoding** [comment]
https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88

**Comment by kaoding** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BD%BF%E7%94%A8-spring-boot

**Comment by stephanieDL** [comment]
> https://pro.ant.design/docs/deploy-cn#%E4%BD%BF%E7%94%A8-spring-boot
哦哦，谢谢，我大致了解了，比心
