### ISSUE TITLE
Topmenu 縮排後不能自動恢復

### ISSUE THREAD

**Issue by hubertmok** [ant-design/ant-design-pro#4304]
當開啟chrome的開發者工具時, topmenu會自動縮排, 以適應顯示頁面大小, 但當把旁邊開發者工具關掉, 卻無法完全顯示內容, 正常應該是要回復原貌
1.開啟develop tool後
![image](https://user-images.githubusercontent.com/5517502/58529817-eda9ec00-820e-11e9-9ccb-358b687b7dc0.png)
2.關掉develop tool後
![image](https://user-images.githubusercontent.com/5517502/58529914-3e214980-820f-11e9-81ff-e8de9ff3df88.png)
3.正常的狀況下
![image](https://user-images.githubusercontent.com/5517502/58530002-9b1cff80-820f-11e9-810f-e3fb27a4acf6.png)

**Comment by chenshuai2144** [comment]
@picodoth  来看一看

**Comment by chenshuai2144** [comment]
尝试最新版本的 antd 即可解决
