### ISSUE TITLE
V4 版本检出后无法直接运行了。

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4305]
![image](https://user-images.githubusercontent.com/18098618/58535855-7762b500-8221-11e9-80ea-389d103a2948.png)

**Comment by Lind-pro** [comment]
执行安装@types/qs后也无法启动

![image](https://user-images.githubusercontent.com/18098618/58535972-cd375d00-8221-11e9-9ecf-539253cf028e.png)
@chenshuai2144

**Comment by Lind-pro** [comment]
@chenshuai2144 似乎半小时前提交的代码已经解决了这个问题。这些警告能否去除掉呢？
```
Warning: Please use `require("react-router").matchPath` instead of `require("react-router/matchPath")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Router` instead of `require("react-router/Router")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Switch` instead of `require("react-router/Switch")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Route` instead of `require("react-router/Route")`. Support for the latter will be removed in the next major release.
```

**Comment by chenshuai2144** [comment]
感觉是  umi的，怎么复现呢？

**Comment by chuDaxin** [comment]
@chenshuai2144 
"@types/qs": "^6.5.3" 引用位置引发的，可以把@types/qs放在dependencies就能复现
![image](https://user-images.githubusercontent.com/21093073/58555815-118c2280-824d-11e9-9dc6-a64ce61083b5.png)

**Comment by Lind-pro** [comment]
> 感觉是 umi的，怎么复现呢？
Warning: Please use `require("react-router").matchPath` instead of `require("react-router/matchPath")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Router` instead of `require("react-router/Router")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Switch` instead of `require("react-router/Switch")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Route` instead of `require("react-router/Route")`. Support for the latter will be removed in the next major release.

这个警告是检出代码。然后npm start 就会出现
