### ISSUE TITLE
使用Input組件value鎖死是BUG還是我使用錯誤？

### ISSUE THREAD

**Issue by SongZhuhai** [ant-design/ant-design-pro#4307]
"antd-pro-merge-less": "^1.0.0",
    "antd-theme-webpack-plugin": "^1.2.0",

import { Input } from 'antd';

`<Input placeholder='asd123' value='123'/>`

就像上面這樣，但設定了placeholder和value的值的時候，value一直保持123，change事件失效，鍵盤輸入沒有任何反應？

**Comment by afc163** [comment]
使用错误：https://github.com/facebook/react/issues/8482#issuecomment-264897287

**Comment by SongZhuhai** [comment]
多謝
