### ISSUE TITLE
v4合并到master之后，pages中的页面会完善吗？

### ISSUE THREAD

**Issue by chuDaxin** [ant-design/ant-design-pro#4308]
想咨询一下，v4合并到master之后，router.config.js中的路由还留着，这样的话。是否原本pages中的页面会完善成ts版本的？

**Comment by Lind-pro** [comment]
@chenshuai2144 大概什么时候可以有一个可用的Releases版本呢？

**Comment by chenshuai2144** [comment]
https://zhuanlan.zhihu.com/p/67498559
看这里
