### ISSUE TITLE
新版本的页面全部为空，怎么配置才能恢复之前的页面全部展示效果？

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/ant-design-pro#4309]
下载5月29日的master版本，重新npm install和npm start，发现页面已全部为空！请问需要怎么配置才能恢复之前的页面全部展示效果？
![ant](https://user-images.githubusercontent.com/3403476/58598683-ef77bc00-82af-11e9-8eba-abf81c991336.png)

**Comment by Anderson-Liu** [comment]
You can checkout V2 version instead.

```
git clone https://github.com/ant-design/ant-design-pro.git --depth=1 -b v2
```
