### ISSUE TITLE
拓扑编辑器删除一个节点后，点击该节点附近的+号，报错

### ISSUE THREAD

**Issue by CheneyLove** [ant-design/ant-design-pro#4310]
![image](https://user-images.githubusercontent.com/34939573/58603153-41c1d880-82c2-11e9-881f-01bc06063ba3.png)

![image](https://user-images.githubusercontent.com/34939573/58603173-57cf9900-82c2-11e9-82ec-640d691cdd66.png)

![image](https://user-images.githubusercontent.com/34939573/58603199-77ff5800-82c2-11e9-8863-e23edd824841.png)
之后页面处于瘫痪状态
![image](https://user-images.githubusercontent.com/34939573/58603266-a11fe880-82c2-11e9-97ce-126e839e8841.png)

**Comment by chenshuai2144** [comment]
我试了一下，是可以的，但是还是有报错。我push g6 升级一下

**Comment by CheneyLove** [comment]
嗯，点击会再次新增一个节点，伴随一个报错。但是不知道为什么我在本地尝试的时候页面会瘫痪呢。

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by Rustin-Liu** [comment]
@CheneyLove  @chenshuai2144  你好，我也遇到了这个问题，请问你们是怎么解决的呢？谢谢！

**Comment by chenshuai2144** [comment]
去g6的社区问问
