### ISSUE TITLE
选用那个区块 umijs/umi-blocks or ant-design/pro-blocks ???

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#4312]
选 ES6【umi 区块官网】https://github.com/umijs/umi-blocks/tree/master/ant-design-pro
选  TS 【antd 区块】https://github.com/ant-design/pro-blocks
是这样吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks 
已这个为准，umi 的将会很快删除
