### ISSUE TITLE
upload data 函数报错

### ISSUE THREAD

**Issue by superchow** [ant-design/ant-design-pro#4313]
![image](https://user-images.githubusercontent.com/24707978/58605510-9a956f00-82ca-11e9-8e9b-a0de1c239807.png)

**Comment by superchow** [comment]
这个暂时发现文件上传失败（oss上传），服务端返回
![image](https://user-images.githubusercontent.com/24707978/58607046-92d8c900-82d0-11e9-8d69-6b5d2fd500a8.png)
就会触发上面的报错

**Comment by superchow** [comment]
能用onError或者onSuccess 去介入处理吗？

**Comment by chenshuai2144** [comment]
完全控制可以用这个方案
https://github.com/react-component/upload#customrequest
