### ISSUE TITLE
safari 页面出现报错，经测试火狐、Edge均出现这种错误，谷歌未出现该错误

### ISSUE THREAD

**Issue by superchow** [ant-design/ant-design-pro#4314]
safari 
![image](https://user-images.githubusercontent.com/24707978/58613719-0edf0b00-82e9-11e9-8ddb-9a2716cacf70.png)

火狐、Edge 
![image](https://user-images.githubusercontent.com/24707978/58613800-3cc44f80-82e9-11e9-95ab-2cb6888af75e.png)

**Comment by yoyo837** [comment]
确定下9.async.js 加载成功没？

**Comment by superchow** [comment]
> 确定下9.async.js 加载成功没？
加载了

**Comment by superchow** [comment]
排查发现是一个正则报错了

```
/^(\s*)\[(\s*["](\d{3}(?<!000))["]\s*(?:,|\s*))+\](\s*)$/
```
请问这段正则有不兼容的语法吗？

**Comment by chenshuai2144** [comment]
SyntaxError: Invalid regular expression: invalid group specifier name

**Comment by superchow** [comment]
> SyntaxError: Invalid regular expression: invalid group specifier name
> 神奇的问题。
> 
> ![image](https://user-images.githubusercontent.com/8186664/58615436-a8102080-82ed-11e9-94a1-f23ca6887795.png)

是的 

**反向否定预查** 其他浏览器不支持
已换 **正向否定预查**
