### ISSUE TITLE
src/pages下只有三个源文件，和线上的例子不一样

### ISSUE THREAD

**Issue by YunzhiWei** [ant-design/ant-design-pro#4315]
Ant pro 的线上演示环境：https://preview.pro.ant.design/dashboard/analysis
里面有很多菜单。
而克隆到本地的源代码，在 src/pages 目录下只看到 3个源文件。
本地构建运行后，只有一个菜单。

请问，该如何操作，才能看到其他菜单呢？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro#use-bash
