### ISSUE TITLE
「官网内容错误」Charts图表 迷你区域图和迷你柱状图的示例代码中，引用的组件名写反了

### ISSUE THREAD

**Issue by lizhiyao** [ant-design/ant-design-pro#4318]
[官网问题页面地址](https://pro.ant.design/components/charts-cn#scaffold-src-components-Charts-demo-mini-area)

问题截图：
![image](https://user-images.githubusercontent.com/8143023/58618874-34264600-82f6-11e9-8316-b3e38b3a9359.png)

**Comment by chenshuai2144** [comment]
效果竟然是对的。。。

**Comment by afc163** [comment]
又没关联 issue。

**Comment by chenshuai2144** [comment]
这个没有修 改动太大！
官网也不维护了
