### ISSUE TITLE
如何设置权限路由？

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design-pro#4319]
例如左侧菜单只有dashboard及其子菜单，但是在浏览器url地址栏直接输入localhost:8000/form/basic-form还是可以进入这个页面，正常情况下应该是进入404。
请问这个如何设置，跪求各位大佬 :)

**Comment by Sayid1** [comment]
我看了其他issues，没看出个所以然来，是我太憨了吗

**Comment by superchow** [comment]
可以参考下这个 https://www.yuque.com/liuyin-zzwa0/ada6ao/va6p77

**Comment by zhaocz2015** [comment]
感觉这里路由权限设计的挺复杂，其实就是登陆后返回什么路由，就显示哪一些路由，config.ts配置的路由，在权限校验时过滤掉存在的，不存在的就notMatch 跳转403 或者 login登录页

**Comment by ruomanwei** [comment]
配置authority，或者直接从后端拿路由
