### ISSUE TITLE
fetch:blocks的时候，分析页图表显示出不来，单独umi block add可以显示出来

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#4321]

**Comment by kaoding** [comment]
是依赖顺序冲突吗？分析页的依赖先安装，后面也有和分析页同样的依赖，但版本低覆盖了分析页所要求的依赖。

**Comment by chenshuai2144** [comment]
是什么的依赖

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/58742164-d2c8b900-8454-11e9-8e5e-690812c14047.png)

**Comment by kaoding** [comment]
上图是因使用区块后，_mock.js 数据各自有一份，又因mock数据是全局，而且名称相同，导致mock数据互相覆盖。如：analysis 和 workplace 中相同的数据 radarData，center团队数据也有相同。建议是mock数据的命名加上所属的区块名称。 @chenshuai2144

**Comment by chenshuai2144** [comment]
这样需要一个新的部署方式，你有兴趣探索一把吗？

**Comment by wangweikang** [comment]
遇见了同样的问题

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/pro-blocks/commit/f7f2f475b6a3d0e3423f513828c64aac00387568
