### ISSUE TITLE
JS 比 TS 更爽

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#4324]
像我这样从后端转过来的，用JS没有类型，感觉很爽。
现在前端用TS，搞的和后端一样，不是很爽。

**Comment by afc163** [comment]
放纵是魔鬼 😈🐶

**Comment by kaoding** [comment]
antd使用TS可以理解，主要是提供基础组件的，严格是好事
antd pro本来是脚手架的，让不太专业的，上手就可以很简单的使用（block更多一种设计与学习资源，也是可以帮助很快上手做产品或者项目的），现在用TS来写的，就是再想用JS来学，碰到了TS的事，总是要学习一下的，有没有考虑过为什么JS一直不和TS一样吗？可能就在这里了。
