### ISSUE TITLE
新版的request.ts有问题。

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4326]
请求错误不会进入到异常处理程序中，例如登录操作时，状态是400，但并没有进入到异常处理中
![image](https://user-images.githubusercontent.com/18098618/58630732-e66c0680-8312-11e9-8e93-2d13518d14a9.png)

**Comment by chenshuai2144** [comment]
看起来是别的报错堵塞了它。
排查一下报错的哪两个变量
