### ISSUE TITLE
更新后无法运行了，安装依赖正常，npm start正常

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design-pro#4328]
如题，安装运行一切正常，但打开浏览器一片空白，控制台显示错误如下：
![Annotation 2019-05-31 103200](https://user-images.githubusercontent.com/5361465/58677693-997a4580-838f-11e9-8597-994966e5abe6.jpg)

**Comment by chenshuai2144** [comment]
看起来是 context 出现了问题，试着删除一下 headerSeach

**Comment by hankaibo** [comment]
headreSeach没有找到，今天更新了之后安装依赖，成功打开了。
