### ISSUE TITLE
NumberInfo数据文本展示问题

### ISSUE THREAD

**Issue by lijingcsu** [ant-design/ant-design-pro#433]
在单独使用ant design pro组件（引入了对应样式）时，使用数据文本，但是total和subTotal展示合一起，没有分开，
![2017-12-14 11-48-35](https://user-images.githubusercontent.com/8297694/33974693-bf8eb5d6-e0c4-11e7-9cce-7061df0286b6.png)

**Comment by lijingcsu** [comment]
![2017-12-14 11-49-13](https://user-images.githubusercontent.com/8297694/33974712-d3b248e8-e0c4-11e7-83d9-47e3e032a70f.png)

**Comment by xiaosongxiaosong** [comment]
NumberInfo 样式没有渲染到DOM节点上
```js
<Card>
  <NumberInfo subTitle="课堂总数" total={this.state.total} />
</Card>
```
渲染结果：
```html
<div>
  <div class="">
    <div>课堂总数</div>
    <div>
      <span>2</span>
    </div>
  </div>
</div>
```
![image](https://user-images.githubusercontent.com/2703455/33979024-72e38a22-e0dd-11e7-8358-f53a8c1212e0.png)

![image](https://user-images.githubusercontent.com/2703455/33979011-64053af0-e0dd-11e7-91cc-a2a271226f2a.png)

![image](https://user-images.githubusercontent.com/2703455/33978993-4b2bcac6-e0dd-11e7-9684-11a6824ec1f1.png)

**Comment by lijingcsu** [comment]
需要怎么解决呢？请指教

**Comment by xiaosongxiaosong** [comment]
我也是使用的时候发现问题，看到你这个issue，把我这边的现象写进来，顺便订阅一下这个issue😁

**Comment by nikogu** [comment]
fixed, try v0.3.1
