### ISSUE TITLE
yarn create umi my-app 这种方式出来少了script 等

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#4330]
在package.json中有fetch:blocks、文档中也有说明

**Comment by chenshuai2144** [comment]
重新来一把，我加上了

**Comment by weicong** [comment]
通过 create umi 出来的**干净**项目真太棒了，省得手工删除一些用不到的文件。

**Comment by kaoding** [comment]
yarn create umi my-app方式出来的还是没有script这个目录和下面的脚本，package.json中有也没有办法执行哟。

**Comment by kaoding** [comment]
yarn create umi my-app这各方式出来的是比较干净的，但依赖是2份，和直接git clone下来的少了docker、lambda、script（这个好像不能少），还有一些环境、版权相关的文件、package.json和README.md就是直接从create-umi复制过来的。

**Comment by chenshuai2144** [comment]
专门删除的
