### ISSUE TITLE
新建项目安装依赖moment version报错

### ISSUE THREAD

**Issue by wangzhipeng404** [ant-design/ant-design-pro#4333]
No matching version found for moment@^2.24.2

**Comment by kouchao** [comment]
我也遇到了   tslint版本也不对 改成存在的版本也安装不上

**Comment by MingRock** [comment]
package.json中
moment改2.24.0
tslint改5.17.0

再npm install

**Comment by yoyo837** [comment]
#4331
是淘宝镜像没同步吗还是啥？
![image](https://user-images.githubusercontent.com/6134547/58691121-b0379100-83bd-11e9-89f2-e671bcee463f.png)

**Comment by MingRock** [comment]
create umi 建出来的package.json和github的不一致

**Comment by chenshuai2144** [comment]
fixed
