### ISSUE TITLE
将窗口变小，再拉大的时候，界面显示不正常

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4334]
将窗口变小，再拉大的时候，界面显示不正常，如下图

![image](https://user-images.githubusercontent.com/24469601/58688319-b413e500-83b6-11e9-8b88-bda8afec55f8.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4304
