### ISSUE TITLE
ReferenceError: DataSet is not defined

### ISSUE THREAD

**Issue by h499360594** [ant-design/ant-design-pro#4335]
ReferenceError: DataSet is not defined
@antv/data-set
external "DataSet":1
> 1 | module.exports = DataSet;
View compiled
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/components/Charts/Pie/index.js
http://localhost:8000/layouts__BasicLayout.async.js:1394:73
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/components/Charts/index.js
src/components/Charts/index.js:1
> 1 | import numeral from 'numeral';
  2 | import './g2';
  3 | import ChartCard from './ChartCard';
  4 | import Bar from './Bar';
View compiled
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/pages/Dashboard/IntroduceRow.js
http://localhost:8000/1.async.js:26:77
__webpack_require__
webpack/bootstrap:771
  768 | };
  769 | 
  770 | // Execute the module function
> 771 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  772 | 
  773 | // Flag the module as loaded
  774 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

为什么会 报这个错，没有改任何东西，下的2.2.0版本的zip文件，解压后，用vscode 打开文件夹，执行npm install 在执行 npm start 启动后就弹出http://localhost:8000/dashboard/analysis页面，提示dataset is not defined。问题是我啥也没改，是啥原因呢？求教。

**Comment by h499360594** [comment]
@chenshuai2144 大佬，请求支援。

**Comment by chenshuai2144** [comment]
external 删除掉

**Comment by h499360594** [comment]
嗯 我自己试了删了就好了，没有影响是么？

**Comment by h499360594** [comment]
> external 删除掉

嗯 我自己试了删了就好了，没有影响是么？ 还有 是刚提了一版新的么，好像跟我上去下的master不一样了

**Comment by chenshuai2144** [comment]
最好用 create umi 进行新建。

**Comment by yoyo837** [comment]
@h499360594 master还在继续完善，watch 一下 repo

**Comment by gaoyafengyagao** [comment]
我也出现了这个问题，之前都是好的，突然就报这个错误

**Comment by h499360594** [comment]
好像是版本的问题，我换了个版本就好了。好久之前的事了，忘记了。



---Original---
