### ISSUE TITLE
按照docker下的Nginx配置线上服务器，反向代理失败，如图配置

### ISSUE THREAD

**Issue by dangyanglim** [ant-design/ant-design-pro#4340]
server {
    listen 1043;
    # gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    root /root/wwwroot/logistics-react;

    location / {
        try_files $uri $uri/ /index.html;
    }
    location /api {
        proxy_pass https://preview.pro.ant.design;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}

**Comment by dangyanglim** [comment]
http://fenghuangyu.cn:1043  报错404

**Comment by dangyanglim** [comment]
http://fenghuangyu.cn:1043/api/currentUser 报not found

**Comment by chenshuai2144** [comment]
`http://fenghuangyu.cn:1043/api/api/currentUser `
应该是这样的

**Comment by afc163** [comment]
> http://fenghuangyu.cn:1043/api/api/currentUser 

看着好奇怪。

**Comment by dangyanglim** [comment]
https://preview.pro.ant.design 估计是它这个不支持调用，用我自己做的后台可以

**Comment by gensir** [comment]
不妨这样试试
```
root /root/wwwroot/logistics-react;

location / {
    try_files $uri $uri/ /index.html;
}
location /api {
    proxy_pass https://preview.pro.ant.design/api;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Host              $http_host;
    proxy_set_header   X-Real-IP         $remote_addr;
}
```

**Comment by chenshuai2144** [comment]
因为我用的 function ，是有前缀的
