### ISSUE TITLE
在document.ejs的header有<script>window.routerBase='/'</script>，导致引入的外部js只在根路由生效

### ISSUE THREAD

**Issue by dutyk** [ant-design/ant-design-pro#4342]
在document.ejs的header有<script>  window.routerBase = "/";</script>，导致引入的外部js只在根路由生效，如http://localhost:8000/test，外部js生效，同一个页面改一个路由http://localhost:8000/test/test，外部js不生效。这个问题怎么解决？

**Comment by xiaohuoni** [comment]
外部js不是通过http的url引入的嘛？和base应该没有关系吧？

**Comment by chenshuai2144** [comment]
来个重现地址
