### ISSUE TITLE
v4代码我这为什么不会跳到登陆页面。例如http://localhost:8000/不会自动跳到http://localhost:8000/user/login

### ISSUE THREAD

**Issue by 952425340** [ant-design/ant-design-pro#4345]

**Comment by gensir** [comment]
要么加权限  要么配置路由重定向

**Comment by 952425340** [comment]
> 要么加权限 要么配置路由重定向
里面不是已经有加了么，为什么好像没效果啊，是不是要改什么

**Comment by u0x01** [comment]
在路由配置里面加  `authority: ['user']`:
```json
    {
      path: '/',
      component: '../layouts/BasicLayout',
      Routes: ['src/pages/Authorized'],
      authority: ['admin', 'user'],
      routes: [
        {
          path: '/',
          name: 'welcome',
          icon: 'smile',
          component: './Welcome',
          authority: ['user'],
        },
      ],
    },
```

**Comment by xiaohuoni** [comment]
在demo里面默认不跳转了

**Comment by evanyangg** [comment]
![image](https://user-images.githubusercontent.com/22952321/58787452-6ac4cf00-861c-11e9-88a2-3f109dcacfb1.png)
我安装了login 的block 但是发现页面页面变成这样，如何让login页面显示为顶层呢？

**Comment by 952425340** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/22952321/58787452-6ac4cf00-861c-11e9-88a2-3f109dcacfb1.png)
> 我安装了login 的block 但是发现页面页面变成这样，如何让login页面显示为顶层呢？
> 第一次用 pro, 应该在哪可以配置的吧？

![图片](https://user-images.githubusercontent.com/22728007/58787842-3c93bf00-861d-11e9-8b01-1eaad41a2bbd.png)
你要注意这个使用的外层布局不一样，你要自己该一下

**Comment by evanyangg** [comment]
@952425340  👌，非常感谢！！！
