### ISSUE TITLE
Nginx部署问题

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design-pro#4347]
![image](https://user-images.githubusercontent.com/3994941/58756975-ef3c2280-8534-11e9-9dc5-c74bceb7e3e0.png)
删掉红框里的字就好了  很无语 我也看不懂  反正删了就好了

**Comment by miaozilong** [comment]
要多加一条try_files 否则切换路由有问题！

**Comment by chenshuai2144** [comment]
@miaozilong  欢迎 pr

**Comment by unrealsmart** [comment]
统计一下配置场景：

**配置到根目录，链接通过`www.xxx.com`访问**

在`history`为`brower`时，Pro 跳转路由后，页面一旦刷新就会出错。
例如：404等，这是服务器配置问题。
解决方案：暂无（有空测试后修改）


**配置到子目录，链接类似于通过`www.xxx.com/admin`访问**

`config/config.js`文件末尾中配置：
```
{
    ...
    base: '/admin',
    publicPath: '/admin'
}
```
`umi build` 打包完成后将 `dist` copy到网站根目录，重命名目录 `dist` 为 `admin`

`nginx` 配置：
```
server {
    listen       80;
    server_name  xxx.com www.xxx.com;
    root    "/public"; # 修改为你的网站根目录

    location / {
        index    index.html index.htm index.php l.php;
        autoindex    off;
    }

    # 防止静态文件被重定向
    location ~ \.(gif|jpg|png|js|css|json)$ {
        rewrite ^/admin(.*)$ /admin/$1 break;
    }

    # 所有路由为`/admin`都重定向到`/admin/index.html`
    location /admin {
        rewrite ^/admin(.*)$ /admin/index.html break;
    }

    # 访问文件或目录不存在时，路由包含`/admin`重定向到`/admin/index.html`；
    # 其他路由全部重定向到`index.php`
    if (!-e $request_filename) {
        rewrite ^/admin(.*)$ /admin/index.html break;
        rewrite ^/(.*)$ /index.php/$1;
    }
}
```

**配置到子域名**

（这个应该跟第一个差不多的，修改一下 `server_name` 就可以了）

**还有其他的（奇葩）的配置方法吗？**
