### ISSUE TITLE
pro4.0 动态获取路由

### ISSUE THREAD

**Issue by zywkuo** [ant-design/ant-design-pro#4348]
你好，最新的4.0版本，如何从接口获取路由信息，动态导入？

**Comment by xiaohuoni** [comment]
https://pro.ant.design/docs/router-and-nav-cn#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95
https://pro.ant.design/docs/authority-management-cn#%E5%A6%82%E4%BD%95%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A8%E6%80%81%E8%BF%BD%E5%8A%A0%E9%A1%B5%E9%9D%A2%E6%9D%83%E9%99%90
