### ISSUE TITLE
标准列表数据重复的问题。不知道是故意设计的还是bug呢

### ISSUE THREAD

**Issue by bingfengblog** [ant-design/ant-design-pro#435]
![image](https://user-images.githubusercontent.com/20056436/33979642-45b6b9fe-e0e0-11e7-93c8-47b7c3dd3c22.png)

点到别的选项卡，再点击标准列表，发现数据多了
![image](https://user-images.githubusercontent.com/20056436/33979693-795dd0da-e0e0-11e7-826d-3f723f882b3e.png)

**Comment by chenshuai2144** [comment]
这些数据都是mock生成的.
都是些假数据.

**Comment by bingfengblog** [comment]
这个我知道，只是现在用自己的api获取的也会这样子

**Comment by chenshuai2144** [comment]
我排查一下

**Comment by lazy1523** [comment]
这个问题是由于 请求之后，旧的数据状态没有得到刷新，请求到的新数据，会重新加载进state中，导致这个问题，解决的方法可以在请求之前，将data设为空  data:[]

**Comment by chenshuai2144** [comment]
@lazy1523  谢谢...

**Comment by chenshuai2144** [comment]
@lazy1523  谢谢...
