### ISSUE TITLE
wrong character

### ISSUE THREAD

**Issue by uv-w** [ant-design/ant-design-pro#4350]
![image](https://user-images.githubusercontent.com/17735161/58777862-e1ed6980-8602-11e9-85e1-190efa88416d.png)

**Comment by afc163** [comment]
来个 PR

**Comment by uv-w** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/294

**Comment by uv-w** [comment]
> 来个 PR

https://github.com/ant-design/ant-design-pro-site/pull/294
