### ISSUE TITLE
V4检出后报错

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4352]
![image](https://user-images.githubusercontent.com/18098618/58783208-f3d70880-8612-11e9-8a43-b5808bf870d0.png)
![image](https://user-images.githubusercontent.com/18098618/58783234-03565180-8613-11e9-9ef9-2d4b878d9702.png)
@chenshuai2144 

复现步骤：
检出项目，然后npm install,再npm start

**Comment by chenshuai2144** [comment]
这个报错的是浏览器插件吐出来的。
检查一下你的插件
