### ISSUE TITLE
fetch:blocks: `node ./scripts/fetch-blocks.js`

### ISSUE THREAD

**Issue by aibinMr** [ant-design/ant-design-pro#4353]
Error: Cannot find module 'F:\WorkSpace\react\learn\ant_design_pro_v4_all\scripts\fetch-blocks.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 fetch:blocks: `node ./scripts/fetch-blocks.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.0.0 fetch:blocks script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aibin\AppData\Roaming\npm-cache\_logs\2019-06-03T07_48_58_585Z-debug.log

**Comment by blackboy1987** [comment]
用这个命令根本就下载不下来

**Comment by chenshuai2144** [comment]
再试一次，我已经 merge 了这个 pr

**Comment by SilentFlute** [comment]
@chenshuai2144 你好，我装了`ant-design-pro`，选择的`js`，后来看了文档使用了`fetch:blocks`命令装区块，然后报错说在`/scripts/fetch-blocks.js`中`找不到`/config/config.ts`，接着我手动修改`/scripts/fetch-blocks.js`中的相应代码将`'../config/config.ts'`改为了`'../config/config.js'`就能成功安装区块了，接着安装完成的时候又报了个类似的错误：
```
(node:28656) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/dkd/Downloads/demos&usages/my-ant-design-pro/src/layouts/BasicLayout.tsx'
```
但是由于最后显示安装完成了，同时我也能启动起来看到页面，页面显示正常，因此就没有再去手动修改相关代码

**Comment by SilentFlute** [comment]
补充一下，后一次报错说的是在`/scripts/insertCode.js`中找不到`/src/layouts/BasicLayout.tsx`

**Comment by SilentFlute** [comment]
以及突然发现安装的区块都是`.tsx`文件……

**Comment by chenshuai2144** [comment]
最好用 ts 的。js 的支持的不好

**Comment by SilentFlute** [comment]
@chenshuai2144 目前来看是ant-design-pro不支持js，只能用ts了是吧？或者说安装的区块是不支持js的，如果自己写自然是可以用js，但是就是对js的支持不好是吗？
