### ISSUE TITLE
npx umi block add  安装后发现不是驼峰目录

### ISSUE THREAD

**Issue by evanyangg** [ant-design/ant-design-pro#4357]
通过页面上的链接 npx umi block add UserLogin  --path=/user/login
安装后 路径为 page/user/login  并不是之前的驼峰命名方式

**Comment by chenshuai2144** [comment]
`-path=/user/login`
通过这个可以自定义

**Comment by evanyangg** [comment]
现在在路径中支持驼峰写法了，谢谢
