### ISSUE TITLE
新版本的菜单渲染

### ISSUE THREAD

**Issue by qy394163797** [ant-design/ant-design-pro#4358]
文档中的
（从服务器请求菜单#
只需在 models/menu 中发起 http 请求，menuData 是一个 json 数组。只需服务器返回类似格式的 json 即可。）
（菜单#
菜单根据 router.config.js 生成，具体逻辑在 src/models/menu.js 中的 formatter 方法实现。）
为什么在新版本中找不到menu.js文件

**Comment by zywkuo** [comment]
我也在寻找动态加载路由的方式，我尝试在models中新建menu.js，但是失败了，在layout组件中获取不到menuData数组，如果你实现了，希望分享一下，谢谢。

**Comment by chenshuai2144** [comment]
可以看一下这里
https://github.com/ant-design/ant-design-pro-layout#prolayout

layout 支持手工传入 menuData. 想怎么玩怎么玩

**Comment by zywkuo** [comment]
手动传入，通过哪个方法传入呢？

**Comment by 952425340** [comment]
> 
> 
> 可以看一下这里
> https://github.com/ant-design/ant-design-pro-layout#prolayout
> 
> layout 支持手工传入 menuData. 想怎么玩怎么玩

有没有示例给我们看一下，你说的是menuRender这个属性还是menuItemRender属性

**Comment by zywkuo** [comment]
目前我以及大体实现从后台获取menuData进行展示。
第一步：
在models中新建menu文件
``` bash
import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
import { Reducer } from 'redux';
import { Effect } from './connect';

export interface MenuModelState {
  menuData: any[];
}

export interface MenuModelType {
  namespace: 'menu';
  state: MenuModelState;
  effects: {
    getMenuData: Effect;
  };
  reducers: {
    save: Reducer<MenuModelState>;
  };
}

const MenuModel: MenuModelType = {
  namespace: 'menu',
  state: {
    menuData: [],
  },
  effects: {
    *getMenuData({ payload, callback }, { call, put }) {
      const response = yield call(getMenuData);
      yield put({
        type: 'save',
        payload: response,
      });
      if (callback) callback(response);
    },
  },

  reducers: {
    save(state, action) {
      return {
        ...state,
        menuData: action.payload || [],
      };
    },
  },
};
export default MenuModel;
```
第二步：
在layout页面中加载
``` bash
dispatch({
  type: 'menu/getMenuData',
});
```
最后一步：**不要忘记**
``` bash
export default connect(({ global, settings, menu }: ConnectState) => ({
  collapsed: global.collapsed,
  settings,
  menuData: menu.menuData, // 不要忘记在这里注入
}))(BasicLayout);
```

目前使用后设置语言就不起作用了，还没找到原因。

**Comment by 952425340** [comment]
> 
> 
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件
> 
> ```shell
> import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> import { Reducer } from 'redux';
> import { Effect } from './connect';
> 
> export interface MenuModelState {
>   menuData: any[];
> }
> 
> export interface MenuModelType {
>   namespace: 'menu';
>   state: MenuModelState;
>   effects: {
>     getMenuData: Effect;
>   };
>   reducers: {
>     save: Reducer<MenuModelState>;
>   };
> }
> 
> const MenuModel: MenuModelType = {
>   namespace: 'menu',
>   state: {
>     menuData: [],
>   },
>   effects: {
>     *getMenuData({ payload, callback }, { call, put }) {
>       const response = yield call(getMenuData);
>       yield put({
>         type: 'save',
>         payload: response,
>       });
>       if (callback) callback(response);
>     },
>   },
> 
>   reducers: {
>     save(state, action) {
>       return {
>         ...state,
>         menuData: action.payload || [],
>       };
>     },
>   },
> };
> export default MenuModel;
> ```
> 
> 第二步：
> 在layout页面中加载
> 
> ```shell
> dispatch({
>   type: 'menu/getMenuData',
> });
> ```
> 
> 最后一步：**不要忘记**
> 
> ```shell
> export default connect(({ global, settings, menu }: ConnectState) => ({
>   collapsed: global.collapsed,
>   settings,
>   menuData: menu.menuData, // 不要忘记在这里注入
> }))(BasicLayout);
> ```
> 
> 目前使用后设置语言就不起作用了，还没找到原因。

你那第二步里面的代码可以截图下给我看么，

**Comment by zywkuo** [comment]
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件
> 
> ```shell
> import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> import { Reducer } from 'redux';
> import { Effect } from './connect';
> 
> export interface MenuModelState {
>   menuData: any[];
> }
> 
> export interface MenuModelType {
>   namespace: 'menu';
>   state: MenuModelState;
>   effects: {
>     getMenuData: Effect;
>   };
>   reducers: {
>     save: Reducer<MenuModelState>;
>   };
> }
> 
> const MenuModel: MenuModelType = {
>   namespace: 'menu',
>   state: {
>     menuData: [],
>   },
>   effects: {
>     *getMenuData({ payload, callback }, { call, put }) {
>       const response = yield call(getMenuData);
>       yield put({
>         type: 'save',
>         payload: response,
>       });
>       if (callback) callback(response);
>     },
>   },
> 
>   reducers: {
>     save(state, action) {
>       return {
>         ...state,
>         menuData: action.payload || [],
>       };
>     },
>   },
> };
> export default MenuModel;
> ```
> 
> 第二步：
> 在layout页面中加载
> 
> ```shell
> dispatch({
>   type: 'menu/getMenuData',
> });
> ```
> 
> 最后一步：**不要忘记**
> 
> ```shell
> export default connect(({ global, settings, menu }: ConnectState) => ({
>   collapsed: global.collapsed,
>   settings,
>   menuData: menu.menuData, // 不要忘记在这里注入
> }))(BasicLayout);
> ```
> 
> 目前使用后设置语言就不起作用了，还没找到原因。

[
<img width="702" alt="WX20190604-133734@2x" src="https://user-images.githubusercontent.com/21994183/58853789-f34f7800-86cd-11e9-9f40-7fc95f8b4ddf.png">
](url)

**Comment by zywkuo** [comment]
> > 目前我基本已经实现从后台获取menuData进行展示。
> > 第一步：
> > 在models中新建menu文件
> > ```shell
> > import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> > import { Reducer } from 'redux';
> > import { Effect } from './connect';
> > 
> > export interface MenuModelState {
> >   menuData: any[];
> > }
> > 
> > export interface MenuModelType {
> >   namespace: 'menu';
> >   state: MenuModelState;
> >   effects: {
> >     getMenuData: Effect;
> >   };
> >   reducers: {
> >     save: Reducer<MenuModelState>;
> >   };
> > }
> > 
> > const MenuModel: MenuModelType = {
> >   namespace: 'menu',
> >   state: {
> >     menuData: [],
> >   },
> >   effects: {
> >     *getMenuData({ payload, callback }, { call, put }) {
> >       const response = yield call(getMenuData);
> >       yield put({
> >         type: 'save',
> >         payload: response,
> >       });
> >       if (callback) callback(response);
> >     },
> >   },
> > 
> >   reducers: {
> >     save(state, action) {
> >       return {
> >         ...state,
> >         menuData: action.payload || [],
> >       };
> >     },
> >   },
> > };
> > export default MenuModel;
> > ```
> > 
> > 
> > 第二步：
> > 在layout页面中加载
> > ```shell
> > dispatch({
> >   type: 'menu/getMenuData',
> > });
> > ```
> > 
> > 
> > 最后一步：**不要忘记**
> > ```shell
> > export default connect(({ global, settings, menu }: ConnectState) => ({
> >   collapsed: global.collapsed,
> >   settings,
> >   menuData: menu.menuData, // 不要忘记在这里注入
> > }))(BasicLayout);
> > ```
> > 
> > 
> > 目前使用后设置语言就不起作用了，还没找到原因。
> 
> 你那第二步里面的代码可以截图下给我看么，
<img width="702" alt="WX20190604-133734@2x" src="https://user-images.githubusercontent.com/21994183/58853917-60630d80-86ce-11e9-9b37-21c6021474c8.png">

**Comment by saltdg** [comment]
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件
> 
...

按照这个实现了动态路由， 

修改 menuItemRender={}
为
menuItemRender={(menuItemProps, defaultDom) => {
        return <Link to={menuItemProps.path}>
          {settings.menu.locale ? formatMessage({
            id: `menu${menuItemProps.path.replace(RegExp('/', 'g'), '.')}`,
          }) : defaultDom}
        </Link>;
      }}

可以实现子菜单的本地化语言，但主菜单却不行。
![image](https://user-images.githubusercontent.com/11764227/58866760-d6c23880-86eb-11e9-8cbb-845bdb465b30.png)

暂时不知道怎么处理。

**Comment by saltdg** [comment]
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件

> 目前使用后设置语言就不起作用了，还没找到原因。


======
修改函数
`
effects: {
    *getMenuData({ payload, callback }, { call, put }) {
    },
  },
`
为：
`
interface MenuItem {
  name: string;
  path: string;
  icon?: string;
  children?: MenuItem[];
  locale?: string;
}
`

`*getMenuData({ payload, callback }, { call, put }) {
      const response = yield call(getMenuData);
     const localeFunc = (menuList: MenuItem[]) => {
        menuList.map((item: MenuItem): MenuItem => {
          item.locale = `menu${item.path.replace(RegExp('/', 'g'), '.')}`;
          if (item.children) {
            item.children = localeFunc(item.children);
          }
          return item;
        });
        return menuList;
      };
      yield put({
        type: 'save',
        payload:  localeFunc(response),
      });
      if (callback) callback(response);
    },`

**Comment by saltdg** [comment]
to 楼上：
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件

> 目前使用后设置语言就不起作用了，还没找到原因。

.....
<br>
<br>

>后台返回字段中添加一个 **locale**字段，为对应的语言key即可


>或者修改函数：
```
effects: {
    *getMenuData({ payload, callback }, { call, put }) {
    },
  },
```
>为：
```
interface MenuItem {
  name: string;
  path: string;
  icon?: string;
  children?: MenuItem[];
  locale?: string;
}
```

```
*getMenuData({ payload, callback }, { call, put }) {
      const response = yield call(getMenuData);
     const localeFunc = (menuList: MenuItem[]) => {
        menuList.map((item: MenuItem): MenuItem => {
          item.locale = `menu${item.path.replace(RegExp('/', 'g'), '.')}`;
          if (item.children) {
            item.children = localeFunc(item.children);
          }
          return item;
        });
        return menuList;
      };
      yield put({
        type: 'save',
        payload:  localeFunc(response),
      });
      if (callback) callback(response);
    },
```

**Comment by micfan** [comment]
坐等开发嵌套菜单API，自己玩翻了还要等 official release

**Comment by micfan** [comment]
找到了这个 example，修改下，就能调出二级菜单：

https://github.com/ant-design/ant-design-pro-layout/blob/8a65a7f53744efbe0ac5244805d99ca737c572d7/example/config/config.ts#L96

**Comment by Hansuku** [comment]
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件
> 
> ```shell
> import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> import { Reducer } from 'redux';
> import { Effect } from './connect';
> 
> export interface MenuModelState {
>   menuData: any[];
> }
> 
> export interface MenuModelType {
>   namespace: 'menu';
>   state: MenuModelState;
>   effects: {
>     getMenuData: Effect;
>   };
>   reducers: {
>     save: Reducer<MenuModelState>;
>   };
> }
> 
> const MenuModel: MenuModelType = {
>   namespace: 'menu',
>   state: {
>     menuData: [],
>   },
>   effects: {
>     *getMenuData({ payload, callback }, { call, put }) {
>       const response = yield call(getMenuData);
>       yield put({
>         type: 'save',
>         payload: response,
>       });
>       if (callback) callback(response);
>     },
>   },
> 
>   reducers: {
>     save(state, action) {
>       return {
>         ...state,
>         menuData: action.payload || [],
>       };
>     },
>   },
> };
> export default MenuModel;
> ```
> 
> 第二步：
> 在layout页面中加载
> 
> ```shell
> dispatch({
>   type: 'menu/getMenuData',
> });
> ```
> 
> 最后一步：**不要忘记**
> 
> ```shell
> export default connect(({ global, settings, menu }: ConnectState) => ({
>   collapsed: global.collapsed,
>   settings,
>   menuData: menu.menuData, // 不要忘记在这里注入
> }))(BasicLayout);
> ```
> 
> 目前使用后设置语言就不起作用了，还没找到原因。

老哥 可以看下你ProLayout 里绑定 menuDataRender 怎么绑定的嘛 我按照你的思路把menuData丢进 menuDataRender 会报错 `menuDataRender is not a function` 似乎他就是需要传入一个方法 而 menuData 是已经处理好的数据
![image](https://user-images.githubusercontent.com/28286561/60378516-20d1dc00-9a56-11e9-849f-33cf1408e5b3.png)

**Comment by saltdg** [comment]
menuDataRender对应的渲染函数不变，还是原来BasicLayout的渲染函数menuDataRender.
你这里menuData只是数据，不是函数哇。menuData是BasicLayout自带的props

**Comment by Hansuku** [comment]
> menuDataRender对应的渲染函数不变，还是原来BasicLayout的渲染函数menuDataRender.
> 你这里menuData只是数据，不是函数哇。menuData是BasicLayout自带的props

那么我怎么把自带的 props 给截胡掉哇 menuDataRender里的参数我试着自己传也不行

**Comment by saltdg** [comment]
在BasicLayout 里面
const { dispatch } = props;
 useState(()=> {
   if (dispatch) {
    dipatch({
      type: 'menu/getMenuData',
   });
   }
});

**Comment by Hansuku** [comment]
> 在BasicLayout 里面
> const { dispatch } = props;
> useState(()=> {
> if (dispatch) {
> dispatch({
> type: 'menu/getMenuData',
> });
> }
> });

这个操作我做过了 并且数据已经拿到了 现在我不懂怎么把数据绑定上去😣
![image](https://user-images.githubusercontent.com/28286561/60378862-b58b0880-9a5b-11e9-8f10-77ad9d84d3eb.png)

**Comment by 2233322** [comment]
@Hansuku  标注的地方不需要，如果props中存在menuData就会优先使用这个数据渲染
![111](https://user-images.githubusercontent.com/23025140/60378918-b2444c80-9a5c-11e9-85e2-687d8a5e92f2.jpg)

**Comment by Hansuku** [comment]
> @Hansuku 标注的地方不需要，如果props中存在menuData就会优先使用这个数据渲染
> ![111](https://user-images.githubusercontent.com/23025140/60378918-b2444c80-9a5c-11e9-85e2-687d8a5e92f2.jpg)

emmmm 我按照这个来错是不报了 但是菜单啥都不显示了 我再挣扎一下 不行我用 menuRender 直接写一个了

**Comment by 2233322** [comment]
@Hansuku 看看你menuData输出的数据

**Comment by Hansuku** [comment]
@2233322 哈哈哈 你提醒我了 就是数据问题 我的 mock 数据出来不是 json 是字符串

**Comment by pkaq** [comment]
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件
> 
> ```shell
> import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> import { Reducer } from 'redux';
> import { Effect } from './connect';
> 
> export interface MenuModelState {
>   menuData: any[];
> }
> 
> export interface MenuModelType {
>   namespace: 'menu';
>   state: MenuModelState;
>   effects: {
>     getMenuData: Effect;
>   };
>   reducers: {
>     save: Reducer<MenuModelState>;
>   };
> }
> 
> const MenuModel: MenuModelType = {
>   namespace: 'menu',
>   state: {
>     menuData: [],
>   },
>   effects: {
>     *getMenuData({ payload, callback }, { call, put }) {
>       const response = yield call(getMenuData);
>       yield put({
>         type: 'save',
>         payload: response,
>       });
>       if (callback) callback(response);
>     },
>   },
> 
>   reducers: {
>     save(state, action) {
>       return {
>         ...state,
>         menuData: action.payload || [],
>       };
>     },
>   },
> };
> export default MenuModel;
> ```
> 
> 第二步：
> 在layout页面中加载
> 
> ```shell
> dispatch({
>   type: 'menu/getMenuData',
> });
> ```
> 
> 最后一步：**不要忘记**
> 
> ```shell
> export default connect(({ global, settings, menu }: ConnectState) => ({
>   collapsed: global.collapsed,
>   settings,
>   menuData: menu.menuData, // 不要忘记在这里注入
> }))(BasicLayout);
> ```
> 
> 目前使用后设置语言就不起作用了，还没找到原因。

好像直接connect menudata之后还得 menuDataRender={ () => menuData } 才可以 不然还是默认走路由生成

**Comment by liuyanming9551** [comment]
方案不成立

**Comment by VeChar** [comment]
> menuDataRender={ () => menuData }

对的，需要这一步才可以

**Comment by shuai93** [comment]
事实证明 issue 应该是倒序看  调试半天发现 最后一步才是最关键的

**Comment by guiqide** [comment]
> 目前我基本已经实现从后台获取menuData进行展示。
> 第一步：
> 在models中新建menu文件
> 
> ```shell
> import { getMenuData } from '@/services/menu'; // 通过后台返回特定的数组json或者mock模拟数据
> import { Reducer } from 'redux';
> import { Effect } from './connect';
> 
> export interface MenuModelState {
>   menuData: any[];
> }
> 
> export interface MenuModelType {
>   namespace: 'menu';
>   state: MenuModelState;
>   effects: {
>     getMenuData: Effect;
>   };
>   reducers: {
>     save: Reducer<MenuModelState>;
>   };
> }
> 
> const MenuModel: MenuModelType = {
>   namespace: 'menu',
>   state: {
>     menuData: [],
>   },
>   effects: {
>     *getMenuData({ payload, callback }, { call, put }) {
>       const response = yield call(getMenuData);
>       yield put({
>         type: 'save',
>         payload: response,
>       });
>       if (callback) callback(response);
>     },
>   },
> 
>   reducers: {
>     save(state, action) {
>       return {
>         ...state,
>         menuData: action.payload || [],
>       };
>     },
>   },
> };
> export default MenuModel;
> ```
> 
> 第二步：
> 在layout页面中加载
> 
> ```shell
> dispatch({
>   type: 'menu/getMenuData',
> });
> ```
> 
> 最后一步：**不要忘记**
> 
> ```shell
> export default connect(({ global, settings, menu }: ConnectState) => ({
>   collapsed: global.collapsed,
>   settings,
>   menuData: menu.menuData, // 不要忘记在这里注入
> }))(BasicLayout);
> ```
> 
> 目前使用后设置语言就不起作用了，还没找到原因。


请问这个方法的服务器菜单支持默认全展开吗？
