### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by zhangjunhou** [ant-design/ant-design-pro#436]
Failed to compile.

4.async.js from UglifyJs
Unexpected character '`' [4.async.js:327,10]

5.async.js from UglifyJs
Unexpected character '`' [5.async.js:301,10]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro-simple@0.2.3-rc.1 build: `roadhog build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro-simple@0.2.3-rc.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/*****/.npm/_logs/2017-12-14T08_04_55_109Z-debug.log

**Comment by afc163** [comment]
升级你的 node。

**Comment by afc163** [comment]
master 工作正常，应该不是我们的问题。
