### ISSUE TITLE
请问这个menu判断是做什么用的？

### ISSUE THREAD

**Issue by uv-w** [ant-design/ant-design-pro#4360]
![image](https://user-images.githubusercontent.com/17735161/58806975-d1141680-8649-11e9-8ce6-fdd444cd9c68.png)

**Comment by uv-w** [comment]
另外SettingDrawer默认也没有了？

**Comment by chenshuai2144** [comment]
create umi 初始化之后的将会是干净的。没有 SettingDrawer 是 pro 演示需要的。
