### ISSUE TITLE
命令下载不下来

### ISSUE THREAD

**Issue by blackboy1987** [ant-design/ant-design-pro#4362]
npx umi block add EditorKoni  --path=/editor/koni 这个命令。下载过程中出现：
![image](https://user-images.githubusercontent.com/6405701/58844085-2c74f180-86a8-11e9-9cb1-cce0fcb620fd.png)

**Comment by chenshuai2144** [comment]
包安装失败了。你可能需要用 cnpm 或者 yarn 重新安装一下

**Comment by afc163** [comment]
我们内置工具优先用 cnpm/tnpm 安装依赖吧。

**Comment by chenshuai2144** [comment]
cnpm 安装完会不兼容 npm。
我们考虑过这个方案

**Comment by afc163** [comment]
`cnpm install --by=npm`

**Comment by chenshuai2144** [comment]
这个样不如 
`npm install --registry=https://registry.npm.taobao.org`

@yutingzhao1991  你来看一下

**Comment by afc163** [comment]
这两个本质是等效的，上面那个还有镜像下载可以走。

**Comment by blackboy1987** [comment]
好的 我试试

**Comment by blackboy1987** [comment]
@chenshuai2144 可以了 谢谢

**Comment by yutingzhao1991** [comment]
现在支持 `--npm-client=cnpm`  这个参数。
