### ISSUE TITLE
升级2.0，启动报yaml错误

### ISSUE THREAD

**Issue by playedclass** [ant-design/ant-design-pro#4363]
![image](https://user-images.githubusercontent.com/3337266/58845918-ab215d00-86af-11e9-8076-326143583331.png)
注释错误，是哪里配置有问题吗
yaml load failed: YAMLException: end of the stream or a document separator is expected at line 1, column 2:
     @description: 日志搜索表单
     ^
yaml load failed: YAMLException: end of the stream or a document separator is expected at line 1, column 2:
     @description: 敏感字段管理
     ^
yaml load failed: YAMLException: end of the stream or a document separator is expected at line 1, column 2:
     @description: 敏感字段表单
     ^

**Comment by chenshuai2144** [comment]
你确定这是前端？ 这是 java 的写法呀

**Comment by playedclass** [comment]
对啊，所以我也感觉奇怪，就是通过https://github.com/ant-design/ant-design-pro-site/blob/bb1f0915a35bb97f86155ee4970f9da06dd8c4ff/docs/upgrade-v2.zh-CN.md 这个改的

查了下，hexo有这问题，说是把注释改成---，感觉有点奇怪

**Comment by chenshuai2144** [comment]
代码展示一下？

**Comment by playedclass** [comment]
![image](https://user-images.githubusercontent.com/3337266/58849318-7ff13a80-86bc-11e9-9dca-2894f25d66df.png)
现在报的错都是页头注释，新项目我直接用pro新版就没问题，老项目升级就卡住了。。

**Comment by playedclass** [comment]
![363C5350-3313-436F-AED0-C9D33A3B0B29](https://user-images.githubusercontent.com/3337266/58855599-00229a80-86d3-11e9-8ede-05a03fda0d4e.png)
不知道是不是上面的引起找不到依赖的，无论用原来的别名还是umi推荐的@字符都报错 @chenshuai2144

**Comment by playedclass** [comment]
找到原因了，看router.js发现用的不是配置式路由，然后才发现把config目录放到src下了。。。

**Comment by weiyingbin** [comment]
你好，请问你是怎么解决的。我用的umi.js搭建的项目，在文件头加上与你类似的注释，启动时也报这个错误。
