### ISSUE TITLE
为什么我用chrome找不到那个传说中的下载按钮？

### ISSUE THREAD

**Issue by zhou0818** [ant-design/ant-design-pro#4364]
mac上，用chrome打开预览站，找不到那个右下角的下载按钮。。
用Safari是有这个下载按钮的

**Comment by chenshuai2144** [comment]
用 隐私模式试一试呢

**Comment by playedclass** [comment]
版本 74.0.3729.169（正式版本） （64 位）
我的这个版本可以看到

**Comment by zhou0818** [comment]
> 用 隐私模式试一试呢

隐私模式看到了。。这是缓存问题？

**Comment by chenshuai2144** [comment]
是的。可能 pwa 还留在你的电脑中。清一下
