### ISSUE TITLE
使用umi block添加区块的时候怎么指定使用Javascript啊

### ISSUE THREAD

**Issue by YAN7** [ant-design/ant-design-pro#4365]
使用`umi block add DashboardAnalysis  --path=/dashboard/analysis`添加的区块默认使用的ts，我想换成用js的，有提供这个功能吗

**Comment by chenshuai2144** [comment]
正在紧张开发中，暂时没有这个功能

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/2554
