### ISSUE TITLE
antd-pro 依赖安装问题

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4366]
各位大神好！

 我在cnpm install 依赖的时候，报这个错误
![image](https://user-images.githubusercontent.com/44084004/58847509-cc854780-86b5-11e9-8b39-bb52d8c7f372.png)
 请问 各位有遇过吗？
![image](https://user-images.githubusercontent.com/44084004/58847537-e6bf2580-86b5-11e9-870d-67ecf0cc96b6.png)
这个是我npm、cnpm、node 所使用的版本信息。
谢谢！

**Comment by chenshuai2144** [comment]
先用 npm install 一下。不行的话删除 node-moudles ，然后再install

**Comment by zhangWeiZhuang** [comment]
> 先用npm install一下。不行的话删除node-moudles，然后再安装

你好。打扰了。我按照你说的方式还是不行
