### ISSUE TITLE
V4版本标题问题

### ISSUE THREAD

**Issue by 952425340** [ant-design/ant-design-pro#4367]
V4版本新建的一个登陆页使用了UserLayout这个布局标题显示异常，缺少项目名，而且还没有翻译
![图片](https://user-images.githubusercontent.com/22728007/58847598-25ed7680-86b6-11e9-850e-1fd8a07bddee.png)

**Comment by chenshuai2144** [comment]
fixed

**Comment by afc163** [comment]
要写明修复的 commit，并在那个 commit 里关联一下，不然已经下载的用户不知道怎么改。

**Comment by afc163** [comment]
最好的方式是修复的时候把 issue 写在 commit message 的 body 里和相关的 PR 里，这样可以一起关联和关闭。https://github.com/ant-design/ant-design/commit/553487e0062fd7f9372324d63654fbcc57ed3a8f
