### ISSUE TITLE
umi block add 报错

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#4369]
执行报错：
LdeMacBook-Pro:umi4 liyanru$ umi block add TableList
Warning: Please use `require("react-router").matchPath` instead of `require("react-router/matchPath")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Router` instead of `require("react-router/Router")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Switch` instead of `require("react-router/Switch")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Route` instead of `require("react-router/Route")`. Support for the latter will be removed in the next major release.
✔ Parse url and args
✔ Git fetch
✔ Git checkout master
✔ Git pull
✖  error     AssertionError [ERR_ASSERTION]: /Users/liyanru/.umi/blocks/github.com/ant-design/pro-blocks/TableList don't exists 
    at /Users/liyanru/Documents/svn/cmsTemplate/trunk/umi4/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:246:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/liyanru/Documents/svn/cmsTemplate/trunk/umi4/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:38:103)
    at _next (/Users/liyanru/Documents/svn/cmsTemplate/trunk/umi4/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:40:194)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by ffalconjs** [comment]
umi block add ant-design-pro/TableList 也报同样的错

**Comment by chenshuai2144** [comment]
`umi block add TableList` 这样用

**Comment by ffalconjs** [comment]
LdeMacBook-Pro:umi4 liyanru$ umi -v
2.7.0

**Comment by afc163** [comment]
`umi block add TableList` 好像和楼主的用法没什么区别。

**Comment by afc163** [comment]
https://github.com/ant-design/pro-blocks/tree/master/ListTableList

**Comment by afc163** [comment]
- ListTableList
- TableList
- ant-design-pro/TableList

看着很奇怪。

**Comment by ffalconjs** [comment]
试了几个都不行

**Comment by ffalconjs** [comment]
block 应该也没写错
LdeMacBook-Pro:umi4 liyanru$ umi block list
Warning: Please use `require("react-router").matchPath` instead of `require("react-router/matchPath")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Router` instead of `require("react-router/Router")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Switch` instead of `require("react-router/Switch")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Route` instead of `require("react-router/Route")`. Support for the latter will be removed in the next major release.

  Blocks:

    ant-design-pro/AccountCenter
    ant-design-pro/AccountSettings
    ant-design-pro/AdvancedForm
    ant-design-pro/AdvancedProfile
    ant-design-pro/Analysis
    ant-design-pro/BasicForm
    ant-design-pro/BasicList
    ant-design-pro/BasicProfile
    ant-design-pro/CardList
    ant-design-pro/Exception403
    ant-design-pro/Exception404
    ant-design-pro/Exception500
    ant-design-pro/Monitor
    ant-design-pro/ResultFail
    ant-design-pro/ResultSuccess
    ant-design-pro/SearchListApplications
    ant-design-pro/SearchListArticles
    ant-design-pro/SearchListProjects
    ant-design-pro/StepForm
    ant-design-pro/TableList
    ant-design-pro/UserLogin
    ant-design-pro/UserRegister
    ant-design-pro/UserRegisterResult
    ant-design-pro/Workplace
    blank
    demo-with-dependencies
    demo
    user-dashboard

**Comment by ffalconjs** [comment]
这个也不行
LdeMacBook-Pro:umi4 liyanru$ umi block add https://github.com/umijs/umi-blocks/tree/master/TableList

**Comment by afc163** [comment]
应该是 `npx umi block add ListTableList  --path=/list/table-list`

<img width="533" alt="image" src="https://user-images.githubusercontent.com/507615/58849489-16256080-86bd-11e9-8c64-ffbb7a5860f7.png">

**Comment by afc163** [comment]
- [ ] `umi block list` 有问题
- [ ] https://github.com/ant-design/pro-blocks/tree/master/ListTableList#usage 这里也有问题。

@chenshuai2144 要统一一下调用方式。

**Comment by ffalconjs** [comment]
确实是名字的问题，下面的名称就可以成功
LdeMacBook-Pro:umi4 liyanru$ umi block add ListTableList
LdeMacBook-Pro:umi4 liyanru$ umi block add EditorFlow

**Comment by ffalconjs** [comment]
如果能支持多级目录会好一点，现在add后 目录结构并不友好

**Comment by afc163** [comment]
` --path=/list/table-list`

**Comment by ffalconjs** [comment]
--path=/list/table-list 确实可以，文档里的说明再清晰一点可能会更好，看文档的第一印象觉得path只是设置路由
LdeMacBook-Pro:umi4 liyanru$ umi block add EditorKoni --path=/Editor/Koni
执行结果
        {
          name: 'koni',
          path: '/editor/koni',
          component: './Editor/Koni',
        },

**Comment by afc163** [comment]
```diff
- --path=/Editor/Koni
+ --to Editor/Koni
```

这个参数改成这样比较好理解，也看着比较易读。

@yutingzhao1991

**Comment by zywkuo** [comment]
npx umi block add UserLogin  --path=/user/login 报错
我把路由配置写在router.config.ts中，执行block命令，报如下错误，改为router.config.js在执行就好了
<img width="1032" alt="WX20190604-145154@2x" src="https://user-images.githubusercontent.com/21994183/58857759-8beaf580-86d8-11e9-9bfd-55f19db04d90.png">

**Comment by yutingzhao1991** [comment]
@zywkuo 这个可能是 umi 区块的一个 bug，找路由文件的时候没有考虑 ts，可以建个 issue 到 umi。

**Comment by yutingzhao1991** [comment]
> 这个参数改成这样比较好理解，也看着比较易读。

嗯，`to` 感觉确实清晰些。

**Comment by bobosbenben** [comment]
![AVI_VP`NW7A@7U0CVL0MGN7](https://user-images.githubusercontent.com/12725799/60004347-03d88a00-969f-11e9-8f6d-0a6013fc4a0d.png)

**Comment by chenshuai2144** [comment]
try use `npx umi block list`

**Comment by puretang** [comment]
> try use `npx umi block list`

开始安装了，但是遇到的麻烦太多了。

Parse url and args
✔ 🚒  Git fetch
✔ 🚛  Git checkout master
✔ 🚀  Git pull
✖ 📦  Install additional dependencies ant-design-pro@^2.1.1,numeral@^2.0.6 with npm --registry https://registry.npm.taobao.org
✖  error     Error: Error: Command failed: npm install ant-design-pro@^2.1.1 numeral@^2.0.6 --registry=https://registry.npm.taobao.org --save
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of @typescript-eslint/parser@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@1.13.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.14.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-react@^7.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint-plugin-import@^2.17.2 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@1.13.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-import@^2.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-react@^7.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint@^4.19.1 || ^5.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint-plugin-import@^2.17.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.18.2 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsdoc@4.8.4 requires a peer of eslint@>=4.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.2.3 requires a peer of eslint@^3 || ^4 || ^5 || ^6 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.14.3 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ant-design/create-react-context@0.2.4 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ant-design/icons-react@2.0.1 requires a peer of react@16.x but none is installed. You must install peer dependencies yourself.
npm WARN rc-drawer@2.0.3 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN rc-editor-mention@1.1.13 requires a peer of react@>=15.x but none is installed. You must install peer dependencies yourself.
npm WARN rc-editor-mention@1.1.13 requires a peer of react-dom@>=15.x but none is installed. You must install peer dependencies yourself.
npm WARN draft-js@0.10.5 requires a peer of react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js@0.10.5 requires a peer of react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-editor-core@0.8.10 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-editor-core@0.8.10 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js@0.10.5 requires a peer of react@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js@0.10.5 requires a peer of react-dom@^0.14.0 || ^15.0.0-rc || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ant-design/create-react-context@0.2.4 requires a peer of prop-types@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ant-design/create-react-context@0.2.4 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@1.9.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@1.9.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-tabs@9.6.4 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by f7753** [comment]
执行`umi block add ant-design-pro/flow`  会遇到类似的错误，检查目录下确实没有对应的文件夹

**Comment by f7753** [comment]
shall we reopen this issue?

**Comment by fanchangyong** [comment]
> 应该是 `npx umi block add ListTableList --path=/list/table-list`
> 
> <img alt="image" width="533" src="https://user-images.githubusercontent.com/507615/58849489-16256080-86bd-11e9-8c64-ffbb7a5860f7.png">


问下preview页面的这个复制命令的东西为什么不见了？

**Comment by osamasayed** [comment]
I got it working by adding the full path of the block from the list of [blocks](https://github.com/ant-design/pro-blocks) after `umi block add`. e.g. `umi block add https://github.com/ant-design/pro-blocks/tree/master/UserRegisterResult`
