### ISSUE TITLE
优先用 cnpm 安装区块

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#4372]
或者比较国内源和国外源的速度，优先选用速度快的那个。

https://github.com/ant-design/ant-design-pro/issues/4362

**Comment by yutingzhao1991** [comment]
可以在 pro 中配置：

```
block: {
  npmClient: 'cnpm'
}
```

**Comment by chenshuai2144** [comment]
内置一下吧。如果没有 cnpm 会不会报错?

**Comment by afc163** [comment]
不能默认写死，要做判断。

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/2541
在这里跟进吧
