### ISSUE TITLE
config/router.config 文件没有了？

### ISSUE THREAD

**Issue by wangjusheng** [ant-design/ant-design-pro#4374]
config/router.config 文件没有掉了？怎么设置路由？

**Comment by chenshuai2144** [comment]
在这里
https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L102 
你可以可以将其分离出去

**Comment by omarc1492** [comment]
Sorry to re-open this, but how do I add sidebar menu dropdowns? I am trying to add menu categories like 

> Dashboard

![Capture](https://user-images.githubusercontent.com/10967529/60358271-38985a00-999b-11e9-8378-7f86f6d92be6.PNG)  ![Capture1](https://user-images.githubusercontent.com/10967529/60358358-76957e00-999b-11e9-95fc-486e83dd50b6.PNG)



 I can not find in documentation and doing `npx umi block add DashboardMonitor --path=/dashboard/monitor`  does not work.

It used to be something like this. [https://github.com/xiaohuoni/umi-antd-pro/blob/95c9298a6560add01825f4b9b5d0ea3789f60d47/config/router.config.js](url)

**Comment by chenshuai2144** [comment]
@omarc1492   give a new issue
