### ISSUE TITLE
切换主题时，背景色和字体色一样了，这时应该是白色字体

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#4375]
![image](https://user-images.githubusercontent.com/18542211/58856357-0e71b600-86d5-11e9-9b22-555906a23509.png)
**注：顶部菜单并且是dark风格时才会这样。**

**Comment by kaoding** [comment]
这个是使用新的主题切换后产生的 @chenshuai2144

**Comment by chenshuai2144** [comment]
这个主题插件还有一些已知问题。
他是根据颜色 来的不是根据了 less 变量，所以会造成这些问题。

**Comment by kaoding** [comment]
我是觉得这个是很好的解决方案，我报这个是不知道怎么解决，那样的话就可以让他变得更好。

**Comment by chenshuai2144** [comment]
这个是通过正则的，你可以帮助他忽略一下 class

**Comment by hzsrc** [comment]
问题原因是由于css优先级的微妙关系，后面加载的主题色样式覆盖了原来的样式。
解决办法有2种：
1、调整源冲突样式的优先级，使css不会被主题色样式覆盖。推荐这种方法。
2、如果源码无法调整，目前只能通过changeSelector方式解决这类问题，类似如下，有点Hack，但目前也找不到其他好办法。
`    config.plugin('webpack-theme-color-replacer').use(ThemeColorReplacer, [
      {
        fileName: 'css/theme-colors.css',
        matchColors: getAntdSerials('#1890ff'), // 主色系列
        // 改变样式选择器，解决样式覆盖问题
        changeSelector(selector: string): string {
          switch (selector) {
            case '.ant-calendar-today .ant-calendar-date':
              return ':not(.ant-calendar-selected-date)' + selector;
            case '.ant-btn:focus,.ant-btn:hover':
              return '.ant-btn:focus:not(.ant-btn-primary),.ant-btn:hover:not(.ant-btn-primary)';
            case '.ant-btn.active,.ant-btn:active':
              return '.ant-btn.active:not(.ant-btn-primary),.ant-btn:active:not(.ant-btn-primary)';
            default:
              return selector;
          }
        },
      },
    ]);`
