### ISSUE TITLE
2.2.0 版本 的standardtable 能否设置单选，和单选时触发时间？

### ISSUE THREAD

**Issue by h499360594** [ant-design/ant-design-pro#4377]
RT

**Comment by chenshuai2144** [comment]
暂时不支持，你可以直接下载区块，在区块中改动

**Comment by Wmstone** [comment]
可以修改一下standardtable组件，const rowSelection = {type: radioType} ,radioType 为变量，参考table组件，传入什么类型就是什么类型

**Comment by h499360594** [comment]
> 可以修改一下standardtable组件，const rowSelection = {type: radioType} ,radioType 为变量，参考table组件，传入什么类型就是什么类型

嗯，已经自己修改了，我误以为这个是完善的功能组件了。谢谢。
