### ISSUE TITLE
[v4]执行yarn fetch:blocks，如果已存在某些区块，则安装卡住不动

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design-pro#4378]
卡在已存在区块的地方

**Comment by chenshuai2144** [comment]
这个区块主要是用来部署 pro 官网的。如果已经存在了，umi block add 就会让你选择新的 path，但是现在这个选项被吃掉了。
如果只需要增加一两个 建议使用 umi block add

**Comment by liushan-github** [comment]
umi block add DashboardAnalysis
umi block add ant-design-pro/Analysis
umi block add Analysis
为什么试了这三个都无法安装这个分析页区块

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/98be9f18fe5acdabb59c7a6372b4070c0ebbfbaf/config/config.ts#L93

是不是旧的脚手架，加一下这个

**Comment by liushan-github** [comment]
不是，加了也还是报同样的错误
![image](https://user-images.githubusercontent.com/45805157/59417379-bbe17980-8df9-11e9-92cd-e7f21dd2e57b.png)

**Comment by chenshuai2144** [comment]
用官网的命令

 npx umi block add FormBasicForm  --path=/form/basic-form
