### ISSUE TITLE
我项目的后台是同一个请求url，根据post的传参不同后台进行接口的识别。发现roadhog.mock.js不支持这种情况？

### ISSUE THREAD

**Issue by hushiyi** [ant-design/ant-design-pro#438]
#### Environment(required) | 环境（必填）

- roadhog version（^1.3.1版本）
- Nodejs and Npm version（v6.5.0 和 5.5.1 版本）
- Operating environment (e.g. OS name) and its version（mac）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

import { format, delay } from 'roadhog-api-doc';

export default format({
  'POST /jkkit-gp/service': {
    $params:{
      method: 'cashier.paymentList'
    },
    $body: require('./mock/cashier.paymentList.json')
  },
   'POST /jkkit-gp/service': {
    $params:{
      method: 'cashier.pay'
    },
    $body: require('./mock/cashier.pay.json')
  }
});

#### What do you expected?（预期的正常效果）

希望请求参数method=cashier.paymentList的时候返回require('./mock/cashier.paymentList.json')的数据，请求参数为method=cashier.pay的时候请求require('./mock/cashier.pay.json')的数据

#### What happen?（发生了何种非正常现象）
发现不管请求哪个接口，最后都去请求了后面配置的require('./mock/cashier.pay.json')的数据

**Comment by kunhour** [comment]
You can write a functon that it return result by paramater

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/mock/rule.js#L23
