### ISSUE TITLE
调用 _.cloneDeep() 时报错 _ is not defined

### ISSUE THREAD

**Issue by wangjusheng** [ant-design/ant-design-pro#4380]
调用 _.cloneDeep() 时报错 _ is not defined
Unhandled Rejection (ReferenceError): _ is not defined

**Comment by xiaohuoni** [comment]
_是啥？

**Comment by wangjusheng** [comment]
我在原先的2.0的项目可以调用这个 _.cloneDeep() 深拷贝的函数，现在这个不行了，报错说 _ is not defined 




------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>; 
发送时间: 2019年6月4日(星期二) 晚上6:05
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>; 
抄送: "WangJS"<455945230@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] 调用 _.cloneDeep() 时报错 _ is not defined (#4380)




_是啥？

**Comment by afc163** [comment]
这个和 antd-pro 无关，请自行排查 lodash 依赖。
