### ISSUE TITLE
路由中的component可以不是字符串，而是从外部import的一个组件吗

### ISSUE THREAD

**Issue by barcelona11** [ant-design/ant-design-pro#4381]
路由中的component可以不是字符串，而是从外部import的一个组件吗？如果可以的话，应该怎么写？

**Comment by chenshuai2144** [comment]
写一个 page，然后里面引入这个组件就好了吧。
直接用外部的组件当 page吗？

**Comment by barcelona11** [comment]
这个办法我们之前也想过，当然如果能直接用外部组件当page是最好了。
另外，model能从外部import吗？
我们想由多个小组开发各自的模块，最后合成一个大的网站。

**Comment by chenshuai2144** [comment]
看看这个文章。你们的思路有问题
https://alili.tech/archive/9xuojm75d2a/
