### ISSUE TITLE
nginx 缓存 

### ISSUE THREAD

**Issue by MRStruggle** [ant-design/ant-design-pro#4383]
每次部署之后，chrome 浏览器 打开访问都不是最新的，刷新也不行，必须要清楚缓存才可以，这个问题有办法解决吗？有遇过的哥们吗

**Comment by afc163** [comment]
试试开启 https://umijs.org/config/#hash

**Comment by MRStruggle** [comment]
> 试试开启 https://umijs.org/config/#hash

我今天部署的 放上列，打包 果然带了一串，在看看 客户的反应吧  感谢 感谢

另外  
![image](https://user-images.githubusercontent.com/29857641/59899622-ec439c00-9427-11e9-9d81-bafa5f6bd497.png)
打包后 为啥di第一个文件要1.7m，其他的都是kb  这个有办法优化吗
