### ISSUE TITLE
ant design pro 4.0 新建后怎么只剩一个欢迎界面了

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#4385]
几天不看，从2.3升级到4.0了！！！
ant design pro 4.0 跑起来后怎么只剩一个欢迎界面了。
https://preview.pro.ant.design/dashboard/analysis，这上面的一些菜单，功能，可不可以加到开发环境。

**Comment by afc163** [comment]
Duplicate of #4351

Duplicate of #4368

**Comment by xyzabc0004** [comment]
谢谢，谢谢！看来脑细胞又得死不少了。
