### ISSUE TITLE
各种报错，各种错

### ISSUE THREAD

**Issue by tangtanglove** [ant-design/ant-design-pro#4386]
![image](https://user-images.githubusercontent.com/2425371/58937851-2cf3b200-87a6-11e9-8ea2-ad56947dffa7.png)
umi block add ant-design-pro/UserLogin
umi block add各种方法，各种路径都试过了，就是拉取不到区块！

**Comment by TokenTyler** [comment]
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/AccountCenter 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/AccountSettings 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/AdvancedForm 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/AdvancedProfile 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/Analysis 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/BasicForm 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/BasicList 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/BasicProfile 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/CardList 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/Exception403 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/Exception404 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/Exception500 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/Monitor 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/ResultFail 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/ResultSuccess 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/SearchListApplications 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/SearchListArticles 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/SearchListProjects 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/StepForm 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/TableList 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/UserRegister 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/UserRegisterResult 
umi block add  https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/Workplace

**Comment by chenshuai2144** [comment]
以这个为主 。 @yutingzhao1991  快点切换吧。
 http://preview.pro.ant.design

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4379
