### ISSUE TITLE
项目引入 ant-pro后 build Module parse failed: Unexpected character '@' (6:0) You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by Liaohuanle** [ant-design/ant-design-pro#439]
`
ERROR in ./node_modules/antd/lib/style/index.css

Module parse failed: Unexpected character '@' (6:0)

You may need an appropriate loader to handle this file type.

| /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors */

| /* stylelint-disable at-rule-no-unknown */

| @font-face {

|   font-family: "Helvetica Neue For Number";
|   src: local("Helvetica Neue");
 @ ./node_modules/antd/lib/tooltip/style/css.js 3:0-32
 @ ./node_modules/ant-design-pro/lib/Charts/MiniProgress/index.js
 @ ./node_modules/ant-design-pro/lib/Charts/index.js
 @ ./src/routes/label-report/component/chart.jsx
 @ ./src/routes/label-report/container.tsx
 @ ./src/routes/label-report/index.ts
 @ ./src/router.tsx
 @ ./src/index.js
`

**Comment by afc163** [comment]
你需要配置 css-loader 和 less-loader。
