### ISSUE TITLE
block是否可以增加多个界面以及多路由以及增加自定义宏

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4390]
目前是打算将一个业务模块作为一个 block。里面有多个界面以及路由。
这样的话许多通用的业务组件就会得到很好的维护以及很方便的集成。

如果将每一个界面都作为一个独立的block的话，维护起来也比较麻烦，由其是 model 当中的业务对象的类型定义还的 COPY 过来 COPY 过去，另外就是 model 之间还有一些复用，很难处理。

**Comment by chenshuai2144** [comment]
去 umi 提一下这个问题吧。感觉是微前端方案之一

**Comment by xiaopanghhh** [comment]
已提了。

https://github.com/umijs/umi/issues/2545#issue-452827709
