### ISSUE TITLE
ant design pro 4.0 footer 无法修改

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#4391]
![image](https://user-images.githubusercontent.com/32530210/59002255-5bc06580-8844-11e9-8c33-5cfd6726e837.png)

各位老师，pro 4.0的页脚，我想修改下，怎么也找不地方。
还请指点下。

**Comment by xiaopanghhh** [comment]
在这个地方修改，将这里的 defaultDom 换成你自己的就好了。
![image](https://user-images.githubusercontent.com/24469601/59004752-51ef3000-884d-11e9-8c86-f21752423841.png)


defaultDom 的代码在  https://github.com/ant-design/ant-design-pro-layout/blob/master/src/Footer.tsx

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/59010400-b4532b00-8863-11e9-98ba-487acaa445b5.png)

谢谢，谢谢，我把userlayout.tsx里面的footer，抄过来，放到 basiclayout.tsx了。

defaultDom 的代码在 https://github.com/ant-design/ant-design-pro-layout/blob/master/src/Footer.tsx
这个footer.tsx怎么在的项目里面找不到。

**Comment by GREENPEANS** [comment]
请问 "@ant-design/pro-layout": "^4.4.2" 版本无法更改或者替换自定义footer吗？ 
![image](https://user-images.githubusercontent.com/28837434/63236532-99903000-c270-11e9-9b59-40c9d4e2da72.png)这个是目录结构，我看footer信息在node包里？要直接更改node包吗
