### ISSUE TITLE
V4. npm run fetch:blocks 报错

### ISSUE THREAD

**Issue by liming8077** [ant-design/ant-design-pro#4395]
Module not found: Can't resolve '../list/search' in 'E:\2018dva\all-ant-pro\src\pages\.umi'

**Comment by dewice** [comment]
我也遇到相同的错误了。

**Comment by chenshuai2144** [comment]
不要在` yarn start`的时候运行 `fetch:blocks`,我会先注入路由。然后再进行区块的下载

**Comment by liming8077** [comment]
> 不要在` yarn start`的时候运行 `fetch:blocks`,我会先注入路由。然后再进行区块的下载

那我已经这样运行了，怎么解决呢？

**Comment by chenshuai2144** [comment]
关掉再来一次就好了

**Comment by aibinMr** [comment]
我遇到了这个问题 是因为安装提示中选择JavaScript版本造成的，这个版本缺少了scripts文件夹，这个直接从git项目中取下来就行了  然后去修改一下文件中config引入的路径，因为默认引入的是ts文件，修改成js就可以了
