### ISSUE TITLE
V4 中notification无法使用了。

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4397]
代码如下
```TypeScript
class Manager extends Component<ManagerProps, ManagerState>{

    openNotification = () => {
        console.log("ssss");
        notification.open({
            message: 'Notification Title',
            description:
                'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
            onClick: () => {
                console.log('Notification Clicked!');
            },
        });
    };
    render() {
        return (
            <PageHeaderWrapper title="综合设置">
                <Card bordered={false}>
           
                    <Button onClick={this.openNotification}>触发错误</Button>
                </Card>
            </PageHeaderWrapper>
        );
    }
}
```

notification无法 弹出了。测试了在utils/request.ts中的也无法正常使用！ @chenshuai2144

**Comment by chenfd99** [comment]
打正式包是没问题的

**Comment by chenshuai2144** [comment]
有报错信息吗？这个组件是 antd 中的，应该不受 pro 影响

**Comment by Lind-pro** [comment]
> 有报错信息吗？这个组件是 antd 中的，应该不受 pro 影响

不报错，就是不弹出来。用法应该是没问题的，之前版本的notification就没问题，升级V4以后都不能用了。我也有直接检出项目，然后触发/utils/request.ts的异常处理，发现notification也无效

**Comment by chenfd99** [comment]
应该就是global.less文件全局样式不生效的问题
去掉 config.js 中下面的代码就可以提示了
 // dll: {
          //   include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
          //   exclude: ['@babel/runtime', 'netlify-lambda'],
          // },

**Comment by Lind-pro** [comment]
> 打正式包是没问题的


> 应该就是global.less文件全局样式不生效的问题
> 去掉 config.js 中下面的代码就可以提示了
> // dll: {
> // include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
> // exclude: ['@babel/runtime', 'netlify-lambda'],
> // },
测试了一下。注释掉这个dll就可以正常用了。 

 @chenshuai2144 这个DLL的问题，好像之前就有ISSUE提到过。什么时候有好的解决办法呢？

**Comment by u0x01** [comment]
> > 有报错信息吗？这个组件是 antd 中的，应该不受 pro 影响
> 
> 不报错，就是不弹出来。用法应该是没问题的，之前版本的notification就没问题，升级V4以后都不能用了。我也有直接检出项目，然后触发/utils/request.ts的异常处理，发现notification也无效

我之前改 utils/request.ts 的时候也是这个问题，notification 不抛 error，我还以为 v4 不能弹 request 了，v2 正常的

**Comment by DieterLi** [comment]
注释掉dll，那么里面include的和dva有关的，不会对其他功能产生影响吗？求解释，否则单纯注释掉，心里不安那

**Comment by Lind-pro** [comment]
> 注释掉dll，那么里面include的和dva有关的，不会对其他功能产生影响吗？求解释，否则单纯注释掉，心里不安那

暂时没有影响

**Comment by wxb1123603312** [comment]
我也是这样 在我的mac上面弹窗就没反应也不报错 在windos上面就没问题
