### ISSUE TITLE
V4:Extracted theme color css content length: 7117

### ISSUE THREAD

**Issue by gentleKun** [ant-design/ant-design-pro#4398]
File sizes after gzip:

  1.8 MB    umi-dlls/umi.dll.js
  26.73 KB  umi-dlls/umi.css
刚拉下来的代码怎么打完包就这么 大？
Extracted theme color css content length: 7117
这个error是什么意思啊？
请求帮助！！！

**Comment by chenshuai2144** [comment]
> Extracted theme color css content length: 7117

这是个 warning. 


> 1.8 MB umi-dlls/umi.dll.js
 
dll 是一种本地使用的缓存，你可以理解为他是一个 node_modules 的压缩包
