### ISSUE TITLE
user目录下页面title有问题

### ISSUE THREAD

**Issue by aibinMr** [ant-design/ant-design-pro#4401]
user下页面title显示有问题 login页面只显示login- ，不会显示“登陆-XXX”，这个需要做额外的判断设置

**Comment by chenshuai2144** [comment]
刷新再看看。

**Comment by aibinMr** [comment]
> 刷新再看看。

我是在6月5号下午五点下载clone下来的，测试刷新user下面页面，显示不正确
`getPageTitle({
          pathname: location!.pathname,
          breadcrumb,
          formatMessage,
        })`这里执行后只能获得`login-`这个结果。还有像您请教下`/src/services`，这个目录文档叫做‘后台接口服务’，这个后端服务接口是什么意思，是不是做ajax请求服务器服务的ts文件的目录，如果是这样，那它和page目录下的service.ts的使用区别在哪里

**Comment by aibinMr** [comment]
> 刷新再看看。

其他目录下页面显示没有问题比如说‘dashboard’这个目录。

**Comment by chenshuai2144** [comment]
在这个提交里面修复的
https://github.com/ant-design/ant-design-pro/commit/fc136b6a2c732d9df2bd49bcdc0b6dbb5e6350df

你可以看一看
