### ISSUE TITLE
Actual Build size is Larger than the 'gzip files size' in terminal

### ISSUE THREAD

**Issue by strangewolf** [ant-design/ant-design-pro#4402]
So i am facing a weird issue related to build size.

I run the command to build.
`yarn build`

output: 

<img width="572" alt="Screenshot 2019-06-07 at 11 20 05 PM" src="https://user-images.githubusercontent.com/22832869/59124034-3fbfdf80-897c-11e9-8eef-48dcda852272.png">

Then i checked the output file in `/dist' folder.
And surprised to see the file size,

<img width="636" alt="Screenshot 2019-06-07 at 11 20 13 PM" src="https://user-images.githubusercontent.com/22832869/59124125-7dbd0380-897c-11e9-95e4-010d41be83d6.png">

I dont know why its says 1.99 MB file size in terminal if it is not ?

Any help? please?

**Comment by chenshuai2144** [comment]
wow, what have you done? What package is added?
Try `yarn analyze`

**Comment by afc163** [comment]
`1.99M` is the gzipped size of `6.9M`.

**Comment by strangewolf** [comment]
@afc163 i am sorry .. i am bit confused.. 
After gzipping the `index.js` file size is `1.99 MB`  then it should have been shown as `1.99 MB` as its file size ???



> `1.99M` is the gzipped size of `6.9M`.

@afc163 i am sorry .. i am bit confused.. 
After gzipping the `index.js` file size is `1.99 MB`  then it should have been shown as `1.99 MB` as its file size ???

please clear my dumb mind

**Comment by strangewolf** [comment]
> wow, what have you done? What package is added?
> Try `yarn analyze`

I shouldnt have removed `"precommit": "npm run lint-staged"`.. its make mistake.. i am sorting out build size.. though it was 9.2 MB before  XD .

yes running `yarn run analyze` helps me figuring out my mistake.

**Comment by afc163** [comment]
https://css-tricks.com/the-difference-between-minification-and-gzipping/
https://stackoverflow.com/questions/2712173/check-the-total-content-size-of-a-tar-gz-file
https://stackoverflow.com/questions/9468511/how-can-i-estimate-the-size-of-my-gzipped-script
https://stackoverflow.com/questions/2712173/check-the-total-content-size-of-a-tar-gz-file
