### ISSUE TITLE
release里没有4.0版本，readme说4.0版本发布，这是什么情况？

### ISSUE THREAD

**Issue by guotie** [ant-design/ant-design-pro#4403]
版本发布能不能严谨一点

**Comment by yutingzhao1991** [comment]
release 的 4.0 是指 ant-design-pro 这个包的 4.0，这个包后面不再有了。

@chenshuai2144 可能要在哪里说明下。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4338

![image](https://user-images.githubusercontent.com/8186664/59140532-770cab80-89d1-11e9-9362-66e474ff3a36.png)
