### ISSUE TITLE
V4还准备支持IE吗？

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design-pro#4405]
![image](https://user-images.githubusercontent.com/3994941/59144559-50b83180-8a0c-11e9-9408-6b4157520ae1.png)

IE11都报错

**Comment by chenshuai2144** [comment]
build 之后支持 ie11，开发环境只支持 chrome等现在浏览器

**Comment by miaozilong** [comment]
关键是build之后也不支持啊 ,只有一个等待的图标在转圈

**Comment by tudinger** [comment]
https://github.com/ant-design/ant-design-pro/issues/4479 同这个帖子一样

**Comment by miaozilong** [comment]
我的还是不行 谁能搞定的 加下我微信 有偿帮适配下IE11 WX 17008305539
