### ISSUE TITLE
4.0怎么新增页面

### ISSUE THREAD

**Issue by nishuer** [ant-design/ant-design-pro#4409]
在pages里面创建页面，按照文档说明在router.config.js里面新增路由配置后页面无法访问，并且文档里面写的路径是config/router.config.js，而脚手架里面的路径是scripts/router.config.js。

**Comment by SuFIND** [comment]
文档还没更新V4。如果是右边的sidemenu并添加页面的话，请到脚手架位置下config/config.js的里面的const route里面去配置，千万别碰src/page/.umi/route.js 每一次重新编译都会按照config里面的配置重新生成，另外子菜单的component生成的路径很奇怪，如果大佬可以的话试一下，一级菜单没问题

**Comment by afc163** [comment]
@zombieJ @chenshuai2144 文档漏了。

**Comment by FlyCai** [comment]
v4加菜单玩不转~~

**Comment by u0x01** [comment]
v4 好多文档还是 v2 的，坐等各位大佬踩坑 😂

**Comment by nishuer** [comment]
@SuFIND 谢谢，确实是在config/config.js里面增加路由。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/298

**Comment by zytjs** [comment]
入门-常见问题-models/menu `404`
入门-常见问题-config/router.config.js `项目没有此文件，路径是scripts/router.config.js?`
进阶-图表-查看图表组件/独立使用 Pro `组件 404`

**Comment by afc163** [comment]
close by ant-design/ant-design-pro-site#298

**Comment by ZhuMinCat** [comment]
我的菜单是从后台获取的，还要再config/config.js里面再配置路由?

**Comment by nishuer** [comment]
> 我的菜单是从后台获取的，还要再config/config.js里面再配置路由?

文档有写：https://pro.ant.design/docs/router-and-nav-cn
