### ISSUE TITLE
标题文字太长了之后就看不到了

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design-pro#4410]
![image](https://user-images.githubusercontent.com/3994941/59161246-c73f5700-8b12-11e9-95e2-83224e448f11.png)

需要修改node_modules/@ant-design/pro-layout/lib/TopNavHeader/index.less中的宽度才行,希望能在业务代码中修改  或者自动匹配

**Comment by chenshuai2144** [comment]
你可以覆盖掉这个 css 的，我们应该不会支持这么长的名字，不够美观。

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59401194-82dee000-8dcc-11e9-967b-c065a3873c7a.png)
@chenshuai2144 在哪覆盖啊  我在global.less里加了  结果被你的覆盖了

**Comment by chenshuai2144** [comment]
提一下 css优先级就好了
```
xxx .ant-pro-top-nav-header-logo{
    width:400px;
}
```

**Comment by miaozilong** [comment]
@chenshuai2144  谢谢  能用
