### ISSUE TITLE
改版之后的不适用，之前的版本如何能下载下来？

### ISSUE THREAD

**Issue by frontendWangqun** [ant-design/ant-design-pro#4412]
![image](https://user-images.githubusercontent.com/43572671/59170494-7a3e9d80-8b71-11e9-828e-bd2c38eb09bf.png)
改版之后的不适用，之前的版本如何能下载下来？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/59170687-6182b780-8b72-11e9-96c2-22a6806ed7f1.png)
https://github.com/ant-design/ant-design-pro/issues/4338
