### ISSUE TITLE
V4 底部的“2019 蚂蚁金服体验技术部出品”怎么配置，这玩意怎么写死在layout footer里面了

### ISSUE THREAD

**Issue by vipway** [ant-design/ant-design-pro#4414]
V4 底部的“2019 蚂蚁金服体验技术部出品”怎么配置，这玩意怎么写死在layout footer里面了

**Comment by xiaohuoni** [comment]
通过 `footerRender` 属性重制掉就可以了。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.tsx#L44

**Comment by yinhunfeixue** [comment]
const footerRender: BasicLayoutProps['footerRender'] = (_, defaultDom) => {
  return React.cloneElement(defaultDom as ReactElement, { links: [], copyright: '你的公司名称’ });
}

**Comment by kennylbj** [comment]
这里涉及的不大合理，如果用户要重置footer，需要clone cloneElement，没法直接给links、copyright这两个属性赋值。
