### ISSUE TITLE
4.0版本, 独立使用Pro组件没有文档 / No documentation for using standalone components in v4

### ISSUE THREAD

**Issue by magickaichen** [ant-design/ant-design-pro#4424]
如题，4.0版本的文档里没有“独立使用Pro组件”，并且图表文档里面“独立使用Pro组件”的链接无效：
https://pro.ant.design/docs/use-components-alone-cn

希望能尽快补充

-------------------------
As said, there's no "Use Pro Components Alone" documentation page anymore. It was there during the v2. Hope it can be added back soon.

**Comment by chenshuai2144** [comment]
pro 4.0 删除了组件，你如果需要使用 可以看 https://v2-pro.ant.design/

**Comment by cerebrowang** [comment]
如题，4.0版本的文档里没有“独立使用Pro组件”，并且图表文档里面“独立使用Pro组件”的链接无效：
https://pro.ant.design/docs/use-components-alone-cn

希望能尽快补充

As said, there's no "Use Pro Components Alone" documentation page anymore. It was there during the v2. Hope it can be added back soon.
