### ISSUE TITLE
「讨论」安装需要的模块时间太久了，不知道有没有更优的包管理方案

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#4426]
每次clone pro，`yarn` 或者 `npm i` 已经科学上网了，
还是安装很久，还会失败。
特别是umi 更新到2.7之后
安装模块最终会经常停留在这个状态
```sh
 Building fresh packages...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[5/6] ⠠ puppeteer
```

**Comment by chenshuai2144** [comment]
cnpm 就可以了 

连你都不看我们的官网吗？

https://pro.ant.design/docs/faq-cn#npm-%E5%AE%89%E8%A3%85-puppeteer-%E5%A4%B1%E8%B4%A5
