### ISSUE TITLE
v4 pro-layout组件onCollapse

### ISSUE THREAD

**Issue by zywkuo** [ant-design/ant-design-pro#4428]
<img width="859" alt="WX20190611-103714@2x" src="https://user-images.githubusercontent.com/21994183/59239739-27c6b500-8c35-11e9-8716-34f26c25e4f5.png">
<img width="100" alt="WX20190611-103947@2x" src="https://user-images.githubusercontent.com/21994183/59239866-a58ac080-8c35-11e9-999a-2900fdf9db64.png">

- 将collapsed设置为false 时，控制展开关闭Icon没有隐藏，页面中没有找到相关代码，应该是写在pro-layout组件中了吧，如果要去掉是需要重写headerRender方法吗? 

- 是否可以再collapsed设置为false时就去掉控制展开关闭的icon？

- collapsed和onCollapse参数是否重复？

- 是否可以添加默认是展开还是关闭的参数？

**Comment by chenshuai2144** [comment]
> 将collapsed设置为false 时，控制展开关闭Icon没有隐藏，页面中没有找到相关代码，应该是写在pro-layout组件中了吧，如果要去掉是需要重写headerRender方法吗?

 是的。

> 是否可以再collapsed设置为false时就去掉控制展开关闭的icon？

你为什么要这么做？


> collapsed和onCollapse参数是否重复？

collapsed 和onCollapse 是一对标准的受控模式。

>  是否可以添加默认是展开还是关闭的参数？

暂时只支持受控模式

**Comment by zywkuo** [comment]
在读V4代码，初衷是为了找到icon位置。

**Comment by zhangzhi93** [comment]
请问下怎样重写headerRender方法可以去掉展开关闭Icon？

**Comment by chenshuai2144** [comment]
css最方便了
