### ISSUE TITLE
分页组件调用真实数据后似乎出现bug

### ISSUE THREAD

**Issue by cocojian** [ant-design/ant-design-pro#443]
分页组件调用真实数据后，上一页永远无法激活，下一页永远都去第一页，向后5页也没有效果。有人遇到国这个问题吗？

**Comment by afc163** [comment]
无法重现，请确认是 antd 或是 pro 的问题再开 issue。

**Comment by cocojian** [comment]
加了pageSize后出现这样的情况，不加的话没问题

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。
