### ISSUE TITLE
在项目中运行 npm run fetch:blocks，报以下错：

### ISSUE THREAD

**Issue by frontendWangqun** [ant-design/ant-design-pro#4431]
![image](https://user-images.githubusercontent.com/43572671/59250422-cd8c1b00-8c59-11e9-8164-dcbf5cced576.png)

**Comment by chenshuai2144** [comment]
请使用 typescript 版本的 pro

**Comment by frontendWangqun** [comment]
> 请使用 typescript 版本的 pro

用js的不行吗？还没用过ts呢

**Comment by chenshuai2144** [comment]
我们推荐全部用 ts。 typescript 优点非常多

**Comment by frontendWangqun** [comment]
> 我们推荐全部用 ts。 typescript 优点非常多

这个问题是使用js导致的吗？

**Comment by chenshuai2144** [comment]
是的。

**Comment by jinfei** [comment]
如果只支持ts ，那还放js版本做什么。。。。。。。

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/2554
