### ISSUE TITLE
chrome 样式错误

### ISSUE THREAD

**Issue by Yaorj** [ant-design/ant-design-pro#4432]
![image](https://user-images.githubusercontent.com/20807269/59252097-de3e9000-8c5d-11e9-9f89-95fe13665839.png)

红框部分是循环出的 select 上面是 chrome 会出现空白，下面 firefox是正常发，如果循环 input 就不会出现空白，谁遇到过

**Comment by Yaorj** [comment]
根本没人理吗。。。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16809#issuecomment-496131765

**Comment by Yaorj** [comment]
![image](https://user-images.githubusercontent.com/20807269/59327384-f1b03080-8d1b-11e9-8447-e6f562aab470.png)
这么修改还是不好用

**Comment by Yaorj** [comment]
![image](https://user-images.githubusercontent.com/20807269/59327437-1a382a80-8d1c-11e9-8438-5c79c8be7923.png)
把项目名称放到了后面，好了。。。

**Comment by Yaorj** [comment]
最终解决方案  Select添加 height:40px
