### ISSUE TITLE
V4 中routes二级菜单配置authority不能控制显示

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4433]

**Comment by Lind-pro** [comment]
代码如下
```
routes: [
    {
      path: '/',
      component: '../layouts/BasicLayout',
      Routes: ['src/pages/Authorized'],
      routes: [
        {
          path: 'system',
          name: 'system',
          icon: 'setting',
          routes: [
            {
              path: '/system/user',
              name: 'user',
              component: './system/users',
              authority: ['user'],
            },
            { path: '/system/role', name: 'role', component: './system/role' },
            { path: '/system/permission', name: 'permission', component: './system/permission' },
            { path: '/system/dictionary', name: 'dictionary', component: './system/dictionary' },
          ],
        },
       ]
    }
]
```

在二级菜单user这一层加了 authority: ['user'],菜单还是存在
![image](https://user-images.githubusercontent.com/18098618/59252407-9f5d0a00-8c5e-11e9-912a-104f32053859.png)

但点击后跳转到403。请问怎么配置，没有权限就不显示菜单呢？在一级菜单中配置authority就可以实现无权限不显示菜单 @chenshuai2144

**Comment by Lind-pro** [comment]
![image](https://user-images.githubusercontent.com/18098618/59266423-35eaf480-8c7a-11e9-8cb6-319ee70b3143.png)


在
```
   {
              path: '/system/user',
              name: 'user',
              component: './system/users',
              authority: ['user'],
            },
```
配置了authority后爆上图这样的错误。我怎么能够控制子菜单显示呢？ @chenshuai2144

**Comment by Lind-pro** [comment]
@xiaohuoni 能看看是为什么嘛？已经研究了好长时间不知道怎么解决

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/98be9f18fe5acdabb59c7a6372b4070c0ebbfbaf/src/layouts/BasicLayout.tsx#L37

你加了这个代码了吗？

**Comment by Lind-pro** [comment]
> https://github.com/ant-design/ant-design-pro/blob/98be9f18fe5acdabb59c7a6372b4070c0ebbfbaf/src/layouts/BasicLayout.tsx#L37
> 
> 你加了这个代码了吗？

检出来的代码中本来就是包含了这段代码的。今天已经解决了这个问题了。更改了第40行，解决了这个问题。。。感觉应该是一个BUG。

**Comment by chenshuai2144** [comment]
来个 pr 懒一下？

**Comment by Lind-pro** [comment]
> 来个 pr 看一下？

好吧。

**Comment by nightsu** [comment]
> > https://github.com/ant-design/ant-design-pro/blob/98be9f18fe5acdabb59c7a6372b4070c0ebbfbaf/src/layouts/BasicLayout.tsx#L37
> > 
> > 你加了这个代码了吗？
> 
> 检出来的代码中本来就是包含了这段代码的。今天已经解决了这个问题了。更改了第40行，解决了这个问题。。。感觉应该是一个BUG。

我也遇到了这个问题，请问可以分享您是如何解决的吗

**Comment by LIFANGTIAN** [comment]
您好 请问您是怎么改的 能说下吗 也碰到了类似的问题
