### ISSUE TITLE
menu的奇怪问题

### ISSUE THREAD

**Issue by ityao** [ant-design/ant-design-pro#444]
代码整合新添加SiderMenu后出现这问题, 用最原始的ant.design样例代码加进SiderMenu也是这样
如下图, 在Menu的Collapsed状态下, 为什么子菜单二级菜单不是弹出右边显示, 而是显示成下拉菜单了

![image](https://user-images.githubusercontent.com/832215/34022748-f4577804-e17b-11e7-89d1-6d2caecbf588.png)

**Comment by afc163** [comment]
现在 master 分支应该是没问题的，你先对比一下？

**Comment by ityao** [comment]
查了一天都没找到问题啊,真奇怪

**Comment by ityao** [comment]
莫名其妙又好了, 偶发现象
