### ISSUE TITLE
antd@next

### ISSUE THREAD

**Issue by JoeyKo** [ant-design/ant-design-pro#445]
When i add page with pro-cli `pro generate`, then choose page -> BasicList

finally, BasicList import antd components with 'antd@next'
`import { List, Card, Row, Col, Radio, Input, Progress, Button, Icon, Dropdown, Menu, Avatar } from 'antd@next';`

**Comment by nikogu** [comment]
fixed: https://github.com/ant-design/ant-design-pro-cli#027
