### ISSUE TITLE
PageHeader 作为组件使用是 children 没有渲染

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design-pro#446]
### 代码：
```jsx
const Shows = ({
  match,
  // dispatch,
}) => {
  const action = (
    <div>
      <Button type="default">创建</Button>
      <Button type="default">刷新</Button>
    </div>
  );
  return (
    <PageHeader
      title="课堂列表"
      action={action}
    >
    课堂列表
    </PageHeader>
  );
};
```
### 渲染结果
![image](https://user-images.githubusercontent.com/2703455/34026275-d04c9e3a-e18f-11e7-9df7-1a763ecef2f1.png)

```html
<div class="antd-pro-page-header-pageHeader">
  <div class="antd-pro-page-header-detail">
    <div class="antd-pro-page-header-main">
      <div class="antd-pro-page-header-row">
        <h1 class="antd-pro-page-header-title">课堂列表</h1>
        <div class="antd-pro-page-header-action">
          <div>
            <button type="button" class="ant-btn ant-btn-default">
              <span>创 建</span>
            </button>
            <button type="button" class="ant-btn ant-btn-default">
              <span>刷 新</span>
            </button>
          </div>
        </div>
      </div>
      <div class="antd-pro-page-header-row"></div>
    </div>
  </div>
</div>
```

### 组件文档 codepen 链接显示异常
https://pro.ant.design/components/PageHeader-cn/#scaffold-src-components-PageHeader-demo-structure

打开后页面一片空白
![image](https://user-images.githubusercontent.com/2703455/34026076-8b7bfcac-e18e-11e7-84d8-df8429e94e13.png)

控制台报错 PageHeader is not defined
![image](https://user-images.githubusercontent.com/2703455/34026091-adde7e50-e18e-11e7-997f-c4bb24927c57.png)

**Comment by kunhour** [comment]
Maybe you need to learn React "Foundation"

**Comment by nikogu** [comment]
@xiaosongxiaosong `PageHeader` 确实不能使用 `children`，组件的设置是使用 `content` 作为内容：

```js
<PageHeader
      title="这是一个标题"
      content={content}
      extraContent={extra}
      breadcrumbList={breadcrumbList}
/>
```

**Comment by nikogu** [comment]
codepen 的问题应该是打包的问题，之后发个 `1.0.0-rc` 版本会修复这个问题

**Comment by doterme** [comment]
@nikogu 什么时候发布1.0版本？

**Comment by chenshuai2144** [comment]
@doterme  下周 下周

**Comment by xiaosongxiaosong** [comment]
@chenshuai2144 加油加油

没仔细看代码，Workplace 页面使用的是 PageHeaderLayout，封装了一层。

**Comment by yearnZero** [comment]
@chenshuai2144 下周要发布1.0版本吗？公司的一个平台管理系统想用这个为基础搭建。

**Comment by nikogu** [comment]
@yearnZero 对，下周

**Comment by xiaosongxiaosong** [comment]
@nikogu 最新版本打包好像还是有问题

![image](https://user-images.githubusercontent.com/2703455/34904876-4aabe3ec-f889-11e7-855d-98c385710735.png)
