### ISSUE TITLE
为什么刚初始化的代码，commit 通不过呀

### ISSUE THREAD

**Issue by zhangyu921** [ant-design/ant-design-pro#4469]
![image](https://user-images.githubusercontent.com/19166761/59319878-d8e55200-8cfe-11e9-8e2c-8968032bfde1.png)
![image](https://user-images.githubusercontent.com/19166761/59319883-ddaa0600-8cfe-11e9-86ec-e13cd0e878fe.png)
![image](https://user-images.githubusercontent.com/19166761/59319962-22ce3800-8cff-11e9-8537-b91db3b771b6.png)

体验上有点让人不舒服，希望能解决下

**Comment by pandaApe** [comment]
文档上好像有说的

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4336

你是配置了特殊的lint吗

**Comment by zhangyu921** [comment]
@chenshuai2144 并没有呀，莫非我是个案 0 0

**Comment by afc163** [comment]
重现步骤：

```
npx create-umi myapp
cd myapp
npm install
npm run lint
```

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/507615/59480084-d1a27d80-8e91-11e9-80c5-8e55e4ce4b7e.png">

**Comment by GrowingMonkey** [comment]
> #4336
> 
> 你是配置了特殊的lint吗

请问commit  是否可以关闭lint？

**Comment by chenshuai2144** [comment]
你是使用 js 版本吗？
ts 的版本是 ok 的

**Comment by zhangyu921** [comment]
是的



------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>; 
发送时间: 2019年6月14日(星期五) 下午5:27
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>; 
抄送: "51410206"<51410206@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] 为什么刚初始化的代码，commit 通不过呀 (#4469)




你是使用 js 版本吗？
 ts 的版本是 ok 的
 
&mdash;

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4336
这个和了就好了 ts 和 eslint 是两个不同的规则
