### ISSUE TITLE
yarn create umi 初始出来的ant-design-pro不是master分支最新的吗？

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#4472]
yarn create umi 初始出来的ant-design-pro不是master分支最新的吗？没有对比其他，就大概看了一下package.json文件 好像有些不一样

**Comment by poklau123** [comment]
我这也是，`yarn create umi` 生成的antd pro项目下的 package.json 中`"version": "1.0.0"`。看文档中说：[推荐使用 yarn create 命令，能确保每次使用最新的脚手架](https://umijs.org/zh/guide/create-umi-app.html#%E5%88%9B%E5%BB%BA-umi-%E9%A1%B9%E7%9B%AE)。不知道是哪里出了问题？

**Comment by chenshuai2144** [comment]
我们对create的代码做了处理，删除一些用不到的脚本，比如部署pro的

**Comment by blueBubble89** [comment]
> 我这也是，`yarn create umi` 生成的antd pro项目下的 package.json 中`"version": "1.0.0"`。看文档中说：[推荐使用 yarn create 命令，能确保每次使用最新的脚手架](https://umijs.org/zh/guide/create-umi-app.html#%E5%88%9B%E5%BB%BA-umi-%E9%A1%B9%E7%9B%AE)。不知道是哪里出了问题？
> 
> ```shell
> $ yarn create umi
> yarn create v1.15.2
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> success Installed "create-umi@0.13.4" with binaries:
>       - create-umi
> ? Select the boilerplate type ant-design-pro
> ? Which language do you want to use? JavaScript
> > git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> > [Sylvanas] Prepare js environment...
> > [JS] Clean up...
> > Clean up...
> ✨ File Generate Done
> Done in 12.73s.
> ```

你的疑问解决了吗？

**Comment by poklau123** [comment]
> > 我这也是，`yarn create umi` 生成的antd pro项目下的 package.json 中`"version": "1.0.0"`。看文档中说：[推荐使用 yarn create 命令，能确保每次使用最新的脚手架](https://umijs.org/zh/guide/create-umi-app.html#%E5%88%9B%E5%BB%BA-umi-%E9%A1%B9%E7%9B%AE)。不知道是哪里出了问题？
> > ```shell
> > $ yarn create umi
> > yarn create v1.15.2
> > [1/4] Resolving packages...
> > [2/4] Fetching packages...
> > [3/4] Linking dependencies...
> > [4/4] Building fresh packages...
> > success Installed "create-umi@0.13.4" with binaries:
> >       - create-umi
> > ? Select the boilerplate type ant-design-pro
> > ? Which language do you want to use? JavaScript
> > > git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> > > [Sylvanas] Prepare js environment...
> > > [JS] Clean up...
> > > Clean up...
> > ✨ File Generate Done
> > Done in 12.73s.
> > ```
> 
> 你的疑问解决了吗？

这个应该是V4版本 `yarn create umi` 后对代码进行了删改，实际上是V4的代码，但是少了很多之前版本有的组件，规划上看是准备放在antd里面，但是目前又没上，文档当时也很多还是V2的东西和V4根本对不上号~~将就着用，实在不行翻源码看（刚又去看了一下发现很多文档已经更新👍）。
