### ISSUE TITLE
Tree组件里面的这个属性defaultExpandAll 默认是hi展开所有节点，但是我配置了没有效果。是我这样写的不正确吗？

### ISSUE THREAD

**Issue by blackboy1987** [ant-design/ant-design-pro#4473]
![image](https://user-images.githubusercontent.com/6405701/59326777-33d87280-8d1a-11e9-995a-dd9a6062bbc6.png)

**Comment by chenshuai2144** [comment]
因为你这个 nodeRender 是异步的，异步加载回来的节点不会帮你自动打开，你可以使用受控模式来做到这个事情

**Comment by blackboy1987** [comment]
嗯 已经解决了
