### ISSUE TITLE
下载的时候选的JavaScript，但是block下载下来都是typeScript

### ISSUE THREAD

**Issue by aaronxdd** [ant-design/ant-design-pro#4474]
<img width="1153" alt="图片" src="https://user-images.githubusercontent.com/16145101/59332856-c7fe0600-8d29-11e9-8bbc-96f09e78d343.png">
下载的时候选的JavaScript，但是block下载下来都是typeScript

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/2554
