### ISSUE TITLE
https://preview.pro.ant.design打不开

### ISSUE THREAD

**Issue by garrett12138** [ant-design/ant-design-pro#4475]
浏览器：
Chrome 74.0.3729.131（正式版本） （32 位）
firefox  67.0.1 (64 位)
一直处理loading状态
Chrome 控制台输出以下错误信息：
umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at i (umi.js:1)
    at Object.PKem (vendors.async.js:1)
    at i (umi.js:1)
    at Module.m8Tn (layouts__BasicLayout.async.js:1)
    at i (umi.js:1)
    at async Promise.all (/index 0)
i @ umi.js:1
PKem @ vendors.async.js:1
i @ umi.js:1
m8Tn @ layouts__BasicLayout.async.js:1
i @ umi.js:1
Promise.then (async)
(anonymous) @ umi.js:1
t @ umi.js:1
y.resolve @ umi.js:1
value @ umi.js:1
r @ umi.js:1
So @ umi.js:1
Ba @ umi.js:1
Qa @ umi.js:1
fc @ umi.js:1
pc @ umi.js:1
Jc @ umi.js:1
Zc @ umi.js:1
Wc @ umi.js:1
gc @ umi.js:1
ol @ umi.js:1
al @ umi.js:1
sl.render @ umi.js:1
(anonymous) @ umi.js:1
nl @ umi.js:1
hl @ umi.js:1
render @ umi.js:1
g @ umi.js:1
o @ umi.js:1
(anonymous) @ umi.js:1
(anonymous) @ umi.js:1
(anonymous) @ umi.js:1
Promise.then (async)
KyW6 @ umi.js:1
i @ umi.js:1
1 @ umi.js:1
i @ umi.js:1
(anonymous) @ umi.js:1
(anonymous) @ umi.js:1
less.min.js:13 b.exports {message: "Unrecognised input", stack: undefined, type: "Parse", filename: "https://preview.pro.ant.design/color.less", index: 0, …}
d @ less.min.js:13
Promise.then (async)
2.../less/default-options @ less.min.js:13
e @ less.min.js:13
a @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
(anonymous) @ less.min.js:13
31The script has an unsupported MIME type ('text/html').

**Comment by ldwonday** [comment]
这个问题我也遇到了，发布到线上，有的最新的谷歌浏览器报错，我的谷歌浏览器上面也是报错
![image](https://user-images.githubusercontent.com/4630157/59418370-8047af00-8dfb-11e9-8136-d1e96085da62.png)
![image](https://user-images.githubusercontent.com/4630157/59418381-8473cc80-8dfb-11e9-9336-76b436cea7c4.png)
