### ISSUE TITLE
typescript引用Charts中的Pie组件时报错：JSX 元素类型“Pie”不具有任何构造签名或调用签名

### ISSUE THREAD

**Issue by Maggiewow** [ant-design/ant-design-pro#4478]
![image](https://user-images.githubusercontent.com/39367320/59422718-6ad68300-8e03-11e9-87c2-da8e79aca72c.png)

报错：JSX 元素类型“Pie”不具有任何构造签名或调用签名。

用同样的方式，引入Charts中的MiniArea是没有问题的

**Comment by chenshuai2144** [comment]
用绝对路径引用呢？

**Comment by Maggiewow** [comment]
> 用绝对路径引用呢？

你是指绝对路径直接引用Pie，还是引用Chart？试过绝对路径直接引用Pie，会导致该组件的样式丢失
