### ISSUE TITLE
Build且Nginx部署后，ie11仍然无法查看内容

### ISSUE THREAD

**Issue by comiscienceknight** [ant-design/ant-design-pro#4479]
参照教程https://pro.ant.design/docs/getting-started-cn
我下载安装build了原有程序，然后使用nginx发布，但是ie11上只有如下图显示:

SCRIPT1002: Syntax error
layouts__BasicLayout.async.js (12,462063)

![image](https://user-images.githubusercontent.com/3014982/59380489-85542200-8d59-11e9-96e0-ff03fadb494a.png)

如图所示。根据其他帖子，做了相关的调整，还是不好使。如:
`targets: {
    ie: 11
  },`

PS：我并没有对官方代码进行任何修改

我得部署方案是修改nginx的conf，将build后的文件夹指定给localhost，如下代码所示：
`
         server {
		listen 80;
                server_name  localhost;
		root   "c:/Projects/Others/test antd pro/dist/";
		index  index.html index.htm;
		# gzip config
		gzip on;
		gzip_min_length 1k;
		gzip_comp_level 9;
		gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
		gzip_vary on;
		gzip_disable "MSIE [1-6]\.";
		location / {
                       root   "c:/Projects/Others/test antd pro/dist";
		       index  index.html index.htm;
                }
	}
`

**Comment by tudinger** [comment]
我们遇到了同样的问题。当前项目版本是2.3.1，ie11不好用。所以选择使用最新版按照教程安装，npm run build，然后发布到nginx服务器（也试了npm run docker:push）

在ie上仍然无法显示，和上述截图非常相似

**Comment by miaozilong** [comment]
我也急等兼容IE11方案 试了好久  没试出来

**Comment by tudinger** [comment]
我退回了2.3.1.... v4暂时放弃~~

**Comment by miaozilong** [comment]
> 我退回了2.3.1.... v4暂时放弃~~

哥们 加我微信

**Comment by miaozilong** [comment]
> 时放弃~~

17008305539

**Comment by miaozilong** [comment]
各位大神  救救我

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59515854-a8660980-8ef2-11e9-892f-d6cb092e8b1c.png)
刚下载下来的原版也不行  master分支的   使用create-umi创建的  也不行

**Comment by miaozilong** [comment]
搞了两天了   实在搞不动了

**Comment by miaozilong** [comment]
头发都快掉了

**Comment by tudinger** [comment]
哥，你这个是微信还是qq啊，我找不到人啊...

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59518678-ba4aab00-8ef8-11e9-87f9-e3d990f5feb6.png)
@tudinger  微信啊

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59555663-82229580-8fe8-11e9-9227-78302b15ee04.png)
我已经在虚拟机里试了,*新系统*,create-umi创建出来的原版ant design pro  
IE11下也*运行不了*

**Comment by chenshuai2144** [comment]
应该react-media-hook2 这个库没有 build 代码。让ie10 挂掉了。
已经联系作者重新发布了，再试试

**Comment by miaozilong** [comment]
我这还不行 @chenshuai2144   
我再等等了

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59972843-ea650e80-95c8-11e9-83c9-2914bb54d0f5.png)
打包完成后,还设有const语句

**Comment by chenshuai2144** [comment]
http://test.preview.pro.ant.design/ 
试试这个，里面有 soucremap。你可以看到是哪个库干的。

**Comment by chenshuai2144** [comment]
已经在 ie11 测试过 pro 的preview，可以访问。

**Comment by miaozilong** [comment]
@chenshuai2144  我更新了一下  原版确实好了  
我加了个redux-logger插件就不行了  生成的umi.js中含有const语法
![image](https://user-images.githubusercontent.com/3994941/60194983-e822de80-986c-11e9-9127-4d3005dfdd2b.png)

**Comment by miaozilong** [comment]
dva.js文件内容
==========================
export const dva = {
  config: {
    onError(e) {
      e.preventDefault();
      console.error(e.message);

    },
    onEffect() {
      console.log('...')
    },
  },
  plugins: [
    require('dva-logger')(),
  ],
};

**Comment by miaozilong** [comment]
删掉dva.js就好了

**Comment by miaozilong** [comment]
可能是我安装依赖的使用使用的 --save  我改成 --save-dev试试
