### ISSUE TITLE
萌新伸手党：请问pro是否有纯前端的excel导入模块呢

### ISSUE THREAD

**Issue by phper-chen** [ant-design/ant-design-pro#448]
不通过后端，直接导入到输入框里面显示，请问有这样的模块吗

**Comment by kunhour** [comment]
In current Programming technology, can not do it; Maybe it is supported "CSV" file.

**Comment by chenshuai2144** [comment]
可以试试 [js-xlsx](https://github.com/SheetJS/js-xlsx)

**Comment by phper-chen** [comment]
嗯 好吧 还是走后端吧 谢谢回答～
