### ISSUE TITLE
PageHeaderWrapper tabList 的 tab 的数据类型扩展一下。

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4483]
![image](https://user-images.githubusercontent.com/24469601/59417362-b421d500-8df9-11e9-8a7c-8787eb971f7d.png)

**Comment by chenshuai2144** [comment]
why？

**Comment by WuJiY** [comment]
因为现在tab类型是string，你想要其他类型， 层主是这个意思吧？

**Comment by chenshuai2144** [comment]
用 formatMessage 就可以了
