### ISSUE TITLE
右上角切换语言报错

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#4484]
![image](https://user-images.githubusercontent.com/18098618/59417700-4c1fbe80-8dfa-11e9-934d-a0363451417f.png)

检出现有的代码。运行后点击切换语言，报如上图错误

**Comment by afc163** [comment]
重新安装 node_modules 即可。

**Comment by Lind-pro** [comment]
> 重新安装 node_modules 即可。

试过了，重新安装依然有问题，还是如上图错误

**Comment by afc163** [comment]
删除 yarn.lock 和 package-lock.json 后重装 node_modules 再试。

**Comment by Lind-pro** [comment]
> 删除 yarn.lock 和 package-lock.json 后重装 node_modules 再试。

通过此方法已解决问题。
