### ISSUE TITLE
Some confusion about V4.0

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design-pro#4485]
os: win7
1. No typescript: I used `npm create umi` and selected `ant-design-pro` but I didn't see any ts code.
2. Layout is the same as before: When I opened the layouts folder, I saw the same code as before, I thought it would use [ant-design-pro-layout](https://github.com/ant-design/ant-design-pro-layout) to refactor.
3. About block: I saw this sentence on the official website, But I didn't find the "add to project" button.
> In our preview website, you can click 'add to project' to get the command with current page.

**Comment by chenshuai2144** [comment]
1 and 2  you should use `npx create umi`
3 try clear cache

**Comment by kwzm** [comment]
@chenshuai2144 Hi, I still haven't solved the first two problems. I found after first step: `Select the boilerplate type`, there was no prompt for me to choose typescript or javascript directly on git clone... in my IDE.
ps: This is a special case because none of my colleagues have encountered this problem :cry:

**Comment by kwzm** [comment]
@chenshuai2144 I found the reason, probably because my create-umi version was low, after I reinstalled the new version it was ok.
