### ISSUE TITLE
ant design的嵌套子路由问题

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#4486]
1. 列表页和详情页是独立的路由，列表页输入查询条件，查询结果，然后点击查看。
2. 页面跳转到详情页
3. 点击返回，返回到列表页，但是列表页的查询条件已经丢弃。

不想用redux，想利用父子路由来做，请问ant design如何实现嵌套子路由，父子路由拥有独立的路由插座。

**Comment by chenshuai2144** [comment]
总需要个地方来存东西。
不想使用 redux 可以把所有需要的信息传到 url 上。
