### ISSUE TITLE
请教卡片列表卡片内容更新最佳方式

### ISSUE THREAD

**Issue by GQMai** [ant-design/ant-design-pro#4487]
请问应该如何卡片列表单独刷新某一个卡片内容？例如点击某一个卡片中的操作一从后台获取数据然后更新卡片。
我尝试设计了一个CustomCard 类继承自Card，然后和指定的Model绑定，但是感觉model和CustomCard 是一对多的关系而不是一对一，只要有一个卡片内容更新，所有的卡片都会更新。

谢谢。

**Comment by chenshuai2144** [comment]
你可以给每个 card 设置一个 id ，然后在 card 中取请求数据。
