### ISSUE TITLE
formatMessage, FormattedMessage  的类型加载，加载不到界面模块下面的定义国际化文件

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4488]
![image](https://user-images.githubusercontent.com/24469601/59434072-64ed9b80-8e1d-11e9-9682-57c47738bd2e.png)

**Comment by keke122765** [comment]
同问

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4515

**Comment by chenshuai2144** [comment]
@ycjcl868  可能需要更好的方案了

**Comment by ycjcl868** [comment]
目前是临时方案，终极方案在 umi dev 的时候，将 umi 内部 merge 的 locales 生成 d.ts

**Comment by chenshuai2144** [comment]
有没有临时解决方案，怎么设置一下可以变成 any 之类的

**Comment by amoibean** [comment]
解决方案见 https://github.com/umijs/umi/issues/2652#issuecomment-506299473
