### ISSUE TITLE
在Drawer中，里面内容可以滚动的情况下，如何让它滚动到最顶部？

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design-pro#4489]
在Drawer中，内容过多会形成滚条，可以滚动。在最底部的时候，我想调用某个方法，让它滚动到最顶部（在控制台里尝试的方法都无效），请问我该怎么做？谢谢！

![QQ20190613-0](https://user-images.githubusercontent.com/40480550/59439905-a899d280-8e28-11e9-8a6d-390c1d14ac4e.png)

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollTop
