### ISSUE TITLE
Slider component misplaced tooltip

### ISSUE THREAD

**Issue by bravoeguizabal** [ant-design/ant-design-pro#4490]
If you download ant-design-pro and create a page with just one Slider component like:
<Slider defaultValue={50} tooltipVisible tooltipPlacement={"bottom"} />
The tooltip is misplaced after you collapse and expand the menu.

Initially
![image](https://user-images.githubusercontent.com/33873082/59458949-96e50a80-8de9-11e9-8d09-3a8b45883983.png)

After collapsing:
![image](https://user-images.githubusercontent.com/33873082/59458975-aa907100-8de9-11e9-884b-f596db3128c3.png)

After expanding:
![image](https://user-images.githubusercontent.com/33873082/59459009-c562e580-8de9-11e9-8ac7-567709504862.png)

 The sample code is the same as the Welcome.tsx page but with an additional slider element on top

`import React from 'react';
import { Slider } from 'antd';

export default () => (
<>
  <Slider defaultValue={50} tooltipVisible tooltipPlacement={"bottom"} />
  <p style={{ textAlign: 'center' }}>
    Want to add more pages? Please refer to{' '}
    <a href="https://pro.ant.design/docs/block-cn" target="_blank" rel="noopener noreferrer">
      use block
    </a>
    。
  </p>
</>
);
`

**Comment by chenshuai2144** [comment]
Antd will not listen to your screen changes. If you do this, it will cause a terrible performance pin. You can close the tooltip and then open it when the screen changes.
