### ISSUE TITLE
npm run fetch:blocks 报错 解决

### ISSUE THREAD

**Issue by wangtoday** [ant-design/ant-design-pro#4492]
搭建脚手架, 运行 fetch:blocks时候报错, 逐步查看原因是获取github上的url的时候报错:

```
{
message: API rate limit exceeded for 116.92.204.173. (But here’s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)”,
documentation_url:[https://developer.github.com/v3/#rate-limiting](https://developer.github.com/v3/#rate-limiting) “
}
```

没有找到相关的解答, 贴上我的解决方法:

添加自己的client_id 和 client_secret, 将`fetch-blocks.js`中的` fetchGithubFiles
` 中的url 添加自己的GitHub设置过的client_id 和 client_secret信息就可以fetch到正确的信息了

`
https://api.github.com/repos/ant-design/pro-blocks/git/trees/master?client_id={your id}&client_secret={your secret}
`

谢谢

**Comment by chenshuai2144** [comment]
你干了什么。github拦住了你？这个和 pro 无关的

**Comment by afc163** [comment]
GitHub API 确实容易有问题，要找更好的方式。
