### ISSUE TITLE
关于Table冻结问题

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4494]
各位大神好，今天小弟在做Table冻结的时候遇到一个问题
![image](https://user-images.githubusercontent.com/44084004/59486123-ea6b5d00-8eaa-11e9-97ec-1682353dedc8.png)
![image](https://user-images.githubusercontent.com/44084004/59486134-f22b0180-8eaa-11e9-8c9c-116de8194fa2.png)
我的代码只冻结了x列，没有冻结y列，但是右侧冻结列缺莫名的多出来一块空白区域，我猜测应该是滚动条。但是我没有冻结y不知道为什么会出来。
"antd": "^3.19.3", antd最新版本也不行呢。还希望各位大神指点下

**Comment by Wmstone** [comment]
看之前的issue里面有说过，可以试着倒数第二列不设置宽度

**Comment by afc163** [comment]
宽度写死了而且不对等，`x + x + x + x > y` 或者 `x + x + x + x < y`。可选方案：

1. 无脑 `scroll={{ x: 'max-content' }}`
2. 或者 `x + x + x + x === y`。
3. 或者留一列或几列不设宽度，以适应弹性布局。
