### ISSUE TITLE
Typescript can't work well with locale id autocomplete feature

### ISSUE THREAD

**Issue by laozhu** [ant-design/ant-design-pro#4496]
When I use ant-design-pro v4, TypeScript is the default option and the feature of locale id autocomplete feature is very awesome. but I still have two problems here:

1. When the locale id contains variables, just like `app.global.role.${role}` format, TypeScript will give an error below.

![image](https://user-images.githubusercontent.com/1212457/59489069-d0824800-8eb3-11e9-9976-c774292bea38.png)

2. If I use locale in block-scoped, the autocomplete of locale id failed and TypeScript will give an error too. Now I have to import all my block-scoped locales in global locale files to fix the feature.

**Comment by afc163** [comment]
ref https://github.com/umijs/umi/pull/2469

**Comment by chenshuai2144** [comment]
ant-design/ant-design-pro#4515

**Comment by amoibean** [comment]
See https://github.com/umijs/umi/issues/2652#issuecomment-506299473 for a workaround.
