### ISSUE TITLE
npm run fetch:blocks: 没有报错，但是在install login to:/user/login这步就不执行了

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4498]
npm run fetch:blocks: 没有报错，但是在install login to:/user/login这步就不执行了。

有两周没有上github，今天来一看炸了窝了。有几个建议：

1：别着急发布新版本，等稳定了。
2：尽量做减法，轻装上阵，既然退出了TS版本，原先的JS版本就别维护了。还有浏览器的兼容等

**Comment by fanhualei** [comment]
不是不执行了，而是执行的很慢，5分钟下载一个文件。
我用npm install 下载全部的库，也没用2分钟。

**Comment by hkl921010** [comment]
同样的问题 +1

**Comment by waylon-edmodo** [comment]
确定不是很慢，是根本不会继续执行。相同的问题。
