### ISSUE TITLE
第一次打开的时候很慢，以后都比较快，如何解决

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#4499]
我看了一下 
vendors.xxxxxx.async.js 1.5M  耗时 7.47s
umi.xxxxx.js  1.4 M  耗时：8.34s

如果加带宽、。、请问有办法解决吗？？ 比如把 vendors 和 umi的js  搞成多个小的集合。

**Comment by afc163** [comment]
https://juejin.im/post/5af003286fb9a07aac24611b

**Comment by xgj1988** [comment]
@afc163  嗯。。加了gzip也是有点慢，，我想问一下我能不能先做一个 loading 的界面 ，然后加载完之后跳转到 登录界面，这样 体验要好点，，只是我不知道怎么做。

**Comment by afc163** [comment]
Try https://github.com/ant-design/ant-design-pro/blob/67b0dcd90b3f4d5fa8a5b3935a496550a176ffa6/config/config.ts
