### ISSUE TITLE
test:all在Linux平台测试无法通过

### ISSUE THREAD

**Issue by linhanyang** [ant-design/ant-design-pro#450]
![68e203fb-40bf-4449-b8dc-ce96b1ed9d69](https://user-images.githubusercontent.com/7603016/34044702-060b47dc-e1e1-11e7-803d-7d7289f262f2.png)

**Comment by afc163** [comment]
https://travis-ci.org/ant-design/ant-design-pro

这个就是在 linux 上跑的，最好先自行检查一下环境和原因。

**Comment by XebniDev** [comment]
这个是CI跑的时候的要求  [点我](https://pro.ant.design/docs/ui-test-cn#%E6%8E%A5%E5%85%A5%E9%9B%86%E6%88%90%E6%B5%8B%E8%AF%95%E6%9C%8D%E5%8A%A1)

如果需要接入 travis、CircleCI、Gitlab CI 等集成测试环境，可以参考本仓库提供的 .travis.yml。
注意 e2e 测试需要集成环境支持 electron，如果不支持，你可以使用 npm test .test.js 单独运行单元测试。

估计是你没有虚拟显示驱动造成的，查查electron 文档。
