### ISSUE TITLE
Ant Design Pro v4.0 使用 Ant Design 的 Notification 组件样式错误

### ISSUE THREAD

**Issue by ZenoZhengs** [ant-design/ant-design-pro#4501]
在 Ant Design Pro v4.0 中使用 Ant Design 的 Notification 组件出现样式错误
审查元素的样式表没有发现.ant-notification .ant-notification-topRight
貌似是没有加载相应的css文件引起的
与之类似的Message组件没有出现问题

没有单独使用过Ant Design组件库,只使用过Ant Design Pro v4.0, 所以不清楚是哪部分引起的

渲染后的界面截图如下所示:
<img width="2032" alt="Screen Shot 2019-06-15 at 11 05 03" src="https://user-images.githubusercontent.com/45112245/59546473-aaff4800-8f60-11e9-8762-97ed1f10d447.png">

bug实例代码在:
https://github.com/ZenoZhengs/notification-bug.git

**Comment by XSmarter** [comment]
+1

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4537
