### ISSUE TITLE
如何移除国际化？

### ISSUE THREAD

**Issue by l2en** [ant-design/ant-design-pro#4505]
修改.umirc下的LocaleWrapper.jsx后还是无法去除，控制台仍会出现警告，文档有明确说了不建议直接修改.umirc的文件。 建议给一个启用国际化的配置项会更友好更适合小企业使用~😸

**Comment by xiaohuoni** [comment]
感觉旧代码中就默认设置中文，新代码里面直接写上中文，也不会有任何影响的吧？

**Comment by loveship00** [comment]
这么简单且普遍的问题一直不解决，很难让人相信这是一个可用于生产环境的产品。

**Comment by afc163** [comment]
Duplicate of #3775

**Comment by afc163** [comment]
@loveship00 欢迎参与贡献。

**Comment by soulmatecm** [comment]
> 这么简单且普遍的问题一直不解决，很难让人相信这是一个可用于生产环境的产品。

柑橘根本就是一个无法用于生产的东西，一直都没有一个稳定的版本，而且过度设计，及其繁琐。

**Comment by chenshuai2144** [comment]
@soulmatecm 一个开源软件，如果停止更新就是死掉了

**Comment by chenhonghui** [comment]
真的太老火了， 确实就这么简单一个要求，去国际化，烦

**Comment by chenhonghui** [comment]
希望默认不要加入国际化

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/available-script-cn#npm-run-i18n-remove
