### ISSUE TITLE
ProLayoutComponents 命名不好

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#4511]
应该改为 `ProLayout`。

https://github.com/ant-design/ant-design-pro/blob/98be9f18fe5acdabb59c7a6372b4070c0ebbfbaf/src/layouts/BasicLayout.tsx#L97

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4336

这个合进来之后一起搞掉。现在改会冲突。
