### ISSUE TITLE
umi module not found when using the ant-design-pro\lib\Authorized

### ISSUE THREAD

**Issue by luhc228** [ant-design/ant-design-pro#4512]
I have added the antd dependency to my ICE project and my project can run normally. But today after I updating the dependency, it throw an error. 
![](https://i.loli.net/2019/06/16/5d06069e2e31f54988.jpg)
Then, I added the umi dependency but I still throw an error.   
![](https://i.loli.net/2019/06/16/5d060685214fc17336.png)  

So could u give me some advice to solve this problem?

**Comment by chenshuai2144** [comment]
https://unpkg.com/ant-design-pro@2.2.1/lib/Authorized/ 

It exists

**Comment by iugo** [comment]
I have a same  error.

After "ant-design-pro" from "2.0.0" to "2.3.2", had this problem.

```
ERROR in ./node_modules/ant-design-pro/lib/Authorized/AuthorizedRoute.js
Module not found: Error: Can't resolve 'umi' in './node_modules/ant-design-pro/lib/Authorized'
 @ ./node_modules/ant-design-pro/lib/Authorized/AuthorizedRoute.js 13:11-25
 @ ./node_modules/ant-design-pro/lib/Authorized/index.js
 @ ./node_modules/ant-design-pro/lib/index.js
```

**Comment by chrispytoes** [comment]
I also have the same issue when attempting to run an existing project on a different PC.

```
./node_modules/ant-design-pro/lib/Authorized/AuthorizedRoute.js
Module not found: Can't resolve 'umi' in 'E:\Projects\dtms\dtms-client\node_modules\ant-design-pro\lib\Authorized'
```

**Comment by sterkhedkar** [comment]
Module not found: Can't resolve 'umi' in 'C:\Users\xxx\Documents\projects\xxxx\xxxx\xxxx\node_modules\ant-design-pro\lib\Authorized'

Same error. What are we missing out here?

**Comment by Elonnn** [comment]
I got the same error when I tried to import like 
`import { Result } from 'ant-design-pro';`.
After switching to
`import Result from 'ant-design-pro/lib/Result';`,
the error has gone.
Helpful link:
[https://v2-pro.ant.design/docs/use-components-alone](https://v2-pro.ant.design/docs/use-components-alone)
