### ISSUE TITLE
如何从服务器请求菜单？ 文档描述错误

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4514]
如何从服务器请求菜单？ 文档描述错误
https://pro.ant.design/docs/faq-cn

找不到 models/menu  这个文件

![menu](https://user-images.githubusercontent.com/34436863/59563070-a2de0000-9067-11e9-90c0-3101d7260f00.png)

**Comment by blackboy1987** [comment]
这个是2.0版本的文档

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/301
