### ISSUE TITLE
webstorm中formatMessage提示id错误

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4515]
webstorm中formatMessage提示id错误

formatMessage({ id: 'form-basic-form.goal.required' })

![formatmessage](https://user-images.githubusercontent.com/34436863/59563988-98c1fe80-9073-11e9-8a93-f7e130b788f1.png)

**Comment by ycjcl868** [comment]
将区块的 locales 目录与项目的 locales 合并下，共用同一份国际化配置。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4488
来这里看吧

**Comment by amoibean** [comment]
解决办法见 https://github.com/umijs/umi/issues/2652#issuecomment-506299473
