### ISSUE TITLE
pages/form/basic-form/index.tsx 编译器中提示错误

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4516]
pages/form/basic-form/index.tsx 编译器中提示错误

## import { AnyAction } from 'redux';
```
ESLint: 'redux' should be listed in the project's dependencies. Run 'npm i -S redux' to add it (import/no-extraneous-dependencies)
```

## effects: EffectsCommandMap & { select: <T>(func: (state: ModalState) => T) => T },
```
ESLint: 'T' is not defined. (no-undef)
```

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/4336
