### ISSUE TITLE
ant design pro token 过期 刷新

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#4517]
各位老师请教下，
ant design pro token 过期 刷新
这个怎么实现下，

还请指点下，谢谢！

**Comment by xyzabc0004** [comment]
我在想，是不是可以这样：

假如登陆后token1 1800S后过期，并在浏览器local storage记录拿到token1 的时间time1。搞个请求的中间件，当系统时间-time1>1500S，调用refreshtoken接口。更新成本地的token1和time1。拿新的token去作后面的请求。

不知道是不是这么回事。还是有其它办法。

**Comment by xiaohuoni** [comment]
实际上token过期是服务端的事情吧

**Comment by xyzabc0004** [comment]
是的，但我想在token没有过期的情况下，得更新下token，不然他每1800S后，就要登录一次。前台不知道咋整。还想到的一个办法是定时器，自动刷token。

**Comment by chenshuai2144** [comment]
@xyzabc0004 浏览器关了你就没办法处理了，你可以存下载 获得 token 的时间，每次进入校验一下。
而且如果 session 不过期，token 也不应该过期的

**Comment by xyzabc0004** [comment]
好的，谢谢！我好像看到你，在别的贴子里面写的request过滤器代码了。去抄下看。
