### ISSUE TITLE
Modal mask 不能完全遮罩后面的元素

### ISSUE THREAD

**Issue by windyrain** [ant-design/ant-design-pro#4518]
![image](https://user-images.githubusercontent.com/7961364/59583052-b55e4500-910c-11e9-879e-c58d15840c9a.png)

试验了很多方法寻找红色框中的小方块。

初步定位他应该不是一个元素，有可能是::after, ::before样式渲染出来的

页面重绘这个小方块会消失。

请教一下大家看看有什么好的思路可以解决这个问题，谢谢！

**Comment by chenshuai2144** [comment]
你通过 js 找一下 zindex 最好的就可以了吧。
应该是你写了什么 css。全局搜一下 z-index 说不定也能找到

**Comment by windyrain** [comment]
> 你通过 js 找一下 zindex 最高的就可以了吧。
> 应该是你写了什么 css。全局搜一下 z-index 说不定也能找到

![image](https://user-images.githubusercontent.com/7961364/59604746-9e851600-913f-11e9-8c5f-a15402474f31.png)

![image](https://user-images.githubusercontent.com/7961364/59604765-a9d84180-913f-11e9-9a1e-b1be8b69fbb7.png)

这个不是一个具体的元素，用z-index, width, height 去匹配元素找不出来。

**Comment by windyrain** [comment]
而且这个小方块不是必现的，触发重绘后就会消失

**Comment by chenshuai2144** [comment]
有可能是你的 chrome 插件搞出来的、

**Comment by windyrain** [comment]
我自己再找找吧，issue先关闭啦。
