### ISSUE TITLE
查询表格，新建 必填和查询条件必填冲突

### ISSUE THREAD

**Issue by 693614965** [ant-design/ant-design-pro#4519]
查询表格，新建时 描述字段是必填的。但是我在查询条件里面没有输入描述，仅仅通过状态 来查询 就不行，控制台提示 描述字段必填，这个算不算bug 啊，求请教

**Comment by tnngo** [comment]
`<CreateForm {...parentMethods} modalVisible={modalVisible} form={form}/`

注意这句，框架为了简单验证，在当前组件中传递了form属性以达到统一验证的效果，你只要把 form={form} 删除掉。再在CreateForm 使用Form.Create 创建一次就可以了。
