### ISSUE TITLE
UI表达问题： 在一排按钮中，设置成primary的按钮是代表什么意思？

### ISSUE THREAD

**Issue by liuguoguo** [ant-design/ant-design-pro#4520]
在Ant Design Pro的样例页面中，经常会出现一组button，然后有一个button被设置成primary（显示蓝色），这个在企业应用UI上有什么设计原则吗？

**Comment by chenshuai2144** [comment]
primary 代表主按钮，主按钮代码主要操作，普通按钮 是次要操作。
比如表单提交的时候，提交就是主要操作，而重置就是次要操作。
