### ISSUE TITLE
Behavior differs between preview and development. (Chart Width)

### ISSUE THREAD

**Issue by erader** [ant-design/ant-design-pro#4523]
For dashboards downloaded with the umi block, the chart is drawn first when the page is loaded and then stretched to fit the page width.
This is strange.
The preview page does not have this symptom. What is the problem?
I attached a comparative image of the same page below.

![previewAntDesignPro](https://user-images.githubusercontent.com/12570499/59592379-e5b4dc00-912a-11e9-9529-dc643f050b2f.gif)
[preview]

![umiBlockAdd](https://user-images.githubusercontent.com/12570499/59592381-e8173600-912a-11e9-9f92-cd4b51cc4653.gif)
[umi block add project]

Please check.
Thank you.

**Comment by afc163** [comment]
That is because css loaded asynchronously in development, it will display in same way after build.

**Comment by erader** [comment]
> That is because css loaded asynchronously in development, it will display in same way after build.

The same symptom occurs when you test nginx after build.

**Comment by chenshuai2144** [comment]
@erader   I think this is because preview loadData is very slow. But it can be very fast in nginx, so the render is very fast.

**Comment by erader** [comment]
@chenshuai2144 
If so, is it normal to come out small at first?
How do I get my original size to show up in the first place?
Until I worked with v2, I upgraded to v4 and all of my charts do this.

**Comment by chenshuai2144** [comment]
You can increase loading. Or give a fixed width in the picture
