### ISSUE TITLE
ant design pro 2.3，登录，重定向，local storage被清空

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#4525]
各位老师，
我这边登录成功后，写local storage，代码自已一重定向，local storage的数据被清空了。
不知道怎么回事。local storage的数据被清空了，每次他回到了登录页面。
![image](https://user-images.githubusercontent.com/32530210/59594576-abe1d680-9126-11e9-810c-f56f8575867f.png)

如果把重定向代码注释掉，可以看到local storage的数据是没有清空。手动更改地址 locahost:80000/后面的访问正常。
![image](https://user-images.githubusercontent.com/32530210/59594838-3296b380-9127-11e9-8840-478a6d0f42e4.png)

还请指点下。

**Comment by xyzabc0004** [comment]
我在退出的时候，有写清除local storage
![image](https://user-images.githubusercontent.com/32530210/59597785-3decdd80-912d-11e9-95c9-d2801bb1b9f5.png)

就在重定 向的时候，也给清掉了。

**Comment by chenshuai2144** [comment]
输出一下这些方法是不是被调用了？
或者是因为你的设置 local 这些都是异步的，重定向跳转让你写入失败了。

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/59605444-654da580-9141-11e9-9642-ca3781912b1c.png)

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/59606920-d9d61380-9144-11e9-9f40-4e936016308e.png)

感觉这个'\'路由，加上这个验证，很有问题

**Comment by xyzabc0004** [comment]
我这样搞了下：
1，把这句注释掉了。不然，我只要请求没有权限的401请求都把我的storge 清空了。
![image](https://user-images.githubusercontent.com/32530210/59614407-49eb9600-9153-11e9-8caf-d938c9b08ff2.png)
2，把\根路的重路由重定向dashboard/analysis里面用到的两个API请求
http://192.168.1.131:8000/api/fake_chart_data
http://192.168.1.131:8000/api/currentUser
让这两个API不需要身从验证都可以访问。
3、登录成功后让他直接返回根（写死）
![image](https://user-images.githubusercontent.com/32530210/59614852-2117d080-9154-11e9-83e4-a6771c5e8899.png)

只是解决了下眼前的，感觉还是不完美。
我觉得还是有更好的办法。

**Comment by xyzabc0004** [comment]
感觉第一次登录的时候，没等写local storage
处理完，就跳转到了

**Comment by xyzabc0004** [comment]
https://github.com/ant-design/ant-design-pro/issues/3962#issue-431396629

用这个办法，感觉完美了！
