### ISSUE TITLE
config.ts 里修改theme没有效果

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#4527]
config.ts 里修改theme没有效果啊  比如改变 背景 'layout-body-background': '#f8f8fb',
不起作用

**Comment by xiaohuoni** [comment]
theme配置的是less变量
```js
"theme": {
  "@primary-color": "#1DA57A"
}
```

**Comment by WuJiY** [comment]
这样也不行？v2版本 直接这样'layout-body-background': '#f8f8fb', 就可以的

**Comment by zhaocz2015** [comment]
defaultSettings.ts
`  navTheme: 'dark',
  primaryColor: '#1890FF',`

**Comment by WuJiY** [comment]
这个只是primaryColor 是有效的  其他属性 https://pro.ant.design/docs/theme-cn 按照这样配置
`...
theme: {
  'font-size-base': '14px',
  'badge-font-size': '12px',
  'btn-font-size-lg': '@font-size-base',
  'menu-dark-bg': '#00182E',
  'menu-dark-submenu-bg': '#000B14',
  'layout-sider-background': '#00182E',
  'layout-body-background': '#f0f2f5',
};
...` 
有的可以有的不可以  不知道是什么原因

**Comment by chenshuai2144** [comment]
删除一下 dll 的功能试试，有可能使用了 dll 里面的内容，而不是 build 之后的 less

**Comment by WuJiY** [comment]
> 删除一下 dll 的功能试试，有可能使用了 dll 里面的内容，而不是 build 之后的 less

这样可以

**Comment by afc163** [comment]
http://github.com/ant-design/ant-design-pro-layout 要提供 less 文件，这边依赖 less 才可以改变量。

@chenshuai2144

**Comment by chenshuai2144** [comment]
https://unpkg.com/@ant-design/pro-layout@4.5.5/lib/BasicLayout.js

有的，支持过的。

**Comment by afc163** [comment]
所以还是 dll 的问题？

**Comment by chenshuai2144** [comment]
dll修复有相关issue吗？ @sorrycc

**Comment by chenshuai2144** [comment]
在 #4537 里统一跟进吧
