### ISSUE TITLE
V4 TS版登录成功又返回登录页面

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#4529]
使用V4最新TS版，登录成功后一直跳回登录页面，浏览器直接输入/可以访问主页面，请问怎么解决？

**Comment by chencs-art** [comment]
我也遇到了这个问题，请问您的解决了吗

**Comment by huang714669** [comment]
解决了，但是办法比较粗暴，在*login这个effect里面，登录成功不走routerRedux.push，直接
`window.location.href = '/'`
进去首页

**Comment by chencs-art** [comment]
哦哦，routerRedux.push(),时常出现这样的问题，重新npm run start又可以登陆进去了，好奇怪

**Comment by chencs-art** [comment]
但是，我重新清除缓存，然后在npm run start，就不行了

**Comment by xyzabc0004** [comment]
你看下，调用的API是不是返回了401的错误，调用API里面只要有一个有401的错误。
![图片](https://user-images.githubusercontent.com/32530210/59739743-6d6c2900-9298-11e9-92aa-85c02d1cb0f3.png)

这个会让回到登陆界面。

**Comment by chencs-art** [comment]
返回是200

**Comment by xaruy** [comment]
我也遇到这个问题，没有好的解决方法吗

**Comment by xyzabc0004** [comment]
你们都开始用V4 的版本了？

**Comment by keke122765** [comment]
权限的问题，因为我断点调试，它进入了Authorized.tsx文件，并重定向到了/user/login，造成了“返回登录页面”的假象

**Comment by keke122765** [comment]
已解决问题: v4版本安装的login组件:
`      if (response.status === 'ok') {
        const urlParams = new URL(window.location.href);`
缺少了:
`reloadAuthorized();`

改为:
`      if (response.status === 'ok') {
        reloadAuthorized();
        const urlParams = new URL(window.location.href);`

导致登录后没有刷新身份，从而重定向到了被Authorized.ts这个组件重定向到了/user/login。

@huang714669 的解决方案确实可以解决问题，但代价是刷新网页。

**Comment by huang714669** [comment]
@keke122765  正解，多谢！

**Comment by JackDan9** [comment]
@chenshuai2144 I think this method(add `reloadAuthorized()`) should be added to the `code repository`.  For the moment, I didn't expect any better solution.
