### ISSUE TITLE
新增组件的this.props异常

### ISSUE THREAD

**Issue by ffly1985** [ant-design/ant-design-pro#453]
新增了一个与TableList类似的组件ScriptListTable，用来管理脚本调度作业，分别添加了对应model、service、菜单等。
**菜单代码：**
`{
        name: '数据输入',
        path: 'dataInput',
        icon: 'warning',
        children: [
          {
            name: '脚本',
            path: 'script',
            component: dynamicWrapper(app, ['job'], () => import('../routes/DataInput/ScriptList')),
          },
        ],
      },`
**组件代码：**
复制了TableList的代码，只修改了类名，和调用路径,从rule/*修改为job/
**Model代码**
复制了rule.js的代码，修改了namespace，修改了fetch调用的Service。
`export default {
  namespace: 'job',

  state: {
    data: {
      list: [],
      pagination: {},
    },
    loading: true,
  },`
在新增的组件中，render函数中，this.props为什么跟TableList的prop是一样的，这个地方很不理解。如果不首先点击列表-查询列表，直接添加我所添加的新页面就会报错，点击查询-查询列表之后就不会报错了。感觉上新组件render的时候，this.props是使用了TableList的props。

使用的是最新版本的antd pro。

**Comment by afc163** [comment]
这样问问题是没用的，信息太少了，代码都在你本地，排查只能靠猜。至少你要提供可重现的代码或仓库。

**Comment by Double517** [comment]
这个没有猜错应该是你的
`@connect(state=> ({
  rule: state.rule,
}))` 没有修改导致的，连接的还是原始的吧。

**Comment by ffly1985** [comment]
是楼上所说的原因 @Double517
