### ISSUE TITLE
麻烦帮忙看下pro 2.0的gzip压缩是否有问题？

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#4530]
根据其他issue的nginx gzip配置完后，首次打开首页仍然很慢，下面是配置信息 和 一些网络请求信息，求大佬们帮忙指点以下我的配置是否有问题？

./js 去掉首次加载也慢。

![image](https://user-images.githubusercontent.com/20454290/59651758-aaafb880-91bd-11e9-8b09-747b222b707f.png)

![image](https://user-images.githubusercontent.com/20454290/59651783-ce72fe80-91bd-11e9-8820-e0f37f68b4b8.png)

![image](https://user-images.githubusercontent.com/20454290/59651786-d337b280-91bd-11e9-9784-5b3d44fa4dfe.png)

**Comment by chenshuai2144** [comment]
http://tool.chinaz.com/Gzips/
用这个工具就可以看了

**Comment by 419280377** [comment]
> http://tool.chinaz.com/Gzips/
> 用这个工具就可以看了

好的，谢谢帅哥！

**Comment by HQ1363** [comment]
> http://tool.chinaz.com/Gzips/
> 用这个工具就可以看了

非公网对外的，这个可没法看
