### ISSUE TITLE
V4 菜单请求后端接口问题

### ISSUE THREAD

**Issue by mlboy** [ant-design/ant-design-pro#4531]
v4 doc 文档已经修改了，是改变 menuDataRender 去调整订单，但是感觉文档还不是最最最新的。

能给个具体demo吗？

**Comment by zhaocz2015** [comment]
+1

**Comment by mlboy** [comment]
文档中如下代码： 不可用，因为代码中是用的 React.FunctionComponent 组件没有state状态。。
`
state = {
  menuData: [],
};

componentDidMount() {
  fetch('/api/example.json')
    .then(response => response.json())
    .then(data => {
      this.setState({
        menuData: data,
      });
    });
}

`

**Comment by afc163** [comment]
> 文档中如下代码： 不可用，因为代码中是用的 React.FunctionComponent 组件没有state状态。。

举一反三吧，例子只是引导。
