### ISSUE TITLE
分析页   访问量 横轴数据挤压在一起

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#4533]
![image](https://user-images.githubusercontent.com/11746742/59657906-ac38ab00-91d4-11e9-9edf-4ecac3d5583b.png)

**Comment by chenshuai2144** [comment]
fixed。我修改g2 的类型搞错了

**Comment by afc163** [comment]
又没关联 commit。

**Comment by chenshuai2144** [comment]
垮了仓库了。也能关联到吗？

**Comment by afc163** [comment]
当然可以：https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by chenshuai2144** [comment]
get
