### ISSUE TITLE
大佬们，这个样式问题啥时候修复，Notification样式不行，刚才又发现在BasicLayout页面加载antd的alert样式也加载不出来，刷新一下才会出来

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#4537]
感觉像是加载BasicLayout时，还没有加载到antd的相关样式导致的，大佬们排查下吧，好几天了。。。多谢～

**Comment by chenshuai2144** [comment]
先关掉 dll。最近报错这个的好多。

**Comment by afc163** [comment]
@chenshuai2144 找 @sorrycc 排查一下，这个问题反馈很多了。

**Comment by sorrycc** [comment]
@chenshuai2144 给我个明确的复现步骤，我差不多知道怎么修了。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4346
还有这个问题。

只要新建一个 pro 的区块就会出现。

**Comment by sorrycc** [comment]
给个手把手的复现步骤？

```bash
$ y create umi # 选 ant-design-pro
```

然后随便拉一个区块？拉完一个区块访问啥？正常和有问题的样子分别是怎样的？

**Comment by sorrycc** [comment]
拉了个 analysis 的区块，访问后没发现问题。

```bash
$ npx umi block add DashboardAnalysis  --path=/dashboard/analysis --npm-client=yarn
```

![image](https://user-images.githubusercontent.com/35128/59735832-ced8cb80-9289-11e9-933b-fd68c26c084d.png)

**Comment by chenshuai2144** [comment]
谈个 Notification 试试

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4527
