### ISSUE TITLE
src/global.less 失效

### ISSUE THREAD

**Issue by tangye1234** [ant-design/ant-design-pro#4538]
v4版本，在最新的 master 分支上，这个全局样式失效。

使用的代码为
commit id: 21d4f7519c3e76fa0e65c3bd929df84cfce0150c

**Comment by chenshuai2144** [comment]
需要先关闭dll，正在想办法解决

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4346
