### ISSUE TITLE
antd v4 request.ts 中的errorHandler不能觸發

### ISSUE THREAD

**Issue by hubertmok** [ant-design/ant-design-pro#4543]
參考list中的search table 模組改成自己的應用, 在後端status為200, 能正常發送資料時, table都能正常顯示, 但後端發出status為401或500時, 錯誤並沒有觸發errorHandler, request不能觸發error notification
正常應該會進入error handler執行以下代碼:
 notification.error({
    message: `请求错误 ${status}: ${url}`,
    description: errortext,
  });

**Comment by XSmarter** [comment]
这个是触发了 只是notification样式没有显示出来，可以下拉到页面最下面可以看到notification的。目前他们应该在修复吧，说现在可以先关掉 dll

**Comment by hubertmok** [comment]
因為我有嘗試在errorhandler裏面加入console.log, 當觸發errorhandler就會有訊息在console顯示, 但是卻沒有, 而頁面下方也沒有notification的提示, 所以懷疑是errorhandler沒有作用到
另以下是觸發錯誤的message
![Capture](https://user-images.githubusercontent.com/5517502/59733252-dabf9000-927f-11e9-800e-b708d8ddfd94.JPG)

**Comment by chenshuai2144** [comment]
errorhandler 只有在请求头 code 不是 200 的时候才能使用

**Comment by hubertmok** [comment]
@chenshuai2144 那個在status 200是沒有問題的, 因為不是error沒有觸發是對的, 但如上圖所示, status 401好像都沒有觸發(用search table的模組作開發)

**Comment by WuJiY** [comment]
> @chenshuai2144 那個在status 200是沒有問題的, 因為不是error沒有觸發是對的, 但如上圖所示, status 401好像都沒有觸發(用search table的模組作開發)

好像是有这个问题，捕获不到400等

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-request/pulls
来这里问一下

**Comment by babizhu** [comment]
如果你的问题没解决，请把service.ts贴上来
