### ISSUE TITLE
为什么npx umi block add (加区块）会这么慢？

### ISSUE THREAD

**Issue by holycharles** [ant-design/ant-design-pro#4547]
一直不动啊。。最后等了10多分钟上才出现
![image](https://user-images.githubusercontent.com/7654804/59748765-63552500-92ae-11e9-8de2-2c22d731e1fe.png)

网速不慢，NPM也加了镜像 ， 但不知道为什么这个操作这么慢？

**Comment by afc163** [comment]
GitHub 慢

**Comment by holycharles** [comment]
有解决的办法吗？ 除了翻墙

**Comment by li305263** [comment]
同失败..
任何npx umi block add 命令都失败..

**Comment by holycharles** [comment]
> 同失败..
> 任何npx umi block add 命令都失败..

说实话 这个功能很重要的。。不然一个一个的粘贴页面好慢

**Comment by liuyongjin** [comment]
这个命令一直报错。。。，没有成功过

**Comment by li305263** [comment]
> 这个命令一直报错。。。，没有成功过

我也是, 有个办法, 可以下载2.0的代码, 逐步拷贝过来.

**Comment by chenshuai2144** [comment]
报错的最好贴一下报错原因。这样我们就可以排查了。
最好用 npx，这样可以用最新的特性

**Comment by xland** [comment]
翻墙也慢，没一次成功的！

报错原因：@chenshuai2144
```
PS D:\project\yaui> npx umi block add UserLogin --path=/user/login
√ �  Parse url and args
× � Clone git repo from https://github.com/ant-design/pro-blocks.git
×  error     Error: Error: Command failed: git clone https://github.com/ant-design/pro-blocks.git github.com/ant-design/pro-blocks --single-branch --recurse-submo
dules -b master
Cloning into 'github.com/ant-design/pro-blocks'...
fatal: early EOF
fatal: the remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining


    at D:\project\yaui\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:320:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\project\yaui\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:39:103)
    at _throw (D:\project\yaui\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
PS D:\project\yaui>
```

**Comment by chenshuai2144** [comment]
clone 失败了，。你确定翻墙了？

**Comment by withzhaoyu** [comment]
太太太太太太慢了

**Comment by youqingxiaozhua** [comment]
> GitHub 慢

直接访问github或者git clone都很快，唯独执行这个命令慢……

**Comment by silianpan** [comment]
这问题没有解决，为什么关闭了

**Comment by xland** [comment]
@silianpan 

因为开发团队认为，这不是开发团队的问题，是使用者的问题~

**Comment by youqingxiaozhua** [comment]
@all 删除整个目录，按照这篇文章中的顺序来依次执行，完美解决（换用yarn）
https://zhuanlan.zhihu.com/p/67498559

**Comment by silianpan** [comment]
配置npm淘宝源，采用umi block list选择区块下载，不会有问题

**Comment by qxchen6** [comment]
@chenshuai2144 @afc163

**Comment by silianpan** [comment]
> @chenshuai2144 @afc163
> RPC failed 真的是网速慢的原因吗。
> 我现在也遇见了 RPC failed ，没有办法解决

区块不要一下全部下载，选择区块下载

**Comment by dsonwy** [comment]
翻墙了，第一次装到login就不动了。第二次挺快地执行到mind，然后就不动了，我开机等了24个小时，还是在mind。。。。 

![image](https://user-images.githubusercontent.com/20673336/68397772-aa38ae00-01ae-11ea-8cee-848c20996ca2.png)

**Comment by silianpan** [comment]
> 翻墙了，第一次装到login就不动了。第二次挺快地执行到mind，然后就不动了，我开机等了24个小时，还是在mind。。。。 而且没报错。。
> 
> ![image](https://user-images.githubusercontent.com/20673336/68397772-aa38ae00-01ae-11ea-8cee-848c20996ca2.png)

选择区块下载

**Comment by dsonwy** [comment]
[https://segmentfault.com/a/1190000019911077]这个办法，亲测有效。如果还是慢的话，把翻墙软件关掉试试（虽然webstorm默认不走代理，但是我下载的时候还是有影响）
