### ISSUE TITLE
umi block add 命令选项 新功能

### ISSUE THREAD

**Issue by gisfinder** [ant-design/ant-design-pro#4549]
umi block add命令执行时，当有依赖项需要下载，还都是通过cnm下载，在国内网络环境不好的情况下下载安装经常不成功。
因此请求umi block add有通过cnpm选项下载依赖项。

**Comment by chenshuai2144** [comment]
更新一下 umi 版本我们增加自动选择 npm 源的功能。会根据网络环境使用 淘宝源

**Comment by gisfinder** [comment]
更新umi到2.8， 在通过ant-design-pro脚手架创建的项目，其依赖项仍umi版本仍为2.7.2.
添加DashboardMonitor这个block时，还是用的npm安装的。 如下： 
× Install additional dependencies @types/lodash.debounce@^4.0.6,bizcharts@^3.5.3-beta.0,bizcharts-plugin-slider@^2.1.1-beta.1,lodash.debounce@^4.0.8,numeral@^2.0.6,react-fittext@^1.0.0,umi-plugin-block-dev@^1.0.0,mockjs@^1.0.1-beta3 with npm --registry https://registry.npmjs.org
×  error     Error: Error: Command failed: npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 umi-plugin-block-dev@^1.0.0 mockjs@^1.0.1-beta3 --registry=https://registry.npmjs.org --save

**Comment by z09176141** [comment]
npx umi block add  FormAdvancedForm   //不加路径，让它自动生成就可以成功
