### ISSUE TITLE
npm run fetch:blocks 只会安装一个 user/login后面都不会执行了

### ISSUE THREAD

**Issue by waylon-edmodo** [ant-design/ant-design-pro#4550]
npm run fetch:blocks#
这个脚本可以将所有的区块下载到当前项目中。你会得到与 https://preview.pro.ant.design/ 相同的界面

**Comment by waylon-edmodo** [comment]
npm run fetch:blocks 只会安装一个 user/login后面都不会执行了

**Comment by chenshuai2144** [comment]
你人工执行以下看看有什么报错？

**Comment by waylon-edmodo** [comment]
没有看明白。怎么看有没有报错。

**Comment by waylon-edmodo** [comment]
yarn create umi
>ant-design-pro
>Typescript
yarn
yarn start 
>页面正常打开
>关闭
yarn fetch:blocks
>yarn run v1.12.3
>warning ../../package.json: No license field
>$ node ./scripts/fetch-blocks.js
>install login to: /user/login
>卡住了，都不会动

**Comment by waylon-edmodo** [comment]
强行掐掉后，启动报错。
✖ Webpack
  Compiled with some errors in 8.43s

Extracted theme color css content length: 8604
 ERROR  Failed to compile with 1 errors                                                                             8:47:38 PM

This relative module was not found:

* ../list/search in ./src/pages/.umi/router.js
 WAIT  Compiling...

**Comment by waylon-edmodo** [comment]
如果使用
npx umi block add UserLogin  --path=/user/login
可以正常安装使用。

**Comment by waylon-edmodo** [comment]
但是我想安装全部。npm run fetch:blocks

**Comment by fanhualei** [comment]
比较慢，等10分钟后，就行了，别着急

**Comment by waylon-edmodo** [comment]
我电脑开机一晚上，第二天来还是停留在
install login to: /user/login

**Comment by chenshuai2144** [comment]
waylon-edmodo  fetch 会用你本地的脚本，你升级一下试试

**Comment by waylon-edmodo** [comment]
umi -v
2.8.3
已经升级到最新版本了，还是一样的。

**Comment by chenshuai2144** [comment]
你看看和这个有关吗？
https://github.com/umijs/umi/pull/2680

**Comment by waylon-edmodo** [comment]
这是要修改本地umi代码？

**Comment by chenshuai2144** [comment]
加个环境就行了。
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

**Comment by waylon-edmodo** [comment]
安装包里面没有找到这个文件 
packages/umi-build-dev/src/plugins/commands/block/util.js

是不是编译后的umi长得不一样。

**Comment by waylon-edmodo** [comment]
找到位置了。

**Comment by waylon-edmodo** [comment]
放弃了，还是一样卡住。没有任何log。

**Comment by yaoshanliang** [comment]
我也是 一直不动

**Comment by richagain** [comment]
我也是 一直不动

**Comment by chenshuai2144** [comment]
详细说明一下，如果有日志最好发一下日志

**Comment by waylon-edmodo** [comment]
就是因为没有任何日志。就卡着不动。所以完全不知道怎么回事。

**Comment by waylon-edmodo** [comment]
user/login的代码是下来了，然后一直卡着不动。

**Comment by waylon-edmodo** [comment]
把yarn换成npm也一样。

**Comment by chenshuai2144** [comment]
你人肉执行时可以的吗？

**Comment by waylon-edmodo** [comment]
嗯。一个一个安装是可以的。

**Comment by waylon-edmodo** [comment]
我就是想要一个完整的工程看一下。一个一个安装不知道怎么能装的全。

**Comment by richagain** [comment]
楼上的，只要你尝试umi block add任何区块，再执行yarn fetch:blocks就是会卡住。
如果只是想要看完整的工程，重新umi Ant Design Pro 4，然后执行yarn fetch:blocks或是npm run fetch:blocks就可以了。

**Comment by afc163** [comment]
> 楼上的，只要你尝试umi block add任何区块，再执行yarn fetch:blocks就是会卡住。

@chenshuai2144 试试

**Comment by waylon-edmodo** [comment]
npx umi block add DashboardAnalysis --path=/dashboard/analysis

用这个是可以安装并使用的。

**Comment by waylon-edmodo** [comment]
@afc163 我新建的工程呀。完全没有安装过区块。

**Comment by richagain** [comment]
现在ant design pro v4的区块，即使你一个一个加，把注册和登陆都加了，但是在主页全局的顶部的用户退出那里，找不到区块添加（至少我暂时不知道哪个区块）。不过用yarn fetch:blocks就可以拿到全局顶部的用户退出UI。

**Comment by waylon-edmodo** [comment]
> 楼上的，只要你尝试umi block add任何区块，再执行yarn fetch:blocks就是会卡住。
> 如果只是想要看完整的工程，重新umi Ant Design Pro 4，然后执行yarn fetch:blocks或是npm run fetch:blocks就可以了。

就是说 创建工程后。连yarn都不用执行。直接安装yarn fetch:blocks ?
我试试看。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/305818834d2f32eddb043978a9724749d2a1cc8a/package.json#L17

已经不会有文件夹重复的问题了，我会删除掉

>  楼上的，只要你尝试umi block add任何区块，再执行yarn fetch:blocks就是会卡住。

**Comment by richagain** [comment]
第一步：yarn create umi
第二步：选择ant-design-pro
第三步：yarn
第四步：yarn fetch:blocks

**Comment by richagain** [comment]
> 第一步：yarn create umi
> 第二步：选择ant-design-pro
> 第三步：yarn
> 第四步：yarn fetch:blocks

我下午也是弄了好几个小时，弄不好。后来看到另外个帖子说只要尝试安装任何区块，就不能fetch。后来我重头再来，按照上面的步骤，就弄好了。我也不知道怎么回事。

**Comment by waylon-edmodo** [comment]
> 第一步：yarn create umi
> 第二步：选择ant-design-pro
> 第三步：yarn
> 第四步：yarn fetch:blocks

我就是你这么操作的。卡住连。我还以为上面说的不要第三步。

**Comment by chenshuai2144** [comment]
@richagain  
修改 

```
<Avatar />
```
为
```
<Avatar menu />
```
就可以了

**Comment by richagain** [comment]
> > 第一步：yarn create umi
> > 第二步：选择ant-design-pro
> > 第三步：yarn
> > 第四步：yarn fetch:blocks
> 
> 我就是你这么操作的。卡住连。我还以为上面说的不要第三步。

那我就不知道了。我是用win10。

**Comment by richagain** [comment]
> @richagain
> 修改
> 
> ```
> <Avatar />
> ```
> 
> 为
> 
> ```
> <Avatar menu />
> ```
> 
> 就可以了

谢谢

**Comment by chenshuai2144** [comment]
win10 没有问题的，我的这个功能就是在 win10 上开发的。

**Comment by waylon-edmodo** [comment]
> win10 没有问题的，我的这个功能就是在 win10 上开发的。

我的是Mac。 我再重头来一遍试试。

**Comment by waylon-edmodo** [comment]
我怀疑是不是第三步跟第四步之间，我执行了一个 yarn start ? 我现在不执行这个试试。

**Comment by richagain** [comment]
> @richagain
> 修改
> 
> ```
> <Avatar />
> ```
> 
> 为
> 
> ```
> <Avatar menu />
> ```
> 
> 就可以了

对了，怎样去除已经添加的区块呢？

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-25 at 8 27 37 PM](https://user-images.githubusercontent.com/51694657/60098270-b257fa00-9787-11e9-8d9a-030a002b544b.png)

**Comment by waylon-edmodo** [comment]
还是卡住。

**Comment by chenshuai2144** [comment]
debug 一下脚本吧。这么难搞估计是个很低级的错误

**Comment by richagain** [comment]
你有用sudo吗？

**Comment by waylon-edmodo** [comment]
> 你有用sudo吗？

没有。这个应该不用sudo吧。我也可以试一下。

**Comment by waylon-edmodo** [comment]
搞定了。把全局的umi卸载掉就可以了。唉。坑呀。

**Comment by waylon-edmodo** [comment]
npm uninstall -g umi

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-25 at 9 36 17 PM](https://user-images.githubusercontent.com/51694657/60102961-48dce900-9791-11e9-91a1-3aa6db581db0.png)

**Comment by waylon-edmodo** [comment]
晕。这回卡在register。一晚上过去了，还在这。

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-25 at 9 36 17 PM](https://user-images.githubusercontent.com/51694657/60148920-74012000-9805-11e9-9874-4b57ac0ef543.png)

npm uninstall umi 会下载Chromium，惊呆了。

**Comment by waylon-edmodo** [comment]
我把umi降级到    "umi": "2.7.2",
终于可以了。

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-26 at 2 05 14 PM](https://user-images.githubusercontent.com/51694657/60154937-70789380-981b-11e9-9c53-3a6c7ab781f3.png)

**Comment by chenshuai2144** [comment]
一个问题开了太多了

**Comment by sentimentally** [comment]
红红火火恍恍惚惚

**Comment by haizhijiange** [comment]
遇到同样的问题试过上面的办法，没办法解决。卡在install login to: /user/login

**Comment by youqingxiaozhua** [comment]
为啥卸载global umi可以解决问题呢
