### ISSUE TITLE
路由和权限问题

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#4551]
第一次登录成功后，还是被权限机制拦截回user/login，LocalStorage已经写入[‘admin’]，再次登录可以进入其他页面。请问大佬们，v4的权限和路由有没有Demo?

**Comment by Clago** [comment]
pages/Authorized有一个isLogin值，你看下这个值，这个值会有影响。
ps:
说实话，这个权限搞得有点复杂。
我是后端开发，所以站在我的角度，感觉复杂了。因为前后分离一般都是基于token的，后端自会判断当前用的权限以及返回当前用户对应的菜单，我觉得简单点就好，或者有多种选择方案，我想要的就是判断用户有没有token就行了，现在改起来对于我这种半吊子好难，官方文档也太简单了点，希望文档能早日完善。不说了，我继续折腾了。

**Comment by keke122765** [comment]
没有人遇到这个问题吗

**Comment by keke122765** [comment]
已解决问题: v4版本安装的login组件:
if (response.status === 'ok') {
const urlParams = new URL(window.location.href);
缺少了:
reloadAuthorized();

改为:
if (response.status === 'ok') {
reloadAuthorized();
const urlParams = new URL(window.location.href);

导致登录后没有刷新身份，从而重定向到了被Authorized.ts这个组件重定向到了/user/login。

@huang714669 的解决方案确实可以解决问题，但代价是刷新网页。
