### ISSUE TITLE
各位大神请问如何实现树形表格懒加载？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#4552]
![image](https://user-images.githubusercontent.com/37643958/59816761-ec706880-934f-11e9-8404-3a143984a1b5.png)

- 如何通过点“+”按钮，异步请求后端加载展开数据？

- 通过expandedRowRender展开相当于嵌套了一个子表格，展示是有问题的，展开子节点数据有存在标题
![image](https://user-images.githubusercontent.com/37643958/59816953-918b4100-9350-11e9-80ec-86c53d49c25b.png)
![image](https://user-images.githubusercontent.com/37643958/59817031-e5962580-9350-11e9-8ebf-27ecac91812a.png)

- 各位大神能不能指教一二

**Comment by chenshuai2144** [comment]
expandedRowRender 返回的是一个 reactNode ,你可以通过自定义个组件来实现这个功能。然后在这个里面进行自定义

`expandedRowRender=()=><RowRender/>`
