### ISSUE TITLE
打包后vendors. async.js过大如何处理？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#4554]
生产环境vendors. async.js这个文件太大了，有什么解决办法可以处理的嘛？
pro版本是2.1.1 
umi版本是2.6.17 
nginx已开gzip

**Comment by zhilianbi520** [comment]
有盆友，有很好的建议嘛？

**Comment by zhilianbi520** [comment]
![18_54_35__07_09_2019](https://user-images.githubusercontent.com/16549630/60882770-2790f800-a27b-11e9-85d4-fa21c0635a7b.jpg)
这是项目的文件分析～！

**Comment by zhilianbi520** [comment]
https://github.com/ant-design/ant-design-pro/pull/3650
目前采用该方案处理～

**Comment by SongZhuhai** [comment]
vendors. async.js  這個文件的作用是什麼？
