### ISSUE TITLE
使用npm start启动项目，出现原重错误！！！

### ISSUE THREAD

**Issue by tgy3300** [ant-design/ant-design-pro#4555]
先说下我的安排过程
1、`yarn create umi myapp`
2、`cd myapp`
3、`cnpm install`，成功安排了项目依赖
4、`cnpm start`， 出错如下

` ERROR  Failed to compile with 1 errors                                 14:01:32
This dependency was not found:
* F:mywwwrootzlzl-pro-antd-project-190621
ode_modules_umi-build-dev@1.10.0@umi-build-devlibindRoute.js in ./src/pages/.um
i/umi.js

To install it, you can run: npm install --save F:mywwwrootmyapp
ode_modules_umi-build-dev@1.10.0@umi-build-devlibindRoute.js

 ERROR CODE  ERR_WEBPACK_MODULE_NOT_FOUND`

这 **`F:mywwwrootmyapp`** 是我的项目路径，怎么合在一起了

**Comment by w3cui** [comment]
同样的，我还是遇到这个问题了

**Comment by chenshuai2144** [comment]
更新一下umi  发了一个新的版本

**Comment by w3cui** [comment]
我这里把项目重新删除了 在选择开发语言的时候卡死了？

PS D:\www\dtk_react_tuiguang_user> npm create umi
? Select the boilerplate type ant-design-pro
? Which language do you want to use? (Use arrow keys)
> TypeScript
  JavaScript

PS D:\www\dtk_react_tuiguang_user> umi -v
2.8.1

PS D:\www\dtk_react_tuiguang_user> node -v
v10.16.0

系统w10

**Comment by sweetmei** [comment]
好了吗

**Comment by w3cui** [comment]
@sweetmei  无效果 我把PS D:\www\dtk_react_tuiguang_user> create-umi -v
0.13.7

**Comment by sweetmei** [comment]
## 错误原因

    1. 文件确实不存在
    2. 大小写问题

如果 mac 下构建成功，而在 linux 下或云构建平台上构建失败，则基本可断定为大小写问题。

## 解决方案

如果是大小写问题，请仔细检查 import 或 require 的文件和目标文件的大小写是否一致。


这种情况怎么解决

**Comment by plusmancn** [comment]
同样问题，手动 `npm i core-js --save`

**Comment by afc163** [comment]
umi@2.8.3 已解决，更新即可。

**Comment by tgy3300** [comment]
解决了，，在项目里npm install --save umi，把umi依赖包更新为最新版即可
