### ISSUE TITLE
Mac/Win 初始化项目失败

### ISSUE THREAD

**Issue by linchengzzz** [ant-design/ant-design-pro#4558]
1. 执行 ant-design-pro 官网 / 开始使用 / 安装 步骤
2. 在选择使用语言步骤卡死无法操作
![image](https://user-images.githubusercontent.com/24381509/59827507-7417a080-936b-11e9-9108-6a332e4cf9aa.png)
3. Mac 和 Win 都会遇到同样的问题

**Comment by chenshuai2144** [comment]
我这里速度很快。试试 yarn create

**Comment by fundon** [comment]
一样问题，Mac，选择语言卡卡卡卡卡卡！

**Comment by linchengzzz** [comment]
> 我这里速度很快。试试纱线创造

我这里不是快慢的问题, 是 直接把 Terminal 卡死了

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/59828915-a8409080-936e-11e9-88f2-d2a1310550c9.png)

**Comment by linchengzzz** [comment]
@chenshuai2144 

![image](https://user-images.githubusercontent.com/24381509/59829290-9ad7d600-936f-11e9-8e22-b4607ccb2f34.png)

和你是一样的命令，是还是会在 选择语言这里卡住，按 Ctrl + C 都没有反应，只能关闭终端

**Comment by mizhicangyue** [comment]
![image](https://user-images.githubusercontent.com/45323549/59829569-539e1500-9370-11e9-8961-4418918ab5f2.png)

我windows，卡死了，光标动都不动，回车也没用！！

**Comment by fundon** [comment]
@linchengzzz 记得杀死进程

**Comment by zhanyunzhi** [comment]
一样的问题，搞了一下午了，还是解决不了

**Comment by linchengzzz** [comment]
@fundon 

> @linchengzzz 记得杀死进程

关闭终端进程就杀死了 我用 top 查了下没问题

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/2658
大家统一在这里看
