### ISSUE TITLE
Syntax Error: SyntaxError: Bad character escape sequence 

### ISSUE THREAD

**Issue by SilvaYH** [ant-design/ant-design-pro#4561]
yarn start  
```
 error  in ./src/pages/.umi/umi.js
Syntax Error: SyntaxError: g:\公司项目\爬虫数据界面\master\ant\ant-pro-admin\elastic-ant\src\pages\.umi\umi.js: Bad character escape sequence (6:89)

  4 | import React from 'react';
  5 | import ReactDOM from 'react-dom';
 6 | import findRoute from 'g:\公司项目\爬虫数据界面\master\ant\ant-pro-admin\elastic-ant\node_modules\umi-build-dev\lib\findRoute.js';
    | 
  7 | 
  8 | 
  9 | // runtime plugins


 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

使用yarn create umi 创建的项目 yarn 安装完依赖以后  yarn start爆以上错误

**Comment by swdcode** [comment]
![image](https://user-images.githubusercontent.com/19856909/59832593-d3c77900-9376-11e9-91e6-8404c17036f1.png)
我也遇到这个问题了,安装的时候选择了typescript

**Comment by chenshuai2144** [comment]
umi 已经发布了新版本再试试

**Comment by SilvaYH** [comment]
umi 之前是2.7.7 升级到2.8.1以后 使用yarn create umi my-project 会卡在选择语言那里
当前node版本：10.16.0 
yarn版本：1.16.0

**Comment by swdcode** [comment]
我更新到2.8.1后还是那问题  
Failed to compile with 1 errors                                                                                                                                                                                              16:32:16
 error  in ./src/pages/.umi/umi.js

Syntax Error: SyntaxError: F:\sw\rc\rcpor2\src\pages\.umi\umi.js: Bad character escape sequence (6:53)

  4 | import React from 'react';
  5 | import ReactDOM from 'react-dom';
> 6 | import findRoute from 'F:\sw\rc\rcpor2\node_modules\umi-build-dev\lib\findRoute.js';
    |                                                      ^
  7 | 
  8 | 
  9 | // runtime plugins

**Comment by yfl-xdkx** [comment]
同样的问题，umi升级到2.8.1没有解决问题

**Comment by yfl-xdkx** [comment]
同样的问题，umi升级到2.8.1没有解决问题

**Comment by yfl-xdkx** [comment]
同样的问题，umi升级到2.8.1没有解决问题

**Comment by KeeepMoving** [comment]
umi升级到2.8.1没有解决问题

**Comment by KeeepMoving** [comment]
umi升级到2.8.1没有解决问题

**Comment by SilvaYH** [comment]
将 umi升级到2.8.2版本 顺便把umi-plugin-react升级到1.8.4 问题解决了
```
 "umi": "^2.8.2",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.8.4",
    "umi-request": "^1.0.7"
```

ps
那个pupupeteer 尝试了官网提到到yarn 设置环境变量， 和修改下载源  也还是很难下载下来 这个问题折腾了一天···

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/issues/2654 重装依赖，这个报错已经解决
