### ISSUE TITLE
Ant Design Pro 脚手架安装

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4563]
![image](https://user-images.githubusercontent.com/44084004/59831176-d7a5cc00-9373-11e9-91ed-3de2c504be7e.png)
 
选择语言的时候无法切换语言选择，也没有任何响应。有人遇过吗？

**Comment by w3cui** [comment]
同问 一样的选择不了

**Comment by chenshuai2144** [comment]
https://github.com/umijs/create-umi/commit/f070d838c083e1e134a752202f75e287200a37e2 

可能和这个有关，正在排查

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/2658
