### ISSUE TITLE
Any long term support plan ? we are hardly to learn new framework.

### ISSUE THREAD

**Issue by netroby** [ant-design/ant-design-pro#4564]
Any long term support plan ? we are hardly to learn new framework.
As a company. we used ant design pro to build our backend management system.
but worried with your release cycle.
you released very often . we used ant design pro v1 . and then hardly migrate to v2. 
now you release v4.
feel can not easy catch up with your release speed.

Any long term support plan.
Not too much more release  frequency. but with much stable, usability.

**Comment by zhaocz2015** [comment]
+1

**Comment by chenshuai2144** [comment]
V4 will be stable for very long time。
We will only update layout and umi
