### ISSUE TITLE
PageLoading component 缺失

### ISSUE THREAD

**Issue by tangye1234** [ant-design/ant-design-pro#4567]
https://github.com/ant-design/ant-design-pro/blob/a04eaed7ea1d4b96c1f6c88b6c35bcd01c850585/config/config.ts#L32

**Comment by zsl1549** [comment]
@tangye1234  说一下怎么解决的  import { PageLoading } from '@ant-design/pro-layout';
这个组件是没有的          "@ant-design/pro-layout": "^4.4.2",
 @chenshuai2144
