### ISSUE TITLE
如图所示，npm install 完成之后，npm start failed 是什么鬼

### ISSUE THREAD

**Issue by zhaocz2015** [ant-design/ant-design-pro#4570]
![image](https://user-images.githubusercontent.com/10446523/59890624-55b1b380-9404-11e9-9d5c-5ea6b8b3596b.png)

**Comment by xiaohuoni** [comment]
自己再装一个core-js，或者不要使用最新版本的umi

**Comment by zhaocz2015** [comment]
OK 3KS

**Comment by afc163** [comment]
最新版本 umi 应该已经修复了，升级即可。
