### ISSUE TITLE
求助，修改ant-layout-footer的背景颜色

### ISSUE THREAD

**Issue by q6413260** [ant-design/ant-design-pro#4572]
求助，我想修改ant-layout-footer的背景颜色为白色，发现直接修改public/color.css里面css貌似没有效果，想问下应该改哪个地方

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/b4392ccd684349ed8aa050ced8ee2119816f3200/src/global.less
可以在这里做修改

**Comment by q6413260** [comment]
@chenshuai
3q，已经解决
