### ISSUE TITLE
antd pro如何支持虚拟目录？

### ISSUE THREAD

**Issue by 120011676** [ant-design/ant-design-pro#4573]
如一个工程已经部署了，访问地址是http://www.a.com
现在有另一个项目做了nginx反向代理，访问路径是http://www.b.com/a
2个需要同时使用，如何才能2个能正常访问

**Comment by chenshuai2144** [comment]
这个需要做一个nginx代理就好了。
http://nginx.org/en/docs/http/ngx_http_core_module.html  
这个模块轻松就可以做到这个

**Comment by 120011676** [comment]
@chenshuai2144 有页面加载js、css路径问题，你能具体给我看看config配置吗？或详细下来；当然你能试验下更好了。
注意我的 http://www.a.com  http://www.b.com/a  都要使用、访问地址方式是默认的

**Comment by iquanzhan** [comment]
> @chenshuai2144 有页面加载js、css路径问题，你能具体给我看看config配置吗？或详细下来；当然你能试验下更好了。
> 注意我的 http://www.a.com http://www.b.com/a 都要使用、访问地址方式是默认的

我也有此需求了，问一下您的问题是否已经解决了，如果有好的解决办法，麻烦分享一下。

**Comment by Double517** [comment]
> @chenshuai2144 给我看看你已部署项目，增加一个新的nginx代理地址，主要是要有虚拟目录不同，或一个有虚拟目录，一个没有虚拟目录；你是怎么做的
> 
> @iquanzhan 他就做不到

请问这个问题解决了么，打包出来同样遇到这个问题.

**Comment by Double517** [comment]
> @chenshuai2144 给我看看你已部署项目，增加一个新的nginx代理地址，主要是要有虚拟目录不同，或一个有虚拟目录，一个没有虚拟目录；你是怎么做的
> 
> @iquanzhan 他就做不到

请问这个问题解决了么，打包出来同样遇到这个问题.

**Comment by 120011676** [comment]
@Double517 没听说，要解决
