### ISSUE TITLE
如何给官网的文档提PR

### ISSUE THREAD

**Issue by JerryMissTom** [ant-design/ant-design-pro#4575]
感觉官网的某些内容有些滞后，和项目的实际情况不符，希望有方式可以给官方文档提PR

**Comment by afc163** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/507615/59902487-e7cfb100-9430-11e9-9e70-0a45bdc1067c.png">

https://github.com/ant-design/ant-design-pro-site/
