### ISSUE TITLE
请问socket的代理怎么配置啊

### ISSUE THREAD

**Issue by sicun7** [ant-design/ant-design-pro#4577]
我的socket服务器地址是:  http://127.0.0.1:9100/chat
代码里直连是没问题的, 但是代理就不行.

代码里socket建立连接:
```
 this.socket = new SockJS('chat');
 this.stompClient = Stomp.over(this.socket);
```

config.js里配置代理是这样的:
```
'/chat/**': {
       target: 'http://127.0.0.1:9100/',
       changeOrigin: true,
       ws:true,
 },
```

请教各位大佬是怎么配置代理的

**Comment by chenshuai2144** [comment]
这样应该是就是对的。你碰上了什么问题？

**Comment by sicun7** [comment]
> 这样应该是就是对的。你碰上了什么问题？

这个websocket链接的messages的data是Opcode -1
然后一直在发 /xhr?t=1561285419783(时间戳)结尾的请求,  这个应该是心跳

不知道哪里配的不对

**Comment by sicun7** [comment]
控制台报的这种错: 
```
WebSocket connection to 'ws://localhost:8000/s9e/933/pz4sxhsa/websocket' failed: Invalid frame header
VM7302 sockjs.min.js:2 Uncaught Error: Incompatibile SockJS! Main site uses: "1.3.0", the iframe: "1.0.0".
```
感觉就是走的长轮询,  服务器端推给我的消息也能收到, 但是都是http的请求返回的.

**Comment by chenshuai2144** [comment]
使用 nginx 代理一把试试呢

**Comment by FunnyWolf** [comment]
遇到了同样的问题,再修改了
'/chat/**': {
       target: 'http://127.0.0.1:9100/',
       changeOrigin: true,
       ws:false,
 },
后重启服务,然后修改为
'/chat/**': {
       target: 'http://127.0.0.1:9100/',
       changeOrigin: true,
       ws:true,
 },再启动服务后问题临时解决,后台收到的错误码是1002,应该是协议错误,具体错误原因没有找到

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
