### ISSUE TITLE
Error: Unexpected token import when running initial server

### ISSUE THREAD

**Issue by rgilling** [ant-design/ant-design-pro#458]
Just trying to get the default installation working for ant-design-pro. 

1. Cloned GitHub repo.
2. Ran npm install.
3. Ran npm start

Get error:

```
(function (exports, require, module, __filename, __dirname) { import mockjs from 'mockjs';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

Am I missing some additional configuration? 

I did not change either of these files.

Mac OSX High Sierra, Node 8.6.0

**.roadhogrc**

```
{
  "entry": "src/index.js",
  "extraBabelPlugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    "transform-class-properties",
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }]
  ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    }
  },
  "externals": {
    "g2": "G2",
    "g-cloud": "Cloud",
    "g2-plugin-slider": "G2.Plugin.slider"
  },
  "ignoreMomentLocale": true,
  "theme": "./src/theme.js",
  "hash": true
}
```

**.roadhogrc.mock.js**

```
import mockjs from 'mockjs';
import { getRule, postRule } from './mock/rule';
import { getActivities, getNotice, getFakeList } from './mock/api';
import { getFakeChartData } from './mock/chart';
import { imgMap } from './mock/utils';
import { getProfileBasicData } from './mock/profile';
import { getProfileAdvancedData } from './mock/profile';
import { getNotices } from './mock/notices';
import { format, delay } from 'roadhog-api-doc';

// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';

// 代码中会兼容本地 service mock 以及部署站点的静态数据
const proxy = {
  // 支持值为 Object 和 Array
  'GET /api/currentUser': {
    $desc: "获取当前用户接口",
    $params: {
      pageSize: {
        desc: '分页',
        exp: 2,
      },
    },
    $body: {
      name: 'Serati Ma',
      avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png',
      userid: '00000001',
      notifyCount: 12,
    },
  },
  // GET POST 可省略
  'GET /api/users': [{
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
  }, {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
  }, {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
  }],
  'GET /api/project/notice': getNotice,
  'GET /api/activities': getActivities,
  'GET /api/rule': getRule,
  'POST /api/rule': {
    $params: {
      pageSize: {
        desc: '分页',
        exp: 2,
      },
    },
    $body: postRule,
  },
  'POST /api/forms': (req, res) => {
    res.send({ message: 'Ok' });
  },
  'GET /api/tags': mockjs.mock({
    'list|100': [{ name: '@city', 'value|1-100': 150, 'type|0-2': 1 }]
  }),
  'GET /api/fake_list': getFakeList,
  'GET /api/fake_chart_data': getFakeChartData,
  'GET /api/profile/basic': getProfileBasicData,
  'GET /api/profile/advanced': getProfileAdvancedData,
  'POST /api/login/account': (req, res) => {
    const { password, userName, type } = req.body;
    res.send({
      status: password === '888888' && userName === 'admin' ? 'ok' : 'error',
      type,
    });
  },
  'POST /api/register': (req, res) => {
    res.send({ status: 'ok' });
  },
  'GET /api/notices': getNotices,
};

export default noProxy ? {} : delay(proxy, 1000);
```

**Comment by chenshuai2144** [comment]
Can not reproduce.
You try to upgrade node

**Comment by rgilling** [comment]
I tried upgrading to 9.3.0. It still has the same error.

**Comment by chenshuai2144** [comment]
I installed with [yarn](https://yarnpkg.com/en/),
You can also try

**Comment by rgilling** [comment]
Ok no problem, I didn't resolve it, but just close the issue because I need to back that mock stuff out anyway because I'm using Firebase. It would have been nice to have the mocks running, but I'll continue without them.

**Comment by PebblerWon** [comment]
I have the same problem too;

**Comment by PebblerWon** [comment]
@nikogu 这个问题已经折磨我好几天了，请问该怎么解决啊。
相似的问题在[#234](https://github.com/ant-design/ant-design-pro/issues/294),但是说的重新安装babel依赖又是怎么一回事呢

**Comment by chenshuai2144** [comment]
@PebblerWon  你检查一下你的全局安装吧.
`npm -g outdated ` ,然后升级试试..

**Comment by PebblerWon** [comment]
@chenshuai2144  
`npm -g outdated `没有提示要更新的包啊 很困惑

**Comment by chenshuai2144** [comment]
你的环境是.... 这就奇怪了,
给我一下我模拟模拟

**Comment by PebblerWon** [comment]
`windows7 64bit`
`node 8.9.0`
`npm 5.5.1`
node已经卸载重装过了，但问题还是一样
根目录下 的` .babel.json`内容只有一个大括号，可能会有帮助。
太感谢你了。

**Comment by chenshuai2144** [comment]
全新windows安装没有问题..

**Comment by PebblerWon** [comment]
@chenshuai2144  那是我环境有问题吗？可是又是哪里的问题啊

**Comment by chenshuai2144** [comment]
报错截图一下吧. 或者远程一下你

**Comment by PebblerWon** [comment]
qq: 857606948 谢谢

**Comment by PebblerWon** [comment]
![tim 20171225102822](https://user-images.githubusercontent.com/10150276/34331061-63d95f50-e95e-11e7-8de4-d4ad8eab3210.png)

**Comment by chenshuai2144** [comment]
请不要使用 Cygwin...
按住shift右键,使用cmd来进行启动.

**Comment by chenshuai2144** [comment]
@rgilling  Does your directory have special symbols too?

**Comment by rgilling** [comment]
not really, unless you count '-' /Users/rgilling/Documents/Projects/firebase/vsc/admin-ant-browser

**Comment by chenshuai2144** [comment]
@rgilling  Sorry I thought I could solve your problem.
I still need to check again. Thank you for your reply

**Comment by huangchu** [comment]
Compiled successfully in 52.5s!

The app is running at:

  http://localhost:8000/

Note that the development build is not optimized.
To create a production build, use npm run build.

Failed to parse mock config.

Error in Unexpected token import
D:\ant\ant-design-pro-master (1)\ant-design-pro-master\mock\rule.js:1

(function (exports, require, module, __filename, __dirname) { import { getUrlPar
ams } from 'utils';
                                                              ^^^^^^
SyntaxError: Unexpected token import

**Comment by rgilling** [comment]
Is this a file loading issue, perhaps `register-babel` from Roadhog is not resolving the paths correctly on Mac OS? I was trying to debug to see what the values were but  couldn't get the breakpoints to work in VSCode. I'll do my best to try a fresh Roadhog project from src over the next few days...

**Comment by chenshuai2144** [comment]
Roadhog has been upgraded to 2.0, you can try upgrade

**Comment by majewing** [comment]
@chenshuai2144 我也遇到相同的问题，这个问题解决了吗？

**Comment by chenshuai2144** [comment]
@majewing  是因为Roadhog 不支持特殊符号 .
(){}+-这些的

**Comment by chenshuai2144** [comment]
@majewing  是因为Roadhog 不支持特殊符号 .
(){}+-这些的

**Comment by majewing** [comment]
@chenshuai2144 
Failed to parse mock config.

Error in Unexpected token import
/Users/chris/ReactProject/ant-design-pro/.roadhogrc.mock.js:1

(function (exports, require, module, __filename, __dirname) { import mockjs from 'mockjs';
                                                              ^^^^^^

SyntaxError: Unexpected token import

我的环境是macos 10.12.6 nodev8.9.3
需要安装babel环境吗，好像import语法不支持。

**Comment by chenshuai2144** [comment]
你可以试试#542
里面做了修改.这个问题windows下是因为特殊字符..
mac下还没找到

**Comment by majewing** [comment]
@chenshuai2144 感觉是不支持import语法的问题

**Comment by chenshuai2144** [comment]
看看升级版本之后把 我刚买了mac 但是用不惯...
一直也没看这个
