### ISSUE TITLE
使用npm create umi新建项目出错

### ISSUE THREAD

**Issue by xingleibinghun** [ant-design/ant-design-pro#4581]
步骤如下
1. 运行 npm create umi
2. 选择 ant-design-pro
3. 选择 JavaScript
出现报错如下

![image](https://user-images.githubusercontent.com/26743990/59917019-4c9c0300-9453-11e9-84bf-4c8d66675480.png)

尝试过 yarn，同样不行。
有人和我遇到一样的问题吗？
主要是想确定下是否是ant库的问题。

**Comment by tt38491367** [comment]
我也是这个情况 之前老版本项目现在安装依赖包也报错了

**Comment by guxiaobai** [comment]
手动执行一下命令是否成功

       git clone https://github.com/ant-design/ant-design-pro --depth=1

可能挂个代理能解决

**Comment by chenshuai2144** [comment]
> 运行 npm create umi

试着用 npx create umi

**Comment by xingleibinghun** [comment]
> 手动执行一下命令是否成功
> 
> ```
>    git clone https://github.com/ant-design/ant-design-pro --depth=1
> ```
> 
> 可能挂个代理能解决


感谢，尝试了下，手动执行命令即可。

**Comment by xingleibinghun** [comment]
> > 运行 npm create umi
> 
> 试着用 npx create umi

感谢，npx还是不行，不过已经通过手动执行git命令解决了该问题

**Comment by xingleibinghun** [comment]
> 我也是这个情况 之前老版本项目现在安装依赖包也报错了

我通过手动执行git命令已解决该问题，你可以试一下
