### ISSUE TITLE
如何正确更新项目

### ISSUE THREAD

**Issue by guxiaobai** [ant-design/ant-design-pro#4582]
通过 `create-umi` 创建项目, 执行的是下面的命令

    git clone https://github.com/ant-design/ant-design-pro --depth=1

随着项目进展或修复问题，需要

1. [ ] 如何更新到最新的master
2. [ ] 如何更新到下一个版本: 例如: `4.1`

**js/ts问题**

1. [ ]  创建的时候选择了`javascript`， 项目本身并无这个文件

**我的尝试**

    git remote add upstream  https://github.com/ant-design/ant-design-pro
    git merge upstream/master
    错误: fatal: refusing to merge unrelated histories

**Comment by chenshuai2144** [comment]
https://github.com/umijs/create-umi 
直接看源码吧。

脚手架更新之后里面的代码就完全交给你了，不会再更新了。

**Comment by guxiaobai** [comment]
这两个项目更新都比较频繁，希望项目能一直保持更新 目前好像还没有比较好的方式。
