### ISSUE TITLE
页面版权信息显示，判断逻辑错误。

### ISSUE THREAD

**Issue by totemtec** [ant-design/ant-design-pro#4585]
默认生成的项目模版里
文件：src/layouts/BasicLayout.tsx

`const footerRender: BasicLayoutProps['footerRender'] = (_, defaultDom) => {

  if (!isAntDesignPro()) {
    return defaultDom;
  }

  return (
    <>
      {defaultDom}
      ...
    </>
`

如果不是AntDesignPro网站，显示默认的版权信息。。。。
另外第二个defaultDom也不应该出现

**Comment by chenshuai2144** [comment]
这是正常的，故意显示的版权信息。
再 pro 的官网还会显示 netlify 的 logo

**Comment by totemtec** [comment]
这里建议还是提示一下，全文检索了都没找到版权字符串写在了哪里
defaultDom是加密了还是从服务器请求回来的？
看以前的教程，这块是明文

**Comment by chenshuai2144** [comment]
在layout组件中 你可以读一下我们的发布文档
