### ISSUE TITLE
switch from  UserLayout to BasicLayout after login 

### ISSUE THREAD

**Issue by BK-Soft** [ant-design/ant-design-pro#4586]
I was trying to configure the route so that once the login was successful, the user would be redirected to the dashboard within the BasicLayout. 
Is there a way to do this in Antd Pro v4?   
 

following is what I have tried :

// Routing configuration
  routes: [
    {
      path: '/',
      component: '../layouts/BasicLayout',
      Routes: ['src/pages/Authorized'],
      authority: ['admin', 'user'],
      routes: [
        {
          name: 'center',
          path: '/account/center',
          component: './account/center',
        },
        {
          path: '/',
          name: 'welcome',
          icon: 'smile',
          component: './Welcome',
        },
        {
          name: 'register',
          path: '/user/register',
          component: './user/register',
        }
      ],
    },
    {
      path: '/user/login',
      component: '../layouts/UserLayout',      
      routes: [       
        {
          name: 'login',
          path: '/user/login',
          component: './user/login',
        },
      ],
    }
  ]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4529

**Comment by scott-joe** [comment]
I think this is less about configuring your routes and more about auth kicking in when someone isn't logged in, redirecting them to the login page, then redirecting them to the dashboard when they have a valid session.

**Comment by scott-joe** [comment]
@BK-Soft https://umijs.org/guide/router.html#global-layout
