### ISSUE TITLE
全新的ts项目,很多地方爆错

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#4589]
![image](https://user-images.githubusercontent.com/44694221/59967909-f1a60100-9563-11e9-8646-7084f5b4804f.png)
![image](https://user-images.githubusercontent.com/44694221/59967912-f9fe3c00-9563-11e9-9d3d-64d73ed9babe.png)
![image](https://user-images.githubusercontent.com/44694221/59967932-2a45da80-9564-11e9-8898-921d681cb09a.png)
类型为unknown是什么原因呢

**Comment by keke122765** [comment]
node_modules里的antd文件有问题，用旧项目里的antd文件替换掉后，问题解决，奇怪的是package.json里的antd版本都是 "antd": "^3.19.1",

**Comment by keke122765** [comment]
降级到3.19.6解决了错误，但是antd升级是为了优化 TypeScript 定义

**Comment by chenshuai2144** [comment]
。。。应该是我的区块没有跟着antd的升级。而且 @types/react 也做了升级。

**Comment by afc163** [comment]
是这个问题：https://github.com/ant-design/ant-design/issues/17245
