### ISSUE TITLE
pro atnd v4 版本的权限功能失效了吗？我退出账号后，访问还是能进

### ISSUE THREAD

**Issue by tgy3300** [ant-design/ant-design-pro#4593]
pro atnd v4 版本的权限功能失效了吗？我退出账号后，访问127.0.0.1:8000还是能进入到系统里

**Comment by chenshuai2144** [comment]
pro 本地现在并没有任何逻辑。你需要什么？

**Comment by afc163** [comment]
登录注册这两个区块感觉要默认加回来。

**Comment by guxiaobai** [comment]
加回来比较好，这个大部分项目都是需要的

**Comment by xiaohuoni** [comment]
感觉都通过token判断，会不会比较符合现在大部分的开发方案？之前的角色判断，感觉不是很满足我们的项目。
举个例子，访问页面-判断token-token失效-重新登录-判断token-token有效-获取菜单-访问页面。

**Comment by pkaq** [comment]
登陆注册和远程菜单这两个最基本的功能在pro里一直是磕磕绊绊的 ， 可能跟pro的目标不符吧 所以这俩功能总是很蹩脚
