### ISSUE TITLE
表格中可编辑行处改变Provider后无法保存

### ISSUE THREAD

**Issue by HiroTang** [ant-design/ant-design-pro#4594]
https://ant.design/components/table-cn/#components-table-demo-edit-row

直接在codesandbox中打开，将Provider从table改成row，3处改动如下
1.增加
![image](https://user-images.githubusercontent.com/39959321/59974620-e8a74500-95e0-11e9-9da5-c6faa99ea5cb.png)

2.增加
![image](https://user-images.githubusercontent.com/39959321/59974635-33c15800-95e1-11e9-9df9-cbd7a47f8b9d.png)

3.注释
![image](https://user-images.githubusercontent.com/39959321/59974653-5ce1e880-95e1-11e9-8663-fe2abc12b102.png)

修改完后，编辑单元格还是可以保存的，在save方法的表单校验里能输出row
但是，将编辑列固定后(如下图)，就无法编辑保存单元格了，在save方法的表单校验里也没有输出row
![image](https://user-images.githubusercontent.com/39959321/59974690-d083f580-95e1-11e9-86a1-89ba943e0e9b.png)

在官方Demo中，加了fixed是不会有这个问题的。
请问为什么修改后加个fixed会导致这样的问题，多谢指导~

**Comment by chenshuai2144** [comment]
你这个也太hack了吧。为什么要这么做呢？

**Comment by HiroTang** [comment]
> 你这个也太hack了吧。为什么要这么做呢？

接手以前同事留下的代码，随手加个fixed才发现这个的。。。现在已经照着demo用Provider了~

**Comment by chenshuai2144** [comment]
这样写很容易出性能问题。。而且只是为了传递 form

**Comment by HiroTang** [comment]
> 这样写很容易出性能问题。。而且只是为了传递 form

学习了，谢谢~
