### ISSUE TITLE
ant design pro如何升级antd的包

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design-pro#4597]
当前ant design pro用的是 "antd": "^3.15.0",  怎么升级到最新版本

**Comment by afc163** [comment]
https://semver.npmjs.com/
https://juejin.im/post/5ad413ba6fb9a028b5485866

这样已经是最新版本了，重新安装 node_modules 即可。

如果还有问题，确保移除 yarn.lock 和 package-lock.json。

**Comment by dmdoit** [comment]
> https://semver.npmjs.com/
> https://juejin.im/post/5ad413ba6fb9a028b5485866
> 
> 这样已经是最新版本了，重新安装 node_modules 即可。
> 
> 如果还有问题，确保安装前移除 yarn.lock 和 package-lock.json。

现在antd的版本是3.19.8， 可是我的ant design pro中的antd的版本还在3.15.0， 请问升级ant design pro 中antd版本的正确方法是什么

**Comment by afc163** [comment]
重新安装 node_modules 即可。
