### ISSUE TITLE
Document local iconfont

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#46]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by chenshuai2144** [comment]
这个是否应该 antd 中做讲解.
pro 可以给一个 demo

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/10353
antd 即将支持 svg，这个就意义不打了

**Comment by afc163** [comment]
1. 用户引入自定义图标的时候还需要用到 iconfont
2. 也可以把 https://www.npmjs.com/package/dynamic-icon 作为推荐方案之一补充到自定义图标这章去。

**Comment by chenshuai2144** [comment]
使用新的 icon来实现。
