### ISSUE TITLE
ant-design-pro.2.x 如何禁止 ts ?

### ISSUE THREAD

**Issue by luo963827954** [ant-design/ant-design-pro#4600]
![image](https://user-images.githubusercontent.com/23068326/60012931-c03a4c00-96af-11e9-9a58-fef934fd4652.png)

**Comment by chenshuai2144** [comment]
删除掉 ts config 试试呢

**Comment by luo963827954** [comment]
> 删除掉 ts config 试试呢

解决不了， 会报  ts config error

**Comment by chenshuai2144** [comment]
那你拷贝一下 v4 的 ts进去吧

**Comment by luo963827954** [comment]
> 那你拷贝一下 v4 的 tsconfig 进去试试。
> 看起像像是编译的时候变异了 包里面的 ts

对啊，现在想禁止TS 编译。 没找到在哪禁止。 V4 的配置会也报错

**Comment by chenshuai2144** [comment]
tsconfig 里面配置一下
