### ISSUE TITLE
请问能出个angular版本的吗？

### ISSUE THREAD

**Issue by lichnow** [ant-design/ant-design-pro#4601]
vue有个社区版本的pro也是非常好用，然后vue的写法太奇怪了，很不好用.react的各种库太散了，redux,mox,dva,umi...一大堆,跟golang的感觉很类似,不是很习惯。由于后端转前端习惯于angular,spring,symfony这种一体化的东西，然而现在angular写后台模板都是themeforest上直接购买的，找不到angular版本的pro. zorro alian这个开源版并不是很好，而收费版使用权限限制太过，如果可以的话建议出个angular版本的pro.

**Comment by chenshuai2144** [comment]
antd 已经有了，但是 pro 暂时没有计划。如果有兴趣你可以搞一个。

**Comment by afc163** [comment]
可以看看 https://github.com/repertory/ng-antd-admin

**Comment by lichnow** [comment]
@afc16 这个太简陋了，vue版的倒是挺完善的
