### ISSUE TITLE
v4.0如何能及时更新github上的最新代码

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4602]
v2.0就很方便，因为构建工程的时候，使用了git clone，所以直接使用git命令，就能更新服务器最新的代码。

假设我使用typescript

1：我怎么使用git得到最新的主干代码
2:  我怎么使用git得到最新的demo的代码

现在感觉antDesignPro从js切换到tc，也很纠结。

**Comment by fanhualei** [comment]
主要是我开发了一段时间后，发现antDesignPro更新了，我怎么使用git命令merge到主干的代码，以前在V2.0就很方便。

**Comment by chenshuai2144** [comment]
check 一下 commit 好了。暂时好像没有好的方案。但是大部分更新你可以无缝获得。Layout 和 umi 的更新对用户比较重要

**Comment by guxiaobai** [comment]
`git clone https://github.com/umijs/ant-design-pro --depth=1`

1. [x]  然后把代码复制到项目下对比差异，手工处理(1897 -1903) 30分钟可以处理完成
2. [ ] 制作一份官方忽略文件列表(`.md`)等文件,在复制环节过滤一部分文件
3. [ ] 制作一份自己项目忽略文件列表() 过滤一部分文件
4. [ ] 少部分文件手工处理
6. [ ] create-umi 部分处理
5. [ ] 封装一个命令

**Comment by guxiaobai** [comment]
`git clone https://github.com/umijs/ant-design-pro --depth=1`

**目录结构**

ant-design-pro
my-project

**同步ts/tsx文件(mac)**

1. `cd ant-design-pro`
2. `find . -name '*.tsx' -print0 | rsync -av --files-from=- --from0 ./ ../my-project`
3. `find .  -name '*.ts' -print0  | rsync -av --files-from=- --from0 ./ ../my-project`

**同步 ts/tsx文件(linux)**

1. `cd ant-design-pro`
2. `find .  -name '*.tsx'  -exec cp -r --parents {} ../my-project \;`

**package.json 暂未处理**

**Comment by fanhualei** [comment]
https://pro.ant.design/docs/faq-cn

官方文档这么写的，不知道好用不

**如何更新 Ant Design Pro？#**

- 单独升级 antd 版本，用于更新基础组件。
- 比较不同的 Ant Design Pro 版本间的差异，手动修改本地配置。
- 也可以尝试合并远程分支：git pull https://github.com/ant-design/ant-design-pro（注意，需要自行解决冲突）。
- 直接在 GitHub 上拷贝最新的典型模板。

**Comment by fanhualei** [comment]
如何更新 Ant Design Pro？  按照官方的文档描述的不好用

**Comment by fanhualei** [comment]
我看了一下 create umi的源代码，在执行完毕后，删除了git目录。 

1：为什么在发部分v4.0时，在master分支上就给出一个干净的环境呢？除了readme保留下来，其他的没用的可以删除了。
2：或者新建一个合并的master分支的scriipt。


create umi：步骤

1：git clone 下载代码

2：修改了`package.json`中的`verson scripts devDepenDencies`

3：删除了一些没有用的文件

> 以上信息记录在了 `package.json`中，如下：

```json
"create-umi": {
  "ignoreScript": [
    "docker*",
    "functions*",
    "site",
    "generateMock"
  ],
  "ignoreDependencies": [
    "netlify*",
    "serverless",
    "express"
  ],
  "ignore": [
    ".dockerignore",
    ".git",
    ".gitpod.yml",
    "CODE_OF_CONDUCT.md",
    "Dockerfile",
    "Dockerfile.*",
    "lambda",
    "LICENSE",
    "netlify.toml",
    "README.*.md",
    "azure-pipelines.yml",
    "docker",
    "create-umi"
  ]
}

```

**Comment by guxiaobai** [comment]
在记一下，最好每天/3天 执行一下, 解决一下因为依赖解决/修复的问题，可以及时发现

* `rm -rf node_modules`
* `yarn install`

**Comment by fanhualei** [comment]
按照v2.0的更新情况，4个月后，这些小问题能解决。 但是2.0时很方便meger到最新的代码。 现在在手工来处理。
