### ISSUE TITLE
v4 在microsoft edge 瀏覽器無法取得本地端cookie

### ISSUE THREAD

**Issue by hubertmok** [ant-design/ant-design-pro#4603]
利用cookie作為權限認證, 在login時, 後端會發送cookie在本地端儲存, 在之後的每次請求都會在request header中帶上此cookie. 在google chrome瀏覽器中是沒有問題, 但在edge瀏覽器中卻無法在request header中附上
圖為在google chrome login時, 後端發送前端cookie, set-cookie欄位
![Capture](https://user-images.githubusercontent.com/5517502/60064045-c244ef00-9731-11e9-83ab-43c806b65df2.JPG)
圖為在google chrome login後, 每次請求都會帶上該段cookie, 但在edge瀏覽器中卻無法
![Capture1](https://user-images.githubusercontent.com/5517502/60064138-0f28c580-9732-11e9-98da-5a0d4cab0428.JPG)

**Comment by afc163** [comment]
一个是 Response Headers 一个是 Request Headers，确定没有截错图？

**Comment by hubertmok** [comment]
response header 是login時, 後端返回的資訊, 下面的request header是login後, 前端向後端發出請求的資訊, 因為在login時, 後端返回的cookie有在本地端儲存, 正常來說, 應該會在隨後的每次請求都帶上, 以作權限檢查, 上面的兩張是google chrome執行時情況, 在chrome上是沒有問題的, 但microsoft edge瀏覽器卻無法在request header中加入login時返回的cookie, 在antd v2沒有這個問題, v4才出現的

**Comment by chenshuai2144** [comment]
你找到问题了吗？

**Comment by hubertmok** [comment]
@chenshuai2144 暫時還未解決, 還在找

**Comment by kzabc** [comment]
请问如何获取response.headers

**Comment by Zhaojing0987** [comment]
fetch里拿不到response.headers，请问有解决方法了吗？ @chenshuai2144
