### ISSUE TITLE
setAuthority设置权限后，侧边栏没有进行相对应的渲染需要二次刷新才会渲染正确，求解

### ISSUE THREAD

**Issue by Duanruilong** [ant-design/ant-design-pro#4604]
effects等待接口返回相对的权限之后，去更新权限

`
setAuthority(‘TEACHER’);
 reloadAuthorized();
`
每次退出重新登录左边侧边栏权限配置还是上一个权限的栏目。
只有重新刷新才会渲染正确

**Comment by Duanruilong** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
刷新一下 layout 即可。你是用的新版本吗？

**Comment by Duanruilong** [comment]
我们用的不是新版本，刷新layout 直接刷新页面吗，还是有其他的刷新机制

**Comment by Duanruilong** [comment]
BasicLayout文件里直接刷新 layout 组件？

**Comment by Duanruilong** [comment]
renderAuthorize.js 文件里的currentAuthority参数在接口获取到权限之后的值 已经发生改变了，但是没有进行 通用权限检查方法（ checkPermissions ）
@

**Comment by Duanruilong** [comment]
再触发一次
`
dispatch({
       type: 'menu/getMenuData',
      payload: {
           routes,
             path,
             authority
          },
       });

`

**Comment by bobosbenben** [comment]
用的是V4版本，如何刷新layout

**Comment by codeXian** [comment]
> 再触发一次
> `
> dispatch({
> type: 'menu/getMenuData',
> payload: {
> routes,
> path,
> authority
> },
> });
> 
> `
哪里写这句话？求大神解惑

**Comment by codeXian** [comment]
@Duanruilong
