### ISSUE TITLE
blocks安装不上

### ISSUE THREAD

**Issue by yaoshanliang** [ant-design/ant-design-pro#4605]
cnpm run fetch:blocks一直请求中，试了好多遍都安装不了

**Comment by afc163** [comment]
看一下完整 log。

**Comment by yaoshanliang** [comment]
没有log 一直等待中

![image](https://user-images.githubusercontent.com/5028569/60076813-13b5a400-975b-11e9-943e-63f4fd65c8a3.png)

**Comment by afc163** [comment]
看上去还是网络问题。

**Comment by waylon-edmodo** [comment]
哎呀，你的问题好像跟我是一样的。跟网络没有关系。我至今没找到原因

**Comment by waylon-edmodo** [comment]
https://github.com/ant-design/ant-design-pro/issues/4550
