### ISSUE TITLE
bug!pro演示站分步表单第三步不显示

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#4606]
https://preview.pro.ant.design/form/step-form
![Capture](https://user-images.githubusercontent.com/44694221/60078343-575ddd00-975e-11e9-98a2-be8d97e391f0.JPG)

**Comment by keke122765** [comment]
https://github.com/ant-design/pro-blocks/blob/master/FormStepForm/src/components/Step3/index.tsx

line 17

return null; 背锅

**Comment by keke122765** [comment]
export default connect .... 没写导致data为空

**Comment by chenshuai2144** [comment]
来一把 pr？

**Comment by keke122765** [comment]
提交了
