### ISSUE TITLE
添加菜单跳转到外部地址失败V4

### ISSUE THREAD

**Issue by xingcun** [ant-design/ant-design-pro#4607]
```
{
  path: '/',
  component: '../layouts/BasicLayout',
  Routes: [
    'src/pages/Authorized'
  ],
  authority: [
    'admin',
    'user'
  ],
  routes: [
    {
      path: '/',
      name: 'welcome',
      icon: 'smile',
      component: './Welcome',
      
    },
    {
      path: 'http://127.0.0.1:8848/nacos', //此处添加失败
      target: '_blank',
      icon: 'smile',
      name: "nacos",
      
    },
    
  ]
}
```
### 错误信息
```
index.js:1 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by BaseMenu)
    in a (created by Link)
    in Link (created by BaseMenu)
```

**Comment by chenshuai2144** [comment]
这是个 warning 因为规范中 a 里面是不能包含 a 的。真正的错误信息不是这个。你看看你渲染出来的 dom

**Comment by xingcun** [comment]
```
<li class="ant-menu-item" role="menuitem" style="padding-left: 24px;">
        <a href="/http://127.0.0.1:8848/nacos">
               <a href="http://127.0.0.1:8848/nacos" target="_blank"><span>nacos</span></a>
        </a>
</li>
```

**Comment by xingcun** [comment]
> 这是个 warning 因为规范中 a 里面是不能包含 a 的。真正的错误信息不是这个。你看看你渲染出来的 dom

```
<li class="ant-menu-item" role="menuitem" style="padding-left: 24px;">
        <a href="/http://127.0.0.1:8848/nacos">
               <a href="http://127.0.0.1:8848/nacos" target="_blank"><span>nacos</span></a>
        </a>
</li>
```

**Comment by chenshuai2144** [comment]
这样看起来时没有问题的吧。出错是指无法跳转吗？

**Comment by xingcun** [comment]
> 这样看起来时没有问题的吧。出错是指无法跳转吗？

对！
问题找到了，是BasicLayout--->menuItemRender组装的时候出错，使用link没跳转

**Comment by chenshuai2144** [comment]
我包装 Link 的原因是吗？

**Comment by xingcun** [comment]
> 我包装 Link 的原因是吗？

对的，加上判断条件，不走link即可

**Comment by xoptimal** [comment]
同样的问题 
```
const menuDataRender = menuList =>
  menuList.map(item => {
    const localItem = { ...item, children: item.children ? menuDataRender(item.children) : [] };
    return Authorized.check(item.authority, localItem, null);
  });


config: 
```
 routes: [
    {
      path: '/home',
      name: '首页',
      icon: 'smile',
      component: './home',
    },
    {
      path: '/',
      component: '../layouts/BasicLayout',
      Routes: ['src/pages/Authorized'],
      authority: ['admin', 'user'],
      routes: [
        {
          path: '/',
          redirect: '/home',
        },
        {
          name: 'exception-403',
          path: '/exception/403',
          component: './exception-403',
          icon: 'smile',
        },
        {
          name: 'exception-404',
          path: '/exception/404',
          component: './exception-404',
          icon: 'smile',
        },
        {
          name: 'exception-500',
          path: '/exception/500',
          component: './exception-500',
          icon: 'smile',
        },
      ],
    },
    {
      component: './404',
    },
  ],
```

结果渲染的时候, 
```
index.js:1 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by BaseMenu)
    in a (created by Link)
    in Link (created by BaseMenu)
```


```

**Comment by xoptimal** [comment]
默认选中了所有, 自动嵌套了 <a><a></a></a>  ...  @chenshuai2144
