### ISSUE TITLE
umi block add 有几个问题，希望大佬解答

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4608]
![image](https://user-images.githubusercontent.com/51696361/60084357-ef14f880-9769-11e9-9ca7-4f0d684398cd.png)
![image](https://user-images.githubusercontent.com/51696361/60084395-02c05f00-976a-11e9-86cc-c680653d46b5.png)
1、可以将 demo1 和 demo2的页面配置成 demo 的子路由吗？
2、block 如果使用 dva 对应的model 和 service应该是什么结构呢？
3、图二红框的目录是多余的吗？可不可以删除？
谢谢~

**Comment by Benpaodejiezai** [comment]
公司想做“中台”，要把业务模块单独提出，然后根据项目按需添加，有什么可行的办法吗

**Comment by guxiaobai** [comment]
### 回答你的问题

1.  可以
2. 参考： https://github.com/ant-design/pro-blocks/tree/master/UserLogin/src
3. 可以删除: 配置式路由与目录结构无关

https://umijs.org/zh/guide/block.html
1. `区块是指页面级别的可复用的代码`

具体看你业务规模吧: https://github.com/ant-design/pro-blocks/tree/master/ListBasicList 这个也有不少功能

**Comment by Benpaodejiezai** [comment]
> ### 回答你的问题
> 1. 可以
> 2. 参考： https://github.com/ant-design/pro-blocks/tree/master/UserLogin/src
> 3. 可以删除: 配置式路由与目录结构无关
> 
> https://umijs.org/zh/guide/block.html
> 
> 1. `区块是指页面级别的可复用的代码`
> 
> 具体看你业务规模吧: https://github.com/ant-design/pro-blocks/tree/master/ListBasicList 这个也有不少功能

大佬，图二红框的文件夹 怎么去掉呢？我添加官方的 block 是没有的，在哪配置吗？
