### ISSUE TITLE
在我们的预览网站中，你可以通过点击右下角的“添加到项目中”获取对应页面的命令内容。

### ISSUE THREAD

**Issue by aizhimin** [ant-design/ant-design-pro#4611]
文档中说的，我在预览网站根本没有添加到项目中的按钮啊。？

**Comment by guxiaobai** [comment]
https://preview.pro.ant.design/
右下角 有一个 下载的图标，点击之后有一个命令复制回来即可

**Comment by aizhimin** [comment]
> https://preview.pro.ant.design/
> 右下角 有一个 下载的图标，点击之后有一个命令复制回来即可

网页的右下角？右下角什么都没有啊？

[](url)

**Comment by chenshuai2144** [comment]
试着换个浏览器或者在控制台关掉 pwa

**Comment by aizhimin** [comment]
> 试着换个浏览器或者在控制台关掉 pwa

我用的是chrome浏览器。用其他浏览器可以。不应该不兼容chrome呀？

**Comment by chenshuai2144** [comment]
@aizhimin  是 pwa 的原因。你可以多访问几次 pro。过一些时间就会关掉 pwa 了
