### ISSUE TITLE
v4.0版本，在config.js中配置代理后，响应的Header总是为空。

### ISSUE THREAD

**Issue by zhuobeikeji** [ant-design/ant-design-pro#4612]
![image](https://user-images.githubusercontent.com/24873702/60106394-bdb32180-9797-11e9-9ed8-f67064dda78b.png)
配置后，请求可以发送到远端服务器，可是远端服务器响应报文中的Header接收过来后一直为空，用nginx代理则无此问题。跪求如何解决？
![image](https://user-images.githubusercontent.com/24873702/60106631-226e7c00-9798-11e9-8eff-ab38c3ae5092.png)
下面是服务端响应的报文：
![image](https://user-images.githubusercontent.com/24873702/60106726-45992b80-9798-11e9-983f-aa17cee0cef8.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4778
