### ISSUE TITLE
趋势图表页无法正确显示

### ISSUE THREAD

**Issue by lichnow** [ant-design/ant-design-pro#4613]
使用`npm run fetch:blocks`命令安装所有包后,图表趋势页无法正确显示,如图:
![](http://static.phpna.com/images/20190626090612.png)
而自己手动添加的block能正确
![](http://static.phpna.com/images/20190626090851.png)

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/pro-blocks/commit/f7f2f475b6a3d0e3423f513828c64aac00387568
