### ISSUE TITLE
组件connect里订阅了全局的Model的数据, 但是全局model数据更新后, 组件props却接收不到最新的数据

### ISSUE THREAD

**Issue by sicun7** [ant-design/ant-design-pro#4614]

**Comment by chenshuai2144** [comment]
你是不是加了什么额外的配置，比如 PureComponent

**Comment by sicun7** [comment]
> 你是不是加了什么额外的配置，比如 PureComponent

没有哦, 都是Component. 
我是聊天应用,  接收到新的消息后存储在全局Model里, 然后组件里connect订阅了这个全局Model,  但是组件里不能实时拿到数据.   必须组件里触发一个更新state的操作,  最新的props才会渲染出来.

**Comment by chenshuai2144** [comment]
看一下你的代码。
getDerivedStateFromProps 中输出一下，看看 props 改动触发了没有

**Comment by sicun7** [comment]
> 看一下你的代码。
> getDerivedStateFromProps 中输出一下，看看 props 改动触发了没有

我试了console看执行顺序,
组件的getDerivedStateFromProps 接收到了最新的数据,  有一点很奇怪, model里reducers更新状态的代码 是在getDerivedStateFromProps触发之后执行的
我理解的是model的reducers了更新了state之后,  getDerivedStateFromProps才会拿到最新的state吧, 现在reducers都没执行, getDerivedStateFromProps都拿到最新数据了

**Comment by chenshuai2144** [comment]
reducers 可能回滚了数据或者执行了两次

**Comment by afc163** [comment]
给重现，不要互相猜来猜去。

**Comment by sicun7** [comment]
> reducers 可能回滚了数据或者执行了两次

model代码:
`
import {msgType} from '../socket/config';

export default {
  namespace: 'gwarroom',

  state: {
    users: [],
    onlineUsers: [],
    offlineUsers: [],

    gsocket: {},
    // 作战室消息
    warRoomMsgMap:{},
    // 订阅过的eventId集合
    socketWarroomIds: [],
    // 事件列表
    eventList: [],
  },

  effects: {
    
  },

  reducers: {

    setUsersData(state, action) {
      return {
        ...state,
        users: action.payload || []
      };
    },

    setGlobalSocket(state, action){
      return {
        ...state, gsocket : action.payload
      }
    },

    setSocketWarroomIds(state, action){
      return {
        ...state, socketWarroomIds: action.payload
      }
    },

    parseWarroomMessage(state, action){
      console.log('Reducers', action);
      const {payload} = action;
      switch(payload.type){
        case msgType.USER_ONLINE_LIST:{
            const onlineIds = payload.userList || [];
            const onlineUsers =[];
            const offlineUsers = [];
            const {users} = state;
            users.forEach(user => {
                if(onlineIds.indexOf(user.id) === -1){
                  offlineUsers.push({onlineStatus:'OFF',...user})
                }else{
                  onlineUsers.push({onlineStatus:'ON',...user})
                }
            })
            return {
              ...state, onlineUsers, offlineUsers
            }
        }
        case msgType.WARROOM_MSG:{
            const {warRoomMsgMap} = state;
            let currentWarroomIdMsgs = warRoomMsgMap[payload.warroomId] || [];
            currentWarroomIdMsgs = currentWarroomIdMsgs.concat(payload.msgList)
            warRoomMsgMap[action.payload.warroomId] = currentWarroomIdMsgs;
            return {
              ...state, warRoomMsgMap
            }
        }
        case msgType.EVENT_LIST:{
            let {eventList} = payload;
            eventList = eventList.map(e => {
              e.warroomId = e.id;
              return e;
            });
            return {
              ...state, eventList: state.eventList.concat(eventList),
            }
        }
        default:
          return {...state};
      }
    }
    
  },
};

`

组件:
`
@connect(({ global, gwarroom,user}) => ({
    global,
    currentUser: user.currentUser,
    onlineUsers: gwarroom.onlineUsers,
    offlineUsers: gwarroom.offlineUsers,
    gsocket: gwarroom.gsocket,
    warRoomMsgMap: gwarroom.warRoomMsgMap,
    socketWarroomIds: gwarroom.socketWarroomIds,
    eventList: gwarroom.eventList,
    users: user.users
}))
class WarRoom extends Component {
  static getDerivedStateFromProps(nextProps, prevState){
   //这里打印的数据每次都是最新的, 并且这里比reducers执行的还早
    console.log('TEST', nextProps, prevState);
    return prevState;
  }
      ...
    render() {
            const {warRoomMsgMap} = this.props;
            ...
    }
}
`

问题就是:  warRoomMsgMap 这个数据render里拿到的都是旧的

**Comment by sicun7** [comment]
找到原因了

reducers里这里  
const {warRoomMsgMap} = state;
这里应该用深拷贝就没这个问题了
