### ISSUE TITLE
SSO单点登录集成

### ISSUE THREAD

**Issue by Alan666156** [ant-design/ant-design-pro#4615]
您好，我这边后台使用的springboot，前端代码部署在nginx中，集成SSO过程如果前端和后端分别部署在不同的服务器会出现跨域问题；导致单点登录成功后，不断的重定向。前端和后端部署在同一服务器就没有这个问题。请问这块怎么解决？

**Comment by chenshuai2144** [comment]
你需要代理。
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

**Comment by Alan666156** [comment]
目前是用的nginx反向代理

**Comment by Alan666156** [comment]
location /integral-web/ {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
                add_header 'Access-Control-Allow-Credentials' true;
               proxy_pass http://10.100.200.140:8080/integral-web/;
        }

**Comment by Alan666156** [comment]
server {
        listen       8001;
        server_name  10.100.200.1;

        #charset koi8-r;

        access_log  /data/nginx/logs/access8001.log  main;

        location / {
                add_header 'Access-Control-Allow-Origin' '*' ;
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,web-token,app-token,Authorization,Accept,Origin,Keep-Alive,User-Agent,X-Mx-ReqToken,X-Data-Type,X-Auth-Token,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #       add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        #       if ($request_method = 'OPTIONS') {
        #       add_header 'Access-Control-Max-Age' 1728000;
        #       add_header 'Content-Type' 'text/plain; charset=utf-8';
        #       add_header 'Content-Length' 0;
        #       return 204;
        #       }
                try_files $uri $uri/ /index.html last;
                root /data/integral-admin/;
                index index.html index.htm;
        }

        location /integral-web/ {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
                add_header 'Access-Control-Allow-Credentials' true;
               proxy_pass http://10.100.200.140:8080/integral-web/;
        }

        location /integral-job/ {
               proxy_pass http://10.100.200.140:8081/integral-job/;
        }

}

**Comment by Alan666156** [comment]
前台和后台都走nginx，入口都在一个ip就没有跨域的问题了。一开始我只是前台走nginx，后台没有走nginx，部署在不同服务器，前端请求nginx所以会出现跨域问题。入口统一就可以解决了
