### ISSUE TITLE
immutable.js的使用以及相关性能优化的建议

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design-pro#462]
建议使用immutable，可以优化下性能.
* 减少内存消耗
* 对deep compare使用immutable.is方法进行比较
* 继承自pureComponent的组件，**如果props传入复杂对象**，建议必须实现shouldComponentUpdate方法，并且使用immutable的is方法做比较  
 
另外就是，由于目前react未对stateless functional做任何性能上的优化，目前阶段是否建议使用stateless functional组件？现在的情况就是，stateless functional组件一旦props变更，一定会rerender。

**Comment by chenshuai2144** [comment]
性能优化是整个框架上的事情了..
过早的优化性能并不是好事.
immutable.js会带来更高的学习成本的.
或许应该dva来做这件事..
@connect 时实现一个简单的shouldComponentUpdate

**Comment by WhatAKitty** [comment]
dva不应该做这个事情。shouldComponentUpdate我觉得在构建的时候就该考虑上了，不然到时候完成后一个个改过去太痛苦。

**Comment by chenshuai2144** [comment]
理论上props 都来自connect.让connect 对比更加方便吧

**Comment by WhatAKitty** [comment]
`@connect时实现一个简单的shouldComponentUpdate`
这个不需要，简单的浅比较，可以通过集成PureComponent来实现。
主要产生的问题是在传入复杂对象的时候，PureComponent无法做到深层次比较。所以，才会提出通过immutable来对复杂对象作比较判断组件是否需要rerender。

**Comment by chenshuai2144** [comment]
好吧.. 我个人不建议现在就开始优化性能. 现在应该增加更多的新功能

**Comment by WhatAKitty** [comment]
这个只是一个问题，还有就是stateless functional组件的使用。这玩意现在facebook官方未对他做任何优化型处理，说是留待以后，那我们在用的时候是否建议使用这个stateless functional组件

**Comment by chenshuai2144** [comment]
我一直觉得好读比性能要重要一点.
我一直在用.
稍微注意一下就不会造成多大的问题的

**Comment by WhatAKitty** [comment]
这个就需要对开发人员的要求比较高了

**Comment by chenshuai2144** [comment]
>  这个就需要对开发人员的要求比较高了
没事的.. 大部分项目一年也活不到.真到了需要优化这东西的是否. 业务已经很大了. 重构吧

**Comment by kunhour** [comment]
目前阶段不适合过多考虑性能，性能问题建议还是交给框架去做

**Comment by AsceticBoy** [comment]
Immutable这个我觉得去交给业务开发人员去做比较好，应用的复杂度取决于实际的业务情况，毕竟过早的考虑性能问题有些得不偿失，相对来说这个阶段可维护性会更重要吧
