### ISSUE TITLE
v4版本面包屑如何实现？

### ISSUE THREAD

**Issue by yaeSakuras** [ant-design/ant-design-pro#4620]
v2版本和v4版本有很大区别，但是官方文档说明模糊。
希望完善一下文档
![image](https://user-images.githubusercontent.com/7360502/60148999-c5111400-9805-11e9-9835-bd6fc6133bf4.png)
还有这里
![image](https://user-images.githubusercontent.com/7360502/60149085-0d303680-9806-11e9-8ba3-89c917693160.png)
这部分代码是V2实现方案
但是v4是一个函数组件，无法使用v2的`getContext()`方法。
![image](https://user-images.githubusercontent.com/7360502/60149100-20430680-9806-11e9-96db-331b2a56eb0f.png)

希望说明一下实现思路，看文档对比代码让人很懵。希望完善代码的同时也能完善文档。

**Comment by afc163** [comment]
文档又漏了 @chenshuai2144 @zombieJ

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/router-and-nav-cn#%E5%9F%BA%E6%9C%AC%E7%BB%93%E6%9E%84

看看这个
