### ISSUE TITLE
top_menu下，如何修改top nav header的背景颜色？

### ISSUE THREAD

**Issue by wangjian1230** [ant-design/ant-design-pro#4621]
top_menu下，top nav header的background-color默认是白色，想修改一下

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis?language=zh-CN&layout=topmenu&contentWidth=Fixed

default is dark

**Comment by wangjian1230** [comment]
theme 设置为 light 时候，默认是白色，想修改一下这里

**Comment by chenshuai2144** [comment]
额。设置成 light 改成黑色是为什么？

**Comment by wangjian1230** [comment]
不是黑色，navTheme在light的时候，默认top nav header的背景色是白色，觉得太素了，想改成淡灰色

**Comment by afc163** [comment]
覆盖 `@pro-header-bg` 变量即可：https://github.com/ant-design/ant-design-pro-layout/blob/6ab074c425cb9c951fee1917d572e36b5051ca89/src/GlobalHeader/index.less#L12

**Comment by cuijiudai** [comment]
```
  lessLoader: {
    modifyVars: {
      '@pro-header-bg': '#ff0000',
    },
  },
```

@afc163 config.ts添加 上面那段不生效。
