### ISSUE TITLE
dva中间件使用

### ISSUE THREAD

**Issue by wakeupSu** [ant-design/ant-design-pro#4623]
想使用redux的中间件，之前都是在dva初始化的时候插入，但是v4版本只在 src/page/.umi/dva.js中找到dva的初始化，但是umi的官方文档说'.umi'是dev 临时目录，不建议修改。那么redux的中间件要在什么位置插入

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/guide/app-structure.html#src-app-js-ts
我觉得你需要它
