### ISSUE TITLE
hi while commiting my changes to git i got this error , 1 error and 0 warnings potentially fixable with the `--fix` option.

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#4624]
how i have to run the script to fix it  automatically with --fix , please let me know

**Comment by chenshuai2144** [comment]
you can use `yarn lint:fix`

**Comment by THARAKS** [comment]
ok thanks can you please provide more explanation on these scripts like each script is doing what job
i could not find any reference for your scripts 

"start:no-mock": "cross-env MOCK=none umi dev",

    "build": "umi build",

    "site": "npm run presite && cross-env APP_TYPE=site npm run build && firebase deploy && npm run docker:push",

    "analyze": "cross-env ANALYZE=1 umi build",

    "lint:style": "stylelint \"src/**/*.less\" --syntax less",

    "lint:prettier": "check-prettier lint",

    "lint": "eslint --ext .js src mock tests && npm run lint:style && npm run lint:prettier",

    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",

    "lint-staged": "lint-staged",

    "lint-staged:js": "eslint --ext .js",

    "tslint": "npm run tslint:fix",

    "tslint:fix": "tslint --fix 'src/**/*.ts*'",

    "test": "umi test",

    "test:component": "umi test ./src/components",

    "test:all": "node ./tests/run-tests.js",

    "prettier": "node ./scripts/prettier.js",

    "docker:dev": "docker-compose -f ./docker/docker-compose.dev.yml up",

    "docker:build": "docker-compose -f ./docker/docker-compose.dev.yml build",

    "docker-prod:dev": "docker-compose -f ./docker/docker-compose.yml up",

    "docker-prod:build": "docker-compose -f ./docker/docker-compose.yml build",

    "docker-prod:deploy": "umi build && docker build  -f Dockerfile.hub -t  zaoui ./",

    "docker-hub:build": "docker build  -f Dockerfile.hub -t  zaoui ./",

    "docker:tag": "docker tag zaoui zaoui",

    "docker:push

**Comment by chenshuai2144** [comment]
```

"docker:dev": "docker-compose -f ./docker/docker-compose.dev.yml up",

"docker:build": "docker-compose -f ./docker/docker-compose.dev.yml build",

"docker-prod:dev": "docker-compose -f ./docker/docker-compose.yml up",

"docker-prod:build": "docker-compose -f ./docker/docker-compose.yml build",

"docker-prod:deploy": "umi build && docker build  -f Dockerfile.hub -t  zaoui ./",

"docker-hub:build": "docker build  -f Dockerfile.hub -t  zaoui ./",

"docker:tag": "docker tag zaoui zaoui",

"docker:push
```
you can remove this.if you don’t use docker

**Comment by THARAKS** [comment]
Hi chenshuai2144 i need a help , could you please edit and remove the content which you mentioned in previous comment , at-least  you can keep till docker-prod:build , rest you can remove or i wish if u delete entire data it will be fine i have mistakenly posted data here

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
