### ISSUE TITLE
ant-design-pro@1.2.1配合socket.io@2.2.0,npm run start 报错

### ISSUE THREAD

**Issue by 15980131262** [ant-design/ant-design-pro#4625]
在没安装socket.io前,项目正常, 安装完socket.io后,npm run start 报错, 查看log如下:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\PhpSort\\nodejs\\node.exe',
1 verbose cli   'D:\\PhpSort\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ant-design-pro@1.2.1~prestart: ant-design-pro@1.2.1
6 info lifecycle ant-design-pro@1.2.1~start: ant-design-pro@1.2.1
7 verbose lifecycle ant-design-pro@1.2.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@1.2.1~start: PATH: D:\PhpSort\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\PhpSort\xampp\htdocs\erp\frontend\node_modules\.bin;D:\PhpSort\xampp\htdocs\erp\frontend\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\PhpSort\nodejs\;D:\PhpSort\xampp\php;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\ProgramData\ComposerSetup\bin;C:\ProgramData\chocolatey\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm;D:\PhpSort\nodejs;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin
9 verbose lifecycle ant-design-pro@1.2.1~start: CWD: D:\PhpSort\xampp\htdocs\erp\frontend
10 silly lifecycle ant-design-pro@1.2.1~start: Args: [ '/d /s /c', 'cross-env ESLINT=none roadhog dev' ]
11 silly lifecycle ant-design-pro@1.2.1~start: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@1.2.1~start: Failed to exec start script
13 verbose stack Error: ant-design-pro@1.2.1 start: `cross-env ESLINT=none roadhog dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\PhpSort\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\PhpSort\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid ant-design-pro@1.2.1
15 verbose cwd D:\PhpSort\xampp\htdocs\erp\frontend
16 verbose Windows_NT 10.0.14393
17 verbose argv "D:\\PhpSort\\nodejs\\node.exe" "D:\\PhpSort\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@1.2.1 start: `cross-env ESLINT=none roadhog dev`
22 error Exit status 1
23 error Failed at the ant-design-pro@1.2.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
请问是否是该版本和socket存在版本冲突?

**Comment by chenshuai2144** [comment]
这个看起来是底层某个库不兼容造成的

**Comment by 15980131262** [comment]
> 这个看起来是底层某个库不兼容造成的
> 最好升级一下，或者全部锁包

降了socket.io版本后正常

**Comment by 15980131262** [comment]
> 这个看起来是底层某个库不兼容造成的
> 最好升级一下，或者全部锁包

您好, 经过测试发现使用最新的antd design pro 是没问题的, 那么我现在antd-design-pro@1.2 的要怎么升级到比较新的版本呢?

**Comment by chenshuai2144** [comment]
https://v2-pro.ant.design/docs/upgrade-v2-cn

**Comment by 15980131262** [comment]
您好, 今天尝试着从1.2升级到2.0, 根据https://v2-pro.ant.design/docs/upgrade-v2-cn这篇文章去操作, 发现最后好像是成功了,能运行起来, 但发现前端页面有做修改或打印输出,在console中均没有打印输出, 好像现在运行的项目读取的是缓存的还是编译后的文件; 但是故意留着打印记录在指定页面上,然后再编译,再运行代码,在console也打印不出来?请指教,有没有这种情况,或者是哪边配置的问题?很期望能收到您的回复,谢谢!
