### ISSUE TITLE
fetch:blocks后，启动是404

### ISSUE THREAD

**Issue by waylon-edmodo** [ant-design/ant-design-pro#4626]
![Screen Shot 2019-06-26 at 3 50 06 PM](https://user-images.githubusercontent.com/51694657/60161397-17642c00-982a-11e9-8544-c25c4b866ef9.png)

终于安装成功，启动只有404.

**Comment by chenshuai2144** [comment]
说明你还是没有安装成功。年轻人用 bash 吧 cmd 没有前途的

**Comment by waylon-edmodo** [comment]
?
我的mac电脑，就是bash呀

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-26 at 3 53 36 PM](https://user-images.githubusercontent.com/51694657/60161673-93f70a80-982a-11e9-9835-dd3a996d4b12.png)

**Comment by waylon-edmodo** [comment]
看。这么多的success。

**Comment by waylon-edmodo** [comment]
yarn的时候，警告实在是太多了。好像package.json里面的库的版本冲突的很厉害呀。

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-26 at 3 58 13 PM](https://user-images.githubusercontent.com/51694657/60162015-3a431000-982b-11e9-9789-9d7393739f54.png)
居然真的没有users。 这log太假了。

**Comment by waylon-edmodo** [comment]
没成功的时候，就只有 user/login这一个。 成功了却没有它。 伤

**Comment by chenshuai2144** [comment]
debug 一下脚本吧! 你一遍一遍的试下去，我们不知道问题是什么
你也只能等项目自己的好

**Comment by waylon-edmodo** [comment]
调试发现一直卡在这里， 没有返回。。

    exec(
      shell,
      {
        encoding: "utf8",
        cwd,
        env: {
          ...process.env,
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        }
      },
      error => {
        if (error) {
          console.error(error);
          return reject(error);
        }
        resolve();
      }
    );

**Comment by waylon-edmodo** [comment]
不知道这下边发生了什么。没有到error也不会返回，就一直卡着。

**Comment by waylon-edmodo** [comment]
有时候狗屎运会过一个。然后下一个又卡住了。

**Comment by waylon-edmodo** [comment]
直接把语句拿出来跑，可以过。不过跑下面这句的时候，跑完也是被吊起。要用ctrl+c退出
npx umi block add https://github.com/ant-design/pro-blocks/tree/master/UserLogin --path=/user/login

**Comment by waylon-edmodo** [comment]
改了fetch-blocks.js, 发现成功一个到下一个的时候。fetch-blocks.js 又会被刷新变回改之前的。

**Comment by waylon-edmodo** [comment]
搞不定哟。

**Comment by waylon-edmodo** [comment]
swl-macmini2:web-admin lsqswl$ npx umi block add https://github.com/ant-design/pro-blocks/tree/master/UserRegister --path=/user/register
✔ 😁  Parse url and args
✔ 🚒 Git fetch
✔ 🚪 Git checkout master
✔ 🚀 Git pull
  📦  install dependencies package
  🔥  Generate files
   create src/pages/user/register/_mock.ts
   create src/pages/user/register/index.tsx
   create src/pages/user/register/locales/en-US.ts
   create src/pages/user/register/locales/zh-CN.ts
   create src/pages/user/register/locales/zh-TW.ts
   create src/pages/user/register/model.ts
   create src/pages/user/register/service.ts
   create src/pages/user/register/style.less
✔ 🔥  Generate files
✔ 🧐  Write route /user/register to /Users/lsqswl/Desktop/project/netinfo/web-admin/config/config.ts
✔  success   probable url http://localhost:8000/user/register (copied to clipboard) for view the block.
(node:8041) UnhandledPromiseRejectionWarning: FetchError: request to https://registry.npmjs.org/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/lsqswl/Desktop/project/netinfo/web-admin/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:8041) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8041) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


发生错误的时候才会继续下一个。不知道为啥这里的源还是官方的。

**Comment by waylon-edmodo** [comment]
npx umi block add https://github.com/ant-design/pro-blocks/tree/master/EditorKoni --path=/editor/koni
执行这些语句的时候，成功后，都会被挂起，只有ctrl+c才会退出。所以上面执行脚本的时候一直进不到回调应该也是这个原因。只是不知道为啥会被挂起，不能成功退出。

**Comment by chenshuai2144** [comment]
```
npx umi block add https://github.com/ant-design/pro-blocks/tree/master/EditorKoni --path=/editor/koni
```
来个日志

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-26 at 10 19 12 PM](https://user-images.githubusercontent.com/51694657/60187606-73e23e00-9860-11e9-8edd-4325e31ac6a6.png)

估计不能按ctrl+c退出。按ctrl+c退出的话路由不生效，虽然模块是安装进去了，路由过去会跳到404

**Comment by waylon-edmodo** [comment]
但是如果不按ctrl+c退出，就会一直被挂在那里。

**Comment by tronnet** [comment]
Silenciar.
Atenciosamente,
<http://site.tron.com.br/site/home/>

Joquebede Castro
Administrativo/Financeiro
(62) 3239 7364 | 99844 6960

O novo começa aqui.
tron.com.br <http://site.tron.com.br/site/home/>




<https://www.facebook.com/troninformatica/>
<https://www.instagram.com/tron.informatica/>
<https://pt.linkedin.com/company/tron-inform-tica>




















Essa mensagem é destinada exclusivamente ao seu(s) destinatário(s) e pode
conter informações confidenciais, protegidas por sigilo profissional ou
cuja divulgação seja proibida por lei. O uso não autorizado de tais
informações é proibido e está sujeito às penalidades cabíveis.


Em qua, 26 de jun de 2019 às 11:21, waylon <notifications@github.com>
escreveu:

**Comment by waylon-edmodo** [comment]
我把命令全部弄出来，执行，然后一句成功后，按ctrl+c中断掉，接着装下一句。最后成功了。唉，需要大神帮忙研究一下，为啥不按ctrl+c无法退出。导致无法执行下一句。

**Comment by waylon-edmodo** [comment]
![Screen Shot 2019-06-26 at 10 28 16 PM](https://user-images.githubusercontent.com/51694657/60188362-bb1cfe80-9861-11e9-89ce-ca02b02b44ec.png)
成功后的界面。

**Comment by waylon-edmodo** [comment]
https://github.com/ant-design/ant-design-pro/issues/4550

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4642
