### ISSUE TITLE
npx umi block add UserLogin --path=/user/login 拉取的ts版本的组件，如何拉取js版本

### ISSUE THREAD

**Issue by Somnus007** [ant-design/ant-design-pro#4627]

**Comment by chenshuai2144** [comment]
加个 --js  https://umijs.org/zh/guide/block.html#%E4%BD%BF%E7%94%A8%E5%8C%BA%E5%9D%97
> 我们不推荐用 js 版本。

**Comment by xland** [comment]
@chenshuai2144 

是整个antd-pro不推荐用js版本，还是只有block的代码不推荐用js版本？
