### ISSUE TITLE
官方预览网站无法访问

### ISSUE THREAD

**Issue by billwing** [ant-design/ant-design-pro#4628]
https://preview.pro.ant.design/ 打开显示如下：
![image](https://user-images.githubusercontent.com/3411815/60169768-ec81d400-9839-11e9-9885-4f81b1e2040b.png)

**Comment by chenshuai2144** [comment]
http://preview.pro.ant.design/ 
先用 http ，证书正在签发中，需要一点时间生效

**Comment by afc163** [comment]
现在貌似会自己跳到 https，只能等证书了。

**Comment by billwing** [comment]
好的，Chrome由于hsts机制会跳到https，用Safari可以访问http。

**Comment by chenshuai2144** [comment]
试试牛逼的 edge 吧
