### ISSUE TITLE
一个刚clone下来的项目，esline报错

### ISSUE THREAD

**Issue by wasdujk** [ant-design/ant-design-pro#4629]
![image](https://user-images.githubusercontent.com/26673917/60170811-d37a2280-983b-11e9-9cc9-a2a4f4d04acc.png)
如图所示，使用了blog中的解决方案与将antd降级到3.19.1或3.19.6或是升级到3.19.8都未能解决这个问题

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/issues/2652，先这样解决吧。后续做通用方案

**Comment by afc163** [comment]
@ycjcl868 给 pro 里先加上这段，不然答疑会一直来。

**Comment by ycjcl868** [comment]
ok
