### ISSUE TITLE
【PRO狂热者提出的非PRO问题】大佬们都是怎么快速解决js运算丢精度问题的？

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#4630]
![image](https://user-images.githubusercontent.com/20454290/60179815-18f51a80-9851-11e9-9060-e3667f1235c0.png)

百度上都是自己写方法，请问有解决此类问题的npm工具吗？ 

PS：不知道怎么搞的，百度不能快速解决的问题，我都喜欢来这里问大佬们，大佬们也都用最精简的文字给了我最高效的解决办法。😄

**Comment by afc163** [comment]
https://zhuanlan.zhihu.com/p/36330307

https://github.com/tc39/proposal-bigint

Stage 3 了，快了。

**Comment by 419280377** [comment]
> https://zhuanlan.zhihu.com/p/36330307
> 
> https://github.com/tc39/proposal-bigint
> 
> Stage 3 了，快了。

It is very nice of you！
