### ISSUE TITLE
求助，怎么去掉下图中的线

### ISSUE THREAD

**Issue by q6413260** [ant-design/ant-design-pro#4632]
![image](https://user-images.githubusercontent.com/11553677/60182050-177a2100-9856-11e9-9404-76112cd553b5.png)
如上图，把ant-layout和ant-layout-footer的背景颜色都改成白色了，感觉红框中的一条线挺多余的，想问下怎么去掉

**Comment by chenshuai2144** [comment]
直接用 css 去掉吧

**Comment by q6413260** [comment]
@chenshuai2144 
3q，已经解决了
