### ISSUE TITLE
preview.pro.ant.design预览进不去了

### ISSUE THREAD

**Issue by php2020** [ant-design/ant-design-pro#4635]
![image](https://user-images.githubusercontent.com/22309166/60230831-d7ed1c80-98c9-11e9-9614-3f90b801cbfc.png)
macOS 10.14.3 
![image](https://user-images.githubusercontent.com/22309166/60230972-50ec7400-98ca-11e9-89b9-3e75b8726194.png)

**Comment by chenshuai2144** [comment]
可以先使用 http。我们修改了域名托管商。证书正在签发。
