### ISSUE TITLE
演示站什么时候恢复呢

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design-pro#4636]
![TIM截图20190627105500](https://user-images.githubusercontent.com/3746762/60230900-1be02180-98ca-11e9-94a7-1d32cd9b9f1e.png)

**Comment by totemtec** [comment]
北京联通，也是这个问题
系统Mac 10.13 Chrome最新版
Safari也不行，虚拟机上跑了个Win7+Chrome也不行

群里有同行反馈说可以访问，经常这样抽风

**Comment by chenshuai2144** [comment]
使用 http 就可以了，我们迁移了一下托管商，证书签发速度有点慢。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4647
