### ISSUE TITLE
ci 挂了？

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#4637]
<img width="173" alt="image" src="https://user-images.githubusercontent.com/507615/60234165-bbef7800-98d5-11e9-8cd1-3fa0aadc93f5.png">

**Comment by chenshuai2144** [comment]
import-sort 升级了一把。我把这个改成 warning 吧

**Comment by afc163** [comment]
这个顺序还是很重要的，改掉吧。

**Comment by chenshuai2144** [comment]
嗯 我会改掉的，但是好多同学不堪其扰

**Comment by afc163** [comment]
搞一个严格模式和宽松模式，默认宽松，项目中可以开启严格模式。
