### ISSUE TITLE
文档缺少可操作性

### ISSUE THREAD

**Issue by lovelock** [ant-design/ant-design-pro#4639]
V4版本相对之前的有很大的变化, 这个从现在能搜到的信息能看出来, 参考[Ant Design Pro v4 is Here](https://zhuanlan.zhihu.com/p/67498559). 但文档仍然是之前版本的组织形式, 导致对ADP没有任何了解的新手上来就会受挫.
![image](https://user-images.githubusercontent.com/2208731/60242035-4ab8c080-98e7-11e9-8784-69b8cf3fb4df.png)
比如这里, block是?v4中新引入的概念, 是在基于ADP的系统中一切的基础, 文档却先讲路由, 而且在讲路由的页面教用户添加菜单(添加的菜单是需要先用umi block add进来才能用的)
![image](https://user-images.githubusercontent.com/2208731/60242164-9ff4d200-98e7-11e9-93ff-8bdb1f2eb611.png)
当用户按文档修改了这些以后页面就报错了.

我对前端的技术栈不甚了解, 可能是我错过了一些其他人都公认应该是都知道的内容. 不过还是希望能针对V4版本重新修订一下文档. 现在能在网上搜到的教程都是以前的版本, 如果官方文档能增强一下可操作性, 我觉得会对新版本的推广更有利不是吗? 🙏🙏

**Comment by sjcarr** [comment]
也不理解为什么强制转入TS

**Comment by chenshuai2144** [comment]
TypeScrtipt 可以显著的减少低级错误和查文档的时间

**Comment by lovelock** [comment]
> TypeScrtipt 可以显著的减少低级错误和查文档的时间

这点我是支持的。只是在不是很重视前端的公司，在一个默认大家都只会js的环境下， 推动ts还是比较困难的。可能主要来自对未知的恐惧。。。

**Comment by sjcarr** [comment]
谈不上恐惧吧，对于公司多个产品用antd构建的情况下，希望能够有一个延续的维护；用TS再来一遍？
就像有人在issues里提到的，antd版本更新快但却没有一个LTS版本一样。对于一个人力有限的小公司来说，这样的成本太高。
TS也只是技术，用未知来形容它，有点高估它了。

**Comment by soulmatecm** [comment]
我也觉得是，更新太快，但是一直没有一个稳定的版本，项目做到中途，可能已经发生了很大的变化了。

**Comment by TrumanDu** [comment]
v4文档更新确实好慢，很多文档已经是无用的，希望团队能关注一下文档的建设。按照现在文档摸索，友好性确实好差，还很容易干扰人。
