### ISSUE TITLE
Menu 组件 selectedKeys  有 bug 

### ISSUE THREAD

**Issue by Mantak** [ant-design/ant-design-pro#464]
`      {
        name: '表单页',
        path: 'form',
        icon: 'form',
        children: [
          {
            name: '分析页',
            path: 'analysis',
            component: dynamicWrapper(app, ['chart'], () => import('../routes/Dashboard/Analysis')),
          },
          {
            name: '基础表单',
            path: 'basic-form',
            component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/BasicForm')),
          },
`

我将nav.js里的 dashboard 下的分析页，简单的复制到表单页的children里，
这时候，首页默认显示的是/dashboard/analysis  菜单列表里的分析页高亮，但是，菜单列表，表单页下的analysis也高亮了
而selectedKeys的是一个包含了父级路径的数组，从文档上看，不该有这个问题

**Comment by chenshuai2144** [comment]
重复了 #378 
现在正在改进...
看一下 #442
