### ISSUE TITLE
页面刚载入时图表显示错误

### ISSUE THREAD

**Issue by Odinman** [ant-design/ant-design-pro#4640]
问题是最近才出现的，代码没变，可能是升级某个包(bizcharts?)导致的
http://preview.pro.ant.design 也有同样的问题：
在页面刚栽入的时候，图表显示时错误的。错误显示大概持续半秒钟后，图标会“变”正常，过程中有动画。
截图如下：
错误1，柱状图宽度是小的：
![image](https://user-images.githubusercontent.com/388163/60243474-e861bf00-98ea-11e9-99d7-0328b12b90fd.png)
半秒后正常：
![image](https://user-images.githubusercontent.com/388163/60243556-134c1300-98eb-11e9-89de-0af221454015.png)

错误2，图表错位，到屏幕外了
![image](https://user-images.githubusercontent.com/388163/60243766-8bb2d400-98eb-11e9-927e-9f8103a79107.png)
也是半秒后正常：
![image](https://user-images.githubusercontent.com/388163/60243835-ad13c000-98eb-11e9-979a-2fa2bd335bd2.png)

**Comment by IMSupperkaka** [comment]
我本地也有这个问题 感觉像是图表初始化的时候宽度不正确

**Comment by chenshuai2144** [comment]
@IMSupperkaka   没有样式的原因是 dll，具体看这个 issue. https://github.com/umijs/umi/pull/2686

**Comment by chenshuai2144** [comment]
@Odinman  因为 pro 的脚手架中并没有自动计算宽度，你可以自己计算宽度来修复这个问题。
或者用 g2 自带的图标渲染器

**Comment by Odinman** [comment]
@chenshuai2144 感谢回复
http://preview.pro.ant.design也会进行相关修改吧？我等着抄😄

**Comment by sorrycc** [comment]
就开发时这样，忍忍吧，😁
