### ISSUE TITLE
npm run fetch:blocks error

### ISSUE THREAD

**Issue by starhu521** [ant-design/ant-design-pro#4641]
![image](https://user-images.githubusercontent.com/23275495/60244060-35926080-98ec-11e9-845c-cd44020deb2b.png)

**Comment by chenshuai2144** [comment]
能把你的项目 和 node 版本信息贴出来吗

**Comment by starhu521** [comment]
system: macos mojave 10.14.5
node: v10.15.3
npm: v6.9.0
umi: 2.8.6
项目是刚npm create umi 创建的，
npm install 后直接 npm run fetch:blocks的，
fetch blocks貌似有问题，起码没做catch

**Comment by starhu521** [comment]
哦对， 我从ant-design-pro直接clone的master分支，运行就没有问题，这其中运行的差别只有umi版本2.7.7

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4642

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4626

**Comment by chenshuai2144** [comment]
重复了
