### ISSUE TITLE
fetch:blocks  没有正确的显示 blocks 下载进度

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design-pro#4642]
![image](https://user-images.githubusercontent.com/19385704/60247577-7e99e300-98f3-11e9-905b-9e203dfb9f3c.png)

![image](https://user-images.githubusercontent.com/19385704/60247448-472b3680-98f3-11e9-8fd8-4166a104b634.png)

运行的新项目，没有改动，文件确实存在，而且大小写也没有问题

**Comment by dmdoit** [comment]
cnpm install   成功，
cnpm run fetch:blocks 成功，
cnpm start  的时候提示文件未找到

**Comment by chenshuai2144** [comment]
cnpm run fetch:blocks 可能是假成功，网络超时也会算成功
是一个bug

**Comment by yechunsuo** [comment]
npm/cnpm/yarn分别装了好多次了，一直提示这个This relative module was not found * ../list/search in ./src/pages/.umi/router.js fetch:blocks 。

**Comment by chenshuai2144** [comment]
重新运行 fetch:blocks

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/issues/4823
