### ISSUE TITLE
ant table i have date column currently it is having value like this 2019-06-30, while displaying it in table/ui  its format is changed to 2019-06-30 00:00:00

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#4644]
How to avoid the format change , i just want to display  2019-06-30

**Comment by chenshuai2144** [comment]
https://ant.design/components/date-picker/
date-picker have format function.

can you show you code?

**Comment by THARAKS** [comment]
I am not using any date picker, 

 {
      title: formatMessage({ id: 'app.feosdate' }),
      dataIndex: 'eosdate',
      onFilter: (value, record) => record.eosdate.indexOf(value) === 0,
      sorter: (a, b) => a.eosdate.length - b.eosdate.length,
      sortDirections: ['descend', 'ascend'],
      filters: [],
      filterMultiple: false,
      width: 160,
    },

its just a column a in table

**Comment by chenshuai2144** [comment]
emmm ，I don't think this antd, the table won't use the moment.
you can add `render:(text)=>moment(text).format(“YYYY-MM-DD”)`

**Comment by THARAKS** [comment]
yes thanks , its issue in the data itself , sorry for trouble
