### ISSUE TITLE
官方预览地址经常打不开！

### ISSUE THREAD

**Issue by yaeSakuras** [ant-design/ant-design-pro#4645]
官方预览地址老是打不开。
既然作为开源项目，大家都是奔着使用去的。
但是使用了一周发现，糟糕的文档说明经常缺失，预览地址也经常打不开。我作为开发者想使用你们的开源产品，你们也希望得到相应的反馈完善产品，但是这糟糕的体验，真的一定程度上阻碍了开发和使用。

![image](https://user-images.githubusercontent.com/7360502/60256523-4cdd4800-9904-11e9-897f-6e44faf87cec.png)

**Comment by glitterlip** [comment]
![Screen Shot 2019-06-27 at 9 37 11 PM](https://user-images.githubusercontent.com/16644496/60270842-ccc6da80-9923-11e9-8ffc-8a30e7e85a6f.png)
![Screen Shot 2019-06-27 at 9 38 10 PM](https://user-images.githubusercontent.com/16644496/60270879-e10ad780-9923-11e9-8f78-5af0eb172093.png)
是证书问题么?看了下是 valid 啊,现在想看预览要开 safari ,信任一下才行,chrome 根本打不开,这都好久了,能解决下么.

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4647 看着 issue。
