### ISSUE TITLE
have sidebar be collapsed by default

### ISSUE THREAD

**Issue by xcesiv** [ant-design/ant-design-pro#4646]
Hi,

Trying to set the default collapsed state of the sidebar in a fresh clone of the latest ant-design-pro to true instead of false. and can't seem to find a clear answer in the documentation or figure out the solution myself. I thought maybe it would be in config/defaultSettings.ts, but can't seem to find anything. Tried playing around with it and read the documentation of ant-deisng-pro-layout but there it says the default for collapsed is already true but the menu is open when i launch it.

Any help would be greatly appreicated.

Thanks

**Comment by boukmi** [comment]
I think ant-pro team only answers to issues in chinese, all the issues I have opened have never been answered.

**Comment by xcesiv** [comment]
> I think ant-pro team only answers to issues in chinese, all the issues I have opened have never been answered.
> I'll maybe use another framework, english support almost doesn't exist

I've had some success getting answers from the ant-design team in english on their Gitter, but I have noticed that i've gotten much fewer replies for Ant Design Pro. I stil really like the framework and maybe once more english speakers use it they'll be open to having us as collaberators to allieviate that. I don't think giving up on Ant Design Pro because of a sidebar being collapsed or not is good enough justification. Otherwise the english docs and what have you have been sufficent enough. Ty though.

**Comment by boukmi** [comment]
Yeah You’re right, I was getting some answers for ant-design too but none for ant-design-pro. I’ll maybe try their Gitter that you mentioned.
Sorry i cannot help you with your issue and if you can help me with mine that would be very appreciated 
Have you ever used redux form with the new ant-design-pro? I couldn’t figure out how to add the form reducer using dva!

Have a good one

**Comment by chenshuai2144** [comment]
@xcesiv  https://ant.design/components/layout/#Layout.Sider

We use antd's Layout.Sider, which will automatically trigger onCollapsed based on the screen size.

**Comment by xcesiv** [comment]
So there isn't a way to initially load with the menu collapsed? Was trying to make it so the application I'm building using pro wants the sidebar to load inversely of how ant-design=pro does. They want this to be the default layout:

<img width="1439" alt="Screen Shot 2019-06-28 at 10 27 49" src="https://user-images.githubusercontent.com/10799441/60356987-a2126b80-998f-11e9-8ebb-0d8ffb6a69cc.png">

I'm aware of using the antd layout slider but when trying to set collapsed for the Sider to default true, I couldn't get it to work right.

Is there a way using Pro to have the Sider initially laod like the image? Thanks.

**Comment by boukmi** [comment]
Did you manage to have the side bar initially collapsed?

**Comment by xcesiv** [comment]
i still have not.

**Comment by chenshuai2144** [comment]
@xcesiv  you need set trigger={null} ，You can try adding in the layout, I am not sure if it will pass through to the side

**Comment by dpetrov** [comment]
Currently you can define collapsed: false into the config.js/ts and the sidebar will be collapsed by default. However, after the handleMenuCollapse is triggered, the sidebar remains collapsed.

@chenshuai2144 would you probably have an idea, why it would remain collapsed?

**Comment by VaVoose** [comment]
I think I may have figured out this issue. To start I am using Ant Design integrated with Vue. The default trigger event checks to see if the sidebar is collapsed by default and if it is it automatically opens it. So we need to check if the trigger is looking for the first time and block the change Here is my sample code:

`<a-layout-sider 
    collapsible
    breakpoint="md"
    :collapsed="c"
    :collapsed-width="collapsedWidth"
    @collapse="triggerCollapse"
    @breakpoint="onBreakpoint"
    :zeroWidthTriggerStyle='sidebarIconStyle'
    >`

`data () {
        return {
            c: true,
            firstCollapse: true, //One way flag for sidebar collapse state
       }
}
`

`triggerCollapse(){
            if(this.firstCollapse){
                this.firstCollapse = false;
                return;
            }
            this.c = !this.c;
        },`

I hope this helps

**Comment by zhangyongjiang** [comment]
In the BasicLayout.tsx, dispatch an event

```
  useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        true,
      });
      dispatch({
        type: 'user/fetchCurrent',
      });
    }
  }, []);
```
