### ISSUE TITLE
预览地址不可用的问题

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#4647]
由于部署方案的改造和升级。preview.pro.ant.design 可以访问不畅。
我们提供别的源来进行访问
国内用户 ：https://prosite.z23.web.core.windows.net/
国外用户：https://ant-design-pro.netlify.com

—

Due to the transformation and upgrade of the deployment plan. Preview. Pro. Ant. Design can be accessed poorly.

We provide other sources for access

Domestic users: https://prosite.z23.web.core.windows.net/

Foreign users: https://ant-design-pro.netlify.com

**Comment by afc163** [comment]
可以了：https://preview.pro.ant.design/ 恢复了。

**Comment by baixiaosh** [comment]
并不能登录

**Comment by wuchaoya** [comment]
Chrome 版本 75.0.3770.100（正式版本） （64 位） mac 不能登录，Safari正常
