### ISSUE TITLE
Breadcrumb links don't work properly

### ISSUE THREAD

**Issue by boukmi** [ant-design/ant-design-pro#4648]
Hello,

I believe the breadcrumb link do not work properly on ant design pro [preview](http://preview.pro.ant.design/form/advanced-form).

Nothing happens when I click on a breadcrumb link. I believe it's supposed to bring the user to the related page.
<img width="992" alt="antdp-1" src="https://user-images.githubusercontent.com/2116866/60277071-c2411c80-98f4-11e9-9477-ab647464a772.png">

Also, I think the last part of the breadcrumbs that points to the current page shouldn't be clickable? its color change when we hover it 
![antdp-2](https://user-images.githubusercontent.com/2116866/60277532-aab66380-98f5-11e9-8186-e1bc403e22cc.png)

Is this a known issue? or just a configuration problem?

I couldn't make them work on mu own project

Thank you for your help guys.

**Comment by chenshuai2144** [comment]
@boukmi  https://ant.design/components/breadcrumb/#Use-with-browserHistory

you can set itemRender in ProLayoutProps.

this is my default render 

https://github.com/ant-design/ant-design-pro-layout/blob/6ab074c425cb9c951fee1917d572e36b5051ca89/src/utils/getBreadcrumbProps.tsx#L28

**Comment by boukmi** [comment]
Thanks I’ll check this out!
