### ISSUE TITLE
Antd pro + redux-form

### ISSUE THREAD

**Issue by boukmi** [ant-design/ant-design-pro#4650]
Hi everyone,

Is there a way to add redux form reducer to antd pro?

Thank you su much

**Comment by chenshuai2144** [comment]
I don't know much about redux form. What trouble did you encounter?

**Comment by boukmi** [comment]
Hi and thank you for taking the time to look at this.
Refus-form works using its own reducer, and I don’t know how to add an external reducer with dva that is used by ant design pro.
This is from redux form doc
```javascript
import { createStore, combineReducers } from 'redux'
import { reducer as formReducer } from 'redux-form'

const rootReducer = combineReducers({
  // ...your other reducers here
  // you have to pass formReducer under 'form' key,
  // for custom keys look up the docs for 'getFormState'
  form: formReducer
})

const store = createStore(formReducer)
```

 the question is how to add a new reducer that uses redux store.

**Comment by chenshuai2144** [comment]
you need this https://dvajs.com/api/#app-use-hooks。
you can write it in src/app.ts. 
Umi will load it automatically

**Comment by boukmi** [comment]
Thank you I’ll check this out!

**Comment by boukmi** [comment]
There is no src/app.ts un ant design pro template project. Does this mean I need to create one?
Is it possible for you to provide a small example please?

**Comment by chenshuai2144** [comment]
https://umijs.org/guide/app-structure.html#src-app-js-ts

you can look here. this is a agreement

**Comment by boukmi** [comment]
This didn't work and I'm still stuck with this. Can you please help?

**Comment by chenshuai2144** [comment]
Submit a question in dva
