### ISSUE TITLE
Antd-Pro theme fails

### ISSUE THREAD

**Issue by mihai-cloudbrick** [ant-design/ant-design-pro#4651]
Hi, 
I try to change the theme variables in the config.js and has no effect. I noticed that when the page reload i can see the changes but then are gone goind to the default. 
Do you have a any solution for this? 
I created the app using yarn create umi, i believe its a umi issue but im no expert. 
I realy like antd and i just started with it

**Comment by mihai-cloudbrick** [comment]
The changes that  made looks like this

// Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'font-size-base': '12px',
    'page-header-padding-horizontal': '3px',
    'page-header-padding-vertical': '2px',
    'border-radius-base': '0px',
    'border-radius-sm': '0px',
    'padding-lg': '16px', // containers
    'padding-md': '8px', // small containers and buttons
    'padding-sm': '4px', // Form controls and items
    'padding-xs': '2px' // small items
  },

**Comment by chenshuai2144** [comment]
you can update umi。
in old umi， have a bug for dll close them config

**Comment by mihai-cloudbrick** [comment]
I done that but no luck, to ilustrate the issue :
i changed in global.less 
html,
body,
#root {
  height: 100%;
  background-color: red;
}
and this is the result: https://drive.google.com/file/d/1c6KJWY5gqm9zInTVQ4cdX4PsP_Th17Mw/view

**Comment by chenshuai2144** [comment]
dll after loaded for css loade.
You can increase the priority of css, or turn off dll。

https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L45
