### ISSUE TITLE
fail to load color.less in (preview.pro.ant.design)

### ISSUE THREAD

**Issue by Dev-Jeromebaek** [ant-design/ant-design-pro#4652]
We could not verify preview of version 4.

message: "'https://preview.pro.ant.design/color.less' wasn't found (404)"

![스크린샷 2019-06-28 오전 11 05 09](https://user-images.githubusercontent.com/27988231/60312095-e3f1e080-9994-11e9-9377-9c5998f83ce0.png)

**Comment by chenshuai2144** [comment]
in latest version，this file is no longer needed. Have you used pwa?

**Comment by Dev-Jeromebaek** [comment]
A ha! Ok! The cache was erased and it was solved. Thank you. Have a nice day.
