### ISSUE TITLE
提示tc语法错误

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#4653]
提示tc语法错误 

mock/notices.ts  line1

mock/user.ts   line 75

src/layouts/BasicLayout.tsx  line23 line72

**Comment by chenshuai2144** [comment]
截图？

**Comment by fanhualei** [comment]
![未标题-1](https://user-images.githubusercontent.com/34436863/60323021-815c0d00-99b3-11e9-8ad6-82343f30b535.png)

**Comment by chenshuai2144** [comment]
升级一下 ts 的版本。

**Comment by fanhualei** [comment]
```shell 
npm -g install typescript
tsc -v 
```
Version 3.5.2  --  还是提示上面的的错误。

**Comment by chenshuai2144** [comment]
Omit 在 ts 中已经原生支持了
