### ISSUE TITLE
hooks pre-commit

### ISSUE THREAD

**Issue by 160905** [ant-design/ant-design-pro#4655]
![企业微信20190628114837](https://user-images.githubusercontent.com/22002759/60315820-c889d400-999a-11e9-9346-2b50cdf22efb.png)

What's the reason

**Comment by chenshuai2144** [comment]
http://eslint.cn/

you need fix eslint

**Comment by 160905** [comment]
Can I delete the file tsconfig.json

**Comment by 160905** [comment]
![企业微信20190628022855](https://user-images.githubusercontent.com/22002759/60322051-17daff00-99b1-11e9-8267-df93d5003bdb.png)

**Comment by chenshuai2144** [comment]
tsconfig.json is reqiured
