### ISSUE TITLE
官网预览出问题了

### ISSUE THREAD

**Issue by Agagy** [ant-design/ant-design-pro#4656]
![11561701328_ pic_hd](https://user-images.githubusercontent.com/33778021/60320522-8bc6d880-99ac-11e9-8d25-0c4f07e17b86.jpg)

**Comment by afc163** [comment]
强刷一下

**Comment by Agagy** [comment]
强刷也不行，换浏览器也不行，清缓存也不行，一直在跳404

**Comment by chenshuai2144** [comment]
@Agagy 给一下具体请求的截图

**Comment by Agagy** [comment]
![21561702267_ pic_hd](https://user-images.githubusercontent.com/33778021/60321186-a437f280-99ae-11e9-8c80-5abae16d3e62.jpg)
进来系统直接进来登录页，然后一直请求获取用户信息接口，一直报404

**Comment by Agagy** [comment]
@chenshuai2144 @afc163 我用的火狐浏览器，登录页是出现弹框，一直在登录页和404页面来回跳，进入系统里其他页面是直接跳到了404页面。

**Comment by chenshuai2144** [comment]
@Agagy 是哪个接口，把地址发出来。

**Comment by Agagy** [comment]
![31561702796_ pic](https://user-images.githubusercontent.com/33778021/60321600-de55c400-99af-11e9-91a1-268bcdf1260a.jpg)
我就只看到这一个接口在请求

**Comment by chenshuai2144** [comment]
打来控制台-> network 来个截图吧。

**Comment by Agagy** [comment]
我上面截图里有啊

**Comment by Agagy** [comment]
但是我在谷歌浏览器里打开没问题

**Comment by chenshuai2144** [comment]
https://ant-design-pro.netlify.com/api/currentUser

应该请求这个，强刷一下吧。被缓存了

**Comment by Agagy** [comment]
火狐浏览器因为那个弹框一直出来然后卡死了，我强制关闭后重新打开好了，是以为缓存没清理干净吗？
