### ISSUE TITLE
GlobalHeader组件中在RightContent.tsx中使用NoticeIconView.tsx，点击查看通知图标后报错

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#4658]
错误如下：
![20190628153350](https://user-images.githubusercontent.com/33716687/60325652-6345db00-99ba-11e9-8e92-ea065b3136c0.jpg)
![20190628153438](https://user-images.githubusercontent.com/33716687/60325699-807aa980-99ba-11e9-85b7-08585272b30c.jpg)

**Comment by chenshuai2144** [comment]
一个 dom 上不存在的属性被透传了

**Comment by bijiasuo2006** [comment]
@chenshuai2144 如何修复这个问题？

**Comment by bijiasuo2006** [comment]
@chenshuai2144 已经测试改动，It works！非常感谢！
