### ISSUE TITLE
 dispath不发起请求

### ISSUE THREAD

**Issue by it5200** [ant-design/ant-design-pro#4659]
bebug 了代码是走到了dispath那步了，但是没有发起网络请求（这是一个组件，有的页面发起网络请求，有的页面不发起网络请求），很郁闷，求解

**Comment by chenshuai2144** [comment]
是不是有的接口报错了，你没有 try catch?

**Comment by it5200** [comment]
这是一个组件，有的页面发起网络请求，有的页面不发起网络请求
--------------------------------------------------------------------------------
就是同一个组件在不同页面，有点页面使用是可以发起请求的，有点页面没有发起请求，是同一个接口

**Comment by chenshuai2144** [comment]
看一下代码把。
