### ISSUE TITLE
怎么去掉代码分离

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#466]
因为组件差不多是同一个就是数据不同，所以不想让几个路由的代码分离 怎么关闭代码分离

**Comment by chenshuai2144** [comment]
你是指打包成多个js文件吗?

**Comment by wunayou** [comment]
@chenshuai2144  能跟我说一下  .roadhogrc 代码分离的原理或者方向吗？一个路由也能打包10个文件  

个人需求
因为把组件已经封装的完善了，页面基本相似，基本上都是通过路由传参数就可以生成所需要的页面了，
路由用同一个组件，打包的文件数量也不变

**Comment by chenshuai2144** [comment]
>  component: dynamicWrapper(app, ['list'], () => import('../routes/List/CardList')

修改为

> component: CardList

就可以了  可能工作量比较大.

**Comment by wunayou** [comment]
@chenshuai2144 不对啊 那reudx的东西 怎么传递

**Comment by chenshuai2144** [comment]
```
// wrapper of dynamic
const dynamicWrapper = (app, models, component) => dynamic({
  app,
  models: () => models.map(m => import(`../models/${m}.js`)),
  component,
});
```
那试试这个..我看了一圈webpack 好像关闭的办法,等我研究一会

**Comment by wunayou** [comment]
@chenshuai2144  是因为 .roadhog打包工具 自已采用的代码分离  这个是路由4.0代码分离 搞懂 这二个有什么区别了

**Comment by chenshuai2144** [comment]
不是这个吗?
[动态导入  ](https://doc.webpack-china.org/guides/code-splitting/#-dynamic-imports-)...

我以为你是想关掉动态导入

**Comment by nikogu** [comment]
试试把 import 改成 require

**Comment by afc163** [comment]
#470
