### ISSUE TITLE
刷新页面加载时样式异常

### ISSUE THREAD

**Issue by Hansuku** [ant-design/ant-design-pro#4660]
![image](https://user-images.githubusercontent.com/28286561/60329032-1403a880-99c2-11e9-9bbe-160e64adf2df.png)
直接从官方仓库 clone 的项目 跑起来刷新一下就可以看到这个问题了 感觉是 css 还没渲染

**Comment by wang997722** [comment]
+1

**Comment by chenShengYa** [comment]
I also have this problem.

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/2686

look this pr.

He only appears in the dev environment
You can close the dll to fix it.

**Comment by chenShengYa** [comment]
ty

**Comment by chenshuai2144** [comment]
期待 webpack5，可以解决掉这些问题。

**Comment by Hansuku** [comment]
好了 我试着把 config.ts 下面 dll 的东西都注释了就正常了 不过这样做会让别的东西有影响吗？ 我看他里面 include 了 dva 之类的东西

**Comment by chenshuai2144** [comment]
dll 是用于优化启动速度的，可以提升第二次启动的速度，不会影响到正式环境
