### ISSUE TITLE
页面样式错乱

### ISSUE THREAD

**Issue by xland** [ant-design/ant-design-pro#4665]
新建的项目，完全按照官方的教程创建
刷新页面样式错乱
看起来像什么样式文件没加载，但打开调试工具，发现没有什么东西没加载
刷新多次，偶尔有一次是正常的。
![image](https://user-images.githubusercontent.com/2980915/60384261-3b37a400-9aae-11e9-809d-04dd08d8cd98.png)

**Comment by afc163** [comment]
给个重现 repo 看看？

**Comment by xland** [comment]
@afc163 

repo不太好搞了，要剥离挺多东西；

谷歌浏览器不会出问题
qq浏览器（也是谷歌核心）10次刷新里，大概有6次会出问题

![image](https://user-images.githubusercontent.com/2980915/60384483-e0537c00-9ab0-11e9-9f4b-4c4a8e43b0d9.png)

**Comment by chenshuai2144** [comment]
@xland 试着删除 dll？
https://github.com/ant-design/ant-design-pro/blob/31efd937313324ee6633583ed20a3355d8976ba4/config/config.ts#L45

在这里

**Comment by xland** [comment]
@chenshuai2144 

嗯！删了这里，多次刷新再没出现过问题！谢谢！

不过....
这里是干嘛用的，不会导致别的问题吧；

另外，能顺便帮忙看看我提的上一个issue吗？

**Comment by chenshuai2144** [comment]
https://webpack.js.org/plugins/dll-plugin/

**Comment by chenshuai2144** [comment]
dll 是不是默认关闭，需要了开启一下，有种不可控的感觉。
@sorrycc  @afc163 

https://github.com/ant-design/ant-design-pro/issues/4660

**Comment by sorrycc** [comment]
可以关掉。

**Comment by chenshuai2144** [comment]
等待 webpack5 吧
