### ISSUE TITLE
我在pro antd项目下安排react-dragline插件后，整个项目就废了

### ISSUE THREAD

**Issue by tgy3300** [ant-design/ant-design-pro#4666]
react-dragline插件github：https://github.com/zcued/react-dragline
我使用cnpm install react-dragline --save把插件安装上后，运行npm start后，出现如下严重错误：

` ERROR  Failed to compile with 20 errors                                        23:34:37

These dependencies were not found:

* core-js/modules/es6.array.filter in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.array.find in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.array.find-index in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/utils.js
* core-js/modules/es6.array.for-each in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.array.is-array in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/utils.js, ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.array.iterator in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.array.map in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.array.sort in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/utils.js, ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.number.constructor in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.number.max-safe-integer in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es6.object.define-property in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/utils.js, ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableChild.js and 2 others
* core-js/modules/es6.string.includes in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es7.array.includes in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/es7.object.entries in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js
* core-js/modules/web.dom.iterable in ./node_modules/_react-dragline@1.0.0@react-dragline/lib/DraggableContainer.js

To install them, you can run: npm install --save core-js/modules/es6.array.filter core-js/modules/es6.array.find core-js/modules/es6.array.find-index core-js/modules/es6.array.for-each core-js/modules/es6.array.is-array core-js/modules/es6.array.iterator core-js/modules/es6.array.map core-js/modules/es6.array.sort core-js/modules/es6.number.constructor core-js/modules/es6.number.max-safe-integer core-js/modules/es6.object.define-property core-js/modules/es6.string.includes core-js/modules/es7.array.includes core-js/modules/es7.object.entries core-js/modules/web.dom.iterable

 ERROR CODE  ERR_WEBPACK_DLL_MODULE_NOT_FOUND

 DETAILS

## 错误原因

构建 dll 文件时出错了，由于 dependencies 下的依赖会全部被打到 dll 里，所以报错可能有以下原因：

    1. dependencies 里的某些依赖没有 main 文件
    2. 应该放在 devDependencies 里的 node 相关的依赖却写在了 dependencies

## 解决方案

让不该打到 dll 的不被打到 dll 里，有几个解决方案：

    1. 把 node 相关依赖放到 devDependencies 里
    2. 把出错的依赖配置到 dll 的 exclude 里

比如：

    dll: {
      exclude: ['foo']
    }

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-29T15_34_37_872Z-debug.log`

我按照提示，运行

`cnpm install --save core-js/modules/es6.array.filter core-js/modules/es6.array.find core-js/modules/es6.array.find-index core-js/modules/es6.array.for-each core-js/modules/es6.array.is-array core-js/modules/es6.array.iterator core-js/modules/es6.array.map core-js/modules/es6.array.sort core-js/modules/es6.number.constructor core-js/modules/es6.number.max-safe-integer core-js/modules/es6.object.define-property core-js/modules/es6.string.includes core-js/modules/es7.array.includes core-js/modules/es7.object.entries core-js/modules/web.dom.iterable`

又出现下面的错误

`× Install fail! Error: [@core-js/modules/es6.array.filter] resolved target F:\mywww\zl-mark\app\pc-app\zl-pro-antd-project-190629\core-js\modules\es6.array.filter error: ENOENT: no such file or directory, lstat 'F:\mywww\zl-mark\app\pc-app\zl-pro-antd-project-190629\core-js'
Error: [@core-js/modules/es6.array.filter] resolved target F:\mywww\zl-mark\app\pc-app\zl-pro-antd-project-190629\core-js\modules\es6.array.filter error: ENOENT: no such file or directory, lstat 'F:\mywww\zl-mark\app\pc-app\zl-pro-antd-project-190629\core-js'
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\local.js:30:11)
    at module.exports.throw (<anonymous>)
    at onRejected (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:81:24)
npminstall version: 3.22.0
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org --save core-js/modules/es6.array.filter core-js/modules/es6.array.find core-js/modules/es6.array.find-index core-js/modules/es6.array.for-each core-js/modules/es6.array.is-array core-js/modules/es6.array.iterator core-js/modules/es6.array.map core-js/modules/es6.array.sort core-js/modules/es6.number.constructor core-js/modules/es6.number.max-safe-integer core-js/modules/es6.object.define-property core-js/modules/es6.string.includes core-js/modules/es7.array.includes core-js/modules/es7.object.entries core-js/modules/web.dom.iterable`

**Comment by tgy3300** [comment]
我运行cnpm install umi --save更新umi为最新版本后也一样有问题，运行cnpm install core-js --save  更新安装core-js后，再npm start还是启动不了项目

**Comment by chenshuai2144** [comment]
问题写的非常好。
看起来像是 core-js 报错造成的，因为 umi 现在还在锁版本在 core-js@2.x
给我们一个可重现的仓库？

**Comment by tgy3300** [comment]
> 问题写的非常好。
> 看起来像是 core-js 报错造成的，因为 umi 现在还在锁版本在 [core-js@2.x](mailto:core-js@2.x)
> 给我们一个可重现的仓库？

请按下面操作即可重现问题
1、yarn create umi my-app
2、Select the boilerplate type: 选择 Ant Design Pro
 ❯ ant-design-pro

3、Which language do you want to use? 选择你使用的语言
TypeScript
❯ JavaScript

4、cd my-app
5、cnpm install
6、cnpm install react-dragline --save
7、npm start  #问题就暴露了

**Comment by huagnshiren2014** [comment]
> 问题写的非常好。
> 看起来像是 core-js 报错造成的，因为 umi 现在还在锁版本在 [core-js@2.x](mailto:core-js@2.x)
> 给我们一个可重现的仓库？

我也遇到了类似问题，项目启动不了，现在有解决方案了吗

**Comment by tgy3300** [comment]
> 问题写的非常好。
> 看起来像是 core-js 报错造成的，因为 umi 现在还在锁版本在 [core-js@2.x](mailto:core-js@2.x)
> 给我们一个可重现的仓库？

不知这问题是否修复！！！

**Comment by chenshuai2144** [comment]
最新版本已经解决。我测试通过了

**Comment by laommmm** [comment]
有解决方法没？
