### ISSUE TITLE
添加区块报错

### ISSUE THREAD

**Issue by tomsure** [ant-design/ant-design-pro#4667]
![image](https://user-images.githubusercontent.com/15616904/60387153-beb6bc80-9ad1-11e9-9b11-0eabf76a81cc.png)
尝试了各种方式否不对
![image](https://user-images.githubusercontent.com/15616904/60387180-f291e200-9ad1-11e9-95ad-5de7043c3e51.png)

**Comment by chenshuai2144** [comment]
可能和这个有关试试
https://github.com/ant-design/ant-design-pro/issues/4664

**Comment by chenshuai2144** [comment]
你使用了cnpm 安装吗？

**Comment by tomsure** [comment]
已经可以了，谢谢！ 用这个命令    npx umi block add FormAdvancedForm  安装就没问题，对path那里用法不是很理解，总是报错，去掉path参数就自动安装到pages 目录里面了
