### ISSUE TITLE
umi block add fails, how to set proxy?

### ISSUE THREAD

**Issue by michaelgli** [ant-design/ant-design-pro#4668]
my company has a proxy.
**umi block add** fails.
How do i set the proxy for umi?

Thanks

**Comment by chenshuai2144** [comment]
you can clone  https://github.com/ant-design/pro-blocks

**Comment by michaelgli** [comment]
I cloned it. 
Then i tried the following:
umi block add /home/dev/antd-pro-blocks/FormBasicForm
and
umi block add file:///home/dev/antd-pro-blocks/FormBasicForm
I got errors:
FetchError: request to https://registry.npmjs.org/ failed
any ideas?
Thanks

**Comment by chenshuai2144** [comment]
This feature relies on github and npm. You may need to have your computer access them
