### ISSUE TITLE
初始化的项目是不是应该把登录页集成进来

### ISSUE THREAD

**Issue by xland** [ant-design/ant-design-pro#4669]
目前只有一个欢迎页，是不是太少了？

**Comment by chenshuai2144** [comment]
将会去做。login 中涉及到了权限，我们现在没有很好的办法来进行权限和 block 的配合

**Comment by fanhualei** [comment]
这样就方便多了， 另外整个代码维护起来会更方便一些。

**Comment by hsdtsyl** [comment]
login 做成可选项如何，企业内部很多用了统一4A认证，开发应用很多不需要登录页

**Comment by xwin1989** [comment]
是否面包屑也加成默认? 这个太常用了..

**Comment by GuoTeng** [comment]
> 是否面包屑也加成默认? 这个太常用了.. 现在的component里面并没有...

V4版本做了封装
![image](https://user-images.githubusercontent.com/23114978/61023933-76a36e00-a3de-11e9-9830-4bc9509fee77.png)
