### ISSUE TITLE
block add安装失败

### ISSUE THREAD

**Issue by tomsure** [ant-design/ant-design-pro#4674]
无法安装成功，报如下错误

![image](https://user-images.githubusercontent.com/15616904/60392317-d83c2080-9b32-11e9-890a-dfe4701aa877.png)

**Comment by tomsure** [comment]
![image](https://user-images.githubusercontent.com/15616904/60392311-ba6ebb80-9b32-11e9-9a66-c8d24103c628.png)

**Comment by chenshuai2144** [comment]
你使用了 cnpm 安装你的依赖吗？

**Comment by tomsure** [comment]
你是说Antd pro 拉下来之后安装的依赖吗？antd pro 是cnpm 安装的依赖
这些区块安装的时候，依赖是自动安装的

**Comment by chenshuai2144** [comment]
cnpm 和 npm 不兼容，推荐都用 cnpm 或者 npm
