### ISSUE TITLE
代码下载下来就报错

### ISSUE THREAD

**Issue by 952425340** [ant-design/ant-design-pro#4678]
npm create umi后npm install 在npm run start 控制台就报错了，然后菜单栏那个欢迎也没显示出来
![图片](https://user-images.githubusercontent.com/22728007/60406626-6d99ec00-9be9-11e9-9d8c-d41e2559139e.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/40
看一下这个

**Comment by xiuyangzhe** [comment]
> 
> 
> [ant-design/ant-design-pro-layout#40](https://github.com/ant-design/ant-design-pro-layout/issues/40)
> 看一下这个

怎么解决，我今天下载的也是这个问题

**Comment by chenshuai2144** [comment]
发了个新版本，更新一下依赖即可。

**Comment by xiuyangzhe** [comment]
> 
> 
> 发了个新版本，更新一下依赖即可。

你是说npm i吗，还是不行

**Comment by chenshuai2144** [comment]
`npm i @ant-design/pro-layout@4.5.10`
