### ISSUE TITLE
右上角头像dropdown内容未展示

### ISSUE THREAD

**Issue by VeChar** [ant-design/ant-design-pro#4679]
右上角头像dropdown内容未展示

比如个人设置，个人中心，退出登录这些都没有，V4版本

请问需要配置哪些参数

**Comment by afc163** [comment]
https://pro.ant.design/docs/block-cn
https://zhuanlan.zhihu.com/p/67498559

**Comment by VeChar** [comment]
> [https://pro.ant.design/docs/block-cn ](https://pro.ant.design/docs/block-cn)
> https://zhuanlan.zhihu.com/p/67498559

抱歉刚刚问题描述不够清楚，添加区块这些都有添加，还需要配置其他参数吗

**Comment by afc163** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
@VeChar  你调用了 fetch-blocks？

**Comment by VeChar** [comment]
> @VeChar 你调用了 fetch-blocks？

创建项目默认就没有展示

**Comment by chenshuai2144** [comment]
默认就是不展示的。只有调用了 fetch-blocks 并且成功之后才会显示

**Comment by afc163** [comment]
用户单独调用 umi block add 就会有问题？这样不太好

**Comment by VeChar** [comment]
> 用户单独调用 umi block add 就会有问题？这样不太好

是的，我项目写了很多了，单独安装了区块，就有这问题，如果重新 fetch-blocks 那将会导致很多问题的

**Comment by VeChar** [comment]
> 默认就是不展示的。只有调用了 fetch-blocks 并且成功之后才会显示

目前有没有其他的办法进行展示呢，创建项目之后，直接操作展示，而不通过 fetch-blocks

**Comment by hu382337381** [comment]
我刚试了试，在fetch-blocks后，还是没有头像的下拉框，感觉是fetch-blocks中的insertCode的insertRightContent这个方法没有执行，没有把相应的代码写到组件RightContent中 @chenshuai2144

**Comment by VeChar** [comment]
> 我刚试了试，在fetch-blocks后，还是没有头像的下拉框，感觉是fetch-blocks中的insertCode的insertRightContent这个方法没有执行，没有把相应的代码写到组件RightContent中 ，之后查看代码发现，RightContent中确实没有写入代码
> @chenshuai2144

记得前两天通过create umi创建项目fetch-blocks完后是有的，今天又试确实又没了

**Comment by youngsailor** [comment]
预览页面也没有下拉了

**Comment by chenshuai2144** [comment]
@VeChar  修了
