### ISSUE TITLE
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by cuongw** [ant-design/ant-design-pro#4683]
I am using Ant Design Pro v1. I have a problem with `babel-runtime` when install new package. Have a solution? Thanks!

**Comment by chenshuai2144** [comment]
Roadhog has stopped maintenance, you better lock all the packages。
try up to v4?

**Comment by cuongw** [comment]
I close this issue! I upgraded `roadhog` version to fix it.
```
"roadhog": "^2.5.0-beta.4"
```
