### ISSUE TITLE
最新版的 下载下来都是这个错误 是什么原因

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#4684]
![image](https://user-images.githubusercontent.com/183884/60411729-ba3cf180-9c00-11e9-96f9-0867cbf6145d.png)

**Comment by chenshuai2144** [comment]
这个是因为你的 formItem 的 name  重复了。排查一下试试

**Comment by WuJiY** [comment]
这个意思是重复了，可是涉及到form表单的页面都出现，奇怪了，我再试试。之前版本没这个问题

**Comment by afc163** [comment]
@chenshuai2144 antd 问题你要咨询一下 @zombieJ 。

**Comment by afc163** [comment]
@zombieJ 也可以适当保持关注一下。

https://github.com/react-component/form/pull/297

**Comment by zombieJ** [comment]
有重现没？看一下

**Comment by chenshuai2144** [comment]
这个和antd的ci没过的报错一样的
你修过一次

**Comment by zombieJ** [comment]
antd ci 是因为的确重复了相同的 field 名字，以前不报错现在报错了，行为是对的。但是上面这个，没有重现还是需要看看重现确认一下。以免漏了什么。

**Comment by WuJiY** [comment]
难道是因为我更新了antd 到3.20.0版本？

**Comment by afc163** [comment]
@WuJiY 给个重现步骤。
