### ISSUE TITLE
删除node module后重新npm i 后报如下错误（之前是ok的）

### ISSUE THREAD

**Issue by Smith-Jefferson** [ant-design/ant-design-pro#4685]
error  in ./src/pages/.umi/router.js

Module parse failed: Unexpected token (16:13)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   "component": __IS_BROWSER ? _dvaDynamic({
|     component: function component() {
>       return import(
|       /* webpackChunkName: "layouts__BasicLayout" */
|       '../../layouts/BasicLayout');

 @ ./src/pages/.umi/umi.js 49:36-58
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/u
mi.js

**Comment by chenshuai2144** [comment]
升级一下 umi 的版本。

**Comment by Smith-Jefferson** [comment]
麻烦请问应该升级到哪个版本，谢谢
现在的版本如下：

    "umi": "^2.4.4",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-react": "^1.4.2"

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/4690

**Comment by Smith-Jefferson** [comment]
在config.js 注释
      dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      },
就不会报错，是umi或者dva的问题吗？

**Comment by Smith-Jefferson** [comment]
尝试下来感觉是umi和dva的版本不匹配导致的，请问pro 2 的umi+dva推荐版本号有吗？

**Comment by chenshuai2144** [comment]
都到最高就好了

**Comment by qhanw** [comment]
都升到最新也解我决不了， 删除node_modules重新安装也不行，同时删了package-lock文件，具体是怎么回事呢？

> 都到最高就好了

都升到最新也解我决不了， 删除node_modules重新安装也不行，同时删了package-lock文件，具体是怎么回事呢？
