### ISSUE TITLE
新pr怎么更新到已有项目？

### ISSUE THREAD

**Issue by zytjs** [ant-design/ant-design-pro#4686]
像这里的修改，#4537

**Comment by xiaohuoni** [comment]
这个pr在umi中修复了。更新对应的umi版本就可以了

**Comment by zytjs** [comment]
更新到2.8.8后，报下面错误是什么原因？
These dependencies were not found:

* umi/_createHistory in dll umi
* umi/_renderRoutes in dll umi

**Comment by hbshun** [comment]
> 更新到2.8.8后，报下面错误是什么原因？
> These dependencies were not found:
> 
> * umi/_createHistory in dll umi
> * umi/_renderRoutes in dll umi

我升级了 umi-plugin-react 就不报错了。

**Comment by zytjs** [comment]
> > 更新到2.8.8后，报下面错误是什么原因？
> > These dependencies were not found:
> > 
> > * umi/_createHistory in dll umi
> > * umi/_renderRoutes in dll umi
> 
> 我升级了 umi-plugin-react 就不报错了。

谢谢，有用！怎么发现的
