### ISSUE TITLE
会不会添加快捷标签栏组件？

### ISSUE THREAD

**Issue by yoZerY** [ant-design/ant-design-pro#4687]
会不会添加快捷标签栏组件？

**Comment by chenshuai2144** [comment]
相应的截图 或者示例吗？

**Comment by yoZerY** [comment]
> 相应的截图 或者示例吗？
![QQ截图20190702114651](https://user-images.githubusercontent.com/45114578/60481255-2ed66580-9cbf-11e9-9628-6ae23a0e9aa1.png)

**Comment by chenshuai2144** [comment]
面包屑的另外一种样子？

**Comment by afc163** [comment]
Duplicate of #220
