### ISSUE TITLE
预览页出现很多404和报错

### ISSUE THREAD

**Issue by huhuf5** [ant-design/ant-design-pro#4688]

**Comment by gebilaoman** [comment]
+1

**Comment by xiaohuoni** [comment]
在哪？是指官网吗？
![image](https://user-images.githubusercontent.com/11746742/60475975-5839c600-9cac-11e9-9787-328dec806e8b.png)

**Comment by huhuf5** [comment]
进入Dash栏目全是404， 其他栏目也有很多



------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 上午9:33
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "┌纠ゝ结"<617179368@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] 预览页出现很多404和报错 (#4688)




在哪？是指官网吗？

**Comment by chenshuai2144** [comment]
@huhuf5 你可能是 pwa 的受害者，去删除一下 pwa 试试

/umi.002f2d77.js 应该加载这个 hash 的 js

**Comment by huhuf5** [comment]
> @huhuf5 你可能是 pwa 的受害者，去删除一下 pwa 试试
> 
> /umi.002f2d77.js 应该加载这个 hash 的 js

没有效果

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4705

**Comment by gebilaoman** [comment]
强制刷新页面，或者清空浏览器缓存
