### ISSUE TITLE
router in config.ts

### ISSUE THREAD

**Issue by omarc1492** [ant-design/ant-design-pro#4689]
I cannot find in documentation how to add menu bar category. 

I am using this command to add the 
> Analysis 

page` under the with the menu category

> Dashboard 

`npx umi block add DashboardAnalysis --path=/dashboard/analysis`

I want this
![Capture](https://user-images.githubusercontent.com/10967529/60418719-46232f00-9ba9-11e9-950e-8c7e6d0c604b.PNG)

But I get this
![Capture1](https://user-images.githubusercontent.com/10967529/60418720-46232f00-9ba9-11e9-9452-8e225801586f.PNG)

What is the proper way of getting sidebar menu categories? I can not find any documentation.

**Comment by xiaohuoni** [comment]
config/config.ts
```ts
routes: [
  {
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [

      {
        path: '/',
        name: 'welcome',
        icon: 'smile',
        component: './Welcome',
      },
      {
        path: '/dashboard',
        name: 'dashboard',
        component: '../layouts/MenuLayout',
        authority: ['admin', 'user'],
        routes: [
          {
            path: '/dashboard',
            redirect: '/dashboard/analysis',
          },
          {
            name: 'analysis',
            path: '/dashboard/analysis',
            component: './dashboard/analysis',
          },
        ]
      }]
  }]
```
