### ISSUE TITLE
面包屑在CMD+R刷新后会显示路由路径

### ISSUE THREAD

**Issue by mgcnrx11** [ant-design/ant-design-pro#469]
版本："version": "0.3.0"（commit: e111d7bfa9333cc1f8)

面包屑正常情况下是

![](https://ws1.sinaimg.cn/large/006tNc79gy1fmn27vm34oj30nu0bhaax.jpg)

在刷新后变成

![](https://ws3.sinaimg.cn/large/006tNc79gy1fmn292fz1sj30nt0c2my4.jpg)

在正常面包屑后多了路由的路径

**Comment by chenshuai2144** [comment]
#442  应该会一起修复... 稍微等等..

**Comment by afc163** [comment]
master 上已修复。
