### ISSUE TITLE
 error  in ./src/pages/.umi/router.js，  * ./node_modules/babel-loader/lib/index.js

### ISSUE THREAD

**Issue by chuang0815** [ant-design/ant-design-pro#4690]
PS D:\WorkSpaceReact\flight-offline-react\reactoffline> npm start

> ctrip-flight-offline@2.2.1 start D:\WorkSpaceReact\flight-offline-react\reactoffline
> cross-env APP_TYPE=site umi dev --port=8080

  build [==                  ] 10%Starting the development server...

  build [=================== ] 95%Theme generated successfully
Build completed in 13.09s

 ERROR  Failed to compile with 1 errors                                                                                                              16:16:34

 error  in ./src/pages/.umi/router.js

Module parse failed: Unexpected token (16:13)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   "component": __IS_BROWSER ? _dvaDynamic({
|     component: function component() {
>       return import(
|       /* webpackChunkName: "layouts__BasicLayout" */
|       '../../layouts/BasicLayout');

 @ ./src/pages/.umi/umi.js 77:48-67 184:2-186:4 184:32-186:3
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

 WAIT  Compiling...                                                                                                                                  16:16:35

Build completed in 0.868s

 ERROR  Failed to compile with 1 errors                                                                                                              16:16:36

 error  in ./src/pages/.umi/router.js

Module parse failed: Unexpected token (16:13)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   "component": __IS_BROWSER ? _dvaDynamic({
|     component: function component() {
>       return import(
|       /* webpackChunkName: "layouts__BasicLayout" */
|       '../../layouts/BasicLayout');

 @ ./src/pages/.umi/umi.js 49:36-58
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/4685 一样的问题
