### ISSUE TITLE
菜单选中色会覆盖标题

### ISSUE THREAD

**Issue by Ieeassassination** [ant-design/ant-design-pro#4692]
点击菜单如下
![企业微信截图_20190701165428](https://user-images.githubusercontent.com/15853557/60423507-f6804a00-9c20-11e9-87a0-82ff6e989205.png)

**Comment by xiaohuoni** [comment]
提供一下重现步骤或者demo

**Comment by Ieeassassination** [comment]
刚下载下来的项目，在config.ts中添加了几个路由，随后在pages中添加相关tsx文件，启动后就这样
![企业微信截图_20190702094356](https://user-images.githubusercontent.com/15853557/60476363-efebe400-9cad-11e9-8590-44f06f3c7c0f.png)

**Comment by chenshuai2144** [comment]
试试删除 dll 呢?

**Comment by WuJiY** [comment]
更新ant-pro-layout解决

**Comment by WuJiY** [comment]
#4678
