### ISSUE TITLE
GlobalHeader是否支持类似RightContent的LeftContent输入？

### ISSUE THREAD

**Issue by hauk0101** [ant-design/ant-design-pro#4693]
需求描述：
想在 GlobalHeader 左侧添加一个面包屑，即在折叠按钮的右边，添加一些自定义的内容。但是看了GlobalHeader 的源码和 DOM 结构，没有发现对应的入口。
问题：
1、现有 GlobalHeader 是否支持诸如 RightContent 的入口？
2、如果不支持，自定义组件应该如何添加呢？求个思路

**Comment by chenshuai2144** [comment]
> 现有 GlobalHeader 是否支持诸如 RightContent 的入口？

参考  rightContentRender.

**Comment by hauk0101** [comment]
@chenshuai2144 您好，请问参考 rightContentRender 的意思是，在 pro-layout 包里添加对应的 rightContentRender 吗？

**Comment by well-monkey** [comment]
解决了吗？我也遇见相同的需求了
