### ISSUE TITLE
使用antd pro写了一个后台管理系统，上线后第一次加载特慢

### ISSUE THREAD

**Issue by liuwang66** [ant-design/ant-design-pro#4694]
打包上线后，第一次加载或者强制刷新后加载，在网速一般的情况下，非常慢，有时候需要加载几十秒才显示，看了下文件加载情况，主要是两个文件 umi.js 和 vendors.async.js，一个400多kb,一个300kb

**Comment by liuwang66** [comment]
官方例子一样，https://preview.pro.ant.design/ ，是否可以优化？

**Comment by afc163** [comment]
400kb 和 300kb 一点也不大，请检查静态服务器的性能。

**Comment by jianhuihi** [comment]
![image](https://user-images.githubusercontent.com/4176545/66725969-fec76280-ee68-11e9-8aaa-dd78f6e18982.png)

**Comment by zhilianbi520** [comment]
@jianhuihi  我们也是。。。这个如何处理。。。nginx已开gzip ，依旧很大。。代码使用splitChunks也做了分割～！！感觉已经山穷水尽了
