### ISSUE TITLE
umi router编译报错

### ISSUE THREAD

**Issue by lvzheng0404** [ant-design/ant-design-pro#4695]
项目使用umi router  报错：
./node_modules/umi/lib/router.js
Module not found: Can't resolve '@tmp/history'

**Comment by xiaohuoni** [comment]
更新插件版本，umi锁包，而umi的plugin没锁包引起的

**Comment by lvzheng0404** [comment]
具体应该怎么更新呢，更新到哪个版本？ @xiaohuoni

**Comment by DucTrinhBk** [comment]
@xiaohuoni i get this error 
Module not found: Can't resolve '@tmp/history' in 'D:\react-apps\blog\node_modules\umi\dist'.How to deal with this???

**Comment by DucTrinhBk** [comment]
你可以早一点给我反馈吗。我是越南人，现在有了一个项目需要使用你们ant-design-pro,但我不知道从怎么开始，你可以给我指引好吗？对不起为了我汉语
