### ISSUE TITLE
This relative module was not found:  *../list/search in ./src/pages/.umi/router.js

### ISSUE THREAD

**Issue by silentcr** [ant-design/ant-design-pro#4697]
StepForm 里面会有个 index.js的文件

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/2879#issuecomment-439583112_

**Comment by silentcr** [comment]
我遇到了一个类似的问题：
在cnpm run fetch:blocks之后，运行，提示如下：
![L$F ~WW5UJN{$ S9E 23581](https://user-images.githubusercontent.com/16534748/60445825-930f1000-9c52-11e9-8bb5-4c3b95ca63c1.png)


而src/pages/list/search下确实没有文件，只有articles和projects这两个目录，分别对应相应模块,并且在router.js中都被导入了。
src/pages/.umi/router.js中导入的其他模块都是目录下有文件的，唯独这个../list/search里面没有文件，不知是不是这个原因引起的报错：
![86QU5X9SXE12H)FGGPN`N 4](https://user-images.githubusercontent.com/16534748/60446133-4972f500-9c53-11e9-8601-f00eab668196.png)

那么，这种情况应该怎样处理呢？

**Comment by xiaohuoni** [comment]
没有这个路由就从配置文件中去掉吧？

**Comment by chenshuai2144** [comment]
你在路由中配置了一个不存在的目录。删除掉就好了

**Comment by silentcr** [comment]
不对哎，每次删除之后一npm start就又恢复了，只有在npm启动之后修改才管用。
/src/pages/.umi/router.js这个文件是自动生成的吧？

**Comment by ruomanwei** [comment]
我也出现了这个问题，windows

**Comment by silentcr** [comment]
注意：要删除的组件是在config里面的，而不是.umi/router.js里的。.umi/router.js是依据config里的配置自动生成的，改完还会回去。
win里面没试过，但应该删掉可可以，我删完就行了。

**Comment by ihamlet** [comment]
如何解决呢  貌似这个问题居然关闭了

**Comment by ihamlet** [comment]
问题在config.ts

> 你在路由中配置了一个不存在的目录。删除掉就好了

我没有在路由配置任何不存在的目录啊  是在执行npm run fetch:block  再 run start 之后就报错了

**Comment by yinhaibo** [comment]
这个问题原因不知道，通过注释config/config.ts中的component就可以了。
```
path: '/list/search',
name: 'search-list',
//component: './list/search',
routes: []
```

**Comment by youqingxiaozhua** [comment]
> 你在路由中配置了一个不存在的目录。删除掉就好了

是通过`fetch:blocks`命令自动添加的，我看config文件里是设置了一个跳转，但是编译的时候却被当作了component？
config代码：

```
                    {
                      path: '/list/search',
                      redirect: '/list/search/articles',
                    },
```

**Comment by heyguo** [comment]
我这里出现这个问题时粗心大意造成的，
![image](https://user-images.githubusercontent.com/30069568/67157798-e4f3b700-f363-11e9-8540-a800de57763d.png)
