### ISSUE TITLE
AntD pro theme not fully loaded/applied

### ISSUE THREAD

**Issue by boukmi** [ant-design/ant-design-pro#4698]
Hello everyone,

I'm trying to customize AntD Pro theme by updating the `config/config.js` file.
I'm using a `them.js` file that contains the following rules:
```javascript
export default {
  'font-size-base': '12px',
  'primary-color': '#fa541c', // Orange

  // Card
  'card-padding-base': '20px',

  // Layout
  'layout-body-background'    : '#88d873', // Green

  // Form
  'form-item-margin-bottom': '14px',
  'label-color': '#8a959f',
}
```

The theme gets updated but not every rule is updated, for instance the `'layout-body-background'    : '#88d873', // Green` and I still get the default grey background color.
Also the primary button color does not get updated (see screenshot)

![image](https://user-images.githubusercontent.com/2116866/60448851-5a554380-9c1e-11e9-9cb7-6c17814a4a91.png)

Do you know why some rules are not overridden? And why my button is still showing in blue?

Thank you all for your help, I appreciate the work you're doing

**Comment by chenshuai2144** [comment]
I only support the replacement of the main color now, I am very sorry.
