### ISSUE TITLE
Allow dynamic route and code split configable

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#470]
并在发布部署那里增加相关文档说明。

**Comment by wunayou** [comment]
这个功能还是没有啊  如何让后端自由生成页面呢？

**Comment by chenshuai2144** [comment]
@wunayou  自由生成是什么意思?

**Comment by afc163** [comment]
@chenshuai2144 这块明天能搞定么？默认 code split 现在给内部发布流程带来很大的困扰，可配置后默认关闭好了。

**Comment by chenshuai2144** [comment]
@afc163  没有问题. 明天上午12点左右提交

**Comment by afc163** [comment]
@WhatAKitty

**Comment by wunayou** [comment]
@chenshuai2144    就是说地址相同 但是加载组件可以不同   或者地址不同 加载相同的组件， 让后台根据参数 生成

**Comment by chenshuai2144** [comment]
这个应该用模板生成器吧....
前后端分离的后台只能提供一下数据这些的...
你可以试着自己生成meun.js

**Comment by yesmeck** [comment]
能不能默认就不用动态加载。代码里留下比较方便的做动态加载的可能性和注释加文档。

**Comment by afc163** [comment]
对，这是这个 issue 的目标。

**Comment by chenshuai2144** [comment]
如果用代码的方法实现..改动太大了.

**Comment by afc163** [comment]
书写方式统一，默认关闭，一键打开。

打包成一个文件对于部署方式的技术要求会简单很多。

**Comment by chenshuai2144** [comment]
babel得方式行不通, 我还没进行处理了 
代码已经变成
`Promise.resolve().then(() => require('model'));`
webpack插件受限于roadhog 添加不上去.

**Comment by afc163** [comment]
直接处理 `Promise.resolve().then(() => require('model'));` 如何？

**Comment by chenshuai2144** [comment]
怎么处理？
webpack内部改一个参数就可以解决。。
要不直接去给webpack pr把。。。
https://github.com/webpack/webpack/issues/5029 
这个issue就是这方面的。

**Comment by afc163** [comment]
把 `Promise.resolve().then(() => require('model'));` 换成 `require('model')`

**Comment by chenshuai2144** [comment]
让我试一试。 好像没有别人想要去掉代码分割。都是教怎么开启代码分割的。

**Comment by chenshuai2144** [comment]
又失败了 。看见babel就恶心。。。。。

**Comment by chenshuai2144** [comment]
现在觉得写备注也能接受了

**Comment by sorrycc** [comment]
通过 babel 插件改代码就好了吧。

**Comment by afc163** [comment]
@sorrycc 看看有没有必要把 #562 的功能内建了。

**Comment by sorrycc** [comment]
可以，加个 `disableDynamicImport` 的配置吧。

**Comment by sorrycc** [comment]
> @sorrycc 看看有没有必要把 #562 的功能内建了。

加上了。

**Comment by afc163** [comment]
貌似 https://github.com/ant-design/ant-design-pro/blob/40e95db18f63140fa3cd23af14eaea071511bd3f/src/common/router.js#L13-L53 这段判断还需要存在，单纯的开启 disableDynamicImport 会报错。

**Comment by sorrycc** [comment]
这应该就加在 antd-design-pro 里吧。
