### ISSUE TITLE
紧急求助。build之后的文件放到tomcat根目录出现先这个提示了。以前还是好好的。就把antd升级到最新的了，其他没改过

### ISSUE THREAD

**Issue by blackboy1987** [ant-design/ant-design-pro#4700]
![image](https://user-images.githubusercontent.com/6405701/60476237-66d4ad00-9cad-11e9-8726-322653e36292.png)

**Comment by chenshuai2144** [comment]
编译的时候打开一下devtools. 这个看起来像是 api 的 json 转化失败造成的

**Comment by zhangshuai0101** [comment]
您好 想问下您这边部署到tomcat需要前端做什么配置吗？我现在放到tomcat下访问404

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn

**Comment by zhangshuai0101** [comment]
> https://pro.ant.design/docs/deploy-cn

@chenshuai2144 帅哥 我前端配置文件是这样的，采用browserHistory
![image](https://user-images.githubusercontent.com/40013310/63683851-13568980-c82e-11e9-8a14-6d38e1058624.png)，然后后端按文档配置好之后，启动tomcat 访问地址localhost:8080/pages/view/login 404
