### ISSUE TITLE
新建项目拉去所有block失败

### ISSUE THREAD

**Issue by heyangjiedd** [ant-design/ant-design-pro#4701]
新建项目出现两个问题，使用yarn create umi创建后，能够运行。需要拉去所有block做本地演示。

- 执行yarn run fetch:blocks后出现spinner.error is not a function。
![1562033299](https://user-images.githubusercontent.com/22470360/60478303-c7b3b380-9cb4-11e9-838d-021a2381970e.jpg)

- 删除spinner.error()这一行代码，重新执行yarn run fetch:blocks后出现BasicLayout.tsx文件找不到，代码创建后BasicLayout.jsx。
![1562033203(1)](https://user-images.githubusercontent.com/22470360/60478278-b8cd0100-9cb4-11e9-9a1e-0ec2325a8f0a.jpg)

**Comment by chenshuai2144** [comment]
对 js 的支持不好。我改一下

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-cli#readme

已经支持，可以在安装这个包 来进行使用
