### ISSUE TITLE
查询表格小bug

### ISSUE THREAD

**Issue by tcyufeng** [ant-design/ant-design-pro#4702]
查询条件-规则名称中输入查询内容，任意选择一条记录点击配置，弹出框中的规则名称是查询内容
![1562035447766](https://user-images.githubusercontent.com/28287106/60478837-612f9500-9cb6-11e9-86ee-2107286ffdec.jpg)

**Comment by chenshuai2144** [comment]
共用了一个 form 的原因。

**Comment by Benpaodejiezai** [comment]
> 共用了一个 form 的原因。

暂时有什么解决办法吗？或是等修复？

**Comment by tcyufeng** [comment]
不要传入form，在UpdateForm中Form.create

**Comment by Benpaodejiezai** [comment]
> 不要传入form，在UpdateForm中Form.create

可以粘端代码吗？我也尝试了  Form.create 没成功。。。

**Comment by tcyufeng** [comment]
export default Form.create<UpdateFormProps>()(UpdateForm);

**Comment by tcyufeng** [comment]
`export default Form.create<UpdateFormProps>()(UpdateForm);`

**Comment by Benpaodejiezai** [comment]
> `export default Form.create<UpdateFormProps>()(UpdateForm);`

我是这么写的，可能是用的不对，帮忙看一下呗~
const CreateFrom: React.FC<CreateFormProps> = props => {
  const { form } = props;
  const { modalVisible, handleAdd, handleModalVisible } = props;
  const okHandle = () => {
    form.validateFields((err: any, fieldsValue: any) => {
      if (err) return;
      form.resetFields();
      handleAdd(fieldsValue);
    });
  };
  return (
    <Modal
      destroyOnClose
      maskClosable={false}
      title="新建"
      visible={modalVisible}
      onOk={okHandle}
      onCancel={() => handleModalVisible()}
    >
      <FormItem labelCol={{ span: 5 }} wrapperCol={{ span: 15 }} label="编码">
        {form.getFieldDecorator('addTypeCode', {
          rules: [{ required: true, message: '请输入编码！' }],
        })(<Input placeholder="请输入" />)}
      </FormItem>
    </Modal>
  );
};

export default Form.create<CreateFormProps>()(CreateFrom);

**Comment by tcyufeng** [comment]
`const CreateForm = Form.create(props=>{})`
这样试试

**Comment by Benpaodejiezai** [comment]
> `const CreateForm = Form.create(props=>{})`
> 这样试试
改好了，谢谢你的帮助
