### ISSUE TITLE
tabs选项卡下动态生成TabPane，TabPane下的内容调用父组件form，

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design-pro#4703]
tabs选项卡TabPane内容动态生成form，生成的子组件内调用父组件的form生成表单，如果这时使用@connect  使用父组件form.getFieldDecorator的input，就会无法输入。

**Comment by chenshuai2144** [comment]
来个可重现的 demo。

**Comment by k983551019** [comment]
不知道该如何用codepen.io重现，因为还需要使用到dva connect

**Comment by k983551019** [comment]
> 来个可重现的demo。

不知道该如何用codepen.io重现，因为还需要使用到dva connect

**Comment by chenshuai2144** [comment]
做个项目，然后给我们 github 的地址

**Comment by k983551019** [comment]
> 做个项目，然后给我们github的地址

https://github.com/k983551019/ant-design-pro-2.git  里面有2个导航，第一个是我写的，第二个是项目中复制的， 两个还不一样，第一个是注释了connect 也不能输入，第二个是注释了可以输入

**Comment by chenshuai2144** [comment]
你这个用法是错误的。
form 本质上是更新 state。现在因为你的嵌套用法造成了 组件无法更新。
你如果需要这样用最好是再封装一层。

**Comment by k983551019** [comment]
> 你这个用法是错误的。
> form 本质上是更新 state。现在因为你的嵌套用法造成了 组件无法更新。
> 你如果需要这样用最好是再封装一层。

封装一层什么？form表单？或者对于tabs下这种多form 有没有什么其他解决的办法

**Comment by chenshuai2144** [comment]
一个 tabpanel 用一个表单是最好的方案。每个 tabPanel 都封装成一个组件

**Comment by k983551019** [comment]
都说了是动态生成的tabpane 怎么去封装某个？






------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 中午12:18
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "择一城而终老丶"<983551019@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] tabs选项卡下动态生成TabPane，TabPane下的内容调用父组件form， (#4703)




一个 tabpanel 用一个表单是最好的方案。每个 tabPanel 都封装成一个组件
