### ISSUE TITLE
官网访问 api 404 的问题 

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#4705]
由于我们切换了官网的部署方案。有部分 api 失效。尤其是有 pwa 缓存的用户可能会报错 api 404。由于 pwa 缓存清除的不及时性。需要人工来强制让缓存失效。

打开 google  控制面板如下图所示：

![image](https://user-images.githubusercontent.com/8186664/60480354-dfdb0100-9cbb-11e9-8109-e34f7ba4d732.png)

点击 unregister,并重启浏览器即可让缓存彻底失效

**Comment by xiaohuoni** [comment]
想搞一个静态化部署方案（2333）还能省一个服务的钱

**Comment by chenshuai2144** [comment]
静态化的方案查看不了 api 了，在控制台中看不见

**Comment by poyiding** [comment]
点击 unregister,并重启浏览器即可让缓存彻底失效 , 操作后还是一样404

**Comment by handyzhang** [comment]
> 点击 unregister,并重启浏览器即可让缓存彻底失效 , 操作后还是一样404

- -  我好像可以了  unregister后都没重启浏览器也生效了。。

**Comment by nightmaring** [comment]
看图片的第一样还以为是什么开发工具。。

**Comment by Baifangchi** [comment]
这用的啥工具啊，小白不会啊

**Comment by chenshuai2144** [comment]
这是 google 浏览器的 devTool

**Comment by JackZhang0817** [comment]
我unregister之后就一直在加载中

**Comment by JackZhang0817** [comment]
> 我unregister之后就一直在加载中

可以了，现在加载慢了，应该是我的网的原因

**Comment by Fled8617** [comment]
4.0没有pwa了么，为什么现在保存不了pwa网页了，chrome

**Comment by gensir** [comment]
@chenshuai2144  pwa 还可以使用吗，在umi@3 中

**Comment by chenshuai2144** [comment]
可以的，用法没变化
