### ISSUE TITLE
长时间不操作浏览器以后，再次请求后台接口获取数据，时间增加

### ISSUE THREAD

**Issue by xuyy133** [ant-design/ant-design-pro#4706]
离开页面几分钟以后，再次返回页面下发请求时，会出现获取后台数据时间增加问题，这个是什么原因？怎么解决？

**Comment by chenshuai2144** [comment]
这个应该找后端同学排查一下吧。和我们前端关系不大的

**Comment by xuyy133** [comment]
这种情况很有规律，并不是只有一个页面、一个浏览器出现，而且还是不同的接口，不同后台，规律性出现这种问题

**Comment by chenshuai2144** [comment]
抓个包试试。这种事情也很神奇
