### ISSUE TITLE
Table带参数scroll之后 参数size="small" 失效  ,

### ISSUE THREAD

**Issue by huangjiangit** [ant-design/ant-design-pro#471]
首先感谢蚂蚁金服提供的脚手架；

当Table参数中有scroll参数时  或者columns参数中有 fixed参数(例如:  fixed:'left' )时，

设置size="small" 没有效果 表格样式 翻页之后都出问题了

当我去掉上面那些scroll和fixed 之后  ,设置size="small"才生效.

是我的问题还是咋滴拉，还望回复！

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/8577
