### ISSUE TITLE
打开页面后，F5刷新，报错

### ISSUE THREAD

**Issue by 744934982** [ant-design/ant-design-pro#4712]
![image](https://user-images.githubusercontent.com/18650301/60499629-71159c00-9ceb-11e9-8351-2e852ef0bcf7.png)
![image](https://user-images.githubusercontent.com/18650301/60499648-7b379a80-9ceb-11e9-9619-ad033404f46b.png)
![image](https://user-images.githubusercontent.com/18650301/60499659-82f73f00-9ceb-11e9-8ad7-633b2599645d.png)

**Comment by WuJiY** [comment]
是的  打开Drawer 还与这个报错
`Warning: Received `true` for a non-boolean attribute `visible`.

If you want to write it to the DOM, pass a string instead: visible="true" or visible={value.toString()}.
    in div (created by Drawer)
    in Drawer (created by Context.Consumer)
    in Drawer (created by Context.Consumer)
    in withConfigConsumer(Drawer) (created by PageCategoryPatch)
    in PageCategoryPatch (created by PageCategory)
    in div (created by PageCategory)
    in div (created by PageCategory)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Card (created by PageCategory)
    in div (created by PageHeaderWrapper)
    in div (created by Context.Consumer)
    in GridContent (created by PageHeaderWrapper)
    in div (created by PageHeaderWrapper)
    in PageHeaderWrapper (created by PageCategory)
    in PageCategory (created by Connect(PageCategory))
    in Connect(PageCategory) (created by Form(Connect(PageCategory)))
    in Form(Connect(PageCategory)) (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Route)
    in Switch (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Component)
    in Switch (created by Component)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Adapter (created by ContainerQuery)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by ContainerQuery)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by ContainerQuery)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by DynamicComponent)
    in DynamicComponent (created by Component)
    in Component (created by Component)
    in Authorized (created by AuthComponent)
    in AuthComponent (created by Connect(AuthComponent))
    in Connect(AuthComponent) (created by Component)
    in Component (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by ret)
    in ret (created by Route)
    in Switch (created by Route)
    in div (created by Layout)
    in Layout (created by DynamicComponent)
    in DynamicComponent (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by _DvaContainer)
    in _DvaContainer`

**Comment by WuJiY** [comment]
[#17387](https://github.com/ant-design/ant-design/issues/17387)
