### ISSUE TITLE
git clone 代码后运行，修改主题无反应

### ISSUE THREAD

**Issue by 744934982** [ant-design/ant-design-pro#4713]
![image](https://user-images.githubusercontent.com/18650301/60499986-1af52880-9cec-11e9-8f1b-2ac5006c3fc6.png)

**Comment by ZylFrank** [comment]
我也发现了该问题：
"version": "2.3.1",
只有主题色无法修改

**Comment by chenshuai2144** [comment]
你需要在 setting.json 中做配置，主题色因为换主题插件会默认设置为setting 中的

**Comment by dongkeng001** [comment]
> setting

V2分支也是同样问题，代码clone下来，装完依赖包跑起来后主题色更改没反应，你说的setting.json，我在全文件检索都没找到这个文件
