### ISSUE TITLE
Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead

### ISSUE THREAD

**Issue by panghaoyuan** [ant-design/ant-design-pro#4717]
`Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead.

The above error occurred in the <DynamicComponent> component:
`

已经在config.js里面设置了

`targets: {
    ie: 9,
  },`

IE9下还是报错无法运行.我看了其他的issues也没有找到可以解决的方案.

**Comment by panghaoyuan** [comment]
> `Warning: The component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead.
> 
> The above error occurred in the component:
> `
> 
> 已经在config.js里面设置了
> 
> `targets: { ie: 9, },`
> 
> IE9下还是报错无法运行.我看了其他的issues也没有找到可以解决的方案.

使用的是V2版不是V4

**Comment by chenshuai2144** [comment]
报错应该不是这个，这个是个 warning

**Comment by panghaoyuan** [comment]
> 报错应该不是这个，这个是个 warning

![image](https://user-images.githubusercontent.com/28645409/60561811-7e806400-9d87-11e9-9526-2fc9c0750079.png) 报错是这个.

**Comment by chenshuai2144** [comment]
试着关掉代码分割吧
https://github.com/ant-design/ant-design-pro/blob/d5b504647d36f27e7916be34905b77604679d705/config/config.ts#L32

**Comment by panghaoyuan** [comment]
> 试着关掉代码分割吧
> https://github.com/ant-design/ant-design-pro/blob/d5b504647d36f27e7916be34905b77604679d705/config/config.ts#L32

![image](https://user-images.githubusercontent.com/28645409/60563279-ba1e2c80-9d8d-11e9-8625-abdf45234b04.png)
![image](https://user-images.githubusercontent.com/28645409/60563295-cb673900-9d8d-11e9-937a-ff2e406de99b.png)
出现新的错误

**Comment by panghaoyuan** [comment]
> 试着关掉代码分割吧
> https://github.com/ant-design/ant-design-pro/blob/d5b504647d36f27e7916be34905b77604679d705/config/config.ts#L32

![image](https://user-images.githubusercontent.com/28645409/60571922-0b86e580-9da7-11e9-8bc9-1e043d71d5e5.png)

注释掉了,错误依旧存在

**Comment by chenshuai2144** [comment]
估计是用的库不支持，umi  antd 是支持 ie9 的

**Comment by panghaoyuan** [comment]
> 估计是用的库不支持，umi antd 是支持 ie9 的
> 但是 pro 依赖第三方库不是的

![image](https://user-images.githubusercontent.com/28645409/60576756-95877c00-9db0-11e9-85da-70040bcb37d2.png)

这里关闭产生了效果...感谢.. 


>
