### ISSUE TITLE
怎么做全屏页面

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#4718]
需要一个集成一个大屏展示界面，现在不知道什么方案比较合理？
1. 集成到menu菜单， 通过一个全屏按钮控制全屏，但是非全屏显示比较奇怪。
2. 在登录页面和菜单页中间加一个路由， 登录之后直接进入大屏， 通过大屏内部的菜单跳转到菜单页，这个路由怎么加？

希望各位给出一些宝贵意见， 包括大屏可视化有没有什么很好的方案，这一块第一次做。

**Comment by chenshuai2144** [comment]
你可以用 https://electronjs.org/ ，chrome 不能完美实现你的方案的

**Comment by Hericium** [comment]
有办法的，登录之后，直接跳转public的静态页面，再重静态页面里面跳回就好了。public文件下的静态页面就可以是全屏的页面了

**Comment by tangfeibiao** [comment]
> 需要一个集成一个大屏展示界面，现在不知道什么方案比较合理？
> 
> 1. 集成到menu菜单， 通过一个全屏按钮控制全屏，但是非全屏显示比较奇怪。
> 2. 在登录页面和菜单页中间加一个路由， 登录之后直接进入大屏， 通过大屏内部的菜单跳转到菜单页，这个路由怎么加？
> 
> 希望各位给出一些宝贵意见， 包括大屏可视化有没有什么很好的方案，这一块第一次做。

你好，有可行的方案没呢？你后来是怎么实现的呢？

**Comment by yoyo837** [comment]
HTML5 Full Screen API.

**Comment by tangfeibiao** [comment]
解决方案:
https://antd-plus.alitajs.com/

**Comment by jeffmxzhao** [comment]
@tangfeibiao got it

**Comment by 756370340** [comment]
> https://antd-plus.alitajs.com/components/full-screen

404了 老哥
