### ISSUE TITLE
The docs described error

### ISSUE THREAD

**Issue by Fiv5** [ant-design/ant-design-pro#472]
#### The official document's description:
![2017-12-20_164010](https://user-images.githubusercontent.com/23014093/34198387-2eeb56a2-e5a5-11e7-8528-2f6130e998b3.png)

#### To be:
> **getRouteData** 是 **src/router.js** 中的方法

**Comment by ddcat1115** [comment]
fixed in https://github.com/ant-design/ant-design-pro-site/commit/4af4a251b8f135032ff535491ed04efc874ba6b7
