### ISSUE TITLE
关于eslint不报错阻止提交问题。

### ISSUE THREAD

**Issue by ShawDanon** [ant-design/ant-design-pro#4720]
package中配置为
"lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
所以src以外报错是没有提示的，然后提交也提交不了。
修改为
"lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./",
能够看到错误，修改后正常提交

**Comment by chenshuai2144** [comment]
来个 pr 吧
