### ISSUE TITLE
TypeError: Cannot read property 'Provider' of undefined

### ISSUE THREAD

**Issue by drduan** [ant-design/ant-design-pro#4722]
![image](https://user-images.githubusercontent.com/7875572/60570133-77ffe580-9da3-11e9-8c5f-23cdebe283b3.png)
这个错有点看不懂 大神指教

**Comment by chenshuai2144** [comment]
react 的版本太低？

**Comment by drduan** [comment]
不是 配置都改成v4的了、应该是别的地方改错了

**Comment by chenshuai2144** [comment]
升级一下 umi 的插件
