### ISSUE TITLE
v4 连接服务器登陆 重复发送2次请求

### ISSUE THREAD

**Issue by JeremyDa** [ant-design/ant-design-pro#4723]
环境：使用master分支，v4版
向后台服务器发送请求时，同一请求会重复发送2次
<img width="820" alt="WX20190703-154327@2x" src="https://user-images.githubusercontent.com/8288208/60574154-9ff34700-9dab-11e9-8cd4-f28bcff03476.png">

**Comment by liweitao92** [comment]
cors，跨域请求了吧

**Comment by guotingchaopr** [comment]
密码框回车和默认提交被同时触发了

**Comment by chenshuai2144** [comment]
目测是跨域

**Comment by JeremyDa** [comment]
v2版本 跨域也没见重复发2次请求啊，这不是bug吗

**Comment by chenshuai2144** [comment]
你看看你的请求，如果是跨域，一次是 Option 一次是 Post

**Comment by afc163** [comment]
similar with https://github.com/dvajs/dva/issues/2145

**Comment by JeremyDa** [comment]
> 你看看你的请求，如果是跨域，一次是 Option 一次是 Post

一次登录操作，发了4个请求，如上图，前2个200是option，后2个401是post，是重复发了2次吗

**Comment by afc163** [comment]
https://juejin.im/post/5b14a3f76fb9a01e72512101

**Comment by afc163** [comment]
https://www.google.com/search?newwindow=1&client=firefox-b-d&ei=aOAiXcuSFcn8wAOg66DYCg&q=option+post+%E4%B8%A4%E6%AC%A1%E8%AF%B7%E6%B1%82&oq=option+post+%E4%B8%A4%E6%AC%A1%E8%AF%B7%E6%B1%82&gs_l=psy-ab.3...5414.11173..11327...10.0..0.187.2433.0j18......0....1..gws-wiz.......0j0i30j0i10i30j0i8i30j0i8i10i30j33i160.E3ZFxqxrbvQ

**Comment by JeremyDa** [comment]
> https://juejin.im/post/5c46af87e51d4552232feaeb
> https://juejin.im/post/5b14a3f76fb9a01e72512101
> https://www.cnblogs.com/virtual/p/3720750.html

你发的这些是解释跨域为什么发option和post。
我问的是输入密码登录回车为什么发了4次(2次option+2次post)，见上图。

看了源码，<Password> onPressEnter 缺少e.preventDefault()，已提交pr到umi-blocks
<img width="668" alt="WX20190708-155324@2x" src="https://user-images.githubusercontent.com/8288208/60792589-8af62980-a198-11e9-841e-391a354f36ba.png">

**Comment by JeremyDa** [comment]
> 你看看你的请求，如果是跨域，一次是 Option 一次是 Post

和跨域没关系
<Password> onPressEnter 的时候漏了e.preventDefault();
