### ISSUE TITLE
在BasicLayout.tsx中使用SettingDrawer组件控制台报错

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#4724]
是用法不对吗？下面是代码：
![20190703160644](https://user-images.githubusercontent.com/33716687/60574715-a209d580-9dac-11e9-8186-6dfcf7854432.jpg)

下面是浏览器报的错误信息：
![20190703160706](https://user-images.githubusercontent.com/33716687/60574771-c6fe4880-9dac-11e9-8c96-35d8d40c5302.jpg)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4712

重复了
