### ISSUE TITLE
build完成后用nginx部署报Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by bobo717** [ant-design/ant-design-pro#4725]
nginx配置：
`server {
        listen       8001;
	
	# gzip config
    	gzip on;
    	gzip_min_length 1k;
    	gzip_comp_level 9;
    	gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    	gzip_vary on;
    	gzip_disable "MSIE [1-6]\.";

	#server_name  www.XXX.com;
	charset UTF-8;
	root /usr/www/node/admin/;

    	location / {
            # 用于配合 browserHistory使用
            try_files $uri $uri/ /index.html;
    	}
	location /api {
            proxy_pass https://www.XXX.com;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   Host              $http_host;
            proxy_set_header   X-Real-IP         $remote_addr;
    	}
    }`

ant design pro本地代理配置：
`proxy: {
    '/api': {
      target: 'https://www.XXX.com/',
      changeOrigin: true,
      pathRewrite: { '^/api': '' },
    },
  },`

**Comment by bobo717** [comment]
另一个帖子写是代理错误，我搞不明白我这代理配置错在哪？

**Comment by chenshuai2144** [comment]
> Unexpected token < in JSON at position 0

你最好有详细的报错。

给我一个可重现的仓库。

**Comment by bobo717** [comment]
> > Unexpected token < in JSON at position 0
> 
> 你最好有详细的报错。
> 
> 给我一个可重现的仓库。

![报错图片](https://www.iyougx.com/img/zhongyin/1562142351851.jpg)

**Comment by bobo717** [comment]
升级4.0后问题解决
