### ISSUE TITLE
v4手动创建页面的model导入

### ISSUE THREAD

**Issue by chenjiangyo** [ant-design/ant-design-pro#4726]
新建的页面使用@connect导入model数据失败，网上说要在src/index.js中注册，但是新版的没有这个index文件，，，大神们帮帮忙

**Comment by chenshuai2144** [comment]
只需要放在 modal 文件夹下，或者page/xxx/mode.js 都会自动引入的

**Comment by chenjiangyo** [comment]
感谢 ，问题解决了
