### ISSUE TITLE
onGetG2Instance时间点同渲染关系

### ISSUE THREAD

**Issue by denissduan** [ant-design/ant-design-pro#4727]
需要做一个饼图自动定时选中一部分轮播的效果。
做饼图的选中操作时，为何需要延迟2秒以上才能拿到具体实例操作成功？少于两秒好像都不行？
<Chart
onGetG2Instance = {chart => {
setTimeout(function(){
const gemos = chart.getAllGeoms()[0];
gemos.setShapeSelected(gemos.getShapes()[0], true);
}, 2000);
}
}   
   onGetG2Instance 按照文档说明：获取 chart 实例的回调。每当生成一个新 chart 时就会调用该函数，并以新生成的 chart 作为回调参数。想确认下这个方法触发时是一定等到饼图完全渲染完成才会触发，还是饼图实例一旦生成就会触发？
    因为如果不在onGetG2Instance中设置setTimeout延时一定时间的话，gemos.getShapes()返回的是一个空数组，也就说明这个时候饼图还没开始渲染，或渲染完成。

**Comment by chenshuai2144** [comment]
去 bizchart 问一下吧，我没听懂
