### ISSUE TITLE
v4版本动态菜单与路由匹配的问题

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design-pro#4728]
从服务端拿到按照antd-design-pro官网定义的数据格式，正常渲染了菜单，点击某个菜单选项，报的404，动态渲染菜单如何匹配到菜单选项对应的页面组件

**Comment by liangyongrui** [comment]
#4691 类似问题，我解决了

**Comment by LiYanGang** [comment]
> #4691 类似问题，我解决了

抱歉啊，我按照你的步骤没成功，能否给一个示例代码呢？

**Comment by LiYanGang** [comment]
> > #4691 类似问题，我解决了
> 
> 抱歉啊，我按照你的步骤没成功，能否给一个示例代码呢？



> #4691 类似问题，我解决了

![屏幕快照 2019-07-03 下午7 15 44](https://user-images.githubusercontent.com/20022163/60587453-0df93780-9dc7-11e9-878d-c082c87e2330.png)
我模拟改变routes，但是还是不起作用

**Comment by chenshuai2144** [comment]
你后端传入的 path 要和 config.js 中的path 相同，不然就会 404
