### ISSUE TITLE
新建数据，向子页面传 form 的相关问题

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4731]
问题1：向子页面传form后，在控件里输入数据会影响到父页面的输入框（PS：官方示例pro-blocks-master/ListTableList 也有此问题，不过避开了，父页面检索条件与子页面添加的数据没有相同的字段）
![image](https://user-images.githubusercontent.com/51696361/60636253-4f7df700-9e48-11e9-9d3c-711270291a12.png)
![image](https://user-images.githubusercontent.com/51696361/60636261-56a50500-9e48-11e9-9e5a-e6c9bf0ba124.png)

**Comment by Benpaodejiezai** [comment]
问题2：父页面检索是可以为空的，但却会执行子页面的 form 校验，导致查询动作被中断
![image](https://user-images.githubusercontent.com/51696361/60636346-a8e62600-9e48-11e9-88bd-b4a2e7cb3679.png)
![image](https://user-images.githubusercontent.com/51696361/60636350-aedc0700-9e48-11e9-806d-47c25326d1ce.png)

**Comment by chenjiangyo** [comment]
我也有这个问题，我是用 指定校验的方式解决的。

**Comment by Benpaodejiezai** [comment]
> 我也有这个问题，我是用 指定校验的方式解决的。
求代码，万分感谢！

**Comment by chenjiangyo** [comment]
form.vaildateFields((err,values) =>{})这个是校验form的全部表单 子组件的form是父组件传过去的
 我的方式是
form.vaildateFields([要校验的属性],(err,values)=>{})

**Comment by Benpaodejiezai** [comment]
> form.vaildateFields((err,values) =>{})这个是校验form的全部表单 子组件的form是父组件传过去的
> 我的方式是
> form.vaildateFields([要校验的属性],(err,values)=>{})

那第一个问题，怎么解决呢

**Comment by chenjiangyo** [comment]
你那是两个input的name属性一样引起的

**Comment by Benpaodejiezai** [comment]
解决方案：不传 form 子页面使用 Form.create
