### ISSUE TITLE
v4 初始的权限

### ISSUE THREAD

**Issue by chenjiangyo** [ant-design/ant-design-pro#4733]
初始的权限是什么 ， 一开始使用/list/table-list 能直接进去。求。。。

**Comment by chenshuai2144** [comment]
默认是 admin

**Comment by chenjiangyo** [comment]
我用getAuthority()在 Authorized.tsx中打印的是user.. 而且islogin初始时是空..到后面第二次渲染的时候才有值,但是BasicLayout.tsx中的'user/fetchCurrent'接口不是同步的吗 应该第一次就有值啊..

**Comment by chenshuai2144** [comment]
所有的就接口请求都是异步的。

**Comment by chenjiangyo** [comment]
> 
> 
> 所有的就接口请求都是异步的。

理解清楚了 万分感谢。
