### ISSUE TITLE
table可编辑里用inputnumbel组件会出现上下箭头

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design-pro#4734]
![QSPDC 7E@S 75@DY5)@P$IQ](https://user-images.githubusercontent.com/48147837/60637442-07ad9e80-9e4d-11e9-8c0d-79e2ca7c1f99.png)

**Comment by chenshuai2144** [comment]
inputNumber 自带箭头的。你可以用 css 删掉他。
https://ant.design/components/input-number-cn/

**Comment by chenshuai2144** [comment]
zindex 的问题 antd 中已经修复了。你可以更新一下你的包
