### ISSUE TITLE
preview.pro.ant.design 无法正常访问

### ISSUE THREAD

**Issue by cylin2000** [ant-design/ant-design-pro#4735]
https://preview.pro.ant.design 无法正常访问，应该是1小时前左右的部署导致的

**Comment by cylin2000** [comment]
页面会显示下面错误，头像无法显示
请求错误 404: https://preview.pro.ant.design/api/notices
发出的请求针对的是不存在的记录，服务器没有进行操作。

**Comment by chenshuai2144** [comment]
再试试

**Comment by cylin2000** [comment]
现在可以了，非常感谢

**Comment by kambleaa007** [comment]
I am facing same error
