### ISSUE TITLE
Ant-design-pro

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4736]
![image](https://user-images.githubusercontent.com/44084004/60642288-ef944a00-9e61-11e9-850d-88fc568dc976.png)
 Ant-design-pro 2.0 打开报这样错误，请问有人遇到过吗？

**Comment by chenshuai2144** [comment]
drawer 的问题。
看这里 https://github.com/ant-design/ant-design-pro/issues/4712
