### ISSUE TITLE
面包屑问题点击跳转

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#4738]
<img width="481" alt="屏幕快照 2019-07-04 下午3 47 37" src="https://user-images.githubusercontent.com/183884/60648767-3179bc00-9e73-11e9-8357-fbe4cebbfed4.png">
<img width="892" alt="屏幕快照 2019-07-04 下午3 49 02" src="https://user-images.githubusercontent.com/183884/60648797-448c8c00-9e73-11e9-8046-03f255ef728b.png">

> 之前版本好像是点击没有用的，现在可以点击了。但是点击会跳转空白页，是不是路由那边设置错了

**Comment by hst-Sunday** [comment]
我也遇到这个问题，请问你是怎么解决的呢?

**Comment by chenshuai2144** [comment]
可以通过 Layout 的 itemRender 来自定义。

https://ant.design/components/breadcrumb-cn/#%E5%92%8C-browserHistory-%E9%85%8D%E5%90%88

**Comment by pxim** [comment]
> 可以通过 Layout 的 itemRender 来自定义。
> 
> https://ant.design/components/breadcrumb-cn/#%E5%92%8C-browserHistory-%E9%85%8D%E5%90%88

在v5版本里，没找到添加这个的地方？
