### ISSUE TITLE
TypeError: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by liang0213** [ant-design/ant-design-pro#4739]
Unhandled Rejection (TypeError): Cannot read property 'dispatch' of undefined

**Comment by liang0213** [comment]
TypeError: Cannot read property 'dispatch' of undefined
Unhandled Rejection (TypeError): Cannot read property 'dispatch' of undefined
down 下来后cnpm install 后,cnpm start 启动后报错
![image](https://user-images.githubusercontent.com/13412697/60678151-25fbb480-9eb6-11e9-9e90-1c07357488c9.png)

**Comment by liang0213** [comment]
移除package.json 中的redux 就可以了

**Comment by symbiot-india** [comment]
When I run the dev server, I get this error sometimes and other times it works fine. But is there a permanent fix to this as I'm unable to expect when the error will be thrown? The solution suggested by @liang0213  doesn't work for me.

**Comment by i-wangcj** [comment]
> 移除package.json 中的redux 就可以了

我也碰到这个问题，但删除了package.json中redux还是报这个错误。高手能指点下么。

**Comment by popingpaul** [comment]
this happend only when using VSCode command Windows. change another CMD and run server. it's ok
for me at least.

**Comment by lin-lang** [comment]
> this happend only when using VSCode command Windows. change another CMD and run server. it's ok
> for me at least.

yep, work for me too. Switch default terminal to PowerShell and problem solved.
