### ISSUE TITLE
Table的底部汇总问题有人遇到过吗?如图

### ISSUE THREAD

**Issue by liyangchiyue** [ant-design/ant-design-pro#474]
1.问题
a.需要在table底部增加汇总统计。(图1)
2.已做尝试
a.在footer中增加数据列(不能满足需求)
b.在datasource增加一行数据(分页会出现)

![image](https://user-images.githubusercontent.com/8132004/34236741-e29b3c9c-e633-11e7-91d0-310b02fcc835.png)
(图1)

![image](https://user-images.githubusercontent.com/8132004/34236745-e70bc29c-e633-11e7-991f-96cc4eefdb69.png)
(图2)

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/5710

**Comment by LDD123** [comment]
请问你解决了吗@liyangchiyue
