### ISSUE TITLE
RangePicker 月份显示英文，请问如何处理？

### ISSUE THREAD

**Issue by jlq023** [ant-design/ant-design-pro#4740]
一：问题描述
![date1](https://user-images.githubusercontent.com/32348538/60692458-b1059a80-9f08-11e9-87b5-c6a095a6f079.png)
我使用RangePicker组件，无法将RangePicker设置为中文，并且已经在组件外使用LocaleProvider,
部分代码如下：
import moment from 'moment';
import {DatePicker } from 'antd';
const { RangePicker } = DatePicker;
import zhCN from 'antd/es/locale-provider/zh_CN';
import 'moment/locale/zh-cn';
moment.locale('zh-cn'); 

LocaleProvider locale={zhCN}
RangePicker locale={zhCN} 
/LocaleProvider

二：开发环境
由于这个环境是以前同事搭建的，ant-design-pro-test版本是1.1.0,antd版本是3.19.8,初始化用的npm install 指令，当antd版本是3.1.0的时候，RangePicker组件显示的中文，一切正常，由于业务需要，我手动执行了npm install antd,将antd版本升级至3.19.8,升级后导致RangePicker无法显示中文。

三：其它
我在网上看到，初始化使用npm install 会导致RangePicker不能显示中文，
原帖地址：https://blog.csdn.net/zeng__yi/article/details/83620262

请问我目前这种情况，该如何处理，谢谢！

**Comment by chenshuai2144** [comment]
有重现仓库吗?

**Comment by afc163** [comment]
确保项目中没有两份不同版本的 moment 依赖。

**Comment by jlq023** [comment]
> 有重现仓库吗?

现在我是antd版本是moment 版本冲突导致的问题，但还没搞清楚，antd和moment 版本的对应关系。

**Comment by jlq023** [comment]
> 确保项目中没有两份不同版本的 moment 依赖。

请问如何判断项目有几份moment 的依赖？

**Comment by chenshuai2144** [comment]
npm ls moment

**Comment by jlq023** [comment]
> npm ls moment

这个问题解决得很悬乎，我目前把antd版本降至3.16.1了，moment 是2.24.0。以后我不会直接npm install antd了，尽量到官网上去下。

**Comment by afc163** [comment]
如果解决不了，可以尝试 push 一个可重现的 repo 上来，我们帮你排查一下 moment 依赖。

**Comment by jlq023** [comment]
> 如果解决不了，可以尝试 push 一个可重现的 repo 上来，我们帮你排查一下 moment 依赖。

谢谢，这个问题解决了，目前我在研究roadhog构建打包，js很大的问题， chenshuai2144 大神告诉我使用externals ，我手上事做完了，研究一下externals ，如果有问题再向你们请教.
问题地址：https://github.com/ant-design/ant-design-pro/issues/4776

**Comment by Mh2336393** [comment]
> > npm ls moment
> 
> 这个问题解决得很悬乎，我目前把antd版本降至3.16.1了，moment 是2.24.0。以后我不会直接npm install antd了，尽量到官网上去下。

低版本本来就没问题啊 但是我要用4.+antd 版本

**Comment by ximendatie** [comment]
> > 如果解决不了，可以尝试 push 一个可重现的 repo 上来，我们帮你排查一下 moment 依赖。
> 
> 谢谢，这个问题解决了，目前我在研究roadhog构建打包，js很大的问题， chenshuai2144 大神告诉我使用externals ，我手上事做完了，研究一下externals ，如果有问题再向你们请教. 问题地址：#4776

我也遇到了，后来怎么解决的呢
