### ISSUE TITLE
v4 如何做用户登录权限设计

### ISSUE THREAD

**Issue by gmw-zjw** [ant-design/ant-design-pro#4742]
v4,如何制作权限设计，当初次进入时怎么显示登录页？

**Comment by hankaibo** [comment]
我写了个demo，动态菜单，按钮级别权限。
就是v2版本的，根据官方文档修改的。

http://58.87.121.239:9000/user/login
admin/123456，所有权限；
user/123456，部分权限；
add/123456，添加加权限；
del/123456，删除权限。
支持动态左侧菜单。
可以自己在权限里面配置角色分配给用户。
https://github.com/hankaibo/myantdpro
源码地址。

**Comment by chenyu1990** [comment]
https://github.com/LyricTian/gin-admin-react
