### ISSUE TITLE
block 的相关问题

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4743]
问题1：在 src 下新建个文件夹，.umi 下的 router.js 运行时候，不更新路径
![image](https://user-images.githubusercontent.com/51696361/60700574-f8048780-9f2a-11e9-9b26-c888aa895572.png)

**Comment by Benpaodejiezai** [comment]
问题2：手动修改路径后，页面获取不到数据，不新建 OneDemo 文件夹的时候是好用的
![image](https://user-images.githubusercontent.com/51696361/60700669-5598d400-9f2b-11e9-914d-5b62d4e82405.png)

**Comment by Benpaodejiezai** [comment]
问题3：页面对应的 less 文件中的样式不生效，ant-design-pro 项目 umi block add 之后样式也是不生效的

**Comment by chenshuai2144** [comment]
> 问题3：

更新一下 umi.

> 问题1，2

.umi 内部是根据 config.js 自动生成的。不要人工修改自动生成的代码

**Comment by Benpaodejiezai** [comment]
> > 问题3：
> 
> 更新一下 umi到最新版本。原来 dll 有个 bug 会导致的 less 无法加载
> 
> > 问题1，2
> 
> .umi 内部是根据 config.js 自动生成的。不要人工修改自动生成的代码

.umi  是因为自动生成的不对我才改的。。。

**Comment by Benpaodejiezai** [comment]
> > 问题3：
> 
> 更新一下 umi到最新版本。原来 dll 有个 bug 会导致的 less 无法加载
> 
> > 问题1，2
> 
> .umi 内部是根据 config.js 自动生成的。不要人工修改自动生成的代码

我怎么才能修改 config.js 文件呢   是修改 .umirc.ts 吗？

**Comment by chenshuai2144** [comment]
约定式的路由建的页面要在 pages 下面才会被算成路由。

**Comment by Benpaodejiezai** [comment]
> 约定式的路由建的页面要在 pages 下面才会被算成路由。

嗯嗯，谢大佬。问题1，2解决了，问题3  更新到umi 2.8.8   但还是没生效

**Comment by chenshuai2144** [comment]
block 好像对约定路由支持不是很好。
pro 中没有这个问题

**Comment by Benpaodejiezai** [comment]
> block 好像对约定路由支持不是很好。
> pro 中没有这个问题

我是直接在 .umirc.ts  里面配置的 routes
