### ISSUE TITLE
v2项目启动后控制台报错

### ISSUE THREAD

**Issue by ZylFrank** [ant-design/ant-design-pro#4744]
克隆项目：git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project -b v2

版本： "version": "2.3.1",

项目启动后控制台报错，无论那个页面都有这个错误
![image](https://user-images.githubusercontent.com/30528319/60701133-3438e780-9f2d-11e9-81a1-c5cbbd628dba.png)

并且绘图的位置有些错乱

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4712

**Comment by ZylFrank** [comment]
版本都是"version": "2.3.1", 为什么我这有的项目就报上面的错误，而又的项目不报错呢？

**Comment by ZylFrank** [comment]
报错原因：antd版本问题
项目安装的antd版本为(3.20.0）；降低antd版本可防止报错
[#17387](https://github.com/ant-design/ant-design/issues/17387)
