### ISSUE TITLE
开发环境更换主题后报错 window.less.modifyVars is not a function

### ISSUE THREAD

**Issue by pollyZhai2018** [ant-design/ant-design-pro#4745]
根据已经有的这个问题的解决办法我这边。300、2000、5000都试过了，不起任何作用。

![1562309271003](https://user-images.githubusercontent.com/40228065/60703285-01462200-9f34-11e9-95f3-b81b6ee2d266.png)

**Comment by chenshuai2144** [comment]
你加载了 less.js 了吗？

**Comment by liudonghua123** [comment]
@chenshuai2144 less.js 是 https://github.com/less/less.js/ 这个么，需要怎么加载？

**Comment by chenshuai2144** [comment]
看看你的控制台，他应该是默认加载的

**Comment by pollyZhai2018** [comment]
已经解决



---原始邮件---
发件人: "陈帅"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 晚上7:06
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"pollyZhai2018"<757962437@qq.com&gt;;
主题: Re: [ant-design/ant-design-pro] 开发环境更换主题后报错 window.less.modifyVars is not a function (#4745)



看看你的控制台，他应该是默认加载的

**Comment by pollyZhai2018** [comment]
谢谢了



---原始邮件---
发件人: "陈帅"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 晚上7:06
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"pollyZhai2018"<757962437@qq.com&gt;;
主题: Re: [ant-design/ant-design-pro] 开发环境更换主题后报错 window.less.modifyVars is not a function (#4745)



看看你的控制台，他应该是默认加载的

**Comment by liudonghua123** [comment]
我是这样修改的，参考
https://github.com/zhangdaiscott/jeecg-boot/issues/592
https://github.com/zhangdaiscott/jeecg-boot/pull/587/commits/d56cc119c62dabe56e870342b7718bb76d31f6e5
