### ISSUE TITLE
## 错误原因      1. 文件确实不存在     2. 大小写问题

### ISSUE THREAD

**Issue by huanying1024** [ant-design/ant-design-pro#4750]
![image](https://user-images.githubusercontent.com/45089695/60716610-74f72780-9f52-11e9-9e42-b0ac160d843b.png)

**Comment by chenshuai2144** [comment]
升级antd到@3.20

**Comment by huanying1024** [comment]
> 升级antd到@ 3.20

大佬 已经是antd3.2的版本,图片上好像是说403;404页面的依赖没找到?
