### ISSUE TITLE
安装全部区块npm run fetch:blocks之后,执行npm start报错

### ISSUE THREAD

**Issue by huanying1024** [ant-design/ant-design-pro#4752]
![image](https://user-images.githubusercontent.com/45089695/60750087-2c814d80-9fd6-11e9-8e9c-d60c6d999063.png)

**Comment by chenshuai2144** [comment]
fetch:blocks 应该是失败了
fetch:blocks 现在有个问题，超时错误他不会显示

**Comment by ght19970126** [comment]
我也遇到这个问题不知道怎么解决

**Comment by chenshuai2144** [comment]
@ght19970126  具体问题要具体解决，这个问题是找不到文件导致的。

**Comment by mytheshow** [comment]
我也是遇到这个问题，一个区块都安装，但是配置文件config.js却有了路由
