### ISSUE TITLE
关于内网无法访问https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js的问题

### ISSUE THREAD

**Issue by tt38491367** [ant-design/ant-design-pro#4756]
打包后index.html引入了：
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>

如果在内网服务器，无法访问cdnjs.cloudflare.com，无法使用怎么办？可以配置less.min的引用地址吗？

**Comment by chenshuai2144** [comment]
你需要换主题的功能吗？

**Comment by tt38491367** [comment]
> 你需要换主题的功能吗？

不是，是我们的项目部署在内网，内网无法访问外网，无妨访问https://cdnjs.cloudflare.com。而打包后都在index.html引入https://cdnjs.cloudflare.com的less.js。导致项目出错。

请问在哪里可以更改less.min的引用地址（我可以吧less.min下载到本地）？？？

**Comment by chenshuai2144** [comment]
你可以直接删掉换主题的功能。
具体看这个 https://pro.ant.design/blog/change-theme-cn
