### ISSUE TITLE
add 自己的 block 会额外套一层文件夹

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4758]
ConfigClassify 是我自己写的 block，
table-list 是官方的 pro-blocks-master/ListTableList
添加自己的 会额外多一层文件夹是怎么回事？在哪配置的呢？
![image](https://user-images.githubusercontent.com/51696361/60790496-394ba000-a194-11e9-833f-bd80ade6f7b0.png)

**Comment by Benpaodejiezai** [comment]
求解啊！！！

**Comment by chenshuai2144** [comment]
区块有 —path 参数，默认会用你的区块名转化。

**Comment by yutingzhao1991** [comment]
--page 就不会多加一层了，pro 有个 https://github.com/ant-design/pro-blocks/blob/master/AccountCenter/package.json#L27 这个配置，所以相当于默认是 --page。

**Comment by Benpaodejiezai** [comment]
> --page 就不会多加一层了，pro 有个 https://github.com/ant-design/pro-blocks/blob/master/AccountCenter/package.json#L27 这个配置，所以相当于默认是 --page。

完美解决问题，谢大佬
