### ISSUE TITLE
点击二级菜单会自动收缩到母菜单

### ISSUE THREAD

**Issue by linxuanwei** [ant-design/ant-design-pro#4760]
`为什么点击二级菜单会自动收缩到母菜单，是bug还是故意的，用着好不爽`

- 母菜单 ----
      
       页面A ---
       页面B ---
       菜单C ---
                页面 C1 ---
                页面 C2 ---
`

点击页面A -->  点击菜单C   会自动收缩到母菜单，而不是扩展开菜单C ？ why？

**Comment by chenshuai2144** [comment]
没有听懂来个动图？

**Comment by 0x55aa** [comment]
@chenshuai2144 应该是不支持三级菜单的问题吧，handleOpenChange这个可用重新定义吗？不知道怎么实现 去掉pro-layout自带的只能展开一个菜单的限制呢

**Comment by afc163** [comment]
@chenshuai2144 开一个手风琴的配置吧。

**Comment by ailonghun** [comment]
ant Menu组件的 openKeys 参数，默认逻辑为/account/settings/security 上级为/account/settings 上级为/account 上级为 / 如果你的路由设置不是这个就会有问题，需要重新按照你自己的业务逻辑修改   openKeys的获取逻辑，不是bug 你自己配置未按照路由规则，需要自己重写，或者简单点直接注释掉Menu组件的 openKeys 参数，此方法交互效果不好

**Comment by xuqplus** [comment]
![image](https://user-images.githubusercontent.com/23195071/62277948-c6bf9e80-b479-11e9-8b1f-a88a056db0e5.png)

**Comment by xuqplus** [comment]
![image](https://user-images.githubusercontent.com/23195071/62277986-d50dba80-b479-11e9-8f08-c7c50fe89f1b.png)

**Comment by xuqplus** [comment]
点一下多级菜单

**Comment by xuqplus** [comment]
![image](https://user-images.githubusercontent.com/23195071/62278075-f4a4e300-b479-11e9-83f8-a07bb5526685.png)

**Comment by xuqplus** [comment]
另外

**Comment by xuqplus** [comment]
> `为什么点击二级菜单会自动收缩到母菜单，是bug还是故意的，用着好不爽`
> 
> * 母菜单 ----
>   ```
>    页面A ---
>    页面B ---
>    菜单C ---
>             页面 C1 ---
>             页面 C2 ---
>   ```
> 
> `
> 
> 点击页面A --> 点击菜单C 会自动收缩到母菜单，而不是扩展开菜单C ？ why？

解决了, 是因为没写 "redirect", 如图这样写就行了
![image](https://user-images.githubusercontent.com/23195071/62302482-02c02700-b4ad-11e9-8594-869a8976d0ca.png)

**Comment by xuqplus** [comment]
被展开的[ 上级菜单 ]自身是没有对应[ component ]的, 可能都需要设置一个[ redirect ], 没有看SiderMenu做了什么逻辑, 对比 @xiaohuoni => https://github.com/xiaohuoni/umi-antd-pro 的路由源码发现的.

**Comment by xuqplus** [comment]
> 没有听懂来个动图？

![biuba-y2kjm](https://user-images.githubusercontent.com/23195071/62304728-284f2f80-b4b1-11e9-84f3-362bf044f3bf.gif)

**Comment by xuqplus** [comment]
> `为什么点击二级菜单会自动收缩到母菜单，是bug还是故意的，用着好不爽`
> 
> * 母菜单 ----
>   ```
>    页面A ---
>    页面B ---
>    菜单C ---
>             页面 C1 ---
>             页面 C2 ---
>   ```
> 
> `
> 
> 点击页面A --> 点击菜单C 会自动收缩到母菜单，而不是扩展开菜单C ？ why？

发现真相了, 不知道你是不是用的官方的脚手架, 把第二个根路径改掉就行了...
![image](https://user-images.githubusercontent.com/23195071/62305649-efb05580-b4b2-11e9-9c4d-0a61a91fc456.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/pull/85

这个 pr 可以实现你想要的功能
