### ISSUE TITLE
按教程安装启动后有错误

### ISSUE THREAD

**Issue by tangniyuqi** [ant-design/ant-design-pro#4761]
教程：https://pro.ant.design/docs/getting-started-cn
多次重新安装都有这个错误。

![image](https://user-images.githubusercontent.com/5830538/60803143-20031d80-a1ad-11e9-9e4a-6e75ba5005d1.png)

**Comment by mushroomlb** [comment]
![image](https://user-images.githubusercontent.com/1701771/60858188-e4fdfa00-a23f-11e9-87eb-8eb35018a0c1.png)
安装全部区块，包这个错

**Comment by chenshuai2144** [comment]
@mushroomlb  你的错误可以忽略，不会影响启动。https://github.com/umijs/umi/issues/2769

@tangniyuqi 升级一下 antd

**Comment by tangniyuqi** [comment]
@chenshuai2144 
更新antd后还是提示之前的错误， yarn upgrade antd
