### ISSUE TITLE
path on breadcrumb of pageheaderwrapper is not absolute

### ISSUE THREAD

**Issue by michaelgli** [ant-design/ant-design-pro#4763]
如果我现在的Page URL是localhost/abc, the breadcrumb of the following example will be:
localhost/abc#/index
localhost/abc#/index/first
What I really want is the following:
localhost/index
localhost/first

Basically, I want to have the absolute path (not relative to the current page), is this possible? Thanks.

        const routes = [
            {
                path: '/index',
                breadcrumbName: 'First-level Menu',
            },
            {
                path: '/first',
                breadcrumbName: 'Second-level Menu',
            },
            {
                path: '/second',
                breadcrumbName: 'Third-level Menu',
            },
        ];

        return (
            <PageHeader title="something" breadcrumb={{ routes }} >
            </PageHeader>
        );

**Comment by michaelgli** [comment]
写了一个 itemRender:
  itemRender = (route, params, routes, paths) => {
    const last = routes.indexOf(route) === routes.length - 1;
    console.log("paths:", paths);
    return last ? (
      <span>{route.breadcrumbName}</span>
    ) : (
      <Link to={route.path}>{route.breadcrumbName}</Link>
    );
  };

**Comment by czw1314** [comment]
> 如果我现在的页面URL是localhost / abc，以下示例的面包屑将是：
> localhost / abc＃/ index
> localhost / abc＃/ index / first
> 我真正想要的是以下内容：
> localhost / index
> localhost / first
> 
> 基本上，我想拥有绝对路径（而不是相对于当前页面的路径），这可能吗？谢谢。
> 
> ```
>     const routes = [
>         {
>             path: '/index',
>             breadcrumbName: 'First-level Menu',
>         },
>         {
>             path: '/first',
>             breadcrumbName: 'Second-level Menu',
>         },
>         {
>             path: '/second',
>             breadcrumbName: 'Third-level Menu',
>         },
>     ];
> 
>     return (
>         <PageHeader title="something" breadcrumb={{ routes }} >
>         </PageHeader>
>     );
> ```

请问这个itemRender写在哪里的？谢谢！

**Comment by czw1314** [comment]
> 写了一个 itemRender:
> itemRender = (route, params, routes, paths) => {
> const last = routes.indexOf(route) === routes.length - 1;
> console.log("paths:", paths);
> return last ? (
> {route.breadcrumbName}
> ) : (
> {route.breadcrumbName}
> );
> };

请问这个itemRender写在哪里的？谢谢！

**Comment by kgloveyou** [comment]
> 写了一个 itemRender:
> itemRender = (route, params, routes, paths) => {
> const last = routes.indexOf(route) === routes.length - 1;
> console.log("paths:", paths);
> return last ? (
> {route.breadcrumbName}
> ) : (
> {route.breadcrumbName}
> );
> };

代码中?:表达式里面两项没区别啊

**Comment by zhaolongli0724** [comment]
```
import React from 'react';
import { Link } from 'umi';
import _ from 'lodash';

export default function itemRender(route, params, routes, paths) {
  const last = routes.indexOf(route) === routes.length - 1;
  const absolutePaths: string[] = paths.map((path) => `/${path}`);
  return last ? (
    <span>{route.breadcrumbName}</span>
  ) : (
    <Link to={_.last(absolutePaths) || '/'}>{route.breadcrumbName}</Link>
  );
}

```

**Comment by kentshenlim** [comment]
``` JS
const itemRender = (currentRoute, params, items, path) => {
  const isLast = currentRoute?.path === items[items.length - 1]?.path;

  return isLast ? (
    <span>{currentRoute.title}</span>
  ) : (
    <Link to={currentRoute.path}>{currentRoute.title}</Link> // I am using React Router here
  );
};
```

And then set as `itemRender` when calling breadcrumb.
```JS
const el = <Breadcrumb
    itemRender={itemRender}
    items={[
      {
        path: '/',
        title: 'Home',
      },
      {
        path: `/products`,
        title: 'Products',
      },
    ]}
  />
```
