### ISSUE TITLE
安装区块后界面问题

### ISSUE THREAD

**Issue by Brandon0916** [ant-design/ant-design-pro#4765]
安装了EditFlow 流程图区块后，这个界面出现错位。。。
<img width="950" alt="屏幕快照 2019-07-09 上午10 32 06" src="https://user-images.githubusercontent.com/35166997/60855073-f4c41100-a234-11e9-8f62-cee9bbf6cb98.png">

**Comment by chenshuai2144** [comment]
你的 css 没有加载成功。试着重新启动一下

**Comment by Brandon0916** [comment]
用了fetch blocks 重新启动了一下就好了
