### ISSUE TITLE
componentDidMount 用dva异步获取数据render为什么this.props打印5次,前两次空值，后三次有值 

### ISSUE THREAD

**Issue by wangjingithub** [ant-design/ant-design-pro#4768]
componentDidMount 用dva异步获取数据render为什么this.props打印5次,前两次空值，后三次有值

**Comment by chenshuai2144** [comment]
你可以判断一下是什么的更新造成的，推荐使用 react chrome 插件来查看

**Comment by wangjingithub** [comment]
菜鸟实在找不到原因。。

**Comment by chenshuai2144** [comment]
有严重的性能问题吗？  如果没有就假装没发生吧。性能调优是个很负责的事情
