### ISSUE TITLE
ant-design 安装失败

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#4769]
![image](https://user-images.githubusercontent.com/44084004/60863196-7e360c00-a252-11e9-8b8a-6c6c6ef42436.png)
各位大神，今天在我升级ant-design 至最新版本时，升级时提示错误信息。并运行开发环境也出现了一系列错误。请问有人遇见过吗？

**Comment by chenshuai2144** [comment]
权限错误，强制删除 node-moudles 即可
