### ISSUE TITLE
打包之后，REACT-AMAP 的高德地图不显示，报错找不到文件

### ISSUE THREAD

**Issue by liuhanbingdabendan** [ant-design/ant-design-pro#4771]
![image](https://user-images.githubusercontent.com/39874357/60871236-ed1c6080-a264-11e9-93d2-5b7cf858fdad.png)
``

**Comment by chenshuai2144** [comment]
这个与 pro 无关，这是你使用了相对引用造成的。你可以将这个文件通过绝对路径来引用
