### ISSUE TITLE
希望能官方出一个菜单权限/按钮权限的CURD示例模块

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#4772]
中后台管理系统,不同用户,拥有不同的角色,每个角色能查看到的菜单/按钮 都不同.
希望官方能出一个前端菜单权限分配的示例~~

**Comment by billychou** [comment]
同在看`Authorized Component`的相关资料。官方文档这块感觉不是特别全。

**Comment by VeChar** [comment]
需要自己踩坑

**Comment by xiaopanghhh** [comment]
你的角色是固定的，还是可以自定义的？

**Comment by l745230** [comment]
@xiaopanghhh 一般是自定义的,比如管理员,财务部,信息部,推广部 等,每个角色看到的菜单都不相同

**Comment by xiaopanghhh** [comment]
角色自定义，那权限估计需要改动一下，可能需要把用户的permissions当作角色来看了。回头我给你一个 demo 吧。

**Comment by zhaokera** [comment]
@xiaohuoni 请问下demo有了吗~求一份谢谢大佬

**Comment by xlszzck** [comment]
需要自己改装Authorized.js，把角色权限转变成功能权限，然后派发权限到页面，再用Authorized组件去管理对应的视图。至于菜单权限，这个是有官方实例的，好像GitHub上有，不太好找。

**Comment by wangxingkang** [comment]
@zhaokera 可以看下 https://github.com/ts-react/react-admin-template

**Comment by xiaopanghhh** [comment]
@l745230    给个邮箱地址，我发一份儿代码给你。

**Comment by l745230** [comment]
@xiaopanghhh 526509994@qq.com 蟹蟹大佬(破音)~

**Comment by xiaopanghhh** [comment]
已发，请查收~

**Comment by Jobchen** [comment]
@xiaopanghhh 兄弟发我一份demo 谢谢啦 dinglino1@163.com

**Comment by xiaopanghhh** [comment]
已发

**Comment by roy201603** [comment]
@xiaopanghhh 麻烦发个demo 给我看看，wait4teng@gmail.com 谢谢～

**Comment by mengshis** [comment]
@xiaopanghhh 大哥给我发一份mengshis@163.com，谢谢🙏

**Comment by chenyjam** [comment]
@xiaopanghhh 兄弟能发一份我不 646537561@qq.com 感谢感谢

**Comment by huangzj0520** [comment]
@xiaopanghhh 老哥发我一份 709564013@qq.com 谢了哈~

**Comment by xiongeee** [comment]
@xiaopanghhh 老哥发我一份 42713491@qq.com 谢了哈~

**Comment by youngsailor** [comment]
@xiaopanghhh 老哥发我一份 591245853@qq.com 谢了哈

**Comment by xiaohuoni** [comment]
我还以为是求什么好人呢。。。

**Comment by xiaopanghhh** [comment]
> 我还以为是求什么好人呢。。。

啥意思？？？

**Comment by xiaohuoni** [comment]
没事（面红耳赤）

**Comment by hankaibo** [comment]
http://58.87.121.239:9000/user/login
admin/123456，所有权限；
user/123456，部分权限；
add/123456，添加加权限；
del/123456，删除权限。
支持动态左侧菜单。

可以自己在权限里面配置角色分配给用户。

**Comment by hankaibo** [comment]
https://github.com/hankaibo/myantdpro
源码地址。

**Comment by furylee** [comment]
1005596113@qq.com thx

> @l745230 给个邮箱地址，我发一份儿代码给你。

**Comment by wangxingkang** [comment]
可以看下 https://antd-plus.alitajs.com/components/authorized  这个权限组件

**Comment by C-SF-C** [comment]
@xiaopanghhh 大佬请发一份给我 我已经被权限搞疯了 求救

**Comment by wangxingkang** [comment]
https://github.com/wangxingkang/website/issues/1 这是对于权限实现的一些想法 可以看下

**Comment by JzwOnly** [comment]
@xiaopanghhh 大佬给我也来一个 836579250@qq.com 谢谢

**Comment by Fuphoenixes** [comment]
@xiaopanghhh 大哥给我发一份657454579@qq.com，谢谢pray

**Comment by FanFanJUN** [comment]
@xiaopanghhh   能发一份权限代码吗 1981824361@qq.com 谢谢

**Comment by MrWangLoveTrue** [comment]
@xiaopanghhh 大佬给我也发一份权限代码把 923500094@qq.com 谢谢

**Comment by RickeyLuckey** [comment]
@xiaopanghhh 大佬麻烦你也发一份权限的完整代码 1053137266@qq.com 非常感谢了！
