### ISSUE TITLE
执行报错：npx umi block add DashboardAnalysis --path=/dashboard/analysis

### ISSUE THREAD

**Issue by heweipingzju** [ant-design/ant-design-pro#4774]
>npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ �  Parse url and args
√ � Git fetch
√ � Git checkout master
√ � Git pull
× �  Install additional dependencies @types/lodash.debounce@^4.0.6,bizcharts@^3.5.3-beta.0,bizcharts-plugin-slider@^2.1.1-beta.1,lodash.debounce@^4.0.8,numeral@^2.0.6,react-fittext@^1.0.0 with npm --registry https://regis
try.npm.taobao.org
×  error     Error: Error: Command failed: npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
://registry.npm.taobao.org --save
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andshe\AppData\Roaming\npm-cache\_logs\2019-07-10T00_13_17_400Z-debug.log

    at D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:403:17
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:39:103)
    at _throw (D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)

D:\nginx-1.14.2\html\wits3>

**Comment by chenshuai2144** [comment]
@sorrycc  跪求判断 cnpm 和 npm 的 🤗

**Comment by heweipingzju** [comment]
> 求判断 cnpm

什么意思？

**Comment by heweipingzju** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\nginx-1.14.2\html\wits3>umi -v
2.8.8

D:\nginx-1.14.2\html\wits3>npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ �  Parse url and args
√ � Git fetch
√ � Git checkout master
√ � Git pull
× �  Install additional dependencies @types/lodash.debounce@^4.0.6,bizcharts@^3.5.3-beta.0,bi
zcharts-plugin-slider@^2.1.1-beta.1,lodash.debounce@^4.0.8,numeral@^2.0.6,react-fittext@^1.0.0with npm --registry https://registry.npm.taobao.org
×  error     Error: Error: Command failed: npm install @types/lodash.debounce@^4.0.6 bizcharts
@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https://registry.npm.taobao.org --save
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andshe\AppData\Roaming\npm-cache\_logs\2019-07-10T06_10_10_949Z-debug.log


    at D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:403:17
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:39:103)
    at _throw (D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)

D:\nginx-1.14.2\html\wits3>

**Comment by heweipingzju** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@types/lodash.debounce@^4.0.6',
1 verbose cli   'bizcharts@^3.5.3-beta.0',
1 verbose cli   'bizcharts-plugin-slider@^2.1.1-beta.1',
1 verbose cli   'lodash.debounce@^4.0.8',
1 verbose cli   'numeral@^2.0.6',
1 verbose cli   'react-fittext@^1.0.0',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   '--save' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose npm-session e0ef3bf634278bfa
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/lodash.debounce 300ms (from cache)
8 http fetch GET 304 https://registry.npm.taobao.org/@types%2flodash.debounce 321ms (from cache)
9 http fetch GET 304 https://registry.npm.taobao.org/bizcharts-plugin-slider 307ms (from cache)
10 silly pacote range manifest for lodash.debounce@^4.0.8 fetched in 309ms
11 silly pacote range manifest for @types/lodash.debounce@^4.0.6 fetched in 1525ms
12 http fetch GET 304 https://registry.npm.taobao.org/react-fittext 309ms (from cache)
13 silly pacote range manifest for bizcharts-plugin-slider@^2.1.1-beta.1 fetched in 313ms
14 http fetch GET 304 https://registry.npm.taobao.org/numeral 312ms (from cache)
15 http fetch GET 304 https://registry.npm.taobao.org/bizcharts 316ms (from cache)
16 silly pacote range manifest for react-fittext@^1.0.0 fetched in 324ms
17 silly pacote range manifest for numeral@^2.0.6 fetched in 326ms
18 silly pacote range manifest for bizcharts@^3.5.3-beta.0 fetched in 331ms
19 timing stage:loadCurrentTree Completed in 65810ms
20 silly install loadIdealTree
21 silly install cloneCurrentTreeToIdealTree
22 timing stage:loadIdealTree:cloneCurrentTree Completed in 57ms
23 silly install loadShrinkwrap
24 timing stage:rollbackFailedOptional Completed in 0ms
25 timing stage:runTopLevelLifecycles Completed in 66482ms
26 silly saveTree ant-design-pro@1.0.0
26 silly saveTree +-- @ant-design/colors@3.1.0
26 silly saveTree +-- @ant-design/pro-layout@4.5.10
26 silly saveTree | +-- antd@3.20.0
26 silly saveTree | | +-- @ant-design/create-react-context@0.2.4
26 silly saveTree | | +-- @ant-design/icons-react@2.0.1
26 silly saveTree | | | `-- babel-runtime@6.26.0
26 silly saveTree | | |   +-- core-js@2.6.9
26 silly saveTree | | |   `-- regenerator-runtime@0.11.1
26 silly saveTree | | +-- @ant-design/icons@2.1.1
26 silly saveTree | | +-- @types/react-slick@0.23.4
26 silly saveTree | | | `-- @types/react@16.8.22
26 silly saveTree | | |   `-- @types/prop-types@15.7.1
26 silly saveTree | | +-- array-tree-filter@2.1.0
26 silly saveTree | | +-- babel-runtime@6.26.0
26 silly saveTree | | +-- classnames@2.2.6
26 silly saveTree | | +-- copy-to-clipboard@3.2.0
26 silly saveTree | | `-- css-animation@1.5.0
26 silly saveTree | |   `-- component-classes@1.2.6
26 silly saveTree | |     `-- component-indexof@0.0.3
26 silly saveTree | `-- classnames@2.2.6
26 silly saveTree +-- @antv/data-set@0.10.2
26 silly saveTree | +-- @antv/hierarchy@0.4.0
26 silly saveTree | | `-- @antv/util@1.3.1
26 silly saveTree | |   `-- @antv/gl-matrix@2.7.1
26 silly saveTree | `-- @antv/util@1.3.1
26 silly saveTree +-- @types/classnames@2.2.9
26 silly saveTree +-- @types/history@4.7.2
26 silly saveTree +-- @types/jest@24.0.15
26 silly saveTree | `-- @types/jest-diff@20.0.1
26 silly saveTree +-- @types/lodash@4.14.135
26 silly saveTree +-- @types/qs@6.5.3
26 silly saveTree +-- @types/react-document-title@2.0.3
26 silly saveTree +-- @types/react-dom@16.8.4
26 silly saveTree +-- @types/react@16.8.22
26 silly saveTree +-- @umijs/fabric@1.1.3
26 silly saveTree | +-- @typescript-eslint/eslint-plugin@1.11.0
26 silly saveTree | | `-- @typescript-eslint/experimental-utils@1.11.0
26 silly saveTree | |   `-- @typescript-eslint/typescript-estree@1.11.0
26 silly saveTree | |     `-- semver@5.5.0
26 silly saveTree | +-- @typescript-eslint/parser@1.11.1-alpha.10
26 silly saveTree | | +-- @types/eslint-visitor-keys@1.0.0
26 silly saveTree | | +-- @typescript-eslint/experimental-utils@1.11.1-alpha.10
26 silly saveTree | | | `-- @typescript-eslint/typescript-estree@1.11.1-alpha.10
26 silly saveTree | | |   `-- semver@5.5.0
26 silly saveTree | | `-- @typescript-eslint/typescript-estree@1.11.1-alpha.10
26 silly saveTree | `-- eslint-plugin-react-hooks@1.6.1
26 silly saveTree +-- antd@3.20.0
26 silly saveTree +-- chalk@2.4.2
26 silly saveTree | +-- ansi-styles@3.2.1
26 silly saveTree | | `-- color-convert@1.9.3
26 silly saveTree | |   `-- color-name@1.1.3
26 silly saveTree | `-- supports-color@5.5.0
26 silly saveTree +-- check-prettier@1.0.3
26 silly saveTree | `-- commander@2.20.0
26 silly saveTree +-- classnames@2.2.6
26 silly saveTree +-- cross-env@5.2.0
26 silly saveTree | `-- cross-spawn@6.0.5
26 silly saveTree `-- cross-port-killer@1.1.1
27 verbose stack TypeError: Cannot read property 'match' of undefined
27 verbose stack     at tarballToVersion (D:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:87:20)
27 verbose stack     at inflatableChild (D:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:99:22)
27 verbose stack     at BB.each (D:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12)
27 verbose stack     at tryCatcher (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
27 verbose stack     at Object.gotValue (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
27 verbose stack     at Object.gotAccum (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
27 verbose stack     at Object.tryCatcher (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
27 verbose stack     at Promise._settlePromiseFromHandler (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
27 verbose stack     at Promise._settlePromise (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
27 verbose stack     at Promise._settlePromiseCtx (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
27 verbose stack     at Async._drainQueue (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
27 verbose stack     at Async._drainQueues (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
27 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (D:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
27 verbose stack     at runCallback (timers.js:705:18)
27 verbose stack     at tryOnImmediate (timers.js:676:5)
27 verbose stack     at processImmediate (timers.js:658:5)
28 verbose cwd D:\nginx-1.14.2\html\wits3
29 verbose Windows_NT 6.1.7601
30 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@types/lodash.debounce@^4.0.6" "bizcharts@^3.5.3-beta.0" "bizcharts-plugin-slider@^2.1.1-beta.1" "lodash.debounce@^4.0.8" "numeral@^2.0.6" "react-fittext@^1.0.0" "--registry=https://registry.npm.taobao.org" "--save"
31 verbose node v10.13.0
32 verbose npm  v6.4.1
33 error Cannot read property 'match' of undefined
34 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
你的仓库是用 cnpm 安装的吗？

**Comment by NearTop** [comment]
我也遇到了同样的问题（使用cnpm安装），换为npm安装，问题解决。cnpm和npm还有这区别？

**Comment by heweipingzju** [comment]
> 你的仓库是用 cnpm 安装的吗？

不是，使用npm安装的

**Comment by heweipingzju** [comment]
> 你的仓库是用 cnpm 安装的吗？

这种问题解决效率太低了，有没有高效点的方式？

本地
D:\nginx-1.14.2\html\wits3>npm -v
6.4.1

D:\nginx-1.14.2\html\wits3>node -v
v10.13.0

D:\nginx-1.14.2\html\wits3>umi -v
2.8.8
D:\nginx-1.14.2\html\wits3>yarn -v
1.12.3

D:\nginx-1.14.2\html\wits3>cnpm -v
'cnpm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

我只用npm，我只用npm，我只用npm，我只用npm，我只用npm

**Comment by chenshuai2144** [comment]
升级一下 node 版本试试，升级到 11

**Comment by heweipingzju** [comment]
> 升级一下 node 版本试试，升级到 11
你确定么？ 从错误信息看，怎么感觉是umi的问题，或者版本不配套的问题？

**Comment by heweipingzju** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\nginx-1.14.2\html\wits3>node -v
v12.6.0

D:\nginx-1.14.2\html\wits3>npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ �  Parse url and args
√ � Git fetch
√ � Git checkout master
√ � Git pull
× �  Install additional dependencies @types/lodash.debounce@^4.0.6,bizcharts@^3.5.3-beta.0,bizcharts-plugin-slider@^2.1.1-beta.1,lodash.debounce@^4.0.8,numeral@^2.0.6,react-fittext@^1.0.0 with npm --registry https://regis
try.npm.taobao.org
×  error     Error: Error: Command failed: npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
://registry.npm.taobao.org --save
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andshe\AppData\Roaming\npm-cache\_logs\2019-07-11T05_52_45_666Z-debug.log


    at D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:403:17
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:39:103)
    at _throw (D:\nginx-1.14.2\html\wits3\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

D:\nginx-1.14.2\html\wits3>npm -v
6.9.0

**Comment by heweipingzju** [comment]
还是不行，看来UMI就是个大坑，粪坑

**Comment by zzq0826** [comment]
我的是node v11.3.0 相同的错误

**Comment by chenshuai2144** [comment]
人工执行一下这个命令

npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
://registry.npm.taobao.org --save

**Comment by heweipingzju** [comment]
> npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
> ://registry.npm.taobao.org --save

小哥，你让我试，总的有个方向吧，你有没有认真定位下？？？

D:\nginx-1.14.2\html\wits3>npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
npm WARN invalid config registry="https"
npm WARN invalid config Must be a full url with 'http://'
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andshe\AppData\Roaming\npm-cache\_logs\2019-07-11T06_52_40_507Z-debug.log

**Comment by heweipingzju** [comment]
> 人工执行一下这个命令
> 
> ```
> npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
> ://registry.npm.taobao.org --save
> ```

你先看看错误信息，我都觉得不是umi的问题，就是版本配套的问题，你总得过过脑子吧

**Comment by chenshuai2144** [comment]
> D:\nginx-1.14.2\html\wits3>npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https

命令要 copy 全。

**Comment by chenshuai2144** [comment]
npm install @types/lodash.debounce@^4.0.6 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 lodash.debounce@^4.0.8 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https
://registry.npm.taobao.org --save

**Comment by panghaoyuan** [comment]
我这边也出现这个问题 
![image](https://user-images.githubusercontent.com/28645409/61042145-3526b900-a406-11e9-9a78-294c2abe9d1e.png)

先安装对应模块 然后再 block add就好了.
![image](https://user-images.githubusercontent.com/28645409/61042054-0872a180-a406-11e9-84b0-130d6ecc06c1.png)
![image](https://user-images.githubusercontent.com/28645409/61042110-22ac7f80-a406-11e9-90aa-a83140857c9e.png)

**Comment by mask2012** [comment]
我也遇到同样的问题。。

**Comment by chenshuai2144** [comment]
@panghaoyuan  清空你的node-moudles即可

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/issues/4823
