### ISSUE TITLE
使用npm安装报错

### ISSUE THREAD

**Issue by zhiphe** [ant-design/ant-design-pro#4775]
> husky@3.0.0 install /home/hezp1/Developer/bot-admin/node_modules/husky
> node husky install

husky > Setting up git hooks
fatal: 不是一个 git 仓库（或者任何父目录）：.git
husky > Failed to install

**Comment by chenshuai2144** [comment]
先忽略。husky 是一个 git 钩子程序。依赖仓库。你可以 git init 之后再进行安装
