### ISSUE TITLE
ant-design-pro-test1.10使用roadhog构建打包，文件很大，如何何化?

### ISSUE THREAD

**Issue by jlq023** [ant-design/ant-design-pro#4776]
我目前使用的ant-design-pro-test版本是1.10，默认使用roadhog构建打包，打包完成后，*.js目前已经有6m多，刷新或者页面加载的时候，特别慢，急需优化，目前想使用UglifyJsPlugin进行压缩，但不知道在.webpackrc.js如何配置，请问如何配置UglifyJsPlugin？或者应该如何优化打包后文件太大的问题？谢谢

**Comment by jlq023** [comment]
官网分析文件大小的指令是npm run analyze ，但我运行该指令，打包都报错了。所以并未运行该指令。 
https://v1.pro.ant.design/docs/deploy-cn

**Comment by chenshuai2144** [comment]
你可以分析一下你的依赖库，然后进行externals ，这个是见效最快的了

**Comment by jlq023** [comment]
> 后进行externals ，这个是见效最快的

谢谢大神的建议，我先百度下externals 如何用！
