### ISSUE TITLE
有谷歌的统计插件（umi-plugin-ga），有没有百度统计的插件呢？

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#4777]
国内，很多还是用百度统计的比较多吧？为啥没有百度统计插件呢？再问一下，在ant-design-pro项目里如何集成百度统计呢？（需要用到事件追踪，需要暴露出全局对象）

**Comment by afc163** [comment]
参考 umi-plugin-ga 做一个很快的，欢迎贡献。

**Comment by xiaohuoni** [comment]
我们有需求是，登录用户的行为统计，除了服务端自建服务，不知道有没有类似的方案可以直接接入的？

**Comment by XSmarter** [comment]
> 我们有需求是，登录用户的行为统计，除了服务端自建服务，不知道有没有类似的方案可以直接接入的？

这些统计里面都有事件统计啊，用户触发了那些行为，直接调用统计的事件记录应该就可以吧

**Comment by xiaohuoni** [comment]
@XSmarter 你看的百度统计是哪个？发个链接来看看。我们对接的都是那个在文件头添加一行代码，看访问量的

**Comment by XSmarter** [comment]
@xiaohuoni 你看下这个文档，百度统计和谷歌统计都有这个的  http://tongji.baidu.com/open/api/more?p=guide_trackEvent  根据上面这个链接添加了事件后 在这个页面（https://tongji.baidu.com/web/demo/custom/event_track?siteId=5503017）的事件分析里面有

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-plugin-tongji

**Comment by xiaohuoni** [comment]
@XSmarter 事件统计不符合我的需求，我们是需要对单个用户做事件统计，感觉会打了慢慢的tag。这个应该符合你的要求，你试试

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/61102370-1d037800-a4a0-11e9-8a10-2d59797dc372.png)
在alitajs.com试了一下，是有效的。不过刚安装延时有点久。所以不要以为没成功

**Comment by afc163** [comment]
可以提交到官方插件仓库

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-plugin-tongji

**Comment by afc163** [comment]
https://github.com/umijs/plugins 这里怎么样？

**Comment by xiaohuoni** [comment]
@afc163 https://github.com/umijs/plugins/pull/6 把两个库合并了

**Comment by XSmarter** [comment]
@xiaohuoni 是不是还没发布到npm，没搜索到发布是不是叫 umi-plugin-analatics ？

**Comment by xiaohuoni** [comment]
@XSmarter 只发了 umi-plugin-tongji ，合并的那个，还没收录呢
