### ISSUE TITLE
获取跨域请求的自定义response headers问题

### ISSUE THREAD

**Issue by tangniyuqi** [ant-design/ant-design-pro#4778]
能获取到数据，但不能获取到自定义header信息

![image](https://user-images.githubusercontent.com/5830538/60942438-31673980-a315-11e9-96b9-45c5d4bf5473.png)

![image](https://user-images.githubusercontent.com/5830538/60942507-74c1a800-a315-11e9-93fe-3e77d745d1e7.png)

**Comment by waylon-edmodo** [comment]
额，跟你相同的问题。

**Comment by waylon-edmodo** [comment]
是因为跨域取不到吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4603

**Comment by kzabc** [comment]
![image](https://user-images.githubusercontent.com/42925731/70226730-4d6beb80-178c-11ea-933b-3724960c025a.png)
![Uploading image.png…]()
![Uploading image.png…]()

不知道为啥取不到response.header 中的值

**Comment by UICJohn** [comment]
我在这个问题也是卡了很长时间，最后发现Header虽然是{}，但还是可以拿到值的， 用这个来获取自定义header: response.headers.get('<你的header key>'). 如果浏览器内有cors报错，那就处理后台header设置吧

**Comment by hyfjjjj** [comment]
1. 直接通过console.log打印不出来response.headers。可以通过 response.headers.forEach 循环打印实际接收到的headers，然后通过 response.headers.get 获取。
2. 如果跨域，需要服务端返回值的 headers 中通过 'Access-Control-Expose-Headers' 指定前端可以“看到”的header，如添加了 headers = { ..., 'Access-Control-Expose-Headers': 'aaa, bbb'}，那么返回值中的'aaa'，'bbb'这2个参数才能可见，有些浏览器也支持*这种写法。具体可以搜索Access-Control-Expose-Headers的用法。（当然也需要headers中添加Access-Control-Allow-Origin等这些保证api执行成功）
