### ISSUE TITLE
使用umi-request, 为什么请求失败了，loading的状态还在一直转，要怎么修改呢

### ISSUE THREAD

**Issue by wuxin2014** [ant-design/ant-design-pro#4779]
![企业微信截图_9bd0edd5-93fd-4416-bf2d-df86980b83fc](https://user-images.githubusercontent.com/6781980/60943313-26fa6f00-a318-11e9-81ef-6d9cda8c0347.png)

**Comment by chenshuai2144** [comment]
request 和 loading 之间没有关系的。loading 需要自己处理

**Comment by wuxin2014** [comment]
使用了dva-loading插件，不是不用自己处理吗？
