### ISSUE TITLE
左面的导航，可以放到一个可滚动区域内吗

### ISSUE THREAD

**Issue by Mantak** [ant-design/ant-design-pro#478]
这样，就不担心菜单过多影响右面的布局，也不担心右面内容过长时，切换导航的麻烦

比如像这样：
http://rommguy.github.io/react-custom-scroll/example/demo.html

**Comment by chenshuai2144** [comment]
菜单过多因为思考你们的架构是不是有问题了.
要实现你的功能很容易的.
meun 外面包一层固定高度就好了

**Comment by afc163** [comment]
Duplicate of #43
