### ISSUE TITLE
v4 动态菜单 点击事件会触发多次

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design-pro#4780]
采用动态菜单单，需求是点击菜单的某项做一些事情，按照文档上说的《自定义 menuItem 的点击逻辑，你可以通过 menuItemRender 的来实现》，我在menuItemRender写方法，发现每次点击会触发多次，次数跟我的菜单数量是一致的。
![屏幕快照 2019-07-10 下午2 24 34](https://user-images.githubusercontent.com/20022163/60945572-7e9bd900-a31e-11e9-9315-692abe474a28.png)
![屏幕快照 2019-07-10 下午2 26 01](https://user-images.githubusercontent.com/20022163/60945649-b9057600-a31e-11e9-85c1-c49f439dcce4.png)
![屏幕快照 2019-07-10 下午2 26 10](https://user-images.githubusercontent.com/20022163/60945656-c02c8400-a31e-11e9-9226-15a0bb34512e.png)

**Comment by chenshuai2144** [comment]
Render代表是一个是渲染，你需要返回一个 dom。他并不是点击事件。

**Comment by LiYanGang** [comment]
> Render代表是一个是渲染，你需要返回一个 dom。他并不是点击事件。

如果要实现菜单自定义事件应该如何做呢？文档就是这种解决方案啊

**Comment by wellenzhong** [comment]
> > Render代表是一个是渲染，你需要返回一个 dom。他并不是点击事件。
> 
> 如果要实现菜单自定义事件应该如何做呢？文档就是这种解决方案啊

你需要返回一个dom,
```
if (menuItemProps.target==='_blank') {   // 判断条件自己定，这里是举个栗子
          return <a herf={menuItemProps.path} target="_blank">{defaultDom}</div>
        }
```
