### ISSUE TITLE
v4 动态菜单 如何实现点击某个菜单选项实现自定义逻辑需求呢

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design-pro#4781]

**Comment by chenshuai2144** [comment]
`MeunItemRender = (_,dom)=><div onClick={myclick}>{dom}</div>`
这样，如果不想触发原来的事件。记得阻止事件冒泡。
有兴趣帮我们完善一下文档吗？

**Comment by LiYanGang** [comment]
> `MeunItemRender = (_,dom)=><div onClick={myclick}>{dom}</div>`
> 这样，如果不想触发原来的事件。记得阻止事件冒泡。
> 有兴趣帮我们完善一下文档吗？

非常感兴趣，我该如何做呢？

**Comment by chenshuai2144** [comment]
在这个仓库中提交 pr 即可
https://github.com/ant-design/ant-design-pro-site
