### ISSUE TITLE
怎么内嵌iframe

### ISSUE THREAD

**Issue by ruomanwei** [ant-design/ant-design-pro#4782]
2.0prolayout在代码里，我是直接判断在content那边，现在4.0需要怎么做

**Comment by chenshuai2144** [comment]
4.0 的也在

**Comment by ruomanwei** [comment]
动态路由+不确定的动态页面配置 ，组件内嵌入iframe
 {
        path: '/dynamic/:url',
        name: 'dynamic',
        icon: 'smile',
        hideInMenu: true,
        component: './SubModuleMenu',
      },

**Comment by zhuguangyue** [comment]
> 动态路由+不确定的动态页面配置 ，组件内嵌入iframe
> {
> path: '/dynamic/:url',
> name: 'dynamic',
> icon: 'smile',
> hideInMenu: true,
> component: './SubModuleMenu',
> },

你好，最近项目需求需要在菜单栏引入其他网站的页面，通过组件内嵌入iframe总是存在一些问题，能不能看看你的demo啊

**Comment by ruomanwei** [comment]
> > 动态路由+不确定的动态页面配置 ，组件内嵌入iframe
> > {
> > path: '/dynamic/:url',
> > name: 'dynamic',
> > icon: 'smile',
> > hideInMenu: true,
> > component: './SubModuleMenu',
> > },
> 
> 你好，最近项目需求需要在菜单栏引入其他网站的页面，通过组件内嵌入iframe总是存在一些问题，能不能看看你的demo啊

啊，我才看见你的回复，你应该弄完了吧

**Comment by zhuguangyue** [comment]
> > > 动态路由+不确定的动态页面配置 ，组件内嵌入iframe
> > > {
> > > path: '/dynamic/:url',
> > > name: 'dynamic',
> > > icon: 'smile',
> > > hideInMenu: true,
> > > component: './SubModuleMenu',
> > > },
> > 
> > 
> > 你好，最近项目需求需要在菜单栏引入其他网站的页面，通过组件内嵌入iframe总是存在一些问题，能不能看看你的demo啊
> 
> 啊，我才看见你的回复，你应该弄完了吧

搞完了，但是不太完美，可以给你的案例来参考一下。哈哈
