### ISSUE TITLE
在没下载安装区块之前,能正常启动欢迎界面,安装区块不成功

### ISSUE THREAD

**Issue by acainew** [ant-design/ant-design-pro#4785]
安装区块的命令:   npm run fetch:blocks   
![image](https://user-images.githubusercontent.com/42227567/60960223-35f31880-a33c-11e9-81d9-4c4cfe0bd166.png)

**Comment by zewu-chen** [comment]
问题是fetch:blocks时没有把所有文件下载全，缺少了list中的search文件夹中的文件，你可以自己看下是否已下全，或者手动把config中路由配置的list/search删除即可

**Comment by acainew** [comment]
下载的时候也没提示没下载全, npm cnpm都是这样,有什么办法可以确保下载全的吗?

**Comment by NearTop** [comment]
参看#4744，我pro项目使用cnpm install，再添加block，就会出现block下载不全的问题（这个过程并没有提示下载失败，但pages目录下部分block确实没有），统一都是要npm，问题解决，你可以试试。

**Comment by xiaohuoni** [comment]
@NearTop 链接给错了吧？

**Comment by acainew** [comment]
> 参看#4744，我pro项目使用cnpm install，再添加block，就会出现block下载不全的问题（这个过程并没有提示下载失败，但pages目录下部分block确实没有），统一都是要npm，问题解决，你可以试试。

按照你的方法,全部用npm,真的可以了,神奇,有谁能告知是什么原因吗?

**Comment by acainew** [comment]
贴一下完整的日志吧
![image](https://user-images.githubusercontent.com/42227567/61017478-ef4a0080-a3c5-11e9-8de8-a5b933e44f35.png)
![image](https://user-images.githubusercontent.com/42227567/61017488-f96bff00-a3c5-11e9-9aff-90906efb173c.png)
![image](https://user-images.githubusercontent.com/42227567/61017498-00930d00-a3c6-11e9-9ea5-57db1646cf4a.png)
![image](https://user-images.githubusercontent.com/42227567/61017506-07218480-a3c6-11e9-90c4-da8794bf9405.png)
![image](https://user-images.githubusercontent.com/42227567/61017514-0c7ecf00-a3c6-11e9-95b8-cf4b190b5b9d.png)
![image](https://user-images.githubusercontent.com/42227567/61017524-1274b000-a3c6-11e9-9efc-8a639fdab01e.png)
![image](https://user-images.githubusercontent.com/42227567/61017538-228c8f80-a3c6-11e9-88ee-610a8c843a79.png)

**Comment by chenshuai2144** [comment]
cnpm 和 npm 不兼容，两者的技术方案有区别

**Comment by acainew** [comment]
thanks all.

**Comment by dongkeng001** [comment]
> > 参看#4744，我pro项目使用cnpm install，再添加block，就会出现block下载不全的问题（这个过程并没有提示下载失败，但pages目录下部分block确实没有），统一都是要npm，问题解决，你可以试试。
> 
> 按照你的方法,全部用npm,真的可以了,神奇,有谁能告知是什么原因吗?

表示我也用了npm去下载，依旧是不行
