### ISSUE TITLE
使用hash路由，面包屑跳转问题，路径为啥错乱了

### ISSUE THREAD

**Issue by wuxin2014** [ant-design/ant-design-pro#4786]
![企业微信截图_da5ad006-d7c8-4cc0-8b39-0f33b4fe00cd](https://user-images.githubusercontent.com/6781980/61026238-722e8380-a3e5-11e9-9402-1942634fb538.png)
![企业微信截图_09406a3f-e276-45a3-a9ac-d757fefd46fe](https://user-images.githubusercontent.com/6781980/61026241-7490dd80-a3e5-11e9-89b2-c7c19f95504b.png)

**Comment by chenshuai2144** [comment]
给你写了个 demo，看一下
