### ISSUE TITLE
V4 prettier 不生效

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#4788]
在 V4 里面执行 npm run  prettier 以后，再执行  yarn run lint:prettier 还是提示有许多的文件is not prettier.

![image](https://user-images.githubusercontent.com/24469601/61030189-6e9ffa00-a3ef-11e9-82c6-d561f9e853d9.png)

**Comment by chenshuai2144** [comment]
试试这样呢 
`   "prettier": "prettier -c --write ‘**/*’”,`
增加一个单引号
