### ISSUE TITLE
Unable to setup multiple layouts 

### ISSUE THREAD

**Issue by mihai-cloudbrick** [ant-design/ant-design-pro#4792]
Hi 
Im trying to setup multiple layouts , using the areas principle , one for the frontend , one for user private area and and admin area. I followed the documentation and created something similar
The config looks like this :
export default [
  {
    //app
    path: '/',
    component: '../layouts/BasicLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [
      {
        path: '/',
        name: 'welcome',
        icon: 'smile',
        component: './public/Welcome',
      },
      {
        component: './404',
      },
    ],
  },
  // admin
  {
    //app
    path: '/admin',
    component: '../layouts/AdminLayout',
    Routes: ['src/pages/Authorized'],
    authority: ['admin', 'user'],
    routes: [
      {
        path: '/admin',
        name: 'welcome',
        icon: 'smile',
        component: './admin/Welcome',
      },
      {
        component: './404',
      },
    ],
  },

  {
    component: './404',
  },
]
the .umi/router.js its generated like this : 

import React from 'react';
import { Router as DefaultRouter, Route, Switch } from 'react-router-dom';
import dynamic from 'umi/dynamic';
import renderRoutes from 'umi/lib/renderRoutes';
import history from '@tmp/history';
import RendererWrapper0 from 'E:/Projects/MediaBrick/MediaBrick/ui/src/pages/.umi/LocaleWrapper.jsx'
import _dvaDynamic from 'dva/dynamic'

const Router = require('dva/router').routerRedux.ConnectedRouter;

const routes = [
  {
    "path": "/",
    "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "layouts__BasicLayout" */'../../layouts/BasicLayout'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../../layouts/BasicLayout').default,
    "Routes": [require('../Authorized').default],
    "authority": [
      "admin",
      "user"
    ],
    "routes": [
      {
        "path": "/",
        "name": "welcome",
        "icon": "smile",
        "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "p__public__Welcome" */'../public/Welcome'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../public/Welcome').default,
        "exact": true
      },
      {
        "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "p__404" */'../404'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../404').default,
        "exact": true
      },
      {
        "component": () => React.createElement(require('E:/Projects/MediaBrick/MediaBrick/ui/node_modules/umi-build-dev/lib/plugins/404/NotFound.js').default, { pagesPath: 'src/pages', hasRoutesInConfig: true })
      }
    ]
  },
  {
    "path": "/admin",
    "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "layouts__BlankLayout" */'../../layouts/BlankLayout'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../../layouts/BlankLayout').default,
    "Routes": [require('../Authorized').default],
    "authority": [
      "admin",
      "user"
    ],
    "routes": [
      {
        "path": "/admin",
        "name": "welcome",
        "icon": "smile",
        "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "p__admin__Welcome" */'../admin/Welcome'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../admin/Welcome').default,
        "exact": true
      },
      {
        "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "p__404" */'../404'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../404').default,
        "exact": true
      },
      {
        "component": () => React.createElement(require('E:/Projects/MediaBrick/MediaBrick/ui/node_modules/umi-build-dev/lib/plugins/404/NotFound.js').default, { pagesPath: 'src/pages', hasRoutesInConfig: true })
      }
    ]
  },
  {
    "component": __IS_BROWSER
    ? _dvaDynamic({
      
      component: () => import(/* webpackChunkName: "p__404" */'../404'),
      LoadingComponent: require('E:/Projects/MediaBrick/MediaBrick/ui/src/components/PageLoading/index').default,
    })
    : require('../404').default,
    "exact": true
  },
  {
    "component": () => React.createElement(require('E:/Projects/MediaBrick/MediaBrick/ui/node_modules/umi-build-dev/lib/plugins/404/NotFound.js').default, { pagesPath: 'src/pages', hasRoutesInConfig: true })
  }
];
window.g_routes = routes;
const plugins = require('umi/_runtimePlugin');
plugins.applyForEach('patchRoutes', { initialValue: routes });

// route change handler
function routeChangeHandler(location, action) {
  plugins.applyForEach('onRouteChange', {
    initialValue: {
      routes,
      location,
      action,
    },
  });
}
history.listen(routeChangeHandler);
routeChangeHandler(history.location);

export { routes };

export default function RouterWrapper(props = {}) {
  return (
<RendererWrapper0>
          <Router history={history}>
      { renderRoutes(routes, props) }
    </Router>
        </RendererWrapper0>
  );
}

The problem is this. When i go to localhost:port/ i get the basic layout , but when i navigate to localhost:port/admin i get 404 

There's not a page yet at /admin.

Create a React.js component in your pages directory at src/pages/admin.js and configure the route in config file then this page will automatically refresh to show the new page component you created.
Your Routes

    /
        /
    /admin
        /admin

the folder view its this 

![image](https://user-images.githubusercontent.com/43190955/61096527-967b7600-a460-11e9-9591-353528b7f1fc.png)

any ideea how to fix this.?

**Comment by chenshuai2144** [comment]
Put admin to the front.

```
/admin
/
   /basic
```

**Comment by mihai-cloudbrick** [comment]
Thanks, that works, looks like the order of the routes does count. You should update the documentation also so.
