### ISSUE TITLE
npm run fetch:blocks安装成功，文件夹为空

### ISSUE THREAD

**Issue by caijing0828** [ant-design/ant-design-pro#4793]
![image](https://user-images.githubusercontent.com/52524222/61107536-bcca0180-a4b2-11e9-92ab-220b0e67d4fc.png)
![image](https://user-images.githubusercontent.com/52524222/61107548-c489a600-a4b2-11e9-90a4-e51ac2885e6d.png)

**Comment by ght19970126** [comment]
yarn cnpm npm 都试一下把

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4642
