### ISSUE TITLE
V4 ts版本 异常处理有问题，后端返回400但是进不去

### ISSUE THREAD

**Issue by yangdachu** [ant-design/ant-design-pro#4794]
#4326 #4543 都有类似的问题

![image](https://user-images.githubusercontent.com/23580181/61109636-f7826880-a4b7-11e9-9d3e-93666783796a.png)
![image](https://user-images.githubusercontent.com/23580181/61109656-ff420d00-a4b7-11e9-8f37-e647038b2e2b.png)

**Comment by fjnetinfo** [comment]
我也遇到这个问题了。求解

**Comment by fjnetinfo** [comment]
有人提供一下怎么修改吗？

**Comment by fjnetinfo** [comment]
![Screen Shot 2019-07-12 at 9 09 17 PM](https://user-images.githubusercontent.com/51048705/61130479-57ddce00-a4e9-11e9-992f-14a7442af3ac.png)

**Comment by fjnetinfo** [comment]
数据是有返回，想弹个提示不知道在哪处理。直接就报这个错。

**Comment by clock157** [comment]
你们能提供一个可以访问的有问题的页面或者 repo 吗？我本地没有模拟出来

**Comment by clock157** [comment]
好像找到问题了，我跟一下

**Comment by clock157** [comment]
可能不是同一个问题，试着给requst 添加参数  `mode: 'no-cors'` 看能解决吗，如果不能，请帖下 network 和一个可重现问题的最小demo，帮助解决问题。

**Comment by WuJiY** [comment]
> 你们能提供一个可以访问的有问题的页面或者 repo 吗？我本地没有模拟出来

就是后台返回的状态码400，在umi request errorhandler里捕捉不到。因为后台返回了错误提示信息，需要统一处理。比如 用户输入密码字数太少或者不正确，后台返回个提示“密码不正确”并返回错误码400。类似这样的400错误，提示信息需要在errhandle里统一处理

**Comment by fjnetinfo** [comment]
其实我也没做什么特别的处理。就是模版工程请求了一下服务端的接口。我把我的request。ts发上来

**Comment by fjnetinfo** [comment]
[request.ts.zip](https://github.com/ant-design/ant-design-pro/files/3388786/request.ts.zip)

**Comment by fjnetinfo** [comment]
都是本地工程，没有demo。要的话只能把整个本地工程先传上来

**Comment by fjnetinfo** [comment]
![Screen Shot 2019-07-13 at 9 05 10 PM](https://user-images.githubusercontent.com/51048705/61172054-11a07180-a5b2-11e9-9103-d070b490fa20.png)
只要是这种接口都不行。

**Comment by fjnetinfo** [comment]
服务端要把所有的接口无论对错都改为 返回200，前端才能取值，然后根据code处理。只要服务端返回400，就出现上面的问题。

**Comment by fjnetinfo** [comment]
DELETE http://47.96.120.4:9998/ams/department/3 
你用这个接口试一下，什么参数都不传。就是报400. 随便用模版工程就可以。看看能不能重现。

**Comment by fjnetinfo** [comment]
出现这个问题后，再发请求就永远都不会发起请求了。需要刷新后才能再发。

**Comment by fjnetinfo** [comment]
![Screen Shot 2019-07-14 at 1 19 05 AM](https://user-images.githubusercontent.com/51048705/61174620-6ef9ea00-a5d5-11e9-8d25-876d0882450b.png)

build 后的版本会弹这个？ 说明build后的是正常的？

**Comment by fjnetinfo** [comment]
![Screen Shot 2019-07-14 at 2 38 29 PM](https://user-images.githubusercontent.com/51048705/61180175-12361800-a645-11e9-955b-638b8dd37387.png)
errorHandler 有设置但取到的是null。 调试发现服务端的数据data是有在，但是不知道应该怎么取到。

**Comment by fjnetinfo** [comment]
![1563087424463](https://user-images.githubusercontent.com/51048705/61180355-adc88800-a647-11e9-832d-5768e3468740.jpg)

![1563087640581](https://user-images.githubusercontent.com/51048705/61180396-30514780-a648-11e9-8811-66a575e26126.jpg)

这种设置可以。剩下一个问题就是一旦出现了400，这个请求就再也不会发起，loading状态也是一直都是true，继续研究中。

**Comment by fjnetinfo** [comment]
![image](https://user-images.githubusercontent.com/51048705/61180447-faf92980-a648-11e9-97d3-08801734a45f.png)

加个return data。 终于通了。不晓得是不是规范的，研究老半天不容易。 如果是错的，请大神帮忙看看。

**Comment by clock157** [comment]
@fjnetinfo 你这里 return data，那在调用那里得到这个值，如果没有 return，调用那里就是一个 undefined。readme里有写

**Comment by clock157** [comment]
@fjnetinfo 请问你是怎样出现这个报错的？包括 @yangdachu，能否说明一下或者提供完整 repo，因为我无法重现这个问题。或者加我钉钉`k9qari9`
![image](https://user-images.githubusercontent.com/4002237/61184352-51815a80-a67f-11e9-9077-305f5c2b1790.png)

**Comment by yangdachu** [comment]
@clock157 你可以本地创建一个ts版本的新项目，在errorHandler里断点就好了

**Comment by diangong** [comment]
服务器返回401也类似问题

**Comment by chenshuai2144** [comment]
看起来是 pro 的问题。 错误之后没有进行 return 数据。

**Comment by yangdachu** [comment]
@chenshuai2144 按照你的方法return数据依然不行
![image](https://user-images.githubusercontent.com/23580181/61197651-bd5bd580-a708-11e9-8121-87ab8909e5e4.png)

![image](https://user-images.githubusercontent.com/23580181/61197657-c482e380-a708-11e9-9890-ca5e6170ba12.png)

**Comment by chenshuai2144** [comment]
@clock157 看你的了。是不是把这个错误吃掉，不要抛出来交给用户自行处理

**Comment by chenshuai2144** [comment]
@yangdachu  在请求中.catch 能拿到吗

**Comment by waylon-edmodo** [comment]
https://github.com/ant-design/ant-design-pro/issues/4794#issuecomment-511178842
https://github.com/ant-design/ant-design-pro/issues/4794#issuecomment-511179105
我一共改了这两个地方才终于正常了呀。
我需要处理服务端返回的data。因为那里面包含了一些提示语是我要的。最好不好吃掉。

**Comment by waylon-edmodo** [comment]
> @fjnetinfo 你这里 return data，那在调用那里得到这个值，如果没有 return，调用那里就是一个 undefined。readme里有写

就是得不到undefined。那边卡住了进不去。所以请求就无法再次发起了，loading状态一直不会变。

**Comment by waylon-edmodo** [comment]
> ![1563087424463](https://user-images.githubusercontent.com/51048705/61180355-adc88800-a647-11e9-832d-5768e3468740.jpg)
> 
> ![1563087640581](https://user-images.githubusercontent.com/51048705/61180396-30514780-a648-11e9-8811-66a575e26126.jpg)
> 
> 这种设置可以。剩下一个问题就是一旦出现了400，这个请求就再也不会发起，loading状态也是一直都是true，继续研究中。

errorhandler如果不设置，model那边也是会卡住永远不会得到undefined的值。设置在extend在yarn start下又无效，build后有效。 我改成直接设置在option上可以进去。

**Comment by waylon-edmodo** [comment]
工程真的没有特别的。就是 create umi，然后请求服务端接口，比如: 
DELETE http://47.96.120.4:9998/ams/department/3
我没有钉钉，我看下整一个。

**Comment by waylon-edmodo** [comment]
晕。我刚刚同步的工程居然可以。醉了。

**Comment by yangdachu** [comment]
> 晕。我刚刚同步的工程居然可以。醉了。还想搞个demo给你们看下帮忙定位下具体问题是啥。 yarn create umi，新搞了个工程，贴上request。可以。。。。。。。
> 
> 这个工程其他地方有没有区别不知道，request里面多了return response了。我原来同步的工程没有这个。 不过我这边是希望return服务端返回的数据，所以要改为data。
> 
> 新工程这个放在extend也可以。
> /**
> 
> * 配置request请求时的默认参数
>   */
>   const request = extend({
>   errorHandler, // 默认错误处理
>   // credentials: 'include', // 默认请求是否带上cookie
>   });
> 
> 我就没有问题了。。。。 得研究一下怎么能够高效的跟最新代码同步，现在纯人工？

新建一个就可以了？ 我新建一个试试。。。

**Comment by yangdachu** [comment]
@chenshuai2144 在.catch里可以的
![image](https://user-images.githubusercontent.com/23580181/61280895-44817a00-a7eb-11e9-872c-c948881642c8.png)

**Comment by yangdachu** [comment]
@fjnetinfo 我刚新建了项目还是一样的，仍然进不去errorHandler

**Comment by chenshuai2144** [comment]
@yangdachu https://github.com/umijs/umi-request/blob/194e5fa118ce6f542f0bec333498bd3da0746a15/src/wrapped-fetch.js#L133

看看 errorHandler的触发条件

**Comment by clock157** [comment]
@yangdachu 你的问题是没有使用 utils/request.ts，直接使用 umi-request 当然不会触发 errorHandler。
![image](https://user-images.githubusercontent.com/4002237/61284864-6fbb9780-a7f2-11e9-9df5-4667a4d8b8a8.png)

**Comment by yangdachu** [comment]
@clock157 @chenshuai2144 多谢

**Comment by clock157** [comment]
@waylon-edmodo 可能是同样的问题，排查下，如果无法解决可以加我钉钉

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-plugin-pro-block

那就是这个插件表现异常了

**Comment by waylon-edmodo** [comment]
> @yangdachu 你的问题是没有使用 utils/request.ts，直接使用 umi-request 当然不会触发 errorHandler。
> ![image](https://user-images.githubusercontent.com/4002237/61284864-6fbb9780-a7f2-11e9-9df5-4667a4d8b8a8.png)

大神。这个才是正解

**Comment by yangdachu** [comment]
> > @yangdachu 你的问题是没有使用 utils/request.ts，直接使用 umi-request 当然不会触发 errorHandler。
> > ![image](https://user-images.githubusercontent.com/4002237/61284864-6fbb9780-a7f2-11e9-9df5-4667a4d8b8a8.png)
> 
> 大神。这个才是正解。 通过add block进来的模块都有这问题。

钉钉有吗？交流一下antd pro?

**Comment by tsuyoii** [comment]
> ![image](https://user-images.githubusercontent.com/51048705/61180447-faf92980-a648-11e9-97d3-08801734a45f.png)
> 
> 加个return data。 终于通了。不晓得是不是规范的，研究老半天不容易。 如果是错的，请大神帮忙看看。

大佬，我用你这个方法成功了，我可以记录到博客上吗，我会注明来源的
