### ISSUE TITLE
4.0右上角用户名不弹出下拉菜单

### ISSUE THREAD

**Issue by cn-ygf** [ant-design/ant-design-pro#4796]
![1562916109(1)](https://user-images.githubusercontent.com/20332876/61109971-ca828580-a4b8-11e9-8e97-8fbdeb8ed867.jpg)

**Comment by ght19970126** [comment]
目录src>components>globalheader>rightcontent.tsx   中的      <Avatar />  改为      <Avatar menu />

**Comment by ght19970126** [comment]
目录src>components>globalheader>rightcontent.tsx 中的       `<Avatar  />`  改为`      <Avatar menu />
`

**Comment by chenshuai2144** [comment]
这个是故意做的 因为默认是什么都没有的
