### ISSUE TITLE
将 block 添加到项目中后，如果 block 的代码有变化，应该怎样更新项目中 block 的代码？

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4797]
第二次添加同一个 block 会提示我，名字相同让我重新输入，重新输入个名字过后，会重新建立一个文件夹，但这并不是我想要的，我只是想将第二次 add 的代码覆盖掉第一次的
![image](https://user-images.githubusercontent.com/51696361/61111051-3534c080-a4bb-11e9-885e-befc2dc6673d.png)
![image](https://user-images.githubusercontent.com/51696361/61111092-5695ac80-a4bb-11e9-90d5-7b9cf1d3d8df.png)
![image](https://user-images.githubusercontent.com/51696361/61111105-61504180-a4bb-11e9-99d7-fa9972548eee.png)

**Comment by Benpaodejiezai** [comment]
是删掉。。重新 add吗  =，=

**Comment by chenshuai2144** [comment]
不更新了，区块就是为了让你改变的。

**Comment by BANG666** [comment]
请问怎么解决更新区块的

**Comment by Benpaodejiezai** [comment]
> 请问怎么解决更新区块的

重新 add 的
