### ISSUE TITLE
是否可以提供一个只维护了基础框架的版本

### ISSUE THREAD

**Issue by liumin1128** [ant-design/ant-design-pro#48]
如题，开箱即用是挺好的，但一上来就给这么多，删起来也是怪麻烦的😂...
如果能有一套，只有基础框架，包含侧边、主体什么的空项目就最好了。

感谢分享，加油😜

**Comment by nikogu** [comment]
会后续会提供多种模板选择，期望通过工具配置实现：https://github.com/ant-design/ant-design-pro-cli

**Comment by afc163** [comment]
可以先自行移除。
