### ISSUE TITLE
how to install weak mode 

### ISSUE THREAD

**Issue by aminabvaal** [ant-design/ant-design-pro#4800]
![image](https://user-images.githubusercontent.com/31241289/61129751-53ee8380-a4ca-11e9-9bbb-3cb1e3a7f505.png)

**Comment by chenshuai2144** [comment]
add this style

https://github.com/ant-design/ant-design-pro/blob/4cb89d56559cb77543025293750e7b894cc0caee/src/global.less#L9

**Comment by loveyandex** [comment]
@chenshuai2144  
this file existed there before and these lines was there: 
.colorWeak {
  filter: invert(80%);
}

but mode is not weak ...
what i have to do to make this weak ??
