### ISSUE TITLE
路由中去除权限判定还是去验证权限，注释默认权限查看所有无法登陆

### ISSUE THREAD

**Issue by GreatGodJackChen** [ant-design/ant-design-pro#4803]
路由中去除权限判定还是去验证权限，注释查看所有无法登陆
/ 没有判定权限.默认查看所有
  //Retirement authority, return target;
  //if (!authority) {
  //  return target;
  //}
路由配置中删除权限还是要去判定权限

**Comment by poyiding** [comment]
如果不想加权限，路由中不要配置权限

**Comment by GreatGodJackChen** [comment]
路由自动生成的，不知道他们在哪里写的，写了个动态菜单

**Comment by poyiding** [comment]
你去了解一下umi就知道，路由自动生成在config里。
