### ISSUE TITLE
v4 顶部菜单布局内容区域和菜单没有对齐

### ISSUE THREAD

**Issue by yanthink** [ant-design/ant-design-pro#4805]
![image](https://user-images.githubusercontent.com/9098321/61197101-8afca900-a705-11e9-9365-d6cf14afd24f.png)

**Comment by chenshuai2144** [comment]
pageHeader 有 对应的 padding  
`padding: 16px 24px;`

**Comment by yanthink** [comment]
> pageHeader 有 对应的 padding
> `padding: 16px 24px;`
我用 PageHeaderWrapper 这个组件设置 style={{padding: '16px 0'}}，但是这个只对header有效，content两边的padding还是存在

**Comment by chenshuai2144** [comment]
直接使用 css 进行覆盖好了
