### ISSUE TITLE
v4 动态菜单 点击自定义逻辑 点击没有高亮

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design-pro#4808]

**Comment by LiYanGang** [comment]
MeunItemRender = (_,dom)=><div onClick={myclick}>{dom}</div>采用这个方法实现了点击自定义逻辑，但是点击没有高亮，如何实现高亮

**Comment by chenshuai2144** [comment]
你是不是取消了 js 的事件的冒泡。导致 onMenuClick没有被处罚

**Comment by LiYanGang** [comment]
> 你是不是取消了 js 的事件的冒泡。导致 onMenuClick没有被触发

是的，阻止了冒泡事件，但是我关闭冒泡事件点击也没有高亮。我需要做什么额外处理吗？

**Comment by chenshuai2144** [comment]
给我个重现代码把.

**Comment by LiYanGang** [comment]
> 给我个重现代码把.

动态菜单 自定义点击逻辑必现
