### ISSUE TITLE
帮忙看下这个问题是不是在.dockerignore里面给过滤了 .umi .umi-production造成的呢？

### ISSUE THREAD

**Issue by cszo** [ant-design/ant-design-pro#4809]
> ant-design-pro@4.0.0 docker:dev D:\Users\Desktop\antd-pro\ant-design-pro4
> docker-compose -f ./docker/docker-compose.dev.yml up

Starting ant-design-pro_dev ... done
Attaching to ant-design-pro_dev
ant-design-pro_dev    |
ant-design-pro_dev    | > ant-design-pro@4.0.0 start /usr/src/app
ant-design-pro_dev    | > umi dev
ant-design-pro_dev    |

ant-design-pro_dev    | ✖ Webpack
ant-design-pro_dev    |   Compiled with some errors in 22.78s
ant-design-pro_dev    |
ant-design-pro_dev    | Starting the development server...
ant-design-pro_dev    |
ant-design-pro_dev    | Extracted theme color css content length: 9665
ant-design-pro_dev    |  ERROR  Failed to compile with 1 errors10:11:58 AM
ant-design-pro_dev    |
ant-design-pro_dev    | This relative module was not found:
ant-design-pro_dev    |
ant-design-pro_dev    | * ../list/search in ./src/pages/.umi/router.js
ant-design-pro_dev    |
ant-design-pro_dev    |  ERROR CODE  ERR_WEBPACK_MODULE_NOT_FOUND
ant-design-pro_dev    |
ant-design-pro_dev    |  DETAILS
ant-design-pro_dev    |
ant-design-pro_dev    | ## Possible Reasons
ant-design-pro_dev    |
ant-design-pro_dev    |     1. The file does not exist
ant-design-pro_dev    |     2. Case problem
ant-design-pro_dev    |
ant-design-pro_dev    | If the build under mac is successful and the build fails under linux or on the cloud build platform, it mus
t be case problem.
ant-design-pro_dev    |
ant-design-pro_dev    | ## Solution
ant-design-pro_dev    |
ant-design-pro_dev    | If it is a case, please double check that the import or require file and the target file are in the same ca
se.
ant-design-pro_dev    |
ant-design-pro_dev    |
ant-design-pro_dev    |  WAIT  Compiling...10:11:58 AM

**Comment by chenshuai2144** [comment]
../list/search 这个文件不存在造成的。

**Comment by cszo** [comment]
> ../list/search 这个文件不存在造成的。
> .umi 是自动生成的

嗯 感谢  估计代码没拉全
