### ISSUE TITLE
调整子菜单的位置，导致点击该菜单会跳转到其它父级菜单

### ISSUE THREAD

**Issue by Gre-Z** [ant-design/ant-design-pro#4811]
比如 router.config.js 的配置是这样子的
{
        name: 'exception',
        icon: 'warning',
        path: '/exception',
        routes: [
          {
            path: '/exception/403',
            name: 'not-permission',
            component: './Exception/403',
          },
        ],
 },
{
        authority: ['admin'],
        path:"/authority",
        name:"权限管理",
        routes:[
          {
            path:"/authority/role",
            name:"角色",
            component:"./Authority/Role",
          },
        ],
},

后端返回的时候将 /exception/403 设置成 ”/authority“ 的子级菜单，也就是后台返回的时候“/exception/403” 跟 “/authority/role” 都是 ”/authority“ 这个父级菜单的子菜单，显示是正常的。
但是当我点击了 “/exception/403”  却不会展开这个标签 而是收缩了起来
[https://u20582072.ctfile.com/fs/20582072-387863347](url)
[https://u20582072.ctfile.com/fs/20582072-387863346](url)

**Comment by chenshuai2144** [comment]
菜单的算法是根据 pathname 来判断是否该展开收起的。

/exception/403 和 /authority 不会被认为是 父子关系

**Comment by pkaq** [comment]
这个设计确实有很大问题 正常情况下菜单是由后台维护的 甚至在某些系统中 不同角色的菜单规划和名称也是不同的 
这样每次后台进行菜单路径调整时为了让前台正确展开 不得不改动前台代码重新发布

**Comment by chenshuai2144** [comment]
那需要自己实现一下了，太灵活的东西无法预设

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/pull/85

这个 pr 可以实现你们的需求
