### ISSUE TITLE
v4版本如何添加全局风格设置？

### ISSUE THREAD

**Issue by anshengme** [ant-design/ant-design-pro#4812]
<img width="1381" alt="WX20190715-234104@2x" src="https://user-images.githubusercontent.com/16428340/61229142-346d8a00-a75a-11e9-91a2-5029195e31cf.png">

**Comment by anshengme** [comment]
![WX20190715-234104@2x](https://user-images.githubusercontent.com/16428340/61229206-59fa9380-a75a-11e9-8a5f-6302b28f0fdc.png)

默认的版本中貌似没有这个选项

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout#settingdrawer
引入这个组件即可
