### ISSUE TITLE
项目第一次安装提交，npm run lint-staged:js 报一堆错

### ISSUE THREAD

**Issue by woohs** [ant-design/ant-design-pro#4813]
### 问题描述：
根据脚手架第一次安装antd pro，并提交代码，就会触发`lint-staged`代码检查，然后就报了一堆错。。
![image](https://user-images.githubusercontent.com/31387031/61259651-b2a74c00-a7ad-11e9-9ec6-1217023aad46.png)

### 期望现象
第一次安装脚手架并提交代码不会报错。

**Comment by chenshuai2144** [comment]
重新安装一下 create-umi。
ts 转化成 js 之后空行丢失了

**Comment by huqinlou0123** [comment]
碰到同样问题

**Comment by woohs** [comment]
最后还是重新更新脚手架，重新部署，就没这个问题了

**Comment by BenlovedLamphere** [comment]
遇到同样问题，git commit -m 时报如上错误，用　cnpm install create umi --save -g　也没解决

**Comment by chenshuai2144** [comment]
最好先删除一下全局的 create-umi。
https://www.npmjs.com/package/create-umi

**Comment by BenlovedLamphere** [comment]
> 最好先删除一下全局的 create-umi。
> https://www.npmjs.com/package/create-umi

我后来把package.json中的这几行删了，git commit 就成功了：
  "husky": { "hooks": { "pre-commit": "npm run lint-staged" } },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,tsx,ts,less,md,json}": ["prettier --write", "git add"],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.{ts,tsx}": "npm run lint-staged:js"
  },

想问我删除的这几行会不会有什么影响？

BTY uninstall -g 之后重新install -g 并　create umi也有error，我就没弄了，直接去package.json里删了那几行。

**Comment by pointline** [comment]
遇到同样问题，请问具体怎么解决的呢？

**Comment by huqinlou0123** [comment]
怎么解决自己研究，反正官方不会理你.

**Comment by Jiojiobba** [comment]
删掉 .git文件夹下的hooks文件夹下的pre-commit文件就行了

**Comment by Linbubin** [comment]
1. 不进行eslint检查。
2. 用ts别转成js。

**Comment by zbncs** [comment]
> 删掉 .git文件夹下的hooks文件夹下的pre-commit文件就行了

这个就可以

**Comment by damin-zhang** [comment]
把gitHooks的`commit-msg`钩子修改成`pre-commit`然后再把"lint-staged"对象中的js, jsx, ts等代码规范检测去掉就可以.
修改如下:

```json
- "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js"
+ "**/*.{js,jsx,ts,tsx}": ["prettier --write"]
```
```json
- "gitHooks": {
    "pre-commit": "fabric verify-commit"
  }
  
+ "gitHooks": {
    "pre-commit": "lint-staged"
  }
```

**Comment by ZengJun-cloud** [comment]
> 把gitHooks的`commit-msg`钩子修改成`pre-commit`然后再把"lint-staged"对象中的js, jsx, ts等代码规范检测去掉就可以.
> 修改如下:
> 
> ```json
> - "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
> - "**/*.less": "stylelint --syntax less",
> + "**/*.{js,jsx,ts,tsx}": ["prettier --write"],
> ```
> 
> ```json
> - "gitHooks": {
>     "pre-commit": "fabric verify-commit"
>   }
>   
> + "gitHooks": {
>     "pre-commit": "lint-staged"
>   }
> ```

棒棒哒
