### ISSUE TITLE
左侧菜单栏中的包含子菜单的菜单如何在面包屑中设置不允许点击

### ISSUE THREAD

**Issue by blackholll** [ant-design/ant-design-pro#4815]
包含子菜单的菜单在config.ts中没有指定component。  但是子页面的面包屑中该菜单是可以点击的，点击后就会出现404的情况。 请问如何设置没有component的菜单在面包屑中不允许点击？ 或者有什么其他好的做法？
```
{
          path: '/workflow',
          name: 'workflow_manage',
          icon: 'smile',
          // 没有指定component
          routes: [
            {
              path: 'config',
              name: 'worflow_config',
              icon: 'smile',
              component: './workflow/WorkflowConfig',
            }]
}
```
如上config.ts。点击面包屑中的workflow_manage 就会报404

**Comment by ght19970126** [comment]
现在应该是不可以的，你可以写一个路由重定到子级第一个页面

**Comment by chenshuai2144** [comment]
https://pro.ant.design/blog/new-pro-use-cn

看看这个

**Comment by liu11hao11** [comment]
itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
在ProLayout组件中传入自己的props参数
