### ISSUE TITLE
使用 npx umi block add 安装区块一直卡死在git fetch

### ISSUE THREAD

**Issue by woohs** [ant-design/ant-design-pro#4818]
使用命令：`npx umi block add ` 安装区块一直卡在git fetch不动。
![image](https://user-images.githubusercontent.com/31387031/61264376-ef2f7380-a7be-11e9-9790-54b9bf743e09.png)

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/issues/4823
