### ISSUE TITLE
win10,npm run fetch:blocks 之后 无法start

### ISSUE THREAD

**Issue by tombear110** [ant-design/ant-design-pro#4819]
报错：如果是大小写问题，请仔细检查import或require的文件和目标文件大小写是否一致

**Comment by tombear110** [comment]
仔细检查了，没发现任何异常。
操作步骤也是按照官方文档一步步来，可以run一个helloword出来，但是添加全部模块后，就start报错

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4823
https://github.com/ant-design/ant-design-pro/issues/4642

fetch:blocks 失败了

**Comment by QijunChiang** [comment]
解决经验：
1、下载https://github.com/ant-design/pro-blocks
2、将下载的文件解压拷贝到C:\Users\用户名.umi\blocks\github.com\ant-design\pro-blocks文件夹下
3、执行npm run fetch:blocks

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/issues/4823
