### ISSUE TITLE
运行cnpm run fetch:blocks，提示 error HTTPError: Response code 403

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design-pro#4821]
为什么我把项目download下跑起来后跟demo不一样的？发现少了很多模块东西，demo相应的模块貌似我在代码里面也没有找到

**Comment by tombear110** [comment]
默认只有一个欢迎页，其他的要自己下。基于区块和自定义开发两种。
我卡在了下载区块这里，各种error。

**Comment by dongkeng001** [comment]
> 默认只有一个欢迎页，其他的要自己下。基于区块和自定义开发两种。
> 我卡在了下载区块这里，各种error。


按照文档提供的命令去安装，发现装不了区块

$ cnpm run fetch:blocks

> ant-design-pro@4.0.0 fetch:blocks D:\ant-design-pro-master
> fetch-blocks

- 🧐  find config.ts ...
√ 🧐  find config.ts ...
(node:9456) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined


$ umi block list
- 🚣 fetch block list
√ 🚣 fetch block list
- 🔍 find block list form https://github.com/ant-design/pro-blocks
×  error     HTTPError: Response code 403 (Forbidden)

**Comment by dongkeng001** [comment]
发现命令多执行几次就可以正常download了

**Comment by dongkeng001** [comment]
> 发现命令多执行几次就可以正常download了
