### ISSUE TITLE
请问你们是怎么让npm run fetch:blocks快速完成的？

### ISSUE THREAD

**Issue by Helaiqu** [ant-design/ant-design-pro#4822]
请问你们是怎么让npm run fetch:blocks快速完成的？
环境：npm已经设置淘宝镜像源，科学上网已开。
情况：我在执行npm run fetch:blocks后7-8个小时依然无法下载完。
![T2AU)X3IEDB_)Q4K%I8)I(4](https://user-images.githubusercontent.com/16275345/61280162-fc158c80-a7e9-11e9-967b-26b9cc03c6b9.png)
图片中是我执行6-7个小时才下载这么点。
极慢！！

**Comment by diangong** [comment]
选择美国人睡觉的时间下载😀。昨天下午6点我用普通100M宽带fetch:blocks用了15分钟左右。

**Comment by youqingxiaozhua** [comment]
居然耐心等了这么久，真不知道他是咋下数据的……
