### ISSUE TITLE
umi block 国内用户加速方案讨论

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#4823]
GitHub 在不翻墙的情况下很慢，还容易失败。

- https://github.com/ant-design/ant-design-pro/issues/4821
- https://github.com/ant-design/ant-design-pro/issues/4774
- https://github.com/ant-design/ant-design-pro/issues/4819
- https://github.com/ant-design/ant-design-pro/issues/4818
- https://github.com/ant-design/ant-design-pro/issues/4822
- https://github.com/ant-design/ant-design-pro/issues/4793
- https://github.com/ant-design/ant-design-pro/issues/4785
- https://github.com/ant-design/ant-design-pro/issues/4642
- https://github.com/ant-design/ant-design-pro/issues/4804

<img width="862" alt="image" src="https://user-images.githubusercontent.com/507615/61282920-cfb03f00-a7ee-11e9-9aca-ad74c31669b0.png">

**Comment by afc163** [comment]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/507615/61281055-8b6f6f80-a7eb-11e9-8d95-42b848ccfc2e.png">

github.com.cnpmjs.org 巨快无比。

**Comment by afc163** [comment]
```
time git clone https://github.com.cnpmjs.org/ant-design/pro-blocks.git test1 --depth=1

time git clone https://github.com/ant-design/pro-blocks.git test2 --depth=1
```

欢迎大家对比一下不同网络下的速度。

**Comment by Helaiqu** [comment]
👍👍👍解决燃眉之急。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/61282060-464c3d00-a7ed-11e9-99da-d451d1b9de76.png)


速度感觉差不多，win+网络差的用户来试一下

**Comment by ycjcl868** [comment]
可能是内网有加速吧，我测的是:

```bash
$ git clone https://github.com.cnpmjs.org/ant-design/pro-blocks.git test1 --depth=1
Receiving objects:  29% (147/505), 676.00 KiB | 252.00 KiB/s

$ git clone https://github.com/ant-design/pro-blocks.git test2 --depth=1

Receiving objects:  68% (344/505), 1.25 MiB | 800.00 KiB/s
```

**Comment by icaife** [comment]
```
➜  test git clone https://github.com.cnpmjs.org/ant-design/pro-blocks.git test1 --depth=1
正克隆到 'test1'...
remote: Enumerating objects: 505, done.
remote: Counting objects: 100% (505/505), done.
remote: Compressing objects: 100% (433/433), done.
remote: Total 505 (delta 108), reused 236 (delta 56), pack-reused 0
接收对象中: 100% (505/505), 3.26 MiB | 337.00 KiB/s, 完成.
处理 delta 中: 100% (108/108), 完成.

➜  test git clone https://github.com/ant-design/pro-blocks.git test2 --depth=1
正克隆到 'test2'...
remote: Enumerating objects: 505, done.
remote: Counting objects: 100% (505/505), done.
remote: Compressing objects: 100% (433/433), done.
remote: Total 505 (delta 108), reused 236 (delta 56), pack-reused 0
接收对象中: 100% (505/505), 3.26 MiB | 880.00 KiB/s, 完成.
处理 delta 中: 100% (108/108), 完成.
```

**Comment by chenshuai2144** [comment]
长城宽带

![image](https://user-images.githubusercontent.com/8186664/61290509-9b447f00-a7fe-11e9-9587-14aaf5507c83.png)

**Comment by afc163** [comment]
@chenshuai2144 没有对比数据。

**Comment by afc163** [comment]
@icaife 内网用户就不用测了，内网 GitHub 有加速。

**Comment by liqianglai** [comment]
加速效果非常明显
![putao_2019-07-16_20-45-45](https://user-images.githubusercontent.com/7068847/61295483-b7e6b400-a80a-11e9-98ef-443a62834ae7.png)

**Comment by liqianglai** [comment]
![putao_2019-07-16_20-45-45](https://user-images.githubusercontent.com/7068847/61295582-f0868d80-a80a-11e9-8247-254716c5cf1b.png)

**Comment by afc163** [comment]
```
🌈  Projects  git clone https://github.com.cnpmjs.org/ant-design/pro-blocks.git test1 --depth=1
Cloning into 'test1'...
remote: Enumerating objects: 505, done.
remote: Counting objects: 100% (505/505), done.
remote: Compressing objects: 100% (433/433), done.
remote: Total 505 (delta 108), reused 236 (delta 56), pack-reused 0
Receiving objects: 100% (505/505), 3.26 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (108/108), done.
🌈  Projects  git clone https://github.com/ant-design/pro-blocks.git test2 --depth=1
Cloning into 'test2'...
remote: Enumerating objects: 505, done.
remote: Counting objects: 100% (505/505), done.
remote: Compressing objects: 100% (433/433), done.
Receiving objects:   9% (50/505), 340.00 KiB | 3.00 KiB/s  
```

不是一个级别的， @chenshuai2144 我们可以搞起了。

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/blob/fc624d4db5ec429dbeef3e012ae62ceca1e00fc6/packages/umi-build-dev/src/plugins/commands/block/download.js#L70

我们自己写个 git 解析库不是很好用，解析不了这个。我来个 pr

**Comment by afc163** [comment]
正好一起做了：https://github.com/umijs/umi/issues/2816

**Comment by hrj303662813** [comment]
请问，如何在使用npx umi block add  时，github.com变成github.com.cnpmjs.org？

**Comment by afc163** [comment]
@hrj303662813 敬请期待，我们正在搞。

**Comment by RunningCoderLee** [comment]
有个方法可以通过改 `host` 文件来加速对 github 网站的访问，下面的图是更改后和更改前的对比效果

![image](https://user-images.githubusercontent.com/13218863/61436968-8c7cda00-a96e-11e9-9c83-7bfc9d69a171.png)


具体更改方法如下：

1.  打开 `host` 文件，OSX 系统位置在`/etc/hosts`
2. 在文件末尾添加如下内容后保存退出
```
140.82.113.4    github.com
185.199.108.153 assets-cdn.github.com
185.199.109.153 assets-cdn.github.com
185.199.110.153 assets-cdn.github.com
185.199.111.153 assets-cdn.github.com
151.101.185.194 github.global.ssl.fastly.net
```
3. 运行命令 `sudo dscacheutil -flushcache ` 清除 DNS 缓存

之后就可以感受飞一般的感觉了 🤪


`github.com`，`assets-cdn.github.com`，`github.global.ssl.fastly.net` 这3个网址的 IP 可以通过 [这里](http://github.global.ssl.fastly.net.ipaddress.com/) 查询确认

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4878

**Comment by afc163** [comment]
@chenshuai2144 你要留一个结论说明，而不是直接关掉。

**Comment by chenshuai2144** [comment]
在 umi@2.8.13 中我们支持了字段切换 github 代理，一切都是无感知的。

**Comment by ruur** [comment]
@chenshuai2144 我这边测试了，在国内的环境下通过 `https://github.com.cnpmjs.org/ant-design/pro-blocks.git`下载会很快，直接通过github会很慢，翻墙之后通过这个地址则很慢。但是现在的`umi block add`是翻墙的环境下默认是`https://github.com.cnpmjs.org/ant-design/pro-blocks.git`，在国内默认是github的地址。刚好不能快速的下载。请问能在哪个地方通过配置选择从哪里下载吗？

**Comment by silianpan** [comment]
最后的结论是什么呢

**Comment by ruur** [comment]
@silianpan 据我这边的测试  默认走的下载链接刚好反了   你也试可以帮忙测试一下哈  验证下
正确的应该是：
国内环境： `github.com.cnpmjs.org`
国外环境：` github.com`

**Comment by silianpan** [comment]
@ruur 配置npm淘宝源，采用umi block list选择区块下载，不会有问题
