### ISSUE TITLE
详情页样式问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#4825]
- [ ] 按钮间距丢失。
- [ ] 响应式表现不佳，右侧操作不应该挤压左侧内容。

https://preview.pro.ant.design/profile/advanced

<img width="539" alt="image" src="https://user-images.githubusercontent.com/507615/61284396-73025380-a7f1-11e9-9eac-03c9a7dd79b3.png">

**Comment by chenshuai2144** [comment]
我处理过一次来着。我记得

**Comment by afc163** [comment]
小屏幕下 PageHeader title 和 extra 可以换行处理。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks/commit/97dc65db9575cd1ced05c91b411936bab9a5ec43

是工作台。

**Comment by chenshuai2144** [comment]
> 小屏幕下 PageHeader title 和 extra 可以换行处理。

全部收起来，做成一个下拉的按钮如何？

**Comment by afc163** [comment]
要动 js 会不会比较麻烦。

**Comment by chenshuai2144** [comment]
Layout 有这个能力，正好当做演示

**Comment by afc163** [comment]
PageHeader 组件应该有自己的响应式表现，不能依赖 Pro-Layout

**Comment by chenshuai2144** [comment]
PageHeader 的  extra 最好的处理方式是收起来。原来的 pro 的直接隐藏
PageHeader 中做可能有点重了

**Comment by afc163** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/507615/61346472-7518f080-a88b-11e9-931b-e47f6fe4c047.png">

也要做的，基础组件的响应式表现很重要，不然每个业务都要自己调。
