### ISSUE TITLE
请问如何共用父模块model?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [ant-design/ant-design-pro#4826]
我的目录如下
`
pages/list
pages/edit
`
浏览器直接打开edit时，需要获取list数据并更新store，但此时局部list model并未加载，不会有反应，
所以我把model移到了list与edit同级，这样两个model就可以共用父级的model了，但是我在edit的componentDidMount中dispatch一个'list/fetch', 我看见在redux 调试中一闪就回退了。。。。没任何效果。我试了一下setTimout 1秒再dispatch就有效果了，也不知道什么原因。目前我的解决办法是把model放到全局model下去加载，我不希望所有model都放在全局model呀，希望能给出原因和参考方案.

**Comment by chenshuai2144** [comment]
提到 src/model中就好了。
page 中的 model 是按需加载的。只有 page 加载才会加载 model

**Comment by sir-ran** [comment]
之前也有这种需求，要么提到全局model里边，要么关闭按需加载
