### ISSUE TITLE
yield put(routerRedux.replace(redirect || '/'))没有执行跳转

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design-pro#4828]
使用'yarn create umi'创建的项目，没有修改任何代码，mock模式下登录成功没有跳转到根路径'/'，发现这行代码‘yield put(routerRedux.replace(redirect || '/'))’没有效果

**Comment by jeffmxzhao** [comment]
出现同样的问题，V4 TypeScript版本，之前的版本没有这个问题

**Comment by jeffmxzhao** [comment]
@chenshuai2144 这个是bug么

**Comment by keke122765** [comment]
@chenshuai2144 这是bug么

**Comment by keke122765** [comment]
已找到问题，‘yield put(routerRedux.replace(redirect || '/'))’ 这段代码是有效果的，只不过因为授权逻辑出了问题导致没有权限 访问 `/` 这个路径，从而又返回了 /user/login，最终产生没有效果的假象。
ps：我是changeLoginStatus方法里的setAuthority参数没写对

**Comment by perfmlin** [comment]
// 之前加入这句。。。。。。
reloadAuthorized();

yield put(routerRedux.replace(redirect || '/'))

**Comment by keke122765** [comment]
@perfmlin 对对对 
https://github.com/ant-design/ant-design-pro/issues/4529#issuecomment-504024840
刷新权限这个bug还没有fix到master
