### ISSUE TITLE
umi block add 报错：sourcePath undefined

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4831]
![image](https://user-images.githubusercontent.com/51696361/61352241-78b67280-a89f-11e9-8036-03c0e1e4322c.png)

**Comment by Benpaodejiezai** [comment]
大佬，搭理搭理我吧

**Comment by chenshuai2144** [comment]
window 不支持这种黑科技的。
先使用代理 顶一下
