### ISSUE TITLE
Why add package-lock.json in .gitignore

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design-pro#4834]
I am confused about that.

**Comment by chenshuai2144** [comment]
lock is bad.
We do not recommend lock packages

**Comment by poulet42** [comment]
Hello, I did try to find pros and cons of using package-lock in a user facing app, but I can't really find anything useful and most articles / resources out there actually recommend the use of a lock file. Do you mind explaining just a tiny bit more why it's not the case here please?
