### ISSUE TITLE
umi-request拦截器问题

### ISSUE THREAD

**Issue by panghaoyuan** [ant-design/ant-design-pro#4835]
拦截器参数response不包括data嘛? 返回的数据怎么拿到
![image](https://user-images.githubusercontent.com/28645409/61360002-22056480-a8b0-11e9-8791-6decb977f444.png)

![image](https://user-images.githubusercontent.com/28645409/61359967-10bc5800-a8b0-11e9-8500-ad2fc0b4ee10.png)

**Comment by zewei1022** [comment]
调用response.json()方法
