### ISSUE TITLE
执行npx umi block add ListTableList安装区块直接安装的ts版，怎么选择js版？

### ISSUE THREAD

**Issue by lijun007** [ant-design/ant-design-pro#4836]
![image](https://user-images.githubusercontent.com/26159082/61363435-95aa7000-a8b6-11e9-8e6f-2b7e778cb5df.png)

![image](https://user-images.githubusercontent.com/26159082/61363492-ab1f9a00-a8b6-11e9-9672-ddf8df7fe9fd.png)

**Comment by afc163** [comment]
Try `umi block list`

**Comment by wgytcdx** [comment]
命令行后面加上 `--js`
