### ISSUE TITLE
官网对权限管理的介绍比较简略不是很明白

### ISSUE THREAD

**Issue by greateidea** [ant-design/ant-design-pro#4837]
能否再丰富一下权限那块文档的介绍，权限这个比较重要，但是写的有些简略确实没怎么看明白。

**Comment by 904492381** [comment]
+1

**Comment by weijx-xa** [comment]
+1

**Comment by FatDoge** [comment]
个人建议:
1.在issues页面多搜搜，基本上可以解决。
2.有没有兴趣搞个汇总问题相关的仓库，因为我也被坑了好久=-=

**Comment by hankaibo** [comment]
我写了个demo，动态菜单，按钮级别权限。

http://58.87.121.239:9000/user/login
admin/123456，所有权限；
user/123456，部分权限；
add/123456，添加加权限；
del/123456，删除权限。
支持动态左侧菜单。
可以自己在权限里面配置角色分配给用户。
https://github.com/hankaibo/myantdpro
源码地址。

**Comment by zhang0ZGC** [comment]
> 我写了个demo，动态菜单，按钮级别权限。
> 
> http://58.87.121.239:9000/user/login
> admin/123456，所有权限；
> user/123456，部分权限；
> add/123456，添加加权限；
> del/123456，删除权限。
> 支持动态左侧菜单。
> 可以自己在权限里面配置角色分配给用户。
> https://github.com/hankaibo/myantdpro
> 源码地址。

login failed

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
