### ISSUE TITLE
'sw.offline'事件不触发

### ISSUE THREAD

**Issue by XuZhaoTong** [ant-design/ant-design-pro#4838]
手机上开关网会触发window的online和offline事件，但是sw.offline事件就没见触发过，另外sw.update事件触发是正常的。

**Comment by chenshuai2144** [comment]
https://developers.google.com/web/ilt/pwa/offline-quickstart
看看这里不是复杂的问题

**Comment by XuZhaoTong** [comment]
> https://developers.google.com/web/ilt/pwa/offline-quickstart
> pwa 好复杂。不过与 pro 无关。去别的平台找答案可能更快

![QQ截图20190722141656](https://user-images.githubusercontent.com/32711995/61610404-a9295280-ac8b-11e9-956f-54cf2ce92db0.png)
看完那个我还是不明白，这行代码是怎么触发的。
