### ISSUE TITLE
Prevent browser caching

### ISSUE THREAD

**Issue by ja573** [ant-design/ant-design-pro#4839]
Apologies in advance if there's already a workaround.

**Background:**
I have written a website using ant design pro (https://metrics.operas-eu.org/) but I'm having trouble delivering new content to users as their browsers keep caching the underlying `umi.js` and `n.asyng.js` files.

In other websites I've done (with other libraries) whenever an update was done these automatically built files would get a random name, causing browsers to request the new file

**Problem:**
Users' browsers cache files generated by `umi build`, making updates hard to deliver

**Proposed solution:**
Force `umi build` to not reuse file names

**Comment by afc163** [comment]
https://umijs.org/config/#hash

**Comment by ja573** [comment]
Thanks for that. Just a quick question: where do I change that setting within ant's config files?

**Comment by ja573** [comment]
Thanks for that, it works! I wonder why the default is `false` - but that's a different story
