### ISSUE TITLE
这种安装正常吗

### ISSUE THREAD

**Issue by zlxls** [ant-design/ant-design-pro#484]
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
[ .................] - fetchMetadata: WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recom[ .................] / fetchMetadata: sill pacot[ .................] / fetchMetadata: sill pacote range manifest for fla[            ......] \ refresh-package-json:stylelint-config-standard: sill finalize D:\Program [            ......] - r[            ......] / refresh-package-json:is-callable: sill refresh-package-json D:\Program Files\phpStudy\WWW[            ......] \ refresh-package-json:is-builtin-module: sill [            [            ..[            ......] | refresh-pack[            ......] | refresh-package-json:is-number: si[            ......] | refresh-package-json:[            ......] | refre[            ......] | refresh-pack[            ......] - refresh-package-json:i[            ......] - refresh-package-json[            ......] - refresh-package-js[            ......] | refresh-package-[            ......[            ......] \ refresh-pac[            ......] | refresh-package-js[            ......] | refres[            ......] |[            ......] / refresh-package[            ......] / refresh[            ......] /[       [         [            ......] \ refre[            ......] \ r[      [            [            .[ [ [ [         [     [            ..[            ......] / refresh-pa[    [            ......] | refresh-[            ......] / refresh-package-json:fastparse: sill refresh-package-json D:\Progra[            ......] \ refresh-package-json:extsprintf: sill refresh-package-json D:\Progr[            ......] \ refresh-package-json:es6-set: sill refresh-package-json D:\Progra[            ......] | refresh-p[            ......] | refresh-package-json:d3: sill refresh[            ......] | refresh-package-json:d3: sill refresh-package-json D:\Program Files\php[            ......] | refresh-package-json:d3: sill ref[
> husky@0.14.3 install D:\Program Files\phpStudy\WWW\dishes\node_modules\husky
> node ./bin/install.js

husky
setting up Git hooks
done

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\Program Files\phpStudy\WWW\dishes\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> electron@1.7.10 postinstall D:\Program Files\phpStudy\WWW\dishes\node_modules\electron
> node install.js

**Comment by chenshuai2144** [comment]
正常。Element 可能下载缓慢
