### ISSUE TITLE
哪位可以私发一下完整区块的文件，我表示真心没办法下载了，每次运行都提示缺少文件

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design-pro#4841]
你们有带完整区块ant-design-pro-master项目的话，可以帮忙私发下么，我每次下载完最后跑起来都提示部分模块没找到，我想要一份完整的区块文件，有的话，可以留下你的github地址么，我去下载，灰常感谢

**Comment by chenshuai2144** [comment]
git clone https://github.com/ant-design/ant-design-pro.git --depth=1 -b v2

这种需求直接用 v2 分支就好了

**Comment by dongkeng001** [comment]
> `git clone https://github.com/ant-design/ant-design-pro.git --depth=1 -b v2`
> 
> 这种需求直接用 v2 分支就好了

大佬， 我想请教下footer内容怎么改的？我全文检索都没找到footer相关内容
