### ISSUE TITLE
color.less 的代码删除后，还是会被引用

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#4842]
color.less 的代码删除后，还是会被引用

model下面的setting,的代码被   if (!lessNodesAppended) { }里面的代码被我住址了。还是回去引用color.less。而且只有生产环境会有，怎么回事呢

**Comment by xgj1988** [comment]
生成的index.html会增加    <link rel="stylesheet/less" type="text/css" href="/color.less" />这个代码，不知道哪里写死的。

**Comment by xgj1988** [comment]
生成的dist/index.html时候会增加这个代码`   <link rel="stylesheet/less" type="text/css" href="/color.less" /> `.

**Comment by xgj1988** [comment]
而且也会生成 `   <script>
      window.less = {
        async: false,
        env: 'production'
      };
    </script>`

**Comment by chenshuai2144** [comment]
https://pro.ant.design/blog/change-theme-cn

可以看看这个

**Comment by xgj1988** [comment]
@chenshuai2144  大各。我看了，但是上面也没说哪里可以取消啊。。

**Comment by Toninie** [comment]
我在config/plugin.config.js里把引入ant-design-theme那段注释掉以后，打的包里index.html没有引入less.min.js了，这个color.less 也不会被引入，如果没用到主题切换功能可以用这个方法试试，仅供参考 @xgj1988

**Comment by xgj1988** [comment]
@Toninie  好的。我试试
