### ISSUE TITLE
v4 动态菜单 点击自定义逻辑 点击某一个菜单选项会造成该菜单收起，正常交互应该不收起。

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design-pro#4843]

**Comment by chenshuai2144** [comment]
现在的菜单展开是根据路径来的，展示不支持自定义模式。可以穿入 openKeys 试试

**Comment by LiYanGang** [comment]
> 现在的菜单展开是根据路径来的，展示不支持自定义模式。可以穿入 openKeys 试试

openKeys是取的path字段吗？我在ProLayout中传入openKeys不管用啊

**Comment by LiYanGang** [comment]
> 现在的菜单展开是根据路径来的，展示不支持自定义模式。可以穿入 openKeys 试试

现在动态菜单，key默认取的path作为key吗？我现在改回正常模式，点击菜单还是会收起来

**Comment by pkaq** [comment]
还是根据pid比较科学

**Comment by LiYanGang** [comment]
> 还是根据pid比较科学

pid?不大明白

**Comment by pkaq** [comment]
> > 还是根据pid比较科学
> 
> pid?不大明白

父节点ID而不是路径 因为后台管理员随时可能把菜单调整到其它路径下去 前台路由不改的话 呵呵呵呵

**Comment by mushroomlb** [comment]
> > > 还是根据pid比较科学
> > 
> > 
> > pid?不大明白
> 
> 父节点ID而不是路径 因为后台管理员随时可能把菜单调整到其它路径下去 前台路由不改的话 呵呵呵呵

有解决方法了吗，我也遇到了

**Comment by mushroomlb** [comment]
不传递key到menudata中在点击菜单时就报多个key重复问题，很是奇怪
![image](https://user-images.githubusercontent.com/1701771/62614257-a0987380-b93d-11e9-8912-8fdb0b982f3b.png)

**Comment by makehkx** [comment]
所以这个bug大家怎么解决的呢，

**Comment by chenshuai2144** [comment]
官方不支持的功能需要自己实现的
@makehkx
