### ISSUE TITLE
远程加载菜单时，如何设置菜单组件的loading?

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#4847]
远程加载菜单时，如何设置菜单组件的loading?

**Comment by chenshuai2144** [comment]
你可以用 spin 包裹一下，这个东西很业务，也很简单。

**Comment by afc163** [comment]
ProLayout 可能需要提供一个 menuLoading 属性，不然用户从外面很难改。

**Comment by effapp** [comment]
另外，远程加载菜单后，单击二级菜单项后，菜单会自动折叠起来。ProLayout的固定侧边栏功能没有，官网例子：
<Sider
      style={{
        overflow: 'auto',
        height: '100vh',
        position: 'fixed',
        left: 0,
      }}
    >

**Comment by chenshuai2144** [comment]
look https://ant-design.github.io/ant-design-pro-layout/
