### ISSUE TITLE
如何在errorHandler获取请求的method与post请求的参数

### ISSUE THREAD

**Issue by waylon-edmodo** [ant-design/ant-design-pro#4848]
求助。

request.interceptors.response.use(async (response, options) => 
拦截器如果return其他的会出错。只能return response。 可是调试发现response又不能被编辑或增加key value。

**Comment by chenshuai2144** [comment]
你为什么要增加 key？

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Response
