### ISSUE TITLE
Npm vulnerability, https://www.npmjs.com/advisories/1065

### ISSUE THREAD

**Issue by Sgouws** [ant-design/ant-design-pro#4850]
Lodash Npm vulnerability is back.

https://www.npmjs.com/advisories/1065

Versions of `lodash` before 4.17.12 are vulnerable to Prototype Pollution. The function `defaultsDeep` allows a malicious user to modify the prototype of `Object` via `{constructor: {prototype: {...}}}` causing the addition or modification of an existing property that will exist on all objects.

Remediation
Update to version 4.17.12 or later.

**Comment by chenshuai2144** [comment]
get a pr?

**Comment by chenshuai2144** [comment]
fixed
