### ISSUE TITLE
v4 在 /src/app.ts 中添加 redux-logger 中间件无效

### ISSUE THREAD

**Issue by Han-MeiM** [ant-design/ant-design-pro#4852]
![image](https://user-images.githubusercontent.com/27951114/61514897-b3511400-aa33-11e9-9ef8-523f69713a17.png)

如上图所示，添加 `redux-logger` 中间件后无效

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
