### ISSUE TITLE
ant design pro 4.0 登陆后，页面footer，页脚不知道怎么哪里改

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#4853]
![image](https://user-images.githubusercontent.com/32530210/61515090-4c802a80-aa34-11e9-9c56-44dce8360df6.png)

**Comment by xyzabc0004** [comment]
这个4.0搞得有点不适应了

**Comment by zewu-chen** [comment]
在ant-design-pro-master\src\layouts\BasicLayout.tsx文件中可以修改footerRender，你可以自己写一个footerRender覆盖，亦可以直接改

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/122edaf5d5baae8e102126c8a14181da60fae056/src/layouts/BasicLayout.tsx#L48
这里有示例

**Comment by xyzabc0004** [comment]
谢谢，谢谢！

**Comment by xshans** [comment]
配置参数就可以，目前要是支持html就更好了。
