### ISSUE TITLE
v4版本 拦截器里获取response.json()报错

### ISSUE THREAD

**Issue by yangdachu** [ant-design/ant-design-pro#4855]
![image](https://user-images.githubusercontent.com/23580181/61572972-3b3d2980-aad9-11e9-8ebd-3da07fae076c.png)
![image](https://user-images.githubusercontent.com/23580181/61572975-55770780-aad9-11e9-9279-32da078fe97d.png)

**Comment by chenshuai2144** [comment]
你需要保证你的 response 是 json 才行，你的应该是个 text

**Comment by yangdachu** [comment]
@chenshuai2144 是一个promise，不然也不会有catch和then了吧？我纳闷的就是不知道为什么进catch

**Comment by chenshuai2144** [comment]
执行一下 .text 就知道了。json 转化失败，很明显的提示
