### ISSUE TITLE
toolTips bug

### ISSUE THREAD

**Issue by kimmerchen** [ant-design/ant-design-pro#4857]
![image](https://user-images.githubusercontent.com/20125299/61576657-34310e00-ab0f-11e9-85dd-9a602ca44945.png)

**Comment by kimmerchen** [comment]
![image](https://user-images.githubusercontent.com/20125299/61576623-ca186900-ab0e-11e9-9a26-7ccfa95a955e.png)

**Comment by chenshuai2144** [comment]
这个需要 g2 去处理一下了。暂时无解
