### ISSUE TITLE
npx umi block add ProfileBasic --path=/profile/basic 失败

### ISSUE THREAD

**Issue by cylovefpc** [ant-design/ant-design-pro#4859]
PS E:\vue\ant-design-pro-4.0.0> npx umi block add ProfileBasic --path=/profile/basic
√ 😁  Parse url and args
× 🔍  clone git repo from https://github.com/ant-design/pro-blocks
×  error     Error: Error: spawn git ENOENT

克隆失败 求解，第一次使用git

**Comment by afc163** [comment]
你需要安装 git 先。

**Comment by chenshuai2144** [comment]
最好在升级一下 umi。新版本的 umi 会根据网络环境来使用代理服务

**Comment by cylovefpc** [comment]
> 最好在升级一下umi。新版本的umi会根据网络环境来使用代理服务

我umi 才新装的，现在是2.8.12 。git也装了，版本是2.22.0。 现在问题是一直卡在 git clone 这转圈圈

**Comment by chenshuai2144** [comment]
`umi-build-dev@1.10.12

`安装这个版本
