### ISSUE TITLE
这几天v2.1.1 npm start老是报错

### ISSUE THREAD

**Issue by sunclelee** [ant-design/ant-design-pro#4864]
Error: Cannot find module 'eslint-config-prettier/@typescript-eslint'
2.1.1版本重新npm install再npm start，就会报这个模块找不到。
这个情况从上周6开始持续到今天，即使重新下载2.1.1的源码包重新安装也是一样。
2.2.0试过没有这个问题，但是不想升级啊好麻烦，有解决方法吗大佬们

**Comment by chenshuai2144** [comment]
一堆依赖升级了，你可以模仿一下 pro v4 的 eslint 配置，。这个是 eslint 的问题。

> 简单的办法  "eslint-config-prettier": "^3.0.1",

**Comment by sunclelee** [comment]
大佬，2.1.1的package.json本来就是"eslint-config-prettier": "^3.0.1"啊

**Comment by sunclelee** [comment]
找到原因了，跟eslint没有关系，是umi升级到2.8.13造成的，降到以前到2.8.8就对了。谢谢大佬。

> 一堆依赖升级了，你可以模仿一下 pro v4 的 eslint 配置，。这个是 eslint 的问题。
> 
> > 简单的办法  "eslint-config-prettier": "^3.0.1",
