### ISSUE TITLE
V4 版本怎么添加详情页面，官方demo没有例子，能否考虑新增一个？ （问题已经解决，closed）

### ISSUE THREAD

**Issue by yangdachu** [ant-design/ant-design-pro#4866]

**Comment by yangdachu** [comment]
通过点击列表的某一条数据，跳转到详情页面

1、点击查看详情拿到对应id
![image](https://user-images.githubusercontent.com/23580181/61612581-8f8b0980-ac91-11e9-9fe2-bef83493d89b.png)

2、表格列表目录下的详情页面目录
![image](https://user-images.githubusercontent.com/23580181/61612617-a6316080-ac91-11e9-9564-7d7c09a18614.png)
![image](https://user-images.githubusercontent.com/23580181/61612643-b6494000-ac91-11e9-8fa4-a4f6ffa156cf.png)

3、路由配置
![image](https://user-images.githubusercontent.com/23580181/61612745-f6a8be00-ac91-11e9-85be-177aaa78e672.png)

**Comment by yangdachu** [comment]
请问下配置是否有问题，官方demo能不能新增一个跳转到页面详情的例子

**Comment by chenshuai2144** [comment]
这个功能其实是有的，后来关掉了。
https://v2-preview-ant-design-pro.netlify.com/list/table-list，可以 clone 一下 v2 分支看一下

**Comment by yangdachu** [comment]
v2版本中的路由
![image](https://user-images.githubusercontent.com/23580181/61613877-0249b400-ac95-11e9-9fb0-39a2255403b7.png)

详情页
![image](https://user-images.githubusercontent.com/23580181/61613903-1097d000-ac95-11e9-80f6-8954548c099a.png)

在config里怎么引入这个详情呢
![image](https://user-images.githubusercontent.com/23580181/61613974-345b1600-ac95-11e9-93fe-1ecbe8a8b165.png)

**Comment by yangdachu** [comment]
![image](https://user-images.githubusercontent.com/23580181/61614056-666c7800-ac95-11e9-9140-6a658368749c.png)
引入这个页面是不是还需要哪里配置一下

**Comment by chenshuai2144** [comment]
tsconfig 是必须的，你可以在 prov4 中拷贝一下

**Comment by yangdachu** [comment]
@chenshuai2144 我的就是V4 ts项目，为啥还要拷贝tsconfig呢？

**Comment by yangdachu** [comment]
![image](https://user-images.githubusercontent.com/23580181/61616139-4c816400-ac9a-11e9-93b0-34f52987153d.png)
![image](https://user-images.githubusercontent.com/23580181/61616179-63c05180-ac9a-11e9-9859-23ac2662fbe9.png)

这个是我自己手动创建的目录和文件，并且我在config.ts里配置了路由信息了

**Comment by yangdachu** [comment]
http://localhost:8000/ground-audit/ground-details/418

![image](https://user-images.githubusercontent.com/23580181/61618798-35de0b80-aca0-11e9-9310-9a7e2397816e.png)

**Comment by yangdachu** [comment]
问题解决了，是目录里的model.ts文件影响了，如果用不到的话直接可以删除掉，但是不能为空，希望能帮助到后面遇到这个问题的人。

**Comment by yangdachu** [comment]
@chenshuai2144 感谢老铁的回复，麻烦了
