### ISSUE TITLE
根据umi官网脚手架创建项目，结果报错？错误如图所示。

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design-pro#4867]
![image](https://user-images.githubusercontent.com/23158766/61612091-222aa900-ac90-11e9-9076-86b17aeed03e.png)

**Comment by chenshuai2144** [comment]
重新安装一下 umi 吧。umi 安装失败了

**Comment by wo-de-ping-er** [comment]
> 重新安装一下 umi 吧。umi 安装失败了

安装了好几遍   一直都在报这个错误？
