### ISSUE TITLE
重新安装umi并不能解决问题啊？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design-pro#4868]
![image](https://user-images.githubusercontent.com/23158766/61613263-73886780-ac93-11e9-824f-99cdc332c3b2.png)

**Comment by chenshuai2144** [comment]
这个是dll报错了。你可以关掉dll。或者按照他的提示进行配置
这里是文档
https://umijs.org/zh/plugin/umi-plugin-react.html#dll

**Comment by tt38491367** [comment]
解决了吗？
