### ISSUE TITLE
总是提示跨域请求有问题

### ISSUE THREAD

**Issue by zlxls** [ant-design/ant-design-pro#487]
Fetch API cannot load http://localhost/dishesAdmin/web/index.php?c=user&a=login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by afc163** [comment]
请使用代理功能和后端进行联调：https://pro.ant.design/docs/mock-api-cn

**Comment by zlxls** [comment]
但是，前后端分离本来就要跨域，应该是个举出模块，上面案列也没有，只有几张截图，写不出来嘛

**Comment by afc163** [comment]
1. 前后端分离不一定要跨域。
2. 如果确实跨域了，服务端要设置相关的 CORS 配置。

类似的文档可见：https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development

**Comment by zlxls** [comment]
我一个80端口，一个8000端口，可以实现不跨域吗
