### ISSUE TITLE
npm install 出现puppeteer安装失败问题

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#4870]
如图：![Snipaste_2019-07-22_15-51-03](https://user-images.githubusercontent.com/23411433/61615481-b1d45580-ac98-11e9-89ab-f4dbb465f6f2.png)

![Snipaste_2019-07-22_16-01-29](https://user-images.githubusercontent.com/23411433/61615848-99186f80-ac99-11e9-9cee-a23855f204ce.png)

以前没有出现过这个问题

**Comment by chenshuai2144** [comment]
使用 cnpm 安装或者设置代理。
https://github.com/cnpm/cnpmjs.org/issues/1246
