### ISSUE TITLE
v2版本独立使用的时候报TS2604错误

### ISSUE THREAD

**Issue by hvsy** [ant-design/ant-design-pro#4871]
测试代码
![image](https://user-images.githubusercontent.com/5687399/61622393-45ad1e00-aca7-11e9-86d6-06cbab013a14.png)

Version 
![image](https://user-images.githubusercontent.com/5687399/61622167-d9cab580-aca6-11e9-98b9-8f62101c165d.png)

tsconfig.json

![image](https://user-images.githubusercontent.com/5687399/61622226-f6ff8400-aca6-11e9-84fe-b842d8db30dd.png)

执行tsc的报错信息
![image](https://user-images.githubusercontent.com/5687399/61622285-10083500-aca7-11e9-9bd5-6b02e66d03c1.png)

**Comment by chenshuai2144** [comment]
看一下 Field 是不是不存在？

**Comment by hvsy** [comment]
> 看一下 Field 是不是不存在？

存在的，只是Field的ds文件里面的内容是这样的
https://github.com/ant-design/ant-design-pro/blob/v2/src/components/Charts/Field/index.d.ts
```typescript
import React from 'react';
export interface IFieldProps {
  label: React.ReactNode;
  value: React.ReactNode;
  style?: React.CSSProperties;
}

export default class Field extends React.Component<IFieldProps, any> {}
```

Field这个class的body缺少constructor 和render方法的声明。

**Comment by chenshuai2144** [comment]
```
export default class Field extends React.Component<IFieldProps, any> {
    render(): JSX.Element;
}
```
改为这样好了

**Comment by hvsy** [comment]
> ```
> export default class Field extends React.Component<IFieldProps, any> {
>     render(): JSX.Element;
> }
> ```
> 
> 改为这样好了

这个文件怎么改??发 pull???这个是自动生成的吧?

**Comment by hvsy** [comment]
@chenshuai2144
