### ISSUE TITLE
什么因素会造成 Popover气泡卡片 定位不准确呢？

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#4874]
![image](https://user-images.githubusercontent.com/33716687/61626048-c3285c80-acae-11e9-8b29-6deb08035c84.png)
不知道什么因素造成的，第二次再显示就好了，就第一次一直定位不准确，感觉很别扭

**Comment by chenshuai2144** [comment]
你试着修改一下 让的父元素绝对定位一把

**Comment by XSmarter** [comment]
arrowPointAtCenter 加了个这个属性 就可以了，谢谢

**Comment by XSmarter** [comment]
不对，还是不行，用了下 getPopupContainer也不可以 
​`function popoperContainerSetting(node: HTMLElement) :HTMLElement {
    return node.parentNode ? node.parentNode as HTMLElement : document.body;
}`

**Comment by XSmarter** [comment]
content 组件设置上宽高好像就好了

**Comment by chenshuai2144** [comment]
来个最小再现，说不定 antd 官方可以帮你修
