### ISSUE TITLE
This relative module was not found:../Flow/List/FlowList in ./src/pages/.umi-production/router.js

### ISSUE THREAD

**Issue by zco4321** [ant-design/ant-design-pro#4875]
路由配置文件如下：
![image](https://user-images.githubusercontent.com/37138011/61626456-eb648b00-acaf-11e9-98ce-cfa31bf04574.png)
相关目结构如下：
![image](https://user-images.githubusercontent.com/37138011/61626489-ff0ff180-acaf-11e9-8ca6-1d8f6090f634.png)
请问现在再Jenkins中打包 一种报错是什么原因导致的，需要修改什么

**Comment by zco4321** [comment]
大小写问题....

**Comment by Lawrence51** [comment]
请问这个是编辑视图中的流程图吗？在哪里有文档或者demo可以看，这个组件去哪里找？麻烦了
