### ISSUE TITLE
安装了区块很多次，安装不了

### ISSUE THREAD

**Issue by liangchuan028** [ant-design/ant-design-pro#4878]
![e68](https://user-images.githubusercontent.com/24433416/61674305-e4785f80-ad25-11e9-94e8-d3732191dd15.png)

**Comment by chenshuai2144** [comment]
npm 安装失败了。你人肉执行一下这个命令

**Comment by liangchuan028** [comment]
@chenshuai2144 我重新又安装了一次，你看下，反正各种问题
![1b5](https://user-images.githubusercontent.com/24433416/61677192-31156800-ad31-11e9-9103-656133381ee7.png)

**Comment by chenshuai2144** [comment]
git clone 失败. 试着全局删除一下 umi，然后重装

**Comment by liangchuan028** [comment]
@chenshuai2144 为啥全局删除不了，umi -v 还有
![image](https://user-images.githubusercontent.com/24433416/61680596-c79b5680-ad3c-11e9-8216-f4434a20d487.png)

**Comment by chenshuai2144** [comment]
` /usr/local/lib/node_modules`
去这个里面看看吧

**Comment by liangchuan028** [comment]
@chenshuai2144 谢谢，果然，重装了umi就可以了
