### ISSUE TITLE
ant design pro定义删除按钮，却不是红底！

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/ant-design-pro#4879]
ant design pro 2定义删除按钮，却不是红底！请问什么原因？
代码如下：
```
<Button icon="minus" type="danger" onClick={this.handleMenuClick}>
批量删除
</Button>
```
截图如下：
![webwxgetmsgimg](https://user-images.githubusercontent.com/3403476/61674720-a0865a00-ad27-11e9-8317-2cde38be7324.jpg)

**Comment by chenshuai2144** [comment]
更新一下 ant 的版本
