### ISSUE TITLE
执行npm run analyze 出错

### ISSUE THREAD

**Issue by jlq023** [ant-design/ant-design-pro#4881]
由于目前的项目，打包后的js有5.9m左右，所以我就按照官方提示，执行npm run analyze分析js占用情况， 但我在本地执行npm run analyze后，出现如下错误：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\workPath\\javaTool\\nodejs\\node.exe',
1 verbose cli   'C:\\workPath\\javaTool\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'analyze' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'preanalyze', 'analyze', 'postanalyze' ]
5 info lifecycle ant-design-pro-test@1.1.0~preanalyze: ant-design-pro-test@1.1.0
6 info lifecycle ant-design-pro-test@1.1.0~analyze: ant-design-pro-test@1.1.0
7 verbose lifecycle ant-design-pro-test@1.1.0~analyze: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro-test@1.1.0~analyze: PATH: C:\workPath\javaTool\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\workPath\gitDown\react_mall_weixin_manage\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\workPath\javaTool\Git;C:\workPath\javaTool\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\workPath\javaTool\nodejs;;E:\workPath\javaTool\java1.8\jdk1.8-64\bin;E:\workPath\javaTool\java1.8\jdk1.8-64\jre\bin;E:\workPath\javaTool\android-sdk-windows\platform-tools;E:\workPath\javaTool\apache-maven-3.5.2\bin;
9 verbose lifecycle ant-design-pro-test@1.1.0~analyze: CWD: C:\workPath\gitDown\react_mall_weixin_manage
10 silly lifecycle ant-design-pro-test@1.1.0~analyze: Args: [ '/d /s /c', 'cross-env ANALYZE=true roadhog build' ]
11 silly lifecycle ant-design-pro-test@1.1.0~analyze: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro-test@1.1.0~analyze: Failed to exec analyze script
13 verbose stack Error: ant-design-pro-test@1.1.0 analyze: `cross-env ANALYZE=true roadhog build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\workPath\javaTool\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\workPath\javaTool\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ant-design-pro-test@1.1.0
15 verbose cwd C:\workPath\gitDown\react_mall_weixin_manage
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\workPath\\javaTool\\nodejs\\node.exe" "C:\\workPath\\javaTool\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "analyze"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro-test@1.1.0 analyze: `cross-env ANALYZE=true roadhog build`
22 error Exit status 1
23 error Failed at the ant-design-pro-test@1.1.0 analyze script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
请问是什么原因呢？

**Comment by chenshuai2144** [comment]
roadhog 这个 ANALYZE 好像挂了，你锁包试一试呢

**Comment by jlq023** [comment]
> roadhog 这个 ANALYZE 好像挂了，你锁包试一试呢

请问一下如何锁包呢，有没有相关的教程，百度也没查询出这方面的资料，我确实不会

**Comment by chenshuai2144** [comment]
https://blog.csdn.net/njweiyukun/article/details/70309066

相关文档还是很多的，是 npm 的一个规范。

**Comment by jlq023** [comment]
> https://blog.csdn.net/njweiyukun/article/details/70309066
> https://docs.npmjs.com/files/package.json
> 
> 相关文档还是很多的，是 npm 的一个规范。

谢谢
