### ISSUE TITLE
yarn create umi项目处处哦

### ISSUE THREAD

**Issue by Mranxiaoranran** [ant-design/ant-design-pro#4882]
> Generate failed Error: Cannot find module 'node-fetch'

**Comment by afc163** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/507615/61682373-008af980-ad44-11e9-8a5a-8458d96cffa4.png">

展现的 create-umi 版本是多少？

**Comment by phatlt** [comment]
I also got this problem
![image](https://user-images.githubusercontent.com/37525408/61765588-e6b2ea80-ae07-11e9-955c-08d517f835af.png)

**Comment by perany** [comment]
创建项目报错：
$ npm create umi 
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
> git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> [JS] Prepare js environment...
> [JS] Compiling ts files...
> [JS] Prettier code...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: npx prettier --write **/*.js
[error] Invalid configuration file: Cannot find module '@umijs/fabric'


    at makeError (/Users/pengyl/.config/yarn/global/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/pengyl/.config/yarn/global/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/pengyl/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by shaohuatsou** [comment]
> 创建项目报错：
> 
> ```
> $ npm create umi 
> ? Select the boilerplate type ant-design-pro
> ? Which language do you want to use? JavaScript
> > git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> > [JS] Prepare js environment...
> > [JS] Compiling ts files...
> > [JS] Prettier code...
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Command failed: npx prettier --write **/*.js
> [error] Invalid configuration file: Cannot find module '@umijs/fabric'
> 
> 
>     at makeError (/Users/pengyl/.config/yarn/global/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/Users/pengyl/.config/yarn/global/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> Emitted 'error' event at:
>     at Immediate.setImmediate (/Users/pengyl/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> ```

我也遇到了，你解决了吗？

**Comment by shaohuatsou** [comment]
@perany 

> 创建项目报错：
> 
> ```
> $ npm create umi 
> ? Select the boilerplate type ant-design-pro
> ? Which language do you want to use? JavaScript
> > git clone https://github.com/ant-design/ant-design-pro --depth=1 ./
> > [JS] Prepare js environment...
> > [JS] Compiling ts files...
> > [JS] Prettier code...
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Command failed: npx prettier --write **/*.js
> [error] Invalid configuration file: Cannot find module '@umijs/fabric'
> 
> 
>     at makeError (/Users/pengyl/.config/yarn/global/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/Users/pengyl/.config/yarn/global/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> Emitted 'error' event at:
>     at Immediate.setImmediate (/Users/pengyl/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> ```

我也遇到了，你解决了吗？ @perany

**Comment by chenshuai2144** [comment]
安装最新的 umi 即可解决这个问题
