### ISSUE TITLE
V4 子路权限不继承

### ISSUE THREAD

**Issue by yjz1004** [ant-design/ant-design-pro#4883]
```javascript
  {
      path: '/',
      component: '../layouts/BasicLayout',
      Routes: ['src/pages/Authorized'],
      authority: ['admin', 'user'],
      routes: [
        {
          path: '/',
          redirect: '/form',
        },
        {
          path: '/form',
          name: 'form',
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/form',
              redirect: '/form/basic-form',
            },
            {
              path: '/form/basic-form',
              name: 'basic-form2',
              component: './form/basic-form',
            },
          ]
        },
      ],
    },
```

路由如上配置
1.直接访问/  能进入页面，在/下配置了authority不会跳到登录页？
2.直接访问/form  跳转到登录页面，
3.直接访问/form/basic-form  能进入页面，在/和/form下配置了authority不会跳到登录页？

**Comment by lukecheng** [comment]
同样的问题

**Comment by Immortalt** [comment]
同样的问题

**Comment by Malarkey-Jhu** [comment]
我的做法是在 pages 底下的 Authorized.jsx 里 getRouteAuthority 函数加一些判断。
![image](https://user-images.githubusercontent.com/36290564/63948918-2080ac00-caac-11e9-8392-720c5f0100d7.png)
且跟路由的配置如下
![image](https://user-images.githubusercontent.com/36290564/63949221-a3096b80-caac-11e9-9d96-e96b348430be.png)

打印  Authorized.jsx 里的routes看看应该会发现，可多尝试看看
