### ISSUE TITLE
target为地址里的pyapi目录 怎么不行  该怎么写

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#4884]
![image](https://user-images.githubusercontent.com/47104575/61688626-1aced280-ad58-11e9-8883-ea75aa1df222.png)这样不行
![image](https://user-images.githubusercontent.com/47104575/61688715-4baf0780-ad58-11e9-9dbc-d4d1f9fbdab9.png)这样也不行

**Comment by Redspitee** [comment]
不能和mock里前缀一致
![image](https://user-images.githubusercontent.com/22409203/61758973-71401d80-adf9-11e9-93ac-e066c0c6ef20.png)

**Comment by 904492381** [comment]
@Redspitee 
![image](https://user-images.githubusercontent.com/47104575/61759945-810d3100-adfc-11e9-9351-c1d549fead00.png)这是什么问题
