### ISSUE TITLE
配置子路由时 为什么找不到这个组件  welcome可以 newpage不行 他们在同一级

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#4885]
![image](https://user-images.githubusercontent.com/47104575/61688847-a5173680-ad58-11e9-9d31-99f46ea8c3a1.png)
![image](https://user-images.githubusercontent.com/47104575/61688904-c5df8c00-ad58-11e9-82d4-fafce783aed0.png)
![image](https://user-images.githubusercontent.com/47104575/61688961-e90a3b80-ad58-11e9-9722-fb6fdc099b1e.png)

**Comment by VEMTK** [comment]
这怎么解决的了？
