### ISSUE TITLE
pages 目录下 只有 welcome

### ISSUE THREAD

**Issue by crocodilema** [ant-design/ant-design-pro#4888]
你好  
       我理解 这个 工程的应该显示所有 https://preview.pro.ant.design/的页面，但是 下载安装后只有一个 welcome 界面 ，请问 那些模板代码在哪里呢
      谢谢

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/available-script-cn#npm-run-fetchblocks

**Comment by crocodilema** [comment]
提示找不到pro 这个命令
pro:未找到命令
