### ISSUE TITLE
为何把它跑起来如此之难.　

### ISSUE THREAD

**Issue by huqinlou0123** [ant-design/ant-design-pro#4891]
难道开发人员自己都不自己安装测试使用的.

**Comment by chenshuai2144** [comment]
难在哪里？

**Comment by huqinlou0123** [comment]
弄了两天了，解决一些问题安装后，提交报eslint一堆错，里面有个提示我执行npm i -S express，
执行了又卡住，卡几小时不动.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated core-js@2.6.0: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @types/webpack-chain@5.2.0: This is a stub types definition. webpack-chain provides its own type definitions, so you do not need this installed.
[            ......] | extract:expect: sill extract expect@^24.8.0 extracted to /auto/FRONT/node_modules/.staging/expect-1373b8fa (302275ms)
/auto/FRONT/node_modules/.staging/expect-1373b8fa (302275ms)

**Comment by huqinlou0123** [comment]
这些问题难道你们都没碰到吗．　还有这个PUPPETEER这个东西是必要的吗，安装时也是卡住下载不动．

**Comment by funoy** [comment]
> 这些问题难道你们都没碰到吗．　还有这个PUPPETEER这个东西是必要的吗，安装时也是卡住下载不动．

我刚刚用npm install 也是同样问题，然后尝试用yarn成功了

**Comment by afc163** [comment]
Try `cnpm`: https://cnpmjs.org/

**Comment by icyes** [comment]
确实！用了淘宝的镜像，跑起来还是太难了
