### ISSUE TITLE
为什么说这个样式没找到？

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#4892]
![image](https://user-images.githubusercontent.com/47104575/61763794-41991180-ae09-11e9-9d2a-0993db234855.png)
![image](https://user-images.githubusercontent.com/47104575/61763799-48c01f80-ae09-11e9-981e-f40ba8a8f154.png)

**Comment by chenshuai2144** [comment]
这是因为 js 中不支持中划线作为变量名
你需要使用 styles["login-form"]
