### ISSUE TITLE
为什么我配置了proxy 在控制台查看还是请求本地

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#4893]
![image](https://user-images.githubusercontent.com/47104575/61767583-5381b100-ae17-11e9-965e-fe89db705c72.png)

![image](https://user-images.githubusercontent.com/47104575/61767602-64cabd80-ae17-11e9-9c04-f3c7b5cc89e8.png)

**Comment by 904492381** [comment]
我的npm start 应该也不走mock才对
![image](https://user-images.githubusercontent.com/47104575/61767942-6779e280-ae18-11e9-97ea-f9d7b741488b.png)

**Comment by zhenzi1995** [comment]
我的接口请求都看不到，也不报错，但是断开服务器，会有提示
![image](https://user-images.githubusercontent.com/17397976/61768743-ec65fb80-ae1a-11e9-90ca-c3de04b3d1a2.png)
![image](https://user-images.githubusercontent.com/17397976/61768752-f2f47300-ae1a-11e9-8d22-0cbaff9fddaf.png)
![image](https://user-images.githubusercontent.com/17397976/61768797-0bfd2400-ae1b-11e9-9682-b1d06b55b04c.png)

**Comment by wsc1988126** [comment]
我和你情况一样 配置好了还是本地，卡了几个小时了，我放弃了，开始自己手动搭建
