### ISSUE TITLE
我配置了proxy 在控制台看不到请求，断开服务会有提示

### ISSUE THREAD

**Issue by zhenzi1995** [ant-design/ant-design-pro#4894]
![image](https://user-images.githubusercontent.com/17397976/61768992-934a9780-ae1b-11e9-9391-4b8b11bbcf3c.png)
![image](https://user-images.githubusercontent.com/17397976/61769003-9b0a3c00-ae1b-11e9-9000-e61d07d2975f.png)
![image](https://user-images.githubusercontent.com/17397976/61769021-a3627700-ae1b-11e9-8331-976ce14eafdc.png)

**Comment by xiaohuoni** [comment]
proxy是请求服务代理，不是请求转化。在浏览器看不到变化的。服务有真实代理就行
