### ISSUE TITLE
 Can not find module  'eslint-config-prettier?@typescript-eslint'

### ISSUE THREAD

**Issue by crocodilema** [ant-design/ant-design-pro#4897]
按照教程 
npm create umi
 Select the boilerplate type (Use arrow keys)
❯ ant-design-pro  - Create project with an layout-only ant-design-pro boilerplate, use together with umi block.
  app             - Create project with a simple boilerplate, support typescript.
  block           - Create a umi block.
  library         - Create a library with umi.
  plugin          - Create a umi plugin.

$ npm install
$ npm start     
会出现  Error : Can not find module  'eslint-config-prettier?@typescript-eslint'

Node -v  10.15.3

**Comment by chenshuai2144** [comment]
已经修复使用最新的 umi 即可
