### ISSUE TITLE
这个 errorHandler 应该不会触发吧

### ISSUE THREAD

**Issue by bigjujube** [ant-design/ant-design-pro#4898]
https://github.com/ant-design/ant-design-pro/blob/122edaf5d5baae8e102126c8a14181da60fae056/src/utils/request.ts#L47

查了一下 MDN，https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful，
fetch 只有在网络出错的情况下才会 reject，但是这个写法我在自己的项目里测试是没有触发，不知道你们有没有测试过出错的这种情况

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4794
看看和这个有关吗

**Comment by chenshuai2144** [comment]
>  fetch 只有在网络出错的情况下才会 reject

umi-request 封装了一下，只要大于 400 都会触发
