### ISSUE TITLE
使用php做后台，用这一套模板，这么实现不跨域

### ISSUE THREAD

**Issue by zlxls** [ant-design/ant-design-pro#490]
求大神解答

**Comment by chenshuai2144** [comment]
https://webpack.github.io/docs/webpack-dev-server.html#proxy

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/blob/master/README.md

结合起来看

**Comment by zlxls** [comment]
怎么会这么复杂，表示不会呀

**Comment by dengfuping** [comment]
The most simple method is to set CORS header in your backend and there are many composer packages about CORS on [https://packagist.org](https://packagist.org). If you are using Laravel, [barryvdh/laravel-cors](https://github.com/barryvdh/laravel-cors) will be helpful.

**Comment by nikogu** [comment]
这个问题问的人比较多，统一总结回答下：
1. 前端起服务，用 mock 映射后端接口：https://github.com/sorrycc/roadhog/blob/master/README.md#mock
2. 前端起服务，服务器页面引用静态文件，如：php 里面的 script src 设置为前端服务地址
3. 给后端服务请求添加 cors header:  https://www.w3.org/TR/cors/#access-control-allow-origin-response-header
4. 下个 chrome 插件，crossdomain

2,3,4 都能够有效顺便搞定权限问题

**Comment by zlxls** [comment]
需要安装 roadhog吗？

**Comment by chenshuai2144** [comment]
Ant.pro自带的
