### ISSUE TITLE
deploy under subdirectory

### ISSUE THREAD

**Issue by zieru** [ant-design/ant-design-pro#4900]
Hello 

I would like to deploy ant design pro, under subfolder,
eg: http://localhost`/ant`

but ant still using `/` instead `/ant` for css and js resources

![photo_2019-07-24_14-41-47](https://user-images.githubusercontent.com/1273033/61774508-3225c280-ae21-11e9-9b86-638507e2ae32.jpg)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E9%83%A8%E7%BD%B2%E5%88%B0%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95

**Comment by iqmal852** [comment]
im having the same issue

@chenshuai2144 the link doesnt seems to work
