### ISSUE TITLE
git commit 出现错误

### ISSUE THREAD

**Issue by ZHENGGEGE** [ant-design/ant-design-pro#4902]
![image](https://user-images.githubusercontent.com/20240270/61775830-47ecb500-ae2c-11e9-8bc4-6276bed5ef3c.png)

**Comment by xiaohuoni** [comment]
v2的项目嘛？

**Comment by xiaohuoni** [comment]
是不是没有rettierrc这个文件

**Comment by ZHENGGEGE** [comment]
对， v2的项目，找到了，确实是新建项目时候直接拷贝原来项目漏了两个隐藏配置文件
