### ISSUE TITLE
npm run fetch:blocks

### ISSUE THREAD

**Issue by crocodilema** [ant-design/ant-design-pro#4903]
运行npm run fetch:blocks   提示
pro:未找到命令

**Comment by xiaohuoni** [comment]
重新装一下模块

**Comment by crocodilema** [comment]
重装哪个模块 ，怎么重装~~谢谢

**Comment by xiaohuoni** [comment]
`yarn` 或者 `npm i`

**Comment by chenshuai2144** [comment]
重装 @ant-design/pro-cli

**Comment by crocodilema** [comment]
Run : pro fetch-blocks 
Set your user:pro set user [name]
什么意思
