### ISSUE TITLE
Table树形表格省份地区大数据加载时候，经常出现卡死现象

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#4905]
好像没找到 懒加载？

**Comment by Redspitee** [comment]
[文档](https://ant.design/components/tree-cn/#components-tree-demo-directory)

**Comment by Redspitee** [comment]
有啊， tree控件的 loadData [文档地址 ](https://ant.design/components/tree-cn/#components-tree-demo-directory)

**Comment by WuJiY** [comment]
> 有啊， tree控件的 loadData [文档地址 ](https://ant.design/components/tree-cn/#components-tree-demo-directory)

谢谢 ，我是说 table组件

**Comment by chenshuai2144** [comment]
table 建议分页
