### ISSUE TITLE
一个 block 可以引用其他 block 的页面吗？

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4906]
想将一个block做成通用组件，其他block 去引用，不知道怎么做到

**Comment by chenshuai2144** [comment]
官方的 blocks 是不可以的。现在支持组件级别的 block，具体可以看
https://umijs.org/zh/guide/block.html#%E4%BD%BF%E7%94%A8%E5%8C%BA%E5%9D%97 
或者在 umi 中提 issue
