### ISSUE TITLE
表单通过dispatch提交数据，需要根据响应决定下一步操作，但无法获取请求的响应

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design-pro#4907]
![image](https://user-images.githubusercontent.com/4182865/61840033-75843d80-aec2-11e9-9956-51883ee2c29f.png)
V4之前的版本可以通过：
```react
dispatch().then(res=>{
// todo somethings...
})
```
但v4版本没有.then()

**Comment by afc163** [comment]
你应该到 effects 里处理异步逻辑。

**Comment by wzlee** [comment]
像表单是通过modal显示，我需要知道提交成功或失败来决定是否关闭modal，这个在effects里无法实现控制页面的modal吧？

**Comment by wzlee** [comment]
@afc163 你这样简单回复就关闭issue好么？

**Comment by WuJiY** [comment]
> 像表单是通过modal显示，我需要知道提交成功或失败来决定是否关闭modal，这个在effects里无法实现控制页面的modal吧？

或者你通过callback 回掉

**Comment by xiaohuoni** [comment]
@wzlee 是不是类型定义错误？dispatch.then应该还是可以用的

**Comment by Liu-Ya** [comment]
@xiaohuoni 能用，但是ts项目类型定义报错
![image](https://user-images.githubusercontent.com/23520283/69545035-eef47f80-0fcb-11ea-8337-8fff37d9fa2d.png)
```tsx
interface InitiateProps {
  current: StateType['current'];
  dispatch?: Dispatch<AnyAction>;
}
```
这个该如何声明？
