### ISSUE TITLE
文档错别字 - 图表

### ISSUE THREAD

**Issue by perany** [ant-design/ant-design-pro#4908]
如下图
图表-使用Ant Design Pro的图表下方小字部分，“...，如果你好要使用可以看图表组件”应该改为“...，如果你还要使用可以看图表组件”。
很荣幸能和antd一起尽善尽美！
![WeChat8a7cebf477b8fc27390fd5b174e71a26](https://user-images.githubusercontent.com/19280845/61843355-debd7e00-aecd-11e9-9849-c584a0bc790c.png)

**Comment by chenshuai2144** [comment]
来个pr吧。
https://github.com/ant-design/ant-design-pro-site

**Comment by perany** [comment]
> 来个pr吧。
> https://github.com/ant-design/ant-design-pro-site
👌
