### ISSUE TITLE
在 Form.create 中添加 onFieldsChange 后，验证信息不显示

### ISSUE THREAD

**Issue by SwordsmanYao** [ant-design/ant-design-pro#491]
#389 我自己简单搭的架子，只用 antd 没问题，在 pro 中会出现这个问题
有问题的代码地址：https://github.com/SwordsmanYao/antd-pro-simple
![image](https://user-images.githubusercontent.com/20725188/34324266-5654809c-e8a7-11e7-8444-2c49d8f4d167.png)

![image](https://user-images.githubusercontent.com/20725188/34324393-546f1fee-e8ac-11e7-9d6b-985f3b55a8cc.png)
![image](https://user-images.githubusercontent.com/20725188/34324396-6b2c7006-e8ac-11e7-9f87-4ada01134a92.png)

**Comment by ddcat1115** [comment]
mapPropsToFields 中除了返回 value，其他属性也需要一起返回，里面就有 error 信息，仔细比较下和官网 [demo](https://ant.design/components/form-cn/#components-form-demo-global-state) 的区别

**Comment by SwordsmanYao** [comment]
哦哦   终于解决了   多谢

**Comment by mixiaotian414** [comment]
补充1L，onFieldsChange 在改变redux里的值时也要带着除value以外的元素 官网中demo显示：
{
  "username": {
    "value": "123122",
    "name": "username",
    "touched": true,
    "dirty": false,
    "validating": false，
"errors": [
      {
        "message": "Username is required!",
        "field": "username"
      }
    ],
  }
} 其中  validating，dirty，还有errors就是需要带着的参数。
