### ISSUE TITLE
子组件怎么从后台取到数据

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4911]
![image](https://user-images.githubusercontent.com/51696361/61849407-c0627d00-aee3-11e9-8ce1-fdd66b8d8889.png)

页面是使用 this.props.XXX 来获取数据的，直接访问此页面是可以正确运行的，但是把它嵌入到其他页面，this.props 就取不到数据了，应该怎么办呢？

![image](https://user-images.githubusercontent.com/51696361/61849412-c9534e80-aee3-11e9-831c-25bbe1ef63ae.png)

我分析是嵌入到其他页面里，props 就变成从父页面传过去的那些数据了，没有子页面自己从后台获取的数据了

**Comment by chenshuai2144** [comment]
了解一下 dva redux和 context
