### ISSUE TITLE
v2版本独立使用的时候报TS2604错误

### ISSUE THREAD

**Issue by hvsy** [ant-design/ant-design-pro#4912]
```
export default class Field extends React.Component<IFieldProps, any> {
    render(): JSX.Element;
}
```
改为这样好了

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/4871#issuecomment-514012773_

这个文件是 ant-design-pro 库里的文件.而且应该是是你们通过工具生成的声明文件.

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-blocks/tree/master/DashboardAnalysis/src/components/Charts
源码再这里，你可以直接下载

**Comment by hvsy** [comment]
@chenshuai2144 这是一个悲伤的故事
