### ISSUE TITLE
路由配置404问题(bug?)

### ISSUE THREAD

**Issue by Lzw2016** [ant-design/ant-design-pro#4913]
umijs 文档描述

![图片](https://user-images.githubusercontent.com/19291563/61852685-a8432b80-aeec-11e9-8e21-15c922d4d787.png)

目前 ant-design-pro 项目是存在 pages/404.js 文件的，但是输入一个路由匹配不上的地址不能正确路由到404页面，如下：

[https://preview.pro.ant.design/dashboard/analysis1](https://preview.pro.ant.design/dashboard/analysis1)

![图片](https://user-images.githubusercontent.com/19291563/61852941-40411500-aeed-11e9-8d81-91c59ec7ed40.png)

**Comment by chenshuai2144** [comment]
因为父路由匹配到了，只是子路由没有匹配到，所以不会触发 404。

**Comment by Lzw2016** [comment]
`父路由匹配到了，只是子路由没有匹配到` 那结果还是没有匹配到，盼望 `umi` 早点支持这个
