### ISSUE TITLE
左上角的logo 可以添加链接吗？

### ISSUE THREAD

**Issue by flycj** [ant-design/ant-design-pro#4916]
![image](https://user-images.githubusercontent.com/5103045/61919695-5a303580-af89-11e9-8842-bba8a8879582.png)
上图左上角希望可以支持在a标签上添加链接

网站有一个前台和一个后台。就是希望通过点击这个图标跳转到前台

**Comment by xiaohuoni** [comment]
可以的吧？

**Comment by flycj** [comment]
我用的组件是 @ant-design/pro-layout 组件，因为4.0以上版本basicLayout 独立成组件了
应该怎么添加呢？
我看了pro-layout 组件源码，也没看到怎么添加，是我哪里忽略了吗？

**Comment by flycj** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/50 在这里找到了

**Comment by LucaLJX** [comment]
```jsx
import router from 'umi/router'
<ProLayout
      logo={() => (
          <img onClick={() => {
            router.push(`/`)
          }} src={require('@/assets/logo.png')} alt='' />
      )}
</ ProLayout>
```
