### ISSUE TITLE
如何关闭 pwa

### ISSUE THREAD

**Issue by OrezzerO** [ant-design/ant-design-pro#4917]
浏览器缓存问题需要关闭pwa , 很多issue 上说关闭pwa 就好, like #4047 ,请问如何关闭pwa? 需要在哪个文件改什么配置?

**Comment by xiaohuoni** [comment]
https://umijs.org/zh/plugin/umi-plugin-react.html#pwa
配置文件里面，不设置这个

**Comment by xiaohuoni** [comment]
大约是在这 https://github.com/ant-design/ant-design-pro/blob/122edaf5d5baae8e102126c8a14181da60fae056/config/config.ts#L37
