### ISSUE TITLE
对 v4 版本的一点看法

### ISSUE THREAD

**Issue by basefas** [ant-design/ant-design-pro#4919]
最近公司业务需要做个后台页面，选择了 Ant Design Pro，使用的时候同时也发现很多问题，希望提出来得到官方及社区的重视及改进。

1. 文档问题： 目前 v4版本的部分文档和 v2 版本混淆，应该是好多还没来得及更新，建议严格区分版本之间的文档，暂时没更新的就指向旧版文档。ts 和 js 混淆，文档中所有事例都是以 ts 为准，但是项目却也同时支持 ts 和 js。建议除了版本区分再加上语言区分，使文档更人性化。

2. 注释问题：对比了 v2 和 v4 版本的代码，原本就不多的注释在 v4 版本里更少了，而且也存在格式不统一，中英文混用的情况，希望今后能丰富项目注释，统一风格。

3. 使用问题：作为一个只懂一点 html 和 js 的外行人，在使用 Ant Design Pro 开发的一周内，需要先后学习 react redux dva umi typescript 等等，了解项目结构及原理，然后才能开始开发自己想要的东西。当然不否认 Ant Design Pro 良好的页面设计和项目结构，但是希望能推出更多更好的教程来指导像我这样只需要做一些后台页面，不太需要关心项目架构的新人，做一个真正开箱即用的解决方案。

4. 关于 block：block 模块的提出对提升开发效率很有帮助，但是感觉现阶段的 block 粒度比较粗，很多跟自己需要的业务逻辑有差别，导致使用 block 还得自己改，不如直接新建 BlankLayout 自己写。建议能提供更细粒度的 block 模块，可以通过参数拼接自己想要的页面，达到提高开发效率的目的。当然自己没什么前端开发经验，这点可能不太正确。

5. 升级问题：脚手架安装完的项目是不带有版本控制的，鉴于 V4 未来应该会有更多内容更新，希望提供更优雅的升级方式。

以上是我使用  Ant Design Pro 时遇到的一点问题和建议，希望大家一起来讨论，来提升  Ant Design Pro 的使用体验。

**Comment by SuFIND** [comment]
自己资历浅薄计算机班科但非软件工程出生的19毕业生。作为实习过程中的一部分，学习antd pro。学习前只拥有后端restful开发，和静态页面的html以及css几乎是难以启齿的经验，入坑的版本是v2，下面的经验可能更面向js版。OK，开始倒苦水:

1. 如果是直接用现在的ts版就请从ts学习，ts只会是未来的趋势（个人意见）。js如果有c++或者javs基础你会非常快速的上手，1-2天足够入门。

2. React是逃不掉的，细致一点随便白嫖个各种网盘的网课，高效一些就照着抄一两个普通的react组件，主要了解自上而下的组件传值，ref，this的绑定（无论是es5还是es6的声明），react-route。对于初次接触antp页面逻辑实现的人，相当一部分会在react的生命周期函数上采坑，但是我觉得这部分就算你真的在react学习的时候就看了，真正实现页面逻辑也会被坑的不行，所以遇到问题在去学习和思考如何解决，这样高效也有目的性。个人大概看了某个React网课的前10节左右，然后就是冲！

3. 边看边做帮助很大，V4那个Weclome就是你的试验田，base说的Redux其实不看都可以，src/model/下的面包屑看明白了怎么用，用console.log(response或者payload)，了解一下dva的action，这个model怎么写你就稳了。

4. 如果你想配合你的后端挑几个软柿子捏？table页面不容错过！

5. 其实一路跌爬滚打文档、blog、逼乎看来看去，dva的知识地图值得推荐，学会使用console.log和各类浏览器的debug稳中带皮，怎么样快速入门才是提起兴趣和提高生产力的关键。（https://dvajs.com/knowledgemap/#javascript-%E8%AF%AD%E8%A8%80）

以上是这一两月的体会了，开箱要即用，我觉得上面OK。

**Comment by basefas** [comment]
> 自己资历浅薄计算机班科但非软件工程出生的19毕业生。作为实习过程中的一部分，学习antd pro。学习前只拥有后端restful开发，和静态页面的html以及css几乎是难以启齿的经验，入坑的版本是v2，下面的经验可能更面向js版。OK，开始倒苦水:
> 
> 1. 如果是直接用现在的ts版就请从ts学习，ts只会是未来的趋势（个人意见）。js如果有c++或者javs基础你会非常快速的上手，1-2天足够入门。
> 2. React是逃不掉的，细致一点随便白嫖个各种网盘的网课，高效一些就照着抄一两个普通的react组件，主要了解自上而下的组件传值，ref，this的绑定（无论是es5还是es6的声明），react-route。对于初次接触antp页面逻辑实现的人，相当一部分会在react的生命周期函数上采坑，但是我觉得这部分就算你真的在react学习的时候就看了，真正实现页面逻辑也会被坑的不行，所以遇到问题在去学习和思考如何解决，这样高效也有目的性。个人大概看了某个React网课的前10节左右，然后就是冲！
> 3. 边看边做帮助很大，V4那个Weclome就是你的试验田，base说的Redux其实不看都可以，src/model/下的面包屑看明白了怎么用，用console.log(response或者payload)，了解一下dva的action，这个model怎么写你就稳了。
> 4. 如果你想配合你的后端挑几个软柿子捏？table页面不容错过！
> 5. 其实一路跌爬滚打文档、blog、逼乎看来看去，dva的知识地图值得推荐，学会使用console.log和各类浏览器的debug稳中带皮，怎么样快速入门才是提起兴趣和提高生产力的关键。（[https://dvajs.com/knowledgemap/#javascript-%E8%AF%AD%E8%A8%80）](https://dvajs.com/knowledgemap/#javascript-%E8%AF%AD%E8%A8%80%EF%BC%89)
> 
> 以上是这一两月的体会了，开箱要即用，我觉得上面OK。

感谢你的分享，不过你的观点着重于怎么学习使用这个项目，而我提出的问题是关于怎么改进项目，为刚入门的使用者提供更好的入门实践。上面提出的问题仍需要改进，我们讨论的方向不一样，不过不冲突。
