### ISSUE TITLE
疑问：菜单权限，reloadAuthorized和disabled

### ISSUE THREAD

**Issue by starhu521** [ant-design/ant-design-pro#4921]
目前运行中修改权限，似乎需要：
setAuthority--->reloadAuthorized--->dispatch menudata 这样的线路，dispatch menudata还比较麻烦，我理解reloadAuthorized本应会触发相应更新，不知道这个问题有没有好的解决方案？、

另：
menu菜单的先后权限问题，就是ant设置的disabled，比如一些路由页面的访问需要依赖一定的操作之后，有什么好的方式能够解决这样的问题？

**Comment by chenshuai2144** [comment]
可以看 master 的 login
