### ISSUE TITLE
https://pro.ant.design/ 404 

### ISSUE THREAD

**Issue by 346359827** [ant-design/ant-design-pro#4922]
https://pro.ant.design/ 404

**Comment by potaty** [comment]
same ask.
home page will jump to https://preview.pro.ant.design/exception/404.

**Comment by LiangZugeng** [comment]
The official web site is down, need someone from the ant design team to fix it.

![image](https://user-images.githubusercontent.com/20870130/61935136-70a3b480-afbc-11e9-8993-a703ccc0fc74.png)

**Comment by xiaohuoni** [comment]
抱歉，已修复，我刚才脚本中止出错了。
