### ISSUE TITLE
npm create umi 或者 yarn create umi 报错，无法正常创建项目

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#4923]
使用 npm create umi 或者 yarn create umi 报错。
nodejs 版本 12.2.0
npm 版本 6.10.2
yarn 版本 1.17.3

![image](https://user-images.githubusercontent.com/50793943/61932442-fff99980-afb5-11e9-9e21-355930c3621b.png)

**Comment by shaohuatsou** [comment]
已经解决了。

**Comment by itfredmoon** [comment]
> 已经解决了。

咋解决的 楼主，我也遇到一样的报错。。。

**Comment by shaohuatsou** [comment]
> > 已经解决了。
> 
> 咋解决的 楼主，我也遇到一样的报错。。。

你安装GIT了吗？
