### ISSUE TITLE
Prov1.3版本引入typescript文件后编译无效

### ISSUE THREAD

**Issue by INTMIN** [ant-design/ant-design-pro#4924]
如下图，我的版本是1.3版本，项目内容比较多所以未升级，写了几个ts文件，本地打包成功，但是到了线上，打包91%的时候就中断了打包，也没报错，请教大佬

![](https://raw.githubusercontent.com/INTMIN/photo/master/%E6%89%93%E5%8C%85%E6%96%87%E4%BB%B6.png)

**Comment by INTMIN** [comment]
能否请教下怎么配置ts和jsx和es6共存

**Comment by chenshuai2144** [comment]
可以升级到 2.x 或者4.0 roadhog 需要自己配置webpack。非常复杂

**Comment by INTMIN** [comment]
@chenshuai2144 好的，只是项目过于庞大，升级pro怕出问题

**Comment by INTMIN** [comment]
最后自己本地编译后上传后可以用了
