### ISSUE TITLE
AspNetCore Integration.

### ISSUE THREAD

**Issue by mihai-cloudbrick** [ant-design/ant-design-pro#4925]
Im tryng to integrate antd-pro with AspNetCore and React. Im very stuck in the autorization part. 
AspNetCore uses the IdentityServer4 authorization/authentication and the basic template from Visual studio provides a way to authorize/authenticate but looks that the authorization/authentication part of antd its a little bit complicated. 
It is possible to provide me example from which i can start?  Im using Antd pro to build an Azure Market Place Application with AspNetcore as backend. 

Or an example implementing oidc
Any help will be apreciated.

**Comment by chenshuai2144** [comment]
No one in us knows net, you may need to wait for the help of the community.

**Comment by mihai-cloudbrick** [comment]
since the .umi folder its autogenerated , its there any way to add a Context Provider on top of the LocaleProvider from the .umi folder?  Like this i can add my OIDC authentication before the admin area its rendered. Its there any way to do this ?

**Comment by chenshuai2144** [comment]
you can wirte code in Lyaout compentent

**Comment by imagiroweb** [comment]
hi @mihai-cloudbrick 
did you solve the problem ? I try to make the same case of you with .net core 3.1 identity with react ant design. the auth provider, i don't know where i can put him.

**Comment by afresh** [comment]
hi @mihai-cloudbrick @imagiroweb Did you solve the problem?
