### ISSUE TITLE
三级菜单问题

### ISSUE THREAD

**Issue by Junnplus** [ant-design/ant-design-pro#4926]
![image](https://user-images.githubusercontent.com/8097526/61980397-40dec600-b029-11e9-9f79-722dddb3cd15.png)
遇到一个问题，打开工作台的页面之后，点击任意二级菜单，“管理控制台”会收缩

**Comment by hqwlkj** [comment]
你的 `openKeys ` 是不是没有设置呢？

**Comment by xuqplus** [comment]
应该是 config.js 里路由配置的不正确, 我之前也遇到了这个问题

参考 https://github.com/ant-design/ant-design-pro/pull/4989

**Comment by Junnplus** [comment]
@xuqplus thx确实是路由配置不正确，不过也是坑 - -
