### ISSUE TITLE
请问pro组件文档是怎么生成的呢

### ISSUE THREAD

**Issue by vonxq** [ant-design/ant-design-pro#493]
看官网的组件文档看起来像是bisheng生成的，但项目好像没有bisheng的依赖及配置文档，
现在我们项目也想维护一个自己的组件库，之前参考https://github.com/wuguanghai45/bisheng-antd-doc-template使用ant design的bisheng配置可以跑起来，但components组件文件夹大写就不能识别了，不知pro有没有相关文档or可提供的demo呢?如没有，给个简单方向也好，感谢

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site
