### ISSUE TITLE
Can't add umi block FormBasicForm

### ISSUE THREAD

**Issue by iloveip** [ant-design/ant-design-pro#4931]
Hi, I tried to add `npx umi block add FormBasicForm --path=/closeip/`, but I got the following error:

```
./src/pages/closeip/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/svetlana/Desktop/iloveip-pro/src/pages/closeip/index.tsx: A class name is required (11:6)

   9 | const { RangePicker } = DatePicker;
  10 | const { TextArea } = Input;
> 11 | class extends Component {
     |       ^
  12 |     constructor() {
  13 |         super(...arguments);
  14 |         this.handleSubmit = (e) => {
```

**Comment by chenshuai2144** [comment]
you can use 
`npx umi block add FormBasicForm --path=/closeip`  don’t need end of ‘/’

**Comment by iloveip** [comment]
Thank you very much for your reply! And how can I delete the previous page which was created as a block?

**Comment by z09176141** [comment]
npx umi block add FormBasicForm --path=/setting/from --js

**Comment by z09176141** [comment]
npx umi block add FormBasicForm --path=/setting/from --js

**Comment by chenshuai2144** [comment]
try use UMI UI
https://umijs.org/zh/guide/umi-ui.html

**Comment by iloveip** [comment]
Is it available in English? The documentation is only in Chinese.
