### ISSUE TITLE
访问地址404：https://pro.ant.design/blog/beter-block

### ISSUE THREAD

**Issue by WenGuangZhu** [ant-design/ant-design-pro#4932]

**Comment by WenGuangZhu** [comment]
![image](https://user-images.githubusercontent.com/32136240/61997001-9ff61680-b0cd-11e9-8e4d-a6f968cae16f.png)

**Comment by chenshuai2144** [comment]
在这里
https://pro.ant.design/blog/better-block，应该是重定向失效了
