### ISSUE TITLE
怎么修改根路由到登录页

### ISSUE THREAD

**Issue by lichunze** [ant-design/ant-design-pro#4934]
// return localStorage.getItem('antd-pro-authority') || ['admin', 'user'];
  const authorityString =
    typeof str === 'undefined' ? localStorage.getItem('antd-pro-authority') : str; // authorityString could be admin, "admin", ["admin"]

  let authority;

这样没管用的啊

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-plugin-main-path
```
export default {
  plugins: [
    ['umi-plugin-main-path'],
  ],
  mainPath:'/login'
}
```

**Comment by lichunze** [comment]
谢谢，但是我后来是用的2.0版本开发的
