### ISSUE TITLE
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.

### ISSUE THREAD

**Issue by huangyanyang** [ant-design/ant-design-pro#4935]
![image](https://user-images.githubusercontent.com/19208961/62002189-98685900-b131-11e9-9bec-1bf87ec86ee8.png)

**Comment by huangyanyang** [comment]
删了node_modules重装也跑不起来，一直是这样

**Comment by chenshuai2144** [comment]
是 2.0 版本吗？ 
看看这个 https://pro.ant.design/blog/change-theme-cn
