### ISSUE TITLE
频繁自动跳转到登录页面

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design-pro#4936]
**我正在做的：**
如果30分钟没有在网站页面进行操作，则跳转到登录页面。

**实现方式：**
通过权限校验组件(/src/pages/Authroried.js)，在window对象挂载一个30分钟的定时器，每一次校验权限的时候都清楚原来的定时器并重新设置。

**问题：**
1. 当我在网站内部进行操作的时候，不知为什么定时器没有被重置，经常会跳转登录页；
2. 如果我登陆后保持静止，不操作页面则会按照正常的30分钟进行跳转；
3. 如果我在登录后操作了网站的功能，在跳转登录页后，会出现再次跳转的现象，导致我输入账号和密码的时候回出现类似刷新页面的效果；如果不操作功能则一切正常
4. 我还发现在跳转登录页的过程中，计时器被触发了两次

**最终目的**
我想要实现30分钟网站无操作自动退出并跳转登录页的效果，且不会影响正常使用。

请有经验的同志指点一下，非常感谢。
下面是我的文件，只有一个JS文件，相关代码都放在了这个JS文件中了
[Authorized.zip](https://github.com/ant-design/ant-design-pro/files/3438853/Authorized.zip)

**以下是实现代码：**
`

function AuthComponent({ children, location, routerData }) {
    const auth = getAuthority();
    const isLogin = auth && auth[0] !== 'guest';

    const getRouteAuthority = (path, routeData) => {
        if (window.expireMachine) {
            clearTimeout(window.expireMachine);
            window.expireMachine = null;
        }

        let authorities;
        if (!isLogin) {
            authorities = () => {
                return false;
            };
        } else {
            routeData.forEach(route => {
                // match prefix
                if (pathToRegexp(`${route.path}(.*)`).test(path)) {
                    authorities = route.authority || authorities;

                    // get children authority recursively
                    if (route.routes) {
                        authorities = getRouteAuthority(path, route.routes) || authorities;
                        if (/^\/.*\//i.test(path)) {
                            if (!checkBtnPermission(path2Perm[path])) {
                                authorities = () => {
                                    return false;
                                };
                            }
                        }
                    }
                }
            });
        }
        window.expireMachine = setTimeout(() => {
            setAuthority('guest');
            setAuthInfoStorage({});
            setGlobalPermissionOperate({});
            setUserPermissionOperate({});
            router.push('/user/login');
        }, 10 * 1000);
        return authorities;
    };

    return (
        <Authorized
            authority={getRouteAuthority(location.pathname, routerData)}
            noMatch={isLogin ? <Exception403 /> : <Redirect to="/user/login" />}
        >
            {children}
        </Authorized>
    );
}

`

**Comment by hqwlkj** [comment]
关于鉴权的信息为什么不服务端验证之后再返回给客户端呢？客户端自己做这个过期的验证没有多大的意义吧。

**Comment by MarxZhou** [comment]
> 关于鉴权的信息为什么不服务端验证之后再返回给客户端呢？客户端自己做这个过期的验证没有多大的意义吧。

领导就要求这么做的，他认为这个东西不需要经过后端的验证，自己跳转就行。
请不要纠结为什么这么要求，如果可以，我也不想这么做。
添加这个自动跳转只是为了在用户登录后30分钟无操作时，防止别人看到。

**Comment by kunhour** [comment]
应该是定时器没有销毁

**Comment by MarxZhou** [comment]
> 应该是定时器没有销毁

我可以理解这个原因，但是我并不明白为什么这个定时器为什么没有被销毁。这个校验组件每一次更新路由都会被触发。而且都是先进行清除定时器，然后再重新设置。可是好像清除失败了。

**Comment by chenshuai2144** [comment]
这个是具体的业务决策，与 pro 无关先关掉了
