### ISSUE TITLE
为什么我新clone的项目dashboard中的图形显示有问题？

### ISSUE THREAD

**Issue by ZylFrank** [ant-design/ant-design-pro#4939]
ant design pro版本：v2

分析页：
![image](https://user-images.githubusercontent.com/30528319/62015065-b50c9b80-b1da-11e9-9cb6-49eae92143ee.png)

监控页：
![image](https://user-images.githubusercontent.com/30528319/62015074-cb1a5c00-b1da-11e9-8849-b8c76f43f76e.png)

**Comment by chenshuai2144** [comment]
升级一下 bizchart 到 3.5.5

**Comment by dongkeng001** [comment]
> 升级一下 bizchart 到 3.5.5

表示bizcharts升到3.5.5也不管用

"bizcharts": "^3.5.5"

**Comment by dongkeng001** [comment]
> ant design pro版本：v2
> 
> 分析页：
> ![image](https://user-images.githubusercontent.com/30528319/62015065-b50c9b80-b1da-11e9-9cb6-49eae92143ee.png)
> 
> 监控页：
> ![image](https://user-images.githubusercontent.com/30528319/62015074-cb1a5c00-b1da-11e9-8849-b8c76f43f76e.png)

请问你这个样式错位的问题解决了么？

**Comment by ZylFrank** [comment]
@dongkeng001  升级bizchart 到 3.5.5如： "bizcharts": "3.5.5" 就可以了
