### ISSUE TITLE
router.config.js中设置了component，routes中的redirect就失效了，是我用法有误吗？

### ISSUE THREAD

**Issue by xlszzck** [ant-design/ant-design-pro#4940]
router.config.js中的配置
```
{
　path: '/manage/icon', 
　component: './Manage/Icon',
　routes: [
　　{
　　　path: '/manage/icon',
　　　redirect: '/manage/icon/manage-icon'
　　},
　　{
　　　path: '/manage/icon/manage-icon',
　　　component: './Manage/Icon/ManageIcon'
　　}
　]
}
```

现在暂时解决方案是在'./Manage/Icon'的生命周期中加上替代redirect的jump跳转，因为routes中的第一个redirect已经失效，又需要在 './Manage/Icon'中用到children，所以这样去配置component和routes。
```
  componentDidMount() {
    this.jump(this.props.location.pathname);
  }

  componentWillReceiveProps(nextProps) {
    this.jump(nextProps.location.pathname);
  }

  jump = pathname => {
    if (pathname === '/manage/icon') {
      router.push('/manage/icon/manage-icon');
    }
  };
```

请问还有更优的写法吗？

**Comment by xiaohuoni** [comment]
exact?

**Comment by chenshuai2144** [comment]
可以用这个  https://umijs.org/zh/api/#umi-redirect.

redirect 不应该会失效这是 umi 中支持的。给个最小配置？

**Comment by xlszzck** [comment]
@chenshuai2144 
上面的代码，是router.config.js中的配置。因为routes的同级配置了component: './Manage/Icon'，导致routes中的redirect: '/manage/icon/manage-icon'失效。

下面那一块代码是我的替代方案（能使用）。
我是觉得这么写可能不妥，所以来问一下最优用法
