### ISSUE TITLE
请问一下使用区块开发，右上角的退出登录下拉没有，请问怎么设置，注册登录页面又该放在哪里？

### ISSUE THREAD

**Issue by hejinhua33** [ant-design/ant-design-pro#4941]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/122edaf5d5baae8e102126c8a14181da60fae056/src/components/GlobalHeader/AvatarDropdown.tsx

可以看这里的代码来打开下拉菜单
