### ISSUE TITLE
BasicLayout+Table组件在低分辨率机器出现部分隐藏

### ISSUE THREAD

**Issue by l11180730** [ant-design/ant-design-pro#4942]
![image](https://user-images.githubusercontent.com/18589562/62022560-83f29200-b1ff-11e9-93b2-1c94ef1039da.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/62024977-54e11e00-b209-11e9-845f-4e2a7cebaff5.png)


检查一下你自己的 css 是不是做了最小宽度处理
