### ISSUE TITLE
如何在现有项目中引入Ant Design Pro

### ISSUE THREAD

**Issue by LiangZugeng** [ant-design/ant-design-pro#4943]
我们用了很长时间的ant design，现在看到ant design pro的页面效果很不错，想用起来。我们的项目从17年1月就开始开发了，是基于webpack/react/react-router/redux/typescript/antd的技术栈，一直在保持更新，现在所有的项目依赖都是最新版本（包括antd）。

我的问题是：如何在现有的项目引入ant design pro，看了Getting Started和FAQ，除了使用umi命令创建脚手架全新开始一个项目这种做法外，ant design pro的Layout和其它组件怎么引入现有项目，我们的项目已经具备完整的路由/后端数据交互/安全/公共组件等东西，如何在此类项目中引入ADP？有什么Instructions文档可以看吗？

**Comment by chenshuai2144** [comment]
你需要先使用 umi 了。pro 的很多功能都构建在 umi 之上。
如果你只想使用页面。你可以直接使用 [pro-blocks](https://github.com/ant-design/pro-blocks) 中的代码

**Comment by LiangZugeng** [comment]
明白了，pro-blocks中的代码是我想要找的，umi提供的其它功能目前还没打算迁移过去。
