### ISSUE TITLE
2.0版 mac下报错

### ISSUE THREAD

**Issue by tt38491367** [ant-design/ant-design-pro#4944]
2.0版老项目，之前在苹果系统还可以用的。突然在苹果系统就运行报错，windows下正常。

These dependencies were not found:

* umi/_runtimePlugin in ./src/pages/.umi-production/umi.js, ./src/pages/.umi-production/LocaleWrapper.jsx and 2 others
* umi/dynamic in ./src/pages/.umi-production/router.js
* umi/link in ./src/components/GlobalHeader/index.js, ./src/components/PageHeaderWrapper/index.js and 8 others
* umi/redirect in ./src/pages/Authorized.js
* umi/router in ./src/layouts/BasicLayout.js, ./src/layouts/Header.js and 11 others

To install them, you can run: npm install --save umi/_runtimePlugin umi/dynamic umi/link umi/redirect umi/router

**Comment by chenshuai2144** [comment]
升级 umi 即可
