### ISSUE TITLE
预览页面无法登录

### ISSUE THREAD

**Issue by ZhelinCheng** [ant-design/ant-design-pro#4946]
登录总是报405的错误。

![TIM截图20190729152954](https://user-images.githubusercontent.com/16441850/62029768-1b62df80-b216-11e9-91f6-8b65e5d5579c.png)

**Comment by hqwlkj** [comment]
现在还不可以登录吗？

**Comment by ZhelinCheng** [comment]
> 现在还不可以登录吗？

不可以，我昨天开始使用，就有这个问题。

**Comment by chenshuai2144** [comment]
无法在线。给一下具体的环境配置信息

**Comment by ZhelinCheng** [comment]
> 无法再现。给一下具体的环境配置信息

好了，很奇怪。从昨晚到刚刚都是不行的。
