### ISSUE TITLE
运行 npm run fetch:blocks 

### ISSUE THREAD

**Issue by crocodilema** [ant-design/ant-design-pro#4952]
Run : pro fetch-blocks
Set your user:pro set user [name]
什么意思

**Comment by chenshuai2144** [comment]
你安装了另外一个 pro 的脚本吗？有再现的仓库地址吗？

**Comment by mynameismaosheng** [comment]
![CPCVZ@71O 0WEX47OHJI$W4](https://user-images.githubusercontent.com/19756360/62178257-fb006580-b37a-11e9-9664-b827051ef54c.png)
![Uploading HRE]}8K@5U[$$C28Z13AW46.png…]()

**Comment by mynameismaosheng** [comment]
![CPCVZ@71O 0WEX47OHJI$W4](https://user-images.githubusercontent.com/19756360/62178286-1b302480-b37b-11e9-94e2-22b230a9bb29.png)
![HRE }8K@5U $C28Z13AW46](https://user-images.githubusercontent.com/19756360/62178287-1d927e80-b37b-11e9-8c60-5bbd0baf5761.png)

**Comment by mynameismaosheng** [comment]
@chenshuai2144 请大佬看看

**Comment by chenshuai2144** [comment]
你这个问题看起来是包没安装，你可以执行 git -dfx 重新安装一下项目。

**Comment by mynameismaosheng** [comment]
使用npx cnpm install fetch:blocks 安装成功了
