### ISSUE TITLE
引入storybook后，如何配置才能加载上样式？

### ISSUE THREAD

**Issue by michael-lu-cn** [ant-design/ant-design-pro#4953]
目前通过网络上搜索，可以应用 ant 的样式。

但是无法加载自定义的写在less里的组件样式。不能识别css module。

谢谢！

目前的 .storybook/webpack.config.js 配置如下 
`const path = require("path");

module.exports = {
  module: {
    rules: [
      {
        loader: 'babel-loader',
        exclude: /node_modules/,
        test: /\.js$/,
        options: {
          presets: ["@babel/react"],
          plugins: [
            ['import', {libraryName: "antd", style: true}]
          ]
        },
      },
      {
        test: /\.less$/,
        loaders: [
          "style-loader",
          "css-loader",
          {
            loader: "less-loader",

            options: {
              // modifyVars: {"@primary-color": "#d8df19"},
              javascriptEnabled: true,
              modules: true,
              localIdentName: "[name]__[local]___[hash:base64:5]",
              importLoaders: 1,
 
            }
          }
        ],
        include: path.resolve(__dirname, "../src")
      },

    ]
  }
};
`

**Comment by chenshuai2144** [comment]
我们没有做过这方面的尝试，如果你的问题可以更加具体一些我们有可能提供帮助。
等待社区想相关实践的同学来帮你 吧

**Comment by cncolder** [comment]
刚出炉的 Storybook webpack 配置

```js
const getConfig = require('af-webpack/getConfig').default;

// umi webpack config
const umiConfig = getConfig({ cwd: process.cwd() });

const umiRules = umiConfig.module.rules.filter(
  rule => rule.test && rule.test.source.includes('.less'),
);

const umiPlugins = umiConfig.plugins.filter(
  plugin => plugin.constructor && plugin.constructor.name === 'MiniCssExtractPlugin',
);

module.exports = ({ config, mode }) => {
  const mergedConfig = {
    ...config,
    resolve: {
      ...config.resolve,
      ...umiConfig.resolve,
    },
    resolveLoader: umiConfig.resolveLoader,
    module: {
      ...config.module,
      rules: [...config.module.rules, ...umiRules],
    },
    plugins: [...config.plugins, ...umiPlugins],
  };

  return mergedConfig;
};

```
