### ISSUE TITLE
npm start 时报fsevents is not a constructor

### ISSUE THREAD

**Issue by may813** [ant-design/ant-design-pro#4955]
xxx/AntDesignPro/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:28
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (xxx/AntDesignPro/node_modules/watchpack/node_modules/chokidar/lib/fsevents-handler.js:28:11)

**Comment by chenshuai2144** [comment]
使用 cnpm 安装即可
