### ISSUE TITLE
使用iconfont.cn显示错误，报错

### ISSUE THREAD

**Issue by VeChar** [ant-design/ant-design-pro#4956]
错误信息：
`
index.js:1 Warning: [antd: Icon] Make sure that you provide correct `viewBox` prop (default `0 0 1024 1024`) to the icon.
`

**Comment by hqwlkj** [comment]
可以参考官网列子 https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-font-%E5%9B%BE%E6%A0%87

**Comment by VeChar** [comment]
> 可以参考官网列子 https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-font-%E5%9B%BE%E6%A0%87

是参照了 自定义 font 图标 这个标题下的描述，貌似不太行

**Comment by hqwlkj** [comment]
贴你的 代码看看呢
