### ISSUE TITLE
about npm run fetch:blocks

### ISSUE THREAD

**Issue by crocodilema** [ant-design/ant-design-pro#4958]

**Comment by crocodilema** [comment]
按照教程 
1 npm create umi
2 npm install
3 npm start  ==>成功运行 
4 npm install pro-cli
5  npm run fetch:blocks 提示 missing script:fetch:blocks

另外 这样产生的代码和 ant-design-pro的代码有啥区别 谢谢

**Comment by chenshuai2144** [comment]
npm create umi 更加纯粹，pro 的git 仓库中有一些部署预览站才需要的脚本
