### ISSUE TITLE
演示demo报错【2019-07-30】

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-pro#4959]
重现步骤
（1）https://preview.pro.ant.design 
（2）列表-查询表格

**Comment by chenshuai2144** [comment]
无法重现

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4705 
你是因为这个吗

**Comment by macmatilda** [comment]
清理了一下缓存，好像可以了
------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>;
发送时间: 2019年7月30日(星期二) 中午12:26
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "天使消失的街"<macmatilda@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] 演示demo报错【2019-07-30】 (#4959)




#4705
 你是因为这个吗
