### ISSUE TITLE
页面之间的参数传递

### ISSUE THREAD

**Issue by zlxls** [ant-design/ant-design-pro#496]
页面之间怎么进行参数传递

**Comment by chenshuai2144** [comment]
你是指什么?
路由参数?还是数据.
如果是数据,请查看dva的相关文档

**Comment by zlxls** [comment]
this.props.dispatch(routerRedux.push('/user/register-result'));

**Comment by chenshuai2144** [comment]
将数据保存到redux中,跳转完成之后去读取不行?

**Comment by zlxls** [comment]
this.props.dispatch({
            type: '/user/register-result',
            payload: {
              user: nextProps.register.data,
            },
        });

**Comment by zlxls** [comment]
这种不会跳转

**Comment by chenshuai2144** [comment]
去看看dva 和 redux吧 不是这么写的...

**Comment by dengfuping** [comment]
```javascript
this.props.dispatch({
    type: '/user/register-result',
    payload: {
        user: nextProps.register.data,
    },
});
```
should be like this:
```javascript
import { routerRedux } from 'dva/router';

this.props.dispatch(routerRedux.push('/user', { name: 'zlxls', age: 20 }))
this.props.dispatch(routerRedux.push({
    pathname: '/user',
    query: { name: 'zlxls', age: 20 },
}));
```
To get the params passed to ‘/user’, you can use `this.props.location.query` for [dva@1.x](https://github.com/dvajs/dva/tree/1.x) and `this.props.location.state` for [dva@2.x](https://github.com/dvajs/dva). If you want to know more usage about routerRedux, which is just the alias of react-router-redux, it will be helpful to read the [docs](https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward)
