### ISSUE TITLE
bash:umi ：未找到命令 

### ISSUE THREAD

**Issue by crocodilema** [ant-design/ant-design-pro#4960]
1 npm create umi
2 npm install
3 npm start ==>成功运行
4 npm install pro-cli
5 npm run fetch:blocks 提示 missing script:fetch:blocks   （没有拼写错误）
另外  按照教程 更新umi 到@2.8.16  运行 umi block list  提示bash:umi ：未找到命令

**Comment by chenshuai2144** [comment]
如果没有全部安装 umi 需要使用 `npx umi block list`

**Comment by iceMusic** [comment]
yuge-2:antd-pro-umi-demo name$ npm run fetch:blocks
npm ERR! missing script: fetch:blocks

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yuge/.npm/_logs/2019-12-11T08_57_07_096Z-debug.log

我也遇到这个问题了，请问是怎么解决的？

**Comment by iceMusic** [comment]
`antd-pro-umi-demo name$ npm run fetch:blocks
npm ERR! missing script: fetch:blocks

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yuge/.npm/_logs/2019-12-11T08_57_07_096Z-debug.log
yuge-2:antd-pro-umi-demo yuge$ `
我也遇到这个问题了，请问是怎么解决的

`antd-pro-umi-demo name$ npx umi block list
⠸ 🚣  fetch block list✖  error     HTTPError: Response code 404 (Not Found) 
    at EventEmitter.emitter.on (/Users/yuge/Desktop/antd-pro-umi-demo/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
⠧`
执行这个也是一直报错拉取不下来

**Comment by iceMusic** [comment]
antd-pro-umi-demo name$ npm run fetch:blocks
npm ERR! missing script: fetch:blocks

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2019-12-11T08_57_07_096Z-debug.log

我也遇到这个问题了，请问是怎么解决的？
