### ISSUE TITLE
Please don't remove proptypes on production build

### ISSUE THREAD

**Issue by linonetwo** [ant-design/ant-design-pro#4961]
Slatejs rely on prop-types on runtime, but antd-pro build will strip all proptypes. So after the build, antd-pro will throw:

`Uncaught (in promise) TypeError: Cannot convert undefined or null to object`

in production build, in `Object.keys(t.propTypes)`

**Comment by chenshuai2144** [comment]
cc @sorrycc

**Comment by linonetwo** [comment]
So you really strip the propTypes?

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
