### ISSUE TITLE
TS2440: Import declaration conflicts with local declaration of 'Form'

### ISSUE THREAD

**Issue by JackDan9** [ant-design/ant-design-pro#4962]
```typescript
import {
  Button,
  Card,
  DatePicker,
  Form,
  Icon,
  Input,
  InputNumber,
  Radio,
  Select,
  Tooltip,
} from 'antd';
```
The Import declaration of 'Form'.
```typescript
class Form extends Component<FormProps> {

}
```
The local declaration of 'Form' from `umi block BasicForm`.
So, I have a suggestion to change the local declaration of 'Form'  avoid the problem.
Thanks!

**Comment by chenshuai2144** [comment]
We need a whitelist to do the name rendering

**Comment by JackDan9** [comment]
Ok, The way can solve the bug.
I am also thinking about how to solve this problem.
If you solve it, please tell me.
Thanks!

**Comment by chenshuai2144** [comment]
fix，weclome use umi ui 
https://umijs.org/zh/guide/umi-ui.html
