### ISSUE TITLE
BasicLayout.tsx中获取的一些基础信息接口子路由中有时候获取不到接口返回的数据，在线等解决方案，大家都没遇到吗？

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#4965]
项目里在BasicLayout.tsx里调用用户信息和基础设置，但是发现刷新的时候，有几率还没加载到基础设置  就走到子路由的一些处理逻辑了，导致读取不到基础设置的一些内容，这块怎么保证BasicLayout中接口调用完成后再渲染子路由呢？

下图，获取用户的设置信息
![image](https://user-images.githubusercontent.com/33716687/62112345-22a4ee80-b2e5-11e9-8de2-1a7bc921b817.png)

在其他页面获取用户的设置信息，这时候有几率获取不到用户设置信息，感觉是读取用户设置信息还没获取到，就开始走子路由的这里的逻辑了
![image](https://user-images.githubusercontent.com/33716687/62112486-63046c80-b2e5-11e9-83d4-212e5456b7d4.png)

大佬们，这个咋解决？在线等。。。

**Comment by XSmarter** [comment]
![image](https://user-images.githubusercontent.com/33716687/62339949-6596da00-b510-11e9-81be-45777764d684.png)
先这么处理了一下，感觉最好框架处理一下 ，下图的models走完再继续走子路由逻辑
![image](https://user-images.githubusercontent.com/33716687/62340365-0fc33180-b512-11e9-94ca-b2a42b1c06c0.png)

**Comment by chenshuai2144** [comment]
你可以layout 上在封装一层
https://github.com/ant-design/ant-design-pro/issues/3808
