### ISSUE TITLE
如何配置 scss 支持？

### ISSUE THREAD

**Issue by nishuer** [ant-design/ant-design-pro#4967]
config.ts 文件中如何配置 scss 支持。

**Comment by xiaohuoni** [comment]
https://umijs.org/zh/guide/faq.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-sass-%EF%BC%9F

**Comment by zhangfu-git** [comment]
> https://umijs.org/zh/guide/faq.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-sass-%EF%BC%9F

访问不了
