### ISSUE TITLE
defaultSetting.js 里设置 contentWidth: 'Fixed' 如何才能生成带有 .ant-pro-grid-content.wide 类名的容器

### ISSUE THREAD

**Issue by puretang** [ant-design/ant-design-pro#4968]
想参照官方示例弄个宽度固定的布局，设置以后 header 没问题, 但是无从参考如何让 content 也固定宽度。
![image](https://user-images.githubusercontent.com/14257482/62125717-82f55980-b300-11e9-9996-2517277f124d.png)
如图，请问框选的样式名需要使用哪个组件才能生成。

**Comment by puretang** [comment]
![image](https://user-images.githubusercontent.com/14257482/62126419-3743af80-b302-11e9-9a52-56193c4e216d.png)
在 ant-design/ant-design-pro-layout 这个库里找到了。。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout#gridcontent
