### ISSUE TITLE
按照部署里的发布，css没加载

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design-pro#4969]
![image](https://user-images.githubusercontent.com/48147837/62129409-3e21f080-b309-11e9-8460-def7fe0b6e5a.png)

这是配置。
![image](https://user-images.githubusercontent.com/48147837/62129258-d8cdff80-b308-11e9-8a14-41d3657c4fe0.png)
没有样式。。
![image](https://user-images.githubusercontent.com/48147837/62129316-fc914580-b308-11e9-867d-03ff3985d3a2.png)
有这个警告

**Comment by chenshuai2144** [comment]
看一下，你的 umi.css 可能反回了一个 html。检查一下你的路径吧

**Comment by k983551019** [comment]
> 看一下，你的umi.css可能反回了一个html。检查一下你的路径吧

怎么检查啊，本地发布样式是OK的。 然后我换了一台服务器。又是好的。。

**Comment by ZuhuaLiu** [comment]
最后怎么解决的

**Comment by ZuhuaLiu** [comment]
我也遇到相同的问题了

**Comment by arrowfeng** [comment]
请在nginx配置中添加这个配置
include mime.types
