### ISSUE TITLE
请问国际化英文版内置文案的开发计划？

### ISSUE THREAD

**Issue by CrewS** [ant-design/ant-design-pro#497]
因为项目需求需要用到多语言切换
react-intl 已实现自定义翻译，但是内置组件的多语言模块antd3.0并没有实现·
所以想咨询一下 这个开发计划
多谢

**Comment by chenshuai2144** [comment]
#120 
看看这个

**Comment by ddcat1115** [comment]
Please trace #120 and I'll close this.
