### ISSUE TITLE
F5一刷新会有这个菜单 一刷新完就没了  就那么0点几秒时间显示 什么原因？

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#4970]
![image](https://user-images.githubusercontent.com/47104575/62181306-7f57e600-b385-11e9-8361-a174bb3ba20d.png)
就是这个数据字典 刷新完就没了   菜单不显示
![image](https://user-images.githubusercontent.com/47104575/62186442-ed59d880-b398-11e9-9423-60509b7fd2fe.png)
直接输入地址进入路由 面包屑也正常 菜单怎么会不见了
![image](https://user-images.githubusercontent.com/47104575/62186383-b08de180-b398-11e9-9e38-f93e2dceca7b.png)

**Comment by 904492381** [comment]
@chenshuai2144

**Comment by 904492381** [comment]
直接地址进入路由 面包屑也正常 菜单怎么会不见了
![image](https://user-images.githubusercontent.com/47104575/62186383-b08de180-b398-11e9-9e38-f93e2dceca7b.png)

**Comment by chenshuai2144** [comment]
你对 menuData 做了什么处理吧

**Comment by 904492381** [comment]
> 你对 menuData 做了什么处理吧

menudata在哪  这个别人的项目 2.0版本的 好像没看到
