### ISSUE TITLE
没有登录，直接跳转到主页，怎么做登录拦截呢？ v4版本

### ISSUE THREAD

**Issue by zcxiyou** [ant-design/ant-design-pro#4971]
v4版本中，控制权限的地方很多，没有明白在哪里控制拦截信息，并跳转，能否给个官方的解决方案，antd pro v4资料太少了

**Comment by wangmhaha** [comment]
我也出现了这个问题，没有登陆直接跳转到了主页，在网上看了些方法，试了下还是不行，不是很明白

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/5088

漏网之鱼
