### ISSUE TITLE
关于ant-design-pro 开发环境下载区块遇到的问题

### ISSUE THREAD

**Issue by yiluxiangbei87110** [ant-design/ant-design-pro#4972]
1. 下载区块搜索列表项目 key值报错
![image](https://user-images.githubusercontent.com/23131032/62190470-fef4ad80-b3a3-11e9-8c74-8cdca29f4b6d.png)

2. 高级表单成员管理 点击取消交互逻辑没有发生变化

![vue inputnumber](https://user-images.githubusercontent.com/23131032/62191322-e1284800-b3a5-11e9-8bcd-44842ec0cefb.gif)

问题出现的原因：
1. map并不会修改原有的数组，会返回新的数组。
2. this.cacheOriginData[key]原始数据应该在取消的时候替换修改的部分后，方能删掉。
![image](https://user-images.githubusercontent.com/23131032/62191504-29e00100-b3a6-11e9-9875-d79337e0fd64.png)

修改后的结果：
![vue inputnumber1](https://user-images.githubusercontent.com/23131032/62191358-eb4a4680-b3a5-11e9-94fa-3abeb9055cf4.gif)

![image](https://user-images.githubusercontent.com/23131032/62191627-74fa1400-b3a6-11e9-9296-0f96f284e5ff.png)

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by yiluxiangbei87110** [comment]
好
