### ISSUE TITLE
我想添加多几个字段，提交时报错500，请问一下handleAdd = (fields:{name:any})这里怎么设置

### ISSUE THREAD

**Issue by hejinhua33** [ant-design/ant-design-pro#4973]
![image](https://user-images.githubusercontent.com/44763470/62191844-fbaef100-b3a6-11e9-9062-f9b990a82afc.png)
![image](https://user-images.githubusercontent.com/44763470/62191873-0b2e3a00-b3a7-11e9-9d2d-0cceb4cc5b42.png)

**Comment by chenshuai2144** [comment]
500 是服务器错误，联系你们的后短筒靴
