### ISSUE TITLE
路由重定向报错

### ISSUE THREAD

**Issue by Pzhicong** [ant-design/ant-design-pro#4974]
![image](https://user-images.githubusercontent.com/13126996/62195787-4d5b7980-b3af-11e9-99ff-1cecbd6ed540.png)
![image](https://user-images.githubusercontent.com/13126996/62195826-5fd5b300-b3af-11e9-9047-0c60354df545.png)
浏览器默认打开8080/端口的时候，报了页面404，改了重定向之后，报了重复路由，请问下要怎么去控制呢？

**Comment by chenshuai2144** [comment]
在 "/" 的children 下 增加` { path:"/",redirect:"/home"}`，不要写在 layout上
