### ISSUE TITLE
npm run fetch:blocks  和用cnpm  下载，有的js 没下下来，list下了但是报Module not found: Can't resolve '../list/search' in 'D:\react\src\pages\.umi'

### ISSUE THREAD

**Issue by yangliuyiyitlp** [ant-design/ant-design-pro#4977]

**Comment by chenshuai2144** [comment]
`npm run fetch:blocks `  会先生成所有的路由的。然后再去下载

**Comment by plane-hjh** [comment]
我也碰到这种问题，没有办法解决吗

**Comment by TuomaXu** [comment]
我也是这个问题

**Comment by chengzequn** [comment]
个人感觉自动生成的路由有问题，自己手动修改某些路由后页面就能显示正常。但是重新启动后，路由又自动重启复原了，目前还不知道怎么设置让其不再自动生成。

**Comment by chengzequn** [comment]
自动生成的路由是根据config/config.ts中的配置自动生成的。里面配置的路由规则应该是有问题的，把config.ts中的139行“component: './list/search',”删除，应用能便能正常使用，list列表也能显示正常，其他组件的问题应该也和这个一样。

**Comment by chenshuai2144** [comment]
npm run fetch:blocks 现在和 cnpm 不兼容，尽量使用 yarn 吧

**Comment by silianpan** [comment]
配置npm淘宝源，采用umi block list选择区块下载，不会有问题

**Comment by chenshuai2144** [comment]
有了新的选择。 https://www.npmjs.com/package/tyarn
