### ISSUE TITLE
CI部署，这步超级慢，而且大概率会出错，[5/5] Building fresh packages...

### ISSUE THREAD

**Issue by zytjs** [ant-design/ant-design-pro#4979]
`[5/5] Building fresh packages...`  
求教有解决办法吗

**Comment by chenshuai2144** [comment]
这个应该是在安装 puppeteer
https://pro.ant.design/docs/faq-cn#npm-%E5%AE%89%E8%A3%85-puppeteer-%E5%A4%B1%E8%B4%A5
