### ISSUE TITLE
线上环境，页面打开后长时间不动作，再次点击左侧menu，页面白屏，刷新页面也无效，必须退出登陆重新登陆才可以

### ISSUE THREAD

**Issue by crane2017** [ant-design/ant-design-pro#4980]
![screenshot_1_1564553863](http://r.mbinfo.cn/redmine/attachments/download/2522/screenshot_1_1564553863.png)

**Comment by crane2017** [comment]
我当时大概3-4小时没动页面，出现了这个现象

**Comment by crane2017** [comment]
![screenshot_1_1564553863](https://user-images.githubusercontent.com/29011458/62262072-0c647300-b44a-11e9-95f0-cf7050aa6334.png)

**Comment by dongkeng001** [comment]
可以先把控制台报错的问题先解决下，貌似报这样的错，一般数组给了null导致不是数组才报这样的错

**Comment by chenshuai2144** [comment]
这个是你业务逻辑的问题，你是有轮询吗？
