### ISSUE TITLE
gg-editor怎么实现鼠标的滚轮缩放功能，修改mode没有效果

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design-pro#4981]
gg-editor怎么实现鼠标的滚轮缩放功能，修改mode没有效果；
还有Flow怎么无法监听onMouseWheel事件，直接监听行为的mousewheel事件也不起作用

**Comment by chenshuai2144** [comment]
https://www.yuque.com/antv/g6/api-g6
