### ISSUE TITLE
Table组件里的拖拽排序用不了 报错

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#4982]
![image](https://user-images.githubusercontent.com/47104575/62278608-0470f700-b47b-11e9-8a83-5df2661a9d2b.png)

用的这个
![image](https://user-images.githubusercontent.com/47104575/62278806-63cf0700-b47b-11e9-82ae-a2f9e5ce4e95.png)

**Comment by wangxingxing123654** [comment]
看报错都给你提示了

**Comment by 904492381** [comment]
导出的是class啊  复制源码的

**Comment by chenshuai2144** [comment]
估计是低级错误
https://github.com/ant-design/ant-design-pro/issues/5013
