### ISSUE TITLE
查询表格在新建返回之后内容丢失

### ISSUE THREAD

**Issue by lizhenmxcz** [ant-design/ant-design-pro#4983]
新建成功返回之后，表格的原本数据丢失，经调试，props的data属性丢失。mock模式下，没有问题，但是改为server api出现上述问题。

**Comment by chenshuai2144** [comment]
props.data 是在 dva 中定义的吧，你估计不小心重置了。
先检查你的代码这个应该和 pro 无关。
先关掉了
