### ISSUE TITLE
Table表格图片设置高度后如果没有图片则fixed高度不齐

### ISSUE THREAD

**Issue by leebooe** [ant-design/ant-design-pro#4984]
![QQ截图20190801184353](https://user-images.githubusercontent.com/15071751/62288072-288a0380-b48e-11e9-8b23-be07e81b255c.png)
![QQ截图20190801184519](https://user-images.githubusercontent.com/15071751/62288078-2b84f400-b48e-11e9-9991-ae78d67a1553.png)

当图片链接不能正常访问时就会出现该情况

**Comment by chenshuai2144** [comment]
你放一个 空的 dom，高度一样好了。
table 的 flex 计算的高度好像是根据第一行来了
