### ISSUE TITLE
移动端的ui  非常不友好

### ISSUE THREAD

**Issue by nv4010** [ant-design/ant-design-pro#499]

**Comment by hqwlkj** [comment]
Same feeling

**Comment by warmhug** [comment]
可以想想有没有办法，动态 port 到 antd-mobile 相应组件？

**Comment by chenshuai2144** [comment]
@warmhug  这是个很大的工程,需要一次写两份代码了

**Comment by warmhug** [comment]
用户写代码还是一套，能做一层自动转换器组件最好

**Comment by nv4010** [comment]
怎么会  需要两套  css  就可以完成了

**Comment by warmhug** [comment]
不只是 css 的适配，事件在 pc 和移动端也有很大不同

**Comment by chenshuai2144** [comment]
没有那么简单的. 很多ui
比如很长表格在app上就并不适用.

**Comment by nv4010** [comment]
反正我是改过的    table  可以参照ant-mobile  版的

**Comment by ddcat1115** [comment]
具体是哪里感觉不爽可以提出来，如果是利用响应式样式优化等简单方案能解决的， 可以加上。但目前 antd pro 主要还是面向桌面应用，尽量兼顾一下小屏展现，不会针对移动端做优化。

**Comment by chenqingspring** [comment]
建议把左边的sidebar收到左上角的menu里

**Comment by chenshuai2144** [comment]
@chenqingspring    #463  看这个

**Comment by chenqingspring** [comment]
@chenshuai2144  awesome! 啥时候能release?

**Comment by chenshuai2144** [comment]
下周又下周.. 你看看隔壁babel  beta36了

**Comment by ddcat1115** [comment]
@chenqingspring 现在这个pr已经合进来了，master 上已可用

**Comment by ddcat1115** [comment]
有具体问题再重新提 issue 吧，这个close了

**Comment by chenqingspring** [comment]
好的 :) @ddcat1115
