### ISSUE TITLE
Select 样式问题

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#4992]
![image](https://user-images.githubusercontent.com/51696361/62348189-de0c9380-b52e-11e9-811b-b5f601206c55.png)
代码
![image](https://user-images.githubusercontent.com/51696361/62348209-ecf34600-b52e-11e9-80bf-79c027e9ad98.png)

**Comment by Benpaodejiezai** [comment]
![image](https://user-images.githubusercontent.com/51696361/62348290-2fb51e00-b52f-11e9-8572-f8fa9ea54e9f.png)
放到 Form里面也一样
![image](https://user-images.githubusercontent.com/51696361/62348296-38a5ef80-b52f-11e9-914b-33162e3a305b.png)

**Comment by afc163** [comment]
Select 默认没有宽度，你需要自行指定一个。
