### ISSUE TITLE
Authorized - not working with trailing '/'

### ISSUE THREAD

**Issue by scotty595** [ant-design/ant-design-pro#4993]
I'm currently working on an Antd Prop project, and I'm having issues with the Authority component/page.

Current router config is set up like so:
![image](https://user-images.githubusercontent.com/19480825/62348932-9d6a4580-b541-11e9-8750-4eba277709b1.png)

When navigating to https://app.url/dashboard the authorised component redirects to login page as per:
![image](https://user-images.githubusercontent.com/19480825/62349016-d1456b00-b541-11e9-8c2a-a3ea105f8a96.png)

However when navigating to https://app.url/dashboard/ (with the trailing '/') the app doesn't navigate to login and allows access to the page.

I've updated the getRouteAuthority() function to include the following:
![image](https://user-images.githubusercontent.com/19480825/62349279-9f80d400-b542-11e9-9454-bae24815e067.png)

Which seems to solve the issue for me, however not sure if it may be an issue with my config somewhere - or if it's an issue.

**Comment by chenshuai2144** [comment]
He seems to want a bug, how about launching a pr?

**Comment by scotty595** [comment]
Happy to create a PR. Just wanted to check there wasn't an issue with my config first.

**Comment by scotty595** [comment]
PR: #5015

**Comment by chenshuai2144** [comment]
fixed
