### ISSUE TITLE
Side bar list's heading is not shown during collapsed state 

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#4994]
Hi Team ,
I  have concern here, actually when the side navigational bar is expanded it will show the main list heading as shown in the below screenshot, example , here Dashboard is shown as a main list heading
![image](https://user-images.githubusercontent.com/15693408/62359507-90932500-b534-11e9-8713-71527907dcd3.png)

Similarly when the side bar is collapsed the main list heading has to shown like dashboard when you hover the icons some where in that place , but currently it will only shows the sub menu items name , but main menu/list item is not visible
![image](https://user-images.githubusercontent.com/15693408/62359533-9c7ee700-b534-11e9-94d2-0708417695de.png)

so is there any solution to show main menu heading when the navigation bar is collapsed

**Comment by chenshuai2144** [comment]
This is the specification of antd, we think this kind of user experience will be better, if there is no submenu will show tootip. If you have questions, you can consult in the issue of antd
