### ISSUE TITLE
最新antd pro-v4引用SettingDrawer 点击风格设置无效

### ISSUE THREAD

**Issue by beijinghuzi** [ant-design/ant-design-pro#4995]
头部有引用，SettingDrawer 组件点击都是没有效果 这个源码呗封装到ProLayout里了？无法查看修改SettingDrawer 里的代码？求全部引用示例，https://github.com/ant-design/ant-design-pro-layout#Settings这个已经查看。引用有点击事件都无效

 <ProLayout
      logo={logo}
      onCollapse={handleMenuCollapse} 
..... rightContentRender={rightProps => <RightContent {...rightProps} />}
      {...props}
      {...settings}
    >
      {children}
       <SettingDrawer />
    </ProLayout>

**Comment by beijinghuzi** [comment]
{children}
       <SettingDrawer />
    </ProLayout>

**Comment by beijinghuzi** [comment]
<ProLayout
logo={logo}
{...settings}
> {children}
       <SettingDrawer />
    </ProLayout>

**Comment by beijinghuzi** [comment]
{children}
       <SettingDrawer />
    </ProLayout>

**Comment by chenshuai2144** [comment]
再整理一下语言吧，没有听懂你想要说什么
