### ISSUE TITLE
测试 models 的effects和reducer？

### ISSUE THREAD

**Issue by fishenal** [ant-design/ant-design-pro#4998]
如何测试，如何在测试文件里引用models里的redux-saga配置文件，有样例吗？

**Comment by chenshuai2144** [comment]
https://www.tutorialspoint.com/redux/redux_testing

看看这个

**Comment by fishenal** [comment]
@chenshuai2144 谢谢，这是基于散写的redux，包括还能搜到redux-saga的测试，antd-pro是封装在dva里，应该是通过dva/saga接口去调用redux内容，https://dvajs.com/api/#dva-saga，不过我没有试出来，也没看到具体的代码样例。。。。。。

**Comment by chenshuai2144** [comment]
dva 是 redux 的封装而已

**Comment by fishenal** [comment]
> dva 是 redux 的封装而已

dva封装并代理了redux-saga的接口啊，在dva项目里无法直接调用redux-saga的接口
