### ISSUE TITLE
怎么在menu list和header之间插入自定义的模块

### ISSUE THREAD

**Issue by liangjingxian** [ant-design/ant-design-pro#4999]
![微信图片_20190802185150](https://user-images.githubusercontent.com/19799139/62365413-a285bf80-b556-11e9-9ebf-7db28d14dc57.png)
![微信图片_20190802185051](https://user-images.githubusercontent.com/19799139/62365421-a44f8300-b556-11e9-82a2-985c2151b4c3.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/pull/74
关注一下这个 api

**Comment by chenshuai2144** [comment]
ant-design/ant-design-pro-layout#74  已发布，升级到 4.5.12 中即可使用
