### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by maxlibin** [ant-design/ant-design-pro#50]
git clone git@github.com:ant-design/ant-design-pro --depth=1 不能使用

**Comment by valleykid** [comment]
Try this: `git clone https://github.com/ant-design/ant-design-pro.git --depth=1`

**Comment by afc163** [comment]
Check your local environment and google for that, nothing else we can help...

**Comment by maxlibin** [comment]
thats what I am saying change to https in ur README maybe?

**Comment by afc163** [comment]
They should all works.
