### ISSUE TITLE
高级详情页中能够如何根据选择的Tab不同渲染不同的数据？

### ISSUE THREAD

**Issue by anshengme** [ant-design/ant-design-pro#5000]
看演示站中也没有这个功能：https://preview.pro.ant.design/profile/advanced

**Comment by diangong** [comment]
我是用tab的事件改变state,根据state 渲染

**Comment by anshengme** [comment]
@diangong 有示例demo嘛？

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/list/search/articles
