### ISSUE TITLE
为什么只有一个欢迎页？

### ISSUE THREAD

**Issue by GavinGuoweiXu** [ant-design/ant-design-pro#5001]
本人超级小白一个，请教各路大神一个问题。
为什么我参照例子构建完成之后只有一个欢迎页面？
怎么才能找到像演示例子那样的代码？

**Comment by UnicornXU** [comment]
可以下载区块,找到演示例子

**Comment by UnicornXU** [comment]
这是地址: https://pro.ant.design/docs/block-cn

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4338
