### ISSUE TITLE
V4版本左侧菜单栏找不到自定义方式

### ISSUE THREAD

**Issue by UnicornXU** [ant-design/ant-design-pro#5002]
原V2版本左侧菜单在components中SliderMenu中,可以自定义样式进行改造,现在V4根本找不到菜单组件,想问该在哪修改,好完成自定义菜单栏及其他布局样式

**Comment by UnicornXU** [comment]
@afc163

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout
看这里

**Comment by UnicornXU** [comment]
谢谢大佬  指点

**Comment by UnicornXU** [comment]
> https://github.com/ant-design/ant-design-pro-layout
> 看这里

谢谢  大佬指点
