### ISSUE TITLE
Antd Pro + Auth

### ISSUE THREAD

**Issue by arherzf8er** [ant-design/ant-design-pro#5004]
首先，感谢您使用优质且易于使用的产品！
目前正在尝试使用Firebase Auth实现一种用户管理。
由于Antd Pro授权模块的内部结构相当复杂，我想知道是否有任何最佳实践可以安全可靠地完成它？

我想找一个熟练的开发人员并付钱让他告诉我如何做到这一点 (我怎样才能找到这样的开发者？)
或者你可以只列出我应该注意的文件并注意？

**Comment by wangxingkang** [comment]
可以搞个模板，玩一下
