### ISSUE TITLE
yarn create umi myapp 还是出现 node-fetch 错误

### ISSUE THREAD

**Issue by tgy3300** [ant-design/ant-design-pro#5005]
问题重现步骤
1、运行：yarn create umi myapp
2、选择 ant-design-pro 回车
3、就出现 Generate failed { Error: Cannot find module 'node-fetch' 的错误

我cnpm install -g umi到最新了，还是不行

我 cnpm install -g node-fetch 了，还是不行

我 umi版本：2.8.16

**Comment by chenshuai2144** [comment]
cnpm 和 yarn  npm 可能有一些兼容问题，你可以尝试直接用` npx create umi myapp`

**Comment by attraction11** [comment]
@tgy3300  
可以使用
# 国内源
$ npm i yarn tyarn -g
# 后面文档里的 yarn 换成 tyarn
$ tyarn -v

tyarn create umi  试试  这样我可以创建项目
