### ISSUE TITLE
v4.0 typescript版本，如何设置支持import绝对路径？

### ISSUE THREAD

**Issue by blackholll** [ant-design/ant-design-pro#5008]
如何配置来支持
import WrappedFormAdvancedAddForm from 'src/pages/workflow/WorkflowConfig/WorkflowAddForm';
而不是使用:
 import WrappedFormAdvancedAddForm from './WorkflowAddForm'

**Comment by chenshuai2144** [comment]
为什么要这么难受？
umi 自带了 @ 别名，代表 src 文件夹 ‘@/pages/workflow/WorkflowConfig/WorkflowAddForm’ 
是可以工作的

**Comment by wangxingkang** [comment]
用别名比较适合 ts 的话 设置下paths  

```
"paths": {
      "@/*": ["./src/*"]
    }
```

**Comment by blackholll** [comment]
多谢两位， 试了下可以。  paths这个已经默认设置过了 在tsconfig.json中

**Comment by blackholll** [comment]
多谢两位， 试了下可以。  paths这个已经默认设置过了 在tsconfig.json中
