### ISSUE TITLE
request.js中的头部信息会导致跨域问题。

### ISSUE THREAD

**Issue by lazy1523** [ant-design/ant-design-pro#501]
Accept: 'application/json',
      'Content-Type': 'application/json; charset=utf-8',
这段头部信息的存在，会导致跨域请求403错误，需要服务器打开CORS功能。
如果不加，浏览器会以默认策略添加，服务器不需要打开CORS也可以正常请求。

**Comment by lazy1523** [comment]
Accept: 'application/json',
 'Content-Type': 'application/json; charset=utf-8',

如果有这一段，会导致跨域请求403错误， 服务器需要打开CORS才可以访问。
如果不添加，浏览器会以默认的策略添加头部信息，服务器不需要CORS，也可以正常访问。
请问这个问题 该如何选择呢？

**Comment by lazy1523** [comment]
请问该怎么解决呢

**Comment by chenshuai2144** [comment]
你看一下头信息 自己设置成一样得不就好了

**Comment by wunayou** [comment]
这种问题先百度一下   CORS有复杂和简单二种
