### ISSUE TITLE
umi block list error

### ISSUE THREAD

**Issue by samlin03** [ant-design/ant-design-pro#5012]
![image](https://user-images.githubusercontent.com/20283873/62440650-a185a580-b783-11e9-8993-063e891d342b.png)

**Comment by samlin03** [comment]
最后一直卡在这个进度里
![image](https://user-images.githubusercontent.com/20283873/62440840-69cb2d80-b784-11e9-99e9-3a1cab37557c.png)

**Comment by chenshuai2144** [comment]
你是使用了 js 吗？

**Comment by chenshuai2144** [comment]
临时搞了一个解决方案
https://github.com/chenshuai2144/umi-remove-locale/commit/96d60b4232d5015ddb1bcd3e532999834de1fddb

**Comment by chenshuai2144** [comment]
已经支持了。更新依赖即可
