### ISSUE TITLE
Table组件里的拖拽排序引入报错 其他表格引入没问题

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5013]
![RL4{~T02FR3BS74FW7F98DP](https://user-images.githubusercontent.com/47104575/62442470-9aae6100-b78a-11e9-9c88-73544c012d58.png)
报错原因我也正确export default 导出了
![image](https://user-images.githubusercontent.com/47104575/62442562-da754880-b78a-11e9-9d69-d5234282d608.png)
导入
![image](https://user-images.githubusercontent.com/47104575/62442581-ea8d2800-b78a-11e9-8c1d-7fe0b05635b5.png)

**Comment by 904492381** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
信息过于模糊，你可能是单纯的文件名大小写，或者拼错了
