### ISSUE TITLE
新项目git后运行报警告LocaleProvider is deprecated.

### ISSUE THREAD

**Issue by lonelyant** [ant-design/ant-design-pro#5014]
`Warning: [antd: LocaleProvider] `LocaleProvider` is deprecated. Please use `locale` with `ConfigProvider` instead: http://u.ant.design/locale`

语言选用的是js

搜索了一下，好像用到`LocaleProvider`的地方只有`src/pages/.umi/LocaleWrapper.jsx`，官方建议是`.umi`文件下不能修改，那这个应该怎么解决呢？

**Comment by chenshuai2144** [comment]
这是个 warning ，你可以暂时忽略，会在 umi-locale 中最修改

**Comment by kele527** [comment]
我也报了这个错误，但是我全局搜索代码，没有任何地方用到 LocaleProvider  为什么还会报这个错误？

**Comment by kele527** [comment]
> 这是个 warning ，你可以暂时忽略，会在 umi-locale 中做修改

是你们改，还是自己改？

**Comment by TnWah** [comment]
记录位置，接收更新通知

**Comment by LuzMariaa** [comment]
此外，除了这个错误还有一堆这个warning  @chenshuai2144 
“react-dom.development.js:11495 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ConnectedRouter, Route, Router, Switch”

**Comment by hoosin** [comment]
@LuzMariaa 这个是因为官方不推荐使用 componentDidMount 了

**Comment by chenshuai2144** [comment]
look https://github.com/umijs/umi/pull/2941

**Comment by ycjcl868** [comment]
同时也需要兼容 3.21.0 之前的版本

**Comment by piaobodewu** [comment]
遇到了同样的问题，好像官方还是没修复好

**Comment by zhipingzhang** [comment]
请问好了吗，我umi更新到了最新版，还是不行，还有那一堆componentWillMount has been renamed的警告。

**Comment by ycjcl868** [comment]
umi 发个新版就 ok 了。

**Comment by zhipingzhang** [comment]
@ycjcl868 您好，我清理后重新install，然后使用 umi dev 启动，还是同样的警告，lock文件中我看umi依赖已经是最新版了
umi@^2.8.7:
  version "2.8.18"

**Comment by ZylFrank** [comment]
相同的问题clone的最新版项目启动时1个error6个warning
<img width="1659" alt="图片" src="https://user-images.githubusercontent.com/30528319/63410591-3d6f0c80-c426-11e9-85f1-a60e0af88050.png">

umi 为2.8.18版本：

<img width="1088" alt="图片" src="https://user-images.githubusercontent.com/30528319/63410656-61325280-c426-11e9-8cb5-3ce7566ff49c.png">

**Comment by qiantaobao** [comment]
同样的问题，请尽快修复吧，不然开发真的很不方便啊

**Comment by ycjcl868** [comment]
locale 问题已修复，升级到 2.8.19

**Comment by fishenal** [comment]
react-dom.development.js 里rename问题依然存在，warning，升级umi解决了locale问题，引入了rename的问题，我的react 明明是16
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ConnectedRouter, Redirect, Router, Switch

warning 报在 connectedRouter Redirect Router等组件内部


我的：
react": "^16.7.0",
    "react-dom": "^16.8.6",
    "umi": "^2.8.4",
    "umi-plugin-react": "^1.8.4",
    "umi-request": "^1.0.8"

**Comment by ycjcl868** [comment]
有些组件使用了将废弃的 react api，@chenshuai2144  cc

**Comment by chenshuai2144** [comment]
@ycjcl868  不是我们的，是第三方的，16 的时候我们已经清理过了。
社区需要反应一段时间

**Comment by farzer** [comment]
marked

**Comment by afc163** [comment]
Fixed in lastest umi version.

**Comment by Lind-pro** [comment]
> Fixed in lastest umi version.

今天使用了umi 2.8.20 还是有这一堆警告哎。。我看了看了2.8.20是最后一个版本啊
![image](https://user-images.githubusercontent.com/18098618/64013743-1796e580-cb53-11e9-94af-1f6dbe8f2f6e.png)

**Comment by wangxingkang** [comment]
react 的警告

**Comment by ShawDanon** [comment]
react生命周期即将废弃的警告

**Comment by ruomanwei** [comment]
所以现在最新版本更新了就好了是吗

**Comment by wangxingkang** [comment]
试一下 不就行了  説是解决了

**Comment by lonelyant** [comment]
umi 2.9.3 版本warning依然存在

**Comment by wangxingkang** [comment]
升级下 ant-design 呢

**Comment by lonelyant** [comment]
> 升级下 ant-design 呢

```
antd: 3.23.1
umi: 2.9.3
```
依然存在

**Comment by ycjcl868** [comment]
`LocaleProvider` 的解决了，其它⚠️警告处理需要一步步来修掉。

**Comment by fishenal** [comment]
antd组件的报错，可以通过指定react和react-dom版本来解决，

```
"react": "16.8.6",
"react-dom": "16.8.6",
```

等antd4上线再改成可变版本吧

**Comment by lyihuan** [comment]
这种warning问题解决了吗？？？？

**Comment by tranducit95** [comment]
![Screenshot from 2019-10-23 08-42-03](https://user-images.githubusercontent.com/26267956/67349054-007fdd00-f571-11e9-80a7-dfbdb23f4a40.png)

**Comment by wangyinwei1** [comment]
哪个版本解决了？我也是一堆告警
