### ISSUE TITLE
EEXIST Error after run npx umi block add ListTableList --path=/list/table-list

### ISSUE THREAD

**Issue by youqingxiaozhua** [ant-design/ant-design-pro#5017]
I try to run `cnpm run fetch:blocks`, but it stuck at `user/login`.
I terminate it and continue run `npx umi block add ListTableList --path=/list/table-list`, but get error bellow:

![image](https://user-images.githubusercontent.com/15990586/62481707-c14db580-b7e5-11e9-9a48-c791ab0872f8.png)

**Comment by youqingxiaozhua** [comment]
After I delete ./pages folder, and it throws this:

```
RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)

```

**Comment by PaigeWw** [comment]
I have encountered the same error. And deleted the pages folder or reported the same error.How did you solve it?

**Comment by PaigeWw** [comment]
I copied the `npx umi block add ListTableList --path=/list/table-list` to execute
I try to use `npx umi block add ListTableList`
Then I succeeded, amazing!
