### ISSUE TITLE
开发环境怎么访问https api？

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#5021]
springboot开启https，证书用的是自签的，postman已经可以请求成功。 请问开发环境下怎么访问https的接口，proxy和requet怎么配？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/1185
试试

**Comment by huang714669** [comment]
已解决,多谢

**Comment by wangerwang** [comment]
麻烦问下怎么解决的；是这样配置吗https://github.com/umijs/umi/issues/1185#issuecomment-699898960

**Comment by wangerwang** [comment]
> 已解决,多谢



> 已解决,多谢

麻烦问下怎么解决的；是这样配置吗https://github.com/umijs/umi/issues/1185#issuecomment-699898960
