### ISSUE TITLE
v4 proxy 无效

### ISSUE THREAD

**Issue by bushadie** [ant-design/ant-design-pro#5022]
修改了 config\config.js 的 proxy 的内容,浏览器这边还是走的8000
`  proxy: {
    '/api': {
      target: 'http://localhost:8888/',
      changeOrigin: true,
    },
  },`
![Snipaste_2019-08-06_13-59-48](https://user-images.githubusercontent.com/28383091/62514683-87ff5f00-b852-11e9-80a8-caee38a5a8b4.png)

**Comment by xiaohuoni** [comment]
这个问题说过好多遍了吧。proxy代理的是服务，不是请求跳转。🙋‍♂️

**Comment by 3c** [comment]
我觉得还是说明白点更好，报错的都先用postman试一下你的target那部分，请求通过的话再用proxy

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
