### ISSUE TITLE
页面上的 title 怎么去掉？

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#5027]
![image](https://user-images.githubusercontent.com/51696361/62525236-9dcc4e80-b869-11e9-80a1-b605d1a6da09.png)
面包屑可以去掉，但是图上红框部分的title怎么去掉呢？
大佬帮帮忙

**Comment by Benpaodejiezai** [comment]
尴尬

**Comment by lonelyant** [comment]
在你需要隐藏title的页面中找到<PageHeaderWrapper>，为其加上title={false}

拿Welcome页面举例
```
export default (): React.ReactNode => (
  <PageHeaderWrapper title={false}>
    <p style={{ textAlign: 'center' }}>
      Want to add more pages? Please refer to{' '}
      <a href="https://pro.ant.design/docs/block-cn" target="_blank" rel="noopener noreferrer">
        use block
      </a>
      。
    </p>
  </PageHeaderWrapper>
);
```

另外，老哥顶部的标签页是咋弄的呀？

**Comment by Benpaodejiezai** [comment]
> 在你需要隐藏title的页面中找到`<PageHeaderWrapper>`，为其加上title={false}
> 
> 拿Welcome页面举例
> 
> ```
> export default (): React.ReactNode => (
>   <PageHeaderWrapper title={false}>
>     <p style={{ textAlign: 'center' }}>
>       Want to add more pages? Please refer to{' '}
>       <a href="https://pro.ant.design/docs/block-cn" target="_blank" rel="noopener noreferrer">
>         use block
>       </a>
>       。
>     </p>
>   </PageHeaderWrapper>
> );
> ```
> 
> 另外，老哥顶部的标签页是咋弄的呀？

![image](https://user-images.githubusercontent.com/51696361/62591891-b8530600-b903-11e9-816e-0764c655b11c.png)
谢谢了，但不明白为什么写 false 了，这个框还回留着。。。用 top: -55px  解决的
多tab页是我自己改的，写的挺烂的，需要可以分享跟你

**Comment by lonelyant** [comment]
我之前还以为是antd pro自带的，刚看了相关的issue好像官方不准备做这个功能。这个功能在我这也不是刚需，所以暂时不做了。

**Comment by xianbing98** [comment]
老哥，顶部标签可以分享下吗

**Comment by syouni** [comment]
import type { ProLayoutProps } from '@ant-design/pro-components';

/**
 * @name
 */
const Settings: ProLayoutProps & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  colorPrimary: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  title: 'Red-Panda',
  **pageTitleRender: false,**  ⇛加上这个
  pwa: true,
  logo: '/icons/keji.svg',
  iconfontUrl: '',
  token: {
    // 参见ts声明，demo 见文档，通过token 修改样式
    //https://procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F
  },
};

export default Settings;
