### ISSUE TITLE
npm run fetch:blocks这个命令是不能用了吗？

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#5028]
昨天使用这个命令的时候还可以下载，今天使用的时候一直卡在了install login  to...这里

**Comment by afc163** [comment]
@chenshuai2144 好像挺多人遇到了这个问题。

**Comment by neewbee** [comment]
如果 `/user/login` 模块存在 
`umi block add https://github.com/ant-design/pro-blocks/tree/master/UserLogin` 
命令会等待用户输入 
![image](https://user-images.githubusercontent.com/13777940/62550929-a9d20380-b89d-11e9-935f-156388cf4fed.png)

https://github.com/ant-design/ant-design-pro-cli/blob/5d3b44283ac027e9b28c04bc0bbb5f28493ae221/src/fetch-blocks/index.js#L131
会一直 pending

**Comment by fx109138** [comment]
这个找到什么原因了吗，很奇怪 @afc163 现在有什么解决方案吗

**Comment by chenshuai2144** [comment]
文件夹如果存在会将其直接删除
https://github.com/ant-design/ant-design-pro-cli/blob/5d3b44283ac027e9b28c04bc0bbb5f28493ae221/src/fetch-blocks/index.js#L110

**Comment by chenshuai2144** [comment]
更换了 execa ，callback 的行为有点区别了。
升级到了 @1.0.8 重新安装即可

**Comment by ityao** [comment]
> 更换了 execa ，callback 的行为有点区别了。
> 升级到了 @1.0.8 重新安装即可

说话别说一半阿, 直接说改package.json里面"@ant-design/pro-cli" 到1.0.8版本可好
