### ISSUE TITLE
mock文件内express缺少声明文件

### ISSUE THREAD

**Issue by perany** [ant-design/ant-design-pro#5029]
`import {Request, Response} from 'express';`
该行导致tslint报错：找不到express模块，需要手动安装@types/express
建议发pr

**Comment by chenshuai2144** [comment]
@perany 直接来个 pr 吧

**Comment by perany** [comment]
通过cli新建的项目没有，github-master上代码是有@types/express依赖的

**Comment by perany** [comment]
> @perany 直接来个 pr 吧

通过cli新建的项目没有，github-master上代码是有@types/express依赖的

**Comment by perany** [comment]
@chenshuai2144  发了，保留了对express依赖的忽略
