### ISSUE TITLE
create umi 步骤感觉不正常啊

### ISSUE THREAD

**Issue by BigHuiWolf** [ant-design/ant-design-pro#5030]
![image](https://user-images.githubusercontent.com/36195100/62592687-a58e0080-b906-11e9-84c4-86527ce0b526.png)
怎么没有让我选择JavaScript和typescript了？一直回车完毕就只剩下这个了？
![image](https://user-images.githubusercontent.com/36195100/62592768-f7cf2180-b906-11e9-940b-fdec0f0896ff.png)
怎么跟文档里展示的差那么多呢？
![image](https://user-images.githubusercontent.com/36195100/62592819-25b46600-b907-11e9-924d-78f9dd0871a6.png)

**Comment by afc163** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/507615/62592900-76c45a00-b907-11e9-901b-e2505f0057f0.png">

选错项目类型了。

**Comment by BigHuiWolf** [comment]
> <img alt="image" width="519" src="https://user-images.githubusercontent.com/507615/62592900-76c45a00-b907-11e9-901b-e2505f0057f0.png">
> 
> 选错项目类型了。

![image](https://user-images.githubusercontent.com/36195100/62593245-90b26c80-b908-11e9-82ed-b76341ca9967.png)

**Comment by afc163** [comment]
![](http://g.recordit.co/cqQfgjuNeX.gif)

**Comment by BigHuiWolf** [comment]
已解决。换成cmd就可以正常操作了。Git Bash命令行无法上下选中，即便默认antdPro回车也会出问题。

**Comment by afc163** [comment]
应该上 window terminal 了

**Comment by BigHuiWolf** [comment]
> 应该上 windows terminal 了。

一直用GitBash，不知道怎么会突然这样。
