### ISSUE TITLE
create umi 安装失败

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#5031]
```
🌈  Projects  yarn create umi
yarn create v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-umi@0.14.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? Which language do you want to use? TypeScript
> git clone https://github.com/ant-design/ant-design-pro --depth=1 /Users/afc163/Projects
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://github.com/ant-design/ant-design-pro --depth=1 /Users/afc163/Projects
fatal: destination path '/Users/afc163/Projects' already exists and is not an empty directory.


    at makeError (/Users/afc163/.config/yarn/global/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/afc163/.config/yarn/global/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by chenshuai2144** [comment]
你的文件夹不是一个空的文件夹，我们应该加个中文提示

**Comment by perany** [comment]
> 你的文件夹不是一个空的文件夹，我们应该加个中文提示

之前遇到过几次，猜到是这个意思了

**Comment by macmatilda** [comment]
我yarn umi create失败的概率 很大，npm umi create貌似从来没有失败过 ，踩雷爽死我 。。。。

**Comment by yangkang55** [comment]
我也是这种情况，我确认了文件夹就是空的啊，请问应该如何解决啊

**Comment by macmatilda** [comment]
npm 貌似都没有问题




------------------ 原始邮件 ------------------
发件人: "yangkang55"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 下午4:39
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "天使消失的街"<macmatilda@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] create umi 安装失败 (#5031)




我也是这种情况，我确认了文件夹就是空的啊，请问应该如何解决啊

**Comment by haomingi** [comment]
`:\code\demo>npm create umi
? Select the boilerplate type (Use arrow keys)
> ant-design-pro  - Create project with a layout-only ant-design-pro boilerplate
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
> git clone https://github.com/ant-design/ant-design-pro --depth=1 G:\code\demo
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at notFoundError (C:\Users\ming.g\AppData\Local\Yarn\Data\global\node_modu
les\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\ming.g\AppData\Local\Yarn\Data\global\node_modul
es\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\ming.g\AppData\Local\Yarn\Data\global\no
de_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\ming.g\AppData\Local\Yarn\Data\global\
node_modules\yeoman-generator\lib\index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`
直接安装umi是可以的。

**Comment by macmatilda** [comment]
呵呵，看来没有一定成功的步骤了


------------------ 原始邮件 ------------------
发件人: "haomingi"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 下午4:32
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "天使消失的街"<macmatilda@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] create umi 安装失败 (#5031)




`:\code\demo>npm create umi
 ? Select the boilerplate type (Use arrow keys)
  
ant-design-pro  - Create project with a layout-only ant-design-pro boilerplate
 ? Select the boilerplate type ant-design-pro
 ? Which language do you want to use? JavaScript
 git clone https://github.com/ant-design/ant-design-pro --depth=1 G:\code\demo
 events.js:174
 throw er; // Unhandled 'error' event
 ^
  
Error: spawn git ENOENT
 at notFoundError (C:\Users\ming.g\AppData\Local\Yarn\Data\global\node_modu
 les\cross-spawn\lib\enoent.js:6:26)
 at verifyENOENT (C:\Users\ming.g\AppData\Local\Yarn\Data\global\node_modul
 es\cross-spawn\lib\enoent.js:40:16)
 at ChildProcess.cp.emit (C:\Users\ming.g\AppData\Local\Yarn\Data\global\no
 de_modules\cross-spawn\lib\enoent.js:27:25)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
 Emitted 'error' event at:
 at Immediate.setImmediate (C:\Users\ming.g\AppData\Local\Yarn\Data\global
 node_modules\yeoman-generator\lib\index.js:436:22)
 at runCallback (timers.js:705:18)
 at tryOnImmediate (timers.js:676:5)
 at processImmediate (timers.js:658:5)`
 直接安装umi是可以的。

**Comment by chenqq86** [comment]
`PS F:\Work\2019\cms\client> npm create umi
npx: installed 511 in 149.411s
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
> git clone https://github.com/ant-design/ant-design-pro --depth=1 F:\Work\2019\cms\client
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at notFoundError (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\2056\node_modules\create-umi\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\2056\node_modules\create-umi\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\2056\node_modules\create-umi\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\Administrator\AppData\Roaming\npm-cache\_npx\2056\node_modules\create-umi\node_modules\yeoman-generator\lib\index.js:436:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

我这也是这样子的情况，在WIN系统下面有这个问题，在MAC下就正常了

**Comment by xiaoshui222** [comment]
> 我也是这种情况，我确认了文件夹就是空的啊，请问应该如何解决啊
我也是，请问你们怎么解决的

**Comment by xiaoshui222** [comment]
> 你的文件夹不是一个空的文件夹，我们应该加个中文提示
我确定文件夹是空的啊，就是安装不了，怎么解

**Comment by yangkang55** [comment]
很尴尬，我 ls -a发现文件夹不是空的，有个.idea，删了就好了

**Comment by yoyo837** [comment]
点(.)开头的文件和文件夹在Mac下Finder默认不可见

**Comment by chengzequn** [comment]
这个问题怎么关了，似乎没有解决吧

PS E:\antdesign-workspace\antdesignpro(ts)> yarn create umi
yarn create v1.22.4
[1/4] Resolving packages...
warning create-umi > sylvanas > @umijs/fabric > stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning create-umi > sylvanas > @umijs/fabric > stylelint-config-rational-order > stylelint > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning create-umi > sylvanas > @umijs/fabric > stylelint-config-rational-order > stylelint > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
[4/4] Building fresh packages...
success Installed "create-umi@0.21.2" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🚀 Do you need all the blocks or a simple scaffold? complete
> 🙈 complete mode can only use the version of antd@4
fatal: destination path 'E:\antdesign-workspace\antdesignpro(ts)' already exists and is not an empty directory.
✨ File Generate Done
Done in 143.04s.

**Comment by gpzjyw** [comment]
操作系统：macOS；node：v8.16.2；npm：6.4.1。
文件夹下是空的，`npm create umi`依然会报错：
![image](https://user-images.githubusercontent.com/13843807/79042548-4f0e5a00-7c2b-11ea-9f1b-8f5c23537cad.png)

**Comment by yujingxiacai** [comment]
> 操作系统：macOS；节点：v8.16.2； npm：6.4.1。
> 文件夹下是空的，`npm create umi`依然会报错，文件`.yo-repository`是创建失败后出现的：
> ![图片](https://user-images.githubusercontent.com/13843807/79042548-4f0e5a00-7c2b-11ea-9f1b-8f5c23537cad.png)
同样的问题在[issue](https://github.com/ant-design/ant-design-pro/issues/6363#issue-598229399)中好像有一个解决办法

**Comment by gpzjyw** [comment]
> > 操作系统：macOS；节点：v8.16.2； npm：6.4.1。
> > 文件夹下是空的，`npm create umi`依然会报错，文件`.yo-repository`是创建失败后出现的：
> > ![图片](https://user-images.githubusercontent.com/13843807/79042548-4f0e5a00-7c2b-11ea-9f1b-8f5c23537cad.png)
> > 同样的问题在[issue](https://github.com/ant-design/ant-design-pro/issues/6363#issue-598229399)中好像有一个解决办法

后来采用了如下方法解决：
1. 到需要新建工程的目录下（不要新建空目录）；
2. 直接采用`npm create umi xxx(工程目录名)`新建工程。

**Comment by CandyQiu** [comment]
> > > 操作系统：macOS；节点：v8.16.2； npm：6.4.1。
> > > 文件夹下是空的，`npm create umi`依然会报错，文件`.yo-repository`是创建失败后出现的：
> > > ![图片](https://user-images.githubusercontent.com/13843807/79042548-4f0e5a00-7c2b-11ea-9f1b-8f5c23537cad.png)
> > > 同样的问题在[issue](https://github.com/ant-design/ant-design-pro/issues/6363#issue-598229399)中好像有一个解决办法
> 
> 后来采用了如下方法解决：
> 
> 1. 到需要新建工程的目录下（不要新建空目录）；
> 2. 直接采用`npm create umi xxx(工程目录名)`新建工程。

**Comment by CandyQiu** [comment]
> > > 操作系统：macOS；节点：v8.16.2； npm：6.4.1。
> > > 文件夹下是空的，`npm create umi`依然会报错，文件`.yo-repository`是创建失败后出现的：
> > > ![图片](https://user-images.githubusercontent.com/13843807/79042548-4f0e5a00-7c2b-11ea-9f1b-8f5c23537cad.png)
> > > 同样的问题在[issue](https://github.com/ant-design/ant-design-pro/issues/6363#issue-598229399)中好像有一个解决办法
> 
> 后来采用了如下方法解决：
> 
> 1. 到需要新建工程的目录下（不要新建空目录）；
> 2. 直接采用`npm create umi xxx(工程目录名)`新建工程。

用这个方法可以了哎~赞~

**Comment by DarrenPei** [comment]
> `:\code\demo>npm create umi
> ? Select the boilerplate type (Use arrow keys)
> 
> > ant-design-pro  - Create project with a layout-only ant-design-pro boilerplate
> > ? Select the boilerplate type ant-design-pro
> > ? Which language do you want to use? JavaScript
> > git clone https://github.com/ant-design/ant-design-pro --depth=1 G:\code\demo
> > events.js:174
> > throw er; // Unhandled 'error' event
> > ^
> 
> Error: spawn git ENOENT
> at notFoundError (C:\Users\ming.g\AppData\Local\Yarn\Data\global\node_modu
> les\cross-spawn\lib\enoent.js:6:26)
> at verifyENOENT (C:\Users\ming.g\AppData\Local\Yarn\Data\global\node_modul
> es\cross-spawn\lib\enoent.js:40:16)
> at ChildProcess.cp.emit (C:\Users\ming.g\AppData\Local\Yarn\Data\global\no
> de_modules\cross-spawn\lib\enoent.js:27:25)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> Emitted 'error' event at:
> at Immediate.setImmediate (C:\Users\ming.g\AppData\Local\Yarn\Data\global
> node_modules\yeoman-generator\lib\index.js:436:22)
> at runCallback (timers.js:705:18)


Windows10下报Error: spawn git ENOENT，解决方法：在环境变量的path里加上“C:\Program Files\Git\bin”就可以了，路径根据你的git安装目录做调整。
