### ISSUE TITLE
Standard Table隐藏tooltip（alert）

### ISSUE THREAD

**Issue by boylych** [ant-design/ant-design-pro#5032]
antd pro的Sample（查询表格）例中Standard Table自带的提示框（显示选中n项）能否关闭？怎么关闭？谢谢

**Comment by chenshuai2144** [comment]
直接修改代码。
https://github.com/ant-design/pro-blocks/blob/d41ef51a3b544b1fa28788199d2235beafb48263/ListTableList/src/components/StandardTable/index.tsx#L127
