### ISSUE TITLE
npm run fetch:blocks 除了 login 什么都拉不下来。

### ISSUE THREAD

**Issue by charliezzo** [ant-design/ant-design-pro#5034]
#npm run fetch:blocks 除了 login 什么都拉不下来。

看了所有npm run fetch:blocks 的issues 还是没有什么卵用。翻墙也不行。
即使是他显示这样了
√ 📦  install analysis  to: /dashboard/analysis
还是没拉下来

##win10
##node 10.16.0
##antd pro 是直接 git clone 的，npm create umi 的也试过了

**Comment by charliezzo** [comment]
有没有包含所有模块的仓库，还是全下下来删掉没用的页面方便。

**Comment by ityao** [comment]
mac也一样, 不只是window的问题
