### ISSUE TITLE
分页问题，我需要怎么设置，分页才出来，可以正常翻页

### ISSUE THREAD

**Issue by hejinhua33** [ant-design/ant-design-pro#5036]
![image](https://user-images.githubusercontent.com/44763470/62666618-b7c77780-b9b6-11e9-9a4f-b0b381ee0151.png)
这是我的数据结构

**Comment by zewei1022** [comment]
可以参考list下面的table-list

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#pagination

看这里你需要配置一下
