### ISSUE TITLE
config.js引入图片错误

### ISSUE THREAD

**Issue by qingming418** [ant-design/ant-design-pro#5037]
在项目的配置文件config.js中， 如果 import icon from '../src/assets/favicon.png';
那么启动的时候会报错。
![image](https://user-images.githubusercontent.com/20061205/62672992-4b0ca700-b9cf-11e9-9623-57eebfd12bb8.png)
有没有办法可以引入图片，编译会自动转换为base64，我要配置到context中

**Comment by chenshuai2144** [comment]
这个里面是node，不建议你设置图片，你可以直接配置 url
