### ISSUE TITLE
面包屑少了一层

### ISSUE THREAD

**Issue by ityao** [ant-design/ant-design-pro#504]
用今天更新的最新的代码编译后发现面包屑少了一层

看了下代码, 逻辑有问题, 用common/router的routerDataWithName来判断面包屑, 就没有了左侧菜单的层次关系了, 导致现在面包屑都是直接 "首页/具体页面"

**Comment by chenshuai2144** [comment]
就是这么设计的. 菜单和面包屑并不是一一对应的.
需要在考虑一下..

**Comment by ddcat1115** [comment]
最新的面包屑只会包含可点的层级，原不可点的层级被去掉了，面包屑跟菜单没有直接关系，跟路由挂钩

**Comment by chenshuai2144** [comment]
搜索列表得问题也放在这里把. 修好了 顺便关掉这个问题.

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34354510-bc5802c4-ea69-11e7-9cd1-6c73c62c7962.png)
问题描述

**Comment by chenshuai2144** [comment]
#507 中已经修复
