### ISSUE TITLE
ant design pro官网在firefox中加载极度缓慢

### ISSUE THREAD

**Issue by liutianzeng** [ant-design/ant-design-pro#5041]
官网在chrome中加载正常，但是在firefox中基本加载不出来，估计是官网那个svg矢量图的问题，请问是firefox对svg图的处理算法问题吗?还是svg图本身的问题
![image](https://user-images.githubusercontent.com/43633459/62708619-5a6b0f00-ba26-11e9-828d-afa173574415.png)

**Comment by afc163** [comment]
我也遇到一样的问题。

@jljsj33

**Comment by jljsj33** [comment]
不科学啊，，ant design 能加载啊，，都是用的 svg

**Comment by jljsj33** [comment]
firefox 对 svg 的支持也太差了吧。。。。

**Comment by jljsj33** [comment]
以前好像没有这问题的啊，，

**Comment by liutianzeng** [comment]
> 以前好像没有这问题的啊，，

我看了一下ant design的官网，他的图标主要是以插入image元素为主，并不是全都用svg写的，而ant design pro的图标则都是使用svg写的，而且其中包含了很多path元素，对渲染性能要求比较高，所以firefox一直处于卡顿状态
![image](https://user-images.githubusercontent.com/43633459/62758198-3f44e180-bab0-11e9-8cfa-68f60f047db5.png)

**Comment by afc163** [comment]
看上去是动画的兼容性问题。

**Comment by liutianzeng** [comment]
> 看上去是动画的兼容性问题。

但是ant design官网的svg动画支持良好，我感觉是不是pro官网的这个svg图用了过多的path，再加上firefox对svg的处理算法不是很好，导致渲染很慢

**Comment by afc163** [comment]
原来一直是好的，不知道哪个时间点变成这样了。

**Comment by liutianzeng** [comment]
> 原来一直是好的，不知道哪个时间点变成这样了。

我对比了这两个图，发现ant design的图是使用了大量的image元素位图，而Pro的svg图都是svg绘制的。
![image](https://user-images.githubusercontent.com/43633459/62920202-99f37b80-bdd7-11e9-8f98-6689b831f530.png)

**Comment by jljsj33** [comment]
firefox 的 svg 渲染问题，，firefox 一直对 svg 的支持就很不乐观，总会有奇怪的东西出现。。。空了再看，，不影响。。。

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-icons v4 将会迎来一大波svg
@HeskeyBaozi

**Comment by afc163** [comment]
目测现在好了？

**Comment by chenshuai2144** [comment]
看起来没问题了
