### ISSUE TITLE
运行 yarn fetch:blocks,无法下载区块

### ISSUE THREAD

**Issue by monoshizuka** [ant-design/ant-design-pro#5042]
下载了十几次了,有时候会在login卡住,有时候会在analysis卡住,一直无法运行.有没有完整的项目地址啊.这样弄真的很难受
![TIM图片20190809103447](https://user-images.githubusercontent.com/26546536/62750142-94bdc600-ba91-11e9-85d8-75f384c81cc2.png)

**Comment by ityao** [comment]
同感, 而且好像还没人管

**Comment by kidneyleung** [comment]
![image](https://user-images.githubusercontent.com/32615691/62760693-30adf880-bab7-11e9-8bb3-7dd7724a4951.png)

**Comment by afc163** [comment]
没有装 git

**Comment by monoshizuka** [comment]
> 没有装git？
肯定装了的啊,感觉是umi这个依赖的问题

**Comment by chenshuai2144** [comment]
@monoshizuka  看你的输出需要更新一下包了

**Comment by lengthmin** [comment]
忘记在哪个 issue 里看到了解释，是因为下载每个区块都要安装 package.json, but 没有输出，所以慢是真的，不一定是卡住了。

我自己第一次也以为是卡住了。后来看了解释之后，设置好代理，慢慢等它，果然安装好了。

**Comment by chenshuai2144** [comment]
可以打开 debug，能缓解等待的焦虑

https://github.com/ant-design/ant-design-pro-cli#debug

**Comment by sunxinGitHub** [comment]
https://pan.baidu.com/s/1sVmY36iKzQS-YrORyHwEog

提取码 n6fu

这个版本时js版本的（非ts版）， 有需要的可以下载

**Comment by xuqplus** [comment]
可以把https://github.com/ant-design/pro-blocks 源码克隆到本地再安装, 本人亲测, 会快很多...

大概会用到这么个命令, 一下子安装所有的 blocks 到你的项目里
`ls /d/work3/pro-blocks-master/ | grep / | xargs -I {} umi block add /d/work3/pro-blocks-master/{}`

详细的过程可以参考 -> https://blog.csdn.net/u011089766/article/details/98032413 本人写的, 逃)

**Comment by chenshuai2144** [comment]
试试最新的 umi。https://github.com/umijs/umi/releases/tag/umi%402.8.20
加了码云来优化下载速度。
