### ISSUE TITLE
npm create umi创建的项目1.0.0 怎么升级？

### ISSUE THREAD

**Issue by RoinBi** [ant-design/ant-design-pro#5044]
![image](https://user-images.githubusercontent.com/26728164/62820821-a344d400-bb9c-11e9-9436-4213387d7aa9.png)

**Comment by lengthmin** [comment]
这是个很小白的问题。自己开发项目里的 package.json 是自己控制的，想改啥就改啥。
这个版本好和 ant design 目前的版本号没有任何关系。

**Comment by RoinBi** [comment]
> 这是个很小白的问题。自己开发项目里的 package.json 是自己控制的，想改啥就改啥。
> 这个版本号和 ant design 目前的版本号没有任何关系。
好的，谢了。第一次使用前端

**Comment by RoinBi** [comment]
> 这是个很小白的问题。自己开发项目里的 package.json 是自己控制的，想改啥就改啥。
> 这个版本号和 ant design 目前的版本号没有任何关系。

好的谢了，第一次使用前端
