### ISSUE TITLE
在config.js中的define下配置的变量eslint 报error undefined

### ISSUE THREAD

**Issue by greateidea** [ant-design/ant-design-pro#5045]
在config.js中的define下的配置
  define: {
    API_PREFIX: ...,
    EMPTY_TEXT: '空',
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION:
      ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION || '', // preview.pro.ant.design only do not use in your production ; preview.pro.ant.design 专用环境变量，请不要在你的项目中使用它。
  },

使用antd design组件：
‘’<Table
    locale={{ emptyText: 'there is no data' }}
     ...
 />‘’

API_PREFIX，EMPTY_TEXT这两个可以正常使用，
但git commit 的时候eslint只报EMPTY_TEXT的错误
error    'EMPTY_TEXT' is not defined          no-undef

**Comment by chenshuai2144** [comment]
在 eslint 中配置 globals
https://github.com/ant-design/ant-design-pro/blob/01547563518588ed7599ebd3643c99269651dcef/.eslintrc.js#L5
