### ISSUE TITLE
v4 关于设置requset的url中host问题

### ISSUE THREAD

**Issue by SuFIND** [ant-design/ant-design-pro#5047]
没有使用mock加载url配置了config/config.ts里面proxy，除了菜单路由只修改了这部分
```
config/config.ts
proxy: {
    '/api/v1/': {
      target: 'http://localhost:5000',
      changeOrigin: true,
      pathRewrite: { '^/api/v1/': '/api/v1/' },
    },
 ```
但是修改对localhost的port的没有效果，如图

![image](https://user-images.githubusercontent.com/30424839/62821926-10f9fb80-bbaf-11e9-909c-1826ab06b1fd.png)
请问我改如何修改呢

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5022
