### ISSUE TITLE
怎么用redux-persist做持久化存储？

### ISSUE THREAD

**Issue by 310731483** [ant-design/ant-design-pro#505]
这里应该怎么用redux-persist做持久化存储？或者有其它什么方法可以实现？现在登录后返回的数据刷新就没有了。。

**Comment by afc163** [comment]
https://github.com/dvajs/dva/blob/67a63c3d421671b074014478ae25ef20e28aa2a5/docs/API_zh-CN.md#extraenhancers

**Comment by kunhour** [comment]
我用的是localStorage，可能不是很优雅，功能可以实现。
