### ISSUE TITLE
当config.ts配置路由为可选值的时候,路由不正确

### ISSUE THREAD

**Issue by 544751779** [ant-design/ant-design-pro#5050]
路由配置 
path: '/chance/list/:scene?',
在左侧的菜单会产生如下url
http://localhost:8000/chance/list/:scene?
期望获得url
http://localhost:8000/chance/list/

**Comment by chenshuai2144** [comment]
菜单现在并不支持参数模式，有想法可以搞个 pr 出来。
现在人力过于紧张。

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
