### ISSUE TITLE
我登录之后获取到的token值，怎么样才能让所有接口全局使用？？

### ISSUE THREAD

**Issue by hejinhua33** [ant-design/ant-design-pro#5053]

**Comment by xiaopanghhh** [comment]
在 utils 下面的 request.js 文件当中。
加入
![image](https://user-images.githubusercontent.com/24469601/62841672-9aa7e700-bcdd-11e9-86bb-df48a01c930b.png)

**Comment by hejinhua33** [comment]
> 在utils下面的request.js文件当中。
> 加入
> ![图片](https://user-images.githubusercontent.com/24469601/62841672-9aa7e700-bcdd-11e9-86bb-df48a01c930b.png)

我用的是.ts格式的，现在是照你一样写就可以了吗？
![image](https://user-images.githubusercontent.com/44763470/62841807-cc6d7d80-bcde-11e9-9ded-b703cddaafa7.png)这个也一样设置吗？

**Comment by xiaopanghhh** [comment]
同理，TS 也可以用。

**Comment by chenshuai2144** [comment]
楼上正解
