### ISSUE TITLE
hooks无法执行pre-commit

### ISSUE THREAD

**Issue by pppppppppppp12** [ant-design/ant-design-pro#5054]
新构建的项目，hooks无法执行pre-commit

在npm run lint-staged检测报错的情况下，git commit没有执行pre-commit钩子，直接提交成功。
应该是在lint-staged检测报错的情况下，commit也会报错。

设备条件：mac系统，create umi最新版本。

![image](https://user-images.githubusercontent.com/13028524/62843416-3f312580-bcec-11e9-86b1-e2df2fab73db.png)

**Comment by zhongjiewu** [comment]
可以查看 `.git/hooks/pre-commit` 文件验证hook是否存在。不存在的话可以重新安装husky
`cnpm install husky`

**Comment by zhongjiewu** [comment]
看到以下内容应该就好了
![image](https://user-images.githubusercontent.com/1766793/62846494-2aac5780-bd03-11e9-8ffb-ae74b5b7be62.png)

**Comment by pppppppppppp12** [comment]
![image](https://user-images.githubusercontent.com/13028524/67840315-8d5a0600-fb30-11e9-829a-ae18fe373ec9.png)
谢谢。找到原因了，husky要求git版本在2.13.0以上，git版本过低会导致husky设置git hooks失败，上图为报错信息。
解决方法：升级git版本，重新执行cnpm install husky。
![image](https://user-images.githubusercontent.com/13028524/67841826-e0818800-fb33-11e9-976e-117dcc08c74d.png)

**Comment by lala2333** [comment]
卸载husky，把yarn.lock或者package.json.lock删掉

**Comment by jokereven** [comment]
in antd pro defalult it's have the husky, but no to use, i have try npm install husky then i can use the husky.

**Comment by lk0606** [comment]
> ![image](https://user-images.githubusercontent.com/13028524/67842041-5b4aa300-fb34-11e9-81b2-3b8cd26889f9.png) 谢谢。找到原因了，husky要求git版本在2.13.0以上，git版本过低会导致husky设置git hooks失败，上图为报错信息。 解决方法：升级git版本，重新执行cnpm install husky。 ![image](https://user-images.githubusercontent.com/13028524/67842285-d57b2780-fb34-11e9-8444-ef51fbbd5fbc.png)

我的git版本，2.20.1，还是不成功，请问是什么原因呀。 @zhongjiewu 
![image](https://github.com/ant-design/ant-design-pro/assets/43233310/3dc3a00b-7247-42db-847f-77798b3803d0)

**Comment by lk0606** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/43233310/ba75ac8d-13d1-48d9-87cd-f6d521d8244b)
![image](https://github.com/ant-design/ant-design-pro/assets/43233310/fe82c61c-4ee6-4059-93a5-5554edce3d1d)
我的git版本，2.20.1，还是不成功，请问是什么原因呀。 @zhongjiewu
