### ISSUE TITLE
文档关于模型的地方，建议链接umi的模型文档

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-pro#5055]
对于完全没有接触过umi的新人，怎么可能知道默认的模型是model？全局的模型如何共享之类？
看了umi的文档才弄清楚。

**Comment by afc163** [comment]
来个 PR 如何

**Comment by macmatilda** [comment]
> 来个 PR 如何

ok

**Comment by macmatilda** [comment]
建议文档采用wiki方式，大家都可以修改，应该很容易改的比较清楚

**Comment by afc163** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/507615/62847911-74993b80-bd0b-11e9-9703-6ae2ac63afe8.png">

**Comment by macmatilda** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "偏右"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 下午2:14
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "天使消失的街"<macmatilda@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] 文档关于模型的地方，建议链接umi的模型文档 (#5055)
