### ISSUE TITLE
https://preview.pro.ant.design 的源码有没有开源? 只找到v1, v2, 没看见v4的

### ISSUE THREAD

**Issue by xuqplus** [ant-design/ant-design-pro#5064]
https://preview.pro.ant.design 的源码有没有开源? 只找到v1, v2, 没看见v4的

**Comment by afc163** [comment]
就是这个仓库。

**Comment by xuqplus** [comment]
谢谢回复  
是这样, 之前我把当前仓库的源码clone下来, yarn && yarn start, 能看到的只有welcome页面
而实际上 https://preview.pro.ant.design 的外观跟 v2 是一致的
所以说preview编译打包部署中还有其他流程, 比如将 pro-blocks 都加入进来对吧

**Comment by afc163** [comment]
https://zhuanlan.zhihu.com/p/67498559
