### ISSUE TITLE
动态菜单国际化问题，已查阅过之前issues

### ISSUE THREAD

**Issue by lonelyant** [ant-design/ant-design-pro#5065]
按照官网建议的动态菜单解决方案进行后，菜单无法国际化。之前的issues都翻过了，还是没有找到相对应的解答，希望大佬们能大概讲一下实现思路（后台多语言方案除外），谢谢！

**Comment by xuqplus** [comment]
我是用的脚手架, 里面已经实现了, 用formatMessage方法和FormattedMessage 标签, 再往locale目录下加翻译就好了...
```js
import { formatMessage, FormattedMessage } from 'umi-plugin-react/locale'

...
{ formatMessage({ id: 'user.register.captcha.errorMessage' }) }

<FormattedMessage id={'user.register.toLogin'}/>&gt;&gt;
```
```ts
export default {
  'user.register.captcha.errorMessage': '请输入图形验证码',
}
```

**Comment by LeeeoZhang** [comment]
+1

**Comment by lonelyant** [comment]
> 我是用的脚手架, 里面已经实现了, 用formatMessage方法和FormattedMessage 标签, 再往locale目录下加翻译就好了...
> 
> ```js
> import { formatMessage, FormattedMessage } from 'umi-plugin-react/locale'
> 
> ...
> { formatMessage({ id: 'user.register.captcha.errorMessage' }) }
> 
> <FormattedMessage id={'user.register.toLogin'}/>&gt;&gt;
> ```
> 
> ```ts
> export default {
>   'user.register.captcha.errorMessage': '请输入图形验证码',
> }
> ```

首先感谢回答哈。不过官方给出的动态菜单解决方案是向后台请求菜单，之后在`BasicLayout`组件里面将`menuDataRender`替换掉。

[从服务器请求菜单](https://pro.ant.design/docs/router-and-nav-cn#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95)

我想知道的是在这种情况下怎么做到国际化。

**Comment by pl2476** [comment]
![image](https://user-images.githubusercontent.com/20450069/63424345-c98e2d80-c440-11e9-9454-414b25acef7b.png)
可以暂时类似像上面这样处理，当然需要层级的还需要递归格式化。
但是这个功能我觉得应该在layout组件做，因为layout组件有这个功能为什么没有对menuData做处理，这点还得看源码  
希望layout组件能支持，或者本身可以而文档需要补充一下，麻烦关注看一下，谢谢 @chenshuai2144
