### ISSUE TITLE
model中effects函数用dispatch调用执行不了？需要做些什么配置？

### ISSUE THREAD

**Issue by lddlww** [ant-design/ant-design-pro#5066]
如下：
#model.ts文件中：
const Model: ModelType = {
    namesapce: 'platform',
    state: {
        merge: {
            ok: false,
            code: 200,
            error: "",
            data: [],
        },
    },

    effects: {
        *merge({ payload }, { call, put }) {
            console.log("in fetchMerge")
            const response = yield call(getMergeApi, payload);
            console.log(response)
            yield put({
                type: "getMerge",
                payload: response,
            });
        },
    },

    reducers: {
        getMerge(state, action) {
            return {
                ...state,
                merge: action.payload,
            };
        },
    }
}

export default Model

#table.tsx文件中调用：
public componentDidMount(){
         dispatch({
            type:'platform/merge',
            payload:{
                dbtype:this.props.dbtype,
                page:1,
            },
        });
    }

console.log一直没有输出任何东西

注：table.tsx和model.ts文件是同一目录

**Comment by lddlww** [comment]
重新启动也不行

**Comment by lddlww** [comment]
我放在全局的src/models目录下就可以执行

**Comment by LeoWang1991** [comment]
当前目录只能调当前目录下的models吧，你是不是跨目录调用了

**Comment by lddlww** [comment]
@LeoWang1991  model.ts和组件是在同一目录下

**Comment by aprilyzl0405** [comment]
model.ts放到同级目录的models文件夹下试试？

**Comment by lddlww** [comment]
@aprilyzl0405  放在上级的models目录下并且namespace必须和文件名称相同，才能够识别到；
如目录：
src/pages/platform/mysql（组件目录）
src/pages/platform/models/db.ts  此时db.ts中namespace必须为db；才能够被识别到 

像其他model.ts直接放在mysql目录下，一直识别不到，即使namespace为mysql也不行；

**Comment by lddlww** [comment]
还有一点就是不能在src/pages/platform/mysql组件目录下有model.ts文件，不然也会识别不到，即使放在上层models目录下也不行，

**Comment by chenshuai2144** [comment]
如果多个页面公用的model 建议放到 src/models 不然不能保证一定会加载
