### ISSUE TITLE
npm run fetch:blocks能下载js版本的吗

### ISSUE THREAD

**Issue by chengmings** [ant-design/ant-design-pro#5067]
npm run fetch:blocks能下载js版本的吗？为什么我下载的是ts版本的

**Comment by chenshuai2144** [comment]
npm run fetch:blocks 是为了部署官方网站而添加，只支持标准的，如果要使用 js 可以使用 umi block list，或者通过 v2 分支来查看demo

**Comment by sunxinGitHub** [comment]
在初始化工程的时候选择JavaScript版本后，npm run fetch:blocks 就是js版本， 另外在使用block命令单独添加块时可以这样：npx umi block add UserLogin --js --path=/user/login

**Comment by chengmings** [comment]
> npm run fetch:blocks 是为了部署官方网站而添加，只支持标准的，如果要使用 js 可以使用 umi block list，或者通过 v2 分支来查看demo

我用umi bolick list 报这个错load all locale file and build ts ×  error     TypeError: Cannot read property 'map' of undefined  然后load all locale file and build ts在这里一直转 就是下载不下载全部

**Comment by chengmings** [comment]
> 在初始化工程的时候选择JavaScript版本后，npm run fetch:blocks 就是js版本， 另外在使用block命令单独添加块时可以这样：npx umi block add UserLogin --js --path=/user/login

我及得我吃实话就是js版本的 然后全部下载的确实TS的 你说的初始化是npm creat umi的时候选择的吗  我再试试

**Comment by chenshuai2144** [comment]
fetch:blocks  不支持配置 js 还是 ts 的。

**Comment by chengmings** [comment]
> fetch:blocks 不支持配置 js 还是 ts 的。只会根绝 config.js 做判断

嗯嗯  我现在就是我弄了一个空的  umi block list 下载的时候都会报错  很纳闷

**Comment by sunxinGitHub** [comment]
我使用 npm run fetch:blocks  的方式就可以下载js版本， 我把代码分享给大家，有需要的直接下载吧， 使用npm run fetch:blocks的方式速度也很慢。
[https://pan.baidu.com/s/1sVmY36iKzQS-YrORyHwEog](url)
提取码: n6fu

**Comment by sunxinGitHub** [comment]
> > fetch:blocks 不支持配置 js 还是 ts 的。只会根绝 config.js 做判断
> 
> 嗯嗯 我现在就是我弄了一个空的 umi block list 下载有的js版本都会报错 很纳闷 比如说工作台里面的第三个

我上传的js版本的demo到百度网盘，有需要你可以去下载
