### ISSUE TITLE
最新版本Bug  侧边栏Memu点击无法展开

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#5068]
![image](https://user-images.githubusercontent.com/44694221/62887284-83b1d500-bd6f-11e9-9aea-dd7f4f605424.png)
![image](https://user-images.githubusercontent.com/44694221/62887322-93c9b480-bd6f-11e9-8785-51c319538e51.png)

**Comment by keke122765** [comment]
cnpm i @ant-design/pro-layout@4.5.13 --save 这个版本有问题
cnpm i @ant-design/pro-layout@4.5.12 --save 这个版本没问题

**Comment by misumisery** [comment]
我这也是，新版本确实有这个问题

**Comment by chenshuai2144** [comment]
close by  https://github.com/ant-design/ant-design-pro-layout/commit/3b8e544a2ac00f4d5c31dfd1b0f7408f798f5cf8
