### ISSUE TITLE
ant-design-pro怎么实现嵌套表格

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/ant-design-pro#5069]
ant-design-pro怎么实现嵌套表格？请告知，感谢
效果如截图所示：
![折叠表格](https://user-images.githubusercontent.com/3403476/62908569-3eab9400-bdab-11e9-9b66-fff811c86718.png)

**Comment by pl2476** [comment]
ant-design table组件就支持啊 @ssyangtian
