### ISSUE TITLE
左上的logo跳转在服务器非根路径部署时跳转出错

### ISSUE THREAD

**Issue by elenva** [ant-design/ant-design-pro#5073]
左上的logo在点击后，如果在服务器根目录部署的话没有问题，一旦不在根目录部署就会跳转不正确

**Comment by elenva** [comment]
目前也暂未发现可配置的地方

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout#prolayout

menuHeaderRender 可以解决你的问题

**Comment by elenva** [comment]
> https://github.com/ant-design/ant-design-pro-layout#prolayout
> 
> menuHeaderRender 可以解决你的问题

万分感谢，问题已经解决
