### ISSUE TITLE
v4.5.12 样式加载问题

### ISSUE THREAD

**Issue by wukongnalizou** [ant-design/ant-design-pro#5074]
![0676bf4ff32380329ce888f940ca240](https://user-images.githubusercontent.com/37323494/62925691-79cab900-bde5-11e9-8153-67f84865bc23.png)
![9a00ca8fe124c33a6aebc93e3ab61e6](https://user-images.githubusercontent.com/37323494/62925693-7afbe600-bde5-11e9-984d-43978be6ebe6.png)

**Comment by wukongnalizou** [comment]
是不同的处理方案么

**Comment by wangxingkang** [comment]
这个是ant-design-pro 写了插件自己处理的 
你可以根据自己的需求写个插件就好

**Comment by wangxingkang** [comment]
cssLoaderOptions: {
    modules: true,
    getLocalIdent: (
      context: {
        resourcePath: string;
      },
      _: string,
      localName: string,
    ) => {
      if (
        context.resourcePath.includes('node_modules') ||
        context.resourcePath.includes('ant.design.pro.less') ||
        context.resourcePath.includes('global.less')
      ) {
        return localName;
      }

      const match = context.resourcePath.match(/src(.*)/);

      if (match && match[1]) {
        const antdProPath = match[1].replace('.less', '');
        const arr = slash(antdProPath)
          .split('/')
          .map((a: string) => a.replace(/([A-Z])/g, '-$1'))
          .map((a: string) => a.toLowerCase());
        return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
      }

      return localName;
    },
  },

**Comment by wukongnalizou** [comment]
thanks
