### ISSUE TITLE
IE11 报错

### ISSUE THREAD

**Issue by guhuangjin** [ant-design/ant-design-pro#5077]
ant-design-pro 版本： "2.3.1"

问题描述：build之后，本地部署测试。发现ie11报错，如下图。现在不知道该怎么排查错误，求大佬帮忙啊
![TIM截图20190813173515](https://user-images.githubusercontent.com/33539824/62931726-69204000-bdf1-11e9-919d-7aa88205ae17.png)

**Comment by wangxingkang** [comment]
设置targets: { ie: 9 } 试一试

**Comment by guhuangjin** [comment]
设置targets: { ie: 9 }  没有效果 一样的错误

**Comment by guhuangjin** [comment]
新拉取的 2.3.1 版本的代码 build后 也在不断报错

![企业微信截图_15658314998763](https://user-images.githubusercontent.com/33539824/63066486-edcba500-bf3c-11e9-8e1b-fbd56b73645a.png)

**Comment by wangxingkang** [comment]
这是请求接口报错啊

**Comment by wangxingkang** [comment]
@guhuangjin 你试一下 我这个项目会在IE11下报错吗 https://github.com/ts-react/react-admin-template 我这没win

**Comment by guhuangjin** [comment]
@wangxingkang  你给的项目报了请求失败的错误  
![image](https://user-images.githubusercontent.com/33539824/63074121-70189100-bf5e-11e9-8e74-ed0b8a6d2235.png)

**Comment by wangxingkang** [comment]
那你在本地跑下吧  这个接口 在线上有问题

**Comment by guhuangjin** [comment]
@wangxingkang yarn start 后 ie11访问报如下截图错误

![TIM截图20190815135343](https://user-images.githubusercontent.com/33539824/63075687-12d40e00-bf65-11e9-96c5-bbe84e36ed61.png)

安装模块时会报模块依赖的warning 不知道和ie11报错有没有关联
![TIM截图20190815135808](https://user-images.githubusercontent.com/33539824/63075943-f2f11a00-bf65-11e9-8acd-c9b6ffdc62e1.png)

**Comment by wangxingkang** [comment]
无关 警告可忽略

**Comment by guhuangjin** [comment]
我最后是这样修复的：
拉取v2.3.1的新代码，然后自己的项目的代码文件一个一个的往新代码里面加，加一两个就build 到ie里测试一下，反复如此。
最终确定代码里有三处导入模块的地方会导致ie11报错：
import { tsImportEqualsDeclaration } from '@babel/types';
import deepcopy from 'deepcopy';
import { loadOptions } from '@babel/core'; 
删除这些引用，不用这些模块就行了

方法耗时但是没办法的办法了，好坑啊

**Comment by wangxingkang** [comment]
引用babel 的代码 这是要干啥

**Comment by guhuangjin** [comment]
@wangxingkang 引用了没用到，也不知道谁写的

**Comment by guhuangjin** [comment]
deepcopy 模块 我还想用的 有什么办法吗

**Comment by wangxingkang** [comment]
哈哈 好的吧
