### ISSUE TITLE
安装成功之后无法运行

### ISSUE THREAD

**Issue by monoshizuka** [ant-design/ant-design-pro#5078]
![TIM截图20190814092414](https://user-images.githubusercontent.com/26546536/62988640-a62f1580-be77-11e9-9338-a0ec947e31cf.png)
![TIM截图20190814092437](https://user-images.githubusercontent.com/26546536/62988652-adeeba00-be77-11e9-8257-3c4803708117.png)
运行就会提示什么文件不存在大小写不一致,但是又不提示是哪里出问题

**Comment by monoshizuka** [comment]
![TIM截图20190814094709](https://user-images.githubusercontent.com/26546536/62988895-864c2180-be78-11e9-9c61-2316a65112ad.png)
/list/search下的文件

**Comment by chenshuai2144** [comment]
关闭项目重启一下，这个好奇怪，给个重现的方式？

**Comment by monoshizuka** [comment]
> 关闭项目重启一下，这个好奇怪，给个重现的方式？

在路由里面把list/search相关的都删掉之后，可以打开了。我之前的步骤就是升级了一下node和npm。然后yarn create umi，依赖的话是npm install安装的，然后运行yarn fetch：blocks,然后启动.
大概是list/search里面的东西没有import到吧

**Comment by chenshuai2144** [comment]
是 windows？

**Comment by monoshizuka** [comment]
> 是 windows？

windows系统

**Comment by chenshuai2144** [comment]
看起来还是fetch blocks更新失败的问题
