### ISSUE TITLE
4.0后HeaderDropdown组件overlay不能实现下拉效果

### ISSUE THREAD

**Issue by RohanSensei** [ant-design/ant-design-pro#5079]
导致AvatarDropdown等用户菜单出不来，点击也不行。
版本4.0

**Comment by wukongnalizou** [comment]
avatar 标签加menu属性

**Comment by RohanSensei** [comment]
> avatar 标签加menu属性

具体怎么做？

**Comment by wukongnalizou** [comment]
![image](https://user-images.githubusercontent.com/37323494/63069414-515bcf80-bf49-11e9-9c4c-faa00d0e5d31.png)
v4版本 RightContent

**Comment by RohanSensei** [comment]
谢谢
