### ISSUE TITLE
husky setting up git hooks failed

### ISSUE THREAD

**Issue by Xeelong** [ant-design/ant-design-pro#5080]
husky@3.0.3 install E:\Demo\ant-design-pro\node_modules\husky
node husky install

husky > Setting up git hooks
Command failed: git rev-parse --show-toplevel --absolute-git-dir
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install

**Comment by chenshuai2144** [comment]
First you must be a git repository to register git hooks
