### ISSUE TITLE
v4 路由变化组件不更新

### ISSUE THREAD

**Issue by wukongnalizou** [ant-design/ant-design-pro#5082]
![eccc62e032862335914520125ab8ef0](https://user-images.githubusercontent.com/37323494/63002522-adbae280-bea8-11e9-897f-ecdf17b85b29.png)
二级菜单子路由，需要隐藏，达到跳页，面包屑变化，二级菜单高亮效果
![3af0d0c2f3c55ed1402690c44913a9c](https://user-images.githubusercontent.com/37323494/63002711-1c983b80-bea9-11e9-8d55-113b85f32efc.png)

目前原因是点击后url地址变化，不渲染shortOrder组件继续停留在OverShop组件

**Comment by wukongnalizou** [comment]
![1d5a3a3ac4b230e5fedbd6161a52422](https://user-images.githubusercontent.com/37323494/63003436-b3192c80-beaa-11e9-8e0e-ef0135ec8681.png)
为什么写在同级就好使

**Comment by chenshuai2144** [comment]
现在 pro 的默认的菜单规则是一棵树的模式。
`/list/item/123` 会 选中 /list , /list/item, /list/item/123。
你只要保证菜单是树形结构即可。

你的问题应该是 使用了相对路径造成的。不是 '/' 开头的路径会将父节点的路径拼上去。
