### ISSUE TITLE
ant pro 传值跨域问题

### ISSUE THREAD

**Issue by acainew** [ant-design/ant-design-pro#5083]
后端地址是:
http://localhost:8080/MyWeb/icitem/queryICItemListJson.action,
ssm框架,control 代码:
![image](https://user-images.githubusercontent.com/42227567/63004822-d85b6a00-bead-11e9-9b84-713e20468958.png)
前端请求代码:
![image](https://user-images.githubusercontent.com/42227567/63005096-6afc0900-beae-11e9-89ed-bf1f4eb0ea64.png)
出错:
![image](https://user-images.githubusercontent.com/42227567/63005133-7f400600-beae-11e9-93c4-843fc2d7cb67.png)
如果把后端和前端分别改成(后端去掉@requestbody,前端直接用地址栏传参):
![image](https://user-images.githubusercontent.com/42227567/63005182-98e14d80-beae-11e9-89a4-21059d344c96.png)
![image](https://user-images.githubusercontent.com/42227567/63005243-b9a9a300-beae-11e9-9689-512cb63d873f.png)
就成功,没有跨域问题
![image](https://user-images.githubusercontent.com/42227567/63005381-fb3a4e00-beae-11e9-8016-7c9b944ee87f.png)
请问有谁知道是什么原因吗?

**Comment by huntdream** [comment]
请求失败的返回头是怎么样的？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/63012206-69d1d880-bebc-11e9-808a-1b776c4704bd.png)
  是hou'dua后端给你的，不是前端自己设置的

**Comment by acainew** [comment]
> 请求失败的返回头是怎么样的？

![image](https://user-images.githubusercontent.com/42227567/63065556-118cec00-bf39-11e9-8184-56cdc45fc226.png)
失败的头是这样的!

**Comment by acainew** [comment]
> 是hou'dua后端给你的，不是前端自己设置的

![image](https://user-images.githubusercontent.com/42227567/63065616-53b62d80-bf39-11e9-85e3-967a74bd209a.png)

后端设置了也是一样,请求服务端的域是一样的(客户端loacalhost:8001,服务端localhost:8080),为什么用地址栏传参就可以,用payload的方式就不行呢?

**Comment by huntdream** [comment]
你直接在地址栏访问是同源的，origin就是localhost:8080。上面大佬的意思是把你前端请求头里面的`Access-Control-Allow-Origin`那行去掉。我试了一下，加上那一行产生了和你相同的错误

**Comment by acainew** [comment]
问题解决了,方法如下:跟前端antdpro无关,前端不需要做任何设置,
![image](https://user-images.githubusercontent.com/42227567/63070133-80c00b80-bf4c-11e9-92e1-9e0e981e589d.png)
后端Spring用拦截器处理跨域问题,直接用网上可行方案就可以了
![image](https://user-images.githubusercontent.com/42227567/63070333-69355280-bf4d-11e9-9baf-e7a30976eb41.png)
control中,如果是bean参数,用@CrossOrigin注解无效,非bean参数则有效,所以拦截器中设置就一劳永与了
![image](https://user-images.githubusercontent.com/42227567/63070537-2627af00-bf4e-11e9-9911-7088ebe13159.png)

thanks all.
