### ISSUE TITLE
路由配置跳转提示umi 404

### ISSUE THREAD

**Issue by lddlww** [ant-design/ant-design-pro#5084]
其中一段路由配置如下：
{
              path: '/platform/mysql',
              name: 'mysql',
              icon: 'icon-MySQL',
              component: './platform/mysql',
              exact: true,
              routes: [
                {
                  path: '/platform/mysql/meters',
                  name: 'meters',
                  component: './platform/mysql/meters',
                  // hideInMenu: true,
                  exact:true,
                },
                {
                  path: '/platform/mysql/test',
                  name: 'test',
                  component: './platform/mysql/test',
                },
              ]
            },

当跳转到/platform/mysql/meters 或者 /platform/mysql/test，都会报umi development 404 page错误

我的目录结构：
src/pages/platform/mysql/
                            index.tsx
                            meters.tsx
                            test.tsx

当我把下面两个配置去掉，就能正常访问，加上就不行
component: './platform/mysql',
exact: true,

**Comment by lddlww** [comment]
经测试，所有这样子配置都会报下面这个错误：

There's not a page yet at xxxxxxx.

Create a React.js component in your pages directory at xxxxxx.js and configure the route in config file then this page will automatically refresh to show the new page component you created.

**Comment by chenshuai2144** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#exact-bool

exact 是严格模式，他会严格比对 url。

'/' , "/link" 在严格模式下只会命中 "/"

**Comment by lddlww** [comment]
@chenshuai2144  那我要怎么配置才能够既可以访问/platform/mysql，也可以访问：/platform/mysql/meters?

**Comment by lddlww** [comment]
明白了，直接在routes中配置父组件即可，如下：
path: '/platform/action',
name: 'action',
// component: './platform/action',
// exact: true,
// hideInMenu:true,
routes: [
{
path:'/platform/action',
component:'./platform/action',
exact:true,
},
{
path: '/platform/action/mysql/meters',
name: 'meters',
component: './platform/action/mysql/meters',
exact:true,
// hideInMenu:true,
},
{
path: '/platform/action/mysql/tags',
name: 'tags',
component: './platform/action/mysql/tags',
exact:true,
// hideInMenu:true,
},
{
path: '/platform/action/mysql/alerts',
name: 'alerts',
component: './platform/action/mysql/alerts',
exact:true,
// hideInMenu:true,
},
]
},
