### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#5085]
`  componentDidMount() {
    const { dispatch } = this.props;
    dispatch({
      type: 'clientList/fetchSell',
    });
    dispatch({
      type: 'clientList/fetchClient',
      payload: {'userid':'all'},
    });
  }`
将`   dispatch({
      type: 'clientList/fetchSell',
    });`注释就不报错，不知道是那写的有问题请大佬帮我看一看

**Comment by chenshuai2144** [comment]
key 重复了。
https://zh-hans.reactjs.org/docs/lists-and-keys.html

**Comment by kzabc** [comment]
@chenshuai2144 应该不是数据的问题因为mysql 主键递增了
`  <PageHeaderWrapper>
        <Card bordered={false}>
          <div className={styles.tableList}>
            <div className={styles.tableListForm}>{this.renderForm()}</div>
            <div className={styles.tableListOperator}>
              <Button icon="plus" type="primary" onClick={() => this.handleModalVisible(true)}>
                新建
              </Button>
            </div>
            <StandardTable
              rowKey={'id'}
              rowSelection={rowSelection}
              selectedRows={selectedRows}
              loading={loading}
              data={data}
              columns={this.columns}
              onSelectRow={this.handleSelectRows}
              onChange={this.handleStandardTableChange}
            />
          </div>
        </Card>
        <CreateForm {...parentMethods} modalVisible={modalVisible} />
        {stepFormValues && Object.keys(stepFormValues).length ? (
          <UpdateForm
            {...updateMethods}
            updateModalVisible={updateModalVisible}
            values={stepFormValues}
          />
        ) : null}
      </PageHeaderWrapper>`
主要是我在删除dispatch({ type: 'clientList/fetchSell', });后就不出现问题了

**Comment by kzabc** [comment]
@chenshuai2144 ` renderSimpleForm() {
    const {
      emailList: { selldata },
    } = this.props;
    //console.log(selldata);
    return (
            <Radio.Group size="default">
              <Radio.Button value="all">全部</Radio.Button>
                {
                  selldata.data.map((value) => (
                  <Radio.Button value={value.userid}>{value.username} </Radio.Button>
                ))
              }
            </Radio.Group>
    );
  }
`
一直在提示Each child in a list should have a unique "key" prop
注释掉  ```
{
                  selldata.data.map((value) => (
                  <Radio.Button value={value.userid}>{value.username} </Radio.Button>
                ))
              }
```也就好了搞不懂到底是哪里出了问题 麻烦大佬帮忙看下

**Comment by kzabc** [comment]
注释掉
{
selldata.data.map((value) => (
<Radio.Button value={value.userid}>{value.username} </Radio.Button>
))
} 

就好了搞不懂到底是哪里出了问题
