### ISSUE TITLE
新版本运行，有错误和警报

### ISSUE THREAD

**Issue by bijiasuo2006** [ant-design/ant-design-pro#5086]
新版本安装完后出现一下错误和警告，是否可以修复？

具体细节看附件。
![TIM截图20190814202115](https://user-images.githubusercontent.com/127547/63020583-18801400-bed1-11e9-8f2a-37c513d4e546.png)

**Comment by SoberK** [comment]
antd组建废弃了，要用新的替换

**Comment by chenshuai2144** [comment]
这个需要 umi 那边去修，还有一些生命周期废弃的事情

**Comment by bijiasuo2006** [comment]
如何能促进这个问题修复？我需要到Umi那里报问题么？我搜了下，在工程里没有相关代码，我无法自己修复。谢谢。

**Comment by chenshuai2144** [comment]
@bijiasuo2006 还有一些是第三方库，可能需要社区反映一段时间

**Comment by bijiasuo2006** [comment]
好的，谢谢。持续关注中

**Comment by chenshuai2144** [comment]
在这里看吧 https://github.com/ant-design/ant-design-pro/issues/5014
