### ISSUE TITLE
How to nest the grid?

### ISSUE THREAD

**Issue by zhenlingcn** [ant-design/ant-design-pro#5087]
I had created two columns(6-span), and I want to add a component under these two columns, how can I do that?  
I'm used to be an android developer. I know that can easily realize by the linear layout in android.
![image](https://user-images.githubusercontent.com/18747119/63029609-6f8ee480-bee3-11e9-9c2e-6b86ee04656f.png)

**Comment by chenshuai2144** [comment]
you can use flex.
http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html
https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex
