### ISSUE TITLE
typescript没进行类型检测?

### ISSUE THREAD

**Issue by imjamespond** [ant-design/ant-design-pro#5089]
如题,  类型不对编译成功? 控制台没有任何提示, 有人说在vs的问题标签有提示, 但是单独配置ts项目控制台是有报错的!?

**Comment by chenshuai2144** [comment]
类型只是辅助，还是会编译成功的。只是在编译的时候提示你。

**Comment by Matthew1994** [comment]
应该提供这个选项的

**Comment by wangzhengbo** [comment]
觉得能提供一个选项支持是不错的，可以全局检测ts编译问题

**Comment by chenshuai2144** [comment]
可以执行一下tsc的 ci里有

**Comment by wangzhengbo** [comment]
> 可以执行一下tsc的 ci里有

请问这个是啥意思呀
