### ISSUE TITLE
重新拉一下这master

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#509]
安装提示这个是什么鬼 
warning "slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
jquery????

**Comment by yesmeck** [comment]
https://github.com/akiran/react-slick/issues/240

忽略就好了。

**Comment by chenshuai2144** [comment]
warning  不算错误....  看开一点兄弟

**Comment by wunayou** [comment]
不喜欢jquery
