### ISSUE TITLE
eslint在编译后不直接显示错误和警告

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design-pro#5090]
用antd design pro 4.0 在写完代码编译后，控制台没有直接显示错误和警告。而是在commit的时候才显示错误和警告。这样写完代码，才知道错误。预期想每编译一次，就直接才控制台显示出错误和警告。这样就在commit之前，就把错误和警告修改了。

**Comment by chenshuai2144** [comment]
ide 会直接提示的。
如果 eslint 报错无法编译，会有很多代码直接无法使用。umi 不会去做，你可以自行增加一个插件来实现这个功能
