### ISSUE TITLE
ant如何调用public下普通js方法

### ISSUE THREAD

**Issue by rxht** [ant-design/ant-design-pro#5091]
如何在组件中调用自己的普通js方法，js存在于public中的lib文件夹下

**Comment by wangxingkang** [comment]
一个插件吗？

**Comment by rxht** [comment]
就一个普通的方法，我后面直接将他放入到document.ejs中进行引入，然后在自己的组件中直接调用，就解决了这个问题。

**Comment by wangxingkang** [comment]
那为啥 不放到  utils目录  用import 引用呢？

**Comment by rxht** [comment]
我会更新这个js，然后拿到数据，放在utils中在编译的时候就被打包了，我就拿不到它了，相当于我将这个js当做是一个数据传递的作用

**Comment by wangxingkang** [comment]
哈哈 可以描述下场景吗

**Comment by rxht** [comment]
让其他人直接写入的我js文件，到时候我直接读取这个文件，用于获取数据，因为js无法直接读取本地的文件，所以就这样处理了

**Comment by wangxingkang** [comment]
什么数据呢？可以写个json 啊，然后 搞个请求

**Comment by chenshuai2144** [comment]
建议使用http请求，写文件的可靠性太低了

**Comment by rxht** [comment]
我不是通过后台的，是另外的一个程序来和我进行通讯的

在 2019-08-17 00:18:56，"陈帅" <notifications@github.com> 写道：


建议使用http请求，写文件的可靠性太低了

**Comment by rxht** [comment]
是其他程序给我传数据，不经过网络，所以不走http

在 2019-08-15 16:48:58，"wangxingkang" <notifications@github.com> 写道：


什么数据呢？可以写个json 啊，然后 搞个请求

**Comment by wangxingkang** [comment]
那可以关闭了 哈哈

**Comment by rxht** [comment]
好的好的

在 2019-08-17 19:20:22，"wangxingkang" <notifications@github.com> 写道：


那可以关闭了 哈哈
