### ISSUE TITLE
linux 下包兼容问题

### ISSUE THREAD

**Issue by mushroomlb** [ant-design/ant-design-pro#5092]
如下图，在linux中安装包时出现如下问题，build之后的dist菜单无法点开
![image](https://user-images.githubusercontent.com/1701771/63075322-e075e100-bf63-11e9-9b75-fa5c246ca161.png)

**Comment by chenshuai2144** [comment]
看看这个
https://github.com/ant-design/ant-design-pro/issues/5068

**Comment by mushroomlb** [comment]
后来改用cnpm安装就好了，主要是puppter的 chrome安装的问题
