### ISSUE TITLE
面包屑怎么动态设置名称呢

### ISSUE THREAD

**Issue by mynameismaosheng** [ant-design/ant-design-pro#5093]
系统设置 / 用户管理 / 新增用户
系统设置 / 用户管理 / 编辑用户
系统设置 / 用户管理 / 用户详情

新增用户, 编辑用户, 用户详情 都是同一个页面, 如何设置成一个url 根据参数不一样设置不同的name呢?

**Comment by lengthmin** [comment]
研究了一下，权当抛砖引玉

---

在 BasicLayout 中，breadcrumbRender 用来生成面包屑数据，itemRender 用来渲染面包屑。
可以在 itemRender 这一步中改变一些东西。

```jsx
itemRender={(route, params, routes, paths) => {
  const savedBreadcrumbName = localStorage.getItem(`_${route.path}_breadcrumbName`);
  return <Link to={route.path}>{savedBreadcrumbName || route.breadcrumbName}</Link>;
}}
```
比如说在 localStorage 里设置自定义的路由名字

**Comment by chenshuai2144** [comment]
楼上的是个解决办法， 但是最好是自定义 pageHeader，在这些特殊的页面没有万能的银弹
