### ISSUE TITLE
TimelineChart component break when accepting an empty array data

### ISSUE THREAD

**Issue by Chersquwn** [ant-design/ant-design-pro#5094]
TimelineChart组件在接收一个空数组数据时，会直接报错，但是通常情况下，初始化数据为空数组，[#3385](https://github.com/ant-design/ant-design-pro/pull/3385)只解决了非数组的情况

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
