### ISSUE TITLE
怎么直接导入.less文件不用带前缀？

### ISSUE THREAD

**Issue by lddlww** [ant-design/ant-design-pro#5097]
如：import './styles.less'  可以直接className='xxx' （这种直接导入样式不生效）

而不要:   import styles from './styles.less' ,className={styles.xxx} （这种模块化导入可以生效）

或者怎么配置，可以让两个可以同时使用？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5100

重复了
