### ISSUE TITLE
更新了项目依赖之后，非根目录配置的路径会写到hash去

### ISSUE THREAD

**Issue by wangzhipeng404** [ant-design/ant-design-pro#5099]
在config配置了
{
base: '/admin/',
outputPath: './admin',
publicPath: '/admin/',
}
原来生成的路径是 localhost:8000/admin/index.html#/index
更新后的路径却是 localhost:8000/admin/index.html#/admin/index
而且登陆后重定向回来的时候会变成 localhost:8000/admin/index.html#/admin/admin/index
请问如何配置才能恢复原来的路径？

**Comment by chenshuai2144** [comment]
问题应该出在了重定向的地方，给一个重定向的代码仓库吧。
可以参考这里
https://github.com/ant-design/pro-blocks/blob/ffa27d5927904dd0acc8a8b5904f04a31d434d4c/UserLogin/src/model.ts
