### ISSUE TITLE
图表渲染更新代码错误

### ISSUE THREAD

**Issue by bardma** [ant-design/ant-design-pro#51]
http://pro.ant.design/docs/graph
![image](https://user-images.githubusercontent.com/9312044/32159045-b317af02-bd19-11e7-9975-d89d5666e8d6.png)
data 是一个数组，不能直接比较吧。

**Comment by afc163** [comment]
可以比较，如果父组件希望通知子组件更新，应该拷贝一份再 setState。

```jsx
const newData = [...this.state.data];

this.setState({ data: newData })
```
```

**Comment by bardma** [comment]
![image](https://user-images.githubusercontent.com/9312044/32160395-95c11320-bd1f-11e7-9e27-6b2f2fc276b2.png)
@afc163 http://pro.ant.design/docs/graph#图表重绘时机

虽然文档下面有写对象的对比函数，但是我觉得可以省略上面代码

**Comment by bardma** [comment]
不严禁的 还是不严谨的 还是错误的

**Comment by afc163** [comment]
@nigoku

**Comment by nikogu** [comment]
`不严谨的`，稍后我同步文档

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/ee7d49931b4460d7c588c4999e02842360ae8551
