### ISSUE TITLE
路由配置，umi识别文件夹路径报错

### ISSUE THREAD

**Issue by lLeahDizon** [ant-design/ant-design-pro#5101]
![微信图片_20190816102041](https://user-images.githubusercontent.com/16300255/63139103-a06c3800-c00f-11e9-8b2d-c1708bfe487d.png)
![微信图片_20190816102051](https://user-images.githubusercontent.com/16300255/63139111-a82bdc80-c00f-11e9-8f6f-a58437973a88.png)
![微信图片_20190816102057](https://user-images.githubusercontent.com/16300255/63139114-aa8e3680-c00f-11e9-8b22-0af25f4d5058.png)
参照分布表单的路由配置，在父目录下添加了一个文件夹路径，但是会运行不起来。

**Comment by chenshuai2144** [comment]
所有的页面都要在 src/page 下面，不能放到别的地方

**Comment by lLeahDizon** [comment]
问题解决了，目录没看仔细，里面还有一个index文件，在umi里的router才注意到，谢谢。
