### ISSUE TITLE
在formitem里使用treeselect  结构显示出来了 但是数据展示不出来 怎么设置？

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5102]
数据是这样的
![image](https://user-images.githubusercontent.com/47104575/63139970-d2cb6480-c012-11e9-856d-1b3df9dbf982.png)
想让它显示的是deptName 是不是这样  默认是title 改成别的是用treeNodeLabelProp这个属性吧
![image](https://user-images.githubusercontent.com/47104575/63139999-ed9dd900-c012-11e9-8bae-a9dc806bbeef.png)
结果是这样的   没显示  但结构是对的
![image](https://user-images.githubusercontent.com/47104575/63140041-0d350180-c013-11e9-8f45-d55dcb4eb354.png)

**Comment by 904492381** [comment]
@chenshuai2144    能改让它显示的是哪个键名吗

**Comment by chenshuai2144** [comment]
你需要自己用 map 转化一下。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map
