### ISSUE TITLE
ie11 页面元素不能重新渲染

### ISSUE THREAD

**Issue by guhuangjin** [ant-design/ant-design-pro#5105]
ant design pro 版本：2.3.1
1. 第一次访问页面可以渲染成功，更新数据后，页面取的缓存中的数据；状态没有重新渲染；
2. 安装‘react-app-polyfill’后 尝试在global.js 中头部添加  import "react-app-polyfill/ie11";  没有效果
3. 在chrome中测试正常

测试图：
![test](https://user-images.githubusercontent.com/33539824/63142154-470a0600-c01b-11e9-8b3f-52bf9574b60c.gif)

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
