### ISSUE TITLE
使用treeselect报错

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5106]
![image](https://user-images.githubusercontent.com/47104575/63146960-4b401e80-c02f-11e9-8249-adb76494d053.png)
![image](https://user-images.githubusercontent.com/47104575/63146986-5b57fe00-c02f-11e9-8fc4-e41deafc9c64.png)

代码
![image](https://user-images.githubusercontent.com/47104575/63147166-ea651600-c02f-11e9-9f14-e62d8ab0d8f3.png)
![image](https://user-images.githubusercontent.com/47104575/63147183-f0f38d80-c02f-11e9-8e84-fedbd28c7cc3.png)

不知道怎么回事  我在table里也用到了这个数据 但是我深拷贝了 还是报错  选项也都列出来了 就是点击无效  这是什么问题？
![image](https://user-images.githubusercontent.com/47104575/63147316-47f96280-c030-11e9-979a-56095feb334f.png)

**Comment by chenshuai2144** [comment]
这个提示是key重复的提示  洗一下你的数据吧

**Comment by 904492381** [comment]
> 这个提示是key重复的提示 洗一下你的数据吧

我看了呀  这几条key都是不同的
