### ISSUE TITLE
更新antd到新版后，所有国际化文本变成null，有报错信息

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#5107]
更新antd到新版后，所有国际化文本变成null，有报错信息：如下图所示
![image](https://user-images.githubusercontent.com/51013754/63154397-163dc700-c043-11e9-99a0-b9467f59d2d9.png)

![image](https://user-images.githubusercontent.com/51013754/63154455-379eb300-c043-11e9-8d17-d020d4a65854.png)

**Comment by effapp** [comment]
补充一下：antd 3.21.4

**Comment by chenshuai2144** [comment]
这是 umi  得问题。重新更新一下 umi
