### ISSUE TITLE
v4调用浏览器打印功能如何隐藏左边菜单栏？

### ISSUE THREAD

**Issue by ybjaawork** [ant-design/ant-design-pro#5108]
请问, v4调用浏览器打印功能如何隐藏左边菜单栏？

以前v2版本时，由于左边菜单栏是在项目代码中，可以去更改样式

`@media print {display:none} `
方式隐藏。

现在v4直接包装成组件了，无法修改了，我试了在全局global.less 设置。菜单内容是隐藏了，可界面还在。

```
@media print{
      aside.ant-layout-sider{
        display: none;
      } 
}
```

请问有没有什么方法达到我想要的要求？即打印时自动隐藏左边的菜单栏。

**Comment by chenshuai2144** [comment]
```
{
@media print{
     .ant-pro-sider-menu-sider{
        display: none;
      } 
}}
```

**Comment by ybjaawork** [comment]
那种方法试过了，不管用，在全局global.less 设置，和设置 aside.ant-layout-sider效果一样 

![搜狗截图20190818191308](https://user-images.githubusercontent.com/35591268/63223682-4e343e00-c1ec-11e9-8080-eaf87bf9003e.jpg)

**Comment by chenshuai2144** [comment]
手机模式用的是drawer。 直接 ant-drawer 就好了

**Comment by ybjaawork** [comment]
大神，不好意思，境界还没达到那么高，能否提示一下，是否菜单栏用了 ant-drawer的原理？因为没有用在手机端，只是PC上使用。就是想实现 CTRL+P 调用浏览器打印功能时能够自动隐藏左边的菜单栏。

现在找到了一种笨办法，在 BasicLayout.tsx 文件，新增以及修改了以下代码

```

class BasicLayoutClass extends Component<BasicLayoutProps>{

  componentDidMount(){
    window.addEventListener("beforeprint",this.closeCollapsed);
  }

  componentWillUnmount(){
    window.removeEventListener("beforeprint",this.closeCollapsed);
  }


  /**
   * 关闭左边菜单栏
   */
  closeCollapsed =()=>{

    const {dispatch} =this.props;

    dispatch({
      type: 'global/changeLayoutCollapsed',
      payload:true,
    });
  };



  render(){
    return (<BasicLayout {...this.props} />);
  }

}

export default connect(({ global, settings }: ConnectState) => ({
  collapsed: global.collapsed,
  settings,
}))(BasicLayoutClass);

```

这样的话，每次ctrl+P直接调用浏览器打印功能，就能够隐藏掉左边的菜单栏。不知道大神还有没有其他更方便的方式？

**Comment by chenshuai2144** [comment]
你的方法才是最好的，通过 js 控制多方便。
你也可以设置 menuRender  为 false

**Comment by ybjaawork** [comment]
谢谢大神
