### ISSUE TITLE
菜单栏中图表和文字不能够水平对齐？

### ISSUE THREAD

**Issue by lddlww** [ant-design/ant-design-pro#5111]
要怎么设置让Icon和menu文字水平对齐？

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/display
看看这个。要是没有兼容性问题 推荐 flex。
http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html?utm_source=tuicool
