### ISSUE TITLE
npm run fetch:blocks 后报错 “ERR_WEBPACK_MODULE_NOT_FOUND”，也按其他issue中方法尝试解决还是不行

### ISSUE THREAD

**Issue by happylys** [ant-design/ant-design-pro#5113]
npm run fetch:blocks 后报错 “ERR_WEBPACK_MODULE_NOT_FOUND”，也按其他issue中方法尝试解决还是不行。node npm 卸载并重新安装最新版本都无法解决。
能否给个完整的版本，或明确的详细的解决方法，不要一会链接到一个issue,又链接到另一个issue；给人感觉一个bug的解决依赖另一个bug，结果还没有头绪。

**Comment by chenshuai2144** [comment]
emmm，可以打开 debug  模式试一下。
ERR_WEBPACK_MODULE_NOT_FOUND 这个错误已经说的很清楚了，包没有下载成功。
https://github.com/ant-design/ant-design-pro-cli#debug

**Comment by zoeykk** [comment]
系统：win10   
block 下载有些页面可以，有些页面不行
![error](https://user-images.githubusercontent.com/36698694/63207481-d5ed5000-c0f9-11e9-8a96-f706270043d3.png)

**Comment by chenshuai2144** [comment]
试试用 tyarn，
https://www.npmjs.com/package/tyarn

**Comment by chenshuai2144** [comment]
```
 Usage: umi block <command>

  Commands:

    add      add a block to your project
    list     list all blocks
    clear    clear all git cache


  Options for the add command:

    --path               the route path, default the name in package.json
    --branch             git branch
    --npm-client         the npm client, default npm or yarn (if has yarn.lock)
    --skip-dependencies  don't install dependencies
    --skip-modify-routes don't modify the routes
    --dry-run            for test, don't install dependencies and download
    --page               add the block to a independent directory as a page
    --layout             add as a layout block (add route with empty children)
    --js                 If the block is typescript, convert to js
    --registry           set up npm installation using the registry
    --uni18n             remove umi-plugin-locale formatMessage
```

**Comment by zoeykk** [comment]
感觉还是不行啊
 命令：umi block add DashboardAnalysis --path=/dashboard/analysis --yarn-client
![error2](https://user-images.githubusercontent.com/36698694/63208027-28326f00-c102-11e9-9e54-a7d8824124fb.png)

**Comment by chenshuai2144** [comment]
`--npm-client =tyarn`

**Comment by happylys** [comment]
是我操作有问题吗？操作如下(mac os):
1.npm create umi (ok)
2.cnpm install (ok)
3.cnpm start (ok)
4.npm run fetch:blocks --npm-client=tyarn (ok)
5.cnpm install (ok)
6.cnpm start (ERR_WEBPACK_MODULE_NOT_FOUND 错误，重复1~6 还是错误)
看到有的网友给出的方案，手动将blocks压缩包下载，并拷贝到.umi下的指定目录下，再执行第4步，还是很慢，并且也没有解决
入门这么难啊

**Comment by chenshuai2144** [comment]
emmm，可以打开 debug 模式试一下。
ERR_WEBPACK_MODULE_NOT_FOUND 这个错误已经说的很清楚了，包没有下载成功。
https://github.com/ant-design/ant-design-pro-cli#debug

我很好奇，为什么你要 fetch:blocks 这个是给官方进行部署用的。

**Comment by chenshuai2144** [comment]
直接用这个分支算了。非要全部代码。 fetch：block 需要稳定的网络。
https://github.com/ant-design/ant-design-pro/tree/all-blocks

最好打开debug给我看一下，报啥错了。

**Comment by happylys** [comment]
多谢了
