### ISSUE TITLE
远程加载菜单后，单击二级菜单项后，菜单会自动折叠起来。ProLayout的固定侧边栏功能没有

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#5116]
问题1：远程加载菜单后，单击二级菜单项后，菜单会自动折叠起来。
问题2：ProLayout的固定侧边栏功能没有，官网实现例子：
<Sider
style={{
overflow: 'auto',
height: '100vh',
position: 'fixed',
left: 0,
}}
>

在ProLayout中如何实现？

**Comment by chenshuai2144** [comment]
> 远程加载菜单后，单击二级菜单项后，菜单会自动折叠起来。

可以通过配置 openKeys 和 selectKeys 自动配置。


> ProLayout的固定侧边栏功能没有。

设置 fixSiderbar=true 即可

**Comment by effapp** [comment]
1、设置 fixSiderbar=true 不起作用，实际设置fixSiderbar= { true }，也不起作用。
2、远程加载菜单后，单击二级菜单项后，菜单会自动折叠起来
请问怎样配置 openKeys 和 selectKeys？ 
我的代码：
return (
    <>
      <ProLayout
        logo={logo}
        onCollapse={handleMenuCollapse}
        menuItemRender={(menuItemProps, defaultDom) => (
          <Link to={menuItemProps.path}>{defaultDom}</Link>
        )}
        breadcrumbRender={(routers = []) => [
          {
            path: '/',
            breadcrumbName: formatMessage({
              id: 'menu.home',
              defaultMessage: 'Home',
            }),
          },
          ...routers,
        ]}
        footerRender={footerRender}
        fixSiderbar = {true}
        menuDataRender={() => menuData || []}
        formatMessage={formatMessage}
        rightContentRender={rightProps => <RightContent {...rightProps} />}
        {...props}
        {...settings}
      >
        {children}
      </ProLayout>
    </>
  );

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis?language=zh-CN&fixSiderbar=1

> 请问怎样配置 openKeys 和 selectKeys？
就像 [menu](https://ant.design/components/menu-cn/#header) 一样使用即可、

**Comment by effapp** [comment]
通过url加上&fixSiderbar=1，我的程序也能够实现固定siderbar，但为什么设置fixSiderbar = {true}不起作用？

**Comment by chenshuai2144** [comment]
你看一下你的 settings.json 你可以在里面直接配置的

**Comment by effapp** [comment]
另外，我是远程从服务器取回的菜单数据，每次单击子菜单项，父菜单都会折叠起来，代码如下：
useEffect(() => {
    const url = '/Sys/GetMenus/';
    const opts = {
      method: 'POST',
      data: {},      
    };
    request(url, opts).then(data => {
      setMenuData(data);
    }
    ).catch(error => {
      ;
    });

  },[]);

怎样防止父菜单折叠呢？

**Comment by chenshuai2144** [comment]
你的菜单不符合 pro 的规范，pro 的菜单应该一棵树。所以需要自己控制了

**Comment by pkaq** [comment]
> 问题1：远程加载菜单后，单击二级菜单项后，菜单会自动折叠起来。
> 问题2：ProLayout的固定侧边栏功能没有，官网实现例子：
> <Sider
> style={{
> overflow: 'auto',
> height: '100vh',
> position: 'fixed',
> left: 0,
> }}
> 
> > 
> 
> 在ProLayout中如何实现？

我也遇到了这个问题 使用本地路由生成得就没问题 远程加载过来就不行 而且远程格式是没错的

**Comment by immortalt** [comment]
> 

defaultSettings.ts是可以设置 fixSiderbar: true,
但是根据我的对比，设置为true还是false，是没有区别的。
我遇到的坑：
当 splitMenus: true时，点击切换顶部的一级菜单后，侧边的导航二级菜单会自动横向折叠。
当 splitMenus: false时，打开页面后，侧边的导航菜单会自动横向折叠的状态，需要手动展开才能看到文字。
版本：
ant-design-pro@6.0.0-beta.1
Umi v4.0.8
