### ISSUE TITLE
Table移动端体验不好，移动端可不可以把横向改为纵向

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#5119]
![image](https://user-images.githubusercontent.com/44694221/63228588-b2282800-c227-11e9-92a1-fbda1c995c58.png)

https://semantic-ui.com/collections/table.html#padded

![image](https://user-images.githubusercontent.com/44694221/63228596-cec46000-c227-11e9-913b-c77cf0dd7422.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8465

**Comment by keke122765** [comment]
> [ant-design/ant-design#8465](https://github.com/ant-design/ant-design/issues/8465)

这个Issue我看过了  没有找到纵向的实现

**Comment by keke122765** [comment]
有的用户甚至不知道移动端的表格可以左右滑动

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/8465

在这里，是一段 css
