### ISSUE TITLE
antd 3.x 版本 Upload 组件的 onChange 回调只执行一次

### ISSUE THREAD

**Issue by wb-chenlong** [ant-design/ant-design-pro#512]
- 环境：antd pro
- antd-version：3.0.0
- 重现：
	- Upload 组件，onChange 回调只执行了 uploading，无论成功还是失败，都没有执行 done 和 error。

![image](https://user-images.githubusercontent.com/14194437/34373730-0ddc1f8c-eb18-11e7-815c-a79d690c2ce2.png)
![image](https://user-images.githubusercontent.com/14194437/34373774-43f57fbe-eb18-11e7-9516-a4884638a58a.png)

**Comment by chenshuai2144** [comment]
第一个问的地方不对
第二 这个问题已经有人回答过了
https://github.com/ant-design/ant-design/issues/2423
