### ISSUE TITLE
浏览器刷新页面时，需要重新登录

### ISSUE THREAD

**Issue by bluesky2525** [ant-design/ant-design-pro#5122]
使用Chrome浏览器，ant Design pro v4版本。
登录后，当点击浏览器的刷新按钮后，发现localStorage里面保存的数据全部消失了，导致跳转到登录页，必须重新登录。
不知道And-design-pro哪个地方有清除localStorage的？我搜索clear，没有发现有。

**Comment by codecook2020** [comment]
我遇到了和你一样的问题，而且很难复现，怀疑过与localstrage容量限制有关，因为出现的案例一共两次都事先大量使用了indexdb，localstrage。 但这个理由也很难成立，因为我换个环境（新域名）又可能登陆。
怀疑过localstrage 未必是同步的（但感觉不像）
环境： antd pro 4.0 chrome： 84
现象：
登陆后跳转页面接着刷新页面重新回到登录页。
我留意到localstrage先插入，然后立即删除了。（重要）
当我重启浏览器后，此问题不再复现。
