### ISSUE TITLE
执行npx react-codemod rename-unsafe-lifecycles 无效问题

### ISSUE THREAD

**Issue by KingThq** [ant-design/ant-design-pro#5123]
fatal: not a git repository (or any of the parent directories): .git
Thank you for using react-codemods!

But before we continue, please stash or commit your git changes.

You may use the --force flag to override this safety check.

**Comment by chenshuai2144** [comment]
他需要你是个 git 仓库，错误日志写的很清楚

**Comment by KingThq** [comment]
ok，谢谢
