### ISSUE TITLE
antd css is overridden by another css framework

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#5127]
Hi I am using different components for my development , which has it own styles , it also has its own global css, when i integrate , this with antd application , ant design css has being overriden by other framework css, how to avoid this  , still i am using those components and styles only in particular pages , still it is affecting entire application, i don't want to alter the existing css of ant design , at the same time i need to have the new components with the new css also, kindly give me some solution

**Comment by robert-claypool** [comment]
I don't think anyone can help you without much more information. It seems you need individual consultation, not a GitHub issue response.

**Comment by robert-claypool** [comment]
This issue should be closed.

There is nothing anyone can do for @THARAKS without more info, and it sounds like the "issue" is application-specific anyway.
