### ISSUE TITLE
ant design pro IE11 报错

### ISSUE THREAD

**Issue by lzy94** [ant-design/ant-design-pro#5128]
项目中加了配置
   targets: {
      ie: 11,
   },
后IE11 还是没法运行
报错信息：
SCRIPT1002: 语法错误
vendors.async.js (81878,28)
Unhandled promise rejection ChunkLoadError: Loading chunk vendors failed.
(missing: http://localhost:8000/vendors.async.js)
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "",
      message: "Loading chunk vendors failed.
(missing: http://localhost:8000/vendors.async.js)",
      name: "ChunkLoadError",
      number: 0,
      request: "http://localhost:8000/vendors.async.js",
      stack: "ChunkLoadError: Loading chunk vendors failed.
(missing: http://localhost:8000/vendors.async.js)
   at Anonymous function (http://localhost:8000/umi.js:159:14)
   at run (http://localhost:8000/umi.js:17962:13)
   at Anonymous function (http://localhost:8000/umi.js:17979:30)
   at flush (http://localhost:8000/umi.js:14485:9)",
      Symbol()_y.pw4gumjtl6c: undefined,
      Symbol()_z.pw4gumjtl6c: undefined,
      Symbol(observable)_12.pw4gumjtl6: undefined,
      Symbol(react.async_mode)_x.pw4gumjtl6c: undefined,
      Symbol(react.concurrent_mode)_s.pw4gumjtljb: undefined,
      Symbol(react.context)_r.pw4gumjtljb: undefined,
      Symbol(react.element)_l.pw4gumjtljb: undefined,
      Symbol(react.forward_ref)_t.pw4gumjtljb: undefined,
      Symbol(react.fragment)_n.pw4gumjtljb: undefined,
      Symbol(react.lazy)_w.pw4gumjtl6c: undefined,
      Symbol(react.memo)_v.pw4gumjtljb: undefined,
      Symbol(react.portal)_m.pw4gumjtljb: undefined,
      Symbol(react.profiler)_p.pw4gumjtljb: undefined,
      Symbol(react.provider)_q.pw4gumjtljb: undefined,
      Symbol(react.strict_mode)_o.pw4gumjtljb: undefined,
      Symbol(react.suspense)_u.pw4gumjtljb: undefined,
      Symbol(Symbol.observable)_10.pw4gumjtl6: undefined,
      Symbol(util.promisify.custom)_11.pw4gumjtl6: undefined,
      type: "missing"
   }

**Comment by chenshuai2144** [comment]
target 的添加只会影响到 build 之后的代码。dev 还是尽量用 chrome

**Comment by lzy94** [comment]
> 你的错误是因为代码分割，关掉就好了。[＃4996](https://github.com/ant-design/ant-design-pro/issues/4996)

我把那个配置去掉后，打包运行还是会报错

**Comment by chenshuai2144** [comment]
可以看一下报错是什么，一般是因为用了不支持 ie 的第三方库

**Comment by chenshuai2144** [comment]
官方的配置是可以，一般是用了维护比较差的第三方库造成的。
