### ISSUE TITLE
如何获取到当前的路由信息，然后给对应的Menu项展开？

### ISSUE THREAD

**Issue by softshield** [ant-design/ant-design-pro#5129]
如何获取到当前的路由信息，然后给对应的Menu项展开？
主要是不知道调用啥接口能获取到当前的路由信息。

**Comment by chenshuai2144** [comment]
dva 中自带了这个。
https://github.com/supasate/connected-react-router
你可以通过这种方式获得

**Comment by softshield** [comment]
要是为了这个功能又安装一个插件代价有点大。
最后通过location.hash对比搞定了。

**Comment by chenshuai2144** [comment]
@softshield 这个自带了，通过 this.props 就能拿到了
