### ISSUE TITLE
StandardTable 觉得封装的有点废了

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#513]
![image](https://user-images.githubusercontent.com/12181423/34398389-89a6b806-ebb9-11e7-962d-d891b3e73ba7.png)

这个标准表格，完全不能像其他组件那样使用。如下面这些数据
![image](https://user-images.githubusercontent.com/12181423/34398452-ee6eb194-ebb9-11e7-8777-25f1233d72e2.png)
都可以让用户自定义传入，让用户配置自己需要的 columns 等，这样才通用。

@sorrycc

**Comment by chenshuai2144** [comment]
这个不是个通用组件.
你没发现他没有文档吗?

**Comment by afc163** [comment]
PR is welcome~

**Comment by hqwlkj** [comment]
建议 做成通用的数据表格。毕竟你们 已经放在 components 目录下的，要么就不要放在 components 下，不然很容易误解。

**Comment by afc163** [comment]
columns 确实应该提出来。@hqwlkj 来个 PR 贡献一下如何？:smiley:

**Comment by hqwlkj** [comment]
可以啊，非常乐意

**Comment by wunayou** [comment]
那菜单组件 也需要弄出来  建contains文件夹啊

**Comment by tworry** [comment]
这个我重新写过。
不光是columns，还有onchange等等，都放到组件里面，外面只需要留dispatch。

**Comment by Frank1e0927** [comment]
这个，我也已经重新提出来了，原本我是在standardTable里面写了个config文件，来对应的colums，后来发现也不好维护，最后包括colums和 rowselection 和 onchange,全部提出来到引用组件上了 = =

**Comment by LKCheng** [comment]
![image](https://user-images.githubusercontent.com/10054789/35370720-80bb69cc-01ca-11e8-8d5d-09b15e01156c.png)
我把columns 提出来了，其他的没有动
![image](https://user-images.githubusercontent.com/10054789/35370733-b3e35936-01ca-11e8-86cc-dd78e6aa03a7.png)
展示效果是这样子的，但是我操作第一个组件的编辑和删除的时候，他处理的数据是第二个组件的。请教下应该怎么做好一点。还是我哪里写的不对。

**Comment by ddcat1115** [comment]
@LKCheng 检查下 data 的控制，两个 table 共用了一个数据？

**Comment by ddcat1115** [comment]
refactor in https://github.com/ant-design/ant-design-pro/commit/33ef0adad6c59d4af70632c87e6bf9cffe5949cd

**Comment by LKCheng** [comment]
![f933a0fb-224f-4584-b44f-c3dc69fef622](https://user-images.githubusercontent.com/10054789/35398209-551a9088-022c-11e8-8a54-9704bf82c5c2.png)
可能是共用了同个数据，
对React 不是很熟, 用了比较笨的方法～，外面再套了一个空壳组件
公司赶着项目就直接上手了pro了
组件是用你们写好的那个TableForm.js 这个，这个带有操作的一些功能，是否能和上面的那个组件（StandardTable ）进行融合呢？

**Comment by ddcat1115** [comment]
StandardTable 只是在基础 Table 之上封装了一些提示信息，基本用法和 Table 差不多

**Comment by jessica1127** [comment]
> ![image](https://user-images.githubusercontent.com/10054789/35370720-80bb69cc-01ca-11e8-8d5d-09b15e01156c.png)
> 我把columns 提出来了，其他的没有动
> ![image](https://user-images.githubusercontent.com/10054789/35370733-b3e35936-01ca-11e8-86cc-dd78e6aa03a7.png)
> 展示效果是这样子的，但是我操作第一个组件的编辑和删除的时候，他处理的数据是第二个组件的。请教下应该怎么做好一点。还是我哪里写的不对。

请问 在一个page里面两个card的standardTable 怎么分别传入data呢？

**Comment by LKCheng** [comment]
加参或者传对象不就可以嘛？不就是传参吗
