### ISSUE TITLE
区块总是不好用各种问题，安装全部区块要不是卡住，要不就是报错，安装单个也不行

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5130]
![image](https://user-images.githubusercontent.com/30397655/63334384-e3ab0b80-c36d-11e9-9569-8739aa24aa2a.png)

**Comment by chenshuai2144** [comment]
这个是因为 cnpm 与 npm 不兼容造成的。试试最新的 tyarn 吧

**Comment by leshalv** [comment]
使用了tyarn在公司机器可以安装全部区块，但在个人电脑不可以，到某一个区块就会卡主，一晚上也不会好，不知道是什么原因，网络还是电脑配置？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-cli#readme

用这个打开 debug 试试，会输出所有错误

**Comment by DusuWen** [comment]
同样无法安装
![image](https://user-images.githubusercontent.com/15500093/63408336-59bc7a80-c421-11e9-9f57-c2f5777b2ca5.png)

**Comment by chenshuai2144** [comment]
把报错信息贴出来吧。不要用图片

**Comment by DusuWen** [comment]
@chenshuai2144 好的
```
C:\Users\xxx\WebstormProjects\antd-pro-demo>npx umi block add UserLogin --js --path=/user/login
√ �  Parse url and args
× �  clone git repo from https://github.com.cnpmjs.org/ant-design/pro-blocks.git
×  error     Error: Error: Command failed: git clone https://github.com.cnpmjs.org/ant-design/pro-blocks.git github.com/ant-design/pro-blocks --single-branch --recurse-submodules -b master
Cloning into 'github.com/ant-design/pro-blocks'...
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining


    at C:\Users\xxx\WebstormProjects\antd-pro-demo\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:345:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (C:\Users\xxx\WebstormProjects\antd-pro-demo\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:41:103)
    at _throw (C:\Users\xxx\WebstormProjects\antd-pro-demo\node_modules\umi-build-dev\lib\plugins\commands\block\util.js:43:291)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by chenshuai2144** [comment]
@DusuWen   试着增加  --closeFastGithub

**Comment by DusuWen** [comment]
@chenshuai2144 卡在这一行不动了，试过挂梯子也还是这样
```
C:\Users\xxx\WebstormProjects\antd-pro-demo>npx umi block add UserLogin --js --path=/user/login --closeFastGithub
√ �  Parse url and args
\ �  clone git repo from https://github.com/ant-design/pro-blocks.git
```

**Comment by chenshuai2144** [comment]
梯子挂不到命令行上面的。

**Comment by DusuWen** [comment]
@chenshuai2144 那么应该就是我这边的网直连github有问题，所以一直处于等待状态了

**Comment by nicecp** [comment]
解决办法：
step1: 把GITHUB的antdesign/pro-blocks地址，放到国内的托管平台
step2: 修改配置GIT仓库地址 _/config/config.js_
`
block: {
    defaultGitUrl: 'https:// xxxxx',
  }
`

> `defaultGitUrl`是仓库地址，不完全是url地址

step2: umi block list

**Comment by afc163** [comment]
@chenshuai2144 gitee 同步一个镜像也是个解决方案。

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/63424617-6cdf4280-c441-11e9-9478-5de044ce67dd.png)
控制台报这个错

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/20c598d03d2cff98a21ab4c5eb6a6a0b8dd0a93b

来了，家里试了一下速度还行 12分钟安装完成

**Comment by DusuWen** [comment]
@chenshuai2144 可以安装了，谢谢

**Comment by chenshuai2144** [comment]
@DusuWen 时间花了多久？

**Comment by DusuWen** [comment]
@chenshuai2144 我只安装了login区块，大概2分钟不到

**Comment by chenshuai2144** [comment]
还是有点长。npm 也慢

**Comment by chengzequn** [comment]
js的是不行，不过ts的可以，我已经完全把ts的区块都下载下来了
