### ISSUE TITLE
BasicLayout布局中的Ant Design ProAnt Design Copyright  2019 蚂蚁金服体验技术部出品 这几句话怎么去掉了

### ISSUE THREAD

**Issue by EvalGitHub** [ant-design/ant-design-pro#5133]

**Comment by chenshuai2144** [comment]
footerRender

https://github.com/ant-design/ant-design-pro/blob/d70ac0952b7c21b15ec26e504be86bc42c88730e/src/layouts/BasicLayout.tsx#L128
