### ISSUE TITLE
使用webstorm发现报了很多错误

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5134]
![image](https://user-images.githubusercontent.com/30397655/63399848-71393a80-c404-11e9-81b1-b5d54d23bece.png)
![image](https://user-images.githubusercontent.com/30397655/63399889-8dd57280-c404-11e9-9f4b-0ebd027fc841.png)

**Comment by chenshuai2144** [comment]
提升一下 ts 的版本 更新你的依赖

**Comment by leshalv** [comment]
升级版本为 @3.5.3 之后，这里还是报错
![image](https://user-images.githubusercontent.com/30397655/63401593-6e414880-c40a-11e9-9e09-cf36389ac1b2.png)

**Comment by Wmstone** [comment]
@leshalv 你好，请问你解决了么
