### ISSUE TITLE
提示缺少umi/locale 安装不成功

### ISSUE THREAD

**Issue by D-KaiDi** [ant-design/ant-design-pro#5135]
在运行一个项目的时候 npm start 提示错误 具体如图
![image](https://user-images.githubusercontent.com/44960282/63400957-418c3180-c408-11e9-8433-4240f40509ef.png)
当我按照提示 npm install --save umi/locale时 不停的让我登录GitHub 然后还下载失败
![image](https://user-images.githubusercontent.com/44960282/63401042-8adc8100-c408-11e9-9e82-79e008d02ab8.png)
![image](https://user-images.githubusercontent.com/44960282/63401063-a182d800-c408-11e9-994c-bd8b6cdce0bd.png)

**Comment by afc163** [comment]
Try https://github.com/cnpm/cnpm

`rm -rf node_modules && cnpm install`

**Comment by chenshuai2144** [comment]
推荐 [tyarn](https://www.npmjs.com/package/tyarn) 吧。
cnpm 黑科技有点多

**Comment by D-KaiDi** [comment]
@afc163 
![image](https://user-images.githubusercontent.com/44960282/63406486-a782b400-c41c-11e9-88e7-a5b21d00a9a5.png)
还是不可以

**Comment by chenshuai2144** [comment]
`import { FormattedMessage } from 'umi-plugin-react/locale';`
这样呢？

**Comment by D-KaiDi** [comment]
@chenshuai2144  谢谢您 按照您的方法解决了
