### ISSUE TITLE
手机端打开会报错

### ISSUE THREAD

**Issue by monoshizuka** [ant-design/ant-design-pro#5136]
![Uploading Screenshot_2019-08-21-14-46-50-986_com.android.br.jpg…]()
不清楚什么bug有点头疼

**Comment by monoshizuka** [comment]
图片上传出问题了,我再上传一下

![Screenshot_2019-08-21-14-46-50-986_com android br](https://user-images.githubusercontent.com/26546536/63409210-4b6f5e00-c423-11e9-8595-6133e14da728.jpg)

**Comment by monoshizuka** [comment]
电脑端打开和手机微信打开是正常的,用安卓手机自带的浏览器打开就会这样

**Comment by chenshuai2144** [comment]
他已经给了你方案了。加一个 Polyfill 即可。
https://www.npmjs.com/package/react-intl-polyfill
