### ISSUE TITLE
Warning: pro-layout: onCollapse and collapsed should exist simultaneously

### ISSUE THREAD

**Issue by pl2476** [ant-design/ant-design-pro#5138]
在BasicLayout  即使都写上  但是还是会有⚠️
![image](https://user-images.githubusercontent.com/20450069/63415433-52e93400-c430-11e9-8e27-fc1a0982076a.png)
![image](https://user-images.githubusercontent.com/20450069/63415679-ace9f980-c430-11e9-9863-cddf0aa4aeea.png)

**Comment by chenshuai2144** [comment]
升级最新的layout即可。

**Comment by lpx7788** [comment]
升级了  "@ant-design/pro-layout": "^4.6.2", 也是报错  index.js:1 Warning: pro-layout: onCollapse and collapsed should exist simultaneously
