### ISSUE TITLE
多种角色共用登录页面，登录后进入各自的BasicLayout应如何配置路由？

### ISSUE THREAD

**Issue by yaochenkun** [ant-design/ant-design-pro#514]
目前在开发中的需求是有管理员和普通用户两种角色，他们共用登录、注册、密码找回页面，但登录后，则跳转到各自的首页（BasicLayout）中。但我在nav.js配置路由时，无论怎么修改都无法达到想要的效果，求问如何才能实现这个功能呢？

**Comment by wunayou** [comment]
路由改以后太坑了  完全不好扩展 

跳转发现的时候  1、只在登陆的时候 那直接 push根据不同的地址 push不同的地址就可以了
如果直接进来\这个地址 那就是重定向你地址 
在 BasicLayout 这个文件里面
```
  <Redirect exact from="/" to="/需要地址" />
```
然后你只需要知道你的数据怎么对应的就可以了

**Comment by chenshuai2144** [comment]
你为什么不在主页上维护一个判断.
登录之后不同的角色,跳转到不同的地方
