### ISSUE TITLE
SelectLang改变语言，AvatarDropdown下拉内容没有变化，目前在预览网站也是如此

### ISSUE THREAD

**Issue by pl2476** [ant-design/ant-design-pro#5143]
![image](https://user-images.githubusercontent.com/20450069/63483727-ede51b00-c4cf-11e9-87c4-eff7fd1bb4c2.png)

![image](https://user-images.githubusercontent.com/20450069/63483946-90050300-c4d0-11e9-9625-0ccfa65e1e93.png)

应该是个bug，但是检查AvatarDropdown ， 里面用的FormattedMessage没问题  ？

**Comment by pl2476** [comment]
![image](https://user-images.githubusercontent.com/20450069/63484141-40730700-c4d1-11e9-9ae5-f7039372ee84.png)
可以使用reload解决  但是毕竟不是特别好

**Comment by chenshuai2144** [comment]
AvatarDropdown 不在 context 中导致的。lang 改变会触发 context render

**Comment by GanJiaJia** [comment]
> ![image](https://user-images.githubusercontent.com/20450069/63484141-40730700-c4d1-11e9-9ae5-f7039372ee84.png)
> 可以使用reload解决 但是毕竟不是特别好

<Selectlang  render = { ()=> null }/>
触发一下render就好了

**Comment by chenshuai2144** [comment]
@GanJiaJia  来个 pr？

**Comment by Malarkey-Jhu** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/36290564/65030840-d8e69500-d972-11e9-8e5c-0eb42f3d56e9.png)
./form/guest/index.jsx 的子组件 （props.children）
似乎也拿不到
context丢失了吗？

**Comment by Malarkey-Jhu** [comment]
试了一下
发现好像是dva的问题
dva connect 拿掉后 就正常了
因为自己的页面也遇到同样问题

**Comment by chenshuai2144** [comment]
fixed
