### ISSUE TITLE
如何关闭CSS Modules

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design-pro#5144]
请问如何可以关闭默认的CSS Modules

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/ad5db1c268100735b5d99624aa75a5cd1be56e2c/config/config.ts#L145

 modules: false 即可

**Comment by overcastsky** [comment]
我尝试将modules: false，并且重新启动服务，然而所有的使用CSS Module的样式依然生效

**Comment by overcastsky** [comment]
是否还需要在修改其他的配置
