### ISSUE TITLE
 problem: react hooks 

### ISSUE THREAD

**Issue by hkl921010** [ant-design/ant-design-pro#5146]
Using DVA to report errors in react hooks in antd-deisgn-pro

![image](https://user-images.githubusercontent.com/23328281/63514721-cfa50c80-c51b-11e9-8c41-47be706f1811.png)

### error！
![image](https://user-images.githubusercontent.com/23328281/63514755-e8adbd80-c51b-11e9-97cb-c1a4aebdf5d0.png)

**Comment by hkl921010** [comment]
![image](https://user-images.githubusercontent.com/23328281/63514970-5b1e9d80-c51c-11e9-8458-43d9218b3c5f.png)

**Comment by chenshuai2144** [comment]
All the code?
