### ISSUE TITLE
切换账号登录,菜单没有根据权限变化,需要刷新才会变化,如何解决?

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5147]
看了之前有解决方案是在BasicLayout组件里面
通过dispatch({
    type: 'menu/getMenuData',
    payload: {routes, path, authority}
});解决.
我在v4版本里面添加了但是没有办法解决.
而且全局搜索了 modal 里面也没有 getMenuData 这个方法.
请教下该如何解决这个问题?

**Comment by z-lionel** [comment]
经过测试, 在BasicLayout组件的useEffect里面加上下面的方法就可以解决了

import { reloadAuthorized } from '@/utils/Authorized';
reloadAuthorized();

**Comment by valley3405** [comment]
在src/pages/user/login/model.ts的*login函数里加上
reloadAuthorized();
其实对比一下v2的文件就知道了。。。

**Comment by KaierChou** [comment]
> 在src/pages/user/login/model.ts的*login函数里加上
> reloadAuthorized();
> 其实对比一下v2的文件就知道了。。。
感谢.
新版本可以在src/models/login.ts下修改
