### ISSUE TITLE
@umi/fabric 缺少依赖？

### ISSUE THREAD

**Issue by fishenal** [ant-design/ant-design-pro#5148]
从v1升级的项目，lint参考最新的项目引用@umi/fabric作为配置文件，但是安装过后的问题是，lint跑不通，因为umi/fabric里引用的依赖不存在，比如eslint-config-prettier这种，需要全部在自己的项目里跑一边yarn add 才可以使用，而安装前yarn list里是存在这个包的，run lint的时候却找不到，是什么原因造成的?

**Comment by chenshuai2144** [comment]
你的lint怎么写的？和pro的一样吗？

**Comment by fishenal** [comment]
eslint版本问题，还原成"eslint": "5.16.0",不会报错，升级到eslint:  ^6.1.0 会报依赖错误，原因不明。。。。
