### ISSUE TITLE
global.less 如何覆盖 antd的默认样式

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#5152]
在global中修改了默认字体，结果被antd默认的样式覆盖掉了，请问各位大佬应该如何写
![image](https://user-images.githubusercontent.com/44694221/63611758-31926e80-c60f-11e9-9e41-053d2913ecd6.png)

![image](https://user-images.githubusercontent.com/44694221/63611721-1b84ae00-c60f-11e9-89c2-65b63993abdc.png)

**Comment by chenshuai2144** [comment]
`html body{ .. . }`
提升一下优先级即可
