### ISSUE TITLE
请教：request带上Authorization信息只有手动刷新了才生效

### ISSUE THREAD

**Issue by diangong** [ant-design/ant-design-pro#5154]
在登录后 LoginModal的reducers中，将服务端返回的Authorization存入sessionStorage。
在request.js中
```
const options: RequestOptionsInit = {
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  headers: {
    Authorization: `Bearer ${sessionStorage.getItem('Authorization‘）}`  // 统一的headers
  },
};
const request = extend(options);
```
需要手动刷新，才能在SecurityLayout 和BasicLayout里面fetchCurrent时带上Authorization信息。

**Comment by diangong** [comment]
在SecurityLayout中fetchCurrent时还判断sessionStorage.getItem('Authorization‘）存在
···
    if (sessionStorage.getItem('Authorization') && dispatch) {
      dispatch({
        type: 'user/fetchCurrent',
      });
    }
···

**Comment by diangong** [comment]
解决了。要在request.interceptors.request.use()中添加headers

**Comment by duxiaojiao** [comment]
和我遇到的问题一模一样，这个全局设置不好用，包括添加request的前缀也是有问题的。

**Comment by iceberg211** [comment]
request.interceptors.request.use((url, options) => ({
  options: {
    ...options,
    headers: {
      Authorization: jwt(),
    },
  },
}))

这样才可以

**Comment by iceberg211** [comment]
```
request.interceptors.request.use((url, options) => ({
  options: {
    ...options,
    headers: {
      Authorization: jwt(),
    },
  },
}));
```

这样才可以
