### ISSUE TITLE
请问tree控件,如何自定义展开/折叠图标?switcherIcon这个如何使用?

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5157]
如题,有没有例子,具体如何使用?谢谢!

**Comment by xiaohuoni** [comment]
https://ant.design/components/tree-cn/#components-tree-demo-customized-icon
是这个吗？

**Comment by z-lionel** [comment]
> https://ant.design/components/tree-cn/#components-tree-demo-customized-icon
> 是这个吗？

是这个, 想自定义展开和收缩的图标,我看api是用 switcherIcon标签, 
要传 React.ReactElement 这个类型.
但是具体怎么写? 
请教下,您知道吗?

**Comment by chenshuai2144** [comment]
React.ReactElement  就是任意一个 react 的实例对象。官方 demo是有写的。
