### ISSUE TITLE
Select 组件 initialValue 不能为数字，否则下拉框默认值直接显示为数字，而不是对应的label。

### ISSUE THREAD

**Issue by softshield** [ant-design/ant-design-pro#5158]
Select 组件 initialValue 不能为数字，否则下拉框默认值直接显示为数字。
是否特意这样设计？还是属于bug？

**Comment by chenshuai2144** [comment]
你输入数字显示数字有什么问题吗？

**Comment by softshield** [comment]
> 你输入数字显示数字有什么问题吗？你的期望是什么？

比如： value=0对应‘选项1’，value=1对应'选项2'；
我期望的是initialValue=0时，显示'选项1'，而不是显示 0。

但是value为字符串时显示正常，例：
 value=‘0’对应‘选项1’，value='1'对应'选项2'时；
initialValue=‘0’，会正常显示'选项1'。

**Comment by chenshuai2144** [comment]
你确定两个要相同的 option 的 key 和 value。这种问题一般是 number 和 string 造成的。
来个重现

**Comment by softshield** [comment]
> 你确定两个要相同的 option 的 key 和 value。这种问题一般是 number 和 string 造成的。
> 来个重现

```
 const option = {
  0: '选项0',
  1: '选项1',
  2: '选项2',
}
```
`  <Form.Item label="测试Select"  {...formItemLayout} >
              {getFieldDecorator('price', {
                initialValue: 0,
              })(<Select
                placeholder="请选择">
                {Object.keys(option).map((key, index) => {
                  return <Option value={key} key={index}>{option[key]}</Option>
                })}
              </Select>)}
            </Form.Item>`


![image](https://user-images.githubusercontent.com/24540701/63756827-9d185c80-c8eb-11e9-9262-69b73cad1010.png)

**Comment by secreter** [comment]
也遇到这个问题了

**Comment by chenshuai2144** [comment]
用 string 吧，不要用 number

**Comment by Yin-Jie** [comment]
用数字作为object的key，会默认转为字符串啊
