### ISSUE TITLE
getAuthority()中异步请求权限问题

### ISSUE THREAD

**Issue by ArcherNG** [ant-design/ant-design-pro#5161]
getAuthority()中注释有权限可由后台获取  具体该怎么做   请大佬赐教  自己请求之后  传到AuthorizedRouter中的currentAuthority参数都是Promise(pending)

**Comment by chenshuai2144** [comment]
aw你的代码出来看看

**Comment by ZuhuaLiu** [comment]
我也是遇到这种问题，异步函数返回的都是promise，改成同步的了
