### ISSUE TITLE
业务问题报错,修改完自动刷新页面会卡住

### ISSUE THREAD

**Issue by 15980131262** [ant-design/ant-design-pro#5163]
例如我的页面上写一个未定义的变量导致页面会报错(到这里都只是我自己的业务代码问题),那么这时我去修正我的业务代码, 修改完之后ant-design-pro 会自动刷新一下浏览器, 但这时,浏览器刷新就会卡住,一直在那加载导致无法刷新的问题, 发现 ant-design-pro v1 和v2 均无该问题,  目前使用了V4 就有这个问题

**Comment by chenshuai2144** [comment]
v2 和 v4 都是 umi 提供一下最小重现吧！
