### ISSUE TITLE
最新版的npm install时出错  antd-with-locales.min.js这个下不下来

### ISSUE THREAD

**Issue by ray-toby** [ant-design/ant-design-pro#5164]

**Comment by ray-toby** [comment]
![1566896037](https://user-images.githubusercontent.com/19220426/63756757-7ce89d80-c8eb-11e9-92ec-36a8f2d1fcdf.jpg)
用了管理员权限也是这样

**Comment by chenshuai2144** [comment]
权限不够
你要先删除一下这个 node_modules.然后在安装
