### ISSUE TITLE
业务图标使用 SVG Symbol 方式引入，typescript下代码报错如何处理？在线等，急。

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#5165]
![image](https://user-images.githubusercontent.com/33716687/63818758-1740f380-c975-11e9-98f7-2f53b82858ad.png)

这里推荐使用SVG Symbol 方式引入https://pro.ant.design/docs/biz-icon-cn，但是按照配置直接在代码中使用是报错的，希望完善一下文档，提供一下如何处理这种情况。新手感觉有点蒙，，不太懂这块，希望给解答一下，现在项目马上要用，比较紧急，多谢～

**Comment by chenshuai2144** [comment]
class to ClassName。
https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes 
先读一下这个， jsx 和 html 是不一样的
