### ISSUE TITLE
按照官方文档的说明，下载模版，报一堆warning

### ISSUE THREAD

**Issue by wuzhong1030** [ant-design/ant-design-pro#5166]
![image](https://user-images.githubusercontent.com/17229981/63819648-9e439b00-c978-11e9-883b-c8edd8d4d6e4.png)
![image](https://user-images.githubusercontent.com/17229981/63819665-b1566b00-c978-11e9-8378-9ce3cc7d7e70.png)

不知道是什么原因

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5014
