### ISSUE TITLE
BasicLayout.d.ts配置问题

### ISSUE THREAD

**Issue by kawaiiz** [ant-design/ant-design-pro#5169]
![image](https://user-images.githubusercontent.com/25151442/63842593-758ec600-c9b7-11e9-8a8f-4a8befe9ecd3.png)

这里的配置footerRender：引入的props不是从Footer里引入吗？
但是也没有报错，这让人有点头疼不知道为什么

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/d19bc783a3a465024e8143f9192e4693ea2ae3d1/src/layouts/BasicLayout.tsx#L49

这里有例子
