### ISSUE TITLE
The children of the Description component display an exception when the number 0 is displayed Error

### ISSUE THREAD

**Issue by Cuihongsen** [ant-design/ant-design-pro#517]
https://github.com/ant-design/ant-design-pro/blob/12d8b4079a89f41a1eea111be64d42802dd70a78/src/components/DescriptionList/Description.js#L12

**Comment by ddcat1115** [comment]
Maybe you have passed a Number to it...

proptypes added  https://github.com/ant-design/ant-design-pro/commit/d9d02c35736f36c3ce9eb7e3e228d4564dbeb4ef
