### ISSUE TITLE
登录成功后必须要刷新一下再登录才能通过权限校验

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design-pro#5172]
登录成功之后设置权限，代码如下
```javascript
localStorage.setItem(AUTHORITY, JSON.stringify(['admin']))
router.push('/')
```

renderAuthorize.tsx如下  
![image](https://user-images.githubusercontent.com/29008437/63907872-a3274e00-ca4f-11e9-9814-5d63ccee8c16.png)

因为renderAuthorize.tsx默认导出的CURRENT='NULL' ，所以当你重新设置权限，进入其它路由的时候，CURRENT还是等于'NULL' ，只有刷新页面重新执行CURRENT才会等于['admin']
![image](https://user-images.githubusercontent.com/29008437/63907851-96a2f580-ca4f-11e9-99c0-1839338528ef.png)

请问在登录后，如何刷新CURRENT的值

**Comment by Sayid1** [comment]
可以直接通过localStorage.getItem(AUTHORITY)获取CURRENT的值吗

**Comment by Sayid1** [comment]
已解决

**Comment by hVenus** [comment]
请问是怎么解决的？ @Sayid1

**Comment by Sayid1** [comment]
@hVenus 
设置权限后，重新加载权限，再跳到登录后的地址

```javascript
import { router } from 'umi'
import { setAuthority } from '@/utils/authority'
import { reloadAuthorized } from '@/utils/Authorized'


setAuthority('admin')
reloadAuthorized()
router.push('/')
```
