### ISSUE TITLE
执行完 npm run fetch:blocks后，user目录下无任何文件

### ISSUE THREAD

**Issue by jm200210** [ant-design/ant-design-pro#5178]
执行完 npm run fetch:blocks后，user目录下无任何文件
![image](https://user-images.githubusercontent.com/50350622/63931443-dbe31980-ca87-11e9-85bb-110ff5436c69.png)

**Comment by mytheshow** [comment]
我自己摸索的，折腾了一天：https://www.dayuzy.com/?p=481

1.自己手动下载https://github.com/ant-design/pro-blocks所有区块
2.将下载的文件解压拷贝到C:\Users\用户名.umi\blocks\github.com\ant-design\pro-blocks文件夹下
3.执行npm run fetch:blocks

**Comment by jm200210** [comment]
> 
> 
> 我自己摸索的，折腾了一天：https://www.dayuzy.com/?p=481
> 
> 1.自己手动下载https://github.com/ant-design/pro-blocks 所有区块
> 2.将下载的文件解压拷贝到C:\Users\用户名.umi\blocks\github.com\ant-design\pro-blocks文件夹下
> 3.执行npm run fetch:blocks

太赞了。终于可以了。
