### ISSUE TITLE
IE11报错

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design-pro#5179]
已配置targets: { ie: 11 } 或 targets: { ie: 9 } 都不能解决问题
添加了一个插件
```javascript
[
    'umi-plugin-auto-externals',
    {
      packages: ['antd', 'react', 'react-dom', 'moment'],
    },
],
```

![image](https://user-images.githubusercontent.com/29008437/63933157-43e72f00-ca8b-11e9-960f-5f4aea614d2f.png)

**Comment by chenshuai2144** [comment]
尝试不要 externals 吧。这个插件引入的 umd 的兼容性有点问题
