### ISSUE TITLE
models/chart.js has repeat data

### ISSUE THREAD

**Issue by sunchenguang** [ant-design/ant-design-pro#518]
i find in `models/chart.js`, reducers -> clear method return data is totally repeat this model file's initial state.
if someday initial state add a property, then you need add it in clear method too.

if we can extract inital state to a const variable, then in clear method return it directly

```
const initialState = {
    visitData: [],
    visitData2: [],
    salesData: [],
    searchData: [],
    offlineData: [],
    offlineChartData: [],
    salesTypeData: [],
    salesTypeDataOnline: [],
    salesTypeDataOffline: [],
    radarData: [],
    loading: false,
  }

...

 clear() {
  return initialState
}


```

**Comment by nikogu** [comment]
The `clear` means reset all state in this models ? This can be customized, it is depend on your scene.
