### ISSUE TITLE
点击侧边栏，菜单会自动收缩

### ISSUE THREAD

**Issue by fenghuolibie** [ant-design/ant-design-pro#5180]
我用ant design pro搭建的点击侧边栏出现菜单收缩

**Comment by fenghuolibie** [comment]
> 
> 
> 我用ant design pro搭建的点击侧边栏出现菜单收缩

**Comment by xiaohuoni** [comment]
给个图如何？

**Comment by fenghuolibie** [comment]
嗯，是配置的问题，已经解决，github用的不太熟哈，抱歉，谢谢了




------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 下午2:23
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>; 
抄送: "游少军"<2302470731@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] 点击侧边栏，菜单会自动收缩 (#5180)




给个图如何？

**Comment by xiaohuoni** [comment]
好的
