### ISSUE TITLE
start antd pro programmatically

### ISSUE THREAD

**Issue by linonetwo** [ant-design/ant-design-pro#5181]
Seems currently the only way to start antd pro is via `umi dev`, but I want to start project programmatically in a test environment.

For CRA, we can:

```jsx
import App from '../../src/App';
When('I shallow render a React component called: App', function () {
    this.wrapper = shallow(<App />);
});
```
https://github.com/NguyenAndrew/Enzyme-Cucumber-React/blob/master/features/step_definitions/stepdefs.js

But, how to run ANtdPro programmatically?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/tree/master/tests
look here
