### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#5182]
css integration issue

**Comment by ShawDanon** [comment]
if you provide a mini GitHub repository which can reproduce the issue.
I'm glad to help you.

**Comment by ShawDanon** [comment]
> My antdesign version is 2.2.1
> In global.less file i am importing my css file as mentioned below
> @import '~antd/lib/style/themes/default.less';
> 
> .mynamespace {
> @import (less) '~my-css/dist/my-style.css';
> }
> 
> **Note:- My style.css has one of its variable called root which defined as :root{--base-font-size:1rem;etc} ,**
> ERROR Failed to compile with 1 errors
> 
> error in ./src/global.less
> 
> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
> ------------------here it load all css contents....................................
> ^
> Unrecognised input. Possibly missing opening '{'
> in /home/abc/Desktop/AntDesign/frontend-master/Myapp/node_modules/my-css/dist/my-style.css (line 1,column 1017)
> at runLoaders (/home/abc/Desktop/AntDesign/frontend-master/Myapp/node_modules/webpack/lib/NormalModule.js:313:20)
> at /home/abc/Desktop/AntDesign/frontend-master/Myapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
> at /home/abc/Desktop/AntDesign/frontend-master/Myapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
> at context.callback (/home/abc/Desktop/AntDesign/frontend-master/SMyapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
> at processTicksAndRejections (internal/process/next_tick.js:81:5)
> 
> @ ./src/pages/.umi/umi.js 205:0-28
> @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.
> 
> Kindly help to resolve this issue

if you provide a mini GitHub repository which can reproduce the issue.
I'm glad to help you.

**Comment by ShawDanon** [comment]
if you provide a mini GitHub repository which can reproduce the issue.
I'm glad to help you.

**Comment by THARAKS** [comment]
I have resolved this issue by myself
