### ISSUE TITLE
修改localStorage的antd-pro-authority即可实现拥有菜单权限

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design-pro#5187]
![image](https://user-images.githubusercontent.com/4182865/64021725-2edfce00-cb67-11e9-8036-67b6afe729ef.png)
如图手动修改localStorage的antd-pro-authority增加原本没有的菜单权限，刷新页面变拥有了未授权的菜单权限，请问如何解决这个问题？

**Comment by huntdream** [comment]
重新拉取一遍权限列表更新就好了吧

**Comment by wuqingabc** [comment]
他说的这个是安全问题吧？

**Comment by huntdream** [comment]
即便前端进入没有权限的页面，但是根本调不动对应的接口(前提是后端接口做了权限)。这种情况感觉算是一个用户体验的问题，但是真正的用户并不会在localStorage里面去修改前端权限。想要处理这种情况，无非是让前端权限和后端保持同步。重新刷新页面会导致所有组件重新挂载，所以在最外层组件挂载的时候获取权限更新到localStorage里面覆盖

**Comment by wzlee** [comment]
@huntdream 确实，后端接口需要加权限校验，并且刷新页面也要从后端根据权限拉取菜单

**Comment by chenshuai2144** [comment]
前端只能展示。具体的权限还是要后端控制的。前端的输入是不可信的。
