### ISSUE TITLE
我想知道pro_layout的运行过程，调用过程，权限原理。

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#5188]
我想知道pro_layout的运行过程，比如入口是哪写方法，文件加载的过程，以及权限验证的过程，不知道有没有详细的文档描述？

**Comment by BassWeb** [comment]
没有

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro-layout
现在可以在这里看看
