### ISSUE TITLE
通过setFieldsValue设置动态增减表单项的值

### ISSUE THREAD

**Issue by mineMineGo** [ant-design/ant-design-pro#5189]
只是代码分享，非原创，转载地址
https://segmentfault.com/q/1010000011282399/a-1020000011288415
如有侵犯，及时联系删帖。

如下结构 
{keys.map((k, index) => {
                        return (
                            <div className="formSelect relatePaper">
                                <FormItem>
                                    {getFieldDecorator(`paperId-${k}`, {
                                        initialValue: ''
                                    })(
                                        <Select showSearch style={{width: 200}}
                                                placeholder="请输入试卷名称"
                                        >
                                            <Option value="">--请选择--</Option>
                                            {
                                                !this.props.examPapers ? "" : this.props.examPapers.map(examPaper =>
                                                    <Option key={examPaper.id}
                                                            value={examPaper.id}>{examPaper.paperName}</Option>)
                                            }
                                        </Select>
                                    )}
                                </FormItem>
                            </div>
                        );
                    })
                }
通过 setFieldsValue 动态更新  `paperId-${k}` 的值方式如下：

setFieldsValue（{ ["name"+(()=>变量)()]： 值}）

亲测可以

**Comment by chenshuai2144** [comment]
太黑了，不推荐官方使用。
