### ISSUE TITLE
如何关闭国际化功能呢？concole老是提示[React Intl] Missing message: "menu.首页" for locale: "zh-CN", using default message as fallback.

### ISSUE THREAD

**Issue by fenghuolibie** [ant-design/ant-design-pro#5191]

**Comment by fenghuolibie** [comment]
希望有人回答

**Comment by fenghuolibie** [comment]
[React Intl] Missing message: "menu.首页.信息表" for locale: "zh-CN", using default message as fallback.

**Comment by fenghuolibie** [comment]
@xiaohuoni

**Comment by fenghuolibie** [comment]
@fifsky

**Comment by Hansuku** [comment]
直接执行`npm run i18n-remove`并且在 config.ts 关闭 locale

**Comment by fenghuolibie** [comment]
> 
> 
> 直接执行`npm run i18n-remove`并且在 config.ts 关闭 locale

你能说下如何在config.ts关闭的细节么

**Comment by fenghuolibie** [comment]
> npm run i18n-remove

感谢！！！方法相当正确，先去除相关js包，再关闭

**Comment by lijinghuatongxue** [comment]
> > npm run i18n-remove
> 
> 感谢！！！方法相当正确，先去除相关js包，再关闭
请问是在哪里关闭呢，我的报错是这个
![image](https://user-images.githubusercontent.com/17118790/70380374-6b487480-1975-11ea-9ab5-0c98237953ac.png)

**Comment by fenghuolibie** [comment]
> 
> 
> > > npm run i18n-remove
> > 
> > 
> > 感谢！！！方法相当正确，先去除相关js包，再关闭
> > 请问是在哪里关闭呢，我的报错是这个
> > ![image](https://user-images.githubusercontent.com/17118790/70380374-6b487480-1975-11ea-9ab5-0c98237953ac.png)

![图片](https://user-images.githubusercontent.com/37245814/70418792-0db04700-1a9f-11ea-9d47-a3b2f1e4fd65.png)

**Comment by fenghuolibie** [comment]
> 
> 
> > > npm run i18n-remove
> > 
> > 
> > 感谢！！！方法相当正确，先去除相关js包，再关闭
> > 请问是在哪里关闭呢，我的报错是这个
> > ![image](https://user-images.githubusercontent.com/17118790/70380374-6b487480-1975-11ea-9ab5-0c98237953ac.png)

我不知到怎么上传图片在/config/config.js文件里，找到local把它的属性设为{}，空对象就好了

**Comment by lijinghuatongxue** [comment]
> > > > npm run i18n-remove
> > > 
> > > 
> > > 感谢！！！方法相当正确，先去除相关js包，再关闭
> > > 请问是在哪里关闭呢，我的报错是这个
> > > ![image](https://user-images.githubusercontent.com/17118790/70380374-6b487480-1975-11ea-9ab5-0c98237953ac.png)
> 
> 我不知到怎么上传图片在/config/config.js文件里，找到local把它的属性设为{}，空对象就好了

直接command+c 然后 command+v 扔到框里面，等一会会自动加载

**Comment by fenghuolibie** [comment]
![1575879293(1)](https://user-images.githubusercontent.com/37245814/70419075-b3fc4c80-1a9f-11ea-9fd1-4c207445261e.png)

**Comment by lijinghuatongxue** [comment]
@fenghuolibie  我关闭了，还是有
![image](https://user-images.githubusercontent.com/17118790/70419497-8368e280-1aa0-11ea-8f7e-5bb881eb6b32.png)

**Comment by lijinghuatongxue** [comment]
@fenghuolibie 
![image](https://user-images.githubusercontent.com/17118790/70419585-b01cfa00-1aa0-11ea-97ee-e0e7d5fa049c.png)

**Comment by fenghuolibie** [comment]
![图片](https://user-images.githubusercontent.com/37245814/70419842-47824d00-1aa1-11ea-90e7-1c6af71b562f.png)

**Comment by fenghuolibie** [comment]
多找找，浅显的样式，我们开发是很容易找的

**Comment by fenghuolibie** [comment]
> 
> 
> @fenghuolibie
> ![image](https://user-images.githubusercontent.com/17118790/70419585-b01cfa00-1aa0-11ea-97ee-e0e7d5fa049c.png)

> 
> 
> @fenghuolibie
> ![image](https://user-images.githubusercontent.com/17118790/70419585-b01cfa00-1aa0-11ea-97ee-e0e7d5fa049c.png)

羡慕老哥有mac ，~。~

**Comment by lijinghuatongxue** [comment]
> > @fenghuolibie
> > ![image](https://user-images.githubusercontent.com/17118790/70419585-b01cfa00-1aa0-11ea-97ee-e0e7d5fa049c.png)
> 
> > @fenghuolibie
> > ![image](https://user-images.githubusercontent.com/17118790/70419585-b01cfa00-1aa0-11ea-97ee-e0e7d5fa049c.png)
> 
> 羡慕老哥有mac ，~。~

加我微信 lijinghua-1995

**Comment by tarami01** [comment]
![local](https://user-images.githubusercontent.com/22916431/75110747-1523cd00-5658-11ea-9408-00b2b2f0f94b.png)

**Comment by tarami01** [comment]
![local](https://user-images.githubusercontent.com/22916431/75110802-a8f59900-5658-11ea-954a-f8bcaaf0f5b2.png)

**Comment by tarami01** [comment]
> [React Intl] Missing message: "menu.首页.信息表" for locale: "zh-CN", using default message as fallback.

https://github.com/ant-design/ant-design-pro/issues/5191#issuecomment-590055670

**Comment by daisybaicai** [comment]
在将prolayout下的formatMessage删除掉就可以关闭菜单的国际化

![image](https://user-images.githubusercontent.com/25605435/149064870-774d2e54-6e02-49b5-a153-0ef6688e6562.png)
