### ISSUE TITLE
Nav Mode设置Top Menu Layout后通知icon默认白色不可见

### ISSUE THREAD

**Issue by bowenluo** [ant-design/ant-design-pro#5192]
Nav Mode设置Top Menu Layout后，将窗口宽度缩到最小，通知icon默认白色不可见

```
{
  "navTheme": "dark",
  "primaryColor": "#1890FF",
  "layout": "topmenu",
  "contentWidth": "Fixed",
  "fixedHeader": false,
  "autoHideHeader": false,
  "fixSiderbar": false,
  "menu": {
    "locale": true
  },
  "title": "Ant Design Pro",
  "pwa": false,
  "iconfontUrl": ""
}
```
![image](https://user-images.githubusercontent.com/3523754/64085094-b22a3b00-cd84-11e9-87b4-a4e68c0349d2.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/64507015-1b252c00-d30c-11e9-8761-7be4f8b1c751.png)

**Comment by bowenluo** [comment]
@chenshuai2144 图片是修复好了？还是不能复现？

**Comment by chenshuai2144** [comment]
不能复现？来个 demo?

**Comment by bowenluo** [comment]
@chenshuai2144 如图，设置后你再看看
![image](https://user-images.githubusercontent.com/3523754/64529557-50a73500-d35f-11e9-87b4-f0752756e8a6.png)

**Comment by chenshuai2144** [comment]
重现了， modal 模式应该直接用白色主题的，你设置为了白色模式可以暂时解决这个问题
