### ISSUE TITLE
umi block add 报错：copy to clipboard failed

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#5193]
![image](https://user-images.githubusercontent.com/51696361/64087455-c152be00-cd6f-11e9-9d80-ec6bf5481dd9.png)

**Comment by Benpaodejiezai** [comment]
大神帮帮忙

**Comment by chenshuai2144** [comment]
copy to clipboard 是要弄到剪切板上，是不影响正常功能。
感觉是没有控制剪贴板的权限造成的。直接忽略吧

**Comment by billypon** [comment]
@chenshuai2144 没有什么选项可以不要复制到剪贴板吗
