### ISSUE TITLE
TypeError: opts.remoteLog is not a function

### ISSUE THREAD

**Issue by GerryGe** [ant-design/ant-design-pro#5196]
Version: ant-design-pro v4
OS Version: Windows 10 (1809)

I follow the steps of https://pro.ant.design/docs/getting-started-cn
and when I ran "npx umi block add DashboardAnalysis --path=/dashboard/analysis"
to add block, I got below erros:
PS D:\Demo\ReactJS\antd> npx umi block add DashboardAnalysis --path=/dashboard/analysis
√ �  Parse url and args
×  error     TypeError: opts.remoteLog is not a function
    at D:\Demo\ReactJS\antd\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:234:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Demo\ReactJS\antd\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:128:103)
    at _next (D:\Demo\ReactJS\antd\node_modules\umi-build-dev\lib\plugins\commands\block\index.js:130:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)

![image](https://user-images.githubusercontent.com/6952917/64101963-89fd0500-cda1-11e9-892a-d0609a060cef.png)

**Comment by 1907** [comment]
me too，but I chose the block list command.

**Comment by sorrycc** [comment]
Fixed via umi@2.9.1 .

**Comment by GerryGe** [comment]
> Fixed via umi@2.9.1 .
Thanks, I had upgrade my umi, and fixed the issue,
but I still have two questions:
1. I ran "npx umi block add DashboardAnalysis --path=/dashboard/analysis", but the block folder is not the same with /dashboard/analysis, and below is my screenshot. How can I generate the same folder structure with the preview site.
2.add block succeed, but why the mutil-language doesn't work, how can I add the international also.

![image](https://user-images.githubusercontent.com/6952917/64107731-c0408180-cdad-11e9-960d-f3b00f51806e.png)
