### ISSUE TITLE
http://preview.pro.ant.design/ 退出会自动登录

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-pro#52]
http://preview.pro.ant.design/#/dashboard/analysis
退出了输入账号密码登录上再退出就会自动再次登录

**Comment by nikogu** [comment]
@qq645381995 pro 貌似没有登陆功能，都是 `ui` 演示，直接访问首页即可

**Comment by qq645381995** [comment]
@nikogu  不  有登录demo

**Comment by nikogu** [comment]
http://preview.pro.ant.design/#/user/login

这里可以再次访问..

**Comment by qq645381995** [comment]
@afc163 
能理解我说的吗 这个人不理解

**Comment by nikogu** [comment]
> pro 没有登陆功能

你可以自己看看代码：https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.js#L80

**Comment by afc163** [comment]
@qq645381995 来个 GIF 看看。

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/32164787-7d516d0e-bd9b-11e7-8956-6b80c4ebff17.gif)

重现了，Chome 下登录过一次并保存用户名密码后，在此进入这个页面会直接登录。

@ddcat1115 来看下。

**Comment by afc163** [comment]
@qq645381995 报告错误的时候多提供一些信息，可以减少误解，提高沟通效率。

**Comment by qq645381995** [comment]
@afc163 https://github.com/ant-design/ant-design-pro/pull/53  想写个pr的

**Comment by nikogu** [comment]
这个一开始是没有『登陆和登出』逻辑的（只有纯展示 UI），但是看起来大家默认是需要加上的，要不然确实是个 bug，这个我来加下好了 ＝。-

**Comment by qq645381995** [comment]
@ddcat1115 
我的问题 这又写了一个logout的tree 应该写在login里面的

**Comment by ddcat1115** [comment]
@qq645381995  是有点问题的，选择浏览器的『保存密码』之后才能重现，已经修复，预计今天晚些时候重新发下就 ok 了

**Comment by qq645381995** [comment]
@ddcat1115  我发现问题的是保存密码的，提测的是没保存密码的，我说我怎么调试成功了，弄的尴尬了，没看store数据
