### ISSUE TITLE
getFieldDecorator如何获取带有小数点的属性,key值,而不是嵌套结构?

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5200]
如题: 使用以下方法
getFieldDecorator('demo.id',  options };
获取的参数是: params = { demo: {id: value} };

request设置请求数据格式为 requestType: 'form'; 
得到的结果是: {demo: [object, object]};

而我想要的数据结构是这样: {demo.id : value};

请问我该如何设置getFieldDecorator的id, 通过什么方法转化数据格式?
而不是自己得到手动去转化.
才能得到我想要的数据格式,谢谢了.

**Comment by chenshuai2144** [comment]
在 antd@4 之前你可能需要自己手工去搞了。v3 不支持的

**Comment by HaiYoungs** [comment]
请问antd@4怎么解决

**Comment by H-xiaoyu** [comment]
@chenshuai2144 请问手工怎么搞呢？

**Comment by chenshuai2144** [comment]
在request 里面自己转化游戏啊

**Comment by H-xiaoyu** [comment]
> 在request 里面自己转化一下，写起来还是挺烦人的

就没有其他解决方法吗

**Comment by chenshuai2144** [comment]
没有的， v3 已经很久没有更新了

**Comment by H-xiaoyu** [comment]
搞不来，很烦，只能换v-model了
