### ISSUE TITLE
如何在v4版本中使用react-dnd、react-dnd-html5-backend？

### ISSUE THREAD

**Issue by Noa-p** [ant-design/ant-design-pro#5201]
如题。

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-plugin-dnd

**Comment by Noa-p** [comment]
插件配置：
`[
    'umi-plugin-dnd',
  ],`

npm start后报错：
> Plugin apply failed: ENOENT: no such file or directory, open '...\node_modules\umi-plugin-dnd\template\DragDropComponent.js'
> (node:5516) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '...\node_modules\umi-plugin-dnd\template\DragDropComponent.js'

**Comment by Noa-p** [comment]
我直接安装react-dnd、react-dnd-html5-backend，使用它的api，但不起作用
`import React, {Component} from 'react'
import { DndProvider, useDrag } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'

default export class Page extends Component {
          render() {
                   return (
                        <DndProvider backend={HTML5Backend}>
                                 <div>
                                        <Group />
                                 </div>
                        </DndProvider>
                   )
          }
}

function Group() {
        const [{ isDragging }, drag] = useDrag({
            item: { type: ItemTypes.IGRESS},
            collect: monitor => ({
                isDragging: !!monitor.isDragging(),
            })
        })
        return (
            <div style={...}></div>
        )
}`

**Comment by Noa-p** [comment]
我直接安装react-dnd、react-dnd-html5-backend，使用它的api，但不起作用
`import React, {Component} from 'react'
import { DndProvider, useDrag } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
default export class Page extends Component {
    render() {
        return (
            <DndProvider backend={HTML5Backend}>
                <div>
                    <Group />
                </div>
            </DndProvider>
        )
    }
}

function Group() {
    const [{ isDragging }, drag] = useDrag({
            item: { type: ItemTypes.IGRESS},
            collect: monitor => ({
                isDragging: !!monitor.isDragging(),
            })
        })
    return (
        <div style={...}></div>
    )
}`

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-plugin-dnd/v/0.0.4
上次修改完，发布失败了。

**Comment by pl2476** [comment]
正好要用到  但是配置插件后还是报错
![image](https://user-images.githubusercontent.com/20450069/64157890-1ffc6280-ce6a-11e9-8c77-9aafff32ede6.png)

**Comment by Noa-p** [comment]
我从插件引入DndProvider
`import { DndProvider } from 'umi-plugin-dnd' `
提示：
![image](https://user-images.githubusercontent.com/43284700/64159503-f264e880-ce6c-11e9-8017-1d1310d0bcf1.png)
我执行npm install @types/umi-plugin-dnd时报错：
![image](https://user-images.githubusercontent.com/43284700/64159633-1de7d300-ce6d-11e9-9efb-3608ab71c209.png)

**Comment by xiaohuoni** [comment]
[ 'umi-plugin-dnd' ] 这么用的嘛？我可以耶！

**Comment by Noa-p** [comment]
import { DndProvider } from 'umi-plugin-dnd'
import HTML5Backend from 'umi-plugin-dnd'

使用api的时候是这样引入的吗？

**Comment by xiaohuoni** [comment]
不用引入这些了，跳过这一步。这部分已经帮你使用了。你直接写拖动那部分的东西

**Comment by xiaohuoni** [comment]
这一步已经加了。
```
import HTML5Backend from 'react-dnd-html5-backend'
import { DndProvider } from 'react-dnd'

export default function MyReactApp() {
  return (
    <DndProvider backend={HTML5Backend}>
      /* your drag-and-drop application */
    </DndProvider>
  )
}
```
你直接写里面的就可以  /* your drag-and-drop application */

**Comment by pl2476** [comment]
安装umi-plugin-dnd后可以直接用了，config中也不需要添加插件了

**Comment by xiaohuoni** [comment]
config中要使用的吧？

**Comment by Noa-p** [comment]
DragDropContext好像过时了，react-dnd官方文档也没有这个api了
会报一个warning：

![image](https://user-images.githubusercontent.com/43284700/64498123-a3440b00-d2e5-11e9-844f-e27321171ce3.png)

**Comment by xiaohuoni** [comment]
最新版本没有了嘛？我用的是我之前的版本测试的。有空再看看，插件就几行代码，欢迎pr
