### ISSUE TITLE
add block international and menu structure cannot work

### ISSUE THREAD

**Issue by GerryGe** [ant-design/ant-design-pro#5203]
Version: ant-design-pro v4
OS Version: Windows 10 (1809)
umi: 2.9.1

I follow the steps of https://pro.ant.design/docs/getting-started-cn
and after I ran "npx umi block add DashboardAnalysis --path=/dashboard/analysis"
to add block, the menu structure change to below screenshot.
I have to queries:
1. How can I generate the same folder structure with the preview site(Dashboard→Analysis).
2. Add block succeed, but why the mutil-language doesn't work, how can I add the international supprort also.

![image](https://user-images.githubusercontent.com/6952917/64118110-867d7400-cdc9-11e9-9f60-eaf117cc0f26.png)

**Comment by GerryGe** [comment]
I don't want to change the config.ts manually! Can umi support add block to the same menu structure of preview site.

![image](https://user-images.githubusercontent.com/6952917/64119742-212b8200-cdcd-11e9-9fe6-fa0ce7ef1fb0.png)
 
After change the config.ts manually!
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
Blocks don't have their own names.
你还是需要自己配置
