### ISSUE TITLE
关于路由的两个问题

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#5204]
1.输入任何一个不存在的路由会显示 umi development 404 page，我看现在的preview页面已经改成antd的404组件了，请问怎么做的。
![Screenshot from 2019-09-03 10-19-07](https://user-images.githubusercontent.com/13537904/64139787-ae55f180-ce34-11e9-9bb3-c262292cc978.png)

2.做菜单权限的时候，我是把每个菜单叶子节点以字符串的形式存在数据库,如：'user-add'， config.ts保留完整的菜单json。
    用户登录后，拿到权限里面的菜单节点后，进入BasicLayout页面修改menuDataRender过滤config.ts里面的全量菜单，获取用户的真实菜单。
![Screenshot from 2019-09-03 10-28-54](https://user-images.githubusercontent.com/13537904/64140074-bc584200-ce35-11e9-8f3a-2374402a7a39.png)
  其中： authorities是从后端获取的菜单列表
问题： 左侧菜单是可以根据用户权限正确显示，但是其他非权限内的菜单还是可以输入url访问，貌似路由还是由的config.ts生成，请问应该怎么改

**Comment by huang714669** [comment]
第一个问题已经找到解决方案了，在config.ts每个routes数组最后面加上{‘component: './404'}就能重定向到404页面；

第二个问题，哪里可以动态修改routes对象？

**Comment by Noa-p** [comment]
pages/Authorized.tsx是控制页面权限的。config.ts的路由配置中有个Routes属性，它指定Authorized作为一个wrapper包裹页面，有权限就正确渲染页面，无权限则渲染noMatch中指定的页面。

这个和菜单是分开的，我当时做权限的时候也很懵。

官方文档：https://pro.ant.design/docs/authority-management-cn

**Comment by huang714669** [comment]
谢谢解答！
我们的权限管理是没有权限分组的概念的，每个用户注册的时候就要选择可以访问哪些菜单。
所以Routes: ['src/pages/Authorized'],和authorities字段我都没用上
想法也是比较简单粗暴，就是直接把不需要的route对象直接过滤掉，但是没有找到解决方案

**Comment by huang714669** [comment]
@Noa-p 原来在Authorized.tsx里面确实能动态修改routes
问题已经解决，多谢！

**Comment by BenlovedLamphere** [comment]
> @Noa-p 原来在Authorized.tsx里面确实能动态修改routes
> 问题已经解决，多谢！

大兄弟咋弄的能分享下代码吗
