### ISSUE TITLE
添加block时报错

### ISSUE THREAD

**Issue by v-wangjinjie** [ant-design/ant-design-pro#5208]
$ npx umi block add DashboardAnalysis --path=/dashboard/analysis

npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://cdn.npm.taobao.org/%40ant-design/icons-svg/-/%40ant-design/icons-svg-4.0.0-alpha.0.tgz failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\v-wangjinjie\AppData\Roaming\npm-cache\_logs\2019-09-03T08_04_04_950Z-debug.log
安装 umi@latest 失败，错误代码：1

**Comment by chenshuai2144** [comment]
重新安装一下吧。umi@laster 没有找到。
