### ISSUE TITLE
打开标签有实现吗?

### ISSUE THREAD

**Issue by kalsolio** [ant-design/ant-design-pro#5209]
增加打开的标签 这个有吗, 可以通过配置实现吗?
![image](https://user-images.githubusercontent.com/14342288/64170463-c3f20800-ce82-11e9-915f-43acf736c93a.png)

**Comment by zhaozhengyan** [comment]
https://github.com/sendya/ant-design-pro-vue   
vue 版本有实现这个功能，react版本的这个功能貌似没有了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/220
