### ISSUE TITLE
block add --layout 的问题

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design-pro#5210]
![image](https://user-images.githubusercontent.com/51696361/64172397-7fb53680-ce87-11e9-82fb-21c93580a15e.png)
block 作为 layout添加可以去掉 component 吗？因为把它作为一个文件夹，或父路由是没有对应文件的

**Comment by chenshuai2144** [comment]
--layout 也不行。component 必须要要存在的
