### ISSUE TITLE
npm run fetch:blocks无法下载下来

### ISSUE THREAD

**Issue by wangdejian163** [ant-design/ant-design-pro#5212]
几个小时了一直无法下载完毕，网络速度挺快的。中间失败一次，又重新下载卡在/exception/500,等了半个多小时不动。又重新下载还是无法下载下来。

**Comment by ZGINMADAO** [comment]
如果速度缓慢，可以尝试升级 umi 版本到最新，并在 config.ts 设置 block.defaultGitUrl 为 'https://gitee.com/ant-design/pro-blocks'。
