### ISSUE TITLE
修改国际化默认语言无效

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#5215]
修改config.ts，将默认语言改成en-US，没有效果，还是中文
locale: {
        // default false
        enable: true,
        // default zh-CN
        default: 'en-US',
        // default true, when it is true, will use `navigator.language` overwrite default
        baseNavigator: true,
      },

**Comment by ffalconjs** [comment]
将 baseNavigator 设置为 false 就可以了

**Comment by goalbased** [comment]
locale: {
        // default false
        enable: true,
        // default zh-CN
        default: 'zh-TW',
        // default true, when it is true, will use `navigator.language` overwrite default
        baseNavigator: false,
      },``
baseNavigator 設為false不起作用

**Comment by medmin** [comment]
你还要清除localstorage和cookie

**Comment by alexander-kinvic** [comment]
antd pro 5.2.0 依然存在这个问题。
