### ISSUE TITLE
路由守卫功能怎么实现？

### ISSUE THREAD

**Issue by shiliangchengdd01** [ant-design/ant-design-pro#5216]

**Comment by shiliangchengdd01** [comment]
引入react-router-dom 就run不起来了。

**Comment by wangxingkang** [comment]
在 布局文件里面做

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/SecurityLayout.tsx

看这里

**Comment by shiliangchengdd01** [comment]
不对，后面发现使用umi的prompt可以实现路由守卫功能。在页面离开的时候做一个自定义弹窗。
