### ISSUE TITLE
发布后settingDrawer的主题颜色切换不成功。

### ISSUE THREAD

**Issue by ZuhuaLiu** [ant-design/ant-design-pro#5217]
发布后settingDrawer的主题颜色切换不成功，有没有其他的解决方案？
![AI4Q5@E4O1_{49HZIMUYU4D](https://user-images.githubusercontent.com/40290781/64303587-6e6d4680-cfbb-11e9-9fe7-7cc9f118d2b9.png)

**Comment by chenshuai2144** [comment]
settingDrawer 修改颜色是需要 modal 配合的。
**https://github.com/ant-design/ant-design-pro/blob/a2192f5d57d934aa3e7a562f6d942907ee89a5a2/src/models/setting.ts#L34**

**Comment by ZuhuaLiu** [comment]
嗯嗯，开发环境是可以的，发布部署后就不行了

**Comment by ccbang** [comment]
有解决方案么? 我也遇到这个问题。开发环境这里有新的返回，build之后发布，这里就返回undefined
https://github.com/ant-design/ant-design-pro/blob/a2192f5d57d934aa3e7a562f6d942907ee89a5a2/src/components/SettingDrawer/themeColorClient.ts#L25
