### ISSUE TITLE
关于PageHeader 的优化建议

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#522]
在ant-design-pro 项目0.3.0 之前的 nav.js ,之后的 menu.js 中，name 为空时，就会不在左侧菜单栏中显示；但是这样有个问题出出现，在面包屑上就会直接使用 url `currentBreadcrumb.name || url,` ,这样出现的效果 如图：
![image](https://user-images.githubusercontent.com/12181423/34407377-1ae20d72-ebf9-11e7-9218-0b37711160c2.png)

所以建议现在 0.3.0 之后的版本中，面包屑额外的取值， 如：“breadcrumbName”
![image](https://user-images.githubusercontent.com/12181423/34407269-75d30f8e-ebf8-11e7-8c68-35dc1a99cb9c.png) 
![image](https://user-images.githubusercontent.com/12181423/34407413-48d5b33c-ebf9-11e7-929e-9c460fdb0ca1.png)

这样就不会 存在上述问题。

这个是我个人在实际项目中的修改，不知各位大神是否已经有了其他的处理方式。

**Comment by afc163** [comment]
这个问题在 master 上已经修复了。

https://github.com/ant-design/ant-design-pro/pull/440
