### ISSUE TITLE
load all locale file and build ts ✖  error

### ISSUE THREAD

**Issue by robinv8** [ant-design/ant-design-pro#5226]
错误：
![image](https://user-images.githubusercontent.com/12277531/64324275-a181fb00-cff8-11e9-812b-08bbc1f96752.png)
操作流程：
![image](https://user-images.githubusercontent.com/12277531/64324397-e6a62d00-cff8-11e9-8c62-16d013e2ee8c.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5118
看这里
