### ISSUE TITLE
三方包引用 antd 样式覆盖主题色问题

### ISSUE THREAD

**Issue by DelBlank** [ant-design/ant-design-pro#5228]
我在项目里使用了 uform 三方包，然后 uform 里面使用了 antd 的原始样式，导致我在配置项目全局主题色的时候，antd 的样式还是原始样式，没办法变成我想要的主题色。

这个问题有什么好的解决方案吗？

**Comment by chenshuai2144** [comment]
你引入 uform 的 less 文件就会覆盖掉的。
