### ISSUE TITLE
64位 win10 npm create umi 失败

### ISSUE THREAD

**Issue by will1989** [ant-design/ant-design-pro#5229]
`PS F:\FrontendProjects\MyDemo> npm create umi
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Files\nodejs\node_cache\_npx\11712" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\Program Files\nodejs\node_cache\_logs\2019-09-06T03_45_49_017Z-debug.log
安装 create-umi@latest 失败，错误代码：1`

已确认：文件夹是空的

**Comment by chenshuai2144** [comment]
`Could not install from "Files\nodejs\node_cache_npx\11712" as it does not contain a package.json file. `
已经告诉你为什么了。建议使用 `npx create umi`
