### ISSUE TITLE
v4 request 捕获不到400返回的内容

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design-pro#5230]
![13_43_36__09_06_2019](https://user-images.githubusercontent.com/20022163/64403774-65a86d80-d0ac-11e9-8519-3a12225f34a0.jpg)
上图中的绿色部分前端捕获不到

**Comment by chenshuai2144** [comment]
竟然不是个 json。有重现吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5168
估计是这个问题
