### ISSUE TITLE
请教大佬 ant  pro 中的图形编辑器能否实现编辑 bizcharts 展示的图例

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#5231]
目前使用bizcharts 实现了室内平面图， 想实现， 通过图形编辑器添加修改数据，请教图形编辑器能否实现？

**Comment by chenshuai2144** [comment]
可以的，这些图也是根据数据结构展示的。但是现在没有 直接用的解决方案，需要自己写
