### ISSUE TITLE
npm start呈现如下欢迎页面，内容显示出错

### ISSUE THREAD

**Issue by christinJiang** [ant-design/ant-design-pro#5232]
<img width="1548" alt="WeChat336a0b58d67fd4439c07c42f9fceb813" src="https://user-images.githubusercontent.com/12716802/64417028-e70ef880-d0ca-11e9-9de7-497df9164b64.png">

**Comment by afc163** [comment]
这是对的，就是这样的。

**Comment by christinJiang** [comment]
https://preview.pro.ant.design/dashboard/analysis
我想要呈现如上链接的页面，如何才能做到？

**Comment by christinJiang** [comment]
@afc163

**Comment by christinJiang** [comment]
@afc163 https://preview.pro.ant.design/dashboard/analysis
我想要呈现如上链接的页面，如何才能做到？

**Comment by afc163** [comment]
https://pro.ant.design/docs/block-cn
