### ISSUE TITLE
Has incorrect peer dependency

### ISSUE THREAD

**Issue by Dounx** [ant-design/ant-design-pro#5234]
这两个的版本是不是出错了，应当是 react@^16.8.4 以及 react-dom@^16.8.4 吧。

1. warning "umi-plugin-react > umi-plugin-dva > dva@2.6.0-beta.6" has incorrect peer dependency "react@^16.18.4".
2. warning "umi-plugin-react > umi-plugin-dva > dva@2.6.0-beta.6" has incorrect peer dependency "react-dom@^16.18.4".

复现步骤：
1. yarn create umi demo
2. Select Ant Design Pro
3. Select Javascript
4. cd demo && yarn

相关 issue: https://github.com/dvajs/dva/issues/2151

环境：
- create-umi@0.17.0
- macOS 10.14.3
- node v12.7.0
- yarn 1.17.3
- npm 6.10.0 

以及还有一些其他的 warning，这些 warning 对于应用没什么关系吧？

完整日志：https://gist.github.com/Dounx/a686f02a45eb5ab22e685e5be6753cc6
package.json: https://gist.github.com/Dounx/44ac805a7db767b45edeac19edf3c382

**Comment by chenshuai2144** [comment]
react-dom@^16.18.4 这个没法重现。很神奇。 dva 的仓库和 pro 的仓库中都没有 16.18.4

@types/react-dom 也没这么高de版本。

**Comment by Dounx** [comment]
> react-dom@^16.18.4 这个没法重现。很神奇。 dva 的仓库和 pro 的仓库中都没有 16.18.4
> 
> @types/react-dom 也没这么高de版本。

我在我两台电脑上使用上面的复现步骤都可以复现这个问题。

**Comment by Dounx** [comment]
> react-dom@^16.18.4 这个没法重现。很神奇。 dva 的仓库和 pro 的仓库中都没有 16.18.4
> 
> @types/react-dom 也没这么高de版本。

好像是 dva@2.6.0-beta.6 有的一个问题，在后续的版本已经修复，那现在使用的话应该怎么办？

**Comment by chenshuai2144** [comment]
先用 dva 的正式版本吧。
