### ISSUE TITLE
如何为复用的列表页面自动新建一个model

### ISSUE THREAD

**Issue by ZuhuaLiu** [ant-design/ant-design-pro#5236]
列表复用同一个页面时，model也是相同的，导致数据刷新时第二次会为上一个model下的值，如何自动为复用的页面新建一个model。

**Comment by jarrywen** [comment]
> 列表复用同一个页面时，model也是相同的，导致数据刷新时第二次会为上一个model下的值，如何自动为复用的页面新建一个model。
我是初始化的时候清理data，或者退出的时候清理data，或者新建一个model
不知道有没有更好的方式

**Comment by chenshuai2144** [comment]
> 退出的时候清理data

这个是比较合适的方案。如果不需要共用，可以直接不用 modal
