### ISSUE TITLE
https://pro.ant.design/index-cn 页面火狐耗资源cpu 都满了卡死了

### ISSUE THREAD

**Issue by chenlong88** [ant-design/ant-design-pro#5243]
https://pro.ant.design/index-cn 页面火狐耗资源cpu 都满了卡死了，Chrome 就不卡

**Comment by xiaohuoni** [comment]
Chrome你试试频繁的变更窗口大小，会不会耗CPU（😊）

**Comment by chenlong88** [comment]
这个和我说的bug 有什么关系，我让另外一个同事看也是同样的问题火狐特别占资源




------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 下午2:48
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>; 
抄送: "阳光"<405770292@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] https://pro.ant.design/index-cn 页面火狐耗资源cpu 都满了卡死了 (#5243)




Chrome你试试频繁的变更窗口大小，会不会耗CPU（😊）

**Comment by xiaohuoni** [comment]
没有关系，我只是接个楼而已。

**Comment by afc163** [comment]
Duplicate of #5041
