### ISSUE TITLE
关于ant

### ISSUE THREAD

**Issue by wxb1989** [ant-design/ant-design-pro#5244]
大家都是开发Facebook体量的应用吗？非要高大上的Redux？改一个isLogin要跳4到5个文件，经过7到8个函数，你们都不烦？Flux和Redux这套为了设计而设计的流程框架，真的适合大家吗？说句不好听的，真到了Facebook体量了，你还用别人家的框架？

忍不住吐槽一下是使用react体系实际项目有一年多了，antd系列是难得的高质量库。但是每次想用一下antd提供的现有demo来使用，总要花大力气来去除Flux和Redux系列的代码，真心烦。号称的解耦，其实是高度耦合。典型的理论脱离实际，搞不懂ant为什么一直大力推。别上来都以为自己是几百人团队合作，几千万用户使用。

我们自己团队只在最开始用了一次Flux和Redux流程就再也没有用过。现在使用的是MVVM架构的Mobx系列，直观高效优雅。微软的MVVM和Google的angular都是这类思想，而且都是工业化被广大使用的。真心不懂为什么react里面大家都要一股脑用什么Flux和Redux，极其难用，不说其它，项目团队里面推都推不动。

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/1516

**Comment by afc163** [comment]
这是机器人？...

**Comment by xiaohuoni** [comment]
应该不是吧，估计觉得这个说的，感同身受
