### ISSUE TITLE
要怎样能实现路由钩子之类的功能呢

### ISSUE THREAD

**Issue by MangGoDio** [ant-design/ant-design-pro#5245]
比如一段页面统计代码，vue可以直接在vue-router提供的方法里监听
```
router.befroeEach(() => {
    if (线上环境判断) {
        baiduTongji();
        _hmt && _hmt.push(['_trackPageview', '/#' + to.fullPath]);
    }
});
```
react-router我看v4以后整合为组件的形式，在umi的框架里要如何去应用呢，看文档有个promot组件但是只能作为离开页面时候的监听似乎并不能实现需求

**Comment by huang714669** [comment]
楼主问题解决了吗？ 我是在store的routing里面看到了pathname是可以监听路由的，但是这个好像是umi router自动做的

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/d19bc783a3a465024e8143f9192e4693ea2ae3d1/src/layouts/SecurityLayout.tsx

在 layout 中监听 props 的改变即可。
