### ISSUE TITLE
菜单默认展开

### ISSUE THREAD

**Issue by wuqiuyude** [ant-design/ant-design-pro#5246]
请教一下大家，怎么让左侧菜单默认全部展开，且切换的时候不会关闭其他菜单啊，没有找到可以设置inlineCollapsed的地方

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/pull/98
看起来你需要这个

**Comment by chenshuai2144** [comment]
已经发布 layout 版本

**Comment by ldwonday** [comment]
@wuqiuyude 你是怎么实现的？

**Comment by tonguelesscat** [comment]
同求

**Comment by chenshuai2144** [comment]
menuProps 属性可以设定所有 menu 的属性
