### ISSUE TITLE
子路由的变化会导致整个组件unmount然后mount，而不是仅仅变化子路由的部分

### ISSUE THREAD

**Issue by vxzhong** [ant-design/ant-design-pro#525]
在SearchList里添加
componentDidMount() {
    console.log("componentWillMount: dispatch");
  }

  componentWillUnmount() {
    console.log("componentWillUnmount");
  }

然后，每次切换搜索，都出现了：
![image](https://user-images.githubusercontent.com/86217/34428461-f146a1c8-ec87-11e7-8d60-5c68d3f19f41.png)

假如我是从一个list到一个detail页面，detail是子路由，这样每次从detail回到list，list都会重刷，而不是在原来的位置。

**Comment by afc163** [comment]
Fixed in #440

**Comment by vxzhong** [comment]
@afc163 我是跑的master上最新的代码，最新的路由实现，还是有这个问题。

**Comment by afc163** [comment]
如果不是互相内嵌的格式，那目前确实是这样的。

**Comment by chenshuai2144** [comment]
这个应该是路由的原因吧. 路由只要被触发整个页面都会加载

**Comment by vxzhong** [comment]
切换到0.3.1的版本，反而没有这个问题了。子路由的切换不到导致父组件被销毁重新创建。

**Comment by vxzhong** [comment]
// wrapper of dynamic
const dynamicWrapper = (app, models, component) => dynamic({
  app,
  // eslint-disable-next-line no-underscore-dangle
  models: () => models.filter(m => !app._models.some(({ namespace }) => namespace === m)).map(m => import(`../models/${m}.js`)),
  // add routerData prop
  component: () => {
    const p = component();
    return new Promise((resolve, reject) => {
      p.then((raw) => {
        const Comp = raw.default || raw;
        resolve(props => <Comp {...props} routerData={getRouterData(app)} />);
      }).catch(err => reject(err));
    });
  },
});

是不是这段代码的问题，这又创建了一个新的实例。

**Comment by afc163** [comment]
修复在这里：https://github.com/ant-design/ant-design-pro/commit/b27bf8deab0300d964b4ee7c04b1b2dead7c5357

然后简化了一下代码：https://github.com/ant-design/ant-design-pro/commit/86a2d26dee3675c937e2890ebe389b1eeba88095
