### ISSUE TITLE
作为后台系统，最好头部有tab 导航，可以让用户点击左边菜的可以在上面tab 切换

### ISSUE THREAD

**Issue by jiangjianshuang** [ant-design/ant-design-pro#5250]
作为后台系统，最好头部有tab 导航，可以让用户点击左边菜的可以在上面tab 切换

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/220 相关 Issues，最近提这个有点多。是否需要重现考虑一下。 220这个已经是17年的事情了。@afc163

**Comment by afc163** [comment]
不考虑

**Comment by afc163** [comment]
Duplicate of #220

**Comment by jiangjianshuang** [comment]
这个不考虑会比较难用的，一些软电话CRM&nbsp;客户&nbsp;呼入，你要多个菜单的，因为进线业务处理什么的，没处理完毕就下一个用户进线了，你可以参考&nbsp;
https://panjiachen.github.io/vue-element-admin




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jun888"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月12日(星期四) 上午10:46
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"一枝梅"<395475789@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 作为后台系统，最好头部有tab 导航，可以让用户点击左边菜的可以在上面tab 切换 (#5250)




不考虑
