### ISSUE TITLE
Copyright 说明 移除 BasicLayout footerRender无效，要在node_modules/@ant-design/BasicLayout移除才有用

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5255]
如题： 
1.登录页的UserLayout移除有效果
2.在内页的BasicLayout移除无效
有无更好的方法，不用修改node_modules里面的？

**Comment by z-lionel** [comment]
> footerRender 被结



> 你是不是 footerRender 被结构赋值重写了。
> 让我看看你的代码把

/**
 * Ant Design Pro v4 use `@ant-design/pro-layout` to handle Layout.
 * You can view component api by:
 * https://github.com/ant-design/ant-design-pro-layout
 */
import ProLayout from '@ant-design/pro-layout';
import React, { useEffect } from 'react';
import Link from 'umi/link';
import { connect } from 'dva';
import { formatMessage } from 'umi-plugin-react/locale';
import Authorized from '@/utils/Authorized';
import RightContent from '@/components/GlobalHeader/RightContent';
import { isAntDesignPro } from '@/utils/utils';

/**
 * use Authorized check all menu item
 */
const menuDataRender = menuList =>
  menuList.map(item => {
    const localItem = { ...item, children: item.children ? menuDataRender(item.children) : [] };
    return Authorized.check(item.authority, localItem, null);
  });

const footerRender = (_, defaultDom) => {
  if (!isAntDesignPro()) {
    return defaultDom;
  }

  return (
    <>
      {defaultDom}
      <div
        style={{
          padding: '0px 24px 24px',
          textAlign: 'center',
        }}
      >
        <a href="https://www.netlify.com" target="_blank" rel="noopener noreferrer">
          <img
            src="https://www.netlify.com/img/global/badges/netlify-color-bg.svg"
            width="82px"
            alt="netlify logo"
          />
        </a>
      </div>
    </>
  );
};

const BasicLayout = props => {
  const { dispatch, children, settings } = props;
  /**
   * constructor
   */

  useEffect(() => {
    if (dispatch) {
      // dispatch({
      //   type: 'user/fetchCurrent',
      // });
      // dispatch({
      //   type: 'settings/getSetting',
      // });
    }
  }, []);
  /**
   * init variables
   */

  const handleMenuCollapse = payload => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  };

  return (
    <ProLayout
      logo={logo}
      onCollapse={handleMenuCollapse}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl) {
          return defaultDom;
        }

        return <Link to={menuItemProps.path}>{defaultDom}</Link>;
      }}
      breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: formatMessage({
            id: 'menu.home',
            defaultMessage: 'Home',
          }),
        },
        ...routers,
      ]}
      itemRender={(route, params, routes, paths) => {
        const first = routes.indexOf(route) === 0;
        return first ? (
          <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
        ) : (
          <span>{route.breadcrumbName}</span>
        );
      }}
      footerRender={footerRender}
      menuDataRender={menuDataRender}
      formatMessage={formatMessage}
      rightContentRender={rightProps => <RightContent {...rightProps} />}
      {...props}
      {...settings}
    >
      {children}
    </ProLayout>
  );
};

export default connect(({ global, settings }) => ({
  collapsed: global.collapsed,
  settings,
}))(BasicLayout);

**Comment by z-lionel** [comment]
> 你是不是 footerRender 被结构赋值重写了。
> 让我看看你的代码把

并没有修改这里面的内容,单单把footerRender={footerRender}删除,还是会显示

**Comment by z-lionel** [comment]
> @z-lionel 傻孩子，BasicLayout也用DefaultFooter就可以了。

大兄弟,现在是原来的那个声明删除不了,自己添加是没问题

**Comment by z-lionel** [comment]
要给footerRender={false} 才能隐藏, 光光删除是没有用

**Comment by chenyu1990** [comment]
我昨天生成的最新版的，特么的，怎么都改不掉copyright。神烦。

**Comment by z-lionel** [comment]
> 我昨天生成的最新版的，特么的，怎么都改不掉copyright。神烦。

在 BasicLayout 里面 找到 footerRender 设置为false应该就可以了， 不要去掉

**Comment by chenyu1990** [comment]
> > 我昨天生成的最新版的，特么的，怎么都改不掉copyright。神烦。
> 
> 在 BasicLayout 里面 找到 footerRender 设置为false应该就可以了， 不要去掉

我试了，不管用。前天的版本。最后我还是改的node_modules里的

**Comment by chenshuai2144** [comment]
@chenyu1990  是不是有 lock 文件？
