### ISSUE TITLE
config/defaultSettings.js报错

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-pro#5258]
import { MenuTheme } from 'antd/es/menu';   <-----报错
![image](https://user-images.githubusercontent.com/2151838/64837644-1620ef00-d622-11e9-8434-8154d3ca453b.png)

**Comment by chenshuai2144** [comment]
更新 antd的版本

**Comment by macmatilda** [comment]
我昨天clone最新的ant design pro






------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>;
发送时间: 2019年9月13日(星期五) 晚上10:38
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "天使消失的街"<macmatilda@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] config/defaultSettings.js报错 (#5258)




更新 antd的版本

**Comment by macmatilda** [comment]
真的是服了，如果还要自己更新版本，用ant design pro干啥？？kpi要关单？？
