### ISSUE TITLE
ant-design-pro 如何进行配置dva-loading插件

### ISSUE THREAD

**Issue by AixsCode** [ant-design/ant-design-pro#5262]
下载了ant-design-pro 脚手架，第一步如何配置dva-loading插件可以加载到项目中，下载好的项目中似乎没法按照`import createLoading from 'dva-loading';const app = dva();app.use(createLoading());` 这种方式去配置，求解答一下？

**Comment by chenshuai2144** [comment]
dva-loading 在 pro 中已经内置，可以直接使用。
