### ISSUE TITLE
如何在antd项目中引入基于jq开发的一个页面？

### ISSUE THREAD

**Issue by joshua178zhy** [ant-design/ant-design-pro#5264]
现在的项目是基于antd开发的一个后台管理项目，项目现在需要对接外部引入他们提供的一套jq项目，想在我们的项目中通过打开一个新窗口运行打开，请问有没有方式可以实现？

**Comment by chenshuai2144** [comment]
iframe 是最好的方案，或者去看看[ 微前端](https://github.com/sorrycc/blog/issues/85) 的方案。

**Comment by joshua178zhy** [comment]
请问iframe的src在哪里配置，如果ifame放在组件内的话需要走router.config.js,这里面都是组件的路径，html文件的路径怎么配置？
