### ISSUE TITLE
pro v4 菜单栏通过 SVG Symbol 方式引用图标失败

### ISSUE THREAD

**Issue by xlszzck** [ant-design/ant-design-pro#5265]
v4在defaultSettings中设置iconfontUrl，菜单栏无法引用在线图标，图标会占位，但是是空图标。
在v2中，同样路径可以引用。
路径是阿里巴巴矢量图标库生成的。例如，'//at.alicdn.com/t/font_1225322_kkyfv99s89.js'

**Comment by chenshuai2144** [comment]
来个最小复现仓库

**Comment by xlszzck** [comment]
解决了，v2版本我在BaseMenu的getIcon函数里加了自定义icon名称的替换。v4版本BaseMenu已经提取到pro-layout了，所以菜单的自定义icon前缀是'icon-'和阿里巴巴矢量图标库一致就行
