### ISSUE TITLE
怎么在生产环境去除console信息？

### ISSUE THREAD

**Issue by MyPacker** [ant-design/ant-design-pro#5266]
我配置了`babel-plugin-transform-remove-console`插件，但是貌似并没有什么用。

**Comment by wangxingkang** [comment]
贴下配置呗

**Comment by wangxingkang** [comment]
提供最小可复现仓库

**Comment by chenshuai2144** [comment]
在  ugly 中配置比较好。
来个复现吧

**Comment by MyPacker** [comment]
只修改了config.js文件

```
export default {
.....
  plugins: [
    [
      'umi-plugin-react',
      {
        antd: true,
        dva: { hmr: true },
        targets: { ie: 11 },
        locale: { enable: false },
        dynamicImport: { loadingComponent: './components/PageLoading/index' },
      },
    ],
    [
      'umi-plugin-pro-block',
      {
        moveMock: false,
        moveService: false,
        modifyRequest: true,
        autoAddMenu: true,
      },
    ],
    ['babel-plugin-transform-remove-console']
  ],
......
};
```

**Comment by wangxingkang** [comment]
https://umijs.org/zh/config/#extrababelplugins 请看这里文档 plugins 是umi插件

**Comment by shuaigemarui** [comment]
uglifyJSOptions(opts) {
    if (process.env.NODE_ENV === 'production'){
      opts.uglifyOptions.compress.drop_debugger = true;
      opts.uglifyOptions.compress.drop_console = true;
    }
    return opts;
  }

**Comment by sunlanlisa** [comment]
> uglifyJSOptions(opts) {
> if (process.env.NODE_ENV === 'production'){
> opts.uglifyOptions.compress.drop_debugger = true;
> opts.uglifyOptions.compress.drop_console = true;
> }
> return opts;
> }

您发的这个管用吗，写在什么地方。我试了一下好像不管用
