### ISSUE TITLE
Sourcemaps Are Wrong

### ISSUE THREAD

**Issue by robert-claypool** [ant-design/ant-design-pro#5267]
1. Create and run a new app

```Shell
npm install --global create-umi
mkdir my-app
cd my-app
npm create umi # choose `ant-design-pro` and `TypeScript`
npm install
npm run start
```

2. Open http://localhost:8000/ in Chromium or Chrome, then `F12` for DevTools
3. Set a breakpoint at `login.ts`, line 47
4. Log out
5. Log in to trigger the breakpoint

Notice that the debugger is off by one line. Notice also that breakpoints cannot be placed on lines 44 and 57.

![broken-sourcemaps](https://user-images.githubusercontent.com/1069956/64938156-87c78b80-d822-11e9-8356-d6073b878ab6.png)

**Comment by jiangzm** [comment]
Same problem.

**Comment by chenshuai2144** [comment]
google waring？

**Comment by robert-claypool** [comment]
@chenshuai2144, I don't understand your question.

**Comment by chenshuai2144** [comment]
> Is Google Chrome wrong or is webpack wrong?

That's right. my english is poor.

@sorrycc   cc

**Comment by robert-claypool** [comment]
No problem, my Mandarin is terrible! 😂

**Comment by chenshuai2144** [comment]
try this config https://umijs.org/config/#devtool

**Comment by KevinShen620** [comment]
我也碰到了一样的问题，通过官方文档指导初始化项目，语言选择了 `typesciprt`。观察了下，源码与断点应该是错开了一行，

![image](https://user-images.githubusercontent.com/3666595/65138947-63e09180-da3e-11e9-8fde-fcd0e6b2271b.png)

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
