### ISSUE TITLE
如何在antd中使用iframe?

### ISSUE THREAD

**Issue by joshua178zhy** [ant-design/ant-design-pro#5272]
项目是基于react和antd开发的，目前需要在项目上打开新窗口运行外部对接的一个jq项目的html文件，目前使用的是iframe方案，新建一个react组件，返回一个iframe,在router.config.js配置当前组件的路径，配置iframe的src为当前相对当前组件的html文件路径，运行时候会报，找不到路径，发现iframe的src也会走router.config.js，然后就在router.config.js配置html文件的路径也找不到，请问是使用iframe方式不正确吗？如果不正确应该怎么使用？如果使用方式正确，iframe的src应该怎么配置呢？

**Comment by chenshuai2144** [comment]
和 link 标签的路径一致即可，不要带上 html。

如 https://preview.pro.ant.design/dashboard/monitor

```
< iframe  src="/dashboard/monitor"/>
```

**Comment by jarrywen** [comment]
如果是外部系统的html呢？

**Comment by taoyouxian** [comment]
假设新增区块：空白页面，则在`index.tsx`中修改如下即可：
```
return (
    <iframe style={{border:0,}} src="http://www.baidu.com"/>
    // <PageHeaderWrapper content="这是一个新页面，从这里进行开发！" className={styles.main}>
    //   <div style={{ paddingTop: 100, textAlign: 'center' }}>
    //     <Spin spinning={loading} size="large" />
    //   </div>
    // </PageHeaderWrapper>
  );
```

**Comment by alianzhang** [comment]
<iframe  src={`./assets/edb_bar/phoneBar/phonebar.html?loginName=${loginName}`}></iframe>
iframe 的 src 写的是一个页面的相对路径，发现会去匹配路由，结果找不到显示404页面，这种情况要怎么办？

**Comment by jayesslin** [comment]
这是啥破烂解答

**Comment by chenshuai2144** [comment]
@renqi1996 iframe 是一个新的标签页，最好的办法是写绝对路径。
