### ISSUE TITLE
前端路由可以从后端根据权限动态返回对应的路由吗

### ISSUE THREAD

**Issue by zytjs** [ant-design/ant-design-pro#5274]
菜单已经在`BasicLayout`从后端动态获取，为什么路由没有开放类似接口呢？菜单只是个展示，路由才是控制权限的吧，如果路由可以直接从后端返回，后端也就不用再做权限校验了，因为这个路由就不存在，是404

**Comment by jiangzm** [comment]
前端路由为什么由后端控制呢， 路由要对应到component

**Comment by xlszzck** [comment]
> 前端路由为什么由后端控制呢， 路由要对应到component

这样会更灵活。如果需要改目录什么的，后端直接改了就OK了，不用前后端一起改。

**Comment by chenshuai2144** [comment]
umi 会根据路由来确定你打包的文件，如果你动态路由那么文件必须要全部打包。
为了灵活建议使用动态菜单。

**Comment by zytjs** [comment]
现在的权限控制也是全部打包吧，反正无论是现在的权限控制方式，还是后端返回权限对应的路由，后端都需要再做一次校验，这样看来，动态菜单的具体作用是什么，路由配置好已经可以自动生成菜单了。
