### ISSUE TITLE
cnpm 卡在这不动了 不着知道为啥

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#5275]
yons@localhost  ~/coding/web/sys_office   master   cnpm install
⠋ [18/66] Installing string-convert@^0.2.0

**Comment by kzabc** [comment]
中断后  在此之星   会在卡在这里   Installing unist-util-is@^3.0.0

**Comment by kzabc** [comment]
@大佬们

**Comment by chenshuai2144** [comment]
先删除 node-moudles ，然后再尝试安装。或者使用 [tyarn](http://npm.taobao.org/package/tyarn)

**Comment by afc163** [comment]
更新一下 cnpm
