### ISSUE TITLE
已登录状态无法获取

### ISSUE THREAD

**Issue by starhu521** [ant-design/ant-design-pro#5276]
登录页面登录后，跳转加载securityLayout或者Authorized，无法获取到currentUser信息，准确的说是currentUser信息获取判断是在dispatch 'user/fetchCurrent'之前，而且currentUser更新后没有触发这两个组件的render，就导致登录必须两次

**Comment by jiangzm** [comment]
已经有人优化了 #5252

**Comment by starhu521** [comment]
> 已经有人优化了 #5252

但是我拉了最新的，好像还是需要登录两次才能获取状态

**Comment by jiangzm** [comment]
@starhu521 你需要修改下isLogin判断逻辑

**Comment by starhu521** [comment]
@jiangzm  我只是创建项目，mock下跑了下模板

**Comment by WuJiY** [comment]
两次登录了，securityLayout里获取不到currentUer

**Comment by laosandegudai** [comment]
我也遇到了，用的是当前最新的cli创建的项目。
