### ISSUE TITLE
点击菜单折叠, 侧边栏的二级菜单会经历 折叠 => 收起 => 折叠 三个步骤

### ISSUE THREAD

**Issue by wonderFF** [ant-design/ant-design-pro#5277]
视觉上看起来有点冗余 

见: https://preview.pro.ant.design/dashboard/analysis

**Comment by chenshuai2144** [comment]
来个gif 没有听懂

**Comment by wonderFF** [comment]
[DEMO_SIDEBAR.zip](https://github.com/ant-design/ant-design-pro/files/3624307/DEMO_SIDEBAR.zip)

我录制了一个 2s 的小视频, 我执行了一次点击, 然后请关注侧边栏的变化, 看起来发生了 折叠 => 收起 => 折叠

**Comment by chenshuai2144** [comment]
来个 gif 吧。只有 2s

**Comment by chenshuai2144** [comment]
@wonderFF  看到了，我看看有办法解决吗

**Comment by wonderFF** [comment]
![sidebar_bug](https://user-images.githubusercontent.com/20740658/65137224-891fd080-da3b-11e9-84d1-e841318b1d9f.gif)
关注第 13 帧, 我也是刚刚录制好

**Comment by chenshuai2144** [comment]
fixed
