### ISSUE TITLE
在antd中如何使用iframe打开其他项目？

### ISSUE THREAD

**Issue by joshua178zhy** [ant-design/ant-design-pro#5278]
项目是基于react和antd开发的，目前需要在项目上打开新窗口运行外部对接的一个jq项目的html文件，目前使用的是iframe方案，新建一个react组件，返回一个iframe,在router.config.js配置当前组件的路径，配置iframe的src为当前相对当前组件的html文件路径，运行时候会报，找不到路径，发现iframe的src也会走router.config.js，然后就在router.config.js配置html文件的路径也找不到，请问是使用iframe方式不正确吗？如果不正确应该怎么使用？如果使用方式正确，iframe的src应该怎么配置呢？

**Comment by chenshuai2144** [comment]
`/#/xxxx`  
如果你使用了hash 路由需要这样配置。
如果是 正常的路由 /XXX , 不需要与 html相关
