### ISSUE TITLE
layout中logo处的链接如何自定义，footer如何自定义

### ISSUE THREAD

**Issue by fhl0403** [ant-design/ant-design-pro#5279]
![image](https://user-images.githubusercontent.com/24505581/65029385-3af1cb00-d970-11e9-87fa-3c112fb737a6.png)
这一块代码注释后仍然存在，请问是哪里可以定义？

**Comment by fhl0403** [comment]
![image](https://user-images.githubusercontent.com/24505581/65029465-6379c500-d970-11e9-8b25-1fe9ced64e96.png)
还有这边的链接定义后还是跳转至/，希望可以定义，还有右边的ant design pro可否改成图片？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout

footerRender 和 headerRender
