### ISSUE TITLE
为了未来 component 能单独拿出来用，是不是规范一下 component 的 props？

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design-pro#528]
现在的 component 有的依赖于 dispatch 的，比如说 SiderMenu 和 GlobalHeader，还有直接依赖于外部写死的数据的，比如说 SiderMenu 的 menuData。
一个 component 应该接受外部指定的数据和行为，才能保持 component 的灵活性，建议 component 不能把 dispatch 作为 prop，也不能依赖于写死的数据，而应该把行为、数据传给 component，你们觉得呢？

**Comment by afc163** [comment]
对，这两个组件我改一下。

**Comment by zation** [comment]
回复的太快了！赞！
但是要能独立出来，好像还有一些需要修改的，因为 SideMenu 的 logo 和 title 也写死在里面了……

**Comment by chenshuai2144** [comment]
现在耦合性还是很高的. 以后应该慢慢的减少偶合.
多弄一些无状态组件.方便大家直接copy

**Comment by zation** [comment]
还有一个问题是，大部分的 component 都用到了 `dva/router` 的 `Link`，这个组件能不能有一个 ant-design-pro 的静态方法，来全局设置？如果不设置的话，就用原生的 a？

**Comment by chenshuai2144** [comment]
你可以用react-router 替代.
或者hash的话
` <a href="/#/login">登陆</a>`

**Comment by zation** [comment]
@chenshuai2144 你是说我 folk 一份 ant-design-pro，然后把里面所有用到了 `dva/router` 的 `Link` 的代码都改成我自己的 Link 组件吗？这样好像不太利于 ant-design-pro 在 component 层级的复用吧？

**Comment by chenshuai2144** [comment]
现在还做不到开箱即用.
我现在开发基于mobx的

**Comment by zation** [comment]
对，所以就是想讨论一下未来如果想复用的话，怎么做，因为每个人用的 router 不同，Link 组件可能也会不同，所以就想一个 global static 的方法去设置行不行

**Comment by chenshuai2144** [comment]
我觉得无状态组件是个好办法,
与其做成传入各种参数的.
不如做成细粒度的方便人们修改和删除.

**Comment by afc163** [comment]
先把 logo、dispatch 这些分离出来了，其他写死的部分如果有需求，可以 PR 过来修改。
