### ISSUE TITLE
使用TimelineChart，当数据时间范围为一周时，默认间隔为1小时，x轴显示太过拥挤

### ISSUE THREAD

**Issue by changechenhao** [ant-design/ant-design-pro#5282]
**Steps to reproduce**
![image](https://user-images.githubusercontent.com/32796773/65032669-2adcea00-d976-11e9-921a-27cd29079ae5.png)

**What is expected?**
![image](https://user-images.githubusercontent.com/32796773/65033199-1f3df300-d977-11e9-8295-543c8474ad13.png)

查看源码发现：
`var timeScale = {
        type: 'time',
        tickInterval: 60 * 60 * 1000,
        mask: 'HH:mm',
        range: [0, 1]
      };`
修改tickInterval即可自定义时间间隔，期望能在TimelineChart加上timeScale属性，使得可以自定义时间间隔。

**What is actually happening?**
version:2.3.2

**Comment by chenshuai2144** [comment]
使用 g2 自定义吧。TimelineChart 是特殊定制的
