### ISSUE TITLE
ant design pro 4.0 如何连接本地后台服务呢? 如何禁用mock数据？官方能说说么，其它网上似乎不太正宗？

### ISSUE THREAD

**Issue by fenghuolibie** [ant-design/ant-design-pro#5283]

**Comment by chenshuai2144** [comment]
proxy 还是关闭 mock？

`  "start:no-mock": "cross-env MOCK=none umi dev",` 这里可以不启动 mock

**Comment by fenghuolibie** [comment]
如何与后端接口对接呢，需要在前端设置些什么呢

**Comment by fenghuolibie** [comment]
> 
> 
> proxy 还是关闭 mock？
> 
> ` "start:no-mock": "cross-env MOCK=none umi dev",` 这里可以不启动 mock
如何与后端接口对接呢，需要在前端设置些什么呢

**Comment by fenghuolibie** [comment]
> 
> 
> proxy 还是关闭 mock？
> 
> ` "start:no-mock": "cross-env MOCK=none umi dev",` 这里可以不启动 mock

还没回答完就close？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/server-cn 看这个文档

**Comment by fenghuolibie** [comment]
> 
> 
> https://pro.ant.design/docs/server-cn 看这个文档

文档并不友好，我看了几十遍，能否细讲哪些配置

**Comment by chenshuai2144** [comment]
你的问题是什么？ 或者碰到什么问题！你的问题有点大，我不知道从何讲起

**Comment by fenghuolibie** [comment]
> 你的问题是什么？ 或者碰到什么问题！你的问题有点大，我不知道从何讲起

我想让我的ant design pro和后端进行数据交互，但是不知如何进行配置。model和service，dispatch我已经知道使用，但是请求的ip地址总是前端react的localhost:8080,我不知道如何配置ip和端口url

**Comment by chenshuai2144** [comment]
代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock

**Comment by fenghuolibie** [comment]
代理是在 config的proxy配置一个代理的json文件么。




------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 下午4:54
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>; 
抄送: "游少军"<2302470731@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-pro] ant design pro 4.0 如何连接本地后台服务呢? 如何禁用mock数据？官方能说说么，其它网上似乎不太正宗？ (#5283)




代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock

**Comment by fenghuolibie** [comment]
> 代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock

问题已经解决，你给的解决方式很好。Thank you！

**Comment by frontendWangqun** [comment]
> > 代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock
> 
> 问题已经解决，你给的解决方式很好。Thank you！

请问怎么解决的  ？ V4版本的也总是出现这个问题，麻烦把详细解决步骤发一下，多谢

**Comment by winlj** [comment]
> > proxy 还是关闭 mock？
> > ` "start:no-mock": "cross-env MOCK=none umi dev",` 这里可以不启动 mock
> > 如何与后端接口对接呢，需要在前端设置些什么呢

朋友，麻烦一下，可以加下qq吗？我出的也是这个问题，我已经蒙逼啦，搞不明白了。不知道应该如何处理，

代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock

这句话我也没理解应该怎么搞啊。

**Comment by withwz** [comment]
> > > proxy 还是关闭 mock？
> > > ` "start:no-mock": "cross-env MOCK=none umi dev",` 这里可以不启动 mock
> > > 如何与后端接口对接呢，需要在前端设置些什么呢
> 
> 朋友，麻烦一下，可以加下qq吗？我出的也是这个问题，我已经蒙逼啦，搞不明白了。不知道应该如何处理，
> 
> 代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock
> 
> 这句话我也没理解应该怎么搞啊。

在config里的proxy设置好接口地址就行了，
运行没有mock的命令
> npm run start:no-mock
就是请求的你的接口地址了，但是浏览器里还是localhost，
![image](https://user-images.githubusercontent.com/39869566/73920698-dcb68c00-4900-11ea-8fa2-c2a6c2acf465.png)

**Comment by mymmoonoa** [comment]
> > > > proxy 还是关闭 mock？
> > > > ` "start:no-mock": "cross-env MOCK=none umi dev",` 这里可以不启动 mock
> > > > 如何与后端接口对接呢，需要在前端设置些什么呢
> > 
> > 
> > 朋友，麻烦一下，可以加下qq吗？我出的也是这个问题，我已经蒙逼啦，搞不明白了。不知道应该如何处理，
> > 代理过去就好了。代理不会修改 url 的，代理是在 node 端做的。 使用代理之前先关掉 mock
> > 这句话我也没理解应该怎么搞啊。
> 
> 在config里的proxy设置好接口地址就行了，
> 运行没有mock的命令
> 
> > npm run start:no-mock
> > 就是请求的你的接口地址了，但是浏览器里还是localhost，
> > ![image](https://user-images.githubusercontent.com/39869566/73920698-dcb68c00-4900-11ea-8fa2-c2a6c2acf465.png)

遇到一样的问题，官方不能给说法吗？ 改了根本不生效啊

**Comment by mymmoonoa** [comment]
proxy.ts文件中有段注释
The agent cannot take effect in the production environment

@chenshuai2144 现在是本地直接npm run start起的，这会被认为是production 环境？
现在情况proxy.ts更新如下，并且代码中使用mock里不存在的路径，发现请求是到还是localhost:8000
```
dev: {
    '/api/': {
      target: 'http://jsonplaceholder.typicode.com/',
      changeOrigin: true,
      pathRewrite: { '^/api': '' },
    },
  },
```
现在看起来就是proxy.ts随便怎么配置，都不会生效

**Comment by mymmoonoa** [comment]
总算看明白了，https://github.com/ant-design/ant-design-pro/issues/5795 @Liqiankun 的优质回答，才能属于给人看的。

**Comment by snow-li-crypto** [comment]
编译后生成dist目录 挂在nginx下， api的路径怎么配置请求到后端服务（这个时候前端没有node 不能代理）
