### ISSUE TITLE
Step Form Page lost it's highlighted menu

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#529]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/507615/34431867-a78c14fc-ecad-11e7-9640-205de88cb72f.png">

ref https://github.com/ant-design/ant-design-pro/pull/519

**Comment by ddcat1115** [comment]
fixed in https://github.com/ant-design/ant-design-pro/commit/e2b1261c8f5d275e105e60e4766734c7eccadfb3
