### ISSUE TITLE
以前在右侧那个导航设置 主题颜色设置，怎么找不到了呢？

### ISSUE THREAD

**Issue by liyi563257046** [ant-design/ant-design-pro#5293]
安装完成运行后预览，发现以前那个导航和主题设置不见了？在哪里可以恢复呢？

**Comment by liyi563257046** [comment]
好奇怪，我装了两个pro，一个有导航设置，一个没有导航设置

**Comment by liyi563257046** [comment]
重新安装就可以了，因为区块在安装的时候，经常装到一半就卡主了，导致一些页面没装上

**Comment by Dygood** [comment]
> 安装完成运行后预览，发现以前那个导航和主题设置不见了？在哪里可以恢复呢？

你这个设置主题的是怎么搞的?我装完后,就是没有,我看官方的预览页面有.

**Comment by liyi563257046** [comment]
你可能是安装的时候没有安装完全，有几个在src下面的pages大概叫layout board啥的页面需要装上，我现在用手机没用电脑名字记不清了。我装的时候好几次都是装了一半就卡住了，然后反复重新装，最后一次成功了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout#settingdrawer
你要的是这个吧

**Comment by Dygood** [comment]
> https://github.com/ant-design/ant-design-pro-layout#settingdrawer
> 你要的是这个吧

对,我昨晚发现我忘记添加那个组件了.

**Comment by UchihaItachi6** [comment]
https://github.com/ant-design/ant-design-pro-layout#settingdrawer这个链接是TS版本的吧，请问有JS版本的吗

**Comment by UchihaItachi6** [comment]
> https://github.com/ant-design/ant-design-pro-layout#settingdrawer
> 你要的是这个吧

https://github.com/ant-design/ant-design-pro-layout#settingdrawer这个链接是TS版本的吧，请问有JS版本的吗

**Comment by joesdu** [comment]
> > https://github.com/ant-design/ant-design-pro-layout#settingdrawer
> > 你要的是这个吧
> 
> [https://github.com/ant-design/ant-design-pro-layout#settingdrawer这个链接是TS版本的吧，请问有JS版本的吗](https://github.com/ant-design/ant-design-pro-layout#settingdrawer%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E6%98%AFTS%E7%89%88%E6%9C%AC%E7%9A%84%E5%90%A7%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%9C%89JS%E7%89%88%E6%9C%AC%E7%9A%84%E5%90%97)

这个组件,TS和JS里边的写法差不多的.

**Comment by UchihaItachi6** [comment]
> > > https://github.com/ant-design/ant-design-pro-layout#settingdrawer
> > > 你要的是这个吧
> > 
> > 
> > [https://github.com/ant-design/ant-design-pro-layout#settingdrawer这个链接是TS版本的吧，请问有JS版本的吗](https://github.com/ant-design/ant-design-pro-layout#settingdrawer%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E6%98%AFTS%E7%89%88%E6%9C%AC%E7%9A%84%E5%90%A7%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%9C%89JS%E7%89%88%E6%9C%AC%E7%9A%84%E5%90%97)
> 
> 这个组件,TS和JS里边的写法差不多的.

谢谢我去试试
