### ISSUE TITLE
一些使用vscode+本机docker node环境运行时的疑问🤔️

### ISSUE THREAD

**Issue by iwhile** [ant-design/ant-design-pro#5296]
请问两个问题，
1. 怎么配置Debugger for Chrome插件调试（我用的vscode 二开，目前只能debugger埋点，然后浏览器调试）。
2. docker运行时vscode打开项目好多找不到模块的红线。这个你们怎么处理的呢？

> docker环境里似乎把node模块都下载自己的环境里了，宿主机器项目里没有node_module这个资源。

**项目很棒，感谢🙏**
vscode模块缺失报错如图：
![image](https://user-images.githubusercontent.com/35193505/65195212-e30ead80-dab0-11e9-8cc7-b7aa112a5bc7.png)

**Comment by chenshuai2144** [comment]
@iwhile  我是都下载了一份。 是个好问题

**Comment by iwhile** [comment]
@chenshuai2144 我docker cp 一份也不行，还是报错。难道必须要本地也装好node？
vscode能远程到docker环境里直接读取里面的项目吗？😂

**Comment by chenshuai2144** [comment]
vscode 是可以的，但是配置比较复杂， 我还没完美跑起来过
