### ISSUE TITLE
npm run build 后，部署到测试环境，怎么把项目中的接口字段拼接上测试接口的地址

### ISSUE THREAD

**Issue by duanpf** [ant-design/ant-design-pro#530]
![image](https://user-images.githubusercontent.com/24790085/34433474-9ad0eff0-ecba-11e7-8edc-d92327d96b7b.png)
在本地开发都时候直接使用代理，就可以调取测试环境接口。请求的接口地址如：http://xxx.com/apicenter/login

但是 npm run build 打包后，请求都地址却成了 http://192.168.100.250/api/login
前面拼接的不是接口地址，而是当前服务器地址。

在.roadhogrc里面应该怎么配置可以解决这个问题呢，求解

**Comment by chenshuai2144** [comment]
你的代理也配置一下rewrite就可以了

**Comment by CrewS** [comment]
写请求的时候就写好 正式服务器的API前缀，本地测试的时候 通过代理rewrite，打包后不影响代码，前缀就是正式服务器的了吧

**Comment by duanpf** [comment]
嗯，那如果需要 npm run build:prod  （生产环境）  npm run build:test（测试环境）。这种，应该怎么配置呢

**Comment by chenshuai2144** [comment]
生产环境和测试环境为什么url差距这个大?
应该调整的尽量相同,
这种得直接操作源码...
