### ISSUE TITLE
pro v4.0文档 开发-路由和菜单部分 有误

### ISSUE THREAD

**Issue by rhtjUed** [ant-design/ant-design-pro#5300]
文档中写的menuData 数据格式如下：
[
  {
    "path": "/dashboard",
    "name": "dashboard",
    "icon": "dashboard",
    "routes": [
      {
        "path": "/dashboard/analysis",
        "name": "analysis",
        "exact": true
      },
      {
        "path": "/dashboard/monitor",
        "name": "monitor",
        "exact": true
      },
      {
        "path": "/dashboard/workplace",
        "name": "workplace",
        "exact": true
      }
    ]
  }
  // ....
]

但实际上数据结构必须为：

[
  {
    "path": "/dashboard",
    "name": "dashboard",
    "icon": "dashboard",
    "children": [
      {
        "path": "/dashboard/analysis",
        "name": "analysis",
        "exact": true
      },
      {
        "path": "/dashboard/monitor",
        "name": "monitor",
        "exact": true
      },
      {
        "path": "/dashboard/workplace",
        "name": "workplace",
        "exact": true
      }
    ]
  }
  // ....
]
才能正确渲染，需要把routes 替换成 children。

**Comment by xuxuMaster** [comment]
有人提过了，但是开发者很傲慢的说他的项目从来不用动态路由，所以就那么放着了

**Comment by chenshuai2144** [comment]
@rhtjUed  来个 pr

**Comment by mzrybbd** [comment]
我不知道哪一步出错了，侧边栏不出现动态路由，可以看一下您动态路由实现的代码吗？

**Comment by leshalv** [comment]
这个我不是提交过pr了吗？很久了都

**Comment by chenshuai2144** [comment]
@leshalv 非常感谢
