### ISSUE TITLE
How to redirect to login page if not logged in? #2157

### ISSUE THREAD

**Issue by pratikmotifworks** [ant-design/ant-design-pro#5301]
I tried everything like change to guest or other user but after logout i will try to access welcome page it is working. ant design latest version.

**Comment by chenshuai2144** [comment]
like this？
https://github.com/ant-design/ant-design-pro/raw/master/src/layouts/SecurityLayout.tsx

**Comment by pratikmotifworks** [comment]
Yes, I changed the Root path as Login page under admin and user authority. but when I am accessing http://localhost:8000/welcome and other pages without login it will automatically be logged in. so what changes i need to do so that i can not access any page without login?

**Comment by lishaoh** [comment]
我也遇到同样问题：
现象：注销登录后点击浏览器返回按钮依然能够回到welcome页
期望：注销登录后如果不重新登录，页面只能在Login页

**Comment by lishaoh** [comment]
注意在config中加入SecurityLayout

**Comment by pratikmotifworks** [comment]
Thank You @lishaoh but Routing is divided in two parts 1. UserLayout 2. BasicLayout. I tried using securityLayout for both but I am not getting. I tried a solution from this issue but it is also not working.
https://github.com/ant-design/ant-design-pro/issues/2157

**Comment by chenshuai2144** [comment]
you need add to `top-level`
