### ISSUE TITLE
ant design pro中如何监听路由变化？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#5302]
path: '/1',name: 'welcome',component: './Welcome1',
path: '/2',name: 'welcome',component: './Welcome2'
我配置了以上路由，hash=true，从/1切换到/2的时候有什么事件被触发？
我试过hashchange只能是#号后面的数据变化才行，但我的url里面并没有#

**Comment by chenshuai2144** [comment]
在 layout 中监听 this.props.location, 或者使用 redux-react-router 来监听。

各种 方法可以看这里 https://github.com/ReactTraining/react-router/issues/3554

> redux-react-router  已经内置，可以直接使用。

**Comment by hight-lig** [comment]
我想问一下我在page中用useEffect调用umijs的路由监听方法，在我logout时会报Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. 请问是哪里的问题
