### ISSUE TITLE
如何添加全局变量

### ISSUE THREAD

**Issue by HengzheLi** [ant-design/ant-design-pro#5303]
情况是：服务器会动态生成一段js代码返回给前端，前端使用eval动态执行该部分代码。
但是eval里貌似只能调用js的全局变量，我尝试在document.ejs里面定义了一些，但是有些eval的代码需要用到一些库里的对象，比如Events库里的emitter，在document.ejs里又无法通过import的形式来引入使用。
有什么类似的解决方案吗？

**Comment by chenshuai2144** [comment]
这个方法太黑科技了。
你可以通过 window 来访问的。emitter 这些的全部挂到 window 上面，或者在 global 中执行代码。

**Comment by HengzheLi** [comment]
嗯  看来是要通过window来访问了
