### ISSUE TITLE
use cesium  error, 

### ISSUE THREAD

**Issue by succulen-plants** [ant-design/ant-design-pro#5304]
error  in ./node_modules/_cesium@1.61.0@cesium/index.js

```
Module parse failed: 'return' outside of function (9:4)
You may need an appropriate loader to handle this file type.
| if (process.env.NODE_ENV === 'production') {
|     module.exports = require(path.join(__dirname, 'Build/Cesium/Cesium'));
>     return;
| }
| 

```

**Comment by chenshuai2144** [comment]
语法错误了！
@sorrycc 看起来是语法不正常，但是是可以跑的

**Comment by succulen-plants** [comment]
npm install cesium
npm run start
后就出现这种情况， 和 语法没也关系吧， 

  data-vi-pro git:(graph-components) ✗ cnpm install cesium --save
✔ Installed 1 packages
✔ Linked 1 latest versions
✔ Run 0 scripts
✔ All packages installed (2 packages installed from npm registry, used 3s(network 3s), speed 2.78kB/s, json 2(9.3kB), tarball 0B)
➜  data-vi-pro git:(graph-components) ✗ npm run start

> ant-design-pro@2.3.1 start /Users/luotengzhan/work/project/test/data-vi-pro
> cross-env ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION=site umi dev


✖ Webpack
  Compiled with some errors in 28.61s

 ERROR  Failed to compile with 1 errors                                                                                                                          6:22:20 PM

 error  in ./node_modules/_cesium@1.61.0@cesium/index.js

Module parse failed: 'return' outside of function (9:4)
You may need an appropriate loader to handle this file type.
| if (process.env.NODE_ENV === 'production') {
|     module.exports = require(path.join(__dirname, 'Build/Cesium/Cesium'));
>     return;
| }
|

**Comment by succulen-plants** [comment]
完全跑不起来， 只要安装了cesium就会报错

**Comment by succulen-plants** [comment]
@chenshuai2144 
在react+webpack上面也出现问题， 但是配置过config后可以了， 在ant pro上面做了相应的配置还是不行哦， 只要安装了cesium 就报错
    chainWebpack(config, { webpack }) {
        config.output.sourcePrefix(' ');
        // config.amd({toUrlUndefined:true});
        // // 设置 alias
        config.resolve.alias.set('cesium', path.resolve(__dirname, cesiumSource));
        config.merge({
          module: {
            unknownContextCritical: false,
            unknownContextRegExp: /^\.\/.*$/,
          }
        });
}

**Comment by chenshuai2144** [comment]
感觉要去umi 问了。需要一个webpack 高级配置工程师

**Comment by sorrycc** [comment]
cesium 这个包的问题，return 不能写在函数外面。
