### ISSUE TITLE
umi request 1.2.5 中间件页面切换拦截生效

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#5305]
request.js 中间件拦截代码如下
request.use(async (ctx, next) => {
  console.log(ctx)
  await next();
  const { res } = ctx;
  if (res.message === "token已过期") {
    console.log('res')
    confirm({
      title: 'token已过期，是否刷新token',
      content: '不刷新需要重新登录',
      onOk() {
        window.g_app._store.dispatch({
          type: 'login/refreshToken',
          callback: (res: any) => {
            userStorage.accessToken = res.data
            localStorage.setItem('vhds-authority', JSON.stringify(userStorage))
            location.reload()
          },
        })
      },
      onCancel() {
        window.g_app._store.dispatch({
          type: 'login/logout',
          payload: {'userName': userName},
        })
      },
    });
  }
})
umi request中间件拦截在页面刷新时才生效，但是路由切换捕捉不到。拦截器没问题。

**Comment by pl2476** [comment]
#5240

**Comment by huang714669** [comment]
@pl2476 好像不是一个问题把，那边是errorHandler的问题， 我这边是中间件的问题

**Comment by pl2476** [comment]
> @pl2476 好像不是一个问题把，那边是errorHandler的问题， 我这边是中间件的问题

可能也是umi-request 的问题，去那边找找看，或者调试定位下

**Comment by huang714669** [comment]
@chenshuai2144 
打扰了，umi-request 拦截失效的问题知道怎么回事吗？ 我想利用这个方法拦截request方法，更新token或者重定向登录页面。本来还想尝试使用interceptor拦截response获取token数据， 但是根本获取不到response data， 只有header，url， code这些。

**Comment by chenshuai2144** [comment]
response.json 来获得？

**Comment by huang714669** [comment]
@chenshuai2144 
不是很明白
我的interceptor是这样的，
![Screenshot from 2019-09-24 14-29-19](https://user-images.githubusercontent.com/13537904/65486914-4f861400-ded8-11e9-83fb-986fa81230be.png)

但是response里面没有后端返回的data，
![Screenshot from 2019-09-24 14-41-56](https://user-images.githubusercontent.com/13537904/65487483-90325d00-ded9-11e9-941f-fc23a818d12f.png)

 response.json返回‘ƒ json() { [native code] }’

**Comment by huang714669** [comment]
搞定了，参考了
#4084 
![image](https://user-images.githubusercontent.com/13537904/65488194-19965f00-dedb-11e9-86be-c1c8105dc628.png)
为什么这样引用就能获取data，感觉有必要在文档里面说明一下啊

**Comment by huang714669** [comment]
@chenshuai2144 @pl2476 多谢各位，问题已解决！
