### ISSUE TITLE
Dom  宽高根据屏幕大小设置

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#5306]
请教大佬们、如何根据  屏幕大小设置  dom 的宽和高

**Comment by chenshuai2144** [comment]
rem ?
https://developer.mozilla.org/zh-CN/docs/Web/CSS/length

**Comment by kzabc** [comment]
是因为我使用了bizchart  不能自动高度，导致  画布元素变形 ，我希望能头通过设置div 宽高解决， 想着获取屏幕分辨率 适配 不同窗口大小，

**Comment by guoziqin** [comment]
请问解决了吗 我这边尝试使用动画修改元素宽度 但是下拉框因为没有dom 必须触发创建dom后 才适应宽度， 现在我仍未找到解决方案
