### ISSUE TITLE
UmiJs automatic routing

### ISSUE THREAD

**Issue by michshat** [ant-design/ant-design-pro#5307]
Awesome project - thank you!!!

Quick question, I following UmiJs routing rules that's supposed to automatically handle it, however can't seem to get it working. Does it mean ant-design-pro doesn't support it?

![image](https://user-images.githubusercontent.com/13825309/65337442-268f1780-db96-11e9-830d-0ff24778cd04.png)

**Comment by chenshuai2144** [comment]
Configuring a route is different from a contract route.

pro is  configuring route, you need config `config.ts`

**Comment by michshat** [comment]
Ok. Good to know. Thank you.
