### ISSUE TITLE
关于动态菜单的问题，从后台加载菜单

### ISSUE THREAD

**Issue by liyi563257046** [ant-design/ant-design-pro#5308]
在文档中写着“从服务器请求菜单
你可以在 src/layouts/BasicLayout.tsx 中修改 menuDataRender，并在代码中发起 http 请求，只需服务器返回下面格式的 json 即可。”
可是我在BasicLayout.tsx代码里并没有找到setMenuData、menuData 数据格式的定义，是文档没更新吗？还是我理解错了

**Comment by chenshuai2144** [comment]
看这里

https://github.com/ant-design/ant-design-pro-layout
