### ISSUE TITLE
pro中修改之后，menu中图标和文字不能水平对齐，foot layout中也不能

### ISSUE THREAD

**Issue by lddlww** [ant-design/ant-design-pro#5309]
如下所示：
![image](https://user-images.githubusercontent.com/27006237/65367171-ff048180-dc5f-11e9-9523-c7f4d7b79463.png)

**Comment by chenshuai2144** [comment]
你是不是全局覆盖了 icon 的 css？ antd 官网是没有问题

**Comment by lddlww** [comment]
我把antd相关组件卸载，再重新安装也不行--

**Comment by lddlww** [comment]
我引用了iconfont图标，不知道这个有没有影响

**Comment by lddlww** [comment]
还有一个问题：就是如果不是从menu菜单栏路由，而是直接在浏览器中输入地址访问，则iconfont图标一律不会显示，如下所示：只有antd中icon有显示
![image](https://user-images.githubusercontent.com/27006237/65381643-3b9bb000-dd28-11e9-9a39-bd43fd2689fd.png)

**Comment by chenshuai2144** [comment]
来个最小的重现仓库吧

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5318
