### ISSUE TITLE
本项目的代码缩进可以调成默认4空格缩进不？

### ISSUE THREAD

**Issue by aihua** [ant-design/ant-design-pro#531]
默认的2空格缩进，老年人阅读不太方便嘞。显示屏目前普遍19寸以上，代码纸质打印的也不多，能改成默认4空格缩进不，免得每次要转代码缩进？虽然google或airbnb是使用2空格缩进，咱能突破下陈规不？ @sorrycc @luolonghao @lifesinger @yiminghe @pingan1927

**Comment by chenshuai2144** [comment]
下个格式化工具..自己调整把!
https://prettier.io/docs/en/options.html

**Comment by aihua** [comment]
OK. 看来只能eslint规则做这些调整了：

"indent": ["error", 4],
"react/jsx-indent": ["error", 4],
"react/jsx-indent-props": ["error", 4],
