### ISSUE TITLE
windows下umi block list无法交互，最新umi也不行

### ISSUE THREAD

**Issue by WenGuangZhu** [ant-design/ant-design-pro#5311]
![1](https://user-images.githubusercontent.com/32136240/65375926-ef6f5200-dccc-11e9-99a4-42ae2932520c.png)

**Comment by WenGuangZhu** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
你用的什么终端？
我用的 powershell 做测试。

**Comment by chenshuai2144** [comment]
Configuring a route is different from a contract route.

pro is  configuring route, you need config `config.ts`
