### ISSUE TITLE
ant design pro如何使未被使用的变量呈灰色？比如一些import导入但未使用的组件名

### ISSUE THREAD

**Issue by fenghuolibie** [ant-design/ant-design-pro#5313]

**Comment by chenshuai2144** [comment]
这个是 eslint 和 vscode 做的。
https://pro.ant.design/blog/use-eslint-typescript-cn

**Comment by fenghuolibie** [comment]
> 这个是 eslint 和 vscode 做的。
> https://pro.ant.design/blog/use-eslint-typescript-cn

官网我试过了，还是不行。有一个ant pro2的项目不用vscode的eslint插件也可以有隐藏效果，这个ant pro 4不行。能否把这个操作讲细一点，我再试试
