### ISSUE TITLE
login成功后无法跳转到dashboard

### ISSUE THREAD

**Issue by hioak** [ant-design/ant-design-pro#5314]
场景及问题描述如下。
1、下载ant-desing-pro源代码，安装依赖并运行。
2、清除浏览器缓存，并输入：http://localhost:8000/user/login地址，进入到登录界面。
3、在用户名和密码都输入正确的情况下登录，系统未跳转到dashboard界面，而是停在登录界面。

截图如下：
![图片](https://user-images.githubusercontent.com/3831083/65389801-438d3b80-dd8c-11e9-9254-b51dd1629759.png)

![图片](https://user-images.githubusercontent.com/3831083/65389827-80f1c900-dd8c-11e9-8272-5b476ceba723.png)

![图片](https://user-images.githubusercontent.com/3831083/65389832-8fd87b80-dd8c-11e9-86ad-197aa35464bf.png)

![图片](https://user-images.githubusercontent.com/3831083/65389833-99fa7a00-dd8c-11e9-800f-5b156163cfe1.png)

**Comment by DWAO** [comment]
同疑问，参照V2 在login.ts 添加reloadAuthorized 也不起作用 @chenshuai2144

**Comment by xiexy1206** [comment]
js版本没有这个问题。

TS版本验证账号密码后：
        const params = getPageQuery();
        let { redirect } = params as { redirect: string };
1. redirect有概率是undefined，页面不跳转。
2. redirect有概率是undefined，页面有概率会跳转。

困扰中，大家有解决这个问题的办法了吗？

**Comment by wangweikang** [comment]
```
handleSubmit = (err: any, values: FromDataType) => {
    const { type } = this.state;
    if (!err) {
      const { dispatch } = this.props;
      ((dispatch({
        type: 'userLogin/login',
        payload: {
          ...values,
          type,
        },
      }) as unknown) as Promise<any>)
      .then(() => this.props.history.push('/dashboard/workplace'))
    }
  };
```

**Comment by iceandfire777** [comment]
![image](https://user-images.githubusercontent.com/32257175/66698647-38d22080-ed12-11e9-8995-df8c375f8061.png)

会提示类型错误。
测试有遇到错误的账号密码也可以登录到主页

**Comment by babizhu** [comment]
同样的问题，history.replace(redirect || '/');
打断点发现replace同样是undefined,
但是第一次登陆不能跳转，第二次登陆就能跳转了

**Comment by xiaofsu** [comment]
> 同样的问题，history.replace(redirect || '/');
> 打断点发现replace同样是undefined,
> 但是第一次登陆不能跳转，第二次登陆就能跳转了

老哥解决了吗？我也是，但我是第一次刷新无法跳转，第二次刷新就可以跳转了。
