### ISSUE TITLE
表单上传组件只有第一个文件上传时才会触发回调事件？后面都无效？

### ISSUE THREAD

**Issue by Cancerbin** [ant-design/ant-design-pro#5315]
上传logo的时候，只有第一次才能获取回调返回的结果，后面执行都不会触发回调，请问如何解决？（当拥有以下代码时）
`if (Array.isArray(e)) {
      return e;
    }
    return e && e.fileList;`

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/2423
