### ISSUE TITLE
BasicLayout 布局下的 tab 页 title 如何去掉？

### ISSUE THREAD

**Issue by linancc** [ant-design/ant-design-pro#5316]
![微信截图_20190923120650](https://user-images.githubusercontent.com/33574533/65401435-a61d2080-ddfa-11e9-9415-d5f01dece2e0.png)

**Comment by chenshuai2144** [comment]
可以在 在 ProLayout 中设置 title。
https://github.com/ant-design/ant-design-pro-layout#prolayout
