### ISSUE TITLE
动态菜单问题

### ISSUE THREAD

**Issue by duxiaojiao** [ant-design/ant-design-pro#5317]
使用的是v4.0版本，菜单是从后端动态取的。
现在点击菜单之后，不会有选中的效果，然后选中一个二级菜单，其他展开的二级菜单会自动收缩这个功能也没了。
看了下其他issue，设置selectedKeys这个属性，是可以保持选中效果，但是当前选中的菜单这个数据不知道从哪里获取，onSelect这个方法试了下，没有效果
![image](https://user-images.githubusercontent.com/12755475/65409266-d6c08280-de19-11e9-93ea-5bd9a139a3fe.png)

**Comment by chenshuai2144** [comment]
试试 onOpenChange, 也可以试试 menuProps。

**Comment by mzrybbd** [comment]
可以看看动态菜单实现的代码吗？

**Comment by chenshuai2144** [comment]
@mzrybbd  https://ant-design.github.io/ant-design-pro-layout/
试试这个代码
