### ISSUE TITLE
我在defaultSetting.ts里设置了url，在config的路由配置了设置了icon: 'wld-activity'，为什么这个图标显示不出来啊？

### ISSUE THREAD

**Issue by MrWuhan** [ant-design/ant-design-pro#5318]
解决了，v2版本我在BaseMenu的getIcon函数里加了自定义icon名称的替换。v4版本BaseMenu已经提取到pro-layout了，所以菜单的自定义icon前缀是'icon-'和阿里巴巴矢量图标库一致就行

_Originally posted by @xlszzck in https://github.com/ant-design/ant-design-pro/issues/5265#issuecomment-532493416_

**Comment by xyy7260** [comment]
@MrWuhan 请问一下我也是按照文档 defaultSettings/   iconfontUrl: '//at.alicdn.com/t/font_1935376_l28glhad4of.js' 设置了
然后在routers {
  path: '/cases',
      name: '管理',
      icon: 'icon-hospital',
....
}
不显示
![image](https://user-images.githubusercontent.com/23183393/87114129-61d41180-c2a2-11ea-80ec-d7424e45eebd.png)
