### ISSUE TITLE
Extra scroll bar in chart card

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#532]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/507615/34453694-64ee2534-ed95-11e7-81dd-eb7dce47bc5f.png">

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34473663-868b5bae-efb0-11e7-8e2d-f25f21b51cc7.png) 
window用户得颤抖

**Comment by WhatAKitty** [comment]
windows上这个真心太丑，antd没有滚动条组件吗？

**Comment by chenshuai2144** [comment]
只有chrome支持自定义滚动条吧

**Comment by WhatAKitty** [comment]
没有啊，都支持的

**Comment by afc163** [comment]
@nikogu
