### ISSUE TITLE
执行npm run lint:fix 报错No configuration provided for '/src/global.less'

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#5323]
![image](https://user-images.githubusercontent.com/20454290/65476722-6d428180-deb6-11e9-8fb5-3cf585d60304.png)

请问执行npm run lint:fix 报No configuration provided for '/src/global.less'，这个该如何解决呀？

**Comment by chenshuai2144** [comment]
开个可重现的仓库吧

**Comment by chenrui95** [comment]
请问怎么解决的呢
