### ISSUE TITLE
为啥 fetchCurrent 两次？

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design-pro#5324]
求解惑。
在 BasicLayout 里面有一次，在 SecurityLayout 里面还有一次

**Comment by chenshuai2144** [comment]
SecurityLayout 是用 fetchCurrent 判断权限的，是个demo。
BasicLayout  是为了展示 右上角的 icon

**Comment by TianEnPang** [comment]
BasicLayout中fetchCurrent注释掉也可以正常展示头像

**Comment by TianEnPang** [comment]
@chenshuai2144 所以BasicLayout中的fetchCurrent有必要写吗？可以只用SecurityLayout中的fetchCurrent吗？

**Comment by tozzz** [comment]
按我自己目前使用情况来看是可以去掉的，不过我也挺疑惑为什么BasicLayout这里还需要fetchCurrent

**Comment by TianEnPang** [comment]
> 按我自己目前使用情况来看是可以去掉的，不过我也挺疑惑为什么BasicLayout这里还需要fetchCurrent

我是注释掉了。

**Comment by tozzz** [comment]
> > 按我自己目前使用情况来看是可以去掉的，不过我也挺疑惑为什么BasicLayout这里还需要fetchCurrent
> 
> 我是注释掉了。

想了下，大概明白作者的意思了。那个SecurityLayout只是个简单实现了登录鉴定的demo，很多人不一定会按这种方式实现，如果有些人去掉了这个SecurityLayout,那就导致无法拉取到用户信息了，所以在BasicLayout里才会也有fetchCurrent，当然这里fetchCurrent如果加个判断currentUser是否存在就更好了。
