### ISSUE TITLE
关于兼容IE9+问题

### ISSUE THREAD

**Issue by jeffrey-liu2333** [ant-design/ant-design-pro#5326]
用ie9-ie10打开会提示
` [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.`

然后页面就挂了,看起来是全球化的问题,这个时候我该怎么去解决呢

**Comment by chenshuai2144** [comment]
`
[React Intl] TheIntlAPIs must be available in the runtime, and do not appear to be built-in. AnIntl polyfill should be loaded
`
这个说的很清楚了, 试试配置 target

https://www.npmjs.com/package/react-intl-polyfill
