### ISSUE TITLE
4.0如何配置请求到服务端呢

### ISSUE THREAD

**Issue by xiexy1206** [ant-design/ant-design-pro#5327]
没有找到这个文件：.roadhogrc.mock.js。
有新的配置方法吗？

**Comment by mark5566** [comment]
Same question.

**Comment by mark5566** [comment]
config/config.ts

**Comment by mark5566** [comment]
config/config.ts文件下，大概210行，有个proxy被注释了，修改成想访问地址

**Comment by mark5566** [comment]
#5283参考这个的

**Comment by mark5566** [comment]
#5283

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#proxy

**Comment by mark5566** [comment]
@chenshuai2144 thank you,It's work for me,You should to run script(npm run start:no-mock)
