### ISSUE TITLE
[Help wantetd] I use the request correctly?

### ISSUE THREAD

**Issue by GENiALi** [ant-design/ant-design-pro#5329]
Hi
I planned for a new project use Ant Design Pro. My first step is now to implement our authentication via JWT token.

Is this basically a correct code?

```
export async function accountLogin(params: LoginParamsType) {
  const sendData = `grant_type=password&username=${params.userName}&password=${params.password}&........`;
  const retValue = request('https://localhost:44308/connect/token', {
      method: 'POST',
      data: sendData,
      mode: 'no-cors',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        Accept: 'application/json',
      },
      body: 'string',
    });
  return retValue;
}
```

I've already asked Stackoverflow.
[How to get the token from response?](https://stackoverflow.com/questions/58075265/how-to-get-the-token-from-response)

**Comment by chenshuai2144** [comment]
I can't see your picture, can you upload it again?
China's network is not very good

**Comment by GENiALi** [comment]
Hi

https://github.com/GENiALi/images/blob/master/antd/Status200.png
https://github.com/GENiALi/images/blob/master/antd/response.png

**Comment by GENiALi** [comment]
I have forked your repo an [implement a sample](https://github.com/GENiALi/ant-design-pro/commit/d4b80f61d9b5e790162252ab44ade37545ce668f).
It is a simple API call that not work. But I don't know if I understand it correctly.

**Comment by GENiALi** [comment]
When I use request from umi-request, then works.

services\login.ts
```typescript
// import request from '@/utils/request';
import request from 'umi-request';
..........
export async function accountLogin(params: LoginParamsType) {
  return request.get('https://api.github.com/emojis')
    .then(function (response) {
      console.log(response);
      return response;
    })
    .catch(function (error) {
      console.log(error);
    });
}
```

**Comment by chenshuai2144** [comment]
try this code.

```

// import request from '@/utils/request';
import request from 'umi-request';
..........
export async function accountLogin(params: LoginParamsType) {
  return request.get('https://api.github.com/emojis')
    .then(function (response) {
      console.log(response.clone().json());
      return response;
    })
    .catch(function (error) {
      console.log(error);
    });
}

```

you need this doc https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by GENiALi** [comment]
Or this?
https://github.com/umijs/umi-request
umi-request has a good documentation.

**Comment by GENiALi** [comment]
Can you please post your answer on Stackoverflow? I accept then your answer.

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-request is base on fetch. 
They are almost the same.
