### ISSUE TITLE
最精简的优秀代码

### ISSUE THREAD

**Issue by manyhelp** [ant-design/ant-design-pro#5330]
在 Ant Design Pro 4.0 中， Layout 抽离成了单独的组件。Ant Design Pro 中，使用 umi 进行区块管理。

我想说的是：能不能再精简？

比如我只要顶部菜单布局，固定页面宽度，固定 Header。
这些配置不希望通过代码的判断来实现，而是直接的最精简代码。

能不能通过再优化一下yarn create umi

**Comment by chenshuai2144** [comment]
感觉你需要的是可视化 开发。试试我们的 umi ui

**Comment by manyhelp** [comment]
@chenshuai2144  

没有整体风格设置啊。顶部菜单布局这些都没有

**Comment by chenshuai2144** [comment]
这个暂时还做不到，你可以把 SettingDrawer 放出来

**Comment by whaty** [comment]
> 这个暂时还做不到，你可以把 SettingDrawer 放出来

v4怎么放出来啊
