### ISSUE TITLE
This relative module was not found:  * ../list/search in ./src/pages/.umi/router.js[问题]

### ISSUE THREAD

**Issue by wxm0019** [ant-design/ant-design-pro#5331]
这是按照官网一步一步来的，在运行安装装所有区块后，运行npm start 就出现了这个问题，我去文件里改了，写的都一样啊，还是报错，该怎么处理啊

**Comment by chenshuai2144** [comment]
这个问题是区块没有下载成功造成的。再次尝试安装试试。
或者直接使用 [all-blocks](https://github.com/ant-design/ant-design-pro/tree/all-blocks) 分支
