### ISSUE TITLE
[antdesign pro脚手架 如何进行webpack配置]

### ISSUE THREAD

**Issue by AixsCode** [ant-design/ant-design-pro#5332]
**问题描述** 
最近在antdesiginpro下 使用到react-monaco-editor 需要配置编辑器高亮
**示例代码** [如果有必要，展示代码，线上示例，或仓库]
https://github.com/react-monaco-editor/react-monaco-editor 提示需要进行配置
 Add the Monaco Webpack plugin monaco-editor-webpack-plugin to your webpack.config.js:

const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
module.exports = {
  plugins: [
    new MonacoWebpackPlugin({
      // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
      languages: ['json']
    })
  ]
};
需要配置这些信息，所以 antdesginpro 下的webpack.config.js文件在哪里，如何暴露出来，进行修改

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#chainwebpack
你需要的是这个

**Comment by silence-githHub** [comment]
请问楼主你是怎么解决的？我刚好也碰到了这个问题，求赐教

**Comment by ShadowJobs** [comment]
能不能答案贴出来。官网写的太简单了，要各种尝试。又得半天

**Comment by zhoujiaxu2014** [comment]
楼主搞定了吗 目前也是遇到该问题
