### ISSUE TITLE
[问题] preview 站点实在太慢了

### ISSUE THREAD

**Issue by endink** [ant-design/ant-design-pro#5334]
为什么不在国内做 cdn 加速，资源都是来自 aws cloudfront， 阿里系不用阿里云？

**Comment by afc163** [comment]
阿里云要钱，我们没有钱。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/5289#issuecomment-532566982

**Comment by endink** [comment]
是 preview 站点慢，帮助文档镜像解决不了问题，阿里云还要和蚂蚁的一个的开源项目收钱，这简直......

**Comment by afc163** [comment]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/507615/65577497-7ad73480-dfa6-11e9-9e8d-4e9edc2cebd9.png">

**Comment by afc163** [comment]
事情没这么简单，国内项目要备案，流程对于开源项目过于复杂，而且 design 域名也不能备案。

**Comment by endink** [comment]
好吧， close 吧， 最后那个一样的，Azure?? 资源文件还是很慢，比 aws 稍好一点点吧
