### ISSUE TITLE
页面加载时显示的title怎么修改？

### ISSUE THREAD

**Issue by Noa-p** [ant-design/ant-design-pro#5335]
![image](https://user-images.githubusercontent.com/43284700/65577647-cbe72880-dfa6-11e9-91b4-8c3a93c590f2.png)

**Comment by chenshuai2144** [comment]
proLayout 有个 title 的 props。

**Comment by Noa-p** [comment]
这是什么？依赖包里的吗？好像没有用到

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout

是这个
