### ISSUE TITLE
[问题] 一个modal表单组件，通过传递formData默认赋值，这时候拉伸浏览器宽度，会将表单填入的值清空

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5338]
**问题描述** 
 一个modal表单组件，通过传递formData使用mapPropsToFields默认赋值，这时候拉伸浏览器宽度，会将表单没有默认值的清空。
因为拉申浏览器的时候，改变了界面左边栏菜单的布局，从而出发了props的变化，传递了一个空对象，从而触发了mapPropsToFields, 会清空没有默认值的表单的数据。
该如何修复？

**Comment by chenshuai2144** [comment]
> 因为拉申浏览器的时候，改变了界面左边栏菜单的布局，从而出发了props的变化

should 里面做一下判断

**Comment by z-lionel** [comment]
> > 因为拉申浏览器的时候，改变了界面左边栏菜单的布局，从而出发了props的变化
> 
> should 里面做一下判断

不好意思， 请问有例子和文档吗？ 还是不知道在哪里加
mapPropsToFields(props) {
   if (formData.id) {
        return {
          id: Form.createFormField({
            value: formData.id,
          })
      }
   }
   return null;
}

我的子组件是这样的， 该如何用should做判断？

**Comment by chenshuai2144** [comment]
https://reactjs.org/docs/react-component.html#shouldcomponentupdate

是这个生命周期。你要不把 from 做成受控的

**Comment by z-lionel** [comment]
> https://reactjs.org/docs/react-component.html#shouldcomponentupdate
> 
> 是这个生命周期。你要不把 from 做成受控的
组件用的是react hook, 还是用form.setFieldsValue,赋值吧,谢谢了
