### ISSUE TITLE
[问题]无法build

### ISSUE THREAD

**Issue by jiangby123** [ant-design/ant-design-pro#5341]
**问题描述** [详细地描述问题，让大家都能理解]
基于antd 2.2.0版本自己开发的代码
无论是npm run build 还是yarn build都不成功
mac环境和centos7.4环境也都一样报错
**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/47846791/65593916-22169480-dfc4-11e9-869c-441517a3f395.png)
这是哪里有问题，还请指点

**Comment by chenshuai2144** [comment]
来个最小重现吧。怀疑是你的 webpack 插件问题

**Comment by jiangby123** [comment]
> 来个最小重现吧。怀疑是你的webpack插件问题

![image](https://user-images.githubusercontent.com/47846791/65606911-42ebe380-dfde-11e9-8702-368d188420d4.png)
我只是在源码的基础上新增了两个页面，其他没有改动过，我的webpack插件是4.41.0版本的，我改如何达到最小重现呢？抱歉～新手一枚

**Comment by jiangby123** [comment]
> 来个最小重现吧。怀疑是你的 webpack 插件问题

![image](https://user-images.githubusercontent.com/47846791/65615379-ceb83c80-dfeb-11e9-81f1-4b8e134a206d.png)
我在npm start的时候会有这个报错，我不确定是不是引起build不成功的原因

**Comment by chenshuai2144** [comment]
你的 tsconfig 改成 pro 官方的吧

**Comment by jiangby123** [comment]
> 你的 tsconfig 改成 pro 官方的吧

感谢您的支持～
