### ISSUE TITLE
使用v2在js中怎么跳转路由

### ISSUE THREAD

**Issue by chenjiangyo** [ant-design/ant-design-pro#5343]
**问题描述** [详细地描述问题，让大家都能理解]
在后端写了一个登陆拦截器 如果没有session会返回一个错误  然后 前端有个对所有返回值进行处理的js方法，可以获取到后端返回的异常 。 但是不知道怎么才能调到登陆页面。 拜托各位大神帮帮忙。

export function checkResponse(response) {
  const rspHead = response.RSP_HEAD;
  if (rspHead.TRAN_SUCCESS === false) {
    if (rspHead.ERROR_MESSAGE === '[BS000021]会话超时！') {
      routerRedux.push('/user/login');                                                       这行没有效果
      return false;
    }
    notification.error({ message: rspHead.ERROR_MESSAGE });
    return false;
  }
  return true;
}
方法写在 js文件中。

**Comment by xiashei** [comment]
你可以在issue里面搜搜routerRedux
或者用
import router from 'umi/router';
router.push。另外首先检查一下是否进入了if (rspHead.ERROR_MESSAGE === '[BS000021]会话超时！')  循环

**Comment by chenjiangyo** [comment]
谢谢。我去研究一下。
