### ISSUE TITLE
build后文件 ie11下报错（已查看issues前面的相似问题，不能解决）

### ISSUE THREAD

**Issue by kawaiiz** [ant-design/ant-design-pro#5346]
**问题描述** [详细地描述问题，让大家都能理解]
1.当项目不打包 dev 情况下 360浏览器极速模式报错，build后360不报错
2.ie在dev和build后都是报错
![image](https://user-images.githubusercontent.com/25151442/65734987-09af9280-e108-11e9-8b16-3689a8d8328d.png)
报错原因未知
![image](https://user-images.githubusercontent.com/25151442/65735065-48dde380-e108-11e9-8838-1117254f9a7f.png)
这是官网示例，在ie打开也报错。
已使用的方法：
1.设置targets为11  
targets: {
    ie: 11,
  },
2.注释代码切割 
 // dynamicImport: {
      //   loadingComponent: './components/PageLoading/index',
      //   webpackChunkName: true,
      //   level: 3,
      // },
3.设置代码切割的level为5

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]
在该项目自己只引入了两个额外的包，这两个包都很有名，想必应该对ie11兼容很好
![image](https://user-images.githubusercontent.com/25151442/65735151-b4c04c00-e108-11e9-9a6e-1b4210edf7f7.png)

**Comment by kawaiiz** [comment]
报错的地方
![image](https://user-images.githubusercontent.com/25151442/65736293-14205b00-e10d-11e9-99df-602e8f35d65b.png)

**Comment by kawaiiz** [comment]
@chenshuai2144    不好意思  能麻烦看一下吗？

**Comment by kawaiiz** [comment]
报错的地方
![image](https://user-images.githubusercontent.com/25151442/65745032-fb27a200-e12c-11e9-8d7b-49cb3b30d8e7.png)

**Comment by kawaiiz** [comment]
这是开了map 后 找到的报错的地方
![image](https://user-images.githubusercontent.com/25151442/65762190-042b6a00-e153-11e9-85c6-428fc03a707d.png)

**Comment by chenshuai2144** [comment]
删掉这个插件吧 
webpack-theme-color-replacer,怎么会把这个打包进去

**Comment by kawaiiz** [comment]
![image](https://user-images.githubusercontent.com/25151442/65824541-59739280-e29d-11e9-8f42-88cb4f38e591.png)
这是修改全局颜色的 （我从github上直接下载的包）

**Comment by kawaiiz** [comment]
![image](https://user-images.githubusercontent.com/25151442/65826136-74043680-e2b2-11e9-8b83-a9ef1624e299.png)
在这里打印    ie  没有打印信息  
![image](https://user-images.githubusercontent.com/25151442/65826157-a746c580-e2b2-11e9-8092-67c2aaa8210f.png)

应该是我代码问题，毕竟master 拉下来可以运行。

我也没用什么少见的api呀，几乎都是es6 ， async/await ，这为什么会报错呢，真的不懂呀，写法和写vue没什么区别呀，

**Comment by kawaiiz** [comment]
https://github.com/sorrycc/blog/issues/68
使用这个webpack-theme-color-replacer不报错了
但是又报了antd es/style/index 里语法错误 好吧 真难

**Comment by chenshuai2144** [comment]
> 几乎都是es6 ， 

ie 不支持 es6 的

> 但是又报了antd es/style/index 里语法错误 好吧 真难

你的 target 没有配置吧

**Comment by kawaiiz** [comment]
已经看了issues里相关的问题了，设置了target（最新版默认就有targets:{ie:11}）

**Comment by chenshuai2144** [comment]
现在本地开发也能在 ie11 中拍起来了

**Comment by kawaiiz** [comment]
> 现在本地开发也能在 ie11 中拍起来了

可能是我的问题吧。ie11是跑不起来的。就 看不懂哪里报错，就图片也可以报错，然后页面spin一直在转。logo 在BasicLayout中使用的。就这么放着了

![image](https://user-images.githubusercontent.com/25151442/78008434-3f149180-7372-11ea-97e5-710715392547.png)

![image](https://user-images.githubusercontent.com/25151442/78008459-43d94580-7372-11ea-8c95-cb2681965051.png)

![image](https://user-images.githubusercontent.com/25151442/78008568-623f4100-7372-11ea-95a6-49d6cd1ae78a.png)

![image](https://user-images.githubusercontent.com/25151442/78008618-7420e400-7372-11ea-9596-58a0c1f1b085.png)

**Comment by pxim** [comment]
我也试了，没鸟用
