### ISSUE TITLE
[BUG] V4 登录跳转异常

### ISSUE THREAD

**Issue by DWAO** [ant-design/ant-design-pro#5348]
**bug 描述** 
整合SecurityLayout 对前端进行权限检查。在登录界面需要登录成功两次才能正常跳转到首页

**复现步骤** 
修改config.ts 的路由

**期望结果** 
登录成功一次跳转到首页

**复现代码** [提供可复现的代码，仓库，或线上示例]
{
    path: '/',
    component: '../layouts/SecurityLayout',
    Routes: ['src/pages/Authorized'],
    routes: [

    {
        path: '/',
        component: '../layouts/BasicLayout',
        Routes: ['src/pages/Authorized'],
        // authority: ['admin', 'user'],
        routes: [{
            path: '/',
            name: 'welcome',
            icon: 'smile',
            component: './Welcome',
        },
        {
            path: 'http://www.baidu.com',
            name: 'hello',
            icon: 'smile',
            // component: './Hello',
        },
        {
            name: 'basic-list',
            path: '/basic-list',
            icon: 'rocket',
            component: './basic-list',
        },
        ],
    },
    ],
},

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by kaoding** [comment]
流程：登录成功就跳转到SecurityLayout ，但在 SecurityLayout 要获取当前用户，在获取用户需要时间，这时候 isLogin 还没有获取值，
` const isLogin = currentUser && currentUser.userid;`
接下来再有下面的跳转到登录界面的操作
```
   if (!isLogin) {
      return <Redirect to={`/user/login?${queryString}`}></Redirect>;
    }
```
如果是第二次（或者没有刷新浏览器）就要登录2次（点击的很快可能要更多次数），所以这里点问题

**Comment by DWAO** [comment]
> 
> 
> 流程：登录成功就跳转到SecurityLayout ，但在 SecurityLayout 要获取当前用户，在获取用户需要时间，这时候 isLogin 还没有获取值，
> ` const isLogin = currentUser && currentUser.userid;`
> 接下来再有下面的跳转到登录界面的操作
> 
> ```
>    if (!isLogin) {
>       return <Redirect to={`/user/login?${queryString}`}></Redirect>;
>     }
> ```
> 
> 如果是第二次（或者没有刷新浏览器）就要登录2次（点击的很快可能要更多次数），所以这里点问题

有什么好的解决办法么？

**Comment by mytheshow** [comment]
另外一个BUG，当用户是登陆状态时候，访问一个没有权限的路由，不会跳转到403页面，而是跳转到了登陆页`pages\Authorized.jsx`
`
return (
    <Authorized
      authority={getRouteAuthority(location.pathname, routes) || ''}
      noMatch={isLogin ? <Redirect to="/exception/403" /> : <Redirect to="/user/login" />}
    >
      {children}
    </Authorized>
  );
`

**Comment by unrealsmart** [comment]
登陆按钮点击时，应当给按钮添加`loading`状态，并禁用（在 `dispatch` 之前设置`disabled`属性），以防止重复请求。

`currentUser` 使用`SecurityLayout`是必须获取的，检查服务端是否有相应属性的输出，`currentUser` 属性跟预设不同的话，可以自己去`interface`里面修改！

`SecurityLayout` 也可以按照自己的逻辑修改。

模型 `*fetchCurrent` 也可以自由修改。

**Comment by kernelogic** [comment]
Routes: ['src/pages/Authorized']  这个一定要加吗？这个是做什么的？

**Comment by pingchangxinli** [comment]
![WeChat Image_20191006215452](https://user-images.githubusercontent.com/19421090/66278164-1470e100-e8d9-11e9-8d71-0f269c8d2cae.png)
@DWAO 
登录成功跳转到SecurityLayout后，在componentDidMount中 setState和dispatch执行问题，setState触发render，此时dispatch loading状态暂未更新到，会导致isReady变为true，会跳到
`if (!isLogin) {
      return <Redirect to={`/user/login?${queryString}`}></Redirect>;
    }`，跳转回登录页面，后面登录loading会有值，所有可以登录

**Comment by ft20082** [comment]
render 中跳转这个操作有问题，应该在 model 中处理，这样就会避免这个问题。

**Comment by ft20082** [comment]
@DWAO 把项目原样clone 下来，只是在 if (!isLogin) { return <Redirect to={/user/login?${queryString}}></Redirect>; } 这个代码前面加上 console.log(...) 也会出现跳转不成功。

**Comment by Locusc** [comment]
你可以在SecurityLayout请求fetchCurrent的时候在类里面设置一个判断请求是否完成的标识符
callback后判断如果请求完成 将这个标识符setState为true
render的时候 判断这个标识符为True才进入isLogin的判断

**Comment by MichaelXu1983** [comment]
我的方法是用登录后返回的`userid`来判断是否登录，修改如下：
`src/layouts/SecurityLayout.jsx` 中 `const isLogin = currentUser && currentUser.userid;` 改成：`const isLogin = login && login.userid;`

**Comment by feifanlee** [comment]
> 录后返回的`userid`来判断

用login来判断的问题在于，刷新就会跳出登录状态。

**Comment by feifanlee** [comment]
> 
> 
> 我的方法是用登录后返回的`userid`来判断是否登录，修改如下：
> `src/layouts/SecurityLayout.jsx` 中 `const isLogin = currentUser && currentUser.userid;` 改成：`const isLogin = login && login.userid;`

用login来判断的问题在于，刷新就会跳出登录状态

**Comment by chenshuai2144** [comment]
每次刷新从服务器重新获取就行了吧

**Comment by lerence** [comment]
用callback来修改isReady，修改src/layouts/SecurityLayout.tsx：
```
componentDidMount() {
    const { dispatch } = this.props;
    if (dispatch) {
      dispatch({
        type: 'user/fetchCurrent',
        callback: () => {
          this.setState({
            isReady: true,
          });
        },
      });
    }
  }
```
userModel 修改：
```
*fetchCurrent({ callback }, { call, put }) {
      const response = yield call(queryCurrent);
      yield put({
        type: 'saveCurrentUser',
        payload: response,
      });
      if (callback && typeof callback === 'function') {
          callback();
      }
    }
```

**Comment by feifanlee** [comment]
我貌似解决这个问题了，直接上代码。
```js
componentWillMount(){
    const { dispatch } = this.props;
    if (dispatch) {
      dispatch({
        type: 'user/fetchCurrent',
      });
    }
  }
  
  componentDidMount() {
    
    let delaySet = ()=>this.setState({isReady: true})

    setTimeout(() => {delaySet()},0)

  }

```

**Comment by C-SF-C** [comment]
请问修改后，登陆还是不能正常跳转，需要刷新一次登陆页面，重新输入账户密码登陆，才能正常跳转

**Comment by feifanlee** [comment]
要不把setTimeout的时间调长点，调到1000等1秒

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/67930999-f9ee0700-fbfb-11e9-865d-efd6e0d29b67.png)

https://github.com/ant-design/ant-design-pro/issues/5348#issuecomment-538797766

**Comment by TianEnPang** [comment]
> 我貌似解决这个问题了，直接上代码。
> 
> ```js
> componentWillMount(){
>     const { dispatch } = this.props;
>     if (dispatch) {
>       dispatch({
>         type: 'user/fetchCurrent',
>       });
>     }
>   }
>   
>   componentDidMount() {
>     
>     let delaySet = ()=>this.setState({isReady: true})
> 
>     setTimeout(() => {delaySet()},0)
> 
>   }
> ```

确实解决了，请问这是个什么原理😂

**Comment by jinuem** [comment]
Even after using the code which @feifanlee mentioned above, but still, this issue persists.

**Comment by BarrySong97** [comment]
> 用callback来设置isReady，修改src/layouts/SecurityLayout.tsx：
> 
> ```
> componentDidMount() {
>     const { dispatch } = this.props;
>     if (dispatch) {
>       dispatch({
>         type: 'user/fetchCurrent',
>         callback: () => {
>           this.setState({
>             isReady: true,
>           });
>         },
>       });
>     }
>   }
> ```
> 
> userModel 修改：
> 
> ```
> *fetchCurrent({ callback }, { call, put }) {
>       const response = yield call(queryCurrent);
>       yield put({
>         type: 'saveCurrentUser',
>         payload: response,
>       });
>       if (callback && typeof callback === 'function') {
>           callback();
>       }
>     }
> ```

这个方法算是比较好的解决了，还是有一个回调好一点。

**Comment by jinuem** [comment]
@BarrySong97  I have changed as per your code. but still not redirecting after login. :(

**Comment by Leskur** [comment]
哈哈，我的做法就比较简单粗暴了。
```js
if (!isLogin && '/user/login' != window.location.pathname) {
    return <Redirect to={`/user/login?${queryString}`}></Redirect>;
}
```

**Comment by juwencheng** [comment]
可以通过`Promise`定义`sleep`方法，使用`yield call(sleep, 100)`实现延时效果。

```js
// sleep 方法
const sleep = (delay) => new Promise((resolve) => setTimeout(resolve, delay))

// 在login 的effects中调用，延迟100ms
yield call(sleep, 100);
```
