### ISSUE TITLE
[需求]增加区块组的概念，可以通过添加区块组的操作一次添加多个区块

### ISSUE THREAD

**Issue by ft20082** [ant-design/ant-design-pro#5349]
**需求描述** [详细地描述需求，让大家都能理解]
我们有很多功能都是重复开发，想通过微服务提供服务，一个微服务对应一组功能，如果按照规范，需要做到多个区块，既然已经支持了区块，增加对区块组的支持应该改动不大。
**解决方案** [如果你有解决方案，在这里清晰地阐述]
通过区块组快速操作多个区块，也可以管理一个区块组中的部分区块，包含添加、删除功能，这样可以更方便的做公司内部的共享，重复的前后端服务功能都不需要开发。

同时建议官方维护一个区块的市场，前端的功能和后端的功能最好绑定，后端服务以 docker 方式提交，这样方便大家共享代码

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/guide/umi-ui.html
试试这个吧。图形化之后会使用起来会更简单
