### ISSUE TITLE
对封装的request提一些建议

### ISSUE THREAD

**Issue by eyasliu** [ant-design/ant-design-pro#535]
我在使用 request的时候，遇到一些问题，在这里提一些建议：

1. 错误提示，在request做了全局的 notification 提示，而且这个提示只要status出现了400 以上就无法取消，有时候请求虽然是错误了，但是希望是自己去做错误处理，比如登录验证失败返回401，这是很常见的
2. 错误处理后，返回的 error.response 的body还是个ReadStream，所以要去获取到body里面的东西还真挺困难的，错误返回的body也是很重要的，应该能方便获取才对
3. request中直接将body用 JSON.stringify 序列化了，显然是没考虑FormData的情况（#260 提的就是该问题，#149 也并不是解决该问题的）

**Comment by chenshuai2144** [comment]
>1.  错误提示 

可以在error.js里面自己修改..耦合的并不是很强.

>2.错误处理

可以看看这里 [Response](https://developer.mozilla.org/zh-CN/docs/Web/API/Response)
> 3. body序列化

这个是千人千面的事情,我推荐你自己做一些处理.比如根据不同的头,进行不同的序列化

```
if (options.headers['Content-Type'] === 'application/json') {
      options.body = JSON.stringify(options.body);
} else {
      options.body = qs.stringify(options.body);
}
```

**Comment by eyasliu** [comment]
1. 如果是指 services/error.js , 这里的只能是修改模拟接口，如果是 `src/error.js`，这里是对错误后续的统一处理，这没问题，我可以自己去定义，但是 notification 的提示应该可以去掉才对，因为不是每个错误请求都是需要一个提醒的
2. 3. 是打算让用户自己去做处理，对吗

**Comment by chenshuai2144** [comment]
是的! 我们搭建一个项目.但是不同的项目有不同的操作逻辑.
开箱即用是不可能的.
我们提供模板项目,你们可以在上面着自己的修改.
你想去掉 notification  直接删除代码就好了.
我们的目标是提供component 级别的复用.
但是具体的业务.我们尽量满足.但是业务之千奇百怪是没有定式的

**Comment by eyasliu** [comment]
了解，谢谢回复！
