### ISSUE TITLE
[BUG] safari 13.1 版本 input输入框输入中文非常卡

### ISSUE THREAD

**Issue by fallenner** [ant-design/ant-design-pro#5350]
**bug 描述** 
safari 13.1 版本 input输入框输入中文非常卡

**复现步骤** 
用safari 13.1版本打开 [pro预览网站](https://preview.pro.ant.design/form/basic-form),输入中文。

**期望结果** 
safari 输入中文不会卡顿

**复现代码** [pro官方预览网站](https://preview.pro.ant.design/form/basic-form)

**版本信息:**

- Ant Design Pro 版本: [e.g. 2.2.1]
- umi 版本 
- 浏览器环境 [safari 13.1]
- 开发环境 [e.g. mac OS]

**其他信息** 
现在生产环境用的2.2.1，但是官方预览网站也一样很卡

**Comment by miguo4** [comment]
我也遇见这个问题了

**Comment by chenshuai2144** [comment]
google 搜了一圈，看起来是 safari 的问题。WordPress  之类的工具都遇到了中文卡顿问题。

https://talk.synyan.net/14465
试试这个?

**Comment by kxcy001123** [comment]
> google 搜了一圈，看起来是 safari 的问题。WordPress 之类的工具都遇到了中文卡顿问题。
> 
> https://talk.synyan.net/14465
> 试试这个?

相同的环境，safari同时打开antdpro中文输入卡顿， 但是自己封装的基于antd组件的页面没有出现卡顿。

**Comment by chenshuai2144** [comment]
@kxcy001123  我的电脑是最新的 safari，也没有感觉到卡顿，是不是还有别的条件

**Comment by kenvies** [comment]
线上反馈我代码有问题，可我怎么都找不到原因，😣

**Comment by chenshuai2144** [comment]
safari 浏览器已经变成新时代的 ie 了。
@kenvies  把依赖全部更新，然后 重新发布一下试试
