### ISSUE TITLE
[BUG]ant design pro table title 和个人中心菜单 国际化切换语言需要手动刷新

### ISSUE THREAD

**Issue by well-monkey** [ant-design/ant-design-pro#5351]
**bug 描述** [详细地描述 bug，让大家都能理解]
https://preview.pro.ant.design/dashboard/analysis
1.以官网例子来讲，我严格的按照官网的进行了国际化 并在table 数组 columns 的title进行了国际化 。
当切换语言的时候 table 表头的语言并没有更新 需要手动的刷新一下
2.个人中心也有类似的问题。需要刷新才会更换语言

**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
https://preview.pro.ant.design/dashboard/analysis
1打开链接 实例网址
2.点击切换语言 繁体中文
3.点开语言旁边头像 下拉菜单显示 显示默认的语言 如英文
4.刷新页面 点开语言旁边头像  下拉菜单显示 繁体中文
5.问题总结：点击切换语言 个人中心下拉菜单并不会更新语言 需要手动更新
6.类似问题复现于 table的表头
**期望结果** [描述你原本期望看到的结果]
点击切换语言 个人中心下拉菜单 显示更改语言 table 表头切换语言  无需刷新

**复现代码** [提供可复现的代码，仓库，或线上示例]
线上4.0.0代码
**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
最稳妥的办法是刷新页面，table 有性能优化，会尽量少的重复渲染。context 修改他没有重新刷新，
别的页面也是同样的道理。

**Comment by well-monkey** [comment]
那想请问一下 个人中心下拉菜单 也是这个原因吗？

**Comment by chenshuai2144** [comment]
是的，没有触发渲染

**Comment by maokty** [comment]
1. 用组件来渲染
title: <FormattedMessage id='xxxx' />,
2. 个人中心菜单  => 升级下dva的依赖

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/faq-cn#%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80%E6%97%B6%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E8%AF%AD%E8%A8%80%E6%97%A0%E6%B3%95%E5%88%87%E6%8D%A2
