### ISSUE TITLE
如何引用less文件不使用css module?

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design-pro#5355]
使用react-transition-group的css动画时, 他需要在引用的less文件里面写入
```
.item-enter {
  opacity: 0;
}
.item-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}
.item-exit {
  opacity: 1;
}
.item-exit-active {
  opacity: 0;
  transition: opacity 500ms ease-in;
}
```
目前我只能放在`global.less`里面, 来代替引用, 直接`import './index.less'`好像是无效的, 因为做了css Module. 只能`import styles from './index.less'`
请问如何可以直接`import './index.less'`
不然我可能要放在global.less里面, 可能有全局污染的可能性

**Comment by chenshuai2144** [comment]
```
:global  {
  你的 css 
}
```

**Comment by DerrickTel** [comment]
谢谢大佬
