### ISSUE TITLE
nginx启动压缩配置后，前端页面ERR_CONTENT_LENGTH_MISMATCH [问题]

### ISSUE THREAD

**Issue by HQ1363** [ant-design/ant-design-pro#5356]
**问题描述** [详细地描述问题，让大家都能理解]
# gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";
nginx配置启用上述官网给的压缩配置后，前端页面ERR_CONTENT_LENGTH_MISMATCH，接口请求虽然是200，但实际前端解析response是failed，去掉这部分配置即可恢复，还望解答下？

猜测：压缩配置似乎压缩了接口返回的内容，而不只针对静态文件(html/css/js等)

**Comment by chenshuai2144** [comment]
你的压缩有点过了。

gzip_min_length 100k; 

压缩级别太高会造成浏览器没法解压 js 的

**Comment by chenshuai2144** [comment]
因为 nginx 配置了反向代理吧
