### ISSUE TITLE
[BUG]antd pro v4 侧边栏无法设置收起

### ISSUE THREAD

**Issue by Lumend** [ant-design/ant-design-pro#5357]
已设置model/global.jx  collapsed: true
进入时在basicLayout 打印 collapsed 出来仍为 true,
但马上又调用了 changeLayoutCollapsed 致使 collapsed 变为了 false，

需要怎么设置才可以使侧边栏默认收起？

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/

这里是没有问题的。是你本地的改动造成的吗？

**Comment by Lumend** [comment]
> https://preview.pro.ant.design/
> 
> 这里是没有问题的。是你本地的改动造成的吗？

我重新下载当前 master,
修改 src/models/global.ts 行39，修改为 collapsed: false
修改 config/defaultSettings.ts 添加配置 collapsed: false

刷新后，侧边栏仍处于展开状态

**Comment by chenshuai2144** [comment]
https://ant.design/components/layout-cn/#components-layout-demo-responsive

你估计碰到了这个问题。Layout 会自动判断展开收起

**Comment by tichamp** [comment]
临时解决方案^o^: 
https://blog.csdn.net/c5211314963/article/details/110210991
