### ISSUE TITLE
修改Ant Dseign Pro组件PageHeaderWrapper默认添加Title[问题]

### ISSUE THREAD

**Issue by Tiny-1985** [ant-design/ant-design-pro#5358]
现在PageHeaderWrapper 组件根据当前的路由填入 title，我不想要这个title怎么去掉呢，我使用<PageHeaderWrapper  title=""></PageHeaderWrapper>不管用，求教，谢谢！

**Comment by chenshuai2144** [comment]
`<PageHeaderWrapper title={false} />`

**Comment by Tiny-1985** [comment]
谢谢

**Comment by YuriyCn** [comment]
请问下设置了默认隐藏不显示，还是会占有行高这个怎么解决？

**Comment by yuyueweb** [comment]
> 请问下设置了默认隐藏不显示，还是会占有行高这个怎么解决？

pageHeaderRender={()=>{
          return false
        }}
