### ISSUE TITLE
s-table在翻页多选中，参数丢失[BUG]

### ISSUE THREAD

**Issue by loveFemi** [ant-design/ant-design-pro#5359]
**bug 描述** [详细地描述 bug，让大家都能理解]
表格完成渲染后，第一页勾选一个数据，翻页，再勾选一个数据，触发的onchange事件中第一个参数selectedRowKeys是勾选数据的rowkey数组，第二个参数selectedRows是勾选数据的信息数组，但是翻页后打印出来的selectedRowKeys是正常两个，selectedRows只有最后一页中的数据。
**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/34272706/65857215-f87bb580-e395-11e9-9297-b6ccb30c865c.png)
![image](https://user-images.githubusercontent.com/34272706/65857249-0598a480-e396-11e9-94cf-d30aa8f599b8.png)
如上，onSelectChange中打印的第二个参数只有后面那一页中的数据
**期望结果** [描述你原本期望看到的结果]
我特意测试了a-table中这个参数是正常的，希望在s-table中也能正常使用
**复现代码** [提供可复现的代码，仓库，或线上示例]
<s-table
          :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"
          :columns="columns"
          :customRow="rowClick"
          rowKey="id"
          bordered
          ref="table"
          :data="tabledata">
          <span slot="serial" slot-scope="text, record, index">
            {{ index + 1 }}
          </span>
        </s-table>
 onSelectChange (selectedRowKeys, selectedRows) {
      this.selectedRowKeys = selectedRowKeys
      this.selectedRows = selectedRows
      console.log(selectedRowKeys, selectedRows)
    },
**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by loveFemi** [comment]
嗯？结构好像掉了呢？
<s-table
          :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"
          :columns="columns"
          :customRow="rowClick"
          rowKey="id"
          bordered
          ref="table"
          :data="tabledata">
          <span slot="serial" slot-scope="text, record, index">
            {{ index + 1 }}
          </span>
        </s-table>
这样的

**Comment by chenshuai2144** [comment]
a-table 和 c table 是什么

**Comment by afc163** [comment]
> a-table是antd中本来的表格组件啊，c table我没有用哦，我用的是你们封装的s-table

不知道你在说什么，这几个词看不太懂
