### ISSUE TITLE
[问题]如何去除4.0版本的底层footer.

### ISSUE THREAD

**Issue by lihuiheng** [ant-design/ant-design-pro#5365]
**问题描述** 
目前使用4.0版本的ant design pro .问下如何去除关于底层的footer.

**其他信息** 
Ant Design ProAnt Design
Copyright  2019 蚂蚁金服体验技术部出品
如上述信息.尝试了几个其他方法都无效.

**Comment by afc163** [comment]
@chenshuai2144 最好把这些文案作为属性写到 pro 的源码里，不然用户咨询太多了。

**Comment by liujiayii** [comment]
在layouts里面吧……

**Comment by lihuiheng** [comment]
我看过,无法修改.找不到那串文字,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LIUJIAYI"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月2日(星期三) 上午10:25
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"522068028"<522068028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] [问题]如何去除4.0版本的底层footer. (#5365)




在layouts里面吧……

**Comment by liujiayii** [comment]
https://github.com/ant-design/ant-design-pro/blob/21e1794335dd7c523db5d40306a05710ead43eb5/src/layouts/UserLayout.tsx#L57

**Comment by lihuiheng** [comment]
<DefaultFooter /&gt;


这行我注释过,没效果.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LIUJIAYI"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月4日(星期五) 中午11:22
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"522068028"<522068028@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] [问题]如何去除4.0版本的底层footer. (#5365)




https://github.com/ant-design/ant-design-pro/blob/21e1794335dd7c523db5d40306a05710ead43eb5/src/layouts/UserLayout.tsx#L57

**Comment by poyiding** [comment]
> **问题描述**
> 目前使用4.0版本的ant design pro .问下如何去除关于底层的footer.
> 
> **其他信息**
> Ant Design ProAnt Design
> Copyright 2019 蚂蚁金服体验技术部出品
> 如上述信息.尝试了几个其他方法都无效.
在BasicLayout 组件里，footerRender() 自定义footer

**Comment by poyiding** [comment]
> 我看过,无法修改.找不到那串文字,
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"LIUJIAYI"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月2日(星期三) 上午10:25 收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;; 抄送:&nbsp;"522068028"<522068028@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [ant-design/ant-design-pro] [问题]如何去除4.0版本的底层footer. (#5365) 在layouts里面吧…… — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

在BasicLayout 组件里，footerRender() 自定义footer

**Comment by poyiding** [comment]
> **问题描述**
> 目前使用4.0版本的ant design pro .问下如何去除关于底层的footer.
> 
> **其他信息**
> Ant Design ProAnt Design
> Copyright 2019 蚂蚁金服体验技术部出品
> 如上述信息.尝试了几个其他方法都无效.

在BasicLayout 组件里，footerRender() 自定义footer

**Comment by chenshuai2144** [comment]
https://ant-design.github.io/ant-design-pro-layout/?path=/story/basiclayout--custom-footer
看看这个 demo

**Comment by lihuiheng** [comment]
thanks!



522068028@qq.com
 
发件人： 陈帅
发送时间： 2019-10-10 15:06
收件人： ant-design/ant-design-pro
抄送： lihuiheng; Author
主题： Re: [ant-design/ant-design-pro] [问题]如何去除4.0版本的底层footer. (#5365)
Closed #5365.
