### ISSUE TITLE
[BUG] 项目警告Function components cannot be given refs.以及lifecycle methods been renamed

### ISSUE THREAD

**Issue by TianEnPang** [ant-design/ant-design-pro#5368]
**BUG描述** ：
新建的项目，启动打开welcome页面时控制台报错
`
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `ResizeObserver`.
`
以及出现大量react生命周期方法已被重命名，不建议使用的警告。

**复现步骤** ：
新建最新项目并启动进入welcome页面即可发现

**期望结果** ：
希望解决Function components cannot be given refs. 警告
以及react生命周期方法已被重命名，不建议使用的警告。

**版本信息:**：
- Ant Design Pro 版本：【4.0.0】
- umi 版本： 【2.9.6】
- Node 版本：【10.16.3】
- 浏览器环境：【Google Chrome 77.0.3865.90】
- 开发环境：【Windows 10 1903】

**警告截图** ：
![批注 2019-10-04 024500](https://user-images.githubusercontent.com/32772271/66156202-c8f9d100-e653-11e9-9580-f69630c4f4d2.jpg)

**Comment by TianEnPang** [comment]
新版本react生命周期方法警告已解决

解决办法规定react 和 react-dom版本

请求帮助解决此问题
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? Check the render method ofResizeObserver.`

**Comment by chenshuai2144** [comment]
都是 第三方库的问题，pro 中的代码已经完全迁移，等待社区处理吧

**Comment by TnWah** [comment]
同样的报错，Pro代码clone后设置为topmenu时会出现，sidemenu正常

**Comment by qsk617** [comment]
同样，设layout: 'topmenu',就报错。。。sad`

**Comment by websmallrabbit** [comment]
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Comment by websmallrabbit** [comment]
+1 同样的问题，有解决的大神吗

**Comment by TianenPang** [comment]
@chenshuai2144 
感觉是 `@ant-design\pro-layout\lib\TopNavHeader\index.js` 渲染 `ResizeObserver` 组件的时候造成的
太复杂看不懂，等待官方解决吧😂

**Comment by chenshuai2144** [comment]
Build之后就没有这个warning了

**Comment by TianenPang** [comment]
> Build之后就没有这个warning了

请问在开发环境如何解决这个报错呢？

**Comment by wangtiegang** [comment]
强迫症患者，看到 pro 升级就想升级，看到 warning 就浑身难受😂

**Comment by afc163** [comment]
排查一下是哪里的问题，直接来 PR。
