### ISSUE TITLE
使用umi block add AccountCenter 命令报错，不能添加区块Error: Command failed: npm install numeral@^2.0.6 react-router@^4.3.1 --registry=https://registry.npm.taobao.org --save[问题]

### ISSUE THREAD

**Issue by xishanxu** [ant-design/ant-design-pro#5369]
**问题描述** [详细地描述问题，让大家都能理解]

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/43942406/66173648-c8792e80-e683-11e9-90c4-f07f7b70b876.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-cli#debug
看看这个
