### ISSUE TITLE
antd pro npm build err: Unexpected token: name (hans) 

### ISSUE THREAD

**Issue by zzyyzz1992** [ant-design/ant-design-pro#537]
UPDATE: I found that this issue may caused by webpack, one of my requirement named `pinyin` failed to convert to es5, does any one know how to just exclude this node requirement in webpack?

**Production build err, pls help me! the code works fine in debug mode**
**Here is the console output:**
C:\Users\zzyyz\WebstormProjects\Web>npm run build

 ant-design-pro@0.3.0 build C:\Users\zzyyz\WebstormProjects\Web> 
roadhog build

Creating an optimized production build...
Failed to compile.

**0.b7a33753.async.js from UglifyJs
Unexpected token: name (hans) [0.b7a33753.async.js:62885,6]**

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@0.3.0 build: `roadhog build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Here is the err log:**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\zzyyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v6.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@0.3.0~prebuild: ant-design-pro@0.3.0
6 info lifecycle ant-design-pro@0.3.0~build: ant-design-pro@0.3.0
7 verbose lifecycle ant-design-pro@0.3.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@0.3.0~build: PATH: C:\Users\zzyyz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\zzyyz\WebstormProjects\Web\node_modules\.bin;C:\Program Files\VanDyke Software\Clients\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Android\android-sdk\tools\;C:\Users\zzyyz\gradle\bin\;C:\Program Files\nodejs\;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files\Git\cmd;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Users\zzyyz\scoop\shims;C:\Users\zzyyz\AppData\Local\Microsoft\WindowsApps;C:\Users\zzyyz\AppData\Roaming\npm;C:\Users\zzyyz\Documents\Path;C:\Users\zzyyz\AppData\Local\atom\bin
9 verbose lifecycle ant-design-pro@0.3.0~build: CWD: C:\Users\zzyyz\WebstormProjects\Web
10 silly lifecycle ant-design-pro@0.3.0~build: Args: [ '/d /s /c', 'roadhog build' ]
11 silly lifecycle ant-design-pro@0.3.0~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@0.3.0~build: Failed to exec build script
**13 verbose stack Error: ant-design-pro@0.3.0 build: `roadhog build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\zzyyz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\zzyyz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)**
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid ant-design-pro@0.3.0
15 verbose cwd C:\Users\zzyyz\WebstormProjects\Web
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zzyyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v6.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@0.3.0 build: `roadhog build`
22 error Exit status 1
23 error Failed at the ant-design-pro@0.3.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
name是个什么变量？

**Comment by zzyyzz1992** [comment]
@chenshuai2144 name 是个let出来的变量，引用的第三方库。现在已经去掉这个库就好了。
