### ISSUE TITLE
在Login界面能不能获取到BasicLayout里的路由列表？登录界面this.props.route只能获取到登录的

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5370]

**Comment by 904492381** [comment]
因为我每个用户的菜单可能是不一样的，登录后动态菜单，登录显示的第一个页面可能是不一样的，不能让他都重定向到同一个路由，我想获取到他的全部路由然后筛选出可以进入的路由。或者说有什么其他办法实现这个功能吗

**Comment by chenshuai2144** [comment]
this.props.route只能在 layout 中获取。

**Comment by 904492381** [comment]
> this.props.route只能在 layout 中获取。

只能获取自身layout的route吗

**Comment by chenshuai2144** [comment]
是的 你可以直接import config.ts
