### ISSUE TITLE
[问题] 如何能强制登录验证？

### ISSUE THREAD

**Issue by kernelogic** [ant-design/ant-design-pro#5374]
默认模式下登录验证并不是必须的，访问/welcome可以不需要验证，为什么？如何设置成必须登录？

**Comment by chenshuai2144** [comment]
pro 中已经默认了 admin 的权限。你可以删除这个默认。具体代码在这里
https://github.com/ant-design/ant-design-pro/blob/4d74e3eb2863008ebec61f03a2d38be98c03e979/src/utils/authority.ts#L20

**Comment by kernelogic** [comment]
删了也不管用啊，依然可以直接访问/welcome
我看了当前localStorage里面antd-pro-authority的值是["guest"]

**Comment by kernelogic** [comment]
就是默认的啊，新由yarn create umi创建的项目，去掉这几行以后，/welcome依然可以自由访问

**Comment by kernelogic** [comment]
any one?

**Comment by DusuWen** [comment]
真的被这个权限要整疯了

**Comment by lihe6666** [comment]
@DusuWen 彻底疯了 

![image](https://user-images.githubusercontent.com/2598007/93202980-34b24c80-f786-11ea-9f36-3dea17100e23.png)


![image](https://user-images.githubusercontent.com/2598007/93202950-282df400-f786-11ea-8cba-7b3be69191aa.png)

还是能进入到这个页面，只是看不见了！这不符合逻辑
