### ISSUE TITLE
[BUG] windows操作系统下npm run format-imports 失败

### ISSUE THREAD

**Issue by zxf4399** [ant-design/ant-design-pro#5375]
**bug 描述** 
windows操作系统执行npm run format-imports，执行失败。

**复现步骤**
进入项目根目录，执行npm run format-imports

**期望结果**
sort imports 成功

**复现代码** 
npm run format-imports

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
4.0.0

- umi 版本
2.9.6

- 浏览器环境
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

- 开发环境 [e.g. mac OS]
windows10

**其他信息** [如截图等其他信息可以贴在这里]

![format-imports image](https://user-images.githubusercontent.com/55656772/66370597-65fd9680-e9d3-11e9-89a2-78cce111048c.PNG)

**Comment by zxf4399** [comment]
我已经定位到问题，是否可以提交PR？

**Comment by chenshuai2144** [comment]
非常欢迎 pr

**Comment by zxf4399** [comment]
@chenshuai2144 已经提交pr
