### ISSUE TITLE
菜单两个主路由，定义两个path，引用的同一个主路由中的子路由组件，如果如果子路由不是该主路由的目录下，左侧菜单没有蓝色选中效果

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5376]
**问题描述**
菜单两个主路由，定义两个path，引用的同一个主路由中的子路由组件，如果如果子路由不是该 
主路由的目录下，菜单无法蓝色选中效果

想达成的效果是两个页面公用一个组建，
分别在两个页面的路由下定义不同的路径，但是引用的是一个页面下的组件，
下面的定义的路由可以实现，但是/space/problem的路由左侧菜单没有蓝色选中效果

**示例代码** 
config 配置如下
[ {
              name: 'space',
              path: '/space',
              icon: 'home',
              routes: [
                {
                  name: 'work',
                  path: '/space/work',
                  component: './space/work/table/list',
                },
                {
                  path: '/space/problem',
                  component: './problem/table/list/components/add',
                  name: 'add',
                  hideInMenu: true,
                },
              ],
            },
           {
              path: '/problem',
              name: 'problem',
              icon: 'question-circle',
              routes: [
                {
                  path: '/problem',
                  component: './problem/table/list',
                },
                {
                  path: '/problem/add',
                  component: './problem/table/list/components/add',
                  name: 'add',
                  hideInMenu: true,
                },
       }
]

**Comment by chenshuai2144** [comment]
来个最小的可重现仓库吧

**Comment by zhang0ZGC** [comment]
你已经将`/space/problem`设置为 `hideInMenu:true` 了，它不会出现在菜单项里面，当然也不会高亮

**Comment by z-lionel** [comment]
> 你已经将`/space/problem`设置为 `hideInMenu:true` 了，它不会出现在菜单项里面，当然也不会高亮

问题是/problem/add 选中的时候, 也设置了隐藏,,菜单/problem会高亮
可能是因为组件是在这个菜单的目录里面

**Comment by leshalv** [comment]
是的，我也发现了
![image](https://user-images.githubusercontent.com/30397655/67732783-72579b00-fa37-11e9-87e2-1bb41fc7176f.png)
