### ISSUE TITLE
如何支持 ant-design 不支持的语言？

### ISSUE THREAD

**Issue by blackcater** [ant-design/ant-design-pro#5380]
**问题描述**

我想在项目中支持印尼语，印尼语在 ant-design 中并不存在，在 ant-design-pro 项目下添加 `in-ID.js` 和 `in-ID` 目录后，编译运行会报错：

![image](https://user-images.githubusercontent.com/9465551/66377817-e4aeff80-e9e4-11e9-999c-462d3347ee4f.png)

![image](https://user-images.githubusercontent.com/9465551/66377735-c6490400-e9e4-11e9-9539-6267962a1fc6.png)

> 有没有什么办法，可以让 ant-design 不支持的语言使用本地的配置或者使用其他语言作为降级方案？

**Comment by chenshuai2144** [comment]
给 antd 的官方提一个 pr 吧。 antd 的发布周期一般为一周一次
或者通过 props 来自定义。
