### ISSUE TITLE
[需求]antdpro v4如何自定义面包屑导航

### ISSUE THREAD

**Issue by 389567702** [ant-design/ant-design-pro#5381]
左侧菜单中列表菜单，需求是点击列表进入详情页，面包屑导航需要将 （首页>列表>详情），显示出来；项目有多个这种不固定内容的面包屑导航。请问如何实现呢？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/blob/master/README.zh-CN.md#pageheaderwrapper
https://ant.design/components/page-header/
支持  breadcrumb 配置

**Comment by 389567702** [comment]
> https://github.com/ant-design/ant-design-pro-layout/blob/master/README.zh-CN.md#pageheaderwrapper
> https://ant.design/components/page-header/
> 支持 breadcrumb 配置，这两个文档可以结合起来看一看

刚要艾特您还没发出去，就看到回复啦~之前v2的面包屑升级到V4不好使，在basicLayout跟自己的页面中没找到相关的配置参数，还请详细说明~多谢

**Comment by 389567702** [comment]
通过PageHeader添加的面包屑导航生效，但面包屑导航默认跳转地址是hash模式，config里面已经将history改为brower，此问题如何解决？@chenshuai2144

**Comment by Jiexiansen** [comment]
> 通过PageHeader添加的面包屑导航生效，但面包屑导航默认跳转地址是hash模式，config里面已经将history改为brower，此问题如何解决？@chenshuai2144

老哥，这个问题如何解决的？

**Comment by Jiexiansen** [comment]
> > 通过PageHeader添加的面包屑导航生效，但面包屑导航默认跳转地址是hash模式，config里面已经将history改为brower，此问题如何解决？@chenshuai2144
> 
> 老哥，这个问题如何解决的？

![image](https://user-images.githubusercontent.com/26481272/110915083-2e2a1980-8352-11eb-88ac-10b94e4de5f6.png)
https://ant.design/components/breadcrumb-cn/

是不是只有这个方式？
