### ISSUE TITLE
用户登录是放到BasicLayout的话，每次都需要重新请求，带来的403和401问题？[问题]

### ISSUE THREAD

**Issue by HQ1363** [ant-design/ant-design-pro#5382]
用户接口登录是放到BasicLayout里的，导致每次刷新页面，都会去请求login接口，用户如果都登录了，实际上不应该去请求。其次，layout只是控制布局一块的内容，并非页面body主体，这就导致了， 如果我的页面，存在多个umi-request异步接口请求，而非登录的接口提前返回的话，就会导致前端报403，但实际上，应该先完成login接口，再去调用其他的接口，这块请求有办法解吗，暂时个人未找到解决办法。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/8aa1400b34233d19c09e00157fd9daae0e29aaa7/src/layouts/SecurityLayout.tsx
在这里做就好了
