### ISSUE TITLE
How to change the settings for different layouts?[问题]

### ISSUE THREAD

**Issue by GauravG8** [ant-design/ant-design-pro#5383]
**问题描述** [详细地描述问题，让大家都能理解]
I want to use a different theme for some of the pages of my site using the Ant Design Pro template. The defaultSettings.ts in `config` folder is applied to all the pages. How can I create and apply different settings to a new layout?
[翻译 Translation (来自Google ): 我想使用Ant Design Pro模板为网站的某些页面使用不同的主题。 config文件夹中的defaultSettings.ts将应用于所有页面。如何创建不同的设置并将其应用于新布局？]

**Comment by chenshuai2144** [comment]
Pro does not support this usage, but we support the url parameter to modify, you can use this method to dynamically modify

**Comment by GauravG8** [comment]
Thank you for your response. Which url parameter? How do I change it? Can you please provide some references that I can use? 

I am trying to change the pageTitle in the header, which is also why I had asked if we can change the settings. The title in the settings gets applied to all pages using the ProLayout with sidebar. How can I change the pageTitle in the menu header to be different for different pages?

![Ant Design pro Menu header](http://falcon.coffeeinc.in/uploads/img/GgsXI7ewokJ8sqwib4VXI9bTRG3SWzeSUK7SyaOj.png)

For example, I want to change the title 'Ant Design Pro' to 'Admin' in one page and to 'Settings' in another. How can I do that?

**Comment by poyiding** [comment]
> Thank you for your response. Which url parameter? How do I change it? Can you please provide some references that I can use?
> 
> I am trying to change the pageTitle in the header, which is also why I had asked if we can change the settings. The title in the settings gets applied to all pages using the ProLayout with sidebar. How can I change the pageTitle in the menu header to be different for different pages?
> 
> ![Ant Design pro Menu header](https://camo.githubusercontent.com/3927c936882cb8f4656abcdc7f7d831d9ba60529/687474703a2f2f66616c636f6e2e636f66666565696e632e696e2f75706c6f6164732f696d672f47677358493765776f6b4a3873717769623456584939625452473353577a6553554b375379614f6a2e706e67)
> 
> For example, I want to change the title 'Ant Design Pro' to 'Admin' in one page and to 'Settings' in another. How can I do that?

you can in getSetting() of setting.ts, according to different url pathName setting title, For example
`    if (urlParams.pathname === 'xxxxx') {
        state.title = 'your title';
      }`

**Comment by GauravG8** [comment]
Thanks for clarifying that. I also was able to modify a few of the settings using `<ProLayout />` props for theme, title and navigation. 

Thanks again @chenshuai2144 for the awesome work you have been doing with this project.
