### ISSUE TITLE
[BUG] git commit 时 lint-staged:js 导致一大堆eslint报错

### ISSUE THREAD

**Issue by pointline** [ant-design/ant-design-pro#5387]
**bug 描述** [详细地描述 bug，让大家都能理解]
yarn create umi my-app
初始化一个新项目git commit 提交代码出现大段报错，导致无法git提交代码，lint-staged:js 无法通过
**复现步骤** [清晰描述复现步骤，让别人也能看到问题]

**期望结果** [描述你原本期望看到的结果]

**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.9.6
- 浏览器环境 
- 开发环境 [e.g. windows]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
来个截图，让我看一下你的 create umi 的版本

**Comment by pointline** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/26851754/66619600-063fff00-ec10-11e9-8196-d283e6e825cc.png)

**Comment by pointline** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/26851754/66619649-4bfcc780-ec10-11e9-88e1-c5fc9fa28e4a.png)
谢谢

**Comment by chenshuai2144** [comment]
```
 src/pages/user/login/components/Login/LoginItem.jsx:87:1
  ✖  87:1   Line 87 exceeds the maximum line length of 100.                          max-len

  src/layouts/SecurityLayout.jsx:27:1
  ✖  27:1   Line 27 exceeds the maximum line length of 100.                          max-len

  src/global.jsx:47:1
  ✖  47:1   Line 47 exceeds the maximum line length of 100.                          max-len

  src/components/SettingDrawer/themeColorClient.js:3:19
  ✖   3:19  Requires eslint-enable directive for import/no-extraneous-dependencies.  eslint-comments/disable-enable-pair

  src/components/NoticeIcon/NoticeList.jsx:40:28
  ✖  40:28  Do not nest ternary expressions.                                         no-nested-ternary

```

发现了 4 个错误，非常感谢

**Comment by afc163** [comment]
pro-blocks 里要有 ci。

**Comment by chenshuai2144** [comment]
@afc163  是相同的，但是转化为 js 之后造成的

**Comment by afc163** [comment]
@chenshuai2144 我意思是 ci 里要有转换到 js 后的 lint 任务。

**Comment by pointline** [comment]
@chenshuai2144 是JS版不能提交，TS版是正常的，那有什么好的解决办法呢？

**Comment by chenshuai2144** [comment]
修掉这些错误就好了，大部分都是简单的错误

**Comment by hezhongfeng** [comment]
选择js的，安装完毕后先使用`npm run lint:fix`修复，然后剩下的就是注释太长（换行就好了）和一个嵌套三目运算

**Comment by chenshuai2144** [comment]
在 区块中已经全部解决

**Comment by leohxj** [comment]
我这刚刚运行还是这个问题，需要先执行 npm run lint:fix
