### ISSUE TITLE
[BUG]权限配置失效

### ISSUE THREAD

**Issue by zhangshuaidan** [ant-design/ant-design-pro#5388]
**bug 描述** [详细地描述 bug，让大家都能理解]
当我在/config/config.js配置了某个页面的路由权限后，当使用admin的用户登录，虽然左侧菜单栏隐藏了配置该权限的菜单，但是直接通过url输入的方式还是能到达该页面。
**复现步骤** [清晰描述复现步骤，让别人也能看到问题]

**期望结果** [描述你原本期望看到的结果]
url输入的方式 应当被拒绝访问
**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**其他信息** [如截图等其他信息可以贴在这里]
这是配置信息
![image](https://user-images.githubusercontent.com/27200655/66458630-c8bf6280-eaa5-11e9-8c36-c4bf4a77c5e0.png)
这是访问截图
![image](https://user-images.githubusercontent.com/27200655/66458696-f86e6a80-eaa5-11e9-8d4e-ecb54af5ec55.png)

**Comment by lishaoh** [comment]
+1

**Comment by lishaoh** [comment]
```js
const getRouteAuthority = (path, routeData) => {
  let authorities;
  routeData.forEach(route => {
// 新增判断
    if (route.authority) {
      authorities = route.authority;
    }

    // match prefix
    if (pathToRegexp(`${route.path}(.*)`).test(path)) {
      // exact match
      if (route.path === path) {
        authorities = route.authority || authorities;
      } // get child
      if (route.routes) {
        authorities = getRouteAuthority(path, route.routes) || authorities;
      }
    }
  });
  return authorities;
};
```

按照上面新增的判断，会导致子集路由的权限覆盖父级路由权限

**Comment by lishaoh** [comment]
目前测试OK了，解决代码如下：
Authorized.jsx
```js
const getRouteAuthority = (path, routeData) => {
  let authorities;
  routeData.forEach(route => {
    // if (route.authority) {
    //   authorities = route.authority;
    // }
    // match prefix
    if (pathToRegexp(`${route.path}(.*)`).exec(path)) {
      // exact match
      // if (route.path === path) {
      authorities = route.authority || authorities;
      // } // get child
      if (route.routes) {
        authorities = getRouteAuthority(path, route.routes) || authorities;
      }
    }
  });
  return authorities;
};
```

**Comment by chenshuai2144** [comment]
> 按照上面新增的判断，会导致子集路由的权限覆盖父级路由权限

这个是应该的吧

**Comment by lishaoh** [comment]
但是如果父级路由下有多个子路由，其中某一个子路由有权限，其他子路由没有权限，这个时候就会影响其他子路由了
应该是authorities = getRouteAuthority(path, route.routes) || authorities;覆盖了

**Comment by chenshuai2144** [comment]
有兴趣完善一下吗？这个 pr 也是最近新提交的

**Comment by alexPang6** [comment]
我现在也发现这个问题，会不会好多已经上线 de 系统也有这个问题？
