### ISSUE TITLE
TimelineChart的滚动条(SliderGen)图标及样式无法正常显示

### ISSUE THREAD

**Issue by Nuoky** [ant-design/ant-design-pro#539]
版本: "0.3.1"
https://github.com/ant-design/ant-design-pro/commit/2e0efbb04cd8c4aa6001d44821edb8dc85e25337
描述：TimelineChart的滚动条(SliderGen)图标及样式无法正常显示且Chrome调试面板Network中无失败请求及该图标请求。
问题图片：![image](https://user-images.githubusercontent.com/24731549/34469140-859c9abc-ef53-11e7-918c-16318395ab26.png)

**Comment by ddcat1115** [comment]
master 上图表底层刚更新过，最新的拖动按钮就长这样，不是展示问题

**Comment by Nuoky** [comment]
好的，谢谢回复，感觉没以前直观了。
