### ISSUE TITLE
umi的约定式路由

### ISSUE THREAD

**Issue by killvf** [ant-design/ant-design-pro#5394]
最近在做公司的项目，项目所需是需要权限控制。
在此基础上修改了`src/layouts/BasicLayout.tsx`文件后手动输入还是能够打开，而且必须在config中定义。
![image](https://user-images.githubusercontent.com/23251559/66535587-9fa5dd00-eb4c-11e9-8f1f-68b683208fd6.png)
然后看到了这个Umi的约定式路由。按照上面文档中的方法并不可行。
能否给予一个有效的方案或者案例

**Comment by xiaohuoni** [comment]
不行是因为你需要自己增加权限过滤

**Comment by killvf** [comment]
> 不行是因为你需要自己增加权限过滤

我是按照文档上`https://github.com/ant-design/ant-design-pro/commit/a22d400328a7a391ed5e5a5f2bba1a5fecf9fad7`来进行操作的，不行是指不能正常运行
