### ISSUE TITLE
[BUG] yarn i18n-remove 提示“编译失败”

### ISSUE THREAD

**Issue by baymaxbowen** [ant-design/ant-design-pro#5396]
**bug 描述** 
- 无法正常通过i18n-remove删除国际化
**复现步骤** 
`yarn i18n-remove 
`

`[~/Desktop/test2]$ yarn i18n-remove
yarn run v1.17.3
$ pro i18n-remove --locale=zh-CN --write
✔ 🕵️‍  find js or ts files
⠋ 📦  load all locale file and build ts /Users/baymax/Desktop/test2/node_modules/@types/react-redux/index.d.ts (92,85): Namespace '"/Users/baymax/Desktop/test2/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.
/Users/baymax/Desktop/test2/node_modules/@types/react-redux/index.d.ts (92,85): Namespace '"/Users/baymax/Desktop/test2/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.
/Users/baymax/Desktop/test2/node_modules/node-import-ts/lib/index.js:28
        throw new Error("编译失败");
        ^

Error: 编译失败
    at module.exports (/Users/baymax/Desktop/test2/node_modules/node-import-ts/lib/index.js:28:15)
    at /Users/baymax/Desktop/test2/node_modules/@ant-design/pro-cli/src/i18n/getLocalFileList.js:52:22
    at Array.map (<anonymous>)
    at module.exports (/Users/baymax/Desktop/test2/node_modules/@ant-design/pro-cli/src/i18n/getLocalFileList.js:52:6)
    at module.exports (/Users/baymax/Desktop/test2/node_modules/@ant-design/pro-cli/src/i18n/index.js:47:21)
    at Object.<anonymous> (/Users/baymax/Desktop/test2/node_modules/@ant-design/pro-cli/cli.js:36:32) `

**期望结果** 
`[~/Desktop/test2]$ yarn i18n-remove
yarn run v1.17.3
$ pro i18n-remove --locale=zh-CN --write
✔ 🕵️‍  find js or ts files
✔ 📦  load all locale file and build ts
✔ ✂️  remove locale for src/components/CopyBlock/index.tsx.
✔ ✂️  remove locale for src/components/GlobalHeader/AvatarDropdown.tsx.
✔ ✂️  remove locale for src/components/GlobalHeader/NoticeIconView.tsx.
✔ ✂️  remove locale for src/components/GlobalHeader/RightContent.tsx.
✔ ✂️  remove locale for src/components/SelectLang/index.tsx.
✔ ✂️  remove locale for src/global.tsx.
✔ ✂️  remove locale for src/layouts/BasicLayout.tsx.
✔ ✂️  remove locale for src/layouts/UserLayout.tsx.
✔ ✂️  remove locale for src/pages/result/success/index.tsx.
✔ ✂️  remove locale for src/pages/user/login/index.tsx.
✔ ✂️  remove locale for src/pages/Welcome.tsx.
✨  Done in 15.82s.`
**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: v4
- umi 版本：2.10.0
- 浏览器环境:chrome
- 开发环境 ：macOS

**解决办法** 
`yarn add hoist-non-react-statics@^3.3.0`
[来源](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35695#issuecomment-495708274)

**Comment by chenshuai2144** [comment]
来个重现的 仓库？或者来个修复的pr？

**Comment by baymaxbowen** [comment]
> 来个重现的 仓库？或者来个修复的 pr？

目前出现的情况是在macOS和win10下通过`yarn create umi` (ant-desgin-pro、typescript)==>`yarn`==> `umi block list` ==> `随便选一个block` (不转ts，不删除国际化)==> `yarn i18n-remove` 到这一步就会提示“编译失败”

![Snipaste_2019-10-16_16-38-28.png](https://i.loli.net/2019/10/16/lbkMA6fw2r5dYUW.png)

**Comment by chenshuai2144** [comment]
看样子是 ts 编译出了问题，我来修改一把。

**Comment by gaorubin1990** [comment]
最新版本的ts也报错啊。

**Comment by chenshuai2144** [comment]
fixed in https://github.com/chenshuai2144/node-require-ts/commit/154510ac515a9b960fef3f0cc52acb546545519a

**Comment by chenyu1990** [comment]
yarn create umi

**Comment by chenyu1990** [comment]
yarn create umi
and design pro
javascript
simple
yarn i18n-remove
问题依然存在

> fixed in [chenshuai2144/node-require-ts@154510a](https://github.com/chenshuai2144/node-require-ts/commit/154510ac515a9b960fef3f0cc52acb546545519a)

yarn create umi
and design pro
javascript
simple
yarn i18n-remove
问题依然存在
