### ISSUE TITLE
[问题]求教：有朋友使用ant design pro 脚手架嵌入rtsp流播放器的吗？

### ISSUE THREAD

**Issue by zhangpp2019** [ant-design/ant-design-pro#5397]
**问题描述** [详细地描述问题，让大家都能理解]

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
你需要写出你碰上了什么问题，不然很难被解决
