### ISSUE TITLE
spanish locales

### ISSUE THREAD

**Issue by windgaucho** [ant-design/ant-design-pro#5398]
How can I generate the locale files for spanish es-ES configuration?

I want to set spanish locale in the config/consig.js file, and I want to generate the locale files fot that, how can I do that?
```
      locale: {
        // default false
        enable: true,
        // default zh-CN
        default: 'es-ES',
        // default true, when it is true, will use `navigator.language` overwrite default
        baseNavigator: true,
      }
```

**Comment by chenshuai2144** [comment]
https://umijs.org/api/#locale
