### ISSUE TITLE
[需求]游客访问Pro的用户场景

### ISSUE THREAD

**Issue by yupeng957** [ant-design/ant-design-pro#5399]
**需求描述**

目前在开发一个项目其中有一个板块类似Github的Explore，游客和登录用户都可以浏览，此时的BasicLayout不能很好的满足需求，描述如下：

BasicLayout（layout：topmenu）顶部菜单会显示注册、登录两个菜单入口。尝试过配置注册、登录的routes的authority：['guest']，用户在未登录前currentAuthority=guest，登录后currentAuthority=admin，此时用户的角色已经发生了变化，但是BasicLayout中的菜单却没有根据状态发生变化。强制刷新网页后菜单又能根据预期隐藏了注册和登录入口。

另外BasicLayout中的菜单能否增加一个配置，在layout：topmenu时，有时希望菜单项居中或者居右显示，目前只能居左。

**解决方案**

**其他信息** 

![image](https://user-images.githubusercontent.com/608342/66617337-4ea6ef00-ec07-11e9-9d6c-febbd0079cee.png)

**Comment by z-lionel** [comment]
import { reloadAuthorized } from '@/utils/Authorized';
reloadAuthorized();
切换账号的时候调用这个，会重新渲染

**Comment by chenshuai2144** [comment]
>另外BasicLayout中的菜单能否增加一个配置，在layout：topmenu时，有时希望菜单项居中或者居右显示，目前只能居左。

用 css 来解决问题吧，居中看起来非常习惯，我们不会默认做进去

**Comment by yupeng957** [comment]
> > 另外BasicLayout中的菜单能否增加一个配置，在layout：topmenu时，有时希望菜单项居中或者居右显示，目前只能居左。
> 
> 用 css 来解决问题吧，居中看起来非常奇怪，我们不会默认做进去

居右可以默认支持吗？
