### ISSUE TITLE
Any plans to support English docs?

### ISSUE THREAD

**Issue by AlwaysAwake** [ant-design/ant-design-pro#54]
I really like ant design stacks and I love your work. Previously, I used antd in my production applications and I want to use this again. Are there any plans to support English documentation?

**Comment by nikogu** [comment]
Yes, we had plan. Internationalization is our important goal for Pro 2.0

**Comment by AkdM** [comment]
@nikogu When is the Pro 2.0 planned?

**Comment by afc163** [comment]
http://pro.ant.design/docs/faq#English-Documentation?

**Comment by AkdM** [comment]
Thanks @afc163, I didn't see it.

**Comment by acomito** [comment]
This looks awesome. I'm going to try and do a meteor/apollo version.

**Comment by afc163** [comment]
A simple translation roadmap will be:

- [ ] Home Page / Header / Footer
- [ ] Documentation titles
- [ ] Documentation content
- [ ] Boilerplate i18n solution and translation

It could be a long trip, we can start from the easy one.

@nikogu @ddcat1115

**Comment by Kikobeats** [comment]
This project is totally awesome and I'm sure many of us want to contribute for this to happen, just provide us a guideline like @afc163 for do it 😄

**Comment by acomito** [comment]
@afc163 are there any plans to break out the components into their own packages?

**Comment by khayalan-mathew** [comment]
Yes, hopefully an English documentation is available soon. It's hard to understand Chinese (I hope it's Chinese)

**Comment by afc163** [comment]
@acomito Not yet, separating components here would make us exhausted.

**Comment by tmattio** [comment]
@afc163 I'd love to help on that one. Could start by the components descriptions and demos. Do you plan on replacing the existing Chinese documentation or duplicating the files in English?

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/issues/120
