### ISSUE TITLE
如何实现基于角色控制页面元素的显隐

### ISSUE THREAD

**Issue by 784134748** [ant-design/ant-design-pro#540]
新项目特别想用pro来搭建后台，但之前的项目都是用shiro来进行前后端权限的控制，也许单个页面不同角色进入看到的内容是不同的。希望能像shiro一样通过

> <shiro:hasRole name="administrator">
>     <a href="admin.jsp">Administer the system</a>
> </shiro:hasRole>
的方式来控制页面元素

**Comment by chenshuai2144** [comment]
#508  看一下讨论
