### ISSUE TITLE
[需求]请问有在ant-pro里做过OSS直传的吗

### ISSUE THREAD

**Issue by xiaminxi** [ant-design/ant-design-pro#5400]
**需求描述** [详细地描述需求，让大家都能理解]

**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
这个和前端框架无关的。可能与这个有关
https://ant.design/components/upload-cn/
