### ISSUE TITLE
cnpm安装依赖，启动后报错

### ISSUE THREAD

**Issue by sylyie** [ant-design/ant-design-pro#5404]
TypeError: intl_messageformat__WEBPACK_IMPORTED_MODULE_1__.default.__addLocaleData is not a function

![TIM截图20191011230025](https://user-images.githubusercontent.com/5829395/66662252-0de8bd80-ec7b-11e9-9379-bf113727aefa.png)

**Comment by chenshuai2144** [comment]
你删除了 locale 文件夹？

**Comment by sylyie** [comment]
> 你删除了 locale 文件夹？

我没有删除 locale 文件夹，项目直接从https://github.com/ant-design/ant-design-pro地址下载到本地的，用npm/cnpm/yarn create umi都不成功，就直接download下来的，不知道跟用命令创建有没有区别

**Comment by chenshuai2144** [comment]
无法再现
你有什么办法能百分百再现吗

**Comment by sylyie** [comment]
> 无法再现
> 你有什么办法能百分百再现吗

在我电脑上一直都是这样，已经重复好几次了

**Comment by sylyie** [comment]
cnpm安装依赖会有下面的 问题，是不是这个影响的
![TIM截图20191014005016](https://user-images.githubusercontent.com/5829395/66718997-bd10ca80-ee1c-11e9-9109-5852f835d21f.png)
![TIM截图20191014005443](https://user-images.githubusercontent.com/5829395/66719036-47592e80-ee1d-11e9-9064-1ec8b28b0888.png)
![TIM截图20191014005553](https://user-images.githubusercontent.com/5829395/66719061-8e472400-ee1d-11e9-9255-8b827c428cbc.png)
![TIM截图20191014005650](https://user-images.githubusercontent.com/5829395/66719063-93a46e80-ee1d-11e9-9c3f-8940d1886694.png)

**Comment by chenshuai2144** [comment]
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by seed-fe** [comment]
> cnpm安装依赖会有下面的 问题，是不是这个影响的
> ![TIM截图20191014005016](https://user-images.githubusercontent.com/5829395/66718997-bd10ca80-ee1c-11e9-9109-5852f835d21f.png)
> ![TIM截图20191014005443](https://user-images.githubusercontent.com/5829395/66719036-47592e80-ee1d-11e9-9064-1ec8b28b0888.png)
> ![TIM截图20191014005553](https://user-images.githubusercontent.com/5829395/66719061-8e472400-ee1d-11e9-9255-8b827c428cbc.png)
> ![TIM截图20191014005650](https://user-images.githubusercontent.com/5829395/66719063-93a46e80-ee1d-11e9-9c3f-8940d1886694.png)

请问最后解决了吗？我今天安装依赖启动后也一直报这个错。

**Comment by chenshuai2144** [comment]
cnpm --by=yarn 试试呢？

**Comment by seed-fe** [comment]
> cnpm --by=yarn
请问这个命令是什么意思，执行的时候会报错：
error: unknown option `--by'

**Comment by chenshuai2144** [comment]
这个命令会使用yarn 来安装依赖

**Comment by seed-fe** [comment]
> 这个命令会使用yarn 来安装依赖

也试过用yarn安装依赖，也会报同样的错误

**Comment by seed-fe** [comment]
用npm install就不报错了
