### ISSUE TITLE
Nested router doesn't work

### ISSUE THREAD

**Issue by JoeyKo** [ant-design/ant-design-pro#541]
![b8dbc8df-f4ee-43a9-a1c8-349a4a338d6d](https://user-images.githubusercontent.com/16659637/34477105-02111464-efd2-11e7-8738-aae83e55fa2f.png)
but 
- `/teaching/study`
- `/teaching/:id` 

works

**Comment by wunayou** [comment]
现在的路由无法用 谁弄过三级路由 怎么弄三级路由。。。。

**Comment by ddcat1115** [comment]
[新的路由/菜单 文档](https://github.com/ant-design/ant-design-pro-site/blob/9ee824beab6497e39109eb8dc63bd8584ad41d4c/docs/router-and-nav.md)

**Comment by ddcat1115** [comment]
@JoeyKo 你的问题可以参考 [嵌套路由同级展示](https://github.com/ant-design/ant-design-pro-site/blob/9ee824beab6497e39109eb8dc63bd8584ad41d4c/docs/router-and-nav.md#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA)

**Comment by ddcat1115** [comment]
Feel free to reopen if any other question~
