### ISSUE TITLE
[问题]webpack-theme-color-replacer包是否应该放在dependencies中声明而非devDependencies?

### ISSUE THREAD

**Issue by lyqeyes** [ant-design/ant-design-pro#5410]
**问题描述** [详细地描述问题，让大家都能理解]

观察到目前基于umi初始化的项目(npm create umi 然后选择ant-design-pro), 
webpack-theme-color-replacer包的依赖声明是放在devDependencies中, 
另一方面, 它又是**被生产环境所依赖的**: 
见/config/plugin.config.js文件
`import ThemeColorReplacer from 'webpack-theme-color-replacer';`

这样的话, 如果在生产环境安装依赖包(eg: npm install --production),  然后构建就会失败(webpack-theme-color-replacer模块不会被安装)
<br/>
麻烦解答此困惑. 

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
来个pr?

**Comment by lyqeyes** [comment]
> 来个pr?

已提
