### ISSUE TITLE
如何去掉Umi ui可视化编程辅助工具

### ISSUE THREAD

**Issue by pcxxiaoxiao** [ant-design/ant-design-pro#5411]
在本地启动不会出现辅助工具，但是用docker发上线后页面右下角会出现Umi ui可视化编程辅助工具，现在的启动命令是umi dev，需要换成什么命令才能去掉这个气泡
![image](https://user-images.githubusercontent.com/4568345/66697891-22c16180-ed0c-11e9-9480-99c828e45a3a.png)
我看了下umi 命令只有这些参数
![image](https://user-images.githubusercontent.com/4568345/66697971-beeb6880-ed0c-11e9-85d7-1e1ae3e60be9.png)

**Comment by yutingzhao1991** [comment]
`UMI_UI=none` 可以隐藏。

**Comment by afc163** [comment]
@yutingzhao1991 要排查一下为啥部署后会出现，正常应该只在 dev 模式下出现。

**Comment by yutingzhao1991** [comment]
他这个是在 docker 环境中用 `umi dev` 启动的吧？

@pcxxiaoxiao 确认下你这个是怎么部署的？

**Comment by ycjcl868** [comment]
`umi build` 是不会加上的

**Comment by sorrycc** [comment]
什么情况下会需要用 `umi dev` 部署？

**Comment by james70s** [comment]
本来用的好好的，一升级给你加上个么个按钮，不是找折腾吗！！！

**Comment by yang-chuanjiang** [comment]
> 本来用的好好的，一升级给你加上个么个按钮，不是找折腾吗！！！

请问老哥解决了嘛，我也升级了antd之后出现这个按钮，看着怪别扭的

**Comment by laixstx** [comment]
> 环境变量 `UMI_UI=none` 可以关闭。

umi2 怎么关闭呢？设置了 UMI_UI=none ，还是关闭不了。。。看着挺烦的

**Comment by sxcooler** [comment]
我的项目里用到了mobx，mobx的provider会用React.Children.only，然后就报了Error: React.Children.only expected to receive a single React element child
我百思不得其解（我代码里明明只有一个div），直到我看到那三个children里有两个type=GUmiUIFlag，我真的……
发在这里方便遇到同样问题的同学吧，真心希望国内有些pm不要设计一些破坏性的莫名其妙的东西。
