### ISSUE TITLE
[BUG]默认生成的项目被React报componentWillReceiveProps已经被改名的warning

### ISSUE THREAD

**Issue by jerry-yuan** [ant-design/ant-design-pro#5412]
**bug 描述** [详细地描述 bug，让大家都能理解]
控制台报大量的:
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: some Components
```
**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
生成一个空项目:yarn create umi
选择AntDesignPro
然后yarn install后通过yarn start 启动项目,加载完成后直接打开浏览器控制台,就能看到大量的warning
**期望结果** [描述你原本期望看到的结果]

**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本:2.10.2
- 浏览器环境:Chrome 77.0
- 开发环境:Windows 10 1903

**其他信息** [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/13380647/66703258-2de3b400-ed43-11e9-86c5-848762683307.png)

**Comment by chenshuai2144** [comment]
是我们依赖的社区库，需要等待社区解决。

**Comment by wangyinwei1** [comment]
![image](https://user-images.githubusercontent.com/15857725/68521264-575c1500-02da-11ea-9f17-7985ef3d128c.png)
这个也是依赖的关系吗？还是我写法有问题还是我的依赖版本不够高？

**Comment by wangyinwei1** [comment]
![image](https://user-images.githubusercontent.com/15857725/68521273-82deff80-02da-11ea-8e37-3154ca3a60eb.png)
![image](https://user-images.githubusercontent.com/15857725/68521288-98ecc000-02da-11ea-8faf-ea3c10fb155e.png)
这个也是依赖的关系吗？还是我写法有问题还是我的依赖版本不够高？

**Comment by chenshuai2144** [comment]
新版本的 react 有些生命周期要废弃了，所以 提示这个warning
