### ISSUE TITLE
[需求]能否提供类似 Laravel 框架的 CLI 快速生成 model page service 等文件的功能呢

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design-pro#5413]
**需求描述** [详细地描述需求，让大家都能理解]
通过命令行的方式快速生成 model service page 等文件的基础结构，方便开发，提高开发效率。
之前 ant-design-pro-cli 好像有 generate 这个命令，不知道为啥现在没有了。
**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
试试 umi ui
https://umijs.org/zh/guide/umi-ui.html
