### ISSUE TITLE
[问题] v2版本如何可以结合single-spa使用

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#5418]
**问题描述** [详细地描述问题，让大家都能理解]
想结合single-spa构建前端微服务应用，有小伙伴们尝试过嘛？能否提供相关案例。

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by zhilianbi520** [comment]
或者是结合https://github.com/umijs/qiankun 使用。

**Comment by chenshuai2144** [comment]
你应该去https://github.com/umijs/umi-plugin-qiankun 问，
qiankun 应该支持任何技术栈的

**Comment by chinaxiaoyy** [comment]
@zhilianbi520 同样遇到v2接入single-spa的问题，没有入口文件，不知道去哪初始化single-spa及暴露钩子，你有解决吗？
