### ISSUE TITLE
[BUG] Cannot access https://scaffold.ant.design/#/ after upgrade chrome

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design-pro#5420]
**bug 描述** [详细地描述 bug，让大家都能理解]
其实这个不是ant-design-pro的问题，是脚手架市场的问题。
估计都是antd团队维护的，就反馈到这里了。
Chrome升级最新的v77版本后，不能访问脚手架市场。停留在loading状态。

**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
1. 升级chrome至 Version 77.0.3865.90 (Official Build) (64-bit)
2. 打开 https://scaffold.ant.design/#/
3. 屏幕停留于loading状态。

**期望结果** [描述你原本期望看到的结果]
看见脚手架市场网页

**复现代码** [提供可复现的代码，仓库，或线上示例]
NA

**版本信息:**
NA

- Ant Design Pro 版本: NA
- umi 版本NA
- 浏览器环境 Chrome V77
- 开发环境 Win10

**其他信息** [如截图等其他信息可以贴在这里]
打开chrome的DevTools，打开Network tab
可以看见list.json是红色的，status是（blocked:mixed-context)
出错原因是，chrome 最新版本禁止https网页加载http内容(http://scaffold.ant.design/list.json)

**Comment by chenshuai2144** [comment]
年久失修，现在已无人维护，你要接坑吗？
