### ISSUE TITLE
[问题] 打包部署后，偶尔出现Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#5422]
**问题描述** [详细地描述问题，让大家都能理解]
打包部署后，偶尔出现Cannot read property 'call' of undefined，页面一直转圈，请问这个是哪里的问题？

![TIM图片20191015111241](https://user-images.githubusercontent.com/23411433/66797058-20dde500-ef3c-11e9-8487-37099aea67bc.png)

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
可以打开 sourceMap 看一下是哪里报错了。

**Comment by mstao** [comment]
ant-design-pro 版本是 2.1.1，打包的时候，如何开启sourceMap？

**Comment by mstao** [comment]
开启sourceMap之后，报错如下：

![TIM图片20191018161803](https://user-images.githubusercontent.com/23411433/67078095-33b61b00-f1c3-11e9-8eec-6fa27a231cf2.png)

**Comment by chenshuai2144** [comment]
竟然是 webpack 报错了。
@sorrycc  你来看一下，这个是不是要加什么 插件

**Comment by sorrycc** [comment]
换个 sourcemap 类型呢？比如 eval，inline-source-map 之类的。

**Comment by mstao** [comment]
这两天这个错误又重现不了了，会不会是webpack 打包的时候，某些模块丢失的问题？等再碰到，再把详细的错误信息贴出来。

**Comment by guoguoorange** [comment]
在本地合了别的分支的代码也会有这个问问题
