### ISSUE TITLE
预览的网站好慢啊，能不能优化下啊！！？[BUG]

### ISSUE THREAD

**Issue by Jarvis2018** [ant-design/ant-design-pro#5424]
**bug 描述** 
https://preview.pro.ant.design/ 这个预览的网站打开也太慢了吧，有的时候都开不开

**Comment by chenshuai2144** [comment]
试试各种镜像吧

* React 官网：https://reactjs.org
* Ant Design 官网：https://ant.design
* Ant Design Pro: https://pro.ant.design
* Ant Design 2.x 版本：http://2x.ant.design
* 国内官网镜像：http://ant-design.gitee.io
* Pro 国内官网镜像：http://ant-design-pro.gitee.io
* Ant Design 2.x 版本国内镜像：http://ant-design-2x.gitee.io/index-cn

**Comment by chenshuai2144** [comment]
我这里还好
![image](https://user-images.githubusercontent.com/8186664/66844245-911e5200-efa0-11e9-8a92-a3c9cf1f0238.png)
