### ISSUE TITLE
权限组件有点鸡肋

### ISSUE THREAD

**Issue by chenyu1990** [ant-design/ant-design-pro#5426]
始终都要从后台取权限的，后台直接就控制了菜单的显示和接口的权限访问，前端搞权限组件，毫无意义，我要在我的项目里干掉这个组件，有点碍手碍脚了。
如果是我考虑欠周，还请指教一下。

**Comment by leohxj** [comment]
路由和菜单，可以由服务端控制返回数据，前端直接渲染。

但是页面内元素的权限，你还是需要服务端告知你当前用户的角色之类，用于鉴权。
