### ISSUE TITLE
为什么一直在loading

### ISSUE THREAD

**Issue by Imhemers** [ant-design/ant-design-pro#5427]
这个一直loading，导致页面也不热更新了，有谁遇到了吗
![image](https://user-images.githubusercontent.com/18650947/66817920-16890e80-ef6f-11e9-85e3-b5fb67bb9293.png)

**Comment by chenshuai2144** [comment]
直接来个重现仓库

**Comment by Imhemers** [comment]
![image](https://user-images.githubusercontent.com/18650947/66887584-fd836a80-f00d-11e9-9c17-8cf2919c24bc.png)




是不是这个导致的?

**Comment by chenshuai2144** [comment]
这个看起来是 umi ui 报错了。
https://umijs.org/zh/guide/umi-ui.html
