### ISSUE TITLE
请问excel导出也就是文件下载有处理办法吗

### ISSUE THREAD

**Issue by phper-chen** [ant-design/ant-design-pro#543]
这种前后端分离的方式来做下载一般是返回个url然后trigger事件自动触发点击下载，但是react这样的方式有点搞不懂了，我是后端的，请指教

**Comment by chenshuai2144** [comment]
你需要的是个[ a标签](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a).
你可以用ref触发dom事件.

**Comment by phper-chen** [comment]
ok 谢谢 我找找方法
