### ISSUE TITLE
接口返回的数据 这种情况怎么做国际化

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design-pro#5430]
接口返回的数据 这种情况怎么做国际化

**Comment by chenshuai2144** [comment]
你把 当前语言 给后端通过cookie 传回去就好了。

**Comment by liangchaofei** [comment]
> 你把 当前语言 给后端通过cookie 传回去 然后后端去做国际化，前端只能对框架做国际化的

不需要前端调接口吧？ 需要前端多少吗？

**Comment by liangchaofei** [comment]
前端怎么把英文渲染到页面上？
