### ISSUE TITLE
接口返回的数据 这种情况怎么做国际化

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design-pro#5431]
接口返回的数据 这种情况怎么做国际化? 翻译的内容是后端返回，前端需要做什么吗？ 怎么把翻译渲染到页面上？

**Comment by mathcw** [comment]
我是这样做的，请求这个需要国际化的后台数据时 请求中会带上前台的locale值 后台会根据locale直接返回对应语种的数据 前端直接使用翻译结果 （因为国际化已经完成）

**Comment by liangchaofei** [comment]
> 我是这样做的，请求这个需要国际化的后台数据时 请求中会带上前台的locale值 后台会根据locale直接返回对应语种的数据 前端直接使用翻译结果 （因为国际化已经完成）

前端直接使用翻译结果？ 这个是怎么弄的？ 是在切换语言的时候 ，在点击事件里调接口？

**Comment by mathcw** [comment]
切换语言时 会使用umi的setlocale 这个动作会引起页面的刷新
然后我有个统一的初始化请求 类似下面的
export async function init(){
  const url = `${AppCore.HOST}/PublicApi/init`;;
  const option = {lang:getLocale()};
  return post(url,option);
}
这会作为后台翻译的依据 前端每次直接使用结果即可

**Comment by liangchaofei** [comment]
> 切换语言时 会使用umi的setlocale 这个动作会引起页面的刷新
> 然后我有个统一的初始化请求 类似下面的
> export async function init(){
> const url = `${AppCore.HOST}/PublicApi/init`;;
> const option = {lang:getLocale()};
> return post(url,option);
> }
> 这会作为后台翻译的依据 前端每次直接使用结果即可

方便加个qq或微信吗？想详细了解下。谢谢了 我的微信是cf825605688

**Comment by taomengyue** [comment]
你好，我也有相同的问题，后端返回的语言包，怎么做国际化
