### ISSUE TITLE
在一级父菜单下，点击三级子菜单，再点击另一个二级子菜单，一级菜单会折叠

### ISSUE THREAD

**Issue by lihongdegithub** [ant-design/ant-design-pro#5433]
**bug 描述** 在一级父菜单下，点击三级子菜单，再点击另一个二级子菜单，一级菜单会折叠

**期望结果**  在一级父菜单下，点击三级子菜单，点击另一个二级菜单的时候当前一级菜单不折叠

- Ant Design Pro 版本: [e.g. 4.0.0]
- 开发环境 [win 10]

**Comment by lihongdegithub** [comment]
![1](https://user-images.githubusercontent.com/20473426/66883932-30bffc80-f002-11e9-9db7-c2f67e57834a.jpg)

**Comment by chenshuai2144** [comment]
在 4.5.13 以后一可以自定义当前选中的菜单想了，参数和antd的menu 相同

**Comment by linfengluo** [comment]
求教
这个问题你解决了吗？ @lihongdegithub

**Comment by gaozhidf** [comment]
遇到了同样折叠的问题找了几天，果然还是配置文件中`/`没处理好的问题，可以参考下，[#4760](https://github.com/ant-design/ant-design-pro/issues/4760#issuecomment-517334019)
