### ISSUE TITLE
约定式路由引发的问题

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#5434]
各位好！
我这边将路由设置为约定式路由
![image](https://user-images.githubusercontent.com/44084004/66886025-aa5ae900-f008-11e9-96dd-1315649e7769.png)
但页面加载后却没有了左侧菜单与顶部内容。
![image](https://user-images.githubusercontent.com/44084004/66886069-c9597b00-f008-11e9-9726-87ff7df295bc.png)
这个是BasicLayout.jsx 我目前也没有改动这边代码。
![image](https://user-images.githubusercontent.com/44084004/66886122-eaba6700-f008-11e9-9c4f-cb31e69a2169.png)
是不是因为我约定式路由哪边缺少了配置引起的问题。因为我改成配置式却没有这样的问题。
各位有没有遇到过这样类似的事情呢？

**Comment by zhangWeiZhuang** [comment]
![image](https://user-images.githubusercontent.com/44084004/66886322-8a77f500-f009-11e9-877c-e4f9755d206f.png)
这个是 umi build出来的路由

**Comment by chenshuai2144** [comment]
看起来是 layout 没有加载到，我没有尝试过 约定式路由，需要社区的同学来排查一下了

**Comment by xiaohuoni** [comment]
少了一个文件吧，你标记红色框框的那个文件。

**Comment by xiaohuoni** [comment]
约定式路由，默认使用 layout/index 或者目录中的 _layout 文件作为导航，如果你需要修改或者自定义，可以通过 routes 的 update 来手动指定

**Comment by zhangWeiZhuang** [comment]
@xiaohuoni 感谢解答。但我这边使用的是最新版本v4.0好像并没有layouts/index.js 这个文件哦。而且_routes.json我也是加上去的

**Comment by xiaohuoni** [comment]
没有layouts/index.js 新建一个咯
