### ISSUE TITLE
页面中使用iframe嵌套网页总是跳转到登录页

### ISSUE THREAD

**Issue by mushroomlb** [ant-design/ant-design-pro#5436]
在前端页面中嵌入iframe，里面引入其他网站的页面，在本地测试没有问题，在服务端用nginx代理后访问该页面就会跳转到登录页面

<iframe style={{border:0,width:"100%",height:630,}} src="http://同nginx下的/bb"/> 
          
nginx配置：
react 前端
 location / {
      root /usr/local/aa;
      index index.html;
      try_files $uri $uri/ /index.html;
  }

iframe嵌套的url：
 location /bb {
      proxy_pass http://127.0.0.1:3000/;
      proxy_set_header Host $Host:80;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

**Comment by chenshuai2144** [comment]
iframe 有安全性限制的，cookie 并不共享， 你可以能需要每次登陆。
