### ISSUE TITLE
脚手架项目启动后在IE11显示空白

### ISSUE THREAD

**Issue by yyzlong** [ant-design/ant-design-pro#5437]
**bug 描述** [详细地描述 bug，让大家都能理解]
脚手架项目启动后在IE11显示空白（中间显示蓝色进行中图标），而同样代码在同一台电脑的chrome下正常显示

**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
npm create umi 生成初始脚手架代码
npm install
npm start
**期望结果** [描述你原本期望看到的结果]
在IE11正常显示
**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: 最新版 4.0
- umi 版本
- 浏览器环境 IE 11
- 开发环境 [e.g. mac OS]
Win 7
**其他信息** [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/985068/66913357-0e040700-f047-11e9-83ad-593bced61c4f.png)

![image](https://user-images.githubusercontent.com/985068/66913417-283de500-f047-11e9-9bab-37027dbfaa18.png)

![image](https://user-images.githubusercontent.com/985068/66913437-37bd2e00-f047-11e9-9013-0c24ddc21289.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#targets
https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport
尝试配置一下个 targets，并且关闭 按需加载。
