### ISSUE TITLE
初次安装获取全部区块时报错

### ISSUE THREAD

**Issue by Mrzzhi** [ant-design/ant-design-pro#5439]
如图，在安装好脚手架能正常运行后，获取全部区块的时候报错！

![卡死](https://user-images.githubusercontent.com/52029992/66976218-b8297080-f0d3-11e9-8926-22a231d7ad64.png)
![错误提示](https://user-images.githubusercontent.com/52029992/66976220-b8297080-f0d3-11e9-9d75-c4b9b94d6ffc.png)

**Comment by chenshuai2144** [comment]
上面已经报错了，你的权限有问题。
