### ISSUE TITLE
eslint 大家有什么共享的吗？

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#544]
因为ant pro 这一套 我都 注释了 太多规则了

**Comment by afc163** [comment]
尽量不要注释，学习和应用规则，受益无穷。

有你认为不合理的规则，可以拿出来讨论。

**Comment by chenshuai2144** [comment]
prettier大法好!退eslint保平安

**Comment by zhangguanpeng** [comment]
我想将代码缩进距离2改为4，有知道怎么改的大神吗？
我在.editorconfig文件里面修改了indent_size = 4，并没有起作用（用的是vscode）

**Comment by chenshuai2144** [comment]
额  装个 eslint 插件  然后设置
https://eslint.org/docs/rules/indent
最后eslint fix一下就好了
