### ISSUE TITLE
[BUG] typescript error about pro-layout

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design-pro#5441]
**bug 描述** [详细地描述 bug，让大家都能理解]
When run `tsc`, there is a ts error about pro-layout.
And I also don't know why ts checking node_modules, I have set `node_modules` in exclude,
![QQ截图20191017154359](https://user-images.githubusercontent.com/16114101/66988711-9214c800-f0f5-11e9-8403-2cffac8fed4d.png)
![QQ截图20191017154413](https://user-images.githubusercontent.com/16114101/66988713-9214c800-f0f5-11e9-9c6a-cd9736569bb3.png)

**复现步骤** [清晰描述复现步骤，让别人也能看到问题]

**期望结果** [描述你原本期望看到的结果]

**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by kwzm** [comment]
OK

**Comment by kwzm** [comment]
Oh, It's my fault, my @ant-design/pro-layout is 4.5.11, the bug was fixed in 4.5.12.
