### ISSUE TITLE
请问 pro 可以做服务端渲染吗  类似于 nextjs  如果可以的话用什么框架 如何可插拔的添加到先用的 pro项目中[问题]

### ISSUE THREAD

**Issue by tongxurt** [ant-design/ant-design-pro#5442]
**问题描述** [详细地描述问题，让大家都能理解]

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by tongxurt** [comment]
或者后续如果考虑服务端渲染的话  会出现全部推翻重写的情况吗  还是直接在现有pro项目的基础是加代码就可以实现了？

**Comment by chenshuai2144** [comment]
https://cnpmjs.org/package/umi-plugin-ssr/v/0.1.4

试试这个，但是比较初级只有在我们自己的项目中使用过。
