### ISSUE TITLE
[问题]一级二级菜单同名，点击其他菜单，怎样不高亮首个菜单

### ISSUE THREAD

**Issue by EEETA** [ant-design/ant-design-pro#5444]
**问题描述** [详细地描述问题，让大家都能理解]
实现一个二级菜单。二级菜单中首选项与一级菜单名相同。点击二级菜单其他选项，首个选项依旧高亮。有没有什么办法让我点击“详情查看”，只显示该选项高亮

**其他信息** [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/24688270/67064133-e96d7380-f19b-11e9-8bde-4c7d3c39bd84.png)

代码如下：
![image](https://user-images.githubusercontent.com/24688270/67064157-0609ab80-f19c-11e9-8a00-06b9191ffcb1.png)

**Comment by huntdream** [comment]
把二级菜单中 全部测试 的路由改一下，跟一级菜单的区分开来。菜单高亮是根据路由来匹配的，你两个都是`/car/all`，都会被匹配到

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5433

**Comment by EEETA** [comment]
> 把二级菜单中 全部测试 的路由改一下，跟一级菜单的区分开来。菜单高亮是根据路由来匹配的，你两个都是`/car/all`，都会被匹配到

试过修改路由，高亮没有问题，但是浏览器报key重复错误。这个key仿佛是根据name值来的，如果不同级菜单显示的字要一样，path也得一样
![code.jpeg](https://i.loli.net/2019/10/22/FBG34WLbTcmY5rM.png)
![view.jpeg](https://i.loli.net/2019/10/22/sxkZMgJLwlfUTDF.png)
![error.jpeg](https://i.loli.net/2019/10/22/WtrKYIGad3spENL.png)

**Comment by EEETA** [comment]
> 看这个 #5433
> layout 支持自定义openKey 和 selectkey了

不同级的菜单要显示的字一样的话，key是根据name值来的吗，能否自定义key值
![微信图片_20191022110256.png](https://i.loli.net/2019/10/22/4OPBsjTtdp2grxZ.png)

**Comment by huntdream** [comment]
> > 把二级菜单中 全部测试 的路由改一下，跟一级菜单的区分开来。菜单高亮是根据路由来匹配的，你两个都是`/car/all`，都会被匹配到
> 
> 试过修改路由，高亮没有问题，但是浏览器报key重复错误。这个key仿佛是根据name值来的，如果不同级菜单显示的字要一样，path也得一样
> ![code.jpeg](https://camo.githubusercontent.com/2d8061134c5be913023d5c8488453a492c37f6a6/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f32322f4642473334574c6254636d5935724d2e706e67)
> ![view.jpeg](https://camo.githubusercontent.com/9a2a3965e560ee391a0f358bd525b7ed8272763f/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f32322f73786b5a4d674a4c776c66555444462e706e67)
> ![error.jpeg](https://camo.githubusercontent.com/024ac0c09a11ed10734a32b1668b0573790eb887/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31302f32322f5774724b5949476164337370454e4c2e706e67)

仔细看你的报错信息，是BreadCrumb这个组件报的key重复

**Comment by chenshuai2144** [comment]
key 是 id，如果不唯一会引发很多问题
