### ISSUE TITLE
如何彻底清除缓存？

### ISSUE THREAD

**Issue by yinbanghui** [ant-design/ant-design-pro#5445]
项目上线后遇到缓存问题，查询文档之后增加了hash:true后，依然存在缓存问题，即重新发布新版之后，在未手动清除缓存的情况下，依然访问上一个版本的带hash的js、css，请问有好的解决办法么？比如请求地址 + ？v=' + Math.random()这种方法

**Comment by dazhi007** [comment]
这直接关闭了， 解决方法在哪里呢

**Comment by yinbanghui** [comment]
@dazhi007 遇到同一个问题了？

**Comment by 1994ZXL** [comment]
我也遇到了同样的问题，请问你是在哪里设置的hash:true，哪里文档有些，谢谢了

**Comment by abcfly** [comment]
> 我也遇到了同样的问题，请问你是在哪里设置的hash:true，哪里文档有些，谢谢了

config.js下面,参考第一行提供的api地址;https://umijs.org/config/

**Comment by tianpanpan66** [comment]
遇到了同样的的问题，hash为true已经设置，但是仍旧有缓存
