### ISSUE TITLE
关于antd pro 上传至阿里云OSS的配置方案

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5450]
想把antd pro部署到阿里oss上，如何设置才能代理到后端服务器呢？

**Comment by chenshuai2144** [comment]
据我所知 阿里oss  是支持代理的，可以考虑一下跨域的模式

**Comment by leshalv** [comment]
嗯，我看看，这块官方能不能给一个方案出来，现在前端部署到阿里云oss作为静态服务的挺多的。

**Comment by imhele** [comment]
试试 https://github.com/imhele/umi-plugin-oss ？或者根据自己的需求简单写一个 umi 插件

**Comment by leshalv** [comment]
> 请尝试https://github.com/imhele/umi-plugin-oss？或者根据自己的需求简单写一个umi插件

嗯，你这个只是上传吗？我文件上传上去了，我就是不知道如何配置，来使页面正常工作，比如代理到后端服务器

**Comment by imhele** [comment]
get，建议：
1. 将 [publicPath 配置](https://umijs.org/zh/config/#publicpath)填上你的 OSS （或 CDN） 地址；
2. 开启 [hash 配置](https://umijs.org/zh/config/#hash)；
3. index.html 上传到后端服务器；
4. 将 js css 及图片等其他文件上传到 OSS ；
5. 按[部署文档](https://pro.ant.design/docs/deploy-cn#%E9%83%A8%E7%BD%B2%E5%88%B0%E4%B8%8D%E5%90%8C%E7%9A%84%E5%B9%B3%E5%8F%B0)配置 nginx （推荐） 或 spring boot 即可访问~

Tips：
- 将 index.html 上传到服务器并开启 umi 的 hash 配置以在重新构建产物后避免浏览器载入旧产物的缓存。
- 如果服务器的域名与 OSS 的访问地址（你的 publicPath 配置）域名不同，请在 OSS 的配置页开启[“跨域访问规则”](https://help.aliyun.com/document_detail/31903.html)。

**Comment by leshalv** [comment]
嗯，使用你的方式成功了

**Comment by leshalv** [comment]
非常感谢！

**Comment by leshalv** [comment]
对了大佬，index.html umi可以压缩一下吗

**Comment by imhele** [comment]
> 对了大佬，index.html umi可以压缩一下吗

这个文件一般不会很大，你生成的 index.html 有多大？如果产物很大，大致贴一下 index.html 的结构？

**Comment by leshalv** [comment]
> > 对了大佬，index.html umi可以压缩一下吗
> 
> 这个文件一般不会很大，你生成的 index.html 有多大？如果产物很大，大致贴一下 index.html 的结构？

我把document.ejs 文件压缩了一下，然后在build，产生的文件就是压缩过后的了

**Comment by lossend** [comment]
1
