### ISSUE TITLE
[问题]V4无法正确设置权限，可以绕过登录直接访问业务页面

### ISSUE THREAD

**Issue by DusuWen** [ant-design/ant-design-pro#5451]
**问题描述** [详细地描述问题，让大家都能理解]
地址栏输入http://localhost:8000 会绕过登录，直接进入业务页面

**示例代码** [如果有必要，展示代码，线上示例，或仓库]
```
  routes: [
    {
      path: '/user',
      component: '../layouts/UserLayout',
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: './user/login',
        },
      ],
    },
    {
      path: '/',
      component: '../layouts/SecurityLayout',
      routes: [
        {
          path: '/',
          component: '../layouts/BasicLayout',
          routes: [
            {
              path: '/',
              redirect: '/order/orders',
              authority: ['admin', 'user'],
            },
            {
              name: 'order',
              icon: 'shopping-cart',
              path: '/order',
              routes: [
                {
                  name: 'orders',
                  path: '/order/orders',
                  component: './ListTableList',
                  authority: ['admin', 'user'],
                },
                {
                  name: 'edit-orders',
                  path: '/order/formbasicform',
                  component: './FormBasicForm',
                  authority: ['admin'],
                },
              ],
            },
            {
              component: './404',
            },
          ],
        },
        {
          component: './404',
        },
      ],
    },
    {
      component: './404',
    },
  ],

```
**其他信息** [如截图等其他信息可以贴在这里]

**Comment by liganghui** [comment]
光发个路由有啥子用  , 你修改默认的登录逻辑了 , 用的真实数据 ?  默认的mock数据自带权限信息  , 所以会自动跳转到首页 .

**Comment by DusuWen** [comment]
@liganghui 有真实接口

**Comment by afc163** [comment]
按这里的逻辑 https://github.com/ant-design/ant-design-pro/blob/1e8238cdb9b39cd2b6d6a51df87aec0d81ed0864/src/utils/authority.ts#L21

如果开启了 `ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION`，那么所有用户都将是 admin 权限（可以访问所有页面），这是用于 preview.pro.ant.design 上做演示页面方便大家看各个页面。如果在真实项目中部署使用，请`不要开启/去掉`这个环境变量。

（官网部署是[在这里](https://github.com/ant-design/ant-design-pro/blob/1e8238cdb9b39cd2b6d6a51df87aec0d81ed0864/package.json#L10)开启的，请确保不要在你的项目中开启，除非你也是要做演示）

**Comment by DusuWen** [comment]
@afc163 我把这里直接注释掉了，然后在SecurityLayout里加了判断localStorage是否已经有权限的逻辑
```
  componentDidMount() {
    this.setState({
      isReady: true,
    });
    const { dispatch } = this.props;
    if (localStorage.getItem('antd-pro-authority') !== null) {
      if (dispatch) {
        dispatch({
          type: 'user/fetchCurrent',
        });
      }
    }
  }
```
但是新问题又出现了，别的issue里也提到了，需要登录两次才能跳转到业务页面

**Comment by afc163** [comment]
因为代码已经在你手中了，而且已经修改过了，具体是什么问题需要你帮忙排查一下。如果是 pro 源码的问题，欢迎解决之后给我们发个 PR。

**Comment by DusuWen** [comment]
我真的没招了，建议大家试试把演示模式关掉，还能不能不经过登录直接进入业务页面

**Comment by DusuWen** [comment]
> @afc163 我把这里直接注释掉了，然后在SecurityLayout里加了判断localStorage是否已经有权限的逻辑
> 
> ```
>   componentDidMount() {
>     this.setState({
>       isReady: true,
>     });
>     const { dispatch } = this.props;
>     if (localStorage.getItem('antd-pro-authority') !== null) {
>       if (dispatch) {
>         dispatch({
>           type: 'user/fetchCurrent',
>         });
>       }
>     }
>   }
> ```
> 
> 但是新问题又出现了，别的issue里也提到了，需要登录两次才能跳转到业务页面

参考这个问题 #5348 
我在SecurityLayout中改了isLogin的判断逻辑
```
    // const isLogin = currentUser && currentUser.userid;
    const isLogin = localStorage.getItem('antd-pro-authority') !== null;
```
登录两次的问题得以解决

**Comment by feifanlee** [comment]
> 
> 
> > @afc163 我把这里直接注释掉了，然后在SecurityLayout里加了判断localStorage是否已经有权限的逻辑
> > ```
> >   componentDidMount() {
> >     this.setState({
> >       isReady: true,
> >     });
> >     const { dispatch } = this.props;
> >     if (localStorage.getItem('antd-pro-authority') !== null) {
> >       if (dispatch) {
> >         dispatch({
> >           type: 'user/fetchCurrent',
> >         });
> >       }
> >     }
> >   }
> > ```
> > 
> > 
> > 但是新问题又出现了，别的issue里也提到了，需要登录两次才能跳转到业务页面
> 
> 参考这个问题 #5348
> 我在SecurityLayout中改了isLogin的判断逻辑
> 
> ```
>     // const isLogin = currentUser && currentUser.userid;
>     const isLogin = localStorage.getItem('antd-pro-authority') !== null;
> ```
> 
> 登录两次的问题得以解决

localsotrage是永久存储，这样登录了就永远登录着，后台就不能用session存登录信息了。

**Comment by DusuWen** [comment]
@liganghui 登出的时候清空了localstorage,这次只是简单的跑个业务demo，后台同学没有提供完整接口支持。
