### ISSUE TITLE
[BUG] 使用IE浏览器打开时,控制台报了这个错误，我并没有找到main在哪里

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5453]
![image](https://user-images.githubusercontent.com/30397655/67179397-c3004000-f408-11e9-94dc-d2e5781fed55.png)
Warning: The tag <main> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Adapter (created by ContainerQuery)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by ContainerQuery)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by ContainerQuery)
    in div (created by ContainerQuery)
    in ContainerQuery (created by BasicLayout)
    in DocumentTitle (created by SideEffect(DocumentTitle))
    in SideEffect(DocumentTitle) (created by BasicLayout)
    in BasicLayout (created by BasicLayout)
    in BasicLayout (created by Connect(BasicLayout))
    in Connect(BasicLayout) (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Route)
    in Switch (created by Route)
    in Route (created by RouteWithProps)

**Comment by chenshuai2144** [comment]
这个是 antd 的 layout 中使用的。

https://github.com/ant-design/ant-design/blob/6b74a1e9448afecd1424a0031b6f45568dad40f4/components/layout/layout.tsx#L125

html 会降级成 div 的。

**Comment by zllisa** [comment]
您好，该问题的主要问题应该是小写的组件导致IE浏览器渲染页面时间过长，浏览器长时间无法响应，等页面加载之后会打印该错误。我目前使用antd   v4.16.10 很新的版本，该问题并未被解决。
已提出新问题https://github.com/ant-design/ant-design-pro/issues/9020
