### ISSUE TITLE
config文件中如何使用formatMessage？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#5454]
![image](https://user-images.githubusercontent.com/50793943/67180068-fa6fec00-f40a-11e9-8e55-7edef223ea29.png)

![image](https://user-images.githubusercontent.com/50793943/67180096-16738d80-f40b-11e9-89d1-d3e04056a739.png)

**Comment by chenshuai2144** [comment]
config 是 node 环境的，无法使用任何 dom。他只是个配置文件
