### ISSUE TITLE
umi-request 请求,服务器返回500,  effect 里面的请求就报错,代码无法往下运行

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5456]
请求返回:
{body: (...)
bodyUsed: true
headers: Headers {}
ok: false
redirected: false
status: 500
statusText: "Internal Server Error"
type: "basic"
url: "http://url"}

在modal里面的effect的请求
 const response = yield call(listData, payload);
就会报错,抛出异常,代码无法运行
index.js:1 uncaught at _callee3 at _callee3 
 at _callee6 
 at takeEvery(listData/fetch, _callee) 
 at _callee 
 at _callee 
 Error: ResponseError: http error

请问这个是为什么?
错误不是errorHandler里面处理吗?
在response拦截器里面可以拦截到上面请求返回的

**Comment by chenshuai2144** [comment]
建议你处理一下 500 的错误。try catch 包裹即可。

如果想一劳永逸，可以用这个方法，但是可能造成别的问题
https://dvajs.com/guide/source-code-explore.html#start-%E6%96%B9%E6%B3%95
你需要这个方法。

**Comment by z-lionel** [comment]
> 建议你处理一下 500 的错误。try catch 包裹即可。
> 
> 如果想一劳永逸，可以用这个方法，但是可能造成别的问题
> https://dvajs.com/guide/source-code-explore.html#start-%E6%96%B9%E6%B3%95
> 你需要这个方法。

有个问题很奇怪，在modal里面的请求如果是来自
import { queryServices} from '@/services/user';
这样就不会有上面的报错，errorHandler里面的方法能运行，能显示500的错误提示框
pages里面的文件夹里的modal引用请求是来同个目录里面service也不会报错

而来自其他的
 '@/services/login'; '@/services/global'; 或者自定义的@/services/abc'; 全都会上面的报错

**Comment by owen0946** [comment]
> > 建议你处理一下 500 的错误。try catch 包裹即可。
> > 如果想一劳永逸，可以用这个方法，但是可能造成别的问题
> > https://dvajs.com/guide/source-code-explore.html#start-%E6%96%B9%E6%B3%95
> > 你需要这个方法。
> 
> 有个问题很奇怪，在modal里面的请求如果是来自
> import { queryServices} from '@/services/user';
> 这样就不会有上面的报错，errorHandler里面的方法能运行，能显示500的错误提示框
> pages里面的文件夹里的modal引用请求是来同个目录里面service也不会报错
> 
> 而来自其他的
> '@/services/login'; '@/services/global'; 或者自定义的@/services/abc'; 全都会上面的报错

看下你那个service里request的引用是import request from 'umi-request';
还是import request from '@/utils/request'; ,我是改成@/utils/request解决的.
我之前是复制的table-list那个样例中的service,那里面是from 'umi-request'.
