### ISSUE TITLE
[BUG]编译后文件解析地址不对

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design-pro#5460]
**bug 描述** [详细地描述 bug，让大家都能理解]
build之后在服务器配置后，打开提示文件路径不正确，请求地址也是错的
**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
npm run build
**期望结果** [描述你原本期望看到的结果]

**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
chrome
- 开发环境 [e.g. mac OS]
windows
**其他信息** [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/3411959/67201443-e8a53d80-f438-11e9-9357-53e53618a173.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn
看一下这里，mock 数据再编译后是不存在的

**Comment by junhui75165** [comment]
@chenshuai2144 如果要使mock作为测试数据生效的话，请求的地址应该怎么配置，启动服务的话mock的入口用哪个

**Comment by chenshuai2144** [comment]
可以使用 umi serve 来启动项目，会自动在加载 mock。

如果要是用 Nginx 的话。
https://ant-design-pro.netlify.com/api/
https://us-central1-antd-pro.cloudfunctions.net/api

**Comment by JzwOnly** [comment]
@chenshuai2144 请问 要如何用umi server 来启动 项目呢
