### ISSUE TITLE
v2版本开发好的页面在360浏览器兼容模式下一直转圈加载中，Loading chunk vendors failed.

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design-pro#5462]
**bug 描述** [详细地描述 bug，让大家都能理解]
这是360浏览器控制台报的问题，谷歌浏览器是正常的
![kk_image](https://user-images.githubusercontent.com/20589684/67254770-76247400-f4b1-11e9-8727-8f2de658e480.png)

SCRIPT1014: 无效字符 
vendors.async.js, 行25 字符25
Unhandled promise rejection ChunkLoadError: Loading chunk vendors failed.
(missing: http://xxx.xx.xxx.xx:8000/vendors.async.js) 

**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
360浏览器加载页面一直加载中
**期望结果** [描述你原本期望看到的结果]
正常显示页面
**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**
v2版本

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 
- 开发环境 [e.g. mac OS]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenshuai2144** [comment]
这是ie吧？ 
关闭动态加载。
https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

**Comment by dongkeng001** [comment]
> 这是ie吧？
> 关闭动态加载。
> https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

我直接把动态加载配置全注释了，还是一直在加载中，只是控制台报了这个错
SCRIPT1014: 无效字符 
umi.js, 行5012 字符25

/*dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      },*/

![fc](https://user-images.githubusercontent.com/20589684/67255486-e2ed3d80-f4b4-11e9-8201-a5069a99ce86.png)

**Comment by chenshuai2144** [comment]
target 设置一下，ie 要兼容需要一系列配置，并且确认你的包没有任何使用了新语法的东西

**Comment by xiaohuoni** [comment]
定位方法 https://github.com/umijs/umi/issues/1421#issuecomment-516762499
