### ISSUE TITLE
【问题】启动本地项目模板预览在chrome浏览器中始终是移动端排版

### ISSUE THREAD

**Issue by Albuseven** [ant-design/ant-design-pro#5465]
启动本地项目模板预览在chrome浏览器中始终是移动端排版，在Edge里显示正常。
![微信图片_20191022170928](https://user-images.githubusercontent.com/6004615/67272726-a7bc3000-f4ef-11e9-91c8-6cee31aff4cd.png)

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/ 
预览环境呢，也是这样吗？

**Comment by Albuseven** [comment]
> https://preview.pro.ant.design/
> 预览环境呢，也是这样吗？

预览环境没问题，正常的

**Comment by Albuseven** [comment]
> 无法再现，你在 chrome 中做了什么？

就只是yarn安装了ant-design-pro脚手架，start
清缓存、重新装也没用，一脸懵

**Comment by liujiayii** [comment]
地址栏最右边那个放大镜重置一下

**Comment by chenshuai2144** [comment]
楼上正解了
