### ISSUE TITLE
[BUG]node_modules\@types\react-redux\index.d.ts中引入报错

### ISSUE THREAD

**Issue by bwlloveistrue** [ant-design/ant-design-pro#5468]
**bug 描述**node_modules\@types\react-redux\index.d.ts中引入hoistNonReactStatics.NonReactStatics报错,没有NonReactStatics
并且hoistNonReactStatics中是真没有这个属性
declare function hoistNonReactStatics<Own, Custom>(
  TargetComponent: React.ComponentType<Own>,
  SourceComponent: React.ComponentType<Own & Custom>,
  customStatic?: any): React.ComponentType<Own>;

**复现步骤** 在vsscode中执行tsconfig.json时候报这个错

**期望结果** 希望可以正常安装

**版本信息:**

- Ant Design Pro 版本: 最新4版本
- umi 版本2.10.7
- 浏览器环境 谷歌:73.0.3683.103 (正式版本) （64 位）
- 开发环境 win7

**其他信息** [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/35321214/67308765-4450f300-f52d-11e9-9ce5-7dbc6ff50c77.png)

**Comment by chenshuai2144** [comment]
更新一下你的依赖，这个是第三方库的代码，与 pro 无关。
