### ISSUE TITLE
[问题]使用html2canvas进行页面截图时，无法获取页面内容

### ISSUE THREAD

**Issue by b9AobJ** [ant-design/ant-design-pro#5469]
**问题描述** [详细地描述问题，让大家都能理解]
项目有个需求，需要截图当前页面数据分享，然而使用html2canvas截图却不行，得到的是一个白屏图片。
**示例代码** [如果有必要，展示代码，线上示例，或仓库]
`

      const root = document.getElementById('root');
      html2canvas(root).then(canvas => {
        const imgUrl = canvas.toDataURL();
        // 获取截图base64 
        console.log(imgUrl);

        // canvas宽度
        var canvasWidth = canvas.width;
        // canvas高度
        var canvasHeight = canvas.height;
          // 调用Canvas2Image插件
        // var img = Canvas2Image.convertToImage(canvas, canvasWidth, canvasHeight);
        const w = canvasWidth; //判断输入宽高是否为空，为空时保持原来的值
        const h = canvasHeight;
        // 调用Canvas2Image插件
        // canvas2image.saveAsPNG(canvas, w, h);
        canvas2image.saveAsPNG(canvas,true);
      });
`

**Comment by chenshuai2144** [comment]
这个与 pro 无关的。Canvas2Image 这个包可能有什么特殊限制
