### ISSUE TITLE
[需求]我想问一下ant design pro 如何从V2.2.1升级到V4.0.0

### ISSUE THREAD

**Issue by ZuccRoger** [ant-design/ant-design-pro#5470]
**需求描述** [详细地描述需求，让大家都能理解]

**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by afc163** [comment]
https://pro.ant.design/docs/upgrade-v4-cn

**Comment by luohaisi** [comment]
同问，文档说不需要做任何改动，难道ta自己会升级？
npm i 应该也不对吧，
升级的话，只升级umi会报错，
救救小白吧，对我们友好一点...

**Comment by afc163** [comment]
技术上来说，v2 和 v4 的区别其实只有把布局相关的代码抽离到了 `@ant-design/pro-layout` 这一个。
