### ISSUE TITLE
componentDidMount中 执行两个dispatch 本地好像没事 部署后nginx 和生产环境 有时候有一个不会去请求是怎么回事

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5472]
![image](https://user-images.githubusercontent.com/47104575/67370674-a94c2d80-f5ad-11e9-94e2-b475a2850902.png)

**Comment by 904492381** [comment]
有一个不会请求 按 F5页面刷新后才行

**Comment by chenshuai2144** [comment]
报错了吧？

**Comment by 904492381** [comment]
> 报错了吧？
> 报错如果不处理，会堵塞下一步的

这两个请求并没有报错

**Comment by chenshuai2144** [comment]
source map  开一下, 打个断点试试好了。这个需要自己排查了 preview 并没有这个问题。

**Comment by 904492381** [comment]
> source map 开一下, 打个断点试试好了。这个需要自己排查了 preview 并没有这个问题。

就部署后 生产模式会这样   断点不是开发模式吗 开发模式没这问题

**Comment by xiaohuoni** [comment]
dva@2.4.1 试试

**Comment by 904492381** [comment]
> dva@2.4.1 试试

我就是这个版本

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#devtool
打开一下这个

**Comment by 904492381** [comment]
> https://umijs.org/zh/config/#devtool
> 打开一下这个

谢谢了 没用过 我研究一下
