### ISSUE TITLE
使用ant-design-pro 实现后端代理。无效果。

### ISSUE THREAD

**Issue by Shhuy** [ant-design/ant-design-pro#5473]
在使用本地mock数据可以使用，但是想要代理到自己的后端服务器，设置后没有作用，求解？
config.js中设置如下，
![TIM截图20191023160444](https://user-images.githubusercontent.com/42715523/67372488-9129dd80-f5b0-11e9-812b-dc75d6df496f.png)

发送的请求路径：
![server](https://user-images.githubusercontent.com/42715523/67372546-a56dda80-f5b0-11e9-907d-aeb4412bdc65.png)
设置完以后依然使用的是本地mock数据，没有请求到自己的后端服务。

**Comment by xiaohuoni** [comment]
你的服务端请求地址是 `http://localhost:7001/login/account` 嘛？

**Comment by Shhuy** [comment]
是的
![noode](https://user-images.githubusercontent.com/42715523/67373810-d3ecb500-f5b2-11e9-955e-042833b0547d.png)

**Comment by xiaohuoni** [comment]
自己先测试一下，服务端有没有用咯。

**Comment by Shhuy** [comment]
在view层用ajax测试是可以的
![test](https://user-images.githubusercontent.com/42715523/67374745-35f9ea00-f5b4-11e9-80ad-c8e339125b91.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/16b969fe7577fca56f9ffaeaae5861cd7c2b8c58/package.json#L34

试试这个

**Comment by Shhuy** [comment]
这样可以了，但是设置完毕以后页面跳转就出现了问题。。。。

**Comment by chenshuai2144** [comment]
什么问题？ 你需要实现所有的接口

**Comment by Shhuy** [comment]
对现在所有的接口我都要写，有的已经报404，改成这样具体是因为什么原因呢

**Comment by chenshuai2144** [comment]
说的详细一点？
上下文是什么

**Comment by Shhuy** [comment]
为什么改成这样启动就可以了，是因为直接就没有使用mock数据吗？

**Comment by chenshuai2144** [comment]
`start:no-mock` 这个命令的意思就是不使用 mock

**Comment by Shhuy** [comment]
好的谢谢

**Comment by linghuxiong** [comment]
在config.ts 里面设置的代理，对登录不生效？
