### ISSUE TITLE
当pro项目的history为hash的时候，如何配置nginx

### ISSUE THREAD

**Issue by kaikaiRRSE** [ant-design/ant-design-pro#5479]
我的pro想的history为hash,有一个publicPath为test。用nginx镜像创建了一个test命名的容器。
我的ngingx 的容器的配置文件如下：

server {
    listen 8000;
    # gzip config
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    location ~ /test/.*\.(html/js/css)$ {
        try_files $uri $uri/ /index.html;
        root /usr/share/nginx/html/;
        index index.html index.htm;
    }

    location /test/ {
        proxy_pass http://192.168.64.3:8020;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}

这个容器的端口代理为8060>8000。

我虚拟机ip为192.168.64.3.
我前端pro项目build后的文件放在/usr/share/nginx/html/目录下
我想到达的效果为输入192.168.64.3:8060/test/进入项目定位到index.html进入首页。所有的数据请求走的是192.168.64.3:8020。
8020是我创建的专门为这个项目提供接口的一个sprinboot容器

我想请问一下正确耳朵配置改怎么写。谢谢

**Comment by chenshuai2144** [comment]
你的 api 要和 html 的路径区分开。
/test 既是代理也是 html 文件路径 nginx 分不清楚的

**Comment by kaikaiRRSE** [comment]
在都是test的路径下，我不能用正则表达式匹配test下面的静态资源吗？非静态资源的接口才经由转发

**Comment by kaikaiRRSE** [comment]
> 你的 api 要和 html 的路径区分开。
> /test 既是代理也是 html 文件路径 nginx 分不清楚的

在都是test的路径下，我不能用正则表达式匹配test下面的静态资源吗？非静态资源的接口才经由转发

**Comment by chenshuai2144** [comment]
你很难判断的，最好是是静态资源是static ， 接口是api

**Comment by kaikaiRRSE** [comment]
> 你很难判断的，最好是是静态资源是static ， 接口是api

因为现在是改造已经存在的项目，能否通过正则和location 的优先级进行判断，进行分发

**Comment by chenshuai2144** [comment]
那要去看看 nginx 的文档了，这个已经和 pro 没有关系了
