### ISSUE TITLE
[问题]2.3.1版本proxy代理失效问题

### ISSUE THREAD

**Issue by GrowingMonkey** [ant-design/ant-design-pro#5481]
我在使用贵公司的antd-design-pro2.3.1遇到个问题，烦请解答下，谢谢。
我在打包的时候新增了package.json配置，多环境打包

![image](https://user-images.githubusercontent.com/24692542/67496022-5c03b500-f6ae-11e9-8298-cfd19eae87dd.png)

然后在config新增了些全局变量后
![image](https://user-images.githubusercontent.com/24692542/67496085-72aa0c00-f6ae-11e9-8567-d6b6d5bcd1e3.png)

然后继续进行项目的二期开发，遇到了代理proxy不能使用的问题，其他配置我并没有改动
问题如下
1；新增config.js中的代理，
![image](https://user-images.githubusercontent.com/24692542/67496201-a38a4100-f6ae-11e9-9c16-0c03942e0b06.png)

开发环境下，在同一局域网类直接调用后台人员本机电脑运行接口即192.168.1.107这个接口，接口返回数据，
但是在调用先上测试环境和正式环境即（www.xxxx.com）的接口时，均报405。或者自己返回我的document源代码。
如下所示
![image](https://user-images.githubusercontent.com/24692542/67496296-c4eb2d00-f6ae-11e9-8212-34825b87d72c.png)

怀疑是代理不成功，然而我config.js并没有其他改动。serves文件夹中api.js改动如下
![image](https://user-images.githubusercontent.com/24692542/67496344-d46a7600-f6ae-11e9-9da7-c98723119143.png)

request.js改动如下
![image](https://user-images.githubusercontent.com/24692542/67496375-e2b89200-f6ae-11e9-97ba-ee4058e20f0f.png)

其他没有改变，百思不得其解。还请亲帮忙解答下
@chenshuai2144 ``

**Comment by GrowingMonkey** [comment]
已解决

**Comment by GrowingMonkey** [comment]
已解决

**Comment by GrowingMonkey** [comment]
已解决

**Comment by chenshuai2144** [comment]
>  ant design 为开源项目，并不是公司行为。

底层是 https://github.com/webpack/webpack-dev-server
看看这个吧

**Comment by chenshuai2144** [comment]
解决贴出来解决方式吧，可以帮到更多人

**Comment by GrowingMonkey** [comment]
> 解决贴出来解决方式吧，可以帮到更多人

![Uploading image.png…]()
代理失效基本就是这里配置错误，注释掉这行详情查看proxy文档配置属性
我都不好意思了

**Comment by laosandegudai** [comment]
> 解决贴出来解决方式吧，可以帮到更多人
> 
> 
> 代理失效基本就是这里配置错误，注释掉这行详情查看proxy文档配置属性
> 我都不好意思了

咋解决的？图裂了看不到解决方式
