### ISSUE TITLE
v4 菜单问题

### ISSUE THREAD

**Issue by ray-toby** [ant-design/ant-design-pro#5483]
config.js里面是routes    menuDataRender里面遍历子菜单时又是chidren  有点蒙
![$EGLGVTCQIZM) `6BB@HLJL](https://user-images.githubusercontent.com/19220426/67540202-27781380-f717-11e9-9cfc-9332fa5d239e.png)
![@Z3G~%`TGEZIWMPEBE@DB8M](https://user-images.githubusercontent.com/19220426/67540209-29da6d80-f717-11e9-9685-aa2c98afd266.png)    
菜单这块有详细点的demo吗  我想从后台拉取菜单  替换config.js里的routes  还是有其他思路   望大佬给点思路

**Comment by ray-toby** [comment]
![%I)MG3%20 QJ{F%9CI$G2(V](https://user-images.githubusercontent.com/19220426/67540438-f5b37c80-f717-11e9-8046-2184e2ce7891.png)

**Comment by chenshuai2144** [comment]
因为 umi 会自动转化一下。代码中的参数来自于 layout 的 props.

**Comment by ray-toby** [comment]
动态获取菜单是要将menudatarender里面这个函数的返回值返回规定的那种格式就行吗

2019年10月25日 上午11:27，"陈帅" <notifications@github.com>写道：

**Comment by ray-toby** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
是的。可以直接看待那

**Comment by ray-toby** [comment]
好的  已经实现了   继续踩坑
