### ISSUE TITLE
[BUG]ant design pro的表格数据精度缺失

### ISSUE THREAD

**Issue by ssyangtian** [ant-design/ant-design-pro#5487]
当后端返回的表格数据的id比较大时前端解析会缺失精度，比如将637143198711861248变为637143198711861200。请问怎么解决？

**Comment by chenshuai2144** [comment]
让后端转成 string。 js 不支持这么大的数字的。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number
