### ISSUE TITLE
🧐How to remove block 

### ISSUE THREAD

**Issue by hern12** [ant-design/ant-design-pro#5488]
How can I remove the block that I do not want to use?. Thank you

**Comment by zhoushaokun** [comment]
emm, I took a test, it seems work. Taking the block of **dashboardworkplace** as example. Firstly, delete the directory of **src/pages/dashboardworkplace**. Secondly, delete the router settings in **config/config.ts**. Lastly, restart the app. 
There is a possibility that It will cause  **Cannot find module .....src\pages\DashboardWorkplace** error in **.umi** when restarting, just Notes the code related the world of **dashboardworkplace**. The reason why I do this is [https://umijs.org/zh/guide/app-structure.html#src-pages-umi](url)

**Comment by hern12** [comment]
after I follow your step. it shows Cannot find module .....src\pages\DashboardWorkplace as you said and I can not use yarn start how to fix this

**Comment by hern12** [comment]
Hi, another question after I generate basic list and after I went to basic list page I got TypeError: Cannot read property 'getFieldDecorator' of undefined. I try to wrap solution before export. It seems does not work please help Thanks

**Comment by zhoushaokun** [comment]
comment the code related **DashboardWorkplace** which may be in [**pages/.umi/dva.js**](https://umijs.org/zh/guide/app-structure.html#src-pages-umi),  so app wont run the code of import part. Just like this:
![image](https://user-images.githubusercontent.com/32841670/67619469-aca21c00-f82e-11e9-8323-af7e168c9300.png)

**Comment by chenshuai2144** [comment]
This feature is under development, but it has a lot of limitations.
It is very difficult to determine whether this file should be deleted.

**Comment by zhoushaokun** [comment]
yeah, it will be perfect if "assets" TAB has the remove button of exited blocks. Just like this:
![image](https://user-images.githubusercontent.com/32841670/67628371-54efc900-f89f-11e9-9334-67066b1bc6b6.png)

**Comment by chenshuai2144** [comment]
We can't identify the user's code, we may just revoke it.
 Add -> Undo, it will be lost after reboot
