### ISSUE TITLE
按照官方文档安装，出现很多deprecated的警告🧐[问题]

### ISSUE THREAD

**Issue by xvdy** [ant-design/ant-design-pro#5490]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12590255/67632581-2f36e400-f8e0-11e9-824a-02a936b4b740.png)

**Comment by chenshuai2144** [comment]
没图没真相

**Comment by afc163** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/507615/67664170-12fb7b80-f9a2-11e9-8f41-14b0214c8d09.png">

@chenshuai2144

**Comment by chenshuai2144** [comment]
这些依赖过于底层了，是 umi 和 dva 的依赖，去 umi 中提交 issue 吧
