### ISSUE TITLE
🧐[问题]页面路由配置后，找不到指定文件

### ISSUE THREAD

**Issue by limerickgds** [ant-design/ant-design-pro#5493]
### 🧐 问题描述

配置了路由，发现为啥生成的路径错误，导致 require 失败
![image](https://user-images.githubusercontent.com/9961514/67648705-74572680-f971-11e9-8566-a45b5212877f.png)

**另外建议一下， ant-design-pro  官网的路由配置文档实在过于简单和平白直叙了（文档约等于初始化router.config.js）。 一会 routes ，一会 children 这个背后逻辑没 get 到。**

### 💻 示例代码
router.config.js
```js
export default [
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    routes: [{
        path: '/form',
        icon: 'form',
        name: '活动',
        component: './Forms/BasicForm',
      },
      {
        path: '/user-manage',
        icon: 'user',
        name: '用户管理',
        children: [{
          path: "/user-manage/users",
          component: './UserManage/Users',
          name: "用户组管理"
        },
        {
          path: "/user-manage/form/user",
          component: './UserManage/Form/UserForm',
          name: "创建用户组"
        }]
      }
    ],
  }
];
```

### 🚑 其他信息
生成的 .umi/router.js
![image](https://user-images.githubusercontent.com/9961514/67648872-e0d22580-f971-11e9-9f9c-4cb310d635f5.png)

**Comment by sunha1yang** [comment]
+ 1

**Comment by sunha1yang** [comment]
+1

**Comment by sunha1yang** [comment]
官方文档写的有点问题，你把children更改成routes试一下

**Comment by chenshuai2144** [comment]
来个 pr？

routes 是 umi 新版本的配置

**Comment by sunha1yang** [comment]
> 来个 pr？
> 
> routes 是 umi 新版本的配置

```
export default [
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    routes: [{
        path: '/form',
        icon: 'form',
        name: '活动',
        component: './Forms/BasicForm',
      },
      {
        path: '/user-manage',
        icon: 'user',
        name: '用户管理',
        children: [{
          path: "/user-manage/users",
          component: './UserManage/Users',
          name: "用户组管理"
        },
        {
          path: "/user-manage/form/user",
          component: './UserManage/Form/UserForm',
          name: "创建用户组"
        }]
      }
    ],
  }
];

将里面的children改成 routes就可以了
```

**Comment by chenshuai2144** [comment]
现在官网上还有哪里没有改过来？

**Comment by sunha1yang** [comment]
> 现在官网上还有哪里没有改过来？

刚刚看，还没有呢。。
![image](https://user-images.githubusercontent.com/19144976/67661784-06c0ef80-f99d-11e9-8d7f-e4039b1c16cf.png)

**Comment by chenshuai2144** [comment]
来个链接

**Comment by sunha1yang** [comment]
> 来个链接

https://pro.ant.design/docs/router-and-nav-cn

**Comment by chenshuai2144** [comment]
这个是 menuitem 的数据结构，不是 config.js 的配置文件，就应该是 children

**Comment by sunha1yang** [comment]
> 这个是 menuitem 的数据结构，不是 config.js 的配置文件，就应该是 children

如果按照这个菜单栏的配置项就会出现题主这样的问题

**Comment by limerickgds** [comment]
@chenshuai2144 如这位同学 @sunha1yang 所说，改成 routes 即可。但你说应该是 children ，这就会出现 .umi/router.js 生成路径有误。

**Comment by afc163** [comment]
> 这个是 menuitem 的数据结构，不是 config.js 的配置文件，就应该是 children

文档里可以特别提示一下，免得其他人搞错。 @chenshuai2144
