### ISSUE TITLE
🧐app启动时model中state初始化的问题

### ISSUE THREAD

**Issue by cc29sf3** [ant-design/ant-design-pro#5494]
### 🧐 问题描述

我的web应用每次启动时需要访问httpApi, 一次性获取所有基础数据, 加载到某个model的state中,  也就是说state的初始化需要访问网络,  但我找不到合适的位置来添加这个逻辑,  antd-pro有没有什么钩子函数或者入口点能初始化state呢?
我目前是在UserLayout.jsx中加入了一行代码,但这明显不是好的解决方法
![image](https://user-images.githubusercontent.com/4985889/67651336-76be7e00-f97b-11e9-9daa-f2c792743746.png)

**Comment by chenshuai2144** [comment]
Layout 就是用来做这个事情的，你的做法其实是对的
