### ISSUE TITLE
👑 [需求]切换横轴的菜单栏，然后侧边也出现不同的菜单项目

### ISSUE THREAD

**Issue by zytjs** [ant-design/ant-design-pro#5495]
### 🥰 需求描述
切换横轴的菜单栏，然后侧边也出现不同的菜单项目
就是 https://ant.design/components/layout-cn/ 中的顶部--侧边布局--通栏的布局
这个v4版本支持了吗？#1231

**Comment by chenshuai2144** [comment]
你可以通过两个 pro-layout 的嵌入来实现这个功能

**Comment by zytjs** [comment]
@chenshuai2144 可以在ProLayout的children实现吗

**Comment by chenshuai2144** [comment]
```
< ProLayout>
    <ProLayout>
       {children}
   </ProLayout>
</ProLayout>
```
这样搞

**Comment by zytjs** [comment]
试试先
