### ISSUE TITLE
🧐[问题] 导航菜单使用了iconfont的图标，当鼠标移到或选中某一项，替换另一个图标，有什么好的方法呢？

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#5496]
### 🧐 问题描述

导航菜单使用了iconfont的图标，当鼠标移到或选中某一项（包含子菜单），替换另一个图标，有什么好的方法呢？，如下图所示：

![TIM图片20191028145043](https://user-images.githubusercontent.com/23411433/67657445-be500480-f991-11e9-9c32-6174feed365b.png)

**Comment by mstao** [comment]
已经实现了

**Comment by dong136279559** [comment]
请问是如何实现的呢？

**Comment by mstao** [comment]
> 请问是如何实现的呢？

我当时是监听鼠标移入移除导航栏item事件，手动替换icon的

**Comment by dong136279559** [comment]
好的，感谢您的回复，我也用这种方法去实现吧



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月2日(星期五) 上午9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] 导航菜单使用了iconfont的图标，当鼠标移到或选中某一项，替换另一个图标，有什么好的方法呢？ (#5496)





  
请问是如何实现的呢？
  
我当时是监听鼠标移入移除导航栏item事件，手动替换icon的
