### ISSUE TITLE
👑 [需求]如果测试发布和正式发布的域名配置不同，需要做什么样的处理

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design-pro#5497]
### 🥰 需求描述
打包后也分为测试版本和正式发布版，想问下，如果两者要求域名配置不相同该如何来处理，config只有一个域名配置，怎么区分是正式还是测试版本

### 🚑 其他信息
还有个问题，如果我想设置一个全局变量，放在哪里比较好，还有通用工具类函数

**Comment by chenshuai2144** [comment]
域名配置？
你是通过跨域的方式来请求后端吗？

**Comment by junhui75165** [comment]
是的，不是同一个域名下的

**Comment by chenshuai2144** [comment]
可以通过环境变量来处理。
https://github.com/ant-design/ant-design-pro/blob/051f5c1dca1899d8392f62df47d15e5b794f6f53/config/config.ts#L11
build 的时候设置不同的，就能快速切换
