### ISSUE TITLE
What's the relationship between here and antd-admin?

### ISSUE THREAD

**Issue by chenqingspring** [ant-design/ant-design-pro#55]
I know here is a official release, but [antd-admin](https://github.com/zuiidea/antd-admin) also use dva, mockjs, roadhog. 

So I'm curious about what's the relationship between them? 

Will antd-admin be long term maintained?

**Comment by afc163** [comment]
>  what's the relationship between them?

antd-admin is mantained by @zuiidea which is not antd official member. There is no relationship between them.

> Will antd-admin be long term maintained?

We realy don't know, you can ask in antd-admin's issue.

**Comment by chenqingspring** [comment]
Thank your for confirming what I was thinking.
