### ISSUE TITLE
图标色彩不符

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#550]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/507615/34482020-5cf4cbbe-eff0-11e7-8442-8bb071f47a62.png">

旧版：https://preview.pro.ant.design/#/dashboard/analysis

**Comment by nikogu** [comment]
fixed: https://github.com/ant-design/ant-design-pro/commit/481787a7aae492ebda5565d7e8a817b24ff5e7e5

**Comment by afc163** [comment]
<img width="170" alt="image" src="https://user-images.githubusercontent.com/507615/34508725-7d5e51da-f07d-11e7-847e-3013dd8b7109.png">

圆点貌似还有点问题。

**Comment by afc163** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/507615/34522388-4f444962-f0cd-11e7-955e-5a8ef9ff74f2.png">

**Comment by nikogu** [comment]
> 圆点貌似还有点问题。

![image](https://user-images.githubusercontent.com/1179603/34553261-78ccec96-f161-11e7-807b-47c8b37f602a.png)

好像比以前的这个好看 =。-

**Comment by nikogu** [comment]
fixed: https://github.com/ant-design/ant-design-pro/pull/567
