### ISSUE TITLE
🐛[BUG] calling router.push() on an Authorized path

### ISSUE THREAD

**Issue by shlomitsur** [ant-design/ant-design-pro#5500]
Hello!

I have a path in my router.config.js with:
```
          {
            path: '/items/new',
            name: 'items',
            component: './NewItem',
            authority: ['admin'],
          },
```
When I reload this path the authority is enforced as expected.
When I call this path using router.push() the authority is enforced only in the 1st time, after that it is not enforced.
```
          <Button  onClick={() => router.push('/items/new')}>
            New Item
          </Button>
```

What am I doing wrong?
Thank you

**Comment by chenshuai2144** [comment]
fixed
