### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by gaorubin1990** [ant-design/ant-design-pro#5503]
### 🐛 bug 描述

需求：动态获取加载国际化的配置信息。
我在rootContainer中用一个组件AAA去包裹root根组件，但是在这个AAA中组件中无法使用connect，会报错，下图。感觉这个dva是在root根组件中封装的。这种如何处理呢？或者有其他动态获取国际化的解决方案吗？

Could not find "store" in either the context or props of "Connect(LocalContainer)". Either wrap the root component in a , or explicitly pass "store" as a prop to "Connect(LocalContainer)".
### 🏞 期望结果
动态获取加载国际化的配置信息

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
直接 用原声的 intl-react 好了，我们封装了一下虽然简单了，但是自由度下去了

**Comment by gaorubin1990** [comment]
想说的问题是在rootContainer封装了一个国际化的组件，但是在这个组件中无法获取global的state。没办法只能把组件加在了layout文件中。
