### ISSUE TITLE
🧐[问题]怎么更改导航栏子菜单样式，昨天拉的代码。

### ISSUE THREAD

**Issue by xzylogic** [ant-design/ant-design-pro#5504]
### 🧐 问题描述
怎么更改导航栏子菜单样式，昨天拉的代码。。

### 🚑 其他信息

默认是这样的：
![22](https://user-images.githubusercontent.com/25906872/67735994-d16ddd80-fa40-11e9-8de4-8bfb37fdf120.png)

怎么写成这样(我看了下，只是在routes里面生成的这个导航栏，并没有页面JSX去写。。)：
![11](https://user-images.githubusercontent.com/25906872/67736010-daf74580-fa40-11e9-8083-ec9e54782b81.png)

**Comment by chenshuai2144** [comment]
antd 现在不支持你这样的魔改的。
你可以在 rc-menu 的基础上自己实现一下。

https://www.npmjs.com/package/rc-menu
