### ISSUE TITLE
🧐[问题]  how request data from backend server?

### ISSUE THREAD

**Issue by abhinavpanse** [ant-design/ant-design-pro#5508]
I need help in requesting data from server. The documentation is also not given nicely. So can you please tell me how can I request data from server. And what changes I have to do in default boilerplate to request data from backend server?

**Comment by zhoushaokun** [comment]
I think the API document of [DVA](https://github.com/dvajs/dva/blob/master/docs/API.md) will help you. Moreover, you can see the content about [mock ](https://umijs.org/guide/mock-data.html) if you need.
