### ISSUE TITLE
关于menu服务端返回

### ISSUE THREAD

**Issue by DingTaiKeji** [ant-design/ant-design-pro#551]
可否修改/src/common/menu.js菜单数据由服务端返回，这样从/src/common/router.js中就可以根据返回菜单数据绑定model和组建，也达到了权限控制的效果，希望developer予以采纳为谢！

**Comment by WhatAKitty** [comment]
前后端完全分离，不建议菜单由服务端干涉




| |
许强
|
|
邮箱：104xuqiang@163.com
|

签名由 网易邮箱大师 定制

在2018年01月02日 19:47，DingTaiKeji 写道：

可否修改/src/common/menu.js菜单数据由服务端返回，这样从/src/common/router.js中就可以根据返回菜单数据绑定model和组建，也达到了权限控制的效果，希望developer予以采纳为谢！

**Comment by chenshuai2144** [comment]
许强你暴露了

**Comment by WhatAKitty** [comment]
……




| |
许强
|
|
邮箱：104xuqiang@163.com
|

签名由 网易邮箱大师 定制

在2018年01月02日 21:02，陈帅 写道：

许强你暴露了

**Comment by chenshuai2144** [comment]
你干嘛把我的也修改了。。。。

**Comment by chenshuai2144** [comment]
多好的留帖为证

**Comment by WhatAKitty** [comment]
。。。不能暴露了。

**Comment by DingTaiKeji** [comment]
那菜单怎么实现权限控制，有什么好的方案吗

**Comment by chenshuai2144** [comment]
有个分支上已经又解决方案了.

**Comment by DingTaiKeji** [comment]
那太好了，马上可以应用正式环境了

**Comment by ychow** [comment]
@chenshuai2144  如果菜单数据不明确，这种情况下，必须得从后端数据获取。。。  有没有思路可以实现呢。。

**Comment by chenshuai2144** [comment]
看看meun.js 你完全可以从服务器获取这个js的内容

**Comment by mrandpz** [comment]
@chenshuai2144 请问菜单数据从后端获取，

`import { getMenus } from "../services/api";`

`export const getMenuData = () => formatter(getMenus);`

这个getMenus 返回的是一个promise，要怎么做处理~

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34727785-e1dd39f4-f592-11e7-8c45-0aae43049def.png)

看看这些 用model来进行这些数据的处理。

你要是想直接用 
`getMenus.then((meun)=>console.log(meun));`
或
`const meun = await getMenus();`

都是很好的解决方式

**Comment by ychow** [comment]
@chenshuai2144   大佬，有一点很奇怪就是，menu.js里的数据通过API获取数据后，视图不会更新。。。

**Comment by chenshuai2144** [comment]
放到redux里面。
数据更新刷新试图

**Comment by ychow** [comment]
@chenshuai2144  大佬，在menu.js里，如何把数据放到redux啊。。。  router.js里也是引用的menu.js这个文件。。

**Comment by chenshuai2144** [comment]
@ychow  大兄弟呀。。 不行你就整一个loading界面。meun查询出来了。在开始执行业务代码

**Comment by mrandpz** [comment]
@chenshuai2144  你好。我把请求menus放在 global.js  
```
*fetchMenus(_,{call,put}){
      const response = yield call(getMenus);
      yield put({
        type: 'saveMenus',
        payload: response,
      });
    }
```

```
saveMenus(state, action) {
      return {
        ...state,
        menus: action.payload,
      };
    },
```
但是视图并没有更新，而且在common/router.js 里的 app._models 里找到的menus的数据也还是初始化的 []   。   在chrom的redux插件能找到数据。

**Comment by chenshuai2144** [comment]
参考一下我这个。等这些都完成在开始加载app这些的界面
![image](https://user-images.githubusercontent.com/8186664/34933608-6e649704-fa12-11e7-9cbb-5c1515774833.png)

**Comment by mrandpz** [comment]
@chenshuai2144  等加载完页面之后菜单栏正常显示，但是在common下的router.js  getRouterData 也需要做控制的？此时app._models 还是初始值。用户手动输入路径的时候依然可以访问这个页面。还是我又错了=。=

**Comment by pengshaomin** [comment]
@mrandpz 碰到同样问题

**Comment by kateli** [comment]
好尴尬 
菜单栏是从后台获取的
后台会返回符合当前角色的菜单
但是不会返回path
但是 怎么让菜单和对应的path关联起来呢
