### ISSUE TITLE
🧐[问题]页面路由跳转后变成 File not found.

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design-pro#5511]
### 🧐 问题描述

在本地测试中用location.href做路由跳转没有问题，但是部署后的使用location.href跳转变成File not found.而且是同一个页面（从host/user/login转到host/user/login）

### 💻 示例代码

`request.interceptors.response.use(async (response) => {
  const data = await response.clone().json();
  if(data && data.code===505) {
    notification.error({
      description: '登录已超时，您需要重新登录',
      message: '登录失效',
    });
    setTimeout(()=>{location.href = '/user/login';},2000);
  }
  return response;
});`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/3411959/67753370-920ab580-fa6f-11e9-98b1-8acea5bb0240.png)

![image](https://user-images.githubusercontent.com/3411959/67753321-815a3f80-fa6f-11e9-8c9b-f406b73ab8f0.png)

**Comment by huntdream** [comment]
https://pro.ant.design/docs/deploy-cn
你这个是前端的路由，实际上后台或者服务器并没有做对应的响应处理，所以请求不到对应的资源
本地的环境应该是做了类似这样的处理
```
app.use(express.static(path.join(__dirname, 'build')));

app.get('/*', function (req, res) {
  res.sendFile(path.join(__dirname, 'build', 'index.html'));
});
```

**Comment by junhui75165** [comment]
@huntdream 这种情况是需要服务端配置的nginx做处理吗？

**Comment by junhui75165** [comment]
![image](https://user-images.githubusercontent.com/3411959/67913811-35bba900-fbc9-11e9-95c7-871d14135b2c.png)
问题已经解决了~配置搞错了
