### ISSUE TITLE
🧐[问题]我在使用electron打包ant design pro v2 版本的时候请求一直是失败的

### ISSUE THREAD

**Issue by TestsLing** [ant-design/ant-design-pro#5512]
### 🧐 问题描述

在进行使用electron时 我查看了issue进行配置
但是貌似所有的请求都走了file协议 寻找原因未果

### 💻 示例代码
![image](https://user-images.githubusercontent.com/40593646/67756545-27f50f00-fa75-11e9-8d3a-fcad9a2fb66e.png)

对config配置：
history: 'hash',
publicPath: './'

electron main文件如下
![image](https://user-images.githubusercontent.com/40593646/67756862-bbc6db00-fa75-11e9-9567-44d889c8dde2.png)

之后进行 build  通过electron查看build后的页面 出现如下问题
![image](https://user-images.githubusercontent.com/40593646/67757028-047e9400-fa76-11e9-8797-897eb14aff25.png)

**Comment by chenshuai2144** [comment]
electron 中要使用 web 需要做一些特殊定制的。
https://github.com/ant-design/ant-design-pro/issues/1874

**Comment by ShawLyon** [comment]
兄弟，解决了吗？我也遇到请求不了接口的问题

**Comment by ShawLyon** [comment]
> electron 中要使用 web 需要做一些特殊定制的。
> #1874

1874我看了n遍，并没有大佬说的关于请求后端接口的，我现在请求的接口都是file://开头，衰

**Comment by yutuan11** [comment]
请求的接口都是file://开头，生产环境需要把axios的请求路径补全。比如我是ant-pro v5，在app.tsx文件中，写request配置加入prefix前缀。
![image](https://github.com/ant-design/ant-design-pro/assets/151594387/a3f767a6-df66-4b72-9934-4f2f63aa4620)
