### ISSUE TITLE
🧐[问题]请问第一次启动的时候该如何怎么处理umi.js

### ISSUE THREAD

**Issue by liangminghui** [ant-design/ant-design-pro#5513]
我build项目之后，将项目部署到服务器上的时候，第一次访问网址加载umi的js和css耗时很久，请问一下这里有什么办法么[图片]

**Comment by imhele** [comment]
在环境变量 [ANALYZE=1](https://umijs.org/zh/guide/env-variables.html#analyze) 下执行 `umi build` 命令，发下产物内容分析的截图。

> 可能的原因与解决办法
- 启用 [dynamicImport](https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport)
- 引入了不必要的 moment locale ，安装 moment-locales-webpack-plugin ，在 .umirc.{ts|js} 或 config/config.{ts|js} 中添加如下配置：
```js
import MomentLocalesPlugin from 'moment-locales-webpack-plugin';
export default {
  ...
  chainWebpack(config) {
    config
      .plugin('moment-locales-webpack-plugin')
      .use(new MomentLocalesPlugin({ localesToKeep: ['zh-cn'] }));
  },
  ...
};
```

**Comment by Ryan1024dr** [comment]
@liangminghui 我也遇到了这个问题 请问你是怎么解决的呢
