### ISSUE TITLE
网站的标题怎么自定义

### ISSUE THREAD

**Issue by Imhemers** [ant-design/ant-design-pro#5515]
如下图的标题怎么自定义 好像只能修改 Ant Design Pro , 我想把-前面的也修改  该怎么弄

![image](https://user-images.githubusercontent.com/18650947/67836357-5af7db00-fb27-11e9-86fc-c223e2ed5725.png)

**Comment by mstao** [comment]
这里 https://github.com/ant-design/ant-design-pro/blob/master/src/pages/document.ejs#L10

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/locales/zh-CN/menu.ts
