### ISSUE TITLE
🧐[问题] expodrt default configDomain

### ISSUE THREAD

**Issue by ZuccRoger** [ant-design/ant-design-pro#5516]
### 🧐 问题描述

这个文件是一个存放http地址头的文件.放在了src/pages/domanconfig.js
我在需要的地方 import .但是 npm start 的时候发现 
export default configDomain
SyntaxError : Unexpected token export 

### 💻 示例代码

const configDomain = {
  mock: "https://www.easy-mock.com/mock/5d4a7312a8339a31ff1ff24c", // mock接口地址
  domain: "http://10.1.11.112:33027", // 后台接口地址
  // domain: "http://localhost:7739", // 后台接口地址
  caas: 'http://192.168.19.101:30088',//观云台地址
  swagger: 'http://127.0.0.1:7002'//Swagger地址
}
export default configDomain;

### 🚑 其他信息

源码在这里 https://github.com/ZuccRoger/FontEnd.git

![image](https://user-images.githubusercontent.com/37689108/67835794-db1d4100-fb25-11e9-87b2-27284e876d18.png)

**Comment by huntdream** [comment]
umi文档中写到
 [src/pages](https://umijs.org/zh/guide/app-structure.html#src-pages)
> 约定 pages 下所有的 js、jsx、ts 和 tsx 文件即路由。

 [配置式路由](https://umijs.org/zh/guide/router.html#%E9%85%8D%E7%BD%AE%E5%BC%8F%E8%B7%AF%E7%94%B1)
> 如果你倾向于使用配置式的路由，可以配置 .umirc.(ts|js) 或者 config/config.(ts|js) 配置文件中的 routes 属性，此配置项存在时则不会对 src/pages 目录做约定式的解析

但是看了你的config.ts是配置式路由
试了一下，把domanconfig.js从pages里面移到其他地方比如config里面就可以跑了

**Comment by chenshuai2144** [comment]
只有 config 下面的文件，umi 才会帮你自动 babel 一下，page 下面的将不会更改。

你需要 node 的模块管理系统
