### ISSUE TITLE
在页面内如何获取进入的, 或者即将前往的路由?

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#5517]
如题,在页面内, 如何获取到这个页面的路由,即将前往的路由.
有没有像vue路由守卫这样的?

**Comment by chenshuai2144** [comment]
React router 删除了 onEnter 。
但是 Layout 的生命周期可以来完成这个事情。写起来更符合 react 的哲学。不过有点麻烦

**Comment by z-lionel** [comment]
> React router 删除了 onEnter 。
> 但是 Layout 的生命周期可以来完成这个事情。写起来更符合 react 的哲学。不过有点麻烦

本来是想每个页面都保存请求参数在redux，切换路由的时候，如果不是子路由就清空当前页面redux的参数。
如果页面没有办法在离开获取到下个路由信息，那就无法判断能不能清楚，那就不能每个页面保存。
在layout里面通过下面的方法，获取到下个路由信息，那就只好一起保存到global里面了
https://umijs.org/zh/guide/router.html#scroll-to-top
