### ISSUE TITLE
🐛[BUG] 添加区块后   页面报错。

### ISSUE THREAD

**Issue by dxd1102** [ant-design/ant-design-pro#5518]
### 🐛 bug 描述

通过  umi block list 添加 基础表单 区块后 ，添加的路径会引起错误 。
TypeError: Cannot read property 'getFieldDecorator' of undefined

### 📷 复现步骤

1. umi block list
2. 选择 FormBasicForm 区块
3. 安装区块路径为 persion/list
4. 成功后跳转到该页面。
5. 报错 TypeError: Cannot read property 'getFieldDecorator' of undefined

### 🏞 期望结果

页面正常出现。

### 💻 复现代码

无需代码

### © 版本信息

- Ant Design Pro 版本: 4.0
- umi 版本 2.10.7
- 浏览器环境 chrome 最新
- 开发环境 Windows

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39640841/67843754-913d5680-fb37-11e9-845b-e596a982cc11.png)

![image](https://user-images.githubusercontent.com/39640841/67843831-b7fb8d00-fb37-11e9-9161-2474f02faecb.png)

**Comment by chenshuai2144** [comment]
try use  umi ui
https://umijs.org/zh/guide/umi-ui.html
