### ISSUE TITLE
[疑问]拼接routes的时候，发现代码有异议的地方

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design-pro#552]
**问题：**
配置了20个路由，但是经过utils.js--getRoutes方法之后剩下13个路由，导致页面访问出错。
在使用BasicLayout的时候，路由的拼接地方。对于/user/:id/detail这样的参数路由（多级路由也有类似问题）支持下不是很好。
**结论：**
跟踪了下代码，发现在utils.js文件125行有块代码有异议。做了下微微改动，就可以很好的支持参数等多级路由。贴图：
_**断点调试图：**_
![image](https://user-images.githubusercontent.com/26354664/34483013-cfd5db54-eff6-11e7-8e3a-f6d0c8f83323.png)

代码改动之后的图：
![image](https://user-images.githubusercontent.com/26354664/34483020-de92f92e-eff6-11e7-9351-8898aab8be29.png)

临时先这样处理，等待官方解决方案。

**Comment by chenshuai2144** [comment]
路由是不是还需要重写一下逻辑。。。
黑箱子好多。

**Comment by WhatAKitty** [comment]
路由的逻辑没啥问题，不需要改成上述图片那样。
这样写是为了嵌套路由，默认子路由不在当前一层路由展示。

> 路由是不是还需要重写一下逻辑。。。
> 黑箱子好多。好多看的晕乎乎。。

逻辑是有点复杂，如果只是单纯应用没啥问题。如果是要设计路由的改写可能比较麻烦

**Comment by chenshuai2144** [comment]
现在流行微服务 或许可以这样模仿着来

**Comment by ddcat1115** [comment]
> 路由的逻辑没啥问题，不需要改成上述图片那样。
> 这样写是为了嵌套路由，默认子路由不在当前一层路由展示。

对的~

今天会把路由这块的文档补充上来

**Comment by wunayou** [comment]
@ddcat1115   我急需 不然真的要去改代码 太复杂了

**Comment by ddcat1115** [comment]
https://github.com/ant-design/ant-design-pro-site/blob/9ee824beab6497e39109eb8dc63bd8584ad41d4c/docs/router-and-nav.md

**Comment by gebilaoman** [comment]
疑问，这俩会不会冲突
![image](https://user-images.githubusercontent.com/26354664/34548648-2e656d22-f13e-11e7-994a-90528b1e38f4.png)
![image](https://user-images.githubusercontent.com/26354664/34548652-32fd6c40-f13e-11e7-9dd2-9c246278e83a.png)
@ddcat1115

**Comment by ddcat1115** [comment]
没懂，你说谁和谁冲突？

**Comment by hanxiansen** [comment]
>路由是不是还需要重写一下逻辑。。。黑箱子好多。好多看的晕乎乎。。

@chenshuai2144，@WhatAKitty， 赞同，pro项目的路由感觉写得确实有点复杂，我看了好几遍又没注释，看得有点绕，路由不光是配置在几个配置文件中，在页面中也嵌套了路由，不知道是不是因为项目周期比较长，到后期更改就很难改变了。

**Comment by chenshuai2144** [comment]
@hanxiansen 我正在酝酿一个新的改版. 会更加完美的.
