### ISSUE TITLE
🐛[BUG]新版系统在手机端，旁边的drawer，点击菜单后无法合上，搜索按钮在手机端也有问题，这些问题从4.0出来就一直有，你们不测试吗

### ISSUE THREAD

**Issue by zhangwd** [ant-design/ant-design-pro#5522]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis
无法再现，你需要给出详细的再现方法
