### ISSUE TITLE
👑 [需求] 当表格左右方向出现滚动条时，鼠标点击表格，可以左右拖拽

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#5523]
### 🥰 需求描述

当表格左右方向出现滚动条时，鼠标点击表格，可以左右拖拽，这样操作比较友好一点

**Comment by chenshuai2144** [comment]
antd 正在筹备 4.0 ，你的需求可能被无限期搁置，有兴趣可以去 antd 中直接发起 pr。
