### ISSUE TITLE
在IE11或360极速浏览器下切换语言报错 🐛[BUG]

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#5524]
### 🐛 bug 描述
在IE11或360极速浏览器下切换语言，会出现以下错误，并且页面一片空白。
![image](https://user-images.githubusercontent.com/50793943/67915571-66eaa800-fbce-11e9-82ee-ed40b11ab9fe.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.8.7
- 浏览器环境 IE11 或 360极速
- 开发环境 windows10 VSCODE

**Comment by chenshuai2144** [comment]
打开 sourcemap 查看一下为什么吧。可能引发了什么库的 bug

**Comment by shaohuatsou** [comment]
> 打开 sourcemap 查看一下为什么吧。可能引发了什么库的 bug

已经更新了也没用，你说的sourcemap是tsconfig.json里面那个sourcemap吗，配置是true，接下来要怎么操作啊？

**Comment by chenshuai2144** [comment]
是这个东西 
https://umijs.org/zh/config/#devtool

设置为 eval 在 ie 中显示的最好

**Comment by shaohuatsou** [comment]
你好，我按照你的设置，改成了 eval ，很奇怪的是现在他切换语言之后没有白屏了，请问这个eval会影响什么导致不白屏了？  另外还是有两个错误：
![image](https://user-images.githubusercontent.com/50793943/68065607-d398aa80-fd66-11e9-8bdf-c97f38de8374.png)
![image](https://user-images.githubusercontent.com/50793943/68065610-ddbaa900-fd66-11e9-833d-7ef0f814774c.png)
![image](https://user-images.githubusercontent.com/50793943/68065614-e8753e00-fd66-11e9-866a-95a4b08019e9.png)
![image](https://user-images.githubusercontent.com/50793943/68065619-f2973c80-fd66-11e9-96e9-f48294bf24dc.png)

**Comment by chenshuai2144** [comment]
看来是 event 不支持 ie11 造成的

https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

**Comment by shaohuatsou** [comment]
那不知道后续有改善机会吗？ 还是说以后也不会支持IE

**Comment by afc163** [comment]
https://stackoverflow.com/a/26596324/3040605

**Comment by shaohuatsou** [comment]
> https://stackoverflow.com/a/26596324/3040605

感谢回答，这个错误是pro里面封装好的库调用的，我现在修改的话到时候更新也比较麻烦，想先看看官方是准备如何处理这个问题。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/faq-cn#%E5%88%87%E6%8D%A2%E8%AF%AD%E8%A8%80%E6%97%B6%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E8%AF%AD%E8%A8%80%E6%97%A0%E6%B3%95%E5%88%87%E6%8D%A2
设置第二位参数吧
