### ISSUE TITLE
🧐[问题] Ant Design Pro v4 npm run fetch:blocks 之后，在路由上配置了权限，还是能访问受限的路由

### ISSUE THREAD

**Issue by kushu001** [ant-design/ant-design-pro#5527]
### 🧐 问题描述
 Ant Design Pro v4 npm run fetch:blocks 之后，在路由上配置了权限，还是能访问受限的路由

### 💻 示例代码
以下是未下载模块之前，对welcome做的权限配置
```javascript
    {
              path: '/welcome',
              name: 'welcome',
              icon: 'smile',
              component: './Welcome',
              authority: ['admin'],
            },
```

以下是下载之后，对monitor做的权限配置
```javascript
              {
                  name: 'monitor',
                  icon: 'smile',
                  path: '/dashboard/monitor',
                  component: './dashboard/monitor',
                  authority: ['admin'],
                },
```
以上是Monitor路由的权限配置，允许admin权限的访问，其它的不能访问，但是，现在情况是，user登录后，菜单上是不显示 Monitor了，路由还是一样能访问

在未把所有模块下下来这前，对Welcome路由配置是可以进行权限访问的，也就是user登录是会跳转到403页面的，做了npm run fetch:blocks之后，把所有模块下下来，相关配置就失效了

### 🚑 其他信息

以下是 未下载模块之前Welcome路由访问 
![图片](https://user-images.githubusercontent.com/3797320/67916674-6e5f8080-fbd1-11e9-9192-489fe341bce6.png)

以下是 所有模块下载下来后 路由访问
![图片](https://user-images.githubusercontent.com/3797320/67916091-96e67b00-fbcf-11e9-802a-38e69fd123a4.png)

**Comment by kushu001** [comment]
状态：已解决，
原因：原处理路由的方法是非递归的，所以里层菜单是处理不到的，只要写个递归方法处理一下即可，
解决方案：
utils.ts: 重写 getAuthorityFromRouter 方法即可（下面是递归的一个实现）
/**
 * props.route.routes
 * @param router [{}]
 * @param pathname string
 */
export const getAuthorityFromRouter = <T extends { path: string,routes:any }>(
  router: T[] = [],
  pathname: string,
): T | undefined => {
  const authority = getAuthorityRecursion(router,pathname);
  if (authority) return authority;
  return undefined;
};

interface Router{
  path:string,
  routes:any,
}

function getAuthorityRecursion(router:Router[],pathname:string):any{
  for(let route of router){
      let { path, routes } = route;
      
      if(path && pathRegexp(path).exec(pathname)){
        return route;
      } else {
        if(!routes){
          continue;
        }
        let authority = getAuthorityRecursion(routes,pathname);
        if(authority){
          return authority;
        }
      }
  }
    
}

**Comment by chenshuai2144** [comment]
来个 pr?

**Comment by kushu001** [comment]
> 来个 pr?

代码写的比较Low……

**Comment by chenshuai2144** [comment]
会审阅的

**Comment by kushu001** [comment]
> 会审阅的
> 被 review 能很快的提升代码质量，虽然有点掉社会地位

那行，我试试，还不太会用pr, 正好学一下

**Comment by minuux** [comment]
这样好像会在找到当前页面的权限前，遍历了其他路由的子路由吧？
我也需要这样的功能。
我先计算了当前页面的`pathname`有可能的路径,对这些路径遍历找权限
```
'/dashboard/monitor' => ['/dashboard','/dashboard/monitor']
```
判断`/dashboard`是否有限制，再判断'/dashboard/monitor'
