### ISSUE TITLE
Breadcrumb's bug?

### ISSUE THREAD

**Issue by ChiaJune** [ant-design/ant-design-pro#553]
[官方预览页面](https://preview.pro.ant.design/#/dashboard/analysis)，点击进到 列表页 -> 搜索列表 -> (搜索列表（项目）、搜索列表（应用）、搜索列表（文章）)任一页面，然后点击页面Breadcrumb上的 **搜索列表**，浏览器url会变成：`https://preview.pro.ant.design/#/list/search[object Object]`，同时404页面出现。

**Comment by chenshuai2144** [comment]
这个已经在 #507 中修复。
