### ISSUE TITLE
那我想把defaultSettings,放在外面，umi有没有提供方案，我要自己去babel吗？

### ISSUE THREAD

**Issue by chencs-art** [ant-design/ant-design-pro#5531]

**Comment by afc163** [comment]
你出现什么问题了么，提问请遵循模板。

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by chencs-art** [comment]
我希望在v4的版本中，把defaultSettings,放在src中，像v2那样，不过defaultSettings的代码中用了export，umi有方案可以处理这样的吗

**Comment by afc163** [comment]
v4 的 src 中也有 export，你现在是出现了什么问题呢？

**Comment by chencs-art** [comment]
https://github.com/ant-design/ant-design-pro/issues/5530

**Comment by chencs-art** [comment]
问题在上面的链接中

**Comment by chencs-art** [comment]
为什么在v4中defaultSettings.ts一定要写在config里，是将v2的项目升级到v4. 在原来项目中defaultSettings是写在src下面，然后运行一直报错。

export interface DefaultSettings {
// theme for nav menu
navTheme: string;

// primary color of ant design
primaryColor: string;

// nav menu position: sidemenu or topmenu
layout: 'sidemenu' | 'topmenu';

// layout of content: Fluid or Fixed, only works when layout is topmenu
contentWidth: string;

// sticky header
fixedHeader: boolean;

// auto hide header
autoHideHeader: boolean;

// sticky siderbar
fixSiderbar: boolean;

title: string;

iconfontUrl: string;

// 权限开关，是否开启权限处理，左侧 menu 权限和功能点的权限
isAuth: boolean;

platformPrefix: string;

platformApiPrefix: string;

// 是否使用管理员登录
isLoginManage: boolean;
};

export default {
navTheme: 'dark',
primaryColor: '#1890FF',
layout: 'sidemenu',
contentWidth: 'Fluid',
fixedHeader: false,
autoHideHeader: false,
fixSiderbar: false,
title: '',
iconfontUrl: '',
isAuth: true,
platformPrefix: '/hcloud',
platformApiPrefix: '/healthcloud',
isLoginManage: false,
} as DefaultSettings;

然后就：Unexpected token export
一直报这样的错误。

**Comment by chencs-art** [comment]
这个defaultSettings放在src目录下的

**Comment by chenshuai2144** [comment]
用 node 的方式即可。
module.exports = xxxx

**Comment by chencs-art** [comment]
那我在v4版本这里，defaultSettings里面怎么写成typeScript的代码，interface，export，按说都是不能使用的，那也就是这里就只能写成node的方式吗？

**Comment by chenshuai2144** [comment]
对，如果要写 ts 就要自己处理编译呀这些的了，最好还是放在 config 中

**Comment by chencs-art** [comment]
好的，谢谢

**Comment by chencs-art** [comment]
不过还是希望以后能支持一下，这样的诉求

**Comment by chenshuai2144** [comment]
config 只是个配置文件，不会支持很多花样的。
