### ISSUE TITLE
antd-pro,npm run build打包后, 页面一直loading，控制台报错，必须刷新一次才会好,Uncaught (in promise) ChunkLoadError: Loading chunk 29 failed.

### ISSUE THREAD

**Issue by shuangzhao66** [ant-design/ant-design-pro#5535]
每次打包部署到开发环境后第一次渲染抛出下图错误，然后就处于一直加载的状态，不知道如何解决
![image](https://user-images.githubusercontent.com/24361614/68001132-b77d0680-fc9d-11e9-8430-6ba37ec5cab0.png)
Uncaught (in promise) ChunkLoadError: Loading chunk 29 failed.

**Comment by chenshuai2144** [comment]
你的缓存除了问题造成的。
你可以通过关闭 按需加载来根治这个问题。

https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

**Comment by shuangzhao66** [comment]
> 你的缓存问题造成的。
> 你可以通过关闭 按需加载来根治这个问题。
> 
> https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

是把config.ts中，下面这段直接注释掉吗？        
dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      },

**Comment by twomiya** [comment]
关闭了也不行

> > 你的缓存问题造成的。
> > 你可以通过关闭 按需加载来根治这个问题。
> > https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport
> 
> 是把config.ts中，下面这段直接注释掉吗？
> dynamicImport: {
> loadingComponent: './components/PageLoading/index',
> webpackChunkName: true,
> level: 3,
> },

你解决了吗？我关闭了也不行，还是一直加载，控制台报错

**Comment by xyy7260** [comment]
@twomiya  请问你之前这个问题怎么解决的呢？

**Comment by xiaoshui222** [comment]
> 你的缓存问题造成的。
> 你可以通过关闭 按需加载来根治这个问题。
> 
> https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

除了这个办法还有其他办法吗

**Comment by xiaoshui222** [comment]
> 你的缓存问题造成的。
> 你可以通过关闭 按需加载来根治这个问题。
> 
> https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

除了这个方法，还有其他方法吗，不想关闭按需加载呢

**Comment by xiaoshui222** [comment]
> 你的缓存问题造成的。
> 你可以通过关闭 按需加载来根治这个问题。
> 
> https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

什么的缓存问题会导致这样

**Comment by taofeifanIT** [comment]
> > 你的缓存问题造成的。
> > 你可以通过关闭 按需加载来根治这个问题。
> > https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport
> 
> 什么的缓存问题会导致这样

链接失效了啊

**Comment by lanxiaojia** [comment]
> 你的缓存问题由你创建。 你可以关闭本机缓存并重新加载这个问题。
> 
> https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

@chenshuai2144 你好 这个链接失效了  可以发下新地址吗 谢谢
