### ISSUE TITLE
🧐[问题] Please update the following components: Connect(AvatarDropdown), Connect(BasicLayout), Connect(GlobalHeaderRight)

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5536]
### 🧐 问题描述
Please update the following components: Connect(AvatarDropdown), Connect(BasicLayout), Connect(GlobalHeaderRight)

pro 控制台报黄，好像

### 💻 示例代码

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30397655/68004466-9a9bff80-fcac-11e9-894f-534fb693a787.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/5534

最后一个了

**Comment by chenshuai2144** [comment]
升级了 dva 版本，已经解决了。
