### ISSUE TITLE
🐛[BUG] ESLint 无法正常使用，执行 npm run lint:js 时报错！

### ISSUE THREAD

**Issue by shuangmianxiaoQ** [ant-design/ant-design-pro#5537]
### 🐛 bug 描述

克隆最新的`ant-design-pro`，安装依赖后，`ESLint`无法正常使用，执行`npm run lint:js`时报错！（`Error: Cannot find module '@umijs/fabric/dist/eslint'`）

### 📷 复现步骤

1. `git clone https://github.com/ant-design/ant-design-pro.git`
2. `npm i`
3. `npm run lint:js`

![image](https://user-images.githubusercontent.com/22791257/68006934-1a2dcc80-fcb5-11e9-9740-105641ae3932.png)

### 🏞 期望结果

`ESLint`正常使用，执行脚本正常

### 💻 复现代码

```js
module.exports = {
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
  globals: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
    page: true,
  },
};
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] `4.0.0`
- umi 版本 `2.9.6`
- 浏览器环境 `Chrome 78.0.3904.70`
- 开发环境 [e.g. mac OS] mac OS 10.14.6

### 🚑 其他信息

在同事`Windows`系统上可以正常执行脚本，在自己电脑上有这个问题

**Comment by chenshuai2144** [comment]
先装依赖？

**Comment by shuangmianxiaoQ** [comment]
> 先装依赖？

依赖安装了，`npm i`

**Comment by chenshuai2144** [comment]
看起来是依赖安装失败了，删除重装一下，ci 里面有 mac 的测试，跑的是同样的脚本

**Comment by shuangmianxiaoQ** [comment]
> 看起来是依赖安装失败了，删除重装一下，ci 里面有 mac 的测试，跑的是同样的脚本

我删了重装不行，清除`npm`缓存，换`npm`源，用`yarn`安装也都不行，刚在同事`Mac`上试了一下能正常运行，我这边不知道怎么回事，跑步起来

**Comment by chenshuai2144** [comment]
是不是全局装了什么依赖。
你清理一下全局的包试试

**Comment by AIEPhoenix** [comment]
如果当前工程的上级目录也有一个.eslintrc.js之类的就会出现这个问题
