### ISSUE TITLE
列表页点击详情按钮进无法入详情页🧐[问题]

### ISSUE THREAD

**Issue by weiTimes** [ant-design/ant-design-pro#5538]
### 💻 示例代码
不知道是不是我的路由配置问题，这里是我的路由配置代码，我是根据文档中使用带参数的路由配置，但好像不是很详细。
![image](https://user-images.githubusercontent.com/21688593/68024402-fc785b80-fce4-11e9-8283-9e53836f5efa.png)
这里是路由跳转
![image](https://user-images.githubusercontent.com/21688593/68024426-0d28d180-fce5-11e9-894c-735c37ae0f7e.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/68024704-d0a9a580-fce5-11e9-8042-7de171f211e2.png)


这里的路由会继承父亲的路由，你可以在前面加个 `/` 使用绝对路由

**Comment by weiTimes** [comment]
yi,还有图片怎么没了，我再提交一下

**Comment by chenshuai2144** [comment]
你的网络可能不好

**Comment by weiTimes** [comment]
什么情况github老要我验证邮箱，好捉急哦。
![image](https://user-images.githubusercontent.com/21688593/68024955-8674f400-fce6-11e9-9fe1-78491183d5cc.png)
还有这个是界面效果图，补一下
![image](https://user-images.githubusercontent.com/21688593/68024995-a86e7680-fce6-11e9-9bfe-e5643727a644.png)

**Comment by weiTimes** [comment]
![image](https://user-images.githubusercontent.com/21688593/68025151-14e97580-fce7-11e9-9b52-b76b437899b1.png)

**Comment by chenshuai2144** [comment]
要先拉成平级。不能设置为子节点，子节点会在 props 中传入

**Comment by weiTimes** [comment]
谢谢哦，可以了
