### ISSUE TITLE
关于antd design pro 的Tab页问题

### ISSUE THREAD

**Issue by xiangfeiying** [ant-design/ant-design-pro#554]
请问，我想在使用antd design pro的时候，点击左侧菜单，右边打开的是一个Tab页，如何实现呢？我本人是做后台的，刚刚开始接触前端的框架，还请多多指教，谢谢！

**Comment by chenshuai2144** [comment]
你需要补得课还有好多.
这个是通过react-router实现的.你可以看看文档 自己试一试

**Comment by ddcat1115** [comment]
这里主要用来讨论 antd pro 使用/bug/建议等相关问题，前序知识需要自己先看下~

https://reactjs.org/
https://reacttraining.com/react-router/web/guides/philosophy
