### ISSUE TITLE
🐛[BUG] Button 波浪动画 影响样式bug 

### ISSUE THREAD

**Issue by glitchboyl** [ant-design/ant-design-pro#5540]
### 🐛 bug 描述

减少 Form.Item 的项数缩短了浏览白色部分的高度之后, 点击按钮触发**波浪动画**.
此时白色部分高度会占满父容器, 然后(按钮波浪动画结束)几秒后恢复原样.

目前的解决方法是给在外层的 main 添加样式 `height: 100%;`

### 🏞 期望结果

无显示错误变化样式.

### 💻 复现代码

[官方的预览示例](https://preview.pro.ant.design/account/settings) 
在基本设置的 Form 中 选择几行 `className='ant-row ant-form-item'` 的 dom 节点删除.
然后点击下方的 更新基本信息 按钮 即可复现 bug.

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本: ^2.9.6
- 浏览器环境: Chrome
- 开发环境: Windows 10

### 🚑 其他信息

bug 演示gif:

![bug](https://user-images.githubusercontent.com/12504732/68066897-3d6e7f80-fd7a-11e9-9fa0-4d3411a56bc4.gif)

**Comment by chenshuai2144** [comment]
竟然这么神奇 😂 。我去查看一下具体原因

**Comment by chenshuai2144** [comment]
antd@4 中不会发生了
