### ISSUE TITLE
🧐[问题] ant pro怎么实现菜单分组呢？

### ISSUE THREAD

**Issue by liujiayii** [ant-design/ant-design-pro#5541]
### 🧐 ant pro怎么实现菜单分组呢？

在menuItemRender里面尝试了遍历好像不太行，求指教

### 🚑 就是item1分组的这种效果

![image](https://user-images.githubusercontent.com/38902744/68067957-d3f66d00-fd89-11e9-86ca-cc0d2af8f073.png)

**Comment by huntdream** [comment]
路由分级就好了

**Comment by liujiayii** [comment]
> 路由分级就好了

有demo吗？研究一下午了

**Comment by huntdream** [comment]
菜单是拿的路由数据转换的，会保持路由的层级结构
你只要给你的的路由配置那里往下加几层子路由试试就知道了
item1和item2是平级的，然后各自下面有两个option的子路由
可以参考一下umi路由这块的文档

**Comment by liujiayii** [comment]
> 菜单是拿的路由数据转换的，会保持路由的层级结构
> 你只要给你的的路由配置那里往下加几层子路由试试就知道了
> item1和item2是平级的，然后各自下面有两个option的子路由
> 可以参考一下umi路由这块的文档

没看明白怎么配置，官网也找着没有这方面的例子啊 =.=

**Comment by huntdream** [comment]
```
const routes = [
  {
    name: 'Navigation one',
    routes: [
      {
        name: 'item1',
        routes: [
          {
            name: 'option1',
          },
          {
            name: 'option2',
          },
        ],
      },
      {
        name: 'item2',
        routes: [
          {
            name: 'option1',
          },
          {
            name: 'option2',
          },
        ],
      },
    ],
  },
]

```
大概是这样的形式吧，你试试看

**Comment by yuan-ze** [comment]
这个问题看着还是没有解决呀。楼主问的是菜单分组，要的是能显示分组标题的效果，不是分级
