### ISSUE TITLE
🧐[问题]请问如何修改ant-design-pro 类选择器的通用前缀

### ISSUE THREAD

**Issue by TroTreboRn** [ant-design/ant-design-pro#5544]
### 🧐 问题描述
请问如何修改ant-design-pro 类选择器的通用前缀

想要一个全局替换，请问如何配置
e.g. 
.ant-layout  ===>  .expected-layout

**Comment by chenshuai2144** [comment]
现在还不可以，layout 支持了一个残废的。
你有兴趣帮忙搞一下吗？
仓库在这里 https://github.com/ant-design/ant-design-pro-layout/

**Comment by TroTreboRn** [comment]
可能是会错意了，我的本意是想自定义css中class的名，
e.g. 
less中的.toolbar编译后 ===> .antd-pro-pages-components-footer-toolbar-index-toolbar
**.antd-pro-pages-components-footer-toolbar-index** 这一段应该是根据src路径添加上的，我想要知道这段相关的代码或配置在哪呢？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L148

是这个吧

**Comment by TroTreboRn** [comment]
是的 thx
