### ISSUE TITLE
🧐[问题]  登录功能调用了后台接口，发现登录成功后，页面显示了403，浏览器显示的路由是正确

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design-pro#5545]
### 🧐 问题描述

登录页面改了一点逻辑，调用了后台接口，不知道哪里改错了还是改多了，发现登录后有问题，登录成功后页面显示403，但url页面路由地址是正确的

### 💻 示例代码
page/Authorized.js
登录成功后，这个发现isLogin是true的，浏览器url显示了正确路径不知为什么还变成了403显示
``<Authorized
      authority={getRouteAuthority(location.pathname, routerData)}
      noMatch={isLogin ? <Exception403 /> : <Redirect to="/user/login" />}
    >
      {children}
    </Authorized>

**Comment by dongkeng001** [comment]
我知道啥原因了，登录名要push到authority数组里面才可以的

**Comment by chenshuai2144** [comment]
可以的。
