### ISSUE TITLE
pro 2.0怎么解决在topNavHeader情况下，改变屏幕尺寸也能自动增减菜单个数

### ISSUE THREAD

**Issue by kaikaiRRSE** [ant-design/ant-design-pro#5546]
在TopNavHeader组件中已经添加以下代码：
static getDerivedStateFromProps(props) {
    return {
      maxWidth: (props.contentWidth === 'Fixed' ? 1200 : window.innerWidth) - 280 - 165 - 40,
    };
  }
maxWideth会根据屏幕大小，但是，屏幕尺寸改变时候，并不会重新渲染，官方pro2.0也是一样的。4.0的版本已经解决这个问题，但是2.0可以怎么去解决这个问题吗？

**Comment by chenshuai2144** [comment]
你把你的layout 用 https://github.com/ant-design/ant-design-pro-layout/ 替换就可以了吧

**Comment by kaikaiRRSE** [comment]
> 你把你的layout 用 https://github.com/ant-design/ant-design-pro-layout/ 替换就可以了吧
谢谢，我已经解决了，是因为2.0版本中在header.js中引入了connect,这个会自动执行shouldComponentUpdate这个类似的操作，当为屏幕尺寸改变的，没有传入新的props就会当成浅比较。而不会渲染，把当前的页面connect添加配置pure:false就行了。但是这个会造成重复渲染，稍微影响一点性能。4.0没有这个问题是因为header.js没有引入connect
