### ISSUE TITLE
🧐[问题] 从 v1 升级到 v2 之后，生产环境下 routes redirect 会引发死循环

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#5548]
### 🧐 问题描述

从 v1 升级到 v2 之后，涉及到 redirect 部分，开发环境正常，生产环境会死循环。

### 💻 示例代码

```
module.exports = [
  {
    path: '/',
    component: '../layouts/BasicLayout',
    routes: [
      { path: '/', redirect: '/monitor' },
      {
        path: '/monitor',
        component: './Monitor/Monitor',
        routes: [
          { path: '/monitor', redirect: '/monitor/dashboard' },
          { path: '/monitor/dashboard', component: './Monitor/Dashboard' },
        ],
      },
    ],
  },
];
```

`Monitor` 中也包含一层路由，这种情况下，生产部署会一直死循环。从 `/monitor` 到  `/monitor/Dashboard` 来回切，但是开发环境下是正常的。

是配置错误吗？还是说不能这么用？

**Comment by zhangjie2012** [comment]
升级之前都是通过 `Switch`中添加 `Redirect` 来实现的，升级之后不允许使用 `Switch` 只能用`this.props.children` 来代替。

**Comment by chenshuai2144** [comment]
试着关掉这个呢
https://umijs.org/zh/config/#disableredirecthoist

**Comment by zhangjie2012** [comment]
> 试着关掉这个呢
> https://umijs.org/zh/config/#disableredirecthoist

没用，之前试过。似乎是因为连续两个 `redirect` 导致了死循环：

```
 { path: '/', redirect: '/monitor' }
```

改成

```
 { path: '/', redirect: '/monitor/dashboard' }
```

就可以了，具体原因我还没搞清楚

**Comment by chenshuai2144** [comment]
去umi 提一个吧。这应该是个问题
