### ISSUE TITLE
🐛[BUG] Found 2 elements with non-unique id

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5549]
https://github.com/ant-design/ant-design-pro/issues/3854

我也发现了这个问题，我有一个form组件和index组件，都包含username字段，提示我如下警告，我别的页面和这个一样，不过叫name，且不报错，我以为是create.form原因，于是打印props.form,发现并不一样，所以现在很迷
![image](https://user-images.githubusercontent.com/30397655/68129133-00f67b80-ff54-11e9-8ca4-b11eec037736.png)

**Comment by chenshuai2144** [comment]
来个可重现的demo， 没听懂你在说什么

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/68135099-1f617480-ff5e-11e9-9091-14247ad969a3.png)
最后加了个name解决了问题，可能和rc-form有关系吧

**Comment by gaspire** [comment]
表格的搜索框和 新建表单，有同样的字段名 会出现上面的警告。有别的方式解决吗
