### ISSUE TITLE
🧐[问题]使用externals 提取依赖，通过cdn引入，很多依赖文件报错？？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#5552]
### 🧐 问题描述
使用externals提取依赖，引入的react、react-dom、antd、moment、jquery 均报错，请问该如何正确配置外部依赖引入？

### 💻 示例代码
![20191105170000](https://user-images.githubusercontent.com/16549630/68193922-0359e380-ffef-11e9-8271-379b1908cb0b.jpg)
![20191105171058](https://user-images.githubusercontent.com/16549630/68194110-5df33f80-ffef-11e9-8694-672317ab0a7f.jpg)

### 🚑 其他信息
antd pro版本：2.1.1
umi版本：2.6.17
react版本：16.8.1
react-dom版本：16.8.1
jquery版本：3.4.1
moment版本：2.24.0

**Comment by chenshuai2144** [comment]
要把 react 放到系列放到最前面，它是最基础的依赖
