### ISSUE TITLE
🧐umi block list 404

### ISSUE THREAD

**Issue by QiangGuZi** [ant-design/ant-design-pro#5554]
### 🧐 问题描述

umi block list 命令返回404

umi: 2.11.1

### 💻 示例代码

$ umi block list
⠏ 🚣  fetch block list✖  error     HTTPError: Response code 404 (Not Found) 
    at EventEmitter.<anonymous> (/Users/tq/.config/yarn/global/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
⠏ 🚣  fetch block list

**Comment by QiangGuZi** [comment]
<img width="830" alt="umiBlockList404" src="https://user-images.githubusercontent.com/42662849/68227447-ada52b80-002e-11ea-8f34-af63bc05de81.png">

**Comment by chenshuai2144** [comment]
现在可以先使用 umi ui ，block list 会找时间下线。

**Comment by QiangGuZi** [comment]
@chenshuai2144 
使用umi ui给ant-design-pro添加区块
![image](https://user-images.githubusercontent.com/42662849/68575363-dbfb8e80-04a6-11ea-9fa6-3cbdc7760067.png)
ant-design-pro pages目录默认情况（TableBasic目录我自己复制过去的）
![image](https://user-images.githubusercontent.com/42662849/68575375-e74eba00-04a6-11ea-855f-530b4cca7148.png)

这种情况我该如何处理？我需要做哪些格外配置？

**Comment by QiangGuZi** [comment]
@chenshuai2144 
会用了。。
陈帅下午好！打扰了！

**Comment by yeluoqiuzhi** [comment]
umi ui不会自动转js啊，好失败

**Comment by sunsmeil** [comment]
umi ui 可以设计添加自己的区块吗
