### ISSUE TITLE
🧐Account Settings tabs don't change route on V4

### ISSUE THREAD

**Issue by nextglabs** [ant-design/ant-design-pro#5555]
### 🧐 Problem Description

On the preview website (https://preview.pro.ant.design/account/settings/base), when clicking on different tabs (ie: notifications, binding, security), the route changes accordingly (ie "/settings/notification", "/settings/binding", "/settings/security"). However, when I download the `Account Settings` umi block, the routing doesn't work and I'm not sure how to implement this without making huge changes in the code.

### 🚑 Other information

I have looked everywhere to see how the preview website worked, the `config.ts` file doesn't show a sample route for this block (not even on the `all-blocks` branch). 

Any ideas where I can find the **full** "ant design preview" source code?

**Comment by chenshuai2144** [comment]
Because he becomes a block, you can save it in the query.

```
router.replace({
  search: stringify({
    redirect: window.location.href
  })
});
```

**Comment by nextglabs** [comment]
Thanks @chenshuai2144 for your answer. However, the actual V4 preview version doesn't save that in the query.
Could you please let me know where I can find the full "v4 preview" source code (including all blocks)?
