### ISSUE TITLE
🐛[Ant Design Pro 预览页面一直都打不开 BUG]

### ISSUE THREAD

**Issue by qinyuhua** [ant-design/ant-design-pro#5557]
Ant Design Pro 预览页面一直都打不开，没有人提吗？
https://preview.pro.ant.design/

**Comment by chenshuai2144** [comment]
打开控制台看卡是什么加载不出来，我们切换了cloudflare 延时只有 600 多了

**Comment by qinyuhua** [comment]
> 打开控制台看卡是什么加载不出来，我们切换了cloudflare 延时只有 600 多了

一直在加载中，也没有什么报错，问了小伙伴们，也都打不开，window、MAC都有，Chrome浏览器

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/68272180-d1ec2100-009d-11ea-8ec4-f1f6d32a6e11.png)

**Comment by qinyuhua** [comment]
> 打开控制台看卡是什么加载不出来，我们切换了cloudflare 延时只有 600 多了

好长时间了，

> 节点速度还是很给力的
> ![image](https://user-images.githubusercontent.com/8186664/68272180-d1ec2100-009d-11ea-8ec4-f1f6d32a6e11.png)

https://github.com/ant-design/ant-design-pro/issues/5557#issuecomment-550158307

**Comment by qinyuhua** [comment]
> 节点速度还是很给力的
> ![image](https://user-images.githubusercontent.com/8186664/68272180-d1ec2100-009d-11ea-8ec4-f1f6d32a6e11.png)

![image](https://user-images.githubusercontent.com/28893646/68272303-34452180-009e-11ea-86a3-6be164380346.png)

**Comment by chenshuai2144** [comment]
你 network 中看看在加载什么呢。需要先刷新一喜

**Comment by qinyuhua** [comment]
> 你 network 中看看在加载什么呢。需要先刷新一下

![image](https://user-images.githubusercontent.com/28893646/68272631-3bb8fa80-009f-11ea-9525-019b599d47ec.png)

**Comment by qinyuhua** [comment]
> 你 network 中看看在加载什么呢。需要先刷新一下

![image](https://user-images.githubusercontent.com/28893646/68272661-51c6bb00-009f-11ea-8b6a-597d55d491e8.png)

**Comment by chenshuai2144** [comment]
清一下缓存？ disk cache 不会加载一分多钟的 磁盘缓存了错误的版本吧

**Comment by qinyuhua** [comment]
> 清一下缓存？ disk cache 不会加载一分多钟的 磁盘缓存了错误的版本吧

都试过，没有用，换浏览器、http、https 等，都用过，但是现在都没有用

**Comment by maxmeng93** [comment]
网站无法打开
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antDpro%E7%BD%91%E7%AB%99%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80.tgvqcuvu05.png)

**Comment by js571** [comment]
![image](https://user-images.githubusercontent.com/16421433/68276954-19c47580-00a9-11ea-9b5f-0d64e996a223.png)

**Comment by wangyong315** [comment]
https://prosite.z23.web.core.windows.net/dashboard/analysis
可以看这个地址

**Comment by chenshuai2144** [comment]
现在是否已经恢复了

**Comment by maxmeng93** [comment]
已经可以访问了
