### ISSUE TITLE
大家有没有觉着antd-Pro封装的太重了吗？

### ISSUE THREAD

**Issue by zhangguanpeng** [ant-design/ant-design-pro#556]
里面集成了太多太多的技术点，对程序员的能力要求是很高的。

**Comment by WhatAKitty** [comment]
额，还好吧，都是react生态圈必须学习的一些点；其他也只是一些插件集合，不知道你说的技术点还体现在哪里？

**Comment by chenshuai2144** [comment]
我们的目标就是减少对程序员的素质要求
现在已经很少了
r最复杂的redux你可以选择性使用。
别的都不是难点吧

**Comment by WhatAKitty** [comment]
我是觉得都不难，redux也不难，相对reflux来说已经很简单了。

**Comment by chenshuai2144** [comment]
redux 已经很麻烦了  一堆范式...
你是被虐的多惨. 试试rx.js 和mobx  小项目很给力

**Comment by WhatAKitty** [comment]
不喜欢mobx这种双向绑定，redux真的很简单了。不知道你有没有用过开始的reflux或者flux，那才叫吐血。

**Comment by chenshuai2144** [comment]
reflux用过.. 后来就换成rx.js

**Comment by chenshuai2144** [comment]
redux这些的 像java似的 把一个小项目写成大项目了

**Comment by WhatAKitty** [comment]
rx.js没尝试过，在用了reflux之后，才使用了redux。感觉难度上就降了一个档次。

> redux这些的 像java似的 把一个小项目写成大项目了

* 没把，redux用好后，很简单的
* java哪里有这么不堪，我就是做java的

**Comment by chenshuai2144** [comment]
我也是写java得....
你看看xml写的 spring boot出来之后才改变了...

redux入门太难了........

**Comment by WhatAKitty** [comment]
额，没啥感觉，可能先写了reflux之后的缘故吧，了解运作机理就差不多了。

另外，spring boot之前你可以用注解啊，也可以做到零配置的概念。或者干脆抛弃spring全家桶。

最后，貌似跑偏了，人家问的是antd-pro的封装是否过于沉重。

**Comment by chenshuai2144** [comment]
讨论了半天就是已经很简单了

**Comment by WhatAKitty** [comment]
嗯，close掉。

**Comment by tuoxiansp** [comment]
google 搜索 ‘antd pro build slow’ 进来的。😂

用了一段时间，认为确实太重了。很难同意上面说的减少对程序员素质要求的观点。
先说说问什么使用 antd pro。
antd pro 集成了大量的 layout 模板，有大量美观的样例页面可以参考。
出于不需要设计师等的参与，程序员自己就可以快速开发出较美观的中台的考虑，选择了 antd pro。
这里的点主要在“快”和“省人力资源”上。
但是 antd pro 作为框架来使用，引入了非常多需要额外学习的东西。
随便列几个：dva,saga。
在中台系统开发的早期，追求快速高产出，交互不会比 hello world 复杂多少，Redux 真不一定用得上，即使用上了，也不一定得想方设法解决副作用。
然后默认的 router 的封装了 menu 组件以及内容页面的组件加载逻辑，不清楚这套逻辑就动手开发，会非常艰难。
总之，要使用 antd pro 付出的学习成本太高了。

**Comment by WhatAKitty** [comment]
@tuoxiansp 学多点也有好处嘛，哈哈。

**Comment by my101du** [comment]
哈哈，我也是 google “antd pro Compiled slow” 进来这个 issue 的。使用原来的 create-react-app 传感的项目再 npm install antd，npm start 非常快就出现了界面。
而这个 antd pro 的 npm start 简直像在思考人生。。。

**Comment by tiakia** [comment]
antd-pro 如果直接使用的话是很简单的看着文档走下来就行，如果想弄懂组件功能的实现的话就需要一定的积累了，这个架构值得我们学习

**Comment by joenahm** [comment]
用了一段时间的ant design pro， 最大的感受是，一致性非常高，确实如果用的熟练了开发起来会十分顺畅。但是确实不适合折腾和魔改。

**Comment by gitshan** [comment]
> google 搜索 ‘antd pro build slow’ 进来的。😂
> 
> 用了一段时间，认为确实太重了。很难同意上面说的减少对程序员素质要求的观点。
> 先说说问什么使用 antd pro。
> antd pro 集成了大量的 layout 模板，有大量美观的样例页面可以参考。
> 出于不需要设计师等的参与，程序员自己就可以快速开发出较美观的中台的考虑，选择了 antd pro。
> 这里的点主要在“快”和“省人力资源”上。
> 但是 antd pro 作为框架来使用，引入了非常多需要额外学习的东西。
> 随便列几个：dva,saga。
> 在中台系统开发的早期，追求快速高产出，交互不会比 hello world 复杂多少，Redux 真不一定用得上，即使用上了，也不一定得想方设法解决副作用。
> 然后默认的 router 的封装了 menu 组件以及内容页面的组件加载逻辑，不清楚这套逻辑就动手开发，会非常艰难。
> 总之，要使用 antd pro 付出的学习成本太高了。

非常同意，感统深受。本来是想节约时间用下layout，结果发现要花更多的时间学习umi、dva等等东西。

**Comment by wulinjie122** [comment]
我也觉得太重了，看完了TypeScript，又开始学习UMI.js，umi官方文档写的太简单了，很多深入的东西根本看不懂，而且umi又参考react-router。总之想快速开发，几乎不可能了。

**Comment by Mayazure** [comment]
同感...就是想快速用一下layout。结果脚手架搭出来的项目内容太多了...好多都不需要，于是退而求其次，单纯的用umi+layout插件。结果配置了大半天愣是跑不起来... 感觉自己不适合搞前端😂

**Comment by chensir1985** [comment]
按照文档根本搞不起来，崩溃

**Comment by fmpfmp** [comment]
看到大家都这么说，我就放心了。。。。。

不仅是pro，包括各种vue，ng， react 。。。。

回到根源，回到原始的 div+css+js，多么简洁多么美好。。。

**Comment by 1161853339** [comment]
前几天看到有人吐槽过，以前写个页面一个前端兼职就行，钱少活少，现在各种框架都需要专业前端，钱多活不少，前端同志都是用实力保住饭碗并提高自己工资，哈哈

**Comment by OlyLis1005** [comment]
> 不喜欢mobx这种双向绑定，redux真的很简单了。不知道你有没有用过开始的reflux或者flux，那才叫吐血。

不算双绑吧，也是通过action更新，不过用的是观察者订阅者模式

**Comment by OlyLis1005** [comment]
> rx.js没尝试过，在用了reflux之后，才使用了redux。感觉难度上就降了一个档次。
> 
> > redux这些的 像java似的 把一个小项目写成大项目了
> 
> * 没把，redux用好后，很简单的
> * java哪里有这么不堪，我就是做java的

我用的mobx，现在学redux一头雾水

**Comment by mote0302** [comment]
看到大家都这样就放心了，从vue的d2 admin转过来  antd pro里面学react 然后发现是用的umi 然后发现里面还有dva （啥啥啥 都写的是啥） 不带玩套娃的  而且官方文档写的巨简单  深入学习需要很大精力

**Comment by javaLuo** [comment]
太多东西了，我只不过想做个后台管理系统而已啊。。。

**Comment by pxim** [comment]
总体来讲，还是挺好的，我还想antdp多提供一些功能，这样用起来，会省很多功夫；然后可以根据经常提的 功能issue，多封装一些常见功能问题的配置；只是入门确实需要一点时间去研究其约束和机制，但是这也没办法；任何新的东西都需要了解其约定和规则的。除非只是一个空白模板，

**Comment by putao520** [comment]
我就想简单快速写个后台而已啊，搞这么复杂！

**Comment by jhshengxy** [comment]
我也是想简单的搞个后台！两天了！两天了！我搞了两天都没有把脚手架搭起来！
后端程序猿果然不适合搞前端！
