### ISSUE TITLE
代码出错,修改后,页面一直白屏转圈不会恢复

### ISSUE THREAD

**Issue by lqf9655** [ant-design/ant-design-pro#5562]
### 🧐 问题描述

代码写错 出现bug页面后  编辑器里调整正确后 页面不会恢复 一直白屏,无法恢复 只能关闭后 重新打开

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/46081576/68288772-fbb63f80-00bf-11ea-96b8-776603d8aef9.png)

**Comment by shaohuatsou** [comment]
看样子像是360的浏览器啊

**Comment by xiaohuoni** [comment]
怎么看出是360浏览器？

**Comment by shaohuatsou** [comment]
> 怎么看出是360浏览器？

你看右上角的功能按钮线条和配色就是360的风格。

**Comment by chenshuai2144** [comment]
360 浏览器就是 ie 了吧，切换成 chrome 内核试试？
