### ISSUE TITLE
Form表单为受控组件时，不能出现错误提醒🧐[问题]

### ISSUE THREAD

**Issue by weiTimes** [ant-design/ant-design-pro#5563]
### 💻 示例代码
这是mapPropsToFields中关键代码
![image](https://user-images.githubusercontent.com/21688593/68288481-76328f80-00bf-11ea-9cfd-86ec325560ba.png)
这是配置了rule的表单项
![image](https://user-images.githubusercontent.com/21688593/68288546-8fd3d700-00bf-11ea-9169-75bd22fb6468.png)
原先不受控的时候是可以正常校验，受控了没有错误提醒，不过在点击submit按钮的时候控制台有打印相应的errors
![image](https://user-images.githubusercontent.com/21688593/68288738-ee995080-00bf-11ea-8883-2c77d606964d.png)

**Comment by weiTimes** [comment]
![image](https://user-images.githubusercontent.com/21688593/68289269-c9f1a880-00c0-11ea-84f2-51b7b1093705.png)

**Comment by weiTimes** [comment]
![image](https://user-images.githubusercontent.com/21688593/68289339-e55cb380-00c0-11ea-9fb7-a6aa3efa1263.png)
这是具体的错误信息

**Comment by chenshuai2144** [comment]
受控组件需要自己构造 error message，你的message 好像构建失败了。
来个重现地址吧
