### ISSUE TITLE
🧐[问题] Unwanted style injection in production

### ISSUE THREAD

**Issue by arherzf8er** [ant-design/ant-design-pro#5564]
### 🧐 问题描述
Why does Table component behaves differently locally and in production?

### 💻 示例代码

```
<Table
  columns={cols}
  className={styles.skills}
  dataSource={skills}
  pagination={false}
/>
```

### localhost
![image](https://user-images.githubusercontent.com/29209372/68350434-f3362700-0108-11ea-95aa-3657513c8440.png)
### Production:
![image](https://user-images.githubusercontent.com/29209372/68350375-c2ee8880-0108-11ea-83e4-470b4c5ea59b.png)
```
.ant-table-row-cell-break-word {
  word-wrap: break-word;
  word-break: break-word;
}
```

**Comment by chenshuai2144** [comment]
you can update your deps？
