### ISSUE TITLE
👑 [需求] 今天去看了下阿里的飞冰，下载了他们一个模板，给pro提一些建议

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5566]
飞冰config目录下有有一个路由配置和一个菜单配置文件
![image](https://user-images.githubusercontent.com/30397655/68366832-332ff500-016f-11ea-8074-884f58b5cf79.png)
路由水平配置
![image](https://user-images.githubusercontent.com/30397655/68366841-39be6c80-016f-11ea-809a-8e245a9ba8c4.png)
菜单分组配置
![image](https://user-images.githubusercontent.com/30397655/68366853-4347d480-016f-11ea-8517-27759a2acf02.png)

编译运行，完美，希望pro可以采取这种配置方式，结合后端真的是爽

**Comment by leshalv** [comment]
更重要的是，路由不是一个目录下，也没有问题，而pro确不行，这算是bug还是不完善？

**Comment by leshalv** [comment]
https://github.com/ant-design/ant-design-pro/issues/5376

**Comment by afc163** [comment]
感觉可以改造一波，更灵活一点。

**Comment by leshalv** [comment]
对的，我看社区大部分人都菜单这块提出的问题挺多，目前确实真的不灵活
![image](https://user-images.githubusercontent.com/30397655/68367867-a175b700-0171-11ea-8bfc-7d357b80adc9.png)
大佬可以参考下飞冰这块，做的确实不错，但是我更喜欢antd

**Comment by chenshuai2144** [comment]
路由可以做到 page 中这个点子感觉不错。

**Comment by leshalv** [comment]
菜单做的也不错

**Comment by effapp** [comment]
菜单单独配置，这个pro可以借鉴一下

**Comment by fanhualei** [comment]
分开配置，代码会更清爽一点。菜单与路由分开，要考虑权限的问题。应该把权限当到路由中。

**Comment by leshalv** [comment]
https://github.com/ant-design/ant-design-pro/issues/5579

**Comment by lay-coder** [comment]
你们说的像没有router-view帮忙的vue的路由配置- -

**Comment by k983551019** [comment]
就是不知道啥时候能出来
