### ISSUE TITLE
🐛[BUG]Pie组件金额为小数时显示为0（金额不显示小数点）

### ISSUE THREAD

**Issue by zengminghua** [ant-design/ant-design-pro#5567]
### 🐛 bug 描述
ant design pro在使用Pie组件时，金额不显示小数点，实际金额是有两位小数的。有使用Yuan组件。

结果显示为0:
![结果1](https://user-images.githubusercontent.com/16233356/68374882-b3ab2180-0180-11ea-91ba-627df4a2e910.png)

后台返回数据（有0.01）：
![结果2](https://user-images.githubusercontent.com/16233356/68374938-cde4ff80-0180-11ea-937a-7c6c4843f3d1.png)

### 🏞 期望结果
正确显示小数信息

### © 版本信息

- Ant Design Pro 版本：2.2.1
- umi 版本：2.4.4
- 浏览器环境：Chrome 78
- 开发环境：mac OS

### 🚑 其他信息
相关issue：https://github.com/ant-design/ant-design-pro/issues/3893

**Comment by chenshuai2144** [comment]
组件已经不会在更新了，推荐你直接下载相应的区块进行改动。

https://gitee.com/ant-design/pro-blocks/blob/master/DashboardAnalysis/src/components/Charts/Pie/index.tsx
