### ISSUE TITLE
部署到相对路径

### ISSUE THREAD

**Issue by AimLuo** [ant-design/ant-design-pro#5568]
### 场景
nginx配置以html目录为web项目根目录，所有前端页面都会放在这个目录中。

### 文档提供了部署到非根目录的方法：
```
export default {
  // ... some config
  base: "/admin/",
  publicPath: "/admin/",
};
```
### 问题
但是对于我来说，以上的` "/admin/"`是不确定的。所以想用相对路径，可以将它配置为`./`吗？结合`browserHistory`会不会用冲突

**Comment by chenshuai2144** [comment]
会的，如果不确定建议用 hash
