### ISSUE TITLE
动态角色怎么实现

### ISSUE THREAD

**Issue by AimLuo** [ant-design/ant-design-pro#5569]
### 🧐 问题描述

角色对应的菜单是变化的：比如a角色今日只有/home访问权限，但是明天又增加了/admi访问权限。
而且也会实时增加其他角色。
官网文档，只能在编译时写死角色，以及角色权限。
![image](https://user-images.githubusercontent.com/21124342/68455239-d77c6f00-0235-11ea-98e9-e4a135c30495.png)

**Comment by chenshuai2144** [comment]
看一下这个方法

https://github.com/ant-design/ant-design-pro/blob/1e8238cdb9b39cd2b6d6a51df87aec0d81ed0864/src/utils/authority.ts#L27

**Comment by ZuhuaLiu** [comment]
角色也是权限的意思，你可以把角色当成权限节点，这个地方不用admin，用具体的权限节点。

**Comment by AimLuo** [comment]
懂了，我去研究研究。

**Comment by sunft1996** [comment]
你可以让菜单从后端返回。[动态多角色登录可以参考这里](https://github.com/sunft1996/ant-back)，页面和页面下的子权限都可以数据库动态配置。
