### ISSUE TITLE
使用动态路由注册model，redux-persist 无法恢复数据

### ISSUE THREAD

**Issue by blackkey520** [ant-design/ant-design-pro#557]
使用动态路由注册model，发现redux-persist persist/REHYDRATE action 触发了但是并没有恢复数据。把需要恢复状态的model在index文件中注册，刷新之后才可以恢复数据。

**Comment by afc163** [comment]
Maybe it should be a dva-related problem?

**Comment by ddcat1115** [comment]
trace https://github.com/dvajs/dva/issues?utf8=%E2%9C%93&q=is%3Aissue+redux-persist
