### ISSUE TITLE
🧐[问题]大佬们，监听浏览器返回，你们是咋搞的啊，，为啥我的代码有问题（新手）

### ISSUE THREAD

**Issue by WuZheXiao** [ant-design/ant-design-pro#5570]
### 🧐 问题描述

我的代码阻止是阻止了返回，但是页面第二次在点详情再点返回，，弹窗会执行好几遍，，，

### 💻 示例代码

  componentDidMount() {
    window.addEventListener('popstate', this.beforeunload);
  }
  // componentWillUnmount() {
  //   // 销毁拦截判断是否离开当前页面
  //   window.removeEventListener('popstate', this.beforeunload);
  // }
  beforeunload = e => {
    // e.preventDefault();
    // e.stopPropagation();
    ConfirmModal({
      content: '您填写的信息尚未提交保存，是否继续返回?',
      onOk() {
        router.replace('/coop-school');
      },
      onCancel() {},
    });
  };

**Comment by AimLuo** [comment]
addEventListener监听的事件没被清除，在组件销毁的时候清除事件。

**Comment by WuZheXiao** [comment]
我上面注释的代码，，是清除的吧？也不是很确定，，但是没起作用，，我的提示都没出来。。

**Comment by WuZheXiao** [comment]
好像可以了，，但是没有拦截返回，提示在下一个页面出来了，有点尴尬

**Comment by WuZheXiao** [comment]
讲下解决方法吧。。最后我是用Prompt组件，来实现页面未保存提示的功能

**Comment by chenshuai2144** [comment]
window.Prompt 才能阻止js的线程 ，别的是无法阻止的。 所以代码还会继续运行
