### ISSUE TITLE
Tree with recursive TreeNode method

### ISSUE THREAD

**Issue by mbarmettler** [ant-design/ant-design-pro#5571]
we need to load a hierarchical Node structure to the tree component.

i see all the nodes in the console message - but i always get an empty node with "---" in its title - even if i set a static string as title.

i expect that i get some properties back and got written into the title - but it seems not to work and all i get back are these literals "---".

here is my code:
`function renderTreeNodes(props) {
        // console.log(props.length)
        console.log(props)

        return (
            props.id == 1 ?
                <TreeNode key={props.id} title={<div> <Tag>{props.id}</Tag> {props.name}({props.type.name}) <Tag> <Icon type="info-circle" /> {props.description}</Tag></div>}>
                    {props.children ? renderTreeNodes(props.children) : <div></div>}
                </TreeNode>
                :
                props.children ?
                    props.children.map(ch =>
                        <TreeNode key={ch.id} title={<div> <Tag>{ch.id}</Tag> {ch.name}({ch.type.name}) <Tag> <Icon type="info-circle" /> {ch.description}</Tag></div>}>
                            {ch.children ? renderTreeNodes(ch.children) : <div></div>}
                        </TreeNode>
                    ) : <div></div>
        )
    }

    return (
        <PageHeaderWrapper content={formatMessage({ id: 'ctrl.category.tree.head.title' })} >
            <Card>
                {loading ? <Spin /> :
                    <Tree treeData={renderTreeNodes(data.value[0])}>
                    </Tree>
                }
            </Card>
        </PageHeaderWrapper>
    );`

**Comment by chenshuai2144** [comment]
give some demo？
like codebox

**Comment by mbarmettler** [comment]
https://codesandbox.io/s/infallible-mendel-62pmx

**Comment by chenshuai2144** [comment]
The tree caches the rendering results to speed up rendering. If you want to pursue higher performance, you can use [rc-tree](https://github.com/react-component/tree/releases/tag/v3.0.0-alpha.37), the performance is very good, will be in the next big version of ant use
