### ISSUE TITLE
🧐[问题] 官方 StandardTable，选中第一页第一项，以后每页默认选中第一个（数据后台获取） 

### ISSUE THREAD

**Issue by lemoncy** [ant-design/ant-design-pro#5572]
### 🧐 问题描述
V2 版本查询表格分页选中，DEMO版本读取mock数据没问题。
从后台获取，分页下一页始终选取第一个，请问是bug么，还是要如何实现。
哪位大神有经验，麻烦告知下，谢谢啦。

### 💻 示例代码
页面：
 `import React, { PureComponent, Fragment } from 'react';
import { connect } from 'dva';
import {
  Row,
  Col,
  Card,
  Form,
  Input,
  Select,
  Icon,
  Button,
  Dropdown,
  Menu,
  InputNumber,
  DatePicker,
  Modal,
  message,
  Badge,
  Divider,
  Steps,
  Radio,
} from 'antd';
import StandardTable from '@/components/StandardTable';
import PageHeaderWrapper from '@/components/PageHeaderWrapper';

import styles from './ResPermsPg.less';

const getValue = obj =>
  Object.keys(obj)
    .map(key => obj[key])
    .join(',');

/* eslint react/no-multi-comp:0 */
@connect(({ resPermsMd, loading }) => ({
  resPermsMd,
  loading: loading.models.resPermsMd,
}))

@Form.create()
class ResPermsList extends PureComponent{
  state = {
    modalVisible: false,
    updateModalVisible: false,
    expandForm: false,
    selectedRows: [],
    formValues: {},
    stepFormValues: {},
  };

  resColumns =[
    {
      title: '资源标识',
      dataIndex: 'resIdentify',
    },
    {
      title: '资源名称',
      dataIndex: 'resName',
    },
    {
      title: '资源类型',
      dataIndex: 'resType',
    },
    {
      title: '授权',
      dataIndex: 'perms',
    },
    {
      title: '路由',
      dataIndex: 'path',
    },
    {
      title: '序号',
      dataIndex: 'orderNum',
    },
    {
      title: '修改时间',
      dataIndex: 'modifyTime',
    },
  ];

  componentDidMount() {
    const params = {filterJson:"[,{column: \"resType\",type: \"asc\", value: \"asc\"}]"};
    const { dispatch } = this.props;
    dispatch({
      type: 'resPermsMd/fetch',
      payload:params
    });
  }

  handleSelectRows = rows => {
    this.setState({
      selectedRows: rows,
    });
  };

  handleModalVisible = flag => {
    this.setState({
      modalVisible: !!flag,
    });
  };

  handleStandardTableChange = (pagination, filtersArg, sorter) => {
    const { dispatch } = this.props;
    const { formValues,selectedRows} = this.state;

    console.log(selectedRows);

    const filters = Object.keys(filtersArg).reduce((obj, key) => {
      const newObj = { ...obj };
      newObj[key] = getValue(filtersArg[key]);
      return newObj;
    }, {});

    const params = {
      currentPage: pagination.current,
      pageSize: pagination.pageSize,
      ...formValues,
      ...filters,
    };
    if (sorter.field) {
      params.sorter = `${sorter.field}_${sorter.order}`;
    }

    dispatch({
      type: 'resPermsMd/fetch',
      payload: params,
    });
  };

  render(){
    const {
      resPermsMd: { data },
      loading,
    } = this.props;
    const { selectedRows, modalVisible, updateModalVisible, stepFormValues } = this.state;

    return(
      <PageHeaderWrapper title="资源权限">
        <Card bordered={false}>
          <div className={styles.tableList}>
            <div className={styles.tableListOperator}>
              <Button icon="plus" type="primary" onClick={() => this.handleModalVisible(true)}>
                新建
              </Button>
              <span>
                <Button>删除</Button>
                <Button>审核</Button>
              </span>
            </div>
          </div>
          <StandardTable
            selectedRows={selectedRows}
            loading={loading}
            data={data}
            pageSize={10}
            columns={this.resColumns}
            onSelectRow={this.handleSelectRows}
            onChange={this.handleStandardTableChange}
          />
        </Card>
      </PageHeaderWrapper>
    );
  }
}

export default ResPermsList;
`
model ：

`import { queryResPerms  } from '@/services/api';

export default {
  namespace: 'resPermsMd',

  state: {
    data: {
      list: [],
      pagination: {},
    },
  },

  effects: {
    *fetch({ payload }, { call, put }) {
      const response = yield call(queryResPerms, payload);
      yield put({
        type: 'save',
        payload: response.data,
      });
    },
  },

  reducers: {
    save(state, action) {
      return {
        ...state,
        data: action.payload,
      };
    },
  },
};
`

### 🚑 其他信息

官方mock数据：
![image](https://user-images.githubusercontent.com/3096214/68486090-68296e00-027b-11ea-8fde-27bcb55187c6.png)
![image](https://user-images.githubusercontent.com/3096214/68486143-7d9e9800-027b-11ea-9751-bfcb8015467e.png)
从后台获取：
![image](https://user-images.githubusercontent.com/3096214/68486411-fb62a380-027b-11ea-847c-f675ae8b4f19.png)
第二页，后台获取数据候，默认选中第一个，但是打印出state selectedRows 还是第一记录
![image](https://user-images.githubusercontent.com/3096214/68486363-e4bc4c80-027b-11ea-9525-708c1fe9830e.png)

**Comment by huntdream** [comment]
放点代码👀？

**Comment by lemoncy** [comment]
@huntdream 才看到。多谢提示。
看了调用的 StandardTable 就把选中的索引还原。第二页索引是0，就还原每一页的第一个默认选中。

**Comment by lemoncy** [comment]
已经查到问题，key的问题。原始数据顺序需要有key关键字。
