### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#5574]
### 🐛 bug 描述
每次打开页面，BasicLayout组件的render都要执行2次，请问问题出现在什么地方？如何修改？

### 📷 复现步骤
每次打开页面，BasicLayout组件的render都要执行2次，请问问题出现在什么地方？如何修改？

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [win10]

**Comment by yoyo837** [comment]
Duplicated of #5575
