### ISSUE TITLE
pro ant design的菜单什么时候能从路由配置分出来，单独配置，现在太影响业务系统开发了。👑 [需求]

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#5579]
### 🥰 需求描述
pro ant design的菜单什么时候能从路由配置分出来，单独配置，现在太影响业务系统开发了。

### 🧐 解决方案

pro ant design的菜单从路由配置分出来，单独配置

**Comment by leshalv** [comment]
https://github.com/ant-design/ant-design-pro/issues/5566#issuecomment-552896083

**Comment by effapp** [comment]
菜单的问题提了很久了，怎么这么长时间都解决不了吗？

**Comment by yoyo837** [comment]
个人时间安排问题；你可以考虑PR！

**Comment by effapp** [comment]
PR是什么的简写，表示什么意思？
（抱歉，我是新手，请多多包涵）

**Comment by fanhualei** [comment]
菜单还真可以改一下.

现在ant design pro好像人手不足,更新的明显慢了, 估计这个需求不会被采纳.

**Comment by Thyiad** [comment]
> PR是什么的简写，表示什么意思？
> （抱歉，我是新手，请多多包涵）

PR 全称： pull request，你 fork 项目之后修改，然后发一个 pull request，源项目接收到 pull request，认可你的修改，就会合并你的代码。
再不懂，可以去 google 了
（小兄弟，有点惨，居然没人回你，哈哈。。）
