### ISSUE TITLE
构建后umi.js体积太大了👑 [需求]

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#5582]
Ant Design Pro 初始工程编译后 umi.257bbc6b.js 都将近2M了，页面加载缓慢，可不可以拆分？

**Comment by yoyo837** [comment]
主要还是antd的原因, 比如https://github.com/ant-design/ant-design/issues/12011

**Comment by chenshuai2144** [comment]
可以使用  `yarn analyze`  来实现
