### ISSUE TITLE
使用umi block list后报错🧐[问题]

### ISSUE THREAD

**Issue by z1811021** [ant-design/ant-design-pro#5583]
### 🧐 问题描述

我任意添加了一个block然后yarn start后报错

### 💻 示例代码

yarn run v1.15.2
$ umi dev
�🚀 Starting Umi UI using umi@2.11.3.
⛽️ Ready on http://localhost:3000/
  build [==                  ] 10%Starting the development server...

  build [=================== ] 95%Extracted theme color css content length: 313
Build completed in 59.89s

 ERROR  Failed to compile with 2 errors                                                                                                                                                3:13:48 PM
 error 

[tsl] ERROR
      TS18002: The 'files' list in config file 'tsconfig.json' is empty.

 @ ./src/pages/.umi/router.js 78:17-36
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

 error  in ./src/pages/snkrs/index.tsx

Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (C:\Users\XiGong\Documents\My folder\项目\Jorge_Front\node_modules\ts-loader\dist\index.js:19:18)

 @ ./src/pages/.umi/router.js 78:17-36
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

**Comment by xbaos** [comment]
1.在项目根目录创建tsconfig.json文件。
2.在该文件中复制如下代码并保存
{
    "compilerOptions": {
      "outDir": "build/dist",
      "module": "esnext",
      "target": "esnext",
      "lib": ["esnext", "dom"],
      "sourceMap": true,
      "baseUrl": ".",
      "jsx": "react",
      "allowSyntheticDefaultImports": true,
      "moduleResolution": "node",
      "forceConsistentCasingInFileNames": true,
      "noImplicitReturns": true,
      "suppressImplicitAnyIndexErrors": true,
      "noUnusedLocals": true,
      "allowJs": true,
      "experimentalDecorators": true,
      "strict": true,
      "paths": {
        "@/*": ["./src/*"]
      }
    },
    "exclude": [
      "node_modules",
      "build",
      "scripts",
      "acceptance-tests",
      "webpack",
      "jest",
      "src/setupTests.ts",
      "tslint:latest",
      "tslint-config-prettier"
    ]
  }
3.cmd ctrl+c --> yarn --> yarn start
4.solve the problem and see the page is normal
