### ISSUE TITLE
🧐[问题]V4版本中SettingDrawer 无效，是需要在哪里进行单独配置么？

### ISSUE THREAD

**Issue by xs0529** [ant-design/ant-design-pro#5586]
### 🧐 问题描述
无法启用在线切换主题的功能

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/4c36a09fcebc0fcfe1b1b8d15a78f13e7f8b90e1/src/models/setting.ts#L19
看这里

**Comment by xs0529** [comment]
我是按照管网的步骤运行项目的，启动之后没有发现页面上有在线换主题的抽屉按钮（屏幕右边那个蓝色的），所有的代码没有进行过更改，运行环境是dev

**Comment by xs0529** [comment]
> https://github.com/ant-design/ant-design-pro/blob/4c36a09fcebc0fcfe1b1b8d15a78f13e7f8b90e1/src/models/setting.ts#L19
> 
> 
> 看这里

我是按照管网的步骤运行项目的，启动之后没有发现页面上有在线换主题的抽屉按钮（屏幕右边那个蓝色的），所有的代码没有进行过更改，运行环境是dev

**Comment by yoyo837** [comment]
@chenshuai2144 他的意思是初始化的项目没有右边那个 全局主题定制的抽屉按钮飘着

**Comment by m430** [comment]
@chenshuai2144 是指的漂浮在右边的抽屉配置按钮。这个功能挺好的呀，怎么去掉了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout
看这里
