### ISSUE TITLE
🧐[问题] dispatch发起的请求没有数据

### ISSUE THREAD

**Issue by sheepfly** [ant-design/ant-design-pro#5589]
### 🧐 问题描述
在diapatch发起请求后，payload的数据没有和请求一起发出，devtool里面请求没有request payload。

### 💻 示例代码
```typescript
// ...
  // tablelist的index.tsx
  handleStandardTableChange = (
    pagination: Partial<TableListPagination>,
    filtersArg: Record<keyof TableListItem, string[]>,
    sorter: SorterResult<TableListItem>,
  ) => {
    const { dispatch } = this.props;
    const { formValues } = this.state;

    const filters = Object.keys(filtersArg).reduce((obj, key) => {
      const newObj = { ...obj };
      newObj[key] = getValue(filtersArg[key]);
      return newObj;
    }, {});

    const  params: Partial<TableListParams> = {
      currentPage: pagination.current,
      pageSize: pagination.pageSize,
      ...formValues,
      ...filters,
    };
    if (sorter.field) {
      params.sorter = `${sorter.field}_${sorter.order}`;
    }
    dispatch({
      type: 'contract/fetch',
      payload: params,
    });
  };
// ...
```
models
```typescript
   // ...
    *fetch({ payload, callback }, { call, put }) {
      const response = yield call(queryRule, payload);
      yield put({
        type: 'save',
        payload: response,
      });
    },
    // ....
```
service.ts
```typescript
// ...
export async function queryRule(params: TableListParams) {
  return request('/api/contract/query', {
    method: 'GET',
    data: {
      ...params,
    },
  });
}
// ...
```
正常情况下，dispatch请求会将payload中的数据传入models，models call的时候将payload中数据传入service，然后可以在devtools中看到request payload
![image](https://user-images.githubusercontent.com/39870481/68742801-032f9880-062c-11ea-82e3-5317a66a9d43.png)
但是query请求发出后devtools空荡荡的什么都没有
![image](https://user-images.githubusercontent.com/39870481/68742855-222e2a80-062c-11ea-8029-86e40eb815d7.png)
在service里`return`前打印`params`，可以看到结果
![image](https://user-images.githubusercontent.com/39870481/68742977-61f51200-062c-11ea-918b-e853764e82c1.png)
而且同一servie文件下的其他请求都没有问题。
如果在这个dispatch下发起别的请求，比如`contract/add`，devtools里可以看到request payload.
请问这个问题应该怎么解决？

其他信息：
1. 关闭了mock代理，直接代理到后端
2. antd v4

**Comment by chenshuai2144** [comment]
get 请求参数会在url上，你看看是不是放到 url上了

**Comment by huntdream** [comment]
GET 方法参数应该是要放在`params`里面

**Comment by sheepfly** [comment]
刚上线不久就收到回复，将`data`改成`params`果然好了，参数附在url后面，谢谢

**Comment by sheepfly** [comment]
> get 请求参数会在url上，你看看是不是放到 url上了

没有在url里，用huntdream的方法，将`data`改成`params`解决了

**Comment by sheepfly** [comment]
> GET 方法参数应该是要放在`params`里面

刚上线不久就收到回复，将data改成params果然好了，参数附在url后面，谢谢

**Comment by chenshuai2144** [comment]
get 应该用 params. fetch 的特性，一下子没想到
