### ISSUE TITLE
控件问题咨询

### ISSUE THREAD

**Issue by ryan-che** [ant-design/ant-design-pro#559]
现在管理后台用的EASYUI ,想用这个框架取代它，但是像easyui 里面的一些复杂控件如Tree、ComboGrid、ComboTree等 这样的复杂控件官方会提供解决方案吗？

**Comment by WhatAKitty** [comment]
[Ant Design](https://pro.ant.design/components/AvatarList-cn)

可以根据这些组件自由组合。

**Comment by ryan-che** [comment]
脚手架的高级表单里面能不能提供几个复杂控件组合的例子，便于大家上手应用，谢谢。

**Comment by chenshuai2144** [comment]
举个例子

**Comment by ryan-che** [comment]
比如ComboGrid下拉表格，选中一行获取这一行的数据，给其他文本框自动赋值。例如选中商品信息，自动带出价格。

![qq 20180103153602](https://user-images.githubusercontent.com/15942427/34512264-1d81dfba-f09c-11e7-82db-a851c54d140f.png)

**Comment by chenshuai2144** [comment]
可以自己封装控件..

**Comment by ryan-che** [comment]
这个是eayui 官方封装的下拉表格combogrid， 像下拉表格、下拉树等常用控件他们官方都统一封装了。

**Comment by ryan-che** [comment]
树列表、下拉列表、下拉树、多选下拉，表单里面能给提供几个例子吗，现在找不到替代他们的控件

**Comment by chenshuai2144** [comment]
去antd 找一找把. 主要是精力在基础框架部分
