### ISSUE TITLE
npm run fetch:blocks 下载过程中卡死

### ISSUE THREAD

**Issue by longyunrui** [ant-design/ant-design-pro#5590]
### 🧐 问题描述
Win 10 系统，24G 内存，8C16T AMD 处理器，
npm run fetch:blocks 下载过程中卡死，而且是整个终端卡死，只能关闭终端后重新打开，然后项目就无法正常运行，因为上一条命令已经修改了部分文件

请问如何在 `npm run fetch:blocks` 过程中是否可以实时显示安装进度，而不是现在的安装一个就显示完成一个，安装过程中就是无尽的等待，不知道具体发生了什么

### 💻 示例代码

已经尝试过以下解决方案
方法一：
1、下载https://github.com/ant-design/pro-blocks
2、将下载的文件解压拷贝到C:\Users\用户名\.umi\blocks\github.com\ant-design\pro-blocks文件夹下
3、执行npm run fetch:blocks

方法二：
打开 host 文件，OSX 系统位置在/etc/hosts
在文件末尾添加如下内容后保存退出
140.82.113.4    github.com
185.199.108.153 assets-cdn.github.com
185.199.109.153 assets-cdn.github.com
185.199.110.153 assets-cdn.github.com
185.199.111.153 assets-cdn.github.com
151.101.185.194 github.global.ssl.fastly.net
运行命令 sudo dscacheutil -flushcache 清除 DNS 缓存

方法三：
如果速度缓慢，可以尝试升级 umi 版本到最新，并在 config.ts 设置 block.defaultGitUrl 为 'https://gitee.com/ant-design/pro-blocks'。

**Comment by yoyo837** [comment]
GitHub国内本身就不稳定，要流畅使用一般需要挂梯子；就GitHub我觉得百分比肯定对体验更好，但没太大作用；
