### ISSUE TITLE
🧐[问题] 菜单颜色问题。

### ISSUE THREAD

**Issue by bxvs888** [ant-design/ant-design-pro#5593]
### 🧐 问题描述

通过 yarn create umi  创建完成项目，然后通过 yarn fetch:blocks 下载所有的区块后。编译运行都 没有问题，就是在显示页面后菜单的样式错误。样试见图片。

### 🚑 其他信息

 
![image](https://user-images.githubusercontent.com/298322/68818465-02484680-06c0-11ea-8944-2f9a2d71d038.png)

**Comment by bxvs888** [comment]
不下载区块显示没有问题。

**Comment by ZuhuaLiu** [comment]
我的也是，项目突然之间菜单全变成这样了，之前都是好的，应该是改了ant pro layout的代码，求尽快解决。

**Comment by ZuhuaLiu** [comment]
现在的父菜单也能点击

**Comment by katherinewei** [comment]
一样的问题，现在的父菜单也能点击。

**Comment by jdfdcc** [comment]
一样的问题

**Comment by jdfdcc** [comment]
一样的问题,看了一下元素是 Link 里面变成A标签了 求修复

**Comment by xhw0714** [comment]
有解决方法了吗

**Comment by mahailong** [comment]
我把"@ant-design/pro-layout"的版本回退到"4.5.9"就好了

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5603
看这个理
