### ISSUE TITLE
导航栏问题，依赖安装出错

### ISSUE THREAD

**Issue by ZuhuaLiu** [ant-design/ant-design-pro#5594]
### 🧐 问题描述

1.之前下载的项目，突然之间发布不了了，就删除了几个文件，安装依赖出错。重新下载ant-design-pro，发现也装不了依赖。
2.前几个小时可以发布，但是导航栏菜单突然之间都变了，父节点也能点击了，pro-layout的版本还是之前下载的版本，是不是这个版本也进行了更新。

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/40290781/68821688-f06ba100-06c9-11ea-9f8c-1d01be31beab.png)
![image](https://user-images.githubusercontent.com/40290781/68821809-43455880-06ca-11ea-8ebf-0796245a71c0.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5603
看这个
