### ISSUE TITLE
如何默然展开所有的菜单？

### ISSUE THREAD

**Issue by ldwonday** [ant-design/ant-design-pro#5595]
这样子配置为什么就是行，不知道为什么，是不支持吗？

```js
<ProLayout
        menuProps={{
          defaultOpenKeys: ['data-insight', 'moments'],
        }}
...
</ProLayout>
```
data-insight和moments是router的name
['/data-insight', '/moments']配置path也不行

**Comment by ldwonday** [comment]
用openKeys可以展开，但是感觉不应该使用openKeys，而是用defaultOpenKeys

**Comment by chenshuai2144** [comment]
@ldwonday  你需要做成受控模式了。

**Comment by ldwonday** [comment]
@chenshuai2144 谢谢了，受控模式是可以的，昨天试过了，但是我觉得defaultOpenKeys应该要支持的呀！

**Comment by chenshuai2144** [comment]
来 layout 提一个issue
