### ISSUE TITLE
👑 [需求] pipeline 组件

### ISSUE THREAD

**Issue by icecraft** [ant-design/ant-design-pro#5596]
### 🥰 需求描述
* 问题描述：数据处理过程中，不同类型的数据不同的处理过程（某些数据处理过程有公用部分）。希望能在web 页面编辑出数据处理流程 pipeline。类似 gitlab ci 那样的

* 希望大佬们能支持一下？ 或者用大佬们资深的阅历告诉我有那些开源库已经实现了。。。。
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13513537/68829324-8102ab00-06e3-11ea-9e10-6297d62e232c.png)

**Comment by yoyo837** [comment]
这个完全可以自己做

**Comment by chenshuai2144** [comment]
这个我也找过但是没有合适的。
看看 d2 这些的图标绘制库有没有你需要的

**Comment by huntdream** [comment]
xstate，不知道是否满足需求
https://github.com/davidkpiano/xstate

**Comment by chenshuai2144** [comment]
看来暂时不会添加
