### ISSUE TITLE
umi官网文档需要更新了???  scollToTop现在不知道加在哪个位置？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design-pro#5598]
![image](https://user-images.githubusercontent.com/23158766/68832797-dc856680-06ec-11ea-8a23-7d9abc8e0e70.png)

**Comment by chenshuai2144** [comment]
详细说明一下？
你的困惑是什么

**Comment by wo-de-ping-er** [comment]
> 详细说明一下？
> 你的困惑是什么

我这边使用hash路由   页面跳转回记录页面停留位置   我目前采用在组件里面加上scrollTop(0,0)的方式    但是感觉这种处理不好    跳转页面很多就会很麻烦    官网里面scroolTop方式是在layout里面进行配置的   但是现在layout文件已不存在    我在BasicLayout里面设置没有生效   详情可见截图

**Comment by chenshuai2144** [comment]
BasicLayout 中可以使用  hooks

```
 useEffect(() => {
    window.scrollTop(0, 0);
}, [location.pathname]);
```

**Comment by wo-de-ping-er** [comment]
> BasicLayout 中可以使用 hooks
> 
> ```
>  useEffect(() => {
>     window.scrollTop(0, 0);
> }, [location.pathname]);
> ```

在basicLayout中加上这个代码   页面依然不会自动置顶   感觉这是个BUG
