### ISSUE TITLE
配置式路由能否给一个详细配置多个HTML模板的例子啊？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design-pro#5599]

**Comment by chenshuai2144** [comment]
多个 html ？
你是指多页应用吗？

**Comment by wo-de-ping-er** [comment]
![image](https://user-images.githubusercontent.com/23158766/68909200-85cd6a80-0788-11ea-9c76-6303b3984483.png)
给指定页面配置HTML模板   这个如何做？  感觉没说清楚

**Comment by chenshuai2144** [comment]
好像不能给制定的，是给任何页面都配置。
@sorrycc  来看一下？

**Comment by wo-de-ping-er** [comment]
> 多个 html ？
> 你是指多页应用吗？

![image](https://user-images.githubusercontent.com/23158766/68909285-ce852380-0788-11ea-8b78-3315ceba471f.png)
针对特定的页面给出相应的HTML模板   目前按照官网的配置方式应用在项目里面   一直报错

**Comment by wo-de-ping-er** [comment]
> 好像不能给制定的，是给任何页面都配置。
> @sorrycc 来看一下？

我们现在有个需求   就是在给指定页面配置指定的HTMl模板   因为document.ejs需要引入像高德地图等相应的超链   但是这样的话   仅仅只想在特定页面加载这些超链   所以想法是为特定页面指定特定的HTML模板   官网提供相应的方法   但感觉一直报错

**Comment by chenshuai2144** [comment]
高德 这种的 应该用动态载入。

https://www.npmjs.com/package/@shopify/react-import-remote
https://www.npmjs.com/search?q=script%20import

npm 里面有一堆这种类似的包，使用起来更加简单
