### ISSUE TITLE
Upload组件 点击删除会触发预览事件

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5602]
![image](https://user-images.githubusercontent.com/47104575/68842150-ddc08e80-0700-11ea-8091-82059ef4130c.png)
如图，鼠标移动在这个蓝色的区域 点击都会触发预览事件，然后我点击删除，删除后会触发预览事件。

**Comment by 904492381** [comment]
![image](https://user-images.githubusercontent.com/47104575/68842840-0432f980-0702-11ea-8c8a-f8abda8ee2a8.png)
这是控制台打印的
![image](https://user-images.githubusercontent.com/47104575/68842872-114fe880-0702-11ea-839b-73c233a5d640.png)

**Comment by 904492381** [comment]
好像 是在删除默认文件 defaultFileList的时候才会出现这种情况

**Comment by 904492381** [comment]
虽然解决了，但是还是会触发预览事件，我只是让它不要打开图片

**Comment by 904492381** [comment]
又发现一个问题， 我在remove事件中用this.setstate设置了fileList，它在触发预览事件后，setstate还未完成， 在预览事件中删掉的文件还是在，我还是会找到我点击的图片的index。

**Comment by yoyo837** [comment]
同志，不要着急开开关关，考虑下 watching 的感受。解决了晚两天关也没事。

**Comment by 904492381** [comment]
> 同志，不要着急开开关关，考虑下 watching 的感受。解决了晚两天关也没事。

好的 下次注意  我以为解决了  发现又有问题

**Comment by chenshuai2144** [comment]
来个重现的 demo

**Comment by 904492381** [comment]
> 来个重现的 demo
![image](https://user-images.githubusercontent.com/47104575/68909750-5a4b7f80-078a-11ea-8f34-c4369a0b1983.png)
![image](https://user-images.githubusercontent.com/47104575/68909780-70594000-078a-11ea-9e42-66a5f0212268.png)

这就是最普通的demo了，你可以试下，就是这个组件删除都会触发预览事件，虽然我用别的办法解决了，但是事件还是会触发，最好能阻止冒泡不让它触发
