### ISSUE TITLE
🧐[问题]左侧菜单突然变蓝色，回滚也没用，有没有解决方法？

### ISSUE THREAD

**Issue by xhw0714** [ant-design/ant-design-pro#5603]
如题。

**Comment by mahailong** [comment]
我把"@ant-design/pro-layout"的版本回退到"4.5.9"就好了

**Comment by mahailong** [comment]
> 如题。

我把"@ant-design/pro-layout"的版本回退到"4.5.9"就好了

**Comment by xhw0714** [comment]
> > 如题。
> 
> 我把"@ant-design/pro-layout"的版本回退到"4.5.9"就好了

![image](https://user-images.githubusercontent.com/24238674/68844532-ec10a980-0704-11ea-8b10-3cea21879b99.png)
我现在就是4.5.9版本出现的这个问题

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/2569beb30c52118855bb3be6ad8d79d4b2c2d747/src/layouts/BasicLayout.tsx#L155
拷贝一下这行

**Comment by xiahaichao11** [comment]
> https://github.com/ant-design/ant-design-pro/blob/2569beb30c52118855bb3be6ad8d79d4b2c2d747/src/layouts/BasicLayout.tsx#L155
> 
> 
> 拷贝一下这行 现在submenu 也支持 render了

这太及时了，万分感谢，

**Comment by ZuhuaLiu** [comment]
为什么依赖版本没变这个地方会有变动，以后更改的话是不是还是会持续影响之前开发的项目啊

**Comment by justCopyBt** [comment]
这个说打包的时候自动升级吗，能不能锁版本？

**Comment by chenshuai2144** [comment]
@ZuhuaLiu  因为是 4.6 升级到 4.7.
做了一个 break change 。 submenu 现在没有自定义的 render 方式也很难受

**Comment by jackkke** [comment]
> https://github.com/ant-design/ant-design-pro/blob/2569beb30c52118855bb3be6ad8d79d4b2c2d747/src/layouts/BasicLayout.tsx#L155
> 
> 
> 拷贝一下这行 现在submenu 也支持 render了

我的代码里面已经有这一行了，为什么控制台还在提示错误？

**Comment by flasco** [comment]
> @ZuhuaLiu 因为是 4.6 升级到 4.7.
> 做了一个 break change 。 submenu 现在没有自定义的 render 方式也很难受

break change 不应该直接升级大版本吗。。

**Comment by liuguojia** [comment]
这个BUG不仅是变蓝色的问题，而且点击了父级菜单后还会反问路由地址并报错问题。

**Comment by chenshuai2144** [comment]
他是一个通知的提醒 @jackkke ，在一段时间后才会消失

**Comment by chenshuai2144** [comment]
@liuguojia  报错什么？ 是 404 吗？

**Comment by TianEnPang** [comment]
@jackkke 
目前我是找到node_model下的警告源码，然后注释掉了（注释掉后就不报警告了）。
等以后更新了也就好了。
node_modules\@ant-design\pro-layout\lib\BasicLayout.js  #251行
node_modules\@ant-design\pro-layout\es\BasicLayout.js #218行

**Comment by myproject-hkp** [comment]
basicLayout.js文件中代码也该了，侧边导航直接在global.less中通过样式也改了，怎么那个警告还在呢？

**Comment by 544751779** [comment]
对啊 为啥error 还在呢 ?

**Comment by jackkke** [comment]
> @jackkke
> 目前我是找到node_model下的警告源码，然后注释掉了（注释掉后就不报警告了）。
> 等以后更新了也就好了。
> node_modules@ant-design\pro-layout\lib\BasicLayout.js #251行
> node_modules@ant-design\pro-layout\es\BasicLayout.js #218行

感谢，找到后注释了就ok了

**Comment by chenshuai2144** [comment]
已经删掉了
