### ISSUE TITLE
🧐[问题]通用查询Form

### ISSUE THREAD

**Issue by wangly452470** [ant-design/ant-design-pro#5604]
### 🧐 问题描述

我是最近刚接触react和ant-design-pro的
在做列表查询是，我想到一个问题。在企业级后台管理系统中有大量的页面都是列表查询页面。
如果每个页面都去维护自己的查询条件的话会有大量的冗余代码。所以就有了将查询列表的查询条件单独抽成一个通用组件的想法。
该通用组件接收父组件的属性，属性包含有哪些查询条件，有哪些按钮。条件需传入label、name、type，按钮需要传入name、event、type。通过这些属性渲染通用查询条件组件。为了方便部分props直接卸载了state中。
我遇到的问题是：
  父组件传进来的函数可通过props传入，能正常调用。
  handleReset是通用组件提供的方法，父组件怎么传进来才能调用到？
我通过event: this.handleReset()，冒红，编译不通过
event: 'handleReset',能编译通过，但是调用不到方法。

### 💻 示例代码
import React from 'react'
import { Form, Row, Col, Input, Button, Icon } from 'antd';
import { FormComponentProps } from 'antd/es/form';

interface SimpleQueryConditionProps extends FormComponentProps {
  // conditions: Array<object>;
  // buttons: Array<object>;
  handleSearch: Function;
  handleReset: Function;
  toggle: Function;
}

class SimpleQueryCondition extends React.Component<SimpleQueryConditionProps, any>{
  state={
    expand: false,
    buttons: [
      {
        name: '查询',
        event: this.props.handleSearch,
        type: 'primary'
      },{
        name: '重置',
        event: 'handleReset',
        type: ''
      },{
        name: '展开',
        event: 'toggle',
        type: 'link'
      }
    ],
    conditions: [
      {
        label: '用户名',
        name: 'userName',
        type: 'text',
      },{
        label: '使用状态',
        name: 'validStatus',
        type: 'text'
      },{
        label: '用户名',
        name: 'userName',
        type: 'text',
      },{
        label: '使用状态',
        name: 'validStatus',
        type: 'text'
      }
    ]
  }
  getConditions=()=>{
    console.log(this.props)
    const conditions = this.state.conditions;
    const children = new Array();
    const count = this.state.expand ? 1000 : 3;
    const { getFieldDecorator } = this.props.form;
    conditions.map((item, index) => {
      children.push(
        <Col span={8} key={item.name} style={{ display: index < count ? 'block' : 'none' }}>
          <Form.Item label={item.label}>
            {getFieldDecorator(item.name, {
              rules: [
                {
                  required: true,
                  message: 'Input something!',
                },
              ],
            })(<Input placeholder={'请输入'+item.label} type={item.type}/>)}
          </Form.Item>
        </Col>
      )
    })
    if(!this.state.expand){
      const buttons = this.state.buttons;
      children.push(
        <Col span={8} key='btn'style={{display: 'block'}}>
          <Form.Item>
            {
              buttons.map(item => {
                if(item.event == 'handleReset'){
                  return (<Button type={item.type} onClick={this.handleReset} style={{ marginLeft: 8 }} >{item.name}</Button>)
                }else if(item.event == 'toggle'){
                  return (<Button type={item.type} onClick={this.toggle} style={{ marginLeft: 8 }} >{item.name}</Button>)
                }else{
                  return (<Button type={item.type} onClick={item.event} style={{ marginLeft: 8 }} >{item.name}</Button>)
                }
                
              })
            }
          </Form.Item>
        </Col>
      )
    }
    console.log(children)
    return children;
  }
  handleReset= () => {
    console.log("重置")
  }
  toggle= () => {
    console.log("展开")
  }
  render() {
    return (
      <div>
        <Form onSubmit={this.props.handleSearch()} layout="inline">
          <Row gutter={{ md: 8, lg: 24, xl: 48 }}>{this.getConditions()}</Row>
        </Form>
      </div>
    )
  }
}

export default Form.create<SimpleQueryConditionProps>()(SimpleQueryCondition);

**Comment by wangly452470** [comment]
本人是新手，提的问题比较蠢。让各位大牛见笑了。_(:з」∠)_

**Comment by wangly452470** [comment]
现在这个能用，只是个雏形。想请教各位大神，优化一下代码

**Comment by chenshuai2144** [comment]
可以使用 onInit

`this.props.onInlt({action})`
