### ISSUE TITLE
🐛[BUG] 用Tree组件设置自动展开expandedKeys时，有时候不会自动展开

### ISSUE THREAD

**Issue by WuZheXiao** [ant-design/ant-design-pro#5605]
### 🐛 bug 描述

用Tree组件的时候，页面进来设置了展开属性expandedKeys（受控的），但有时候不会自动展开，也没有报错。。出现不自动展开的概率为30%左右

### 💻 复现代码
![image](https://user-images.githubusercontent.com/26809951/68912704-e7470680-0793-11ea-91ae-9ed326f46710.png)

![image](https://user-images.githubusercontent.com/26809951/68912637-a5b65b80-0793-11ea-9780-67657b4a36ab.png)

**Comment by chenshuai2144** [comment]
有可能是你的数据还没有 render 完成，你就设置了  expandedKeys。
最好 setTimeOut 一下

**Comment by WuZheXiao** [comment]
嗯，解决了 3q
