### ISSUE TITLE
Upload组件的 下载按钮样式修改不了

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5606]
![image](https://user-images.githubusercontent.com/47104575/68913207-7f91bb00-0795-11ea-8b68-ce28a982b463.png)
![image](https://user-images.githubusercontent.com/47104575/68913058-08f4bd80-0795-11ea-9f03-39bf5a73b10b.png)
如图  我修改ant-upload-list-item-card-actions或者i标签可以生效  但是改下面的action 和 action-download 都不可以  我想只留下删除按钮

![image](https://user-images.githubusercontent.com/47104575/68912994-cb903000-0794-11ea-8ecf-c274fecc113d.png)
这样可以  但是下载和删除都没了 不符合我的需求

![image](https://user-images.githubusercontent.com/47104575/68913010-e367b400-0794-11ea-85c5-4811439c7013.png)
这样却不可以了  action也是一样

**Comment by chenshuai2144** [comment]
在 showUploadList 中配置就好了


`showUploadList = { showRemoveIcon : false }`
