### ISSUE TITLE
#最新版本20180103  npm install 报错#

### ISSUE THREAD

**Issue by iT-lijun** [ant-design/ant-design-pro#561]
=================================================================
# 0.翻墙之前 报错：
=================================================================
C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0>npm install

\> weak@1.0.1 install C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0\node_modules\weak
\> node-gyp rebuild

C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
gyp ERR! stack     at Object._errnoException (util.js:1024:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1046:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0\node_modules\weak
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN @antv/g2-plugin-slider@2.0.1 requires a peer of @antv/g2@>=3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react@>15 <16 but none is installed. You must install peer dependencies yourself.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-dom@>15 <16 but none is installed. You must install peer dependencies yourself.
npm WARN bizcharts-plugin-slider@2.0.1 requires a peer of react-addons-transition-group@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-redux@5.0.0-alpha.6 requires a peer of react@^15 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 118 packages in 69.313s

C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0>

=================================================================
# 1. 翻墙之后 报错：
=================================================================
C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\dsl\Desktop\Pros\ant-design-pro-master-v3.1.0\node_modules\weak
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by chenshuai2144** [comment]
msbuild 是什么操作！
你装了gyp？》

**Comment by WhatAKitty** [comment]
> msbuild 是什么操作！
有些组件需要在本地进行编译。

@iT-lijun 你重新安装一下试试，先删除你的node_modules然后清空下node的缓存。或者直接使用yarn常识下安装。

**Comment by afc163** [comment]
应该不是我们的问题，建议自行查询一下 stackoverflow。

**Comment by kaoding** [comment]
Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).
@iT-lijun

**Comment by iT-lijun** [comment]
已解决，解决方法参考mousetraps的 [https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245](url)
也可以参考[http://www.cnblogs.com/iTlijun/p/8193588.html](url)
