### ISSUE TITLE
🐛[BUG] Could not resolve 

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5611]
在pro 里编写组件，组件有个data.d.tsx ，在pages 页面里进行引入使用，npm start 启动的时候控制台报错误
![image](https://user-images.githubusercontent.com/30397655/69006253-5f195a80-0967-11ea-97fa-d9ffd926f415.png)

不知道是我写的问题，还是ts配置问题

**Comment by chenshuai2144** [comment]
一般而言。d.ts 里面只能写类型。如果里面有逻辑，删除掉 d

**Comment by leshalv** [comment]
没有写逻辑，这个是umi的改进项，已经和 @sorrycc 陈成大佬沟通了，应该是 mock 文件对 ts 的支持没有那么好，不支持依赖的 ts 解析。ts 解析支持 _mock.ts，以及 mock 目录，其他路径的解析会不正确。
