### ISSUE TITLE
V1版本 proxy代理不生效的疑问

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design-pro#5613]
### 🧐 问题描述

目前项目是需要获取微信公众号的code所以需要跨域，为了解决跨域前端采用代理的方式。

### 💻 示例代码

项目版本号
![Captureww](https://user-images.githubusercontent.com/37989537/69021514-fc6da080-09f2-11ea-9c41-4380ab4a1b3d.PNG)

### 🚑 其他信息

配置的webpackrc.js如图
![Capture](https://user-images.githubusercontent.com/37989537/69021538-114a3400-09f3-11ea-8afa-91a029b80102.PNG)

services的接口如图

![Capture11](https://user-images.githubusercontent.com/37989537/69021564-2cb53f00-09f3-11ea-855a-53c8537b0694.PNG)

发起的get请求如图

![Captureqqq](https://user-images.githubusercontent.com/37989537/69021566-376fd400-09f3-11ea-9536-06fc28b937b6.PNG)

实际结果是
![Captureggg](https://user-images.githubusercontent.com/37989537/69021579-43f42c80-09f3-11ea-962d-5f2cbfdeeeca.PNG)

fetch请求并没有把/connectWeixin转化成微信的https

请问这是什么原因？需要怎么解决呢？

**Comment by chenshuai2144** [comment]
proxy 不会修改 url，可以去看一些科普文章
