### ISSUE TITLE
 Removing the - character in the page title

### ISSUE THREAD

**Issue by charithjayasanka** [ant-design/ant-design-pro#5614]
### Remove - character in generated page title in the tab.

After removing the default title (Ant Design Pro ) from the code, the page title is displayed in the tab but with a - character appended to end of it.
Ex :- Login - , Monitor - , Success -

![Annotation 2019-11-18 165731](https://user-images.githubusercontent.com/33053033/69048929-add8fa00-0a24-11ea-9d8f-fcb51d976488.png)

![Annotation 2019-11-18 165755](https://user-images.githubusercontent.com/33053033/69048934-b03b5400-0a24-11ea-9c90-dc57c601ea03.png)

**Comment by chenshuai2144** [comment]
you can use pageTitleRender

**Comment by charithjayasanka** [comment]
That worked out. Thanks for the help
