### ISSUE TITLE
🧐新手使用Pagination组件出现错误，求解答

### ISSUE THREAD

**Issue by Hstare** [ant-design/ant-design-pro#5616]
### 💻 示例代码
`render() {
    return (
    <div>
      <Pagination size="small" defaultPageSize={5} total={50} />
    </div>)
  }`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/36981685/69128885-2d7bcd00-0ae8-11ea-822d-5b678871d55f.png)

**Comment by chenshuai2144** [comment]
看看是什么影响了？可能是外面包裹了flex布局导致的
