### ISSUE TITLE
Drak 主题是怎么配置的有具体的文档,吗? 🧐[问题]

### ISSUE THREAD

**Issue by shxinlei** [ant-design/ant-design-pro#5617]
### 🧐 问题描述
Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊Drak主题 啊

  @ant-design/dark-theme 安装完毕之后呢 ?

**Comment by chenshuai2144** [comment]
在config 中配置  ` theme:drak`。
我现在在等待 antd4.0的 官方dark主题。我做的是码农的审美，并不是很完美
