### ISSUE TITLE
🐛[BUG] Tab should be placed after handleVisibleChange

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5621]
NoticeIcon 组件 Tab should be placed after handleVisibleChange Eslint 错误

**Comment by chenshuai2144** [comment]
不要重复的提交同一个问题

**Comment by leshalv** [comment]
好的大佬

**Comment by leshalv** [comment]
嗯，我提的pr过去不去，大佬帮忙看下吧，umi ui 检测包括webstorm eslint 都有问题，但是那个提交上去检测就不行，大佬处理下吧
