### ISSUE TITLE
🧐[问题] modal  effects 规范

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5624]
![image](https://user-images.githubusercontent.com/30397655/69199012-ab37eb00-0b71-11ea-893f-96a5ccf91f29.png)
个人觉得下划线方式比较清晰，调理，不知道大佬们都用什么方式，pro有没有相关规范。

**Comment by chenshuai2144** [comment]
找了一圈没有相关规范，我现在都在用 hooks。
先关掉了，估计会越来越不重要
