### ISSUE TITLE
可以在settingsDrawer里面增加darkTheme选项吗？

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#5625]
### 🥰 需求描述

试用了 []darkTheme((https://github.com/ant-design/ant-design-dark-theme))，感觉挺炫的；
但是在config里面配置，运行中不能动态切换是否使用dark，实际项目中只有dashboard页面有dark主题的需求，

### 🧐 解决方案

能否在settingsDrawer中加入这个选项？
或者能否说下怎么更轻量的动态切换theme的步骤？

**Comment by chenshuai2144** [comment]
这周会搞一个 demo 出来，但是比较卡。可以等一等

**Comment by huang714669** [comment]
期待......

**Comment by chenshuai2144** [comment]
看一下 dark 分支和你想要的一样吗？@huang714669

**Comment by huang714669** [comment]
已经使用了， 最新的pro-layout4.7.5-1的npm包下不了，所以暂时使用4.7.5-0
发现了一个bug，使用antd description组件，显示异常如下

**Comment by huang714669** [comment]
![error](https://user-images.githubusercontent.com/13537904/69508787-aa3bfa80-0f71-11ea-97f7-00cd490b6e30.png)

**Comment by chenshuai2144** [comment]
@huang714669  看起来是有个变量没覆盖。你可以先人肉设置一下，我推动 antd 改一下

**Comment by chenshuai2144** [comment]
合并到主分支了
