### ISSUE TITLE
🐛[BUG] 获取全部区块后，固定 Header有bug

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design-pro#5627]
### 🐛 bug 描述

获取全部区块后，固定 Header 有bug。无法固定 Header，而且其他样式也有问题。具体问题请查看下面的GIF。
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-pro-bug.xhzwlv1w6ip.gif)

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本
- 浏览器环境 [chrome]
- 开发环境 [Win10]

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/ant-design-pro-layout/blob/master/changelog.en-US.md#473
