### ISSUE TITLE
在对接laravel api 时发现 Authorization 获取不到，以及登录成功后SecurityLayout 中获取不到currentUser

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#5628]
首先是request.ts 中获取不到Authorization 
目前已在lssues中搜索到解决。
`request.interceptors.request.use((url, options) => {
  options.headers = {
    ...options.headers,
    Accept: 'application/x.optometry.v1+json',
    'Content-Type': 'application/json; charset=utf-8',
    Authorization: getAuthorization(),
  }
  return (
    {
      url:url,
      options: {
        ...options,
        interceptors: true,
      },
    }
  );
});`
登录成功能获取到用户信息
![image](https://user-images.githubusercontent.com/42925731/69217033-9460bb00-0ba8-11ea-9805-86b8413ace40.png)

但是在SecurityLayout.tsx 文件中 初次登录获取不到currentUser  再次输入账号密码登录成功跳转

`render() {
    const { isReady } = this.state;
    const { children, loading, currentUser } = this.props;
    **console.log(currentUser);**
    // You can replace it to your authentication rule (such as check token exists)
    // 你可以把它替换成你自己的登录认证规则（比如判断 token 是否存在）
    const isLogin = currentUser && currentUser.id;
    const queryString = stringify({
      redirect: window.location.href,
    });

    if ((!isLogin && loading) || !isReady) {
      return <PageLoading />;
    }
    if (!isLogin) {
      return <Redirect to={`/user/login?${queryString}`}></Redirect>;
    }
    return children;
  }`

**Comment by kzabc** [comment]
@chenshuai2144

**Comment by kzabc** [comment]
@ 各位大佬

**Comment by yoyo837** [comment]
社区大部分人都不是全职的 @kzabc 不要过度依赖。

**Comment by kzabc** [comment]
嗯 谢谢大佬

**Comment by chenshuai2144** [comment]
来个可重现的 repo，我们的登录是假的

**Comment by jinuem** [comment]
any update on this?

**Comment by jinuem** [comment]
@kzabc why this is closed. Still, this issue persists in master branch.
