### ISSUE TITLE
🐛[BUG]设置fixedHeader: true, 顶部状态栏样式出现问题

### ISSUE THREAD

**Issue by lemoncy** [ant-design/ant-design-pro#5629]
### 🐛 bug 描述
设置defaultSettings.ts
fixedHeader: true, 顶部状态栏样式出现空白问题，如图1,
且顶部状态栏无法固定，如图2

图1：
![image](https://user-images.githubusercontent.com/3096214/69239198-abb59d80-0bd4-11ea-86ea-2b91839b9e35.png)
![image](https://user-images.githubusercontent.com/3096214/69239372-00591880-0bd5-11ea-8f36-0a3c6ba54550.png)
图2：
![image](https://user-images.githubusercontent.com/3096214/69240179-e3254980-0bd6-11ea-820a-88c470c57f5a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed 4.7.3
🐞 https://github.com/ant-design/ant-design-pro-layout/blob/master/changelog.zh-CN.md#473
