### ISSUE TITLE
🧐[问题] 每个Layout能实现不同的theme吗？

### ISSUE THREAD

**Issue by jing-wu** [ant-design/ant-design-pro#5630]
不同的layout下是不同的子系统，想要每个子系统实现不同的主题风格，比如layoutA下是light风格，layoutB下是dark风格。

请教大佬们，实现这个效果有什么思路吗？

**Comment by chenshuai2144** [comment]
这个需要使用 ,不然容易混淆。
https://github.com/umijs/umi#community
如果只是想改变菜单颜色，可以试试 嵌套 layout
