### ISSUE TITLE
今天获取的版本会自动插入带有g_umiuiBlockAddEditMode的节点，导致布局混乱🐛[BUG]

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design-pro#5635]
今天获取的版本会自动插入带有g_umiuiBlockAddEditMode的节点，导致布局混乱

**Comment by ffalconjs** [comment]
![image](https://user-images.githubusercontent.com/22336356/69395907-8d0dee80-0d1b-11ea-9acb-d78e68c62270.png)

**Comment by ffalconjs** [comment]
仅在开发环境存在

**Comment by chenshuai2144** [comment]
关闭一下[ umi ui](https://umijs.org/zh/guide/umi-ui.html)
`cross-env UMI_UI=none umi dev`
