### ISSUE TITLE
defaultSettings.js读不到config/config.js里define定义的参数

### ISSUE THREAD

**Issue by sicun7** [ant-design/ant-design-pro#5636]
### defaultSettings.js读不到config/config.js里define定义的参数

我在config/config.js的webpack配置项define里定义了一个参数CUSTOM_CODE, 在defaultSettings里取不到,  构建时一直提示CUSTOM_CODE is not defined,  项目里其他代码里都可以取到.

config/config.js:

```
define: {
    APP_TYPE: APP_TYPE || '',
    CUSTOM_CODE: CUSTOM_CODE || 'Common',
 },

```
defaultSettings.js:

`const customConfig =  require(`./custom/${CUSTOM_CODE}`);`

package.json:

` "start": "cross-env CUSTOM_CODE=Common  MOCK=none umi dev",`

**Comment by chenshuai2144** [comment]
defaultSettings 要通过环境变量使用。

`process.env. CUSTOM_CODE`

**Comment by sicun7** [comment]
> defaultSettings 要通过环境变量使用。
> 
> `process.env. CUSTOM_CODE`

我在define里配置了还是不行, 引用时报错:

`const custom =  require(`./custom/${process.env.CUSTOM_CODE}`);`

ReferenceError: process is not defined

```
define: {
    APP_TYPE: APP_TYPE || '',
    CUSTOM_CODE,
    'process.env': {
      'CUSTOM_CODE': JSON.stringify(CUSTOM_CODE)
    }
  },
```

**Comment by sicun7** [comment]
> defaultSettings 要通过环境变量使用。
> 
> `process.env. CUSTOM_CODE`

我配置了还是不行
```
  define: {
    APP_TYPE: APP_TYPE || '',
    CUSTOM_CODE,
    'process.env.CUSTOM_CODE': JSON.stringify(CUSTOM_CODE),
  },
```

`const custom =  require(`./custom/${process.env.CUSTOM_CODE}`);`

错误: process undefined

**Comment by sicun7** [comment]
成功了, 刚配置process没成功是因为我没重新打包的原因
