### ISSUE TITLE
👑 [需求]BasicLayout布局建议

### ISSUE THREAD

**Issue by waj1991-afk** [ant-design/ant-design-pro#5639]
### 🥰 需求描述

左侧菜单顶部的logo图标点击时，跳转的地址无法修改。
如果对项目根路径进行修改后，无法跳转至真实的项目地址

### 🧐 解决方案

默认区config配置的根路径，或者有个可以手动配置的地方

### 🚑 其他信息

![微信截图_20191122174610](https://user-images.githubusercontent.com/58070415/69415668-01fb1b80-0d50-11ea-9fdd-30135ba3437e.png)

**Comment by chenshuai2144** [comment]
try  

onMenuHeaderClick | menu 菜单的头部点击事件 | (e: React.MouseEvent<HTMLDivElement>) => void | -
-- | -- | -- | --
