### ISSUE TITLE
🐛[BUG]SecurityLayout导致重复跳转登录页面

### ISSUE THREAD

**Issue by twtyjvkg** [ant-design/ant-design-pro#5640]
### 🐛 bug 描述

本地开发，在进行登录操作时，有时会循环跳转到登录页面，见截图

### 📷 复现步骤

输入http://localhost:8000/user/login， 输入用户名密码，点击登录，这时会跳转到SecurityLayout进行是否登录的校验，重复到登录页面的情形见截图。
通过network可以看出，已经完成登录，但是还没有查询currentUser。

### 🏞 期望结果

跳转到首页

### © 版本信息

- Ant Design Pro 版本: 4.5.16
- umi 版本：2.9.6
- 浏览器环境 Chrome 77.0.3865.90
- 开发环境 win10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26063786/69426937-5b237900-0d69-11ea-9942-16e8c1ed5158.png)
![image](https://user-images.githubusercontent.com/26063786/69427176-f1f03580-0d69-11ea-970f-29fb09d61fa1.png)

**Comment by TianEnPang** [comment]
你看下这个应该可以解决，我刚用这个方法解决。
[#5348](https://github.com/ant-design/ant-design-pro/issues/5348#issuecomment-544956068)

**Comment by chenshuai2144** [comment]
看描述是因为dispatch 的速度太慢导致的？

**Comment by twtyjvkg** [comment]
应该是了，我觉得应该把isReady=true的代码放到dispatch的callback里，这样就能避免这个问题了。

**Comment by dumengQaQ** [comment]
> 看描述是因为dispatch 和 组件更新速度不同导致的？

对的

**Comment by jinuem** [comment]
Same issue i am facing.

**Comment by jinuem** [comment]
@twtyjvkg 
Have you found the solution?

**Comment by Leskur** [comment]
我是这么做的 #5348

**Comment by Leskur** [comment]
```js
if (!isLogin && '/user/login' != window.location.pathname) {
    return <Redirect to={`/user/login?${queryString}`}></Redirect>;
}
```

**Comment by chenshuai2144** [comment]
@Leskur  give a pr？
