### ISSUE TITLE
🧐[Tabs 搭配Authorized无法正常显示]

### ISSUE THREAD

**Issue by LyndonXiao** [ant-design/ant-design-pro#5641]
### 🧐 问题描述

在多页标签中，想实现根据权限显示个别标签页，但是如果使用Authorized组件包裹，则无法正常显示，提示`index.js:1 Warning: There must be `tab` property on children of Tabs. `，同时页面上加载了透明的tab标签，鼠标可点击，点击后跳转第一个标签页。

### 💻 示例代码

```
<Authorized authority={['role/team']}>
                <Tabs.TabPane tab="测试" key="test">111</Tabs.TabPane>
</Authorized>
```

**Comment by chenshuai2144** [comment]
emmm ，antd 不支持这样的用法的，建议使用 display的方法控制。

tabs 下面的子节点是不支持 HOC 的
