### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by web-kubor** [ant-design/ant-design-pro#5642]
### 📷 复现步骤

终端安装时候报错
? Select the boilerplate type ant-design-pro
? Which language do you want to use? JavaScript
选择使用语言后终端报错，如下图所示：

### 💻 复现代码
![img](https://tva1.sinaimg.cn/large/006y8mN6ly1g97wr54viej31b00egdjg.jpg)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
提示很清晰，你的文件夹已存在别的文件了，你需要换个名字
