### ISSUE TITLE
Type checking and linting aborted - probably out of memory. 🧐[问题]

### ISSUE THREAD

**Issue by GloriaCHL** [ant-design/ant-design-pro#5643]
### 🧐 问题描述

引用了一个第三方组件后，编译的时候报了下面的错误，貌似是ts语法检查时内存爆了？请问怎么解决？有什么办法可以排除tslint对这种使用方法的react组件的语法检查吗？

### 💻 示例代码
引用方式如下：

```javascript
import Comp from 'demo';

···
render (
    <Comp />
) 
···

```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10557315/69474399-b4d48380-0dfb-11ea-9a08-dacff6a55bc5.png)

**Comment by chenshuai2144** [comment]
一般这种情况都是引入了过大的依赖，或者循环引用。

**Comment by GloriaCHL** [comment]
是我这边操作有误，问题已经解决。谢谢回复。

**Comment by GloriaCHL** [comment]
请问build的时候 fork-ts-checker 那个插件可去掉吗？或者在哪里配置ignore文件？因为我发现打包内存爆是这个插件对引入的那个component起作用才引起的，dev开发时没这问题。
