### ISSUE TITLE
🧐Tree组件回显问题，怎么单独获取子级的内容，而不是全部被勾选了

### ISSUE THREAD

**Issue by WuZheXiao** [ant-design/ant-design-pro#5644]
传的时候，选中子级顺带父级
![image](https://user-images.githubusercontent.com/26809951/69474482-ba7e9900-0dfc-11ea-8a5c-06ced7fd3003.png)

但是回显的时候，怎么单独显示已传的内容，，
问题：全部被勾选了
![image](https://user-images.githubusercontent.com/26809951/69474530-3547b400-0dfd-11ea-8102-0ba0c244b1ef.png)

正常情况下：单独显示已勾选的内容
![image](https://user-images.githubusercontent.com/26809951/69474505-00d3f800-0dfd-11ea-9976-709c5a3f0cdd.png)

代码如下
提交：
![image](https://user-images.githubusercontent.com/26809951/69474543-69bb7000-0dfd-11ea-9070-642160add59a.png)
代码：
![image](https://user-images.githubusercontent.com/26809951/69474557-8b1c5c00-0dfd-11ea-96bc-275e1db67231.png)
![image](https://user-images.githubusercontent.com/26809951/69474553-822b8a80-0dfd-11ea-8f3a-4f054a8d21b0.png)

**Comment by chenshuai2144** [comment]
没有听懂诶，你想做什么？

**Comment by WuZheXiao** [comment]
就回显的时候，怎么只显示子级的内容啊，，，我现在连父级也一起显示了，，也被勾选了

**Comment by chenshuai2144** [comment]
来个可重现的 demo 吧，我不理解回显这个概念

**Comment by WuZheXiao** [comment]
没问题了，已经解决啦
