### ISSUE TITLE
ant-pro 设置fixedHeader 固定顶部失败！！🐛[BUG]

### ISSUE THREAD

**Issue by zhangbiy** [ant-design/ant-design-pro#5649]
### 🐛 bug 描述
ant-pro 设置fixedHeader 固定顶部失败！！

### 📷 复现步骤
defaultSettings.js ->  fixedHeader:true

**Comment by chenshuai2144** [comment]
在这里修复  
https://github.com/ant-design/ant-design-pro-layout/pull/209

**Comment by chenshuai2144** [comment]
4.8 中已修复

**Comment by y-a-n-g-a-n-g** [comment]
额  为啥我的还不好使  
![image](https://user-images.githubusercontent.com/17758990/69699466-f5493f80-1122-11ea-8224-ca77dc7ce813.png)
![image](https://user-images.githubusercontent.com/17758990/69699479-ff6b3e00-1122-11ea-866a-408bf864f591.png)

**Comment by chenshuai2144** [comment]
你看看官网，对比一下区别
