### ISSUE TITLE
🧐[问题] 有没有人尝试过docz或者react-styleguidist，在pro基础上做组件文档

### ISSUE THREAD

**Issue by gebin** [ant-design/ant-design-pro#5650]
### 🧐 问题描述
一直在使用ant design pro做为基础定制开发业务系统，最近因为组件越来越多，希望做一个组件的文档来方便同事之间来查阅和使用组件，查阅了一些资料之后发现，比较合适的就是docz，storybook和
react-styleguidist，docz得到的文档形式比较满足我们的需要，但是配置的时候总是出现webpack配置问题，暂时无法解决，不知道有没有朋友尝试过这个，给一些意见 
 
### 🚑 其他信息

https://www.docz.site/docs/getting-started#add-docz-to-an-existing-project
https://react-styleguidist.js.org/docs/getting-started.html

**Comment by chenshuai2144** [comment]
可以直接使用 father doc。
https://www.npmjs.com/package/father

正好支持 storybook 和 docz
