### ISSUE TITLE
🐛[BUG]移动端访问报错：<a> cannot appear as a descendant of <a>.

### ISSUE THREAD

**Issue by twtyjvkg** [ant-design/ant-design-pro#5651]
### 🐛 bug 描述

将开发者工具调成移动设备后，会出现`<a> cannot appear as a descendant of <a>`.的警告

### 📷 复现步骤

移动设备访问

### 💻 复现代码
logo包了一层a标签

![image](https://user-images.githubusercontent.com/26063786/69544864-945b2380-0fcb-11ea-927c-259ea8392b63.png)

### © 版本信息

- Ant Design Pro 版本: 4.5.16

**Comment by chenshuai2144** [comment]
a 不能嵌套 a，看来是dom 导致的，我换个标签

**Comment by wjf444128852** [comment]
@chenshuai2144 PC端缩放的时候也会出现这个Warning，导致的该原因出现的位置：BasicLayout.jsx/menuHeaderRender方法内部，
![image](https://user-images.githubusercontent.com/16033932/71051951-d9b2e100-2184-11ea-823f-550ec0c4bd77.png)

![image](https://user-images.githubusercontent.com/16033932/71051997-0535cb80-2185-11ea-9c6a-ea67bb65cec8.png)

**Comment by wjf444128852** [comment]
@twtyjvkg

**Comment by xclw2000** [comment]
但是这样就没有点击跳转功能了呀

**Comment by zqxb** [comment]
自定义不就有了？ 报错问题有解决么？

**Comment by xclw2000** [comment]
> 自定义不就有了？ 报错问题有解决么？

解决了，谢谢

**Comment by chenshuai2144** [comment]
在新版本中使用了div，不会出现 a 嵌套 div的情况了
