### ISSUE TITLE
左侧栏菜单＋顶部菜单栏，有人这样改造过的吗？👑 [需求]

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design-pro#5652]
### 🥰 需求描述
顶部菜单栏只有一级，当点击顶部菜单栏的某个菜单会对应显示左侧菜单栏数据

顶部菜单栏只有一级，当点击顶部菜单栏的某个菜单会对应显示左侧菜单栏数据
### 🧐 解决方案
有人这样实现过吗？我想交流下实现的逻辑

有人这样实现过吗？我想交流下实现的逻辑
### 🚑 其他信息
有人这样实现过吗？我想交流下实现的逻辑

![布局](https://user-images.githubusercontent.com/20589684/69595193-dae76700-1039-11ea-9405-1900532aa032.png)

**Comment by pkaq** [comment]
sword那个项目就是这么干的啊

**Comment by dongkeng001** [comment]
> sword那个项目就是这么干的啊

sword那个项目?有仓库地址吗

**Comment by pkaq** [comment]
你搜一下就好了啊 我发也是要给你搜出来贴过来 伸手不要这么彻底把

**Comment by dongkeng001** [comment]
> 你搜一下就好了啊 我发也是要给你搜出来贴过来 伸手不要这么彻底把

你回答的内容表达意思都不明确，你说的这个sword项目指的是ant-design-pro脚手架实现的还是其它脚手架实现的？另外搜的话，是在当前issue里面搜索还是在github网站搜索？如果在当前issue里面搜索的话我是没找到的，如果在github网站搜的话，倒是有一堆sword这样的关键词项目

**Comment by pkaq** [comment]
牛逼 溜了溜了

**Comment by dongkeng001** [comment]
> 牛逼 溜了溜了

技术牛逼就可以为所欲为？回答别人问题得考虑下别人，不然跟没回答有什么区别？？？

**Comment by puce006** [comment]
![1574411956765](https://user-images.githubusercontent.com/28282818/69688614-83acc980-1101-11ea-8c35-7502352ff14c.jpg)
实现了css样式，但是点击顶部菜单，左侧对应的菜单这块还在研究，本人后端，对前端不熟，目前考虑应该是用dva的组件通信去实现，但是还不知道怎么通信还在研究。

**Comment by dongkeng001** [comment]
> ![1574822252303](https://user-images.githubusercontent.com/28282818/69688810-16e5ff00-1102-11ea-95df-79d1b625d1d2.jpg)
> 
> 实现了css样式，但是点击顶部菜单，左侧对应的菜单这块还在研究，本人后端，对前端不熟，目前考虑应该是用dva的组件通信去实现，但是还不知道怎么通信还在研究。

good

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/layout-component-cn#%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80

嵌套布局应该能满足你的需求

**Comment by dongkeng001** [comment]
> https://pro.ant.design/docs/layout-component-cn#%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80
> 
> 嵌套布局应该能满足你的需求

好的，3q

**Comment by TianEnPang** [comment]
@dongkeng001 
[Sword](https://github.com/chillzhuang/Sword#%E5%9C%A8%E7%BA%BF%E6%BC%94%E7%A4%BA)

**Comment by dongkeng001** [comment]
> @dongkeng001
> [Sword](https://github.com/chillzhuang/Sword#%E5%9C%A8%E7%BA%BF%E6%BC%94%E7%A4%BA)

进去看了下，应该是Saber布局才是我想要的效果，可惜Saber是基于vue的版本

**Comment by dm0104x** [comment]
![image](https://user-images.githubusercontent.com/44898730/69846021-a54ab400-12ad-11ea-8054-7236d9c5ce6f.png)不知道这样算不算大的改动

**Comment by chenshuai2144** [comment]
感觉是一个收起的 layou+一个没有 header 的layout

**Comment by HuKang183** [comment]
我们项目现在就是这样的，已经做完了

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/example?anchor=%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80#%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80
