### ISSUE TITLE
🧐如何在热加载中禁用build theme？

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/ant-design-pro#5654]
### 🧐 问题描述

每次修改完代码热加载会在 `build theme` 那里卡几秒，时间有点长，挺急的 :cry: 

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10346399/69608446-6d9bfc00-1062-11ea-9660-294f3b0e9264.png)

**Comment by kaoding** [comment]
注释掉 config.ts 下的
```

// if (!TEST && !isAntDesignProPreview) {
//   plugins.push([
//     'umi-plugin-antd-theme',
//     {
//       theme: [
//         {
//           key: 'dark',
//           fileName: 'dark.css',
//           theme: 'dark',
//         },
//         {
//           key: 'dust',
//           fileName: 'dust.css',
//           modifyVars: {
//             '@primary-color': '#F5222D',
//           },
//         },
//         {
//           key: 'dust',
//           theme: 'dark',
//           fileName: 'dark-dust.css',
//           modifyVars: {
//             '@primary-color': '#F5222D',
//           },
//         },
//         {
//           key: 'volcano',
//           theme: 'dark',
//           fileName: 'dark-volcano.css',
//           modifyVars: {
//             '@primary-color': '#FA541C',
//           },
//         },
//       ],
//     },
//   ]);
// }

```

**Comment by zhang0ZGC** [comment]
> 注释掉 config.ts 下的
> 
> ```
> 
> // if (!TEST && !isAntDesignProPreview) {
> //   plugins.push([
> //     'umi-plugin-antd-theme',
> //     {
> //       theme: [
> //         {
> //           key: 'dark',
> //           fileName: 'dark.css',
> //           theme: 'dark',
> //         },
> //         {
> //           key: 'dust',
> //           fileName: 'dust.css',
> //           modifyVars: {
> //             '@primary-color': '#F5222D',
> //           },
> //         },
> //         {
> //           key: 'dust',
> //           theme: 'dark',
> //           fileName: 'dark-dust.css',
> //           modifyVars: {
> //             '@primary-color': '#F5222D',
> //           },
> //         },
> //         {
> //           key: 'volcano',
> //           theme: 'dark',
> //           fileName: 'dark-volcano.css',
> //           modifyVars: {
> //             '@primary-color': '#FA541C',
> //           },
> //         },
> //       ],
> //     },
> //   ]);
> // }
> ```

不知道这个 theme 干嘛用的，怎么用

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/af01272a27190f3f6390c160d08f282ff27c4939/config/config.ts#L74
删掉这行。
这是相关文章
https://pro.ant.design/blog/dynamic-theme-cn
