### ISSUE TITLE
如何关闭select 的搜索图标的旋转效果？👑 [需求]

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design-pro#5656]
### 🥰 需求描述

![1](https://user-images.githubusercontent.com/37989537/69611639-3715af80-1069-11ea-95a3-abf17a927485.PNG)

![2](https://user-images.githubusercontent.com/37989537/69611655-3d0b9080-1069-11ea-83e5-39f2de343d1f.PNG)

### 🚑 其他信息

focus之后图标会旋转，但官方文档没有找到哪里写了控制旋转？请问如何解决

**Comment by afc163** [comment]
你应该用 AutoComplete 而不是 Select。
