### ISSUE TITLE
🐛[BUG] fixSiderbar 为true时，菜单栏显示异常

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/ant-design-pro#5659]
### 🐛 bug 描述
fixSiderbar 设置为 `true` 时，菜单栏显示异常

### 📷 复现步骤
官方预览，SettingDrawer 勾选固定侧边菜单

或空项目 defaultSettings.ts 设置 fixSiderbar 为true，

### 🏞 期望结果

菜单栏显示正常

### © 版本信息

- Ant Design Pro 版本: 4.0
- 浏览器环境 :  chrome 75

#### 官方预览页面的效果
![image](https://user-images.githubusercontent.com/10346399/69622350-bdd38800-107b-11ea-8860-49101529f562.png)

#### 使用仓库内的 gitpod，随便在 `Welcome.tsx` 增加了点内容的效果
![image](https://user-images.githubusercontent.com/10346399/69622416-db085680-107b-11ea-898b-44b8a9271ee0.png)

**Comment by zhang0ZGC** [comment]
找到了，去掉 `transform: rotate(0); ` 就正常了

![image](https://user-images.githubusercontent.com/10346399/69624055-e8731000-107e-11ea-9132-064a4cb40762.png)

看起来是 ant-design-pro-layout 的问题

**Comment by chenshuai2144** [comment]
置顶换了一个技术方案，方便我们的内部使用。
具体可以看这里
https://github.com/ant-design/ant-design-pro-layout/blob/master/changelog.zh-CN.md#482
