### ISSUE TITLE
🧐[问题]怎么将build阶段的环境变量传给app的window 对象？

### ISSUE THREAD

**Issue by ahuigo** [ant-design/ant-design-pro#5660]
### 🧐 问题描述
有时我们需要将构建阶段的环境变量传给app应用

比如`process.env.APP_ENV='dev' ` 传给app的全局对象`window.APP_ENV`

### 🚑 其他信息
这种变量传递应该写在哪里呢?

**Comment by chenshuai2144** [comment]
https://umijs.org/zh/config/#define
可以通过这个来实现，但是要注意注入代码是非常 hack 的行为，一般不推荐使用

**Comment by ahuigo** [comment]
@chenshuai2144 我在define 里面加了APP_DEV:process.env.APP.ENV.
然后在项目代码(`config/defaultSettings.ts`)中使用APP_ENV.

**请问**我只是想通过环境变量解决让config/defaultSettings.ts 支持 dev/production 模式下的config 切换，有什么非hack 的方法吗？
