### ISSUE TITLE
🧐[问题]  演示环境中的右侧设置图标如何打开

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#5661]
演示环境中的右侧设置图标如何打开

**Comment by leshalv** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
你点不开吗?

**Comment by leshalv** [comment]
显示出来

**Comment by chenshuai2144** [comment]
请详细描述，不然我关掉它

**Comment by leshalv** [comment]
我其实想说，如何显示的和演示环境一样的，因为我下载下来，没有发现那个设置按钮

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/layout-component-cn

**Comment by afc163** [comment]
> https://pro.ant.design/docs/layout-component-cn

这篇文档只提到了 SettingDrawer，没有提到怎么开启 SettingDrawer。

**Comment by whaty** [comment]
到底怎么设置才有啊

**Comment by chenshuai2144** [comment]
你需要这个 
https://pro.ant.design/docs/layout-component-cn#settingdrawer
