### ISSUE TITLE
🐛[BUG]整合webpack插件@arcgis/webpack-plugin导致ant-design报错

### ISSUE THREAD

**Issue by pookpal** [ant-design/ant-design-pro#5662]
### 🐛 bug 描述

使用ant-design-pro的框架，按照官方文档在webchain中使用@arcgis/webpack-plugin插件时，报错，提示无法使用moment库，报错信息如下。

![image](https://user-images.githubusercontent.com/10249353/69705197-03ea2380-1130-11ea-875e-97f33652dccd.png)

### 📷 复现步骤

1、npm install --save-dev @arcgis/webpack-plugin
2、在config/plugin.config.js中引入import ArcGISPlugin from  '@arcgis/webpack-plugin';
3、在config/plugin.config.js中config方法中写入以下代码
config.plugin('@arcgis/webpack-plugin').use(ArcGISPlugin,[
      {
        useDefaultAssetLoaders: false,
}

### 🏞 期望结果

npm  run start能正常运行，并在其他页面可以使用arcgis的api

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by LightningVII** [comment]
@pookpal 请问解决了吗

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它

----

We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
