### ISSUE TITLE
每次更改代码，重新编译是出错，求解决🧐[问题]

### ISSUE THREAD

**Issue by alonesmall** [ant-design/ant-design-pro#5665]
###  build theme出错

根据官网创建一个全新的项目，然后每次编译总是出现，build theme出错，提示theme文件已经存在，重新创建theme，然后一直卡死在这一步。每次修改代码都会这样，求解决。

![error](https://user-images.githubusercontent.com/48789948/69779330-9b0fb380-11e2-11ea-9311-db8c898f4e7e.jpg)

**Comment by alonesmall** [comment]
只有每次删除这个文件夹，才能编译成功，但是一旦修改代码，又继续报这个错误。

**Comment by chenshuai2144** [comment]
重新安装一下依赖，这个是 windows下的权限 bug。

也可以直接在这里删除
https://github.com/ant-design/ant-design-pro/commit/03865b8b81b2a94c18de08f57015ab5ae0e16b85
