### ISSUE TITLE
How to change Gauge language...? range is in chinese language.. i need to change in english.how to do?

### ISSUE THREAD

**Issue by sivasakthi37** [ant-design/ant-design-pro#5666]
how to change Gauge language...? range is in chinese language.. i need to change in english.how to do?

**Comment by joshidhruv** [comment]
Just do following 
`<Gauge title="Test" height={164} percent={87} formatter={(f) => 10 * f } />`
Let me know if that works.

**Comment by sivasakthi37** [comment]
Yes it works. 
Thanks.
