### ISSUE TITLE
左侧菜单从后台拉数据生成，渲染菜单的时候无法为包含children的项匹配对应的语言包

### ISSUE THREAD

**Issue by RickChenCX** [ant-design/ant-design-pro#5667]
### 🧐 问题描述
问题如标题，

**Comment by chenshuai2144** [comment]
自定一的菜单没有进行 国际化格式的，可以直接在后端格式化掉吧？

**Comment by RickChenCX** [comment]
> 自定义的菜单没有进行 国际化格式的，可以直接在后端格式化掉吧？

国际化格式？貌似没有这个说明吧，在config下面配置的路由倒是能够正常显示，现在在想是否把多语言加到项目里

**Comment by chenshuai2144** [comment]
@RickChenCX  4.10.0 的 layout 支持了一下内部也有这个需求
