### ISSUE TITLE
🧐[问题]在react ts下怎么独立使用啊

### ISSUE THREAD

**Issue by SilentWeirdo** [ant-design/ant-design-pro#5669]
### 🧐 问题描述

在ts项目里独立使用一直报错，不知道是什么原因
Type '{}' is missing the following properties from type 'BasicLayoutProps': breadcrumbNameMap, disableContentMargin

### 💻 示例代码
// App.tsx
import React from 'react';
// import logo from './logo.svg';
import './App.css';
import BasicLayout from '@ant-design/pro-layout'

const App: React.FC = () => {
  return (
        <BasicLayout />
  );
}

export default App;

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38556357/69789423-825fc780-11fb-11ea-8679-3b0ecac9ebbd.png)

**Comment by wangxingkang** [comment]
缺必须参数吧

**Comment by chenshuai2144** [comment]
你想使用的是它吧？
https://github.com/ant-design/ant-design-pro-layout
