### ISSUE TITLE
🧐[问题]安装V4，npm create umi 下来的是1.0.0，还这种警告.

### ISSUE THREAD

**Issue by lemoncy** [ant-design/ant-design-pro#5670]
### 🧐 问题描述
安装V4，npm create umi 下来的是1.0.0，还这种警告。
1、npm create umi
2、npm install
出现以下警告，项目目录package.json版本也是 ：1.0.0，什么 问题，有大神能改释一下么，
今天新装的node，npm，是环境问题么？

![image](https://user-images.githubusercontent.com/3096214/69806127-1beba100-121d-11ea-983b-06f4d216a98f.png)

![image](https://user-images.githubusercontent.com/3096214/69806542-15115e00-121e-11ea-90ea-2f57e2e2822a.png)

**Comment by chenshuai2144** [comment]
这是 npm 整个生态的问题。 create umi 生成出来就是一个新的仓库，和 pro 没有关系
