### ISSUE TITLE
动态路由重定向无效🧐[问题]

### ISSUE THREAD

**Issue by Feather130** [ant-design/ant-design-pro#5672]
### 🧐 问题描述

config.js的路由里没有配置重定向，重定向的地址是请求回来的，现在无法重定向到目标页面
### 🚑 其他信息

config.js
![image](https://user-images.githubusercontent.com/10240614/69840704-6b6eb300-1297-11ea-9f2a-905910276b14.png)

mock
![image](https://user-images.githubusercontent.com/10240614/69840731-83decd80-1297-11ea-8fe8-486641588ef9.png)

效果
![image](https://user-images.githubusercontent.com/10240614/69840775-b12b7b80-1297-11ea-995e-533700be3172.png)

**Comment by chenshuai2144** [comment]
没找到相关页面，你配置了吗？

**Comment by Feather130** [comment]
welcome页配置了
![image](https://user-images.githubusercontent.com/10240614/69854900-41cc8080-12c5-11ea-98a3-61b1f989ded0.png)

**Comment by Fuphoenixes** [comment]
好像是路由里面redirect这个配置失效了

**Comment by chenshuai2144** [comment]
redirect 必须要在 config.js 里面设置，配置再菜单里面是无效的。

**Comment by Miss-violet** [comment]
最后我是这么处理的：
在config.js 里设置好 / 对应的是一个叫 routeRedirect 的组件
在 routeRedirect 里根据后端拿到的菜单再跳转到对应的页面
