### ISSUE TITLE
🧐[问题]pro官网和预览问题

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design-pro#5674]
### 🧐 问题描述
![pro](https://user-images.githubusercontent.com/23520283/69845545-007ba700-12ac-11ea-857c-2d4b9a0c6d07.gif)
当访问官网文档，链接中带有定位时，展开/收起菜单页面会跳转到定位
https://pro.ant.design/docs/layout-component-cn#pageheaderwrapper

![image](https://user-images.githubusercontent.com/23520283/69845670-594b3f80-12ac-11ea-86b7-f1f481dfd24c.png)
预览中的区块代码怎么没了呢

**Comment by chenshuai2144** [comment]
@Liu-Ya  推荐使用 umi ui 了https://pro.ant.design/docs/block-cn

在官网仓库提一个 issue 吧，我来跟踪一下
