### ISSUE TITLE
🧐使用 antd pro 如何更好的优化项目

### ISSUE THREAD

**Issue by dm0104x** [ant-design/ant-design-pro#5675]

**Comment by chenshuai2144** [comment]
执行一下 
`   "analyze": "cross-env ANALYZE=1 umi build",`

看一下你打包进去了什么

**Comment by dm0104x** [comment]
> 执行一下
> ` "analyze": "cross-env ANALYZE=1 umi build",`
> 
> 看一下你打包进去了什么
![image](https://user-images.githubusercontent.com/44898730/69853043-cc5eb100-12c0-11ea-973d-61a9210434af.png)
