### ISSUE TITLE
table 设置了 scroll={{ x: 1200 }}，不默认显示滚动条

### ISSUE THREAD

**Issue by WuZheXiao** [ant-design/ant-design-pro#5677]
![image](https://user-images.githubusercontent.com/26809951/69854219-80f9d200-12c3-11ea-9494-1d5b6ad6c147.png)

怎么样才能不让滚动条显示，，达到1200才显示滚动条，，默认不显示

**Comment by chenshuai2144** [comment]
需要 列的宽度超过百分之百
