### ISSUE TITLE
model动态加载

### ISSUE THREAD

**Issue by KingChow1981** [ant-design/ant-design-pro#568]
新增了一个功能页面，页面可以正常显示，但是在新增了model后，从model中取数据时，发现model中的数据不能获取

---component
```
@connect(state => ({
  rule1: state.rule1,
}))
export default class SmsTemplate extends PureComponent {
```
--model rule1.js
```
export default {
  namespace: 'rule1',

  state: {
    loading: true,
  },
```

--nav
```
 {
       name: '短信模板维护',
       path: 'sms-template',
       component: dynamicWrapper(app, ['rule1'], () => import('../routes/Test/SmsTemplate')),
 },
```

在页面中通过this.porps.rule1获取的不是对象，是undefined

**Comment by WhatAKitty** [comment]
```
state: {
    loading: true,
  },
```

没有初始化`rule`变量。

**Comment by KingChow1981** [comment]
我这个是照着TableList功能写的，
export default {
  namespace: 'rule',

  state: {
    data: {
      list: [],
      pagination: {},
    },
    loading: true,
  },
这个里面也没有初始化rule

**Comment by chenshuai2144** [comment]
哥们格式化一下代码把?
![image](https://user-images.githubusercontent.com/8186664/34557021-d5a5d0ce-f173-11e7-946e-0ec0d4471ec3.png)
点一下z这个就好了

**Comment by WhatAKitty** [comment]
@KingChow1981 这个本身就有this.state.rule这个变量

**Comment by KingChow1981** [comment]
那我自己写的model怎么获取值？
我把rule1: state.rule1 改为rule1:state.loading也获取不到loading的值
loading这个值我已经初始化过了
`export default {
  namespace: 'rule1',

  state: {
    loading: true,
  },`

**Comment by afc163** [comment]
可以提供一个可重现的 repo 看看。

**Comment by KingChow1981** [comment]
自己写的model，可以动态加载吗？

**Comment by afc163** [comment]
目前贴出来的代码看不出问题。

**Comment by KingChow1981** [comment]
SmsTemplate.js
`import React, { PureComponent } from 'react';
import { connect } from 'dva';
import { Modal, Table, Card } from 'antd';

import PageHeaderLayout from '../../layouts/PageHeaderLayout';

import styles from './SmsTemplate.less';

@connect(state => ({
  rule1: state,
}))
export default class SmsTemplate extends PureComponent {

  componentDidMount() {
    const { dispatch } = this.props; //const dispatch = this.props.dispatch;
    dispatch({
      type: 'rule1/changeLoading',
      payload: true,
    });
  }

  render() {
    alert(this.props.rule1.loading);
    return (
      <PageHeaderLayout>
        <Card bordered={false}>
          <div className={styles.tableList}>
            ccccc
          </div>
        </Card>
      </PageHeaderLayout>
    );
  }
}
`

rule1.js
`import { queryTemplates } from '../services/api';

export default {
  namespace: 'rule1',

  state: {
    loading: true,
  },

  effects: {
    *fetch({ payload }, { call, put }) {
      yield put({
        type: 'changeLoading',
        payload: true,
      });
    },
  },

  reducer: {
    save(state, action) {
      return {
        ...state,
        data: action.payload,
      };
    },
    changeLoading(state, action) {
      alert('111111');
      return {
        ...state, //扩展运算符
        loading: action.payload,
      };
    },
  },
};
`
目前我在SmsTemplate.js中即获取不到rule1.js中的值，也执行不了rule1.js中的方法，以上是全部代码

**Comment by afc163** [comment]
看上去没问题。。

**Comment by KingChow1981** [comment]
按道理，调用changeLoading方法时，是要alert('111111');但是没有反应，好像model没有注册一样

**Comment by afc163** [comment]
1. 建议学习一下代码格式化 http://segmentfault.com/markdown
2. 提供可以重现可运行的 repository，可以更好的帮助排查问题。

**Comment by KingChow1981** [comment]
自定义的model可以动态注册吗？我这个rule1.js好像没有注册一样，方法也调用不到

**Comment by nvsky** [comment]
我也遇到同样问题，新建model后在reducer里没有注册

**Comment by nvsky** [comment]
![image](https://user-images.githubusercontent.com/8436965/37589447-54b3de9a-2ba0-11e8-99d5-4c975d1417a5.png)
![image](https://user-images.githubusercontent.com/8436965/37589484-69fe862e-2ba0-11e8-95a1-a98049326302.png)

**Comment by nvsky** [comment]
需要在路由里注册数据模型，即namespace
