### ISSUE TITLE
👑 [需求] 编辑页面需要独立一个页面

### ISSUE THREAD

**Issue by eep2019** [ant-design/ant-design-pro#5683]
### 🥰 需求描述

编辑页面内容比较多，需要独立一个页面。我设了一个路由，但是我不想它显示在左边菜单中，要保持左边菜单还是在A页面active状态。

xxxx配置 ----------路由A
xxxx配置编辑页 ---路由B
如果是用hideInMneu，把B隐藏，怎么同时把菜单状态留在A。

**Comment by misumisery** [comment]
怎么实现的呢？我也想知道

**Comment by fanhualei** [comment]
怎么实现的呢？我也想知道
