### ISSUE TITLE
👑 [ant design pro区块的添加模板不会自动将同一个父路由下的子路由文件归档在一个菜单栏下]

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#5684]
#### 页面操作：如下图，我添加两次列表模块在同一个文件夹menu下面

![CB7C46F3-3672-4ec3-A81D-E728AC0B82EF](https://user-images.githubusercontent.com/19780441/69934835-328c4380-150e-11ea-97ad-06705b05e9c4.png)

#### 现象：没有一个统一的menu菜单，然后归档两个子菜单

![image](https://user-images.githubusercontent.com/19780441/69934934-7e3eed00-150e-11ea-8636-969f8748b240.png)

![image](https://user-images.githubusercontent.com/19780441/69934957-88f98200-150e-11ea-97b6-6a304943ec24.png)

#### 期望结果：是否可以和以前版本一样，归档在一起

![image](https://user-images.githubusercontent.com/19780441/69935032-ae868b80-150e-11ea-9be8-5be67ee6a47d.png)

**Comment by alonesmall** [comment]
我也遇到了这个问题，感觉这个菜单的配置真的很难用，也没有说明文档。

**Comment by rodchen-king** [comment]
> 我也遇到了这个问题，感觉这个菜单的配置真的很难用，也没有说明文档。

可能还需要完善而已，挺好的了，相当于ant design pro的cli了，CLI的源代码不知道在哪里找得到
1. 手动修改项目菜单
2. 研究CLI源代码，然后本地打出来命令。

**Comment by rodchen-king** [comment]
> 我也遇到了这个问题，感觉这个菜单的配置真的很难用，也没有说明文档。

遇到这个问题了吗？https://github.com/ant-design/ant-design-pro/issues/5686

**Comment by rodchen-king** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
@rodchen-king 需要一个 /menu 的配置才行，找不到 name 没法生成一个菜单的。
你有好的建议吗？

**Comment by rodchen-king** [comment]
> @rodchen-king 需要一个 /menu 的配置才行，找不到 name 没法生成一个菜单的。
> 你有好的建议吗？

是我的话，可能就去判断路径地址

![image](https://user-images.githubusercontent.com/19780441/70766518-ed330600-1d98-11ea-8a2c-0d54b96923eb.png)

![image](https://user-images.githubusercontent.com/19780441/70766528-f4f2aa80-1d98-11ea-83e1-2c6fdec96985.png)

这里的地址是两级，每一次新增，会去判断是否存在相同的一级地址，有两个相同，则会提出来一个menu

**Comment by chenshuai2144** [comment]
menu 在菜单中的名字应该叫什么？

**Comment by rodchen-king** [comment]
> menu 在菜单中的名字应该叫什么？

![image](https://user-images.githubusercontent.com/19780441/70773500-9afede80-1db2-11ea-9d92-20de63571bc3.png)

绿色框里的名称，因为区块的里操作，会让用户感觉这是一个菜单吧，我用的时候是这样认为的。

**Comment by chenshuai2144** [comment]
这是个英文，你可以先加一个 layout 类型的区块，然后再增加
