### ISSUE TITLE
🧐[问题]如何修改区块获取的资源路径，想使用公司自己的github?哪里有相关介绍吗？

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#5686]
### 🧐 问题描述

[问题]如何修改区块获取的资源路径，想使用公司自己的github?哪里有相关介绍吗？

目前指向：https://gitee.com/ant-design/ant-design-blocks/

**Comment by rodchen-king** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
还没有文档，打算写了

**Comment by rodchen-king** [comment]
> 还没有文档，打算写了

好的，有提纲能提前给一下吗，学习一下。

**Comment by fanhualei** [comment]
祝你好运。
可以尝试升级 umi 版本到最新，并在 config.ts 设置 block.defaultGitUrl 为 'https://gitee.com/ant-design/pro-blocks'。

**Comment by rodchen-king** [comment]
> 祝你好运。
> 可以尝试升级 umi 版本到最新，并在 config.ts 设置 block.defaultGitUrl 为 '[https://gitee.com/ant-design/pro-blocks'。](https://gitee.com/ant-design/pro-blocks'%E3%80%82)

谢谢你的方式，这个一开始就试过了，没用的。还是等官方吧。

**Comment by qiangyongjun918** [comment]
感觉V4 bug太多了，我也遇到这个问题。好像默认的源全是gitee。其实还有很多问题

**Comment by qiangyongjun918** [comment]
gitee 代码五个月之前的，哪敢用，用了发现编译都有问题。搞不懂。希望官方给力一点，谢谢

**Comment by rodchen-king** [comment]
@chenshuai2144 现在有文档了吗

**Comment by talenhao** [comment]
同样的问题，如何设置使用github

**Comment by TrumanDu** [comment]
期待回复

**Comment by szheng3** [comment]
block.defaultGitUrl  v4 无法使用，求解决方法

**Comment by chenshuai2144** [comment]
这个功能已经停止维护了，不推荐使用了
