### ISSUE TITLE
🐛[BUG]运行单测报 .umi/history.js 下的错

### ISSUE THREAD

**Issue by liuxinqiong** [ant-design/ant-design-pro#5689]
### 🐛 bug 描述
运行 `umi test ".test.(js|ts)"` 报如下奇怪的错误
![6C4FC801-037C-4b85-B114-EFF0F6FC3101](https://user-images.githubusercontent.com/20576218/70025577-6469dc80-15d8-11ea-9666-b2e6df851fc6.png)

### 📷 复现步骤
重新运行 `npm create umi` 创建新的 ant-design-pro 项目并没有报错，怀疑是不是 umi 版本问题，于是将项目升级到相同的 `2.12.3` 版本，却依旧报错

### 🏞 期望结果
正确运行单测

### 💻 复现代码
暂无法提供

### © 版本信息

- Ant Design Pro 版本: 2.3.2
- umi 版本: 2.12.3
- 浏览器环境: chrome
- 开发环境 [e.g. mac OS]: windows 10

**Comment by chenshuai2144** [comment]
jest 测试的时候需要放进去 jsdom，不然会找不到 window 对象
