### ISSUE TITLE
从 mock 直接切换到服务端请求 无效

### ISSUE THREAD

**Issue by jayguojianhai** [ant-design/ant-design-pro#569]
从 mock 直接切换到服务端请求#
通常来讲只要 mock 的接口和真实的服务端接口保持一致，那么只需要重定向 mock 到对应的服务端接口即可。
// .roadhogrc.mock.js
export default {
  'GET /api/(.*)': 'https://your.server.com/api/',
};
这样你浏览器里这样的接口 http://localhost:8001/api/applications 会被转发到 https://your.server.com/api/applications 下。
以上是官网的文档 我按照文档方法设置无效
![image](https://user-images.githubusercontent.com/15603321/34555804-b20b7240-f16e-11e7-9ffa-a2f6065e8374.png)

![image](https://user-images.githubusercontent.com/15603321/34555793-a1179afe-f16e-11e7-9a37-be7882aee3aa.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/194#issuecomment-346021302
