### ISSUE TITLE
🧐我们可以支持对部分页面的预渲染吗？

### ISSUE THREAD

**Issue by mathcw** [ant-design/ant-design-pro#5692]
### 🧐 问题描述

我的一个SPA 存在一部分需要 SEO 的重要静态页面，并不需要做整站 SSR。
想使用umijs的plugin-prerender 看看能不能满足我的需求 但集成后 构建报错

期望：
可以提供一个预渲染的示例不  或者帮忙想想做预渲染的解决方案

### 💻 示例代码
相关配置如下:
  [
    '@umijs/plugin-prerender',
    {
      exclude:[]
    }
  ],
  ssr:true

### 🚑 其他信息

<img width="554" alt="截屏2019-12-03下午3 06 26" src="https://user-images.githubusercontent.com/11343266/70028106-bc0b4680-15de-11ea-8899-bd621ef4096b.png">

**Comment by AttackXiaoJinJin** [comment]
楼主有解决吗？

**Comment by mathcw** [comment]
> 楼主有解决吗？

抱歉 没有 你可以去尝试一下https://umijs.org/zh-CN/config#ssr-32 umi配置一下再看看 
我后来放弃这个对部分页面进行ssr的想法

**Comment by mathcw** [comment]
因为对于中台来说 需要预览的页面不是很多 主要是一些展示性的页面 所以我就总结了一下
然后用nextjs 单独做了个项目
