### ISSUE TITLE
🐛[BUG] 个人设置页面打开报错

### ISSUE THREAD

**Issue by yeojongki** [ant-design/ant-design-pro#5696]
### 🐛 bug 描述

官方预览网站页面 **个人设置** 打开报错 一片空白
![image](https://user-images.githubusercontent.com/21023676/70069285-7aa18800-162c-11ea-98f3-0769c5881a4c.png)

### 📷 复现步骤

打开预览网站 -> 个人页 -> 个人设置

### 🏞 期望结果

正常显示页面

**Comment by afc163** [comment]
试试隐身模式。

**Comment by yeojongki** [comment]
> 试试隐身模式。

一样的报错 你们那边不能复现? @afc163

**Comment by chenshuai2144** [comment]
@yeojongki  我复现了，是因为 observe 的问题，我来修改一下
