### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by KimGuBa** [ant-design/ant-design-pro#5698]
### 🐛 bug 描述
**右侧设置主题颜色出不来**

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5710
要写标题呀 大佬
