### ISSUE TITLE
nginx部署的时候不是根文件，刷新404🧐[问题]

### ISSUE THREAD

**Issue by Tiny-1985** [ant-design/ant-design-pro#5699]
### 🧐 问题描述
nginx部署的时候有4个前端项目，当进入其中一个的login登录的时候，F5刷新就报nginx404，进入首页也是，一个没有路由的首页，刷新也是404，但点击路由页面后，再刷新就没有问题了，

**Comment by Liqiankun** [comment]
@Tiny-1985 这个问题怎么解决的？

**Comment by gx200918** [comment]
@Tiny-1985 请问这个问题解决了ma

**Comment by HQ1363** [comment]
我遇到一个前端路由不生效问题，必须访问 根路由，子路由必须带后缀/ 才可以正常打开页面，否则前端路由无法正常识别
