### ISSUE TITLE
ant design pro 中引用sortablejs，但无法解析这个插件

### ISSUE THREAD

**Issue by zrongrong** [ant-design/ant-design-pro#5701]
ant design pro 中引用sortablejs，但无法解析这个插件
代码：

```
import Sortable from 'react-sortablejs';
render() {
  const listItems = items.map(
      val => (<li
        key={val} data-id={val}>List Item: {val}</li>),
    );
  return (
    <Sortable
        options={{
          group: 'shared',
        }}
        tag="ul"
   >
        {listItems}
    </Sortable>
  )
}

````
问题：
页面报错 `./src/pages/auditSubsystem/specialDiseaseRecord/specialDiseaseRecordRecheck/components/SpecialDiseaseRecordRecheckSearch.tsx`
Module not found: Can't resolve 'react-sortablejs'

**Comment by z-lionel** [comment]
重新运行下看看

**Comment by zrongrong** [comment]
项目是typescript的项目，重新运行也不行

**Comment by chenshuai2144** [comment]
你这个包 react-sortablejs 依赖安装了吗？

**Comment by zrongrong** [comment]
react-sortablejs 安装了

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
----
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
