### ISSUE TITLE
默认fixSiderbar失效, 一直是固定的状态

### ISSUE THREAD

**Issue by Imhemers** [ant-design/ant-design-pro#5702]
Ant Design Pro 4.0.0 我把pro-layout升级到4.9.2之后 fixSiderbar失效, 一直是固定的状态

![image](https://user-images.githubusercontent.com/18650947/70135537-331b0a80-16c5-11ea-92d9-924db1904368.png)

![image](https://user-images.githubusercontent.com/18650947/70135564-44641700-16c5-11ea-8163-52fe78e99117.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重新刷新试试呢，我这里看起来是ok的

**Comment by gb-6k-house** [comment]
遇到同样的问题，请求有解决？
