### ISSUE TITLE
🧐[问题]项目安装完启动后会报错，是什么原因呢

### ISSUE THREAD

**Issue by liyi563257046** [ant-design/ant-design-pro#5704]
<img width="890" alt="微信图片_20191205164902" src="https://user-images.githubusercontent.com/55487917/70219084-2a870a80-177f-11ea-9739-1849ea9e98b1.png">

**Comment by liyi563257046** [comment]
npm start启动后，默认页面是空白的，我手动输入进入user/login就会报上图的错误

**Comment by LuffySu** [comment]
我也碰到了，之前拉的没有问题，最新下的就会出现这个错误。查 是因为本地浏览器版本不支持 fromEntries，需要CH77版本以上，https://kangax.github.io/compat-table/es2016plus/

但是我们公司，CH版本有控制，那是不是说不能玩了？

**Comment by LuffySu** [comment]
经高人指点，处理方法如下：
 1、 将浏览器版本升级。
 2、浏览器不升级的话，只能 将 @ant-design/pro-layout  版本降下来，我使用最低的 4.8.3, 重新启动，就好了。

**Comment by mankeheaven** [comment]
fromEntries这个是es2019的，很多浏览器不支持，我企图改ts的target为es5都不行。
但是降pro-layout这个不应该是编译antd的时候antd发布es支持程度的吗，es的应该尽量低吧？不然很多项目怎么做兼容？手动降某个用了新语法的包的版本？

**Comment by mankeheaven** [comment]
@LuffySu  这玩意不治本啊。应该在编译antd的时候往低的es编译

**Comment by chenshuai2144** [comment]
fixed  in https://github.com/ant-design/ant-design-pro-layout/commit/4f2a368cbdf309ec1b2b2a0413380de6105bb053

**Comment by lxw-bfw** [comment]
有没有什么最新的解决方案，只能降低版本吗
