### ISSUE TITLE
🐛[BUG] ie11打开官网是空白的

### ISSUE THREAD

**Issue by katherinewei** [ant-design/ant-design-pro#5705]
### 🐛 bug 描述
https://preview.pro.ant.design/  这个我用ie,360极速浏览器打开是一片空白，是不是不支持啊？

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [win]

**Comment by chenshuai2144** [comment]
360极速浏览器 是 ie，可以试试兼容模式。

**Comment by chenshuai2144** [comment]
和这个有关

**Comment by GloriaCHL** [comment]
> 360极速浏览器 是 ie，可以试试兼容模式。

是否可以理解为不支持Ie系列？
