### ISSUE TITLE
线上打包，拉不下来antd，并且提示cross-env 不是一个命令 请问是什么问题🧐[问题]

### ISSUE THREAD

**Issue by GrowingMonkey** [ant-design/ant-design-pro#5707]
Jenkins！打包命令
echo $PATH
node -v
npm -v
pwd

 
#npm set registry https://registry.npm.taobao.org
#npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver
#npm install chromedriver
#npm install -g npm
#npm install --registry=https://registry.npm.taobao.org
npm install -g cnpm --registry=https://registry.npm.taobao.org

npm run build:aiyu 
cd dist
rm -rf dist.tar.gz
tar -zcvf dist.tar.gz *

pwd
打包日志文件
[2019-12-06T03_27_58_314Z-debug.log](https://github.com/ant-design/ant-design-pro/files/3930309/2019-12-06T03_27_58_314Z-debug.log)

jekens关键日志
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN tarball tarball data for antd@^3.13.0 (sha1-CmpD/dhXfmFwiTK3vDS6AjTQ8Tg=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for antd@^3.13.0 (sha1-CmpD/dhXfmFwiTK3vDS6AjTQ8Tg=) seems to be corrupted. Trying one more time.
npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-umi@1.6.0 requires a peer of eslint-plugin-react-hooks@1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/eslint-plugin@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of @typescript-eslint/parser@2.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint@6.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@5.0.2 requires a peer of eslint-plugin-flowtype@3.x but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of @typescript-eslint/parser@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-import@^2.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-react@^7.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-dva-hmr@0.4.2 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
npm WARN dva-immer@0.4.5 requires a peer of dva@^2.5.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN dva-loading@3.0.6 requires a peer of dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN connected-react-router@6.5.2 requires a peer of react-redux@^6.0.0 || ^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-babel@4.3.3 requires a peer of rollup@>=0.60.0 <2 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-commonjs@9.3.4 requires a peer of rollup@>=0.56.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting antd@^3.13.0:
npm ERR! Verification failed while extracting antd@^3.13.0:
npm ERR! sha1-CmpD/dhXfmFwiTK3vDS6AjTQ8Tg= integrity checksum failed when using sha1: wanted sha1-CmpD/dhXfmFwiTK3vDS6AjTQ8Tg= but got sha512-wOL6dLX6TTcVoGSkmHequtLtiAewZx8v+o/u01U6O+OCH1WRh/W8Uhwiy4/HURzS25dAovyAF1XMd4oHn7t68Q== sha1-4CrTS2kbAGtXEXFiQK3++X99MYM=. (9549061 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-06T03_04_43_368Z-debug.log
Build step 'Execute shell' marked build as failure
SSH: Connecting from host [aiyu-ios]
SSH: Connecting with configuration [releaseServer] ...
SSH: EXEC: STDOUT/STDERR from command [cd /opt/jenkins/data/web_aiyu_admin
rm -rf dist
mkdir dist
tar -zxvf dist.tar.gz -C dist/
] ...
tar (child): dist.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
SSH: EXEC: completed after 200 ms
SSH: Disconnecting configuration [releaseServer] ...
ERROR: Exception when publishing, exception message [Exec exit status not zero. Status [2]]
Finished: FAILURE

package命令

![image](https://user-images.githubusercontent.com/24692542/70294260-e1d25e80-181d-11ea-9fe2-d1b127b8e762.png)

烦请各位同僚解答下，本地我能打包  ，jekens不行  香港的服务器，国内的可以

**Comment by chenshuai2144** [comment]
你需要先安装依赖，试试 `tyarn`，国内网络不是很稳定。
