### ISSUE TITLE
🧐[问题]windows下安装使用antd-pro 运行时报错

### ISSUE THREAD

**Issue by sundengbing** [ant-design/ant-design-pro#5708]
### 🧐 问题描述
windows下新安装ant-design-pro，运行时报错

![image](https://user-images.githubusercontent.com/58584631/70301323-0259e300-1835-11ea-8636-4561b0079e2a.png)

操作系统:windows7 64位
安装的包版本：
![image](https://user-images.githubusercontent.com/58584631/70301166-98413e00-1834-11ea-83e8-bbbdaafe4589.png)

**Comment by chenshuai2144** [comment]
你这是 ie 浏览器吗？intl的一个 api 没有兼容

**Comment by chenshuai2144** [comment]
尝试更新一下依赖，并且配置 target 为 ie11 ，我用默认的脚手架在ie下 通过了测试
