### ISSUE TITLE
How does the dark theme work?

### ISSUE THREAD

**Issue by veeral-patel** [ant-design/ant-design-pro#5709]
Hi - I'm trying to understand how you've implemented the dark theme into Ant Design Pro. Any pointers would be greatly appreciated!

Thank you!

**Comment by chenshuai2144** [comment]
you need  this [code](https://github.com/ant-design/ant-design-pro/blob/1449dca6ced9e83974ba5c09ff8e3e5bbcd4a225/config/config.ts#L68)

doc in here  https://pro.ant.design/docs/dynamic-theme

**Comment by veeral-patel** [comment]
@chenshuai2144 Thank you! I'm using create-react-app at the moment; should these instructions work with it?
