### ISSUE TITLE
默认端口是8000，如何设置成3000，按照dva-cli方法报错

### ISSUE THREAD

**Issue by wdao7** [ant-design/ant-design-pro#571]
![01](https://user-images.githubusercontent.com/34474826/34556096-f81c434e-f16f-11e7-85d9-ab1d91ccab70.png)

**Comment by ryltcsjg** [comment]
package.json中 npm start改为
"start": "set port=3016 && roadhog server",

**Comment by wdao7** [comment]
谢谢了，自己理解错了文档的意思了

**Comment by wdao7** [comment]
谢谢了，自己理解错了文档的意思了 @ryltcsjg
