### ISSUE TITLE
ant design pro v4 如何加载SettingDrawer

### ISSUE THREAD

**Issue by whaty** [ant-design/ant-design-pro#5710]
### 🥰 需求描述

ant design pro v4 如何加载SettingDrawer？

按照官网的方式启动之后，右侧没有设置按钮，怎么弄出来,求你们别给我发链接，尤其是直接转到官网的连接，我都看了，上面没说咋弄出来?

![image](https://user-images.githubusercontent.com/26294919/70320400-9476e100-185f-11ea-9f1e-a8f7bfd6d561.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/layout-component-cn
![image](https://user-images.githubusercontent.com/8186664/70414873-4697ee00-1a96-11ea-8c36-0818c8206881.png)
？？？？
