### ISSUE TITLE
🧐[问题]SettingDrawer在目前版本中如何使用

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design-pro#5711]
### 🧐 问题描述
SettingDrawer组件不能改变主题色，只能改变布局

我目前升级了最新版本的代码。我发现在SettingDrawer的主题色选择项只有默认的拂晓蓝，其他的条目看不到。但是themePluginConfig中默认配置了大量的主题色。
这些主题色该如何展示到SettingDrawer中。我在themePluginConfig文件中增加主题色的话应该遵循什么样的规则呢。我看到里面的颜色都有两种配置项（以包含theme属性为区分）
原来的defaultSettings中的primaryColor也已经不管用了，那我应该如何通过settingDrawer去处理呢
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39861054/70344279-43cdab00-1894-11ea-9429-83428e79a16e.png)

**Comment by chenshuai2144** [comment]
可以看这两个文档
[动态主题](https://pro.ant.design/docs/dynamic-theme-cn)
[settingdrawer](https://pro.ant.design/docs/layout-component-cn#settingdrawer)
