### ISSUE TITLE
🐛[BUG]BasicLayout组件的高度不能自动铺满

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design-pro#5712]
### 🐛 bug 描述
在内容不够长的时候，会导致页面底部大量留白

我发现root的高度能够达到100%，但是basicLayout的高度却不行，总是差了一点。这个一点是由内容区的高度决定的。
如果内容太少，则整个BasicLayout的高度就无法铺满

### 📷 复现步骤
新建一个脚手架Antd Pro项目，随便写个页面，内容不要太多
然后运行浏览写好的页面就可以

### 🏞 期望结果
BasicLayout高度能够铺满整个浏览器

但是实际高度只延伸到内容区和菜单区的高度
### 💻 复现代码

js
import React from 'react';
import { Card } from 'antd';
import router from 'umi/router';
import { formatMessage } from 'umi-plugin-react/locale';

import IconFont from '@/components/IconFont';

import styles from './welcome.less';

const { Grid } = Card;

const gridData: any = [
  { name: 'structure', path: '/structure/zang', desc: 'JIEGOUGUANLI', icon: 'icon-jiegouguanli' },
  { name: 'text', path: '/text', desc: 'WENGAO', icon: 'icon-wengao' },
  { name: 'image', path: '/image/classic', desc: 'TUPIAN', icon: 'icon-tupian' },
];

const link = (path: string) => {
  router.push(path);
};

const renderGrid = (data: any) =>
  data.map((value: any) => (
    <Grid key={value.path} className={styles.gridItem}>
      <div
        onClick={() => {
          link(value.path);
        }}
        className={styles.itemView}
      >
        <div className={styles.iconView}>
          <IconFont type={value.icon} />
        </div>
        <div className={styles.descView}>
          <div>{formatMessage({ id: `menu.${value.name}` })}</div>
          <div className={styles.desc2}>{`${value.desc}GUANLI`}</div>
        </div>
      </div>
      <div className={styles.iconBgView}>
        <IconFont className={styles.iconBg} type={value.icon} />
      </div>
    </Grid>
  ));

export default (): React.ReactNode => (
  <div className={styles.main}>
    <div className={styles.sign}>欢迎后台管理系统</div>
    <div className={styles.gridView}>
      <Card>{renderGrid(gridData)}</Card>
    </div>
  </div>
);

css
.main {
  .sign {
    width: 100%;
    color: rgba(255, 255, 255, 1);
    font-weight: bold;
    font-size: 42px;
    line-height: 270px;
    text-align: center;
    background: url('https://xxx/houtai/welcome.png') center center no-repeat;
    background-size: 100%;
    opacity: 1;
  }

  .gridView {
    margin-top: 24px;

    .gridItem {
      width: 25%;
      height: 210px;
      padding: 56px 0 0 44px;
      font-weight: bold;
      font-size: 28px;

      .itemView {
        display: inline-block;
        width: 55%;
        vertical-align: top;
        cursor: pointer;

        .iconView {
          display: inline-block;
          height: 80px;
          vertical-align: top;
        }
        .descView {
          display: inline-block;
          height: 40px;
          margin-left: 4px;

          .desc2 {
            color: rgba(215, 215, 215, 1);
            font-size: 14px;
          }
        }
      }

      .iconBgView {
        display: inline-block;
        box-sizing: border-box;
        width: 45%;
        height: 100%;
        overflow: hidden;

        .iconBg {
          width: 240px;
          margin-top: -12px;
          font-size: 210px;
          opacity: 0.35;
        }
      }
    }
  }
}

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.12.5
- 浏览器环境 Chrome 78
- 开发环境 [e.g. mac OS] Win10

### 🚑 其他信息
我在脚手架提供的默认欢迎页看到一切正常，但是其他页面就不行，高度就无法自动铺满
我需要在global.less中添加这么一段样式代码，才能够让页面正常显示
.ant-pro-basicLayout {
  height: 100% !important;
}

![image](https://user-images.githubusercontent.com/39861054/70346616-ad03ed00-1899-11ea-9f15-d947dcdf89e3.png)

![image](https://user-images.githubusercontent.com/39861054/70347992-adea4e00-189c-11ea-8806-196b673adcdc.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/c9ab42bec5bb9c8ea57369bf93a0705bd6abd185/src/global.less#L27

看看这个代码。 layout 现在不会自带高度导致的。

**Comment by MarxZhou** [comment]
> https://github.com/ant-design/ant-design-pro/blob/c9ab42bec5bb9c8ea57369bf93a0705bd6abd185/src/global.less#L27
> 
> 看看这个代码。 layout 现在不会自带高度导致的。

我发现在antd pro的仓库中这个样式是存在的，但是我强两天使用脚手架创建的项目中却不存在这两句样式。
可是我刚刚使用脚手架新建的项目时候这两句样式又出来了。。。。。。。
