### ISSUE TITLE
打开登陆界面很慢

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#5713]
### 🧐 问题描述
打开登陆界面速度很慢，具体看图，家在信息在里面。。网站是 [：](https://ksbg8.cn/system/login/index)
 

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/8272614/70368426-0e9d7900-18e5-11ea-96a2-f72c64a2f91a.png)

**Comment by chenshuai2144** [comment]
加载一次就好了，我们部署在github pages。因为众所周知的原因，速度不是很快。
可以看这个文章
https://pro.ant.design/blog/deploy-pro-cn

**Comment by xgj1988** [comment]
@chenshuai2144  关键是我部署在生产环境月很慢。 。 地址是 https://ksbg8.cn。我知道加载一次就好了。但是客户问到我，我不好解释啊。。

**Comment by xgj1988** [comment]
没人了？
