### ISSUE TITLE
真的好想骂街，一直相信阿里，开源个东西文档太不靠谱

### ISSUE THREAD

**Issue by whaty** [ant-design/ant-design-pro#5715]
好不容易把v4部署完了，看起来效果又和官网演示的不一样，烦死了！！！

官网如下：
![image](https://user-images.githubusercontent.com/26294919/70370335-0c491800-1901-11ea-8caf-de5853386cde.png)

自己的如下：
![image](https://user-images.githubusercontent.com/26294919/70370341-1703ad00-1901-11ea-8856-27afe882b23f.png)

少这么多细节，烦死了

**Comment by whaty** [comment]
就不能保证演示版，和你官网的教程弄出来的效果一样吗？让我们东改西改，有意思吗？

**Comment by fanhualei** [comment]
淡定淡定，antdpro做的还是听不错的

**Comment by afc163** [comment]
Duplicate of #5711

**Comment by afc163** [comment]
SettingDrawer **只是用于演示和本地调试 pro 的配置**，本身的实现有性能问题，也不是在控制台的产品设计中，不推荐在生产环境使用。

**Comment by withwz** [comment]
> SettingDrawer **只是用于演示和本地调试 pro 的配置**，本身的实现有性能问题，也不是在控制台的产品设计中，不推荐在生产环境使用。

嘿嘿，完了，我老板看着好看非让弄这个

**Comment by OriginZero** [comment]
我以为我的姿势不对，主题只有一个....
