### ISSUE TITLE
页面样式无法显示 2.0版本

### ISSUE THREAD

**Issue by h499360594** [ant-design/ant-design-pro#5718]
我的版本是2.0，我通过打包npm run build命令，打包好的文件，放到nginx上，页面一开始不显示，后来发现是#3398 问题，然后按照方法，修改之后可以显示页面了，但是页面却没有样式，我看了下是vendors.chunk.css加载是在页面请求两秒后才加载，所以没有样式，我看了好多说删除dll的，我也试着删除了dll但是并没有效果，请问是什么问题造成的？求大佬指点。

**Comment by chenshuai2144** [comment]
关闭一下 异步就在应该就好了。
只打包一个 js 和 一个 css

**Comment by h499360594** [comment]
> 关闭一下 异步就在应该就好了。
> 只打包一个 js 和 一个 css

好的，我需要在哪里关闭异步？

**Comment by chenshuai2144** [comment]
https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#disabledynamicimport

**Comment by h499360594** [comment]
> https://github.com/sorrycc/roadhog/blob/master/README_zh-cn.md#disabledynamicimport

你好，非常感谢你的回答，我发现我的版本是2.2.0，然后我找到了2.2.0修改这个配置的地方，修改配置如下：
const plugins = [
  [
    'umi-plugin-react',
    {
      antd: true,
      dva: {
        hmr: true,
      },
      locale: {
        enable: true, // default false
        default: 'zh-CN', // default zh-CN
        baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
      },
      // dynamicImport: {
      //   loadingComponent: './components/PageLoading/index',
      //   webpackChunkName: true,
      // },
      pwa: {
        workboxPluginMode: 'InjectManifest',
        workboxOptions: {
          importWorkboxFrom: 'local',
        },
      },
      ...(!process.env.TEST && os.platform() === 'darwin'
        ? {
            dll: {
              include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
              exclude: ['@babel/runtime'],
            },
            hardSource: false,
          }
        : {}),
    },
  ],
];
注调了那部分，我尝试了false没有效果，所以注调之后有了效果。
打包如下：
File sizes after gzip:

  1022.69 KB  dist\umi.js
  52.15 KB    dist\umi.css
  2.39 KB     dist\pwacompat.min.js
内容减少了很多，无法加载的部分css，也打包到了umi.css中，但是，我放到nginx，也清理也浏览器缓存，但是访问网页，还是读取不到css样式，请问我是否还需修改其他内容？

**Comment by chenshuai2144** [comment]
把 dll 也删掉呢
