### ISSUE TITLE
🧐[问题] 三步实现Ant Design Pro 的主题切换

### ISSUE THREAD

**Issue by JerryMissTom** [ant-design/ant-design-pro#5719]
### 🧐 问题描述
最近实现了在线主题切换的需求，此方案适应于V2和V4 版本，也适用于自定义组件。

### 💻 示例代码
具体的过程可以见：https://juejin.im/post/5dede7556fb9a0160b637241 ，
】希望有类似需求的可以参考下

**Comment by chenshuai2144** [comment]
帮我们搞个 pr 吧 加到 site 里面

**Comment by JerryMissTom** [comment]
@chenshuai2144 已经提交了中文版本的PR，英文版本的话，需要迟些了

**Comment by chenshuai2144** [comment]
google 翻译一把梭好了

**Comment by JerryMissTom** [comment]
@chenshuai2144 不辱使命，英文版本的也已经提交了PR

**Comment by birdycn** [comment]
掘金打不开了。。请问怎么实现？ @chenshuai2144

**Comment by JerryMissTom** [comment]
@birdycn 我这儿是可以的呀，你再试试
