### ISSUE TITLE
什么时候会开发treegrid组件？

### ISSUE THREAD

**Issue by arayte** [ant-design/ant-design-pro#572]
做企业富客户端开发经常需要用到treegrid组件，这个有在计划开发吗？有的话什么时候能用

**Comment by chenshuai2144** [comment]
详细描述需求？

**Comment by ryan-che** [comment]
同样需要treegrid，可参考easyui官方的treegrid ，功能很强大。
http://www.jeasyui.com/demo/main/index.php?plugin=TreeGrid&theme=material&dir=ltr&pitem=&sort=


![treegrid](https://user-images.githubusercontent.com/15942427/34595974-257670a6-f217-11e7-8aaa-8c9cf1263813.png)

![treegrid2](https://user-images.githubusercontent.com/15942427/34595977-30e9b43e-f217-11e7-9b56-47b55e98fd50.png)

![treegrid3](https://user-images.githubusercontent.com/15942427/34595979-37d6e9e2-f217-11e7-90e1-b738aab9c84e.png)

**Comment by chenshuai2144** [comment]
去隔壁ant.design问一问吧
