### ISSUE TITLE
配置antd的externals之后，antd还是会被打包进去 🐛[BUG]

### ISSUE THREAD

**Issue by zhaofinger** [ant-design/ant-design-pro#5720]
### 🐛 bug 描述

在`webpack`的配置项中配置`antd`的`externals`选项之后之后，`antd`还是会被打包进去。

### 📷 复现步骤

1. `document.ejs`中引入`antd`的相关cdn如下:
![image](https://user-images.githubusercontent.com/31442077/70422341-89fa5880-1aa6-11ea-9728-45afa2fa7269.png)
2. 在`config/plugin.config.ts`配置`externals`选项如下：
```javascript
  // externals 配置
  config.externals({
    react: 'React',
    'react-dom': 'ReactDOM',
    moment: 'moment',
    antd: 'antd',
  });
```
3. 运行打包分析命令`yarn analyze`之后发现`antd`还是被打包进去了，其他的externals配置项并没有打包进去例如react、react-dom等
![image](https://user-images.githubusercontent.com/31442077/70422679-1147cc00-1aa7-11ea-96d7-b11133218043.png)

### 🏞 期望结果

进行`externals`配置之后`antd`可以不被打包进去。

### © 版本信息

- Ant Design Pro 版本 4.0.0
- umi 版本 2.9.6
- 浏览器环境 Chrome 78.0.3904.108
- 开发环境 mac OS 10.15.1

**Comment by chenshuai2144** [comment]
你好像写错了

https://umijs.org/config/#externals 在 config.js 中

**Comment by zhaofinger** [comment]
@chenshuai2144 配置到config里效果也是一样的，`antd`还是会被打包进去。
另外在`plugin.config.ts`里配置应该也是没问题的，因为react、react-dom都已经生效了。

**Comment by gyf30827** [comment]
这个问题解决了吗？我这里也遇到了

**Comment by gyf30827** [comment]
你应该是配置了按需加载导致引用的方式变了，可以把按需加载代码去掉就可以了
` plugins: [
    [
      "import", { "libraryName": "antd", "style": true }
    ]
  ]`

**Comment by zhaofinger** [comment]
@gyf30827 对，谢谢！移除`antd`的按需加载就可以了，pro里通过`umi-plugin-react`来配置`antd`的按需加载，[文档地址](https://umijs.org/zh/plugin/umi-plugin-react.html#antd)。

**Comment by haobrother** [comment]
Pro V5版本打包也是这样，externals包含了antd: 'window.antd'，scripts包含了对应antd的CDN地址，但是analyze后发现antd还在里面。
另外，全局的按需加载已经被我关了dynamicImport: false
![511605690392_ pic_hd](https://user-images.githubusercontent.com/19492909/99509230-777be500-29c0-11eb-82d6-ad5e21e6b7f9.jpg)

**Comment by pw0621** [comment]
配置react、react-dom externals后直接报错了

**Comment by vinvin1022** [comment]
react-dom externals那里是写错了

**Comment by chenshuai2144** [comment]
也可以这么配置

  externals: {
      react: 'React',
      'react-dom': 'ReactDOM',
      '^/antd/.*': 'antd',
      '^/dayjs/.*': 'dayjs',
    },
