### ISSUE TITLE
🐛[BUG]页脚不在最下面

### ISSUE THREAD

**Issue by zhipingzhang** [ant-design/ant-design-pro#5721]
### 🐛 bug 描述

今天清理缓存，重新install后，发现页脚不保持在页面最下面了

### 📷 复现步骤

清理缓存

### 🏞 期望结果

期望页脚保持在最下面，烦请给出自己修改的方案

### 💻 复现代码

就默认代码
![image](https://user-images.githubusercontent.com/10151383/70427229-4e17c100-1aaf-11ea-9f61-0959a3bdb110.png)
上面是之前的，header,main,footer是平级的
下面是最新的，footer跑到了main里面，导致footer不在最下面
![image](https://user-images.githubusercontent.com/10151383/70427330-7a334200-1aaf-11ea-9f47-82416dea32c0.png)

### © 版本信息

- Ant Design Pro 版本: 4.9.7
- chrome 78.0.3904.108
- windows10

**Comment by zhipingzhang** [comment]
@chengshuai2144 
大神你好，我看这个改动是https://github.com/ant-design/ant-design-pro-layout/commit/da8239d3c57c13690495b7a91b8fbffc14f53bf7 里面做的，现在footer飞上去了，请问有什么办法吗

**Comment by zhipingzhang** [comment]
我直接把BasicLayout.tsx 复制到了项目里，修改了import和那一行代码footer代码，然后项目引用我修改后的

**Comment by chenshuai2144** [comment]
。。。。 你太黑了，你可以把 chidren 撑高。就可以解决问题了

**Comment by zhipingzhang** [comment]
> 。。。。 你太黑了，你可以把 chidren 撑高。就可以解决问题了

```
<Fragment>
        <div style={{ 'min-height': '80vh' }}>
        {init && children}
        </div>
      </Fragment>
```
确实，我把children用个div包起来就行了，不好意思，我刚学前端，谢谢指导
