### ISSUE TITLE
🧐[问题]如何在生产环境改变primaryColor对侧边栏生效？

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design-pro#5725]
如何在生产环境改变primaryColor对侧边栏生效？目前好像只有build后才有效果

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5719
你需要的是这个吧

**Comment by birdycn** [comment]
请问应该怎么解决呢？那个掘金的链接失效 @chenshuai2144
