### ISSUE TITLE
能否增强浏览器支持至少到IE10或9以上呢？👑 [需求]

### ISSUE THREAD

**Issue by yinxiaoling** [ant-design/ant-design-pro#5727]
### 🥰 需求描述
对于一个使用广泛的脚手架浏览器兼容性限制了项目的发展，2C不必说，2B的客户依然大部分停留在IE9/10左右的版本，到IE11的都很少。

另外hooks也可以着手进行重构一部分组件了。

### 🧐 解决方案
babel-polyfill
babel-polyfill-ie

### 🚑 其他信息
兼容性规范说明

我也不想做伸手党，但是想有更加大的发展，浏览器兼容性真的是非常非常重要，如果这方面不行的话会挡住2/3的选型者的脚步。

**Comment by afc163** [comment]
现在的 React 技术栈全家桶做中后台支持 IE 9/10 非常困难，我们没有足够的能力。

**Comment by chenshuai2144** [comment]
https://tongji.baidu.com/research/site

可以提醒客户升级 浏览器了

**Comment by yinxiaoling** [comment]
> 现在的 React 技术栈全家桶做中后台支持 IE 9/10 非常困难，我们没有足够的能力。

好吧，2B的太难了...我们自己更没有能力搞这个兼容性了...

> https://tongji.baidu.com/research/site
> 
> 可以提醒客户升级 浏览器了

2B的太难了...根本没有网络，机器老旧，浏览器IE8 9 10，新技术根本使用不了。期待Chrome 赶紧一统天下...
