### ISSUE TITLE
【求助】antdpro项目中引用npm上自己封装的组件报错🧐[问题]

### ISSUE THREAD

**Issue by JeremyDa** [ant-design/ant-design-pro#5730]
### 🧐 问题描述
对ant design的组件进行了封装，上传到了npm。
antdpro项目中引用npm的组件报错，不知如何解决。

### 💻 示例代码
![image](https://user-images.githubusercontent.com/8288208/70589815-b24f9780-1c0b-11ea-9d1c-ff962ec5bf7e.png)

### 🚑 其他信息
网页上报错信息如下：
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by chenshuai2144** [comment]
导出有问题，你导入的组件是空。。
最好输入一下。建议使用 father 打包。

**Comment by JeremyDa** [comment]
> 导出有问题，你导入的组件是空。。
> 最好输入一下。建议使用 [father](https://github.com/umijs/father) 打包。

使用father打包，封装antd组件，报错如下：
Can't import the named export 'Radio' from non EcmaScript module (only default export is available)
您知道是如何处理吗？

**Comment by chenshuai2144** [comment]
show code
