### ISSUE TITLE
按照官网的教程，下载所有区块时执行npm run fetch:blocks，报错missing

### ISSUE THREAD

**Issue by iceMusic** [ant-design/ant-design-pro#5732]
### 🧐 问题描述
ray:antd-pro-umi-demo ray$ npm run fetch:blocks
npm ERR! missing script: fetch:blocks

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ray/.npm/_logs/2019-12-11T09_02_01_788Z-debug.log

**Comment by chenshuai2144** [comment]
检查一下你的 package.json script

**Comment by iceMusic** [comment]
> 检查一下你的 package.json script

确实是没有，这个要怎么加呢？自动生成的文件里没有

**Comment by chenshuai2144** [comment]
使用umi ui 也很方便的。
