### ISSUE TITLE
路由必须在config中配置吗

### ISSUE THREAD

**Issue by lixiaoshun** [ant-design/ant-design-pro#5733]
### 🧐 问题描述
已经在BasicLayout从后台接口取得菜单数据，也可以显示，但是没有在config.js定义的路径，就还是报404，这个能有办法解决吗，就是不需要在没写一个就去配置

**Comment by chenshuai2144** [comment]
路由决定你要将那些文件编译到你的项目中
和你的本地严格相关的，你没有办法从服务器获得
