### ISSUE TITLE
登录后设置了cookie 但是后续的请求没带全的问题

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5734]
登录可以看到设置了JSESSIONID
![image](https://user-images.githubusercontent.com/47104575/70674174-28153b00-1cc0-11ea-9917-0dd56ca2e0da.png)

且手动设置了一个cookie
![image](https://user-images.githubusercontent.com/47104575/70674201-43804600-1cc0-11ea-9b98-74c354ab4505.png)

为什么后续的请求没有带上这个JSESSIONID
![图片](https://user-images.githubusercontent.com/47104575/70674478-0f595500-1cc1-11ea-989f-9b34ad3dba19.png)

尝试了我不手动设置我自定义的cookie  T.session那个的话  请求也不会带上JSESSIONID
总结就是不会带上set-cookie设置上的JSESSIONID   该如何解决  也设置了credentials: 'include',
![image](https://user-images.githubusercontent.com/47104575/70675998-b809b380-1cc5-11ea-84b3-4beb8c73da97.png)

**Comment by 904492381** [comment]
@chenshuai2144 大佬帮忙看看

**Comment by chenshuai2144** [comment]
跨域了?

**Comment by 904492381** [comment]
> 跨域了?

跨域的话 会出现 JSESSIONID不会带上  登录后手动设置的cookie会带上吗

**Comment by chenshuai2144** [comment]
对的 看一下这个文章
https://pro.ant.design/blog/proxy-cn

**Comment by 904492381** [comment]
> 对的 看一下这个文章
> https://pro.ant.design/blog/proxy-cn

那请问下 我在开发环境的时候 需要跨域的 怎么解决呢

**Comment by 904492381** [comment]
解决了 是cookie的path问题 重写就可以了
