### ISSUE TITLE
🐛[BUG]'SettingDrawer' has already been declared

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#5735]
### 🐛 bug 描述
antdesignpro启动报错

报错如下：
🚀 Starting Umi UI using umi@2.12.5...
⛽️ Ready on http://localhost:3000/
  build [==                  ] 10%Starting the development server...

  build [=================== ] 95%Extracted theme color css content length: 23391
Build completed in 31.691s

 ERROR  Failed to compile with 1 errors                                                                                                                                   9:30:38 AM
 error  in ./src/layouts/BasicLayout.jsx

Syntax Error: SyntaxError: E:\datav\src\layouts\BasicLayout.jsx: Identifier 'SettingDrawer' has already been declared (6:50)

  4 |  * https://github.com/ant-design/ant-design-pro-layout
  5 |  */
> 6 | import ProLayout, { DefaultFooter, SettingDrawer, SettingDrawer } from '@ant-design/pro-layout';
    |                                                   ^
  7 | import React, { useEffect } from 'react';
  8 | import Link from 'umi/link';
  9 | import { connect } from 'dva';

 @ ./src/pages/.umi/router.js 75:15-51
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

### 📷 复现步骤

1.更新下载antdesignpro所有模块
2.启动
### 🏞 期望结果

期望能够正常启动
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.12.5
- 浏览器环境 chorme
- 开发环境 [e.g. mac OS] win10

**Comment by chenshuai2144** [comment]
你代码写错了，不能重复导入

**Comment by suchasplus** [comment]
src/layouts/BasicLayout.tsx

 error  in ./src/layouts/BasicLayout.tsx

Syntax Error: SyntaxError: /Users/who/antd-pro/src/layouts/BasicLayout.tsx: Identifier 'SettingDrawer' has already been declared (12:2)

  10 |   DefaultFooter,
  11 |   SettingDrawer,
> 12 |   SettingDrawer,
     |   ^
  13 | } from '@ant-design/pro-layout';
  14 | import React, { useEffect } from 'react';
  15 | import { Link, useIntl, connect, Dispatch } from 'umi';

直接拉回来的antd-pro， 没做任何改动， npm run start就报错


同样
./src/components/GlobalHeader/RightContent.tsx

   9 | import styles from './index.less';
  10 | import NoticeIconView from './NoticeIconView';
> 11 | import NoticeIconView from './NoticeIconView';
     |        ^
  12 | export type SiderTheme = 'light' | 'dark';
  13 | export interface GlobalHeaderRightProps extends Partial<ConnectProps> {
  14 |   theme?: SiderTheme | 'realDark';

另外
 warning  in ./src/pages/user/register/index.tsx

"export 'router' was not found in 'umi'

 "@ant-design/pro-layout": {
      "version": "5.0.12",

**Comment by chenshuai2144** [comment]
安装的包错了吧。看起来是tsloader不对

**Comment by dongleiw** [comment]
我也遇到了。一年还没修复吗

**Comment by chengzequn** [comment]
> 我也遇到了。一年还没修复吗

检查一下你的代码，可能代码中有重复的代码，我当时更新后它重新又给我更新复制了一遍导致这样的报错。
如果解决了您的问题，请关闭这个问题。谢谢

**Comment by dongleiw** [comment]
> 
> 
> > 我也遇到了。一年还没修复吗
> 
> 检查一下你的代码，可能代码中有重复的代码，我当时更新后它重新又给我更新复制了一遍导致这样的报错。
> 如果解决了您的问题，请关闭这个问题。谢谢

嗯可能是这个问题. 谢谢
