### ISSUE TITLE
🐛[BUG] 框架内部提供的request在IE11上面报错？在IE11上面始终会出现这个弹窗报错。

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design-pro#5736]
![image](https://user-images.githubusercontent.com/23158766/70678995-c27c7b00-1cce-11ea-8adb-1da7b04505ca.png)
![image](https://user-images.githubusercontent.com/23158766/70679031-e93ab180-1cce-11ea-9cb6-9f4a191e3cbf.png)

**Comment by chenshuai2144** [comment]
额 这个应该和 ie11 没有关系的，检查一下你的网络请求

**Comment by wo-de-ping-er** [comment]
> 额 这个应该和 ie11 没有关系的，检查一下你的网络请求

不不不    我检查了我所有的网络请求   都没问题    而且谷歌等浏览器不会有问题   仅仅在IE11上有问题

**Comment by xoptimal** [comment]
dev没问题, build后 Edge 访问不了 ~  @chenshuai2144 
```
TypeError: Object doesn't support property or method 'fromEntries'
Unhandled promise rejection TypeError: Object doesn't support property or method 'fromEntries'
```

pro-version: 4.0.0
edge: Microsoft Edge 44.18362.449.0

**Comment by chenshuai2144** [comment]
@xoptimal 更新下版本，layout 误用了一个新的api，已经修复了。

**Comment by chenshuai2144** [comment]
@wo-de-ping-er  估计是cookie 或者 seesion 导致的。你需要 debug 一下。
preview 在 ie11 下表现还是比较完美的。
