### ISSUE TITLE
请问下proxy代理前面替换的部分能用正则吗

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5737]
![image](https://user-images.githubusercontent.com/47104575/70696267-4f8af880-1cfe-11ea-9351-cfe40b1411f7.png)
现在有/api/和/hr/两个 可能之后还不止  能用正则放到一行上吗  如果可以的话该怎么写 求教

**Comment by chenshuai2144** [comment]
能 就是普通的 js正则 然后 toString。 
可以看这篇文章了解一下底层实现
https://pro.ant.design/blog/proxy-cn

**Comment by 904492381** [comment]
> 能 就是普通的 js正则 然后 toString。
> 可以看这篇文章了解一下底层实现
> https://pro.ant.design/blog/proxy-cn

没太懂  怎么还要toString  能写个例子吗 比如如上图我/api/ 和 /hr/都要替换 该怎么写 谢谢
@chenshuai2144
