### ISSUE TITLE
新创建的应用，@connect报错

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#5739]
通过命令创建一个新的应用时报错
yarn create umi app
![image](https://user-images.githubusercontent.com/33716687/70698996-6aac3700-1d03-11ea-98f6-c7585df0b936.png)

是跟这个有关吗？
![image](https://user-images.githubusercontent.com/33716687/70699169-ad6e0f00-1d03-11ea-80e8-9623c5d337cc.png)

**Comment by chenshuai2144** [comment]
不是的，这看起来是我们的类型没写好造成的。
