### ISSUE TITLE
👑 [需求] Ant Design v4 beta is released.

### ISSUE THREAD

**Issue by tranducit95** [ant-design/ant-design-pro#5740]
### 🥰 需求描述
When does Ant Design Pro apply Ant Design v4?
For a new project, should I use Ant Design v4 right away?

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/issues/5717 and https://github.com/ant-design/ant-design-pro/pull/5716.
please  wait some time.
