### ISSUE TITLE
🧐[问题]中后台的umi项目,编译后,谷歌,idge打开都没问题,IE(用的是IE9,业务需要兼容至IE9),结果保错

### ISSUE THREAD

**Issue by wangShengCool** [ant-design/ant-design-pro#5743]
### 🧐 问题描述

中后台的umi项目,编译后,谷歌,idge打开都没问题,IE(用的是IE9,业务需要兼容至IE9),结果保错

### 💻 示例代码

发现项目打包部署后,也会出现这个问题,目前怀疑是不是项目里用到了ie不兼容的第三方库导致的,求大神告知,解决方法!!

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38369701/70761952-ebae1180-1d89-11ea-9106-3bba7f6e8d26.png)
![image](https://user-images.githubusercontent.com/38369701/70762035-2d3ebc80-1d8a-11ea-8418-78fb590a4af2.png)

![image](https://user-images.githubusercontent.com/38369701/70762112-7131c180-1d8a-11ea-85c4-61414a7b7f44.png)

**Comment by wangShengCool** [comment]
who can help me 呀

**Comment by wangShengCool** [comment]
西湖区的大佬,们,快来啊

**Comment by chenshuai2144** [comment]
ie9 是不行的。
大部分库都不兼容。你可能需要付出很多的努力

**Comment by wangShengCool** [comment]
> ie9是不行的。
> 大部分库都不兼容。你可能需要付出很多的努力

你看我那个报错,我分析的对不

**Comment by chenshuai2144** [comment]
@wangShengCool  关闭一下 
```
   dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      },
```

**Comment by wangShengCool** [comment]
> @wangShengCool 关闭一下
> 
> ```
>    dynamicImport: {
>         loadingComponent: './components/PageLoading/index',
>         webpackChunkName: true,
>         level: 3,
>       },
> ```

关掉了,好像没起作用,跟之前一样

**Comment by chenshuai2144** [comment]
删掉这个配置，能解决部分问题

**Comment by wangShengCool** [comment]
> 删掉这个配置，能解决部分问题

之前一个项目也是umi开发,ie9并没有问题,我就搞不明白这出错的原因是什么,我不是切换路由的时候而是项目初始化时候就保这个错

**Comment by ithss** [comment]
我也是, 本地都可以编译通过, 正常在ie运行, 但是上了服务器之后却有未转换的语法,类似模板字符串这种, 导致报错, 这表明两种环境下打的包一定是不一样的,  但又找不到原因,  真是服了, 要吐了
