### ISSUE TITLE
🐛[BUG]打开config.ts中的如下注释会使global.less中定义的样式失效

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design-pro#5744]
### 🐛 bug 描述
打开config.ts中的如下注释会使global.less中定义的样式失效
```javascript
      // dynamicImport: {
      //   loadingComponent: './components/PageLoading/index',
      //   webpackChunkName: true,
      //   level: 3,
      // },
```

### 📷 复现步骤

打开config.ts中的如下注释

### 🏞 期望结果

不覆盖

### © 版本信息

全部最新 
### 🚑 其他信息

**Comment by chenshuai2144** [comment]
脚手架看起来是 ok 的

**Comment by pkaq** [comment]
![QQ截图20191213112847](https://user-images.githubusercontent.com/4537450/70767311-ca562100-1d9b-11ea-9b72-8383bdae4a81.png)
主要是覆盖部分的样式失效

**Comment by chenshuai2144** [comment]
你要提升一下 css 的优先级。你的优先级太低了
