### ISSUE TITLE
请问BasciLayout左上角logo部分能不能和菜单收缩按钮调换位置？如图

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5748]
![F886A31F-5E94-4F85-83C0-3617018C39E7](https://user-images.githubusercontent.com/47104575/70791822-cf829280-1dd2-11ea-8d0e-00a23be173e9.jpeg)
现在的布局是左右两部分，收缩菜单的时候，logo右边的字就会不见了，我想让按钮在左边，logo和文字在右边，就不会被遮挡了，怎么实现呢 我是v4

**Comment by chenshuai2144** [comment]
试试这个 api 

collapsedButtonRender | custom collapsed button method | (collapsed: boolean) => ReactNode | -
-- | -- | -- | --

**Comment by 904492381** [comment]
> 试试这个 api
> 
> collapsedButtonRender	custom collapsed button method	(collapsed: boolean) => ReactNode	-

这个好像只能改样式  不能改位置吧

**Comment by chenshuai2144** [comment]
返回一个dom，什么都能干的

**Comment by xiaoxiong113** [comment]
v5 的怎么改

**Comment by xiaoxiong113** [comment]
这个只能改内容，上面说的位置怎么跟logo去换？

**Comment by chenshuai2144** [comment]
用第一个第三方变量交换一下。。
不过不推荐这么搞，搞微创新会留很麻烦的坑
