### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design-pro#5749]
### 🐛 bug 描述

PageHeaderWrapper组件没有给className定义类型，所以一直有条红线
![image](https://user-images.githubusercontent.com/19385704/70793238-d232b700-1dd5-11ea-80aa-a35776e1f3f6.png)

![image](https://user-images.githubusercontent.com/19385704/70793161-b3342500-1dd5-11ea-8438-557f42873b1d.png)

### 🏞 期望结果

期望官方添加定义

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 [e.g. 2.12.4]
- 浏览器环境 [e.g. chrome]
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
来个 PR

**Comment by chenshuai2144** [comment]
在 layout 中已经有了
