### ISSUE TITLE
权限演示

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design-pro#575]
- [ ]  增加一个演示权限的页面
- [ ]  扩展一个页面用于动态修改当前用户权限
- [ ]  权限控制菜单显示
- [ ] 权限控制路由导向
- [ ] 权限控制页面元素显示
- [ ] 权限字符串、表达式、promise等形式演示

**Comment by chenshuai2144** [comment]
强行给你改了改.
最好支持动态的修改权限.

**Comment by afc163** [comment]
目前做成文档就好了。

这块演示权限的定制，后续和主题、国际化、布局一起做到一个右侧展开的 drawer 里去。

cc @ddcat1115

**Comment by WhatAKitty** [comment]
Ok，那这个下次再说。先放着了。

**Comment by williamwang2015** [comment]
想知道这个权限管理的，如果我的菜单内容要在用户登录成功后从服务端拉取怎么实现?

**Comment by wuzehao16** [comment]
急需一个动态修改当前用户权限的页面

**Comment by FrankGuos** [comment]
这个权限管理做的真是时候，省下我不少时间，ths，可惜刚一打开就有bug。

**Comment by gebilaoman** [comment]
都要开始做权限了，感觉要偏了……

**Comment by xoptimal** [comment]
@warmhug  文档在哪里~

**Comment by ddcat1115** [comment]
@xoptimal  今天或者明天会补充上来

**Comment by xoptimal** [comment]
@ddcat1115   现在创建的项目, 最新的, 登录这边异常,  导致查看不了权限 ...   能尽可能今天补充上来吗~

**Comment by chenshuai2144** [comment]
@xoptimal  clone matser  已经修复了

**Comment by ddcat1115** [comment]
[权限文档](https://github.com/ant-design/ant-design-pro-site/blob/master/docs/authority-management.md)

[权限组件文档](https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/index.md)

**Comment by laosandegudai** [comment]
mock数据，强行清掉本地Storage权限刷新后，路由的权限无法控制畅通无阻，路由的激活时的验证不知道咋搞了。

**Comment by chenshuai2144** [comment]
@ddcat1115  重定向这块是不是改一改？
如果一个人没有任何权限。。应该跳转到主页吧。现在会重定向无限次。

**Comment by spiritree** [comment]
@chenshuai2144 
我现在的状况就是/和/user/login两个重定向无限次直到报错
能指导下怎么解决吗 谢谢

**Comment by chenshuai2144** [comment]
把login的权限去掉就好了

**Comment by chenshuai2144** [comment]
关了吧。。。 需要做的时候重新打开
