### ISSUE TITLE
可否从V1直接升级到V4

### ISSUE THREAD

**Issue by jhyy1986** [ant-design/ant-design-pro#5753]
我目前还在使用V1，随着页面越来越多，产生的问题也挺多的，想直接升级到V4，我看官网上只有V2升级V4的文档，可以直接从V1升级到V4吗？

**Comment by chenshuai2144** [comment]
可以的，不过 roadhog 迁移到 umi 的改动非常大。劳动强度比较大

https://v2-pro.ant.design/docs/upgrade-v2-cn

**Comment by jhyy1986** [comment]
好的，谢谢，我再研究下文档。

**Comment by jhyy1986** [comment]
> 
> 
> 可以的，不过 roadhog 迁移到 umi 的改动非常大。劳动强度比较大
> 
> https://v2-pro.ant.design/docs/upgrade-v2-cn

好的，谢谢，我再研究下文档。
