### ISSUE TITLE
🐛[BUG]UMI UI下修改umi-plugin-react 配置,关掉国际化方案,保存后重启项目,页面空白!!!

### ISSUE THREAD

**Issue by codetown** [ant-design/ant-design-pro#5754]
### 🐛 bug 描述

UMI UI下修改umi-plugin-react 配置,关掉国际化方案,保存后重启项目,页面空白!!!
### 📷 复现步骤
UMI UI下修改umi-plugin-react 配置,关掉国际化方案,保存后重启项目,页面空白!!!

UMI UI下修改umi-plugin-react 配置,关掉国际化方案,保存后重启项目,页面空白!!!
### 🏞 期望结果
UMI UI下修改umi-plugin-react 配置,关掉国际化方案,保存后重启项目,页面正常显示,并且右上角的语言选择菜单消失

UMI UI下修改umi-plugin-react 配置,关掉国际化方案,保存后重启项目,页面正常显示,并且右上角的语言选择菜单消失
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/i18n-cn#%E5%88%A0%E9%99%A4%E5%85%A8%E7%90%83%E5%8C%96
跟着这个来吧
