### ISSUE TITLE
v4安装出现很多warning

### ISSUE THREAD

**Issue by liuwei9413** [ant-design/ant-design-pro#5755]
### 🧐 安装antd-design-pro v4 版本出现很多warning

yarn 和 npm 两种方式都尝试过了，都有提示升级的warning

### 🚑 其他信息

![yarn-w](https://user-images.githubusercontent.com/13143368/70842929-eeca0000-1e64-11ea-8ce8-cc6d80150a29.png)
![WX20191214-111930](https://user-images.githubusercontent.com/13143368/70842930-ef629680-1e64-11ea-9621-1e66af129608.png)

**Comment by liuwei9413** [comment]
umi:2.12.2   npm:6.13.2  nodejs:v10.17.0   yarn:v1.12.1
求教大神，有没有好的解决方案？

**Comment by chenshuai2144** [comment]
npm 的 warning 忽略就好了。这是由生态决定的
