### ISSUE TITLE
menu如何完全收起🧐[问题]

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design-pro#5759]
### 🧐 问题描述
@menu-collapsed-width: 80px; 设置为0px后还是会留有一部份，请问如何完全收起菜单？

**Comment by chenshuai2144** [comment]
可以看着这个 demo 

https://prolayout.ant.design/menu?anchor=%E5%85%B3%E9%97%AD%E6%97%B6%E5%AE%8C%E5%85%A8%E6%94%B6%E8%B5%B7-menu#%E5%85%B3%E9%97%AD%E6%97%B6%E5%AE%8C%E5%85%A8%E6%94%B6%E8%B5%B7-menu
