### ISSUE TITLE
V4怎么统一处理返回的数据  只找到了统一处理状态码的

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5760]
这是状态码的
![image](https://user-images.githubusercontent.com/47104575/70874074-86f1f180-1feb-11ea-8c9f-7fe782bf333b.png)
我想统计处理返回的数据 比如code = 2 时怎么样

**Comment by xiaodit** [comment]
试下 `response.data`

**Comment by 904492381** [comment]
> 试下 `response.data`

应该没用 errorHandle里的response好像只能有error的才能获取到
我的需求是状态码200也要获取到

**Comment by 904492381** [comment]
已解决
![image](https://user-images.githubusercontent.com/47104575/70875190-0d103700-1ff0-11ea-9baf-6f671cad2c1c.png)
