### ISSUE TITLE
🧐[问题]表格列表请求异常时，会阻断网页执行

### ISSUE THREAD

**Issue by yuyu147** [ant-design/ant-design-pro#5761]
### 🧐 问题描述

使用表格ProTable request属性，fetch请求出错，抛出了Error异常，无法使用 try catch 捕获错误，导致页面运行杯阻断

### 💻 示例代码

request={params => queryRule(params)}

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22487249/70875119-d5a18a80-1fef-11ea-8f4a-50f79b36c7da.png)

**Comment by afc163** [comment]
`require().then().catch()`

**Comment by yuyu147** [comment]
> `require().then().catch()`

ok thanks
