### ISSUE TITLE
🐛[BUG]pro的样式影响到了antd的样式，Popover、Select、Popconfirm等组件的弹出元素在页面滚动时，没有跟随组件

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design-pro#5762]
### 🐛 bug 描述
pro的样式影响到了antd的样式，Popover、Select、Popconfirm等组件的弹出元素在页面滚动时，没有跟随页面一起滚动。而在antd官网上，这些组件的弹出元素始终是跟随组件的。
请看以下GIF。有问题的应该不只是这几个组件，这个问题应该会影响到所有使用相同定位方法的组件。
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-pro-bug.zf22qum1j5.gif)

而且在官方pro演示中，出现了多个滚动条。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/70875291-709a6480-1ff0-11ea-8fcf-9f5b97a8b3c5.png">

这个滚动条真是灾难。@chenshuai2144 尽快修复一下吧。

**Comment by maxmeng93** [comment]
我拉了一份最新的 pro 代码，有2个问题：
* 固定 Header 失效
* 固定侧边菜单后，弹出元素不跟随组件的问题依然存在

**Comment by maxmeng93** [comment]
固定 Header 只有在同时设置 固定Header 和 固定侧栏菜单 后才生效。不知道设计如此，还是bug。
还有固定侧栏后，可以看到页面右侧多了一个空白，页面元素因为居中显示，会看到有一个左移的动作。
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-pro-bug.ffdoio2kvoj.gif)

**Comment by chenshuai2144** [comment]
@maxmeng93 那边多了一个 header 是 drawer 的 bug。

> 固定侧边菜单后，弹出元素不跟随组件的问题依然存在 

这个没有很好地解法。

**Comment by maxmeng93** [comment]
> @maxmeng93 那边多了一个 header 是 drawer 的 bug。
> 
> > 固定侧边菜单后，弹出元素不跟随组件的问题依然存在
> 
> 这个没有很好地解法。

应该只能取消侧栏的固定

**Comment by maxmeng93** [comment]
悬浮元素，应该是基于html或者body进行定位的。
* 当侧栏没有固定时，悬浮元素会跟随定位元素一起滚动。
* 但是，侧栏固定后，html或者说body是无法滚动的，因此悬浮元素也无法跟随那几个组件一起移动。

解决办法：
侧栏使用 position: fixed; 整个页面还是设置为可以滚动的
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-pro-bug.h1mses6sp7g.gif)

**Comment by qiqizjl** [comment]
这个问题解决了 引起了另外一个问题 高级表单页面的提交不会随着滚动。。这是不能兼得么。。

**Comment by maxmeng93** [comment]
> 这个问题解决了 引起了另外一个问题 高级表单页面的提交不会随着滚动。。这是不能兼得么。。

应该不会影响到表单吧，只有侧栏只固定的，其他改怎么样，还是怎么样呀

**Comment by XSmarter** [comment]
Affix 组件也受到影响，只有改变浏览器尺寸的时候会生效，上下滚动无法正常使用Affix组件，console输出
![image](https://user-images.githubusercontent.com/33716687/70975069-2abec880-20e4-11ea-9452-20e4bd1cb5f8.png)

**Comment by chenshuai2144** [comment]
fixed in 4.10.0
