### ISSUE TITLE
v4线上预览的版本 菜单一直是固定的  fixSiderbar 失效

### ISSUE THREAD

**Issue by Imhemers** [ant-design/ant-design-pro#5763]
https://preview.pro.ant.design/dashboard/analysis
这里已经复现了哦  还有那个 menu足够高往下拉会出现空白部分  

contentStyle设置100%也没有作用

![image](https://user-images.githubusercontent.com/18650947/70877570-fa4e3000-1ff8-11ea-9379-e1c1007b47b9.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
清空一下缓存就好了

**Comment by Imhemers** [comment]
> 清空一下缓存就好了，这个 issue 半个月前就 fixed 了

是清空浏览器缓存还是 npm缓存

**Comment by chenshuai2144** [comment]
浏览器缓存

**Comment by gb-6k-house** [comment]
fixSiderbar 无效。左边菜单栏固定不动，超出内容无法滑动
