### ISSUE TITLE
👑 [需求]就不能把pro设计的简洁一些？

### ISSUE THREAD

**Issue by shx996** [ant-design/ant-design-pro#5765]
### 🥰 需求描述
我希望默认把 国际化、和权限一切相关的、登录页面、统统干掉，然后分离出来给需要的人一键添加，或者他们需要的话自己可以写的，我觉得你们写的权限认证我不太喜欢。通常我手动去掉这些很头疼，要花费不少时间，还要照顾你们写好的各种test。。。

### 🧐 解决方案
分离。。。

### 🚑 其他信息
简洁，清晰。而不是一堆你们写好的一大堆我用不到的东西。。各取所需不好吗。

**Comment by shx996** [comment]
权限这个东西我相信大家都有自己的方案，你们写的东西未必适用于别人。还有国际化这东西我估计大多数人都是国内使用，还是分离出来吧。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/3775

**Comment by yucccc** [comment]
我也觉得 本身还是挺不错的 就是太多不必要的东西了

**Comment by zqxb** [comment]
把不需要的给删除掉 不就好了

**Comment by mankeheaven** [comment]
install 过程太重了太慢了。

**Comment by poyiding** [comment]
> ### 🥰 需求描述
> 我希望默认把 国际化、和权限一切相关的、登录页面、统统干掉，然后分离出来给需要的人一键添加，或者他们需要的话自己可以写的，我觉得你们写的权限认证我不太喜欢。通常我手动去掉这些很头疼，要花费不少时间，还要照顾你们写好的各种test。。。
> 
> ### 🧐 解决方案
> 分离。。。
> 
> ### 🚑 其他信息
> 简洁，清晰。而不是一堆你们写好的一大堆我用不到的东西。。各取所需不好吗。

在pro v4 发布前其实大家有[讨论](https://github.com/ant-design/ant-design-pro/issues/3143#issuecomment-483140697)，你可以用[pro-layout](https://github.com/ant-design/ant-design-pro-layout)，现在国际化删除很简单了，但是权限这个确实还是得你自己删除或改造。权限这种定制化的东西确实不应该集成进去，他们应该是想给个参考示例，但是忽略了一点，怎么兼顾给了想要的或者给了不会用的人。

**Comment by yutingzhao1991** [comment]
简化的事情一直在做，之前做了 umi 区块，做了 pro-layout 其实都是在往这个方向走。后面还会继续简化，通过把一些通用性的内容封装为 umi 插件或者组件的方式进一步简化。比如权限目前就封装了一个 https://github.com/umijs/plugin-access 后面也会接到 Pro 中来，到时候不管是理解还是要去掉都会变得更简单。整体思路可以参考云谦的 https://github.com/sorrycc/blog/issues/90 《蚂蚁前端研发最佳实践》，近期 Pro 也会基于这个思路有一波更新。

**Comment by afc163** [comment]
大家反复提到的这些问题中的一些，也是我们自己业务遇到的问题：初始化页面太多，布局组件改不动，业务组件不好用，js/ts，是否要默认包含登录页，国际化，权限，动态主题怎么移除（或者怎么增加）等等等。

从 Pro 2.0 到 Pro 4.0，我们针对上面的问题做了下面一些事情：

- 提供 ts 和 js 两个版本，主要靠 https://github.com/umijs/sylvanas 来做转换。
- 所有的典型页面拆分成区块，并把区块的添加做到 [umi ui](https://umijs.org/zh/guide/umi-ui.html)，解决 pro 上手时代码太多的问题，大多数人只需要一个布局模板。
- 把布局相关代码拆到 [pro-layout](https://github.com/ant-design/ant-design-pro-layout) 组件中，进一步简化 pro 里的代码，方便统一升级，简化自定义的成本。
- 把 pro 里的部分业务组件直接做进 antd，比如这一年来添加的 Result、Empty、Typography、PageHeader、Descriptions、Statistic 等等，使这部分代码的质量和 API 更规范。
- 做了 `npm run i18n-remove` 可以一键移除国际化相关代码：https://github.com/ant-design/ant-design-pro/issues/3775#issuecomment-521873978
- 做了 [umi-plugin-antd-theme](https://github.com/chenshuai2144/umi-plugin-antd-theme) 简化动态主题的相关代码。

我们接下来要做的事情是：

1. @yutingzhao1991 上面提到的最佳实践，把 pro 里面的权限、布局、菜单、数据流、请求、国际化等能力全面 umi 插件化、代码标准化和配置化，这样 pro 里的代码会极致精简，只包含业务逻辑的部分，配合 umi ui 里提供的区块资产市场，很快可以搭出想要的产品雏形。
2. 进一步拆分重型组件，例如 @chenshuai2144 在做的 https://github.com/ant-design/pro-table 。

整体上 Ant Design Pro 是向着精简化，配置化，区块化，强约束的方向发展的。最近由于人力问题，Pro 的投入力度也确实不太够，一直只能保持细水长流的关注，欢迎大家持续吐槽。当然能直接贡献代码是最好的，成为 Pro 核心贡献者，你想它变成什么样直接上手改！

**Comment by JunlinZhu-Tommy** [comment]
I beileve antd-pro is working great, just give it time to let people optimize it.
