### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by yinbanghui** [ant-design/ant-design-pro#5767]
### 🐛 bug 描述
通过
![image](https://user-images.githubusercontent.com/10389726/70895575-29c96080-202a-11ea-8206-6e55fc2e2c7f.png)
获取最新代码
npm run lint报错

![image](https://user-images.githubusercontent.com/10389726/70895519-0dc5bf00-202a-11ea-9649-445cbe755a42.png)

**Comment by yinbanghui** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
项目下下来之后是要先装依赖的。。。。。。

**Comment by chenshuai2144** [comment]
@sorrycc  项目新建之后是不是自动帮装一下依赖，这种问题最近出现了两次了

**Comment by yinbanghui** [comment]
![image](https://user-images.githubusercontent.com/10389726/70898294-5a5fc900-202f-11ea-89dc-ce306e18cb38.png)

**Comment by yinbanghui** [comment]
cnpm install eslint --save-dev就OK
