### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by charithjayasanka** [ant-design/ant-design-pro#5768]
Issue with dependency @typescript-eslint/typescript-estree

Cannot run npm install, it fails with an error
**error Couldn't find any versions for "@typescript-eslint/typescript-estree" that matches "2.11.1-alpha.2+f9a9fbfc"**

It seems that @typescript-eslint/typescript-estree 2.11.1 alpha version is no longer available so their archives has been updated.

**Comment by chenshuai2144** [comment]
The lerna project sent 10 packages at a time, and only 8 packages were successfully sent, but the other 2 package versions were relied on to successfully send 8 packages. When npm installs these 8 packages, it will prompt npm There are no other 2 package versions.

2019-12-16 21.19.00
npm has been restored.
