### ISSUE TITLE
🧐[问题]查询表格的复选框是被改掉了么？

### ISSUE THREAD

**Issue by hellomolike** [ant-design/ant-design-pro#5769]
### 🧐 问题描述
使用umi,下载了table-list模板，项目成功运行，展示查询表格的时候复选框不见了。是就是写成这样的还是我本地环境有问题啊？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/36214418/70921667-b8a4a000-205f-11ea-9f48-86bfe63bc325.png)
![image](https://user-images.githubusercontent.com/36214418/70921783-f4d80080-205f-11ea-9147-3fdf6ae3451c.png)

**Comment by XiaYaXia** [comment]
rowSelection={} 我加了一个这个参数，复选出来了  不知道之不是这样配置

**Comment by chenshuai2144** [comment]
换成这个了，欢迎提 issue

https://ant-design.github.io/pro-table/

**Comment by hellomolike** [comment]
嗯嗯 感谢！

**Comment by hellomolike** [comment]
> 
> 
> 换成这个了，欢迎提 issue
> 
> https://protable.ant.design/

嗯嗯 非常感谢！
