### ISSUE TITLE
🧐[问题]  服务端分页 在pro-table 如何实现呢？

### ISSUE THREAD

**Issue by XiaYaXia** [ant-design/ant-design-pro#5770]
### 🧐 问题描述
问题一： rowSelection={} 开启复选康 这样实现是正确的吗？

问题二： 服务端分页数据 如何在pro-table 实现功能，

### 💻 示例代码
这个是我请求后台的代码
` const request = (params:any): Promise<{
    data: TableListItem[];
    success: true;
    total:number;
  }> =>
    new Promise(resolve => {
      queryRule(params).then(res=>{
        console.log(res);
        const data = res.data.list;
        const count = res.data.count;
        message.success(res.msg);       
        
          resolve({
            data:data,                        
            success: true,
            total:count,
            current:2,
            pageSize:2,         
            
          });
        
      })  
      
    });`

**Comment by chenshuai2144** [comment]
https://ant-design.github.io/pro-table/
这个官网上有个 demo，是真实的数据
