### ISSUE TITLE
🐛[BUG] 左边栏滚动条和右侧滚动条在多内容的情况下未显示

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design-pro#5772]
### 🐛 bug 描述
PRO layout版本4.9.11
左边栏滚动条和右侧滚动条在多内容的情况下未显示
PRO layout版本4.5.16是正常的

4.5.16如图：
![image](https://user-images.githubusercontent.com/8730272/70969101-09ef7680-20d6-11ea-8c8d-2c83ae98a35a.png)
补充标红框，两处
![image](https://user-images.githubusercontent.com/8730272/70970272-e0841a00-20d8-11ea-97fb-59a505e55489.png)

升级到4.9.11滚动条不见了
![image](https://user-images.githubusercontent.com/8730272/70969438-9b5ee880-20d6-11ea-8729-47779998d7a1.png)

### © 版本信息

- Ant Design Pro 版本: [4.9.11]
- umi 版本2.9.6
- 浏览器环境 QQ浏览器极速模式
- 开发环境 [Windows10]

**Comment by chenshuai2144** [comment]
fixed in 4.10.0

https://prolayout.ant.design/api

**Comment by phoema** [comment]
@chenshuai2144 
你好，辛苦了

![image](https://user-images.githubusercontent.com/8730272/71306945-66c69600-2422-11ea-8b73-5f003a6242c7.png)

从V4.5.16升到V4.10.0
1、大红框处 依然没有滚动条，最右侧有了滚动条，但是是有右侧内容区的，导航部分下部被遮挡无法滚动。
2、小红框收缩左侧菜单按钮明显卡顿

**Comment by chenshuai2144** [comment]
你可以把这个配置在项目中加回来， 
固定 siderMenu 的高度对于一个通用组件来说比较 hack。
你的需求应该是固定菜单的高度把。可以试着打开固定菜单试试

**Comment by chenshuai2144** [comment]
另外如果方便 可否将你的菜单 分享出来，我将其加入到测试中

**Comment by phoema** [comment]
不好意思，我可能描述的不太清楚，
我就是想滚动，用浏览器的滚动条做整体滚动也是可以接受的。但是现在是超出浏览器高度左侧导航没有滚动，显示不全。而且目前并没有浏览器的滚动条，只有右侧内容区的滚动条控制右侧。

calc高度那个在4.5.16有，我也不知道他在哪儿。具体表现就是菜单和右侧内容区是分别控制的滚动条。
4.10.0就没了，我只升了这一个layout的包版本，别的文件没有动，不知道冲突在哪儿




菜单:


[config.zip](https://github.com/ant-design/ant-design-pro/files/3993373/config.zip)

**Comment by phoema** [comment]
@chenshuai2144
