### ISSUE TITLE
是否考虑对皮肤主题文件单独维护

### ISSUE THREAD

**Issue by fancyboynet** [ant-design/ant-design-pro#5774]
### 🥰 需求描述

我们的项目并不是用umi构建的，但是很喜欢ant pro的UI，并且有也想有动态换肤功能
目前我们的解决方案是把demo上的css下载下来再引入

### 🧐 解决方案

我的理解，主题本质就是一些样式文件，是否可以独立维护，并提供相应的less和css文件，这样不同的项目都能用，是不是会更灵活一点呢？

### 🚑 其他信息
暂无

**Comment by afc163** [comment]
- https://github.com/ant-design/ant-design-dark-theme
- https://github.com/ant-design/ant-design-aliyun-theme

**Comment by fancyboynet** [comment]
我是指demo里的theme color那些，像是这些
https://preview.pro.ant.design/theme/volcano.css
https://preview.pro.ant.design/theme/cyan.css

**Comment by afc163** [comment]
这些其实只是换了个主色，没有太多维护的必要。

**Comment by fancyboynet** [comment]
嗯，就是皮肤吧，个人感觉，可能仓库不是很大，但还是有意义的，毕竟控件比较多，变量也比较多，如果官方可以给个demo，那对想贡献皮肤，但是对ant并不很了解的人还是有一些参考价值的吧

**Comment by afc163** [comment]
需要维护贡献主题皮肤，fork 一份 https://github.com/ant-design/ant-design-aliyun-theme 按需改动就可以了。

**Comment by fancyboynet** [comment]
这个也支持动态换色吗

**Comment by chenshuai2144** [comment]
模仿这个插件写一个吧

https://github.com/chenshuai2144/umi-plugin-antd-theme

换主题是一个炫酷但是意义不大的需求，很多 to C 的换主题功能都没什么人用

**Comment by fancyboynet** [comment]
@chenshuai2144 项目没上umi

**Comment by fancyboynet** [comment]
需求有时候不是我们能决定的额

**Comment by fancyboynet** [comment]
不好意思，我感觉我问错地方了，感觉换色应该是属于ant-design的范畴了
