### ISSUE TITLE
🧐[问题]ProTable 在后面页数时，搜索怎么回到第一页

### ISSUE THREAD

**Issue by chendanlin** [ant-design/ant-design-pro#5776]
### 🧐 问题描述

使用ProTable，在后面页数如第二页，触发搜索，页数还是保持在搜索前的页数，我想让搜索后重新定位到第一页，我已经实现数据刷新，但是分页器还是保持在第二页

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/35648425/71050897-770c1600-2181-11ea-8ccc-60af703ed581.png)
![image](https://user-images.githubusercontent.com/35648425/71050933-9145f400-2181-11ea-8d69-8f9eb8e88479.png)
这是在点击搜索后的图片，分页还是保持在第二页
![image](https://user-images.githubusercontent.com/35648425/71050970-aae73b80-2181-11ea-9b12-516ef336bac8.png)

**Comment by chenshuai2144** [comment]
@chendanlin  这应该是个默认行为。我支持一下。

**Comment by afc163** [comment]
`action.resetPageIndex()` 这个不好，给属性控制，尽量不要暴露内部方法，这样会改变 React 的使用心智。

**Comment by chendanlin** [comment]
更新版本后，确定已经默认回到第一页了，谢谢
