### ISSUE TITLE
🧐[问题]Layout 组件ProLayout如何控制菜单手风琴折叠

### ISSUE THREAD

**Issue by 475533819** [ant-design/ant-design-pro#5778]
### 🧐 问题描述
通过路由routes渲染的菜单，在ProLayout里如何加上手风琴折叠效果？

**Comment by chenshuai2144** [comment]
是个 bug，可以在这里跟踪

https://github.com/ant-design/ant-design-pro-layout/pull/244

**Comment by chenshuai2144** [comment]
fixed in 4.10.0
