### ISSUE TITLE
监控页报的一个错

### ISSUE THREAD

**Issue by lawrence-peng** [ant-design/ant-design-pro#578]
![image](https://user-images.githubusercontent.com/13516546/34599058-74def76c-f22b-11e7-8313-3021628b810d.png)

**Comment by chenshuai2144** [comment]
看起来像是注解报错了.什么情况下?

**Comment by lawrence-peng** [comment]
用的admin账号登录，然后点击 dashboard->监控页 就出现下图的错误提示，（运行时的错误）
注：环境是 mac pro.

![image](https://user-images.githubusercontent.com/13516546/34599254-2032cc6a-f22c-11e7-9708-b23ec2b45393.png)

**Comment by chenshuai2144** [comment]
主分支?

**Comment by lawrence-peng** [comment]
是的

**Comment by PeterRock** [comment]
这波push是不是没测试啊

**Comment by chenshuai2144** [comment]
这就是开源的优越之处了.....
有人会帮忙测试的.. 预览版

**Comment by wuzehao16** [comment]
./src/routes/Dashboard/Monitor.js
137:22-29 '../../utils/Authorized' does not contain an export named 'Secured'.
login都不行了

**Comment by chenshuai2144** [comment]
因为 roadhog升级导致的!!!
我们会紧急搞一个提交

**Comment by PeterRock** [comment]
在线等

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34601598-aaaa6fa0-f237-11e7-84ce-fa3dfc7c847d.png)

这还要写key   !!!!气派

**Comment by elevensky** [comment]
![image](https://user-images.githubusercontent.com/6904834/34602092-797db1a6-f239-11e7-8b97-00f290c192e8.png)
控制台还有三个吧 Warning

**Comment by chenshuai2144** [comment]
key的问题   #581  改了

**Comment by dai875939260** [comment]
升级roadhog2.x后，就一直报key的错误。。我都不管它了

**Comment by chenshuai2144** [comment]
估计是什么规则改了  react16.2应该不会这样的
