### ISSUE TITLE
🧐[问题]4.0 @connect  ts校验不通过

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#5782]
### 🧐 问题描述

4.0官方区块代码,在vscode中ts提示,如何修改让ts校验通过?

### 💻 示例代码

![03FC51F2-593B-45AD-9874-C7B476539B86](https://user-images.githubusercontent.com/15940920/71135775-9cf6f080-223d-11ea-89fe-78f4e61fab2c.png)

**Comment by chenshuai2144** [comment]
我得修一下，不要用 注解就好了。ts的注解和js的表现不一样，所以一定会报错
