### ISSUE TITLE
👑 菜单栏打开外部页面（嵌入页面）

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#5784]
### 🥰 需求描述
请问官方能不能提供一个菜单栏打开外部页面（嵌入页面），在原窗口tab打开，而是新开页面。

### 🧐 解决方案
目前，我通过编写一个iframe组件实现，但是存在诸多缺陷。

### 🚑 其他信息
希望官方能支持一下菜单栏打开外部页面需求，如下效果：
![image](https://user-images.githubusercontent.com/37643958/71140841-632de600-224d-11ea-92d1-8dcaa95b22d3.png)

**Comment by chenshuai2144** [comment]
你要的这个太高级了，iframe 是唯一的办法。
你详细描述一下你的问题和碰到的缺陷，。这个问题现在没有完美的解决方案，只能各种拖鞋了
