### ISSUE TITLE
🧐[问题]单选按钮组样式无法生效

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#5785]
### 🧐 问题描述
我在初始化的antdesignpro框架中新建一个页面，页面中有一组单选按钮组，页面引用index.class样式，无法生效。但是我在antdesign中样例中的在线网站编辑中写的是可以生效的，https://hmkamn.run.stackblitz.io。
所以不知antdesignpro中编写样式需要什么特殊的规则吗还是什么？

1.按照官网教程初始化一个antdesignpro（js）的框架
2.新建页面test.js和index.css
3.启动项目样式无法生效
### 💻 示例代码
index.js代码,
class test extends React.Component {
    render(){
        return(
            <Radio.Group value={1} className={styles}>
            <Radio value={1}>5</Radio>
            <Radio value={2}>4</Radio>
          </Radio.Group>
        )
    }
}
export default test

index.css代码
.ant-radio-wrapper.ant-radio-wrapper-checked{
    background-color: red;
}

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/style-cn#header
你碰到了 css-moudle ,看一下这个文章
