### ISSUE TITLE
开启按需加载 布局出现部分白屏🧐[问题]

### ISSUE THREAD

**Issue by zqxb** [ant-design/ant-design-pro#5789]
### 🧐 问题描述
如果数据多的话不会出现，但是数据少就会出现
### 💻 示例代码

dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      },

### 🚑 其他信息

![WechatIMG20](https://user-images.githubusercontent.com/35833867/71226551-29291680-2317-11ea-9236-4eb15753c416.jpeg)

**Comment by chenshuai2144** [comment]
你是指 layout 的高度没有撑满吗？

**Comment by zqxb** [comment]
layout 跟内容都是没撑满，不开按需加载就没事@chenshuai2144

**Comment by zqxb** [comment]
或者针对root 下面div 设置高100%，就行了

**Comment by chenshuai2144** [comment]
@zqxb  如果你的layout是 root 的话直接设置  minHeight:"100vh" 即可解决问题。
默认的layout 高度是 100%，如果父容器没有高度他就不会继承。
