### ISSUE TITLE
代码没有格式化导致报错

### ISSUE THREAD

**Issue by wuzehao16** [ant-design/ant-design-pro#579]
![1515137297 1](https://user-images.githubusercontent.com/6562398/34599533-dbaf995e-f22d-11e7-93c2-5a8849f89715.png)
拉的主分支最新的代码，会报错，运行lint:fix 才行

**Comment by chenshuai2144** [comment]
因为默认是lf  windows 默认是 crlf

**Comment by wuzehao16** [comment]
谢谢， Windows做开发机真的烂

**Comment by chenshuai2144** [comment]
不能怪罪windows呀... 各个平台都有怪癖

**Comment by KOHOH1992** [comment]
再给git clone之前运行git config --global core.autocrlf false，禁用自动转化为crlf
