### ISSUE TITLE
🐛[BUG] PageHeaderWrapper 导致ProLayout底部额外留空24px

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design-pro#5790]
### 🐛 bug 描述

在使用`PageHeaderWrapper`的页面，底部留白不是预期的24px，而是48px。移除footer后很明显
![image](https://user-images.githubusercontent.com/23520283/71227701-0d277400-231b-11ea-82e6-77fbe2214da0.png)

### 📷 复现步骤

在[ant-design-pro-layout](https://github.com/ant-design/ant-design-pro-layout)中没有这个问题，对比dom解构
pro中
![image](https://user-images.githubusercontent.com/23520283/71227821-61caef00-231b-11ea-8c9b-6a069a43e27f.png)
pro-layout中
![image](https://user-images.githubusercontent.com/23520283/71227991-dc940a00-231b-11ea-8a2b-36d67fd6b94d.png)

在官网preview中将dom移动
![image](https://user-images.githubusercontent.com/23520283/71228086-2bda3a80-231c-11ea-9bce-b908742b18dd.png)
结果达到预期的24px
但如果开启固定header，则底部留白为0px

### © 版本信息

官网priview

**Comment by Liu-Ya** [comment]
@chenshuai2144 看pro-layout的更新日志以为是autoHideHeader的问题，但将项目中的版本更新到4.10.0后问题还是存在。目前没找到这个层div是哪来的。

**Comment by chenshuai2144** [comment]
可以试试 disableContentMargin.

**Comment by Liu-Ya** [comment]
🤔 disableContentMargin可以，但应该不是最优的解法，为layout设置disableContentMargin后，不使用PageHeaderWrapper的页面就要重写margin，如果放到router config去配置好像也不是很好

**Comment by chenshuai2144** [comment]
因为 - margin 的原因，我来想想办法

**Comment by chenshuai2144** [comment]
已经在最新版本中顺便被修复。
