### ISSUE TITLE
umi创建的项目中， 独立使用 Pro 组件 需要额外引入import "antd/dist/antd.css";

### ISSUE THREAD

**Issue by dobeweb** [ant-design/ant-design-pro#5791]
### 🧐 问题描述
umi创建的项目，选择了antd和dva，按照文档单独引入了图表插件
[独立使用 Pro 组件](https://v2-pro.ant.design/docs/use-components-alone-cn)

需要在额外在global.css里面引入antd/dist/antd.css，否则图表里面缺少antd样式

### 💻 示例代码

/src/global.less
`
import "ant-design-pro/dist/ant-design-pro.css";
// import "antd/dist/antd.css"; // 

`

### 🚑 其他信息

![WechatIMG1315](https://user-images.githubusercontent.com/50686836/71228441-1285be00-231d-11ea-9858-2ff8d34338e6.jpeg)

**Comment by chenshuai2144** [comment]
建议使用 umi ui 将组件下载到本地来使用。组件已经停止维护了。使用停止维护的组件可能会造成一些无法解决的问题
https://pro.ant.design/docs/block-cn
