### ISSUE TITLE
🧐[问题]RouteContext中取不到任何值

### ISSUE THREAD

**Issue by xclw2000** [ant-design/ant-design-pro#5792]
代码如下
`<RouteContext.Consumer>
      {value => {
        console.log('RouteContext value', value);
      }}
    </RouteContext.Consumer>`

控制台输出如下
![image](https://user-images.githubusercontent.com/32091566/71229116-5f6a9400-231f-11ea-9eba-47f200354bfe.png)

value就是个空对象，我还拿到isMobile，可是什么也取不到，是不是我哪里写错了？需要我手动写
Provider吗？

**Comment by chenshuai2144** [comment]
他必须要包在 Layout 里面，不然拿不到数据

**Comment by xclw2000** [comment]
> 他必须要包在 Layout 里面，不然拿不到数据

我在BasicLayout的menuHeaderRender里怎么拿Layout包RouteContext呀
![image](https://user-images.githubusercontent.com/32091566/71299550-d019bb00-23c8-11ea-9f85-bc9ddab9ccec.png)

**Comment by chenshuai2144** [comment]
@xclw2000 耐心等待一下，我的新版将会增加第三个参数，是 layout 的 props，里面就可以拿到 isMoble。

**Comment by chenshuai2144** [comment]
版本已经发布，你可以通过第三个参数来拿到你需要的东西。

https://prolayout.ant.design/example#%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95

**Comment by xclw2000** [comment]
> 版本已经发布，你可以通过第三个参数来拿到你需要的东西。
> 
> https://prolayout.ant.design/example#%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95

升级到4.10.1后，页面加载报错，左侧菜单出不来
好像是SideMenu里出问题了
![image](https://user-images.githubusercontent.com/32091566/71460785-457df500-27e8-11ea-9356-2ab8356949d2.png)

**Comment by chenshuai2144** [comment]
@xclw2000  是我的 bug

**Comment by 1715215176** [comment]
我也遇到了这个问题，可能是新的版本需要从import { RouteContext } from '@ant-design/pro-components'; 导入就可以拿到所的信息了。之前是从@ant-design/pro-layout 导入的就是空对象
