### ISSUE TITLE
请问路由能否支持这样传参？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#5794]
### 🧐 问题描述
请问路由能否支持这样传参：
http://localhost:8000/myiframe/urlPath?src=http://localhost:9111/nacos

需要怎么配置？

**Comment by chenshuai2144** [comment]
encodeURI 一下就可以了，具体可以看 mdn。
文档地址
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI
