### ISSUE TITLE
部署之后还是请求本地API

### ISSUE THREAD

**Issue by Liqiankun** [ant-design/ant-design-pro#5795]
### 💻 示例代码
config文件配置
```
  proxy: {
    '/api': {
      target: 'https://xcx-img.teamup.group:9000/api/',
      changeOrigin: true,
      pathRewrite: { '^/api': '' },
    },
  }
```
build之后部署错误如下。
![错误](https://user-images.githubusercontent.com/11532418/71318213-ec048600-24c8-11ea-9c30-4db4a416990e.png)
部署之后请求为啥不是我target设置的地址？怎么设置才能访问我设置的地址？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/5613
https://github.com/ant-design/ant-design-pro/issues/5022
https://github.com/ant-design/ant-design-pro/issues/2302

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/2779

**Comment by afc163** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-436546754

**Comment by Liqiankun** [comment]
@afc163 恩，我还是不知道怎么解决。

**Comment by chenshuai2144** [comment]
还可以看看这两篇
https://pro.ant.design/blog/proxy-cn
https://pro.ant.design/docs/deploy-cn

**Comment by Liqiankun** [comment]
@xiaohuoni
> 代理只是服务请求代理，这个地址是不会变的。
原理可以简单的理解为，在本地启了一个服务，你先请求了本地的服务，本地的服务转发了你的请求到实际服务器。所以你在浏览器上看到的请求地址还是http://localhost:8000/xxx 。以服务端是否收到请求为准

**对于前端同学来说这个确实不好理解，解决方法是服务端需要设置，关键点如下，以我们为例。** 更多请参考[部署到不同的平台](https://pro.ant.design/docs/deploy-cn)
```
location /api {
      proxy_pass https://ant-design-pro.netlify.com;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   Host              $http_host;
      proxy_set_header   X-Real-IP         $remote_addr;
  }
```
**proxy_pass设置成真实服务器地址就可以了。** 

***很多回答都是让你去看文档(对于做前端的同学真的摸不着头脑)，而不直接告诉你解决问题的方法，真的不太好，如果解决了你的问题给个👍*** 

这样才是回答问题。

**Comment by afc163** [comment]
@Liqiankun 欢迎来帮我们完善文档。

**Comment by Liqiankun** [comment]
@afc163 一点个人意见而已。😂

**Comment by mymmoonoa** [comment]
> @xiaohuoni
> 
> > 代理只是服务请求代理，这个地址是不会变的。
> > 原理可以简单的理解为，在本地启了一个服务，你先请求了本地的服务，本地的服务转发了你的请求到实际服务器。所以你在浏览器上看到的请求地址还是http://localhost:8000/xxx 。以服务端是否收到请求为准
> 
> **对于前端同学来说这个确实不好理解，解决方法是服务端需要设置，关键点如下，以我们为例。** 更多请参考[部署到不同的平台](https://pro.ant.design/docs/deploy-cn)
> 
> ```
> location /api {
>       proxy_pass https://ant-design-pro.netlify.com;
>       proxy_set_header   X-Forwarded-Proto $scheme;
>       proxy_set_header   Host              $http_host;
>       proxy_set_header   X-Real-IP         $remote_addr;
>   }
> ```
> 
> **proxy_pass设置成真实服务器地址就可以了。**
> 
> _**很多回答都是让你去看文档(对于做前端的同学真的摸不着头脑)，而不直接告诉你解决问题的方法，真的不太好，如果解决了你的问题给个👍，看看解决了多少人的问题。**_
> 
> 这样才是回答问题。如果之前的回答指出关键点，这个问题还会被一遍又一遍提问吗？

chenshuai2144 这个人回问题，感觉像是去政府单位很不耐烦的那种
