### ISSUE TITLE
基本 antd design pro 配置 dva 的 hooks 报错

### ISSUE THREAD

**Issue by soeasyjx** [ant-design/ant-design-pro#5798]
基本 antd design pro 配置 dva 的 hooks 报错 只有onStateChange可以正常使用

因项目需要，看umijs 官方文案 配置 dva hooks 
在 src 目录下新建 app.js，内容如下：
export const dva = {
  config: {
     onAction: () => {
      console.log('action');
    },
  },
};

执行 npm run start 启动项目报错
×
TypeError: Cannot read property 'apply' of undefined
(anonymous function)
.[name]/node_modules/_redux@3.7.2@redux/es/compose.js:29
  26 | 
  27 |   return funcs.reduce(function (a, b) {
  28 |     return function () {
> 29 |       return a(b.apply(undefined, arguments));
  30 |     };
  31 |   });
  32 | }
View compiled
(anonymous function)
.[name]/node_modules/_redux@3.7.2@redux/es/applyMiddleware.js:41
  38 | chain = middlewares.map(function (middleware) {
  39 |   return middleware(middlewareAPI);
  40 | });
> 41 | _dispatch = compose.apply(undefined, chain)(store.dispatch);
     | ^  42 | 
  43 | return _extends({}, store, {
  44 |   dispatch: _dispatch
View compiled
createStore
.[name]/node_modules/_redux@3.7.2@redux/es/createStore.js:51
  48 |     throw new Error('Expected the enhancer to be a function.');
  49 |   }
  50 | 
> 51 |   return enhancer(createStore)(reducer, preloadedState);
     | ^  52 | }
  53 | 
  54 | if (typeof reducer !== 'function') {
View compiled
_default
.[name]/node_modules/_dva-core@1.4.0@dva-core/lib/createStore.js:49
  46 |   }
  47 | 
  48 |   var enhancers = [_redux.applyMiddleware.apply(void 0, (0, _toConsumableArray2.default)(middlewares))].concat((0, _toConsumableArray2.default)(extraEnhancers), [devtools(_window.default.__REDUX_DEVTOOLS_EXTENSION__OPTIONS)]);
> 49 |   return (0, _redux.createStore)(reducers, initialState, _redux.compose.apply(void 0, (0, _toConsumableArray2.default)(enhancers)));
  50 | }
View compiled
start
.[name]/node_modules/_dva-core@1.4.0@dva-core/lib/index.js:250
  247 |   return !(key in reducers);
  248 | }), "[app.start] extraReducers is conflict with other reducers, reducers list: ".concat((0, _keys.default)(reducers).join(', '))); // Create store
  249 | 
> 250 | var store = app._store = (0, _createStore.default)({
      | ^  251 |   // eslint-disable-line
  252 |   reducers: createReducer(),
  253 |   initialState: hooksAndOpts.initialState || {},
View compiled
start
.[name]/node_modules/_dva@2.4.1@dva/lib/index.js:72
  69 | (0, _invariant.default)(app._router, "[app.start] router must be registered before app.start()");
  70 | 
  71 | if (!app._store) {
> 72 |   oldAppStart.call(app);
     | ^  73 | }
  74 | 
  75 | var store = app._store; // export _getProvider for HMR
View compiled
_DvaContainer.render
src/pages/.umi/dva.js:42
  39 |   render() {
  40 |     const app = getApp();
  41 |     app.router(() => this.props.children);
> 42 |     return app.start()();
  43 |   }
  44 | }
  45 | 
View compiled
▶ 16 stack frames were collapsed.
_callee$
src/pages/.umi/umi.js:68
  65 | const rootContainer = plugins.apply('rootContainer', {
  66 |   initialValue: React.createElement(require('./router').default, props),
  67 | });
> 68 | ReactDOM[window.g_useSSR ? 'hydrate' : 'render'](
     | ^  69 |   rootContainer,
  70 |   document.getElementById('root'),
  71 | );
View compiled
▶ 3 stack frames were collapsed.
asyncGeneratorStep
node_modules/_@babel_runtime@7.4.5@@babel/runtime/helpers/asyncToGenerator.js:3
  1 | function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
  2 |   try {
> 3 |     var info = gen[key](arg);
  4 |     var value = info.value;
  5 |   } catch (error) {
  6 |     reject(error);
View compiled
_next
node_modules/_@babel_runtime@7.4.5@@babel/runtime/helpers/asyncToGenerator.js:25
  22 | var gen = fn.apply(self, args);
  23 | 
  24 | function _next(value) {
> 25 |   asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
     | ^  26 | }
  27 | 
  28 | function _throw(err) {
View compiled
(anonymous function)
node_modules/_@babel_runtime@7.4.5@@babel/runtime/helpers/asyncToGenerator.js:32
  29 |         asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
  30 |       }
  31 | 
> 32 |       _next(undefined);
  33 |     });
  34 |   };
  35 | }
View compiled
(anonymous function)
node_modules/_@babel_runtime@7.4.5@@babel/runtime/helpers/asyncToGenerator.js:21
  18 | return function () {
  19 |   var self = this,
  20 |       args = arguments;
> 21 |   return new Promise(function (resolve, reject) {
     | ^  22 |     var gen = fn.apply(self, args);
  23 | 
  24 |     function _next(value) {
View compiled
clientRender
src/pages/.umi/umi.js:35
  32 | window.g_app = app;
  33 | 
  34 | // render
> 35 | let clientRender = async () => {
  36 |   window.g_isBrowser = true;
  37 |   let props = {};
  38 |   // Both support SSR and CSR
View compiled
(anonymous function)
.[name]/node_modules/_umi@2.12.5@umi/lib/runtimePlugin.js:89
(anonymous function)
src/pages/.umi/umi.js:83
  80 | if (__IS_BROWSER) {
  81 |   Promise.all(moduleBeforeRendererPromises)
  82 |     .then(() => {
> 83 |       render();
  84 |     })
  85 |     .catch(err => {
  86 |       window.console && window.console.error(err);
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

### 🏞 期望结果

可以在 ant design pro 中正常配置 dva 的 hooks

### © 版本信息

- Ant Design Pro 版本:3.10.10
- 2.2.1
- 浏览器环境
-  mac OS

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/17918538/71333090-acdf3f00-2573-11ea-8054-9716f2e12722.png)
![image](https://user-images.githubusercontent.com/17918538/71333114-c4b6c300-2573-11ea-99da-5e61ebe957cd.png)

**Comment by soeasyjx** [comment]
close

**Comment by chenshuai2144** [comment]
我们没有尝试过 dva+hooks。按照我们的规划，下一代应该全部使用 hooks

**Comment by winter-ice** [comment]
下一代是5.0?

**Comment by crashsol** [comment]
> 我们没有尝试过 dva+hooks。按照我们的规划，下一代应该全部使用 hooks

下一代就是UMI3.0? 直接使用hooks？不在默认项目中依赖dva？
