### ISSUE TITLE
最新版本运行登陆报错

### ISSUE THREAD

**Issue by tclinhan** [ant-design/ant-design-pro#580]
![image](https://user-images.githubusercontent.com/3694559/34601619-ca07b5d8-f237-11e7-9498-f4973487e858.png)

![image](https://user-images.githubusercontent.com/3694559/34601609-bb2fd888-f237-11e7-9970-7cb93b4259c4.png)

**Comment by chenshuai2144** [comment]
参见 #578   同样的

**Comment by FrankGuos** [comment]
最新版本报错，在线等，着急，但不是578问题。

**Comment by chenshuai2144** [comment]
同一个问题引发的  mock 挂了

**Comment by FrankGuos** [comment]
啥时候能修复更新一个版本 @chenshuai2144

**Comment by chenshuai2144** [comment]
正在了

**Comment by FrankGuos** [comment]
谢谢啦，辛苦，我能获得更新通知么，本想用最新启动一个新项目,,ԾㅂԾ,,
坐等

**Comment by tclinhan** [comment]
最新版本运行还有这个错误

![image](https://user-images.githubusercontent.com/3694559/34601961-f8aa7a32-f238-11e7-979b-de4a0ddbd66b.png)

**Comment by chenshuai2144** [comment]
LF 和 CFLT 是git的原因 .
#579

**Comment by chenshuai2144** [comment]
@FrankGuos  会@你的

**Comment by ddcat1115** [comment]
@FrankGuos  报错的问题在 #581 里已解决，key 的warning还要排查

**Comment by FrankGuos** [comment]
@chenshuai2144 @ddcat1115 我已经获取了最新代码。1楼第一张图的报错已经解决。但是第二张图登陆之后还是爆出这个错误。

**Comment by chenshuai2144** [comment]
@FrankGuos  已经修复了 重新安装一下依赖包.
