### ISSUE TITLE
👑 [需求]官方默认项目可以将暗黑主题部分属性调整一下.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#5800]
### 🥰 需求描述

现在可以支持暗黑主题了,可是官方给的配色,不得不说存在一些问题.在暗黑模式下,Table选中行的背景色是白色的,会导致行内数据无法正常阅读.所以建议将暗黑模式中的色值调整一下.
具体描述可以查看该链接 https://www.cnblogs.com/dygood/p/12072096.html

### 🧐 解决方案

在暗黑主题中的modifyVars中添加 '@table-selected-row-bg': '#30303d !important' 来避免选中行背景色为白色造成数据无法阅读的情况.让第一次使用该框架的人少一个坑.

**Comment by chenshuai2144** [comment]
antd4.0 会支持官方的暗色主题。

**Comment by joesdu** [comment]
> antd4.0 会支持官方的暗色主题。
> 一旦发布，我们就会跟进
好的,那我关闭这个issue了.
