### ISSUE TITLE
🐛[BUG]使用SettingDrawer更新主题后,浏览器地址栏的配置未发生变化

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#5801]
### 🐛 bug 描述

使用SettingDrawer更新主题后,浏览器地址栏的配置primaryColor=xxxx未发生变化,导致刷新浏览器后,SettingDrawer组件默认选中主题色非配置的主题色.并且若是出现页面跳转(离开BasicLayout组件包裹的页面后),跳转回来的时候,会默认切换成地址栏中的配置色.

### 📷 复现步骤

先使用SettingDrawer进行主题色切换,仅第一个主题色的配置信息,填到了浏览器地址栏,切换主题色的时候,地址栏的数据未发生变化.

### 🏞 期望结果

当切换主题后,地址栏的主题色配置同步更新,避免刷新后,造成组件选中主题色和配置色不同步.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
具体效果可以查看该视频https://github.com/joesdu/Bug-/blob/master/Video_2019-12-23_145536.wmv

**Comment by chenshuai2144** [comment]
已经修复
