### ISSUE TITLE
借助 react-undo 实现撤销/重做功能，并不成功

### ISSUE THREAD

**Issue by soeasyjx** [ant-design/ant-design-pro#5802]
借助 react-undo 实现撤销/重做功能，并不成功

借助 react-undo 实现撤销/重做功能，并不成功

### 📷 复现步骤

在 src/app.js 中添加如下代码 (参照 dvajs 官方示例)
import undoable from 'redux-undo';
const app = dva({
  onReducer: reducer => {
    return (state, action) => {
      const undoOpts = {};
      const newState = undoable(reducer, undoOpts)(state, action);
      // 由于 dva 同步了 routing 数据，所以需要把这部分还原
      return { ...newState, routing: newState.present.routing };
    },
  },
});

直接报错（见截图）

实现撤销/重做功能 借助 react-undo
不报错，能提示一个正常能运行的示例么

### © 版本信息

- Ant Design Pro 版本: 3.10.10
- redux-undo 版本：0.6.1
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17918538/71348998-d2d30680-25a8-11ea-96ea-40800513b91a.png)

**Comment by chenshuai2144** [comment]
一个两年前的包，估计 dva 根本不支持。
你是用的这个吗  https://github.com/omnidan/redux-undo

**Comment by soeasyjx** [comment]
是的，开始用的是react-undo 后来没用这个包了，自己实现了一下。请问还有其他可用的包么




| |
江鑫
邮箱：jx3313@163.com
|

签名由 网易邮箱大师 定制

在2019年12月24日 12:57，陈帅 写道：

一个两年前的包，估计 dva 根本不支持。
你是用的这个吗 https://github.com/omnidan/redux-undo

**Comment by soeasyjx** [comment]
redux-undo名称更正一下




| |
江鑫
邮箱：jx3313@163.com
|

签名由 网易邮箱大师 定制

在2019年12月24日 13:03，soeasyjx 写道：
是的，开始用的是react-undo 后来没用这个包了，自己实现了一下。请问还有其他可用的包么




| |
江鑫
邮箱：jx3313@163.com
|

签名由 网易邮箱大师 定制

在2019年12月24日 12:57，陈帅 写道：

一个两年前的包，估计 dva 根本不支持。
你是用的这个吗 https://github.com/omnidan/redux-undo

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
----
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
