### ISSUE TITLE
TreeSelect里的treeData的属性名能更改吗  例如Pid改为ParentId  title改为name

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5803]
![image](https://user-images.githubusercontent.com/47104575/71390365-0199bd00-263b-11ea-9499-a34e60dd4eb9.png)
我获得的数据是叫parentId和name  能不能把 Pid改为ParentId  title改为name

**Comment by chenshuai2144** [comment]
需要你自己 render 了
