### ISSUE TITLE
🧐[问题]有个打包的问题需要求助一下.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#5804]
### 🧐 问题描述
目前项目使用如下配置进行打包.

![新建位图图像](https://user-images.githubusercontent.com/13188169/71395673-d7072e80-2651-11ea-954d-3bbcb9aebd1c.png)
打包后无法在服务器非根目录下运行,我本机测试的nginx的目录为html/web-test,
![image](https://user-images.githubusercontent.com/13188169/71395763-5563d080-2652-11ea-9c1c-0f2a81e45471.png)

所以看了下Umi官方文档添加.
"exportStatic": {htmlSuffix:true,dynamicRoot:true}
以及关闭
history: 'hash'
后均出现部分资源文件访问的还是根目录的情况,希望官方能出一个较为通用的配置说明.

**Comment by chenshuai2144** [comment]
可以看看这里
https://umijs.org/zh/guide/deploy.html#%E4%BD%BF%E7%94%A8-runtime-%E7%9A%84-publicpath
估计是这个东西

**Comment by joesdu** [comment]
我调整了,一下publicPath的路径与服务端一致,能够正常取到部分静态文件了,但是使用umi-plugin-antd-theme 插件创建的主题文件还是出现了404

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 陈帅<mailto:notifications@github.com>
发送时间: 2019年12月24日 15:21
收件人: ant-design/ant-design-pro<mailto:ant-design-pro@noreply.github.com>
抄送: Joe Du<mailto:dygood@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ant-design/ant-design-pro] 🧐[问题]有个打包的问题需要求助一下. (#5804)


可以看看这里
https://umijs.org/zh/guide/deploy.html#%E4%BD%BF%E7%94%A8-runtime-%E7%9A%84-publicpath
估计是这个东西

**Comment by chenshuai2144** [comment]
SettingDrawer 上有个没开放的属性 publicPath，你设置一下试试

**Comment by joesdu** [comment]
🤣搞定了,太难了,要是没有你估计还能整很久.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 陈帅<mailto:notifications@github.com>
发送时间: 2019年12月24日 16:14
收件人: ant-design/ant-design-pro<mailto:ant-design-pro@noreply.github.com>
抄送: Joe Du<mailto:dygood@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ant-design/ant-design-pro] 🧐[问题]有个打包的问题需要求助一下. (#5804)


SettingDrawer 上有个没开放的属性 publicPath，你设置一下试试

**Comment by chenshuai2144** [comment]
我应该支持一下的。
