### ISSUE TITLE
🐛[BUG]antdesign rowcol布局消耗的时间非常多

### ISSUE THREAD

**Issue by liyi563257046** [ant-design/ant-design-pro#5807]
`数据源list记录数700条，光在row col上的布局所消耗的时间为2秒到2.5秒，为什么会这么慢呢？
<List
          rowKey="id"
          loading={loading}
          grid={{ gutter: 12, lg: 3, md: 2, sm: 1, xs: 1, }}
          dataSource={list}
          renderItem={item => {
              return (
                <List.Item key={item.MatchId}>
  
                    <Row>
                      <Col span={6} /><Col span={4} /><Col span={4} /><Col span={2} /><Col span={4} />
                    </Row>
                    <Row>
                      <Col span={1} /><Col span={12} /><Col span={1} /><Col span={2} /><Col span={4} /><Col span={4} />
                    </Row>
                    <Row>
                      <Col span={1} /><Col span={12} /><Col span={1} /><Col span={2} /><Col span={4} /><Col span={4} />
                    </Row>             

                </List.Item>
              );
          }}
         />`

**Comment by liyi563257046** [comment]
`数据源list记录数700条，光在row col上的布局所消耗的时间为2秒到2.5秒，为什么会这么慢呢？
<List
          rowKey="id"
          loading={loading}
          grid={{ gutter: 12, lg: 3, md: 2, sm: 1, xs: 1, }}
          dataSource={list}
          renderItem={item => {
              return (
                <List.Item key={item.MatchId}>
                  <Card hoverable className={styles.card}>
                    <Row>
                      <Col span={6} />
                      <Col span={4} />
                      <Col span={4} />
                      <Col span={2} />
                      <Col span={4} />
                    </Row>
                    <Row>
                      <Col span={1} />
                      <Col span={12} />
                      <Col span={1} />
                      <Col span={2} />
                      <Col span={4} />
                      <Col span={4} />
                    </Row>
                    <Row>
                      <Col span={1} />
                      <Col span={12} />
                      <Col span={1} />
                      <Col span={2} />
                      <Col span={4} />
                      <Col span={4} />
                    </Row>             
                  </Card>
                </List.Item>
              );
          }}
         />`

**Comment by liyi563257046** [comment]
数据源list记录数700条，光在row col上的布局所消耗的时间为2秒到2.5秒，为什么会这么慢呢？
<List
          rowKey="id"
          loading={loading}
          grid={{ gutter: 12, lg: 3, md: 2, sm: 1, xs: 1, }}
          dataSource={list}
          renderItem={item => {
              return (
                <List.Item key={item.MatchId}>
                  <Card hoverable className={styles.card}>
                    <Row>
                      <Col span={6} />
                      <Col span={4} />
                      <Col span={4} />
                      <Col span={2} />
                      <Col span={4} />
                    </Row>
                    <Row>
                      <Col span={1} />
                      <Col span={12} />
                      <Col span={1} />
                      <Col span={2} />
                      <Col span={4} />
                      <Col span={4} />
                    </Row>
                    <Row>
                      <Col span={1} />
                      <Col span={12} />
                      <Col span={1} />
                      <Col span={2} />
                      <Col span={4} />
                      <Col span={4} />
                    </Row>             
                  </Card>
                </List.Item>
              );
          }}
         />

**Comment by chenshuai2144** [comment]
和 Row 和 Col 有一点关系，但主要是demo 太多导致了，你可以使用虚拟滚动来实现一下。

https://ant.design/components/list-cn/#components-list-demo-infinite-virtualized-load
