### ISSUE TITLE
🧐[问题]  Cannot read property 'Provider' of undefined

### ISSUE THREAD

**Issue by cpu220** [ant-design/ant-design-pro#5808]
### 🧐 问题描述

 
 1.  升级了antd后，控制台提示 LocaleProvider 要被淘汰。然后发现这个文件是src/.umi/LocaleWrapper.jsx
2. 因为这个文件是umi自己创建的，所以进行了umi的升级。
3.  结果又出现  TypeError: Cannot read property 'Provider' of undefined
 

### 💻 示例代码

``` json
    "ant-design-pro": "^2.1.1",
    "antd": "3.26.4",
    "cheerio": "1.0.0-rc.2",
    "classnames": "^2.2.6",
    "core-js": "^2.6.5",
    "dva": "2.4.1",
    "file-saver": "2.0.1",
    "lodash": "^4.17.10",
    "lodash-decorators": "^6.0.0",
    "localStorage": "~1.0.3",
    "memoize-one": "^4.0.0",
    "moment": "^2.22.2",
    "path-to-regexp": "^2.4.0",
    "prop-types": "^15.5.10",
    "rc-animate": "^2.4.4",

    "react": "16.12.0",
    "react-container-query": "^0.11.0",
    "react-document-title": "^2.0.3",
    "react-media": "^1.8.0",
    "react-sortable-hoc": "1.8.3",

     "umi": "2.12.7",
    "umi-plugin-pro-block": "1.3.6",
    "umi-plugin-react": "1.14.10",
    "umi-request": "1.2.16",
```

### 🚑 其他信息
本地开发不报错，但打包后发布却一直控制台报错 TypeError: Cannot read property 'Provider' of undefined

翻遍了issues，没看到具体说明怎么解决的

**Comment by cpu220** [comment]
所以是umi版本升太高了还是什么？

**Comment by chenshuai2144** [comment]
umi 的新版本已经不会了
你的配置来看一下

**Comment by cpu220** [comment]
``` javascrtion
 
import {
  primaryColor,
  borderRadiusBase,
  layoutHeaderBbackground
} from '../src/defaultSettings';

export default {
  plugins: [
    [
      'umi-plugin-react',
      {
        antd: true,
        dva: {
          hmr: true,
        },
        targets: {
          ie: 11,
        },
        locale: {
          enable: true, // default false
          default: 'zh-CN', // default zh-CN
          baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
        },
        dynamicImport: {
          loadingComponent: './components/PageLoading/index',
        },
      },
    ],
    [
      'umi-plugin-pro-block',
      {
        moveMock: false,
        moveService: false,
        modifyRequest: true,
        autoAddMenu: true,
      },
    ],
  ],
  targets: {
    ie: 11,
  },
  publicPath: './',
  // cssPublicPath:'',
  /**
   * 路由相关配置
   */
  routes: [{
      path: '/pre',
      component: '../layouts/PreLayout',
      routes: [{
        path: '/pre',
        component: './BaseTemplate'
      }],
    },
    {
      path: '/iframe',
      component: '../layouts/IframeLayout',
      routes: [{
        path: '/iframe',
        component: './BaseTemplate'
      }],
    },
    {
      path: '/',
      component: '../layouts/BasicLayout',
      routes: [{
          path: '/',
          redirect: '/edit'
        },
        // dashboard
        {
          path: '/edit',
          name: 'edit',
          icon: 'smile',
          component: './BaseTemplate',
        }
      ],
    },

  ],
  history:'hash',
  hash:true,
  disableRedirectHoist: true,

  /**
   * webpack 相关配置
   */
  define: {
    APP_TYPE: process.env.APP_TYPE || '',
  }, 
  theme: {
    'primary-color': primaryColor,
    'border-radius-base': borderRadiusBase,
    'layout-header-background': layoutHeaderBbackground,
  },
  externals: {
    '@antv/data-set': 'DataSet',
  },
  ignoreMomentLocale: true,
  lessLoaderOptions: {
    javascriptEnabled: true,
  },
  chainWebpack(config, {
    webpack
  }) { 
    config.resolve.alias.set('@', require('path').resolve('src'));
    
  }
};


```

**Comment by chenshuai2144** [comment]
```
locale: {
          enable: true, // default false
          default: 'zh-CN', // default zh-CN
          baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
        },
```
不需要国际化可以把这个删掉

**Comment by cpu220** [comment]
> ```
> locale: {
>           enable: true, // default false
>           default: 'zh-CN', // default zh-CN
>           baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
>         },
> ```
> 
> 不需要国际化可以把这个删掉

已删掉，倒是不报错了。。。虽然还是没明白升级后哪出问题了

**Comment by chenshuai2144** [comment]
应该是 configProvider的问题

**Comment by llh1187** [comment]
> 几乎是默认，没什么改动
> 
> ```
>  
> import {
>   primaryColor,
>   borderRadiusBase,
>   layoutHeaderBbackground
> } from '../src/defaultSettings';
> 
> export default {
>   plugins: [
>     [
>       'umi-plugin-react',
>       {
>         antd: true,
>         dva: {
>           hmr: true,
>         },
>         targets: {
>           ie: 11,
>         },
>         locale: {
>           enable: true, // default false
>           default: 'zh-CN', // default zh-CN
>           baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
>         },
>         dynamicImport: {
>           loadingComponent: './components/PageLoading/index',
>         },
>       },
>     ],
>     [
>       'umi-plugin-pro-block',
>       {
>         moveMock: false,
>         moveService: false,
>         modifyRequest: true,
>         autoAddMenu: true,
>       },
>     ],
>   ],
>   targets: {
>     ie: 11,
>   },
>   publicPath: './',
>   // cssPublicPath:'',
>   /**
>    * 路由相关配置
>    */
>   routes: [{
>       path: '/pre',
>       component: '../layouts/PreLayout',
>       routes: [{
>         path: '/pre',
>         component: './BaseTemplate'
>       }],
>     },
>     {
>       path: '/iframe',
>       component: '../layouts/IframeLayout',
>       routes: [{
>         path: '/iframe',
>         component: './BaseTemplate'
>       }],
>     },
>     {
>       path: '/',
>       component: '../layouts/BasicLayout',
>       routes: [{
>           path: '/',
>           redirect: '/edit'
>         },
>         // dashboard
>         {
>           path: '/edit',
>           name: 'edit',
>           icon: 'smile',
>           component: './BaseTemplate',
>         }
>       ],
>     },
> 
>   ],
>   history:'hash',
>   hash:true,
>   disableRedirectHoist: true,
> 
>   /**
>    * webpack 相关配置
>    */
>   define: {
>     APP_TYPE: process.env.APP_TYPE || '',
>   }, 
>   theme: {
>     'primary-color': primaryColor,
>     'border-radius-base': borderRadiusBase,
>     'layout-header-background': layoutHeaderBbackground,
>   },
>   externals: {
>     '@antv/data-set': 'DataSet',
>   },
>   ignoreMomentLocale: true,
>   lessLoaderOptions: {
>     javascriptEnabled: true,
>   },
>   chainWebpack(config, {
>     webpack
>   }) { 
>     config.resolve.alias.set('@', require('path').resolve('src'));
>     
>   }
> };
> ```

您的配置帮了我一个大忙，谢谢您~

**Comment by jinjinwa** [comment]
我遇到了同样的问题。
    "umi-plugin-antd-icon-config": "^2.0.0-1",
    "umi": "2.13.0",
    "@ant-design/pro-layout": "^5.0.0",
