### ISSUE TITLE
🧐[问题]请教左侧默认菜单栏的滚动条有没有办法美化?

### ISSUE THREAD

**Issue by shui106** [ant-design/ant-design-pro#5809]
### 🧐 问题描述
当子菜单太多的时候, 左边的菜单栏会出现滚动条, 默认的不太好看.
我看有教程是可以使用Scrollbars来美化Sider的滚动条, 如果用了prolayout不知道有没有地方可以inject来加入Scrollbars? 请大神赐教.

![image](https://user-images.githubusercontent.com/3031491/71456766-0050c780-27d6-11ea-8c6c-a47b0386afc0.png)

**Comment by chenshuai2144** [comment]
@shui106  如果只是 chrome 的话可以用 css 来美化一下。
Scrollbars 需要 hack 一个自己的滚动条出来。你可以用 menuRender 来实现

**Comment by shui106** [comment]
> @shui106 如果只是 chrome 的话可以用 css 来美化一下。
> Scrollbars 需要 hack 一个自己的滚动条出来。你可以用 menuRender 来实现

好的, 我去试试, 非常感谢.
