### ISSUE TITLE
选择语言和用户操作鼠标移出后不会隐藏🐛[BUG]

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#5810]
![image](https://user-images.githubusercontent.com/18098618/71471054-4c692f80-2809-11ea-9950-f039a80b1fdd.png)

**Comment by chenshuai2144** [comment]
你是怎么做到的？
我湿了一下不会

**Comment by Lind-pro** [comment]
> 你是怎么做到的？
> 我试了一下不会

就是鼠标放上去会。偶尔会有这样暂时没发现原因。更新一下Pro好像就好了
