### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by yysfwls** [ant-design/ant-design-pro#5811]
新建文件夹
yarn create umi （选的js）
npm install
根目录umi block add ant-design-pro/TableList --js
![image](https://user-images.githubusercontent.com/29426633/71472050-8e47a500-280c-11ea-9f52-0d088f893189.png)

根据报错找了一下目录 也没找到
![image](https://user-images.githubusercontent.com/29426633/71473370-aa9a1080-2811-11ea-806e-0dfbf72cc73a.png)

**Comment by chenshuai2144** [comment]
用umi ui 把。你的路径拼错了。
https://pro.ant.design/docs/block-cn

**Comment by yysfwls** [comment]
> 用UMI UI把。你的路径拼错了。
> https://pro.ant.design/docs/block-cn

![image](https://user-images.githubusercontent.com/29426633/71496181-e1613c80-288c-11ea-928c-93c9ce4fe045.png)
就是这个路径嘛？

**Comment by yysfwls** [comment]
> 用UMI UI把。你的路径拼错了。
> https://pro.ant.design/docs/block-cn

![image](https://user-images.githubusercontent.com/29426633/71496223-284f3200-288d-11ea-8a94-93d7073551c9.png)
就是这个路径嘛

**Comment by chenshuai2144** [comment]
文档错误，要更新了。。。。

**Comment by yysfwls** [comment]
> 文档错误，要更新了。。。。

(；´д｀)ゞ   现在还怎么下载js呀

**Comment by yysfwls** [comment]
> 文档错误，要更新了。。。。


5555哪里还能下js版的啊。。。好着急

**Comment by yysfwls** [comment]
你好 ant design pro可以下载以前的版本吗 发现tableList区块  js版的代码全变了 想看一下以前的
如果您手边有的话 可以发一下吗 谢谢~

陈帅 <notifications@github.com> 于2019年12月27日周五 上午10:24写道：
