### ISSUE TITLE
🧐[问题]请问一下点击按钮如何跳转到外部链接？

### ISSUE THREAD

**Issue by liyi563257046** [ant-design/ant-design-pro#5813]
### 🧐 问题描述
这么写会跳转到/page1/https://github.com，会自动加上page1项目地址，
用window.location.href也是同样会加上项目地址，改如何跳转到外部地址呢？
jumpDetail = (matchId) => {
    this.props.dispatch(routerRedux.push({
      pathname: 'https://github.com',
    }))
  }

**Comment by afc163** [comment]
```
window.location.href = 'https://github.com';
```

**Comment by liyi563257046** [comment]
@afc163 
window.location.href = 'https://github.com'; 我在问题里写了呀，还是会跳转到项目地址+https://github.com'这样的路径。页面的提示是下面：
umi development 404 page
There's not a page yet at /match/page/www.baidu.com.

**Comment by afc163** [comment]
@liyi563257046 不太可能，给个重现。

**Comment by liyi563257046** [comment]
@afc163 找到问题了，location.href的地址要带上htttp，我写的www就会跳转到项目地址。多谢了
