### ISSUE TITLE
请问各位大佬，顶部模块如何关联菜单栏菜单啊？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#5815]
请问各位大佬，顶部模块如何关联菜单栏菜单啊？达到这样的效果？
![image](https://user-images.githubusercontent.com/37643958/71498700-4f5f3100-2898-11ea-9113-e6e4e236f08e.png)

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/example?anchor=%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80#%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80


这样可以吗

**Comment by zhuguangyue** [comment]
> https://prolayout.ant.design/example?anchor=%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80#%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80
> 
> 这样可以吗

类似这种，只是顶模块与左侧菜单栏，路由如何处理

**Comment by chenshuai2144** [comment]
@zhuguangyue 可以看我的 demo，你可以配置 

a layout
- b layout
- c layout

每个 layout 都会生成相应的菜单

**Comment by zhuguangyue** [comment]
> @zhuguangyue 可以看我的 demo，你可以配置
> 
> a layout
> 
> * b layout
> * c layout
> 
> 每个 layout 都会生成相应的菜单

官网有没有打算在面板风格那里支持这种风格啊

**Comment by chenshuai2144** [comment]
这个是具体业务的，不是功能的问题

**Comment by zhuguangyue** [comment]
![image](https://user-images.githubusercontent.com/37643958/77794955-b82c9400-70a7-11ea-9069-f3f2c491dc5a.png)
