### ISSUE TITLE
config.target('electron-renderer');

### ISSUE THREAD

**Issue by xuchao321** [ant-design/ant-design-pro#5817]
报错  require undefind 不用config.target('electron-renderer'); 就不报

**Comment by xuchao321** [comment]
<img width="740" alt="WeChate0c1faf0329c47533d32741ec1479347" src="https://user-images.githubusercontent.com/28084523/71505353-cd7f0000-28b7-11ea-8983-e6434f2832e3.png">

**Comment by chenshuai2144** [comment]
require 在 浏览器中是不存在的。但是在 electron 中存在，如果你配置了 targer = electron，node 相关的代码就不会进行编译，修改为浏览器能支持的行为。
如果你的项目需要在浏览器中运行，是不能打开这个配置的
