### ISSUE TITLE
请问国际化的formatMessage如何添加html标签

### ISSUE THREAD

**Issue by bailihuiyue** [ant-design/ant-design-pro#5818]
### 💻 示例代码
formatHTMLMessage({id:test});
国际化文件:{test:123\<br/\>456}
结果页面上原样输出,请问如何将br变成换行,不胜感激

**Comment by chenshuai2144** [comment]
我猜你需要他
 https://zh-hans.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
