### ISSUE TITLE
🧐[问题] fetch:blocks，出现FetchError:.....failed

### ISSUE THREAD

**Issue by wander-poet** [ant-design/ant-design-pro#5819]
### 🧐 问题描述

我看了一圈，好像没有和我错误一样的，我是npm run fetch:blocks后就出现报错，一个都无法安装，错误信息如下：

$ npm run fetch:blocks

> ant-design-pro@4.0.0 fetch:blocks D:\webproject\demo
> pro fetch-blocks && npm run prettier

- 🧐  find config.ts ...
√ 🧐  find config.ts ...
(node:34412) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\webProject\demo\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:34412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> ant-design-pro@4.0.0 prettier D:\webproject\demo
> prettier -c --write "**/*"

Checking formatting...
.eslintrc.js
.github\ISSUE_TEMPLATE\bug_report.md
.github\ISSUE_TEMPLATE\feature_request.md
.github\ISSUE_TEMPLATE\question.md
.github\workflows\rebase.yml
.gitpod.yml
.prettierrc.js
.stylelintrc.js
azure-pipelines.yml
[error] No parser could be inferred for file: CNAME
CODE_OF_CONDUCT.md
config\config.ts
config\defaultSettings.ts
config\plugin.config.ts
config\themePluginConfig.ts
jest-puppeteer.config.js
jest.config.js
jsconfig.json
lambda\api.js
lambda\mock\index.js
lambda\mock\matchMock.js
mock\notices.ts
mock\route.ts
mock\user.ts
package-lock.json
README.fr-FR.md
README.ja-JP.md
README.md
README.pt-BR.md
README.ru-RU.md
README.tr-TR.md
README.zh-CN.md
src\components\Authorized\Authorized.tsx
src\components\Authorized\AuthorizedRoute.tsx
src\components\Authorized\CheckPermissions.tsx
src\components\Authorized\index.tsx
src\components\Authorized\PromiseRender.tsx
src\components\Authorized\renderAuthorize.ts
src\components\Authorized\Secured.tsx
src\components\GlobalHeader\AvatarDropdown.tsx
src\components\GlobalHeader\index.less
src\components\GlobalHeader\NoticeIconView.tsx
src\components\GlobalHeader\RightContent.tsx
src\components\HeaderDropdown\index.less
src\components\HeaderDropdown\index.tsx
src\components\HeaderSearch\index.less
src\components\HeaderSearch\index.tsx
src\components\NoticeIcon\index.less
src\components\NoticeIcon\index.tsx
src\components\NoticeIcon\NoticeList.less
src\components\NoticeIcon\NoticeList.tsx
src\components\PageLoading\index.tsx
src\components\SelectLang\index.less
src\components\SelectLang\index.tsx
src\e2e\__mocks__\antd-pro-merge-less.js
src\e2e\baseLayout.e2e.js
src\e2e\topMenu.e2e.js
src\global.less
src\global.tsx
src\layouts\BasicLayout.tsx
src\layouts\BlankLayout.tsx
src\layouts\SecurityLayout.tsx
src\layouts\UserLayout.less
src\layouts\UserLayout.tsx
src\locales\en-US.ts
src\locales\en-US\component.ts
src\locales\en-US\globalHeader.ts
src\locales\en-US\menu.ts
src\locales\en-US\pwa.ts
src\locales\en-US\settingDrawer.ts
src\locales\en-US\settings.ts
src\locales\pt-BR.ts
src\locales\pt-BR\component.ts
src\locales\pt-BR\globalHeader.ts
src\locales\pt-BR\menu.ts
src\locales\pt-BR\pwa.ts
src\locales\pt-BR\settingDrawer.ts
src\locales\pt-BR\settings.ts
src\locales\zh-CN.ts
src\locales\zh-CN\component.ts
src\locales\zh-CN\globalHeader.ts
src\locales\zh-CN\menu.ts
src\locales\zh-CN\pwa.ts
src\locales\zh-CN\settingDrawer.ts
src\locales\zh-CN\settings.ts
src\locales\zh-TW.ts
src\locales\zh-TW\component.ts
src\locales\zh-TW\globalHeader.ts
src\locales\zh-TW\menu.ts
src\locales\zh-TW\pwa.ts
src\locales\zh-TW\settingDrawer.ts
src\locales\zh-TW\settings.ts
src\manifest.json
src\models\connect.d.ts
src\models\global.ts
src\models\login.ts
src\models\setting.ts
src\models\user.ts
src\pages\404.tsx
src\pages\Admin.tsx
src\pages\Authorized.tsx
src\pages\document.ejs
src\pages\user\login\components\Login\index.less
src\pages\user\login\components\Login\index.tsx
src\pages\user\login\components\Login\LoginContext.tsx
src\pages\user\login\components\Login\LoginItem.tsx
src\pages\user\login\components\Login\LoginSubmit.tsx
src\pages\user\login\components\Login\LoginTab.tsx
src\pages\user\login\components\Login\map.tsx
src\pages\user\login\index.tsx
src\pages\user\login\locales\en-US.ts
src\pages\user\login\locales\zh-CN.ts
src\pages\user\login\locales\zh-TW.ts
src\pages\user\login\style.less
src\pages\Welcome.less
src\pages\Welcome.tsx
src\service-worker.js
src\services\login.ts
src\services\user.ts
src\typings.d.ts
src\utils\authority.test.ts
src\utils\authority.ts
src\utils\Authorized.ts
src\utils\request.ts
src\utils\utils.less
src\utils\utils.test.ts
src\utils\utils.ts
tests\run-tests.js
tests\setupTests.js
tsconfig.json
Code style issues fixed in the above file(s).

该试的方法都试过了，都没用，网上也没找到跟我类似的，unable to verify the first certificate对应的方法也试过，还是一样。

### 🚑 其他信息
系统是Win10，Nodejs 10.16.3  UMI 2.12.7 

![image](https://user-images.githubusercontent.com/24449934/71512000-52294880-28cf-11ea-9151-daaef647e016.png)

**Comment by chenshuai2144** [comment]
@wander-poe 你是开了代理吗？

**Comment by wander-poet** [comment]
@chenshuai2144 没有 不过用的公司笔记本是加过域 有安全软件 可能有影响 我拿自己的mac倒是没问题一次就成功了 我把mac安装目录下pages内容全拷到win对应目录下 改了config 又试了下可以编译成功 区块也都有用 至少能先用 反正windows真是头疼 各种奇怪问题

**Comment by chenshuai2144** [comment]
这个看起来是 github 拦住了你，说你的证书不对

**Comment by whyzsm** [comment]
我的mac安装区块也有报这个错，安装区块只能是完全的链接地址安装，可视化工具安装失败。

**Comment by wander-poet** [comment]
> 我的mac安装区块也有报这个错，安装区块只能是完全的链接地址安装，可视化工具安装失败。

我是window的笔记本有问题 mac还好 一切正常

**Comment by zs9720** [comment]
，老哥  你这个问题解决了没

**Comment by Wananme** [comment]
提供一个解决方案 可能不适合所有人：1、下载官方demo(https://github.com/ant-design/ant-design-pro/ )，2、解压使用命令行进入项目所在路径，执行npm install。 3、最终要的一步  不要执行npm start! npm start! npm start! npm start!。。。。直接执行npm run fetch.block!!!npm run fetch.block!!!npm run fetch.block!!! 等待十几分钟以后 下载完毕后 在执行npm start！！！这个是在我被折磨了一天以后 偶然试出来的方法，希望有帮助
