### ISSUE TITLE
localhost 打開需要登入

### ISSUE THREAD

**Issue by jenniferkao0614** [ant-design/ant-design-pro#582]
我想要請問一下，我剛剛clone了這個repo，但一打開localhost只能看到登入畫面呢？

<img width="1163" alt="2018-01-05 4 58 08" src="https://user-images.githubusercontent.com/24220615/34602096-7dc65736-f239-11e7-9009-9aeacf9c3071.png">

**Comment by chenshuai2144** [comment]
报错了 正在修复!!!
#580

**Comment by jenniferkao0614** [comment]
所以我需要申請帳號密碼，才有辦法登入是嗎～～

**Comment by chenshuai2144** [comment]
对呀  账号密码写在提示上了
