### ISSUE TITLE
🧐[问题]ProTable 搜索表单 更新之后，有些应用场景怎么使用更优雅

### ISSUE THREAD

**Issue by keke122765** [ant-design/ant-design-pro#5820]
### 🧐 问题描述
ProTable 的搜索表单目前与 Columns关联，而有些搜索场景并不是一一对应的搜索，比如
1、跨字段模糊搜索
2、日期范围搜索
3、姓和名 两列合一搜索

针对以上应用场景，官方封装的搜索表单是不是无法使用，或者说官方封装只考虑一一对应的搜索？
### 🚑 其他信息

如下场景
![image](https://user-images.githubusercontent.com/44694221/71540017-d3401880-297f-11ea-9d37-849e0f713941.png)

**Comment by chenshuai2144** [comment]
可以用 params 自定义，也可以自定义 renderFromItem, 我们无法遍历所有行为的。

为了方便使用我们保留了所有antd的事件和方法。

**Comment by keke122765** [comment]
@chenshuai2144 大佬您看下是不是像这样子，需要new一个Promise，我是新手，多多指教。
![image](https://user-images.githubusercontent.com/44694221/71553721-0c938980-2a4f-11ea-8e00-f95ffc475ebd.png)

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#toolbar-%E6%90%9C%E7%B4%A2

给你写了个 demo

**Comment by keke122765** [comment]
多谢！
