### ISSUE TITLE
👑 [需求]可自定义升级TypeScript

### ISSUE THREAD

**Issue by linxiangjun** [ant-design/ant-design-pro#5821]
### 🥰 需求描述

比如TypeScript 3.7 Beta发布了我想要使用的特性，但是antd pro默认安装的版本为3.5.2，也没有可以手动配置的地方，如果可以支持自定义升级就会更加的方便！

### 🧐 解决方案

整合的umijs中支持更新package

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
项目在你电脑硬盘上你想做什么都可以的，但是beta版本生态可能跟不上，你需要自己做很多努力。

**Comment by afc163** [comment]
@chenshuai2144 当前的 TypeScript 版本是多少？去哪里看

**Comment by chenshuai2144** [comment]
3.7.3 vscode 中就能看到

**Comment by afc163** [comment]
@chenshuai2144 我的意思是 pro/umi 代码里哪里控制了这个。

**Comment by chenshuai2144** [comment]
代码里没有控制的，是走的用户默认，但是用了最新的beta，eslint 和 prettier不支持，也需要升级到相应的版本

**Comment by afc163** [comment]
用户默认是哪里默认的？现在 pro 代码下载下来默认 ts 版本是多少？

**Comment by chenshuai2144** [comment]
> 用户默认是哪里默认的

用户的 package.json

> 现在 pro 代码下载下来默认 ts 版本是多少？

是最新的稳定版

**Comment by afc163** [comment]
那应该可以的，现在最新稳定版本的 TypeScript 是 3.7.4：https://www.npmjs.com/package/typescript

**Comment by chenshuai2144** [comment]
他的诉求应该是想使用 TypeScript  Beta 版本，但是发现编译过不去。因为对应的生态没有跟上来，ts-loader eslint prettier babel 的版本都要相应的升级

**Comment by afc163** [comment]
楼主想用的应该就是 typescript@3.7
