### ISSUE TITLE
🐛[BUG]屏幕尺寸改变,顶部菜单栏显示菜单显示个数没有自适应,(首次渲染的个数有点问题)

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#5822]
### 🐛 bug 描述

首次访问,顶部菜单个数渲染跟多次旋转屏幕后的结果不同. 
![A60F1F0B-DC49-4CD5-AC52-AED32D594574](https://user-images.githubusercontent.com/15940920/71567275-bbd86b00-2af8-11ea-9d55-88b3b957591a.png)
![FCA5ABC9-3A6B-40B2-87AF-52329B0EED93](https://user-images.githubusercontent.com/15940920/71567278-be3ac500-2af8-11ea-9728-2c8d7fc8578c.png)
![ADAB71AE-BA5A-4ECC-90AB-AEE586040F3F](https://user-images.githubusercontent.com/15940920/71567279-c09d1f00-2af8-11ea-9595-3e220e70f3fb.png)

### 🏞 期望结果

多次旋转屏幕,顶部菜单栏显示相同

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新依赖即可。

**Comment by l745230** [comment]
> 更新依赖即可。

是指删掉node_modules,重新npm i 吗?
我试了下,还是老样子.

**Comment by chenshuai2144** [comment]
怎么重现呢？或者有没有 gif 什么的，我尝试了一下不会有问题

**Comment by l745230** [comment]
@chenshuai2144 修改浏览器窗口大小,进行访问 渲染正常.
使用调试模式,切到ipad尺寸,才会重现...
回头我试下打包部署到服务器上,用真机ipad访问试试.

**Comment by l745230** [comment]
真机ipad访问时,重现不出来-.-
