### ISSUE TITLE
v4.0 defaultSettings.ts配置primaryColor: 'dust'无效,还是默认的蓝色🐛[BUG]

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#5823]
### 🐛 bug 描述

重新npm install了,启动还是蓝色.
配置的primaryColor: 'dust'不生效

![FB12D7E7-CA34-4396-B040-556AC49F3CA6](https://user-images.githubusercontent.com/15940920/71568705-5c805800-2b04-11ea-9fd1-59cff6a2c90a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/666b74d65df6472dae9a96d06eaa3e315ac098f7/config/config.ts#L118

@chenshuai2144 这个配置是有问题的吧，应该直接是颜色色值。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/blob/4e62a9f2788de5a0f1a574b1e2ce570fa6b5c5a7/config/config.ts#L131-L134

漏了配置？

**Comment by l745230** [comment]
@afc163 在config.ts theme中配置'primary-color': '#F5222D'. 覆盖掉全局的less变量能生效,
但是pro官网上 主题色:薄暮 复制出来的配置是"primaryColor": "dust". 
能否直接使用dust这个值呢?

**Comment by chenshuai2144** [comment]
@afc163  应该是 drawer 里面用了 key 不是颜色值导致的。

**Comment by chenshuai2144** [comment]
> 能否直接使用dust这个值呢?

@l745230  需要使用动态换主题插件才能使用 dust 这个值。dust 是我们定义出来的值，并不是一个标准的 色值。

**Comment by l745230** [comment]
@chenshuai2144  
1.项目不需要在线动态更换主题功能,就只能在theme中覆盖掉primary-color吗?
2.在哪儿能看到dust对应的值呢? https://github.com/chenshuai2144/umi-plugin-antd-theme 这个链接进去没找到相关的配置.
3.使用主题色:薄暮,如果在theme中配置, 除了'primary-color'='#F5222D' ,我还需要覆盖掉其他变量吗?

**Comment by chenshuai2144** [comment]
> 项目不需要在线动态更换主题功能,就只能在theme中覆盖掉primary-color吗?

是的

>  在哪儿能看到dust对应的值呢? https://github.com/chenshuai2144/umi-plugin-antd-theme 这个链接进去没找到相关的配置.

可以在这里看到
https://github.com/ant-design/ant-design-pro/blob/4e62a9f2788de5a0f1a574b1e2ce570fa6b5c5a7/config/themePluginConfig.ts

> 使用主题色:薄暮,如果在theme中配置, 除了'primary-color'='#F5222D' ,我还需要覆盖掉其他变量吗?

不需要，antd 中大部分颜色是根据主色计算出来的

**Comment by l745230** [comment]
@chenshuai2144 好的,谢谢.
