### ISSUE TITLE
请安直接脚手架创建项目的路由嵌套格式和按照了区块页的不一样的

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#5824]
### 🧐 请安直接脚手架创建项目的路由嵌套格式和按照了区块页的不一样的

- 未安装区块前，路由嵌套在SecurityLayout组件下

![1](https://user-images.githubusercontent.com/37643958/71573454-f1904a80-2b1e-11ea-80af-6548ae67c308.png)
- 安装区块页面后，所有路由嵌套在BlankLayout组件下，而SecurityLayout组件不使用。
![2](https://user-images.githubusercontent.com/37643958/71573515-43d16b80-2b1f-11ea-82a5-ac577c0b4d34.png)

- 这是什么原因，各位大神方便解释一下吗？

**Comment by chenshuai2144** [comment]
fetch:blocks 是为了部署我们的官网，官网不需要权限

**Comment by zhuguangyue** [comment]
> fetch:blocks 是为了部署我们的官网，官网不需要权限

正常开发项目是按照SecurityLayout这种？

**Comment by chenshuai2144** [comment]
SecurityLayout 可以按需使用，如果你的权限是后端控制的话。
