### ISSUE TITLE
🧐[求助]eslint如何与vscode结合 保存时自动fix

### ISSUE THREAD

**Issue by ruige24601** [ant-design/ant-design-pro#5825]
问题：在vscode中安装ESLint插件，并配置保存时进行fix：
 `"eslint.autoFixOnSave": true,` ，但是保存时，并没有自动fix。（执行npm run lint:fix 可以正常fix）
期望：保存时，自动fix。
求教：请问应该如何配置，才能保存时自动fix

**Comment by chenshuai2144** [comment]
你还真难住我了，是一般都是用 prettier，eslint fix 都是靠人肉。

**Comment by DiamondYuan** [comment]
```
{
 "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
```

安装 eslint 插件就好了
