### ISSUE TITLE
🧐[问题]官网在微信中白屏,无法浏览.

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#5829]
### 🧐 问题描述

![321577929175_ pic](https://user-images.githubusercontent.com/15940920/71648779-cf2b4680-2d43-11ea-97ae-bcd21680887e.jpg)

IOS   9.3.3
微信  6.7.3

**Comment by chenshuai2144** [comment]
试了一下是可以的，你的 ios 版本太低了吗？

**Comment by imhele** [comment]
iOS 13.3 Safari +0.5，半白屏

**Comment by chenshuai2144** [comment]
@jljsj33  是不是需要做特殊配置？

**Comment by l745230** [comment]
我把官网代码下载,改了target ie:8后,ios 9.3.3 微信能访问.
