### ISSUE TITLE
路由注册与侧边菜单显示问题

### ISSUE THREAD

**Issue by zhanghe1992** [ant-design/ant-design-pro#583]
有这样一个需求，在侧边栏显示主菜单，该菜单下没有下拉菜单，点击该菜单会进入到表格形式的列表展示页面，该页面上有一个添加按钮，点击添加按钮会跳转到新建页面(因为新建交互较复杂，没选modal框)。这是路由与菜单显示问题就出现了，由列表页路由/user => /user/add，现在是这样配置，
menu.js中配置为:
`{name: '用户列表', path: 'user'}`,
router.js中配置为:
`{'/user': {xxx}, '/user/add': {xxx}}`
现在输入/user/add，就会加载那个列表布局。
看了路由的说明文档，感觉路由注册这块用起来略微麻烦，像这种需求，怎样配置路由和菜单才合理呢？

**Comment by ddcat1115** [comment]
`/user` 和 `/user/add` 在布局上没有包含关系（`/user/add` 不用渲染 `/user` 对应的组件），两者需要在同一层 layout 中渲染，是这个意思么？是的话，可以参考 [嵌套路由同级展示](https://github.com/ant-design/ant-design-pro-site/blob/master/docs/router-and-nav.md#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA)
