### ISSUE TITLE
最新antdpro v2白屏

### ISSUE THREAD

**Issue by ChallengerDefier** [ant-design/ant-design-pro#5830]
最新依赖umi 2.12.8会导致项目启动后白屏 且未报错

**Comment by Evan-Future** [comment]
遇到了，虽然页面看似无错，但是页面console还是输出了warning： Invalid prop `children` supplied to `Media`.

**Comment by chenshuai2144** [comment]
pro 好像没问题，你们有重现吗？有两个这种问题了

**Comment by yutingzhao1991** [comment]
https://github.com/umijs/umi/issues/3858 是这个问题

**Comment by Evan-Future** [comment]
> [umijs/umi#3858](https://github.com/umijs/umi/issues/3858) 是这个问题

解决方法是？？好像这个也没说解决方法是什么

**Comment by chenshuai2144** [comment]
在 umi 中跟踪问题，会有人接活的

**Comment by Evan-Future** [comment]
> 在 umi 中跟踪问题，会有人接活的

那目前临时解决方案是什么？去掉检查？还是降级umi版本？公司需要项目产出

**Comment by Ka-Houl** [comment]
> > 在 umi 中跟踪问题，会有人接活的
> 
> 那目前临时解决方案是什么？去掉检查？还是降级umi版本？公司需要项目产出
我尝试了降级umi和react-midia版本，虽然没有报这个错了，但是左侧路由导航栏没有了数据了

**Comment by Evan-Future** [comment]
> > > 在 umi 中跟踪问题，会有人接活的
> > 
> > 
> > 那目前临时解决方案是什么？去掉检查？还是降级umi版本？公司需要项目产出
> > 我尝试了降级umi和react-midia版本，虽然没有报这个错了，但是左侧路由导航栏没有了数据了

我的解决方案是直接去掉Media，改成：(props => <BasicLayout {...props} isMobile={false} />); 即可正常

**Comment by Ka-Houl** [comment]
> > 在 umi 中跟踪问题，会有人接活的
> 
> 那目前临时解决方案是什么？去掉检查？还是降级umi版本？公司需要项目产出
我尝试了降级umi和react-midia版本，虽然没有报这个错了，但是左侧路由导航栏没有了数据了


> > > > 在 umi 中跟踪问题，会有人接活的
> > > 
> > > 
> > > 那目前临时解决方案是什么？去掉检查？还是降级umi版本？公司需要项目产出
> > > 我尝试了降级umi和react-midia版本，虽然没有报这个错了，但是左侧路由导航栏没有了数据了
> 
> 我的解决方案是直接去掉Media，改成：(props => <BasicLayout {...props} isMobile={false} />); 即可正常

感谢~问题已暂时解决

**Comment by ycjcl868** [comment]
试试 umi@2.12.9-beta.2， 我这里是ok的。
可以把版本号写成 `"umi": "^2.12.9-beta.2"`
