### ISSUE TITLE
🧐菜单跳转到外部地址 这个是可以将外部地址的内容在面包屑里面显示吗

### ISSUE THREAD

**Issue by 15010970141** [ant-design/ant-design-pro#5834]
### 💻 示例代码

{
    path: 'https://pro.ant.design/docs/getting-started-cn',
    target: '_blank', // 点击新窗口打开
    name: "文档",
}文档上的这段代码加上了不好使

**Comment by chenshuai2144** [comment]
> 可以将外部地址的内容在面包屑里面显示吗

这个是不支持的，可以提个pr，自己支持一把
