### ISSUE TITLE
ant-design-pro form 增加validateTrigger 无效🐛[BUG]

### ISSUE THREAD

**Issue by begoliu** [ant-design/ant-design-pro#5836]
### 💻 复现代码

<LoginComponents
          defaultActiveKey={type}
          onTabChange={this.onTabChange}
          onSubmit={this.handleSubmit}
          onCreate={(form?: FormComponentProps['form']) => {
            this.loginForm = form;
          }}
        >
          {/*<Tab key="account" tab={formatMessage({ id: 'user-login.login.tab-login-credentials' })}>*/}
            {errorMsg &&
              loginType === 'account' &&
              !submitting &&
              this.renderMessage(
                errorMsg
              )}
            <UserName
              name="phone_number"
              placeholder={`请输入手机号!`}
              onChange={this.onErrorMsgStatus}
              allowClear={true}
              rules={[
                {
                  required: true,
                  message: '请输入手机号!',
                },
                {
                  len:11,
                  pattern: regexPhone(),
                  message: '请输入正确的手机号',
                },
              ]}
              // trigger={['onBlur']}
              validateTrigger={'onBlur'}
            />

---------------------------------------------------------------------
 public static UserName: React.FunctionComponent<LoginItemProps>;
-----------------------------------------------
export interface LoginItemProps extends GetFieldDecoratorOptions {
  name?: string;
  style?: React.CSSProperties;
  onGetCaptcha?: (event?: MouseEvent) => void | Promise<boolean> | false;
  placeholder?: string;
  buttonText?: React.ReactNode;
  onPressEnter?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  countDown?: number;
  getCaptchaButtonText?: string;
  getCaptchaSecondText?: string;
  updateActive?: LoginContextProps['updateActive'];
  type?: string;
  defaultValue?: string;
  form?: FormComponentProps['form'];
  customProps?: { [key: string]: unknown };
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  tabUtil?: LoginContextProps['tabUtil'];
  allowClear?:boolean;
  autoComplete?:'off'|'on'
}

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd@4 修改了用法
