### ISSUE TITLE
🐛[BUG]npm create umi构建的ant design pro 的version为1.0.0我手动git 克隆的version4.0.0

### ISSUE THREAD

**Issue by code5257** [ant-design/ant-design-pro#5838]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
是专门帮你设置的，具体可以看 create umi 中的配置。
https://github.com/umijs/create-umi/blob/28281dcde47cefac40fa23cf3143d89bf77515ea/lib/generators/ant-design-pro/index.js#L119
