### ISSUE TITLE
固定侧边栏菜单后, 子选项错位 🐛[BUG]

### ISSUE THREAD

**Issue by PangHuFatcat** [ant-design/ant-design-pro#5840]
### 🐛 bug 描述

固定侧边栏菜单后, 子选项错位

### 📷 复现步骤
先固定菜单栏, 然后收起菜单栏, 鼠标移到菜单栏子选择后错位了

### © 版本信息

- Ant Design Pro 版本:  4.10.0
- umi 版本:  2.8.7
- 浏览器环境: 所有浏览器环境
- 开发环境: 所有开发环境

### 🚑 其他信息
![242e005860e6d5b098957980f524ddc](https://user-images.githubusercontent.com/33117989/71707765-3cfc6e80-2e27-11ea-8dda-a0b03f75cb77.png)
![9e2a4396940b2f9eb5355e984f2b6b5](https://user-images.githubusercontent.com/33117989/71707769-4259b900-2e27-11ea-9f4a-cd907eae92ec.png)

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis?fixedHeader=true&fixSiderbar=true
是好的，可否提供更多的信息？

**Comment by PangHuFatcat** [comment]
> https://preview.pro.ant.design/dashboard/analysis?fixedHeader=true&fixSiderbar=true
> 是好的，可否提供更多的信息？

是github上的https://github.com/ant-design/ant-design-pro.git库哇, 我刚刚拉取下来看, 还是有这个问题

**Comment by PangHuFatcat** [comment]
> https://preview.pro.ant.design/dashboard/analysis?fixedHeader=true&fixSiderbar=true
> 是好的，可否提供更多的信息？

在github上的https://github.com/ant-design/ant-design-pro.git 库, master主分支, 要把node_modules删了重新yarn install 才会出现, 真的有这个bug, 在修复了的话, 能否回复一下

**Comment by afc163** [comment]
删了 yarn.lock 再重新安装 node_modules 试试。
