### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by LamdoHeaven** [ant-design/ant-design-pro#5841]
### 🥰 需求描述 二级以下路由的权限管理

目前BasicLayout.tsx中，通过getAuthorityFromRouter( )方法只能获取一级路由的权限，无法正确获取深层次路由的权限。 
### 🧐 解决方案
遍历嵌套路由，获取正确的页面权限

/**
 * props.route.routes
 * @param router [{}]
 * @param pathname string
 */
export const getAuthorityFromRouter = <T extends { path: string, routes?: T[], authority?: string[] | string}>(
  router: T[] = [],
  pathname: string,
): T | undefined => {
  let authRoute
  const route = router.find(({ path, routes, authority }) => {
    if (!path) return false
    if (pathRegexp(path).exec(pathname)) {
      return true
    }
    if (routes) {
      //@ts-ignore
      authRoute = getAuthorityFromRouter(routes.map(e => ({
        ...e,
        authority: e.authority || authority
      })), pathname)
      return authRoute
    }
    return false
  });
  authRoute = authRoute || route
  if (authRoute) return authRoute;
  return undefined;
};

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
----
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
