### ISSUE TITLE
分析页<销售额类别占比>扇形统计图🐛[BUG]🐛[BUG]

### ISSUE THREAD

**Issue by Jidahan** [ant-design/ant-design-pro#5843]
### 🐛 bug 描述

当关掉一些图例后切换到第二个tab选项，被关掉的数据源就无法进行显示以及图例消失

### 🏞 期望结果

当关掉一些图例后切换到第二个tab选项，被关掉的数据源正常显示在页面中可以进行显示与不显示操作

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
新的区块中已经重写
