### ISSUE TITLE
🐛[BUG] antdPro为什么渲染4次

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design-pro#5844]
github上拉了antdPro(V4)，在Welcome页面里加一行输入，为什么输出了4次，V2版本倒是没有

**Comment by ywy94ywy** [comment]
对了，basiclayout页面中只会渲染一次，它旗下的子页面就会渲染4次

**Comment by afc163** [comment]
看看 https://www.npmjs.com/package/@ant-design/pro-layout 的本地安装版本是多少？

**Comment by ywy94ywy** [comment]
![image](https://user-images.githubusercontent.com/22499767/71710980-c026c000-2e39-11ea-84c1-3d3a994bba64.png)
一开始是4.5.9，我更新了一下，但是页面上还是4次

**Comment by chenshuai2144** [comment]
最新的应该只有3次了，用了 hooks 就是这样的，因为有一些的数据会进行计算，然后触发 update，但是 create 只触发了一次，
要是非常建议这些，可以继续用 class 模式，render 执行次数就会减少很多。

**Comment by ywy94ywy** [comment]
倒是不太建议这个，倒是子页面调试的时候会变得比较烦，比如表格render，查看每行信息之类的多次输出数据，可能就会成倍的污染控制台，一方面是不好找，一方面是卡顿

**Comment by chenshuai2144** [comment]
@ywy94ywy  我们会尽力优化，但是 hooks 的使用不可避免的会造成 update 的问题。
你可以在 useEffect 中输出。

**Comment by fanhualei** [comment]
关注一下

**Comment by guozhengzhongGit** [comment]
@chenshuai2144 对的，所以现在看到项目里各种不规范的hooks写法好无奈

**Comment by ywy94ywy** [comment]
> @chenshuai2144 对的，所以现在看到项目里各种不规范的hooks写法好无奈

怎么样的才是规范的啊，有没有规范文档之类的

**Comment by guozhengzhongGit** [comment]
> > @chenshuai2144 对的，所以现在看到项目里各种不规范的hooks写法好无奈
> 
> 怎么样的才是规范的啊，有没有规范文档之类的
就是说大家只是直接开始写hooks，根本不关心class变函数以后有什么变化，effect 的依赖该不该写，哪个该写哪个可以优化掉，useMemo和useCallback要么不用，要么见一个函数就包一下，完全不分析，就是为写hooks而写，看着这种代码很烦
