### ISSUE TITLE
带参数的路由在某些浏览器下面不能正常跳转

### ISSUE THREAD

**Issue by jhyy1986** [ant-design/ant-design-pro#5845]
### 🐛 bug 描述
我使用的ant-pro版本是2.3.1 使用带参数的路由配置
{
            path: '/data/supplierDetail/:supplierID',
            component: './Supplier/Detail',
}
发现在 Edge 40.15063.674.0版本，Chrome 62.0.3202.94， 60.0.3112.78版本下无法匹配到路由，跳转不到指定的页面上去
![图片](https://user-images.githubusercontent.com/14037039/71710296-856f5880-2e36-11ea-99d3-22039c1b18a5.png)

### 💻 复现代码

希望可以正常匹配路由

### © 版本信息

- Ant Design Pro 版本: [2.3.1]
- umi 版本 2.4.4
- 浏览器环境
Edge 40.15063.674.0，
Chrome 62.0.3202.94， 60.0.3112.78
- 开发环境 [windows]

**Comment by jhyy1986** [comment]
补充一点，由于特殊的业务需求，我的路由是通过window.open打开的

**Comment by jhyy1986** [comment]
这个问题有人遇到过吗，加班加了半夜了，还是解决不了

**Comment by chenshuai2144** [comment]
感觉是因为路由配置错误导致的。
来个重现吧
