### ISSUE TITLE
IE10下，报错如下，网页无法打开🐛[BUG]

### ISSUE THREAD

**Issue by fantasy-wc** [ant-design/ant-design-pro#5847]
### 🐛 bug 描述
用antd pro新搭建的项目，在chrome，IE11下正常，但是IE10下就会报错，页面无法打开

### 📷 复现步骤
Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead.
SCRIPT5022: 引发了异常但未捕获
umi.js (15544,5)
![image](https://user-images.githubusercontent.com/24581530/71714835-4ea33d80-2e4a-11ea-979a-252af30749d0.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
我们支持到 ie11，ie10 的问题需要自己解决了。
你需要关掉 代码分割 locale 等功能
