### ISSUE TITLE
PageHeaderWrapper中返回按钮不显示👑 [需求]

### ISSUE THREAD

**Issue by sunxia628** [ant-design/ant-design-pro#5848]
### 🥰 需求描述
因为需要通过返回按钮来返回上一页，由于路由中可能带有参数，通过面包屑点击返回会造成参数丢失，所以希望可以显示返回按钮，通过自定义返回来实现返回上一页或指定页面；另外https://pro.ant.design/docs/layout-component-cn文档中标明：“PageHeaderWrapper 支持 Tabs 和 PageHeader 的所有属性。”有严重误导性！

**Comment by afc163** [comment]
来个 PR 帮忙修改一下文档。
