### ISSUE TITLE
在有表格的页面使用对话框组件时的性能问题

### ISSUE THREAD

**Issue by w11th** [ant-design/ant-design-pro#585]
操作系统：macOS High Sierra
浏览器：Safari
测试页面：[https://preview.pro.ant.design/#/list/table-list](url)
问题重现：修改页面 DOM，向 Table 添加数据，当条目数量多于 20 个的时候，对话框的弹入弹出就出现明显的迟滞
尝试解决的结果：
对话框在弹入弹出的时候，Safari 的渲染时间都特别长，卡死了整个浏览器

<img width="1279" alt="2018-01-05 7 58 51" src="https://user-images.githubusercontent.com/11044635/34608379-09dae142-f253-11e7-97d4-62e7361ff968.png">

最后排查到的结果是，对话框在弹入弹出的时候会更改 body overflow:hidden 属性。这个原因导致的渲染时间特别长。

请问这个情况有比较合适的解决方式吗？

感谢你们的工作 :)

**Comment by afc163** [comment]
@yesmeck 貌似又有一个类似的问题。https://github.com/ant-design/ant-design/issues/7799

**Comment by w11th** [comment]
补充一下：在 Chrome 下就没有这个问题

**Comment by yesmeck** [comment]
Table 这个滚动条问题好多，要不就不用原生的滚动条了。

**Comment by chenshuai2144** [comment]
这个锅是Safari的吧

**Comment by yesmeck** [comment]
Chrome 也有不同的问题。https://github.com/ant-design/ant-design/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Table+%E6%BB%9A%E5%8A%A8%E6%9D%A1

**Comment by wupinlang** [comment]
楼主，这个问题有解决办法吗？

**Comment by dai875939260** [comment]
一直感觉只要页面有大量元素的时候，modal打开会卡顿，只要一个modal的情况就就还好。比如antd官网组件的例子，明显让人感觉到动画的延迟，和在codepen里运行独立的组件对比就能感受到。

**Comment by chenshuai2144** [comment]
ant-design/ant-design#7799
已经优化
