### ISSUE TITLE
🐛[BUG]可能不算bug吧，就是界面响应式不太好

### ISSUE THREAD

**Issue by jinshadefensi** [ant-design/ant-design-pro#5850]
### 🐛 bug 描述
新建模板-个人中心：
1.用户头像最好设置一下width:100%;要不然在小屏上宽度始终是400，就会超出盒子
2.用户中心-项目那个tab对应的内容，当屏幕很宽的话会不对齐，原因是介绍微文字高度不一致导致盒子高度不一致，大概超过1730px左右吧，就会出现这样的情况

### 📷 复现步骤
新建模板-个人中心：调整屏幕宽度，小屏出现问题1，大屏出现问题2

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
最好来个 pr！
