### ISSUE TITLE
🐛[BUG]表单页-高级表单-UI设计

### ISSUE THREAD

**Issue by jinshadefensi** [ant-design/ant-design-pro#5851]
### 🐛 bug 描述
表单页的高级表单，下面有个提交按钮，但是设计却盖住了一部分内容，让人很难受，建议增大padding-bottom的距离，要不然有强迫症的话很难受

### 📷 复现步骤
https://preview.pro.ant.design/form/advanced-form
滚到最下面看看

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
<img width="1552" alt="图片" src="https://user-images.githubusercontent.com/507615/71759798-8f07c780-2eed-11ea-9768-b0ee04dde38d.png">

这个地址访问进去，没盖住啥内容吧。

**Comment by chenshuai2144** [comment]
欢迎提出建设性意见
