### ISSUE TITLE
使用npm run fetch:blocks下载模块后，有些模块下载不下来

### ISSUE THREAD

**Issue by LianCui** [ant-design/ant-design-pro#5852]
![image](https://user-images.githubusercontent.com/33477801/71762226-f92d6600-2f07-11ea-9f41-642e4490a6a6.png)

**Comment by qiangyongjun918** [comment]
现在应该可以了，但是还是有bug

**Comment by chenshuai2144** [comment]
这个是从 github 进行的下载，可以 clean 之后重新删除一下

**Comment by LianCui** [comment]
好的 ，谢谢了

**Comment by LianCui** [comment]
@chenshuai2144  不是执行npm run fetch:blocks吗？

**Comment by whyzsm** [comment]
我也有这个问题，删除了node_modules，安装安装，总有几个是安装失败的

**Comment by shuibin20172016** [comment]
我试了还是不行你呢

**Comment by VATALU** [comment]
I have the same issue.

**Comment by VATALU** [comment]
我试了下，有些模块有dependency conflict，"@antv/data-set": "^0.10.1"与"@antv/data-set": "^0.11.1"冲突了，把源项目里的版本升级之后便可安装

**Comment by VATALU** [comment]
Hi @chenshuai2144 ,
也许我们应该在 fetch:blocks script 中增加 error message。

**Comment by chenshuai2144** [comment]
已经解决
