### ISSUE TITLE
AntdV4 RC 已经发布了 大佬们有计划Pro适配AntdV4吗？👑 [需求]

### ISSUE THREAD

**Issue by wushizhan** [ant-design/ant-design-pro#5853]
### 🥰 需求描述
AntdV4 RC 已经发布了 大佬们有计划Pro适配AntdV4吗？

**Comment by kurtwilbies** [comment]
What about updating to V4. Is tjere a roadmap, strayegy, something ... ?

**Comment by tangtanglove** [comment]
同样的需求

**Comment by wushizhan** [comment]
更新换ant-design-pro-layout版本到4.9.0-1无icon版本，可以跑起来AntdV4，Login页面，css问题 估计V4 form 调整后适配问题，菜单没有icon 折叠显示有问题。想自己尝试调整的 可以先玩玩。ant-design-pro-layout 那边大佬已经打算搞pro-layout适配版本了。

**Comment by liujiayii** [comment]
> 更新换ant-design-pro-layout版本到4.9.0-1无icon版本，可以跑起来AntdV4，Login页面，css问题 估计V4 form 调整后适配问题，菜单没有icon 折叠显示有问题。想自己尝试调整的 可以先玩玩。ant-design-pro-layout 那边大佬已经打算搞pro-layout适配版本了。
除了菜单没有icon有别的区别吗？我试了试总感觉哪里不对

**Comment by chenshuai2144** [comment]
@liujiayii  试试这个版本
https://www.npmjs.com/package/@ant-design/pro-layout/v/4.11.0-0

**Comment by liujiayii** [comment]
> @liujiayii 试试这个版本
> https://www.npmjs.com/package/@ant-design/pro-layout/v/4.11.0-0

页面刷新后菜单高亮消失，右上角的搜索小工具有点错位

**Comment by chenshuai2144** [comment]
@liujiayii  毕竟样式改动很大

**Comment by wushizhan** [comment]
大佬已经更新了 可以使用antd@4 分支
