### ISSUE TITLE
👑 [需求] 建议首页是登录页面，登录后才能访问 /dashboard 等页

### ISSUE THREAD

**Issue by enzeberg** [ant-design/ant-design-pro#5854]
### 🥰 需求描述

我在访问 `Pro` 的 `Preview` 时发现，无论是否登录，都可以直接进入 `/dashboard` 等页，而这似乎不是我们大多数人所想要的。所以希望官方把这个改一下，改成首页是登录页，只有登录后才能访问 `/dashboard` 等页，而直接访问 `/dashboard` 会跳转到首页  `/` ，也就是登录页面。

### 🚑 PS
好吧，我承认我不会配置这个，所以想参考一下官方的做法。😂

无比感谢！！！

**Comment by chenshuai2144** [comment]
我们希望展示一下我们能力，所以专门设置的 谁都可以访问。
默认启动的时候还是登陆页。

**Comment by enzeberg** [comment]
@chenshuai2144  嗯，我理解，这是一个很不错的推广方式。那，能不能把 Pro 的脚手架做成这种首页是登录页的？😂

**Comment by HowGraceU** [comment]
在 /layout/SecurityLayout.tsx 里面可以找到相关逻辑以及为什么进来不是登录页

**Comment by enzeberg** [comment]
@HowGraceU 好的，感谢~
