### ISSUE TITLE
🐛[BUG]在ProTable组件中，使用renderFormItem自定义搜索表单出现问题

### ISSUE THREAD

**Issue by AaronWrdo** [ant-design/ant-design-pro#5855]
### 🐛 bug 描述

使用renderFormItem自定义搜索表单中的一项，可以正常渲染出自定义的内容，也可以正常拿到输入的内容，但在点击自带的Reset后，自定义的表单项不会reset

### 部分代码
```
// 渲染RangePicker
  const renderRangePicker = 
    (item, config: {value,onChange}) =>
      (<RangePicker
            onChange={(value) => {
              config.onChange(
				[
					moment(value[0]).format('YYYY-MM-DD'), 
 					moment(value[1]).format('YYYY-MM-DD')
				]
			  )
			}
          }
      />)
    ;

const columns = [
   {
      title: '上次更新时间',
      dataIndex: 'updatedAt',
      sorter: true,
      valueType: 'dateTime',
      sorter: (a, b) => moment(a.createdAt).isBefore(b.createdAt),
      renderFormItem: renderRangePicker, // 搜索表单中，该项的渲染方式
    },
	...
]



```

### © 版本信息
- "@ant-design/pro-layout": "^4.10.0",
- "@ant-design/pro-table": "^1.0.22",
- umi 版本 [2.12.7]
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
```
const renderRangePicker = 
    (item, config) =>
      (<RangePicker
            {...config}
            onChange={(value) => {
              config.onChange(
				[
					moment(value[0]).format('YYYY-MM-DD'), 
 					moment(value[1]).format('YYYY-MM-DD')
				]
			  )
			}
          }
      />)
    ;

```
最好直接  {...config}

**Comment by AaronWrdo** [comment]
> ```
> const renderRangePicker = 
>     (item, config) =>
>       (<RangePicker
>             {...config}
>             onChange={(value) => {
>               config.onChange(
> 				[
> 					moment(value[0]).format('YYYY-MM-DD'), 
>  					moment(value[1]).format('YYYY-MM-DD')
> 				]
> 			  )
> 			}
>           }
>       />)
>     ;
> ```
> 
> 最好直接 {...config}

谢谢你的帮助！
不过问题还是没有解决。
可能是我表述有误，是点击右侧表单自带的“重置”后，其他项都可以自动重置，但自定义的表单项没有变化
<img width="800" alt="图片" src="https://user-images.githubusercontent.com/30727053/71805555-7f30e480-30a1-11ea-9828-22125e615566.png">

**Comment by AaronWrdo** [comment]
> ```
> const renderRangePicker = 
>     (item, config) =>
>       (<RangePicker
>             {...config}
>             onChange={(value) => {
>               config.onChange(
> 				[
> 					moment(value[0]).format('YYYY-MM-DD'), 
>  					moment(value[1]).format('YYYY-MM-DD')
> 				]
> 			  )
> 			}
>           }
>       />)
>     ;
> ```
> 
> 最好直接 {...config}

我知道了，是我使用的方式不对。
不能在RangePicker的onChange里去调用config.onChange()。应该使用{...config}直接赋值。
但如果使用{...config}赋值后再去改变onChange就会报错。
所以我把代码改成了

`
  const renderRangePicker = 
    (item, config) => {
      config.value = (config.value === undefined)? ([]) : (
          [
            moment(config.value[0]).format('YYYY-MM-DD'), 
            moment(config.value[1]).format('YYYY-MM-DD')
          ]
        );
      return (<RangePicker
        {...config}
      />)
    }
`

问题就解决了。
非常感谢你的帮助！

**Comment by lqt1990** [comment]
`onChange={(value: any) => config.onChange(value)}`

**Comment by chenshuai2144** [comment]
@AaronWrdo 就是受控模式。你可以看看这个 demo

https://protable.ant.design/search#demo

**Comment by 308787520huanhuan** [comment]
请问最终是怎么解决的呢？

**Comment by dy931001** [comment]
> @AaronWrdo 就是受控模式。你可以看看这个 demo
> 
> https://protable.ant.design/search#demo

官方给的案例中，自定义组件中select的选项并没有重新置空，这个时候就会出现选项不匹配的情况，有没有方法可以通知renderFormItem重新渲染选项？？？
