### ISSUE TITLE
没有主题切换和黑色模式和官网演示的不一样

### ISSUE THREAD

**Issue by etoscn** [ant-design/ant-design-pro#5856]
没有主题切换和黑色模式和官网演示的不一样

我的
<img width="320" alt="QQ20200106-134640@2x" src="https://user-images.githubusercontent.com/22249392/71797986-4f76e200-308b-11ea-92fc-dbb02f271cc5.png">
官网演示
<img width="307" alt="QQ20200106-134808@2x" src="https://user-images.githubusercontent.com/22249392/71798002-5d2c6780-308b-11ea-8d88-83b8dffd9c62.png">

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/dynamic-theme-cn#header

可以看这个文章，开发和暖井打开会很卡。

**Comment by zhanggs1994** [comment]
> 没有主题切换和黑色模式和官网演示的不一样
> 
> 我的
> <img alt="QQ20200106-134640@2x" width="320" src="https://user-images.githubusercontent.com/22249392/71797986-4f76e200-308b-11ea-92fc-dbb02f271cc5.png">
> 官网演示
> <img alt="QQ20200106-134808@2x" width="307" src="https://user-images.githubusercontent.com/22249392/71798002-5d2c6780-308b-11ea-8d88-83b8dffd9c62.png">

请问这个问题你解决了吗？
