### ISSUE TITLE
使用国际化切换的时候，必须每种语言都得写一份模板做id映射吗？

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#5857]
### 🧐 问题描述

当我使用国际化的时候，比如说中文，我只需要在Zh-CN文件下写id来映射， 切换英文的时候，我还得在en-US文件下在写份英文的id模板来映射吗？我想切换成英文的时候显示edit，而不是app.dashbord.edit

### 💻 示例代码

formatMessage({ id: 'app.dashbord.edit' })
![image](https://user-images.githubusercontent.com/30942709/71798420-f14afe80-308c-11ea-9561-47a5390f42e7.png)

### 🚑 其他信息

那比如说其他语言的还得写这种模板吗？
![image](https://user-images.githubusercontent.com/30942709/71798227-3de20a00-308c-11ea-83b2-85eb562f18ee.png)

**Comment by ISBN9527** [comment]
@chenshuai2144 期待大佬的解答。

**Comment by chenshuai2144** [comment]
是的。国际化其实是根据不同的 key 来隐射不同的国际化文案。每个语言都是不同的

**Comment by ISBN9527** [comment]
亲，不是写一种语言后，其他语言模板自动生成吗？

**Comment by chenshuai2144** [comment]
那是理想中的情况，我们内部有这样的基础设施。开源的你可以找找

**Comment by ISBN9527** [comment]
大佬啊，有什么推荐的吗？
