### ISSUE TITLE
V4的左侧菜单跟官网提供的“预览”界面表现不一致

### ISSUE THREAD

**Issue by Vera1128** [ant-design/ant-design-pro#5858]
- 环境
ant-design-pro v4
- 现象
现有主菜单A和B，A展开，B关闭，我点击主菜单B(这时候我还没点击B下面的子菜单)，B展开的同事，A直接就收了起来，导致我的菜单看起来就是全部未选中状态，实际上我的页面还停留在之前A展开时候的状态。
如图：
![1](https://user-images.githubusercontent.com/19609295/71806379-9cff4900-30a3-11ea-8699-e0f31eed0ddf.gif)
- 对比
我去官网的预览页面体验了一下，发现没有这个问题，官网上的效果是ok的
![2](https://user-images.githubusercontent.com/19609295/71806410-b3a5a000-30a3-11ea-8b7e-f04f289ef5c5.gif)
- 探索
debug了下，发现点击主菜单的时候，会判断是否只有一个mainTitle被打开，如果是的话，就会展示这个主菜单，关闭其他主菜单。这个是否有问题？

**Comment by chenshuai2144** [comment]
看起来好像有 bug，只有 pathname 变化才应该触发menu 的状态更新的。
来个重现？
