### ISSUE TITLE
ProTable pagination size changer 切换数量时，分页组件无响应

### ISSUE THREAD

**Issue by paerhaty** [ant-design/ant-design-pro#5859]
### 🧐 问题描述
通过极少改变 pro v4 的table示例代码，碰到以下问题
页面中的查询功能正常，数据可以正常显示出来，直接点击分页组件中的页码，可以正常进行页面的切换，而且单独设置pagenation的 defaultPageSize，页面中的每页查询条数也正确获取。
可是唯独将 sizeChanger 显示出来后，在页面上下拉选择设置pageSize时
 pageSizeOptions: ['15', '50', '100'],
通过下拉框选择 pageSize后，页面无响应，不过通过调试信息可以看到 onShowSizeChange 事件正常运行，返回current, size调试信息等，

### 💻 示例代码
```js
const TableList = (props) => {

  return (
    <PageHeaderWrapper>
      <ProTable
        headerTitle="菜单数据查询"
        columns={columns}
        actionRef={actionRef}
        request={async (params = {}) => {
          return await queryMenuByCondition({
            ...params,
          });
        }}
        rowKey="id"
        size='middle'
        dateFormatter="string"
        pagination={{
          defaultCurrent: 1,
          defaultPageSize: 15,
          showTotal: total => `共 ${total} 条`,
          showSizeChanger: true,
          pageSizeOptions: ['15', '50', '100'],
        }}
        expandedRowRender={record => displayDescription(record)}
      />
    </PageHeaderWrapper>
  );
};
export default TableList;
```

### 🚑 其他信息
部分依赖如下：
```json
   "@ant-design/pro-layout": "^4.8.7",
    "@ant-design/pro-table": "^1.0.13",
    "@antv/data-set": "^0.10.2",
    "antd": "^3.23.6",
    "dva": "^2.6.0-beta.16",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "react": "^16.8.6",
    "umi": "^2.8.7",
    "umi-plugin-antd-theme": "^1.0.1",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.9.5",
    "umi-request": "^1.0.8"
```

© 版本信息
Ant Design Pro 版本: 4.8.7
umi 版本: 2.8.7
浏览器环境 FireFox V71.0(64位）、Google Chrome V79.0.3945.88（正式版本） （64 位）
开发环境 mac OS

**Comment by paerhaty** [comment]
希望得到大家的帮助！！

**Comment by paerhaty** [comment]
描述的不清楚，还是怎么回事？
来点回应啊各位

**Comment by chenshuai2144** [comment]
输出一下  params 看看里面的参数发生了变化吗？

**Comment by chenshuai2144** [comment]
https://protable.ant.design/

看看这里是可以的

**Comment by linjiangl** [comment]
https://preview.pro.ant.design/list/table-list
这里修改每页显示的条数, 也没效果

**Comment by linjiangl** [comment]
`
onChange: function onChange(page, newPageSize) {
      // pageSize 改变之后就没必要切换页码
      if (newPageSize !== pageSize && current !== page) {
        action.setPageInfo({
          pageSize: pageSize,
          page: page
        });
      } else {
        if (newPageSize !== pageSize) {
          action.setPageInfo({
            pageSize: pageSize
          });
        }

        if (current !== page) {
          action.setPageInfo({
            page: page
          });
        }
      }

      var onChange = pagination.onChange;

      if (onChange) {
        onChange(page, newPageSize || 20);
      }
    },
`
node_modules\@ant-design\pro-table\es\Table.js 第95行

`newPageSize` 默认没有处理

**Comment by rogerhzh** [comment]
同遇到这个问题，怎么解决的？

**Comment by linjiangl** [comment]
问题修复了,更新下@ant-design/pro-table版本


"@ant-design/pro-table":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"version":&nbsp;"2.4.3",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"resolved":&nbsp;"https://registry.npm.taobao.org/@ant-design/pro-table/download/@ant-design/pro-table-2.4.3.tgz?cache=0&amp;other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2F%40ant-design%2Fpro-table%2Fdownload%2F%40ant-design%2Fpro-table-2.4.3.tgz",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"integrity":&nbsp;"sha1-Q82c+DNzcAszRblRFvbRjGoxUXo=",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"requires":&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"@ant-design/icons":&nbsp;"^4.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"antd":&nbsp;"^4.1.5",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"classnames":&nbsp;"^2.2.6",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"dnd-core":&nbsp;"^10.0.2",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"lodash.isequal":&nbsp;"^4.5.0",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"lodash.tonumber":&nbsp;"^4.0.3",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"moment":&nbsp;"^2.24.0",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"rc-resize-observer":&nbsp;"^0.2.1",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"rc-util":&nbsp;"^5.0.1",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"react-dnd":&nbsp;"^10.0.2",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"react-dnd-html5-backend":&nbsp;"^10.0.2",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"unstated-next":&nbsp;"^1.1.0",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"use-json-comparison":&nbsp;"^1.0.5",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"use-media-antd-query":&nbsp;"1.0.2",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"use-merge-value":&nbsp;"^1.0.1"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;},






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 凌晨0:23
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"aim"<8257796@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] ProTable pagination size changer 切换数量时，分页组件无响应 (#5859)



 同遇到这个问题，怎么解决的？

**Comment by arwinz** [comment]
同问，使用ProTable上的改变分页条数，请求正常发送，数据按照分页条数正常返回，结果分页条数一直是默认的10条/页
