### ISSUE TITLE
🧐[问题]How to change app port from 8000 to another port number

### ISSUE THREAD

**Issue by ddzsy** [ant-design/ant-design-pro#5862]
### 🧐 问题描述

Add PORT=8001 or BASE_PORT=8001 into script does not work.

And how to change umi ui port from 3000 to another number?

**Comment by afc163** [comment]
https://umijs.org/zh/guide/env-variables.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE

**Comment by loia5tqd001** [comment]
## The problem
If I add `PORT=3000` in a `.env` file, it works.

But when I add `PORT: process.env.PORT || 3000` under `define` in the `config/config.ts` file, it should work but it doesn't. Why?

By "work" I mean the app should run at `http://localhost:3000` but instead it runs on `http://localhost:8001`. Even when the `define` is `PORT: 3000` with no `process.env.PORT`. 

## Reproduction 
You could reproduce the problem by installing `ant-design-pro` v5. Add `define: { PORT: 3000 }` in `config/config.ts`
