### ISSUE TITLE
[讨论] workbox在ios设备上偶尔会刷新失败

### ISSUE THREAD

**Issue by zhongjiewu** [ant-design/ant-design-pro#5864]
### 🐛 bug 描述

serivce worker发现服务器上有新版本时，ant design会发送“有新版本”的提示，下面的按钮本质上就是 `window.location.reload(true)`。但是iOS设备上，经常会出现点击后，缓存的asset都被清掉了，但是service worker并没有更新，导致刷新后又会出一样的更新提示。更要命的是，如果开启了asset文件的hash功能，新的版本发到服务器上以后，老的js就不见了，会让整个app因为无法获取老的hash对应的js文件而直接挂在转圈圈的阶段，用户必须要去系统设置里清理掉域名的缓存才行。
这个可能是iOS浏览器的bug，但是需要想办法解决。

### 📷 复现步骤

很难重现，想问问大家有没有谁碰到。

### 🏞 期望结果

建议在强制刷新前，进行service worker注销

```
navigator
  .serviceWorker
  .getRegistrations()
  .then((registrations) => registration.unregister())
  .then(() => window.location.reload(true));
```

**Comment by chenshuai2144** [comment]
是时候放弃 pwa 了，他的更新机制很奇怪， 我到现在也没有完全理解

**Comment by zhongjiewu** [comment]
PWA在手机和电脑上可以单独保存成一个图标，这个是最大的亮点。一些企业应用中都可以替代移动app的开发了。

**Comment by zhongjiewu** [comment]
关闭问题。如果有人遇到类似问题搜到这里的话，可以添加讨论。

**Comment by jimStyle88** [comment]
> 关闭问题。如果有人遇到类似问题搜到这里的话，可以添加讨论。

你好，我遇到同样的问题，在pc 端上，请问你是怎么解决的
