### ISSUE TITLE
🧐[问题]整个头部header组件怎么隐藏？

### ISSUE THREAD

**Issue by weiweizhuang** [ant-design/ant-design-pro#5867]
![image](https://user-images.githubusercontent.com/30386171/71976998-b4306900-3252-11ea-9dfa-66a6b3af5b8c.png)

我已经通过重写headerRender去掉了header组件里面的东西。但是这个头部还是有  我想去掉，应该怎么办呢？

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/api#demo
看这个

**Comment by weiweizhuang** [comment]
> https://prolayout.ant.design/api#demo
> 看这个

谢谢，刚刚使用这个框架，不知道你们竟然单独把layout开了个文档。已经搞好了。
