### ISSUE TITLE
🧐模仿antPro的例子，做了一个脚手架，可以自动生成一部分代码

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#5868]
### 模仿antPro的例子，做了一个脚手架，可以自动生成一部分代码

希望能生成80%的重复代码，具体的细节再仔细调整。业余时间做着玩的，里面可能有很多bug，我会及时修改的。

主要是根据数据库的table结构，来生成：
* mock
* d.ts
* service
* model
* page

[详细使用说明](https://github.com/fanhualei/ant-g/blob/master/doc/manual-cn.md)

页面例子：

![page1](https://user-images.githubusercontent.com/34436863/71980037-193b8d00-325a-11ea-87a1-8a27bd532e9b.png)

![page2](https://user-images.githubusercontent.com/34436863/71980048-222c5e80-325a-11ea-8368-e1edd369e923.png)

![init](https://user-images.githubusercontent.com/34436863/71980057-2789a900-325a-11ea-81f6-374d4f3ed708.png)

![pageconfig](https://user-images.githubusercontent.com/34436863/71980071-307a7a80-325a-11ea-9839-85adc86f3b0c.png)

![pageconfig-fields](https://user-images.githubusercontent.com/34436863/71980096-3d976980-325a-11ea-80e9-1ae2d43a96a3.png)

![pageGenerate](https://user-images.githubusercontent.com/34436863/71980108-425c1d80-325a-11ea-9641-0d59f19365c5.png)

**Comment by chenshuai2144** [comment]
用father doc 整个官网吧

**Comment by fanhualei** [comment]
我去研究一下father doc 。

录了一个1分钟的视频上传到优酷了，优酷有15秒的广告，只能忍忍了。

建议在电脑上看，不然看不清楚字。 [链接地址](https://v.youku.com/v_show/id_XNDUwMTI3NzE4MA==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~5~A)

**Comment by fanhualei** [comment]
> 用father doc 整个官网吧

弱弱的问： 啥是father doc ？ 我百度了一下，没有弄明白。

**Comment by winter-ice** [comment]
@fanhualei  https://umijs.github.io/father-doc/

**Comment by fanhualei** [comment]
多谢，看起来功能比较强大呀！！！

**Comment by fanhualei** [comment]
## father-doc 没有搞定
快速上手的第一步，就牺牲了,npm 安装出现错误。
```shell
$ npm i father-doc@next -D
```

## 想把ant-g以umi-ui 插件的形式实现，也没有搞定。
按照[umi ui 插件开发文档](https://umijs.org/zh/guide/develop-umi-ui-plugin.html#%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6)，也是在前几步失败了。
umi ui 还不错，我是新手，未来有时间，我仔细去研究研究。
![alt](https://gw.alipayobjects.com/zos/antfincdn/JAgV0HTUZn/702548da-6a1b-404c-bac6-3dd321dfc2b0.png)

## 高兴的是，在看umi-ui教程时，发现B站没有广告。
我把ant-g的最新使用方法，传到B站了。 [可以点击这里查看使用视频](https://www.bilibili.com/video/av83159430)
这个版本有这么些功能：
* 可以显示中文标题。
* 可以根据字段类型，来生成 input inputNumber date 的控件。
* 可以生成form的校验规则，例如非空和长度校验。

新版本，我明天抽空测试一下，然后上传到npm里面。

**Comment by fanhualei** [comment]
> @fanhualei https://umijs.github.io/father-doc/
发现docz也能写文档，租father-doc功能类似
https://github.com/pedronauck/docz

**Comment by chenshuai2144** [comment]
@fanhualei 因为 docz 无法解决问题我们才自己做了 fatherdoc
