### ISSUE TITLE
底部版权信息 GlobalFooter 与 FooterToolbar 吸底按钮同时存在时版权信息被遮挡🐛[BUG]

### ISSUE THREAD

**Issue by chenyiliunian** [ant-design/ant-design-pro#5869]
### 🐛 bug 描述

当页面中引入 FooterToolbar 组件包裹吸底按钮时，GlobalFooter 中的信息被遮挡，设置 GlobalFooter 中的 padding 时，页面滚动出现卡顿现象。

### 📷 复现步骤
1. 在页面中引入 FooterToolbar 组件
2. GlobalFooter中的版权信息被遮挡

### 🏞 期望结果
1. GlobalFooter 中的信息完全展示
2. 设置 GlobalFooter padding-bottom 时，页面滚动不会出现卡顿现象。

### © 版本信息

- Ant Design Pro 版本: v1 v2 v4
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12947402/71986248-1a26eb80-3267-11ea-8c40-ffa80b0899d2.png)

**Comment by chenshuai2144** [comment]
现在没有好的办法，你可以在项目中自己处理，通用的办法我们暂时没想到。
你有好的想法也可以来个 pr。
