### ISSUE TITLE
🐛[BUG]列表 个人设置bug

### ISSUE THREAD

**Issue by qiangyongjun918** [ant-design/ant-design-pro#5871]
### 🐛 bug 描述
fetch:blocks 以后，项目可以正常跑起来：
问题1：测试用例不是全部通过
问题2：点击列表tab会出现bug，不明原因
问题3：点击个人设置tab会出现bug，不明原因

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> 问题2：点击列表tab会出现bug，不明原因, 问题3：点击个人设置tab会出现bug，不明原因

什么 bug？
