### ISSUE TITLE
header固定时，HeaderDropdown不固定🐛[BUG]

### ISSUE THREAD

**Issue by Feather130** [ant-design/ant-design-pro#5872]
### 🐛 bug 描述
1.header固定时，长页面的HeaderDropdown不固定
2.HeaderDropdown的位置会定位到当前的scorll位置

### 📷 复现步骤
1.设置header固定，在dashbord分析页，点击右上角小铃铛，鼠标滚轮滑动页面，HeaderDropdown会移动
2.设置header固定，在dashbord分析页，鼠标滚轮滑动页面，点击右上角小铃铛，鼠标再往回滚动，HeaderDropdown会固定在之前scorll位置

### 🏞 期望结果
header固定，鼠标滚动页面HeaderDropdown固定到header下方

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
图片可能需要vpn
![GIF 2020-1-9 10-52-48](https://user-images.githubusercontent.com/10240614/72034045-e7b0d900-32ce-11ea-9928-8378f9e104f0.gif)
![GIF 2020-1-9 10-54-20](https://user-images.githubusercontent.com/10240614/72034304-9b19cd80-32cf-11ea-9d30-4f336bd0cfd0.gif)

**Comment by chenshuai2144** [comment]
https://ant.design/components/config-provider-cn/#API
试试 getPopupContainer ，你可以在 header 里面

**Comment by Feather130** [comment]
解决了，谢谢
