### ISSUE TITLE
🐛[BUG] - Nested route with components not working

### ISSUE THREAD

**Issue by narayanncube** [ant-design/ant-design-pro#5873]
### 🐛 bug 描述

if parent route has component linked to it and child route has another component linked to it, when visiting child route parent component only loads

```
{
              path: '/people',
              name: 'people',
              icon: 'usergroup-add',
              component: './people',
              routes: [
                {
                  name: 'Drivers',
                  path: '/people/drivers',
                  component: './people/drivers',
                },
              ],              
}

```
in here visiting http://localhost:8000/people/drivers opens same view as http://localhost:8000/people. only title changes to Drivers

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
Your child route will be expected as the childern of the parent route component.
You can get it using this.props.children.
like :
```
const people = (props)=>props.children
```
this is best useage
```
{
  path: "/people",
  name: "people",
  icon: "usergroup-add",
  routes: [
    {
      path: "./",
      redirect: "info"
    },
    {
      name: "people",
      path: "/people/info",
      component: "./people"
    },
    {
      name: "Drivers",
      path: "/people/drivers",
      component: "./people/drivers"
    }
  ]
};

```

**Comment by narayanncube** [comment]
Its a workaround but not an ideal solution.

Generally list for anything comes as 

/products (List of all products)

/products/new (Add a new product)

/products/:id (edit a product with id)

**Comment by chenshuai2144** [comment]
order your router ?
    ```
[
  {
    name: "people",
    path: "/people/info",
    component: "./people"
  },
  {
    name: "Drivers",
    path: "/people/drivers",
    component: "./people/drivers"
  },
  {
    path: "/people",
    name: "people",
    icon: "usergroup-add"
  }
];
```

**Comment by narayanncube** [comment]
Yeah this is good. Please close the bug
