### ISSUE TITLE
🧐[问题]请问哪个分支有动态主题的使用案例

### ISSUE THREAD

**Issue by zp2359** [ant-design/ant-design-pro#5874]
我在master、v4、v4-migration、feat-antd-4.0-dark分支，均未找到动态主题的案例。请问哪个分支有？

![image](https://user-images.githubusercontent.com/6220430/72122339-82c1b580-3398-11ea-9625-2cb66b6e258a.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/dynamic-theme-cn

看看这个文档，我们默认不打开，只有在 部署官网的时候才打开

**Comment by zp2359** [comment]
默认不打开~，嗯嗯，搞定了。 谢谢

**Comment by zp2359** [comment]
为什么我的返回的不是css文件呢？

![image](https://user-images.githubusercontent.com/6220430/72123856-a9ceb600-339d-11ea-940d-a651cd3f4f16.png)

**Comment by chenshuai2144** [comment]
把路径截全吧

**Comment by zp2359** [comment]
路径是：http://localhost:8000/theme/dark.css

**Comment by chenshuai2144** [comment]
@zp2359  重启一下项目，我看到你的文件已经生成了。

**Comment by zp2359** [comment]
404哦：
![image](https://user-images.githubusercontent.com/6220430/72125002-d4227280-33a1-11ea-95ad-20a7dedad2bb.png)

**Comment by zp2359** [comment]
![image](https://user-images.githubusercontent.com/6220430/72125014-df759e00-33a1-11ea-96c4-a49483ff13e2.png)

**Comment by chenshuai2144** [comment]
看看 cache 里面有东西吗？

**Comment by zp2359** [comment]
没有：
![image](https://user-images.githubusercontent.com/6220430/72125434-827ae780-33a3-11ea-96fc-9a06881b4c49.png)

**Comment by zp2359** [comment]
第一次报错：
![image](https://user-images.githubusercontent.com/6220430/72135860-69356380-33c2-11ea-9f1b-6fe0696d1926.png)

第二次有缓存：
![image](https://user-images.githubusercontent.com/6220430/72135891-74888f00-33c2-11ea-86c1-b9b0f44da6a6.png)

**Comment by zp2359** [comment]
应该是依赖包或代码中自己copy了一份antd.less的原因~

**Comment by chenshuai2144** [comment]
看样子生成失败了，估计对 win 支持不好， 我来试试
