### ISSUE TITLE
👑 [需求]大型系统构建性能

### ISSUE THREAD

**Issue by kunhour** [ant-design/ant-design-pro#5875]
### 🥰 需求描述

大型系统，单页面应用非常庞大，构建太慢，打包太久，需要30-40分钟。
### 🧐 解决方案

暂时没有找到合适的解决方案，有一种想法就是：支持模块打包，最终合并在一起。
不知道是否可行，pro  有这方面的考虑吗，期盼回复

### 🚑 其他信息

暂无

**Comment by bailnl** [comment]
大王， 微前端可行？

**Comment by kunhour** [comment]
> 大王， 微前端可行？
看似可行，有推荐方案麽

**Comment by aprilyzl0405** [comment]
参考下 umi 的区块？
