### ISSUE TITLE
🐛[BUG] 在线预览网站 显示问题

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design-pro#5877]
### 💻 复现代码
https://preview.pro.ant.design/dashboard/analysis

### 🐛 bug 描述
1. 右边配置点开后，第一栏整体风格，第二个第三个名称重复。第三个应为 整体暗色风格
2. 默认配色时 **通知图标** 的 `.antd-pro-components-notice-icon-index-badge` 有个 `font-size: 16px`，切换其他配色时，该图标为 `14px`。当使用顶部菜单导航模式时，会出现明显的抖动。
3. 整体风格选择第二种，默认配色时，顶部图标有 `.antd-pro-components-global-header-index-dark .antd-pro-components-global-header-index-action>i` 设置了 `color: hsla(0, 0%, 100%, .85)，当切换配色时，无该样式，图标呈现黑色，与底色重合。色弱模式下，切换配色，图标仍存在次问题。

### 📷 复现步骤
- 打开网站
- 点击网站右侧配置按钮
- 鼠标悬浮整体风格 3 个忽略图，可观察到第一个bug
- 导航模式选择顶部，切换配色，观察通知图标，可观察到第二个 bug
- 整体风格选择第二种，切换配色，可观察到第三个bug

### 🏞 期望结果
- 文字提示描述信息准确
- 切换配色，图标尺寸保持一致
- 切换配色，图标颜色直观可见

### 🚑 其他信息
![](https://github.com/xrkffgg/Kimg/blob/master/ant-design-pro/2020.01/2020-01-10%2016.52.14-min.gif?raw=true)

**Comment by chenshuai2144** [comment]
这只是个beta 版本 
需要等antd@4 正式发布才会产出一个非常完美的版本，现在这个只能做示例，如果需要在产品中使用需要付出很高昂的代价

**Comment by chenshuai2144** [comment]
https://next.ant.design
可以试试这个
