### ISSUE TITLE
🧐[问题]预览效果的的完整源代码在哪里可以找到，想要学习下

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design-pro#5879]
### 🧐 问题描述

预览效果的的完整源代码在哪里可以找到，想要学习下

### 🚑 其他信息
![图片](https://user-images.githubusercontent.com/4978379/72144835-2c726800-33d4-11ea-92ca-66f481dbd36b.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/available-script-cn#npm-run-fetchblocks
