### ISSUE TITLE
最新版本路由使用BrowserRouter报错

### ISSUE THREAD

**Issue by shizhiqian** [ant-design/ant-design-pro#588]
问题: 路由使用BrowserRouter报错,修改如下:
...
import browserHistory from 'history/createBrowserHistory';
...
const app = dva({
  history: browserHistory(),
  ...
});

现象: 谷歌浏览器,默认进入http://localhost:8000/user/login,页面上显示
Unhandled Rejection (Error): Loading chunk 24 failed.
HTMLScriptElement.onScriptComplete
internal:/webpack/bootstrap 051f960b096a674aa891:756
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
控制台输出:
Uncaught SyntaxError: Unexpected token <     .......24.async.js:1 
Uncaught (in promise) Error: Loading chunk 24 failed.at HTMLScriptElement.onScriptComplete ....index.js:757

期望: http://localhost:8000/user/login 能正常显示登录页

  
![k6 wp su i bf0deb t s](https://user-images.githubusercontent.com/12113101/34636242-1cb1ece0-f2d8-11e7-9e46-12431ad12fae.jpg)

**Comment by chenshuai2144** [comment]
试着升级一下roadhog.
#542

**Comment by shizhiqian** [comment]
@chenshuai2144 升级到"roadhog": "^2.0.5",不行,还是报同样的错误

**Comment by chenshuai2144** [comment]
我排查一下

**Comment by chenshuai2144** [comment]
路径的问题,我们升级了 roadhog2, 你去那边提一下.
或者你关闭掉大妈分割.

**Comment by chenshuai2144** [comment]
路径的问题,  关掉代码分割吧.  我们再修复一下

是roadhog2的问题

**Comment by shizhiqian** [comment]
@chenshuai2144 麻烦你了

**Comment by shizhiqian** [comment]
@chenshuai2144 这个问题大概什么时候能修复好?

**Comment by chenshuai2144** [comment]
主力人员都不在  今天不行 等下周吧.
你关掉代码分割就好了

**Comment by bobbychan** [comment]
请问 代码分割 如何关闭？

**Comment by chenshuai2144** [comment]
默认是关闭的。。 我去找找文档

**Comment by guohuihuiguo** [comment]
我也遇到这个问题   请问是如何解决的
