### ISSUE TITLE
🧐[问题] 在查询表格页面中的检索框中，如果标题长度不一样，想把输入框对其，应该怎么做？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#5880]
# 在查询表格页面中的检索框中，如果标题长度不一样，想把输入框对其，应该怎么做？

有没有好的实现思路？

例如下图。

![TIM截图20200110183022](https://user-images.githubusercontent.com/34436863/72146517-97716e00-33d7-11ea-9e22-1c5c594081f6.png)

**Comment by chenshuai2144** [comment]
最好的办法其实是给 标题设置一个固定宽度无毒无害。虽然不够灵活但是实现起来很简单。

**Comment by fanhualei** [comment]
# 如果能添加padEnd或者padStart 在前后添加空格，就方便了

```jsx
        <FormItem
          {...this.formLayout}
          key="activityBanner"
          label="活动图片"
        >
```
