### ISSUE TITLE
dynamic menu

### ISSUE THREAD

**Issue by zhangyongjiang** [ant-design/ant-design-pro#5881]
Following the instruction at https://pro.ant.design/docs/router-and-nav#fetch-menu-from-server

I changed file BasicLayout.tsx as below. Menu is not showing up.
`
...
const testMenu = [{name:"login", path:"/user/login"}] as any;
const [menuData, setMenuData] = useState([]);

useEffect(() => {
  if (dispatch) {
    dispatch({
      type: 'user/fetchCurrent',
    });
  }
  setMenuData(testMenu)
}, []);
...
menuDataRender={()=>menuData}
`

**Comment by chenshuai2144** [comment]
like here?
https://prolayout.ant.design/menu
