### ISSUE TITLE
关于Umi的

### ISSUE THREAD

**Issue by LianCui** [ant-design/ant-design-pro#5885]
pages下面的.umi是用来做什么的，页面的路由是在这里配置的吗？

**Comment by chenshuai2144** [comment]
这个是 umi 生成的临时目录，会放一些开发中需要使用，但是不用频繁编译的文件。
路由在 `config/config.js|ts` 中配置

**Comment by LianCui** [comment]
> 这个是 umi 生成的临时目录，会放一些开发中需要使用，但是不用频繁编译的文件。
> 路由在 `config/config.js|ts` 中配置

好的，谢谢了。那这个umi的临时目录，删除的话也是会影响项目运行的吗？他是因为使用了umi才会生成的吗？

**Comment by chenshuai2144** [comment]
是的，你在 git 中忽略就好了，里面有很多必要的文件
