### ISSUE TITLE
ProTable组件，操作表格右上角固定某一列到表格第一列，原来的第一列就没有了🐛[BUG]

### ISSUE THREAD

**Issue by BarronLin** [ant-design/ant-design-pro#5889]
### 🐛 bug 描述

> ProTable组件，操作表格右上角固定某一列到表格第一列，原来的第一列就没有了

### 📷 复现步骤

1.打开线上pro版本，https://preview.pro.ant.design/list/table-list
2.点击表格右上角“列设置”
![image](https://user-images.githubusercontent.com/9267731/72334669-a8342380-36f8-11ea-86af-316ec6030316.png)
3.固定列“服务调用次数”
![image](https://user-images.githubusercontent.com/9267731/72334715-c0a43e00-36f8-11ea-9dc5-70c0ce8b7957.png)
4.查看表格显示的列

### 🏞 期望结果

> 列“服务调用次数”在第一列，然后其他列自动移到后面

### 🏞 实际结果
列“服务调用次数”在第一列，但列“规则名称”没有了
![image](https://user-images.githubusercontent.com/9267731/72334967-24c70200-36f9-11ea-9a7b-0c9fa3c5eaf7.png)

### 💻 复现代码

> https://preview.pro.ant.design/list/table-list

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.10.0]
- "@ant-design/pro-table": "^1.0.29",
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
@BarronLin  使用固定的时候需要设置宽度，或者直接用 4.0 可以轻松坚决问题

**Comment by BarronLin** [comment]
> @BarronLin 4.0 这个问题会自动解决，我就没有改了

您好，请问是antd 4.0 吗？还是antd pro 4.0呢？
或者现在要解决，有分支可以参考吗？

**Comment by chenshuai2144** [comment]
升级antd@4 就好了

**Comment by tnndworlds** [comment]
dva 与pro-table怎么结合使用的，有没有demo呢
