### ISSUE TITLE
PageHeader 带参数(ex. :id) 面包屑显示问题

### ISSUE THREAD

**Issue by samchanye** [ant-design/ant-design-pro#589]
nav.js 配置如下
![image](https://user-images.githubusercontent.com/22740401/34636351-0814f64a-f2da-11e7-80ac-8b5d4e972fc7.png)
显示如下
![image](https://user-images.githubusercontent.com/22740401/34636339-f6bc3818-f2d9-11e7-805c-9f93614f0399.png)
看了下源码是因为父级菜单(/sale/sale-detail)没有对应的 name 而显示了 url, 但是配置上了 name 如下
![image](https://user-images.githubusercontent.com/22740401/34636365-3f86f196-f2da-11e7-9fb7-3cbe8dd5f9d0.png)
显示如下
![image](https://user-images.githubusercontent.com/22740401/34636368-49e7f6bc-f2da-11e7-91a2-981c399f71ef.png)

望指正!

**Comment by chenshuai2144** [comment]
配置hidden 为true

**Comment by samchanye** [comment]
@chenshuai2144 😭无效

**Comment by TonyChanNJU** [comment]
有同样的需求

**Comment by chenshuai2144** [comment]
你这个不是新版本meun 配置把?

**Comment by chenshuai2144** [comment]
@ddcat1115  带参数的路由 是不是用正则匹配一下?

(/user/:id).test(/user/1212) => true

**Comment by WhatAKitty** [comment]
@chenshuai2144  带路径参数路由是支持的啊，比如：
```
    '/pipeline/:pipelineId/edit': {
      component: dynamicWrapper(app, ['pipeline'], () => import('../routes/Pipeline/Add')),
      name: '编辑流程',
    },
    '/pipeline/:pipelineId/edit/basic': {
      component: dynamicWrapper(app, ['pipeline'], () => import('../routes/Pipeline/Add/Step1')),
      name: '编辑流程-基本信息',
    },
    '/pipeline/:pipelineId/edit/build-actions': {
      component: dynamicWrapper(app, ['pipeline'], () => import('../routes/Pipeline/Add/Step2')),
      name: '编辑流程-构建动作',
    },
    '/pipeline/:pipelineId/edit/result': {
      component: dynamicWrapper(app, ['pipeline'], () => import('../routes/Pipeline/Add/Step3')),
      name: '编辑流程-完成',
    },
```

**Comment by chenshuai2144** [comment]
额` /:id`这种的.....
展示用户信息 user/:id
id一般是uuid 怎么可能定义好

**Comment by ddcat1115** [comment]
这个跟带不带参数没关系啊，老版本也是支持带参数的。这里是因为父级没有配置name或name为空字符串，最简单的解决办法就是配置上name，如果面包屑里不需要这一级，可以参照master上最新的 PageHeader 代码加个判断，在name为空时就不会展现这一级 [判断name非空](https://github.com/ant-design/ant-design-pro/blob/master/src/components/PageHeader/index.js#L98)
