### ISSUE TITLE
🧐[问题]SettingDrawer显示不正确

### ISSUE THREAD

**Issue by lichnow** [ant-design/ant-design-pro#5890]
### 🧐 问题描述

`npm run fetch:blocks`后的SettingDrawer显示不正确，只有一种颜色可选，并且没有暗黑主题

### 🚑 其他信息

![](https://pic.phpna.com/media/20200114235046.png)

**Comment by jramirez0309** [comment]
> ### 🧐 问题描述
> `npm run fetch:blocks`后的SettingDrawer显示不正确，只有一种颜色可选，并且没有暗黑主题
> 
> ### 💻 示例代码
> ### 🚑 其他信息
> ![](https://camo.githubusercontent.com/503a869d6ecfdca3d3d4e21f981edbab7a74fa40/68747470733a2f2f7069632e7068706e612e636f6d2f6d656469612f32303230303131343233353034362e706e67)

**Comment by chenshuai2144** [comment]
还有一个环境变量 
https://github.com/ant-design/ant-design-pro/blob/e497b34a197eab3a9d3c3c14fad26b3fdd9162bb/config/config.ts#L68

开发环境打开会很卡，请慎重使用
