### ISSUE TITLE
How to deploy different environments without proxy reverse 🧐[问题]

### ISSUE THREAD

**Issue by vedatkilic** [ant-design/ant-design-pro#5891]
I can't find any document how to deploy different environment with different configuration. We need to configure app for different envs[dev, test, staging], so we need to have different config files -> config.js, config.dev.js etc..., and we dont want to use proxy reverse, we want to set up base url for request for every environment and we want to use it. Do you have a solution?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/5946
look here
