### ISSUE TITLE
How to change umi-request baseUrl?

### ISSUE THREAD

**Issue by vedatkilic** [ant-design/ant-design-pro#5892]
How to change umi-request baseUrl?
Ex: https://github.com/axios/axios/issues/175

setting a proxy is for local, so it is not solution, I want to configure umi-request to make a call to different domain for prod environment and dont want to add all request to same url

**Comment by chenshuai2144** [comment]
look here 
https://github.com/umijs/umi-request

**Comment by whaty** [comment]
you just do like this:

`
![image](https://user-images.githubusercontent.com/26294919/98756022-ad3f2d80-2404-11eb-9f49-86a7438e5aaa.png)

`

**Comment by whaty** [comment]
you just do like this:
`
/**
 * 配置request请求时的默认参数
 */
const request = extend({
   prefix: 'http://127.0.0.1:8080/erd',
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
});
`

**Comment by raphaelsoul** [comment]
config file located at here https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.ts#L44
not at `{projectRoot}/config`

This wouldn't waste me hours to find it out if you guys give more details. 🤮

**Comment by raphaelsoul** [comment]
config file located at here https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.ts#L44
not at `{projectRoot}/config`

This wouldn't waste me hours to find it out if you guys give more details. 🤮

**Comment by raphaelsoul** [comment]
config file located at here https://github.com/ant-design/ant-design-pro/blob/master/src/utils/request.ts#L44
not at `{projectRoot}/config`

This wouldn't waste me hours to find it out if you guys give more details. 🤮
