### ISSUE TITLE
🐛[BUG] create-umi 选择typescript却仍然还是js文件

### ISSUE THREAD

**Issue by Thyiad** [ant-design/ant-design-pro#5894]
### 🐛 bug 描述
Hi，我用 npm create umi 创建了项目后，发现选择的 typescript 并不生效，仍然是js文件

试了好几次，发现都是这样的，package.json中压根没有引入typescript，ts相关的eslint配置也没有引入，感觉应该是bug~

### © 版本信息

- create-umi版本
0.20.0
- Ant Design Pro 版本:
4.0.0
- 开发环境 
mac os

### 🚑 其他信息
- create-umi版本截图
![image](https://user-images.githubusercontent.com/3324812/72506725-6bde0000-387d-11ea-9246-66782d585112.png)
- npm create umi截图
![image](https://user-images.githubusercontent.com/3324812/72506834-a8116080-387d-11ea-980c-eed1f050e5f2.png)
- 生成的文件截图
![image](https://user-images.githubusercontent.com/3324812/72506879-c4ad9880-387d-11ea-93ef-cfdd47e89087.png)

**Comment by kongh** [comment]
我用yarn也是一样的，有解决吗

**Comment by Thyiad** [comment]
我发现create-umi 20.0是今天更新的，所以有可能是最新版的bug，因为我不急着弄，所以先没管了，你可以降级试试看先

> 我用yarn也是一样的，有解决吗

**Comment by kongh** [comment]
我单独降到19.0，使用命令create-umi可以了，yarn create umi 会把旧的给覆盖掉

**Comment by Thyiad** [comment]
> 我单独降到19.0，使用命令create-umi可以了，yarn create umi 会把旧的给覆盖掉

果然，那就是最新版的问题咯

**Comment by guozhengzhongGit** [comment]
果然，我也遇到了，试了两次，想着来GitHub瞅一眼，有答案了，哈哈哈

**Comment by siuu** [comment]
`npm install create-umi@0.19.0 -g --force`

**Comment by serical** [comment]
我也遇到了

**Comment by chenshuai2144** [comment]
fixed in  https://github.com/umijs/create-umi/releases/tag/v0.20.1
