### ISSUE TITLE
How to deploy to netlify keeping mock data intact?

### ISSUE THREAD

**Issue by narayanncube** [ant-design/ant-design-pro#5895]
### 🧐 问题描述
How to deploy to netlify keeping mock data intact?

Whole procedure with screenshots preferred

**Comment by chenshuai2144** [comment]
you can look  https://github.com/ant-design/ant-design-pro/tree/master/lambda

**Comment by narayanncube** [comment]
@chenshuai2144 : Didn't get you. Can you give me steps? I have multiple mock js files for various folders. 

Your production runs on netlify. Can you tell how you guys did?
