### ISSUE TITLE
🐛[BUG] Internationalization for '@ant-design/pro-table' is absent

### ISSUE THREAD

**Issue by kyarginski** [ant-design/ant-design-pro#5897]
### 🐛 bug 描述
Internationalization for '@ant-design/pro-table' is absent

### 📷 复现步骤

1) See https://preview.pro.ant.design/list/table-list
2) Switch languages to English

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kyarginski** [comment]
See screenshot:
https://www.dropbox.com/s/ubdwcggpys3iy5v/screen_i18l_ant1.png?dl=0

**Comment by chenshuai2144** [comment]
升级一下 react 和 antd 的依赖

**Comment by JohanWillfred** [comment]
I have the same issue, just created project from scratch using CLI and internationalization for the table is not working. Selected language is "English" but table is still on Chinese.
Is there any way to translate those messages using project localization files?
<img width="1037" alt="Screenshot 2020-04-14 at 23 15 44" src="https://user-images.githubusercontent.com/11837719/79269995-fe566580-7ea5-11ea-9f08-71114120f312.png">
