### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by fengzzzz** [ant-design/ant-design-pro#5898]
### 🐛 bug 描述
Execute task error: find dependencies conflict between block and your project:* @ant-design/pro-layout: 4.11.0-0(your project) not compatible with ^4.5.5(block)

添加一个空白模板时提示错误，添加失败
### 📷 复现步骤
根据yarn create umi下载andt pro
yarn install 、 yarn start后在页面使用区块开发
在antd下面选择空白页，添加到项目

报错，提示“添加失败，请重试”
Execute task error: find dependencies conflict between block and your project:* @ant-design/pro-layout: 4.11.0-0(your project) not compatible with ^4.5.5(block)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by inksong** [comment]
Same bug while adding template: ListTableList.

**Comment by hesingon** [comment]
ListTableList我这里也加不了
