### ISSUE TITLE
🐛[BUG] Identifier 'NoticeIconView' has already been declared

### ISSUE THREAD

**Issue by sbhouchen** [ant-design/ant-design-pro#5899]
### 🐛 bug 描述
NoticeIconView 重复声明了

按照官网 npm create umi 选择 javascript版本创建的工程，src\components\GlobalHeader\RightContent.jsx文件中重复申明了NoticeIconView
import { QuestionCircleOutlined } from '@ant-design/icons';
import { Tooltip } from 'antd';
import React from 'react';
import { connect } from 'dva';
**import NoticeIconView from './NoticeIconView';**
import Avatar from './AvatarDropdown';
import HeaderSearch from '../HeaderSearch';
import SelectLang from '../SelectLang';
import styles from './index.less';
**import NoticeIconView from './NoticeIconView';**

const GlobalHeaderRight = props => {
  const { theme, layout } = props;
  let className = styles.right;

  if (theme === 'dark' && layout === 'topmenu') {
    className = `${styles.right}  ${styles.dark}`;
  }
......
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你是不是重复 fetch:blocks 了，每次执行一次命令就会增加一个 NoticeIconView

**Comment by yasongxu** [comment]
+1 没有重复执行，也出现了这个错误
