### ISSUE TITLE
最新版,点击菜单警告:Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by shizhiqian** [ant-design/ant-design-pro#590]
基本上点击每个菜单都有类似的警示,
http://localhost:8000/#/dashboard/monitor 如下图
![qq 20180106142312](https://user-images.githubusercontent.com/12113101/34637260-31c4695e-f2ed-11e7-9a32-3bd3dcba2812.png)

http://localhost:8000/#/dashboard/workplace 如下图
![qq 20180106142441](https://user-images.githubusercontent.com/12113101/34637266-5fe3b86c-f2ed-11e7-998f-c58f5fe6bbcf.png)

http://localhost:8000/#/form/basic-form 例如表单,如果对每个<Form.Item key={1}>加上key,就不会报异常
![qq 20180106142720](https://user-images.githubusercontent.com/12113101/34637294-db62d0a4-f2ed-11e7-840a-2d15d18dfd4b.png)

**Comment by chenshuai2144** [comment]
这个 我感觉是babel做了一些比较奇怪的事情  
但是我还没又找到资料 ,
给 所有多余一个的子节点 加一个key 就能解决

**Comment by shizhiqian** [comment]
@chenshuai2144 嗯嗯

**Comment by chenshuai2144** [comment]
transform-react-inline-elements 
这个插件得原因 
https://github.com/facebook/react/issues/10352

**Comment by tclinhan** [comment]
什么时候能推出一个稳定版的DEMO呢，官网预览还不是最新的

**Comment by chenshuai2144** [comment]
clone 下来看吧. 我们正在更新文档.

**Comment by tclinhan** [comment]
早上刚clone了最新的，那个key的问题还在，还有点击 触发异常 那个新页面里面的几个异常页也出各种错误

**Comment by tclinhan** [comment]
![image](https://user-images.githubusercontent.com/3694559/34657417-c02cf584-f460-11e7-8a64-45c91244530f.png)

**Comment by chenshuai2144** [comment]
你更新一下最新的包.清空缓存重新安装.


这种情况是不是需要加个锁包文件? @afc163

**Comment by tclinhan** [comment]
我是clone最新的包，在新的文件夹下安装的，应该不存在缓存的情况

**Comment by afc163** [comment]
不加，交给使用方自行决定是否要锁。

**Comment by chenshuai2144** [comment]
@tclinhan  你是哪个请求404了?  
#542 就是解决这个问题的

**Comment by tclinhan** [comment]
demo中的这几个地方
![image](https://user-images.githubusercontent.com/3694559/34657679-b6326be2-f463-11e7-95cc-6e3f44f5d9cb.png)

**Comment by chenshuai2144** [comment]
这几个地方就是用来报错的......
😶

**Comment by tclinhan** [comment]
好的，坐等更新稳定版，辛苦了，技术大大~~

**Comment by nikogu** [comment]
fixed: https://github.com/ant-design/ant-design-pro/commit/5ade223021e54ace30ebfa60b31a38a403394a09

**Comment by chenshuai2144** [comment]
只是修复了一个页面, 需要编译工具修复

**Comment by chenshuai2144** [comment]
Really fixed [74b1e62 ](https://github.com/ant-design/ant-design-pro/commit/677d1718e9fda9b5dfc35e541a558fbc7c405fbf)
