### ISSUE TITLE
🧐[问题]ts与注解的取舍疑问.请大佬指导~~

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#5901]
### 🧐 问题描述

在v2版本时,@Form.create() @connect 用起来很舒服,代码量也少. 
用umi的话说就是约定大于配置.

自从v4版本上了ts后. 调用ts封装的组件,确实是比以前方便. 但是随之而来的就是自己写业务很麻烦,很麻烦,很麻烦. 代码量提升100+行

不用tsx吧,vscode又不提示. 用tsx吧,又得写.data.ts, 不然vscode各种红线提醒,无法忍受.

我太南了.又想要调用组件的时候有代码提示,又不想写那么多描述代码,只想专心写业务代码.

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/72677347-7515d980-3ad6-11ea-9ed9-dce531534770.png)

import { AnyAction, Reducer } from 'redux';
import { EffectsCommandMap } from 'dva';
这2个引入跟业务一点关系都没有.

export interface ModalState {
  currentUser?: Partial<CurrentUser>;
  province?: GeographicItemType[];
  city?: GeographicItemType[];
  isLoading?: boolean;
}

export type Effect = (
  action: AnyAction,
  effects: EffectsCommandMap & { select: <T>(func: (state: ModalState) => T) => T },
) => void;

export interface ModelType {
  namespace: string;
  state: ModalState;
  effects: {
    fetchCurrent: Effect;
    fetch: Effect;
    fetchProvince: Effect;
    fetchCity: Effect;
  };
  reducers: {
    saveCurrentUser: Reducer<ModalState>;
    changeNotifyCount: Reducer<ModalState>;
    setProvince: Reducer<ModalState>;
    setCity: Reducer<ModalState>;
    changeLoading: Reducer<ModalState>;
  };
}
这些ts描述,也不想写. dva中约定俗成的东西,每个model都要写一份,总感觉毫无意义.


export interface Member {
  avatar: string;
  name: string;
  id: string;
}

export interface BasicListItemDataType {
  id: string;
  owner: string;
  title: string;
  avatar: string;
  cover: string;
  status: 'normal' | 'exception' | 'active' | 'success';
  percent: number;
  logo: string;
  href: string;
  body?: any;
  updatedAt: number;
  createdAt: number;
  subDescription: string;
  description: string;
  activeUser: number;
  newUser: number;
  star: number;
  like: number;
  message: number;
  content: string;
  members: Member[];
}
表格list类的ts描述更是写的欲仙欲死,  每个字段都要进行声明. 太降低开发效率了.

**Comment by chenshuai2144** [comment]
静态类型还是非常有必要的。
你们的各种问题其实可以试试 通过swagger来生成 data.d, 或者推荐使用  http://www.jsontots.com/
vscode 也是有插件的，只有已经有了数据，就可以自动生成类型。
毕竟动态类型一时爽

**Comment by l745230** [comment]
能否在UmiUi中集成一下啊~~
根据mode 生成相关的ts
Form.create()  connect() 生成ts
json生成ts

**Comment by chenshuai2144** [comment]
可以去看看 antd@4 分支。
https://github.com/ant-design/pro-blocks/tree/antd%404
