### ISSUE TITLE
🧐[问题]umi-plugin-antd-theme这个插件能运用在roadhog上吗？

### ISSUE THREAD

**Issue by hzcdt** [ant-design/ant-design-pro#5902]
### 🧐 问题描述
我们现在用的还是dva+roadhog那套，所以想问下umi-plugin-antd-theme这个插件能运用在roadhog上吗？

**Comment by chenshuai2144** [comment]
不行的，这是 umi 的插件.
但是你可以用更底层的
https://github.com/chenshuai2144/merge-cssMoudle-less ，umi-plugin-antd-theme 是封装了它。a

**Comment by hzcdt** [comment]
> 不行的，这是 umi 的插件.
> 但是你可以用更底层的
> https://github.com/chenshuai2144/merge-cssMoudle-less ，umi-plugin-antd-theme 是封装了它。a

感谢回复，我昨天也想到了直接使用antd-pro-merge-less，不过报了如下错误：
![image](https://user-images.githubusercontent.com/54352257/72695336-19e5f480-3b73-11ea-89b9-50ce81c58439.png)
![image](https://user-images.githubusercontent.com/54352257/72695352-29fdd400-3b73-11ea-992d-4f7f286c2e17.png)

**Comment by chenshuai2144** [comment]
less 语法解析失败了额。你的antd 也是低版本的吗》

**Comment by hzcdt** [comment]
> less 语法解析失败了额。你的antd 也是低版本的吗？

我是删掉了node_modules，然后重新npm，看版本应该是antd最新的
![image](https://user-images.githubusercontent.com/54352257/72696886-d68e8480-3b78-11ea-8829-fedc89243580.png)
