### ISSUE TITLE
🐛布局为顶部菜单，主题为亮色时图标高度塌陷问题[BUG]

### ISSUE THREAD

**Issue by Norberta1314** [ant-design/ant-design-pro#5903]
### 🐛 bug 描述
当 defaultSetings 设置为：

> {"navTheme": "light",
>  "layout": "topmenu",}

时（无关配置已省略），RightContent 内的图标高度会小于 Header 的图标高度，截图如下：
![image](https://user-images.githubusercontent.com/26577320/72685041-07db6600-3b21-11ea-806a-c1ba4a214b62.png)

### 📷 复现步骤
defaultSettings 的配置为上方菜单，亮色主题（如上
### 🏞 期望结果
![image](https://user-images.githubusercontent.com/26577320/72685089-8932f880-3b21-11ea-8b57-9901a789afdd.png)

### © 版本信息

- Ant Design Pro 版本: 4.11.0-0
- umi 版本 2.13.3
- 浏览器环境 chrome
- 开发环境 mac OS Catalina

### 🚑 其他信息

啊我其实已经查到原因了
![image](https://user-images.githubusercontent.com/26577320/72685154-12e2c600-3b22-11ea-83e9-73f8708f0c73.png)
`div.right` 的父元素没有高度导致 height:100%继承不到，`div.right` 的高度是使用line-height 撑起的。然鹅这就苦了 `div.action`, `div.action` 的高度height:100% 也继承不到父元素高度……

**Comment by chenshuai2144** [comment]
非常感谢

**Comment by gx200918** [comment]
顶部菜单怎么设置的 呀，我在defaultSettings里面设置layout:'topmenu'不生效，修改name试了下也不生效，是不是defaultSetting都不生效
