### ISSUE TITLE
👑 请问ant有没有类似表单设计器的插件，类似Avue表单设计器？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#5905]
### 🥰 请问ant有没有类似表单设计器的插件，类似Avue表单设计器

官方能否也支持一下，把ant各大组件集成一个表单设计器插件啊？最近项目由vue改为ant,遇到表单设计器插件需求，发现在各大开源插件，都对ant,react支持的插件比较少，各位大神能否介绍一款，或者官方将ant各大组件集成表单设计器插件
![image](https://user-images.githubusercontent.com/37643958/72693647-a8a34300-3b6c-11ea-9a09-c6078a0e699c.png)

访问地址：http://112.74.43.150/

**Comment by chenshuai2144** [comment]
没有相关的开源项目
