### ISSUE TITLE
🧐[问题]pro的css规则

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design-pro#5906]
### 🧐 问题描述
关于pro的css规范。

下面截图是提交代码的时候出现的，。
这种规则能不能在VS上代码提示出来？
这样就不用每次提交看错误
如何做

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/48147837/72712496-1ae44980-3ba6-11ea-8203-931035f9e3c3.png)

**Comment by chenshuai2144** [comment]
用一下 lint:fix 
你可以装个 stylelint 插件来解决
