### ISSUE TITLE
🧐[问题]使用umi运行时配置patchRoutes方法调整路由时未能加载页面组件

### ISSUE THREAD

**Issue by Leon-JiangLe** [ant-design/ant-design-pro#5909]
### 🧐 问题描述
rt 运行后BisicLayout加载正常,但未能加载Welcome组件

### 💻 示例代码
新建src/app.js patchRoutes(routes)方法部分代码如下
```
routes[1].routes.unshift(`
`   {`
`      path: '/',`
`      component: `
`        dynamic({ `
`          component: () => import( './layouts/BasicLayout'),`
`        }),`
`      routes:[`
`        {`
`          path: '/',`
`          redirect: '/welcome',`
`        },`
`        {`
`         path: '/welcome',`
`          name: 'welcome',`
`          icon: 'smile',`
`          component:`
`            dynamic({`
`                component: () => import('./pages/Welcome'),`
`            }),`
`          // exact: true,` 
`        },`
`      ]`
`    }`
`  );`
```
config.ts中配置,
```
`{ `
`path: '/',`
`component: '../layouts/SecurityLayout',`
`routes: [`   
`{`
`component: './404',`
`},`
`],`
`},
``` 

### 🚑 其他信息

![antd-issue](https://user-images.githubusercontent.com/46557163/72782996-3a3fad00-3c60-11ea-8bb3-7350ae04b154.PNG)

**Comment by chenshuai2144** [comment]
没有听懂你的描述，你是希望可以动态修改路由吗？

**Comment by Leon-JiangLe** [comment]
感谢回复:&nbsp; 目前路由是在config.ts中的 routes: 字段下配置的一个数组,领导要求不在config中配置,想动态引入,也算是动态修改路由




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2020年1月28日(星期二) 晚上6:29
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;; 
抄送: "　"<852244241@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-pro] 類[问题]使用umi运行时配置patchRoutes方法调整路由时未能加载页面组件 (#5909)




没有听懂你的描述，你是希望可以动态修改路由吗？

**Comment by chenshuai2144** [comment]
路由是不能动态修改的，你最好修改菜单，路由决定了你会打包什么文件进去，如果你再路由配置中不包含，js都不会直接打入。

**Comment by jing-wu** [comment]
> 路由是不能动态修改的，你最好修改菜单，路由决定了你会打包什么文件进去，如果你再路由配置中不包含，js都不会直接打入。

有办法实现题主说的功能吗？我也有类似的需求，config.ts 里不配置一些路由，运行时动态添加路由。打包时包含所有文件是能接受的。

**Comment by chenshuai2144** [comment]
@jing-wu  你要的是动态菜单吗

**Comment by jing-wu** [comment]
@chenshuai2144 不是动态菜单。
目前的需求是前端拿到后端给的页面层级结构（包含 path 和 component），前端生成相应的路由，然后展示。层级结构是变化的，所以没法在 config.ts 里事先配置好。

**Comment by Leon-JiangLe** [comment]
@jing-wu  按照我上面贴的示例代码,你需要在 config.ts 中配置 layout层,然后可以动态向 layout层中的route属性内添加页面路由.但是不能动态的添加layout层

**Comment by jing-wu** [comment]
> @jing-wu 按照我上面贴的示例代码,你需要在 config.ts 中配置 layout层,然后可以动态向 layout层中的route属性内添加页面路由.但是不能动态的添加layout层

多谢！我尝试下。

另外，你提的这个问题现在解决了吗？Welcome组件没有加载，是因为没有事先在本地配置路由，所以打包时这个组件没有被打入，找不到组件导致的吗？

**Comment by exvu** [comment]
@Leon-JiangLe  有一个很笨的方法是，在routes配置中设置一个临时挂载点，挂载所有的路由，作用是加载l组件和model，待服务器获取菜单后，根据key取出挂载点的路由，修改后使用patchRoutes即可

**Comment by exvu** [comment]
@Leon-JiangLe  有一个很笨的方法是，在routes配置中设置一个临时挂载点，挂载所有的路由，作用是加载l组件和model，待服务器获取菜单后，根据key取出挂载点的路由，修改后使用patchRoutes即可

**Comment by peachapp** [comment]
> > @jing-wu 按照我上面贴的示例代码,你需要在 config.ts 中配置 layout层,然后可以动态向 layout层中的route属性内添加页面路由.但是不能动态的添加layout层
> 
> 多谢！我尝试下。
> 
> 另外，�你提的这个问题现在解决了吗？Welcome组件没有加载，是因为没有事先在本地配置路由，所以打包时这个组件没有被打入，找不到组件导致的吗？

遇到了同样的需求，可以动态修改吗 多级路由的那种

**Comment by peachapp** [comment]
> @jing-wu 按照我上面贴的示例代码,你需要在 config.ts 中配置 layout层,然后可以动态向 layout层中的route属性内添加页面路由.但是不能动态的添加layout层

想问一下 遇到了与你一样的问题，请问你的问题解决了吗

**Comment by jing-wu** [comment]
> > @jing-wu 按照我上面贴的示例代码,你需要在 config.ts 中配置 layout层,然后可以动态向 layout层中的route属性内添加页面路由.但是不能动态的添加layout层
> 
> 想问一下 遇到了与你一样的问题，请问你的问题解决了吗

动态路由是解决了，config.ts 中写死一个顶层 layout 作为动态路由构建层，里面拿到 props 中的路由对象，按照你要的层级动态修改路由对象就行了。修改完后重定向到你要跳转的页面

**Comment by Leon-JiangLe** [comment]
差不多的情况 &nbsp;无权限要求home页配置在config 以此为基 &nbsp;在登陆操作完成的时候 &nbsp;载入需要权限信息的layout ，触发app.tsx内的从后端获取菜单数据的方法获取数据 &nbsp;使用patchRoutes 注入到前面在config里配置的基础route&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 土豆泥 ***@***.***&gt;
发送时间: 2021年6月16日 10:39
收件人: ant-design/ant-design-pro ***@***.***&gt;
抄送: Leon-JiangLe ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[ant-design/ant-design-pro] ��[问题]使用umi运行时配置patchRoutes方法调整路由时未能加载页面组件 (#5909)

**Comment by hyzx86** [comment]
> 路由是不能动态修改的，你最好修改菜单，路由决定了你会打包什么文件进去，如果你再路由配置中不包含，js都不会直接打入。

是啊，主要是路由 跟 菜单搞在一起，建议路由上的菜单相关设定单独包裹起来，不要打平。。
刚上手的时候在这里卡了好久。。
后来用一个页面接收所有动态菜单就可以了。。类似404 路由
