### ISSUE TITLE
官方会发布VueJs版本的Antd吗？

### ISSUE THREAD

**Issue by FrankGuos** [ant-design/ant-design-pro#591]
看了ElementUI和IView实现的Vue，明显有抄袭嫌疑，还是相信专业团队的Antd。请问贵团队有VueJS官方版本的开发计划么？

**Comment by chenshuai2144** [comment]
来错地方了！

**Comment by chenshuai2144** [comment]
vue 用饿了吗也挺好的

**Comment by FrankGuos** [comment]
@chenshuai2144 就是不想用饿了吗，不够档次感觉，想用vue实现的antd才来问一下的

**Comment by chenshuai2144** [comment]
但是你来错地方了

**Comment by afc163** [comment]
暂时不会有这个计划，我们的精力和技术栈都不太可能做这个事。

https://github.com/ant-design/ant-design/wiki/FAQ#are-you-going-to-provide-vueetc-edition

**Comment by afc163** [comment]
另外，你不应该 Ant Design Pro 的地方询问 antd 相关的事情。

**Comment by chenshuai2144** [comment]
开完会还有时间来github.  不是有人现场给你提bug?

**Comment by FrankGuos** [comment]
@chenshuai2144 @afc163 感谢二位，问题提错了地方，尴尬

**Comment by yanlee26** [comment]
antd 逼格很高，值得研究借鉴的东西有很多；element就算了。。。
