### ISSUE TITLE
🐛[BUG]redux-saga的Error handling与umi-request的errorHandler不能同时使用

### ISSUE THREAD

**Issue by lirenhao** [ant-design/ant-design-pro#5910]
### 🐛 bug 描述
当使用redux-saga的[Error handling](https://redux-saga.js.org/docs/basics/ErrorHandling.html) ,异步请求返回状态码非200时，model中的effect不能获取error，我不认为是umi-request或者dva的问题，而是集成的问题

### 📷 复现步骤
调用@/utils/request后添加then、catch
```
import request from '@/utils/request';

export async function getTest() {
  return request('/api/permit/test')
    .then(response => ({ response }))
    .catch(error => ({ error }));
}
```
model的effects中不能够获取error
```
const {response, error} = yield call(getSvcs);
```
### 🏞 期望结果
由于umi-request是pro默认使用的fetch框架，希望能更好的跟redux-saga兼容

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
两个不可兼得的，
你可以使用 try  catch 来解决 yield 的报错
