### ISSUE TITLE
fixSiderbar 失效  默认为false  但却是一直固定的

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design-pro#5913]
![image](https://user-images.githubusercontent.com/47104575/72861512-16827280-3d05-11ea-9dd7-4b846e3f9e1e.png)
![image](https://user-images.githubusercontent.com/47104575/72861521-200bda80-3d05-11ea-9ce0-66f50b4a87ec.png)
刷新 和 清空缓存都试过了

**Comment by chenshuai2144** [comment]
无法再现，你是使用最新的 layout 吗？
