### ISSUE TITLE
TypeError: intl_messageformat_1.default.__addLocaleData is not a function

### ISSUE THREAD

**Issue by seed-fe** [ant-design/ant-design-pro#5916]
### 🐛 bug 描述
按照ant design pro 官网文档的步骤安装或者直接clone后安装，启动后浏览器页面里报标题中的错误，v4和v2版本都是这样，8月份的时候在同一台电脑上安装的v4没有问题。

TypeError: intl_messageformat_1.default.__addLocaleData is not a function
![image](https://user-images.githubusercontent.com/21357576/73167906-b55b0480-4133-11ea-9b2d-35dbef524a6a.png)

Unhandled Rejection (TypeError): intl_messageformat_1.default.__addLocaleData is not a function
![image](https://user-images.githubusercontent.com/21357576/73172031-0e7b6600-413d-11ea-942e-aa7b5050309c.png)

### 🏞 期望结果
能正常启动进入页面

**Comment by seed-fe** [comment]
用npm install不报错了

**Comment by one-juru** [comment]
Got the same problem today. @seed-fe How did you fix it?

![image](https://user-images.githubusercontent.com/79324991/112138621-077da580-8bd2-11eb-9403-afc03b4342f8.png)
