### ISSUE TITLE
把ant-design-pro 系统，做成内核-插件的模式 。。

### ISSUE THREAD

**Issue by lusess123** [ant-design/ant-design-pro#592]
能否把ant-design-pro 封装成一个npm 包做为一个内核，而我们新增的页面 或者 多个页面组成的模块，或者 模块组成项目 ，作为单独发布的插件包。

**Comment by WhatAKitty** [comment]
[独立使用Antd-pro组件](https://pro.ant.design/docs/use-components-alone)

**Comment by afc163** [comment]
很好的想法，目前可能没有精力抽象，有更具体的建议可以在这里讨论。

**Comment by unrealsmart** [comment]
确实，使用脚手架的话，因为本来就有不少 Components，和新增的自定义组件混在一起，那感觉，不要不要的。

暂时可以

- 自定义组件目录：`components-custom`
- 自定义布局目录：`layouts-custom`
- 自定义其他目录：`xxx-custom`

组件可以 `Copy` 出来

**Comment by yutingzhao1991** [comment]
有一个想法，可以让 antdpro 在页面级别实现据欧洲。把路由，菜单，主题这些再抽象一下，形成一套标准。使得可以开发出更多类型的页面，让社区的力量也贡献进来，形成一套页面市场这样的东西。

**Comment by lusess123** [comment]
我讲一下，我在之前的公司 。 前端模块化  的一些实现方式：

设计思路：

整体来说，由于  平台+多个项目，内核+插件 在传统桌面客户端开发（winForm,wpf）的应用级的系统 已经相当成熟。而前端发展至今，组件化，模块化，工程化
已经达到相当高度， 所以可以借鉴和照搬 java / c#，（主要是.net）这些静态编程语言在做客户端系统（winForm,wpf），以及服务端系统(asp.net mvc )的一些设计思路。

需求场景：

我所在的公司是2b软件外包性质的，同时会进行好几个后台管理系统项目的开发.公司分为 一个横向平台组 和多个垂直的项目组。
铁打的平台流水的项目，平台为多个项目提供服务的同时，项目反哺平台。
 很自然的，平台组开发和维护的是一些公共可复用的代码，包括：

 菜单，路由，外部页面框架，可复用的组件，基本上就是ant designer pro 这样的，
 如果能跟服务端集成的话，还可包括： 
对于某个业务对象（通常是数据库的单表，或者多表）增删改查动态表单，权限，工作流，消息聚合推送....等等，为各个项目组提供各种基础服务。

而项目组开发和维护的代码大概分成2部分：

1.具体业务逻辑实现，大概就是具体页面的实现，面向的是最终用户。
2.平台个性化的声明式代码（比如 配置，模版），用这种方式消费平台组提供的功能。

以下是供大家讨论几个实现想法或者建议：

1.各个项目都是独立的包（模块），所共同依赖的平台也是独立的包（模块），部署到 私有 npm服务器上的。
 
2.包（模块）的实现和声明（接口） 分离，虽然正常情况平台代码的变动不会太频繁，但是每次变动，项目组都要卸载当前依赖的平台版本，获取最新的版本。这些改动中，有相当一大部分的改动是平台模块的具体实现，而声明部分 可能保持不变，或者只是增加声明项。这个时候，如果项目在开发阶段只依赖平台的 声明包，而不管实现包，将极大减少同步依赖包的次数，不过由于浏览器端要控制打包大小，除了要懒加载外，也要做tree shaking,跟java/.net 不同的是，必须要源码依赖，不过其实，我们可以把依赖方案分成开发阶段，和  发布阶段 两种不同的方式来解决。

3.使用typescript 的interface，abstract class   和Decorator   来定义平台的接口和契约 。学习java 的spring ,以ioc 为基石构建整个插件系统。比如，我们要新增某个页面，就是新建一个class继承于平台定义的BasePage (参考asp.net 的 webform),这个页面对于平台来说就是一个插件，可以在该class头上做Annotation, 标记 plug regname  ,或者直接标记 路由信息。

4.可以定义平台级别的event bus  ，提供接口给项目调用。

5.由于可选的模块层级和依赖不同，根据依赖导致原则，平台包会分解成多个包，整个平台架构应该是一个 洋葱状的多层级同心圆（倒立金字塔）
最里面（金字塔顶尖）的是核心的插件系统包，最外部（金字塔底部）是具体的项目包。

6.对于传统 客户端，服务端 java/.net开发出身的前端来说，拿着把锤子，看啥都是钉子.....

**Comment by unrealsmart** [comment]
大大们可以提供代码层思路吗

**Comment by LaiHuanMin** [comment]
我觉得还是不要把components的组件放到npm下，因为有时候components并不是特别完全就符合业务的需求，比如说我要修改UserLayout的某个图标，添加某个Input，如果都放在npm下面我就没办法自定义再进行修改了。    

即使你说components的props再丰富些，那也不如自己直接进行修改。

**Comment by afc163** [comment]
@LaiHuanMin 现在就是这个思路，所有的 components 都在源码里，有需求可以直接改。

**Comment by lusess123** [comment]
目前的 ant-designer-pro  就是个 SDK
