### ISSUE TITLE
🐛[BUG] 登录页面出现错误_form.default.create(...) is not a function

### ISSUE THREAD

**Issue by lichnow** [ant-design/ant-design-pro#5928]
### 🐛 bug 描述

`npm run fetch:blocks`后刷新登录页出现报错
```
Unhandled Rejection (TypeError): _form.default.create(...) is not a function
./src/pages/user/login/components/Login/index.tsx
src/pages/user/login/components/Login/index.tsx:161
```

### 📷 复现步骤

umi安装antd pro后再运行`npm run fetch:blocks`与`npm start`，打开页面后再退出登录，接着刷新

### 🏞 期望结果

与初始安装后一样的正常登录页

### © 版本信息

- Ant Design Pro 版本: [4.11]
- umi 版本 [2.13]
- 浏览器环境 [chrome]
- 开发环境 [emac OS]

### 🚑 其他信息

<img width="1056" alt="截屏2020-02-01上午3 04 49" src="https://user-images.githubusercontent.com/1695900/73566763-a1026900-449f-11ea-90ba-d8372389b510.png">

**Comment by xiaohuoni** [comment]
是不是没有安装 @ant-design/compatible ？

**Comment by lichnow** [comment]
@xiaohuoni 是的。。。

**Comment by viniciusfss** [comment]
I have the same issue here.. @lichnow , what was your solution for this?

我这里有同样的问题.. @lichnow ，您对此有何解决方案？

**Comment by mulspace** [comment]
我也遇到同样问题，最后解决了。
1. yarn add @ant-design/compatible
2. 把原来的
import {Form} from 'antd';
改成
import { Form } from '@ant-design/compatible'
