### ISSUE TITLE
关于pro 的权限问题 ，这样设计的好处在哪？

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design-pro#5930]
把角色绑定在路由上， 角色是用户自定义的，角色可以无限多，请问你把角色都绑定到路由可考虑过后端的设计，这种设计是不是就为了支持一个后台两三个角色就满足了呢。写了那么复杂是我笨看不到他的优秀？

**Comment by chenshuai2144** [comment]
可以搜一下历史的issue，我们的权限系统是一个非常简单的系统，你可以通过function 等其他方式来扩展它。未来的会有内部沉淀出来的其他库来实现这个功能。

**Comment by chenshuai2144** [comment]
如果你期望一个复杂的强大的权限体系，我建议是自研，通过的权限必然牺牲灵活性。复杂的同时也会造成繁多的 api 。
