### ISSUE TITLE
🐛[BUG] Route Recursive Authority

### ISSUE THREAD

**Issue by NarApp** [ant-design/ant-design-pro#5931]
## the line with the problem
https://github.com/ant-design/ant-design-pro/blob/1f60fb7e96c818d4cda9eeb549918c477437dbcc/src/utils/utils.ts#L37

## solution of the problem
`  const authority = router.find(({ path = '/', ...sub }) => {
    return path && pathRegexp(path).exec(pathname) || sub.routes && getAuthorityFromRouter(sub.routes,pathname)
  });`

**Comment by chenshuai2144** [comment]
give a pr?

**Comment by NarApp** [comment]
I had no time during the day.
I have finished working now.
I sent a pull request.
https://github.com/ant-design/ant-design-pro/pull/5933
