### ISSUE TITLE
用hook升级数据流(dva)👑 [需求]

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#5932]
### 🥰 需求描述

这次antd pro要使用antd4，在升级的过程中是否考虑将antd pro的数据流（dva）一并考虑用hook的方式升级。
**dva的问题**
1. 概念太多，学习成本高
2. 样板代码太多，很冗余

### 🧐 解决方案

考虑使用umi 插件的方式： @umijs/plugin-model

### 🚑 最佳实践

Pro 4 已经发布有一些时间了，在内外部的各种实践中我们期望可以探索出一套最佳实践，sorrycc  的文章中做了很深的思考。接下来我们会发布我们的解决方案。敬请期待！

**Comment by afc163** [comment]
应该很快就会做改造了。

**Comment by chenshuai2144** [comment]
最佳实践已经含苞待放，在3月中旬左右就会完工。🕊

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/6023
