### ISSUE TITLE
🧐[问题]暗黑主题下的菜单为什么与header的颜色不统一?

### ISSUE THREAD

**Issue by lichnow** [ant-design/ant-design-pro#5934]
### 🧐 问题描述

选择暗黑主题后菜单还是默认的深色，与顶部header不统一，显得非常突兀。而[https://antdtheme.com/dark](https://antdtheme.com/dark)的颜色是统一的，请问如何才能实现https://antdtheme.com/dark一样的效果呢？

### 🚑 其他信息
[ant design pro](https://preview.pro.ant.design/)
<img width="805" alt="截屏2020-02-04上午7 48 39" src="https://user-images.githubusercontent.com/1695900/73700891-ca7ef700-4722-11ea-95a3-c3e92327b232.png">

[改了一下的ant design pro vue](https://preview.pro.loacg.com)
<img width="872" alt="截屏2020-02-04上午7 42 04" src="https://user-images.githubusercontent.com/1695900/73700746-58a6ad80-4722-11ea-9f97-9484a2e4d704.png">

[ant的dark theme](https://antdtheme.com/dark)
<img width="941" alt="截屏2020-02-04上午7 42 55" src="https://user-images.githubusercontent.com/1695900/73700755-5d6b6180-4722-11ea-8012-73d33d33970a.png">

**Comment by chenshuai2144** [comment]
设计是这样的，你可以关掉自己修改菜单的主题 ，等 antd 官方发布了就可以切换了

**Comment by TianEnPang** [comment]
> 设计是这样的，你可以关掉自己修改菜单的主题 ，等 antd 官方发布了就可以切换了，
> 现在黑色主题还是个玩具

antd@4不是发布了黑色主题的菜单了嘛？怎么现在用不来呢？
