### ISSUE TITLE
🐛[BUG] 在global.less 引入 antd全局替换样式无效

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design-pro#5935]
### 🐛 bug 描述
在global.less 引入 antd全局替换样式无效 

### 📷 复现步骤
在使用pro + antd v4 版本

### 🏞 期望结果
能在global.less 中 引入 全局替换样式  一次奏效

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24733229/73713033-ea281680-4746-11ea-926e-8504430f68c9.png)

**Comment by wfnuser** [comment]
怎么解决的呀？ 我似乎也碰到了这个问题

**Comment by chenshuai2144** [comment]
直接在config.ts 中配置 theme 就好了
