### ISSUE TITLE
npm run fetch:blocks 下载了十几次都卡住，后面证实了是过年回老家，老家的宽带网络的问题

### ISSUE THREAD

**Issue by hegphegp** [ant-design/ant-design-pro#5937]
### 问题描述
* npm run fetch:blocks 下载了十几次都卡住，该如何处理？
* 我配置了npm,yarn,cnpm的淘宝源，npm config set registry https://registry.npm.taobao.org --verbose
* 各种方法都试了，我本地有 Shadowsocks 代理的，我配置了npm代理还是不行
```
npm config set https-proxy socks5://localhost:1080
npm config set proxy socks5://localhost:1080
```
可否给出可行的方案，否则全国几十万前端开发者，如果有10%遇到这个问题，就是几万人都遇到的，每个人都耗费一天半天去解决这个问题的话，就是几万天的

**Comment by hegphegp** [comment]
这个问题搞得我很绝望，很崩溃，很头痛，各种百度，各种谷歌查找方法，都是失败告终

**Comment by zula1994** [comment]
我也下了一天 疯了

**Comment by hihuangwei** [comment]
使用淘宝NPM  npm.tapbap.com

**Comment by hegphegp** [comment]
我已经配置了  npm config set registry https://registry.npm.taobao.org

**Comment by hegphegp** [comment]
@chenshuai2144 @afc163 
#### 这个是什么原因导致的
* 1) 国内网络的原因
* 2) 第三方插件版本的原因
* 3) 代码的原因

#### 我折腾了一天后，我用 git status 发现下面目录已经是完整把插件库下载好的
```
~/.umi/blocks/github.com/ant-design/pro-blocks
```

我在github仓库搜索关于 npm run fetch:blocks 的问题，发现这个问题在 2019 年就存在了的，希望给一个解决方法，这个问题搞得我很绝望，很崩溃，很头痛，各种百度，各种谷歌查找方法，都是失败告终。希望你们有个好的解决方案，谢谢。
@chenshuai2144  @afc163

**Comment by chenshuai2144** [comment]
@hegphegp 
https://github.com/ant-design/ant-design-pro-cli 按照这个文档可以打开 debug，会输出很多日志
我们现在使用的国内的 gitee，一般这种都是权限或者 文件不合理导致的

**Comment by hegphegp** [comment]
* 老家移动宽带网络的问题
#### 三个例子证明了
1) 我连上公司vpn后，在公司的虚拟机创建项目，执行 npm run fetch:blocks 命令，不翻墙，完全不卡
2) 我连上自己的阿里云服务器，创建项目，执行 npm run fetch:blocks 命令，不翻墙，完全不卡
3) 我连上自己的腾讯云服务器，创建项目，执行 npm run fetch:blocks 命令，不翻墙，完全不卡

##### 在老家的移动宽带网络，发现之前很多网站访问不了，用ssh也连不上国外的vultr服务器，但是用公司的网络能ssh国外的vultr服务器，登录阿里云服务器后能ssh国外的vultr服务器，登录腾讯云服务器后能ssh国外的vultr服务器

**Comment by afc163** [comment]
@hegphegp 我的梯子也是，老家宽带 ping 不通 ip，公司可以。
