### ISSUE TITLE
npm ERR! Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by shahidkarimi** [ant-design/ant-design-pro#594]
[    ..............] | fetchMetadata: verb afterAdd /home/vagrant/.npm/add-dom-event-listener/1.0.2/package/package.json written[    ..............] | fetchMetadata: verb afterAdd /home/vagrant/.npm/add-dom-event-listener/1.0.2/package/package.json written[    ..............] | fetchMetadata: verb afterAdd /home/vagrant/.npm/add-dom-event-listener/1.0.2/package/package.json written[    ..............] - fetchMetadata: verb afterAdd /home/vagrant/.npm/add-dom-event-listener/1.0.2/package/package.json written[    ..............] - fetchMetadata: verb afterAdd /home/vagrant/.npm/hoist-non-react-statics/2.3.1/package/package.json writte[    ..............] - fetchMetadata: verb afterAdd /home/vagrant/.npm/hoist-non-react-statics/2.3.1/package/package.json writte[    ..............] - fetchMetadata: verb afterAdd /home/vagrant/.npm/hoist-non-react-statics/2.3.1/package/package.json writte[     .............] \ fetchMetadata: verb afterAdd /home/vagrant/.npm/validate-npm-package-license/3.0.1/package/package.json w[     .............] \ fetchMetadata: verb afterAdd /home/vagrant/.npm/validate-npm-package-license/3.0.1/package/package.json w[     .............] \ fetchMetadata: verb afterAdd /home/vagrant/.npm/validate-npm-package-license/3.0.1/package/package.json wnpm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/code/lalazar/ant-design-pro/npm-debug.log
vagrant@homestead:~/code/lalazar/ant-design-pro$ npm install ant-design-pro-cli -g
npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "ant-design-pro-cli" "-g"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by afc163** [comment]
没有重现环境，能否帮助排查？

**Comment by shahidkarimi** [comment]
这很容易生产。 只要尝试在Ubuntu上安装。
Node: v6.12.0
npm: 3.10.10

**Comment by sorrycc** [comment]
node 用 8 试试。
