### ISSUE TITLE
🐛[BUG]添加查询表格失败

### ISSUE THREAD

**Issue by Leskur** [ant-design/ant-design-pro#5940]
### 🐛 bug 描述
🚧  Execute task error: find dependencies conflict between block and your project:* @ant-design/pro-table: ^2.0.0(your project) not compatible with ^1.0.22(block)

### 📷 复现步骤
1. npm create umi
2. npm install
3. npm run start
4. 添加模板 -> 表格 -> 查询表格

### 🏞 期望结果
正常的添加模板

### 💻 复现代码
无

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本: [2.13.0]
- 浏览器环境: [Chrome]
- 开发环境: [mac OS]

**Comment by chenshuai2144** [comment]
@Leskur 依赖冲突了

**Comment by chenshuai2144** [comment]
已经解决，可以重试一下了

**Comment by Leskur** [comment]
@chenshuai2144 试了下还是不行呢

**Comment by botue** [comment]
遇到了相同的问题

**Comment by Leskur** [comment]
以下是我的重现步骤和临时解决方案：

- 重现步骤：
  1. npm create umi

  2. npm create umi

  3. npm install && npm start

  4. 添加查询表格模板
     1. 如果 npm create umi 时选择了使用 antd@4，此时就会提示错误： @ant-design/pro-table: ^2.0.0(your project) not compatible with ^1.0.22(block)

      1. 如果 npm create umi 时选择不使用 antd@4 而使用 antd@3。此时就能成功添加模板，并且会在 package.json 下添加对应的依赖： @ant-design/compatible: 0.0.1-rc.1

          停止运行后再次 npm start 并添加查询表格，此时会提示错误： @ant-design/compatible: 0.0.1-rc.1(your project) not compatible with ^0.0.1-rc.0(block)

- 临时解决方案：

  1. 出现上诉错误后删除 package.json 中提示错误依赖。如：@ant-design/pro-table 或 @ant-design/compatible
      
      在 package.json 里删除即可，不需要 npm uninstall 模块，因为项目中引用了该模块。

  2. 然后停止运行后再次 npm start，此时再次添加查询表格模板就能成功了。

      并且在下次 npm start 之前都可以正常添加模板。

- 存在问题：
每次要添加模板时候都需要在 npm start 之间在 package.json 中删除对应的依赖，这样就很烦～

**Comment by botue** [comment]
@Leskur 测试这样可以，谢谢

**Comment by Leskur** [comment]
@botue 看最后一行，可以比较有效的解决。

**Comment by chenshuai2144** [comment]
你用的是哪个分支呢？

**Comment by Leskur** [comment]
npm create umi 选择 ant-design-pro、TypeTypeScript、antd@4

**Comment by chenshuai2144** [comment]
需要增加一个新的参数了

**Comment by botue** [comment]
@Leskur 了解了，多谢

**Comment by YellowPure** [comment]
@Leskur 请问，按照你的临时方案运行之后，添加完重新运行项目会提示以下错误
`Unhandled Rejection (TypeError): antd_es_form__WEBPACK_IMPORTED_MODULE_5__.default.create(...) is not a function`

**Comment by Leskur** [comment]
@YellowPure 你重新安装下 @ant-design/compatible 试试

**Comment by hx4111** [comment]
> @Leskur 请问，按照你的临时方案运行之后，添加完重新运行项目会提示以下错误
> `Unhandled Rejection (TypeError): antd_es_form__WEBPACK_IMPORTED_MODULE_5__.default.create(...) is not a function`

遇到同样的问题，请问如何解决的？

**Comment by YellowPure** [comment]
@Leskur  Thanks for help!
I remove all, install  "antd": "^3.23.6" to cross this problem.

**Comment by liyinSakura** [comment]
我也遇到同样的bug了，添加的是注册表单。
📷 复现步骤
npm create umi -> v4 -> ts
npm install
npm start
添加模板 -> 表格 -> 注册表格

报错Unhandled Rejection (TypeError): _form.default.create(...) is not a function

**Comment by Leskur** [comment]
@liyinSakura 控制台报错：[antd: Form] antd v4 removed `Form.create`. Please remove or use `@ant-design/compatible` instead.
因为 antd v4 移除了 Form.create，所以请使用 `@ant-design/compatible`。

需要使用 `Form.create` 的话，一下是解决方法：

1. 安装 `@ant-design/compatible` 模块。
  ```bash
  npm i --save @ant-design/compatible
  ```
2. 修改引用方式。
``` javascript
import { Form } from '@ant-design/compatible';
import '@ant-design/compatible/assets/index.css';
```
