### ISSUE TITLE
umi-serve was not found in dll umi 🐛[BUG]

### ISSUE THREAD

**Issue by arherzf8er** [ant-design/ant-design-pro#5942]
### 🐛 bug 描述

Clean install on MacOS Catalina gives error:
Dependencies were not found: umi-serve in dll umi

After adding those dependencies into dev:
Module parse failed: Unexpected character '#' (1:0)

After commenting out that line:
This dependency was not found:
* module in ./node_modules/prettier/third-party.js

Prettier is in dev

### 📷 复现步骤

```
npm install
npm run start
```

### © 版本信息

- Ant Design Pro 版本: 4.0
- umi 2.4.4
- MacOS 10.15.2
- Node v12.15.0
- npm v6.13.4

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/29209372/73964903-f7a2f380-4934-11ea-92d8-be177c4fb75c.png)
![image](https://user-images.githubusercontent.com/29209372/73965238-93346400-4935-11ea-89a3-92e0fee6bbcf.png)
![image](https://user-images.githubusercontent.com/29209372/73965676-66348100-4936-11ea-960b-f6a6829118c0.png)

**Comment by chenshuai2144** [comment]
try new cersion
