### ISSUE TITLE
Error installing on ubuntu

### ISSUE THREAD

**Issue by shahidkarimi** [ant-design/ant-design-pro#595]
9236 silly addNameRange   range: '>=1.0.2 <2.0.0',
9236 silly addNameRange   hasData: false }
9237 silly mapToRegistry name spdx-license-ids
9238 silly mapToRegistry using default registry
9239 silly mapToRegistry registry https://registry.npmjs.org/
9240 silly mapToRegistry data Result {
9240 silly mapToRegistry   raw: 'spdx-license-ids',
9240 silly mapToRegistry   scope: null,
9240 silly mapToRegistry   escapedName: 'spdx-license-ids',
9240 silly mapToRegistry   name: 'spdx-license-ids',
9240 silly mapToRegistry   rawSpec: '',
9240 silly mapToRegistry   spec: 'latest',
9240 silly mapToRegistry   type: 'tag' }
9241 silly mapToRegistry uri https://registry.npmjs.org/spdx-license-ids
9242 verbose addNameRange registry:https://registry.npmjs.org/spdx-license-ids not in flight; fetching
9243 verbose get https://registry.npmjs.org/spdx-license-ids not expired, no request
9244 silly addNameRange number 2 { name: 'spdx-license-ids',
9244 silly addNameRange   range: '>=1.0.2 <2.0.0',
9244 silly addNameRange   hasData: true }
9245 silly addNameRange versions [ 'spdx-license-ids',
9245 silly addNameRange   [ '0.0.0',
9245 silly addNameRange     '1.0.0',
9245 silly addNameRange     '1.0.1',
9245 silly addNameRange     '1.0.2',
9245 silly addNameRange     '1.1.0',
9245 silly addNameRange     '1.2.0',
9245 silly addNameRange     '1.2.1',
9245 silly addNameRange     '1.2.2',
9245 silly addNameRange     '2.0.0',
9245 silly addNameRange     '2.0.1' ] ]
9246 silly addNamed spdx-license-ids@1.2.2
9247 verbose addNamed "1.2.2" is a plain semver version for spdx-license-ids
9248 silly cache afterAdd spdx-license-ids@1.2.2
9249 verbose afterAdd /home/vagrant/.npm/spdx-license-ids/1.2.2/package/package.json not in flight; writing
9250 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
9251 verbose afterAdd /home/vagrant/.npm/spdx-license-ids/1.2.2/package/package.json written
9252 silly fetchNamedPackageData find-up
9253 silly mapToRegistry name find-up
9254 silly mapToRegistry using default registry
9255 silly mapToRegistry registry https://registry.npmjs.org/
9256 silly mapToRegistry data Result {
9256 silly mapToRegistry   raw: 'find-up',
9256 silly mapToRegistry   scope: null,
9256 silly mapToRegistry   escapedName: 'find-up',
9256 silly mapToRegistry   name: 'find-up',
9256 silly mapToRegistry   rawSpec: '',
9256 silly mapToRegistry   spec: 'latest',
9256 silly mapToRegistry   type: 'tag' }
9257 silly mapToRegistry uri https://registry.npmjs.org/find-up
9258 silly fetchNamedPackageData read-pkg
9259 silly mapToRegistry name read-pkg
9260 silly mapToRegistry using default registry
9261 silly mapToRegistry registry https://registry.npmjs.org/
9262 silly mapToRegistry data Result {
9262 silly mapToRegistry   raw: 'read-pkg',
9262 silly mapToRegistry   scope: null,
9262 silly mapToRegistry   escapedName: 'read-pkg',
9262 silly mapToRegistry   name: 'read-pkg',
9262 silly mapToRegistry   rawSpec: '',
9262 silly mapToRegistry   spec: 'latest',
9262 silly mapToRegistry   type: 'tag' }
9263 silly mapToRegistry uri https://registry.npmjs.org/read-pkg
9264 verbose request uri https://registry.npmjs.org/find-up
9265 verbose request no auth needed
9266 info attempt registry request try #1 at 9:06:30 PM
9267 verbose etag "5a305f26-2c0c"
9268 verbose lastModified Tue, 12 Dec 2017 22:58:46 GMT
9269 http request GET https://registry.npmjs.org/find-up
9270 verbose request uri https://registry.npmjs.org/read-pkg
9271 verbose request no auth needed
9272 info attempt registry request try #1 at 9:06:30 PM
9273 verbose etag "59fd7544-1e82"
9274 verbose lastModified Sat, 4 Nov 2017 8:07:32 GMT
9275 http request GET https://registry.npmjs.org/read-pkg
9276 http 304 https://registry.npmjs.org/find-up
9277 verbose headers { date: 'Sat, 06 Jan 2018 21:06:30 GMT',
9277 verbose headers   via: '1.1 varnish',
9277 verbose headers   'cache-control': 'max-age=300',
9277 verbose headers   etag: '"5a305f26-2c0c"',
9277 verbose headers   age: '5605',
9277 verbose headers   connection: 'keep-alive',
9277 verbose headers   'x-served-by': 'cache-sin18025-SIN',
9277 verbose headers   'x-cache': 'HIT',
9277 verbose headers   'x-cache-hits': '29',
9277 verbose headers   'x-timer': 'S1515272790.192700,VS0,VE0',
9277 verbose headers   vary: 'Accept-Encoding, Accept' }
9278 silly get cb [ 304,
9278 silly get   { date: 'Sat, 06 Jan 2018 21:06:30 GMT',
9278 silly get     via: '1.1 varnish',
9278 silly get     'cache-control': 'max-age=300',
9278 silly get     etag: '"5a305f26-2c0c"',
9278 silly get     age: '5605',
9278 silly get     connection: 'keep-alive',
9278 silly get     'x-served-by': 'cache-sin18025-SIN',
9278 silly get     'x-cache': 'HIT',
9278 silly get     'x-cache-hits': '29',
9278 silly get     'x-timer': 'S1515272790.192700,VS0,VE0',
9278 silly get     vary: 'Accept-Encoding, Accept' } ]
9279 verbose etag https://registry.npmjs.org/find-up from cache
9280 verbose get saving find-up to /home/vagrant/.npm/registry.npmjs.org/find-up/.cache.json
9281 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
9282 silly resolveWithNewModule find-up@1.1.2 checking installable status
9283 silly cache add args [ 'find-up@^1.0.0', null ]
9284 verbose cache add spec find-up@^1.0.0
9285 silly cache add parsed spec Result {
9285 silly cache add   raw: 'find-up@^1.0.0',
9285 silly cache add   scope: null,
9285 silly cache add   escapedName: 'find-up',
9285 silly cache add   name: 'find-up',
9285 silly cache add   rawSpec: '^1.0.0',
9285 silly cache add   spec: '>=1.0.0 <2.0.0',
9285 silly cache add   type: 'range' }
9286 silly addNamed find-up@>=1.0.0 <2.0.0
9287 verbose addNamed ">=1.0.0 <2.0.0" is a valid semver range for find-up
9288 silly addNameRange { name: 'find-up', range: '>=1.0.0 <2.0.0', hasData: false }
9289 silly mapToRegistry name find-up
9290 silly mapToRegistry using default registry
9291 silly mapToRegistry registry https://registry.npmjs.org/
9292 silly mapToRegistry data Result {
9292 silly mapToRegistry   raw: 'find-up',
9292 silly mapToRegistry   scope: null,
9292 silly mapToRegistry   escapedName: 'find-up',
9292 silly mapToRegistry   name: 'find-up',
9292 silly mapToRegistry   rawSpec: '',
9292 silly mapToRegistry   spec: 'latest',
9292 silly mapToRegistry   type: 'tag' }
9293 silly mapToRegistry uri https://registry.npmjs.org/find-up
9294 verbose addNameRange registry:https://registry.npmjs.org/find-up not in flight; fetching
9295 verbose get https://registry.npmjs.org/find-up not expired, no request
9296 silly addNameRange number 2 { name: 'find-up', range: '>=1.0.0 <2.0.0', hasData: true }
9297 silly addNameRange versions [ 'find-up',
9297 silly addNameRange   [ '1.0.0', '1.1.0', '1.1.1', '1.1.2', '2.0.0', '2.1.0' ] ]
9298 silly addNamed find-up@1.1.2
9299 verbose addNamed "1.1.2" is a plain semver version for find-up
9300 http 304 https://registry.npmjs.org/read-pkg
9301 verbose headers { date: 'Sat, 06 Jan 2018 21:06:30 GMT',
9301 verbose headers   via: '1.1 varnish',
9301 verbose headers   'cache-control': 'max-age=300',
9301 verbose headers   etag: '"59fd7544-1e82"',
9301 verbose headers   age: '5605',
9301 verbose headers   connection: 'keep-alive',
9301 verbose headers   'x-served-by': 'cache-sin18034-SIN',
9301 verbose headers   'x-cache': 'HIT',
9301 verbose headers   'x-cache-hits': '23',
9301 verbose headers   'x-timer': 'S1515272790.210366,VS0,VE0',
9301 verbose headers   vary: 'Accept-Encoding, Accept' }
9302 silly get cb [ 304,
9302 silly get   { date: 'Sat, 06 Jan 2018 21:06:30 GMT',
9302 silly get     via: '1.1 varnish',
9302 silly get     'cache-control': 'max-age=300',
9302 silly get     etag: '"59fd7544-1e82"',
9302 silly get     age: '5605',
9302 silly get     connection: 'keep-alive',
9302 silly get     'x-served-by': 'cache-sin18034-SIN',
9302 silly get     'x-cache': 'HIT',
9302 silly get     'x-cache-hits': '23',
9302 silly get     'x-timer': 'S1515272790.210366,VS0,VE0',
9302 silly get     vary: 'Accept-Encoding, Accept' } ]
9303 verbose etag https://registry.npmjs.org/read-pkg from cache
9304 verbose get saving read-pkg to /home/vagrant/.npm/registry.npmjs.org/read-pkg/.cache.json
9305 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
9306 silly resolveWithNewModule read-pkg@1.1.0 checking installable status
9307 silly cache add args [ 'read-pkg@^1.0.0', null ]
9308 verbose cache add spec read-pkg@^1.0.0
9309 silly cache add parsed spec Result {
9309 silly cache add   raw: 'read-pkg@^1.0.0',
9309 silly cache add   scope: null,
9309 silly cache add   escapedName: 'read-pkg',
9309 silly cache add   name: 'read-pkg',
9309 silly cache add   rawSpec: '^1.0.0',
9309 silly cache add   spec: '>=1.0.0 <2.0.0',
9309 silly cache add   type: 'range' }
9310 silly addNamed read-pkg@>=1.0.0 <2.0.0
9311 verbose addNamed ">=1.0.0 <2.0.0" is a valid semver range for read-pkg
9312 silly addNameRange { name: 'read-pkg', range: '>=1.0.0 <2.0.0', hasData: false }
9313 silly mapToRegistry name read-pkg
9314 silly mapToRegistry using default registry
9315 silly mapToRegistry registry https://registry.npmjs.org/
9316 silly mapToRegistry data Result {
9316 silly mapToRegistry   raw: 'read-pkg',
9316 silly mapToRegistry   scope: null,
9316 silly mapToRegistry   escapedName: 'read-pkg',
9316 silly mapToRegistry   name: 'read-pkg',
9316 silly mapToRegistry   rawSpec: '',
9316 silly mapToRegistry   spec: 'latest',
9316 silly mapToRegistry   type: 'tag' }
9317 silly mapToRegistry uri https://registry.npmjs.org/read-pkg
9318 verbose addNameRange registry:https://registry.npmjs.org/read-pkg not in flight; fetching
9319 verbose get https://registry.npmjs.org/read-pkg not expired, no request
9320 silly addNameRange number 2 { name: 'read-pkg', range: '>=1.0.0 <2.0.0', hasData: true }
9321 silly addNameRange versions [ 'read-pkg', [ '1.0.0', '1.1.0', '2.0.0', '3.0.0' ] ]
9322 silly addNamed read-pkg@1.1.0
9323 verbose addNamed "1.1.0" is a plain semver version for read-pkg
9324 silly cache afterAdd find-up@1.1.2
9325 verbose afterAdd /home/vagrant/.npm/find-up/1.1.2/package/package.json not in flight; writing
9326 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
9327 verbose afterAdd /home/vagrant/.npm/find-up/1.1.2/package/package.json written
9328 silly cache afterAdd read-pkg@1.1.0
9329 verbose afterAdd /home/vagrant/.npm/read-pkg/1.1.0/package/package.json not in flight; writing
9330 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
9331 verbose afterAdd /home/vagrant/.npm/read-pkg/1.1.0/package/package.json written
9332 silly fetchNamedPackageData pinkie-promise
9333 silly mapToRegistry name pinkie-promise
9334 silly mapToRegistry using default registry
9335 silly mapToRegistry registry https://registry.npmjs.org/
9336 silly mapToRegistry data Result {
9336 silly mapToRegistry   raw: 'pinkie-promise',
9336 silly mapToRegistry   scope: null,
9336 silly mapToRegistry   escapedName: 'pinkie-promise',
9336 silly mapToRegistry   name: 'pinkie-promise',
9336 silly mapToRegistry   rawSpec: '',
9336 silly mapToRegistry   spec: 'latest',
9336 silly mapToRegistry   type: 'tag' }
9337 silly mapToRegistry uri https://registry.npmjs.org/pinkie-promise
9338 verbose request uri https://registry.npmjs.org/pinkie-promise
9339 verbose request no auth needed
9340 info attempt registry request try #1 at 9:06:30 PM
9341 verbose etag "5a512d53-211"
9342 verbose lastModified Sat, 6 Jan 2018 20:10:59 GMT
9343 http request GET https://registry.npmjs.org/pinkie-promise
9344 http 304 https://registry.npmjs.org/pinkie-promise
9345 verbose headers { date: 'Sat, 06 Jan 2018 21:06:30 GMT',
9345 verbose headers   via: '1.1 varnish',
9345 verbose headers   'cache-control': 'max-age=300',
9345 verbose headers   etag: '"5a512d53-211"',
9345 verbose headers   age: '3241',
9345 verbose headers   connection: 'keep-alive',
9345 verbose headers   'x-served-by': 'cache-sin18022-SIN',
9345 verbose headers   'x-cache': 'HIT',
9345 verbose headers   'x-cache-hits': '22',
9345 verbose headers   'x-timer': 'S1515272790.424006,VS0,VE0',
9345 verbose headers   vary: 'Accept-Encoding, Accept' }
9346 silly get cb [ 304,
9346 silly get   { date: 'Sat, 06 Jan 2018 21:06:30 GMT',
9346 silly get     via: '1.1 varnish',
9346 silly get     'cache-control': 'max-age=300',
9346 silly get     etag: '"5a512d53-211"',
9346 silly get     age: '3241',
9346 silly get     connection: 'keep-alive',
9346 silly get     'x-served-by': 'cache-sin18022-SIN',
9346 silly get     'x-cache': 'HIT',
9346 silly get     'x-cache-hits': '22',
9346 silly get     'x-timer': 'S1515272790.424006,VS0,VE0',
9346 silly get     vary: 'Accept-Encoding, Accept' } ]
9347 verbose etag https://registry.npmjs.org/pinkie-promise from cache
9348 verbose get saving pinkie-promise to /home/vagrant/.npm/registry.npmjs.org/pinkie-promise/.cache.json
9349 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
9350 verbose stack TypeError: Cannot convert undefined or null to object
9350 verbose stack     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
9350 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
9350 verbose stack     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
9350 verbose stack     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
9350 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
9350 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
9351 verbose cwd /home/vagrant/code/atchogo/ant-design-pro
9352 error Linux 4.4.0-92-generic
9353 error argv "/usr/bin/node" "/usr/bin/npm" "install"
9354 error node v6.12.0
9355 error npm  v3.10.10
9356 error Cannot convert undefined or null to object
9357 error If you need help, you may report this error at:
9357 error     <https://github.com/npm/npm/issues>
9358 verbose exit [ 1, true ]

**Comment by afc163** [comment]
duplicate #594
