### ISSUE TITLE
🧐[问题] 新建 'AntD v4' 的项目, 左侧菜单栏点击切换时明显延迟

### ISSUE THREAD

**Issue by TianEnPang** [ant-design/ant-design-pro#5950]
### 🧐 问题描述

使用 `yarn create umi` 新建的项目，并选择使用了And Design version 4.

`yarn install` 并运行后，左侧菜单的点击切换明显延迟甚至有时会卡顿。

主要体现在点击后，地址栏地址和Menu Item 的背景颜色切换上。
（可见下图）

@chenshuai2144  麻烦请问如何解决？

### 🚑 其他信息

![demo](https://user-images.githubusercontent.com/32772271/74097010-b3d10980-4b41-11ea-86e2-669af9b61f39.gif)

**Comment by TianEnPang** [comment]
因为切换到“查询表格”的时候会请求表格数据造成的嘛？

**Comment by chenshuai2144** [comment]
https://next.ant.design/components/menu-cn/
antd的动画换了导致的，等 antd 修一下吧

**Comment by TianEnPang** [comment]
> https://next.ant.design/components/menu-cn/
> antd的动画换了导致的，等 antd 修一下吧

OK👌

**Comment by YunSD** [comment]
我想问一下，针对于列表动画加载导致的antd菜单动画异常卡顿，有什么好的解决方法吗
