### ISSUE TITLE
🧐[问题]v4里的form到底是引用@ant-design/compatible还是 antd

### ISSUE THREAD

**Issue by winlj** [ant-design/ant-design-pro#5951]
### 🧐 问题描述
我在看官方文档里面有写antd4里面把form进行了简化，但是我使用antd pro4 umi方式不论是增加模板还是blocks里面的form都是以前未简化的写法，请问是我理解的有错误，还是模板跟blocks还没有升级呢？

### 💻 示例代码
// antd v3
const Demo = ({ form: { getFieldDecorator } }) => (
  <Form>
    <Form.Item>
      {getFieldDecorator('username', {
        rules: [{ required: true }],
      })(<Input />)}
    </Form.Item>
  </Form>
);

const WrappedDemo = Form.create()(Demo);
改成：

// antd v4
const Demo = () => (
  <Form>
    <Form.Item name="username" rules={[{ required: true }]}>
      <Input />
    </Form.Item>
  </Form>
);

const WrappedDemo = Form.create()(Demo);

**Comment by kaoding** [comment]
ant pro正在做升级中。

**Comment by chenshuai2144** [comment]
@winlj  去看 antd@4 分支，里面已经迁移完成

**Comment by winlj** [comment]
> @winlj 去看 antd@4 分支，里面已经迁移完成，期望使用 antd@4 的新版本

我用了那个啦，但是你从资产里获取模板或者block的时候他还是基于v3版本的，得自己手动修改，期待完全适配的v4版本的pro，嗷嗷嗷~~

**Comment by qindj** [comment]
的确，建立出来的antd@4版本的项目，通过UI添加模板，获取的还是之前的，只是会自动加上compatible的依赖，和blocks仓库里的antd@v4分支里的代码不一样，需要手动复制粘贴

**Comment by chenshuai2144** [comment]
@qindj  ui 还需要开发切换分支的功能，现在只能用 master，都是兼容的。

**Comment by qindj** [comment]
@chenshuai2144 明白，不影响使用，就是容易引起误解，大佬辛苦
