### ISSUE TITLE
我在使用v4 antd pro  然后安装 v4的block 就会出现如下的错误 提示不存在

### ISSUE THREAD

**Issue by winlj** [ant-design/ant-design-pro#5954]
PS E:\selfproj\xiaodishu\ant-design-pro> umi block add ant-design-pro/AccountCenter
√ �🔍  Parse url and args
- �🔍  clone git repo from https://gitee.com/umijs/umi-blocks.gitCloning into 'github.com/umijs/umi-blocks'...
/ �🔍  clone git repo from https://gitee.com/umijs/umi-blocks.gitremote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (81/81), done.
| �🚒  clone git repo from https://gitee.com/umijs/umi-blocks.gitremote: Total 2474 (delta 17), reused 2 (delta 0)
Receiving objects: 100% (2474/2474), 2.76 MiB | 651.00 KiB/s, done.
Resolving deltas: 100% (1433/1433), done.
- 🔍🔍  clone g
|🔍🔍  clone git repo from https:///gitee.com/umijs/umi-blocks.git2K
-🔍🔍  clone git repo from https://gitee.com/umijs/umii-blocks.git2K

\ 🔍🔍  c
/🔍🔍  clone git repo from htttps://gitee.com/umijs/umi-blocks.git2K
\🔍🔍  clone git repo from https://gitee.com/umi
| �
-🔍🔍  clone git repo f
|🔍🔍  clone git repo from https://gitee.c
-🔍🔍  clone git repo from https://gitee.com/umijs/umi-blocks
/
\ 🔍🔍  clone gi
√ �🔍  clone git repo from https://gitee.com/umijs/umi-blocks.git
×  error     AssertionError [ERR_ASSERTION]: C:\Users\Administrator\.umi\blocks\github.com\umijs\umi-blocks\ant-design-pro\AccountCenter don't exists 

    at E:\selfproj\xiaodishu\ant-design-pro\node_modules\umi-build-dev\lib\plugins\commands\block\addBlock.js:262:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\selfproj\xiaodishu\ant-design-pro\node_modules\umi-build-dev\lib\plugins\commands\block\addBlock.js:129:103)
    at _next (E:\selfproj\xiaodishu\ant-design-pro\node_modules\umi-build-dev\lib\plugins\commands\block\addBlock.js:131:194)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by yinlianggood** [comment]
同样提示这个错误， 你解决了吗 ？

**Comment by chenshuai2144** [comment]
umi block add AccountCenter 就好了，不用加 ant-design-pro

**Comment by winlj** [comment]
> umi block add AccountCenter 就好了，不用加 ant-design-pro

不好使的，但是我解决了，我的方式是，把blocks的内容都下载提示不存在的那个目录中，就可以了。

**Comment by winlj** [comment]
> 同样提示这个错误， 你解决了吗 ？

不好使的，但是我解决了，我的方式是，把blocks的内容都下载提示不存在的那个目录中，就可以了。
