### ISSUE TITLE
🧐[问题]在服务器请求菜单，返回的图标无法正常显示

### ISSUE THREAD

**Issue by hufengchao** [ant-design/ant-design-pro#5955]
### 🧐 问题描述
在服务器请求菜单后，icon设置为string，呈现的时候无法正常显示

### 💻 示例代码
 [
    {
      "path": "/dashboard",
      "name": "dashboard",
      "icon": "smile",
      "children": [
        {
          "path": "/dashboard/analysis",
          "name": "analysis",
          "icon": "smile",
        },
        {
          "path": "/dashboard/monitor",
          "name": "monitor"
        },
        {
          "path": "/dashboard/workplace",
          "name": "workplace"
        }
      ]
    }
  ] 

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/18630983/74106489-6a64d680-4ba2-11ea-90ff-4e493bccfb69.png)

**Comment by wital** [comment]
同问！

**Comment by luckyli** [comment]
我也出现这个问题了，试了umi-plugin-antd-icon-config，还是无法显示icon

**Comment by antdz** [comment]
同问

**Comment by hufengchao** [comment]
最后我用自定义图标实现的，按照antd pro@4版本要求，不在用传统的

**Comment by uliian** [comment]
同问

**Comment by MaciekBaron** [comment]
English speaker here: I see a warning in the console about something to do with migration, but I cannot find any information about why the icons don't work anymore.

**Comment by wital** [comment]
> 最后我用自定义图标实现的，按照antd pro@4版本要求，不在用传统的

你自定义图标是怎么实现的，烦请贴个代码看看。

**Comment by chenyiliunian** [comment]
我也遇到了同样的问题

**Comment by BanananaDeng** [comment]
同问，有解决的了吗？

**Comment by MaciekBaron** [comment]
同问！

**Comment by hopechans** [comment]
同问！

**Comment by pandaApe** [comment]
The team has provided an example.
https://codesandbox.io/s/xotbp?module=/demo.tsx

@MaciekBaron @all

**Comment by hopechans** [comment]
Demo。https://prolayout.ant.design/menu#%E8%87%AA%E5%AE%9A%E4%B9%89-menu-%E7%9A%84%E5%86%85%E5%AE%B9
