### ISSUE TITLE
v4版本打包部署到springboot后该怎么使用mock数据？

### ISSUE THREAD

**Issue by liuxiawang** [ant-design/ant-design-pro#5957]
通过npm run build之后，将build后是文件放到springboot的resource中，启动boot项目，访问页面时显示接口404，发现好像build时没有把mock数据一起打包，请问能否解决这个问题？该怎么解决？我想要在部署之后能使用mock的数据

**Comment by chenshuai2144** [comment]
暂时没有 java 版本的服务端，你可以将数据代理到我们的官网使用
