### ISSUE TITLE
🐛[BUG] antd@4 登录验证的问题

### ISSUE THREAD

**Issue by daniyyer** [ant-design/ant-design-pro#5958]
### 🐛 bug 描述

react新手，试装了下antd@4 的版本，发现登录的时候如果切换到mobile tab，再切换回account tab，点击登录的时候会验证mobile tab，验证出错，无法登录。
![Kapture 2020-02-11 at 14 20 20](https://user-images.githubusercontent.com/1432045/74214893-207f0c00-4cda-11ea-8ac2-c926d1d93844.gif)

### 🏞 期望结果

与master分支一致，只验证当前tab的表单

### 💻 复现代码

在线版本可以查看这个问题
https://deploy-preview-5948--ant-design-pro.netlify.com/user/login

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by daniyyer** [comment]
感觉是updateActive这个函数没有执行，没有根据type去更新验证的字段列表？

**Comment by chenshuai2144** [comment]
已经修复了，是没有删除表单导致的

**Comment by daniyyer** [comment]
那什么时候能提交更新？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/165e31af75a9cdd364b7e13ad456494647bf8c5c
已经提交了 是分支的问题

**Comment by daniyyer** [comment]
好的，谢谢，昨天看master分支的预览手机登录也有些问题，不知修复没？
