### ISSUE TITLE
登录后权限没有刷新

### ISSUE THREAD

**Issue by ityao** [ant-design/ant-design-pro#596]
使用新版本的登录方式校验权限, 

```
// 非常粗暴的跳转,登陆成功之后权限会变成user或admin,会自动重定向到主页
        // Login success after permission changes to admin or user
        // The refresh will automatically redirect to the home page
        // yield put(routerRedux.push('/'));
       location.reload();
```

debug发现在chrome浏览器location.reload()或者location.reload(true)都无重新调用
utils包里面的authority.getAuthority()方法来重新获取最新权限

**Comment by chenshuai2144** [comment]
啊 还有这事？  authority.getAuthority() 没有调用

**Comment by ityao** [comment]
@chenshuai2144 是呢, 每次登录之后, 还要手动浏览器刷新一下, 才能触发getAuthority()加载权限

**Comment by chenshuai2144** [comment]
@afc163   是不是该引入用户管理了.
还是只做一个简单的redux 来管理用户的权限就行了?

**Comment by ityao** [comment]
能不能做到权限的动态刷新啊, 我感觉登录的时候不应该获取权限回来的, 只记录是否登录成功就行, 权限获取应该在获取user model的fetch里面做, 这样就方便了别的登录方式了

**Comment by chenshuai2144** [comment]
有这个想法.但是现在还没有用户信息界面

**Comment by chenshuai2144** [comment]
fix in #654
