### ISSUE TITLE
🧐[问题] 我想尝试一下antd4.0,但是分支check下来的东西咋和官网上的不太一样呢

### ISSUE THREAD

**Issue by mathcw** [ant-design/ant-design-pro#5961]
### 🧐 问题描述

antd 的table组件有个components 的api 在v4版本里我看官网给的链接
https://github.com/ant-design/ant-design/blob/1c85bb3b6231a01c53c53204846a03c4cfdf41f9/components/table/interface.tsx#L39
定义是
![image](https://user-images.githubusercontent.com/11343266/74208810-151ee700-4cc0-11ea-95f0-ca60017318c5.png)

但是我把pro 4.0的分支下载下来却发现是下图
![image](https://user-images.githubusercontent.com/11343266/74208777-eacd2980-4cbf-11ea-97d1-f4575a9c58a3.png)

是我找错了还是别的问题啊

**Comment by xsp0723** [comment]
It's a good question, and I want to know

**Comment by chenshuai2144** [comment]
create umi is simple，don't have unless file
