### ISSUE TITLE
🧐[问题]移动端真机下部分组件点击后无反应

### ISSUE THREAD

**Issue by TianEnPang** [ant-design/ant-design-pro#5963]
### 🧐 问题描述

- 真机测试 
   - iPhone Safari
   - 排除IOS版本问题

- version : antd@4

- 目前已知出现此问题有：头像组件，语言选择组件【主页和登录页】以下简称“问题组件”

- 描述
   - 第一次点击可能会没有响应，需要点击空白处或者其他组件后再去点击“问题组件”才有反应
   - “问题组件”没反应时需要来回切换点击“问题组件”才会有反应
   - 登录页“语言选择”很难选中，可能是因为上面的问题

- 重现
   - 官方Demo即可重现   

备注
- 
   - Menu点击后没有自动收回 #4649 

如果后续发现相同问题会继续更新......

**Comment by TianEnPang** [comment]
@chenshuai2144 有时间看下，还没找到原因，目前感觉是pc端的hover和移动端的click之间有冲突，造成元素聚焦上面的问题。

**Comment by chenshuai2144** [comment]
提交给antd@4 ？ 不过 antd 的有计划删除hover，改为使用click

**Comment by TianEnPang** [comment]
可能是`Dropdown`造成的，但是antd@4中的`Dropdown`依然是hover，等待更新吧。
