### ISSUE TITLE
预览

### ISSUE THREAD

**Issue by naisuqing** [ant-design/ant-design-pro#5964]
你们官网预览打不开 一直处于加载中 网没问题
![image](https://user-images.githubusercontent.com/40747622/74299201-eb7cc300-4d86-11ea-9ec5-ab4307ad6dc8.png)

**Comment by TianEnPang** [comment]
我这边正常，Windows 10 Pro，Chrome  80.0.3987.100

**Comment by fangmuke** [comment]
![image](https://user-images.githubusercontent.com/26641510/74304639-8e8a0880-4d98-11ea-9dd9-9204f39af408.png)

**Comment by TianEnPang** [comment]
加个梯子？
