### ISSUE TITLE
🧐[问题] v4使用Umi UI 可视化工具添加模版报错（添加区块不会报错）

### ISSUE THREAD

**Issue by yinlianggood** [ant-design/ant-design-pro#5965]
🧐 v4使用Umi UI 可视化工具添加模版报错（**添加区块不会报错**）报错截图如下：

Umi UI可视化工具添加报错：
![image](https://user-images.githubusercontent.com/10203628/74327642-7f6e7f00-4dc7-11ea-9658-ae7d5da0fcfc.png)

![image](https://user-images.githubusercontent.com/10203628/74322896-9c06b900-4dbf-11ea-9356-cc488fcbd38d.png)

使用umi block add 命令添加模块可以成功。

**Comment by yutingzhao1991** [comment]
具体命令贴一下。

**Comment by fangmuke** [comment]
#5924

**Comment by yinlianggood** [comment]
@yutingzhao1991  umi block add 命令添加已经可以添加成功了。

**Comment by chenshuai2144** [comment]
已经修复

**Comment by Tao66** [comment]
还是厉害的，已经解决问题了！
