### ISSUE TITLE
🧐[Question] Will there be any support for antdv4?

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design-pro#5967]
### 🧐 Problem description

in favor of the release of [antd v4](https://github.com/ant-design/ant-design/issues/20661), are you going to add support for v4? because ant design pro is built around antdv3 and needs some tweaks in order for it to work with antv4,
Icons, for example, have changed and the API has changed, etc..

**Comment by chenshuai2144** [comment]
look  https://github.com/ant-design/ant-design-pro/pull/5948
