### ISSUE TITLE
🧐[问题] 1.0 升级到 2.0 之后，文件变更监听目录变了吗？

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design-pro#5968]
### 🧐 问题描述

升级到 2.0 之后，修改 `src/pages` 下面的代码，才会触发 umi 重新编译，修改 `components` 下的代码，**不会** 触发重新编译？

是 umi 的 bug ，还是正常的逻辑就这样？监听目录是否可配置呢？

**Comment by chenshuai2144** [comment]
components 你放到了哪里？
现在 src，mock locale 这些的 CIA会被监听，你可以把 components 放到 src 下面

**Comment by zhangjie2012** [comment]
在 src 目录下.
