### ISSUE TITLE
v4 页面 resize Title丢失🐛[BUG]

### ISSUE THREAD

**Issue by DreFalPoetry** [ant-design/ant-design-pro#5970]
### 🐛 bug 描述

pro v4版本 页面resize的时候 title丢失
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21257916/74406815-936bbc80-4e6b-11ea-9651-6b5bceaf1a88.png)

**Comment by chenshuai2144** [comment]
无法再现，需要什么特殊的操作吗？

**Comment by DreFalPoetry** [comment]
WINDOWS操作系统，CHROME浏览器
1.将导航模式改为顶部菜单布局
2.将页面宽度缩小，至菜单缩起
![image](https://user-images.githubusercontent.com/21257916/75327265-09821180-58b7-11ea-8321-2c8ecc597363.png)
3.再次将页面宽度拉大到正常，title丢失
![image](https://user-images.githubusercontent.com/21257916/75327429-5534bb00-58b7-11ea-9670-d837822e2640.png)

**Comment by DreFalPoetry** [comment]
@ant-design/pro-layout到 5.0.6版本依然不行尝试依旧不行
![image](https://user-images.githubusercontent.com/21257916/76387978-fa18c300-63a2-11ea-9469-2f0d04324955.png)ye'mia页面元素检查 title 消失
