### ISSUE TITLE
🐛[BUG] 4.0版本 高级表单,成员管理 异常

### ISSUE THREAD

**Issue by wlixcc** [ant-design/ant-design-pro#5971]
### 🐛 bug 描述

升级到4.0后高级表单部分无法正常输入数据

### 📷 复现步骤

1. `tyarn create umi`
2. 添加高级表单模块
3.  无法正常输入,数据状态更新异常
4. 查看代码发现在`setState`之前,state已被修改(`src/pages/FormAdvancedForm/components/TableForm.tsx` 204行开始)

             handleFieldChange(e: React.ChangeEvent<HTMLInputElement>, fieldName: string, key: string) {
              const { data = [] } = this.state;
              const newData = [...data];
              const target = this.getRowByKey(key, newData);
              if (target) {
                target[fieldName] = e.target.value;
                //发现这里newData已经为最新数据,导致table不再更新
                console.log('before set state',newData);
                this.setState({ data: newData });
                console.log('after set state',newData);
              }
            }

### 🏞 期望结果

1. 能正常添加与删除行
2. [发现preview中能够正常操作,部署的版本是？](https://preview.pro.ant.design/form/advanced-form)

### © 版本信息

- Ant Design Pro 版本: [ 4.0.0]
- 开发环境 [mac OS]

**Comment by lattemj** [comment]
react已经升级了，我也是才发现state的逻辑和原来this.setState不一样了，建议你看一下新的hooks和生命周期，我现在都还不知道该怎么用state，你解决了告诉一下

**Comment by wlixcc** [comment]
> react已经升级了，我也是才发现state的逻辑和原来this.setState不一样了，建议你看一下新的hooks和生命周期，我现在都还不知道该怎么用state，你解决了告诉一下

我用antd4.0的table重写了,[参考链接](https://ant.design/components/table-cn/#components-table-demo-edit-row)
