### ISSUE TITLE
🧐[问题]像vue的keep-alive一样的页面缓存功能要怎么做？

### ISSUE THREAD

**Issue by Gdevil** [ant-design/ant-design-pro#5972]
### 🧐 问题描述

#####需求：
列表页有搜索、筛选、分页等功能，从列表页点击进入详情页后，再返回列表页，这时列表页的状态都会被刷新；
我想要实现跟vue中的keep-alive标签一样的功能，详情页返回列表页，列表页不会刷新。哪位大神能教教小弟

**Comment by 729993031** [comment]
你可以看一下umi-hooks这个包 他有提供这个功能 他的原理也很简单就是在生命周期结束的时候存储一下数据，回退的时候重新渲染

**Comment by MinJieLiu** [comment]
@Gdevil 
https://codesandbox.io/s/umi-activation-demo-with-tab-zxz84

这个是 Umi@2.x 的例子，3.x 的我没用插件了。

**Comment by chenshuai2144** [comment]
umi@3 将会支持
