### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by anihy** [ant-design/ant-design-pro#5974]
### 🐛 bug 描述

无法添加区块和模板

### 📷 复现步骤

1.yarn create umi
2.select ant-design-pro
3.git init
4.cnpm install
5.npm run

### 💻 复现代码
添加模板时报错

⚓  Start git fetch
fatal: Not a git repository (or any of the parent directories): .git
⚓  Start git fetch
fatal: Not a git repository (or any of the parent directories): .git
Faild git fetch: Command failed: git fetch
undefined
undefined

🚧  Execute task error: Error: Command failed: git fetch
undefined
undefined
⚓  Start git fetch
fatal: Not a git repository (or any of the parent directories): .git
Faild git fetch: Command failed: git fetch
undefined
undefined

🚧  Execute task error: Error: Command failed: git fetch
undefined
undefined

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本  2.8.1
- 浏览器环境 chrome
- 开发环境 [win7]

### 🚑 其他信息

 git version 2.10.2.windows.1

**Comment by chenshuai2144** [comment]
执行 umi block clear ，最好不要使用 cnpm ，与 npm 不兼容，可以使用 tyarn
