### ISSUE TITLE
如何开发多应用的后台管理系统？

### ISSUE THREAD

**Issue by hegphegp** [ant-design/ant-design-pro#5975]
### 如何开发多应用的后台管理系统？
* 现在想把多个应用集成到同一个后台管理页面，有什么简洁的方法，类似于这么效果图
![image](https://user-images.githubusercontent.com/26202719/74590709-ad63f580-504b-11ea-97e8-8b489d12dfa1.png)

![image](https://user-images.githubusercontent.com/26202719/74590735-fd42bc80-504b-11ea-84a0-7abfbe569b57.png)

**Comment by afc163** [comment]
https://github.com/umijs/qiankun

**Comment by fangmuke** [comment]
layuimini是利用css改变菜单的隐藏显示。

antd-pro可以用以下两种方式：
1️⃣ 使用dva dispatch+umi-request从后端请求menuData进行渲染。

2️⃣ 使用乾坤https://qiankun.umijs.org

根据你所描述的，我推荐使用第一种。
