### ISSUE TITLE
🧐[问题]顶部菜单布局模式下顶部不同类型菜单高度不一致

### ISSUE THREAD

**Issue by QiangGuZi** [ant-design/ant-design-pro#5976]
### 🧐 问题描述
antdPro导航模式：顶部菜单布局
一级标题和含子菜单的二（多）级标题高度不一致

个人页是含子菜单的标题，其他三个是一级标题
图片：
![image](https://user-images.githubusercontent.com/42662849/74597589-d19bf280-509c-11ea-849c-b478c94210af.png)

这种样式问题不确定是设计如此还是说不小心，希望得到准确答复

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis?layout=topmenu&contentWidth=Fixed
这里是一样的，来个复现环境？

**Comment by QiangGuZi** [comment]
@chenshuai2144 可能是我没描述清楚，我尝试再次描述一遍
在antdpro的预览里，所有的menu都含有子menu，所以表现是一致的。
但是当一个menu没有子menu的时候，它就与其他有子menu的高度表现不一致了

我刚刚重新创建了一个工程又测试了一遍，流程如下，成功复现

1.创建工程，选择如下
![image](https://user-images.githubusercontent.com/42662849/74605852-a352fd00-5106-11ea-99ce-4dbee3b63aff.png)
2.修改导航布局
![image](https://user-images.githubusercontent.com/42662849/74605874-c41b5280-5106-11ea-8d6f-4f185446a43f.png)
3.修改路由，红框内为添加部分
![image](https://user-images.githubusercontent.com/42662849/74605883-dc8b6d00-5106-11ea-9a47-06c4821fc235.png)

4.复现，误差在1（2）个像素，
![image](https://user-images.githubusercontent.com/42662849/74605944-4dcb2000-5107-11ea-9833-4d68d8f62378.png)


5.我觉得问题出在下图红框部分
![image](https://user-images.githubusercontent.com/42662849/74605914-207e7200-5107-11ea-9e14-81ee95c6924d.png)

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by QiangGuZi** [comment]
@chenshuai2144 
1

**Comment by chenshuai2144** [comment]
我试了试，不会这样。是不是要升级一下？
