### ISSUE TITLE
🧐[问题]如何使用Dispatch方法获取动态菜单

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#5977]
### 🧐 问题描述
如何使用Dispatch方法获取动态菜单，可以给个demo 么

**Comment by antdz** [comment]
你好，我最近也在研究，刚写一篇[动态菜单](https://blog.csdn.net/antdz/article/details/104369471)。刚刚接触typescript，希望能帮助你。

**Comment by hihuangwei** [comment]
> 你好，我最近也在研究，刚写一篇[动态菜单](https://blog.csdn.net/antdz/article/details/104369471)。刚刚接触typescript，希望能帮助你。

谢谢！用你的方法可以实现，但是图标不显示，我是"antd": "^4.0.0-rc.5","@ant-design/pro-layout": "^5.0.2"

**Comment by chenshuai2144** [comment]
@hihuangwei  📈不显示还在想办法，插件还不支持从服务器请求回来的 icon

**Comment by BanananaDeng** [comment]
> 
> 
> @hihuangwei 📈不显示还在想办法，插件还不支持从服务器请求回来的 icon

请问想到办法了吗？同样遇到请求回来的菜单icon不显示的问题。

**Comment by lattemj** [comment]
个人觉得，前后端分离就要考虑鉴权，鉴权了每次请求是不是就需要带上角色别名之类的？，这样ant design pro里就使用官方的方法，不需要完整的从服务端读取json的菜单了，我两种都弄过，服务端获取菜单有可能整个数据架构要重写，性价比不高。用官方的方法只需要实现request时带token，response时返回authority个人觉得优雅点，也方便后续升级，我从V2到V4，只要有更新，会很崩溃。

**Comment by UchihaItachi6** [comment]
js获取动态菜单我会，ts我不会，你需要代码吗

**Comment by UchihaItachi6** [comment]
111
