### ISSUE TITLE
🧐[问题]如何在设置全局样式处加上设置字体大小，可动态改变font-size-base大小生效？

### ISSUE THREAD

**Issue by pollyZhai2018** [ant-design/ant-design-pro#5979]
### 🧐 问题描述
 
如何在设置全局样式处加上设置字体大小，可动态改变font-size-base大小生效？
 
setting.js中window.less.modifyVars({
         'primary-color':primaryColor,
         'font-size-base':'18px'
})

如何让这个font-size-base=18px  这个 全局less变量生效？？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/19606d7d6f102847954ab9c68d8e9f172810db83/config/config.ts#L150
看这里，直接写变量就好了
