### ISSUE TITLE
🐛[BUG]无法通过自定义的主题less，来覆盖antd的变量（e.g. @primary-color）

### ISSUE THREAD

**Issue by Atuna** [ant-design/ant-design-pro#5980]
### 🐛 bug 描述

参考了https://github.com/ant-design/ant-design/issues/1793
在global.less里写入了：
```
@import "~antd/lib/style/themes/default.less";
@primary-color: red;
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
```
但主题色还是默认的

### © 版本信息

- Ant Design Pro 版本: 2.2.1
- umi 版本 2.8.20
- 浏览器环境 Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
直接通用 config.js 的 theme 来吧，gobal.less 会被覆盖掉
