### ISSUE TITLE
🧐[问题]如何使用real server

### ISSUE THREAD

**Issue by shanhsuatgmaildotcom** [ant-design/ant-design-pro#5982]
### 🧐 问题描述
如何使用real server

我把mock/notice.js裡的api/notices: 改成http://x.x.x.x/getNotices。網頁上會顯示:TypeError: notices.map is not a function。
#5981 面## 💻 示例代码

### 🚑 其他信息

<img width="1210" alt="截圖 2020-02-17 下午8 12 22" src="https://user-images.githubusercontent.com/2858032/74652834-e2925400-51c1-11ea-86c2-ed9007cce4bf.png">

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/mock-api-cn#%E8%81%94%E8%B0%83
https://pro.ant.design/blog/proxy-cn#%E5%9C%A8%E5%BC%80%E5%8F%91%E4%B8%AD%E4%BD%BF%E7%94%A8
可以看这两篇
