### ISSUE TITLE
🐛[BUG] 登录页面出现错误_form.default.create(...) is not a function

### ISSUE THREAD

**Issue by hegphegp** [ant-design/ant-design-pro#5983]
### 🐛 bug 描述

* 用 `yarn create umi` 创建项目 和 `npm run fetch:blocks` 获取所有区块后，刷新登录页出现报错
```
Unhandled Rejection (TypeError): _form.default.create(...) is not a function
./src/pages/user/login/components/Login/index.tsx
src/pages/user/login/components/Login/index.tsx:164
```

### 📷 复现步骤

umi安装antd pro后再运行`npm run fetch:blocks`与`npm start`，打开页面后再退出登录，接着刷新

### 🏞 期望结果

与初始安装后一样的正常登录页

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本[2.13.3]
- 浏览器环境 [chrome]
- 开发环境 [Ubuntu]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26202719/74706327-90990f00-5251-11ea-9546-60db6e080e4f.png)

* 我参照了 `https://github.com/ant-design/ant-design-pro/issues/5928 `这个安装了  @ant-design/compatible ，还是有问题
* 我的解决方法是：`git clone项目`，然后`npm run fetch:blocks`，把git clone项目的package.json覆盖了`yarn ceate umi`的package.json，项目成功运行，打开登录页不怕错
```
git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project
cd my-project
npm run fetch:blocks
# 最后把git clone项目的package.json覆盖 `yarn ceate umi` 项目的package.json
```

**Comment by chenshuai2144** [comment]
重新安装依赖就好了，你这个应该是antd的版本没有升级导致的

**Comment by 3463135482** [comment]
> 重新安装依赖就好了，你这个应该是antd的版本没有升级导致的

我也碰到一样的问题，重新安装依赖，也没有解决

**Comment by 3463135482** [comment]
> ### 🐛 bug 描述
> * 用 `yarn create umi` 创建项目 和 `npm run fetch:blocks` 获取所有区块后，刷新登录页出现报错。当前时间是 2020-02-18号，但是我在一个星期前，用`yarn create umi` 创建项目 和 `npm run fetch:blocks` 却是可以的
> 
> ```
> Unhandled Rejection (TypeError): _form.default.create(...) is not a function
> ./src/pages/user/login/components/Login/index.tsx
> src/pages/user/login/components/Login/index.tsx:164
> ```
> 
> ### 📷 复现步骤
> umi安装antd pro后再运行`npm run fetch:blocks`与`npm start`，打开页面后再退出登录，接着刷新
> 
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 4.0.0]
> * umi 版本[2.13.3]
> * 浏览器环境 [chrome]
> * 开发环境 [Ubuntu]
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/26202719/74706327-90990f00-5251-11ea-9546-60db6e080e4f.png)
> 
> * 我参照了 `https://github.com/ant-design/ant-design-pro/issues/5928 `这个安装了  @ant-design/compatible ，还是有问题
> * 我的即将方法是，git clone ant-design-pro项目下来，然后`npm run fetch:blocks` ，把该项目的package.json文件拷贝到 `yarn create umi` 创建项目，可以运行
> 
> ```
> git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project
> cd my-project
> npm install --verbose
> npm run fetch:blocks
> # 然后把package.json文件拷贝到yarn create ymi创建的项目，就可了
> ```

好的package.json能贴出来看看吗？

**Comment by yykoypj** [comment]
umi create之后的package.json里面的命令长这样
```
"fetch:blocks": "pro fetch-blocks --branch antd@4 && npm run prettier",
```
branch参数是antd@4，下面是pro-cli里面的下载命令
```
      const cmd = [
        `umi block add https://github.com/ant-design/pro-blocks/tree/master/${gitPath}`,
        `--path=${item.path}`,
        '--skip-dependencies',
        `--branch=${arg.branch || 'master'}`,
      ];
```

问题是我在[pro-blocks](https://github.com/ant-design/pro-blocks)里面并没有见到这个分支
把这个branch参数删除，或者改成master就好了
