### ISSUE TITLE
vs code报stylelint: Undefined rule unicode-bom🐛[BUG]

### ISSUE THREAD

**Issue by AimLuo** [ant-design/ant-design-pro#5984]
### 🐛 bug 描述

vs code装[stylelint-plus](https://marketplace.visualstudio.com/items?itemName=hex-ci.stylelint-plus)扩展，vs code错误提示：stylelint：Undefined rule unicode-bom

### © 版本信息

- Ant Design Pro 版本: yarn create umi创建的最新版
- 开发环境: window10 1909
- vs  code: 1.42.1
- stylelint-plus : 最新

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21124342/74710978-d360e400-525d-11ea-9fa5-928dc494d41b.png)

**Comment by iwyvi** [comment]
`unicode-bom` 规则需要 `stylelint >=11` ，而 `stylelint-plus` 扩展使用的是内置 `stylelint` ，版本是 `^10.1.0` ，因此会报错。

这个规则的引入目前来看是因为 `@umijs/fabric` 在 2月6日更新了一波 `stylelint` 基础规则依赖。

https://github.com/umijs/fabric/commit/0da833f28bba1d6547c0a6cca58bcd76e969d4cc

目测是这个配置引入的

https://github.com/prettier/stylelint-config-prettier/issues/49

我现在换了 [stylelint.vscode-stylelint](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) 这个扩展可以正常使用

**Comment by chenshuai2144** [comment]
楼上正解

**Comment by AimLuo** [comment]
没有保存时自动修复功能。不过提供了命令修复。

**Comment by AimLuo** [comment]
> 没有保存时自动修复功能。不过提供了命令修复。

原来使用了vs code新版的自动格式化功能
```json
"editor.codeActionsOnSave" : {
   "source.fixAll.stylelint":true
}
```
