### ISSUE TITLE
🐛[BUG] v4 preview site-列表页-标准列表 点击添加时Modal的title为'编辑'

### ISSUE THREAD

**Issue by joriewong** [ant-design/ant-design-pro#5986]
### 🐛 bug 描述

v4 preview site-列表页-标准列表 点击添加时Modal的title为'编辑'

### 🏞 期望结果

v2的写法是正确的

https://github.com/ant-design/v2.preview.pro.ant.design/blob/v2/src/pages/List/BasicList.js

我pr的写法也能实现正确的效果

https://github.com/ant-design/pro-blocks/pull/188

### 💻 复现代码

current 默认为 {}

https://github.com/ant-design/pro-blocks/blob/master/ListBasicList/src/index.tsx

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/11408040/74819767-db8f5100-533b-11ea-8936-35d4d05c5aa7.png)

**Comment by chenshuai2144** [comment]
来个pr？
