### ISSUE TITLE
🧐[问题]ie11下显示白屏

### ISSUE THREAD

**Issue by sbhouchen** [ant-design/ant-design-pro#5992]
### 🧐 问题描述
v4的ts版本，下载了所有模块，去掉代码分割，build之后在ie下显示白屏

ie会报语法错误
![image](https://user-images.githubusercontent.com/26555772/74998584-186e5b80-5494-11ea-88a1-a35e999e72df.png)
![image](https://user-images.githubusercontent.com/26555772/74998601-20c69680-5494-11ea-8067-6abba0b15155.png)

注释掉关于这两个组建后，在ie下可以正常显示
![image](https://user-images.githubusercontent.com/26555772/74998828-bbbf7080-5494-11ea-9ed1-2a39c8a6a3e1.png)

**Comment by chenshuai2144** [comment]
看一下 pro 的官网，我们是支持在 ie11 下使用的。
