### ISSUE TITLE
🐛Is AuthorizedRoutePops actually AuthorizedRouteProps

### ISSUE THREAD

**Issue by JackDan9** [ant-design/ant-design-pro#5993]
### 🐛 Is AuthorizedRoutePops actually AuthorizedRouteProps

[https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/AuthorizedRoute.tsx](https://github.com/ant-design/ant-design-pro/blob/master/src/components/Authorized/AuthorizedRoute.tsx)

 Is AuthorizedRoutePops actually AuthorizedRouteProps

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本: ^2.13.0
- 浏览器环境: Google Chrome
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
will remove in v5
