### ISSUE TITLE
🧐[问题]ProTable 组件 合并单元格怎么做？ 按antd官网使用render 返回值会报错

### ISSUE THREAD

**Issue by hanwensheng666** [ant-design/ant-design-pro#5994]
### 🧐 问题描述

ProTable 组件 合并单元格怎么做？ 按antd官网使用render 返回值会报错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/34360878/75000253-ca0f8b80-5498-11ea-9394-c5c8a8671bf6.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-table/issues/158
看这里
