### ISSUE TITLE
🐛[BUG]高级表单-成员管理-编辑-输入框无法输入

### ISSUE THREAD

**Issue by 691091849** [ant-design/ant-design-pro#5995]
### 🐛 bug 描述
使用JavaScript类型，使用npm run fetch:blocks安装所有区块后，启动项目，在表单页-高级表单-成员管理处，点击编辑，展示的如成员姓名等输入框中，无法输入，（输入后输入框不变化）

### 📷 复现步骤
执行如下步骤：
1：npm create umi创建项目，选择JavaScript类型
2：npm install
3: npm run fetch:blocks
4，npm start
5,项目启动后，点击表单页-高级表单，在页面成员管理处，点击编辑，在展示出的输入框输入字符，即可发现输入框没有任何变化

### 🏞 期望结果
输入框输入后会显示相应的输入字符

### 💻 复现代码
[advanced-form.zip](https://github.com/ant-design/ant-design-pro/files/4234091/advanced-form.zip)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![TIM截图20200221111619](https://user-images.githubusercontent.com/56719502/75001186-a6017980-549b-11ea-9e04-b9b58fc7108a.png)

**Comment by afc163** [comment]
啥也没写。

**Comment by 691091849** [comment]
> 啥也没写。

不好意思，写到注释里了，刚改了下

**Comment by chenshuai2144** [comment]
试了一下不会的。
