### ISSUE TITLE
关于页面滚动

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#60]
1.在PC web下，左侧菜单栏会跟随页面滚动，理想情况下，左侧菜单栏是固定不动的。
2.在手机端下，左侧菜单栏固定，右侧内容页使用的是浏览器自带的滚动，滚动起来比较卡，是不是可以考虑使用transform: translate来进行滚动呢。

**Comment by afc163** [comment]
1. Trace #43
2. 我们暂时不会针对手机端做过多的优化，毕竟这主要是面向桌面端的应用场景。

感谢反馈。
