### ISSUE TITLE
🧐antdpro 的Dva 怎么配置react-persist 数据持久化

### ISSUE THREAD

**Issue by 986244073** [ant-design/ant-design-pro#6001]
antdpro 的Dva 怎么配置react-persist

**Comment by yezongyang** [comment]
// app.js文件
import { persistStore, persistReducer } from 'redux-persist';
import storageSession from 'redux-persist/lib/storage/session';

export const dva = {
  config: {
    onError(e) {
      e.preventDefault();
    },
    onReducer(reducer) {
      const persistConfig = {
        key: 'root',
        storage: storageSession,
        whitelist: ['global']
      };
      return persistReducer(persistConfig, reducer);
    }
  }
};

window.addEventListener('DOMContentLoaded', () => {
  /* eslint-disable no-underscore-dangle */
  persistStore(window.g_app._store);
});

**Comment by liuhong1happy** [comment]
没有找到app.js 啊

**Comment by yezongyang** [comment]
```
import { getDvaApp } from 'umi'
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

export const dva = {
  config: {
    onError(e) {
      e.preventDefault()
    },
    onReducer(reducer) {
      const persistConfig = {
        key: 'root',
        storage,
        whitelist: ['global']
      }
      return persistReducer(persistConfig, reducer)
    }
  }
}

window.addEventListener('DOMContentLoaded', () => {
  const app = getDvaApp()
  // eslint-disable-next-line no-underscore-dangle
  persistStore(app._store)
})
```

**Comment by ykmind** [comment]
umi3 我这样配置在app.ts中没有效果, 我甚至放到了app.tsx中也没起作用

**Comment by Heqingsong** [comment]
@ykmind 请问这个问题你解决了吗？

**Comment by ykmind** [comment]
> @ykmind 请问这个问题你解决了吗？

no🤣

**Comment by QShengW** [comment]
我也想知道

**Comment by wxf-start** [comment]
有人解决吗？？

**Comment by LiuJiangshan** [comment]
https://github.com/umijs/umi/issues/249

**Comment by gengkeke** [comment]
umi3 antdpro v5   getDvaApp() null
