### ISSUE TITLE
🧐[问题] v4 修改 primaryColor 无效

### ISSUE THREAD

**Issue by yinlianggood** [ant-design/ant-design-pro#6002]
### 🧐 问题描述
config/defaultSettings.ts 修改primaryColor参数无效，还是默认的蓝色（修改其它的参数都是正常的）。
![image](https://user-images.githubusercontent.com/10203628/75103514-64590600-5636-11ea-8c76-23f408f0dab9.png)

**Comment by afc163** [comment]
@chenshuai2144 看，这种需求是很多的，需要修复。

**Comment by chenshuai2144** [comment]
没有默认赋值上去，我赋值一下

**Comment by hydRAnger** [comment]
@afc163 @chenshuai2144 

确定这个有fix吗？今天试了一下，还是无法修改primaryColor，无论直接修改defaultSettings.ts还是config.ts

按照[文档](https://pro.ant.design/docs/getting-started-cn#%E5%AE%89%E8%A3%85)使用`yarn create umi`进行初始化，umi版本：2.13.0

需要reopen issue吗？
