### ISSUE TITLE
初始化项目的时候，运行npm install报错

### ISSUE THREAD

**Issue by insistenceZHUO** [ant-design/ant-design-pro#6008]
环境：node v11.14.0。npm 6.7.0 操作系统win7.
报错信息如下：
第一个报错信息：
npm ERR! path H:\asto\erp-antd\node_modules\.staging\antd-3bc4a160\dist\antd-with-locales.min.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'H:\asto\erp-antd\node_modules\.staging\antd-3bc4a160\dist\antd-with-locales.min.js'
npm ERR!  { [OperationalError: EPERM: operation not permitted, unlink 'H:\asto\erp-antd\node_modules\.staging\antd-3bc4a160\dist\antd-with-locales.min.js']
npm ERR!   cause:
npm ERR!    { [Error: EPERM: operation not permitted, unlink 'H:\asto\erp-antd\node_modules\.staging\antd-3bc4a160\dist\antd-with-locales.min.js']
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'H:\\asto\\erp-antd\\node_modules\\.staging\\antd-3bc4a160\\dist\\antd-with-locales.min.js' },
npm ERR!   stack:
npm ERR!    "Error: EPERM: operation not permitted, unlink 'H:\\asto\\erp-antd\\node_modules\\.staging\\antd-3bc4a160\\dist\\antd-with-locales.min.js'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'H:\\asto\\erp-antd\\node_modules\\.staging\\antd-3bc4a160\\dist\\antd-with-locales.min.js',
npm ERR!   parent: 'umi-plugin-react' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

第二个报错信息：
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-02-24T13_08_00_463Z-debug.log

**Comment by chenshuai2144** [comment]
```
npm ERR! Error: EPERM: operation not permitted, unlink 'H:\asto\erp-antd\node_modules.staging\antd-3bc4a160\dist\antd-with-locales.min.js'
```
看这里

**Comment by goto217** [comment]
@chenshuai2144 @insistenceZHUO 具体如何解决的， 能详细说明一下吗

**Comment by chenshuai2144** [comment]
是一个权限问题，清空一下缓存即可

**Comment by tjpanda88** [comment]
以管理员形式运行cmd
npm cache clean --force
npm install
