### ISSUE TITLE
🐛[BUG] router配置会因为path的匹配问题，前缀相同会导致菜单切换的时候高亮失效

### ISSUE THREAD

**Issue by JasLin** [ant-design/ant-design-pro#6009]
### 🐛 bug 描述

router配置会因为path的匹配问题，前缀相同会导致菜单切换的时候高亮失效

### 📷 复现步骤

用umi 可视化工具添加两个“空白页面”的模板，点击 左边菜单不同的“空白页面”，菜单的item高亮应该切换，实际情况没有。

经过看router的配置，发现如果两个path的前缀相同，则会有这个问题,如router里面有这样两个path:

```js
{
  name: '...',
  icon: '...',
  path: '/abcd'
  component: '...'
},
{
  name: '...',
  icon: '...',
  path: '/abc',
  component: '...',
},
```
那么菜单切换时候高亮没有跟随变化(但是实际路由是变了-页面内容会改变)

但是如果上面的配置，把顺序调换一下，则一切正常：

```js
{
  name: '...',
  icon: '...',
  path: '/abc'
  component: '...'
},
{
  name: '...',
  icon: '...',
  path: '/abcd',
  component: '...',
},
```

先配置/abc，然后配置/abcd，那么一切ok

没去看菜单渲染的代码，估计遍历处理的算法有问题。

### 🏞 期望结果

用umi 可视化工具添加两个“空白页面”的模板，点击 左边菜单不同的“空白页面”，菜单的item高亮应该切换，实际情况没有。 

### 💻 复现代码

```js
{
  name: '空白页面',
  icon: 'smile',
  path: '/emptypagetwo',
  component: './EmptyPageTwo',
},
{
  name: '空白页面',
  icon: 'smile',
  path: '/emptypage',
  component: './EmptyPage',
},             
```

### © 版本信息

- Ant Design Pro 版本: 4.0.0-rc.5
- umi 版本 mi@2.13.3
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
现在用了贪婪模式，这两个被匹配了，应该修改一下正则

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/333

看这里

**Comment by JasLin** [comment]
umi 可视化工具里默认行为还有这个问题存在，建议判断一下，这种情况加入正则（否则可视化工具一致会有人碰到这个问题）。另外 在文档里面也提一下这种特殊情况
