### ISSUE TITLE
切换列表页 查询表格和标准表格菜单时 用性能工具查看出现 (Committing Changes) Warning: Lifecycle hook scheduled a cascading update

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design-pro#601]
![image](https://user-images.githubusercontent.com/12318131/34649078-720cbae8-f3e2-11e7-9b95-0dd70c873c90.png)

**Comment by Nokecy** [comment]
菜单切换可以明显感觉到卡顿，有一点点，随着数量增多，卡顿更加明显

**Comment by caixmi** [comment]
请问你这个后来是怎么解决的？我查找了一些资料后还是没有比较好的想法[](https://github.com/reduxjs/react-redux/issues/834)

**Comment by caixmi** [comment]
请问你这个后来是怎么解决的？我查找了一些资料后还是没有比较好的想法[https://github.com/reduxjs/react-redux/issues/834](url)

**Comment by caixmi** [comment]
@Nokecy 请问你这个后来是怎么解决的？我查找了一些资料后还是没有比较好的想法。[https://github.com/reduxjs/react-redux/issues/834](url)

**Comment by ke1vin1993** [comment]
@caixmi 估计是componentDidUpdate里setState了
