### ISSUE TITLE
🧐[问题]如何根据屏幕宽度大小，自动收起或展开菜单栏

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6010]
### 🧐 问题描述
如何更具屏幕大小，自动收起或展开菜单栏

**Comment by chenshuai2144** [comment]
这个在 pro-layout 已经有配置。如果你有调节阈值的需求。

breakpoint | breakpoints of the responsive layout | Enum { 'xs', 'sm', 'md', 'lg', 'xl', 'xxl' } | lg
-- | -- | -- | --


可以试试这个 api

**Comment by zoeykk** [comment]
在v5里app.tsx中的layout中设置breakpoint: 'xl' 不起作用
