### ISSUE TITLE
🐛[BUG] 无法通过配置进行主题色修改

### ISSUE THREAD

**Issue by hydRAnger** [ant-design/ant-design-pro#6014]
### 🐛 bug 描述
参考：https://github.com/ant-design/ant-design-pro/issues/6002

今天试了一下，还是无法修改primaryColor，无论直接修改defaultSettings.ts还是config.ts

### 📷 复现步骤

按照[文档](https://pro.ant.design/docs/getting-started-cn#%E5%AE%89%E8%A3%85)使用`yarn create umi`进行初始化，umi版本：2.13.0

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] latest
- umi 版本：2.13.0
- 浏览器环境：Chrome 80.0.3987.116 
- 开发环境 mac OS

**Comment by afc163** [comment]
按照 https://github.com/ant-design/ant-design-pro/commit/4c9aa880042c3bbfe9f4a725ea6325b21313ff3f 修改了吗？

**Comment by hydRAnger** [comment]
@afc163 

现在使用`npm create umi`进行初始化得到的是：

```
  theme: {
    // ...darkTheme,
    primaryColor: defaultSettings.primaryColor,
  }
```

和https://github.com/ant-design/ant-design-pro/commit/4c9aa880042c3bbfe9f4a725ea6325b21313ff3f 是一样的吧

**Comment by l745230** [comment]
@hydRAnger 我是直接在config theme.ts里设置.
// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

const theme = {
  'primary-color': '#F5222D', // 薄暮红
  'border-radius-base': '4px', // V4升级基础圆角调整，由4px 改为 2px
};

export default theme;

default.less里覆盖的变量名是primary-color,不是驼峰写法.
