### ISSUE TITLE
🧐[问题]v4版本添加模板编译时报错

### ISSUE THREAD

**Issue by KJohn2q** [ant-design/ant-design-pro#6015]
### 🧐 问题描述

使用umi可视化工具添加模板页面成功，编译时报错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20499046/75303831-cf941980-587c-11ea-8105-ad917ec11383.png)

**Comment by KJohn2q** [comment]
项目目录为全小写并没有出现这样的问题，项目目录必须小写吗

**Comment by chenshuai2144** [comment]
你估计大小写写错了。
可以尝试打开 git  的大小写敏感
