### ISSUE TITLE
🧐[问题]怎样使用站内信组件？

### ISSUE THREAD

**Issue by KJohn2q** [ant-design/ant-design-pro#6016]
### 🧐 问题描述

怎样使用站内信组件？有站内信相关的区块吗？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20499046/75322375-90ca8780-58ad-11ea-8f2e-8d93cfd1ec86.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/tree/antd%404/src/components/NoticeIcon

是这个组件，把他加载在
https://github.com/ant-design/ant-design-pro/blob/antd%404/src/components/GlobalHeader/RightContent.tsx
即可

**Comment by KJohn2q** [comment]
能给下具体的加载示例吗
