### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by chris-js** [ant-design/ant-design-pro#6018]
![photo_2020-02-26_18-45-26](https://user-images.githubusercontent.com/54987011/75337567-30950f00-58c8-11ea-924b-da11969d3b1b.jpg)
 

很奇怪 我不管在哪个页面引入 import {  Icon } from 'antd';     使用<Icon type="alert" />  都是报这个警告 ，而且图标也不展示，V4版本里面全都没用icon 组件，无法参考 ，
 import { QuestionCircleOutlined } from '@ant-design/icons';   中 QuestionCircleOutlined 又是从哪来的呢

**Comment by chenshuai2144** [comment]
v4 需要从 @ant-design/icons 中引入

使用方式如下
```tsx
import { StepForwardOutlined } from '@ant-design/icons';

<StepForwardOutlined />
```
