### ISSUE TITLE
V4 版本，ListTableList示例中UpdateForm values为空🧐[问题]

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design-pro#6019]
### 🧐 问题描述

ListTableList示例中UpdateForm组件定义了values属性来接收需要编辑的数据，实际使用发现UpdateForm中“const [formValues, setFormValues] = useState..........”的"formValues"一直为空，是因为我在定义了这样"Id?: string;"的属性原因？还是别的问题？props.values可以接收值。

### 💻 示例代码

目前弃用“const [formValues, setFormValues] = useState......”，直接"<Form initialValues={ Id: props.values.Id } ....."，这样的方式可以获取数据，同时也可以编辑。

**Comment by chenshuai2144** [comment]
formValues 这个东西不是受控的，initialValues 才是正解
