### ISSUE TITLE
 "TableForm.js"75行，为什么这么改变state?

### ISSUE THREAD

**Issue by sunplum123** [ant-design/ant-design-pro#602]
[TableForm.js](https://github.com/ant-design/ant-design-pro/blob/master/src/routes/Forms/TableForm.js)

谁能解释一下这个例子中75行为什么要这么改变state？
`target[fieldname] = e.target.value`
官方文档不是说不能直接改state吗？
新手。。。

**Comment by afc163** [comment]
严格的说是不应该直接改，感谢反馈。
