### ISSUE TITLE
🐛[BUG]从服务器请求菜单设置icon图标无效

### ISSUE THREAD

**Issue by bushuocao** [ant-design/ant-design-pro#6024]
### 🐛 bug 描述
从服务器请求菜单设置icon图标无效

![image](https://user-images.githubusercontent.com/49134598/75414502-b74afa00-5963-11ea-95d2-44df016afcf2.png)

### 📷 复现步骤
你可以在 src/layouts/BasicLayout.tsx 中修改 menuDataRender。
menuData 数据格式中添加icon后，无法显示图标。只能显示图标代码

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Clago** [comment]
[https://github.com/ant-design/ant-design-pro-layout/issues/338](url)
我也遇到这个问题了，手动替换Icon后页面会卡死崩溃，现在我暂时把icon置为空了，也不知道后续会不会修复。

**Comment by DAOLIDEWONIU** [comment]
通过这个插件可以解决：umi-plugin-antd-icon-config

**Comment by Clago** [comment]
> 通过这个插件可以解决：umi-plugin-antd-icon-config

本地路由可以。动态菜单不行。

**Comment by heyepeng** [comment]
> > 通过这个插件可以解决：umi-plugin-antd-icon-config
> 
> 本地路由可以。动态菜单不行。
我的方法，在菜单返回一个自定义属性iconName,用antdd自定义图标，取值，重新render成icon元素

`import { createFromIconfontCN } from '@ant-design/icons';`

`const IconFont = createFromIconfontCN({scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js',});`

属性里面
`menuItemRender={(menuItemProps, defaultDom) => {
          const { props: { children } } = defaultDom;
          const {iconName} = menuItemProps;
          const iconDom = <IconFont type={iconName} />;
          if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) {
            return defaultDom;
          }
          return <Link to={menuItemProps.path}>{iconDom}{defaultDom}</Link>;
        }}`

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon
专门写了个 demo，可以看看

**Comment by dealdot** [comment]
ProLayout添加以下函数即可解决，Link之间返回的是  {defaultDom}

menuItemRender={(menuItemProps, defaultDom) => {
       return <Link to={menuItemProps.path}>{defaultDom}</Link>;
}}

**Comment by 1998729** [comment]
> > > 通过这个插件可以解决：umi-plugin-antd-icon-config
> > 
> > 
> > 本地路由可以。动态菜单不行。
> > 我的方法，在菜单返回一个自定义属性iconName,用antdd自定义图标，取值，重新render成icon元素
> 
> `import { createFromIconfontCN } from '@ant-design/icons';`
> 
> `const IconFont = createFromIconfontCN({scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js',});`
> 
> 属性里面 `menuItemRender={(menuItemProps, defaultDom) => { const { props: { children } } = defaultDom; const {iconName} = menuItemProps; const iconDom = <IconFont type={iconName} />; if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) { return defaultDom; } return <Link to={menuItemProps.path}>{iconDom}{defaultDom}</Link>; }}`

这个我测试有效，但是只能从阿里矢量去拿，貌似默认的比如simle这种的都不行

**Comment by 1998729** [comment]
> > > > 通过这个插件可以解决：umi-plugin-antd-icon-config
> > > 
> > > 
> > > 本地路由可以。动态菜单不行。
> > > 我的方法，在菜单返回一个自定义属性iconName,用antdd自定义图标，取值，重新render成icon元素
> > 
> > 
> > `import { createFromIconfontCN } from '@ant-design/icons';`
> > `const IconFont = createFromIconfontCN({scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js',});`
> > 属性里面 `menuItemRender={(menuItemProps, defaultDom) => { const { props: { children } } = defaultDom; const {iconName} = menuItemProps; const iconDom = <IconFont type={iconName} />; if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) { return defaultDom; } return <Link to={menuItemProps.path}>{iconDom}{defaultDom}</Link>; }}`
> 
> 这个我测试有效，但是只能从阿里矢量去拿，貌似默认的比如simle这种的都不行

貌似还是不行， 因为你收起菜单的时候文字都没了， 看起来还是需要配合一些其他的函数进行改造， 我先验证一下
