### ISSUE TITLE
Help with @svgr/webpack

### ISSUE THREAD

**Issue by AngeloReppucci** [ant-design/ant-design-pro#6027]
Hi to all,

can someone help me to figure out how to configure ant design pro to use svg as components using `@svgr/webpack` please?

What i done is:

in the `plugin.config.js`, inside the `webpackPlugin `function, i've added the following code:

```
    const svgToComponentRule = config.module.rule('svg')
    svgToComponentRule
        .test(/\.svg(\?v=\d+\.\d+\.\d+)?$/)
        .include
            .add(path.resolve(__dirname, '../src/assets/icons-svg'))
            .end()
    svgToComponentRule
            .use('babel-loader')
                .loader('babel-loader')
            .end()
            .use('@svgr/webpack')
                .loader('@svgr/webpack')
                    .options({
                        babel: false,
                        icon: true,               
                    })
                    .end()
```

This does not work with the following error:

![error](https://user-images.githubusercontent.com/134796/75429340-e94f6280-5949-11ea-940b-7bebd758e0be.png)

What is the problem?

Thanks to all for the help.

PS: `@svgr/webpack` is installed as dev dependecy module.

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它

----

We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by chenshuai2144** [comment]
umi supports svg by default
