### ISSUE TITLE
🧐[问题] 按照文档配置按需加载组件， css 无法加载。

### ISSUE THREAD

**Issue by kuku** [ant-design/ant-design-pro#6031]
### 🧐 问题描述
根据 [独立使用 Pro 组件](https://v2-pro.ant.design/docs/use-components-alone-cn) 这篇文档，进行按需加载配置的时候，按照给出的 babel-plugin-import  配置:

```
{
    libraryName: 'ant-design-pro',
    libraryDirectory: 'lib',
    style: true,
    camel2DashComponentName: false,
}
```

**无法正常加载 css**,  如果把 `style: true` 修改为 `style:css` 就可以正常加载，正常加载的配置如下:

```
{
    libraryName: 'ant-design-pro',
    libraryDirectory: 'lib',
    style: css,
    camel2DashComponentName: false,
}
````

不知道是不是文档写错了，还是和我环境有关，请各位大佬确认下，以免向我这样的新手无法正常使用，谢谢。

### 🚑 其他信息
我的环境是 使用 create-react-app 创建应用，并安装了 `customize-cra` `react-app-rewired` 这两个 package 来修改默认配置文件。

**Comment by chenshuai2144** [comment]
你需要配置 less-loader，pro 的组件已经停止维护了，你有什么需求我帮你找一下同类组件

**Comment by kuku** [comment]
> 你需要配置 less-loader，pro 的组件已经停止维护了，你有什么需求我帮你找一下同类组件

谢谢提示。pro 的组件已经不维护了啊，暂时没有特别需求请你帮忙的，谢谢。
