### ISSUE TITLE
🐛[BUG]403 404 500 页面无法显示

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6035]
### 🐛 bug 描述

403 404 500 页面无法显示，显示为白屏

### 📷 复现步骤

由 status="403" 改为 status={403}
由 status="404" 改为 status={404}
由 status="500" 改为 status={500}
导致无法显示

**Comment by zhfish** [comment]
确实，手动改回字符串

**Comment by chenshuai2144** [comment]
antd 的 bug 下个版本就会修复。
