### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by RichardStark** [ant-design/ant-design-pro#6038]
### 🐛 bug 描述
当前按照官网进行 create umi -> fetch:block 时，会由于antv/data-set 的版本问题，导致fetch失败（然而并不报错）。从而构建好的多个页面会存在404的情况。

### 📷 复现步骤
1. yarn create umi
2. npm install
3. npm run fetch:blocks

### 🏞 期望结果
所有组件按照demo 的样式进行展示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 1.0.0
- umi 版本 2.13.0
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] macOS

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/49977764/75607122-c8943200-5b2e-11ea-973c-29b41759835b.png)

**Comment by RichardStark** [comment]
@antv/data-set 从0.10.2 版本升级到 0.11.1 版本，问题解除

**Comment by afc163** [comment]
@chenshuai2144 @antv/data-set 该升级了

**Comment by afc163** [comment]
记得关联 issue。
