### ISSUE TITLE
webpackrc文件中添加dev-tool配置无效

### ISSUE THREAD

**Issue by fantaishao** [ant-design/ant-design-pro#604]
clone项目之后，在.webpackrc文件中添加    "devtool": "source-map" 配置， 按照 https://webpack.js.org/configuration/devtool/ 的说明，F12控制台中是可以看到源码，然后进行断点调试的，但是仍然是编译后的代码？

那么，应该如何进行配置，F12中可以看到源码进行断点调试呢？

**Comment by afc163** [comment]
建议提到 https://github.com/sorrycc/roadhog
