### ISSUE TITLE
🐛[BUG]NoticeIconView控制台警告

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design-pro#6040]
### 🐛 bug 描述
使用umi脚手架构建antd pro的JS项目， GlobalHeader的RightContent中添加NoticeIconView，当点击Icon打开信息下拉tab时，console会出现警告：

index.js:1 Warning: Received `false` for a non-boolean attribute `selectable`.
If you want to write it to the DOM, pass a string instead: selectable="false" or selectable={value.toString()}.
If you used to conditionally omit it with selectable={condition && value}, pass selectable={condition ? value : undefined} instead.
    in div (created by Context.Consumer)
    in Spin (created by NoticeIcon)
    in div (created by PopupInner)
    in PopupInner (created by Align)
    in Align (created by CSSMotion)
    in CSSMotion (created by ForwardRef)

### 📷 复现步骤
1，使用umi脚手架构建antd pro的JS项目
2，在components目录GlobalHeader的RightContent中添加NoticeIconView
3，当点击header中的bell icon，console出现警告

### 🏞 期望结果
无警告出现

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- Ant Design 版本:  4.0.0
- umi 版本 2.13.0
- 浏览器环境 Chrome 80.0.3987.122
- 开发环境  mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12717523/75629959-ae874c00-5c21-11ea-88d5-29c74e87293c.png)

![image](https://user-images.githubusercontent.com/12717523/75629968-c2cb4900-5c21-11ea-8c0e-946208575aba.png)

**Comment by chenshuai2144** [comment]
这应该是很老的组件了吧，
我刚刚新建了没有发现这个问题，是你自己设置的 selectable？

**Comment by johnnylc** [comment]
没有设置selectable，刚测试问题依然存在。排查到提示文中 NoticeIcon中的Spin控件，替换为div则警告消失，怀疑可能是本地npm包版本问题。不过该警告不影响使用，暂时先关闭了，多谢
