### ISSUE TITLE
🧐[问题]antd pro会升级到umi3.0吗

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6041]
### 🧐 问题描述

会升级到umi3.0吗

**Comment by afc163** [comment]
一定会的。

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/pull/6039
什么时候？

**Comment by zhfish** [comment]
按照 #6039  改，umi里找不到connect
直接跑 #6039 ，能跑起来，但有几个css冲突
算了，还是等官方完工吧。。

**Comment by winter-ice** [comment]
会是放弃dva基于 umi-plugin-model 的吗?

**Comment by kaoding** [comment]
> 会是放弃dva基于 umi-plugin-model 的吗?

 umi-plugin-model 只提供了hooks的写法，那全要改为hooks来写才行，class的方式好像没有办法直接使用，如果用户还是用class来写，dva还是有用的。

**Comment by crashsol** [comment]
感觉以后发展的方向是hooks，umi-plugin-model感觉挺好的

**Comment by wushizhan** [comment]
> 感觉以后发展的方向是hooks，umi-plugin-model感觉挺好的

请问哪里能看到umi-plugin-model 使用方法 以后不用dva了 这种方法还不会用 谢谢

**Comment by winter-ice** [comment]
@wushizhan https://umijs.org/zh-CN/plugins/plugin-model
