### ISSUE TITLE
🐛cnpm create umi 创建 ant-design-pro项目，使用JavaScript ant4版本报错？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6042]
### 🐛cnpm create umi 创建 ant-design-pro项目，使用JavaScript ant4版本报错？
官方脚手架创建项目页面样式错误，控制台警告，ant4
1.cnpm create umi
2选择.ant-design-pro
3.选择JavaScript
4.选择Y
5.cnpm install
6.cnpm run fetch:blocks

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/37643958/75648600-89c7be80-5c8b-11ea-978b-8a2aac26984f.png)

**Comment by chenshuai2144** [comment]
这是各种过期指引，
试试 执行 `umi block clear`，然后重新安装

最终效果应该是

https://preview.pro.ant.design/dashboard/analysis

**Comment by zhuguangyue** [comment]
> 这是各种过期指引，
> 试试 执行 `umi block clear`，然后重新安装
> 
> 最终效果应该是
> 
> https://preview.pro.ant.design/dashboard/analysis

根据官网脚手架，和创建工程步骤也会有问题吗？

**Comment by zhuguangyue** [comment]
> 这是各种过期指引，
> 试试 执行 `umi block clear`，然后重新安装
> 
> 最终效果应该是
> 
> https://preview.pro.ant.design/dashboard/analysis
按照这个步骤，试了很多次都是这效果，兄弟可以指教一下吗
1.cnpm create umi
2选择.ant-design-pro
3.选择JavaScript
4.选择Y
5.cnpm install
6.cnpm run fetch:blocks
7.cnpm start

**Comment by chenshuai2144** [comment]
这个 

`umi block clear`

**Comment by zhuguangyue** [comment]
> umi block clear

![image](https://user-images.githubusercontent.com/37643958/75739690-91956a80-5d40-11ea-8a31-8d90baa786d7.png)

**Comment by zhuguangyue** [comment]
执行 umi block clear
![image](https://user-images.githubusercontent.com/37643958/75739791-d28d7f00-5d40-11ea-86a0-7c898a6009ba.png)

**Comment by chenshuai2144** [comment]
在 pro 的项目里执行一下，或者用 umi ui

**Comment by zhuguangyue** [comment]
也是一样。兄弟使用这个脚手架创建项目是正常，安装区块cnpm run fetch:blocks后，登录注册页面样式乱了，控制台也出错。umi block clear和umi ui都不行。

**Comment by Leskur** [comment]
你再试试看？我用的 npm，看起来一切正常呢~
