### ISSUE TITLE
升级antd 4  icon 失效🐛[BUG]

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#6043]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/42925731/75657017-3dd34480-5ca0-11ea-9f5f-dfb483f09353.png)

### 📷 复现步骤
升级到antd4 后菜单icon 失效

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kzabc** [comment]
对不起我瞎。。。。
https://pro.ant.design/blog/antd-4.0-cn


yarn add umi-plugin-antd-icon-config -D
并且在 config.ts 中设置

export default {
  plugins: [['umi-plugin-antd-icon-config', {}]],
};

**Comment by 569202812** [comment]
> 对不起我瞎。。。。
> https://pro.ant.design/blog/antd-4.0-cn
> 
> yarn add umi-plugin-antd-icon-config -D
> 并且在 config.ts 中设置
> 
> export default {
> plugins: [['umi-plugin-antd-icon-config', {}]],
> };
引用```'umi-plugin-antd-icon-config```报错你有遇到吗
