### ISSUE TITLE
Cannot read property 'Component' of undefined🧐[问题]

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#6044]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/42925731/75688675-ddadc400-5cda-11ea-817f-ffba4f73e306.png)

在修改主题 突然就这样了， 也不知道动了哪里，请大佬帮忙看看

**Comment by chenshuai2144** [comment]
更新一下依赖？
```
git clean -dfx
yarn
```
