### ISSUE TITLE
🐛[BUG] UserLayout无法使用

### ISSUE THREAD

**Issue by chengpu3** [ant-design/ant-design-pro#6045]
### 🐛 bug 描述

在此网站中下载ant-design-pro模板后，运行npm install与npm start后启动项目，然后进入登录页面报错。

### 📷 复现步骤

我发现是UserLayout有问题，当我把登录路由中的component由UserLayout改为SecurityLayout或BasicLayout时则可以运行，只是改变为对应布局。

### 🏞 期望结果

希望UserLayout可以使用

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![123abc](https://user-images.githubusercontent.com/61704044/75698882-739d1b00-5cea-11ea-8190-d56ca09b83f6.png)
![123abcd](https://user-images.githubusercontent.com/61704044/75698901-7b5cbf80-5cea-11ea-9b8e-5b6551bfff89.png)
![123abcde](https://user-images.githubusercontent.com/61704044/75698907-7f88dd00-5cea-11ea-93b7-382d780d1fe4.png)

**Comment by chenshuai2144** [comment]
不能复现，你有做过改动吗？

**Comment by huntdream** [comment]
遇到过一次这个报错，是react-document-title抛出的错误，检查一下UserLayout下面是不是有多个子节点
现在好像已经换成react-helmet了
