### ISSUE TITLE
🐛[BUG] 升级antd4 手机样式

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#6046]

**Comment by kzabc** [comment]
![E4D44B58-1022-4F1F-B9E6-FEDA89F370FB](https://user-images.githubusercontent.com/42925731/75701778-561e8000-5cef-11ea-85e4-1ba451c269a4.png)
![C6552EFD-C6C5-4ACB-A9E1-B79EDCCB25F5](https://user-images.githubusercontent.com/42925731/75701796-5cacf780-5cef-11ea-81d6-c6192a320946.png)

**Comment by chenshuai2144** [comment]
这个问题我见到过一次是因为同时打包了 antd  3 和 4，最好清空依赖重装一下
```
git clean -dfx
yarn
```

**Comment by kzabc** [comment]
@chenshuai2144  按照你提供的方法尝试了下，没有作用
git clean -dfx
cnpm install

`{
  "name": "ant-design-pro",
  "version": "1.0.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run site && npm run gh-pages",
    "fetch:blocks": "pro fetch-blocks && npm run prettier",
    "format-imports": "cross-env import-sort --write '**/*.{js,jsx,ts,tsx}'",
    "gh-pages": "cp CNAME ./dist/ && gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "lint": "npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "check-prettier lint",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "prettier": "prettier -c --write \"**/*\"",
    "start": "umi dev",
    "start:no-mock": "cross-env MOCK=none   umi dev ",
    "start:no-ui": "cross-env UMI_UI=none umi dev",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "ui": "umi ui"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged"
    }
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write",
      "git add"
    ],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.{js,ts,tsx}": "npm run lint-staged:js"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@alitajs/antd-plus": "^1.1.1",
    "@ant-design/compatible": "^1.0.0",
    "@ant-design/icons": "^4.0.0-rc.0",
    "@ant-design/pro-layout": "^5.0.5",
    "@ant-design/pro-table": "^2.1.3",
    "@antv/data-set": "^0.10.2",
    "@types/lodash.debounce": "^4.0.6",
    "antd": "^4.0.0",
    "babel-plugin-prismjs": "^2.0.1",
    "classnames": "^2.2.6",
    "dompurify": "^2.0.8",
    "dva": "^2.4.1",
    "emoji-assets": "^5.0.2",
    "emoji-toolkit": "^5.0.4",
    "escape-string-regexp": "^2.0.0",
    "fluidbox": "^2.0.5",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.1",
    "lodash.debounce": "^4.0.8",
    "marked": "^0.8.0",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.4",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "prismjs": "^1.17.1",
    "qs": "^6.9.0",
    "raf": "^3.4.1",
    "rc-banner-anim": "^2.4.2",
    "react": "^16.8.6",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^16.8.6",
    "react-fittext": "^1.0.0",
    "react-helmet": "^5.2.1",
    "react-router": "^4.3.1",
    "redux": "^4.0.1",
    "throttle-debounce": "^2.1.0",
    "umi": "^2.8.7",
    "umi-plugin-antd-icon-config": "^1.0.3",
    "umi-plugin-antd-theme": "^1.0.1",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.9.5",
    "umi-request": "^1.0.8",
    "webpack-theme-color-replacer": "^1.3.4",
    "yt-emoji-picker": "^1.1.0",
    "yt-simplemde-editor": "^3.2.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.14",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^24.0.23",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.8.19",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^5.0.13",
    "@umijs/fabric": "^2.0.0-beta.3",
    "chalk": "^3.0.0",
    "check-prettier": "^1.0.3",
    "cross-env": "^6.0.0",
    "cross-port-killer": "^1.1.1",
    "enzyme": "^3.9.0",
    "express": "^4.17.1",
    "gh-pages": "^2.0.1",
    "husky": "^3.0.0",
    "import-sort-cli": "^6.0.0",
    "import-sort-parser-babylon": "^6.0.0",
    "import-sort-parser-typescript": "^6.0.0",
    "import-sort-style-module": "^6.0.0",
    "jest-puppeteer": "^4.2.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^9.0.0",
    "mockjs": "^1.0.1-beta3",
    "node-fetch": "^2.6.0",
    "prettier": "^1.19.1",
    "pro-download": "1.0.1",
    "stylelint": "^12.0.0",
    "umi-plugin-antd-icon-config": "^1.0.3",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-pro": "^1.0.2",
    "umi-types": "^0.5.0"
  },
  "optionalDependencies": {
    "puppeteer": "^1.17.0"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "checkFiles": [
    "src/**/*.js*",
    "src/**/*.ts*",
    "src/**/*.less",
    "config/**/*.js*",
    "scripts/**/*.js"
  ]
}
`

**Comment by kzabc** [comment]
![image](https://user-images.githubusercontent.com/42925731/75742620-269c6180-5d49-11ea-8b15-c3f1a998b3a0.png)
