### ISSUE TITLE
🧐[问题] 使用umi构建的项目，菜单图标没展示?

### ISSUE THREAD

**Issue by hejiawang** [ant-design/ant-design-pro#6047]
### 🧐 问题描述

使用umi构建的项目，使用ant design pro 4.0，没有改动代码，菜单图标为什么不展示呢？

### 💻 示例代码

        {
              path: '/dashboard',
              name: 'dashboard',
              icon: 'dashboard',
              routes: [
                {
                  name: 'analysis',
                  icon: 'smile',
                  path: '/dashboard/analysis',
                  component: './dashboard/analysis',
                },
                {
                  name: 'monitor',
                  icon: 'smile',
                  path: '/dashboard/monitor',
                  component: './dashboard/monitor',
                },
                {
                  name: 'workplace',
                  icon: 'smile',
                  path: '/dashboard/workplace',
                  component: './dashboard/workplace',
                },
              ],
            },

**Comment by chenshuai2144** [comment]
看看控制台是不是没有加插件。
https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8
