### ISSUE TITLE
升级antd4 手机出现样式问题 隔一会还崩溃 rc-banner-anim 不显示

### ISSUE THREAD

**Issue by kzabc** [ant-design/ant-design-pro#6048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.kzabc.com](http://www.kzabc.com)

### Steps to reproduce
手机访问kzabc.com 或者chrome 访问 控制台切换手机模式， 将会出现样式问题， 以及"rc-banner-anim": "^2.4.2", 轮播图不显示 访问成功后等一会页面会崩溃

### What is expected?
解决bug

### What is actually happening?
页面 样式混乱，  轮播图不显示 页面会崩溃

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8.6 |
| System | centos |
| Browser | chrome 80.0.3987.122（正式版本） （64 位） |

**Comment by chenshuai2144** [comment]
你的网页中有什么逻辑死循环吗？
切换一下屏幕大小整个页面都会卡死，内存很快就消耗完了

**Comment by kzabc** [comment]
没有逻辑死循环啊，不切换手机显示的情况下是没有问题的， 切换手机显示， 没一会就挂了 ，并且打包后的没有问题。好奇怪啊

**Comment by kzabc** [comment]
![image](https://user-images.githubusercontent.com/42925731/75745561-a5e26300-5d52-11ea-88d8-0628be54eb33.png)

**Comment by kzabc** [comment]
这是老版本  没有升级antd4 时  的样子

**Comment by kzabc** [comment]
等待一会 没有出现崩溃的情况

升级步骤如下:
`npx -p @ant-design/codemod-v4 antd4-codemod src`

![image](https://user-images.githubusercontent.com/42925731/75745742-35881180-5d53-11ea-90e4-395e7f67525d.png)

之后按照提示修改：
 "@ant-design/pro-layout": "^4.8.7",
 "@ant-design/pro-table": "^1.0.17",
 "@ant-design/compatible": "^0.0.1-rc.1",
 "antd": "^3.23.6",


 "@ant-design/pro-layout": "^5.0.5",
 "@ant-design/pro-table": "^2.1.3",
 "@ant-design/compatible": "^1.0.0",
 "antd": "^4.0.0",

**Comment by kzabc** [comment]
@ 各位大佬给看看

**Comment by chenshuai2144** [comment]
我一打开你的网页，几秒钟 内存就耗尽了。

**Comment by kzabc** [comment]
嗯 ，刚才吗？
我访问kzabc.com  没有出现内存耗尽的情况， 但是在本地npm run start:no-mock 访问会出现
我又回滚到未升级前，没有内存就耗尽情况
按照上面步骤执行完antd3升级antd4 后就会出现内存耗尽（只有在浏览器切换手机时出现）。
 我中午14点的时候把线上kzabc.com 的项目，替换成了未升级前的了，

**Comment by kzabc** [comment]
`     <Col{...formItemLayout}>
          <Card bodyStyle={{ padding: '0px' }}>
            <div><img alt="example" width='100%' height= {'200px'} src="https://www.duoguyu.com/dist/images/wechat-miniapp.jpg?v=2019090502" /></div>
          </Card>
          <Card bodyStyle={{ padding: '0px' }}  style={{ marginTop: 6}}>
            <div><img alt="example" width= '100%' height= {'150px'} src="https://www.duoguyu.com/uploads/201905/09/190509025519155.png" /></div>
          </Card>
        </Col>
          <Col {...topColResponsiveProps}>
         <Card
           size={"small"}
          loading={loading.global}
          title="最新文章"
          extra={ <Link
            className={styles.listItemMetaTitle}
            to={`/article/list`}
          >
            更多
          </Link>}
          style={{ marginTop: 6}}
          bordered={false}
          bodyStyle={{ padding: '8px 32px 32px 32px' }}
        >
          <List<IArticle>
          size="small"
          rowKey="id"
          itemLayout="vertical"
          dataSource={newList}

          renderItem={item => (
            <List.Item
              key={item.id}
              extra={  <div className={styles.listItemExtra}>
                {item.preview && <img src={item.preview} width="100%"  alt="预览" />}
              </div>}
            >
              <List.Item.Meta
                title={
                  <Link
                    className={styles.listItemMetaTitle}
                    to={`/article/${item.id}`}
                  >{item.title}
                  </Link>
                }
                description={
                  <span>
                   {item.tags.map(tag => (
                     <Tag>{tag.name}</Tag>
                   ))}
                  </span>
                }
              />
              <ArticleListContent data={item} />
            </List.Item>
          )}
        />

        </Card>

        </Col>
          <Col {...formItemLayout}>
            <Card
              size={"small"}
              loading={loading.global}
              style={{ marginTop: 6}}
              title={"特别推荐"}
              bordered={false}
              bodyStyle={{ padding: '8px 32px 32px 32px' }}
            >
              <List<IArticle>
                size="small"
                rowKey="id"
                itemLayout="vertical"
                dataSource={heatList}
                renderItem={item => (
                  <List.Item
                    key={item.id}
                  >
                    <List.Item.Meta
                      description={
                        <Row gutter={[16, 16]} >
                          <Col span={8}>
                            <img width='100%' height="74px" src={item.preview}/>
                          </Col>
                          <Col span={16}>
                            <p>
                              <a className={styles.listItemMetaTitle} href={item.href}>
                                {item.title}
                              </a>
                            </p>
                            <span>
                            {item.created_at_timeago}
                            </span>
                            <span style={{marginLeft:"10px" }}>
                              浏览 {item.friendly_views_count}
                            </span>

                          </Col>
                        </Row>
                      }
                    />
                  </List.Item>
                )}
              />
            </Card>
            <Card
              loading={loading.global}
              style={{ marginTop: 12}} bodyStyle={{ padding: '0px' }}>
              <div><img alt="example" width= '100%' height= {'145px'} src="https://www.duoguyu.com/uploads/201905/09/190509025519155.png" /></div>
            </Card>

            <Card
              size={"small"}
              loading={loading.global}
              style={{ marginTop: 12}}
              title={"热门标签"}
              bordered={false}
              bodyStyle={{ padding: 24 }}
            >

              {tag.map(tagItem => (
                <Link
                  className={styles.listItemMetaTitle}
                  to={`/article/list?tags=${tagItem.id}`}
                >
                <Tag style={{marginBottom:"8px"}}   color={`#${Math.floor(Math.random()*16777215).toString(16)}`}>{tagItem.name}</Tag>
                </Link>
                  ))}
            </Card>
          </Col>`
这段代码导致cpu 300%

**Comment by kzabc** [comment]
看了我本地崩溃是cpu 满了

**Comment by chenshuai2144** [comment]
通过二分法试一试到底是谁干的，不然没发排查问题

**Comment by kzabc** [comment]
昨天排查了， 把轮播图和list 分开都没事， 在一起有时候cpu 就满了，list在其他地方我也有使用没有出现问题，但是轮播图只有这个页面有

**Comment by kzabc** [comment]
等下我在排查一次

**Comment by kzabc** [comment]
@chenshuai2144 找到了缩小到了轮播图这里，rc-banner-anim

**Comment by kzabc** [comment]
测试了几次就是这个rc-banner-anim

**Comment by kzabc** [comment]
<Row gutter={[12,12]}>

        </Row>

不会是这个问题吧

**Comment by kzabc** [comment]
`
<Row gutter={[12,12]}>
<Col>轮播图</Col>
</Row>
<Row gutter={[12,12]}>
<Col>文章列表</Col>
</Row>
`
咋感觉是row 问题呢

**Comment by kzabc** [comment]
`  <GridContent>
        <Row gutter={[12,12]}>
          <Col {...topColResponsiveProps}>
            <BannerAnim prefixCls="banner-user" autoPlay>
              <Element
                prefixCls="banner-user-elem"
                key="0"
              >
                <BgElement
                  key="bg"
                  className="bg"
                  style={{
                    background: '#364D79',
                  }}
                />
                <TweenOne className="banner-user-title" animation={{ y: 30, opacity: 0, type: 'from' }}>
                  Ant Motion Banner
                </TweenOne>
                <TweenOne className="banner-user-text"
                          animation={{ y: 30, opacity: 0, type: 'from', delay: 100 }}
                >
                  The Fast Way Use Animation In React
                </TweenOne>
              </Element>
              <Element
                prefixCls="banner-user-elem"
                key="1"
              >
                <BgElement
                  key="bg"
                  className="bg"
                  style={{
                    background: '#64CBCC',
                  }}
                />
                <TweenOne className="banner-user-title" animation={{ y: 30, opacity: 0, type: 'from' }}>
                  Ant Motion Banner
                </TweenOne>
                <TweenOne className="banner-user-text"
                          animation={{ y: 30, opacity: 0, type: 'from', delay: 100 }}
                >
                  The Fast Way Use Animation In React
                </TweenOne>
              </Element>
            </BannerAnim>
          </Col>
        <Col{...formItemLayout}>
          <Card bodyStyle={{ padding: '0px' }}>
            <div><img alt="example" width='100%' height= {'200px'} src="https://www.duoguyu.com/dist/images/wechat-miniapp.jpg?v=2019090502" /></div>
          </Card>
      </Col>
      <Col{...formItemLayout}>
        <Card bodyStyle={{ padding: '0px' }}>
          <div><img alt="example" width= '100%' height= {'145px'} src="https://www.duoguyu.com/uploads/201905/09/190509025519155.png" /></div>
        </Card>
      </Col>

        </Row>

        <Row gutter={[12,12]}>

        </Row>
      </GridContent>`


这是我的代码
        <Row gutter={[12,12]}>
          <col>轮播图</col>
        </Row>
        <Row gutter={[12,12]}>
          <col>list</col>
        </Row>


我把下表面的row 中内容删掉只留row  还是会挂

    <Row gutter={[12,12]}>

        </Row>

**Comment by kzabc** [comment]
![image](https://user-images.githubusercontent.com/42925731/76060628-a716c880-5fbc-11ea-9cec-dd702c50a2dd.png)

**Comment by kzabc** [comment]
图片能看到吗

**Comment by kzabc** [comment]
![image](https://user-images.githubusercontent.com/42925731/76060835-2c9a7880-5fbd-11ea-8e1b-07e9c2d2446b.png)

**Comment by chenshuai2144** [comment]
去给 rc-banner-anim 提个 bug 吧
