### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by kambleaa007** [ant-design/ant-design-pro#6049]
### 🐛 bug 描述
My npm run build dist folder deployed here
https://zen-murdock-baaa46.netlify.com/
cant login

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
You need delopy mock data.
You can run umi serve to start

**Comment by kambleaa007** [comment]
my package.json is,
scripts:{ "start": "umi dev", }

**Comment by kambleaa007** [comment]
when i do `npm run build` it creates dist folder, similar way, `netlify` takes my github repo, then builds using `netlify.toml` file,
so, where to write,  `umi serve` in package.json or netlify.toml file

**Comment by kambleaa007** [comment]
Do you mean,
`"start": "umi dev && umi serve",` in `package.json` if i am not wrong
