### ISSUE TITLE
不知有没有做Angular版本pro的意愿

### ISSUE THREAD

**Issue by jackzhum** [ant-design/ant-design-pro#605]
一直很看好ant design，也而且也很实用，特别是出了ng版本的ng-zorro之后。看到这个admin的模板，简直太漂亮了，不知道近期有没有打算将pro移植到angular上的想法？

**Comment by ddcat1115** [comment]
这个得到 ng-zorro 咨询下，之前有个讨论的issue -> https://github.com/NG-ZORRO/ng-zorro-antd/issues/542

**Comment by huajian123** [comment]
https://github.com/huajian123/ng-antd-admin
