### ISSUE TITLE
🐛[BUG]二级菜单的路由不正确

### ISSUE THREAD

**Issue by neo20** [ant-design/ant-design-pro#6051]
### 🐛 bug 描述

使用create-umi创建的脚手架项目，有一个默认的二级菜单示例

    {
          path: '/admin/sub-page',
          name: 'sub-page',
          icon: 'smile',
          component: './Welcome',
          authority: ['admin'],
     },

事实上，我输入下面的网址，显示的都一样。
`http://localhost:8000/admin/sub-page`
`http://localhost:8000/admin/sub-pagexxxxxxxxx`
`http://localhost:8000/admin/abc`

造成二级菜单下的组件没法访问。

另外`http://localhost:8000/xxxx`，会空白，不能显示404

### 📷 复现步骤

终端安装

    create-umi
    ? Select the boilerplate type ant-design-pro
    ? 🤓 Which language do you want to use? JavaScript
    ? 🦄 Time to use better, faster and latest antd@4! Yes

    npm start

### 💻 复现代码

create-umi创建的项目，没有任何改动
https://8000-b1ff33a0-711a-4e6a-aca9-1a0e055dadf9.ws-ap01.gitpod.io/
右上角退出使用admin登录

### © 版本信息

- Ant Design Pro 版本: [1.0.0]
- umi 版本 2.13.3
- 浏览器环境 Chrome  79.0.3945.130
- 开发环境 [ mac OS 10.14.6 ]

**Comment by chenshuai2144** [comment]
403了,
无法再现，最好来的repo，估计是你的路由配置错了

**Comment by neo20** [comment]
> 403了,
> 无法再现，最好来的repo，估计是你的路由配置错了

现在可以打开了。
我没有修改配置，都是默认的。

**Comment by supremeFish** [comment]
确实是这样，父路由 如果 配置component，子路由全部被父路由的component覆盖。
不知道有什么解决办法没

**Comment by neo20** [comment]
> 确实是这样，父路由 如果 配置component，子路由全部被父路由的component覆盖。
> 不知道有什么解决办法没

明白了。去掉122和125行就行了。建议官方修改，以免再有人疑惑

https://github.com/ant-design/ant-design-pro/blob/0cb2e28db5f107ac5e6bdf69319390b62593156e/config/config.ts#L122

https://github.com/ant-design/ant-design-pro/blob/0cb2e28db5f107ac5e6bdf69319390b62593156e/config/config.ts#L125

**Comment by H5futurehreohanshuo** [comment]
# #

> > 确实是这样，父路由 如果 配置component，子路由全部被父路由的component覆盖。
> > 不知道有什么解决办法没
> 
> 明白了。去掉122和125行就行了。建议官方修改，以免再有人疑惑
> 
> https://github.com/ant-design/ant-design-pro/blob/0cb2e28db5f107ac5e6bdf69319390b62593156e/config/config.ts#L122
> 
> https://github.com/ant-design/ant-design-pro/blob/0cb2e28db5f107ac5e6bdf69319390b62593156e/config/config.ts#L125

但是面包屑那就显示不正确了。。。

**Comment by H5futurehreohanshuo** [comment]
可参考：https://github.com/ant-design/ant-design-pro/issues/5873
