### ISSUE TITLE
预览页面404

### ISSUE THREAD

**Issue by cokyxu** [ant-design/ant-design-pro#6053]
https://preview.pro.ant.design/   网页404了

**Comment by aiyuchen** [comment]
`npm run fetch:blocks`下载到本地预览，不过默认提供的页面里面好多错误啊

**Comment by Plortinus** [comment]
修复发布了吗？现在还是一直404

**Comment by cokyxu** [comment]
> 修复发布了吗？现在还是一直404

已经好了，谢谢

**Comment by byan** [comment]
好像没有。
请求错误 404: https://preview.pro.ant.design/api/currentUser
发出的请求针对的是不存在的记录，服务器没有进行操作。
