### ISSUE TITLE
🐛[BUG]项目打包上线后页面报错：vue We're sorry but vue-antd-pro doesn't work properly without JavaScript enabled. Please enable it

### ISSUE THREAD

**Issue by SidselLoong** [ant-design/ant-design-pro#6056]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by SidselLoong** [comment]
> ### 🐛 bug 描述
> 在本地挺好的，项目上线之后在页面上报错：vue We're sorry but vue-antd-pro doesn't work properly without JavaScript enabled. Please enable it
> 
> ### 📷 复现步骤
> ### 🏞 期望结果
> ### 💻 复现代码
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 4.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]
> 
> ### 🚑 其他信息

**Comment by muzig** [comment]
为什么这个问题被close了喃; 请问有解决方案了吗? 感谢

**Comment by chenshuai2144** [comment]
vue-antd-pro

这里是react的
