### ISSUE TITLE
🧐[问题]`prolayout`如何做到点击子菜单的时候，其他菜单不会自动收起来

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design-pro#6057]
现在的菜单，点击任意一个子菜单，只展开当前父级菜单，其他菜单自动收起来
![image](https://user-images.githubusercontent.com/578141/75848842-510c1e80-5e1e-11ea-9284-a400eb0c6734.png)

我希望是无论怎么点子菜单，所有菜单都不要自动收起来，在antd的`menu`中有一个“内嵌菜单”示范：
> https://ant.design/components/menu-cn/#components-menu-demo-inline
![image](https://user-images.githubusercontent.com/578141/75848936-929cc980-5e1e-11ea-9b2b-30946d9b87c4.png)

请问如何做到像示范案例那样，无论怎么点子菜单，所有菜单不会收起来

**Comment by chenshuai2144** [comment]
需要使用受控的 openKeys ,现在不支持不变成的方式。

**Comment by aiyuchen** [comment]
能否增加个api，禁止点击菜单后自动收起呢？目前可以默认展开所有菜单
```
menu: {defaultOpenAll: true,}
```
但是点击任意展开的菜单，都会自动把其他菜单收起来，这样操作就多余了
能不能提供一个api禁止自动收起呢 @chenshuai2144

**Comment by chenshuai2144** [comment]
`opeKeys={false}` 即可

**Comment by tiansQAQ** [comment]
> `opeKeys={false}` 即可

敷衍了事
