### ISSUE TITLE
🧐[问题] 我希望在一个二级页面获取路由表信息，应该咋获取呀

### ISSUE THREAD

**Issue by mathcw** [ant-design/ant-design-pro#6058]
### 🧐 问题描述

我有个权限的编辑页面 需要获取到路由表的配置信息 
 应该怎么获取呢？
我看layout的props里面是有完整的路由信息的，难道我需要在layout中把routes放入全局的modal里
然后在编辑页面使用它吗？大佬们有啥其他的方法不

**Comment by chenshuai2144** [comment]
在 layout 中的时候放到 dva 里面吧。

**Comment by mathcw** [comment]
> 在 layout 中的时候放到 dva 里面吧。
好吧  谢谢回复 我觉得我这个想法很奇怪 我要在想想
