### ISSUE TITLE
为什么我使用antd pro 的模板出现以下问题？🧐[问题]

### ISSUE THREAD

**Issue by huangruitian** [ant-design/ant-design-pro#6059]

**Comment by huangruitian** [comment]
⚓  Start git fetch
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
Faild git checkout: Command failed: git checkout master
undefined
undefined

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
Faild git checkout: Command failed: git checkout master
undefined
undefined


🚧  Execute task error: Error: Command failed: git checkout master
undefined
undefined
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
Faild git checkout: Command failed: git checkout master
undefined
undefined


🚧  Execute task error: Error: Command failed: git checkout master
undefined
undefined

**Comment by chenshuai2144** [comment]
用 umi ui 清理一下缓存，应该是 git clone 的时候失败了。

**Comment by huangruitian** [comment]
> 用 umi ui 清理一下缓存，应该是 git clone 的时候失败了。

方便告知以下怎么清嘛？刚入坑，谢谢

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/75870873-97757380-5e46-11ea-8e12-9bd1bdd4d030.png)


这个的右上角有个 清理的图表，点一下就好了

**Comment by huangruitian** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/75870873-97757380-5e46-11ea-8e12-9bd1bdd4d030.png)
> 
> 这个的右上角有个 清理的图表，点一下就好了

谢谢，已解决，是git clone 的问题，不过右上角的清理没用。是npm的问题
