### ISSUE TITLE
PageHeaderLayout has a display issue with nav

### ISSUE THREAD

**Issue by vtista** [ant-design/ant-design-pro#606]
![default](https://user-images.githubusercontent.com/22438077/34657500-a8ac18b2-f461-11e7-849c-6e11362dbc59.png)

**this is code from your documents**:

export const getNavData = app => [
  {
    component: dynamicWrapper(app, ['user'], () => import('../layouts/BasicLayout')),
    layout: 'BasicLayout',
    name: '详情页',
    path: '/',
    icon: 'profile',
    children: [{
      name: '基础详情页',
      path: '/',
      component: dynamicWrapper(app, ['rule'], () => import('../routes/List/TableList')),
    }, {
      name: '高级详情页',
      path: 'advanced',
      children: [{
        name: '高级详情页',
        path: 'new',                      // id 为参数名
        component: dynamicWrapper(app, [], () => import('../routes/new/new')),
      }]
    }],
  }

**Comment by afc163** [comment]
It is fixed in master now.

Check https://github.com/ant-design/ant-design-pro/pull/440

**Comment by vtista** [comment]
Well,the reply is fast,that's quite impressive! I have tested master branch which works perfect fine.You documents must be out of date then.

**Comment by afc163** [comment]
We are working on it: https://github.com/ant-design/ant-design-pro/issues/333
