### ISSUE TITLE
4.0版本当中 是否相对应的依赖也更新到了最新版，比如umi是否是3.x🧐[问题]

### ISSUE THREAD

**Issue by infinityboy** [ant-design/ant-design-pro#6060]

**Comment by chenshuai2144** [comment]
umi@3 还没有适配，antd4 已经升级完成。

**Comment by joesdu** [comment]
> umi@3 还没有适配，antd4 已经升级完成。

希望早点出Umi3的pro模板项目.

**Comment by xiexingen** [comment]
+1

**Comment by kaoding** [comment]
+1

**Comment by liangyongrui** [comment]
+1

**Comment by xiexingen** [comment]
我就坐等这个出来 做个参考 然后改之前的了

**Comment by fangzhengjin** [comment]
+1

**Comment by infinityboy** [comment]
> umi@3 还没有适配，antd4 已经升级完成。

umi3应该还有一些bug，我昨天用umi3.0 内置的antd 4.0 想看一下暗黑主题，配置无效。

**Comment by infinityboy** [comment]
> > umi@3 还没有适配，antd4 已经升级完成。
> 
> 希望早点出Umi3的pro模板项目.

是啊

**Comment by joesdu** [comment]
> > > umi@3 还没有适配，antd4 已经升级完成。
> > 
> > 
> > 希望早点出Umi3的pro模板项目.
> 
> 是啊

出了模板我才敢升级.现在的项目我升级包后,发现错误太多了.头大,不想动了.到时候我新建项目,重新迁移就好.

**Comment by crashsol** [comment]
> > > > umi@3 还没有适配，antd4 已经升级完成。
> > > 
> > > 
> > > 希望早点出Umi3的pro模板项目.
> > 
> > 
> > 是啊
> 
> 出了模板我才敢升级.现在的项目我升级包后,发现错误太多了.头大,不想动了.到时候我新建项目,重新迁移就好.

坐等官方的pro release，才敢升级

**Comment by fenglier** [comment]
> > > > umi@3 还没有适配，antd4 已经升级完成。
> > > 
> > > 
> > > 希望早点出Umi3的pro模板项目.
> > 
> > 
> > 是啊
> 
> 出了模板我才敢升级.现在的项目我升级包后,发现错误太多了.头大,不想动了.到时候我新建项目,重新迁移就好.

我也是升级umi2到umi3，升级了一天了都没弄出来。头大

**Comment by joesdu** [comment]
> > > > > umi@3 还没有适配，antd4 已经升级完成。
> > > > 
> > > > 
> > > > 希望早点出Umi3的pro模板项目.
> > > 
> > > 
> > > 是啊
> > 
> > 
> > 出了模板我才敢升级.现在的项目我升级包后,发现错误太多了.头大,不想动了.到时候我新建项目,重新迁移就好.
> 
> 我也是升级umi2到umi3，升级了一天了都没弄出来。头大

升级其实不难.
