### ISSUE TITLE
TypeError: Path must be a string有没有人遇见过

### ISSUE THREAD

**Issue by tianyuanztm** [ant-design/ant-design-pro#6063]
最近项目更新了，莫名其妙在start，和build的时候，报错TypeError: Path must be a string.

**Comment by MangGoDio** [comment]
我也遇到了，朋友请问你怎么解决的

**Comment by zhiqiangpan** [comment]
我也遇到了，朋友请问你怎么解决的

**Comment by tianyuanztm** [comment]
umi版本过高，或者说你同事在使用umi的@2与@3
1.清理npm缓存
rm -rf node_modules 
rm package-lock.json 
npm cache clear --force
2.检查package里umi的版本，改为@2
3.npm install

> 我也遇到了，朋友请问你怎么解决的

**Comment by tianyuanztm** [comment]
> 我也遇到了，朋友请问你怎么解决的

@zhiqiangpan @MangGoDio umi版本过高，或者说你同事在使用umi的@2与@3
1.清理npm缓存
rm -rf node_modules 
rm package-lock.json 
npm cache clear --force
2.检查package里umi的版本，改为@2
3.npm install

**Comment by MangGoDio** [comment]
> > 我也遇到了，朋友请问你怎么解决的
> 
> @zhiqiangpan @MangGoDio umi版本过高，或者说你同事在使用umi的@2与@3
> 1.清理npm缓存
> rm -rf node_modules
> rm package-lock.json
> npm cache clear --force
> 2.检查package里umi的版本，改为@2
> 3.npm install

啊啊谢谢了，单独升级一个antd就好了

**Comment by tianyuanztm** [comment]
> > > 我也遇到了，朋友请问你怎么解决的
> > 
> > 
> > @zhiqiangpan @MangGoDio umi版本过高，或者说你同事在使用umi的@2与@3
> > 1.清理npm缓存
> > rm -rf node_modules
> > rm package-lock.json
> > npm cache clear --force
> > 2.检查package里umi的版本，改为@2
> > 3.npm install
> 
> 啊啊谢谢了，单独升级一个antd就好了

哎，主要最近都是大版本更新，就很烦

**Comment by zhiqiangpan** [comment]
我把原来的目录删掉，重新下载安装，就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ".Mr."<notifications@github.com&gt;; 
发送时间: 2020年3月6日(星期五) 中午12:07
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;; 
抄送: "潘智强"<zhiqiangpan@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-pro] TypeError: Path must be a string有没有人遇见过 (#6063)



   
我也遇到了，朋友请问你怎么解决的
  
@zhiqiangpan @MangGoDio umi版本过高，或者说你同事在使用umi的@2与@3
 1.清理npm缓存
 rm -rf node_modules
 rm package-lock.json
 npm cache clear --force
 2.检查package里umi的版本，改为@2
 3.npm install
  
啊啊谢谢了，单独升级一个antd就好了
  
哎，主要最近都是大版本更新，就很烦

**Comment by chenshuai2144** [comment]
umi 的版本冲突导致的，一般 重装依赖就会好

**Comment by ISBN9527** [comment]
umi 3.1 + antd 4.1.5一直报  TypeError: Path must be a string.错误

**Comment by ISBN9527** [comment]
@chenshuai2144 上面的方法都试了，还是报这个错

**Comment by tianyuanztm** [comment]
> @chenshuai2144 上面的方法都试了，还是报这个错

最简单的就是umi版本冲突，ant版本冲突，重新安装依赖就好了，实在不行就降umi版本为2.0

**Comment by ISBN9527** [comment]
不能降umi版本，为了升级umi，项目都重构了

**Comment by xiaofsu** [comment]
难受，用到了这多插件版本，能不能统一管理下？
