### ISSUE TITLE
🐛[BUG] .less import crashing app

### ISSUE THREAD

**Issue by ncioj10** [ant-design/ant-design-pro#6064]
### 🐛 bug 描述

I import a .less file as such:

``` import styles from './style.less'; ```

In my Card i call:
``` <Card style={styles.test} ... > ```
This gives me a complete white screen with the following error:

``` Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX. ``` 

style.less contains:
```
.test {
  color: black;
}
Antd pro: 4.11.3
Antd: 3.26.12

Rest:
```
 "dependencies": {
    "@ant-design/pro-layout": "^4.11.3",
    "@antv/data-set": "^0.10.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "@types/uuid": "^3.4.5",
    "antd": "^3.26.12",
    "classnames": "^2.2.6",
    "dva": "^2.4.1",
    "konva": "^4.0.12",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.1",
    "memoize-one": "^5.0.4",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "^3.0.0",
    "prop-types": "^15.7.2",
    "qs": "^6.7.0",
    "quill": "^1.3.7",
    "quill-mention": "^2.1.4",
    "rc-animate": "^2.8.3",
    "react": "^16.8.6",
    "react-container-query": "^0.11.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.8.6",
    "react-grid-gallery": "^0.5.5",
    "react-konva": "^16.9.0-0",
    "react-media": "^1.9.2",
    "react-media-hook2": "^1.0.5",
    "react-mic": "^12.4.1",
    "react-quill": "^1.3.3",
    "react-sketch": "^0.5.1",
    "redux": "^4.0.1",
    "umi": "^2.7.2",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.8.2",
    "umi-request": "^1.0.7",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "@ant-design/colors": "^3.1.0",
    "@types/classnames": "^2.2.7",
    "@types/history": "^4.7.2",
    "@types/jest": "^24.0.13",
    "@types/lodash": "^4.14.133",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.8.19",
    "@types/react-document-title": "^2.0.3",
    "@types/react-dom": "^16.8.4",
    "@umijs/fabric": "^1.0.4",
    "babel-eslint": "^10.0.1",
    "chalk": "^2.4.2",
    "check-prettier": "^1.0.3",
    "cross-env": "^5.2.0",
    "cross-port-killer": "^1.1.1",
    "enzyme": "^3.9.0",
    "eslint": "^5.16.0",
    "gh-pages": "^2.0.1",
    "husky": "^2.3.0",
    "import-sort-cli": "^6.0.0",
    "import-sort-parser-babylon": "^6.0.0",
    "import-sort-parser-typescript": "^6.0.0",
    "import-sort-style-module": "^6.0.0",
    "jest-puppeteer": "^4.2.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^8.1.7",
    "mockjs": "^1.0.1-beta3",
    "node-fetch": "^2.6.0",
    "prettier": "^1.17.1",
    "slash2": "^2.0.0",
    "stylelint": "^10.1.0",
    "webpack-theme-color-replacer": "^1.1.5"
  },
```

**Comment by afc163** [comment]
```diff
- <Card style={styles.test} ... >
+ <Card className={styles.test} ... >
```
