### ISSUE TITLE
🐛[BUG]如何在ProTable的表单提交时加校验规则拦截

### ISSUE THREAD

**Issue by Jackay1990** [ant-design/ant-design-pro#6066]
最新发布版的ant design pro4，基于ant degin@4 的查询表格案例中，新增的页面弹出框表单使用了ProTable， 点击提交按钮的时候直接执行onSubmit（）了，这期间并没有做规则校验拦截，请问如果加 form.validateFields（）....

### 💻 复现代码

```
<CreateForm onCancel={() => handleModalVisible(false)} modalVisible={createModalVisible}>
        <ProTable<TableListItem, TableListItem>
          onSubmit={async value => {
            const success = await handleAdd(value);
            if (success) {
              handleModalVisible(false);
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          rowKey="key"
          type="form"
          columns={columns}
          rowSelection={{}}
        />
</CreateForm>
```

**Comment by chenshuai2144** [comment]
查询的表单不应该有必填项的，所以关闭了规则检验。

**Comment by Jackay1990** [comment]
> 查询的表单不应该有必填项的，所以关闭了规则检验。

这个是新增页面的，不是查询的

**Comment by Jackay1990** [comment]
是这个页面的哈：

![image](https://user-images.githubusercontent.com/6316440/76057414-6e72f100-5fb4-11ea-8c07-7e1c59ae8ab4.png)

**Comment by chenshuai2144** [comment]
我刚刚试了一下是好的，你是不是要更新一下版本

**Comment by Jackay1990** [comment]
> 我刚刚试了一下是好的，你是不是要更新一下版本？

我测试的版本是一个星期前的，刚更新最新版本，发现可以了， 谢谢啦！

**Comment by 15723185734** [comment]
> 是这个页面的哈：
> 
> ![image](https://user-images.githubusercontent.com/6316440/76057414-6e72f100-5fb4-11ea-8c07-7e1c59ae8ab4.png)

我通过ProTable type='form'是  表单lable和输入框是排列是纵向的 ，请问怎么横排的？
