### ISSUE TITLE
🧐[问题]关于二级页面如何配置component

### ISSUE THREAD

**Issue by liuyun521** [ant-design/ant-design-pro#6067]
### 🧐 问题描述
我有这样的一个菜单
![image](https://user-images.githubusercontent.com/9554224/76064101-f7455900-5fc3-11ea-94ff-870f43f30acd.png)
在config.ts中这样备注route
{
name: "settings",
icon:"setting",
children:[{
	name: "permission",
        icon:"lock",
	children:[
		{
		  path: "/settings/personinfo/groups",
		  name: "groups"
		  component: './settings/groups'
		}
	]}
]
}

但是编译运行时报这个错误
This relative module was not found:

* ../../../groupsin ./src/pages/.umi/router.js

**Comment by zs9720** [comment]
老哥改好没

**Comment by liuyun521** [comment]
> 老哥改好没
解决了

**Comment by zs9720** [comment]
> 老哥改好没
> 解决了

那方便说一下 你改了哪块吗  我这怎么都改不好

**Comment by liuyun521** [comment]
在顶层目录定义好path 和 component，同时定义hideInMen: true,
如下
{
              hideInMen: true,
              path: '/settings/task',
              component: './settings/task',
            },

然后在菜单定义中只需path一致就可以，不需定义component

**Comment by zs9720** [comment]
> 在顶层目录定义好path 和 component，同时定义hideInMen: true,
> 如下
> {
> hideInMen: true,
> path: '/settings/task',
> component: './settings/task',
> },
> 然后在菜单定义中只需path一致就可以，不需定义component

谢谢老哥
