### ISSUE TITLE
安装Ant Design Pro 出错🧐[问题]

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#6070]
![image](https://user-images.githubusercontent.com/44084004/76096463-1f06e200-6001-11ea-83a8-d8e5026c403b.png)
安装的时候出现问题，有人遇过吗？这个是V4版本

**Comment by afc163** [comment]
你需要先安装 git。

**Comment by zhangWeiZhuang** [comment]
谢谢指教。
我这边安装了git已经再次试了一下。
却报错以下错误
![image](https://user-images.githubusercontent.com/44084004/76101328-38ac2780-6009-11ea-93e8-c17b803a3035.png)
这个会影响后续执行吗？
