### ISSUE TITLE
菜单图标显示成文字的问题

### ISSUE THREAD

**Issue by tigerxiongj** [ant-design/ant-design-pro#6071]
### 🧐 问题描述
项目采用antd pro脚手架生成，根据umi官方文档升级成umi3。
package.json的依赖包如下：
    "@ant-design/icons": "^4.0.2",
    "@ant-design/pro-layout": "^5.0.5",
    "@umijs/preset-react": "^1.3.9",
    "antd": "^4.0.1",
    "umi": "^3.0.5",
运行发现左侧菜单栏的图标显示成文字本身，控制太打印了错误。

### 💻 示例代码
config.js中的一项菜单配置如下：
            {
              name: '空白页面',
              icon: 'smile',
              path: '/emptypage',
              component: './EmptyPage',
            },

官方的代码注解是这样的：
// Allow menu.js config icon as string or ReactNode
//   icon: 'setting',
//   icon: 'icon-geren' #For Iconfont ,
//   icon: 'http://demo.com/icon.png',
//   icon: '/favicon.png',
//   icon: <Icon type="setting" />,

第一种，字符串形式的，被干掉了。
iconfont是可以的。
但是我想试第五种，引用@ant-design/icons中的一个icon对象<SmileOutlined />
            {
              name: '空白页面',
              icon: <SmileOutlined />,
              path: '/emptypage',
              component: './EmptyPage',
            },
不过运行的时候报找不到react，引用react也不对，感觉config.js中没有办法像正常的页面那样渲染。

请教一下，有没有办法像正常的页面那样在config.js引用icon对象。

**Comment by admiao** [comment]
icon 在antd4中是单个引入的

**Comment by tigerxiongj** [comment]
> icon 在antd4中是单个引入的

引入没有问题，import { SmileOutlined } from @ant-design/icons
出错的地方是config.js的icon属性指向这个icon变量，无法渲染，回报react的错误
应该是config.js还没有到react的地方

**Comment by chenshuai2144** [comment]
config node 环境，里面是没有react 的。可以看这骗文章
https://pro.ant.design/blog/antd-4.0-cn
