### ISSUE TITLE
请问在umi的资产中添加模板报下面这个错是什么原因？

### ISSUE THREAD

**Issue by LiamLin07** [ant-design/ant-design-pro#6072]
![image](https://user-images.githubusercontent.com/47836780/76133178-f0652780-6051-11ea-8a06-3e7c35932e9f.png)
控制台上报这个错
![image](https://user-images.githubusercontent.com/47836780/76133262-5651af00-6052-11ea-979b-6b7ddb21b86d.png)

**Comment by chenshuai2144** [comment]
试着点一下右上角的清理，应该是git clone 失败导致的
