### ISSUE TITLE
升级到umi3.x后npm run ui 命令无效🐛[BUG]

### ISSUE THREAD

**Issue by BYChoo** [ant-design/ant-design-pro#6073]
### 🐛 bug 描述

根据官网给出的升级步骤升级后运行：

`npm run ui`

报错：**run command failed, command ui does not exists.**
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本：3.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Godi13** [comment]
你是要使用 umi ui 吗？

[umi 3.0 版 ui 使用方法 ](https://umijs.org/zh-CN/docs/use-umi-ui)

```
yarn add @umijs/preset-ui -D
UMI_UI=1 umi dev
```

**Comment by ruwuchusan** [comment]
umi 3.0想使用umiui必须在已有项目中么？ 无法从零构建
