### ISSUE TITLE
🧐[问题]'pro' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by homlex** [ant-design/ant-design-pro#6077]
### 🧐 在ant-design-pro根目录下运行 npm run fetch:blocks 报如下错误：

![image](https://user-images.githubusercontent.com/48396880/76148031-5054e000-60dd-11ea-93a6-43ead08a4124.png)

**Comment by chenshuai2144** [comment]
重新安装一下依赖，尝试使用 tyarn 或者 cnpm
