### ISSUE TITLE
optional chaining不支持

### ISSUE THREAD

**Issue by Pzhicong** [ant-design/ant-design-pro#6078]
![image](https://user-images.githubusercontent.com/13126996/76155263-9b461600-6124-11ea-83e4-407ecaa99589.png)
如题，为什么不支持ts  optional chaining写法，请问要怎么升级呢

**Comment by chenshuai2144** [comment]
升级typescript 版本。 至少要 3.7

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html
