### ISSUE TITLE
npm run fetch:blocks 报错 区块分步安装也报错

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design-pro#6083]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 window 10
- 开发环境 [e.g. mac OS]

**Comment by zheng1013757145** [comment]
![2020-03-09_112740](https://user-images.githubusercontent.com/23191825/76180751-d6664900-61f9-11ea-81aa-8dac3a9cbbbc.png)

**Comment by zheng1013757145** [comment]
npm run fetch:blocks 没有安装全部区块

**Comment by dekuofa1995** [comment]
(node:23660) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: connect ECONNREFUSED 13.250.168.23:443

以为是网络错误，但是开关代理，以及切换淘宝源都无效

**Comment by dekuofa1995** [comment]
> (node:23660) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: connect ECONNREFUSED 13.250.168.23:443
> 
> 以为是网络错误，但是开关代理，以及切换淘宝源都无效

替换为 gitee 下载路径解决了。

```js
// node_modules/@ant-design/pro-cli/src/fetch-blocks/index.js
...
const fetchGithubFiles = async () => {
  const ignoreFile = ['_scripts', 'tests'];
  // 替换此处地址
  const data = await fetch('https://api.github.com/repos/ant-design/pro-blocks/git/trees/master');
  if (data.status !== 200) {
    return [];
  }
  const { tree } = await data.json();
  const files = tree.filter(file => file.type === 'tree' && !ignoreFile.includes(file.path));
  return files;
};
```
gitee 地址：https://gitee.com/api/v5/repos/mirrors/Ant-Design-Pro/git/trees/master

**Comment by zheng1013757145** [comment]
github 似乎连接有问题 很慢

**Comment by chenshuai2144** [comment]
现在用的是 gitee，umi block clear 一下就会非常快
