### ISSUE TITLE
👑 [需求] Windows下的默认字体

### ISSUE THREAD

**Issue by ousing9** [ant-design/ant-design-pro#6085]
### 🥰 需求描述

Windows用Chrome 80访问[preview](https://preview.pro.ant.design/)页面，或者用`yarn create umi`创建的用antd v4的模板，默认字体都是宋体，希望能改成默认微软雅黑。

### 🧐 解决方案

CSS更改font-family

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32257773/76182637-a2daed00-6200-11ea-82fe-17bcc9eba342.png)

**Comment by chenshuai2144** [comment]
。。。
我们和平台无关的，你可以自己设置。

**Comment by ousing9** [comment]
。。font-family不是从前到后匹配的吗，在宋体之前加一个微软雅黑就可以给Windows适配了吧，也不影响苹果和Linux，这样preview和默认页面的观感会更好些吧？

**Comment by chenshuai2144** [comment]
可以去 antd 提一个 issue。
这里是现在的
```
Avenir, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji', sans-serif;
```
