### ISSUE TITLE
按照官方步骤初始化项目尽管选择了语言还是会生成双语言的项目🐛[BUG]

### ISSUE THREAD

**Issue by xieww** [ant-design/ant-design-pro#6087]
### 🐛 bug 描述
执行npm create umi之后选择ant-design-pro再选择JavaScript生成的项目最终会是双语言的版本

### 📷 复现步骤
创建新的文件夹，如
1.  mkdir test；
2. 在test下执行npm create umi；
3. 选择ant-design-pro；
4. 选择JavaScript;

### 🏞 期望结果
按照上面步骤执行完成应该是生成的是JavaScript版本的项目

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本：2.13.0
- 浏览器环境: 谷歌(80.0.3987.132)
- 开发环境 mac OS：10.13.6

### 🚑 其他信息
![1583738560197](https://user-images.githubusercontent.com/26969239/76191282-f148b580-6219-11ea-8cb6-b0b9c0c6151e.jpg)

**Comment by chenshuai2144** [comment]
看起来是个 bug，没有删除掉所有的 js 的文件。

**Comment by xieww** [comment]
我按照官方步骤重新试了一下还是不行，选择JavaScript还是会生成双语言的项目，你们并没有解决这个bug啊

**Comment by afc163** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
@xieww  来个复现方式，我复现不了。
或者来个截图，我看看你是怎么操作的
