### ISSUE TITLE
🐛[BUG] preview页面后端接口5xx错误码

### ISSUE THREAD

**Issue by tun100** [ant-design/ant-design-pro#6088]
### 🐛 bug 描述

无法访问preview完整功能，后端接口报500错误
页面：https://preview.pro.ant.design/dashboard/analysis   
还有一个问题，是否有preview完整的源码可以使用呢？我想下载到本地浏览一下效果

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/available-script-cn#npm-run-fetchblocks
