### ISSUE TITLE
🐛[BUG] 麵包屑越來越棒，即使最後一個項目

### ISSUE THREAD

**Issue by WillianHMartins** [ant-design/ant-design-pro#6089]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
You can use English to describe question.

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它

----

We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
