### ISSUE TITLE
阿里公司内部使用，怎么集成buc登录啊？？？

### ISSUE THREAD

**Issue by yaogunzenml** [ant-design/ant-design-pro#609]
阿里公司内部使用，怎么集成buc登录啊？？？能不能给个示例

**Comment by ddcat1115** [comment]
内部使用示例（脚手架）及文档正在紧张开发中，预计会在周三随 pro 1.0 一起公布

**Comment by ddcat1115** [comment]
https://pro.ant.design/docs/getting-start-inner-cn
