### ISSUE TITLE
🐛[BUG] PageHeaderWrapper结合tabList滑动效果卡顿

### ISSUE THREAD

**Issue by SmartWrh** [ant-design/ant-design-pro#6091]
### 🐛 bug 描述

PageHeaderWrapper结合tabList滑动效果卡顿

### 📷 复现步骤

官方Demo个人中心和搜索列表均有此情况

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
把问题写在标题里面，再来个重现
