### ISSUE TITLE
🐛[BUG]在首页刷新页面，会导致cookie的token失效

### ISSUE THREAD

**Issue by jaysg** [ant-design/ant-design-pro#6092]
### 🐛 bug 描述
登陆存了token在cookie后，在首页刷新页面，会导致cookie的token失效，复现情况特殊
### 📷 复现步骤
代码准备：
1.拉取antdpro最新的代码
2.在src/model/login.js/login 加入一行登陆成功存token
交互流程：
1.保证首次登陆的情况下（也可以手动清除domain下全部缓存）
2.在登录页刷新一次（不要登录，登录后无法复现）
3.登录进入默认的欢迎页面
4.F5刷新并查看ApplicationCookie
结果是上面存的token cookie丢失了，目前仅发现以上步骤会重现
### 🏞 期望结果
首次登陆后，在index刷新不会丢失token

antdproV4，任意主流浏览器

https://intelab2latest.blob.core.chinacloudapi.cn/file/avatar/999_file_b5f4aab2-1ebb-49d5-9020-010fe332dfc9.png

**Comment by jaysg** [comment]
![QQ浏览器截图20200310104044](https://user-images.githubusercontent.com/28700250/76274415-9bc4e500-62bb-11ea-9a32-58689a2498e1.png)

**Comment by chenshuai2144** [comment]
cookie 除了前端操作，后端也可以操作，是不是后端重置掉了？

**Comment by jaysg** [comment]
> cookie 除了前端操作，后端也可以操作，是不是后端重置掉了？

不是的，我是拉的最新的antdpro的代码，并没有部署和调用后端接口

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
----
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
