### ISSUE TITLE
🧐[问题]使用yarn create umi创建项目后，配置图标，图标显示不正常

### ISSUE THREAD

**Issue by snowwindsand** [ant-design/ant-design-pro#6095]
### 🧐 问题描述

通过官方的文档创建项目后，菜单加载，如果只有一个菜单，显示的图标与文字很近，样式不正常。
### 💻 示例代码

```
path: '/',
          component: '../layouts/BasicLayout',
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/',
              redirect: '/welcome',
            },
            {
              path: '/welcome',
              name: 'welcome',
              icon: 'smile',
              component: './Welcome',
            },
```
### 🚑 其他信息
查了论坛，也看项目自动配置了如下：
```
const plugins = [
  ['umi-plugin-antd-icon-config', {}],
```

![image](https://user-images.githubusercontent.com/13346090/76300702-26c3d080-62f8-11ea-824a-ea939d1695ea.png)

**Comment by sonstephendo** [comment]
I can confim that this bug happen with current "umi-antd-pro" template. Maybe it comes from pro-layout package (antd)
Inspects: 
![Screenshot from 2020-03-10 17-39-20](https://user-images.githubusercontent.com/30832424/76305050-047d8300-62f7-11ea-8980-62f0ad007986.png)
![Screenshot from 2020-03-10 17-43-04](https://user-images.githubusercontent.com/30832424/76305086-13643580-62f7-11ea-92ff-d390b8fa1fb3.png)
![Screenshot from 2020-03-10 17-42-02](https://user-images.githubusercontent.com/30832424/76305095-16f7bc80-62f7-11ea-82d6-3bc18a375902.png)

This error happen when we wrap **Link** component around **defaultDom**
![Screenshot from 2020-03-10 17-44-51](https://user-images.githubusercontent.com/30832424/76305117-21b25180-62f7-11ea-939b-14a4fcf8ee0a.png)

**Comment by chenshuai2144** [comment]
antd 的 bug，这周的版本会更新。

**Comment by snowwindsand** [comment]
> I can confim that this bug happen with current "umi-antd-pro" template. Maybe it comes from pro-layout package (antd)
> Inspects:
> ![Screenshot from 2020-03-10 17-39-20](https://user-images.githubusercontent.com/30832424/76305050-047d8300-62f7-11ea-8980-62f0ad007986.png)
> ![Screenshot from 2020-03-10 17-43-04](https://user-images.githubusercontent.com/30832424/76305086-13643580-62f7-11ea-92ff-d390b8fa1fb3.png)
> ![Screenshot from 2020-03-10 17-42-02](https://user-images.githubusercontent.com/30832424/76305095-16f7bc80-62f7-11ea-82d6-3bc18a375902.png)
> 
> This error happen when we wrap **Link** component around **defaultDom**
> ![Screenshot from 2020-03-10 17-44-51](https://user-images.githubusercontent.com/30832424/76305117-21b25180-62f7-11ea-939b-14a4fcf8ee0a.png)

Thanks!

**Comment by snowwindsand** [comment]
> antd 的 bug，这周的版本会修复这个问题。

谢谢！
