### ISSUE TITLE
🧐[问题]ProTable的分页器的下拉选择显示不全

### ISSUE THREAD

**Issue by Mu-xue** [ant-design/ant-design-pro#6096]
### 🧐 问题描述
页面中使用了2个ProTable，第一个的分页器的下拉选择显示不全

### 💻 示例代码

```
<ProTable
   pagination={{
       showQuickJumper: true,
       showSizeChanger: true,
       pageSizeOptions: ['5','10','20'],
       pageSize: 5
    }}
/>
```
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26177732/76302512-18c37f00-62fb-11ea-9fea-e54da95ded7b.png)

**Comment by afc163** [comment]
@chenshuai2144 组件应该避免用 `overflow: hidden`。

之前的 PageHeader 有一样的问题。https://github.com/ant-design/ant-design/pull/22030

**Comment by chenshuai2144** [comment]
这个不是 `overflow: hidden` 引起的，@Mu-xue  方便展示一下你的代码吗？

**Comment by Mu-xue** [comment]
> 这个不是 `overflow: hidden` 引起的，@Mu-xue 方便展示一下你的代码吗？

我2个table都没有修改过样式
```
<ProTable
   style={{ overflow: "auto" }}
/>
当我加上overflow: auto这个问题就解决了
```
![image](https://user-images.githubusercontent.com/26177732/76375644-4b17bf80-6381-11ea-862c-f6f50c0fb113.png)

**Comment by afc163** [comment]
我想当然了。

这个看上去更像是 z-index 问题。

**Comment by chenshuai2144** [comment]
@Mu-xue  试着提升一下zindex 呢，我试了一下不会重叠，你是不是全局有什么样式覆盖

**Comment by Mu-xue** [comment]
没有样式覆盖的，改z-index确实可以，2个ant-pro-table的默认z-index都是1，提升一下第一个表格的z-index就可以
![image](https://user-images.githubusercontent.com/26177732/76480554-f8eea100-6449-11ea-9643-0a2035ea2dcd.png)

**Comment by afc163** [comment]
@chenshuai2144 测试一下两个 Table 放在在一起的情况。

**Comment by chenshuai2144** [comment]
fixed
