### ISSUE TITLE
官方预览网站出现🐛[BUG]

### ISSUE THREAD

**Issue by llh1187** [ant-design/ant-design-pro#6097]
### 🐛 bug 描述
chrome浏览器打开预览页面后出现未知问题

![image](https://user-images.githubusercontent.com/40154001/76311418-de161280-630b-11ea-9ff1-b6d9e2c8c58a.png)

### 📷 复现步骤
chrome浏览器打开https://preview.pro.ant.design/ 进行登录

**Comment by github-ace** [comment]
你这个界面看起来是老版本界面，新版本换了antd4.x

**Comment by llh1187** [comment]
> 你这个界面看起来是老版本界面，新版本换了antd4.x

不知道是哪个版本哦，我是打开https://pro.ant.design/index-cn这个网站之后点击预览的，是官方的网站吧。

**Comment by chenshuai2144** [comment]
估计是缓存了，试着清空一下pwa

**Comment by llh1187** [comment]
> pwa

大佬，您说的是缓存cookie吗？
