### ISSUE TITLE
🧐[问题]import组件时有警告怎么解决？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design-pro#6099]
### 🧐 问题描述
```
import React from 'react';
```
import时有如下警告：
```
Definition for rule '@typescript-eslint/consistent-type-assertions' was not foundeslint(@typescript-eslint/consistent-type-assertions)
```
这该配置什么信息？在网上也没找到响应的方案。

**Comment by afc163** [comment]
https://lmgtfy.com/?q=%40typescript-eslint%2Fconsistent-type-assertions

**Comment by codepandy** [comment]
@afc163 上面链接打不开，能说下怎么解决吗？

**Comment by codepandy** [comment]
@afc163 你上面的链接是乱码啊，是解决方案吗？

**Comment by afc163** [comment]
Google 搜索 `@typescript-eslint/consistent-type-assertions`。

**Comment by chenshuai2144** [comment]
看这里
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-assertions.md
