### ISSUE TITLE
路径去掉#

### ISSUE THREAD

**Issue by jiemo525** [ant-design/ant-design-pro#610]
官方文档是 https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88
但是 尝试了 并没有解决问题  有人成功么 是怎么样解决的

**Comment by chenshuai2144** [comment]
browserHistory 现在还有点问题.
不能用 需要等roadhog 做一些处理

**Comment by jiemo525** [comment]
好的 谢谢
