### ISSUE TITLE
🐛[BUG]IE11 一直停留在加载页面

### ISSUE THREAD

**Issue by fexlab** [ant-design/ant-design-pro#6100]
### 🐛 bug 描述

使用IE11 访问 https://preview.pro.ant.design/ ，一直停留在加载页面，控制台报错。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![6871583895921_ pic_hd](https://user-images.githubusercontent.com/12415273/76378430-4efb1000-6388-11ea-85ce-2b40992f863d.jpg)

**Comment by llh1187** [comment]
https://github.com/ant-design/ant-design-pro/issues/6097
我昨晚报告了，好像还没人跟进。

**Comment by chenshuai2144** [comment]
我的ie 好像没有问题，和版本有关吗？

**Comment by fexlab** [comment]
使用umi创建ant-design-pro工程发现，打包后umi.js中有箭头函数未编译成function函数，导致ie浏览器报错。

umi：3.0.7
antd：4.0.2

config配置：
```
export default defineConfig({
  dva: {
    hmr: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  locale: {
    default: 'zh-CN',
    antd: true,
    title: false,
    baseNavigator: false,
    baseSeparator: '-',
  },
  pwa: false,
  targets: {
    ie: 11
  },
  ignoreMomentLocale: true,
  lessLoader: { javascriptEnabled: true }
}
```

**Comment by chenshuai2144** [comment]
dev 环境有一些debug 用的代码没有编译。
要显示 可以用编译之后通过  serve 来查看。

**Comment by xiaohuoni** [comment]
umi 升级3.0.16。
