### ISSUE TITLE
🧐[问题]Error: Reducer "login" returned undefined during initialization

### ISSUE THREAD

**Issue by jaysg** [ant-design/ant-design-pro#6102]
### 🧐 问题描述
Error: Reducer "login" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined. If you don't want to set a value for this reducer, you can use null instead of undefined.

根据错误提示在model/login里面,并没有发现有赋值为空的情况,

请问为何会报这个错,然后是怎么解决,谢谢

![image](https://user-images.githubusercontent.com/28700250/76392506-a317eb80-63ac-11ea-86cd-d4033e4a23db.png)

**Comment by huntdream** [comment]
Model看起来没什么问题，有导出Model吗? 
`export default Model`
