### ISSUE TITLE
🐛[BUG]叶子菜单-图标和文字没有margin-right属性值，导致两者紧挨着

### ISSUE THREAD

**Issue by Lanboo** [ant-design/ant-design-pro#6103]
### 🐛 bug 描述
如题

![image](https://user-images.githubusercontent.com/19277171/76401619-22adb680-63bd-11ea-9a42-9b2da63492c7.png)

### 📷 复现步骤
更新相关依赖的版本，如下
![image](https://user-images.githubusercontent.com/19277171/76402565-8f758080-63be-11ea-8772-25b7c0d7cc09.png)

目前 https://preview.pro.ant.design 也是这样的，

### © 版本信息

- Ant Design Pro 版本: [4.0.2]
- umi 版本 2.13.0
- 浏览器环境 Chrome
- 开发环境 Windows

**Comment by chenshuai2144** [comment]
antd 新版本的bug，本周的antd 版本会解决
