### ISSUE TITLE
🐛[BUG]更新完4.0之后，菜单内icon错位问题

### ISSUE THREAD

**Issue by github-ace** [ant-design/ant-design-pro#6106]
### 🐛 bug 描述
Menu组件内icon错位，同级菜单有的没有子菜单，无子菜单的可跳转菜单icon样式被覆盖

### 📷 复现步骤
1、按照官网步骤升级4.0，
2、打开antdesignpro，侧边菜单icon错位如图
![image](https://user-images.githubusercontent.com/26371407/76406760-45dc6400-63c5-11ea-8a6e-757961b1f745.png)

### 🏞 期望结果
期望和原来一样，不错位

### 💻 复现代码
[https://stackblitz.com/edit/react-auums6-adndgq](https://stackblitz.com/edit/react-auums6-adndgq)

### © 版本信息

- Ant Design Pro 版本: [2.x]
- umi 版本 2.4.4
- 浏览器环境 chrome79.0.3945.88
- 开发环境 [windows7]

### 🚑 其他信息
antdesignpro 也存在同样问题
![image](https://user-images.githubusercontent.com/26371407/76406989-a2d81a00-63c5-11ea-8fc9-03773a211562.png)
经过对比，是以下样式导致
![image](https://user-images.githubusercontent.com/26371407/76407137-d4e97c00-63c5-11ea-98cb-a4111a9d98fa.png)

**Comment by lsj3210** [comment]
同样问题，期待解决。

**Comment by chenshuai2144** [comment]
antd 的bug，本周antd 发版本就会解决

**Comment by chenshuai2144** [comment]
dup of #6096
