### ISSUE TITLE
🧐[问题] 从后台加载的菜单 icon 的问题

### ISSUE THREAD

**Issue by paulzanmei** [ant-design/ant-design-pro#6107]

**Comment by chenshuai2144** [comment]
看这里相同的issue 很多了
https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon
