### ISSUE TITLE
.roadhogrc.mock.js mock到真实数据

### ISSUE THREAD

**Issue by cfZeng** [ant-design/ant-design-pro#611]
![image](https://user-images.githubusercontent.com/8567216/34660559-3b33678c-f47e-11e7-9703-5b2f08d52c14.png)

这样mock到后端代理能转发走，但是服务端收到的url斜线变成反斜线了，报400
![image](https://user-images.githubusercontent.com/8567216/34660567-5293f810-f47e-11e7-8e84-0d54fcc4ee57.png)
哪里有问题吗？

.webpackrc里proxy直接写就没问题
![image](https://user-images.githubusercontent.com/8567216/34661260-6a24952a-f483-11e7-8023-680cc2053a2d.png)

**Comment by cfZeng** [comment]
@chenshuai2144 有空没，帮忙指教一下

**Comment by chenshuai2144** [comment]
你 翻翻 issue  , 我记得有个一样的 解决了

**Comment by cfZeng** [comment]
看到一个 #194 ，可以做全局的proxy，但是我只需要用部分接口的代理，windows下会变反斜线

**Comment by chenshuai2144** [comment]
提给云谦大大吧 
https://github.com/sorrycc/roadhog/issues

**Comment by gemrabbit** [comment]
Win10系统下用linux bash启动可以

**Comment by cfZeng** [comment]
找到问题了。roadhog里改一笔就ok了。

**Comment by afc163** [comment]
@cfZeng 可以留下具体的改法以方便后面的同学。

**Comment by cfZeng** [comment]
@afc163 已经去roadhog提交给提给云谦大大了，下个版本会修复
目前自己可以修改roadhog工程里src/utils/mock.js#L56
改为:
return winPath(join(url.parse(target).path, matchPath));

**Comment by mushroomlb** [comment]
https://pro.ant.design/docs/mock-api-cn
