### ISSUE TITLE
🧐[问题] cross-env 版本为什么要升到7.0+

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-pro#6111]
### 🧐 问题描述

cross-env 版本为什么要升到7.0+，升到这个版本有node版本要求。然后 之前用的 6.0.3，我感觉和7.0.0在功能上没有任何区别？

```bash
error cross-env@7.0.0: The engine "node" is incompatible with this module. Expected version ">=10.14".
error Found incompatible module
```

出于什么考虑，要合并这个代码？

https://github.com/ant-design/ant-design-pro/pull/5917

能不能改回去？

**Comment by chenshuai2144** [comment]
更新依赖的 pr 只要没报错，我们会尽量升级的。
你升级一下node是最好的办法，不然 jsdom 你也不兼容
