### ISSUE TITLE
antd样式使用异常

### ISSUE THREAD

**Issue by ms20hj** [ant-design/ant-design-pro#6113]
### 🐛 bug 描述
今天刚刚用yarn create umi 构建了项目，启动的时候确实这样子的，

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23376892/76495887-bee5c500-6472-11ea-8841-84bc986b83ea.png)
![image](https://user-images.githubusercontent.com/23376892/76495901-c907c380-6472-11ea-8125-5b535ac2c107.png)

**Comment by chenshuai2144** [comment]
重新安装一下依赖吧，我试了试没问题。看样子是less 没有 build 导致的
