### ISSUE TITLE
🧐[问题]升级到antd4.0之后，如何不把icons打包进去?

### ISSUE THREAD

**Issue by kilik52** [ant-design/ant-design-pro#6116]
### 🧐 问题描述

1. 用yarn create umi新建全新的pro程序。选择使用antd@4。
2. 检查代码，确认没有地方使用import {Icon} from 'antd'。用的都是新的icon调用方式。
3. npm run anaylze. 发现icon还是被打包进去了。

### 🚑 其他信息

<img width="1425" alt="截屏2020-03-12下午6 12 06" src="https://user-images.githubusercontent.com/37238/76510959-62dc6a00-648d-11ea-8afc-fd282a3a554a.png">

**Comment by jing-wu** [comment]
请问是如何解决的？

**Comment by kilik52** [comment]
> 请问是如何解决的？

我发现打包进去的就是新的icon，不是老的。只是还是太大了，没解决。

**Comment by jing-wu** [comment]
好的，多谢

**Comment by flyingFlowers** [comment]
这个问题也遇到了，使用了最新的"antd": "^4.3.0",
发现并没有tree-shaking，icon包的体积还是很大呀
![image](https://user-images.githubusercontent.com/22411463/83491493-70314f80-a4e4-11ea-9e06-81588b8f93f8.png)
