### ISSUE TITLE
🐛[BUG] umijs router push  地址栏 变了。。内容没有刷新

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#6121]
我当前的地址为：
http://localhost:8000/system/member/update/1
我用router.push('/system/member/update/2')
也就是加载ID为2的数据。。
但是界面没变，。也没请求后端数据。。但是地址栏变成了 /system/member/update/2。。
但是内容还是1 的。。

路由是这样设置的。
{
path: "/system/member/update/:id",
name: "修改用户",
component: "./System/Member/MemberInfo"
},

**Comment by liujiayii** [comment]
emmm我也遇到了 感觉是更新了umi那边引起的

**Comment by liujiayii** [comment]
"umi": "2.13.6", "2.13.5", 应该是这两个版本有bug，回滚了就正常了 @chenshuai2144

**Comment by xgj1988** [comment]
@liujiayii  我是   "umi": "^2.4.4",，是不是该升级了。

**Comment by liujiayii** [comment]
> @liujiayii 我是 "umi": "^2.4.4",，是不是该升级了。

你到node_modules里面看看安装的是哪个版本

**Comment by chenshuai2144** [comment]
已经回滚了，非常抱歉大家重新安装一下依赖就好了

**Comment by xgj1988** [comment]
@liujiayii  哎。我先用willprops 监听属性变化 重新 load 了一次数据。。先这样吧

**Comment by chenshuai2144** [comment]
@xgj1988 不要写这种黑科技，以后看到会懵逼的，重新更新依赖即可

**Comment by sorrycc** [comment]
Fixed via umi@2.13.7.
