### ISSUE TITLE
NoticeIcon with Ant design V4 and ant-design-pro 2.3.2

### ISSUE THREAD

**Issue by medoms** [ant-design/ant-design-pro#6129]
Hi there,
first of all thanks for the project.

I am using the NoticeIcon ("ant-design-pro/lib/NoticeIcon") in my ant-design project as separate component. Before version v4 came, it was working properly but now it does not. I am getting a warning and there is no bell icon appearing.

I have checked your ant-desing-pro code and you have updated it with the new way of showing icons. But there is no way to update my ant-design-pro code through npm with the latest version... as the last one is 2.3.2. Also the NoticeIcon is not part of antdesign yet.. 

So I am stuck with this issue because I am getting errors and unable to get the latest NoticeIcon code through NPM or antdesign project.

How should I be proceeding?

Thanks for your time!!!

**Comment by chenshuai2144** [comment]
He has stopped maintaining, and you can support copying code into your project to use it.

code in  https://github.com/ant-design/ant-design-pro/tree/master/src/components/NoticeIcon

**Comment by medoms** [comment]
Thank you @chenshuai2144 .

I did it and have it working in my project.
