### ISSUE TITLE
🐛[BUG] BasicLayouts modifications doesn't take effect in login page

### ISSUE THREAD

**Issue by jimmy-chow** [ant-design/ant-design-pro#6130]
### 🐛 bug 描述

After create an initial project, I modfiy some text in src->layouts->BasicLayouts. 
But it doesn't take effect in the login page.

### 📷 复现步骤

For example, in src->layouts->BasicLayouts, line 41 is modified to

copyright="2020 xxx Inc."

We can see this modification takes effect in welcome page. 

But when you go to the login page, it still shows the txt below in the footer.
Copyright  2019 蚂蚁金服体验技术部出品

All the modifications in BasicLayouts doesn't work in the login page.

### 🏞 期望结果

The modifications in BasicLayouts take effect in all pages.

### © 版本信息

- Ant Design Pro 版本: 4.0.2
- umi 版本: 2.13.0
- 浏览器环境: Chrome
- 开发环境: windows10

### 🚑 其他信息

NA

**Comment by chenshuai2144** [comment]
you should edit https://github.com/ant-design/ant-design-pro/blob/d344356a238bd2fe78ae4de30b5273b8289b98ae/src/layouts/UserLayout.tsx

**Comment by jimmy-chow** [comment]
No, I don't think so.

BasicLayouts includes the header and footer which are used by all the other pages, UserLayout shoud not be an exception.

Meanwhile there is no any code about the copyright in BasicLayouts. How can I modify it?
