### ISSUE TITLE
二级菜单的路由配置怎么都弄不好，打开网页时路由路径正确 ，但就是会跳转到404页面 ，这是为啥？

### ISSUE THREAD

**Issue by zs9720** [ant-design/ant-design-pro#6133]

**Comment by zs9720** [comment]
These relative modules were not found:

* ../../../ListTableList/ProfileAdvanced in ./src/pages/.umi/router.js
* ../../../ListTableList/test2 in ./src/pages/.umi/router.js
这是错误提示

**Comment by chenshuai2144** [comment]
show your code

**Comment by zs9720** [comment]
> show your code



> show your code

his relative module was not found:
../../../groupsin ./src/pages/.umi/router.js
