### ISSUE TITLE
umi-plugin-antd-icon-config有版本区别？

### ISSUE THREAD

**Issue by 81777268** [ant-design/ant-design-pro#6135]
通过yarn 下载的插件umi-plugin-antd-icon-config 里面  patchRoutes方法为
```
function patchRoutes(_ref) {
  var routes = _ref.routes;
  formatter(routes);
}
```
因为_ref获得是config里面配置的路由 routes，该属性的值就是array，没有routes属性，所以会报错；

但是我看antdp官方例子里面引用的umi-plugin-antd-icon-config 插件 里面patchRoutes方法是：
```
function patchRoutes(routes) {
  formatter(routes);
}
```
这样就没问题；

为什么会有两个不同版本呢？  而且公开下载的还是错的；谢谢；

**Comment by 81777268** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
是umi@2 和 umi@3 的造成的。
1.x 版本是umi@2， umi@3 是 2.x

**Comment by 81777268** [comment]
> 是umi@2 和 umi@3 的造成的。
> 1.x 版本是umi@2， umi@3 是 2.x

ok
