### ISSUE TITLE
使用umi3 + antd4后，umi ui 出现兼容错误

### ISSUE THREAD

**Issue by snice** [ant-design/ant-design-pro#6138]
### 🐛 bug 描述

使用umi3 + antd4后，umi ui 出现兼容错误。
错误如下：
 Execute task error: find dependencies conflict between block and your project:* antd: ^4.0.2(your project) not compatible with ^3.23.4(block)

### 📷 复现步骤

1. yarn start
2. 通过umi ui 可视化工具添加区块
3. 提示失败

### 🏞 期望结果

能够正常使用umi ui 辅助工具

### 💻 复现代码

https://github.com/gadmins/admin-react/tree/develop/antd-pro

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本： 3.0.8
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8744870/76693665-ecfe1b80-66a3-11ea-932f-908848f2eace.png)

**Comment by crixusshen** [comment]
当antd官方升级到v4后，使用老版本umi并一直通过umi ui来构建界面模板都出现了一堆版本兼容性问题，建议Umi拉取区块和模板的json资源还是区别v3和v4对待，我们的项目一直使用antd v3，短时间内不可能升级到v4，现在在v3基础上通过umi ui构建，就会一直报pro-table和pro-layout不兼容，升级到了最新发现底层的模板实现已经使用了antd4的实现，这就造成了umi ui在v3上已经无法正常使用了，望antd团队还是考虑下兼容性，毕竟目前的大体量应用还是v3的主战场！

**Comment by ycjcl868** [comment]
antd 区块需要更新了，已经问题
