### ISSUE TITLE
🐛[BUG]umi3不兼容umi ui

### ISSUE THREAD

**Issue by xiao-xiansheng** [ant-design/ant-design-pro#6141]
### 🐛 bug 描述
使用yarn create @umijs/umi-app方式创建项目,然后安装umi ui, 在umirc.ts里配置了dynamicImport和layout, 启动umi ui, umi ui页面是报错
发现umi ui不兼容umi3, 打开配置文件时打开了umi2的配置文件(所在项目是umi3的)

### 📷 复现步骤
1.yarn create @umijs/umi-app安装项目
2.yarn add @umijs/preset-ui -D 安装umi ui
3.修改umirc.ts增加dynamicImport,和layout配置
4.umi ui启动,进入umi ui,导入项目,点击项目列表里面的项目进入,
5.报错

### 🏞 期望结果
能够正常进入

### 💻 复现代码
umirc.ts文件
import { defineConfig } from 'umi';

export default defineConfig({
  dynamicImport: {},
  layout: {
    name: 'Ant Design',
    locale: true,
    title: "个人项目"
  },
  targets: {ie: 6,},
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
});

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.0.8
- 浏览器环境 chrome 80.0.3987.132（正式版本） （64 位）
- 开发环境 [e.g. mac OS] win10

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/22864419/76701641-db496200-66fd-11ea-897a-e7c446a6ade6.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/6178
