### ISSUE TITLE
各位大神，请指教一下ant-design-pro新脚手架，登录页子组件form如何传递到父组件

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6142]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/37643958/76727156-2c089b80-678e-11ea-8bdf-f4c071e1835b.png)
![image](https://user-images.githubusercontent.com/37643958/76727180-46db1000-678e-11ea-83c8-feba401f91c4.png)

**Comment by chenshuai2144** [comment]
通过ref 或者 propsRender 来传输即可

```
const ref = useRef();
formRef={ref}
```

```
let from = null;

ref={(ref)=>from=ref}

```
