### ISSUE TITLE
🐛[BUG]进入页面BasicLayout判断是否登陆，进行跳转报错

### ISSUE THREAD

**Issue by 31ui** [ant-design/ant-design-pro#6143]
### 🐛 bug 描述
layouts>BasicLayout.tsx
`
 useEffect(() => {
    const token=getToken();
    if(!token){
      window.g_app._history.replace('/login');
      return 
    }
  }, []);`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5842559/76744648-8a924180-67af-11ea-8ec6-4802afbac2e7.png)
@ant-design\pro-layout\lib\WrapContent.js
![image](https://user-images.githubusercontent.com/5842559/76744787-c4fbde80-67af-11ea-9984-aa884e9a75a7.png)

**Comment by GuoMouMo** [comment]
先回退umi版本吧，我也碰到这个问题了，固定umi@2.8.7就好了

**Comment by chenshuai2144** [comment]
看样子是Layout 被销毁导致的。可以先忽略，我重写一下这个逻辑
