### ISSUE TITLE
🧐[disableRedirectHoist会不会影响重定向]

### ISSUE THREAD

**Issue by lichangchao15442** [ant-design/ant-design-pro#6144]

**Comment by chenshuai2144** [comment]
可能会但是很难碰到。
disableRedirectHoist 是不把 Redirect 提升到最高优先级，在普通使用中是不会碰到的。

**Comment by lichangchao15442** [comment]
@@我现在使用了disableRedirectHoist后，在config中配置的重定向没有生效，本来应该由'/'重定向到首页，但是路由还是在'/'下面。是缺少什么插件吗？@chenshuai2144

**Comment by lichangchao15442** [comment]
现在突然发现在config.ts中配置的路由的重定向生效了，但是没有找到原因。（不知道为什么之前一直不起作用，是只要在配置路由中配置了重定向就可以使用吗？）
