### ISSUE TITLE
🧐[问题]关于跨组件刷新PRO-TABLE

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design-pro#6146]
### 🧐 问题描述

![微信图片_20200317150804](https://user-images.githubusercontent.com/4537450/76830868-2a5bd800-6861-11ea-9c10-402e30700644.png)
因为在aoeform内保存完数据后要刷新外层列表 那么问题来了   
使用了protable之后   
这种页面结构 如何在aoeform里面拿到 <List>组件内部protable的actionref呢?  

### 💻 示例代码

当然继续使用DataSource也可以 但那样又回到原来的table去了呀

**Comment by chenshuai2144** [comment]
用props 或者 ref 来赋值一下。
如果有这种全局数据的需求，建议还是用 dataSource 的模式，这种复杂数据流 如果传来传去反而不好维护

**Comment by pkaq** [comment]
换了个社区封装的datatable 😂
