### ISSUE TITLE
已经升级了antd4.0 并且项目中更换了dayjs 打包还会有moment???🐛[BUG]

### ISSUE THREAD

**Issue by 81777268** [ant-design/ant-design-pro#6150]
### 🐛 bug 描述

1、antd升级到了4.0；
2、项目中替换了dayjs;

### 📷 复现步骤

```
 mac@localhost  ~/Desktop/optimus   master ●  yarn why moment
yarn why v1.22.0
warning ../../package.json: No license field
[1/4] 🤔  Why do we have the module "moment"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "moment@2.24.0"
info Reasons this module exists
   - "antd" depends on it
   - Hoisted from "antd#moment"
   - Hoisted from "umi-types#@types#moment#moment"
   - Hoisted from "umi-plugin-react#umi-plugin-locale#moment"
   - Hoisted from "umi-plugin-react#antd#moment"
   - Hoisted from "antd#rc-picker#moment"
   - Hoisted from "umi-plugin-react#antd#rc-time-picker#moment"
   - Hoisted from "umi-plugin-react#antd#rc-calendar#moment"
   - Hoisted from "umi#umi-build-dev#write-file-webpack-plugin#moment"
info Disk size without dependencies: "3.48MB"
info Disk size with unique dependencies: "3.48MB"
info Disk size with transitive dependencies: "3.48MB"
info Number of shared dependencies: 0
✨  Done in 1.33s.
```

### 🏞 期望结果

不再有moment

### 💻 复现代码

```
 mac@localhost  ~/Desktop/optimus   master ●  yarn why moment
yarn why v1.22.0
warning ../../package.json: No license field
[1/4] 🤔  Why do we have the module "moment"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "moment@2.24.0"
info Reasons this module exists
   - "antd" depends on it
   - Hoisted from "antd#moment"
   - Hoisted from "umi-types#@types#moment#moment"
   - Hoisted from "umi-plugin-react#umi-plugin-locale#moment"
   - Hoisted from "umi-plugin-react#antd#moment"
   - Hoisted from "antd#rc-picker#moment"
   - Hoisted from "umi-plugin-react#antd#rc-time-picker#moment"
   - Hoisted from "umi-plugin-react#antd#rc-calendar#moment"
   - Hoisted from "umi#umi-build-dev#write-file-webpack-plugin#moment"
info Disk size without dependencies: "3.48MB"
info Disk size with unique dependencies: "3.48MB"
info Disk size with transitive dependencies: "3.48MB"
info Number of shared dependencies: 0
✨  Done in 1.33s.
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26462331/76839998-79116e00-6871-11ea-8922-2e19dfde6aba.png)

**Comment by chenshuai2144** [comment]
是不是还有别的地方引用了moment？

**Comment by 81777268** [comment]
> 是不是还有别的地方引用了moment？
> 
> npm ls 一下

本地肯定没有再用 看起来像是antd里面用到了 或者是umi中有

**Comment by chenshuai2144** [comment]
npm ls 一下
应该不少依赖都用了

**Comment by 81777268** [comment]
> npm ls 一下
> 应该不少依赖都用了

看起来在umi中

**Comment by ling7334** [comment]
├─ @ant-design/pro-table@2.2.1
│  ├─ @ant-design/icons@^4.0.0
│  ├─ antd@^4.0.0
│  ├─ classnames@^2.2.6
│  ├─ dnd-core@^10.0.2
│  ├─ lodash.isequal@^4.5.0
│  ├─ lodash.tonumber@^4.0.3
│  ├─ **`moment@^2.24.0`**
│  ├─ rc-resize-observer@^0.1.3
│  ├─ rc-resize-observer@0.1.3
│  │  ├─ classnames@^2.2.1
│  │  ├─ rc-util@^4.13.0
│  │  └─ resize-observer-polyfill@^1.5.1
│  ├─ rc-util@^4.19.0
│  ├─ react-dnd-html5-backend@^10.0.2
│  ├─ react-dnd@^10.0.2
│  ├─ unstated-next@^1.1.0
│  ├─ use-json-comparison@^1.0.5
│  ├─ use-media-antd-query@1.0.1
│  └─ use-merge-value@^1.0.1
├─ @umijs/plugin-locale@0.4.4
│  ├─ @formatjs/intl-pluralrules@^1.5.0
│  ├─ @formatjs/intl-relativetimeformat@^4.5.7
│  ├─ intl@1.2.5
│  ├─ **`moment@2.x`**
│  ├─ react-intl@3.12.0
│  └─ warning@^4.0.3
├─ antd@4.1.3
│  ├─ @ant-design/icons@^4.0.0
│  ├─ @ant-design/react-slick@~0.25.5
│  ├─ array-tree-filter@^2.1.0
│  ├─ classnames@~2.2.6
│  ├─ copy-to-clipboard@^3.2.0
│  ├─ css-animation@^1.5.0
│  ├─ lodash@^4.17.13
│  ├─ **`moment@^2.24.0`**
├─ rc-picker@1.4.8
│  ├─ classnames@^2.2.1
│  ├─ **`moment@^2.24.0`**
│  ├─ rc-trigger@^4.0.0
│  ├─ rc-util@^4.17.0
│  └─ shallowequal@^1.1.0

**Comment by chenshuai2144** [comment]
生态太多了，估计修不过来
