### ISSUE TITLE
🐛[BUG] Enzyme mount api使用报错

### ISSUE THREAD

**Issue by huang714669** [ant-design/ant-design-pro#6151]
### 🐛 bug 描述
Enzyme mount api使用报错

### 📷 复现步骤

####针对login组件进行简单的单元测试，使用enzyme shallow没问题，但是使用mount就报错
![image](https://user-images.githubusercontent.com/13537904/76915986-187a4380-68fa-11ea-9824-c0092adfbcbb.png)
使用的是最新的默认配置，是否jest或者enzyme配置有问题？
### 🏞 期望结果
可以正常使用enzyme测试react组件
### 💻 复现代码
` /* jshint esversion: 6 */
import React from 'react';
import {shallow, mount} from 'enzyme';
import Login from './index'; 
describe('<Login/>', () => {
    it('renders with UserName and Password', () => {
        const wrapper = mount(
            <Login.WrappedComponent  
                userLogin={{}} 
                submitting={true} 
            />)
        expect(wrapper.find('#userName').length).toBe(1); // 有 UserName 组件
        expect(wrapper.find('#password').prop('name')).toBe('password'); // UserName 组件的类型是成功
        expect(wrapper.find('[className="submit"]').length).toBe(1);
    });
});
`

### © 版本信息

- Ant Design Pro 版本: [4.0.0]，最新代码
- umi 版本
- 浏览器环境
- 开发环境 [ubuntu]

**Comment by huang714669** [comment]
不好意思，为什么插入代码块还是这样，我直接上图把
![image](https://user-images.githubusercontent.com/13537904/76916372-33998300-68fb-11ea-9b36-0041ae77f806.png)

**Comment by chenshuai2144** [comment]
mount 暂时支持不了，要不要试试 e2e 的测试。

**Comment by huang714669** [comment]
e2e也有问题，说是找不到footer，感觉前端单元测试还是主要靠人肉啊 ？

**Comment by chenshuai2144** [comment]
找不到 footer? pro 的测试是没有问题，测试了每个路由

**Comment by GloriaCHL** [comment]
e2e 同找不到footer...特意为测试建了个pro项目的，V5。
使用命令 `npm create umi`
安装完依赖什么都没改连编辑器都没打开，直奔 `npm test`，然后报了下面的错：
![image](https://user-images.githubusercontent.com/10557315/93201421-c076a980-f783-11ea-91ef-acfeac5816fa.png)

**Comment by GloriaCHL** [comment]
e2e我是在本地把项目跑起来才运行成功的...puppeteer需要项目运行在浏览器是前提？但官网上的文档并没有提过这点╮(╯▽╰)╭
