### ISSUE TITLE
🐛登录页子组件form如何传递到父组件

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6153]
### 📷 复现步骤
![image](https://user-images.githubusercontent.com/37643958/76918704-ec62c080-6901-11ea-9ae3-b07c37ec3347.png)
![image](https://user-images.githubusercontent.com/37643958/76918720-f84e8280-6901-11ea-80cb-06ecbc107acc.png)
![image](https://user-images.githubusercontent.com/37643958/76918744-02708100-6902-11ea-952d-f2f74495de7c.png)

**Comment by chenshuai2144** [comment]
按照提示来就好了, React.forwardRef包一下，不然 function 组件是没有 ref 的
```
React.forwardRef(YOUR_Page)
```
