### ISSUE TITLE
🧐[问题]4.0.2版本的表格（table）响应式的问题

### ISSUE THREAD

**Issue by we-coder** [ant-design/ant-design-pro#6154]
### 🧐 问题描述

之前使用4.0.0的版本，进行缩小屏幕至手机大小，表格列表是可以适应屏幕的变化的。但是现在用4.0.2的版本，进行缩小屏幕，表格显示会超出屏幕显示范围，求解决

### 🚑 截图

![image](https://user-images.githubusercontent.com/46117809/76921624-73676700-6909-11ea-8cac-e2eabcfdf72a.png)
![image](https://user-images.githubusercontent.com/46117809/76922724-86c80180-690c-11ea-9bfb-49ff287b3964.png)

**Comment by chenshuai2144** [comment]
有兴趣提供一个可重现版本吗？

**Comment by we-coder** [comment]
不用重现，你现在直接到官网演示的demo进行查看，可以发现问题所在，就是把屏幕缩小到手机大小。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2020年3月18日 18:44
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt;
抄送: we-coder <1799772817@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-pro] 類[问题]4.0.2版本的表格（table）响应式的问题 (#6154)





 
有兴趣提供一个可重现版本吗？

**Comment by loocor** [comment]
> 不用重现，你现在直接到官网演示的demo进行查看，可以发现问题所在，就是把屏幕缩小到手机大小。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 陈帅 <notifications@github.com&gt; 发送时间: 2020年3月18日 18:44 收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt; 抄送: we-coder <1799772817@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[ant-design/ant-design-pro] 類[问题]4.0.2版本的表格（table）响应式的问题 (#6154) 有兴趣提供一个可重现版本吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

设置 scroll={{ x: true }} 可解决

**Comment by we-coder** [comment]
谢谢😊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Loocor <notifications@github.com&gt;
发送时间: 2020年3月19日 17:54
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt;
抄送: we-coder <1799772817@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-pro] 類[问题]4.0.2版本的表格（table）响应式的问题 (#6154)





  
不用重现，你现在直接到官网演示的demo进行查看，可以发现问题所在，就是把屏幕缩小到手机大小。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: 陈帅 <notifications@github.com&gt; 发送时间: 2020年3月18日 18:44 收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt; 抄送: we-coder <1799772817@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[ant-design/ant-design-pro] 類[问题]4.0.2版本的表格（table）响应式的问题 (#6154) 有兴趣提供一个可重现版本吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
设置 scroll={{ x: true }} 可解决

**Comment by xiazefeng** [comment]
当table数据列多一点的时候，慢慢缩小浏览器的宽度，就会发现被后面的列被撑出去了，而且没有滚动轴，导致页面不正常了。
设置下 
.ant-table-body {
  overflow-x: auto;
}
应该比scroll={{ x: true }} 好用一点。
