### ISSUE TITLE
🐛登录成功无法页面跳转

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6156]
### 🐛 登录成功无法页面跳转

![image](https://user-images.githubusercontent.com/37643958/76929434-19719c00-691f-11ea-8242-3ec916a68b34.png)

**Comment by chenshuai2144** [comment]
依赖安装错了？我这边无法再现

**Comment by huntdream** [comment]
dva.router是react-router，应该要用routerRedux吧
![image](https://user-images.githubusercontent.com/7903755/77128230-4bebd800-6a8a-11ea-8c00-a11ee70d1b93.png)
