### ISSUE TITLE
希望react版本支持通过多个tabs来保持打开的页面👑 [需求]

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro#6157]
### 🥰 需求描述

现在的效果是完全单页面的。但是基于pc浏览器的中后台系统普遍使用一个个的tab来保留已经打开的页面，这样有很多优点，包括：用户使用方便，同时已经打开的页面也不需要重新打开等，强烈建议ant design pro支持！

**Comment by afc163** [comment]
Duplicate of #220
