### ISSUE TITLE
更新最新代码后，models路径不支持子目录

### ISSUE THREAD

**Issue by zhengjieyuan** [ant-design/ant-design-pro#616]
今天合并了官方最新代码，router.js文件中的dynamicWrapper路径不支持sys/role写法。之前一直都没这个问题。
const routerConfig = {
    '/': {
      component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    },
    '/dashboard/analysis': {
      component: dynamicWrapper(app, ['chart'], () => import('../routes/Dashboard/Analysis')),
    },
    '/dashboard/monitor': {
      component: dynamicWrapper(app, ['monitor'], () => import('../routes/Dashboard/Monitor')),
    },
    '/dashboard/workplace': {
      component: dynamicWrapper(app, ['project', 'activities', 'chart'], () => import('../routes/Dashboard/Workplace')),
      // hideInBreadcrumb: true,
      // name: '工作台',
      // authority: 'admin',
    },
    '/form/basic-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/BasicForm')),
    },
    '/form/step-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm')),
    },
    '/form/step-form/info': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step1')),
    },
    '/form/step-form/confirm': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step2')),
    },
    '/form/step-form/result': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step3')),
    },
    '/form/advanced-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/AdvancedForm')),
    },
    '/list/table-list': {
      component: dynamicWrapper(app, ['rule'], () => import('../routes/List/TableList')),
    },
    '/list/basic-list': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/BasicList')),
    },
    '/list/card-list': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/CardList')),
    },
    '/list/search': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/List')),
    },
    '/list/search/projects': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Projects')),
    },
    '/list/search/applications': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Applications')),
    },
    '/list/search/articles': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Articles')),
    },
    '/profile/basic': {
      component: dynamicWrapper(app, ['profile'], () => import('../routes/Profile/BasicProfile')),
    },
    '/profile/advanced': {
      component: dynamicWrapper(app, ['profile'], () => import('../routes/Profile/AdvancedProfile')),
    },
    '/result/success': {
      component: dynamicWrapper(app, [], () => import('../routes/Result/Success')),
    },
    '/result/fail': {
      component: dynamicWrapper(app, [], () => import('../routes/Result/Error')),
    },
    '/exception/403': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/403')),
    },
    '/exception/404': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/404')),
    },
    '/exception/500': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/500')),
    },
    '/exception/trigger': {
      component: dynamicWrapper(app, ['error'], () => import('../routes/Exception/triggerException')),
    },
    '/user': {
      component: dynamicWrapper(app, [], () => import('../layouts/UserLayout')),
    },
    '/user/login': {
      component: dynamicWrapper(app, ['login'], () => import('../routes/User/Login')),
    },
    '/user/register': {
      component: dynamicWrapper(app, ['register'], () => import('../routes/User/Register')),
    },
    '/user/register-result': {
      component: dynamicWrapper(app, [], () => import('../routes/User/RegisterResult')),
    },
    # '/sys/user': {
      component: dynamicWrapper(app, ['sys/user'], () => import('../routes/Sys/User/index')),
    },
    '/sys/role': {
      component: dynamicWrapper(app, ['sys/role'], () => import('../routes/Sys/Role/index')),
    },
    '/sys/menu': {
      component: dynamicWrapper(app, ['sys/menu'], () => import('../routes/Sys/Menu/index')),
    },
    '/sys/office': {
      component: dynamicWrapper(app, ['sys/office'], () => import('../routes/Sys/Office/index')),
    },
    '/sys/session': {
      component: dynamicWrapper(app, ['sys/session'], () => import('../routes/Sys/Session/index')),
    },
    '/sys/log': {
      component: dynamicWrapper(app, ['sys/log'], () => import('../routes/Sys/Log/index')),
    },
  };

编译和启动都没错误，启动服务后，打开浏览器访问http://localhost:8000,页面提示：
×
[app.model] namespace should be unique
▶ 4 stack frames were collapsed.
(anonymous function)
D:/react_work/mms-design/src/common/router.js:25
  22 | _models.forEach(function (model) {
  23 |   if (modelNotExisted(app, model)) {
  24 |     // eslint-disable-next-line
> 25 |     app.model(require("../models/".concat(model)).default);
  26 |   }
  27 | });
  28 | 
View compiled
dynamicWrapper
D:/react_work/mms-design/src/common/router.js:22
  19 | // () => require('module')
  20 | // transformed by babel-plugin-dynamic-import-node-sync
  21 | if (_component.toString().indexOf('.then(') < 0) {
> 22 |   _models.forEach(function (model) {
  23 |     if (modelNotExisted(app, model)) {
  24 |       // eslint-disable-next-line
  25 |       app.model(require("../models/".concat(model)).default);
View compiled
getRouterData
D:/react_work/mms-design/src/common/router.js:237
  234 |   })
  235 | },
  236 | '/business/order': {
> 237 |   component: dynamicWrapper(app, ['sys/menu'], function () {
  238 |     return require('../routes/Sys/Menu/index');
  239 |   })
  240 | },
View compiled
RouterConfig
D:/react_work/mms-design/src/router.js:23
  20 | function RouterConfig(_ref) {
  21 |   var history = _ref.history,
  22 |       app = _ref.app;
> 23 |   var routerData = getRouterData(app);
  24 |   var UserLayout = routerData['/user'].component;
  25 |   var BasicLayout = routerData['/'].component;
  26 |   return React.createElement(_LocaleProvider, {
View compiled
▶ 22 stack frames were collapsed.
(anonymous function)
D:/react_work/mms-design/src/index.js:80
  77 | })(); // 5. Start
  78 | 
  79 | 
> 80 | app.start('#root');
  81 | FastClick.attach(document.body);
  82 | 
  83 |

**Comment by chenshuai2144** [comment]
贴出你的配置就好了... 没法看呀 兄弟

**Comment by zhengjieyuan** [comment]
嗯 ，这个是我router.js 文件内容
import { createElement } from 'react';
import dynamic from 'dva/dynamic';
import { getMenuData } from './menu';

let routerDataCache;

const modelNotExisted = (app, model) => (
  // eslint-disable-next-line
  !app._models.some(({ namespace }) => namespace === model)
);

// wrapper of dynamic
const dynamicWrapper = (app, models, component) => {
  // () => require('module')
  // transformed by babel-plugin-dynamic-import-node-sync
  if (component.toString().indexOf('.then(') < 0) {
    models.forEach((model) => {
      if (modelNotExisted(app, model)) {
        // eslint-disable-next-line
        app.model(require(`../models/${model}`).default);
      }
    });
    return (props) => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return createElement(component().default, {
        ...props,
        routerData: routerDataCache,
      });
    };
  }
  // () => import('module')
  return dynamic({
    app,
    models: () => models.filter(
      model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)
    ),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return component().then((raw) => {
        const Component = raw.default || raw;
        return props => createElement(Component, {
          ...props,
          routerData: routerDataCache,
        });
      });
    },
  });
};

function getFlatMenuData(menus) {
  let keys = {};
  menus.forEach((item) => {
    if (item.children) {
      keys[item.path] = { ...item };
      keys = { ...keys, ...getFlatMenuData(item.children) };
    } else {
      keys[item.path] = { ...item };
    }
  });
  return keys;
}

export const getRouterData = (app) => {
  const routerConfig = {
    '/': {
      component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    },
    '/dashboard/analysis': {
      component: dynamicWrapper(app, ['chart'], () => import('../routes/Dashboard/Analysis')),
    },
    '/dashboard/monitor': {
      component: dynamicWrapper(app, ['monitor'], () => import('../routes/Dashboard/Monitor')),
    },
    '/dashboard/workplace': {
      component: dynamicWrapper(app, ['project', 'activities', 'chart'], () => import('../routes/Dashboard/Workplace')),
      // hideInBreadcrumb: true,
      // name: '工作台',
      // authority: 'admin',
    },
    '/form/basic-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/BasicForm')),
    },
    '/form/step-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm')),
    },
    '/form/step-form/info': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step1')),
    },
    '/form/step-form/confirm': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step2')),
    },
    '/form/step-form/result': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step3')),
    },
    '/form/advanced-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/AdvancedForm')),
    },
    '/list/table-list': {
      component: dynamicWrapper(app, ['rule'], () => import('../routes/List/TableList')),
    },
    '/list/basic-list': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/BasicList')),
    },
    '/list/card-list': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/CardList')),
    },
    '/list/search': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/List')),
    },
    '/list/search/projects': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Projects')),
    },
    '/list/search/applications': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Applications')),
    },
    '/list/search/articles': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Articles')),
    },
    '/profile/basic': {
      component: dynamicWrapper(app, ['profile'], () => import('../routes/Profile/BasicProfile')),
    },
    '/profile/advanced': {
      component: dynamicWrapper(app, ['profile'], () => import('../routes/Profile/AdvancedProfile')),
    },
    '/result/success': {
      component: dynamicWrapper(app, [], () => import('../routes/Result/Success')),
    },
    '/result/fail': {
      component: dynamicWrapper(app, [], () => import('../routes/Result/Error')),
    },
    '/exception/403': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/403')),
    },
    '/exception/404': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/404')),
    },
    '/exception/500': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/500')),
    },
    '/exception/trigger': {
      component: dynamicWrapper(app, ['error'], () => import('../routes/Exception/triggerException')),
    },
    '/user': {
      component: dynamicWrapper(app, [], () => import('../layouts/UserLayout')),
    },
    '/user/login': {
      component: dynamicWrapper(app, ['login'], () => import('../routes/User/Login')),
    },
    '/user/register': {
      component: dynamicWrapper(app, ['register'], () => import('../routes/User/Register')),
    },
    '/user/register-result': {
      component: dynamicWrapper(app, [], () => import('../routes/User/RegisterResult')),
    },
    '/sys/log': {
      component: dynamicWrapper(app, ['sys'], () => import('../routes/Sys/Log/index')),
    },
    // '/user/:id': {
    //   component: dynamicWrapper(app, [], () => import('../routes/User/SomeComponent')),
    // },
  };
  // Get name from ./menu.js or just set it in the router data.
  const menuData = getFlatMenuData(getMenuData());
  const routerData = {};
  Object.keys(routerConfig).forEach((item) => {
    const menuItem = menuData[item.replace(/^\//, '')] || {};
    routerData[item] = {
      ...routerConfig[item],
      name: routerConfig[item].name || menuItem.name,
      authority: routerConfig[item].authority || menuItem.authority,
    };
  });
  return routerData;
};
========================================================
启动后浏览器提示
Error: Cannot find module './sys'.
▶ 2 stack frames were collapsed.
(anonymous function)
D:/react_work/mms-design/src/common/router.js:25
  22 | _models.forEach(function (model) {
  23 |   if (modelNotExisted(app, model)) {
  24 |     // eslint-disable-next-line
> 25 |     app.model(require("../models/".concat(model)).default);
  26 |   }
  27 | });
  28 | 
View compiled
dynamicWrapper
D:/react_work/mms-design/src/common/router.js:22
  19 | // () => require('module')
  20 | // transformed by babel-plugin-dynamic-import-node-sync
  21 | if (_component.toString().indexOf('.then(') < 0) {
> 22 |   _models.forEach(function (model) {
  23 |     if (modelNotExisted(app, model)) {
  24 |       // eslint-disable-next-line
  25 |       app.model(require("../models/".concat(model)).default);
View compiled
getRouterData
D:/react_work/mms-design/src/common/router.js:232
  229 |   })
  230 | },
  231 | '/sys/log': {
> 232 |   component: dynamicWrapper(app, ['sys'], function () {
  233 |     return require('../routes/Sys/Log/index');
  234 |   })
  235 | } // '/user/:id': {
View compiled
RouterConfig
D:/react_work/mms-design/src/router.js:23
  20 | function RouterConfig(_ref) {
  21 |   var history = _ref.history,
  22 |       app = _ref.app;
> 23 |   var routerData = getRouterData(app);
  24 |   var UserLayout = routerData['/user'].component;
  25 |   var BasicLayout = routerData['/'].component;
  26 |   return React.createElement(_LocaleProvider, {
View compiled
▶ 22 stack frames were collapsed.
(anonymous function)
D:/react_work/mms-design/src/index.js:80
  77 | })(); // 5. Start
  78 | 
  79 | 
> 80 | app.start('#root');
  81 | FastClick.attach(document.body);
  82 | 
  83 | 
View compiled
▶ 6 stack frames were collapsed.

**Comment by chenshuai2144** [comment]
兄弟 学习一下markdown 语法把,,吓死我了

**Comment by afc163** [comment]
http://segmentfault.com/markdown

**Comment by zhengjieyuan** [comment]
### 提示namespace should be unique错误
------
下载官方最新代码，添加页面做测试，编译和启动没有报错，页面访问提示[app.model] namespace should be unique
##### 操作内容：
> * 下载git最新代码
> * models目录下面创建sys目录，并添加log.js文件（拷贝models/error.js文件内容，修改namespace为sysLog）
> * routes目录下面创建Sys目录，并添加Log.js文件（拷贝routes/Exception/triggerException.js文件内容）
> * 在menu.js和router.js文件中添加访问菜单和路径（只是添加了菜单访问配置，其他代码未修改）。
> * 编译及启动。

### 代码内容：
### 1. models/sys/log.js
```javascript
import { query403, query404, query500 } from '../../services/error';

export default {
  namespace: 'sysLog',

  state: {
    error: '',
    isloading: false,
  },

  effects: {
    *query403(_, { call, put }) {
      yield call(query403);
      yield put({
        type: 'trigger',
        payload: '403',
      });
    },
    *query500(_, { call, put }) {
      yield call(query500);
      yield put({
        type: 'trigger',
        payload: '500',
      });
    },
    *query404(_, { call, put }) {
      yield call(query404);
      yield put({
        type: 'trigger',
        payload: '404',
      });
    },
  },

  reducers: {
    trigger(state, action) {
      return {
        error: action.payload,
      };
    },
  },
};
```


### 2. routes/Sys/Log.js
```javascript
import React, { PureComponent } from 'react';
import { Button, Spin } from 'antd';
import { connect } from 'dva';

@connect(state => ({
  isloading: state.sysLog.isloading,
}))
export default class Log extends PureComponent {
  state={
    isloading: false,
  }
  trigger403 = () => {
    this.setState({
      isloading: true,
    });
    this.props.dispatch({
      type: 'sysLog/query403',
    });
  };
  trigger500 = () => {
    this.setState({
      isloading: true,
    });
    this.props.dispatch({
      type: 'sysLog/query500',
    });
  };
  trigger404 = () => {
    this.setState({
      isloading: true,
    });
    this.props.dispatch({
      type: 'sysLog/query404',
    });
  };
  render() {
    return (
      <Spin spinning={this.state.isloading} >
        <Button type="danger" onClick={this.trigger403}>
          测试model路径问题
        </Button>
      </Spin>
    );
  }
}
```

### 3. common/menu.js 中添加“测试页面”链接
```javascript
const menuData = [{
  name: 'dashboard',
  icon: 'dashboard',
  path: 'dashboard',
  children: [{
    name: '分析页',
    path: 'analysis',
  }, {
    name: '监控页',
    path: 'monitor',
  }, {
    name: '工作台',
    path: 'workplace',
    // hideInMenu: true,
  }],
}, {
  name: '测试页面',
  icon: 'form',
  path: 'sys',
  children: [{
    name: '添加测试',
    path: 'log',
  }],
}, {
  name: '表单页',
  icon: 'form',
  path: 'form',
  children: [{
    name: '基础表单',
    path: 'basic-form',
  }, {
    name: '分步表单',
    path: 'step-form',
  }, {
    name: '高级表单',
    authority: 'admin',
    path: 'advanced-form',
  }],
}, {
  name: '列表页',
  icon: 'table',
  path: 'list',
  children: [{
    name: '查询表格',
    path: 'table-list',
  }, {
    name: '标准列表',
    path: 'basic-list',
  }, {
    name: '卡片列表',
    path: 'card-list',
  }, {
    name: '搜索列表',
    path: 'search',
    children: [{
      name: '搜索列表（文章）',
      path: 'articles',
    }, {
      name: '搜索列表（项目）',
      path: 'projects',
    }, {
      name: '搜索列表（应用）',
      path: 'applications',
    }],
  }],
}, {
  name: '详情页',
  icon: 'profile',
  path: 'profile',
  children: [{
    name: '基础详情页',
    path: 'basic',
  }, {
    name: '高级详情页',
    path: 'advanced',
    authority: 'admin',
  }],
}, {
  name: '结果页',
  icon: 'check-circle-o',
  path: 'result',
  children: [{
    name: '成功',
    path: 'success',
  }, {
    name: '失败',
    path: 'fail',
  }],
}, {
  name: '异常页',
  icon: 'warning',
  path: 'exception',
  children: [{
    name: '403',
    path: '403',
  }, {
    name: '404',
    path: '404',
  }, {
    name: '500',
    path: '500',
  }, {
    name: '触发异常',
    path: 'trigger',
  }],
}, {
  name: '账户',
  icon: 'user',
  path: 'user',
  authority: 'guest',
  children: [{
    name: '登录',
    path: 'login',
  }, {
    name: '注册',
    path: 'register',
  }, {
    name: '注册结果',
    path: 'register-result',
  }],
}, {
  name: '使用文档',
  icon: 'book',
  path: 'http://pro.ant.design/docs/getting-started',
  target: '_blank',
}];

function formatter(data, parentPath = '', parentAuthority) {
  return data.map((item) => {
    const result = {
      ...item,
      path: `${parentPath}${item.path}`,
      authority: item.authority || parentAuthority,
    };
    if (item.children) {
      result.children = formatter(item.children, `${parentPath}${item.path}/`, item.authority);
    }
    return result;
  });
}

export const getMenuData = () => formatter(menuData);

```
### 4. common/router.js 中添加“/sys/log”路径
```javascript
import { createElement } from 'react';
import dynamic from 'dva/dynamic';
import { getMenuData } from './menu';

let routerDataCache;

const modelNotExisted = (app, model) => (
  // eslint-disable-next-line
  !app._models.some(({ namespace }) => namespace === model)
);

// wrapper of dynamic
const dynamicWrapper = (app, models, component) => {
  // () => require('module')
  // transformed by babel-plugin-dynamic-import-node-sync
  if (component.toString().indexOf('.then(') < 0) {
    models.forEach((model) => {
      if (modelNotExisted(app, model)) {
        // eslint-disable-next-line
        app.model(require(`../models/${model}`).default);
      }
    });
    return (props) => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return createElement(component().default, {
        ...props,
        routerData: routerDataCache,
      });
    };
  }
  // () => import('module')
  return dynamic({
    app,
    models: () => models.filter(
      model => modelNotExisted(app, model)).map(m => import(`../models/${m}.js`)
    ),
    // add routerData prop
    component: () => {
      if (!routerDataCache) {
        routerDataCache = getRouterData(app);
      }
      return component().then((raw) => {
        const Component = raw.default || raw;
        return props => createElement(Component, {
          ...props,
          routerData: routerDataCache,
        });
      });
    },
  });
};

function getFlatMenuData(menus) {
  let keys = {};
  menus.forEach((item) => {
    if (item.children) {
      keys[item.path] = { ...item };
      keys = { ...keys, ...getFlatMenuData(item.children) };
    } else {
      keys[item.path] = { ...item };
    }
  });
  return keys;
}

export const getRouterData = (app) => {
  const routerConfig = {
    '/': {
      component: dynamicWrapper(app, ['user', 'login'], () => import('../layouts/BasicLayout')),
    },
    '/dashboard/analysis': {
      component: dynamicWrapper(app, ['chart'], () => import('../routes/Dashboard/Analysis')),
    },
    '/dashboard/monitor': {
      component: dynamicWrapper(app, ['monitor'], () => import('../routes/Dashboard/Monitor')),
    },
    '/dashboard/workplace': {
      component: dynamicWrapper(app, ['project', 'activities', 'chart'], () => import('../routes/Dashboard/Workplace')),
      // hideInBreadcrumb: true,
      // name: '工作台',
      // authority: 'admin',
    },
    '/form/basic-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/BasicForm')),
    },
    '/form/step-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm')),
    },
    '/form/step-form/info': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step1')),
    },
    '/form/step-form/confirm': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step2')),
    },
    '/form/step-form/result': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/StepForm/Step3')),
    },
    '/form/advanced-form': {
      component: dynamicWrapper(app, ['form'], () => import('../routes/Forms/AdvancedForm')),
    },
    '/list/table-list': {
      component: dynamicWrapper(app, ['rule'], () => import('../routes/List/TableList')),
    },
    '/list/basic-list': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/BasicList')),
    },
    '/list/card-list': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/CardList')),
    },
    '/list/search': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/List')),
    },
    '/list/search/projects': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Projects')),
    },
    '/list/search/applications': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Applications')),
    },
    '/list/search/articles': {
      component: dynamicWrapper(app, ['list'], () => import('../routes/List/Articles')),
    },
    '/profile/basic': {
      component: dynamicWrapper(app, ['profile'], () => import('../routes/Profile/BasicProfile')),
    },
    '/profile/advanced': {
      component: dynamicWrapper(app, ['profile'], () => import('../routes/Profile/AdvancedProfile')),
    },
    '/result/success': {
      component: dynamicWrapper(app, [], () => import('../routes/Result/Success')),
    },
    '/result/fail': {
      component: dynamicWrapper(app, [], () => import('../routes/Result/Error')),
    },
    '/exception/403': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/403')),
    },
    '/exception/404': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/404')),
    },
    '/exception/500': {
      component: dynamicWrapper(app, [], () => import('../routes/Exception/500')),
    },
    '/exception/trigger': {
      component: dynamicWrapper(app, ['error'], () => import('../routes/Exception/triggerException')),
    },
    '/user': {
      component: dynamicWrapper(app, [], () => import('../layouts/UserLayout')),
    },
    '/user/login': {
      component: dynamicWrapper(app, ['login'], () => import('../routes/User/Login')),
    },
    '/user/register': {
      component: dynamicWrapper(app, ['register'], () => import('../routes/User/Register')),
    },
    '/user/register-result': {
      component: dynamicWrapper(app, [], () => import('../routes/User/RegisterResult')),
    },
    '/sys/log': {
      component: dynamicWrapper(app, ['sys/log'], () => import('../routes/Sys/Log')),
    },
  };
  // Get name from ./menu.js or just set it in the router data.
  const menuData = getFlatMenuData(getMenuData());
  const routerData = {};
  Object.keys(routerConfig).forEach((item) => {
    const menuItem = menuData[item.replace(/^\//, '')] || {};
    routerData[item] = {
      ...routerConfig[item],
      name: routerConfig[item].name || menuItem.name,
      authority: routerConfig[item].authority || menuItem.authority,
    };
  });
  return routerData;
};

```

### 浏览器打开http://localhost:8000 提示错误：
```javascript
[app.model] namespace should be unique
▶ 4 stack frames were collapsed.
(anonymous function)
D:/temp/ant-design-pro/src/common/router.js:25
      22 | _models.forEach(function (model) {
      23 |   if (modelNotExisted(app, model)) {
      24 |     // eslint-disable-next-line
    > 25 |     app.model(require("../models/".concat(model)).default);
      26 |   }
      27 | });
      28 | 
View compiled
dynamicWrapper
D:/temp/ant-design-pro/src/common/router.js:22
      19 | // () => require('module')
      20 | // transformed by babel-plugin-dynamic-import-node-sync
      21 | if (_component.toString().indexOf('.then(') < 0) {
    > 22 |   _models.forEach(function (model) {
      23 |     if (modelNotExisted(app, model)) {
      24 |       // eslint-disable-next-line
      25 |       app.model(require("../models/".concat(model)).default);
View compiled
getRouterData
D:/temp/ant-design-pro/src/common/router.js:232
      229 |   })
      230 | },
      231 | '/sys/log': {
    > 232 |   component: dynamicWrapper(app, ['sys/log'], function () {
      233 |     return require('../routes/Sys/Log');
      234 |   })
      235 | } // '/user/:id': {
View compiled
(anonymous function)
D:/temp/ant-design-pro/src/common/router.js:31
      28 | 
      29 | return function (props) {
      30 |   if (!routerDataCache) {
    > 31 |     routerDataCache = getRouterData(app);
      32 |   }
      33 | 
      34 |   return createElement(_component().default, _extends({}, props, {
View compiled
▶ 21 stack frames were collapsed.
(anonymous function)
D:/temp/ant-design-pro/src/index.js:80
      77 | })(); // 5. Start
      78 | 
      79 | 
    > 80 | app.start('#root');
      81 | FastClick.attach(document.body);
      82 | 
      83 | 
View compiled
▶ 6 stack frames were collapsed.
```

**Comment by pkaq** [comment]
model的文件名必须与所指定的namespace一致，因为router.js中是通过读取文件名来判断已经注册的model
中是否存在该model的，又由于存在namespace的唯一性约束，所以当两者不一致时无法通过此种方式判断对应文件名的model是否已经注册导致异常

可以修改`modelNotExisted`
```
const modelNotExisted = (app, model) => (
  // eslint-disable-next-line
  !app._models.some(({ namespace }) => {
    return namespace.toLowerCase() === model.substring(model.lastIndexOf('/') + 1).toLowerCase();
  })

);
```

**Comment by pkaq** [comment]
@zhengjieyuan

**Comment by zhengjieyuan** [comment]
谢了 已经解决。我把之前所有model的文件名改成namespace一致的。

**Comment by danyangfaimdata** [comment]
为什么要model文件名跟namepace一样呢？希望能跟antd admin 那样只检测文件名
