### ISSUE TITLE
🧐[问题]关于Authorized组件中CURRENT变量的疑问

### ISSUE THREAD

**Issue by HullQin** [ant-design/ant-design-pro#6161]
### 🧐 问题描述

在`src/utils/Authorized.js`中，引用了组件`@/components/Authorized`，是为了在`setAuthority`时更新组件中的`CURRENT`变量吗？
我是新手，第一次见到这样的代码方式，有点不太懂。
为什么不把`CURRENT`放在model的state中呢~

另外，`pages/Authorized`中的`AuthComponent`，看样子是用来实现这样的组件的：有`props.route`中指定权限的人才能看到的组件。为什么设计时让它属于`pages`呢，感觉这个属于`components`。

还有个小问题，`SecurityLayout`中最后的部分。`loading`是什么呀？
```
export default connect(({ user, loading }) => ({
  currentUser: user.currentUser,
  loading: loading.models.user,
}))(SecurityLayout);
```

谢谢。

**Comment by chenshuai2144** [comment]
loading.models.user 代表的是 model/logon.js 进行的操作，这个是 dva-loading 实现的功能。

pages/Authorized 设计有点问题，
试试 https://umijs.org/plugins/plugin-access

**Comment by HullQin** [comment]
明白了哈~谢谢
