### ISSUE TITLE
🐛[BUG]npm run fetch:blocks,无法安装blocks

### ISSUE THREAD

**Issue by fangaofeng** [ant-design/ant-design-pro#6162]
### 🐛 bug 描述
npm run fetch:blocks,无法安装blocks
执行结果：
√ �🧐  find config.ts ...
�📦  install login  to: /user/login
�👌  install login  to: /user/login success
�📦  install register  to: /user/register
�👌  install register  to: /user/register success
�📦  install register.result  to: /user/register-result
经过几个小时等待，全部提示完成后，发现一个文件都没有新增加。
npm start 提示缺少各种文件。
user/login下没有新增任何文件

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 umi3.0.10
- 浏览器环境
- 开发环境  windows 10

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-cli
打开 debug 看看你少了什么东西吧
