### ISSUE TITLE
🧐[获取系统所有配置的菜单]

### ISSUE THREAD

**Issue by guqidong** [ant-design/ant-design-pro#6164]
### 🧐 问题描述

后端管理系统中，从服务器获取菜单，但在获取菜单之前需要获取到系统配置的所有菜单树，这样可对菜单树进行选择，给角色赋菜单，但是现在不知道怎么获取到配置的所有菜单

**Comment by chenshuai2144** [comment]
可以从 props.router 拿到。umi 会帮你注入。
或者直接读取 config.ts 中的 router 配置。
也可以写插件来实现
