### ISSUE TITLE
👑 [需求]什么时候出umi3.0版的？

### ISSUE THREAD

**Issue by qingbopro** [ant-design/ant-design-pro#6165]
### 🥰 需求描述

什么时候出umi3.0版的？或者说怎么升级

**Comment by loocor** [comment]
参考官方文档已经能正常升级了：

https://umijs.org/zh-CN/guide/upgrade-antd-pro-to-umi-3

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/6178
看这里
