### ISSUE TITLE
暗黑主题下表格的背景依旧为白色

### ISSUE THREAD

**Issue by dreamfinally** [ant-design/ant-design-pro#6166]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/list/table-list?navTheme=realDark&primaryColor=daybreak&fixedHeader=true&fixSiderbar=true](https://preview.pro.ant.design/list/table-list?navTheme=realDark&primaryColor=daybreak&fixedHeader=true&fixSiderbar=true)

### Steps to reproduce
设置=》整体风格设置为暗黑

### What is expected?
表格背景适配为暗黑主题

### What is actually happening?
表格背景为白色

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome 79.0.3945.117 |

**Comment by loocor** [comment]
问题复现 +1

**Comment by chenshuai2144** [comment]
可以使用 yarn upgrade 更新依赖

**Comment by Agr-0Z** [comment]
<img width="1432" alt="Image" src="https://github.com/user-attachments/assets/0fcc82be-d708-4e6d-8c56-c97ee422efad" />
一样的问题 umiMaxV4 antdV5 pro-componentsV2.4.4. 有关antdpro的组件暗色主题都没有生效
