### ISSUE TITLE
为什么pro2的菜单路由代码部分链接的github地址都是404呢  ？

### ISSUE THREAD

**Issue by whl01135020** [ant-design/ant-design-pro#6169]

**Comment by whl01135020** [comment]
v4的文档没有之前的详细了 看完了还是懵

**Comment by afc163** [comment]
具体是哪里，我们改掉。

**Comment by whl01135020** [comment]
![image](https://user-images.githubusercontent.com/20772117/77240274-07de0c00-6c1f-11ea-823c-ce598917b45e.png)

**Comment by whl01135020** [comment]
![image](https://user-images.githubusercontent.com/20772117/77240321-80dd6380-6c1f-11ea-9a12-6a200c1ce420.png)

**Comment by chenshuai2144** [comment]
看样子链接过期了
