### ISSUE TITLE
ant design pro相关，

### ISSUE THREAD

**Issue by qq328180750** [ant-design/ant-design-pro#617]
在BasicLayout中的componentDidMount更新视图导航条的时候会报dynamic component警告，请问该怎样解决呢。

**Comment by chenshuai2144** [comment]
视图导航条?

**Comment by qq328180750** [comment]
@chenshuai2144
 就是更新BasicLayout里面的组件就会报这个警告，componentDidMount里面调用同步操作刷新状态就会报警告，但是原来不使用dynamic的时候就不报警告，

**Comment by chenshuai2144** [comment]
截图一下报错

**Comment by qq328180750** [comment]
![1](https://user-images.githubusercontent.com/33867025/34664633-cd0db068-f497-11e7-93d9-b293738ba3b8.jpg)


![qq 20180108171900](https://user-images.githubusercontent.com/33867025/34664649-e01d1fb8-f497-11e7-93b1-9be33a473917.jpg)
就只是获取了一下当前时间，

**Comment by qq328180750** [comment]
![22](https://user-images.githubusercontent.com/33867025/34664725-29e8e078-f498-11e7-90b2-2c7255ab45be.jpg)
![33](https://user-images.githubusercontent.com/33867025/34664728-2d554b34-f498-11e7-9335-292943fa052a.jpg)
![44](https://user-images.githubusercontent.com/33867025/34664730-300e24a4-f498-11e7-85e9-1fe64c97ee7e.jpg)

**Comment by qq328180750** [comment]
@chenshuai2144  reducers里面的东西感觉被挂起了还是怎么，切换菜单的时候都会都会走一遍

**Comment by chenshuai2144** [comment]
不是报错了?  报错的截图呢?

**Comment by qq328180750** [comment]
![1](https://user-images.githubusercontent.com/33867025/34664913-23d868ec-f499-11e7-90a8-4133950e2f95.jpg)
就是报这个警告...

**Comment by chenshuai2144** [comment]
你是不是componentDidMount中跳转页面什么的?

**Comment by qq328180750** [comment]
@chenshuai2144
就只有这一个操作 调用异步获取了一下时间

**Comment by chenshuai2144** [comment]
你最好拆分一下.  不要异步 或者保存在redux里面 用的时候取.

**Comment by qq328180750** [comment]
@chenshuai2144
感谢，我去修改修改
