### ISSUE TITLE
🧐[问题]  整体风格设置里面没有 官方案例里面的 暗色

### ISSUE THREAD

**Issue by paulzanmei** [ant-design/ant-design-pro#6171]
### 🧐 整体风格设置里面没有 官方案例里面的 暗色

下载完整代码后，没有找到暗色的配置，重官方案例设置好拷贝配置json 进去也不生效

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/dynamic-theme-cn
看看这个文档
