### ISSUE TITLE
翻遍网络，找不到与后台交互时的CRUD功能的实现，希望能提供实例[问题]

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro#6172]
### 🧐 问题描述
pro的代码全都是针对老版本（v3.*或更早）的，但是象Form.create等在v4.*都不能用了，如果要使用pro v4，不清楚后台的MVC各个部分的代码该怎么写，希望能提供一个示例

**Comment by fengnex** [comment]
这个问题很重要，关系到这个工具能否用。。。。。。

**Comment by chenshuai2144** [comment]
尝试执行 `yarn fetch-blocks` 获取所有区块
https://github.com/ant-design/ant-design-pro/blob/master/src/pages/ListTableList/index.tsx
https://github.com/ant-design/pro-blocks
