### ISSUE TITLE
🧐[问题] 关于打包体积优化问题

### ISSUE THREAD

**Issue by xhw0714** [ant-design/ant-design-pro#6173]
### 🧐 问题描述
打包项目后发现pro-layout和icon的体积比较大，请问可以怎么优化

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24238674/77219359-06a1d600-6b70-11ea-8929-6c5e08b885b3.png)

**Comment by chenshuai2144** [comment]
这个大小有点过分我来看看

**Comment by xhw0714** [comment]
> 这个大小有点过分我来看看打包进去了什么

要提供什么给你吗？

**Comment by chenshuai2144** [comment]
给一下你的配置吧，不应该这么大的，你是 import 了别的什么吗

**Comment by xhw0714** [comment]
> 给一下你的配置吧，不应该这么大的，你是 import 了别的什么吗
> 
> ![image](https://user-images.githubusercontent.com/8186664/77304258-216e7900-6d2f-11ea-9dd7-a89c846a280f.png)

升级到antd 4之后pro-layout正常了。icons已改成官方文档的按需引入方式，但还是很大。
![image](https://user-images.githubusercontent.com/24238674/77310635-9c3c9180-6d39-11ea-8f1d-30c756b40200.png)

**Comment by xhw0714** [comment]
`export default {
  antd: {},
  scripts: [
    'https://unpkg.com/react@16.8.6/umd/react.production.min.js',
    'https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js',
    'https://unpkg.com/bizcharts@3.5.5/umd/BizCharts.min.js',
  ],
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    bizcharts: 'BizCharts',
  },
  hash: true,
  targets: {
    ie: 9,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  pwa: false,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': primaryColor,
  },
  define: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION:
      ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION || '', // preview.pro.ant.design only do not use in your production ; preview.pro.ant.design 专用环境变量，请不要在你的项目中使用它。
  },
  ignoreMomentLocale: true,
  lessLoader: { javascriptEnabled: true },
  // disableRedirectHoist: true,
  cssLoader: {
    // 这里的 modules 可以接受 getLocalIdent
    modules: {
      getLocalIdent: (context, _, localName) => {
        if (
          context.resourcePath.includes('node_modules') ||
          context.resourcePath.includes('ant.design.pro.less') ||
          context.resourcePath.includes('global.less')
        ) {
          return localName;
        }
        const match = context.resourcePath.match(/src(.*)/);
        if (match && match[1]) {
          const antdProPath = match[1].replace('.less', '');
          const arr = winPath(antdProPath)
            .split('/')
            .map(a => a.replace(/([A-Z])/g, '-$1'))
            .map(a => a.toLowerCase());
          return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
        }
        return localName;
      },
    },
  },
  manifest: {
    basePath: '/',
  },
  chainWebpack: webpackPlugin,
  proxy: {
    '/api/': {
      target: TARGET,
      changeOrigin: true,
    },
  },
};
`
这个是配置

**Comment by xhw0714** [comment]
```javascript
export default {
  antd: {},
  scripts: [
    'https://unpkg.com/react@16.8.6/umd/react.production.min.js',
    'https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js',
    'https://unpkg.com/bizcharts@3.5.5/umd/BizCharts.min.js',
  ],
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    bizcharts: 'BizCharts',
  },
  hash: true,
  targets: {
    ie: 9,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  pwa: false,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': primaryColor,
  },
  define: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION:
      ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION || '', // preview.pro.ant.design only do not use in your production ; preview.pro.ant.design 专用环境变量，请不要在你的项目中使用它。
  },
  ignoreMomentLocale: true,
  lessLoader: { javascriptEnabled: true },
  // disableRedirectHoist: true,
  cssLoader: {
    // 这里的 modules 可以接受 getLocalIdent
    modules: {
      getLocalIdent: (context, _, localName) => {
        if (
          context.resourcePath.includes('node_modules') ||
          context.resourcePath.includes('ant.design.pro.less') ||
          context.resourcePath.includes('global.less')
        ) {
          return localName;
        }
        const match = context.resourcePath.match(/src(.*)/);
        if (match && match[1]) {
          const antdProPath = match[1].replace('.less', '');
          const arr = winPath(antdProPath)
            .split('/')
            .map(a => a.replace(/([A-Z])/g, '-$1'))
            .map(a => a.toLowerCase());
          return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
        }
        return localName;
      },
    },
  },
  manifest: {
    basePath: '/',
  },
  chainWebpack: webpackPlugin,
  proxy: {
    '/api/': {
      target: TARGET,
      changeOrigin: true,
    },
  },
};

```
这个是配置

**Comment by xhw0714** [comment]
```javascript
export default {
  antd: {},
  scripts: [
    'https://unpkg.com/react@16.8.6/umd/react.production.min.js',
    'https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js',
    'https://unpkg.com/bizcharts@3.5.5/umd/BizCharts.min.js',
  ],
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    bizcharts: 'BizCharts',
  },
  hash: true,
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  pwa: false,
  routes:[],
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': primaryColor,
  },
  define: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION:
      ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION || '', // preview.pro.ant.design only do not use in your production ; preview.pro.ant.design 专用环境变量，请不要在你的项目中使用它。
  },
  ignoreMomentLocale: true,
  lessLoader: { javascriptEnabled: true },
  // disableRedirectHoist: true,
  cssLoader: {
    // 这里的 modules 可以接受 getLocalIdent
    modules: {
      getLocalIdent: (context, _, localName) => {
        if (
          context.resourcePath.includes('node_modules') ||
          context.resourcePath.includes('ant.design.pro.less') ||
          context.resourcePath.includes('global.less')
        ) {
          return localName;
        }
        const match = context.resourcePath.match(/src(.*)/);
        if (match && match[1]) {
          const antdProPath = match[1].replace('.less', '');
          const arr = winPath(antdProPath)
            .split('/')
            .map(a => a.replace(/([A-Z])/g, '-$1'))
            .map(a => a.toLowerCase());
          return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
        }
        return localName;
      },
    },
  },
  manifest: {
    basePath: '/',
  },
  chainWebpack: webpackPlugin,
  proxy: {
    '/api/': {
      target: TARGET,
      changeOrigin: true,
    },
  },
};

```
这个是配置

**Comment by xhw0714** [comment]
```json
"dependencies": {
    "@ant-design/compatible": "^1.0.1",
    "@ant-design/icons": "^4.0.3",
    "@ant-design/pro-layout": "^5.0.6",
    "@antv/data-set": "^0.10.2",
    "@umijs/preset-react": "1.x",
    "antd": "^4.0.3",
    "bizcharts": "^3.5.5",
    "classnames": "^2.2.6",
    "immutability-helper": "^3.0.1",
    "lodash": "^4.17.11",
    "md5": "^2.2.1",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "^3.0.0",
    "qs": "^6.7.0",
    "react": "^16.8.6",
    "react-amap": "^1.2.8",
    "react-canvas-poster": "^1.0.21",
    "react-color": "^2.17.3",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dnd": "^9.3.4",
    "react-dnd-html5-backend": "^9.3.4",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.8.6",
    "react-flv-player": "^1.0.9",
    "react-images": "^1.0.0",
    "redux": "^4.0.1",
    "umi": "^3.0.12",
    "umi-request": "^1.2.19"
  },
  "devDependencies": {
    "@ant-design/colors": "^3.1.0",
    "@ant-design/pro-cli": "^1.0.0",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^24.0.13",
    "@types/lodash": "^4.14.133",
    "@types/md5": "^2.1.33",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.8.19",
    "@types/react-document-title": "^2.0.3",
    "@types/react-dom": "^16.8.4",
    "@umijs/fabric": "^1.1.0",
    "babel-polyfill": "^6.26.0",
    "chalk": "^2.4.2",
    "check-prettier": "^1.0.3",
    "cross-env": "^5.2.0",
    "cross-port-killer": "^1.1.1",
    "enzyme": "^3.9.0",
    "eslint": "^5.16.0",
    "gh-pages": "^2.0.1",
    "husky": "^3.0.0",
    "import-sort-cli": "^6.0.0",
    "import-sort-parser-babylon": "^6.0.0",
    "import-sort-parser-typescript": "^6.0.0",
    "import-sort-style-module": "^6.0.0",
    "jest-puppeteer": "^4.2.0",
    "lint-staged": "^9.0.0",
    "mockjs": "^1.0.1-beta3",
    "node-fetch": "^2.6.0",
    "prettier": "^1.17.1",
    "pro-download": "1.0.1",
    "slash2": "^2.0.0",
    "stylelint": "^10.1.0",
    "umi-plugin-antd-icon-config": "^2.0.0",
    "webpack-theme-color-replacer": "^1.2.15"
  },
```
这是依赖

**Comment by qiqizjl** [comment]
测试发现如果引入``umi-plugin-antd-icon-config``就会把整个icon打进去 是否和这个包存在关系？

**Comment by chenshuai2144** [comment]
是的 
umi-plugin-antd-icon-config 会全量引入，代码没写好，最近会更新一下插件。

**Comment by joesdu** [comment]
我觉得你这个还好,我用到了图表,那个@antv/data-set的库占了我所有大小的一半.
![image](https://user-images.githubusercontent.com/13188169/78149815-ff7ca100-7468-11ea-92cb-0e6292b65ee1.png)

**Comment by klzen** [comment]
使用ant-desgin-pro模板,添加了分析页面和一个查询表格,在查询表格里加了几个图标后,我的情况更糟.
使用umi进行新项目,引入图标是没有问题的.是不是ant-design-pro的构建里,需要什么额外的操作?
<img width="1440" alt="截屏2020-04-04 下午4 55 17" src="https://user-images.githubusercontent.com/2476288/78422946-8d3cd400-7695-11ea-8244-168a3e40adaf.png">

**Comment by chenshuai2144** [comment]
close by https://github.com/umijs/umi-plugin-antd-icon-config/pull/10/

**Comment by klzen** [comment]
@chenshuai2144 更新后问题得到了很好的解决.十分感谢!

**Comment by dyyliao123** [comment]
> close by [umijs/umi-plugin-antd-icon-config#10](https://github.com/umijs/umi-plugin-antd-icon-config/pull/10)
更新哪个插件，能解决这个问题啊

**Comment by xhw0714** [comment]
> > close by [umijs/umi-plugin-antd-icon-config#10](https://github.com/umijs/umi-plugin-antd-icon-config/pull/10)
> > 更新哪个插件，能解决这个问题啊

4.x后升级@ant-design/pro-layout能解决pro-layout体积问题，升级umi-plugin-antd-icon-config能解决icon体积问题

**Comment by dyyliao123** [comment]
谢谢，下午试了，已经ok了

**Comment by jing-wu** [comment]
umi@2.13.13，使用 umi-plugin-antd-icon-config@1.0.3，icons还是在打包文件里

去掉这个插件后，打包体积反而小了

**Comment by jing-wu** [comment]
有大佬处理下吗？解决下插件在 umi@2.x 下的问题

**Comment by zoeykk** [comment]
V5版本的umi-plugin-antd-icon-config怎么升级

**Comment by KingThq** [comment]
umi@2.x版本，升级插件运行 npm run analyze 会报错

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/126613920-f3a671fb-bd31-4070-98e7-970af31e45f0.png)
升级 umi-plugin-antd-icon-config  2.0.4 版本   报错了，怎么处理

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/126613920-f3a671fb-bd31-4070-98e7-970af31e45f0.png)
升级 umi-plugin-antd-icon-config  2.0.4 版本   报错了，怎么处理

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/126613920-f3a671fb-bd31-4070-98e7-970af31e45f0.png)
升级 umi-plugin-antd-icon-config  2.0.4 版本   报错了，怎么处理

**Comment by chenshuai2144** [comment]
这个是重复注册，是安装在了package.json里面了吗
