### ISSUE TITLE
🧐[问题]升级umi3后run出错

### ISSUE THREAD

**Issue by carlchou** [ant-design/ant-design-pro#6174]
### 🧐 问题描述
按umi升级antd pro项目到umi@3的文档操作后，npm run start出错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8382278/77220164-69976b00-6b78-11ea-8254-274e625401f9.png)
![image](https://user-images.githubusercontent.com/8382278/77220174-7c11a480-6b78-11ea-96e9-d6c5ff393522.png)
![image](https://user-images.githubusercontent.com/8382278/77220177-816eef00-6b78-11ea-9dfb-60fed1acfcf5.png)

**Comment by chenshuai2144** [comment]
来个仓库吧，没看出来问题

**Comment by carlchou** [comment]
删除node_modules及package-lock重装就好了，谢谢
