### ISSUE TITLE
升级4.0 后menu 数据从后台获取 ICON 不显示

### ISSUE THREAD

**Issue by YUANZHICHENG118** [ant-design/ant-design-pro#6175]
menu 从数据库获取到 数据 格式：{"id":1000,"parentId":-1,"children":[{"id":1100,"parentId":1000,"children":[],"icon":"dashboard", ... 显示不出来
![image](https://user-images.githubusercontent.com/15242802/77223668-af186000-6b99-11ea-81f5-d2983cffceb9.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/blog/antd-4.0-cn#-%E4%B8%80%E4%B8%AA%E9%A2%84%E5%91%8A
看这个文章，里面讲了相关的问题
