### ISSUE TITLE
Pie 的data部分的min-width如何调整

### ISSUE THREAD

**Issue by afeiluo** [ant-design/ant-design-pro#6180]
![image](https://user-images.githubusercontent.com/6848479/77281352-c6725d00-6d01-11ea-8981-13b6deb7ce0b.png)
后面的数字太长导致和 data 的百分比重合了

**Comment by chenshuai2144** [comment]
去这里问问？
Pie 好像能 fromat 一下

**Comment by wangligit** [comment]
> ![image](https://user-images.githubusercontent.com/6848479/77281352-c6725d00-6d01-11ea-8981-13b6deb7ce0b.png)
> 后面的数字太长导致和 data 的百分比重合了

遇到相同的问题，请问你怎么解决的？
