### ISSUE TITLE
🧐[问题]刚看了Use Umi3的提交变更,为什么都用了Umi3却没有用Umi3的权限等插件

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6183]
### 🧐 问题描述

刚看了Use Umi3的提交变更,为什么都用了Umi3却没有用Umi3的plugin-access,plugin-layout,以及plugin-initial-state,plugin-local等插件来实现,还是用的以前的实现方式.

**Comment by joesdu** [comment]
等官方升级就是希望,官方能调整为Umi3插件的方式来实现.希望后期能调整一下.

**Comment by joesdu** [comment]
个人觉得ant pro这个模板项目就应该是跟随Umi版本更新,采用全新的实现方式,即使是新开一个项目也行.

**Comment by chenshuai2144** [comment]
umi@3 是底层。plugin-access,plugin-layout 这些是最佳实践
普通用户需要很复杂的操作的升级，会提升了 pro 的版本。
预计会在 4 月发布

**Comment by joesdu** [comment]
> umi@3 是底层。plugin-access,plugin-layout 这些是最佳实践
> 普通用户需要很复杂的操作的升级，会提升了 pro 的版本。
> 预计会在 4 月发布

感谢大佬支持.
