### ISSUE TITLE
🧐[问题]使用umi2.x，antd4.x(umi ui创建的最新项目),当把菜单和路由分开的话，菜单数据中的icon属性依然不生效，显示的字符串

### ISSUE THREAD

**Issue by sorryljt** [ant-design/ant-design-pro#6185]
### 🧐 问题描述
如题，我在项目的项目是使用的umi2.13.antd4，项目中已经配置`umi-plugin-antd-icon-config`插件，在配置式路由，菜单和路由耦合的情况下，配置中的`icon:string`能够被渲染为对应的图标，但是将菜单数据和路由配置分开设置的时候，菜单数据中的icon属性又不生效了，请问这是bug吗？还是我用的不合理？

### 💻 示例代码
```
const menuData = [
  {
    "path": "/systemadmin",
    "name": "系统设置",
    "icon": "CaretLeftOutlined",
    "routes": [
      {
        "path": "/systemadmin/dictionary",
        "name": "字典管理"
      },
    ]
  },
  {
    "path": "/deviceadmin",
    "name": "设备管理",
    "icon": "CaretLeftOutlined",
    "routes": [
      {
        "path": "/deviceadmin/vfsfence",
        "name": "围栏管理"
      },
    ]
  }
]
.....
menuDataRender={() => menuData}//这是ProLayout中的配置改变。
```

**Comment by chenshuai2144** [comment]
umi-plugin-antd-icon-config 只能解决 config 的中 icon 问题，menuData 是你给的，你直接将其转化了 reactNode 就好了。

这里有个 demo

**Comment by sorryljt** [comment]
不好意思，没有看到demo啊，能不能给个链接呢？

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon
看这里

**Comment by xgj1988** [comment]
感觉好不方便了

**Comment by BluesVN** [comment]
这样的话IconMap要提前在前端静态的写好了 有没有更好的办法
