### ISSUE TITLE
Ant Design Pro Preview - "dark style" / "dark theme" issues 🐛[BUG]

### ISSUE THREAD

**Issue by scouttyg** [ant-design/ant-design-pro#6186]
### 🐛 bug 描述
I'm not sure if this is an issue with https://github.com/ant-design/ant-design-dark-theme or with this repository, but on several places on the [preview site](https://preview.pro.ant.design/) the "dark style" / "dark theme" used does not render elements correctly.

Here's some basic things I found:

#### Navbar
1. "World dropdown" wrong background & font colors:
<img width="306" alt="World dropdown navbar wrong colors" src="https://user-images.githubusercontent.com/463175/77363250-c6d21e80-6d28-11ea-8cad-0e38fff9b082.png">

2. "Profile Icon dropdown" wrong background & font colors:
<img width="247" alt="Profile image dropdown wrong colors" src="https://user-images.githubusercontent.com/463175/77363285-d6e9fe00-6d28-11ea-9aaf-8bc3426d61c0.png">

#### Settings / Gear Sidebar
1. Inside styling more "dark" than the outside styling, making it look weird:
<img width="338" alt="Sidebar inside styling dark" src="https://user-images.githubusercontent.com/463175/77363462-26302e80-6d29-11ea-8fd8-5969d16f8814.png">

#### Search Table (https://preview.pro.ant.design/list/table-list)
1. Table head column shows wrong color on hover
2. Table row shows wrong color (should be dark?)

<img width="1660" alt="Search table colors and tr highlighting" src="https://user-images.githubusercontent.com/463175/77363697-8de67980-6d29-11ea-82a5-620665a537af.png">

#### Basic Profile (https://preview.pro.ant.design/profile/basic)
1. Table row shows wrong color (should be dark) -- same as mentioned above
<img width="1662" alt="Basic profile table white" src="https://user-images.githubusercontent.com/463175/77363868-ddc54080-6d29-11ea-8905-3f352bed3a40.png">

#### Card List (https://preview.pro.ant.design/list/card-list)
1. Card hover disappears border of card:

![hover-on-card-removes-border](https://user-images.githubusercontent.com/463175/77363880-e3228b00-6d29-11ea-81dd-ca252ad6ecd3.gif)

#### Account Center (https://preview.pro.ant.design/account/center)
1. Image icons (briefcase / sitemap / map marker) in profile aren't transparent, and so they don't blend in with background theme
2. Tag input section colored wrong (white instead of dark)
 
<img width="1877" alt="account center images white and label:tags white" src="https://user-images.githubusercontent.com/463175/77364127-4dd3c680-6d2a-11ea-84e3-8ee98f0dbce6.png">

### 📷 复现步骤
- Go to https://preview.pro.ant.design/
- Click the gear on the right hand side
- Choose "Dark style" under "Page style setting"
- Navigate to the areas / urls I mention in the screenshots above

**Comment by scouttyg** [comment]
Few other places I found:

#### Dashboard Monitor Page (https://preview.pro.ant.design/dashboard/monitor)
1. Hover tooltip has white text
<img width="1247" alt="hover-github-map-dashboard-monitor-page" src="https://user-images.githubusercontent.com/463175/77433192-7785ff80-6db5-11ea-945c-7af97ee7470b.png">

#### Editor Pages (any, but example: https://preview.pro.ant.design/editor/koni)
1. Canvas text white when should be dark (I highlighted it to show it's there)
<img width="1662" alt="editor-not-overriding-styles-for-canvas" src="https://user-images.githubusercontent.com/463175/77433297-9a181880-6db5-11ea-815b-6572e3699ac0.png">

cc @chenshuai2144 , I know he's worked on a good amount of the dark theme for https://github.com/ant-design/ant-design-dark-theme

**Comment by chenshuai2144** [comment]
I will solve these problems step by step. Thank you very much for your arrangement

**Comment by chenshuai2144** [comment]
- [ ] "World dropdown" wrong background & font colors
- [ ] "Profile Icon dropdown" wrong background & font colors
- [ ] Inside styling more "dark" than the outside styling
- [ ] Card hover disappears border of card
- [ ] Tag input section colored wrong (white instead of dark)
- [ ] Image icons (briefcase / sitemap / map marker) in profile aren't transparent, and so they don't blend in with background theme
- [ ] Hover tooltip has white text
- [ ] 
- [ ] Canvas text white when should be dark (I highlighted it to show it's there)
- [ ]

**Comment by scouttyg** [comment]
Hey @chenshuai2144,

I've been checking out the progress and have been really loving the changes! Few things extra I found based on the latest changes on https://preview.pro.ant.design/:

### Mind Editor (https://preview.pro.ant.design/editor/mind)
Looks like the text just is still dark here, when it should be light:

<img width="1920" alt="Screen Shot 2020-04-07 at 5 40 29 PM" src="https://user-images.githubusercontent.com/463175/78722555-b9578f80-78f7-11ea-9b5e-3dde5029707d.png">

### Setting panel - Inside styling more "dark" than the outside styling (clarification)
This one I mentioned before, but just to make sure I'm clear, I tried to point out exactly what I'm talking about:

<img width="402" alt="Screen Shot 2020-04-07 at 5 41 39 PM" src="https://user-images.githubusercontent.com/463175/78722607-db511200-78f7-11ea-80e2-9670bf844d51.png">

Basically, there's a padding of a lighter black around the darker black in the Settings side panel, and it looks kind of odd, especially when near text, and near things like the "x" in the top right corner.

### Settings panel - "Dark style" mentioned twice
Quick gif to explain:

![dark-theme-twice](https://user-images.githubusercontent.com/463175/78722702-0a678380-78f8-11ea-934d-59ed89f618bd.gif)

In the settings sidebar, the right two themes are both called "dark style", even though really the differentiation should maybe be "dark sidebar" and "dark".

### Settings panel - clicking theme changes url, but does not persist on reload:

Another quick gif to explain:
![dark-theme-not saving-on-refresh](https://user-images.githubusercontent.com/463175/78722825-413d9980-78f8-11ea-8cb9-adbf0edf2d42.gif)

Basically, if you load the page in the normal theme, and change the theme to something like "dark style", the url changes to:

https://preview.pro.ant.design/dashboard/analysis?navTheme=realDark&primaryColor=daybreak

I'd expect the `navTheme=realDark&primaryColor=daybreak` params to mean that the theme would load and persist when refreshing that url, but that doesn't seem to be the case.

### Overall
Just want to say I really appreciate you listening to my feedback! Hope you are having a great week ❤️

**Comment by chenshuai2144** [comment]
Providing useful suggestions is very helpful for open source projects
❤️

**Comment by scouttyg** [comment]
@chenshuai2144 Possible new regressions?

<img width="1920" alt="Screen Shot 2020-06-08 at 9 25 14 AM" src="https://user-images.githubusercontent.com/463175/84035745-3770fa80-a96a-11ea-8678-d278828f0205.png">

**Comment by chenshuai2144** [comment]
new version  will change this style
