### ISSUE TITLE
🧐[问题]nginx配置成https时，下载xls会跳转到项目根目录html文件

### ISSUE THREAD

**Issue by sunfutao** [ant-design/ant-design-pro#6187]
### 🧐 问题描述
项目使用nginx反代到后端，http和https时都可以正常访问，但是在https时下载文件或者跳转页面（a标签、location.href）时，页面就会跳到项目根目录，而http不会发生这种情况。
和[这位同学](https://github.com/ant-design/ant-design-pro/issues/6120#issue-580436048)一样的问题，nginx的配置也基本一致，但是按照官方的说法分开配置http和https并没有效果。

**Comment by chenshuai2144** [comment]
搜一下历史 issue
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon

**Comment by sunfutao** [comment]
> 搜一下历史 issue
> https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon

没有搜到相关的issue,[这个issue](https://github.com/ant-design/ant-design-pro/issues/6120)的解决方案也没用

**Comment by chenshuai2144** [comment]
你是使用了 tryfile吧，如果404 就会返回 html本身

**Comment by sunfutao** [comment]
> 你是使用了 tryfile吧，如果404 就会返回 html本身
但是http下载文件可以成功，https就会返回html本身。我刚刚尝试删除了所有tryfile,http情况下返回了404，https依然返回html本身。觉得可能是umi路由有问题

**Comment by chenshuai2144** [comment]
umi 的路由不会影响到 nginx 的，umi 只是个 js 而已。
你看看是不是别的地方还写了配置文件
