### ISSUE TITLE
👑 请问各位大神，作者能不能建个ant-design-pro社区技术沟通交流钉钉群或者微信群啊？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6189]

**Comment by fengnex** [comment]
建议QQ群，因为可以长期保存文件

**Comment by shaohuatsou** [comment]
有钉钉群的呀

**Comment by zhaoxiaobao** [comment]
antd微信群，之前没有找到，拉了一个antd微信交流群，有需要的入。
![20200408180124.png](https://oss.jkxcx.xyz/pics/20200408180124_PS4yJA_20200408180124.png)

**Comment by shaohuatsou** [comment]
> antd微信群，之前没有找到，拉了一个antd微信交流群，有需要的入。
> ![20200408180124.png](https://camo.githubusercontent.com/7e6e9d70227b450feb58b03f9238d7fe36cd7b45/68747470733a2f2f6f73732e6a6b7863782e78797a2f706963732f32303230303430383138303132345f505334794a415f32303230303430383138303132342e706e67)

看不到图

**Comment by xiaohuoni** [comment]
“Ant Design 提问要给在线重现不给重现解决效率会降低而且很可能无法解决”群的钉钉群号： 11722346
