### ISSUE TITLE
关于在router中调取不同model中接口的问题

### ISSUE THREAD

**Issue by myyyy** [ant-design/ant-design-pro#619]
文件夹(model)：A.js，B.js
文件夹(router)：A.js

在router->A.js中通过
```
  componentDidMount() {
    this.props.dispatch({
      type: 'a/fetch',
      payload: {
        count: 8,
      },
    });
  }
```
我可以拿到 model->A.js 中 fetch 方法的数据(这个已经拿到)，
**那么** 我在 **router->A.js** 中怎么 通过调用 调取 **model->B.js**中的fetch方法呢？
我看了一下，在nav.js 中 这段代码
```
const dynamicWrapper = (app, models, component) => dynamic({
  app,
  models: () => models.map(m => import(`../models/${m}.js`)),
  component,
});
```
限制了 只能在同名文件中调用。
问下各位大神 我的这个问题有解决的方案吗，

**Comment by chenshuai2144** [comment]
额  去dva'看看怎么绑定model吧

**Comment by WhatAKitty** [comment]
@myyyy 
```
['path/to/subdir/model']
```

**Comment by myyyy** [comment]
@chenshuai2144 @WhatAKitty  感谢大佬 已经解决 方法如下
      {
        name: 'A',
        path: 'a',
        icon: 'file',
        component: dynamicWrapper(app, ['A','B'], () => import('../routes/A/A')),
      },
