### ISSUE TITLE
🧐[问题] 无法安装使用 `path-to-regexp@6.1.0`

### ISSUE THREAD

**Issue by zpr1g** [ant-design/ant-design-pro#6190]
### 🧐 问题描述

默认依赖版本为 `path-to-regexp@2.4.0` ，由于需要用到其中的 `match` 方法，所以需要使用新版本的依赖，`cnpm i -S path-to-regexp@latest` 后发现无法正常使用 6.1.0 的依赖，打印依赖结构：

```
// 无 match 方法
{parse: ƒ, compile: ƒ, tokensToFunction: ƒ, tokensToRegExp: ƒ, default: ƒ}
```

移除 `node_modules` 重新安装，依然无法使用。

**Comment by chenshuai2144** [comment]
包括 react-router 在内的生态 使用的 path-to-regexp 的版本都在 2.x 或者 1.x
你要使用 6.0 可能有点难度

**Comment by zpr1g** [comment]
我也试过用别名的方式 [Two versions of same npm package in Node application](https://stackoverflow.com/questions/43770328/two-versions-of-same-npm-package-in-node-application) 几经折腾终于用 yarn 装上了 `"path-to-regexp-v6": "npm:path-to-regexp@6.1.0"` ，但是引入使用却是 `undefined` 。有点难度是还是能搞的意思？

现在是直接复制 6.1.0 的源码放到本地临时解决的 :joy: 另外因为这个问题我对 node 的引包逻辑又懵了。

**Comment by chenshuai2144** [comment]
不是 node 干的，是 webpack 干的，你可以发个 6.x 的包，自己玩玩这样最简单

**Comment by zpr1g** [comment]
fork 下来再发一个包这个思路可以啊 :joy: 不过这个包就一个文件，不去麻烦了，直接复制源码吧。

有空再研究下 webpack 的引包逻辑。多谢指路。
