### ISSUE TITLE
👑 [需求]建议将AntD的Column的render函数参数调整为Object

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6191]
### 🥰 需求描述

如图所示,大部分时间使用render的时候都是根据record的内容定义渲染.这个时候无需text参数,但是不写text又不行,这个时候每次写text很麻烦,并且VS Code会提示未使用.建议将3个参数调整为JSON,由JSON结构赋值就可以避免这种问题.
![image](https://user-images.githubusercontent.com/13188169/77384583-bbcacd00-6dc0-11ea-972b-b1df8823900d.png)

**Comment by afc163** [comment]
```diff
- render: (text, record) => {
+ render: (_, record) => {
```
