### ISSUE TITLE
🧐[问题] 示例中有一行代码疑似有误

### ISSUE THREAD

**Issue by tongkunLiu** [ant-design/ant-design-pro#6192]
代码位置：ant-design-pro/src/pages/ListTableList/index.tsx 第202行

下面代码中的 handleModalVisible 是否应为 handleUpdateModalVisible

<UpdateForm
          onSubmit={async (value) => {
            const success = await handleUpdate(value);
            if (success) {
             **handleModalVisible(false);**
              setStepFormValues({});
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          onCancel={() => {
            **handleUpdateModalVisible(false);**
            setStepFormValues({});
          }}
          updateModalVisible={updateModalVisible}
          values={stepFormValues}
        />

**Comment by chenshuai2144** [comment]
直接来提 pr 吧
