### ISSUE TITLE
🐛[BUG]umi3.0.13多语言报错

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6193]
### 🐛 bug 描述
![QQ浏览器截图20200324131939](https://user-images.githubusercontent.com/3166799/77390905-54b61400-6dd2-11ea-887c-1408412df350.png)
![QQ浏览器截图20200324131952](https://user-images.githubusercontent.com/3166799/77390912-567fd780-6dd2-11ea-8c0e-9b8f75b20d38.png)

### © 版本信息

- Ant Design Pro 版本: 4.0.4
- umi 版本 3.0.13
- 浏览器环境 Chrome80
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不要在 class 里面使用hooks。

你可以用  injectIntl,

```
class Page extends React.Compent<{  intl:  intlStore },{}>{
   render(){
     console.log(this.props)
   }
}

injectIntl(Page )
```
