### ISSUE TITLE
怎么在执行npm start的时候，自动lint 🧐[问题]

### ISSUE THREAD

**Issue by lawrsp** [ant-design/ant-design-pro#6194]
### 🧐 问题描述
之前一直用create-react-app，
在npm start的时候会自动lint，看到所有的错误，
antd pro  有没有这个功能？

**Comment by xrkffgg** [comment]
可以自己在项目中修改 package.json 中的 
start  加上你想要的命令呀

**Comment by lawrsp** [comment]
不是就那一下，修改后自动重编译的时候也需要

**Comment by xrkffgg** [comment]
修改后，IDE 应该有提示吧。
VSCode 装个 ESLint

**Comment by lawrsp** [comment]
还有不是自己改的，主要是不想强制用pre-commit检查
一般是隔一段时间，清理一次
找到了方法，手动配eslint-loader

**Comment by xrkffgg** [comment]
👍👍👍

**Comment by JanssenZhang** [comment]
> 还有不是自己改的，主要是不想强制用pre-commit检查
> 一般是隔一段时间，清理一次
> 找到了方法，手动配eslint-loader

请问一下，怎么配置的eslint-loader？
