### ISSUE TITLE
🐛[BUG]umi ui blocks不显示

### ISSUE THREAD

**Issue by tailang** [ant-design/ant-design-pro#6195]
### 🐛 bug 描述
umi ui blocks选择区域没有可用的block，但是终端显示json请求成功
```bash
find block list form https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.json
```

疑惑点：这个问题从3月23日开始出现，之前没有问题

![截屏2020-03-24下午5 24 58](https://user-images.githubusercontent.com/3025182/77409552-67d9db80-6df4-11ea-8169-94e402311dcb.png)
### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本 2.13.7
- 浏览器环境 Google Chrome 已是最新版本
版本 80.0.3987.149（正式版本） （64 位）
- 开发环境  mac OS

**Comment by tailang** [comment]
![截屏2020-03-24下午6 27 14](https://user-images.githubusercontent.com/3025182/77415214-197d0a80-6dfd-11ea-827c-c15251fa4535.png)

**Comment by nspers** [comment]
昨天下午开始 我的也这样了... 咋弄

**Comment by Ma2k** [comment]
我也是这个问题，而且目前重新安装的环境下，package.json 下已经没有 ui 的script了，不知道为什么

**Comment by lxie018** [comment]
＠ant-design

**Comment by chenshuai2144** [comment]
@ycjcl868  来看看我也复现了

**Comment by ycjcl868** [comment]
![Uploading image.png…]()


神奇，为啥我这复现不了

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/77619307-eb213b80-6f72-11ea-8c24-45142e3eac68.png)

**Comment by ycjcl868** [comment]
大家怎么复现的

**Comment by hefengly** [comment]
我这边点击气泡没有反应，弹窗也没有出现

**Comment by Ma2k** [comment]
我这边更新node 到 v13.11.0 ,umi 更新到3.0.12 就好了

**Comment by ycjcl868** [comment]
> 我这边更新node 到 v13.11.0 ,umi 更新到3.0.12 就好了

与 node 版本有关吗？

**Comment by run6** [comment]
我时有时无，很奇怪，请问有人知道什么原因么。

**Comment by ycjcl868** [comment]
修复了，更新即可

**Comment by 1995lk** [comment]
![image](https://user-images.githubusercontent.com/48973261/92843623-8621ab00-f417-11ea-8702-edadda024b02.png)

**Comment by 1995lk** [comment]
求解解决啊  当前node 10.15.3   umi 2.13.13  模板加载不出来啊  
√ �  find block list form https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.json

**Comment by fangguangyu** [comment]
> 求解解决啊 当前node 10.15.3 umi 2.13.13 模板加载不出来啊
> √ � find block list form https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.json

最后解决了吗。我也遇到这个问题。

**Comment by yilinyo** [comment]
科学上网一下可加载
