### ISSUE TITLE
🧐[问题]如何修改PageLoading默认样式

### ISSUE THREAD

**Issue by yinbanghui** [ant-design/ant-design-pro#6196]
### 🧐 问题描述
PageLoading默认样式如何修改
```
 dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      }
```
修改这里没效果
![image](https://user-images.githubusercontent.com/10389726/77409912-049c7900-6df5-11ea-981b-cd7bfd58c623.png)

**Comment by chenshuai2144** [comment]
在这里
https://github.com/ant-design/ant-design-pro/blob/master/src/pages/document.ejs
