### ISSUE TITLE
请问antd pro官方例子中，主题编译出来的css去冗余是哪一步做的🧐[问题]

### ISSUE THREAD

**Issue by hangaoke1** [ant-design/ant-design-pro#6198]
### 🧐 问题描述
官方在线例子中
![image](https://user-images.githubusercontent.com/19623160/77422048-d07e8380-6e07-11ea-84c0-0c3483578c2a.png)

发现dark.css只编译了color属性

clone到本地，编译后dark.css

![image](https://user-images.githubusercontent.com/19623160/77422123-ec822500-6e07-11ea-84b5-eaad17c3a133.png)

看了umi-plugin-antd-theme的实现方式，貌似也没有去冗余这块，所以想问下在线例子里只编译出涉及到变量的css属性是怎么做到的

**Comment by chenshuai2144** [comment]
https://github.com/chenshuai2144/merge-cssMoudle-less/blob/f7d51fb0dfbb09872b3a2daca5cfe68a910faec1/getVariable.js

在这里
