### ISSUE TITLE
🧐[问题]昨天升级了Antd 4.x使用暗黑模式出现一些问题

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6199]
### 🧐 问题描述

如图所示,使用暗黑模式后,使用浏览器的快捷填入这个Input就会出现白色的底.但是我从官网的组件页面试了下,没有这种问题.想问一下可能是啥原因造成的哦.
![image](https://user-images.githubusercontent.com/13188169/77495193-d5344d80-6e82-11ea-8ea5-491088d87dcf.png)

![image](https://user-images.githubusercontent.com/13188169/77494766-8fc35080-6e81-11ea-8fc8-b1e6db9a319f.png)

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/6186

**Comment by chenshuai2144** [comment]
看起来是google的设置问题，你应该设置浏览器

**Comment by joesdu** [comment]
> 看起来是google的设置问题，你应该设置浏览器的主题色

看起来应该是微软的Chrome浏览器bug,我切换浅色和深色主题都是这样,但是使用真正的Edge浏览器是能够正常显示的.
