### ISSUE TITLE
使用 CLI 创建的 browserHistory 项目的面包屑配置问题

### ISSUE THREAD

**Issue by balancelove** [ant-design/ant-design-pro#620]
![image](https://user-images.githubusercontent.com/20970152/34666916-9b73927a-f4a1-11e7-93d7-aa506d655c1b.png)
我看了下简单的模板里 breadcrumbNameMap 是一个 key-value值，而 PageHeader 里面处理的时候是要取它的的 `name` 属性值，而其没有提供
![image](https://user-images.githubusercontent.com/20970152/34666993-f7fcb4ea-f4a1-11e7-887d-66add23ca98f.png)

**Comment by chenshuai2144** [comment]
版本是不是太旧呢 试试clone 吧

**Comment by balancelove** [comment]
新版本一样的，还是有这个问题

**Comment by chenshuai2144** [comment]
show 一下你的meun和router的相关配置

**Comment by balancelove** [comment]
这就是项目直接 clone 下来的，没做任何修改，打开就是这样的，是需要我做什么配置修改么？

**Comment by chenshuai2144** [comment]
我本地是没有问题的...
![image](https://user-images.githubusercontent.com/8186664/34667559-7c251940-f4a4-11e7-807d-0fbb3d16f35d.png)
你的环境?

**Comment by balancelove** [comment]
`browser-history-simple` 是创建的这个，不是 standard，这个是要做一些配置还是要我自己做修改

**Comment by afc163** [comment]
@nikogu pro-cli 是不是需要相应更新一下？

**Comment by nikogu** [comment]
pro-cli 已经升级，由于 `browser-history` 的配置改动已经异常简单，所以这次已经去掉了这个模板

@balancelove 直接使用 pro-cli@1.0.0 来使用 pro@1.0.0，1.0.0 有很多新特性，值得改动。

路由配置：https://pro.ant.design/docs/deploy-cn#%E5%9C%A8-Ant-Design-Pro-%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1
