### ISSUE TITLE
🧐[问题]antdesignpeo项目中，umi ui 如何修改block远端的仓库地址及分支

### ISSUE THREAD

**Issue by lihaoran93** [ant-design/ant-design-pro#6200]
### 🧐 问题描述
antdesignpeo项目中，umi ui 如何修改block远端的仓库地址及分支

最近通过umi ui 安装 TableList时，一直会报 pro-table 、pro-layout版本冲突错误，导致不能通过umi ui直接安装。

### 💻 示例代码
`
我尝试修改过：
 config中添加 
block: {
    defaultGitUrl: 'https://github.com/ant-design/pro-blocks/tree/antd@3',
    npmClient: 'yarn', // 优先级低于 umi block add [block] --npm-client
  },

及
const fetchGithubFiles = async () => {
  const ignoreFile = ['_scripts', 'tests'];
  const data = await fetch('https://api.github.com/repos/ant-design/pro-blocks/git/trees/antd@3');
  if (data.status !== 200) {
    return [];
  }
`

### 🚑 其他信息
umi@2
antd@3

![图片](https://user-images.githubusercontent.com/26021760/77505757-fa36b980-6e9e-11ea-94c0-73001a7918df.png)

**Comment by chenshuai2144** [comment]
这个功能已经停止维护，如果需要使用建议fork之后自己处理
