### ISSUE TITLE
🐛[BUG]umi ui  connect ECONNREFUSED

### ISSUE THREAD

**Issue by wangruiStart** [ant-design/ant-design-pro#6201]
### 🐛 bug 描述

今天刚通过yarn create umi创建的项目，package.json里umi版本为3.0.14。
yarn start启动后，点击umi ui报错。

参考文档中安装
yarn add @umijs/preset-ui -D
并且以UMI_UI=1 umi dev命令启动。还是报这个错

`
{ RequestError: connect ECONNREFUSED 127.0.0.1:8002
    at ClientRequest.request.once.error (/Users/wangrui/Documents/smart/gym/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.origin.emit.args (/Users/wangrui/Documents/smart/gym/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',

`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本

- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by bamboooooo** [comment]
我也遇到相同的问题

**Comment by Pengyiz** [comment]
一样问题

**Comment by zcSkr** [comment]
看到大家都有问题，我就放心了

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/77521306-6fb18280-6ebd-11ea-9eac-ffd4e014f8a9.png)

为啥我下载是正常的

**Comment by Pengyiz** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/77521306-6fb18280-6ebd-11ea-9eac-ffd4e014f8a9.png)
> 
> ![image](https://user-images.githubusercontent.com/13595509/77521449-a8e9f280-6ebd-11ea-9d31-7b31abc3367f.png)
> 
> 为啥我下载是正常的

点一下 umi ui，页面加载不出来

**Comment by zcSkr** [comment]
而且我的浏览器不会自己打开

**Comment by Pengyiz** [comment]
<img width="1016" alt="Screen Shot 2020-03-25 at 5 27 34 pm" src="https://user-images.githubusercontent.com/34616869/77521684-0b42f300-6ebe-11ea-89e7-bf7fa903b4cb.png">

**Comment by Pengyiz** [comment]
> 而且我的浏览器不会自己打开

对的

**Comment by Pengyiz** [comment]
<img width="743" alt="Screen Shot 2020-03-25 at 5 30 57 pm" src="https://user-images.githubusercontent.com/34616869/77521958-6f65b700-6ebe-11ea-8c79-30910c28268d.png">
这个请求无响应

**Comment by zcSkr** [comment]
> > 而且我的浏览器不会自己打开
> 
> 对的

都是mac os，实锤了，等我回家windows试一下

**Comment by wry5560** [comment]
> > > 而且我的浏览器不会自己打开
> > 
> > 
> > 对的
> 
> 都是mac os，实锤了，等我回家windows试一下

我windows也不行~  而且我脚本装区块也不行。

**Comment by ycjcl868** [comment]
Windows 问题？

**Comment by dylanleung** [comment]
为啥每次我要用的时候都出来bug...

**Comment by zcSkr** [comment]
> 为啥每次我要用的时候都出来bug...

巧了，我故意多等一段时间，准备升一下要用的时候粗问题了。

**Comment by ycjcl868** [comment]
试下 @umijs/preset-ui: 2.1.2，修复了
