### ISSUE TITLE
🐛[BUG]Pro-table 语言不根据全局语言设置更改

### ISSUE THREAD

**Issue by carolwu-1206** [ant-design/ant-design-pro#6203]
### 🐛 bug 描述

Pro-table 语言不根据全局语言设置更改

### 📷 复现步骤

示例代码查询表格页面，切换右上角语言成英语，pro-table里的语言不变

### 🏞 期望结果

切换右上角语言成英语，pro-table的input里的“请输入”变成“Please enter”

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
插件还不支持 protable，现在还要手动切换，我去支持一下

**Comment by kiennguyen1101** [comment]
关于此问题是否有任何更新？

**Comment by chenshuai2144** [comment]
最新版本支持了
