### ISSUE TITLE
🐛[BUG] umi ui添加模板报错

### ISSUE THREAD

**Issue by wangruiStart** [ant-design/ant-design-pro#6206]
### 📷 复现步骤

之前umi-ui不能用，umiJs/preset-ui更新到2.1.2之后可以使用。但是添加模板时报错
![image](https://user-images.githubusercontent.com/21194195/77543243-625abf00-6ee2-11ea-96db-64cefb96bd61.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TianEnPang** [comment]
@chenshuai2144 
同样的问题，不仅如此。
1. umi ui中区块的示例图片都是404
2. 添加失败后，项目还会报错

以下截图：
![批注 2020-03-26 152300](https://user-images.githubusercontent.com/32772271/77620650-c8dced00-6f75-11ea-86a0-0fa0a9c813ff.png)

![批注 2020-03-26 152140](https://user-images.githubusercontent.com/32772271/77620525-84e9e800-6f75-11ea-948b-4558b1a06368.png)

**Comment by chenshuai2144** [comment]
再试试 应该能正常更新了，
区块没图片是因为截图功能消失了，正在重新生成，但是数量太大

**Comment by TianEnPang** [comment]
> 再试试 应该能正常更新了，
> 区块没图片是因为截图功能消失了，正在重新生成，但是数量太大，可能需要一定的时间

刚才新建了项目尝试了一下，依然不可以。而且添加模块失败后重启项目还会报错。
![批注 2020-03-26 175044](https://user-images.githubusercontent.com/32772271/77633782-ecf6f900-6f8a-11ea-9945-343f65fc1318.png)
![批注 2020-03-26 175416](https://user-images.githubusercontent.com/32772271/77633816-faac7e80-6f8a-11ea-96b1-201fe80c515e.png)

**Comment by 364** [comment]
请问解决了吗？我也遇到相同的问题

![GprNHs.png](https://s1.ax1x.com/2020/03/26/GprNHs.png)

Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/DashboardAnalysis/src/components

路径中的文件在本地是存在的

Ant Design Pro 版本: [e.g. 4.0.0]
umi 版本
浏览器环境
开发环境 [e.g. Win 10]

**Comment by chenshuai2144** [comment]
执行一下 clean 呢？

**Comment by TianEnPang** [comment]
> 执行一下 clean 呢？

项目根目录执行 `yarn clean` ?

**Comment by TianEnPang** [comment]
感觉和 `clean` 没什么关系吧，umi根本找不到本地的block的资源，也就没办法添加。
等着大佬出解决方案，我还是直接存本地的.umi/block手动复制吧。
 (T_T)

**Comment by 364** [comment]
是的 我使用命令添加也是报同样的错误
```
umi block add DashboardAnalysis --path=/dashboard/analysis
```

手动复制是指把区块源码复制到项目吗？

**Comment by TianEnPang** [comment]
> 是的 我使用命令添加也是报同样的错误
> 
> ```
> umi block add DashboardAnalysis --path=/dashboard/analysis
> ```
> 
> 手动复制是指把区块源码复制到项目吗？

复制要改的东西太多..... 我放弃了。

**Comment by TianEnPang** [comment]
@chenshuai2144 
早。
希望可以关注一下这个问题，目前添加模板报错。添加完后整个项目都是报错的，启动不来。
如果重现的话，直接创建新项目后添加模块应该就可以重现了。
版本：antd@4  umi@3

**Comment by ACLB** [comment]
同样的问题，有的模块可以添加，有的模块添加不了

**Comment by chenshuai2144** [comment]
umi block clean 
执行一下这个命令。 pro 刚刚部署过。区块添加应该没有问题

**Comment by TianEnPang** [comment]
> umi block clean
> 执行一下这个命令。 pro 刚刚部署过。区块添加应该没有问题

OK，我去新建个项目试试，之后再回馈。

**Comment by ACLB** [comment]
执行 umi block clean 出现错误
`×  error     Error: Please run umi help block to checkout the usage
    at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:96:17
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:46:103)
    at _next (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:48:194)
    at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:48:364
    at new Promise (<anonymous>)
    at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:48:97
    at _block (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:101:19)
    at block (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:71:19)
    at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-blocks\lib\index.js:158:17`

**Comment by ACLB** [comment]
并不是所有的模板添加都出现错误，添加一个空白的页面不出现错误，但是添加一个注册页面就出现了上述的错误

**Comment by chenshuai2144** [comment]
umi block help 一下

**Comment by TianEnPang** [comment]
> umi block help 一下
> 看起来是打错了。
> 
> umi block clear

为什么什么都没有呢？options 都是空格  ,,ԾㅂԾ,,

![批注 2020-03-27 133006](https://user-images.githubusercontent.com/32772271/77724923-18332400-702f-11ea-848d-5532ea9d2acc.png)

**Comment by ACLB** [comment]
umi block help 输出的结果
>   Usage: umi block [options]
  Options:
  Details:

**Comment by TianEnPang** [comment]
> 并不是所有的模板添加都出现错误，添加一个空白的页面不出现错误，但是添加一个注册页面就出现了上述的错误

空白页面貌似是直接生成的，所有没有错误，我这边新增空白页面也没有问题。
但是其他模块都是要从 `users/.umi/` 中找资源的，结果就报错：资源找不到。
两天了，这个问题还没解决。哭撩

**Comment by ACLB** [comment]
> 
> 
> > 并不是所有的模板添加都出现错误，添加一个空白的页面不出现错误，但是添加一个注册页面就出现了上述的错误
> 
> 空白页面貌似是直接生成的，所有没有错误，我这边新增空白页面也没有问题。
> 但是其他模块都是要从 `users/.umi/` 中找资源的，结果就报错：资源找不到。
> 两天了，这个问题还没解决。哭撩

同样的问题

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/77725142-af987700-702f-11ea-9460-ade2ee299f01.png)

这里也有一个clear，可以试试

**Comment by TianEnPang** [comment]
> umi block help 输出的结果
> 
> > Usage: umi block [options]
> > Options:
> > Details:

`umi block help` 貌似是错的命令，我执行后报错，提示执行 `umi help block` ，
执行后和你显示的一样...

**Comment by ACLB** [comment]
@chenshuai2144 clear以后安装还是出现一样的问题
>Execute task error Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/JueChen/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegister/src/locales
    at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:109:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:50:103)
    at _throw (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:52:291)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[Asset Error] Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/JueChen/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegister/src/locales
    at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:109:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:50:103)
    at _throw (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:52:291)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by TianEnPang** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/77725142-af987700-702f-11ea-9460-ade2ee299f01.png)
> 
> 这里也有一个clear，可以试试

依然不行哦，大佬请看截图的报错信息，是不是哪里umi有问题？
![批注 2020-03-27 133943](https://user-images.githubusercontent.com/32772271/77725494-947a3700-7030-11ea-99be-75744bb37519.png)
![批注 2020-03-27 134009](https://user-images.githubusercontent.com/32772271/77725499-9643fa80-7030-11ea-8ba0-c45a56650716.png)

**Comment by TianEnPang** [comment]
@chenshuai2144 
- - -
还有一个问题，为什么添加区块会自动add dva 和 react router 的依赖。
我刚看了GitHub上的pro_blocks，就拿AccountCenter模块看。
master下的AccountCenter模块中connect是从dva引入的。
但是antd@3&umi@3下的AccountCenter模块中connect是从umi引入的。
为什么是antd@3&umi@3，现在Ant Design Pro不是整合antd@4了嘛？
- - -

**Comment by TianEnPang** [comment]
@chenshuai2144 
晚上好，请问有出解决方案嘛？

**Comment by TianEnPang** [comment]
> @chenshuai2144 clear以后安装还是出现一样的问题
> 
> >Execute task error Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/JueChen/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegister/src/locales
> 
>     at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:109:13
> 
>     at Generator.throw (<anonymous>)
> 
>     at asyncGeneratorStep (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:50:103)
> 
>     at _throw (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:52:291)
> 
>     at processTicksAndRejections (internal/process/task_queues.js:86:5)
> 
> [Asset Error] Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/JueChen/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegister/src/locales
> 
>     at D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:109:13
> 
>     at Generator.throw (<anonymous>)
> 
>     at asyncGeneratorStep (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:50:103)
> 
>     at _throw (D:\Project\FrontEnd\FullSpectrumSegmentProject\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:52:291)
> 
>     at processTicksAndRejections (internal/process/task_queues.js:86:5)

请问你解决此问题了吗？

**Comment by amosync** [comment]
我也是， 这么垃圾发布什么发布

**Comment by TianenPang** [comment]
> 我也是， 这么垃圾发布什么发布

理解万岁吧，什么系统没BUG😂

现在可以使用 ` yarn create umi ` 安装完整的示例项目，就是自己复制一下的事儿

等官方后续的修复吧...

**Comment by andcup** [comment]
确实糟糕

**Comment by nameJw** [comment]
确实有这个问题，搞了我好久都没搞好
