### ISSUE TITLE
🧐[问题] 升级到umi3后，iconfont.cn 的业务自定义图标怎么引入使用

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#6208]
### 🧐 问题描述

升级到umi3后，iconfont.cn 的业务自定义图标怎么引入使用，umi3，config.ts中好像没有iconfontUrl 这个字段了。。

### 💻 示例代码
config.ts
iconfontUrl: '//at.alicdn.com/t/font_xxx.js',

**Comment by joesdu** [comment]
import { createFromIconfontCN } from '@ant-design/icons';

export const IconFont: ReactNode = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_1709014_ev4b7az4vd6.js'
});

**Comment by joesdu** [comment]
> ### 🧐 问题描述
> 升级到umi3后，iconfont.cn 的业务自定义图标怎么引入使用，umi3，config.ts中好像没有iconfontUrl 这个字段了。。
> 
> ### 💻 示例代码
> config.ts
> iconfontUrl: '//at.alicdn.com/t/font_xxx.js',
> 
> ### 🚑 其他信息

import { createFromIconfontCN } from '@ant-design/icons';

export const IconFont: ReactNode = createFromIconfontCN({
scriptUrl: '//at.alicdn.com/t/font_1709014_ev4b7az4vd6.js'
});

**Comment by joesdu** [comment]
> ### 🧐 问题描述
> 升级到umi3后，iconfont.cn 的业务自定义图标怎么引入使用，umi3，config.ts中好像没有iconfontUrl 这个字段了。。
> 
> ### 💻 示例代码
> config.ts
> iconfontUrl: '//at.alicdn.com/t/font_xxx.js',
> 
> ### 🚑 其他信息

interface IconFontProps extends IconBaseProps {
  type: string;
}
export const IconFont: React.SFC<IconFontProps> = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_1709014_ev4b7az4vd6.js'
});

建议调整成这样,我之前ReactNode在使用的时候会报错.
