### ISSUE TITLE
默认加载组件不显示

### ISSUE THREAD

**Issue by unrealsmart** [ant-design/ant-design-pro#621]
# 默认加载组件不显示

Ant Design Pro：0.3.1

Browser Version：Chrome/55.0.2883.87

OS：Window 10 Pro Insider Preview

本地环境搭建

<br>

问题描述：
- 首页或刷新首页，没有加载动画（白屏后载入页面）
- 切换菜单组件时，没有加载动画（似乎会直接出内容，没有加载动画 —— 没有详细测试）

简单来说：
载入页面的那个 Spin 不见了，文件 `src/router.js` 中的
```
...

dynamic.setDefaultLoadingComponent(() => {
  return <Spin size="large" className={styles.globalSpin} />;
});

...
```
修改也是没有任何反映的。

<br>

感觉是因为最新版本使用了路由权限的问题？
嗯，简单的尝试着修复，但没能成功。

<br>

希望大大们赶紧修复一下吧！

**Comment by chenshuai2144** [comment]
要不先试试升级浏览器到
![image](https://user-images.githubusercontent.com/8186664/34699169-dabded8e-f516-11e7-8c17-a8e65af81e3b.png)

我和你的版本一样 是没有问题的.

**Comment by iT-lijun** [comment]
Hi，看到源码加了**路由权限**，但是**官方预览**怎么不同步**更新**啊？

**Comment by chenshuai2144** [comment]
还没写好demo 和 文档

**Comment by iT-lijun** [comment]
对了，我觉得，这个项目还是弄个**概要**的**Function Todos**吧，不然都不知道接下来又会**突然新增**什么功能

**Comment by chenshuai2144** [comment]
#333  
看看这个

**Comment by chenshuai2144** [comment]
@iT-lijun   你的问题解决了吗？

**Comment by unrealsmart** [comment]
我升级到最新的 Chrome 版本，但仍然不显示，明天去找其他电脑测试一下。
另外，`npm install` 时：
```
D:\env\www\ADP>npm install

> weak@1.0.1 install D:\env\www\ADP\node_modules\weak
> node-gyp rebuild


D:\env\www\ADP\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bi
n\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  weakref.cc
  win_delay_load_hook.cc
C:\Users\Administrator\.node-gyp\8.9.3\x64\node.lib : fatal error LNK1127: library is corrupt [D:\env\www\ADP\node_modules\weak\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17025
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\env\www\ADP\node_modules\weak
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

因为电脑上没装过 `Python`、`node-gyp`，上列的报告不是最先的提示

<br>

- 安装 **Python**，配置好环境变量
- 安装 `node-gyp` && `node-gyp configure`

去网上找了一些方法（比如：配置 npm 环境变量、还有 node-gyp --python 什么的，当然，结果都不怎么好使）

最终，经过一番努力之后，仍然会报错（据说报错也不影响使用的……）

<br>

如果安装 **Ant Design Pro** 也需要安装其他程序的话，能否来一个安装教程？

**Comment by afc163** [comment]
这个和 pro 关系不大，成功安装任何 npm 包的前提是需要用户已经配好了本地环境。https://github.com/ant-design/ant-design-pro/issues/561

**Comment by hepengwei** [comment]
我今天也遇到这个问题，放一个Spin组件到页面上怎么都看不见，但是按F12审查元素，它还是在旋转的，就是看不见
