### ISSUE TITLE
table的新增页面样式的设置🧐

### ISSUE THREAD

**Issue by chengmings** [ant-design/ant-design-pro#6211]
table的新增页面的规则rules可以在columns里面，那么input框的宽度，以为label的labelCol属性又如何设置，在columns里面吗🧐

**Comment by chenshuai2144** [comment]
@chengmings  现在不支持设置都是透传上去的

**Comment by chengmings** [comment]
> @chengmings 现在不支持设置都是透传上去的

好的谢谢
