### ISSUE TITLE
🧐根据权限的不同，redirect重定向地址也需要发生变化

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6212]
### 🧐 根据权限的不同，需求是redirect重定向地址也需要变化

比如登录账户A，权限是A，它的重定向地址是/#/A/xxx,退出登录后，选择账户B登录，权限是B，它的重定向地址是/#/B/xxx

请问这样有什么好的解决办法吗？

**Comment by unrealsmart** [comment]
可以在 `src/models/login.(ts/js)` 里面的`*login`函数中做判断

**Comment by chenshuai2144** [comment]
或者直接让后端返回，登录成功之后给个地址，非常安全

**Comment by ISBN9527** [comment]
可能是问题我描述清楚，我的问题是在权限不同的情况下，在已登录的情况下，手动在url上输入https: xxxxxxx/#/  ,router.config.js的重定向地址怎么改变

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/77623616-5b33bf80-6f7b-11ea-81ee-d273e8aaa216.png)

**Comment by ISBN9527** [comment]
@chenshuai2144 大佬

**Comment by HHL030303** [comment]
在已登录的情况下，手动在url上输入https: xxxxxxx/#/ ,router.config.js的重定向地址怎么改变
这个问题我也遇到了 你最后是怎么处理的
