### ISSUE TITLE
🧐[问题]在TSX文件中使用Table,在column字段上产生异常

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6213]
### 🧐 问题描述

不能将类型“
```
({ title: ReactNode; dataIndex: string; key: string; align: string; width?: undefined; render?: undefined; } | { title: ReactNode; align: string; key: string; width: number; render: (_: any, record: { ...; }) => Element; dataIndex?: undefined; })[]”分配给类型“ColumnsType<{ tenantId: string; }>”。
  不能将类型“{ title: ReactNode; dataIndex: string; key: string; align: string; width?: undefined; render?: undefined; } | { title: ReactNode; align: string; key: string; width: number; render: (_: any, record: { ...; }) => Element; dataIndex?: undefined; }”分配给类型“ColumnGroupType<{ tenantId: string; }> | ColumnType<{ tenantId: string; }>”。
    不能将类型“{ title: React.ReactNode; dataIndex: string; key: string; align: string; width?: undefined; render?: undefined; }”分配给类型“ColumnGroupType<{ tenantId: string; }> | ColumnType<{ tenantId: string; }>”。
      不能将类型“{ title: React.ReactNode; dataIndex: string; key: string; align: string; width?: undefined; render?: undefined; }”分配给类型“ColumnType<{ tenantId: string; }>”。
        属性“align”的类型不兼容。
          不能将类型“string”分配给类型“"center" | "left" | "right" | undefined”。ts(2322)
Table.d.ts(11, 5): The expected type comes from property 'columns' which is declared here on type 'IntrinsicAttributes & Pick<TableProps<{ tenantId: string; }>, "loading" | "children" | "footer" | "style" | "summary" | "title" | "prefixCls" | ... 34 more ... | "sortDirections"> & Partial<...> & Partial<...>
```

### 💻 示例代码

![image](https://user-images.githubusercontent.com/13188169/77617223-911e7700-6f6e-11ea-98bd-6013a3b85304.png)

![image](https://user-images.githubusercontent.com/13188169/77617261-ab585500-6f6e-11ea-847f-2e854f82c918.png)

**Comment by chenshuai2144** [comment]
配置一下类型

**Comment by joesdu** [comment]
> TableListItem

我使用的是Antd的Table没有用Pro的Table,也是这样配置吗?

**Comment by joesdu** [comment]
> 配置一下类型, ts 现在还不够智能
> 
> ```
>   const columns: ProColumns<TableListItem>[]
> ```

我使用的是Antd的Table没有用Pro的Table,也是这样配置吗?

**Comment by chenshuai2144** [comment]
`import { TableProps, ColumnType } from 'antd/es/table';`

antd 的有点麻烦

**Comment by joesdu** [comment]
> `import { TableProps, ColumnType } from 'antd/es/table';`
> 
> antd 的有点麻烦

感谢

**Comment by joesdu** [comment]
> `import { TableProps, ColumnType } from 'antd/es/table';`
> 
> antd 的有点麻烦

整了半天都有点不对,后来我改成ColumnsType<any>了😂😂

**Comment by windman-only** [comment]
> > `import { TableProps, ColumnType } from 'antd/es/table';`
> > antd 的有点麻烦
> 
> 整了半天都有点不对,后来我改成ColumnsType了😂😂

您好，请问一下最终怎么解决的呢

**Comment by akakaze** [comment]
![截圖 2023-11-15 上午10 15 02](https://github.com/ant-design/ant-design-pro/assets/15887117/3b9b8c3c-1626-4588-b5c5-785f35fdff0f)
![截圖 2023-11-15 上午10 15 23](https://github.com/ant-design/ant-design-pro/assets/15887117/2b2c5927-b75d-4f66-8811-156e15a58025)

相關套件版本：
- antd@5.11.0
- react@18.2.0
- typescript@5.2.2

內容直接從 https://ant.design/components/table-cn#components-table-demo-fixed-columns-header 複製，但仍然有錯誤提示
