### ISSUE TITLE
umi ui 气泡点击无反应🐛[BUG]

### ISSUE THREAD

**Issue by hefengly** [ant-design/ant-design-pro#6215]
### 🐛 bug 描述

初始化 Ant Design Pro 项目后，点击umi ui 气泡没有反应

### 📷 复现步骤

初始化 Ant Design Pro 项目，点击 umi ui 气泡

### 🏞 期望结果

出现区块下载弹窗

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.0.14
- 浏览器环境 谷歌浏览器
- 开发环境 [e.g. mac OS]

**Comment by TianEnPang** [comment]
按照 [使用方法](https://umijs.org/zh-CN/docs/use-umi-ui) 试试。
我这边可以显示，但是添加模板会报错。

**Comment by hefengly** [comment]
噢，谢谢。我重启试试后，气泡可以点击了。我新建了一个空白页后，往空白页那里添加区块，但是地址信息那里有问题，是我哪个姿势不对吗？
![image](https://user-images.githubusercontent.com/28841926/77637269-5c231c00-6f90-11ea-917b-18ea34d30cba.png)

**Comment by hefengly** [comment]
> 按照 [使用方法](https://umijs.org/zh-CN/docs/use-umi-ui) 试试。
> 我这边可以显示，但是添加模板会报错。

**Comment by hefengly** [comment]
> 按照 [使用方法](https://umijs.org/zh-CN/docs/use-umi-ui) 试试。
> 我这边可以显示，但是添加模板会报错。

噢，谢谢，我重启之后再尝试，发现气泡可以点击了。我添加了一个空白页后，在里面添加区块，发现地址信息那里有问题，指向的位置不是我所添加的那个页面（空白页），是我操作有问题吗？
![image](https://user-images.githubusercontent.com/28841926/77637418-9bea0380-6f90-11ea-959a-f33bc8be85f6.png)

**Comment by hefengly** [comment]
是不同的问题，我重新开个 issues 吧
