### ISSUE TITLE
🧐[问题] 请问打完包生成的js文件按照数字顺序命名，怎么才能随机命名呢

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#6216]
### 🧐 问题描述

目前我们用的是V2版本，打完包生成的js文件文件如下：

![Snipaste_2020-03-26_15-47-14](https://user-images.githubusercontent.com/23411433/77622523-5f5edd80-6f79-11ea-9583-3d2e93fbf1e2.png)

而ant-design-pro官网是这种随机命名的：

![Snipaste_2020-03-26_15-47-36](https://user-images.githubusercontent.com/23411433/77622564-74d40780-6f79-11ea-9c4f-1b1b09809002.png)

请问需要在哪里配置呢？

**Comment by chenshuai2144** [comment]
在 config.js 中配置  hash: true,

**Comment by mstao** [comment]
> 在 config.js 中配置 `hash: true,`
> https://github.com/ant-design/ant-design-pro/blob/8e21acdf9943c23a2f8f6e6603724a8fc4f7d726/config/config.ts#L14

目前我们用的是V2,版本，config.js文件也是配置过的，但不起作用
![Snipaste_2020-03-26_15-56-01](https://user-images.githubusercontent.com/23411433/77623043-591d3100-6f7a-11ea-92fd-883f8a6eeb26.png)

**Comment by mstao** [comment]
V2 版本，export default 节点下配置就可以了

**Comment by chenshuai2144** [comment]
hash 要在第一集配置
你配置在了插件里

**Comment by mstao** [comment]
> hash 要在第一集配置
> 你配置在了插件里

嗯呢，已经可以了，thanks
