### ISSUE TITLE
添加区块报错🐛[BUG]

### ISSUE THREAD

**Issue by hefengly** [ant-design/ant-design-pro#6217]
### 🐛 bug 描述

我添加了一个空白页后，在里面添加区块，发现地址信息那里有问题，报错了。其指向的位置不是我所添加的那个页面（空白页）
![image](https://user-images.githubusercontent.com/28841926/77640072-bc1bc180-6f94-11ea-8e0f-44d8a1511f8a.png)

### 📷 复现步骤

初始化 Ant Design Pro 项目，利用 umi ui新建一个空白页，在空白页上新建区块

## © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.0.14
- 浏览器环境 谷歌浏览器
- 开发环境 win 10

**Comment by Matthew1994** [comment]
+1
