### ISSUE TITLE
🐛[BUG]useDispatch，useSelector无法从umi导出

### ISSUE THREAD

**Issue by wangruiStart** [ant-design/ant-design-pro#6218]
### 🐛 bug 描述

直接
`import { useDispatch, useSelector } from 'umi';`报错
useDispatch，useSelector无法从umi导出。
查看src/.umi/core/umiExports.ts发现dva只导出了connect

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/21194195/77712440-bbc00c80-700e-11ea-8ec9-40c79b431874.png)

**Comment by xiaohuoni** [comment]
dva 版本需要 2.6 以上。你确认一下。

**Comment by wangruiStart** [comment]
> 装

直接装的umi 3不是封装成umijs/preset-react了？还是说dva需要单独安装？

**Comment by xiaohuoni** [comment]
dva不需要单独安装，就是怕你单独安装，你可以给一个重现demo嘛？

**Comment by wangruiStart** [comment]
> dva不需要单独安装，就是怕你单独安装，你可以给一个重现demo嘛？

直接npm create umi创建新项目就可以。另外，我看到modules里面的dva版本是2.6.0

**Comment by chenshuai2144** [comment]
已经修复了，从区块中全部删除

**Comment by wangruiStart** [comment]
> 已经修复了，从区块中全部删除 dva 的依赖

全部删除dva依赖是什么意思，如果是需要操作的话可否描述一下具体操作步骤？我又新建的项目，刚开始是可以的，启动两次之后突然又不行了

**Comment by wangruiStart** [comment]
手动回复。package.json中删除dva

**Comment by Memories-SlowFever** [comment]
我用umi 3.x也是这样 有知道为什么的嘛  难道说只能用2.6.x?
