### ISSUE TITLE
🐛[BUG] 升级umi3.0两个问题

### ISSUE THREAD

**Issue by zhfish** [ant-design/ant-design-pro#6219]
#### ~~umi-plugin-antd-icon-config 插件不生效~~
~~1. console里提示兼容性warnin~~
~~2. 是我自己少粘了一个字母~~
#### antd4的Modal的api调用时不取全局语言
1. 我已经移除了i18n
2. antd本来是想关上的，但是关上之后发现antd控件全局变英文了
3. antd打开之后，直接渲染的控件会随浏览器语言，但Modal.confirm这类还是英文
```
  locale: {
    default: 'zh-CN',
    baseNavigator: false,
    antd: true,
    title: false,
  },
```
### 🏞 期望结果
1. menu的icon能正常显示，也没必要非string，但至少给条路
2. 移除i18n后，antd可以指定zh-CN, 不受浏览器语言环境影响
### 💻 复现代码

https://github.com/zhfish/ant-design-pro-demo

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
4.0.0
- umi 版本
3.0.12
- 浏览器环境
edge81
- 开发环境 [e.g. mac OS]
mac OS

**Comment by joesdu** [comment]
不知道为啥,你的这些问题,我都没有🤔🤔

**Comment by joesdu** [comment]
图标没了,应该是你需要添加一个库@umijs/preset-ant-design-pro  应该是这个

**Comment by zhfish** [comment]
...我新起个环境试一下
https://github.com/umijs/umi-plugin-antd-icon-config/issues/8
@umijs/preset-ant-design-pro肯定是有的呀
手动注册umi-plugin-antd-icon-config时，会提示已经自动注册

**Comment by joesdu** [comment]
https://github.com/ant-design/ant-design-pro/issues/6178
建议看下这个issue和Umi升级3.0的两篇文章.

**Comment by chenshuai2144** [comment]
umi-plugin-antd-icon-config

这个用的新的 antd@4 的图表有些图表被改名了，你可能需要在 antd@4 中找一下新的名字

**Comment by zhfish** [comment]
@chenshuai2144 @joesdu 
复现demo
https://github.com/zhfish/ant-design-pro-demo

**Comment by zhfish** [comment]
抱歉，刚又检查了一遍，复制icon名字这里，少了个字母
那么就剩下语言的问题

**Comment by chenshuai2144** [comment]
语言的需要包在最外面，你应该放到layout的顶部

**Comment by zhfish** [comment]
@chenshuai2144 你意思是不用umi3的locale设置，自己在layout去包ConfigProvider么？
我试一下

**Comment by joesdu** [comment]
> @chenshuai2144 你意思是不用umi3的locale设置，自己在layout去包ConfigProvider么？
> 我试一下

我用了umi3的local，并没有实现国际化也默认显示了中文

**Comment by zhfish** [comment]
@

> > @chenshuai2144 你意思是不用umi3的locale设置，自己在layout去包ConfigProvider么？
> > 我试一下
> 
> 我用了umi3的local，并没有实现国际化也默认显示了中文

麻烦您帮忙看一下我的demo，是有哪个设置不对么？

**Comment by joesdu** [comment]
> @joesdu
> 
> > > @chenshuai2144 你意思是不用umi3的locale设置，自己在layout去包ConfigProvider么？
> > > 我试一下
> > 
> > 
> > 我用了umi3的local，并没有实现国际化也默认显示了中文
> 
> 麻烦您帮忙看一下我的demo，是有哪个设置不对么？

import { defineConfig, utils } from 'umi';

import defaultConfig from './default.config';
import { produceVersion } from './version.config';
import { routerConfig } from './router.config';

const { winPath } = utils;

export default defineConfig({
  routes: routerConfig,
  theme: { 'primary-color': defaultConfig.primaryColor },
  dva: { hmr: true },
  antd: { dark: false },
  locale: {
    default: 'zh-CN',
    antd: true,
    baseNavigator: true
  },
  dynamicImport: { loading: '@/components/PageLoading' },
  // plugins: [],
  favicon: './favicon.svg',
  hash: true,
  ignoreMomentLocale: true,
  lessLoader: { javascriptEnabled: true },
  cssLoader: {
    modules: {
      getLocalIdent: (context: { resourcePath: string }, _: string, localName: string) => {
        if (context.resourcePath.includes('node_modules') || context.resourcePath.includes('ant.design.pro.less') || context.resourcePath.includes('global.less')) {
          return localName;
        }
        const match = context.resourcePath.match(/src(.*)/);
        if (match && match[1]) {
          const antdProPath = match[1].replace('.less', '');
          const arr = winPath(antdProPath)
            .split('/')
            .map((a: string) => a.replace(/([A-Z])/g, '-$1'))
            .map((a: string) => a.toLowerCase());
          return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
        }
        return localName;
      }
    }
  },
  history: { type: 'hash' },
  // exportStatic: {
  //   htmlSuffix: true,
  //   dynamicRoot: true
  // },
  // publicPath: 'smartlight-web/', // 该路径需要和服务端的文件路径一致
  outputPath: produceVersion ? './produce' : './demonstrative'
});



我是这么配置的.你可以看看.其他我没做什么变动.

**Comment by zhfish** [comment]
> > @joesdu
> > > > @chenshuai2144 你意思是不用umi3的locale设置，自己在layout去包ConfigProvider么？
> > > > 我试一下
> > > 
> > > 
> > > 我用了umi3的local，并没有实现国际化也默认显示了中文
> > 
> > 
> > 麻烦您帮忙看一下我的demo，是有哪个设置不对么？
> 
> import { defineConfig, utils } from 'umi';
> 
> import defaultConfig from './default.config';
> import { produceVersion } from './version.config';
> import { routerConfig } from './router.config';
> 
> const { winPath } = utils;
> 
> export default defineConfig({
> routes: routerConfig,
> theme: { 'primary-color': defaultConfig.primaryColor },
> dva: { hmr: true },
> antd: { dark: false },
> locale: {
> default: 'zh-CN',
> antd: true,
> baseNavigator: true
> },
> dynamicImport: { loading: '@/components/PageLoading' },
> // plugins: [],
> favicon: './favicon.svg',
> hash: true,
> ignoreMomentLocale: true,
> lessLoader: { javascriptEnabled: true },
> cssLoader: {
> modules: {
> getLocalIdent: (context: { resourcePath: string }, _: string, localName: string) => {
> if (context.resourcePath.includes('node_modules') || context.resourcePath.includes('ant.design.pro.less') || context.resourcePath.includes('global.less')) {
> return localName;
> }
> const match = context.resourcePath.match(/src(.*)/);
> if (match && match[1]) {
> const antdProPath = match[1].replace('.less', '');
> const arr = winPath(antdProPath)
> .split('/')
> .map((a: string) => a.replace(/([A-Z])/g, '-$1'))
> .map((a: string) => a.toLowerCase());
> return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
> }
> return localName;
> }
> }
> },
> history: { type: 'hash' },
> // exportStatic: {
> // htmlSuffix: true,
> // dynamicRoot: true
> // },
> // publicPath: 'smartlight-web/', // 该路径需要和服务端的文件路径一致
> outputPath: produceVersion ? './produce' : './demonstrative'
> });
> 
> 我是这么配置的.你可以看看.其他我没做什么变动.

@joesdu 能否帮忙试下Modal.confrim的按钮的文字是否是中文？

**Comment by joesdu** [comment]
> > > @joesdu
> > > > > @chenshuai2144 你意思是不用umi3的locale设置，自己在layout去包ConfigProvider么？
> > > > > 我试一下
> > > > 
> > > > 
> > > > 我用了umi3的local，并没有实现国际化也默认显示了中文
> > > 
> > > 
> > > 麻烦您帮忙看一下我的demo，是有哪个设置不对么？
> > 
> > 
> > import { defineConfig, utils } from 'umi';
> > import defaultConfig from './default.config';
> > import { produceVersion } from './version.config';
> > import { routerConfig } from './router.config';
> > const { winPath } = utils;
> > export default defineConfig({
> > routes: routerConfig,
> > theme: { 'primary-color': defaultConfig.primaryColor },
> > dva: { hmr: true },
> > antd: { dark: false },
> > locale: {
> > default: 'zh-CN',
> > antd: true,
> > baseNavigator: true
> > },
> > dynamicImport: { loading: '@/components/PageLoading' },
> > // plugins: [],
> > favicon: './favicon.svg',
> > hash: true,
> > ignoreMomentLocale: true,
> > lessLoader: { javascriptEnabled: true },
> > cssLoader: {
> > modules: {
> > getLocalIdent: (context: { resourcePath: string }, _: string, localName: string) => {
> > if (context.resourcePath.includes('node_modules') || context.resourcePath.includes('ant.design.pro.less') || context.resourcePath.includes('global.less')) {
> > return localName;
> > }
> > const match = context.resourcePath.match(/src(.*)/);
> > if (match && match[1]) {
> > const antdProPath = match[1].replace('.less', '');
> > const arr = winPath(antdProPath)
> > .split('/')
> > .map((a: string) => a.replace(/([A-Z])/g, '-$1'))
> > .map((a: string) => a.toLowerCase());
> > return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
> > }
> > return localName;
> > }
> > }
> > },
> > history: { type: 'hash' },
> > // exportStatic: {
> > // htmlSuffix: true,
> > // dynamicRoot: true
> > // },
> > // publicPath: 'smartlight-web/', // 该路径需要和服务端的文件路径一致
> > outputPath: produceVersion ? './produce' : './demonstrative'
> > });
> > 我是这么配置的.你可以看看.其他我没做什么变动.
> 
> @joesdu 能否帮忙试下Modal.confrim的按钮的文字是否是中文？

![image](https://user-images.githubusercontent.com/13188169/77844487-e1e5d800-71d9-11ea-80b7-f1448f4e4924.png)

![image](https://user-images.githubusercontent.com/13188169/77844504-f924c580-71d9-11ea-8678-e2a2d0080ca7.png)

没有问题.

**Comment by joesdu** [comment]
我发现我的RangePicker国际化有问题,其他都能正常显示中文,这个组件却显示英文.

**Comment by Tenodec** [comment]
如果嫌升级太麻烦或者遇到奇怪问题，个人建议yarn create umi 新启一个项目    ，然后把业务代码复制，配置复制过去。

**Comment by zhfish** [comment]
@Tenodec 可以看下我的demo，就是新启动的，然后Modal.confirm的国际化就有问题
不过我已经用ConfigProvider包了，不用umi的locale了

**Comment by Mh2336393** [comment]
> 我发现我的RangePicker国际化有问题,其他都能正常显示中文,这个组件却显示英文.并且单独引入locale都无效.

我也是这个问题。全局设置单个组件设置都试了

**Comment by chenshuai2144** [comment]
一般是 moment 没设置
`
moment.locale('zh-cn');`

![image](https://user-images.githubusercontent.com/8186664/98792208-1e043b00-2441-11eb-8b55-acc62e5e96d8.png)

**Comment by Mh2336393** [comment]
![image](https://user-images.githubusercontent.com/48132028/98792348-4f7d0680-2441-11eb-9f40-643e3a97af00.png)
![image](https://user-images.githubusercontent.com/48132028/98792394-628fd680-2441-11eb-95ae-50166e41e0e9.png)

**Comment by Mh2336393** [comment]
![Uploading image.png…]()

**Comment by Mh2336393** [comment]
> 一般是 moment 没设置
> ` moment.locale('zh-cn');`
> 
> ![image](https://user-images.githubusercontent.com/8186664/98792208-1e043b00-2441-11eb-8b55-acc62e5e96d8.png)
![image](https://user-images.githubusercontent.com/48132028/98792709-daf69780-2441-11eb-81f1-101187df3a26.png)

**Comment by JuSanZhi** [comment]
> > 一般是 moment 没设置
> > ` moment.locale('zh-cn');`
> > ![image](https://user-images.githubusercontent.com/8186664/98792208-1e043b00-2441-11eb-8b55-acc62e5e96d8.png)
> > ![image](https://user-images.githubusercontent.com/48132028/98792709-daf69780-2441-11eb-81f1-101187df3a26.png)

我也是遇到这个问题，请问解决了么

**Comment by soeasyjx** [comment]
moment.locale('zh-cn'); 也还是月份显示英文 ，umi3.x

**Comment by JamosLi** [comment]
> 
import moment from 'moment';
import 'moment/dist/locale/zh-cn';
moment.locale('zh-cn');

移除.umi文件夹
