### ISSUE TITLE
🐛[BUG]多步update例子中的UpdateForm可能丢失最后一步数据

### ISSUE THREAD

**Issue by carolwu-1206** [ant-design/ant-design-pro#6220]
### 🐛 bug 描述
```
  const handleNext = async () => {
    const fieldsValue = await form.validateFields();
    setFormVals({ ...formVals, ...fieldsValue });
    if (currentStep < 2) {
      forward();
    } else {
      handleUpdate(formVals);
    }
  };
```

这里setFormVals是异步的，因此在handleUpdate里拿到的不是最新数据。

### 📷 复现步骤

在service.ts的updateRule打印params内容

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个 pr 修复一下?

**Comment by wxq851685279** [comment]
同样问题

**Comment by korenhe** [comment]
Here's a workaround:
-    handleUpdate(formVals);
+    handleUpdate({ ...formVals, ...fieldsValue });
