### ISSUE TITLE
对 src/models/user.ts 包裹了下返回，却打包后未能加载全局user model

### ISSUE THREAD

**Issue by 363676727** [ant-design/ant-design-pro#6221]
### 🧐 问题描述

直接git clone ant-design-pro最新umi3.0.14版本,
对 src/models/user.ts 包裹了下返回，却打包后未能加载全局user model

### 💻 示例代码
const enhance = (rest) => {
  //to do

  return {...rest}
}
const UserModel = enhance({
  namespace: 'user',
  ...
})

### 🚑 其他信息
在之前版本都可以，不知道为什么最新版本却不行?
![image](https://user-images.githubusercontent.com/29798215/77720603-59bdd200-7023-11ea-8e34-dc60a59183ea.png)

在.umi下生成的文件缺失了user model加载，如果在这里直接添加user model是可以加载成功，redux store 上就有了
![image](https://user-images.githubusercontent.com/29798215/77720747-c638d100-7023-11ea-810d-1e9a7dc221bf.png)

**Comment by chenshuai2144** [comment]
你破坏了 dva 的自动读取，为什么要这样做？

**Comment by 363676727** [comment]
因为在写request异步effect函数时，经常要请求成功还要写reducer来同步state，于是我在每个model注册时都加了一个公共的request effect函数，这样我就只需要指定request url， 再配置一个参数用来指定更新state里的哪个key值就好了，这样代码就可以减少很多，用起来也方便。

类似下面案例
![image](https://user-images.githubusercontent.com/29798215/77738114-378b7a80-704a-11ea-8b47-735b58d8c85f.png)

**Comment by 363676727** [comment]
> 你破坏了 dva 的自动读取，为什么要这样做？

因为在写request异步effect函数时，经常要请求成功还要写reducer来同步state，于是我在每个model注册时都加了一个公共的request effect函数和公共同步state的reducer函数，这样我就只需要指定request url， 再配置一个参数来调用 公共同步state的reducer函数 更新state里的哪个key值就好了，这样代码就可以减少很多，用起来也方便。

类似下面案例
![image](https://user-images.githubusercontent.com/29798215/77738114-378b7a80-704a-11ea-8b47-735b58d8c85f.png)

**Comment by 363676727** [comment]
> 你破坏了 dva 的自动读取，为什么要这样做？

> 你破坏了 dva 的自动读取，为什么要这样做？

因为在写request异步effect函数时，经常要请求成功还要写reducer来同步state，于是我在每个model注册时都加了一个公共的request effect函数和公共同步state的reducer函数，这样我就只需要指定request url， 再配置一个参数来调用 公共同步state的reducer函数 更新state里的哪个key值就好了，这样代码就可以减少很多，用起来也方便。

类似下面案例
![image](https://user-images.githubusercontent.com/29798215/77738114-378b7a80-704a-11ea-8b47-735b58d8c85f.png)

**Comment by 363676727** [comment]
> 你破坏了 dva 的自动读取，为什么要这样做？

因为在写request异步effect函数时，经常要请求成功还要写reducer来同步state，于是我在每个model注册时都加了一个公共的request effect函数和公共同步state的reducer函数，这样我就只需要指定request url， 再配置一个参数来调用 公共同步state的reducer函数 更新state里的哪个key值就好了，这样代码就可以减少很多，用起来也方便。

类似下面案例
![image](https://user-images.githubusercontent.com/29798215/77738114-378b7a80-704a-11ea-8b47-735b58d8c85f.png)

**Comment by chenshuai2144** [comment]
这个你看看有没有更好的解决方案，这个有点 hack

**Comment by 363676727** [comment]
> 这个你看看有没有更好的解决方案，这个有点 hack

在pro很早的版本我就使用了这个方式，之前查询了dva并没有符合我需求的插件。

我是觉得enhance函数只是单纯返回增强后的{}，来替代我每个model写上同样代码，是一个比较正常的操作。
或者是我并不理解dva 的自动读取方式，无意间破坏了它，dva自动读取方式我觉得应该是在最近发生变化，之前都是正常，我应该去哪里了解dva自动读取方式，这样我可以有机会尝试其他方式来实现需求。

**Comment by sorrycc** [comment]
配这个 https://umijs.org/plugins/plugin-dva#skipmodelvalidate 。
