### ISSUE TITLE
🧐[问题]在Pro中能否使用IconFont图标作为logo

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6222]
### 🧐 问题描述

如题,我希望使用IconFont的图标作为logo,但是使用如下的写法无效.
讲iconfontUrl属性加上,直接使用图标名字字符串也无效.
![image](https://user-images.githubusercontent.com/13188169/77721225-2ed47d80-7025-11ea-9486-aae80f04cd44.png)

**Comment by joesdu** [comment]
同时还希望能够修改logo的样式.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/pull/3517

**Comment by joesdu** [comment]
> #3517

8太对,我想换掉的是logo不是图标.图标我没问题.我现在是换logo无效

**Comment by chenshuai2144** [comment]
@joesdu  logo 建议直接用svg，因为 IconFont 需要先注册在用。

```
import { createFromIconfontCN } from '@ant-design/icons';

const MyIcon = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js', // 在 iconfont.cn 上生成
});

logo={<MyIcon type="icon-example" />}
```

**Comment by joesdu** [comment]
> @joesdu  logo 建议直接用svg，因为 IconFont 需要先注册在用。
> 
> ```
> import { createFromIconfontCN } from '@ant-design/icons';
> 
> const MyIcon = createFromIconfontCN({
>   scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js', // 在 iconfont.cn 上生成
> });
> 
> logo={<MyIcon type="icon-example" />}
> ```
> 
> 

我就是这么用的在baselayout的logo属性中没有效果，页面没有显示

**Comment by chenshuai2144** [comment]
你用了  ()=> Node, 直接 Node

**Comment by joesdu** [comment]
> 你用了 ()=> Node, 直接 Node

![image](https://user-images.githubusercontent.com/13188169/77738682-3eff5380-704b-11ea-92c4-6153ed79fb7c.png)
这么写hai's还是无效.不知道是什么原因,暂时使用SVG图吧,以后有时间了再研究.
