### ISSUE TITLE
How to do redux-persist ?🧐[问题]

### ISSUE THREAD

**Issue by venkatamandala** [ant-design/ant-design-pro#6223]
### 🧐 问题描述
Can someone share the code snippet for perfoming redux-persist in dvajs with antdpro v4?

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它


——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by venkatamandala** [comment]
good bye Ant Design Pro :) i moved on with a better product
