### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by yj18523574287** [ant-design/ant-design-pro#6224]
### 🧐 问题描述
antd-pro 无法引入umi/router

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29517645/77727402-3439c400-7035-11ea-8dfb-78a58206ad9a.png)

**Comment by joesdu** [comment]
> ### 🧐 问题描述
> antd-pro 无法引入umi/router
> 
> ### 💻 示例代码
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/29517645/77727402-3439c400-7035-11ea-8dfb-78a58206ad9a.png)

import { Effect, Reducer, history } from 'umi';
这样引入.旧版的umi使用
import { router } from 'umi';
