### ISSUE TITLE
Authorized权限组件🧐[问题]

### ISSUE THREAD

**Issue by luxuryXu** [ant-design/ant-design-pro#6225]
### 🧐 问题描述

1、renderAuthorize函数为什么要传入Authorized组件，不做任何操作就直接返回，这样做有什么意义吗；
2、CURRENT是否作为props传入会更好？
3、CURRENT在getAuthrity方法做了一个处理，在传入renderAuthorize方法为什么又做了一次处理

**Comment by chenshuai2144** [comment]
CURRENT  经常修改才会这么设计，
如果你使用了最新版本的 umi@3，推荐使用 https://umijs.org/plugins/plugin-access
