### ISSUE TITLE
🐛[BUG] 点击侧边导航时没有立马触发更新document.title，也是在同样的组件下。

### ISSUE THREAD

**Issue by wscart** [ant-design/ant-design-pro#6227]
### 🐛 bug 描述
在官方演示上有bug，跟我遇到的问题是一样的
点击列表页/搜索列表/搜索列表(文章)页面，当初始化的时候有将当前页面标题更改documnt.title，不过再次点击搜索列表(项目)页面，这个时候就缺少了触发更新documnt.title，导致当前浏览器标题变成url。

另外做测试了，
1、重新刷新浏览器才有当前页面的标题，
2、每次渲染不同组件时会触发更新documnt.title。

据我分析结果问题，是点击N个同样的组件都是默认为已初始化的状态，不会再次主动触发。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本: 3.0.14
- 浏览器环境: Chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![1](http://qinin.iut8.cn/1585303346576.jpg)

**Comment by chenshuai2144** [comment]
这个图片显示不了？

**Comment by wscart** [comment]
> 这个图片显示不了？

可能需要开翻墙才能看到。
另外你可以去打开官方演示站，导航地址：列表页/搜索列表/搜索列表(文章)。

**Comment by afc163** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/77829118-e028ff80-715a-11ea-8270-16f134208e7a.png">

确实。

**Comment by jx-zyf** [comment]
我也遇到了同样的问题，现在有解决方案吗？

**Comment by haohuaZhang** [comment]
<img width="707" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/126741760/93c969f5-b73d-409b-a86b-a7e5bfd2f5fc">
