### ISSUE TITLE
🧐[umi3.0登录成功之后一直处于loading状态、页面无法进入系统内部]

### ISSUE THREAD

**Issue by xieww** [ant-design/ant-design-pro#6228]
### 🧐 问题描述
umi3.0登录成功之后一直处于loading状态、页面无法进入系统内部
调试代码发现是已经进入SecurityLayout内部，但是并没有进入UserLayout；
控制台有语言包的警告信息，这个也是升级umi到3才出现的

### 🚑 其他信息
umi: 3.0.14;
system: macOS: 10.13.6;
Google: 80.0.3987.149
![image](https://user-images.githubusercontent.com/26969239/77746571-0fa31380-7058-11ea-95ca-c5a6038b75a3.png)

![image](https://user-images.githubusercontent.com/26969239/77746836-8a6c2e80-7058-11ea-8ec7-ac74b0a24456.png)

**Comment by chenshuai2144** [comment]
登陆逻辑被你删掉了吗》？

**Comment by xieww** [comment]
> 登陆逻辑被你删掉了吗》？

我把请求成功之后的逻辑改成了我自己的，在登录逻辑回调里面写的跳转地址

![image](https://user-images.githubusercontent.com/26969239/77843252-ead0ac80-71cd-11ea-8321-6f34bc306c18.png)

**Comment by HashidaHaru** [comment]
是不是 SecurityLayout 里的 render 逻辑也要修改
```typescript
render() {
    const { isReady } = this.state;
    const { children, loading, currentUser } = this.props;
    // You can replace it to your authentication rule (such as check token exists)
    // 你可以把它替换成你自己的登录认证规则（比如判断 token 是否存在）
    const isLogin = currentUser && currentUser.userid;
    const queryString = stringify({
      redirect: window.location.href,
    });

    if ((!isLogin && loading) || !isReady) {
      return <PageLoading />;
    }
    if (!isLogin && window.location.pathname !== '/user/login') {
      return <Redirect to={`/user/login?${queryString}`} />;
    }
    return children;
  }
```

**Comment by chenshuai2144** [comment]
楼上正解
