### ISSUE TITLE
🐛[BUG]官网预览进不去 接口报404

### ISSUE THREAD

**Issue by dongliang36k** [ant-design/ant-design-pro#6229]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TianEnPang** [comment]
我这边官网预览没问题...

**Comment by chenshuai2144** [comment]
看这个 https://github.com/ant-design/ant-design-pro/issues/4705
