### ISSUE TITLE
添加区块的路径不对🧐[问题]

### ISSUE THREAD

**Issue by zhyunlong** [ant-design/ant-design-pro#6230]
### 🧐 问题描述

在新添加的空白页和初始的查询表格里添加区块，显示“区块将被安装到/layouts/BasicLayout”，在欢迎页添加区块可以正常添加，求教为什么

### 🚑 其他信息
前端小白，希望可以快速构建页面，感谢解答

![image](https://user-images.githubusercontent.com/24251496/77772395-0aa78980-7083-11ea-848e-fc3b3e372a0d.png)

**Comment by Ying-Git** [comment]
+1
