### ISSUE TITLE
🧐[问题]请教怎么修改内容区域的margin值？

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro#6231]
<img width="775" alt="margin" src="https://user-images.githubusercontent.com/26297547/77774274-c073d780-7085-11ea-91c0-ebdf4e6bb7a5.png">
### 🧐 问题描述

首先，官方、网上能搜到的文档都看了，花了好长时间，搞不清楚怎么修改上图中的margin的值，有不想放弃，希望官方能在此说明！

**Comment by chenshuai2144** [comment]
用css 覆盖吧，
为什么需要改动呢？

**Comment by fengnex** [comment]
能否具体说说怎么修改？
我试过改global.less等几个地方都不成功，我知道要覆盖，希望能真正落地实现，所以才具体问问，并且做了截图，烦请结合代码具体说说，多谢！

**Comment by fengnex** [comment]
@chenshuai2144 请教！

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/384
建议不要调整，没有很好地设计师，做出来的可能会很丑
美观是前端最核心的竞争力
