### ISSUE TITLE
🐛ProTable 能否动态改变页面字段参数？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6233]
### 🐛ProTable 能否动态改变页面字段参数？
total
pageSize
current

![image](https://user-images.githubusercontent.com/37643958/77779897-249a9980-708e-11ea-9db8-28d42284c89c.png)

**Comment by chenshuai2144** [comment]
没搞懂，你是希望修改 pageSzie 和 current 吗？

**Comment by zhfish** [comment]
他想修改字段名。。
和mybatis plus的page插件，默认字段名不一样

本来我也有这需求，后来自己处理兼容掉了

**Comment by chenshuai2144** [comment]
要自己兼容的，在 request 里面转化一下就好了
