### ISSUE TITLE
Start using English as a main language

### ISSUE THREAD

**Issue by cddumanov** [ant-design/ant-design-pro#6234]
Ant Design Pro is so nice library. So powerful. But so underrated in Europe at least because docs in English is poor. Github repo in Chinese. Some pages only in Chinese. Answers in Chinese. Yeah, maybe for people in Chine it's good and I respect it. But the standard language in the cosmopolitan worldwide community is English. Hope you understand me in the right way. No offense. Thanks

**Comment by joesdu** [comment]
> Ant Design Pro is so nice library. So powerful. But so underrated in Europe at least because docs in English is poor. Github repo in Chinese. Some pages only in Chinese. Answers in Chinese. Yeah, maybe for people in Chine it's good and I respect it. But the standard language in the cosmopolitan worldwide community is English. Hope you understand me in the right way. No offense. Thanks

You can still use English to ask the same questions, so that there are Chinese and English, both convenient for Chinese developers can also facilitate English users, if you mention the same questions, administrators or other personnel will also provide English version of the answer.

**Comment by cddumanov** [comment]
@joesdu But how can I find an issue if I don't know Chinese? They won't even appear in my search results.

**Comment by joesdu** [comment]
> @joesdu But how can I find an issue if I don't know Chinese? They won't even appear in my search results.
If the issue cannot be retrieved in English, you can try to use [Google Translate](https://translate.google.cn/#view=home&op=translate&sl=en&tl=zh-CN) or [Bing Translate](https://cn.bing.com/translator/?mkt=zh-CN) and retrieve in Chinese Simplified

**Comment by cddumanov** [comment]
@joesdu Ok, thanks

But may I ask you more general questions and you can be a representative person :) I'm Ukrainian bilingual. I speak Ukrainian and Russian. The community of developers that speaks these languages is less than the Chinese community of course. But I can barely remember repos where we used these languages except very local things like maps of Kyiv city or so. In 95% we use English. Why Chinese people don't do the same? It's a huge barrier to make e.g. ant design pro library which is great popular. In Ukraine some people use antd because this thing is nice and docs are normal in English. But nobody dgaf about ant design pro because of everything in Chinese. Can you explain me the mentality?

**Comment by afc163** [comment]
Because most Chinese developers don't speak English well like your guys, we simply cannot force other people using their main language.

**Comment by joesdu** [comment]
> @joesdu Ok, thanks
> 
> But may I ask you more general questions and you can be a representative person :) I'm Ukrainian bilingual. I speak Ukrainian and Russian. The community of developers that speaks these languages is less than the Chinese community of course. But I can barely remember repos where we used these languages except very local things like maps of Kyiv city or so. In 95% we use English. Why Chinese people don't do the same? It's a huge barrier to make e.g. ant design pro library which is great popular. In Ukraine some people use antd because this thing is nice and docs are normal in English. But nobody dgaf about ant design pro because of everything in Chinese. Can you explain me the mentality?

You can ask me if I know the answer.

**Comment by B-Esmaili** [comment]
Guys thank you for the framework but using it in Chinese is really a pain.after each page load i have to translate page into english. changing language to english is not as effective as it looks.If you've made it for chines people then you better make it completely chines but if it is an international thing then you should offer it in english. People don't have enough time to learn all languages after all.

**Comment by joesdu** [comment]
> Guys thank you for the framework but using it in Chinese is really a pain.after each page load i have to translate page into english. changing language to english is not as effective as it looks.If you've made it for chines people then you better make it completely chines but if it is an international thing then you should offer it in english. People don't have enough time to learn all languages after all.
> 
> ![Capture](https://user-images.githubusercontent.com/9152515/83434974-b210b600-a450-11ea-96a7-f8717837b5fa.PNG)

If you use the V5 AntDPro template, you can write default:en-US in the layout property of config.ts
![image](https://user-images.githubusercontent.com/13188169/83471084-58db6d80-a4b6-11ea-8cd3-f001f12e94da.png)
If you are using version V4, you can add the locale property en-US to the ProLayout component of BaseLayout.tsx in the src/layouts folder

**Comment by chenshuai2144** [comment]
google yes


Google Translate is recommended

**Comment by B-Esmaili** [comment]
![antd-pro](https://user-images.githubusercontent.com/9152515/86722110-dbb69180-c03b-11ea-85af-c977dc152975.gif)

Sorry for the delay in build process (rec) ,could you tell me what am i doing wrong changing language?
