### ISSUE TITLE
antd pro v4 下载安装所有的区块,日志未有异常，但无法运行🐛[BUG]

### ISSUE THREAD

**Issue by linkai0001** [ant-design/ant-design-pro#6235]
### 🐛 bug 描述

antd pro v4 下载安装所有的区块, 安装时无提示异常。运行脚手架时，异常信息如下（已经尝试过很多遍，都是一毛一样的结果额），异常信息如下： 
G:\temp\demo04>
yarn run v1.22.4
$ umi dev
🚀 Starting Umi UI using umi@3.0.14...
🌈 Umi UI mini Ready on port 3000

Starting the development server...
Cannot find module 'G:/temp/demo04/src/pages/list/search'
Require stack:
- G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js
- G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\index.js
- G:\temp\demo04\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
- G:\temp\demo04\node_modules\@umijs\core\lib\Service\Service.js
- G:\temp\demo04\node_modules\@umijs\core\lib\index.js
- G:\temp\demo04\node_modules\umi\lib\ServiceWithBuiltIn.js
- G:\temp\demo04\node_modules\umi\lib\forkedDev.js
Error: Cannot find module 'G:/temp/demo04/src/pages/list/search'
Require stack:
- G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js
- G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\index.js
- G:\temp\demo04\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
- G:\temp\demo04\node_modules\@umijs\core\lib\Service\Service.js
- G:\temp\demo04\node_modules\@umijs\core\lib\index.js
- G:\temp\demo04\node_modules\umi\lib\ServiceWithBuiltIn.js
- G:\temp\demo04\node_modules\umi\lib\forkedDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:63:77
    at Array.reduce (<anonymous>)
    at getComponents (G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:56:44)
    at G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:68:28
    at Array.reduce (<anonymous>)
    at getComponents (G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:56:44)
    at G:\temp\demo04\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:68:28
    at Array.reduce (<anonymous>)
Done in 9.29s.

### 📷 复现步骤

tyarn create umi
tyarn
tyarn fetch:blocks 
tyarn start

### 🏞 期望结果

访问到与  preview 相同的功能页面

### 💻 复现代码

tyarn create umi
tyarn
tyarn fetch:blocks 
tyarn start

### © 版本信息

- Ant Design Pro 版本:  antd pro v4
- umi@3.0.14
- 开发环境 window10

### 🚑 其他信息
执行 yarn fetch:blocks 日志信息如下

G:\temp\demo04>
yarn run v1.22.4yarn fetch:blocks
$ pro fetch-blocks --branch=umi@3 && npm run prettier
‼ 🧐  find config.ts ...
√ 🧐  find config.js ...
📦  install login  to: /user/login
👌  install login  to: /user/login success
📦  install register  to: /user/register
👌  install register  to: /user/register success
📦  install register.result  to: /user/register-result
👌  install register.result  to: /user/register-result success
📦  install analysis  to: /dashboard/analysis
👌  install analysis  to: /dashboard/analysis success
📦  install monitor  to: /dashboard/monitor
👌  install monitor  to: /dashboard/monitor success
📦  install workplace  to: /dashboard/workplace
👌  install workplace  to: /dashboard/workplace success
📦  install basicform  to: /form/basic-form
👌  install basicform  to: /form/basic-form success
📦  install stepform  to: /form/step-form
👌  install stepform  to: /form/step-form success
📦  install advancedform  to: /form/advanced-form
👌  install advancedform  to: /form/advanced-form success
📦  install searchtable  to: /list/table-list
👌  install searchtable  to: /list/table-list success
📦  install basiclist  to: /list/basic-list
👌  install basiclist  to: /list/basic-list success
📦  install cardlist  to: /list/card-list
👌  install cardlist  to: /list/card-list success
📦  install search-list  to: /list/search
👌  install search-list  to: /list/search success
📦  install articles  to: /list/search/articles
👌  install articles  to: /list/search/articles success
📦  install projects  to: /list/search/projects
👌  install projects  to: /list/search/projects success
📦  install applications  to: /list/search/applications
👌  install applications  to: /list/search/applications success
📦  install basic  to: /profile/basic
👌  install basic  to: /profile/basic success
📦  install advanced  to: /profile/advanced
👌  install advanced  to: /profile/advanced success
📦  install success  to: /result/success
👌  install success  to: /result/success success
📦  install fail  to: /result/fail
√ 🎁  insert BasicLayout successl success
√ 🎁  insert RightContent success
yarn --registry=https://registry.npm.taobao.orgsuccess
√ 🚚  install dependencies package
👌  install not-find  to: /exception/404 success
> ant-design-pro@1.0.0 prettier G:\temp\demo04
> prettier -c --write "**/*": /exception/500 success
📦  install center  to: /account/center
Checking formatting...: /account/center success
.eslintrc.js
.prettierrc.js
.stylelintrc.js
config\config.js
config\plugin.config.js
config\proxy.js
jest.config.js
jsconfig.json
mock\listTableList.js
src\components\Authorized\AuthorizedRoute.jsx
src\components\Authorized\CheckPermissions.jsx
src\components\Authorized\PromiseRender.jsx
src\components\Authorized\renderAuthorize.js
src\components\Authorized\Secured.jsx
src\components\GlobalHeader\AvatarDropdown.jsx
src\components\GlobalHeader\index.less
src\components\GlobalHeader\NoticeIconView.jsx
src\components\GlobalHeader\RightContent.jsx
src\components\HeaderDropdown\index.less
src\components\HeaderSearch\index.jsx
src\components\HeaderSearch\index.less
src\components\NoticeIcon\index.jsx
src\components\NoticeIcon\index.less
src\components\NoticeIcon\NoticeList.jsx
src\components\NoticeIcon\NoticeList.less
src\components\SelectLang\index.jsx
src\components\SelectLang\index.less
src\e2e\__mocks__\antd-pro-merge-less.js
src\e2e\baseLayout.e2e.js
src\e2e\getBrowser.js
src\e2e\topMenu.e2e.js
src\global.jsx
src\global.less
src\layouts\BasicLayout.jsx
src\layouts\UserLayout.jsx
src\layouts\UserLayout.less
src\manifest.json
src\models\global.js
src\models\setting.js
src\pages\404.jsx
src\pages\Admin.jsx
src\pages\Authorized.jsx
src\pages\document.ejs
src\pages\exception\403\index.jsx
src\pages\exception\404\index.jsx
src\pages\ListTableList\components\CreateForm.jsx
src\pages\ListTableList\components\UpdateForm.jsx
src\pages\ListTableList\index.jsx
src\pages\profile\advanced\data.d.ts
src\pages\profile\advanced\index.jsx
src\pages\profile\advanced\style.less
src\pages\profile\basic\data.d.ts
src\pages\profile\basic\index.jsx
src\pages\profile\basic\style.less
src\pages\Welcome.jsx
src\pages\Welcome.less
src\service-worker.js
src\utils\Authorized.js
src\utils\request.js
src\utils\utils.js
src\utils\utils.less
tests\run-tests.js
tests\setupTests.js
Code style issues fixed in the above file(s).
Done in 3325.32s.

**Comment by thinkingsim** [comment]
删掉.umi文件夹试试

**Comment by linkai0001** [comment]
hello , 刚才已经尝试删除 src 下的 .umi 文件夹，还是一样的异常额

**Comment by linkai0001** [comment]
此问题应该是必现问题，可以使用最新的版本代码做测试
tyarn create umi
tyarn
tyarn fetch:blocks
tyarn start

**Comment by TianEnPang** [comment]
> 此问题应该是必现问题，可以使用最新的版本代码做测试
> tyarn create umi
> tyarn
> tyarn fetch:blocks
> tyarn start

试过了，新建的项目，fetch:blocks没有报错，都显示安装成功，但是项目目录中没有并没有产生相应的文件，但是config中的路由有，启动时也是报和楼主一样的错。

**Comment by zhyblack** [comment]
同是天涯沦落人。

**Comment by D-wuque** [comment]
试了几次都是同样的报错，难搞

**Comment by TianEnPang** [comment]
**@chenshuai2144** 

- 你好，请问这个blocks的问题现在是个什么情况，我自己也没明白到底哪里错了

- `umi ui` 和 `fetch:blocks` 都没有用，即使在  `umi ui` 中 `clear` 后也是一样

- `fetch:blocks` 会更严重连page中Login的文件都给整没了😂

- 现在至少有3个issue来说的，麻烦官方解释一下如何解决此问题。

- 例： #6238 #6206

**Comment by chenshuai2144** [comment]
难搞 我无法复现，中间差了什么步骤吗

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/77827674-039b7c80-7152-11ea-92ec-ee6d288c1dfc.png)

![image](https://user-images.githubusercontent.com/8186664/77827742-668d1380-7152-11ea-978b-aa71ad538882.png)



各位需要更多的信息

**Comment by TianEnPang** [comment]
|  环境   | 版本  |
|  :----:  | :----:  |
| node  | 12.16.0 |
| yarn  | 1.22.0 |
| umi  | 3.0.14 |
| antd | 4.0.4 |
| windows | 1909 |

- ` yarn create umi ` - ` Ant Design Pro` - ` Typescript ` - `antd@4` - `yarn install` - `yarn start ` - 正常
- ` yarn fetch:blocks ` 安装所有Blocks
  执行到此处时（下图所示）` @/src/pages/user ` 下的所有文件会被删除，之后命令继续执行并无报错

  ![批注 2020-03-29 024103](https://user-images.githubusercontent.com/32772271/77830902-c7bee200-7166-11ea-949e-0d14ac2cd94e.png)
  
  安装过程缓慢（排除网络和性能问题）等待安装中...
  安装所有Blocks成功，并无报错，之后自动安装依赖包（下图所示）
  
  ![批注 2020-03-29 032157](https://user-images.githubusercontent.com/32772271/77831845-892c2600-716c-11ea-9bb9-3c674de728ac.png)
  
  安装依赖包完成，自动检查代码执行完成，并无报错（下图所示）
  
  ![批注 2020-03-29 032712](https://user-images.githubusercontent.com/32772271/77831934-3b63ed80-716d-11ea-9fd0-98a543b6be16.png)

  全部完成后 ` @/src/pages ` 只多了exception文件夹和profile文件夹，另外user文件夹下的所有内容在图一执行到 ` install login to: user/login ` 时被清空，原因未知（下图所示）

  ![批注 2020-03-29 031405](https://user-images.githubusercontent.com/32772271/77831649-677e6f00-716b-11ea-8ed9-224c2112f514.png)
  
  config.ts路由中未成功安装的Block的routes都是空（以下代码块所示）
  ```javascript
  routes: [
    {
      path: '/',
      component: '../layouts/BlankLayout',
      routes: [
        {
          path: '/user',
          component: '../layouts/UserLayout',
          routes: [
            {
              path: '/user',
              redirect: '/user/login',
            },
            {
              component: '404',
            },
          ],
        },
        {
          path: '/',
          component: '../layouts/BasicLayout',
          Routes: ['src/pages/Authorized'],
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/dashboard',
              name: 'dashboard',
              icon: 'dashboard',
              routes: [],
            },
            {
              path: '/form',
              icon: 'form',
              name: 'form',
              routes: [],
            },
            {
              path: '/list',
              icon: 'table',
              name: 'list',
              routes: [
                {
                  path: '/list/search',
                  name: 'search-list',
                  component: './list/search',
                  routes: [
                    {
                      path: '/list/search',
                      redirect: '/list/search/articles',
                    },
                  ],
                },
              ],
            },
            {
              path: '/profile',
              name: 'profile',
              icon: 'profile',
              routes: [
                {
                  name: 'basic',
                  icon: 'smile',
                  path: '/profile/basic',
                  component: './profile/basic',
                },
                {
                  name: 'advanced',
                  icon: 'smile',
                  path: '/profile/advanced',
                  component: './profile/advanced',
                },
              ],
            },
            {
              name: 'result',
              icon: 'CheckCircleOutlined',
              path: '/result',
              routes: [],
            },
            {
              name: 'exception',
              icon: 'warning',
              path: '/exception',
              routes: [
                {
                  name: '403',
                  icon: 'smile',
                  path: '/exception/403',
                  component: './exception/403',
                },
                {
                  name: '404',
                  icon: 'smile',
                  path: '/exception/404',
                  component: './exception/404',
                },
              ],
            },
            {
              name: 'account',
              icon: 'user',
              path: '/account',
              routes: [],
            },
            {
              name: 'editor',
              icon: 'highlight',
              path: '/editor',
              routes: [],
            },
            {
              path: '/',
              redirect: '/dashboard/analysis',
              authority: ['admin', 'user'],
            },
            {
              component: '404',
            },
          ],
        },
      ],
    },
  ]
  ```
- ` yarn start ` 启动项目报错（下图所示）

  ![批注 2020-03-29 034905](https://user-images.githubusercontent.com/32772271/77832345-4e2bf180-7170-11ea-8816-7fd82447268e.png)
  ```markdown
  yarn run v1.22.0
  $ umi dev
  🚀 Starting Umi UI using umi@3.0.14...
  🌈 Umi UI mini Ready on port 3000
  
  Starting the development server...
  Cannot find module 'C:/Users/tiane/Desktop/Demo/src/pages/list/search'
  Require stack:
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\index.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\core\lib\Service\Service.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\core\lib\index.js
  - C:\Users\tiane\Desktop\Demo\node_modules\umi\lib\ServiceWithBuiltIn.js
  - C:\Users\tiane\Desktop\Demo\node_modules\umi\lib\forkedDev.js
  Error: Cannot find module 'C:/Users/tiane/Desktop/Demo/src/pages/list/search'
  Require stack:
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\index.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\core\lib\Service\Service.js
  - C:\Users\tiane\Desktop\Demo\node_modules\@umijs\core\lib\index.js
  - C:\Users\tiane\Desktop\Demo\node_modules\umi\lib\ServiceWithBuiltIn.js
  - C:\Users\tiane\Desktop\Demo\node_modules\umi\lib\forkedDev.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
      at Function.resolve (internal/modules/cjs/helpers.js:83:19)
      at C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:63:77
      at Array.reduce (<anonymous>)
      at getComponents (C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-        blocks\lib\ui\index.js:56:44)
      at C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:68:28
      at Array.reduce (<anonymous>)
      at getComponents (C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-  blocks\lib\ui\index.js:56:44)
      at C:\Users\tiane\Desktop\Demo\node_modules\@umijs\plugin-ui-blocks\lib\ui\index.js:68:28
      at Array.reduce (<anonymous>)
  Done in 6.64s.
  ```
- - -
以上为 ` yarn fetch:blocks ` 失败的所有信息，如还需提供更多信息，请指明信息类型
我怀疑 ` umi ui ` 添加Blocks失败的原因和这个也有关系🤔
关于 ` umi ui ` 的更多报错信息可查看Issue #6206

**Comment by linkai0001** [comment]
hello , @TianenPang @chenshuai2144 
![mac](https://user-images.githubusercontent.com/24260681/77838258-d4fac180-71a4-11ea-89dc-2a171ed51eea.png)
mac 在执行 yarn fetch:blocks 时，差不多花了180s  左右 ， windwos 花了 2401s  左右， 连的是同一个  WiFi 额。  
mac 可以执行成功，并且运行成功。windwos 依然运行失败

**Comment by linkai0001** [comment]
补充 window 的完成时间照片
![(U4ZP{{W4HWO8R$%ILG2F2](https://user-images.githubusercontent.com/24260681/77838300-6b2ee780-71a5-11ea-8213-3ea39d4d17b0.png)

**Comment by linkai0001** [comment]
刚才又测试了 linux 系统发行版本 ubuntu ，虽然时间是1000S左右，可能和我连接的电脑（使用笔记本），虚拟机有关系（连的是同一个  wifi）。但是依然可以安装并运行成功。
综合上面所述，window 版本存在缺陷或我的windows 系统存在问题，重装系统是不可能了哈，需要你们使用 windwos 系统验证下额，当前windows版本是 window10。
@chenshuai2144 @TianenPang 

![image](https://user-images.githubusercontent.com/24260681/77838590-ef826a00-71a7-11ea-8a0f-80cd93010847.png)

**Comment by qianyue** [comment]
一样的错误

**Comment by linkai0001** [comment]
如果紧急的，可以直接直接通过 https://github.com/linkai0001/umi-all-blocks.git  项目得到所有区块的 umi 手脚架， 根目录下执行 tyarm  或  npm install 安装库即可额。

**Comment by TianenPang** [comment]
> 刚才又测试了 linux 系统发行版本 ubuntu ，虽然时间是1000S左右，可能和我连接的电脑（使用笔记本），虚拟机有关系（连的是同一个  wifi）。但是依然可以安装并运行成功。
> 
> 综合上面所述，window 版本存在缺陷或我的windows 系统存在问题，重装系统是不可能了哈，需要你们使用 windwos 系统验证下额，当前windows版本是 window10。
> 
> @chenshuai2144 @TianenPang 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/24260681/77838590-ef826a00-71a7-11ea-8a0f-80cd93010847.png)
> 
> 
> 
> 

不知如何在Windows验证具体的原因，这个问题是在我升级到umi@3后出现的。

**Comment by chenshuai2144** [comment]
看来是 windows 会出现问题，我来看一下

**Comment by chenshuai2144** [comment]
如果非常着急 可以通过 all-blocks 来拿到所有的分支，但是其中包含 pro 部署官网用的代码
使用时检查一下

**Comment by TianenPang** [comment]
> 如果非常着急 可以通过 all-blocks 来拿到所有的分支，但是其中包含 pro 部署官网用的代码
> 使用时检查一下

OK，谢谢

**Comment by TianenPang** [comment]
> 看来是 windows 会出现问题，我来看一下

刚才重新装了一下node ， yarn 和 umi 试了试，还是一样不行，一样的错误。

**Comment by wxz0107** [comment]
还没有修复呀 真头苦  下载都正常。 到pages里面 毛也没有

**Comment by TianenPang** [comment]
> 还没有修复呀 真头苦 下载都正常。 到pages里面 毛也没有

着急可以先到 [all-blocks](https://github.com/ant-design/ant-design-pro/tree/all-blocks) 里获取

问题等待官方后续的修复吧

**Comment by acebing** [comment]
我还以为只有我出现这种情况。。只能删除重新安装，想要的页面，用区块来实现吧

**Comment by D-wuque** [comment]
刚刚用公司的电脑试（win10）了下貌似问题已经修复了
```
yarn create umi
Select the boilerplate type ant-design-pro
ich language do you want to use? JavaScript
 you need all the blocks or a simple scaffold? complete
tyarn
yarn start
```

**Comment by chenshuai2144** [comment]
推荐使用 yarn create umi 来获得所有的区块。fetch:blocks 对网络要求太高，日志也不友好。

**Comment by leesumen** [comment]
> 推荐使用 yarn create umi 来获得所有的区块。fetch:blocks 对网络要求太高，日志也不友好。

大多数情况下，我只拉取某一个模板来进行修改，自从升级至umi3.0之后，直接通过添加模板的方式，始终失败；
`Cloning into 'github.com/ant-design/pro-blocks'...
🎉  Success git clone

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Branch 'umi@3' set up to track remote branch 'umi@3' from 'origin'.
Switched to a new branch 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/---/.umi3/blocks/github.com/ant-design/pro-blocks/ListCardList/src/utils


🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/---/.umi3/blocks/github.com/ant-design/pro-blocks/ListCardList/src/utils
🚚  Start git clone from https://gitee.com/ant-design/pro-blocks.git
Cloning into 'github.com/ant-design/pro-blocks'...
🎉  Success git clone

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Branch 'umi@3' set up to track remote branch 'umi@3' from 'origin'.
Switched to a new branch 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/---/.umi3/blocks/github.com/ant-design/pro-blocks/ListCardList/src/utils


🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/---/.umi3/blocks/github.com/ant-design/pro-blocks/ListCardList/src/utils`

**Comment by ffalconjs** [comment]
$ yarn create umi
yarn create v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.21.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🚀 Do you need all the blocks or a simple scaffold? complete

$ yarn
$ yarn start

然后会不停的刷日志，无法运行

**Comment by ffalconjs** [comment]
一直处于 building

**Comment by cdrcool** [comment]
> 推荐使用 yarn create umi 来获得所有的区块。fetch:blocks 对网络要求太高，日志也不友好。

咋获取所有区块呢？选择了 complete，结果还是 simple！

**Comment by afc163** [comment]
现在可以直接 `git clone git@github.com:ant-design/ant-design-pro.git -b all-blocks` 来下载所有区块完整版本的 pro 代码。

**Comment by afc163** [comment]
> 现在可以直接 git clone git@github.com:ant-design/ant-design-pro.git -b all-blocks 来下载所有区块完整版本的 pro 代码。

@chenshuai2144 这句官方文档里也补充一下，包括 create umi 的完整使用方式。

**Comment by yuejie89** [comment]
这次升级有点升的太猛了  表示受伤

**Comment by chenshuai2144** [comment]
@yuejie89  是依赖库在 window 下的bug。我们正在推动修复

**Comment by Tenodec** [comment]
win 10  node 12.13   同样遇到这个问题，只能新建的时候选择complete才没问题。如果选择simple ，之后只能添加空白页，添加其他的block都会报错

**Comment by gongcheng121** [comment]
只要你添加的模板文件中，没有components 这样的子目录的，都可以添加成功的
