### ISSUE TITLE
新版pro js版本使用npm run lint报错🧐[问题]

### ISSUE THREAD

**Issue by TnWah** [ant-design/ant-design-pro#6236]
### 🧐 问题描述

刚新建的项目测试了下，安装依赖后都正常，就是lint相关命令报错
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/27721311/77817454-d75a0e80-7105-11ea-82ce-95a4977e45b1.png)

**Comment by TnWah** [comment]
在以前版本项目中试了下运行正常，最新的失败。。

**Comment by chenshuai2144** [comment]
看报错是 eslint 安装失败导致的
试试 tyarn 来安装

**Comment by afc163** [comment]
@chenshuai2144 eslint 要放 devDependencies 里，因为用到了。
