### ISSUE TITLE
npm run fetch:blocks无法将模块拉取到本地，启动时直接在src中无对应的文件

### ISSUE THREAD

**Issue by cqrcgslinbin** [ant-design/ant-design-pro#6238]
npm run fetch:blocks无法将模块拉取到本地，启动时直接在src中无对应的文件

**Comment by zhyblack** [comment]
我也是唉，
Error: Cannot find module 'C:/God/web_worker/web/src/pages/list/search'

**Comment by D-wuque** [comment]
看来我并不孤独

**Comment by xyzabc0004** [comment]
我也是这个

**Comment by chenshuai2144** [comment]
看这里 
https://github.com/ant-design/ant-design-pro/issues/6235
