### ISSUE TITLE
👑 [需求]权限控制可以升级到@umijs/plugin-access的useAccess吗？

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#6241]
### 🥰 需求描述
权限控制可以升级到@umijs/plugin-access的useAccess吗？

### 🧐 解决方案

直接使用@umijs/plugin-access的useAccess来进行antd pro的权限控制

**Comment by chenshuai2144** [comment]
这就是最佳实践的工作，可以关注
https://github.com/ant-design/ant-design-pro/issues/6023
