### ISSUE TITLE
添加区块报错--Can not find insert position🐛[BUG]

### ISSUE THREAD

**Issue by hefengly** [ant-design/ant-design-pro#6242]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/28841926/77845440-8d465b00-71e1-11ea-93f1-5d500e5c7da2.png)
### 📷 复现步骤

新建空白页，添加区块

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 umi@3.0.14.
- 浏览器环境 谷歌
- 开发环境 win 10

**Comment by ycjcl868** [comment]
是约定式路由吗？

**Comment by hefengly** [comment]
> 是约定式路由吗？

是的

**Comment by zhubaobao** [comment]
请问是否已经解决，我也遇到了同样的问题

**Comment by tyxf** [comment]
还有，npm run ui。。根本是一个无效的指令啊
