### ISSUE TITLE
gg-editor 组件🧐[问题]

### ISSUE THREAD

**Issue by linkai0001** [ant-design/ant-design-pro#6244]
### 🧐 问题描述

hello , antd pro v4  集成了 流程编辑器 的区块， 他是使用了 gg-editor 的组件。
不仅仅只有 Flow 或 Mind 组件， 他还内置了大量的其他辅助组件，比如 CanvasPanel, DetailPanel, EdgePanel, GroupPanel, MultiPanel, NodePanel， Item, ItemPanel， Minimap， Toolbar .... 等等 ， 当然组件也有相关属性配置。这些有相关文档具体描述吗？  目前还未找到其功能文档额，语雀wen文档 https://www.yuque.com/ggeditor/api/flow 有对 gg-editor 的描述， 主要是围绕 flow 和 mind 组件而已

**Comment by afc163** [comment]
你或许应该去 https://github.com/alibaba/GGEditor/issues 里咨询。
