### ISSUE TITLE
i18n page is not relevant 

### ISSUE THREAD

**Issue by cddumanov** [ant-design/ant-design-pro#6245]
i18n docs page is not relevant. Can't use any of the described functional. Why docs are so poor?

https://pro.ant.design/docs/i18n

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/363
https://umijs.org/plugins/plugin-locale
look here，we will update doc  for site

**Comment by cddumanov** [comment]
@chenshuai2144 Since you only the person who responds. Can I ask you why do ant design uses Chinese too much and do not stick to the policy use English as the main language? Sometimes docs half translated. UMI UI in Chinese. Why it does like this? Are there any plans to change this? And why docs are soo poor?
