### ISSUE TITLE
PC端默认进入系统的时候，侧边栏为折叠状态，除非点击展开icon，不然就一直是折叠状态

### ISSUE THREAD

**Issue by reng99** [ant-design/ant-design-pro#6246]
### 🧐 问题描述

PC端默认进入系统的时候，侧边栏为折叠状态，除非点击展开icon，不然就一直是折叠状态。拜谢！

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22773901/77881747-2fbe1700-7292-11ea-958d-e37121ff5441.png)

**Comment by chenshuai2144** [comment]
你这是需求吗？
```
breakpoint={false} 
collapsed={true}
onCollapse={}
```
做成受控模式就可以了，breakpoint 会根据屏幕大小来自动确定是都需要展开收起

**Comment by reng99** [comment]
@chenshuai2144 【刚想关闭此issues就看到回复，很给力，点赞】我之前阅读了文档，是按照您这种操作的，不能满足；刚才我改了model/global.ts下的collapsed为true就可以了，如下：
![image](https://user-images.githubusercontent.com/22773901/77883849-8168a080-7296-11ea-93a6-29ca6f16d3a7.png)
![image](https://user-images.githubusercontent.com/22773901/77883873-8e858f80-7296-11ea-86a3-12dd4c2fafed.png)

**Comment by chenshuai2144** [comment]
被 model 覆盖了。
补充的很棒，给你点赞

**Comment by chengmings** [comment]
你说的这个文档是在哪里看的 我在你这里满足了我的需求 我还是想再看看文档学习学习其他的

**Comment by reng99** [comment]
> 你说的这个文档是在哪里看的 我在你这里满足了我的需求 我还是想再看看文档学习学习其他的

可以看看项目下node_module的ant-design下的相关组件参数

**Comment by chengmings** [comment]
> > 你说的这个文档是在哪里看的 我在你这里满足了我的需求 我还是想再看看文档学习学习其他的
> 
> 可以看看项目下node_module的ant-design下的相关组件参数

好的谢谢
