### ISSUE TITLE
👑 [需求]操作菜单实现顶部为一级菜单，左侧为二级菜单

### ISSUE THREAD

**Issue by cqrcgslinbin** [ant-design/ant-design-pro#6247]
### 🥰 需求描述
ant-design-pro可实现顶部一级菜单，左侧为二级菜单吗？
![image](https://user-images.githubusercontent.com/47732987/77885227-3bf9a280-7299-11ea-8242-1facead7871a.png)
类似于这样的效果

**Comment by chenshuai2144** [comment]
试试这个
https://prolayout.ant.design/example#%E5%8F%A6%E5%A4%96%E4%B8%80%E7%A7%8D%E5%B5%8C%E5%A5%97%E5%B8%83%E5%B1%80
