### ISSUE TITLE
 Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist 🐛[BUG]

### ISSUE THREAD

**Issue by yuejie89** [ant-design/ant-design-pro#6248]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/36728384/77889588-acf08880-72a0-11ea-9f9a-819f95e2a0f1.png)

### 📷 复现步骤

tyarn create umi
tyarn
tyarn fetch:blocks

### 🏞 期望结果

访问到 ant-design-pro 2版本的所有页面

### 💻 复现代码

D:\jiateng\test\ant-design-pro4>tyarn fetch:blocks
yarn run v1.15.2
$ pro fetch-blocks --branch=umi@3 && npm run prettier
√ 😁  find config.ts ...
(node:14064) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (D:\jiateng\test\ant-design-pro4\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:209:13)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:14064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> ant-design-pro@1.0.0 prettier D:\jiateng\test\ant-design-pro4
> prettier -c --write "**/*"

Checking formatting...
.eslintrc.js
.prettierrc.js
.stylelintrc.js
config\config.ts
config\defaultSettings.ts
config\plugin.config.ts
config\proxy.ts
jest.config.js
jsconfig.json
mock\listTableList.ts
mock\notices.ts
mock\route.ts
mock\user.ts
src\components\Authorized\Authorized.tsx
src\components\Authorized\AuthorizedRoute.tsx
src\components\Authorized\CheckPermissions.tsx
src\components\Authorized\index.tsx
src\components\Authorized\PromiseRender.tsx
src\components\Authorized\renderAuthorize.ts
src\components\Authorized\Secured.tsx
src\components\GlobalHeader\AvatarDropdown.tsx
src\components\GlobalHeader\index.less
src\components\GlobalHeader\NoticeIconView.tsx
src\components\GlobalHeader\RightContent.tsx
src\components\HeaderDropdown\index.less
src\components\HeaderDropdown\index.tsx
src\components\HeaderSearch\index.less
src\components\HeaderSearch\index.tsx
src\components\NoticeIcon\index.less
src\components\NoticeIcon\index.tsx
src\components\NoticeIcon\NoticeList.less
src\components\NoticeIcon\NoticeList.tsx
src\components\PageLoading\index.tsx
src\components\SelectLang\index.less
src\components\SelectLang\index.tsx
src\e2e\__mocks__\antd-pro-merge-less.js
src\e2e\baseLayout.e2e.js
src\e2e\getBrowser.js
src\e2e\topMenu.e2e.js
src\global.less
src\global.tsx
src\layouts\BasicLayout.tsx
src\layouts\BlankLayout.tsx
src\layouts\SecurityLayout.tsx
src\layouts\UserLayout.less
src\layouts\UserLayout.tsx
src\locales\en-US.ts
src\locales\en-US\component.ts
src\locales\en-US\globalHeader.ts
src\locales\en-US\menu.ts
src\locales\en-US\pwa.ts
src\locales\en-US\settingDrawer.ts
src\locales\en-US\settings.ts
src\locales\pt-BR.ts
src\locales\pt-BR\component.ts
src\locales\pt-BR\globalHeader.ts
src\locales\pt-BR\menu.ts
src\locales\pt-BR\pwa.ts
src\locales\pt-BR\settingDrawer.ts
src\locales\pt-BR\settings.ts
src\locales\zh-CN.ts
src\locales\zh-CN\component.ts
src\locales\zh-CN\globalHeader.ts
src\locales\zh-CN\menu.ts
src\locales\zh-CN\pwa.ts
src\locales\zh-CN\settingDrawer.ts
src\locales\zh-CN\settings.ts
src\locales\zh-TW.ts
src\locales\zh-TW\component.ts
src\locales\zh-TW\globalHeader.ts
src\locales\zh-TW\menu.ts
src\locales\zh-TW\pwa.ts
src\locales\zh-TW\settingDrawer.ts
src\locales\zh-TW\settings.ts
src\manifest.json
src\models\connect.d.ts
src\models\global.ts
src\models\login.ts
src\models\setting.ts
src\models\user.ts
src\pages\404.tsx
src\pages\Admin.tsx
src\pages\Authorized.tsx
src\pages\document.ejs
src\pages\ListTableList\components\CreateForm.tsx
src\pages\ListTableList\components\UpdateForm.tsx
src\pages\ListTableList\data.d.ts
src\pages\ListTableList\index.tsx
src\pages\ListTableList\service.ts
src\pages\user\login\components\Login\index.less
src\pages\user\login\components\Login\index.tsx
src\pages\user\login\components\Login\LoginContext.tsx
src\pages\user\login\components\Login\LoginItem.tsx
src\pages\user\login\components\Login\LoginSubmit.tsx
src\pages\user\login\components\Login\LoginTab.tsx
src\pages\user\login\components\Login\map.tsx
src\pages\user\login\index.tsx
src\pages\user\login\style.less
src\pages\Welcome.less
src\pages\Welcome.tsx
src\service-worker.js
src\services\login.ts
src\services\user.ts
src\typings.d.ts
src\utils\authority.ts
src\utils\Authorized.ts
src\utils\request.ts
src\utils\utils.less
src\utils\utils.test.ts
src\utils\utils.ts
tests\run-tests.js
tests\setupTests.js
tsconfig.json
Code style issues fixed in the above file(s).
Done in 3.45s.

D:\jiateng\test\ant-design-pro4>tyarn
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.67s.

D:\jiateng\test\ant-design-pro4>tyarn fetch:blocks
yarn run v1.15.2
$ pro fetch-blocks --branch=umi@3 && npm run prettier
√ 🧐  find config.ts ...
📦  install login  to: /user/login
- 😁  Parse url and args
√ 😁  Parse url and args
- 🔍  clone git repo from https://gitee.com/ant-design/pro-blocks.git
Cloning into 'github.com/ant-design/pro-blocks'...
√ 🔍  clone git repo from https://gitee.com/ant-design/pro-blocks.git
- 📦  install dependencies package
√ 📦  install dependencies package
- 🔥  Generate files
  🔥  Generate files
× 🔥  Generate files
×  error     Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/UserLogin/src/components
    at D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:332:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _throw (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
👌  install login  to: /user/login success
📦  install register  to: /user/register
- 😁  Parse url and args
√ 😁  Parse url and args
- 🚒  Git fetch
√ 🚒  Git fetch
- 🚛  Git checkout umi@3
Branch umi@3 set up to track remote branch umi@3 from origin.
Switched to a new branch 'umi@3'
√ 🚛  Git checkout umi@3
- 🚀  Git pull
Already up-to-date.
√ 🚀  Git pull
- 📦  install dependencies package
√ 📦  install dependencies package
- 🔥  Generate files
  🔥  Generate files
× 🔥  Generate files
×  error     Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegister/src/locales
    at D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:332:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _throw (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
👌  install register  to: /user/register success
📦  install register.result  to: /user/register-result
- 😁  Parse url and args
√ 😁  Parse url and args
- 🚒  Git fetch
√ 🚒  Git fetch
- 🚛  Git checkout umi@3
Your branch is up-to-date with 'origin/umi@3'.
Already on 'umi@3'
√ 🚛  Git checkout umi@3
- 🚀  Git pull
Already up-to-date.
√ 🚀  Git pull
- 📦  install dependencies package
√ 📦  install dependencies package
- 🔥  Generate files
  🔥  Generate files
× 🔥  Generate files
×  error     Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegisterResult/src/locales
    at D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:332:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _throw (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
👌  install register.result  to: /user/register-result success
📦  install analysis  to: /dashboard/analysis
- 😁  Parse url and args
√ 😁  Parse url and args
- 🚒  Git fetch
√ 🚒  Git fetch
- 🚛  Git checkout umi@3
Your branch is up-to-date with 'origin/umi@3'.
Already on 'umi@3'
√ 🚛  Git checkout umi@3
- 🚀  Git pull
Already up-to-date.
√ 🚀  Git pull
- 📦  install dependencies package
√ 📦  install dependencies package
- 🔥  Generate files
  🔥  Generate files
× 🔥  Generate files
×  error     Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/DashboardAnalysis/src/components
    at D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:332:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _throw (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
👌  install analysis  to: /dashboard/analysis success
📦  install monitor  to: /dashboard/monitor
- 😁  Parse url and args
√ 😁  Parse url and args
- 🚒  Git fetch
√ 🚒  Git fetch
- 🚛  Git checkout umi@3
Your branch is up-to-date with 'origin/umi@3'.
Already on 'umi@3'
√ 🚛  Git checkout umi@3
- 🚀  Git pull
Already up-to-date.
√ 🚀  Git pull
- 📦  install dependencies package
√ 📦  install dependencies package
- 🔥  Generate files
  🔥  Generate files
× 🔥  Generate files
×  error     Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/DashboardMonitor/src/components
    at D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:332:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _throw (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
👌  install monitor  to: /dashboard/monitor success
📦  install workplace  to: /dashboard/workplace
- 😁  Parse url and args
√ 😁  Parse url and args
- 🚒  Git fetch
√ 🚒  Git fetch
- 🚛  Git checkout umi@3
Your branch is up-to-date with 'origin/umi@3'.
Already on 'umi@3'
√ 🚛  Git checkout umi@3
- 🚀  Git pull
Already up-to-date.
√ 🚀  Git pull
- 📦  install dependencies package
√ 📦  install dependencies package
- 🔥  Generate files
  🔥  Generate files
× 🔥  Generate files
×  error     Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi3/blocks/github.com/ant-design/pro-blocks/DashboardWorkplace/src/components
    at D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:332:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _throw (D:\jiateng\test\ant-design-pro4\node_modules\@umijs\block-sdk\lib\addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/6235
