### ISSUE TITLE
🐛[BUG]一级菜单设置权限可以控制访，二级菜单设置了权限却无法控制权限

### ISSUE THREAD

**Issue by tonyjync** [ant-design/ant-design-pro#6249]
### 🐛 bug 描述

我显示的菜单是从后台读取的，其了配置是2月份在github上下载的pro代码，测试发现在一级菜单(说明：config.ts-->component: '../layouts/BasicLayout', routes[]，routes里配置的菜单，页面展示为一级)配置全权是可以控制没有设置权限的用户不能通过菜单地址访问页面的，但是权限配置放在再下一级时，就不能生效，不知道为什么？
如果只能控制一级菜单，遇到二级菜单需要配置权限的时候就不好控制。
config.ts 

### 📷 复现步骤

测试使用的是官网上自带的二级目录配置：
  config.ts配置权限有效的如下：
{
              path: '/admin',
              name: 'admin',
              icon: 'crown',
              authority: ['admin'],
              routes: [
                {
                  path: '/admin/sub-page',
                  name: 'sub-page',
                  icon: 'smile',
                  component: './Welcome',
                  
                },
              ],
            },
配置权限无效的如下：
{
              path: '/admin',
              name: 'admin',
              icon: 'crown',
              routes: [
                {
                  path: '/admin/sub-page',
                  name: 'sub-page',
                  icon: 'smile',
                  component: './Welcome',
                  authority: ['admin'],
                },
              ],
            },

### 🏞 期望结果

希望官方提供解决办法，谢谢！

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

有效的截图（显示403）：
![image](https://user-images.githubusercontent.com/40910386/77893108-1a52e800-72a6-11ea-97bd-c4b963ed5b85.png)
无效的截图（正常显示）：
![image](https://user-images.githubusercontent.com/40910386/77893465-86cde700-72a6-11ea-8009-f81f73d03b28.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/5933

看这个 pr，如果代码没有很多，建议使用 https://umijs.org/plugins/plugin-access

**Comment by tonyjync** [comment]
谢谢您的回复，问题已经解决了。
