### ISSUE TITLE
🧐[问题]package.json里面的checkFiles create-um这些配置是作用是什么？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#6251]
### 🧐 问题描述
package.json里面的checkFiles create-um这些配置是作用是什么，有没有介绍的文档？

**Comment by joesdu** [comment]
> ### 🧐 问题描述
> package.json里面的checkFiles create-um这些配置是作用是什么，有没有介绍的文档？

{
  "name": "myprojectname",
  "version": "1.1",
  "private": true,
  "description": "myprojectdescription",
  "scripts": {
    "build": "umi build",
    "start": "cross-env PORT=8848 umi dev",
    "plugin": "umi plugin list --key",
    "postinstall": "umi g tmp",
    "analyze": "cross-env ANALYZE=1 umi build"
  },
  "dependencies": {
    "@ant-design/icons": "^4.0.5",
    "@ant-design/pro-layout": "^5.0.8",
    "@antv/data-set": "^0.11.1",
    "antd": "^4.1.0",
    "bizcharts": "^3.5.8",
    "classnames": "^2.2.6",
    "dayjs": "^1.8.23",
    "dva": "2.6.0-beta.20",
    "lodash": "^4.17.15",
    "path-to-regexp": "^6.1.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^5.2.1",
    "umi": "^3.0.16",
    "umi-request": "^1.2.19"
  },
  "devDependencies": {
    "@types/classnames": "^2.2.10",
    "@types/express": "^4.17.3",
    "@types/lodash": "^4.14.149",
    "@types/react": "^16.9.29",
    "@types/react-dom": "^16.9.5",
    "@types/react-helmet": "^5.0.15",
    "@umijs/fabric": "^2.0.6",
    "@umijs/preset-ant-design-pro": "^1.1.2",
    "@umijs/preset-react": "^1.4.8",
    "chalk": "^3.0.0",
    "cross-env": "^7.0.2",
    "cross-port-killer": "^1.2.1",
    "express": "^4.17.1"
  },
  "engines": {
    "node": ">=13.5.0"
  }
}


这个是我目前精简后的package文件.我将ESLint和Prettier以及imports-sort,TSLint等功能都通过VS Code插件来支持,这样的好处就是每次换电脑安装依赖快很多.每次提交和运行都不会Lint一次.还把部分我没有使用的包也给删掉了.

**Comment by shaohuatsou** [comment]
> > ### 🧐 问题描述
> > package.json里面的checkFiles create-um这些配置是作用是什么，有没有介绍的文档？
> 
> {
> "name": "myprojectname",
> "version": "1.1",
> "private": true,
> "description": "myprojectdescription",
> "scripts": {
> "build": "umi build",
> "start": "cross-env PORT=8848 umi dev",
> "plugin": "umi plugin list --key",
> "postinstall": "umi g tmp",
> "analyze": "cross-env ANALYZE=1 umi build"
> },
> "dependencies": {
> "@ant-design/icons": "^4.0.5",
> "@ant-design/pro-layout": "^5.0.8",
> "@antv/data-set": "^0.11.1",
> "antd": "^4.1.0",
> "bizcharts": "^3.5.8",
> "classnames": "^2.2.6",
> "dayjs": "^1.8.23",
> "dva": "2.6.0-beta.20",
> "lodash": "^4.17.15",
> "path-to-regexp": "^6.1.0",
> "react": "^16.13.1",
> "react-dom": "^16.13.1",
> "react-helmet": "^5.2.1",
> "umi": "^3.0.16",
> "umi-request": "^1.2.19"
> },
> "devDependencies": {
> "@types/classnames": "^2.2.10",
> "@types/express": "^4.17.3",
> "@types/lodash": "^4.14.149",
> "@types/react": "^16.9.29",
> "@types/react-dom": "^16.9.5",
> "@types/react-helmet": "^5.0.15",
> "@umijs/fabric": "^2.0.6",
> "@umijs/preset-ant-design-pro": "^1.1.2",
> "@umijs/preset-react": "^1.4.8",
> "chalk": "^3.0.0",
> "cross-env": "^7.0.2",
> "cross-port-killer": "^1.2.1",
> "express": "^4.17.1"
> },
> "engines": {
> "node": ">=13.5.0"
> }
> }
> 
> 这个是我目前精简后的package文件.我将ESLint和Prettier以及imports-sort,TSLint等功能都通过VS Code插件来支持,这样的好处就是每次换电脑安装依赖快很多.每次提交和运行都不会Lint一次.还把部分我没有使用的包也给删掉了.

其实我是想知道具体是什么意思，想了解了解。

**Comment by joesdu** [comment]
不同的依赖包,有不一样的脚本.这些东西都是相应包的一些命令或者配置参数.

**Comment by shaohuatsou** [comment]
> 不同的依赖包,有不一样的脚本.这些东西都是相应包的一些命令或者配置参数.

嗯好吧，反正也没找到关于这方面的文档。

**Comment by joesdu** [comment]
> > 不同的依赖包,有不一样的脚本.这些东西都是相应包的一些命令或者配置参数.
> 
> 嗯好吧，反正也没找到关于这方面的文档。

http://caibaojian.com/npm/files/package.json.html

虽然没有你说的那几个参数,但是这个文档已经说的很详细了.

**Comment by chenshuai2144** [comment]
create-umi 是为了给 create umi 用的在新建项目之后需要删除的文件。

checkFiles 应该被删掉，已经移除了那个库。

**Comment by shaohuatsou** [comment]
> create-umi 是为了给 create umi 用的在新建项目之后需要删除的文件。
> 
> checkFiles 应该被删掉，已经移除了那个库。



> > > 不同的依赖包,有不一样的脚本.这些东西都是相应包的一些命令或者配置参数.
> > 
> > 
> > 嗯好吧，反正也没找到关于这方面的文档。
> 
> http://caibaojian.com/npm/files/package.json.html
> 
> 虽然没有你说的那几个参数,但是这个文档已经说的很详细了.

感谢两位。
