### ISSUE TITLE
🧐[问题]不知道有没有Upload组件dva的实现方式?

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6252]
### 🧐 问题描述

不知道有没有Upload组件dva的实现方式?项目中大量的文件上传地方,每次都写一次props,感觉很烦,而且将action也写在组件中,看起来很不舒服.希望能有一个使用dva的实现例子.

**Comment by chenshuai2144** [comment]
文件上传接口应该是一个单独的接口，上传一个文件，返货一个 oss 的 id，后端取消ossid，所有 上传组件才会把 action 也包进去这样比较简单。


如果你想把文件也放到 dva 中的话，可以只利用 upload 的 fileList 能力

**Comment by joesdu** [comment]
> 文件上传接口应该是一个单独的接口，上传一个文件，返货一个 oss 的 id，后端取消ossid，所有 上传组件才会把 action 也包进去这样比较简单。
> 
> 如果你想把文件也放到 dva 中的话，可以只利用 upload 的 fileList 能力

了解了
