### ISSUE TITLE
Ant Design Pro 开启默认进入登录页

### ISSUE THREAD

**Issue by fuwin** [ant-design/ant-design-pro#6258]
怎么设置能首次直接进入登录页 无论什么权限 都从登录页面进入

**Comment by huntdream** [comment]
我的想法是在localStorage里面设置一个flag，考虑到多标签的情况，flag可以是当前窗口的数量，新增+1，关闭-1，为0时需要登录

**Comment by joesdu** [comment]
> 我的想法是在localStorage里面设置一个flag，考虑到多标签的情况，flag可以是当前窗口的数量，新增+1，关闭-1，为0时需要登录

在request里边设置拦截器,在本地设置一个localStorage用于记录每次请求的时间戳.然后再在SecurityLayout中判断localStorage中的时间戳和当前Data.now()的时间戳的差值.若是大于你设定的值就路由到login,若是小于就说明登陆没有超时,正常加载页面.

**Comment by huntdream** [comment]
> > 我的想法是在localStorage里面设置一个flag，考虑到多标签的情况，flag可以是当前窗口的数量，新增+1，关闭-1，为0时需要登录
> 
> 在request里边设置拦截器,在本地设置一个localStorage用于记录每次请求的时间戳.然后再在SecurityLayout中判断localStorage中的时间戳和当前Data.now()的时间戳的差值.若是大于你设定的值就路由到login,若是小于就说明登陆没有超时,正常加载页面.

这种的话应该由后端来设置用户身份信息失效好一点吧

**Comment by joesdu** [comment]
> > > 我的想法是在localStorage里面设置一个flag，考虑到多标签的情况，flag可以是当前窗口的数量，新增+1，关闭-1，为0时需要登录
> > 
> > 在request里边设置拦截器,在本地设置一个localStorage用于记录每次请求的时间戳.然后再在SecurityLayout中判断localStorage中的时间戳和当前Data.now()的时间戳的差值.若是大于你设定的值就路由到login,若是小于就说明登陆没有超时,正常加载页面.
> 
> 这种的话应该由后端来设置用户身份信息失效好一点吧

反正我们公司后端没做😂

**Comment by hankaibo** [comment]
获取权限，获取到就进入菜单页；获取不到就进入登录页要求登录。
我有一份不成熟的版本，请参考。https://github.com/hankaibo/myantdpro

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/blob/bf3abbb89918f6f34d3f4967e2497c4301eca53f/src/utils/authority.ts#L21
这里关了，就好
