### ISSUE TITLE
请问带中间参数的路由如何跳转

### ISSUE THREAD

**Issue by jutian88** [ant-design/ant-design-pro#626]
![lalpbbcc1u2tl2fna6hnbfy_1110_929](https://user-images.githubusercontent.com/30802089/34702698-1aa5a7bc-f52a-11e7-8fa6-45697d5aa068.png)

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-pro/commit/577ded4b3440c99b3b1ecc76bda55e25389ab818#r26682818

**Comment by yesmeck** [comment]
@ddcat1115 这里的设计是不是调整下？

**Comment by chenshuai2144** [comment]
我调整了一下 #613 
但是这种中间参数。。。。。

**Comment by chenshuai2144** [comment]
@jutian88   你关闭掉 getRelation 这个方法 就能跳转三级路由了

**Comment by chenshuai2144** [comment]
@ddcat1115  至少三级路由要放开了。。
而且面包屑需要用正则匹配了

**Comment by jutian88** [comment]
按照你的建议, 找到了getRelation调用,请问如何修改
![image](https://user-images.githubusercontent.com/30802089/34703127-4263987a-f52c-11e7-9bd2-db6596e2b65e.png)

**Comment by jutian88** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
isAdd = true 就行了。

**Comment by jutian88** [comment]
@chenshuai2144 我尝试把参数放置至最后, 并删除isAdd过滤, 依旧不行, 只能跳转到vehicle路径
![qq 20180109112930](https://user-images.githubusercontent.com/30802089/34703877-65952648-f530-11e7-9699-3fd36a2f987e.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34704018-2cedc754-f531-11e7-9084-aea3eb685170.png)
这个也要也要去掉 ，忘记告诉你了

**Comment by jutian88** [comment]
@chenshuai2144 还是不可行...

**Comment by chenshuai2144** [comment]
给我看看你得嗲吗

**Comment by jutian88** [comment]
@chenshuai2144 刚刚已经试出来了, 我将下面的exact默认为true即可, 用不到getRelation方法和判断exact条件

**Comment by chenshuai2144** [comment]
那也贴一下代码吧。。。。
我都晕了

**Comment by JoeyKo** [comment]
@ jutian88  `path` 里为什么加上 `info` 感觉多余

**Comment by jutian88** [comment]
@chenshuai2144 跳转至详情页面, 业务需要~

**Comment by jutian88** [comment]
@chenshuai2144 马上哦

**Comment by chenshuai2144** [comment]
嗯

**Comment by jutian88** [comment]
![qq 20180109115845](https://user-images.githubusercontent.com/30802089/34704515-77baafe2-f534-11e7-9ae1-d81957ff8f08.png)

直接默认exact: true能够使得路由的匹配更严格一些, /vehicle页面必须完全匹配后才能跳转,这样就可以实现子路由跳转

**Comment by chenshuai2144** [comment]
soga  看懂了，留着帮助一下以后的人

**Comment by jutian88** [comment]
@chenshuai2144 谢谢你啦, 告辞~

**Comment by chenshuai2144** [comment]
没帮上什么大忙

**Comment by ddcat1115** [comment]
> 你关闭掉 getRelation 这个方法 就能跳转三级路由了 

不用自己改这些框架代码，直接把这条路由拉出来在需要的地方渲染就好了 [嵌套路由同级展示](https://github.com/ant-design/ant-design-pro-site/blob/master/docs/router-and-nav.md#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA)

> @ddcat1115 至少三级路由要放开了。。
> 而且面包屑需要用正则匹配了

不管几级路由，都可以直接从 routerData 里提出来写，三级路由N级路由
应该都是一致的处理方式；
目前面包屑支持带参数的路由渲染，刚测试了一下没问题呀

<img width="572" alt="2018-01-09 4 22 28" src="https://user-images.githubusercontent.com/7017767/34711206-7879891a-f559-11e7-9743-f3bd0d9e94f0.png">

<img width="817" alt="2018-01-09 4 22 55" src="https://user-images.githubusercontent.com/7017767/34711184-5af8d7b0-f559-11e7-8a51-2a7d9d123658.png">

**Comment by chenshuai2144** [comment]
我怎么不行！！ 看了半天代码没找到

**Comment by ddcat1115** [comment]
@chenshuai2144  你不是正在优化.... 😿  [diff](https://github.com/ant-design/ant-design-pro/pull/613/files#diff-6050d85bb60250a72b7616cd88fefc61R14)

**Comment by chenshuai2144** [comment]
难道我优化的不能用了！

**Comment by family2hu** [comment]
@ddcat1115 这种需要把所有详情页都拉出来写，感觉也挺麻烦的~~
