### ISSUE TITLE
🐛[BUG]  UnhandledPromiseRejectionWarning: Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by wxq851685279** [ant-design/ant-design-pro#6260]
### 🐛 在linux下npm create umi或者yarn create umi，都会报错。windows下正常

UnhandledPromiseRejectionWarning: Error: Cannot find module 'typescript'

### 📷 复现步骤
npm create umi 选择ant-design-pro

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. Ubuntu]

### 🚑 其他信息

npm create umi
? Select the boilerplate type ant-design-pro
(node:23924) UnhandledPromiseRejectionWarning: Error: Cannot find module 'typescript'
Require stack:
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/2.8/node.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/2.9/node.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/3.0/node.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/3.2/node.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/node.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/@typescript-eslint/eslint-plugin/dist/util/types.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/@typescript-eslint/eslint-plugin/dist/util/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/eslint/lib/config/plugins.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/eslint/lib/config.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/eslint/lib/cli-engine.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/eslint/lib/api.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/sylvanas/lib/eslintJs.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/sylvanas/lib/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/lib/generators/ant-design-pro/index.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/lib/run.js
- /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/cli.js
Referenced from: /home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/eslint-config-airbnb-typescript/index.js
Referenced from: 
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/ubuntu/.npm/_npx/23720/lib/node_modules/create-umi/node_modules/tsutils/typeguard/2.8/node.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
(node:23924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by chenshuai2144** [comment]
重新安装一下依赖即可。
https://github.com/umijs/fabric/commit/483c5039ea23feed86dc9af107c0718f36a7fcb5

**Comment by Zach-Lu** [comment]
我跟他问题一样，不过提示的是：
`success Installed "create-umi@0.21.2" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
(node:4458) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:`

**Comment by ahtashamabbasse** [comment]
I also faced the same issue, seems like something is breaking. 
![image](https://user-images.githubusercontent.com/25702074/82039949-2ca2ad00-96bf-11ea-931f-fb8142b8b273.png)
