### ISSUE TITLE
我有个地图页面，请问如何让高度填充、再去掉24的外边距

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#6264]
### 🧐 问题描述

我有一个不需要竖向滚动条的地图页面；想要填充整个页面（高度100%）；请问如何设置？

### 🚑 其他信息

![TIM截图20200401131502](https://user-images.githubusercontent.com/33310261/78102192-4ee8b000-741c-11ea-81a6-019286a3dd5b.png)

**Comment by chenshuai2144** [comment]
`height:"calc(100vh - 64px)"`, 你可以在这个页面外面包个  margin:-24 的
