### ISSUE TITLE
⚠️ Windows 添加模板和区块的说明及解决办法

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#6266]
## 问题说明

在 umi@3 中，所有的插件 api 都使用了异步模式，我们原来使用了[ mem-fs-editor](https://github.com/SBoudrias/mem-fs-editor) 只支持同步的方法，所以我们使用 [mem-fs-editor-async](https://github.com/ycjcl868/mem-fs-editor/)。 但是这个库对 windows 的兼容性不是很好。

如果碰到了 类似 `pages/**` 这样的文件夹目录，它无法正常识别，会报错文件不存在。详细的修复方法可以在看这个 [diff](https://github.com/umijs/umi-ui/pull/46)

### create umi
yarn create umi 中使用  complete 模式，可以获得带所有区块的版本。

### git clone 
git clone all-blocks 分支 也可以获得带所有区块的版本
`git clone git@github.com:ant-design/ant-design-pro.git -b all-blocks`

### 更新依赖

在 https://github.com/umijs/umi-ui/pull/46 我们已经修复了这个问题。更新一下依赖的版本即可解决。

更新的版本：
@umijs/preset-ui@2.1.7
@umijs/plugin-blocks@2.1.2

## 后续的保障

umi ui 这个仓库刚从 umi 主仓库中独立出来各种 ci 以及测试用例都不够健壮。本周内我们会补充主流程的各种测试用例，通过 ci 和 测试来保障功能的正常。防止以后出现大规模的影响主流程问题。

------

相关 issue：
ref ant-design/ant-design-pro#6235
ref umijs/umi-ui#39
ref umijs/umi-ui#35
ref ant-design/ant-design-pro#6206

**Comment by kaoding** [comment]
在 windows 10 上使用 umi ui 点 “构建”、“代码风格检查”、“测试”、“重装依赖” ，就会挂掉。
![image](https://user-images.githubusercontent.com/18542211/78158646-1bd20b00-7474-11ea-8631-4ed28aaa3e58.png)

**Comment by hot588** [comment]
我把node重装了一遍，后来就正常了！我被折磨晕了！现在一切正常了！

但是版本更新好快，看之前的视频教程不行了！

升级的文档更不上！没有官方文档更新！

**Comment by afc163** [comment]
@chenshuai2144 文档也要安排一波整体更新上来了。

**Comment by hot588** [comment]
只有 pages 或 page 目录下的页面才能插入资产   更新了依赖，还是不行！！！  win10，对win10 太不友好了！

**Comment by hot588** [comment]
5天过去了，还是没有任何进展啊！win10，好痛苦！

**Comment by hot588** [comment]
只能添加模板，不能添加区块！“**只有 pages 或 page 目录下的页面才能插入资产**”！！！

官方的修复，直接不行，不行！ 在win10下不行！

不能在空白模板里添加区块！

**Comment by hot588** [comment]
已经解决了！

**Comment by ysq-developer** [comment]
> 已经解决了！
怎么解决的

**Comment by floydljy** [comment]
> 已经解决了！

请问您怎么解决的，我也遇到了同样的问题

**Comment by 75986562** [comment]
> 已经解决了！

请问您怎么解决的，我更新了依赖还是不行
