### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design-pro#6267]
### 🐛 bug 描述
在路由中配置了权限码，authority: [xxx]，在BasicLayout中使用ProLayout的menuDataRender渲染菜单，在其中进行Authorized.check判断，发现无论配置什么权限码都没生效。

### 📷 复现步骤**

路由配置如下：
{
    rath: '/system/users',
    name: 'user',
    component: './System/User',
    authority: ['system:user'],
},
![Annotation 2020-04-01 165611](https://user-images.githubusercontent.com/5361465/78118540-ba8d4600-7439-11ea-924e-4cba5f12ce40.png)

### 🏞 期望结果

期望没有权限在左侧菜单不显示该菜单项。

### 💻 复现代码

[myantdpro.zip](https://github.com/ant-design/ant-design-pro/files/4413973/myantdpro.zip)

### © 版本信息

- Ant Design Pro 版本: 4.1.0
- umi 版本: 3.0.16
- 浏览器环境 版本 80.0.361.69
- 开发环境  Windows 10

**Comment by huntdream** [comment]
`menuDataRender`你直接传进去就好了，`Array.isArray(menuDataRender)`是不对的
![image](https://user-images.githubusercontent.com/7903755/78125272-5ec7ba80-7443-11ea-9c25-d4cff1dbad87.png)

**Comment by hankaibo** [comment]
犯迷糊了。汗。
