### ISSUE TITLE
🧐[问题]我有一个问题,不知道是不是bug希望大佬能解答一下.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6268]
### 🧐 问题描述

我使用umi3.x的history.push()进行页面跳转并传递参数.代码是这么操作的.我截图上来.
首先在发起跳转的页面Model中写好Effect.
![image](https://user-images.githubusercontent.com/13188169/78134638-0ac4d200-7453-11ea-8199-76824d52152b.png)
然后再在页面按钮点击触发跳转并传递相关参数.
![image](https://user-images.githubusercontent.com/13188169/78134717-24feb000-7453-11ea-9116-12ecc3106d37.png)
再目标页面的Model subscriptions中写好如下代码.
![image](https://user-images.githubusercontent.com/13188169/78135108-e5849380-7453-11ea-99ac-ad3ab29be098.png)
然后在页面的生命周期函数中进行数据获取
![image](https://user-images.githubusercontent.com/13188169/78135284-372d1e00-7454-11ea-8c3b-31cf1c2b1c06.png)
结果死活数据拿不到,一直是空字符串.被逼无奈实用了localStorage来实现功能.
希望大佬们能够指点迷津.若是由于数据是异步的话,如何才能避免这种问题.往往页面跳转并传参,参数肯定大部分数据是在页面展示数据之前就得使用.

**Comment by huntdream** [comment]
为什么要通过路由来把数据从A页面传递到B页面，最后还是放到redux里面，在A页面直接放到redux里面不就好了吗?

**Comment by joesdu** [comment]
> 为什么要通过路由来把数据从A页面传递到B页面，最后还是放到redux里面，在A页面直接放到redux里面不就好了吗?

没懂你说的这种操作.有 示例吗?

**Comment by huntdream** [comment]
大概是这个意思吧，
```
const { pathname, state} = payload

yield put({
  type: '[namespace]/setData', 
  payload: state 
})

history.push(pathname)
```

**Comment by joesdu** [comment]
> 大概是这个意思吧，
> 
> ```
> const { pathname, state} = payload
> 
> yield put({
>   type: '[namespace]/setData', 
>   payload: state 
> })
> 
> history.push(pathname)
> ```

OK,Thanks,我试试.

**Comment by joesdu** [comment]
> 大概是这个意思吧，
> 
> ```
> const { pathname, state} = payload
> 
> yield put({
>   type: '[namespace]/setData', 
>   payload: state 
> })
> 
> history.push(pathname)
> ```
搞定了,相当感谢.

**Comment by chenshuai2144** [comment]
`history.push({ pathname,query })`
可以这么用

**Comment by joesdu** [comment]
> `history.push({ pathname,query })`
> 可以这么用

我最开始就是这么用的,然后在subscription中将数据写到Model的state中.结果在页面Component中没有拿到相应的数据.

**Comment by huntdream** [comment]
> > `history.push({ pathname,query })`
> > 可以这么用
> 
> 我最开始就是这么用的,然后在subscription中将数据写到Model的state中.结果在页面Component中没有拿到相应的数据.

你写的是放在state里面，这个是放在query里面同步到url。其实查询参数的话一般放在url里面好一点，不用放在redux里面维护，你只需要监听解析query就行了。redux和location.state一刷新页面就清空了

**Comment by joesdu** [comment]
> > > `history.push({ pathname,query })`
> > > 可以这么用
> > 
> > 
> > 我最开始就是这么用的,然后在subscription中将数据写到Model的state中.结果在页面Component中没有拿到相应的数据.
> 
> 你写的是放在state里面，这个是放在query里面同步到url。其实查询参数的话一般放在url里面好一点，不用放在redux里面维护，你只需要监听解析query就行了。redux和location.state一刷新页面就清空了

了解了,目前先这么实现,以后若是经理觉得刷新页面数据丢了是bug的话,再改😁😁🤣
