### ISSUE TITLE
🐛[BUG]在BasicLayout.tsx的ProLayout中引入BackTop组件后,页面无效果.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6269]
### 🐛 bug 描述

以前这么写是有效果的,最近突然发现没有了,今天才想起来提问.
![image](https://user-images.githubusercontent.com/13188169/78145625-af4f1000-7463-11ea-92cd-3bf9823cf428.png)
![image](https://user-images.githubusercontent.com/13188169/78145658-ba09a500-7463-11ea-97e8-3178c7b88d89.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你是 固定了菜单是吗？

**Comment by joesdu** [comment]
> 你是 固定了菜单是吗？
???左侧菜单吗?左侧菜单是通过路由文件生成的.以前我这么写,是能够有backtop的,现在没了,不知道改了什么

**Comment by chenshuai2144** [comment]
BackTop 默认是挂载 body 上的，你的滚定条是不是不在 body 吧

**Comment by joesdu** [comment]
> BackTop 默认是挂载 body 上的，你的滚定条是不是不在 body 吧

我后边调整试试.

**Comment by chenshuai2144** [comment]
有答案了吗？

**Comment by joesdu** [comment]
> 有答案了吗？
我在页面中没有找到这个组件生成的元素.奇怪.

**Comment by joesdu** [comment]
> 有答案了吗

还是不行,单独写到页面或者写在BasicLayout.tsx中都没有效果.

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/78454720-664dc480-76cc-11ea-8595-0eb15ac07f68.png)


默认会注册到windows，应该是你魔改了一下样式吧

**Comment by joesdu** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/78454720-664dc480-76cc-11ea-8595-0eb15ac07f68.png)
> 
> 默认会注册到windows，应该是你魔改了一下样式吧
奇怪的很，没有改过什么呀，以前能显示，现在突然没了。我以后再查看看吧。
