### ISSUE TITLE
测试挂了么？

### ISSUE THREAD

**Issue by VitoVan** [ant-design/ant-design-pro#627]
https://travis-ci.org/ant-design/ant-design-pro/jobs/326638951#L632

![image](https://user-images.githubusercontent.com/1756956/34703193-a1858368-f52c-11e7-8451-2eb67a586b31.png)

**Comment by afc163** [comment]
Trying to fix that at https://github.com/ant-design/ant-design-pro/commit/f61090219f31cb8b3da66ae9890391c1c75fde2d

**Comment by VitoVan** [comment]
It is fixed, thank you @afc163
