### ISSUE TITLE
🐛[BUG] react-helmet-async

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6270]
### 🐛 bug 描述

换 react-helmet-async 后，标题反应不及时，时不时还会"退回"不显示标题（变成显示url）

#6181 

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
看看这个pr，我也发现这个问题了

https://github.com/ant-design/ant-design-pro-layout/pull/391
