### ISSUE TITLE
从 umi 中导入 connect，Dispatch 等模块时提示 umi 未导出

### ISSUE THREAD

**Issue by zhangminggeek** [ant-design/ant-design-pro#6271]
https://github.com/ant-design/ant-design-pro/blob/bf3abbb89918f6f34d3f4967e2497c4301eca53f/src/pages/user/login/index.tsx#L4

'umi' does not contain an export named 'connect'.

![image](https://user-images.githubusercontent.com/30174437/78200679-fe2b9280-74c1-11ea-82f6-e51ecf905ff9.png)

**Comment by xiaohuoni** [comment]
dev 之后就有的
![image](https://user-images.githubusercontent.com/11746742/78203359-55813100-74c9-11ea-92c7-a5c70f3702b6.png)

**Comment by guangming21** [comment]
@xiaohuoni 怎么解决的

**Comment by chenshuai2144** [comment]
需要打开 dva，并且有 models 这个文件夹

**Comment by rkumar1904** [comment]
I'm still unable to figure out how to get connect. ??

**Comment by rkumar1904** [comment]
> after dev
> ![image](https://user-images.githubusercontent.com/11746742/78203359-55813100-74c9-11ea-92c7-a5c70f3702b6.png)

How do you solved it ??

**Comment by zzjjbbaa** [comment]
npm run start:dev

**Comment by qweasd25** [comment]
> 需要打开 dva，并且有 models 这个文件夹

什么意思啊

**Comment by SnakeHacker** [comment]
在src文件夹下新建models文件夹，然后创建一个文件，删除node_modules，重新yarn install
<img width="429" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/11294011/faf6b508-be79-4cff-bb39-872c39e71c53">
