### ISSUE TITLE
🧐 请问使用umi ui 添加区块和模板的时候能选择语言吗

### ISSUE THREAD

**Issue by nameJw** [ant-design/ant-design-pro#6274]

**Comment by chenshuai2144** [comment]
会自动推算的，默认是 ts，如果推算你的项目是 js，就会帮你转化为 js

**Comment by nameJw** [comment]
> 会自动推算的，默认是 ts，如果推算你的项目是 js，就会帮你转化为 js

但是没有自动推算，我的项目是js的，但是下的区块和模板都是ts的，所以我来提问了。

**Comment by afc163** [comment]
给个重现方式。@nameJw

**Comment by nameJw** [comment]
> 给个重现方式。@nameJw

1、npm create umi
2、选择ant design pro 版本4
3、选择使用javascript
5、选择创建 simple 的 pro 项目
6、安装好后启动项目
**重点**
可以看到都是js语言的
![js](https://user-images.githubusercontent.com/37288382/78215355-ee27a900-74e9-11ea-9b2f-f1d2b673b003.png)
然后umi ui 安装一个模板-空白页面
![image](https://user-images.githubusercontent.com/37288382/78215451-1b745700-74ea-11ea-9ced-c730b8fc4c7c.png)
![image](https://user-images.githubusercontent.com/37288382/78215499-33e47180-74ea-11ea-9084-62bf4ff6e7c7.png)
**然后再代码中可以看到**
![image](https://user-images.githubusercontent.com/37288382/78215543-4f4f7c80-74ea-11ea-9d0d-b81251ccb35f.png)

**Comment by nameJw** [comment]
> > 给个重现方式。@nameJw
> 
> 1、npm create umi
> 2、选择ant design pro 版本4
> 3、选择使用javascript
> 5、选择创建 simple 的 pro 项目
> 6、安装好后启动项目
> **重点**
> 可以看到都是js语言的
> ![js](https://user-images.githubusercontent.com/37288382/78215355-ee27a900-74e9-11ea-9b2f-f1d2b673b003.png)
> 然后umi ui 安装一个模板-空白页面
> ![image](https://user-images.githubusercontent.com/37288382/78215451-1b745700-74ea-11ea-9ced-c730b8fc4c7c.png)
> ![image](https://user-images.githubusercontent.com/37288382/78215499-33e47180-74ea-11ea-9084-62bf4ff6e7c7.png)
> **然后再代码中可以看到**
> ![image](https://user-images.githubusercontent.com/37288382/78215543-4f4f7c80-74ea-11ea-9d0d-b81251ccb35f.png)

@afc163 我这看的重现截图是缩略图，看不到，不知道你那边可不可以。

**Comment by twobear** [comment]
> > 会自动推算的，默认是 ts，如果推算你的项目是 js，就会帮你转化为 js
> 
> 但是没有自动推算，我的项目是js的，但是下的区块和模板都是ts的，所以我来提问了。

我遇到了同样的问题，求解决

**Comment by ZeeRoc** [comment]
> > 会自动推算的，默认是 ts，如果推算你的项目是 js，就会帮你转化为 js
> 
> 但是没有自动推算，我的项目是js的，但是下的区块和模板都是ts的，所以我来提问了。

我关注两天了 为什么还没有人来解决这个问题？？？

**Comment by nameJw** [comment]
> > > 会自动推算的，默认是 ts，如果推算你的项目是 js，就会帮你转化为 js
> > 
> > 
> > 但是没有自动推算，我的项目是js的，但是下的区块和模板都是ts的，所以我来提问了。
> 
> 我遇到了同样的问题，求解决

先自己写吧。等是等不来的

**Comment by southpeak** [comment]
同样的问题，整个工程看了一下，只有 src/.umi 下面有 ts 文件，其它地方没有，也没有找到可配置的地方，求解

**Comment by yeluoqiuzhi** [comment]
我也是，好垃圾啊，还不如以前

**Comment by yeluoqiuzhi** [comment]
@nameJw  怎么自己写？

**Comment by nameJw** [comment]
> @nameJw 怎么自己写？

自己添加页面和自己去引入ui库组件呗

**Comment by StylishSite** [comment]
我也是一样的问题，求解决

**Comment by tigerxiongj** [comment]
ui block倒是可以从antd官方拷贝代码，pro block还是要用添加模版的方式，也些页面去掉国际化也有问题，显示变量。ts没法转化成js是个问题。

**Comment by yeluoqiuzhi** [comment]
我用的是土办法，新建工程的时候可以选择新建一个完整demo版本选择js语言，不过新建出来的项目居然也是各种问题，好在问题不大，我是去里面复制需要的代码的

**Comment by hankaibo** [comment]
我有一个基于官方版本4做的js版本。
https://github.com/hankaibo/myantdpro
将官方ts文件完全js化，定期手动同步官方文件😂，并在其基础上集成了权限管理等公共页面，而且提供真实后台接口。
希望可以帮到各位。
