### ISSUE TITLE
添加区块 出现 【只有 pages 或 page 目录下的页面才能插入资产】🐛[BUG]

### ISSUE THREAD

**Issue by a0215cpl** [ant-design/ant-design-pro#6275]
### 🐛 bug 描述

直接添加 区块 时出现 【只有 pages 或 page 目录下的页面才能插入资产】

### 📷 复现步骤

基本上新添加的所有page都会出现

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🏞 误打误撞解决的办法

通过进入完整版添加一遍区块就可以添加其他布局了。

![1321585795594_ pic_hd](https://user-images.githubusercontent.com/42417914/78206020-42be2a80-74d0-11ea-828d-37c8a3cf27c6.jpg)
![1331585795693_ pic_hd](https://user-images.githubusercontent.com/42417914/78206031-4e115600-74d0-11ea-8966-49e7a210c008.jpg)
![1341585795732_ pic_hd](https://user-images.githubusercontent.com/42417914/78206040-536ea080-74d0-11ea-8659-72e8c90b3e5c.jpg)
![1351585795761_ pic_hd](https://user-images.githubusercontent.com/42417914/78206044-58335480-74d0-11ea-9594-d9c445a274c2.jpg)

**Comment by ycjcl868** [comment]
`BABEL_CACHE=none yarn start` 试试，babel 有缓存

**Comment by nameJw** [comment]
我刚刚也遇到了，我看了下这个问题，它只有在pages 或 page下的文件才能加，多一层目录都不行。我觉得这没什么用啊。本来我也想提问的

**Comment by ycjcl868** [comment]
> 我刚刚也遇到了，我看了下这个问题，它只有在pages 或 page下的文件才能加，多一层目录都不行。我觉得这没什么用啊。本来我也想提问的

多层目录也可以的，只检查了路径是否包含了 `pages` 或 `page`

**Comment by nameJw** [comment]
> > 我刚刚也遇到了，我看了下这个问题，它只有在pages 或 page下的文件才能加，多一层目录都不行。我觉得这没什么用啊。本来我也想提问的
> 
> 多层目录也可以的，只检查了路径是否包含了 `pages` 或 `page`

可以吗，我重新建立的简单的pro项目都不行诶

**Comment by twobear** [comment]
我也遇到了，安装了几遍，js ts换来换去也还有这个问题，这个解决方法有...默认加的区块tsx ....又看了半天

**Comment by williamhatch** [comment]
> `BABEL_CACHE=none yarn start` 试试，babel 有缓存

need to restart every time to make it work
