### ISSUE TITLE
umi版本问题🧐[问题]

### ISSUE THREAD

**Issue by rainbowdiary** [ant-design/ant-design-pro#6276]
### 🧐 问题描述
1. 使用官网的方法https://v2-pro.ant.design/  yarn create umi最后生成pro项目umi版本是"^3.0.14";
2. 但是我看github上pro v4版本package.json中umi版本是"^2.7.2",
这是什么情况？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/bf3abbb89918f6f34d3f4967e2497c4301eca53f/package.json#L74

是按照这里来的
