### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#6278]
### 🧐 问题描述

插件区块后报错
Uncaught (in promise) TypeError: Cannot read property 'trim' of undefined
### 🚑 其他信息

![TIM截图20200402094058](https://user-images.githubusercontent.com/33310261/78220473-2e8c2480-74f4-11ea-80ce-2c248d9dda17.png)

**Comment by chenshuai2144** [comment]
能给更多重现吗？

**Comment by laolaolulu** [comment]
![TIM截图20200403084519](https://user-images.githubusercontent.com/33310261/78312831-9475bc00-7587-11ea-91f8-0a607d847814.png)
我刚又重新创建了个项目，在首页新增区块就报错

**Comment by laolaolulu** [comment]
我使用umi那个可视化辅助工具建区块就没正常过，报各种错误

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/6275

**Comment by laolaolulu** [comment]
> DUP的[＃6275](https://github.com/ant-design/ant-design-pro/issues/6275)

图片之前我发错了

**Comment by laolaolulu** [comment]
> 能给更多信息，或者重现步骤吗？

使用Umi辅助工具先建模板-空白页-然后再空白页建表格区块就出现这个错误，每次都出现
