### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by fantaishao** [ant-design/ant-design-pro#628]
拉取最新的工程，删除原来的node_moudles，再npm install， npm start之后报错

报错信息如下：

Failed to compile
./src/rollbar.js
  Line 4:  Unexpected use of 'location'  no-restricted-globals

Search for the keywords to learn more about each error.
This error occurred during the build time and cannot be dismissed.

**Comment by chenshuai2144** [comment]
重新安装依赖呢？
