### ISSUE TITLE
🧐[问题] 生产环境下，如果前端程序出错（比如对象为null，map这个对象时），页面直接白屏问题。怎么处理比较好？

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#6280]
### 🧐 问题描述
生产环境下，如果前端程序出错，页面直接白屏问题。怎么处理比较好？直接白屏感觉不如自定义提示一下，程序内部出现错误，然后下面展示下具体错误原因，这样也方便排查问题

比如对象为null，map这个对象时
### 💻 示例代码
const obj = null;
obj.map(item => item.id);

**Comment by chenshuai2144** [comment]
https://zh-hans.reactjs.org/docs/error-boundaries.html
你是想要这个吗？
