### ISSUE TITLE
🐛[BUG]  完全按官方文档操作，最后npm start  webpack的时候报错

### ISSUE THREAD

**Issue by huaiguoguo** [ant-design/ant-design-pro#6281]
### 🐛 bug 描述

 完全按官方文档操作，最后npm start  的时候报错,  启动不起来

### 📷 复现步骤
我完全按官方文档指示操作:
yarn create umi ,  
yarn , 
yarn start

一直报下面的错
 ERROR  Failed to compile with 1 errors                                                                                                        22:11:39
 error  in ./src/.umi/umi.ts

Module parse failed: Unexpected token (44:29)

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### 🏞 期望结果
期望可以正常启动yarn start

 ERROR  Failed to compile with 1 errors                                                                                                        22:11:39
 error  in ./src/.umi/umi.ts

Module parse failed: Unexpected token (44:29)

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]       4.0 按官方现在文档操作的
- umi 版本                 按官方现在文档操作的
- 浏览器环境             yarn start 启动不起来
- 开发环境 [e.g. mac OS]  win10 1909  x64
-node  12.13.1
-npm  6.13.7

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1888094/78261005-3d44fc80-7531-11ea-9539-3e3310089165.png)

![image](https://user-images.githubusercontent.com/1888094/78262112-b5f88880-7532-11ea-827a-6b346b6a19ce.png)

![image](https://user-images.githubusercontent.com/1888094/78261042-48982800-7531-11ea-89d5-f56a42e548ad.png)

**Comment by Tzng** [comment]
我也遇到了，刚想提交一个。
我把  "optionalDependencies": {  },里面的 "puppeteer": "^2.0.0" 移到了 devDependencies 就可以运行了。。。

**Comment by huaiguoguo** [comment]
> 我也遇到了，刚想提交一个。
> 我把 "optionalDependencies": { },里面的 "puppeteer": "^2.0.0" 移到了 devDependencies 就可以运行了。。。

是不是官方即刻改正了，我刚才又重新创建了一个(npm create umi)发现又好了！

**Comment by Tzng** [comment]
> > 我也遇到了，刚想提交一个。
> > 我把 "optionalDependencies": { },里面的 "puppeteer": "^2.0.0" 移到了 devDependencies 就可以运行了。。。
> 
> 是不是官方即刻改正了，我刚才又重新创建了一个(npm create umi)发现又好了！

你可以对比下两个package.json之间的区别

**Comment by huaiguoguo** [comment]
> > > 我也遇到了，刚想提交一个。
> > > 我把 "optionalDependencies": { },里面的 "puppeteer": "^2.0.0" 移到了 devDependencies 就可以运行了。。。
> > 
> > 
> > 是不是官方即刻改正了，我刚才又重新创建了一个(npm create umi)发现又好了！
> 
> 你可以对比下两个package.json之间的区别

没对比，我先启动了一下，发现又报错了

![image](https://user-images.githubusercontent.com/1888094/78272404-0f1ae900-7540-11ea-94b5-f725b5892c89.png)

![image](https://user-images.githubusercontent.com/1888094/78272405-0f1ae900-7540-11ea-90fe-04543c50c513.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/6279/checks?check_run_id=554660923

官方的ci 也出了问题，看来是umi的bug

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/4368
