### ISSUE TITLE
登录页面会显示一个多余的🐛[BUG]

### ISSUE THREAD

**Issue by Tzng** [ant-design/ant-design-pro#6282]
### 🐛 bug 描述

鼠标点一下用户名跟密码之间的空白处就可以看到，在Edge浏览器是黑色的，在Chrome是蓝色的

![image](https://user-images.githubusercontent.com/26215888/78266255-1b9b4380-7538-11ea-9613-d42e4fc01071.png)

![image](https://user-images.githubusercontent.com/26215888/78266293-2eae1380-7538-11ea-8e90-52638fde48c6.png)

### 📷 复现步骤

直接访问

https://preview.pro.ant.design/user/login?redirect=https%3A%2F%2Fpreview.pro.ant.design%2Fdashboard%2Fanalysis

### 🏞 期望结果

没有框框

### 💻 复现代码

https://preview.pro.ant.design/user/login?redirect=https%3A%2F%2Fpreview.pro.ant.design%2Fdashboard%2Fanalysis

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/78312952-df8fcf00-7587-11ea-859b-03203ce8e860.png)


是你浏览器的插件吗？

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/78317401-c5a8b900-7594-11ea-9896-46913e8c6a5c.png)
应该是antd的bug。
![image](https://user-images.githubusercontent.com/11746742/78317828-ede4e780-7595-11ea-8932-2664c8c3c219.png)

**Comment by xiaohuoni** [comment]
我也不确定是不是我浏览器插件的问题，换了两个电脑，都是这样子的

**Comment by chenshuai2144** [comment]
多一个线段没发现，但是hover 样式的确很奇怪

**Comment by Tzng** [comment]
换了Safari也有这个，真神奇

**Comment by huntdream** [comment]
![image](https://user-images.githubusercontent.com/7903755/78346567-c57ade80-75d1-11ea-8169-cb113e2007ea.png)
是tab被focus的时候的outline

**Comment by chenshuai2144** [comment]
是 antd 导致的，等待新的版本发布

**Comment by chenshuai2144** [comment]
antd 已经发布
