### ISSUE TITLE
🧐[问题]想知道https://ant.design/index-cn首页ant design后面的动画是怎么做的？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#6283]
### 🧐 问题描述
https://ant.design/index-cn 首页ant design后面的动画是怎么做的呀，不知道哪里有例子可以学习学习？

**Comment by chenshuai2144** [comment]
haitu，但是现在还没有文档。
你可以看ant-design 官方的源码

**Comment by shaohuatsou** [comment]
是F12查看源码吗？
那里面的看不太懂啊

**Comment by shaohuatsou** [comment]
> haitu，但是现在还没有文档。
> 你可以看ant-design 官方的源码

是F12查看源码吗？
那里面的看不太懂啊

**Comment by shaohuatsou** [comment]
> haitu，但是现在还没有文档。
> 你可以看ant-design 官方的源码

@chenshuai2144 是F12查看源码吗？那里面的看不太懂啊
