### ISSUE TITLE
🐛[BUG] ProTable报 Cannot read property 'reduce' of undefined 完全按官方操作(npm create umi)没任何操作

### ISSUE THREAD

**Issue by huaiguoguo** [ant-design/ant-design-pro#6285]
### 🐛 bug 描述
npm create umi
npm i
npm start
点击带有ProTable的页面报以下错误
TypeError: Cannot read property 'reduce' of undefined
tableAlertRender
./src/pages/ListTableList/index.jsx:207

### 📷 复现步骤

npm create umi
npm i
npm start
点击带有ProTable的页面报以下错误
TypeError: Cannot read property 'reduce' of undefined
tableAlertRender
./src/pages/ListTableList/index.jsx:207

### 🏞 期望结果
期望正常展现表格

### 💻 复现代码
npm create umi
npm i
npm start
无任何改动

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  完全按官方文档操作 4.0
- umi 版本   完全按官方文档操作
- 浏览器环境 完全按官方文档操作
- 开发环境 [e.g. mac OS]  win 1909 x64

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1888094/78272404-0f1ae900-7540-11ea-94b5-f725b5892c89.png)

![image](https://user-images.githubusercontent.com/1888094/78272405-0f1ae900-7540-11ea-90fe-04543c50c513.png)

**Comment by chenshuai2144** [comment]
看来是umi的bug。等待修复一下。

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/issues/4368

**Comment by huaiguoguo** [comment]
> [umijs/umi#4368](https://github.com/umijs/umi/issues/4368)
这个错看起来不像是umi的bug, 像是antd->ProTable的bug?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/6284

这个呢？
是 protable 的不兼容改动

**Comment by huaiguoguo** [comment]
> #6284
> 
> 这个呢？
> 是 protable 的不兼容改动

嗯，感谢;
这个bug啥时候可以修复了，在线等，项目急用 :)

**Comment by huaiguoguo** [comment]
> #6284
> 
> 这个呢？
> 是 protable 的不兼容改动

看到你的提交改动了，非常感谢！
