### ISSUE TITLE
🧐[问题]项目构建后dist文件夹生成的js文件没有统一放在js文件夹下

### ISSUE THREAD

**Issue by 11350494** [ant-design/ant-design-pro#6286]
### 🧐 问题描述

项目构建后dist文件夹生成的js文件没有统一放在js文件夹下

### 💻 示例代码

npm run build

### 🚑 其他信息

![js](https://user-images.githubusercontent.com/33769146/78315844-c0e20600-7590-11ea-96d8-d6b778e46769.png)

**Comment by chenshuai2144** [comment]
没有这个功能的，都是放在一起的。
