### ISSUE TITLE
🐛[BUG]官方预览里查询表格页面报错

### ISSUE THREAD

**Issue by Lmangoxx** [ant-design/ant-design-pro#6289]
### 🐛 官方预览里查询表格页面打开报错

问题页面地址：https://preview.pro.ant.design/list/table-list

发现时间：4月3日11点30分

### 🚑 其他信息
报错截图：
![image](https://user-images.githubusercontent.com/13163328/78321391-62bc1f80-759e-11ea-84c1-b63dc46f4b8a.png)

### © 版本信息
- 浏览器环境：Chrome 80.0.3987.162（正式版本） （64 位）
- 开发环境： mac OS

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/list/table-list

清空一下缓存，重新部署一下

**Comment by Lmangoxx** [comment]
@chenshuai2144 已经OK了，👍
