### ISSUE TITLE
3月底v4.0.0 TS版🐛[BUG]request执行window.g_app，报错Cannot read property '_store' of undefined

### ISSUE THREAD

**Issue by RohanSensei** [ant-design/ant-design-pro#6290]
### 🐛 bug 描述

如题

### 📷 复现步骤

和以往一样新建项目后，修改request.ts，判断status===401错误代码：
`
window.g_app._store.dispatch({
        type: 'login/logout',
      });
`
运行出现401错误，截获报错：Cannot read property '_store' of undefined

### 🏞 期望结果

执行dispatch动作，回到登录页。

### 💻 复现代码

同上修改request.ts

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本:3.0.14
- 浏览器环境:chrome/edge
- 开发环境 [mac OS]

### 🚑 其他信息
另外发现奇怪问题：突然request.ts中的errorHandler失效（不知怎么产生的），无法截获任何错误，只好又单独写了个interceptors来截获，错误现象同上。

**Comment by chenshuai2144** [comment]
umi @3 已经把 g_app._store 干掉了
不允许使用这种黑科技了

**Comment by huang714669** [comment]
遇到同样的问题，umi-request的interceptor不能访问store，有什么替代的方案吗？

**Comment by 15531400827** [comment]
https://github.com/umijs/umi/issues/4099
import { getDvaApp } from 'umi'; 
使用 getDvaApp()._store.dispatch()

**Comment by wulinjie122** [comment]
> umi @3 已经把 g_app._store 干掉了
> 不允许使用这种黑科技了

那应该怎么使用呢？？？？我想获取全局的dispatch
