### ISSUE TITLE
TagCloud 当数据量为1的时候没有画出任何图像。一片空白🐛[BUG]

### ISSUE THREAD

**Issue by iam-frankqiu** [ant-design/ant-design-pro#6291]
### 🐛 bug 描述
TagCloud 当数据量为1的时候没有画出任何图像。一片空白🐛[BUG]

### 💻 复现代码

https://codesandbox.io/s/nice-blackwell-2zlp2
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xiaohuoni** [comment]
可以复现。想找一下是不是 bizcharts 的bug，结果，他们好像在官网删掉了，词云的demo
https://bizcharts.net/product/bizcharts/gallery

**Comment by iam-frankqiu** [comment]
> 可以复现。想找一下是不是 bizcharts 的bug，结果，他们好像在官网删掉了，词云的demo

所以有没有什么别的办法解决这个问题？

**Comment by chenshuai2144** [comment]
直接用 g2 的呢？
