### ISSUE TITLE
请教一下,如何在Pro中做统一的接口数据异常处理

### ISSUE THREAD

**Issue by zhichao8756** [ant-design/ant-design-pro#6292]
接口数据异常情况下,如果直接取数据,会导致js链式操作报错(xxxx of undefined等等)
![image](https://user-images.githubusercontent.com/24514251/78337474-952c4380-75c3-11ea-97a1-85afaa968da2.png)
每次从接口返回数据做判断过于繁琐,请教一下大家项目中是如何优雅的统一处理的

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/blob/1df41a3f348ed237f7acd3296f3014b219e7d9e1/src/utils/request.ts#L29

**Comment by zhichao8756** [comment]
@xiaohuoni 我没表述清楚 ,生产环境报错可能会导致页面空白

**Comment by chenshuai2144** [comment]
@zhichao8756  如果是dva，可以用onError

如果是业务逻辑，可以试试 react 的错误[边界](https://zh-hans.reactjs.org/docs/error-boundaries.html)

如果还有问题，那就需要特殊除了，要注意不能信任后端的任何字段，总有可能出错的
