### ISSUE TITLE
🐛已经把响应数据重新封装成pro-table固定的数据格式，还是无法渲染数据？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6294]
### 🐛 pro-table无法渲染数据，请问各位大神？
已经把响应数据重新封装成pro-table固定的数据格式，还是无法渲染数据？

数据：
![image](https://user-images.githubusercontent.com/37643958/78391516-2083f400-7619-11ea-8f33-0f437dce121a.png)

重新封装：
![image](https://user-images.githubusercontent.com/37643958/78391548-2f6aa680-7619-11ea-8231-4af9dbfe5ca7.png)
![image](https://user-images.githubusercontent.com/37643958/78391579-398ca500-7619-11ea-9ee1-8a7b9b291ee2.png)

![image](https://user-images.githubusercontent.com/37643958/78391608-48735780-7619-11ea-8aec-a42374758c90.png)

**Comment by chenshuai2144** [comment]
onSearch 是什么？

**Comment by chenshuai2144** [comment]
dep of https://github.com/ant-design/pro-table/issues/301
