### ISSUE TITLE
🐛[BUG] umi 中的 router undefined

### ISSUE THREAD

**Issue by heyuxian** [ant-design/ant-design-pro#6295]
### 🐛 bug 描述
umi 中找不到 `router` ，导致使用了 `router` 的地方都在报错，包括 `antd-pro` 的官网也有这个问题

![image](https://user-images.githubusercontent.com/30259465/78421656-dee06100-768b-11ea-99cf-e8351b13a912.png)

![image](https://user-images.githubusercontent.com/30259465/78421622-a6408780-768b-11ea-8a46-7edfd3e3ea1f.png)

### 📷 复现步骤

- 访问 https://preview.pro.ant.design/list/search/articles
- 切换 tab 页

### 🏞 期望结果
- 更新 `router`

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本
- 浏览器环境
- 开发环境

**Comment by chenshuai2144** [comment]
应该更换成 history呢

**Comment by chenshuai2144** [comment]
已经删除了
等待部署
