### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#6296]
### 🐛 bug 描述
跟下面这个一样的问题，请问是否修复好了呀？
https://github.com/ant-design/ant-design-pro/issues/6285

1、node版本 12.6.0
2、按下面流程操作完后启动项目报错：tyarn create umi -> tyarn -> tyarn start
3、操作时间：4月4日周六23:00
![image](https://user-images.githubusercontent.com/20454290/78454425-854b5700-76ca-11ea-88e8-9ede97169f00.png)

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本 ^3.0.14
- 浏览器环境: chrome
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-table/issues/296
看这个issue，注意写好标题

**Comment by 419280377** [comment]
> [ant-design/pro-table#296](https://github.com/ant-design/pro-table/issues/296)
> 看这个issue，注意写好标题

收到，已修正，谢谢！
