### ISSUE TITLE
🐛[BUG]在线预览没有彩色，只显示黑白

### ISSUE THREAD

**Issue by zhangyongjiang** [ant-design/ant-design-pro#6297]
### 🐛 bug 描述

https://preview.pro.ant.design/dashboard/analysis 没有彩色。所有显示都是黑白

### 📷 复现步骤

浏览器指向 https://preview.pro.ant.design/dashboard/analysis 没有彩色。所有显示都是黑白。我试了下chrome和safari。都是黑白的。

<img width="1564" alt="Screen Shot 2020-04-04 at 8 37 21 AM" src="https://user-images.githubusercontent.com/1043451/78454996-a0798080-7650-11ea-940c-86cee75826dc.png">

### 🏞 期望结果

彩色显示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

Ant Design Pro老版本v2, v1没有问题

**Comment by afc163** [comment]
这应该是 @chenshuai2144 加了今天全站变灰的代码吧？

**Comment by sumaoge** [comment]
...认真的吗？
