### ISSUE TITLE
🐛请教ProTable显示问题？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6298]
### 🐛请教ProTable显示问题？

1. 查询表单按钮如何加入图标？

2. 如何屏蔽下图，在支持多选的情况下？

3. ProTable 列表有12列，如何默认进来显示主要信息8列，次要信息可以通过设置按钮勾选中显示全部12列？

![image](https://user-images.githubusercontent.com/37643958/78455384-ae6ee600-76d0-11ea-8ed2-422b56cc984d.png)

**Comment by chenshuai2144** [comment]
https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F

可以这个demo
