### ISSUE TITLE
🐛[BUG] 切换主题色，页面背景色成了黑色

### ISSUE THREAD

**Issue by onecmd** [ant-design/ant-design-pro#6299]
### 🐛 bug 描述

https://preview.pro.ant.design/dashboard/analysis?navTheme=light&primaryColor=dust
切换主题色，页面背景色成了黑色， 希望是白色。

### 📷 复现步骤

直接访问：https://preview.pro.ant.design/dashboard/analysis?navTheme=light&primaryColor=dust
或切换主题色

### 🏞 期望结果
背景是白色

### 💻 复现代码
![image](https://user-images.githubusercontent.com/3389081/78457852-df0a4c00-76df-11ea-85e3-4cebe34b0933.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

v2没有这个问题：https://v2-preview-ant-design-pro.netlify.com/list/table-list?navTheme=light&primaryColor=%23FA541C

**Comment by chenshuai2144** [comment]
重新编译了一下，已经 fix

**Comment by chenshuai2144** [comment]
好像还有问题

**Comment by tomgao365** [comment]
仍然有问题
