### ISSUE TITLE
Unhandled Rejection (403)

### ISSUE THREAD

**Issue by lxxoolxx** [ant-design/ant-design-pro#630]
点击画面--异常页--触发异常 时由于throw error 导致 Unhandled Rejection 画面会崩掉

**Comment by chenshuai2144** [comment]
@sorrycc  现在catch不了吗？
onError完了，应该就ok了！

**Comment by sorrycc** [comment]
没明白，是指 dva 里加了 onError 之后，在哪里 `throw error`，会出现 unhandled rejection ?

**Comment by chenshuai2144** [comment]
dva  增加了 onError，
再网络请求里面 throw error
onError 已经触发了 ，但是界面还是会跳转到错误界面

**Comment by sorrycc** [comment]
> 但是界面还是会跳转到错误界面

跳转到错误界面是什么场景下触发的？

**Comment by chenshuai2144** [comment]
> /exception/trigger

专门用来触发网络请求错误的界面。用于测试403 404 500的跳转

**Comment by chenshuai2144** [comment]
> /exception/trigger

专门用来触发网络请求错误的界面。用于测试403 404 500的跳转

**Comment by lxxoolxx** [comment]
我现在是点击 异常页--触发异常 比如其中的403按钮 正常拦截跳转到共同错误画面后 然后会跳转到错误界面  我觉得可能是 promise 有unhandled rejection 浏览器或者node js 做的处理

**Comment by chenshuai2144** [comment]
理论上onError 就应该rejection

**Comment by yuanfuwang** [comment]
现在触发异常画面，点击404、403和500按钮，弹出信息后画面一直在loading等待，没有进行页面跳转，请问如何解决该问题？谢谢

**Comment by chenshuai2144** [comment]
look #675
