### ISSUE TITLE
🧐[问题]新建空白模板，无法添加区块！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#6302]
### 🧐 问题描述

**只有 pages 或 page 目录下的页面才能插入资产**
新建的空白页，添加不了区块，添加区块的时候提示不是page页，或者page目录

再再带的页面里，可以添加区块，也能添加成功，只要是新建的“模板”都不可以添加区块

请看下面的图片！

**win10 的操作系统！**

### 🚑 其他信息

![微信图片_20200406142151](https://user-images.githubusercontent.com/51880332/78528590-4d4f2b80-7812-11ea-8247-0c14b1deffe2.png)

![微信图片_20200406142215](https://user-images.githubusercontent.com/51880332/78528589-4d4f2b80-7812-11ea-8396-fe3fc151b697.png)
@sorrycc @pmq20 @andriijas @craxyz

**Comment by chenshuai2144** [comment]
试着 重启一下呢？

**Comment by hot588** [comment]
> 试着 重启一下呢？

重启不管用，好多朋友都是这个问题了！ win10！ 在官方的原始模板里可以添加区块！自己添加的区块，就不行！

**Comment by taizhengfs** [comment]
我也遇到这个问题- -

**Comment by ycjcl868** [comment]
重装下， 上周修过。https://github.com/umijs/umi-ui/pull/52

**Comment by taizhengfs** [comment]
> 重装下， 上周修过。[umijs/umi-ui#52](https://github.com/umijs/umi-ui/pull/52)

我刚刚重装了下，还是一样，是有什么特殊的重装步骤吗？

**Comment by taizhengfs** [comment]
> 重装下， 上周修过。[umijs/umi-ui#52](https://github.com/umijs/umi-ui/pull/52)

能告知下哪个模块重装吗？装到哪个版本？UMI？

**Comment by lolieatapple** [comment]
还是不行，有个方法可以绕过，就是每次新建完页面退出后用这个命令启动：
BABEL_CACHE=none yarn start

**Comment by clarkchen** [comment]
你可以直接进入完全版，然后在那里进行编辑
