### ISSUE TITLE
Validate config "history" failed, "type" is required

### ISSUE THREAD

**Issue by Liqiankun** [ant-design/ant-design-pro#6303]
### 🐛 bug 描述

config中添加`history: 'hash'`，然后yarn start就出现`Validate config "history" failed, "type" is required`

### 💻 复现代码
```
export default defineConfig({
  history: 'hash',
  hash: true,
  ........
})
```

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本: 3.0.14
- 浏览器环境: Chrome
- 开发环境: mac OS

**Comment by Liqiankun** [comment]
居然不更新文档
![屏幕快照 2020-04-06 16 36 11](https://user-images.githubusercontent.com/11532418/78540371-a5902880-7826-11ea-8669-255a87022a4a.png)
**解决方案**
```
export default defineConfig({
  history: { type: 'hash' },
  hash: true,
  ........
})
```

**Comment by xwg2015** [comment]
醉了 文档也不更新

**Comment by Liqiankun** [comment]
@xwg2015 解决了就好，就是有点浪费时间。

**Comment by afc163** [comment]
@xwg2015 @Liqiankun 来 PR 帮我们修改文档吧

**Comment by Liqiankun** [comment]
@afc163 在什么地方？

**Comment by afc163** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/507615/78854046-f3897400-7a52-11ea-936e-3091ab98b0cb.png">

https://github.com/ant-design/ant-design-pro-site/

**Comment by Liqiankun** [comment]
[关于hash的文档PR](https://github.com/ant-design/ant-design-pro-site/pull/366#event-3216660677)
