### ISSUE TITLE
🐛[BUG] package 更新到最新版本，无法显示标题title

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6306]
### 🐛 bug 描述

package 更新到最新版本，无法显示标题title，仅显示网址
![QQ浏览器截图20200407124335](https://user-images.githubusercontent.com/3166799/78630927-7d0f3980-78cd-11ea-9620-e349c5bdcaf1.png)

**Comment by chenshuai2144** [comment]
来个重现的地址？

**Comment by hihuangwei** [comment]
最新的  ant-design-pro Git pull下来  就不行

**Comment by chenshuai2144** [comment]
复现不了的，create umi 也试过了

**Comment by hihuangwei** [comment]
> 复现不了的，create umi 也试过了

npm update  到最新

**Comment by hihuangwei** [comment]
> > 复现不了的，create umi 也试过了
> 
> npm update 到最新

刷新可以显示，点击菜单后变为网址

**Comment by gehaijun** [comment]
> 来个重现的地址？
我也是同样情况，
@ant-design/pro-layout@5.0.8 可以正常显示标题
5.0.9不行

**Comment by joesdu** [comment]
> > > 来个重现的地址？
> > 
> > 
> > 我也是同样情况，
> > @ant-design/pro-layout@5.0.8 可以正常显示标题
> > 5.0.9不行
这个好像是由于上个版本Antd偷偷更新了,将react-helmet-async改成了react-helmet.,现在需要手动装这个包react-helmet-async.
