### ISSUE TITLE
🐛[BUG]添加模板时报错

### ISSUE THREAD

**Issue by wxq851685279** [ant-design/ant-design-pro#6308]
### 🐛 bug 描述

使用umi ui添加模板报错
### 📷 复现步骤
启动项目，点击右下角umi ui,模板，选择一个页面，添加到项目

### 🏞 期望结果

可以正常添加模板

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.0.14
- 浏览器环境 chrome 80.0.3987.132
- 开发环境 windows10
以下是日志

⚓  Start git fetch
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

🎉  Success git checkout umi@3

⚓  Start git pull
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

🎉  Success git checkout umi@3

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

🎉  Success git checkout umi@3

⚓  Start git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

🎉  Success git checkout umi@3

⚓  Start git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Faild git pull: Command failed: git pull
undefined
undefined

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

🎉  Success git checkout umi@3

⚓  Start git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Faild git pull: Command failed: git pull
undefined
undefined

🚧  Execute task error: Command failed: git pull
undefined
undefined
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
.prettierignore: needs merge
AccountCenter/src/index.tsx: needs merge
ListTableList/package.json: needs merge
package.json: needs merge
error: you need to resolve your current index first
Faild git checkout: Command failed: git checkout umi@3
undefined
undefined

🎉  Success git checkout umi@3

⚓  Start git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Faild git pull: Command failed: git pull
undefined
undefined

🚧  Execute task error: Command failed: git pull
undefined
undefined

**Comment by hot588** [comment]
更新下缓存，即可！

**Comment by chenshuai2144** [comment]
执行一下 umi ui 右上角的 垃圾桶图表，看起来是本地的 区块列表和服务器的冲突了
