### ISSUE TITLE
如何关闭npm run build 的eslint

### ISSUE THREAD

**Issue by welkink** [ant-design/ant-design-pro#631]
项目前期未使用eslint检测。导致新版本打包（npm run build）后强制检查规则。请问如何禁用 eslint。

**Comment by afc163** [comment]
@sorrycc

**Comment by sorrycc** [comment]
```bash
$ DISABLE_ESLINT roadhog dev
```

**Comment by kstar11** [comment]
请问这个配置写在哪个文件里面?
DISABLE_ESLINT=1 roadhog dev
DISABLE_ESLINT=1 roadhog build

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/commit/0949342b71b4a15096198a3221f6ac0b42b4079a

**Comment by kstar11** [comment]
@afc163 非常3Q

**Comment by ychow** [comment]
请问：
windows系统报DISABLE_ESLINT不是内部或外部命令。 在本地node_modules里已经下载了roadhog.
`"roadhog": "^2.0.5"`

![wechatimg109](https://user-images.githubusercontent.com/6530996/35717651-995cb3ee-081b-11e8-80d3-56b79e074a7f.jpeg)
