### ISSUE TITLE
yarn create umi 选择ant-design-pro 则Failed to load plugin @typescript-eslint🐛[BUG]

### ISSUE THREAD

**Issue by Zach-Lu** [ant-design/ant-design-pro#6310]
### 🐛 bug 描述
以前安装都是没有问题的，但是这个不知道什么原因，总是报错，按道理空目录安装是不会这样的，不应该有依赖问题吧。
`zach@zachMacBook-Pro teacher % yarn create umi
yarn create v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@ant-design/codemod-v4 > @ant-design/icons@4.0.0-rc.0" has unmet peer dependency "react@16.x".
warning "@ant-design/codemod-v4 > @ant-design/icons > rc-util@4.19.0" has unmet peer dependency "react@^15.0.0 || ^16.0.0".
warning "@ant-design/codemod-v4 > @ant-design/icons > rc-util@4.19.0" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning "@umijs/create-umi-app > @umijs/utils > @babel/register@7.8.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi > @umijs/runtime@3.0.2" has unmet peer dependency "react@16.x".
warning "umi > @umijs/runtime > use-subscription@1.4.0" has unmet peer dependency "react@^16.8.0".
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.21.2" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
(node:12212) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
`

### 📷 复现步骤
nvm 管理的node版本号13.12.0，mkdir folder && cd folder && yarn create umi ，然后就报错。

### 🏞 期望结果

只希望能正常安装起来。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Zach-Lu** [comment]
`UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin' Require stack:`

这是关键错误。

**Comment by Zach-Lu** [comment]
解决了，重装nodejs.

**Comment by hlipeter** [comment]
> 解决了，重装nodejs.

or maybe you need buy a new Macbook.

**Comment by lolieatapple** [comment]
我重新安装新版nodejs也还是有同样的问题，请问你是怎么重装的？
