### ISSUE TITLE
🐛[BUG]topmenu状态下，页面宽度拖到很小，然后再拉大，左上角的logo旁边的字消失

### ISSUE THREAD

**Issue by xzf123456** [ant-design/ant-design-pro#6311]
刚进入时很正常：
![BB101654-F6F6-43e6-98C7-2FC6D0FDA342](https://user-images.githubusercontent.com/58057891/78652674-9c6d8d00-78f4-11ea-9d7d-a56d71f2ab0f.png)
页面宽度缩小，文字隐藏，依然很正常：
![9C6FC3CE-665D-42ca-9AC5-E7DB58C4DB35](https://user-images.githubusercontent.com/58057891/78652672-9bd4f680-78f4-11ea-94bc-54eb73c24027.png)
页面宽度再拉大，文字消失了，不正常：
![6E5F0B7B-A808-44c8-809D-26B8E2C442D0](https://user-images.githubusercontent.com/58057891/78652667-9aa3c980-78f4-11ea-8e06-b0aeadc2b3af.png)

**Comment by sunluby** [comment]
确定是，我也遇到了
