### ISSUE TITLE
🐛[BUG] git上下载的最新版本两处有bug

### ISSUE THREAD

**Issue by as882301** [ant-design/ant-design-pro#6313]
![image](https://user-images.githubusercontent.com/8169000/78671328-bb2e4c80-7911-11ea-95a7-49c06d54c0fd.png)
这里会请求两次 应该是重复渲染了两次

![image](https://user-images.githubusercontent.com/8169000/78671471-ec0e8180-7911-11ea-9fea-a48300216161.png)
这里的表单报错了

官网新安装的 没改过

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/78951436-c7c6c680-7b04-11ea-8bb7-0adb48a92ca9.png)
拦截器这样配置，
api/currentuser是请求了两次，
![image](https://user-images.githubusercontent.com/32530210/78951533-0eb4bc00-7b05-11ea-8dae-1e038fe94528.png)

**Comment by as882301** [comment]
n

> ![image](https://user-images.githubusercontent.com/32530210/78951436-c7c6c680-7b04-11ea-8bb7-0adb48a92ca9.png)
> 拦截器这样配置，
> api/currentuser是请求了两次，
> ![image](https://user-images.githubusercontent.com/32530210/78951533-0eb4bc00-7b05-11ea-8dae-1e038fe94528.png)

github上新下載的  没动过 代码 也是请求了两次 应该是权限验证那 还走了次  和拦截器无关
