### ISSUE TITLE
🐛[BUG] - https://pro.ant.design not loading hero on mobile?

### ISSUE THREAD

**Issue by scouttyg** [ant-design/ant-design-pro#6314]
### 🐛 bug 描述

**What is shown on desktop: ✅**
![pro-ant-design-homepage-desktop](https://user-images.githubusercontent.com/463175/78721240-24539700-78f5-11ea-928b-40a9daf5da06.gif)
Note: has the "Preview" and "Getting Started" button

**What is shown on mobile: ❌**
![pro-ant-design-homepage-mobile](https://user-images.githubusercontent.com/463175/78721295-40efcf00-78f5-11ea-9f21-1729af89fe26.gif)
Note: flashes for a brief second the buttons, but them immediately disappears. 

### 📷 复现步骤
- Go to https://pro.ant.design/
- Open Chrome console, and try "Mobile view", or try to view website from your mobile phone
- Possibly refresh the page if it works initially
- The buttons / animation should be missing!

Here's a quick gif of everything, including when it breaks after going back to desktop:
![pro-ant-design-homepage-full-reproduction](https://user-images.githubusercontent.com/463175/78721806-36820500-78f6-11ea-9be6-32106843ee2c.gif)

**Comment by chenshuai2144** [comment]
fixed, thanks
