### ISSUE TITLE
🐛[BUG] 升级antd v4图标不展示

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#6315]
### 🐛 bug 描述
参考文档[https://pro.ant.design/blog/antd-4.0-cn](url),引用```umi-plugin-antd-icon-config```后报错,不引用图标则不展示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 2.8.7
- 浏览器环境 chrome
- 开发环境 win

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/34082148/78739624-40a01400-7987-11ea-8564-dab1fa66b6b3.png)
![image](https://user-images.githubusercontent.com/34082148/78739646-4c8bd600-7987-11ea-8fa1-d8540fe183de.png)
![image](https://user-images.githubusercontent.com/34082148/78739842-bc9a5c00-7987-11ea-8aaa-28cceb4444ca.png)

**Comment by chenshuai2144** [comment]
你的菜单配置方便给一下吗？

**Comment by 569202812** [comment]
> 你的菜单配置方便给一下吗？

```
  routes: [
    {
      path: '/callback',
      component: './callback',
    },
    {
      path: '/',
      component: '../layouts/SecurityLayout',
      routes: [
        {
          path: '/',
          component: '../layouts/BasicLayout',
          // authority: ['pay', 'free'],
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/',
              redirect: '/by_links',
            },
            {
              path: '/by_links',
              name: '按链接复制',
              icon: 'LinkOutlined',
              component: './by-links',
            },
            {
              path: '/by_shop',
              name: '按店铺复制',
              icon: 'shop',
              component: './by-shop',
            },
            {
              path: '/record',
              name: '复制记录',
              icon: 'history',
              component: './record',
            },
            {
              path: '/goods',
              name: '商品管理',
              icon: 'form',
              component: './goods',
            },
            {
              component: './404',
            },
          ],
        },
        {
          component: './404',
        },
      ],
    },

    {
      component: './404',
    },
```
![image](https://user-images.githubusercontent.com/34082148/78753672-ca140e00-79a8-11ea-97b0-06cf6b8f62ab.png)

**Comment by 569202812** [comment]
更新了插件还是报错
![image](https://user-images.githubusercontent.com/34082148/78861074-77009080-7a66-11ea-9e05-44f99ab0f391.png)
