### ISSUE TITLE
🐛[BUG]最新Pro版本添加sass拓展时报错

### ISSUE THREAD

**Issue by EthanOrange** [ant-design/ant-design-pro#6316]
### 🐛 bug 描述
```bash
Invalid config key: sass
```

### 📷 复现步骤

```bash
yarn add node-sass sass-loader
```
```js
//config/config.js
export default defineConfig({
  hash: true,
  antd: {},
  sass:{}
})
```

### 🏞 期望结果

正常支持sass拓展

### 💻 复现代码

参考复现步骤

### © 版本信息

- Ant Design Pro 版本: [yarn create umi脚手架]
- umi 版本 [3@]
- 浏览器环境 [chrome 80x]
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/7098719/78749209-5ff76b00-79a0-11ea-9d3c-5cfc3a987d79.png)

**Comment by chenshuai2144** [comment]
现在是不支持 sass 的，可以看看这个
https://github.com/umijs/umi-examples/tree/master/sass

**Comment by dh13899396662** [comment]
说不支持就不支持 什么玩意
