### ISSUE TITLE
🐛[BUG] NoticeIcon 提示报错，功能正常

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6317]
### 🐛 bug 描述
![QQ浏览器截图20200408192042](https://user-images.githubusercontent.com/3166799/78778707-4a993580-79ce-11ea-8ddd-4cdde2868254.png)
![QQ浏览器截图20200408192104](https://user-images.githubusercontent.com/3166799/78778710-4bca6280-79ce-11ea-801a-e2eb7cd0e0cd.png)
![QQ浏览器截图20200408192125](https://user-images.githubusercontent.com/3166799/78778711-4c62f900-79ce-11ea-96d4-1739a4f3e57f.png)

**Comment by chenshuai2144** [comment]
你这个是旧版本吗？刚刚发现无法重现
