### ISSUE TITLE
🐛[BUG]升级antd v4，谷歌浏览器F12，查看源码是打包之后的代码，无法查看源码进行跟踪

### ISSUE THREAD

**Issue by huaryliu** [ant-design/ant-design-pro#6318]
### 🐛 bug 描述

升级antd v4，谷歌浏览器F12，无法查看源码进行跟踪

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
https://umijs.org/config#devtool

构建时打开 sourcemap。

**Comment by JianhuaLiu** [comment]
我在config.ts中配置了，发现仍然不起作用
`export default defineConfig({
  hash: true,
  devtool:'source-map',`

**Comment by chenshuai2144** [comment]
试试配置成 eval-source-map

umi 加载起来好像是真的慢了一些，需要等一下map才能加载进来

**Comment by huaryliu** [comment]
配置为source-map或者eval-source-map的效果基本一致，都是在webpack目录下能关联到源码，但是localhost目录下仍然是编译之后的js文件，还是没有像未升级版本前，直接能在localhost目录看能看到源码并且调试。

**Comment by gb-6k-house** [comment]
遇到同样问题，有更好解决办法？

**Comment by phoema** [comment]
> 试试配置成 eval-source-map
> 
> umi 加载起来好像是真的慢了一些，需要等一下map才能加载进来

能催促UMI项目组不
