### ISSUE TITLE
🧐[问题]只有在page或pages项目下的页面才能插入资产

### ISSUE THREAD

**Issue by zhangbc** [ant-design/ant-design-pro#6319]

**Comment by methinking** [comment]
系统macos, 按官方流程安装, 空白页面上创建区块也会出现这个

**Comment by zhangbc** [comment]
可以执行如下语句解决：
`☁  demo  BABEL_CACHE=none yarn start`

**Comment by hot588** [comment]
demo BABEL_CACHE=none yarn start

**Comment by hot588** [comment]
问题很严重！官方也不给明确的修复时间！我都弄很多次！

好了又坏了！

**Comment by likejie9502** [comment]
我的也有这个问题
加上`BABEL_CACHE=none`也没有用

**Comment by 2227322717** [comment]
waiting for someone

**Comment by s3341458** [comment]
同样遇到这个问题跪求解决办法

**Comment by wfjuiceku** [comment]
同样遇到这个问题跪求解决办法

**Comment by wfjuiceku** [comment]
![image](https://user-images.githubusercontent.com/5484985/82807719-eddcd600-9eba-11ea-82cd-a01733e20ff5.png)

**Comment by chenshuai2144** [comment]
加上 BABEL_CACHE=none 应该能解决大部分问题了
