### ISSUE TITLE
🧐[问题]除了document.ejs加载之外，最后一个加载样式怎么改？

### ISSUE THREAD

**Issue by wscart** [ant-design/ant-design-pro#6321]
### 🧐 问题描述
除了document.ejs加载之外，最后一个加载样式怎么改？

**Comment by chenshuai2144** [comment]
> 最后一个加载样式怎么改？

能详细展开一下吗？

**Comment by wscart** [comment]
> > 最后一个加载样式怎么改？
> 
> 能详细展开一下吗？

当刷新页面的时候出现加载效果的地方，而这个怎么样才能改？

**Comment by chenshuai2144** [comment]
document.ejs 和 layout， 最好是 document 速度比较快
