### ISSUE TITLE
第一次的api/currentuser请求拿不到localStorage.getItem()，后面请求可以拿到

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#6322]
### 🧐 问题描述

登录成功后，写入localStorage.setItem()正常，
但在跳转到/时，做api/currentuser请求时，拿不到localStorage.getItem()，为null
手动录入localhost:8000/回车，api/currentuser请求又是正常的。

点登录请求
![image](https://user-images.githubusercontent.com/32530210/78794422-50027a00-79e6-11ea-9b6c-b01b85046f83.png)
写入的localStorage
![image](https://user-images.githubusercontent.com/32530210/78794615-91932500-79e6-11ea-991f-1c9272720d05.png)
跳传后的api/currentuser
![image](https://user-images.githubusercontent.com/32530210/78794792-c0a99680-79e6-11ea-89bc-a1b318a5ef61.png)
但地址址输入localhost:8000
api/currentuser请求又正常了
![image](https://user-images.githubusercontent.com/32530210/78795015-0cf4d680-79e7-11ea-9140-b95b15399ed2.png)

对Request.ts的请求改如下：
![image](https://user-images.githubusercontent.com/32530210/78795159-3f063880-79e7-11ea-9813-ab9037fbcf09.png)

还请老师们指点下。怎么在第一次跳转/api/currentuser，request.ts,header里面拿不到localStorage的值

**Comment by as882301** [comment]
![image](https://user-images.githubusercontent.com/8169000/78812146-88618280-79fd-11ea-88f7-a8820d193792.png)
我也弄到这  我查到 官方说要用 拦截器来做 像我这样 

但是我又遇到其他问题   https://github.com/ant-design/ant-design-pro/issues/6313  不知道你的是否是这样

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/78812490-13db1380-79fe-11ea-85b9-827c809677b0.png)


这里只执行一次的，你要用拦截器来实现，这样每次查询才会用上，另外建议用 sessionStorage 或者cookie，最好是cookie 。

localStorage 用来当tooken，太危险了

**Comment by xyzabc0004** [comment]
@as882301 @chenshuai2144 
我改成了， 拿到token，将token写入到 cookie,
后面请求request.ts，都会带上这个cookie.感觉没有什么问题了。
![image](https://user-images.githubusercontent.com/32530210/78848744-3e03f400-7a45-11ea-9b99-fe7abff29bdb.png)

我觉得没有必要写拦截器吧。
除非cookie快过期了，把这个cookie重新refresh 下，或者要写其它的逻辑在里面，这个可以写到拦截器里面。

是这这样的吧？
