### ISSUE TITLE
执行npm run fetch:blocks 之后菜单展示异常，部分接口404🐛[BUG]

### ISSUE THREAD

**Issue by dmljc** [ant-design/ant-design-pro#6324]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
umi 发了 3.1 ，插件也做了更新，重新安装一下依赖应该就好了
