### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by dmljc** [ant-design/ant-design-pro#6325]
![bug](https://user-images.githubusercontent.com/28803668/78851996-d0a89100-7a4d-11ea-9fb0-e387be2058c4.jpeg)
### 🐛 bug 描述

1、从官网clone下来的代码没有全部区块，为了获取全部区块于是执行 npm run fetch:blocks,
2、然后，出现菜单展示既有中文又有英文的bug，并且部分接口404

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 [其他信息]
![bug](https://user-images.githubusercontent.com/28803668/78852009-d8683580-7a4d-11ea-9d38-f4f1b716228e.jpeg)

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/78852261-6fcd8880-7a4e-11ea-8459-047caa5ed232.png)

**Comment by chenshuai2144** [comment]
@kaoding 插件好像有问题，清楚依赖重新安装一下

**Comment by chenshuai2144** [comment]
@dmljc  我刚刚试了一下是没有问题的，你是 windows 吗？

**Comment by kaoding** [comment]
我试了一下，清除依赖重新安装一下就可以了，谢谢！ @chenshuai2144
