### ISSUE TITLE
🐛在新方案出来前，可以给提示，但不要改变现有的菜单上icon显示图标方式。

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6326]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/18542211/78852602-5da01a00-7a4f-11ea-8152-4dd5f744a703.png)

![image](https://user-images.githubusercontent.com/18542211/78852624-6bee3600-7a4f-11ea-962b-5191e30a080a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
只要安装这个插件就会显示的  umi-plugin-antd-icon-config
