### ISSUE TITLE
🐛[BUG]顶部二级菜单显示空白

### ISSUE THREAD

**Issue by wasay001** [ant-design/ant-design-pro#6327]
### 🐛 bug 描述

将菜单设置到顶部显示，此时二级菜单显示空白

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/78861510-8207f080-7a67-11ea-9491-7f782b2a2190.png)

**Comment by chenshuai2144** [comment]
by design

**Comment by wasay001** [comment]
你好！


我使用最新的git代码（https://github.com/ant-design/ant-design-pro.git），将菜单设置成顶部显示，然后运行，
则出现如下问题：
&nbsp; &nbsp; 1）“crown管理页”菜单下面的二级菜单背景色变成白色了
&nbsp; &nbsp; 2）菜单前的图标没有显示出来


如果是设置问题，请问在哪里设置？


鼠标划至“crown管理页”菜单后如图：

点击二级菜单后如图：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wangxingkang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 中午1:55
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"张学安"<56625428@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🐛[BUG]顶部二级菜单显示空白 (#6327)





 
by design

**Comment by mushroomlb** [comment]
![image](https://user-images.githubusercontent.com/1701771/78974325-560e6d00-7b44-11ea-93ff-3d5c811925bd.png)

使用umi创建simple项目时，菜单改为topmenu出现 @xiaohuoni

**Comment by chenshuai2144** [comment]
antd 的 bug，正在发版本
