### ISSUE TITLE
可以出个基于typescript 的脚手架吗

### ISSUE THREAD

**Issue by huanglei1991** [ant-design/ant-design-pro#633]
想使用typescript开发 但是不清楚有没有比较好的工程案例

**Comment by chenshuai2144** [comment]
typescript你只能使用组件化了！重新写别的

**Comment by huanglei1991** [comment]
@chenshuai2144  我们公司做自己产品就维护好几个项目就好了 感觉用ts比较稳健如果有基于ts的脚手架希望能通知我

**Comment by chenshuai2144** [comment]
暂时不会有的
#93  看看这个
