### ISSUE TITLE
🐛[BUG]升级umijs到3.0后IE11下就不行了

### ISSUE THREAD

**Issue by FFJUN** [ant-design/ant-design-pro#6331]
### 🐛 bug 描述

配置targets: {  ie: 11,},也没有效果，开发和build之后都是报这个Promise未定义的错误
![}7%1`XG@FZFQWI8ZV8C4 A0](https://user-images.githubusercontent.com/22334300/78872401-d1581c00-7a7b-11ea-8bc8-1782a5b01bea.png)
![70ON82C} P@4J5W6X3BQ(9U](https://user-images.githubusercontent.com/22334300/78872415-d4eba300-7a7b-11ea-8b89-d7fb6de66ca6.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.0.18
- 浏览器环境 IE11
- 开发环境 [e.g. mac OS] window10

**Comment by XSmarter** [comment]
+1

**Comment by ijisen** [comment]
+1

**Comment by chenshuai2144** [comment]
试了一下开发的时候，但是 build 可以的
