### ISSUE TITLE
🧐[问题] 打包时老是卡住不知道为什么？

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#6334]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/33716687/78956702-ab7f5580-7b15-11ea-86af-50fcf004af8c.png)

刚升级了umi 3.1.0 按照下面commit，删除了一些配置，就这样了
https://github.com/ant-design/ant-design-pro/commit/d124863b69be88fc342f007dfeda2644e5ece589

**Comment by chenshuai2144** [comment]
看起来是插件执行报错了，我用 pro 试了试没有问题。来个重现仓库？

**Comment by XSmarter** [comment]
![image](https://user-images.githubusercontent.com/33716687/78973652-ecda2a00-7b42-11ea-83c1-b9e353b5d997.png)
umi3.1.0 是修改了打包方式了吗？为什么文件大小变化成这样了，然后打包时间200s。。。

umi.js 文件变小了（原本1.4m），其他的的文件（原本最多就几百k）变大了。。。。

**Comment by chenshuai2144** [comment]
修改一下规则，可以让页面加载的速度更快

你可以更新插件来减少包大小，icon 已经支持按需加载了
