### ISSUE TITLE
用ant design pro4.0提供的模板代码，运行以及打包的问题🐛[BUG]

### ISSUE THREAD

**Issue by bieao-coding** [ant-design/ant-design-pro#6337]
打包时直接提示：  The bundle size is significantly larger than recommended
运行时直接提示：[BABEL] Note: The code generator has deoptimised the styling of D:\coding\newCrane\newCraneReact\node_modules\_mapbox-gl@1.9.1@mapbox-gl\dist\mapbox-gl.js as it exceeds the max of 500KB.

**Comment by chenshuai2144** [comment]
这个是提示你的文件太大，如果不是特别在乎可以忽略。

另外 你的 gl 的包很大，可以考虑 异步加载
