### ISSUE TITLE
umi-plugin-antd-theme 自定义主题不生效🧐[问题]

### ISSUE THREAD

**Issue by zhangpengfa666** [ant-design/ant-design-pro#6338]
### 🧐 问题描述

![20200410103357](https://user-images.githubusercontent.com/43570454/78957456-f26e4a80-7b17-11ea-931b-943c4ddc82ed.png)
![20200410103432](https://user-images.githubusercontent.com/43570454/78957458-f4d0a480-7b17-11ea-8b4f-97d682027596.png)
![20200410103514](https://user-images.githubusercontent.com/43570454/78957460-f4d0a480-7b17-11ea-8bf3-2a07cf5762a3.png)
这个怎么解决

**Comment by zhangpengfa666** [comment]
plugins.push(['umi-plugin-antd-theme', {
    theme: [
      {
        fileName: 'theme2.css',
        key: 'theme1',
        // theme: 'dark',
        modifyVars: {
          '@primary-color': '#EB5E5E',
          // '@menu-dark-color': '#324444',
          // '@menu-dark-bg': '#5A5A5A',
        },
      },
      {
        fileName: 'theme2.css',
        key: 'theme2',
        // theme: 'dark',
        modifyVars: {
          '@primary-color': '#F7A0AF',
          // '@menu-dark-color': '#9B9B9B',
          // '@menu-dark-bg': '#3A3A3A',
        },
      },
    ],
    // 是否压缩css
    min: true,
    // css module
    isModule: true,
    // 忽略 antd 的依赖
    ignoreAntd: false,
    // 忽略 pro-layout
    ignoreProLayout: false,
    // 不使用缓存
    cache: true,
  }]);

 quickTheme = () => {
    let styleLink = document.getElementById('theme-style');
    let body = document.getElementsByTagName('body')[0];
    if (styleLink) {
      // 假如存在id为theme-style 的link标签，直接修改其href
      if (theme1) {
        styleLink.href = '/theme/theme1.css'; // 切换 antd 组件主题
        body.className = 'body-wrap-theme1'; // 切换自定义组件的主题
      } else {
        styleLink.href = '/theme/theme2.css';
        body.className = 'body-wrap-theme2';
      }
      theme1 = !theme1;
    } else {
      // 不存在的话，则新建一个
      styleLink = document.createElement('link');
      styleLink.type = 'text/css';
      styleLink.rel = 'stylesheet';
      styleLink.id = 'theme-style';
      if (theme1) {
        styleLink.href = '/theme/theme1.css';
        body.className = 'body-wrap-theme1';
      } else {
        styleLink.href = '/theme/theme2.css';
        body.className = 'body-wrap-theme2';
      }
      theme1 = !theme1;
      document.body.append(styleLink);
    }
  }
加上上面两段代码, 点击切换会出现下面问题 :
index.jsx:48 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8000/theme/theme1.css".  
@chenshuai2144

**Comment by tomgao365** [comment]
umi@3 版本？主题的配置方式改了
https://pro.ant.design/docs/dynamic-theme-cn

**Comment by zhangpengfa666** [comment]
@tomgao365  请问一下config/theme.config.json如何配置自定义主题🙏

**Comment by tomgao365** [comment]
```json
{
  "theme": [
    {
      "key": "dark",
      "fileName": "dark.css",
      "theme": "dark"
    },
    {
      "key": "dust",
      "fileName": "dust.css",
      "modifyVars": {
        "@primary-color": "#F5222D"
      }
    },
    {
      "key": "volcano",
      "fileName": "volcano.css",
      "modifyVars": {
        "@primary-color": "#FA541C"
      }
    },
    {
      "key": "sunset",
      "fileName": "sunset.css",
      "modifyVars": {
        "@primary-color": "#FAAD14"
      }
    },
    {
      "key": "cyan",
      "fileName": "cyan.css",
      "modifyVars": {
        "@primary-color": "#13C2C2"
      }
    },
    {
      "key": "green",
      "fileName": "green.css",
      "modifyVars": {
        "@primary-color": "#52C41A"
      }
    },
    {
      "key": "geekblue",
      "fileName": "geekblue.css",
      "modifyVars": {
        "@primary-color": "#2F54EB"
      }
    },
    {
      "key": "purple",
      "fileName": "purple.css",
      "modifyVars": {
        "@primary-color": "#722ED1"
      }
    },
    {
      "key": "dust",
      "theme": "dark",
      "fileName": "dark-dust.css",
      "modifyVars": {
        "@primary-color": "#F5222D"
      }
    },
    {
      "key": "volcano",
      "theme": "dark",
      "fileName": "dark-volcano.css",
      "modifyVars": {
        "@primary-color": "#FA541C"
      }
    },
    {
      "key": "sunset",
      "theme": "dark",
      "fileName": "dark-sunset.css",
      "modifyVars": {
        "@primary-color": "#FAAD14"
      }
    },
    {
      "key": "cyan",
      "theme": "dark",
      "fileName": "dark-cyan.css",
      "modifyVars": {
        "@primary-color": "#13C2C2"
      }
    },
    {
      "key": "green",
      "theme": "dark",
      "fileName": "dark-green.css",
      "modifyVars": {
        "@primary-color": "#52C41A"
      }
    },
    {
      "key": "geekblue",
      "theme": "dark",
      "fileName": "dark-geekblue.css",
      "modifyVars": {
        "@primary-color": "#2F54EB"
      }
    },
    {
      "key": "purple",
      "theme": "dark",
      "fileName": "dark-purple.css",
      "modifyVars": {
        "@primary-color": "#722ED1"
      }
    }
  ]
}

```

**Comment by zhangpengfa666** [comment]
@tomgao365   非常感谢👌

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？
一劳永逸的解决问题

**Comment by quicklearning123** [comment]
> ```json
> {
>   "theme": [
>     {
>       "key": "dark",
>       "fileName": "dark.css",
>       "theme": "dark"
>     },
>     {
>       "key": "dust",
>       "fileName": "dust.css",
>       "modifyVars": {
>         "@primary-color": "#F5222D"
>       }
>     },
>     {
>       "key": "volcano",
>       "fileName": "volcano.css",
>       "modifyVars": {
>         "@primary-color": "#FA541C"
>       }
>     },
>     {
>       "key": "sunset",
>       "fileName": "sunset.css",
>       "modifyVars": {
>         "@primary-color": "#FAAD14"
>       }
>     },
>     {
>       "key": "cyan",
>       "fileName": "cyan.css",
>       "modifyVars": {
>         "@primary-color": "#13C2C2"
>       }
>     },
>     {
>       "key": "green",
>       "fileName": "green.css",
>       "modifyVars": {
>         "@primary-color": "#52C41A"
>       }
>     },
>     {
>       "key": "geekblue",
>       "fileName": "geekblue.css",
>       "modifyVars": {
>         "@primary-color": "#2F54EB"
>       }
>     },
>     {
>       "key": "purple",
>       "fileName": "purple.css",
>       "modifyVars": {
>         "@primary-color": "#722ED1"
>       }
>     },
>     {
>       "key": "dust",
>       "theme": "dark",
>       "fileName": "dark-dust.css",
>       "modifyVars": {
>         "@primary-color": "#F5222D"
>       }
>     },
>     {
>       "key": "volcano",
>       "theme": "dark",
>       "fileName": "dark-volcano.css",
>       "modifyVars": {
>         "@primary-color": "#FA541C"
>       }
>     },
>     {
>       "key": "sunset",
>       "theme": "dark",
>       "fileName": "dark-sunset.css",
>       "modifyVars": {
>         "@primary-color": "#FAAD14"
>       }
>     },
>     {
>       "key": "cyan",
>       "theme": "dark",
>       "fileName": "dark-cyan.css",
>       "modifyVars": {
>         "@primary-color": "#13C2C2"
>       }
>     },
>     {
>       "key": "green",
>       "theme": "dark",
>       "fileName": "dark-green.css",
>       "modifyVars": {
>         "@primary-color": "#52C41A"
>       }
>     },
>     {
>       "key": "geekblue",
>       "theme": "dark",
>       "fileName": "dark-geekblue.css",
>       "modifyVars": {
>         "@primary-color": "#2F54EB"
>       }
>     },
>     {
>       "key": "purple",
>       "theme": "dark",
>       "fileName": "dark-purple.css",
>       "modifyVars": {
>         "@primary-color": "#722ED1"
>       }
>     }
>   ]
> }
> ```

@chenshuai2144 @tomgao365  请问下
      "key": "dark",
      "fileName": "dark.css",
如何使用呢？
比如用代码实现切换功能，key是用来做啥的？
styleLink.href = '/theme/{fileName}';
是这样用吗？
