### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by nanase-takesi** [ant-design/ant-design-pro#6339]
### 📷 复现步骤
执行 npm run fetch:blocks 命令

### 💻 复现代码
error: pathspec 'umi@3' did not match any file(s) known to git
✖ 🚛  sync file for git repo --branch umi@3
ℹ  info      发生错误，请尝试 `umi block clear`
✖  error     AssertionError [ERR_ASSERTION]: /Users/takesi/.umi3/blocks/github.com/ant-design/pro-blocks/UserRegisterResult don't exists
    at /Users/takesi/Desktop/商家领券业务系统/ant-design-pro/node_modules/@umijs/block-sdk/lib/addBlock.js:224:27
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/takesi/Desktop/商家领券业务系统/ant-design-pro/node_modules/@umijs/block-sdk/lib/addBlock.js:110:103)
    at _throw (/Users/takesi/Desktop/商家领券业务系统/ant-design-pro/node_modules/@umijs/block-sdk/lib/addBlock.js:112:291)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xiaohuoni** [comment]
试过清楚缓存了嘛？ umi block clear

**Comment by nanase-takesi** [comment]
清了，执行了两遍都是一样的结果

**Comment by xiaohuoni** [comment]
是什么电脑系统？问题里面好像没写

**Comment by nanase-takesi** [comment]
Mac book pro

**Comment by nanase-takesi** [comment]
他这个错误意思难道不是找不到这个仓库地址吗

**Comment by nanase-takesi** [comment]
我遇到很多问题，比如在umi ui 里添加模版，都会出现错误

**Comment by chenshuai2144** [comment]
@nanase-takesi 更新依赖依赖，并且清除缓存，
这个是一个历史 bug，已经修复了

**Comment by nanase-takesi** [comment]
OK了，谢了
