### ISSUE TITLE
🐛[BUG]scroll={{ y: 400 }}添加这个属性之后，表头CheckBox会左移约17px的宽度，导致与下面内容记录中的CheckBox无法对齐

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro#6340]
### 🐛 bug 描述

scroll={{ y: 400 }}
给Protable添加这个属性之后，表头CheckBox会左移约17px的宽度，导致与下面内容记录中的CheckBox无法对齐，即使把scroll滚动条的宽度设置的很细，例如2px，仍然这样
### 📷 复现步骤
1、创建一个包含ProTable的页面，支持选择全部记录，让第一列的CheckBox显示出来
2、给ProTable添加一个属性 scroll={{ y: 400 }}，y值可以随意设置
3、观察表头中的CheckBox与下面每个内容记录中的CheckBox是否左或右对齐

### 🏞 期望结果
给ProTable添加scroll={{ y: 400 }}这样的属性之后，表头和下面各个记录中的scroll={{ y: 400 }}仍然能对齐

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本  3.0.14
- 浏览器环境 Chrome 73.0
- 开发环境 Windows 7

**Comment by chenshuai2144** [comment]
已经去掉了我们的 hack
