### ISSUE TITLE
空目录，创建报错，大神们帮忙看看🧐[问题]

### ISSUE THREAD

**Issue by balala2oo8** [ant-design/ant-design-pro#6342]
![s](https://user-images.githubusercontent.com/16219142/78965042-7f240300-7b2e-11ea-8c7e-a73578921624.png)

**Comment by way-jm** [comment]
我也遇到了这个情况

**Comment by Tangyincheng** [comment]
我也是这个问题，在选择语言后你的文件夹里会生成一个文件，这个时候先把这个文件删掉，再选择simple，就可以了，但是我语言选得JS下载下来得代码还是TS版本的。

**Comment by way-jm** [comment]
> 我也是这个问题，在选择语言后你的文件夹里会生成一个文件，这个时候先把这个文件删掉，再选择simple，就可以了，但是我语言选得JS下载下来得代码还是TS版本的。

yarn create umi [app-name]也是可以的，就是在空目录里面直接yarn create umi会报目录已存在并且不为空。

**Comment by balala2oo8** [comment]
谢谢了，完美！
