### ISSUE TITLE
👑 [需求]我使用yarn create umi 选择了Javascript版本，怎么所有的文件还是TS版本的呢

### ISSUE THREAD

**Issue by Tangyincheng** [ant-design/ant-design-pro#6343]

**Comment by hot588** [comment]
升级到最新版！

**Comment by yysfwls** [comment]
你怎么解决的

**Comment by Tangyincheng** [comment]
> 你怎么解决的
用yarn create mui创建的时候，第二部选择Js，第三步选择simple就是js版本的了，

**Comment by Enhoo** [comment]
奇怪 我选择了 simple 还是不可以

**Comment by yysfwls** [comment]
> > 你怎么解决的
> > 用yarn create mui创建的时候，第二部选择Js，第三步选择simple就是js版本的了，

packjson里是1.0.0啊啊

**Comment by ISBN9527** [comment]
+1同问怎么解决的？

**Comment by Tangyincheng** [comment]
> +1同问怎么解决的？

npm create umi
? Select the boilerplate type ant-design-pro
? � Be the first to experience the new umi@3 ? No
? � Which language do you want to use? JavaScript
? � Do you need all the blocks or a simple scaffold? simple
false
? � Time to use better, faster and latest antd@4! No

这样是可以的

**Comment by ISBN9527** [comment]
> npm create umi

? � Be the first to experience the new umi@3 ? No
是怎么跳过的？

**Comment by ISBN9527** [comment]
> > +1同问怎么解决的？
> 
> npm create umi
> ? Select the boilerplate type ant-design-pro
> ? � Be the first to experience the new umi@3 ? No
> ? � Which language do you want to use? JavaScript
> ? � Do you need all the blocks or a simple scaffold? simple
> false
> ? � Time to use better, faster and latest antd@4! No
> 
> 这样是可以的


> ? � Be the first to experience the new umi@3 ? No
这步是怎么操作的？
我的是这样
mac@macdeMacBook-Pro-2:~|⇒  npm create umi
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ?
  Pro V5
❯ Pro V4

**Comment by ISBN9527** [comment]
npm create umi youApp
现在必须是这样了，哈哈哈😀

**Comment by ISBN9527** [comment]
要不选择PRO V4 要不选择 PRO V5

**Comment by hankaibo** [comment]
我有一个基于官方版本4做的js版本。
https://github.com/hankaibo/myantdpro
将官方ts文件完全js化，定期手动同步官方文件😂，并在其基础上集成了权限管理等公共页面，而且提供真实后台接口。
希望可以帮到各位。

**Comment by iHDJ** [comment]
> 我有一个基于官方版本4做的js版本。
> https://github.com/hankaibo/myantdpro
> 将官方ts文件完全js化，定期手动同步官方文件😂，并在其基础上集成了权限管理等公共页面，而且提供真实后台接口。
> 希望可以帮到各位。

好人一胎五个
