### ISSUE TITLE
🐛[BUG]history.push(path,query) 数据加载不同步

### ISSUE THREAD

**Issue by hu272293309** [ant-design/ant-design-pro#6345]
### 🐛 bug 描述
history.push({pathname,query}) 数据加载不同步，不是最新的
history.replace ({pathname,query})  也是一样的

### 📷 复现步骤
routes
{
              name: 'vehicle',
              path: '/vehicle',
              // hideChildrenInMenu: true,
              // component: './vehicle/list',
              routes: [
                {
                  name: 'list',
                  path: '/vehicle/list',
                  component: './vehicle/list',
                },
                {
                  name: 'edit',
                  hideInMenu: true,
                  path: '/vehicle/edit',
                  component: './vehicle/edit',
                },
                {
                  name: 'detail',
                  hideInMenu: true,
                  path: '/vehicle/detail',
                  component: './vehicle/detail',
                },
              ]
            },
在Vehicle List中点击编辑进入vehicle/edit,用 history.push({pathname, query})
第一种读取数据方式
componentDidMount() {
    const { dispatch, location } = this.props;
    const { query } = location

    dispatch({
      type: 'vehicleDetail/query',
      payload: query,
    });

  }
第二种读取数据方式
subscriptions: {
    setup({ dispatch, history }) {
      history.listen(({ pathname, query }) => {
        const match = pathRegexp('/vehicle/edit').exec(pathname)
        if (match) {
          dispatch({ type: 'query', payload: query  })
        }
      })
    },
  },

这两种读取数据的方式都不同步
/vehicle/edit?id=1
  页面数据是空的
/vehicle/edit?id=2
  页面显示的是id=1的数据

<Form  form={form}  initialValues={initData} onFinish={handleSubmit}>

</Form>
  

### 🏞 期望结果

id = 1 时显示1的数据
id = 2 时显示2的数据

### © 版本信息

- Ant Design Pro 版本: last
- umi 版本 3.1.1
- 浏览器环境 Chrome
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
`history.push({pathname,query})` 这个只是单纯的跳转页面而已，看样是是你的页面数据加载出了问题。props 修改没有重新刷新数据

**Comment by hu272293309** [comment]
@chenshuai2144 props如何进行重新刷新数据
export default connect(({ vehicleEdit, loading }) => ({ vehicleEdit, loading}))(VehicleEdit)
这样不能刷新数据吗？

**Comment by chenshuai2144** [comment]
在didupdate中更新一下

可以去看看react的生命周期来学习

**Comment by hu272293309** [comment]
@chenshuai2144 
我通过下面两种方式获取更新数据， 你看可行吗 ，为什么还不是最数据呢
第一种读取数据方式
componentDidMount() {
const { dispatch, location } = this.props;
const { query } = location

dispatch({
  type: 'vehicleDetail/query',
  payload: query,
});
}
第二种读取数据方式
subscriptions: {
setup({ dispatch, history }) {
history.listen(({ pathname, query }) => {
const match = pathRegexp('/vehicle/edit').exec(pathname)
if (match) {
dispatch({ type: 'query', payload: query })
}
})
},
},

**Comment by chenshuai2144** [comment]
生命周期看一下你就懂了

**Comment by hu272293309** [comment]
@chenshuai2144 感谢 ！已解决
