### ISSUE TITLE
🧐[问题] 升级到umi 3 和 antd 4后，浏览器edge访问有一些页面报错，不知道具体什么原因

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#6346]
### 🧐 问题描述
升级到umi 3 和 antd 4后，浏览器edge访问有一些页面报错，不知道具体什么原因。浏览器报错如下：

![image](https://user-images.githubusercontent.com/33716687/78972277-f8782180-7b3f-11ea-84fa-4fe56369dcfe.png)

**Comment by chenshuai2144** [comment]
这个我还真没见过

**Comment by XSmarter** [comment]
const ws = new WebSocket('ws:localhost:5000'); 好像是我一连接websocket 就报错了 ...

**Comment by chenshuai2144** [comment]
清空缓存再来一下 git clean -dfx 一把 一般能解决大部分问题
