### ISSUE TITLE
🧐[问题] props 修改如何重新刷新数据

### ISSUE THREAD

**Issue by hu272293309** [ant-design/ant-design-pro#6348]
### 🧐 问题描述

props 修改如何重新刷新数据

### 💻 示例代
const VehicleEdit = ({ vehicleEdit, loading }) =>
{
       return (
<Form  form={form}  initialValues={initData} onFinish={handleSubmit}>
</Form>
)
}
export default connect(({ vehicleEdit, loading }) => ({ vehicleEdit, loading}))(VehicleEdit)

**Comment by chenshuai2144** [comment]
先把markdown 写的好

然后去看看  [生命周期](https://reactjs.org/docs/react-component.html#updating)，
