### ISSUE TITLE
🐛[BUG]npm create umi创建项目菜单栏bug

### ISSUE THREAD

**Issue by Shujunhuai** [ant-design/ant-design-pro#6349]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/49665926/78976908-c23f9f80-7b49-11ea-9b01-459a78cda1b9.png)
![image](https://user-images.githubusercontent.com/49665926/78976935-cbc90780-7b49-11ea-90cb-644e1d44c2fd.png)
![image](https://user-images.githubusercontent.com/49665926/78976948-d4214280-7b49-11ea-97b3-63d727db288b.png)

### 📷 复现步骤

菜单的bug，菜单收起是看不见二级菜单，不显示图标，菜单收起是还可以看待菜单名称
直接创建项目再 npm start 就是这样的

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重新安装依赖，umi 发了 3.1 了已经

**Comment by Shujunhuai** [comment]
![image](https://user-images.githubusercontent.com/49665926/78977195-4eea5d80-7b4a-11ea-8f6d-a5eb09133f95.png)
这是解决菜单栏图标的问题方法吗，我试了没有用

**Comment by Shujunhuai** [comment]
> 重新安装依赖，umi 发了 3.1 了已经

umi升级3.1还是没用，菜单还是这样的bug

**Comment by Shujunhuai** [comment]
> 重新安装依赖，umi 发了 3.1 了已经

![image](https://user-images.githubusercontent.com/49665926/78981730-22870f00-7b53-11ea-8270-4fc768b0c4e4.png)
图标的的问题可以了， 菜单栏的不行
