### ISSUE TITLE
代码使用异步加载，打包后没有执行文件拆分

### ISSUE THREAD

**Issue by welkink** [ant-design/ant-design-pro#635]
代码使用异步加载，执行Npm run build命令打包后，没有进行文件拆分。导致index 文件2M多。并且执行后也全部加载。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34710720-6f19668a-f557-11e7-99dc-03889272c387.png)


.webpackrc

关了 disableDynamicImport：false

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/7830f524e46b305594329b0b054ded5ab28f75fc
