### ISSUE TITLE
cross-env REACT_APP_ENV 失效🐛[BUG]

### ISSUE THREAD

**Issue by tailang** [ant-design/ant-design-pro#6350]
### 🐛 bug 描述
yarn start:test 或 yarn start:pre 启动后，项目无法获取到REACT_APP_ENV环境变量，导致proxy一直读取到dev

### 📷 复现步骤
必现

### 💻 复现代码
必现

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本 2.13.7
- 浏览器环境 Google Chrome 已是最新版本
- 版本 80.0.3987.149（正式版本） （64 位）
- 开发环境 mac OS

### 🚑 其他信息

![截屏2020-04-10 下午5 20 39](https://user-images.githubusercontent.com/3025182/78980028-9aebd100-7b4f-11ea-8f33-7483eeee7be2.png)
![截屏2020-04-10 下午5 21 07](https://user-images.githubusercontent.com/3025182/78980061-ab9c4700-7b4f-11ea-83a5-6bd658ed2e7e.png)
![截屏2020-04-10 下午5 21 32](https://user-images.githubusercontent.com/3025182/78980088-bb1b9000-7b4f-11ea-95b7-b10e0f92e1bd.png)
![截屏2020-04-10 下午5 22 03](https://user-images.githubusercontent.com/3025182/78980116-cd95c980-7b4f-11ea-98fb-fc9c883d8a29.png)
<img width="410" alt="截屏2020-04-10 下午5 22 27" src="https://user-images.githubusercontent.com/3025182/78980142-ddada900-7b4f-11ea-8ac0-2aaac02a02e0.png">

**Comment by chenshuai2144** [comment]
有没有更新插件到最新版本？

**Comment by tailang** [comment]
是指umi的插件吗？现在umi版本是2.13.7 @chenshuai2144

**Comment by chenshuai2144** [comment]
REACT_APP_ENV 这个插件需要 antd@3，我现在内置到了 @umijs/preset-pro-ant-design
