### ISSUE TITLE
🐛[BUG] I can't run up successfully custom tests with the npm commands

### ISSUE THREAD

**Issue by gabe2code** [ant-design/ant-design-pro#6353]
### 🐛 bug I can't execute customs test with the npm commands

I can't execute the custom test with npm test: all or npm test .test.js. I added the test case of the login described in the [official documentation](https://pro.ant.design/docs/ui-test#focus-or-ignore-test-cases) and doesn't work either, :( 

I use the command **npm test .test.js  "tsx in my case cause i'm using the typescript version"** and I receive ` ReferenceError: __UMI_HTML_SUFFIX is not defined`. Any suggestions to solve those issues?

- Ant Design Pro: 4.0.0
- umi 2.13
- Chrome
- Windows 10

**Comment by gabe2code** [comment]
I was able to solve the problem setting the variable as false in the jest configuration, inside the global variables, but I think this is a temporary solution, maybe you guys have a better way to solve it

`__UMI_HTML_SUFFIX: false`

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它


——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
