### ISSUE TITLE
🧐[问题]there is an error message after exec command 'npm start';

### ISSUE THREAD

**Issue by yanjc39** [ant-design/ant-design-pro#6354]
### 🧐 问题描述
当执行npm start 后能启动；但是在打开页面的时候会提示：
UnhandledPromiseRejectionWarning: TypeError: text.trimEnd is not a function

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33985927/79011649-0efd9780-7b97-11ea-9916-bfa73b010867.png)

**Comment by rodbv** [comment]
I'm having the same issue when starting a new project, both on Typescript and JS versions.
If I start a v3 project it works fine.

**Comment by afc163** [comment]
https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/issues/14#issuecomment-528788007

Please upgrade node version greater than 10.x

**Comment by Harrypotterrrr** [comment]
Thanks for the above answer. it did!
