### ISSUE TITLE
🧐[问题]用`npm create umi`初始化ant-design-pro，总是提示不是空目录，但确实是空目录

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design-pro#6355]
### 🧐 问题描述
用`npm create umi`初始化ant-design-pro，总是提示不是空目录，但确实是空目录。当选择用JavaScript时文件夹下会生成一个.yo-repository

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/16435301/79032482-750b0e80-7bd9-11ea-9bed-8023931e36cc.png)

**Comment by kaindy7633** [comment]
跟我遇到的问题一样，一直提示文件夹已存在或不是一个空的目录，后来到Mac环境下，也是同样的，我又在全局安装了 `create-umi`，结果还是一样，求解决方案~~

**Comment by chenshuai2144** [comment]
目录下有文件的，可以这样用 `yarn create umi myapp`

**Comment by wuzhitian** [comment]
好吧，所有的问题在于
![image](https://user-images.githubusercontent.com/4716708/89023431-2800a300-d356-11ea-9223-590f27efa917.png)
由于用户根目录下有 .yo-rc 文件，里面有相关的配置，生成的项目已经在用户根目录了 /Users/you-name 里面了，不在当前执行目录
