### ISSUE TITLE
🐛[BUG] 切换国际化语言后 菜单图标没有渲染 而是显示图标名  如team  没有显示图标

### ISSUE THREAD

**Issue by huangfy1** [ant-design/ant-design-pro#6357]
### 🐛 bug 描述

切换国际化语言后 菜单图标没有渲染 而是显示图标名  如team  没有正确的显示图标，而是显示图标名称 team

**Comment by muashell** [comment]
![image](https://user-images.githubusercontent.com/58284491/79052353-7afc0080-7c68-11ea-8564-301b550fc748.png)
同样的问题

**Comment by muashell** [comment]
![image](https://user-images.githubusercontent.com/58284491/79052391-c4e4e680-7c68-11ea-92ad-935b441c01f7.png)
同样的问题

**Comment by muashell** [comment]
https://github.com/ant-design/ant-design-pro/issues/6326
https://github.com/ant-design/ant-design-pro/issues/6332
https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8

已参考以上文档,
但未能解决问题,
我想请教一下,
在v4版本下动态从服务器获取"带图标的菜单"的正确方式是什么呢?

**Comment by chenshuai2144** [comment]
可以看这个 demo

https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon
