### ISSUE TITLE
👑 [需求]文档内容与实际情况有出入，不能正常安装

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#6358]
### 🥰 需求描述

按照现在页面的的使用指导不能正常安装
执行yarn create umi或npm create umi,报错不是空文件夹，但是执行命令选择的时候会自动在文件夹里生成一个.yo-repository的文件夹

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13833722/79035383-93c8cf80-7bf0-11ea-8f1d-467fefc7005b.png
PS E:\antdesign-workspace\antdesignpro(ts)> yarn create umi
yarn create v1.22.4
[1/4] Resolving packages...
warning create-umi > sylvanas > @umijs/fabric > stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning create-umi > sylvanas > @umijs/fabric > stylelint-config-rational-order > stylelint > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning create-umi > sylvanas > @umijs/fabric > stylelint-config-rational-order > stylelint > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
[4/4] Building fresh packages...
success Installed "create-umi@0.21.2" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🚀 Do you need all the blocks or a simple scaffold? complete
> 🙈 complete mode can only use the version of antd@4
fatal: destination path 'E:\antdesign-workspace\antdesignpro(ts)' already exists and is not an empty directory.
✨ File Generate Done
Done in 143.04s.

**Comment by hot588** [comment]
最近才出现的，以前是没有的！我也是遇到了！直接把.yo-repository删除，就好了！他出现，就就删除，然后在一步步安装就好了！

**Comment by xuxuejin** [comment]
> 最近才出现的，以前是没有的！我也是遇到了！直接把.yo-repository删除，就好了！他出现，就就删除，然后在一步步安装就好了！

根本就没有用，还是会提示 already exists and is not an empty directory。不知道你是怎么操作的，可以成功？

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/6363
