### ISSUE TITLE
使用 yarn 安装依赖，测试跑不过

### ISSUE THREAD

**Issue by balancelove** [ant-design/ant-design-pro#636]
![image](https://user-images.githubusercontent.com/20970152/34711201-7079994e-f559-11e7-8361-b86f17934f1b.png)

使用  `yarn` 安装依赖后，测试出现这个报错问题

![image](https://user-images.githubusercontent.com/20970152/34711303-e0879e20-f559-11e7-884b-6e498a13ed2d.png)

npm 安装之后，再次跑测试，pass，没有出现问题

yarn 版本： 1.3.2

**Comment by chenshuai2144** [comment]
`yarn upgrade`
试一试

**Comment by balancelove** [comment]
还是不行

**Comment by chenshuai2144** [comment]
yarn cache clean

**Comment by balancelove** [comment]
试了不行

**Comment by chenshuai2144** [comment]
额

**Comment by balancelove** [comment]
就是不知道用yarn就不行，用 npm 就行，npm 也有 lock，npm 不会出现这个问题
