### ISSUE TITLE
最新安装的 ANT DESIGN PRO 报错

### ISSUE THREAD

**Issue by JeffreyBool** [ant-design/ant-design-pro#6361]
devScripts.js:5035 Warning: In order to ensure compatibility with antd@4, we will delete the configuration icon in the next version, details can be viewed.
为了兼容 antd@4，我们会在下个版本删除配置 icon: string 生成icon的用法。请查看

**Comment by zim-lee** [comment]
遇到了同样的问题，解决了么

**Comment by chenshuai2144** [comment]
https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8
可以看看这个文章 了解一下为什么

**Comment by JeffreyBool** [comment]
为什么不在最新代码解决 ------------------ 原始邮件 ------------------
发件人: "陈帅"<notifications@github.com>
发送时间: 2020年4月15日(星期三) 晚上10:19
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "JeffreyBool"<1402992668@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] 最新安装的 ANT DESIGN PRO 报错 (#6361)




 
Closed #6361.
 
&mdash;

**Comment by zim-lee** [comment]
仅仅从umi3.1.0->3.1.1, antd4.1.1 ->4.1.2就这样了，而且按文档说的添加插件，但是启动提示插件已经注册过了，难道现在pro-layout里面的icon不是用字符串了么

**Comment by DusuWen** [comment]
> https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8
> 可以看看这个文章 了解一下为什么

但是我并没有升级到4的打算，这样侵入性的提示，OK吗？
