### ISSUE TITLE
🐛[BUG]最新版npm create umi的TS版本工程出现问题

### ISSUE THREAD

**Issue by leonkong** [ant-design/ant-design-pro#6362]
### 🐛 bug 描述
src/pages/user/login/index.tsx  出现错误

![image](https://user-images.githubusercontent.com/26429579/79040037-44969500-7c18-11ea-9f33-30706ac32bf7.png)

![image](https://user-images.githubusercontent.com/26429579/79040057-6728ae00-7c18-11ea-91df-4d54bfce3549.png)

### 📷 复现步骤
1、新建空目录
2、进入目录npm create umi
3、选择ant-design-pro
4、选择TypeScript
5、选择complete
6、回车(这里有另外一个BUG已单提)

### 💻 复现代码
src/pages/user/login/index.tsx  出现错误

![image](https://user-images.githubusercontent.com/26429579/79040037-44969500-7c18-11ea-9f33-30706ac32bf7.png)

![image](https://user-images.githubusercontent.com/26429579/79040057-6728ae00-7c18-11ea-91df-4d54bfce3549.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.0.0
- umi 版本 3.0.14
- 浏览器环境 Chrome 
- 开发环境 [e.g. mac OS] MacOS vscode

**Comment by chenshuai2144** [comment]
重新安装一下即可，已经删除了这些代码的使用
