### ISSUE TITLE
🐛[BUG]最新版npm create umi搭建脚手架最后一步失败

### ISSUE THREAD

**Issue by leonkong** [ant-design/ant-design-pro#6363]
### 🐛 bug 描述
最新版npm create umi搭建脚手架最后一步失败

### 📷 复现步骤
1、新建空目录
2、进入目录npm create umi
3、选择ant-design-pro
4、选择TypeScript/JavaScript
5、选simple或者complete
6、回车
提示fatal: destination path '/XXX' already exists and is not an empty directory.

原因：目录里生成了一个.yo-repository目录
解决方案：在第6步前，删除.yo-repository目录即可。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by w6990548** [comment]
对对对，我今天也是一直出现这个问题，昨天还好好的呢，命名文件夹里什么都没有，在电脑哪个盘执行都不行

**Comment by w6990548** [comment]
`PS D:\ceshi> npm create umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! Yes
fatal: destination path 'D:\ceshi' already exists and is not an empty directory.
✨ File Generate Done`

**Comment by w6990548** [comment]
PS D:\ceshi> npm create umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! Yes
fatal: destination path 'D:\ceshi' already exists and is not an empty directory.
✨ File Generate Done

**Comment by hot588** [comment]
选择ant-design-pro  在选择这个以后，你的目录就不是空了，就会有个文件,你打开就知道了！然后把那个文件删除掉！继续选择TypeScript/JavaScript，就可以和以前一样安装了！

**Comment by cuibty** [comment]
> 选择ant-design-pro 在选择这个以后，你的目录就不是空了，就会有个文件,你打开就知道了！然后把那个文件删除掉！继续选择TypeScript/JavaScript，就可以和以前一样安装了！

同样遇到了这个问题，会生成一个 .yo-repository 的文件夹。

**Comment by hot588** [comment]
.yo-repository 删除掉，再安装！就行了！

**Comment by mflaugh** [comment]
> .yo-repository 删除掉，再安装！就行了！

不是删掉 .yo-repository，而是删掉包含 .yo-repository 的根目录才行。mac OS

**Comment by yaeSakuras** [comment]
> .yo-repository 删除掉，再安装！就行了！

我删除也不行，mac os

**Comment by yaeSakuras** [comment]
删除了还是提示

**Comment by lichangchao15442** [comment]
害 我也是 无解。。。

**Comment by gpzjyw** [comment]
不要新建目录，直接采用`npm create umi xxx(工程目录名)`新建工程，就不会出现上述问题了

**Comment by tonyfud** [comment]
> 不要新建目录，直接采用`npm create umi xxx(工程目录名)`新建工程，就不会出现上述问题了

对的 就是这样子， 不能在自己建立的空目录下去 create ， 需要用 create 命令去建立这个项目的文件夹。  

yarn create umi antd-pro-v4-learn

**Comment by LewinJun** [comment]
这是他们的一个bug, 给一些人安装来了一个锤子，  还是希望解决，这是第一步，用脚手架本来就是节约技术前期搭建踩坑时间成本的，文档一定要可用

**Comment by liufa520** [comment]
yarn create umi 创建的版本怎么显示的是1.0.0？？？？

**Comment by RYUDEN** [comment]
对对对 这个一定要修复 保证文档的可用性

**Comment by xqk1** [comment]
我也是，遇到这个问题

**Comment by xzplays** [comment]
前几天这个问题我也碰到了。实际上是umi目录和我们实际要用的目录冲突了，后来查了下指令发现创建的时候可以指定目录，带上后就可以正常创建了。文档写的确实有问题。

**Comment by cnahliu** [comment]
https://github.com/umijs/umi/issues/4443

**Comment by chenshuai2144** [comment]
yeoman-environment 版本升级会生成一个[` .yo-repository `](
https://github.com/yeoman/environment/blob/9880bc7d5b26beff9f0b4d5048c672a85ce4bcaa/lib/util/repository.js),  create umi 中会判断文件夹是不是为空，正好冲突了

**Comment by xuxuejin** [comment]
> 不要新建目录，直接采用`npm create umi xxx(工程目录名)`新建工程，就不会出现上述问题了

确实成功了，谢谢

**Comment by Liuhuan247** [comment]
`yarn create umi project-name`

**Comment by leonkong** [comment]
npm create umi project-name
yarn create umi project-name
已测试生成JS版和TS版脚手架均无此错误

**Comment by H-Sven** [comment]
还是不行

**Comment by H-Sven** [comment]
还是不行啊，我的目录里没有生成这个.yo-repository

用yarn create umi project-name 也不行

**Comment by xqk1** [comment]
@H-Sven 可以的，直接创建就行，不要建文件夹，直接npm create umi project-name就行，会创建一个跟project-name一样的文件夹

**Comment by H-Sven** [comment]
@xqk1 不行啊，我按照这个issues做的，还是不行 

[#7005](https://github.com/ant-design/ant-design-pro/issues/7005)
