### ISSUE TITLE
🧐[问题] 动态主题介绍模糊

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design-pro#6364]
### 🧐 问题描述

1，开发菜单下有一个“动态主题”的文档说明；
2，进阶菜单下有一个“更换主题”的文档说明；它还引用到“动态主题”。
3，入门菜单“快速升级到umi3”中说不需要这个包了，umi-plugin-antd-theme。
     动态主题时，又说功能需要umi-plugin-antd-theme包作为实现，到底需要不需要？
     umi@3版本有一句解释；
     v2版本也有一句解释；
     umi@2 版本又有解释；
     最后又说v4 中自带了 theme 插件，我看多了反而疑惑了，不知道怎么办了。
     明明是v4的版本文档，为什么又插入了v2的说明呢？
     还有这个依赖安装与不安装问题。
     最后，新代码配置中已经移除了plugins的配置，v4说直接加上plugins就行了，如果新手，刚入门，可能会不明白。
     2020-04-09日文档。

希望文档说明能更准确及时，便于新手理解。
再次感谢你们的付出。

**Comment by joesdu** [comment]
暂时别用.动态主题等最佳实践出来了,应该就有官方案例了.

**Comment by avalonWx** [comment]
而且在umi3中安装了umi-plugin-antd-theme的依赖后会导致scss的文件加载不了，也不报错。。。对于umi3晕呼呼的了，文档有些地方还有错误，而且写很不清楚，老手也容易踩坑

**Comment by chenshuai2144** [comment]
有兴趣可以来个 pr。
