### ISSUE TITLE
动态加载组件需求👑 [需求]

### ISSUE THREAD

**Issue by chungkui** [ant-design/ant-design-pro#6368]
### 🥰 需求描述

有没有办法，按需要动态加载组件，而不是一次性注册所有组件的路由。这样能保证第一次打开页面的时候不至于太慢。当用户点击到某个菜单的时候才回去加载对应组件的js

**Comment by chenshuai2144** [comment]
看这里  pro 中有配置[ config.ts](https://github.com/ant-design/ant-design-pro/blob/9f088cb3f259260a5fd869cddd9521b10779acc4/config/config.ts#L21)

https://umijs.org/config#dynamicimport
