### ISSUE TITLE
🧐[问题]引入第三方min.js后在生产环境页面为空白

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#6369]
### 🧐 问题描述
引入第三方min.js后在生产环境页面为空白

1、在dev环境中引用了下面的js，可以正常打开页面。
![image](https://user-images.githubusercontent.com/20454290/79067576-df63a200-7cf2-11ea-9496-4dfd61dd01f9.png)
效果：
![image](https://user-images.githubusercontent.com/20454290/79067607-23ef3d80-7cf3-11ea-9fd9-47320e99d155.png)

2、部署到生产环境就一直loading，加载不出来
![image](https://user-images.githubusercontent.com/20454290/79067614-3ff2df00-7cf3-11ea-8b62-317916fc1205.png)

3、百度了一下，我的问题貌似可以理解为：在umi中如何引用本地js插件？

**Comment by 419280377** [comment]
已解决

**Comment by fatesq** [comment]
> 已解决

请问怎么解决的

**Comment by 419280377** [comment]
http -&gt; https




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"宛若夜空"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月15日(星期三) 中午11:47
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"??﹏髪茹鱈〆"<419280377@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题]引入第三方min.js后在生产环境页面为空白 (#6369)





  
已解决
  
请问怎么解决的
