### ISSUE TITLE
请问：nav.js 的nav data 中name不为空，怎么让页面nav list 不显示？请看图

### ISSUE THREAD

**Issue by MerlynStone** [ant-design/ant-design-pro#637]
![question](https://user-images.githubusercontent.com/16041806/34712101-a5abe678-f55c-11e7-845b-8a23f65e6cbd.png)

**Comment by chenshuai2144** [comment]
hiddenhttps://github.com/ant-design/ant-design-pro-site/blob/master/docs/router-and-nav.md#%E9%9A%90%E8%97%8F%E8%8F%9C%E5%8D%95

**Comment by MerlynStone** [comment]
之前的版本设置无效，重写git最新版本是可以的…………

**Comment by chenshuai2144** [comment]
对 文档都是最新的

**Comment by MerlynStone** [comment]
多谢
