### ISSUE TITLE
🐛[BUG]Umi  Ui 还不抓紧修复啊！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#6370]
### 🐛 bug 描述

> 只有 pages 或 page 目录下的页面才能插入资产

> 不管是什么操作系统，都会报这个错误！

### 🏞 期望结果

让Umi UI 正常的增加模板，再模板里能够正常添加区块！

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hot588** [comment]
千万别说什么！BABEL_CACHE=none umi dev  这个在.env里根本不起作用！env里的命令只有PORT=3000,还能起个改变端口作用！至于其他的作用！都不行！！！

**Comment by AnzerWall** [comment]
无语了，所有系统都不行，上了issues发现windows下不能插入资产，我花了一天部署了了个ubuntu虚拟机，也不行。
到工作电脑上(mac)试了下也不行。

已尝试系统： windows 10 home， macOS 10， Ubuntu

**Comment by hot588** [comment]
> 无语了，所有系统都不行，上了issues发现windows下不能插入资产，我花了一天部署了了个ubuntu虚拟机，也不行。
> 到工作电脑上(mac)试了下也不行。
> 
> 已尝试系统： windows 10 home， macOS 10， Ubuntu

现在坑太升，都是一群小白！！！

**Comment by xiaohuoni** [comment]
UI 问题，统一反馈处理。https://github.com/umijs/umi/issues/4456
