### ISSUE TITLE
npm install --save umi/router报错

### ISSUE THREAD

**Issue by Tangyincheng** [ant-design/ant-design-pro#6375]
### 🥰 需求描述
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/umi/router.git
Directory: D:\project\real\testgit\Homework\ui
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by joesdu** [comment]
现在没有这个包了，看下umi的文档吧

**Comment by chenshuai2144** [comment]
可以直接使用 

`import { router } from 'umi'`

**Comment by joesdu** [comment]
> 可以直接使用 
> 
> `import { router } from 'umi'`
> 
> 更多 api 看这里 https://pro.ant.design/docs/upgrade-umi3-cn 

router在umi3中变成了history
