### ISSUE TITLE
请问ProTable的.ant-table-cell:first-child 的    padding-left: 24px怎么取消

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#6377]
padding-left: 24px怎么取消
![TIM截图20200413192236](https://user-images.githubusercontent.com/33310261/79117620-2f5b6b00-7dbe-11ea-8dec-54b769bac140.png)

**Comment by chenshuai2144** [comment]
这是为了与标题对齐？你为什么要删除呢
