### ISSUE TITLE
使用框架自带的fetch发送请求，为什么 "+" 这个符号被过滤掉，变为空格？

### ISSUE THREAD

**Issue by duanpf** [ant-design/ant-design-pro#638]
使用ant-design-pro官方脚手架里的fetch，发送请求，请求数据中的 ‘+’ 被过滤成空格，导致和后台做出的签名不一致，验签失败。

**Comment by WhatAKitty** [comment]
不适用antd-pro的项目使用fetch看看会不会有问题

**Comment by chenshuai2144** [comment]
浏览器中你用默认的fetch

**Comment by duanpf** [comment]
@WhatAKitty  使用原生fetch,不会出现被过滤现象

**Comment by chenshuai2144** [comment]
那就用原生的！ 区别不大
