### ISSUE TITLE
antDesign从昨天晚上开始浏览速度很慢很慢，组件都点不开了🧐[问题]

### ISSUE THREAD

**Issue by Wananme** [ant-design/ant-design-pro#6380]
### 🧐 问题描述

https://ant.design/docs/react/introduce-cn;
难道就我一个人这样吗 
根本用不了啊

**Comment by Wananme** [comment]
![image](https://user-images.githubusercontent.com/45476748/79179477-4770d000-7e3a-11ea-8c41-2d2dd5799c56.png)
啥啥都加载不出来 烦人

**Comment by chenshuai2144** [comment]
github pages发生了故障 可以先使用国内的镜像
