### ISSUE TITLE
fatal: destination path '/Users/pzc/repos/myapp' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by pzc666** [ant-design/ant-design-pro#6381]
![image](https://user-images.githubusercontent.com/37856520/79183108-19dc5480-7e43-11ea-8425-f30c41f7f969.png)

**Comment by ChenWeihua123** [comment]
一样的问题 你有解决吗
这是什么原因

**Comment by rannawang** [comment]
npm create umi myapp

**Comment by vellengs** [comment]
同样的问题

**Comment by ycjcl868** [comment]
找个空的新目录，或者 `yarn create umi your-app`

**Comment by vellengs** [comment]
@ycjcl868  是不是应该这样才更好，如果开始输入的命令是 yarn create umi 不带名称参数，第一个提示的是输入 项目名,  或者 抛出一个明确的异常提示必须输入项目名称，而不是等到最后才失败。

**Comment by chenshuai2144** [comment]
新的pr中会给你一个默认值
