### ISSUE TITLE
🧐[问题]切换语言的时候部分控件的语言没有变化

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#6382]
### 🧐 问题描述

切换语言的时候，有些控件的语言没有变化，需要刷新或者setlocal的时候把realReload设置成true才行，这是什么原因导致的呢？

![image](https://user-images.githubusercontent.com/50793943/79192112-afcfa980-7e5a-11ea-9be0-2fd280d2e3e5.png)

**Comment by ycjcl868** [comment]
umi 几?

**Comment by ycjcl868** [comment]
建议用 `useIntl` 进行切换

**Comment by shaohuatsou** [comment]
> 建议用 `useIntl` 进行切换

我是class组件，在里面用报错。

**Comment by shaohuatsou** [comment]
@ycjcl868 class组件里面能用吗？

**Comment by shaohuatsou** [comment]
已使用 useIntl 解决。
