### ISSUE TITLE
🧐[问题]官网示例的标准列表页点击编辑多次后current丢失

### ISSUE THREAD

**Issue by liyinSakura** [ant-design/ant-design-pro#6384]
### 🧐 问题描述

官网示例的[标准列表页](https://preview.pro.ant.design/list/basic-list)点击编辑多次后表单编辑数据没了，我想知道是故意如此设计的还是bug？如果是设计如此，为啥是这样的设计呢？

### 💻 示例代码
```javascript
  useEffect(() => {
    console.log('--------------->22',current)
    if (form && !visible) {
      form.resetFields();
    }
  }, [props.visible]);

  useEffect(() => {
    console.log('--------------->333',current)
    if (current) {
      form.setFieldsValue({
        ...current,
        createdAt: current.createdAt ? moment(current.createdAt) : null,
      });
    }
  }, [props.current]);
```
个人对reacthook不是很在行（不大清楚是不是props.current这里的问题），所以把项目代码直接复制过来了……333那条打印在第一次点击的时候是有的，22那个每次点击都会存在。
### 其他信息
另外之前为了查看是不是我自己这边代码有问题，重新建的项目里添加了标准列表页准备看看效果的，结果发现会报错Unhandled Rejection (TypeError): (0 , _umi.connect) is not a function，不知道是不是可能是版本不对的问题

**Comment by liyinSakura** [comment]
自己看了下好像是关闭的时候没有把current设置为undefined，设置了好像就可以了。

**Comment by cddumanov** [comment]
@liyinSakura Hey

I have quite same problem but different problem when I do test my component.

` FAIL  src/components/OrganizationSelect/index.test.jsx
  ● Test suite failed to run

    TypeError: (0 , _umi.connect) is not a function

      38 | };
      39 | 
    > 40 | export default connect(({ user, loading }) => ({
         |                ^
      41 |   currentUser: user.currentUser,
      42 |   loading: loading.models.user,
      43 | }))(OrganizationSelect);

      at Object.<anonymous> (src/components/OrganizationSelect/index.jsx:40:16)
      at Object.<anonymous> (src/components/OrganizationSelect/index.test.jsx:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.007s
Ran all test suites matching /src\/components\/OrganizationSelect\/index.test.jsx/i.
AssertionError [ERR_ASSERTION]: Test with jest failed
error Command failed with exit code 1.`  

Code of the test

`import React from 'react'
import { shallow } from 'enzyme';
import OrganizationSelect from './index';

it('renders Dashboard', () => {
  // Use the wrapped components
  // const wrapper = shallow(<OrganizationSelect.WrappedComponent user={{ list: [] }} loading={{user: []}}/>);
  const wrapper = shallow(<OrganizationSelect/>);
  expect(wrapper).toBe()
});`

I beg you. In English please. Thanks!

**Comment by liyinSakura** [comment]
> @liyinSakura Hey
> 
> I have quite same problem but different problem when I do test my component.
> 
> ` FAIL src/components/OrganizationSelect/index.test.jsx
> ● Test suite failed to run
> 
> ```
> TypeError: (0 , _umi.connect) is not a function
> 
>   38 | };
>   39 | 
> > 40 | export default connect(({ user, loading }) => ({
>      |                ^
>   41 |   currentUser: user.currentUser,
>   42 |   loading: loading.models.user,
>   43 | }))(OrganizationSelect);
> 
>   at Object.<anonymous> (src/components/OrganizationSelect/index.jsx:40:16)
>   at Object.<anonymous> (src/components/OrganizationSelect/index.test.jsx:3:1)
> ```
> 
> Test Suites: 1 failed, 1 total
> Tests: 0 total
> Snapshots: 0 total
> Time: 3.007s
> Ran all test suites matching /src/components/OrganizationSelect/index.test.jsx/i.
> AssertionError [ERR_ASSERTION]: Test with jest failed
> error Command failed with exit code 1.`
> 
> Code of the test
> 
> `import React from 'react'
> import { shallow } from 'enzyme';
> import OrganizationSelect from './index';
> 
> it('renders Dashboard', () => {
> // Use the wrapped components
> // const wrapper = shallow(<OrganizationSelect.WrappedComponent user={{ list: [] }} loading={{user: []}}/>);
> const wrapper = shallow();
> expect(wrapper).toBe()
> });`
> 
> I beg you. In English please. Thanks!

I did not solve this problem……
