### ISSUE TITLE
🧐[问题]pro 有没有最佳的model实践

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design-pro#6387]
### 🧐 问题描述

我常常把一个表的需求写在一个model内,在list 、create 、edit页面都共同调用这个mode,出了问题
1，我是在model 中实现存储请求数据，在不刷新页面的情况下  ，从edit路由切换到list 在点击创建出现form  里面的数据仍然是上一个edit 的数据，
2、从edit 路由到list 再到其他ID的edit ,发现也是上一个ID的数据，
虽然model中的subscriptions 监听到了history变化也执行了从新查询但form 中的数据不是当前最新的，为了规避这种情况官方有没有比较好的案例参考？
这里面涉及了dva umi ant from 我判断不出该去哪里Issue，麻烦各位大佬了
### 💻 示例代码
![image](https://user-images.githubusercontent.com/24733229/79212791-a9512a00-7e7a-11ea-9d9e-a106cf81d706.png)

<
!--
如果你有解决方案，在这里清晰地阐述
-->

**Comment by chenshuai2144** [comment]
有plugin/models  用起来简单方便

https://umijs.org/plugins/plugin-model
