### ISSUE TITLE
为什么动态渲染的菜单icon不能显示成图标而是显示成了字符呢🧐[问题]

### ISSUE THREAD

**Issue by dfhe** [ant-design/ant-design-pro#6391]
### 🧐 问题描述
菜单前面的icon无法正常显示

### 💻 示例代码
![image](https://user-images.githubusercontent.com/33407462/79243347-16c77f80-7ea8-11ea-963b-9af38c444d15.png)
![image](https://user-images.githubusercontent.com/33407462/79243461-3a8ac580-7ea8-11ea-8ae0-3d95f306b951.png)

**Comment by dfhe** [comment]
![image](https://user-images.githubusercontent.com/33407462/79243242-f26ba300-7ea7-11ea-98c0-5a0e4a05c80b.png)
![image](https://user-images.githubusercontent.com/33407462/79243284-03b4af80-7ea8-11ea-8088-8eb23821e05e.png)

**Comment by tanyueran** [comment]
+1

**Comment by chenshuai2144** [comment]
可以看这个文章 https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8

https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon
