### ISSUE TITLE
TypeError: func.apply is not a function

### ISSUE THREAD

**Issue by wuyugege** [ant-design/ant-design-pro#6394]
菜单切换报：TypeError: func.apply is not a function这个错误
菜单配置如下：

> routes: [
        {
          path: '/',
          component: '../layouts/BasicLayout',
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/product-category',
              name: 'product-category',
              icon: 'PartitionOutlined',
              authority: ['admin'],
              routes: [
                {
                  path: '/product-category/category',
                  name: 'category',
                  component: './category',
                  authority: ['admin'],
                },
                {
                  path: '/product-category/product',
                  name: 'product',
                  component: './spu',
                  authority: ['admin'],
                },
                {
                  path: '/product-category/product/detail',
                  component: './spu/detail',
                  name:'spu-detail',
                  authority: ['admin'],
                  hideInMenu: true,
                },
              ],
            },
            {
              component: './404',
            },
          ],
        },
        {
          component: './404',
        },
      ],

当我使用 代码：
`<Link to={{ pathname: '/product-category/product/detail', query: { id: 1 } }}>
            <Button type="link">编辑</Button>
          </Link>`
跳转到detail页面后，再点击product或category菜单栏时，页面就会报：

> TypeError: func.apply is not a function
HTMLUnknownElement.callCallback
./node_modules/react-dom/cjs/react-dom.development.js:188
  185 |     window.event = windowEvent;
  186 |   }
  187 | 
> 188 |   func.apply(context, funcArgs);
      | ^  189 |   didError = false;
  190 | } // Create a global error event handler. We use this to capture the value
  191 | // that was thrown. It's possible that this error handler will fire more

使用的是开发环境，项目依赖如下

> "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.2.0",
    "@antv/data-set": "^0.11.2",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "antd": "^4.0.0",
    "bizcharts": "^3.5.8",
    "bizcharts-plugin-slider": "^2.1.1",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.0.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },

**Comment by chenshuai2144** [comment]
`git clean -dfx` 然后再安装依赖
