### ISSUE TITLE
首个加载的页面，或者当前url刷新会进入loading 无法加载🐛[BUG]

### ISSUE THREAD

**Issue by fatesq** [ant-design/ant-design-pro#6395]
### 🐛 bug 描述

首个加载的页面，或者当前url刷新会进入loading 无法加载
![)MSVSNQEHZXQFIBGY} K6UW](https://user-images.githubusercontent.com/11306229/79293045-3c36a680-7f05-11ea-88e6-b8e5c950b7ce.png)
路由从后端获取，总是无法获取页面加载时第一个url的page文件。
例如 A B C D 4个页面，
刷新页面url是/A时，右侧A总是loading，点击左侧菜单 B，C， D正常加载
刷新页面url是/B时，右侧B总是loading，点击左侧菜单 A，C， D正常加载

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个报错是因为组件为空导致的，应该是你的某个组件为空
可以用二分法来找到是什么组件报错了

**Comment by fatesq** [comment]
并没有为空的组件，而且只在首次加载会这样
![(JQ57BH_EX {YJ@ 6A`G651](https://user-images.githubusercontent.com/11306229/79722882-70500400-8317-11ea-90e4-bcb809189710.png)

**Comment by koupeng** [comment]
我也偶尔会遇到这个问题。
