### ISSUE TITLE
🧐[问题] ProLayout header 原组件覆盖样式问题

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#6396]
### 🧐 问题描述

自带的demo

<ProLayout
        logo={logo}
        className={styles.antHeaderMy}

.antHeaderMy {
  :global() {
    .ant-layout-header {
      background: "#0074FF";
    }

  }
}

样式覆盖不了header

### 🚑 其他信息

![WechatIMG254](https://user-images.githubusercontent.com/19459174/79308600-74e97680-7f2b-11ea-8e50-fca97a18cbd4.jpeg)

**Comment by chenshuai2144** [comment]
提升一下 css 的优先级

```
body .myclassname{
// something
}
```

**Comment by LewinJun** [comment]
> 提升一下 css 的优先级
> 
> ```
> body .myclassname{
> // something
> }
> ```

还是不行，  我不是专门搞前端的， 有点菜， 还望指教一下，谢谢
<img width="548" alt="截屏2020-04-16 下午3 02 39" src="https://user-images.githubusercontent.com/19459174/79424811-55b61c00-7ff3-11ea-9c03-0e954160732a.png">

**Comment by zonday** [comment]
background: "#0074FF";  不要引号！！！
 background: #0074FF；

**Comment by LewinJun** [comment]
> background: "#0074FF"; 不要引号！！！
> background: #0074FF；

哈哈，懵逼了，因为刚刚写完RN 应用，习惯带上来了，谢谢
