### ISSUE TITLE
👑 [需求]Table组件不更新数据的问题

### ISSUE THREAD

**Issue by Tangyincheng** [ant-design/ant-design-pro#6397]
### 🥰 需求描述
我的项目中组件的一个Table接收props传进来的数据，然后展示。当数据更新之后，Table组件没有更新，但是数据确实已经更新。当我在此组件中使用List进行同样的操作时，List会更新数据，请问一下这是i咋回事呢？？

**Comment by chenshuai2144** [comment]
Table 有优化的，你可以 {...props} 来每次触发更新吗

**Comment by Tangyincheng** [comment]
> Table 有优化的，你可以 {...props} 来每次触发更新吗

之前在父组件中我用push更新数组，子组件中的Table没有更新，但是我试了在父组件中用concat更新数组，子组件中的Table就更新了。有点迷...
