### ISSUE TITLE
🐛[BUG] 相同请求方式，相同api, 返回的是其它目录下面的_mock.js数据

### ISSUE THREAD

**Issue by huaiguoguo** [ant-design/ant-design-pro#6398]
### 🐛 bug 描述

本目录下的_mock.js与其它目录下的_mock.js下  存在相同api时，
并没有返回本目录下的_mock.js返回的数据， 而是最后一个有相同api的_mock.js返回的数据
下面有图，项目是今天搭建的....

### 📷 复现步骤
```
在 src\pages\list\basic-list\index.jsx 这个页面调用

// src\pages\list\basic-list\service.js
import request from 'umi-request';

export async function queryFakeList(params) {
  return request('/api/fake_list', {
    params,
  });
}
```

```
// src\pages\list\basic-list\_mock.js
const user = [   '付小小', ];
function fakeList(count) {
  const list = [];
  for (let i = 0; i < count; i += 1) {
  }
  return list;
}
function getFakeList(req, res) {
  const params = req.query;
  const count = params.count * 1 || 20;
  const result = fakeList(count);
  sourceData = result;
  return res.json(result);
}
export default {
  'GET  /api/fake_list': getFakeList,
  'POST  /api/fake_list': postFakeList,
};
```

```
// src\pages\list\search\projects\_mock.js
export default {
  'GET  /api/fake_list': getFakeList,
};
// 返回的数据这里面的数据
```

### 🏞 期望结果

期望返回的是本目录下的_mock.js数据

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  4.1.x
- umi 版本 3.1.1
- 浏览器环境
- 开发环境 [e.g. mac OS] win10 1909 专业版 x64

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1888094/79309590-1de4a100-7f2d-11ea-9113-dcedc923f094.png)

![image](https://user-images.githubusercontent.com/1888094/79309972-bda22f00-7f2d-11ea-8e0f-2a29fa913f53.png)

![image](https://user-images.githubusercontent.com/1888094/79309003-28526b00-7f2c-11ea-9b09-88181020d79e.png)

**Comment by chenshuai2144** [comment]
mock 的规则是 match，后一个会覆盖前一个，这个是设计

**Comment by huaiguoguo** [comment]
> mock 的规则是 match，后一个会覆盖前一个，这个是设计

这个设计不合理或者算一个缺陷，我在本目录请求的肯定是本目录里面的_mock.js返回的数据
