### ISSUE TITLE
umi@3在加载umi-plugin-antd-theme后.scss的文件引入全部失效🐛[BUG]

### ISSUE THREAD

**Issue by avalonWx** [ant-design/ant-design-pro#6399]
### 🐛 bug 描述
umi3我想换成dark的黑色主题，在yarn add umi-plugin-antd-theme -D后，在使用了@umijs/plugin-sass和node-sass，组件中import './index.scss'全部未生效，但是也没有报错，有人遇到过同样的问题吗

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.1.2]
- umi 版本 [e.g. 3.1.1]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
umi-plugin-antd-theme 主题不支持 scss，只支持 less

**Comment by avalonWx** [comment]
不是不支持吧，是我组件中自己写的scss文件引入失效导致样式全部错乱了

**Comment by avalonWx** [comment]
并不是支持的问题，而是我自己写的scss文件在引入到组件中的时候失效，导致没有css样式，布局样式全部错乱了

**Comment by chenshuai2144** [comment]
Sass在umi 需要专门的插件来实现,我没用过 
你可以去社区里看看
