### ISSUE TITLE
项目安装问题

### ISSUE THREAD

**Issue by Erin-mm** [ant-design/ant-design-pro#6400]
mac电脑用yarn/npm create umi 创建项目过程中会产生一个.yo-repository的文件夹，然后提示安装目录不为空安装失败

**Comment by afc163** [comment]
@chenshuai2144 同类反馈太多了，去排查一下是哪一层出现了问题。

**Comment by chenshuai2144** [comment]
duo of  https://github.com/ant-design/ant-design-pro/issues/6363
