### ISSUE TITLE
Can't run unit test same as in the example docs

### ISSUE THREAD

**Issue by cddumanov** [ant-design/ant-design-pro#6401]
When I run my test I see the next:
![image](https://user-images.githubusercontent.com/43003794/79379919-535ab000-7f68-11ea-9c29-0820419b9f16.png)

Code of the test is pretty mush simple.

```
import React from 'react'
import { shallow } from 'enzyme';
import OrganizationSelect from './index';

it('renders Dashboard', () => {
  // Use the wrapped components
  const wrapper = shallow(<OrganizationSelect.WrappedComponent user={{ list: [] }} loading={{user: []}}/>);
  // const wrapper = shallow(<OrganizationSelect/>);
  expect(wrapper).toBe()
});
```

Code of the component

```
import React from 'react';
import { connect } from 'umi';
import { Select } from 'antd';
import styles from './index.less';

const { Option } = Select;

const OrganizationSelect = ({ dispatch, currentUser, loading, ...props }) => {
  const handleChange = async (code) => {
    await dispatch({
      type: 'user/setLastSelectedOrganization',
      payload: code,
    });
    await dispatch({
      type: 'user/fetchCurrent',
    });
  };
  if (!loading) {
    return (
      <Select
        className={styles.organizationSelect}
        defaultValue={
          currentUser.last_selected_organization
            ? currentUser.last_selected_organization.code
            : null
        }
        onChange={handleChange}
      >
        {currentUser.organizations.map(({ name, code }, i) => (
          <Option key={code} value={code}>
            {name}
          </Option>
        ))}
      </Select>
    );
  }
  return <></>;
};

export default connect(({ user, loading }) => ({
  currentUser: user.currentUser,
  loading: loading.models.user,
}))(OrganizationSelect);
```

How I can fix this error and make my test run? Can you help me, please? Many thanks for the answers in English!

**Comment by cddumanov** [comment]
@chenshuai2144 @afc163  Please help.

**Comment by zsxing99** [comment]
Having the same issue.

```
  ● Test suite failed to run

    TypeError: (0 , _umi.connect) is not a function

```

umi version:

```
"umi": "^3.2.3",
```

**Comment by zsxing99** [comment]
Update: no solution to this. Problem with umi dependency.

**Comment by y-lohse** [comment]
Ran into the same probleme, the issue was that umi is importing things from `@@/whatever` and jest doesn't know the `@@` alias.
Adding this in the jest configuration solved the problem:

```
moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@@/(.*)$': '<rootDir>/src/.umi/$1',
  },
```

**Comment by 1765659645** [comment]
@y-lohse 
Hello，I tested it according to your method. There is no problem in my local area, but after submitting to git, it will go through the unit test of Jenkins, but the code on git does not have a .umi directory, so there are other feasible methods Is it

**Comment by y-lohse** [comment]
I think the .umi directory is created when running the build command, so one possible workaround would be to build the project before running the tests?

**Comment by 1765659645** [comment]
@y-lohse 
ok，My current solution is to extract connect to another file
![image](https://user-images.githubusercontent.com/57136514/94254302-2bc93400-ff59-11ea-9702-06a1ddb857e2.png)

**Comment by Lubyam** [comment]
**_the same issue._**
Unhandled Rejection (TypeError): (0 , _umi.connect) is not a function
./src/layouts/BasicLayout.tsx
src/layouts/BasicLayout.tsx:174
>  171 |   );
  172 | };
  173 | 
 174 | export default connect(({ global, settings }: ConnectState) => ({
  175 |   collapsed: global.collapsed,
  176 |   settings,
  177 | }))(BasicLayout);
![image](https://user-images.githubusercontent.com/7630366/101235287-7823b380-3702-11eb-8536-ba63cede9f16.png)

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是它已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but it has not responded for a long time. We will temporarily close it
