### ISSUE TITLE
🐛[BUG]今日install 暗黑主题报错

### ISSUE THREAD

**Issue by ZhangXY-Magic** [ant-design/ant-design-pro#6402]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/25630228/79409433-85076180-7fd0-11ea-97b6-605806ec55e3.png)
@chenshuai2144

**Comment by chenshuai2144** [comment]
详细的错误原因？

**Comment by ZhangXY-Magic** [comment]
不清楚 什么原因 导致暗黑主题不生效 antd pro官网的暗黑主题也失效了 你可以看下

**Comment by ZhangXY-Magic** [comment]
yarn add @ant-design/dark-theme
仓库install下来的包里有error.log

**Comment by ZhangXY-Magic** [comment]
@chenshuai2144 大佬，有解决么

**Comment by ZhangXY-Magic** [comment]
> 详细的错误原因？

@chenshuai2144 大佬，有解决么

**Comment by lattemj** [comment]
解决了没？我也遇到同样问题

**Comment by ZhangXY-Magic** [comment]
> 解决了没？我也遇到同样问题

没有 两天了 没人管 @chenshuai2144 大佬也没回复

**Comment by FinchJohnRen** [comment]
> 不清楚 什么原因 导致暗黑主题不生效 antd pro官网的暗黑主题也失效了 你可以看下

就是 官网主题都没作用了 都没人解决吗

**Comment by ZhangXY-Magic** [comment]
可以先参考https://github.com/ant-design/ant-design/issues/23237#issuecomment-613290095， @FinchJohnRen @lattemj

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它


——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
