### ISSUE TITLE
使用umi-plugin-antd-theme 来切换主题问题

### ISSUE THREAD

**Issue by zhangpengfa666** [ant-design/ant-design-pro#6403]
在 "antd": "^3.16.1", ant design pro V2 , umiV2版本中使用该插件报错, 如何在当前版本使用该插件
![20200416113411](https://user-images.githubusercontent.com/43570454/79411747-3957b680-7fd6-11ea-9766-98213c84c966.png)
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个插件已经不支持antd@3了
