### ISSUE TITLE
🐛[BUG] @ant-design/icons are not treeshaked and all of them are added to the bundle

### ISSUE THREAD

**Issue by mxschmitt** [ant-design/ant-design-pro#6404]
### 🐛 bug 描述

`@ant-design/icons` are not treeshaked and by that all 1.26 MB are added to the bundle.

Related https://github.com/ant-design/ant-design/issues/12011

Feel free to transfer this issue to other Ant Design repositories.

### 📷 复现步骤

1. Clone the [Ant Design Pro repository](https://github.com/ant-design/ant-design-pro)
2. Install `webpack-bundle-analyzer` via NPM / Yarn
3. Add that to your config:

```
  chainWebpack: (config) => {
    const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
    config.plugin("BundleAnalyzerPlugin").use(BundleAnalyzerPlugin)
  },
```
4. Build the project

### 🏞 期望结果

Treeshaked Ant Icons, so not all of them are always loaded.
### © 版本信息

- Ant Design Pro 版本: 4.1.3
- umi 版本: 3.1.1
- 浏览器环境: Chrome 80
- 开发环境 macOS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17984549/79435525-13c7ae80-7fd0-11ea-8279-469410170afc.png)

**Comment by chenshuai2144** [comment]
you can use news prolayout plugins 
it only load used icons

**Comment by mxschmitt** [comment]
@chenshuai2144 which one exactly? I've used:
- `umi-plugin-antd-icon-config`
- `umi-plugin-antd-theme`
- `umi-plugin-pro`

all of them don't fix the issue that all icons were included in the bundle. I'm referring to the [official template](https://github.com/ant-design/ant-design-pro), where this issue is also persistent. Thats's why I'm so confused.
