### ISSUE TITLE
🐛[BUG] 在新建的空白文件夹里 yarn create umi 报错

### ISSUE THREAD

**Issue by darkengine** [ant-design/ant-design-pro#6410]
### 🐛 bug 描述

在新建的空白文件夹里运行 yarn create umi ，依次选择  ant-design-pro ，JavaScript， JavaScript， Yes 之后，报错

### 📷 复现步骤

1 运行 yarn create umi 
2 选择  ant-design-pro 
3 JavaScript
4 Yes

### 🏞 期望结果

可以正常初始化项目

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本: 最新版
- umi 版本
- 浏览器环境
- 开发环境  mac OS 10.14.6

### 🚑 其他信息

? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! Yes
fatal: destination path '/Users/xxx/Documents/projects/own/web' already exists and is not an empty directory.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 /Users/xxx/Documents/projects/own/web
null
null
    at makeError (/Users/xxx/.config/yarn/global/node_modules/execa/index.js:174:9)
    at /Users/xxx/.config/yarn/global/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AntDesignProGenerator.writing (/Users/xxx/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js:118:5)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/Users/xxx/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:791:20)
    at processImmediate (internal/timers.js:439:21) {
  code: 128,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'git clone https://gitee.com/ant-design/ant-design-pro --depth=1 /Users/xxx/Documents/projects/own/web',
  timedOut: false,
  killed: false
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments:
Directory: /Users/xxx/Documents/projects/own/web
Output:

**Comment by StKelen** [comment]
#6363 参考这个

**Comment by darkengine** [comment]
> #6363 参考这个

了解，已经解决，还是希望在文档里写清除吧。最终是 yarn create umi <your-project-name> 这样解决的。

**Comment by chenshuai2144** [comment]
dup of #6363
