### ISSUE TITLE
🧐[问题]官方预览界面的查询表格无法排序

### ISSUE THREAD

**Issue by morrle** [ant-design/ant-design-pro#6411]
### 🧐 问题描述

查询表格点击排序无反应，官方示例界面：https://preview.pro.ant.design/list/table-list

但是之前应该是可以的，如https://v2-preview-ant-design-pro.netlify.app/list/table-list

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/28941145/79538790-9bd4b380-80b7-11ea-842a-cd6ada1dbf56.png)

### 🏞 期望结果

点击排序后能正常排序

如https://v2-preview-ant-design-pro.netlify.app/list/table-list 中的效果

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 Google Chrome 版本 81.0.4044.92（正式版本） （64 位）
- 开发环境 [e.g. mac OS]

**Comment by hfpp2012** [comment]
因为 ProTable 不支持，不知现在修复了没有

**Comment by morrle** [comment]
pro-table已经修复了
