### ISSUE TITLE
🐛[BUG] await form.validateFields() 设置进useState后，useState的数据非实时数据

### ISSUE THREAD

**Issue by huaiguoguo** [ant-design/ant-design-pro#6412]
### 🐛 bug 描述

官方的page/list/table-list/component/UpdateForm.js文件里面的
handleNext函数是一个异步函数，在里面await form.validateFields() 获取表单数据后
用useState函数 setFormVals 后，向后台提交的数据(formVals)始终少了一步，不是时实数据

```
const UpdateForm = (props) => {
  const [formVals, setFormVals] = useState({
    name: props.values.name,
    desc: props.values.desc,
    key: props.values.key,
    target: '0',
    template: '0',
    type: '1',
    time: '',
    frequency: 'month',
  });
  const [currentStep, setCurrentStep] = useState(0);
  const [form] = Form.useForm();
  const {
    onSubmit: handleUpdate,
    onCancel: handleUpdateModalVisible,
    updateModalVisible,
    values,
  } = props;

  const forward = () => setCurrentStep(currentStep + 1);

  const backward = () => setCurrentStep(currentStep - 1);

  const handleNext = async () => {
    const fieldsValue = await form.validateFields();
    console.log(`这是原formValues:`, formVals);
    console.log(`这是表单的fieldValues: `, fieldsValue);
    setFormVals({ ...formVals, ...fieldsValue });

    //这里获取的formVals数据始终不是时实数据，是旧数据，始终少了一步数据;
    console.log(`这是合并过后的formValues: `, formVals);
    console.log(`=============================================`);
    // return false;

    if (currentStep < 2) {
      forward();
    } else {
      //这里获取的formVals数据始终不是时实数据，是旧数据，始终少了一步数据;
      // 可以实试一下，这里向后台提交的数据是旧数据;
      handleUpdate(formVals);
    }
  };
```

### 🏞 期望结果

斯望formVals获得的是最新时实数据

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.1.x
- umi 版本 3.1.1
- 浏览器环境
- 开发环境 [e.g. mac OS] win10 1909 x64 专业版

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1888094/79541096-cfb1d800-80bb-11ea-9d81-837544de94c6.png)

**Comment by huaiguoguo** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
setState 是异步的，也不会更改 const 变量，你要取需要这样取，
```
setTimeout(()=>{
const newValues = await form.validateFields()
},0)
```
你的代码写的很奇怪，思考一下是不是逻辑有问题

**Comment by huaiguoguo** [comment]
> setState 是异步的，也不会更改 const 变量，你要取需要这样取，
> 
> ```
> setTimeout(()=>{
> const newValues = await form.validateFields()
> },0)
> ```
> 
> 你的代码写的很奇怪，思考一下是不是逻辑有问题

这代码不是我写的，是你们官方的例子，我没有作任何改动
你可以跟着图片路径找一下文件，里面就是这么写的
yarn create umi myapp

**Comment by huaiguoguo** [comment]
> setState 是异步的，也不会更改 const 变量，你要取需要这样取，
> 
> ```
> setTimeout(()=>{
> const newValues = await form.validateFields()
> },0)
> ```
> 
> 你的代码写的很奇怪，思考一下是不是逻辑有问题

@chenshuai2144 

这个组当完全没有必要设置formVals这个useState,  只在初始化的时候用了一下formVals，
最后handleUpdate的时候用了一下，而且向handleUpdate传入的这个数据不是时实数据;

可以详细看一下：
src\pages\list\table-list\components\UpdateForm.jsx   第42行到51行之间
