### ISSUE TITLE
config.js里设置暗黑模式无效🧐[问题]

### ISSUE THREAD

**Issue by elfman** [ant-design/ant-design-pro#6415]
### 🧐 问题描述
新创建的antd pro项目，使用的umi3，想使用dark版本的antd，按照文档里说的在config.js里设置
```
export default defineConfig({
  hash: true,
  antd: {
    dark: true
  },
  ...
```
编译后没有任何效果

使用最新版本的`@ant-design/dark-theme`也没有任何效果，但修改为v1.0.3后有效，但旧版本并不好用，有些颜色没覆盖
请问这是什么原因？
OS：win10
node: v12.13.1
npm: 6.12.1

**Comment by whitedive** [comment]
不是应该在defaultSettings.ts修改吗     navTheme: 'dark',

**Comment by chenshuai2144** [comment]
antd有byg 等4.1.4发布就好了

**Comment by chenshuai2144** [comment]
已经发布
