### ISSUE TITLE
🐛[BUG]Form内容为空验证未通过，出现错误

### ISSUE THREAD

**Issue by leonkong** [ant-design/ant-design-pro#6416]
### 🐛 bug 描述
TS版脚手架空的Form提交出现错误
![image](https://user-images.githubusercontent.com/26429579/79573796-bfb4eb00-80f1-11ea-9de4-01ce662ac4c3.png)

### 📷 复现步骤
使用最新的npm create umi project_name创建脚手架
选择TS版，并选择complete。
npm install
npm run start
选择左侧列表页->查询表格进入http://localhost:8001/list/table-list
点击新建按钮，弹出Modal，任何东西不填直接点确定
出现错误
![image](https://user-images.githubusercontent.com/26429579/79573796-bfb4eb00-80f1-11ea-9de4-01ce662ac4c3.png)

### © 版本信息
最新版脚手架
"antd": "^4.0.0",
"react": "^16.8.6",
"@ant-design/pro-cli": "^1.0.18",
- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这是个warning，因为 formitem 没通过验证会 throw 一个错误，可以忽略掉
