### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by wangruiStart** [ant-design/ant-design-pro#6417]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/21194195/79638491-23a1e700-81b8-11ea-9a9b-d155a110e2e9.png)
配置如上路由，希望在menu中只显示课程菜单。menu显示正常。但点击跳转到新增或者编辑页时，路由和title都变了。但是加载的组件还是列表页的组件。
尝试着将课程的component隐藏之后，就可以正常匹配二级路由
![image](https://user-images.githubusercontent.com/21194195/79638544-81363380-81b8-11ea-9248-aa83354ae490.png)

**Comment by chenshuai2144** [comment]
所有的 children 配置都会作为 ，这个组建的
![image](https://user-images.githubusercontent.com/8186664/79678793-9307ed00-8231-11ea-9559-16168c9b94d1.png) 的 props.chidren 传入，如果要这么做，应该处理他的children，或者将其打平
