### ISSUE TITLE
🧐[问题] 某些页面没用任何ant pro的东西，可以不加载umi.css吗？还是我自己在ant pro建个react router

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#6419]
### 🧐 问题描述

如图
我这个就是纯react 组件页面，但是把umi.js全部加载出来了以及umi.css
test是用在 BlankLayout下面
 component: '../layouts/BlankLayout',
      routes: [
        {
          path: "/test",
          component: "./shareholder"
        },

![WechatIMG261](https://user-images.githubusercontent.com/19459174/79681788-7f6b7f00-824f-11ea-93e6-e94e558c3acd.jpeg)

**Comment by chenshuai2144** [comment]
不可能的， umi.css 是指你项目中任何的css
不是umi 给你注入的，antd 最后也会编译到 umi.css 中
