### ISSUE TITLE
今天刚clone下来的代码，cnpm安装怎么报这种错。。。

### ISSUE THREAD

**Issue by wdao7** [ant-design/ant-design-pro#642]
![a](https://user-images.githubusercontent.com/34474826/34727166-1223249a-f591-11e7-8713-425c0607194b.png)

**Comment by afc163** [comment]
应该是你的 node 环境有问题。

**Comment by chenshuai2144** [comment]
我记得有个一模一样的问题

**Comment by chenshuai2144** [comment]
#561 看看他的解决方案
