### ISSUE TITLE
🧐[问题] 用最新的umi3.x添加模板注册页和注册结果页，报错

### ISSUE THREAD

**Issue by su1329** [ant-design/ant-design-pro#6420]
### 🧐 问题描述

用最新的umi3.x添加模板注册页和注册结果页，报错
 warning  in ./src/pages/user/UserRegister/index.tsx

"export 'router' was not found in 'umi'

### 💻 浏览器提示
>
TypeError: Cannot read property 'push' of undefined
(anonymous function)
./src/pages/user/UserRegister/index.tsx:74
  71 | const account = form.getFieldValue('mail');
  72 | if (userAndUserRegister.status === 'ok') {
  73 |   message.success('注册成功！');
  74 |   router.push({
  75 |     pathname: '/user/register-result',
  76 |     state: {
  77 |       account,
View compiled
▶ 33 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13175074/79691768-e9a61300-8293-11ea-896a-1811345a767c.png)

**Comment by chenshuai2144** [comment]
试着使用一下 umi clean 已经改掉了，router 被废弃了，需要使用 history

**Comment by su1329** [comment]
解决了
