### ISSUE TITLE
🧐[问题]antdesign pro如何配置使用sass

### ISSUE THREAD

**Issue by dfhe** [ant-design/ant-design-pro#6421]
### 🧐 问题描述

antdesign pro如何配置使用sass

### 💻 示例代码

执行安装了 npm i --save node-sass sass-loader
使用时报错说没有loader，请问loader在哪里配置啊，在umi api上并没找到配置的地方
![image](https://user-images.githubusercontent.com/33407462/79717270-b606cf80-830b-11ea-93fb-993589131346.png)

**Comment by chenshuai2144** [comment]
看这里 
https://umijs.org/plugins/plugin-sass
