### ISSUE TITLE
🐛[BUG]手机浏览器访问官方预览站顶部右侧菜单在展开情况下切换路由后无法再通过点击展开

### ISSUE THREAD

**Issue by wanxger** [ant-design/ant-design-pro#6422]
### 🐛 bug 描述

手机浏览器访问官方预览站，顶部右侧菜单在展开情况下，切换路由后无法再通过点击展开。

### 📷 复现步骤

手机浏览器访问 https://preview.pro.ant.design/dashboard/workplace ，加载完成后点击右上角头像。当菜单显示后，在菜单显示的状态下，点击『进行中的项目』卡片右侧『全部项目』链接。待页面完成跳转后，点击右上角头像，此时菜单不会显示。

**Comment by chenshuai2144** [comment]
无法再现
