### ISSUE TITLE
👑 win10系统安装安装块内容的时候系统兼容性报错

### ISSUE THREAD

**Issue by itutopia** [ant-design/ant-design-pro#6423]
### 🥰 需求描述

👑 win10系统安装安装块内容的时候系统兼容性报错
 The operation was rejected by your operating system.

### 🚑 其他信息

npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\itutopia\Documents\vuedemo\ant-demo\node_modules\.staging\tinyqueue-0261a52c\index.d.ts
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\itutopia\Documents\vuedemo\ant-demo\node_modules\.staging\tinyqueue-0261a52c\index.d.ts'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\Users\itutopia\Documents\vuedemo\ant-demo\node_modules\.staging\tinyqueue-0261a52c\index.d.ts'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\Users\itutopia\Documents\vuedemo\ant-demo\node_modules\.staging\tinyqueue-0261a52c\index.d.ts'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\Users\\itutopia\\Documents\\vuedemo\\ant-demo\\node_modules\\.staging\\tinyqueue-0261a52c\\index.d.ts'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, unlink 'C:\\Users\\itutopia\\Documents\\vuedemo\\ant-demo\\node_modules\\.staging\\tinyqueue-0261a52c\\index.d.ts'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\itutopia\\Documents\\vuedemo\\ant-demo\\node_modules\\.staging\\tinyqueue-0261a52c\\index.d.ts',
npm ERR!   parent: 'ant-demo'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by chenshuai2144** [comment]
权限不足，把这个文件夹删除掉再安装就好了
