### ISSUE TITLE
🐛[BUG] 在一个页面上 用两个不同的TableForm，提交时只能得到一个TableForm的数据

### ISSUE THREAD

**Issue by hu272293309** [ant-design/ant-design-pro#6424]
### 🐛 bug 描述
在一个页面上 用两个不同的TableForm，提交时只能得到一个TableForm的数据

### 📷 复现步骤
```

<Form.Item name="carMaintenanceRecordServices">
              <ServicesTableForm readonly={false} calculate={this.handleTableChange} { ...this.tableServicesFormProps } />
            </Form.Item>
<Form.Item name="carMaintenanceRecordItems">
            <TableForm readonly={false} calculate={this.handleServicesTableChange} { ...this.tableFormProps } />
          </Form.Item>
```

### 🏞 期望结果

carMaintenanceRecordItems 和 carMaintenanceRecordServices都能取到数据

### © 版本信息

- Ant Design Pro 版本: last
- umi 版本 last
- 浏览器环境 Chrome
- 开发环境  mac OS

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它


——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
