### ISSUE TITLE
🧐[问题]config配置多个生产环境的问题

### ISSUE THREAD

**Issue by leonkong** [ant-design/ant-design-pro#6425]
### 🧐 问题描述
在ant design pro v2.x里，配置多个生产环境下的我是采用如下配置方法
假如有三个环境：个人开发dev环境，预上线stage环境，生产product环境，
个人开发dev环境  config.dev.js
 proxy: {
    '/admin/api': {
      target: 'http://localhost:9000/',
    },
  },
  define: {
    // 自定义配
    'process.env.meidaUrl': 'http://localhost:9000',
  },
...
预上线stage环境 config.stage.js
 proxy: {
    '/admin/api': {
      target: 'http://stage-api.mydomain/',
    },
  },
  define: {
    // 自定义配
    'process.env.meidaUrl': 'http://stage-meida.mydomain',
  },
...
生产product环境 config.product.js
 proxy: {
    '/admin/api': {
      target: 'http://api.mydomain.com/',
    },
  },
  define: {
    // 自定义配
    'process.env.meidaUrl': 'http://media.mydomain.com',
  },
...
package.json里的script有这三个对应
"start": "cross-env UMI_ENV=dev umi dev",
"build:stage": "cross-env UMI_ENV=stage umi build",
"build:product": "cross-env UMI_ENV=product umi build",
个人开发用npm run start启动本地webpack server，使用config.dev.js
预上线会使用 npm run build:stage编译静态文件 ，使用config.stage.js
生产环境使用 npm run build:product编译静态文件，使用config.product.js

antd pro v4把之前router.config.js的东西放到config.js里，因此不想使用之前v2的方式，
看到有个proxy.js，里面可以采用npm run start:XXX方式在dev模式下使用不同的target url。
那么有几个问题：
1、v4 里使用npm run build方式编译的生产环境下的静态页，到底怎么定义访问的target url？
proxy里定义的都是dev模式下使用的
2、像我之前build:stage和build:product两个生产环境需要指向不同线上后台地址，这个在v4里有没有好的处理方式？

**Comment by chenshuai2144** [comment]
静态页是跟着后端容器走的，前端应该是一模一样的
为了安全，不应该导入不同的 url。你要做的应该是配置的不同的容器，而不是在前端下功夫

**Comment by leonkong** [comment]
第一个问题你这个建议挺好，我就在nginx里配一下。不过有个问题没解决，就是不同环境下使用不同的内部变量，这个貌似还是没解决。比如stage和product里会访问一个资源地址，stage访问的是本地的，而product则需要访问七牛的。这个并不是通过services里 /api这样的方式，而是作为一个内部变量去使用的。这个有什么更规范的做法么？

**Comment by leonkong** [comment]
> 静态页是跟着后端容器走的，前端应该是一模一样的
> 为了安全，不应该导入不同的 url。你要做的应该是配置的不同的容器，而不是在前端下功夫

第一个问题你这个建议挺好，我就在nginx里配一下。不过有个问题没解决，就是不同环境下使用不同的内部变量，这个貌似还是没解决。比如stage和product里会访问一个资源地址，stage访问的是本地的，而product则需要访问七牛的。这个并不是通过services里 /api这样的方式，而是作为一个内部变量去使用的。这个有什么更规范的做法么？

**Comment by missfoxs** [comment]
同遇到这个问题，有什么解决方法吗
