### ISSUE TITLE
ant-design-pro 4.0之后要怎么生成动态的左侧菜单 和动态的权限

### ISSUE THREAD

**Issue by xjf348060793** [ant-design/ant-design-pro#6429]
菜单和权限全部由后台接口返回， 两个需求 ，菜单:  4.0之后找不到可以设置的地方，以前的layouts文件夹也移除了，权限： 文档有一句 “pro 现在这样从 config 中传值，也可以通过 http 请求从服务端获取，甚至本地的 json 文件加载也可以“  但是没有任何示例

**Comment by chenshuai2144** [comment]
https://umijs.org/plugins
可以看这个文档，这里是全新的 umi@3 架构使用的样式
