### ISSUE TITLE
unique "key" prop warning

### ISSUE THREAD

**Issue by C-Force** [ant-design/ant-design-pro#643]
<img width="1027" alt="screen shot on 2018-01-09 at 10_24_27" src="https://user-images.githubusercontent.com/4500005/34728244-62c5ad92-f527-11e7-881d-2f03ccf9f094.png">

When access 基础表单 and 分步表单 pages for the first time, two unique-key-prop warnings were given in the console.

**Comment by chenshuai2144** [comment]
安装新包就好了。这个问题今天好几个人问了

**Comment by pkaq** [comment]
@C-Force 把lock文件删掉重新clean install
