### ISSUE TITLE
🐛[BUG] 官方预览页挂掉了

### ISSUE THREAD

**Issue by yisbug** [ant-design/ant-design-pro#6430]
### 🐛 bug 描述

官方预览页挂掉了

### 📷 复现步骤

https://preview.pro.ant.design/exception/404

### 🏞 期望结果

https://preview.pro.ant.design/

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
清一下缓存，哪是因为 result 的 api 修改导致的，很久之前就修复了
