### ISSUE TITLE
🐛[BUG]RangePicker 组件中出现 '岁' 这个汉字

### ISSUE THREAD

**Issue by bushadie** [ant-design/ant-design-pro#6432]
### 🐛 bug 描述

RangePicker 组件中出现  '岁' 这个汉字

### 📷 复现步骤

浏览器 chrome 版本 81.0.4044.113（正式版本） （64 位）
    "@ant-design/icons": "^4.0.6",
    "@ant-design/pro-layout": "^5.0.9",
    "@ant-design/pro-table": "^2.2.2",
    "@antv/data-set": "^0.11.4",
    "antd": "^4.1.3",

### 💻 复现代码

`          
<RangePicker showTime
                       format="YYYY-MM-DD HH:mm"
                       minuteStep={5}
        />
`

### © 版本信息

浏览器 chrome 版本 81.0.4044.113（正式版本） （64 位）
    "@ant-design/icons": "^4.0.6",
    "@ant-design/pro-layout": "^5.0.9",
    "@ant-design/pro-table": "^2.2.2",
    "@antv/data-set": "^0.11.4",
    "antd": "^4.1.3",

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/28383091/79833494-08b0bc00-83de-11ea-87a8-e9f70b97601c.png)

**Comment by joesdu** [comment]
😂18岁

**Comment by chenshuai2144** [comment]
你打开了 google 的自动翻译了吧，打开之后 react 经常会出诡异的问题
