### ISSUE TITLE
🧐[问题]希望通过 utils/request.ts 给 headers 加上 Authorization Bearer 作为用户校验

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6433]
### 🧐 问题描述

项目使用 eggjs 作为后端，使用 jwt 方式作为用户连接，希望在每次请求时加上 Authorization Bearer，目前可以通过 utils/request.ts 在 extend({..., headers: { Authorization: `Bearer ${getToken()}` } })
加上 token，但是目前碰到一个问题，就是当用户登录后，得到新的 token，通过 setToken 写入 localStorage，可是 在请求时，以后发送的是原来的 token，请教我改怎么办？ （登录成功后不想刷新页面）

### 💻 示例代码

```
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'omit', // include 默认请求是否带上cookie
  headers: {
    Authorization: `Bearer ${getToken()}`
  }
});
```

**Comment by joesdu** [comment]
拦截器了解下

**Comment by zhangbc** [comment]
getToken() 是怎么写的？

**Comment by 510846** [comment]
> getToken() 是怎么写的？



> 拦截器了解下

嗯，以前用 axios 也是通过拦截器 request 上加的 header，可是这个 and design pro 中用的是 umi-request，然后在 utils/request.ts 中是通过 extend 来扩展，看了里面的参数没有拦截器相关的参数，因为我是 TS 初学者，不知道该如何去改造这个 utils/request.ts ，望指点，谢谢！

**Comment by 510846** [comment]
> getToken() 是怎么写的？

就简单放到了一个 token.ts 文件中，

```
export function getToken() {
  return localStorage.getItem('token');
}
export function setToken(token: string): void {
  localStorage.setItem('token', token);
}
```

**Comment by huntdream** [comment]
可以看下文档，https://github.com/umijs/umi-request

**Comment by huntdream** [comment]
可以看下文档，https://github.com/umijs/umi-request

**Comment by 510846** [comment]
> 可以看下文档，https://github.com/umijs/umi-request

搞定了，谢谢！`request.interceptors.request`

**Comment by 510846** [comment]
> 拦截器了解下

感谢，搞定了！ `request.interceptors.request`

**Comment by joesdu** [comment]
> > 拦截器了解下
> 
> 感谢，搞定了！ `request.interceptors.request`

![image](https://user-images.githubusercontent.com/13188169/79936671-9fd34d80-848a-11ea-8ad2-bc3f0a7ad75e.png)

若是使用Umi3.x建议调整成这样,去掉request文件.

**Comment by hfpp2012** [comment]
看我这个

``` typescript
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'same-origin', // 默认请求是否带上cookie
  prefix: `${DOMAIN}/api`,
  headers: {
    Authorization: `Bearer ${localStorage.getItem('token')}`,
  },
});

const myRequest = (url: string, options: RequestOptionsInit | undefined = {}) => {
  return request(url, {
    ...options,
    headers: {
      ...options!.headers,
      Authorization: `Bearer ${localStorage.getItem('token')}`,
    },
  });
};

export default myRequest;
```

完整文件：https://github.com/hfpp2012/hello-antd-role/blob/master/clientv4/src/utils/request.ts

**Comment by lynxkor** [comment]
`
request.interceptors.request
  .use(async (url, options) => {
    /**
     * GET TOKEN
     */
    const token = getAuthToken();
    if (token) {
      return ({
        url: url,
        options: {
          ...options,
          headers: {
            Authorization: `Bearer ${token}`,
          }
        }
      })
    }
    else {
      return ({
        url: url,
        options: { ...options }
      });
    }
  });`

**Comment by 510846** [comment]
> 这样,去掉req

谢谢，迟点试试看 ~

**Comment by zhangbc** [comment]
获取后台API的token：

```tpyescript
// @ts-ignore
request.interceptors.request.use((url, options) => {
  let headers;
  if (localStorage.getItem('authorization')) {
    headers = {'authorization': localStorage.getItem('authorization')};
  } else {
    headers = {'authorization': ' '};
  }
  return (
    {
      url,
      options: {...options, headers},
    }
  );
});

request.interceptors.response.use((response) => {
  if (response.headers.get("authorization")) {
    localStorage.setItem("authorization", <string>response.headers.get("authorization"));
  }
  return response;
});
```

参考博文：[umi-request 获取 headers](https://blog.csdn.net/qq_38025939/article/details/105506378)
