### ISSUE TITLE
 Layout 全新样式

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#6434]
随着 antd 正式版的发布，layout 也将迎来全新的设计风格。新的风格仍然会以科技的风格为主，在原来的基础上优化尺寸和体验细节，设计更加简洁，匹配更多业务场景。

## AntDesign Pro  主要修改点

| 内容 | 修改点 |
| --- | --- |
| 导航尺寸 | 顶部导航高度由  AntDesign Pro 64px 改为 48px- 侧边导航宽度由 AntDesign Pro 256px 改为 208px |
| 导航布局模式 | 在原来单一侧边或顶部导航模式基础上，增加一种混合模式，与 TechUI 现有模式统一 |
| 顶部导航细节优化 | 全局搜索样式修改，与顶部菜单交互修改，打开搜索挤压菜单后，关闭搜索回到正常态- 实用工具区 Hover 颜色修改，由蓝色改为深黑色 #161726 |
| 侧边导航细节优化 | 在侧边导航增加自定义辅助功能操作，如下拉筛选- 侧边导航展开收起图标修改，放置在侧边导航底部- 增加菜单名过长，菜单高度小信息隐藏交互 默认修改为固定模式 |
| 混合模式 | 顶部导航提供自定义顶部导航与原来一致，但是增加一个通透的顶栏 |

### 结构与尺寸

侧边导航宽度由  256px 改为 208px，导航内容与前后边距改为 16px

![image.png](https://gw.alipayobjects.com/zos/antfincdn/sEHoMffUP%26/1586503920221-16d9c22e-1373-40c9-8d08-e6edf5c68ee2.png)

### 自定义辅助操作

增加自定义辅助操作，如下拉筛选（业务诉求）

![image.png](https://gw.alipayobjects.com/zos/antfincdn/gScRFjhdce/1586503972482-1f62c5ec-e6ce-478f-a7c6-2362d7c888f1.png)

### 菜单过长过多交互

菜单名过长，缩略展示，hover 出现全部 tooltip 提示。

![image.png](https://gw.alipayobjects.com/zos/antfincdn/4gtxYL3HP8/1586505237583-656e788e-d9d0-4d14-9278-dac102b9edd0.png)

菜单名过多或出现折叠时，顶部标题产品标题区，辅助操作区和底部通用操作区固定，中间功能菜单区进行滑动。上下区域出现阴影分割。

## 顶部导航交互部分

交互和导航的改动是本次最大的改变。

### 结构与尺寸

顶部导航高度由 64px 改为 48px

![image.png](https://gw.alipayobjects.com/zos/antfincdn/UtfyUhUaSV/1586502220305-25adb29e-5609-4eda-b4c4-ca117ec52580.png)

### 颜色版本

继续提供暗色、亮白颜色版本，暗色颜色由 `#001529` 改为金融云导航（OneX）同样深色 `#1F293D`

![image.png](https://gw.alipayobjects.com/zos/antfincdn/BnkRy%26WUJ9/1586502256521-88d3b504-de75-4ac0-a7c9-d6cd15bcae99%252520%281%29.png)

### 搜索交互优化

搜索激活样式修改，打开搜索挤压菜单后，关闭搜索回到正常态

![image.png](https://gw.alipayobjects.com/zos/antfincdn/0Xx9XYePgQ/1586503735289-59c77d00-2428-49a8-9bd2-d47330e2831c%252520%281%29.png)

### 实用工具 Hover 效果优化

实用工具 Hover 由蓝色背景色改为深黑色 `#161726`

![image.png](https://gw.alipayobjects.com/zos/antfincdn/dvccJS41Tl/1586503854420-8236a5b9-66da-48a7-9f58-ea5c40a3b479.png)

## 混合菜单新模式

顶部全局导航+侧边导航混合模式，支持 Ant Design Pro 已有导航模式切换到此模式。

![image.png](https://gw.alipayobjects.com/zos/antfincdn/HSeAGqaEwn/1586504755352-479bf47d-97a6-4080-afed-d38ffe905e57.png)

### 样例

![image.png](https://gw.alipayobjects.com/zos/antfincdn/1r4WQhweas/1586964514728-bdca9455-e887-4c94-8091-30cf008937c8.png)

**Comment by joesdu** [comment]
👍

**Comment by zhfish** [comment]
multitab，永恒的话题。。说实话，阿里云那样的侧开抽屉，太丑了

**Comment by kaoding** [comment]
新的 layout，什么地方可以看到？

**Comment by admiao** [comment]
> multitab，永恒的话题。。说实话，阿里云那样的侧开抽屉，太丑了
丑而且操作起来还差

**Comment by chenshuai2144** [comment]
@zhfish  umi 支持keep live 之后 multitab 可以被提上日常了

**Comment by zhfish** [comment]
> @zhfish umi 支持keep live 之后 multitab 可以被提上日常了

我觉得umi很难用现有方案支持，都不太完美
还是要看react的。。
考虑用vue3撸一套antd-pro

**Comment by hihuangwei** [comment]
期待早点发布

**Comment by snakeUni** [comment]
@zhfish multitab 是什么样子的呀。

**Comment by wulibaibao** [comment]
怎么给导航栏、菜单栏增加样式，比如菜单栏我想给菜单上面放个头像，把导航的头像删掉

**Comment by duwei54** [comment]
赞一个哈

**Comment by kaoding** [comment]
侧边栏、顶部栏 和 PageContainer 如果都是同一个theme（如： navTheme: 'light'），看不出明显的分割感，应该要体显一点分割感（如加线条、阴影之类的）才看好。

**Comment by kaoding** [comment]
可以将 navTheme: 'light'、’dark' 和 layout: 'mix'、‘side’、‘top’ 让设计再看一看，微调一下样式。

**Comment by kaoding** [comment]
> 侧边栏、顶部栏 和 PageContainer 如果都是同一个theme（如： navTheme: 'light'），看不出明显的分割感，应该要体显一点分割感（如加线条、阴影之类的）才看好。

需要将 fixSiderbar: true, 就会出来层次感。

**Comment by zoeykk** [comment]
我想设置layout中content部分的marin值，比如设置为8 怎么设置？ 我看配置里只有disableContentMargin，设置true就是24 否则就没有

**Comment by joesdu** [comment]
> 我想设置layout中content部分的marin值，比如设置为8 怎么设置？ 我看配置里只有disableContentMargin，设置true就是24 否则就没有

在里边写个className绑个样式就好了.

**Comment by rudyzou** [comment]
![image](https://user-images.githubusercontent.com/4281891/83964197-de5b8500-a8dd-11ea-88ed-3b3a1fdb5153.png)

**Comment by X-neuron** [comment]
> keep-alive 我打算用 https://www.npmjs.com/package/react-keep-alive 试试

可以试试这个： 0框架的 mutiTab 纯原生 纯hook，可动态json的路由 https://github.com/X-neuron/antdFront.git

**Comment by joesdu** [comment]
> ![image](https://user-images.githubusercontent.com/4281891/83964197-de5b8500-a8dd-11ea-88ed-3b3a1fdb5153.png)
> 瞅瞅multitab
> keep-alive 我打算用 https://www.npmjs.com/package/react-keep-alive 试试

你这个标签怎么玩的

**Comment by X-neuron** [comment]
> 你这个标签怎么玩的，纯原生的组件，这么玩~
 https://github.com/X-neuron/antdFront.git

**Comment by joesdu** [comment]
> > 你这个标签怎么玩的，纯原生的组件，这么玩~
> > https://github.com/X-neuron/antdFront.git

感谢

**Comment by realcyma** [comment]
![image](https://user-images.githubusercontent.com/32567610/84468673-fd795e80-acb1-11ea-9659-783dadac0d9c.png)

1. 語言選擇的icon不見了.  color不對, 是黑色.  所以, black in black 看不見.
2. logo重複出現, 在header和side menu 都有.

**Comment by rudyzou** [comment]
> > ![image](https://user-images.githubusercontent.com/4281891/83964197-de5b8500-a8dd-11ea-88ed-3b3a1fdb5153.png)
> > 瞅瞅multitab
> > keep-alive 我打算用 https://www.npmjs.com/package/react-keep-alive 试试
> 
> 你这个标签怎么玩的

有时间整个开源框架出来，还有很多细节问题需要开源力量支持

**Comment by li515422618** [comment]
跪求pro v5的开发大佬，能不能给加个多tab页打开的能力呀，急需，另外就是v5的layout的mix模式非常实用，期望能早点开源出来，现在正在用v4开发了真蛋疼啊，趁着功能还开发的不多，5出来我就直接重写了。

**Comment by joesdu** [comment]
> 跪求pro v5的开发大佬，能不能给加个多tab页打开的能力呀，急需，另外就是v5的layout的mix模式非常实用，期望能早点开源出来，现在正在用v4开发了真蛋疼啊，趁着功能还开发的不多，5出来我就直接重写了。

我都升级V5好一个多月了

**Comment by li515422618** [comment]
> > 跪求pro v5的开发大佬，能不能给加个多tab页打开的能力呀，急需，另外就是v5的layout的mix模式非常实用，期望能早点开源出来，现在正在用v4开发了真蛋疼啊，趁着功能还开发的不多，5出来我就直接重写了。
> 
> 我都升级V5好一个多月了

刚才翻了翻我也找到v5的代码了，刚跑起来demo，看了下beta版的文档，看了看代码，不知道怎么搞动态菜单，之前用4实现了一版，这俩区别还挺大，大佬有啥经验分享么

**Comment by joesdu** [comment]
> > > 跪求pro v5的开发大佬，能不能给加个多tab页打开的能力呀，急需，另外就是v5的layout的mix模式非常实用，期望能早点开源出来，现在正在用v4开发了真蛋疼啊，趁着功能还开发的不多，5出来我就直接重写了。
> > 
> > 
> > 我都升级V5好一个多月了
> 
> 刚才翻了翻我也找到v5的代码了，刚跑起来demo，看了下beta版的文档，看了看代码，不知道怎么搞动态菜单，之前用4实现了一版，这俩区别还挺大，大佬有啥经验分享么

V5动态路由我也不会.官方大佬也没给我说要怎么搞.

**Comment by chenshuai2144** [comment]
用menuDataRender 可以很快的实现的

**Comment by joesdu** [comment]
> 用menuDataRender 可以很快的实现的

我今天摸索出来了🤣🤣😂

**Comment by hikitty2** [comment]
> ![image](https://user-images.githubusercontent.com/32567610/84468673-fd795e80-acb1-11ea-9659-783dadac0d9c.png)
> 
> 1. 語言選擇的icon不見了.  color不對, 是黑色.  所以, black in black 看不見.
> 2. logo重複出現, 在header和side menu 都有.
·

> ![image](https://user-images.githubusercontent.com/32567610/84468673-fd795e80-acb1-11ea-9659-783dadac0d9c.png)
> 
> 1. 語言選擇的icon不見了.  color不對, 是黑色.  所以, black in black 看不見.
> 2. logo重複出現, 在header和side menu 都有.

你好 这个demo是怎么起的呢 我跑起来是空白的

**Comment by hikitty2** [comment]
本地demo 怎么起的呢  我起的是空白的

**Comment by chendonghai1982** [comment]
> 跪求pro v5的开发大佬，能不能给加个多tab页打开的能力呀，急需，另外就是v5的layout的mix模式非常实用，期望能早点开源出来，现在正在用v4开发了真蛋疼啊，趁着功能还开发的不多，5出来我就直接重写了。

能不能给加个多tab页打开的能力，这个功能我也非常想要。

**Comment by X-neuron** [comment]
> 能不能给加个多tab页打开的能力，这个功能我也非常想要。
https://github.com/X-neuron/antdFront.git  你的原生参考~

**Comment by effapp** [comment]
> > 用menuDataRender 可以很快的实现的
> 
> 我今天摸索出来了🤣🤣😂

能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？

**Comment by joesdu** [comment]
> > > 用menuDataRender 可以很快的实现的
> > 
> > 我今天摸索出来了🤣🤣😂
> 
> 能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？

可以参考5.1的源码去实现服务端加载菜单，5.1中有大佬写了个样列

**Comment by effapp** [comment]
> > > > 用menuDataRender 可以很快的实现的
> > > 
> > > 
> > > 我今天摸索出来了🤣🤣😂
> > 
> > 
> > 能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？
> 
> 可以参考5.1的源码去实现服务端加载菜单，5.1中有大佬写了个样列

5.1中有大佬写的样例在哪里？我没有找到

**Comment by joesdu** [comment]
> > > > > 用menuDataRender 可以很快的实现的
> > > > 
> > > > 
> > > > 我今天摸索出来了🤣🤣😂
> > > 
> > > 
> > > 能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？
> > 
> > 
> > 可以参考5.1的源码去实现服务端加载菜单，5.1中有大佬写了个样列
> 
> 5.1中有大佬写的样例在哪里？我没有找到

[v5.1 (#6758)](https://github.com/ant-design/ant-design-pro/commit/195fd79f602f5e6b9b6c72580a293cea19ddf27d)

**Comment by effapp** [comment]
> > > > > > 用menuDataRender 可以很快的实现的
> > > > > 
> > > > > 
> > > > > 我今天摸索出来了🤣🤣😂
> > > > 
> > > > 
> > > > 能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？
> > > 
> > > 
> > > 可以参考5.1的源码去实现服务端加载菜单，5.1中有大佬写了个样列
> > 
> > 
> > 5.1中有大佬写的样例在哪里？我没有找到
> 
> [v5.1 (#6758)](https://github.com/ant-design/ant-design-pro/commit/195fd79f602f5e6b9b6c72580a293cea19ddf27d)

您好，请问在renderMenuData: (localMenu, serverMenu) => { 中，serverMenu的数据来自哪里？如果异步从服务器取数据，会出现菜单loading的提示吗？类似下面的：
![image](https://user-images.githubusercontent.com/51013754/87740323-7d946600-c814-11ea-9d32-3fb4d45a087c.png)

**Comment by liz-zhang** [comment]
请问 要怎么给不同的页面配置不同 的layout

**Comment by ztedu** [comment]
> > > > > > > 用menuDataRender 可以很快的实现的
> > > > > > 
> > > > > > 
> > > > > > 我今天摸索出来了🤣🤣😂
> > > > > 
> > > > > 
> > > > > 能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？
> > > > 
> > > > 
> > > > 可以参考5.1的源码去实现服务端加载菜单，5.1中有大佬写了个样列
> > > 
> > > 
> > > 5.1中有大佬写的样例在哪里？我没有找到
> > 
> > 
> > [v5.1 (#6758)](https://github.com/ant-design/ant-design-pro/commit/195fd79f602f5e6b9b6c72580a293cea19ddf27d)
> 
> 您好，请问在renderMenuData: (localMenu, serverMenu) => { 中，serverMenu的数据来自哪里？如果异步从服务器取数据，会出现菜单loading的提示吗？类似下面的：
> ![image](https://user-images.githubusercontent.com/51013754/87740323-7d946600-c814-11ea-9d32-3fb4d45a087c.png)

你好，请问serverMenu来自哪里，你弄明白了吗？

**Comment by fangniu** [comment]
> > > > > > > > 用menuDataRender 可以很快的实现的
> > > > > > > 
> > > > > > > 
> > > > > > > 我今天摸索出来了🤣🤣😂
> > > > > > 
> > > > > > 
> > > > > > 能说说是摸索的结果吗？是不是要自定义layout？menuDataRender的代码加在哪里？
> > > > > 
> > > > > 
> > > > > 可以参考5.1的源码去实现服务端加载菜单，5.1中有大佬写了个样列
> > > > 
> > > > 
> > > > 5.1中有大佬写的样例在哪里？我没有找到
> > > 
> > > 
> > > [v5.1 (#6758)](https://github.com/ant-design/ant-design-pro/commit/195fd79f602f5e6b9b6c72580a293cea19ddf27d)
> > 
> > 
> > 您好，请问在renderMenuData: (localMenu, serverMenu) => { 中，serverMenu的数据来自哪里？如果异步从服务器取数据，会出现菜单loading的提示吗？类似下面的：
> > ![image](https://user-images.githubusercontent.com/51013754/87740323-7d946600-c814-11ea-9d32-3fb4d45a087c.png)
> 
> 你好，请问serverMenu来自哪里，你弄明白了吗？

同问啊

**Comment by blinkMyEyesConsciously** [comment]
@chenshuai2144  我想问一下怎么切换到混合模式 我找了很久没有发现哪里能够切换.

**Comment by realcyma** [comment]
> @chenshuai2144 我想问一下怎么切换到混合模式 我找了很久没有发现哪里能够切换.

config/defaultSetting  入面, layout: 'mix'

**Comment by blinkMyEyesConsciously** [comment]
@rudyzou  非常感谢你的回复  但是我现在defaultSetting中的layout: 'mix' 跟你说的一样; 但是他的一级菜单栏还是在左侧

**Comment by realcyma** [comment]
> @rudyzou 非常感谢你的回复 但是我现在defaultSetting中的layout: 'mix' 跟你说的一样; 但是他的一级菜单栏还是在左侧

不太明白, 來一個screen capture 可以嗎?

**Comment by blinkMyEyesConsciously** [comment]
![image](https://user-images.githubusercontent.com/38968979/93037312-b4e88d00-f674-11ea-91ef-e69190d9dd8b.png)

这个 这是defaultSetting  我虽然有defaultSetting  但是我不明白  pro到底有没有引用  layout: 'mix',
因为我在config.ts里面只看到他引用了primaryColor ;  pro会寻找defaultSettings.ts 里面的设置吗
![image](https://user-images.githubusercontent.com/38968979/93037342-ca5db700-f674-11ea-9bb2-133c99f2edc5.png)
@realcyma

**Comment by liujiayii** [comment]
> ![image](https://user-images.githubusercontent.com/38968979/93037312-b4e88d00-f674-11ea-91ef-e69190d9dd8b.png)
> 
> 这个 这是defaultSetting 我虽然有defaultSetting 但是我不明白 pro到底有没有引用 layout: 'mix',
> 因为我在config.ts里面只看到他引用了primaryColor ; pro会寻找defaultSettings.ts 里面的设置吗
> ![image](https://user-images.githubusercontent.com/38968979/93037342-ca5db700-f674-11ea-9bb2-133c99f2edc5.png)
> @realcyma
https://procomponents.ant.design/docs/getting-started-layout#%E8%87%AA%E5%8A%A8%E5%88%87%E5%89%B2%E8%8F%9C%E5%8D%95 文档虽然不健全 但是都有提到，

**Comment by joesdu** [comment]
> > ![image](https://user-images.githubusercontent.com/38968979/93037312-b4e88d00-f674-11ea-91ef-e69190d9dd8b.png)
> > 这个 这是defaultSetting 我虽然有defaultSetting 但是我不明白 pro到底有没有引用 layout: 'mix',
> > 因为我在config.ts里面只看到他引用了primaryColor ; pro会寻找defaultSettings.ts 里面的设置吗
> > ![image](https://user-images.githubusercontent.com/38968979/93037342-ca5db700-f674-11ea-9bb2-133c99f2edc5.png)
> > @realcyma
> > https://procomponents.ant.design/docs/getting-started-layout#%E8%87%AA%E5%8A%A8%E5%88%87%E5%89%B2%E8%8F%9C%E5%8D%95 文档虽然不健全 但是都有提到，

大佬.我开始做后端了.🤣

**Comment by luzhaoren** [comment]
> @zhfish umi 支持keep live 之后 multitab 可以被提上日常了

恳求大佬下个版本一定实现这个multitab，苦苦期盼N久了，大佬牛逼，大佬快乐一整天，哈哈

**Comment by codedart2018** [comment]
> ![image](https://user-images.githubusercontent.com/4281891/83964197-de5b8500-a8dd-11ea-88ed-3b3a1fdb5153.png)
> 瞅瞅multitab
> keep-alive 我打算用 https://www.npmjs.com/package/react-keep-alive 试试

请问顶部菜单如何和左侧边栏菜单联动的

**Comment by edifangyi** [comment]
样例我怎么没找到在哪里呢？

**Comment by edifangyi** [comment]
样例我怎么没找到在哪里呢？
