### ISSUE TITLE
🧐[问题]v4版本是否还支持chrome的Redux DevTools?

### ISSUE THREAD

**Issue by GloriaCHL** [ant-design/ant-design-pro#6438]
### 🧐 问题描述

新初始化的 v4 版本，选择 umi@3，初始化完成后运行 `yarn start` 发现用不了 chrome 的 Redux DevTools。请问是有什么其他调试 redux 的方案还是不再做 redux 调试的支持？

**Comment by GloriaCHL** [comment]
自己新加个model到项目里就打开了。是检测到项目里有使用model后自动打开的样子

**Comment by chenshuai2144** [comment]
umi@3 架构没有使用 redux了，我们使用了全新的数据流框架。

https://umijs.org/plugins/plugin-model
