### ISSUE TITLE
关于列表页搜索结果，前进后退的问题

### ISSUE THREAD

**Issue by superkoh** [ant-design/ant-design-pro#644]
期望这样一种场景：
在一个查询表格进行搜索，对搜索结构中的某一项编辑，编辑是跳转新页面的，希望跳转过去后，点击浏览的返回按钮恢复到之前的搜索结果

现在的情况：
如果挑出当前列表，后退回来，搜索query就清空了

原来老版本antd下，我搜索都是通过reduxRouter.push里把query带上，每次搜索都刷新当前页面来进行的。但是现在会报不能push到同一个页面。。。

所以pro里要做到上面的场景，要如何处理？

**Comment by chenshuai2144** [comment]
参数保存在redux里面就好了

**Comment by afc163** [comment]
https://reacttraining.com/react-router/web/api/Link/replace-bool

**Comment by Sayi** [comment]
@chenshuai2144  貌似HashHistory不支持这样传query条件。
我是把查询条件带入了详情页，然后详情页返回到列表页再把条件带回去赋值到搜索框，然后到服务端根据条件拉取数据。
```
Browser Console报警告
Warning: Hash history cannot push state; it is ignored
```
代码如下：
```
this.props.dispatch(routerRedux.push(`/gods/app/detail/${id}`, query));
其中query是查询条件的json数据
```

**Comment by chenshuai2144** [comment]
We only support the state argument when using browser/memory history, not hash.

**Comment by Sayi** [comment]
是的，我搜到这个警告了。

所以 **“列表页 进入 详情页 再返回列表页，查询条件该如何保存且传递呢？？？”**

业务经常有翻页一条条数据处理，所以返回肯定希望查询条件存在。

**Comment by chenshuai2144** [comment]
放在redux里面把

**Comment by Sayi** [comment]
@chenshuai2144 
谢谢了，前端的技术栈太多了，已经找到了写法。

**Comment by chenshuai2144** [comment]
分享一下吧

**Comment by mutouzdl** [comment]
@Sayi 我也遇到这个疑问，请问你的解决方案是什么呢？我目前是保存到redux里，但是因为页面比较复杂，会有一些冲突。能分析一下你的方案吗？

**Comment by Sayi** [comment]
我还没有深度尝试，但是通过
“reduxRouter.push里把query带上”
我发现可以传递数据，应该能满足我的需求了。
