### ISSUE TITLE
create umi 之后获得了移除layout的版本🧐[问题]

### ISSUE THREAD

**Issue by fatesq** [ant-design/ant-design-pro#6440]
### 🧐 问题描述
这个版本和官网的使用说明不太一样，例如自定义菜单和自定义的layout等应该如何配置。

**Comment by chenshuai2144** [comment]
文档还在准备，这个是抢先版本的 pro 

https://umijs.org/plugins/preset-react，可以看这里

**Comment by pengzj** [comment]
@chenshuai2144， 你好，看了文档 https://umijs.org/zh-CN/plugins/plugin-layout， 就是觉得layout设定的太死板了，能否自定义layout替代默认的呢？

**Comment by chenshuai2144** [comment]
关掉这个插件好了，就可以用原来的了
这个插件就是为了死板

**Comment by Tenodec** [comment]
@chenshuai2144  文档没出来，项目接口先出来了。还以为我创建错误。。。
