### ISSUE TITLE
🧐[问题]切换页面时，怎么让modle中的state重置呢？或者让页面强制刷新？

### ISSUE THREAD

**Issue by SuperEffort** [ant-design/ant-design-pro#6441]
### 🧐 问题描述
切换页面时，怎么让modle中的state重置呢？或者让页面强制刷新？

在菜单中切换页面后，页面不会强制刷新，返回之后modle中state还是上次修改的状态

**Comment by joesdu** [comment]
使用dispatch调用一下model中的reducers.在reducers函数中清除model的state数据.例如:
    cleanRegion(state): ProjectsModelState {
      return { ...state, regionList: [] };
    }

**Comment by chenshuai2144** [comment]
@joesdu  可以注意一下文档格式，效果会更好

**Comment by joesdu** [comment]
> @joesdu  可以注意一下文档格式，效果会更好

😁好的

**Comment by SuperEffort** [comment]
> 使用dispatch调用一下model中的reducers.在reducers函数中清除model的state数据.例如:
> 
> ```
>     cleanRegion(state): ProjectsModelState {
>       return { ...state, regionList: [] };
>     }
> ```

感谢你的回复，除了这方法还有其他解决方案吗

**Comment by joesdu** [comment]
> > 使用dispatch调用一下model中的reducers.在reducers函数中清除model的state数据.例如:
> > ```
> >     cleanRegion(state): ProjectsModelState {
> >       return { ...state, regionList: [] };
> >     }
> > ```
> 
> 感谢你的回复，除了这方法还有其他解决方案吗
目前我都是这么写的.其他方法的话,好像没有看到demo
