### ISSUE TITLE
🐛[BUG]路由权限，父页面有权限，其中某个子页面有权限，在浏览器中可以跳转到其他无权限的子页面

### ISSUE THREAD

**Issue by tigerxiongj** [ant-design/ant-design-pro#6442]
出错的函数

export const getAuthorityFromRouter = (router = [], pathname) => {
//这是以前的函数实现，这段代码有问题，如果子页面有权限，实际返回的是父页面的权限
  // const authority = router.find(
  //   ({ routes, path = '/' }) =>
  //     (path && pathRegexp(path).exec(pathname)) ||
  //     (routes && getAuthorityFromRouter(routes, pathname)),
  // );

//下面的部分是修改的，
  for (let r of router) {
    let {routes, path = '/'} = r;
    if (path && pathRegexp(path).exec(pathname)) {
      return r;
    }
    if (routes) {
      let authority = getAuthorityFromRouter(routes, pathname);
      if (authority) {
        return authority;
      }
    }
  }

  return undefined;
};

**Comment by chenshuai2144** [comment]
fixed in 4.1
