### ISSUE TITLE
🧐[问题] v4 根路径的页面是否默认带pro-layout？有没有办法去掉？

### ISSUE THREAD

**Issue by GloriaCHL** [ant-design/ant-design-pro#6444]
### 🧐 问题描述

v4的 '/' 路径默认就自带一个layout，可以通过配置或者修改 src 下的什么文件去掉这个 layout 吗？我现在需求是直接在 / 目录中写内容；而且另外一点是就算跳转到其他页面有时候也会出现根路径下的那个layout闪过的视觉。

---

###### 后续尝试
* 尝试了在 config.js 中的 / 里面配置 `layout: false`并没有成功隐去 layout
* 在v4项目中的 src 目录里找不到文档 (https://pro.ant.design/docs/layout-component-cn)[https://pro.ant.design/docs/layout-component-cn] 介绍的 `BasicLayout`文件

**Comment by pengzj** [comment]
今天也越到同样的问题，现在src下已经没有layouts文件夹，我自己添加的layout没有办法覆盖之前的，现在layout重叠了，不知道这个明天会修复吗？

**Comment by chenshuai2144** [comment]
可以在路由上设置 layout=false，或者在config.js 中设置layout=false

**Comment by GloriaCHL** [comment]
> 可以在路由上设置 layout=false，或者在config.js 中设置layout=false
> 
> 文档还在编写中，可以看这里
> https://umijs.org/plugins

###### 尝试一: `config.js` 中直接改 layout
```
  // layout: {
  //   name: 'Ant Design Pro',
  //   locale: true,
  // },
  layout: false,
```
这样改是直接报错的。

###### 尝试二：根路由 '/' 设置 layout: false
```javascript
   {
      path: '/',
      // redirect: '/welcome',
      layout: false,
      component: './Welcome',
    },
```
这样设置不起作用，根路径下的 layout 依然存在。

**Comment by BluesVN** [comment]
> > 可以在路由上设置 layout=false，或者在config.js 中设置layout=false
> > 文档还在编写中，可以看这里
> > https://umijs.org/plugins
> 
> ###### 尝试一: `config.js` 中直接改 layout
> ```
>   // layout: {
>   //   name: 'Ant Design Pro',
>   //   locale: true,
>   // },
>   layout: false,
> ```
> 
> 这样改是直接报错的。
> 
> ###### 尝试二：根路由 '/' 设置 layout: false
> ```js
>    {
>       path: '/',
>       // redirect: '/welcome',
>       layout: false,
>       component: './Welcome',
>     },
> ```
> 
> ## 这样设置不起作用，根路径下的 layout 依然存在。
> 那个 plugin 的文档我之前看过了，没有介绍怎么取消根路径layout的方法。望指条明路～

我也遇到同样的问题,请问解决了吗?

我打算在app.tsx中引入prolayout 覆盖试试看;

标准化了有些配置不太容易看到原理 有点恶心

**Comment by GloriaCHL** [comment]
> > > 可以在路由上设置 layout=false，或者在config.js 中设置layout=false
> > > 文档还在编写中，可以看这里
> > > https://umijs.org/plugins
> > 
> > 
> > ###### 尝试一: `config.js` 中直接改 layout
> > ```
> >   // layout: {
> >   //   name: 'Ant Design Pro',
> >   //   locale: true,
> >   // },
> >   layout: false,
> > ```
> > 
> > 
> > 这样改是直接报错的。
> > ###### 尝试二：根路由 '/' 设置 layout: false
> > ```js
> >    {
> >       path: '/',
> >       // redirect: '/welcome',
> >       layout: false,
> >       component: './Welcome',
> >     },
> > ```
> > 
> > 
> > ## 这样设置不起作用，根路径下的 layout 依然存在。
> > 那个 plugin 的文档我之前看过了，没有介绍怎么取消根路径layout的方法。望指条明路～
> 
> 我也遇到同样的问题,请问解决了吗?
> 
> 我打算在app.tsx中引入prolayout 覆盖试试看;
> 
> 标准化了有些配置不太容易看到原理 有点恶心

没解决。官方也没回，他给的那个文档也没起作用，根路径不受那些控制，我还没法reopen这个issue。你可以试试你的想法，能解决的麻烦告知哈。

**Comment by JiayiLuoJarvis** [comment]
快2024年了，还没解决吗
