### ISSUE TITLE
New umijs ant-design-pro failed on the first commit

### ISSUE THREAD

**Issue by 3dw1np** [ant-design/ant-design-pro#6445]
## What happens?

New umijs ant-design-pro failed on the first commit on lint-staged:js (eslint):
Then you will get 2 errors (first one is easy to fix):
```
/app/src/e2e/baseLayout.e2e.js
  1:18  error  'lodash' should be listed in the project's dependencies. Run 'npm i -S lodash' to add it  import/no-extraneous-dependencies

i/app/src/utils/utils.test.ts
  1:17  error  getRouteAuthority not found in './utils'  import/named
```

## How To Reproduce

Just init a new app of type ant-design-pro && git add -A && git commit

## Context

- **Ant Design Pro**: 4.x
- **Umi Version**: 3.x
- **Node Version**: v13.13.0
- **Platform**: Mac OS

**Comment by chenshuai2144** [comment]
现在好了这个规则关掉了
