### ISSUE TITLE
Pie 图表每项数据为0时显示NaN%

### ISSUE THREAD

**Issue by jdongdong** [ant-design/ant-design-pro#645]
如下图：
![image](https://user-images.githubusercontent.com/11850305/34753218-c3b564ec-f5f1-11e7-9523-fa0fbcf37d41.png)

**Comment by afc163** [comment]
官网没问题的话，你需要先自行排查。否则我们只能靠猜了。

**Comment by jdongdong** [comment]
官方的也有问题哈
![image](https://user-images.githubusercontent.com/11850305/34753380-927149a4-f5f2-11e7-8d51-1a1186de482e.png)
mock数据改成如下图：
![image](https://user-images.githubusercontent.com/11850305/34753417-c191e2ac-f5f2-11e7-93b5-2a5b343c5468.png)

**Comment by nikogu** [comment]
@jdongdong 其实最好不要这样有这样的数据，不合理

**Comment by jdongdong** [comment]
我这边是按天统计，基本上0点到早上起床这个时间段的数据都是0
