### ISSUE TITLE
v5 --- @ant-design/pro-layout 构建时配置是否有必要？？？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6453]
### 🥰 需求描述

[@ant-design/pro-layout 构建时配置](https://umijs.org/zh-CN/plugins/plugin-layout#配置)

- **name** 这个在 pro-layout 就叫 title，同一个东西搞2个不同的名词是否有必要？[6450](https://github.com/ant-design/ant-design-pro/issues/6450)

- **logo** 这个在  pro-layout 是返一个ReactNode，现在是一个string，似乎满足不了需求，而且现在也有bug [6449](https://github.com/ant-design/ant-design-pro/issues/6449)

- **locale** 这个在 pro-layout 里有2个有，一个是设置pro-layout的国际化的，另一个是 menu: { locale: true }控制业务菜单国际化的，这里的 locale是对业务菜单国际化进行设置，也是容易搞晕的。

- **theme** 这个在外面暂时只能使用 pro，不是阿里内部的也使用不了你们的tech （Bigfish ），所以可以对外开源里写出来，呵呵。

### 🧐 解决方案

上述构建时配置，在 [app.ts 运行时配置](https://umijs.org/zh-CN/plugins/plugin-layout#配置)  里都可以配置出来，所以这些配置要不就配置在运行时里，要不就要构建时配置和运行时配置一致。

**Comment by chenshuai2144** [comment]
运行时配置就是原来的 prolayout 的 props，你可以直接覆盖

**Comment by kaoding** [comment]
我的意思是配置时和运行时名称上统一

**Comment by kaoding** [comment]
在构建时配置logo不行，应该是一个bug，我将这个issues打开了 [6449](https://github.com/ant-design/ant-design-pro/issues/6449)
