### ISSUE TITLE
🐛[BUG] yarn create umi -> ant-design-pro layouts文件夹缺失

### ISSUE THREAD

**Issue by yulrosy** [ant-design/ant-design-pro#6454]
### 📷 复现步骤

1. yarn create umi
2. Select the boilerplate type => ant-design-pro 
3. Be the first to experience the new umi@3 => y
4. yarn install 
5. yarn fetch:blocks
6. yarn start

Cannot find module 'xxx/src/layouts/BlankLayout

src缺少layouts

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本: 3.1.1
- create-umi 版本: 0.22.0
- 开发环境 [e.g. mac OS]: macOS 10.15.4

**Comment by ijisen** [comment]
+1

**Comment by lxzxl** [comment]
不要选 umi@3

**Comment by chenshuai2144** [comment]
umi@3 架构师全新的架构，使用方式有不同
文档在这里 https://umijs.org/plugins/preset-react
