### ISSUE TITLE
👑 [需求]create-umi创建的pro完整版本中暗黑模式和主题色怎么没有呢？

### ISSUE THREAD

**Issue by pccai** [ant-design/ant-design-pro#6455]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/2232794/80075962-06856380-857e-11ea-8393-af704f718dc2.png)

**Comment by chenshuai2144** [comment]
安装一下 插件就好了
https://pro.ant.design/docs/theme-cn#%E4%B8%BB%E9%A2%98%E5%AE%9A%E5%88%B6

**Comment by pccai** [comment]
多谢！
yarn add umi-plugin-antd-theme 就可以了。
