### ISSUE TITLE
v5 --- 扩展的路由配置 没有对应的？？？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6456]
**在老版本中**
- hideChildrenInMenu: 当前路由的子级在菜单中不展现，默认 false。
- hideInBreadcrumb: 当前路由在面包屑中不展现，默认 false。

 **在新的 v5 中没有对应的解决方法？？？** 
[扩展的路由配置](https://umijs.org/zh-CN/plugins/plugin-layout#扩展的路由配置)

**Comment by chenshuai2144** [comment]
文档没写，功能没有变 
你有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
文档没写，功能没有变 
你有兴趣来个 pr 吗？

**Comment by kaoding** [comment]
```
{
  name: 'dashboard',
  icon: 'dashboard',
  hideInMenu: true,
  hideChildrenInMenu: true,
  hideInBreadcrumb: true,
  authority: ['admin'],
}
```
上面是老版本的路由配置，在v5中，name，icon是有效的，hideInMenu，hideChildrenInMenu，hideInBreadcrumb是无效的，authority我没有测试，然在v5中看到了新的配置（扩展的路由配置），但不能覆盖老的需求，老的配置有的有效，有的无效。

**Comment by kaoding** [comment]
> 文档没写，功能没有变
> 你有兴趣来个 pr 吗？

我只会使用，发现问题，这个pr我提不了，还是要麻烦你们才行。

**Comment by kaoding** [comment]
再测试了一下：
```
{
  name: 'dashboard',
  icon: 'dashboard',
  hideInMenu: true,
  hideChildrenInMenu: true,
  hideInBreadcrumb: true,
  authority: ['admin'],
}
```
在 pro-layout 层面是可以的
但到 plugin-layout 层面就不行了，可能是 plugin-layout 的问题。
@chenshuai2144

**Comment by chenshuai2144** [comment]
已经修好了，感谢提醒
