### ISSUE TITLE
api/auth_routes is throwing 404 error in production

### ISSUE THREAD

**Issue by mattphung** [ant-design/ant-design-pro#6457]
Hi, I am able to run pro.ant.design locally but when I build and deploy to a server I get a 404 error for api/auth_routes and the username is not displayed and my admin routes are missing. I'm trying to create the api/auth_routes but I do not know what json to return back. I know umi is handling the api/auth_routes but I can't see the json that umi is returning. Any help would be greatly appreciated. Thank you

**Comment by chenshuai2144** [comment]
you can remove this api。we removed this api in preview
