### ISSUE TITLE
🧐[问题]antd pro4.0使用相同路径同时配置proxy代理与publicPath，执行dev运行时umi资源路径不正确

### ISSUE THREAD

**Issue by LydiaAgute** [ant-design/ant-design-pro#6458]
### 🧐 问题描述
antd pro4.0版本项目中，我同时配置了dev代理与publicPath，使用了相同的路径前缀。
在执行`npn run start:dev`启动项目后无限loading，查看浏览器请求时，发现请求的umi资源路径不正确。
### 💻 示例代码
为了复现问题，我使用`npm create umi`命令重新安装新的antd pro项目，然后执行以下改动：
1.proxy.ts中修改配置如下，将request请求代理到9002端口的后台服务：
```
  dev: {
    '/site': {
      target: 'http://localhost:9002',
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
  },
```
2.在config.ts中，添加如下配置：
```
  history: { type: 'hash' },
  publicPath: '/site/',
```
这样启动dev时就会发现，umi.css和umi.js均指向了/site/umi.*,导致请求被代理到9002端口的后台服务。
![info](https://user-images.githubusercontent.com/26812296/80167224-688fa880-8612-11ea-8328-2eaae61bcf88.png)

### 🚑 其他信息
预期的行为是，publicPath在dev环境下不生效，只在build时使用。但是目前的表现是开发环境下运行项目，umi文件路径一样会加上publicPath前缀。通常这样并不会带来问题，但是一旦配置了相同路径的代理和publicPath，就会导致umi资源文件路径异常，出现404。
在之前使用antd2.0版本中，该配置没有此问题，这样做无论是本地开发还是项目build，我都不需要再修改config文件。现在我在本地开发必须注释掉publicPath属性，而在打包前必须重新打开注释。
我现在应该如何配置代理，是否可以绕过所有静态资源的请求，应该如何配置？

**Comment by chenshuai2144** [comment]
一般不会出现这种情况需要使用正则，比如匹配.json 结尾的，不然程序无法区分静态资源和动态请求的区别
