### ISSUE TITLE
roadhog-api-doc start  error

### ISSUE THREAD

**Issue by wuzehao16** [ant-design/ant-design-pro#646]
Target container is not a DOM element.
▼ 3 stack frames were expanded.
invariant
D:/project/1801/ant-design-pro/node_modules/fbjs/lib/invariant.js:42
renderSubtreeIntoContainer
D:/project/1801/ant-design-pro/node_modules/react-dom/cjs/react-dom.development.js:15180
render
D:/project/1801/ant-design-pro/node_modules/react-dom/cjs/react-dom.development.js:15290
▲ 3 stack frames were expanded.
(anonymous function)
D:/project/1801/ant-design-pro/_roadhog-api-doc/src/api.js:345
```
  342 |   return ApiDoc;
  343 | }(Component);
  344 | 
> 345 | ReactDOM.render(_jsx(ApiDoc, {}), document.getElementById("root"));
  346 | 
  347 | 
  348 | //////////////////
```
▼ 6 stack frames were expanded.
__webpack_require__
internal:/webpack/bootstrap d51ccd31e41ef84740c4:678
fn
internal:/webpack/bootstrap d51ccd31e41ef84740c4:88
(anonymous function)
http://localhost:8000/api.js:14722:18
__webpack_require__
internal:/webpack/bootstrap d51ccd31e41ef84740c4:678
(anonymous function)
internal:/webpack/bootstrap d51ccd31e41ef84740c4:724
(anonymous function)
http://localhost:8000/api.js:728:10
▲ 6 stack frames were expanded.

**Comment by nikogu** [comment]
@wuzehao16 try `roadhog-api-doc@1.0.0`
