### ISSUE TITLE
table column使用fixed后缩放侧边栏会盖不住底部的td

### ISSUE THREAD

**Issue by desosaa** [ant-design/ant-design-pro#6460]
table的column我加入了fixed浮动此时是正常的。
但是当把左侧的侧边栏收缩后，会导致table的宽度发生了变化，此时fixed列会盖不住原先的列，因为原来的列随着table的宽度发生变化而变化了，但是fixed列却没有改变

**Comment by chenshuai2144** [comment]
可以使用 antd@4 来解决这个问题。
antd@3 解决这个问题很难，最好重新渲染一下

**Comment by desosaa** [comment]
vue 支持antd@4吗，我看react有了
