### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by bieao411327** [ant-design/ant-design-pro#6461]
想在class中使用formatMessage，但是控制台打出警告  
<使用此 api 会造成切换语言的时候无法自动刷新，请使用 useIntl 或 injectIntl>
useIntl只能在hook中使用，class中怎么用

**Comment by chenshuai2144** [comment]
injectIntl 注入到 props 中就好了

**Comment by bieao411327** [comment]
> injectIntl 注入到 props 中就好了
> 
> ```
> export default connect(state => {
>   return {
>     ...state
>   };
> })(injectIntl(App));
> ```
这个在antd pro中咋用啊，拜托了，大佬1
