### ISSUE TITLE
🧐[问题] 区块Dashboard/Monitor出错:Unhandled Rejection (Error): (regl) Error compiling fragment shader, http://localhost:8000/vendors~p__dashboard__monitor.js:23867:24

### ISSUE THREAD

**Issue by chzng** [ant-design/ant-design-pro#6462]
### 🧐 问题描述

Ant Design Pro 使用区块时候报错，Dashboard/Monitor这个区块没有做任何修改，当点击这个菜单后页面loading后开始时正常的，Map组件加载导致整个页面报错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/9945287/80191094-cee2ee00-8647-11ea-95b1-dca992a4290b.png)

![image](https://user-images.githubusercontent.com/9945287/80190632-32b8e700-8647-11ea-949d-27269506f718.png)

**Comment by chenshuai2144** [comment]
看起来是dva 和 map冲突了

**Comment by chenshuai2144** [comment]
l7 修复了
