### ISSUE TITLE
iconfont库可以在https://www.iconfont.cn/中找到吗？

### ISSUE THREAD

**Issue by 1195002442** [ant-design/ant-design-pro#6463]
### 💻 示例代码
import { Card, Icon, Row, Col } from 'antd';
import iconFont from '@/utils/iconfont';
const IconFont = Icon.createFromIconfontCN({
  scriptUrl: iconFont,
});

**Comment by 1195002442** [comment]
`我想要直接使用默认的iconfont，想知道库里面有哪些对应的图标。我发现和antd不是一套图标库，想知道有没有对应的可以在https://www.iconfont.cn/中能看到具体的图标`

**Comment by chenshuai2144** [comment]
https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=9402
在这里
