### ISSUE TITLE
🧐[问题]npm run start 启动后无法访问

### ISSUE THREAD

**Issue by hsh075623201** [ant-design/ant-design-pro#6465]
### 🧐 问题描述
npm run start 启动后无法访问 直接拉取的项目 没有编写任务代码

npm run start 启动后 访问  http://localhost:8000 控制台出现如下错误：
(node:14996) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: createRequire is not a function

**Comment by hsh075623201** [comment]
windows 用户 
npm:6.4.1
node:8.8.0

**Comment by chenshuai2144** [comment]
清空一下依赖重新安装试试呢？
看起来是某个依赖没有安装成功

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它


——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
