### ISSUE TITLE
🧐[问题]请教一个表单问题：表单中如何获取另外一个元素的值？

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6466]
### 🧐 问题描述

我的表单中，有一个 Switch “允许直销“，然后会有一个 InputNumber ”直销折扣“，我希望当 “允许直销”为 false 的时候，“直销折扣”为 disabled 状态，这个应该怎么做？

我看了 Pro的文档 Form部分会有 “自定义校验”，但这个并不能解决我的问题。

**Comment by 510846** [comment]
`const [allowRetail, setRetailAllow] = useState(false);`

配合
`Form.onValuesChange={(_, allValues) => { setRetailAllow(allValues.allowRetail);`

目前使用了上面的方法解决，不知道是否有更好的方法？

**Comment by 510846** [comment]
```
useEffect(() => {
  form.validateFields(['retailDiscount']);
}, ['allowRetail']);
```
使用上面代码 在 “允许直销“ 改变时，重新校验表单元素，碰到如下问题：
`devScripts.js:5035 Warning: Instance created by `useForm` is not connect to any Form element. Forget to pass `form` prop?`

应该如何解决？

**Comment by chenshuai2144** [comment]
@510846 https://www.yuque.com/chenshuai/web/gytp81
看这个小文章，有一些怪癖需要注意一下

**Comment by 510846** [comment]
> @510846 https://www.yuque.com/chenshuai/web/gytp81
> 看这个小文章，有一些怪癖需要注意一下

非常感谢！其实我的主要问题是：
1、如何做表单内元素的关联互动，比如：`<Switch checked />` 的时候才出现一个 `<InputNumber />` 输入折扣；
2、其实跟上面类似的，怎么根据另外一个字段值来做元素的校验？比如上面的 `<Switch checked/>` 时，我要求必须在 `<InputNumber />` 输入值。

—— 这个在很多的文档中，都没有看到有相关的说明 ~

**Comment by 15723185734** [comment]
> > @510846 https://www.yuque.com/chenshuai/web/gytp81
> > 看这个小文章，有一些怪癖需要注意一下
> 
> 非常感谢！其实我的主要问题是：
> 1、如何做表单内元素的关联互动，比如：`<Switch checked />` 的时候才出现一个 `<InputNumber />` 输入折扣；
> 2、其实跟上面类似的，怎么根据另外一个字段值来做元素的校验？比如上面的 `<Switch checked/>` 时，我要求必须在 `<InputNumber />` 输入值。
> 
> —— 这个在很多的文档中，都没有看到有相关的说明 ~

请问解决了吗？我们遇到的是一个问题 protable type=form时 怎么操作表单联动？

**Comment by 15723185734** [comment]
> > @510846 https://www.yuque.com/chenshuai/web/gytp81
> > 看这个小文章，有一些怪癖需要注意一下
> 
> 非常感谢！其实我的主要问题是：
> 1、如何做表单内元素的关联互动，比如：`<Switch checked />` 的时候才出现一个 `<InputNumber />` 输入折扣；
> 2、其实跟上面类似的，怎么根据另外一个字段值来做元素的校验？比如上面的 `<Switch checked/>` 时，我要求必须在 `<InputNumber />` 输入值。
> 
> —— 这个在很多的文档中，都没有看到有相关的说明 ~

请看到后回复一下 如果没有解决方案 我就手写了 我已经研究一天了 试了各种办法
