### ISSUE TITLE
🧐[问题]如何修改DefaultFooter页脚内容？

### ISSUE THREAD

**Issue by afr751116** [ant-design/ant-design-pro#6468]
### 🧐 问题描述

在UserBayout.tsx里面的DefaultFooter内容有搜过Issue说是不能修改，写死。同时也搜到说改
BasicLayout.tsx里的footerRender就好。但是可能太菜，不知具体修改哪些细节，不知可有文档详细说明？谢谢

**Comment by huntdream** [comment]
https://github.com/ant-design/ant-design-pro/blob/e0e65bbd7d40b75647925572b176d16889f5ed58/src/layouts/UserLayout.tsx#L60

https://github.com/ant-design/ant-design-pro/blob/e0e65bbd7d40b75647925572b176d16889f5ed58/src/layouts/BasicLayout.tsx#L156

把这两个地方的footer替换成自己的footer就好，注意类型
