### ISSUE TITLE
🧐[问题] 集成springboot 官方文档描述问题

### ISSUE THREAD

**Issue by TrumanDu** [ant-design/ant-design-pro#6469]
### 🧐 问题描述

```
@RequestMapping(value="/**", method=HTTPMethod.GET)
public String index(){
    return "index"
}
```
该配置会造成死循环。因为静态资源都在static下
### 💻 示例代码
![image](https://user-images.githubusercontent.com/16727775/80279533-e5b13f80-8730-11ea-9150-0b8621566018.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16727775/80279512-c1edf980-8730-11ea-9ad5-510b07547a8d.png)

**Comment by gehaijun** [comment]
你删掉那个controller 就行，boot会自己加
![image](https://user-images.githubusercontent.com/35563401/80296155-32396100-87ab-11ea-8568-23784868b089.png)

**Comment by TrumanDu** [comment]
@gehaijun `javax.servlet.ServletException: Circular view path [index]: would dispatch back to the current handler URL [/index] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name g`

**Comment by gehaijun** [comment]
![image](https://user-images.githubusercontent.com/35563401/80296370-04edb280-87ad-11ea-85c1-76d0b83e7d13.png)注释掉

**Comment by TrumanDu** [comment]
@gehaijun 给你发的结果就是已经注释掉了的

**Comment by TrumanDu** [comment]
@gehaijun 按官方文档，是无法实现springboot运行的。

通过调试其他代码，去掉你说的代码，springboot默认通过 `http://localhost:8080/` `http://localhost:8080`可以访问页面，但是会存在新的问题，强刷页面，无法找到相应的资源。
因为默认路径只对我举的例子生效，对于前端路由地址，例如`http://localhost:8080/admin/sub-page`依然会无法查找到资源。官方文档的本意是想让所有的资源都定向到`index.html`。就像上面所说的，按官方文档所述，会访问所有静态咨询造成循环，页面无法打开。

**Comment by gehaijun** [comment]
![image](https://user-images.githubusercontent.com/35563401/80296712-d6250b80-87af-11ea-9d96-7f9e83726006.png)
你得用hash路由，就是后面会有个#号。

**Comment by TrumanDu** [comment]
@gehaijun 
![image](https://user-images.githubusercontent.com/16727775/80296756-3025d100-87b0-11ea-97df-33a455e18508.png)
这个hash不知道又是什么意思。

深度使用过ice,对比后，发现ant design最大的问题是**配置文件太多**，**官网多个链接无效**，**技术栈重**，文档也有一定误导。


感谢，按你说的这种是可以的，但是无法解决**使用 browserHistory** 

默认生成的项目应该是browserHistory

**Comment by chenshuai2144** [comment]
来个pr？

**Comment by TrumanDu** [comment]
@chenshuai2144 好的，我整理一下
