### ISSUE TITLE
搜索列表(文章)，好评度查询条件布局错乱

### ISSUE THREAD

**Issue by doterme** [ant-design/ant-design-pro#647]
![image](https://user-images.githubusercontent.com/12495369/34756793-329a4dc6-f608-11e7-8076-d165e34ba43f.png)

**Comment by doterme** [comment]
而且多了一个label：好评度

**Comment by ddcat1115** [comment]
fixed in https://github.com/ant-design/ant-design-pro/commit/25e6789576df60e2bc855618f088a1cc94633d2b#diff-bac45500e7596eed57ca0270b99784f5
