### ISSUE TITLE
🧐[问题]菜单层级显示问题疑惑

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6470]
### 🧐 问题描述

比如有一个菜单 “产品”，分别有 “列表” 页面 和 “详情” 页面，但详情页面并不需要显示在 导航菜单中（hideInMenu: false），尽管如此，这个 “产品” 还是会变成了 “两级” 菜单，我希望还是显示为 “一级” 的菜单，应该怎么做？

![image](https://user-images.githubusercontent.com/7681405/80283030-5fecbe80-8747-11ea-9ddb-1c225ba68575.png)

**Comment by 510846** [comment]
尝试了 `hideChildrenInMenu: true` 选项，可是这样一来，详情页路由没有办法正常使用，还是显示的列表页面

```
{
  name: '订购人',
  icon: 'icon-customer',
  path: '/customers',
  component: './customer',
  hideChildrenInMenu: true,
  routes: [
    {
      name: '列表',
      icon: 'UnorderedList',
      path: '/customers/index',
      component: './customer',
    },
    {
      name: '详情',
      path: '/customers/:id',
      component: './customer/details',
      // hideInMenu: true,
    },
  ]
},
```

**Comment by 510846** [comment]
终于给“试”出来了一个解决方案 ~

```
{
  name: '订购人',
  icon: 'icon-customer',
  path: '/customers',
  component: './customer',
},
{
  name: '详情',
  path: '/customers/:id',
  component: './customer/details',
  hideInMenu: true,
},
```

目前工作正常 ~ close!

**Comment by admiao** [comment]
当多的时候文件就很乱了，这也不合法一个开发文件结构，我也遇到这个问题， 我不明白为什么会产生这种布局，还是自己哪里不明白。

**Comment by Emmeet** [comment]
> 终于给“试”出来了一个解决方案 ~
> 
> ```
> {
>   name: '订购人',
>   icon: 'icon-customer',
>   path: '/customers',
>   component: './customer',
> },
> {
>   name: '详情',
>   path: '/customers/:id',
>   component: './customer/details',
>   hideInMenu: true,
> },
> ```
> 
> 目前工作正常 ~ close!

兄弟你这个上面面包屑好用么，能跳回上一层么？

**Comment by codercatmomi** [comment]
> 终于给“试”出来了一个解决方案 ~
> 
> ```
> {
>   name: '订购人',
>   icon: 'icon-customer',
>   path: '/customers',
>   component: './customer',
> },
> {
>   name: '详情',
>   path: '/customers/:id',
>   component: './customer/details',
>   hideInMenu: true,
> },
> ```
> 
> 目前工作正常 ~ close!

这样详情页的时候 导航高亮不是没有了么

**Comment by chenshuai2144** [comment]
/customers/:id 是能匹配 path: '/customers', 的
