### ISSUE TITLE
🐛[BUG] 新增一个空白页模板后无法在空白页添加区块

### ISSUE THREAD

**Issue by dengkuang** [ant-design/ant-design-pro#6471]
### 🐛 bug 描述
新增一个空白页模板后无法在空白页添加区块

### 📷 复现步骤
提示 只有 pages 或 page 目录下的页面才能插入资产

![image](https://user-images.githubusercontent.com/64340803/80295824-81ca5d80-87a8-11ea-84c9-184045dc9428.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.1.4
- 浏览器环境
- 开发环境 [windows 10]

**Comment by johnnyzuo** [comment]
我也遇到了，而且不同浏览器还不一样，用谷歌只在console报Uncaught (in promise) TypeError: Illegal invocation，其他浏览器就会弹出提示框

**Comment by chenshuai2144** [comment]
试着重新启动一下
