### ISSUE TITLE
Is it possible to programmatically collapse sidebar?   

### ISSUE THREAD

**Issue by Dev142** [ant-design/ant-design-pro#6475]
I have button in the container area, now I need to toggle sidebar collapse. Is there any redux event to toggle it?

**Comment by huntdream** [comment]
![image](https://user-images.githubusercontent.com/7903755/80308709-f8944480-8802-11ea-92de-149d2132a3ff.png)
https://github.com/ant-design/ant-design-pro/blob/e0e65bbd7d40b75647925572b176d16889f5ed58/src/models/global.ts#L104
