### ISSUE TITLE
🧐[问题]BasicLayout.jsx生成的菜单中的icon无法显示

### ISSUE THREAD

**Issue by 18322517126** [ant-design/ant-design-pro#6479]
### 🧐 问题描述
为什么在config.js路由中配置的icon可以显示,在BasicLayout.jsx生成的路由中的icon无法显示?

### 💻 示例代码
BasicLayout.jsx中生成的菜单
       [
            {
                "path": "/dashboard",
                "name": "dashboard",
                "icon": "dashboard",
                "routes": [
                    {
                        "path": "/dashboard/analysis",
                        "name": "analysis",
                        "icon": 'smile',
                    },
                    {
                        "path": "/dashboard/monitor",
                        "name": "monitor"
                    },
                    {
                        "path": "/dashboard/workplace",
                        "name": "workplace"
                    }
                ]
            }
        ]

**Comment by 18322517126** [comment]
![image](https://user-images.githubusercontent.com/29945982/80329682-ac361c80-8875-11ea-93f0-d1bd58f0ca02.png)

**Comment by 27547897** [comment]
遇上同样问题，解决了吗？

**Comment by liufa520** [comment]
控制台会提示的，要装一个插件

**Comment by 27547897** [comment]
> 控制台会提示的，要装一个插件

![image](https://user-images.githubusercontent.com/45513420/80583665-194add00-8a43-11ea-8b3e-090f1ccc6098.png)
我的提示这个，是那个插件来的？我装了@ant-design/compatible没得显示，还记得是什么插件吗？

**Comment by liufa520** [comment]
点开链接进去看看呀。官网也有说------------------ 原始邮件 ------------------
发件人: "nrong8"<notifications@github.com>
发送时间: 2020年4月29日(星期三) 晚上6:00
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com>;
抄送: "davis_liu"<1404289545@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ant-design/ant-design-pro] &#x1F9D0;[问题]BasicLayout.jsx生成的菜单中的icon无法显示 (#6479)




  
控制台会提示的，要装一个插&#x4EF6;
  

 我的提示这个，是那个插&#x4EF6;来的？我装了@ant-design/compatible没得显示，还记得是什么插&#x4EF6;吗？
 
&mdash;

**Comment by joesdu** [comment]
安装"@ant-design/icons"这个库.后应该就好了.
