### ISSUE TITLE
小伙伴们，你们的首页是不是有问题啊？

### ISSUE THREAD

**Issue by vtista** [ant-design/ant-design-pro#648]
![default](https://user-images.githubusercontent.com/22438077/34762227-00012078-f622-11e7-96c0-92defb3ba321.png)
![default](https://user-images.githubusercontent.com/22438077/34762268-2b626bd2-f622-11e7-9501-b614e0d14655.png)

**Comment by afc163** [comment]
好像没问题。

<img width="891" alt="image" src="https://user-images.githubusercontent.com/507615/34762906-67257ee6-f624-11e7-954b-e1eeb2b16c4a.png">

**Comment by vtista** [comment]
Super well,then!
