### ISSUE TITLE
🧐[问题]为什么设置隐藏路由不生效，不能隐藏子级路由

### ISSUE THREAD

**Issue by zhouxiaona** [ant-design/ant-design-pro#6480]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31843561/80329848-1ea6fc80-8876-11ea-9281-93a54eddfdb1.png)

**Comment by x-yang11** [comment]
+1我在根routes设置hideInMenu也无效

**Comment by dreamZhf** [comment]
同问

**Comment by wenJonSnow** [comment]
同问

**Comment by myproject-hkp** [comment]
重新创建项目，是否使用umi3选择no，然后一切都正常，创建好的项目同样支持umi3

**Comment by admiao** [comment]
他这个路由我也好迷茫，umi约定式动态路由，没有看到灵活的一面，也没有看到约定后带来的好出发点在哪。

**Comment by chenshuai2144** [comment]
是 umi@3 中 plugin-layout 的 bug，已经修复
