### ISSUE TITLE
🧐[问题]请问登录页面的model loading怎么导入的呢

### ISSUE THREAD

**Issue by plabcd** [ant-design/ant-design-pro#6481]
### 🧐 问题描述
刚开始学习pro antd, 发现connect的里面的map方法的 loading没有引入&&定义就能使用，是为什么呢，我看资料都是 dva-loading， 是从哪里封装了么

### 💻 示例代码
export default connect(({ login, loading }) => ({
  userLogin: login,
  submitting: loading.effects['login/login'],
}))(Login);

**Comment by joesdu** [comment]
你说的应该是这个
![image](https://user-images.githubusercontent.com/13188169/80336817-e1009e80-888a-11ea-8fd7-fc0852037cc1.png)

**Comment by plabcd** [comment]
您好~ 是这个，但是我想知道为什么能解构出来 loading，引入的最开始的源头在哪里呢

**Comment by joesdu** [comment]
> 您好~ 是这个，但是我想知道为什么能解构出来 loading，引入的最开始的源头在哪里呢

在Umi3.x中直接通过umi的Loading引入的.

**Comment by plabcd** [comment]
@joesdu  谢谢。
