### ISSUE TITLE
🧐[问题]你们不不要把没有弄好程序发出来！BUG，统一修复不行吗！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#6482]
### 🧐 问题描述

太不专业的一帮人了！弄得BUG到处都是，一个没有弄好又体验第二个！一个稳定性都没有！

真是一帮废柴啊！

马云怎么养一帮这样勤奋的小白！先出稳定版的，体验版的后续出了！BUG逐渐恢复！

BUG一大堆，这个没有弄完，又有下一个版本！

你们连一个像样的“文档”都没有！

真是头脑思路混乱的程序员！开发的混乱程序！

**Comment by joesdu** [comment]
????

**Comment by xiaohuoni** [comment]
@hot588 你行你上，逼逼啥？是把你拉黑名单了，还是咋地？这么厉害不会PR嘛？你是充了会员还是搞了套餐啊，把你能的。
