### ISSUE TITLE
🐛[BUG] Umi 3 / Ant Design Pro 在路由中增加布局组件，导致菜单无法正常显示

### ISSUE THREAD

**Issue by ILiuDongHui** [ant-design/ant-design-pro#6483]
### 🐛 bug 描述

我使用了 UmiJS 3 版本的 Ant Design Pro ，并启用了 layout，在 config/config.js 中配置了 routes 数组，如：
```js
{
    routes: [
        {
            path: '/welcome',
            name: 'welcome',
            icon: 'smile',
            component: '/welcome',
        },
        {
            path: '/',
            redirect: './Welcome',
        }
    ]
}
```
这时，SiderMenu 表现正常，有1个一级菜单“welcome”。

但，当我想要给所有的顶级路由增加一个自定义的布局组件时，我将 routes 改为了如下：
```js
{
    routes: [
        {
            path: '/',
            component: '../layouts/MyLayout',
            routes: [ 
                {
                    path: '/',
                    redirect: '/welcome',
                },
                {
                    path: '/welcome',
                    name: 'welcome',
                    icon: 'smile',
                    component: './Welcome',
                },
            ]
        }
    ]
}
```
这个配置是在查阅了 UmiJS 3 官方文档和 Ant Design Pro 文档后更改的，当改为如上配置时，yarn start 启动后，可以访问 /welcome 路由，但是 SiderMenu 不正常了，它没有展示任何菜单项！！！

### 🏞 期望结果

可以自由的添加自定义布局组件，但不影响菜单的展示。

### © 版本信息

- Ant Design Pro 版本: "@ant-design/pro-layout": "^5.0.8"
- umi 版本: "umi": "^3.1.0"
- 浏览器环境: Google Chrome 81.0.4044.122（正式版本） （64 位）
- 开发环境: Windows 10 1909 18363.778

**Comment by chenshuai2144** [comment]
MyLayout 中需要将 props 传下去，layout 的菜单是根据 props 生成的
