### ISSUE TITLE
自定义主题切换后，无法找到assets下的图片🧐[问题]

### ISSUE THREAD

**Issue by wukaMM** [ant-design/ant-design-pro#6484]
### 🧐 问题描述

使用 
https://pro.ant.design/docs/dynamic-theme-cn#%E4%B8%BB%E9%A2%98%E5%88%87%E6%8D%A2
下提供的方法，自定义主题的切换后，原来less 文件中设置的背景图

background-image: url(~@/assets/logo.png); 

现在找不到了，控制台报出 

GET http://localhost:8003/theme/~@/assets/logo.png 404 (Not Found) 

似乎是因为在上面自定义主题的时候，styleLink.href = '/theme/theme1.css'; 影响了图片的路径查找，前面多了个 theme

想问下各位大神，怎么解决

### 💻 示例代码

自定义主题切换用的这段：

theme1 = true;
onClick = () => {
  let styleLink = document.getElementById('theme-style');
  let body = document.getElementsByTagName('body')[0];
  if (styleLink) {
    // 假如存在id为theme-style 的link标签，直接修改其href
    if (this.theme1) {
      styleLink.href = '/theme/theme1.css'; // 切换 antd 组件主题
      body.className = 'body-wrap-theme1'; // 切换自定义组件的主题
    } else {
      styleLink.href = '/theme/theme2.css';
      body.className = 'body-wrap-theme2';
    }
    this.theme1 = !this.theme1;
  } else {
    // 不存在的话，则新建一个
    styleLink = document.createElement('link');
    styleLink.type = 'text/css';
    styleLink.rel = 'stylesheet';
    styleLink.id = 'theme-style';
    if (this.theme1) {
      styleLink.href = '/theme/theme1.css';
      body.className = 'body-wrap-theme1';
    } else {
      styleLink.href = '/theme/theme2.css';
      body.className = 'body-wrap-theme2';
    }
    this.theme1 = !this.theme1;
    document.body.append(styleLink);
  }
};

**Comment by chenshuai2144** [comment]
background-image: url(~@/assets/logo.png)

url 应该用 "" 包起来
