### ISSUE TITLE
🧐[问题]关于 Select Search value 的疑问

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6485]
### 🧐 问题描述

目前根据官方文档 [and.design/components/select](https://ant.design/components/select-cn/#components-select-demo-search-box)
照着做了一个带搜索功能的 Select，现在碰到一个问题，我希望 value 使用 后端 数据库 id，那就跟 label 不是同一个值，这样做现在碰到一个问题：当搜索后选择了一项，这时再随便输入点内容，然后移开焦点（blur）已选中的内容就会变成了 id（期望是 label），这个该怎么办？

**Comment by 510846** [comment]
在 CodeSandbox 可以方便看到问题，请各位大佬指点 ~
https://codesandbox.io/s/sousuokuang-ant-design-demo-f9p5v

**Comment by chenshuai2144** [comment]
你需要的是 https://ant.design/components/auto-complete-cn/
