### ISSUE TITLE
🐛[BUG]BasicLayout.tsx中<ProLayout>的menuDataRender方法会被重复调用

### ISSUE THREAD

**Issue by YunSD** [ant-design/ant-design-pro#6486]
### 🐛 bug 描述

BasicLayout.tsx中<ProLayout>的menuDataRender方法会被重复调用，该方法会被调用两次
而且项目启动后，每次切换路由，都会重新加载菜单，我认为作为单页应用是没有必要的。

另外BasicLayout与SecurityLayout都会加载user/fetchCurrent的currentUser方法，当登陆后会查询两次，我认为这都没有必要。

我使用的 最新拉取的master分支clone下来的

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by YunSD** [comment]
不对，描述出现了错误，当刷新整个单页应用时，BasicLayout.tsx中的menuDataRender方法会被调用两次，当出现页面跳转时，也会触发调用menuDataRender，在低性能计算机，会出现明显的页面闪烁

**Comment by chenshuai2144** [comment]
为了保证菜单是最新的每次 render  的时候都会重新刷新的
你可以不配置 menuDataRender 就可以减少刷新次数，因为menuDataRender是个function，只有执行之后才知道结果
