### ISSUE TITLE
🧐[问题]CreateForm的时候，请教怎么对有的字段自动生成下拉框或CheckBox？

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro#6487]
### 🧐 问题描述

CreateForm的时候，请教怎么对有的字段自动生成下拉框或CheckBox？

**Comment by fengnex** [comment]
默认的效果：
不管字段的什么类型，生成的都是文本框。

**Comment by fengnex** [comment]
还有个问题，下面这样子创建的“新建”窗口，当children有很多个时，一列显示不完，怎么调整显示？
const CreateForm: React.FC<CreateFormProps> = props => {
  const { modalVisible, onCancel } = props;

  return (
    <Modal
      destroyOnClose
      title="新建***"
      visible={modalVisible}
      onCancel={() => onCancel()}
      footer={null}
    >
      {props.children}
    </Modal>
  );
};

**Comment by chenshuai2144** [comment]
试试这个 
https://ant.design/components/space-cn/

从数据中生成checkbox

https://ant.design/components/checkbox-cn/#components-checkbox-demo-group
