### ISSUE TITLE
🐛[BUG] ReferenceError: GUmiUIFlag is not defined

### ISSUE THREAD

**Issue by Preethamveigas** [ant-design/ant-design-pro#6488]
### 🐛 bug 描述

ReferenceError: GUmiUIFlag is not defined.

/*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_18___default.a.createElement(GUmiUIFlag, {..

Behaviour:-  randomly error shown.
workaround:- stop and run it again it works fine.
reproduce steps:- Not known   

error stacks:- 
<renderWithHooks
./node_modules/react-dom/cjs/react-dom.development.js:14803
mountIndeterminateComponent
./node_modules/react-dom/cjs/react-dom.development.js:17482
beginWork
./node_modules/react-dom/cjs/react-dom.development.js:18596
HTMLUnknownElement.callCallback
./node_modules/react-dom/cjs/react-dom.development.js:188
invokeGuardedCallbackDev
./node_modules/react-dom/cjs/react-dom.development.js:237
invokeGuardedCallback
./node_modules/react-dom/cjs/react-dom.development.js:292
beginWork$1
./node_modules/react-dom/cjs/react-dom.development.js:23203
performUnitOfWork
./node_modules/react-dom/cjs/react-dom.development.js:22154
workLoopSync
./node_modules/react-dom/cjs/react-dom.development.js:22130
performSyncWorkOnRoot
./node_modules/react-dom/cjs/react-dom.development.js:21756
(anonymous function)
./node_modules/react-dom/cjs/react-dom.development.js:11089
unstable_runWithPriority
./node_modules/scheduler/cjs/scheduler.development.js:653
runWithPriority$1
./node_modules/react-dom/cjs/react-dom.development.js:11039
flushSyncCallbackQueueImpl
./node_modules/react-dom/cjs/react-dom.development.js:11084
flushSyncCallbackQueue
./node_modules/react-dom/cjs/react-dom.development.js:11072
scheduleUpdateOnFiber
./node_modules/react-dom/cjs/react-dom.development.js:21199
dispatchAction
./node_modules/react-dom/cjs/react-dom.development.js:15660
checkForUpdates
./node_modules/use-subscription/cjs/use-subscription.development.js:87
(anonymous function)
./node_modules/@umijs/runtime/dist/index.esm.js:671
LoadableSubscription._update
./node_modules/@umijs/runtime/dist/index.esm.js:670
(anonymous function)
./node_modules/@umijs/runtime/dist/index.esm.js:653

**Comment by chenshuai2144** [comment]
git clean -dfx 即可，这种的一般是同时启动服务冲突导致的

**Comment by zchuhui** [comment]
我安装了 umi-ui 包后，每次更新包都会报这个错误，然后随便改一下又好了，挺无奈的。
移除 umi-ui 包后，就没这个问题了。

**Comment by WLyKan** [comment]
> git clean -dfx 即可，这种的一般是同时启动服务冲突导致的

记录一下：tyarn安装了新包，就可能出现这种情况
