### ISSUE TITLE
关于本地browserHistory问题，刷新报错

### ISSUE THREAD

**Issue by Zhou-Bill** [ant-design/ant-design-pro#649]
index.js 中使用browserHistory，刷新后就报错了

```
import browserHistory from 'history/createBrowserHistory';
const app = dva({
  history: browserHistory(),
  onError,
});

```

当在首页或其他链接刷新报 `Uncaught SyntaxError: Unexpected token <` 错误

我在npm start 下运行的， 还想问一个问题， 项目中有index.html ? 
`app.start('#root');`  app 组件应该挂载在 ` id = root` 的元素中，但我没找到index.html ,

**Comment by zqqq** [comment]
有 index.ejs
使用createBrowserHistory 后，遇到同样问题，但并不是每次个链接刷新都出错，只有 http://localhost:8000/user/login 登录成功之后跳转会出错。

**Comment by afc163** [comment]
browserHistory 需要服务端支持。

https://pro.ant.design/docs/deploy-cn#%E5%89%8D%E7%AB%AF%E8%B7%AF%E7%94%B1%E4%B8%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%9A%84%E7%BB%93%E5%90%88

**Comment by zqqq** [comment]
@afc163  clone的最新版。使用npm start 运行。并不是你说的问题
在未登录之前  访问 http://localhost:8000/user/login  是正常的，可以出来界面 
点击登录之后，登录成功，页面会自动刷新然后就出错了。
推测是  AuthorizedRoute 的问题
手动输入url 访问除 /user之外的路径，正常，请测试。

**Comment by sangxiaolong** [comment]
@afc163 之前不论是hashHistory还是browserHistory，本地开发都没问题的，不需要服务器配置，roadhog升级以后就出现这个问题了，只能用hashHistory，是不是index.html的问题，现在生成的index.html中'index.js'都是相对路径，而不是'/index.js'，系统找不到 /user/index.js

**Comment by sorrycc** [comment]
```
<script type="text/javascript" src="index.js"></script></body>
```

这串是 html-webpack-plugin 注入的吧？是否能改成 `/index.js` 得看下他的配置，[https://github.com/jantimon/html-webpack-plugin#configuration](https://github.com/jantimon/html-webpack-plugin#configuration)。

**Comment by afc163** [comment]
原来是 `/index.js`，这里应该算是一个升级不兼容的问题。

**Comment by sorrycc** [comment]
roadhog@1 dev 模式下的 publicPath 始终是 `/`，所以没这个问题。

**Comment by chenshuai2144** [comment]
@afc163   默认配个publicPath 吧。

**Comment by yyyddc** [comment]
@chenshuai2144 @sorrycc  请问publicPath在哪里加，是在html-webpack-plugin中加吗，我加了如下
```
"html-webpack-plugin": {
      "version": "2.30.1",
      "publicPath": "/",
      ...
      ...
      },
```
刷新还是出错，求解

**Comment by chenshuai2144** [comment]
在 .webpackrc里面配置一下

**Comment by balancelove** [comment]
在 .webpackrc 里配

**Comment by chenshuai2144** [comment]
@yyyddc   看 [6f2782083b70df3ff955ecc8dbc7d1229bb02fa1](https://github.com/ant-design/ant-design-pro/commit/6f2782083b70df3ff955ecc8dbc7d1229bb02fa1)

**Comment by chenshuai2144** [comment]
@sorrycc  云谦大大。。
 .webpackrc 里面hash ：true 有什么作用

**Comment by yyyddc** [comment]
感谢@chenshuai2144  @sorrycc 两位大哥
不过我当时是用的❯browser history simple (Simple version of Ant Design Pro with browser history)选项安装的ant-design-pro，即如下
```
? which type of scaffold do you want to new ?
  standard (All functional Ant Design Pro scaffold)
  simple (Simple version of Ant Design Pro with hash history)
❯ browser history simple (Simple version of Ant Design Pro with browser history)
```
这种方式安装的没有.webpackrc，`standard (All functional Ant Design Pro scaffold)`是有.webpackrc的，我需要安装什么包吗

**Comment by chenshuai2144** [comment]
这是个脚手架？？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-cli/commit/f51a45d4fb06426ac361513ad78ef8c6afd75a5e

**Comment by yyyddc** [comment]
经测试，修改.webpackrc文件后，刷新没问题，但我关闭mock后，使用云服务器如下：
```
export default (noProxy
  ? { "/*": "http://mywebsite/" }
  : delay(proxy, 1000));
```
`npm run start:no-proxy`
进入任意路由如：`http://localhost:8000/form/basic-form`，后刷新，出现：
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Jan 11 11:21:51 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available
```
求解

**Comment by yyyddc** [comment]
经测试，修改.webpackrc文件后，刷新没问题，但我关闭mock后，使用云服务器如下：
```
export default (noProxy
  ? { "/*": "http://mywebsite/" }
  : delay(proxy, 1000));
```
`npm run start:no-proxy`
进入任意路由如：`http://localhost:8000/form/basic-form`，后刷新，出现：
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Jan 11 11:21:51 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available
```
求解

**Comment by chenshuai2144** [comment]
一个很简单的404呀。 你的路径配错了呀

**Comment by lwt0023** [comment]
您好，antd-pro2.0好像没有搜索到webpackrc.js文件，请问应该在哪个文件里配置打包的路径呢？

**Comment by yutingzhao1991** [comment]
@lwt0023 2.0 框架改为 umi，可以参考 umi 文档在 `config/config.js` 中配置。
