### ISSUE TITLE
怎么修改网页标题🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6491]
### 🧐 问题描述
网页刷新的过程中标题的我个人配置的标题，刷新完成后网页标题就变成了localhost:8000,
我在defaultSettings和document.ejs 里面都改了但是还是不管用 
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.1",
!--
详细地描述问题，让大家都能理解
-->

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/27960630/80445901-f2f44700-8947-11ea-9272-31056bbb8e4f.png)

**Comment by chenshuai2144** [comment]
Config里面设置title为false 模仿一下matser的写法

**Comment by lovesL** [comment]
> Config里面设置标题为false模仿一下matser的写法

在请教一个问题 我想项目启动的url是localhost:8000/abv  这个该改哪里 conifg 里面的base 和publicpath 我都改了 不管用

**Comment by xiaohuoni** [comment]
这个配置开发的时候都会帮你映射到8000，如果你是build之后需要部署到类似的非更目录，才需要配置。
