### ISSUE TITLE
🧐[问题]更换主题时，antd-pro-merge-less有没有配置的地方

### ISSUE THREAD

**Issue by RuiCaiSmile** [ant-design/ant-design-pro#6492]
### 🧐 问题描述
在参照[这篇文章](https://pro.ant.design/blog/change-theme-cn)进行在线更换主题时，发现antd-pro-merge-less只收集src目录的less，请问该插件有配置的方法么？之前写了一部分less是放在其他目录的，这里收集不到

**Comment by chenshuai2144** [comment]
可以移到一起吗？
因为 src 之外的害怕循环应用，所以一直没有做。
