### ISSUE TITLE
🐛请问ant-design-pro新的脚手架创建项目不支持JS模式了吗？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6493]

**Comment by huaiguoguo** [comment]
你新建页面组件的时候，新建成js文件，直接写成js模式也支持的

**Comment by huaiguoguo** [comment]
#6474

**Comment by myproject-hkp** [comment]
使用npm create umi创建项目时是否使用umi3选择no，就可以正常选择了，而且创建出来的项目都是支持umi3的

**Comment by vini123** [comment]
现在又恢复以前的了，没有说选择使用 umi3 了。之前更新的那个，使用 umi3 ，那个 useModel 好像蛮好用的。现在的又去掉了。

**Comment by yysfwls** [comment]
> 使用npm create umi创建项目时是否使用umi3选择no，就可以正常选择了，而且创建出来的项目都是支持umi3的

选择no之后 是1.0.0版本哎 这太老了233

**Comment by ISBN9527** [comment]
@afc163 请问大佬，为什么无论怎么选择，都无法切换成JS语言，怎么下都是TS
