### ISSUE TITLE
🐛[BUG] 使用Input的Search组件，在onSearch的时候会导致页面闪动以及重载

### ISSUE THREAD

**Issue by taizhengfs** [ant-design/ant-design-pro#6498]
### 🐛 bug 描述
使用Input的Search组件，在onSearch的时候会导致页面闪动以及重载

### 📷 复现步骤
`<Search
            placeholder="Search by Address / Txhash / Block"
            onSearch={(value, event) => {
              event.preventDefault()
              props.onSearch(value, event)
            }}
            enterButton
          />`
比如这样一个组件，在onSearch的时候，我只是希望请求一个接口，并不希望当前页闪烁加载，于是我试着加了`event.preventDefault()`，但是依然会闪烁重载

### 🏞 期望结果
我希望我在onSearch的时候不会闪，当前页面不会有额外的操作，只是去执行我要处理的逻辑

### 💻 复现代码
`<Search
            placeholder="Search by Address / Txhash / Block"
            onSearch={(value, event) => {
              event.preventDefault()
              props.onSearch(value, event)
            }}
            enterButton
          />`

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本[3.0.14]
- 浏览器环境[chrome]
- 开发环境 [mac OS]

### 🚑 其他信息
暂无

**Comment by chenshuai2144** [comment]
这个应该和 Search 无关，是你的 props.onSearch(value, event)  导致的

**Comment by taizhengfs** [comment]
我直接在onSearch里面啥也不干也会重载刷新页面，不加 props.onSearch(value, event)  这句
