### ISSUE TITLE
拓展组件：参照

### ISSUE THREAD

**Issue by edeity** [ant-design/ant-design-pro#65]
对于一般的【企业级关联档案】，存在选择一个关联项的组件，举个例子，如高级表单中的审批人，在目前pro中表现为选择器Select；

但考虑子公司存在相同人名，需要额外的描述，如公司名，性别，职位等，此时更好的展示方式是表格；（可以弹出模态框等表现形式）；通用的表达有：简单表格，树表或树（如表达有层级关系的项），左树右表（如，左树表示子公司）；

以及基本功能，如搜索，刷新数据，常用选项等；对于树，也有是否级联，是否全选等常规操作；

在我们的业务中，这种富选择组件被称为【参照】，常作用于【关联档案】，在ant-desing-pro中是否存在这样的组件，或考虑封装成通用组件？（额外：组件通在表格单元格中也常常使用。应无缝支持ant Table中的render。)

**Comment by edeity** [comment]
1. 描述字段
![1](https://user-images.githubusercontent.com/10323795/32269869-b4d0ae4e-bec1-11e7-9c63-7366e3aedc45.png)

- 展示形式：基本表格
![2](https://user-images.githubusercontent.com/10323795/32269870-b4ffea2e-bec1-11e7-98fa-6fa6bfa698b2.png)

- 展示形式：树
![3](https://user-images.githubusercontent.com/10323795/32269985-239b16ca-bec2-11e7-94b6-37c464ede2b8.png)

- 展示形式：树表
![4](https://user-images.githubusercontent.com/10323795/32270019-48ea3064-bec2-11e7-84d2-22c6d8f10efe.png)

基本的原则是：快速无误选择对应的关联项；可认为是增强型的Select；
用法是：仅需描叙字段和渲染类型，如

```javascript
  const tempMeta = {
    field: 'checker'
    type: 'tree',
    data: 'xxx'
  }
  <Refer meta={meta}/>
```

**Comment by afc163** [comment]
暂时没有这个计划，不过我建议这个组件可以做成独立 react 方便复用和造福社区。

**Comment by Nokecy** [comment]
@edeity  关于这个组件 有想法可以分享吗？
