### ISSUE TITLE
browserHistory 路径问题

### ISSUE THREAD

**Issue by balancelove** [ant-design/ant-design-pro#650]
第一次打开页面，直接访问的根目录，然后加载没有问题，index.js 加载正常

![image](https://user-images.githubusercontent.com/20970152/34765660-0bbff9e2-f62d-11e7-8772-687f34a17f0d.png)

然后刷新页面，就不能加载了

![image](https://user-images.githubusercontent.com/20970152/34765713-2ea35440-f62d-11e7-82e4-313ebc3a4637.png)

因为他去加载了 user/index.js 

所以我觉得
![image](https://user-images.githubusercontent.com/20970152/34765768-58a54bcc-f62d-11e7-8686-40ab8ff7cc4d.png)

这个地方应该是  `/index.js`，这东西在哪儿配置呢？

**Comment by Jeepeng** [comment]
+1

**Comment by afc163** [comment]
Duplicate of #649
