### ISSUE TITLE
🐛[BUG]yarn create umi 默认使用的branch V5分支的代码。

### ISSUE THREAD

**Issue by bxvs888** [ant-design/ant-design-pro#6500]
### 🐛 bug 描述

生成的代码是v5分支的。如下图所示。

### 📷 复现步骤

yarn create umi 

### 🏞 期望结果

 master 分支或某一个稳定分支。
经比对，生成的代码是v5分支的。

### © 版本信息

- Ant Design Pro 版本: 4.0
- umi 版本 3.1.2
- 浏览器环境
- 开发环境 Mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/298322/80591982-39819880-8a51-11ea-8602-20799de93e7e.png)

**Comment by chenshuai2144** [comment]
create-umi 回滚了新的特性，已经不允许超前试用了
