### ISSUE TITLE
How to invalidate store on logout 🐛[BUG]

### ISSUE THREAD

**Issue by nbvora** [ant-design/ant-design-pro#6502]
### 🐛 bug 描述
I am loging out from application but not sure how to clear redux store. 

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
you can set a reducers，

reducers can clear all state
