### ISSUE TITLE
新增模版页 在加区块，提示只有pages 下的页面才能插入资产。

### ISSUE THREAD

**Issue by wenJonSnow** [ant-design/ant-design-pro#6503]
新增 模版页 在 加 区块，提示只有pages 下的页面才能插入资产。

本身 构建自带的页面模版，加区块又可以

![image](https://user-images.githubusercontent.com/24515796/80615298-15827f00-8a72-11ea-9405-508890320c6c.png)

**Comment by wenJonSnow** [comment]
4.29 的问题

**Comment by taizhengfs** [comment]
我前几天也遇到过这个问题   用 `BABEL_CACHE=none npm start ` 解决

**Comment by wenJonSnow** [comment]
刚才又突然 可以了

**Comment by s3341458** [comment]
> 我前几天也遇到过这个问题 用 `BABEL_CACHE=none npm start ` 解决

这个可以的谢谢🙏

**Comment by hot588** [comment]
我前几天也遇到过这个问题用BABEL_CACHE=none npm start 解决  这个是在环境配置里加入的嘛？

我加入多次都不行！

**Comment by s3341458** [comment]
@hot588 

两种选择 

1.改环境变量 export BABEL_CACHE=none 再npm start, 可以用.env 或者https://direnv.net/

2. 改package.json 里面的 scripts

**Comment by hot588** [comment]
> @ hot588
> 
> 两种选择
> 
> 1.改环境变量export BABEL_CACHE = none再npm start，可以用.env或https://direnv.net/
> 
> 1. 改package.json里面的脚本


我在.env 里的配置

PORT=8000
BABEL_CACHE=none


然后 npm start 启动，就是不行！

**Comment by hot588** [comment]
> @ hot588
> 
> 两种选择
> 
> 1.改环境变量export BABEL_CACHE = none再npm start，可以用.env或https://direnv.net/
> 
> 1. 改package.json里面的脚本


我在.env 里的配置

PORT=8000
BABEL_CACHE=none


然后 npm start 启动，就是不行！

**Comment by hot588** [comment]
"start": "BABEL_CACHE = none umi dev",  这样试过了，也没有什么用啊！修改有什么用呢！

**Comment by taizhengfs** [comment]
> > @ hot588
> > 两种选择
> > 1.改环境变量export BABEL_CACHE = none再npm start，可以用.env或https://direnv.net/
> > 
> > 1. 改package.json里面的脚本
> 
> 我在.env 里的配置
> 
> PORT=8000
> BABEL_CACHE=none
> 
> 然后 npm start 启动，就是不行！

啥都不用配置啊，直接终端里面输`BABEL_CACHE=none npm start` 回车就好了

**Comment by hot588** [comment]
> BABEL_CACHE=none npm start

BABEL_CACHE=none : 无法将“BABEL_CACHE=none”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保
路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ BABEL_CACHE=none npm start
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (BABEL_CACHE=none:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by taizhengfs** [comment]
> "start": "BABEL_CACHE = none umi dev", 这样试过了，也没有什么用啊！修改有什么用呢！

你把`"start": "BABEL_CACHE = none umi dev"` 重新改回 `"start": "umi dev"`, 然后在终端编译的时候输 `BABEL_CACHE=none npm start` 然后回车，我这样是可以的

**Comment by hot588** [comment]
> BABEL_CACHE=none npm start

改过来了啊！

**BABEL_CACHE=none : 无法将“BABEL_CACHE=none”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保
路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ BABEL_CACHE=none npm start
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (BABEL_CACHE=none:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**

**Comment by hot588** [comment]
![QQ图片20200506172534](https://user-images.githubusercontent.com/51880332/81161739-9f749f80-8fbe-11ea-90f4-6c2b203d4502.png)

**Comment by hot588** [comment]
> > “ start”：“ BABEL_CACHE = none umi dev”，这样试过了，也没有什么用啊！修改有什么用呢！
> 
> 你把`"start": "BABEL_CACHE = none umi dev"`重新改回`"start": "umi dev"`，然后在终端编译的时候输`BABEL_CACHE=none npm start`然后回车，我这样是可以的

你看看是不是这样的？

**Comment by hot588** [comment]
> > “ start”：“ BABEL_CACHE = none umi dev”，这样试过了，也没有什么用啊！修改有什么用呢！
> 
> 你把`"start": "BABEL_CACHE = none umi dev"`重新改回`"start": "umi dev"`，然后在终端编译的时候输`BABEL_CACHE=none npm start`然后回车，我这样是可以的

帮忙看看，怎么回事啊！

**Comment by hot588** [comment]
每次添加空白页，都要重新启动一下，才不会出现这个提示！  重启后，就可以添加了！

新建.env文件  然后添加  BABEL_CACHE=none  这个解决不了实际问题！我都做很多遍了！

umi 文档的 环境配置里有这个，但是没有解决不了问题的！

**Comment by s3341458** [comment]
我不是windows用户不知道 是不是一样在我的电脑上 你是不能有空格的

"BABEL_CACHE=none umi dev" 而不是 "BABEL_CACHE = none umi dev"

实在不行你可以在 命令行里面设置环境变量 我是“export BABEL_CACHE=none” 在运行 ”npm start“

**Comment by hot588** [comment]
> BABEL_CACHE = none umi dev

这个也不行，都试过了！

实在没有办法，就用.env里，加了BABEL_CACHE = none

每次先批量增加 模板，然后重启下，这样就可以添加了！

**Comment by afc163** [comment]
右上角中间这个按钮点一下试试：

<img width="143" alt="image" src="https://user-images.githubusercontent.com/507615/81248600-4a349e80-904f-11ea-8de5-a87a444effe6.png">

**Comment by hot588** [comment]
> 右上角中间这个按钮点一下试试：
> 
> <img alt="图片" width="143" src="https://user-images.githubusercontent.com/507615/81248600-4a349e80-904f-11ea-8de5-a87a444effe6.png">

清理模块都清理过了！能弄的都弄了！


现在就是解决方案 就是 一次批量建模板，把需要的模板都创建好！建好以后！重新启动下


就可以添加区块了！这样就没有问题了！

也算一种解决方案吧！

其他的没有啥用啊！

win10操作系统！

**Comment by hot588** [comment]
cross-env BABEL_CACHE=none umi dev

这样在package.json 添加有  执行 npm start

**Comment by gameruleCEO** [comment]
> > 右上角中间这个按钮点一下试试：
> > <img alt="图片" width="143" src="https://user-images.githubusercontent.com/507615/81248600-4a349e80-904f-11ea-8de5-a87a444effe6.png">
> 
> 清理模块都清理过了！能弄的都弄了！
> 
> 现在就是解决方案 就是 一次批量建模板，把需要的模板都创建好！建好以后！重新启动下
> 
> 就可以添加区块了！这样就没有问题了！
> 
> 也算一种解决方案吧！
> 
> 其他的没有啥用啊！
> 
> win10操作系统！

还是你这方法靠谱，上面说的那些都不行，加配置啥的不好使，看来只能先这么搞了....

**Comment by sun-te** [comment]
[csdn](https://blog.csdn.net/shujudaniu/article/details/106080987?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.nonecase&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.nonecase)的评论里说在`PageHeaderWrapper`标签里随便加点内容就可以了。

原文是："我在src,pages目录下的我插入的模块，比如名字为test1,然后进入的test1下,打开index.tsx,找到<Spin spinning={loading} size="large" />，在后面随便输入点东西，然后就可以了，不知道是啥原因"

**Comment by cryst4lMao** [comment]
> > 右上角中间这个按钮点一下试试：
> > <img alt="图片" width="143" src="https://user-images.githubusercontent.com/507615/81248600-4a349e80-904f-11ea-8de5-a87a444effe6.png">
> 
> 清理模块都清理过了！能弄的都弄了！
> 
> 现在就是解决方案 就是 一次批量建模板，把需要的模板都创建好！建好以后！重新启动下
> 
> 就可以添加区块了！这样就没有问题了！
> 
> 也算一种解决方案吧！
> 
> 其他的没有啥用啊！
> 
> win10操作系统！

你在pages下新建一个文件夹，把你通过umi创建的模板文件拖到这个文件夹中，重启下就可以了
![image](https://user-images.githubusercontent.com/12853720/83225239-e155c780-a1b1-11ea-9067-b1bb8d33c029.png)

**Comment by cryst4lMao** [comment]
> > > 右上角中间这个按钮点一下试试：
> > > <img alt="图片" width="143" src="https://user-images.githubusercontent.com/507615/81248600-4a349e80-904f-11ea-8de5-a87a444effe6.png">
> > 
> > 
> > 清理模块都清理过了！能弄的都弄了！
> > 现在就是解决方案 就是 一次批量建模板，把需要的模板都创建好！建好以后！重新启动下
> > 就可以添加区块了！这样就没有问题了！
> > 也算一种解决方案吧！
> > 其他的没有啥用啊！
> > win10操作系统！
> 
> 你在pages下新建一个文件夹，把你通过umi创建的模板文件拖到这个文件夹中，重启下就可以了
> ![image](https://user-images.githubusercontent.com/12853720/83225239-e155c780-a1b1-11ea-9067-b1bb8d33c029.png)

哦，别忘了改config.js中的路由配置

**Comment by lchjczw** [comment]
试了上面的方法都没用,最后升级yarn到最新版解决了

**Comment by HaiYoungs** [comment]
> > BABEL_CACHE=none npm start
> 
> BABEL_CACHE=none : 无法将“BABEL_CACHE=none”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保
> 路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> 
> * BABEL_CACHE=none npm start
> * ```
>     + CategoryInfo          : ObjectNotFound: (BABEL_CACHE=none:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

我也死遇到这种情况，不能识别 BABEL_CACHE=none，好像是环境变量的问题，请问怎么解决？

**Comment by gameruleCEO** [comment]
> > > BABEL_CACHE=none npm start
> > 
> > 
> > BABEL_CACHE=none : 无法将“BABEL_CACHE=none”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保
> > 路径正确，然后再试一次。
> > 所在位置 行:1 字符: 1
> > 
> > * BABEL_CACHE=none npm start
> > * ```
> >     + CategoryInfo          : ObjectNotFound: (BABEL_CACHE=none:String) [], CommandNotFoundException
> >     + FullyQualifiedErrorId : CommandNotFoundException
> >   ```
> 
> 我也死遇到这种情况，不能识别 BABEL_CACHE=none，好像是环境变量的问题，请问怎么解决？

[https://blog.csdn.net/shujudaniu/article/details/106080987](参考我这篇文章)
