### ISSUE TITLE
 v4 src/layouts 目录 没了 ？？？ 造成   npm run fetch:blocks  后config.ts 配置错误

### ISSUE THREAD

**Issue by wenJonSnow** [ant-design/ant-design-pro#6504]
v4 src/layouts 目录 没了 ？？？ 造成   npm run fetch:blocks  后config.ts 配置错误，最终导致无法启动项目

![image](https://user-images.githubusercontent.com/24515796/80616714-d05f4c80-8a73-11ea-8e87-21596ea6792c.png)

**Comment by tonyxinxin** [comment]
一样的问题，还以为自己操作错了，搞了3次~~~浪费时间

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/tree/master/src/layouts

**Comment by yidafu** [comment]
I found that `src/` doesn't have `layout/` dir  if select `Be the first to experience the new umi@3` when 
 generate from boilerplate. @xiaohuoni

**Comment by xiaohuoni** [comment]
@chenshuai2144 感觉是脚手架提供太早了。这边还没同步完成。

**Comment by afc163** [comment]
@chenshuai2144 回滚吧，搞个 next 版本。Pro 的兼容性一定要保障好。

PS：之前的 umi2 区块迁移就没考虑好，老用户已经没法用了。

**Comment by bubucuo** [comment]
胖友们 你们是提前过五一去了么 pro代码有layout 命令行敲出来的没有 官方文档还是老的  现在在研究源码 看到底是怎么回事 您们有时间还是赶紧回来更新吧

**Comment by xiaohuoni** [comment]
直接拉主分支代码，初始化项目就好。

**Comment by chenshuai2144** [comment]
我默认选的都是 false，还有一堆人用，我直接删掉吧

**Comment by chenshuai2144** [comment]
删除 umi@3 的选项，需要的人可以 

yarn create umi  --branch v5

**Comment by afc163** [comment]
等我们都准备好了再上。
