### ISSUE TITLE
🧐[问题]一个来自于新成员的疑问

### ISSUE THREAD

**Issue by afr751116** [ant-design/ant-design-pro#6506]
### 🧐 问题描述

刚接触Pro ， 想请问下，有没有较全面的教程或文档？我找了官网了都是针对某个问题或阶段而说明。

有无类似刚上手，那我们第一考虑登陆问题，这里面的样式、后端通讯涉及哪些文件？
传的JSON字段源在哪些文件，需要修改哪些？

第二就是页面布局，功能。。。。这样一步一步的教程或文档有没有？

**Comment by yzw2017** [comment]
文档目录结构有说明，剩下的要自己慢慢摸索，去看代码。 我也是这样过来的，其实不难

**Comment by chenshuai2144** [comment]
pro 很多实用的都是约定，读一下官网就能看到各种约定了
