### ISSUE TITLE
npm create umi 没了javascript模板了.

### ISSUE THREAD

**Issue by yzw2017** [ant-design/ant-design-pro#6507]
window 10 使用Npm create umi 创建ant design pro 没了javascript模板选择。clone下来的只有ts模板。这不科学呀

**Comment by wenJonSnow** [comment]
现在 可以了

**Comment by luohaisi** [comment]
为什么我今天用还不可以？mac版的

**Comment by luohaisi** [comment]
> 现在 可以了

为什么我今天用还不可以？mac版的。需要升级什么吗？

**Comment by chenshuai2144** [comment]
@luohaisi  需要重新安装依赖，或者在使用 全新 umi@3 架构的时候选择 false

**Comment by iHDJ** [comment]
问题解决了吗？我tm也遇到这脑瘫问题了
