### ISSUE TITLE
为什么设置隐藏路由不生效，不能隐藏子级路由

### ISSUE THREAD

**Issue by wenJonSnow** [ant-design/ant-design-pro#6508]
hideInMenu: 当前路由在菜单中不展现，默认 false。
hideChildrenInMenu: 当前路由的子级在菜单中不展现，默认 false。
hideInBreadcrumb: 当前路由在面包屑中不展现，默认 false  

这3个值 都无效了

**Comment by wenJonSnow** [comment]
现在 又可以了， 重新 npm create umi

**Comment by yebingo** [comment]
但是已经在开发的项目碰到这样的问题怎么办？
总不能再生成个模板重新搞一遍？
