### ISSUE TITLE
pro如何使用iconfont上的图标🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6509]
### 🧐 问题描述
antd pro 的菜单栏如何使用公司自定义的图标，并且已经上传到iconfont上了 
版本
@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.1",

### 💻 示例代码
![image](https://user-images.githubusercontent.com/27960630/80687976-b0746b00-8afd-11ea-8927-0351b90ea822.png)
我cha查过相关文档 说这样设置 然后 这样使用 
![image](https://user-images.githubusercontent.com/27960630/80688176-fe896e80-8afd-11ea-8165-4fd5297cf528.png)
但是依然不显示图标

**Comment by jockey100332** [comment]
解决了吗

**Comment by lovesL** [comment]
> 解决了吗
解决了

**Comment by HengCC** [comment]
> > 解决了吗
> > 解决了

解决办法呢? 什问题导致的
