### ISSUE TITLE
yarn start 报错

### ISSUE THREAD

**Issue by dogrod** [ant-design/ant-design-pro#651]
![image](https://user-images.githubusercontent.com/21096842/34768058-c358c276-f634-11e7-9bbb-aa907512c532.png)
``npm start``一样，跟随文档使用 ant-design-pro-cli 安装的

**Comment by chenshuai2144** [comment]
[roadhog 2.0](https://github.com/sorrycc/blog/issues/55)
有个和你一样的问题 ，你看看

**Comment by chenshuai2144** [comment]
看你的报错信息。应该是roadhog 命令未找到这种的

**Comment by dogrod** [comment]
@chenshuai2144 这个issue我昨天有看到过，跟他的情况不一样。roadhog那边我也去找过好像也没有类似的情况

**Comment by chenshuai2144** [comment]
重装一下环境吧。
node升级一下版本

**Comment by iugo** [comment]
@chenshuai2144 鉴于是一个严肃的生产环境项目, 无论是 npm 还是 yarn, 建议加个 lock 文件吧.

**Comment by chenshuai2144** [comment]
建议自己搞一个lock
