### ISSUE TITLE
antd desgin pro 使用iconfont

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6513]
### 🧐 问题描述
antd desgin pro 使用iconfont 界面上了一节显示了ico的dom  但是图标没显示 似乎没有加载
![image](https://user-images.githubusercontent.com/27960630/80818238-62e32580-8c05-11ea-9154-7ee11221645d.png)
![image](https://user-images.githubusercontent.com/27960630/80818384-a8075780-8c05-11ea-87a1-fb03a05adaaf.png)
下面是我的icofont配置
![image](https://user-images.githubusercontent.com/27960630/80818480-d5540580-8c05-11ea-9a05-5350a5176e6b.png)
我尝试在那个url前面加了http 似乎也不管用 

### 🚑 其他信息
版本
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.1",
    "antd": "^4.0.0",

**Comment by joesdu** [comment]
interface IconFontProps extends IconBaseProps {
  type: string;
}
export const IconFont: React.FC<IconFontProps> = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_1709014_wl3qyrmbhuo.js'
});
这么写就好了.
