### ISSUE TITLE
🐛控制台报错require("history").createHashHistory

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6517]
### 🐛 控制台报错require("history").createHashHistory
![image](https://user-images.githubusercontent.com/37643958/80897017-2576b900-8d27-11ea-98ff-dce528d9094f.png)

**Comment by chenshuai2144** [comment]
使用这个版本
https://www.npmjs.com/package/dva/v/2.6.0-beta.20
