### ISSUE TITLE
🐛国际化报错

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6518]
### 🐛 国际化报错
Warning: Using this API will cause automatic refresh when switching languages, please use useIntl or injectIntl.
![image](https://user-images.githubusercontent.com/37643958/80897041-6f5f9f00-8d27-11ea-9cd4-d68b6baf5a2e.png)
![image](https://user-images.githubusercontent.com/37643958/80897050-8605f600-8d27-11ea-8fff-8e77dde9a50f.png)

**Comment by admiao** [comment]
![image](https://user-images.githubusercontent.com/24733229/80909020-58d13c00-8d57-11ea-8f9c-2cb9ee095d98.png)
我暂时注释了config这里 .

**Comment by chenshuai2144** [comment]
你看看相应的文档就好了，里面详细描述了为什么

**Comment by 4kb-wgh** [comment]
我也遇到国际化的问题。
Warning: Using this API will cause automatic refresh when switching languages, please use useIntl or injectIntl.
**函数组件**也遇到过，用了useIntl解决了，单这是**类组件**，怎么解决？
`import { injectIntl, InjectedIntlProps } from "react-intl";
import { formatMessage, useIntl } from 'umi';

class Info extends React.Component {
   render(){
    return (
    <Select>
                    <Option value={0}>{formatMessage({ id: 'register.hk.xs' })}</Option>
                    <Option value={1}>{formatMessage({ id: 'register.hk.ns' })}</Option>
                </Select>
    )
  }
}

export default injectIntl(Info);`

**Comment by chenshuai2144** [comment]
直接用组件，不要用静态方法
