### ISSUE TITLE
🧐[问题]patchRoutes方法里面修改路由。

### ISSUE THREAD

**Issue by blackboy1987** [ant-design/ant-design-pro#6521]
### 🧐 问题描述
参照uimijs的运行时配置，在patchRoutes里面修改路由。发现只能添加一层，如果是添加子路由，子路由不效果。
![image](https://user-images.githubusercontent.com/6405701/80908084-8fa35400-8d4f-11ea-8e20-013ec9a67bf0.png)
访问路由http://localhost:8000/foo 是可以的：
![image](https://user-images.githubusercontent.com/6405701/80908124-dc872a80-8d4f-11ea-8bb2-eed90aa6c05e.png)
访问http://localhost:8000/foo/1 就是404了。Welcome和Welcome组件都是有的。
![image](https://user-images.githubusercontent.com/6405701/80908130-edd03700-8d4f-11ea-8ec0-c723d349353c.png)

**Comment by chenshuai2144** [comment]
去umi问一下把，这个routers 是不是需要返回?
