### ISSUE TITLE
🧐[问题] 移除国际化文件后，浏览器控制台报错

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design-pro#6522]
### 🧐 问题描述
使用 `create-umi@0.22.0` 初始化 ts 版本项目
使用 `yarn i18n-remove` 移除国际化，并删除相关 locales 文件夹
控制台菜单爆出国际化的一些错误，虽然不影响使用，但是开发很不舒服。
请问如何彻底移除这些国际化，但不影响 antd 等这些相关配置。

国际化配置如下
```js
  locale: {
    // default zh-CN
    default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    antd: true,
    baseNavigator: true,
  }
```

错误如下
![image](https://user-images.githubusercontent.com/13798931/80909336-07767c00-8d5a-11ea-9713-aa18ba332af2.png)

### 💻 示例代码

官方示例

**Comment by zhfish** [comment]
remove了就不要配置locale了

**Comment by tomgao365** [comment]
@zhfish 如果配置locale为false，antd的国际化就出问题。

**Comment by chenshuai2144** [comment]
需要自己配置locale 不能用umi的了

**Comment by tomgao365** [comment]
@chenshuai2144 
哦，config.ts 里的 locale 设置为 false；
在 v5 中如何实现如下国际化配置呢？不知如何下手。
```
import zhCN from 'antd/es/locale/zh_CN';

return (
  <ConfigProvider locale={zhCN}>
    <App />
  </ConfigProvider>
);
```

**Comment by chenshuai2144** [comment]
你可以在外层继续配置的一个layout
```
import zhCN from 'antd/es/locale/zh_CN';

const Layout:React.FC<{}> = ({children})=>{
  return (
    <ConfigProvider locale={zhCN}>
      {children}
    </ConfigProvider>
  );
}
```

**Comment by 569202812** [comment]
> const Layout:React.FC<{}> = ({children})=>{
>   return (
>     <ConfigProvider locale={zhCN}>
>       {children}
>     </ConfigProvider>
>   );
> }

这个在哪文件里写,写了之后怎么配置layout
