### ISSUE TITLE
Tree或者modal不支持滚动条？

### ISSUE THREAD

**Issue by teeemooo** [ant-design/ant-design-pro#653]
把tree放到了一个modal中弹出，Tree的展开会无限拖长modal 即使modal设置了 bodyStyle={ {height:150 }}或者给tree设置height也无效 这不科学啊

**Comment by pkaq** [comment]
可以尝试设置 overflowY: 'scroll' 试试看

**Comment by teeemooo** [comment]
可以了 多谢
