### ISSUE TITLE
如何修改启动页🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6532]
### 🧐 问题描述
我想默认启动页是localhost：8080/home   我在config.js 里面配置了base: '/home/' publicPath: '/home/' 但是启动还是没有home

### 💻 示例代码
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.1",
"@ant-design/pro-cli": "^1.0.18",

**Comment by chenshuai2144** [comment]
没听懂你的描述,详细展开一下？

**Comment by lovesL** [comment]
> 没听懂你的描述,详细展开一下？
项目默认启动页是localhost:8080/
我想项目启动后 默认启动页是localhost:8080/home

**Comment by chenshuai2144** [comment]
用redirect  
base 和pulickpath是为了部署用的

```
{
   path:'/',
   redirect: '/home'
}

```
