### ISSUE TITLE
menuData请求的菜单数据，点点操作点击，是否受config.ts中authority的影响[问题]

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#6533]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/32530210/81156654-bfa16000-8fb8-11ea-8939-0f2abfff1cee.png)

突然想到一个问题，还请指点下,

如果从服务器动态拿到菜单数据menuData，
当点击菜单进入时，是否受到config.ts中配置的authority角色的限制。
还是config.ts的角色配置没有作用了，只要知道菜单的url都能访问进入。

**Comment by chenshuai2144** [comment]
会受到的，服务端获取的数据也会走一下 render 的

**Comment by xyzabc0004** [comment]
@chenshuai2144  
OK! 谢谢， 我后面试试看，
