### ISSUE TITLE
🧐[问题] V4版本的ant-pro如何设置域名与服务端交互？

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6534]
### 🧐 问题描述
V4版本的ant-pro如何设置域名与服务端交互？

当我在开发时，我在本地开始用的是proxy代理，但是线上打包后肯定不能用proxy了，那我怎么与后端交互呢？比如项目部署到xx.xx.xx:800，但是我想请求的是域名是xx.xx.xx:88

### 💻 示例代码
`import request from '@/utils/request';`

`export async function queryChort() {
  return request('/api/salesperson-app/v3/cohorts');
}`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/81246697-d7c1bf80-904a-11ea-83b2-514f177b92ca.png)

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/blob/c43f6eba9f6dcb09bf2dc33b9a7b298706bdeb6b/src/utils/request.ts#L52

这里加 prefix

**Comment by ISBN9527** [comment]
@xiaohuoni 大哥，不对啊，加上prefix后，http://192.168.11.14:800/88/api/salesperson-app/v3/login，我需要把192.168.11.14:800 ---> 192.168.11.14:88,并不是加前缀
![image](https://user-images.githubusercontent.com/30942709/81249633-aef0f880-9051-11ea-86c3-2c97bce12ff2.png)

**Comment by ISBN9527** [comment]
> https://github.com/ant-design/ant-design-pro/blob/c43f6eba9f6dcb09bf2dc33b9a7b298706bdeb6b/src/utils/request.ts#L52
> 
> 这里加 prefix

希望大佬解答

**Comment by xiaohuoni** [comment]
没看懂，你前缀直接写92.168.11.14:88 不就好了？

**Comment by ISBN9527** [comment]
`const request = extend({`
 ` errorHandler,
  // 默认错误处理`
  credentials: 'include', // 默认请求是否带上cookie
  `prefix: "192.168.11.14:88"
});`
这样？
