### ISSUE TITLE
🧐响应时间过长返回值为null 

### ISSUE THREAD

**Issue by WangTongesri** [ant-design/ant-design-pro#6536]
### 🧐 问题描述
你好，在ant pro中使用时，使用post方法，timeout设置6000000，大约4分钟左右出现返回null，执行失败提示，此时后端接口尚未返回正确结果，请问这个怎么解决？

### 💻 示例代码
export async function tdlyrun(params) {
    const pytxt = params;
    return new Promise((resolve, reject) => {
      request('/model/landusechange', {
        method: 'post',
        timeout: 600000,
        requestType: 'form',
        data: pytxt
      })
        .then(function (response) {
          debugger;
        })
        .catch(function (error) {
          console.log(error);
          reject(error)
        });
    })
  }

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/33825293/81254493-cdf58780-905d-11ea-8e51-8fb6ebc2882e.png)

**Comment by chenshuai2144** [comment]
什么接口需要 5 分钟才能返回？
一般都是后端的超时设置有问题，建议把 url 改成异步的

**Comment by WangTongesri** [comment]
> 什么接口需要5分钟才能返回？
> 一般都是初始化的超时设置有问题，建议把网址改成初始的

您好，问题已解决，发现是webpack中有一个timeout的内容，把这个timeout时间设长即可解决问题。

**Comment by WangTongesri** [comment]
您好，问题已解决，发现是proxy中有一个timeout的内容，把这个timeout时间设长即可解决问题。
dev: {
'/chengdu/': {
target: 'http:///chengdu/',
changeOrigin: true,
pathRewrite: {
'^/chengdu': '',
},
},
'/model/': {
target: 'http://:3005/model/',
changeOrigin: true,
proxyTimeout: 60 * 60 * 1000,
timeout: 60 * 60 * 1000,
pathRewrite: {
'^/model': '',
},
},
},






------------------

&nbsp; &nbsp; &nbsp; &nbsp; 祝您
顺利！










大数据解决方案部&nbsp;王彤



Esri中国信息技术有限公司

地址：北京市朝阳区西坝河南路1号金泰大厦16层

邮编：100028

传真：010-57632299

电话：010-57632149

手机：13581787601

网址：www.esrichina.com.cn
ArcGIS在线体验中心：http://solutions.arcgisonline.cn/ 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
