### ISSUE TITLE
🐛[BUG] V5 在路由配置菜单隐藏无效 hideInMenu: true,

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6538]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by yebingo** [comment]
同问

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/ant-design-pro/issues/6555
