### ISSUE TITLE
🧐[下载源码构建启动完成访问报错]

### ISSUE THREAD

**Issue by MRStruggle** [ant-design/ant-design-pro#6539]
### 🧐 问题描述
git clone 地址
npm install
npm run dev
以上3步完成后 根据提示访问网址 打开页面就是 显示如下
请求错误 404: http://localhost:8000/api/currentUser
发出的请求针对的是不存在的记录，服务器没有进行操作。
输入用户名密码 就是405 

我操作哪里不对了吗？

**Comment by chenshuai2144** [comment]
重装依赖试试呢。我试了一下是不会的
你关闭了 mock 吗？

**Comment by MRStruggle** [comment]
没有关闭，就直接下载下来，我换来目录 重新来了还不行，好奇怪，我让别人试试

**Comment by xshans** [comment]
我也碰到了，是什么原因呢？

**Comment by dfang** [comment]
@chenshuai2144 
+1, same as @MRStruggle but on v5 branch

**Comment by chenshuai2144** [comment]
试着升级一下 node 的版本到 12.x
