### ISSUE TITLE
🐛[BUG]console.log没有移除

### ISSUE THREAD

**Issue by YaseminLi** [ant-design/ant-design-pro#6540]
- Ant Design Pro 版本: 
       "antd": "^4.0.0-rc.1",
       "@ant-design/icons": "^4.0.0-alpha.19",
      "@ant-design/pro-layout": "^5.0.0",
        "@ant-design/pro-table": "^2.0.0",
- umi 版本 "umi": "^2.13.0",
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by afc163** [comment]
直接来 PR 个删除吧。

**Comment by YaseminLi** [comment]
> 直接来 PR 个删除吧。

没有封装好的删除log吗？还需要在webpack自己配置吗？

**Comment by afc163** [comment]
哪里有 console.log，把源码里的干掉吧。

**Comment by chenshuai2144** [comment]
源码里是没有console的，你想要的应该是build 的时候压缩代码顺便删除console把

**Comment by lengjh** [comment]
打包之后 ，怎么去掉console相关内容？
怎么配置？

**Comment by SilvaYH** [comment]
V5的话 可以先安装插件
terser-webpack-plugin 
然后在config/config.js  defineConfig中配置 chainWepack 
`const FileManagerPlugin = require('filemanager-webpack-plugin')`
` chainWebpack:(config)=>{
     // 生产环境
     config.when(IsPro, config => {
        config.optimization.minimizer('terser').use(require.resolve('terser-webpack-plugin')).tap((args) => {
          // 注释console.*
          args.push({
              cache: true,
              parallel: true,
              sourceMap: true,
              terserOptions: {
                compress: {
                  drop_console: true,
                  drop_debugger: true,
                  pure_funcs: ['console.log']
                }
              }
            })
          return args
        })
      })
    },`

**Comment by ProgramAlgo** [comment]
```
"antd": "^4.7.0"
"umi": "^3.2.14"
```

#### Through the API reference
[https://umijs.org/config#terseroptions](https://umijs.org/config#terseroptions)

[https://github.com/terser/terser#minify-options](https://github.com/terser/terser#minify-options)
- drop_console (default: false) -- Pass true to discard calls to console.* functions. If you wish to drop a specific function call such as console.info and/or retain side effects from function arguments after dropping the function call then use pure_funcs instead.

- drop_debugger (default: true) -- remove debugger; statements

#### edit config.ts
add **terserOptions** in config/config.ts

```
export default defineConfig({
  terserOptions: {
    compress: {
      drop_console: true,
      drop_debugger: true,
      pure_funcs: ['console.log']
    }
  },
});
```

**console.log** removed
