### ISSUE TITLE
Protable 组件的加载动画会对菜单的切换动画造成影响

### ISSUE THREAD

**Issue by YunSD** [ant-design/ant-design-pro#6542]
如题:Protable 组件的加载动画会对菜单的切换动画造成影响

实际会造成菜单切换到存在protable组件的页面时，菜单的切换动画会被protable的数据渲染干扰，，菜单动画的卡顿时间会根据protable数据数据渲染的时间长短而发生变化

**Comment by websmallrabbit** [comment]
怎么实现菜单切换，动画的？

**Comment by YunSD** [comment]
是这样的，再andt 中 菜单的切换是有一个0.3s的渐入渐出效果，这个是由css控制，但是andt protable数据渲染的时候，会对页面的渐入渐出动画造成影响。

**Comment by YunSD** [comment]
我在观察测试了一段时间后，发现这不是一个BUG，应该属于一个优化点。

**Comment by chenshuai2144** [comment]
有动图吗？
