### ISSUE TITLE
👑 [需求]建议新增富文本编辑器

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6543]
### 🥰 需求描述

或者有推荐的富文本编辑器吗？

**Comment by huntdream** [comment]
[braft-editor](https://github.com/margox/braft-editor)，这个感觉挺不错的，基于draft-js开发的
(最近在自己整富文本编辑器，也是基于draft-js，太难了😭 )

**Comment by sunft1996** [comment]
我用的wangeditor，感觉还可以。嫌文档麻烦你可以直接复制我这个[页面代码](https://github.com/sunft1996/ant-back/blob/master/src/pages/Article/ArticleEditor.js)


![页面图片-写文章](http://back.1cloud.xyz/uploadImg/1589959795874_article.png)

**Comment by kevinzl** [comment]
什么时候百度编辑器能支持 react就好了

**Comment by chenshuai2144** [comment]
暂时我们不会做的
