### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by lpgph** [ant-design/ant-design-pro#6544]
### 🐛 bug 描述
路由中 父级路由设置redirect无法转发到隐藏的子路由，页面显示空白
### 📷 复现步骤
父级路由中设置hideChildrenInMenu 隐藏所有子路由 ，通过redirect跳转到指定子路由中

### 🏞 期望结果
比如说文章管理是父级路由 它分为表单和列表 这两个子路由隐藏，点击文章管理跳转到文章列表页，在文章列表页点击新建可以跳转到文章表单页

### 💻 复现代码
{
  path: '/a',
  name: 'A',
  hideChildrenInMenu: true,
  redirect: '/a/list',
  routes: [
    {
      path: '/a/form',
      name: 'form',
      component: './A/form',
    },
    {
      path: '/a/list',
      name: 'list',
      component: './A/list',
    },
  ],
},

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本: 3.1.2
- 浏览器环境: Chromium Version 81.0.4044.129 (Official Build) Arch Linux (64-bit)
- 开发环境: Arch Linux

**Comment by chenshuai2144** [comment]
routes: [{path: '/a', redirect: '/a/list',}]
这样搞，redirect 有特殊处理，建议不要在上面带逻辑，会失效的
