### ISSUE TITLE
👑 [需求]建议添加转场动画

### ISSUE THREAD

**Issue by websmallrabbit** [ant-design/ant-design-pro#6545]
建议添加转场动画

**Comment by TianenPang** [comment]
这个好像可以自己实现的，官方有一些推荐的动画库😂

**Comment by websmallrabbit** [comment]
有没有成熟的方案 ，有个css -transition-group 怎么使用

**Comment by TianenPang** [comment]
> 有没有成熟的方案 ，有个css -transition-group 怎么使用

这两个动画库看看吧
[Ant Motion ](https://motion.ant.design/index-cn)  |  [React Spring](https://www.react-spring.io/)
