### ISSUE TITLE
🧐[问题]如何在画面中import xlsx格式的文件

### ISSUE THREAD

**Issue by saddamwilson** [ant-design/ant-design-pro#6547]
### 🧐 问题描述

请问一下我再assets目录下放了一个excel文件，但是import导入的时候会提示报错，同样的目录下导入png格式的文件就没有问题，想知道是不是在哪里可以配置这个导入文件的格式呢？

### 💻 示例代码
import wo from '../../../assets/AVB.xlsx'

### 🚑 其他信息

Module parse failed: Unexpected character '' (1:2)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by yanruoxinb** [comment]
您好 请问这个问题你怎么解决的？

**Comment by chenshuai2144** [comment]
@yanruoxinb  放到 public 里用 url 引入，xlsx 引入你有不能看，还是要通过特殊的方法来读取
