### ISSUE TITLE
请问页內侧导航如何实现？

### ISSUE THREAD

**Issue by lifeixiang027** [ant-design/ant-design-pro#655]
请问如下图红框部分的页內侧导航如何实现？

![default](https://user-images.githubusercontent.com/18546370/34788467-9d430466-f675-11e7-9bbe-3d53952a535e.png)

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/#/form/step-form/confirm
和分布表单的实现是一样的。。
你参考一下
