### ISSUE TITLE
保存在public下js文件中的数据如何不被打包到umi.js中🧐[问题]

### ISSUE THREAD

**Issue by xuxuMaster** [ant-design/ant-design-pro#6551]
### 🧐 问题描述

我遇到一个需求，前端被访问的ip是动态，所以我将request.js中的prefix改为从public文件夹中获取，所以我在public中创建了一个js存放ip，可是js中的数据会在打包时一起打包到umi.js中。

### 💻 示例代码
request,js
`import ip from '../../public/dynamicIpAddr';
const prefix = `http://${ip}:8090/XXXXXX`;`

dynamicIpAddr.js
`const ip = '111.222.333.444';
export default ip;`

### 🚑 其他信息

我希望可以通过更改dynamicIpAddr.js中ip的方式实现更改前端访问ip，可是失败了，是我哪里理解错误了吗

**Comment by chenshuai2144** [comment]
不要通过 import访问，通过script 脚本访问即可。
