### ISSUE TITLE
🐛[BUG] topmenu模式下菜单会有像素偏差

### ISSUE THREAD

**Issue by liujiayii** [ant-design/ant-design-pro#6554]
### 🐛 bug 描述
topmenu模式下菜单会有像素偏差

### 📷 复现步骤
yarn create umi

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![QQ截图20200511085834](https://user-images.githubusercontent.com/38902744/81515334-1cf53280-9366-11ea-8614-6505435ba5c8.png)
![QQ截图20200511085847](https://user-images.githubusercontent.com/38902744/81515338-1f578c80-9366-11ea-9506-39785af5efa2.png)

**Comment by liujiayii** [comment]
![QQ截图20200613140109](https://user-images.githubusercontent.com/38902744/84561394-8c53ad00-ad7e-11ea-9f87-3b766c5ea0c7.png)
![QQ截图20200613140123](https://user-images.githubusercontent.com/38902744/84561395-8f4e9d80-ad7e-11ea-9d23-0c6eeee1787e.png)

"@ant-design/pro-layout": "^6.0.0-7" 依然有1px偏差 6.x和5.x都存在这个问题
@chenshuai2144

**Comment by chenshuai2144** [comment]
antd 中会修复
