### ISSUE TITLE
菜单设置hideInMenu依然显示

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6555]
### 🐛 bug 描述
菜单 设置 hideInMenu：true  但是 依然显示了 

### 📷 复现步骤

"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.7",
### © 版本信息

- Ant Design Pro 版本: 
- umi 版本 :"^3.1.2",
- 浏览器环境：谷歌
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/6538

**Comment by chenshuai2144** [comment]
已发版本，可以重新安装了

**Comment by yikyo** [comment]
@chenshuai2144 重装安装哪个？@ant-design/pro-layout 吗？

**Comment by chenshuai2144** [comment]
直接npm update 或者git clean -dfx

**Comment by TnWah** [comment]
@chenshuai2144 pro-layout5.0.8版本正常，升级到5.0.15就又无效了，目前我回退到5.0.8使用

**Comment by TnWah** [comment]
hideInMenu：true设置无效

**Comment by JaniceDong** [comment]
@ant-design-vue/pro-layout": "^1.0.11"维护的老版本的项目，是不是hideinmenu这个属性就用不了了
