### ISSUE TITLE
form 的 initialValues 属性无效

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#6559]
form 的 initialValues 属性无效,
form里面加了{initialValues.属性}，可以显示。

太难了！

![image](https://user-images.githubusercontent.com/32530210/81561624-0a124a80-93c6-11ea-9402-fbe1f3dd7245.png)
![image](https://user-images.githubusercontent.com/32530210/81562192-fe735380-93c6-11ea-8e85-07335973ee4f.png)

**Comment by joesdu** [comment]
![image](https://user-images.githubusercontent.com/13188169/81572869-582f4a00-93d6-11ea-8322-9c94a3542938.png)
我是这么用的,没有问题.

**Comment by huntdream** [comment]
Drawer 关闭的时候销毁Form实例，或者手动`setFieldsValue`

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/81627273-614d0500-9430-11ea-82b1-3f47e2a4c2ac.png)

![image](https://user-images.githubusercontent.com/32530210/81627361-98bbb180-9430-11ea-8623-e7f877a3fa22.png)

现在显示是可以显示了，console.出现这个鬼

**Comment by huntdream** [comment]
`updateForm.setFieldsVlaue`需要放在`useEffect`里面
```
useEffect(()=>{
  updateForm.setFieldsValue(initValues)
}, [myinitialValues])
```

你放在外面的话，第一次调用的时候组件还没有渲染，Form还没有实例化

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/81629166-1f728d80-9435-11ea-80ea-43734bb7aa09.png)
![image](https://user-images.githubusercontent.com/32530210/81629244-47fa8780-9435-11ea-9fa5-0d058cce36eb.png)



终于，不报错了！！！感谢，感谢！
昨天这个鬼，百度到半夜2点 。不如你这一句话。
我太难了！

**Comment by huntdream** [comment]
多看看文档，熟悉一下组件就好啦，靠百度还不如靠自己 😄

**Comment by xyzabc0004** [comment]
有时候，也要跟对 对象 😆,看师傅  @huntdream @
