### ISSUE TITLE
🐛[BUG] V5关闭不了国际化

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6561]
### 🐛 bug 描述

关闭  config.ts 中

 layout: {
    name: 'Ant Design Pro',
    locale: false,
 },

关闭 defaultSettings.ts 中
  menu: {
    locale: false,
  },
都不起作用

同时在console下还报如下错误：

![image](https://user-images.githubusercontent.com/18542211/81569561-0684c080-93d2-11ea-8830-822315708b4e.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by FFJUN** [comment]
我也是这样，关了报错

**Comment by kaoding** [comment]
同时在console下还报如下错误：此bug已修复，但V5还是关闭不了国际化

![image](https://user-images.githubusercontent.com/18542211/81569561-0684c080-93d2-11ea-8830-822315708b4e.png)

**Comment by FFJUN** [comment]
怎么修复的 ，我的还是报错

**Comment by kaoding** [comment]
> 怎么修复的 ，我的还是报错

要重新 install 一下

https://github.com/umijs/route-utils/commit/b0830e12b3410a6eddc696295ddceb6ac813f456

**Comment by chenshuai2144** [comment]
看来是 umijs/route-utils 的 bug

**Comment by CodingZJ** [comment]
我也是，楼主解决没

**Comment by kaoding** [comment]
> 我也是，楼主解决没

我解决不了，等陈大师亲自解决。

**Comment by chenshuai2144** [comment]
close by 
https://github.com/umijs/route-utils/commit/01e9ba1363b9a9a1ac7049a223d07b8f0c566930

**Comment by 123wangjinfeng** [comment]
> 怎么修复的 ，我的还是报错
