### ISSUE TITLE
antd pro 的左侧菜单栏问题

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6562]
### 🧐 问题描述
antd pro 的左侧菜单栏我能否自己用antd的Menu组件去实现，但是我需要用pro的权限功能 ，不知道这样会不会影响到添加权限功能
![image](https://user-images.githubusercontent.com/27960630/81628009-146a2e00-9432-11ea-8f23-a7fdd8f10b80.png)
这是我自己生成的左侧菜单栏

**Comment by chenshuai2144** [comment]
可以直接用 https://umijs.org/plugins/plugin-access
这样就不用担心了

**Comment by lovesL** [comment]
@chenshuai2144  只用这个可以了？  还需不需要authority.js  Authority.js用到

**Comment by chenshuai2144** [comment]
不需要了，变成一个插件了

**Comment by lovesL** [comment]
@chenshuai2144  谢谢你在周末还帮忙解答我的疑惑
