### ISSUE TITLE
🐛[BUG]Logout後還是可以進入頁面

### ISSUE THREAD

**Issue by hubertmok** [ant-design/ant-design-pro#6564]
### 📷 复现步骤

在官方DEMO上, 同樣出現這問題
https://preview.pro.ant.design/dashboard/analysis

按退出登錄按鈕
![image](https://user-images.githubusercontent.com/5517502/81631232-fa344e00-9439-11ea-8e24-404e258bceac.png)

在沒有任何帳號密碼資訊情況下
![image](https://user-images.githubusercontent.com/5517502/81631306-1f28c100-943a-11ea-9be7-702d86993944.png)

將URL標注的部分刪掉, 即只保留 https://preview.pro.ant.design 這部分, 按回車還是可以進入頁面
![image](https://user-images.githubusercontent.com/5517502/81631380-4ed7c900-943a-11ea-8d59-b70442fe9a13.png)

### 🏞 期望结果

無法login
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TianenPang** [comment]
在 `SecurityLayout` 中做判断试试， `SecurityLayout`  中 有一个 `const isLogin`
