### ISSUE TITLE
🧐[问题]请问开头PRO页面的信息在哪个文件修改？

### ISSUE THREAD

**Issue by afr751116** [ant-design/ant-design-pro#6567]
请问，Pro进入页面时，那个待跳转的页面在哪修改信息？
![image](https://user-images.githubusercontent.com/57131579/81637057-f4456980-9447-11ea-9ce5-27fb82931ea8.png)

**Comment by chenshuai2144** [comment]
look https://github.com/ant-design/ant-design-pro/blob/d07cb50f1c90f971c8e8c8544c04fa672e4f5d86/src/pages/document.ejs
