### ISSUE TITLE
🧐[问题]用区块跟模板自动生成的代码language不是JavaScript，而是TypeScript。

### ISSUE THREAD

**Issue by yangcansheep** [ant-design/ant-design-pro#6569]
### 🧐 问题描述
用区块跟模板自动生成的代码language是TypeScript。而创建工程时选择的language是JavaScript。

### 💻 建议

是否可以在自动生成模板或模块的时候提供language的选项，自动生成？

**Comment by saddamwilson** [comment]
同问

**Comment by kevinzl** [comment]
同问

**Comment by chenshuai2144** [comment]
有个自动推算，你可以删除 tsconfig 来避开它
