### ISSUE TITLE
单独使用ant-design-pro中的部分组件出现样式重复

### ISSUE THREAD

**Issue by clverpanda** [ant-design/ant-design-pro#657]
我在create-react-app创建的项目中使用了antd以及ant-design-pro，并且只使用了ant-design-pro的一些组件。
因为要配置使用本地的图标所以使用react-app-wired配置了如下
```
config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config);
```
可是在ant-design-pro/lib/PageHeader中会引入：
```
require('antd/lib/tabs/style/css');
require('antd/lib/breadcrumb/style/css');
```
其中antd/lib/tabs/style/css 会引入
```
require('../../style/index.css');
require('./index.css');
```
导致在加载了antd的less的样式之后又加载了css的样式。

**Comment by afc163** [comment]
对，对于 less 和 css 混用目前没有特别好的办法，有没有什么建议。

**Comment by dingyiming** [comment]
ant-design-pro 的样式覆盖了基于react-app-wired-less自定义的样式,很尴尬

**Comment by lyingd** [comment]
这个问题有进展吗，现在生产打包的css是双倍大小，antd的样式有双份，而且第二份出现在自定义样式之后，导致部分自定义样式无法覆盖antd的样式。

**Comment by fritx** [comment]
我发现打包后，部分antd的样式又反过来覆盖了自己重写的样式，不知道是不是antd或antd-pro的问题，还没找着

**Comment by lusess123** [comment]
全部使用less 不可以吗

**Comment by chenshuai2144** [comment]
#1317

**Comment by 750973092** [comment]
还是没有解决啊，用umi创建pro的时候引用单独组件@ant-design/pro-layout还是重复打包两份css;好抓狂；
![image](https://user-images.githubusercontent.com/22766860/68996698-6ba2a200-08d8-11ea-8a95-8f04a73d2520.png)

**Comment by wingsico** [comment]
这没有丝毫进展吗 @afc163

**Comment by wingsico** [comment]
> 这没有丝毫进展吗 @afc163

这个问题在 pro-components 单独使用时也存在

**Comment by chenshuai2144** [comment]
一般都是因为 打包了一份lib 一份 css 导致的，你检查一下你的代码

**Comment by fanck0605** [comment]
> > 这没有丝毫进展吗 @afc163
> 
> 这个问题在 pro-components 单独使用时也存在

最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入

我就只使用了按需引入(和 pro-components 的导入方式保持一致，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常

```jsx
import 'antd/es/[component-name]/style'
```

**Comment by projectcss** [comment]
> > > 这没有丝毫进展吗 @afc163
> > 
> > 
> > 这个问题在 pro-components 单独使用时也存在
> 
> 最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入
> 
> 我就只使用了按需引入(**和 pro-components 的导入方式保持一致**，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常
> 
> ```js
> import 'antd/es/[component-name]/style'
> ```



> > > 这没有丝毫进展吗 @afc163
> > 
> > 
> > 这个问题在 pro-components 单独使用时也存在
> 
> 最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入
> 
> 我就只使用了按需引入(**和 pro-components 的导入方式保持一致**，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常
> 
> ```js
> import 'antd/es/[component-name]/style'
> ```
pro-components怎么按需引入的

**Comment by fanck0605** [comment]
> > > > 这没有丝毫进展吗 @afc163
> > > 
> > > 
> > > 这个问题在 pro-components 单独使用时也存在
> > 
> > 
> > 最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入
> > 我就只使用了按需引入(**和 pro-components 的导入方式保持一致**，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常
> > ```js
> > import 'antd/es/[component-name]/style'
> > ```
> 
> > > > 这没有丝毫进展吗 @afc163
> > > 
> > > 
> > > 这个问题在 pro-components 单独使用时也存在
> > 
> > 
> > 最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入
> > 我就只使用了按需引入(**和 pro-components 的导入方式保持一致**，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常
> > ```js
> > import 'antd/es/[component-name]/style'
> > ```
> 
> pro-components怎么按需引入的

pro-components 不需要按需引入

可能是我没说清楚，我是指和 pro-components 按需引入 antd 的方式一样，进行 antd 的按需引入。

比如 pro-components 引入的是antd 的 es 文件夹下的 modules，而我们自己引入的是 lib 文件夹下的 modules，这样就不可以，styles 会被打包多次，我们自己要也引入 es 文件夹下 modules，这样子就不会被多次打包了。

**Comment by projectcss** [comment]
> > > > > 这没有丝毫进展吗 @afc163
> > > > 
> > > > 
> > > > 这个问题在 pro-components 单独使用时也存在
> > > 
> > > 
> > > 最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入
> > > 我就只使用了按需引入(**和 pro-components 的导入方式保持一致**，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常
> > > ```js
> > > import 'antd/es/[component-name]/style'
> > > ```
> > 
> > 
> > > > > 这没有丝毫进展吗 @afc163
> > > > 
> > > > 
> > > > 这个问题在 pro-components 单独使用时也存在
> > > 
> > > 
> > > 最近在 vite 项目里也尝试使用了 `pro-components`，只要导入方式正确，css **似乎**不会被重复引入
> > > 我就只使用了按需引入(**和 pro-components 的导入方式保持一致**，用 babel 插件就行了)，导入了 `antd/es/[component-name]/style/index.js`(**es** 目录下的)，目前一切工作正常
> > > ```js
> > > import 'antd/es/[component-name]/style'
> > > ```
> > 
> > 
> > pro-components怎么按需引入的
> 
> pro-components **不需要按需引入**
> 
> 可能是我没说清楚，我是指和 pro-components 按需引入 antd 的方式一样，进行 antd 的按需引入。
> 
> 比如 pro-components 引入的是antd 的 es 文件夹下的 esmodules，而我们自己引入的是 lib 文件夹下的 commonjs，这样就不可以，styles 会被打包多次，我们自己要也引入 es 文件夹下 esmodules，这样子就不会被多次打包了。

但是我们在使用pro-components时都没有引入他的css文件，应该是babel import-plugin帮我们引入的，这应该怎么去改呢

**Comment by fanck0605** [comment]
![image](https://user-images.githubusercontent.com/28819315/164366902-57710986-6af4-48eb-b2dc-17e48fd3541b.png)

不要去改它啊，自己引 antd 的时候注意一下就好了

**Comment by projectcss** [comment]
> 

嗯嗯是的，也就是说我们用antd的时候需要自己手动去引入antd/es/[组件]/styles下的样式是吗

**Comment by fanck0605** [comment]
> > 
> 
> 嗯嗯是的，也就是说我们用antd的时候需要自己手动去引入antd/es/[组件]/styles下的样式是吗

对，只要 antd 按需引入就行了，然后记得是 es 文件夹下的。

**Comment by projectcss** [comment]
> > > 
> > 
> > 
> > 嗯嗯是的，也就是说我们用antd的时候需要自己手动去引入antd/es/[组件]/styles下的样式是吗
> 
> 对，只要 antd 按需引入就行了，然后记得是 es 文件夹下的。

这个babel-plugin-import后面能提供一个配置吗，现在使用这个插件都是从lib下引入的，提供个配置让我们自定义去引入es/lib下的文件

**Comment by fanck0605** [comment]
这个不是本来就有配置项吗。

```js
  {
    "libraryName": "antd",
    "libraryDirectory": "es", // 修改这里
    "style": true
  }
```

**Comment by isliqian** [comment]
<img width="419" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/29324161/dc93c0d1-81c2-4be2-8660-9b5d17b8eec4">

切换主题，因为重复样式，导致不生效。。
