### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by Topthinking** [ant-design/ant-design-pro#6571]
![image](https://user-images.githubusercontent.com/13382821/81686722-3fcd3700-948b-11ea-8112-a818f226941c.png)

**Comment by TianenPang** [comment]
使用 `yarn create umi` 试试

**Comment by Topthinking** [comment]
> 使用 `yarn create umi` 试试

不行，一样的错误

**Comment by TianenPang** [comment]
> > 使用 `yarn create umi` 试试
> 
> 不行，一样的错误

可能是环境的问题？

**Comment by chenshuai2144** [comment]
升级一下 node 和 ts 的版本就好了

**Comment by Topthinking** [comment]
> 升级一下 node 和 ts 的版本就好了

啥意思，具体到多少版本，都是最新的版本么

**Comment by Topthinking** [comment]
@chenshuai2144 我升级到最新版本，还是不行啊
![image](https://user-images.githubusercontent.com/13382821/82172046-a921cf80-98fb-11ea-9da2-83ab1f97b8d7.png)

**Comment by chenshuai2144** [comment]
这个错误是eslint抛出的，删掉全局的eslint?

**Comment by Topthinking** [comment]
> 这个错误是eslint抛出的，删掉全局的eslint?

应该不是这个原因吧，我全局也没有eslint，目前看上去选择了 ant-design-pro 这个模板，然后就执行报错了
