### ISSUE TITLE
🐛[BUG] Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()

### ISSUE THREAD

**Issue by qsk617** [ant-design/ant-design-pro#6572]
### 🐛 bug 描述
PRO4.0版本
设置
layout: 'topmenu',
浏览器就会报错。
谢谢~

`devScripts.js:5035 
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ResizeObserver`.
    in ConnectFunction (at BasicLayout.tsx:158)
    in ResizeObserver (created by RightContent)
    in div (created by RightContent)
    in div (created by RightContent)
    in RightContent (created by TopNavHeader)`

**Comment by aarabmed** [comment]
i encountered the same problem today too, the app is rendering and working fine but the red warning on the console is annoying me :/ , the issue is in the `RightConent `component , when i remove it in `BasicLayout.tsx` , poof the warning is gone,  however the `RightContent` is required,

**Comment by websmallrabbit** [comment]
i meet the  isuure  too

**Comment by aarabmed** [comment]
inside `RightContent ` component when i dont use `connect ` function the warning disappears, im start to wonder if there is an issue with connect ? any help is appreciated

**Comment by aarabmed** [comment]
hmmm, after so many testing , i have noticed that if you set the layout menu to `sidemenu `inside `DefaultSettings`  the warning disappear however it will show if you set it to `topmenu` , i have tested that on the latest ant design pro repository and i got the same result.

**Comment by lovesmilesha** [comment]
the same for me,when i use topmenu
![image](https://user-images.githubusercontent.com/181152/82428675-6f98c200-9abd-11ea-8ae5-8d90470e921e.png)

**Comment by sixersun** [comment]
同样遇到这个问题

**Comment by aarabmed** [comment]
the workaround that you might not like it is to give away the use of `Connect `method and set layout and them variables manually, instead of getting them from  `DefaultSettings `using `props ` and `connect `

**Comment by 13007640364** [comment]
我也遇到了这个问题

**Comment by ChenWeihua123** [comment]
同样的问题

**Comment by hbshun** [comment]
同问

**Comment by kaoding** [comment]
重新 yarn install

**Comment by hbshun** [comment]
> 重新 yarn install

你是认真的吗？

**Comment by synebula** [comment]
> > 重新 yarn install
> 
> 你是认真的吗？

yarn upgrade-interactive --lastest 更新下@ant-design/pro-layout包

**Comment by hcyfreedom** [comment]
导出子组件的时候，用React.forwardRef包一下

**Comment by chenshuai2144** [comment]
close by https://github.com/dvajs/dva/issues/2222

**Comment by MagicHacker** [comment]
导出组件的时候使用withRouter了吧？类组件包装成函数组件了

**Comment by bhd119** [comment]
in ConnectFunction (at BasicLayout.tsx:158)
这行报错，BasicLayout不能用connect。使用export default class BasicLayout
