### ISSUE TITLE
👑 [需求] 打开查询表格的时候，是否支持设置默认查询条件？

### ISSUE THREAD

**Issue by rocklee0098** [ant-design/ant-design-pro#6573]
### 🧐 问题描述
默认工程里面的 table-list 页面，希望可以在打开的时候能设置默认的查询条件，并且显示在查询条件表单中

### 💻 示例代码

尝试了使用 initialValue, 可以正常显示在查询条件表单空间里，但是第一次进入时的默认查询并不会带上这个条件

![image](https://user-images.githubusercontent.com/53533904/81740804-20a4c880-94d0-11ea-8e29-7e34dffc7f1e.png)

![image](https://user-images.githubusercontent.com/53533904/81741143-ab85c300-94d0-11ea-85e8-df52709f3457.png)

请问有办法实现打开时自带默认值吗？ 如果有办法的话，请教教我，谢谢🙏

**Comment by rocklee0098** [comment]
btw : 还尝试过 renderFormItem , 自己创建表单空间并填上默认值，同样是打开页面的时候会有显示，但是第一次查询不会带上默认值

**Comment by onlymindofakmd** [comment]
这个最后解决了吗？

**Comment by chenshuai2144** [comment]
使用 initValues 即可
