### ISSUE TITLE
🐛切换黑色主题，页面没反应

### ISSUE THREAD

**Issue by xcj01010203** [ant-design/ant-design-pro#6574]

**Comment by xcj01010203** [comment]
![image](https://user-images.githubusercontent.com/20202711/81758871-a5eea400-94f5-11ea-9f3c-a026a19a7f39.png)

**Comment by imhxc** [comment]
这个问题有人解决了吗？
我看了下，是因为编译后的 dark.css 没有编译对。
好像是用了这个插件 `umi-plugin-antd-theme` ，但是我没看懂怎么读的 Antd 的 dark 主题文件。
求助。。。

**Comment by chenshuai2144** [comment]
重新部署了一下
