### ISSUE TITLE
Umi UI 资产界面没有antd区块🧐[问题]

### ISSUE THREAD

**Issue by IslandGray** [ant-design/ant-design-pro#6576]
### 🧐 问题描述

在Umi UI的资产界面添加区块时，antd的区块列表居然是空的？？
官方文档里演示似乎是有的，是因为我是用js的原因吗

### 💻 示例代码

null

### 🚑 其他信息

<img width="1416" alt="截屏2020-05-13 17 38 38" src="https://user-images.githubusercontent.com/22031964/81796861-96e11380-9540-11ea-9e96-86c9b06a4783.png">

**Comment by chenshuai2144** [comment]
看来是网络问题，重启应该就可以了

**Comment by Start-from-zero** [comment]
> 看来是网络问题，重启应该就可以了

你好  我也遇到了这个问题重启也没有解决
