### ISSUE TITLE
🧐[问题]table列中render一个音频播放组件audio问题

### ISSUE THREAD

**Issue by 1334310385** [ant-design/ant-design-pro#6579]
### 🧐 问题描述
我table列中render一个音频播放组件audio，页面刚加载出来时组件是正常可以播放录音，页面过一会这个组件会自动置灰无法操作，页面中其他地方正常，只有这个组件的这一列是置灰状态。

### 💻 示例代码
    {
      dataIndex: 'recUrl',
      title: '播放录音',
      align: 'center',
      width: 260,
      render: (text, record) => {
        return (
          <div className={record.callResult === '07' ? divStyle.audioDiv : ''}>
            <audio
              src={text}
              controls="controls"
              controlslist="nodownload"
              style={{ width: '100%' }}
            />
            <span className={divStyle.audioDisable} />
          </div>
        );
      },
    },

### 🚑 其他信息

1、页面刚加载时
![image](https://user-images.githubusercontent.com/48980855/81881873-e157a400-95c3-11ea-94df-a569bd5d7e1d.png)
2、页面过一会组件自动置灰
![image](https://user-images.githubusercontent.com/48980855/81881901-f0d6ed00-95c3-11ea-8021-08e30e354b59.png)

**Comment by chenshuai2144** [comment]
看起来是audio 没有成功加载，和 antd 无关，可以看看控制台是不是加载出错了
