### ISSUE TITLE
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops

### ISSUE THREAD

**Issue by gongzili456** [ant-design/ant-design-pro#658]
![image](https://user-images.githubusercontent.com/6082335/34806426-c8a52164-f6bd-11e7-8959-a982be55ebbc.png)

另一个严重的问题就是, 部署到线上服务后, 打开网页导致电脑(Mac)风扇狂转, 卡死等现象.
本地开发没问题

**Comment by chenshuai2144** [comment]
额 清除一下各种缓存。。。
这是因为页面频繁重定向的原因。

**Comment by lyingd** [comment]
请问这个问题是否有修复计划，我这里也经常出现。

**Comment by chenshuai2144** [comment]
@lyingd  你是最新版本吗？ 
![image](https://user-images.githubusercontent.com/8186664/34855492-f62c3646-f77a-11e7-8257-fa87c30c312b.png)

清楚这个就解决问题。。。

**Comment by lyingd** [comment]
用的昨天早上的master版本，chrome版本是65.0.3298.4的dev版（64位）
清楚数据后，仍然无法解决

**Comment by chenshuai2144** [comment]
这就很尴尬了
没有任何改动？

**Comment by lyingd** [comment]
想起了，路由有点变动，改回去后，问题解决了……

**Comment by chenshuai2144** [comment]
你改了什么？  这个应该是权限造成的。。 我看看

**Comment by lyingd** [comment]
我用的0.3的路由，不想按1.0全部重写，就写了一个转换的方法。
但我们有修改0.3的路由，强调了路径的表达方式，nav里所有path都加了前置斜杠‘／’，我怀疑与这个斜杠判断错误有关

**Comment by chenshuai2144** [comment]
看来就是这个原因了。。
#631 应该可以解决这个问题。用了react-router同款匹配工具

**Comment by gongzili456** [comment]
当 local storage中的 用户身份信息 undefined 的时候就会出现这种情况，因为点击logout 的时候 设置为了undefined

**Comment by chenshuai2144** [comment]
。。。。。。。。。。
undefined 还是 ‘undefined’？

**Comment by heyuxian** [comment]
我也有这个问题， 测了下，只要 `antd-pro-authority` 的值不是系统内置的三种角色，就会出现这个问题

**Comment by chenshuai2144** [comment]
怎么会出现第四种情况？

**Comment by jimmy-online** [comment]
我也遇到相同的方法，我临时的解决办法是修改 CheckPermissions.js 
const checkPermissions = (authority, currentAuthority, target, Exception) => {
第一行添加：
`currentAuthority = getAuthority();`

**Comment by LydiaAgute** [comment]
我发现localStorage里面antd-pro-authority值为'undefined',会出现上述错误,重启也无法解决.
只有控制台手动设置window.localStorage.setItem('antd-pro-authority', 'guest');

**Comment by chenshuai2144** [comment]
新的master已经完全解决这个问题了
