### ISSUE TITLE
升级到新版本后，会出现node_modules/umi/types"”没有导出的成员“Dispatch”等🧐[问题]

### ISSUE THREAD

**Issue by Anberm** [ant-design/ant-design-pro#6581]
### 🧐 问题描述

升级到新版本 pro4 umi3 后
1.运行yarn start
2.原来代码上正常的引用，会显示警告 node_modules/umi/types"”没有导出的成员“Dispatch history connect” 等
没找到合适的解决方式，所以来此请教

**Comment by jiangf0775** [comment]
同问

**Comment by hanxinimm** [comment]
一样的问题，报错

**Comment by chenshuai2144** [comment]
```
 "paths": {
      "@/*": ["./src/*"],
      "@@/*": ["./src/.umi/*"]
    }
```
这个配置了吗，是必须的

**Comment by Anberm** [comment]
> ```
>  "paths": {
>       "@/*": ["./src/*"],
>       "@@/*": ["./src/.umi/*"]
>     }
> ```
> 
> 这个配置了吗，是必须的

配置了，直接拉取当前仓储也会出现这个问题

**Comment by chenshuai2144** [comment]
拉取之后去执行 依赖安装然后 执行 npm run start，就会生成依赖。

试了试 window 和 mac 都是可以生成类型的。

**Comment by Liu-Ya** [comment]
> 拉取之后去执行 依赖安装然后 执行 npm run start，就会生成依赖。
> 
> 试了试 window 和 mac 都是可以生成类型的。

是可以生成，但没一定哪一次start之后就找不到，查看.umi下文件是存在导出的，有点拼运气的意思，每次碰到都要尝试重新打开VSCode，重新start，不停尝试，偏偏没法提供稳定的重现，令人头大。

配置成
```
"paths": {
      "@/*": ["src/*"],
      "@@/*": ["src/.umi/*"]
    }
```
出错的概率会更小，但不能在工作区中使用。
搜索下pro和umi的issues，类似问题很多 umijs/umi#4164 umijs/umi#4360 umijs/umi#4341 #6568 #6271 ，不是用户配置问题，希望你们重视

**Comment by Anberm** [comment]
> > 拉取之后去执行 依赖安装然后 执行 npm run start，就会生成依赖。
> > 试了试 window 和 mac 都是可以生成类型的。
> 
> 是可以生成，但没一定哪一次start之后就找不到，查看.umi下文件是存在导出的，有点拼运气的意思，每次碰到都要尝试重新打开VSCode，重新start，不停尝试，偏偏没法提供稳定的重现，令人头大。
> 
> 配置成
> 
> ```
> "paths": {
>       "@/*": ["src/*"],
>       "@@/*": ["src/.umi/*"]
>     }
> ```
> 
> 出错的概率会更小，但不能在工作区中使用。
> 搜索下pro和umi的issues，类似问题很多 [umijs/umi#4164](https://github.com/umijs/umi/issues/4164) [umijs/umi#4360](https://github.com/umijs/umi/issues/4360) [umijs/umi#4341](https://github.com/umijs/umi/issues/4341) #6568 #6271 ，不是用户配置问题，希望你们重视

@chenshuai2144 的确，在拉取项目后 yarn, 然后yarn start ，是生成了依赖项，但是 vscode 并不认可，会报出找不到的提示，这并不影响build 但是很影响开发体验，望重视

**Comment by Liu-Ya** [comment]
@Anberm reopen?

**Comment by Anberm** [comment]
> @Anberm reopen?

没权限

**Comment by Liu-Ya** [comment]
> > @Anberm reopen?
> 
> 没权限

我重开个

**Comment by LbhFront-end** [comment]
同问

**Comment by Anberm** [comment]
@Liu-Ya @LbhFront-end  vscode 快捷键ctrl+shift+p ，重启ts服务器可以解决
![image](https://user-images.githubusercontent.com/34148806/83584665-678b5880-a57a-11ea-9528-963898610c1a.png)

**Comment by LbhFront-end** [comment]
> @Liu-Ya @LbhFront-end vscode 快捷键ctrl+shift+p ，重启ts服务器可以解决
> ![image](https://user-images.githubusercontent.com/34148806/83584665-678b5880-a57a-11ea-9528-963898610c1a.png)

已解决 谢谢

**Comment by LbhFront-end** [comment]
> > @Liu-Ya @LbhFront-end vscode 快捷键ctrl+shift+p ，重启ts服务器可以解决
> > ![image](https://user-images.githubusercontent.com/34148806/83584665-678b5880-a57a-11ea-9528-963898610c1a.png)
> 
> 已解决 谢谢

发现这个方法只能解决单个文件，其他文件还是会有一样的问题 好像不是很友好

**Comment by yHuChang** [comment]
刚接触react  我这是因为models 没有导出 
![image](https://user-images.githubusercontent.com/40140833/89894652-008abf80-dc0d-11ea-836f-0b3f3470d2b6.png)
可能加载时找不到model ，plugin-dva就没加载到.umi里 大家可以看看是不是这个问题

**Comment by yHuChang** [comment]
我这里是models里的文件没有 export default。 可能加载.umi时找不到model ，就没加载plugin-dva 。可以看看models 格式的问题
