### ISSUE TITLE
🧐[帮助？] 寻求 Gantt （甘特图 ）React 组件

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6582]

**Comment by chenshuai2144** [comment]
本来想让你试试 https://charts.ant.design/
看了一圈发现 g2 中也没有，google 里都是 excel 的

**Comment by kaoding** [comment]
这个我也提给了 G2plot，Gantt （甘特图 ）左边类似 antd 组件，右边类似 antdv图形，是一个相对综合的组件需求。所以看一看这种需求是怎么实现比较好，没有现成的组件也可以给一个实际建议。主要使用场景就是计划和排程。

**Comment by s464446877** [comment]
dhtmlxgantt

**Comment by kaoding** [comment]
> dhtmlxgantt

我看一看，谢谢！

**Comment by jkiss** [comment]
[react-gantt](https://www.npmjs.com/package/@j.k.bi/react-gantt)
