### ISSUE TITLE
🐛[BUG] 在app.js中服务端动态加载路由配置icon不生效

### ISSUE THREAD

**Issue by luyi18** [ant-design/ant-design-pro#6583]
### 🐛 bug 描述
在app.js中服务端动态加载路由配置icon为字符串不生效，如果配置成icon 为ReactNode ,由于pro-layout5.0.8中有兼容包的依赖，会报uppercase的错误，也不生效

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
antd 4.0.0
pro-layout5.0.8
- umi 版本
3.1.1
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon
看看这个 demo

**Comment by afc163** [comment]
pro 的文档要把 prolayout 也同步一份过去，现在很多需求都在 prolayout 上。

**Comment by luyi18** [comment]
@chenshuai2144 并不是menu，加载menu是可以实现的。而且我这个问题是在app.js中动态加载路由表
