### ISSUE TITLE
🧐forwardRef结合dva connect后，父组件拿不到子组件ref

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6586]
### 🧐 问题描述

forwardRef结合dva connect后，父组件拿不到子组件ref

### 💻 示例代码
子组件Test
`export default connect(({ test, loading }) => ({`
 ` currentUser: test.currentUser,`
`}))(forwardRef(Test));`

父组件

`<Test ref={testRef}/>`

然后testRef.current一直为undefined

**Comment by chenshuai2144** [comment]
`const page =(props,ref)` 你需要把ref 挂到具体的 dom 上，不是只要 forwardRef 就好了

可以看官方的 demo 来学习一下
https://reactjs.org/docs/forwarding-refs.html

**Comment by ISBN9527** [comment]
我就是这样写的啊。还是拿不到
子组件 Test
```
const Test = (props,ref)=>{
   return 'test'
}
```

```
export default connect(({ test, loading }) => ({
currentUser: test.currentUser,
}))(forwardRef(Test));
```
