### ISSUE TITLE
🧐[问题]为什么按官方步骤构建出的版本为1.0.0

### ISSUE THREAD

**Issue by elvinest** [ant-design/ant-design-pro#6587]
请教一下大家，按官方文档
npm create umi / yarn create umi (两者都尝试过)

npm install
npm start

一切都正常，但命令提示的ant-design-pro版本是1.0.0

![QQ截图20200515113950](https://user-images.githubusercontent.com/3347361/82009095-f6eecb80-96a0-11ea-8370-4f4ec96a0174.png)

谢谢大家!

**Comment by afc163** [comment]
#6537
