### ISSUE TITLE
创建项目中途报错🐛[BUG]

### ISSUE THREAD

**Issue by tangweicuit** [ant-design/ant-design-pro#6588]
### 🐛 bug 描述

 ①无论选择js版本还是ts版本安装的都是ts版本②配置好一切之后，开始安装项目，项目没有安装成功，中途报错，但是报错之后项目中已经存在文件，但是有些不该存在的文件也出现了

![image](https://user-images.githubusercontent.com/49397526/82021836-2bbd4b80-96be-11ea-9d44-112e63c6b6f7.png)
![image](https://user-images.githubusercontent.com/49397526/82022149-bd2cbd80-96be-11ea-97ab-b8fcfed55d61.png)

**Comment by chenshuai2144** [comment]
建议使用 ts，看起来是全局的依赖问题
