### ISSUE TITLE
dva 相关问题

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6589]
### 🧐 问题描述
antd  pro 把dva 封装后  我在哪里写onReducer方法   如果我当前用户退出登陆 我需要把所有的dva state 清空

**Comment by joesdu** [comment]
他封装的只是导出方式变了,用法还是一样的.

**Comment by chenshuai2144** [comment]
@joesdu 能给个 demo 吗？ 我没用过 dva 的高级用法

**Comment by joesdu** [comment]
> @joesdu 能给个 demo 吗？ 我没用过 dva 的高级用法

好的,我等下整理一下我原有项目,提个demo项目到我的GitHub,然后再来给链接.

**Comment by joesdu** [comment]
https://github.com/joesdu/react-typescript-umi-dva-demo

这个是我整理后的用法,其中login页面用的全局的model,另一个页面用的组件自己的model.可以参考下,我也不知道我是不是高级用法,反正我就是这么用了.🤣
