### ISSUE TITLE
🧐pro-table能否自定义查询项？

### ISSUE THREAD

**Issue by wp88** [ant-design/ant-design-pro#6590]
### 🧐 问题描述
pro-table能否自定义头部的筛选项，如某些项才需要筛选、某些项是以下拉框形式筛选

### search

| 属性 | 描述 | 类型 | 默认值 |
| --- | --- | --- | --- |
| searchText | 查询按钮的文本 | string | 查询 |
| resetText | 重置按钮的文本 | string | 重置 |
| submitText | 查询按钮的文本 | string | 重置 |
| collapseRender | 收起按钮的 render | `(collapsed: boolean,showCollapseButton?: boolean,) => React.ReactNode` | - |
| collapsed | 是否收起 | boolean | - |
| onCollapse | 收起按钮的事件 | `(collapsed: boolean) => void;` | - |
| optionRender | 操作栏的 render | `(( searchConfig: Omit<SearchConfig, 'optionRender'>, props: Omit<FormOptionProps, 'searchConfig'>, ) => React.ReactNode) \| false;` | - |

在文档里面没有找到自定义筛选的属性，请问该属性可以自定义吗？
### 🚑 其他信息
version:
pro-table:2.2.7

![image](https://user-images.githubusercontent.com/15691426/82039419-87e09980-96d7-11ea-8b99-3b36970deb95.png)

**Comment by chenshuai2144** [comment]
看看这个 demo，重点是 renderFormItem 这个 api

https://protable.ant.design/search#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8

**Comment by yuandalu** [comment]
> 看看这个 demo，重点是 renderFormItem 这个 api
> 
> https://protable.ant.design/search#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8

在这里追问一个问题，如果在外面额外控制查询的时候，还想走ProTable的param那套关系，我发现必须配一个列，，但是配置一个列就会导致原有的查询表单会显示一个查询框，我尝试隐藏这个框，比如search=false，或者renderFormItem=null，都会导致param里这个查询字段消失，能否可以支持param里面带着这个字段，且自带的查询框里不显示这个表单，这样我在外面其他位置控制；目前的笨办法是renderFormItem=<></>，但是这样会占位置，倒是即使表单不满足换行也会因为其他隐藏的表单占用了位置而换行
![image](https://user-images.githubusercontent.com/3860040/125583599-125d28a5-93a1-47ea-89cc-153b7698d560.png)
