### ISSUE TITLE
👑 [需求] umi3.2即将来临，支持ssr。antD pro什么时候支持

### ISSUE THREAD

**Issue by aLIEzsss4** [ant-design/ant-design-pro#6591]
### 🥰 需求描述

使用了umi@3.2.0-beta.8 测试了一下 ，开启ssr之后跟antd pro不是完美结合

### 🚑 其他信息

ERROR [SSR] ReferenceError: localStorage is not defined
![image](https://user-images.githubusercontent.com/24380830/82040420-24576b80-96d9-11ea-96c4-4df916330abd.png)

**Comment by afc163** [comment]
中后台系统没必要上 SSR。

**Comment by chenshuai2144** [comment]
中后台系统对速度要求不是很搞，我们的某些组件并不支持 SSR, 不过如果成本很低我们会做一些尝试

我们现在的主要精力还是在增加编译速度和开发速度

**Comment by Zach-Lu** [comment]
> 中后台系统对速度要求不是很搞，我们的某些组件并不支持 SSR, 不过如果成本很低我们会做一些尝试
> 
> 我们现在的主要精力还是在增加编译速度和开发速度

其实我们现在一个项目是用的antd pro，但是前台类似于一个社区了。一般用户会在社区登陆，然后转到后台直接使用。所以我们想，直接在antd pro上把社区和中后台都做了，唯一的问题就是，社区部分的SEO确实难以解决。

**Comment by chenshuai2144** [comment]
可以给社区部分专门做 ssr 的，你在 layout 中加个 if(!isBorwer) return null

这样就不会加载别的 ssr 了
