### ISSUE TITLE
移除国际化后报错

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/ant-design-pro#6592]
1: 移除国际化后，删掉local文件
2.控制台一直显示The current popular language does not exist, please check the locales folder!

**Comment by chenshuai2144** [comment]
清空一下 localStorage 并且 在 config 中配置 locale=false

**Comment by CodingZJ** [comment]
config 中的locale是个对象，这样设置会报错哇。
  // locale: {
  //   default: 'zh-CN',
  //   antd: true,
  //   baseNavigator: true,
  // },
  locale:false,

**Comment by CodingZJ** [comment]
config 中的locale是个对象，这样设置会报错哇。
// locale: {
// default: 'zh-CN',
// antd: true,
// baseNavigator: true,
// },
locale:false,

**Comment by CodingZJ** [comment]
@chenshuai2144 
config 中的locale是个对象，这样设置会报错哇。
// locale: {
// default: 'zh-CN',
// antd: true,
// baseNavigator: true,
// },
locale:false,

**Comment by CodingZJ** [comment]
清空一下 localStorage ，但是onfig 中配置 ：
  // locale: {
  //   default: 'zh-CN',
  //   antd: true,
  //   baseNavigator: true,
  // },
  locale:false,
会导致报错
"export 'useIntl' was not found in 'umi'

**Comment by CodingZJ** [comment]
清空一下 localStorage ，但是onfig 中配置 ：
// locale: {
// default: 'zh-CN',
// antd: true,
// baseNavigator: true,
// },
locale:false,
会导致报错
"export 'useIntl' was not found in 'umi'  @chenshuai2144

**Comment by CodingZJ** [comment]
清空一下 localStorage ，但是config 中配置 ：
// locale: {
// default: 'zh-CN',
// antd: true,
// baseNavigator: true,
// },
locale:false,
会导致报错很多模块找不到useIntl。例如
"export 'useIntl' was not found in 'umi'：
@chenshuai2144

**Comment by chenshuai2144** [comment]
你不是要关闭权限吗 应该不使用useintl

**Comment by CodingZJ** [comment]
没有哇，我只是移除国际化。
1:yarn i18n-remove  2:删除locales文件夹就报错了

**Comment by CodingZJ** [comment]
没有哇，我只是移除国际化。因为我不需要国际化
1:yarn i18n-remove 2:删除locales文件夹就报错了
@chenshuai2144

**Comment by chenshuai2144** [comment]
useIntl 就是国际化的api，你不使用了应该全部删掉的

**Comment by CodingZJ** [comment]
所以我要全局搜索，一个个删掉?是嘛@chenshuai2144

**Comment by XSmarter** [comment]
@chenshuai2144 设置locale: false后，不报错了，但是<Typography.Paragraph copyable>这类组件变成了英文，怎么处理呢？
![image](https://user-images.githubusercontent.com/33716687/82187522-20b52600-991f-11ea-879a-cbc53d79e63c.png)

**Comment by FinchJohnRen** [comment]
文档写全一点吧。！ 这么多人遇到

**Comment by bytrix** [comment]
为啥不在脚手架中加入是否需要国际化的选项？

**Comment by jiankian** [comment]
y移除配置就会报错，报错的是.umi目录里生成的代码，与我自己的无关，跟脚手架有关。。。

**Comment by derenmiao** [comment]
把useIntl相关代码删除掉
