### ISSUE TITLE
Overridig plugins in .umi folder

### ISSUE THREAD

**Issue by shakesBeardZ** [ant-design/ant-design-pro#6593]
Hi, 
I did initiate an empty project of Ant Pro and I tried to figure out how to add for example other languages so I ended up overriding plugin-local in .umi folder to add a language and pass a direction to ConfigProvider but every time a build it's gone.
the docs said it's temporary,  so how I can override the configs in .umi folder?

**Comment by huntdream** [comment]
You should change config in `config/config.ts`

**Comment by shakesBeardZ** [comment]
@huntdream  can you elaborate? say for example I want to do this 
```
  const direcition = getLocale() === 'ar-EG' ? 'rtl' : 'ltr'
  return (
    <ConfigProvider  direction={direcition} locale={localeInfo[locale]?.antd || defaultAntdLocale}>
      <RawIntlProvider value={intl}>{props.children}</RawIntlProvider>
    </ConfigProvider>
  )
```

**Comment by chenshuai2144** [comment]
you can read this doc
https://umijs.org/plugins/plugin-locale

pro power by plugin-locale

**Comment by shakesBeardZ** [comment]
@chenshuai2144 I know it's powered by plugin-local but how to override the generated configs to add direction.
by the way, this doesn't answer my question so no need to close the issue!!! 
it's called a community other contributions can answer the issue.

**Comment by huntdream** [comment]
@shakesBeardZ You want to pass some props to `ConfigProvider`, right?

**Comment by shakesBeardZ** [comment]
@huntdream yeah, sorry I just saw your answer
