### ISSUE TITLE
Deno 1.0 发布，有没有取代 node 的优势？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6596]

**Comment by chenshuai2144** [comment]
一个语言能成功，重要的不是有多好的新特性。而是在某个刚好的时间满足了一些需求，并且形成了自己的生态。Deno 虽然比较 node 要棒，但是有点晚了。

**Comment by joesdu** [comment]
我猜以后可能会真香,并且会支持,或者antd团队出个新的项目.
