### ISSUE TITLE
Add support for RTL 

### ISSUE THREAD

**Issue by shakesBeardZ** [ant-design/ant-design-pro#6599]
since Ant design now supports RTL, I'm wondering when you guys ready to add the support here, 
right now I'm having difficulties passing direction to ```ConfigProvider``` cause I didn't find a proper way to do it.

**Comment by shakesBeardZ** [comment]
I added a PR for ```umi``` plugins repo to support the direction attribute in plugin-local, I assumed that the branch used by ant design pro is ```pro``` so my PR is to that branch I hope you can check it guys ASAP.
https://github.com/umijs/plugins/pull/212

**Comment by chenshuai2144** [comment]
Antd has supported，you can try

**Comment by shakesBeardZ** [comment]
@chenshuai2144 I know but we are talking about ant design pro, anyway my or has been merged I'll test now and continue improving, thanks 👌

**Comment by shakesBeardZ** [comment]
@chenshuai2144, unfortunately, the issue is not solved, as I explained before we need to pass the direction to ```ConfigProvider``` in order for ant design to detect the direction after I requested my PR to be merged in ```umi/plugins```
 I thought it's gonna be merged because when you merge it will solve the problem.
I hope you can look into it.
