### ISSUE TITLE
Charts 饼状图样式问题

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro#66]
- 实际字号小于 12px 的时候 js 对 `.chart` 的 font-size 设置无效
- demo 中 legend 占宽较多，加上第一个问题的影响，使 992>x>1300 这个区间的展示效果不太好

<img width="429" alt="2017-11-01 3 09 54" src="https://user-images.githubusercontent.com/7017767/32264106-0b760b26-bf18-11e7-89f1-1b9f81116ae9.png">

**Comment by afc163** [comment]
看到的效果不太一样，下面是 1200px 下的。

<img width="477" alt="image" src="https://user-images.githubusercontent.com/507615/32264554-3e35646a-bf1a-11e7-9628-0016633418c4.png">

**Comment by afc163** [comment]
1200px 以下就换布局了。

**Comment by ddcat1115** [comment]
我这儿本地和线上 1200 时看着都是这样，而且要到 992 以下才换布局...

<img width="571" alt="2017-11-01 4 16 00" src="https://user-images.githubusercontent.com/7017767/32265894-0f32c30a-bf20-11e7-8d40-3af1cd1858df.png">

**Comment by nikogu** [comment]
我判断一下，让 `legend` 在宽度不够的时候换行好了

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/commit/8d9b7cfd94bc45adb4b26e44ff9ec83ea760dacd
