### ISSUE TITLE
[bikeshedding] username or userName; password or passWord

### ISSUE THREAD

**Issue by VitoVan** [ant-design/ant-design-pro#660]
https://github.com/ant-design/ant-design-pro/blob/976e610bcb0d487080d5ef56314d87069e14de86/src/routes/User/Login.js#L66

以上行有代码如下：

![image](https://user-images.githubusercontent.com/1756956/34807671-0781a7f2-f6c5-11e7-8008-fa17ca4d70f9.png)

其中 userName 中的 N 大写，而 password 全部小写。

用 Google 查询：

![image](https://user-images.githubusercontent.com/1756956/34807705-3388081e-f6c5-11e7-9835-3fd862ce8112.png)

![image](https://user-images.githubusercontent.com/1756956/34807697-274e99d2-f6c5-11e7-8e11-cbb3e218a886.png)

username 以及 password 都可以认为是已有单词，可以直接写为 username 以及 password 这样的形式。

**如果我们此处是为了将 user 和 name 中间断开的话，按照这个策略，是不是 password 也应该写成 passWord ?**

关于这个情况，我们该如何考虑？

**Comment by ddcat1115** [comment]
I think `user name` and `username` are both ok, but `pass word` is not.
