### ISSUE TITLE
今天最新版安装后，package.json中没有fetch:blocks 🐛[BUG]

### ISSUE THREAD

**Issue by cryst4lMao** [ant-design/ant-design-pro#6601]
### 🐛 bug 描述

今天最新版安装后，package.json中没有fetch:blocks，手动添加
"fetch:blocks": "pro fetch-blocks --branch=umi@3 && npm run prettier",
执行npm run fetch:blocks

出现异常：
 🧐  find config.ts ...
(node:15858) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/ant-design/pro-blocks/git/trees/master failed, reason: connect ECONNREFUSED 13.250.168.23:443

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
v5 的版本中删除了fetch:blocks
推荐使用 yarn create umi 中选择 全部区块来下载

**Comment by GreatAuk** [comment]
> v5 的版本中删除了fetch:blocks
> 推荐使用 yarn create umi 中选择 全部区块来下载

目前没有这个选项啊，选择 V5 版本后就直接拉代码了，也没有要求你选择 ts 还是 js, 是否下载完整的 blocks
