### ISSUE TITLE
菜单名称超长，文本溢出没有提示🐛[BUG]

### ISSUE THREAD

**Issue by liufa520** [ant-design/ant-design-pro#6603]
[###](url) 🐛 bug 描述

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
需要自己实现了一下，在 6.0 中我们会默认实现。

试试 meunItemRender api 和 [typography](https://ant.design/components/typography-cn/)
