### ISSUE TITLE
有没有实现过app.js中动态加载路由表，并显示出来icon的demo🧐[问题]

### ISSUE THREAD

**Issue by luyi18** [ant-design/ant-design-pro#6604]
### 🧐 问题描述
动态加载路由表实现了，但是icon不管配置成string 还是react node都不行，配置成react node 报错.
ps:官方给的demo里面也是没有配置icon的

版本:
 @ant-design/icons: "^4.0.0",
 @ant-design/pro-layout: "^5.0.12",
@ant-design/pro-table: "2.2.1",
 antd: "^4.0.0",
umi: "3.1.1",

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu

看这个 demo
