### ISSUE TITLE
🐛[BUG]Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by loveProgrammingRedWolf** [ant-design/ant-design-pro#6607]
### 🐛 bug 描述

npm create umi myApp
find error
Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
### 🏞 期望结果
Why is there such a low-level error?

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wb121017405** [comment]
同款  删除了本地全局安装的typescript和eslint解决🤮

**Comment by LuckWolf** [comment]
这个bug已经修复了吗？
