### ISSUE TITLE
🧐关于通过npm create umi拉取ant-design-pro,代码有缺失[问题]

### ISSUE THREAD

**Issue by knight2018** [ant-design/ant-design-pro#6608]
### 🧐 问题描述
乌米版本umi@3.1.3
"@ant-design/pro-cli": "^1.0.18"
1.通过乌米拉下的ant-design代码好像有一些缺失，首先是/src/layouts/SecurityLayout.jsx,通过官方注释，我认为他是登陆的验证规则，但是，在我拉取的版本中，此组件并没有在任何地方引用。/config/config.js中缺失 path: '/', component: '../layouts/SecurityLayout'这一层。
2.另外一个是一个小小的建议 /src/utils/request.js并没有被作用于官方的示例，官方所有的示例都是引用import request from 'umi-request';不知道官方能否换成import request from '@/utils/request';

### 🚑 其他信息
虽然这些问题对于整个项目并没有任何影响，但是加上官方的注释，会对我这种萌新进行一定的误导

![image](https://user-images.githubusercontent.com/34180683/82187502-1a26ae80-991f-11ea-8447-26a98bcd46cf.png)
这是我刚刚从umi拉取的pro，可以看到，仍然缺少
拉取步骤，npm create umi
? Select the boilerplate type ant-design-pro
? � Be the first to experience the new umi@3 ? Pro V4
? � Which language do you want to use? TypeScript
? � Do you need all the blocks or a simple scaffold? complete

**Comment by chenshuai2144** [comment]
complete 中的代码时又一些滞后的，这个需要解决一下。
建议使用 v5 虽然有风险，但是里面抽象了很多东西，需要学习的东西更少了

**Comment by knight2018** [comment]
> complete 中的代码时又一些滞后的，这个需要解决一下。
> 建议使用 v5 虽然有风险，但是里面抽象了很多东西，需要学习的东西更少了

感谢回复，因为我们业务要求，我们要大量魔改项目的代码。这一点上v5抽象的太多东西反而成了我们的负担（而且，还看不到官方秀技 手动狗头）

**Comment by knight2018** [comment]
> complete 中的代码时又一些滞后的，这个需要解决一下。
> 建议使用 v5 虽然有风险，但是里面抽象了很多东西，需要学习的东西更少了

还有一个问题，pro所使用的request似乎对于jwt不太友好，为什么不考虑dva/fetch呢
