### ISSUE TITLE
🐛[BUG] history在自定义工具类中封装再导出后，history.push浏览器路由变化但是页面不刷新

### ISSUE THREAD

**Issue by Liaozzzzzz** [ant-design/ant-design-pro#6609]
### 🐛 bug 描述
特殊场景， 需要对history进行一层封装，但是发现调用push时路由变化， 页面不刷新。

### 💻 复现代码
![image](https://user-images.githubusercontent.com/33082279/82196195-fcac1180-992b-11ea-811c-8532578cc5dc.png)
未作任何修改， 仅仅转了一次导出；

![image](https://user-images.githubusercontent.com/33082279/82196296-16e5ef80-992c-11ea-984b-c1bc96af11fb.png)
页面内使用就无法刷新页面了

复现demo仓库：https://github.com/Liaozzzzzz/umi-issue.git

### © 版本信息

   "@ant-design/pro-layout": "^5.0.12",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.2.0-beta.6",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.2.0-beta.6",
    "yorkie": "^2.0.0"

- 浏览器环境 chrome 81.0.4044.138
- 开发环境 win10

**Comment by soeasyjx** [comment]
兄弟问题解决了么
