### ISSUE TITLE
🧐[问题]4.0如何让部分接口走mock，部分接口走代理proxy

### ISSUE THREAD

**Issue by fjnetinfo** [ant-design/ant-design-pro#6611]
### 🧐 问题描述

4.0如何让部分接口走mock，部分接口走代理proxy。
服务端通常并非全部接口一下子都完成了，这时候需要让部分接口走mock，部分接口走服务端。
求指点。谢谢。

**Comment by Shijiuwei** [comment]
package.json srcipts 加一个： ``` "start:sit": "cross-env REACT_APP_ENV=sit umi dev", ```

config 文件下 proxy.ts 加一个代理：
``` js
sit: {
    '/myapi/': {
      target: 'http://8.8.8.8:8888', // sit 环境的 api 地址
      changeOrigin: true,
      pathRewrite: { '^/myapi': '' },
    },
  },
```

**Comment by chenshuai2144** [comment]
不要给他写mock ，他就不得不走代理了😎

**Comment by fjnetinfo** [comment]
> 不要给他写mock ，他就不得不走代理了😎

这个我试了好像不管用。所以来求助。可能有什么问题。

**Comment by fjnetinfo** [comment]
> package.json srcipts 加一个： `"start:sit": "cross-env REACT_APP_ENV=sit umi dev",`
> 
> config 文件下 proxy.ts 加一个代理：
> 
> ```js
> sit: {
>     '/myapi/': {
>       target: 'http://8.8.8.8:8888', // sit 环境的 api 地址
>       changeOrigin: true,
>       pathRewrite: { '^/myapi': '' },
>     },
>   },
> ```
> 
> 开发时跑： start:sit

谢谢，我试试

**Comment by tss0823** [comment]
这个问题简单，不写mock,它就默认走代理
