### ISSUE TITLE
🧐[问题]有人用过在这个上集成IOC吗?

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6614]
### 🧐 问题描述

有人试过IOC吗?我用inversify以及reflect-metadata实现依赖注入会产生错误,希望有大佬能帮我一下.

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它


——


We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
