### ISSUE TITLE
🧐[问题]主菜单收缩的宽度(80)在ProLayout中不能修改？

### ISSUE THREAD

**Issue by meloncocoo** [ant-design/ant-design-pro#6616]
### 🧐 主菜单收缩的宽度(80)在ProLayout中不能修改？

主菜单收缩的宽度在ProLayout中不能修改？是这样设计的，还是说我没有找到正确的地方？

### 💻 示例代码
@ant-design/pro-layout/es/BasicLayout.js
LINE: 123

var getPaddingLeft = function getPaddingLeft(hasLeftPadding, collapsed, siderWidth) {
  if (hasLeftPadding) {
    return collapsed ? 80 : siderWidth;
  }

  return undefined;
};

**Comment by chenshuai2144** [comment]
暂时是不支持这个功能，我们的设计就是这样，如果改了动画，页面布局可能都会挂掉

**Comment by shanghaihehework** [comment]
能不能支持修改啊。 老板说太宽了 ，又要被老板骂了

**Comment by meloncocoo** [comment]
@shanghaihehework 
```
<ProLayout
      logo={logo}
      siderWidth={200}
      formatMessage={formatMessage}
      menuHeaderRender={(logoDom, titleDom) => (
        <Link to="/">
          {logoDom}
          {titleDom}
        </Link>
      )}
...
```
修改siderWidth的默认值

**Comment by anyviya** [comment]
> 能不能支持修改啊。 老板说太宽了 ，又要被老板骂了

自己改padding样式
