### ISSUE TITLE
🐛[BUG]访问路由时，二级页面指向的是一级的Component

### ISSUE THREAD

**Issue by lujijiang** [ant-design/ant-design-pro#6617]
### 🐛 bug 描述

访问路由时，二级页面指向的是一级的Component

### 📷 复现步骤

直接git clone后，在点击管理页-二级管理页菜单，出现的页面其实是Admin.tsx而不是Welcome.tsx

### 🏞 期望结果

直接git clone后，在点击管理页-二级管理页菜单，出现的页面应该是Welcome.tsx

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/layout-cn#%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%A0%81%E5%AE%9E%E7%8E%B0-layout
看这里。layout 的 children会从 props 传进来需要自己处理

**Comment by chenshuai2144** [comment]
故意这么配置的，这是个featrue
