### ISSUE TITLE
🐛[BUG] protable内存泄漏问题

### ISSUE THREAD

**Issue by YunSD** [ant-design/ant-design-pro#6619]
### 🐛 bug 描述

当前版本中，在菜单栏中疯狂切换两个页面（其中至少一个界面使用到了protable组件），那么会报告这个问题：

`devScripts.js:5035 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ProTable (created by Context.Consumer)
    in Provider (created by ProviderWarp)
    in ProviderWarp (at Menu.tsx:169)
    in div (created by PageHeaderWrapper)
    in div (created by GridContent)
    in GridContent (created by PageHeaderWrapper)
    in div (created by PageHeaderWrapper)
    in PageHeaderWrapper (at Menu.tsx:168)
    in MenuList (created by ConnectFunction)
    in ConnectFunction (created by ForwardRef(LoadableComponent))
    in ForwardRef(LoadableComponent) (created by Context.Consumer)
    in Route (created by Context.Consumer)`

### 📷 复现步骤

在菜单栏中快速且反复切换两个页面（其中至少一个界面使用到了protable组件）

### 🏞 期望结果

protable组件的生命周期恢复正常

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by YunSD** [comment]
![image](https://user-images.githubusercontent.com/18546121/82285729-af34b080-99ce-11ea-85fe-b531437ad3fe.png)

**Comment by YunSD** [comment]
起初我没有仔细阅读错误，以为是由于自定义表单中的useEffect没有销毁导致的，后来发现是在
in ProTable (created by Context.Consumer)
出现的，请问有什么办法可以解决（不影响使用）

**Comment by YunSD** [comment]
我是使用protable 的request方式获取datasource ，不知道是否因此导致

**Comment by YunSD** [comment]
我在 protable 的项目中找到了相似的问题
https://github.com/ant-design/pro-table/issues/436

**Comment by chenshuai2144** [comment]
是因为网络请求太慢 回来之后去 setState 这个时候组件已经被销毁了！

暂时没有好的解法，不会造成内存泄露

**Comment by afc163** [comment]
卸载组件要 abort 掉正在进行的请求。

**Comment by YunSD** [comment]
好的，谢谢

**Comment by afc163** [comment]
@YunSD 我是和 @chenshuai2144 提的，ProTable 里应该尽量解决掉。

**Comment by chenshuai2144** [comment]
fetch 不支持 abort，只能搞一个类似去抖的东西来干掉请求之后会的回调

**Comment by chenshuai2144** [comment]
搞了一个，尝试一下最新的 2.3.0

**Comment by YunSD** [comment]
"@ant-design/pro-table": "2.3.0",
事实上，我在更改了版本后，依旧会出现这个问题，虽说不影响使用

**Comment by pxim** [comment]
v5版本，还存在这个问题，如果我自己写可以用request.CancelToken，或者axios.CancelToken，在生命周建结束时，销毁请求；但是用的ProTable，不改源码，没办法解决
