### ISSUE TITLE
BUG：无状态组件，内部dispatch调用之后，state全局更新，组件被重新渲染。

### ISSUE THREAD

**Issue by lettywiterock** [ant-design/ant-design-pro#662]
调用dispatch 更新state其中一个data，整个组件被重新刷新了！
页面无法存储数据，已修改数据被重置更新，无状态组件被重新渲染！
是不是redux绑的出错了。

这个问题会交替出现，调用计时器的时候，就能感觉到。
有几率自己OK，请问哪里可以修改，在线等急！

**Comment by WhatAKitty** [comment]
请提供可重现repo

**Comment by lettywiterock** [comment]
redux组件刷新问题，更改一个值，所有值都会刷新

**Comment by afc163** [comment]
React 就是这样的，合理的 connect Redux store（避免 connect 不需要的数据）可以优化这个问题。
