### ISSUE TITLE
🐛[BUG] V5预览版本 Bug 汇总

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6621]
- [ ]   在 navTheme: 'dark' 模式下，routes 注释掉 icon后，菜单色变了，如下图：
```
[
    {
      path: '/welcome',
      name: 'welcome',
      // icon: 'smile',
      component: './Welcome',
    },
]
```
![image](https://user-images.githubusercontent.com/18542211/82293764-a8626980-99df-11ea-86ba-526f4ac2a173.png)

- [x]  在子菜单没有配置 icon 时，自动继承了父菜单的 icon，这个不应该是继承的关系，不配置icon就不应该显示才合适。

- [x]  无法关闭多国际化 https://github.com/ant-design/ant-design-pro/issues/6561 , 在console 打印 
 ![image](https://user-images.githubusercontent.com/18542211/82297050-afd84180-99e4-11ea-9f07-88eda43a343f.png)

- [x]  在 layout: 'mix' 与  layout: 'side'( layout: 'top') 切换时，保持**头信息**显示，要启用或者注释掉 app.ts 里的 menuHeaderRender: false,

**Comment by hot588** [comment]
只是预览版，也不是正式版！V4还不稳定！还是用V2比较健康

**Comment by afc163** [comment]
@hot588 给个小建议，以后尝试一下用 `，` 代替所有 `！`。

**Comment by kaoding** [comment]
第一个问题是：navTheme: 'dark' 、layout: 'mix' 或 layout: 'side'、icon 不设置 三个条件同时满足时才会出现字体色和背景色不对的情况发生。

**Comment by kaoding** [comment]
> 第一个问题是：navTheme: 'dark' 、layout: 'mix' 或 layout: 'side'、icon 不设置 三个条件同时满足时才会出现字体色和背景色不对的情况发生。

这个问题能否快一些修复一下，现有的项目直接升级过来，在不改变大的体验情况，三个条件同时满足是很多的情况，比较急一点
@chenshuai2144 .

**Comment by chenshuai2144** [comment]
@kaoding 最近有点忙。今晚一定修，修不好不睡觉

**Comment by kaoding** [comment]
> @kaoding 最近有点忙。今晚一定修，修不好不睡觉

里面现在有点复杂了，我现在也是忙业务的事，也没有空认真看里面，所以自己也修不了。

**Comment by chenshuai2144** [comment]
@kaoding  发了版本了
@ant-design/pro-layout@6.0.0-3

**Comment by kaoding** [comment]
> @kaoding 发了版本了
> @ant-design/pro-layout@6.0.0-3

感谢 ！陈大师
