### ISSUE TITLE
想要兼容ie9,,有啥好的解决方案🧐[问题]

### ISSUE THREAD

**Issue by wangShengCool** [ant-design/ant-design-pro#6623]
### 🧐
ie9打开,保错Cannot call a class as a function

**Comment by wangShengCool** [comment]
babel-polyfill 和 babel-plugin-transform-runtime这两个怎么添加到项目,在哪里添加呢

**Comment by wangShengCool** [comment]
![image](https://user-images.githubusercontent.com/38369701/82305062-c041e980-99ef-11ea-844e-eca55fcf5e3a.png)

**Comment by wangShengCool** [comment]
![image](https://user-images.githubusercontent.com/38369701/82305097-cb951500-99ef-11ea-8051-12e851b1e1fc.png)

**Comment by wangShengCool** [comment]
![image](https://user-images.githubusercontent.com/38369701/82305139-d94a9a80-99ef-11ea-8074-6c39d4668bc6.png)

**Comment by wangShengCool** [comment]
"ant-design-pro": "^2.3.2",
 "umi": "^2.12.5",
 "antd": "^3.20.0",
用的版本,
config里配置了target,dynamicImport去掉了....都没用,搞不懂

**Comment by chenshuai2144** [comment]
ie9 这个太难了，antd 都不支持了。
最好从 webpack 开始搭建，然后使用一些兼容性比较低的库，比如 bootstrap 什么的
