### ISSUE TITLE
🐛[BUG]请问大佬，为什么无论怎么选择，都无法切换成JS语言，怎么下都是TS,求解答

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6624]
### 🐛 bug 描述

按照官方介绍下载，无论怎么下载都是TS语言，无法下载成JS语言

### 📷 复现步骤

- yarn create umi myapp
- ❯ ant-design-pro
- ❯ Pro V4
- ❯ JavaScript
- ❯ simple
- ❯ antd@4

### 🏞 期望结果

希望项目是JS语言

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/82309114-4ad91780-99f5-11ea-828b-1d68aa6af55f.png)
![image](https://user-images.githubusercontent.com/30942709/82398666-ffbb1500-9a85-11ea-8112-ae3a643df8f4.png)

**Comment by JAMIERWANG** [comment]
Choose ‘No’ for the question that ‘Be the first to experience the new umi@3’.

**Comment by ISBN9527** [comment]
> Choose ‘No’ for the question that ‘Be the first to experience the new umi@3’.

what do you mean?

**Comment by ISBN9527** [comment]
@JAMIERWANG no this option

**Comment by chenshuai2144** [comment]
you need update create umi version

**Comment by ISBN9527** [comment]
大佬，umi版本吗？最新3.2.2？
是这个意思吗？

**Comment by ISBN9527** [comment]
> you need update create umi version

升级到 create-umi@0.24.1 还是不行

**Comment by yysfwls** [comment]
请问解决了吗。

**Comment by chenshuai2144** [comment]
@ISBN9527 清理一下全局的 babel 和 ts 依赖，最近碰到的都是全局依赖不兼容语法造成的

**Comment by kevinzl** [comment]
DefaultSettings 报错如何解决的？

**Comment by bill80362** [comment]
一開始會是ts沒錯，yarn之後會轉成js

**Comment by bill80362** [comment]
DefaultSettings 重安裝create-umi有用

**Comment by hankaibo** [comment]
基于官方的仓库，我自己搞了一个js版本。
[https://github.com/hankaibo/myantdpro](https://github.com/hankaibo/myantdpro)
基本上就是把官方的 ts 换成了 js，并且在其基础上集成了一些公共页面，调用真实的后台接口。
你可以参考一下，希望帮到你。

**Comment by BluesVN** [comment]
无法使用js 尝试使用ts开发
