### ISSUE TITLE
🐛[BUG]升级umi@3.2.0 造成页面错乱

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6626]
### 🐛 bug 描述

升级umi@3.2.0 造成页面错乱
![QQ浏览器截图20200519174838](https://user-images.githubusercontent.com/3166799/82312069-21ba8600-99f9-11ea-9181-baad70f45366.png)

### © 版本信息

- Ant Design Pro 版本: 4.2.4
- umi 版本 3.2.0
- 浏览器环境 Chrome 80
- 开发环境 Windows

**Comment by ycjcl868** [comment]
可能和这个有关 https://github.com/ant-design/ant-design-pro/issues/6620，我发个 patch

**Comment by Zach-Lu** [comment]
所以怎么解决呢？
