### ISSUE TITLE
我升级antd Pro到4 左侧菜单子级列表继承了父级的图标

### ISSUE THREAD

**Issue by zhengxdlol** [ant-design/ant-design-pro#6627]
我升级antd Pro到4 左侧菜单子级列表继承了父级的图标，是根据后台动态加载的 现在更新的antd的图标也不知道怎么解决
![image](https://user-images.githubusercontent.com/39687287/82314082-d8b80100-99fb-11ea-8204-98bfa7823f16.png)

**Comment by zhengxdlol** [comment]
![QQ截图20200519181032](https://user-images.githubusercontent.com/39687287/82314261-174dbb80-99fc-11ea-926f-956982e70f31.png)

**Comment by zhengxdlol** [comment]
我靠 我解决了

**Comment by zhangyu1818** [comment]
大兄弟，咋个解决的，我也出现这个问题，不过我图标显示出来了的
