### ISSUE TITLE
🧐[问题]api接口中的下划线统一映射成驼峰的typescript类型

### ISSUE THREAD

**Issue by fjnetinfo** [ant-design/ant-design-pro#6628]
### 🧐 问题描述

如何把api接口中的下划线统一映射成驼峰的typescript类型，求大佬赐教

### 💻 示例代码

export interface ErrorParamsType {
  errorMessage: string;
  errorCode: string;
}
代码中用的是驼峰式，但是服务端返回的是下划线，如何统一映射。
{
    "error_message": "失败",
    "error_code":'400',
}

**Comment by fjnetinfo** [comment]
好像跟pro没有什么关系。还是希望有大佬帮忙解答。谢谢。

**Comment by joesdu** [comment]
```typescript
const {errorMessage: error_message,errorCode:error_code} = response;
```

**Comment by eternallycyf** [comment]
// 下划线转驼峰
export type CamelCase<Str extends string> = Str extends `${infer Left}_${infer Right}${infer Rest}`
  ? `${Left}${Uppercase<Right>}${CamelCase<Rest>}`
  : Str;

// 驼峰转下划线
export type SnakeCase<Str extends string> = Str extends `${infer Left}${infer Right}${infer Rest}`
  ? `${Left}${Right extends Uppercase<Right> ? `_${Lowercase<Right>}` : Right}${SnakeCase<Rest>}`
  : Str;
