### ISSUE TITLE
文档更新问题

### ISSUE THREAD

**Issue by williamwang2015** [ant-design/ant-design-pro#663]
https://pro.ant.design/docs/layout-cn
“common/nav.js ”这个文件已经不存在，内容也是不正确！

**Comment by ddcat1115** [comment]
Thank you for reminding!

**Comment by ddcat1115** [comment]
fixed in https://github.com/ant-design/ant-design-pro-site/commit/dba4bd8ae49762f462b3ff28193a1b02e5388f55
