### ISSUE TITLE
🐛[BUG]线上预览项目好多布局错乱，不知道是antd的锅还是啥原因

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6630]
### 🐛 bug 描述

进入ANT DESIGN PRO预览，你会发现好多布局错乱

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/30942709/82396600-dc419b80-9a80-11ea-99c7-4afa3b0dd688.png)
![image](https://user-images.githubusercontent.com/30942709/82396629-f11e2f00-9a80-11ea-8dfc-c3dc672a32cc.png)

**Comment by chenshuai2144** [comment]
是设计的不好导致的
有兴趣来个 pr 吗？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/82401798-5bd56780-9a8d-11ea-90c3-72d453dd57b4.png)


这个还真的是 antd 的锅，旧版本的 antd 就没事

**Comment by ISBN9527** [comment]
对吧，那个栅格布局好像也是😀

**Comment by chenshuai2144** [comment]
我正好在提 pt

**Comment by ISBN9527** [comment]
大佬，pro怎么下载JS模式的项目啊，找了一天了也没解决

**Comment by chenshuai2144** [comment]
现在 js 没有任何优势，建议直接上 ts。

因为 pro 的 js 是 ts 转化成的，转化的库和 3.9 配合起来有点坑，需要解决一下

**Comment by ISBN9527** [comment]
因为这次项目周期比较短，直接上怕耽误工期，所以还是想js先搞定
以后ts是大趋势，肯定是要学的

**Comment by joesdu** [comment]
> 因为这次项目周期比较短，直接上怕耽误工期，所以还是想js先搞定
> 以后ts是大趋势，肯定是要学的

TS的JS用法,就是把所有东西都声明成any.其他和JS还是一样的.
