### ISSUE TITLE
👑 [需求]V5版本有配置umi-plugin-setting-drawer中SettingDrawer组件的例子吗?

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6633]
### 🥰 需求描述

我想要修改一些SettingDrawer中的一些属性.请问需要如何调整.同时我发现现在的SettingDrawer里边主题色只有一个.

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-plugin-setting-drawer/blob/55f87fd2310f782c9b3e7a3d5275d2168a723a7e/src/layout/index.tsx#L17

在 initialState 中做一个 settingDrawer 对象就好了

**Comment by joesdu** [comment]
> settingDrawer

现在settingDrawer中可选主题色只有一个了,有什么办法像以前一样有很多吗?

**Comment by hagyao520** [comment]
现在settingDrawer中可选主题色只有一个了,有什么办法像以前一样有很多吗?
