### ISSUE TITLE
🧐[问题]关于官网预览时左上角的 待办图标（闹铃）怎样安装？

### ISSUE THREAD

**Issue by afr751116** [ant-design/ant-design-pro#6635]
![image](https://user-images.githubusercontent.com/57131579/82428317-e84b4e80-9abc-11ea-8d47-678be0362f7e.png)
![image](https://user-images.githubusercontent.com/57131579/82428398-0c0e9480-9abd-11ea-8d38-c9453ab50f53.png)

如题，这个功能是取消了吗？还是需要安装？谢谢

**Comment by chenshuai2144** [comment]
在这里，默认没有打开

https://github.com/ant-design/ant-design-pro/tree/bb040b1946bff874a539abe02ddff077404454df/src/components/NoticeIcon
