### ISSUE TITLE
🐛[BUG]错误通知：http code 200

### ISSUE THREAD

**Issue by abcnny** [ant-design/ant-design-pro#6639]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/7876570/82517744-5d1b9880-9b50-11ea-9995-ecdca520f3d3.png)

为什么成功返回200，还来个错误通知，是不是超时导致的

### © 版本信息

"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.2.2",
    "antd": "^4.1.5",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "umi": "3.1.1",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },

**Comment by chenshuai2144** [comment]
输出一下 `const errorHandler = (error: { response: Response }) => {`
一般情况下超时是有属于自己的报错的。

**Comment by abcnny** [comment]
用的就是request.ts，如下，notification就是弹出的通知框吧，奇怪的是为什么200会进这个错误里面
<code>
const errorHandler = (error: { response: Response }): Response => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  } else if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  return response;
};
</code>

**Comment by abcnny** [comment]
这贴代码怎么完全格式化的，怎么格式化一半

**Comment by chenshuai2144** [comment]
贴一下你的返回吧
