### ISSUE TITLE
RangePicker 控件配合 form表单，设置initialValue报错？

### ISSUE THREAD

**Issue by duanpf** [ant-design/ant-design-pro#664]
{getFieldDecorator('dataTime',  {initialValue: [this.state.startTime, this.state.endTime]})(
                <RangePicker allowEmpty='false' placeholder={[开始时间, 结束时间]}
                style={{ width: '100%' }}  />
 )}

这样写法报错~~~

**Comment by ddcat1115** [comment]
给个可重现地址或步骤，或者至少报错截图

另外，代码建议格式化下  http://segmentfault.com/markdown

**Comment by afc163** [comment]
Please file issue to https://github.com/ant-design/ant-design/ if you meet a antd component problem.

**Comment by duanpf** [comment]
ant-design  文档并没有给出一个明确的为RangePicker设置默认值的写法。 initialValue: [this.state.startTime, this.state.endTime]写成这种数组的形式，会报错。那么请问下正确的写法应该怎样的
