### ISSUE TITLE
🧐[问题]在重新npm install后运行npm start报出一些less找不到，但项目可以正常运行起来

### ISSUE THREAD

**Issue by s464446877** [ant-design/ant-design-pro#6641]
### 🧐 问题描述
在重新npm install后运行npm start报出一些less找不到，但项目可以正常运行起来，在修改文件热更新后不会出这个错误，只有在npm start启动项目的时候出现

**Comment by s464446877** [comment]
https://user-images.githubusercontent.com/52397868/82528281-ff487a00-9b6a-11ea-9f03-870c88b02758.png

**Comment by chenshuai2144** [comment]
less 里面是不支持别名的

**Comment by s464446877** [comment]
不是less文件的问题，是在我把node_modules和package-lock.json删除之后重新安装包后，运行就会有这个问题，如果用之前的package-lock.json去npm install后，运行就没有问题

**Comment by 7ynstar** [comment]
同样遇到了这个问题，三月份时 `npm install` 的node_modules不会报这个错，但是最近一个新的项目在 `npm install` 后就会找不到less文件

**Comment by chenshuai2144** [comment]
一直没有办法复现
