### ISSUE TITLE
npm run start 为什么不能打开浏览器

### ISSUE THREAD

**Issue by jinyindu** [ant-design/ant-design-pro#6642]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
若是每次都开会造成很多页面.甚至是有时候电脑性能不好,自动开浏览器会造成电脑卡死.我不建议官方自动开.

**Comment by kaoding** [comment]
以前是自动打开浏览器的，是不是可以做一个开关给用户，默认关闭就行了。

**Comment by chenshuai2144** [comment]
现在好像不支持自定义，我也不是很喜欢这个功能，相比还是 crt 的效果更好一些，永远打开一个 浏览器窗口
