### ISSUE TITLE
🐛[BUG] V5 左侧栏收缩时，点击图标无效。

### ISSUE THREAD

**Issue by juzhiyuan** [ant-design/ant-design-pro#6644]
### 🐛 bug 描述
V5 左侧栏收缩时，点击图标无效。

![image](https://user-images.githubusercontent.com/2106987/82540934-40985400-9b82-11ea-97de-c2bae4a9b6cb.png)

![image](https://user-images.githubusercontent.com/2106987/82540952-4726cb80-9b82-11ea-857c-b66bfdb124fb.png)

### 📷 复现步骤

1. clone https://github.com/ant-design/ant-design-pro/tree/v5
2. 启动

### 🏞 期望结果

收缩状态下，点击图标可以切换路由。

### 💻 复现代码

https://github.com/ant-design/ant-design-pro/tree/v5

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本: 3
- 浏览器环境: Chrome
- 开发环境: Mac OSX

### 🚑 其他信息
None

**Comment by kaoding** [comment]
这个只会发生在只有一级菜单上，二级及以上正常。
@chenshuai2144

**Comment by kaoding** [comment]
这个貌似解决了，先关了。
