### ISSUE TITLE
使用antd4的暗黑模式，如何在运行时动态设置？

### ISSUE THREAD

**Issue by 13007640364** [ant-design/ant-design-pro#6645]
在config.ts代码中如下配置后可以使用暗黑模式。
```
export default defineConfig({
  antd: {
    dark: true, // 开启暗色主题
  },
}
```
但是如何让用户控制是否开启暗黑模式呢？可以在运行时修改antd的配置吗？

**Comment by chenshuai2144** [comment]
https://www.npmjs.com/package/umi-plugin-antd-theme
https://pro.ant.design/docs/dynamic-theme-cn

看这些地方
