### ISSUE TITLE
🐛[BUG]V5中使用umi-plugin-setting-drawer Bug汇总.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6648]
### 🐛 bug 描述

V5中使用umi-plugin-setting-drawer插件会导致菜单渲染不出来.同时SettingDrawer组件选择固定Header的时候会出现闪烁.可选主题色也仅有蓝色.色弱模式还无法生效.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
这个我也碰到了。

**Comment by joesdu** [comment]
> 这个我也碰到了。
只有等修复了.

**Comment by chenshuai2144** [comment]
> 可选主题色也仅有蓝色. 

需要安装 https://www.npmjs.com/package/umi-plugin-antd-theme

> 色弱模式还无法生效.

这个修掉了。

> umi-plugin-setting-drawer插件会导致菜单渲染不出来

需要升级 plugin-layout

> .同时SettingDrawer组件选择固定Header的时候会出现闪烁

这个是因为页面结构大变，修起来比较费劲

**Comment by joesdu** [comment]
> > 可选主题色也仅有蓝色.
> 
> 需要安装 https://www.npmjs.com/package/umi-plugin-antd-theme
> 
> > 色弱模式还无法生效.
> 
> 这个修掉了。
> 
> > umi-plugin-setting-drawer插件会导致菜单渲染不出来
> 
> 需要升级 plugin-layout
> 
> > .同时SettingDrawer组件选择固定Header的时候会出现闪烁
> 
> 这个是因为页面结构大变，修起来比较费劲

我又试了下,发现还是有几个BUG.
在切换主题后,RightContent里边的disableContentMargin: false,好像失效了.
同时SettingDrawer组件的主题色不会跟随切换后的主题.
同时这个theme的插件会产生如下错误.并且编译时间有点小长(估计是电脑配置不够好)
� less render start!
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1380:5)
    at loop (C:\Users\joe_du\Documents\GitHub\destiny-admin-flow\node_modules\antd-pro-merge-less\index.js:288:12)
    at build (C:\Users\joe_du\Documents\GitHub\destiny-admin-flow\node_modules\antd-pro-merge-less\index.js:300:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
� less render end!

**Comment by Gzbox** [comment]
@joesdu 我遇到了同样的问题  请问你的解决了吗

**Comment by joesdu** [comment]
> @joesdu 我遇到了同样的问题  请问你的解决了吗

目前估计官方没有修复，我平时也没有用

**Comment by Gzbox** [comment]
> > @joesdu我遇到了同样的问题请问你的解决了吗
> 
> 目前估计官方没有修复，我平时也没有用

好的谢谢啦

**Comment by joesdu** [comment]
> > > @joesdu我遇到了同样的问题请问你的解决了吗
> > 
> > 
> > 目前估计官方没有修复，我平时也没有用
> 
> 好的谢谢啦

建议在开发的时候就选dark或者light主题.动态切换在开发的时候编译太慢了.

**Comment by Gzbox** [comment]
> > > > @joesdu我遇到了同样的问题请问你的解决了吗
> > > 
> > > 
> > > 目前估计官方没有修复，我平时也没有用
> > 
> > 
> > 好的谢谢啦
> 
> 建议在开发的时候就选dark或者light主题.动态切换在开发的时候编译太慢了.

有什么地方能配置开发环境下不启动编译吗？ 总不能开发环境下去手动删除package.json 里面的 umi-plugin-antd-theme 依赖 吧   有啥好办法吗？

**Comment by joesdu** [comment]
> > > > > @joesdu我遇到了同样的问题请问你的解决了吗
> > > > 
> > > > 
> > > > 目前估计官方没有修复，我平时也没有用
> > > 
> > > 
> > > 好的谢谢啦
> > 
> > 建议在开发的时候就选dark或者light主题.动态切换在开发的时候编译太慢了.
> 
> 有什么地方能配置开发环境下不启动编译吗？ 总不能开发环境下去手动删除package.json 里面的 umi-plugin-antd-theme 依赖 吧   有啥好办法吗？

看起来是没有😶

**Comment by ZhaoYuxin-Go** [comment]
umi@4自动构建的项目，初始化启动后切换主题色不生效，有遇到同样问题的小伙伴吗
