### ISSUE TITLE
Redirecting user based on its permission.

### ISSUE THREAD

**Issue by renatognunes** [ant-design/ant-design-pro#6649]
Is there a way to redirect the user to specific path based on its permission?
For example, user accessing homepage ' / ', if he has an admin permission, redirect him to one specific page, if he has a different permission, redirect him to another page.

My first approach was trying a variable or condition in the config.ts file. Although, it doesn't seem the best way to do it. 

``` 
routes: [
  {
     path: '/',
     redirect: REDIRECT USER TO A PATH BASED ON ITS AUTHORITY FLAG,
     authority: ['admin', 'guest'],
   },
];
```

**Comment by mohamedRhaiem** [comment]
You can resolve this in login component , check user role and redirect it to the required route.

**Comment by renatognunes** [comment]
> You can resolve this in login component , check user role and redirect it to the required route.

That would be a workaround. Although, I want to redirect them when they try to access the homepage. When they access the homepage, I want to redirect them based on their permissions. Not only when they login.

**Comment by chenshuai2144** [comment]
You can resolve this in https://github.com/ant-design/ant-design-pro/blob/bb040b1946bff874a539abe02ddff077404454df/src/utils/request.ts#L51

**Comment by renatognunes** [comment]
> You can resolve this in
> 
> https://github.com/ant-design/ant-design-pro/blob/bb040b1946bff874a539abe02ddff077404454df/src/utils/request.ts#L51
> 
> doc in here
> https://github.com/umijs/umi-request#example-1

Any example of how could I set this middleware to a way that everytime a user try to access the homepage he is redirected to another page based on its permission? 
Thanks!

**Comment by renatognunes** [comment]
@chenshuai2144 could you provide any example of how I redirect the user based on its permission? 

E.g.
When an user with "Admin" permissions try to access "homepage.com", I want to redirect him to "homepage.com/admin". When a guest tries to access "homepage.com", I want to redirect him to "homepage.com/guest".

The user permission tag is being saved in local storage when first logged in.

Thanks!
