### ISSUE TITLE
帅哥，请问一下umi3怎么配置分环境打包呢，不要网上说的那个复制config/config.js方法🧐[问题]

### ISSUE THREAD

**Issue by liufa520** [ant-design/ant-design-pro#6650]

**Comment by chenshuai2144** [comment]
配置分环境打包 是什么？能展开描述吗

**Comment by liufa520** [comment]
就是dev环境打dev环境的包，test环境打test环境的包，生产打生产的包，例如npm run build:dev或者npm run build:pre，配置这些脚本命令。因为每个环境的域名不一样。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈帅&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月23日(星期六) 上午10:19
收件人:&nbsp;&quot;ant-design/ant-design-pro&quot;<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;&quot;liufa&quot;<1404289545@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 帅哥，请问一下umi3怎么配置分环境打包呢，不要网上说的那个复制config/config.js方法&#x1F9D0;[问题] (#6650)

**Comment by chenshuai2144** [comment]
那不应该这样的，前端应该在哪里都一样，然后用 proxy 来区分环境

直接写环境很 hack 也不安全 万一放错了呢

**Comment by liufa520** [comment]
我的理解和你的一样，前几天客户向我提了这个问题。我很懵，我也不明白配置多环境打包有啥好处------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;陈帅&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月23日(星期六) 上午10:33
收件人:&nbsp;&quot;ant-design/ant-design-pro&quot;<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;&quot;liufa&quot;<1404289545@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 帅哥，请问一下umi3怎么配置分环境打包呢，不要网上说的那个复制config/config.js方法&#x1F9D0;[问题] (#6650)

**Comment by chenshuai2144** [comment]
可以增加很多 bug，让老板多找几个前端。
