### ISSUE TITLE
🧐[问题] fetchCurrent接口报错，退出登录页，第一次点击登录，SecurityLayout不渲染，导致需要点击两次

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6652]
### 🧐 问题描述

1.  fetchCurrent(拿用户的相关信息，有token过期时间)接口报错后，退出登录页
2.  点击登录需要点击两次

最后发现第一次点击登录按钮没有触发SecurityLayout的渲染

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
----
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
