### ISSUE TITLE
官网 ”搜索列表（应用）“ 页面出现🐛[BUG]

### ISSUE THREAD

**Issue by sujingclg** [ant-design/ant-design-pro#6653]
### 🐛 bug 描述

https://preview.pro.ant.design/list/search/applications
https://preview.pro.ant.design/list/card-list
卡片列表展示不整齐

### 📷 复现步骤

浏览器窗口最大化

### 🏞 期望结果

卡片整齐显示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
dep of https://github.com/ant-design/ant-design-pro/issues/6630
