### ISSUE TITLE
🧐[问题]菜单路由为外部地址

### ISSUE THREAD

**Issue by chenpeitao** [ant-design/ant-design-pro#6655]
### 🧐 问题描述
比如我的菜单的路由地址为www.baidu.com,怎么配置能新建窗口，而不是当前窗口打开

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/44704881/82628461-76d7e100-9c1f-11ea-9cf2-2f00513d9cb5.png)

**Comment by chenpeitao** [comment]
在#5834已解决

**Comment by afc163** [comment]
应该可以自动识别 http 开头的地址。

**Comment by chenshuai2144** [comment]
有这个识别的，也支持使用 target 的配置

https://github.com/ant-design/ant-design-pro-layout/blob/94c02e0280592a7c81222f6fda79b144824ec760/src/SiderMenu/BaseMenu.tsx#L204
