### ISSUE TITLE
use custom icon in the menu

### ISSUE THREAD

**Issue by shakesBeardZ** [ant-design/ant-design-pro#6656]
I'm trying to use Fontawesome in the menu icons, I've checked the docs it says edit ```getIcon``` function but I don't know where I can find it(the link not working)
I'm using ant design pro 4.0

![image](https://user-images.githubusercontent.com/15571628/82635390-bc3ce400-9c08-11ea-8529-bc32a71fb26b.png)

**Comment by chenshuai2144** [comment]
we only support iconfont 
https://www.iconfont.cn/

sorry， but you can use menuItemRender support any icon style

**Comment by shakesBeardZ** [comment]
@chenshuai2144 it's working thanks 
```
const menuDataRender = menuList =>
  menuList.map( item => {        
    const localItem = { 
      ...item, 
       icon: <FontAwesomeIcon className={styles.menuicons} icon={['far', item.iconName]}/>,
      children: item.children ? menuDataRender(item.children) : [] 
    };
    return Authorized.check(item.authority, localItem, null);
  });
```

**Comment by rkumar1904** [comment]
> @chenshuai2144 it's working thanks
> 
> ```
> const menuDataRender = menuList =>
>   menuList.map( item => {        
>     const localItem = { 
>       ...item, 
>        icon: <FontAwesomeIcon className={styles.menuicons} icon={['far', item.iconName]}/>,
>       children: item.children ? menuDataRender(item.children) : [] 
>     };
>     return Authorized.check(item.authority, localItem, null);
>   });
> ```

Hi, I have tried the above snippets but it's not working could you explain it a bit more.

**Comment by arifszn** [comment]
Using `Icon` should work.

https://ant.design/components/icon/#Custom-SVG-Icon
