### ISSUE TITLE
🐛[BUG]按照官方集成qiankun插件后，界面显示有问题，分为上下两层

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#6657]
### 🐛 bug 按照官方集成qiankun插件后，界面显示有问题，分为上下两层

按照官方集成qiankun插件后，界面显示有问题，分为上下两层

![image](https://user-images.githubusercontent.com/6110684/82642356-55d3b800-9c40-11ea-9977-98c73f0174a2.png)

**Comment by koupeng** [comment]
完整复现问题的代码库：
https://github.com/koupeng/and-design-pro-qiankun

**Comment by koupeng** [comment]
删除样式代码可以了。

**Comment by Shijiuwei** [comment]
> 删除样式代码可以了。

我也出现这个问题，删除样式代码，删除那部分代码呢

**Comment by CoderAha** [comment]
> 删除样式代码可以了。

删除哪部分的样式代码？
