### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by infinityboy** [ant-design/ant-design-pro#6659]
### 🧐 问题描述

在v5版本中，添加request，使用了umi-request的extend，想要加入拦截器等代码，这时登陆会抛异常
### 💻 示例代码
import React from 'react';
import { BasicLayoutProps, Settings as LayoutSettings } from '@ant-design/pro-layout';

import { notification } from 'antd';
import { history, RequestConfig } from 'umi';
import { extend, RequestMethod, RequestOptionsInit } from 'umi-request';
import RightContent from '@/components/RightContent';
import Footer from '@/components/Footer';
import { queryCurrent } from './services/user';

import defaultSettings from '../config/defaultSettings';

export async function getInitialState(): Promise<{
  currentUser?: API.CurrentUser;
  settings?: LayoutSettings;
}> {
  // 如果是登录页面，不执行
  if (history.location.pathname !== '/user/login') {
    try {
      const currentUser = await queryCurrent();
      return {
        currentUser,
        settings: defaultSettings,
      };
    } catch (error) {
      history.push('/user/login');
    }
  }
  return {
    settings: defaultSettings,
  };
}

export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings };
}): BasicLayoutProps => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};

const codeMessage = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
};

/**
 * 异常处理程序
 */
const errorHandler = (error: { response: Response }) => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};
/**
 * 配置request请求时的默认参数
 */

const requestExtend: RequestMethod = extend({
  errorHandler,
  // 默认错误处理
  credentials: 'omit',
});
// interface requestTypes {
//   url: string,
//   options: RequestOptionsInit
// }
// interface headers {
//   'Content-Type': string,
//   Accept: string,
//   'X-Access-Token': string | null,
//   [propName: string]: any;
// }
// // request拦截器, 改变url 或 options.
// requestExtend.interceptors.request.use((url: string, options: RequestOptionsInit): requestTypes => {
//   const token = localStorage.getItem('token');
//   const headers: headers = {
//     'Content-Type': 'application/json',
//     Accept: 'application/json',
//     'X-Access-Token': token,
//   };

//   if (!token) {
//     return {
//       url,
//       options: { ...options },
//     };
//   }
//   return {
//     url,
//     options: { ...options, headers },
//   };
// });

// // response拦截器, 处理response
// requestExtend.interceptors.response.use((response: Response) => {
//   const token = response.headers.get('X-Access-Token');
//   if (token) {
//     localStorage.setItem('token', token);
//   }
//   return response;
// });

// export const request: RequestConfig = {
//   errorHandler,
// };

export const request: RequestMethod = requestExtend;

### 🚑 其他信息
以上代码将拦截器注释，采用v5原mock登陆，会抛异常url不是string，但是servicezhong中url是string，是我的ts类型不对么？如果不对，请问该如何处理？

![image](https://user-images.githubusercontent.com/15925294/82646759-b87c8200-9c47-11ea-8b2a-49e0740f25dc.png)

**Comment by lvqibin123** [comment]
export const request: RequestConfig = {
  headers:headers,
  errorHandler,
  errorConfig: {
    adaptor: (resData, { res }) => {
      if (res.status != 200 && !resData.errorMessage) {
        const errorMessage = codeMessage[res.status] || res.statusText;
        return {
          ...resData,
          errorMessage,
        };
      }
      return resData;
    },
  }
};

这样处理就行了，访问加tonken，status不是200 又自己处理就行了，不要用拦截器了，不好用，资料还少，我都没有搜到一个demo了，这个应该可以满足要求了。

**Comment by dmdoit** [comment]
要仔细看文档啊。
```
/**
 * 请求拦截器
 */
const responseInterceptors = (url, options: RequestOptionsInit) => {
  const token = localStorage.getItem('token');
  const Authorization = token === null ? '' : `Bearer ${token}`;

  const headers: HeadersInit = {
    Accept: 'application/json',
    Authorization,
  };
  return {
    url,
    options: {
      ...options,
      headers,
    },
  };
};

export const request: RequestConfig = {
  errorHandler,
  requestInterceptors: [responseInterceptors],
};
```
文档地址：https://umijs.org/plugins/plugin-request#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE

![image](https://user-images.githubusercontent.com/19385704/97405356-795b0700-1932-11eb-842c-665e1afbeb0a.png)

**Comment by lvqibin123** [comment]
多谢了，我都不记得是什么问题了，应该是解决掉了。
