### ISSUE TITLE
🐛更新版本报错，请问这什么原因？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#6660]
### 🐛 更新版本报错，请问这什么原因？
![image](https://user-images.githubusercontent.com/37643958/82656388-42cbe280-9c56-11ea-89a5-618ac5368602.png)
![image](https://user-images.githubusercontent.com/37643958/82656432-58410c80-9c56-11ea-862a-44cdb0819fb7.png)
![image](https://user-images.githubusercontent.com/37643958/82656459-642cce80-9c56-11ea-875d-935fb4985c04.png)

**Comment by chenshuai2144** [comment]
看起来是国际化坏掉了， 你需要替换成新的 api
