### ISSUE TITLE
🧐[问题] 从自建 block 仓库下载区块报错。

### ISSUE THREAD

**Issue by juzhiyuan** [ant-design/ant-design-pro#6662]
### 🧐 问题描述

自建 Block 仓库，在使用下面命令时出错：
```bash
$ npx umi block add https://github.com/api7/apisix-dashboard-blocks/tree/master/BlockTemplate
```

从表现来看，是因为真实下载地址变为了 `gitee.com`。

![image](https://user-images.githubusercontent.com/2106987/82719970-acdd9980-9ce1-11ea-93dd-a5d2ff76bb2b.png)

![image](https://user-images.githubusercontent.com/2106987/82719971-b6670180-9ce1-11ea-9c54-febdbcd83249.png)

此外，通过 `yarn create umi --type=block` 创建的区块，文档中自动生成的命令是：
```bash
umi block https://github.com/api7/apisix-dashboard-blocks/tree/master/BlockTemplate
```

这个是不正确的。。

![image](https://user-images.githubusercontent.com/2106987/82720132-2e81f700-9ce3-11ea-8621-f786b60c607e.png)

### 💻 示例代码

None

### 🚑 其他信息

https://github.com/ant-design/ant-design-pro/issues/5554
https://github.com/ant-design/ant-design-pro/issues/5924
https://github.com/ant-design/ant-design-pro-cli/blob/master/src/fetch-blocks/index.js#L141
https://pro.ant.design/blog/better-block-cn
https://github.com/umijs/umi/pull/2641/files#diff-b1692be107cfe4a6c2f7d719398a69f0R60
https://github.com/umijs/umi/issues/4043
https://github.com/umijs/umi/issues/4649
https://github.com/umijs/umi/issues/3801

**Comment by juzhiyuan** [comment]
related issue https://github.com/umijs/umi/issues/4649

**Comment by sunsmeil** [comment]
遇到相同问题了

**Comment by juzhiyuan** [comment]
看 https://github.com/umijs/umi-ui/pull/75
