### ISSUE TITLE
🐛[BUG] 官网预览页面，第一次点击二级菜单，其父级菜单会收起，之后再次点击二级菜单，父菜单正常

### ISSUE THREAD

**Issue by leesama** [ant-design/ant-design-pro#6663]
### 🐛 bug 描述

官网预览页面，第一次点击二级菜单，其父级菜单会收起，之后再次点击二级菜单，父菜单正常

### 📷 复现步骤

官网预览页面，以及创建的项目都有这个问题

### 🏞 期望结果

此为设计如此？如果是，该如何改成父级菜单一直固定？
使用openKeys，进入页面时是打开了父级菜单，但第一次点击子项，父菜单还是会收起，之后就正常了。

### 💻 复现代码

还请尽快回复，非常想用V5，但是该问题会导致用户体验非常差

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本
- 浏览器环境
- 开发环境win10

**Comment by chenshuai2144** [comment]
是 bug

**Comment by linkai0001** [comment]
> 是 bug

v4 版本也有此问题，除了此问题，还有另外一个问题。
 第一次刷新页面，点击菜单收缩后， 点击其他栏目，会重新展开菜单。
从代码上开，点击栏目切路由后， 会重新调用 ProLayout  的 onCollapse 方法， 重新渲染 collapsed 的值导致。 onCollapse 并非路由切换触发的事件额？？？

**Comment by leesama** [comment]
@linkai0001 升级到最新版prolayout可以解决该问题 ，但我这边最后还是选择自行渲染菜单以满足需求

**Comment by linkai0001** [comment]
> @linkai0001 升级到最新版prolayout可以解决该问题 ，但我这边最后还是选择自行渲染菜单以满足需求

嗯，感谢， 刚才从另一个 issues 看到另一种解决方式， 将  umi 切为 3.1.4 版本，也解决了该问题了。

**Comment by linkai0001** [comment]
> @linkai0001 升级到最新版prolayout可以解决该问题 ，但我这边最后还是选择自行渲染菜单以满足需求

hello ， 用的版本是哪个呢？ 刚才把@ant-design/pro-layout升级到6.0.0-7 最新版本还是有问题哦(umi版本最新)！

**Comment by beevivo6** [comment]
#7524 @ @chenshuai2144 

> @chenshuai2144 
#
> @chenshuai2144 
机进入其中两个子菜单并切换，然后你再去收起的时候，收起要点击两次||，第一次点击二级菜单，其父级菜单会收起，之后再次点击二级菜单，父菜菜单没有收起，第二次点击才会收起...

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/98795842-aab0f800-2445-11eb-8164-2884d1cc6dee.png)
