### ISSUE TITLE
👑 [需求]antd 正式版的发布，为什么“最佳实战”还不出来？

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#6665]
### 🥰 需求描述

V4正式版发布，为什么最佳实战还不出来？

不要说最佳实战了，先来个实战看看也行啊 ！

**Comment by chenshuai2144** [comment]
V5 就是最佳实践，里面把很多东西都内置了，
数据流 权限和 国际化 layout 都提供了新方案
