### ISSUE TITLE
🧐[问题] antdp整体布局分导航和内容区域，怎样确认或获取内容区域的ID

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#6666]
### 🧐 问题描述

正在使用ant design pro作为qiankun的底座，内容区域用于渲染子应用，但是发现内容区域ID不固定，怎么设置为固定的？或者有其他思路么？

**Comment by chenshuai2144** [comment]
去乾坤问一下？
他们是通过 config.js 中的 [mountelementid](https://umijs.org/config#mountelementid) 来实现动态的
