### ISSUE TITLE
虚拟机下无法热更新问题

### ISSUE THREAD

**Issue by Chenqt5** [ant-design/ant-design-pro#6667]
本机是MAC.
在MAC跑了一个Linux虚拟机
编辑文件无法引起重新编译，每次都需要重新编译很久
开发上非常痛苦。

尝试过HMR=reload和Watch=True都没有效果

**Comment by chenshuai2144** [comment]
我们的 CI 都是在 linxu 跑的，你的问题可能是大小写导致的。

**Comment by Chenqt5** [comment]
请不要着急关闭issue
我是一名后端人员，在这里遇到了一些困难，寻求帮助
