### ISSUE TITLE
🧐[问题]V5 app.tsx中如何使用useIntl或injectIntl

### ISSUE THREAD

**Issue by fjnetinfo** [ant-design/ant-design-pro#6668]
### 🧐 问题描述

V5 app.tsx中如何使用useIntl或injectIntl.

app.tsx里面有几个notification(如 errorHandler中的汉字)怎么用 useIntl或injectIntl 国际化替换提示

**Comment by chenshuai2144** [comment]
> app.tsx里面有几个notification(如 errorHandler中的汉字)怎么用 useIntl或injectIntl 国际化替换提示

那个是 demo 的，你应该删掉的。

> V5 app.tsx中如何使用useIntl或injectIntl.

直接用 formatMessage 好了，warning 只有在开发模式下显示，如果建议这个可以用 injectIntl
