### ISSUE TITLE
🧐[问题] intl.formatMessage 如何传参

### ISSUE THREAD

**Issue by fjnetinfo** [ant-design/ant-design-pro#6669]
### 🧐 问题描述

有些国际化语句需要参数，这个怎么用。求大佬。谢谢。

**Comment by chenshuai2144** [comment]
第二个参数就是了，建议读一下 react intl 的 demo
`intl.formatMessage({id:string},values)`

**Comment by fjnetinfo** [comment]
> 第二个参数就是了，建议读一下 react intl 的 demo
> https://github.com/formatjs/formatjs
> `intl.formatMessage({id:string},values)`

谢谢。
