### ISSUE TITLE
🐛[BUG]生产环境的请求代理，都代理到了https://proapi.azurewebsites.net/

### ISSUE THREAD

**Issue by Wmstone** [ant-design/ant-design-pro#6670]
### 🐛 bug 描述
生产环境的请求代理，都代理到了https://proapi.azurewebsites.net/

本地开发 
proxy: {
    '/api/': {
      target: 'http://10.xxx.xxx.xx:8081',
      changeOrigin: true,
      pathRewrite: { '^/api/': '' },
    },
  },
代理正常
生产环境使用nginx，配置没有问题，之前部署也没有问题，这次发版是升级了Antd4.0同时升级了其它包，出现了代理到https://proapi.azurewebsites.net/
### 🏞 期望结果
希望代理正常

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.2.4
- umi 版本  3.2.1
- 浏览器环境 谷歌
- 开发环境 [e.g. mac OS]  Windows

### 🚑 其他信息
 "@ant-design/compatible": "1.0.0",
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.12",
    "@ant-design/pro-table": "^2.2.8",
  "@ant-design/pro-cli": "^1.0.14",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^24.0.23",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.8.19",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^5.0.13",
    "@umijs/fabric": "^2.0.5",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/preset-ui": "^2.0.9",

**Comment by kaoding** [comment]
是不是代理的IP和原来的url没有对应上啊

**Comment by Wmstone** [comment]
是这个包umi-plugin-pro 里面写死了const gaTpl = function (serverUrl = 'https://proapi.azurewebsites.net/') ，我为什么会用这个包呢，，，，
