### ISSUE TITLE
🐛[BUG] V4 查询表格在全屏状态下点击新建的问题

### ISSUE THREAD

**Issue by yaozhongnan** [ant-design/ant-design-pro#6672]
### 🐛 bug 描述

全屏状态下点击新建后，Modal 组件显示在全屏外。

### 📷 复现步骤

1、打开 [官方预览项目的查询表格页面](https://preview.pro.ant.design/list/table-list)
2、点击表格的 toolbar 的全屏按钮
3、点击新建

### 🏞 期望结果

在全屏状态下展示该 Modal

**Comment by kaoding** [comment]
https://github.com/ant-design/pro-table/issues/49
