### ISSUE TITLE
🐛[BUG] 下载全部区块时报错

### ISSUE THREAD

**Issue by yysfwls** [ant-design/ant-design-pro#6673]
![image](https://user-images.githubusercontent.com/29426633/82792630-405dc880-9ea2-11ea-837c-f941aa84d561.png)

（选择simple不会报错

**Comment by chenshuai2144** [comment]
https://github.com/umijs/sylvanas/blob/master/__tests__/optionalChaining.test.js

应该是你全局安装了低版本的 babel 的问题。尝试升级一下 babel 系列，或者从全局删掉
