### ISSUE TITLE
V4版本如何使用第三方的enhanceReduxMiddleware 🧐[问题]

### ISSUE THREAD

**Issue by GloriaCHL** [ant-design/ant-design-pro#6674]
### 🧐 问题描述

上个版本 src 目录有个 app.js 文件，可以在里面配置第三方的 reducers，但我当前使用的版本里取消了app.js变成app.tsx，我应该怎么去添加第三方的reducers以及对应的actions呢？

### 💻 示例代码
旧版 app.js 里的配置代码：

```
// 扩展 dva 配置，顺手解决之前的 dva.js 不支持额外的 dva plugin 的问题
export const dva = {
  config: {
    onError() {},
    initialState: {},
  },
  plugins: [
    {
      onAction: enhanceReduxMiddleware([]),
      extraReducers: {
        customReduces: customReduces,
      },
    },
    // { onAction: require('redux-logger').createLogger() },
    // require('dva-logger'),
  ],
};
```

### 🚑 其他信息

我现在使用的 "@ant-design/pro-cli": "^1.0.18" 里试图在 app.tsx 里加第三方的reducers没加成功。请问我该如何设置？

---- 

另外好像v4最新的代码连app.tsx都没有了，这版又该如何配置第三方reducers？

**Comment by chenshuai2144** [comment]
@GloriaCHL  和原来一样的，继续在 app.tsx 中配置。
https://umijs.org/plugins/plugin-dva#%E7%BA%A6%E5%AE%9A%E5%BC%8F%E7%9A%84-model-%E7%BB%84%E7%BB%87%E6%96%B9%E5%BC%8F

**Comment by chenshuai2144** [comment]
好像不行！
@ycjcl868

**Comment by GloriaCHL** [comment]
@chenshuai2144 我目前有app.tsx中贴入上一版app.js里的dev配置代码是可以的。不过最新版貌似连app.tsx都没有了这个就不知道了，没尝试。

**Comment by Feather130** [comment]
4.x版本没有app.tsx只有global.tsx，按照之前的写法，貌似没有效果

**Comment by YanYuanFE** [comment]
最新版没有app.tsx，可以手动创建app.tsx文件，写入以下代码，重启ok的:
```
import { createLogger } from 'redux-logger';

export const dva = {
  config: {
    onError(err) {
      err.preventDefault();
    },
    onAction: createLogger(),
  },
};

```
