### ISSUE TITLE
🐛[BUG]第一次载入页面，菜单仅图标时，图标没有居中

### ISSUE THREAD

**Issue by Starpuccino** [ant-design/ant-design-pro#6678]
### 🐛 bug 第一次载入页面，菜单仅图标时，图标没有居中

第一次载入页面，如果屏幕宽度不够，菜单只图标；
但是这个图标没有居中耶，要鼠标移进去才会居中

### 📷 复现步骤
浏览器宽度调小，比如800px，然后打开 https://preview.pro.ant.design/dashboard/analysis
发现侧边栏图标没有居中
<img width="976" alt="QQ20200526-012549@2x" src="https://user-images.githubusercontent.com/33953383/82833453-98bbb700-9ef0-11ea-9e79-899555ced95c.png">

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本 3.1.2
- 浏览器环境 Edge Chromium 81.0.416.77
- 开发环境 macOS

**Comment by chenshuai2144** [comment]
666，牛逼

antd 最近加了个 icon 的设置导致动画有点小问题。我来跟进一下

**Comment by chenshuai2144** [comment]
fixed by antd
