### ISSUE TITLE
🐛[BUG]ncaught (in promise) TypeError: antd_es_form__WEBPACK_IMPORTED_MODULE_20__.default.create(...) is not a function

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#6679]
### 🐛 bug 描述

之前使用的是antd-Pro2的版本，有很多写法如下。
const CreateForm = Form.create()(props => {
  const { modalVisible, confirmLoading, form, handleAdd, handleModalVisible } = props;
  const okHandle = () => {
    form.validateFields((err, fieldsValue) => {
      if (err) return;
      handleAdd(fieldsValue);
    });
  };

现在这些代码迁移到Pro4.0全部报错。
Uncaught (in promise) TypeError: antd_es_form__WEBPACK_IMPORTED_MODULE_20__.default.create(...) is not a function

**Comment by chenshuai2144** [comment]
这是 antd 的升级，已经换了用法了
https://ant.design/docs/react/migration-v4
https://pro.ant.design/blog/antd-4.0-cn

**Comment by Wmstone** [comment]
import { Form} from '@ant-design/compatible';看一下是不是有的Form导入是有问题的？ @koupeng
