### ISSUE TITLE
前台预留

### ISSUE THREAD

**Issue by callmez** [ant-design/ant-design-pro#668]
虽然很可能这个提议不会被采纳, 但是我觉得还是有必要提一下. 各位看官可以给出留言来说下自己看法. 

`ant design pro`是一个很出色的产品.  我们的项目也在0.x的时候就采用了.  当时采用的时候出发点就是一个纯后端管理应用.
 但是随着迭代深入, 我们发现很多后台和前台的应用都是复用了很多组件, 并且逻辑几乎差不多. 

然后决定前端合并.  应用逻辑上的合并很清晰也很轻松(前后端复用), 但是在基础结构层面上做了很多工作(主要做了很多区分前后端场景的结构修改).  甚至mobile端也可以部分逻辑复用(其实后来也合并进来了).  然后就构成了一个大型的整站应用.
项目初上线来说其实并没有太多的多端维护困扰, 
好处是我们省了维护多端的复用逻辑, 也不用多端项目库跳来跳去找问题.  不好也有协同开发需要更多的开发约定和逻辑判断预留(其实只要更加的拆分组件也不会太麻烦)

所以建议pro在前后台部分预留出一块前(frontend, mobile)后(backend,)端基础结构. 以便中小型项目可以迅速开始上手开发.  节省项目初始启动成本. 谢谢!

**Comment by xiaosongxiaosong** [comment]
@callmez 请教一下 mobile 端与 桌面端的基础样式与组件库如何分开打包成两个两个不同的公共包啊？我了解的情况是 roadhog 设置为多页应用的时候会将公共部分打包成 common.css 和 common.js，没有看到比较简单的方法指定哪些包打包在一起

**Comment by callmez** [comment]
我是通过webpack.config.js自己配置的
