### ISSUE TITLE
🐛[BUG]Umi UI 添加多个空白页，就会出错！把空白页都变成选中状态！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#6680]
### 🐛 bug 描述
添加两个 空白页 就变成这样了！

默认两个都选择了，不管是V4，还是V5，都这样！

### 📷 复现步骤
![QQ图片20200526100557](https://user-images.githubusercontent.com/51880332/82853860-67b3a480-9f39-11ea-9de5-4fc0c8cd7ffb.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
path是一样的，就应该被选中
