### ISSUE TITLE
🧐[问题] build 后还存在 es6 的代码（Umi@2.13.13）

### ISSUE THREAD

**Issue by jing-wu** [ant-design/ant-design-pro#6685]
### 🧐 问题描述

执行 build 命令后，打包生成的 umi.js 中包含 const、=> 这些 es6 代码，在 ie11 上运行报错

打包后的代码：
<img width="825" alt="const" src="https://user-images.githubusercontent.com/6805536/82874606-c6dcdd80-9f68-11ea-87a0-247c2c638dfc.png">

### 🚑 其他信息

config.ts 中已经配置了 targets：

`targets: {
    ie: 11,
  },`

依赖：

    "@ant-design/icons": "^4.1.0",
    "@ant-design/pro-layout": "^5.0.12",
    "@ant-design/pro-table": "^2.2.9",
    "@antv/data-set": "^0.11.4",
    "ace-builds": "^1.4.11",
    "antd": "^4.2.5",
    "bizcharts": "^3.5.9",
    "bizcharts-plugin-slider": "^3.0.1",
    "classnames": "^2.2.6",
    "dva": "^2.6.0-beta.16",
    "dva-model-extend": "^0.1.2",
    "form-render": "^0.5.5",
    "lodash": "^4.17.11",
    "moment": "^2.26.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.4",
    "react": "^16.13.1",
    "react-ace": "^8.1.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^5.2.1",
    "redux": "^4.0.1",
    "umi": "^2.13.13",
    "umi-plugin-antd-icon-config": "^1.0.2",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.15.8",
    "umi-request": "^1.3.2",
    "use-merge-value": "^1.0.1"

**Comment by chenshuai2144** [comment]
umi@2 不会编译 node_moudle 里的，你可以检查一下里面是不是有的什么库用了 es6

**Comment by jing-wu** [comment]
排查出问题了，在 src 下的一个 ts 文件中，import 了 config.ts，打算读取某个配置项的，导致了这个问题。后来改用注入环境变量的方式解决了。

但是话说回来，为啥这样直接 import config.ts 会出现这个问题

**Comment by afc163** [comment]
umi 应该只会处理 src 里面的文件。
