### ISSUE TITLE
🧐[问题]默认登录参数 userName 为什么不用 username？

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6686]
### 🧐 问题描述

后端搭配 egg-passport 使用 passport-local 本地鉴权方式，插件默认认的是 username & password，为什么 Pro 要使用 userName？这是有什么用意吗？

另外请教，egg-passport 可以配置 使用 userName 吗？
在 config.default.js 中配置了下面参数，还是没用 ~
```
passportLocal: {
  usernameField: 'userName',
  passwordField: 'password',
},
```

**Comment by kaoding** [comment]
这个问题可以改进一下，保持一致。

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/pull/6687

**Comment by kaoding** [comment]
> 问题已经解决了，感觉 eggjs 官方文档关于 passport-local 这一块没写好，应该直接介绍 egg-passport-local 插件的用法，会更简单一些 ~ （记得很久之前就折腾过一次，后来放弃了，这次是对 eggjs 熟悉一些了，有进步了 @@）

文档你到这里提PR:
https://github.com/ant-design/ant-design-pro-site

**Comment by 510846** [comment]
> 这个问题可以改进一下，保持一致。

您好，大神！请教一个比较菜的问题，如何可以基于分支提交PR？（我想针对 v5 分支）
