### ISSUE TITLE
🐛[BUG]无法创建工程npm create umi

### ISSUE THREAD

**Issue by leoluo0818** [ant-design/ant-design-pro#6688]
### 🐛 bug 描述

使用
`npm create umi`
`yarn create umi`
命令，选择类型：ant-design-pro，抛出异常如下：

(node:59887) UnhandledPromiseRejectionWarning: Error: Cannot find module 'core-js-pure/stable/object/define-property'
Require stack:
- /Users/leo/.config/yarn/global/node_modules/@babel/runtime-corejs3/core-js-stable/object/define-property.js
- /Users/leo/.config/yarn/global/node_modules/xregexp/lib/index.js
- /Users/leo/.config/yarn/global/node_modules/eslint-plugin-react/lib/rules/jsx-pascal-case.js
- /Users/leo/.config/yarn/global/node_modules/eslint-plugin-react/index.js
- /Users/leo/.config/yarn/global/node_modules/eslint/lib/config/plugins.js
- /Users/leo/.config/yarn/global/node_modules/eslint/lib/config.js
- /Users/leo/.config/yarn/global/node_modules/eslint/lib/cli-engine.js
- /Users/leo/.config/yarn/global/node_modules/eslint/lib/api.js
- /Users/leo/.config/yarn/global/node_modules/sylvanas/lib/eslintJs.js
- /Users/leo/.config/yarn/global/node_modules/sylvanas/lib/index.js
- /Users/leo/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js
- /Users/leo/.config/yarn/global/node_modules/create-umi/lib/run.js
- /Users/leo/.config/yarn/global/node_modules/create-umi/cli.js
Referenced from: /Users/leo/.config/yarn/global/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/leo/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
Referenced from:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/leo/.config/yarn/global/node_modules/@babel/runtime-corejs3/core-js-stable/object/define-property.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:59887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### © 版本信息
- 开发环境 [mac OS, node  v14.3.0, npm 6.14.4]

**Comment by chenshuai2144** [comment]
清空一下全局的依赖。

**Comment by leoluo0818** [comment]
尝试过了，都重新安装了nodejs与npm，也删掉了全局的node_modules。
