### ISSUE TITLE
权限路由后端返回之后，组件无法加载

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/ant-design-pro#6691]
### 🧐 问题描述

1. 登录完成之后，请求后端返回的当前用户的菜单列表然后渲染给MenuData.

### 💻 示例代码

1. BasicLayout.tsx 的部分代码:
 useEffect(() => { // hook设置进去
    getMenuData().then((response) => {
      if (response.success) {
        setMenuData(response.data)
      }
    });
  }, []);

2.  BasicLayout的ProLayout里面：
// 这个是按照官方提示，渲染上icon string不显示的问题
const menuDataRender = (menus: MenuDataItem[]): MenuDataItem[] =>
  menus.map(({ icon, children, ...item }) => ({
    ...item,
    icon: icon && IconMap[icon as string],
    children: children && menuDataRender(children),
  }));

menuDataRender={()=> menuDataRender(menuData || [])}

3.//  后端返回格式大致 response如下
{
"success":true,"code":"200","data":[
      {  "icon":"smile","path":"/authority-manage",
         "name":"权限管理","component":"/",
        "authority": ["user"],
         "children":[
            { 
            "path":"/authority-manage/role","component":"./RoleManage",
             "name":"角色管理","icon":"smile", "authority":["user"]
            },
           { 
            "path":"/authority-manage/account","component":"./AccountManage",
             "name":"账号管理","icon":"smile", "authority":["user"]
            }
       ]
  }
}

4. 我的config.ts 的
 routes: [
    {
      path: '/user',
      component: '../layouts/UserLayout',
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: './user/login',
        },
      ],
    },
    {
      path: '/',
      component: '../layouts/SecurityLayout',
      routes: [
        {
          path: '/',
          component: '../layouts/BasicLayout',
          authority: ['admin', 'user'],
          routes: [ // 我的理解是，直接把menudata设置到这里，所以我清空了
          ],
        },
        {
          component: './404',
        },
      ],
    },
    {
      component: './404',
    },
  ],
 

5.现在的问题是我的菜单列表可以正常渲染，但是点击菜单无法显示组件，挂载的组件找不到了。起初怀疑是后端返回的children要改成routes,但是还是无效，咨询朋友们说是：服务端给的"component":"./RoleManage" 这个组件路径是不行的，不支持这种方式处理，但是又有人说是支持的，然后我另外一个朋友说是支持的，希望知道的朋友给个建议。不胜感激。

6.我的版本是V4,然后描述不清楚，需要我补充的跟我说下。
![1590500885(1)](https://user-images.githubusercontent.com/30285121/82908547-b5142e00-9f9a-11ea-886c-e79030b467db.jpg)

**Comment by chenshuai2144** [comment]
config.js 的路里面的配置时必须的。不然 umi 不知道该渲染什么组件。
如果要做服务器返回菜单，需要把所有的路由都配置到 config.js。 服务器返回的菜单数据要喝 config.js 中对应

**Comment by CodingZJ** [comment]
确实，解决了，后端接口不需要组件。没注意

**Comment by wulinjie122** [comment]
> config.js 的路里面的配置时必须的。不然 umi 不知道该渲染什么组件。
> 如果要做服务器返回菜单，需要把所有的路由都配置到 config.js。 服务器返回的菜单数据要喝 config.js 中对应

但是在config.js配置了一份，后台服务器又返回了一份，就没必要了，重复的工作。

**Comment by xiaoxiaofan123** [comment]
请问你解决之后是怎么配置的呢，在config.js里全量配置，服务器只返回需要显示的菜单路由么
