### ISSUE TITLE
🧐[问题]ant design pro v4,  後台和前台在不同的機器, 如何設置.

### ISSUE THREAD

**Issue by realcyma** [ant-design/ant-design-pro#6692]
### 🧐 问题描述

後台和前台需要在不同的機器運行.  

在dev 環境中, 設置了用proxy,  (npm run start:no-mock)  成功運行. 能夠在後台找到api 和資料.
但在production, 生產環境. (npm run build, 然後用express 打開 dist).  前台沒有問題, 頁面可以顯示, 但找不到後台api.  結果找不到資料.

### 💻 示例代码
直接修改了config.js 的proxy.
export default defineConfig({ 
...
proxy: {
    '/api': {
      target: 'http://...backend server url....',
      changeOrigin: true,
    },
  },
...

### 🚑 其他信息

在生產環境, 
notification 報錯顯示, 他在前台的本機找API.  而不是後台的本機.
在chrome 的network trace, fetch API 時, 回報 404.

**Comment by TianenPang** [comment]
生产环境可使用Nginx做反向代理，通过反向代理将请求转发到后台的服务器上。

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn

看着这个文章
