### ISSUE TITLE
🧐[问题] 今天 create 的 project 有个错误 ~

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6693]
`yarn create umi`

昨天 create 都还没有这个错误，就今天的发现了 ~ 特此报告 ~~

devScripts.js:5035 Warning: Received `false` for a non-boolean attribute `title`.
If you want to write it to the DOM, pass a string instead: title="false" or title={value.toString()}.
If you used to conditionally omit it with title={condition && value}, pass title={condition ? value : undefined} instead.

![image](https://user-images.githubusercontent.com/7681405/82971499-694a9e80-a005-11ea-9e23-14c9eee6e780.png)

**Comment by chenshuai2144** [comment]
antd 那里的透传问题，我会修一下

**Comment by 510846** [comment]
> 传问题，

另外，今天更新的版本还有一个问题

defaultSettings.ts
layout: 'mix' => 'side'
更改后，头部的收缩菜单按钮不见了，侧边菜单的阴影也不见了，一起看看 ~

![image](https://user-images.githubusercontent.com/7681405/82984752-56e05d00-a025-11ea-9d7b-7402b9d4addc.png)

下图是之前正常的效果
![image](https://user-images.githubusercontent.com/7681405/82984786-695a9680-a025-11ea-96e5-c113ce3f0ac7.png)


BTW: 用的是 Pro V5，这个版本感觉非常赞👍，很多地方做了调整，更合理了 ~

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/6434#issuecomment-631923936

**Comment by chenshuai2144** [comment]
都跑到下面了

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/478

**Comment by 510846** [comment]
> 都跑到下面了

再提一个问题，之前都有脚本可以将所有的页面拉下来的，现在没了？ 因为新版本变化比较大，我想参考最新版本的页面代码，还有别的方法吗？
