### ISSUE TITLE
🐛[BUG]首次切换路由BasicLayout会重新渲染

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design-pro#6694]
### 🐛 bug 描述

今天项目upgrade之后发现，首次切换路由`BasicLayout`会重新渲染，然后官网预览也是这个问题，线上运行的版本没有这个问题

### 📷 复现步骤

打开官网随便一个页面，清理通知，点击菜单栏切换，整个页面重新渲染了，通知、用户信息再次触发请求
![image](https://user-images.githubusercontent.com/23520283/82992170-5b127780-a031-11ea-8077-4ed0240957c1.png)

### 🏞 期望结果

`BasicLayout`只渲染一次

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Liu-Ya** [comment]
@chenshuai2144 陈总看一眼

**Comment by linxianxi** [comment]
![image](https://user-images.githubusercontent.com/47104575/83218238-486a8080-a1a0-11ea-81d6-4cc05286aeed.png)
遇到同样的问题  history.push(window.location.pathname)  第一次会触发页面摧毁重载,继续点击就不会。F5刷新后重新出现此问题。只有第一次会。

我的umi之前是3.1.4版本，不会有此问题 ，升级到3.2.1之后出现此问题，好像是3.1.4版本之前也有这个问题，我试了一个。 你升级到3.1.4版本试一下。

**Comment by atzcl** [comment]
这个是 umi 的 layout 处理问题: https://github.com/umijs/umi/issues/4104

**Comment by linkai0001** [comment]
> 这个是 umi 的 layout 处理问题: [umijs/umi#4104](https://github.com/umijs/umi/issues/4104)

hello,  这个问题解决了吗？ 也遇到了这个问题， 首次刷新页面后，点击栏目会导致  ProLayout 重新被渲染， 而且 onCollapse 也被会触发，导致原本收起的菜单栏，重新被展开（步骤： 刷新页面-》 收起菜单 -》点击其他菜单）。

**Comment by linkai0001** [comment]
没事了， 按楼上的切到了 3.1.4 版本后解决了该问题了。

**Comment by xuwenqing2014** [comment]
我切到3.1.4也没解决，有官方解决方案么

**Comment by lirunwin** [comment]
3.2.9出现此问题

**Comment by ycjcl868** [comment]
修复了
