### ISSUE TITLE
🐛[BUG] Pro V5 access 疑问

### ISSUE THREAD

**Issue by 510846** [ant-design/ant-design-pro#6695]
新版本使用 access 来控制导航菜单显示，这个改进感觉是挺好，不过我发现这个并不能限制住手工输入 未授权 url （之前使用 authority 的时候，访问未授权 url 会自动出现 403 页面），这个是还没有完成？还是说不实现了？

—— 今天发现会有 403 页面， 但是如果是 “子” 路径中的页面则不会有这个 403 重定向

如下：place_an_order 页面定义了 canPlace，当没有权限去访问该页面，不会重定向到 403 ~

**—— 经过反复测试，发现了没有跳转到 403 页面是因为 后面的 details 菜单，这个应该属于一个 bug，因为 路由匹配的是 place_an_order 页面，可是权限判断缺匹配了 details 页面，请检查！**
```
{
  name: 'order',
  icon: 'icon-order',
  path: '/orders',
  component: './order',
},
{
  name: 'place_an_order',
  icon: 'plus',
  path: '/orders/create',
  component: './order/create',
  access: 'canPlace',
},
{
  name: 'details',
  path: '/orders/:id',
  component: './order/details',
  hideInMenu: true,
},
```

**Comment by joesdu** [comment]
估计你用法不对吧,我都是OK的.

**Comment by 510846** [comment]
> 估计你用法不对吧,我都是OK的.

**—— 经过反复测试，发现了没有跳转到 403 页面是因为 后面的 details 菜单，这个应该属于一个 bug，因为 路由匹配的是 place_an_order 页面，可是权限判断缺匹配了 details 页面，请检查！**

是上面这个原因，你试试给你的路由配置中，增加上面三条规则试试看 ~

**Comment by lvqibin123** [comment]
access.ts文件是这样的
export default function (initialState = {}) {
  const { isAdmin, hasRoutes = [] } = initialState;
  debugger;
  return {
    // ...
    adminRouteFilter: () => isAdmin, // 只有管理员可访问
    normalRouteFilter: (route) => hasRoutes.includes(route.name), // initialState 中包含了的路由才有权限访问
  };
}

这个是我在网上找的的关于@umijs/plugin-access的使用
config.ts
  routes: [
                {
                  name: 'menu',
                  icon: 'smile',
                  path: '/sys/menu',
                  access: 'normalRouteFilter', // 权限定义返回值的某个 key
                  // authority: ['/sys/menu'],//配置准入权限,可以配置多个角色
                  component: './sys/menu',
                },
但是取到的这个值是空的
我还要配置什么地方吗

**Comment by CaicoLeung** [comment]
我也遇到和你一样的问题. 登录跳转后, access的route(如你代码)没有name属性, 要刷新页面才会成功获取

**Comment by chenshuai2144** [comment]
现在会强制刷新整个 dom 🌲

**Comment by h1nson** [comment]
我也是通过url访问 没有出来403页面 不知道怎么配置了。
