### ISSUE TITLE
🧐[问题] 如何编译提速 Pro V4，请给个明示！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#6696]
### 🧐 问题描述

现在编译就需要很久在69%那个位置，使劲儿跑，跑着跑着CPU就开始飙升，我的CPU温度能到到100度，关闭了温度又恢复正常了！

请问如何降低呢？

**Comment by hot588** [comment]
配置 nodeModulesTransform 为 { type: 'none' }

这一招，我试了试，确实有效果！现在CPU的温度减少到85度了！

**Comment by afc163** [comment]
https://umijs.org/zh-CN/guide/boost-compile-speed
