### ISSUE TITLE
🐛[BUG]ProTable的options会导致 Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by tmzhenzheng** [ant-design/ant-design-pro#6698]
### 🐛 bug 描述
ProTable的options会导致 Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

设置为false时就没有这个Warning了

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

**Comment by chenshuai2144** [comment]
fixed
