### ISSUE TITLE
🧐V5版本如何固定一级菜单，只在用户点击的时候关闭

### ISSUE THREAD

**Issue by leesama** [ant-design/ant-design-pro#6701]
V5版本如何固定一级菜单，只在用户点击的时候关闭？
现在打开defaultOpenAll后是点击其中一个菜单项后，其他一级菜单会自动关闭，如何使其一直固定，只有用户主动点击时才关闭

**Comment by leesama** [comment]
通过自定义菜单渲染完美解决

**Comment by cdz620** [comment]
通过设置layout的运行时配置，openKeys: false 解决
