### ISSUE TITLE
DefaultSettings设置改为layout: 'topmenu',报rightContentRender有错误

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#6703]
我现在yum 一个新的ant design pro simple 代码，然后，啥也不干，就只改下DefaultSettings的layout: 'topmenu'，
![image](https://user-images.githubusercontent.com/32530210/83106675-73e16280-a0ef-11ea-8033-e5cd0266b119.png)
出现如下错误，
![image](https://user-images.githubusercontent.com/32530210/83106725-8a87b980-a0ef-11ea-96b7-0e463d61daac.png)
错误代码説的是这里。
![image](https://user-images.githubusercontent.com/32530210/83106773-9c695c80-a0ef-11ea-94d0-e3fbd661e6dc.png)

不影响使用，但我这个有强迫症的人，过不了，有啥方法解决没。

**Comment by chenshuai2144** [comment]
修了，等待发版本

https://github.com/ant-design/ant-design-pro-layout/commit/91d30487196cf0c47d6a8ef52db179af73460250

**Comment by xyzabc0004** [comment]
牛！！！
@chenshuai2144 ，我终于提了一个有意义的问题。

发了能不能，来个邮件告知下，我也得改下。
