### ISSUE TITLE
🧐[问题]V5版本如何删除国际化啊？

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-pro#6704]
### 🧐 问题描述

1、执行了npm run i18n-remove
2、删除了locales文件夹

antd的国际化也没了，现在希望antd能默认成中文就ok了!

看到其他回答说包一层antd的ConfigProvider,具体应该在哪加了？
### 💻 示例代码
无

### 🚑 其他信息
无

**Comment by WangJM001** [comment]
```js
// src/app.js
export function rootContainer(container) {
  return React.createElement(
    ConfigProvider,
    {
      locale: zhCN,
    },
    container,
  );
}
```

**Comment by CodingZJ** [comment]
V4如何处理呢？ts版本，并没有app.js 也没找到App @WangJM001
