### ISSUE TITLE
未登录跳到首页不会跳到登陆页面？？🧐[问题]

### ISSUE THREAD

**Issue by oaifshdfaseo** [ant-design/ant-design-pro#6707]
项目启动自动跳到首页，怎样才能启动跳到登陆页？
修改了config.js的首页地址后，就一直在登录页了

**Comment by chenshuai2144** [comment]
把 `/user` 放到最前面,并且 配置 重定向。
https://github.com/ant-design/ant-design-pro/blob/eacaa274f088590b2681d4ebbbb1c328de32cea8/config/config.ts#L49
