### ISSUE TITLE
如何部署pro

### ISSUE THREAD

**Issue by Hsinky** [ant-design/ant-design-pro#671]
安装了pro项目后，执行npm run build生成的文件(没有api这个目录，见图一)部署到iis下后，提示截图种的错误(图二)，该如何处理呢？
![1](https://user-images.githubusercontent.com/10111222/34858021-f3dca96c-f788-11e7-98fe-15ef5554622e.png)
![2](https://user-images.githubusercontent.com/10111222/34858030-fb4711c4-f788-11e7-8af4-75124ba249bb.png)

**Comment by chenshuai2144** [comment]
你需要一个服务。 mock只是为了让你方便调试而已

**Comment by Hsinky** [comment]
初入有点不太懂。您的意思是这个api的地址是后台提供的一个地址？如果是这样怎么统一修改？另，如果就用pro提供的api又如何部署呢？

**Comment by chenshuai2144** [comment]
用node写一个一样的。
https://segmentfault.com/a/1190000009329474
先看看什么是前后端分离

**Comment by Hsinky** [comment]
@chenshuai2144 我的意思是，pro项目如何切换到我指定的api的地址？在services那个目录里面请求的都是api/../..

**Comment by Hsinky** [comment]
@chenshuai2144 帮我根据pro项目解释一下吧

![3](https://user-images.githubusercontent.com/10111222/34858735-ee06da0e-f78c-11e7-8927-cc6fb1c5463c.png)

![4](https://user-images.githubusercontent.com/10111222/34858849-9c87b08a-f78d-11e7-84d7-8d3775428907.png)
