### ISSUE TITLE
🐛[BUG]只有 pages 或 page 目录下的页面才能插入资产

### ISSUE THREAD

**Issue by qq1778551951** [ant-design/ant-design-pro#6710]
### 🐛 bug 描述

只有 pages 或 page 目录下的页面才能插入资产
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个功能已经废弃并停止维护，如果需要建议自行frok维护。
——
This function has been abandoned and stopped maintenance. If necessary, it is recommended to start maintenance by yourself.
