### ISSUE TITLE
🐛[BUG] hideInMenu 后面包屑缺失，网页标题与 PageHeader 标题变为默认值

### ISSUE THREAD

**Issue by i-Ethan** [ant-design/ant-design-pro#6712]
### 🐛 bug 描述

hideInMenu 后面包屑缺失，网页标题与 PageHeader 标题变为默认值

### 📷 复现步骤

在 /config/config.ts 中为某个菜单项添加 hideInMenu: true 属性

### 🏞 期望结果

仅在菜单中隐藏该路由，不影响页面标题和面包屑

### © 版本信息

2020 年 05 月 29 日使用 yarn create umi 创建的 Pro V4 项目（simple / complete 都有问题）

### 🚑 其他信息

以官方 demo 项目为例：
hideInMenu: false 时
![image](https://user-images.githubusercontent.com/6869602/83239941-436ef680-a1cb-11ea-8248-3f6e5f97ce6b.png)

hideInMenu: true 时
![image](https://user-images.githubusercontent.com/6869602/83240145-8a5cec00-a1cb-11ea-9136-9dceed0dd571.png)

**Comment by beijibeijing** [comment]
刚好也遇到这个问题，同问

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-layout/pull/496
默认打开l

**Comment by yunuo-tech** [comment]
> [ant-design/ant-design-pro-layout#496](https://github.com/ant-design/ant-design-pro-layout/pull/496)
> 默认打开l

此bug依旧存在于 5.0.17

**Comment by cuijiudai** [comment]
6.38.4 还是有问题。
