### ISSUE TITLE
🧐[问题]为什么路由不能按component 来加载

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design-pro#6714]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/24733229/83247466-2855b400-a1d6-11ea-8d63-b251b87c7fef.png)

这样的路由布局不是很普遍吗，按路由的component来渲染页面思路不是很清晰明了吗

**Comment by chenshuai2144** [comment]
现在就是这样实现的。但是你要自己再父路由中处理 children，我们会把 子路由交给父亲的 children。

**Comment by MarxZhou** [comment]
我尝试渲染了一下这种3级路由，在我的项目中第3级路由是隐藏的。
但是碰到了一个新的问题。对应子路由我可以渲染出来，但是左侧菜单的却无法保持原有的2级菜单的选中状态。
请问有没有什么方法能够直接对隐藏的路由设置对应菜单项的选中状态呢？
我的想法是将这些隐藏的路由都设置为2级路由，同时有一个配置项可以直接指定，哪一个其他的2级菜单进入选中状态
