### ISSUE TITLE
I do not see  page style settings to switch to dark style with  ProV5

### ISSUE THREAD

**Issue by pkdcryptos** [ant-design/ant-design-pro#6716]
Hi , 
I followed the instructions to install ProV5 as below:
$ yarn create umi my-app, select ant-design-pro, Then it asks to choose ProV4/V5, no option to install simple or complete. I chose ProV5.

What came up at localhost is: a simple install w/o pagestyle settings.
What exactly i have to do to see exactly like demo site as shown  in the attachment. Thousands of thanks for anybody who can offer a quick help. Basically i want to see some thing shown at https://preview.pro.ant.design/dashboard/analysis with dark background page style.

![Capture](https://user-images.githubusercontent.com/33589724/83292023-443d6380-a19e-11ea-8be0-5fba8d7624c1.PNG)

**Comment by chenshuai2144** [comment]
you need https://github.com/chenshuai2144/umi-plugin-antd-theme

doc in here https://pro.ant.design/docs/dynamic-theme-cn
