### ISSUE TITLE
🐛[BUG] ant design pro chart 用 UMI套开发图形详细定位问题

### ISSUE THREAD

**Issue by YongquanYao** [ant-design/ant-design-pro#6717]
### 🐛 bug 描述
我看PRO DEMO的CHARTS组件是正常的，公司产品开发刚好用了PRO的CHARTS发现鼠标移动到折线图，柱状图，饼图etc..查看详细对应天数信息时，定位有问题会整体往右偏移。无法正确定位到详细信息。 所有图形都会这样。

### 截图
鼠标hover在右侧时左边的点才触发
![IMG_1406](https://user-images.githubusercontent.com/45799780/83303370-f25f0280-a1ca-11ea-9959-d2c436d6a931.jpg)

鼠标在柱状图上没有显示详细信息，需要往右才可以定位到
![IMG_1407](https://user-images.githubusercontent.com/45799780/83303580-479b1400-a1cb-11ea-80ff-e70ed8728a09.jpg)

此时在右边才显示柱状图的3
![IMG_1593](https://user-images.githubusercontent.com/45799780/83303587-4a960480-a1cb-11ea-8093-99f657002e91.jpg)

### © 版本信息

- Ant Design Pro 版本: ^5.0.8
- umi 版本 3.1.2,
- 浏览器环境 CHORME
- 开发环境 [e.g. mac OS]

**Comment by cxOrz** [comment]
检查一下传的 x 轴坐标是不是 number 类型？应该传字符串。
