### ISSUE TITLE
🧐[问题] 有没有基于pro开源的后台项目，有后端，涉及权限管理的

### ISSUE THREAD

**Issue by xiaoliusp** [ant-design/ant-design-pro#6718]
### 🧐 问题描述
最近需要快速做一个后台，想看看有没有开源项目可以直接用的，有权限管理的需求。前后端都要有。
希望大家有开源的项目可以告知下。

**Comment by sunft1996** [comment]
你可以参考 [这个项目](https://github.com/sunft1996/ant-back/)，有多角色登录，用户管理、角色管理、图片上传、富文本等功能。后端用node写的。

![页面图片-角色管理](http://back.1cloud.xyz/uploadImg/1589959890213_role.png)

**Comment by Lind-pro** [comment]
https://github.com/jetlinks/jetlinks-ui-antd

**Comment by hankaibo** [comment]
前端：[https://github.com/hankaibo/myantdpro](https://github.com/hankaibo/myantdpro)
后台：[https://github.com/hankaibo/myantdpro](https://github.com/hankaibo/myantdpro)
