### ISSUE TITLE
登录之后如何返回之前的页面

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design-pro#672]
如果是之前查看的是#/form/basic-form页面，如果因为token过期，跳转到了login页面，登录成功之后，如何返回之前的页面#/form/basic-form.

**Comment by chenshuai2144** [comment]
粗暴一点。保存在session里面。登陆成功了重定向一下

**Comment by chenshuai2144** [comment]
401重定向可以带一个url参数。登陆成功之后判断一下有没有参数，有的话重定向如何。

**Comment by gebilaoman** [comment]
这块其实你们肯定会加，只是提前与滞后的问题了，为了以后合并你们代码，蛮希望使用官方方案的

**Comment by chenshuai2144** [comment]
谢谢你的信任。 我今晚就撸一个

**Comment by gebilaoman** [comment]
哈哈，其实我是故意来取巧的，多谢

**Comment by chenshuai2144** [comment]
look in #675
