### ISSUE TITLE
🧐[问题]升级umi3后，'dva' should be listed in the project's dependencies

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#6721]
### 🧐 问题描述

升级umi3后，'dva' should be listed in the project's dependencies。

**Comment by joesdu** [comment]
感觉你应该是需要这个https://umijs.org/zh-CN/plugins/plugin-dva#%E9%85%8D%E7%BD%AE

**Comment by koupeng** [comment]
谢谢。 是可以继续使用dva或者安装plugin-dva插件吧。fetch还是这样使用？import fetch from 'dva/fetch';   @joesdu

**Comment by joesdu** [comment]
> 谢谢。 是可以继续使用dva或者安装plugin-dva插件吧。fetch还是这样使用？import fetch from 'dva/fetch';   @joesdu 
> 

dva的用法我有个demo你可以看看
