### ISSUE TITLE
🧐[问题]ProTable type="form", 如何传默认值进去。

### ISSUE THREAD

**Issue by fjnetinfo** [ant-design/ant-design-pro#6722]
### 🧐 问题描述

ProTable type="form", 如何传默认值进去。 UpdateForm我是拷贝CreateForm的。

### 💻 示例代码

      {stepFormValues && Object.keys(stepFormValues).length ? (
        <UpdateForm onCancel={() => handleUpdateModalVisible(false)} modalVisible={updateModalVisible}>
          <ProTable<TableListItem, TableListItem>
            onSubmit={async (value) => {
              const success = await handleUpdate(value);
              if (success) {
                handleUpdateModalVisible(false);
                if (actionRef.current) {
                  actionRef.current.reload();
                }
              }
            }}
            rowKey="id"
            type="form"
            columns={columns}
            rowSelection={{}}
            defaultData={[stepFormValues]}
          />
        </UpdateForm>
      ) : null}

**Comment by 510846** [comment]
`defaultData={[stepFormValues]}`

你这上面都已经有了吧？

**Comment by fjnetinfo** [comment]
> `defaultData={[stepFormValues]}`
> 
> 你这上面都已经有了吧？

设置了这个不起作用。

**Comment by fjnetinfo** [comment]
找到答案了。感谢大神： https://github.com/ant-design/pro-table/issues/238
