### ISSUE TITLE
🧐[问题]有没有大佬能给我plugin-model的使用例子哦.我按照官网文档写的一直无法渲染.我一直没整明白.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6723]
### 🧐 问题描述

我在model中写下如下代码
```typescript
import { GetPage } from '@/services/user';
import { useCallback, useState } from 'react';

export default function useUserTableModel() {
  const [itemList, setItemList] = useState();
  const [total, setTotal] = useState<number>(0);
  const [loading, setLoading] = useState(false);
  const getUserTable = useCallback(async (param: any) => {
    setLoading(true);
    await GetPage(param)
      .then((response) => {
        let data= response.data;
        setItemList(data);
        setTotal(response.total);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);
  return { itemList, loading, total, getUserTable };
}
```

然后在组件中如下使用
```typescript
const { itemList, loading, total, getUserTable } = useModel('useUserTableModel');
 useEffect(() => {
    getUserTable({ pageIndex: 1, pageSize: 10 });
  }, [itemList]);

return(
      <Card>
        <Table loading={LoadingObject(loading)} rowKey={(record) => record?.id!} tableLayout="fixed" size="small" dataSource={itemList} pagination={pagination} columns={columns}></Table>
      </Card>
);
```

结果Table一直拿不到itemList的数据.请问应该如何搞哦.

**Comment by joesdu** [comment]
MMP,是后端数据返回格式不对.

**Comment by xyy7260** [comment]
@joesdu  请问一下，你在这个页面的时候是不已经注入了这个状态？  才能useModel('useUserTableModel') 这样引入呢

**Comment by joesdu** [comment]
> rTableModel') 这样引入呢

只要写好了model,然后用umi g tmp命令执行一下,Umi就能识别到你的model,然后引入的时候就会有智能提示了.

**Comment by xyy7260** [comment]
@joesdu  我从新创建个文件
![image](https://user-images.githubusercontent.com/23183393/84337527-57075d80-abcc-11ea-99f4-b912d72ef7d8.png) 然后在执行umi g tmp ?

**Comment by xyy7260** [comment]
@joesdu   你有没有文档介绍怎么使用的没呀， 完全是看列子没任何介绍 蛋疼， 执行umi g tmp 不知道是什么

**Comment by liujiayii** [comment]
> @joesdu 你有没有文档介绍怎么使用的没呀， 完全是看列子没任何介绍 蛋疼， 执行umi g tmp 不知道是什么

https://umijs.org/zh-CN/plugins/plugin-model

**Comment by xyy7260** [comment]
@joesdu   找到了 感觉老大

**Comment by xyy7260** [comment]
@joesdu   在请问一下， 在v5版本安装完过后，再次启动你遇到这样的问题没
![image](https://user-images.githubusercontent.com/23183393/84339480-1e1db780-abd1-11ea-906b-7ed6411295e6.png) ， 提示已经注册？ 但是在目中看到
![image](https://user-images.githubusercontent.com/23183393/84339538-3c83b300-abd1-11ea-9dcf-ba8ea1f38a99.png)
![image](https://user-images.githubusercontent.com/23183393/84339574-545b3700-abd1-11ea-91b5-c8767a658076.png)
是否需要删除  .uim？

**Comment by joesdu** [comment]
> @joesdu   在请问一下， 在v5版本安装完过后，再次启动你遇到这样的问题没
> ![image](https://user-images.githubusercontent.com/23183393/84339480-1e1db780-abd1-11ea-906b-7ed6411295e6.png) ， 提示已经注册？ 但是在目中看到
> ![image](https://user-images.githubusercontent.com/23183393/84339538-3c83b300-abd1-11ea-9dcf-ba8ea1f38a99.png)
> ![image](https://user-images.githubusercontent.com/23183393/84339574-545b3700-abd1-11ea-91b5-c8767a658076.png)
> 是否需要删除  .uim？

删掉试试，还有文件名不能重复

**Comment by xyy7260** [comment]
@joesdu  好了xiexie

**Comment by liz-zhang** [comment]
当我第二次调用useCallback，想拿到上一次useState的值 但是拿到的是初始默认值，有类似dva里 const list = yield select(state => state.module.list);这样的吗

**Comment by joesdu** [comment]
> 当我第二次调用useCallback，想拿到上一次useState的值 但是拿到的是初始默认值，有类似dva里 const list = yield select(state => state.module.list);这样的吗

你是状态没有更新吗？若是遇到useState状态没更新可以试试useReducer
