### ISSUE TITLE
🧐[问题]V5 手机端菜单不显示

### ISSUE THREAD

**Issue by fjnetinfo** [ant-design/ant-design-pro#6726]
### 🧐 问题描述

手机端完全无法使用。请问是什么配置错了吗？不需要那么漂亮的适配，只要跟以前一样能操作的就行。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51048705/83346937-aab7b280-a353-11ea-87b2-00324f282118.png)

**Comment by chenshuai2144** [comment]
fixed in 6.0.0-5
