### ISSUE TITLE
dva pre-configuration with ant pro v4

### ISSUE THREAD

**Issue by mohamedRhaiem** [ant-design/ant-design-pro#6729]
### 🧐 dva pre-configuration removed from ant pro v4

I want to know why the dva pre implementation design was removed in the last version(v4), 
It persist in the project lib(was moved from dva to umi package).

dva is not recommended any more or there's other explanations?

Thanks,

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/simple-model/

this is better dva
