### ISSUE TITLE
Make default template project title configurable

### ISSUE THREAD

**Issue by wmz7year** [ant-design/ant-design-pro#673]
### What problem does this feature solve?
Default antd template project title config is in 'src/layouts/BasicLayout.js#getPageTitle'.

Make it configurable such as menu config.

### What does the proposed API look like?
src/common/project.js
```
{
  "title": "ant design"
}
```

**Comment by chenshuai2144** [comment]
Why do not you get rid of it?

**Comment by andriijas** [comment]
different Layout files can have different default title.

In my project I have.

BasicLayout.js
UserLayout.js
PublicLayout.js

I think its good as it is.
