### ISSUE TITLE
👑 V5 Pro 能不能出一个多标签页

### ISSUE THREAD

**Issue by chenjiakuan** [ant-design/ant-design-pro#6730]
### 🥰 V5 Pro 能不能出一个多标签页

V5 Pro 能不能出一个多标签页

### 🚑 其他信息
![1590981545](https://user-images.githubusercontent.com/18523983/83373044-b8c00e80-a3f9-11ea-91d3-c754bc332b9b.jpg)

![image](https://user-images.githubusercontent.com/18523983/83372867-30416e00-a3f9-11ea-95fd-793904538332.png)

**Comment by pkaq** [comment]
这是个从v2时代就开始的老需求了

**Comment by crashsol** [comment]
既然这个需求一直都有人提，而且作为一个后端管理模板，多标签是需求很大的，感觉可以提供一个啊，官方大佬如何看？

**Comment by pkaq** [comment]
#220

**Comment by yangdachu** [comment]
后台管理系统的确需要这个，希望官方可以增加一下这个功能，谢谢🙏

**Comment by MudOnTire** [comment]
我实现了一个不知道能否满足你们的需求：https://github.com/MudOnTire/antd-pro-page-tabs

**Comment by afc163** [comment]
Duplicate of #220

**Comment by Fengly0503** [comment]
自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs 在线演示地址：http://pc.loveeveryday.cn/ant-pro-tabs/
