### ISSUE TITLE
🐛[BUG]getInitialState try catch 不好使

### ISSUE THREAD

**Issue by wulibaibao** [ant-design/ant-design-pro#6731]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/22147011/83373561-6aac0a80-a3fb-11ea-9cb2-729b6fcfd40e.png)

try catch不好使，因为request报错的时候也是正常返回
![image](https://user-images.githubusercontent.com/22147011/83373651-b2329680-a3fb-11ea-811c-59c57466df01.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by liujiayii** [comment]
你怎么是这样用的……不是在app.ts导出的request里面吗

**Comment by wulibaibao** [comment]
> 你怎么是这样用的……不是在app.ts导出的request里面吗

V5里的app.tsx里啊

**Comment by xiaohuoni** [comment]
> request报错的时候也是正常返回

我的报错，都到了 request 的 errorHandler 里了！

**Comment by wulibaibao** [comment]
> > request报错的时候也是正常返回
> 
> 我的报错，都到了 request 的 errorHandler 里了！

V5刚搭建，清除cookies，直接进/welcome路由，没有拿到用户信息的时候还在/welcome

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/cd4340a90e885f48db812061f7d970e647b8f3fa/src/app.tsx#L69

在 errorHandler 里 throw 一下错误
