### ISSUE TITLE
V5版本中从后台获取菜单的代码应该放在哪儿🧐[问题]

### ISSUE THREAD

**Issue by netcore-jroger** [ant-design/ant-design-pro#6732]
### 🧐 问题描述
V5版本中从后台获取菜单的代码应该放在哪儿?
V4的文档中是这样说的：
![image](https://user-images.githubusercontent.com/3223890/83374660-da6fc480-a3fe-11ea-8f98-964bfb36e073.png)

**Comment by netcore-jroger** [comment]
找到在哪儿写了。
![image](https://user-images.githubusercontent.com/3223890/83377564-73570d80-a408-11ea-9ca1-85b2bca6b8e9.png)

**Comment by joesdu** [comment]
> 找到在哪儿写了。
> ![image](https://user-images.githubusercontent.com/3223890/83377564-73570d80-a408-11ea-9ca1-85b2bca6b8e9.png)

非常感谢,我又学会新招数了
