### ISSUE TITLE
🧐[问题] V5的request是否支持动态修改默认参数

### ISSUE THREAD

**Issue by liujiayii** [ant-design/ant-design-pro#6733]
### 🧐 问题描述
比如umi-request的这个api，试了试好像不行
https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E6%9B%B4%E6%96%B0%E6%8B%93%E5%B1%95%E5%AE%9E%E4%BE%8B%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0

**Comment by chenshuai2144** [comment]
支持修改，但是动态是不支持的。你的需求是什么？

**Comment by liujiayii** [comment]
> 什么



> 支持修改，但是动态是不支持的。你的需求是什么？

用户登录后在header里面动态加个token字段，umi-request是可以的

**Comment by liujiayii** [comment]
`import {request} form '@/app'

request.header.xx = 'xx'
`
emmm可以这样改。
