### ISSUE TITLE
🐛[BUG]V5 app.tsx layout menuHeaderRender 渲染自带点击事件？

### ISSUE THREAD

**Issue by wulibaibao** [ant-design/ant-design-pro#6736]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/22147011/83382449-b66bad80-a415-11ea-973a-34adcb40ed76.png)

![image](https://user-images.githubusercontent.com/22147011/83382490-c8e5e700-a415-11ea-8173-8e5229794bb4.png)

如上图，渲染222的元素点击会跳路由，是只有我自带点击事件？

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wulibaibao** [comment]
onMenuHeaderClick : () => {},

layout需要配置onMenuHeaderClick 移除or增加事件

**Comment by xiaohuoni** [comment]
> onMenuHeaderClick : () => {},
> 
> layout需要配置onMenuHeaderClick 移除or增加事件

这个自带点击事件，有使用场景，你不需要自己配置一下。
