### ISSUE TITLE
🧐[问题]请问怎么配置antd的全局化配置

### ISSUE THREAD

**Issue by zoeykk** [ant-design/ant-design-pro#6742]
### 🧐 问题描述
`
  <ConfigProvider {...yourConfig}>
    <App />
  </ConfigProvider>
`

我需要配置antd全局化配置，antd文档是包裹入口App，可是pro当中没有入口文件

**Comment by dreamof2080** [comment]
同问，查询Umi的API也没发现有地方可调用设置

**Comment by dreamof2080** [comment]
在config/config.ts中设置antd: {compact: true}
