### ISSUE TITLE
🐛[BUG]ProTable搜索表单新增过滤条件组件如何实现？

### ISSUE THREAD

**Issue by 767746649zyy** [ant-design/ant-design-pro#6743]
### 🐛 ProTable搜索表单新增过滤条件组件如何实现

想在ProTable的form表单新增过滤条件组件如何实现

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
可以描述的再祥细一点吗，没有 get 到你要实现的功能是什么样子的？
