### ISSUE TITLE
🧐[问题]想通过点击tree获取的id做为入参通过去重新拉取Protable的数据

### ISSUE THREAD

**Issue by 767746649zyy** [ant-design/ant-design-pro#6744]
### 🧐 问题描述
我是通过request获取proTable的数据的，现在需求是通过点击左侧tree组件的onClick事件拿到treeId做为request的入参重新拉取数据，有没有什么好的办法呀 

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23164065/83472643-6266d480-a4ba-11ea-939b-ac7106de77e6.png)

**Comment by chenshuai2144** [comment]
protable 有个叫 parmas 的 props，每次 parmas 改成都会重新去请求数据，你可以将你的treeId 放打到 params 中，就可以做到每次点击重新加载数据了

**Comment by 767746649zyy** [comment]
多谢，解决了

**Comment by licuan** [comment]
@767746649zyy @chenshuai2144 大佬可以出个例子吗 我想通过渲染出来的搜索select选中的时候去触发搜索是不是用这个方法也可以
