### ISSUE TITLE
建议统一不同的页面的编写技术，比如使用React Hooks

### ISSUE THREAD

**Issue by hiksec2020** [ant-design/ant-design-pro#6745]
很多页面比如列表页面，通过新增区块的方式添加到项目时，发现已经是React Hooks写的；
但是还有一些页面，比如高级详情页，添加到项目时，却发现是React Component写的。
同一个项目，编写的技术、模式却不一样，这样很乱，请尽快统一为React Hooks。
除此之外麻烦催一下Antd，他们的很多组件的demo文档也存在不统一的问题，一些ts一些es6。
你们应该统一用比如ts、React Hooks写完了再发布新版本吧。

**Comment by kaoding** [comment]
看一看这个，你可以提PR
https://github.com/ant-design/pro-blocks/issues/230

**Comment by xiaohuoni** [comment]
应该都已经换成 reacy hooks 的写法了，你看到哪个还没改？可以指出来下。太多文件了，可能有遗漏的地方。

**Comment by chenshuai2144** [comment]
V5 已经修改造成
