### ISSUE TITLE
设置网页favicon.ico[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6746]
### 🧐 问题描述
favicon.ico编译后显示正常，但是 刷新后 图标不见了，我在document.ejs里面设置的
![image](https://user-images.githubusercontent.com/27960630/83480083-05c0e500-a4cd-11ea-8eed-85705e1515da.png)

**Comment by chenshuai2144** [comment]
favicon.ico 的缓存很严重，是不是被别的网页缓存了。
