### ISSUE TITLE
MobileOutlined 字符串要转换为Icon怎么做啊？之前老版本是type="" 4.x怎么做？🧐[问题]

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#6747]
### 🧐 问题描述

路由里面的icon字符串怎么转换为Node?
如老版本
```javascript
<Icon type="simle"/>
```

**Comment by afc163** [comment]
https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8
https://prolayout.ant.design/menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon

**Comment by LewinJun** [comment]
IconMap这边有写好的方法吗？  那么多Icon我不可能把哪些枚举全部写出来吧？你们路由icon字符串怎么转换为标签的？

**Comment by afc163** [comment]
按需引用的话，需要手动引入指定的图标 https://github.com/ant-design/ant-design/issues/22210

**Comment by xiaohuoni** [comment]
可以参考 `@umijs/plugin-layout` 中的实现 https://github.com/umijs/plugins/blob/e20cc8d42ff97cb041be5cab34232c25774e28db/packages/plugin-layout/src/index.ts#L34 
 
如果需要支持约定式路由的方式，layout 是动态生成的。也可以作为一种参考。
https://github.com/umijs/plugins/blob/e20cc8d42ff97cb041be5cab34232c25774e28db/packages/plugin-access-layout/src/AccessLayout.tpl#L35

如果你使用这两个插件，那你其实无需关心这个 IconMap ，直接按照之前字符串的写法就可以。

**Comment by LewinJun** [comment]
ok,谢谢各位大佬的指点
