### ISSUE TITLE
🐛[BUG] antd 4.3.0 antd/es/tabs 没有导出 TabPaneProps 导致 LoginTab.tsx 警告

### ISSUE THREAD

**Issue by shanlaomao** [ant-design/ant-design-pro#6748]
### 🐛 bug 描述

antd 4.3.0 antd/es/tabs 没有导出 TabPaneProps，但是在 LoginTab.tsx 中有导入 TabPaneProps， 导致 LoginTab.tsx 警告。

### © 版本信息

- Ant Design Pro 版本: v5
- Antd 版本: v4.3.0
- umi 版本: 3.2.3
- 开发环境: Windows 10

### 🚑 其他信息

```
import React, { useEffect } from 'react';
import { TabPaneProps } from 'antd/es/tabs';
import { Tabs } from 'antd';
import LoginContext, { LoginContextProps } from './LoginContext';';
```

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/releases/tag/4.3.1
