### ISSUE TITLE
🧐[问题]Unhandled Rejection (ReferenceError): tryApplyUpdates is not defined 这是什么问题

### ISSUE THREAD

**Issue by zhangWeiZhuang** [ant-design/ant-design-pro#6752]
![image](https://user-images.githubusercontent.com/44084004/83597927-0f188300-a59b-11ea-8aa0-40fb6ba9cefb.png)

常常保存代码自动编译后会出现这个错误提示信息，但当页面手动重新刷新过后，就消失了。页面也可以正常运行。这个现象有人遇过吗？

antd 版本：4.2.5

**Comment by chenshuai2144** [comment]
是热更新的错误，umi 正在尝试新的热更新方便，解决了就可以设置了。
