### ISSUE TITLE
V5版本中怎样下载所有的区块🧐[问题]

### ISSUE THREAD

**Issue by MI-Class** [ant-design/ant-design-pro#6753]
### 🧐 问题描述

V5版本中不能使用npm run fetch:blocks来下载所有的区块了,现在V5版本该怎样下载所有的区块?

### 🚑 其他信息
在其他issue中有看到说用yarn create umi,但是并没有找到下载所有区块的选项

**Comment by Jamenchan** [comment]
npm run fetch:bloc

**Comment by chenshuai2144** [comment]
`yarn run pro fetch-blocks --branch=v5`

需要网络比较号才能下载下来

**Comment by hswyxj** [comment]
error     Error: find dependencies conflict between block and your proj
ect:* omit.js: ^2.0.2(your project) not compatible with ^1.0.2(block)

块和项目之间的依赖项冲突，不兼容

> `yarn run pro fetch-blocks --branch=v5`
> 
> 需要网络比较号才能下载下来
> 
> yarn create umi的用法可以看这个文档
> https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96
