### ISSUE TITLE
面包屑只能点击第一个，没法点击其他项🐛[BUG]

### ISSUE THREAD

**Issue by bieao411327** [ant-design/ant-design-pro#6754]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/d9e7fa86075ff415cdb50b1196ae4bcb1aa520b4/src/layouts/BasicLayout.tsx#L150

这里做的，你可以打开它
