### ISSUE TITLE
🐛[BUG]ant-design-pro 4.0更新ant版本后就报错

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/ant-design-pro#6757]
### 🐛 bug 描述
V4安装的ant版本是4.2.0版本，但是ant的组件Switch组件有问题，查看文档，在ant4.2.4版本之后修复，于是我就升级了ant4.2.4，但是一升级之后就报错。components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef，有没有人遇见过？

**Comment by chenshuai2144** [comment]
报错信息祥细一点。报错原因是这个 https://reactjs.org/docs/forwarding-refs.html
