### ISSUE TITLE
新down的pro   点菜单 跟 没点一样

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#6759]
我新yarn 的ant design pro .
在npm install后

其它的啥不干。
跑起来后，菜单没法点。

**Comment by SureYee** [comment]
同样的情况

**Comment by gluefxu** [comment]
相同问题，而且我之前5月份的工程，删掉lock文件，重新yarn，也一样问题，感觉是pro-layout出问题了

**Comment by gluefxu** [comment]
"@ant-design/pro-layout": "^5.0.8", 改为 "@ant-design/pro-layout": "5.0.8", 定死版本就行了，搞定，具体原因就没时间深究了，干活去喽。

**Comment by xyzabc0004** [comment]
谢谢各位！
