### ISSUE TITLE
关于配置代理propx的问题

### ISSUE THREAD

**Issue by wandaoshen** [ant-design/ant-design-pro#676]
![1](https://user-images.githubusercontent.com/22441780/34871807-dfe7fb46-f7c9-11e7-9f63-bf11e9d7c527.png)
![2](https://user-images.githubusercontent.com/22441780/34871808-e01cdbd6-f7c9-11e7-95ac-ffae2e4e0dae.png)
![3](https://user-images.githubusercontent.com/22441780/34871809-e0549986-f7c9-11e7-8275-7d02f60eada8.png)
为啥一直是400，难道是我代理配置错了，还是没有生效？

**Comment by chenshuai2144** [comment]
直接在chrome中打开。然后截图看看你姐

**Comment by wdao7** [comment]
你是想让用浏览器打开什么 @chenshuai2144

**Comment by chenshuai2144** [comment]
报错400的链接

**Comment by wdao7** [comment]
不好意思，刚在外面现在才回来，打开是这样的
![2](https://user-images.githubusercontent.com/34474826/34874413-cf9669f8-f7d3-11e7-952d-4f93890aeb03.png)

**Comment by wdao7** [comment]
@chenshuai2144 
![3](https://user-images.githubusercontent.com/34474826/34874550-519a5734-f7d4-11e7-950f-aa08ae2ba8c1.png)

**Comment by chenshuai2144** [comment]
https和http不能混用。。

**Comment by wdao7** [comment]
额，我待会找个http的再测试下

**Comment by wdao7** [comment]
@chenshuai2144 找了一个，但是还是400
![3](https://user-images.githubusercontent.com/34474826/34875822-d521dbae-f7d9-11e7-9ced-8f70ca5a94ad.png)

**Comment by chenshuai2144** [comment]
最后面的‘/’也加上试试

**Comment by wdao7** [comment]
.com/  加了也没用
export default {
  'GET /api/(.*)':'http://jsonplaceholder.typicode.com/'
}

api.js

export  function text(){
  return request('/api/posts/1')
}

routes里面

const res = text();

就是这样操作的

**Comment by afc163** [comment]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/507615/34876528-e68251dc-f7dc-11e7-9946-9ec027b14401.png">

**Comment by afc163** [comment]
而且 http 到 https 貌似也没问题。

**Comment by wdao7** [comment]
@afc163  可为什么我配置的就一直有问题？

**Comment by afc163** [comment]
....我也不知道，试下你的源码？

**Comment by wdao7** [comment]
你要怎么拿到我的源码了？

**Comment by chenshuai2144** [comment]
你的服务有域名贴出来吧

**Comment by wdao7** [comment]
@chenshuai2144 我没有呀，那是我自己在网上随便找个一个借口，我是在本地开发的，刚把我代码上传了
api.js里面：
 export  function text(){
  return request('/api/posts/1')
}
   routes里面const res = text();
然后就是代理配置
其他代码就是官方的源码
这是我上传代码的地址[https://github.com/wdao7/text](url)

**Comment by wdao7** [comment]
@afc163 有时间的话可以用我源码试一试老兄

**Comment by wdao7** [comment]
@chenshuai2144 关闭这个吧，我下了最新版的ant-design-pro测试了下代理是没有问题的
