### ISSUE TITLE
最新版本点击二级菜单无反应🐛[BUG]

### ISSUE THREAD

**Issue by zhengjieyuan** [ant-design/ant-design-pro#6761]
### 🐛 bug 描述
运行官方示例项目，点击二级菜单页面无跳转，没有任何反应
### 📷 复现步骤
操作步骤：
1.从github上下载最新官方例子
2.cnpm i  安装包
3.cnpm run fetch:blocks
4.cnpm start 

打开页面后，点击二级菜单无反应

**Comment by gluefxu** [comment]
"@ant-design/pro-layout": "^5.0.8", 改为 "@ant-design/pro-layout": "5.0.8", 定死版本就行了，搞定，具体原因就没时间深究了，干活去喽。

**Comment by hot588** [comment]
我也遇到了！天天出幺蛾子啊！

**Comment by hot588** [comment]
按照楼上，解决了！

这帮人，不知道天天搞什么！

BUG，越来越多了！

**Comment by LiUhoNgDan222** [comment]
你们的umi的版本是多少呀，我试了将pro-layout改成5.0.8还是有问题
