### ISSUE TITLE
请问antd  pro的入口文件在哪里 我想在入口放一个类似Provider🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6763]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/83727229-51af8d80-a677-11ea-89ef-918cf390781f.png)

**Comment by huntdream** [comment]
layouts里面可以改

**Comment by lf7817** [comment]
同问

**Comment by chenshuai2144** [comment]
layout有个 childrenRender 配置

可以在 app.tsx 中 

```tsx
export const layout = (children) => <Provider>{children}</Provider>;
```

**Comment by HiZhaoYun** [comment]
> layout有个 childrenRender 配置
> 
> 可以在 app.tsx 中
> 
> ```tsx
> export const layout = {
>   childrenRender: (children) => <Provider>{children}</Provider>,
> };
> ```

V4里面没有app.tsx

**Comment by chenshuai2144** [comment]
V4直接修改layout就好了

**Comment by acfasj** [comment]
> V4直接修改layout就好了

provider可能是全局的,  然而layout有多个, 这种情况如何处理?

**Comment by acfasj** [comment]
找到了, 参考umi文档, https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args

**Comment by peter064226** [comment]
没有用umi，用的是cra，要怎么改呢

**Comment by kgloveyou** [comment]
> 找到了, 参考umi文档, https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args

链接失效了，这个是哪个属性呢？

**Comment by acfasj** [comment]
@kgloveyou 应该可以用这个 https://umijs.org/docs/api/runtime-config#rootcontainer
