### ISSUE TITLE
umi 安装umi-plugin-cache-route失败🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6768]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/83742606-3602b200-a68c-11ea-821d-cc3b2faafa53.png)
@xiaohuoni  
### 🚑 其他信息
umi:3.1.2,
node:v12.16.1

**Comment by chenshuai2144** [comment]
这个插件看起来依赖 umi@2 。
@xiaohuoni  看看这个

**Comment by xiaohuoni** [comment]
这个插件不要了。umi@3 用这个方案尝试 https://github.com/umijs/umi/issues/3091
