### ISSUE TITLE
Cannot visit monitor page in Firefox

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#677]
https://preview.pro.ant.design/#/dashboard/monitor

**Comment by chenshuai2144** [comment]
没有map 没法调试呀

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34874851-b0a035c2-f7d5-11e7-9658-78c63716f160.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34874900-e5711d8e-f7d5-11e7-94c9-e550b08adeba.png)

很有可能是因为i这个
