### ISSUE TITLE
🐛[BUG]V5版本 通知模块间隔不一致

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6770]
### 🐛 bug 描述
![QQ截图20200604213627](https://user-images.githubusercontent.com/3166799/83763855-c43a6080-a6ab-11ea-9477-fb0b6e06b07c.png)
![QQ截图20200604213642](https://user-images.githubusercontent.com/3166799/83763866-c7cde780-a6ab-11ea-8406-43768cdeac97.png)

**Comment by chenshuai2144** [comment]
fixed for antd
