### ISSUE TITLE
🧐[问题]V4版本移除国际化之后，但是希望antd默认中文

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/ant-design-pro#6772]
🧐 问题描述
1、执行了npm run i18n-remove
2、删除了locales文件夹

antd的国际化也没了，现在希望antd能默认成中文就ok了!

看到其他回答说包一层antd的ConfigProvider,具体应该在哪加了？

💻 示例代码
无

🚑 其他信息
无

**Comment by chenshuai2144** [comment]
4.x 版本可以在 layout 中增加。使用方式与 antd 中相同

5.x 版本 在 app.ts 中配置  
文档看这里  https://github.com/umijs/plugins/pull/246

**Comment by CodingZJ** [comment]
@chenshuai2144 layout指的是哪个？不是特别清楚，是指layouts文件夹嘛？哪个组件呢，麻烦你了。

**Comment by haitongz** [comment]
> 给新人指坑：layouts的BasicLayout.tsx. 简单的2行代码。
> 
> import zhCN from 'antd/es/locale/zh_CN';

没有看懂，这不是一行代码吗？

**Comment by chenshuai2144** [comment]
他忘记加 三个点了，我给改了一下
