### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by simida0852** [ant-design/ant-design-pro#6773]
### 🧐 问题描述

安装报错
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12591108/83841091-b4199400-a732-11ea-8233-5dcd8fd7a8af.png)

**Comment by chenshuai2144** [comment]
升级ts版本，这个是 typescript  3.8 的新语法

**Comment by simida0852** [comment]
谢谢
