### ISSUE TITLE
🐛[BUG]最新 v5 代码移除国际化后，使用git提交出错

### ISSUE THREAD

**Issue by tomgao365** [ant-design/ant-design-pro#6775]
### 🐛 bug 描述

移除国际化相关代码后，提交代码，`src/global.jsx` 会生成 `import { formatMessage } from 'umi';` 代码这个又违反了 eslint 规则无法提交

`config/config.ts`
```ts
export default defineConfig({
	layout: {
	    name: 'Ant Design Pro',
	    locale: false,
	    siderWidth: 208,
	},
	locale: false,
}
```

### © 版本信息

- Ant Design Pro 版本:  v5
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS] windows 10

**Comment by chenshuai2144** [comment]
自己手工删除一下这些调用，删除国际化并不是一个非常完美的东西

**Comment by tomgao365** [comment]
删除后，还会重新生成，提交失败
