### ISSUE TITLE
🧐[问题]use-merge-value这个依赖的作用是？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#6776]
### 🧐 问题描述
use-merge-value的作用是啥？
### 💻 示例代码
```
const [type, setType] = useMergeValue('', {
    value: props.activeKey,
    onChange: props.onTabChange,
  });
// 看到demo的登录有引用该依赖，字面意思是合并值，那第二个参数对象是？
```

### 🚑 其他信息
antd pro 4.0

**Comment by chenshuai2144** [comment]
useMergeValue 是一个用于合并 props 的 value 和自己的 value 的 hooks
具体的操作可以看这里，非常简单粗暴的hooks
https://github.com/chenshuai2144/merge-value-hooks/
