### ISSUE TITLE
Redirect to previous path when logging in

### ISSUE THREAD

**Issue by andriijas** [ant-design/ant-design-pro#678]
Current flow:

1) Log out  ✅
2) go to /profile ✅
3) get redirected to /user/login ✅
4) login ✅
5) get redirected to /  ❌ 

It should be:

5) get redirected back to /profile ✅

I tried to fix it for a PR but there are some issues with the new authorized management, redirectPath is static code in AuthorizedRoute   and model/login reloads the whole page instead of using routerRedux.push.

Maybe @ddcat1115 can fix it who did nice efforts in #508 

Thanks

**Comment by chenshuai2144** [comment]
I am doing this job,you will see it soon.

**Comment by chenshuai2144** [comment]
look in #675
