### ISSUE TITLE
👑 [需求]菜单太长了怎么设置宽度滚动条

### ISSUE THREAD

**Issue by mumuchenxiang** [ant-design/ant-design-pro#6782]

**Comment by l745230** [comment]
需要的是个超过宽度显示省略号.

**Comment by mumuchenxiang** [comment]
省略号我可以设置，就是滚动条设置不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"L745230"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 上午9:32
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"1905_陈翔"<821256083@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 👑 [需求]菜单太长了怎么设置宽度滚动条 (#6782)





 
需要的是个超过宽度显示省略号.

**Comment by chenshuai2144** [comment]
`ant-layout-sider-children`

给这个css 设置样式就好了
