### ISSUE TITLE
👑 [需求]V5替换Moment.js

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#6783]
### 🚑 其他信息

看了文档,已经有了官方实现替换Moment.js
antd-dayjs-webpack-plugin

pro能不能默认集成此方案,作为最佳实践

**Comment by chenshuai2144** [comment]
生态里面依赖的太多了，只有 antd 支持对我们这个集成了这么多组件的项目来说有点杯水车薪
