### ISSUE TITLE
网络请求地址在哪儿改啊？找了半天找不到🧐[问题]

### ISSUE THREAD

**Issue by lxy910812** [ant-design/ant-design-pro#6784]

**Comment by lxy910812** [comment]
/**
 * request 网络请求工具
 * 更详细的 api 文档: https://github.com/umijs/umi-request
 */
import { extend } from 'umi-request';
import { notification } from 'antd';

const codeMessage = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
};
/**
 * 异常处理程序
 */

const errorHandler = error => {
  const { response } = error;

  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;
    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  } else if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }

  return response;
};
/**
 * 配置request请求时的默认参数
 */

const request = extend({
  errorHandler,
  // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
});
export default request;
这是request.js文件

**Comment by liujiayii** [comment]
` import { request } form 'umi'  `

这个request和 umi-request不是完全一样的

**Comment by hankaibo** [comment]
config/proxy.js文件里面配置后台接口地址。

**Comment by lxy910812** [comment]
> config/proxy.js文件里面配置后台接口地址。

不行啊，

**Comment by hankaibo** [comment]
启动的时候，禁用mock。

**Comment by lodisy** [comment]
> `import { request } form 'umi' `
> 
> 这个request和 umi-request不是完全一样的

有没有文档啊 官网搜不到 只有插件 umi-request

**Comment by gowwwog** [comment]
export async function addRule(params: TableListItem) {
  return request(`http://localhost:9402/api/rule`, {
    method: 'POST',
    data: {
      ...params,
      method: 'post',
    },
  });
}
找了一个早上，测试行得通
