### ISSUE TITLE
Navigation between pages not working

### ISSUE THREAD

**Issue by cielblog** [ant-design/ant-design-pro#6788]
### 🧐  Description:

I created a new Umi projct, after I started the project and logged-in .. I tried to navigate to another page then I got a blank page then an error shows up.

My machine info:
Mac Pro (Mid 2012)
2 x 2.4 GHz 6-Core Intel Xeon
Node version: v12.13.1
Npm version: 6.14.4

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16566503/83998498-689cfb00-a969-11ea-9101-06cad01e278d.png)
![image](https://user-images.githubusercontent.com/16566503/83998864-33dd7380-a96a-11ea-84af-b641581d22af.png)

**Comment by chenshuai2144** [comment]
you need update you  deps.

**Comment by chenshuai2144** [comment]
dep of https://github.com/ant-design/ant-design-pro/issues/6800
