### ISSUE TITLE
🐛v4切换不同角色，需要刷新页面才可以渲染正确菜单[BUG]

### ISSUE THREAD

**Issue by mx-chen** [ant-design/ant-design-pro#6790]
### 🐛 bug 描述

用管理者账号登录后，出现的是有管理者权限的菜单，退出登录后，用普通用户登录，显示的还是管理者权限的菜单，需要刷新才可以

### 📷 复现步骤

/src/models/user.js
![dd49315348c131e1305d4c2b33100b8](https://user-images.githubusercontent.com/49704473/84004686-83d62d80-a99e-11ea-9351-357bb49800e8.png)

### 🏞 期望结果

退出后重新登录能渲染正确菜单

### © 版本信息

- Ant Design Pro 版本: antd pro v4
- umi 版本 @3.1.2
- 浏览器环境 谷歌
- 开发环境 window7

### 🚑 其他信息

SecurityLayout中打印
![3a203cc34fba55e3343cb32956e5491](https://user-images.githubusercontent.com/49704473/84004109-a451b800-a99d-11ea-8f44-4dbc5007cb19.png)

第一次登录管理者后打印出来的
![2ddc801c0ede9b7e465bdd6055c8b46](https://user-images.githubusercontent.com/49704473/84004345-fa266000-a99d-11ea-9d5e-bed58921ceb6.png)

换成普通用户后打印出来的
![Uploading 63f0719e596c06cf37ce41027e2e451.png…]()

**Comment by liujiayii** [comment]
emmm 你解决了吗？

**Comment by mx-chen** [comment]
@liujiayii   没有，刚刚重复提交了

**Comment by joesdu** [comment]
> emmm 你解决了吗？

这个是V4的bug,升到V5这个bug还在,但是听说V5.1是好的.

**Comment by joesdu** [comment]
> emmm 你解决了吗？

这个是V4的bug,升到V5这个bug还在,但是听说V5.1是好的.

**Comment by NO2046** [comment]
我也遇到这个问题了，请问楼主解决这个问题了么？

**Comment by joesdu** [comment]
> 我也遇到这个问题了，请问楼主解决这个问题了么？

可以用location.reload()在登录后刷新一下

**Comment by joesdu** [comment]
> emmm 你解决了吗？

可以用location.reload()处理一下

**Comment by NO2046** [comment]
> > 我也遇到这个问题了，请问楼主解决这个问题了么？
> 
> 可以用location.reload()在登录后刷新一下

我这边逻辑，刷新就要实时用token 拉取用户信息的，所以不能用刷新来实现，我再想想办法

**Comment by zhengjf1988** [comment]
> > > 我也遇到这个问题了，请问楼主解决这个问题了么？
> > 
> > 
> > 可以用location.reload()在登录后刷新一下
> 
> 我这边逻辑，刷新就要实时用token 拉取用户信息的，所以不能用刷新来实现，我再想想办法

退出的时候刷新一下
