### ISSUE TITLE
新建ant-design-pro项目，并本地启动，控制台报错：devScripts.js:5035 Warning: The current popular language does not exist, please check the locales folder!

### ISSUE THREAD

**Issue by tsinglemon** [ant-design/ant-design-pro#6791]
系统：window7
浏览器：谷歌浏览器83.0.4103.61

创建项目：`tyarn create umi`
- ant-design-pro
-  sample
-  typescript
启动项目：
`tyarn start`

结果：
控制台报warning错误
```js 
devScripts.js:5035 Warning: The current popular language does not exist, please check the locales folder!
```

希望得到的帮助：
解决控制台的报错信息；

**Comment by chenshuai2144** [comment]
你默认设置的语言有点问题，在 devtools 中清空一下各种数据。


![image](https://user-images.githubusercontent.com/8186664/84134135-ba817600-aa7a-11ea-904a-b62d17087a69.png)

**Comment by zsjun** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/8063904/229337032-16ef9412-768a-46ab-84a4-7fb9add8af98.png">
这样解决
