### ISSUE TITLE
🐛[BUG]Form会输出很多内容.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6792]
### 🐛 bug 描述

我觉得这个东西还是删掉好点,这种强(JIAN)了输出面板.
![image](https://user-images.githubusercontent.com/13188169/84037348-0f68b200-a9d1-11ea-932f-7ba0e387a82e.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新一下依赖，有个版本把 debug 的信息发上来了
