### ISSUE TITLE
新建的页面，有这个警告提示，怎么去掉？？🧐[问题]

### ISSUE THREAD

**Issue by lxy910812** [ant-design/ant-design-pro#6795]
[React Intl] Missing message: "menu.新页面" for locale: "zh-CN", using default message as fallback.

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/24c122b5443e8a35bfa85dc8a7d73d0d15ead504/config/defaultSettings.ts#L17
设置为 false 即可
