### ISSUE TITLE
👑 [需求] 有没有什么方式可以去掉*electron*，来提速生产环境的打包时间？

### ISSUE THREAD

**Issue by zealinux** [ant-design/ant-design-pro#6796]
###** 🥰 需求描述

现在打包部署是，npm install 时，一直会卡在

`electron@1.8.8 postinstall /root/workspace/node_modules/electron
> node install.js`

十分痛苦~

有什么办法可以部署时去掉吗？

**Comment by chenshuai2144** [comment]
我们现在没有依赖 electron 了，是你项目中的吗？

两个解决办法

1. 删除 electron 依赖
2. 使用 cnpm 安装来加快速度
