### ISSUE TITLE
🧐[问题]  linux   v5 版本 如何 通过本地加载获取全部blocks

### ISSUE THREAD

**Issue by zhengshubin** [ant-design/ant-design-pro#6797]
### 🧐 问题描述
我尝试使用 npm run fetch:blocks  ，但可能公司网络不好，会出错，在 使用  yarn create umi  选择 v5 时 也没有 complete 选项 ，现在 想尝试 用 本地导入的方法 。想问 linux 在哪配置。

**Comment by l745230** [comment]
yarn run pro fetch-blocks --branch=v5
