### ISSUE TITLE
🐛[BUG]V5 fetch-blocks后,登录失败

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-pro#6798]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15940920/84117461-22789200-aa64-11ea-9381-58b4ec1f84b2.png)

通过yarn create umi新建项目, 启动使用admin/ant.design登陆正常
yarn run pro fetch-blocks --branch=v5 拉取全部代码后,
yarn run start启动admin/ant.design登陆失败

**Comment by renyi818** [comment]
![image](https://user-images.githubusercontent.com/30144443/84338039-a13d0e80-abcd-11ea-9eed-21d6ea42048e.png)
是的，我昨天和今天分别新建拉了2次，确实登录首页样式乱了。同时登录按钮点击无效。对比了两边的登录页面代码，确实不一样。

**Comment by chenshuai2144** [comment]
fixed in blocks
