### ISSUE TITLE
🐛[BUG]手机访问(超小屏模式) https://preview.pro.ant.design/ 失败

### ISSUE THREAD

**Issue by maroon1** [ant-design/ant-design-pro#6799]
### 🐛 bug 描述
手机模式访问 https://preview.pro.ant.design/ 失败，控制台报错，页面空白

![image](https://user-images.githubusercontent.com/15511355/84125906-cd427d80-aa6f-11ea-8dbe-c35734aabf7c.png)

### 📷 复现步骤
使用手机或浏览器设置成超小屏(xs)模式下访问预览页面

### 🏞 期望结果
正常访问预览页面

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
dep of  https://github.com/ant-design/ant-design-pro/issues/6800
