### ISSUE TITLE
Cannot read property 'getParent' of undefined

### ISSUE THREAD

**Issue by webshy** [ant-design/ant-design-pro#6800]
### 🐛 bug 描述
https://preview.pro.ant.design/dashboard/analysis
页面点击 类名为 ant-pro-setting-drawer-handle 按钮 报错
Cannot read property 'getParent' of undefined

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/29698214/84128053-9fab0380-aa72-11ea-9855-1ed32d738591.png)
![image](https://user-images.githubusercontent.com/29698214/84128763-99695700-aa73-11ea-9c76-add3363d9bd3.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by webshy** [comment]
页面点击类名为 ant-pro-setting-drawer-handle 按钮 报错 Cannot read property 'getParent' of undefined

**Comment by liujiayii** [comment]
好像是moment的版本有问题，因为我本地也出现过……

**Comment by liujiayii** [comment]
在package.json里面加上这个就没事
`
"resolutions": {
    "moment": "2.24.0"
  },
`

**Comment by webshy** [comment]
> 在package.json里面加上这个就没事
> `"resolutions": { "moment": "2.24.0" },`

https://preview.pro.ant.design/dashboard/analysis 网站

**Comment by gguan** [comment]
https://preview.pro.ant.design/list/table-list

点击新建按钮报错

**Comment by chenshuai2144** [comment]
重新更新依赖就好了
