### ISSUE TITLE
为什么我把docuent.ejs 的title修改之后 ，登录界面 的ttile 还是Ant Design Pro

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#6801]
为什么我把docuent.ejs 的title修改之后 ，登录界面 的ttile 还是Ant Design Pro,,如何修改呢？

**Comment by huntdream** [comment]
document.ejs中的title会被Helmet覆盖，登录页面好像是在UserLayout里面，
它使用的`title`是用ant-design-pro-layout中的`getPageTitle`生成的，
https://github.com/ant-design/ant-design-pro/blob/6412fd6c35252ed1bc7cfdb6efe99bff37f60b77/src/layouts/UserLayout.tsx#L31

这里设置了默认值`title= 'Ant Design Pro'`，

https://github.com/ant-design/ant-design-pro-layout/blob/e6203dec808e3d372e732dd338e3bdc220c8ed4d/src/getPageTitle.ts#L54

你传个自定义的`title`进去应该就可以了
