### ISSUE TITLE
🐛[BUG] 5.1下app.tsx中的accessLayout下声明的menuDataRender未执行

### ISSUE THREAD

**Issue by PlayApple** [ant-design/ant-design-pro#6803]
### 🐛 bug 描述

clone下来的5.1版本，自定义menuDataRender后，menuDataRender没有执行。

### 📷 复现步骤

`
export const accessLayout: BasicLayoutProps = {
  // @ts-ignore
  // 自定义完整头信息
  headerTitleRender: undefined,
  // 自定义头信息的logo和右侧工具栏之间的信息
  headerContentRender: () => <HeaderMenu />,
  // 自定义 标题和菜单之间的区域。
  menuExtraRender: undefined,
  title: 'Ant Design Pro',
  siderWidth: 208,
  rightContentRender: () => <RightContent />,
  disableContentMargin: false,
  footerRender: () => <Footer />,
  menuHeaderRender: undefined,
 // menuDataRender没有被执行？？？？？？
  menuDataRender: menuDataRender,
  ...defaultSettings
}
`

### 🏞 期望结果

我的路由菜单在config中声明了，由于顶部导航的时候，我需要动态过滤下右侧路由菜单，所以我准备使用menuDataRender来过滤route数据，使用5.1发现menuDataRender没有执行。

### © 版本信息

- Ant Design Pro 版本: [5.1]

**Comment by chenshuai2144** [comment]
可以试试postMenuData
