### ISSUE TITLE
🐛[BUG]build 完的样式和开发样式有区别

### ISSUE THREAD

**Issue by gaspire** [ant-design/ant-design-pro#6805]
### 🐛 bug 描述

部署到服务器的样式和开发环境下的样式有区别, 请看下图左边是build完的，右图是开发。
导航宽度不一样
### © 版本信息

- Ant Design Pro 版本: 4.0
![991591773063_ pic_hd](https://user-images.githubusercontent.com/49259119/84239856-ba8f7d80-ab2f-11ea-9c9f-80dc449efeea.jpg)

**Comment by afc163** [comment]
这样提问和没提差不多。

**Comment by gaspire** [comment]
> 这样提问和没提差不多。

需要什么信息

**Comment by afc163** [comment]
两边网页都按一下 <kbd>cmd</kbd> + <kbd>0</kbd>

**Comment by gaspire** [comment]
> 两边网页都按一下 cmd + 0

没做放大，缩小.
