### ISSUE TITLE
v5版本在Safari浏览器上，左侧菜单栏在登录页面会显示出来 🐛[BUG]

### ISSUE THREAD

**Issue by yangdachu** [ant-design/ant-design-pro#6806]
### 🐛 bug 描述

v5版本在Safari浏览器上，左侧菜单栏在登录页面会显示出来

### 📷 复现步骤

使用Safari浏览器访问登录页面

### 🏞 期望结果

左侧菜单栏应该隐藏

### © 版本信息

- Ant Design Pro 版本: 5.0
- umi 版本
- 浏览器环境  Safari版本 13.1.1 (13609.2.9.1.3)
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23580181/84240982-65ed0200-ab31-11ea-8313-81cc88a89a67.png)

**Comment by liujiayii** [comment]
https://github.com/ant-design/ant-design-pro/blob/v5/config/config.ts#L36

**Comment by yangdachu** [comment]
> https://github.com/ant-design/ant-design-pro/blob/v5/config/config.ts#L36

![image](https://user-images.githubusercontent.com/23580181/84338701-558b6480-abcf-11ea-97a8-e58d881d19b8.png)
默认就是false

**Comment by linkai0001** [comment]
最新的 ant pro 是  v5 版本， 标明是 5.0.0-alpha.0， 也就是内测版本吧， 这种版本现在应该还不能应用于生产吧？

**Comment by yangdachu** [comment]
> 最新的 ant pro 是 v5 版本， 标明是 5.0.0-alpha.0， 也就是内测版本吧， 这种版本现在应该还不能应用于生产吧？

到时候升级一下不行吗

**Comment by linkai0001** [comment]
不晓得  v5 正式版出来后，相对于现在版本差异大不大，v4 升级 v5 肯定是没有问题的，应该会提供相关升级方案。但应该不会提供内测版本到正式版本的过渡方案。
在有一点 ant pro v5 文档还没有出来， 基于 v4 文档使用 v5, 有出入额。

**Comment by yangdachu** [comment]
> 不晓得 v5 正式版出来后，相对于现在版本差异大不大，v4 升级 v5 肯定是没有问题的，应该会提供相关升级方案。但应该不会提供内测版本到正式版本的过渡方案。
> 在有一点 ant pro v5 文档还没有出来， 基于 v4 文档使用 v5, 有出入额。
> 
> 我是觉得，现在玩玩 v5 版本还行， 如果是用于项目研发，建议还是听下官方的意见

ok 谢谢  我还是继续用v4吧

**Comment by chenshuai2144** [comment]
试了一下，不会这样，你是不是依赖问题

**Comment by jxwright** [comment]
> 
> 
> 试了一下，不会这样，你是不是依赖问题

有这样的问题，直接clone v5.1的下来 yarn yarn start

**Comment by yangdachu** [comment]
> 试了一下，不会这样，你是不是依赖问题

应该不是依赖问题  新clone下来都项目也是这样

**Comment by bxvs888** [comment]
相同的问题，还没有看到怎么解决。只有在safari下登录不是好的。

**Comment by leesama** [comment]
@chenshuai2144 帅哥， 包更新后chrome浏览器也出现这问题了

**Comment by WhiteTheIce** [comment]
采用动态路由后，左侧菜单栏在登录页面会显示出来有没有解决方案

**Comment by chenshuai2144** [comment]
手动判断pathname 吧
