### ISSUE TITLE
Cannot read property 'getParent' of undefined🐛[BUG]

### ISSUE THREAD

**Issue by ty888** [ant-design/ant-design-pro#6807]
### 🐛 bug 描述
本地没有问题，线上点击某个操作按钮的时候报这个错

看了一下之前的一个issues但是没解决我的问题

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/19710589/84255861-c5eda380-ab45-11ea-91ae-4df0886d4800.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]
- "moment": "^2.26.0",
"@ant-design/pro-table": "^2.3.4",

**Comment by afc163** [comment]
Fixed in [rc-util@5.0.4](https://github.com/react-component/util/commit/b64a03b89ac35a8f7590d4bd183e24b4042d252a), 清除 package-lock.json 和 yarn.lock 重新部署即可。
