### ISSUE TITLE
🧐[问题] Is it possible to use global wrappers in V5?

### ISSUE THREAD

**Issue by scotty595** [ant-design/ant-design-pro#6809]
### 🧐 问题描述
Previously in V4 I had used Firebase & Stripe wrappers around my app using the layouts folder, now that layout has been changed to a plugin, is there a similar way to do this in V5?

One of the key things I'm now missing is the ability to wrap the RightContent  component in a firebase wrapper (firebase is used for authentication in my app). I can get the internal pages working using:

```
        {
          path: '/welcome',
          name: 'welcome',
          icon: 'smile',
          component: './Welcome',
          wrappers: ['@/wrappers/FirebaseWrapper', '@/wrappers/AuthCheck', '@/wrappers/OrgCheck'],
        },
        {
          path: '/welcome2',
          name: 'welcome',
          icon: 'smile',
          component: './Welcome',
          wrappers: ['@/wrappers/FirebaseWrapper','@/wrappers/AuthCheck', '@/wrappers/OrgCheck'],
        },
```

But still missing a way to get the entire app wrapped. Any ideas?

**Comment by chenshuai2144** [comment]
you can try  childrenRender 
or  you  mybe can warpper a  layout in children

**Comment by mduecker** [comment]
@scotty595 Did you find a solution?

And could you give more details about your `wrappers` configuration as shown above. Where does the rendering of the components listed in the `wrappers` key happen?

Similar question was asked here:
#6946
