### ISSUE TITLE
独立使用 Pro 组件的方式使用 PageHeader 时 tabActiveKey 属性未生效

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design-pro#681]
### 2. 使用 Chrome React 插件查看 PageHeader 的 Props 如下：

```js
{
  action: {…},
  content: {…},
  extraContent: {…},
  tabActiveKey: 'records',
  tabList: [{
    key: 'basic',
    tab: {…},
  }, {
    key: 'records',
    tab: {…},
  }],
  title: '你好',
}
```

### 3. 此时 PageHeader 的 Tabs Props 如下：

```js
{
  defaultActiveKey: 'basic',
  ...
}
```

### 4. PageHeader 的 Props 截图：

![image](https://user-images.githubusercontent.com/2703455/34904785-e7deae9e-f887-11e7-8e50-4d4e51cdc2bc.png)

### 5. Tabs Props 截图：

![image](https://user-images.githubusercontent.com/2703455/34904843-d3a7f6d2-f888-11e7-8a6a-3d36971a9381.png)

###  6. 界面最终显示效果：

![image](https://user-images.githubusercontent.com/2703455/34904728-c8a45822-f886-11e7-95c5-4a55caae798c.png)

**Comment by afc163** [comment]
一个非常愚蠢的笔误。。感谢反馈，会在 1.0.2 里修复。

@ddcat1115 需要发布一个 1.0.2 并补充 1.0.1 的 changelog。

**Comment by chenshuai2144** [comment]
我也中招了。。 可以说是很滑稽了
