### ISSUE TITLE
🧐[问题]Prettier Formatter格式化问题.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6811]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/13188169/84270916-035e2b00-ab5e-11ea-80c5-2c030539401b.png)
![image](https://user-images.githubusercontent.com/13188169/84270955-107b1a00-ab5e-11ea-92ba-0d630753b851.png)
不知道从何时起,就无法格式化文档了,以前这种写法都是OK的.求教应该怎么改哦.

**Comment by chenshuai2144** [comment]
这个应该是 prettier 的版本变成 1.x 了吧。

?? 这个语法是什么语法？

**Comment by joesdu** [comment]
> 这个应该是 prettier 的版本变成 1.x 了吧。
> 
> ?? 这个语法是什么语法？

这个是TS的语法糖,就是a?a:b的意思.还有a?.length之类的一些用法.这里有篇文章说明了一些这个https://cloud.tencent.com/developer/article/1610693

**Comment by joesdu** [comment]
执行yarn add prettier @types/prettier --dev就好了.应该是项目中内置的是1.x.自己装2.x的就好了.
