### ISSUE TITLE
🐛[BUG]V5版本页面宽度小于768px时的错误

### ISSUE THREAD

**Issue by wuyansongs** [ant-design/ant-design-pro#6812]
### 🐛 bug 描述

V5或者V5.1版本，在页面宽度小于768px时:

1.BasicLayout的 logo左侧多出一个logo的img
2.菜单栏完全不见且没有展开按钮
3.右侧国际化语言选择的菜单显示错误。

### 📷 复现步骤

`git clone -b v5.1 git@github.com:ant-design/ant-design-pro.git .`
`yarn`
`yarn start`

### © 版本信息

- Ant Design Pro 版本: [v5.1]
- umi 版本
- 浏览器环境 chrome 版本 81.0.4044.122（正式版本） （64 位）
- 开发环境 [ubuntu 20.04]

### 🚑 其他信息

![2020-06-11 01-16-38屏幕截图](https://user-images.githubusercontent.com/19507788/84299143-d40de500-ab82-11ea-965a-137e478f1e86.png)

**Comment by liujiayii** [comment]
升级一下@ant-design/pro-layout
