### ISSUE TITLE
可否支持类似这样的websocket的proxy相关配置

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design-pro#6813]
### 🥰 需求描述
项目中遇到需要使用websocket的组件，但需要独立配置url，但无法使用config.ts中的proxy配置
```ts
let wsSourceUrl = 'http://127.0.0.1:8080/ws/app/';
<SockJsClient
            url={wsSourceUrl}
            topics={[
              `/salt/beacon/${current.id}/memusage`,
              `/salt/beacon/${current.id}/network_info`,
              `/salt/beacon/${current.id}/diskusage`,
              `/salt/beacon/${current.id}/cpuusage`,
            ]}
            onMessage={this.onBeaconMessageReceive}
            onConnect={this.onBeaconConnected}
            onDisconnect={this.onBeaconDisconnected}
            debug={false}
          />

### 🧐 解决方案
期望可以在config中全局配置这个url并且支持proxy全局代理

**Comment by domeafavour** [comment]
支持websocket代理啊：
```js
// config/proxy.js
export default {
  dev: {
    '/api/': {
      target: 'http://localhost:8888',
      changeOrigin: true,
      secure: false,
      pathRewrite: {
        '^/api': '/api',
      },
    },
    // websocket代理
    '/ws/': {
      target: 'ws://localhost:8889',
      ws: true,
      logLevel: 'debug',
      secure: false,
      pathRewrite: {
        '^/ws': '',
      },
    },
  },
}
```

**Comment by sayPink** [comment]
> 支持websocket代理啊：
> 
> ```js
> // config / proxy.js 
> 导出 默认值 { 
>   dev：{ 
>     '/ api /'：{ 
>       目标：'http：// localhost：8888' ，
>       changeOrigin：true ，
>       secure：false ，
>       pathRewrite：{ 
>         '^ / api'：' / api' ，
>       } ，
>     } ，
>     // websocket代理
>     '/ ws /'：{ 
>       target：'ws：// localhost：8889' ，
>       ws：true ，
>       logLevel：'debug'，
>       secure：false ，
>       pathRewrite：{ 
>         '^ / ws'：'' ，
>       } ，
>     } ，
>   } ，
> }
> ```

老哥 这样配置完成后，应该怎么使用啊，在线求方案

**Comment by domeafavour** [comment]
> > 支持websocket代理啊：
> > ```js
> > // config / proxy.js 
> > 导出 默认值 { 
> >   dev：{ 
> >     '/ api /'：{ 
> >       目标：'http：// localhost：8888' ，
> >       changeOrigin：true ，
> >       secure：false ，
> >       pathRewrite：{ 
> >         '^ / api'：' / api' ，
> >       } ，
> >     } ，
> >     // websocket代理
> >     '/ ws /'：{ 
> >       target：'ws：// localhost：8889' ，
> >       ws：true ，
> >       logLevel：'debug'，
> >       secure：false ，
> >       pathRewrite：{ 
> >         '^ / ws'：'' ，
> >       } ，
> >     } ，
> >   } ，
> > }
> > ```
> 
> 老哥 这样配置完成后，应该怎么使用啊，在线求方案

参考一下这个吧 https://blog.csdn.net/u013897323/article/details/106330388
协议、地址、端口动态获取一下，然后拼接成你的`wsSourceUrl`

**Comment by sayPink** [comment]
按照她这样写 好像链接都建立不上&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上6:33
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"S"<461377096@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 可否支持类似这样的websocket的proxy相关配置 (#6813)





   
支持websocket代理啊：
 // config / proxy.js  导出 默认值 {    dev：{      '/ api /'：{        目标：'http：// localhost：8888' ，       changeOrigin：true ，       secure：false ，       pathRewrite：{          '^ / api'：' / api' ，       } ，     } ，     // websocket代理     '/ ws /'：{        target：'ws：// localhost：8889' ，       ws：true ，       logLevel：'debug'，       secure：false ，       pathRewrite：{          '^ / ws'：'' ，       } ，     } ，   } ， }
  
老哥 这样配置完成后，应该怎么使用啊，在线求方案
  
参考一下这个吧 https://blog.csdn.net/u013897323/article/details/106330388
 协议、地址、端口动态获取一下，然后拼接成你的wsSourceUrl

**Comment by domeafavour** [comment]
@sayPink 生成的链接能贴一下吗

**Comment by sayPink** [comment]
这个是生成的链接ws://localhost:8000/ws/admin/ws/conn




然后我代理配置是这么写


老哥能加你个联系方式吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上7:37
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"S"<461377096@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 可否支持类似这样的websocket的proxy相关配置 (#6813)





 
@sayPink 生成的链接能贴一下吗

**Comment by sayPink** [comment]
感谢老哥， 已经找到问题&nbsp; 是我代理的时候&nbsp; 位置摆放错了，感谢老哥万忙之中抽空解答 谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上7:37
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"S"<461377096@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 可否支持类似这样的websocket的proxy相关配置 (#6813)





 
@sayPink 生成的链接能贴一下吗
