### ISSUE TITLE
🧐[问题] 想改basic Layout 

### ISSUE THREAD

**Issue by realcyma** [ant-design/ant-design-pro#6814]
ant design pro 的 basic layout是這樣.

![image](https://user-images.githubusercontent.com/32567610/84351877-ce4de900-abee-11ea-8416-bd60cd797306.png)

我想改成這樣.

![image](https://user-images.githubusercontent.com/32567610/84351860-c5f5ae00-abee-11ea-8a5b-bbd1d66e4ad5.png)

不知從何入手.

**Comment by chenshuai2144** [comment]
试试` npm i @ant-desgin/pro-layout@next`
