### ISSUE TITLE
🧐[问题]ant-deasign-pro打包后体积umi.js太大了有什么办法优化

### ISSUE THREAD

**Issue by fightingSunnyGirl** [ant-design/ant-design-pro#6815]
### 🧐 问题描述

ant-deasign-pro打包后体积umi.js太大了有什么办法优化？
mac 打包出来的是1.5兆 linux打包出来的2.3兆
首屏加载太慢了 20好几秒
没有改任何配置

node v12.16.2 npm 6.14.4

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24716684/84360437-a6fe1880-abfc-11ea-947d-9a3f2b63dcec.png)
![image](https://user-images.githubusercontent.com/24716684/84360459-aebdbd00-abfc-11ea-9c4c-90122e3102ae.png)

**Comment by fightingSunnyGirl** [comment]
体积太大

**Comment by sunft1996** [comment]
分析一下依赖

`npm run analyze`

然后删掉无用的依赖包，对于有些过大的包你可以先代码分离，然后用react.lazy进行懒加载

**Comment by fightingSunnyGirl** [comment]
> 分析一下依赖
> 
> `npm run analyze`
> 
> 然后删掉无用的依赖包，对于有些过大的包你可以先代码分离，然后用react.lazy进行懒加载

![image](https://user-images.githubusercontent.com/24716684/84471979-07eb2680-acb9-11ea-878d-6e8f6927e869.png)
光一个umi就这么大，我就想这个小点，而且不同设备打包出来的不一样的，这我也不知道怎么优化

**Comment by fightingSunnyGirl** [comment]
windos打出来的这个umi.js 3M!! 不同的系统打出来的不一样 为啥？？？

**Comment by chenshuai2144** [comment]
u里面有 antd 和 react 就会辣么大，你可以试试把这些 extends 掉

**Comment by Minitiai** [comment]
extends 是什么？
umi.js 不能按需加载吗，或者cdn也中阿

**Comment by xiaorong61** [comment]
dynamicImport: {},

.umirc 打开动态加载

**Comment by zhuwei** [comment]
@xiaorong61 创建一个空项目，打包后umi.js就有570KB，这正常吗？

**Comment by xiaorong61** [comment]
我估计是正常的，毕竟 umi 有一大堆的依赖。

**Comment by zhuwei** [comment]
@xiaorong61 有啥办法吗？准备做手机网页。空项目就有570K，再加个antd mobile。就1.3MB
对于手机端，太大了

**Comment by xiaorong61** [comment]
> @xiaorong61 有啥办法吗？准备做手机网页。空项目就有570K，再加个antd mobile。就1.3MB 对于手机端，太大了

试试 umi 开启dynamicImport，然后开启 nginx brotli 压缩？

**Comment by guojia99** [comment]
![image](https://github.com/user-attachments/assets/2b51740b-fd64-4cc7-a070-b80c07a4b680)
有点离谱的6M
