### ISSUE TITLE
正常npm start 后无法打开页面

### ISSUE THREAD

**Issue by fanslead** [ant-design/ant-design-pro#682]
尝试过直接git下载包，用cli直接new，清除npm的缓存，更新node.js都没用。每次install完，start服务就这个提示。求解。
![image](https://user-images.githubusercontent.com/22066473/34907147-f7a6634e-f8b4-11e7-9306-45242905ca4e.png)

**Comment by chenshuai2144** [comment]
清空一下应用数据！这个问题有好多人问了

**Comment by chenshuai2144** [comment]
#658
