### ISSUE TITLE
🐛[BUG]如何先出现登陆页面，再去加载其他的js文件包

### ISSUE THREAD

**Issue by AmberJyh** [ant-design/ant-design-pro#6821]
### 🐛 bug 描述

使用iframe渲染了登录页。项目启动时，会加载完所有的包以后，才会show出登录页。

### 🏞 期望结果

先show出登录页，用户登录的同时，加载其他包

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#dynamicimport

把这个打开就好了，只会加载主框架
