### ISSUE TITLE
🐛[BUG]菜单收缩状态首次加载，图标不居中，鼠标放上去就居中了

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6825]
### 🐛 bug 描述

菜单收缩状态首次加载，图标不居中，鼠标放上去就居中了

### 📷 复现步骤

![QQ浏览器截图20200612185705](https://user-images.githubusercontent.com/3166799/84495974-b5246580-acde-11ea-9207-332cfff3c476.png)

### © 版本信息

- Ant Design Pro 版本: 4.3.3
- pro-layout: 5.0.17
- umi 版本 3.2.3
- 浏览器环境 Chrome 80
- 开发环境  Windows 10

**Comment by chenshuai2144** [comment]
更新一下antd和layout的版本这是某次版本更新导致的bug
