### ISSUE TITLE
🧐[问题] 如何生成zip压缩包

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/ant-design-pro#6826]
以往都是在webpack.config.js 或者vue.config.js加入下面的代码，但是pro不知道放在哪里？
const FileManagerPlugin = require('filemanager-webpack-plugin');
new FileManagerPlugin({
  onEnd: {
    mkdir: ['./zip'],
    archive: [
      { source: './dist', destination: './zip/test.zip' },
    ]
  }
})

**Comment by chenshuai2144** [comment]
umijs 支持chainwebpack，或者使用bash来实现。
```
tar -zcvf /home/xahot.tar.gz /xahot
```
