### ISSUE TITLE
子路由配置 exact 全路径匹配未生效🐛[BUG]

### ISSUE THREAD

**Issue by linkai0001** [ant-design/ant-design-pro#6829]
### 🐛 bug 描述

子路由中配置 exact: true ， 实际没有达到路径完全匹配的限制效果

### 📷 复现步骤

1. 添加子路由的 exact: true配置
`
...
routes: [
                {
                  path: '/admin/subpage',
                  name: 'sub-page',
                  icon: 'smile',
                  component: './Welcome',
                  authority: ['admin'],
                  exact: true
                }
....`
2. 请求 http://xxxxxx/admin/subpage 为完全匹配的路径， 实际 http://xxxxxx/admin/subpagexxxxxx 的路径也是可以访问到  http://xxxxxx/admin/subpage  绑定的组件资源

### 🏞 期望结果

当配置了exact: true 后， 当前路由应该是全路径匹配。

### 💻 复现代码

```
{
      path: '/',
      component: '../layouts/SecurityLayout',
      routes: [
        {
          path: '/',
          component: '../layouts/BasicLayout',
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/',
              redirect: '/welcome',
            },
            {
              path: '/welcome',
              name: 'welcome',
              icon: 'smile',
              component: './Welcome',
              exact: true
            },
            {
              path: '/admin',
              name: 'admin',
              icon: 'crown',
              component: './Admin',
              authority: ['admin'],
              routes: [
                {
                  path: '/admin/subpage',
                  name: 'sub-page',
                  icon: 'smile',
                  component: './Welcome',
                  authority: ['admin'],
                  exact: true
                }
              ],
            },
            {
              name: 'list.table-list',
              icon: 'table',
              path: '/list',
              component: './ListTableList',
            },
            {
              component: './404',
            },
          ],
        },
        {
          component: './404',
        },
      ],
    },
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  4.0.0
- umi 版本                                      3.1.4
- 浏览器环境                                  谷歌
- 开发环境 [e.g. mac OS]               windows

**Comment by chenshuai2144** [comment]
exact默认为false，如果为true时，需要和路由相同时才能匹配，但是如果有斜杠也是可以匹配上的。 如果在父路由中加了exact，是不能匹配子路由的,建议在子路由中加exact

exact 是个父路由用的
