### ISSUE TITLE
🐛[BUG]V5手机端布局显示问题

### ISSUE THREAD

**Issue by jxwright** [ant-design/ant-design-pro#6831]
### 🐛 bug 描述
v5手机端或者宽度为735电脑网页端显示问题。无法正常显示语言选项

### 📷 复现步骤
yarn create umi 0.24.x 

-选择PRO V5

- yarn 

- yarn start

### 🏞 期望结果
显示正常

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境firefox 77.0.1 最新安卓手机端
- 开发环境 [window 10]

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/41815729/84582083-dccc1880-ae19-11ea-92a0-0c4619684022.png)

![图片](https://user-images.githubusercontent.com/41815729/84582077-cc1ba280-ae19-11ea-99f8-a099699d4fc0.png)

- ![图片](https://user-images.githubusercontent.com/41815729/84582059-95de2300-ae19-11ea-9d43-e9cd47d8b358.png)

**Comment by chenshuai2144** [comment]
更新最新版本即可修复，非常感谢你的 issue
