### ISSUE TITLE
🧐[问题] v5 主题插件 bug？

### ISSUE THREAD

**Issue by dumplingJ** [ant-design/ant-design-pro#6832]
1、v5 安装 umi-plugin-antd-theme 插件后编译极其慢啊，而且每次保存代码修改都要重新漫长的编译，是不是要做什么配置啊？
![image](https://user-images.githubusercontent.com/37341798/84592794-c7d3a180-ae7a-11ea-96d0-ad916c144ab8.png)

2、settingDrawer 的 onSettingChange 回调并没有触发啊，为啥？
![image](https://user-images.githubusercontent.com/37341798/84592901-75df4b80-ae7b-11ea-865a-527ff5286520.png)

3、安装 umi-plugin-setting-drawer 插件后，登录页也出现了按钮，这，不合适吧

**Comment by chenshuai2144** [comment]
这个是设计，设置抽屉是为了给设计师使用的。

> 编译慢

是因为要编译好多份 less，所以速度很慢。这个插件建议在部署的时候再使用

**Comment by Gzbox** [comment]
> 这个是设计，设置抽屉是为了给设计师使用的。自然需要每个页面都存在
> 
> > 编译慢
> 
> 是因为要编译好多份 less，所以速度很慢。这个插件建议在部署的时候再使用

能在某个地方 设置  在指定环境下（dev）不开启编译吗？
这样就不用去手动注释package.json 里面的 umi-plugin-antd-theme 依赖啦

**Comment by Gzbox** [comment]
> 这个是设计，设置抽屉是为了给设计师使用的。自然需要每个页面都存在
> 
> > 编译慢
> 
> 是因为要编译好多份 less，所以速度很慢。这个插件建议在部署的时候再使用

@chenshuai2144 能在某个地方 设置 在指定环境下（dev）不开启编译吗？
这样就不用去手动注释package.json 里面的 umi-plugin-antd-theme 依赖啦

**Comment by erlei22** [comment]
![image](https://user-images.githubusercontent.com/30687008/103269741-6677b800-49f1-11eb-8940-914e822905f4.png)
这样平时编译的时候就不会带上 theme了
