### ISSUE TITLE
🐛[BUG] v5 登录页高度大于100% 导致页面出现滚动条

### ISSUE THREAD

**Issue by AntPrince** [ant-design/ant-design-pro#6834]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/56467036/84595288-9f06d880-ae89-11ea-94c7-d971ded39b12.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by dumplingJ** [comment]
/src/pages/user/login/style.less 的 .container class 的 height 去掉

/src/pages/user/login/index.tsx 最顶层 div 加上 style：
```
return (
    <div
      style={{ height: document.documentElement.clientHeight - 88 }}
      className={styles.container}
    >
```

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/ant-design-pro/commit/9c4a1a473294e4bd10e10eb1602d79ba2f12bcd9
