### ISSUE TITLE
👑 [需求]如何在basicLayout里面获取到路由的name

### ISSUE THREAD

**Issue by juewangxiansheng** [ant-design/ant-design-pro#6835]
### 🥰 需求描述

现在有个需求需要获取到路由的name，根据翻译拿到中文名字，但是不知道怎么获取。在OnPageChange函数里获取路由信息也没有带name

**Comment by dumplingJ** [comment]
```
import { history, formatMessage} from 'umi';

formatMessage({ id: `menu${history.location.pathname.replace(/\//g, '.')}` });
```

**Comment by chenshuai2144** [comment]
https://github.com/umijs/route-utils
试试这个库，或者用 https://prolayout.ant.design/#routecontext

**Comment by juewangxiansheng** [comment]
好的谢谢



---原始邮件---
发件人: "陈帅"<notifications@github.com&gt;
发送时间: 2020年6月24日(周三) 中午11:40
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"绝望先生"<493341396@qq.com&gt;;
主题: Re: [ant-design/ant-design-pro]  [需求]如何在basicLayout里面获取到路由的name (#6835)




 
https://github.com/umijs/route-utils
 试试这个库，或者用 https://prolayout.ant.design/#routecontext
