### ISSUE TITLE
🧐路由菜单怎么使用 iconfont 自定义的图标喃

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#6837]
### 🧐 问题描述
[文档](https://pro.ant.design/docs/router-and-nav-cn)这里跳转的使用让人很困惑

**Comment by lovesL** [comment]
![image](https://user-images.githubusercontent.com/27960630/85366584-3dfe9500-b55a-11ea-8777-bcc4b1a67579.png)
  这样可以这样设置

**Comment by chenshuai2144** [comment]
https://prolayout.ant.design/example#iconfont

看看这个 demo

**Comment by lovesL** [comment]
@chenshuai2144 那个demo版本是多少  我看了我的 ProLayout 没有iconfontUrl  在config/defaultSettings.js 里面有iconfontUrl 我在 config/defaultSettings.js里面设置了 iconfontUrl似乎也不管用

**Comment by HQ1363** [comment]
我用的最新版，也不管用
