### ISSUE TITLE
为什么我build之后title会出现ASCII编码?🧐[问题]

### ISSUE THREAD

**Issue by blockmood** [ant-design/ant-design-pro#6838]
### 🚑 其他信息

![1592188204793](https://user-images.githubusercontent.com/22879524/84612427-38b6a000-aef3-11ea-85d9-42306cd828cf.jpg)

**Comment by chenshuai2144** [comment]
这个无所谓的，为了兼容性才这么搞得，浏览器渲染的时候会自动转化
