### ISSUE TITLE
ant design pro 侧边栏菜单  本地显示正常 ； 打包发到测试环境 点击任意一个菜单，所有的菜单都折叠起来了🧐[问题]

### ISSUE THREAD

**Issue by wjzgw** [ant-design/ant-design-pro#6839]
### 🧐 问题描述
ant design pro v4版本  侧边栏菜单，在本地显示正常，打包发布后，点击任意菜单，所有的菜单都折叠了

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23611992/84635211-7b916b80-af25-11ea-9189-12c1e0a42d0f.png)
![image](https://user-images.githubusercontent.com/23611992/84635241-864c0080-af25-11ea-9226-2a8b90c64314.png)

**Comment by xuezhenxiang** [comment]
找到解决方案了吗？我也遇到同样的问题。

**Comment by xuezhenxiang** [comment]
应该是@ant-design/pro-layout的问题，我升级了一下好了

**Comment by LiUhoNgDan222** [comment]
> 应该是@ant-design/pro-layout的问题，我升级了一下好了

可以发一下你的pro-layout版本和umi的版本吗？我现在也遇到了这个问题
