### ISSUE TITLE
can not running, always open like this

### ISSUE THREAD

**Issue by ufoqhmdt** [ant-design/ant-design-pro#684]
![image](https://user-images.githubusercontent.com/1751382/34915316-39eb4e90-f95f-11e7-9df5-a51a200a6259.png)

npm start

Can't open home page , just open file list , what wrong ?

**Comment by ynnyh** [comment]
npm install???

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/.webpackrc#L16-L18

**Comment by ufoqhmdt** [comment]
@ynnyh npm install 都装成功了。 是不是我clone的版本不是稳定版本。

**Comment by ynnyh** [comment]
实在不行的话，考虑重新clone试试

**Comment by chenshuai2144** [comment]
我也发现了一次问题  是因为roadhog2 用的1的配置文件
