### ISSUE TITLE
🧐[v5 登录权限配置求助]

### ISSUE THREAD

**Issue by kuicodefly** [ant-design/ant-design-pro#6843]
### 🧐 问题描述

对比v5和v4之后发现 很多文件都没了. 不知道怎么去登录的时候设置权限了.求帮助. 翻了项目原有的设置权限方式只有几行代码.复制到别的地方时并不好用

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/49471670/84722687-7fb99980-afb6-11ea-8755-fb9bf1511b34.png)
![image](https://user-images.githubusercontent.com/49471670/84722715-92cc6980-afb6-11ea-932b-ec384772175b.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/plugins/plugin-access

看这里
