### ISSUE TITLE
🧐[问题]浏览器中的标题刷新之后才更新为正确的标题

### ISSUE THREAD

**Issue by stack-wuh** [ant-design/ant-design-pro#6844]
### 🧐 问题描述
首次进入页面，浏览器标题展示为域名+路由, 刷新之后变为设置的路由name+defaultSetting.title

![image](https://user-images.githubusercontent.com/34117238/84726293-2144e900-afbf-11ea-860d-91dbfe1747d7.png)
![image](https://user-images.githubusercontent.com/34117238/84726419-5fdaa380-afbf-11ea-88ea-8ed041dad33a.png)

已经在document.ejs文件中的设置了固定的title

**Comment by AproC0der** [comment]
I have the same trouble now,have you gotten any solution?

**Comment by stack-wuh** [comment]
not yet , but could to use navigator compents or react hooks to sync update title

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis

this page is work faster，you have a repo？
