### ISSUE TITLE
DOMException: Only secure origins are allowed🧐[问题]

### ISSUE THREAD

**Issue by yinbiao** [ant-design/ant-design-pro#6845]
### 🧐 问题描述

我按照文档安装后，执行了npm start，用http://172.18.2.124:8000访问，出现这个错误：
DOMException: Only secure origins are allowed

这个一定要启用https或使用localhost域名才能开发吗？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/11266046/84727067-dc21b680-afc0-11ea-998f-c444ba781d1b.png)

**Comment by chenshuai2144** [comment]
在做录音和视频的时候访问链接必须是https，否者调用无反应！

这种问题百度一下就能解决

**Comment by waylon-edmodo** [comment]
我也出现了。chrome上没有问题。出问题的是360浏览器。

**Comment by jjwong1991** [comment]
> 在做录音和视频的时候访问链接必须是https，否者调用无反应！
> 
> 这种问题百度一下就能解决

@chenshuai2144 在Chrome61下非https环境测试发现同样问题，报错源头是global.tsx中对CacheStorage的操作报出的，提示只有安全来源可以操作，与录音视频无关。在Chrome69以上版本未发现问题。

**Comment by afc163** [comment]
closed by #7280
