### ISSUE TITLE
🐛[BUG] portable搜索表单校验失败后也向后台发起请求

### ISSUE THREAD

**Issue by winnie-weinan** [ant-design/ant-design-pro#6849]
🐛 bug 描述
portable的搜索表单有十几个输入框，并做了正则校验，在正则校验失败的情况下，点击查询依旧向后台发起请求

📷 复现步骤
1.portable的搜索表单有十几个input搜索框
2.每个搜索框都有自己的正则校验
3.在校验失败的情况下点击查询
4.无论正则校验是否通过，均向后台发起请求

🏞 期望结果
搜索表单在校验失败的情况下不向后台发起请求
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
protable 的 查询表单不允许校验的
