### ISSUE TITLE
🐛[BUG]  antd-pro-authority close

### ISSUE THREAD

**Issue by suguer** [ant-design/ant-design-pro#6850]
### 🐛 bug 描述
antd-pro-authority  权限管理的权限我改成用接口方式数组返回，在我的电脑浏览器使用无异常，但是有些用户的浏览器会将该antd-pro-authority = close ，然后会导致他的界面打开一片空白

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
实测额一把。不会的，会认为没有权限
