### ISSUE TITLE
🧐[问题] umi-plugin-pro-block的配置moveMock autoAddMenu最新版中在哪里修改？

### ISSUE THREAD

**Issue by mtianyan** [ant-design/ant-design-pro#6853]
### 🧐 问题描述

旧版本的v4 可以通过config.ts 中 umi-plugin-pro-block 改变moveMock等flag信息，新版本中没有找到修改覆盖配置的地方。

### 💻 示例代码
.umirc.ts 或 config/config.ts 中配置项目和插件，尝试没有成功

      moveMock: false,
      moveService: false,
      modifyRequest: true,
      autoAddMenu: true,

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15145231/84795019-8e8d6400-b029-11ea-9dd2-80f24272766b.png)

**Comment by chenshuai2144** [comment]
已经删掉了，不支持了
