### ISSUE TITLE
🐛[BUG]在项目中多处表单提交增加lodash的debounce防抖函数后，项目build体积暴增

### ISSUE THREAD

**Issue by yjhtry** [ant-design/ant-design-pro#6854]
### 🐛 bug 描述
今天产品要求项目中的所有表单防止用户重复提交，于是我为每一个表单的onFinish监听函数加了一个防抖处理。然后在打包的时候发现加这个函数的模块，包体积增加了几十k，项目整体体积增加0.5M(压缩后)实际项目改动代码两百行左右

### 防抖函数
import { debounce } from 'lodash';
`const clickDebounce = (cb, wait = 1000) => {
  return debounce(cb, wait);
};`

### 使用防抖函数
`<Form
        {...layout}
        name="allot"
        form={form}
        scrollToFirstError
        onFinish={clickDebounce(handleFinish)}
      >`

### 项目体积前后如图

![体积](https://user-images.githubusercontent.com/39440537/84889907-3bb8b880-b0cc-11ea-9ff2-c7d5354b515d.png)
![详细](https://user-images.githubusercontent.com/39440537/84889914-3e1b1280-b0cc-11ea-91eb-9b4d3d9a5295.png)

### © 版本信息

- @ant-design/pro-table: "2.2.1"
- Ant Design Pro 版本: ^4.0.0
- umi 版本 3.1.1
- 浏览器环境 chrome 81.0.4044.138（正式版本)
- 开发环境 ubuntu 20.04LTS

**Comment by afc163** [comment]
lodash 很大，请使用 `lodash-es`，或者 `import debounce from 'lodash/debounce';`.

**Comment by yjhtry** [comment]
@afc163 恩恩，是的换了之后项目体积就正常了。谢谢啦😀
