### ISSUE TITLE
🐛[BUG] V5.1 出现异常滚动条

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#6855]
### 🐛 bug 描述

![微信截图_20200617194437](https://user-images.githubusercontent.com/3166799/84894776-ee404980-b0d3-11ea-87ce-35c9faff239b.png)
![微信截图_20200617194450](https://user-images.githubusercontent.com/3166799/84894777-ef717680-b0d3-11ea-9279-a1094f5a8621.png)

内容未超出屏幕，出现滚动条，表格页出现双滚动条

### 🏞 期望结果

内容不超出屏幕无滚动条

### 💻 复现代码

v5.1 最新分支

### © 版本信息

- Ant Design Pro 版本:  4.3.4
- pro-layout:  6.0.0-8
- umi 版本 3.2.3
- 浏览器环境 chrome 80
- 开发环境  windows 10

**Comment by chenshuai2144** [comment]
fixed for @ant-design/pro-layout 6.2
