### ISSUE TITLE
🧐[问题] V4 路由菜单栏有A,B,C三个子菜单,但是C菜单设置了hideInMenu,在B菜单的列表点击跳转到C,路由当前的key就是C,但是因为隐藏了导致不高亮,如何停留在B的高亮效果,你们怎么解决的

### ISSUE THREAD

**Issue by CodingZJ** [ant-design/ant-design-pro#6856]

**Comment by chenshuai2144** [comment]
你可以把 c 放到 b 的 routers 中，layout 就会去找 b 来高亮

**Comment by yuqiao11278** [comment]
> 你可以把 c 放到 b 的 routers 中，layout 就会去找 b 来高亮

如果把C放到B的routes中，跳转到C的时候还是展示的B的页面，这是怎么回事
`
{
                path: '/orderManagement/order',
                name: 'order',
                component: './orderManagement/order',
                routes: [
                  {
                    path: '/orderManagement/order/:id',
                    name: 'orderDetail',
                    hideInMenu: true,
                    component: './orderManagement/order/detail',
                  },
                ]
              },
`

**Comment by yuqiao11278** [comment]
> 你可以把 c 放到 b 的 routers 中，layout 就会去找 b 来高亮

如果把C放到B的routes中，跳转到C的时候还是展示的B的页面，这是怎么回事
`
{
                path: '/orderManagement/order',
                name: 'order',
                component: './orderManagement/order',
                routes: [
                  {
                    path: '/orderManagement/order/:id',
                    name: 'orderDetail',
                    hideInMenu: true,
                    component: './orderManagement/order/detail',
                  },
                ]
              },
`

**Comment by yuqiao11278** [comment]
> 你可以把 c 放到 b 的 routers 中，layout 就会去找 b 来高亮

如果把C放到B的routes中，跳转到C的时候还是展示的B的页面，这是怎么回事
![Uploading image.png…]()

**Comment by yuqiao11278** [comment]
> 你可以把 c 放到 b 的 routers 中，layout 就会去找 b 来高亮

如果把C放到B的routes中，跳转到C的时候还是展示的B的页面，这是怎么回事
`{
                path: '/orderManagement/order',
                name: 'order',
                component: './orderManagement/order',
                routes: [
                  {
                    path: '/orderManagement/order/:id',
                    name: 'orderDetail',
                    hideInMenu: true,
                    component: './orderManagement/order/detail',
                  },
                ]
              },`
