### ISSUE TITLE
动态增加语言🐛[BUG]

### ISSUE THREAD

**Issue by linkai0001** [ant-design/ant-design-pro#6857]
### 🐛 bug 描述

基于后台国际化资源数据，通过使用 addLocale 动态加入数据，使用 FormattedMessage 组件无法获取国际化资源内容， 栏目的名称也是由后台国际化数据基于 addLocale 注入，也出现同样的问题。

### 📷 复现步骤

1. 动态增加国际化资源数据

```
import enUS from 'antd/es/locale/en_US';
addLocale("en-US", {
    "sys.user.age.field.key": "测试0001"
  },{
    momentLocale: "en-US",
    antd: enUS
  });
<FormattedMessage id="sys.user.age.field.key"/>
```

### 🏞 期望结果

通过 addLocale 添加国际化资源后， 基于 FormattedMessage 可获取指定国际化资源

### 💻 复现代码
```

import enUS from 'antd/es/locale/en_US';

addLocale("en-US", {
    "sys.user.age.field.key": "测试0001"
  },{
    momentLocale: "en-US",
    antd: enUS
  });

<FormattedMessage id="sys.user.age.field.key"/>
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] antd pro 4.0.0
- umi 版本     umi 3.1.4
- 浏览器环境   谷歌
- 开发环境 [e.g. mac OS]  window

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24260681/84915334-3caf1180-b0ef-11ea-9912-c876ac6b28a7.png)
![image](https://user-images.githubusercontent.com/24260681/84915470-6b2cec80-b0ef-11ea-9b7c-156146bfc5b5.png)

**Comment by taomengyue** [comment]
请问这个问题找到解决方案了吗？

**Comment by linkai0001** [comment]
> 请问这个问题找到解决方案了吗？

**我贴下代码吧， 我目前是这么解决的**
/**
 * 获取指定 key 国际化内容, 简化函数名
 * @param key
 * @param locale
 */
const gl =  (key: string, locale: string = getLocale()) : any => {

  return getIntl(locale).messages[key] || key;
}

**针对动态变量的注入定义**
/**
 * 获取指定 key 国际化内容，支持动态参数注入， 既支持 locales 下的国际化配置，也支持后台动态配置注入
 * @param key
 * @param item
 * @param locale
 */
const fm = (key: string, item?: {[key: string]: any}, locale: string = getLocale()) : any => {

  let result = gl(key);
  if (objectUtils.isNotEmpty(item)) {
    for (let attrName in item) {

      let parser: RegExp = new RegExp(eval(`/{[\s]*${attrName}[\s]*}/g`));
      result = result && result.replace(parser, item[attrName]);
    }
  }
  return result;
}

**Comment by taomengyue** [comment]
谢谢楼主。我不太清楚fm方法什么时候用。是不是动态参数的话，页面就不用useIntl，用 fm() 这个方法吗？

**Comment by linkai0001** [comment]
> useIntl
就比如你配置了一个 key 为 app.table.selected.times， 然后他的内容是 Selected {selectedTimes} items  ，对于  {selectedTimes} 而言，就是一个动态的参数呢，需要结合自己的上下文做数据的注入。

**Comment by linkai0001** [comment]
> 谢谢楼主。我不太清楚fm方法什么时候用。是不是动态参数的话，页面就不用useIntl，用 fm() 这个方法吗？

如果变量绑定的内容是 jsx ，可以在封装下， 目前 gl 和 fm 我已经够用了额

**Comment by taomengyue** [comment]
谢谢楼主，我明白您说的了。我想问一个额外的问题，如果语言包从后端获取的，怎么用？

**Comment by linkai0001** [comment]
> 谢谢楼主，我明白您说的了。我想问一个额外的问题，如果语言包从后端获取的，怎么用？

![image](https://user-images.githubusercontent.com/24260681/90464550-2699ed80-e140-11ea-81ec-f427610d6120.png)
locale 插件 api :
https://umijs.org/plugins/plugin-locale#addlocale
有个  addLocale 函数就是了呢。

**Comment by amin168** [comment]
@linkai0001 , @taomengyue ，我是在 `app.ts`  里面的 `getInitialState()` 动态添加多语言，下面是的我解决方案

```
// 以下的代码都在 `app.ts` 里面

export async function getInitialState() {
	// 1. 从后台获取多语言
	// 2. 调用 addLocale() 添加多语言
	// 3. 调用 setLocale() 设置当前多语言
	
	// 如果用 umi 自带的 useIntl 会出现如下错误
	// const msg = useIntl().formatMessage({
	//   id: 'Ui:InternalServerErrorMessage',
	//   defaultMessage: '你好，旅行者',
	// });
	// [React Intl] Missing message: "AbpUi:InternalServerErrorMessage" for locale: "en-US", using default message as fallback.
	  
	// 所以需要在下面自定义一个 setLocale
}

// 官方的参考文档 https://umijs.org/zh-CN/plugins/plugin-locale#setlocale-1
// 设置一个自定义语言切换逻辑
// 4. 强制更新当前组件国际化状态
export const locale = {
  setLocale({ updater }: { updater: Function }) {
	updater() // 最主要是这句话
  },
}
```

**Comment by jeffxu** [comment]
通过查看umi代码，发现这个bug的问题是因为`addLocale `之后调用`setLocale`时一定要保证之前的语言和目标语言要不同，比如之前是en-US，则目标语言不能是en-US，否则就不会触发umi自定义事件`LANG_CHANGE_EVENT`

以下是umi`setLocale`的代码
```
export const setLocale = (lang: string, realReload: boolean = true) => {
  const localeExp = new RegExp(`^([a-z]{2})-?([A-Z]{2})?$`);

  const runtimeLocale = plugin.applyPlugins({
    key: 'locale',
    type: ApplyPluginsType.modify,
    initialValue: {},
  });

  const updater = () => {
    if (lang !== undefined && !localeExp.test(lang)) {
      // for reset when lang === undefined
      throw new Error('setLocale lang format error');
    }

    // !!!!!!! 就是这里来判断语言是否切换过，如果没切换则不会触发下面的event.emit(LANG_CHANGE_EVENT, lang);
    if (getLocale() !== lang) {
      if (typeof window.localStorage !== 'undefined' && useLocalStorage) {
        window.localStorage.setItem('umi_locale', lang || '');
      }
      setIntl(lang);
      if (realReload) {
        window.location.reload();
      } else {
        event.emit(LANG_CHANGE_EVENT, lang);
        // chrome 不支持这个事件。所以人肉触发一下
        if (window.dispatchEvent) {
          const event = new Event('languagechange');
          window.dispatchEvent(event);
        }
      }
    }
  }
```

**Comment by chenshuai2144** [comment]
@jeffxu  有兴趣帮我们来个pr 吗？

**Comment by jeffxu** [comment]
@chenshuai2144 已发了一个pr

**Comment by chenshuai2144** [comment]
地址贴一下，我看看代码

**Comment by jeffxu** [comment]
@chenshuai2144 这个是pr地址：https://github.com/umijs/plugins/pull/573/commits/ef8aefc802468f9cb705f04a193e19f3cd38154d

**Comment by chenshuai2144** [comment]
已经合并了呀，那我关掉了

**Comment by jeffxu** [comment]
@chenshuai2144 是在哪个分支里面？我这边看显示的是`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

**Comment by chenshuai2144** [comment]
你没有pr 吗？有的话给个pr的地址
