### ISSUE TITLE
How to make Storybook work with ant design pro?

### ISSUE THREAD

**Issue by Nooka10** [ant-design/ant-design-pro#6858]
Hi,

I'm trying to install [storybook](https://storybook.js.org/docs/guides/guide-react/) to use it with ant design pro, but can't make it work...

I installed ant design pro v4, with typescript and all the blocks, then I add storybook running this cmd:
`npx -p @storybook/cli sb init`

I created this story:
```
import React from 'react';
import Analysis from '@/pages/dashboard/analysis';

export default {
  title: 'Button',
  component: Analysis,
};

export const Text = () => <Analysis/>;
```

Running Storybook here gave me an error because the @ in the import are not recognized...
Apparently, the tsconfig.json file is not used by the default configuration of web pack in storybook....

So, after many tries, I modified the default main.js file in the .storybook folder like that:
```
const getWebpackConfig = require('@ant-design/tools/lib/getWebpackConfig');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const getConfig = require('af-webpack/getConfig').default;
// umi webpack config
const umiConfig = getConfig({cwd: process.cwd()});
const umiRules = umiConfig.module.rules.filter(
  rule => rule.test && rule.test.source.includes('.less')
);
const umiPlugins = umiConfig.plugins.filter(
  plugin => plugin.constructor && plugin.constructor.name === 'MiniCssExtractPlugin'
);
module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],

  webpackFinal: async config => {
    config.module = config.module || {rules: []};
    config.plugins = config.plugins || [];
    config.resolve.plugins = [
      new TsconfigPathsPlugin({
        configFile: path.resolve(__dirname, '../tsconfig.json')
      })
    ];
    const webpackConfig = getWebpackConfig(false);

    if (webpackConfig.module == null) {
      throw new Error('our webpack config should have module rules');
    }
    if (webpackConfig.plugins == null) {
      throw new Error('our webpack config should have plugins');
    }

    return {
      ...config,
      resolve: {
        ...config.resolve,
        ...webpackConfig.resolve
      },
      module: {
        ...config.module,
        ...webpackConfig.module
      },
      plugins: [...config.plugins, new MiniCssExtractPlugin()]
    };
  }
};
```

Now, I'm stuck with this error:
`Could not find "store" in either the context or props of "Connect(Analysis)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Analysis)".`

Is there a way to make it work?
Thanks for the help!

**Comment by chenshuai2144** [comment]
i think you use dumi is great
https://d.umijs.org/

**Comment by Nooka10** [comment]
> i think you use dumi is great
> https://d.umijs.org/

Oh! That looks great! Thank you! I'll try it.
It would be awesome if it was directly configured and included in ant design pro scaffolding... And if the doc was traduced in english too... ^^
