### ISSUE TITLE
🐛[BUG]v5版本，语言选择下拉没法定制选项，比如我只需要英文和中文

### ISSUE THREAD

**Issue by rudyzou** [ant-design/ant-design-pro#6859]
### 🐛 bug 描述
语言选择下拉内容没法定制选项，比如我只需要英文和中文，没办法根据需要定制语种下拉，看了语言切换组件SelectLang代码，目前下拉菜单是写死的
![image](https://user-images.githubusercontent.com/4281891/84930641-2f505200-b104-11ea-88c2-8f1e50e0379f.png)

**Comment by chenshuai2144** [comment]
SelectLang 支持 postLocalesData 的。或者把 locale 的文件夹删掉

**Comment by rudyzou** [comment]
> SelectLang 支持 postLocalesData 的。或者把 locale 的文件夹删掉
原本我期望也想是这样结果，但是这两种操作都没效果。
下面是我代码，帮忙看看是否有问题：
locales
![image](https://user-images.githubusercontent.com/4281891/85089344-023f9480-b215-11ea-97f0-3f1f89ee6e7b.png)

SelectLang
![image](https://user-images.githubusercontent.com/4281891/85089378-1c797280-b215-11ea-9699-afbb20b0260b.png)

**Comment by zhangshuling** [comment]
![Uploading 122213.png…]()

粗暴一点，直接注释掉吧 ...

**Comment by YuYanzy** [comment]
同样遇到这个问题
这个langMenu是写死的……
就算改了postLocalData也改变不了langMenu里面的Item，我真的是醉了
