### ISSUE TITLE
权限管理问题

### ISSUE THREAD

**Issue by zhangweihua66** [ant-design/ant-design-pro#686]
pro 的权限管理 , 是通过角色来进行控制, 但是有新的角色权限时, 得在代码中添加新的角色 , 修改代码才可以, 感觉这样做,  是不是有些死板了,  是不是不如通过返回的角色的资源来的精细 和灵活 , 所以 ,有没有什么解决方案是新的角色权限产生的时候, 不用通过修改代码的解决方案呢?

**Comment by chenshuai2144** [comment]
参数是支持function 和 promise 的。
https://pro.ant.design/components/Authorized-cn/
传入function就可以了

**Comment by robinren240** [comment]
同问，如果一个用户拥有多个角色的情况
`const Authorized = RenderAuthorized('user');`

>/**
 * 通用权限检查方法
 * Common check permissions method
 * @param { 权限判定 Permission judgment type string |array | Promise | Function } authority
 * @param { 你的权限 Your permission description  type:string} currentAuthority
 * @param { 通过的组件 Passing components } target
 * @param { 未通过的组件 no pass components } Exception
 */
const checkPermissions = (authority, currentAuthority, target, Exception) => 

这个currentAuthority是一个string，这样判断多角色权限并集应该如何解决？

**Comment by chenshuai2144** [comment]
传入function 会忽略currentAuthority。只要function返回true就会通过

**Comment by robinren240** [comment]
@chenshuai2144 你的意思是使用function和后台做交互，直接判断权限么？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/components/Authorized-cn/
看看这个示例代码

**Comment by WhatAKitty** [comment]
authority不仅仅限于role，系统本身不限制这个。pro的role只是个距离

**Comment by robinren240** [comment]
@chenshuai2144 这个示例代码看到了。我是新接触到这块。是我之前没有表达清楚吗？


> const Authorized = RenderAuthorized(user.role);
const noMatch = <Alert message="No permission." type="error" showIcon />;

>const havePermission = () => {
  return false;
};

这里，如果user.role得到的是一个数组['user','admin']，这样使用func做参数怎么写？
或者说user.role得到多角色的情况应该怎样实现？
麻烦您给详细说一下。

**Comment by chenshuai2144** [comment]
@robinren240  自己写判断逻辑。。。
定义这样一个方法。
`(roleArray) => boolean`
考试要自己考。 不要直接抄答案。

**Comment by robinren240** [comment]
@chenshuai2144 你误会了。
const havePermission = (user) => {
    // do something 
    return true;
};
是涉及到的用户都在这里判断么？
这个用户增加了角色是不是要所有涉及到这里的地方都改代码？
拜托您这个简单回复真的没有说清楚。三次回复都没有。。。

**Comment by chenshuai2144** [comment]
你封装成一个方法不就好了。。
比如 
`havePermission` 每个地方都穿传这个方法不就好了
你没有通用的判断方式？

**Comment by chenshuai2144** [comment]
有思路不就好了。。。。。。。难不成我帮你把代码都写好。

**Comment by robinren240** [comment]
const Authorized = RenderAuthorized('user');
const havePermission = () => {
  return false;
};
确认下：
authority={havePermission} 这里传function的话，RenderAuthorized('user')这块无论些什么都是只看function的return值。
这样就实现了多角色并集控制是么？

**Comment by chenshuai2144** [comment]
对 function就忽略RenderAuthorized的值了

**Comment by robinren240** [comment]
多些解答。之前简单回复确实没看懂。

**Comment by wuzehao16** [comment]
@chenshuai2144 看了这么多还是没有懂...
{
  name: '系统管理',
  icon: 'user',
  path: 'system',
  authority: 'admin',
  children: [{
    name: '用户管理',
    path: 'user',
    authority: 'sys:role',
  },
  {
    name: '菜单管理',
    path: 'menu',
    authority: 'sys:menu',
  },
  {

**Comment by wuzehao16** [comment]
@chenshuai2144 看了这么多还是没有懂。。
我的menuDate是这样的
```
  name: '系统管理',
  icon: 'user',
  path: 'system',
  authority: 'admin',
  children: [{
    name: '用户管理',
    path: 'user',
    authority: 'sys:role',
  },
  {
    name: '菜单管理',
    path: 'menu',
    authority: 'sys:menu',
  }]
```
比如我login返回的authority，是个数组，[‘sys:role’,'sys:menu']
应该怎么处理

**Comment by WhatAKitty** [comment]
@wuzehao16 目前貌似只支持string,如果是数组你需要改代码：
```
  // 没有判定权限.默认查看所有
  // Retirement authority, return target;
  if (!authority) {
    return target;
  }
  // 数组处理
  if (Array.isArray(authority)) {
   // 修改点
    if (currentAuthority.filter(auth => authority.indexOf(auth) > 0).length === authority.length) {
      return target;
    }
    return Exception;
  }

  // string 处理
  if (typeof authority === 'string') {
 // 修改点
    if (currentAuthority.indexOf(authority) > -1) {
      return target;
    }
    return Exception;
  }
```

**Comment by WhatAKitty** [comment]
。。。忽略之前的答案，搞错了

**Comment by WhatAKitty** [comment]
@wuzehao16 


```
  // 没有判定权限.默认查看所有
  // Retirement authority, return target;
  if (!authority) {
    return target;
  }
  // 数组处理
  if (Array.isArray(authority)) {
    if (currentAuthority.filter(auth => authority.indexOf(auth) > 0).length === authority.length) {
      return target;
    }
    return Exception;
  }

  // string 处理
  if (typeof authority === 'string') {
    if (currentAuthority.indexOf(authority) > -1) {
      return target;
    }
    return Exception;
  }
```

**Comment by linyuliang** [comment]
@WhatAKitty 你这个改的是checkPermission.js?

**Comment by 1987zfp** [comment]
关注
