### ISSUE TITLE
🐛[BUG] 使用请求报错

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#6861]
### 🐛 bug 描述

页面请求时不使用 try catch 会报错

### 📷 复现步骤
修改app.tsx 后, 后台请求返回success false后就会出现

### © 版本信息

- Ant Design Pro 版本:  5.0.0
- umi 版本 3.2.3
- 浏览器环境 Chrome  78
- 开发环境 win 10

### 🚑 其他信息
![报错](https://user-images.githubusercontent.com/34082148/85086801-44b1a300-b20e-11ea-8c14-e64180c17a4f.png)
![code](https://user-images.githubusercontent.com/34082148/85086802-454a3980-b20e-11ea-976c-7872dea4866f.png)
![app tsx](https://user-images.githubusercontent.com/34082148/85086807-48452a00-b20e-11ea-8086-9b0c2d2b879a.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/92998756-76f14900-f54e-11ea-8c16-fe2aa438d06a.png)

用了 await，记得 try catch
