### ISSUE TITLE
🐛[BUG] 二级及以下菜单配置 icon 无效 V5

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6862]
### 🐛 bug 描述

二级及以下菜单配置 icon 无效 V5

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
这个问题我也遇到了.

**Comment by chenshuai2144** [comment]
其实是个新功能 第二级的菜单都不应该有图标

**Comment by kaoding** [comment]
我现有的系统升级就看不到图标了，这个功能好像有点太强执性了，二级菜单不应该有图标应该是推荐功能（我本来也不太喜欢二级菜单有图标）。

**Comment by kaoding** [comment]
在文档中可以加一栏"最佳实践"的说明，以文档的方式告诉大家怎么做更符合"最佳实践"。
"最佳实践"可以有2种方式并存：
一种是程序约定（强执）的方式
另一种是文档约定（推荐）的方式

**Comment by chenshuai2144** [comment]
文档约定就是没有约定的，还是要强制

**Comment by HQDragon** [comment]
emmm,刚create下来的项目，二级菜单都设置了icon，这不是个好方案，我想要图标都要不成了吗？

**Comment by phoema** [comment]
我为二级菜单绞尽脑汁匹配了很多图标，一升级全部不显示了。。。。

**Comment by kaoding** [comment]
这个强制还是建议要取消。

**Comment by Huanzi0703** [comment]
这个有点不给力了 遇到同样问题

**Comment by wmf508** [comment]
今天刚接的项目，一级没图标，二级才有，结果你这给老子强制取消了，还用毛线啊

**Comment by hhniao** [comment]
总是搞这种圣诞彩蛋, 强制性.

**Comment by zhoubichuan** [comment]
这个问题有解决吗，同样遇到了
