### ISSUE TITLE
antd  pro侧边栏收缩很卡顿

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#6863]
### 🧐 问题描述
  我页面布局是这样的左边是侧边栏 右边是地图 地图会上覆盖一些其他DOM和Ecahrts 收缩的时候很不流畅 我发现复杂的页面会很卡顿   我查了下资料发现vue-element也会有有如此情况 https://github.com/PanJiaChen/vue-element-admin/issues/937   希望优化一下  @chenshuai2144 

### 🚑 其他信息
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "2.2.7",

**Comment by chenshuai2144** [comment]
这个感觉不是我们组件库能做到的，你可以试试惰性一下，减少页面的上的渲染速度
