### ISSUE TITLE
👑 [需求] 菜单栏显示Badge徽章图标

### ISSUE THREAD

**Issue by lixiuna0908** [ant-design/ant-design-pro#6865]
### 🥰 需求描述

菜单栏显示Badge徽章图标

**Comment by chenshuai2144** [comment]
在 renderMenuItem 里试试, 官方没有提供功能

**Comment by zhangfu-git** [comment]
@chenshuai2144 最新版本是在哪里注入renderMenuItem？

**Comment by imgoby** [comment]
https://github.com/ant-design/ant-design-pro/issues/10178

![image](https://github.com/ant-design/ant-design-pro/assets/27885492/b61d574d-1fbc-43a3-92ee-69f9708ff567)

https://github.com/ant-design/ant-design-pro-layout
