### ISSUE TITLE
用脚手架创建的项目登录报405

### ISSUE THREAD

**Issue by zhouzhaojun-zhouzhouzhou** [ant-design/ant-design-pro#6867]
### 🧐 问题描述

用脚手架创建的项目登录报405， 输入的 用户名：admin 或者 user 和 密码：ant.design 

![image](https://user-images.githubusercontent.com/59383096/85227951-0933f600-b413-11ea-8244-333d8042a5e8.png)

**Comment by chenshuai2144** [comment]
这个是为了让你体验一下登录权限的感觉。

**Comment by 15207799874** [comment]
所以我要怎么样才能登录?

**Comment by waylon-edmodo** [comment]
"start:dev": "cross-env REACT_APP_ENV=dev umi dev",

这里的mock=none 去掉一下就行了。
