### ISSUE TITLE
👑 [需求]请问如何在这个里面使用mobx改变数据，从而渲染组件？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#6869]
### 🥰 需求描述

请问如何在这个里面使用mobx改变数据，从而渲染组件？现在里面使用的是reduce，我感觉这个里面的reduce使用起来，太复杂，嵌套的太多了，没有mobx简洁，方便，直观；想请教，如何在antd pro4.0里使用mobx，或者有没有mobx版本的，或者有没有在antd pro4.0的基础上使用mobx的案例？

### 🧐 解决方案
mobx

**Comment by chenshuai2144** [comment]
试试我们最新的 https://umijs.org/zh-CN/plugins/plugin-model
用起来灰常简单。 mobx 我们这边都没有研究

**Comment by pxim** [comment]
> 试试我们最新的 https://umijs.org/zh-CN/plugins/plugin-model
> 用起来灰常简单。 mobx 我们这边都没有研究

好的，我学习下，谢谢
