### ISSUE TITLE
修改mock权限编码问题

### ISSUE THREAD

**Issue by l-Lemon** [ant-design/ant-design-pro#687]
我只是修改了mock里面返回的权限编码，
![image](https://user-images.githubusercontent.com/25998672/34927609-5d6f3fe6-f9f2-11e7-9512-3c762bfb268d.png)

刷新页面后就这样了
![image](https://user-images.githubusercontent.com/25998672/34927520-b6386608-f9f1-11e7-8925-1a78ca50b157.png)

**Comment by chenshuai2144** [comment]
这个权限没有任何页面能访问。。
所以就一直跳转了。把login页面给他加上权限
