### ISSUE TITLE
>SelectLang 自定义下拉语言选项无效

### ISSUE THREAD

**Issue by rudyzou** [ant-design/ant-design-pro#6870]
V5版本，语言我只需要中文和英文。原本我以为SelectLang 支持 postLocalesData 的，或者把 locale 的文件夹删掉就可以了，但是这两种操作都没效果。看了umi插件编译出来的代码好像是写死的，不知道是不是bug。
下面是我代码，哪位大神帮忙看看是否有问题或者有遇到同样的问题没有？：
locales
![image](https://user-images.githubusercontent.com/4281891/85089344-023f9480-b215-11ea-97f0-3f1f89ee6e7b.png)

SelectLang
![image](https://user-images.githubusercontent.com/4281891/85089378-1c797280-b215-11ea-9699-afbb20b0260b.png)

_Originally posted by @rudyzou in https://github.com/ant-design/ant-design-pro/issues/6859#issuecomment-646395267_

**Comment by chenshuai2144** [comment]
搞完之后要重启一下项目的，这样文件会重新生成

**Comment by rudyzou** [comment]
> 搞完之后要重启一下项目的，这样文件会重新生成

重启很多次了。跟umi或者locale插件版本有关系吗？

**Comment by YuYanzy** [comment]
在V4版本遇到了同样的问题
翻遍了所有提到“语言”的issue都没有找到解决方案，可能只能自己重写SelectLang组件，决定暂时先去掉国际化功能了

**Comment by YuYanzy** [comment]
我的问题解决了
https://github.com/ant-design/ant-design-pro/issues/6859#issuecomment-751155937
