### ISSUE TITLE
安装后IED提示Error: .eslintrc.js 

### ISSUE THREAD

**Issue by firstbullet** [ant-design/ant-design-pro#6873]
### 🧐 安装后IED提示Error: .eslintrc.js 

然后执行了下npm run lint看看，结果也出现同样错误信息：
`
Error: .eslintrc.js ：node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js »  /node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/rules/imports.js:
        Configuration for rule "import/no-cycle" is invalid:
        Value null should be integer.
`
### 🚑 其他信息
使用版本V5.0，头一次使用，根据官方介绍的安装方法进行的安装！

<img width="844" alt="WX20200622-224503@2x" src="https://user-images.githubusercontent.com/17379629/85301229-28e22180-b4da-11ea-9aa6-d60f0845305c.png">

**Comment by afc163** [comment]
See https://github.com/eslint/eslint/issues/13427

**Comment by afc163** [comment]
eslint 新版已修复。
