### ISSUE TITLE
🧐[问题]ant design pro配置config中routes，怎么配置隐藏三级菜单，让二级菜单可点击

### ISSUE THREAD

**Issue by CooCleC** [ant-design/ant-design-pro#6874]
### 🧐 问题描述

ant design pro配置config中routes，怎么配置隐藏三级菜单，让二级菜单可点击

### 💻 示例代码

      path: '/ceshi',
      name: '测试',
      icon: 'dashboard',
      access: 'canAdmin',
      routes: [
        {
          path: '/ceshi',
          redirect: '/ceshi/erjicaidan',
        },
        {
          path: '/ceshi/erjicaidan',
          name: '二级菜单',
          hideChildrenInMenu: true,
          component: './ceshi/erjicaidan/_layout',
          routes: [
            {
              path: '/ceshi/erjicaidan',
              redirect: '/ceshi/erjicaidan/sanjicaidan1',
            },
            {
              path: '/ceshi/erjicaidan/sanjicaidan1',
              name: '三级菜单1',
              component: './ceshi/erjicaidan/sanjicaidan1',
            },
            {
              path: '/ceshi/erjicaidan/sanjicaidan2',
              name: '三级菜单2',
              component: './ceshi/erjicaidan/sanjicaidan2',
            }]
}]

© 版本信息
Ant Design Pro 版本: 5.0.0-alpha.0
umi 版本: ^3.1.0
浏览器环境: chrome
开发环境: Mac
pro-layout版本：6.0.0-8

**Comment by CooCleC** [comment]
查询了好多个issues， 发现了https://umijs.org/zh-CN/plugins/plugin-layout#menu 这个文档，然后换成了hideMenu: true，问题解决

**Comment by minzojian** [comment]
```
{
                  path: 'designers',
                  name: '设计师管理',
                  routes: [
                    {
                      path: 'designers/:designerId',
                      name: '设计师管理',
                      icon: 'user',
                      hideInMenu: true,
                      component: './users/designers/designer',
                    },
                    {
                      path: 'index',
                      name: '设计师管理(实际应该到达的首页)',
                      icon: 'team',
                      component: './users/designers',
                    },
                    {
                 //我在这里做跳转，原本的意思是希望点上边的一级菜单的时候，自动跳到同级的index页。
                      redirect: 'index',
                    },
                  ],
                }
```
我也是想实现个类似效果，想点某个隐藏了子菜单的一级菜单，使其直接路由跳到其下级菜单里的首页路由，不过一旦我在一级上设了hideChildrenMenu,一级菜单点了就没啥反应，也没有触发二级里的默认跳转路由。
请问你最后具体是怎么实现的呢？能否分享一下你相关代码？

**Comment by CooCleC** [comment]
@minzojian 看一下我上面那个链接，里面有具体的配置说明，看不懂再问我

**Comment by admiao** [comment]
我每次都为路由配置烦恼 ， 查了很多文档也没有答案。
