### ISSUE TITLE
页面里面的401 怎么不  Response.redirect('/user/login');

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#6875]
![image](https://user-images.githubusercontent.com/32530210/85380712-d4898100-b56f-11ea-9d2e-750f69704942.png)

![image](https://user-images.githubusercontent.com/32530210/85380855-fedb3e80-b56f-11ea-9748-156a1cd44e98.png)

感觉第一次进去，回车，拿用户信息401是跳转了下，进去后在里面，如果再401，就不跳了。

不知道是哪里有机关，又！

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/86312221-cfee5800-bc54-11ea-8b88-756a8b03e46c.png)


你应该用 history.push('login')

**Comment by xyzabc0004** [comment]
啊，谢谢，我试哈看。
