### ISSUE TITLE
Select组件使用showSearch后 使用tab键切换到Select组件时 Select不能自动获得输入焦点 需要按回车才能输入文字

### ISSUE THREAD

**Issue by BadWangc** [ant-design/ant-design-pro#6876]
Select使用showSearch后 
使用tab键切到Select组件时 Select不能自动获得输入焦点 需要按回车才能输入文字
有没有办法能和Input组件一样 使用tab键切到组件时 自动获得输入焦点
Input组件效果
![image](https://user-images.githubusercontent.com/46133235/85392328-effb8880-b57d-11ea-8e17-e105bc05bf71.png)
Select组件效果
![image](https://user-images.githubusercontent.com/46133235/85392451-1faa9080-b57e-11ea-9162-381db08e4827.png)

**Comment by chenshuai2144** [comment]
用 ref 获得一下焦点吧。

const ref = useRef();
<Select ref={ref} />

**Comment by BadWangc** [comment]
> 用ref获得一下焦点吧。
> 
> ```
> const ref = useRef();
> <Select ref={ref} />
> ```
您好 我是这样用的
ref={(selectRef) => this.selectRef = selectRef}

var inputRef = this.selectRef.rcSelect.inputRef;
inputRef.focus();

通过ref给select中的input设置焦点无效 这是什么问题呢？
