### ISSUE TITLE
🐛[BUG]样式内容重复

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design-pro#6877]
### 🐛 bug 描述

1. `production`模式 
1. 有A、B两个Page，两个Page都引入了antd的`Tag`组件
2. 先点击A，然后在点击B，查看开发者工具
3. 发现了Tag的样式重复，且相互覆盖

### 📷 复现步骤

1. 在global.less文件中导入样式
```js
@import '~antd/es/style/index.less';
```

2. 分别在A、B中各自定义业务样式，并分别给Tag组件定义自定义的className

3. 在A、B中引入样式的方法是
```js
import './index.less';
```

### 🏞 期望结果

1. 不出现重复样式内容

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
v4
- umi 版本
v3.1.4
- 浏览器环境
chrome83
- 开发环境 [e.g. mac OS]
win10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13702561/85426522-2997b800-b5ad-11ea-8d2f-3e275e8c2fe1.png)

**Comment by chenshuai2144** [comment]
最好不要在 global.less 里最这种事情。
global.less 有些特殊的逻辑

**Comment by Rhuaer** [comment]
1. 把`@import '~antd/es/style/index.less';`去掉后仍然存在该问题
2. 是指哪个插件？
3. 我开个demo看看能否复现这个问题
