### ISSUE TITLE
🧐[问题]更新pro-layout的版本之后，菜单不显示

### ISSUE THREAD

**Issue by LiUhoNgDan222** [ant-design/ant-design-pro#6878]
### 🧐 问题描述
我升级了pro-layout的版本之后，菜单用的从服务器拉取数据，但是现在菜单不显示了

### 🚑 其他信息
  "@ant-design/pro-layout": "^6.0.0-7",
    "umi": "3.1.4",

**Comment by chenshuai2144** [comment]
代码展示一下，你是怎么用的

**Comment by LiUhoNgDan222** [comment]
> 代码展示一下，你是怎么用的

/**
 * Ant Design Pro v4 use `@ant-design/pro-layout` to handle Layout.
 * You can view component api by:
 * https://github.com/ant-design/ant-design-pro-layout
 */
import ProLayout, { DefaultFooter } from '@ant-design/pro-layout';
import React, { useEffect, useState } from 'react';
import { Link, useIntl, connect } from 'umi';
import { Result, Button } from 'antd';
import ReactWaterMark from 'react-watermark-component';
import Authorized from '@/utils/Authorized';
import { getAuthorityFromRouter } from '@/utils/utils';
import logo from '../assets/logo.png';
import globalStyle from '../global.less';

const noMatch = (
  <Result
    status={403}
    title="403"
    subTitle="Sorry, you are not authorized to access this page."
    extra={
      <Button type="primary">
        <Link to="/user/login">Go Login</Link>
      </Button>
    }
  />
);

/**
 * use Authorized check all menu item
 */
const menuDataRender = (menuList) =>
  menuList.map((item) => {
    const localItem = {
      ...item,
      children: item.children ? menuDataRender(item.children) : [],
      onTitleClick: (e) => console.log(e),
    };
    return Authorized.check(item.authority, localItem, null);
  });

const defaultFooterDom = (
  <DefaultFooter
    links={false}
    className={globalStyle.footer}
  />
);

const footerRender = () => <>{defaultFooterDom}</>;
const remoteMenu = true;
const BasicLayout = (props) => {
  const {
    dispatch,
    children,
    settings,
    location = {
      pathname: '/',
    },
    currentUser,
  } = props;
  /**
   * constructor
   */

  const [menuData, setMenuData] = useState([]);

  useEffect(() => {
    if (dispatch) {
      dispatch({
        type: 'user/fetchCurrent',
      });
    }

    if (dispatch) {
      dispatch({
        type: 'global/fetchMenu',
        callback: (data) => {
          setMenuData(data || []);
        },
      });
    }
  }, []);

  const menuDataRenderRemote = (menuList) =>
    menuList.map((item) => {
      const localItem = {
        ...item,
        key: item.menuId,
        name: item.menuName,
        path:
          item.menuUrl.indexOf('http') === -1 ? item.menuUrl : encodeURIComponent(item.menuUrl),
        children: item.children ? menuDataRenderRemote(item.children) : [],
      };
      return localItem;
    });
  /**
   * init variables
   */

  /**
   * 门户退出 子系统也退出
   */
  window.logoutGlobal = () => {
    console.log('logout subsystem');
    // eslint-disable-next-line no-underscore-dangle
    dispatch({
      type: 'login/logout',
    });
  };

  const handleMenuCollapse = (payload) => {
    if (dispatch) {
      dispatch({
        type: 'global/changeLayoutCollapsed',
        payload,
      });
    }
  }; // get children authority

  const alarmWatermarkChanged = () => {
    console.error("don't not modify the watermark");
  };

  const authorized = getAuthorityFromRouter(props.route.routes, location.pathname || '/') || {
    authority: undefined,
  };

  const { formatMessage } = useIntl();

  return (
    <ReactWaterMark
      waterMarkText={`${currentUser.userName} ${currentUser.userNickname || ''}`}
      openSecurityDefense
      securityAlarm={alarmWatermarkChanged}
    >
      <>
        <ProLayout
          logo={logo}
          formatMessage={formatMessage}
          menuHeaderRender={(logoDom, titleDome) => <Link to="/">{logoDom}{titleDome}</Link>}
          onCollapse={handleMenuCollapse}
          menuItemRender={(menuItemProps, defaultDom) => {
            if (menuItemProps.isUrl || menuItemProps.children || !menuItemProps.path) {
              return defaultDom;
            }
            return <Link to={menuItemProps.path}>{defaultDom}</Link>;
          }}
          breadcrumbRender={(routers = []) => [
            {
              path: '/',
              breadcrumbName: formatMessage({
                id: 'menu.home',
              }),
            },
            ...routers,
          ]}
          itemRender={(route, params, routes, paths) => {
            const first = routes.indexOf(route) === 0;
            return first ? (
              <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
            ) : (
              <span>{route.breadcrumbName}</span>
            );
          }}
          footerRender={footerRender}
          menuDataRender={remoteMenu ? () => menuDataRenderRemote(menuData) : menuDataRender}
          rightContentRender={() => null}
          {...props}
          menuProps={{
            onSelect: (e) => {
              console.log('menu selected', e);
              // eslint-disable-next-line no-restricted-globals
              const pWindow = parent && parent.window;
              if (pWindow && pWindow.getIframeHash) {
                pWindow.getIframeHash(window.location.href);
              }
            },
          }}
          onMenuHeaderClick={(e) => console.log('menu header click', e)}
          {...settings}
          siderWidth={200}
          // 需要header把 headerRende{false}移除
          headerRender={false}
        >
          <Authorized authority={authorized.authority} noMatch={noMatch}>
            {children}
          </Authorized>
        </ProLayout>
      </>
    </ReactWaterMark>
  );
};

export default connect(({ global, user, settings }) => ({
  collapsed: global.collapsed,
  currentUser: user.currentUser,
  settings,
}))(BasicLayout);

**Comment by LiUhoNgDan222** [comment]
有2个系统，代码都是一样的，然后一个行，一个不行

**Comment by chenshuai2144** [comment]
menuData 给我一下

**Comment by LiUhoNgDan222** [comment]
[{
	"fullPath": "1252775113613139968-",
	"grade": 1,
	"icon": "",
	"isLeaf": false,
	"menuId": "1252775113613139968",
	"menuName": "首页",
	"menuType": "menu",
	"menuUrl": "/welcome",
	"parentId": "0",
	"perms": "*",
	"rootId": "1252774861802205184",
	"sortCode": 1
}, {
	"children": [{
		"fullPath": "1273445352035233792-1273445451222384640-",
		"grade": 2,
		"icon": "",
		"isLeaf": false,
		"menuId": "1273445451222384640",
		"menuName": "故障车辆查询",
		"menuType": "menu",
		"menuUrl": "/faultMonitoring/realTime",
		"parentId": "1273445352035233792",
		"perms": "*",
		"rootId": "1252774861802205184",
		"sortCode": 10
	}, {
		"fullPath": "1273445352035233792-1273794837260308480-",
		"grade": 2,
		"icon": "",
		"isLeaf": false,
		"menuId": "1273794837260308480",
		"menuName": "单车故障监控",
		"menuType": "menu",
		"menuUrl": "/faultMonitoring/carSingle",
		"parentId": "1273445352035233792",
		"perms": "*",
		"rootId": "1252774861802205184",
		"sortCode": 20
	}, {
		"fullPath": "1273445352035233792-1273794620248203264-",
		"grade": 2,
		"icon": "",
		"isLeaf": false,
		"menuId": "1273794620248203264",
		"menuName": "故障诊断处理",
		"menuType": "menu",
		"menuUrl": "/faultMonitoring/faultLocation",
		"parentId": "1273445352035233792",
		"perms": "*",
		"rootId": "1252774861802205184",
		"sortCode": 30
	}],
	"fullPath": "1273445352035233792-",
	"grade": 1,
	"icon": "",
	"isLeaf": false,
	"menuId": "1273445352035233792",
	"menuName": "监控诊断",
	"menuType": "menu",
	"menuUrl": "/faultMonitoring",
	"parentId": "0",
	"perms": "*",
	"rootId": "1252774861802205184",
	"sortCode": 10
}]

**Comment by Asence** [comment]
我也遇到了这个问题  请问有解决方案吗？ 我现在版本是6.0.8，也是更新以后发现菜单出不来了

**Comment by Asence** [comment]
> menuData给我一下，记得脱敏

你好 我也遇到了这个问题 请问有解决的方案吗？

**Comment by chenshuai2144** [comment]
修复了，有人帮我找到了问题，升级一下 pro-layout 到 6.2.2
