### ISSUE TITLE
🧐[关于代码复杂性、可读性]

### ISSUE THREAD

**Issue by iT-lijun** [ant-design/ant-design-pro#6879]
### 🧐 代码复杂度令人头皮发麻、代码可读性糟糕透顶

当我把V5跑起来、并打算在Vscode阅读代码时。。。**震惊！震惊！！震惊！！！**
虽然以前2.x的代码有点面条 但是复杂度、可读性还是能接受的 自V4开始。。唉 不说了

**这个只是个人的直接感受 可以忽略不计**

**Comment by chenshuai2144** [comment]
哪里复杂了？
