### ISSUE TITLE
Ellipsis文本自动省略号 组件存在问题

### ISSUE THREAD

**Issue by soolx** [ant-design/ant-design-pro#688]
Ellipsis文本自动省略号 组件存在问题

Tooltip提示，显示不完整。
![2018-01-15](https://user-images.githubusercontent.com/7274864/34928773-99cb71a0-f9fa-11e7-833e-ac56c4c9a9aa.png)

内容没有自动换行。
![2018-01-15 1](https://user-images.githubusercontent.com/7274864/34928779-a8b70a4e-f9fa-11e7-98dd-a1388d4db34f.png)

**Comment by soolx** [comment]
![2018-01-15 2](https://user-images.githubusercontent.com/7274864/34928795-d65c281c-f9fa-11e7-82ae-4970fe242590.png)

**Comment by theBestVayne** [comment]
这个组件我在设置 **多行** 省略时也遇到了问题：tooltip总是无法显示

**Comment by ddcat1115** [comment]
fixed in  https://github.com/ant-design/ant-design-pro/commit/e7ddfff8e80e77fc2562a79181f2c552f58d41ad
