### ISSUE TITLE
RTL still no support - Check my PR on umi/plugins

### ISSUE THREAD

**Issue by shakesBeardZ** [ant-design/ant-design-pro#6880]
@chenshuai2144, unfortunately, the issue is not solved, as I explained before we need to pass the direction to ConfigProvider in order for ant design to detect the direction after I requested my PR to be merged in umi/plugins
I thought when it's gonna be merged to pro branch it will provide the direction attribute but no, although my PR is merged to pro branch nothing has changed here.
Does that mean that I have to merge my PR to a different branch?!!!
the result should be like this:

![image](https://user-images.githubusercontent.com/15571628/85502804-cc255a80-b5f0-11ea-8669-75eb3a78dddc.png)

I hope you can look into it.

**Comment by chenshuai2144** [comment]
Waiting for your pr to post

**Comment by shakesBeardZ** [comment]
@chenshuai2144 sorry what do you mean post, it's already merged to ```pro``` branch?

**Comment by shakesBeardZ** [comment]
@chenshuai2144  look to understand what and design pro needs to support RTL check this 

```
  <ConfigProvider locale={localeInfo[locale]?.antd || defaultAntdLocale}>
      <RawIntlProvider value={intl}>{props.children}</RawIntlProvider>
    </ConfigProvider>
```

this should be supporting ```direction``` like this 

```
  <ConfigProvider direction={direction} locale={localeInfo[locale]?.antd || defaultAntdLocale}>
      <RawIntlProvider value={intl}>{props.children}</RawIntlProvider>
    </ConfigProvider>
```

**Comment by smddzcy** [comment]
It would be awesome to have this feature on ConfigProvider. @chenshuai2144 do you have any plans for this feature?

**Comment by chenshuai2144** [comment]
can use

```
export default {
  antd: {
    config:{
        direction: direction,
        componentSize:'small'
    }
  },
}
```
