### ISSUE TITLE
🐛[BUG]V5版本，小屏幕下，多语言的框被挡住了

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/ant-design-pro#6881]
### 🐛 bug 描述

V5版本，小屏幕下，多语言的框被挡住了。如图：

### © 版本信息

- Ant Design Pro 版本: V5

### 🚑 其他信息

<img width="496" alt="截屏2020-06-24 23 46 59" src="https://user-images.githubusercontent.com/51048705/85588402-3d0e5600-b675-11ea-9382-4122a974c0f8.png">

**Comment by chenshuai2144** [comment]
更新一下 umi locale 的版本就好了
