### ISSUE TITLE
 Ant Design Pro 的图表组件定位问题🐛[BUG]

### ISSUE THREAD

**Issue by YongquanYao** [ant-design/ant-design-pro#6882]
### 🐛 bug 描述
在项目里独立引入了 Ant Design Pro 的图表组件,发现图表数据显示定位不准确。在chrome,safari,edge浏览器里鼠标定位信息都是错的。在firefox里用则是正常的。有老大来看看这个是什么问题？？

### 📷 复现
1. chrome浏览器错位：
![IMG_8452](https://user-images.githubusercontent.com/45799780/85598061-36ea8c00-b619-11ea-8921-9cdd649f56be.jpg)
2.firefox浏览器正常：
![IMG_7119](https://user-images.githubusercontent.com/45799780/85598123-4964c580-b619-11ea-8d50-4e16fc90b55a.jpg)

### © 版本信息

 "@ant-design/pro-layout": "^5.0.8",
 "umi": "3.1.2",
- firefox: 77.0.1
-chrome: 83.0.4103.106
-edge: 83.0.478.54
-  mac OS 10.15.5

**Comment by chenshuai2144** [comment]
http://charts.ant.design/
试试这个，antd 的已经停止维护了
