### ISSUE TITLE
🐛[BUG]pro V5.1的登陆界面出现菜单树

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#6884]
### 🐛 bug 描述

pro V5.1的登陆界面出现菜单树

### 📷 复现步骤

当fetch blocks后，登录界面的左侧出现了菜单树

### 🏞 期望结果

不应该出现菜单树

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.1.0]
- umi 版本3.2.3
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51013754/85819377-126fea80-b7a6-11ea-925d-b4b9922ba9ba.png)

**Comment by mushroomlb** [comment]
路由配置有问题，登录页面不能在BasicLayout中，需要单独一个

**Comment by effapp** [comment]
找到原因了，fetch blocks后，路由变成 layout=false了，修改成hideLayout=true就正常了。
