### ISSUE TITLE
🧐[问题]request携带请求头不生效?

### ISSUE THREAD

**Issue by sunluby** [ant-design/ant-design-pro#6887]
### 🧐 问题描述
修改@utils/request.ts文件, 增加headers, 但是请求并没有携带token请求头信息..不知为啥

### 💻 示例代码
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  headers: {
    token: localStorage.getItem('token'),
  }
});

**Comment by liujiayii** [comment]
这个request只创建一次，创建的时候local存储还么有呢，得动态改一下

**Comment by sunluby** [comment]
呃,随便带个什么字符串也没有名为token的请求头啊...

**Comment by mushroomlb** [comment]
了解下header基础知识，了解authorization 和 authentication区别

**Comment by chenshuai2144** [comment]
要用拦截器，不能这么粗暴地

**Comment by sunluby** [comment]
已经靠自己解决了...@utils/request.ts文件, 增加myrequest
```
const request = extend({
  errorHandler, // 默认错误处理
  // credentials: 'include', // 默认请求是否带上cookie
});

const myRequest = (url: string, options = {}) => {
  return request(url, {
    ...options,
    headers: {
      ...options.headers,
      token: `${localStorage.getItem('token')}`,
    },
  });
};
export default myRequest;
```
