### ISSUE TITLE
🐛关于黑色主题的几个缺陷

### ISSUE THREAD

**Issue by xcj01010203** [ant-design/ant-design-pro#6888]
### 🐛 bug 描述

我用的ant design pro V4
defaultSettings.js里navTheme设置为light
按照官方步骤集成里主题切换的功能后，切换为暗色主题，左侧菜单没有变成暗色
![image](https://user-images.githubusercontent.com/20202711/85936009-47f11100-b929-11ea-8902-53a3b024e402.png)

### 🏞 期望结果
左侧菜单也变成黑色

### 💻 复现代码
defaultSettings配置
export default {
  navTheme: 'light',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'sidemenu',
  contentWidth: 'Fluid',
  fixedHeader: false,
  autoHideHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  menu: {
    locale: true,
  },
  title: '数据管理平台',
  pwa: false,
  iconfontUrl: '',
};

### © 版本信息

- Ant Design Pro 版本:4.0.0
- umi 版本 3 

### 🚑 其他信息
查看样式后，发现以下样式有问题
![image](https://user-images.githubusercontent.com/20202711/85936041-7f5fbd80-b929-11ea-93d4-4830580e0b19.png)
![image](https://user-images.githubusercontent.com/20202711/85936049-8d154300-b929-11ea-8a13-5cd030c7964f.png)

**Comment by xcj01010203** [comment]
dark.css中，h3的样式没有设置字体颜色
h3 {
    margin-bottom: 20px;
    font-size: 16px;
}

多了条菜单背景白色的设置
.ant-pro-sider-menu-sider.light {
    background-color: #fff;
    box-shadow: 2px 0 8px 0 rgba(29,35,41,0.05);
}

**Comment by xcj01010203** [comment]
再补充一个
![image](https://user-images.githubusercontent.com/20202711/85938867-898eb580-b943-11ea-9477-dda3432e3fd2.png)


请问下，如果想更改dark.css内容，到哪里更改，如何更新？

**Comment by xrkffgg** [comment]
可以直接在自己项目中根据名称改 css，引入就行

**Comment by xrkffgg** [comment]
试试 
```
"navTheme": "realDark",
```

**Comment by xcj01010203** [comment]
> 试试
> 
> ```
> "navTheme": "realDark",
> ```

主要是想项目初始用light主题，改了navTheme就达不到这个需求了

**Comment by xcj01010203** [comment]
> 可以直接在自己项目中根据名称改 css，引入就行

如果自定重新定义css，样式太多了，而且除了指出的几个，其他都跟dark.css一样；无法更改dark.css，或者在dark.css基础上自定义吗？

**Comment by xrkffgg** [comment]
设了 light ，还想要 黑色。。。。😂😂😂

**Comment by xrkffgg** [comment]
在自己项目中  引一个 css ，然后在里面改就行

**Comment by xcj01010203** [comment]
> 设了 light ，还想要 黑色。。。。😂😂😂

白天模式是light，晚上模式是dark，感觉需求应该正常吧

**Comment by xrkffgg** [comment]
修改默认的css，会影响本身的。建议将 navTheme 进行动态修改。

**Comment by xcj01010203** [comment]
> 修改默认的css，会影响本身的。建议将 navTheme 进行动态修改。

navTheme如何动态修改，我看了官方文档，用的是这种方式
```
let styleLink = document.getElementById("theme-style");
    let body = document.getElementsByTagName('body')[0];
    if (styleLink) { // 假如存在id为theme-style 的link标签，直接修改其href
      styleLink.href = '/theme/'+ myTheme +'.css'; // 切换 antd 组件主题
    // body.className = "body-warp-theme1"; // 切换自定义组件的主题
    } else { // 不存在的话，则新建一个
      styleLink = document.createElement('link');
      styleLink.type = 'text/css';
      styleLink.rel = 'stylesheet';
      styleLink.id = 'theme-style';
      styleLink.href = '/theme/'+ myTheme +'.css';
      document.body.append(styleLink);
    }
```

**Comment by xrkffgg** [comment]
我晚上试试😂，之前没用过。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design-pro/blob/2a6b5a7a22950c15cb085c903bdefbe5c6a809a7/src/layouts/BasicLayout.tsx#L162

可以动态修改 `<ProLayout />` 传入的 [settings](https://github.com/ant-design/ant-design-pro-layout#Settings) 就可以了啊

**Comment by xcj01010203** [comment]
谢谢大佬，我试试

**Comment by xcj01010203** [comment]
自己做下总结
如果想实现白色模式和黑色模式之间切换，且默认为白色模式，做法如下
1、动态设置settings.js中的navTheme
(1)在setting.js中添加如下reducers
```
changeTheme(state, { payload }) {
      const { navTheme } = state;
      if (navTheme === 'dark') {
        return {...state, navTheme: 'light'}
      } else {
        return {...state, navTheme: 'dark'}
      }
    }
```
（2）在RightContent.jsx中添加如下方法
```
const changeTheme = () => {
    const { dispatch } = props;
    dispatch({
      type: 'settings/changeTheme',
      payload: {}
    });
}
```
动态设置的目的在于，如果黑色模式且navTheme=light，会出现我上面截图的样式问题

2、经过第一步操作，把navTheme改为dark后，只能达到官网默认的左边蓝色，右面白色的效果（把navTheme设置为realDark经过测试也是这个效果，估计是官方bug）；如果想做到黑色模式，还需要根据官方文档中的“动态主题-自定义使用方式”操作方式进行。
我的做法是在RightContent.jsx中添加如下代码
```
useEffect(() => {
    let styleLink = document.getElementById("theme-style");
    let body = document.getElementsByTagName('body')[0];
    if (styleLink) { // 假如存在id为theme-style 的link标签，直接修改其href
      styleLink.href = '/theme/'+ theme +'.css'; // 切换 antd 组件主题
    // body.className = "body-warp-theme1"; // 切换自定义组件的主题
    } else { // 不存在的话，则新建一个
      styleLink = document.createElement('link');
      styleLink.type = 'text/css';
      styleLink.rel = 'stylesheet';
      styleLink.id = 'theme-style';
      styleLink.href = '/theme/'+ theme +'.css';
      document.body.append(styleLink);
    }
  }, [theme]);
```

**Comment by shaodushu** [comment]
@xcj01010203 https://livecodestream.dev/post/2020-08-06-a-better-approach-to-dark-mode-on-your-website/
