### ISSUE TITLE
🧐[问题]v5版本怎样设置antD的语言为中文

### ISSUE THREAD

**Issue by blinkMyEyesConsciously** [ant-design/ant-design-pro#6896]
### 🧐 问题描述

v5版本去掉国际化后怎么 将antd的语言改成中文?

### 💻 示例代码

无

### 🚑 其他信息
我在https://github.com/ant-design/ant-design-pro/issues/6772 找到了v5 说可以在app.ts配置  但是具体怎么配置没有找到

**Comment by chenshuai2144** [comment]
在 app.ts 中
```
antd:{
	config:{
	    locale:{}
	}
}
```

**Comment by 569202812** [comment]
> export const antd= {
> 	config:{
> 	    locale:{}
> 	}
> }

设置了然后页面报错喃
![image](https://user-images.githubusercontent.com/34082148/88893522-0f6e8b00-d279-11ea-99ef-51dc5406e0ea.png)
![Uploading image.png…]()

**Comment by 569202812** [comment]
> 在 app.ts 中
> 
> ```
> export const antd= {
> 	config:{
> 	    locale:{}
> 	}
> }
> ```

新创建的项目也是报错
