### ISSUE TITLE
🧐[问题]antd proV4中已内置umi的插件，umi升级是否相关的umi插件也会升级？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#6898]
### 🧐 问题描述
使用antd proV4时，已内置umi,升级umi后是否对应的插件版本也会对应升级，如果不会，如何对应升级新的插件版本，例如@umijs/plugin-model等。现在单独安装的时候会提示该插件已存在，无法安装新的版本？

### 💻 示例代码

无

### 🚑 其他信息
antd pro：V4.0
umi：3.2.6

**Comment by chenshuai2144** [comment]
插件会自动安装最新的，不需要单独升级的

**Comment by Yana5417** [comment]
> 插件会自动安装最新的，不需要单独升级的

为什么按照v4的官网安装Ant Design Pro，package.json里面ant-design-pro的版本号是2.1.1，antd的版本号是3.10.9呢？
