### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by yinbiao** [ant-design/ant-design-pro#6899]
### 🐛 bug 描述

初始化项目后，在“查询表格”页面，选择多条记录时，selectedRows没有去重，导致数组有多个重复的记录。
应该是每次选中一行记录时，都将当前选中的记录行追加到selectedRows里面了。

### 📷 复现步骤

1、初始化项目
2、选择多行记录
![image](https://user-images.githubusercontent.com/11266046/86080529-b4087c00-bac5-11ea-88cd-ad246638eea9.png)
图中红框内的数字不对，他算了两个第一条数据加上一个第二条数据。

### 🏞 期望结果

期望的数字应该是第一条和第二条记录的总和

### © 版本信息

- ant-design-pro@4.0.0
- umi@3.2.3
- chrome  64.0.3282.186
- windows10

### 🚑 其他信息
我将selectedRows数值打印出来如下：
![image](https://user-images.githubusercontent.com/11266046/86080679-08abf700-bac6-11ea-8a76-41f027ffd4b1.png)

**Comment by chenshuai2144** [comment]
更新一下依赖吧，这个 bug 是一个多月前的问题了

**Comment by yinbiao** [comment]
更新了@ant-design/pro-table 到2.5.7 ，然后分页栏目那里的每页显示条数的下拉列表（20条/页，50条/页等这个控件），点击就没有反应了。
