### ISSUE TITLE
About upgrade guidance

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro#690]
Version 1.0 is very different from the previous version, and we recieved lots of consultation about how to upgrade to 1.0, the current [docs](https://pro.ant.design/docs/faq-cn#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0-Ant-Design-Pro%EF%BC%9F) should be more detailed.

Or is there any other better way too solve the upgrade issue...

**Comment by CrewS** [comment]
have the same problem

**Comment by heratech** [comment]
Hey, I would also like to know how to update/upgrade.
