### ISSUE TITLE
🧐[问题] PWA doesnot work

### ISSUE THREAD

**Issue by nguyenhuutinh** [ant-design/ant-design-pro#6900]
Hello, 
I just enable pwa: true in default settings, but service workers is not running?

with umi v2 works well,
do you know how to fix it?
thannks

**Comment by LamdoHeaven** [comment]
Actually, manifeist.json and service-worker.js are not copied or generated to output even though we set pwa:true, pwa might not have finished yet in v5.

**Comment by cundejo** [comment]
PWA Is not working either in v4.2.0, and is the same issue (manifest.json and service-worker.js files missing in build).

Any idea?

**Comment by sajjadshahi** [comment]
Any update on supporting PWA progress?!

**Comment by meijuji202** [comment]
umi 3 中删除了 PWA，寻找替代方案中……

**Comment by tan-c** [comment]
Any updates? This is a showblocker for us...

**Comment by kevinadhiguna** [comment]
Pardon me, any updates on this ?  @chenshuai2144 and @afc163 
Sorry for bothering you... any info will be appreciated 🙏

**Comment by 3hson** [comment]
> Pardon me, any updates on this ? @chenshuai2144 and @afc163
> Sorry for bothering you... any info will be appreciated

I think the problem comes from umijs3.

**Comment by Aloento** [comment]
> umi 3 中删除了 PWA，寻找替代方案中……

就离谱

**Comment by cundejo** [comment]
I just moved to Next.js

**Comment by conioX** [comment]
any news about this?

**Comment by gomaglev** [comment]
any news about this? 有进展吗？進展がありますか。

**Comment by gomaglev** [comment]
不支持PWA是硬伤啊

**Comment by ngudeveloper** [comment]
Any update about this? We used old version but we can't upgrade to new version anymore because we were using PWA......

**Comment by ngudeveloper** [comment]
> I just moved to Next.js

Is it easy to move from ant design to Next.js?

**Comment by ycang89** [comment]
所以是不支持PWA了？
