### ISSUE TITLE
🧐[问题]TS版本的V4的Dispatch报警告

### ISSUE THREAD

**Issue by zhaokera** [ant-design/ant-design-pro#6901]
### 🧐 问题描述

Dispatch报警告去不掉，怎么处理，网上查了半天也没找到相关的情况。。

### 🚑 其他信息

![E87A7867-82EC-4FC2-95A4-EA313BD85349](https://user-images.githubusercontent.com/10410744/86105339-ca2c3180-baf1-11ea-8f36-823c557cdc10.png)
![1FFDDFA1-CDEF-4CD6-B4AA-1BDA6683A84E](https://user-images.githubusercontent.com/10410744/86105349-cbf5f500-baf1-11ea-9c8c-7cc4087d2928.png)

**Comment by chenshuai2144** [comment]
不要写泛型就行了，试试我们的 ConnectProps

```
import { ConnectProps } from 'umi';
```

**Comment by zhaokera** [comment]
嗯嗯，我试试ConnectProps，我是因为看到脚手架生成的时候这样写的有点疑问

**Comment by zhaokera** [comment]
@chenshuai2144

**Comment by zhaokera** [comment]
![ts警告](https://user-images.githubusercontent.com/10410744/88123507-937f9d80-cbfd-11ea-81a5-b5e06625fe7e.png)
你们都没有这个警告吗？

**Comment by psybor** [comment]
export type Dispatch = <P = any, C = (payload: P) => void>() => any;
上面 umi 生成的泛型写错了， 
换成 Dispatch<P = any, C = (payload: P) => void> = () => any;  就对了。
不过这是 umi 的锅
