### ISSUE TITLE
from中使用radio报警告

### ISSUE THREAD

**Issue by maochongzi** [ant-design/ant-design-pro#6905]
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
![image](https://user-images.githubusercontent.com/34764808/86200302-dfa36900-bb8e-11ea-850b-d94b27161c7f.png)

**Comment by chenshuai2144** [comment]
看看你的代码？ 看起来是你没有实现 forwardRef 导致 ide

**Comment by maochongzi** [comment]
import React, { useState } from 'react';
import { Button, Card, Input, Form, Radio, Select } from 'antd';
import { connect } from 'umi';
import { PageHeaderWrapper } from '@ant-design/pro-layout';

const FormItem = Form.Item;
const { Option } = Select;

const BasicForm = (props) => {
  const { submitting } = props;
  const [form] = Form.useForm();
  const [showAll, setShowAll] = useState(false);
  const formItemLayout = {
    labelCol: {
      xs: {
        span: 24,
      },
      sm: {
        span: 7,
      },
    },
    wrapperCol: {
      xs: {
        span: 24,
      },
      sm: {
        span: 12,
      },
      md: {
        span: 10,
      },
    },
  };
  const submitFormLayout = {
    wrapperCol: {
      xs: {
        span: 24,
        offset: 0,
      },
      sm: {
        span: 10,
        offset: 7,
      },
    },
  };

  const onFinish = (values) => {
    const { dispatch } = props;
    dispatch({
      type: 'formAndbasicForm/submitRegularForm',
      payload: values,
    });
  };

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };

  const onValuesChange = (changedValues) => {
    const { type } = changedValues;
    if (type) setShowAll(type === '2');
  };

  return (
    <PageHeaderWrapper title={<span>添加单位</span>}>
      <Card
        bordered={false}
        title={
          <span>
            <strong style={{ color: '#1890ff' }}>丨</strong> 基础信息
          </span>
        }
      >
        <Form
          // hideRequiredMark
          style={{
            marginTop: 8,
          }}
          form={form}
          name="basic"
          initialValues={{
            type: '1',
          }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          onValuesChange={onValuesChange}
        >
          <FormItem
            {...formItemLayout}
            label="单位名称"
            name="title"
            rules={[
              {
                required: true,
                message: '请输入单位名称',
              },
            ]}
          >
            <Input placeholder="请输入准确的单位名称" />
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="社会统一信用代码"
            name="date"
            rules={[
              {
                required: true,
                message: '请输入社会统一信用代码',
              },
            ]}
          >
            <Input placeholder="请输入社会统一信用代码" />
          </FormItem>
          <FormItem {...formItemLayout} label="数据获取方式" name="type">
            <Radio.Group>
              <Radio value="1">自动爬取</Radio>
              <Radio value="2">手动输入</Radio>
            </Radio.Group>
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="单位简称"
            name="short_name"
            rules={[
              {
                required: showAll,
                message: '请输入单位简称',
              },
            ]}
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Input placeholder="请输入单位简称" />
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="所属地区"
            name="area"
            rules={[
              {
                required: showAll,
                message: '请选择地区',
              },
            ]}
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Select mode="multiple" placeholder="请选择地区">
              <Option value="1">1</Option>
              <Option value="2">2</Option>
              <Option value="3">3</Option>
            </Select>
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="用途类型"
            name="use_type"
            rules={[
              {
                required: showAll,
                message: '请选择用途类型',
              },
            ]}
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Select mode="multiple" placeholder="请选择用途类型">
              <Option value="1">1</Option>
              <Option value="2">2</Option>
              <Option value="3">3</Option>
            </Select>
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="单位类型"
            name="unit_type"
            rules={[
              {
                required: showAll,
                message: '请选择单位类型',
              },
            ]}
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Select placeholder="请选择单位类型">
              <Option value="1">1</Option>
              <Option value="2">2</Option>
              <Option value="3">3</Option>
            </Select>
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="行业类型"
            name="industry_type"
            rules={[
              {
                required: showAll,
                message: '请选择行业类型',
              },
            ]}
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Select mode="multiple" placeholder="请选择行业类型">
              <Option value="1">1</Option>
              <Option value="2">2</Option>
              <Option value="3">3</Option>
            </Select>
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="经纬度"
            name="jingweidu"
            rules={[
              {
                required: showAll,
                message: '请输入经纬度',
              },
            ]}
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Input placeholder="请输入经纬度" />
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="详细地址"
            name="adress"
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Input placeholder="请输入详细地址" />
          </FormItem>
          <FormItem
            {...formItemLayout}
            label="备注"
            name="mark"
            style={{ display: showAll ? 'flex' : 'none' }}
          >
            <Input placeholder="请输入备注" />
          </FormItem>
          <FormItem
            {...submitFormLayout}
            style={{
              marginTop: 32,
            }}
          >
            <Button type="primary" htmlType="submit" loading={submitting}>
              提交
            </Button>
            <Button
              style={{
                marginLeft: 8,
              }}
            >
              保存
            </Button>
          </FormItem>
        </Form>
      </Card>
    </PageHeaderWrapper>
  );
};

export default connect(({ loading }) => ({
  submitting: loading.effects['create/submitRegularForm'],
}))(BasicForm);

**Comment by lucifer1004** [comment]
I also encountered with this issue. 

```tsx
<Form.Item name="some">
  <Radio.Group>
    <Radio></Radio>
    <Radio></Radio>
  </Radio.Group>
</Form.Item>
```

will cause this error,

while

```tsx
<Form.Item>
  <Radio.Group>
    <Radio></Radio>
    <Radio></Radio>
  </Radio.Group>
</Form.Item>
```

is OK.

By the way, I did not use `redux`, just plain `react`.

**Comment by chenshuai2144** [comment]
antd is out
