### ISSUE TITLE
🧐[问题]app.tsx中layout的rightContentRender函数不执行

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6907]
### 🧐 问题描述

控制台未输出任何信息,导致我头像功能全部仅能显示默认.
![image](https://user-images.githubusercontent.com/13188169/86213245-fc01ce80-bbab-11ea-9107-127e7fefb072.png)

**Comment by kushao** [comment]
我刚才也发现这个问题了

**Comment by joesdu** [comment]
> 我刚才也发现这个问题了

难受.只有等官方修复了.

**Comment by joesdu** [comment]
> 我刚才也发现这个问题了

目前可以这么写来渲染,我看了下源码,是由于Umi的插件更新了,pro那边的props还没改.
```typescript
export const layout = ({ initialState }: { initialState: { settings?: LayoutSettings } }): BasicLayoutProps => ({
  logo,
  siderWidth: 220,
  // @ts-ignore
  rightRender: () => <RightContent />,
  disableContentMargin: false,
  disableMobile: true,
  menuHeaderRender: undefined,
  ...initialState?.settings
});
```

![image](https://user-images.githubusercontent.com/13188169/86223260-e4314700-bbb9-11ea-92c8-d8c13ec337ca.png)
