### ISSUE TITLE
🧐[问题] 用户不登陆也可以访问页面

### ISSUE THREAD

**Issue by mk-qi** [ant-design/ant-design-pro#6909]
### 🧐 问题描述

直接通过npm create umi  建的项目,在用用户没有登陆的情况下, 发现通过带有link页面可以直接访问应该需要用户登陆才能访问的页面,如下 随便点一个菜单都可以访问,但是刷新后就会跳入登陆页面.  不确定是问题或还是需在修改哪里?

<img width="1793" alt="Screen Shot 2020-07-02 at 12 59 05 AM" src="https://user-images.githubusercontent.com/642228/86271391-5f691c00-bbff-11ea-81c8-2f28d267ed86.png">

**Comment by chenshuai2144** [comment]
我们的鉴权只发生在 login 接口，一般接入真正得很后端之后鉴权会发生在任何接口。

如果接口返回 401 就会报错，可以试试 v5，里面有一个真实的 mock
