### ISSUE TITLE
E2E测试时electron依赖报错

### ISSUE THREAD

**Issue by miccuci** [ant-design/ant-design-pro#691]
执行e2e测试时，提示： Electron failed to install correctly, please delete node_modules/electron and try installing again   本地安装了electron1.7.10的版本，但是nightmare里依赖的是1.4.4的版本，然后我切换成1.4.4的版本依旧报错

**Comment by chenshuai2144** [comment]
electron这货经常安装失败。。。 你百度一下有教程帮你

**Comment by afc163** [comment]
用 cnpm 可以解决网络问题。
