### ISSUE TITLE
请问回调请求如何实现局部刷新?

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#6910]
比如我使用支付宝第三方验证登录,登录接口会给个回调页面,当支付宝完成验证后会重定向这个回调页面导致我的antdpro整个页面刷新了,请问如何拦截重定向页面来实现局部刷新呢

**Comment by chenshuai2144** [comment]
额 这种第三方登录没办法的，除非用 iframe 嵌套一下，推荐使用 sdk 这样就不用跳页什么的，更加方便

**Comment by laolaolulu** [comment]
> 

iframe设备了,百度了下什么CSP玩意的搞不懂;
