### ISSUE TITLE
🧐[问题]请教一下，能用代码的方式触发proTable的查询按钮吗？

### ISSUE THREAD

**Issue by panxingxiang** [ant-design/ant-design-pro#6911]
### 💻 示例代码
`
const [form] = Form.useForm();
const formProps = {
    form: form,
    layout: 'vertical'
  }

<ProTable<any>
        forceRender
        headerTitle="礼物订单"
        params={{
          sorter,
        }}
        request={(params) => getOrders(params)}
        columns={columns}
        form={formProps}
      />
`

**Comment by chenshuai2144** [comment]
```
const ref = useRef();
ref.current.submit();


formRef={ref}

```

https://protable.ant.design/example#form-%E6%93%8D%E4%BD%9C

**Comment by panxingxiang** [comment]
thanks @chenshuai2144
