### ISSUE TITLE
🐛[v5 BUG] 没有适配ant-design-pro-layout v6的新api

### ISSUE THREAD

**Issue by mjkohoh** [ant-design/ant-design-pro#6912]
### 🐛 bug 描述

ant-design-pro-layout v6版本去除了`rightContentRender`prop，新增了`headerContentRender`prop。但是在ant-design-pro v5中并没有适配该api，导致header不能正常显示。

### 💻 问题代码

当前v5中`app.tsx`中存在问题的代码，其依旧在使用`rightContentRender`，而不是`headerContentRender`
```
export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings };
}): BasicLayoutProps => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};
```

### © 版本信息

- Ant Design Pro 版本: v5

**Comment by chenshuai2144** [comment]
是个bug，rightContentRender 没有被删除，你可以重新安装一下依赖，就会生效了
