### ISSUE TITLE
Custom form elements width

### ISSUE THREAD

**Issue by avalladaresm** [ant-design/ant-design-pro#6915]
### 🧐 问题描述

Is there a way to set custom placement and width to an input in a modal with a form? On the file /src/pages/ListTableList/index.tsx there's this piece of code that renders the columns of the table as a form, but it renders them as inputs that take the whole modal width.
![Screenshot from 2020-07-02 11-25-03](https://user-images.githubusercontent.com/4381970/86391237-b1895c00-bc56-11ea-998f-bf9e024b6789.png)
I'd like to change that to make it look a bit more responsive as if I were using `<Row gutter={16}> <Col span={6}> </ Row>` for example. Is there any way to achieve that?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-table/blob/ebe12af8738d45429414689aaad98539afddcedf/src/Form/index.tsx#L62

i need more doc， can you help me？

**Comment by avalladaresm** [comment]
Hey, so I searched a bit further trying to solve it and found there's a `form` prop on the ProTable component that takes an 'antd form configuration' and its type is FormProps ([table api](https://protable.ant.design/api#table)). Now, by looking at the Form API on the [ant.design](https://ant.design/components/form/#Form) site, you can create a `formLayout` object with whatever form configuration you want, but the thing is, that applies to the form as a whole, not to each individual `Form.Item`, and what I want is to have to inputs side-by-side, inline-styled, see first screenshot, I did that with `<Row>` and `<Col>` in another project, but the way it's coded right now through ProTable, it appears as if each `Form.Item` has a fixed width (see second screenshot) depending on the `wrapperCol` prop. I can't figure out a way to have a different style for each separate row so it could look like the first screenshot because right here, I'm dealing with the form through the ProTable component, not through the Form component directly, so, this is what I came up with and the result is the second screenshot:

```
const formItemLayout = {
  labelCol: {
    xs: { span: 4},
  },
  wrapperCol:{
    xs: { span: 4},
  }
};


```
```
<Modal  
  destroyOnClose
  title="New User"
  style={{ top: 20 }}
  width={window.innerWidth > 576 ? '50%':''}
  visible={createModalVisible}
  onCancel={() => handleModalVisible(false)}
  footer={null}
>
  <ProTable<UsersListItem, UsersListItem>
    onSubmit={async (value) => {
      const success = await handleAdd(value);
      if (success) {
        handleModalVisible(false);
        if (actionRef.current) {
          actionRef.current.reload();
        }
      }
    }}
    rowKey="key"
    type="form"
    form={formLayout}
    columns={columns}
    rowSelection={{}}
  />
</Modal>
```

![Screenshot from 2020-07-02 21-37-18](https://user-images.githubusercontent.com/4381970/86429277-54b89080-bcac-11ea-8d39-fa767f85ee1e.png)

![Screenshot from 2020-07-02 21-41-00](https://user-images.githubusercontent.com/4381970/86429445-bed13580-bcac-11ea-8071-0521577c70c8.png)

If you have any tips it would be greatly appreciated!

**Comment by chenshuai2144** [comment]
We can't support it now, but we are developing, you can follow this repo 

https://github.com/ant-design/pro-components/issues
