### ISSUE TITLE
🧐[问题] What does `Routes: ['src/pages/Authorized']` do in config.ts?

### ISSUE THREAD

**Issue by IronSean** [ant-design/ant-design-pro#6916]
### 🧐 Problem description

I am trying to configure my site so that pages don't load if a user is not logged in. I can add this check manually to BasicLayout by injecting the user state from redux, but src/Pages/Authorized.tsx appears to already do this. 

But my problem is that it doesn't seem to be running any checks. Adding `console.log` calls to that file show shows it's not even rendering, and I can't find it in my render tree with react dev tools. It's listed in condig.ts as a property called `Routes` which is different than the `routes` used to define other routes.

Is there any docs on this capital R `Routes`? How is it supposed to work, is it supposed to work like a layout file where it wraps everything or renders first?

### 💻 Sample code

from config.ts

```javascript
routes: [
    {
      path: '/',
      component: '../layouts/BlankLayout',
      routes: [
        {
          path: '/user',
          component: '../layouts/UserLayout',
          routes: [
            {
              path: '/user',
              redirect: '/user/login',
            },
            {
              name: 'login',
              icon: 'smile',
              path: '/user/login',
              component: './user/login',
            },
            {
              name: 'register-result',
              icon: 'smile',
              path: '/user/register-result',
              component: './user/register-result',
            },
            {
              name: 'register',
              icon: 'smile',
              path: '/user/register',
              component: './user/register',
            },
            {
              component: '404',
            },
          ],
        },
        {
          path: '/',
          component: '../layouts/BasicLayout',
          Routes: ['src/pages/Authorized'],  // <== this line here.
          authority: ['admin'],
          routes: [
            {
              path: '/dashboard',
              hideInMenu: true,
              name: 'dashboard',
              icon: 'dashboard',
              routes: [
                {
                  name: 'analysis',
                  icon: 'smile',
                  path: '/dashboard/analysis',
                  component: './dashboard/analysis',
                },
                {
                  name: 'monitor',
                  icon: 'smile',
                  path: '/dashboard/monitor',
                  component: './dashboard/monitor',
                },
                {
                  name: 'workplace',
                  icon: 'smile',
                  path: '/dashboard/workplace',
                  component: './dashboard/workplace',
                },
              ],
            },
   ...
```

**Comment by IronSean** [comment]
I did get it working by changing it to look more like the layout in this repo:

```javascript
  routes: [
    {
      path: '/',
      component: '../layouts/BlankLayout',
      routes: [
        {
          path: '/user',
          component: '../layouts/UserLayout',
          routes: [
            {
              path: '/user',
              redirect: '/user/login',
            },
            {
              name: 'login',
              icon: 'smile',
              path: '/user/login',
              component: './user/login',
            },
            {
              name: 'register-result',
              icon: 'smile',
              path: '/user/register-result',
              component: './user/register-result',
            },
            {
              name: 'register',
              icon: 'smile',
              path: '/user/register',
              component: './user/register',
            },
            {
              component: '404',
            },
          ],
        },
        {
          path: '/',
          component: '../layouts/SecurityLayout',
          routes: [
            {
              path: '/',
              component: '../layouts/BasicLayout',
              Routes: ['src/pages/Authorized'],
              authority: ['admin'],
              routes: [
                {
                  path: '/dashboard',
                  hideInMenu: true,
                  name: 'dashboard',
                  icon: 'dashboard',
                  routes: [
                    {
                      name: 'analysis',
                      icon: 'smile',
                      path: '/dashboard/analysis',
                      component: './dashboard/analysis',
                    },
...
```

But the question remains why is that `Routes: ['src/pages/Authorized']` in the ant design pro template? does it do anything? If it does, why isn't it documented? And if not, can we remove it?

**Comment by huntdream** [comment]
Have you read this? [Authority Management](https://pro.ant.design/docs/authority-management#menu-and-router-permission)
I think it's documented here

**Comment by IronSean** [comment]
Hi @huntdream , it is not documented in there. Those pages refer to the `routes` attributes where you can define additional routes and sub-routes, and the authority for each, but not the `Routes` attribute which is being passed the `Authorized.ts` page. Note that one is `r` and the other is `R`. 

It is mentioned briefly [here](https://pro.ant.design/docs/faq#how-to-close-page-permission-control), but just saying you can remove it to disable it. But if my testing it didn't work anyway.

**Comment by huntdream** [comment]
@IronSean Sorry, the docs I read is Chinese version, the link I referred above is English version which is out of date.
The `Routes` attribute refers a component which is used to wrap the route component, it will perform permission check internally
(You can try to read the docs in Chinese and translate it by Google Translate)

**Comment by supermqB** [comment]
Ironsean提的这个问题，老实讲文档里也没说。就讲被Authorized包裹。而且也没找到这个文件‘src/pages/Authorized’。这个大写R开头Routes到底是干什么的？有没有人来给入门者解释一下。多谢。
