### ISSUE TITLE
🧐[问题] defaultItemRender 为什么使用 <a> 标签而不是使用 <link>

### ISSUE THREAD

**Issue by youshao** [ant-design/ant-design-pro#6918]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/11664572/86425558-15278e00-bd18-11ea-8a5b-7c607dcc6441.png)

问题迁移到：https://github.com/ant-design/ant-design-pro-layout/issues/531#issue-650308313

**Comment by chenshuai2144** [comment]
Link 要依赖别的包，我们希望 layout 要纯粹一些

**Comment by youshao** [comment]
> Link 要依赖别的包，我们希望 layout 要纯粹一些

那 hash 模式时，如何配置才能确保面包屑中的路由跳转正常？

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro-layout/issues/531
