### ISSUE TITLE
关于权限问题

### ISSUE THREAD

**Issue by Colinlyj210** [ant-design/ant-design-pro#692]
后端通常会返回一个 权限列表（数组），然后前端可以根据menu中的auth是否在该数组中进行判断，能否提供这样的一个方法？目前的这套只能在menu的auth中写数组，currentAuth写字符串不够灵活

**Comment by chenshuai2144** [comment]
currentAuth 和 authority 都是数组应该怎么比较？
子集？

**Comment by Colinlyj210** [comment]
这就需要规定好，如果currentAuth是数组的话authority不能是数组，只能是字符串

**Comment by chenshuai2144** [comment]
这就有点更麻烦了。。。。。
你还是传入function来的实惠。

**Comment by Colinlyj210** [comment]
框架里面哪个地方有？文档太简单，看不懂。如果function可以获取到menu的的authority那么也就没区别了

**Comment by chenshuai2144** [comment]
你说的对。我应该把menu的authority注入到方法中。

**Comment by Colinlyj210** [comment]
好的，期待ing...

**Comment by iT-lijun** [comment]
- @Colinlyj210 建议提的很awesomes !   
- 这种 authority={['admin', 'user']} 确实不该写死！ 
- 建议**menu**数据和**authority**数据都由**mock**返回更好！

**Comment by chenshuai2144** [comment]
下一阶段都会做的。。
这样就能动态修改权限了

**Comment by Colinlyj210** [comment]
@iT-lijun 如果menu都由后端返回的话会很麻烦，所以一般都是后端返回权限，前端进行控制展示

**Comment by chenshuai2144** [comment]
如果后端需要完全控制。推荐直接返回整个meun.js

**Comment by lanke** [comment]
currentAuth 如果能支持数组的话，前端配置authority可以配置成每个路由一个authority（不配置成角色名，配置当前路由所需要的权限），这样的话，后端就能完全的控制前端的权限了。不用修改前端代码，就能动态修改前端路由的权限

**Comment by chenshuai2144** [comment]
可以给个伪代码示例吗

**Comment by lanke** [comment]
![image](https://user-images.githubusercontent.com/1082843/34987620-bdda6ffe-faf6-11e7-9e0b-d99e0e35c674.png)
前端配置的时候就这样配置，后端返回的时候，返回用户拥有的权限的数组。

**Comment by Colinlyj210** [comment]
就是这样，因为菜单兰肯定是固定的，而用户是可变的，所以就是需要和现在框架里面写的反一下。

**Comment by chenshuai2144** [comment]
这个好像更自由一点！复杂的怎么搞？

**Comment by longzhaobi** [comment]
对于权限控制这一块我一直是这么做的：
1.用户登录时或者刷新浏览器时，会请求该用户最新的权限信息并返回前端保存到localStrorage里，返回格式如下：
```
["user:create", "user:view", "usesr:update", "user:remove", "role:view"]等
```
2.进入系统首页加载菜单时，程序会循环组装菜单，在循环里加上如下代码一一判断：
在common的menu.js里需要权限控制的菜单加上key，如：
```
 },{
    name: '用户管理',
    path: 'user',
    key:'user',
    icon:'user-add'
  },{
```
循环里加上判断：
```
//如果路由对象有name属性，则进行权限判断，否则放行
if(item.key) {
    if(!this.isAuth(item.key)) {
        return null;
     }
 }

isAuth = (perm) => {
      let flag = false;
      for (let p of this.permission) {
        if(p === perm + ':view') {
          flag = true;
          break;
        }
      }
      return flag;
    }
```
如果menu.js没有key，说明该菜单不需要权限。这样就实现菜单的控制了，如果后端权限改变了，用户只需刷新浏览器就会隐藏。


2.按钮的权限控制是我这样实现的。

新增一个组件，名叫IButton，接收一个props参数：perm，如果该按钮需要用户的新增权限才显示，如：
```
 <IButton type="primary" icon="plus" perm="user:create"> 新增 </IButton>
```
这个IButton里的逻辑判断如下：
```
isAuth = (perm) => {
    let flag = false;
    const cacheFlag = 'perm:' + perm;
   //如果已经缓存，则根据缓存判断
    const cacheAuth = localStorage.getItem(cacheFlag);
    if(cacheAuth === 'true') {
      return true;
    } else if(cacheAuth === 'false') {
      return false;
    }
    for (let i = 0; i < this.permission.length; i++) {
      if(this.permission[i] === perm) {
        flag = true;
        break;
      }
    }
    //本地缓存权限，这样就不用每次都去循环判断，刷新浏览器时，清空本地缓存
    localStorage.setItem(cacheFlag, flag)
    return flag;
  }
```
这样就可以实现按钮的控制了。

**Comment by chenshuai2144** [comment]
你这个没有解耦。前端后端还是需要配合

**Comment by longzhaobi** [comment]
嗯，但这个实际情况感觉也不麻烦。

**Comment by chengnuo** [comment]
@lanke 我也是这种思路，你们有实现了demo我们可以参考的吗？

**Comment by zjscy666** [comment]
建议权限那块最好是可以人为设置，用户随便设置那种

**Comment by PuShaoWei** [comment]
因为我是服务端开发，所以我写了两套路由。。将当前所有服务端返回路由存入`localStrong`，然后根据当前路由地址做决断，有放行，没有报403

**Comment by PuShaoWei** [comment]
然后我写了一个本地遍历目录的脚本，权限添加时分清该路由属于`菜单`还是`action`，分为两栏
