### ISSUE TITLE
🐛[BUG][v5] Cannot find module 'node-libs-browser/mock/empty'

### ISSUE THREAD

**Issue by wuchaoya** [ant-design/ant-design-pro#6920]
### 🐛 bug 描述

执行 yarn start

出现 Cannot find module 'node-libs-browser/mock/empty'

### 📷 复现步骤

1. yarn create umi
2. 选择v5版本
3. yarn 
4. yarn start

Cannot find module 'node-libs-browser/mock/empty'

### 🏞 期望结果

正常启动

### © 版本信息

- Ant Design Pro 版本: [v5]
- umi 版本
- 浏览器环境
- 开发环境 [ mac OS]

**Comment by jlahtinen** [comment]
I have this same poblem. yarn cache is missing this file when this happens. removing cache fixes this for a while. no idea why this file is removed from cache and when
