### ISSUE TITLE
🧐[问题]why代码分支v5和v5.1

### ISSUE THREAD

**Issue by dsldata** [ant-design/ant-design-pro#6926]
### 🧐 问题描述

代码分支**v5**不是还完全未上麽，那**v5.1**又是一个什么样的存在？

难道是这样？
**v5: 混合过度期的产物
v5.1: 完全新版的产物**

**Comment by liujiayii** [comment]
目前版本感觉有点乱了……v4 v5 v5.1 还有对应antd4 antd3 umi2 umi3的版本 =.=

**Comment by chenshuai2144** [comment]
v5.1  是一个实验性质的，可以忽略掉
