### ISSUE TITLE
版本从5.0.8更新到6.1.0以后，从后端获取路由菜单，菜单不显示🐛[BUG]

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#6928]
### 🐛 bug 描述
我在5.0.8版本做从后端获取路由菜单的时候是没有问题的，当我把版本更新到了6.1.0，重新跑项目的时候，菜单不显示了

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
![image](https://user-images.githubusercontent.com/45235142/86466001-63af4980-bd65-11ea-8d31-83ac18a0e10b.png)

- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/45235142/86466106-a3763100-bd65-11ea-8e5b-8563bceefdc8.png)
![image](https://user-images.githubusercontent.com/45235142/86466120-abce6c00-bd65-11ea-9885-149b28c45bbe.png)
![image](https://user-images.githubusercontent.com/45235142/86466221-d4eefc80-bd65-11ea-9871-5a36e971f8c3.png)
![image](https://user-images.githubusercontent.com/45235142/86466463-4038ce80-bd66-11ea-9268-41f920db6584.png)

**Comment by LB-nan** [comment]
我也遇到这个问题了，我在重定向了一下路由就有了，你可以试试~~
我的版本是6.2.0
```js
*fetch(_, { call, put }) {
      const response = yield call(getMenus);
     // 这里，在请求完数据之后重新刷新了一下路由
      history.push('/');
      yield put({
        type: 'get',
        payload: response,
      });
    },
```

**Comment by Asence** [comment]
> 我也遇到这个问题了，我在重定向了一下路由就有了，你可以试试~~
> 我的版本是6.2.0
> 
> ```js
> *fetch(_, { call, put }) {
>       const response = yield call(getMenus);
>      // 这里，在请求完数据之后重新刷新了一下路由
>       history.push('/');
>       yield put({
>         type: 'get',
>         payload: response,
>       });
>     },
> ```



> 我也遇到这个问题了，我在重定向了一下路由就有了，你可以试试~~
> 我的版本是6.2.0
> 
> ```js
> * fetch （_ ， { call ， put } ） { 
>       const  response  =  yield  调用（getMenus ）; 
>      //这里，在请求完数据之后重新刷新一下一下路由
>       history 。推（'/' ）; 
>       yield  put （{ 
>         类型：'get' ，
>         有效载荷：响应，
>       } ）; 
>     } ，
> ```

这个问题已经修复了 更新一下版本到6.2.2
