### ISSUE TITLE
关于增加Tab导航标签问题

### ISSUE THREAD

**Issue by dabenlu803** [ant-design/ant-design-pro#693]
目前基于最新代码增加Tab导航标签，遇到react-router无法缓存页面，导致每次切换标签，页面都重新加载的问题。react-router本身无法支持页面缓存功能，React-Keeper可支持。Tab导航标签在后台管理系统中还是挺常见的，请问本框架是否有增加Tab导航标签的计划或是支持React-Keeper的计划？
![image](https://user-images.githubusercontent.com/6845677/34935491-0f831b14-fa19-11e7-9af5-a1972769f6c5.png)

**Comment by tianlinzx** [comment]
@dabenlu803 之前提过类似的需求，貌似被否了。

**Comment by pkaq** [comment]
#667 
#220

**Comment by chenshuai2144** [comment]
试着自己实现把 🙃

**Comment by longzhaobi** [comment]
我用antdesign提供的Tabs标签页也弄了个和你类似的功能，切换回来，只要数据请求放在commponentWillMount里不会重选渲染组件啊？我每个路由的组件都是放在TabPane 里的。

**Comment by guoxiangwen** [comment]
@dabenlu803 能看下你实现的代码吗？

**Comment by wyy19940829** [comment]
好想知道你怎么实现的哦  我现在就是要实现这个功能

**Comment by roc2539** [comment]
commponentWillMount  ?  主要是页面数据缓存。。这样，不会重新渲染组件？
