### ISSUE TITLE
🐛[BUG]The Form is reset When I dispatch in Form's onValuesChange(在表单onValuesChange里调用dispatch，会导致表单被清空)

### ISSUE THREAD

**Issue by yerphon** [ant-design/ant-design-pro#6931]
### 🐛 bug 描述

The Form is reset When I dispatch in Form's onValuesChange

### 📷 复现步骤
为Form组件添加onValuesChange函数
![image](https://user-images.githubusercontent.com/7892904/86476496-3d93a480-bd79-11ea-948e-ed3ce3591f25.png)
在onValuesChange函数里调用dispatch
![image](https://user-images.githubusercontent.com/7892904/86476509-41272b80-bd79-11ea-8ced-7a409db79326.png)

### 🏞 期望结果

The form should not be reset.
在onValuesChange函数里调用dispatch，Form表单不要被重置。

### 💻 复现代码

![image](https://user-images.githubusercontent.com/7892904/86476496-3d93a480-bd79-11ea-948e-ed3ce3591f25.png)
![image](https://user-images.githubusercontent.com/7892904/86476509-41272b80-bd79-11ea-8ced-7a409db79326.png)

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本 3.0.14
- 浏览器环境 chrome
- 开发环境 win10

**Comment by chenshuai2144** [comment]
没看懂，这个应该是 dispath 无关吧，是不是你出发了 form.reset
