### ISSUE TITLE
Which code to install to see the template exactly as https://preview.pro.ant.design/ 

### ISSUE THREAD

**Issue by pkdcryptos** [ant-design/ant-design-pro#6932]
Hi Experts,

Which code to install to see the template exactly as https://preview.pro.ant.design/ 

Thanks for any clues.

I installed v4 and v5 , none of them are equivalent to the display at https://preview.pro.ant.design

Pkd

**Comment by avalladaresm** [comment]
You could try `npm create umi`, then on ` Select the boilerplate type (Use arrow keys)` select ant-design-pro and on the next prompt you will see Pro V5 and Pro V4, select the Pro V4 option.

**Comment by pkdcryptos** [comment]
> You could try `npm create umi`, then on ` Select the boilerplate type (Use arrow keys)` select ant-design-pro and on the next prompt you will see Pro V5 and Pro V4, select the Pro V4 option.

No that does not help. Tried atleast 10's of links. There is no GitHub repo that is very equal to website display. It is only on owner's machine. There are some links explaining how to achieve the same display, but bot helpful.

**Comment by dsldata** [comment]
**Its really confusing a lot..**

**Comment by pkdcryptos** [comment]
If some experts help with repo equivalent to website display...that will be awesome and thousand thanks in advance

**Comment by marian2js** [comment]
To get the page deployed on https://preview.pro.ant.design run `npm run site && npm start` on the root of this repo.
