### ISSUE TITLE
🐛[BUG] yarn create umi my-app 报错

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6933]
### 🐛 bug 描述

选择  ant-design-pro 模板时报错

### 📷 复现步骤
```

PS D:\temp\my-app> yarn create umi my-app
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@umijs/create-umi-app > @umijs/utils > @babel/register@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi-serve > @babel/preset-typescript > @babel/plugin-transform-typescript@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi-serve > @babel/preset-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi-serve > @babel/register@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
warning "create-umi > sylvanas > @umijs/fabric > eslint-config-airbnb@17.1.1" has incorrect peer dependency "eslint-plugin-react@^7.14.2".
[4/4] Building fresh packages...
success Installed "create-umi@0.24.1" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
(node:52736) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\plugins.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\cli-engine.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\api.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\lib\eslintJs.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\lib\index.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\create-umi\lib\generators\ant-design-pro\index.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\create-umi\lib\run.js
- C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\create-umi\cli.js
Referenced from: C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\eslint-config-airbnb-typescript\index.js
Referenced from:
    at Function.Module._resolveFileyourname (internal/modules/cjs/loader.js:966:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Plugins.load (C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\plugins.js:165:21)
    at loadFromDisk (C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:529:35)
    at load (C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:587:20)
    at C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Users\yourname\AppData\Local\Yarn\Data\global\node_modules\sylvanas\node_modules\eslint\lib\config\config-file.js:431:26)
(node:52736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:52736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 57.48s.
```

**Comment by CuiFi** [comment]
win10同样的错误,mac上面就没有

**Comment by kaoding** [comment]
> win10同样的错误,mac上面就没有

是win10上报错误

**Comment by bluescurry** [comment]
我这mac也报错了。。。

**Comment by chenshuai2144** [comment]
刚刚试了一下没什么问题

**Comment by bluescurry** [comment]
> 刚刚试了一下没什么问题

我这是这个报错信息，有时间能否辛苦帮忙看一下是不是环境问题呢？
node 版本：12.16.3；npm 版本：6.14.4
```
npm create umi
? Select the boilerplate type ant-design-pro
(node:51519) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js
- /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config.js
- /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine.js
- /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/api.js
- /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/eslintJs.js
- /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/index.js
- /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js
- /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/run.js
- /Users/hanshuo/.config/yarn/global/node_modules/create-umi/cli.js
Referenced from: /Users/hanshuo/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
Referenced from:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at Plugins.load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:529:35)
    at load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:587:20)
    at /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:453:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:431:26)
(node:51519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:51519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bluescurry** [comment]
> > 刚刚试了一下没什么问题
> 
> 我这是这个报错信息，有时间能否辛苦帮忙看一下是不是环境问题呢？
> node 版本：12.16.3；npm 版本：6.14.4
> 
> ```
> npm create umi
> ? Select the boilerplate type ant-design-pro
> (node:51519) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
> Require stack:
> - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js
> - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config.js
> - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine.js
> - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/api.js
> - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/eslintJs.js
> - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/index.js
> - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js
> - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/run.js
> - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/cli.js
> Referenced from: /Users/hanshuo/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
> Referenced from:
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:83:19)
>     at Plugins.load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:104:29)
>     at Array.forEach (<anonymous>)
>     at Plugins.loadAll (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:165:21)
>     at loadFromDisk (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:529:35)
>     at load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:587:20)
>     at /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:453:36
>     at Array.reduceRight (<anonymous>)
>     at applyExtends (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:431:26)
> (node:51519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:51519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

问题解决了，我发现 yarn global 中有 `@umijs/create-umi-app` 和 `create-umi`，我将它们 remove 以后，再执行 `npm create umi` 就没问题了，不过我不太知道到底是什么问题导致，不过问题算是解决了

**Comment by kaoding** [comment]
> create-umi

我试了，这个方法不行。

**Comment by koupeng** [comment]
> > > 刚刚试了一下没什么问题
> > 
> > 
> > 我这是这个报错信息，有时间能否辛苦帮忙看一下是不是环境问题呢？
> > node 版本：12.16.3；npm 版本：6.14.4
> > ```
> > npm create umi
> > ? Select the boilerplate type ant-design-pro
> > (node:51519) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
> > Require stack:
> > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/api.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/eslintJs.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/index.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/run.js
> > - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/cli.js
> > Referenced from: /Users/hanshuo/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
> > Referenced from:
> >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
> >     at Function.resolve (internal/modules/cjs/helpers.js:83:19)
> >     at Plugins.load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:104:29)
> >     at Array.forEach (<anonymous>)
> >     at Plugins.loadAll (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:165:21)
> >     at loadFromDisk (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:529:35)
> >     at load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:587:20)
> >     at /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:453:36
> >     at Array.reduceRight (<anonymous>)
> >     at applyExtends (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:431:26)
> > (node:51519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> > (node:51519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ```
> 
> 问题解决了，我发现 yarn global 中有 `@umijs/create-umi-app` 和 `create-umi`，我将它们 remove 以后，再执行 `npm create umi` 就没问题了，不过我不太知道到底是什么问题导致，不过问题算是解决了

@chenshuai2144 我也是这样解决的，但是npm run lint会报错呢。怎么解决啊？
https://github.com/ant-design/ant-design-pro/issues/6938

**Comment by kaoding** [comment]
> > > > 刚刚试了一下没什么问题
> > > 
> > > 
> > > 我这是这个报错信息，有时间能否辛苦帮忙看一下是不是环境问题呢？
> > > node 版本：12.16.3；npm 版本：6.14.4
> > > ```
> > > npm create umi
> > > ? Select the boilerplate type ant-design-pro
> > > (node:51519) UnhandledPromiseRejectionWarning: Error: Failed to load plugin @typescript-eslint: Cannot find module '@typescript-eslint/eslint-plugin'
> > > Require stack:
> > > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/api.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/eslintJs.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/lib/index.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/generators/ant-design-pro/index.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/lib/run.js
> > > - /Users/hanshuo/.config/yarn/global/node_modules/create-umi/cli.js
> > > Referenced from: /Users/hanshuo/.config/yarn/global/node_modules/eslint-config-airbnb-typescript/index.js
> > > Referenced from:
> > >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
> > >     at Function.resolve (internal/modules/cjs/helpers.js:83:19)
> > >     at Plugins.load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:104:29)
> > >     at Array.forEach (<anonymous>)
> > >     at Plugins.loadAll (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/plugins.js:165:21)
> > >     at loadFromDisk (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:529:35)
> > >     at load (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:587:20)
> > >     at /Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:453:36
> > >     at Array.reduceRight (<anonymous>)
> > >     at applyExtends (/Users/hanshuo/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/config/config-file.js:431:26)
> > > (node:51519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> > > (node:51519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > ```
> > 
> > 
> > 问题解决了，我发现 yarn global 中有 `@umijs/create-umi-app` 和 `create-umi`，我将它们 remove 以后，再执行 `npm create umi` 就没问题了，不过我不太知道到底是什么问题导致，不过问题算是解决了
> 
> @chenshuai2144 我也是这样解决的，但是npm run lint会报错呢。怎么解决啊？
> #6938

这种解决方法应该不是正道。

**Comment by kaoding** [comment]
问题解决了，我发现 yarn global 中有 @umijs/create-umi-app 和 create-umi，我将它们 remove 以后，再执行 npm create umi 就没问题了，不过我不太知道到底是什么问题导致，不过问题算是解决了

只要 yarn global remove create-umi 后，执行 npm create umi 是可以的，但执行 yarn create umi 还是不行（同时再次安装 create-umi），再执行  npm create umi 又不行了，可能是依赖冲突问题。

**Comment by kaoding** [comment]
https://github.com/umijs/umi/issues/4993

**Comment by gwuah** [comment]
If you're on a mac, checkout into this directory `/Users/[your_user_name]/.config/yarn/global`
and then run `yarn global remove create-umi. Also remove and every other package with the name "umi" in it.
After run a clean install of `npm create umi myApp`

That should work for you.

**Comment by kaoding** [comment]
在windows 上问题解决了， 在 windows 上 C:\Users\[your_user_name]\AppData\Local\Yarn\Data\global\package.json 看一下全局安装的 package，一般是因局安装的 package有冲突，yarn global remove create-umi 和 相关的 package（不一定是umi相关的包冲突，要自己试），就可以了。
