### ISSUE TITLE
🧐[问题] DatePicker 组件国际化问题

### ISSUE THREAD

**Issue by ChenWeihua123** [ant-design/ant-design-pro#6934]
### 🧐 问题描述

求大佬帮下忙 谢谢了！！
请问为什么会这样。。中英文混搭

期望结果：我希望全部都是中文的

### 🚑 其他信息

![timer](https://user-images.githubusercontent.com/33150900/86504125-a3b71080-bde7-11ea-8de8-c07919bce5fe.png)

![微信截图_20200704111953](https://user-images.githubusercontent.com/33150900/86504200-4c657000-bde8-11ea-9887-5dcf17958349.png)

![code](https://user-images.githubusercontent.com/33150900/86504128-a6b20100-bde7-11ea-8ed7-98c60e161b38.png)

**Comment by ChenWeihua123** [comment]
antd的版本 4.3.5， pro-table 2.4.0 显示正常

目前这个问题的 antd版本是 4.4.0 pro-table 是 2.4.1 

我也不确定是不是这antd 或者 pro-table 的问题

**Comment by joesdu** [comment]
去掉自己项目中引入的moment试试

**Comment by chenshuai2144** [comment]
楼上正解

**Comment by ChenWeihua123** [comment]
谢谢各位了🙏
