### ISSUE TITLE
🧐[问题]跳转路由同时改变redux store上的router，有什么办法

### ISSUE THREAD

**Issue by 363676727** [ant-design/ant-design-pro#6936]
### 🧐 问题描述

之前版本的路由跳转
router.push('/foo'); -> 会改变redux store上的router
history.push('/foo'); -> 却不会改变redux store上的router
### 💻 示例代码
官方pro项目起来后，切换menu，或者利用history进行跳转

### 🚑 其他信息
虽然我知道history这个实例里location这些有所变化,但是我期望的是redux store上的router有同步,
这个变化umi3文档里似乎没有提及，目前想要跳转路由同时改变redux store上的router，有什么办法

**Comment by ycjcl868** [comment]
试下 `withRouter`，然后取 `history` 对象

**Comment by 363676727** [comment]
> 试下 `withRouter`，然后取 `history` 对象

withRouter 利用上下文传递 router 参数，这个我明白，可能是我的问题没描述清楚。
我的目的是是希望，history.push('/xxx')的时候，同步更新redux store上的router这个对象, 因为之前版本的pro就是这么做的。
目前我准备从redux的router中间件入手，查看antd pro是用什么router中间件的npm包, 查询同步api。
3q for your answer
