### ISSUE TITLE
🧐[问题]线上的service-worker.js有更新，浏览器会立即感知它的改变并触发sw.updated事件吗

### ISSUE THREAD

**Issue by UNDERCOVERj** [ant-design/ant-design-pro#6937]
我尝试更新了service-worker.js，但是只有手动刷新页面，才能触发sw.updated。

**Comment by chenshuai2144** [comment]
pwa 就是这样的逻辑吧。

https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps/Re-engageable_Notifications_Push

看看这里

**Comment by UNDERCOVERj** [comment]
> pwa 就是这样的逻辑吧。
> 
> https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps/Re-engageable_Notifications_Push
> 
> 看看这里

贴的链接是消息推送，不是 service-worker 更新

**Comment by chenshuai2144** [comment]
service-worker 更新是一种是特殊的消息，效果是一样的

**Comment by UNDERCOVERj** [comment]
> service-worker 更新是一种是特殊的消息，效果是一样的

可以告诉我细节是怎么做的吗

**Comment by UNDERCOVERj** [comment]
> service-worker 更新是一种是特殊的消息，效果是一样的

我试验了，在前端代码更新后 ，上线了，需要新开个tab输入url进入页面，原有的tab才能感知到service-worker的更新。你说的特殊的消息是需要额外的配置吗

**Comment by chenshuai2144** [comment]
一般 pwa  都是需要第二次的，你的功能可能实现不了
