### ISSUE TITLE
🧐[问题]npm run lint 报无法解析tsconfig.json

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#6938]
### 🧐 问题描述

```
 src\components\Authorized\Authorized.jsx
  ×  Parsing error: Cannot read file f:\dingplatform\antdp_base\tsconfig.json.

  src\components\Authorized\AuthorizedRoute.jsx
  ×  Parsing error: Cannot read file f:\dingplatform\antdp_base\tsconfig.json.

  src\components\Authorized\CheckPermissions.jsx
  ×  Parsing error: Cannot read file f:\dingplatform\antdp_base\tsconfig.json.

  src\components\Authorized\PromiseRender.jsx
  ×  Parsing error: Cannot read file f:\dingplatform\antdp_base\tsconfig.json.

  src\components\Authorized\Secured.jsx
  ×  Parsing error: Cannot read file f:\dingplatform\antdp_base\tsconfig.json.

```

**Comment by chenshuai2144** [comment]
你没有配置tsconfig 吗?

**Comment by koupeng** [comment]
@chenshuai2144 没有额外配置。怎么配置？我就是按照官网。npm create umi-->ant design pro-->ant4-->JavaScript操作的。我用的是JS版本

**Comment by koupeng** [comment]
@chenshuai2144 刚开始npm create umi 一直报错。我执行了yarn global remove create-umi yarn global remove prisma
是不是和这个有关？
https://github.com/ant-design/ant-design-pro/issues/6787

**Comment by kaoding** [comment]
yarn create umi 或 npm create umi 选择 ant-design-pro 就报错
https://github.com/ant-design/ant-design-pro/issues/6933

**Comment by chenshuai2144** [comment]
close by https://github.com/umijs/fabric/pull/51

**Comment by chenshuai2144** [comment]
> @chenshuai2144 刚开始npm create umi 一直报错。我执行了yarn global remove create-umi yarn global remove prisma
是不是和这个有关？

你的十有八九是这个问题

**Comment by koupeng** [comment]
> > @chenshuai2144 刚开始npm create umi 一直报错。我执行了yarn global remove create-umi yarn global remove prisma
> > 是不是和这个有关？
> 
> 你的十有八九是这个问题

怎样解决？
