### ISSUE TITLE
🧐[问题]权限控制相关问题

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/ant-design-pro#6939]
### 🧐 问题描述

角色的权限控制，可以在菜单里配置。如果在登陆完成以后，进入首页或者其他页面时，需要再进行一次判断，判断用户是否激活。（通过登陆完成后的用户接口来获取到一个字段：active是否激活）。如果未激活都显示未激活的页面，已激活显示相应页面。

想请问一下，该怎么做

**Comment by kaoding** [comment]
https://umijs.org/zh-CN/plugins/plugin-access#children
https://beta-pro.ant.design/docs/authority-management-cn#%E9%A1%B5%E9%9D%A2%E5%86%85%E7%9A%84%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6
