### ISSUE TITLE
npm run build 没有dist 目录生成

### ISSUE THREAD

**Issue by cuihairu** [ant-design/ant-design-pro#694]
>在mac 环境下运行npm run build 有dist目录，但在centos7.4 下没有dist目录生成，也没有报错

> pro 1.0.1

>mac  成功
npm 5.6.0
node v8.9.3

> centos7.x 失败
npm 3.10.10
node v6.12.2

> centos7.x 失败
npm 5.3.0
node v8.6.0

> centos7.x 失败
npm 5.6.0
node v8.9.4

> fedora 27 成功
npm 5.5.1
node v8.9.3

---重新安装centos系统居然可以了，这个应该是我个人的环境问题。

反复测试验证之后发现开始使用的测试服内存只有1G就会出现这类情况，使用超过1G内存的机子就没有这类问题。

**Comment by soolx** [comment]
node版本太低了，好像要增加babel的额外插件，不方便升级版本的话，可以build之后直接过去运行啊
