### ISSUE TITLE
👑 [需求]新的Layout 无法在最外层添加相关代码，上一个版本是支持的

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#6940]
### 🥰 需求描述
上个版本可以这样实现，这个版本用app.tsx无法实现了,希望开放函数渲染。上个版本如下图实现

![image](https://user-images.githubusercontent.com/33716687/86528005-de4ba680-bed6-11ea-998d-f255631ef703.png)

**Comment by chenshuai2144** [comment]
为什么会有这样的需求呢？

**Comment by XSmarter** [comment]
@chenshuai2144 我们菜单实在太多了，layout: 'top' 放不开，并且我们在最上面放的都是些辅助性的菜单功能，所以就出现这个需求了。能不能加个属性可以在layout外面添加一些组件代码？

**Comment by XSmarter** [comment]
这个问题解决我们项目基本就可以升级到新的layout了

**Comment by chenshuai2144** [comment]
@XSmarter  试试我们新的特性

https://preview.pro.ant.design/dashboard/analysis?navTheme=light&layout=mix&splitMenus=true

**Comment by XSmarter** [comment]
@chenshuai2144 这个新特性没法满足我们的需求呢，我们是想在外面可以定义一个组件放到头部做一些辅助菜单。我们是工具类软件所以辅助菜单多一些

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/docs/routing#wrappers

试试这个
