### ISSUE TITLE
🐛[BUG] 请求出现400错误 进入errorHandler后为啥还会进入到then

### ISSUE THREAD

**Issue by yangdachu** [ant-design/ant-design-pro#6943]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/23580181/86560778-b8370c80-bf91-11ea-9e40-2afe15e59d19.png)
![image](https://user-images.githubusercontent.com/23580181/86560797-c422ce80-bf91-11ea-9d35-80d30c0cb0a2.png)

### 📷 复现步骤

发送请求

### 🏞 期望结果

不进入then

### 💻 复现代码

` useEffect(() => {
    queryRule().then(res => {
      debugger
    });
  }, []);`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
我应该也遇到这些问题.请求发生错误后,没有进入catch中.

**Comment by yangdachu** [comment]
> 我应该也遇到这些问题.请求发生错误后,没有进入catch中.

是的 只会进入then

**Comment by joesdu** [comment]
> > 我应该也遇到这些问题.请求发生错误后,没有进入catch中.
> 
> 是的， 只会进入then。我觉得既然 errorHandler都处理了，就不应该在进入then或者catch了吧？

这个errorHandler官方好像写的是,只是做个提示,不会处理数据,所以数据还是会返回回去.但是我觉得至少应该进入catch.

**Comment by yangdachu** [comment]
> > > 我应该也遇到这些问题.请求发生错误后,没有进入catch中.
> > 
> > 
> > 是的， 只会进入then。我觉得既然 errorHandler都处理了，就不应该在进入then或者catch了吧？
> 
> 这个errorHandler官方好像写的是,只是做个提示,不会处理数据,所以数据还是会返回回去.但是我觉得至少应该进入catch.

那你现在是怎么处理的，每个then里在加个判断吗？

**Comment by joesdu** [comment]
> > > > 我应该也遇到这些问题.请求发生错误后,没有进入catch中.
> > > 
> > > 
> > > 是的， 只会进入then。我觉得既然 errorHandler都处理了，就不应该在进入then或者catch了吧？
> > 
> > 
> > 这个errorHandler官方好像写的是,只是做个提示,不会处理数据,所以数据还是会返回回去.但是我觉得至少应该进入catch.
> 
> 那你现在是怎么处理的，每个then里在加个判断吗？

对,then里边也做了判断,也写了catch.就像这样.
![image](https://user-images.githubusercontent.com/13188169/86571389-e45b8900-bfa3-11ea-8b43-2583309395a6.png)

**Comment by yangdachu** [comment]
> > > > > 我应该也遇到这些问题.请求发生错误后,没有进入catch中.
> > > > 
> > > > 
> > > > 是的， 只会进入then。我觉得既然 errorHandler都处理了，就不应该在进入then或者catch了吧？
> > > 
> > > 
> > > 这个errorHandler官方好像写的是,只是做个提示,不会处理数据,所以数据还是会返回回去.但是我觉得至少应该进入catch.
> > 
> > 
> > 那你现在是怎么处理的，每个then里在加个判断吗？
> 
> 对,then里边也做了判断,也写了catch.就像这样.
> ![image](https://user-images.githubusercontent.com/13188169/86571389-e45b8900-bfa3-11ea-8b43-2583309395a6.png)

目前看来也只能先这么处理一下了

**Comment by yangdachu** [comment]
希望官方的小伙伴回复一下有没有解决的办法，谢谢

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/86598581-e6d3d800-bfcf-11ea-8ca8-1e3200df1a57.png)
现在 v5 版本中做了异常处理程序，但是没有“吃掉”异常（只是做了一些提示notification.error），会继续抛出异常（如上图），可以在自己的网络请求使用` try { } catch(error e ) { }`

**Comment by crashsol** [comment]
有没有办法通过一个统一的方法，来处理调异常呢？

**Comment by yangdachu** [comment]
> 有没有办法通过一个统一的方法，来处理调异常呢？

暂时没有吧 问题被 @kaoding 关闭了

**Comment by crashsol** [comment]
> > 有没有办法通过一个统一的方法，来处理调异常呢？
> 
> 暂时没有吧 问题被 @kaoding 关闭了

主要每个调用方法都去写一个try catch ，还是很不科学啊，现在都是直接用httpStatueCode来判断api是否调用成功，是否可以通过umi-request的中间件来处理呢？

**Comment by kaoding** [comment]
> > > 有没有办法通过一个统一的方法，来处理调异常呢？
> > 
> > 
> > 暂时没有吧 问题被 @kaoding 关闭了
> 
> 主要每个调用方法都去写一个try catch ，还是很不科学啊，现在都是直接用httpStatueCode来判断api是否调用成功，是否可以通过umi-request的中间件来处理呢？

“异常处理程序”就是统一的方法，你可以根据自己需要在“异常处理程序”进行统一异常处理的。你不要抛出 throw error（吃掉异常），后面就不用写 try catch了，但这种写法要进行统一的后台接口定义，根据业务返回结果做处理。

**Comment by yangdachu** [comment]
> > > > 有没有办法通过一个统一的方法，来处理调异常呢？
> > > 
> > > 
> > > 暂时没有吧 问题被 @kaoding 关闭了
> > 
> > 
> > 主要每个调用方法都去写一个try catch ，还是很不科学啊，现在都是直接用httpStatueCode来判断api是否调用成功，是否可以通过umi-request的中间件来处理呢？
> 
> “异常处理程序”就是统一的方法，你可以根据自己需要在“异常处理程序”进行统一异常处理的。你不要抛出 throw error（吃掉异常），后面就不用写 try catch了，但这种写法要进行统一的后台接口定义，根据业务返回结果做处理。

不是很理解你说的，能上个代码说明一下吗？我不管怎么搞都会进then啊，这个和v4 v5没关系吧

**Comment by kaoding** [comment]
> > > > > 有没有办法通过一个统一的方法，来处理调异常呢？
> > > > 
> > > > 
> > > > 暂时没有吧 问题被 @kaoding 关闭了
> > > 
> > > 
> > > 主要每个调用方法都去写一个try catch ，还是很不科学啊，现在都是直接用httpStatueCode来判断api是否调用成功，是否可以通过umi-request的中间件来处理呢？
> > 
> > 
> > “异常处理程序”就是统一的方法，你可以根据自己需要在“异常处理程序”进行统一异常处理的。你不要抛出 throw error（吃掉异常），后面就不用写 try catch了，但这种写法要进行统一的后台接口定义，根据业务返回结果做处理。
> 
> 不是很理解你说的，能上个代码说明一下吗？我不管怎么搞都会进then啊，这个和v4 v5没关系吧

可能是你对 promise 用法不是太熟悉引起的这些问题（不好意思，我猜的）。

**Comment by yangdachu** [comment]
> > > > > > 有没有办法通过一个统一的方法，来处理调异常呢？
> > > > > 
> > > > > 
> > > > > 暂时没有吧 问题被 @kaoding 关闭了
> > > > 
> > > > 
> > > > 主要每个调用方法都去写一个try catch ，还是很不科学啊，现在都是直接用httpStatueCode来判断api是否调用成功，是否可以通过umi-request的中间件来处理呢？
> > > 
> > > 
> > > “异常处理程序”就是统一的方法，你可以根据自己需要在“异常处理程序”进行统一异常处理的。你不要抛出 throw error（吃掉异常），后面就不用写 try catch了，但这种写法要进行统一的后台接口定义，根据业务返回结果做处理。
> > 
> > 
> > 不是很理解你说的，能上个代码说明一下吗？我不管怎么搞都会进then啊，这个和v4 v5没关系吧
> 
> 可能是你对 promise 用法不是太熟悉引起的这些问题（不好意思，我猜的）。

我最开始的问题是进入errorHandler了就没有必要在进入到then里去了，你们估计也是这么设计的，绕来绕去问题还是没有解决。。。

**Comment by kaoding** [comment]
一般设计不用到then里，如果抛异常，通过try catch 捕获，通过 async await 里拿返回值。
