### ISSUE TITLE
🧐[问题] How do I wrap application root with a provider?

### ISSUE THREAD

**Issue by IronSean** [ant-design/ant-design-pro#6946]
### 🧐 Problem description

I want to wrap my application root with a React Context Provider. But using the ant design pro full template I cannot find where to do this.

It appears to be possible, as documentation like this one suggests it: [https://ant.design/components/config-provider/](config-provider).

And UMI.js shows that there are several config methods exposed to support this, which would usually be in src/App.tsx: https://umijs.org/docs/runtime-config

Where can I best do things like wrap my entire application in a Context Provider, or use methods like OnRouteChange to add behaviour?

**Comment by scotty595** [comment]
Depends on the version - assuming you're using Ant Design Pro V4 rather than the new one, but I've wrapped my components a few ways in the past.

Can use a wrapper in the layout component (i.e. any used layouts in the /layouts folder)

Or create a separate wrapper and wrap all routes in it with the context provider.. 
i.e. original routing config:
```
routes: [
    {
      path: '/user',
      component: '../layouts/UserLayout',
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: './user/login',
        },
      ],
    },
  ],
```

with a wrapper:
```
routes: [
    {
      path: '/',
      component: '../layouts/ContextProvider',
      routes: [
        {
          path: '/user',
          component: '../layouts/UserLayout',
          routes: [
            {
              name: 'login',
              path: '/user/login',
              component: './user/login',
            },
          ],
        },
    ]
  ],
```
Might need to do some work on the breadcrumbs/menu generation if you use the above though, depends, haven't tested specifically...

Or just add the context provider in the layout:

https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.tsx

**Comment by chenshuai2144** [comment]
you can use layout.childrenRender.
```tsx

export const layout = (): BasicLayoutProps & {
  childrenRender?: (dom: JSX.Element) => React.ReactNode;
} => {
  return {
    childrenRender: () => doSomeThing,
  };
};
```

**Comment by scrapstation** [comment]
@chenshuai2144 在app.tsx内修改childrenRender无法在ant-layout-header内拿到上下文
![image](https://user-images.githubusercontent.com/56467036/130418139-6d3e7158-a245-4b7c-bd88-9daebc219c79.png)

![image](https://user-images.githubusercontent.com/56467036/130418109-e8d3f9e2-f790-4ebf-bdbf-28cbfa1813ae.png)

**Comment by scotty595** [comment]
@scrapstation Here's my firebase provider setup... wraps the entire app (add in app.tsx)

see: https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args

```tsx
const FirebaseProvider = ({ children, routes }: any) => {
  const newChildren = React.cloneElement(children, {
    ...children.props,
    routes,
  })

  return (
    <Suspense fallback={<PageLoading />}>
      <FirebaseAppProvider key='fbp' firebaseConfig={fbConfig} suspense={true}>
        {newChildren}
      </FirebaseAppProvider>
    </Suspense>
  );
}

export function rootContainer(container: any) {
  return React.createElement(FirebaseProvider, null, container);
}
```

**Comment by scrapstation** [comment]
@scotty595  u are right, it's an elegant solution

**Comment by daviscyl** [comment]
@scotty595 I'm new to React.js so please bear with my newbie question: why do you have to use cloneElement()?
