### ISSUE TITLE
🧐[问题] 收缩菜单栏的时候，echarts图不会自适应宽度，改变浏览器窗口大小是可以自适应的

### ISSUE THREAD

**Issue by yangdachu** [ant-design/ant-design-pro#6950]
### 🧐 问题描述

收缩菜单栏的时候，echarts图不会自适应宽度，改变浏览器窗口大小是可以自适应的。

怎么能做到收缩菜单的时候也自适应

### 💻 示例代码

` const resize = () => chartInstance.resize();
        window.removeEventListener("resize", resize);
        window.addEventListener("resize", resize);`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23580181/86702580-add64a80-c045-11ea-9188-30a94b133653.png)

**Comment by afc163** [comment]
echarts 问题建议去 echarts 的地方进行反馈。
