### ISSUE TITLE
顶部logo这块 感觉和 线上预览版不一致啊

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#6951]
没有对对齐啊
### © 版本信息

- Ant Design Pro 版本: 5.0.0-alpha.0
- umi 版本  3.1.0
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息

<img width="485" alt="截屏2020-07-07 下午1 38 58" src="https://user-images.githubusercontent.com/183884/86720559-b899db00-c057-11ea-9c32-5c7045f8f81e.png">

**Comment by chenshuai2144** [comment]
无图无真相

**Comment by WuJiY** [comment]
sorry 啊 又重新安装了一下 ，好想又正常了  不知道咋回事
