### ISSUE TITLE
🐛[BUG] V5执行tsc时提示  error TS2614: Module '"../../../node_modules/antd/es/menu"' has no exported member 'ClickParam'

### ISSUE THREAD

**Issue by Elric-H** [ant-design/ant-design-pro#6954]
### 🐛 bug 描述
  使用`npm create umi`选择v5版本的pro创建项目并安装依赖后
  执行tsc时提示  error TS2614: Module '"../../../node_modules/antd/es/menu"' has no exported member 'ClickParam'

### 📷 复现步骤
  `$ tsc`
  `src/components/RightContent/AvatarDropdown.tsx:4:10 - error TS2614: Module '"../../../node_modules/antd/es/menu"' has no exported member 'ClickParam'. Did you mean to use 'import ClickParam from "../../../node_modules/antd/es/menu"' instead?
`
### 💻 复现代码
控制台执行tsc命令
`$ tsc`

### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本: 3.1.0
- 浏览器环境: chrome
- 开发环境: macOS

**Comment by chenshuai2144** [comment]
类型错了，我来更新一下

**Comment by chenshuai2144** [comment]
fixed in v5，是因为 antd 修改了类型导致的

**Comment by Elric-H** [comment]
> fixed in v5，是因为 antd 修改了类型导致的

验证已解决，谢谢大佬

**Comment by Elric-H** [comment]
> fixed in v5，是因为 antd 修改了类型导致的

验证已解决，谢谢大佬

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/pull/7045
