### ISSUE TITLE
🧐[问题]antd-pro的版本很混乱，V5是什么鬼，官网没有

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design-pro#6956]
### 🧐 问题描述
-官网上说antd-pro的2.3版本是最后一个版本；
-npm仓库上也是2.3的版本
-github的release上有4.0的版本

-现在umi-cli生成项目的是让选V4和V5

V5又是什么版本？有文档么？官网的文档是V4的还是V5的。

antd-pro的组件有pro-layout和pro-table，他们的版本和antd-pro什么关系？

**Comment by afc163** [comment]
> -官网上说antd-pro的2.3版本是最后一个版本；

@chenshuai2144 这句话清理一下，误导用户。

**Comment by chenshuai2144** [comment]
> @chenshuai2144 这句话清理一下，误导用户。

清理了，v5 的文档在这里。https://beta-pro.ant.design
