### ISSUE TITLE
🐛[BUG]在列表页面，点展开链接，效果如图所示，左侧被盖住。

### ISSUE THREAD

**Issue by bxvs888** [ant-design/ant-design-pro#6959]
### © 版本信息

- Ant Design Pro 版本: 5.0
- umi 版本 3.2.8
- 浏览器环境  safari，chrome 效果一样。
- 开发环境 macOS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/298322/86780764-ad62a180-c08f-11ea-97b4-5baea994731f.png)

**Comment by kaoding** [comment]
fixed in @ant-design/pro-layout@6.2.1
