### ISSUE TITLE
promiseRender regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by 15011120064** [ant-design/ant-design-pro#696]

**Comment by 15011120064** [comment]
import RenderAuthorized from 'ant-design-pro/lib/Authorized';的时候

**Comment by chenshuai2144** [comment]
typescript?

**Comment by 15011120064** [comment]
什么意思啊？

**Comment by 15011120064** [comment]
引用权限那个控件的时候报的错

**Comment by 15011120064** [comment]
webpack-internal:///645:52 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (webpack-internal:///645:52)
    at eval (webpack-internal:///645:82)
    at eval (webpack-internal:///645:104)
    at Object.<anonymous> (index.js:4994)
    at __webpack_require__ (index.js:708)
    at fn (index.js:113)
    at eval (webpack-internal:///160:12)
    at Object.<anonymous> (index.js:1836)
    at __webpack_require__ (index.js:708)
    at fn (index.js:113)

**Comment by chenshuai2144** [comment]
是不是使用typescript？

**Comment by chenshuai2144** [comment]
babel的问题。 重新更新一下你的包

**Comment by 15011120064** [comment]
现在的版本是最新的 "ant-design-pro": "^1.0.1",

**Comment by chenshuai2144** [comment]
重新更新你所有的包。删除的lock文件。然后重新安装

**Comment by 15011120064** [comment]
好的，我试一下

**Comment by 15011120064** [comment]
还是同样的错误

**Comment by 15011120064** [comment]
删除node-modle ，lock文件，重新 yarn install，yarn start 还是这个错误

**Comment by chenshuai2144** [comment]
我也使用的这个 不会有问题的 。你clone官方试试

**Comment by 15011120064** [comment]
好吧，谢谢了

**Comment by wanghche** [comment]
yarn add babel-polyfill;
import "regenerator-runtime/runtime";

**Comment by wyklion** [comment]
独立方式使用。1.1.0。也是这个问题啊~
用的typescript。

**Comment by wyklion** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined

看看这个 不行升级到版本7.0
