### ISSUE TITLE
在页面里面使用antd的抽屉Drawer的时候，点击蒙层，抽屉关闭不了🐛[BUG]

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#6960]
### 🐛 bug 描述

用umi创建了一个表格页面，在里面把表格的配置组件model改成了抽屉Drawer，然后发现页面点击遮罩没办法关闭遮罩了；

很急很急！！！！！！！！！ 有办法或者有解决方案的回一下 谢谢

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/45235142/86785207-f23d0700-c094-11ea-9312-459cb98a513c.png)

![image](https://user-images.githubusercontent.com/45235142/86785530-59f35200-c095-11ea-881d-57fca713ec6b.png)

**Comment by RachelChanning** [comment]
你代码有问题的。抽屉里面写表单，没有问题的。

**Comment by Asence** [comment]
> 你代码有问题的。拖放里面写表单，没有问题的。

我在排查一次

**Comment by weiningning** [comment]
我点击蒙层也关闭不了，没看到相关api呀
