### ISSUE TITLE
🧐[问题]动态引入本地图片

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#6962]
### 🧐 问题描述
ant-design-pro : v5版本
开发系统：mac
浏览器：Chrome

我根据后端返回的图片名称，动态的去找本地图片

### 💻 示例代码
![image](https://user-images.githubusercontent.com/23183393/86869210-be9bc480-c108-11ea-9a70-e4092fba12b4.png)
报的错误
![image](https://user-images.githubusercontent.com/23183393/86869246-d07d6780-c108-11ea-849a-005f582b5592.png)
当我直接填写路径引入却成功
![image](https://user-images.githubusercontent.com/23183393/86869331-f30f8080-c108-11ea-8665-47eb468079e6.png)
![image](https://user-images.githubusercontent.com/23183393/86869423-1a664d80-c109-11ea-9f9e-4c9823baf2fc.png)

**Comment by huntdream** [comment]
`require`好像不支持这种动态引入

**Comment by xyy7260** [comment]
@huntdream   好
