### ISSUE TITLE
🐛[BUG] V5 增加 antd 的 Descriptions 组件后，”躲“到左边菜单“后面”了

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#6963]
### 🐛 bug 描述

V5 增加 Descriptions 组件后，”躲“到左边菜单“后面”了，
只有加了antd 的 Descriptions 组件会出现这种情况，一开始还以为是 antd 的 Descriptions 组件原因，但使用以前的 antd 版本同样出现，分析后基本可以确定是 ProLayout 产生的（也可能是和 Descriptions 组件共同作用产生的）

![image](https://user-images.githubusercontent.com/18542211/86873782-a7150980-c111-11ea-8d98-5f6711ba5c72.png)

![image](https://user-images.githubusercontent.com/18542211/86873749-949ad000-c111-11ea-922c-45a8a433dc78.png)

### 📷 复现步骤

在V5版本的 Welcome.tsx 中加上 Descriptions 组件后就可以复现，如下图：

![image](https://user-images.githubusercontent.com/18542211/86874044-2efb1380-c112-11ea-885d-f88bb44f3e5a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/6959

**Comment by kaoding** [comment]
@chenshuai2144 希望可以紧急修复一下。

**Comment by kaoding** [comment]
确定这个问题是从 ProLayout v6.1.0 开始出现的，初步看是不是因这个提交的问题：
https://github.com/ant-design/ant-design-pro-layout/commit/4a1bd1877440ac41d3c5cba6797925ba4cac3a3d

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/532

**Comment by chenshuai2144** [comment]
fixed in @ant-design/pro-layout@6.2.1

**Comment by afc163** [comment]
记得 commit 关联 issue。
