### ISSUE TITLE
🧐[问题] 如何让一级菜单可以点击，因为我的二级菜单是隐藏的

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#6964]
### 🧐 问题描述

如图，我没有二级菜单，我想要的效果是当进入这个（"/team-cooperation/details/:chortId"）路由时，高亮一级路由菜单（"/team-cooperation"）

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/86881011-27db0200-c120-11ea-9087-1a3bbca5514f.png)
![image](https://user-images.githubusercontent.com/30942709/86881162-6b357080-c120-11ea-8d45-ec588c09c99b.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/86989944-1b14e780-c1ce-11ea-8081-60de173029d1.png)


把这个包到你要高亮的菜单的 children 里面
