### ISSUE TITLE
什么时候支持多标签页？

### ISSUE THREAD

**Issue by goyuanfang** [ant-design/ant-design-pro#6965]

**Comment by goyuanfang** [comment]
不喜欢element-admin，但是antdpro官方又不支持多标签页

**Comment by afc163** [comment]
Duplicate of #220

**Comment by Fengly0503** [comment]
自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs 在线演示地址：http://pc.loveeveryday.cn/ant-pro-tabs/
