### ISSUE TITLE
Menu is really slow - better use other layout

### ISSUE THREAD

**Issue by pkdcryptos** [ant-design/ant-design-pro#6966]
I struggled allot for few weeks to get the best layout  & scss support out of ant design pro. 

Finally I ended up replacing the layout/menu/sidedrawywr/ basically the whole layout and it is better.
Prolayout menu is damn slow and bad for user experience. No smooth animation, the menu does not close some times or really slow some times.
Layout is really critical for any platform and gives the first hand experience. Inside components are small and easy and antd just works awesome.
But for layout, I prefer to use other smooth layouts.

And also scss is not supported well.. I finally got it worked with plugin..it is just a few lines and you need to remove cssloader in config file..

Best layout + scss support is the need of the hour.

Any comments or suggestions appreciated.

**Comment by xyy7260** [comment]
@pkdcryptos 

请问一下， 我需要这个背景图占满， 但是布中有自带的margin  怎么移除掉呢

![image](https://user-images.githubusercontent.com/23183393/86990534-624fa800-c1cf-11ea-9a6d-9c7033a6bbdb.png)

**Comment by pkdcryptos** [comment]
> @pkdcryptos
> 
> 请问一下， 我需要这个背景图占满， 但是布中有自带的margin 怎么移除掉呢
> 
> ![image](https://user-images.githubusercontent.com/23183393/86990534-624fa800-c1cf-11ea-9a6d-9c7033a6bbdb.png)

Answered on the other thread

**Comment by pkdcryptos** [comment]
> @pkdcryptos
> 
> 请问一下， 我需要这个背景图占满， 但是布中有自带的margin 怎么移除掉呢
> 
> ![image](https://user-images.githubusercontent.com/23183393/86990534-624fa800-c1cf-11ea-9a6d-9c7033a6bbdb.png)

Can you pls remove this, as it is not related to the title of the issue

**Comment by xyy7260** [comment]
@pkdcryptos  ok

**Comment by chenshuai2144** [comment]
Our entire ecology is based on less
Layout performance issues, we will focus on the next iteration
