### ISSUE TITLE
如何取消自带的布局margin🧐[问题]

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#6969]
### 🧐 问题描述
ant-design-pro : v5版本
开发系统：mac
浏览器：Chrome

我需要把背景图片占满全屏，但是自带的布局有margin所以无法占满，
![image](https://user-images.githubusercontent.com/23183393/86991961-f40ce480-c1d2-11ea-8ce1-e5196ff2f95e.png)
![image](https://user-images.githubusercontent.com/23183393/86991990-071fb480-c1d3-11ea-8d27-6a78116a5bde.png)

**Comment by pkdcryptos** [comment]
> ###  问题描述
> ant-design-pro : v5版本
> 开发系统：mac
> 浏览器：Chrome
> 
> 我需要把背景图片占满全屏，但是自带的布局有margin所以无法占满，
> ![image](https://user-images.githubusercontent.com/23183393/86991961-f40ce480-c1d2-11ea-8ce1-e5196ff2f95e.png)
> ![image](https://user-images.githubusercontent.com/23183393/86991990-071fb480-c1d3-11ea-8d27-6a78116a5bde.png)
> 
> ###  示例代码
> ###  其他信息

You can overwrite css in global.less file

**Comment by xyy7260** [comment]
@pkdcryptos 如果我在login页面中，  我在login.less去覆盖 :global{.ant-pro-basicLayout-content{margin:0}}这样没问题。
但是在别的页面中， ant-pro-basicLayout-content也会被覆盖。
比如我覆盖了当前样式
![image](https://user-images.githubusercontent.com/23183393/87106256-9db1ab80-c28f-11ea-957a-f3d9c2eb67ee.png)
去了别的页面
![image](https://user-images.githubusercontent.com/23183393/87106422-fed97f00-c28f-11ea-9971-263b0c7b153e.png)
覆盖的样式也会被带过去。

因为ant-pro-basicLayout-content的样式在最外面，所以无法通过自己定义className来包裹改，
.myClass{ //login.less  no
:global{.ant-pro-basicLayout-content{margin:0}}
}
:global{.ant-pro-basicLayout-content{margin:0}} //yes

**Comment by xyy7260** [comment]
我用别的方法解决了，就覆盖 :global{.ant-pro-basicLayout-content{margin:0}}
跳转的的时候使用 window.location.replace

**Comment by up55** [comment]
可以直接使用position定位：
```
position: absolute;
  top: -24px;
  left: -24px;
  right: -24px;
```
