### ISSUE TITLE
🧐[问题]ant design pro v2 打包后上生产第一次页面加载很慢？

### ISSUE THREAD

**Issue by Felix-lucky** [ant-design/ant-design-pro#6974]

**Comment by chenshuai2144** [comment]
试试 `ANALYZE=1 umi build` 看看你的包里面有什么东西。

https://pro.ant.design/docs/build-cn#%E5%88%86%E6%9E%90%E6%9E%84%E5%BB%BA%E6%96%87%E4%BB%B6%E4%BD%93%E7%A7%AF
