### ISSUE TITLE
更新版本后登陆界面有菜单导航栏🐛[BUG]

### ISSUE THREAD

**Issue by guogeer** [ant-design/ant-design-pro#6975]
### 🐛 bug 描述

未做为何改动，仅npm update
    {
      path: '/user/login',
      hideInMenu: true,
      layout: false,
      routes: [
        {
          name: '登陆',
          path: '/user/login',
          component: './user/login',
        }
      ],
    },
    ...
登陆界面莫名显示了导航栏
![image](https://user-images.githubusercontent.com/5010851/87025261-bd53c000-c20c-11ea-956f-13d517f34262.png)

### 🏞 期望结果

登陆界面不应该显示了导航栏

### © 版本信息

- Ant Design Pro 版本: 5.0.0-alpha.0
- umi 版本 3.2.8
- 浏览器环境 chrome 83.0.4103.116
- 开发环境 macOS

**Comment by leesama** [comment]
我也遇到该问题了

**Comment by chenshuai2144** [comment]
执行下面的代码，重试一下
```
git clean -dfx 
npm install 
```

**Comment by guogeer** [comment]
感谢回复，不过试了下，没有效果。

**Comment by leesama** [comment]
![微信图片_20200714162713](https://user-images.githubusercontent.com/16167426/87403019-ed290c00-c5ee-11ea-9bd8-c38b84476569.png)
![微信图片_20200714162710](https://user-images.githubusercontent.com/16167426/87403025-eef2cf80-c5ee-11ea-8a38-fb6f506eb960.png)
文档更新了，你看看你的配置对不对
这是我现在的配置
![image](https://user-images.githubusercontent.com/16167426/87403080-003bdc00-c5ef-11ea-99e0-84ab82a47978.png)

**Comment by leesama** [comment]
`  {
    path: '/login',
    layout: false,
    component: './login',
  },`

**Comment by guogeer** [comment]
问题解决了。
  {
    path: '/user/login',
    // hideInMenu: true, // 这行代码会导致登陆界面显示出菜单。
    layout: false,
    component: './user/login'
  },

**Comment by leesama** [comment]
@guogeer 你切换pagesize 正常吗？

**Comment by guogeer** [comment]
@leesama 试了一下，默认分页20，点击其他的分页不生效

**Comment by leesama** [comment]
这个只能antd 降级来解决 ，pro table issue里有这个问题   @chenshuai2144  帅哥该问题有知晓吗？
