### ISSUE TITLE
🧐[问题]  图表显示异常 

### ISSUE THREAD

**Issue by codeliufan** [ant-design/ant-design-pro#6977]
### 🧐 问题描述
自己的项目开启keep-alive和多标签时，切换页面并改变窗口尺寸，再切换回图表页面时，页面的图标显示异常。

在以前的antd pro版本中也有这个问题。

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/16485762/87026888-f5f49900-c20e-11ea-8152-a1977998495b.png)

**Comment by leesama** [comment]
兄弟这是 react 版本的，没有keep-alive和多标签

**Comment by codeliufan** [comment]
抱歉抱歉，走错片场，我去那边提去

**Comment by codeliufan** [comment]
抱歉抱歉，走错片场，我去那边提去。。
