### ISSUE TITLE
🐛[BUG]V4生成的模板，CardList样式还是错乱的

### ISSUE THREAD

**Issue by crashsol** [ant-design/ant-design-pro#6979]
### 🐛 bug 描述
使用yarn create umi 创建V4 Typescript 完全分支，预览CardList 页面样式错乱

![image](https://user-images.githubusercontent.com/17925647/87035718-4faf9000-c21c-11ea-9fd1-1820dc6da8c0.png)

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/17925647/87035480-fb0c1500-c21b-11ea-9d5f-334dbaffe7cb.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
同步了一下码云，可以在执行一下` fetch:blocks`
