### ISSUE TITLE
URL对象的searchParams属性问题在Edge浏览器中不支持

### ISSUE THREAD

**Issue by canzihou** [ant-design/ant-design-pro#698]
刚更新出来的layouts/BasicLayout.js中有这么一行

const redirect = urlParams.searchParams.get('redirect') || '/dashboard/analysis';

经测试和查询后发现Edge浏览器中URL对象没有searchParams这个属性，看了一下antdPRO支持的是现代浏览器以及IE11，不知道Edge浏览器是否兼容？

**Comment by chenshuai2144** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8993198/
最近将会实现的。

**Comment by chenshuai2144** [comment]
我应该使用一个polyfill .谢谢你的提醒

**Comment by chenshuai2144** [comment]
look  #699

**Comment by canzihou** [comment]
thanks a lot. Should I close this?@chenshuai2144

**Comment by chenshuai2144** [comment]
等分支呗合并
