### ISSUE TITLE
🐛[BUG] config transforms don't work.

### ISSUE THREAD

**Issue by IronSean** [ant-design/ant-design-pro#6980]
### 🐛 bug description

UMI.js supports config file transformations for different config settings in different environments. More info here: https://v2.umijs.org/guide/env-variables.html#environment-variables

However, these transforms do not seem to work in Ant Design Pro.

### 📷 Steps to reproduce

1. Open Ant Design Pro template
2. Create config/config.dev.ts
3. Define additional settings in there and export
4. modify package.json script `start:dev` to `"start:dev": "cross-env UMI_APP=dev REACT_APP_ENV=dev MOCK=none umi dev",`
5. run `npm run dev` or `npm run start:dev`
6. See the settings aren't working.

### 🏞 Expected result

The config.{ENVIRONMENT_NAME}.ts settings are merged into the config.ts settings, and affect the app.

### © Version Information

-Ant Design Pro version: current
-umi version: 3.0.14
-Browser environment: N/A
-Development environment : Windows 10

**Comment by chenshuai2144** [comment]
show your code, this api should work
