### ISSUE TITLE
🐛[BUG]登陆页面又出问题了.

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#6982]
### 🐛 bug 描述

登陆页面又这样了.就很奇怪,明明之前就修好了的bug.目前尚不清楚是插件问题还是pro的问题.
![image](https://user-images.githubusercontent.com/13188169/87108362-b5d7f980-c294-11ea-9250-5354b38b75b3.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by joesdu** [comment]
把路由改了下就可以了,但是感觉还是是个bug.
之前的路由写法
```typescript
  {
    layout: false,
    path: '/login',
    component: './login'
  },
```
调整后的路由写法
```typescript
  {
    layout: false,
    path: '/login',
    routes: [
      {
        name: '登陆',
        path: '/login',
        component: './login'
      }
    ]
  },
```

**Comment by leesama** [comment]
我改了还是不行

**Comment by joesdu** [comment]
> 我改了还是不行

😂这是什么原理哦.

**Comment by leesama** [comment]
@chenshuai2144 帅哥 该问题如何解决呢

**Comment by chenshuai2144** [comment]
https://github.com/umijs/route-utils/commit/624cbb6d73ae5b95f50682e4b61225d8c5a48f5a#diff-281faf2ac6865c54acdc5848a36f7118R162
应该和这个有关，再试试呢

**Comment by joesdu** [comment]
> [umijs/route-utils@624cbb6#diff-281faf2ac6865c54acdc5848a36f7118R162](https://github.com/umijs/route-utils/commit/624cbb6d73ae5b95f50682e4b61225d8c5a48f5a#diff-281faf2ac6865c54acdc5848a36f7118R162)
> 应该和这个有关，再试试呢

😟这个怎么试哦.

**Comment by leesama** [comment]
@chenshuai2144 

😟这个怎么试哦.

**Comment by joesdu** [comment]
> @chenshuai2144 回复要回复完整。
> 
> @joesdu @leesama 请尝试清除 package-lock.json 后重新 npm install。

这样好了.

**Comment by leesama** [comment]
@joesdu 你确定你正常了吗？我这儿还是不行  老哥

**Comment by joesdu** [comment]
> @joesdu 你确定你正常了吗？我这儿还是不行 老哥

我这儿好了,你删掉lock文件,删掉node_model文件夹,删掉yarn的cache文件.然后重新安装试一下.

**Comment by leesama** [comment]
@joesdu 还是不行 你之前的路由改了吗？

**Comment by joesdu** [comment]
> @joesdu 还是不行 你之前的路由改了吗？

我改回原来那种了，不带routers的

**Comment by leesama** [comment]
可以了，umi的文档太快了😓

**Comment by joesdu** [comment]
> 可以了，umi的文档更新太快了😓

更新啥了.😮

**Comment by leesama** [comment]
> > 可以了，umi的文档更新太快了😓
> 
> 更新啥了.😮

去看看吧，反正和我的配置差异有点大，也可能我之前就没写对😂

**Comment by joesdu** [comment]
> > > 可以了，umi的文档更新太快了😓
> > 
> > 更新啥了.😮
> 
> 去看看吧，反正和我的配置差异有点大，也可能我之前就没写对😂

我都是按照文档升级的，文档中用的内容我都以文档为主
