### ISSUE TITLE
🧐[问题] 有 Ant Design Pro v4 的 Sketch 设计套件吗？

### ISSUE THREAD

**Issue by yangmingshan** [ant-design/ant-design-pro#6983]
### 🧐 问题描述
现在官网上下载的 Ant Design Pro 设计套件还是 3.x 版本，设计师用此套件做了设计。而我们开发使用的 4.x 版本，这就造成了设计稿与实现不匹配。

### 🚑 解决方案
将官网的 Ant Design Pro 设计套件更新为 4.x 版本。

**Comment by chenshuai2144** [comment]
https://ant.design/docs/resources-cn

在这里
