### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by xicka** [ant-design/ant-design-pro#6986]
### 🧐 问题描述 
webpack  打包时提示错误

var api = require("!../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js");
      ^
Unrecognised input
      Error in xxx\node_modules\@ant-design\pro-layout\es\FooterToolbar\index.less (line 1, column 8)

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/5865187/87138159-98c11c00-c2d0-11ea-8b0c-2678ad4ff1bf.png)

**Comment by chenshuai2144** [comment]
less-loader 没有配置吗？
