### ISSUE TITLE
🐛[BUG] V5版本 package.json 中引入  "@umijs/plugin-access-layout": "^1.2.0" 后系统无法启动:

### ISSUE THREAD

**Issue by houtianxi** [ant-design/ant-design-pro#6988]
package.json 中引入plugin-access-layout后系统无法启动:
 package.json 加入:
    "@umijs/plugin-access-layout": "^1.2.0",

编译通过后，打开站点报错如下：

 
![image](https://user-images.githubusercontent.com/3362680/87217250-b72f2200-c379-11ea-85f4-8e10f5f1ae19.png)

**Comment by xunbie** [comment]
git clean -dfx
然后再安装依赖

**Comment by xunbie** [comment]
git clean -dfx
然后再安装依赖
