### ISSUE TITLE
🐛[BUG]umi快速生成模板时formatMessage可能抛错

### ISSUE THREAD

**Issue by yukilzw** [ant-design/ant-design-pro#6990]
### 🐛 bug 描述

项目初始化，start报错

### 📷 复现步骤

npm create umi myapp
- ant-design-pro
- Pro V4
- Javascript
- simple
- anyd@4
npm i
npm start
浏览器出现报错信息
 
>Error: [React Intl] An `id` must be provided to format a message.
>invariant
>./src/invariant.ts:7
>  4 |         throw new Err(message);
>  5 |     }
>  6 | }
>  7 | //# sourceMappingURL=invariant.js.map
> formatMessage
> ./node_modules/react-intl/lib/formatters/message.js:34
> formatMessage
> ./node_modules/@ant-design/pro-layout/es/BasicLayout.js:174

### 🏞 期望结果

能正常出现模板页面

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 3.1.2
- Chrome
- win10
- node v12.18.2
- npm 6.14.6

**Comment by xuan200922702** [comment]
我也出现了这个错误，新创建的项目，yarn start  报错。求解

**Comment by niufen0420** [comment]
+1

**Comment by kovalevroman7** [comment]
+1

**Comment by eeBryant** [comment]
+1

**Comment by chenshuai2144** [comment]
fixed in https://github.com/umijs/route-utils/commit/4c09bb43d909c90f6f4ac2325729cc83d1d2a205
