### ISSUE TITLE
🐛[BUG]预览页面报错，页面不显示

### ISSUE THREAD

**Issue by zhanghslq** [ant-design/ant-design-pro#6993]
### 📷 复现步骤
https://preview.pro.ant.design/

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30916066/87241340-ccc54a00-c454-11ea-8cae-bcc0c6b07173.png)

**Comment by GitHubWuYi** [comment]
这种错误都能犯.....

**Comment by Dongsw08** [comment]
真的服了

**Comment by yangdachu** [comment]
好奇怎么上线的啊

**Comment by chenshuai2144** [comment]
fixed

**Comment by chenshuai2144** [comment]
> 好奇怎么上线的啊

机器人自动部署的 https://github.com/ant-design/ant-design-pro/runs/863932912

**Comment by afc163** [comment]
@chenshuai2144 要跑过 E2E 再部署。
