### ISSUE TITLE
🐛[BUG]layout='mix'，navTheme='light'时，顶部header为黑色

### ISSUE THREAD

**Issue by LamdoHeaven** [ant-design/ant-design-pro#6994]
### 🏞 期望结果
顶部header应为白色

### 💻 复现代码
![image](https://user-images.githubusercontent.com/45940666/87262438-858a9800-c4ec-11ea-9aaa-3c6d0cf05202.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/45940666/87262469-9dfab280-c4ec-11ea-9a00-a9cb28445bae.png)

**Comment by chenshuai2144** [comment]
按照现在的设计，mix 只支持黑白配。
