### ISSUE TITLE
使用4.0版本的pro，执行install后，node_gyp总是报错

### ISSUE THREAD

**Issue by WangAmin** [ant-design/ant-design-pro#6995]
执行install后，node_gyp总是报错，
npm install --global --production windows-build-tools执行成功
npm install -g node-gyp安装成功，正确并配置npm config set node_gyp
![image](https://user-images.githubusercontent.com/22916287/87267080-4e6eb380-c4f9-11ea-9f7a-ab79551c4970.png)

**Comment by WangAmin** [comment]
@chenshuai2144 麻烦帮忙看下呗，是不是我node版本的问题，还是什么问题

**Comment by chenshuai2144** [comment]
试着升级一下 node12 吧。理论上是不需要 gyp 编译的，
我们的依赖中是没有需要gyp 的

**Comment by WangAmin** [comment]
> 试着升级一下 node12 吧。理论上是不需要 gyp 编译的，
> 我们的依赖中是没有需要gyp 的
> 
> gyp 的安装特别复杂，最好跟着 node 的最新版本来更新


我的node是v14.5.0，npm是6.14.6版本已经很新了，pro3和pro2的版本执行npm install都没出现问题，只有使用V4的项目会报这个错误

**Comment by liihuu** [comment]
问题解决了吗？我遇到了同样的问题。

**Comment by WangAmin** [comment]
> 问题解决了吗？我遇到了同样的问题。
没有解决，你试试把node环境和npm装的一些插件卸载重装试试吧，node版本不要安装太新的，当时出现这个问题的时候，看到过“node版本太新问题”的说法

**Comment by liihuu** [comment]
已经解决了，的确是node版本的问题，node 16.x的版本会报错
