### ISSUE TITLE
🐛[BUG] Pro Menu initial click work strangely

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#6996]
1. 访问 https://preview.pro.ant.design/dashboard/analysis
2. 点击左侧菜单 `工作台`
3. 此时菜单收起后又展开，预期应该没有这个动画效果

**Comment by chenshuai2144** [comment]
这个和 umi 有关系，重复了

**Comment by chenshuai2144** [comment]
dup of  https://github.com/ant-design/ant-design-pro/issues/6828
