### ISSUE TITLE
🐛[BUG]  ant design pro V4 选择javascript生成的文件怎么是tsx

### ISSUE THREAD

**Issue by zhangxiaofeng87** [ant-design/ant-design-pro#6999]
### © 版本信息
- 开发环境：window 10 和 mac v10.13.6
- node版本：v10.21.0 和 v12.13.1
- npm版本：v6.14.0 和 v6.13.1

### 🚑 其他信息

> 把环境补充一下，用的系统，node 的版本，babel 和 ts 的版本都列一下，我们想办法复现一下。
> 
> > 最好直接用 ts

找到问题了，是脚手架好久没更新了 ，版本太低了，刚更新了下create-umi好了，感谢您的支持！

**Comment by chenshuai2144** [comment]
这种的一般都是 全局安装了 typescript 和 babel 导致，
全局的可能版本有问题，导致编译失败了

**Comment by zhangxiaofeng87** [comment]
> 这种的一般都是 全局安装了 typescript 和 babel 导致，
> 全局的可能版本有问题，导致编译失败了

好几个人试了都是这个问题，他们也没全局安装过 typescript 和 babel，刚试了下选择antd@3x的没问题，选antd@4x以后，不管选ts还是js，生成的都是tsx文件，如果是这种问题，要怎么解决呢，

**Comment by chenshuai2144** [comment]
把环境补充一下，用的系统，node 的版本，babel 和 ts 的版本都列一下，我们想办法复现一下。

> 最好直接用 ts

**Comment by Zhong-Ling** [comment]
您好，我导入 ant design pro怎么还是.tsx啊
