### ISSUE TITLE
为什么要在index.html 引用 另外的https://gw.alipayobjects.com/as/g/??datavis/g2/2.3.12/index.js ？

### ISSUE THREAD

**Issue by sillyfeng** [ant-design/ant-design-pro#70]
老铁，我想知道index.html 中的那行js引用是起到了什么作用，好像没有还不行，在我们的内部环境是访问不了的？有什么替代方式吗？？

**Comment by afc163** [comment]
可以拷贝上述静态文件的内容并自行部署。

或者关闭相应的 extenals：https://github.com/ant-design/ant-design-pro/blob/97092686cfbcc69b29b1f038c18b17a98a25d8d5/.roadhogrc#L23-L25
