### ISSUE TITLE
菜单上面的logo到底应该如何更换？

### ISSUE THREAD

**Issue by ImJustAMan** [ant-design/ant-design-pro#7000]
这个问题我在v4版本就很好奇。。
到底应该怎么样才能配置到这个logo，在v4 layout还能看到的时候，我强行改layout代码还能改
现在v5版本来了，layout全都莫得了
那么 我到底应该怎么把菜单上面的logo改成我自己的呢。。

**Comment by afc163** [comment]
请 @chenshuai2144 补充文档和 FAQ。

**Comment by koupeng** [comment]
+1

**Comment by joesdu** [comment]
> 这个问题我在v4版本就很好奇。。
> 到底应该怎么样才能配置到这个logo，在v4 layout还能看到的时候，我强行改layout代码还能改
> 现在v5版本来了，layout全都莫得了
> 那么 我到底应该怎么把菜单上面的logo改成我自己的呢。。

直接在app.ts中写logo:xxxx就可以了.umi的插件文档中有写.

**Comment by joesdu** [comment]
```typescript
export const layout = ({ initialState }: { initialState: { settings?: LayoutSettings } }): BasicLayoutProps => ({
  logo: '',
  siderWidth: 220,
  rightContentRender: () => <RightContent />,
  disableContentMargin: false,
  disableMobile: true,
  menuHeaderRender: undefined,
  ...initialState?.settings
});
```
在app.ts中的layout函数中可以写入logo.值可以是本地文件import的.也可以是http地址或者CDN链接.
或者在umi的config文件中
如下写到|:
```typescript
export default defineConfig({
  antd: {
    dark: false
  },
  dynamicImport: {
    loading: '@/components/PageLoading'
  },
  esbuild: {},
  favicon: 'http://service-gw.winside.com:8080/uploadFile/webicon/favicon.svg',
  hash: true,
  history: {
    type: 'hash'
  },
  ignoreMomentLocale: true,
  layout: {
    locale: false,
    logo: 'http://service-gw.winside.com:8080/uploadFile/webicon/logo.svg'
  },
  locale: {
    default: 'zh-CN',
    antd: true,
    baseNavigator: true
  },
  routes: Route,
  theme: {
    'primary-color': Default.primaryColor
  },
  title: false
});
```

**Comment by ImJustAMan** [comment]
> > 这个问题我在v4版本就很好奇。。
> > 到底应该怎么样才能配置到这个logo，在v4 layout还能看到的时候，我强行改layout代码还能改
> > 现在v5版本来了，layout全都莫得了
> > 那么 我到底应该怎么把菜单上面的logo改成我自己的呢。。
> 
> 直接在app.ts中写logo:xxxx就可以了.umi的插件文档中有写.

感谢 我找到了 但是还是希望pro的文档可以至少说明下这个文档是有的 不然实在是有点懵逼

**Comment by Jackay1990** [comment]
> > > 这个问题我在v4版本就很好奇。。
> > > 到底应该怎么样才能配置到这个logo，在v4 layout还能看到的时候，我强行改layout代码还能改
> > > 现在v5版本来了，layout全都莫得了
> > > 那么 我到底应该怎么把菜单上面的logo改成我自己的呢。。
> > 
> > 
> > 直接在app.ts中写logo:xxxx就可以了.umi的插件文档中有写.
> 
> 感谢 我找到了 但是还是希望pro的文档可以至少说明下这个文档是有的 不然实在是有点懵逼

请问是在哪个目录的  app.ts , 这个logo 好难改

**Comment by joesdu** [comment]
> > > > 这个问题我在v4版本就很好奇。。
> > > > 到底应该怎么样才能配置到这个logo，在v4 layout还能看到的时候，我强行改layout代码还能改
> > > > 现在v5版本来了，layout全都莫得了
> > > > 那么 我到底应该怎么把菜单上面的logo改成我自己的呢。。
> > > 
> > > 
> > > 直接在app.ts中写logo:xxxx就可以了.umi的插件文档中有写.
> > 
> > 
> > 感谢 我找到了 但是还是希望pro的文档可以至少说明下这个文档是有的 不然实在是有点懵逼
> 
> 请问是在哪个目录的 app.ts , 这个logo 好难改

![image](https://user-images.githubusercontent.com/13188169/87640558-779d7700-c779-11ea-9ab8-94a27a4a98ce.png)

**Comment by Jackay1990** [comment]
> > > > > 这个问题我在v4版本就很好奇。。
> > > > > 到底应该怎么样才能配置到这个logo，在v4 layout还能看到的时候，我强行改layout代码还能改
> > > > > 现在v5版本来了，layout全都莫得了
> > > > > 那么 我到底应该怎么把菜单上面的logo改成我自己的呢。。
> > > > 
> > > > 
> > > > 直接在app.ts中写logo:xxxx就可以了.umi的插件文档中有写.
> > > 
> > > 
> > > 感谢 我找到了 但是还是希望pro的文档可以至少说明下这个文档是有的 不然实在是有点懵逼
> > 
> > 
> > 请问是在哪个目录的 app.ts , 这个logo 好难改
> 
> ![image](https://user-images.githubusercontent.com/13188169/87640558-779d7700-c779-11ea-9ab8-94a27a4a98ce.png)

找到了，万分感谢哈！

**Comment by joesdu** [comment]
解决了就关掉吧
