### ISSUE TITLE
Umi - replace with CRA

### ISSUE THREAD

**Issue by pkdcryptos** [ant-design/ant-design-pro#7001]
Create-react-app/react-app-rewired can work well with dva. Then what exactly umi helps with: 

I think the below ones.

1) setlocale, getlocale, useIntl, formatted message : I guess these can be handled very well with any standard react based code

2) umi request - either we can use umi request or any react standard one 

3) link, history, redirect,route - can be handled by any react based setup

4) menu handling - can be done easily

So, I am thinking to replace the whole umi and make it cra based. I found some github code too that is ported from umi to cra based.

Not sure, why we have to stick with umi, the webpack configuration is very difficult to understand. Not much English language based support. 

What you guys think, if we can use ant design pro with cra ?

Will I be missing any imp things, if I replace umi with cra?

Thanks allot for any support /help

**Comment by chenshuai2144** [comment]
umi is to reduce the configuration, out of the box.
He has more presets instead of choosing so many technology stacks

**Comment by pkdcryptos** [comment]
i agree. but we are loosing the flexibility. but i still have to agree with you. probably making umi more flexible is the way to go. thaqnks
