### ISSUE TITLE
👑 [需求]config 里面路由的redirect 配置问题  如何动态配置 /的redirect

### ISSUE THREAD

**Issue by HHL030303** [ant-design/ant-design-pro#7002]
在已登录的情况下，手动在url上输入https: xxxxxxx/#/ ,router.config.js的重定向地址怎么改变
如何动态配置 /的redirect

**Comment by chenshuai2144** [comment]
在routers最后写一个 `{ redirect:"path"  } `，这样没被命中的都会跳转

**Comment by HHL030303** [comment]
这个path是一个写死的值啊，但是我需要的是动态配置，你这种思路根本不可行
