### ISSUE TITLE
👑 [左侧菜单折叠按钮，应该固定在浏览器左下角]

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design-pro#7004]
### 🥰 需求描述

左侧菜单折叠/展开的按钮，应该固定在左下角。
目前是跟随在菜单底部，如果菜单较少还行，菜单很多时，需要滚动菜单到底部才能操作，不是很方便。

### 🧐 解决方案

左侧菜单折叠/展开的按钮，应该固定在左下角。

**Comment by chenshuai2144** [comment]
可以设置固定侧边菜单的。
https://preview.pro.ant.design/dashboard/analysis

```
<ProLayout
 fixSiderbar
/>
```

 默认就是这样做的
