### ISSUE TITLE
🧐[问题] yarn create umi 失败  （#6363无法解决问题）

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design-pro#7005]
### 🧐 问题描述

根据官网指引 执行 `yarn create umi`后最后一步的时候报下载错误

为什么使用的是gitee的仓库，而不用github的仓库？ 是这个原因导致的吗？ 

我单独 `git clone git@github.com:ant-design/ant-design-pro.git` 没有问题，所以不是我的网络问题

### 💻 示例代码

`
fatal: unable to access 'https://gitee.com/ant-design/ant-design-pro/': Failed to connect to 127.0.0.1 port 1080: Connection refused

Error: Command failed: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 E:\study\antd-pro
`

![Snipaste_2020-07-14_13-50-40](https://user-images.githubusercontent.com/26042365/87389313-1ccd1980-c5d9-11ea-8bab-08c40dcaa95b.png)

**Comment by H-Sven** [comment]
[#6363](https://github.com/ant-design/ant-design-pro/issues/6363) 还是不行

**Comment by H-Sven** [comment]
@afc163 @chenshuai2144  我并没有生成像#6363中说的一样有一个.yo....文件

**Comment by H-Sven** [comment]
我现在无法创建项目了！

**Comment by H-Sven** [comment]
![1](https://user-images.githubusercontent.com/26042365/87392637-77697400-c5df-11ea-9c90-b56e3afe91bc.png)
![2](https://user-images.githubusercontent.com/26042365/87392645-79cbce00-c5df-11ea-9530-698327977d2d.png)
![3](https://user-images.githubusercontent.com/26042365/87392652-7b959180-c5df-11ea-95f3-6f1fd7f87ea2.png)
![4](https://user-images.githubusercontent.com/26042365/87392657-7d5f5500-c5df-11ea-918d-985ccd464664.png)
![5](https://user-images.githubusercontent.com/26042365/87392660-7f291880-c5df-11ea-8c10-103c5742a3c0.png)





@afc163 @chenshuai2144  没有像#6363中说的那样有所谓的.yo-repository， 直接就是创建失败

**Comment by H-Sven** [comment]
我现在完全无法创建项目了。 已经一整天了

**Comment by chenshuai2144** [comment]
```bash 
git clone https://gitee.com/ant-design/ant-design-pro --depth=1 E:\study\antd-pro
```

这个命令你能跑吗？

**Comment by chenshuai2144** [comment]
```bash
fatal: unable to access 'https://gitee.com/ant-design/ant-design-pro/': Failed to connect to 127.0.0.1 port 1080: Connection refused

```

从日志来看是你的代理问题，你可以先关掉代理试试

**Comment by H-Sven** [comment]
@chenshuai2144 

谢谢，
不过为什么可以 git clone git@github.com:ant-design/ant-design-pro.git
为什么你们是从gitee去拉的代码  gitee设置了代理的情况下为什么clone不了代码，github却可以

**Comment by chenshuai2144** [comment]
@H-Sven 因为大部分用户没有梯子，所有我们在码云搞了一个备份，这样国内用户也可以很快，
但是码云在国外不是很快

**Comment by dmljc** [comment]
fatal: unable to access 'https://gitee.com/ant-design/ant-design-pro/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to gitee.com:443

![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
@dmljc  It looks like a network problem

**Comment by mm6950302** [comment]
@H-Sven 你好，我也遇到和你一样的问题，请问最后解决了吗？

**Comment by chenshuai2144** [comment]
https://blog.csdn.net/daerzei/article/details/79528153
