### ISSUE TITLE
ProTable使用DataSource请求数据的话。 actionRef.current.reload()事件没用的问题   急急急！！！🧐[问题]

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7006]
### 🧐 问题描述

ProTable使用DataSource请求数据的话。 actionRef.current.reload()事件失效；

紧急问题，求告知！！！！！！

### 🚑 其他信息
版本6.2.2

![image](https://user-images.githubusercontent.com/45235142/87408230-c02c2780-c5f5-11ea-8b4b-961cabd46871.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/87496285-d97cb480-c685-11ea-9f9a-8d268d622963.png)


你应该用这个的，没用的 request ，reload 是不生效
