### ISSUE TITLE
🐛[BUG] react-initl 的问题，它的字符串调用方法发生了改变，然后 ant design pro 中的某些代码使用了错误的方法

### ISSUE THREAD

**Issue by youngershen** [ant-design/ant-design-pro#7007]
### 🐛 bug 描述

使用官方文档最新建立项目的方式，建立 V 4 版本的 ant design pro 项目，建立完之后装包完成，使用 npm start
启动项目之后，打开页面，会显示如下报错

 
![image](https://user-images.githubusercontent.com/1480539/87410889-7cd3b800-c5f9-11ea-99c4-27de04f6fb51.png)

### 📷 复现步骤

通过官方文档提供的方法就可以复现，一定要安装 v4 版本的 ant design pro, 

### 🏞 期望结果

我看了很长时间代码，发现应该是 react-initl 的问题，它的字符串调用方法发生了改变，然后 ant design pro 中的某些代码使用了错误的方法，导致出现这个错误。

### © 版本信息

全都是 npm 最新版

**Comment by youngershen** [comment]
貌似很多人都遇到了，而我目前也没解决，希望大佬帮忙解决一下，在下感激不尽，近期要开发一个项目所以选择了 ant design pro， 如果解决不了，那只能换框架了！！伤心！！！重复安装很多次，每次都会遇到这个问题

**Comment by chenshuai2144** [comment]
删除一下 lock 文件，然后在重新安装。

**Comment by youngershen** [comment]
> 删除一下 lock 文件，然后在重新安装。

非常感谢，确实解决了问题，您可以解释一下这个问题的原因么
