### ISSUE TITLE
How to debug custom less partial files

### ISSUE THREAD

**Issue by pkdcryptos** [ant-design/ant-design-pro#7008]
Hi

How to debug in chrome to point to less partial style files. It always points to main .less file , but does not show the source maps to partial files.

I tried devtool and sourcemap configuration, but no success. Hope somebody helps.

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是它已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but it has not responded for a long time. We will temporarily close it
