### ISSUE TITLE
🧐[问题]config.js中routes菜单的icon从哪里检索有哪些key可以直接使用

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-pro#7009]
### 🧐 问题描述
 **icon: 'crown',** 比如这个crown图标从哪里搜到的，而且他的key就是crown?

**Comment by chenshuai2144** [comment]
https://ant.design/components/icon-cn/

是这里的，可以完全使用

**Comment by koupeng** [comment]
> https://ant.design/components/icon-cn/
> 
> 是这里的，都可以使用

你好。<CrownOutlined />  在那个官方https://ant.design/components/icon-cn/  搜到的是<CrownOutlined /> ，，我从哪里知道他的简写是crown呢？

**Comment by chenshuai2144** [comment]
是ant design 3 是时期的写法 理论上不应该用了

**Comment by rabbitlhf** [comment]
难道现在必须要 先定义一个map 进行遍历吗？ 有没有geng'hao更好的解决方案？
![image](https://user-images.githubusercontent.com/1415158/89411128-7bf4f880-d757-11ea-8a55-7777649aea7b.png)

**Comment by pxim** [comment]
同问

**Comment by pxim** [comment]
```
{
      path: '/create-project',
      name: 'create-project',
      icon: 'FileAddOutlined',
      component: './editor/W3DEditor/ProjectCreate',
    },
```

发现这样可以
