### ISSUE TITLE
编译一次突然变久了，第一次启动和热加载都要70多S

### ISSUE THREAD

**Issue by binyellow** [ant-design/ant-design-pro#701]
![image](https://user-images.githubusercontent.com/29519985/34967764-0d5d958a-faa0-11e7-815c-f3e1fac0e965.png)
同时还经常在改动之后内存溢出，不知道是工程变大之后的问题还是设置问题
![image](https://user-images.githubusercontent.com/29519985/34967873-a91e3722-faa0-11e7-9e67-87826cc53214.png)

**Comment by chenshuai2144** [comment]
不应该呀。。。问给roadhog把。 你这个不是普遍现象

**Comment by lichaoming1559731827** [comment]
这是普遍现象我们这边3台电脑都不行，都是内存溢出

**Comment by chenshuai2144** [comment]
提问给 roadhog 吧。
应该是环境哪里不合适了
