### ISSUE TITLE
Android 安卓手机 QQ浏览器 打不开umi 搭建的项目 其他浏览器都行， 应该是国际化的问题

### ISSUE THREAD

**Issue by wenJonSnow** [ant-design/ant-design-pro#7010]
"umi": "^2.9.0",
"umi-plugin-locale": "^2.11.6",
"umi-plugin-react": "^1.15.8"

ie11 
targets: {
ie: 11,
},
提示这个错误：   这个问题已经解决    ie: 9 时 就行或[https://github.com/ant-design/ant-design-pro/issues/2149](https://github.com/ant-design/ant-design-pro/issues/2149)

[React Intl] The Intl APIs must be available in the runtime, and do not appear to be built-in. An Intl polyfill should be loaded. #2149

ie9时 又报这个错误
targets: {
ie: 9,
},
这个错
![21594777864_ pic](https://user-images.githubusercontent.com/24515796/87496064-6a06c500-c685-11ea-8891-2fd192de4025.jpg)

**Comment by chenshuai2144** [comment]
这个估计要自己搞一下， target 不能解决所有的问题。
看看这里
https://github.com/formatjs/formatjs/wiki#getting-started

**Comment by wenJonSnow** [comment]
需要单独引入intl这个包，并且在入口处引用

import 'intl';
import 'intl/locale-data/jsonp/en';
 在src 下新建 global.js 加入上面的 内容就行
