### ISSUE TITLE
像这种ProTable组件有哪些Props在什么地方可以看到？有文档吗？

### ISSUE THREAD

**Issue by Liqiankun** [ant-design/ant-design-pro#7011]

**Comment by afc163** [comment]
https://protable.ant.design/

**Comment by Liqiankun** [comment]
@afc163 这个全部的文档在什么地方啊？我怎么买找到呢？

**Comment by afc163** [comment]
啥？不就是上面发的链接么？

**Comment by Liqiankun** [comment]
@afc163 我的意思是Pro中再次封装的组件的组件文档。Pro中只有一个ProTable有文档吗？

**Comment by afc163** [comment]
还有 https://prolayout.ant.design/ 和 https://prolist.ant.design/

**Comment by Liqiankun** [comment]
@afc163 好奇怪，为啥没有一个Pro Components的文档呢，每个都是单独的，而且在https://pro.ant.design/index-cn也看到不入口？

**Comment by afc163** [comment]
@chenshuai2144 来补一下。

**Comment by Liqiankun** [comment]
@afc163 是的呀，这个真的是太难搞了。根本不知道有这个文档。
