### ISSUE TITLE
mock如果切换到真实服务器请求(回答不要贴文档)

### ISSUE THREAD

**Issue by Liqiankun** [ant-design/ant-design-pro#7015]
### 💻 示例代码
```
dev: {
    '/api': {
      target: 'https://my.api.call/',
      changeOrigin: true,
      pathRewrite: {
        '^/api': '',
      },
    },
  }
```
![截屏2020-07-15 14 11 06](https://user-images.githubusercontent.com/11532418/87509901-1c01b980-c6a5-11ea-9d0a-c194a03e5a8e.png)

**Comment by afc163** [comment]
你不是搞明白了么：https://github.com/ant-design/ant-design-pro/issues/2303#issuecomment-566446412

**Comment by Liqiankun** [comment]
是的，但是现在又不明白了。@afc163 我本地调试应该是可以的，但是现在还是去本地的API

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/5795#issuecomment-568327112

做做个人知识沉淀吧，一条河流踏进去两次。

**Comment by Liqiankun** [comment]
@afc163 这个是部署之后的，我这个是本地开发，测试环境，而且是按照上次的方法设置的还是不行。

**Comment by Liqiankun** [comment]
![截屏2020-07-15 14 43 15](https://user-images.githubusercontent.com/11532418/87512541-c7ad0880-c6a9-11ea-9526-48acc292880b.png)
@afc163 这个地方应该不是或吧？

**Comment by afc163** [comment]
本地开发用 proxy，就是你主楼里的用法。

**Comment by Liqiankun** [comment]
@afc163 但是从我实践的角度来说，应该是设置proxy && `npm run start:no-mock`才能在本地开发中链接到真实的服务器。一个字的差别就是一个小时。很多人的一个小时啊。

**Comment by afc163** [comment]
实测不需要，proxy + npm start 就可以反向代理到真实服务器了。

**Comment by Liqiankun** [comment]
@afc163 你说完之后我又测试了一下。可能是因为我没有重新`npm start`

**Comment by afc163** [comment]
补充了一些文档：https://github.com/ant-design/ant-design-pro-site/commit/f51145b721e5f784f4319bfe51dd163e1883bd11

**Comment by xz9876** [comment]
> 补充了一些文档：[ant-design/ant-design-pro-site@f51145b](https://github.com/ant-design/ant-design-pro-site/commit/f51145b721e5f784f4319bfe51dd163e1883bd11)

不好意思  我的实测不起作用啊  改了proxy和用npm start, 这个方法并没有连接到我给的Api地址

**Comment by afc163** [comment]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/507615/87909877-a4180280-ca9b-11ea-9321-253b21574046.png">

**Comment by kennylbj** [comment]
在V5里，开启了proxy + yarn start，如果mock里有相同的url，会优先使用Mock数据。

能否优先进行反向代理？

**Comment by luozan** [comment]
> 在V5里，开启了proxy + yarn start，如果mock里有相同的url，会优先使用Mock数据。
> 
> 能否优先进行反向代理？

同样的问题，求解
