### ISSUE TITLE
🧐[问题]关于pro v5版本的model

### ISSUE THREAD

**Issue by ImJustAMan** [ant-design/ant-design-pro#7017]
### 🧐 问题描述
为何v5版本项目直接创建会没有models了 是相对来说并不是项目中的必须模块了么？
然后v5中使用的@umijs/plugin-model说是简易数据管理方案 这个插件会不会出现什么问题呢
然后可不可以说明一下这两个模块的差异性
最后一个问题就是如果我还有需要的话 还能不能继续使用plugin-dva的原model形式呢
PS：初尝plugin-model还可以 但是又不清楚未来会怎样

**Comment by ImJustAMan** [comment]
无事发生 我蠢了

**Comment by ImJustAMan** [comment]
还有一个问题 我发现头像下拉框里面有一个使用model的地方传入的是@@initialState 请问这个models到底定义在了哪儿

**Comment by chenshuai2144** [comment]
我们期望是可以用户可以减少全局的数据依赖，很多地方其实是不需要共享的。但是用户信息等信息还是需要全局存放的
`@umijs/plugin-model `就是为了解决数据共享的问题。dva 也是同样的，但是 dva 更加重型，功能更加强大，我们希望可以更加轻量，所以做了` @umijs/plugin-model`


> 初尝plugin-model还可以 

plugin-model 基于 react hooks ，其实是一个 hooks + ts 类型的语法糖，是 react 的标准范式，可以不用担心维护。
