### ISSUE TITLE
🧐[问题] 请问Pro v5.1在什么地方加入从服务器动态获取菜单的代码？

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7018]
### 🧐 问题描述

请问Pro v5.1在什么地方加入从服务器动态获取菜单的代码？

v4.x的方法在v5.1中不能用了。

**Comment by hot588** [comment]
同问！

**Comment by effapp** [comment]
有谁成功了吗？能提供代码片段来参考一下吗？

**Comment by pwh19920920** [comment]
app.tsx的getInitialState()方法声明，然后再app.tsx的layout()方法中使用

**Comment by chenshuai2144** [comment]
app.tsx 中的 layout [配置](https://github.com/ant-design/ant-design-pro/blob/7e40523d79c6ae28fbabf87e42bd55880977e33b/src/app.tsx#L37)
```

const layout = ()=>({
 menuDataRender:()=> menuData
})

```

**Comment by effapp** [comment]
> app.tsx 中的 layout [配置](https://github.com/ant-design/ant-design-pro/blob/7e40523d79c6ae28fbabf87e42bd55880977e33b/src/app.tsx#L37)
> 
> ```
> 
> const layout = ()=>({
>  menuDataRender:()=> menuData
> })
> ```

报错 ： Object literal may only specify known properties, and 'renderMenuData' does not exist in type 'BasicLayoutProps'.

代码如下：

export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings };
}): BasicLayoutProps => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,
    renderMenuData: ()=> { 
      return initialState.menu;
    },
    ...initialState?.settings,
  };
};

使用v5.1
