### ISSUE TITLE
🧐[问题] moment.js 国际化失效问题

### ISSUE THREAD

**Issue by czhou29** [ant-design/ant-design-pro#7020]
### 🧐 问题描述

类似于示例页面https://preview.pro.ant.design/list/search/projects 中 当选择简体中文时 每个Card 人物头像的左侧可以显示 几秒钟 繁体中文时也正确，而选择en-US时会是随机的语言 在我的项目中显示的是葡萄牙语的 há 20 anos 而不是英文 从右上角的小铃铛通知中也能看出来 当选择英文的时候 打开还是会显示3年前 而选择 葡萄牙语的时候可以生效

**Comment by chenshuai2144** [comment]
现在刷新页面了
