### ISSUE TITLE
🧐[问题]ColumnsState,columnsStateMap,onColumnsStateChange都是做什么的呢？不太明白

### ISSUE THREAD

**Issue by LOVEwitch** [ant-design/ant-design-pro#7021]
### 🧐 问题描述
表头筛选的枚举值需要在后端获取，是否能用到以上3个属性呢？

**Comment by chenshuai2144** [comment]
现在表头筛选还不支持从服务器获取。

columnsStateMap 是控制列的状态的，可以看这个 demo

https://protable.ant.design/example#%E5%8F%97%E6%8E%A7%E6%A8%A1%E5%BC%8F

**Comment by LOVEwitch** [comment]
已经解决了，可以通过ant-design的filters解决：在服务器获取到表头信息后，通过state给到表头
