### ISSUE TITLE
👑 [需求]SiderBar收起时的style

### ISSUE THREAD

**Issue by ZidiHu** [ant-design/ant-design-pro#7022]
### 🥰 需求描述

最近做的项目有调整siderBar style的需求，现在的的效果是这样的。

展开时：
<img width="322" alt="Screen Shot 2020-07-16 at 2 37 19 pm" src="https://user-images.githubusercontent.com/50161886/87627816-ee834180-c772-11ea-9213-17a5c0f2397e.png">

收起时：
<img width="148" alt="Screen Shot 2020-07-16 at 2 37 27 pm" src="https://user-images.githubusercontent.com/50161886/87627895-1ecae000-c773-11ea-846d-5fa1fd8f233b.png">
尝试了很多方法都没有办法把红框里的那根蓝线去掉，请问有什么方法可以盖掉那根蓝线吗？

### 🚑 其他信息

siderBar style是在global.less里改的，代码如下
<img width="624" alt="Screen Shot 2020-07-16 at 2 49 24 pm" src="https://user-images.githubusercontent.com/50161886/87628137-a9134400-c773-11ea-9f56-223347e401ab.png">

**Comment by LOVEwitch** [comment]
可以直接写样式覆盖

**Comment by ZidiHu** [comment]
> 可以直接写样式覆盖

请问具体怎么改样式呢？我试过加个边框 但是盖不住这个蓝线
不好意思可能我没想到什么好的解决办法，方便具体说一下吗

**Comment by chenshuai2144** [comment]
最简单的 `margin-left : -1px`
