### ISSUE TITLE
预览链接里面的流程图哪去了，clone下载项目里面没有看到呀🧐[问题]

### ISSUE THREAD

**Issue by walnutYa** [ant-design/ant-design-pro#7026]
### 🧐 问题描述
预览链接里面的 图形编辑器/流程编辑器 是用的什么包做的啊？bpmn吗？很想看下你的demo。但是项目下载下来后，列表里面没有...求解惑

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/33886874/87653950-d9b1a880-c788-11ea-95b3-92c17e476305.png)
![image](https://user-images.githubusercontent.com/33886874/87654004-eb934b80-c788-11ea-868d-583aaed05689.png)

**Comment by xiaohuoni** [comment]
你好，所有的页面都整理在了 https://github.com/ant-design/pro-blocks 
你可以执行相关命令将所有页面下载下来。

**Comment by walnutYa** [comment]
感谢🤝
________________________________
发件人: 陈小聪 <notifications@github.com>
发送时间: 2020年7月16日 18:37
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com>
抄送: walnutYa <zhangh_666@outlook.com>; Author <author@noreply.github.com>
主题: Re: [ant-design/ant-design-pro] 预览链接里面的流程图哪去了，clone下载项目里面没有看到呀🧐[问题] (#7026)


你好，所有的页面都整理在了 https://github.com/ant-design/pro-blocks
你可以执行相关命令将所有页面下载下来。
