### ISSUE TITLE
🧐[问题] npm create umi创建项目选择js及antd4时出错

### ISSUE THREAD

**Issue by zhangfeng993** [ant-design/ant-design-pro#7027]
### 🧐 问题描述

npm create umi创建项目选择js及antd4时出错

### 🚑 其他信息

![错误截图](https://user-images.githubusercontent.com/39079641/87752476-0d490d00-c833-11ea-95f5-c7a761e1e9ca.png)

**Comment by chenshuai2144** [comment]
看起来是全局的 babel 的问题，你可以 
```
npm -g ls | grep -v 'npm@' | awk '/@/ {print $2}' | awk -F@ '{print $1}' | xargs npm -g rm
```
 来删除所有的全局依赖，也可以只删除 babel 系列的。
