### ISSUE TITLE
🎉[项目模板] 对于不想使用Ant Degsin layout Pro的童鞋可以看看

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#7028]
对于不需要或者不想使用antd pro,完全使用antd组件手撸页面的同学可以看看这个模板.
基于Umi 3.x和V5的模板修改而来.
[react-app-template](https://github.com/joesdu/react-app-template-umi)
项目中扩展了部分JavaScript基础类型的原型链.紧跟V5版本代码和Umi以及Antd最新版本.
当然也可以自己引入pro的内容来实现pro的布局.
含有简单的登陆页面和create-react-app经典首页.

**Comment by li515422618** [comment]
跑起来了，给大佬手动点赞o(￣▽￣)ｄ

**Comment by joesdu** [comment]
> 跑起来了，给大佬手动点赞o(￣▽￣)ｄ

😁😁

**Comment by xiaohuoni** [comment]
有什么差异点嘛？

**Comment by joesdu** [comment]
> 有什么差异点嘛？

要说差异嘛，也没什么太大的，要说没有什么差异也还真有那么些差异

**Comment by ImJustAMan** [comment]
> > 有什么差异点嘛？
> 
> 要说差异嘛，也没什么太大的，要说没有什么差异也还真有那么些差异

emmmm 是对pro的简易封装版本？还是只是单纯的只是细微差别那种

**Comment by joesdu** [comment]
> > > 有什么差异点嘛？
> > 
> > 要说差异嘛，也没什么太大的，要说没有什么差异也还真有那么些差异
> 
> emmmm 是对pro的简易封装版本？还是只是单纯的只是细微差别那种

去掉了pro，和dva，只保留了umi和antd的引用，当然antd也可以去掉😂

**Comment by joesdu** [comment]
> > > 有什么差异点嘛？
> > 
> > 要说差异嘛，也没什么太大的，要说没有什么差异也还真有那么些差异
> 
> emmmm 是对pro的简易封装版本？还是只是单纯的只是细微差别那种

算是对umi的一个简易封装吧，

**Comment by ImJustAMan** [comment]
> > > > 有什么差异点嘛？
> > > 
> > > 
> > > 要说差异嘛，也没什么太大的，要说没有什么差异也还真有那么些差异
> > 
> > 
> > emmmm 是对pro的简易封装版本？还是只是单纯的只是细微差别那种
> 
> 去掉了pro，和dva，只保留了umi和antd的引用，当然antd也可以去掉😂
emmmmmm 没了antd突然怀疑起我到底来干什么了

**Comment by joesdu** [comment]
> 起我到底来干什么了

😂😂😂

**Comment by xiaohuoni** [comment]
> > 有什么差异点嘛？
> 
> 要说差异嘛，也没什么太大的，要说没有什么差异也还真有那么些差异

没看出来

**Comment by joesdu** [comment]
我这个仅仅是作为一个模板项目,去掉了layout pro和dva引入的一些东西.主要还是用的Umi3.x的底层框架来实现的,所以和官方的那个V5看起来没有什么本质上的差别.本身Umi底层框架用来开发就已经很OK了.该模板项目主要是用于不需要使用pro的那种布局的人用来快速创建项目的.若是后期我学会了Umi的插件开发,或许我根据其他需求写点什么不一样的东西.,但是目前看起来这个模板项目就是这样了.所有的配置都遵循Umi的文档说明.
