### ISSUE TITLE
请求超时功能 可以不可以添加一下

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#703]
2秒中请求不到数据就显示请求超时？？

**Comment by chenshuai2144** [comment]
你自己封装一下fetch。
github上有很多库。
试着搜索一下 `fetch timeout`

**Comment by WuJiY** [comment]
经常504，我直接postman 里测试接口响应几十ms，不知道是哪个环节问题？

**Comment by chenshuai2144** [comment]
Mock接口？

**Comment by WuJiY** [comment]
这么晚还在啊…… 代理

**Comment by chenshuai2144** [comment]
直接访问代理呢？ 我们配置了1000的延时

**Comment by afc163** [comment]
进 mock 文件里调试一下。

**Comment by WuJiY** [comment]
一个是 这样 设置
// .roadhogrc.mock.js
export default {
'GET /api/(.*)': 'https://your.server.com/',
};
一种在.webpackrc里设置proxy 两种方式。都会出现这种情况。

**Comment by WuJiY** [comment]
这个是设置 proxy 里用经常出现这样 504 
[HPM] Error occurred while trying to proxy request manager/currentUser from localhost:8000 to http://api.xxxxx.com/backend/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by WuJiY** [comment]
如果在mock里设置的话，这样设置的，应该没问题吧。经常出现504
![image](https://user-images.githubusercontent.com/183884/35603103-ade75ec8-0676-11e8-959a-10cec691fa4d.png)

**Comment by WuJiY** [comment]
express-http-proxy timed out your request after undefinedms.

**Comment by ccOnTheWay** [comment]
> 单独调用接口可以正常返回，使用 该框架中的 fetch 调用 超过 3s 就 返回 null ， 状态码 还是 200，跪求

遇到同样的问题解决了吗
