### ISSUE TITLE
🐛[BUG] v5 权限页面非admin能够直接访问

### ISSUE THREAD

**Issue by zlllya** [ant-design/ant-design-pro#7030]
### 🐛 bug 描述
安装最新的v5版本，无任何改动，登录user账户，能够直接访问/admin/sub-page页面，虽然菜单已经隐藏了admin页面，但是通过url能够直接访问，v4版本则会显示403页面

### 🏞 期望结果
能够显示403

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0-alpha.0]
- umi 版本 3.1.2
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![WX20200717-170413](https://user-images.githubusercontent.com/6331020/87769038-99692d80-c84f-11ea-9b66-0787db0d277b.png)

**Comment by chenshuai2144** [comment]
fixed by plugin-layout

**Comment by holiday12138** [comment]
直接改localstorage 也能免登陆变成admin吧
