### ISSUE TITLE
🧐[问题]git pre commit的时候出现eslint错误

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#7032]
### 🧐 问题描述
今天刚安装的antPro5 啥都没动 git 提交的时候预检查出现这个问题，是我vscode配置问题？还是...？  
<img width="906" alt="截屏2020-07-18 上午12 07 16" src="https://user-images.githubusercontent.com/183884/87807756-41e8b300-c88b-11ea-9a7d-69e6dd54305a.png">

**Comment by chenshuai2144** [comment]
这个是一个 bug，你可以 -n 先跳过一下，是 eslint-ts 新搞的东西
