### ISSUE TITLE
I was literally searching for this

### ISSUE THREAD

**Issue by pkdcryptos** [ant-design/ant-design-pro#7037]
I was really searching for last one month for cra kind of implementation for ant design pro and finally found the below:
https://github.com/HeavyShell/ant-design-pro
The above is roadhog based, but can be used for cra type project too.

With this, the layout , sidebar, top bar can be customized and also faster loads compare to umi based structure. 

Hope it helps somebody looking for the same.

Unfortunately there is no mention of this repo in this issues list.

Thanks

**Comment by chenshuai2144** [comment]
give a pr？
