### ISSUE TITLE
建议：添加重定向动画

### ISSUE THREAD

**Issue by teeemooo** [ant-design/ant-design-pro#704]
目前重定向后会出现白板 建议添加一个loading更加友好

**Comment by chenshuai2144** [comment]
是因为
window.location.reload()

**Comment by teeemooo** [comment]
果然非常粗暴  但这个pro不应该是最佳实践么

**Comment by chenshuai2144** [comment]
主要是因为权限的原因。。。
第二阶段会改成redux，不会这么粗暴了
