### ISSUE TITLE
👑 [需求] 提供几个数据大屏的展示页面可以吗？BI 展示页面实在太少了

### ISSUE THREAD

**Issue by 693614965** [ant-design/ant-design-pro#7040]

**Comment by hot588** [comment]
我也很需要！！！有的话，你也给我们提供下哦

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是它已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but it has not responded for a long time. We will temporarily close it
