### ISSUE TITLE
 npm start  报错 error  in ./node_modules/antd/es/dropdown/style/index.less 

### ISSUE THREAD

**Issue by shiminan** [ant-design/ant-design-pro#7041]
error  in ./node_modules/@ant-design/pro-layout/es/BasicLayout.less

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No valid exports main found for '/Users/shimin.an/web_react_app/antd_pro_demo/node_modules/colorette'

npm start 的时候报了许多这样的错误，请问是哪里出问题了？

**Comment by zxlzl** [comment]
遇到了同样的错误，请问怎么解决的呢？

**Comment by shiminan** [comment]
跟 node 版本有关，你换 v12  然后删除项目路径下的node_modules文件夹重新安装一下依赖应该就好了

**Comment by shiminan** [comment]
> 遇到了同样的错误，请问怎么解决的呢？
跟 node 版本有关，你换 v12 然后删除项目路径下的node_modules文件夹重新安装一下依赖应该就好了
