### ISSUE TITLE
🐛[BUG]Ant Design Pro 预览 demo 无法进入，登录报错

### ISSUE THREAD

**Issue by weiliang903** [ant-design/ant-design-pro#7042]
### 🐛 bug 描述

`https://preview.pro.ant.design/user/login` 打开后默认跳转登录界面，登录接口报 405

![截屏2020-07-20 17 30 17](https://user-images.githubusercontent.com/20644345/87922577-c36c5b00-caae-11ea-9c9c-fa9c265e894f.png)

**Comment by pxim** [comment]
同样遇到这种情况

**Comment by SimonAlong** [comment]
同样遇到这种情况，有没有默认的账号和密码

**Comment by asanjorjo** [comment]
Same bug for me, can't login with the default credentials given.
`admin` or `user`
`ant.design`

It always gives me an error. Please check and fix. Thank you.

**Comment by JarvisArt** [comment]
本地的antd pro项目也会出现这种情况

**Comment by tortorse** [comment]
同样的问题，而且并非账户认证所致。通过路由直接访问<https://preview.pro.ant.design/dashboard/analysis>，github page 404


![image](https://user-images.githubusercontent.com/10540493/87997569-0880a380-cb28-11ea-94ae-249556251648.png)

**Comment by tortorse** [comment]
临时解决方案，下载本仓库中的gh-pages分支<https://github.com/ant-design/ant-design-pro/tree/gh-pages>中所有文件
本地开启一个 webserver，即可预览

**Comment by yangdachu** [comment]
+1

**Comment by MBearo** [comment]
+1

**Comment by chenshuai2144** [comment]
CNAME 被抢走了  ,在找 github 申诉

**Comment by chenshuai2144** [comment]
找回来了

**Comment by lin-mt** [comment]
> 找回来了，已部署最新的

![image](https://user-images.githubusercontent.com/58337359/108578856-300a4980-735f-11eb-8522-59ba74aa98e1.png)
又又又不行了

**Comment by guomaoqiu** [comment]
这个问题到目前都没解决？？？？？
![image](https://user-images.githubusercontent.com/9714859/126334575-7d49d71b-76b6-4e08-ab2c-845144ff6655.png)
