### ISSUE TITLE
🐛[BUG]Using this API will cause automatic refresh when switching languages, please use useIntl or injectIntl.

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7049]
### 🐛 bug 描述
Using this API will cause automatic refresh when switching languages, please use useIntl or injectIntl.

### 📷 复现步骤
 run start --scripts-prepend-node-path=auto

### 🏞 期望结果
解决这个问题

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.0.0
- umi 版本 3.2.3
- 浏览器环境 chrome 81.0.4044.113
- 开发环境 [e.g. mac OS] win7

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5111701/88004791-60c0a100-cb3a-11ea-83eb-728bf553e3cb.png)

**Comment by chenshuai2144** [comment]
you should use `useIntl` ，don't use  `formatMessage`

**Comment by FreeCodersix** [comment]
> you should use `useIntl` ，don't use `formatMessage`

请问在类组件里怎么使用useIntl

**Comment by chenshuai2144** [comment]
insertIntl

**Comment by FreeCodersix** [comment]
> insertIntl

可以给个简单的用法示例吗

**Comment by FreeCodersix** [comment]
> insertIntl

我找了很多文档，但是都写都稀里糊涂的，所以劳烦您指教一下

**Comment by chenshuai2144** [comment]
```
const page=({intl})=>{
 console.log(intl)
}


export default injectIntl(page);
```
