### ISSUE TITLE
一个dashboard 中多个 table的实现方式

### ISSUE THREAD

**Issue by xueye515** [ant-design/ant-design-pro#705]
问题:
     dashboard 中存在十多个table报表，每个table的数据量较大，dashboard加载时较慢。想实现每个table单独请求数据，单独加载而不影响整个dashboard的显示(请求完一个table,显示一个，没获取到数据的table loading)

现在的解决办法：
 在dashboard对应的model层中请求1 返回所有table的id及布局，然后循环异步根据Id请求table数据，存储在key-value对象中。 这样解决后 每个table请求完都会更新dashboard的state，会导致dashboard不断刷新，虽然这样table会一个个显示，但是所有table加载完成之前，整个dashboard都属于卡死状态。

想问一下这种情况怎么设计，有什么比较好的设计方案吗？

**Comment by chenshuai2144** [comment]
放到redux中。
请求最好做队列请求。你要优化涉及的还挺多的

**Comment by xueye515** [comment]
接触react 就直接用的dva antd 这一套东西，感觉挺容易上手的，所以redux router之类的只是泛泛了解了下。
劳烦能说一下具体实现技术点吗，我好有针对性的查一下。

**Comment by chenshuai2144** [comment]
这个，我也不知道从何说起。涉及的太多了。
先看看redux的资料。 再看看 懒加载这些的实现。

查一查吧。这种文章估计不少

**Comment by xueye515** [comment]
好的，多谢
