### ISSUE TITLE
🧐[问题]ChunkLoadError: Loading chunk 2 failed

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#7053]
### 🧐 问题描述
ant-design-pro: v5
"umi": "^3.1.0",
开发平台：mac,
浏览器：chrome，

运行中出现 ChunkLoadError: Loading chunk，
再次之前我做了打包文件zip的压缩，
chainWebpack(memo) {
    memo.plugin('CompressionPlugin').use(
      new CompressionPlugin({
        filename: '[path].gz[query]',
        algorithm: 'gzip',
        // test: productionGzipExtensions,
        test: /\.js$|\.css$|\.html$/,
        // 只处理大于xx字节 的文件，默认：0
        threshold: 10240,
        // 示例：一个1024b大小的文件，压缩后大小为768b，minRatio : 0.75
        minRatio: 0.8, // 默认: 0.8
      })
    );
memo.merge({
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: 'all',
          minSize: 30000,
          minChunks: 3,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      }
    });

![image](https://user-images.githubusercontent.com/23183393/88010244-00842c00-cb47-11ea-9c3f-8c7212bdb42d.png)
却得到这样的提示。

我尝试过清楚浏览器缓存，在issues中搜索没发现v5版本的问题

**Comment by UnicornXU** [comment]
最后是解决了么

**Comment by xyy7260** [comment]
@UnicornXU  好像解决了， 具体好像是配置配置错了

**Comment by UnicornXU** [comment]
> 

可以看一下么
