### ISSUE TITLE
👑 [需求]能否增加异步权限校验的功能

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7054]
### 🥰 需求描述

能否增加异步权限校验的功能？

把页面访问权限的校验逻辑放在服务端进行，返回客户端校验成功或失败的信息，希望Access具备这样的异步远程校验功能，在校验过程中，显示一个Spin.

**Comment by chenshuai2144** [comment]
v5总已经支持了。
https://beta-pro.ant.design/docs/authority-management-cn
