### ISSUE TITLE
🧐[问题]menu 里item上ico不显示，以及切换按钮样式问题？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7057]
### 🧐 问题描述

用的最新的 ant-design-pro all-blocks的代码，现在menu的第二级菜单上不显示ico，并且切换按钮跑到左下边了，如图：
![image](https://user-images.githubusercontent.com/5111701/88124381-8f547f80-cbff-11ea-920e-f987dfa08ce7.png)

以前的all-blocks版本里，是这样的效果，如图：
![image](https://user-images.githubusercontent.com/5111701/88124447-bca12d80-cbff-11ea-9bf5-4ee747c9f6ec.png)

请问在使用最新 blocks版本的基础上，我想实现图二的功能，应该改哪里。

### 💻 示例代码

关于这方面的代码，都是all-blocks里默认的，目前没改动。

**Comment by chenshuai2144** [comment]
如果你不想改动就不要升级 6.x，但是可能无法修复 bug

新的 6.x 的设计已经修改，更加的紧凑，提升了信息密度。
