### ISSUE TITLE
🧐[问题]histroy模式，页面第一次设置hash时会触发页面刷新

### ISSUE THREAD

**Issue by natsupan** [ant-design/ant-design-pro#7058]
### 🧐 问题描述

histroy模式，当页面加载完成后，第一次设置hash会使组件umount，第二次设置就不会。请问下这是什么原因啊？目前是不想让组件umount。

### 💻 示例
打开  https://preview.pro.ant.design   
在控制台中输入window.location.hash = 'test'，即可观察到。

**Comment by chenshuai2144** [comment]
是umi的问题，不要配置重定向就不会触发

**Comment by shaohuatsou** [comment]
> 是umi的问题，不要配置重定向就不会触发

你说的是路由里面的redirect吗？
这个我没有配置啊

**Comment by shaohuatsou** [comment]
> ### 🧐 问题描述
> histroy模式，当页面加载完成后，第一次设置hash会使组件umount，第二次设置就不会。请问下这是什么原因啊？目前是不想让组件umount。
> 
> ### 💻 示例
> 打开 https://preview.pro.ant.design
> 在控制台中输入window.location.hash = 'test'，即可观察到。

你解决了吗？@natsupan

**Comment by htank-wang** [comment]
同样问题，上线了的项目，不好升级umi
