### ISSUE TITLE
🧐[问题]分支里 v5和v5.1有啥区别？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7059]
### 🧐 问题描述

分支里 v5和v5.1有啥区别？

**Comment by xiaohuoni** [comment]
v5 用的是 preset-react 的库，是最佳实践。因为不支持约定式路由，动态菜单设置比较复杂的问题，我搞了v5.1的方案。

|对比项| v5 | v5.1 |
| :-: | :-:   | :-:  |
|插件|plugin-access、plugin-layout  | plugin-access-layout |

**Comment by pxim** [comment]
> v5 用的是 preset-react 的库，是最佳实践。因为不支持约定式路由，动态菜单设置比较复杂的问题，我搞了v5.1的方案。
> 
> 对比项	v5	v5.1
> 插件	plugin-access、plugin-layout	plugin-access-layout



> v5 用的是 preset-react 的库，是最佳实践。因为不支持约定式路由，动态菜单设置比较复杂的问题，我搞了v5.1的方案。
> 
> 对比项	v5	v5.1
> 插件	plugin-access、plugin-layout	plugin-access-layout

了解了，谢谢
