### ISSUE TITLE
菜单配置中菜单的children 添加hideInMenu: true后仍然会显示下拉箭头

### ISSUE THREAD

**Issue by qq328180750** [ant-design/ant-design-pro#706]
菜单配置中菜单的children 添加hideInMenu: true后仍然会显示下拉箭头，children只有唯一一个，请问该如何解决呢
![qq 20180116111307](https://user-images.githubusercontent.com/33867025/34970253-40b7b06a-faae-11e7-8bb1-68cda2ef3dcc.jpg)

**Comment by ddcat1115** [comment]
有 children（哪怕只有一个）也应该有箭头啊，如果一个children都没有，直接隐藏父级不是更好？

**Comment by qq328180750** [comment]
@ddcat1115 请问下，如果隐藏了，面包屑那里怎么做处理呢，想让他在这个菜单的下一级

**Comment by ddcat1115** [comment]
menu隐藏不会影响面包屑的，如果你这级有对应路由，面包屑就会默认展示

**Comment by qq328180750** [comment]
@ddcat1115 好，谢谢你，我再调整调整
