### ISSUE TITLE
🐛 npm script lint-staged throws Parsing error

### ISSUE THREAD

**Issue by rbrugnollo** [ant-design/ant-design-pro#7061]
### 🐛 bug description

npm run lint-staged throws the error: 

```
C:\Users\user\src\myApp.eslintrc.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided
```

### 📷 Steps to reproduce

1. Create a new project with `yarn create umi myApp` and select the options:
- ant-design-pro
- Pro V4
- TypeScript
- simple
2. go to myApp folder
3. run `npm run lint-staged`

### 🏞 Expected results

`npm run lint-staged` runs with no errors

### © Version Information

-Ant Design Pro version: 4.0.0
-Umi version: 3.2.0
-Windows 10

**Comment by chenshuai2144** [comment]
在 tsconfig 中 include 一下 myApp.eslintrc.js

**Comment by steadyzeus** [comment]
Solved by adding .eslintignore

/*.*

**Comment by KingThq** [comment]
> 在 tsconfig 中 include 一下 myApp.eslintrc.js

在 tsconfig 中 include 之后，报错的文件更多了，怎么解决？

**Comment by erlei22** [comment]
> 在 tsconfig 中 include 一下 myApp.eslintrc.js

我也没解决，报错更多了

**Comment by Zach-Lu** [comment]
我也是这个问题，没解决。
