### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by JiangLikang** [ant-design/ant-design-pro#7069]
### 🥰 需求描述
Pro什么时候提供多标签页的功能。现在要实现多标签页需要在Pro的基础上自己实现，建议Pro提供多标签页的功能开关，后台管理系统这个需求真的很常见！

**Comment by afc163** [comment]
Duplicate of #220

**Comment by Fengly0503** [comment]
自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs
