### ISSUE TITLE
为什么不直接定制create-react-app，而是搞一个roadhog出来？

### ISSUE THREAD

**Issue by henrydf** [ant-design/ant-design-pro#707]
ant-design-pro是个不错的东东，里面有不少很棒的东东，比如ant-design、dva。
有一点不明白的就是为什么要造一个roadhog这种东西，感觉很多底层功能应该都是扒的create-react-app。那为什么不能直接用呢？
毕竟create-react-app也是可以自定制的！参考后面的文章，自定义一套模板就可以了。定制化程度非常高。
https://auth0.com/blog/how-to-configure-create-react-app/
这么做的花，还可以隐藏很多细节，对新手入门更加的友好。

**Comment by afc163** [comment]
关于 roadhog 和 create-react-app 的关系可以参考：

https://github.com/sorrycc/blog/issues/17
https://github.com/sorrycc/blog/issues/15

简单的说就是，cra 官方的定制化方案都是基于 npm run eject 的，官方也不推荐 eject。eject 出来的 webpack.config.js 的配置对于我们太复杂了，全栈研发人员根本 hold 不住。

**Comment by henrydf** [comment]
@afc163 你可以看一下我给的链接，这个解决方案不是用eject的。而是基于--scripts-version的。

**Comment by tqcc** [comment]
类似copyPublicFolder的处理在哪里？ 不想copy public的文件 到 dist ， 应该怎么配置？
