### ISSUE TITLE
🧐[问题]高级表单AdvancedForm提交时，怎么获取TableForm的所有数据？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7070]
### 🧐 问题描述

高级表单AdvancedForm，点击提交按钮时，怎么获取TableForm的所有数据？

### 💻 示例代码

![image](https://user-images.githubusercontent.com/5111701/88259968-ffddc800-ccf5-11ea-80a1-ab7f8f1eb20e.png)

**Comment by chenshuai2144** [comment]
可以使用 onChange 记下数据
