### ISSUE TITLE
🐛[BUG]使用默认模板运行报错

### ISSUE THREAD

**Issue by Hareis** [ant-design/ant-design-pro#7076]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/11290701/88354149-93fd6d00-cd92-11ea-97b4-529bd2a4ae83.png)

### 📷 复现步骤
cmd中运行 ``npm create umi``
? Select the boilerplate type ant-design-pro                                                                            
? 🧙 Be the first to experience the new umi@3 ? Pro V4                                                                  
? 🤓 Which language do you want to use? TypeScript                                                                     
 ? 🚀 Do you need all the blocks or a simple scaffold? complete                                                          
> 🙈 complete mode can only use the version of antd@4 
.....                                                      
> 🚚 clone success                                                                                                      
> Clean up...                                                                                                          
 ✨ File Generate Done 

创建完demo后 使用npm run dev
能正常编译完成 但是 打开localhost：8080/ 后 服务崩溃
console 中提示如上错误信息

尝试打开此文件后``node_modules\@umijs\server\lib\Server\Server.js:314:29`` 发现确实缺少URL的定义

**Comment by FAOfao931013** [comment]
问下 后来解决了吗 我也遇到这个问题了

**Comment by FAOfao931013** [comment]
> 问下 后来解决了吗 我也遇到这个问题了

已自行解决，切到 node 10 即可
