### ISSUE TITLE
🧐[问题] Ant Design Pro：只有 pages 或 page 目录下的页面才能插入资产

### ISSUE THREAD

**Issue by MrLhn** [ant-design/ant-design-pro#7078]
### 🧐 Ant Design Pro：只有 pages 或 page 目录下的页面才能插入资产

当我看着API 使用AntDesignPro V4 版本区块功能时,我始终不能成功添加资产,目前使用过项目重启, 在新建页面对应的 xxx.tsx 文件，找到 PageHeaderWrapper 标签,在里面随便加点东西,保存后刷新页面等方式,仍然无法插入资产,求解决
### 💻 示例代码
我严格按照AntDesignPro的文档进行操作,如有解决方案 不胜感激
![image](https://user-images.githubusercontent.com/58026980/88356226-b5ae2280-cd99-11ea-8e46-2258025efce3.png)

**Comment by hot588** [comment]
已经发布了解决方案了，多搜搜

**Comment by gameruleCEO** [comment]
https://blog.csdn.net/shujudaniu/article/details/106080987

看看我的这篇文章

**Comment by chenshuai2144** [comment]
干掉 babel cache，或者重启一下就好了

**Comment by wangzhoubin** [comment]
去掉 PageContainer上面的content
