### ISSUE TITLE
🐛[BUG]  V5版本中未登录情况下，能进入welcome页面

### ISSUE THREAD

**Issue by zhangshuling** [ant-design/ant-design-pro#7079]
1.  修改config.js ,增加   
 history: {
    type: 'hash'
  },

2. 启动工程

3. 直接在地址栏 输入 
http://localhost:8001/#/welcome  第一次会正常跳转到 登录页面， 不做任何登录操作

4. 再在地址栏输入 http://localhost:8001/#/welcome， 会发现进入了 welcome页面, 此时在地址栏回车，或者刷新页面，会再次跳转到 登录页面 (相当于再次回到了步骤 3)

**Comment by shaohuatsou** [comment]
这么快就用上V5了啊

**Comment by chenshuai2144** [comment]
修复了

**Comment by zhangshuling** [comment]
redirect 丢了？ 
登录成功后需要返回的页面丢了

**Comment by zhangshuling** [comment]
Safari 登录成功,   页面不跳转, 控制台也没报错
Safari 版本13.1.1 (15609.2.9.1.2)
