### ISSUE TITLE
🧐[问题]dva全局model和页面model有什么区别？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#7081]
model 还分为 src/models/*.js 目录下的全局 model，和 src/pages/**/models/*.js 下的页面 model

全局model和页面model的区别是什么？

**Comment by joesdu** [comment]
> model 还分为 src/models/_.js 目录下的全局 model，和 src/pages/**/models/_.js 下的页面 model
> 
> 全局model和页面model的区别是什么？

就是一个项目构架的思想问题,本质上没啥实际差别.

**Comment by shaohuatsou** [comment]
> > model 还分为 src/models/_.js 目录下的全局 model，和 src/pages/**/models/_.js 下的页面 model
> > 全局model和页面model的区别是什么？
> 
> 就是一个项目构架的思想问题,本质上没啥实际差别.

就是说umi都会自动引入，也没有访问限制或者是按需加载的区别对吧？

**Comment by joesdu** [comment]
> > > model 还分为 src/models/_.js 目录下的全局 model，和 src/pages/**/models/_.js 下的页面 model
> > > 全局model和页面model的区别是什么？
> > 
> > 就是一个项目构架的思想问题,本质上没啥实际差别.
> 
> 就是说umi都会自动引入，也没有访问限制或者是按需加载的区别对吧？

没有，就是在引用的时候会显得很难看😂

**Comment by shaohuatsou** [comment]
> > > > model 还分为 src/models/_.js 目录下的全局 model，和 src/pages/**/models/_.js 下的页面 model
> > > > 全局model和页面model的区别是什么？
> > > 
> > > 
> > > 就是一个项目构架的思想问题,本质上没啥实际差别.
> > 
> > 
> > 就是说umi都会自动引入，也没有访问限制或者是按需加载的区别对吧？
> 
> 没有，就是在引用的时候会显得很难看😂

感谢解答。

**Comment by pkdcryptos** [comment]
Pages models load when page is accessed. Src/models automatically start with yarn start

**Comment by pkdcryptos** [comment]
This is very critical and importabt difference. If u want to switch umi to create react app, u need to apply these initially with dva call and page models can be loaded when page is loaded

**Comment by shaohuatsou** [comment]
> This is very critical and importabt difference. If u want to switch umi to create react app, u need to apply these initially with dva call and page models can be loaded when page is loaded

Thank you very much.

**Comment by joesdu** [comment]
> > This is very critical and importabt difference. If u want to switch umi to create react app, u need to apply these initially with dva call and page models can be loaded when page is loaded
> 
> Thank you very much.

thx
