### ISSUE TITLE
🧐[问题]如何枚举@ant-design/icons的所有图标？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#7083]
请问如何枚举@ant-design/icons的所有图标？

**Comment by shaohuatsou** [comment]
已经枚举出所有的icon了

**Comment by rabbitlhf** [comment]
求教下！

**Comment by shaohuatsou** [comment]
> 求教下！

![image](https://user-images.githubusercontent.com/50793943/89411913-ca56c700-d758-11ea-9f65-987fbdfa6c51.png)
