### ISSUE TITLE
🧐[问题]dev环境下第一次进入页面点击菜单整个页面刷新

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#7084]
第一次进入主页面，从服务器请求了菜单，单击任意一个菜单整个页面全部刷新，之后再点击其它菜单功能都正常。
menu中的item我只设置了 name:，path，icon，children  不知道是什么原因造成的？

**Comment by chenshuai2144** [comment]
dep of https://github.com/ant-design/ant-design-pro/issues/7058
