### ISSUE TITLE
🧐[问题]为啥刷新页面的时候会自动在地址后面加斜杠？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#7085]
原地址 http://www.xxxx.com/user  刷新页面变成了 http://www.xxxx.com/user/

**Comment by chenshuai2144** [comment]
这个是个很棒的 feature
https://qastack.cn/webmasters/35643/is-trailing-slash-automagically-added-on-click-of-home-page-url-in-browser
