### ISSUE TITLE
🐛[BUG]V5菜单传参问题

### ISSUE THREAD

**Issue by XiaYaXia** [ant-design/ant-design-pro#7086]
### 🐛 bug 描述
服务器获取到的菜单 带参数?id=113等   点击菜单，参数被过滤，无法实现PATH传参  试过:113 等方式 都不行， 路由是改的约定路由   如何实现服务器菜单带传参功能？ 还是传参有其他约定参数？

**Comment by XiaYaXia** [comment]
没人知道吗？？

**Comment by XiaYaXia** [comment]
@hardyfan  transformRoute.js  67 行  过滤掉了   问题怎么传出来

**Comment by XiaYaXia** [comment]
@hardyfan `function stripQueryStringAndHashFromPath(url) {
  return url.split('?')[0].split('#')[0];
}`

**Comment by XiaYaXia** [comment]
@chenshuai2144 antd大佬 可不可以在menuDataRender 加一个接收参数的 点击菜单传给页面   我用的FormRender表单  schema-generator线上生成表单   path 路径都是一样的  只需要参数不一样  key是带参path 就可以  有没有解决方案呢

**Comment by XiaYaXia** [comment]
已自行解决， 如官方添加此功能再改回

**Comment by hufengchao** [comment]
怎么解决的
