### ISSUE TITLE
🐛[BUG]  登录问题

### ISSUE THREAD

**Issue by zhangshuling** [ant-design/ant-design-pro#7087]
https://github.com/ant-design/ant-design-pro/issues/7079 修复后续 又遇上两个问题

1. redirect 丢了？
登录成功后需要返回的页面丢了
例如，从 http://localhost:8000/#/account/settings 退出，但是 退出后 跳转到 登录页面时 redirect 没了

2. Safari 登录成功, 页面不跳转, 控制台也没报错
Safari 版本13.1.1 (15609.2.9.1.2)

**Comment by zhangshuling** [comment]
大致原因已经找到了， 在history.push外面加个延时调转会发现，登录成功后，调用  replaceGoto(); 方法其实成功跳转到了 redirect 页面， refresh() 方法调用 也执行了 app.tsx 里面的 getInitialState()方法， 后面也会查询到 相关的登录用户信息
表面是没什么毛病的

`      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser?.userid && history.location.pathname !== '/user/login') {
        setTimeout(() => { history.push('/user/login'); }, 5000);
      }
`



但是 replaceGoto(); 调用完后，跳转到 redirect 页面， 这时 由于 getInitialState() 是个异步的，所有 onPageChange()  里面的代码居然先执行了
currentUser 这时还没取到数据，所有无情的 跳转到了  登录页面

**Comment by shaodushu** [comment]
![image](https://user-images.githubusercontent.com/26360246/89269280-47584280-d66c-11ea-88f8-de2931e836ea.png)
在getInitialState中未对重定向进行处理，所以不会重新获取用户信息。页面跳转[onPageChange]时用户信息为空，所以又会重新跳转到登录页

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/pull/7095

看看这个 pr

**Comment by zhangshuling** [comment]
> #7095
> 
> 看看这个 pr

你好，我想你应该是没看明白我的意图，我现在的代码已经是最新的了，已经包含你在 app.tsx 第43行的改动
app.tsx 第43行  if (!initialState?.currentUser?.userid && history.location.pathname !== '/user/login') {

现在关键问题是 在 hash模式下，登录成功，在返回 redirect页面后，触发onPageChange时 initialState.currentUser 并没取到 当前登录者的 登录信息

**Comment by zhangshuling** [comment]
> ![image](https://user-images.githubusercontent.com/26360246/89269280-47584280-d66c-11ea-88f8-de2931e836ea.png)
> 在getInitialState中未对重定向进行处理，所以不会重新获取用户信息。页面跳转[onPageChange]时用户信息为空，所以又会重新跳转到登录页。此问题只出现在hash模式

你好，请问有什么解决办法呢？ 还是说这并非是个bug ？

**Comment by chemieliu** [comment]
我把我的情况讲一下，刚开始我也是message都展示登录成功了，却一直没有重定向到/welcome页面。后来发现，新版V5更改了，**!initialState?.currentUser?.userid && history.location.pathname !== '/user/login'，**这是判断条件。currentUser是我们数据库中取得的，我们不一定有userid这个字段，所以有可能问题出现在这边。如果我们自己换成username等我们自己数据中有的，然后就成功了。

**Comment by zhangshuling** [comment]
> 我把我的情况讲一下，刚开始我也是message都展示登录成功了，却一直没有重定向到/welcome页面。后来发现，新版V5更改了，**`!initialState?.currentUser?.userid && history.location.pathname !== '/user/login'`，**这是判断条件。currentUser是我们数据库中取得的，我们不一定有userid这个字段，所以有可能问题出现在这边。如果我们自己换成username等我们自己数据中有的，然后就成功了。

` // 如果没有登录，重定向到 login
      if (!initialState?.currentUser?**.token** && history.location.pathname !== '/user/login'`


这个我早就换了，登录成功后这个token是一定有值的， 上述问题只会出现在 地址栏有 redirect 回跳页面是存在的情况，如果没有这个redirect，登录成功后，会跳到首页

**Comment by chemieliu** [comment]
```
 if (history.location.pathname !== '/user/login') {
    try {

      return {
        currentUser,
        settings: defaultSettings,
      };
    } catch (error) {
      history.push('/user/login');
    }
  }
  return {
    currentUser,
    settings: defaultSettings,
  };
```
我在if后面的也把currentUser给返回了，你再看看呢？

**Comment by zhangshuling** [comment]
> ```
>  if (history.location.pathname !== '/user/login') {
>     try {
> 
>       return {
>         currentUser,
>         settings: defaultSettings,
>       };
>     } catch (error) {
>       history.push('/user/login');
>     }
>   }
>   return {
>     currentUser,
>     settings: defaultSettings,
>   };
> ```
> 
> 我在if后面的也把currentUser给返回了，你再看看呢？

![image](https://user-images.githubusercontent.com/15334960/91515742-691bb100-e91c-11ea-8313-24550f61c5f3.png)

**Comment by chenshuai2144** [comment]
这周会处理一下 做一个完美的方案
