### ISSUE TITLE
🐛[BUG] pro 5 启动后，登录页面加载失败 

### ISSUE THREAD

**Issue by puxinhe** [ant-design/ant-design-pro#7088]
### 🐛 bug 描述
启动之后，无法输入账号登陆，报错
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in BasicLayout (created by BasicLayout)
    in BasicLayout
    in Unknown (created by ComponentWithInitialPropsFetch)
    in ComponentWithInitialPropsFetch (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by RouterComponent)
    in RouterComponent
    in AccessProvider
    in Unknown
    in FormProvider (created by Context.Consumer)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (at locale.tsx:49)
    in _LocaleContainer
    in Unknown

### © 版本信息

- Ant Design Pro 版本:5.0
- umi 版本
- 浏览器环境 chrome
- 开发环境win

**Comment by xuxusheng** [comment]
同上

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/ant-design-pro/pull/7095
