### ISSUE TITLE
在BasicLayout中访问不到cookie

### ISSUE THREAD

**Issue by 591749921** [ant-design/ant-design-pro#709]

**Comment by chenshuai2144** [comment]
详细一点？
cookie是window对象的，什么地方都能访问到的

**Comment by 591749921** [comment]
我在BasicLayout中请求服务端  服务端去查cookie 这时候是查不到的，但是我在页面里面，比如table-list里面访问的时候是可以的

**Comment by chenshuai2144** [comment]
不应该的呀。 你使用浏览器自带的fetch试试

**Comment by 591749921** [comment]
用fetch试过了   主要是写在basiclayout里面  就娶不到cookie   别的地方都可以

**Comment by chenshuai2144** [comment]
延时试一下。是不是cookie还没生成
