### ISSUE TITLE
如何更改build后的目标目录

### ISSUE THREAD

**Issue by tomcyndi** [ant-design/ant-design-pro#7090]
### 🧐 问题描述
即对于tyarn build后的输出目录如何更改？

默认情况下build后的文件是放在dist目录下，之前版本的antd下有个.umirc.js里是可以配置output，能指定一个目录来存放build之后的文件，但在antd pro 2.3里我没找到如何更改这个配置的地方。

目前我是在整合spring boot与antd pro，虽然antd pro官网在部署这个环节里说了，先build，然后把dist下的文件拷贝到spring boot的static目录下，也确实可以，运行后能看到效果，但是这样有个不方便的地方，因为我得把antd pro工程与spring boot工程分开来，每次在antd pro工程里编译完还得手动拷贝到spring boot工程里，非常不方便。

之前我们用antd时，是可以在同一个工程里对antd 以及 spring boot进行开发、编译、运行的，但目前这个antd pro2.3该怎么整呢？求指教

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#outputpath

可以自定义配置的
