### ISSUE TITLE
🧐[问题]build时，怎么设置非跟目录 相对路径？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7091]
### 🧐 问题描述

build时，怎么设置相对路径？用create-react-app可以通过在package.js里添加  homepage: ".", 这个字段，把web部署时设置成非根目录，并且是相对路径  ./ 这样的，现在在antd pro，不清楚怎么设置？

![image](https://user-images.githubusercontent.com/5111701/88501361-d5de1b80-cffd-11ea-8b32-ed237d56421e.png)
这种指定目录的，设置方法，不是我想要的。
我想随便web 内容的文件夹名字叫什么，只要连接路径对应上，都能访问。
我设置成
```
  base: './',
  publicPath: './',
  history: { type: 'hash' },
  manifest: {
    basePath: './',
    // basePath: '/admin/',
    // publicPath: '/admin/',
  },
```
会出bug。
![image](https://user-images.githubusercontent.com/5111701/103390225-4ad5f400-4b4e-11eb-9012-85c94a82cf69.png)
这是其中一个报错图片的使用方式，dev模式下正常，build后部署到非根目录服务下，就出现这个问题；
![image](https://user-images.githubusercontent.com/5111701/103393023-9c38b000-4b5b-11eb-99b8-5895877470f0.png)

用的egg服务部署
![image](https://user-images.githubusercontent.com/5111701/103390456-73122280-4b4f-11eb-98a7-cbe98bcec4d2.png)

![image](https://user-images.githubusercontent.com/5111701/103390187-0185a480-4b4e-11eb-889c-3f59ffafac48.png)

----
![image](https://user-images.githubusercontent.com/5111701/103392037-eb301680-4b56-11eb-8238-66a8f97a86c4.png)
改成这样，也会出现同样的问题

**Comment by yueyemisi** [comment]
请问最后如何解决的？
