### ISSUE TITLE
🧐[问题]如何只用一个文件管理api，开发环境 和 生产环境 下只是 http前缀不同？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7092]
### 🧐 问题描述

如何只用一个文件管理api，开发环境 和 生产环境 下只是 http前缀不同？

我现在用的v5版本；
我看proxy里有dev的配置，数据用的 本地mock里的。
如果是生产环境prod，我应该如何配置？
我的web页面，和server程序都是分离独立的，数据通过url接口连接。
![image](https://user-images.githubusercontent.com/5111701/88508503-89044000-d011-11ea-850f-8995a7f451d7.png)

上线部署的时候。web页面会使用iis服务器。server程序是用node启动。

![image](https://user-images.githubusercontent.com/5111701/88508400-4e020c80-d011-11ea-9ac6-c9f7b6b9e2c9.png)

w我看下图例子，要把antd pro web代码放到 egg 程序里？
![image](https://user-images.githubusercontent.com/5111701/88509248-3af03c00-d013-11ea-8c4b-2485310ef894.png)

## PS:
我现在用命令 start:test，
然后proxy里test填写 
![image](https://user-images.githubusercontent.com/5111701/88518440-14d29800-d023-11ea-9512-dfc74e6b28df.png)

然后server里接口
![image](https://user-images.githubusercontent.com/5111701/88518503-2b78ef00-d023-11ea-89fb-2177034515d6.png)

然后/api/login/account可以正常访问，
但是 /api/currentUser是什么鬼？
![image](https://user-images.githubusercontent.com/5111701/88518587-4ba8ae00-d023-11ea-8ba7-4932c24c8784.png)
为什么前缀端口是8000，
感觉数据这块，有点乱！

**Comment by pxim** [comment]
尝试了 egg-ant-design-pro，也没用，这个项目都2年没更了，一直报错，连issue都没有

**Comment by duncup** [comment]
放到环境变量

**Comment by chenshuai2144** [comment]
前端直接放到 nginx 好了，然后代理，一份 js 到处用

**Comment by pxim** [comment]
> nginx

这个nginx没搞过，

> 放到环境变量

具体在哪个文件里呢？

**Comment by pxim** [comment]
> 前端直接放到 nginx 好了，然后代理，一份 js 到处用

没用过nginx ，wo'k我看v5版本里有个这个，是在这里改么
![image](https://user-images.githubusercontent.com/5111701/89969159-4cc71580-dc88-11ea-8c07-35fed7400c3c.png)

**Comment by pxim** [comment]
> 前端直接放到 nginx 好了，然后代理，一份 js 到处用

配置config下的proxy里的dev，路径改成，
![image](https://user-images.githubusercontent.com/5111701/89970100-a7fa0780-dc8a-11ea-8cbc-39b4f5c9e63e.png)
然后运行 npm start:dev ，这种方法行不通么？
我现在这样改了，没效果

**Comment by pxim** [comment]
> > 前端直接放到 nginx 好了，然后代理，一份 js 到处用
> 
> 配置config下的proxy里的dev，路径改成，
> ![image](https://user-images.githubusercontent.com/5111701/89970100-a7fa0780-dc8a-11ea-8cbc-39b4f5c9e63e.png)
> http://localhost:9060 是我服务器程序的url地址
> 然后运行 npm start:dev ，这种方法行不通么？
> 我现在这样改了，没效果，还是8000

用这种方法，现在可以了

**Comment by tss0823** [comment]
我也遇到这种问题， @pxim 求指教
