### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by ShangTX** [ant-design/ant-design-pro#7097]
### 🐛 bug 描述

我也不知道是bug还是设计，
布局为top，菜单和header为黑色，当宽度改变菜单被隐藏后，header变为白色

### 📷 复现步骤

官方演示地址可复现

### 🏞 期望结果

宽度变化，header颜色不变

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.2x
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![topmenu](https://user-images.githubusercontent.com/25798245/88615548-c2e24e80-d0c4-11ea-8956-13bb2c081ec2.gif)

**Comment by chenshuai2144** [comment]
是设计， Mobile 模式下有特殊的设计的
