### ISSUE TITLE
官网的demo重定向问题地址栏直接输入/list/search

### ISSUE THREAD

**Issue by youyuxun** [ant-design/ant-design-pro#710]
官网的demo，地址栏直接输入/list/search跳转，除了PageHeaderLayout组件，其余未渲染，就是这样子的还是bug？
看代码在BasicLayout已经生成了对应的Redirect，应该可以跳转的吧？

**Comment by afc163** [comment]
就是这样的，/list/search 不是一个真实路径。

https://preview.pro.ant.design/#/list/search/articles

**Comment by chenshuai2144** [comment]
渲染了呀。。。

**Comment by youyuxun** [comment]
我自己再加了层Redirect，就是输入/list/search也会重定向到/list/search/articles，解决了。虽然/list/search不是真实路径，不能通过菜单导航进入，个人觉得通过地址栏进入也要处理掉

**Comment by afc163** [comment]
感觉应该跳 404。@ddcat1115

**Comment by chenshuai2144** [comment]
我记得我写了重定向了。我去排查一下

**Comment by chenshuai2144** [comment]
@afc163  
![image](https://user-images.githubusercontent.com/8186664/34977283-e5973260-fad4-11e7-95bd-0faa87d13e2b.png) 这个面包屑可以点击。。要是404 点击就毫无意义了。


不知道什么时候rebase 修改了顺序。我改回来了

**Comment by chenshuai2144** [comment]
@youyuxun  看一下主分支
