### ISSUE TITLE
修改document.ejs 标题不生效？

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#7100]
### 🧐 问题描述
版本：antd pro : v5版本

![image](https://user-images.githubusercontent.com/23183393/88638667-63009d80-d0ee-11ea-8cc1-3c5bdf5e9a62.png)
![image](https://user-images.githubusercontent.com/23183393/88638716-76ac0400-d0ee-11ea-849a-387fe087f850.png)
网页值出现一个加载框

**Comment by mushroomlb** [comment]
重新启动一次

**Comment by xyy7260** [comment]
@mushroomlb  主要是有点奇怪😆， 我重启后出现了。 但是我刷新页面过后 又没得了
