### ISSUE TITLE
🧐[问题&求助] v5如何保存修改全局变量，就比如我要存储loginName

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/ant-design-pro#7101]
### 🧐 问题描述

比如实现逻辑：
       用户登录，先请求token认证，再请求用户信息。此时请求用户信息的时候并不知道是哪个用户，两个请求是分开的，不能then()，so需要在请求token后设置一个全局变量loginName||loginId，然后再去请求用户信息，如何实现保存修改全局变量，麻烦说的详细一些，基于v5实现的。谢谢~

**Comment by duncup** [comment]
token你怎么存的就怎么存

**Comment by gameruleCEO** [comment]
> token你怎么存的就怎么存

token存的会话sessionStorage...总觉得不怎么好，后续也会优化掉存会话sessionStorage的

**Comment by pxim** [comment]
同问，我设置了一些全局配置，想存储到一个全局变量里，用哪个方法 useModel？

**Comment by gameruleCEO** [comment]
> 同问，我设置了一些全局配置，想存储到一个全局变量里，用哪个方法 useModel？

你这个如果不是动态变化的话，可以参考官网的方法：https://beta-pro.ant.design/docs/simple-model-cn

**Comment by pxim** [comment]
> > 同问，我设置了一些全局配置，想存储到一个全局变量里，用哪个方法 useModel？
> 
> 你这个如果不是动态变化的话，可以参考官网的方法：https://beta-pro.ant.design/docs/simple-model-cn

好的，谢谢了

**Comment by shaohuatsou** [comment]
model , storage 都是可以存的，或者你为啥不在token中包含用户的信息？这样根据token就能直接获取用户信息了。

**Comment by gameruleCEO** [comment]
> model , storage 都是可以存的，或者你为啥不在token中包含用户的信息？这样根据token就能直接获取用户信息了。

token里肯定包含了用户信息，只是不想前端放置解析token代码，不安全。
这个问题涉及到我一些别的想法，比如全局的动态数据(需发请求)也需要存储，就不适用token方式。storage的方式容易篡改。

**Comment by shaohuatsou** [comment]
> > model , storage 都是可以存的，或者你为啥不在token中包含用户的信息？这样根据token就能直接获取用户信息了。
> 
> token里肯定包含了用户信息，只是不想前端放置解析token代码，不安全。
> 这个问题涉及到我一些别的想法，比如全局的动态数据(需发请求)也需要存储，就不适用token方式。storage的方式容易篡改。

我说的意思token只包含个用户的id，没要你前端解析，请求接口的时候后端根据token返回用户的其他信息。

**Comment by gameruleCEO** [comment]
> > > model , storage 都是可以存的，或者你为啥不在token中包含用户的信息？这样根据token就能直接获取用户信息了。
> > 
> > 
> > token里肯定包含了用户信息，只是不想前端放置解析token代码，不安全。
> > 这个问题涉及到我一些别的想法，比如全局的动态数据(需发请求)也需要存储，就不适用token方式。storage的方式容易篡改。
> 
> 我说的意思token只包含个用户的id，没要你前端解析，请求接口的时候后端根据token返回用户的其他信息。

明白你的意思。只是我还没弄明白v5内部怎么保存全局变量或全局函数，不依靠token啊storage啊这些额外的方式。毕竟项目中总会用到全局变量或函数的

**Comment by shaohuatsou** [comment]
可以试试 window.xx = xx; 或者model的state啊

**Comment by gameruleCEO** [comment]
> 可以试试 window.xx = xx; 或者model的state啊

你确定你看过v5？

**Comment by shaohuatsou** [comment]
V5里面没看到model文件夹，按照umi的约定，你可以手动创建src/models，然后用usemoodel去加载，这样多个页面能共享数据。

**Comment by gameruleCEO** [comment]
> V5里面没看到model文件夹，按照umi的约定，你可以手动创建src/models，然后用usemoodel去加载，这样多个页面能共享数据。

emm官网给的这个方式我上午试了一下，没生效。我就很迷....

**Comment by shaohuatsou** [comment]
> > V5里面没看到model文件夹，按照umi的约定，你可以手动创建src/models，然后用usemoodel去加载，这样多个页面能共享数据。
> 
> emm官网给的这个方式我上午试了一下，没生效。我就很迷....

没生效是啥意思，是跳转之后新页面的model拿不到数据吗？

**Comment by gameruleCEO** [comment]
> > > V5里面没看到model文件夹，按照umi的约定，你可以手动创建src/models，然后用usemoodel去加载，这样多个页面能共享数据。
> > 
> > 
> > emm官网给的这个方式我上午试了一下，没生效。我就很迷....
> 
> 没生效是啥意思，是跳转之后新页面的model拿不到数据吗？

对的，拿不到数据，我还是粘的官网例子的model，useModel取出来的是undefined。加个wx吧：sibaiabis

**Comment by shaohuatsou** [comment]
你咋跳转的？

**Comment by gameruleCEO** [comment]
> 你咋跳转的？

我就是一个测试项目，用来学习的。我打在登录逻辑了，登录逻辑里取了默认的model数据，我以为在那里可以取到我自定义的这个model，结果取不到undefined

**Comment by shaohuatsou** [comment]
我也是刚学不久，跳转的时候要用history的方式，不然数据会被刷新掉

**Comment by gameruleCEO** [comment]
> 我也是刚学不久，跳转的时候要用history的方式，不然数据会被刷新掉

哈哈，彼此彼此。我都是瞎折腾，想到啥写啥。不过还是感谢解答
