### ISSUE TITLE
参考Deom，不能在dva中拿到数据，问题解决但是有一点疑惑🧐[问题]

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#7104]
### 🧐 问题描述
完全参考Demo写的，已经请求到了数据，然是在页面中传递不过来

代码1
![image](https://user-images.githubusercontent.com/12421552/88685956-1edebe80-d129-11ea-9121-167c8b6da547.png)

代码2，

![image](https://user-images.githubusercontent.com/12421552/88686094-4df53000-d129-11ea-9276-dbaaadf79652.png)

结果是截图3。。。

![image](https://user-images.githubusercontent.com/12421552/88686136-5c434c00-d129-11ea-8c39-f585352ccd80.png)

诡异的是当我把代码1中 这三个名称改成login后页面恢复正常

![image](https://user-images.githubusercontent.com/12421552/88686464-b3e1b780-d129-11ea-9ab3-cc992364d9eb.png)

结果页面正常，但是没有数据

![image](https://user-images.githubusercontent.com/12421552/88686655-e25f9280-d129-11ea-97f6-bdafb73ef68c.png)

### 💻 示例代码

问题已经解决，在connect.d.ts中注册了信息
![image](https://user-images.githubusercontent.com/12421552/88749172-4f544600-d185-11ea-834b-ad119eede57e.png)

可是我还是没看懂为什么需要这么做

### 🚑 其他信息
使用最新的v4版本开发，完全没有多余的东西

**Comment by chenshuai2144** [comment]
他是异步的，你需要给个默认值。
hooks 是先执行 render 再执行 hooks 的。
