### ISSUE TITLE
🧐[问题]v5版本头部面包屑点击跳转 问题

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7105]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/5111701/88745082-b967ed80-d17b-11ea-8ac4-5da2d8536f79.png)
点击红框部分，会跳转，但是跳转到异常页面，dev模式是调整到首页，prod模式是空白页，请问我应该在哪个地方调整配置？

我想跳转到正确的页面，或者关闭 点击跳转 这个功能。

### 🚑 其他信息

我看了 https://github.com/ant-design/ant-design-pro/issues/4738  这个上面的，但是目前v5版本配置改了很多，不一样，没找到有效配置的地方。

**Comment by chenshuai2144** [comment]
breadcrumbRender | 自定义面包屑的数据 | (route)=>route
-- | -- | --




可以试试这个 api，和 antd 的使用方法相同

**Comment by pxim** [comment]
`.ant-breadcrumb-link {
  pointer-events: none;
}
`
我直接修改css，屏蔽点击
