### ISSUE TITLE
升级1.0版本后，roadhog也更新到roadhog@2.1.0，但是IE11打开直接报错

### ISSUE THREAD

**Issue by jifeng122333** [ant-design/ant-design-pro#711]
TypeError: 对象不支持此操作
_this.getBashRedirect
E:/xx/src/layouts/BasicLayout.js:105
  102 | }, _this.getBashRedirect = function () {
  103 |   // According to the url parameter to redirect
  104 |   // è¿éæ¯éå®åç,éå®åå° url ç redirect åæ°æç¤ºå°å
> 105 |   var urlParams = new URL(window.location.href);
  106 |   var redirect = urlParams.searchParams.get('redirect') || '/dashboard/analysis'; // Remove the parameters in the url
  107 | 
  108 |   urlParams.searchParams.delete('redirect');

**Comment by chenshuai2144** [comment]
#698 
#699

**Comment by jifeng122333** [comment]
Could not open BasicLayout.js in the editor.

To set up the editor integration, add something like REACT_EDITOR=atom to the .e
nv.local file in your project folder and restart the development server. Learn m
ore: https://goo.gl/MMTaZt
