### ISSUE TITLE
v3 basiclayout 会重新渲染这个怎么解决么

### ISSUE THREAD

**Issue by JianJD** [ant-design/ant-design-pro#7113]
### 🧐 问题描述

点击同一路由模块的子路由不会重新渲染，切换到不同模块下的子路由basiclayout就会被重新渲染
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32892566/88893471-f5cd4380-d278-11ea-8f0f-dddae58960cf.png)

**Comment by chenshuai2144** [comment]
描述有点不清楚。
https://v2.umijs.org/config/#disableredirecthoist

是不是这个

**Comment by afc163** [comment]
看看是不是已经被 https://github.com/umijs/umi/pull/5124 解决了？

**Comment by JianJD** [comment]
> 描述有点不清楚。
> https://v2.umijs.org/config/#disableredirecthoist
> 
> 是不是这个

能加个qq请教一下么1520057670

**Comment by JianJD** [comment]
> 描述有点不清楚。
> https://v2.umijs.org/config/#disableredirecthoist
> 
> 是不是这个



> 看看是不是已经被 [umijs/umi#5124](https://github.com/umijs/umi/pull/5124) 解决了？

就是切换路由的时候basicLayout会被重新渲染

**Comment by thelaurelyy** [comment]
> > 描述有点不清楚。
> > https://v2.umijs.org/config/#disableredirecthoist
> > 是不是这个
> 
> > 看看是不是已经被 [umijs/umi#5124](https://github.com/umijs/umi/pull/5124) 解决了？
> 
> 就是切换路由的时候basicLayout会被重新渲染

 请教，这个问题解决了吗？

**Comment by thelaurelyy** [comment]
@JianJD   请教，这个问题解决了吗？

> > 描述有点不清楚。
> > https://v2.umijs.org/config/#disableredirecthoist
> > 是不是这个
> 
> > 看看是不是已经被 [umijs/umi#5124](https://github.com/umijs/umi/pull/5124) 解决了？
> 
> 就是切换路由的时候basicLayout会被重新渲染
