### ISSUE TITLE
如何动态生成model?或者如何使用createModel

### ISSUE THREAD

**Issue by lininn** [ant-design/ant-design-pro#7115]
### 🧐 问题描述

我想把所有的api请求方法都使用dva的model来实现，但是需要在model下创建多个js文件，我不想特别繁琐，如何一个js文件包含多个model,或者动态根据数组创建model，如何动态实现？
### 💻 示例代码
/model/order.js
import { history } from 'umi';
const allProvinces = {
  namespace: 'allProvinces',
  state: {
    data:[],
  },
  effects: {
    *allProvinces({ payload }, { call, put }) {
      const response = yield call(fakeAccountLogin, payload);
      yield put({
        type: 'changeLoginStatus',
        payload: response,
      }); // Login successfully

      console.log(1)
    }
  },
  reducers: {
    changeLoginStatus(state, { payload }) {
      return { ...state, status: payload.status, type: payload.type };
    },
  },
};

const getLine= {
  namespace: 'getLine',
  state: {
    data:[],
  },
  effects: {
    *allProvinces({ payload }, { call, put }) {
      const response = yield call(fakeAccountLogin, payload);
      yield put({
        type: 'changeLoginStatus',
        payload: response,
      }); // Login successfully

      console.log(1)
    }
  },
  reducers: {
    changeLoginStatus(state, { payload }) {
      return { ...state, status: payload.status, type: payload.type };
    },
  },
};

export default [allProvinces,getLine]

假如我有更多的方法都是如上实现，但是我发现，现在这样是报错的

**Comment by lininn** [comment]
哪位大佬帮忙看一下？我想用swagger生成model.js，如果不按模块而按照方法的话，可能要生成数百个model的js,如果能按照如上的话只需要生成模块数量的model

**Comment by chenshuai2144** [comment]
model 还是写的细一点比较好，如果不想写 model，直接不用 dva 就好了。
