### ISSUE TITLE
🧐[问题]项目初始化时，控制台出现Json解析失败的日志信息。

### ISSUE THREAD

**Issue by wayneee188** [ant-design/ant-design-pro#7116]
### 🧐 问题描述

操作步骤：
1. 使用create umi安装antd prov4项目
2. 打开页面，查看控制台
3. 错误信息如下:
日志级别：信息
SyntaxError: Unexpected token O in JSON at position 0
    at JSON.parse (<anonymous>)
    at window.onload (app.js:59)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38581778/88910658-61221000-d28f-11ea-8d65-1e2cf8083b0a.png)

**Comment by chenshuai2144** [comment]
这个应该是你的接口问题
