### ISSUE TITLE
查询表格中 renderFormItem  使用Select  之后再查询的时候没有参数

### ISSUE THREAD

**Issue by qixijie** [ant-design/ant-design-pro#7117]
![image](https://user-images.githubusercontent.com/31504074/88944123-f092e780-d2be-11ea-9c48-0e4003be533d.png)
使用select 之后 选择 参数 再点击查询  查询的时候没有参数，不知道是什么情况。不使用枚举的， 望解答下

![image](https://user-images.githubusercontent.com/31504074/88944422-4b2c4380-d2bf-11ea-8edb-26950105650e.png)
 现在使用input 是可以输出参数
![image](https://user-images.githubusercontent.com/31504074/88944652-99414700-d2bf-11ea-85e6-4a08224aef3c.png)

![image](https://user-images.githubusercontent.com/31504074/88944762-b6761580-d2bf-11ea-816a-c1aec2a591fb.png)

**Comment by huntdream** [comment]
`rest`里面有`value`和`onChange`，需要把它们传递给表单控件，这样`Form`才能收集表单控件的值，你看你的`Input`传递了`rest`而`Select`却没有

**Comment by qixijie** [comment]
收到 测试了下  把rest 加上 还是没有 ，
![image](https://user-images.githubusercontent.com/31504074/89105197-9bd3a600-d451-11ea-8a9f-02496b8ccdf3.png)
加上之后请求参数为：
![image](https://user-images.githubusercontent.com/31504074/89105210-bf96ec00-d451-11ea-92dc-e3add8e9ad3c.png)

**Comment by huntdream** [comment]
因为你`rest`里面的`onChange`实际上并没有传递下去，而是被后面的`onChange={handleChange}`覆盖掉了

**Comment by qixijie** [comment]
测试通过了，  谢谢
