### ISSUE TITLE
反复测试，发现dynamicWrapper的第二个参数model有多目录时无法按需打包

### ISSUE THREAD

**Issue by longzhaobi** [ant-design/ant-design-pro#712]
例子本仓库的项目：
我也已经把disableDynamicImport：true删掉。刚clone下来的项目打包后能正常按需打包成几十个文件，但是我做如下改动后就不能了。
比如我把所有的src下models（src/models）目录全部复制到routes目录下（src/routes/models），然后common下的router.js里的代码改成如下所示：
```
component: dynamicWrapper(app, ['models/user', 'models/login'], () => import('../layouts/BasicLayout')),
```
然后把
```
import(`../models/${m}.js`
```
改成
```
import(`../routes/${m}.js`
```

npm start后正常运行。

但执行npm run build后，并没有按需打包成很多个文件，有一个2M左右的index.js文件。

我还原成官方默认的写法就可以正常分割打包。

但我们项目为了快速定位到需要改的代码，model文件一般都是放到各个模块里的。不可能四五十个model文件全部丢到一个目录下。

之前的版本是没这个问题的。

**Comment by afc163** [comment]
这个应该和动态 require 变量的写法有关系。@chenshuai2144 来答一下。

**Comment by chenshuai2144** [comment]
https://github.com/webpack/webpack/issues/118
这个应该能解释你的问题！
![image](https://user-images.githubusercontent.com/8186664/34976989-de4257a2-fad3-11e7-9ab0-e59a0bd17b3c.png)

这样使用表现是正常的

**Comment by dai875939260** [comment]
今天也发现了这个问题。。

**Comment by longzhaobi** [comment]
@chenshuai2144  嗯，这样使用是正常的，这种写法就跟你们默认的写法没什么区别，但只有model参数带有/这种就不行了，但如果不能这样，那所有的model文件都得写在一个文件夹才行了，这样model文件四五十个，他们改代码找model文件也头痛啊！。
我可以非常的确定，之前你们的版本是没这个问题的，我的model文件任意放都可以按需打包。
这个能有好的办法解决吗？

**Comment by chenshuai2144** [comment]
你可以把model这部分改回原来的加载方式。
我们这个方式是为了能只有配置代码分割。
没有特别好的方式。办法都比较脏

**Comment by longzhaobi** [comment]
@chenshuai2144  你好，我把dynamicWrapper第二个参数数组里的值改成了函数形式：
```
'/dashboard/analysis': {
      component: dynamicWrapper(app, [() => import(`../routes/Dashboard/models/chart`)], () => import('../routes/Dashboard/Analysis')),
    },
```
然后在dynamicWrapper函数里把import(`../routes/${m}.js`改成了m(),
这样打包后无论我model放在哪个目录是实现了按需打包，但因为无法获取具体的路径，我把modelNotExisted这个判断删掉了，请问下这个删掉了有影响吗？之前版本没有这个判断的，还有就是dva2.0后，内部貌似自己也判断了namespace是否唯一了吧？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34981181-b89e3328-fae1-11e7-8c49-db1d81d96028.png)

你可以把这里改一下。我是忘了原来有什么用了

**Comment by chenshuai2144** [comment]
应该没有问题

**Comment by chenshuai2144** [comment]
嗯。我们也是在跟进webpack。如果webpack更新了更好的办法，我们一定会跟进的
