### ISSUE TITLE
v5版本怎么使用ConfigProvider🧐[问题]

### ISSUE THREAD

**Issue by suncongcong49** [ant-design/ant-design-pro#7120]
### 🧐 问题描述

v5版本要怎么使用ConfigProvider的全局化配置呢

**Comment by 569202812** [comment]
同问

**Comment by chenshuai2144** [comment]
可以看看这个，刚写了文档

https://github.com/ant-design/ant-design-pro/issues/7123

**Comment by 569202812** [comment]
> 可以看看这个，刚写了文档
> 
> #7123

日期怎么设置成中文喃

**Comment by suncongcong49** [comment]
> 可以看看这个，刚写了文档
> 
> #7123

# # # #我全局设置空状态。这样设置不生效。

> 

> `
![微信截图_20200810113205](https://user-images.githubusercontent.com/69026168/89750107-2628a380-dafd-11ea-8957-6b14a6253e62.png)
`

**Comment by suncongcong49** [comment]
> 可以看看这个，刚写了文档
> 
> #7123

我全局设置空状态，在config里面去配置。renderEmpty的值为一个组件。这样设置不生效

![微信截图_20200810113205](https://user-images.githubusercontent.com/69026168/89750178-7142b680-dafd-11ea-92e1-610cbd58b246.png)

**Comment by chenshuai2144** [comment]
>  日期怎么设置成中文喃

https://ant.design/components/config-provider-cn/

**Comment by chenshuai2144** [comment]
@suncongcong49  之一一下 antd 的版本，而且 config 里面是不能写 runtime 的代码。
要到 app.ts 里面写

**Comment by 569202812** [comment]
> @suncongcong49 之一一下 antd 的版本，而且 config 里面是不能写 runtime 的代码。
> 要到 app.ts 里面写
> 
> ```
> // src/app.ts
> export const antd = {
>   componentSize:'small'
> }
> ```

配置了还是报错
![image](https://user-images.githubusercontent.com/34082148/89774411-65281a80-db38-11ea-9f57-75abf3dd62e3.png)
