### ISSUE TITLE
🧐[问题] 🧐 setFieldsValue赋值问题

### ISSUE THREAD

**Issue by rong12345** [ant-design/ant-design-pro#7121]
### 💻 示例代码
setFieldsValue({
          ChildForm[index].subject: [{label: '项目名称', value: 1}]
        })

当index是变量的时候应该怎么写

**Comment by lovesL** [comment]
这种基础问题 你也好意思 在这来问 。。。。

**Comment by rong12345** [comment]
我试了好几种都不对才问的，不能问？

> 这种基础问题你也好意思在这来问。。。。

**Comment by huntdream** [comment]
你是需要修改`ChildForm`中第`index`项的值吗?

**Comment by rong12345** [comment]
> 你是需要修改`ChildForm`中第`index`项的值吗?

是的，ChildForm里有好几组数据，我直接写ChildForm[0].subject可以赋值，但是当那个0是一个变量的时候试过好几种方法都不对，`ChildForm[${index} ].subject`这种也尝试过

**Comment by huntdream** [comment]
能贴一下`setFieldsValue`这块实际的代码吗？

**Comment by rong12345** [comment]
逻辑是某个事件会修改当前项的subject值，之前的代码是赋值的地方，下面的是渲染页面的代码，主要就是想知道setFieldsValue怎么给当前项的subject赋值
<Form.Item>
            {getFieldDecorator(`ChildForm[${(parseInt(pane.key) - 1).toString()}].subject`)(
              <Select showSearch placeholder="请选择科目" labelInValue filterOption onChange={handleSubjectChange}>
                {SubjectDataSource &&
                  Array.prototype.map.call(SubjectDataSource, item => (
                    <Option value={item.ID}>{item.NAME}</Option>
                  ))}
              </Select>,
            )}
          </Form.Item>

**Comment by huntdream** [comment]
```javascript
setFieldsValue({
      [`ChildForm[${index}].subject`]: value,
})
```
我一般是这样写的，按理来说应该没什么问题

**Comment by rong12345** [comment]
> ```js
> setFieldsValue({
>       [`ChildForm[${index}].subject`]: value,
> })
> ```
> 
> 我一般是这样写的，按理来说应该没什么问题

可以可以太感谢了
