### ISSUE TITLE
antd pro 自定义侧边栏收缩按钮位置

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#7122]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/27960630/89008952-30e57a80-d33e-11ea-8a52-cb809b905416.png)
 BasicLayout.jsx 里面的ProLayout自定义侧边栏收缩按钮按钮能否放到菜单栏最下面 我用的是Pro v4

**Comment by shaohuatsou** [comment]
你升级下layout不就行了吗？

**Comment by chenshuai2144** [comment]
可以通过 


collapsed | 控制菜单的收起和展开 | boolean | true
-- | -- | -- | --
onCollapse | 菜单的折叠收起事件 | (collapsed: boolean) => void


两个属性配置，就可以实现完全的自定义了 

文档  https://procomponents.ant.design/components/layout#api
