### ISSUE TITLE
🐛[v5版本怎样设置antD的语言为中文 ]

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#7123]
### 🐛 bug 描述
新拉的框架, 关闭国际化，配置
```
export const antd= {
	config:{
	    locale:{}
	}
}
```
报错

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本【3.2.13】
- 浏览器环境 谷歌
- 开发环境 [win10]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/34082148/89010062-7acf6000-d340-11ea-85f7-7cb737c2774d.png)
![image](https://user-images.githubusercontent.com/34082148/89010085-81f66e00-d340-11ea-98ef-650a22f7b619.png)
![image](https://user-images.githubusercontent.com/34082148/89010117-8f135d00-d340-11ea-83a3-7d5754d82627.png)

**Comment by shaohuatsou** [comment]
为啥我看不到图？

**Comment by 569202812** [comment]
> 为啥我看不到图？

看不到吗

**Comment by Wanyucheng** [comment]
“locale.antd: false” 就可以关闭了

**Comment by xiaohuoni** [comment]
https://umijs.org/plugins/plugin-antd#config

**Comment by 569202812** [comment]
> 可以用这个 api 来自定义
> https://umijs.org/plugins/plugin-antd#config
> https://ant.design/components/config-provider-cn/

这样引用bao报错
![image](https://user-images.githubusercontent.com/34082148/89748381-83205b80-daf5-11ea-8279-e6218fa25453.png)

**Comment by chenshuai2144** [comment]
```
// src/app.ts
export const antd = {
  componentSize:'small'
}
```

**Comment by 569202812** [comment]
> 用 runtime 的写法
> 
> ```
> // src/app.ts
> export const antd = {
>   componentSize:'small'
> }
> ```

配置了后还是报错
![image](https://user-images.githubusercontent.com/34082148/89774548-b1735a80-db38-11ea-830c-798f6ce2fb7c.png)

**Comment by xiaohuoni** [comment]
@569202812 这里的设计有点问题，配置中的 antd 的 config 配置了才会开启运行时配置。你需要在配置里面写上 `antd:{config:{}}`

**Comment by 569202812** [comment]
> @569202812 这里的设计有点问题，配置中的 antd 的 config 配置了才会开启运行时配置。你需要在配置里面写上 `antd:{config:{}}`
配置了可以了, 日期还需要在app.tsx里面配置下
```import 'moment/locale/zh-cn';```

**Comment by Dowgen** [comment]
> > @569202812 这里的设计有点问题，配置中的 antd 的 config 配置了才会开启运行时配置。你需要在配置里面写上 `antd:{config:{}}`
> 
> 配置了可以了, 日期还需要在app.tsx里面配置下
> `import 'moment/locale/zh-cn';`

具体怎么配的能讲讲吗，看得我一脸懵逼

**Comment by 569202812** [comment]
> > > @569202812 这里的设计有点问题，配置中的 antd 的 config 配置了才会开启运行时配置。你需要在配置里面写上 `antd:{config:{}}`
> > 
> > 
> > 配置了可以了, 日期还需要在app.tsx里面配置下
> > `import 'moment/locale/zh-cn';`
> 
> 具体怎么配的能讲讲吗，看得我一脸懵逼

config 文件 添加```antd:{config:{}}```
app.tsx 文件 添加
```
import 'moment/locale/zh-cn';

export const antd= {
	config:{
	    locale: zhCN // 引用antd的语言包
	}
}
```

**Comment by KingDracula** [comment]
麻烦请教一下，我加上了这些怎么时间控件还是英文的？
config 文件 添加antd:{config:{}}
app.tsx 文件 添加

import 'moment/locale/zh-cn';
import zhCN from 'antd/es/locale/zh_CN';
export const antd= {
	config:{
	    locale: zhCN // 引用antd的语言包
	}
}

**Comment by chenshuai2144** [comment]
moment.set 也要执行
