### ISSUE TITLE
V5版本是否会支持js的版本

### ISSUE THREAD

**Issue by wolfkingchuang** [ant-design/ant-design-pro#7124]
目前V5版本生成的过程中无法选择相应的语言，原有项目的V4版本准备升级到V5，发现原有的项目是js的版本，而新版本V5只有TS版本，希望能支持一下js版本，这样对老项目可以实现平滑的升级

**Comment by iHDJ** [comment]
v4现在都没发选js版本了。今天弄了一天了

**Comment by chenshuai2144** [comment]
ts 和是 js 的超集，把文件名改成 ts 就可以 run 了，慢慢迁移就好了
