### ISSUE TITLE
Ant Design Pro 5：只有 pages 或 page 目录下的页面才能插入资产🧐[问题]

### ISSUE THREAD

**Issue by VagueZhao** [ant-design/ant-design-pro#7125]
### 🧐 问题描述

当我使用AntDesignPro V4 版本区块功能时,报只有 pages 或 page 目录下的页面才能插入资产。我在新建页面对应的 xxx.tsx 文件，找到 PageHeaderWrapper 标签,在里面随便加点东西,保存后刷新页面等方式,实现了插入资产。
但是当我使用AntDesignPro V5 版本区块功能时,也会报只有 pages 或 page 目录下的页面才能插入资产。我按照原来的解决方式，仍然不能插入资产。求解决！！如有解决方案 不胜感激！

**Comment by gameruleCEO** [comment]
这个不是必现的吧？我们都没有问题。
我以前用的办法，把页面全部加进去，然后重启....就好了
https://blog.csdn.net/shujudaniu/article/details/106080987

**Comment by kisslove** [comment]
我也遇到了，不是偶然，这是个bug

**Comment by chenshuai2144** [comment]
dupof https://github.com/ant-design/ant-design-pro/issues/6710

**Comment by robotPPG** [comment]
怎么解决啊
