### ISSUE TITLE
🧐[问题]<Form.Item>有name属性的包裹下的Select，无法更新value到默认值

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#7127]
### 🧐 问题描述
<Form.Item name='tags'> ，Select无法自动更新value =  this.state.selectedTags 中的数据
把 name 属性去掉就可以使用了

### 🚑 其他信息

显示正常，并且根据onSelectChange函数我还可以控制显示最多Tag
![image](https://user-images.githubusercontent.com/12421552/89096515-c69a0c00-d409-11ea-94a3-c0724b1babdc.png)
![image](https://user-images.githubusercontent.com/12421552/89096552-082ab700-d40a-11ea-9ed7-8886951be739.png)

显示有问题，<Form.Item name='tags'>
![image](https://user-images.githubusercontent.com/12421552/89096577-2b556680-d40a-11ea-9b94-fa0130e44f10.png)

**Comment by chenshuai2144** [comment]
name 配置之后 value 将会被 FormItem 接管，你的设置将会无法使用。

你可以通过 `initialValues ` 来设置默认值。

```tsx
<Form initialValues ={{tags:[] }}>
```
