### ISSUE TITLE
🐛[BUG] 服务器拉取menu，404错误页面无法显示

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#7128]
### 🐛 bug 描述

服务器拉取menu，404错误页面无法显示，页面内容部分显示空白

````
const loopMenuItem = (menus: MenuDataItem[]): MenuDataItem[] =>
    menus.map(({ icon, children, ...item }) => ({
      ...item,
      icon: icon && IconMap[icon as string],
      children: children && loopMenuItem(children),
    }));
````

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.2.14
- 浏览器环境 Chrome 80
- 开发环境 [e.g. mac OS] Windows 10

**Comment by chenshuai2144** [comment]
try catch 包一下网络请求。

有报错要处理掉，框架不可能枚举所有的的错误的。

**Comment by hihuangwei** [comment]
@chenshuai2144 
`component: './exception/404',`  每一级菜单下都要加 404 页面，可否改进下
![QQ浏览器截图20200807134523](https://user-images.githubusercontent.com/3166799/89613229-56c9cc80-d8b4-11ea-95df-048d1b957ff6.png)
