### ISSUE TITLE
🐛[BUG] yarn start 之后，没有出现官方示例的主题抽屉

### ISSUE THREAD

**Issue by guanrongjia** [ant-design/ant-design-pro#7130]
### © 版本信息

- Ant Design Pro 版本: 5.0.0-alpha.0
- umi 版本 "^3.2.0",
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息

 
![image](https://user-images.githubusercontent.com/31066159/89123081-3fc75b00-d4ff-11ea-9c3e-947eac7092eb.png)
![image](https://user-images.githubusercontent.com/31066159/89123086-448c0f00-d4ff-11ea-947e-f899d365f678.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/layout-cn#settingdrawer

看这个文档

**Comment by guanrongjia** [comment]
但是，新版本并没有这个命令啊

![image](https://user-images.githubusercontent.com/31066159/89622081-0870f980-d8c5-11ea-9cbf-ffcb3a98f4a8.png)

**Comment by OriginZero** [comment]
BasicLayout文件里引入SettingDrawer
