### ISSUE TITLE
🐛[BUG] 5.0 alpha 对齐问题

### ISSUE THREAD

**Issue by lirulei** [ant-design/ant-design-pro#7131]
下图这里没有对齐啊

© 版本信息
Ant Design Pro 版本: 5.0.0-alpha.0
umi 版本 3.1.0
浏览器环境 chrome
开发环境 mac OS
![image](https://user-images.githubusercontent.com/13436331/89140155-66bf7480-d573-11ea-8970-c2cd5d977f5b.png)

**Comment by chenshuai2144** [comment]
设计是这样的，我来修改一下宽度，让看起来是对齐的
