### ISSUE TITLE
🧐[问题]请求失败（需要根据后台返回的错误信息提示）

### ISSUE THREAD

**Issue by Pythonchao** [ant-design/ant-design-pro#7132]
### 🧐 问题描述
当请求失败时，如何得到后台返回的报错信息
![image](https://user-images.githubusercontent.com/40911444/89144546-aa6cab00-d580-11ea-842f-d13078be5a11.png)

这是后台返回的报错信息
![image](https://user-images.githubusercontent.com/40911444/89144585-c1130200-d580-11ea-8842-90e3bff6788d.png)

**Comment by shaohuatsou** [comment]
状态码是200吗？ 如果不是的话在 errorHandler的取error.data.code    error.data.msg
