### ISSUE TITLE
V5版本的菜单怎么从服务器获得呢？

### ISSUE THREAD

**Issue by ztedu** [ant-design/ant-design-pro#7133]
本人小白，麻烦大神讲下v5版本的pro如何从服务器拉取菜单呢？感谢

**Comment by k983551019** [comment]
看v4的文档

**Comment by lininn** [comment]
获取的菜单的component:'./Welcome'，页面无法渲染，文档太简单了

**Comment by chenshuai2144** [comment]
menu 只支持菜单的，不支持  component:'./Welcome'，要实现 component 要在服务器部署 webpack，然后动态编译。

**Comment by chenshuai2144** [comment]
@ztedu  
https://procomponents.ant.design/docs/getting-started-layout

可以读一下这个
