### ISSUE TITLE
how can i deploy to production with all the mock data

### ISSUE THREAD

**Issue by misterkrc** [ant-design/ant-design-pro#7136]
I have set up the and design pro locally with the mock data but all the mock data only shows in development, i cant use them in production

**Comment by chenshuai2144** [comment]
try use [umi-serve](https://www.npmjs.com/package/umi-serve)

`umi-serve ./`

**Comment by misterkrc** [comment]
Thanks alot, any idea how i can do that on netlify or heroku?
