### ISSUE TITLE
🐛[BUG]import { Access } from 'umi'; 这一句报错了：export 'Access' was not found in 'umi'

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7138]
### 🐛 bug 描述

import { Access } from 'umi';
这一句报错了：export 'Access' was not found in 'umi'

**Comment by effapp** [comment]
![image](https://user-images.githubusercontent.com/51013754/89195010-b8e7b080-d5da-11ea-9b7c-c95fdb7e646a.png)

**Comment by ztedu** [comment]
你好，麻烦问一下您的【请问在renderMenuData: (localMenu, serverMenu) => { 中，serverMenu的数据来自哪里？如果异步从服务器取数据，会出现菜单loading的提示吗？】这个问题解决了吗？

**Comment by effapp** [comment]
> 你好，麻烦问一下您的【请问在renderMenuData: (localMenu, serverMenu) => { 中，serverMenu的数据来自哪里？如果异步从服务器取数据，会出现菜单loading的提示吗？】这个问题解决了吗？

没有解决，我目前把菜单写死在config.ts的路由中，等新版出来解决了这个问题，再把菜单移值到服务端。

**Comment by chenshuai2144** [comment]
```
  "postinstall": "umi g tmp",
```
src/access.ts

这两个存在了吗

**Comment by fangniu** [comment]
> 你好，麻烦问一下您的【请问在renderMenuData: (localMenu, serverMenu) => { 中，serverMenu的数据来自哪里？如果异步从服务器取数据，会出现菜单loading的提示吗？】这个问题解决了吗？

@chenshuai2144 大佬，这个serverMenu从哪来的啊，看了好几个文档，都没有提到这个

**Comment by chenshuai2144** [comment]
用 useState 存起来的服务器数据
