### ISSUE TITLE
🧐[问题]脚手架选择JavaScript却生成出TypeScript的代码

### ISSUE THREAD

**Issue by iHDJ** [ant-design/ant-design-pro#7141]

**Comment by iHDJ** [comment]
离谱 没人看issue

**Comment by iHDJ** [comment]
@chenshuai2144

**Comment by iHDJ** [comment]
@chenshuai2144

**Comment by iHDJ** [comment]
@chenshuai2144

**Comment by iHDJ** [comment]
@chenshuai2144

**Comment by 1tjackp0t** [comment]
我还以为我哪里没选对,搞了半天...

**Comment by iHDJ** [comment]
> 我还以为我哪里没选对,搞了半天...

你也遇到这种问题？

**Comment by 1tjackp0t** [comment]
> > 我还以为我哪里没选对,搞了半天...
> 
> 你也遇到这种问题？

是的,其实之前已经看到过类似的issue提出了,但是看来还是没得到解决?

**Comment by chenshuai2144** [comment]
dep of https://github.com/ant-design/ant-design-pro/issues/7118
