### ISSUE TITLE
请问如何单独的展开一项菜单栏

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#7142]
### 🧐 问题描述
版本：antd pro : v5

文档上没看到，关于如何设置展开的菜单栏的方法，大概就是下面图片一样的功能
### 💻 示例代码
![image](https://user-images.githubusercontent.com/23183393/89274259-3f4fd100-d673-11ea-8acf-2ab13abf9f02.png)

**Comment by chenshuai2144** [comment]
用 openKeys 和 onOpenChange 受控的来搞。

我们默认是只打开一个的，并且打开的当前选中的菜单

**Comment by xyy7260** [comment]
@chenshuai2144  好的谢谢
