### ISSUE TITLE
🧐[问题] 请问使用 Ant Design Pro V4 时如何禁用生产环境下的 Redux DevTools

### ISSUE THREAD

**Issue by elyotlee** [ant-design/ant-design-pro#7144]
### 🧐 问题描述

我希望项目部署后，浏览器调试工具选项卡中不会出现 Redux DevTools，请问在 Ant Design Pro V4 (TypeScript版本) 中该如何实现？

**Comment by chenshuai2144** [comment]
这个我记得是不行的，只能删除这个插件的了
