### ISSUE TITLE
v5 mix 模式，侧边栏二级菜单图标不显示🐛[BUG]

### ISSUE THREAD

**Issue by li515422618** [ant-design/ant-design-pro#7146]
### 🐛 bug 描述

v5版本，mix模式，侧边栏二级菜单图标不显示
### 📷 复现步骤

config.ts 文件admin部分代码
{
      path: '/admin',
      name: 'admin',
      icon: 'crown',
      access: 'canAdmin',
      // component: './Admin',
      routes: [
        {
          path: '/admin/sub-page',
          name: 'sub-page',
          icon: 'smile',
          routes: [
            {
              path: '/admin/sub-page/test',
              name: 'sub-page-test',
              icon: 'smile',
              component: './Welcome',
            }
          ]
        },
      ],
    },

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. windows 10]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17846480/89393282-2a3f7480-d73d-11ea-8891-5f6cd155e365.png)

![image](https://user-images.githubusercontent.com/17846480/89393618-a2a63580-d73d-11ea-85b4-f90915e39a98.png)

**Comment by chenshuai2144** [comment]
这是个设计，我们不会打开的，相关的 hack 看这里
https://github.com/ant-design/ant-design-pro-layout/issues/525
