### ISSUE TITLE
🐛[BUG]下载最新的pro4之后，项目文件有TS报错;

### ISSUE THREAD

**Issue by LQCreator** [ant-design/ant-design-pro#7147]
### 🐛 bug 描述

下载最新的pro4之后，项目文件有TS报错;
npm run tsc有很多报错
![image](https://user-images.githubusercontent.com/8773714/89399074-88bc2100-d744-11ea-86d7-0f8af865af9c.png)
![image](https://user-images.githubusercontent.com/8773714/89399137-a12c3b80-d744-11ea-95c5-b5a7e5e215f9.png)

**Comment by chenshuai2144** [comment]
项目里已经没有这种代码了，你是在哪里找到的？

**Comment by LQCreator** [comment]
@chenshuai2144 前两天利用npm create umi自动安装的，选择了typescript的版本，还没做任何修改

**Comment by chenshuai2144** [comment]
block 里面的内容，blocks 的ci 没走tsc
