### ISSUE TITLE
浏览器调试无法进行，全是编译之后的代码

### ISSUE THREAD

**Issue by flysheet** [ant-design/ant-design-pro#715]
升级到1.0.0之后，在谷歌浏览器调试，f12出现的已经是编译之后的代码了，没法调试了
全是下面这样的代码。
exports = module.exports = require("../../node_modules/css-loader/lib/css-base.js")(false);
// imports

// exports
exports.locals = {
	"container": "container___1qll8",
	"top": "top___dAPWE",
	"header": "header___3xyac",
	"logo": "logo___3yv0h",
	"title": "title___2SlIy",
	"desc": "desc___1uABx",
	"footer": "footer___1tybZ"
};

**Comment by chenshuai2144** [comment]
map的级别调整的有点低了。。。 我去排查一下

**Comment by chenshuai2144** [comment]
[[Roadhog 2] devtool选项不能正确生成source map](https://github.com/sorrycc/roadhog/issues/554)

**Comment by topmyself** [comment]
roadhog@2.3.0-beta.1解决这个问题了
