### ISSUE TITLE
🐛[BUG] Unable to install ant-design-pro

### ISSUE THREAD

**Issue by pravishanth** [ant-design/ant-design-pro#7154]
Hi,

I am unable to install, I get these errors when I run the command: `yarn create umi`

Couldn't find package "@umijs/fabric@^1.1.7" required by "sylvanas@^0.4.0" on the "npm" registry.
Couldn't find package "@mrmlnc/readdir-enhanced@^2.2.1" required by "fast-glob@^2.0.2" on the "npm" registry.

Please suggest a way forward

**Comment by afc163** [comment]
npm 挂了，等恢复。
