### ISSUE TITLE
🧐[问题] 怎么通过iframe只嵌入目标页面的指定部分

### ISSUE THREAD

**Issue by wangyf123** [ant-design/ant-design-pro#7158]
### 🧐 问题描述

比如：需要将grafan的监控页嵌入到antd pro开发的web page中，但想把页面的左侧竖长条屏蔽，只引入页面右侧的div
或者有没有除了iframe之外的其他方法呢？

### 💻 示例代码
当前的index.jsx中代码如下：
export default () => (

	<iframe style={{border:0,width:"100%", height: "100%"}} src="http://grafana.xxx/d/001"></iframe>
);

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/6194754/89642389-5c400a80-d8e6-11ea-8e63-da15ef9bf296.png)

**Comment by wangyf123** [comment]
![image](https://user-images.githubusercontent.com/6194754/89642630-b8a32a00-d8e6-11ea-93f3-bdeb399497a5.png)
需要屏蔽左侧竖长条

**Comment by wangyf123** [comment]
也就是取到这个 class="main-view" 的div
![image](https://user-images.githubusercontent.com/6194754/89643023-77f7e080-d8e7-11ea-8478-29e7c9da2e47.png)

**Comment by chenshuai2144** [comment]
你可以能需要通过 url 参数来隐藏了layout，可以试试这个 api


pure | 是否删除掉所有的自带界面 | boolean
-- | -- | --
