### ISSUE TITLE
🧐[问题] How can I refresh token with umi request?

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#7159]
### 🧐 问题描述
I use tokens as authorization, when the token expires, I want to create a new token using the refresh token. I can do this with the axios library but I couldn't find how to do it with umi request. Can you translate the code sample given below to an umi request interceptor example?

```
  let isRefreshing: boolean = false;
  let failedQueue: any = [];

  const processQueue = (error: any, token: any = null) => {
    failedQueue.forEach((prom: any) => {
      if (error) {
        prom.reject(error);
      } else {
        prom.resolve(token);
      }
    });

    failedQueue = [];
  };

axios.interceptors.response.use(
    async response => {
      return response;
    },
    async error => {
      debugger;
      const originalRequest = error.config;
      if (error.response) {
        const status = error.response.status;
        const refreshToken = getStoredUserAuth().refreshToken;
        if (status === 401 && !originalRequest._retry) {
          if (isRefreshing) {
            return new Promise(function(resolve, reject) {
              failedQueue.push({ resolve, reject });
            })
              .then(token => {
                originalRequest.headers["Authorization"] = "Bearer " + token;
                return axios(originalRequest);
              })
              .catch(err => {
                return Promise.reject(err);
              });
          }

          originalRequest._retry = true;
          isRefreshing = true;

          return new Promise(function(resolve, reject) {
            refreshAccessToken(refreshToken)
              .then(response => {
                if (response.status === 200) {
                  if (response.data.token) {
                    setAuthStatus(response.data);
                    axios.defaults.headers.common["Authorization"] =
                      "Bearer " + response.data.token;
                    originalRequest.headers["Authorization"] =
                      "Bearer " + response.data.token;
                  }
                  processQueue(null, response.data.token);
                  resolve(axios(originalRequest));
                } else {
                  throw new Error();
                }
              })
              .catch(err => {
                //console.log(err);
                failedQueue = [];
                setUnauthStatus();
                source.cancel("Session time out");
                processQueue(err, null);
                reject(err);
              })
              .then(() => {
                isRefreshing = false;
              });
          });
        }
      } else {
        debugger;
        errorHandler(error);
      }
      return Promise.reject(error);
    }
  );
```

**Comment by xXAvoraXx** [comment]
+1

**Comment by xXAvoraXx** [comment]
++1

**Comment by xXAvoraXx** [comment]
> ### 🧐 问题描述
> I use tokens as authorization, when the token expires, I want to create a new token using the refresh token. I can do this with the axios library but I couldn't find how to do it with umi request. Can you translate the code sample given below to an umi request interceptor example?
> 
> ```
>   let isRefreshing: boolean = false;
>   let failedQueue: any = [];
> 
>   const processQueue = (error: any, token: any = null) => {
>     failedQueue.forEach((prom: any) => {
>       if (error) {
>         prom.reject(error);
>       } else {
>         prom.resolve(token);
>       }
>     });
> 
>     failedQueue = [];
>   };
> 
> axios.interceptors.response.use(
>     async response => {
>       return response;
>     },
>     async error => {
>       debugger;
>       const originalRequest = error.config;
>       if (error.response) {
>         const status = error.response.status;
>         const refreshToken = getStoredUserAuth().refreshToken;
>         if (status === 401 && !originalRequest._retry) {
>           if (isRefreshing) {
>             return new Promise(function(resolve, reject) {
>               failedQueue.push({ resolve, reject });
>             })
>               .then(token => {
>                 originalRequest.headers["Authorization"] = "Bearer " + token;
>                 return axios(originalRequest);
>               })
>               .catch(err => {
>                 return Promise.reject(err);
>               });
>           }
> 
>           originalRequest._retry = true;
>           isRefreshing = true;
> 
>           return new Promise(function(resolve, reject) {
>             refreshAccessToken(refreshToken)
>               .then(response => {
>                 if (response.status === 200) {
>                   if (response.data.token) {
>                     setAuthStatus(response.data);
>                     axios.defaults.headers.common["Authorization"] =
>                       "Bearer " + response.data.token;
>                     originalRequest.headers["Authorization"] =
>                       "Bearer " + response.data.token;
>                   }
>                   processQueue(null, response.data.token);
>                   resolve(axios(originalRequest));
>                 } else {
>                   throw new Error();
>                 }
>               })
>               .catch(err => {
>                 //console.log(err);
>                 failedQueue = [];
>                 setUnauthStatus();
>                 source.cancel("Session time out");
>                 processQueue(err, null);
>                 reject(err);
>               })
>               .then(() => {
>                 isRefreshing = false;
>               });
>           });
>         }
>       } else {
>         debugger;
>         errorHandler(error);
>       }
>       return Promise.reject(error);
>     }
>   );
> ```
> 
> ### 💻 示例代码
> ### 🚑 其他信息

**Comment by chenshuai2144** [comment]
hi boy， look here https://github.com/umijs/umi-request

**Comment by xXAvoraXx** [comment]
> hi boy， look here https://github.com/umijs/umi-request

Of course, I know there, I could'nt write look like that example

**Comment by chenshuai2144** [comment]
i think like  this
```tsx
// request interceptor, change url or options.
request.interceptors.request.use((url, options) => {
  return {
    url: `${url}&interceptors=yes`,
    options: { ...options, interceptors: true },
  };
});

// Same as the last one
request.interceptors.request.use(
  (url, options) => {
    return {
      url: `${url}&interceptors=yes`,
      options: { ...options, interceptors: true },
    };
  },
  { global: true }
);

// response interceptor, chagne response
request.interceptors.response.use((response, options) => {
  response.headers.append('interceptors', 'yes yo');
  return response;
});

// handling error in response interceptor
request.interceptors.response.use(response => {
  const codeMaps = {
    502: '网关错误。',
    503: '服务不可用，服务器暂时过载或维护。',
    504: '网关超时。',
  };
  message.error(codeMaps[response.status]);
  return response;
});

// clone response in response interceptor
request.interceptors.response.use(async response => {
  const data = await response.clone().json();
  if (data && data.NOT_LOGIN) {
    location.href = '登录url';
  }
  return response;
});
```

**Comment by xXAvoraXx** [comment]
> i think like this
> 
> ```tsx
> // request interceptor, change url or options.
> request.interceptors.request.use((url, options) => {
>   return {
>     url: `${url}&interceptors=yes`,
>     options: { ...options, interceptors: true },
>   };
> });
> 
> // Same as the last one
> request.interceptors.request.use(
>   (url, options) => {
>     return {
>       url: `${url}&interceptors=yes`,
>       options: { ...options, interceptors: true },
>     };
>   },
>   { global: true }
> );
> 
> // response interceptor, chagne response
> request.interceptors.response.use((response, options) => {
>   response.headers.append('interceptors', 'yes yo');
>   return response;
> });
> 
> // handling error in response interceptor
> request.interceptors.response.use(response => {
>   const codeMaps = {
>     502: '网关错误。',
>     503: '服务不可用，服务器暂时过载或维护。',
>     504: '网关超时。',
>   };
>   message.error(codeMaps[response.status]);
>   return response;
> });
> 
> // clone response in response interceptor
> request.interceptors.response.use(async response => {
>   const data = await response.clone().json();
>   if (data && data.NOT_LOGIN) {
>     location.href = '登录url';
>   }
>   return response;
> });
> ```

I use to ant design pro V5 version, so I've tried to refresh token with umi request but I could'nt do it, As in the axios library, I cannot write for umi request, I cannot establish its logic. So can anyone write the same example (axios.interceptors.response) above for umi request?

```
const requestInterceptors = (url: string, options: RequestOptionsInit) => {
  if (tokenService.check()) {
    const headers = {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Accept': 'application/x-www-form-urlencoded',
      'Authorization': `Bearer ${tokenService.parse()?.token}`,
    };
    return {
      url,
      options: { ...options, headers },
    };
  }
  return {
    url,
    options: { ...options },
  };
};

const responseInterceptors = (response: Response, options: RequestOptionsInit) => {
return response;
}

export const request: RequestConfig = {
  errorHandler,
  requestInterceptors: [requestInterceptors],
  responseInterceptors: [responseInterceptors]
};
```

**Comment by xXAvoraXx** [comment]
I got that error how can I solve this ?

Type '(response: Response) => Promise<unknown>' is not assignable to type 'ResponseInterceptor'.
  Type 'Promise<unknown>' is not assignable to type 'Response | Promise<Response>'.
    Type 'Promise<unknown>' is not assignable to type 'Promise<Response>'.
      Type 'unknown' is not assignable to type 'Response'.

```
interface ResponseExtend extends Response {
  retry: boolean;
}

const responseInterceptors = async (response: Response) => {
  const originalRequest: ResponseExtend = await response.clone().json();
  if (response) {
    const { status } = response;
    const refreshToken = tokenService.parse()?.refreshToken;
    if (status === 401 && !originalRequest.retry) {
      if (isRefreshing) {
        return new Promise((resolve, reject) => {
          failedQueue.push({ resolve, reject });
        })
          .then(token => {
            originalRequest.headers.append('Authorization', `Bearer ${token}`);
            return originalRequest;
          })
          .catch(err => {
            return Promise.reject(err);
          });
      }
      originalRequest.retry = true;
      isRefreshing = true;

      return new Promise((resolve, reject) => {
        refreshAccessToken(refreshToken!)
          .then(res => {
            if (res.status === 200) {
              if (res.data.token) {
                // setAuthStatus(res.data);
                // axios.defaults.headers.common["Authorization"] =
                //   "Bearer " + res.data.token;
                originalRequest.headers.append('Authorization', `Bearer ${res.data.token}`);
              }
              processQueue(null, res.data.token);
              resolve(originalRequest);
            } else {
              throw new Error();
            }
          })
          .catch(err => {
            // console.log(err);
            failedQueue = [];
            // setUnauthStatus();
            // source.cancel("Oturum Zaman Aşımına Uğradı.");
            processQueue(err, null);
            reject(err);
          })
          .then(() => {
            isRefreshing = false;
          });
      });
    }
    
  }


  return response;
}
```

**Comment by xXAvoraXx** [comment]
https://github.com/umijs/umi-request/issues/181

I need helppppppppppp

**Comment by fei199225** [comment]
> [umijs/umi-request#181](https://github.com/umijs/umi-request/issues/181)
> 
> I need helppppppppppp

I have the same problem as you.
Did you solve it?🥺

**Comment by newketom** [comment]
here is my solution in v5 app.tsx:

```
const tokenRequestInterceptor: RequestInterceptor = (url: string, options: RequestOptionsInit) => {
  const token = localStorage.getItem('antd-pro-token');

  return {
    url,
    options: {
      ...options,
      headers: {
        ...options.headers,
        Authorization: `Bearer ${token}`,
      },
    },
  };
};

export const request: RequestConfig = {
  errorHandler,
  requestInterceptors: [tokenRequestInterceptor],
};
```

**Comment by xXAvoraXx** [comment]
> > [umijs/umi-request#181](https://github.com/umijs/umi-request/issues/181)
> > I need helppppppppppp
> 
> I have the same problem as you.
> Did you solve it?🥺

I tried this one work correctly but not perfect, I still working new one.

```
import { history, RequestConfig, request as requestUmi } from 'umi';
import Reqs, { ResponseError, RequestOptionsInit } from 'umi-request';
// import jwt_decode from "jwt-decode";
import tokenService from './services/token';
import { refreshAccessToken } from './services/login';

const { source } = Reqs.CancelToken;
const { cancel } = source();

let isRefreshing: boolean = false;
let failedQueue: any = [];

const processQueue = (error: any, token: any = null) => {
  failedQueue.forEach((prom: any) => {
    if (error) {
      prom.reject(error);
    } else {
      prom.resolve(token);
    }
  });

  failedQueue = [];
};
// interface RequestOptionsExtend extends RequestOptionsInit {
//   retry?: boolean;
// }
const responseInterceptors = (response: Response, options: RequestOptionsInit) => {
  const { status } = response;
  // const originalRequest: RequestOptionsExtend = options;
  const refreshToken = tokenService.parse()?.refreshToken;

  if (status === 401) {
    if (isRefreshing) {
      return new Promise<Response>((resolve, reject) => {
        failedQueue.push({ resolve, reject });
      })
        .then(token => {
          return requestUmi(response.url, { ...options, headers: { Authorization: `Bearer ${token}` } });
        })
        .catch(err => {
          return Promise.reject(err);
        });
    }

    // originalRequest.retry = true;
    isRefreshing = true;

    return new Promise<Response>((resolve, reject) => {
      refreshAccessToken(refreshToken!)
        .then(res => {
          if (res) {
            if (res.token) {
              tokenService.save(res);
            }
            processQueue(null, res.token);
            resolve(requestUmi(response.url, { ...options, headers: { Authorization: `Bearer ${res.token}` } }));
          } else {
            throw new Error();
          }
        })
        .catch(err => {
          failedQueue = [];
          tokenService.remove();
          cancel("Session time out.");
          processQueue(err, null);
          reject(err);
        })
        .then(() => {
          isRefreshing = false;
        });
    });
  }

  return response;
}

export const request: RequestConfig = {
  errorHandler,
  headers: {
    'Authorization': `Bearer ${tokenService.parse()?.token}`
  },
  // requestInterceptors: [requestInterceptors],
  responseInterceptors: [responseInterceptors]
};
```

**Comment by xXAvoraXx** [comment]
@fei199225 I found such a solution, I think you have found it before. I'm trying to edit this solution according to the current ant-design pro typescript version, but it gives an error in the promise part.

 https://www.cnblogs.com/qkstart/p/11856168.html

That's why the example I gave above seems to be the solution for now.

**_If you have better solution, please share it bellow._**

**Comment by loia5tqd001** [comment]
> > > [umijs/umi-request#181](https://github.com/umijs/umi-request/issues/181)
> > > I need helppppppppppp
> > 
> > 
> > I have the same problem as you.
> > Did you solve it?🥺
> 
> I tried this one is work correctly but not perfect, I still working new one.
> 
> **_If you have better solution, please share it bellow._**
> 
> ```
> import { history, RequestConfig, request as requestUmi } from 'umi';
> import Reqs, { ResponseError, RequestOptionsInit } from 'umi-request';
> // import jwt_decode from "jwt-decode";
> import tokenService from './services/token';
> import { refreshAccessToken } from './services/login';
> 
> const { source } = Reqs.CancelToken;
> const { cancel } = source();
> 
> let isRefreshing: boolean = false;
> let failedQueue: any = [];
> 
> const processQueue = (error: any, token: any = null) => {
>   failedQueue.forEach((prom: any) => {
>     if (error) {
>       prom.reject(error);
>     } else {
>       prom.resolve(token);
>     }
>   });
> 
>   failedQueue = [];
> };
> // interface RequestOptionsExtend extends RequestOptionsInit {
> //   retry?: boolean;
> // }
> const responseInterceptors = (response: Response, options: RequestOptionsInit) => {
>   const { status } = response;
>   // const originalRequest: RequestOptionsExtend = options;
>   const refreshToken = tokenService.parse()?.refreshToken;
> 
>   if (status === 401) {
>     if (isRefreshing) {
>       return new Promise<Response>((resolve, reject) => {
>         failedQueue.push({ resolve, reject });
>       })
>         .then(token => {
>           return requestUmi(response.url, { ...options, headers: { Authorization: `Bearer ${token}` } });
>         })
>         .catch(err => {
>           return Promise.reject(err);
>         });
>     }
> 
>     // originalRequest.retry = true;
>     isRefreshing = true;
> 
>     return new Promise<Response>((resolve, reject) => {
>       refreshAccessToken(refreshToken!)
>         .then(res => {
>           if (res) {
>             if (res.token) {
>               tokenService.save(res);
>             }
>             processQueue(null, res.token);
>             resolve(requestUmi(response.url, { ...options, headers: { Authorization: `Bearer ${res.token}` } }));
>           } else {
>             throw new Error();
>           }
>         })
>         .catch(err => {
>           failedQueue = [];
>           tokenService.remove();
>           cancel("Session time out.");
>           processQueue(err, null);
>           reject(err);
>         })
>         .then(() => {
>           isRefreshing = false;
>         });
>     });
>   }
> 
>   return response;
> }
> 
> export const request: RequestConfig = {
>   errorHandler,
>   headers: {
>     'Authorization': `Bearer ${tokenService.parse()?.token}`
>   },
>   // requestInterceptors: [requestInterceptors],
>   responseInterceptors: [responseInterceptors]
> };
> ```

What do you mean by "not perfect"?

**Comment by loia5tqd001** [comment]
Here's my solution, works like a charm

```typescript
// Neccesary imports
import type { RequestConfig } from 'umi';
import { request as requestUmi } from 'umi';
import type {
  RequestInterceptor,
  RequestOptionsInit,
  ResponseError,
} from 'umi-request';
import Reqs from 'umi-request';
import merge from 'lodash/merge';
import cloneDeep from 'lodash/cloneDeep';

// My personal type definitions
namespace API {
  export interface LoginResult {
    access: string;
    refresh: string;
  }
}

// Part 1: "Simple" Error Handler =))
const errorHandler = (error: ResponseError) => {
  console.log('HTTP ERROR', error);
  throw error;
};

// Part 2: Request Interceptors, (use this instead of "headers" directly in request config)
const requestInterceptor: RequestInterceptor = (url, options) => {
  return {
    url,
    options: merge(cloneDeep(options), {
      headers: { Authorization: `Bearer ${jwt.getAccess()}` },
    }),
  };
};

// Part 3: Response Interceptos
const { cancel } = Reqs.CancelToken.source();
let refreshTokenRequest: Promise<API.LoginResult> | null = null;
const responseInterceptor = async (
  response: Response,
  options: RequestOptionsInit
) => {
  const accessTokenExpired = response.status === 401;
  if (accessTokenExpired) {
    try {
      if (!refreshTokenRequest) {
        refreshTokenRequest = refreshAccessToken(jwt.getRefresh());
      }
      // multiple requests but "await"ing for only 1 refreshTokenRequest, because of closure
      const res = await refreshTokenRequest;
      if (!res) throw new Error();
      if (res.access) jwt.saveAccess(res.access);
      if (res.refresh) jwt.saveRefresh(res.refresh); // for ROTATE REFRESH TOKENS
      return requestUmi(
        response.url,
        merge(cloneDeep(options), {
          headers: { Authorization: `Bearer ${res.access}` },
        })
      );
    } catch (err) {
      jwt.removeAccess();
      jwt.removeRefresh();
      cancel('Session time out.');
      throw err;
    } finally {
      refreshTokenRequest = null;
    }
  }

  return response;
};

export const request: RequestConfig = {
  errorHandler,
  // This would fuck the refresh token logic, use requestInterceptors instead,
  // because jwt.getAccess() will not being called everytime, but only the first time => lead to stale access token
  // headers: { Authorization: `Bearer ${jwt.getAccess()}` },

  // Handle refresh token (old): https://github.com/ant-design/ant-design-pro/issues/7159#issuecomment-680789397
  // Handle refresh token (new): https://gist.github.com/paulnguyen-mn/8a5996df9b082c69f41bc9c5a8653533
  requestInterceptors: [requestInterceptor],
  responseInterceptors: [responseInterceptor],
};

```
