### ISSUE TITLE
Authorized权限组件和dva/router强耦合

### ISSUE THREAD

**Issue by HeskeyBaozi** [ant-design/ant-design-pro#716]
在没有使用`dva`的项目中，引入`Authorized`组件
```typescript
import RenderAuthorized from 'ant-design-pro/lib/Authorized';
```

`Roadhog`会编译失败并报错
```
./node_modules/ant-design-pro/lib/Authorized/AuthorizedRoute.js
Module not found: Can't resolve 'dva/router' in 'D:\WebProject\dva-course-fe\node_modules\ant-design-pro\lib\Authorized'
```

[源代码 AuthorizedRoute.js#L2](https://github.com/ant-design/ant-design-pro/blob/f9f8eb00df614b3732f8f3e15c03fa885b7f3781/src/components/Authorized/AuthorizedRoute.js#L2)中路由依赖于`dva/router`

期望：
至少引入`react-router`而不是`dva/router`，不想和`dva`强制耦合

**Comment by chenshuai2144** [comment]
dva/router 就是 react-router.
你这个要求是合理的。我测试一下会不会有问题
