### ISSUE TITLE
升级成V4后，每次刷新页面，Authorized.js好像不起作用了，如何恢复到每次刷新都经过这个文件呢，谢谢！🧐[问题]

### ISSUE THREAD

**Issue by leehaoxindehao** [ant-design/ant-design-pro#7160]

**Comment by chenshuai2144** [comment]
方便给一个最小重现的 repo 吗？

**Comment by Zhou-Bill** [comment]
我也好像是，我版本是 antd-design-pro 4.1.0 是官方那个项目，我在pages/Authorized.tsx 无论在这个文件打印什么都好像不经过这个文件，

**Comment by leehaoxindehao** [comment]
> 方便给一个最小重现的 repo 吗？

我下载了官方antdProV4的版本，但是即使我在config.js文件中添加了 Routes: ['src/pages/Authorized'],还是不能控制页面权限，并且在pages/Authorized.tsx的render下打印，好像不会经过了。请问下，现在需要进行页面权限的控制和需要每次进行页面切换都进过pages/Authorized.tsx这个页面，能够实现吗？谢谢了

**Comment by chenshuai2144** [comment]
直接在这里判断吧，v4

https://github.com/ant-design/ant-design-pro/blob/master/src/layouts/BasicLayout.tsx
