### ISSUE TITLE
🧐左侧Menu里的Icon偏移错位

### ISSUE THREAD

**Issue by ZidiHu** [ant-design/ant-design-pro#7162]
### 🧐 问题描述

<img width="253" alt="Screen Shot 2020-08-09 at 5 26 59 pm" src="https://user-images.githubusercontent.com/50161886/89727194-d4810a00-da65-11ea-9839-4599867f2e96.png">
左侧menu里icon和文字没有水平对齐，icon有点往下偏移，怀疑是自己写的样式覆盖了anticon的样式，但是检查了一下好像并没有覆盖，不知道是什么原因，想请问大家是否有遇到类似问题或者解决办法，先谢过。

### 💻 示例代码

<img width="774" alt="Screen Shot 2020-08-09 at 5 26 38 pm" src="https://user-images.githubusercontent.com/50161886/89727244-1d38c300-da66-11ea-8166-d8249ecd6a23.png">

### 🚑 其他信息

<img width="353" alt="Screen Shot 2020-08-09 at 5 32 02 pm" src="https://user-images.githubusercontent.com/50161886/89727263-45282680-da66-11ea-9d3a-f53e9747f341.png">

**Comment by chenshuai2144** [comment]
这个应该是你自定义导致的，用 css hack 吧，菜单的 dom 结构很复杂
