### ISSUE TITLE
跪求https://preview.pro.ant.design/ 源码地址

### ISSUE THREAD

**Issue by dragonforce2010** [ant-design/ant-design-pro#7163]
请问哪位大佬知道这个示例网站（https://preview.pro.ant.design/）的源码在哪里？跪求参考orz

**Comment by onecmd** [comment]
https://pro.ant.design/docs/getting-started-cn 按这个创建出来的（选Completed）就是了吧，本地启动就一样的

**Comment by onecmd** [comment]
好像还引用了这个： https://procomponents.ant.design/components/layout

**Comment by chenshuai2144** [comment]
嫌麻烦可以直接 `all-blocks`


https://github.com/ant-design/ant-design-pro/tree/all-blocks

**Comment by dragonforce2010** [comment]
多谢大家 终于看到全部组件啦😺
