### ISSUE TITLE
ProTable组件的全屏模式下弹出框被挡住，取消全屏后可以看到弹出框🐛[BUG]

### ISSUE THREAD

**Issue by Huangxiaoyan71** [ant-design/ant-design-pro#7164]
#7162 ## 🐛 bug 描述

ProTable组件的全屏模式下弹出框被挡住，取消全屏后可以看到弹出框

### 📷 复现步骤

1.  查询表格 -> 点击”全屏“按钮。
2. 点击“新建”按钮，无法看到弹出框。
3. 取消全屏，弹出框出现。

### 🏞 期望结果

全屏下点击“新建”按钮可以看到弹出框

### 💻 复现代码

https://github.com/ant-design/ant-design-pro

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
1. 全屏后无法显示弹出框
<img width="1440" alt="截屏2020-08-09 下午5 57 12" src="https://user-images.githubusercontent.com/24107008/89729724-08126300-da6b-11ea-9f59-536c90bd4cc4.png">
2. 取消全屏可以看到弹出框
<img width="1440" alt="截屏2020-08-09 下午6 07 18" src="https://user-images.githubusercontent.com/24107008/89729740-342de400-da6b-11ea-8ae6-a7504dea0dd1.png">

**Comment by chenshuai2144** [comment]
ProTable 的全屏只能全屏 自己的 dom，你要把 model render 到 table 的 dom 里才能正常使用。

```tsx

<ConfigProvider getPopupContainer={()=>document.getElementById('ant-design-pro-table')}>
{your modal}
</ConfigProvider>
```
https://ant.design/components/config-provider-cn/
https://developer.mozilla.org/zh-CN/docs/Web/API/Fullscreen_API

**Comment by Huangxiaoyan71** [comment]
谢谢😊解决了。 ant design pro v5的官方示例也有这个问题。 在2020年08月09日 20:50，陈帅 写道： ProTable 的全屏只能全屏 自己的 dom，你要把 model render 到 table 的 dom 里才能正常使用。 <ConfigProvider getPopupContainer={()=>document.getElementById('ant-design-pro-table')}>

{your modal}

</ConfigProvider> https://ant.design/components/config-provider-cn/ https://developer.mozilla.org/zh-CN/docs/Web/API/Fullscreen_API — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
