### ISSUE TITLE
🧐[问题]如何修改Header导航栏选中菜单的背景颜色

### ISSUE THREAD

**Issue by onecmd** [ant-design/ant-design-pro#7166]
### 🧐 问题描述
我修改 config/config.js实现修改了导航栏背景颜色:

theme: {
    // ...darkTheme,
    'primary-color': defaultSettings.primaryColor,
    "layout-header-background": defaultSettings.layoutHeaderBackground,
  },

有哪一个变量可以用来修改选中的菜单的背景颜色（menu-item-active-bg这个只能修改子菜单的）?

![image](https://user-images.githubusercontent.com/3389081/89731074-da331b80-da76-11ea-9749-d0e1d838a669.png)

**Comment by chenshuai2144** [comment]
是   @menu-highlight-color;
```less
  &-submenu-selected {
    color: @menu-highlight-color;
  }
```

https://github.com/ant-design/ant-design/blob/f964abc7f432b6b56521e52b9b1b1da03d078887/components/menu/style/index.less#L54

**Comment by onecmd** [comment]
好像不是这个呢，我试了下：
![image](https://user-images.githubusercontent.com/3389081/89737247-234c9500-daa2-11ea-8f28-2854231bd748.png)

**Comment by ivsass** [comment]
解决了吗  老铁？   相同问题，我也想改下选中后的颜色，能分享一下吗？

**Comment by my9988** [comment]
> 
> 
> 能分享一下吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

@onecmd  这里有所有可以修改的颜色，顶部导航和右侧导航的颜色是不一样的

**Comment by wi100sh** [comment]
config/config.js的属性，调整导航菜单和选中菜单的背景色，目前是有效的。  
theme: {
    'primary-color': defaultSettings.primaryColor,
   "layout-header-background": "#FF0000"  // Menu导航菜单的背景色（参考本帖）
    "@menu-dark-item-active-bg":"#00FF00"  // 选中菜单的背景颜色  
  }
