### ISSUE TITLE
👑 [需求] 用户登录得时候，能不能也弄一个滑动验证，而且和后端交互得滑动验证

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7167]
### 🥰 需求描述

             Ant Pro 用了很久了，越来越强壮了！

            就有一个遗憾，验证尽然还是验证码！太LOW 了，就像一个现代的中国人，还留着大清朝的辫子！

             官方能不能也出一个滑动验证的模块！

**Comment by huntdream** [comment]
滑动验证自己集成第三方的模块就行了吧，这个没那么简单，人家都是拿来卖的 🤣

**Comment by chenshuai2144** [comment]
滑动验证 这个东西要前后端配合的，实现起来没那么简单，

这个东西要去买 sass 服务的

**Comment by hihuangwei** [comment]
腾讯验证码  007.qq.com

**Comment by hot588** [comment]
> 滑动验证 这个东西要前后端配合的，实现起来没那么简单，
> 
> 这个东西要去买 sass 服务的，可以问问大家有没有性价比比较高的服务

这个可以弄一个体验啊，把功能开发出来，使用者直接对接后端，或者开发的密匙，不就简单了嘛！

帅哥，抓紧弄一个吧！

**Comment by afc163** [comment]
建议自行搜索社区实现。
