### ISSUE TITLE
二期开发任务

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-pro#717]
### 新增页面

- 对话框 (Modal)
 	- [x] 分步对话框 `@ddcat1115`
 	 	- 对话框一
 	 	- 对话框二
 	 	- 对话框三
 	- [x] 信息录入对话框 `@valleykid`
 	 	- 录入页
 	 	- 结果页
- 个人设置页 `@chenshuai2144`
 	- [x] 基本设置
 	- [x] 安全设置
 	- [x] 账号绑定
 	- [x] 新消息通知
- [x] 个人中心页 `@ddcat1115`

### 新增模块/业务组件

- [x] 顶部导航 NavBar-Top`@chenshuai2144`

### 其他

- [x] 文档翻译
- [x] 脚手架国际化支持
- [x] 增加侧边栏配置项（支持布局、主题等配置切换）
- [x] 支持布局选择（侧边栏导航 - 顶部导航（只支持 basic 模式顶部导航））
- [x] 支持主题选择
- [x] 升级文档

---
以上是目前已经确定的部分，可能有变动或新增

**Comment by tianlinzx** [comment]
顶部导航 NavBar-Top，支持这个。

**Comment by chenshuai2144** [comment]
个人设置页 Assignees给我吧。

**Comment by kaoding** [comment]
这几个都很好，都有很实用的价值。

**Comment by accaolei** [comment]
开始细化了，good

**Comment by lifeixiang027** [comment]
有没有计划做搜索页面？

**Comment by ddcat1115** [comment]
@lifeixiang027 具体长什么样子？

**Comment by jove9834** [comment]
会有umi版本吗？

**Comment by mb-workspace** [comment]
话不多说：富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！富文本编辑器！

哪怕是集成社区的呢都可以啊

**Comment by valleykid** [comment]
信息录入对话框 我做吧

**Comment by afc163** [comment]
@mb-workspace 可以先看看 https://pro.ant.design/docs/import-cn

后续我们会尝试集成一个符合 antd 风格的社区编辑器。

**Comment by afc163** [comment]
加上侧边配置栏的部分。

**Comment by potcode** [comment]
大赞ant design， 另外想问一下pro 2.0版本上线有具体时间吗？

**Comment by hqwlkj** [comment]
期待 ant design pro 2.0 上线 

点击支持 ant design

**Comment by cranehe** [comment]
期待2.0，继续学习1.x，大大的👍ant design

**Comment by aihua** [comment]
需要补充v1.x向v2的升级文档

**Comment by tianlinzx** [comment]
2期的功能在各个分支差不多都实现了，什么时候最终合并分支打包发布啊？

**Comment by chenshuai2144** [comment]
2期功能只是有了基本雏形，我们还需要继续打磨

**Comment by kaoding** [comment]
最近好像搞的比较慢，好像精力不放在这个上面啊！

**Comment by yyhuaisha** [comment]
希望能够早日用上二期

**Comment by camry** [comment]
什么时候上二期？

**Comment by billyshen26** [comment]
有没有专门更新用户认证模块的，比如JWT，OAuth2这些的使用； 还有请问有菜单数据从服务器端得到的示例么

**Comment by gucciwu** [comment]
JWT和OAuth修改request就可以了，把Token写到request header里面去，token可以登录的时候获取，user/fetchCurrent的时候更新，存到redux或者SessionStorage里面（类似Auth） @billyshen26

**Comment by tianlinzx** [comment]
热烈祝贺2.0Beta发布。

**Comment by chenshuai2144** [comment]
- [] drawer 提成 antd 组件。
- [] drawer 右上角要有关闭。

**Comment by sillyfeng** [comment]
现在2.0.beta 顶部导航已经支持了吗？ @chenshuai2144

**Comment by chenshuai2144** [comment]
支持了 可clone 2.0分支进行预览

**Comment by kaoding** [comment]
什么时候将V2合并到master？

**Comment by XLoong666** [comment]
建议增加
1.二级菜单可设置放在主体左边
2.菜单打开页面支持多标签便于切换

**Comment by chenshuai2144** [comment]
> 建议增加
1.二级菜单可设置放在主体左边
2.菜单打开页面支持多标签便于切换

pr 让生活更美好

**Comment by sillyfeng** [comment]
刚刚试了一下，感觉v2的横向菜单效果挺好的。目前是不是还在优化？当前如果菜单比较多一行放不下的话，就会挤到第二行。

**Comment by kaoding** [comment]
一行放不下的菜单，建议使用“三个点”（左中右或者上中下）标识为“更多”字样

**Comment by picodoth** [comment]
> 一行放不下的菜单，建议使用“三个点”（左中右或者上中下）标识为“更多”字样

+1 一般是这样做的

**Comment by afc163** [comment]
@picodoth Menu 组件最好能原生支持动态变化。

**Comment by picodoth** [comment]
https://github.com/react-component/menu/issues/148

**Comment by kaoding** [comment]
v2是否可以发布了？

**Comment by ybning** [comment]
v2什么时候出炉？很期待...😄😄😄

**Comment by WuJiY** [comment]
v2是否可以发布了？

**Comment by woodcode** [comment]
发布吧，就等米下锅了

**Comment by afc163** [comment]
@chenshuai2144 把新的 done 和 todo 补充到顶楼去吧

**Comment by kaoding** [comment]
老铁们再加油，把V2发布了，等米下锅。

**Comment by chenshuai2144** [comment]
明天 umi 发版本了就加

**Comment by hqwlkj** [comment]
@chenshuai2144   今天会发布吗？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/1512

**Comment by afc163** [comment]
- [ ] pro.ant.design 上的 v2 弹窗提示
- [ ] README 里的 v2 提示

**Comment by afc163** [comment]
<img width="244" alt="image" src="https://user-images.githubusercontent.com/507615/44718702-7d413380-aaf3-11e8-8f6e-8b03175742ed.png">

<img width="506" alt="image" src="https://user-images.githubusercontent.com/507615/44718730-96e27b00-aaf3-11e8-8f1d-6661d335fdf2.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/507615/44718736-9b0e9880-aaf3-11e8-8f10-b0cc8fd3d80b.png">

这几个地方也要改改。

**Comment by afc163** [comment]
- [ ] 404 页面 @chenshuai2144 
- [ ] 权限路由校验方案 + 401 页面 @afc163
- [ ] 文档更新 https://github.com/ant-design/ant-design-pro/issues/2007

**Comment by chenshuai2144** [comment]
2.0 已发布
