### ISSUE TITLE
🧐[新鲜的问题带求助]你们都是在什么时机获取用户信息的？关于获取用户信息的问题

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/ant-design-pro#7170]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/32796170/89761534-29ce2180-db21-11ea-9cdf-3eaa4af43065.png)
就是如果这个获取用户信息的请求时间很长，那么页面会有很长时间的白屏，影响美观效果，各位有什么解决办法么？另外全局loading好像不大行，毕竟这是个全局的初始化函数。求支招...

**Comment by li515422618** [comment]
一般来说用户信息属于可缓存的数据，在后端可以加上缓存，控制耗时在ms级别

**Comment by gameruleCEO** [comment]
> 一般来说用户信息属于可缓存的数据，在后端可以加上缓存，控制耗时在ms级别

嗯，但是不能保证请求暂时中断的可能。就可能中断了1~3秒。这种情况下就比较难受

**Comment by hot588** [comment]
估计你后端接后有问题，而不是前端的问题！

我看mock 弄得很好啊！

**Comment by gameruleCEO** [comment]
> 估计你后端接后有问题，而不是前端的问题！
> 
> 我看mock 弄得很好啊！

我模拟的，用mock延迟3秒

**Comment by Zzy0706** [comment]
我觉着某些基础的信息可以放在登录那块获取，这样就不用后面靠获取用户信息来进行权限认证了😑

**Comment by chenshuai2144** [comment]
有新的 api 可以解决这个问题
```
/**
 * 获取用户信息比较慢的时候会展示一个 loading
 */
export const initialStateConfig = {
  loading: <PageLoading />,
};
```
