### ISSUE TITLE
🐛[页面白屏]当请求用户信息时间很长时，页面会出现白屏，待解决

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/ant-design-pro#7171]
### 🐛 bug 描述
![复现图](https://user-images.githubusercontent.com/32796170/89765325-aca6aa80-db28-11ea-8900-d14bdd4dd28d.gif)
![代码1](https://user-images.githubusercontent.com/32796170/89765332-afa19b00-db28-11ea-9410-55bf4d13568d.png)
![代码2](https://user-images.githubusercontent.com/32796170/89765339-b4664f00-db28-11ea-85a0-e921c7f88345.png)
如图

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gameruleCEO** [comment]
目前我用官网demo也是这样

**Comment by chenshuai2144** [comment]
加了个新的 api
```
/**
 * 获取用户信息比较慢的时候会展示一个 loading
 */
export const initialStateConfig = {
  loading: <PageLoading />,
};
```

**Comment by RealWseven** [comment]
你好，请问最后怎么解决的？

**Comment by sibaiabis** [comment]
这个后续的antdpro版本不是解决了么，升级一下版本就好了

发自亖佰的iPhone12 pro max

**Comment by RealWseven** [comment]
> 这个后续的antdpro版本不是解决了么，升级一下版本就好了 发自亖佰的iPhone12 pro max
> […](#)
> On Jun 10, 2021, at 18:12, RealWseven ***@***.***> wrote: ﻿ 你好，请问最后怎么解决的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，我看看要怎么升级，感谢您的回复，谢谢。
