### ISSUE TITLE
🐛[BUG]官网-/list/table-list页面报错

### ISSUE THREAD

**Issue by luanweijie** [ant-design/ant-design-pro#7172]
### 🐛 bug 描述

访问 https://preview.pro.ant.design/list/table-list
页面不能正常打开
显示Something went wrong.
(0 , g.proFieldParsingText) is not a function

### 📷 复现步骤

访问https://preview.pro.ant.design/list/table-list

### 🏞 期望结果

正常显示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重新 build 了，protable 发布了一个错误的版本

**Comment by 419280377** [comment]
> 重新 build 了，protable 发布了一个错误的版本

Ant Design Pro 4.0.0的版本重新install一下也报了同样的错(Something went wrong)，将ProTable升至最新(2.54.3)仍然报错

详情见：https://github.com/ant-design/ant-design-pro/issues/9165
