### ISSUE TITLE
🧐[问题]下拉菜单设置数组值为菜单名称

### ISSUE THREAD

**Issue by alvinjzhang** [ant-design/ant-design-pro#7173]
### 🧐 问题描述

下拉菜单如何设置数组值为菜单名称？
![image](https://user-images.githubusercontent.com/53717827/89788646-11c2c600-db52-11ea-8a09-832bed917764.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/53717827/89788618-08d1f480-db52-11ea-943b-605d3964c369.png)

**Comment by chenshuai2144** [comment]
没有听懂诶，有代码示例吗

**Comment by alvinjzhang** [comment]
![image](https://user-images.githubusercontent.com/53717827/89863248-4da26d80-dbdc-11ea-9725-8deaa3959e42.png)
标红处的代码想要用数组的值来代替

**Comment by chenshuai2144** [comment]
没有这个 api 的吗， 你可以自己封装一下吗，社区倒是有不少方案
