### ISSUE TITLE
新建pro v4项目有javascript版本的吗?

### ISSUE THREAD

**Issue by qiantaobao** [ant-design/ant-design-pro#7177]
### 🧐 问题描述

用npm create umi创建新项目，选的是V4版本，选的语言是javascript，但是项目下载下来后，里面却使用的是ts，我想请问选择javascript和typescript的区别是什么?

**Comment by Fuphoenixes** [comment]
同样遇到了这个问题，项目2.x的今天准备升级发现用npm create umi创建新项目，选的语言是javascript无效，怎么下都是ts版的

**Comment by Fuphoenixes** [comment]
@sorrycc

**Comment by ziiyan** [comment]
选择 antd@3 就行了，不知道为什么
