### ISSUE TITLE
🧐[问题]打包後的umi.xxx.js 含有所有icon, 包括沒有用過的icon

### ISSUE THREAD

**Issue by realcyma** [ant-design/ant-design-pro#7178]
### 🧐 问题描述
build 完成後, 打包後的 umi.xxx.js file, 包含了所有icon. (我沒有用過的icon也在)

我用的 antd 已經是4.5.3 版本.

我在https://www.npmjs.com/package/umi-plugin-antd-icon-config  找到要修改. .umirc.js 文檔.  但我的project 中沒有這檔案. 

![image](https://user-images.githubusercontent.com/32567610/89890326-bc47f100-dc05-11ea-8972-77ea72256e16.png)

**Comment by chenshuai2144** [comment]
写标题

**Comment by realcyma** [comment]
從新下載一個新的 boilerplate 就沒有這問題. 我自己再研究我的project 有甚麼不一樣, 謝謝.
