### ISSUE TITLE
打包部署

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#718]
请问ant-desing-pro 打包之后如何部署到服务端

现在是做了index的映射,但报错index.js和index.css找不到

**Comment by chenshuai2144** [comment]
你是不是相对路径？

**Comment by TigerBill2016** [comment]
绝对路径  pro版本是0.3 我要怎样配置才能打包成相对路径

**Comment by Colinlyj210** [comment]
编译之后改成绝对路径，或者把css，js放到cdn上

**Comment by chenshuai2144** [comment]
参见#649
