### ISSUE TITLE
🧐[问题]Ant Design项目添加Umi区块报错

### ISSUE THREAD

**Issue by wittontech** [ant-design/ant-design-pro#7180]
### 🧐 问题描述

基于Umi脚手架新建了Ant design项目，通过Umi UI添加区块到项目页面中，操作步骤如下
1. 点击Umi UI气泡
1. 选择`Assets->Blocks`，选择一个区块进行添加
1. 使用默认或者修改`Varibale Name`，点击OK
1. `Varibale Name`报错，提示***This experimental syntax requires enabling the parser plugin: 'optionalChaining' (132:21)***
1. 试了几个区块，都是同样的问题

### 💻 示例代码

无

### 🚑 其他信息

<img width="1213" alt="Screen Shot 2020-08-12 at 10 10 17 AM" src="https://user-images.githubusercontent.com/66680831/89967490-28693a00-dc84-11ea-9fd6-9baa865cb426.png">

**Comment by lvvlan** [comment]
同遇到，有解决方案了吗？

**Comment by AndyWebJava** [comment]
同遇到，怎么解决？

**Comment by wittontech** [comment]
> 同遇到，有解决方案了吗？
> 同遇到，怎么解决？

目前还没有解决方案，二位有进展没？

**Comment by zrone** [comment]
试试 ```npm install babel-plugin-dynamic-import-webpack --save-dev```

**Comment by 980061076** [comment]
> 试试 `npm install babel-plugin-dynamic-import-webpack --save-dev`

没有用

**Comment by SWaiter** [comment]
解决了吗

**Comment by SWaiter** [comment]
> > 试试 `npm install babel-plugin-dynamic-import-webpack --save-dev`
> 
> 没有用

解决了吗  我遇到这个问题  上面的命令没有用

**Comment by 980061076** [comment]
> > > 试试 `npm install babel-plugin-dynamic-import-webpack --save-dev`
> > 
> > 
> > 没有用
> 
> 解决了吗 我遇到这个问题 上面的命令没有用

没有解决，不过在模块界面里的区块有一些可以使用比如 高级>高级表单 这个区块就可以正常添加

**Comment by kouhunzhe** [comment]
同样问题+1

**Comment by fleetscythe** [comment]
tyarn add @babel/plugin-proposal-optional-chaining     我用这个可以解决

**Comment by 980061076** [comment]
> tyarn add @babel/plugin-proposal-optional-chaining 我用这个可以解决

不得行,在当前页面内添加模块还是会报错

**Comment by chenshuai2144** [comment]
这个功能已经废弃并停止维护，如果需要建议自行frok维护。
