### ISSUE TITLE
🧐[问题]  这么多用 Ant pro ，React 版本的，就没有一个像样的站嘛1

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7186]
### 🧐 问题描述

Ant  Pro  Vue 版本有个一个实例展示站，做的非常的不错！而且他的模板都是写在数据库里的！ 可以随心所欲的修改，可视化布局！

https://github.com/zhangdaisc…
https://gitee.com/jeecg/jeecg…
演示地址：http://boot.jeecg.org
技术文档：http://jeecg-boot.mydoc.io
快速入门：http://jeecg-boot.mydoc.io/?t…

找了一大圈，没有找到一个像模像样的，React版本的！  

太遗憾了！

有的话贴出来，一起学习学习！

**Comment by pkaq** [comment]
这个大家主要都是拿来做企业级管理应用吧 , 你这个jeecg也是国内伪开源派的代表作品 这个公司本身就是做商业化开发的

**Comment by zhengchalei** [comment]
`ANT DESIGN PRO
开箱即用的中台前端/设计解决方案`
并非是一个后端的服务应用, 如果你需要可以直接用他的就好了, 说明 Ant Design Pro 不适合你

**Comment by chenshuai2144** [comment]
你要的这个要封装成服务的，我们这边只有两个人要负责antd + pro + plugins 一大摊事情，很难做到大而全。

你需要的可能是一个一站式的 sass 服务
