### ISSUE TITLE
不能创建simple (Simple version of Ant Design Pro with hash history)项目了？

### ISSUE THREAD

**Issue by wuwu8ku** [ant-design/ant-design-pro#719]
$pro new
? which type of scaffold do you want to new ? simple (Simple version of Ant Design Pro with hash history)
? input project name: app
? which directory do you want to init to ? (default is current directory ./): 
Failed to download repo https://github.com/ant-design/ant-design-pro#simple HTTPError: Response code 404 (Not Found)

**Comment by ddcat1115** [comment]
https://github.com/ant-design/ant-design-pro-cli/blob/master/README.md#100
