### ISSUE TITLE
🐛[BUG]顶部三级路由菜单选中问题

### ISSUE THREAD

**Issue by wsgyp-dashuaige** [ant-design/ant-design-pro#7191]
### 🐛 bug 描述

顶部三级路由菜单选中问题

### 📷 复现步骤

在config中设置routes多级菜单后（此处为三级），选中三级菜单中的一个项，同级菜单文字颜色同时发生变化

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/64769763/90111767-b0813980-dd81-11ea-9c1b-0b981108821f.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/92746264-b33d7180-f3b5-11ea-977f-9234666cb39c.png)


看起来你的菜单名字起的重复了吧
