### ISSUE TITLE
AntModal 或 AntDrawer 包裹 type 为 form 的 ProTable，弹窗时需要缩放浏览器窗口才能显示表单 🐛[BUG]

### ISSUE THREAD

**Issue by aweiu** [ant-design/ant-design-pro#7192]
### 🐛 bug 描述

如题...

### 📷 复现步骤

1. 直接访问官方预览：https://preview.pro.ant.design/list/table-list
2. 点击新建
3. 左右缩放浏览器窗口

### 🏞 期望结果

[AntModal](https://ant.design/components/modal-cn/) 或 [AntDrawer](https://ant.design/components/drawer-cn/) visible 的时候能展示出表单。（不确定是不是还有其他类似的容器也会有这个问题

### 💻 复现代码

[ListTableList](https://github.com/ant-design/ant-design-pro/blob/b265871ac0501840a390c20a6b14bf38887cdb9d/src/pages/ListTableList/index.tsx#L193)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by aweiu** [comment]
目前的解决办法是给 model 或 drawer 设置：`forceRender`

**Comment by chenshuai2144** [comment]
修复了，@ant-design/pro-table@2.5.10
