### ISSUE TITLE
🐛[BUG]IE 11时，页面占不满屏幕，左侧菜单点击时，有时内容只占半个屏幕。

### ISSUE THREAD

**Issue by gugu-lee** [ant-design/ant-design-pro#7195]
### 🐛 bug 描述

IE 11时，页面占不满屏幕，左侧菜单点击时，有时内容只占半个屏幕。
### © 版本信息

"@ant-design/icons": "^4.0.0",
"@ant-design/pro-layout": "^6.4.4",
 "@ant-design/pro-table": "2.3.4",

 "antd": "4.3.3",
浏览器 IE11

### 🚑 其他信息

![无标题](https://user-images.githubusercontent.com/6067910/90125296-60f83900-dd94-11ea-8836-dcab1ea34d7f.png)

**Comment by chenshuai2144** [comment]
强行设置一下 height:"100vh" 吧。ie11 的 flex 有点问题，要支持的话就要 hack 一点
