### ISSUE TITLE
🐛[BUG] PRO V5 setInitialState手动设置数据没有效果

### ISSUE THREAD

**Issue by FlintZheng** [ant-design/ant-design-pro#7196]
##### 1、使用PRO V5的全局数据手动设置数据失效，如下设置
`const { initialState, loading, refresh, setInitialState } = useModel('@@initialState');  
 setInitialState({KK:111})`
##### 2、设置后在其它组件中获取initialState，无法得到KK这个设置的值，这个setInitialState没用啊
   ` 在其它组件里使用useModel('@@initialState');  ` 无法获取到新增的值

**Comment by FlintZheng** [comment]
加了标题了

**Comment by afc163** [comment]
写标题

<img width="541" alt="image" src="https://user-images.githubusercontent.com/507615/90246403-26130580-de67-11ea-9c0c-5d26531489e1.png">

[如何向开源社区提问题](https://github.com/seajs/seajs/issues/545)

**Comment by FlintZheng** [comment]
这次加上了

**Comment by chenshuai2144** [comment]
@FlintZheng  试了一下可以，有详细的复现吗？

**Comment by jzsn2018** [comment]
I have meet same issue now
