### ISSUE TITLE
🐛[BUG]从commit[5d3bb00]之后, V5部署在nginx非根目录部署，登录成功后会跳转到根目录。

### ISSUE THREAD

**Issue by waylon-edmodo** [ant-design/ant-design-pro#7197]
### 🐛 bug 描述

Commit:
5d3bb00e33852e841542bd38b118ef322f353979 [5d3bb00]
Parents:
df80e961c3, 7e40523d79
Author:
kaoding <41830859@qq.com>
Date:
July 20, 2020 at 10:22:15 PM GMT+8
Committer:
GitHub <noreply@github.com>

会导致登录后跳转的页面是根目录。如果应用不是部署在根目录，会有问题。
  // window.location.href = urlParams.href.split(urlParams.pathname)[0] + (redirect || '/'); 【有问题】

### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本
- 浏览器环境 Chrome
- 开发环境 MAC

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/51694657/90142437-f30d3b00-ddae-11ea-8dd1-25fc099bac52.png)

**Comment by waylon-edmodo** [comment]
dev模式下是因为 根路径/ 会跳转到 二级/path下，所以没问题

**Comment by chenshuai2144** [comment]
有兴趣来个 pr 吗？

**Comment by waylon-edmodo** [comment]
嗯。一直在用。跟了很多版本了。
我改了一下replaceGoto方法的处理，在browser模式下，部署在根目录与非根目录都可以。
但是我发现在history.type.hash模式下，当登录的时候调用完/api/login/account接口后会马上跳转到welcome页面，但是马上会触发这个commit中的onPageChange方法，在取/api/currentUser之前，页面就被重定向到登录页面，导致一直进不去。

// Commit:
// e7471b6a890d9cbc75b859c538ee1348e7c2054d [e7471b6]




`
import { Link, SelectLang, useModel, history } from 'umi';
/**
 * 此方法会跳转到 redirect 参数所在的位置
 */
const replaceGoto = () => {
  const urlParams = new URL(window.location.href);
  const params = getPageQuery();
  let { redirect } = params as { redirect: string };
  let path = urlParams.href.split(history.location.pathname)[0];
  if (redirect) {
    const redirectUrlParams = new URL(redirect);
    if (redirectUrlParams.origin === urlParams.origin) {
      redirect = redirect.substr(urlParams.origin.length);
      if (redirect.match(/^\/.*#/)) {
        redirect = redirect.substr(redirect.indexOf('#'));
      }
      path = urlParams.href.split(urlParams.pathname)[0] + (redirect || '/');
    }
  }
  window.location.href = path;
};`

**Comment by waylon-edmodo** [comment]
原来的代码在hash模式下也有问题，点击登录，退出登录，再点登录，页面无法进入。需要再点登录才行。

**Comment by zhangshuling** [comment]
https://github.com/ant-design/ant-design-pro/issues/7087

我提的好像也是这个问题

**Comment by king-lxt** [comment]
@waylon-edmodo 老哥  请教你点问题，V5版本  我点击菜单，可以调到对应的页面，但是菜单没有选中的状态，有遇到过吗？

**Comment by chenshuai2144** [comment]
@waylon-edmodo  是不是配置了base？

**Comment by waylon-gmail** [comment]
@chenshuai2144 是的
