### ISSUE TITLE
🐛 蚂蚁设计，咱们再也不能耍流氓啦！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7198]
### 🐛 bug 描述

V5 预览版都出来这么久了！

正式版不推出来就算了吧！

怎么也得弄一个文档出来吧！

没有文档，不是耍流氓嘛！让我们新手怎么入门！

怎么学？

真是应征了那句话   **热锅上的蚂蚁，急得团团转**

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/

看起来你没认真读我们的预览公告
