### ISSUE TITLE
🐛[BUG]国际化的问题

### ISSUE THREAD

**Issue by phpmaple** [ant-design/ant-design-pro#7199]
### 🐛 bug 描述

删除locales下面某一种语言的文件和文件夹, .umi 还会在生成默认的那几种语言
### 📷 复现步骤
比如删除pt-br这个语言所有文件和文件夹

删除之后再用 umi template 生成 dashboard 之后 语言切换会多出来之前的 pt-br
### 🏞 期望结果
删除语言之后语言切换类型应该保持不变 不应添加 umi template 之后又多出来之前的语言

### 💻 复现代码
确定就是添加 umi template 的 dashboard 的问题

### © 版本信息

- Ant Design Pro 版本: 5.0.0-alpha.0
- umi 版本 3
- 浏览器环境 chrome
- 开发环境  mac OS

**Comment by chenshuai2144** [comment]
umi template 加了这个语言了
