### ISSUE TITLE
关于ant design pro chart 组件宽度不会自适应问题

### ISSUE THREAD

**Issue by MonsterKim** [ant-design/ant-design-pro#720]
你好！我安装的是ant design。然后再安装了ant design pro 里面的charts组件（单独引用）。目前数据是没问题，可是发现chart的右侧少了一截，无论是任何种类的chart都会少一截。我看了一下，具体宽度计算是从windows窗口开始计算的。左侧我有个200px宽度的侧边栏。而2个chart刚好每一个都少了100px。

但是当我缩小或放大窗口、以及切换导航时，chart的宽度又恢复正常。顿时懵逼。。。

请问针对此问题有无好的解决办法。

附上截图。

![1](https://user-images.githubusercontent.com/12606338/34983097-5ccd12b6-fae7-11e7-9ed5-c11feefb6697.png)
![2](https://user-images.githubusercontent.com/12606338/34983099-5d2b2626-fae7-11e7-957d-58d7294aca65.png)

**Comment by nikogu** [comment]
@MonsterKim 这个问题只会在开发环境重现，问题还是因为 js 在 css 之前执行，所以宽度计算有误差。roadhog 应该在搞了。

**Comment by MonsterKim** [comment]
@nikogu 谢谢你。

**Comment by kennylbj** [comment]
我用create-react-app的时候也遇到这个问题，暂时的解决办法是在展示chart页面componentDidMount的时候进行resize。
```js
componentDidMount() {
    const event = document.createEvent('HTMLEvents');
    event.initEvent('resize', true, false);
    window.dispatchEvent(event);
}
```
