### ISSUE TITLE
🐛[BUG] don't create ant-design-pro v4 with javascript

### ISSUE THREAD

**Issue by taivo-vietcetera** [ant-design/ant-design-pro#7202]
### 🐛 bug 描述
I can't create ant-design-pro with javascript; log error image

![image](https://user-images.githubusercontent.com/66932418/90240865-3968a580-de54-11ea-8f40-5da5f1d3d5f0.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed in https://github.com/umijs/sylvanas/pull/10
