### ISSUE TITLE
🐛[BUG]V4 、V5菜单收起后重新展开，没有目录的项中图标与文字之间有动画，但是有目录的没有动画

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#7205]
### 🐛 bug 描述

V4 、V5菜单收起后重新展开，没有目录的项中图标与文字之间有动画，但是有目录的没有动画

都是使用的最新没有更改过的代码。

### 🏞 期望结果

要么都没有动画，要么都加上动画

### © 版本信息

- Ant Design Pro 版本: V4、V5
- umi 版本
- 浏览器环境
- 开发环境 [e.g. Chrome]

### 🚑 其他信息

展开瞬间的事情

![image](https://user-images.githubusercontent.com/12421552/90304278-b7768c00-dee8-11ea-8890-3551295c1498.png)

**Comment by chenshuai2144** [comment]
最新的版本fixed 了，竟然没发现找到这个issue
