### ISSUE TITLE
🐛[BUG] 布局 query 在切换时没有保存

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#7209]
1. 打开 https://preview.pro.ant.design/
2. 打开右侧抽屉菜单，设置导航模式为顶部菜单模式，此时 url 上多了 `?layout=top&contentWidth=Fixed&splitMenus=false`。
3. 顶部菜单点击一个新页面进行切换
4. 此时 url 上的 query 都没了，但是布局依然是 `顶部菜单模式`。

这样刷新页面后，会回到左右布局。

**Comment by chenshuai2144** [comment]
umi 暂时不支持这个功能
@sorrycc   看看
