### ISSUE TITLE
👑 [需求]ProTable的右上角的工具栏，添加自定义按钮？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#7211]
### 🥰 需求描述

我想在 ProTable的右上角的工具栏，添加一个 下载按钮。如下图：
![image](https://user-images.githubusercontent.com/5111701/90348833-f08a3a00-e069-11ea-9c55-7d70e1781d58.png)

应该怎么写？
![image](https://user-images.githubusercontent.com/5111701/90348867-144d8000-e06a-11ea-9a4d-f4f53d1641a1.png)

**Comment by xunbie** [comment]
`toolBarRender={(action, { selectedRows }) => [
          <Button type="primary" onClick={() => handleModalVisible(true)}>
            <PlusOutlined /> 新建
          </Button>,
          <Button type="primary" onClick={() => handleModalVisible(true)}>
            <PlusOutlined /> 新建
          </Button>,
          selectedRows && selectedRows.length > 0 && (
            <Dropdown
              overlay={
                <Menu
                  onClick={async (e) => {
                    if (e.key === 'remove') {
                      await handleRemove(selectedRows);
                      action.reload();
                    }
                  }}
                  selectedKeys={[]}
                >
                  <Menu.Item key="remove">批量删除</Menu.Item>
                  <Menu.Item key="approval">批量审批</Menu.Item>
                </Menu>
              }
            >
              <Button>
                批量操作 <DownOutlined />
              </Button>
            </Dropdown>
          ),
        ]}`

**Comment by pxim** [comment]
> `toolBarRender={(action, { selectedRows }) => [ <Button type="primary" onClick={() => handleModalVisible(true)}> <PlusOutlined /> 新建 </Button>, <Button type="primary" onClick={() => handleModalVisible(true)}> <PlusOutlined /> 新建 </Button>, selectedRows && selectedRows.length > 0 && ( <Dropdown overlay={ <Menu onClick={async (e) => { if (e.key === 'remove') { await handleRemove(selectedRows); action.reload(); } }} selectedKeys={[]} > <Menu.Item key="remove">批量删除</Menu.Item> <Menu.Item key="approval">批量审批</Menu.Item> </Menu> } > <Button> 批量操作 <DownOutlined /> </Button> </Dropdown> ), ]}`

谢谢
