### ISSUE TITLE
🧐[问题] antd-pro5 接口返回的语言包，没有写死在前端项目， 这种情况怎么做国际化

### ISSUE THREAD

**Issue by taomengyue** [ant-design/ant-design-pro#7216]

**Comment by chenshuai2144** [comment]
动态设置 setLocale？

https://pro.ant.design/docs/i18n-cn#%E8%AE%BE%E7%BD%AE%E5%8C%BA%E5%9F%9F

**Comment by Uil-Nehz** [comment]
addLocale

**Comment by taomengyue** [comment]
你好，addLocale的话在app.tsx中写？不知道怎么写这个请求的？

**Comment by taomengyue** [comment]
> addLocale

你好，addLocale的话在app.tsx中写？不知道怎么写这个请求的？

**Comment by taomengyue** [comment]
> 动态设置 setLocale？
> 
> https://pro.ant.design/docs/i18n-cn#%E8%AE%BE%E7%BD%AE%E5%8C%BA%E5%9F%9F

你好，addLocale的话写在app.tsx中？antdpro5的话写在最外层才有用，但是数据是异步的，怎么弄

**Comment by taomengyue** [comment]
> 动态设置 setLocale？
> 
> https://pro.ant.design/docs/i18n-cn#%E8%AE%BE%E7%BD%AE%E5%8C%BA%E5%9F%9F

你好，addLocale的话写在app.tsx中？antdpro5的话写在最外层才有用，但是数据是异步的，怎么弄

**Comment by taomengyue** [comment]
> 动态设置 setLocale？
> 
> https://pro.ant.design/docs/i18n-cn#%E8%AE%BE%E7%BD%AE%E5%8C%BA%E5%9F%9F

你好，addLocale的话写在app.tsx中？antdpro5的话写在最外层才有用，但是数据是异步的，怎么弄

**Comment by chenshuai2144** [comment]
`import { addLocale } from 'umi'`
是可以写在任何地方的
