### ISSUE TITLE
🧐[问题] 已经修改了BasicLayout下的DefaultFooter 但登录页的没变 还要修改哪里吗

### ISSUE THREAD

**Issue by wj0101** [ant-design/ant-design-pro#7217]
### 🧐 问题描述

用的v4
已经修改了BasicLayout下的DefaultFooter 但登录页的没变

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/e49a1953e6e6931d2d6c0382ecb5b07c1528561a/src/layouts/UserLayout.tsx

这里

**Comment by wj0101** [comment]
> https://github.com/ant-design/ant-design-pro/blob/e49a1953e6e6931d2d6c0382ecb5b07c1528561a/src/layouts/UserLayout.tsx
> 
> 这里

我说的是footer
![image](https://user-images.githubusercontent.com/13463968/90463837-7d062c80-e13e-11ea-82f2-3299c9cdd364.png)

**Comment by xshans** [comment]
这里已经打包进package了，可以自己写。
