### ISSUE TITLE
🧐[问题] 关的太快了只能重发一次 不是UserLayout中登录文案  是页面底部的版权声明 

### ISSUE THREAD

**Issue by wj0101** [ant-design/ant-design-pro#7218]
### 🧐 问题描述

已经修改了BasicLayout的DefaultFooter ，但登录页还是默认的，用的v4

![image](https://user-images.githubusercontent.com/13463968/90463837-7d062c80-e13e-11ea-82f2-3299c9cdd364.png)

**Comment by xiaohuoni** [comment]
登录页 用的是自己的layout。注意修改
