### ISSUE TITLE
related route doesnt get rendered

### ISSUE THREAD

**Issue by andriijas** [ant-design/ant-design-pro#722]
1) add similar route in `common/router.js`
```
    '/user/login': {
      component: dynamicWrapper(app, ['login'], () => import('../routes/User/Login')),
    },
    '/user/login/:token': {
      component: dynamicWrapper(app, ['login'], () => import('../routes/User/AutoLogin')),
    },
```

2) doesnt work because of bug in `getRelation`  in `utils.js`   - can we fix this?

3) `getPlainNode`  in `utils.js`  is not used, you can remove it

thanks!

**Comment by ddcat1115** [comment]
`/user/login/:token` will not render at the same level of `/user/login` by default, you can refer to [doc](https://pro.ant.design/docs/router-and-nav-cn#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA) to get the solution

**Comment by ddcat1115** [comment]
What does `exact` mean to do in this sinario?

**Comment by andriijas** [comment]
/user/login   should have exact = true so that   /user/login/:token  also works, or? 

it could be same issue when logging in,  /users   vs /users/:userId
