### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by zhaosanyuan-520** [ant-design/ant-design-pro#7220]
### 🧐 问题描述 页面的title的问题

我现在用的是antd pro v5 这个版本  这个页面的title会跟着路由的变化而发生改变但是我不需要这段文字，请问如何删除

![image](https://user-images.githubusercontent.com/68691066/90480121-6245af00-e162-11ea-86e1-23cd5ee53faa.png)

**Comment by chenshuai2144** [comment]
在 app.ts 的 layout 中配置 `pageTitleRender:false`
