### ISSUE TITLE
请教umi-plugin-antd-theme配置无效

### ISSUE THREAD

**Issue by wxf-start** [ant-design/ant-design-pro#7221]
### 🧐 问题描述
我按照官方文档进行主题配置，但是无效，界面
![image](https://user-images.githubusercontent.com/37679380/90490327-164e3680-e171-11ea-9d82-5f30b136a87c.png)

### 💻 示例代码
1.安装 umi-plugin-antd-theme
![image](https://user-images.githubusercontent.com/37679380/90490635-6a591b00-e171-11ea-8e45-2d29dd9fd9e8.png)

2.创建theme.config.json
![image](https://user-images.githubusercontent.com/37679380/90490693-82309f00-e171-11ea-9527-10e5d8a87d1a.png)

3.重启项目
![image](https://user-images.githubusercontent.com/37679380/90490748-91afe800-e171-11ea-8304-32739c6716b1.png)

### 🚑 其他信息

页面显示为什么没有那个选择颜色的出来啊，我哪里理解错了吗
![image](https://user-images.githubusercontent.com/37679380/90490800-a68c7b80-e171-11ea-9b6c-79fae894cb70.png)

版本信息：
umi3
ant-desgin-pro v4

**Comment by wxf-start** [comment]
![image](https://user-images.githubusercontent.com/37679380/90584751-e4d37a80-e205-11ea-8340-58372519c774.png)
![image](https://user-images.githubusercontent.com/37679380/90584764-ea30c500-e205-11ea-91a9-9e03dcfbbada.png)

simple下自己添加进去的方法，文档写的。。有点误导人哦

**Comment by afc163** [comment]
@wxf-start 帮忙更新一下文档吧？

**Comment by wxf-start** [comment]
@afc163 可以啊，哈哈哈，你不是开玩笑就好

**Comment by wxf-start** [comment]
@afc163 提醒一下,v4的layouts/BasicLayout，可以把内部发地址都换成新的了！
![image](https://user-images.githubusercontent.com/37679380/90705694-20357e00-e2c6-11ea-817b-da2877296cd8.png)

换成这个
![image](https://user-images.githubusercontent.com/37679380/90705744-380d0200-e2c6-11ea-931a-f9bcc8da9ac6.png)

**Comment by afc163** [comment]
直接来 PR 吧 @wxf-start

**Comment by wxf-start** [comment]
> @wxf-start 你的SettingDrawer配置是什么呀 这文档确实有毒 我也研究了半天

建议你去看看ant-desgin-pro 的 BaseLayout ，然后查找SettingDrawer, 直接引入即可，就可以看到，不过这个不建议在正式环境使用呢

**Comment by OriginZero** [comment]
@wxf-start 我SettingDrawer主题色只有一个，你的怎么样呢？

**Comment by wxf-start** [comment]
> @wxf-start 我SettingDrawer主题色只有一个，你的怎么样呢？

你需要安装npm i umi-plugin-antd-theme --save-dev ，重启就有多种主题了
