### ISSUE TITLE
为什么我安装模板的时候总是出现这种问题？哪位大神可以帮我看看吗？

### ISSUE THREAD

**Issue by genghaibin** [ant-design/ant-design-pro#7222]
安装模块的时候总是装不成功，提示信息如下。反复搞了好2天了，还是解决不了，跪求大神帮我看看。
`⚓  Start git fetch
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
Faild git checkout: Command failed: git checkout master
undefined
undefined

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
Faild git checkout: Command failed: git checkout master
undefined
undefined

🚧  Execute task error: Error: Command failed: git checkout master
undefined
undefined
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
error: pathspec 'master' did not match any file(s) known to git
Faild git checkout: Command failed: git checkout master
undefined
undefined

🚧  Execute task error: Error: Command failed: git checkout master
undefined
undefined`

**Comment by genghaibin** [comment]
> 安装模块的时候总是装不成功，提示信息如下。反复搞了好2天了，还是解决不了，跪求大神帮我看看。
> `⚓ Start git fetch
> ⚓ Start git fetch
> 🎉 Success git fetch
> 
> ⚓ Start git fetch
> 🎉 Success git fetch
> 
> ⚓ Start git checkout master
> ⚓ Start git fetch
> 🎉 Success git fetch
> 
> ⚓ Start git checkout master
> error: pathspec 'master' did not match any file(s) known to git
> ⚓ Start git fetch
> 🎉 Success git fetch
> 
> ⚓ Start git checkout master
> error: pathspec 'master' did not match any file(s) known to git
> Faild git checkout: Command failed: git checkout master
> undefined
> undefined
> 
> ⚓ Start git fetch
> 🎉 Success git fetch
> 
> ⚓ Start git checkout master
> error: pathspec 'master' did not match any file(s) known to git
> Faild git checkout: Command failed: git checkout master
> undefined
> undefined
> 
> 🚧 Execute task error: Error: Command failed: git checkout master
> undefined
> undefined
> ⚓ Start git fetch
> 🎉 Success git fetch
> 
> ⚓ Start git checkout master
> error: pathspec 'master' did not match any file(s) known to git
> Faild git checkout: Command failed: git checkout master
> undefined
> undefined
> 
> 🚧 Execute task error: Error: Command failed: git checkout master
> undefined
> undefined`

 对了，我用的是ant design pro V4

**Comment by chenshuai2144** [comment]
执行一下右上角的 clear

![image](https://user-images.githubusercontent.com/8186664/91258590-4b750d00-e79f-11ea-840f-0050562e25c9.png)
