### ISSUE TITLE
ant-design-pro 4.x  安装脚手架 Simple 选择 javascript时 最后生成的是 TypeScript🐛[BUG]

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/ant-design-pro#7223]
### 🐛 bug 描述

ant-design-pro 4.x  安装脚手架 Simple 选择 javascript时 最后生成的是 TypeScript🐛[BUG]

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by justdoitweb** [comment]
遇到了相同的情况，我还以为我操作方式不对呢
