### ISSUE TITLE
🐛[BUG] Page not found when reloading Netlify

### ISSUE THREAD

**Issue by Antoine-lb** [ant-design/ant-design-pro#7227]
### 🐛 bug 描述 / bug description
Hello 👋
Everytime I refresh the page and there is something after the domain name `name.com/something`, Netlify returns a `Page Not Found`. 
I have to go to `name.com`, for then to navigate to `name.com/something`, and it works. But if I refresh when I'm in `name.com/something` I get a `Page Not Found`.

This only happens when I deploy to Netlify, in local this does not happen.

### 📷 复现步骤 / Steps to reproduce
1) Clone repo
2) Hack a little bit to make the login system work (the problem could very well come from this)
3) Push to Netlify (the code is built by Netlify, so I push all the sourse code and then it gets built on the cloud)
4) Go to `name.com`, it works and I log in
5) It redirects me to `name.com/list`, and everything works
6) I refresh the page (`name.com/list`) and get a `Page Not Found` by Netlify (is not a Ant Design Pro 404 page)

### 🏞 期望结果 / Expected results
I can refresh in `name.com/something` and not get a page not found.

### © 版本信息 / Version Information
- antd: "^4.4.0",
- umi: "^3.2.0",
- umi-request: "^1.0.8",
- MacOS Catalina (10.15.5)
- Happens in all browsers

### 🚑 其他信息 / other information
I did hack a bit to make the login work with my back-end. I'm fetching a JWT that I store in local storage, and it gets added in `queryCurrent();`.

Is there something wrong that could break the routing:

In `app.tsx`
```
...
  if (history.location.pathname !== '/user/login') {
    try {
      const currentUser = await queryCurrent();

      return {
        currentUser: {
          avatar: 'string',
          name: currentUser.name,
          title: 'string',
          group: 'string',
          signature: 'string',
          tags: [
            {
              key: 'string',
              label: 'string',
            },
          ],
          userid: 'string',
          access: 'admin',
          unreadCount: 0,
        },
        settings: defaultSettings,
      };
    } catch (error) {
      console.error('error fetching current user', error);
      history.push('/user/login');
    }
  }
  return {
    settings: defaultSettings,
  };
}
...
```

Do somebody has an idea on where to look for answers?
Thanks for the help!

**Comment by chenshuai2144** [comment]
you need some config for Netlify

https://sung.codes/blog/2018/12/18/page-not-found-on-netlify-with-react-router/

**Comment by Antoine-lb** [comment]
Just as a note: the `_redirects` file has to be inside of the `public` folder
