### ISSUE TITLE
🧐[问题]如何引入项目外的jsx文件

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design-pro#7228]
### 🧐 问题描述

如何引入项目外的jsx文件?
我们公司现在要做一个公共页面的模块,多个项目共用公共页面

目录结构是这样的
+project1
+project2
+commonProject
所以我的项目中,需要使用项目外的jsx文件

### 💻 示例代码

routes.js

            {
              path: '/welcome',
              name: 'welcome',
              icon: 'smile',
              component: '../../../Welcome',
            },

这样的component已经配置到项目外面去了

### 🚑 其他信息

报错如下

![image](https://user-images.githubusercontent.com/3994941/90643170-d917a080-e265-11ea-9092-d2de8b710d23.png)

Module parse failed: Unexpected token (5:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by miaozilong** [comment]
求各位路过的大佬帮帮忙,不要只回答一句配一下webpack之类的

**Comment by miaozilong** [comment]
在线等.有人在吗?

**Comment by HengCC** [comment]
那你应该考虑把common的放到npm仓库去. 每次common有更新的时候要推仓库.  其他项目配package.json依赖这个包.

**Comment by miaozilong** [comment]
> 那你应该考虑把common的放到npm仓库去. 每次common有更新的时候要推仓库. 其他项目配package.json依赖这个包.

目前用的就是这用方式,很麻烦
1. common包更新了 项目包不自动更新
2. 要专门搞个npm私服

**Comment by chenshuai2144** [comment]
用多 repo 的方式，现在很成熟了。
