### ISSUE TITLE
🐛[BUG] Layout v5 文档 BUG

### ISSUE THREAD

**Issue by zhengchalei** [ant-design/ant-design-pro#7229]
### 🐛 bug 描述

https://beta-pro.ant.design/docs/dynamic-theme-cn#antd-%E4%B8%BB%E9%A2%98%E5%88%87%E6%8D%A2
![](https://files.catbox.moe/1kn2ry.png)

打开混乱, 看URL 有几个404, 是不是文件缺失

**Comment by FinchJohnRen** [comment]
还有国际化移除， 拜托写全一点， 按照文档 弄完一堆错， 解决问题浪费很久时间

**Comment by chenshuai2144** [comment]
有些文档被删掉了，这个 404 页面有点奇怪，有空修一下

**Comment by chenshuai2144** [comment]
> 还有国际化移除， 拜托写全一点， 按照文档 弄完一堆错， 解决问题浪费很久时间

移除就是会有一堆错误需要解决的，工具不成熟。有需求最好是用 simple 项目启动
