### ISSUE TITLE
post提交发现提交了两次

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#723]
![image](https://user-images.githubusercontent.com/183884/34994617-1675455e-fb0f-11e7-99d3-735dc518186e.png)

有谁知道会是什么情况，排查半天了。而且type 怎么一个是fetch  一个是json,Request Method一个是:OPTIONS 一个是post 怎么会多出一个OPTIONS

**Comment by chenshuai2144** [comment]
你估计是跨域了吧 跨域会发起在put 一次post

**Comment by WuJiY** [comment]
是跨域了。那应该是这个问题了吧。

**Comment by chenshuai2144** [comment]
最好用代理。改头部就会造成这个问题

**Comment by WuJiY** [comment]
按照文档上这样设置
// .roadhogrc.mock.js
export default {
  'GET /api/(.*)': 'https://your.server.com/api/',
};
经常404，会是什么原因啊？

**Comment by chenshuai2144** [comment]
你从服务器看一下.是不是url拼接错了

**Comment by WuJiY** [comment]
没错啊，有时候请求成功。但有几个接口请求404，而且只要返回错误的结果好像都变成404错误。难道是我的代理设置有问题》？
![image](https://user-images.githubusercontent.com/183884/35021834-bb7b1d90-fb6d-11e7-8422-2d73fcd30c88.png)

**Comment by WuJiY** [comment]
pro对返回结果格式有要求？

**Comment by WuJiY** [comment]
问题找到了：
![image](https://user-images.githubusercontent.com/183884/35023958-0f7612a6-fb78-11e7-969f-13f0b2741bf6.png)  这个GET 时候POST的没用，POST的时候GET 没效果。有没有什么办法同时兼容？
