### ISSUE TITLE
🧐[问题] antd proV5中是否提供js版本？V4的js版本如何优雅升级至V5版本？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#7231]
### 🧐 问题描述
正在使用 antd pro V4版本，想请问下，V4的js版本如何优雅升级至V5版本？目前V5版本只有ts版是否会有js版？

### 💻 示例代码
无

### 🚑 其他信息
无

**Comment by zhilianbi520** [comment]
up，有哪位小伙伴可以解答下。

**Comment by zhilianbi520** [comment]
求解答。

**Comment by chenshuai2144** [comment]
V5版本 与 v4 的差别的不大的，你可以渐进式的进行开发。功能都是可以混用的，我的老项目就是这样

**Comment by zhilianbi520** [comment]
> V5版本 与 v4 的差别的不大的，你可以渐进式的进行开发。功能都是可以混用的，我的老项目就是这样
好的，了解。多谢～！
