### ISSUE TITLE
👑 [需求] 关于V5动态权限的思考

### ISSUE THREAD

**Issue by HengCC** [ant-design/ant-design-pro#7232]
### 🥰 需求描述

现有的权限控制是通过access.ts中定义若干条权限来控制的.  这在事实上的行为是由前端和后端根据约定来指明某个菜单或者按钮具有一定的权限.  是一种声明式的权限.   比如 我定义组件如下:
```
{
name:"xxx",
path:"/abc",
access:"canAccess"
}
```
之后在canAccess中. 我若做判定权限 事实上只能像下面这样或者类似这样的做法; 这种做法就限定了我必须知道这个角色事先存在. 
```
canAccess: return user.hasRole('rolexxx')
```

### 🧐 解决方案

有没有这样一种可能.  我事先从服务器获取 这样的数据结构 
```
[
{
菜单A:[role1,role2,xxxx....]
}
]
```
然后canAccess中需要将当前菜单的data也作为参数传递进来.  这样我有2个参数,类似这样

```
canAccess(currentMenuData,currentUser)
```
判定权限的时候只需要根据path获取这个path有哪些role可以访问. 然后判定当前的用户是否有这些role. 这样菜单就能避免在前端去定义权限. 而把权限抽象给后端去定义

### 🚑 其他信息

无

**Comment by zhangshuling** [comment]
之前看到有人说可以参考 V4 的配置，但是V5 好像删掉了 V4 配置动态权限的地方，不知道怎么下叉子啊，兄台找到解决办法没？赐教一下

**Comment by li515422618** [comment]
当前菜单route可以作为参数传递的，我是这样写的，在每个菜单组件上定义access: normalRouteFilter，之后判断当前访问path是否在后端返回的菜单集合中存在，若存在返回true，不存在返回false
![image](https://user-images.githubusercontent.com/17846480/91822323-30f0d700-ec6a-11ea-9cfd-b91d5f9a6f17.png)

**Comment by wangxingkang** [comment]
可以考虑下 @alitajs/umi-plugin-authority  https://react-admin-site.vercel.app/guide/advanced/authority
