### ISSUE TITLE
版本ant-design-pro新建的项目没有侧边栏的伸缩功能?怎么添加这个功能?🧐[问题]

### ISSUE THREAD

**Issue by Amy-Tan** [ant-design/ant-design-pro#7233]

**Comment by Amy-Tan** [comment]
![image](https://user-images.githubusercontent.com/49202591/90753291-feaab580-e30a-11ea-8412-2add3b1bce56.png)
这个怎么显示

**Comment by chenshuai2144** [comment]
在左下角，换了位置了

![image](https://user-images.githubusercontent.com/8186664/91258983-2b921900-e7a0-11ea-9115-fd769b791464.png)
