### ISSUE TITLE
Pro Table和Modal一起用的时候有冲突🐛[BUG]

### ISSUE THREAD

**Issue by DreamParadise** [ant-design/ant-design-pro#7234]
### 🐛 bug 描述

见下面的GIF

### © 版本信息

- Ant Design Pro Table 版本: 2.5.15
- Ant Design 版本: 4.5.2
- 浏览器环境: Chromium 80.0.3987.163
- 开发环境: Windows 10

### 🚑 其他信息

![iii](https://user-images.githubusercontent.com/3191003/90757949-d8881400-e310-11ea-8e4a-3c3de1cf7655.gif)

**Comment by DreamParadise** [comment]
GIF是直接上传到Github的，要翻墙才能看到……

**Comment by chenshuai2144** [comment]
按照 warning 的提示处理一下就好了
