### ISSUE TITLE
🧐如何给API/request 提供 token

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/ant-design-pro#7239]
### 🧐 问题描述

如何给API/request 提供 token？
Login后， token如何保存？ Localstorage?

**Comment by aoyinke** [comment]
request.interceptors.request.use(async (url, options) => {
  if (
    options.method === 'post' ||
    options.method === 'put' ||
    options.method === 'delete' ||
    options.method === 'get'
  ) {
    const headers = {
      token:localStorage.getItem("token")
    };
    return {
      url,
      options: { ...options, headers },
    };
  }
});
export default request;
加一个拦截器，如果只是在extend里面加的话会导致初次登陆的时候拿不到token
