### ISSUE TITLE
ProTable 绑定formRef后current是undefined，加了setTimeout异步处理后可以取到current

### ISSUE THREAD

**Issue by aoyinke** [ant-design/ant-design-pro#7240]
### 🧐 问题描述
在做修改功能的时候，我把ProTable当form使用，但是无奈dataSource和defaultValue都填充不了数据，就给ProTable加了一个formRef属性，但是在使用的时候拿不到current的，但是在用setTimeout包裹了操作之后，就拿得到了，感觉有点疑问，想请教一下。

### 💻 示例代码
const detailFormRef = useRef()
 <ProTable
          onSubmit={(value) => {
            changeDictDetaiFunc(value);
          }}
          type="form"
          formRef={detailFormRef}
          columns={createDictDetailColumns}
        />

// 使用 
<Space size="middle">
      <Button
        type="primary"
        onClick={() => {
          dispatch({
            type: 'GlobalModel/changeModifyDetailModalVisible',
            payload: true,
          });  // 弹出修改Model，此时会导致页面小刷新
          currentModifyDetail = record; //将这一行的数据赋值给一个全局变量
           detailFormRef.current.setFieldsValue(record); // 将这一行的数据填充进去 current undefined
        }}
      >
        修改
      </Button>
    </Space>

// 解决方法
<Space size="middle">
      <Button
        type="primary"
        onClick={() => {
          dispatch({
            type: 'GlobalModel/changeModifyDetailModalVisible',
            payload: true,
          });  // 弹出修改Model，此时会导致页面小刷新
          currentModifyDetail = record; //将这一行的数据赋值给一个全局变量
         setTimeout(() => {
            detailFormRef.current.setFieldsValue(record);  // 将这一行的数据填充进去 current undefined
          });
          
        }}
      >
        修改
      </Button>
    </Space>

**Comment by liujiayii** [comment]
也许跟modal里面的是懒加载的有关

**Comment by chenshuai2144** [comment]
ref 拿到的是上次 render 的值，所有 ref 不是实时的。

其实 setTimeOut 不是不能接受的解决方案

**Comment by aoyinke** [comment]
> ref 拿到的是上次 render 的值，所有 ref 不是实时的。
> 
> 其实 setTimeOut 不是不能接受的解决方案

明白了，谢谢！
