### ISSUE TITLE
V5版本  config.ts  增加公共路由， 点击二级路由，页面可以打开，但是对应的菜单没有高亮

### ISSUE THREAD

**Issue by king-lxt** [ant-design/ant-design-pro#7241]
![image](https://user-images.githubusercontent.com/23032062/90865457-f3b45b80-e3c4-11ea-8bc6-471f9e910ab0.png)

增加了公共路由，点击对应的二级菜单，可以跳转到对应的页面，但是菜单没有高亮

**Comment by chenshuai2144** [comment]
全一点，感觉看不懂

**Comment by king-lxt** [comment]
你好  我在config.ts下  配置了base路径，点击左侧菜单按钮，页面可以正常跳转，但是点击的菜单没有选中状态。（本地开发正常），发到测试环境就有问题

**Comment by chenshuai2144** [comment]
没测试过 base，有兴趣搞个复现的 repo吗

**Comment by king-lxt** [comment]
有点  有具体的联系方式吗  或者给我个邮件，可以具体沟通下

**Comment by king-lxt** [comment]
@chenshuai2144  问题已解决了，  测试出来的结果是路由只匹配了path, 没有匹配 base + path。所以没有匹配到菜单

**Comment by chenshuai2144** [comment]
我来加个测试用例

**Comment by king-lxt** [comment]
@chenshuai2144  好的  我是在config里配置了   base: URLMap['baseRoute'][REACT_APP_ENV || 'dev'], 
顺便在请教下，怎么屏蔽logo自带的跳转事件 ，onMenuHeaderClick 自定义点击事件，但是logo自带的跳转也生效 谢谢

**Comment by chenshuai2144** [comment]
Logo里面用了一个a 标签 你在meunHeaderRender上解除一下事件冒泡

**Comment by king-lxt** [comment]
@chenshuai2144 V5版本 config.ts 增加公共路由， 点击二级路由，页面可以打开，但是对应的菜单没有高亮     这个问题修复了吗？

**Comment by chenshuai2144** [comment]
你不是说是 base 的问题吗? 我加了个 base 的读取机制，不过只有 layout 支持

**Comment by king-lxt** [comment]
@chenshuai2144  没太明白，我更新下依赖  就可以了吧?

**Comment by chenshuai2144** [comment]
还没发 这周末就好了
