### ISSUE TITLE
🐛[BUG]tyarn run build failed 

### ISSUE THREAD

**Issue by Ying-Git** [ant-design/ant-design-pro#7242]
### 🐛 bug 描述

当使用umi v3.1.1时， tyarn run build 失败 ，运行tyarn start正常。
当使用umi v3.2.6时，tyarn run build 成功，但是tyarn start后进入不了页面

### 📷 复现步骤
使用umi v3.1.1  tyarn build 报错
![image](https://user-images.githubusercontent.com/53270124/90862302-d3ce6900-e3bf-11ea-9df4-cf64fd698987.png)

使用umi v3.2.6  tyarn start 浏览器报错
![image](https://user-images.githubusercontent.com/53270124/90862929-c5348180-e3c0-11ea-8bec-d0cac61f1e45.png)

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本: v3.1.1
- 浏览器环境 chrome
- 开发环境  Vscode

**Comment by chenshuai2144** [comment]
把你的路径改一下吧，这个路径估计触发什么字符串处理的问题了
