### ISSUE TITLE
部署后请求图片404

### ISSUE THREAD

**Issue by hudawen** [ant-design/ant-design-pro#725]
前端代码中对图片资源配置为src="..."的形式，部署到服务器后打开页面总是`GET http://localhost:7001/logo.png 404 (Not Found)`，但我服务器资源路径为`http://localhost:7001/public/logo.png`，该怎么修改请求路径呢，试了在.roadhogrc中配置publicPath但不起作用。

**Comment by chenshuai2144** [comment]
你去适应服务端 上面加上public

**Comment by chenshuai2144** [comment]
publicPath 作用 参见 #649

**Comment by hudawen** [comment]
@chenshuai2144 那`src=""`指向的路径是不起作用的吗

**Comment by chenshuai2144** [comment]
对 不起 不操作代码

**Comment by hudawen** [comment]
`<img alt="" className={styles.logo} src="public/logo.png" />`
那像这种前端指定的静态资源路径部署后没有意义？

**Comment by chenshuai2144** [comment]
`<img alt="" className={styles.logo} src="/public/logo.png" />`
加个 `/` 不然使用browser history 会报错。

**Comment by hudawen** [comment]
缓存造成的。。。
