### ISSUE TITLE
🧐[问题]模板里的标准列表，翻页和搜索条件不起作用，这个标准列表怎么玩？

### ISSUE THREAD

**Issue by xiangHannibal** [ant-design/ant-design-pro#7252]

**Comment by xiangHannibal** [comment]
![9OXU9HSW~37CFGJXQYLLD(P](https://user-images.githubusercontent.com/6896623/91026262-1ba5f800-e62d-11ea-8e46-c4207b33c2c9.png)

就是这个列表，怎么让搜索条件和翻页起作用

**Comment by xiangHannibal** [comment]
这块有小伙伴有完整的demo吗？给个细节的链接，前端初学者，这玩意包装后整不了

**Comment by chenshuai2144** [comment]
https://gitee.com/ant-design/pro-blocks/tree/master/ListBasicList

可以看这里，要自己做一些改动了，这么是只能看看的 demo
