### ISSUE TITLE
🐛[BUG]v5版本官网预览页面mix模式自动分割菜单后点击子菜单没有redirect

### ISSUE THREAD

**Issue by zooeydotmango** [ant-design/ant-design-pro#7253]
### 🐛 bug 描述

antd v5，官方预览页面，混合菜单布局，自动分割菜单后
点击顶部菜单，出现白屏页面
在自己的项目中设置redirect后，路由能够跳转，但是没有载入组件
### 🏞 期望结果
点击顶部菜单可以redirect到菜单第一个子页面

### 💻 复现代码

[https://preview.pro.ant.design/profile/basic?navTheme=light&primaryColor=daybreak&layout=mix&splitMenus=true](url)

### © 版本信息

- Ant Design Pro 版本: 4.5.2
- umi 版本:3.2.16
- 浏览器环境：chrome
- 开发环境 ：windows10

**Comment by chenshuai2144** [comment]
需要自己去 config 中配置
