### ISSUE TITLE
🧐[npm install报错: npm WARN tar ENOENT: no such file or directory]

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-pro#7254]
### 🧐 问题描述

npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated @hapi/joi@16.1.8: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated har-validator@5.1.5: this
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated intl-locales-supported@1.8.12: bad publish
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN tarball tarball data for typescript@^3.5.3 (sha1-mNYApevcOPQMsndSLxLcgA6eJfo=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\path-browserify-3b0bb9ce\test\test-path.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\es-abstract-97c5d054\2020\SetIntegrityLevel.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\es-abstract-ab25e7a0\2019\ToPropertyDescriptor.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\parse5-b83ed148\lib\common\doctype.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\es-abstract-97c5d054\helpers\setProto.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\regenerate-unicode-properties-72a824af\General_Category\Modifier_Letter.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\es-abstract-ab25e7a0\5\ToPropertyDescriptor.js'
……
……
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\@ant-design\icons-svg-18a53a75\lib\asn\InboxOutlined.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'E:\projects\test\ant\node_modules\.staging\@ant-design\icons-svg-18a53a75\es\index.d.ts'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yangyang43\AppData\Roaming\npm-cache\_logs\2020-08-24T08_54_04_848Z-debug.log

### 🚑 其他信息
node版本 v12.18.3
npm版本 6.14.6
镜像源：https://registry.npm.taobao.org/
没有设置任何代理 or 域名绑定

参考了下方文中说明的去除国际化的方法
https://github.com/ant-design/ant-design-pro/issues/6987
但是失败了，报错
E:\projects\test\ant>npm run i18n-remove

> ant-design-pro@4.2.0 i18n-remove E:\projects\test\ant
> pro i18n-remove --locale=zh-CN --write

'pro' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.2.0 i18n-remove: `pro i18n-remove --locale=zh-CN --write`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@4.2.0 i18n-remove script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

求大神指点迷津

**Comment by iambool** [comment]
使用过yarn、cnpm、tyarn，都没有成功

**Comment by chenshuai2144** [comment]
node_modules.staging@ant-design 
你这个是什么奇怪的包？

**Comment by iambool** [comment]
> node_modules.staging@ant-design
> 你这个是什么奇怪的包？

我也不清楚它是怎么生成的，一开始我使用的是最新的node.js。后来使用了 12.14.1 版本的node，然后使用yarn安装就成功了。。上面的报错其实并没有真正的解决

**Comment by chenshuai2144** [comment]
没有人知道 node_modules 里发生了什么

**Comment by KenNaNa** [comment]
有解决的方案了？

**Comment by BskyRui** [comment]
rm -rf package-lock.json, it works for me.

**Comment by iambool** [comment]
> 有解决的方案了？

下方这位兄弟给出了解决方案
