### ISSUE TITLE
ant-design-pro  兼容到ie几呢？🧐[问题]

### ISSUE THREAD

**Issue by Dawn-hjj** [ant-design/ant-design-pro#7259]

**Comment by chenshuai2144** [comment]
加上 profill 能到 ie11，再低了无法支持

**Comment by Dawn-hjj** [comment]
喔喔谢谢，那v2也只能兼容到11吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 中午1:42
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"晨曦"<2469277933@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] ant-design-pro  兼容到ie几呢？🧐[问题] (#7259)





 
加上 profill 能到 ie11，再低了无法支持

**Comment by chenshuai2144** [comment]
可以的
