### ISSUE TITLE
🐛[BUG] Using webpack aliases  doesn't work for Typescript in version 4.x.x

### ISSUE THREAD

**Issue by cundejo** [ant-design/ant-design-pro#7260]
### 🐛 bug 描述

We are using a monorepo structure for our project, and when changed from ant-design-pro 2.x to 4.x we found that the external aliases we defined to link our TypeScript libraries don't work anymore, Webpack complains about not having the appropriate loader.

### 📷 复现步骤

If we have a monorepo project with this structure: 

```
monorepo-project
    |- app-ant-design-pro
    |- foo-package
        |- index.ts   
```

Where `app-ant-design-pro` is an app with **ant-design-pro version 2.2.0**, and `foo-package` is just a small module in TS.

If I want to include the `foo-package` as an alias to use it in `app-ant-design-pro`, in **ant-design-pro 2.2.0** all I need to do is include the alias in `app-ant-design-pro/config/plugin.config.js` like this:

```js
// app-ant-design-pro/config/plugin.config.js
// Configuration for external alias. THIS WORKS for ant-design-pro 2.2.0

import path from 'path';

export default (config) => {
  // ...rest of the configuration...

  config.resolve.alias.set('@foo', path.join(__dirname, '../../foo-package'));
}
```

But this solution doesn't work in **ant-design-pro 4.2.0**. I included the following on `app-ant-design-pro/config/config.ts`:

```ts
// app-ant-design-pro/config/config.ts
// Configuration for external alias. THIS DOES NOT WORK for ant-design-pro 4.2.0

import path from 'path';

export default defineConfig({
  // ...rest of the configuration...

  chainWebpack: (config) => {
    config.resolve.alias.set('@foo', path.join(__dirname, '../../foo-package'));
  },
});
```

When we try to use the module `@foo` we have the following error:

![image](https://user-images.githubusercontent.com/10601715/91311484-88360980-e789-11ea-95ba-752dd6ba91d3.png)

### 🏞 期望结果

I want to be able to create aliases for external modules for TypeScript as we did in ant-design-pro 2.2.0

### © 版本信息

- Ant Design Pro 版本: 4.2.0
- umi 版本: 3.2.14
- 浏览器环境: Chrome 84.0.4147.125
- 开发环境: Linux Ubuntu 18.04

**Comment by chenshuai2144** [comment]
yep，please wait some time， Both the community and the solutions we use are upgraded
