### ISSUE TITLE
🧐[问题] AntdProV5 用yarn create umi 拉取全部模块的步骤  

### ISSUE THREAD

**Issue by maomft** [ant-design/ant-design-pro#7262]
### 🧐 问题描述
没有像v4有Complete的选项，不知道选哪个可以拉到v5全部模块？求一下可以傻瓜执行的步骤

**Comment by siaoynli** [comment]
目前没有的拉吧？个人感觉umi ui简直就是累赘

**Comment by maomft** [comment]
> 目前没有的拉吧？个人感觉umi ui简直就是累赘
~~issues 挂着也没人回

**Comment by xrkffgg** [comment]
0 - 0 有啥问题？

**Comment by maomft** [comment]
> 0 - 0 有啥问题？

umi怎么一次性拉全部v5页面模块?我目前是在本机的开发页面一个一个拉取的~~最好有能用可操作的步骤.谢谢了

**Comment by xrkffgg** [comment]
这个好像没有

**Comment by chenshuai2144** [comment]
`yarn  fetch-blocks --branch v5`

这样搞就好了

**Comment by luxiaojian2016** [comment]
yarn fetch-blocks --branch v5  为什么执行后，还是没有加载所有的组件
