### ISSUE TITLE
🧐[问题]V5里如何实现点击页面某按钮就增加一个菜单的功能？

### ISSUE THREAD

**Issue by UnrealIce** [ant-design/ant-design-pro#7263]
### 🧐 问题描述

按钮位于某个页面（子组件）中，按钮名为“增加菜单”，点击后输入基本的信息，确定后就增加一个菜单项。

app.tsx里的patchRoutes只能是初始化的时候用一下，似乎不能在运行时随时改动？

看了一些文章，说是要修改BasicLayout.tsx，但V5已经没这个文件了，难道不能用V5默认的layout，一定要自己写一个Layout？这样工作量有点大啊～

请各路大神指点一下有无简单的办法，感谢！

**Comment by UnrealIce** [comment]
研究了一下自己解决了，虽然不是很完美的解法。
1、在函数组件内利用useModel('@@initialState')获得setInitialState函数。按钮点击事件可以调用setInitialState，把菜单放到initialState里；
2、在app.tsx里，利用layout的属性menuDataRender，拿到initialState里的菜单，拼装起即可。

不算完美的地方：菜单是有了，但是点击后的路由对应的组件也需要自己去配置，还要支持动态加载，略麻烦。试了一下ProLayout例子里的多个路由对应一个菜单项，indexRoute似乎不起作用，疑似bug？

如果有更好的方案，也欢迎补充

**Comment by chenshuai2144** [comment]
indexRoute 在umi3中被废弃了

**Comment by Snow670** [comment]
@UnrealIce 求助求助，请问下这个功能最后是怎么实现的呢  可以贴下代码嘛
