### ISSUE TITLE
🐛[BUG] api.addDepInfo is not a function, at _default (xxx_project/node_modules/@umijs/plugin-antd/lib/index.js:84:7)

### ISSUE THREAD

**Issue by xishanxu** [ant-design/ant-design-pro#7265]
### 🐛 bug 描述

今早起来运行项目，yarn run dev, 突然报错
![image](https://user-images.githubusercontent.com/43942406/91380137-cb11e300-e856-11ea-8054-1732909697ce.png)
没有安装任何新依赖，  和任何代码改动
删除node_modules后，重新cnpm i ，也尝试了 yarn install, 但是安装依赖到最后也会报同样的错误
api.addDepInfo is not a function
TypeError: api.addDepInfo is not a function

### 📷 复现步骤

第二天突然项目启动不了，
api.addDepInfo is not a function
TypeError: api.addDepInfo is not a function

![image](https://user-images.githubusercontent.com/43942406/91417126-e4c91f80-e882-11ea-83f1-8b4c1d916bd4.png)

### 🏞 期望结果

项目启动成功

### 💻 复现代码

yarn run dev

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.1.1
- 浏览器环境 Chrome 
- 开发环境 [e.g. mac OS]
-- node.js版本v14.6.0
-- cnpm@6.1.1 
-- npm@6.13.6 
-- yarn@1.21.1

### 🚑 其他信息

如截图等其他信息可以贴在这里
这是所有依赖
![image](https://user-images.githubusercontent.com/43942406/91380354-57bca100-e857-11ea-97be-8514139298da.png)

**Comment by 569202812** [comment]
同样遇到了重装了依赖可以了,但是报错

![image](https://user-images.githubusercontent.com/34082148/91430963-42189d00-e892-11ea-91a1-4422ef712f9f.png)

**Comment by chunge66** [comment]
Change "umi" version to "umi": "^3.2.17" in package.json solve this issue.

**Comment by kyssion** [comment]
antd bug 太多了, 这个问题非常诡异 , 遇到同样的问题 + 1

**Comment by kyssion** [comment]
这个问题 100% 是umi 有一个不兼容的更新导致的

**Comment by chenshuai2144** [comment]
已经修复，回滚了
