### ISSUE TITLE
🐛[BUG] Failed to load parser '@typescript-eslint/parser' declared in '--config

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#7267]
### 🐛 bug 描述
![QQ浏览器截图20200827144750](https://user-images.githubusercontent.com/3166799/91405018-636a9080-e874-11ea-95f4-92cdb9cb8505.png)

### © 版本信息

- Ant Design Pro 版本: 6.4.12
- umi 版本 3.2.17
- eslint 7.7.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by DAHU123** [comment]
这个问题时怎么解决的呀？
