### ISSUE TITLE
🧐[问题]V5 app.tsx中responseInterceptor中无法使用useIntl()

### ISSUE THREAD

**Issue by taomengyue** [ant-design/ant-design-pro#7268]
国际化在app.tsx中做返回数据统一拦截，发现用不了useIntl()
notification.info({
        description: useIntl().formatMessage({ id: 'error' }),
        message: useIntl().formatMessage({ id: 'error' }),
});
![image](https://user-images.githubusercontent.com/65144847/91421340-67081280-e888-11ea-9a7c-4b6b4d459ad9.png)

![image](https://user-images.githubusercontent.com/65144847/91421186-3031fc80-e888-11ea-8812-6efd1cd09769.png)

**Comment by UnrealIce** [comment]
这么用：
```
import { getIntl } from 'umi';

// 必须在函数里用以下语句
const intl = getIntl()
```
当初我也是被坑了好久才找到的……

**Comment by taomengyue** [comment]
> 这么用：
> 
> ```
> import { getIntl } from 'umi';
> 
> // 必须在函数里用以下语句
> const intl = getIntl()
> ```
> 
> 当初我也是被坑了好久才找到的……

哎呀，真的是太谢谢了，解决了。再问个问题，你做的多语言是从后端获取的吗？
