### ISSUE TITLE
在表单Form.Item里放入react-draft-wysiwyg编辑器样式被覆盖

### ISSUE THREAD

**Issue by sskcal** [ant-design/ant-design-pro#727]
<FormItem
            {...formItemLayout}
            label="内容"
            >
              {getFieldDecorator('content', {
                rules: [{
                    required: true,
                    message: '内容不能为空!'
                }],
            })(
                <EditorInput />
            )}
            </FormItem>

EditorInput组件里的样式被污染了，咋办啊？

**Comment by sskcal** [comment]
` <FormItem
            {...formItemLayout}
            label="内容"
            >
              {getFieldDecorator('content', {
                rules: [{
                    required: true,
                    message: '内容不能为空!'
                }],
            })(
                <EditorInput />
            )}
            </FormItem>`

**Comment by chenshuai2144** [comment]
css强行继承。。。
你可能需要将react-draft-wysiwyg的css 做一些修改
