### ISSUE TITLE
👑 [需求]配置了proxy.js后，如何直接在js中（非umi-request调用中）使用解析后的地址

### ISSUE THREAD

**Issue by shoutrain** [ant-design/ant-design-pro#7270]
### 🥰 需求描述

比如我在如下config.js中配置了代理地址，在umi-request中可以直接使用/server/xxx?id=xx得到对应环境的真实地址：http://localhost:3000/xxx?id=xx，但我没有找到如何在其他js中直接使用这个地址，比如<img src='/server/xxx?id=xx' /\>这样的用法。是否有一个函数，可以协助我返回代理地址解析后的真实地址，比如<img src={someFun('/server/xxx?id=xx');} /\>，这个someFun('/server/xxx?id=xx');就可以返回：http://localhost:3000/xxx?id=xx

```javascript
export default {
    dev: {
        '/server/': {
            target: 'http://localhost:3000',
            changeOrigin: true,
            pathRewrite: {
                '^/server': '',
            },
        },
    },
    test: {
        '/server/': {
            target: 'http://localhost:3000',
            changeOrigin: true,
            pathRewrite: {
                '^/server': '',
            },
        },
    },
};
```

我找了umi-request以及umi-proxy-plugin，没有发现这样的API。难道需要自己写一个吗？还是有这样的API，我因为不熟悉没找到？

我当前用的解决方案使用了window.location.host，可以工作，但感觉不太安全，总觉得是不是有API直接用：

```javascript
<img
    alt={item.name}
    src={`http://${window.location.host}/server/image/get?id=${item.id}`}
/>
```

（以上代码其实在@/utils/utils中分装了个getImage，src={getImage(item.id)}这样）

谢谢。

**Comment by chenshuai2144** [comment]
前端不应该拿到真实的地址的

这个要交给容器来做

**Comment by Liu-Ya** [comment]
```jsx
<img
    alt={item.name}
    src={`/server/image/get?id=${item.id}`}
/>
```

**Comment by shoutrain** [comment]
> ```js-jsx
> <img
>     alt={item.name}
>     src={`/server/image/get?id=${item.id}`}
> />
> ```

works!!! 谢谢。

之前其实也直接用了`/server/...`，不知怎么没效果，才想其他办法。估计是犯了什么低级错我。
