### ISSUE TITLE
如何让侧边栏折叠按钮在侧边栏底部显示 而不是header

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#7271]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/91513254-7d5caf80-e916-11ea-8453-e6fc90679224.png)
![image](https://user-images.githubusercontent.com/27960630/91513301-99f8e780-e916-11ea-8be2-bdd1db6dafd0.png)

我想在侧边栏底部加折叠按钮 这样加 似乎没作用

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/27960630/91513123-248d1700-e916-11ea-83c9-b22cc39025eb.png)

**Comment by chenshuai2144** [comment]
位置不能自定义的 你可以关掉 然后用collapse 来受控一把

**Comment by lovesL** [comment]
![image](https://user-images.githubusercontent.com/27960630/91541026-4609f500-e94e-11ea-8ca6-d5c2b6c5b6bb.png)
@chenshuai2144  那这个是怎么在下面显示的

**Comment by lovesL** [comment]
https://prolayout.ant.design/example#%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95
