### ISSUE TITLE
🧐[问题]pro4,如何在不使用登录组件，直接接入公司openid，获取到页面跳转后，通过获取user用户接口返回权限，在localstorage保存antd-pro-Authority后，自动加载路由权限，目前需要手动刷新页面才能获取，否则报403

### ISSUE THREAD

**Issue by puxinhe** [ant-design/ant-design-pro#7272]
### 🧐 问题描述
pro4,如何在不使用登录组件，直接接入公司openid，获取到页面跳转后，通过获取user用户接口返回权限，在localstorage保存antd-pro-Authority后，自动加载路由权限，目前需要手动刷新页面才能获取，否则报403

**Comment by chenshuai2144** [comment]
执行一下 `reloadAuthorized` 就好了，可以执行 

```
window.reloadAuthorized()
```
