### ISSUE TITLE
🧐[问题] prov4版本，当采用动态获取后台菜单数据显示到页面时，F5刷新页面后，菜单打开到当前菜单位置且不显示高亮，再次选中时当前页所在菜单也没有反应

### ISSUE THREAD

**Issue by gggtuujat** [ant-design/ant-design-pro#7274]
### 🧐 问题描述
prov4版本，当采用动态获取后台菜单数据显示到页面时，F5刷新页面后，菜单打开到当前菜单位置且不显示高亮，再次选中时当前页所在菜单也没有反应。

### 💻 示例代码
```
  const [menuData, setMenuData] = useState([]);
  useEffect(() => {
      let menuList:any=[];
      if (dispatch) {
        dispatch({
          type: 'menu/fetch',
          payload:{tenantId:'4244b3ed6e4b',noPage:1},
          callback:(res:any)=>{
            if(res.status ==='success') {
              menuList= getMenuTree(res.data.list,2)
              // menuFormat(menuList);// icon 处理
              setMenuData(menuList);
            }else{
              setMenuData([]);
            }
          }
        });
      }
  }, []);

```
```
    menuDataRender={()=>menuData}
```

### 🚑 其他信息
选中当前菜单后F5刷新页面
![image](https://user-images.githubusercontent.com/41365173/91542425-6d61c180-e950-11ea-96f1-0d60e8d3e924.png)

![image](https://user-images.githubusercontent.com/41365173/91542511-91bd9e00-e950-11ea-9fbc-45705bfe22a6.png)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu

看这里，无法复现，你要不要重新触发一下 setData

**Comment by LB-nan** [comment]
@gggtuujat  我也遇到了，请问你解决了吗，是如何解决的

**Comment by LB-nan** [comment]
升级版本到`"@ant-design/pro-layout": "^6.4.18"`就好了
