### ISSUE TITLE
global.tsx中代码导致 DOMException: Only secure origins are allowed.🐛[BUG]

### ISSUE THREAD

**Issue by jjwong1991** [ant-design/ant-design-pro#7275]
### 🐛 bug 描述

由于serviceWorker和cacheStorage只能在https页面中被使用，在部分未使用https的项目中，[链接](https://github.com/ant-design/ant-design-pro/blob/c43f6eba9f6dcb09bf2dc33b9a7b298706bdeb6b/src/global.tsx#L62-L84)中的代码片段会导致谷歌浏览器抛出 DOMException: Only secure origins are allowed 错误，如[#6845](https://github.com/ant-design/ant-design-pro/issues/6845)中的情形

### 📷 复现步骤

Chrome61版本，依照文档安装，执行npm start

### 🏞 期望结果

正常展示页面

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] latest
- umi 版本 latest
- 浏览器环境 Chrome 61
- 开发环境 [e.g. mac OS] Windows 10

**Comment by chenshuai2144** [comment]
来个pr?

**Comment by afc163** [comment]
close #7280
