### ISSUE TITLE
antd Pro V2相关咨询

### ISSUE THREAD

**Issue by xinruoxiangyang1997** [ant-design/ant-design-pro#7277]
### 💻 示例代码
 'Cannot find module \'@/utils/utils.less\' from \'D:\\Mitu_save\\tobacco\\src\\pages\\Topic\\SolveProblem\'',
  stack:
   'Error: Cannot find module \'@/utils/utils.less\' from \'D:\\Mitu_save\\tobacco\\src\\pages\\Topic\\SolveProblem\'\n    at module.exports (D:\\Mitu_save\\tobacco\\node_modules\\less-plugin-npm-import\\node_modules\\resolve\\lib\\sync.js:33:11)\n    at NpmFileManager.resolve (D:\\Mitu_save\\tobacco\\node_modules\\less-plugin-npm-import\\lib\\npm-file-manager.js:29:16)\n    at NpmFileManager.loadFile (D:\\Mitu_save\\tobacco\\node_modules\\less-plugin-npm-import\\lib\\npm-file-manager.js:52:29)\n    at ImportManager.exports.default.ImportManager.push (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\import-manager.js:149:43)\n    at ImportVisitor.processImportNode (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\visitors\\import-visitor.js:87:28)\n    at ImportVisitor.visitImport (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\visitors\\import-visitor.js:50:22)\n    at Visitor.visit (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\visitors\\visitor.js:77:34)\n    at Visitor.visitArray (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\visitors\\visitor.js:113:22)\n    at Ruleset.accept (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\tree\\ruleset.js:44:34)\n    at Visitor.visit (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\visitors\\visitor.js:91:22)\n    at ImportVisitor.run (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\visitors\\import-visitor.js:23:27)\n    at Object.parse (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\parser\\parser.js:254:22)\n    at Object.parse (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\parse.js:82:18)\n    at Object.render (D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\render.js:26:18)\n    at D:\\Mitu_save\\tobacco\\node_modules\\less\\src\\less\\render.js:17:24\n    at new Promise (<anonymous>)'

### 🚑 其他信息
希望求一个js版本的antd pro2.x版本，因为经常使用jsx写组件比较多。

**Comment by xinruoxiangyang1997** [comment]
less警告已解决，但是还是想求一个稳定的pro2.0版本

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/tree/2.2.0

**Comment by yongzhizou** [comment]
请问ess警告已解决是如何解决的谢谢

**Comment by xinruoxiangyang1997** [comment]
> 请问ess警告已解决是如何解决的谢谢

将config下面的plugin.config.js中的所有代码注释掉，这里原来是官方写的一个less合并的插件，应该是有问题，之前有一个issue下面官方解释过，我现在没找到，你先将这个文件注释掉再试下吧

**Comment by xinruoxiangyang1997** [comment]
> 请问ess警告已解决是如何解决的谢谢

看这个， #2755
