### ISSUE TITLE
🐛[BUG]  在表格页面 点击功能块的全屏按钮，然后在点击表格的编辑弹窗，弹窗没有在全屏里面打开。

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7278]
### 🐛 bug 描述

在表格页面 点击功能块的全屏按钮，然后在点击表格的编辑弹窗，弹窗没有在全屏里面打开。

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/45235142/91678069-1ab61e80-eb77-11ea-8040-2beeaad5d2b4.png)
![image](https://user-images.githubusercontent.com/45235142/91678089-26a1e080-eb77-11ea-8b70-ff14ac980c8c.png)
![image](https://user-images.githubusercontent.com/45235142/91678100-30c3df00-eb77-11ea-826f-94793a4b352a.png)
![image](https://user-images.githubusercontent.com/45235142/91678114-38838380-eb77-11ea-9090-dbcd91c46e74.png)

全屏的时候 弹窗没有显示出来， 在关闭全屏的时候，弹窗是显示的
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
弹窗要挂载在 table中才可以。

getTargetContainer=()=> document.getElementById('pro-table')

**Comment by Asence** [comment]
@chenshuai2144 这个东西需要加到哪？

**Comment by chenshuai2144** [comment]
@Asence  加到 antd 的modal 上面

**Comment by Asence** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/45235142/92681544-7a26e200-f360-11ea-827c-3ddd614dbd4b.png)
我们的页面很大 公司这边希望全屏的时候全屏整个最大的盒子；最好全屏事件能传一个盒子id 自定义全屏的盒子ID； 希望您能快点给个解决方案，项目到下个星期就要上线了，谢谢
