### ISSUE TITLE
🧐[问题] 路由， /api/v1/projects/<project_id>

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/ant-design-pro#7279]
建议用这种路由，  /api/v1/projects/<project_id>吗？
  - 有project_id时，/api/v1/projects/1
  - 无project_id时，/api/v1/projects

 似乎不太方便吧

**Comment by afc163** [comment]
有啥不方便的呢？

**Comment by gaohongwei** [comment]
> 有啥不方便的呢？

要定义多个endpoint吧？
如果一个endpoint 可以的话，发个例子学习一下。

**Comment by afc163** [comment]
不太理解你的意思，非 Pro 的前端相关问题不再这里回答了，你可以到相关技术社区咨询。

**Comment by gaohongwei** [comment]
这是一个很典型的 Pro 的前端 API call啊，怎么就关掉了？ 好歹也发个例子说明怎么方便啊。
