### ISSUE TITLE
关于权限组件

### ISSUE THREAD

**Issue by teeemooo** [ant-design/ant-design-pro#728]
实际应用中 一般都是根据登陆的用户查询获取相应角色 菜单 资源等信息，没有权限的菜单基本上不会查询并返回前台，现在的权限组件的实际意义何在？

**Comment by chenshuai2144** [comment]
我们面向前后端分离的业务。前后端高度耦合需要自己实现

**Comment by teeemooo** [comment]
分离的话也不是把菜单带着权限全撸出来吧 。。。。

**Comment by chenshuai2144** [comment]
然而是的。。。
前台配置。后台喂数据。

**Comment by teeemooo** [comment]
应该是我理解错了 这个不涉及角色权限 只是鉴权
