### ISSUE TITLE
不存在的路由没有跳转404🐛[BUG]

### ISSUE THREAD

**Issue by it5200** [ant-design/ant-design-pro#7281]
### 🐛 bug 描述

不存在的路由没有跳转404 ，v4/v5 都有这个问题

### 📷 复现步骤

访问v4/v5 官方在线示例即可复现

v5 https://preview.pro.ant.design/dashboard/analysis1

### 🏞 期望结果

跳转404
### 💻 复现代码

线上示例 ： https://preview.pro.ant.design/dashboard/analysis1
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] v4/v5
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![WX20200831-183547](https://user-images.githubusercontent.com/19451694/91711672-d77c9f80-ebb8-11ea-9d47-03405a998c8a.png)

**Comment by chenshuai2144** [comment]
官方是故意的，你可以通过 设置一个不带 path 的组件来让其跳转

**Comment by HurriedOn** [comment]
地址栏输入菜单一级路由也会跳到空白页，没有跳到404

**Comment by HurriedOn** [comment]
地址栏输入菜单一级路由也会跳到空白页，没有跳到404    https://preview.pro.ant.design/dashboard/
