### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by leehaoxindehao** [ant-design/ant-design-pro#7285]
### 🧐 Umi2.0升级到Umi3.0的有些文件找不到
 问题描述

https://pro.ant.design/docs/upgrade-umi3-cn，官网文档中关于升级到Umi3.0的内容中，以下的内容在我的项目中找不到：tsconfig文件；config.ts的lessLoaderOptions 、cssLoaderOptions 、IConfig属性，请问这种情况该如何升级到Umi3.0，谢谢了

**Comment by chenshuai2144** [comment]
写标题
