### ISSUE TITLE
🐛[BUG]移除国际化后系统启动多了好多warning

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-pro#7286]
### 🐛 bug 描述
移除了国际化后，插件里依然生成了国际化相关的代码
![image](https://user-images.githubusercontent.com/20501316/91822608-9c3aa900-ec6a-11ea-94fa-028faebb1d3e.png)
![image](https://user-images.githubusercontent.com/20501316/91822635-a3fa4d80-ec6a-11ea-8bfd-d47ce50e7cea.png)

### 📷 复现步骤

- 移除国际化配置

### 🏞 期望结果

正常启动无警告

### 💻 复现代码
无

### © 版本信息

- Ant Design Pro 版本: V5.0
- umi 版本 3.2.19
- 浏览器环境 chrome
- 开发环境 mac OS

**Comment by WangJM001** [comment]
https://github.com/umijs/plugins/pull/326 和这个调整有关

**Comment by 569202812** [comment]
> [umijs/plugins#326](https://github.com/umijs/plugins/pull/326) 和这个调整有关

这个有修复吗,新创建的项目也是这样
