### ISSUE TITLE
🧐[问题] table的dataSource更新后，页面不刷新

### ISSUE THREAD

**Issue by jlq023** [ant-design/ant-design-pro#7287]
### 🧐 问题描述 
Table的dataSource，使用state定义的数据源，动态更新state的数据源后，table显示的还是旧数据，table没有刷新，在render方法打印dataSource，在控制台看到的是新数据，以下代码和截图，均使用官方下载的例子   详情页-高级详情页。

antd版本为antd4.5.1,pro版本为"4.1.0"。

### 💻 示例代码（部分代码）
 
class Advanced extends Component {

 state = {
    operationKey: 'tab1',
    tabActiveKey: 'detail',
    advancedOperation1: [{key: "op1",memo:"-",
      name:"曲丽丽",
      status:"agree",
      type:"订购关系生效",
      updatedAt:"2017-10-03  19:23:12"
    }]
  };

render() {
    let { operationKey, tabActiveKey, advancedOperation1 = [] } = this.state;  
    console.log("render:",advancedOperation1);
    const contentList = {
      tab1: (
        <Table
          pagination={false}
          loading={loading}
          dataSource={advancedOperation1}
          columns={columns}
        />
      ),
      tab2: (
        <Table
          pagination={false}
          loading={loading}
          dataSource={advancedOperation2}
          columns={columns}
        />
      ),
      tab3: (
        <Table
          pagination={false}
          loading={loading}
          dataSource={advancedOperation3}
          columns={columns}
        />
      ),
    };
    
    return (
...
           <Card
              className={styles.tabsCard}
              bordered={false}
              tabList={operationTabList}
              onTabChange={this.onOperationTabChange}
            >
              {contentList[operationKey]}
            </Card>
            <Button onClick={() => {
              let item = {
                key: "statekey",
                memo:"1",
                name:"state曲丽丽2",
                status:"3",
                type:"state订购关系生效4",
                updatedAt:"2020-09-01 09:23:12"
              };
              let advancedOperation1 = this.state.advancedOperation1;
              advancedOperation1[0] = item;
               this.setState(advancedOperation1)
            }} >测试</Button>
...
)

}

  
}

### 🚑 其他信息

![state_data](https://user-images.githubusercontent.com/32348538/91826356-0b66cc00-ec70-11ea-8658-bafd37d756e5.png)

我正式项目antd用3.x，都可以这样重置table数据源，table也可以刷新,4.x就不支持这种方式还是其它原因？
当然重置state数据源可以用以下方法，但确实不方便,因为我这个列表属性有20 多个，昨天第一次遇到这个问题，还把我难住了一会,之前还没遇到过这种问题。
<Button onClick={() => { 
              let advancedOperation1 = this.state.advancedOperation1;
              advancedOperation1[0].name ="state曲丽丽2"
              advancedOperation1[0].updatedAt="2020-09-01 09:23:12"
               this.setState(advancedOperation1)
            }} >测试</Button>

**Comment by chenshuai2144** [comment]
table 现在有优化，如果key相同他是不会更新的，建议你使用

```
setState({
  data:[]
},()=>{
  setState({
     data:relaData
  }
})
```

**Comment by earthaYan** [comment]
@chenshuai2144 同遇到这个问题，在函数组件中有什么替代的实现方法么，尝试使用useEffct好像不太行
