### ISSUE TITLE
🧐[问题]请问除了在根目录下弄一个app.js，还有其他方法可以获取当前一整套路由信息的吗

### ISSUE THREAD

**Issue by aoyinke** [ant-design/ant-design-pro#7288]
### 🧐 问题描述

请问除了在根目录下弄一个app.js，还有其他方法可以获取当前一整套路由信息的吗

**Comment by chenshuai2144** [comment]
layout 组件的 props 中会带给你,你可以放一个根的 layout 组件，这样就可以拿到所有路由了
