### ISSUE TITLE
🐛[BUG]Protable column列表项配置copyable后 信息的显示和复制 在hover时会重叠

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/ant-design-pro#7289]
### 🏞 期望结果
复制的情况多为复制单号，一般只会有一行，数字有部分会被遮挡住
希望可以出一个方案

显示如下

![image](https://user-images.githubusercontent.com/40973214/91834189-48d05700-ec7a-11ea-97ee-0cd0051b07e4.png)

**Comment by chenshuai2144** [comment]
有一个 issue，去 pro-compents 里跟踪吧
