### ISSUE TITLE
点击浏览器后退按钮，不会后退，需要点击多次

### ISSUE THREAD

**Issue by XiangDeMei** [ant-design/ant-design-pro#729]
项目在本地片跑起来之后，点击浏览器的后退按钮不会跳转，需要点击两次，如果是再往前一次的页面就需要点击三次。点击一次之后从浏览器里看起来已经后退了，但是并没有跳转。
![image](https://user-images.githubusercontent.com/16175984/35021923-28df2250-fb6e-11e7-91e3-6ccd98e4b6e0.png)
请问这是什么原因那？

**Comment by chenshuai2144** [comment]
什么浏览器版本？

**Comment by XiangDeMei** [comment]
linux chrome 版本 63.0.3239.132（正式版本） （64 位）

**Comment by chenshuai2144** [comment]
你试试我们的预览界面有没有问题？

**Comment by XiangDeMei** [comment]
是没有问题的，在本地跑起来让其他人访问也是一样的

**Comment by chenshuai2144** [comment]
我在本地也ok的。。。你是不是该考虑一下是不是你电脑有什么特殊的？

**Comment by XiangDeMei** [comment]
就是没有头绪。。不知道什么引起的。所以来问问

**Comment by chenshuai2144** [comment]
你试着把history暴露出来

**Comment by XiangDeMei** [comment]
请问应该怎么看那？

**Comment by chenshuai2144** [comment]
利用的hash？

**Comment by XiangDeMei** [comment]
是的

**Comment by XiangDeMei** [comment]
通过window.history 来看，每次长度时增加了２
![image](https://user-images.githubusercontent.com/16175984/35028286-421ea9ee-fb90-11e7-9447-14bdebae3984.png)

**Comment by chenshuai2144** [comment]
这么科学的

**Comment by XiangDeMei** [comment]
不用hash是完全不能后退。。会不会包有什么问题

**Comment by XiangDeMei** [comment]
请问该怎么获取路由堆栈那？

**Comment by XiangDeMei** [comment]
在阿里云上部署试了一下也是一样的问题。。。

**Comment by longzhaobi** [comment]
@XiangDeMei   你把BasicLayout.js这个文档的108行的代码：
```
window.history.pushState(null, 'redirect', urlParams.href);
```
删掉就可以正常前进后退了，这个会导致要点很多次才会后退。

**Comment by chenshuai2144** [comment]
没有重定向也会吗？

**Comment by chenshuai2144** [comment]
我应该catch一下的

**Comment by XiangDeMei** [comment]
去掉确实不会了，不然每次都会push一遍

**Comment by chenshuai2144** [comment]
@XiangDeMei  @longzhaobi  谢谢你们的帮助。我会修改掉这个问题

**Comment by LKCheng** [comment]
我也刚发现了这个问题，刚想来提交，哈哈～😄
