### ISSUE TITLE
🐛[BUG] ant pro v4 js环境新安装报错Error: Failed to load plugin 'eslint-comments' declared in 'BaseConfig

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design-pro#7291]
### 🐛 bug 描述
ant pro4 js环境安装不了了，按照默认流程下来，提示umi缺少模块

接上个问题，改用`yarn create`还是报错
https://github.com/ant-design/ant-design-pro/issues/7290

以为是umi的问题，将全局的umi删除了，还是没用
```
yarn global remove create-umi
```

报错如下：
> 有很多都报这个错误，这里只截一小段 Error: Failed to load plugin 'eslint-comments' declared in 'BaseConfig
```
Require stack:
- /Library/WebServer/Documents/cn.51baopen/admin/v1.05/__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.resolve (internal/modules/cjs/helpers.js:81:19)
    at Object.resolve (/Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/shared/relative-module-resolver.js:40:50)
    at ConfigArrayFactory._loadPlugin (/Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine/config-array-factory.js:1004:39)
    at /Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine/config-array-factory.js:895:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine/config-array-factory.js:891:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine/config-array-factory.js:719:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/eslint/lib/cli-engine/config-array-factory.js:659:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Library/WebServer/Documents/cn.51baopen/admin/v1.05/__placeholder__.js'
  ],
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: 'eslint-plugin-eslint-comments',
    resolvePluginsRelativeTo: '/Library/WebServer/Documents/cn.51baopen/admin/v1.05',
    importerName: 'BaseConfig » /Users/liwei/.config/yarn/global/node_modules/sylvanas/node_modules/@umijs/fabric/dist/eslint.js'
  }
}
```

### 📷 复现步骤
仅安装pro4 js环境

### 🏞 期望结果
应该不报错

### 💻 复现代码
```
yarn create umi
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V4
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! antd@4
```

### © 版本信息

- Ant Design Pro 版本: Pro V4
- umi 版本：umi@3
- 浏览器环境：不需要浏览器
- 开发环境：mac OS

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/578141/91848595-54794900-ec8d-11ea-8508-8aa49dfa4af5.png)

**Comment by liangxp** [comment]
哎，这个问题提出无数次了，没人鸟！

**Comment by kwdiwt** [comment]
这边也遇这个问题~~

**Comment by zybn2004** [comment]
是 sylvanas 的问题

[eslint 报 plugin-missing MODULE_NOT_FOUND 错误 #11](https://github.com/umijs/sylvanas/pull/11)

不过官方还木有合并

**Comment by chenshuai2144** [comment]
升级一下 fabric 到2.x  ,eslint 到 7.x 就能解决

**Comment by zybn2004** [comment]
> 升级一下 fabric 到2.x ,eslint 到 7.x 就能解决
> 
> [umijs/sylvanas#10](https://github.com/umijs/sylvanas/pull/10)

yarn create umi 时就是用最新的 create-umi 包的（create-umi 它是使用 "sylvanas": "^0.5.0"，而 sylvanas 0.5.x 内部依赖的是 "@umijs/fabric": "^2.2.2" 和 "eslint": "^7.7.0"）。

我这边（mac OS Catalina 10.15.6 ，当前 yarn 版本号是 1.22.4）产生 plugin-missing 的原因是：

eslint 的 CLIEngine 默认 resolve 包的起始路径是 yarn create umi 时所在的文件目录，同时 yarn create umi 下载的包位于 `/Users/zybn2004/.config/yarn/global/node_modules`，问题就在于 eslint 的 CLIEngine resolve 不到 `/Users/zybn2004/.config/yarn/global/node_modules` 这个路径，然后就报错了，对此行为我也比较困惑，也许是 yarn 的 bug吧。

我这边解决的方式是 [fix: eslint 报 plugin-missing MODULE_NOT_FOUND 错误 #11](https://github.com/umijs/sylvanas/pull/11)，通过增加 eslint 的 CLIEngine 的 resolvePluginsRelativeTo 参数指定 resolve 为 sylvanas 包所在的目录（因为该目录的 package.json 直接依赖了正确的 @umijs/fabric 和 eslint）。

**PS：[sylvanas@0.5.0 npm](https://www.npmjs.com/package/sylvanas/v/0.5.0) 上的 package.json 和 sylvanas github 上的 [package.json](https://github.com/umijs/sylvanas/blob/master/package.json)  是不一致的。**

**Comment by crazysunnylong** [comment]
> eslint

fabrci升级到latest 2.3.1，eslint升级到latest  7.13.0同样还是报错

**Comment by crazysunnylong** [comment]
> > 升级一下 fabric 到2.x ,eslint 到 7.x 就能解决
> > [umijs/sylvanas#10](https://github.com/umijs/sylvanas/pull/10)
> 
> @chenshuai2144
> 
> yarn create umi 时就是用最新的 create-umi 包的（create-umi 它是使用 "sylvanas": "^0.5.0"，而 sylvanas 0.5.x 内部依赖的是 "@umijs/fabric": "^2.2.2" 和 "eslint": "^7.7.0"）。
> 
> 我这边（mac OS Catalina 10.15.6 ，当前 yarn 版本号是 1.22.4）产生 plugin-missing 的原因是：
> 
> eslint 的 CLIEngine 默认 resolve 包的起始路径是 yarn create umi 时所在的文件目录，同时 yarn create umi 下载的包位于 `/Users/zybn2004/.config/yarn/global/node_modules`，问题就在于 eslint 的 CLIEngine resolve 不到 `/Users/zybn2004/.config/yarn/global/node_modules` 这个路径，然后就报错了，对此行为我也比较困惑，也许是 yarn 的 bug 或者我的 yarn 缺少一些环境配置。
> 
> 我这边解决的方式是 [fix: eslint 报 plugin-missing MODULE_NOT_FOUND 错误 #11](https://github.com/umijs/sylvanas/pull/11)，通过增加 eslint 的 CLIEngine 的 resolvePluginsRelativeTo 参数指定 resolve 为 sylvanas 包所在的目录（因为该目录的 package.json 直接依赖了正确的 @umijs/fabric 和 eslint）。
> 
> **PS：[sylvanas@0.5.0 npm](https://www.npmjs.com/package/sylvanas/v/0.5.0) 上的 package.json 和 sylvanas github 上的 [package.json](https://github.com/umijs/sylvanas/blob/master/package.json) 是不一致的。**

你这段代码是加的位置在哪里？
要怎么操作？
