### ISSUE TITLE
🧐[问题]V5版本动态路由相关问题？

### ISSUE THREAD

**Issue by timofun** [ant-design/ant-design-pro#7293]
### 🧐 问题描述
后端返回的路由之后，放进menuDataRender里，页面是可以出来，
但是鉴权问题怎么处理，access无效；
没有匹配的路由404也无效，有没有案例参考

**Comment by karlspace7** [comment]
https://umijs.org/zh-CN/docs/routing#wrappers
这个可以处理

**Comment by timofun** [comment]
> https://umijs.org/zh-CN/docs/routing#wrappers
> 这个可以处理

谢谢，不是想要的
