### ISSUE TITLE
🧐[问题]使用vscode格式化less文件后，git显示有改动

### ISSUE THREAD

**Issue by htank-wang** [ant-design/ant-design-pro#7296]
### 🥰 需求描述
使用vscode格式化less文件后，git显示有改动。
是否有额外的vscode的配置或插件要安装。

![image](https://user-images.githubusercontent.com/17918845/91969486-bea2f400-ed48-11ea-9e42-448298a9992e.png)

### 🧐 解决方案

官方是否出一个IED配置的文档出来，要装哪些插件，要配置哪些东西。或者放一份setting.json

**Comment by chenshuai2144** [comment]
我们统一使用 prettier 来进行配置，是有配置文件的。不过你要先安装 依赖。我们也有 ci 检查格式是否正确。


看你截图的错误，你应该是修改了  tab 的配置改成了4个空格
