### ISSUE TITLE
如何优化antd pro 打包

### ISSUE THREAD

**Issue by ysh0552** [ant-design/ant-design-pro#7297]
### 🧐 问题描述

已经开启的按需加载，可还是体积很大，而且启动也要21秒，如何优化？

### 💻 

![QQ截图20200903110724](https://user-images.githubusercontent.com/14260225/92067114-1d627f00-edd6-11ea-9a39-da55ab3c7f0a.png)
)

**Comment by chenshuai2144** [comment]
看起来无解，最好的办法是等 webpack5.

https://umijs.org/guide/boost-compile-speed

**Comment by my9988** [comment]
> 看起来无解，最好的办法是等 webpack5.
> 
> https://umijs.org/guide/boost-compile-speed

@chenshuai2144 关于打包的大小问题，我看很多人都在提问，我也在苦恼中，首页加载很慢。我也看了umijs的说明，我还是想在这里继续咨询这个问题

1.你提到等webpack5，我看目前官网已经是5.1了，请问我们用的webpack是什么版本？怎么查版本呢？按网上不少方法试了。
2.dist\4.a16a8e91.async.js                     3.0 MB         836.4 KB  如下图中包含的antv,如果我只是用了一个import { Column } from '@ant-design/charts';   antv也都要打包进去吗？不了解互相的关系。

![image](https://user-images.githubusercontent.com/17469220/105803005-766bc300-5fc2-11eb-8bff-bb1354dca4c3.png)

3.关于打包配置问的人比较多，antd pro能不能写个推荐配置？
