### ISSUE TITLE
🐛[BUG]从服务器获取的菜单icon无法显示

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#7298]
**一、版本**
1、"umi": "^3.0.14",
2、"@ant-design/pro-layout": "^5.0.8",

**二、数据库存储路由菜单**
![image](https://user-images.githubusercontent.com/20454290/92083338-76dba580-edf8-11ea-82bd-d4ad3b13f4c9.png)

**三、页面展示**
![image](https://user-images.githubusercontent.com/20454290/92083393-8fe45680-edf8-11ea-8a1f-62753134f0b1.png)

**四、代码**
![image](https://user-images.githubusercontent.com/20454290/92083479-aee2e880-edf8-11ea-9d39-280b77519d1f.png)

![image](https://user-images.githubusercontent.com/20454290/92083521-bbffd780-edf8-11ea-9461-cbad352c21f2.png)

**五、问题：请问该如何正常显示logo？**

**Comment by hot588** [comment]
百度下，就解决了Q！

**Comment by 419280377** [comment]
有需要的自取！
menu的各种操作：https://prolayout.ant.design/menu

**Comment by edifangyi** [comment]
感谢楼上
![image](https://user-images.githubusercontent.com/12421552/95297160-90b35100-08ac-11eb-9c16-bfb03b393b2b.png)
