### ISSUE TITLE
🧐[问题]项目刚打开的时候这个加载页面在哪里修改

### ISSUE THREAD

**Issue by LB-nan** [ant-design/ant-design-pro#7299]
### 🧐 问题描述

这个一闪而过的加载页面在哪里，如何修改？

### 🚑 其他信息

![1](https://user-images.githubusercontent.com/26077292/92087451-10f21c80-edfe-11ea-8989-a70bf68dbad6.jpg)

**Comment by LB-nan** [comment]
![1](https://user-images.githubusercontent.com/26077292/92087494-223b2900-edfe-11ea-9cd7-b22a22b75413.jpg)

**Comment by TianenPang** [comment]
`@/src/pages/document.ejs` 在这个文件中自定义或者修改
