### ISSUE TITLE
组件打包缺少依赖

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-pro#73]

**Comment by teemosauce** [comment]
## webpack
## less
## babel-core

**Comment by nikogu** [comment]
- [x] 之前依赖了 `scaffold` 里面 `utils.js` 以及 `utils.less` 等依赖，已经抽离
- [x] 打包部分包未暴露 `module.exports = exports['default'];` 导致打包失败

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro-site/commit/6eabb53b3836b0f52dbca41fcef61e6da3f08478
