### ISSUE TITLE
🧐[问题]v4以后的table变得这么难用了，功能是丰富了，可惜不灵活了

### ISSUE THREAD

**Issue by xshans** [ant-design/ant-design-pro#7300]
### 🧐 问题描述

封装的pro-table，难用度非常高，还是没有v2时候的灵活度和简单度，现在想加个条件都得折腾半天封装的组件。
要不是v2有个 选择月份跨度的组件不好用 还真不会去研究v4了。虽然功能是多了好多，界面也好看了很多。

**Comment by jlq023** [comment]
v4把table,搜索表单，添加和修改的表单，统一到column配置，开发效率很高，缺点的确不灵活，不过一些基础的增删改查表格，protable还是可以胜任的，我也在研究protable，坑貌似还不少，尤其是用级联菜单。

**Comment by chenshuai2144** [comment]
你可以当成一个普通的antd的table来用的，我们会以用户为准。
