### ISSUE TITLE
🐛[BUG]macos 下运行npm run 报错Module parse failed: Unexpected character '#' (1:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by CheKey30** [ant-design/ant-design-pro#7301]
### 🐛 bug 描述

在macos下运行npm start，webpack打包进行到99%时报错，内容为：
 ERROR  Failed to compile with 1 errors                                                                                                                                              10:09:07 AM

 error  in ./node_modules/netlify-lambda/bin/cmd.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| 
| /**

 @ dll umi

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.3.1 start: `cross-env NOW_ENV=local_no_auth APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.3.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### 📷 复现步骤

package.json 设置如下：
{
  "name": "ant-design-pro",
  "version": "2.3.1",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "presite": "cd functions && npm install",
    "start": "cross-env NOW_ENV=local_no_auth APP_TYPE=site umi dev",
    "start:no-mock": "cross-env NOW_ENV=local_no_auth MOCK=none umi dev",
    "build": "cross-env NOW_ENV=local_auth umi build",
    "site": "umi build && npm run functions:build",
    "analyze": "cross-env ANALYZE=1 umi build",
    "lint:style": "stylelint 'src/**/*.less' --syntax less",
    "lint:prettier": "check-prettier lint",
    "lint": "eslint --ext .js src mock tests && npm run lint:style && npm run lint:prettier",
    "lint:fix": "eslint --fix --ext .js src mock tests && stylelint --fix 'src/**/*.less' --syntax less",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "tslint": "npm run tslint:fix",
    "tslint:fix": "tslint --fix 'src/**/*.ts*'",
    "test": "umi test",
    "test:component": "umi test ./src/components",
    "test:all": "node ./tests/run-tests.js",
    "prettier": "node ./scripts/prettier.js",
    "docker:dev": "docker-compose -f ./docker/docker-compose.dev.yml up",
    "docker:build": "docker-compose -f ./docker/docker-compose.dev.yml build",
    "docker-prod:dev": "docker-compose -f ./docker/docker-compose.yml up",
    "docker-prod:build": "docker-compose -f ./docker/docker-compose.yml build",
    "docker-hub:build": "docker build  -f Dockerfile.hub -t  ant-design-pro ./",
    "docker:tag": "docker tag ant-design-pro antdesign/ant-design-pro",
    "docker:push": "npm run docker-hub:build && npm run docker:tag && docker push antdesign/ant-design-pro",
    "functions:build": "npm run generateMock && netlify-lambda build ./lambda",
    "functions:run": "npm run generateMock && cross-env NODE_ENV=dev netlify-lambda serve ./lambda",
    "generateMock": "node ./scripts/generateMock",
    "build:local": "cross-env NOW_ENV=local_auth umi build",
    "build:dev": "cross-env NOW_ENV=dev umi build",
    "build:test": "cross-env NOW_ENV=test umi build",
    "build:pro": "cross-env NOW_ENV=pro umi build"
  },
  "dependencies": {
    "@antv/data-set": "^0.10.1",
    "@babel/runtime": "^7.3.1",
    "antd": "^3.15.2",
    "bizcharts": "^3.4.3",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.2.6",
    "d3": "^3.5.17",
    "dva": "^2.4.1",
    "enquire-js": "^0.2.1",
    "express": "^4.16.4",
    "gg-editor": "^2.0.2",
    "hash.js": "^1.1.7",
    "jquery": "^3.3.1",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.1",
    "memoize-one": "^5.0.0",
    "module": "^1.2.5",
    "moment": "^2.24.0",
    "netlify-lambda": "^1.4.3",
    "numeral": "^2.0.6",
    "nzh": "^1.0.4",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^3.0.0",
    "prop-types": "^15.6.2",
    "qs": "^6.6.0",
    "rc-animate": "^2.6.0",
    "react": "^16.7.0",
    "react-container-query": "^0.11.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dnd": "9.3.2",
    "react-dnd-html5-backend": "9.3.2",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.7.0",
    "react-fittext": "^1.0.0",
    "react-media": "^1.9.2",
    "react-router-dom": "^4.3.1",
    "socket.io-client": "2.2.0",
    "tableau-react": "^1.2.1",
    "umi": "2.4.4",
    "umi-plugin-react": "1.7.2",
    "umi-request": "1.0.5"
  },
  "devDependencies": {
    "@types/history": "^4.7.2",
    "@types/react": "^16.8.1",
    "@types/react-dom": "^16.0.11",
    "antd-pro-merge-less": "^1.0.0",
    "antd-theme-webpack-plugin": "^1.2.0",
    "babel-eslint": "^10.0.1",
    "chalk": "^2.4.2",
    "check-prettier": "^1.0.1",
    "cross-env": "^5.2.0",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.9.0",
    "eslint": "^5.13.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-compat": "^2.6.3",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-markdown": "^1.0.0",
    "eslint-plugin-react": "^7.12.4",
    "gh-pages": "^2.0.1",
    "husky": "^1.3.1",
    "jest-puppeteer": "^4.1.0",
    "less": "^3.9.0",
    "lint-staged": "^8.1.1",
    "merge-umi-mock-data": "^1.0.4",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^1.17.0",
    "serverless-http": "^1.9.1",
    "slash2": "^2.0.0",
    "stylelint": "^9.10.1",
    "stylelint-config-css-modules": "^1.3.0",
    "stylelint-config-prettier": "^5.0.0",
    "stylelint-config-rational-order": "^0.0.4",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-declaration-block-no-ignored-properties": "^1.1.0",
    "stylelint-order": "^2.0.0",
    "tslint": "^5.12.1",
    "tslint-config-prettier": "^1.17.0",
    "tslint-react": "^3.6.0",
    "umi": "2.4.4",
    "umi-plugin-ga": "1.1.3",
    "umi-plugin-react": "1.7.2"
  },
  "optionalDependencies": {
    "puppeteer": "^1.12.1"
  },
  "lint-staged": {
    "**/*.{js,ts,tsx,json,jsx,less}": [
      "node ./scripts/lint-prettier.js",
      "git add"
    ],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "checkFiles": [
    "src/**/*.js*",
    "src/**/*.ts*",
    "src/**/*.less",
    "config/**/*.js*",
    "scripts/**/*.js"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged"
    }
  }
}
先运行npm install， 没有问题。再运行npm run start 报错。

### 🏞 期望结果

前端编译通过

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 2.4.4
- 浏览器环境
- macos

**Comment by chenshuai2144** [comment]
这个库已经没用了。直接删掉吧。理论上你不会引用到这个库的

netlify-lambda 是node环境的，所以你打包有问题。
