### ISSUE TITLE
🐛[BUG] umi has no exported member 'useModel' problem.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#7302]
### 🐛 bug 描述
There was no such error before.
Module '"../../../node_modules/umi/types"' has no exported member 'useModel'.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
you can  run  ` "postinstall": "umi g tmp"` .

**Comment by icedcoke** [comment]
我遇到一样的问题

**Comment by laozhu** [comment]
一样的问题

**Comment by stepbystep2** [comment]
> 一样的问题

请问解决了吗

**Comment by yangkuo1993** [comment]
遇到了同样的问题，怎么解决？

**Comment by ETRick** [comment]
我也遇到了，在自定义的 model 文件中加了一个局部函数引起的，把多余内容挪出去就好了，否则会解析失败，无法生成 src/.umi/plugin-model。

**Comment by yangkuo1993** [comment]
> 我也遇到了，在自定义的 model 文件中加了一个局部函数引起的，把多余内容挪出去就好了，否则会解析失败，无法生成 src/.umi/plugin-model。

umi g tmp

**Comment by ilanguis** [comment]
有此问题+1，并且执行umi g tmp并未修复。

**Comment by chenshuai2144** [comment]
> 在自定义的 model 文件中加了一个局部函数引起的

试试这个

**Comment by NeroSolomon** [comment]
> 有此问题+1，并且执行umi g tmp并未修复。

@ilanguis 请问最后解决了么，我执行了umi g tmp也不行

**Comment by lian8306** [comment]
vcode提示错误Module '"../../../../../node_modules/umi/types"' has no exported member 'Effect'.ts(2305)

**Comment by D-liszt** [comment]
可以尝试在tsconfig.json 中加入下面的方法：

"compilerOptions": {
        "experimentalDecorators": true
    }

猜测原因是在TypeScript中装饰器还属于实验性语法，所以要想使用必须在配置文件中tsconfig.json编译选项中开启
@NeroSolomon
