### ISSUE TITLE
在tab标签中使用steps和modal后关闭modal时页面异常滚动的bug🐛[BUG]

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design-pro#7303]
### 🐛 bug 描述

我在tab中嵌入了步骤条（steps）和模态框（modal）!当我点击步骤条打开模态框（modal）后关闭，之前的页面会自动滚动到中间！

### 📷 复现步骤

点击tab页切换到弹窗，并点击【点我查看bug】后关闭modal框就会复现

### 🏞 期望结果

页面不进行任何滚动，保持原来的状态

### 💻 复现代码

https://codesandbox.io/s/strange-moore-nehpd?file=/src/App.js

预览bug:
https://nehpd.csb.app/

### © 版本信息

- Ant Design Pro 版本: [4.6.2]
- umi 版本
- 浏览器环境 [chrome 版本 85.0.4183.83（正式版本）（64 位]
- 开发环境 [mac OS]

### 🚑 其他信息
预览bug:
https://nehpd.csb.app/

**Comment by chenshuai2144** [comment]
antd中已经修复了， 4.6.3 版本安装即可
