### ISSUE TITLE
🐛[BUG]混合菜单布局

### ISSUE THREAD

**Issue by Strive-Java** [ant-design/ant-design-pro#7304]
### 🐛 bug 描述

问题1:
   混合菜单布局->自动分割菜单
   点击顶部菜单，右侧菜单展开后未自动触发第一个菜单项

问题2：
   混合菜单布局->自动分割菜单
   右侧菜单文字显示不全，请查看截图

### 📷 复现步骤

无

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20058791/92201796-03956a80-eeb0-11ea-84b7-8ac3a9e0e81d.png)
![image](https://user-images.githubusercontent.com/20058791/92202603-f7121180-eeb1-11ea-8629-0436cd1b2aa8.png)

**Comment by liujiayii** [comment]
问题1我这是做了一下重定向……
问题2补充一下没有icon的情况下菜单组是显示一半文字，单个菜单是显示空白
点击左下角那个收齐和展开，icon大小有明显的差异，看起来有点别扭

**Comment by Strive-Java** [comment]
> 问题1我这是做了一下重定向……
> 问题2补充一下没有icon的情况下菜单组是显示一半文字，单个菜单是显示空白
> 点击左下角那个收齐和展开，icon大小有明显的差异，看起来有点别扭

**Comment by Strive-Java** [comment]
> 问题1我这是做了一下重定向……
> 问题2补充一下没有icon的情况下菜单组是显示一半文字，单个菜单是显示空白
> 点击左下角那个收齐和展开，icon大小有明显的差异，看起来有点别扭

可以参考下里面的综合布局：vue-admin-beautiful-pro
地址：https://chu1204505056.gitee.io/vue-admin-beautiful-pro/?hmsr=github&hmpl=&hmcu=&hmkw=&hmci=#/index
这里两个问题的方案他都解决了

**Comment by Strive-Java** [comment]
> 问题1我这是做了一下重定向……
> 问题2补充一下没有icon的情况下菜单组是显示一半文字，单个菜单是显示空白
> 点击左下角那个收齐和展开，icon大小有明显的差异，看起来有点别扭

针对问题1、问题2的情况
这个平台他都考虑进去了，感觉他这个方案非常的赞，如Ant Design Pro采纳，那更加赞👍啦
打开以下链接->选择主题配置->综合布局
地址：https://chu1204505056.gitee.io/vue-admin-beautiful-pro/?hmsr=github&hmpl=&hmcu=&hmkw=&hmci=#/vab/roles

**Comment by jlq023** [comment]
> > 问题1我这是做了一下重定向……
> > 问题2补充一下没有icon的情况下菜单组是显示一半文字，单个菜单是显示空白
> > 点击左下角那个收齐和展开，icon大小有明显的差异，看起来有点别扭
> 
> 针对问题1、问题2的情况
> 这个平台他都考虑进去了，感觉他这个方案非常的赞，如Ant Design Pro采纳，那更加赞啦
> 打开以下链接->选择主题配置->综合布局
> 地址：https://chu1204505056.gitee.io/vue-admin-beautiful-pro/?hmsr=github&hmpl=&hmcu=&hmkw=&hmci=#/vab/roles

这个不错

**Comment by chenshuai2144** [comment]
>  问题2：
混合菜单布局->自动分割菜单
右侧菜单文字显示不全，请查看截图

这个最好都配置 icon 或者都不配置

**Comment by chenshuai2144** [comment]
>  https://chu1204505056.gitee.io/vue-admin-beautiful-pro/?hmsr=github&hmpl=&hmcu=&hmkw=&hmci=#/vab/roles

这个感觉不错，我们会好好看看
