### ISSUE TITLE
🧐[问题]侧边导航收缩再展开，右侧页面被遮挡

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#7305]
https://user-images.githubusercontent.com/50793943/92196002-d55c5e80-eea0-11ea-922b-0cdcc1981c94.png

不知道是什么原因导致的，如果图挂了，请看这个iss [https://github.com/ant-design/pro-components/issues/384](url)

**Comment by chenshuai2144** [comment]
在一个地方提就好了
