### ISSUE TITLE
react antd pro菜单与tab页联动

### ISSUE THREAD

**Issue by dinglingbo** [ant-design/ant-design-pro#7306]
点击左边菜单栏，可以在右边以tab形式展开菜单；切换tab可以定位到左边菜单栏。

![微信图片_20200905122802](https://user-images.githubusercontent.com/51599298/92297546-03aa6e80-ef73-11ea-8879-18bd89c84783.png)

**Comment by chenshuai2144** [comment]
这个感觉就是 多标签页的变种，
你可以用 topMenu 和 siderMenu 一起做个假的出来。

在umi支持 keep-alive 之前我们不会支持多标签页的

**Comment by Fengly0503** [comment]
自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs
