### ISSUE TITLE
🐛[BUG] V4 proTable在type=form下生成的表单class问题

### ISSUE THREAD

**Issue by cleverdb** [ant-design/ant-design-pro#7308]
### 🐛 bug 描述
proTable在type=form下生成的表单样式不对，
class如下
`<form class="ant-form ant-form-inline">`
官方demo：
`<form class="ant-form ant-form-vertical">`

### 🏞 期望结果

from 样式为 ant-form-vertical

### © 版本信息

版本：V4 JavaScript

**Comment by chenshuai2144** [comment]
可以自行配置一下


layout | 表单布局 | horizontal \| vertical \| inline | horizontal
-- | -- | -- | --
