### ISSUE TITLE
🧐[问题]warning Error running install script for optional dependency: "/var/jenkins_home/workspace/austgo-erp-antd/node_modules/node-pty: Command failed.

### ISSUE THREAD

**Issue by insistenceZHUO** [ant-design/ant-design-pro#7309]
### 🧐 问题描述
自动化部署 build的时候打包不成功

`
+ node -v
v12.18.0
+ npm -v
6.14.4
+ npm config get registry
https://registry.npm.taobao.org/
+ yarn config get registry
https://registry.npm.taobao.org
+ yarn -v
1.22.4
+ yarn install --pure-lockfile
yarn install v1.22.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @ant-design/pro-layout > omit.js > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning braft-editor > draft-js > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning umi > umi-build-dev > core-js@2.6.9: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning umi > umi-build-dev > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning umi > umi-ui > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning umi > umi-ui > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning umi > umi-ui > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning umi > umi-build-dev > af-webpack > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning umi > umi-build-dev > af-webpack > less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning umi > umi-build-dev > yeoman-generator > yeoman-environment > npm-api > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning umi > umi-build-dev > af-webpack > less > request > har-validator@5.1.5: this library is no longer supported
warning umi > umi-build-dev > af-webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning umi > umi-build-dev > umi-test > babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning umi > umi-build-dev > af-webpack > @svgr/core > h2x-core > h2x-parse > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning umi > umi-build-dev > umi-test > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning umi > umi-ui > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning umi > umi-ui > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning umi > umi-build-dev > umi-test > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning umi > umi-build-dev > sylvanas > @umijs/fabric > stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning umi-plugin-react > umi-plugin-polyfills > core-js@2.6.0: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning umi-plugin-react > workbox-webpack-plugin > workbox-build > joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning umi-plugin-react > umi-plugin-locale > react-intl > intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
warning umi-plugin-react > workbox-webpack-plugin > workbox-build > joi > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning umi-plugin-react > workbox-webpack-plugin > workbox-build > joi > topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning umi-plugin-react > workbox-webpack-plugin > workbox-build > joi > topo > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning @ant-design/pro-cli > pngjs-image > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > @hapi/joi@15.1.1: This version has been deprecated and is no longer supported or maintained
warning jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning jest-puppeteer > jest-environment-puppeteer > jest-dev-server > wait-on > @hapi/joi > @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
warning umi-types > @types/xterm@3.0.0: This is a stub types definition for xterm.js (https://github.com/sourcelair/xterm.js/). xterm.js provides its own type definitions, so you don't need @types/xterm installed!
warning umi-types > @types/webpack-chain@5.2.0: This is a stub types definition. webpack-chain provides its own type definitions, so you do not need this installed.
warning umi-types > @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "dva > connected-react-router@6.5.2" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > react-sortable-hoc@1.11.0" has unmet peer dependency "prop-types@^15.5.7".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi@1.6.0" has incorrect peer dependency "eslint-plugin-react-hooks@1.5.0".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@5.0.2" has unmet peer dependency "@typescript-eslint/eslint-plugin@2.x".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@5.0.2" has unmet peer dependency "@typescript-eslint/parser@2.x".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@5.0.2" has incorrect peer dependency "eslint@6.x".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@5.0.2" has incorrect peer dependency "eslint-plugin-flowtype@3.x".
warning "umi > umi-build-dev > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
warning "umi > umi-build-dev > sylvanas > @umijs/fabric > eslint-config-airbnb@17.1.1" has incorrect peer dependency "eslint-plugin-react@^7.14.2".
warning "umi-plugin-react > umi-plugin-dva > babel-plugin-dva-hmr@0.4.2" has unmet peer dependency "redbox-react@1.x".
warning "umi-plugin-react > umi-plugin-dva > dva-loading@3.0.6" has unmet peer dependency "dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0".
warning "@ant-design/pro-cli > @umijs/fabric > @typescript-eslint/eslint-plugin@3.10.1" has unmet peer dependency "@typescript-eslint/parser@^3.0.0".
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "/var/jenkins_home/workspace/austgo-erp-antd/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments: 
Directory: /var/jenkins_home/workspace/austgo-erp-antd/node_modules/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.0 | linux | x64
gyp info find Python using Python version 2.7.13 found at \"/usr/bin/python\"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/jenkins_home/workspace/austgo-erp-antd/node_modules/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/jenkins_home/.cache/node-gyp/12.18.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/jenkins_home/.cache/node-gyp/12.18.0',
gyp info spawn args   '-Dnode_gyp_dir=/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/var/jenkins_home/.cache/node-gyp/12.18.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/jenkins_home/workspace/austgo-erp-antd/node_modules/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Linux 3.10.0-693.2.2.el7.x86_64
gyp ERR! command \"/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/bin/node\" \"/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs12.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /var/jenkins_home/workspace/austgo-erp-antd/node_modules/node-pty
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
Done in 117.10s.
+ yarn run build
yarn run v1.22.4
$ umi build
`

**Comment by chenshuai2144** [comment]
这种一般是node版本的问题 升级到最新的稳定版本吧

**Comment by insistenceZHUO** [comment]
> 这种一般是node版本的问题 升级到最新的稳定版本吧

问题，已经解决，在解决前，我们后台反应说是内存溢出，服务器是8g的内存，然后我们删除了项目中没用的包，就打包成功了。
