### ISSUE TITLE
🧐[问题]查询列表的新增表单怎么横向排列

### ISSUE THREAD

**Issue by xiangHannibal** [ant-design/ant-design-pro#7311]

**Comment by xiangHannibal** [comment]
![M2X~N)J4)%(8LS63CIA)QRS](https://user-images.githubusercontent.com/6896623/92455759-aa517200-f1f4-11ea-8856-21fc37292b6a.png)

**Comment by chenshuai2144** [comment]
直接用 antd 的 form 配置


layout | 表单布局 | horizontal \| vertical \| inline | horizontal
-- | -- | -- | --
