### ISSUE TITLE
🧐[问题]npx create umi提示 找不到命令：create

### ISSUE THREAD

**Issue by s464446877** [ant-design/ant-design-pro#7313]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/52397868/92554336-ad516e80-f297-11ea-9501-7a433a6cea46.png)

还有就是v5beta版和正式版差别会不会很大，现在用v5beta版有什么影响吗

**Comment by chenshuai2144** [comment]
`npx create-umi` 命令是这样的

最好用 v5，更加小巧简单

**Comment by xsser** [comment]
官方文档改一下命令吧  我也遇到这个问题了
https://beta-pro.ant.design/docs/getting-started-cn

**Comment by chenshuai2144** [comment]
升级一下 npm 好了
