### ISSUE TITLE
🧐[问题]查询表格，新建按钮右侧的工具栏实现在哪里

### ISSUE THREAD

**Issue by wgf4242** [ant-design/ant-design-pro#7314]
### 🧐 问题描述
查询表格 页面，有全屏，调整高度。刷新。。。这几个我在这里搜索，发现搜不到。

对应的是ListTableList/index.tsx么？我进去看了也没找到。。

https://preview.pro.ant.design/list/table-list

![Snipaste_2020-09-09_23-51-40](https://user-images.githubusercontent.com/3336626/92622495-a8240c00-f2f7-11ea-9883-283617ab57be.jpg)

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table
看这里
