### ISSUE TITLE
🧐[问题]import顺序是否有一定的规范

### ISSUE THREAD

**Issue by itsuki0927** [ant-design/ant-design-pro#7316]
### 🧐 问题描述
这个import导入顺序是有规范还是是按照自己的风格导入嘛? 我看到这个导入顺序有点乱, 还是说在commit的时候会自动美化import?

### 💻 示例代码

如果是按照自己风格导入的话,并且使用的是`vscode`的话, 可以使用一个快捷键进行import的排序并且自动去除没有使用module:
mac: `option + shift + o`
window: `alt + shift + o`.

**Comment by hengkx** [comment]
这一块 好像 暂时 没有吧 ，你可以参考一下 antd 项目里面 现在的一些 总结出 规则 写到 wiki里面去 这个暂时先关了
