### ISSUE TITLE
🧐[问题]v5的页面logo也太难换了吧！！！

### ISSUE THREAD

**Issue by qweasd25** [ant-design/ant-design-pro#7317]
### 🧐 问题描述
把所有的logo都换了一遍，但是最终还是显示antd的logo。我无力吐槽啊

![image](https://user-images.githubusercontent.com/21007491/92708489-be2ddd00-f388-11ea-8566-2aa9ccc99650.png)

**Comment by chenshuai2144** [comment]
？？？  被什么卡住了?
```
export default defineConfig({
  layout: {
    name: 'Ant Design Pro',
    locale: true,
    logo:"url"
  },
}
```

**Comment by qweasd25** [comment]
刚开始不知道有这个属性，然后我测试了，路径有问题哎
![image](https://user-images.githubusercontent.com/21007491/92849746-401c1580-f41e-11ea-955f-30ba41f69541.png)
这么写不对么

> ？？？ 被什么卡住了?
> 
> ```
> export default defineConfig({
>   layout: {
>     name: 'Ant Design Pro',
>     locale: true,
>     logo:"url"
>   },
> }
> ```
![image](https://user-images.githubusercontent.com/21007491/92849795-4ca06e00-f41e-11ea-8877-e69ddecbf316.png)

**Comment by liujiayii** [comment]
> 刚开始不知道有这个属性，然后我测试了，路径有问题哎
> ![image](https://user-images.githubusercontent.com/21007491/92849746-401c1580-f41e-11ea-955f-30ba41f69541.png)
> 这么写不对么
> 
> > ？？？ 被什么卡住了?
> > ```
> > export default defineConfig({
> >   layout: {
> >     name: 'Ant Design Pro',
> >     locale: true,
> >     logo:"url"
> >   },
> > }
> > ```

logo可以放在public目录下面 不用@

**Comment by chenshuai2144** [comment]
是url，你要用动态的能力要去app.ts里的layou里配置 

还以为你碰到了bug！！结果只是没看文档

**Comment by qweasd25** [comment]
> 是url，你要用动态的能力要去app.ts里的layou里配置
> 
> 还以为你碰到了bug！！结果只是没看文档

尴尬了 哈哈哈哈 v4上直接logo替换掉就好了 v5还要改代码啊

**Comment by xiaohuoni** [comment]
看你们讨论这么嗨，我帮你们关掉好了。专心工作。

**Comment by chenshuai2144** [comment]
defaultSetting 我加回来吧
