### ISSUE TITLE
🧐[问题]footer 部分的怎么删掉啊

### ISSUE THREAD

**Issue by qweasd25** [ant-design/ant-design-pro#7318]
### 🧐 问题描述

这个明明在footer中删掉了，怎么还在啊，好像是自带的

![image](https://user-images.githubusercontent.com/21007491/92709035-2c729f80-f389-11ea-9f80-42e5a88a7809.png)

**Comment by qweasd25** [comment]
<DefaultFooter
    copyright={`xxxxx`}
    links={[]}
  />


修改的时候links也要保留，我开始统一删掉了

**Comment by fapjsc** [comment]
在BasicLayout.jsx裡面刪掉後，Welcome組件的footer沒有了，但是login頁面還是在，求解......
