### ISSUE TITLE
部署服务端代理请求报错

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#732]
pro项目直接clone下来，部署到服务端 ,pro自己代理的请求会报错，请问我应该怎么处理，谢谢

**Comment by longzhaobi** [comment]
打包后，部署到服务端，mock的数据都无效了。

**Comment by afc163** [comment]
这是合理的，mock 就是本地调试用的**模拟数据**，部署到生产环境需要和服务端接口进行配合。
