### ISSUE TITLE
logo怎么调整高度 🧐[问题]

### ISSUE THREAD

**Issue by kenzheng2020** [ant-design/ant-design-pro#7320]
.ant-pro-top-nav-header-logo img {
    display: inline-block;
    height: 32px;
    vertical-align: middle;
}

这里的32px，请问怎么可以调整大小？

**Comment by karlspace7** [comment]
你可以在app.tsx中设置自定义头部渲染来更改默认样式，如下图：
![image](https://user-images.githubusercontent.com/15607058/92922454-78484600-f468-11ea-8463-e1f6ac8e179d.png)
![image](https://user-images.githubusercontent.com/15607058/92922513-872ef880-f468-11ea-9cc7-ee2a010e5f5b.png)
![image](https://user-images.githubusercontent.com/15607058/92922523-8dbd7000-f468-11ea-9a8d-8cdc830e7720.png)

**Comment by chenshuai2144** [comment]
最好不要修改，会造成一些样式错误

**Comment by kenzheng2020** [comment]
:global {
  .ant-pro-top-nav-header-logo img {
    display: inline-block;
    height: 64px;
    vertical-align: middle;
  }
}

less里增加这个全局样式 替换掉默认的 实测管用
ps：不能改logo大小 甲方爸爸会打屁屁的
