### ISSUE TITLE
🐛[BUG]V5 删除国际化后的问题

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design-pro#7321]
### 🐛 bug 描述

```
 WARNING  Compiled with 8 warnings                                                                          上午10:50:54

 warning  in ./src/.umi/plugin-layout/layout/layout/renderRightContent.tsx

"export 'SelectLang' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/renderRightContent.tsx

"export 'SelectLang' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'getLocale' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/index.tsx

"export 'useIntl' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/index.tsx

"export 'useIntl' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'useIntl' was not found in 'umi'
```
![image](https://user-images.githubusercontent.com/23520283/92851902-b0c43180-f420-11ea-9c93-59dd8c60e89c.png)

### 📷 复现步骤

修改config.ts 移除国际化代码
![image](https://user-images.githubusercontent.com/23520283/92852088-e23cfd00-f420-11ea-88b2-482a7ce9eaa9.png)

### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本 3.2.20
- 浏览器环境 edge
- 开发环境 windows10

**Comment by Liu-Ya** [comment]
看起来是  https://github.com/umijs/plugin-layout 的问题，好像没人维护的样子😂

**Comment by chenshuai2144** [comment]
删除了国际化要顺便把 locale 设置为false

**Comment by Liu-Ya** [comment]
> 删除了国际化要顺便把 locale 设置为false，然后重启一下项目，会重新生成这个dom

没有用
![image](https://user-images.githubusercontent.com/23520283/93033289-3a197500-f668-11ea-8ede-96e4e9edb3ed.png)

**Comment by 569202812** [comment]
我也遇到了这个问题

**Comment by 569202812** [comment]
> 删除了国际化要顺便把 locale 设置为false，然后重启一下项目，会重新生成这个dom

这个删除了后不生效,需要怎么改吗

**Comment by YogaZong** [comment]
The same question.

**Comment by simplast** [comment]
遇到同样的问题，按照官网新建项目，dev启动就有一堆warning

**Comment by hujinbo** [comment]
我也遇到了同样的问题：
```js
 WARNING  Compiled with 5 warnings                                                                                                                                                                                 5:27:27 ├F10: PM┤

 warning  in ./src/.umi/plugin-layout/layout/layout/renderRightContent.tsx

"export 'SelectLang' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/renderRightContent.tsx

"export 'SelectLang' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'getIntl' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'getIntl' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'getLocale' was not found in 'umi'
```

**Comment by chenshuai2144** [comment]
👪 现在先忽略吧，都是 warning，要解决的需要很大的成本。有人有兴趣提个 pr 吗？

**Comment by wangfupeng1988** [comment]
- `config/config.ts` 中增加 `locale: {}`
- 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
- 重启服务

当前版本 `"umi": "^3.2.22"`

**Comment by chenshuai2144** [comment]
统一这里跟踪

https://github.com/ant-design/ant-design-pro/issues/7546

**Comment by guorouda** [comment]
> * `config/config.ts` 中增加 `locale: {}`
> * 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
> * 重启服务
> 
> 当前版本 `"umi": "^3.2.22"`

IT WORKS REALLY.

**Comment by GreynerVA** [comment]
> * `config/config.ts` 中增加 `locale: {}`
> * 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
> * 重启服务
> 
> 当前版本 `"umi": "^3.2.22"`

It worked to me, thanks.

**Comment by zsio** [comment]
> * `config/config.ts` 中增加 `locale: {}`
> * 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
> * 重启服务
> 
> 当前版本 `"umi": "^3.2.22"`

@wangfupeng1988  编译虽然不报错了，但是运行时报错。
![image](https://user-images.githubusercontent.com/16083606/106983885-9610a180-67a1-11eb-91e6-06243be39a76.png)

**Comment by chenshuai2144** [comment]
把菜单的locale关掉，在app.tsx 里设置 layout 加一个 menu.locale:false

**Comment by birdycn** [comment]
> 把菜单的locale关掉，在app.tsx 里设置 layout 加一个 menu.locale:false

@chenshuai2144 尝试配置
```
  menu: { locale: false },
    menuHeaderRender: undefined,
```

没有解决问题

**Comment by birdycn** [comment]
> > * `config/config.ts` 中增加 `locale: {}`
> > * 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
> > * 重启服务
> > 
> > 当前版本 `"umi": "^3.2.22"`
> 
> @wangfupeng1988 编译虽然不报错了，但是运行时报错。
> ![image](https://user-images.githubusercontent.com/16083606/106983885-9610a180-67a1-11eb-91e6-06243be39a76.png)

已经设置  menu: { locale: false },了，还是报错。

**Comment by chenshuai2144** [comment]
配置应该被覆盖了，你这个还是没关掉

**Comment by Onlylonger** [comment]
menu: { locale: false } 加了不生效呢
