### ISSUE TITLE
请教一下  antd proV5 打包问题

### ISSUE THREAD

**Issue by ysh0552** [ant-design/ant-design-pro#7326]
每次都要打包全部页面，有没有什么办法，只打包修改的页面？
因为每次发版本的时候都是整个包发，就不能一个一个页面发吗？
跟以前传统的HTML文件一样，改哪发哪

**Comment by chenshuai2144** [comment]
现在不流行这个了，改js已经是不可能的了。

一般都是一个版本发一次，直接上cdn。你那样估计要试试微服务了
