### ISSUE TITLE
🐛[BUG] react-pdf PDF generation is very slow

### ISSUE THREAD

**Issue by mleister97** [ant-design/ant-design-pro#7327]
I included **react-pdf** in a fresh umi project:
* PDF-Generation 150 Text-components took arround **311.44 ms without umi**
* Using umi: 7179.40 ms

**Every single element takes about 10X more in umi projects!**

**Code example I tried**
```javascript
import React from "react";
import "./styles.css";
import { Document, Page, pdf, Text, View } from "@react-pdf/renderer";

export default function App() {
  const pdfClickHandler = async () => {
    console.time("PDF generation took:");
    await pdf(
      <Document>
        <Page>
          <View>
            {Array.from(Array(150).keys()).map((key) => (
              <Text key={key}>text-element</Text>
            ))}
          </View>
        </Page>
      </Document>
    ).toBlob();
    console.timeEnd("PDF generation took:");
  };

  return (
    <div className="App">
      <button onClick={pdfClickHandler}>
        Generate fast PDF (without ant-design-pro)
      </button>
    </div>
  );
}

```

* Fast version: https://codesandbox.io/s/damp-thunder-rybh7
* Slow version: https://codesandbox.io/s/confident-leaf-hgk7c?file=/src/pages/user/login/index.tsx
[![Instructions slow version codesandbox][1]][1]
* Slow version (GitHub): https://github.com/mleister97/ant-design-react-pdf-slow
* (Slow version is a fresh setup of ant-design-pro, just modified the "startup"-page)
[![fast version][2]][2]
* (Make sure you open the Browser (:8000) Tab as the application is served on this port AND check directly the **browser's console**, not the codesandbox one)

**What is going on behind the scenes when the toBlob is beeing called?** 

How can I fix this issue?

  [1]: https://i.stack.imgur.com/QWi30.png
  [2]: https://i.stack.imgur.com/3xat4.png

**Comment by mleister97** [comment]
https://stackoverflow.com/questions/63855370/react-pdf-pdf-generation-is-very-slow-in-combination-with-ant-design-pro?noredirect=1#comment112920187_63855370

400 Points bounty

**Comment by mleister97** [comment]
The issue is related to umijs!

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是它已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but it has not responded for a long time. We will temporarily close it
