### ISSUE TITLE
🐛[BUG] v5 版本登录的菜单权限问题

### ISSUE THREAD

**Issue by iwaitu** [ant-design/ant-design-pro#7329]
### 🐛 bug 描述
当非管理员登录时，菜单仍然显示，虽然已经显示 403 了，但不会隐藏，需要刷新一下浏览器，那些 access: 'canAdmin' 的菜单才会隐藏，请问如何解决

### 📷 复现步骤
加入有一个这样的菜单配置

 {
      name: 'dashboard',
      icon: 'smile',
      path: '/dashboardanalysis',
      component: './DashboardAnalysis',
      access: 'canAdmin',
},

用非 admin 登录时菜单还是正常显示，只是右侧显示403 ，刷新浏览器后，这个 dashboard 才会隐藏
### 🏞 期望结果
应该是非 admin 登录时，该菜单不显示
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
手动刷新一下浏览器？

**Comment by iwaitu** [comment]
> 手动刷新一下浏览器？

是滴

**Comment by shuxiaoman** [comment]
同样的问题，需要access:'canAdmin'的页面，当切换用户后，左侧的菜单栏不会更新，只有按F5刷新才会重新加载菜单栏，

**Comment by chenshuai2144** [comment]
刷新一下把，不然没法触发reload

**Comment by hot588** [comment]
这个BUG，比较严重，确实是这样滴！
