### ISSUE TITLE
🧐[问题]请教下：在antd-pro里想要引用vue文件，配置了vue-loader，编译时提示‘ No matching use for vue-loader is found.’

### ISSUE THREAD

**Issue by zsfish** [ant-design/ant-design-pro#7331]
### 🧐 问题描述
想在antd-pro【使用的是antd@3分支代码】里使用vue的组件，下载了解析vue的依赖,使用vuera，在plugin.config.ts里配置了vue-loader,vue-style-loader,vueLoaderPlugin，在pages里引入vue组件，但编译时报错‘No matching use for vue-loader is found.’。是不能引入vue文件吗？

### 💻 示例代码
`
// config/plugin.config.ts
const VueLoaderPlugin = require('vue-loader/lib/plugin');
// 配置vue
   config.module
   .rule('vue')
   .test(/\.vue$/)
   .exclude
   .add([path.resolve('node_modules')])
   .end()
   .use('vue-loader')
   .loader('vue-loader')

 // 配置vue-style-loader
 config.module.rule('css')
   .test(/\.css$/)
   .exclude
   .add([path.resolve('node_modules')])
   .end()
   .use('vue-style-loader')
   .loader('vue-style-loader')

 // 配置vueLoaderPlugin
 config.plugin('VueLoaderPlugin').use(VueLoaderPlugin)`
`

### 🚑 其他信息
`
    "vue": "^2.6.12",
    "vue-loader": "^15.9.3",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.12",
    "vuera": "^0.2.7"
`

**Comment by chenshuai2144** [comment]
怎么说呢，这个功能pro不会支持，去 umi 问问把
