### ISSUE TITLE
🐛[BUG]ant pro 动态加载菜单，滑动模块怎么不显示呢？来看看图吧！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7332]
### 🐛 bug 描述

![1](https://user-images.githubusercontent.com/51880332/93017673-166d1500-f5fd-11ea-9bf6-30a6b3a07ef5.png)
![2](https://user-images.githubusercontent.com/51880332/93017674-1836d880-f5fd-11ea-8965-db41f5d68edb.png)

上图显示，必须往下翻，才能找到隐藏菜单的地方！

下图是官方的，他又那个滑动模块，就可以很方便了！
![3](https://user-images.githubusercontent.com/51880332/93017675-18cf6f00-f5fd-11ea-95cd-3d00d9c9f3a8.png)

详细地描述 bug，让大家都能理解
-->
谁能告诉我下，这个滑动模块，在哪里能够显示出来！！
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixSiderbar | 是否固定导航 | boolean | false
-- | -- | -- | --


滑动模块的学名叫滚动条。你可以用这个在mdn上搜到你想要的内容
