### ISSUE TITLE
🐛[BUG] 如果menu在上方，没有子菜单的menu会比有子菜单的menu高两个像素

### ISSUE THREAD

**Issue by kenzheng2020** [ant-design/ant-design-pro#7333]
![image](https://user-images.githubusercontent.com/54108006/93034501-cc237c80-f66c-11ea-9ff0-e285dba57683.png)

![image](https://user-images.githubusercontent.com/54108006/93034548-f2491c80-f66c-11ea-85fb-cceb8b7ea8d9.png)

![image](https://user-images.githubusercontent.com/54108006/93034614-39cfa880-f66d-11ea-97f7-7d831491642b.png)

**Comment by liujiayii** [comment]
[同样](https://github.com/ant-design/ant-design-pro/issues/6554)

**Comment by chenshuai2144** [comment]
存在很久了。需要antd 那边修一下
