### ISSUE TITLE
pro  突然不能编译代码了  🐛[BUG]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#7335]
### 🐛 bug 描述
在src目录下里面任意文件修改代码 代码不编译也没用热更新 
![image](https://user-images.githubusercontent.com/27960630/93037155-60dda880-f674-11ea-9e59-011cb863216d.png)
控制台一直这样
![image](https://user-images.githubusercontent.com/27960630/93036868-a2218880-f673-11ea-851f-5a0c9ff07aa7.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ThomasHang** [comment]
解决了没有，我也遇到了，保存后不编译

**Comment by 521guyu** [comment]
您解决了吗，我也是必须start一下才行，项目庞大了（上百个组件太费时间了）

**Comment by ThomasHang** [comment]
> 您解决了吗，我也是必须start一下才行，项目庞大了（上百个组件太费时间了）

我这边是在pages里重新建个文件夹，换个不同的名称，重新引入，把要用的页面放进去，昨天弄了大半天。完美解决。

**Comment by 521guyu** [comment]
就是在pages 下重新建一个文件夹，然后把原来的全部放进去，路由在重新引一下是吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;chu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月25日(星期五) 下午4:04
收件人:&nbsp;&quot;ant-design/ant-design-pro&quot;<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;&quot;谷雨&quot;<2952148908@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] pro  突然不能编译代码了  🐛[BUG] (#7335)
