### ISSUE TITLE
🧐[问题]pro-table的tip如何设置？

### ISSUE THREAD

**Issue by LB-nan** [ant-design/ant-design-pro#7336]
### 🧐 问题描述

我看官网的示例demo的表格有一个tip(网址：`https://preview.pro.ant.design/list/table-list`)，表头的那个`规则名称`旁边的小叹号，鼠标移上去有提示的那个，翻了github上的源码(`https://github.com/ant-design/ant-design-pro/blob/master/src/pages/ListTableList/index.tsx`),发现有一行代码` tip: '规则名称是唯一的 key',`，但是我配置完无效，文档上也没有这个字段，请问是需要下载什么插件之类的吗

**Comment by littlePrincessAlin** [comment]
我也遇到了一样的问题，请问有解吗？
