### ISSUE TITLE
https://umijs.org/zh-CN/docs/routing#wrappers

### ISSUE THREAD

**Issue by xd19831203** [ant-design/ant-design-pro#7338]
https://umijs.org/zh-CN/docs/routing#wrappers
这个可以处理

_Originally posted by @karlspace7 in https://github.com/ant-design/ant-design-pro/issues/7293#issuecomment-691054720_

那个……我在V5的项目里，没看见这个目录

**Comment by chenshuai2144** [comment]
v5 没用这个功能，你需要可以自己加上
