### ISSUE TITLE
umi3已经到来，开始支持ssr, prov4什么时候会支持呢？

### ISSUE THREAD

**Issue by wxf-start** [ant-design/ant-design-pro#7339]
### 🧐 问题描述

umi3已经到来，开始支持ssr, prov4什么时候会支持呢？

**Comment by wxf-start** [comment]
https://cnpmjs.org/package/umi-plugin-ssr/v/0.1.4 请问是只需要用这个插件，就不用做其他配置就可以进行ssr吗？

**Comment by chenshuai2144** [comment]
哪里的不支持呢？你可以提供具体的问题出来，我们会跟进解决

**Comment by phoema** [comment]
pro我换完umi3，打包打不动、浏览器调试也不能断点了，是不是我把pro+umi3用歪了，困扰我好几个月了。
按umi3官网配置也不行。

**Comment by lddhappy** [comment]
同问，这个问题解决了吗，antd pro官网文档直接跳转到umi,umi文档建议给antd pro提PR,死循环了属于是
