### ISSUE TITLE
如何保持登录

### ISSUE THREAD

**Issue by liuwenzhuang** [ant-design/ant-design-pro#734]
Router v3的时候有`onEnter`钩子函数，在需要校验登录状态的地方使用即可，但是现在v4的Router不支持了，需要使用Component的生命周期方法代替，但是如果在`BasicLayout.js`里面做处理，怎么能使其校验登录不成功后跳转到登录页面呢？

**Comment by chenshuai2144** [comment]
你可以试着增加一个loading界面。
![image](https://user-images.githubusercontent.com/8186664/35027427-a212cad8-fb8b-11e7-9986-38c97b4e687f.png)

这种的比较纯粹。也好写。
