### ISSUE TITLE
🐛[BUG]layout-header-color没有起作用

### ISSUE THREAD

**Issue by sapphirezzz** [ant-design/ant-design-pro#7341]
### 🐛 bug 描述

修改了layout-header-color，没有起作用

### 📷 复现步骤

1.yarn create umi
boilerplate type，选择ant-design-pro
Be the first to experience the new umi@3，选择Pro V5

2.config/config.ts文件中，theme添加两个字段：
theme: {
'primary-color': defaultSettings.primaryColor,
'layout-header-color': '#ff5577',
'layout-header-background': '#ffffff',
},

3.yarn && yarn start

### 🏞 期望结果

顶部header标题的字体颜色修改为#ff5577

### 💻 复现代码

https://github.com/sapphirezzz/ProAntDesignForTest

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 Safari
- 开发环境 [e.g. mac OS]

**Comment by sapphirezzz** [comment]
发现 layout 改成 side/top ，顶部右上角的用户名会改变颜色，但是标题都没受影响

**Comment by chenshuai2144** [comment]
来个截图？

我覆盖了这个颜色，所以使用是无效的

**Comment by laozhizi** [comment]
> light

我试过了，确实是这样。

**Comment by laozhizi** [comment]
> navTheme 为 light 时，layout 改为 side/top ，顶部右上角的用户名会改变颜色；其他 layout 用户名不变。
> navTheme 为 dark 时，layout 改为side，顶部右上角的用户名会改变颜色；其他 layout 用户名不变。
> 
> 标题是一直为白色，不受影响。

我试过了，确实如此。

**Comment by chenshuai2144** [comment]
headerTheme | 顶部导航的主题，mix 模式生效 | 'light' \| 'dark' | 'dark'
-- | -- | -- | --




你们可能需要的是这个

**Comment by alianrock** [comment]
所以最新的文档是地址是？
