### ISSUE TITLE
Firefox下a标签的download属性因为Service Worker导致跨域问题，404

### ISSUE THREAD

**Issue by peng0807** [ant-design/ant-design-pro#7345]
### 🧐 问题描述

在Firefox下，点击 <a download .. > 链接不能下载文件，而是显示404，怀疑是Service Worker导致。

### 💻 示例代码

<a href={`.....`} download> 
     <Icon type="download" /> 导出 
</a>

**Comment by chenshuai2144** [comment]
有报错吗？

**Comment by peng0807** [comment]
没有报错，只是跳转到了404页面

**Comment by chenshuai2144** [comment]
关掉 Service Worker 吧
