### ISSUE TITLE
🐛[BUG]部署后，访问页面在一直空白页转圈圈，只有手动强制刷新才能访问

### ISSUE THREAD

**Issue by okwen5566** [ant-design/ant-design-pro#7346]
### 🐛 bug 描述
每次打包部署到linux服务器后，使用的是nginx，访问页面在一直空白页转圈圈，代码没有报错，只有手动强制刷新才能正常访问
  请问这是什么问题 @craxyz  @pmq20 @andriijas 
### © 版本信息

- Ant Design Pro 版本:4.0
- umi 版本
- 浏览器环境：chrome
- 开发环境 ：windows

**Comment by chenshuai2144** [comment]
打开一下 hash 模式，可能你的nginx 缓存了html，导致每次都去找了旧的js文件。

你可以把 html 的缓存关掉，或者使用hash模式的文件

**Comment by okwen5566** [comment]
已经开启hash 模式，nginx 也配置了不缓存，
但是部署上次第一次还是空白
console报了umi.7569acc4.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
手动强制刷新之后就好了，请问这个怎么解决？

**Comment by Asence** [comment]
遇到同样问题 请问最后怎么解决的

**Comment by Asence** [comment]
同样配置了hash nginx也设置了不缓存  但是项目发布以后 跳转页面资源文件还是会404  需要重新去加载资源文件

**Comment by Asence** [comment]
@chenshuai2144 大佬 请教一下解决方法

**Comment by cuiliming666** [comment]
请问怎样能解决呀

**Comment by cicilyxx** [comment]
怎么解决呀
