### ISSUE TITLE
🧐[问题]没有报错，只显示404

### ISSUE THREAD

**Issue by cathy919** [ant-design/ant-design-pro#7347]
### 🧐 问题描述

登录后变成404，再重启都没有登录页面，只有404，浏览器没报错，后台都没报错，只是换了logo图标

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/71301185/93155828-8680b580-f739-11ea-9e5f-57a120baae17.png)

**Comment by chenshuai2144** [comment]
你的页面跳转到404了，一般是你的登录接口返回了http状态码为404导致的
