### ISSUE TITLE
🧐[问题]sos，太难了看完了相关的issue，还是不能解决proxy的问题

### ISSUE THREAD

**Issue by qweasd25** [ant-design/ant-design-pro#7349]
和大多数人一样，代理改了
![image](https://user-images.githubusercontent.com/21007491/93178658-1be66e80-f767-11ea-9ecb-a6f594f086da.png)
但是还是本地地址，因为返回了200.明明是错误的
![image](https://user-images.githubusercontent.com/21007491/93178764-47695900-f767-11ea-9076-369b82cbd1da.png)
然后我运行 yarn dev  yarn start:no-mock 
所有的都一样
也看了文档
是我太笨了 我不会用这个 好难

**Comment by qweasd25** [comment]
**早知惊鸿一场
何必情深一往**

**Comment by qweasd25** [comment]
我只是想在开发环境用后端给的测试数据 为啥这么难啊

**Comment by xiaohuoni** [comment]
https://umijs.org/docs/faq#proxy%E4%BB%A3%E7%90%86%E4%B8%8D%E6%88%90%E5%8A%9F%E6%B2%A1%E6%9C%89%E4%BB%A3%E7%90%86%E5%88%B0%E5%AE%9E%E9%99%85%E5%9C%B0%E5%9D%80

看这个文档能不能帮到你

**Comment by qweasd25** [comment]
> https://umijs.org/docs/faq#proxy%E4%BB%A3%E7%90%86%E4%B8%8D%E6%88%90%E5%8A%9F%E6%B2%A1%E6%9C%89%E4%BB%A3%E7%90%86%E5%88%B0%E5%AE%9E%E9%99%85%E5%9C%B0%E5%9D%80
> 
> 看这个文档能不能帮到你

不是地址问题 就是没有跑通 后端也没有收到🔗

**Comment by Victoriacsl** [comment]
![image](https://user-images.githubusercontent.com/34528097/93185946-9c5d9d00-f770-11ea-9ac0-363102fd1f44.png)

![image](https://user-images.githubusercontent.com/34528097/93186148-df1f7500-f770-11ea-8de3-754fa9b06673.png)

**Comment by Victoriacsl** [comment]
我只用到了dev  所以  我就只改了dev的配置

**Comment by qweasd25** [comment]
莫名其妙好了 别问我为什么

**Comment by qweasd25** [comment]
> 我只用到了dev 所以 我就只改了dev的配置

谢谢

**Comment by qweasd25** [comment]
> https://umijs.org/docs/faq#proxy%E4%BB%A3%E7%90%86%E4%B8%8D%E6%88%90%E5%8A%9F%E6%B2%A1%E6%9C%89%E4%BB%A3%E7%90%86%E5%88%B0%E5%AE%9E%E9%99%85%E5%9C%B0%E5%9D%80
> 
> 看这个文档能不能帮到你

谢谢
