### ISSUE TITLE
V5 版本没有『整体风格设置』这个 drawer 了吗🧐[问题]

### ISSUE THREAD

**Issue by GreatAuk** [ant-design/ant-design-pro#7350]
### 🧐 问题描述

目前初始化差不多是这样的，如果还有这个功能的话， 希望能告知怎么放出来
![image](https://user-images.githubusercontent.com/20253809/93181815-88fc0300-f76b-11ea-88c2-8b1658e6847e.png)

V4 版本是有个命令拉取完整代码的，发布 V5 没有这个命令了
![image](https://user-images.githubusercontent.com/20253809/93184733-2d337900-f76f-11ea-8b13-ad8253188195.png)

**Comment by maytake** [comment]
同问

**Comment by chenshuai2144** [comment]
装个插件 
`yarn add umi-plugin-setting-drawer`

**Comment by laosandegudai** [comment]
出来了吗？我加了也出不来。
