### ISSUE TITLE
为什么打包后每个页面都存在大量重复组件呢🧐[问题]

### ISSUE THREAD

**Issue by hafly** [ant-design/ant-design-pro#7352]
![截图20200916004845059](https://user-images.githubusercontent.com/13634263/93240303-8b377f00-f7b6-11ea-951b-51fb4b140e9b.jpg)
echarts被每个页面重复打包了，我想直接引用echarts，只打包一个公共的文件，而不是每个页面都重复打包，需要怎么配置呢？

**Comment by hafly** [comment]
发布后我发现每个页面加载时间都特别长，打包分析后发现每个页面都在重新打包echarts，怎么让echarts打包成公共包呢，其它页面就不要再打包echarts了

**Comment by chenshuai2144** [comment]
可以看一下 

https://github.com/umijs/plugins/blob/747e0e7b5a4e7b99c253457c2c852c73b1ec7021/packages/preset-ant-design-pro/src/chainWebpack.ts#L17

你可以模仿这个写一下，具体的写法 https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by hafly** [comment]
已解决，非常感谢

**Comment by TnWah** [comment]
v4版本的antd现在不再默认将antd提取了么？
![image](https://user-images.githubusercontent.com/27721311/93838185-5ac27a00-fcbb-11ea-8e4e-c5c787a3ffc9.png)

**Comment by hafly** [comment]
> v4版本的antd现在不再默认将antd提取了么？
> ![image](https://user-images.githubusercontent.com/27721311/93838185-5ac27a00-fcbb-11ea-8e4e-c5c787a3ffc9.png)

默认打包只有两个文件，一个vendors.js一个umi.js，antd打包到一起的

**Comment by TnWah** [comment]
之前版本好像是会把antd打包到umijs中，现在这个没了，要按照上边的配置设置一下，不太明白怎么把这个默认配置关掉了
