### ISSUE TITLE
yarn create umi 没有文档描述的行为，V5 版本怎么得到和官网预览一样的界面

### ISSUE THREAD

**Issue by GreatAuk** [ant-design/ant-design-pro#7354]
`yarn create umi` 创建的是一个比较空的框架，目前希望得到和[官方预览](https://preview.pro.ant.design/dashboard/analysis)一样的内容
***
V4 版本可以通过下面的方式实现，V5 好像没有下面的实现
![image](https://user-images.githubusercontent.com/20253809/93297231-76450500-f823-11ea-92a2-89f7ed46fb4b.png)
***
目前运行 `yarn create umi` 命令的过程是下面这样的（并没有像[文档](https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96)上说的一样，能选择 ts 还是 js 版本，是否下载完整的 blocks）
![image](https://user-images.githubusercontent.com/20253809/93299678-05541c00-f828-11ea-91da-771ef8047fa7.png)
***
通过查看之前的 issue ,有人说可以通过这条命令 fetch blocks, `yarn run pro fetch-blocks --branch=v5`，但下载的过程有下面的错误发生，导致项目无法正常运行
![image](https://user-images.githubusercontent.com/20253809/93300101-c5416900-f828-11ea-8126-bb450fbdd69e.png)
![image](https://user-images.githubusercontent.com/20253809/93300164-e1450a80-f828-11ea-853d-7c8b19342876.png)

**Comment by chenshuai2144** [comment]
v5 还不支持哦。

你可以试试用 

`yarn fetch:blocks --branch v5`

**Comment by GreatAuk** [comment]
@chenshuai2144 想问下有完整代码的仓库吗， 还是说都已经拆分成 block了？
