### ISSUE TITLE
🐛[BUG] Pro v5升级umi、antd到最新版后进入不了主界面了

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7355]
### 🐛 bug 描述

Pro v5升级umi、antd到最新版后进入不了主界面了
现在： umi 3.2.20
             antd 4.6.3
             pro v5

主界面一直转啊转，如下图所示：

![image](https://user-images.githubusercontent.com/51013754/93664050-9af8e100-fa9e-11ea-832c-5b91a88c0b3e.png)

**Comment by chenshuai2144** [comment]
图呢？

**Comment by li515422618** [comment]
更新到v5版本最新代码【9.12日提交】，一直报404，大佬给看看。@chenshuai2144
![image](https://user-images.githubusercontent.com/17846480/93453151-e29b3380-f90b-11ea-9783-915fd46089f3.png)

**Comment by chenshuai2144** [comment]
这个一般是接口挂了 是不是mock没有启动。

**Comment by effapp** [comment]
已经补充了图，代码没有任何的报错，就是一直转，没有加载登录页。

**Comment by effapp** [comment]
不知道什么原因，重新安装依赖n次后，莫名其妙的就正常了。

**Comment by whhlulu** [comment]
我也遇到了，怎么解决？
阿里的东西越来越不讲究了

**Comment by chenshuai2144** [comment]
> 不知道什么原因，重新安装依赖n次后，莫名其妙的就正常了。

建议用 cnpm 火或者 tyarn 之类的东西安装
