### ISSUE TITLE
🧐[问题]请问如何手动触发表格查询并设置查询条件

### ISSUE THREAD

**Issue by KellenHe** [ant-design/ant-design-pro#7356]
### 🧐 问题描述

场景是左侧是颗树，右侧是pro table。通过点击树来对pro table进行查询。

**Comment by chenshuai2144** [comment]
actionRef | Table action 的引用，便于自定义触发 | React.MutableRefObject<FormInstance> \| ((actionRef: ActionType) => void) | -
-- | -- | -- | --

文档在这里，如果有传参的需求，可以是formRef 或者 params props
https://procomponents.ant.design/components/table#protable

**Comment by KellenHe** [comment]
@chenshuai2144 请问有没有示例可以参考下

**Comment by chenshuai2144** [comment]
点进去网站 第一个demo就是

**Comment by KellenHe** [comment]
多谢，ok了。
`            request={(params: any) => {
              params.departmentIds = selectedDepKeys;
              return queryUsers(params);
            }}`
