### ISSUE TITLE
V5会支持多页签功能吗👑 [需求]

### ISSUE THREAD

**Issue by li515422618** [ant-design/ant-design-pro#7357]
### 🥰 需求描述

记得之前有个pinned面板，大家都在讨论多页签，怎么找到不了
目前在用v5来开发公司的后台系统，逻辑比较重，弹出模态框的方式不太能满足使用，期望能有个多页签能力

**Comment by chenshuai2144** [comment]
可以看这个
https://github.com/ant-design/ant-design-pro/issues/220
