### ISSUE TITLE
pro v4 设置环境变量UMI_ENV=dev报错

### ISSUE THREAD

**Issue by wxuonline** [ant-design/ant-design-pro#7358]
在package.json中设置环境变量UMI_ENV=dev后运行报错，是什么问题

`"start": "cross-env UMI_ENV=dev umi dev",`

![1600256866(1)](https://user-images.githubusercontent.com/28921455/93333248-9db4c580-f855-11ea-8a34-254b40c24d4e.jpg)

**Comment by chenshuai2144** [comment]
这个 UMI_ENV 是我们用的，你可以换一个

**Comment by wxuonline** [comment]
@chenshuai2144 
最开始我想在.env.development文件和.env.prduction文件里面添加环境变量以区分开发环境和生产环境配置
![1](https://user-images.githubusercontent.com/28921455/93412669-2e2fec00-f8d0-11ea-87c9-de221640da41.jpg)

但是发现config.js中获取不到.env.development里的环境变量，目前只能获取到.env文件中的变量。个人判断是否是因为未进入开发模式造成？不过设置 --mode development也没有效果。

后面发现UmiJS中可以配置UMI_ENV=dev然后添加config.dev.js和config.pro.js区分多环境配置，现在如果UMI_ENV现在不能用的话，请问下有什么其他的方案？

**Comment by chenshuai2144** [comment]
换个名字就好了 我一直用REACT_APP

**Comment by wxuonline** [comment]
> 换个名字就好了 我一直用REACT_APP

有什么方法能获取到.env.development文件里面的变量么？
如果有很多个变量都在package.json的scripts中设置的话，命令行是否会显的太长

**Comment by chenshuai2144** [comment]
https://segmentfault.com/a/1190000011683741

什么都行

**Comment by kz739925388** [comment]
> 这个 UMI_ENV 是我们用的，你可以换一个

什么意思？谁用的？Umi 官网不就是这么配置的吗？

**Comment by kz739925388** [comment]
> https://segmentfault.com/a/1190000011683741
> 
> 什么都行，你要这么用的

这是在 使用 Umi 改变路由配置

**Comment by kz739925388** [comment]
> 在package.json中设置环境变量UMI_ENV=dev后运行报错，是什么问题
> 
> `"start": "cross-env UMI_ENV=dev umi dev",`
> 
> ![1600256866(1)](https://user-images.githubusercontent.com/28921455/93333248-9db4c580-f855-11ea-8a34-254b40c24d4e.jpg)

最后解决了吗？在线急等。。。

**Comment by chenshuai2144** [comment]
UMI_ENV 不要自己设置

**Comment by kz739925388** [comment]
你看一下 umi 官网：多环境多份配置，里面是这么要求配置的，是我电脑的原因吗？在 window 下就没有问题，新换的 mac pro 就有这个问题，在线急等。。。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2020年12月6日(星期天) 晚上10:39
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;; 
抄送: "用心未来"<739925399@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-pro] pro v4 设置环境变量UMI_ENV=dev报错 (#7358)





 
UMI_ENV 不要自己设置

**Comment by chenshuai2144** [comment]
看到了 ，新家的功能呀, 配置了 UMI_ENV=dev ，要同时存在 `config.dev.js`, 不然会报错。

我建议你用 locale，用内置的，不要用dev 这种特别容易被混淆的

**Comment by kz739925388** [comment]
你在看看，local是本地项目开发build打包不会打包进入的，也就是可以认为自己本地代码演示，线上环境不会存在这些配置





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2020年12月6日 22:53
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt;
抄送: 康小白 <739925399@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-pro] pro v4 设置环境变量UMI_ENV=dev报错 (#7358)





 
看到了 ，新家的功能呀, 配置了 UMI_ENV=dev ，要同时存在 config.dev.js, 不然会报错。
 
我建议你用 locale，用内置的，不要用dev 这种特别容易被混淆的

**Comment by kz739925388** [comment]
local是本地项目开发使用，在build打包时不会打进去，也就是说只做本地演示，UMI_ENV可做多版本区别开发呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2020年12月6日 22:53
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt;
抄送: 康小白 <739925399@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-pro] pro v4 设置环境变量UMI_ENV=dev报错 (#7358)





 
看到了 ，新家的功能呀, 配置了 UMI_ENV=dev ，要同时存在 config.dev.js, 不然会报错。
 
我建议你用 locale，用内置的，不要用dev 这种特别容易被混淆的

**Comment by chenshuai2144** [comment]
你的多版本是什么概念？详细解释一下

**Comment by kz739925388** [comment]
你可以在package.json，中自己加配置UMI_ENV=eflops，打包eflops版本，等等
...



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2020年12月6日 23:07
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt;
抄送: 康小白 <739925399@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-pro] pro v4 设置环境变量UMI_ENV=dev报错 (#7358)





 
你的多版本是什么概念？详细解释一下

**Comment by chenshuai2144** [comment]
可以的，但是用起来还是很麻烦的，前端最好还是到处一份代码

**Comment by kz739925388** [comment]
跑偏了，如果你也用的是Mac pro，你可以试下有没有问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 <notifications@github.com&gt;
发送时间: 2020年12月6日 23:14
收件人: ant-design/ant-design-pro <ant-design-pro@noreply.github.com&gt;
抄送: 康小白 <739925399@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-pro] pro v4 设置环境变量UMI_ENV=dev报错 (#7358)





 
可以的，但是用起来还是很麻烦的，前端最好还是到处一份代码

**Comment by chenshuai2144** [comment]
搞不定去umi问问，他们更加专业
