### ISSUE TITLE
V5里面 app.tsx里面如何使用useState🧐[问题]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/ant-design-pro#7359]
### 🧐 问题描述

V5里面 app.tsx里面如何使用useState

### 💻 示例代码

![image](https://user-images.githubusercontent.com/60868863/93425443-9096e580-f8ec-11ea-9fcf-c9f69a0e1fb2.png)

**Comment by quarkcms** [comment]
@sorrycc @chenshuai2144 大佬帮忙解答一下

**Comment by chenshuai2144** [comment]
不能用的 你只能存在intlvalues里面 你的需求是什么？

**Comment by quarkcms** [comment]
![image](https://user-images.githubusercontent.com/60868863/93435693-5fbeac80-f8fc-11ea-91e1-7786756e1dbd.png)

**Comment by quarkcms** [comment]
以前我解决的办法是，用pro-layout菜单受控，自己控制展开和选中

**Comment by quarkcms** [comment]
@chenshuai2144 有没有好的解决办法？或者说选中这一块儿是不是可以根据鼠标点击的key来判定展开和选中更合理

**Comment by quarkcms** [comment]
现在应该是根据path来判定的对吧，但是path很有可能会出现相同的，只是参数不同；这样就出现了bug

**Comment by chenshuai2144** [comment]
Path不同参数不同就不应该做成菜单的，菜单是一种导航

**Comment by quarkcms** [comment]
额，其实这个需求应该很常见吧；我现在写的系统是这样的，就是前台的路径都一样，只是参数不一样；前端对各种组件进行了封装，后端返回调用组件的类型，前端根据后端返回的数据调用组件。

**Comment by quarkcms** [comment]
类型这样的路径，只是api的参数不一样。
http://localhost:8000/quark/engine?api=admin/dashboard/index&component=table
http://localhost:8000/quark/engine?api=admin/admin/index&component=table

**Comment by quarkcms** [comment]
@chenshuai2144 
或者这里能否可以使用useState，用户自己控制
![image](https://user-images.githubusercontent.com/60868863/93447191-b7611600-f904-11ea-9a5d-17f73a1ea8b5.png)

**Comment by quarkcms** [comment]
@chenshuai2144 帅哥，应该怎么处理？

**Comment by chenshuai2144** [comment]
都不行 这里只是个配置 你需要自己使用layout

**Comment by quarkcms** [comment]
可不可以增加根据鼠标点击的key以及当前的path同时来判定展开和选中的功能，毕竟在实际的开发中相同的path是不可避免的

**Comment by chenshuai2144** [comment]
做一下专门的区分就好了，你可以设置openKeys为false 关闭自动选中

**Comment by quarkcms** [comment]
![image](https://user-images.githubusercontent.com/60868863/93455335-cea50100-f90e-11ea-9a21-0bf286c805be.png)
关闭了，并没有起到作用

**Comment by chenshuai2144** [comment]
@quarkcms   自己实现一下吧，
https://procomponents.ant.design/components/layout
