### ISSUE TITLE
Ant Design Pro format config error

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-pro#736]
修改Login.js之后无法提交
===>原因是代码的格式检查不通过
===>具体原因是import React, {Component} from 'react';
          需要修改为import React, { Component } from 'react';

===>本人编辑器webstorm
          修改建议
          1）默认的Login.js就满足配置的githook检查
          2）修改AntDesignPro  的 Editorconfig配置，达到webstorm可以格式化后满足githook配置的检查标准
          3）修改githook检查

**Comment by chenshuai2144** [comment]
你的意思是我们的esllint 和 webstorm的冲突了吗？

**Comment by macmatilda** [comment]
1）建议默认的代码，都是满足格式化，和eslint要求的
这样就不会出现，我修改Login一行代码，提交的时候要把  不满足eslint的地方都要修改一遍

2）我现在不确定是EditConfig在webStorm下面不生效，还是EditConfig没有配置完整，因为这一块我也不熟。

ps
我刚刚用vs code，格式化了一下，貌似可以解决大部分的eslint报错，

建议总结一个类似最佳实践的编辑器，

我现在修改代码，要进行如下步骤
1）用webStorm处理导入的报错
2）用code格式化代码

**Comment by afc163** [comment]
editorconfig 不可能满足 eslint 的要求格式，建议关闭 webStorm 的自动格式化。
