### ISSUE TITLE
🐛[BUG]renderFormItem自定义組件進行自定义搜索表单出现问题，Request无法获得自定义组件的值

### ISSUE THREAD

**Issue by jackykwandesign** [ant-design/ant-design-pro#7360]
### 🐛 bug 描述
renderFormItem自定义組件進行自定义搜索表单出现问题，Request无法获得自定义组件的值

`onChange={(value: any) => config.onChange(value)}`

_Originally posted by @lqt1990 in https://github.com/ant-design/ant-design-pro/issues/5855#issuecomment-572363467_

### 📷 复现步骤
这个是我自己写的组件，目的是做一个搜寻日期区间的组件
```
import { DatePicker } from 'antd'
import moment,{ Moment } from 'moment';
import React from 'react'

const DateRangePicker = (props:any)=>{
    const {startFromToday,lockTimeToZero} = props
    console.log("props",props)
    function range(start:  number, end: number) {
        const result = [];
        for (let i = start; i < end; i++) {
          result.push(i);
        }
        return result;
      }
      function disabledDate(current: Moment) {
        // Can not select days before today and today
        return current && current < moment().endOf('day');
      }
      function disabledDateTime() {
        return {
          disabledHours: () => range(1, 24),
          disabledMinutes: () => range(1, 60),
          disabledSeconds: () => range(1, 60),
        };
      }
    return (
        <DatePicker.RangePicker  
            allowClear 
            inputReadOnly 
            disabledDate = {startFromToday ? disabledDate : undefined}
            disabledTime = {lockTimeToZero ? disabledDateTime : undefined}
            showNow = {false}
            showTime={{ 
            defaultValue: [moment('00:00:00', 'HH:mm:ss') ,moment('00:00:00', 'HH:mm:ss') ]
            }}
        />
    )
}

export default DateRangePicker
```

如果我是在ProTable组件中直接使用，如下图，是可以获取到值的
``` 
const columns: ProColumns<any>[] = [
{
      title: '賬單創建日',
      dataIndex: 'createAtRange',
      sorter: true,
      hideInTable:true,
      hideInForm: true,
      hideInDescriptions: true,
      renderFormItem: (item, props)=> {
        return (
          // <DateRangePicker {...props}/>
          <DatePicker.RangePicker  
            allowClear 
            inputReadOnly 
            // disabledDate = {disabledDate}
            disabledTime = {disabledDateTime}
            showNow = {false}
            showTime={{ 
              defaultValue: [moment('00:00:00', 'HH:mm:ss') ,moment('00:00:00', 'HH:mm:ss') ]
            }}
          />
        )
      },
      // hideInSearch: true,
    }
]
```

![image](https://user-images.githubusercontent.com/46065771/93433062-e6718a80-f8f8-11ea-9d15-416ffcfe699f.png)

如果先建立组件，再在renderFormItem里面引用，却没拿到值
```  
renderFormItem: (item, props)=> {
        return (
          <DateRangePicker {...props}/>
        )
      },

```
![image](https://user-images.githubusercontent.com/46065771/93433000-d9ed3200-f8f8-11ea-86d3-e29f793999c5.png)

我肯定组件有接受到onChange
![image](https://user-images.githubusercontent.com/46065771/93433194-115bde80-f8f9-11ea-8a81-e9221327629c.png)

但如果我在组件里面加上这一句
`onChange={(value: any) => config.onChange(value)}`

_Originally posted by @lqt1990 in https://github.com/ant-design/ant-design-pro/issues/5855#issuecomment-572363467_

一切都正常了，组件也能传值
![image](https://user-images.githubusercontent.com/46065771/93434616-f5593c80-f8fa-11ea-867e-f7b9dae4719d.png)

![image](https://user-images.githubusercontent.com/46065771/93433508-74e60c00-f8f9-11ea-9fbc-ba7e385107fe.png)

所以是所有自定义组件都需要加上上面的onChange事件吗？

### © 版本信息

- Ant Design Pro 版本: [4.2.1]
- umi 版本: [^3.2.14]
- umi-request:[1.0.8]
- 浏览器环境: [chrome]
- 开发环境 [Ubuntu 18.04 + nest.js]

**Comment by chenshuai2144** [comment]
`<DatePicker.RangePicker  { ...props}>` 你要把 value 和 onChange 附加上去

**Comment by jackykwandesign** [comment]
> `<DatePicker.RangePicker { ...props}>` 你要把 value 和 onChange 附加上去
![image](https://user-images.githubusercontent.com/46065771/93483127-12116680-f933-11ea-80ac-9a98e747a0ef.png)
最後我是這樣放上去了，謝謝

**Comment by qiyulaoshi** [comment]
图裂了 能贴代码吗？  我也遇到select不能传参得得问题
