### ISSUE TITLE
🐛[BUG]没有子路由时，无法生成面包屑

### ISSUE THREAD

**Issue by Joker0824** [ant-design/ant-design-pro#7361]
没有子路由的时候，无法生成面包屑，使用RouteContext获取到的Breadcrumb中的routes为undefined
<img width="1680" alt="Snipaste_2020-09-17_18-04-58" src="https://user-images.githubusercontent.com/26892349/93456635-8ab2fb80-f910-11ea-8a16-c8164f81cd73.png">

**Comment by chenshuai2144** [comment]
是故意这么设计的，必须要长度为 2 以上才显示
