### ISSUE TITLE
🐛[BUG]查询表格，增加默认选中值之后，手动点击其他选项时，无法选中

### ISSUE THREAD

**Issue by go-package-lab** [ant-design/ant-design-pro#7367]
### 🐛 bug 描述

查询表格，增加默认选中值 selectedRowKeys 之后，手动点击其他选项时，无法选中

rowSelection={{
          getCheckboxProps: record => ({
            disabled: record.disabled === true, // Column configuration not to be checked
            //indeterminate: record.name === 'Tom',
            name: record.name,
          }),
          onChange: (_, selectedRows) => setSelectedRows(selectedRows),
          preserveSelectedRowKeys: false,
          selectedRowKeys: [99],

        }}

### 📷 复现步骤
必现

### 🏞 期望结果

可勾选

### © 版本信息

- Ant Design Pro 版本: [v5]
- umi 版本:umi@3.2.20
- 浏览器环境 ：chrome 版本 85.0.4183.102（正式版本）
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
你写起了选中的keys 当然无法更换了.

受控组件必须 value和 onchange 配合  


Antd官网有demo 可以去找下↓
