### ISSUE TITLE
🧐[问题] 怎么动态引用组件

### ISSUE THREAD

**Issue by hafly** [ant-design/ant-design-pro#7369]

**Comment by hafly** [comment]
我想动态引入一个组件，但是引用后一直加载不了，处于loading状态。还有react-loadable也是同样的问题，但是我在react原生项目都能使用。

引用：
const MapChart = () => import('./lib/MapChart');

使用：
<MapChart />

**Comment by chenshuai2144** [comment]
动态？

试试 原生的 react.lazy
