### ISSUE TITLE
🧐[为什么npm或cnpm克隆下来的v5代码跟v5分支代码不一样]

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/ant-design-pro#7370]
### 🧐 问题描述

使用的命令：npm create umi xxx  || cnpm create umi
选择的版本：v5
![image](https://user-images.githubusercontent.com/32796170/93727491-f71e4b00-fbed-11ea-86d8-4732303b2500.png)

![image](https://user-images.githubusercontent.com/32796170/93727468-e372e480-fbed-11ea-8a03-04e754acebc1.png)

**Comment by liganghui** [comment]
大兄弟 ,  开发版本和线上版本代码能一样么...

**Comment by gameruleCEO** [comment]
> 大兄弟 , 开发版本和线上版本代码能一样么...

额....入口函数总该一样吧？

**Comment by chenshuai2144** [comment]
当然不一样了，v5 是滚动根更新的
