### ISSUE TITLE
🧐[问题]请问有谁用umi和pro-layout做的开源例子吗

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7372]
### 🧐 问题描述

请问有谁用umi和pro-layout做的开源例子吗

**Comment by effapp** [comment]
我想在ant pro中用Pro-layout做一个自定义的layout

**Comment by xiexingen** [comment]
https://github.com/wetrial/wetrial-template
算一个抄袭了pro的模板项吧

**Comment by effapp** [comment]
> https://github.com/wetrial/wetrial-template
> 算一个抄袭了pro的模板项吧 ^_^

请问是否包含自定义的layout？

**Comment by xiexingen** [comment]
> > https://github.com/wetrial/wetrial-template
> > 算一个抄袭了pro的模板项吧 ^_^
> 
> 请问是否包含自定义的layout？

自定义layout修改app.ts中的layout就行了呀

**Comment by effapp** [comment]
> > > https://github.com/wetrial/wetrial-template
> > > 算一个抄袭了pro的模板项吧 ^_^
> > 
> > 
> > 请问是否包含自定义的layout？
> 
> 自定义layout修改app.ts中的layout就行了呀

我需要修改左侧菜单加载逻辑，让菜单和路由分离，app.ts中的layout做不到。

**Comment by xiexingen** [comment]
远程加载菜单？

**Comment by effapp** [comment]
> 远程加载菜单？

这只是其中之一，还可以自定义菜单的外观，可以随心在菜单区域增加自定义的内容。
