### ISSUE TITLE
如何解决 Warning 警告

### ISSUE THREAD

**Issue by ysh0552** [ant-design/ant-design-pro#7378]
![QQ截图20200922092505](https://user-images.githubusercontent.com/14260225/93836504-99edcc80-fcb5-11ea-9bd7-397903475c7e.png)

**Comment by zhushenhang** [comment]
这个生命周期方法警告应该是antd pro 写在底层封装了吧，应该要他们改。

**Comment by chenshuai2144** [comment]
按照文档指示操作一下！

**Comment by ysh0552** [comment]
> 按照文档指示操作一下！

哪个文档？

**Comment by chenshuai2144** [comment]
截图上面的那个链接 能点进去
