### ISSUE TITLE
V5如何自定义全局layout？🧐[问题]

### ISSUE THREAD

**Issue by quarkcms** [ant-design/ant-design-pro#7379]
### 🧐 问题描述

如题：V5如何自定义全局layout？

**Comment by quarkcms** [comment]
@chenshuai2144 我现在没有用官方默认的layout，自定义的
`routes: [
    {
      path: '/user',
      layout: false,
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: './user/login',
        },
      ],
    },
    {
      path: '/quark',
      component: '@/layouts/Index',
      routes: [
        {
          path: '/quark/engine',
          component: './Quark/Engine',
        },
      ],
    },
    {
      path: '/',
      redirect: '/quark/engine?api=admin/dashboard/index',
    },
    {
      component: './404',
    },
  ],`
但是有个问题，404这个layout也不存在了，要是能使用自己定义的全局layout，应该怎么弄？

**Comment by chenshuai2144** [comment]
包到最外面 把404也包进去

**Comment by quarkcms** [comment]
![image](https://user-images.githubusercontent.com/60868863/93839399-6fa10c80-fcbf-11ea-9a54-f7c519a8b41f.png)
这样吗？不起作用

**Comment by quarkcms** [comment]
重新启动一下好了
