### ISSUE TITLE
🧐[v5 版本 如何自定义 403 500 页面呢]

### ISSUE THREAD

**Issue by phpmaple** [ant-design/ant-design-pro#7380]
默认可以在路由设置 404 如何自定义 403 500 页面呢, ErrorComponent 这个现在也用不了

**Comment by chenshuai2144** [comment]
也新建一个 403 和 500，然后再reques 报错之后 跳转一下，模仿 404 写就好了

**Comment by phpmaple** [comment]
> 也新建一个 403 和 500，然后再reques 报错之后 跳转一下，模仿 404 写就好了

但是比如配置的路由access不符合就返回 403 页面,这里是不需要服务器返回 403 的, 现在内置的 403 肯定也没有根据请求来判断
