### ISSUE TITLE
PageContainer 链接有问题，或者可以自己手动配置吗？🧐[问题]

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#7384]
### 🚑 其他信息

<img width="486" alt="截屏2020-09-23 下午5 48 49" src="https://user-images.githubusercontent.com/19459174/93996731-2c30c600-fdc5-11ea-852d-24f2c7483e57.png">

我鼠标聚焦在商品管理为啥后面还拼接一样的链接
config.ts加了  antd: {},
  base: 'console',
  publicPath: '/console/',

我本地当前浏览器连接是:  http://location:8000/console/goods/manager

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/7389
