### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by lvzhyt** [ant-design/ant-design-pro#7386]
### 🐛 bug 描述

权限管理 Basiclayout.tsx 中 在浏览器直接输入 url 或刷新页面， 页面可以展现不能跳转403
```
  // get children authority
  const authorized = useMemo(
    () =>
      getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
        authority: undefined,
      },
    [location.pathname],
  );

```
中 menuDataRef.current 为空

### © 版本信息

- Ant Design Pro  master

通过 yarn create umi 办版本中 getMatchMenu在util中有另一种实现 。 可以解决问题。

**Comment by Ligengxin96** [comment]
我也遇到了同样的问题，不过既然有这个issue了我就不开了
@lvzhyt 是否可以把问题描述得清楚点，比如标题简单描述下bug, 比如： ‘路由配置设置的权限无效, 可以通过url直接访问业务页面’
更好的是可以提供复现问题的repo

**Comment by Ligengxin96** [comment]
> ### 🐛 bug 描述
> 权限管理 Basiclayout.tsx 中 在浏览器直接输入 url 或刷新页面， 页面可以展现不能跳转403
> 
> ```
>   // get children authority
>   const authorized = useMemo(
>     () =>
>       getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
>         authority: undefined,
>       },
>     [location.pathname],
>   );
> ```
> 
> 中 menuDataRef.current 为空
> 
> ### © 版本信息
> * Ant Design Pro  master
> 
> 通过 yarn create umi 办版本中 getMatchMenu在util中有另一种实现 。 可以解决问题。

你好 @lvzhyt ， 通过 yarn create umi 办版本中 getMatchMenu在util中有另一种实现。可以发下代码吗？

**Comment by chenshuai2144** [comment]
不写标题直接关
