### ISSUE TITLE
🧐[问题]ts类型写错时，怎样让项目开发环境下把错误信息报在预览页面上

### ISSUE THREAD

**Issue by zhangtang1** [ant-design/ant-design-pro#7387]
### 🧐 问题描述
我写错个ts类型，如，
`export default (): number => (
  <PageContainer>
    <Card>
      123
    </Card>
  </PageContainer>
);
`
我把React.ReactNode改成number，页面仍然可正常运行和编译，只有vscode的报错，

请问，这是正常的吗？
如果我想把报错能实时如react-error-overlay的效果，要怎么做？

最后，感谢adp团队的付出，开发提效喜人~

**Comment by chenshuai2144** [comment]
现在没打开，那个玩意有点费性能，而且ts 报错是不会堵塞开发的。

你可以在 precommit 配置一个 tsc 来拦住。

**Comment by zhangtang1** [comment]
> 现在没打开，那个玩意有点费性能，而且ts 报错是不会堵塞开发的。
> 
> 你可以在 precommit 配置一个 tsc 来拦住。

三克油
