### ISSUE TITLE
PageContainer 点击连接跳转不对🐛[BUG]

### ISSUE THREAD

**Issue by LewinJun** [ant-design/ant-design-pro#7389]
### 🐛 bug 描述

<img width="486" alt="截屏2020-09-23 下午5 48 49" src="https://user-images.githubusercontent.com/19459174/93996731-2c30c600-fdc5-11ea-852d-24f2c7483e57.png">

我鼠标聚焦在商品管理为啥后面还拼接一样的链接
config.ts加了  antd: {},
  base: 'console',
  publicPath: '/console/',

我本地当前浏览器连接是:  http://location:8000/console/goods/manager

### 🏞 期望结果

点击面包屑 连接是 http://location:8000/console/goods/manager而不是http://location:8000/console/goods/manager/console/goods/manager

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境 谷歌最新版
- 开发环境 [e.g. mac OS]

**Comment by wmf508** [comment]
我看你的header栏是和菜单栏分离的并且占满整行，这是v5的默认布局吗？v4是和菜单同宽

**Comment by chenshuai2144** [comment]
@wmf508`  layout=mix`

**Comment by chenshuai2144** [comment]
面包屑会自动拼接个节点的path，

你可以用 `breadcrumbRender` 这个api来自定义一下
