### ISSUE TITLE
路由跳转query传参无作用？

### ISSUE THREAD

**Issue by Chirs-Evans** [ant-design/ant-design-pro#739]
1.在menu.js内配置菜单路由
![image](https://user-images.githubusercontent.com/17941821/35035440-588ba008-fbac-11e7-9450-11b6bba2ea4d.png)
2.页面跳转配置无作用
![image](https://user-images.githubusercontent.com/17941821/35035463-699d5f12-fbac-11e7-981b-21761063c5c3.png)
![image](https://user-images.githubusercontent.com/17941821/35035472-71d3a98e-fbac-11e7-9418-887329f6bf69.png)

**Comment by longzhaobi** [comment]
可以啊！这个是DVA相关的知识：
```
this.props.dispatch(routerRedux.push({
      pathname: '/admin/role',
      query: {
        id:'1234'
      }
}))
```
这里传递参数id:1234,在role的model的subscriptions里：
```
setup({ dispatch, history }) {
  return history.listen(({ pathname, query }) => {
    console.log(query)
    if (pathname === url) {
      dispatch({ type: 'fetch', payload: { current: 1, size: 20, ...query } });
    }
  });
},
```
console.log(query)可以正常打印传过来的参数：
```
Object {id: "1234"}
```

menu里的写法不变：
```
{
    name: '角色管理',
    path: 'role',
    key:'role',
    icon:'trademark'
  }
```

**Comment by wunayou** [comment]
@longzhaobi   hash路由支持这种写法吗？

**Comment by longzhaobi** [comment]
n你可以试试，这个是dva官方的写法，应该都支持吧！

**Comment by ddcat1115** [comment]
1. 在 menu.js 中配置 path 只是给 MenuItem 一个连接地址，你还需要在 router.js 中增加这一条路由 `customer/detail/:id`

2. 
```js
dispatch(routerRedux.push({
  pathname: 'customer/detail',
  query: {
    id: e.key,
  }
}))
```
这样并不能跳转到 `customer/detail/:id`，query 只是这个location携带的一个状态，不会拼到url上，而且rr4 中推荐写法是 [state](https://github.com/ReactTraining/history/blob/v3/docs/Location.md), dva/routerRedux(react-router-redux)执行相同的标准
