### ISSUE TITLE
🧐[问题]protable type=form怎么执行重置

### ISSUE THREAD

**Issue by shuaicloud** [ant-design/ant-design-pro#7390]
### 🧐 问题描述
定义protable type=form
执行actionRef.current.reset() 无效

### 💻 示例代码

比如：
` const formRef = useRef();`
 `const actionRef = useRef<ActionType>();`

`<ProTable
  type="form"
  columns={columns}
  formRef={formRef}
  actionRef={actionRef}
/>`

**Comment by chenshuai2144** [comment]
`formRef.current.reset()`
