### ISSUE TITLE
🧐[问题] V5 版本还支持 dva 吗？

### ISSUE THREAD

**Issue by jing-wu** [ant-design/ant-design-pro#7393]
### 🧐 问题描述
V5 版本还支持 dva 吗？

依赖中看到已经引入了 `@umijs/preset-react` 插件集，但是 `.umi` 目录下没有自动生成 `plugin-dva` 目录。

请大神指教

**Comment by chenshuai2144** [comment]
支持，但是不会默认添加，如果要使用自己建议 models 文件夹，并且新加一个 dva model 才能打开并且生效
