### ISSUE TITLE
[BUG]🐛当具有三级菜单时，点击收起菜单报错

### ISSUE THREAD

**Issue by cai-zhuo** [ant-design/ant-design-pro#7396]
### 🐛 bug 描述
在点击三级菜单后，收起菜单，会报错。或者收起菜单再打开，点击该路由的上一级菜单，会报错。

### 📷 复现步骤
启动流程：
1. yarn create umi
2. yarn
3. yarn fetch:blocks
4. yarn start
界面交互：
1. 点击菜单列表页
2. 点击菜单搜索列表
3. 点击菜单搜索列表（文章）
接下来有两种可能，一个是个人项目，一个是新项目fetch:blocks以后

(1) 收起菜单。（会报错----fetch:blocks） 
      - Pro Layout "@ant-design/pro-layout": "^6.0.0"

(2) 收起菜单再打开，点击菜单搜索列表（文章）（会报错----个人项目）
      - Pro Layout  "@ant-design/pro-layout": "^6.4.8",

### © 版本信息
- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![42921601011931_ pic_hd](https://user-images.githubusercontent.com/44321355/94236080-32e34880-ff3f-11ea-8958-036bf7ecfcc6.jpg)
![42931601011958_ pic_hd](https://user-images.githubusercontent.com/44321355/94236090-3676cf80-ff3f-11ea-95b9-eb79135b83f3.jpg)

**Comment by chenshuai2144** [comment]
看起来是像是antd的某个bug，你试着重新安装一下依赖

**Comment by xrkffgg** [comment]
可以到 ant-design 里提一个  https://new-issue.ant.design/
