### ISSUE TITLE
🐛[BUG]antd pro v5的菜单点第一个显示正常，换一个菜单点就报错了

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7397]
### 🐛 bug 描述

antd pro v5的菜单点第一个显示正常，换一个菜单点就报错了

### 📷 复现步骤

antd pro v5的菜单点第一个显示正常，换一个菜单点就报错了

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本： 3.2.22
- 浏览器环境: chrome
- 开发环境 : win10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51013754/94237612-b56d0780-ff41-11ea-9140-f57e0d90d4e8.png)

![image](https://user-images.githubusercontent.com/51013754/94238512-13e6b580-ff43-11ea-8430-f2262620ebac.png)

**Comment by chenshuai2144** [comment]
你在菜单上绑了什么方法，这个是方法调用错误导致的

**Comment by effapp** [comment]
菜单上我没有绑定任何方法，用menuDataRender进行自定义菜单。

**Comment by xiaohuoni** [comment]
给复现demo吧，猜不到问题。

**Comment by effapp** [comment]
终于莫名其妙的把这个问题解决了，原来是某个页面里面的一个组件有错误导致，那个组件的错误没有任何显示，这个错误居然莫名其妙的就让pro v5 报了如题的错误，从错误提示看完全没有关联。有没有什么办法，让组件的错误影响范围仅局限在组件范围内，不要这种无限制的蔓延？

**Comment by effapp** [comment]
终于莫名其妙的把这个问题解决了，原来是某个页面里面的一个组件有错误导致，那个组件的错误没有任何显示，这个错误居然莫名其妙的就让pro v5 报了如题的错误，从错误提示看完全没有关联。有没有什么办法，让组件的错误影响范围仅局限在组件范围内，不要这种无限制的蔓延？
