### ISSUE TITLE
如何停止路由跳转后页面状态重新加载（路由跳转后保留页面状态）

### ISSUE THREAD

**Issue by zys555** [ant-design/ant-design-pro#7398]
每次跳转路由后都会刷新页面的状态，重置掉之前的选择，在ant design pro中如何保存之前选择的状态呢？

react有个插件叫做react-keeper，可以做到，但是不知道如何在ant design pro中使用

**Comment by chenshuai2144** [comment]
暂时是不支持的，可以去umi的社区问问。
https://umijs.org/
