### ISSUE TITLE
🧐[问题]Pro v5 如何添加动态路由？

### ISSUE THREAD

**Issue by kevin0713** [ant-design/ant-design-pro#7399]
### 🧐 Pro V5 中如何添加动态路由？

Pro V5官网文档说明 layout 组件中有patchMenus 接口,但是组件加载方式component: require('@/extraRoutes/foo').default,并没有生效，如何才能加载组件？

### 💻 示例代码

/ src/app.ts
export const layout = {
  patchMenus: (menus, initialInfo) => {
    return [
      ...menus,
      {
        path: '/sss',
       component: require('@/extraRoutes/foo').default
      },
    ];
  },
};

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13919688/94353903-9e94f500-00a8-11eb-9ca7-58d5aa48795f.png)

**Comment by chenshuai2144** [comment]
不支持动态路由， 只支持动态菜单

**Comment by Mis-tian** [comment]
1、app.ts 入口文件中使用render、patchRoutes 方法去动态修改routes ，此处方法的执行时机几乎在app.ts中为最高优先级。
有一种场景是在登入后根据登陆太拿菜单数据渲染菜单。此时已经错过以上提到的方法的执行时机 也只会在初始化时加载执行一次。
2、通过patchMenus、menuDataRender等方法实际上只能支持到menu菜单并且access插件会失效，因为只是menus相关的处理方法
