### ISSUE TITLE
fastclick库导致手机上点击Radio.Button组件很不灵敏

### ISSUE THREAD

**Issue by bravecat** [ant-design/ant-design-pro#740]
示例：https://preview.pro.ant.design/#/dashboard/analysis
![img_0187](https://user-images.githubusercontent.com/2279074/35036662-fceec76c-fbaf-11e7-9529-785c5dd4b085.PNG)

**Comment by chenshuai2144** [comment]
fastclick好尴尬。。。 他就是为了解决300毫秒延时，更快的响应存在的

**Comment by chenshuai2144** [comment]
是不是在某些情况下需要忽略掉fastclick的功能。。
@bravecat ？

**Comment by bravecat** [comment]
@chenshuai2144 https://github.com/ftlabs/fastclick 的readme上说：
> Note: As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application. Consider carefully whether you really need to use it.

**Comment by chenshuai2144** [comment]
过时了呀！！！我的mix2 还是很流畅的

**Comment by chenshuai2144** [comment]
@afc163 我测试了一下红米手机也不需要这个库了。是不是没有意义了？

**Comment by chenshuai2144** [comment]
看来影响不大，先关了
