### ISSUE TITLE
ant design pro 里面使用想自己的fetch 请示

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#7400]
各位老师，
我在ant design pro 页面里面使用一个从postman 生成的 一段fetch 请求。出来下面的错误。

这段fetch的请求代码，我放在原生的react项目里面，是可以跑，没有问题的。
不知道是怎么个回事。
还请指点下。

![image](https://user-images.githubusercontent.com/32530210/94355261-59c38b00-00b5-11eb-8728-9fa26cc5b948.png)

![image](https://user-images.githubusercontent.com/32530210/94355251-41ec0700-00b5-11eb-8431-b839ec5af8e6.png)

**Comment by chenshuai2144** [comment]
404了, 原生的也不可能跑起来，你应该是在另外一个项目里配置了 proxy，搬过来就好了

**Comment by xyzabc0004** [comment]
@chenshuai2144 
好的，谢谢！
我发觉我范了一个错误。我是直接在前端调用了阿里云上的API请求，用了proxy。

前端应该还是调用自己的API，自己的API再访问阿里云上的API。
不知道你们 搞法是不是也这样。
