### ISSUE TITLE
👑 [需求]V5安装完整组件fetch:blocks报错

### ISSUE THREAD

**Issue by luxiaojian2016** [ant-design/ant-design-pro#7401]
### 🥰 需求描述
V5安装完整组件fetch:blocks报错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23330131/94357053-fa22ab00-00c7-11eb-8e2e-4f45c12241ea.png)

**Comment by chenshuai2144** [comment]
没有这个脚本了，直接用 yarn  create umi  拉取全部。

**Comment by luxiaojian2016** [comment]
使用yarn create umi 只有两个组组件安装啦，和官方预览的不一样
![image](https://user-images.githubusercontent.com/23330131/94401940-eba6c300-019d-11eb-80cd-a0901cf9d44a.png)
