### ISSUE TITLE
v4版本的切换亮色主题为什么就这样了？配置是直接拷贝粘贴过去的！

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design-pro#7402]
![image](https://user-images.githubusercontent.com/44257305/94357332-9cdc2900-00ca-11eb-8715-3ac6647a8867.png)

这是复制过去的配置：
![image](https://user-images.githubusercontent.com/44257305/94357335-b7160700-00ca-11eb-9448-d47dbd84c51f.png)

**Comment by chenshuai2144** [comment]
你是不是增加了 umi-plugin-theme 的插件？

**Comment by glk-hll** [comment]
问题已经解决了。蟹蟹
