### ISSUE TITLE
项目无法热更新

### ISSUE THREAD

**Issue by 521guyu** [ant-design/ant-design-pro#7404]
### 🧐 问题描述
项目无法热更新，有的文件（config目录）可以触发控制台变化但不编译。每次保存都会触发一句 debug [change]  文件路径，但只有config目录才触发，其他pages下则无任何反应，也不报错，也不重新编译。想要看到变化必须每次start一下，但是项目好几十个组件

### 💻 示例代码
[https://img-ask.csdn.net/upload/202009/25/1601015188_514477.png](截图地址)

我试过删除node_moudels下的.cache目录还是不起作用
### 🚑 其他信息
antd-pro版本：2.x
umi                : 2.8.7
node              :12.18.3

**Comment by chenshuai2144** [comment]
清空一下所有的缓存。顺便给个复现地址

**Comment by DunDunDunAbandon** [comment]
我也遇到这个问题

**Comment by vs0533** [comment]
我也遇到这个问题 系统是macos 发现只要是新建文件 热更新均失效

**Comment by pyfs** [comment]
V5 版本在 Macos 下也是这样；

node: v12.20.0

**Comment by 521guyu** [comment]
> 我也遇到这个问题

你可以尝试把项目复制到c盘目录看看

**Comment by 521guyu** [comment]
> 我也遇到这个问题 系统是macos 发现只要是新建文件 热更新均失效

你可以试试把项目移动到c盘试试

**Comment by lishaoh** [comment]
问题解决了吗？我也遇到了

**Comment by 521guyu** [comment]
> 问题解决了吗？我也遇到了

https://blog.csdn.net/weixin_44058725/article/details/108885581 你看看这个看对你有没有帮助
