### ISSUE TITLE
👑 [需求]遇到一个需求，把伸缩按钮放到上面去怎么实现呢？如图

### ISSUE THREAD

**Issue by Pythonchao** [ant-design/ant-design-pro#7406]
![12](https://user-images.githubusercontent.com/40911444/94433723-54586480-01cb-11eb-9267-800968e0dfe1.png)

**Comment by 521guyu** [comment]
defaultSetting里把layout设置成topmenu

**Comment by Pythonchao** [comment]
> defaultSetting里把layout设置成topmenu

这好像是把菜单全部放上面去了，  需求是：把伸缩按钮放到上面

**Comment by chenshuai2144** [comment]
关掉官方的按钮，自己实现一个呗。

collapsed | 控制菜单的收起和展开 | boolean | -
-- | -- | -- | --
onCollapse | 菜单的折叠收起事件 | (collapsed: boolean) => void | -
