### ISSUE TITLE
🧐[问题]ant-design-pro v5 怎么修改logo呢

### ISSUE THREAD

**Issue by zhangdeheng** [ant-design/ant-design-pro#7407]
![image](https://user-images.githubusercontent.com/27886302/94507149-af2ca300-0241-11eb-8ba7-e3e383fab85a.png)

登录页面的logo可以修改，这个地方的改不了

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/94510088-7cd27400-0248-11eb-9cc3-4b59d58ff92d.png)

**Comment by maytake** [comment]
![image](https://user-images.githubusercontent.com/13763352/115838353-2e86fb80-a44c-11eb-9675-7c3faaf3c02a.png)
这个路径是不是有问题，为什么logo显示不出来

**Comment by chenshuai2144** [comment]
public 目录
此目录下所有文件会被 copy 到输出路径。也就是项目的根目录

所以你应该 ` logo: "/logo.png"`
