### ISSUE TITLE
🧐[问题]登录界面使用键盘回车事件在登录请求中依旧可以进行操作

### ISSUE THREAD

**Issue by wangly19** [ant-design/ant-design-pro#7409]
### 🧐 问题描述

您好，我不清楚我的疑问是否是一个BUG，它并不影响正常的工作，但在我看来是一个比较不合理的问题，登录界面在使用键盘事件进行用户登录时，回车键依旧是可以生效的，意味着在短时间内只要用户按的足够快，那么请求数量是一个不合理性的状态。它看起来非常消耗资源。

Tip：如果算是一个BUG，可以尝试进行更改。

### 💻 示例代码

未提供正确实例

### 🚑 其他信息
network接口：
![ant warning](https://user-images.githubusercontent.com/45115006/94539518-e7e76f00-0277-11eb-9308-abcfdbc5802e.png)

**Comment by chenshuai2144** [comment]
fixed
