### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#741]
pro升到1.0 npm start 控制台中没有报错，但浏览器中出现的是项目的目录结构

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/.webpackrc#L16-L18

检查这里。

**Comment by TigerBill2016** [comment]
我这里是没有问题的，我特意改错npm start控制台报错

**Comment by TigerBill2016** [comment]
问题现象是: npm start 控制台中没报错, 浏览器中 页面标题是  listing directory, 页面内容是项目目录结构

**Comment by TigerBill2016** [comment]
貌似发展问题了 : 我把 publicPath由“/”改成“./”就出现这问题了

**Comment by chenshuai2144** [comment]
你这样写只支持hash目录了
