### ISSUE TITLE
🐛[BUG]Protable中的columns，设置了initialValue，在protable中request未能生效

### ISSUE THREAD

**Issue by zczc1984** [ant-design/ant-design-pro#7411]
### 🐛 bug 描述

Protable需要指定columns，columns是一个数组，可以设置initialValue，经过bug修复后，目前控件已可以获得初始值，但是request首次时，无法将initialValue值传递过去，必须手工再按一次查询。

另外columns里还有formItemProps，在formItemProps中也可以设置initialValue，这里感觉有重复的情况，且好像有时候会不生效。

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/339

**Comment by zhuchaowe** [comment]
目前控件已可以获得初始值，但是request首次时，无法将initialValue值传递过去，必须手工再按一次查询。 ant-design/pro-table @2.9.15 问题依然存在

**Comment by chenshuai2144** [comment]
initialValue 是怎么写的，看了下测试用例，功能没问题。initialValue 是不支持异步设置的哦

**Comment by lql670520** [comment]
我手动触发请求能解决这个问题：manualRequest={true}
