### ISSUE TITLE
🧐[问题]如何用微信开放平台扫码登录替换帐号登录？

### ISSUE THREAD

**Issue by yuzifu** [ant-design/ant-design-pro#7412]
尝试用4.2.1建立一个后台管理网站应用，准备使用微信开放平台扫码登录替换掉帐号登录。在npm网站上搜索到了一个组件react-wxlogin，安装后使用WxLogin组件替换掉src/pages/user/login/index.tsx里的LoginForm，但编译报错说未发现react-wxlogin。

```
import WxLogin from 'react-wxlogin';
...
<div className={styles.main}>
  <WxLogin appid='xxxxxx' scope='xxxxxxxx' redirect_uri='xxxxxxxxx' />
</div>
...
```

我在网上也没有搜索到在ant design pro里整合微信开放平台扫码登录的例子，只找到了一些react里整合的例子，但是这些例子都是直接在render()函数里使用的，在user/login组件里没有这个函数。

哪位可以帮忙给出一些例子吗？谢谢！

**Comment by chenshuai2144** [comment]
这个的确没有，你有兴趣搞个pr吗？做个插件也是极好的
