### ISSUE TITLE
菜单栏在后端根据权限设置后，请问怎么让前端刷新后菜单栏能即时生效

### ISSUE THREAD

**Issue by okwen5566** [ant-design/ant-design-pro#7414]
菜单栏在后端根据权限设置后，请问怎么让前端刷新后菜单栏能即时生效

**Comment by chenshuai2144** [comment]
当然是reload了 没有任何副作用

**Comment by zhilianbi520** [comment]
> 当然是刷新整个网页了 没有任何副作用

刷新整个网页的话会清除model中存储的状态吧？那这样的话，是不是只能把那些状态存储到本地存储中了？

**Comment by chenshuai2144** [comment]
那就写个loading，如果loading为true 就把整个layout 解除挂载掉

**Comment by zhilianbi520** [comment]
> 那就写个loading，如果loading为true 就把整个layout 解除挂载掉

好嘞，多谢～！

**Comment by Gzbox** [comment]
> > 那就写个loading，如果loading为true就把整个layout解除挂载掉
> 
> 好嘞，多谢〜！
没太理解，在何处写这个loading,能指点下不？  谢谢 @zhilianbi520

**Comment by chenshuai2144** [comment]
用 layout 加个的 warp
