### ISSUE TITLE
🐛[BUG] Pro layout Localization Problem, globalHeader

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#7417]
### 🐛 bug 描述
Ant Design Pro V5

Although the English language is selected, why does it write in chinese?
![prob](https://user-images.githubusercontent.com/6988989/94720869-adf09880-035d-11eb-89ec-7b7e4a0944ef.PNG)

Another problem pro table localization problem.
When I change the localization set to english good work but while set to turkish lang not work.

![problem](https://user-images.githubusercontent.com/6988989/94720940-c791e000-035d-11eb-9463-7d26bcde04d1.PNG)

![local](https://user-images.githubusercontent.com/6988989/94721219-38d19300-035e-11eb-8fcb-05ef14fee62b.PNG)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
this is hardcode 
https://github.com/ant-design/ant-design-pro/blob/02af3f18621e5b1500497d2a51ccae6e4f0ace5c/src/components/RightContent/index.tsx#L55

you can rename it

**Comment by xXAvoraXx** [comment]
Is it possible to manage this content from the language folder?
