### ISSUE TITLE
v5 是放弃了么， 我看Git仓库删除这个branch 了

### ISSUE THREAD

**Issue by andy136240860** [ant-design/ant-design-pro#7418]
RT， 一直在等V5更新， 然后更新项目代码， 因为开发中发现还是有不少小问题没解决， 今天突然发现这个分支被删了，因为给客户的交付项目用的就是v5， 如果后续不维护了对项目影响蛮大的。

目前我应该怎么做， 整体再退回迁移到v4么， 给个建议？

**Comment by kaoding** [comment]
操作失误
