### ISSUE TITLE
🧐[问题]v5通过menuDataRender传递菜单结构时，页面无法显示的疑问

### ISSUE THREAD

**Issue by aspirantzhang** [ant-design/ant-design-pro#7420]
### 🧐 问题描述

v5版本通过menuDataRender传递菜单结构时，菜单显示正常，但页面无法显示。

### 💻 示例代码

重现
[https://codesandbox.io/s/antdprov5-menudatarender-4vd58?file=/src/app.tsx](https://codesandbox.io/s/antdprov5-menudatarender-4vd58?file=/src/app.tsx)

直接根据今天的v5版本fork的，去掉了登录判断后，做了两步操作：
1. config/config.ts中route部分注释掉了
2. src/app.tsx中添加了一个变量newMenu，然后把原route部分通过`menuDataRender: () => newMenu`传给layout。

### 🚑 现象

点击菜单项后，welcome页面正常。
但原本的[二级管理页]、[查询表格]均无法显示。
请看一下这部分应该是怎么回事？

![001.png](https://i.loli.net/2020/10/06/e4GRadvFQp5iCwN.png)

**Comment by chenshuai2144** [comment]
你把 路由删掉了当然不行了，把路由加回去

**Comment by aspirantzhang** [comment]
我明白了，路由是路由，菜单是菜单。没有路由配置，菜单虽然显示出来，也是不好使的。
菜单会根据path去找路由。

路由：
```
    {
      path: '/basic-list/:page*',
      component: './BasicList',
    },
```
菜单：
```
    {
      name: 'admin-list',
      icon: 'icon-table',
      path: '/basic-list/backend/admins',
    },
```

**Comment by zplzpl** [comment]
后端学习前端，这种设计是什么缘由？从menu与router的属性结构看，好像都是MenuItemData?
为什么注释了就没有不能生效
