### ISSUE TITLE
🐛[BUG]部署后，打开页面后一直转圈圈

### ISSUE THREAD

**Issue by okwen5566** [ant-design/ant-design-pro#7421]
已经开启hash 模式，nginx 也配置了不缓存，
但是部署后打开页面空白，一直转圈圈加载中，
console报了umi.7569acc4.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)错误，
手动强制刷新之后就好了，请问这个怎么解决？

**Comment by chenshuai2144** [comment]
可以打开 hash，这个是因为缓存导致的
https://umijs.org/config#hash
