### ISSUE TITLE
🐛[BUG] pro-table 国际化 不生效

### ISSUE THREAD

**Issue by pentyh** [ant-design/ant-design-pro#7422]
### 🐛 bug 描述

"@ant-design/pro-table": "^2.9.1"

ProTable 国际化 不生效

createIntl('ko_KR', koKRLocale); 添加了 韩语资源

用 IntlProvider 或 ConfigProvider 包裹 ProTable 没有效果

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个可重现的 repo

**Comment by pentyh** [comment]
https://codesandbox.io/s/interesting-torvalds-6z22y?file=/App.tsx

修改 语言资源 搜索控件的 placeholder 一直是中文的 

请解决

**Comment by chenshuai2144** [comment]
@pentyh  更新最新版本
