### ISSUE TITLE
@antv/l7-react 这个依赖包

### ISSUE THREAD

**Issue by cleverwo** [ant-design/ant-design-pro#7424]
# 问题描述
antv/17-react 依赖包下不下来
These dependencies were not found:

* @antv/l7 in ./node_modules/@antv/l7-react/es/component/Marker.js, ./node_modules/@antv/l7-react/es/component/Popup.js and 7 others
* @antv/l7-maps in ./node_modules/@antv/l7-react/es/component/AMapScene.js, ./node_modules/@antv/l7-react/es/component/MapboxScene.js and 1 other

To install them, you can run: npm install --save @antv/l7 @antv/l7-maps

### 💻 示例代码

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/@antv%2f17-react - Not found
npm ERR! 404
npm ERR! 404  '@antv/17-react@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program\nodejs\node_cache\_logs\2020-10-07T08_16_09_927Z-debug.log

切换 淘宝镜像也不行，这个包咋整

**Comment by cleverwo** [comment]
顶顶顶

**Comment by yangtianfu01** [comment]
我也碰到了这个问题, 不知道是哪一步错了

**Comment by yangtianfu01** [comment]
> 顶顶顶

我觉得你应该补充node版本, 电脑系统, 以及安装的选项, 要不他们定位问题会麻烦的

**Comment by lzxue** [comment]
如 @yangtianfu01  回复，后面会在package.json 增加 l7 和l7-map依赖

**Comment by cleverwo** [comment]
> 如 @yangtianfu01 回复，后面会在package.json 增加 l7 和l7-map依赖
默认就有这俩依赖，下不下来，找不到资源，这个怎么弄？

**Comment by yangtianfu01** [comment]
> > 如 @yangtianfu01 回复，后面会在package.json 增加 l7 和l7-map依赖
> > 默认就有这俩依赖，下不下来，找不到资源，这个怎么弄？

未更新前的`package.json`是不会有这两个依赖的, 你的日志里面有一行是依赖包在npm仓库找不到(可能是依赖版本不对), 建议全删除掉, 重新创建和安装.
我本地的node是v12的版本

**Comment by chenshuai2144** [comment]
模仿一下这个 pr
https://github.com/ant-design/pro-blocks/pull/294

**Comment by cleverwo** [comment]
ok，解决了，感谢
