### ISSUE TITLE
🐛[BUG]pro v5的布局不正常，在左边有一块留白，左边不能对齐到边

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7426]
### 🐛 bug 描述

pro v5的布局不正常，在左边有一块留白，左边不能对齐到边

### 🏞 期望结果

左边不要有留白

### © 版本信息

- Ant Design Pro 版本: [v5]
- umi 版本 [3.2.22]
- 浏览器环境 [ Chrome ]
- 开发环境 [ vs code]
-pro-layout [ 6.5.0]
-pro-table [ 2.9.1 ]

### 🚑 其他信息
1、菜单栏展开状态时出现的左侧留白
![image](https://user-images.githubusercontent.com/51013754/95419659-a6884b00-096c-11eb-894a-d81267c64c5f.png)
2、菜单栏收缩状态时出现的左侧留白
![image](https://user-images.githubusercontent.com/51013754/95419837-f8c96c00-096c-11eb-8a9c-9527e8129c8a.png)
3、F12状态下的留白
![image](https://user-images.githubusercontent.com/51013754/95420169-9fae0800-096d-11eb-8a28-9c0a8c987ffc.png)

**Comment by aspirantzhang** [comment]
这个现象我遇到过一次，随后发现是我多余的引用了`import 'antd/dist/antd.css';`

**Comment by effapp** [comment]
确实是有个组件引用了import 'antd/dist/antd.css'; ，删除这一句后布局就正常了，奇怪的是出现这个问题的页面并没有使用这个组件。

谢谢！

> 这个现象我遇到过一次，随后发现是我多余的引用了`import 'antd/dist/antd.css';`
