### ISSUE TITLE
👑 [BUG] V5 不能使用的 layout 如何自定 500 403 400 页面

### ISSUE THREAD

**Issue by phpmaple** [ant-design/ant-design-pro#7428]
默认实现了页面, 没有发现可以修改页面组件的地方了, 老版本是可以的
已经没有这个了, 不希望直接通过 request 捕获来达到页面, 比如配置的路由没有权限直接就到自定义的 403 组件
```
ErrorComponent: (e: any) => {
    console.log(e);
}
```

**Comment by chenshuai2144** [comment]
在 app.tsx 中有个这个

```
/**
 * 异常处理程序
 */
const errorHandler = (error: ResponseError) => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};

export const request: RequestConfig = {
  errorHandler,
};

```

**Comment by phpmaple** [comment]
> 在 app.tsx 中有个这个
> 
> ```
> /**
>  * 异常处理程序
>  */
> const errorHandler = (error: ResponseError) => {
>   const { response } = error;
>   if (response && response.status) {
>     const errorText = codeMessage[response.status] || response.statusText;
>     const { status, url } = response;
> 
>     notification.error({
>       message: `请求错误 ${status}: ${url}`,
>       description: errorText,
>     });
>   }
> 
>   if (!response) {
>     notification.error({
>       description: '您的网络发生异常，无法连接服务器',
>       message: '网络异常',
>     });
>   }
>   throw error;
> };
> 
> export const request: RequestConfig = {
>   errorHandler,
> };
> ```

想要在路由那边跳转到默认的 403 那个页面修改 403 的页面, 不是请求返回之后

**Comment by HQ1363** [comment]
这个是解决了，还是没解决啊？？？  看着不像解决了
