### ISSUE TITLE
🧐[问题]token失效以后重新登录，再次回到原页面dispatch不执行

### ISSUE THREAD

**Issue by 1995hjh** [ant-design/ant-design-pro#7431]
### 🧐 token失效以后重新登录，再次回到原页面dispatch不执行

如图所示，在request.js对token失效捕捉，一旦监听倒token失效，则强制退到登录页面。
但是，再次重新登录以后，该页面的dispatch不触发，需要f5刷新页面才可以执行，请问怎么解决？

![2020-10-09_133654](https://user-images.githubusercontent.com/12559428/95548067-e582d300-0a36-11eb-9ce8-48fff3510fbc.png)
![2020-10-09_133858](https://user-images.githubusercontent.com/12559428/95548070-e74c9680-0a36-11eb-945a-f46ff42df20c.png)

**Comment by chenshuai2144** [comment]
看这里，用法没什么变化，都是因为 dva throw error 导致的

https://github.com/ant-design/ant-design-pro/issues/2772
