### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by zhangtang1** [ant-design/ant-design-pro#7432]
### 🧐 问题描述
我用antdp起了项目，但我想在项目中尝试formily，需要import 'antd/dist/antd.less'，但样式多少有点问题，我想请问下框架本身有在哪里引入过antd.less吗

**Comment by aspirantzhang** [comment]
我在antd pro中使用了一下formilyjs，看起来不用额外引用antd的css，组件显示状态正常。 有时候显示错位，命令行停掉项目以后，再重启就好了。

**Comment by chenshuai2144** [comment]
标题不写直接关
