### ISSUE TITLE
🧐[问题] 使用 ProLayout 中的 menuDataRender 属性从服务端加载菜单，如何给整个状态加 loading 呢？或是有其他解决方案？

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design-pro#7433]
### 🧐 问题描述
从服务端加载菜单如果没有loading（或者更好的解决方案）且网络不好的话，很长一段时间菜单栏都是空白的，请问怎么解决？

**Comment by chenshuai2144** [comment]
layout 是有一个 loading的属性的，你可以使用 loading 属性

**Comment by glk-hll** [comment]
好的 我先试试，感谢

**Comment by daifuyang** [comment]
不行，js我尝试了！第一次进来还是空白！代码热更新确实出来了！感觉还是有bug！谢谢

**Comment by chenshuai2144** [comment]
写了个文档
https://beta-pro.ant.design/docs/advanced-menu-cn
