### ISSUE TITLE
🧐[问题]umi-request中多个request请求在response拦截器抛出错误时只能捕获第一个错误

### ISSUE THREAD

**Issue by wehuss** [ant-design/ant-design-pro#7437]
### 🧐 问题描述

多个request请求在response拦截器抛出错误时只能捕获第一个错误

### 💻 示例代码

**响应拦截器**
`
const responseInterceptors = [
  async (response: Response) => {
    const data:ResponseData = await response.clone().json();
    if(data.SUCCESS==="0"){
      if(typeof data.DATA === 'string'){
        throw new Error(data.DATA);
      }else {
        throw new Error('未知错误');
      }
    }
    console.log('data',data,'response',response);
    return response;
  }
];
`
**错误处理程序**
`
const errorHandler = (error: ResponseError) => {
  const { response, message } = error;
  console.log('response',response,'error',error.message);
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  if(message&&typeof message=== 'string'&&message!=='http error'){
    notification.error({
      message: `操作失败`,
      description: message,
    });
  }

  if (!response&&!message) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};
`
**请求程序(演示)**
`
const handleUpdate = async (params: UserInfo) => {
  const hide = message.loading('正在更新');
  try {
    updateUser(params);
    updateUser(params);
    await updateUser(params);
    hide();

    message.success('更新成功');
    return true;
  } catch (error) {
    hide();
    message.error('更新失败请重试！');
    return false;
  }
};
`

### 🚑 其他信息

响应拦截器
![image](https://user-images.githubusercontent.com/48681136/95650399-1128ba80-0b16-11eb-86f2-d4951dae5855.png)
错误处理程序
![image](https://user-images.githubusercontent.com/48681136/95650408-1be34f80-0b16-11eb-9249-7bfe148c6245.png)
进行多个请求
![image](https://user-images.githubusercontent.com/48681136/95650474-83999a80-0b16-11eb-86e2-92473598d3ec.png)
错误没有被捕获
![image](https://user-images.githubusercontent.com/48681136/95650542-d4a98e80-0b16-11eb-9b68-1fd5e2575852.png)

请问一下为什么会出现这种情况

**Comment by wehuss** [comment]
issue格式因为代码中有"`"出现了问题🤣

**Comment by xrkffgg** [comment]
你自己可以修改一下

用 三个 ```

**Comment by chenshuai2144** [comment]
用了await 最好 try catch 一下，尤其是网络请求

**Comment by wehuss** [comment]
> 用了await最好试试catch一下，尤其是网络请求

在拦截器中不抛出错误的话无法进入umi-request的错误处理程序吧

**Comment by chenshuai2144** [comment]
umi-request 的错误处理里面 try catch 一下呢，这个看起来是第一个错误把堆栈直接干掉了
