### ISSUE TITLE
🧐怎么在V5 json 转菜单

### ISSUE THREAD

**Issue by langengel** [ant-design/ant-design-pro#7438]
### 🧐 问题描述

我想从服务端请求菜单数据  但是没有图标  或者请给我一个正确的方式 难道需要我自己结合antd 改造吗？那么pro 的意义是什么？  很多常用的demo都没有  很难下手  

### 💻 
import React from 'react';
import { BasicLayoutProps, MenuDataItem, Settings as LayoutSettings } from '@ant-design/pro-layout';
import { notification } from 'antd';
import { history, RequestConfig } from 'umi';
import RightContent from '@/components/RightContent';
import Footer from '@/components/Footer';
import { ResponseError } from 'umi-request';
import { queryCurrent } from './services/user';
import defaultSettings from '../config/defaultSettings';

export async function getInitialState(): Promise<{
  settings?: LayoutSettings;
  currentUser?: API.CurrentUser;
  fetchUserInfo: () => Promise<API.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    const token = localStorage.getItem('access_token')
    if(!token){
      return undefined
    }
    try {
      const currentUser = await queryCurrent();
      return currentUser;
    } catch (error) {
      history.push('/user/login');
    }
    return undefined;
  };
  // 如果是登录页面，不执行
  if (history.location.pathname !== '/user/login') {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: defaultSettings,
    };
  }
  return {
    fetchUserInfo,
    settings: defaultSettings,
  };
}

export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps => {
  let AdminMenu: MenuDataItem[] = []
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { currentUser } = initialState;
      const { location } = history;
      // 如果没有登录，重定向到 login
      if (!currentUser?.userid && location.pathname !== '/user/login') {
        history.push('/user/login');
      }
    },
    menuDataRender:((menuData) =>{
      console.log(menuData);
      AdminMenu = [
        {
          path: '/welcome',
          name: 'welcome',
          icon: 'smile',
          component: './Welcome',
        },
      ]

      return AdminMenu
    }),
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};

**Comment by chenshuai2144** [comment]
试试 `menuDataRender`, 这个 api 可以搞定

https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu

**Comment by langengel** [comment]
刚刚接触antdesginpro  很多时候是对资源的了解不够彻底  非常感谢
