### ISSUE TITLE
按钮冒泡事件处理

### ISSUE THREAD

**Issue by LKCheng** [ant-design/ant-design-pro#744]
![f8628bdb-cae6-47bd-a33f-28ba32558dfc](https://user-images.githubusercontent.com/10054789/35049115-f91c7e48-fbd9-11e7-8b2b-26b5881184f6.png)
这里的点击保存后，会继续触发编辑的按钮

**Comment by wunayou** [comment]
这是因为那一个人 写的时侯用了 onblur  事件

**Comment by chenshuai2144** [comment]
chrome  mac 没有发现问题。 我该怎么重现！？

**Comment by chenshuai2144** [comment]
重现了。我去排查一下

**Comment by chenshuai2144** [comment]
已经修复了，不是因为事件冒泡是因为onblur被触发了

**Comment by LKCheng** [comment]
增加了 Debounce 感觉更多bug了，第一次点击编辑，然后点击取消后还会再次进入编辑状态。
上面的选择框选择后会触发到下面table的编辑
![222](https://user-images.githubusercontent.com/10054789/35135575-12e9a1b2-fd19-11e7-9505-5227193a2532.png)

**Comment by chenshuai2144** [comment]
我排查一下！ 不行得写个专门的关闭方法了

**Comment by chenshuai2144** [comment]
@LKCheng  换了个粗暴的方法。 这次绝对不会了
