### ISSUE TITLE
🐛[BUG] V5 如何在服务器端返回 401 退出登录呢?

### ISSUE THREAD

**Issue by phpmaple** [ant-design/ant-design-pro#7440]

**Comment by chenshuai2144** [comment]
app.tsx 文件的行数
```tsx
/**
 * 异常处理程序
 */
const errorHandler = (error: ResponseError) => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};

export const request: RequestConfig = {
  errorHandler,
};

```

可以在这里做判断

**Comment by phpmaple** [comment]
> app.tsx 文件的行数
> 
> ```tsx
> /**
>  * 异常处理程序
>  */
> const errorHandler = (error: ResponseError) => {
>   const { response } = error;
>   if (response && response.status) {
>     const errorText = codeMessage[response.status] || response.statusText;
>     const { status, url } = response;
> 
>     notification.error({
>       message: `请求错误 ${status}: ${url}`,
>       description: errorText,
>     });
>   }
> 
>   if (!response) {
>     notification.error({
>       description: '您的网络发生异常，无法连接服务器',
>       message: '网络异常',
>     });
>   }
>   throw error;
> };
> 
> export const request: RequestConfig = {
>   errorHandler,
> };
> ```
> 
> 可以在这里做判断

没有解决如何退出登录 退出登录V5 要使用initstate 使currentUser 为 null, 但是 useModel 是 hooks 在这里不可以调用
