### ISSUE TITLE
🧐[问题]SettingDrawer在生产环境显示

### ISSUE THREAD

**Issue by hafly** [ant-design/ant-design-pro#7441]
### 🧐 问题描述

SettingDrawer这个提示的“配置栏只在开发环境用于预览，生产环境不会展现”，但是我打包发布后的页面还是会显示配置栏啊。
怎样在生产模式不显示配置栏，而且所有设置要生效呢？

**Comment by chenshuai2144** [comment]
人肉删掉，我们是不推荐使，但是不强制的。

如果要生效可以把配置 copy 到 defaultSetting 里面

**Comment by hafly** [comment]
哦，但是删除了SettingDrawer，通过地址栏修改参数就不行了，能不能不删除，只是隐藏那个图标呢

**Comment by hafly** [comment]
> 人肉删掉，我们是不推荐使，但是不强制的。
> 
> 如果要生效可以把配置 copy 到 defaultSetting 里面

哦，但是删除了SettingDrawer，通过地址栏修改参数就不行了，能不能不删除，只是隐藏那个图标呢

**Comment by xixichensh** [comment]
问的就是不删除怎么通过配置关闭，这东西还影响菜单栏的服务器读取，搞啥呀
