### ISSUE TITLE
🧐[帮助！！！]关于嵌套路由或三级路由的问题

### ISSUE THREAD

**Issue by gameruleCEO** [ant-design/ant-design-pro#7443]
### 🧐 问题描述
需求：有一个表格列表页面，操作里有【查看详情】。如何配置【查看详情】的路由？
![image](https://user-images.githubusercontent.com/32796170/95710633-a604f280-0c93-11eb-9c3d-e6fdffdc7a77.png)
就比如这样形式的三级路由。但是页面上并不是我想要的结果。这样会导致二级路由里嵌套三级路由，并且必须在二级路由里写props.children才能获取到三级路由页面。
我想要的是，点击【查看详情】后跳转到三级路由页面。并且菜单中不包含此三级路由。
当然，这也会涉及到多级路由，比如四级路由，五级路由。
感谢各位的帮助[抱拳了]

**Comment by chenshuai2144** [comment]
打平不就好了吗？

**Comment by gameruleCEO** [comment]
> 打平不就好了吗？

您的意思是？可否细说一下

**Comment by MarxZhou** [comment]
> > 打平不就好了吗？
> 
> 您的意思是？可否细说一下

他的意思应该是将三级路由升级为二级路由，并进行隐藏，但是这样一来又会产生左侧菜单的选中状态问题。
比如说我进入了三级路由，但是却失去了二级路由菜单的选中状态。我目前还没有找到好方法去控制左侧菜单的展示状态。

我觉得应该增加一个配置项，用来指定被隐藏的路由对应哪个二级菜单或者一级菜单的选中状态。

在2.x版本中，这个菜单选中状态问题并不存在，不是很理解官方为什么这样更改。

**Comment by x13872140520** [comment]
> 打平不就好了吗？

感觉这样不是很自然，而且一般二级菜单本来就很多了，同放在一个层级，如果每一个二级菜单都对应一个表单页，详情页，那么路由数量就直接x3了

**Comment by MarxZhou** [comment]
> > 打平不就好了吗？
> 
> 感觉这样不是很自然，而且一般二级菜单本来就很多了，同放在一个层级，如果每一个二级菜单都对应一个表单页，详情页，那么路由数量就直接x3了

打平确实是一个不错的选择，但是我目前还没有找到合适和方式解决之后产生的菜单选中状态问题。
通常而言，类似编辑的页面如果放在二级菜单的话，需要将其隐藏。
但是这时如果进入编辑页面，左侧的菜单则会出现没有任何一项被选中的情况。

这里我觉得应该会有配置项能够处理，但是我目前还未找到。

**Comment by grace618** [comment]
这个问题为什么关闭了，框架根本没解决啊

**Comment by grace618** [comment]
@chenshuai2144 这个问题没解决啊，查看详情的页面放在三级路由根本出不来

**Comment by sibaiabis** [comment]
> 这个问题为什么关闭了，框架根本没解决啊

这个在新版本里解决了呀，我在自己的demo项目里可以实现隐藏查看详情路由的呀

**Comment by fei199225** [comment]
> > 这个问题为什么关闭了，框架根本没解决啊
> 
> 这个在新版本里解决了呀，我在自己的demo项目里可以实现隐藏查看详情路由的呀

请问最后是用的什么处理方案啊？

**Comment by sibaiabis** [comment]
新版里有一些hide啥啥的隐藏配置。设置一下就好了

发自iPhone12 pro max

**Comment by jerryyxu** [comment]
？？

**Comment by sibaiabis** [comment]
> ？？

嗯？

**Comment by xiaofeisss** [comment]
解决了吗  楼主，用你的这种思路?  二级路由和三级路由都有comoonent的情况，三级不显示，怎么解决？

**Comment by 275712722** [comment]
跳转不到三级路由页面怎么解决
