### ISSUE TITLE
ant design pro 重定向问题🧐[问题]

### ISSUE THREAD

**Issue by web-cang** [ant-design/ant-design-pro#7445]
### 🧐 问题描述

怎样根据权限设置，每个项权限的人登录时，登录后进入的页面不同，萌新，斗胆问一下，就像下面的系统管理员进入/welcome
普通管理员进入/user/list,开始想在login.js中判断，却无从下手

### 💻 示例代码
{
      path: '/',
      // redirect: `${agent}`,
      redirect:'/user/list',
    },
{
      path: '/welcome',
      name: '首页',
      icon: 'HomeOutlined',
      component: './welcome/Welcome',
      access: 'adminRouteFilter',
    },
    {
      path:'/user',
      
      icon:'user',
      routes:[
        {
          path:'/user/list',
          name:'用户列表',
          component:'./user/UserList'
        },
      ]
    },

**Comment by yutingzhao1991** [comment]
有一个方案是可以在 access.ts 里面判断然后做跳转。 https://umijs.org/plugins/plugin-access
