### ISSUE TITLE
🐛[BUG] 在 getInitialState`初始化数据时间比较长的情况下，会导致页面空白，直至初始化完成

### ISSUE THREAD

**Issue by amin168** [ant-design/ant-design-pro#7446]
### 🐛 bug 描述

在 `getInitialState` 初始化数据时间比较长的情况下，会导致页面空白，直至初始化完成

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

**Comment by xiaohuoni** [comment]
很正常吧？

**Comment by amin168** [comment]
有个 `loading` 会好点吧，但是目前这个情况，不知道在那里加 `loading`

**Comment by chenshuai2144** [comment]
getInitialState 最好是必要数据，不要什么都放进去。loading 应该默认加一下

**Comment by amin168** [comment]
@chenshuai2144 对啊，只是用来加载初始化数据，就是下面的代码不知道在哪里加 loading

```
export async function getInitialState():  {
  const config = await initAppConfig() // 这里会导致白屏，但是不知道如何加 loading
  return {
    appConfig: config
  }
}
```

**Comment by chenshuai2144** [comment]
@amin168 在最外面的包个 layout，然后做一下判断，没有 appConfig 的时候展示 loading


https://beta-pro.ant.design/docs/layout-cn#%E8%87%AA%E5%AE%9A%E4%B9%89-layout
