### ISSUE TITLE
点击退出登陆，跳转到登陆页面，提示无法对已卸载的组件进行状态更新

### ISSUE THREAD

**Issue by Json314** [ant-design/ant-design-pro#7447]
错误提示信息如下：
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
![image](https://user-images.githubusercontent.com/24929232/95747448-0ebb9180-0ccb-11eb-95f9-66411b847ecc.png)

**Comment by chenshuai2144** [comment]
可能有些数据没有更新完，要去排查一下到底是哪个逻辑导致的

**Comment by Json314** [comment]
> 可能有些数据没有更新完，要去排查一下到底是哪个逻辑导致的

不是数据没有更新的缘故。只要是由SecurityLayout布局变为其他（UserLayout或者自定义的404），都会出现此错误。如果将退出登陆的路由跳转延迟100ms执行，就不会有错误了。怀疑是SecurityLayout某个组件文件中，useEffect里面return的函数中，修改了state???找了半天还是没找到原因。请大神指点一二

**Comment by fenglijunnb** [comment]
@chenshuai2144 @Json314 请问一下这个问题解决了吗啊大神

**Comment by Json314** [comment]
> @chenshuai2144 @Json314 请问一下这个问题解决了吗啊大神

目前这样解决，退出登陆，延迟跳转，/src/models/login.js
![image](https://user-images.githubusercontent.com/24929232/97843004-85c0d480-1d23-11eb-8ae2-d84e96619762.png)
不是完美的解决方式

**Comment by fenglijunnb** [comment]
@Json314 确实不报错了，没办法，先凑合用吧，这个至少没有warning就很不错了，官方又不给予正确的答案

**Comment by easy261925** [comment]
同问

**Comment by chenshuai2144** [comment]
看了看好像只能 setTimeOut 了

**Comment by codedart2018** [comment]
2021-07-31 复现问题，登陆页面我进进行了网络请求。但我退出的时候发现请求了两次。导至报错。真的好过分！

**Comment by Daudxu** [comment]
窝尼玛，怎么总报这个错
