### ISSUE TITLE
项目构建 放到linux nginx服务器后 提示404 api/fake_chart_data错误

### ISSUE THREAD

**Issue by yunakeji** [ant-design/ant-design-pro#745]
我现在还没有做后端， 想着先用mock，但一直提示找不到错误。 本地运行正常

**Comment by chenshuai2144** [comment]
nginx服务器配置了反向代理了？？

**Comment by yunakeji** [comment]
是的， 是nginx配置错误了么？

**Comment by longzhaobi** [comment]
mock出来的数据，打包后还会有效果？

**Comment by yunakeji** [comment]
打包后不能用mock数据吗？？

**Comment by chenshuai2144** [comment]
@yunakeji 我得理解是这样的。你部署了正式版本。然后重新启动了一个antd.pro.
nginx 访问 antd.pro 服务是这样吗？

**Comment by yunakeji** [comment]
@chenshuai2144 我是直接将html、css、js文件上传到服务器 /home/www/test 下， 配置nginx

server {
    listen       80;
    server_name  test.bgck.com;

    index index.html
    root /home/www/test;
    location ~ .* {
        root /home/www/test;
        expires      7d;
    }
}

**Comment by chenshuai2144** [comment]
去学习一下基本的运维知识吧。。这样是不可能能用的

**Comment by yunakeji** [comment]
好的，谢谢， 我在去看看nginx

**Comment by chenshuai2144** [comment]
不是nginx的问题。 前后端分离。去看看是怎么分离的x
