### ISSUE TITLE
🧐[问题]V5设置navTheme: 'realDark'无效

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#7450]
### 🧐 问题描述

我们想换成全黑的主题色，另外自己再定制一些组件样式css。不需要动态切换
通过umi插件，打开了antd pro v5的settingdrawer，设置realDark全黑，这时候界面上生效，但把拷贝出来的配置放在代码里面运行不生效

### 💻 示例代码
```
    "umi-plugin-antd-theme": "^2.1.2",
    "umi-plugin-setting-drawer": "^1.0.3"
```
生成的代码，覆盖默认的defaultSettings.ts里面相应的内容
```
{
  "navTheme": "realDark",
  "primaryColor": "#1890ff",
  "layout": "top",
  "contentWidth": "Fluid",
  "fixedHeader": false,
  "fixSiderbar": true,
  "menu": {
    "locale": true
  },
  "title": "demo",
  "pwa": false,
  "iconfontUrl": "/iconfont/iconfont.js"
} 
```
```
import defaultSettings from '../config/defaultSettings';
import { BasicLayoutProps, SettingDrawerProps, Settings as LayoutSettings } from '@ant-design/pro-layout';
export async function getInitialState(): Promise<{
  currentUser?: API.CurrentUser;
  settings?: LayoutSettings;
  settingDrawer?: SettingDrawerProps;
}> {

  return {
    settings: defaultSettings,
    settingDrawer: {
      hideCopyButton: true,
      hideHintAlert: true
    }
  };
}
```

**Comment by chenshuai2144** [comment]
里面有个行为，要点击才能出发，如果要设置黑色不切换可以试试
在 config.ts 里面配置
theme:{
 dart:true
}

**Comment by quicklearning123** [comment]
> 里面有个行为，要点击才能出发，如果要设置黑色不切换可以试试
> 在 config.ts 里面配置
> theme:{
> dart:true
> }

dart,dark都试了
报错 Validate config "theme" failed, "dark" must be a string

**Comment by quicklearning123** [comment]
> > 里面有个行为，要点击才能出发，如果要设置黑色不切换可以试试
> > 在 config.ts 里面配置
> > theme:{
> > dart:true
> > }
> 
> dart,dark都试了
> 报错 Validate config "theme" failed, "dark" must be a string


theme: {
    ...darkTheme,
    // 'primary-color': defaultSettings.primaryColor,
  },
这样能起效果。如果根据切换的theme，需要更新自定义组件的样式，需要怎么做呢，有最佳实践文档吗？

**Comment by chenshuai2144** [comment]
这个 js 估计无法做到了，你需要全局做个 context

**Comment by imgoby** [comment]
> 里面有个行为，要点击才能出发，如果要设置黑色不切换可以试试
> 在 config.ts 里面配置
> theme:{
> dart:true
> }

单词写错了吧。dark 不是dart

应是这样吧：
  antd: {
    dark: true,
    compact: true,
  },
