### ISSUE TITLE
🧐[问题]打包后想本地打开dist里面的index.html，要配置些什么呢

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/ant-design-pro#7451]
### 🧐 问题描述
打包后想本地打开dist里面的index.html，要配置些什么呢

**Comment by xiaohuoni** [comment]
```
yarn global add serve
cd dist && serve
```

**Comment by CiciIvory** [comment]
> ```
> yarn global add serve
> cd dist && serve
> ```

electron 无法使用build打包出来的index.html 有什么解决方案么

**Comment by xiaohuoni** [comment]
[publicpath](https://umijs.org/config#publicpath) 设置 ./

**Comment by CiciIvory** [comment]
> [publicpath](https://umijs.org/config#publicpath) 设置 ./

设置了但是依然没有效果诶

**Comment by xiaohuoni** [comment]
那要看错误了。

**Comment by CiciIvory** [comment]
> 那要看错误了。

方便加qq私聊么：904889229

**Comment by CiciIvory** [comment]
> 那要看错误了。
方便看一下
我的config如下
`export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true
  },
  locale: {
    default: 'zh-CN',
    antd: true,
    baseNavigator: true
  },
  targets: {
    ie: 11
  },
  routes: pageRoutes,
  theme: {
    'primary-color': defaultSettings.primaryColor
  },
  title: false,
  ignoreMomentLocale: true,
  proxy: {},
  manifest: {
    basePath: '/'
  },
  publicPath: './',
  // 新增
  lessLoader: {
    javascriptEnabled: true,
  },
})`
但是 会闪退
![Uploading 20201013_171018.gif…]()

**Comment by xiaohuoni** [comment]
提供个复现demo吧。
