### ISSUE TITLE
🧐[问题]现在需求是把web项目打包成桌面应用，有对应的解决策略么，electron一直配不好啊！！

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/ant-design-pro#7452]
### 🧐 问题描述

现在需求是把web项目打包成桌面应用，有对应的解决策略么，electron一直配不好啊！！

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/ant-design-pro/issues/1874

**Comment by WangJM001** [comment]
基于Umi的Electron框架，一行命令(pnpm create poros)生成Electron应用，快速开发、打包， 集成了各种功能，方便好用，感兴趣的可以看下，欢迎Star，项目还在不断迭代中。
https://github.com/porosjs/poros
