### ISSUE TITLE
通过ProTable自动生成代码新建记录时，怎么指定字段的默认值？例如，在有下拉框时，怎么指定默认自动选中的条目

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design-pro#7455]
写标题

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/7444#issuecomment-707525188_

**Comment by fengnex** [comment]
ProTable在自动创建的新增数据的form中，怎么指定自动默认值？
例如文本框，在form打开时，能自动已经填好设置的默认值，
对于下拉框，指定默认值的选项自动选中，而不是全部空着，去等用户输入。
目前Pro自动的功能示例中，没看到相关内容。

**Comment by mapleflow** [comment]
1 defaultData={[stepFormValues]}
2 formRef.setFieldsValue
3 form={{ initialValues:{} }}
4 valueEnum

默认选中的，必须在已有集合内。
