### ISSUE TITLE
🐛[BUG] 退出登录后重新进入会出现样式错位(官方预览版v4也有一样问题)

### ISSUE THREAD

**Issue by wj0101** [ant-design/ant-design-pro#7457]
### 🐛 bug 描述

退出登录后重新进入会出现样式错位

### 📷 复现步骤

先退出登入，再重新登录就会复现

### 🏞 期望结果

样式正常

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13463968/95839671-dcb33980-0d75-11eb-9c26-de585a776038.png)

**Comment by ineedacatmiao** [comment]
确实有，正在考虑用不用antd pro呢

**Comment by chenshuai2144** [comment]
是 umi 的问题，打包了多份的 css，导致样式被重叠了

**Comment by 0-Captain** [comment]
我用umi也遇见了这个问题，我发现是因为在一个页面同时使用了ant-design-pro的layout和ant-design的layout导致其中的一个样式ant-pro-sider-fixed的优先级降低了。下图一是正常样式
![image](https://user-images.githubusercontent.com/36297071/96371882-98b99d80-1196-11eb-906f-7045463582c2.png)
![image](https://user-images.githubusercontent.com/36297071/96371902-b424a880-1196-11eb-9e32-4844adb38560.png)
