### ISSUE TITLE
🧐[问题] v4版本的 ant-design-pro 中为什么点击任一菜单后刷新浏览器，就自动类似返回上一个路由的页面了？

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design-pro#7458]
### 下面是我的 config.js 中的一部分：
![image](https://user-images.githubusercontent.com/44257305/95838503-6b26bb80-0d74-11eb-9113-c7fa157525b1.png)

下面是出现的问题：（去某个路由，刷新之后会自动返回上一个路由的页面）
![Bug](https://user-images.githubusercontent.com/44257305/95839779-feacbc00-0d75-11eb-886f-bc734928e5c0.gif)

请问是出了什么问题？是 UMI 的什么配置影响的吗？

**Comment by chenshuai2144** [comment]
这个是umi的一个bug，应该很久之前就修好了

**Comment by glk-hll** [comment]
那我这个是咋回事嘞？一直没有主要到这个事情，最近才发现的。官方的演示上面没有这个问题。

**Comment by glk-hll** [comment]
@chenshuai2144 对了 在v4 版本中项目上线后的console.log() 一类的代码有没有什么统一处理掉的方法？

**Comment by chenshuai2144** [comment]
> 在v4 版本中项目上线后的console.log() 一类的代码有没有什么统一处理掉的方法？

再 webpack 中设置一下，webpack 有相关的插件

**Comment by glk-hll** [comment]
请问可以说的具体点吗？我没有用过这类的插件。 @chenshuai2144

**Comment by huntdream** [comment]
> 请问可以说的具体点吗？我没有用过这类的插件。 @chenshuai2144

可以用这个：[babel-plugin-transform-remove-console](https://www.npmjs.com/package/babel-plugin-transform-remove-console)

**Comment by glk-hll** [comment]
@huntdream 好的 我试试！

**Comment by glk-hll** [comment]
@huntdream 请问你知道为什么我一刷新页面就会返回上一个页面吗？就是我提交的这个问题，这个问题一直还存在。不知道哪里出了问题~^~

**Comment by glk-hll** [comment]
@chenshuai2144 你说这是Umi的一个bug，是不是我的Umijs 版本不对，这是版本：
![image](https://user-images.githubusercontent.com/44257305/96069232-50695980-0ed0-11eb-8583-f0c9d6f76f4a.png)

**Comment by chenshuai2144** [comment]
升级到最新就好了

**Comment by glk-hll** [comment]
@chenshuai2144 好的，蟹蟹。
