### ISSUE TITLE
🐛[BUG] pro-table的ellipsis效果未生效

### ISSUE THREAD

**Issue by guogeer** [ant-design/ant-design-pro#7459]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/5010851/95843511-5e0ccb00-0d7a-11eb-8a58-8be4867da3a4.png)
pro-table的ellipsis效果未生效，如上图所示
### 🏞 期望结果

单元格内容根据宽度自动省略

### 💻 复现代码

    {
      title: '强更地址',
      dataIndex: 'url',
      hideInSearch: true,
      ellipsis: true,
      width: 100,
    },
    {
      title: '自定义参数',
      dataIndex: 'config',
      hideInSearch: true,
      ellipsis: true,
      width: 100,
    },
### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.0
- umi 版本：3.2.23
- 浏览器环境：版本 86.0.4240.75（正式版本） (x86_64)
- 开发环境：Mac 10.15.6,  VS Code

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/479
