### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by 521guyu** [ant-design/ant-design-pro#7460]
### 🧐 问题描述

1.antd-pro v4，routes的icon属性可以使用本地图片吗（格式是jpg）？比如xxx.jpg，我看了一下antd自定义图标必须是svg格式。

💻 示例代码
{ path: '/SystemStartUp', name: '系统开工', icon: 'table', //这里可以不用antd图标吗，我们的都是图片jpg格式的 component: './SystemStartUp', title: 'ddd', meta: false },

**Comment by chenshuai2144** [comment]
写标题
