### ISSUE TITLE
👑 [需求] 可不可以更新一个“多标签” 的功能

### ISSUE THREAD

**Issue by GDLong** [ant-design/ant-design-pro#7464]
### 🥰 需求描述

多标签切换在后台管理中还是挺常见的，我自己做了一个总感觉 不太完美，希望官方可以出一个多标签切换的功能！！

**Comment by pkaq** [comment]
#220 这个问题已经问烂了   真是又臭又长的一个issue

**Comment by fainle** [comment]
不管你问多少次 就是不会提供

**Comment by xiaofuliang** [comment]
是啊，能否提供一个官方的啊

**Comment by chenshuai2144** [comment]
没有完美的 keep live方案之前是不会提供的

**Comment by Fengly0503** [comment]
自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs

**Comment by pkaq** [comment]
> 自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs

哥们 你是把 #220 所有相关的issue都刷了一遍回复么 ？ github不是这么用的

**Comment by Fengly0503** [comment]
> > 自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs
> 
> 哥们 你是把 #220 所有相关的issue都刷了一遍回复么 ？ github不是这么用的

这块了解比较少，见笑 😀

**Comment by pkaq** [comment]
> > > 自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs
> > 
> > 
> > 哥们 你是把 #220 所有相关的issue都刷了一遍回复么 ？ github不是这么用的
> 
> 这块了解比较少，见笑 😀

酒香不怕巷子深 表搞得跟逛国内论坛一样刷榜吧

**Comment by pxim** [comment]
同求
