### ISSUE TITLE
👑 [需求]pro-list 如何手动刷新, 使用了request 属性, 如果使用 datasource 自己刷新数据源, 如何获取当前页数

### ISSUE THREAD

**Issue by phpmaple** [ant-design/ant-design-pro#7466]

**Comment by mapleflow** [comment]
问题解决了记得整理下解决方案，帮助他人。

**Comment by ashen114** [comment]
#参考proTable的方法即可：[https://procomponents.ant.design/components/table#actionref-手动触发](https://procomponents.ant.design/components/table#actionref-手动触发)

```js
ref.current?.reload()
```
