### ISSUE TITLE
🐛[BUG]permission控制中，每次刷新页面都store.getters.roles.length === 0

### ISSUE THREAD

**Issue by BrettKang** [ant-design/ant-design-pro#7467]
### 🐛 bug 描述

\src\permission.js
这个权限路由页面，每次判断roles集合都为空

if (store.getters.roles.length === 0) {
         console.log('store.getters.roles:' + JSON.stringify(store.getters.roles))
        //**************这里每次都会打印出空array[]
        store
          .dispatch('GetInfo')
          .then(res => {

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个代码不是 pro 里面的吧

**Comment by BrettKang** [comment]
> 这个代码不是 pro 里面的吧

是的啊，源码位置不是都给了吗？src目录下的permission.js第28行

**Comment by BrettKang** [comment]
> 这个代码不是 pro 里面的吧

不好意思，是ant design vue pro的
