### ISSUE TITLE
🧐[问题] ant V4 build 之后如何去除 console 相关的代码？求详解！急急急

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design-pro#7469]
### 🧐 问题描述
查看其它问题说是在 umi config.js 的chainWebpack 属性上配置，具体点改怎么配置？

**Comment by chenshuai2144** [comment]
https://juejin.im/post/6844904186501398542
https://github.com/umijs/umi/issues/1111

搜一下就能找到的。

**Comment by glk-hll** [comment]
@chenshuai2144 像这一类的代码我不知道在哪加上？
```
 new webpack.optimize.UglifyJsPlugin({
//删除注释
output:{
 comments:false
},
//删除console 和 debugger  删除警告
compress:{
warnings:false,
drop_debugger:true,
drop_console:true
}

```
我只在 Umi 的文档中看到了这些：
![image](https://user-images.githubusercontent.com/44257305/96244949-5b5be100-0fd9-11eb-8291-ceb43205e98a.png)

麻烦告知正确的修改建议。蟹蟹

**Comment by serenespring** [comment]
config.js 文件加上
  uglifyJSOptions(opts) {
    opts.uglifyOptions.compress.drop_console = true;
    return opts;
  },
