### ISSUE TITLE
🐛[BUG] 动态路由下使用在线代码生成报错: 只有 pages 或 page 目录下的页面才能插入资产

### ISSUE THREAD

**Issue by gy0801151351** [ant-design/ant-design-pro#7470]
### 🐛 bug 描述

项目需要使用后台配置的菜单来生成前端的动态路由, 
路由中的component属性的值的形式是: 
dynamic({ loader: () => import(`@/pages${componentPath}`), loading: LoadingComponent})
使用这种路由, 页面加载没有问题. 但是使用浏览器的在线页面编辑功能就报如下错误:

BlockItem error Error: 只有 pages 或 page 目录下的页面才能插入资产
    at n (eval at fa (umi.e85a7b7d.js:127), <anonymous>:16438:52610)
eval @ VM62715:16438
c @ VM62715:16438
eval @ VM62715:16438
forEach.e.<computed> @ VM62715:16438
b @ VM62715:16438
l @ VM62715:16438
Promise.then (async)
b @ VM62715:16438
o @ VM62715:16438
Promise.then (async)
b @ VM62715:16438
o @ VM62715:16438
eval @ VM62715:16438
eval @ VM62715:16438
eval @ VM62715:16438
eval @ VM62715:16438
c @ VM62715:16438
eval @ VM62715:16438
forEach.e.<computed> @ VM62715:16438
b @ VM62715:16438
o @ VM62715:16438
eval @ VM62715:16438
eval @ VM62715:16438
eval @ VM62715:16438
M @ antd.min.js:23
ki @ react-dom.production.min.js:176
ji @ react-dom.production.min.js:13
mi @ react-dom.production.min.js:13
lf @ react-dom.production.min.js:13
wi @ react-dom.production.min.js:187
Kd @ react-dom.production.min.js:32
pc @ react-dom.production.min.js:32
Wf @ react-dom.production.min.js:34
(anonymous) @ react-dom.production.min.js:236
uf @ react-dom.production.min.js:15
Qd @ react-dom.production.min.js:42
sc @ react-dom.production.min.js:41
unstable_runWithPriority @ react.production.min.js:25
Da @ react-dom.production.min.js:60
mk.Events.current @ react-dom.production.min.js:236
Ei @ react-dom.production.min.js:41

### 📷 复现步骤

1. 使用在线编辑器生成任意模板页面
2. 删除生成的静态路由配置, 改为上面说的动态路由
3. 从浏览器进入刚才生成的模板页面
4. 使用在线代码编辑器给当前页面添加"区块"中的任意组件(这一步就会报上面说的异常)

### 🏞 期望结果

期望能动态查找路由所对应的组件所在的位置, 消除报错异常.

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本: 3.2.14
- 浏览器环境: Google Chrome 85.0.4183.121
- 开发环境: Windows10 1909, WebStorm 2020.2, Node.js v12.16.1

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/6710


有很多同类问题，可以搜一下，一般重启能解决

**Comment by gy0801151351** [comment]
可能是我没讲清楚, 我用静态配置的路由是正常的, 就是这种dynamic({ loader: () => import(@/pages${componentPath}), loading: LoadingComponent})的动态路由,而且是带有 变量表达式 的才会报错....
所以, 这个BUG跟其他的类似的问题是不一样的.

**Comment by gy0801151351** [comment]
这个应该是umi的问题, 你们做 antd的搞不定也很正常.

**Comment by gy0801151351** [comment]
我自己已经找到变通的解决办法.
简单的讲, 就是分两步,
1. 在 /config/config.ts里面配置好静态路由
2. 在 app.tsx里的 patchRoutes方法中再把第1步配置的路由给删掉, 使用动态配置的路由. 这样就不会报 "只有 pages 或 page 目录下的页面才能插入资产"这个错了. 
虽然这个办法看上去比较别扭, 但是临时先这么做了. 但愿antd或umi在以后的版本能修复这个BUG
