### ISSUE TITLE
🐛[BUG] layout/siderWidth 侧边栏收缩页面布局无法回弹

### ISSUE THREAD

**Issue by Edison-tianhe** [ant-design/ant-design-pro#7471]
### 🐛 bug 描述

siderWidth设置之后，侧边栏收缩正常，但页面布局无法正常回弹

### 📷 复现步骤及解决方案

`config/defaultSettings.ts`文件设置 `siderWidth: "225"`  数值为string类型  相关组件样式出现问题

改为`siderWidth: 225` number类型  相关组件样式恢复正常

### 🏞 疑惑点

既然string类型有问题，为什么sider组件展示正常，sider的占位`div`的样式却出现问题

### 💻 复现代码
源码中`div`样式的逻辑
```
// node_modules\@ant-design\pro-layout\es\SiderMenu\SiderMenu.js

style: _objectSpread({
      width: collapsed ? 48 : siderWidth,
      overflow: 'hidden',
      flex: "0 0 ".concat(collapsed ? 48 : siderWidth, "px"),
      maxWidth: collapsed ? 48 : siderWidth,
      minWidth: collapsed ? 48 : siderWidth
    }, style)
```
正常来说`width/maxWidth/minWidth/flex`中的数值应该一致，但是实际不一样，望解惑

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.0
- umi 版本: ^3.2.0
- @ant-design/pro-layout: ^6.4.19
- 浏览器环境: 85.0.4183.121（正式版本） （64 位）
- 开发环境: win

### 🚑 dom截图

![image](https://user-images.githubusercontent.com/35984031/96087505-89b4c000-0ef6-11eb-8d63-4864a8e3bcf2.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/96209519-63e4f500-0fa2-11eb-8044-679dc011f78e.png)


代码里有lei'xing类似这样的逻辑，还有根据宽度的计算，所以用 string 是不行
