### ISSUE TITLE
🐛[BUG]  initialState变化了，但是路由菜单不渲染

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#7473]
### 🐛 bug 描述

1. 登陆后，在组件中使用 ` const { refresh, initialState } = useModel('@@initialState');`
2. 我的需求是：根据权限的不同，路由菜单显示也不同，然而我在组件中使用refresh想要刷新initialState时，是第一次的initialState直接渲染了，然后refresh后的initialState变化了，但是页面上方路由菜单不刷新。

### 💻 复现代码
routerConfig.ts `
 {
    name: 'patientCenter.patient-center',
    icon: 'idcard',
    path: '/patient-center',
    component: './PatientCenter',
    access: 'canUsePatientCenter',
  },`

access.ts
`export default function access(initialState: {
  currentUser?: any | undefined;
  permission?: any | undefined;
}) {
  const { permission = {} } = initialState;
  console.log('permission:%o', permission);
  return {
    canCreateDataSet: permission?.function_access_pers?.create_dataset || false, // 是否能够创建数据集
    canCreateDashBoard: permission?.function_access_pers?.create_dashboard || false, // 是否能够创建仪表盘
    canUseFileSystem: permission?.function_access_pers?.file_system || false, // 是否可以使用文件系统模块
    canUsePatientCenter: permission?.function_access_pers?.patient_module || false, // 是否可用患者模块
    canUseReportCenter: permission?.function_access_pers?.report_module || false, // 是否可用报告模块
    canUseQueryStats: permission?.function_access_pers?.statistics_module || false, // 是否可用统计模块
    canDownloadData: {
      // 在对应的数据源下是否有下载数据集的权限
      ...permission.data_access_pers,
    },
  };
}`

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ISBN9527** [comment]
指点下

**Comment by chenshuai2144** [comment]
直接刷新整个浏览器是最方便的

**Comment by ISBN9527** [comment]
目前是这样解决的，还有什么其他办法吗？

**Comment by chenshuai2144** [comment]
layout 和 initalState 通信的 bug，umi 上好像有解决方案

**Comment by ISBN9527** [comment]
umi好像有人说用menuDataRender这个api，我试了下还是不行呢

**Comment by kaoding** [comment]
> 直接刷新整个浏览器是最方便的

https://github.com/ant-design/ant-design-pro/commit/e199a07712ab95e41f2e8b89ea7553fd4bb7bd06
