### ISSUE TITLE
1016号后下载安装报错：src/model/global.ts的129行括号不对🐛[BUG]

### ISSUE THREAD

**Issue by vivichloe** [ant-design/ant-design-pro#7475]
### 🐛 bug 描述
1016号后下载安装，启动时会报错：src/model/global.ts的129行括号不对

setup({ history }): void {
      // Subscribe history(url) change, trigger `load` action if pathname is `/`
      history.listen(({ pathname, search }): void => {
        if (typeof window.ga !== 'undefined') {
          window.ga('send', 'pageview', pathname + search);
        }
错误指向该文件的该行 history.listen((中的第二个括号，在编译时的某个插件会报这个错误，错误信息如下：

× Webpack
  Compiled with some errors in 35.67s

 ERROR  Failed to compile with 1 errors                                                                     下午12:28:14
 error  in ./src/models/global.ts.
Starting the development server...
Syntax Error: SyntaxError: D:\vv_work\NorthPole\test\ant-design-pro-master\src\models\global.ts: Did not expect a type annotation here. (129:21)

  127 |     setup({ history }): void {
  128 |       // Subscribe history(url) change, trigger `load` action if pathname is `/`
> 129 |       history.listen(({ pathname, search }): void => {
      |                      ^
  130 |         if (typeof window.ga !== 'undefined') {
  131 |           window.ga('send', 'pageview', pathname + search);
  132 |         }

 @ ./src/.umi/plugin-dva/connect.ts 2:0-82 2:0-82
 @ ./src/.umi/core/umiExports.ts
 @ ./node_modules/umi/dist/index.esm.js
 @ ./src/global.tsx
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts
### 📷 复现步骤
git clone 项目后
npm install
npm start会出现

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
`src/model/globle.ts` 这个文件是没有的 ，你是不是安装错了

**Comment by vivichloe** [comment]
sorry 打错了，是 src/model/global.ts这个文件

**Comment by chenshuai2144** [comment]
也没有这个文件，来个链接？

**Comment by CoddingApe** [comment]
同样的问题，不过路径是src\models\global.ts
报错信息：
Syntax Error: SyntaxError: E:\Workstation\changhong-crl\crl-front\src\models\global.ts: Did not expect a type annotation here. (129:21)

  127 |     setup({ history }): void {
  128 |       // Subscribe history(url) change, trigger `load` action if pathname is `/`
> 129 |       history.listen(({ pathname, search }): void => {
      |                      ^
  130 |         if (typeof window.ga !== 'undefined') {
  131 |           window.ga('send', 'pageview', pathname + search);
  132 |         }

**Comment by CoddingApe** [comment]
同样的问题，不过路径是src\models\global.ts

复现步骤：
执行命令 npm create umi demo
后续选项如下：
-> ant design pro
-> Pro V4
-> Javascript
-> simple
-> antd@4
选完之后自动clone，然后就报错
? Select the boilerplate type ant-design-pro
? � Be the first to experience the new umi@3 ? Pro V4
? � Which language do you want to use? JavaScript
? � Do you need all the blocks or a simple scaffold? simple
? � Time to use better, faster and latest antd@4! antd@4
Cloning into 'demo'...
remote: Enumerating objects: 187, done.
remote: Counting objects: 100% (187/187), done.
remote: Compressing objects: 100% (172/172), done.
Receiving objects:  88% (165/187), 236.00 KiB | 223.00 KiBused 0 eceiving objects:  87% (163/187), 236.00 KiB | 223.00 KiB/s
Receiving objects: 100% (187/187), 291.32 KiB | 237.00 KiB/s, done.
Resolving deltas: 100% (22/22), done.
> � clone success
> [Sylvanas] Prepare js environment...
events.js:291
      throw er; // Unhandled 'error' event
      ^

SyntaxError: unknown: Did not expect a type annotation here. (129:21)

  127 |     setup({ history }): void {
  128 |       // Subscribe history(url) change, trigger `load` action if pathname is `/`
> 129 |       history.listen(({ pathname, search }): void => {
      |                      ^
  130 |         if (typeof window.ga !== 'undefined') {
  131 |           window.ga('send', 'pageview', pathname + search);
  132 |         }
    at Object._raise (C:\Users\REONIX\AppData\Roaming\npm-cache\_npx\14492\node_modules\create-umi\node_modules\@babel\parser\lib\index.js:799:17)

后续执行执行npm install && npm run start依然报错：
**Syntax Error: SyntaxError: E:\Workstation\demo\src\models\global.ts: Did not expect a type annotation here. (129:21)

  127 |     setup({ history }): void {
  128 |       // Subscribe history(url) change, trigger `load` action if pathname is `/`
> 129 |       history.listen(({ pathname, search }): void => {
      |                      ^
  130 |         if (typeof window.ga !== 'undefined') {
  131 |           window.ga('send', 'pageview', pathname + search);
  132 |         }**

**Comment by ezailWang** [comment]
出现同样问题 打包报错 
src/models/global.ts: Did not expect a type annotation here. (129:21)

**Comment by xliudaxia** [comment]
同样的问题，在线求解答，是不是执行merge之前没有做测试？

**Comment by frankgray** [comment]
请查看日志：
× Webpack
  Compiled with some errors in 1.72m

 ERROR  Failed to compile with 1 errors                                                                                                                    3:08:45 ├F10: PM┤

 error  in ./src/models/global.ts

Syntax Error: SyntaxError: D:\code\web-workspace\ant-design-pro\src\models\global.ts: Did not expect a type annotation here. (129:21)

  127 |     setup({ history }): void {
  128 |       // Subscribe history(url) change, trigger `load` action if pathname is `/`
> 129 |       history.listen(({ pathname, search }): void => {
      |                      ^
  130 |         if (typeof window.ga !== 'undefined') {
  131 |           window.ga('send', 'pageview', pathname + search);
  132 |         }

**Comment by LbhFront-end** [comment]
+1

**Comment by proactivefly** [comment]
+1

**Comment by chenshuai2144** [comment]
删除一下这个代码吧，umi 不支持这个api了，这个是用来统计页面的访问信息的。

![image](https://user-images.githubusercontent.com/8186664/96240991-27ca8800-0fd4-11eb-8165-5193836cc3e4.png)

**Comment by frankgray** [comment]
> 删除一下这个代码吧，umi 不支持这个api了，这个是用来统计页面的访问信息的。
> 
> ![image](https://user-images.githubusercontent.com/8186664/96240991-27ca8800-0fd4-11eb-8165-5193836cc3e4.png)

ok
