### ISSUE TITLE
jest打包iconfont报错🧐[问题]

### ISSUE THREAD

**Issue by old-zsh** [ant-design/ant-design-pro#7477]
### 🧐 问题描述

jest 打包iconfont报错，在组件中引入的封装的iconfont.js,运行没问题，但是在执行jest测试报以下错误，
![image](https://user-images.githubusercontent.com/20679549/96210190-fdf96d00-0fa3-11eb-8027-36df29142575.png)

我的jest配置如下
![image](https://user-images.githubusercontent.com/20679549/96210247-15d0f100-0fa4-11eb-874e-e366dd158761.png)
组件引入如下：
![image](https://user-images.githubusercontent.com/20679549/96210292-28e3c100-0fa4-11eb-9143-0c310eaf3e5b.png)
请问如何配置jest才可以让iconfont不报错？？？？

**Comment by chenshuai2144** [comment]
参考这里
https://github.com/ant-design/pro-components

**Comment by SFmonkey** [comment]
@old-zsh 请问最后有解决方案了吗？🥺

**Comment by banyudu** [comment]
类似问题都可以通过mock解决：

```bash
npm i -D identity-obj-proxy
```

```json
  "jest": {
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
      "\\.(png|jpeg|jpg|gif)$": "identity-obj-proxy",
      "iconfont\\.js$": "identity-obj-proxy"
    }
  }
```

**Comment by july-12** [comment]
@banyudu take your suggestion like blew, it will work for me :)

```javascript
    "moduleNameMapper": {
        "iconfont": "identity-obj-proxy"
    }
```
