### ISSUE TITLE
部署后Logo和顶部菜单栏样式丢失🧐[问题]

### ISSUE THREAD

**Issue by C-SF-C** [ant-design/ant-design-pro#7479]
### 🧐 问题描述

使用npm start 启动项目没有问题，build后部署在nginx上，只有左上角logo和顶部菜单栏样式丢失
V4版本
对比后发现是global样式都没有加载进来！

### 💻 示例代码

请大佬指点下

### 🚑 其他信息

部署异常：
![IMG_20201016_140459](https://user-images.githubusercontent.com/53546899/96219441-6d2d8c00-0fb9-11eb-8b43-3452ffd1a7e4.jpg)
开发正常：
![IMG_20201016_140629](https://user-images.githubusercontent.com/53546899/96219470-774f8a80-0fb9-11eb-909a-68e87227bb1f.jpg)

**Comment by chenshuai2144** [comment]
有重现的地址吗？ 最好是能访问你的nginx的地址。

可以先 删除 lock，`git clean -dfx `然后` npm i `一下，这样可以解决版本问题。
