### ISSUE TITLE
🧐[问题] 怎么设置进入移动端（菜单隐藏）的breakpoint

### ISSUE THREAD

**Issue by zoeykk** [ant-design/ant-design-pro#7480]
### 🧐 问题描述
v5当前版本在尺寸小于768（‘md’）时候自适应为移动端样式（菜单默认是隐藏的那种），我想修改这个breakpoint 想在平板上也使用这种移动端样式 怎么设置

**Comment by zoeykk** [comment]
在antd layout里找到答案了
  app.tsx里设置（  breakpoint="lg"  collapsedWidth="0"）不起作用是and问题还是pro不支持？

**Comment by chenshuai2144** [comment]
@zoeykk  collapsedWidth是不会生效的，你可以设置 mobile=true 试试，以前没有见过这个 case，可能支持的不大好

**Comment by zoeykk** [comment]
> @zoeykk collapsedWidth是不会生效的，你可以设置 mobile=true 试试，以前没有见过这个 case，可能支持的不大好

试了isMobile: true不行  但是禁了disableMobile: true可以   ~ ~ ~

**Comment by gezhicui** [comment]
怎么解决的呢，我设置（ breakpoint="lg" collapsedWidth="0"）整个菜单出不来了
