### ISSUE TITLE
安装的时候报错

### ISSUE THREAD

**Issue by mysky2015-1** [ant-design/ant-design-pro#7481]
### 🧐 yarn create umi 报错

yarn create umi 之后
Select the boilerplate type ant-design-pro
然后报错UnhandledPromiseRejectionWarning:

如截图等其他信息可以贴在这里
![image](https://user-images.githubusercontent.com/11416863/96234900-a7ecef80-0fcc-11eb-94ea-feb389846706.png)

![image](https://user-images.githubusercontent.com/11416863/96235304-33ff1700-0fcd-11eb-8e68-2626aeed63d3.png)

* 请问如何解决

**Comment by chenshuai2144** [comment]
升级一下 node的版本，10. 就支持这个语法了
