### ISSUE TITLE
创建V5版本antd pro 启动会出现警告🐛[BUG]

### ISSUE THREAD

**Issue by Alt-er** [ant-design/ant-design-pro#7484]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/18004903/96282801-c6270f80-100d-11eb-98ca-68a011d994cd.png)

### 📷 复现步骤

npm create umi

npm install

npm start

打开页面后会出现上图中的警告

### 🏞 期望结果

无警告日志打印

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境 chrome
- 开发环境 [e.g. win10]

**Comment by chounvwudi** [comment]
@umijs/preset-react版本问题，版本不要高于1.6.10可解决此问题
