### ISSUE TITLE
🐛[BUG] V5 约定式路由下的登录页 前端呈现 和 在config中配置这种方式下不同

### ISSUE THREAD

**Issue by BeanWei** [ant-design/ant-design-pro#7485]
### 🐛 bug 描述
![屏幕截图 2020-10-17 111653](https://user-images.githubusercontent.com/33516660/96327274-b853a780-106a-11eb-93c8-e7094a721303.png)

### 📷 复现步骤
移除config.ts下的routes配置

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本
- 浏览器环境 Edge
- 开发环境: Ubuntu

**Comment by chenshuai2144** [comment]
是否显示菜单是 routers 中的 layout 配置实现的。直接在config.ts 中配置 `layout=false `
