### ISSUE TITLE
🐛[BUG] V5 Steps Css not work correctly.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#7486]
### 🐛 bug 描述
I use to Ant design pro v5.
I'm trying to put this component on the page, but it turns out like the image below.
from https://ant.design/components/steps/#components-steps-demo-step-next

### 📷 复现步骤
![steps](https://user-images.githubusercontent.com/6988989/96339521-fa4a1100-109d-11eb-81bd-b52c6ded0d88.PNG)

### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本
- 浏览器环境
- 开发环境 Windows, Chrome

**Comment by chenshuai2144** [comment]
try restart you serve？ css no hot load

**Comment by xXAvoraXx** [comment]
it is not written in the document but I did it by adding (_import 'antd/dist/antd.css'_) to the top of the relevant page.
