### ISSUE TITLE
👑 [需求]菜单的多语言支持的简化

### ISSUE THREAD

**Issue by fmpfmp** [ant-design/ant-design-pro#7487]
### 🥰 需求描述

在实际应用中，多数的系统是不需要支持多语言国际化的；

但仍然需要按照 多语言 的约定来配置，带来了不必要的麻烦；

### 🧐 解决方案

是否可以在route中加一个  defaultText 的属性；

如果有这个属性，就直接把defaultText作为菜单文字显示，不走多语言；

如果没有这个属性，再走多语言的配置；

**Comment by BeanWei** [comment]
菜单的多语言可以在config下的配置关闭，应该可以满足需求？

**Comment by fmpfmp** [comment]
@BeanWei 
name 作为route的唯一标识，假如菜单名称重复，担心会对路由或者其他功能造成影响；

**Comment by shangfeiSF** [comment]
locale中配置茫茫多的类似'menu.form.advanced-form': '高级表单'，其中的menu是个什么约定？太隐晦了
