### ISSUE TITLE
👑 [需求] 4.x三级路由的实现方式过于繁琐

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design-pro#7488]
### 🥰 需求描述
我的项目中存在隐藏的三级路由，但是现在的三级路由需要我在二级路由中手动判断props.chidlren并返回。
这个判断繁琐不说，还会在跳转时产生滚动条无法自动置顶的问题。

所以我觉得应该恢复之前2.x版本的三级路由的逻辑，不需要在二级路由中进行额外的判断，就能直接访问到对应的三级路由页面，并且能够将对应的二级路由设置为选中状态。

### 🚑 其他信息

这是我现在的路由。

![image](https://user-images.githubusercontent.com/39861054/96408091-5a16f800-1215-11eb-8e53-a3d868b3a52d.png)

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/layout

看看这个

**Comment by MarxZhou** [comment]
> https://beta-pro.ant.design/docs/layout
> 
> 看看这个

好的，我去尝试一下。
