### ISSUE TITLE
@jing-wu  你要的是动态菜单吗

### ISSUE THREAD

**Issue by Shaoyouqing** [ant-design/ant-design-pro#7489]
@jing-wu  你要的是动态菜单吗

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issue_comments/588055006_

**Comment by jing-wu** [comment]
算是吧。
开发一些页面，事先不配置相关路由，由后端返回的数据动态生成路由，然后生成对应的菜单。避免事先配置好路由带来的一些局限性

**Comment by chenshuai2144** [comment]
那样你会打包所有的 js 的。技术上也很难实现。
你需要配置一个 serve 来动态打包 js

**Comment by jing-wu** [comment]
目前做到了按一个个独立的模块开发（有自己的 model），然后动态组装成页面。
前端请求后端有哪些页面，每个页面有哪些模块，然后前端动态生成相应的路由，每个页面的内容则由模块动态组合而成。
开发模式由原先的页面开发，转变为模块开发，页面具体内容由数据驱动，动态生成。
