### ISSUE TITLE
怎样设置左侧菜单点击后右侧页面重新渲染

### ISSUE THREAD

**Issue by sangxiaolong** [ant-design/ant-design-pro#749]
<img width="533" alt="screen shot 2018-01-18 at 11 04 30 am" src="https://user-images.githubusercontent.com/77712/35079390-14f02166-fc42-11e7-9dc8-dca846d92465.png">

左侧菜单类似于上面的查询表格，右侧页面组件的componentDidMount()中有获取数据的操作，用户可以按某些条件在列表页进行筛选搜索，当用户再次点击左侧菜单的时候，右侧的页面组件怎样才能重新加载，按最初的条件获取数据呢？

**Comment by ddcat1115** [comment]
不太明白。。。希望通过点击左侧同一个 MenuItem 实现右侧数据变化？

**Comment by sangxiaolong** [comment]
是的，就是点击左侧菜单后，右侧的数据按组价最初加载时候的搜索条件进行加载，相当于刷新了页面

**Comment by longzhaobi** [comment]
这个因为第一次加载组件会触发componentDidMount，第二次再点击如果组件还是当前组件就不会触发了。你如果需要重新触发可以把请求数据写到subscriptions里。

**Comment by sangxiaolong** [comment]
@longzhaobi 不想把所有的路由判断都写在subscription里，如果路由改了，后期维护起来比较麻烦

**Comment by longzhaobi** [comment]
那你就看看其他生命周期看能不能每次都执行，还有你说的这个如果路由改了，后期维护麻烦，一两个无所谓，如果你路由改动都非常大，那只能说明前期没规范好了，我用dva到现在，至少没出现过大批量的改路由过，一般前期路由地址规定是什么就一直是那个了。

**Comment by chenshuai2144** [comment]
加个loading state 。如果loading = false return null 。这样组件就会被销毁掉

**Comment by ddcat1115** [comment]
感觉这个交互不应该这样设计吧，重复点击同一个 MenuItem 应该没有任何变化，不应该依靠这个动作来重置 state（即使实现了用户也想不到这样用），直接加 reset 按钮之类的不行么？

**Comment by sangxiaolong** [comment]
@ddcat1115 我觉得用户习惯上还是觉得点击菜单会刷新页面啊，有些场景下没有搜索重置之类的按钮，比如只有一个table加上分页，用户翻了几页之后想回到第一页呢，直接点击左侧菜单就行了啊，传统的前后端不分离的应用不都是这样的吗

**Comment by ddcat1115** [comment]
点击其他菜单肯定应该刷新，点击当前菜单不会触发任何事情，Menu，Tabs 都是这样的，面包屑最后一级不可点也是类似。antd Table 分页第一页是永远展示的，可以直接点击，实在要回到初始状态就直接刷新，这才是常规做法吧

**Comment by chenshuai2144** [comment]
@sangxiaolong  你这个需求不具有普适性的。你可以自己实现。
对于浏览器来说你如果想重置状态  reload是最好的办法

**Comment by sangxiaolong** [comment]
![1516268912129](https://user-images.githubusercontent.com/77712/35092239-bad8a42c-fc79-11e7-9726-bce1d384a915.jpg)

@ddcat1115 我想实现类似于上面Issues这个Tab的点击效果，无论它是Menu还是Tab，只要是Link a链接，每次点击都应该刷新

**Comment by guoyangyang666** [comment]
请问你解决这个问题了吗？我也想实现点击左侧菜单页面刷新的功能

**Comment by SuperEffort** [comment]
请问问题解决了吗？也遇到了同样的问题，谢谢
