### ISSUE TITLE
🧐[问题]ProTable  字段类型是DateTime，但搜索的时候需要是选择日期范围，应该如何实现呢？

### ISSUE THREAD

**Issue by fmpfmp** [ant-design/ant-design-pro#7490]
### 🧐 问题描述

ProTable  字段类型是DateTime，但搜索的时候需要是选择日期范围，应该如何实现呢？

**Comment by mapleflow** [comment]
问题如果解决了，留下解决方案，方便他人，别关闭完事。

**Comment by PeakFish** [comment]
可以多用一列来实现，一个 hideInSearch 用来展示数据 `valueType="DateTime"`， 一个 hideInTable 用来搜索 `valueType="dateTimeRange"`。

**Comment by Veexx** [comment]
用search的transform方法可以转化搜索字段，传入props即可

  {
      title: '发布时间',
      dataIndex: 'createdAt',
      search: {
        transform: (fields) => {
          return {
            startTime: fields[0],
            endTime: fields[1],
          };
        },
      },
      hideInForm: true,
      width: 200,
      renderFormItem: (item, props, form) => {
        return <RangePicker {...props} />;
      }

**Comment by Evanl-lai** [comment]
试下用renderFormItem返回一个自定义节点
