### ISSUE TITLE
eslint not work🐛[BUG]

### ISSUE THREAD

**Issue by starhu521** [ant-design/ant-design-pro#7495]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/23275495/96549769-85b3e400-12e2-11eb-8e0e-9bbef2ba562c.png)

I have tried a lot of methods, but not work. And I have checked #7291 , #7290, https://github.com/umijs/sylvanas/pull/11#issue-476811568.

node:  v12.19.0
umi:  v3.2.24
"@umijs/fabric":  "^2.3.0"
"eslint": "^7.11.0"

os: mac

**Comment by chenshuai2144** [comment]
try use npm install pkg？
