### ISSUE TITLE
🧐[问题] 在global.less中修改antd变量无效

### ISSUE THREAD

**Issue by KellenHe** [ant-design/ant-design-pro#7497]
### 🧐 问题描述

在/src/global.less中修改antd less变量无效

`@primary-color: #0b68e6;`

![微信图片_20201020172924](https://user-images.githubusercontent.com/9713892/96567836-d97df780-12f9-11eb-8df2-13b4a693f48a.png)

**Comment by chenshuai2144** [comment]
推荐在 config.ts 的 theme 中修改，less 有互相引用优先级的问题

**Comment by KellenHe** [comment]
@chenshuai2144 有大量定制化的情况下，less代码很多，是一套自定义的样式库。如果都在config下修改不方便。

关于优先级，是否需要提供一个less的入口，定制化的less这种需求应该是很常见的。

**Comment by chenshuai2144** [comment]
@KellenHe 这个很难搞，如果你在 app.less 里面设置，如果再 import 一下  app.less  就失效了，所以最好是写在 js 里面，比较好控制
