### ISSUE TITLE
antd pro v5侧拉菜单是从服务端拉取，其中icon是后台字符串，新版已经不推荐使用Icon组件，该如何处理？

### ISSUE THREAD

**Issue by BluesVN** [ant-design/ant-design-pro#7498]
新版不推荐使用Icon组件，控制台会报警告。
转而使用`import { LogoutOutlined, SettingOutlined, UserOutlined } from '@ant-design/icons';`的方式进行引入。
但后台配置的图标都是字符串，例如desk、table这种；
先要能够动态配置侧栏菜单的图标该如何处理？
图标参考：https://ant.design/components/icon-cn/#header

1 项目内置一份全量的映射文件？

2使用iconfont 和i标签自己重新封装组件？

**Comment by chenshuai2144** [comment]
>  项目内置一份全量的映射文件？

推荐内部维护一份，你应该知道自己要用的 icon 列表。
