### ISSUE TITLE
🐛[BUG]路由：当二级路由有path属性的时候，三级路由的component一直显示的是二级路由的页面

### ISSUE THREAD

**Issue by fmpfmp** [ant-design/ant-design-pro#7500]
### 🐛 bug 描述

场景：
一级路由是主菜单：‘系统设置’
二级路由中有一个菜单：‘用户管理’  (页面上有个编辑按钮，点击会打开一个新页面修改用户信息)
三级路由：‘修改用户’  （hideInMenu:true， 不在菜单中显示）

### 📷 复现步骤

路由配置如下：
三级路由无论如何配置都找不到对应的component

去掉二级路由的path属性后，三级路由才可以正常打开对应的component

### 💻 复现代码

routes: [   
    {
      path: 'system',
      name: '系统设置',
      
      routes: [       
        {
          name: '用户管理',         
          path: '/system/users', 
          component: './system/user/index',   
          routes: [
            {
              name:'修改用户',
              path: '/owl/user/edit',
              component: './owl/user/create',                 
              hideInMenu:true,
            },           
          ]
        }
      ],
    },    
  ],
### © 版本信息

- Ant Design Pro 版本:   v5 最新代码
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kevin0713** [comment]
在二级 去掉 component，然后在三级路由里面加 path 和 component  二级菜单然后 hideInMenu:true

**Comment by fmpfmp** [comment]
@kevin0713    想要的是显示二级，不显示三级；  
菜单显示现在没问题，就是三级路由打开的时候，显示的是二级的页面；

**Comment by chenshuai2144** [comment]
自定义路由一定要记得，处理 children，不然无法展示
