### ISSUE TITLE
🧐[Question] How to set default locale (language)?

### ISSUE THREAD

**Issue by cielblog** [ant-design/ant-design-pro#7502]
### 🧐 Problem Description

I started a new ant-design-pro project on  (V5) and I added new  `ar-EG`'s language to the locales folder, then I change the `locale.default` value from `zh-CN` to `ar-EG`, and then I removed the browser cache, but the app keeps showing English locale until I change it manually from the navigator.

### 💻 Sample Code
My config.ts:

  `locale: {

    // default zh-CN

    default: 'ar-EG',

    antd: true,

    // default true, when it is true, will use `navigator.language` overwrite default

    baseNavigator: true,

  },`

Language exists in the navigator:
![image](https://user-images.githubusercontent.com/16566503/96630919-58852700-131e-11eb-8b11-d5179b2754f8.png)

![image](https://user-images.githubusercontent.com/16566503/96630974-65a21600-131e-11eb-9d91-6157de39a400.png)

### 🚑 Other information

umijs version 3
antd-pro version 5

**Comment by chenshuai2144** [comment]
Because he will read the environment variable first， it's warning
you can  setLocale in  `app.ts`.

**Comment by h1nson** [comment]
`locale: {
    default: 'en-US',
    antd: false,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: false,
  },`

Set **baseNavigator** to false!

**Comment by egelipta** [comment]
In app.tsx file add this code

localStorage.setItem('umi_locale', 'id-ID'); //your locale
