### ISSUE TITLE
🧐[问题]antd pro能否支持antd的<ConfigProvider prefixCls='xxx'>

### ISSUE THREAD

**Issue by KellenHe** [ant-design/ant-design-pro#7504]
### 🧐 问题描述

antd pro能否支持antd的
`
<ConfigProvider prefixCls='cscs'>
  {this.renderContent()}
</ConfigProvider>
`
或者类似的功能可以修改样式的前缀。

**Comment by chenshuai2144** [comment]
支持的，与 antd 用法相同，但是要注意相关的样式覆盖问题。

你可以设置一个全局的 layout，在 layout 中配置 ConfigProvider, 可以参靠这个文档
https://beta-pro.ant.design/docs/layout-cn#%E8%87%AA%E5%AE%9A%E4%B9%89-layout

**Comment by KellenHe** [comment]
> 支持的，与 antd 用法相同，但是要注意相关的样式覆盖问题。
> 
> 你可以设置一个全局的 layout，在 layout 中配置 ConfigProvider, 可以参靠这个文档
> https://beta-pro.ant.design/docs/layout-cn#%E8%87%AA%E5%AE%9A%E4%B9%89-layout

@chenshuai2144 我目前是这样做的，在一个layout中设置，但是antd生效了，antd pro的前缀还是ant，并未生效。

**Comment by chenshuai2144** [comment]
来个repo，我们微前端项目一直在用 还没收到货反馈

**Comment by KellenHe** [comment]
https://codesandbox.io/s/pedantic-dream-oz893?file=/README.md

yarn安装的时候codesandbox一直报no space left on device。依赖安装不成功。
这个是我本地重现后上传到codesandbox的。

**Comment by KellenHe** [comment]
@chenshuai2144 代码是在pro v5的基础上主要做了如下修改：
1. 删除了pro的layout布局，在config中删除layout配置，在app.tsx中删除layout导出
2. 在src/pages下新增了layout文件夹，添加了自定义的layout，并使用ConfigProvider包裹。

**Comment by KellenHe** [comment]
@chenshuai2144 
升级到    "@ant-design/pro-table": "^2.9.8" 和     "antd": "^4.7.2"，就好了。
但是还有一些细节问题，比如pro table 的列展示下拉框样式还有点问题。
![微信图片_20201022162738](https://user-images.githubusercontent.com/9713892/96845745-9e0f3480-1483-11eb-9a0f-43b55d65cdea.png)

**Comment by birdycn** [comment]
pro-form遇到同样的问题
