### ISSUE TITLE
🧐[问题] 面包屑自动拼接节点

### ISSUE THREAD

**Issue by qq382724935** [ant-design/ant-design-pro#7505]
### 🧐 问题描述
umi3创建的项目，使用PageContainer，面包屑会自动拼接节点的path

看了#7389，需要在breadcrumbRender api 重定义，在.umirc中配置layout,routes生成的布局路由, 应该怎么进行重定义？

**Comment by qq382724935** [comment]
尝试在PageContainer外层使用ProLayout，但就属于嵌套布局了

**Comment by qq382724935** [comment]
已解决

**Comment by Sean1514** [comment]
> 已解决

请问怎么解决的呢？
