### ISSUE TITLE
🧐[问题] layout布局为top，在页面布局对应位置显示为[object Object]

### ISSUE THREAD

**Issue by shaodushu** [ant-design/ant-design-pro#7506]
### 🧐 问题描述

layout布局为top，在页面布局对应位置显示为[object Object],导致页面布局异常

### 💻 示例代码

![image](https://user-images.githubusercontent.com/26360246/96688866-3a6a0600-13b4-11eb-8655-9c8d21956c0c.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26360246/96689013-6be2d180-13b4-11eb-8faf-a43be1da401c.png)

**Comment by chenshuai2144** [comment]
来个重现吧，是了一下并不会

**Comment by shaodushu** [comment]
![image](https://user-images.githubusercontent.com/26360246/96700863-80c66180-13c2-11eb-93a9-727874e99691.png)

在路由中这样设置设置就会出现。

"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.0.19",
    "@ant-design/pro-form": "^1.0.2",
    "@ant-design/pro-layout": "^6.4.19",
    "@ant-design/pro-table": "^2.9.5",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.7.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },

**Comment by chenshuai2144** [comment]
这种用法是在哪里看到的？

**Comment by shaodushu** [comment]
https://github.com/umijs/umi/issues/5233

https://beta-pro.ant.design/docs/layout-cn#%E6%A0%B9%E6%8D%AE%E8%B7%AF%E7%94%B1%E9%9A%90%E8%97%8F%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95%E3%80%81%E9%9A%90%E8%97%8F%E5%AF%BC%E8%88%AA%E5%A4%B4%E3%80%81footer

**Comment by shaodushu** [comment]
在umi文档中没有相关参数，https://umijs.org/zh-CN/plugins/plugin-layout#layout

**Comment by shaodushu** [comment]
@chenshuai2144 请问上述文档中参数目前是否还能使用
