### ISSUE TITLE
v5版本，在route配置里配路由菜单，一级菜单没有配置path和component，在routes加了多个二级菜单的路由，当前的菜单正常打开，后面的菜单打开内容为空🧐[问题]

### ISSUE THREAD

**Issue by RickChenCX** [ant-design/ant-design-pro#7508]
### 🧐 问题描述
v5版本，在route配置里配路由菜单，一级菜单没有配置path和component，在routes加了多个二级菜单的路由，当前的菜单正常打开，后面的菜单打开内容为空

### 🚑 其他信息

<img width="336" alt="截屏2020-10-22 上午9 47 50" src="https://user-images.githubusercontent.com/23163651/96808615-c11df200-144b-11eb-8a4c-49e7ca7d6029.png">
<img width="294" alt="截屏2020-10-22 上午9 48 05" src="https://user-images.githubusercontent.com/23163651/96808640-c9762d00-144b-11eb-8af2-cd55e89ea125.png">

UserManage 菜单正常打开展开的页面，BaseData下的展开打开为空

**Comment by RickChenCX** [comment]
<img width="435" alt="截屏2020-10-22 上午9 52 04" src="https://user-images.githubusercontent.com/23163651/96808877-51f4cd80-144c-11eb-940d-dd93c1b1bab6.png">
<img width="512" alt="截屏2020-10-22 上午9 52 18" src="https://user-images.githubusercontent.com/23163651/96808879-53be9100-144c-11eb-8574-1629047c2afd.png">
展示的效果

**Comment by chenshuai2144** [comment]
path 还是要设置的，不设置 path 会匹配所有的路由一般是用来做 404 的，你这样会导致 任何不在 routers 里面的都无法找到
