### ISSUE TITLE
您的网络发生异常，无法连接服务器🧐[问题]

### ISSUE THREAD

**Issue by totemtec** [ant-design/ant-design-pro#7509]
### 业务出错，服务器返回了错误信息，前端也进行了提示，但是一直有个 "您的网络发生异常，无法连接服务器"
<img width="504" alt="Screen Shot 2020-10-22 at 10 08 19 AM" src="https://user-images.githubusercontent.com/2002380/96812862-e52f0280-144e-11eb-8911-1d3e889090db.png">

找到了代码
app.js

const errorHandler = (error: ResponseError) => {
  const { response } = error;
  ......

  if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};

发现错误处理没有传过来response，是undefined
这种情况怎么处理呢

期望真正的网络出错才有这个提示
业务出错的时候，不要有这个网络出错提示

**Comment by 569202812** [comment]
看样子像是你相应拦截器处理的原因喃,提供下拦截器的代码

**Comment by shaohuatsou** [comment]
正常来说，除了真正的网络问题，剩下的服务器都是有返回的，error里面确实应该包含response或者data的。
![image](https://user-images.githubusercontent.com/50793943/97383042-a645f480-1907-11eb-84a5-9c92d4e799cb.png)

**Comment by totemtec** [comment]
后来在app.tsx中，给errorHandler报错加了个判断，就是BizError不再提示网络错误，算是暂时解决了这个问题

if (error.name !== 'BizError' && !response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }

这样还是使用框架提供的错误提示，如果这里errorHandler需要自己提示业务错误，那还是拿不到response信息

**Comment by chenshuai2144** [comment]
`error.response` 这样就可以拿到了

**Comment by ly020044** [comment]
@chenshuai2144  下午好，当发生 BizError 错误的时候， error里面拿到的 response 为 undefined。这个 BizError 是啥错误？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/blob/2de577ed78c2df2a2a16933e97b77920366fcf6c/docs/plugins/plugin-request.md

是我们做的一个转化

**Comment by 569202812** [comment]
> https://github.com/umijs/umi/blob/2de577ed78c2df2a2a16933e97b77920366fcf6c/docs/plugins/plugin-request.md
> 
> 是我们做的一个转化

我试了一下在没有catch的时候会堵塞页面吗
![image](https://user-images.githubusercontent.com/34082148/106348499-ab994d80-6301-11eb-97b8-20a836878c6a.png)

**Comment by chenshuai2144** [comment]
你可以配置app.ts, extends 中onError 全部设置一下，但是我比较推荐每个请求都处理一下，这样很健壮。
