### ISSUE TITLE
🐛[BUG] V5的登录页，在移动端下，两边顶着边了，没有v4的体验好；

### ISSUE THREAD

**Issue by fmpfmp** [ant-design/ant-design-pro#7513]
### 🐛 bug 描述

V5的登录页，在移动端下，两边顶着边了，没有v4的体验好；
### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本
- 浏览器环境   iphone X
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
重写了
