### ISSUE TITLE
面包屑能不能支持换成多个页签

### ISSUE THREAD

**Issue by caiseg** [ant-design/ant-design-pro#7514]
类似于tab页签

**Comment by pkaq** [comment]
#220

**Comment by shaohuatsou** [comment]
或者自己实现

**Comment by chenshuai2144** [comment]
暂时不会支持的，需要 umi 的 keep live

**Comment by Fengly0503** [comment]
自己实现了一个，上到项目中感觉还可以，可以参考一下：https://github.com/Fengly0503/ant_pro_tabs 在线演示地址：http://pc.loveeveryday.cn/ant-pro-tabs/
