### ISSUE TITLE
🐛[BUG]ant design pro 服务端渲染菜单无法显示，一片空白

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design-pro#7515]
### 🐛 bug 描述

 "@ant-design/pro-layout": "^6.4.19",通过setState进行的内容填充，pro-layout无法获取数据改变。并且不进行数据渲染
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by daifuyang** [comment]
服务端渲染的菜单在pro-layout中显示空白！打印array为空

**Comment by wangjusheng** [comment]
远程加载.menuDataRender传入的值有数据, menu还是显示为空

**Comment by daifuyang** [comment]
我解决了！官方这个menu需要增加一个laoding状态来控制数据实时刷新！
还需要吧defaultSetings中的menu删除
menu={{ locale: false, loading }}

**Comment by daifuyang** [comment]
it's ok

**Comment by zhipingzhang** [comment]
> 我解决了！官方这个menu需要增加一个laoding状态来控制数据实时刷新！
> 还需要吧defaultSetings中的menu删除
> menu={{ locale: false, loading }}

请问这个在哪加呀

**Comment by chenshuai2144** [comment]
proLayout 上面
