### ISSUE TITLE
Global.less seems to be overridden when updating global styles?

### ISSUE THREAD

**Issue by askurat** [ant-design/ant-design-pro#7517]
I am trying to update the border radius for a checkbox by adding this to global.less file:
`.ant-checkbox-inner {
  border-radius: 4px;
}`

I would like this to be global which is why I put it in the global.less file, however, it seems to be overridden by "antd/es/checkbox/style/index.less". 

Is this correct? How do I override the checkbox style globally?

Here is a screenshot showing it is overridden:

![image](https://user-images.githubusercontent.com/9997087/97028051-34456800-1521-11eb-942b-0702a3ddd6e9.png)

**Comment by chenshuai2144** [comment]
it is first loader。
