### ISSUE TITLE
🧐pro-table中，request里的params参数可以去掉pagesize和current吗

### ISSUE THREAD

**Issue by DunDunDunAbandon** [ant-design/ant-design-pro#7518]
### 🧐 问题描述

request里的params每次只刷新页面不查询的话不是都会主动发送pagesize和current吗，但我现在只想实现一个最简单的表格页面，就是从后端返回一条数据显示在表格里，不需要分页用的pagesize和current，该怎么处理呢？找了半天也没看到是怎么封装了params可以主动只发送这俩参数的。

**Comment by DunDunDunAbandon** [comment]
找到了…确实是封装好了的……还是不知道咋改

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/issues/827
