### ISSUE TITLE
🧐[问题] toolBarRender: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/ant-design-pro#7520]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/51048705/97085311-53daae80-164f-11eb-86a3-5c15e641235e.png)

![image](https://user-images.githubusercontent.com/51048705/97085324-6b199c00-164f-11eb-9ec1-5019ba838e6a.png)

devScripts.js:5836 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ListToolBar`. It was passed a child from ToolBar. See https://fb.me/react-warning-keys for more information.
    in Button (at ListTableList/index.tsx:169)
    in ListToolBar (created by ToolBar)
    in ToolBar (created by ProTable)
    in div (created by Card)
    in div (created by Card)
    in Card (created by ProTable)
    in div (created by ProTable)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ProTable)
    in ProTable (created by ProviderWarp)
    in ErrorBoundary (created by ProviderWarp)
    in ConfigProviderWarp (created by ProviderWarp)
    in Provider (created by ProviderWarp)
    in ProviderWarp (at ListTableList/index.tsx:161)
    in div (created by PageContainer)
    in div (created by PageContainer)
    in div (created by GridContent)
    in div (created by GridContent)
    in GridContent (created by PageContainer)
    in div (created by PageContainer)
    in PageContainer (at ListTableList/index.tsx:160)
    in TableList (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in WithExceptionOpChildren (at layout/index.tsx:140)
    in ErrorBoundary (at layout/index.tsx:139)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (created by WrapContent)
    in ConfigProviderWarp (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (at layout/index.tsx:83)

**Comment by waylon-gmail** [comment]
以前都不会报这个错误，不知道从什么时候开始出现了这个。官网提供的预览页面好像没有这个问题。不晓得需要设置什么。V5最新代码直接拉取运行后也有这个问题。

**Comment by waylon-gmail** [comment]
求大佬帮忙指点一下，这里该如何设置key。谢谢。

**Comment by BeanWei** [comment]
文档中有示例

```tsx
toolBarRender={() => [
        <Button key="show">查看日志</Button>,
        <Button key="out">
          导出数据
          <DownOutlined />
        </Button>,
        <Button key="primary" type="primary">
          创建应用
        </Button>,
      ]}
```

**Comment by KellenHe** [comment]
我也遇到这个问题了，升级版本后出现这个问题，之前没有这个报错。

**Comment by gaofei019** [comment]
我也遇到了，不知道怎么解决，😓

**Comment by chenshuai2144** [comment]
react 要求数组组件要增加一个 key， 可以这样写 `[<Button key="show">查看日志</Button>]`
