### ISSUE TITLE
🐛[BUG] protable 部分控件没有国际化

### ISSUE THREAD

**Issue by gerri0098** [ant-design/ant-design-pro#7521]
### 🐛 bug 描述

antd pro v5 版本
根据antd pro 文档做了国际化处理, 大部分界面都可以正常切换语言，但是表单中的 input / select 的 paceholder 没有转换语言， ProColumns 里也没有找到 placeholder 属性，可以手动进行转换

### 📷 复现步骤

切换语言

### 🏞 期望结果

切换到英语时，表单控件全部变成英文

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

对比图片
![image](https://user-images.githubusercontent.com/61908109/97101252-ccd11900-16d6-11eb-9458-7ea3b569b83d.png)
![image](https://user-images.githubusercontent.com/61908109/97101270-f5591300-16d6-11eb-8851-151631782aad.png)

**Comment by gerri0098** [comment]
https://procomponents.ant.design/components/table#%E5%9B%BD%E9%99%85%E5%8C%96%E7%A4%BA%E4%BE%8B

**Comment by gerri0098** [comment]
实在不行的话，只能手动 renderFormItem 重写控件了, 这样太麻烦，不能充分用到antd pro 的便捷之处

**Comment by chenshuai2144** [comment]
来个重现

**Comment by gerri0098** [comment]
应该是版本的问题，  protable 升级到 pro-table": "^2.9.5 ， 就正常了。谢谢🙏， 

之前的protable版本是2.7.2

**Comment by gerri0098** [comment]
还是建议一下，
可否考虑把 placeholder 属性提出来放到 ProColumns 里面呢，
毕竟 '请输入/ please enter' 的提示太简单了，
有时候会想要修改一下，但是通过 renderFormItem 只是为了修改 placeholder , 又觉得改动太大了点

**Comment by chenshuai2144** [comment]
@gerri0098  可以自定义国际化，或者用 `fieldProps.placeholder`

来 https://procomponents.ant.design/ 提问题吧
