### ISSUE TITLE
在form中添加select组件   为select设置defaultValue的值，不能通过form.getFieldValue获取到相应的值🐛[BUG]

### ISSUE THREAD

**Issue by wdd772109685** [ant-design/ant-design-pro#7523]
### 🐛 bug 描述
在form中添加select组件   为select设置defaultValue的值，不能通过form.getFieldValue获取到相应的值

### 🏞 期望结果

可以通过form.getFieldValue获取到select设置的defaultValue。

      <Form form={form}>
        <FormItem rules={[{required: true, message: "xxxx！"}]} label="设备" name="equipmentID">
          <Select style={{width: "70%"}} defaultValue={params.equipments[0]?.props?.value}>
            {params.equipments}
          </Select>
        </FormItem>-
      </Form>

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- 浏览器环境 chrome 86
- 开发环境 [Windows10]

### 🚑 其他信息

如截图等其他信息可以贴在这里
![image](https://user-images.githubusercontent.com/39125997/97145097-9f50a200-17a0-11eb-8549-41332122d93c.png)

**Comment by 569202812** [comment]
看一下文档FormItem之后不要通过defaultValue和value设置组件

**Comment by chenshuai2144** [comment]
使用 initalValues
