### ISSUE TITLE
AntD Pro 是否可以菜单可以支持动态的增删改查,配合后端接口实现路由配置~🧐question

### ISSUE THREAD

**Issue by DJPY** [ant-design/ant-design-pro#7525]
## 恭喜蚂蚁上树 啊  上市💐

> 现在的项目是通过后端返回菜单进行显示，但是菜单都是基于config里的路由配置，无法自定义，根据Pro官网文档配置的。

> @@@希望可以能够自定义化，实现动态的增删改路由菜单。

**Comment by shaohuatsou** [comment]
这个本身就是支持的呀，但是所有新增的路由，必须是已配置的路由。

**Comment by DJPY** [comment]
> 这个本身就是支持的呀，但是所有新增的路由，必须是已配置的路由。

### 🛫  
> 所有的路由必须是config里面的，后期的话我无法通过前后端交互的接口进行动态的增删改，我就是想能够实现路由菜单的高度自由化呀。
> 之所以想提这个问题 是应为我们经常需要去重新定制菜单规则，可能修改、可能新增、可能删除，每次都要去调整config里面的路由，想做成界面化的。

**Comment by DJPY** [comment]
> ## 恭喜蚂蚁上树 啊 上市💐
> > 现在的项目是通过后端返回菜单进行显示，但是菜单都是基于config里的路由配置，无法自定义，根据Pro官网文档配置的。
> 
> > @@@希望可以能够自定义化，实现动态的增删改路由菜单。


> ## 恭喜蚂蚁上树 啊 上市💐
> > 现在的项目是通过后端返回菜单进行显示，但是菜单都是基于config里的路由配置，无法自定义，根据Pro官网文档配置的。
> 
> > @@@希望可以能够自定义化，实现动态的增删改路由菜单。

## 🎉  🎉  这个需求要是可以的话，逼格就很高了呦。。 来人呀🎉  🎉  🎉    求解决方案噻~
> 🎉  🎉  🎉  🎉  🎉  🎉        🎉  🎉  🎉  🎉  🎉  🎉

**Comment by sicun7** [comment]
我也有这个需求,   我们的产品面向不同客户时, 每个客户要求的菜单组织都不一样,  所以无法在router.config.js里配置,  就想后端给一个菜单数据,  前端根据数据生成路由, 现在不知道怎么解决

**Comment by shaohuatsou** [comment]
> 我也有这个需求, 我们的产品面向不同客户时, 每个客户要求的菜单组织都不一样, 所以无法在router.config.js里配置, 就想后端给一个菜单数据, 前端根据数据生成路由, 现在不知道怎么解决

先把所有路由配置在config中，然后请求服务器菜单，通过menuDataRender动态渲染。

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

看看文档

**Comment by DJPY** [comment]
> > 我也有这个需求, 我们的产品面向不同客户时, 每个客户要求的菜单组织都不一样, 所以无法在router.config.js里配置, 就想后端给一个菜单数据, 前端根据数据生成路由, 现在不知道怎么解决
> 
> 先把所有路由配置在config中，然后请求服务器菜单，通过menuDataRender动态渲染。

### 🤦‍♂️那样不得行哦，我们暂时是这么做的，但是还是不能去动态的增删改查菜单，应为所有的菜单都是存在于config中的，害~~。
