### ISSUE TITLE
🐛[BUG]在两个二级菜单之间切换，第一次点击二级菜单，再其父级菜单会收起，再次点击切换不同的二级菜单，再点击父菜菜单没有收起，第二次点击才会收起...(官网也存在此问题)

### ISSUE THREAD

**Issue by beevivo6** [ant-design/ant-design-pro#7526]
### 🐛 bug 描述
在两个二级菜单之间切换，第一次点击二级菜单，再其父级菜单会收起，再次点击切换不同的二级菜单，再点击父菜菜单没有收起，第二次点击才会收起...(官网也存在此问题)

> @chenshuai2144 
#
> @chenshuai2144 

> umi-3.2.14版本
> antd/pro-layout-6.4.1版本
> antd-4.7.0版本
> 谷歌浏览器
  @chenshuai2144

**Comment by ChenWeihua123** [comment]
貌似只要点击一个二级菜单，就需要点击两次父级菜单才能收起

**Comment by beevivo6** [comment]
> 貌似只要点击一个二级菜单，就需要点击两次父级菜单才能收起

是的，而且，我已经把umi,pro-layout,antd这些库都升级到最新的笨笨了，不知道为啥还是不行.

**Comment by ouzhou** [comment]
确实是一个bug
只有点二级菜单的 主菜单才会出现这个问题, antd 的menu组件没有这个问题
