### ISSUE TITLE
@ant-design/pro-layout  menuDataRender不加载?

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#7527]
menuDataRender里面值是state,但我使用setState更新值后menuDataRender却不执行,导致我的左侧菜单栏加载不出来

**Comment by lcosmos** [comment]
我也碰到了同样的情况，以前4.2.0没这个问题，今天更新了一下，就不能用了

**Comment by lcosmos** [comment]
https://github.com/ant-design/ant-design-pro/issues/7530

**Comment by chenshuai2144** [comment]
模仿这个来，可以用 menu.loading 控制渲染
https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu
