### ISSUE TITLE
🧐[问题] 如何处理TS版JWT方案的TOKEN过期？

### ISSUE THREAD

**Issue by yuzifu** [ant-design/ant-design-pro#7528]
使用V4.2.1（TS版）做后台，登录方式使用JWT，期望的逻辑是服务端返回状态401立刻退出到登录界面，前端的改动有三个地方：

1. 登录后把获得的token存储
2. 在/src/utils/request.ts文件用request的拦截器，为headers添加token
3. 在/src/utils/request.ts文件的异常处理逻辑errorHandler里，当返回状态是401时从存储删除token

后来发现这种实现方式有个问题，当token异常（比如过期）时通过菜单切换不同的视图不会立刻退出到登录界面（只提示接口访问异常），原因是在SecurityLayout里，会根据currentUser对象判断是否登录，但此时currentUser对象（含token）没有及时更新，所以还是会判断已登录。

现在想到的方法有两个：

1. 在SecurityLayout的render()函数里添加获取currentUser对象的逻辑
2. 在request的errorHandler里清空User Model的currentUser对象

但总觉的这两种方式不太理想，本想来参考 #298 的思路，但它是JS版实现的，在TS找不到对应的地方来修改。
或者是在request的errorHandler发出一个信号，然后在SecurityLayout里订阅这个信号，执行清空currentUser对象的动作。

请问怎么实现我的这种需求？谢谢！

**Comment by manondidi** [comment]
我的解决方案是这样的,
1.登录后存下 token 和 refreshtoken
2.response拦截器 拦截后端返回 token过期的特殊状态码, 并且主动做调用刷新token接口,并且把刷新后的token重新保存,再提用户重新发起请求
3.刷新token 接口失败 (用户改了密码 refreshtoken过期等等原因),也有一个特殊的状态码, 判断出这个状态码 退到登录界面

具体代码如下

https://github.com/umijs/umi-request/issues/181#issuecomment-730794198

**Comment by yuzifu** [comment]
@manondidi 
感谢！
