### ISSUE TITLE
🐛[BUG]隐藏菜单栏后，控制台报内存溢出

### ISSUE THREAD

**Issue by RedScarf007** [ant-design/ant-design-pro#7529]
### 🐛 bug 描述
隐藏菜单栏后，控制台报内存溢出

### 💻 复现代码

config.ts里面的routes属性
` {
        path: '/h5/test',
        component: './user/login',
        layout: false,
    }
`
### © 版本信息

- Ant Design Pro 版本: 5.0
- umi 版本 ^3.2.14
- 浏览器环境 edge(新版，谷歌内核)
- 开发环境 [e.g. mac OS] win10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/28618983/97272674-384cef00-186d-11eb-9efa-66a6c6de15b5.png)
![image](https://user-images.githubusercontent.com/28618983/97272690-3e42d000-186d-11eb-9aa4-1dddc2c68e78.png)
![image](https://user-images.githubusercontent.com/28618983/97272705-4569de00-186d-11eb-9478-1c2a0f4f75b9.png)

另外作者能不能牵头写下文档，可以的话我也想参与其中，东西好用但是有写配置文档鸡零狗碎的给同事安利根本推不动啊

**Comment by chenshuai2144** [comment]
> 另外作者能不能牵头写下文档，可以的话我也想参与其中，东西好用但是有写配置文档鸡零狗碎的给同事安利根本推不动啊

@RedScarf007  去 sit 提 pr 好了，或者列出来你觉得有问题的地方

**Comment by chenshuai2144** [comment]
> 隐藏菜单栏后，控制台报内存溢出

这个不是内存泄露，是组件解除挂在了还在设置 state

**Comment by RedScarf007** [comment]
> > 隐藏菜单栏后，控制台报内存溢出
> 
> 这个不是内存泄露，是组件解除挂在了还在设置 state, 看样子像是 resizeobsever 的问题

那么，亲爱的朋友，我应该如何去修复他，或者说是我的代码违反了某种规范，或者是我的react代码错误

**Comment by funny99** [comment]
> > > 隐藏菜单栏后，控制台报内存溢出
> > 
> > 
> > 这个不是内存泄露，是组件解除挂在了还在设置 state, 看样子像是 resizeobsever 的问题
> 
> 那么，亲爱的朋友，我应该如何去修复他，或者说是我的代码违反了某种规范，或者是我的react代码错误

检查一下是不是在异步请求后执行了setState的操作，这个问题很常见，组件卸载后，异步请求返回响应了，这时候去setState就会这个错误。

**Comment by wywppkd** [comment]
> > 隐藏菜单栏后，控制台报内存溢出
> 
> 这个不是内存泄露，是组件解除挂在了还在设置 state, 看样子像是 resizeobsever 的问题

hello, 在 Pro5 中我也遇到同样的问题了, 目前解决办法是

```js
useEffect(() => {
  let mounted = true;
  (async () => {
    const res = await getDataById({ id });
    const list = res?.data || [];
    if (mounted) {
      setList(list);
    }
  })();

  return () => {
    console.log('组件卸载...');
    mounted = false;
  };
}, [id]);
```

不知道后期迭代有没有办法解决这个问题: 设置 `layout:false` 的路由组件在渲染过程中会发生卸载
