### ISSUE TITLE
🐛[BUG]从服务器请求菜单文档提供方法菜单不显示

### ISSUE THREAD

**Issue by lcosmos** [ant-design/ant-design-pro#7530]
### 🐛 bug 描述

[文档地址](https://pro.ant.design/docs/router-and-nav-cn#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95)

今天删除了node_modules重新拉取新的包后，按上述文档地址切换成动态路由后菜单不显示。

### 📷 复现步骤

使用最新的antd pro，按找文档方式修改服务器请求菜单，菜单不显示。

### 🏞 期望结果

菜单能够正常显示

### © 版本信息

- Ant Design Pro 版本: 4.2.2
- umi 版本：3.2.4
- 浏览器环境：Chrome 86.0.4240.111（正式版本）
- 开发环境  mac OS

### 🚑 其他信息

无

**Comment by lcosmos** [comment]
@ant-design/pro-layout 6.5.5没问题哦
6.5.6有问题 目测下面这段代码问题
![image](https://user-images.githubusercontent.com/20968285/97281503-90d5b980-1878-11eb-97a9-57bb93c1ce8f.png)

**Comment by xiaofsu** [comment]
+1

**Comment by chenshuai2144** [comment]
模仿这个来 
https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu

通过 loading 来让layout 重新渲染，不然会有性能问题
```
<ProLayout
        style={{
          height: 400,
          border: '1px solid #ddd',
        }}
        menu={{
          loading,
        }}
        location={{
          pathname: '/welcome/welcome',
        }}
        menuDataRender={() => menuData}
      >
        <PageContainer content="欢迎使用">Hello World</PageContainer>
      </ProLayout>
```

**Comment by wxuonline** [comment]
> 模仿这个来
> https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu
> 
> 通过 loading 来让layout 重新渲染，不然会有性能问题
> 
> ```
>      <ProLayout
>         style={{
>           height: 400,
>           border: '1px solid #ddd',
>         }}
>         menu={{
>           loading,
>         }}
>         location={{
>           pathname: '/welcome/welcome',
>         }}
>         menuDataRender={() => menuData}
>       >
>         <PageContainer content="欢迎使用">Hello World</PageContainer>
>       </ProLayout>
> ```

pro-layout:  6.5.11 
```
const [loading, setLoading] = useState(true);

<ProLayout
        menu={{ loading }}
        menuDataRender={() => menuDataRender(menus)}
      >
      </ProLayout>
```
没有显示loading动画，
develop环境正常显示菜单，打包后生产环境，第一次登陆跳转页面时可以显示菜单，F5刷新后就不显示菜单了

**Comment by wxuonline** [comment]
menu={{ loading }}
会被 {...settings} 中的menu覆盖，找半天才找到问题...

**Comment by daifuyang** [comment]
这个问题我之前解决了！有两个坑！

**Comment by daifuyang** [comment]
> 这个问题我之前解决了！有两个坑！
第一个，删除config/defaultSettings.js中的menu

**Comment by daifuyang** [comment]
这个问题我之前解决了！有两个坑！
第一个，删除config/defaultSettings.js中的menu

**Comment by daifuyang** [comment]
这个问题我之前解决了！有两个坑！
第一步：删除config/defaultSettings.js中的menu，第二步menu={{ loading }}

**Comment by lee-li** [comment]
@daifuyang 👍  确实！

**Comment by johnstevin** [comment]
> menu={{ loading }}
> 会被 {...settings} 中的menu覆盖，找半天才找到问题...

这个问题我找了整一天，才解决，全是泪啊！
