### ISSUE TITLE
在移动端下会出现2个logo🐛[BUG]

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#7531]
### 🐛 bug 描述
最近开始测试的时候发现在移动端显示LOGO会出现2个，并且菜单栏不在了。
1、我当时过从新安装一个新的antd Pro 版本 更换了config文件里面的config.ts、defaultSettings.ts 都没出现当前的问题

### © 版本信息

- Ant Design Pro 版本:  5.0.0-alpha.0
- umi 版本  "^3.1.0",
- 浏览器环境 Chrome
- 开发环境  mac

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23183393/97287624-c5993f00-187f-11eb-99e2-ac1baad67e7f.png)
![image](https://user-images.githubusercontent.com/23183393/97380132-595f1f80-1901-11eb-9e71-60a0de1449b3.png)

**Comment by chenshuai2144** [comment]
样式覆盖了吧，是不是安装了多份 antd ，或者 多份 `@ant-design/pro-layout`

**Comment by xyy7260** [comment]
@chenshuai2144 
  "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "6.0.0-3",
    "@ant-design/pro-table": "^2.2.0",
    "@progress/kendo-theme-default": "^4.19.0",
    "@progress/kendo-ui": "^2020.2.513",
    "@rjsf/antd": "^2.2.1",
    "@rjsf/core": "^2.0.2",
    "ajv-i18n": "^3.5.0",
    "antd": "^4.0.0",
    "antd-theme-generator": "^1.2.4",
    "axios": "^0.19.2",
    "bootstrap": "^3.4.1",
    "compression-webpack-plugin": "^4.0.0",
    "dayjs": "^1.8.30",
    "echarts": "^4.8.0",
    "echarts-for-react": "^2.0.16",
    "lodash": "^4.17.15",
    "moment": "^2.25.3",
    "node-sass": "^4.14.1",
    "omit.js": "^1.0.2",
    "qs": "^6.9.0",
    "rc-calendar": "^9.15.11",
    "react": "^16.8.6",
    "react-countup": "^4.3.3",
    "react-dom": "^16.8.6",
    "react-highlight-words": "^0.16.0",
    "react-json-tree": "^0.11.2",
    "sass-loader": "^8.0.2",
    "searchkit": "^2.4.1",
    "searchkit-daterangefilter": "0.0.2",
    "umi": "^3.1.0",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },

难道和rjsf/antd 有关吗？  我点不确定

**Comment by chenshuai2144** [comment]
npm ls一下 有一个logo 应该display none

**Comment by xyy7260** [comment]
@chenshuai2144    ls 一下太长了，  是否需要从新清楚缓存安装一次呢

**Comment by chenshuai2144** [comment]
Ls后面可以加包名的

**Comment by xyy7260** [comment]
@chenshuai2144  这样哇
![image](https://user-images.githubusercontent.com/23183393/97855148-50bd7d80-1d35-11eb-8a32-65328be6749c.png)

**Comment by chenshuai2144** [comment]
升级到正式版本吧 你用了测试用的版本

**Comment by xyy7260** [comment]
@chenshuai2144  好
