### ISSUE TITLE
- `config/config.ts` 中增加 `locale: {}`

### ISSUE THREAD

**Issue by xiaojun29** [ant-design/ant-design-pro#7532]
- `config/config.ts` 中增加 `locale: {}`
- 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
- 重启服务

当前版本 `"umi": "^3.2.22"`

_Originally posted by @wangfupeng1988 in https://github.com/ant-design/ant-design-pro/issues/7321#issuecomment-717091618_

我是在Windows10 64位中使用的是UmiJS版本为`"umi": "^3.2.24",`
还是有同样的问题

**Comment by aLIEzsss4** [comment]
解决了吗

**Comment by F-loat** [comment]
`src/pages/user/login/index.tsx` 这个文件里的国际化内容需要手动删一下的
