### ISSUE TITLE
🐛[BUG] V5 proxy problem

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#7533]
### 🐛 bug 描述
Hello, the following settings do not work in the proxy file after the application is published.

When I send any request from the application, it does not redirect to my api application running in the subdomain. Always returns origin domain without api prefix like **'mydomain.com/api'**, but I want to that **'api.mydomain.com/api'**.

```
export default {
  dev: {
    '/api': {
      target: 'https://api.mydomain.com/',
      changeOrigin: true,
      //secure: false,
      pathRewrite: { '^/api' : '' },
    },
  },
  test: {
    '/api': {
      target: 'https://api.mydomain.com/',
      changeOrigin: true,
      //secure: false,
      pathRewrite: { '^/api' : '' },
    },
  },
  pre: {
    '/api': {
      target: 'https://api.mydomain.com/',
      changeOrigin: true,
      //secure: false,
      pathRewrite: { '^/api' : '' },
    },
  },
};
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
look here https://pro.ant.design/blog/proxy

proxy do not change your url. it's a transponder running in the background
