### ISSUE TITLE
🐛[BUG] v5 config.ts中routes配置layout属性生成的class名称异常

### ISSUE THREAD

**Issue by xiyanZ** [ant-design/ant-design-pro#7534]
### 🐛 bug 描述

生成class为
![image](https://user-images.githubusercontent.com/36783777/97538816-fef6b980-19fb-11eb-9489-2ba0183ed92f.png)
config.ts配置为
![image](https://user-images.githubusercontent.com/36783777/97538838-0918b800-19fc-11eb-84ba-e4b941e9720a.png)

### © 版本信息
- @ant-design/pro-cli 版本: [2.0.2]
- @ant-design/pro-layout  版本: [6.4.19]
- antd 版本: [4.7.3]
- umi 版本: [3.2.0]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/pro-components/pull/872
