### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by sichaofei** [ant-design/ant-design-pro#7537]
### 🐛 bug 描述

谷歌浏览器  打开react官网  ant design pro 屏幕出现花屏状态  包括我们用你们框架开发的后台  显示问题

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  
- umi 版本
- 浏览器环境  谷歌
- 开发环境 [e.g. mac OS]  macos

### 🚑 其他信息

<img width="596" alt="企业微信截图_1ff122c9-336c-45c9-b906-b442820f34a3" src="https://user-images.githubusercontent.com/36755630/97677143-c1ae2c80-1acc-11eb-98c9-85dba83b2bba.png">
<img width="1617" alt="企业微信截图_126bd1a5-edb1-4a4b-914e-ac4beff441e9" src="https://user-images.githubusercontent.com/36755630/97677178-d38fcf80-1acc-11eb-9ac6-200bed0b1e3a.png">

**Comment by zombieJ** [comment]
看起来是显卡问题……
