### ISSUE TITLE
🐛[BUG] 项目初始化后umi ui气泡不显示

### ISSUE THREAD

**Issue by OnePieceLiu** [ant-design/ant-design-pro#7539]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by OnePieceLiu** [comment]
是"start": "umi dev",模式 但是umi ui气泡没有显示

**Comment by tigerxiongj** [comment]
疼，蛋

**Comment by JarnTang** [comment]
项目目录下执行命令：`yarn add @umijs/preset-ui -D`

再运行项目就可以看见umi ui的气泡了 @OnePieceLiu

**Comment by OnePieceLiu** [comment]
> 项目目录下执行命令：`yarn add @umijs/preset-ui -D`
> 
> 再运行项目就可以看见umi ui的气泡了@OnePieceLiu

谢谢

**Comment by alecui** [comment]
加完了用umi模块化生成页面以后，再次重启直接报错。

**Comment by waxeia** [comment]
> 项目目录下执行命令：`yarn add @umijs/preset-ui -D`
> 
> 再运行项目就可以看见umi ui的气泡了 @OnePieceLiu

我的问题是：执行完依赖安装的指令yarn add @umijs/preset-ui -D以后，重启项目，依然无法显示小气泡，该怎么办呢？
