### ISSUE TITLE
🐛[BUG] eslint  Parsing error: "parserOptions.project"

### ISSUE THREAD

**Issue by clarkchen** [ant-design/ant-design-pro#7540]
### 🐛 bug 描述

yarn create umi 之后创建的标准模板，eslint报错
mock文件夹

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/1352085/97769042-9b3ad080-1b62-11eb-831b-6b67dcd1c44b.png)

1. yarn create umi

2. 选择方法：
    2.1. ant-design-pro
    2.2 Pro V4
    2.3 TypeScript
    2.4 simple
    2.5 antd@4

3. yarn install 

4. yarn add eslint

5. ./node_modules/eslint/bin/eslint.js .

### 🏞 期望结果
期望：
无Error

实际：
![image](https://user-images.githubusercontent.com/1352085/97769158-87439e80-1b63-11eb-9d90-7de1a31b7837.png)

### 💻 复现代码

[bug-antd-demo](https://github.com/clarkchen/bug-antd-demo)

### © 版本信息

- Ant Design Pro 版本: 4.2.2
- umi 版本: 3.2.24
- 浏览器环境: chrome
- 开发环境  mac OS 10.15.7

**Comment by zhanglinge** [comment]
我遇到了类似的问题，git 提交时 eslint 不过。
![image](https://user-images.githubusercontent.com/4507011/97779954-81c67280-1bbc-11eb-86de-cefffc0396b5.png)

**Comment by chenshuai2144** [comment]
在tsconfig中把文件加进去

**Comment by clarkchen** [comment]
@chenshuai2144 , 谢谢，的确好使
