### ISSUE TITLE
👑 [需求] 初始化时提供无国际化的选项

### ISSUE THREAD

**Issue by Mu-xue** [ant-design/ant-design-pro#7546]
### 🥰 需求描述
`i18n-remove` 并没有完全移除国际化的东西（下拉选项还是存在，翻译的文件还是存在等），其实对大部分Admin中后台系统，都只需要一种语言，希望antd团队能够提供在create-umi初始化时完全移除国际化的版本。

**Comment by darkfiredarkhalo** [comment]
超级赞同, 国内使用就总是变英文,搞得焦头烂额的

**Comment by FlavourSh4T** [comment]
一直觉得需要这个功能

**Comment by chenshuai2144** [comment]
写起来还挺麻烦。因为 antd 是默认英文的

**Comment by Mu-xue** [comment]
@chenshuai2144 默认英文我觉得可以的，我的诉求在于国际化内容没有完全移除，初始化就被迫要准备中英文的翻译，不然就要自己再去删除文件和修改配置

**Comment by Kaier33** [comment]
确实.. 希望能在创建项目的时候 提供一个没有国际化的中文模板

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/i18n#%E5%88%A0%E9%99%A4%E5%85%A8%E7%90%83%E5%8C%96

提供了完善的删除国际化能力
