### ISSUE TITLE
🐛[BUG]Uncaught TypeError: Cannot read property 'getItem' of null

### ISSUE THREAD

**Issue by RedScarf007** [ant-design/ant-design-pro#7547]
### 🐛 bug 描述
在安卓7.0的浏览器中报错`Uncaught TypeError: Cannot read property 'getItem' of null`新起的项目，并没有用到session之类的东西。

![af6ab4654ceb8479ef722ce4afd3c50](https://user-images.githubusercontent.com/28618983/97964263-7315d080-1df3-11eb-900d-1ce5d8f73d06.jpg)
![fc21d6ab01ef251eff099f8f01f127a](https://user-images.githubusercontent.com/28618983/97964270-75782a80-1df3-11eb-8c9d-7c29f8398226.jpg)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]5.0
- umi 版本^3.2.14
- 浏览器环境 安卓7.0浏览器
- 开发环境 [e.g. mac OS] window10

**Comment by chenshuai2144** [comment]
估计是国际化插件的 localStorage导致的，andorid 7 的浏览器也太老了。即使能跑起来 localStorage ，别的css样式也全挂了

**Comment by RedScarf007** [comment]
> 估计是国际化插件的 localStorage导致的，可以关掉试试
> 
> andorid 7 的浏览器也太老了。即使能跑起来 localStorage ，别的css样式也全挂了

咋关哦，没用上什么高端的css

**Comment by chenshuai2144** [comment]
@RedScarf007 `config/config.ts`  中配置  locale:false ,不只是高端css，是 flex 都不能用的，还有一大票的 js api。
比兼容ie6 难度低不到哪里
