### ISSUE TITLE
🧐[问题]Antd Pro v5 打包文件过大，请问如何优化

### ISSUE THREAD

**Issue by SuperBugs** [ant-design/ant-design-pro#7550]
### 🧐 问题描述

Ant Design Prov5 打包后文件过大，请问如何优化

### 💻 示例代码

![image](https://user-images.githubusercontent.com/24450930/98054729-b8c7ad00-1e76-11eb-9c8e-898271670615.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24450930/98054788-e280d400-1e76-11eb-9050-a12d8c0b5f5f.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/guide/boost-compile-speed#%E6%9F%A5%E7%9C%8B%E5%8C%85%E7%BB%93%E6%9E%84

看这里，尽量改用cdn把
