### ISSUE TITLE
🧐[问题]想请问adp5，资源默认输出路径有哪些（dist根目录、static、public拷贝过来的）

### ISSUE THREAD

**Issue by zhangtang1** [ant-design/ant-design-pro#7552]
### 🧐 问题描述
一个现象：js加载的图片资源、css引用的字体资源，打包后出现在dist/static文件夹内，而其他js、css等直接在dist文件夹内，adp、umi相关文档都没查到static相关，想问下哪些资源会被打包进dist内，哪些会打包进dist/static内

最后，感谢antd团队的付出，献上花花❀❀

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/docs/assets-image#%E5%9B%BE%E7%89%87%E8%B7%AF%E5%BE%84%E9%97%AE%E9%A2%98

看这里，static 是 import 的但是不能被内置为base64 的文件， dist内的都是 public 中的文件。用于存放 icon， cname 等代码。

**Comment by zhangtang1** [comment]
> https://umijs.org/zh-CN/docs/assets-image#%E5%9B%BE%E7%89%87%E8%B7%AF%E5%BE%84%E9%97%AE%E9%A2%98
> 
> 看这里，static 是 import 的但是不能被内置为base64 的文件， dist内的都是 public 中的文件。用于存放 icon， cname 等需要放在根目录的静态资源。

三克油❀❀
