### ISSUE TITLE
🧐[问题] 请求数据问题

### ISSUE THREAD

**Issue by matianhe** [ant-design/ant-design-pro#7554]
### 🧐 问题描述

如何获取接口数据？通过文档实现不知道对不对。
data 没有数据，正规获取数据流程是什么样呢。
![image](https://user-images.githubusercontent.com/24929062/98095972-2e0e9e80-1ec6-11eb-9f75-07c287154f95.png)

### 💻 示例代码

export async function getSpiderList() {
    return request('/api/spiderlist');
}

const { data, loading } = useRequest(()=>{getSpiderList()})

**Comment by chenshuai2144** [comment]
哥哥 记得 return呀

**Comment by matianhe** [comment]
> 哥哥 记得 return呀

哈哈，大哥大哥Sorry打扰了，确实没return。
