### ISSUE TITLE
🧐[问题]antd pro 引入qiankun后布局分层

### ISSUE THREAD

**Issue by AqingCyan** [ant-design/ant-design-pro#7556]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/32301956/98112764-9fa61700-1edd-11eb-915c-4c1581e8cfd7.png)

### 💻 示例代码
https://github.com/AqingCyan/antd-pro-qiankun

### 🚑 其他信息

有看到别的issue说是样式互相影响，但是把基座应用的id从root改为别的还是如此

**Comment by blueju** [comment]
@AqingCyan 
为什么关闭问题，我也遇到了这个问题

**Comment by AqingCyan** [comment]
@blueju  你的邮件已回复，其实就是基座应用和子应用的根节点id都是root造成的，解决该冲突即可
