### ISSUE TITLE
🧐[Detect Mobile with Antd Pro V5]

### ISSUE THREAD

**Issue by takeitforwardsolutions** [ant-design/ant-design-pro#7557]
Detect if Mobile with Antd Pro V5

Would like to know if Antd Pro has available a Mobile property or how others have handle it inline with Antd Pro; as in IsMobile or something similar to that. Within in the tsx I want to render certain component if user is loading on Mobile device. Solution to problem isn't viable via Css or less etc, I need to do it inline.

Thank You in advance for any suggestions or references.

**Comment by chenshuai2144** [comment]
I usually use this

https://www.npmjs.com/package/react-media

**Comment by takeitforwardsolutions** [comment]
Thank You, I'll dive into that; I ended up creating something similar to this locally. But no need to rework if it does the same, I'll take a look.   Dino Don
