### ISSUE TITLE
🧐 Cannot find module '@umijs/preset-ant-design-pro' from '/opt/build/repo' on netlify! HELP PLEASE!!!

### ISSUE THREAD

**Issue by jvcjunior** [ant-design/ant-design-pro#7558]
### 🧐 问题描述

I'm trying to deploy my ant-design-pro app into Netlify and this error is happening:

Cannot find module '@umijs/preset-ant-design-pro' from '/opt/build/repo' 

### 💻 示例代码
<img width="1225" alt="Screen Shot 2020-11-04 at 15 13 08" src="https://user-images.githubusercontent.com/397790/98152303-41af0a80-1eb0-11eb-84f9-23b7adffc135.png">

<img width="1315" alt="Screen Shot 2020-11-04 at 15 16 25" src="https://user-images.githubusercontent.com/397790/98152574-b6824480-1eb0-11eb-89ee-752e0ad0a125.png">

 HELP PLEASE!!!

**Comment by flygo6** [comment]
兄弟，解决了吗？ 我今天也遇到了。

**Comment by flygo6** [comment]
![image](https://user-images.githubusercontent.com/65991901/105144871-d54fb900-5b38-11eb-8423-3b77b1552975.png)

**Comment by chenshuai2144** [comment]
你这个问题重装一下依赖就好了吧

**Comment by jvcjunior** [comment]
If I remember correctly, @flygo6 check if @umijs/preset-ant-design-pro is inside your dependencies and not on devDependencies.

**Comment by lcysgsg** [comment]
>  Use this flag to instruct Yarn to ignore NODE_ENV and take its production-or-not status from this flag instead.
> https://classic.yarnpkg.com/en/docs/cli/install/

`RUN yarn install  --production=false` can resolve. This spent most of the day, make my day grey...
