### ISSUE TITLE
Ant Design Pro 如何与NuxtJS SSR框架整合？

### ISSUE THREAD

**Issue by ye21st** [ant-design/ant-design-pro#7559]
### 🧐 问题描述

我想使用NuxtJS SSR框架，我怎么将Ant Design Pro进行整合处理？请问有大佬实现的吗？或者是可以提供一个模板之类的出来吗？

**Comment by chenshuai2144** [comment]
umi 有自己的 ssr, 接入另外的可能成本很高
https://umijs.org/zh-CN/docs/ssr
