### ISSUE TITLE
ant design pro v4如何动态修改ant design组件主题颜色

### ISSUE THREAD

**Issue by chneqiang** [ant-design/ant-design-pro#7560]
我参考了官网文档步骤去做，umi3一直报错

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96
这里有个视频

**Comment by chneqiang** [comment]
> https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96
> 这里有个视频

你好，视频中提到的主题切换是固定的，我在页面放一个切换主题的功能，如何实现？

**Comment by chneqiang** [comment]
> https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96
> 这里有个视频

我的是ant-design-pro-v4版本，"umi": "^3.2.14"，我参照了v4文档动态主题报错无法实现
![image](https://user-images.githubusercontent.com/49935844/98529455-98558380-22b8-11eb-8b53-acc49df6bebc.png)

**Comment by chenshuai2144** [comment]
提供一个重现

**Comment by peiwen-pts** [comment]
> > https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96
> > 这里有个视频
> 
> 我的是ant-design-pro-v4版本，"umi": "^3.2.14"，我参照了v4文档动态主题报错无法实现
> ![image](https://user-images.githubusercontent.com/49935844/98529455-98558380-22b8-11eb-8b53-acc49df6bebc.png)

请问这个问题有解决方法了么？同问啊~~ 谢谢

**Comment by LilianShi** [comment]
请问楼主实现了吗？
