### ISSUE TITLE
怎么去除刷新的时候出来的页面，如下图🧐[问题]

### ISSUE THREAD

**Issue by frontendWangqun** [ant-design/ant-design-pro#7561]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/43572671/98192325-cdc73d80-1f55-11eb-92b3-1099f017975f.png)

详细地描述问题，让大家都能理解
-->

**Comment by yuntuzhuiyi** [comment]
调整这个src/pages/document.ejs

**Comment by frontendWangqun** [comment]
> 调整这个src/pages/document.ejs

好嘞，谢谢哈
