### ISSUE TITLE
👑 [需求]   在ProTable的option里面配置setting

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7564]
### 🥰 需求描述

我们现在的项目需要在table里面对表格列做显示隐藏，所以使用到了setting这个属性，
但是现在需要在setting发现变化的以后去获取最新的table表头数据进行打印和导出，
但是现在setting这个属性就支持boolean。
没办法在发生了变化以后获取最新的columns；
所以我希望能加一个参数，用来获取最新的表格数据和最新的表头用来进行打印和导出；

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/45235142/98239228-9632b280-1fa2-11eb-9bb9-29251996f7b1.png)
![image](https://user-images.githubusercontent.com/45235142/98239271-a3e83800-1fa2-11eb-9a6e-a1868a89e7d2.png)
比如下面这个图，原来的表格有序号和产量，但是现在被我隐藏；
然后我想获取最新的表头，但是获取不到。
能不能请求大佬解决一下

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table/#%E5%8F%97%E6%8E%A7%E7%9A%84%E5%88%97%E6%98%BE%E7%A4%BA%E9%9A%90%E8%97%8F

看看这个demo ，提供了  


columnsStateMap | columns 的状态枚举 | {[key: string]: { show:boolean, fixed: "right" \| "left"} } | -
-- | -- | -- | --
onColumnsStateChange | columns 状态发生改变 | (props: {[key: string]: { show:boolean, fixed: "right" \| "left"} }) => void | -
