### ISSUE TITLE
🐛[BUG] 更新 ⚡️ performance: open esbuild 后 含有动态路由 无法build

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#7565]
### 🐛 bug 描述

更新后 含有动态路由 无法build

https://github.com/ant-design/ant-design-pro/commit/f68066a91e2ddb53ed821ff2b770bac9c90f8989

````
[Error: EINVAL: invalid argument, mkdir 'D:\Web\console\dist\shop\goods\:id\edit'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'D:\\Web\\console\\dist\\shop\\goods\\[:id]\\edit'
}
build failed
````

**Comment by chenshuai2144** [comment]
这个不是esbuild 是exportStatic导致的

**Comment by kaoding** [comment]
https://github.com/umijs/umi/issues/5633

**Comment by ycjcl868** [comment]
> 这个不是esbuild 是exportStatic导致的

与 esbuild 无关 https://github.com/ant-design/ant-design-pro/issues/7638
