### ISSUE TITLE
🧐[问题] 一直有奇怪的报错 Change::: false

### ISSUE THREAD

**Issue by Choi-Jungwoo** [ant-design/ant-design-pro#7567]
### 🧐 问题描述

一直有奇怪的报错 Change::: false，只要触发左边 menu hover 的时候，在 console 就会出现 Change::: false ，Change::: true

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/26923066/98392617-2f40f680-2093-11eb-892b-74480cf5d8c8.png)

**Comment by wlxscn** [comment]
我也遇到这个问题，看起来是log日志没删除
![image](https://user-images.githubusercontent.com/12622564/98430449-3f36f580-20e8-11eb-811d-b55ccc219ce8.png)
