### ISSUE TITLE
🐛 v4 升级到 v5后网络请求错误会闪屏

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#7568]
### 🐛 bug 描述
后台success为false报错误的时候页面会白屏,输出的时候组件也会渲染

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 3.2.17
- 浏览器环境 谷歌浏览器
- 开发环境 win

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/34082148/98430064-ce8ed980-20e5-11eb-984a-29d50a51b818.png)
app ts
![image](https://user-images.githubusercontent.com/34082148/98430071-db133200-20e5-11eb-9fcd-b5de52c479b4.png)

**Comment by 569202812** [comment]
测试了是```useRequest```的问题，使用了useRequest请求后组件会渲染一次， 能帮忙反馈到```ahook```的同学吗

**Comment by 569202812** [comment]
> 测试了是`useRequest`的问题，使用了useRequest请求后组件会渲染一次， 能帮忙反馈到`ahook`的同学吗

@chenshuai2144

**Comment by chenshuai2144** [comment]
去ahooks提issue好了
