### ISSUE TITLE
🧐[问题]ant pro v5自定义layout该如何使用？

### ISSUE THREAD

**Issue by 985563349** [ant-design/ant-design-pro#7569]
### 🧐 问题描述
按照antd pro v5文档自定义layout无法正常运行程序。
antd pro v5配置文档：
![image](https://user-images.githubusercontent.com/36779802/98433221-f5f2a000-20ff-11eb-9504-2969ba475a63.png)

umi 3配置文档：
![image](https://user-images.githubusercontent.com/36779802/98433228-0571e900-2100-11eb-8fc4-c20dfbb0db0c.png)

配置方式不一致，我该如何使用？

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/layout-cn#%E8%87%AA%E5%AE%9A%E4%B9%89-layout

按照这个来，两种都可以，但是umi的那种用法会导致没有代码提示

**Comment by Eliot00** [comment]
v6是不是又改行为了？
