### ISSUE TITLE
路由嵌套问题

### ISSUE THREAD

**Issue by accaolei** [ant-design/ant-design-pro#757]
router.js中这样嵌套路由不工作，请指点。
![image](https://user-images.githubusercontent.com/1756074/35091647-13518076-fc78-11e7-9cda-4a890fa15a70.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/router-and-nav-cn#%E5%B8%A6%E5%8F%82%E6%95%B0%E7%9A%84%E8%B7%AF%E7%94%B1/%E8%8F%9C%E5%8D%95
