### ISSUE TITLE
🐛[BUG]没有该权限的用户可以通过地址栏跳入

### ISSUE THREAD

**Issue by Anonymity94** [ant-design/ant-design-pro#7571]
### 🐛 bug 描述
用户可以通过地址栏输入 url 的方式进去到一个没有权限的页面，显示为空白页面？没有403无权限的提示。

### 📷 复现步骤
1. 克隆 `ant-design-pro`
2. `yarn`
3. `npm run fetch:blocks`
4. 随便修改 `config/config.ts` 中的一个菜单的权限为`authority: ['admin']`。例如：

```js
{
  name: 'editor',
  icon: 'highlight',
  path: '/editor',
  authority: ['admin'],
  routes: [
    // balabala
  ],
}
```

5. 使用 `guest` 访客登录
6. 浏览器访问 `http://localhost:<port>/editor`
7. 出现空白页面
![image](https://user-images.githubusercontent.com/13148447/98434637-95b62b00-210c-11eb-8540-ea47250d0dba.png)

### 原因

1. `CheckPermissions.tsx` L29的条件判定，没有权限时默认可以被访问到。
```js
  // 没有判定权限.默认查看所有
  // Retirement authority, return target;
  if (!authority) {
    return target;
  }
```

2. `BasicLayout.tsx`中在去页面地址权限的时候，无权限的地址已经被过滤掉了，取不到权限然后手动赋值了一个 `undefined`
```js
  // get children authority
  const authorized = useMemo(
    () =>
      getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
        authority: undefined,
      },
    [location.pathname],
  );
```

### 解决办法

<b>仅供参考😄</b>

在计算`authorized`时，给赋值一个特殊的权限（别和你的权限系统中的权限相同即可），例如：
```js
  // get children authority
  const authorized = useMemo(
    () =>
      getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
        authority: 'NO_AUTH',
      },
    [location.pathname],
  );
```

**Comment by Anonymity94** [comment]
新版本 [4.2.1](https://github.com/ant-design/ant-design-pro/tree/v4.2.1)已经解决此问题~^_^

**Comment by fenglijunnb** [comment]
@Anonymity94 大哥， 你确定是好了吗，可我下载官方的都有问题啊

**Comment by Anonymity94** [comment]
@fenglijunnb 可以直接查看 [v4.2.1](https://github.com/ant-design/ant-design-pro/tree/v4.2.1) 下的 2 个文件：[BasicLayout.tsx](https://github.com/ant-design/ant-design-pro/blob/v4.2.1/src/layouts/BasicLayout.tsx#L121)、[utils.ts](https://github.com/ant-design/ant-design-pro/blob/v4.2.1/src/utils/utils.ts#L33)


我参考修改后，并无问题。

**Comment by tom-chanafanghua** [comment]
如果undefined改成任意不匹配的字符串后，当你访问 / 的时候  不会出现403吗？我这边出现403了。。

**Comment by fenglijunnb** [comment]
@Anonymity94 那哥个大哥，如何能直接下载4.2.1版本的后台啊
我现在按照官方的文档来的话是只能还是4.0

**Comment by tom-chanafanghua** [comment]
> @Anonymity94 那哥个大哥，如何能直接下载4.2.1版本的后台啊
> 我现在按照官方的文档来的话是只能还是4.0

git clone https://github.com/ant-design/ant-design-pro.git  直接拉取

**Comment by fenglijunnb** [comment]
@tom-chanafanghua 那这样拉取的不就是ts 版本吗，我要的是jsx版本

**Comment by Anonymity94** [comment]
> 如果undefined改成任意不匹配的字符串后，当你访问 / 的时候 不会出现403吗？我这边出现403了。。

@tom-chanafanghua 会的。所以这个方法并不好。参考官方的吧。^_^

**Comment by tom-chanafanghua** [comment]
> > 如果undefined改成任意不匹配的字符串后，当你访问 / 的时候 不会出现403吗？我这边出现403了。。
> 
> @tom-chanafanghua 会的。所以这个方法并不好。参考官方的吧。^_^

这个4.2.1版本的 我拉取了 还是没有控制好权限呀  依旧可以通过地址栏进去呢

**Comment by Anonymity94** [comment]
@tom-chanafanghua 那可以继续向官方提 Issuse 了。我参考官方的处理方式，简单的自测了下没什么大问题。等我后面再测到这一块的时候，给提个 PR
