### ISSUE TITLE
动态从后台获取菜单数据；一级菜单国际化时都带上了dashboard

### ISSUE THREAD

**Issue by changjiangquan** [ant-design/ant-design-pro#7572]
### 💻 示例代码
 'GET /api/menus' : [

    {
      path: '/dashboard',
      name: 'dashboard',
      icon: 'dashboard',

      routes: [
        {
          name: 'analysis',
          icon: 'smile',
          path: '/dashboard/analysis',
          component: './dashboard/analysis',
        },
        {
          name: 'monitor',
          icon: 'smile',
          path: '/dashboard/monitor',
          component: './dashboard/monitor',
        },
        {
          name: 'workplace',
          icon: 'smile',
          path: '/dashboard/workplace',
          component: './dashboard/workplace',
        },
      ],

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/36941570/98436044-052f1900-2113-11eb-8f61-fcd49a141e28.png)

**Comment by chenshuai2144** [comment]
你没有设置 icon 插件导致的。 
https://pro.ant.design/blog/antd-4.0-cn#-pro-%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by Ray-56** [comment]
@chenshuai2144 umi3.x 文档中将这个插件移除了
