### ISSUE TITLE
🧐[问题]退出账号，换一个菜单权限不一样的账号登录，菜单不会刷新。

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/ant-design-pro#7576]
### 🧐 问题描述

退出账号，换一个菜单权限不一样的账号登录，菜单不会刷新。
需要F5刷新后，菜单才会更新。

从access中看，权限其实已经更新了，只是页面没有变化。

**Comment by chenshuai2144** [comment]
更新一下依赖。 
在这里修掉了 https://github.com/umijs/plugins/pull/433

**Comment by waylon-edmodo** [comment]
酷!

**Comment by ITyaoji** [comment]
> 酷!

所以到底升级哪个依赖？
