### ISSUE TITLE
🧐[问题]针对组件文件夹的规范问题

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design-pro#7577]
### 🧐 问题描述

我在ant-design-pro项目中的pages中发现了两个组件，一个是ListTableList，一个是user/login。为了使我开发的项目更加规范，这边自定义的组件正常应该是如何命名的呢？求指教。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19951467/98493178-c3b67f00-2274-11eb-97d2-a980e7f4273f.png)

**Comment by daifuyang** [comment]
非常疑惑这边组件的命名规范，是不是组件都应该大写，有相应的规范文档嘛？

**Comment by chenshuai2144** [comment]
页面代码结构推荐


为了让项目代码组织更加规范，让开发能够更方便的定位到相关页面组件代码，我们定义了一套规范，该规范当前只作为推荐的指导，并非强制。



src
├── components
└── pages
    ├── Welcome        // 路由组件下不应该再包含其他路由组件，基于这个约定就能清楚的区分路由组件和非路由组件了
    |   ├── components // 对于复杂的页面可以再自己做更深层次的组织，但建议不要超过三层
    |   ├── Form.tsx
    |   ├── index.tsx  // 页面组件的代码
    |   └── index.less // 页面样式
    ├── Order          // 路由组件下不应该再包含其他路由组件，基于这个约定就能清楚的区分路由组件和非路由组件了
    |   ├── index.tsx
    |   └── index.less
    ├── user           // 一系列页面推荐通过小写的单一字母做 group 目录
    |   ├── components // group 下公用的组件集合
    |   ├── Login      // group 下的页面 Login
    |   ├── Register   // group 下的页面 Register
    |   └── util.ts    // 这里可以有一些共用方法之类，不做推荐和约束，看业务场景自行做组织
    └── *              // 其它页面组件代码


所有路由组件（会配置在路由配置中的组件）我们推荐以大驼峰命名打平到 pages 下面第一级（复杂的项目可以增加 group 层级，在 group 下放置 pages）。不建议在路由组件内部再嵌套路由组件 - 不方便分辨一个组件是否是路由组件，而且不方便快速从全局定位到路由组件。


项目中的位置有一些历史因素，我们推荐是这样的

**Comment by daifuyang** [comment]
感谢陈老师的解答。谢谢。大赞

**Comment by blueju** [comment]
> 页面代码结构推荐
> 
> 为了让项目代码组织更加规范，让开发能够更方便的定位到相关页面组件代码，我们定义了一套规范，该规范当前只作为推荐的指导，并非强制。
> 
> ```
> src
> ├── components
> └── pages
>     ├── Welcome        // 路由组件下不应该再包含其他路由组件，基于这个约定就能清楚的区分路由组件和非路由组件了
>     |   ├── components // 对于复杂的页面可以再自己做更深层次的组织，但建议不要超过三层
>     |   ├── Form.tsx
>     |   ├── index.tsx  // 页面组件的代码
>     |   └── index.less // 页面样式
>     ├── Order          // 路由组件下不应该再包含其他路由组件，基于这个约定就能清楚的区分路由组件和非路由组件了
>     |   ├── index.tsx
>     |   └── index.less
>     ├── user           // 一系列页面推荐通过小写的单一字母做 group 目录
>     |   ├── components // group 下公用的组件集合
>     |   ├── Login      // group 下的页面 Login
>     |   ├── Register   // group 下的页面 Register
>     |   └── util.ts    // 这里可以有一些共用方法之类，不做推荐和约束，看业务场景自行做组织
>     └── *              // 其它页面组件代码
> ```
> 
> 所有路由组件（会配置在路由配置中的组件）我们推荐以大驼峰命名打平到 pages 下面第一级（复杂的项目可以增加 group 层级，在 group 下放置 pages）。不建议在路由组件内部再嵌套路由组件 - 不方便分辨一个组件是否是路由组件，而且不方便快速从全局定位到路由组件。
> 
> 项目中的位置有一些历史因素，我们推荐是这样的

@chenshuai2144 
陈老师您好，请问这套规范，目前有调整吗？目前是否可沿用该规范？
