### ISSUE TITLE
Ellipsis组件在firefox下设置lines=1不显示，lines>1没问题

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design-pro#758]
see codepen: https://codepen.io/anon/pen/WdYdxN?&editors=001
官网示例，设置lines=1,非webkit下不显示，childNode中targetCount = 0，导致span中为空；

**Comment by nikogu** [comment]
在 firefox 中通过 js 计算的场景，并未重现，请贴下 pro 版本以及浏览器版本

**Comment by sbyps** [comment]
pro最新版本，firefox 57版本

**Comment by sbyps** [comment]
@nikogu

**Comment by nikogu** [comment]
@sbyps 截个图我看看，如果有 dom 的图就更好了

**Comment by nikogu** [comment]
![image](https://user-images.githubusercontent.com/1179603/35095170-7c831c44-fc82-11e7-8d2e-b567b40b6e9c.png)

**Comment by sbyps** [comment]
![qq 20180118190814](https://user-images.githubusercontent.com/3881956/35095333-0ac8d084-fc83-11e7-83c3-4f793d7f7b2f.png)

**Comment by nikogu** [comment]
![image](https://user-images.githubusercontent.com/1179603/35096489-64983e52-fc87-11e7-8a16-51118b11d048.png)

这个为啥要设置个 12

**Comment by sbyps** [comment]
有的，我复写了antd的基础样式，font-size为12px，@line-height-base变量设置为1，所以是12px

**Comment by nikogu** [comment]
@sbyps 那看起来就是这个的问题了，你把你这个地方的显示设置为 `20px` 试试

**Comment by sbyps** [comment]
怎么显示设置成20px啊，这个不是组建算的么，我在外层设置了20px没用

**Comment by nikogu** [comment]
```jsx
import Ellipsis from "ant-design-pro/lib/Ellipsis";

const article = (
  <p>
    There were injuries alleged in three <a href="#cover">cases in 2015</a>, and
    a fourth incident in September, according to the safety recall report. After
    meeting with US regulators in October, the firm decided to issue a voluntary
    recall.
  </p>
);

ReactDOM.render(
  <div style={{ width: 200, lineHeight: 20 }}>
    <Ellipsis tooltip lines={1}>
      {article}
    </Ellipsis>
  </div>,
  mountNode
);
```

**Comment by sbyps** [comment]
![qq 20180118195448](https://user-images.githubusercontent.com/3881956/35097064-79794fd0-fc89-11e7-9281-0fc9569ba02d.png)

这样了，呃呃呃

**Comment by nikogu** [comment]
@sbyps 我复现了，就是这个问题，应该是 firefox 的问题，它如果 line-height 跟字体一样大，结果就是高度小于 12，所以就挂了，你设置大一点就好了。

ps：line-height: 12 -> line-height: 12px，要加 px

**Comment by sbyps** [comment]
@nikogu 好了，我写错了，那这个就只能在外层设置一个大于font-size的line-height了是吧

**Comment by nikogu** [comment]
> 那这个就只能在外层设置一个大于font-size的line-height了是吧

对，或者你让子元素继承外部的 line-height 也可以。

ps：一般不会将 line-height 设置成 1 的，这样文本都没有间距了，不是最佳实践。
