### ISSUE TITLE
🧐[问题]Definition for rule '@typescript-eslint/no-loop-func' was not found

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7580]
### 🧐 问题描述

我也是个新手，下载ant-design pro后，该安装的也安装了，eslint总提示有些错误信息，请高手指点！

### 💻 示例代码

如截图等其他信息可以贴在这里
![image](https://user-images.githubusercontent.com/17469220/98507041-cfa93d80-2282-11eb-81a1-519ddb5e3083.png)

**Comment by chenshuai2144** [comment]
包看起来没装全，试试 tyarn 或者  cnpm

**Comment by my9988** [comment]
> 包看起来没装全，试试 tyarn 或者 cnpm

感谢您的回复。
编译都是成功的没有任何错误，非常纳闷。另外前几天你们改的Login screen 多国语言支持 漏掉了提交按钮的翻译

**Comment by my9988** [comment]
> > 包看起来没装全，试试 tyarn 或者 cnpm
> 
> 感谢您的回复。
> 编译都是成功的没有任何错误，运行也正常，非常纳闷。另外前几天你们改的Login screen 多国语言支持 漏掉了提交按钮的翻译

![image](https://user-images.githubusercontent.com/17469220/98520913-c1feb280-2298-11eb-9ef8-c4754fa134bc.png)

**Comment by my9988** [comment]
> 包看起来没装全，试试 tyarn 或者 cnpm

用cnpm等都安装全了，还是一样的问题，麻烦再给分析下原因

**Comment by dongweiguang** [comment]
在.eslint.js 中 配置 rules
  rules: {
    "@typescript-eslint/no-loop-func":'off',
    "@typescript-eslint/no-redeclare":'off',
    "@typescript-eslint/no-shadow":'off',
    "@typescript-eslint/no-use-before-define":'off'
  }

**Comment by huanqiuxuexiji** [comment]
@typescript-eslint的版本问题
