### ISSUE TITLE
运行脚本 lint 报错  🐛[BUG]

### ISSUE THREAD

**Issue by zlfgege** [ant-design/ant-design-pro#7581]
### 🐛 bug 描述

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.3.0 lint:js: `eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@4.3.0 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhenglifeng/.npm/_logs/2020-11-09T08_23_08_829Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.3.0 lint: `umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@4.3.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'lint:js' ]
2 info using npm@6.14.8
3 info using node@v14.5.0
4 verbose run-script [ 'prelint:js', 'lint:js', 'postlint:js' ]
5 info lifecycle ant-design-pro@4.3.0~prelint:js: ant-design-pro@4.3.0
6 info lifecycle ant-design-pro@4.3.0~lint:js: ant-design-pro@4.3.0
7 verbose lifecycle ant-design-pro@4.3.0~lint:js: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@4.3.0~lint:js: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zhenglifeng/work/smart-metering_智能评测/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zhenglifeng/work/smart-metering_智能评测/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle ant-design-pro@4.3.0~lint:js: CWD: /Users/zhenglifeng/work/smart-metering_智能评测
10 silly lifecycle ant-design-pro@4.3.0~lint:js: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src'
10 silly lifecycle ]
11 silly lifecycle ant-design-pro@4.3.0~lint:js: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@4.3.0~lint:js: Failed to exec lint:js script
13 verbose stack Error: ant-design-pro@4.3.0 lint:js: `eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid ant-design-pro@4.3.0
15 verbose cwd /Users/zhenglifeng/work/smart-metering_智能评测
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:js"
18 verbose node v14.5.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@4.3.0 lint:js: `eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src`
22 error Exit status 1
23 error Failed at the ant-design-pro@4.3.0 lint:js script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个看起来是路径的问题？
