### ISSUE TITLE
监听路由的页面logout时会报错🧐[问题]

### ISSUE THREAD

**Issue by hight-lig** [ant-design/ant-design-pro#7582]
### 🧐 问题描述

在有监听路由的页面页面登出，控制台会报错 Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### 💻 示例代码
useEffect(() => {
      //监听路由变化
      const unlisten = history.listen((location, action) => {
        console.log(location);
      });
      return unlisten();
    })

**Comment by chenshuai2144** [comment]
真的有这个语法吗？
