### ISSUE TITLE
🧐[在Umi UI的资产界面添加区块时，antd的区块列表是空的]重启后也没有效果

### ISSUE THREAD

**Issue by Start-from-zero** [ant-design/ant-design-pro#7584]
![Dingtalk_20201110165312](https://user-images.githubusercontent.com/35064277/98651469-4161b400-2375-11eb-9890-be8d57df0e16.jpg)
![Dingtalk_20201110165358](https://user-images.githubusercontent.com/35064277/98651537-5c342880-2375-11eb-8f5e-d6388d6ef872.jpg)
![Dingtalk_20201110165558](https://user-images.githubusercontent.com/35064277/98651779-a2898780-2375-11eb-871e-273972c4eb48.jpg)
![Dingtalk_20201111092050](https://user-images.githubusercontent.com/35064277/98753408-3d7a7400-23ff-11eb-954a-5a7628829322.jpg)

![Dingtalk_20201111092050](https://user-images.githubusercontent.com/35064277/98753516-7ca8c500-23ff-11eb-9b6b-61d82dcd1ebe.jpg)

后台一直在解析json :'https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.json'
umi的区块是有的 antd的没有

**Comment by lvchanglu** [comment]
我也遇到这个问题了,你解决了吗

**Comment by chenshuai2144** [comment]
现在没人维护，估计不会修了

**Comment by sunclelee** [comment]
> 现在没人维护，估计不会修了

今天我下载了v4，运行起来后也是遇到pro 资产暂无数据。没人维护是代表这个功能以后都用不了嘛？

**Comment by sunclelee** [comment]
哦，解决了，antd 选择 4就出现区块了

**Comment by chenshuai2144** [comment]
这个功能已经废弃并停止维护，如果需要建议自行frok维护。
——
This function has been abandoned and stopped maintenance. If necessary, it is recommended to start maintenance by yourself.

**Comment by NingTang-DaoCloud** [comment]
这个问题无解
