### ISSUE TITLE
V5并没有使用最新的layout，菜单宽度还是256px🐛[BUG]

### ISSUE THREAD

**Issue by yuandalu** [ant-design/ant-design-pro#7585]
### 🐛 V5并没有使用最新的layout，菜单宽度还是256px

- Ant Design Pro 版本: [e.g. 5.0.0-beta.0]
- 浏览器环境chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/3860040/98652650-ee88fc00-2376-11eb-9a9d-f7002d5551b6.png)

**Comment by yuandalu** [comment]
直接 yarn create umi 选择 pro  选v5创建的项目，
尝试过从github拉取v5分支最新代码也是这样，layout最新的规则没有在v5实现
v4测试是208px的

**Comment by chenshuai2144** [comment]
看了一下layout插件里重写了 我在v5里改一下

**Comment by chenshuai2144** [comment]
重新生成员 就好了

**Comment by yuandalu** [comment]
> 重新生成一下就好了

感谢，我最后也是找到了这个参数设定了208，，，，我以为这个不是正式解决方案

**Comment by chenshuai2144** [comment]
layout 主要是内部用户，我也不知道为啥要 256 ，可能是为了让内部用户的 改动更小一点
