### ISSUE TITLE
🧐[问题]菜单的path重合，会导致同时激活

### ISSUE THREAD

**Issue by DCLangX** [ant-design/ant-design-pro#7587]
### 🧐 问题描述

如图，是因为路径匹配是贪婪模式吗，，刚上手react，云里雾里，不知道哪里改

### 🚑 其他信息

![微信图片_20201110193917](https://user-images.githubusercontent.com/19513657/98669605-8e04b980-238c-11eb-859b-9c7ec4e6082b.png)

**Comment by chenshuai2144** [comment]
不要太像就好了 逻辑被写到组件里了

你可以展示一下你的代码

**Comment by dmdoit** [comment]
改成 `path: '/award'`和`path: '/awardtype'`试试

**Comment by DCLangX** [comment]
解决不了，我已经放弃了，直接改path= =
