### ISSUE TITLE
🧐[问题]11月11日，complete版本，服务启动后，直接进入/dashboard/analysis路由，只有工作区页面，菜单，顶部，底部页面没有了。

### ISSUE THREAD

**Issue by oxygen-xx** [ant-design/ant-design-pro#7589]
### 🧐 问题描述

11月11日，npm create umi新建立的项目，complete版本，服务启动后，直接进入/dashboard/analysis路由，只有工作区页面，菜单，顶部，底部页面没有了。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/153051/98779165-66fec400-242e-11eb-924c-15a6f5f6e0df.png)

**Comment by XieCJ** [comment]
同样的问题，并且报TypeError: reactRouter.Router.computeRootMatch is not a function错误

**Comment by XieCJ** [comment]
thanks，已解决
