### ISSUE TITLE
🧐[问题]less文件不报eslint错误，只有在提交的时候提交不了，提示less有错误

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design-pro#7590]
### 🧐 问题描述
🧐[问题]less文件不报eslint错误，只有在提交的时候提交不了，提示less有错误

**Comment by chenshuai2144** [comment]
什么问题？

**Comment by xiaoshui222** [comment]
`& p {
        color: #ffffff;
        margin-bottom: 0;
      }`
比如这个代码，color应该写在margin-bottom下面，但是IDE不报错

**Comment by chenshuai2144** [comment]
@xiaoshui222  没装stylelint 吧，执行一下 lint:fix 能自动修复

**Comment by xiaoshui222** [comment]
stylelint装了，不过还是希望能跟js一样能有提示，大佬有没有什么办法

**Comment by xiaoshui222** [comment]
弄好了，IDE中stylelint配置问题，依然感谢
