### ISSUE TITLE
🧐[急需求救]怎么使用mock模拟restful接口url中有动态参数的这类接口?

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ant-design/ant-design-pro#7591]
### 🧐 问题描述
怎么使用mock模拟restful接口url中有动态参数的这类接口?举例如下:  
有`GET /v1/testone/user/{userCode}/homes/{homeId}`所示rest接口,在mock目录下应该如何拦截?  

### 💻 示例代码
我的错误示例:    
- 在mock目录下新建`user.ts`文件,内容如下
```
import { Request, Response } from 'express';
const queryUser = (req:Request, res:Response)=> {
   ....
};
export default {
  'GET /v1/testone/user/*/homes/*': queryUser,
};  
```  
这么写拦截不到哈  

### 🚑 其他信息
能麻烦给个具体示例吗?

**Comment by chenshuai2144** [comment]
可以看看这个 https://expressjs.com/zh-cn/4x/api.html#path-examples

底层是express

```tsx
app.get('/user/:id', function (req, res) {
  res.send('user ' + req.params.id)
})
```

**Comment by darkfiredarkhalo** [comment]
谢谢,这种方式也试了,结果少拼写了个字母😂,非常感谢
