### ISSUE TITLE
如何不通过npm run lint 就能在编辑器中看到对应的规则检查报错信息？

### ISSUE THREAD

**Issue by 123456wjw** [ant-design/ant-design-pro#7593]
如何不通过npm run lint 就能在编辑器中看到对应的规则检查报错信息？

**Comment by chenshuai2144** [comment]
装个 eslint 插件

https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by 123456wjw** [comment]
编辑器里，项目中并且全局都已经安装过了eslint插件，但是仍然没有效果

**Comment by 123456wjw** [comment]
> 装个 eslint 插件
> 
> https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

编辑器里，项目中并且全局都已经安装过了eslint插件，但是仍然没有效果

**Comment by 123456wjw** [comment]
> 装个 eslint 插件
> 
> https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

编辑器里，项目中并且全局都已经安装过了eslint插件，但是仍然没有效果

**Comment by chenshuai2144** [comment]
可以打开看是不是报错

**Comment by 123456wjw** [comment]
> 可以打开看是不是报错
> 
> ![image](https://user-images.githubusercontent.com/8186664/98793693-35442800-2443-11eb-828d-4458dea1f196.png)

![image](https://user-images.githubusercontent.com/37201576/98798060-63783680-2448-11eb-8bf2-7903ba024c6a.png)
