### ISSUE TITLE
在V5版本中，FC可以使用<Access>组件，class页面权限如何使用呢？🧐[问题]

### ISSUE THREAD

**Issue by wenslo** [ant-design/ant-design-pro#7594]
### 🧐 问题描述

在V5版本中，FC可以使用<Access>组件，class页面权限如何使用呢？
class中无法使用hook，找了找官网没找到示例部分
有demo么？

**Comment by chenshuai2144** [comment]
这个组件只有 hooks 的用法，不过你可以封装一下，把需要用权限的拆分成 function，没有 hooks 的组件的逻辑的确很难公用。

**Comment by wenslo** [comment]
嗯嗯，手动封装了一下
只是感觉没你们封装的写得好
23333

**Comment by chenshuai2144** [comment]
拥抱新潮流吧，function + state 的抽象能力太强了，用起来很爽
