### ISSUE TITLE
👑 [需求]ant  pro 最大的问题？也是最大的BUG！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7595]
### 🥰 需求描述

最大的BUG，也是最大的问题，就是一直不知道自己开发的软件是什么！一直推翻重新搞，搞了一堆BUG！

V5挺好的，就好好搞V5！

学习成本太高了！你们的开发成本也不低啊！

至少你搞不好V4，支持个2年，这样我们也能接受啊！

**Comment by BeanWei** [comment]
好家伙 我直接好家伙！

**Comment by chenshuai2144** [comment]
你要的是一个企业级+维护服务的产品，但是 pro 的定位是最佳实践，要跟着社区一直更新的。

如果想要不会变化的建议买商业产品，固步自封对一个开源产品来说相当于死掉了
