### ISSUE TITLE
🐛[BUG]登录问题（需要二次登录，DVA兼容性问题）

### ISSUE THREAD

**Issue by meccain** [ant-design/ant-design-pro#7596]
###登录时的DVA兼容性问题

### 📷 复现步骤
如果我在package.json里引入dva的依赖
导致我在登录页面输入用户名、密码，验证成功之后还是会定向到登录页面（需要再输一遍用户名密码），然后才能登录成功
如果我把dva的依赖去掉，则无此问题
但是我之前的项目的老代码还需要createStore reducer epics，改造难度大，请问如何老项目在不需要大概代码的情况下兼容dva依赖

1.根路径进入登录页面
2.输入用户名、密码，验证成功
3.还是定向到登录页面，再输一遍用户名密码
4.登录成功

需要每次都还是通过根路径进入登录页面

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.3.0，4.2.*均有此问题]
- umi 版本 3.2.14
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/7619

这两个问题看起来是一样的
