### ISSUE TITLE
🧐[问题] 升级高版本后项目启动很慢？

### ISSUE THREAD

**Issue by Mh2336393** [ant-design/ant-design-pro#7597]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/48132028/98896098-2e6cf200-24e3-11eb-8e70-45181265c278.png)
得好几分钟项目才能跑起来，我是从低版本升上来 ，umi升级到3，antd 升级了最新得4.8.2 ，并且进行了nodeModulesTransform配置
![image](https://user-images.githubusercontent.com/48132028/98896231-7855d800-24e3-11eb-8216-e189a634c12b.png)

我猜测是不是项目里面有好多没用得依赖 导致node_modules太大了？有什么办法没找出 没用得依赖然后在package.json去掉吗？

**Comment by chenshuai2144** [comment]
这是前端的特性了 我也很慢！期待webpack5

**Comment by phoema** [comment]
umi2就很快，umi3就很慢，慢到没法子了，太苦。
