### ISSUE TITLE
小白一个，antdesign pro V5使用umi request🧐[问题]

### ISSUE THREAD

**Issue by uuxia** [ant-design/ant-design-pro#7598]
### 🧐 问题描述

小白一个，求解答
antdesign pro V5中useRequest请求获取到的数据为什么打印不出来呢？

### 💻 示例代码

```
import React from 'react'; 
import { getCatels } from '@/services/process';
import { useRequest } from 'umi';
 
 
export const Processls: React.FC<{}> = () => {
    const { data, error, loading } = useRequest(getCatels);
    console.log(data, error, loading);
    if (error) {
        return <div>failed to load</div>;
    }
    if (loading) {
        return <div>loading...</div>;
    }
    return <div>Username: {data}</div>;
};

export default Processls; 
```

代码如上所示，看console是请求到接口数据的，但是下面的data好像是undefined 一直不显示。
### 🚑 其他信息

 
![image](https://user-images.githubusercontent.com/11535708/98903976-a511eb80-24f3-11eb-8a20-1f9d2af998e0.png)

**Comment by chenshuai2144** [comment]
`import { getCatels } from '@/services/process';`

代码展示一下

**Comment by uuxia** [comment]
谢谢大家 已经解决  v5里面接口规范要求返回数据放到data里面  按这样处理就好啦
