### ISSUE TITLE
UI is position at wrong place after loading

### ISSUE THREAD

**Issue by kevinaskin** [ant-design/ant-design-pro#76]
![image](https://user-images.githubusercontent.com/20034891/32307362-151eca3e-bfbb-11e7-8c7f-e9d3a1e6b2f5.png)

**Comment by nikogu** [comment]
track: https://github.com/dvajs/dva/issues/1300

**Comment by afc163** [comment]
不是这个问题。这是线上的。

**Comment by nikogu** [comment]
好的，我看看

**Comment by nikogu** [comment]
原因是因为 `card` 有个 `padding-transition`，会判断宽度进行 `padding` 的设置，但是这个是有动画的，导致 G2 `auto fix` 算位置出错，所以只需要固定 `padding` 就可以了(因为我们的设计也是固定的)

**Comment by afc163** [comment]
![](https://gw.alipayobjects.com/zos/rmsportal/HkEqJwftoJvzEAXIygJu.png)

现在变得太快了，水平空间还足够。
