### ISSUE TITLE
支持websocket吗？

### ISSUE THREAD

**Issue by eruca** [ant-design/ant-design-pro#760]
在pro之前自己搭建了个类似的项目，使用websocket,近期发现pro，总之高大上好多，可是通讯不一样，怎么支持websocket?

**Comment by chenshuai2144** [comment]
这个不影响呀！redux 可以支持
https://github.com/itaylor/redux-socket.io

**Comment by jabezGit** [comment]
@chenshuai2144   能帮助一下讲一下思路如何在 antd pro 里集成 redux-socket.io /socket.io 不

**Comment by succulen-plants** [comment]
@chenshuai2144 怎么集成socket.io

**Comment by chenshuai2144** [comment]
你们碰到了什么问题？

**Comment by succulen-plants** [comment]
dva里 把 store 及 saga 统一为一个 model , 
redux.socket.io 需要一个链接redux和socket.io的 middleware： let store = applyMiddleware(socketIoMiddleware)(createStore)(reducer);
这里完全不知道， 怎么把这个middleware塞进去。


import { queryZone } from '@/services/api';
export default {
  namespace: 'zone',
  state: {
    data: {
      list: [],
      pagination: {},
    },
  },

  effects: {
    *fetch({ payload }, { call, put }) {
      const response = yield call(queryZone, payload);
      yield put({
        type: 'save',
        payload: response,
      });
    },
  },

  reducers: {
    save(state, action) {
      return {
        ...state,
        data: action.payload,
      };
    },
  },

};

**Comment by succulen-plants** [comment]
@chenshuai2144  这个问题怎么解决

**Comment by chenshuai2144** [comment]
请先格式化一下代码

**Comment by succulen-plants** [comment]
@chenshuai2144 
感谢你回复我的问题
首先我需要创建socket链接以及redux和socket的middleware：
let socket = io('http://localhost:5000');
let socketIoMiddleware = createSocketIoMiddleware(socket, "server/");
function reducer(state = {}, action){
    switch(action.type){
      case 'message':
        return Object.assign({}, {message:action.data});
      default:
        return state;
    }
  }
通过middle创建了store
let store = applyMiddleware(socketIoMiddleware)(createStore)(reducer);
但是dva里 把 store 及 saga 统一为一个 model ,所以不知道怎么把这个middleware放到model中

**Comment by chenshuai2144** [comment]
https://github.com/dvajs/dva-knowledgemap#redux-middleware

**Comment by eruca** [comment]
在middleware 中，如果使用dispatch({type:"login",...})， 好像global里的login reducer没法收到信息啊？

**Comment by micfan** [comment]
如果用 websocket, 那么前端的 HTTP mock 功能就用不上了

我看 websocket 是大趋势，5G 一旦推开，实时应用就会普及
