### ISSUE TITLE
Pro能否把dva移除掉 

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#7601]
### 🧐 问题描述

准备开个新项目 但dva又不支持hook，虽然dva和hook不冲突但两个结合用起来总感觉那怪怪的很不舒服，pro硬绑上了dva 不用又不行，希望proV5能与其他的状态管理库试试（**dva更新太慢了建议换掉**）

**Comment by afc163** [comment]
你试试 v5 的 beta 版本，里面已经默认把 dva 移除了。

https://beta-pro.ant.design/
