### ISSUE TITLE
Couldn't find package "use-media-antd-query@^1.0.3" required by "@ant-design/pro-skeleton@1.0.0-beta.10" on the "npm" registry.🧐[问题]

### ISSUE THREAD

**Issue by Ckefan** [ant-design/ant-design-pro#7602]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/23022046/99144890-dd0c6080-26a4-11eb-869f-3eabb2efa2a5.png)

**Comment by chenshuai2144** [comment]
有个包没有写依赖，更新一下就好了，是我的疏忽
