### ISSUE TITLE
[V5] Uncaught Error: register failed, invalid key initialStateConfig from plugin

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/ant-design-pro#7603]
![image](https://user-images.githubusercontent.com/51048705/99151029-4a36ea80-26d3-11eb-9506-4d581fe3b97b.png)
![image](https://user-images.githubusercontent.com/51048705/99151040-5c188d80-26d3-11eb-9ca9-a93be71b836d.png)

更新后会报这个错误。注释掉可正常使用。不知道是否我这边缺了什么配置。求大佬指点。谢谢。

**Comment by chenshuai2144** [comment]
更新一下依赖

**Comment by gaohongwei** [comment]
我今天也遇到这个错误。更新依赖没管用啊。紧急求助。

**Comment by chenshuai2144** [comment]
lock 文件删除

**Comment by FangHaydn** [comment]
最新版还有

**Comment by Zhiyue-Li** [comment]
> 最新版还有

不要在app.tsx用initialStateConfig, 在.umirc.ts里面可以config你想用的加载页面对应的路径:
<img width="282" alt="截屏2022-07-22 下午2 22 01" src="https://user-images.githubusercontent.com/30882307/180500732-2c6f3ad4-2f1a-4eff-ad26-0f2222f8fdaf.png">
