### ISSUE TITLE
🧐[问题]路由的拦截是在layout-plugin的onPageChange配置中实现，还是应该在全局运行时配置render中实现？

### ISSUE THREAD

**Issue by 985563349** [ant-design/ant-design-pro#7607]
### 🧐 问题描述
我在onPageChange中实现登录拦截，在未登录状态下我通过输入url地址的方式进入页面，虽然会被重定向至登录页，但那个页面还是会闪烁显示出来，这不是我想要的。我觉得路由的拦截逻辑应该在视图渲染之前执行，但我使用全局运行时配置render去实现时发现没有什么好方式可以获取dva或者initialState内的数据。

**Comment by chenshuai2144** [comment]
render 中也会出现问题，如果要完美解决，可以专门做一个 / 页面，里面展示一个 loading，然后根据状态去不同的地方
