### ISSUE TITLE
🧐[问题] 在部署到服务器上之后，第一次进入页面整个页面缩放有问题如下图

### ISSUE THREAD

**Issue by Jiyr0119** [ant-design/ant-design-pro#7608]
### 🧐 问题描述

<img width="1792" alt="WX20201116-174048@2x" src="https://user-images.githubusercontent.com/28727613/99237207-22f72f00-2833-11eb-87ab-728dcb1ab507.png">
<img width="1792" alt="WX20201116-174105@2x" src="https://user-images.githubusercontent.com/28727613/99237220-25598900-2833-11eb-973f-d4dfc3df4103.png">
这是这种缩放的问题 还有一个疑问怎么隐藏这个设置主题颜色的按钮

### 🚑 其他信息
修改过 route 配置

```javascript
          path: '/',
          component: '../layouts/BasicLayout',
          Routes: ['src/pages/Authorized'],
          authority: ['admin', 'user'],
          routes: [
            {
              path: '/',
              // redirect: '/dashboard/analysis',
              redirect: '/user/login',
            },
```
默认到登录页面，登录之后跳到首页。本地没问题，打包部署之后有问题。
但是部署到服务器上的项目，缩放问题浏览器刷新就能解决，麻烦大佬们看看

版本信息：
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.0.21",
    "@ant-design/pro-form": "^1.4.1",
    "@ant-design/pro-layout": "^6.0.0",
    "@ant-design/pro-table": "^2.4.0",
    "antd": "^4.6.1",
    "umi": "^3.2.0",

**Comment by chenshuai2144** [comment]
来个dist，我看看为什么

**Comment by Jiyr0119** [comment]
链接:https://pan.baidu.com/s/15EPXnMZ5fHNcuwDqR27b4A  密码:llzj     这样可以么？ 这个是我本地的，其实是在服务器上自动部署的，您现帮忙看看有问题没有吧，谢谢了

**Comment by Jiyr0119** [comment]
![image](https://user-images.githubusercontent.com/28727613/99347759-d3684000-28d2-11eb-8abb-904108275e06.png)
![image](https://user-images.githubusercontent.com/28727613/99347775-de22d500-28d2-11eb-8878-d3f579f034e2.png)


我以为是这里的问题，因为我改成了登录页面 现在恢复之后部署上去还是不好使 本地就没有问题，我本地打好dist包之后 丢到服务器上也还是有上面的这种问题  就是第一次replace进来有这个问题

**Comment by Jiyr0119** [comment]
问题解决了： 升级了 "umi": "^3.2.13",  "@ant-design/pro-layout": "^6.5.15",  这两个版本  部署后没问题了
