### ISSUE TITLE
🐛[BUG]Modal在linux环境下中英文随机出现

### ISSUE THREAD

**Issue by skyc024** [ant-design/ant-design-pro#7609]
### 🐛 bug 描述

在linux环境下执行npm run build打包部署在nginx服务器后，弹窗组件会中英文随机出现。在win10本本地环境npm run build打出来的包部署到linux服务器没有这个问题。代码在linux\win10环境下打包均没有任何报错

### 📷 复现步骤

在centos下部署pro v5工程项目，使用const { confirm } = Modal组件，弹窗会随机中英文切换。

### 🏞 期望结果

根据设置locale设置的字体只显示中文，
配置如下
 locale: {
    // default zh-CN
    default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    antd: true,
    baseNavigator: true,
  },

### 💻 复现代码

const { confirm } = Modal;

  confirm({
        title: '提示',
        icon: <ExclamationCircleOutlined />,
        content: tips,
        onOk() {
          setQueryParam(values)
          console.log('OK');
        },
        onCancel() {
          console.log('Cancel');
        },

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本(3.0以上)
- 浏览器环境 （chome）
- 开发环境 [win10]
-构建环境[centos7.3,jenkins,node12.8.2]
-部署环境[centos7.3]

### 🚑 其他信息

[http://chuantu.xyz/t6/741/1605526167x-1404755675.png](url)
[http://chuantu.xyz/t6/741/1605526428x2073447983.png](url)
http://chuantu.xyz/t6/741/1605526428x2073447983.png

**Comment by chenshuai2144** [comment]
close  by https://github.com/ant-design/ant-design/pull/27797
