### ISSUE TITLE
🧐 Problems with rendering the name of the page when using routing with parameters

### ISSUE THREAD

**Issue by iloveip** [ant-design/ant-design-pro#7610]
Hi there,

I would like to use dynamic routing with parameters. In my `config.js` file I have:

```
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order'
}
```

How can I render the name of the page (to show in PageHeader and in Breadcrumbs) dynamically as well? Now I have the title from `proSettings` in there. I tried to use static attributes from Umi in my component (something like `Order.title = Order # ${id}/`, but it doesn't seem to work.

**Comment by chenshuai2144** [comment]
breadcrumbRender | 自定义面包屑的数据 | (route)=>route | -
-- | -- | -- | --




you can use this api

**Comment by iloveip** [comment]
I ended up using breadcrumb prop from RouteContext and passing it to PageContainer to dynamically render on every page.
