### ISSUE TITLE
🐛[BUant pro v5用mock模拟获取导航，icon应该怎么配置？

### ISSUE THREAD

**Issue by ChineseGril** [ant-design/ant-design-pro#7611]
### 🐛 bug 描述
用mock模拟数据的时候，icon用“smile”或者是<SmileOutlined/>都是不对的，请问该怎么解决

### 🏞 期望结果
引进icon能快速的渲染出来。类似在config/routes.ts里面展示的一样

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Ray-56** [comment]
请问你的解决了么
