### ISSUE TITLE
🐛[BUG] 运行 npx create-umi 不能选择是ts 还是js

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#7613]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/27960630/99352110-ff88be80-28dc-11eb-9e03-c40876063ef0.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
v5 推荐使用 typescript，正式发布后才会做 js 版本。
无论如何使用 typescript总是更好的，js 现在的没什么优势

**Comment by zjxpcyc** [comment]
看到这个回复，就果断放弃 v5 了。

`js 现在没什么优势`  这话说的，我们小团队，选择 pro 就是为了快，节省成本。一个会  ts 的，跟一个会 js 的， 成本都大不一样。我们还能怎么选？
