### ISSUE TITLE
🧐[问题]V5版本远程请求菜单，登陆后，第一次菜单为空，刷新网页后菜单可以显示

### ISSUE THREAD

**Issue by guogeer** [ant-design/ant-design-pro#7614]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/5010851/99374108-32db4580-28fd-11eb-9de9-9c8373c62f13.png)
V5版本远程请求菜单。第一次登陆后，菜单显示为空，刷新网页后菜单可以显示
### 💻 示例代码

![image](https://user-images.githubusercontent.com/5010851/99374260-5dc59980-28fd-11eb-8d0f-395b11e8533d.png)

```
export const layout = ({
  initialState,
}: {
  initialState: { 
    settings?: LayoutSettings,
    currentUser?: API.CurrentUser,
  };
}): BasicLayoutProps => {
  console.log("app init..............",initialState?.currentUser)

  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,
    menuDataRender: () => {
      console.log("render..............",initialState?.currentUser)
      return initialState?.currentUser?.menuTree || []
    },
    ...initialState?.settings,
  };
};
```
### 🚑 其他信息

    "@ant-design/pro-layout": "^6.5.14",
    "@ant-design/pro-table": "^2.10.1",
    "@umijs/route-utils": "^1.0.34",
    "antd": "^4.8.4",
    "umi": "^3.2.27",

**Comment by chenshuai2144** [comment]
看这个文档
https://beta-pro.ant.design/docs/advanced-menu-cn

**Comment by guogeer** [comment]
不知道"loading: true"放到哪个控件合适
![image](https://user-images.githubusercontent.com/5010851/99924876-f1bcb880-2d76-11eb-9dbe-3dd9a6ce8da6.png)
自己摸索了下，文档提了个PR，更简单点。

**Comment by sirRen** [comment]
怎么解决的，能说一下吗。也不知道该怎么刷新页面出现菜单

**Comment by guogeer** [comment]
就是需要更新loading，比如我在登陆成功后设置loading
      // 登录
      const msg = await fakeAccountLogin({ ...values, type });
      if (msg.status === 'ok') {
        message.success('登录成功！');
        setInitialState({
          settings: {
            ...defaultSettings,
            menu: {
              ...defaultSettings.menu,
              loading: true, // 正在加载菜单
            },
          },
        });

        replaceGoto();






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月2日(星期五) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-pro] 🧐[问题]V5版本远程请求菜单，登陆后，第一次菜单为空，刷新网页后菜单可以显示 (#7614)





 
怎么解决的，能说一下吗。也不知道该怎么刷新页面出现菜单

**Comment by sirRen** [comment]
了解了，谢谢你
