### ISSUE TITLE
 如何做到系统端口占用 自动启动别的端口  

### ISSUE THREAD

**Issue by zlfgege** [ant-design/ant-design-pro#7615]
最近发现antd pro 一个有趣的功能，在8000端口占用的情况下，会自动启动8001端口 。

可以告诉我一下原理 ，或者告知哪有相关文档可以看吗？

百度出来端口占用都是教一些杀死端口这并不是我想要的

希望可以知道 如何做到启动项目时端口占用 自动启动别的端口

**Comment by tnngo** [comment]
监听端口的自动改变和antd pro并没有任何关系，建议去看一下http服务的基础知识，任何能写http服务的语言都可以通过判断做到自动改变端口。

**Comment by chenshuai2144** [comment]
node 有 api 可以拿到的

**Comment by chenshuai2144** [comment]
https://segmentfault.com/a/1190000004915782
