### ISSUE TITLE
🧐[问题] 安装JavaScript版本的complete选项时，有eslint相关报错信息。问题由来已久

### ISSUE THREAD

**Issue by oxygen-xx** [ant-design/ant-design-pro#7617]
### 🧐 问题描述
npm create umi ,  v4, javascript ,complete
一直有Error提示：

Error: BaseConfig »  .npm/_npx/65064/lib/node_modules/create-umi/node_modules/@umijs/fabric/dist/eslint.js » eslint-config-airbnb » /.npm/_npx/65064/lib/node_modules/create-umi/node_modules/eslint-config-airbnb-base/index.js » /.npm/_npx/65064/lib/node_modules/create-umi/node_modules/eslint-config-airbnb-base/rules/imports.js:
	Configuration for rule "import/no-cycle" is invalid:
	Value "∞" should be integer.
后面还有很多eslint的相关信息。

MacOS
Node版本 14.15.1 
这个问题很多人问题过，而且时间由来已久，但一直没有解决。请管理员给处理一下？

**Comment by chenshuai2144** [comment]
更新一下依赖吧，看起来是的 eslint-config-airbnb-base 的问题
