### ISSUE TITLE
🐛[BUG]缓存问题

### ISSUE THREAD

**Issue by rong12345** [ant-design/ant-design-pro#7620]
线上更新后用户需要手动清除缓存，hash也打开了，应该是html缓存，上线后html里请求的还是上一次的js,css，有配置exportStatic，会生成很多html，有什么解决方法吗
- Ant Design Pro 版本: 4.1.0
- umi 版本 3.2.0

**Comment by rong12345** [comment]
> 缓存是浏览器行为，我记得可以用`META`标签解决，内容填写no-cache。

十多个页面，每次上线都要手动修改的话是不是太麻烦了

**Comment by toesbieya** [comment]
服务器的response header设置no cache

**Comment by rong12345** [comment]
> 服务器的response header设置no cache

好的 试一下
