### ISSUE TITLE
🧐[问题] 将 Card 单独封装成组件的时候，.ant-card 样式无法正确加载

### ISSUE THREAD

**Issue by Han-MeiM** [ant-design/ant-design-pro#7625]
### 🧐 问题描述

- 单独的组件封装 Card 样式没有加载
- 访问其他带有 Card 的页面将样式加载完毕后，再回到无法加载的页面后，样式又成功加载出来
- 猜测可能是按需加载的时候没有正确加载到？
- 看了下控制台，没有加载到的时候少了 `.ant-card` 这个样式
- ant-design 目前的版本为 4.0，升级到 4.8 后仍然有这个问题

**Comment by chenshuai2144** [comment]
你是不是没有使用 less 导致的？
如果没有使用 less，需要人工 import 一下 card 的样式。
如果使用了less，可以在 less 文件中 中专门 import一下 less，可能是依赖分析的问题
