### ISSUE TITLE
🐛[BUG]左侧菜单收起来后，鼠标放上去，图标跑偏了，木有居中

### ISSUE THREAD

**Issue by beevivo6** [ant-design/ant-design-pro#7628]
### 🐛 bug 描述

左侧菜单收起来后，鼠标放上去，图标跑偏了，木有居中

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^6.5.13",
    "@ant-design/pro-table": "^2.5.3",
    "antd": "^4.7.0",
- umi 版本
    "umi": "^3.2.14",

- 浏览器环境
    chrom
- 开发环境 [e.g. mac OS]
    windown

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29418930/99636904-0f400880-2a7f-11eb-9885-911b05bd4b21.png)

**Comment by chenshuai2144** [comment]
看看是不是样式污染，在 https://preview.pro.ant.design/dashboard/analysis 中是没有问题的

**Comment by beevivo6** [comment]
![image](https://user-images.githubusercontent.com/29418930/100601100-22838b80-333d-11eb-8b1e-04cdf3ce5799.png)
@ @ @chenshuai2144 这个padding去掉就正常了，这个css文件看着明显是组件库的。
![image](https://user-images.githubusercontent.com/29418930/100601343-6bd3db00-333d-11eb-8a2e-4a4ef7dc89b6.png)

**Comment by chenshuai2144** [comment]
看看是不是打包了两份layout导致的 这个样式已经被删除了

**Comment by beevivo6** [comment]
本地也有这样的情况哦 @chenshuai2144

**Comment by beevivo6** [comment]
> 看看是不是打包了两份layout导致的 这个样式已经被删除了

@问个题外话 这个 颜色无法覆盖，但是我又想修改要怎么办呢？
![image](https://user-images.githubusercontent.com/29418930/100989120-6ff53800-358b-11eb-94dc-683b43a4a5ef.png)

**Comment by beevivo6** [comment]
> 看看是不是打包了两份layout导致的 这个样式已经被删除了

本地也有这样的情况哦 @chenshuai2144
![image](https://user-images.githubusercontent.com/29418930/100988199-6cad7c80-358a-11eb-87de-a706b5635e2c.png)
z只是一份哦

**Comment by iambool** [comment]
这个问题我也遇到了，求解

**Comment by chenshuai2144** [comment]
> 这个 颜色无法覆盖

这个是多色icon，你要换一下

**Comment by chenshuai2144** [comment]
@iambool  用 npm ls @ant-design/pro-layout ，看看是不是又多个版本被覆盖了
