### ISSUE TITLE
v5版本 在config设置路由模式 history: { type: 'hash' }, 退出登录，页面无法重定向

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#7632]
在config设置路由模式 history: { type: 'hash' }, 退出登录，页面无法重定向
一级路由重定向结果是这样子，跑到了首页 http://localhost:8000/list#/welcome
二级路由重定向打开之后是空白， 路劲变成这样 http://localhost:8000/admin/sub-page
v5版本

脚手架重定向的代码如下
`
const goto = () => {
  const { query } = history.location;
  const { redirect } = query as { redirect: string };
  window.location.href = redirect || '/';
};

`

路由配置如何下
```
{
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
    ],
  },
  {
    path: '/',
    component: '../layouts/index',
    menu: {
      flatMenu: true,
    },
    routes: [
      {
        path: '/welcome',
        name: 'welcome',
        icon: 'smile',
        component: './Welcome',
      },
     {
        path: '/admin',
        name: 'admin',
        icon: 'crown',
        access: 'canAdmin',
        component: './Admin',
        routes: [
          {
            path: '/admin/sub-page',
            name: 'sub-page',
            icon: 'smile',
            component: './Welcome',
          },
        ],
      },
 {
        name: 'list.table-list',
        icon: 'table',
        path: '/list',
        component: './ListTableList',
      },

```

**Comment by chenshuai2144** [comment]
改成这样

```
/**
 * 此方法会跳转到 redirect 参数所在的位置
 */
const goto = () => {
  if (!history) return;
  const { query } = history.location;
  const { redirect } = query as { redirect: string };
  history.push(redirect || '/');
};

```

**Comment by z-lionel** [comment]
>  if (!history) return;
>   const { query } = history.location;
>   const { redirect } = query as { redirect: string };
>   history.push(redirect || '/');

这个方法无效，一进到页面又立刻闪退回登录页，之前试过用history.push跳转不过去，
上面分开两个根路径 / 和 /user   难道不能用history跳转?

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/7473 这个问题没有解决，还是要用 window.location.href =redirect || '/';  跳转才行。https://github.com/ant-design/ant-design-pro/commit/e199a07712ab95e41f2e8b89ea7553fd4bb7bd06


> > if (!history) return;
> > const { query } = history.location;
> > const { redirect } = query as { redirect: string };
> > history.push(redirect || '/');
> 
> 这个方法无效，一进到页面又立刻闪退回登录页，之前试过用history.push跳转不过去
> 
> 试了一下，不用window.location.href =redirect || '/'; 这个方法跳转路由，
> app.ts的getInitialState方法不会重新加载， 就不会触发请求用户信息的方法，
> 又被onPageChange重定向回登录页，如何解决？
> 在layout里面或者onPageChange加判断和请求用户数据了？

这个问题，可以在登录后保存和个 token之类的 如：
![image](https://user-images.githubusercontent.com/18542211/99865917-120a3d00-2be8-11eb-82c2-af0de4d255cb.png)

**Comment by z-lionel** [comment]
token是有设置，主要还有个获取用户信息的接口，本来放在getInitialState获取的，但是不刷新无法触发，
不然还是在登录的时候，顺便请求用户信息，就存到initialState，这样也能行

**Comment by z-lionel** [comment]
> #7473 这个问题没有解决，还是要用 window.location.href =redirect || '/'; 跳转才行。[e199a07](https://github.com/ant-design/ant-design-pro/commit/e199a07712ab95e41f2e8b89ea7553fd4bb7bd06)
> 
> > > if (!history) return;
> > > const { query } = history.location;
> > > const { redirect } = query as { redirect: string };
> > > history.push(redirect || '/');
> > 
> > 
> > 这个方法无效，一进到页面又立刻闪退回登录页，之前试过用history.push跳转不过去
> > 试了一下，不用window.location.href =redirect || '/'; 这个方法跳转路由，
> > app.ts的getInitialState方法不会重新加载， 就不会触发请求用户信息的方法，
> > 又被onPageChange重定向回登录页，如何解决？
> > 在layout里面或者onPageChange加判断和请求用户数据了？
> 
> 这个问题，可以在登录后保存和个 token之类的 如：
> ![image](https://user-images.githubusercontent.com/18542211/99865917-120a3d00-2be8-11eb-82c2-af0de4d255cb.png)

token是有设置，主要还有个获取用户信息的接口，本来放在getInitialState获取的，但是不刷新无法触发，
不然还是在登录的时候，顺便请求用户信息，就存到initialState，这样也能行

**Comment by Cooolyu** [comment]
@z-lionel 我也遇到这个问题，目前有解决方案么

**Comment by z-lionel** [comment]
> @z-lionel 我也遇到这个问题，目前有解决方案么
我上面说了吧，如果不用window.location.href 刷新页面，app的getInitialState不会重新运行；
如果还用history.push在登录的时候，多调用一次获取用户信息的接口，把用户信息存起来，这样就应该就可以通用，
app的获取就在内页用户刷新的时候会用

**Comment by chenshuai2144** [comment]
重新执行了一下 fetchMenu 这个问题应该完美解决了
