### ISSUE TITLE
🧐[问题]antd pro是不支持面包屑加链接吗

### ISSUE THREAD

**Issue by LB-nan** [ant-design/ant-design-pro#7633]
### 🧐 问题描述

看了官网的示例demo与其他issues，没有发现关于面包屑加链接的，请问是不支持吗？如果要加需要如何配置或代码demo

**Comment by chenshuai2144** [comment]
可以看看这个 
https://github.com/umijs/plugins/blob/master/packages/plugin-layout/src/layout/index.tsx

文档在这里

https://procomponents.ant.design/
