### ISSUE TITLE
🧐[问题] V5 动态菜单的一些疑问

### ISSUE THREAD

**Issue by zhangshuling** [ant-design/ant-design-pro#7634]
app.tsx 代码如下：
![image](https://user-images.githubusercontent.com/15334960/99763991-0579dc00-2b37-11eb-8424-b72adbe2814c.png)

每次重新登录后，菜单是可以动态显示，以基本实现

access.tsx 中 , 我在canAdmin 里面 打算用当前地址栏地址与 登录用户的 动态菜单中的 url 做对比， 简单的实现鉴权
![image](https://user-images.githubusercontent.com/15334960/99764977-1d525f80-2b39-11eb-8a37-4e776314d978.png)

结果遇上了2个问题：
1. 当我通过点击动态菜单想进入相应功能页面时（随便点哪一个动态出来的菜单，都显示403），却显示了 403 页面 （access.tsx 中的 canAdmin 没打印日志，应该是没有执行）， 我如果刷新一下地址栏(或者地址栏回车 canAdmin方法里面的日志也输出了)，就好了， 其他的菜单也可以点进去了
![image](https://user-images.githubusercontent.com/15334960/99764746-afa63380-2b38-11eb-81c0-076ec31319af.png)

2. 我通过地址栏输入上一个用户的菜单（不属于当前用户的）也可以进去(好像只出现在登录另一个用户时，手动输入上一个用户的菜单才可以直接进去)，当我再刷新时会跳转 403, 功能正常

请问一下 动态菜单的鉴权，是如何进行的呢？ access.tsx 中的 canAdmin 不是每次都会执行吧？

**Comment by lgfinfo** [comment]
我想问的是icon 能不能自己加载
![image](https://user-images.githubusercontent.com/15934579/99790399-ff97f100-2b5e-11eb-92ff-51907031a2e6.png)

**Comment by chenshuai2144** [comment]
>  access.tsx 中的 canAdmin 不是每次都会执行吧

每次 initvalues 改变都会重新执行

**Comment by chenshuai2144** [comment]
@lgfinfo 

https://github.com/ant-design/pro-components/issues/363

看看这个 pr

**Comment by lgfinfo** [comment]
> @lgfinfo
> 
> [ant-design/pro-components#363](https://github.com/ant-design/pro-components/issues/363)
> 
> 看看这个 pr

已解决

**Comment by no13bus** [comment]
@lgfinfo  我发现按照这个pr，父级菜单确实显示了，但是子菜单还是没显示。我用的是ant pro v4

**Comment by chenshuai2144** [comment]
你用的确定一下要用 children 不是 routers

**Comment by no13bus** [comment]
@chenshuai2144  是children。数据格式就是这样的。

```json
const cc = [
    {
      "path": "/dashboard",
      "name": "dashboard",
      "icon": "dashboard",
      "children": [
        {
          "path": "/dashboard/analysis",
          "name": "analysis",
          "icon": "dashboard"
        },
        {
          "path": "/dashboard/monitor",
          "name": "monitor",
          "icon": "dashboard"
        },
        {
          "path": "/dashboard/workplace",
          "name": "workplace",
          "icon": "dashboard"
        }
      ]
    }
  ]
```

**Comment by chenshuai2144** [comment]
来个重现吧

**Comment by AndroidMilk** [comment]
> app.tsx 代码如下：
> ![image](https://user-images.githubusercontent.com/15334960/99763991-0579dc00-2b37-11eb-8424-b72adbe2814c.png)
> 
> 每次重新登录后，菜单是可以动态显示，以基本实现
> 
> access.tsx 中 , 我在canAdmin 里面 打算用当前地址栏地址与 登录用户的 动态菜单中的 url 做对比， 简单的实现鉴权
> ![image](https://user-images.githubusercontent.com/15334960/99764977-1d525f80-2b39-11eb-8a37-4e776314d978.png)
> 
> 结果遇上了2个问题：
> 
> 1. 当我通过点击动态菜单想进入相应功能页面时（随便点哪一个动态出来的菜单，都显示403），却显示了 403 页面 （access.tsx 中的 canAdmin 没打印日志，应该是没有执行）， 我如果刷新一下地址栏(或者地址栏回车 canAdmin方法里面的日志也输出了)，就好了， 其他的菜单也可以点进去了
>    ![image](https://user-images.githubusercontent.com/15334960/99764746-afa63380-2b38-11eb-81c0-076ec31319af.png)
> 2. 我通过地址栏输入上一个用户的菜单（不属于当前用户的）也可以进去(好像只出现在登录另一个用户时，手动输入上一个用户的菜单才可以直接进去)，当我再刷新时会跳转 403, 功能正常
> 
> 请问一下 动态菜单的鉴权，是如何进行的呢？ access.tsx 中的 canAdmin 不是每次都会执行吧？

您好，我现在也遇到了这样的问题，请问您是怎么解决的？

**Comment by zhangshuling** [comment]
> > app.tsx 代码如下：
> > ![image](https://user-images.githubusercontent.com/15334960/99763991-0579dc00-2b37-11eb-8424-b72adbe2814c.png)
> > 每次重新登录后，菜单是可以动态显示，以基本实现
> > access.tsx 中 , 我在canAdmin 里面 打算用当前地址栏地址与 登录用户的 动态菜单中的 url 做对比， 简单的实现鉴权
> > ![image](https://user-images.githubusercontent.com/15334960/99764977-1d525f80-2b39-11eb-8a37-4e776314d978.png)
> > 结果遇上了2个问题：
> > 
> > 1. 当我通过点击动态菜单想进入相应功能页面时（随便点哪一个动态出来的菜单，都显示403），却显示了 403 页面 （access.tsx 中的 canAdmin 没打印日志，应该是没有执行）， 我如果刷新一下地址栏(或者地址栏回车 canAdmin方法里面的日志也输出了)，就好了， 其他的菜单也可以点进去了
> >    ![image](https://user-images.githubusercontent.com/15334960/99764746-afa63380-2b38-11eb-81c0-076ec31319af.png)
> > 2. 我通过地址栏输入上一个用户的菜单（不属于当前用户的）也可以进去(好像只出现在登录另一个用户时，手动输入上一个用户的菜单才可以直接进去)，当我再刷新时会跳转 403, 功能正常
> > 
> > 请问一下 动态菜单的鉴权，是如何进行的呢？ access.tsx 中的 canAdmin 不是每次都会执行吧？
> 
> 您好，我现在也遇到了这样的问题，请问您是怎么解决的？



我最后没有用 canAdmin, 自己重新定义了一个的方法去判断

![image](https://user-images.githubusercontent.com/15334960/133010008-dc2c8221-ffd4-4877-851e-e4ac78f7fff8.png)

可能算是野路子吧，不过最后的最后，放弃了 antd pro  ...
