### ISSUE TITLE
🧐[问题] 怎么获取ProTable排序后,当前分页的数据?

### ISSUE THREAD

**Issue by matianhe3** [ant-design/ant-design-pro#7635]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/24929062/99771364-fe0cff80-2b43-11eb-83e4-961ee29dac7f.png)
我想要获取ProTable中的当前分页数据(排序之后),有什么方法,属性?
### 💻 示例代码
目前用这种方法获取排序后的sourceData, 有什么方法获取当前分页的排序后数据?
```
<ProTable
onChange={(page, ... sorter) => {console.log(soter} }
/>
```

**Comment by chenshuai2144** [comment]
可以用 postData，每次改变就会执行以下
