### ISSUE TITLE
👑 [建议]Antd Pro V5开放ui调试模式，展示umi 气泡工作台

### ISSUE THREAD

**Issue by renqi1996** [ant-design/ant-design-pro#7636]
### 🥰 建议描述

Antd Pro V5版本默认没有页面右下角umi气泡工作台，不方便新接入的同学学习并使用区块;

### 🧐 解决方案

建议package.json中，新增start:ui命令，同时需要devDependencies新增@umijs/preset-ui，展示气泡，方便页面调试开发；

```
"start:ui": "UMI_UI=1 umi dev",
```

**Comment by chenshuai2144** [comment]
手动装一下 @umijs/preset-ui 吧，使用量只有个位数，不要浪费大家的硬盘了
