### ISSUE TITLE
🧐[问题]build文件部署遇js bug卡死跳的500页如何自定义？

### ISSUE THREAD

**Issue by wulibaibao** [ant-design/ant-design-pro#7637]
### 🧐 问题描述
build文件夹打包上线，中间遇到js报错会跳一个500的错误页，这时候的页面返回首页是不能用的，js卡死，想要返回首页只能f5刷新页面，如何自定义？或者返回首页的实践改成location.href='/'

**Comment by chenshuai2144** [comment]
js 报错处理一下？理论上你不能写出任何 block 页面的错误的。不然整个 js 堆栈都要拐到了
