### ISSUE TITLE
🧐[问题] V5 build 失败

### ISSUE THREAD

**Issue by sunzhengbo** [ant-design/ant-design-pro#7638]
以下build的过程报的错误：

[Error: EINVAL: invalid argument, mkdir 'D:\Workspace\Develop\XSOM\angular10\ant-design-pro\dist\sites\:id\edit'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'D:\\Workspace\\Develop\\XSOM\\angular10\\ant-design-pro\\dist\\sites\\:id\\edit'
}
build failed
Error: build failed
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\@umijs\bundler-webpack\lib\index.js:138:27
    at finalCallback (D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\MultiCompiler.js:275:14
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\neo-async\async.js:2830:7
    at done (D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\neo-async\async.js:2925:13)
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\MultiCompiler.js:186:23
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\MultiCompiler.js:267:15
    at finalCallback (D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\Compiler.js:257:39)
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\Compiler.js:279:21
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\Compiler.js:480:22
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\neo-async\async.js:2830:7
    at done (D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\neo-async\async.js:3517:9)
    at writeOut (D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\lib\Compiler.js:369:23)
    at D:\Workspace\Develop\XSOM\angular10\ant-design-pro\node_modules\webpack\node_modules\mkdirp\index.js:48:53
    at FSReqCallback.oncomplete (fs.js:168:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@5.0.0-beta.0 build: `umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@5.0.0-beta.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sunzhengbo\AppData\Roaming\npm-cache\_logs\2020-11-22T01_55_04_748Z-debug.log

**Comment by RonMiu** [comment]
我也遇到同样问题，怎么解决

**Comment by sunzhengbo** [comment]
目前还不知道如何解决这个问题，因为项目是升级上来的，所以就把版本退回去了




sunzhengbo
sunzhengbo@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 晚上8:37
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] V5 build 失败 (#7638)





 
我也遇到同样问题，怎么解决

**Comment by chenshuai2144** [comment]
umi 修了，可以升级一下 umi 再试试

**Comment by sunzhengbo** [comment]
已经将umi升级到了3.2.27版本，还是不行。、
报错信息如下：







最后提个建议，能否先联系题主，等题主确实解决了问题，再关闭问题？？？


sunzhengbo
sunzhengbo@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 中午11:38
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] V5 build 失败 (#7638)





 
umi 修了，可以升级一下 umi 再试试

**Comment by ycjcl868** [comment]
umi build 在 windows 上生成动态路由页面会报错，因为动态路由路径是 `:id.html` ，在 windows 里是非法字符。

ref: https://github.com/umijs/umi/issues/5633

**Comment by chenshuai2144** [comment]
exportStatic 可以关掉，这个问题还挺麻烦的

**Comment by kaoding** [comment]
> `exportStatic` 可以关掉，这个问题还挺麻烦的

closed

**Comment by sunzhengbo** [comment]
好的
