### ISSUE TITLE
👑 [需求]V5权限管理，access都 改为数组，这样每个用户可以赋予多个角色或权限，每个页面可以被多个角色访问

### ISSUE THREAD

**Issue by jnyuzs** [ant-design/ant-design-pro#7641]
### 🥰 需求描述

👑 [需求]V5权限管理，access都 改为数组，这样每个用户可以赋予多个角色，每个页面可以被多个角色访问
### 🧐 解决方案
access都改为数组，可以是多个权限或角色

**Comment by ruanhailiang** [comment]
你做一层映射就可以了,比如role a === role.A || role.B

**Comment by FoggeOvO** [comment]
> 你做一层映射就可以了,比如role a === role.A || role.B

抱歉，大佬，这个具体该如何实现？
