### ISSUE TITLE
🧐组件中的数据加载不出来

### ISSUE THREAD

**Issue by ZidiHu** [ant-design/ant-design-pro#7643]
### 🧐 问题描述
截图中compact为{userPlan.plan}的值，截图中可以看到，写在select外面的{userPlan.plan}成功打印了出来，但是将{userPlan.plan}放在select里面作为defaultValue却没有显示。其他的组件也有一样的情况，都没有显示出来。
请问是不是因为我将Select或者Input这些组件包裹在description组件里的原因？感觉很奇怪，直接打印可以打印出来但是作为值传入defaultValue就无法显示。
另外：日期选择组件的值都是NAH不知道是什么原因。

请好心人帮忙解答，是不是我的代码有什么问题，谢谢！

### 💻 示例代码

<img width="816" alt="Screen Shot 2020-11-23 at 7 55 36 pm" src="https://user-images.githubusercontent.com/50161886/99943743-e3e25400-2dc5-11eb-83aa-4d13e60c9f4f.png">

### 🚑 其他信息

<img width="1313" alt="Screen Shot 2020-11-23 at 7 48 42 pm" src="https://user-images.githubusercontent.com/50161886/99943624-b4cbe280-2dc5-11eb-91ba-ec06f189f7e1.png">

**Comment by huntdream** [comment]
`defaultValue`是在组件挂载的时候去读取的，`userPlan.plan`应该是在挂载之后才有值的吧？

**Comment by ZidiHu** [comment]
> `defaultValue`是在组件挂载的时候去读取的，`userPlan.plan`应该是在挂载之后才有值的吧？

嗯嗯是的，我也考虑是这个原因，但是不知道怎么解决。确实会有一个一前一后的问题，请问有什么建议解决办法吗？谢谢你！

**Comment by huntdream** [comment]
数据到达之后，通过设置value传递进去就好了

**Comment by ZidiHu** [comment]
> 数据到达之后，通过设置value传递进去就好了

谢谢你，请问有类似事例代码吗？我现在是页面第一次加载取不到数据，要刷新一次才可以取到赋值的defaultValue。不好意思刚接触不久，还不太明白。

**Comment by huntdream** [comment]
可以参考一下
https://codesandbox.io/s/set-select-value-after-mounted-uttir

**Comment by chenshuai2144** [comment]
@ZidiHu  最简单判断加个 loading`，if(loading) return 'loading'`
