### ISSUE TITLE
Fetch Menu Data from Server

### ISSUE THREAD

**Issue by jhimanjhi** [ant-design/ant-design-pro#7646]
Hi, I'm having an issue the same as #3403  , but I think it's main problem was not resolved on that thread.

I'm using UmiJS and I want to fetch routes data from server, for example:

```
routes: [...fetchRoutesData()] //fetchRoutesData contains an httpRequest and returns an array of routes object.

// structure of routes object
routesObject = {
    name: 'sampleName',
    path: 'samplePath',
    component: 'SampleComponent',
  }
```

but it doesn't work. The menu does not display the routes fetched from the API.

Is this possible? or is there a way for me to ensure that fetchRoutesData() has been completed before my app uses the configuration? (I already tried async await here but still, the routes Data from API was not displayed in the Menu)

Thank you in advance.

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu

look here

**Comment by jhimanjhi** [comment]
Thank you very much, but I used UmiJS patchRoutes to solve my problem. 

https://umijs.org/docs/runtime-config#patchroutes-routes-
