### ISSUE TITLE
新Yarn create umi出来的V5项目，运行后，出现左右滚动条

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#7648]
新Yarn create umi出来的项目，运行后，出现左右滚动条
并且多语言栏也只出来一半，如下图：

![image](https://user-images.githubusercontent.com/32530210/100030448-83d3c800-2e2e-11eb-999d-f8cbd1050362.png)

**Comment by 123456wjw** [comment]
+1，请问您解决这个问题了吗

**Comment by xyzabc0004** [comment]
没有，我暂时放弃V5了。等正式出来。

**Comment by 123456wjw** [comment]
![image](https://user-images.githubusercontent.com/37201576/100312676-e7f0ba80-2fed-11eb-82ca-0e82e96fe79a.png)
找到了 由这个margin引起的

**Comment by xyzabc0004** [comment]
@123456wjw 点赞！

**Comment by chenshuai2144** [comment]
fixed
