### ISSUE TITLE
🐛建议V4与V5分开板块来解决问题吧！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7649]
### 🐛 bug 描述

整个一个社区感觉好乱，V4与V5是两个不同的版本，问题却混在一起提交，找答案都不好找！

V4，V5分开讨论多好，多直观！

只是建议！

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
v4 和 v5 是差不多的，等合并了就好了
