### ISSUE TITLE
antd Upload component is not working...

### ISSUE THREAD

**Issue by LeeGeonho** [ant-design/ant-design-pro#765]
Upload component of antd is not working in antd pro.
(both safari and chrom browser on iOS device)

But, Works well sample in antd upload docs(https://ant.design/components/upload/) on iOS device

i tested to add upload component in login route and I touched, but there was no response.
![img_0085](https://user-images.githubusercontent.com/9799339/35136152-3c79b93e-fd25-11e7-8b64-3122aadfd482.PNG)

One thing I found that works well touch again after long press the button

**Comment by chenshuai2144** [comment]
I can use it. . .

**Comment by LeeGeonho** [comment]
I added it Component in Login.js file (path : src/routes/User/)
(Only modify this part after git clone)
```
render() {
    .....
    return (
      <div className={styles.main}>
        <Login
          defaultActiveKey={type}
          onTabChange={this.onTabChange}
          onSubmit={this.handleSubmit}
        >
          ......
        </Login>

        **<Upload {...props}>
          <Button>
            <Icon type="upload" /> Click to Upload
          </Button>
        </Upload>**
      </div>
    );
  }
```

Works fine other device(android, pc). only occurs on iOS device.

**Comment by chenshuai2144** [comment]
Development environment code compiled to ES5, there may be this reason

**Comment by LeeGeonho** [comment]
@chenshuai2144 
Seems to be a problem in the development environment?
Please let me know where to fix it.

**Comment by chenshuai2144** [comment]
ecause I also use antd.pro and upload. After deployment is normal. Even iphone5s.
Maybe you should try the deployment after the test。

**Comment by xiak** [comment]
I have the same issue on IphoneX and Iphone 7

@LeeGeonho  Do you have resolved this issue?

**Comment by LeeGeonho** [comment]
@xiak i was disabled `FastClick` in `src/index.js` file then it works fine.

**Comment by xiak** [comment]
Thanks ◕‿◕
