### ISSUE TITLE
版本升级出现问题（from  2.2 to 4.0）

### ISSUE THREAD

**Issue by lihuiheng** [ant-design/ant-design-pro#7650]
版本从2.2升级到4.0版本出现问题，根据官方升级提示还是会出现* antd/es/space in ./node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.js
* antd/es/space/style in ./node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.js这样的问题。无法一次性解决。

**Comment by chenshuai2144** [comment]
升级 antd 到 antd@4
