### ISSUE TITLE
🐛[BUG]antd版本为4.0+时候的底部缩回按钮点击，侧边栏无法收回

### ISSUE THREAD

**Issue by tom-chanafanghua** [ant-design/ant-design-pro#7652]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
   4.0.0
- umi 版本
  umi@3, Pro V4
- 浏览器环境
- 开发环境 [e.g. mac OS]
  window

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/74945644/100050237-ebe8d500-2e53-11eb-8667-5ee2eb813ff2.png)

**Comment by tom-chanafanghua** [comment]
在同事mac和朋友的电脑上多次测试，都有这种问题

**Comment by xyzabc0004** [comment]
刚Yarn了一个V5，也是这样

**Comment by tom-chanafanghua** [comment]
https://procomponents.ant.design/components/layout/    官方的这个页面的侧边栏好像都没办法收回。。。

**Comment by pzc666** [comment]
我也遇到了这个问题，点击底部按钮菜单栏没有收回
preview 页面稳定复现
https://preview.pro.ant.design/dashboard/analysis?splitMenus=false&primaryColor=daybreak&navTheme=light

**Comment by lovesL** [comment]
同上V4昨天刚 试了 无法收回

**Comment by lspeer** [comment]
一样

**Comment by leitingx762** [comment]
+1

**Comment by zhengchalei** [comment]
mark

**Comment by lspeer** [comment]
<ProLayout> 把breakpoint设为false

**Comment by tanqiyuan** [comment]
我在侧面板伸缩点击事件 const handleMenuCollapse = payload => {}  加入了一个console.log(payload);  发现触发了2次payload，一次false，一次true，不知道什么原因导致的重复事件，从而导致缩不回去。 只能自己加了个防止重复点击解决了：
```
 const [isClick, setClick] = useState(false);  
 const handleMenuCollapse = payload => {
    if (dispatch) {
      if(!isClick){
        dispatch({
          type: 'global/changeLayoutCollapsed',
          payload
        });
        setClick(true);
        setTimeout(()=>{setClick(false)},500);
      }
    }
  };
```

**Comment by chenshuai2144** [comment]
Antd的锅 周一就好了

可以配置 `breakpoint=false` 先绕过一下
