### ISSUE TITLE
🧐[问题] v2版本 Cannot find module '@/utils/utils.less' from 'D:\project\idea\ant-design-pro\my-project\src\pages\Account\Center

### ISSUE THREAD

**Issue by mynameiscuining** [ant-design/ant-design-pro#7653]
新手,求教
![image](https://user-images.githubusercontent.com/16378568/100054873-e5f7f180-2e5d-11eb-9d64-3de8a945ae7e.png)

**Comment by AHIMOTU** [comment]
#7712

**Comment by haianweifeng** [comment]
method one
import url(relative path or absolute path) 
method two
import '~@/utils/utils.less;
method three
delete the code about antd-theme-webpack-plugin in plugin.config.js, then import '@/utils/utils.less';
