### ISSUE TITLE
🧐[问题]tree 异步加载数据

### ISSUE THREAD

**Issue by LiuYuanZhe** [ant-design/ant-design-pro#7655]
### 🧐 问题描述
使用tree组件异步加载数据时加载数据不正常，之前用3时可以

### 💻 示例代码
//list是需要挂到children的数据
treeNode.props.data.children = list
setTimeout(() => {
  this.setState({
     treeData: [...this.state.treeData],
  });
}, 3000);
render（）{
                <Tree 
                  checkable
                  onSelect={this.onselectTree}
                  onCheck={this.onCheck}
                  loadData={this.onLoadData} 
                  treeData={this.state.treeData} 
                />
}

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17759888/100058239-e8f5e080-2e63-11eb-9b5f-0921f41bedc0.png)

**Comment by chenshuai2144** [comment]
看antd的官网demo
