### ISSUE TITLE
🧐[问题] 添加landing page index 重定向 redirect 路由 routers.js

### ISSUE THREAD

**Issue by Dragon201701** [ant-design/ant-design-pro#7657]
### 🧐 问题描述

怎样在根增加一个landing page? 就是当用户访问 / 时不需要登录即可访问到welcome这种，我应该怎么修改路由？

### 🚑 其他信息

我想让用户登录/注册之后会被引导至/welcome页面，然后我在用户/user平级的地方加一个诸如/index这种，我应该怎样修改routes.ts?
`

export default [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
      {
        name: 'register',
        path: '/user/register',
        component: './user/register',
      },
      {
        name: 'register-result',
        path: '/user/register-result',
        component: './user/register-result'
      },
      {
        component: '404',
      },
    ],
  },
  /*{
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      {
        path: '/',
        redirect: './welcome',
      },
      {
        path: '/welcome',
        name: 'welcome',
        component: './welcome',
      }
    ]
  },*/
  {
    path: '/',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/BasicLayout',
        authority: ['admin', 'user'],
        routes: [
          {
            path: '/',
            redirect: '/main',
          },
          {
            path: '/main',
            name: 'main',
            icon: 'smile',
            component: './main',
          },
          {
            path: '/admin',
            name: 'admin',
            icon: 'crown',
            component: './Admin',
            authority: ['admin'],
            routes: [
              {
                path: '/admin/sub-page',
                name: 'sub-page',
                icon: 'smile',
                component: './main',
                authority: ['admin'],
              },
            ],
          },
          {
            name: 'list.table-list',
            icon: 'table',
            path: '/list',
            component: './ListTableList',
          },
          {
            component: './404',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    component: './404',
  },
];

`

**Comment by Dragon201701** [comment]
部分修复。但是这个貌似在本地跑跟服务器跑有点不太一样，不知道为什么本地跑会引导到/user/login但是服务器端目前会在/welcome里

`{
    path: '/welcome',
    component: '../layouts/BlankLayout',
    routes: [
      {
        path: '/welcome',
        name: 'welcome',
        component: './welcome',
      }
    ]
  },
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
      {
        name: 'register',
        path: '/user/register',
        component: './user/register',
      },
      {
        name: 'register-result',
        path: '/user/register-result',
        component: './user/register-result',
      },
      {
        component: '404',
      },
    ],
  },`

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/100565628-03fe9f80-32ff-11eb-9ba5-f4950ec05ad5.png)


这个部分也要做改动的，它拦截了所有请求

**Comment by AmagiDDmxh** [comment]
@chenshuai2144  求下主题

**Comment by chenshuai2144** [comment]
德古拉 去搜一下 各个IDE都有
