### ISSUE TITLE
菜单栏使用自定义iconfont

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#7658]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/100074054-3b8dc780-2e79-11eb-964d-0d1cc4bd3a89.png)
![image](https://user-images.githubusercontent.com/27960630/100074082-45172f80-2e79-11eb-8d45-372bd5486b97.png)
![image](https://user-images.githubusercontent.com/27960630/100074095-4b0d1080-2e79-11eb-92c3-8f9334f67354.png)
我是按照这弄的 https://github.com/ant-design/ant-design-pro/pull/3517

### 🚑 其他信息
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.0.19",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.5.0",
    "@ant-design/pro-table": "^2.9.16",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.8.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont

看这里，有很详细的例子

**Comment by HQ1363** [comment]
> https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont
> 
> 看这里，有很详细的例子

不行，不管用，不适用于不同版本pro-layout下的情况

**Comment by HQ1363** [comment]
> > https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont
> > 看这里，有很详细的例子
> 
> 不行，不管用，不适用于不同版本pro-layout下的情况

或者更详细的说，一级菜单 icon可以正常展示，二级不可以了

**Comment by chenshuai2144** [comment]
二级不展示是 featrue ，故意这么做的

**Comment by HQ1363** [comment]
> 二级不展示是 featrue ，故意这么做的

这。。。  捣鼓了半天，居然是feature。话说有办法二级也展示吗

**Comment by chenshuai2144** [comment]
自己用 meunItemRender 渲染出来
