### ISSUE TITLE
新项目git下来报错！

### ISSUE THREAD

**Issue by rexrui** [ant-design/ant-design-pro#766]
Module build failed: Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

**Comment by rexrui** [comment]
npm start 时

**Comment by chenshuai2144** [comment]
你发一下你的node版本？
我们需要 8.0版本

**Comment by rexrui** [comment]
![image](https://user-images.githubusercontent.com/3296149/35137581-1b4ae8b4-fd25-11e7-901a-edfc05ac0932.png)
![image](https://user-images.githubusercontent.com/3296149/35137666-930589f4-fd25-11e7-8917-9b5dd86e7d11.png)

**Comment by chenshuai2144** [comment]
https://github.com/babel/babel/issues/7177
这个也许能解决你的问题
