### ISSUE TITLE
🧐[问题]npm install 后 npm run build 失败

### ISSUE THREAD

**Issue by cater111** [ant-design/ant-design-pro#7660]
提示：
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'

今天刚出现的，昨天还可以。
antd用的3.x

**Comment by GitterYang** [comment]
同样的问题，npm start就报chencheng大佬的错误...

**Comment by GitterYang** [comment]
> 同样的问题，npm start就报chencheng大佬的错误...

antd版本4.0

**Comment by cater111** [comment]
@GitterYang  解决了吗？

我这里还是不行的呢

**Comment by cater111** [comment]
@GitterYang   自己业务的package.json中 babel-plugin-import 指定1.13.0之前的版本就可以了。

**Comment by GitterYang** [comment]
@cater111 多谢了，可以了。umijs那边修复了，本地删除lock文件和node_module文件，重新install就可以了

**Comment by chenshuai2144** [comment]
umi 的锅

`git clean -dfx && npm i`
