### ISSUE TITLE
请问v5版，侧边栏左右切换的如何从底部配置到顶部切换？侧边栏底部如何自定义按钮，改为比如配置按钮？

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#7662]
如下图所示，
1.侧边栏底部如何自定义按钮，改为比如配置按钮

![微信截图_20201125120228](https://user-images.githubusercontent.com/37678805/100181919-506c6880-2f16-11eb-8ff3-c3b32eb17097.png)

**Comment by caoyanangithup** [comment]
真他玛lj
