### ISSUE TITLE
Problem with SiderMenu when using dynamic routing with parameters

### ISSUE THREAD

**Issue by iloveip** [ant-design/ant-design-pro#7664]
Hi there,

I'm using dynamic routing with parameters. In my config.js file I have:

```
{
  path: '/orders',
  name: 'All orders',
  icon: 'file',
  component: './OrdersList'
},
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order'
}
```

The problem is that when I visit a page for a single order (`/orders/:id`), the parent menu item (`/orders`) in SiderManu is set as selected and the corresponding breadcrumb for All orders in PageHeader doesn't have a url on it.

If I get the value from RouteContext, I see that matchMenuKeys prop has both paths (`["/orders", "/orders/:id"]`) in its array. May be that's the problem?

How can I fix that

**Comment by chenshuai2144** [comment]
you need a litter sort。


```
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order'
},
{
  path: '/orders',
  name: 'All orders',
  icon: 'file',
  component: './OrdersList'
},
```

**Comment by iloveip** [comment]
You mean, that I need to change the order in `config.js`?  I tried it but it didn't help. All Orders are still highlighted as selected in SiderManu and there are still `["/orders", "/orders/:id"]` in matchMenuKeys prop.

**Comment by chenshuai2144** [comment]
sorry, you can try `hideInBreadcrumb:true` 
eg:
```json
{
  path: '/orders/:id',
  hideInMenu: true,
  component: './Order'
},
{
  path: '/orders',
  name: 'All orders',
  icon: 'file',
  hideInBreadcrumb:true,
  component: './OrdersList'
},
```

**Comment by iloveip** [comment]
Thanks again. But I don't want to hide it from breadcrumbs.

The problem is that when I visit a page for a single order (`/orders/:id`), the parent menu item (`/orders`) in SiderMenu is highlighted. Please see the screenshot. I'm on page `/orders/9`, but in SiderMenu the parent page All orders ("Мои заявки") is active.

Also I can't click on All orders ("Мои заявки") in breadcrumbs, as it doesn't have a url on it. 

<img width="1265" alt="Снимок экрана 2020-12-01 в 11 14 10" src="https://user-images.githubusercontent.com/4873895/100714176-72f2fb80-33c6-11eb-898d-b7d159687e4d.png">

**Comment by chenshuai2144** [comment]
you can use menuItemRender 

<html>
<body>


menuItemRender | 自定义菜单项的 render 方法 | (itemProps: MenuDataItem, defaultDom: React.ReactNode, props: BaseMenuProps) => ReactNode | -
-- | -- | -- | --
subMenuItemRender | 自定义拥有子菜单菜单项的 render 方法 | (itemProps: MenuDataItem) => ReactNode | -


</body>
</html>
