### ISSUE TITLE
antd-pro-v4  umi  request 请求一个接口 返回 status: 404,error: "Not Found" 的时候 redux的数据状态： loading：{ global一直为true, effects里面对应的接口状态也一直是true }

### ISSUE THREAD

**Issue by kevinzl** [ant-design/ant-design-pro#7665]

**Comment by kevinzl** [comment]
antd-pro-v4  umi  request

场景：请求一个接口 返回 status: 404,error: "Not Found" 的时候 

redux的数据状态： loading：{ global一直为true, effects里面对应的接口状态也一直是true }

这中情况导致页面或者按钮一直在loading中，按钮无法再次发起请求，必须刷新F5页面才可以重新发起请求，
按说请求只要结束了，不管接口是返回什么， 这个状态就应该为false才合理吧

**Comment by chenshuai2144** [comment]
处理一下报错，这个是整个 redux 挂掉了。

无脑一点可以用 onError

https://umijs.org/plugins/plugin-dva#dva-%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE
