### ISSUE TITLE
🐛[问题]V4权限不生效

### ISSUE THREAD

**Issue by Statfine** [ant-design/ant-design-pro#7666]
### 🐛 bug 描述

页面的localstorage添加权限字段“antd-pro-authority”同时设置为"visitor",同样可以打开/dashboard/analysis等控台页面

### 📷 复现步骤

1. yarn create umi app
2. npm i
3. npm start
4. 打开页面
5. 浏览器控制台localstorage设置antd-pro-authority：antd-pro-authority，刷新页面

### 🏞 期望结果

因为'/'设置了authority: ['admin', 'user'],希望不在权限数组里面的权限不能打开页面，同时侧边栏也不显示

### © 版本信息

- Ant Design Pro 版本: 4.3.0
- umi 版本： 3.2.14
- 浏览器环境：chrome
- 开发环境 Mac 10.15.7

### 🚑 其他信息

![1606289775958](https://user-images.githubusercontent.com/4608910/100196613-1611c400-2f34-11eb-909e-067befb74d8c.jpg)

**Comment by fenglijunnb** [comment]
@Statfine 哥们，你这个问题解决了吗

**Comment by Leskur** [comment]
去看 src/utils/utils.ts 文件。

**Comment by fenglijunnb** [comment]
@Leskur 跟这个没关系啊，你就是给它注释了也解决不了问题的

**Comment by Leskur** [comment]
@fenglijunnb 追踪了一下，发现是由于一开始 menuDataRef 的值为 [] 导致。
[src/layouts/BasicLayout.tsx](https://github.com/ant-design/ant-design-pro/blob/ecc2b42c9558fcc746891414ebec55ecaeae87e5/src/layouts/BasicLayout.tsx#L98)
```javascript
const menuDataRef = useRef<MenuDataItem[]>([]);

**Comment by chenshuai2144** [comment]
@fenglijunnb 随便怎么改一下props，或者强行 setState 一下

**Comment by fenglijunnb** [comment]
@chenshuai2144 你的意思就是不要让其为空是吗

**Comment by chenshuai2144** [comment]
多触发几次render方法就可以不为空

**Comment by fenglijunnb** [comment]
@chenshuai2144 这个确实不太理解多次render是什么个意思

**Comment by chenshuai2144** [comment]
多次 setState，每次 setState 就会触发 render，每次 render 就会重新计算的

**Comment by fenglijunnb** [comment]
@chenshuai2144 那么是在base页面进行操作对吧

**Comment by Mr-zhuxing** [comment]
> @fenglijunnb 追踪了一下，发现是由于一开始 menuDataRef 的值为 [] 导致。
> [src/layouts/BasicLayout.tsx](https://github.com/ant-design/ant-design-pro/blob/ecc2b42c9558fcc746891414ebec55ecaeae87e5/src/layouts/BasicLayout.tsx#L98)
> 
> ```js
> const menuDataRef = useRef<MenuDataItem[]>([]);
> ```

嗯，每次刷新页面的时候menuDataRef.current第一次的确实是空值。我寻思，这权限管理这么大的问题，为啥官方不去解决呢

**Comment by Mr-zhuxing** [comment]
> 多次 setState，每次 setState 就会触发 render，每次 render 就会重新计算的

虽然每次render会重新计算，但是menuDataRef.current的值永远都是当前角色下的菜单，其他角色的菜单没有。在Authorized组件中还是没法验证

**Comment by lishaoh** [comment]
而且现在接口返回权限重新render后，Authorized组件验证的路由不是从0开始

**Comment by lishaoh** [comment]
通过接口返回权限，刷新页面后该有的菜单没有出来，还需要选中其他菜单才会出来

**Comment by YoursOwen** [comment]
有解决方案吗？

**Comment by YoursOwen** [comment]
> 有解决方案吗？

![image](https://user-images.githubusercontent.com/42412564/104807958-be9a2100-581d-11eb-8cbd-78a69bc8cc2d.png)
![image](https://user-images.githubusercontent.com/42412564/104807973-dd98b300-581d-11eb-9493-489bb2db3e3e.png)
写了个hack 方法，仅供参考

**Comment by hejun200613224** [comment]
> > 有解决方案吗？
> 
> ![image](https://user-images.githubusercontent.com/42412564/104807958-be9a2100-581d-11eb-8cbd-78a69bc8cc2d.png)
> ![image](https://user-images.githubusercontent.com/42412564/104807999-1afd4080-581e-11eb-8b57-c9be55441dcb.png)
> 
> 写了个hack 方法，仅供参考

这里应该是有2个bug，而不是一个：
**bug1**
src/layouts/BasicLayout.tsx menuDataRef.current第一次被调用时为[]，如果是页面跳转，此时location.pathname变化会触发二次调用，无问题；如果是url+回车，或者直接reload，由于没有location.pathname修改，因此没有二次调用，出现bug；
**bug2**
menuDataRef.current的赋值语句，写在postMenuData里，这里获取到的menuData已经是filter过的了，没有权限的页面不会出现在这里，导致的结果是判断权限时找不到菜单，因而返回undefined误判断为是不鉴权；

这里给出我的修复方案（非最佳）
**fix1**
修改authorized的useMemo为useState：
  const [authorized, setAuthorized] = useState({
    authority: undefined,
  })
修改menuDataRef.current的赋值处为：
  const currentMenu = getMatchMenu(location.pathname || '/', menuList).pop()
  setTimeout(() => {
    setAuthorized(currentMenu || {
      authority: undefined,
    });
  }, 0)

**fix2**
将上述赋值语句挪到menuDataRender，此处参数为filter前的菜单list，可以修复bug2：
  menuDataRender={menuList => {
    const currentMenu = getMatchMenu(location.pathname || '/', menuList).pop()
    setTimeout(() => {
      setAuthorized(currentMenu || {
        authority: undefined,
      });
    }, 0)
    return menuDataRender(menuList)
  }}

**Comment by night1008** [comment]
`
const authorized = useMemo(
    () => getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
      authority: undefined,
    },
    [location.pathname],
 );
`
替换成
`
const initAuthorized = {
    authority: 'unknown'
}
const [authorized, setAuthorized] = useState<MenuDataItem>(initAuthorized);
useEffect(() => {
    setAuthorized(getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || initAuthorized);
}, [location.pathname]);
`

**Comment by Raja0sama** [comment]
Thanks you @hejun200613224, That worked.

**Comment by chj6** [comment]
`menuDataRender={menuList => {
  const currentMenu = getMatchMenu(location.pathname || '/', menuList).pop()

  setTimeout(() => {
    setAuthorized(currentMenu || { authority: undefined });
  }, 0)

  return menuDataRender(menuList)
}}`
这种做法，在pro-layout 6.19.3上会引起性能问题。

**Comment by hejun200613224** [comment]
临时处置而已。等待官方修复。

**Comment by chenshuai2144** [comment]
v5 已经发布，更换了方式

**Comment by hejun200613224** [comment]
> ```
> menuDataRender={menuList => {
>   const currentMenu = getMatchMenu(location.pathname || '/', menuList).pop()
> 
>   setTimeout(() => {
>     setAuthorized(currentMenu || { authority: undefined });
>   }, 0)
> 
>   return menuDataRender(menuList)
> }}
> ```
> 
> 这种做法，在pro-layout 6.19.3上会引起性能问题。

做了一个新的实现方式，避免了上述性能问题。
如下
```
// .....
 import _ from 'lodash'

const BasicLayout = (props) => {
    // .......
    const menuDataRef = useRef([]);
    const [authorized, setAuthorized] = useState({
      authority: undefined,
    });
    const [menuDataLen, setMenuDataLen] = useState(0)
  
    const setMenuDataOnce = useMemo(() => _.once((menuData) => _.defer(() => {
      // defer调用防止在本级组件render过程中再次触发render
      menuDataRef.currnet = menuData;
      setMenuDataLen(menuData?.length || 0);
    })), [])
  
    const setValidMenuData = useCallback((menuData) => {
      // 根据menuData的length判定是否有效值
      if (menuData?.length === menuDataLen) {
        // once方法只能有效调用一次，由于menuData在实际应用中不是频繁变动的，但是由menuDataRender每次获取到的实例不同，故此判定。如果涉及到动态router则需要额外的逻辑。
        setMenuDataOnce(menuData)
      }
    }, [menuDataLen, setMenuDataOnce])
  
    // menuDataLen 变化后触发useEffect更新权限信息。
    useEffect(() => {
      if (menuDataLen) {
        setAuthorized(getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
          authority: undefined,
        })
      }
    }, [menuDataLen, location.pathname])

    // ......

    return (
    <ProLayout 
    {/* ...... */}
    menuDataRender={(menuData) => {
      // 从menuDataRender方能取到未经filter的完整menuData
      setValidMenuData(menuData);
      return menuDataRender(menuData);
    }}
    >
        {
        // 判断menuDataLen有效值后再进一步判断权限，避免权限不可用时（尚未获取到menuData时）已经触发子组件渲染，并越权调用子组件请求的问题
        Boolean(menuDataLen) && (
            <Authorized authority={authorized.authority} noMatch={noMatch}>
              {children}
            </Authorized>
        )}
    </ProLayout>
    )
}
```
虽然能解决问题，但是依然不是特别优雅的方式。
建议方便的话，尽快升级到V5吧。
