### ISSUE TITLE
🧐[问题]V5 在routers.ts配置的路由，如何重定向到子路由

### ISSUE THREAD

**Issue by sunzhengbo** [ant-design/ant-design-pro#7668]
{
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        icon: 'smile',
        component: './Welcome',
      }
    ],
  },

如上述的路由，怎么从admin，重定向到admin/sub-page ???

**Comment by chenshuai2144** [comment]
和v4 一样。

```
{
    path: '/',
    redirect: '/welcome',
  },
```

**Comment by sunzhengbo** [comment]
你们关闭问题这么随意吗？都没有和提问者事先沟通一下就直接关闭了，还有什么叫和V4一样，我直接上手V5，你和提V4 ？？？


    {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;'users',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path:&nbsp;'/users',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;icon:&nbsp;'user',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;authority:&nbsp;['Administrator'],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;routes:&nbsp;[
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;'list',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path:&nbsp;'/users/list',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;component:&nbsp;'./users/list',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;'create',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path:&nbsp;'/users/create',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;component:&nbsp;'./users/create',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;},




上面的路由，当我的uri是/users时，我怎么才能重定向到/users/list


你说的方式我没有成功。。。


sunzhengbo
sunzhengbo@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 下午5:38
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题]V5 在routers.ts配置的路由，如何重定向到子路由 (#7668)





 
和v4 一样。
 {     path: '/',     redirect: '/welcome',   },

**Comment by chenshuai2144** [comment]
举一反三吧，我们不会给你写代码的，只会告诉你怎么用

**Comment by Jiexiansen** [comment]
加个重定向喽: `redirect: '/users/list'`
