### ISSUE TITLE
🧐[问题]V5的git commit钩子生效，V4的没生效

### ISSUE THREAD

**Issue by GloriaCHL** [ant-design/ant-design-pro#7669]
### 🧐 问题描述

用 `yarn create umi` 新建了个 ant design pro v4 的项目，发现提交的时候 git 的语法检查钩子没生效。故意在代码里引了个没install的包，没被拦截：
![image](https://user-images.githubusercontent.com/10557315/100204892-66daea00-2f3f-11eb-9c67-39250719389f.png)
成功commit了。手动运行了 `yarn lint-staged:js` 也没有报错：
![image](https://user-images.githubusercontent.com/10557315/100204950-765a3300-2f3f-11eb-9c25-41ec27ddb798.png)

但是 V5 同样的操作就能够成功拦截我的commit。
![image](https://user-images.githubusercontent.com/10557315/100205194-c3d6a000-2f3f-11eb-90cb-7019e7c2df7f.png)

想请教下，是V4已经放弃git钩子需要用户自己配置吗？还是官方的问题？

**Comment by chenshuai2144** [comment]
试试 `rm -rf .git/hooks`，然后再安装依赖

**Comment by GloriaCHL** [comment]
> 试试 `rm -rf .git/hooks`，然后再安装依赖

没效果。还试了整个.get 都删了，还是没作用。我在linux和mac两台系统上试过了，同样情况。

**Comment by chenshuai2144** [comment]
删除之后要重新安装依赖
