### ISSUE TITLE
Noification出现滚动条

### ISSUE THREAD

**Issue by DragonT** [ant-design/ant-design-pro#767]
![image](https://user-images.githubusercontent.com/7319029/35138372-29f65ef8-fd29-11e7-90e5-a5c3100058c9.png)
升级antd 到3.1.3Notification出现滚动条。代码还是之前的代码 没有做修改 使用antd 3.0.0的话是正常的

**Comment by unrealsmart** [comment]
额，滚动条在哪儿？

**Comment by DragonT** [comment]
![image](https://user-images.githubusercontent.com/7319029/35138934-c00e2108-fd2b-11e7-8926-f5950d0e5c95.png)

**Comment by chenshuai2144** [comment]
大兄弟 这个应该叫响应式设计

**Comment by afc163** [comment]
应该是个问题，这里没必要出现切换按钮。

**Comment by chenshuai2144** [comment]
@afc163 那具体尺度是多少？

**Comment by unrealsmart** [comment]
哈哈哈哈

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/c9d73978dd2694f9d2bd0111f82a20d237f83621#r26928989

**Comment by unrealsmart** [comment]
```
Push failed: Failed with error: unable to access 'https://github.com/ant-design/ant-design-pro.git/': The requested URL returned error: 403
```
为啥`push`不了

**Comment by chenshuai2144** [comment]
你没权限 403

**Comment by unrealsmart** [comment]
那我想 push 个代码该如何操作？

**Comment by afc163** [comment]
自己去搜搜 GitHub 玩法吧，总不能我想给 http://github.com/facebook/react push 代码就 push 吧。

**Comment by DragonT** [comment]
不是响应式的问题 好像第一个tab左间距的问题

**Comment by unrealsmart** [comment]
哈哈，`push success`，歇麻烦的。
