### ISSUE TITLE
🐛[BUG] Pro V5  Umi Request  Response 和预期不一样

### ISSUE THREAD

**Issue by zhengchalei** [ant-design/ant-design-pro#7670]
https://www.yuque.com/docs/share/5e6d7fa5-712d-431c-808d-e3e94e94a25c?# 《Pro V5  Umi Request  Response 和预期不一样》

```js
const codeMessage = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  405: '请求方法不被允许。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
};

/**
 * 异常处理程序
 */
const errorHandler = (error: ResponseError) => {
  const {response, data} = error;
  // 这里拿到的 data 和 response 返回的 data有差异, 不一致
  console.log(data)
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const {status, url} = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  return data;
};

const jwtInterceptor = (url: string, options: RequestOptionsInit) => {
  // 判断是否有 token
  const token = localStorage.getItem('token');
  if (token) {
    return {
      url,
      options: {
        ...options,
        interceptors: true,
        headers: {
          ...options.headers,
          Authorization: `Bearer ${token}`,
        },
      },
    };
  }
  return {url, options};
}

const getDataAndPageInterceptor = (url: string, options: RequestOptionsInit) => {
  // 判断是否有自行添加参数或者 body 为空
  if (options.method === "get" && options.data && url.indexOf("?") < 0) {
    const { pageSize, current, ...data } = options.data;
    const search = {...data, current, size: pageSize}
    return  {url: `${url}?${qs.stringify(search)}`, options};
  }

  return {url, options};
}


const errResponseInterceptor = async (response: Response, options: RequestOptionsInit) => {
  const {success, code, msg} = await response.clone().json();
  if (!success) {
    // message.error(msg);
    if (code === 500) {
      // 处理...
    }
    if (code === 401) {
      // 处理...
      localStorage.clear();
      history.push('/user/login');
    }

    if (code === 403) {
      // 处理...
    }
  }
  return {success, code, msg};
}

export const request: RequestConfig = {
  errorHandler,
  requestInterceptors: [
    jwtInterceptor,
    getDataAndPageInterceptor
  ],
  responseInterceptors: [
    errResponseInterceptor
  ],
};
```

![image](https://user-images.githubusercontent.com/31665079/100213881-2a60bb80-2f4a-11eb-9d34-35f15b72c6ca.png)
![image](https://user-images.githubusercontent.com/31665079/100213892-2c2a7f00-2f4a-11eb-83c5-b74153227c6d.png)
![image](https://user-images.githubusercontent.com/31665079/100213896-2df44280-2f4a-11eb-9864-7a7e7a700759.png)

**Comment by chenshuai2144** [comment]
你的预期是什么？

**Comment by zhengchalei** [comment]
> 你的预期是什么？

我预期是图2拿到的响应, 但是图三为啥拿到的是这样的.
我看到好像 Prov5中 umi 有一个 error filter 过滤响应信息

我贴出了我的配置信息, 我不确定是不是我的配置问题还是, 因为 这个 errorHandler 的原因

文件在 : `src\.umi\plugin-request`

requestMethodInstance = extend({
    errorHandler: (error: RequestError) => {
      // @ts-ignore
      if (error?.request?.options?.skipErrorHandler) {
        throw error;
      }
      let errorInfo: ErrorInfoStructure | undefined;
      if (error.name === 'ResponseError' && error.data && error.request) {
        const ctx: Context = {
          req: error.request,
          res: error.response,
        };
        errorInfo = errorAdaptor(error.data, ctx);
        error.message = errorInfo?.errorMessage || error.message;
        error.data = error.data;
        error.info = errorInfo;
      }
      errorInfo = error.info;

      if (errorInfo) {
        const errorMessage = errorInfo?.errorMessage;
        const errorCode = errorInfo?.errorCode;
        const errorPage =
          requestConfig.errorConfig?.errorPage || DEFAULT_ERROR_PAGE;

        switch (errorInfo?.showType) {
          case ErrorShowType.SILENT:
            // do nothing
            break;
          case ErrorShowType.WARN_MESSAGE:
            message.warn(errorMessage);
            break;
          case ErrorShowType.ERROR_MESSAGE:
            message.error(errorMessage);
            break;
          case ErrorShowType.NOTIFICATION:
            notification.open({
              message: errorMessage,
            });
            break;
          case ErrorShowType.REDIRECT:
            // @ts-ignore
            history.push({
              pathname: errorPage,
              query: { errorCode, errorMessage },
            });
            // redirect to error page
            break;
          default:
            message.error(errorMessage);
            break;
        }
      } else {
        message.error(error.message || 'Request error, please retry.');
      }
      throw error;
    },
    ...requestConfig,
  });

**Comment by chenshuai2144** [comment]
useRequest 做了一些封装，你可以直接用 umi-request，表现和 v4 相同了

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/request-cn

看看这里，你需要以一个拦截器了
