### ISSUE TITLE
🧐[问题]Input.TextArea如何获取原生dom节点，需要通过原生节点的selectionStart获取光标位置

### ISSUE THREAD

**Issue by zhaobosky** [ant-design/ant-design-pro#7671]
### 🧐 问题描述

Input.TextArea 无法取到原生的dom节点，Input组件可以通过ref.input取得
主要是为了获取textarea中光标的位置，对光标前后的字符串进行处理

### 💻 示例代码

![image](https://user-images.githubusercontent.com/22151144/100222106-934d3100-2f54-11eb-8107-0fd086195e29.png)

### 🚑 其他信息

Input组件
![image](https://user-images.githubusercontent.com/22151144/100221875-3baec580-2f54-11eb-8cc4-b493c8b0bd69.png)
Input.TextArea组件
![image](https://user-images.githubusercontent.com/22151144/100221979-6862dd00-2f54-11eb-9b8a-10c025300b74.png)

**Comment by chenshuai2144** [comment]
可以用 ref 来打开的

**Comment by zhaobosky** [comment]
> 可以用 ref 来设置

ref没有对应方法，input组件可以通过ref.input. selectionStart 但是input.textarea没有啊，我的两个截图就是input和input.textarea

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/blob/73a07d075e47fc9c7165d0d7780eaafb855ab261/components/input/TextArea.tsx#L91

看这里是有重定向的，如果有问题可以去 antd 提一个，ref 出问题影响还是很大的

**Comment by Amethyst-Ruby** [comment]
我是这样拿到原生节点的

``` javascript
 <Input.TextArea ref={(input) => {this.contentProp[index] = input}}   />  // 元素

 const { _reactInternalFiber } = this.contentProp[index]
 const { selectionStart } = _reactInternalFiber.firstEffect.stateNode   // 光标开始位置
```
