### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by willdreame** [ant-design/ant-design-pro#7674]
### 🐛 bug 描述
版本  antd pro v4

左侧菜单栏 左下角的缩进图标 点击缩进 并不会进行缩进操作， 包括 antd pro 官网 也存在同样的 bug 

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/40716306/100300020-12cc1600-2fd0-11eb-8beb-d6055a53c2bc.png)
#

### 🏞 期望结果

我期望可以解决 

还有我将  SettingDrawer  组件去掉了， 会有影响嘛

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TnWah** [comment]
+1

**Comment by yangzhenwang** [comment]
+1 遇到了同样的问题 开发环境没问题 打包后运行导航栏点击不会收起

**Comment by willdreame** [comment]
请问这个这个有解决嘛 请给一个答复 谢谢

**Comment by chenshuai2144** [comment]
升级一下antd，是antd 引入的bug
