### ISSUE TITLE
useEffect给空依赖仍然会触发2次

### ISSUE THREAD

**Issue by 123456wjw** [ant-design/ant-design-pro#7675]
![image](https://user-images.githubusercontent.com/37201576/100300997-2aa49980-2fd2-11eb-8698-07a8660aecb7.png)
在登录页使用此方法跳转后，退出登录后会导致useEffect执行2次
![image](https://user-images.githubusercontent.com/37201576/100301086-5e7fbf00-2fd2-11eb-837a-6e1e438ed7b5.png)

**Comment by chenshuai2144** [comment]
因为触发页面刷新了

**Comment by leshalv** [comment]
@chenshuai2144 如果我只想加载一次，应该怎么做呢？

**Comment by fandepeng1993** [comment]
求交问我也遇到这个问题了 如何解决

**Comment by chenshuai2144** [comment]
用 location.href="xxx" 来跳转页面
