### ISSUE TITLE
🐛[BUG] 导航栏的defaultCollapsed默认展开收起设置无效，导航栏点击不会收起

### ISSUE THREAD

**Issue by iambool** [ant-design/ant-design-pro#7676]
### 🐛 bug 描述
创建了4.3.0版的ant design pro工程，试用时，出现以下问题：
（1）点击左侧导航栏的收起按钮，没有作用；
![image](https://user-images.githubusercontent.com/30134533/100306057-714bc100-2fdd-11eb-8b5e-2a07d5952281.png)

（2）阅读官方文档后，设置defaultCollapsed={true}，但是导航栏还是展开状态；设置collapsed={true}，同样无效；

### © 版本信息

- Ant Design Pro 版本：4.3.0
- umi 版本：^3.2.14
- 浏览器环境：chrome
- 开发环境：windows

**Comment by lspeer** [comment]
#7652

**Comment by yangzhenwang** [comment]
遇到了同样的问题 开发环境没问题 打包后运行导航栏点击不会收起

**Comment by chenshuai2144** [comment]
不要大量的刷重复的issue
