### ISSUE TITLE
🧐[问题] V5怎么添加stylus支持

### ISSUE THREAD

**Issue by leitingx762** [ant-design/ant-design-pro#7677]
### 🧐 问题描述

我想使用stylus,参照文档在/confgi/config.ts添加
`stylus:{} `
报错 invalid key;
于是改为添加
` 
 chainWebpack: config => {
    config.module
      .rule('stylus')
      .test('/.styl(us)?$')
      .use('stylus')
      .loader('stylus-loader')
  }
`

但还是解析不了
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5674953/100315338-71ef5200-2ff3-11eb-8da7-62268e6ba8c2.png)

**Comment by chenshuai2144** [comment]
学习一下 webpack 的基础吧，你的 test 都写错了。
这一整套都要写进去
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.styl$/,
        use: [
          {
            loader: "style-loader", // creates style nodes from JS strings
          },
          {
            loader: "css-loader", // translates CSS into CommonJS
          },
          {
            loader: "stylus-loader", // compiles Stylus to CSS
          },
        ],
      },
    ],
  },
};
```

**Comment by leitingx762** [comment]
多谢大佬...test是写错了,不过umi没有提供写webpack.config.js的地方,大佬这个配置我要写在哪里?
目前还是用的chainWebpack解决
`
  chainWebpack: config => {
    config.module
      .rule('stylus')
      .test(/\.styl(us)?$/)
      .use('styleloader')
      .loader('style-loader')
      .end()
      .use('cssloader')
      .loader('css-loader')
      .options({ modules: true })
      .end()
      .use('stylusloader')
      .loader('stylus-loader')
  }
`
