### ISSUE TITLE
🐛[BUG] proV5 关闭国际化运行报错

### ISSUE THREAD

**Issue by Cooolyu** [ant-design/ant-design-pro#7678]
### 🐛 bug 描述
修改配置文件如下
![image](https://user-images.githubusercontent.com/16718459/100326617-22b21d00-3005-11eb-8e8b-d6bcf9226d19.png)

### 🚑 其他信息
前端白屏，控制台报错如下
![image](https://user-images.githubusercontent.com/16718459/100326863-7b81b580-3005-11eb-9eed-259d86fd5d75.png)

**Comment by chenshuai2144** [comment]
统一在这里跟踪吧 

https://github.com/ant-design/ant-design-pro/issues/7546
