### ISSUE TITLE
🧐[问题]想下载全部区块文件，整个压缩包下载的方式有吗？

### ISSUE THREAD

**Issue by afr751116** [ant-design/ant-design-pro#7679]
如题，我知可以通过下载源码后，再下载全部区块。
但是有时不方便这样操作，请问哪里有全部区块的下载，因似于全部一个包下载的那种方式，下载打开就可用的，不用再去分步下载。谢谢

**Comment by chenshuai2144** [comment]
yarn create umi 选全量下载。

https://beta-pro.ant.design/docs/getting-started-cn#%E5%88%9D%E5%A7%8B%E5%8C%96

**Comment by my9988** [comment]
@chenshuai2144 关于下载区块的问题，我看到很多人在问这个问题，你也给了回复，但是我有很多疑惑，比如你上面回复的URL，在V5下没有选择全部的选项，还有你说的yarn run fetch-blocks --branch=v5,前几天试过可以，现在不行了，不知道为什么？

**Comment by HaitaoWang555** [comment]
下载全部 直接下 [all-block 分支](https://github.com/ant-design/ant-design-pro/tree/all-blocks) 目前看还是 V4的 V5 的还没出来吧
