### ISSUE TITLE
边栏菜单的collapsed功能没用

### ISSUE THREAD

**Issue by jacksuc** [ant-design/ant-design-pro#7682]
### 🐛 bug 描述

边栏菜单最下方的折叠收缩功能失效

### 📷 复现步骤

一直存在

### 🏞 期望结果

修复

### © 版本信息

- Ant Design Pro 版本: V4
- 浏览器环境 chrome
- 官方演示站

**Comment by willdreame** [comment]
+2

**Comment by vVvlife** [comment]
+3，不过是在升级antdesign 4.8.5后出现

**Comment by vVvlife** [comment]
Ant Design Pro 版本: V5 也有这种问题

**Comment by my9988** [comment]
+4

**Comment by vVvlife** [comment]
大家去升级刚推的antdesign 4.8.6版本吧，已经修复了

**Comment by quarkcms** [comment]
+5

**Comment by willdreame** [comment]
> 大家去升级刚推的antdesign 4.8.6版本吧，已经修复了

问下 是升级 antd  还是  antdpro 呢 ？

**Comment by vVvlife** [comment]
> > 大家去升级刚推的antdesign 4.8.6版本吧，已经修复了
> 
> 问下 是升级 antd 还是 antdpro 呢 ？

升antd

**Comment by chenshuai2144** [comment]
升级 antd 就好了，已经发布了

antd@4.8.6
