### ISSUE TITLE
proxy配置文件是否可以配置正则？

### ISSUE THREAD

**Issue by mrhsiang** [ant-design/ant-design-pro#7683]
config/proxy.js文件
因为后台微服务的原因，所有接口api前面都有编码
export default {
  dev: {
    '/99030901': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    },
    '/99010102': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    },
    '/99020203': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    },
    '/99020202': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    },
    '/99020201': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    },
    '/99050101': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    },
  },
  test: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
  pre: {
    '/api/': {
      target: 'your pre url',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
};

因此为了方便，想使用正则来匹配编码开头的接口如
export default {
  dev: {
    '~*/[1-9]\d*': {
      target: 'http://192.168.5.171:7101',
      changeOrigin: true,
    }
  },
  test: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
  pre: {
    '/api/': {
      target: 'your pre url',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
};

注：该正则表达式在nginx.config文件以及在线正则验证是有效的，但是在项目中就没有效果？

**Comment by chenshuai2144** [comment]
可以，但是与 nginx 规则不同，nginx 是 c，proxy 是 js 的正则。

https://webpack.js.org/configuration/dev-server/ 这里有比较深入的解释
