### ISSUE TITLE
🧐[问题]layout 的入参是怎么理解的

### ISSUE THREAD

**Issue by wenbolwm** [ant-design/ant-design-pro#7684]
### 🧐 问题描述
正常是这样的：
export const layout = (initialState: Any): BasicLayoutProps => {
或
interface xxx{
}
export const layout = (initialState: xxx): BasicLayoutProps => {
请问下这里入参是怎么理解的?
export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps => {

### 💻 示例代码
import React from 'react';
import {
  BasicLayoutProps,
  Settings as LayoutSettings,
} from '@ant-design/pro-layout';

export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps => {
  return {
    rightContentRender: () => <RightContent />,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { currentUser } = initialState;
      const { location } = history;
      // 如果没有登录，重定向到 login
      if (!currentUser && location.pathname !== '/user/login') {
        history.push('/user/login');
      }
    },
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};

**Comment by chenshuai2144** [comment]
initialState 可以理解成一个全局的 state，这个 state 改变会触发 layout 的重新 render。
```
  const { initialState, setInitialState } = useModel('@@initialState');
```
