### ISSUE TITLE
🧐关于V5 Login Logout问题

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7685]
### 🧐 initialState运行原理？

系统Login 后，再logout,然后再次Login的时候，initialState怎么不再次运行fetchUserInfo这个呢？

不运行这个怎么获取人员信息及判断权限？

### 💻 export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps & {
  childrenRender?: (dom: JSX.Element) => React.ReactNode;
} => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { currentUser } = initialState;
      const { location } = history;
      const isLogin = currentUser && currentUser.userid;
      if (!isLogin && location.pathname !== '/user/login') {
        history.push('/user/login');
      }
    },
    menuHeaderRender: undefined,
    ...initialState?.settings,

**Comment by wenbolwm** [comment]
export const layout = ({
initialState,
}: {
initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps 你知道这里面的入参是怎么理解的么？

**Comment by my9988** [comment]
谢谢回复，我也是刚使用V5，不太熟悉流程，我用clone的代码也是一样的，我和我的后台系统联动，第二次登陆时也看不到/api/currentUser这个请求，不知道问题出在哪里？谢谢帮忙

**Comment by my9988** [comment]
> export const layout = ({
> initialState,
> }: {
> initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
> }): BasicLayoutProps 你知道这里面的入参是怎么理解的么？

谢谢回复，我也是刚使用V5，不太熟悉流程，我用clone的代码也是一样的，我和我的后台系统联动，第二次登陆时也看不到/api/currentUser这个请求，不知道问题出在哪里？谢谢帮忙

**Comment by z-lionel** [comment]
主要看你再次登录用的什么方法？
你用histroy.push()到主页的话，页面没有刷新，不会触发initialState里面的方法，
这个方法默认运行只加载一次，
你用原来demo里面的window.location.href 的方法登录到页面内，会刷新页面，就会触发了

**Comment by my9988** [comment]
> 主要看你再次登录用的什么方法？
> 你用histroy.push()到主页的话，页面没有刷新，不会触发initialState里面的方法，
> 这个方法默认运行只加载一次，
> 你用原来demo里面的window.location.href 的方法登录到页面内，会刷新页面，就会触发了

我没有修改V5的登录方法，就是用的historyr.push(),我根据您说的，既然这是正常现象就行了，我以为是我理解的问题，非常感谢热心解答。

**Comment by my9988** [comment]
经过我反复测试，
![image](https://user-images.githubusercontent.com/17469220/100447065-ea2e4400-30d5-11eb-8ee1-38f900a6ecaa.png)
原代码!currentUser总是false,感觉这里有问题，我改了下不知道是否正确
