### ISSUE TITLE
🐛[BUG] antd pro v5保存文件后偶发无限编译

### ISSUE THREAD

**Issue by wehuss** [ant-design/ant-design-pro#7686]
### 🐛 bug 描述

antd pro v5保存文件后偶发无限编译

### 📷 复现步骤

Ctrl+S保存文件后无限编译
![antdPro](https://user-images.githubusercontent.com/48681136/100425759-c1548180-30ca-11eb-9286-0d538203a4cc.gif)

### 🏞 期望结果

正常编译更新

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本:5.0.0-beta.0
- umi 版本：3.2.28
- 浏览器环境：Chrome  87.0.4280.66（正式版本）
- 开发环境  windows10企业版 2004
-开发工具：VS Code 1.51.1

### 🚑 其他信息

希望各位大佬能够解答

**Comment by chenshuai2144** [comment]
可能是大小写的问题，因为大小写不敏感会导致它认为两个文件在更新

**Comment by wehuss** [comment]
好像和我电脑系统时间不准确有关
