### ISSUE TITLE
import { Donut } from '@ant-design/charts';]

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7687]
### 🧐 
![image](https://user-images.githubusercontent.com/17469220/100474589-fe3e6980-3106-11eb-9e46-2f58dfbf748c.png)
这个Donut在哪里呢，找不到呢？

**Comment by lxfu1** [comment]
https://charts.ant.design/demos/pie#%E7%8E%AF%E5%9B%BE%E7%BB%9F%E8%AE%A1%E6%8C%87%E6%A0%87%E5%8D%A1

**Comment by jikefan** [comment]
请问如何解决的呢
