### ISSUE TITLE
🐛[BUG] Firebase firestore 不支持

### ISSUE THREAD

**Issue by Dragon201701** [ant-design/ant-design-pro#7688]
### 🐛 bug 描述

引入Firebase firestore报错。 Ant Design Pro 目前不支持firebase-admin。根据官方文档，firebase-admin不支持前端。
Cannot read property 'DEADLINE_EXCEEDED' of undefined while processing firestore query

### 📷 复现步骤

npm install firebase-admin --save
const admin = require('firebase-admin');

### 🏞 期望结果

我想用firestore数据库！！！

### 💻 复现代码

我在config目录下新建了一个firebase.js
`` `Javascript
import firebase from 'firebase'
let firebaseConfig = {...}
let serviceAccount = {...} //这两处为项目配置文件，包括apikey, authDomain, project_id, private_key_id这些信息
firebasel.initializeApp(firebaseConfig)
const firebaseadmin = require('firebase-admin');
firebaseadmin.initializeApp({
    credential: firebaseadmin.credential.cert(serviceAccount)
});
let db = firebaseadmin.firestore();
expoprt default firebaseConfig
`` `

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by Dragon201701** [comment]
哦没事解决了。。。
把这个转成Note
敲黑板
请不要安装firebase-admin!
请不要安装firebase-admin!!
请不要安装firebase-admin!!!
重要的事情说三遍。
直接使用`var db = firebase.firestore();`
即可

**Comment by danleighton** [comment]
I am not sure I understand the issue and the resolution. Do you mean do not install Firebase Admin in the Dev environment at all as it corrupts the system, umi, etc. Or do you mean just do not use Firebase Admin to access the Firestore SDK, etc. instead, just access firestore directly using the solution proposed by @Dragon201701 ?

And thank you team! Great work on Ant Design Pro. It is amazing and we are telling more people in Europe and India about it. Thank you for all your hard work :-)

**Comment by Dragon201701** [comment]
Just don't use firebase admin lol. Firstore SDK works well.

**Comment by danleighton** [comment]
> Just don't use firebase admin lol. Firstore SDK works well.

Haha ;-) I take your point. Will experiment.

**Comment by Dragon201701** [comment]
Update: 请暂时使用SDK8
