### ISSUE TITLE
V5 请教怎么配置去掉导航条？

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7689]
showBreadcrumb:false,

我想通过配置去掉配置，也查了很多说明试过无效，请问应该怎么办？

![image](https://user-images.githubusercontent.com/17469220/100520439-b3365c00-31c3-11eb-94df-fd749ca7cc8c.png)

**Comment by chenshuai2144** [comment]
导航条 是什么。你是指面包屑吗？
面包屑可以通过` breadcrumbRender={()=>[]}` 关闭，不过不支持在 layout 中配置，

**Comment by my9988** [comment]
@chenshuai2144 对，就是 如图中的可能叫面包屑，我是刚从jquery开发转过来，基本靠模仿你们的代码，尽管你给了提示还是没明白你说的那句话写在哪里？还麻烦再细一点。

**Comment by chenshuai2144** [comment]
在` src\app.tsx `中这样写
```
export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps & {
  childrenRender?: (dom: JSX.Element) => React.ReactNode;
} => {
  return {
    breadcrumbRender: () => [],
    menuHeaderRender: undefined,
    ...initialState?.settings,
  };
};

```
