### ISSUE TITLE
🐛[BUG]  modal 使用modalRender 渲染自定义窗体时候，窗体内的按钮无法点击（窗体无法浮在最上层）

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#7690]
modal组件 使用modalRender 渲染自定义窗体时候，窗体内的按钮无法点击（窗体无法浮在最上层）
使用谷歌谷歌浏览器调试的时候，无法选中窗体，  默认的组件是可以选中的

**Comment by lovesL** [comment]
你这个问个和antd  pro有什么关系  来错地方了应该去antd  那里提问

**Comment by chenshuai2144** [comment]
看来没人碰到同样的问题，去 antd 问问吧
