### ISSUE TITLE
🐛[BUG]v5登录页样式有问题，需要把margin给去了

### ISSUE THREAD

**Issue by yehuozhili** [ant-design/ant-design-pro#7692]
### 🐛 bug 描述

登录页右上方切换语言脱离界面，且产生滚动条

### 📷 复现步骤

打开v5，进入登录页即可看见

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.0
- umi 版本 3.2.14
- 浏览器环境 谷歌86.0.4240.183
- 开发环境 windows

发现container的margin写了个-24px，去了就行了

**Comment by chenshuai2144** [comment]
来个 pr 吧

**Comment by yehuozhili** [comment]
你这个刚改过了  那我就不改了

**Comment by chenshuai2144** [comment]
@yehuozhili  非常感谢
