### ISSUE TITLE
🧐[问题] 使用browserHistory nginx配置  无法正常访问页面

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#7693]
前端希望通过路由加上 /ui/demo 的前缀， 页面部署在web/demo，请问该如何配置下面的参数，才能正常使用?
下面的base, publicPath尝试了各种组合都无法正常使用
`
  hash: true,
  base: '/ui/demo/',
  publicPath: '/',
`

nginx 配置
`
location ^~ /ui/demo {
		# 用于配合 browserHistory使用
        try_files $uri $uri/ /index.html;
		alias /opt/web/demo/;
 }
`

**Comment by chenshuai2144** [comment]
base 和 publicPath 都用 /ui/demo/，然后 nginx 的配置不需要不需要前缀，可以在 network 中看到具体的请求。

一般这种问题都是对 nginx 不熟悉导致的
