### ISSUE TITLE
🧐[问题]defaultSettings.ts中的logo字段的值怎么使用本地资源，以及如何给这个图标添加一个点击事件？？？

### ISSUE THREAD

**Issue by sunzhengbo** [ant-design/ant-design-pro#7694]
### 🧐 问题描述

logo怎么使用本地资源，以及如何给这个logo添加一个点击事件？？？

### 💻 示例代码
export default {
  navTheme: 'dark',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  menu: {
    locale: true,
  },
  title: false,
  pwa: false,
  logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  iconfontUrl: '',
  siderWidth: 208,
} as LayoutSettings & {
  pwa: boolean;
};

**Comment by chenshuai2144** [comment]
在 app.tsx 里配置 layout ，typescript 有提示的。

**Comment by sunzhengbo** [comment]
问题是怎么配置啊，我感觉你们这个为了关闭问题而来的，不是为了解决问题的。




sunzhengbo
sunzhengbo@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 中午1:01
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"sunzhengbo"<sunzhengbo@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题]defaultSettings.ts中的logo字段的值怎么使用本地资源，以及如何给这个图标添加一个点击事件？？？ (#7694)





 
在 app.tsx 里配置 layout ，typescript 有提示的。

**Comment by chenshuai2144** [comment]
typescript 有提示的。 就像写 jsx 一样，jsx 总是会写的吧，而且相同的 issue 很多了。

**Comment by sunzhengbo** [comment]
已解决，解决方案如下：在app.tsx的getInitialState()中添加如下代码，
`
import logo from '@/assets/logo.png';

  // set logo
  defaultSettings.logo = () => React.createElement('img', {
    // update local resources
    src: logo,
    alt: 'logo',
    onClick: () => {
      // TODO
    },
    // set size of the image
    style: { height: 40, width: 120 }
  });
`

**Comment by chenshuai2144** [comment]
@sunzhengbo  你的太黑科技了，我把你折叠了。

```
import logo from "@/assets/logo.png";

export const layout = ({
  initialState,
}: {
  initialState: { settings?: LayoutSettings; currentUser?: API.CurrentUser };
}): BasicLayoutProps & {
  childrenRender?: (dom: JSX.Element) => React.ReactNode;
} => {
  return {
    ...initialState?.settings,
    // 要写在initialState?.settings,之后，不然会被覆盖
    logo: <img src={logo} />,
  };
};

```

**Comment by sunzhengbo** [comment]
这样的方式确实更好点，我的写的那个确实有被覆盖的可能，但是这个...initialState?.settings就是从getInitialState()来到，只要没有在你这个return里面加上logo就不会被覆盖。最后问题解决，感觉帮忙。
