### ISSUE TITLE
🐛[BUG]DatePicker的format不生效

### ISSUE THREAD

**Issue by Mustard404** [ant-design/ant-design-pro#7695]
### 🐛 bug 描述

DatePicker的format不生效，无法格式化时间格式。

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/14071947/100588197-881b4c00-332c-11eb-9de7-dc7a3b852830.png)
![image](https://user-images.githubusercontent.com/14071947/100588415-c3b61600-332c-11eb-9831-da6734cf128d.png)

**Comment by chenshuai2144** [comment]
DatePicker 的  format  是只读的，存到服务器的时候需要你自己处理。

你可以使用proForm 会帮你自动处理
