### ISSUE TITLE
🧐[问题] 退出后login页面刷新两次问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#7696]
很不理解为什么会执行两次useEffect()？有没有方案只执行一次，因为我里面要做一些逻辑处理。

**Comment by chenshuai2144** [comment]
看看这里，不要使用 location.href 的跳转就不会出问题

https://github.com/ant-design/ant-design-pro/commit/99312f5cc1da41ca794c2f6257d8c522d53e6d12#diff-9da5070134fcd6f9407d2b5431f6355b1647b3f559b67a66a78ffd57d859d8cf

**Comment by leshalv** [comment]
我是用的是当前仓库最新版本V5，没有使用location.href

**Comment by chenshuai2144** [comment]
那不会的 你的effect在哪写的？

**Comment by pingfangushi** [comment]
> 那不会的 你的effect在哪写的？

在login页面写的。确实是执行了两次。

**Comment by leshalv** [comment]
> 那不会的 你的effect在哪写的？

在login页面写的。确实是执行了两次。

**Comment by chenshuai2144** [comment]
来个仓库吧，让我试试为什么

**Comment by chenshuai2144** [comment]
无法重现先关掉吧

**Comment by fandepeng1993** [comment]
我现在的项目也出现了两次呢
