### ISSUE TITLE
🧐[问题]急急急，求助，本地设置反向代理proxy，一直连不到服务器

### ISSUE THREAD

**Issue by u0028917** [ant-design/ant-design-pro#7697]
### 🧐 设置了反向代理proxy 服务器地址，但是请求不到
![image](https://user-images.githubusercontent.com/23309025/100593408-56f24a00-3333-11eb-8b4b-6dc9f2cb2930.png)
一直是html类型，后台数据返回结果是html。

**Comment by u0028917** [comment]
如何上传图片呢

**Comment by xiaohuoni** [comment]
是什么问题？需要修改 `Content-Type` 还是要修改 proxy？

**Comment by u0028917** [comment]
> 是什么问题？需要修改`Content-Type`还是要修改代理？

就是我设置了proxy 的后台代理，请求的时候返回的数据是html 类型，
![image](https://user-images.githubusercontent.com/23309025/100594327-7d64b500-3334-11eb-8c2a-178c26d2bb84.png)
我除了设置proxy，还需要额外配置什么东西吗，为什么请求不到后台，返回的是html

**Comment by u0028917** [comment]
本地启动的时候 npm run start:dev
默认是关闭 mock 数据了，为什么还是请求不到后台接口，接口返回是200，但是返回数据是 html，接口在postman 是好的，是我哪里配置没有改吗？

**Comment by chenshuai2144** [comment]
这个是因为404导致的，你proxy 的正则不对把

**Comment by u0028917** [comment]
> 这个是因为404导致的，你proxy 的正则不对把

![image](https://user-images.githubusercontent.com/23309025/100597889-f108c100-3338-11eb-8679-7d15ba7134d3.png)
proxy 设置，应该没问题吧

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/100598032-28776d80-3339-11eb-8367-2decbebc94b0.png)

你应该设置这个把，怎么是/api/

**Comment by u0028917** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/100598032-28776d80-3339-11eb-8367-2decbebc94b0.png)
> 
> 你应该设置这个把，怎么是/api/

把那里忽略了，已经解决了，感谢

**Comment by u0028917** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/100598032-28776d80-3339-11eb-8367-2decbebc94b0.png)
> 
> 你应该设置这个把，怎么是/api/

把那里忽略了，已经解决了，感谢
