### ISSUE TITLE
🧐[问题] 如何快速的将前端演示环境部署到服务器上，包含演示用到的mock数据。

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#7699]
### 🧐 问题描述

如何快速的将前端演示环境部署到服务器上，包含演示用到的mock数据。

文档上说build后，就没有mock数据了。

**Comment by chenshuai2144** [comment]
emmm，mock 估计没办法，你可以试试 `@umijs/serve` 这个包，但是没有文档，你需要去umi里面去看看到底怎么用

**Comment by Leskur** [comment]
😁如果只是为了演示一下，何不在服务器上运行 serve？

**Comment by fanhualei** [comment]
> 😁如果只是为了演示一下，何不在服务器上运行 serve？

都有哪些serve可以用呀？ 就是把mock文件传递到服务器上

**Comment by Leskur** [comment]
> > 😁如果只是为了演示一下，何不在服务器上运行 serve？
> 
> 都有哪些serve可以用呀？ 就是把mock文件传递到服务器上

我的意思是，何不在服务器上运行 `npm run serve`。

觉得这样不优雅的话，那么建议自己使用 mockjs 替换掉 [src/service](https://github.com/ant-design/ant-design-pro/blob/9aea28298e051a953604e4e14742481d9eda6be8/src/services/) 中的行为。

或者使用 [rap2.taobao.org]( http://rap2.taobao.org/) 来实现你的 mock api。

**Comment by fanhualei** [comment]
明白了
