### ISSUE TITLE
输入框的搜索按钮无效

### ISSUE THREAD

**Issue by basicfu** [ant-design/ant-design-pro#77]
在这个脚手架中，我加入以下代码，搜索输入框回车输入可以触发事件，但是点击搜索按钮图标无效并没有触发事件，搜索图标也没有point指向样式

```
import { Input } from 'antd';
const Search = Input.Search;
<Search
     placeholder="input search text"
     style={{ width: 200 }}
     onSearch={value => console.log(value)}
/>
```

**Comment by afc163** [comment]
对，这个图标只有装饰作用。

**Comment by basicfu** [comment]
ant-design里2.13.8中有这个图标可以点也有效，是因为这个脚手架用的ant3.0beta版吗？

**Comment by afc163** [comment]
是的，行为有变化。可以暂时查看 http://beta.ant.design/components/input/#components-input-demo-search-input

**Comment by basicfu** [comment]
好的，非常感谢，我可以先用带图标的button
