### ISSUE TITLE
🧐[问题]使用protable后，翻页后每一页的数据量不对

### ISSUE THREAD

**Issue by guoxuncn** [ant-design/ant-design-pro#7700]
### 🧐 使用protable后，翻页后每一页的数据量不对

比如设置一个显示10条数据，刚进入页面的时候是正常的，翻页后就会显示15条，再回到第一个就会显示全部数据，感觉有某个缓存之类的没有清除掉一样。
哪怕在onchange后，重新获取数据改 ret.data 的数量为10条，他仍然会显示15条数据

### 💻 示例代码

      <ProTable<TableListConsulItem>
        headerTitle="配置，项目/环境 -> 值"
        actionRef={actionRef}
        rowKey="proj"
        search={{
          labelWidth: 120,
        }}
        toolBarRender={() => [
          <Button type="primary" onClick={() => 
			  { handleUpdateModalVisible(true);
			    setStepFormValues({this});
			  }}>
            <PlusOutlined /> 新建
          </Button>,
        ]}
        request={
			(params ) => queryRule({ ...params }).then(res =>{
				
                var ret = {}
                ret.total = res.length
                ret.success = true
               	ret.data = res	
				ret.pageSize = params.pageSize
		
				for (var i = 0; i < res.length; i++)
				{
					ret.data[i].key = ret.data[i].ModifyIndex
					ret.data[i].proj = ret.data[i].Key.split('/')[0]
					ret.data[i].env = ret.data[i].Key.split('/')[1]
					var _value = ret.data[i].Value
					try
					{
						ret.data[i].value = _Base64.decode(_value)
					}
					catch(err)
					{
						ret.data[i].value = _value
					}
				}
								
			    return ret
			})//then
			}//request
		onChange ={(page,pageSize) => 
			  { 

			  }}
        columns={columns}
      />

**Comment by chenshuai2144** [comment]
onChange  里面是不能修改的。而且你这个写的很奇怪，你不能修改引用的，不然可能被浅拷贝。你最好这样,
另外 total 应该是服务器告诉你的总共需要多少条，如果你没有服务器分页，最好不要设置

```
const request = async (params) => {
  const res = await queryRule({ ...params });
  const data = res.map((item) => {
    const value = _Base64.decode(ret.data[i].Value);
    return {
      ...item,
      key: item.ModifyIndex,
      proj: item.Key.split("/")[0],
      env: item.Key.split("/")[1],
      value,
    };
  });

  return {
    data,
    success: true,
    pageSize: params.pageSize,
  };
};

```

**Comment by guoxuncn** [comment]
> 
> 
> onChange 里面是不能修改的。而且你这个写的很奇怪，你不能修改引用的，不然可能被浅拷贝。你最好这样,
> 另外 total 应该是服务器告诉你的总共需要多少条，如果你没有服务器分页，最好不要设置
> 
> ```
> const request = async (params) => {
>   const res = await queryRule({ ...params });
>   const data = res.map((item) => {
>     const value = _Base64.decode(ret.data[i].Value);
>     return {
>       ...item,
>       key: item.ModifyIndex,
>       proj: item.Key.split("/")[0],
>       env: item.Key.split("/")[1],
>       value,
>     };
>   });
> 
>   return {
>     data,
>     success: true,
>     pageSize: params.pageSize,
>   };
> };
> ```

照您这改了一下，页码数量还是不对。
`<ProTable<TableListConsulItem>
        headerTitle="配置，项目/环境 -> 值"
        actionRef={actionRef}
        rowKey="proj"
        search={{
          labelWidth: 120,
        }}
        toolBarRender={() => [
          <Button type="primary" onClick={() => 
			  { handleUpdateModalVisible(true);
			    setStepFormValues({this});
			  }}>
            <PlusOutlined /> 新建
          </Button>,
        ]}
		

		const request = {async (params) => {
			const res = await queryRule({ ...params });
			const data = res.map((item) => {
			const value = _Base64.decode(item.Value);
			return {
				...item,
				key: item.ModifyIndex,
				proj: item.Key.split("/")[0],
				env: item.Key.split("/")[1],
				value,
				};
			});

			return {
				data,
				success: true,
				pageSize: params.pageSize,
				};
			}
		}
        columns={columns}
      />`

补充一个就是，就算我返回了10个数字，只要我之前有别的返回，他翻页后就可能会把之前的数据加进去，导致数据总数不对。

**Comment by chenshuai2144** [comment]
pageSize 也不要返回

**Comment by guoxuncn** [comment]
> 
> 
> pageSize 也不要返回，试试postData 看看，是最终的数据

		postData = {(data) =>{
			console.log(data)
			return data.slice( (_current - 1) * _pagesize,_current * _pagesize)
		}}

加了一个这样的，还是不行，我感觉核心就是在于之前刷到页面里的数据，再次翻页他不会刷新掉，导致了数据越来越多

**Comment by guoxuncn** [comment]
我找到原因了  rowkey 设置错误，F12一下还是挺明显的

**Comment by chenshuai2144** [comment]
来个可重现的例子吧，这个问题还是第一次。

**Comment by maoyaru123** [comment]
@chenshuai2144 hi，我也遇到这个问题了，现在解决了。原因我推测是：后端返回的list中每一项都有id，于是我把rowkey设置为id，但页面上不显示id，也就是说column里面没有dataIndex为id的这一项，之后翻页的时候就出现了上述问题，最后我把rowkey设置为column中有的一项，就好了

**Comment by maoyaru123** [comment]
@chenshuai2144 终极结论是与column中有没有这一项无关，是因为id太长丢失精度了，因此出现了重复的id￣□￣｜｜

**Comment by starlitya** [comment]
> @chenshuai2144 hi，我也遇到这个问题了，现在解决了。原因我推测是：后端返回的list中每一项都有id，于是我把rowkey设置为id，但页面上不显示id，也就是说column里面没有dataIndex为id的这一项，之后翻页的时候就出现了上述问题，最后我把rowkey设置为column中有的一项，就好了

遇到類似的問題，也是rowKey導致. 感謝樓主
