### ISSUE TITLE
🧐[问题]V5 在routers.ts配置的路由，如何重定向到子路由

### ISSUE THREAD

**Issue by LyndonXiao** [ant-design/ant-design-pro#7701]
### 🧐 问题描述

父菜单希望能重定向进入其子菜单路由，在父菜单中配置redirect后，路由虽然变为子菜单路由，但是子路由的component并未渲染，移除父菜单的redirect直接进入子菜单路由是能正常渲染子菜单component的，不知道是bug还是没有正确配置？

### 💻 示例代码

```
...
{
    path: '/order',
    name: 'order',
    icon: 'crown',
    // redirect: '/order/list',
    routes: [
      {
        path: '/order/list',
        name: 'list',
        icon: 'smile',
        component: './order/list',
      },
    ],
  },
...
```

### 🚑 其他信息
使用redirect情况
![image](https://user-images.githubusercontent.com/15028509/100708989-44861800-33e8-11eb-8805-9af725ab0f1e.png)

不使用redirect情况
![image](https://user-images.githubusercontent.com/15028509/100709487-2ec52280-33e9-11eb-9aca-8fed43924528.png)

**Comment by chenshuai2144** [comment]
这样用好了。
```json
[
  {
    path: "/order",
    name: "order",
    icon: "crown",
    routes: [
      { path: "/", redirect: "/order/list" },
      {
        path: "/order/list",
        name: "list",
        icon: "smile",
        component: "./order/list",
      },
    ],
  },
];
```

**Comment by LyndonXiao** [comment]
![image](https://user-images.githubusercontent.com/15028509/100843366-36ea9400-34b5-11eb-9900-6a1927458603.png)

按照此方法调整后
![image](https://user-images.githubusercontent.com/15028509/100843159-e5daa000-34b4-11eb-84dd-3bf37d7996ad.png)

![image](https://user-images.githubusercontent.com/15028509/100843254-0efb3080-34b5-11eb-84d1-841cd719afe6.png)
在父路由上不会跳转子路由，子路由上能正常渲染component

**Comment by LyndonXiao** [comment]
```
{
    path: '/order',
    name: 'order',
    icon: 'crown',
    routes: [
      { path: '/order', redirect: '/order/list' },
      {
        path: '/order/list',
        name: 'list',
        icon: 'smile',
        component: './order/list',
      },
    ],
  },
```
这样调整后可以了，感谢
