### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#7704]
### 🐛 bug 描述

安装完ant design pro之后，tyarn start报错
This relative module was not found:

* ../plugin-layout/layoutExports in ./src/.umi-production/core/umiExports.ts
Child

    ERROR in ./src/.umi-production/core/umiExports.ts
    Module not found: Error: Can't resolve '../plugin-layout/layoutExports' in 'E:\web\learn\src\.umi-production\core'
     @ ./src/.umi-production/core/umiExports.ts 8:0-47 8:0-47
     @ ./node_modules/umi/dist/index.esm.js
     @ ./src/global.tsx
     @ ./src/.umi-production/umi.ts
     @ multi ./src/.umi-production/umi.ts
null
build failed
Error: build failed
    at E:\web\learn\node_modules\@umijs\bundler-webpack\lib\index.js:138:27
    at finalCallback (E:\web\learn\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at E:\web\learn\node_modules\webpack\lib\MultiCompiler.js:277:6
    at done (E:\web\learn\node_modules\neo-async\async.js:2931:13)
    at runCompilers (E:\web\learn\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at E:\web\learn\node_modules\webpack\lib\MultiCompiler.js:188:7
    at E:\web\learn\node_modules\webpack\lib\MultiCompiler.js:270:7
    at finalCallback (E:\web\learn\node_modules\webpack\lib\Compiler.js:257:39)
    at E:\web\learn\node_modules\webpack\lib\Compiler.js:273:13
    at _next3 (eval at create (E:\web\learn\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at eval (eval at create (E:\web\learn\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:53:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

### 🏞 期望结果

正常运行
### 💻 复现代码
tyarn create umi
选择ant design pro v5
tyarn
tyarn start

### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本 3.2.14
- 浏览器环境
- 开发环境 windows 10

**Comment by askurat** [comment]
Same here. I updated `@umijs/preset-react` to 1.7.1 and the error started happening. I removed the package and re-added version 1.7.0 and it worked.

**Comment by DissoluteGao** [comment]
应该是今天才刚发的包引起的，早上我创建的工程并不会启动报错，下午创建的就开始启动不了了，现在只能每次启动报错后先注释src/.umi/core/umiExports.ts里export * from '../plugin-layout/layoutExports'能够正常启动，而且我早上创建的工程在umiExports.ts里没有plugin-layout的export

**Comment by chaosJS** [comment]
昨晚能正常跑的项目，今天早上来就报错了

**Comment by chaosJS** [comment]
![image](https://user-images.githubusercontent.com/17522683/100819140-8796c880-3486-11eb-9a98-1e2a621b94b6.png)

**Comment by ChenYCL** [comment]
同问题,自己的cli工具报错,昨天好的

**Comment by chenshuai2144** [comment]
看起来是我写的plugin有问题 我修一下

**Comment by ref45638** [comment]
@ideaviewes  他寫V5
我也是V5

**Comment by chaosJS** [comment]
> 看起来是我写的plugin有问题 我修一下 大家都是pro v4吗

我的是v5版本

**Comment by laozhu** [comment]
我是v5版本，一样的问题

**Comment by EvanHongYousan** [comment]
pro v5 出同款报错
