### ISSUE TITLE
🐛[BUG] 报错： `../plugin-layout/layoutExports`

### ISSUE THREAD

**Issue by haoyinag** [ant-design/ant-design-pro#7705]
### 🐛 bug 描述
报错信息
```json
This relative module was not found:

* ../plugin-layout/layoutExports in ./src/.umi/core/umiExports.ts
```
找到对应的文件，发现引入的是`layoutExports.d.ts`文件，而实际应该引入的是`Layout.tsx`？
改正后正常运行，但因为umi是运行时，只要有热更，对应的也会重新出现报错

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/24349947/100823528-55d62f80-348f-11eb-81aa-524894ddf8b7.png)

### 版本信息
```json
"@ant-design/pro-cli": "^2.0.2",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.0-beta.2",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "puppeteer-core": "^5.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3"
```

**Comment by vecold** [comment]
yeah
I have the same problem

**Comment by leshalv** [comment]
@sorrycc @chenshuai2144

**Comment by gs205642** [comment]
yeah
I have the same problem

**Comment by my9988** [comment]
+1

**Comment by chenshuai2144** [comment]
更新一下依赖，现在可以了。

**Comment by haoyinag** [comment]
@chenshuai2144  哪怕删除了node_modules，执行了`yarn upgrade --latest`，还是不行

**Comment by chenshuai2144** [comment]
https://www.npmjs.com/package/@umijs/plugin-layout

用这个版本

**Comment by haoyinag** [comment]
@chenshuai2144 报错

**Comment by haoyinag** [comment]
plugin @umijs/plugin-layout is already registered by E:/Code/antd-pro/node_modules/@umijs/plugin-layout/lib/index.js, plugin from E:/Code/antd-pro/node_modules/@umijs/plugin-layout/lib/index.js register failed.

**Comment by starhu521** [comment]
@chenshuai2144 还是不行，我用tyarn create umi 新建的v5项目，安装选的@umijs/preset-react选的是1.7.3

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/100863364-6c9c7680-34cf-11eb-9630-bd8350822595.png)


是不是用了tao淘宝源

**Comment by haoyinag** [comment]
@chenshuai2144 移除了淘宝镜像可以了，但是不明白为啥这个会带来影响

**Comment by chenshuai2144** [comment]
淘宝镜像同步速度有点慢。

核心问题是因为 umi 认为  plugin.d.ts 和  plugin.ts 不是一个文件

**Comment by haoyinag** [comment]
ok tks
