### ISSUE TITLE
如何对modal 里的tree 控件设置滚动条🧐[问题]

### ISSUE THREAD

**Issue by yugonglian** [ant-design/ant-design-pro#7707]
### 🧐 问题描述

        在对话框里 的 tree 控件设置 height 属性，滚动却失效了

### 🚑 其他信息

只能在 modal bodyStyle={{height: '200px', overflowY: 'scroll' }} ，问题是我只需要针对 tree 进行滚动

**Comment by chenshuai2144** [comment]
来个重现，没有重现我们发现不了问题的
