### ISSUE TITLE
👑 [需求]  需要一个导出功能，可以导出antd表格里面的数据

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7708]
### 🥰 需求描述
需要一个导出功能，可以导出antd表格里面的数据，并且数据是合并单元格；
现在遇到问题，合并单元格的数据配合antd表格没办法进行导出了；

**Comment by chenshuai2144** [comment]
可以用 `onDataSourceChange` 来拿到当前的 dataSource 数据

**Comment by Asence** [comment]
![image](https://user-images.githubusercontent.com/45235142/100953895-74e7c680-354e-11eb-9230-2b0894ffeffb.png)
这样的表格合并单元格以后的数据也可以拿吗？

**Comment by githubmann** [comment]
+1

**Comment by chenshuai2144** [comment]
这样得要自己拼接了，antd 不支持

**Comment by Asence** [comment]
大佬有什么好的插件推荐吗  我现在用的js-export-excel 这个现在也是不支持合并导出功能的

**Comment by chenshuai2144** [comment]
这个应该后端搞吧，前端拼接数据好麻烦的

**Comment by Asence** [comment]
后端说不会搞  说前端插件很多 直接用插件就行。  就丢给前端了。 现在也没办法了

**Comment by chenshuai2144** [comment]
想办法干掉合并单元格吧

**Comment by Asence** [comment]
有办法拿到合并后的数据吗 我重新组装成数组 然后进行导出 怎么样

**Comment by xiaohuoni** [comment]
自己写一个工具类，将 columns 传进去过滤，就好了。可以用 pro-table 设计的 columns ，在编写的时候会更简单一点
