### ISSUE TITLE
查询表格新建描述输入框getFieldDecorator和value一起使用

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design-pro#771]
![pic2](https://user-images.githubusercontent.com/16483610/35140085-e26375a0-fd30-11e7-9e3c-88141719005f.png)

使用 `Form.create` 的 `mapPropsToFields` 把父组件的属性映射到表单项上比较好

**Comment by infeng** [comment]
是的，提issue的时候没细看:satisfied:

**Comment by valleykid** [comment]
#762
