### ISSUE TITLE
👑 [急 · 支持标签栏导航]

### ISSUE THREAD

**Issue by liubin595338764** [ant-design/ant-design-pro#7710]
### 🥰 能否支持标签栏导航

![image](https://user-images.githubusercontent.com/5274428/100850039-30144f00-34be-11eb-876a-c74783a744db.png)

[https://panjiachen.github.io/vue-element-admin/](https://panjiachen.github.io/vue-element-admin/)

像vue-element-admin后台管理系统一样，支持标签栏导航，可以快速记住打开过的页面。不然如果左侧菜单栏比较复杂，每次切换页面需要去菜单找二级甚至三级导航，也是比较费事的交互。

### 🧐 解决方案

在 `basiclayout.jsx` 里面的 `ProLayout`新增可以控制是否显示标签栏导航的配置项。

标签栏导航可以显示在现在的面包屑的位置。

**Comment by liubin595338764** [comment]
或者 `breadcrumbRender` 可以支持传入一个组件，让开发者在面包屑的位置自己去实现标签栏导航的功能。

**Comment by chenshuai2144** [comment]
这个是在`layout`内部实现的，你可以用`childrenRender`自定义一下

**Comment by liubin595338764** [comment]
@chenshuai2144 你好，没太明白，`childrenRender`是在哪里设置的，可以给个例子吗

**Comment by chenshuai2144** [comment]
```
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { location } = history;
      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser && location.pathname !== '/user/login') {
        history.push('/user/login');
      }
    },
    menuHeaderRender: undefined,
    // 自定义 children
    // childrenRender: <div>unAccessible</div>,
    ...initialState?.settings,
  };
};
```

**Comment by liubin595338764** [comment]
@chenshuai2144 没找到这个代码的位置，我这边直接按照官网上的命令安装完的目录是这样子的
![image](https://user-images.githubusercontent.com/5274428/100955049-c7c27d80-3550-11eb-8eb7-3ca82c8f8437.png)

**Comment by liubin595338764** [comment]
以实现，谢谢

**Comment by jianatrm** [comment]
请问怎么实现的

**Comment by robin536180** [comment]
@liubin595338764 请问怎么实现的

**Comment by changlin0501** [comment]
> Reference in new issue
你好，请问是怎么实现的呢

**Comment by changlin0501** [comment]
> ```
> export const layout: RunTimeLayoutConfig = ({ initialState }) => {
>   return {
>     rightContentRender: () => <RightContent />,
>     disableContentMargin: false,
>     footerRender: () => <Footer />,
>     onPageChange: () => {
>       const { location } = history;
>       // 如果没有登录，重定向到 login
>       if (!initialState?.currentUser && location.pathname !== '/user/login') {
>         history.push('/user/login');
>       }
>     },
>     menuHeaderRender: undefined,
>     // 自定义 children
>     // childrenRender: <div>unAccessible</div>,
>     ...initialState?.settings,
>   };
> };
> ```

https://github.com/ant-design/ant-design-pro/issues/7710#issuecomment-737171586

你好，我加了 childrenRender 怎么没生效呢，请问是怎么回事，请帮忙看看
