### ISSUE TITLE
🐛[BUG] v2.20报”error evaluating function `darken`: color.toHSL is not a function“ 错误

### ISSUE THREAD

**Issue by niming175** [ant-design/ant-design-pro#7711]
### 🐛 bug 描述

在执行'npm run start'的时候，会报这错误：
>error evaluating function `darken`: color.toHSL is not a function

### 📷 复现步骤

1、拉取v2.2.0版本，执行`npm install` ，然后执行`npm update`
2、执行`npm run start` 就会报这错误.

### 🏞 期望结果

因为我用的项目还是基于v2.0的，因为技术太菜，不会升级到v4.0, 所以希望在2.0版本能有解决方案

### © 版本信息

- Ant Design Pro 版本: [e.g. 2.2.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26159724/100960312-f9404680-355a-11eb-8019-89b6fdae9f40.png)

**Comment by chenshuai2144** [comment]
你是使用了什么插件吗？这个看起来是 less 编译报错导致的

**Comment by chenshuai2144** [comment]
在一个 issue 里处理吧
