### ISSUE TITLE
🐛[BUG] v2.2.0 修改less后，报"FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"

### ISSUE THREAD

**Issue by niming175** [ant-design/ant-design-pro#7712]
### 🐛 bug 描述

在开发模式下，修改了`less`样式后，会自动编译，然后就会报错
>FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### 📷 复现步骤

1、拉取v2.20版本， 执行`npm install` 然后执行`npm update`;
2、执行`npm run start` 进入开发模式；
3、修改任一`less`样式文件，终端会报这错误；

### 🏞 期望结果

因为我的项目是基于`v2.0`的， 技术太菜，不会升级到v4.0, 每次修改样式都会报错，这让我很抓狂，希望在该版本能有个解决方案

### © 版本信息

- Ant Design Pro 版本: 2.2.0
- umi 版本: 2.4.2
- 浏览器环境: edge
- 开发环境: mac os

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26159724/100961090-9d76bd00-355c-11eb-8138-11727c12f7ff.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/100974457-3dd9db00-3577-11eb-9813-c0f8ed78cf3c.png)


把这个插件干掉，应该就好了，去项目搜一下 碰到 antd-theme-generator 的及直接删掉

**Comment by chenshuai2144** [comment]
这个问题估计也是一样的 https://github.com/ant-design/ant-design-pro/issues/7711

**Comment by niming175** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/100974457-3dd9db00-3577-11eb-9813-c0f8ed78cf3c.png)
> 
> 把这个插件干掉，应该就好了，去项目搜一下 碰到 antd-theme-generator 的及直接删掉

package.json 里并没有引用该报，应该是某个插件使用该包，目前不知道是哪个包在使用该包

**Comment by chenshuai2144** [comment]
`npm ls antd-theme-generator `

这样就能看见了

**Comment by niming175** [comment]
> npm ls antd-theme-generator

涉及到的包是`antd-theme-webpack-plugin`, 但不知道是干嘛的， 在`config/plugin.config.js`中引用，注释掉相关代码；项目确实能正常跑起来；但是就是不知道这个包具体作用是什么，删了会不会有什么影响

**Comment by chenshuai2144** [comment]
是为了动态计算插件的，但是less 的消耗有点大，所以导致了卡顿和内存泄露

**Comment by Benjaminbai** [comment]
我也遇到了这个问题，如何解决？

**Comment by chenshuai2144** [comment]
直接删除掉

**Comment by chenxizhang** [comment]
https://github.com/ant-design/ant-design-pro/issues/9015#issuecomment-907594630 通过指定node 的版本号可以解决这个问题
