### ISSUE TITLE
当配置了 responseInterceptors 后，全局的错误处理失效 🐛[BUG]

### ISSUE THREAD

**Issue by GreatAuk** [ant-design/ant-design-pro#7713]
### 🐛 bug 描述

当配置了 responseInterceptors 后，返回的数据中 `success`  为 `false`  的情况下 ` errorHandler` 没有被触发， 全局的错误处理失效。但配置 `responseInterceptors` 是非常常见的需求

### © 版本信息

- Ant Design Pro 版本:  V5
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
success 是你们业务逻辑的，你要真的报错才能出发，比如 404  403 这样的。
自定义的逻辑需要自定义中间件来使用的

**Comment by GreatAuk** [comment]
> success 是你们业务逻辑的，你要真的报错才能出发，比如 404 403 这样的。
> 自定义的逻辑需要自定义中间件来使用的

![image](https://user-images.githubusercontent.com/20253809/100974816-e5efa400-3577-11eb-81bd-cc31aea75acd.png)

**Comment by chenshuai2144** [comment]
你使用了 v5 的 useRequest 吗？ 
给我看看代码

**Comment by GreatAuk** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/20253809/101135147-5fee5e80-3646-11eb-8420-7a4ed71ad1c9.png)

**Comment by chenshuai2144** [comment]
request 没有做自动得错误处理得，你需要自己处理一下。

判断 res.success=false, throw new Error('') 就能阻断执行了
