### ISSUE TITLE
🧐[问题] router设置layout：false的，在本地看不到menu的layout，但是还会有容器的，部署到线上也希望有

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/ant-design-pro#7716]
复现：官方案例即可
1、设置layout：false，本地开发可见layout相关元素
![image](https://user-images.githubusercontent.com/38031220/100993768-c618aa00-3590-11eb-8614-44fbe62b4a94.png)
![image](https://user-images.githubusercontent.com/38031220/100993805-d29d0280-3590-11eb-8b86-cc6458aecdf5.png)

2、部署到线上，就看不到layout相关元素，导致很多页面开发样式操控不方便
![image](https://user-images.githubusercontent.com/38031220/100993887-e5173c00-3590-11eb-8e94-3c39b87b0ee7.png)

请问如何解决

**Comment by chenshuai2144** [comment]
升级一下最新的版本，我们做了一些修改，现在直接返回children了

**Comment by Augustzyh** [comment]
好嘞，可以了多谢
