### ISSUE TITLE
🧐[问题] 项目 umi在ie上打开报错 页面进不去

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7717]
### 🧐 问题描述

在ie上打开项目，语法错误 InvalidTokenError: Invalid token specified: 无法获取未定义或 null 引用的属性“replace”
![image](https://user-images.githubusercontent.com/45235142/101004953-ac309480-359b-11eb-999b-62e5c7151424.png)
![image](https://user-images.githubusercontent.com/45235142/101005094-b6529300-359b-11eb-94cc-c62c76e1d3c2.png)

**Comment by chenshuai2144** [comment]
开发不支持  ie 的，产物才支持 ie11

**Comment by Asence** [comment]
好的吧  大佬能不能先把合并单元格导出的问题想想办法 项目进度卡着了

**Comment by chenshuai2144** [comment]
合并单元格导出 是什么？ 哪个issue？

**Comment by Asence** [comment]
#7708

**Comment by Asence** [comment]
这个

**Comment by chenshuai2144** [comment]
先关了，去另外一个issue里跟踪
