### ISSUE TITLE
🧐[问题] v5动态菜单如何做多语言？后台可以随时更改菜单名称，locales文件能动态添加多语言吗？

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#7719]
动态菜单如何做多语言？

需求是后台可以随时更改菜单名称，但是locales文件里面没有配置，就会有错误提示。

不能直接去掉，因为项目里面已经有多语言的使用，去掉也会报错。

或者能不能单独关掉菜单的多语言功能?

**Comment by chenshuai2144** [comment]
你可以设置 menu.locale =false，就可以关闭菜单的国际化了。

如果你都由后端变了，为什么不国际化也让后端做了。

**Comment by z-lionel** [comment]
> 你可以设置 menu.locale =false，就可以关闭菜单的国际化了。
> 
> 如果你都由后端变了，为什么不国际化也让后端做了。

嗯，可以后端做，主要是要关闭菜单本地locales文件没有的报错问题，关闭了，剩下就交给后端做，多谢解答
