### ISSUE TITLE
🐛[BUG] V5 版本的app.ts layout onPageChange 进入一个页面会走两次

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#7721]
V5 版本的app.ts layout onPageChange 进入一个页面会走两次，用的是hash路由
![image](https://user-images.githubusercontent.com/30397655/101146216-b2834700-3655-11eb-910c-3dd8e9f0f851.png)
![image](https://user-images.githubusercontent.com/30397655/101146243-ba42eb80-3655-11eb-8113-229136bbee16.png)
我加了个随机数，进入一个页面，执行了两次。

**Comment by leshalv** [comment]
https://github.com/ant-design/ant-design-pro/issues/7696

**Comment by chenshuai2144** [comment]
这个是因为触发了重定向，先是去了 `/` , 然后重定向到了 `webclome`, 想要解决问题可以在login中配置到 `/webclome`

https://github.com/ant-design/ant-design-pro/blob/99312f5cc1da41ca794c2f6257d8c522d53e6d12/src/pages/user/login/index.tsx#L40

可以这里配置以下，或配置个忽略，根路由不要做特殊处理
