### ISSUE TITLE
[问题]请问如何以生产环境运行？

### ISSUE THREAD

**Issue by ahdung** [ant-design/ant-design-pro#7724]
原谅我没按格式，我相信一张图更能说明问题：
![image](https://user-images.githubusercontent.com/12094247/101234347-71447300-36f9-11eb-94bb-5d7c8be2764c.png)

**Comment by chenshuai2144** [comment]
前端生产和编译的唯一区别应该是访问 proxy， 这个环境变量也是为了配置 proxy 中的 环境配置。

如果你要访问正式环境，最好的办法是修改一下 proxy 中的url，指到 正式环境

**Comment by ahdung** [comment]
@chenshuai2144 是这里吗？我改成这样没用啊，还是按start里的PORT跑
![image](https://user-images.githubusercontent.com/12094247/101298149-8d662280-3867-11eb-9e67-7561012d0398.png)

**Comment by chenshuai2144** [comment]
代理不会修改url。

https://pro.ant.design/blog/proxy-cn

**Comment by ahdung** [comment]
感谢您的耐心回复，不过我感觉我们说的可能不是同一个事情。
我的问题是，npm run start启动后，调试发现`process.env.NODE_ENV`仍然是`development`，而不是我指定的`production`（第8行），导致项目中涉及NODE_ENV的判断分支依然走dev环境，我想知道如何让`NODE_ENV`以`production`环境运行。

**Comment by chenshuai2144** [comment]
@ahdung  你改不了的我记得，NODE_ENV 是非常重要的环境变量，只有 umi build  的时候才会设置

**Comment by ahdung** [comment]
@chenshuai2144 请教设置方法

**Comment by chenshuai2144** [comment]
为什么有这个需求？

**Comment by ahdung** [comment]
@chenshuai2144 正式跑起来用production不是很合理么。主要是development的话，会出现右边配置齿轮，和右下角Umi UI配置这些不宜给到用户的东西。还请大佬教授方法

**Comment by chenshuai2144** [comment]
用一个新的变量来产生不同的 config.js 好了，都用 `product`

**Comment by ahdung** [comment]
@chenshuai2144 我想象中这应该是一个典型到有标准答案甚至可以写进文档的问题，听你这么说好像很不容易

**Comment by lishaoh** [comment]
@ahdung 如果只是想模拟线上环境，你可以试试如下方法：
```bash
yarn build
serve -s ./dist
```
