### ISSUE TITLE
🐛[BUG]打开混合菜单布局和自动分割菜单，点击上方菜单会把内容替换成空白

### ISSUE THREAD

**Issue by jipfqf** [ant-design/ant-design-pro#7725]
### 🐛 bug 描述

打开导航模式中的混合菜单布局并且选中自动分割菜单，点击上方菜单会把内容替换成空白

### 🏞 期望结果

应该只是切换左侧菜单而不是把内容替换成空，已经打开的页面内容不变

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22951659/101234850-f598f500-36fd-11eb-89a1-8a2324182234.png)

**Comment by chenshuai2144** [comment]
是因为没有配置路由，点一下菜单就好了

**Comment by jipfqf** [comment]
你是说点下左侧菜单吗

**Comment by jipfqf** [comment]
> 是因为没有配置路由，点一下菜单就好了

你是说点下左侧菜单吗

**Comment by jipfqf** [comment]
> 是因为没有配置路由，点一下菜单就好了

我找到了一个跟这个问题很像的问题[#7304](https://github.com/ant-design/ant-design-pro/issues/7304)，他这个参考了一个后台把左侧第一个菜单默认打开，但是我觉得是不是不用打开，点击最上面的菜单把左侧的菜单切换一下就行了，内容不需要替换，就比如我只是想看下这个菜单下有什么东西，点击这个菜单就把内容给替换了，特别是antd pro没有tab标签的概念，就把当前打开页面内容给替换了，如果当前页面正在填写什么东西直接替换页面内容我觉得不好把

**Comment by chenshuai2144** [comment]
在输入内容的时候随便乱点， 怎么都不对的

**Comment by jipfqf** [comment]
> 在输入内容的时候随便乱点， 怎么都不对的

那能不能不替换内容啊，只是左侧菜单切换一下

**Comment by chenshuai2144** [comment]
切换菜单都不叫乱点吗？菜单切换相当于刷新浏览器了

**Comment by chenshuai2144** [comment]
Url变了内容就会变的 这是浏览器的特性，你可以改成top menu可以hover上显示子 menu

**Comment by whaty** [comment]
一堆B问题，他妈的！所有阿里的东西，第一眼看上去可以，用起来感觉就是一坨屎，自己的官网展示的效果，和拉下来的代码，跑起来都不一样！

**Comment by whaty** [comment]
我他吗从4.0就跟ant pro，到了5.0还是这B样子。代码拉到本地，绝对一堆几把问题！
