### ISSUE TITLE
🐛[BUG]注销再登录后页面问题！

### ISSUE THREAD

**Issue by 438623459** [ant-design/ant-design-pro#7729]
### 🐛 bug 描述

本地开发没有问题，打包后出现的问题。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33709385/101303586-53058100-3879-11eb-94b7-b57300cdfd5e.png)

**Comment by chenshuai2144** [comment]
这个原来也报错过，一直没法复现，你看看是不是什么样式没打包进去

**Comment by 438623459** [comment]
> 这个原来也报错过，一直没法复现，你看看是不是什么样式没打包进去

还真是，换个电脑打包就好了
