### ISSUE TITLE
🧐[问题]左侧菜单自定义icon使用问题

### ISSUE THREAD

**Issue by StylishSite** [ant-design/ant-design-pro#7730]
### 🧐 问题描述
我使用的是iconfont，有两个问题，1、部分icon不能在hover的时候变色
2、我想请问下，怎么在点击切换目录后，当前菜单目录的icon也能切换掉，我在本地测试的没问题，但是发到测试环境不行
这个菜单渲染函数在本地的时候，每次切换都会触发，但是在线上环境不会触发，请问下有没有什么办法能做到这种效果，选中的icon和未选中的icon不是同一个哦，望大佬赐教

```
 menuList.map(item => {
      return {
        ...item,
        icon: item.source && <IconFont style={{ fontSize: '18px' }} type={ path.startsWith(item.path) ? `icon${item.source}-select` : `icon${item.source}` } />,
        children: item.children && menuDataRender(item.children),
      };
    })
  )`
  }, [path]);
```

![image](https://user-images.githubusercontent.com/59858493/101335533-4c482f80-38b4-11eb-9f62-3a6dd19a1510.png)
![image](https://user-images.githubusercontent.com/59858493/101335574-579b5b00-38b4-11eb-9055-4ab0e050352f.png)

**Comment by StylishSite** [comment]
> 为什么不在 menuItemRender 里面搞呢？

还请赐教

**Comment by chenshuai2144** [comment]
menuItemRender | 自定义菜单项的 render 方法 | (itemProps: MenuDataItem) => ReactNode | -
-- | -- | -- | --


这个 api，会传给你所有值的。

**Comment by StylishSite** [comment]
> menuItemRender	自定义菜单项的 render 方法	(itemProps: MenuDataItem) => ReactNode	-
> 这个 api，会传给你所有值的。

我看了下，这个是不能获取到菜单目录信息的

**Comment by chenshuai2144** [comment]
>  菜单目录信息的

这个是什么？

**Comment by StylishSite** [comment]
> > 菜单目录信息的
> 
> 这个是什么？
加我钉钉说吧，这上面回复好难，17600336268

**Comment by chenshuai2144** [comment]
在这里是为了帮助到以后的同学！资料就留存很重要

**Comment by StylishSite** [comment]
> 在这里是为了帮助到以后的同学！资料就留存很重要

![image](https://user-images.githubusercontent.com/59858493/101435843-02108e00-3948-11eb-9b9b-370f9964a78a.png)
,就像我这个菜单，带icon的是目录，不带icon的是菜单，我打印了下，在menuitem里面是访问不到目录信息的

**Comment by StylishSite** [comment]
![image](https://user-images.githubusercontent.com/59858493/101436072-692e4280-3948-11eb-9294-8924868fc91e.png)
是在这里打印的

**Comment by chenshuai2144** [comment]
| subMenuItemRender | 自定义拥有子菜单菜单项的 render 方法 | [`(itemProps: MenuDataItem) => ReactNode`](/components/layout/#menudataitem) | - |

那你需要这个 api 了

**Comment by StylishSite** [comment]
> subMenuItemRender

好的，解决了，十分感谢
