### ISSUE TITLE
国际化失败

### ISSUE THREAD

**Issue by burning110-lab** [ant-design/ant-design-pro#7733]
### 🧐 问题描述

Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

### 💻 示例代码
```
<ConfigProvider locale={{locale: countryIntl}}>
    <PageContainer>
        <ProTable<TableListItem>
        actionRef={actionRef}
        rowKey="id"
        search={{
          layout: "vertical"
        }}
        toolBarRender={() => [
          <Button type="primary" onClick={() => handleModalVisible(true)} key="1">
            <PlusOutlined /> <FormattedMessage id="common.add"/>
          </Button>,
        ]}
        request={(params, sorter, filter) => queryRule({ ...params, sorter, filter })}
        columns={columns}
      />

      <CreateForm onCancel={() => handleModalVisible(false)} modalVisible={createModalVisible}>
        <ProTable<TableListItem, TableListItem>
          onSubmit={async (value) => {
            const success = await handleAdd(value);
            if (success) {
              handleModalVisible(false);
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          rowKey="id"
          type="form"
          columns={columns}
        />
      </CreateForm>
      {formValues && Object.keys(formValues).length ? (
        <UpdateForm
          onSubmit={async (value) => {
            const success = await handleUpdate(value);
            if (success) {
              handleUpdateModalVisible(false);
              setFormValues({});
              if (actionRef.current) {
                actionRef.current.reload();
              }
            }
          }}
          onCancel={() => {
            handleUpdateModalVisible(false);
            setFormValues({});
          }}
          updateModalVisible={updateModalVisible}
          values={formValues}
        />
      ) : null}

    </PageContainer>
  </ConfigProvider>

```

**Comment by chenshuai2144** [comment]
config.js 中设置 locale。

https://umijs.org/plugins/plugin-locale

**Comment by burning110-lab** [comment]
这个我已经设置了

**Comment by burning110-lab** [comment]
locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },

**Comment by burning110-lab** [comment]
我在使用model时候就出现这种问题，其他地方是可以的

**Comment by burning110-lab** [comment]
在使用Modal的时候就出这个问题了，我表格的国际化就是好的，不知道啥问题

**Comment by chenshuai2144** [comment]
model 里没法使用的，因为 locale 是存在 context 中的

**Comment by burning110-lab** [comment]
/**
 * 添加节点
 * @param fields
 */
const handleAdd = async (fields: TableListItem) => {
  const hide = message.loading(<FormattedMessage id="common.add.title"/>);
  try {
    await addRule({ ...fields });
    hide();
    message.success(<FormattedMessage id="common.add.success"/>);
    return true;
  } catch (error) {
    hide();
    message.error(<FormattedMessage id="common.add.fail"/>);
    return false;
  }
};  这个方法就是modal添加数据提交后api返回的结果，显示提示，到这里国际化失败了

**Comment by chenshuai2144** [comment]
message.error(); ？ 这个是什么用法？

**Comment by burning110-lab** [comment]
这个里面就是国际化内容

**Comment by burning110-lab** [comment]
const handleAdd = async (fields: TableListItem) => {
  const hide = message.loading(<FormattedMessage id="common.add.title"/>);
  try {
    await addRule({ ...fields });
    hide();
    message.success(<FormattedMessage id="common.add.success"/>);
    return true;
  } catch (error) {
    hide();
    message.error(<FormattedMessage id="common.add.fail"/>);
    return false;
  }
};``

**Comment by chenshuai2144** [comment]
你放到外面，在处理好，再扔进来。
const message = intl.formartMessage("xxxx");

message.error(message);

**Comment by burning110-lab** [comment]
不能<FormattedMessage id="common.add.title"/>直接这样使用吗？

**Comment by burning110-lab** [comment]
`<FormattedMessage id="common.add.title"/>`

**Comment by chenshuai2144** [comment]
不能的，这个是个组件，要用 方法

**Comment by chenshuai2144** [comment]
FormattedMessage 和 formattedMessage 有不同的用法

**Comment by burning110-lab** [comment]
大佬，我是刚使用ant.desgin.pro的小白，我不知道`<FormattedMessage id="common.add.title"/>` 和`intl.formartMessage({id:'xxxx'})`在这里有啥区别，`intl.formartMessage`可以动态帮定值

**Comment by burning110-lab** [comment]
明白了，🙏

**Comment by chenshuai2144** [comment]
组件和值 的不同


组件是需要上下文的，所以必须要 挂载在某个Provide下面，message.xx 是重新render 组件里没有上下文
