### ISSUE TITLE
用docker的Nginx部署完之后，映射了非80端口，每次在其他路由下刷新浏览器端口号就不见了

### ISSUE THREAD

**Issue by jiazil** [ant-design/ant-design-pro#7734]
V4版本出现这个问题，V5版本没问题

**Comment by jiazil** [comment]
![image](https://user-images.githubusercontent.com/15866105/101437663-aba54e80-394b-11eb-834f-bd8a4121aee6.png)
点完刷新后：
![image](https://user-images.githubusercontent.com/15866105/101437743-d55e7580-394b-11eb-86de-e22c44dd2091.png)

**Comment by chenshuai2144** [comment]
看看你的 js 代码吧。更改 host 这样的代码很明显的，一般框架不会写进去

**Comment by jiazil** [comment]
![image](https://user-images.githubusercontent.com/15866105/101447552-66d7e280-3960-11eb-9a5c-2f8370e3c21c.png)
我把80改为10046，docker映射调整一下就可以。这个问题在v5是没问题的

**Comment by chenshuai2144** [comment]
这个应该是 js 搞得，你看看你的代码是不是有操作 hostname 的地方，一般来说前端不会控制端口的，也没有能力感知

**Comment by jiazil** [comment]
hostname是空的

**Comment by chenshuai2144** [comment]
直接浏览器挂了，估计是什么东西没配置号
