### ISSUE TITLE
请求帮助，如何写刷新功能

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7736]
@chenshuai2144 想请教一个问题，我看了所有DEMO，没有一个类似的用法。就是页面加个 手动刷新 按钮，重新从服务器获取数据，不知道怎么写了，比如dashbord\analysis,我想点this week,再根据新的条件获取数据，DEMO里只有首次加载时获取数据。
![image](https://user-images.githubusercontent.com/17469220/101477388-2898ee00-3975-11eb-918e-9437ab486251.png)

我再补充下问题，比如如下页面选项条件发生变化，如何再次请求数据？

![image](https://user-images.githubusercontent.com/17469220/101486043-12455f00-3982-11eb-9cfa-7d3133277274.png)

**Comment by chenshuai2144** [comment]
```tsx
const { run } =  useRequest();

// 重新请求
run()
```
