### ISSUE TITLE
yarn start启动警告

### ISSUE THREAD

**Issue by xiaowang1314** [ant-design/ant-design-pro#7737]
WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json

Node版本：v14.15.1

**Comment by chenshuai2144** [comment]
提issue之前先看看是不是有一摸一样的了

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/7698
