### ISSUE TITLE
🧐[问题]protable使用actionRef.current?.reload()获取不到查询表单数据

### ISSUE THREAD

**Issue by oliviaxtli** [ant-design/ant-design-pro#7738]
### 🧐 问题描述

想实现的功能：在protable中导入文件后，调用查询接口刷新表格
出现的问题：使用actionRef.current?.reload()实现表格刷新，此时可以触发查询接口，但是获取不到已填写在查询表单中的数据
求助：请问应该怎么写才能在actionRef.current?.reload()中获取到查询表单的数据

### 💻 示例代码
```
    <ProTable
            headerTitle="查询列表"
            manualRequest
            formRef={searchForm}
            actionRef={actionRef}
            columns={columns}
            request={templateListHook.queryTemplateList}  // 使用request触发查询接口
            rowKey="key"
            toolBarRender={() => [
              <UploadCom  // 包装的antd Upload组件
                key="upload"
                loadStatus={loadStatus}
                reloadMainTable={() => {
                  actionRef.current?.reload();       // 触发表格刷新
                }}
              />
```

### 🚑 其他信息

情况一：如果在导入之前填写查询表单并点击查询，导入后刷新可以获取到查询表单的参数；
情况二：如果在导入之前仅填写查询表单但不点击查询，直接导入，导入后刷新无法获取到查询表单的参数
![image](https://user-images.githubusercontent.com/31402051/101571049-97785480-3a12-11eb-882e-c8b6713cbd0e.png)

**Comment by chenshuai2144** [comment]
ProTable 的 查询表单只有在提交之后才会生效

可以用 `formRef.current.submit` 提交下
