### ISSUE TITLE
🧐[问题] 为什么切换语言时，会自动刷新页面呢？

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design-pro#7740]
### 🧐 问题描述

开启国际化后，切换不同只语言后，页面刷新。

### 💻 示例代码

https://preview.pro.ant.design/dashboard/analysis

### 🚑 其他信息

我看官方文档介绍umi时说使用之后可以避免刷新。

**Comment by chenshuai2144** [comment]
为了解决大家不想一个设置页面的问题，不刷新页面对你的代码有很大的要求。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101989065-d2131300-3cd8-11eb-8e63-f2992484ec59.png)


setLocale 是可以配置要不要刷新的
