### ISSUE TITLE
👑 [需求]如何自定义展开和收起图标的位置

### ISSUE THREAD

**Issue by yuanye4017** [ant-design/ant-design-pro#7742]
### 🥰 需求描述
目前Ant design pro将展开和收起的图标放在左下角，如何定义图标的位置在header左侧呢？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed
