### ISSUE TITLE
一级菜单页面的面包屑是空白，如何去掉这个div呢？🧐[问题]

### ISSUE THREAD

**Issue by Cooolyu** [ant-design/ant-design-pro#7743]
### 🧐 问题描述

项目使用Pro V5，之前从Issue中了解到Pro V5从设计上不支持一级菜单的面包屑显示，那如何把这块div去掉呢，毕竟显示一个白条在这里太丑了

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16718459/101709319-30b67200-3aca-11eb-8e63-4270f2c29b73.png)

**Comment by chenshuai2144** [comment]
升级一下 antd 的版本？ 
我记得已经修过了

**Comment by Cooolyu** [comment]
@chenshuai2144 antd已经升级到4.9.2版本，问题依然还在

**Comment by chenshuai2144** [comment]
👌

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101713647-04532380-3ad3-11eb-87cc-5be850bb956c.png)


给我看看你的元素审查、

**Comment by Cooolyu** [comment]
![Uploading image.png…]()

**Comment by Cooolyu** [comment]
![image](https://user-images.githubusercontent.com/16718459/101714792-3e252980-3ad5-11eb-89bf-a46c419f663a.png)

**Comment by chenshuai2144** [comment]
看起来就是antd的锅🔥   你npm ls一下

**Comment by Cooolyu** [comment]
结果在这儿https://github.com/Cooolyu/1/blob/main/log.txt，你看下

**Comment by chenshuai2144** [comment]
😓 npm ls @ant-design/pro-layout

**Comment by Cooolyu** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/16718459/101848027-7c7f1f00-3b8f-11eb-96c4-5cd7cf10b3e6.png)
