### ISSUE TITLE
🧐[问题]control+c停止运行项目后报错ELIFECYCLE，errno 1

### ISSUE THREAD

**Issue by s464446877** [ant-design/ant-design-pro#7745]
### 🧐 问题描述

npm start可以正常启动项目，但是在control+c停止运行项目后报错ELIFECYCLE

### 💻 示例代码

^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.5.0 start: `umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@4.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chun/.npm/_logs/2020-12-10T03_26_57_273Z-debug.log

**Comment by root1005214** [comment]
我也遇到了这个问题
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '~/.nvm/versions/node/v12.19.0/bin/node',
1 verbose cli   '~/.nvm/versions/node/v12.19.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:dev'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prestart:dev', 'start:dev', 'poststart:dev' ]
5 info lifecycle zebra-web@1.0.0~prestart:dev: zebra-web@1.0.0
6 info lifecycle zebra-web@1.0.0~start:dev: zebra-web@1.0.0
7 verbose lifecycle zebra-web@1.0.0~start:dev: unsafe-perm in lifecycle true
8 verbose lifecycle zebra-web@1.0.0~start:dev: PATH: ~/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/workspace/repo/shaozhaicode/zebra-web/node_modules/.bin:~/.nvm/versions/node/v12.19.0/bin:/var/folders/vh/7g5xs9q114q8c84f225wnbvr0000gn/T/yarn--1609308604399-0.36233498699894984:~/workspace/repo/shaozhaicode/zebra-web/node_modules/.bin:~/.config/yarn/link/node_modules/.bin:~/.nvm/versions/node/v12.19.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:~/.nvm/versions/node/v12.19.0/lib/node_modules/npm/bin/node-gyp-bin:~/.nvm/versions/node/v12.19.0/bin/node_modules/npm/bin/node-gyp-bin:~/.jenv/shims:~/.nvm/versions/node/v12.19.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:~/.jenv/shims:~/.nvm/versions/node/v12.19.0/bin
9 verbose lifecycle zebra-web@1.0.0~start:dev: CWD: ~/workspace/repo/shaozhaicode/zebra-web
10 silly lifecycle zebra-web@1.0.0~start:dev: Args: [ '-c', 'cross-env UMI_ENV=dev REACT_APP_ENV=dev MOCK=none umi dev' ]
11 silly lifecycle zebra-web@1.0.0~start:dev: Returned: code: 1  signal: null
12 info lifecycle zebra-web@1.0.0~start:dev: Failed to exec start:dev script
13 verbose stack Error: zebra-web@1.0.0 start:dev: `cross-env UMI_ENV=dev REACT_APP_ENV=dev MOCK=none umi dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (~/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (~/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zebra-web@1.0.0
15 verbose cwd ~/workspace/repo/shaozhaicode/zebra-web
16 verbose Darwin 19.6.0
17 verbose argv "~/.nvm/versions/node/v12.19.0/bin/node" "~/.nvm/versions/node/v12.19.0/bin/npm" "run" "start:dev"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error zebra-web@1.0.0 start:dev: `cross-env UMI_ENV=dev REACT_APP_ENV=dev MOCK=none umi dev`
22 error Exit status 1
23 error Failed at the zebra-web@1.0.0 start:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by chenshuai2144** [comment]
https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle

```
Step 1: $ npm cache clean --force

Step 2: Delete node_modules by $ rm -rf node_modules package-lock.json folder or delete it manually by going into the directory and right-click > delete / move to trash. Also, delete package-lock.json file too.

Step 3: npm install

To start again, $ npm start

This worked for me. Hopes it works for you too.

PS: Still if it is there, kindly check the error it is displaying in red and act accordingly. This error is specific to node.js environment. Happy Coding!!
```
