### ISSUE TITLE
🧐[问题] Pro5 `src/services/API.d.ts` 定义接口数据的类型太多, 如何拆分这个文件呢

### ISSUE THREAD

**Issue by wywppkd** [ant-design/ant-design-pro#7747]
### 🧐 问题描述

如题, 定义的接口数据类型太多了, 如何拆分 `src/services/API.d.ts` 文件呢, TS 声明文件这块了解的不多, 网上也没找到想要的答案~~

### 💻 示例代码

- 目前打算创建多个声明文件(API1.d.ts, API2.d.ts...), 内部都声明同名的命名空间`declare namespace API{...}`, 没有报错, 不知道能不能这样写呢?

```ts
// API1.d.ts
declare namespace API {
  export type LoginParamsType = {
    username: string;
    password: string;
  };
}

// API2.d.ts
declare namespace API {
  export type Table = {
    title: string;
    desc: string;
  };
}
```

**Comment by chenshuai2144** [comment]
没必要拆分吧 徒增工作量

**Comment by wywppkd** [comment]
> 没必要拆分吧 徒增工作量

主要考虑 2 个原因
1. 多人同时开发修改 `API.d.ts` 文件容易产生版本冲突
2. `API.d.ts` 文件越来越大后期不好管理

**Comment by chenshuai2144** [comment]
API.ts应该用脚本生成而不是自己写

**Comment by wywppkd** [comment]
> API.ts应该用脚本生成而不是自己写
> 
> 自己写的没必要放到api里了 放到各自的文件夹里 组合到一起

`脚本生成`这个大概是怎样实现呢? 是通过mock数据做的吗, 之前的项目一直是手动定义的😹

**Comment by chenshuai2144** [comment]
@wywppkd   https://github.com/alibaba/pont

swagger 解千愁，什么都自动生成的
