### ISSUE TITLE
🐛[BUG] actionRef.current.reload(); 没有重新去获取表格头部的值

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7748]
### 🐛 bug 描述

我把输入框的值清空 然后调了actionRef.current.reload();  发现他还是带了上一次请求的请求的数据；
没有重新去获取表单里面的最新的值；

### 🏞 期望结果

每一次actionRef.current.reload(); 都可以重新获取头部搜索的值

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/45235142/101775291-33e14a80-3b2a-11eb-87f5-f838523fc9ae.png)
![image](https://user-images.githubusercontent.com/45235142/101775344-4d829200-3b2a-11eb-937f-b77d23ebd2db.png)

**Comment by chenshuai2144** [comment]
执行以下 `formRef.current.submit()`，只要点击查询按钮才会重新设置得 查询参数

**Comment by Asence** [comment]
可是在表格的ref.current 没有submit()这个执行事件啊
![image](https://user-images.githubusercontent.com/45235142/102032112-e9deba00-3df2-11eb-94ef-64c420b0887e.png)

**Comment by Asence** [comment]
好了好了 我加了个 formRef

**Comment by Asence** [comment]
但是编辑提交会报
![image](https://user-images.githubusercontent.com/45235142/102038962-8f9a2500-3e03-11eb-8038-56ea4fa74e58.png)
这是什么情况

**Comment by Asence** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
你提交的值为空，你输入了什么东西呢？

**Comment by Asence** [comment]
![image](https://user-images.githubusercontent.com/45235142/102161855-0ea26280-3ec3-11eb-996a-068810e3ec50.png)
![image](https://user-images.githubusercontent.com/45235142/102161878-182bca80-3ec3-11eb-82f0-efa379be4ed7.png)
就是这样的

**Comment by chenshuai2144** [comment]
😯

**Comment by Asence** [comment]
辛苦啦
