### ISSUE TITLE
🧐[问题]在打包后，protable的tooltip在DOM中层级改变

### ISSUE THREAD

**Issue by oliviaxtli** [ant-design/ant-design-pro#7751]
### 🧐 问题描述

protable中的列使用了ellipsis属性，本地npm start环境下tooltip的层级在table下，但是npm build部署上环境之后，tooltip层级在table外层。想请教下这是什么原因？

### 💻 示例代码

protable的columns：
```
{
      title: 'Test',
      dataIndex: 'test',
      search: false,
      ellipsis: true,
}
```

### 🚑 其他信息
tooltip：
![image](https://user-images.githubusercontent.com/31402051/101852983-cff66a80-3b99-11eb-9bb4-8d249083f334.png)

本地环境：
![image](https://user-images.githubusercontent.com/31402051/101853448-8ce8c700-3b9a-11eb-92fd-a27247d5d475.png)

打包部署的测试环境：
![image](https://user-images.githubusercontent.com/31402051/101853166-22d02200-3b9a-11eb-852b-ae0c927faebb.png)

**Comment by chenshuai2144** [comment]
配置了 ConfigProvide ？

**Comment by oliviaxtli** [comment]
> 配置了 ConfigProvide ？

请教下你说的这个是在哪里配置？我应该没修改过这个

**Comment by chenshuai2144** [comment]
你更新一下本地吧，估计是版本的问题
