### ISSUE TITLE
🧐[问题]非根目录下的部署，访问出现 500 错误

### ISSUE THREAD

**Issue by luneice** [ant-design/ant-design-pro#7752]
### 🧐 问题描述

由于我要部署的目录在非根目录下，也就是部署到`${host}/index.php/abc/`，且web容器的配置文件不支持修改。如果访问`${host}/index.php/abc/` 浏览器报 `500` 错误，且出现 `Referrer Policy: strict-origin-when-cross-origin`，如果访问 `${host}/index.php/abc/index.html` 页面不停转圈，其他资源均出现 `500 Referrer Policy: strict-origin-when-cross-origin` 错误。

### 💻 示例代码
根据官方文档的要求修改的配置代码如下
nginx 的配置 abc.conf
```
server{
    listen 80;
    server_name abc.com;

    access_log /luneice/website/logs/abc.com.log;
    index index.html index.php index.htm;
    root /luneice/website/dist/;
    location / {
        try_files $uri $uri /index.html;
    }
}
```
config.js 的配置
```
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';

const { REACT_APP_ENV } = process.env;
export default defineConfig({
...
proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/index.php/abc/',
    publicPath: '/index.php/abc/',
  },
}
```
站点的目录结构为
```
- luneice
  - website
    - dist   <- nginx 配置文件指明的根目录
      - index.php
        - abc  <- 实际要部署的目录
```

**Comment by chenshuai2144** [comment]
`Referrer Policy: strict-origin-when-cross-origin`  一般是在https 中访问 http 得报错，再检查下你的代码把

**Comment by rodchen-king** [comment]
你的路径部署，因为不是根目录，所以项目当中需要配置 publicPath: '/index.php/'，这样部署出来的包里的文件引用才会从根目录正常访问。

转圈圈的情况，可以看一下页面，应该是页面资源加载不到。

**Comment by luneice** [comment]
> 你的路径部署，因为不是根目录，所以项目当中需要配置 publicPath: '/index.php/'，这样部署出来的包里的文件引用才会从根目录正常访问。
> 
> 转圈圈的情况，可以看一下页面，应该是页面资源加载不到。

能麻烦简短的给一下配置代码吗？

**Comment by rodchen-king** [comment]
> > 你的路径部署，因为不是根目录，所以项目当中需要配置 publicPath: '/index.php/'，这样部署出来的包里的文件引用才会从根目录正常访问。
> > 转圈圈的情况，可以看一下页面，应该是页面资源加载不到。
> 
> 能麻烦简短的给一下配置代码吗？

https://umijs.org/zh-CN/config#publicpath
