### ISSUE TITLE
👑 [一点建议]antd是国内react的标杆，请不要越跑越偏

### ISSUE THREAD

**Issue by galileo303** [ant-design/ant-design-pro#7753]
umi和pro原先我还觉得不错，现在越来越觉得群魔乱舞。

完全不考虑开发者和使用者。越来越远离初衷了。

框架本质本来就应该提升开发体验，提高开发效率。
现在的pro和umi开发体验没体验到啥好处，配置倒是越来越繁琐，不是这里出错就是哪里出问题。升级就要去翻源码看。文档也不会及时更新。升级不会不做任何兼容，或者提示。

走了一大圈，不能立马写业务不说，还要重新去学习哪些所谓自己发明，自认为牛x的插件，写法确实牛逼，但是这些重型插件，百分之90都是不能用的，需要重新改造。而且改造起来还不如重新写一个组件。适用性太弱。可能写这个组件的人感觉不到，但是对于百分之90的使用者来说，都是哗众取宠。

越来越觉得pro和umi在沉浸在自己的世界里面，自己感动自己。认为自己的组件价值观是“伟大的”，而忽略了中国大部分react开发者的开发体验。当打开pro给的案例的时候，ohshirt～！react是这么写的吗？大段大坨恶心的群魔乱舞的代码，个现聪明。结果成了一个乱糟糟的代码页面，没有任何思想的硬怼的业务代码。就像初级程序员开发一个紧急需求一样。

越来越华而不实，反而是带偏了react开发者们的思考方向。越来越觉得react乱七八糟。本来的初衷是为了取代cra，智能化的配置。现在看来，配置成了群魔乱舞，相反还不如cra自己配置一个反而比umi快很多，自有很多。

我觉得应该值得思考

**Comment by yutingzhao1991** [comment]
> 但是这些重型插件，百分之90都是不能用的，需要重新改造。

具体什么问题？插件应该都是直接可以用的，不需要改造。

**Comment by xiaohuoni** [comment]
其实这个问题，简单的说，就是越和蚂蚁内部的设计越吻合的方案，用 umi@3 就会越舒服。越偏离设计的方案，就会觉得越复杂。举一个具体一点的例子，umi 把握了 route，plugin 掌握了 layout。给用户的操作空间非常小，也许在内部项目，或者团队内有强制规范的项目中使用会觉得省了很多事情。但是不少团队有自己的开发习惯时，就会有晦涩难懂的感觉。拿我这边的情况来说，所有的设计都遵从蚂蚁对外的规范，只有路由采用了约定式路由，这一点的差异，但是需要做的工作就会多出很多。

**Comment by phoema** [comment]
umi@3在多入口、build静态文件时的编译性能、调试debug方面是不是能尽快提升一下啊。

**Comment by chenshuai2144** [comment]
主要是人力不够，ant design pro 主要就我一个人维护，我还要做内部的业务，还要做插件，还要做procomponents，所以pro 收窄了使用范围，专心服务中后台。

如果能接受我们的模式是可以很快的实现一个 crud 的页面，各种 xxx 管理后台可以很快的搭建起来。

需求催生产品。我们主要满足内部的需求，所以就会变成现在的样子

**Comment by fanhualei** [comment]
越来越多的人贡献代码，就好了。光使用，不贡献，就给antDesignPro很大压力。

**Comment by phoema** [comment]
pro这边还好，1个人顶3个人，umi好像更严重。
使用国产中发现问题也是一种贡献，并不一定是提交代码。
