### ISSUE TITLE
🧐[问题]在ant-design-pro上使用第三方组件，引入antd样式导致整个布局样式乱

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#7754]
### 🧐 问题描述
在使用[react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form)组件需要引入antd样式，引入后网页显示这样
![image](https://user-images.githubusercontent.com/23183393/101878928-6b540380-3bcb-11eb-8a55-7e84e2513ff7.png)
不引入antd样式显示这样
![image](https://user-images.githubusercontent.com/23183393/101878990-8757a500-3bcb-11eb-9520-dbeab5234425.png)

**Comment by chenshuai2144** [comment]
是一位内使用了两个不同版本的antd 吗？

**Comment by xyy7260** [comment]
@chenshuai2144 
@rjsf/antd 组件的 package.json antd版本是4.0
  "devDependencies": {
    "@ant-design/icons": "^4.0.0",
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/plugin-transform-react-jsx": "^7.3.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.10.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.4.4",
    "@babel/runtime-corejs2": "^7.10.3",
    "@rjsf/core": "^2.4.0",
    "antd": "^4.0.0",
    "atob": "^2.0.3",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.6",
    "concurrently": "^5.1.0",
    "core-js": "^2.5.7",
    "cross-env": "^2.0.1",
    "css-loader": "^3.2.0",
    "dayjs": "^1.8.0",
    "eslint": "^4.9.0",
    "eslint-config-react-app": "^2.0.1",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.4.0",
    "jest": "24.9.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "lodash": "^4.17.15",
    "react": "^16.8.6",
    "react-app-polyfill": "^1.0.4",
    "react-dom": "^16.8.6",
    "react-test-renderer": "^16.13.1",
    "rimraf": "^3.0.2",
    "style-loader": "^1.0.0",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-middleware": "^3.4.0",
    "webpack-hot-middleware": "^2.13.2"
  },
antd-pro 使用的antd版本是 
 "antd": "^4.8.0",
 "antd-theme-generator": "^1.2.4",
 ......
果然使用了两个不同版本的antd，我需要把antd-pro的antd 4.8.0 改成 4.0.0 吗

**Comment by chenshuai2144** [comment]
用npm ls一下

**Comment by xyy7260** [comment]
@chenshuai2144  npm ls 太多了 一个窗口无法显示
![image](https://user-images.githubusercontent.com/23183393/102053309-7d7baf00-3e22-11eb-8db9-7f4b57d8e10c.png)

**Comment by xyy7260** [comment]
@chenshuai2144  
npm ls  antd 
├─┬ @ant-design/pro-layout@6.0.0-3
│ └── antd@4.8.4
├─┬ @umijs/preset-react@1.6.19
│ ├─┬ @umijs/plugin-antd@0.9.0
│ │ └── antd@4.9.1
│ └─┬ @umijs/plugin-layout@0.12.5
│   └── antd@4.9.1
└── antd@4.9.3

npm ls @rjsf/antd
└── @rjsf/antd@2.4.0

**Comment by chenshuai2144** [comment]
看起来没有问题 你用了 core 包了吗

**Comment by xyy7260** [comment]
@chenshuai2144  用了

**Comment by chenshuai2144** [comment]
估计引入了 bootstrap 了，这个包是用来干啥的 从来没见过呀

**Comment by xyy7260** [comment]
@chenshuai2144   那我把"core-js"删除掉在试一试，目前只有用了"@rjsf/core": "^2.4.0"是组件必须引入的包。 如果还是不行我想的办法就是，把那些布局乱的元素去修改他们style 貌似只有2部分修改。 第一部分值左边栏和右边空白出
![image](https://user-images.githubusercontent.com/23183393/102162980-30044e00-3ec5-11eb-9067-da47f328dddf.png)

**Comment by xyy7260** [comment]
解决了， 我直接引入import 'antd/lib/form/style/css'  thx
