### ISSUE TITLE
🧐[问题]useRequest 统一错误处理404错误提示信息为空

### ISSUE THREAD

**Issue by wenbolwm** [ant-design/ant-design-pro#7755]
![Snipaste_2020-12-11_16-09-00](https://user-images.githubusercontent.com/1632932/101879497-6479c080-3bcc-11eb-9a00-6138753755da.png)
看原因是404时，errorInfo 拿不到 404相关的信息
这种情况，官方有推荐的方法吗?

**Comment by chenshuai2144** [comment]
这个是个约定，你在返回得数据里加个 error Message 就会展示，我看到你的配置得 statusText。

可以看看这个文档 

https://umijs.org/plugins/plugin-request#errorconfigadaptor

**Comment by wenbolwm** [comment]
> 这个是个约定，你在返回得数据里加个error消息就会展示，我看到你的配置得statusText。
> 
> 可以看看这个文档
> 
> https://umijs.org/plugins/plugin-request#errorconfigadaptor

![404](https://user-images.githubusercontent.com/1632932/102001554-855a2700-3d2e-11eb-823a-a2667e41e921.png)
![4041](https://user-images.githubusercontent.com/1632932/102001562-88edae00-3d2e-11eb-8d94-112ea37118c5.png)
我就是get了一个404的接口，没有任何返回
error.response 相关信息应该是umi 自己写入的

**Comment by chenshuai2144** [comment]
你这个不是约定好的 404，真的 404，要用 try catch来解决了，
```tsx
export const request: RequestConfig = {
  errorHandler,
};
```

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/request-cn
