### ISSUE TITLE
一个直击灵魂的需求, 默认颜色有点丑,  我想clone下来的代码,默认主题色就是蓝色的

### ISSUE THREAD

**Issue by imsjw** [ant-design/ant-design-pro#7756]
默认颜色有点丑,  我想clone下来的代码,默认主题色就是蓝色的
默认颜色有点丑,  我想clone下来的代码,默认主题色就是蓝色的
默认颜色有点丑,  我想clone下来的代码,默认主题色就是蓝色的

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/476bfbfe8415fab918f9c66fc0c43368e1443a97/config%2FdefaultSettings.ts

你想要得是这种蓝色吗?
```tsx
const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
 navTheme: 'light',
  // 拂晓蓝
  primaryColor: 'blue',
  layout: 'mix',
}
```

**Comment by imsjw** [comment]
是的

**Comment by imsjw** [comment]
这个默认颜色比那个好看的多得多了

**Comment by chenshuai2144** [comment]
那个是我们的品牌色，你可以设置 primaryColor ，就会修改主色调。

怎么说了默认的蓝色太蓝了。

**Comment by imsjw** [comment]
了解了,多谢
