### ISSUE TITLE
網址重新导向(redirect)成主頁

### ISSUE THREAD

**Issue by worldleadertechSteven** [ant-design/ant-design-pro#7757]
### 🧐 问题描述

如果用戶已經登入了，但他不小心去在網址在加了(/user/login)變成登錄頁(http://localhost:8080/user/login)，
怎樣可以令到網址重新导向(redirect)成主頁(http://localhost:8080) ？

**Comment by chenshuai2144** [comment]
可以在 login里加个判断，如果已经登陆，就跳转到主页。
在实际使用中我们一般都是这么做的
