### ISSUE TITLE
🧐[问题] V5 国际化怎么只保留中文和英文

### ISSUE THREAD

**Issue by foxyZeng** [ant-design/ant-design-pro#7758]
### 🧐 问题描述

locales文件夹下只剩中文和英文文件了，然后我也删除了.umi，重新编译，还是有繁体这些，怎么解决呀。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/101985048-66bd4700-3cc0-11eb-9377-5350ef601e28.png)

试了试 是可以的！

**Comment by foxyZeng** [comment]
可是我的还是有。。删除了无效

**Comment by foxyZeng** [comment]
![QQ截图20201216171256](https://user-images.githubusercontent.com/11335550/102328466-139a0b80-3fc2-11eb-893f-b8d6ac3dabae.png)
![QQ截图20201216171242](https://user-images.githubusercontent.com/11335550/102328481-172d9280-3fc2-11eb-8f89-8875a391308a.png)

**Comment by foxyZeng** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/8186664/101985048-66bd4700-3cc0-11eb-9377-5350ef601e28.png)
> 
> 试了试 是可以的！

![QQ截图20201216171242](https://user-images.githubusercontent.com/11335550/102328612-404e2300-3fc2-11eb-9d86-f95264d8f390.png)
![QQ截图20201216171256](https://user-images.githubusercontent.com/11335550/102328618-4217e680-3fc2-11eb-97de-a907464d1c8f.png)

**Comment by foxyZeng** [comment]
src/.umi/plugin-locale/localeExports.ts
![QQ截图20201216171724](https://user-images.githubusercontent.com/11335550/102328919-acc92200-3fc2-11eb-883b-60a94186e22e.png)

**Comment by foxyZeng** [comment]
`{
  "name": "ant-design-pro",
  "version": "5.0.0-beta.1",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "cross-env UMI_ENV=prod umi build",
    "deploy": "npm run site && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier --check \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "start": "umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none umi dev",
    "start:no-mock": "cross-env MOCK=none umi dev",
    "start:no-ui": "cross-env UMI_UI=none umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.0.19",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.5.0",
    "@ant-design/pro-table": "^2.9.16",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.8.6",
    "antd-img-crop": "^3.13.2",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.7.4",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "puppeteer-core": "^5.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}`

**Comment by chenshuai2144** [comment]
你的截图没出来

**Comment by foxyZeng** [comment]
翻墙就可以看到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈帅"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 中午11:19
收件人: "ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;; 
抄送: "千里あ寻风"<840208856@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-pro] 🧐[问题] V5 国际化怎么只保留中文和英文 (#7758)





 
你的截图没出来

**Comment by chenshuai2144** [comment]
你是不是在 src/pages 里面还有语言的配置信息

**Comment by foxyZeng** [comment]
你给个邮箱，我发你源码看看呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:21
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"千里あ寻风"<840208856@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] V5 国际化怎么只保留中文和英文 (#7758)





 
你是不是在 src/pages 里面还有语言的配置信息

**Comment by foxyZeng** [comment]
没有，给你发源码。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:21
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"千里あ寻风"<840208856@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] V5 国际化怎么只保留中文和英文 (#7758)





 
你是不是在 src/pages 里面还有语言的配置信息

**Comment by chenshuai2144** [comment]
你在 github 上新建一个仓库，扔上来发给我好了

**Comment by foxyZeng** [comment]
https://github.com/foxyZeng/ant-pro-v5-test



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:32
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"千里あ寻风"<840208856@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] V5 国际化怎么只保留中文和英文 (#7758)





 
你在 github 上新建一个仓库，扔上来发给我好了

**Comment by chenshuai2144** [comment]
https://github.com/foxyZeng/ant-pro-v5-test/tree/master/src/pages/exception/500/locales

把这些里面的也要全删除哦

**Comment by foxyZeng** [comment]
额。。。没注意。。万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:52
收件人:&nbsp;"ant-design/ant-design-pro"<ant-design-pro@noreply.github.com&gt;;
抄送:&nbsp;"千里あ寻风"<840208856@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题] V5 国际化怎么只保留中文和英文 (#7758)





 
https://github.com/foxyZeng/ant-pro-v5-test/tree/master/src/pages/exception/500/locales
 
把这些里面的也要全删除哦
