### ISSUE TITLE
🧐[问题]Get store outside component or without connect

### ISSUE THREAD

**Issue by quanptit18** [ant-design/ant-design-pro#7761]
### 🧐 问题描述
I have read https://v2.umijs.org/guide/with-dva.html#faq.
It says : window.g_app._store.
But i cannot get store. Anyone can help me in more detail than doc.

**Comment by chenshuai2144** [comment]
@ycjcl868 cc

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
