### ISSUE TITLE
🧐[问题]Ant Design Pro 如何对接公司的sso

### ISSUE THREAD

**Issue by wenbolwm** [ant-design/ant-design-pro#7763]
```
/**
 * 退出登录，并且将当前的 url 保存
 */
const loginOut = async () => {
  await outLogin();
  const { query, pathname } = history.location;
  console.log(history.location)
  const { redirect } = query;
  // Note: There may be security issues, please note
  if (window.location.pathname !== '/user/login' && !redirect) {
    history.replace({
      pathname: '/user/login',
      search: stringify({
        redirect: pathname,
      }),
    });
  }
};

export async function outLogin() {
  // return request('/api/login/outLogin');
  return request('/logout');
}
```
![1](https://user-images.githubusercontent.com/1632932/102012469-98e4ac80-3d85-11eb-82cc-1022cd321dd7.png)
![2](https://user-images.githubusercontent.com/1632932/102012473-9aae7000-3d85-11eb-87e9-31cef7276e9e.png)
![3](https://user-images.githubusercontent.com/1632932/102012474-9c783380-3d85-11eb-9bbf-833402609fde.png)

对接公司的sso时，登入和登出怎么实现浏览器url跳转啊？用上述默认方法获取不到服务端返回的302相关信息，浏览器的url也没有跳转到sso的页面还停留在当前

**Comment by mushroomlb** [comment]
window.location.href = 'sso网址'

**Comment by lunhui1994** [comment]
返回302不能直接重定向么？
