### ISSUE TITLE
🐛[BUG]刚安装的v5，二级菜单图标不显示，列表警告需要唯一key

### ISSUE THREAD

**Issue by heibais** [ant-design/ant-design-pro#7765]
### 🐛 bug 描述
按照步骤安装的v5，二级菜单图标不显示，列表警告需要唯一key。
以前也使用过，都没有出现这种问题。

### 📷 复现步骤
直接按照官网首页步骤安装。
### 🏞 截图信息
![image](https://user-images.githubusercontent.com/34224645/102032961-26abb080-3df5-11eb-8d0f-49d47e2462a6.png)

**Comment by chenshuai2144** [comment]
二级图表不显示是 featrue，重复 key 我看看

**Comment by lishaoh** [comment]
@heibais 二级icon可暂用以下解决：
![1608114278993](https://user-images.githubusercontent.com/20917295/102336353-05e98380-3fcc-11eb-95ea-a5562e6b26d0.jpg)

**Comment by Lonly007** [comment]
> 
> 
> @heibais 二级icon可暂用以下解决：
> ![1608114278993](https://user-images.githubusercontent.com/20917295/102336353-05e98380-3fcc-11eb-95ea-a5562e6b26d0.jpg)

我尝试以后报错如下：ReferenceError: Link is not defined

**Comment by chenshuai2144** [comment]
从 umi 中引入一下 Link

**Comment by Lonly007** [comment]
> 
> 
> 从 umi 中引入一下 Link

您好，使用您给的代码并引用Link后，我的二级菜单也可以设置图标了，多谢您了。

**Comment by heibais** [comment]
> @heibais 二级icon可暂用以下解决：
> ![1608114278993](https://user-images.githubusercontent.com/20917295/102336353-05e98380-3fcc-11eb-95ea-a5562e6b26d0.jpg)

非常感谢

**Comment by jemygraw** [comment]
贴下完整的代码，需要的用。
```
      menuItemRender={(menuItemProps, defaultDom) => {
        if (
          menuItemProps.isUrl ||
          !menuItemProps.path ||
          location.pathname === menuItemProps.path
        ) {
          return defaultDom;
        }

        return <Link to={menuItemProps.path}>
          {menuItemProps.pro_layout_parentKeys && menuItemProps.pro_layout_parentKeys.length > 0 &&
          menuItemProps.icon}{defaultDom}</Link>;
      }}
```

**Comment by lishaoh** [comment]
@jemygraw 不能加 location.pathname === menuItemProps.path，不然在二级菜单页刷新浏览器还是不会显示icon
