### ISSUE TITLE
左侧导航栏收缩动画丢失

### ISSUE THREAD

**Issue by pzc666** [ant-design/ant-design-pro#7770]
### 🐛 bug 描述
点击菜单栏的收缩按钮，左侧导航直接展开收起，过渡动画丢失。

### 📷 复现步骤
官方预览页面稳定复现
https://preview.pro.ant.design/dashboard/analysis

### 🏞 期望结果
点击收缩按钮的时候，有过渡动画。
### 💻 复现代码
官方预览页面稳定复现
https://preview.pro.ant.design/dashboard/analysis

### © 版本信息

- Ant Design Pro 版本: 4.3.0
- umi 版本 3.3.2
- 浏览器环境 Google
- 开发环境 mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/37856520/102196122-6dcf9980-3efa-11eb-8f85-bf17fbd83994.png)

**Comment by chenshuai2144** [comment]
有个pr修掉了，发了版本就好了

**Comment by chenshuai2144** [comment]
已经修复
