### ISSUE TITLE
在from表单中使用select时候，通过filterOption函数来筛选，只能获取到value的值，获取不到label的值

### ISSUE THREAD

**Issue by burning110-lab** [ant-design/ant-design-pro#7772]
### 🐛 bug 描述

在from表单中使用select时候，通过filterOption函数来筛选，只能获取到value的值，获取不到label的值
### 📷 复现步骤

直接使用ant.desgin官网自带select案例，采用filterOption也是获取不到label的值
### 🏞 期望结果
我期望获取到value和label的值，本来这个函数参数也提供获取label的值，但是获取到都是undefine

我期望获取到value和label的值，本来这个函数参数也提供获取label的值，但是获取到都是undefine
### 💻 复现代码
` filterOption={(input,option) => option?.value.includes(input)}`
这个option包含了value、label、key的值，唯有label的值获取不到

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://ant.design/components/select-cn/#components-select-demo-label-in-value
