### ISSUE TITLE
🐛[BUG]V5版本没有"fetch:blocks"命令

### ISSUE THREAD

**Issue by LeoChenCQH** [ant-design/ant-design-pro#7773]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
就是这么设计的 还不支持拉取全部

**Comment by LeoChenCQH** [comment]
> 就是这么设计的还不支持拉取全部
但是我看开发文档里是有写执行此命令即可拉取全部区块，但不知为什么V5的版本是不支持呢，我已经下回V4了，V4是有的

**Comment by chenshuai2144** [comment]
因为还没发布😂
