### ISSUE TITLE
🐛[BUG] 文档错误

### ISSUE THREAD

**Issue by jasper-pan** [ant-design/ant-design-pro#7774]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/23065701/102301122-2f38ee00-3f91-11eb-9c79-e417f0a69430.png)

 menuDateRender 字段不对 
### 🏞 期望结果
应该为 menuDataRender

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新一下就刷新了 写了个错别字
