### ISSUE TITLE
🧐[问题]我在使用PageContainer时,不希望breadcrume显示出来，但是不知道怎么配置可以实现这个功能？

### ISSUE THREAD

**Issue by Lonly007** [ant-design/ant-design-pro#7777]
### 🧐 问题描述

我在使用PageContainer时,不希望breadcrume显示出来，就是删除下图中的红色选中部分，但是不知道怎么配置可以实现这个功能？

### 💻 示例代码
import React from 'react';
import { PageContainer } from '@ant-design/pro-layout';

export default (): React.ReactNode => {
  return (
    <PageContainer affixProps={false} >
      Hello Herolei
    </PageContainer>
  );
};

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/34476562/102354120-16f2be80-3fe5-11eb-93db-cff3959a99d7.png)

**Comment by 569202812** [comment]
breadcrume={false} 或者 breadcrume={undefined}

**Comment by chenshuai2144** [comment]
或者可以设置 `breadcrumbRender={()=>[]} `自定义面包屑

**Comment by Lonly007** [comment]
> 
> 
> breadcrume={false} 或者 breadcrume={undefined}

使用您的设置后，“实时监控/远程控制”没有了，但是大的黑体字“远程控制”还显示，请问1）如何把它也去掉？2）如何查看文档以确认对于“PageContainer ”组件，我能设置哪些东西？ 不好意思，作为新手，我的问题太low了。

**Comment by Lonly007** [comment]
> 
> 
> 或者可以设置 `breadcrumbRender={()=>[]} `自定义面包屑

感谢您的回答，我是一个新手，想请教您如何查看文档以确认对于“PageContainer ”组件，我能设置哪些东西？或是我能回调哪些接口进行一些部分的自定义开发？。

**Comment by 569202812** [comment]
> > breadcrume={false} 或者 breadcrume={undefined}
> 
> 使用您的设置后，“实时监控/远程控制”没有了，但是大的黑体字“远程控制”还显示，请问1）如何把它也去掉？2）如何查看文档以确认对于“PageContainer ”组件，我能设置哪些东西？ 不好意思，作为新手，我的问题太low了。

这是另一个属性 ```title```，如果不想展示可以使用 ```GridContent``组件，更多参考文档[pagecontainer](https://procomponents.ant.design/components/layout#pagecontainer)

**Comment by Lonly007** [comment]
此问题在@569202812 的帮助下已经完全解决，整理如下：
1）breadcrumb可以在属性中使用：breadcrumb={false} 或者 breadcrumb={undefined}直接取消
2）titile需要去掉的话使用``GridContent``组件即可

这是一个很初级的问题，希望对其他新手有帮助，官方文档很重要，还是需要仔细阅读，当前V5的文档不够完善，可以在这里先提问解决。

再次感谢569202812和chenshuai2144的分享！

**Comment by xiaodin1** [comment]
> 
title={() => []}
page: https://procomponents.ant.design/components/page-container
header: https://ant.design/components/page-header-cn/
