### ISSUE TITLE
使用table组件  如果让表格的表头竖着显示

### ISSUE THREAD

**Issue by 591749921** [ant-design/ant-design-pro#778]

**Comment by chenshuai2144** [comment]
如何让竖着显示

**Comment by 591749921** [comment]
我用ant  design 没有实现出来

**Comment by ddcat1115** [comment]
antd Table 暂不支持横向表格。[#8214](https://github.com/ant-design/ant-design/issues/8214) [#4312](https://github.com/ant-design/ant-design/issues/4312)

PS: 单纯的 antd 组件问题请到 https://github.com/ant-design/ant-design/issues 讨论，Thx~
