### ISSUE TITLE
🧐[问题] antd pro预览项目， 查询表格模块选择表格行后，为什么多出一个div样式？

### ISSUE THREAD

**Issue by maochongzi** [ant-design/ant-design-pro#7781]
### 🧐 问题描述

如下图所示

### 💻 示例代码

官方预览： https://preview.pro.ant.design/list/table-list

### 🚑 其他信息

[image](https://user-images.githubusercontent.com/34764808/102455964-73082200-407b-11eb-9c22-3d6ef5e1b0b1.png)

**Comment by chenshuai2144** [comment]
是footerTooBar, 不过看起来没显示出来

**Comment by chenshuai2144** [comment]
fixed in  2.17.3
