### ISSUE TITLE
🐛[BUG] "View chart components doc" link not working

### ISSUE THREAD

**Issue by roxylu** [ant-design/ant-design-pro#7782]
### 🐛 bug 描述

"View chart components doc" link returns 404 on https://v2-pro.ant.design/docs/graph

### 📷 复现步骤

1. Visit https://v2-pro.ant.design/docs/graph, and search for "View chart components doc" link.
2. Click the link, and it takes you to https://pro.ant.design/components/charts/, which is a 404 page.

### 🏞 期望结果

It should go to https://v2-pro.ant.design/components/charts.

### 💻 复现代码

N/A

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

N/A

**Comment by chenshuai2144** [comment]
You may be forced to upgrade to the latest g2

https://g2.alipay.com/
