### ISSUE TITLE
🐛[BUG]Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by liuht777** [ant-design/ant-design-pro#7783]
### 🐛 bug 描述

npm create umi

构建的V5 V4版本的最新脚手架都有这个问题，查询表格都有这个警告。
而且，构建的V4版本，每个页面打开都是一堆黄色的警告，这个水准好像不行吧

### 📷 复现步骤

npm create umi 构建最新的V4 V5 版本，均有这个问题。

### © 版本信息

- Ant Design Pro 版本: V4 V5 最新版
- umi 版本
- 浏览器环境
- 开发环境 windows10

**Comment by chenshuai2144** [comment]
我们依赖的各种底层库不更新，所以才做了 v5 的，很多都是生命周期的过期声明

**Comment by liuht777** [comment]
Each child in a list should have a unique "key" prop，那这个问题是不是应该解决下

**Comment by chenshuai2144** [comment]
这周发了版本会解决，是 https://procomponent.ant.design/ 的问题

**Comment by liuht777** [comment]
静候佳音。
另外V5，有什么生产实践吗

**Comment by chenshuai2144** [comment]
内部已经在用了，但是外部没有精力搞一直发不了

**Comment by rodchen-king** [comment]
> 内部已经在用了，但是外部没有精力搞一直发不了

外部用应该ok的吧。

**Comment by chenshuai2144** [comment]
用起来蛮爽的，我还是很喜欢用的

**Comment by Veexx** [comment]
@chenshuai2144 请问pro-table更新了吗，v4版本的pro-table 2.16.2还是会直接报错
![image](https://user-images.githubusercontent.com/32189627/102735221-ced4f280-437c-11eb-858d-4cffaef7759c.png)

**Comment by liuht777** [comment]
> 内部已经在用了，但是外部没有精力搞一直发不了

V5 正式版什么时候发啊?

**Comment by chenshuai2144** [comment]
fixed in 2.17
