### ISSUE TITLE
如果有多个项目全部用ant design pro  如何使用monorepo的方式 实现组件共享👑 [需求]

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/ant-design-pro#7784]
### 🥰 需求描述

假设我们的项目目录是这样的
![image](https://user-images.githubusercontent.com/19420622/102587608-1eca7400-4147-11eb-8601-029c66a3a55a.png)
apps 使我们使用create react app起的项目，libs 是这些项目依赖的公共组件。
使用 @craco/craco 替换react-scripts 启动项目。
![image](https://user-images.githubusercontent.com/19420622/102588058-c8aa0080-4147-11eb-80d4-3d0c3ceea644.png)
![image](https://user-images.githubusercontent.com/19420622/102588152-f0996400-4147-11eb-8eb0-a1249cc30283.png)

craco 会帮助我们将lia中打包到项目中。这样就实现了在monorepo多个项目组件的共享。那么如果我们的项目替换成 ant design pro 框架是否也支持这种类似的方式 实现组件共享呢

**Comment by chenshuai2144** [comment]
我们好像没有这样的实践  @sorrycc @ycjcl868  cc,我最近也有个需求

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/

试试这里的方式

**Comment by semmywong** [comment]
有没有用turbo整合这种monorepo的方案
