### ISSUE TITLE
🐛[BUG]ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7785]
onSubmit = async (model) => {
await this.setState({ data: model });
}

上述的代码报错了：

ReferenceError: regeneratorRuntime is not defined

Umi 版本：3.3.2
Node 版本：14.11.0
操作系统：windows 2019

**Comment by chenshuai2144** [comment]
>  async和await关键字让我们可以用一种更简洁的方式写出基于Promise的异步行为，而无需刻意地链式调用promise。

读一下规范吧

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by effapp** [comment]
> > async和await关键字让我们可以用一种更简洁的方式写出基于Promise的异步行为，而无需刻意地链式调用promise。
> 
> 读一下规范吧
> 
> https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function

报错了，请问下述这个错误怎样解决：

ReferenceError: regeneratorRuntime is not defined

**Comment by chenshuai2144** [comment]
async和await关键字让我们可以用一种更简洁的方式写出基于Promise的异步行为，而无需刻意地链式调用promise。

基于 promise， 你await 得方法需要是一个promise。 setState 不是 promise
