### ISSUE TITLE
🧐[问题] 打包文件大小按需引入问题

### ISSUE THREAD

**Issue by matianhe3** [ant-design/ant-design-pro#7787]
![image](https://user-images.githubusercontent.com/24929062/102595614-d618b800-4152-11eb-8d86-ebd40d4c15fb.png)

请问打包后的体积 360k, 属于正常吗?

```
import ProTable, { ProColumns } from '@ant-design/pro-table';
import { QueryFilter, ProFormDateRangePicker, ProFormText, ProFormSelect } from '@ant-design/pro-form';
```
目前的引入方式是按需引入吧, 用脚手架搭建是不是不用单独配置babel了, 有没有什么方法可以减少体积呢?

**Comment by CannonAndroid** [comment]
试试我的，我的感觉不大。。。
 //提取antd_pro
            antd_pro: {
              name: 'antd_pro',
              test: /pro-table|pro-field|pro-form|pro-descriptions|pro-cil|pro-skeleton|pro-layout|pro-utils|pro-provider/,
              priority: 11,
              chunks: 'async',
              enforce: true,
            },

 //提取antd-design_compatible
            ant_compatible: {
              name: 'ant_compatible',
              test: /ant-design_compatible/,
              priority: 11,
              chunks: 'async',
              enforce: true,
            },

            //提取antd es
            antd_es: {
              name: 'antd_es',
              test: /antd[\\/]es/,
              priority: 11,
              chunks: 'async',
              enforce: true,
            },

            //提取antd lib
            antd_lib: {
              name: 'antd_lib',
              test: /antd[\\/]lib/,
              priority: 11,
              chunks: 'async',
              enforce: true,
            },

 //提取ant_icon_svg
            ant_icon_svg: {
              name: 'ant_icon_svg',
              //打包成单独文件 
              // name(module:any) {
              //   const packageName = module.resource.match(/[a-z|A-Z]*.js/);
              //   if (!packageName) return 'ant_icon_svg';
              //   return packageName;
              // },
              test: /ant-design_icons-svg/,
              priority: 12,
              chunks: 'async',
              enforce: true,
            },

            //提取ant_icon
            ant_icon: {
              name: 'ant_icon',
              //打包成单独文件 
              // name(module: any) {
              //   const packageName = module.resource.match(/[a-z|A-Z]*.js/);
              //   if (!packageName) return 'ant_icon';
              //   return packageName;
              // },
              test: /ant-design_icons/,
              priority: 11,
              chunks: 'async',
              enforce: true,
            },

**Comment by matianhe3** [comment]
> 试试我的，我的感觉不大。。。
> //提取antd_pro
> antd_pro: {
> name: 'antd_pro',
> test: /pro-table|pro-field|pro-form|pro-descriptions|pro-cil|pro-skeleton|pro-layout|pro-utils|pro-provider/,
> priority: 11,
> chunks: 'async',
> enforce: true,
> },
> 
> //提取antd-design_compatible
> ant_compatible: {
> name: 'ant_compatible',
> test: /ant-design_compatible/,
> priority: 11,
> chunks: 'async',
> enforce: true,
> },
> 
> ```
>         //提取antd es
>         antd_es: {
>           name: 'antd_es',
>           test: /antd[\\/]es/,
>           priority: 11,
>           chunks: 'async',
>           enforce: true,
>         },
> 
>         //提取antd lib
>         antd_lib: {
>           name: 'antd_lib',
>           test: /antd[\\/]lib/,
>           priority: 11,
>           chunks: 'async',
>           enforce: true,
>         },
> ```
> 
> //提取ant_icon_svg
> ant_icon_svg: {
> name: 'ant_icon_svg',
> //打包成单独文件
> // name(module:any) {
> // const packageName = module.resource.match(/[a-z|A-Z]*.js/);
> // if (!packageName) return 'ant_icon_svg';
> // return packageName;
> // },
> test: /ant-design_icons-svg/,
> priority: 12,
> chunks: 'async',
> enforce: true,
> },
> 
> ```
>         //提取ant_icon
>         ant_icon: {
>           name: 'ant_icon',
>           //打包成单独文件 
>           // name(module: any) {
>           //   const packageName = module.resource.match(/[a-z|A-Z]*.js/);
>           //   if (!packageName) return 'ant_icon';
>           //   return packageName;
>           // },
>           test: /ant-design_icons/,
>           priority: 11,
>           chunks: 'async',
>           enforce: true,
>         },
> ```

ok, 回头试试.
