### ISSUE TITLE
🧐[问题]菜单跳转到外部地址，链接被截取

### ISSUE THREAD

**Issue by cryst4lMao** [ant-design/ant-design-pro#7788]
### 🧐 问题描述

在配置路由时候，需要跳转到外币地址，按文档配置了path后，实际dom渲染出来的a标签中href属性值缺少了？后面的参数；
请问为啥会去掉？能不能保留完整的配置外链地址？

### 💻 示例代码
这里是config.js的路由配置
```
{
              path: 'https://zhuanlan.zhihu.com/p/94949118?from_voters_page=true',
              name: 'test-demo',
              icon: 'profile'
            }
```

### 🚑 其他信息

![捕获](https://user-images.githubusercontent.com/12853720/102598012-5e4c8c80-4156-11eb-8d11-38fcc9caa1ed.JPG)

**Comment by chenshuai2144** [comment]
算法搞出了问题，我来修一下

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103208679-3f12e380-493c-11eb-8d67-fab2f3d18398.png)

修复了，更新一下试试

**Comment by w01fb0ss** [comment]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/44709004/185086487-4662dcee-4f2d-4716-952b-7f68e6ccf65b.png">

同样遇到这个问题，发现生成的页面，不是个a标签，怎么都会跳转到新的页面，按照文档应该是添加`target: '_blank',`才会跳转到新的页面，但是我不加这个，还是会跳转
<img width="584" alt="image" src="https://user-images.githubusercontent.com/44709004/185086757-d9722829-2525-48f4-97ef-e087ad71b15d.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/44709004/185086341-b3014c5b-af81-4225-9a56-095be36d148c.png">
