### ISSUE TITLE
代理设置了无效

### ISSUE THREAD

**Issue by a526800921** [ant-design/ant-design-pro#7792]
就昨天刚新装的，v4，simple，已关闭mock
config/proxy.js文件里面

  '/api': {
    target: 'https://xxx',
    changeOrigin: true,
    pathRewrite: {
      '^': '',
    },
  },

这配置没效果，接口返回了页面的html？？？

将/api改成了**才有效果

  '**': {
    target: 'https://xxx',
    changeOrigin: true,
    pathRewrite: {
      '^': '',
    },
  },

**Comment by a526800921** [comment]
改成 ** 之后页面刷新直接404

**Comment by a526800921** [comment]
真是绝了，刷新到404后改回来代理好了

**Comment by chenshuai2144** [comment]
😂 这个配置是一个正则表达式

正则果然入门门槛很高
