### ISSUE TITLE
🐛[BUG]菜单折叠后，第一次移上一级菜单，有时无法弹出二级菜单

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design-pro#7794]
### 🐛 bug 描述

基于antd pro的系统，点击左侧菜单收起按钮，菜单收起后，鼠标从右侧内容区移到左侧一级菜单图标上，无法正常弹出二级菜单
需要移到别处，再移上刚才的一级菜单，才会弹出

### 📷 复现步骤

**注意：有时不会出现，但出现的几率很高，请尽量避免先移上其他菜单，而是从右侧内容区滑到左侧菜单**
**如果没有出现，只需再次展开-折叠，即可再次测试，无需刷新页面**
1 点击菜单收起按钮
2 菜单收起后，鼠标从右侧内容区移到左侧一级菜单图标上
3 无法正常弹出二级菜单
4 将鼠标移到别处，再移到刚才的一级菜单上
5 二级菜单能正常弹出

### 🏞 期望结果

点击菜单收起按钮，菜单收起后，鼠标从各个方位移到一级菜单图标上，总是能正常弹出二级菜单

### 💻 复现代码

https://preview.pro.ant.design/

### © 版本信息

- Ant Design Pro 版本: 2.0.2
- umi 版本 3.2.14
- 浏览器环境 Chrome
- 开发环境 Win7

### 🚑 其他信息

![菜单折叠后，第一次移上一级菜单，无法弹出二级菜单](https://user-images.githubusercontent.com/11645301/102692189-c41b4000-424c-11eb-97c6-278c2a9ec08d.png)

**Comment by chenshuai2144** [comment]
没有复现诶，有 repo 吗

**Comment by chairui2001** [comment]
刚才试了下，无法复现了。回头我再用当时出现这个问题的电脑试试

**Comment by chairui2001** [comment]
又详细测试了下，发现是加入了以下样式会出现这个问题：
`.anticon {
    font-size: 14px !important;
}`
比如加在 global.less 中，或者直接在官方预览网站F12加在body上。
注意操作方式：点完折叠按钮以后，鼠标从右侧出来到内容区，然后划入左侧菜单。不要点完折叠按钮顺势往上滑。
另外，之前官网预览的确出现过，我还截过图。不过现在确实不会复现了。

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
