### ISSUE TITLE
🐛[BUG]重新安装依赖后报错了： Unexpected token in JSON at position 1 at parse (<anonymous>) 

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design-pro#7795]
重新安装依赖后，运行时报错了： Unexpected token in JSON at position 1 at parse ()

![image](https://user-images.githubusercontent.com/51013754/102703899-fa3ddb80-42af-11eb-9eab-bec62db4fb9c.png)

![image](https://user-images.githubusercontent.com/51013754/102703996-2c037200-42b1-11eb-9b9a-b06a8f166beb.png)

![image](https://user-images.githubusercontent.com/51013754/102704004-42a9c900-42b1-11eb-9a44-1a1c86441af6.png)

Umi Version: 3.3.2
Node Version: 14.11.0
Platform: windows server 2019
Antd pro : v5

**Comment by chenshuai2144** [comment]
这个是你的逻辑问题。
