### ISSUE TITLE
 [问题] v5 protable的数据更新后如何刷新局部组件

### ISSUE THREAD

**Issue by jipfqf** [ant-design/ant-design-pro#7797]
如题，我在protable中渲染了一个switch,用datasource中的某个字段来控制其是否选中

现在问题是我改了其中一条数据的这个字段值后，这个switch选中状态并没有随之改变，我知道用actionref.reload重新加载数据后会变，但是需要重新请求接口

现在能不能实现我改了表格中的某个字段后只是局部刷新下，不用重新调用接口

**Comment by chenshuai2144** [comment]
这个和 proTable 没有关系，你要让 table 知道你的 dataSouce 是个新的，比如浅拷贝什么的。

可变数据是万恶之源。使用起来要小心一些

**Comment by jipfqf** [comment]
> 这个和 proTable 没有关系，你要让 table 知道你的 dataSouce 是个新的，比如浅拷贝什么的。
> 
> 可变数据是万恶之源。使用起来要小心一些

是我需要把这个datasource单独存一份，直接改这个datasource 表格就会刷新，还是说我处理每条数据传进来的record就行，protable上有个request参数，但是没有单独接收datasource的参数，我就有点迷table咋知道datasource是个新的

**Comment by chenshuai2144** [comment]
protable也支持dataSource
