### ISSUE TITLE
🧐[问题]v5 后台获取菜单怎么配置呢？

### ISSUE THREAD

**Issue by Jack-Aizelasi** [ant-design/ant-design-pro#7798]
### 🧐 问题描述

create创建的项目 v5，菜单看到是在config中配置的，在app.ts中与官网上的不一样，有RunTimeLayoutConfig，求解

### 💻 示例代码

export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { location } = history;
      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser && location.pathname !== '/user/login') {
        history.push('/user/login');
      }
    },
    menuHeaderRender: undefined,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings,
  };
};

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/59014138/102706880-bdcea780-42d0-11eb-852c-67e522082397.png)

**Comment by ideaviewes** [comment]
https://procomponents.ant.design/components/layout/

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

**Comment by chengzequn** [comment]
楼主有解决这个问题吗？感觉文档里的内容不是很好懂。如果解决能不能贴个代码也帮帮我，感谢
