### ISSUE TITLE
demo用的"antd": "^3.0.0-beta.1",但是antd还没发布这个版本吧？

### ISSUE THREAD

**Issue by chenange** [ant-design/ant-design-pro#78]

**Comment by afc163** [comment]
https://pro.ant.design/docs/faq#%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Ant-Design-Pro%EF%BC%9F

**Comment by chenange** [comment]
嗯嗯，看到了
