### ISSUE TITLE
报错：./node_modules/nightmare/lib/nightmare.js Module not found: Can't resolve 'child_process' in 'D:\webStormProjects\sino-safe-web\node_modules\nightmare\lib'

### ISSUE THREAD

**Issue by dongtianqi** [ant-design/ant-design-pro#780]
报错了，我想动态import组件，就像引入model一样
`./node_modules/nightmare/lib/nightmare.js
Module not found: Can't resolve 'child_process' in `'D:\webStormProjects\sino-safe-web\node_modules\nightmare\lib'`

代码：
 const dynamicWrapper = (app, models, component) => dynamic({
        app,
        models: () => models.map(m => import(`./models/${m}.js`)),
        component: () => import(`${component}`),
      });
      const navData = [
        {
          component: dynamicWrapper(app, ['user', 'login'], './layouts/BasicLayout'),
          layout: 'BasicLayout',
          name: '首页', // for breadcrumb
          path: '/',
          children: [

**Comment by dongtianqi** [comment]
111

**Comment by chenshuai2144** [comment]
感觉是你的包没装好！  试试cnpm

**Comment by afc163** [comment]
require 里带 `/` 的问题。

**Comment by chenshuai2144** [comment]
还需要注意一个问题  webpack是不支持全动态路径的。
https://webpack.js.org/api/module-methods/#import-
