### ISSUE TITLE
🐛[BUG] 菜单和头部导航高亮重复点击

### ISSUE THREAD

**Issue by RIPm** [ant-design/ant-design-pro#7800]
### 🐛 bug 描述
菜单和头部导航高亮时点击，会加入路由栈。导致路由不断叠加，退回的时候要点到叠加次数为止

### 🏞 期望结果

高亮重复点击，不加入路由栈

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0/5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xmn1990** [comment]
我也出现这样的问题  ！！！！！

**Comment by Cherdinand** [comment]
这样重复点击还能跳转 好不合理 啥时候能修复

**Comment by gyt95** [comment]
我也遇到过这个bug

**Comment by chenshuai2144** [comment]
这个好像是link 的bug 以前都没有过 
控制台会直接报错的

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/monitor

这里看起来还是 ok 的，是不是更新了什么奇怪的依赖

**Comment by RIPm** [comment]
> https://preview.pro.ant.design/dashboard/monitor
> 
> 这里看起来还是 ok 的，是不是更新了什么奇怪的依赖

你试试点3次监控页，你再按退回 要退3次才退回来。这些点击进入了路由栈堆里面了

**Comment by chenshuai2144** [comment]
还真是，我去 react router 提个 bug，业务层面做去重有点难搞

**Comment by RIPm** [comment]
哥 你解析出是当前 不让点击不是可以了吗
