### ISSUE TITLE
🐛[BUG]切换国际化语言后，没有渲染出菜单

### ISSUE THREAD

**Issue by LB-nan** [ant-design/ant-design-pro#7806]
### 🐛 bug 描述

在切换国际化语言后，刷新页面，然后菜单栏消失，看log打印，第一次获取到的menu是空数组，然后接着又打印出来一个有数据的数组，但是并未重新渲染。

### 🏞 期望结果

我试了重新登录是可以的，切换语言后需要执行什么操作么，或者在渲染的地方有没有什么可以等待一下接口返回数据的方法，或者有数据重新渲染的方法。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] ： 
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

```
    "@ant-design/pro-layout": "^6.5.0",
    "@ant-design/pro-descriptions": "^1.0.19",
    "@ant-design/pro-table": "^2.9.16",
    "@ant-design/pro-form": "^1.3.0",
    "umi": "^3.1.2",
    "antd": "^4.8.6",
```

这个版本是我今天复制之前的项目然后进行版本升级后的，然后就出现了这个问题，原来的项目测试并没有这个问题，虽然也打印了两次菜单栏数据，且第一次为空数据。

之前的依赖版本如下
```
    "@ant-design/pro-layout": "^6.4.18",
    "@ant-design/pro-table": "^2.2.7",
    "umi": "^3.1.2",
    "antd": "4.2.0",
```
没有另外两个依赖。

### 🚑 其他信息

![12](https://user-images.githubusercontent.com/26077292/102753899-11132980-43a7-11eb-8413-b9ad3a539afa.png)

**Comment by LB-nan** [comment]
发现和`@ant-design/pro-layout`有关系，版本切换回`6.4.18`就没有这个毛病了，

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

看看这个文档，设置一下 menu.loading，menuDataRender 改变不会触发重新渲染
