### ISSUE TITLE
🐛[BUG]动态路由menuDataRender函数执行缺少一步

### ISSUE THREAD

**Issue by FE-zj** [ant-design/ant-design-pro#7809]
### 🐛 bug 描述
**场景：直接在地址栏输入栏非首页的地址**  期望能将接口的路由数据正常渲染至页面
![image](https://user-images.githubusercontent.com/64066443/102880205-ef3ca400-4485-11eb-8281-d55ee5f6b6a6.png)

   版本： "@ant-design/pro-layout": "^4.6.1", 
   4.x.x的版本 执行时机正常
代码和执行情况如下图所示
![image](https://user-images.githubusercontent.com/64066443/102879737-42622700-4485-11eb-95a0-58ec2392c942.png)
![image](https://user-images.githubusercontent.com/64066443/102879792-57d75100-4485-11eb-983b-df800cb1035d.png)
**结果：路由可以正常渲染**
版本：    "@ant-design/pro-layout": "^6.5.0",
**6.5.0的版本就少执行了最后一步**
代码和上面一样
但是执行情况如下图
![image](https://user-images.githubusercontent.com/64066443/102880108-c9af9a80-4485-11eb-8642-dd16b07c32fa.png)
**结果：路由没有正常渲染**
望能尽快解决这个问题 这个问题导致项目做不下去

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/getting-started-cn

看看这个

**Comment by guyunxiang** [comment]
用 postMenuData, menuDataRender 只在第一次渲染时生效，之后就不执行了。
