### ISSUE TITLE
🧐[问题]如果区分环境来判断是否要加载 layout

### ISSUE THREAD

**Issue by bluescurry** [ant-design/ant-design-pro#7810]
### 🧐 问题描述
需求是：当 REACT_APP_ENV === 'dev' 时使用 layout，其他环境下不加载 layout，我在 config.ts 中判断了环境，代码如下：
`typescript
layout: REACT_APP_ENV === 'dev' ? {
    name: '业务分析平台',
    locale: false,
    siderWidth: 208,
    ...defaultSettings,
  } : false,
`
因为会对 layout 有一些自定义配置，所以在 app.tsx 中设置 export const layout = { ... }。
目前的问题是当 app.tsx 有 layout 字段时就会执行 layout 插件的内容就会报错，报错信息如下：
![image](https://user-images.githubusercontent.com/19237129/102880564-7be76200-4486-11eb-8a6e-12a57e528b24.png)
请问这种场景应该怎么处理呢？

**Comment by chenshuai2144** [comment]
在 app.ts 中设置 layout

```
const layout ={
 pure: REACT_APP_ENV === 'dev'
}
```

这样应该能满足你的需求了

**Comment by bluescurry** [comment]
> 在 app.ts 中设置 layout
> 
> ```
> const layout ={
>  pure: REACT_APP_ENV === 'dev'
> }
> ```
> 
> 这样应该能满足你的需求了

好的，可以的，多谢
