### ISSUE TITLE
🐛[BUG] 使用抽屉，样式问题

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#7812]
![image](https://user-images.githubusercontent.com/30397655/102886498-2adc6b80-4490-11eb-88af-90e1294b7187.png)

**Comment by chenshuai2144** [comment]
看不懂是什么造成的？

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
