### ISSUE TITLE
[问题]antd-pro5 怎么添加一个不再Layout下的路由？

### ISSUE THREAD

**Issue by CannonAndroid** [ant-design/ant-design-pro#7813]
### 🧐 问题描述

  问题原因：为了提高登录界面打开的速度。
  问题描述：antd-pro5脚手架默认集成Layout组件，这将导致我新添加的界面都在Layout布局下，但是为了提升登录界面的速度，我将不引用antd相关的组件来实现，所以不希望在打开时加载antd相关的资源文件。我应该如何解决？希望可以配置最外层的路由，谢谢。

antd-pro  牛牛牛，希望越来越强，点赞

### 🚑 其他信息

加载的文件，我希望写个普通的界面，首次打开不加载红色框内的文件
![image](https://user-images.githubusercontent.com/17492336/102890641-be656a80-4497-11eb-81a2-af22c6188bce.png)

这是查看源码发现的文件
![image](https://user-images.githubusercontent.com/17492336/102890773-f8367100-4497-11eb-8d98-714864ace10a.png)

**Comment by chenshuai2144** [comment]
只能关掉 layout 插件，或者写个新的插件插入了，现在还不支持这种场景

**Comment by hui9464** [comment]
> 只能关掉layout插件，或者写个新的插件插入了，现在还不支持这种场景
你好，我想请教下，内置布局支持动态菜单吗

**Comment by chenshuai2144** [comment]
支持的 有文档你搜一下

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/advanced-menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95

文档在这里
