### ISSUE TITLE
🐛[BUG] 更新以后表格表头出问题了

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7815]
### 🐛 bug 描述

我没有设置表头的宽高，这个时候列表数据为空。就出来如下问题；
![image](https://user-images.githubusercontent.com/45235142/102919082-2a10fd00-44c3-11eb-8caf-ae79f32cae81.png)

这个图是正常的
![image](https://user-images.githubusercontent.com/45235142/102921134-d30d2700-44c6-11eb-9e01-55ca7fc3d0c8.png)

版本：
![image](https://user-images.githubusercontent.com/45235142/102921169-e4563380-44c6-11eb-844e-be9414534801.png)

**Comment by chenshuai2144** [comment]
看起来是浏览器的 bug，用 火狐试试?

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
