### ISSUE TITLE
🧐[问题]Cascader在Form.Item中如何更新数据

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#7816]
### 🧐 问题描述

异步加载options数据，如何更新在Form中的Cascader

### 💻 示例代码

![image](https://user-images.githubusercontent.com/12421552/102953220-c5c65b80-450b-11eb-9b75-a02bd51bcf11.png)

![image](https://user-images.githubusercontent.com/12421552/102953394-26559880-450c-11eb-8c61-dd8714e143f8.png)

### 🚑 其他信息

还有个问题是
为什么在loadDepartmentUserData 函数中的setDepartmentUserState会失效，导致更新不了departmentUser数据

![L)2O6U4BF2_T1%LY7E3NWU1](https://user-images.githubusercontent.com/12421552/102953354-0aea8d80-450c-11eb-90c2-8c8d62d036c0.png)

**Comment by chenshuai2144** [comment]
Form 不关心你怎么更新的，你只要保证能接受 Form.Item 的 value 和  调用 onChange。

你最好搞个组件，组件里包进去请求数据的逻辑。Form 为了性能渲染非常惰性
