### ISSUE TITLE
🐛[BUG] 直接通过 url 可越权访问页面！

### ISSUE THREAD

**Issue by liyupi** [ant-design/ant-design-pro#7817]
### 🐛 bug 描述

**通过 url 可越权访问！**

/src/layouts/BasicLayout.tsx 的逻辑有些问题，判断权限时，先获取现有菜单项的 authority 属性，如果不存在，则 authority 为 undifiend，不会进行鉴权。而如果用户通过 url 直接访问无权限页面（触发页面刷新），拿到的 authority 为 undifined 导致 允许访问。

### 📷 复现步骤

通过 url 访问无权限页面

### 🏞 期望结果

弹出 403

### 💻 复现代码

应该从全部菜单项中获取 authority 字段，而不是只从 ”有权限可展示“ 的菜单项中获取

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
>  而如果用户通过 url 直接访问无权限页面（触发页面刷新），拿到的 authority 为 undifined 导致 允许访问。

这样应该不会每次都会计算的，pro 默认没配置就是有权限，你可以返回来
