### ISSUE TITLE
🧐[问题]非根目录部署， 修改完路径页面改动后无变化

### ISSUE THREAD

**Issue by lolocoo** [ant-design/ant-design-pro#7819]
### 🧐 问题描述
pro v5
非根目录部署， 修改完路径页面改动后无变化而且展现的还不是最新的改动后的代码。
当把路径再改回 /， 页面就是最新改动过的代码一切就正常了。

### 💻 示例代码
config.ts

  hash: true,
  base: '/admin/',
  publicPath: '/admin/',
  // base: '/',
  // publicPath: '/',
  history: { type: 'hash' },
  manifest: {
    // basePath: '/',
    basePath: '/admin/',
  },

**Comment by chenshuai2144** [comment]
热更新坏了吗？

一般是大小写的问题，操作系统忽略大小写，但是 js 的大小写敏感的
