### ISSUE TITLE
🧐[问题] 第一次进入的时候，切换导航，发现会加载一些`p__xxxxx.js`的文件，这些文件可以一次性加载么？

### ISSUE THREAD

**Issue by LB-nan** [ant-design/ant-design-pro#7820]
### 🧐 问题描述

网站清空缓存重新进入的时候，打开控制台，看`JS`那栏，每次打开一个新的导航，都会加载一个对应的js文件，这个文件会导致屏幕出现闪屏一下，导致加载变慢，请问这个如何优化

看了一个其他的站，他们就没有这个问题，没有加载其他很多东西，应该是没有使用antd pro  只用了antd + umi

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26077292/103066265-7d826880-45f3-11eb-8200-5c461e9ef2cd.png)

**Comment by LB-nan** [comment]
如果不按需加载，需要配置啥呢

**Comment by LB-nan** [comment]
我发现官网的demo也有这个问题，而且加载的更慢，我们是闪一下loading，官网的直接loading半天

**Comment by chenshuai2144** [comment]
https://umijs.org/config#dynamicimport

关掉这个就好了，如果一次性加载包很大的，可能首次加载速度会超级慢
