### ISSUE TITLE
🐛[BUG] 点击左侧菜单路由，组件会重新渲染

### ISSUE THREAD

**Issue by chaosJS** [ant-design/ant-design-pro#7821]
### 🐛 bug 描述

新下载的ant-design-pro代码，点击左侧相同的菜单，路由没有变化，对应的组件会重新渲染

### 🏞 期望结果

不重新渲染

### © 版本信息

- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/17522683/103072997-b75a6b80-4601-11eb-9f2c-ff45bbcad48d.png)
![image](https://user-images.githubusercontent.com/17522683/103073040-cb9e6880-4601-11eb-87d1-2c47e388b2fb.png)

**Comment by bluexiaowei** [comment]
me too.

**Comment by chaosJS** [comment]
我现在的做法是给路由组件打补丁，判断路由相同就阻止重新渲染，但是每个都加很麻烦，并且可能会有意料之外的bug🐛
![image](https://user-images.githubusercontent.com/17522683/103076460-bd077f80-4608-11eb-96c8-d96b080cdbfe.png)

**Comment by chenshuai2144** [comment]
我正在翻 react-router 为什么要打开这个功能

**Comment by chenshuai2144** [comment]
加了个判断逻辑，更新依赖即可

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/6d69af72a281a31db7341573b6f9529cd1286d90/src/layouts/BasicLayout.tsx#L135-L144
