### ISSUE TITLE
🐛[BUG]超出了ResizeObserver循环限制

### ISSUE THREAD

**Issue by yubin-code** [ant-design/ant-design-pro#7823]
### 🐛 bug 描述
当顶部头像旁边搜索框失去焦点的时候会报 ResizeObserver loop limit exceeded
使用以下代码获取到的错误
`onerror=handleErr

function handleErr()
{

  console.log(arguments);
  return false
}`

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<img width="1073" alt="error" src="https://user-images.githubusercontent.com/8856962/103089710-c3f2ba00-4629-11eb-9024-d450fa7ddf3e.png">

**Comment by chenshuai2144** [comment]
更新一下依赖好了

rc-resizeObserver 发布了新的版本
