### ISSUE TITLE
👑 [需求] 使用文档建议

### ISSUE THREAD

**Issue by YuYanzy** [ant-design/ant-design-pro#7826]
### 🥰 需求描述

非常好的产品，为什么要被文档毁了？
为什么文档写的这么烂？？？
想改一下默认的语言选项，在文档里面根本找不到怎么做？
一个Ant design Pro 文档里面套娃三个组件的文档: umi, dva, procomponents？？？
而且每一个组件的文档都没有说清楚到底该怎么用？？？
直接复制粘贴文档里的代码都有问题？？？

### 🧐 解决方案

写一个完整的，细致的使用文档。

**Comment by chenshuai2144** [comment]
提 pr 吧
