### ISSUE TITLE
🐛[BUG]新版本有个路径错误 影响到启动

### ISSUE THREAD

**Issue by jinhongjie007** [ant-design/ant-design-pro#7827]
### 🐛 bug 描述

更新到最新的ant pro,出现启动不了的现象

### 📷 复现步骤

使用最新的ant pro，然后运行yarn run start,报错

### 🏞 期望结果

正常启动

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本 
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10215848/103116090-0c4cbf00-46a0-11eb-9a89-01dec6b8a56d.png)

**Comment by jinhongjie007** [comment]
> ### 🐛 bug 描述
> 更新到最新的ant pro,出现启动不了的现象
> 
> ### 📷 复现步骤
> 使用最新的ant pro，然后运行yarn run start,报错
> 
> ### 🏞 期望结果
> 正常启动
> 
> ### 💻 复现代码
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 5.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/10215848/103116090-0c4cbf00-46a0-11eb-9a89-01dec6b8a56d.png)

**Comment by jinhongjie007** [comment]
在路径中src/.umi/core/routes.ts中手动修改import LoadingComponent from '@ant-design/pro-layout/es/PageLoading'为import LoadingComponent from '@ant-design/pro-layout/es/components/PageLoading'可正常运行

**Comment by jinhongjie007** [comment]
手动改完 但是在新加模块后依然会出现这个问题  希望紧急修复下

**Comment by ISBN9527** [comment]
碰到同样的错误+1，希望早点修复。

**Comment by jinhongjie007** [comment]
最烦的是每次编译还会出现这个错误

**Comment by ISBN9527** [comment]
可以暂时修改下config.js里的路径

**Comment by chenshuai2144** [comment]
fixed，重新安装一下。文档站修改导致了这个问题
