### ISSUE TITLE
🐛[BUG]V5 开启约定式路由, 登录页面嵌入了layout当中, 404页面也无法正常显示

### ISSUE THREAD

**Issue by liuht777** [ant-design/ant-design-pro#7829]
### 🐛 bug 描述

开启约定式路由, 登录页面嵌入了layout当中
点击菜单,本应该显示404页面,但是开启约定式路由后,就不展示了,404页面必须手动输入path /404 才会显示

### 📷 复现步骤
请求后端获取菜单
开启约定式路由, config.ts中注释掉 // routes

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
无法上传图片,但我想,应该已经描述清楚了

**Comment by chenshuai2144** [comment]
约定式路由好像不支持的

@xiaohuoni  你看看，好像只有你有经验
