### ISSUE TITLE
为什么代码分离后，不同的入口文件引入同一个组件，这个组件会被分别打包到不同的chunks下面呢？

### ISSUE THREAD

**Issue by hushiyi** [ant-design/ant-design-pro#783]
比如配置文件如下：
```
const dynamicWrapper = (app, models, component) => dynamic({
  app,
  models: () => models.map(m =>
    import (`models/${m}.js`)),
  component,
});

```
```
export default app => [
  {
    "name": '首页',
    "path": '/',
    "exact": true,
    "component": dynamicWrapper(app, [], () =>
      import ('routes/home'))
  },
  {
    "name": '收银台1',
    "path": '/cashier',
    "exact": true,
    "component": dynamicWrapper(app, ['cashier'], () =>
      import ('routes/cashier')),
    }]
  }
]
```
在'routes/home'和'routes/cashier' 下都引入了componet下的同一个Charts组件，打包后发现routes/home'和'routes/cashier' 打生产包的chunk都重复引入了同一个Charts组件

**Comment by chenshuai2144** [comment]
https://webpack.js.org/guides/code-splitting/
看看这个，公用的最好common一下。webpack这种方式也很无奈。。。

**Comment by hushiyi** [comment]
￼![1516590705335](https://user-images.githubusercontent.com/13818093/35203812-0dbb6b0a-ff65-11e7-8123-b9688adb3e35.jpg)
也用了文档里面的方式配置，但是打包出来代码分离的bundle里面0.js 1.js 还是存在公共的代码，common里面提取的公共代码只是entry.js里面的公共代码，并没有解决问题。
![1516590705335](https://user-images.githubusercontent.com/13818093/35203839-38d14b5c-ff65-11e7-9470-fbf9af96f629.jpg)

我是想请问是不是dva的dynamic动态路由配置导致的这个问题？
然后我是没有用roadhog，项目用的webpack+dva的形式，
补充一个问题是，在models里面并没有用到的js，为什么也会最后打包出来了呢,比如3.js？（路由配置里面没用到的一个models，其他地方更没有引用）

**Comment by chenshuai2144** [comment]
你用的1.0版本吗？

**Comment by chenshuai2144** [comment]
webpack的问题。
webpack为了保证代码的可用性。可能代码块会造成重复。尤其是使用import ，from 的语法，要解决这个问题。你可能需要将公用的用
‘async import’语法来进行导入，这样这个库会变成单独的代码快。异步导入
