### ISSUE TITLE
🧐[问题] Too many warnings of unmet peer dependencies.

### ISSUE THREAD

**Issue by liyuanqiu** [ant-design/ant-design-pro#7830]
### 🧐 问题描述

NPM shows too many warnings of unmet peer dependencies while initiating an and-design-pro project.

Should I install all of them manually? Or just ignore it?

### 💻 示例代码

```shell
npx create-umi myapp
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24999464/103124919-5778c900-46c4-11eb-8913-25f0e9aacdd0.png)

**Comment by chenshuai2144** [comment]
好多人框架都没支持 react 17 ，可能还要等一段时间
