### ISSUE TITLE
🐛[BUG] extraBabelIncludes Error: Invalid config key 

### ISSUE THREAD

**Issue by MoonSeeing** [ant-design/ant-design-pro#7831]
## What happens?
![image](https://user-images.githubusercontent.com/19420622/103115676-8a0fcb00-469e-11eb-8446-1bf64df3eaa9.png)
在  umi 启动的项目中添加 extraBabelIncludes 就会报错如下
![image](https://user-images.githubusercontent.com/19420622/103115700-a1e74f00-469e-11eb-880b-d8759cd684e4.png)

如果不添加 这个参数 就可以正常运行。
## Mini Showcase Repository(REQUIRED)

![image](https://user-images.githubusercontent.com/19420622/103116842-d3621980-46a2-11eb-8eed-b2f4727f0656.png)

代码地址：
https://github.com/MoonSeeing/umi-shared

## How To Reproduce
1. clone code
2. yarn
3. yarn start

**Expected behavior** 1. 2.

## Context

- **Umi Version**: umi": "^3.2.14",

**Comment by chenshuai2144** [comment]
extraBabelIncludes 需要 umi@3，你的环境是什么？

**Comment by MoonSeeing** [comment]
> extraBabelIncludes 需要 umi@3，你的环境是什么？

umi@3.3.3

**Comment by MoonSeeing** [comment]
我里面有个demo  ，用umi 起的ant-designer-pro 项目，在配置中加了 extraBabelIncludes 就没法启动 @chenshuai2144

**Comment by MoonSeeing** [comment]
> extraBabelIncludes 需要 umi@3，你的环境是什么？
你有时间的话 试试启动下这个 https://github.com/MoonSeeing/umi-shared

**Comment by chenshuai2144** [comment]
这个报错是意思是这不是umi支持的配置

**Comment by MoonSeeing** [comment]
> 这个报错是意思是这不是umi支持的配置
我看官方文档 提到是支持的，然后 看之前的issue 貌似 也是支持的，难道是新版本删除了？

**Comment by MoonSeeing** [comment]
@chenshuai2144 
![image](https://user-images.githubusercontent.com/19420622/103132258-ea266180-46de-11eb-8515-b4c91c582d06.png)

**Comment by MoonSeeing** [comment]
![image](https://user-images.githubusercontent.com/19420622/103132406-6325b900-46df-11eb-835a-604dbefc326d.png)
看到umi 3 又把它删掉了，看来是不支持了
