### ISSUE TITLE
🧐[问题] umi-theme 编译时报错

### ISSUE THREAD

**Issue by zhj778930960** [ant-design/ant-design-pro#7833]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23496206/103131473-e0e7c580-46db-11eb-92ba-ff1a61e59cdb.png)

**Comment by chenshuai2144** [comment]
看起来是 node 版本的问题，底层 api 改动了？

**Comment by zhj778930960** [comment]
我的版本是14.0.7

**Comment by chenshuai2144** [comment]
用 12 吧。14 有点新了才刚出来

**Comment by zhj778930960** [comment]
> 用 12 吧，我好像没怎么用过 14

那我切到12吧

**Comment by chenshuai2144** [comment]
这个不是主要问题，只是个兼容行的 warning
