### ISSUE TITLE
🧐[问题]Descriptions.Item中颜色属性无法修改

### ISSUE THREAD

**Issue by Lonly007** [ant-design/ant-design-pro#7834]
### 🧐 问题描述
我使用Descriptions进行一些数据显示，但是无法根据具体数值动态修改字体的颜色（其实我也没做到静态修改字体颜色）。请问如何才能实现Descriptions.Item的颜色动态修改。(设置background-color可以，设置color属性却不行)

### 💻 示例代码
控件生成部分：
function CreateAnalogItems(props){
  const datas = converterAnalogStatus(props);
  const listItems = datas.map((data)=>
    <Descriptions column={3}>
      <Descriptions.Item className={styles.AnalogNameItem}>
        <Field text={data.name} mode="read"/>
      </Descriptions.Item>
      <Descriptions.Item className={styles.AnalogStatusItem}>
        <Field text={data.value} mode="read" />
      </Descriptions.Item>
      <Descriptions.Item className={styles.AnalogStatusdiscriptions} >
        <Field text={data.descript} mode="read" className={styles.AnalogTextColor} />
      </Descriptions.Item>
    </Descriptions>);

  return listItems;
}

样式部分：
.AnalogTextColor{
  color: red !important;
}

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/34476562/103131680-ac283e00-46dc-11eb-8e44-634acac4f6e3.png)

**Comment by chenshuai2144** [comment]
你这个套的太深了，不能这样全局设置的。

如果要这样建议用 importants

**Comment by Lonly007** [comment]
> 
> 
> 你这个套的太深了，不能这样全局设置的。
> 
> 如果要这样建议用 importants

能讲的再详细点么？我是个新手，看不懂你说的，不好意思。

**Comment by chenshuai2144** [comment]
用 css 来实现不要用行内的 js

**Comment by Lonly007** [comment]
> 
> 
> 用 css 来实现不要用行内的 js

我是在.less里面写的样式，设置background-color可以看到效果，但是设置color属性，字体的颜色就是不变化，加上!important也不行，因此提问。

**Comment by Lonly007** [comment]
呃，经过研究官方文档自己解决了，代码如下(动态改变颜色的部分加粗斜体显示了)，但是不明白原理，希望有高手解释一下原理或是给出一个此类问题通用的解决思路：
`function CreateAnalogItems(props) {
  const datas = converterAnalogStatus(props);
  const listItems = datas.map((data) => (
    <Descriptions column={3}>
      <Descriptions.Item className={styles.AnalogNameItem}>
        <Field text={data.name} mode="read" />
      </Descriptions.Item>
      <Descriptions.Item className={styles.AnalogStatusItem}>
        <Field text={data.value} mode="read" />
      </Descriptions.Item>
      <Descriptions.Item className={styles.AnalogStatusdiscriptions} **_contentStyle={{color:data.color}}_**>
        <Field text={data.descript} mode="read" />
      </Descriptions.Item>
    </Descriptions>
  ));`
