### ISSUE TITLE
v5 版本 如何使用request

### ISSUE THREAD

**Issue by wangjunhong** [ant-design/ant-design-pro#7835]
### 🧐 问题描述
现有一个后端项目，所有的接口已经有了一套规则，如何能够以修改参数的形式兼容到antd pro里

### 💻 示例代码
如图所示，目前我是使用自己封装的request，会提示警告，还有分页的字段current能不能自定义成别的
github上传不了图片，这里有[截图链接](http://img.yooticloud.cn/gov1608969384813)

**Comment by liganghui** [comment]
可以通过 配置请求拦截器 , 格式化请求和响应

**Comment by wangjunhong** [comment]
> 可以通过 配置请求拦截器 , 格式化请求和响应

可以 谢谢
