### ISSUE TITLE
🐛[BUG]config配置hash:true,public下的静态资源没有加hash后缀

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#7836]
### 🐛 bug 描述

config配置hash:true,public下的静态资源没有加hash后缀

### 📷 复现步骤

是产品设计成这样吗?如果想自动生成带hash后缀的静态资源

### 💻 复现代码

```
enum Status {
  WAITING = '/icons/minus-circle-outline.svg',
  RUNNING = '/icons/loading.svg',
  FAILED = '/icons/close.svg',
  SUCCESS = '/icons/check-circle.svg',
}

        cell.updateAttrs({
          image2: {
            xlinkHref: Status.RUNNING,
          },
        });

```

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.2-beta]
- umi 版本   ^3.2.21
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/70048681/103163243-9595fa00-4836-11eb-8c7c-7ae9e20b5bf3.png)

**Comment by chenshuai2144** [comment]
public 不加hash 是个 featrue，
public 表示完全静态。如果想要就加 hash 可以用
```
import  Xxx from '../xxx.svg'
```

这样的方式来使用，但是如果不是每个迭代都变化推荐使用 public ，这样可以更好的利用缓存

**Comment by quicklearning123** [comment]
> public 不加hash 是个 featrue，
> public 表示完全静态。如果想要就加 hash 可以用
> 
> ```
> import  Xxx from '../xxx.svg'
> ```
> 
> 这样的方式来使用，但是如果不是每个迭代都变化推荐使用 public ，这样可以更好的利用缓存

就是说，如果需要hash，只能移到asset目录下面吗

**Comment by chenshuai2144** [comment]
是的，hash 是为了解决缓存的问题，public 是为了缓存。
如果 public 加了缓存，public 就没有意义了
