### ISSUE TITLE
🐛[BUG] 配置target无法兼容IE

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#7837]
### 🐛 bug 描述

配置target后，但IE11仍然打开页面报错

![image](https://user-images.githubusercontent.com/70048681/103163314-90857a80-4837-11eb-880f-76c903c3dd49.png)

### 📷 复现步骤

必现

### 🏞 期望结果

IE能正常使用

### 💻 复现代码

  targets: {
    ie: 10,
  },

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.2]
- umi 版本  ^3.2.21
- 浏览器环境 IE
- 开发环境 [e.g. mac OS]  window 10

**Comment by chenshuai2144** [comment]
target 也是有极限的，只能支持ie11，如果是开发环境的话 ie11 也很勉强，需要你把所有依赖理一遍，去掉任何不支持 ie11 的

**Comment by quicklearning123** [comment]
> target 也是有极限的，只能支持ie11，
> 
> 如果是开发环境的话 ie11 也很勉强，需要你把所有依赖理一遍，去掉任何不支持 ie11 的
> 
> > 对于现在还要支持 ie10 表示同情

@chenshuai2144  我想表达的意思是，能兼容到IE11也可以接受。但即使target设成10，IE11运行也会报错。

**Comment by chenshuai2144** [comment]
要去掉所有用了新版本的 featrue 的库。
我记得大部分库都不支持 ie11 了，你可以需要自研很多库

**Comment by xbpxxb** [comment]
config.ts 里的esbuild: {}注释掉试试
