### ISSUE TITLE
版本 如何跟着你们的版本升级

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#784]
以前用老版本做一个项目  现在想用1.0  有什么最快的方式迁移

**Comment by longzhaobi** [comment]
升级最主要的还是components下的把，如果你没改的话，就直接把最新的复制进去呗！
我之前升级1.0，最笨的方式就是把他们代码clone下来，用他们的做模板，把之前项目的代码复制进去，然后完善下common下的菜单就差不多了。

**Comment by ddcat1115** [comment]
业务代码不多的话，可以像楼上这么干。直接 merge master 会有很多冲突，会改的比较痛苦

**Comment by chenshuai2144** [comment]
有没有可能写个小工具将菜单转化一下。
类似于 https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types
