### ISSUE TITLE
🧐[问题]  如何修改菜单选中后的颜色？？？

### ISSUE THREAD

**Issue by ivsass** [ant-design/ant-design-pro#7841]
### 🧐 问题描述
  如何修改 菜单选中后的颜色？  选中默认是蓝色的  我想改为选中后为红色 ,  望大佬们不吝赐教！！！！

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103206675-5f8c6f00-4937-11eb-957f-c23f1343021f.png)

https://github.com/ant-design/ant-design-pro/blob/2f67dd2e49c821dd9df2885c654665807a85e79e/config/defaultSettings.ts

这里改一下吧。或者用 css 硬写。
