### ISSUE TITLE
🐛[BUG]antdpro5  umi.useModel中的useCallback获取不到state

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#7844]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![微信截图_20201228210418](https://user-images.githubusercontent.com/33310261/103216332-c66a5200-4950-11eb-9674-52dd154d8e4f.png)
del里面打印olist一直是初始值;而我使用 const { olist, add, del } = useModel('orderlist');的olist是有值的

**Comment by chenshuai2144** [comment]
useCallback 会闭包的，没有必要不要乱用 useCallback 和 useMemo 

收益不大不说还会出现各种奇怪的引用问题

**Comment by laolaolulu** [comment]
> useCallback会闭包的，没有必要不要乱用useCallback和useMemo
> 
> 收益不大不说将会出现各种奇怪的引用问题

antd pro5 我没找见哪儿有增删查改的例子,确实不知道应该如何写;  还是就在页面中useModel('orderlist') 然后直接删除?不需要在model中去写?

**Comment by chenshuai2144** [comment]
是 useCallBack 的问题

**Comment by laolaolulu** [comment]
> 是useCallBack的问题

那是需要解决的吗?还是得改不应该这样去写?

**Comment by chenshuai2144** [comment]
不要乱用useCallbck 和 useMemo

**Comment by laolaolulu** [comment]
> 不要乱用useCallbck 和 useMemo

那请问现在集合共享的例子在哪写呢?比如上面截图代码,我要从集合中删除一条数据应该在哪写呢?

**Comment by chenshuai2144** [comment]
不要用 useCallback 包就行了，你的写法没问题

**Comment by laolaolulu** [comment]
> 不要用 useCallback 包就行了，你的写法没问题

好的谢谢
