### ISSUE TITLE
🧐[问题] ProFormCaptcha 改成必须校验手机号了？

### ISSUE THREAD

**Issue by zhenglingfei** [ant-design/ant-design-pro#7845]
### 🧐 问题描述
ProFormCaptcha组件原来可以通过在onGetCaptcha中返回promise禁用并做其他表单的校验操作，这个Pr #1396改成必须校验通过才能走onGetCaptcha了么，现在下面的代码无法提前校验其他表单元素了，onClick似乎也不能触发，有什么其他比较灵活的方案么

### 💻 示例代码

onGetCaptcha={async (mobile) => {
  setValidCaptcha(true); // 这边是其他表单的校验开关
  await form.validateFields(['mobile', 'captcha']);
  return getSms({
    mobile,
    captcha: form.getFieldsValue(['captcha']).captcha,
  })
    .then(function () {
      setImgCaptcha(`/api/utils/captcha?time=${new Date().getTime()}`); // 成功则刷新验证码
      return Promise.resolve();
    })
    .catch(function (error) {
      return Promise.reject(error);
    });
}}

**Comment by zhenglingfei** [comment]
这个写法再v1.10.0是可用的，感觉这样更灵活些，可以在点击时做不同的校验操作

**Comment by chenshuai2144** [comment]
增加了一个phoneName 的props ，是因为原来写死了name 是个bug。

你可以配置一下 phoneName  或者不配置自己处理
