### ISSUE TITLE
V4 TS版本，如何在page目录下读取config里面的defaultSettings配置🧐[问题]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#7847]
目前想生成了一个layoutConfig.ts文件放在config里面，但是在page目录下无法获取config里面的文件
layoutConfig.ts文件主要是对全局layout的一个配置

**Comment by chenshuai2144** [comment]
直接 import 好了

**Comment by lishaoh** [comment]
@chenshuai2144 直接import路径不友好，通过在tsconfig.json里面设置paths，但是一直报错

![1609241108397](https://user-images.githubusercontent.com/20917295/103280602-cbd8a280-4a0b-11eb-8ab5-11901b3bbaaa.jpg)

**Comment by chenshuai2144** [comment]
你还需要在webpack中配置一下别名，现在编译都是 webpack 和 babel ，所以需要特殊配置没走 ts-loader
