### ISSUE TITLE
刚从master仓库拉取代码，运行报错

### ISSUE THREAD

**Issue by liushunqiu** [ant-design/ant-design-pro#785]
![_20180122103947](https://user-images.githubusercontent.com/13740807/35202970-b1d41f7a-ff60-11e7-8ff0-1081f1ffdcba.png)

**Comment by chenshuai2144** [comment]
看看你的mock  没有返回成功数据

**Comment by winer632** [comment]
@chenshuai2144 阿里云1cpu2G的云服务器能跑起来这个吗？是否必须用2cpu4G的配置？

**Comment by chenshuai2144** [comment]
没问题呀！！ 这个只是个前端 静态服务器就可以！前端吃的是用户的硬件  你们的后台才是真正吃硬件的
