### ISSUE TITLE
V4 TS版本直接在tsconfig.json里面设置paths，编译一直出错，需要在umi里面设置什么参数？🧐[问题]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#7851]
### 在config目录下新建layoutConfig文件，在page目录下引用，想用@config/*代替config路径，代码提示正确，编译一直报错
![1609241108397](https://user-images.githubusercontent.com/20917295/103280720-093d3000-4a0c-11eb-8940-799e0a6636e1.jpg)

**Comment by serenaxx** [comment]
同问

**Comment by chenshuai2144** [comment]
编译是webapck的 paths没用  在umi里要配置alias

**Comment by lishaoh** [comment]
> ### 在config目录下新建layoutConfig文件，在page目录下引用，想用@config/*代替config路径，代码提示正确，编译一直报错
> ![1609241108397](https://user-images.githubusercontent.com/20917295/103280720-093d3000-4a0c-11eb-8940-799e0a6636e1.jpg)
