### ISSUE TITLE
动态路由一直找不到页面🧐[问题]

### ISSUE THREAD

**Issue by shxinlei** [ant-design/ant-design-pro#7852]
### 💻 示例代码

 menuDataRender={() => [
        {
          path: '/welcome',
          name: 'welcome',
          icon: 'smile',
          // authority: "1",
          component: './Welcome',
        },
      ]}
### 🚑 其他信息

是我写的有问题吗

**Comment by shxinlei** [comment]
需要现在 config.js(javascript)  或者 config.ts(typescript) 配置路由, 然后在文件中动态请求路由

**Comment by chenshuai2144** [comment]
不支持这种功能
