### ISSUE TITLE
代码检查报错，程序能正常运行🧐[问题]

### ISSUE THREAD

**Issue by DreamParadise** [ant-design/ant-design-pro#7854]
### 🧐 问题描述
好多地方报`is declared but its value is never read.`，实际上这些变量是有使用的
![image](https://user-images.githubusercontent.com/3191003/103325879-c9685e00-4a88-11eb-987c-d05b3243c2cd.png)

还有像下面这种报错，一模一样的代码在这个窗口有错误信息，而且另一个窗口却显示正常的
![image](https://user-images.githubusercontent.com/3191003/103325914-f87ecf80-4a88-11eb-9c1e-c3b3ef4a514d.png)

请问这种情况是什么问题？

**Comment by chenshuai2144** [comment]
这个英语的意思是定义了但是没使用，能自动的 fix 的，执行以下

`npm run lint --fix`
