### ISSUE TITLE
🧐[问题] 为什么初始化时，国际化使用umi方法getLocale得到的是“zh”，而不是“zh-CN”?

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#7855]
### 🧐 问题描述

由于我的项目用到了国际化，在config里开启了浏览器语言自识别，但是项目初始化时，在app.ts的layout方法中调用getLocale方法时，得到的是“zh”。

### 💻 示例代码
config.js
`locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true, // 自动检测浏览器语言
    baseSeparator: '-',
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },`

app.jsx

`
import { getLocale } from 'umi';

export const layout = ({ initialState }) => {
  console.log(getLocale()) // "zh" 而不是“zh-CN”
  return {
    .....
    title: getLocale() === 'en-US' ?   'xxxxxx' : title,
  };
};`

**Comment by ISBN9527** [comment]
求大佬指点

**Comment by chenshuai2144** [comment]
是不是别的框架设置的？

![image](https://user-images.githubusercontent.com/8186664/103451275-ead18000-4cfc-11eb-8f96-5382c8be6e6e.png)


我们使用了 umi_locale 来存储了具体的key

**Comment by ISBN9527** [comment]
不是只有切换国际化的时候才会设置umi_locale的key值吗？

**Comment by chenshuai2144** [comment]
刚进来就会读取一下

**Comment by ISBN9527** [comment]
当我开启自动检测浏览器语言baseNavigator的时候，读取的就是“zh”，关闭后就正常。不知道为什么？

**Comment by Sean529** [comment]
请问这个问题解决了吗，我也遇到了，已经入项目获取到的就是 zh
