### ISSUE TITLE
白屏，chrome打开页面，切换标签到其他网站一段时间后回来白屏🐛[BUG]

### ISSUE THREAD

**Issue by starhu521** [ant-design/ant-design-pro#7856]
### 🐛 bug 描述

最新创建的项目（2020-12-30 14:30:00左右）：tyarn create umi选择v5，然后什么都不修改，只在table页面增加定时器：
 
![image](https://user-images.githubusercontent.com/23275495/103338594-d5b8df00-4ab9-11eb-94c8-e07b5708d023.png)

yarn start，mock数据，

然后chrome（版本 87.0.4280.88（正式版本） (x86_64)）访问页面，一切正常，切换到别的标签页，大约10min左右，
时间不等，复现概率能达到70%，在点击标签回到页面，页面白屏，大约过5-10s页面自动恢复正常（时间不等）。

之前不存在这个问题，我半个多月前创建的项目同样的操作没有问题（但现在已经删了），所以不清楚是哪个依赖出得问题。

#### 复现最快方式是打开十来个标签，打开页面后，切入其他标签，在其余10来个标签间正常来换切换30次左右，在切回页面必现。
简单测试发现是pro-table 2.16.4（该版本正常）之后出现该问题。

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本： 3.2.14
- 浏览器环境：chrome 版本 87.0.4280.88（正式版本） (x86_64)
- 开发环境：mac OS

### 🚑 其他信息
最新的依赖：
![image](https://user-images.githubusercontent.com/23275495/103338954-0b11fc80-4abb-11eb-865b-c5f3aae99f61.png)

![bugg](https://user-images.githubusercontent.com/23275495/103344475-aad68700-4ac9-11eb-80b8-7312fc31aa1e.gif)

**Comment by chenshuai2144** [comment]
看起来是触发了 浏览器的标签休眠了。浏览器重新触发了一次全部渲染

**Comment by starhu521** [comment]
> 看起来是触发了 浏览器的标签休眠了。浏览器重新触发了一次全部渲染

应该是的，简单排查了下应该是pro-table出的问题。chrome和safari浏览器行为表现不同，chrome全白，safari只有layout的content空白，也就是这个pro-table。

**Comment by chenshuai2144** [comment]
疑难杂症，我问问懂浏览器标准的同学

**Comment by fukantiankong** [comment]
同样的问题，请问是解决的？

**Comment by liwanyang** [comment]
> 疑难杂症，我问问懂浏览器标准的同学

我也遇到了同意的问题，感觉不是某个组件的问题，我的那个页面有ws推送消息，需要实时更新内容

**Comment by xiaohongYY** [comment]
怎么解决的？

**Comment by NTFSk** [comment]
如何解决的呢？
