### ISSUE TITLE
V4 TS版本，现在导出 interface 定义的类型 最后都通过umi引入？🧐[问题]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#7857]
### 自定义的export interface 类型，在别的文件引用时是通过umi引入？这样看着好奇怪

![1609319187940](https://user-images.githubusercontent.com/20917295/103341265-6a730b00-4ac1-11eb-946b-4cff262f4e5a.jpg)

**Comment by chenshuai2144** [comment]
umi 帮你自动计算了一下，你可以继续用默认的方式
