### ISSUE TITLE
请问ProTable结合Modal使用时,如何去掉ProTable自带的footer，只保留Modal配置的footer

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#7858]
### 🧐 问题描述

  定义一个Modal组件，并自定义footer,为“取消”和“确定”两个按钮，给该Modal组件传递props.children，结果同时也传过来一个footer，不清楚这个“重置”和“提交”这两个按钮究竟是哪里来的，可以去掉这两个按钮吗，我只需要我自己定义的两个按钮

### 
index.tsx
````
  const createFormColumns:ProColumns<createListItem>[] = [
    {
      title: '商品名称',
      dataIndex: 'districtUuid',    
      hideInTable:true,
      formItemProps: {
        rules: [
          {
            required: true,
            message: '请选择商品！',
          },
        ],
      },
      valueEnum:sitedata
    },
    
  ]

      <CreateForm onCancel={()=>handleCreateModalVisible(false)} modalVisible={createModalVisible} onSubmit={()=>handleCreateModalVisible(false)}> 
        <ProTable<createListItem,createListItem>
          onSubmit={(value) => createItem(value)}
          rowKey='key'
          type='form'
          columns={createFormColumns}
        />
        
      </CreateForm >
````
createForm.tsx
````
import React from "react"
import { Modal, Button } from "antd"

interface createFormProps {
    modalVisible: boolean;
    onCancel: () => void;
    onSubmit: (values: any) => void;
  }

const CreateForm:React.FC<createFormProps >=(props)=>{
    const {modalVisible,onCancel} = props
    console.log(props.children);
    console.log(props);
    return (
        <Modal
        destroyOnClose
        title="添加商品"
        visible={modalVisible}
        onCancel={() => onCancel()}
        footer=
        { 
            <>
            <Button type="primary" onClick={props.onCancel}>
            取消
            </Button>,
            <Button type="primary" onClick={props.onSubmit}>
            确定
            </Button>
            </>
        }
      >
        {props.children}
      </Modal>
    )
}
export default CreateForm
````

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/54265150/103340815-09970300-4ac0-11eb-93f9-ddc3012c48bb.png)

**Comment by chenshuai2144** [comment]
默认带的，设置` footer={null}` 就能取消掉

**Comment by HengCC** [comment]
我也想问 如何只保留modal的按钮. 还有里面的按钮能不能控制样式呢? 比如在右边展示

**Comment by chenshuai2144** [comment]
<html>
<body>
<h4 id="submitter" style="box-sizing: border-box; margin: 42px 0px 18px; color: rgb(69, 77, 100); font-weight: 500; line-height: 1.40625; font-size: 18px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">submitter</h4><p style="box-sizing: border-box; margin: 16px 0px; color: rgb(69, 77, 100); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">虽然我们希望不要对 submitter 进行修改，但在使用中修改是很常见的需求，ProForm 的各个组件都使用了同样的 API 来支持需求。</p>

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
onSubmit | 提交方法 | ()=>void | -
onReset | 重置方法 | ()=>void | -
searchConfig | 搜索的配置，一般用来配置文本 | {resetText,submitText} | -
submitButtonProps | 提交按钮的 props | ButtonProps | -
resetButtonProps | 重置按钮的 props | ButtonProps | -
render | 自定义操作的渲染 | false\|(props,dom:JSX[])=>ReactNode[] | -


</body>
</html>
