### ISSUE TITLE
由于roadhog的dev-tool bug官方一直未修复，请教下你们内部是如何进行调试的

### ISSUE THREAD

**Issue by fantaishao** [ant-design/ant-design-pro#786]
由于roadhog的dev-tool 配置的bug官方一直未修复，现在F12都是编译的代码，看的比较吃力，
https://github.com/sorrycc/roadhog/issues/554

请教下你们内部在用这个框架的时候是如何进行调试的？

**Comment by chenshuai2144** [comment]
去dva提吧。我都是强行看得

**Comment by remotesc2** [comment]
强行跟踪 es5 代码~
到是单步调试，不会乱跳了 :sweat_smile:

**Comment by lyingd** [comment]
我降级roadhog到1.3.1，这样就可以调试源码了

**Comment by heshunwq** [comment]
还一个问题是，请求老是返回304，导致无法获取到mock返回的数据。而实际上我直接从浏览器地址访问的时候，又是可以获取到数据的。

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/43，@pigcan 在看了。

**Comment by pythonsir** [comment]
这个bug解决了没有？痛苦死了。

**Comment by zenjava** [comment]
太痛苦了

**Comment by guojindai** [comment]
痛苦

**Comment by tianlinzx** [comment]
这个问题已经修复了，是不是可以关闭了，改一下依赖到最新的@2.3.0-beta.1就行。

**Comment by chenshuai2144** [comment]
正式版本发布。主分支升级会关掉的

**Comment by chenshuai2144** [comment]
fix in  https://github.com/ant-design/ant-design-pro/commit/2009bf3b0725fcc71ea64f64041a94bf5b720537
