### ISSUE TITLE
🧐[问题] 怎么实现点击父级菜单直接跳转路由

### ISSUE THREAD

**Issue by auyo18** [ant-design/ant-design-pro#7861]
### 🧐 问题描述

有子菜单的只能展开收起，只有点击没有子菜单的项才会跳转路由，怎么在展开菜单的时候也跳转到当前菜单的path，或者下级的某个路由呢

**Comment by chenshuai2144** [comment]
| subMenuItemRender | Customize the render method with submenu items | [`(itemProps: MenuDataItem) => ReactNode`](/components/layout/#menudataitem) | - |

你可以给里面整个 onClick
