### ISSUE TITLE
如何自定义网页title👑 [需求]

### ISSUE THREAD

**Issue by htank-wang** [ant-design/ant-design-pro#7862]
### 🥰 需求描述
我配置了个全局的title，比如“某某管理系统”
但是项目里有一个特殊页面是分享给外部用户使用，不希望看到“某某管理系统”字样。
通过document.title修改会出现title闪烁，由“某某管理系统”变为设置的标题

### 🧐 解决方案
这种如何调整?

**Comment by chenshuai2144** [comment]
在跳转之前就进行设置。 或者在 document.ejs 中设置 title

**Comment by htank-wang** [comment]
![image](https://user-images.githubusercontent.com/17918845/103499912-b5579e80-4e84-11eb-99a3-b524e845e387.png)
查了下，这里会将我设置的title给清空。这是什么原因？

**Comment by chenshuai2144** [comment]
设置 config.ts 中设置 title=false，这个是 umi 提供的功能，但是不好用

**Comment by htank-wang** [comment]
是的，对照了ant-design-pro的config.ts发现需要显式的指定title:false。感谢！
