### ISSUE TITLE
🐛[BUG]在mock文件夹里import src目录里的文件，开发时编译报错

### ISSUE THREAD

**Issue by serenaxx** [ant-design/ant-design-pro#7863]
### 🐛 我在mock里加了一个文件，文件里import src 里的一个配置文件，但发现编译通不过，解析不了内置的@/目录

![image](https://user-images.githubusercontent.com/7919149/103432926-ff414a00-4c22-11eb-9c6f-841f6dcfc7fe.png)

**Comment by chenshuai2144** [comment]
Mock是node 环境 不支持别名
