### ISSUE TITLE
各位大佬 萌新想要份 ant design pro v5的教程 求分享啊

### ISSUE THREAD

**Issue by c834482351** [ant-design/ant-design-pro#7864]
各位大佬 萌新想要份 ant design pro v5的教程 求分享啊

**Comment by shaohuatsou** [comment]
有多萌？

**Comment by c834482351** [comment]
> 有多萌？

只要有教程，要拍多萌有多萌，

**Comment by shaohuatsou** [comment]
https://www.yuque.com/u285157/kb
https://www.yuque.com/study365/ant
https://www.yuque.com/ant-design/course

**Comment by c834482351** [comment]
> https://www.yuque.com/u285157/kb
> https://www.yuque.com/study365/ant
> https://www.yuque.com/ant-design/course

谢谢谢谢 向大佬献出我的屁股

**Comment by qnamqj** [comment]
> https://www.yuque.com/u285157/kb https://www.yuque.com/study365/ant https://www.yuque.com/ant-design/course

给出 v5 版本的，这些根本都跑不通了，官网上的也有些滞后

**Comment by mrchenxxx** [comment]
> > https://www.yuque.com/u285157/kb
> > https://www.yuque.com/study365/ant
> > https://www.yuque.com/ant-design/course
> 
> 给出 v5 版本的，这些根本都跑不通了，官网上的也有些滞后

谢谢
