### ISSUE TITLE
🧐[问题] getInitialState 时 requestInterceptors 没有加入到 request 里

### ISSUE THREAD

**Issue by bow3nwang** [ant-design/ant-design-pro#7866]
### 🧐 问题描述

在 getInitialState 里请求用户数据，Token 没有被正确添加

### 💻 示例代码

只能手动添加 Token

const { data } = await umiRequest('/server/uac/account/current', {
  headers: { Authorization: `Bearer ${getAccessToken}` },
});

### 🚑 其他信息

能否更改一下初始化顺序？

**Comment by chenshuai2144** [comment]
getInitialState  在最前面，应该做增加 token 的功能。
你的token 是什么时候增加的？

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/request-cn#uniform-specification

看看这里，你需要一个拦截器了

**Comment by zhuguangyue** [comment]
> https://beta-pro.ant.design/docs/request-cn#uniform-specification
> 
> 看看这里，你需要一个拦截器了
@chenshuai2144 大佬请问这写有什么不对吗，为什么不生效的？
![image](https://user-images.githubusercontent.com/37643958/135372048-eafb4e80-73a5-424e-b885-b63db88c0af3.png)
