### ISSUE TITLE
🐛[BUG]react-dev-inspector在v5版本下不生效

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design-pro#7873]
### 🐛 bug 描述

react-dev-inspector在v5版本下不生效

- Ant Design Pro 版本: 5.x
- umi 版本: 3.x
- 浏览器环境: chome
- 开发环境: mac OS

**Comment by brlala** [comment]
在文件夹里添加一个model.ts即可

**Comment by chenshuai2144** [comment]
为什么会有这种神奇的问题？

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by drizzlesconsin** [comment]
@chenshuai2144 确实不会生效，issue 应该要重新打开。

新建 `yarn create umi myapp` 个 V5 版项目，`Ctrl ⌃+Shift ⇧+Command ⌘+C` 有生成对应属性。

![image](https://user-images.githubusercontent.com/69514654/112743563-f3b7b200-8fca-11eb-92ce-cf6c66e46bf3.png)

试过楼上的方法，以下地方都有添加 `model.ts`.
```
model.ts
src/model.ts
config/model.ts
```

**Comment by drizzlesconsin** [comment]
### 贴一下为什么不生效

> 源码只是加上插件而已，并没有调用。

https://github.com/ant-design/ant-design-pro/blob/master/config/config.dev.ts#L5-L14=

还需要参照 [react-dev-inspector 插件的使用文档第一步](https://github.com/zthxxx/react-dev-inspector#1-add-inspector-react-component=) 在 [app.tsx 这里](https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L89=) 修改。

```tsx
// app.tsx
import { Fragment } from 'react';
import { Inspector } from 'react-dev-inspector';

const isDev = process.env.NODE_ENV === 'development';
const loginPath = '/user/login';
```
```diff
+ const InspectorWrapper = isDev ? Inspector : Fragment;

+ <InspectorWrapper keys={['control', 'shift', 'command', 'c']} disableLaunchEditor={false}>
  {children}
+ </InspectorWrapper>
```

最后控制台验证
```js
window.__REACT_DEV_INSPECTOR_TOGGLE__()
```

**Comment by chenyu1990** [comment]
> ### 贴一下为什么不生效
> > 源码只是加上插件而已，并没有调用。
> 
> https://github.com/ant-design/ant-design-pro/blob/master/config/config.dev.ts#L5-L14=
> 
> 还需要参照 [react-dev-inspector 插件的使用文档第一步](https://github.com/zthxxx/react-dev-inspector#1-add-inspector-react-component=) 在 [app.tsx 这里](https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L89=) 修改。
> 
> // app.tsx
> import { Fragment } from 'react';
> import { Inspector } from 'react-dev-inspector';
> 
> const isDev = process.env.NODE_ENV === 'development';
> const loginPath = '/user/login';
> + const InspectorWrapper = isDev ? Inspector : Fragment;
> 
> + <InspectorWrapper keys={['control', 'shift', 'command', 'c']} disableLaunchEditor={false}>
>   {children}
> + </InspectorWrapper>
> 最后控制台验证
> 
> window.__REACT_DEV_INSPECTOR_TOGGLE__()

请教一下，我快捷键按了后，有效果了，但是鼠标点击，没有跳转到 webstorm的代码页面，我已经配置了环境变量，还是不行。
