### ISSUE TITLE
关于菜单权限配置不起作用的问题(请教)

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7874]
@chenshuai2144 麻烦能回复下，就因为简单才不知道原因了。菜单权限控制没起作用。
v5最新

![image](https://user-images.githubusercontent.com/17469220/103517938-ef32a000-4e98-11eb-9ff4-8b12a0323824.png)
![image](https://user-images.githubusercontent.com/17469220/103517990-05406080-4e99-11eb-934c-4e85a9ac57ec.png)

如上图所示，本来很简单的配置，我随便弄个权限，这两个菜单应该移除，可是视乎没起任何作用，请问有可能哪里出问题了，或者该怎么查，我对V5文档基本很熟悉了，也了解配置access.ts.

**Comment by WangJM001** [comment]
先看看access插件有没有运行

**Comment by WangJM001** [comment]
另外access这个菜单权限功能还有配合pro-layout插件使用才行

**Comment by WangJM001** [comment]
可以看下plugin-access、plugin-layout源码，再调试下

**Comment by my9988** [comment]
> 另外access这个菜单权限功能还有配合pro-layout插件使用才行

我就是在v5基础上改的，没有大的变化。看access插件有没有运行，麻烦说详细点，本人也是初次设计。最初的时候可以，功能差不多了，想加权限不行了

**Comment by WangJM001** [comment]
> > 另外access这个菜单权限功能还有配合pro-layout插件使用才行
> 
> 我就是在v5基础上改的，没有大的变化。看access插件有没有运行，麻烦说详细点，本人也是初次设计。最初的时候可以，功能差不多了，想加权限不行了
可以先看看access.ts里的方法有没有执行，你这个最好能提供复现的仓库

**Comment by my9988** [comment]
> > > 另外access这个菜单权限功能还有配合pro-layout插件使用才行
> > 
> > 
> > 我就是在v5基础上改的，没有大的变化。看access插件有没有运行，麻烦说详细点，本人也是初次设计。最初的时候可以，功能差不多了，想加权限不行了
> > 可以先看看access.ts里的方法有没有执行，你这个最好能提供复现的仓库

我这个系统后台django,配置运行起来有点麻烦，没有弄mock,因此不方便提供仓库。

![image](https://user-images.githubusercontent.com/17469220/103520197-c6aca500-4e9c-11eb-81a6-543b2db3f066.png)
![image](https://user-images.githubusercontent.com/17469220/103520239-dcba6580-4e9c-11eb-86d0-50600bc00aa6.png)
看样子是运行了，我是随便加了个权限想测试是否管用

![image](https://user-images.githubusercontent.com/17469220/103520198-c6aca500-4e9c-11eb-8250-eda0ae245f59.png)

**Comment by WangJM001** [comment]
你这个canAaa得配上啊
```
canAaa: false,
或者
canAaa: ()=>false
```

**Comment by WangJM001** [comment]
你可以看下```@umijs/plugin-access/lib/utils/runtimeUtil  ```的```traverseModifyRoutes```方法

**Comment by my9988** [comment]
> canAaa: false

大侠就是高，配置上就可以了。说实话这点和我理解不同，我认为没有的默认是false,你们是默认是true了

**Comment by beatlesD** [comment]
> 你可以看下`@umijs/plugin-access/lib/utils/runtimeUtil `的`traverseModifyRoutes`方法

![image](https://user-images.githubusercontent.com/68275945/133547983-e65fc707-db3f-4ea2-8e0f-92e9ca525ff5.png)

大佬你好，我在accessprovider文件里添加了一行
 props.routes.splice(0, props.routes.length, ...traverseModifyRoutes(props.routes, access));
权限可以正常跑起来，但是最新access这个插件里面并没有这个方法，现在我是要降版本么，还是怎么处理？

**Comment by chenshuai2144** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/8186664/134274796-3c5c36de-b2ad-495b-9a87-bf55f9160b06.png">


有 应该效果一样吧

**Comment by beatlesD** [comment]
> <img alt="image" width="364" src="https://user-images.githubusercontent.com/8186664/134274796-3c5c36de-b2ad-495b-9a87-bf55f9160b06.png">
> 
> 有 应该效果一样吧

尴尬的就是，这行代码没起作用，但是自己添加的那行代码可以做到左侧菜单的显示隐藏

**Comment by chenshuai2144** [comment]
你试试  [...] 这样搞一下，是不是因为触发重新更新

**Comment by yuanhuo** [comment]
> > 你可以看下`@umijs/plugin-access/lib/utils/runtimeUtil `的`traverseModifyRoutes`方法
> 
> ![image](https://user-images.githubusercontent.com/68275945/133547983-e65fc707-db3f-4ea2-8e0f-92e9ca525ff5.png)
> 
> 大佬你好，我在accessprovider文件里添加了一行 props.routes.splice(0, props.routes.length, ...traverseModifyRoutes(props.routes, access)); 权限可以正常跑起来，但是最新access这个插件里面并没有这个方法，现在我是要降版本么，还是怎么处理？

hi，能问下，我也碰到了，突然就不行，你这个最后怎么处理的？

**Comment by DerekHQ** [comment]
我也碰到该问题，一级菜单access控制有效， 一级放开，二级菜单限制， 二级就无效

**Comment by yuanhuo** [comment]
> 我也碰到该问题，一级菜单access控制有效， 一级放开，二级菜单限制， 二级就无效
你解决了么？
