### ISSUE TITLE
🧐  切换国际化时不想刷新页面，但是SelectLang是从umi里引入的，想setLocale(key, false)，没法设置啊？

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#7875]
### 🧐 问题描述

🧐  切换国际化时不想刷新页面

### 💻 示例代码

` <SelectLang className={styles.action} />`

SelectLang.tsx
`export const SelectLang: React.FC<SelectLangProps> = (props) => {`
  `const { globalIconClassName, postLocalesData, onItemClick, style, ...restProps } = props;`
`const changeLang = ({ key }: ClickParam): void => setLocale(key);`
`}`

这是写死的，也没法传值切换啊？

**Comment by chenyangyang123** [comment]
同问,怎么解决

**Comment by zhen9527** [comment]
import { SelectLang, setLocale } from 'umi';

 SelectLang className={styles.action} onItemClick={onSetLocale} 

const onSetLocale = (item: any) => {
	setLocale(item.key, false);
}

**Comment by chenshuai2144** [comment]
`<SelectLang reload={false}/>`

**Comment by hyl1374961656** [comment]
form的errorMessage设置这个后切换语言不会变化
