### ISSUE TITLE
🐛[BUG] SCRIPT1014: 无效字符 IE打开网站报错

### ISSUE THREAD

**Issue by skaier** [ant-design/ant-design-pro#7876]
ie打开会报错，无法进入网站，官方文档预览网站也是无法打开。

### 📷 复现步骤

打开官方演示网站https://preview.pro.ant.design在IE中打开就会有报错 进不了网站。官网下载安装，什么配置都不改也是这样子。
![image](https://user-images.githubusercontent.com/19259682/103596993-25742c00-4f3a-11eb-903d-78d1a9bf93d9.png)

### 🏞 期望
能在IE中进入网站

版本：
antd@^4.8.6
umi@^3.2.14

**Comment by chenshuai2144** [comment]
官网现在应该是 ie11 进不去了。你可以下载下来自己编译一下。

**Comment by LiuYnag** [comment]
遇到同样问题，IE11打开一直加载中，日志显示的一模一样

**Comment by luoheix** [comment]
去掉 config.ts 下的 esbuild 配置，esbuild 会把带有 '/n' 的字符串压缩成 ie 不兼容的模版字符串。

**Comment by Zhang-haohua** [comment]
umi2也遇到这问题，有大佬解决了吗

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF

推荐看这里，一步步排查

**Comment by Symous** [comment]
@luoheix 牛批，老哥。

**Comment by hanxzi** [comment]
@luoheix 牛批，老哥+++1
