### ISSUE TITLE
部署到多项目 nginx服务器   layout : 自定义 headerRender无效 🧐[问题]

### ISSUE THREAD

**Issue by mogoui** [ant-design/ant-design-pro#7877]
### 🧐 问题描述

config.ts 配置  
![image](https://user-images.githubusercontent.com/76653351/103615063-e0b1ba80-4f64-11eb-925b-35c14e479337.png)

本地 serve -s /build  一切正常
部署到 nginx 除了header样式 其他显示正常  ,    感觉是layout()没执行引起的

   `export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  console.log('test1');  // 这一句不执行
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { location } = history;
      console.log('history', location.pathname);  // 这一句不执行
    },

    headerRender: () => (
       <div>XX</div>   //这里配置无效  还是显示ant 默认的header
    ),
    menuHeaderRender: undefined,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings,
  };
};`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/76653351/103614591-e65ad080-4f63-11eb-80b6-bdcc10cbdf71.png)

![image](https://user-images.githubusercontent.com/76653351/103614903-93354d80-4f64-11eb-9087-c32c41e81734.png)

**Comment by chenshuai2144** [comment]
```
headerRender: () => (
   <div>XX</div>   //这里配置无效  还是显示ant 默认的header
),
menuHeaderRender: undefined,
...initialState?.settings,
```

你看看是不是 ...initialState?.settings 覆盖了它

**Comment by mogoui** [comment]
![image](https://user-images.githubusercontent.com/76653351/103621459-350e6780-4f70-11eb-84c1-f40612d3a206.png)
这里面 会影响?

**Comment by mogoui** [comment]
那请问我应该如何写呢

**Comment by chenshuai2144** [comment]
console 一下

**Comment by mogoui** [comment]
![image](https://user-images.githubusercontent.com/76653351/103624272-45c0dc80-4f74-11eb-8c55-b7812c54d587.png)

本地可以,只是服务器上面就有问题

**Comment by chenshuai2144** [comment]
debug下 可以用二分法慢慢来

**Comment by mogoui** [comment]
部署之后 App  layout() 不执行,无法调试
不知道这是不是一个bug

**Comment by chenshuai2144** [comment]
估计是依赖的问题吧。layout 一定会执行的，除非报错。

是不是线上什么接口挂了

**Comment by ClenLu** [comment]
大兄弟 解决了吗
