### ISSUE TITLE
👑 [需求] react-keep-alive 有没有办法在项目里面使用

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7878]
### 🥰 需求描述

      公司这边希望在浏览器返回上一个页面的时候不刷新页面;
      所以希望做一个页面存储；然后我看到了react-keep-alive；
      问一下pro里面有没有办法实现

**Comment by Asence** [comment]
只有在返回的时候不刷新页面

**Comment by chenshuai2144** [comment]
umi 有个插件，你直接看看那个插件。
不过不是官方支持的，使用起来可能需要自己动手

**Comment by Asence** [comment]
有案例吗？

**Comment by Asence** [comment]
我这边页面都用的useEffect去请求的接口 所以每次进入页面的时候都回去重新加载页面。
那么我原页面跳转的新页面然后返回到原页面的时候，页面就会走加载。导致了页面的重新加载；

**Comment by shaohuatsou** [comment]
React Activation

**Comment by Asence** [comment]
@shaohuatsou 谢啦

**Comment by chenshuai2144** [comment]
https://my.oschina.net/xiaohuoni/blog/4433778

看看这个插件，umi的核心维护者做的

**Comment by GStocking** [comment]
@Asence  hello 我也要在pro中使用react-keep-alive，请问你是怎么实现的？
`export default () => (
  <KeepAlive>
    <Log />
  </KeepAlive>
);`
单独每个页面设置 没有问题，但有些麻烦。
希望可以在layout中使用

**Comment by Asence** [comment]
> @Asence hello我也要在pro中使用react-keep-alive，请问你是怎么实现的？
> `export default () => ( <KeepAlive> <Log /> </KeepAlive> );`
> 单独每个页面设置没有问题，但有些麻烦。
> 希望可以在layout中使用

我改用了React Activation  你可以看看我觉得还不错

**Comment by foreverstars** [comment]
> @Asence hello 我也要在pro中使用react-keep-alive，请问你是怎么实现的？ `export default () => ( <KeepAlive> <Log /> </KeepAlive> );` 单独每个页面设置 没有问题，但有些麻烦。 希望可以在layout中使用

你的需求解决了吗

**Comment by Asence** [comment]
@foreverstars  解决了，不过没用react-keep-alive  用的是 react-activation    你如果需要做这个功能的话，建议看下react-activation   这个应该是可以帮助你解决的

**Comment by foreverstars** [comment]
我也是想用这个，我想在layout全局作用，不知道怎么弄

**Comment by foreverstars** [comment]
> > 我这边页面都用的useEffect去请求的接口 所以每次进入页面的时候都回去重新加载页面。 那么我原页面跳转的新页面然后返回到原页面的时候，页面就会走加载。导致了页面的重新加载；
> 
> 所以想问React Activation可以让function component 不重复执行useEffect吗

你这个解决了吗，我也遇到了这个问题
