### ISSUE TITLE
🧐[问题] pages 命名规范

### ISSUE THREAD

**Issue by Leskur** [ant-design/ant-design-pro#7879]
### 🧐 问题描述
为什么在 [all-blocks/src/pages](https://github.com/ant-design/ant-design-pro/tree/all-blocks/src/pages) 中 TableList 和 User 要使用大驼峰命名，而其他页面使用短横线命名呢？

### 💻 示例代码
无

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/33910980/103659606-9271db00-4fa7-11eb-8892-1caddfee58bc.png)
--
![image](https://user-images.githubusercontent.com/33910980/103659291-31e29e00-4fa7-11eb-9086-2fc74a188300.png)

**Comment by Leskur** [comment]
可以的话，能请您说明一下吗？

**Comment by chenshuai2144** [comment]
页面代码结构推荐


为了让项目代码组织更加规范，让开发能够更方便的定位到相关页面组件代码，我们定义了一套规范，该规范当前只作为推荐的指导，并非强制。


```

src
├── components
└── pages
    ├── Welcome        // 路由组件下不应该再包含其他路由组件，基于这个约定就能清楚的区分路由组件和非路由组件了
    |   ├── components // 对于复杂的页面可以再自己做更深层次的组织，但建议不要超过三层
    |   ├── Form.tsx
    |   ├── index.tsx  // 页面组件的代码
    |   └── index.less // 页面样式
    ├── Order          // 路由组件下不应该再包含其他路由组件，基于这个约定就能清楚的区分路由组件和非路由组件了
    |   ├── index.tsx
    |   └── index.less
    ├── user           // 一系列页面推荐通过小写的单一字母做 group 目录
    |   ├── components // group 下公用的组件集合
    |   ├── Login      // group 下的页面 Login
    |   ├── Register   // group 下的页面 Register
    |   └── util.ts    // 这里可以有一些共用方法之类，不做推荐和约束，看业务场景自行做组织
    └── *              // 其它页面组件代码
```
