### ISSUE TITLE
plus手机端适配bug

### ISSUE THREAD

**Issue by sitting2002** [ant-design/ant-design-pro#788]
如图所示，手机端（主要plus类）会出现未有全屏现象。
解决思路screen-xs加上height：100%
但代码实现还没摸透，请高手指教。谢谢

![image](https://user-images.githubusercontent.com/6848625/35203813-10e28caa-ff65-11e7-8766-19462fad51e0.png)

**Comment by chenshuai2144** [comment]
应该有个footer的。你删掉了？

**Comment by sitting2002** [comment]
footer还在啊 就是图中用红线遮住部分，只是改了名字。不方便暴露出来

**Comment by chenshuai2144** [comment]
我的mix，2 加上footer正好。

**Comment by chenshuai2144** [comment]
在线了 感觉flex布局发生了一点问提。。我修改一下

**Comment by chenshuai2144** [comment]
windows10 中  height:100%也不起作用。。。。

**Comment by unrealsmart** [comment]
win10 height:100% ！！！ 
表示使用 `flex` 布局的元素，在其里面的元素使用 `height` 根本没有用
建议尝试 `align-self: normal;`，也许管用，当然，只限于 `height: 100%`，非`height: 100%;`，可以`padding`

**Comment by chenshuai2144** [comment]
不起作用。。。

**Comment by unrealsmart** [comment]
尴尬

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/#/exception/403
都给100%就可以。。。

master就不行。。。好奇怪

**Comment by unrealsmart** [comment]
![image](https://user-images.githubusercontent.com/11688458/35213038-30b798f4-ff97-11e7-8ab5-379387be83f4.png)
这样布局是满的！额，什么鬼？！

**Comment by chenshuai2144** [comment]
修改为 后缀是plus的
![image](https://user-images.githubusercontent.com/8186664/35213123-810f08f0-ff97-11e7-837b-e72d05b3ce42.png)
最严重

**Comment by unrealsmart** [comment]
不行，有超出...

**Comment by unrealsmart** [comment]
应该在 `screen-xs` 上面 `height: 100%`，因为 `.ant-layout` 的 `height` 是根据 `screen-xs` 计算的
所以在 `ant-layout` 只能使用`vh`撑开

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35213310-26b6d9ae-ff98-11e7-8d5c-74e001a61e5f.png)

试试master 增加了也撑不开

**Comment by chenshuai2144** [comment]
用vh才能解决问题

**Comment by unrealsmart** [comment]
恩，的确，`screen-xs` 增加 `height: 100%`，同事其下的第一个`ant-layout`也需要添加`height:100%`才行。
还是用 `vh`  好，简单粗暴

**Comment by sitting2002** [comment]
感谢各位大神的鼎力相助，这个小问题总算解决了

**Comment by unrealsmart** [comment]
俺是连个 `git` 都不会的小白……

**Comment by chenshuai2144** [comment]
@sitting2002  感觉还是vh比较好一点。
min-height:100vh
