### ISSUE TITLE
🧐[问题] 不使用iconfont如何自定义菜单栏图标？如何将png图片用作菜单图标？

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#7881]
### 🧐 问题描述

请问react版本中，如何自定义菜单栏的icon呢，图标不是使用的iconfont，是UI设计的一组图标，png格式，请问这个该如何修改呢，router.config.js中应该如何处理icon呢？

**Comment by chenshuai2144** [comment]
router.config.js 直接配置 icon=cdn 的地址

**Comment by Youmyin** [comment]
> router.config.js 直接配置 icon=cdn 的地址

这个图片不是网上下载的，是公司UI设计的，然后直接给我的png图片

**Comment by chenshuai2144** [comment]
这就很尴尬了，我们现在不支持非 cdn 的图片。

你可以在 menuItemRender 里面自己自定义一下。

https://github.com/ant-design/ant-design-pro/blob/0301e41d1dd5da0c4abf90f46c351c054d28ff07/src/layouts/BasicLayout.tsx#L135-L143

**Comment by chenshuai2144** [comment]
建议 icon 不要搞得太花，中后台 太花了有点喧宾夺主

**Comment by Youmyin** [comment]
好吧，谢谢

**Comment by withwz** [comment]
> menuItemRender

一般只有组织节点才用icon

重写的就是这个
subMenuItemRender
