### ISSUE TITLE
🧐[问题]将开发的发布成产品... 直接访问 http://域名/user/login 报404

### ISSUE THREAD

**Issue by test7748** [ant-design/ant-design-pro#7883]
### 🧐 问题描述
直接 http://域名/index.html 会跳转到  http://域名/user/login
但是，直接访问  http://域名/user/login ，就是 404，这个是什么原因呢？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn

![image](https://user-images.githubusercontent.com/8186664/103740537-5d5e9a80-5032-11eb-9f7c-3fe047a529bc.png)

**Comment by shuhongwu** [comment]
> https://pro.ant.design/docs/deploy-cn
> 
> ![image](https://user-images.githubusercontent.com/8186664/103740537-5d5e9a80-5032-11eb-9f7c-3fe047a529bc.png)

这个并不难解决问题～～重新刷新还是会出现，版本 V4，Umi版本:3.3.7
