### ISSUE TITLE
🧐[问题] 找不到PageHeaderWrapper的相关API

### ISSUE THREAD

**Issue by fivefog** [ant-design/ant-design-pro#7885]
### 🧐 问题描述
问题虽简单，也很重要~  [捂脸]
在ProComponents找了一圈也没找到PageHeaderWrapper 的相关描述，搜素也木有，请问是在哪的？

```tsx
import { PageHeaderWrapper } from '@ant-design/pro-layout';
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/53244212/103752637-ea125400-5044-11eb-8bed-16ac2eaf3b04.png)

![image](https://user-images.githubusercontent.com/53244212/103752503-c0592d00-5044-11eb-935d-14b184b0875f.png)

**Comment by fivefog** [comment]
提问错地方了。。

**Comment by chenshuai2144** [comment]
没事，官网已经偷偷更新了
