### ISSUE TITLE
🐛[BUG] V5版本代码生成后删掉代码里的分号后，eslint没有报错

### ISSUE THREAD

**Issue by zhouxinyong** [ant-design/ant-design-pro#7887]
### 🐛 bug 描述

随便找一行代码，删掉分号，保存。 vscode不提示格式报错，且执行 `npm run lint-staged:js`也不报错。

### 📷 复现步骤
1. yarn create umi myapp 
2. select ant-design-pro
3. select Pro V5
4. 生成后 cd myapp
5. yarn
6. 重启vscode，随便找一行代码，删掉分号，保存。

### 🏞 期望结果
删掉分号后，vscode提示 缺少分号的报错。保存后，能够自动修复，加上分号。

>  vscode 已配置好eslint， 保存自动修复功能。

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本 3.X
- 浏览器环境
- 开发环境 [e.g. mac OS] mac OS

**Comment by chenshuai2144** [comment]
我们建议用 prettier 的自动 fix 功能，性能更好，速度更快还和当前的代码状态无关。

eslint 专心做预发层面的报错，性能也更好了。

一起来拥抱 prettier 吧

https://zhuanlan.zhihu.com/p/34287543

**Comment by chang-ke** [comment]
> 我们建议用 prettier 的自动 fix 功能，性能更好，速度更快还和当前的代码状态无关。
> 
> eslint 专心做预发层面的报错，性能也更好了。
> 
> 一起来拥抱 prettier 吧
> 
> https://zhuanlan.zhihu.com/p/34287543

这个回复好像文不对题吧，我现在也遇到了V5 eslint没有报错，保存后prettier没有生效的问题。想自己去配置eslint和prettier了

**Comment by chang-ke** [comment]
发现 @umijs/fabric下面的规则没有加 extend 'plugin:prettier/recommended' 导致 eslint + prettier 失效，暂时是自己加了解决问题

**Comment by Jiangyidan** [comment]
+1，有解决办法了吗
