### ISSUE TITLE
👑 [需求]如何在项目中使用 babel-plugin-import-glob 实现 glob pattern

### ISSUE THREAD

**Issue by felix-cao** [ant-design/ant-design-pro#7888]
### 🥰 需求描述

[babel-plugin-import-glob](https://www.npmjs.com/package/babel-plugin-import-glob)

- 安装 babel-plugin-import-glob
```bash
yarn add -D babel-plugin-import-glob
```
- 使用后路径解析无效
```
import * as Areas from './areas/**/planner-element.jsx';
```

![image](https://user-images.githubusercontent.com/8563874/103845953-1cb95c80-50d8-11eb-875d-e39405563064.png)

**Comment by chenshuai2144** [comment]
这个黑科技的插件是用来做啥的？

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是它已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but it has not responded for a long time. We will temporarily close it
