### ISSUE TITLE
IE11 下报错:Minified React error #31

### ISSUE THREAD

**Issue by rex11458** [ant-design/ant-design-pro#789]
我原本是用 dva 2.0.4创建的项目。之后dva升级到2.1.0，并将组件改为动态加载后，在IE11下报错：:Minified React error #31

**Comment by chenshuai2144** [comment]
https://reactjs.org/docs/error-decoder.html?invariant=37

低级错误

**Comment by jc920699638** [comment]
请问你解决这个问题了吗？
