### ISSUE TITLE
V5怎么配置多个paths 

### ISSUE THREAD

**Issue by wangjunhong** [ant-design/ant-design-pro#7891]
怎么配置自定义路径
tsconfig.json
paths 跟include都配置了
jsconfig.json
也配置paths 

这种改成数组也不行
"@/*": ["./src/*", "../ytCommon/*"],

[代码截图](http://img.yooticloud.cn/gov1609996544586)

**Comment by chenshuai2144** [comment]
https://www.typescriptlang.org/docs/handbook/module-resolution.html

语法是这样的，配置完了记得去配置 umi 的 alias

**Comment by wangjunhong** [comment]
https://blog.csdn.net/qq_27175079/article/details/112930771 问题解决了，方法如上。
