### ISSUE TITLE
🧐[问题]V5里改了语言locale-default，但是Pro Form还是显示中文

### ISSUE THREAD

**Issue by brlala** [ant-design/ant-design-pro#7892]
### 🧐 问题描述
我在config.ts里改了locale用 'en-US'作为主要语言，但是Pro Form一直展示中文的PlaceHolder。

### 💻 示例代码
config.ts
```
export default defineConfig({
  locale: {
    // default zh-CN
    default: 'en-US',
    antd: false,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/8999633/103857593-c1946380-50f1-11eb-97c9-fdd6e92a41cb.png)
Label已经自动切换成英文了，但是输入框那里还是显示着中文。

如果手动切换成英文多一次，就会显示对的结果
![image](https://user-images.githubusercontent.com/8999633/103858069-a7a75080-50f2-11eb-841a-1a9e6bf3c87e.png)

**Comment by brlala** [comment]
求问有解决方案吗？我尝试了V4，也出现了同样的问题

**Comment by chenshuai2144** [comment]
没有出发了组件更新！刷新下页面就好了

**Comment by brlala** [comment]
刷新了也没用，这貌似是umi设置语言前后的秩序问题(moment-locale也有个小bug)。谢谢你啦

**Comment by peterleng** [comment]
![image](https://user-images.githubusercontent.com/7566681/172760483-96cbf087-7308-410a-abc9-1cbd36711936.png)
这里设置为 false 就好了
