### ISSUE TITLE
responseinterceptors里打印headers为空🧐[问题]

### ISSUE THREAD

**Issue by wildor1** [ant-design/ant-design-pro#7895]
### 🧐 问题描述
请问为什么我在responseInterceptors里打印response，但是headers是{},没有任何数据

### 💻 示例代码
const responseinterceptors=(response, options) => {
  console.log(response)
  const token = response.headers.get('authorization')
  if (token) {
    localStorage.setItem('token', token);
  }
  return response;
}

export const request: RequestConfig = {
  errorHandler,
  responseInterceptors: [responseinterceptors],
};

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/request-cn

看这个文档，你应该试试拦截器
