### ISSUE TITLE
🧐[问题]请问在登录时，为什么会报告405错误，而无法登录？

### ISSUE THREAD

**Issue by njypx** [ant-design/ant-design-pro#7897]
### 🧐 问题描述

安装pro之后，在浏览器中显示登录框，输入\ant-design-pro-master\mock\user.ts 文件中提示的用户名admin和密码ant.design
为什么会报405错误：
请求错误 405: http://localhost:8000/api/login/account
Method Not Allowed

**Comment by njypx** [comment]
再请问一下？如何运行起mock?

**Comment by chenshuai2144** [comment]
默认就会运行 mock的。

**Comment by njypx** [comment]
需要看到全部的内容，需要运行哪一个？
scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run site && npm run gh-pages",
    "dev": "npm run start:dev",
    "docker-hub:build": "docker build  -f Dockerfile.hub -t  ant-design-pro ./",
    "docker-prod:build": "docker-compose -f ./docker/docker-compose.yml build",
    "docker-prod:dev": "docker-compose -f ./docker/docker-compose.yml up",
    "docker:build": "docker-compose -f ./docker/docker-compose.dev.yml build",
    "docker:dev": "docker-compose -f ./docker/docker-compose.dev.yml up",
    "docker:push": "npm run docker-hub:build && npm run docker:tag && docker push antdesign/ant-design-pro",
    "docker:tag": "docker tag ant-design-pro antdesign/ant-design-pro",
    "fetch:blocks": "pro fetch-blocks && npm run prettier",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier --check \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "site": "npm run fetch:blocks && npm run build",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc --noEmit"
  },

**Comment by njypx** [comment]
请问一下，哪一个是默认运行的？

**Comment by njypx** [comment]
做一下自我解答：
在使用时，下载的内容，并不是网站上预览的全部内容，只是部分内容，要获得完整的内容，还需要单独下载。初次使用从"start": "cross-env UMI_ENV=dev umi dev"处运行。

**Comment by chenshuai2144** [comment]
`"start": "cross-env UMI_ENV=dev umi dev",`

**Comment by njypx** [comment]
建议以后，增加使用指南及操作步骤，对于熟悉的人，可以略过，但是对于初次使用的人，却会有许多帮助。

**Comment by MINGLIANG98** [comment]
麻了

**Comment by wy2022** [comment]
搞这么多，麻了,官网也没说明

**Comment by wy2022** [comment]
放弃了，start": "cross-env UMI_ENV=dev umi dev",   还是提示帐号密码错误，并没有网络请求.

**Comment by wyc6990906** [comment]
npm run start 可以

**Comment by Lsnsh** [comment]
> npm run start 可以

我也遇到了相同的问题，使用 `npm run dev` 会报 `405 (Method Not Allowed)`，改用 `npm run start` 能正常登录。

---

观察对比 `dev`、`start`、`start:dev` 

```json
"scripts": {
  "dev": "npm run start:dev",
  "start": "cross-env UMI_ENV=dev umi dev",
  "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
}
```

发现 `dev`/`start:dev` 相对于 `start` 多了 `REACT_APP_ENV=dev MOCK=none` 这一段，而其中的 `MOCK=none` 猜测和是否开启 mock 数据有关。

在 [ant-design-pro](https://pro.ant.design/zh-CN/docs/overview) 文档搜索 MOCK 关键词，找到了[配置相关的说明](https://pro.ant.design/zh-CN/docs/faq/#%E5%A6%82%E4%BD%95%E4%BB%A3%E7%90%86%E5%88%B0%E5%90%8E%E7%AB%AF%E6%9C%8D%E5%8A%A1%E5%99%A8)：

![image](https://user-images.githubusercontent.com/26019513/160323567-5feabce1-472a-4542-84e8-d73320c17dcd.png)

**Comment by jokereven** [comment]
解决了2333.

**Comment by bincute** [comment]
Thank you, this post is very helpful.
