### ISSUE TITLE
树型控件如何修改hover颜色？

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#7898]
### 🧐 问题描述

在选中前，当鼠标移动至树的节点上时，如何修改hover的颜色？

如图一所示，当鼠标移动至节点上时，节点的背景色变成浅灰色了，请问这个颜色如何更改呢？F12检查元素找不到修改hover的这个类
![image](https://user-images.githubusercontent.com/54265150/103874462-23fa5d80-510c-11eb-8322-f3aa4f1e4471.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103966875-b564e080-519b-11eb-9766-d8724e596ab5.png)

这样就就能看见了，都是 css 实现的，不行就覆盖css

**Comment by Youmyin** [comment]
好的，谢谢！
