### ISSUE TITLE
🧐[问题]菜单无法自动展开的问题

### ISSUE THREAD

**Issue by lspeer** [ant-design/ant-design-pro#7899]
### 🧐 问题描述

使用 https://beta-pro.ant.design/docs/advanced-menu-cn
从服务端请求菜单，目前我想跳到第二级菜单
预期：一级菜单会展开 
目前:  一级菜单不会展开
### 💻 示例代码
获取菜单后
history.push('/home/authority-management/web');

![image](https://user-images.githubusercontent.com/25837435/103881767-dc78cf00-5115-11eb-85d8-1df06c1d2e75.png)

### 🚑 其他信息
Pro V5

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/103967068-273d2a00-519c-11eb-98e6-4b197a145671.png)

这不是都打平成了一级菜单？

**Comment by lspeer** [comment]
flatMenu 不是意味着把/home/authority-management移到一级菜单，那么相应的/home/authority-management/web就是二级菜单，我现在选中/home/authority-management/web后刷新，/home/authority-management不展开的

**Comment by chenshuai2144** [comment]
你要通 routes 来定义，不要玩魔法
