### ISSUE TITLE
列表页> 搜索列表> 搜索文章(文章)> 文章    owner 下拉框, 如果是空的, 会出现显示异常的bug

### ISSUE THREAD

**Issue by jaythc** [ant-design/ant-design-pro#7903]
4.5.0 版本 
页面路径如下: 
列表页> 搜索列表> 搜索文章(文章)> 文章 

owner 下拉框, 如果是空的, 会出现如下的bug, 显示异常,  解决方法是什么? 
![image](https://user-images.githubusercontent.com/29886008/103985015-25d32800-51c3-11eb-8dc7-1c1b61aa0999.png)

**Comment by chenshuai2144** [comment]
设置一个最小的宽度

**Comment by jaythc** [comment]
style={{ width: 170 }}
