### ISSUE TITLE
打包加载慢

### ISSUE THREAD

**Issue by gaolongge** [ant-design/ant-design-pro#7904]
采用这个antdpro后，部署测试环境，首屏加载很慢。加载chunk-vendors.js需要7s。但是你的demo很快，请问是原因（基于antdpro开发，没有新增第三方插件）

**Comment by chenshuai2144** [comment]
7s 有点过分了是不是你的 nginx 没配置过

**Comment by gaolongge** [comment]
问题排查出来，是宽带问题，裂开。
