### ISSUE TITLE
🧐[问题] 使用pro V4 javascript  最新版 4.5.0  eslint 报错

### ISSUE THREAD

**Issue by kiwikaki** [ant-design/ant-design-pro#7906]
### 🧐 问题描述
下载最新的pro(v4 javascript) ，在vscode中发现eslint会对react等进行报错警告，是@umijs/fabric问题吗？
### 💻 示例代码
![image](https://user-images.githubusercontent.com/5789944/104078203-cffc8f80-5257-11eb-8a76-b47451c7561a.png)
![image](https://user-images.githubusercontent.com/5789944/104078212-e4408c80-5257-11eb-8d2f-d8b0535261df.png)

**Comment by chenshuai2144** [comment]
升级一下依赖好了，我记得是typescipt 版本太低导致的

**Comment by kiwikaki** [comment]
> 升级一下依赖好了，我记得是typescipt 版本太低导致的
我加入babel-eslint 才解决的，是继承@umijs/fabric没起作用吗？
`module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: { jsx: true, generators: true, experimentalObjectRestSpread: true },
    ecmaVersion: 2020,
    sourceType: 'module',
  },
  plugins: ['react'],
  rules: {
    'react/jsx-uses-react': 2,
    'no-unused-vars': 'off',
  },
  globals: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
    page: true,
    REACT_APP_ENV: true,
  },
};`

**Comment by chenshuai2144** [comment]
fabric 没用 babel-eslint ，用的是默认的解析器

**Comment by YoursOwen** [comment]
我也碰到这个问题了，有更好的解决方案吗？

**Comment by YoursOwen** [comment]
> > 升级一下依赖好了，我记得是typescipt 版本太低导致的
> 
> 我加入babel-eslint 才解决的，是继承@umijs/fabric没起作用吗？
> 
> ```
> module.exports = {
>   env: {
>     browser: true,
>     commonjs: true,
>     es6: true,
>     node: true,
>   },
>   extends: [require.resolve('@umijs/fabric/dist/eslint')],
>   parser: 'babel-eslint',
>   parserOptions: {
>     ecmaFeatures: { jsx: true, generators: true, experimentalObjectRestSpread: true },
>     ecmaVersion: 2020,
>     sourceType: 'module',
>   },
>   plugins: ['react'],
>   rules: {
>     'react/jsx-uses-react': 2,
>     'no-unused-vars': 'off',
>   },
>   globals: {
>     ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
>     page: true,
>     REACT_APP_ENV: true,
>   },
> };
> ```

这个不是相当于把项目的 un-used-vars 关掉了么？

**Comment by YoursOwen** [comment]
> fabric 没用 babel-eslint ，用的是默认的解析器

请问有更好的解决方案吗？

**Comment by chenshuai2144** [comment]
我来想想办法

**Comment by zhaokera** [comment]
有解决办法了吗

**Comment by forzalianjunting** [comment]
> 我来想想办法

请问有解决办法了吗？

**Comment by chenshuai2144** [comment]
今天解决
