### ISSUE TITLE
悬浮窗

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#7907]
### 🥰 需求描述

请问能否给Ant design添加一个悬浮框的组件，类似移动端那样可以点击拖拽，在不点击的时候可以收缩成一个图标之类的。

该悬浮框类似卡片的样式，里面可以放入其他组件

**Comment by chenshuai2144** [comment]
你是内部用户吗？ 可以试试 techui 里面做了一个，外部用户的话，开源有好多的
