### ISSUE TITLE
🐛原来远程获取菜单里，内藏乾坤呐！

### ISSUE THREAD

**Issue by hot588** [ant-design/ant-design-pro#7909]
### 🐛 bug 描述

MenuDataItem

export declare type MenuDataItem = {
    /**
     * @name 子菜单
     */
    children?: MenuDataItem[];
    /**
     * @name 在菜单中隐藏子节点
     */
    hideChildrenInMenu?: boolean;
    /**
     * @name 在菜单中隐藏自己和子节点
     */
    hideInMenu?: boolean;
    /**
     * @name 菜单的icon
     */
    icon?: React.ReactNode;
    /**
     * @name 自定义菜单的国际化 key
     */
    locale?: string | false;
    /**
     * @name 菜单的名字
     */
    name?: string;
    /**
     * @name 用于标定选中的值，默认是 path
     */
    key?: string;
    /**
     * @name disable 菜单选项
     */
    disabled?: boolean;
    /**
     * @name 路径
     */
    path?: string;
    /**
     * @name 自定义父节点
     * @description 当此节点被选中的时候也会选中 parentKeys 的节点
     */
    parentKeys?: string[];
    /**
     * @name 隐藏自己，并且将子节点提升到与自己平级
     */
    flatMenu?: boolean;
    [key: string]: any;
};

**在后台自定义菜单的时候，一定要看这个，我再文档里怎么没有看到这块呢！

再源码里有明确的解释！**

**Comment by shaohuatsou** [comment]
我都看到了。

**Comment by chenshuai2144** [comment]
我竟然没有看懂，求解

**Comment by shaohuatsou** [comment]
https://procomponents.ant.design/components/layout/#%E8%87%AA%E5%AE%9A%E4%B9%89-menu-%E7%9A%84%E5%86%85%E5%AE%B9
这不是写的有吗？

**Comment by johnstevin** [comment]
https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu

V4最新版，远程获取服务器菜单，按照官方的例子做。然后第一次获取到数据并更新了state后，视图没渲染，不显示菜单。第二次就好了。

这是什么问题呢？最新版有bug？？

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

看这个文档，可以用 menu.loading 来触发加载
