### ISSUE TITLE
npm install到一半,自动killed掉了??

### ISSUE THREAD

**Issue by ymvkujn** [ant-design/ant-design-pro#791]

**Comment by chenshuai2144** [comment]
估计是断网了。 用cnpm把。

**Comment by pkaq** [comment]
yarn靠谱

**Comment by ymvkujn** [comment]
npm执行到一半，就出现以下信息，然后就被杀掉了！环境: CentOS Linux release 7.3.1611 (Core)
Killed         ....] - extract:xhr2: sill doParallel extract 2200 .  执行到一半,
