### ISSUE TITLE
在config或setting中导入svg图标🧐[问题]

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#7911]
我在config或setting中导入svg图标，如果使用别名 ‘@/assets/logo.svg’ 会提示无法找到文件，如果使用 '../src/assets/logo.svg' 会提示 Unexpected token '<'。

路径别名
![image](https://user-images.githubusercontent.com/50793943/104084810-875bcb00-5285-11eb-9401-8bdf7039c3f5.png)

相对路径
![image](https://user-images.githubusercontent.com/50793943/104084817-96db1400-5285-11eb-88c7-959a40d494bc.png)

**Comment by shaohuatsou** [comment]
放到运行时配置就可以，为啥呢？

**Comment by chenshuai2144** [comment]
因为node 不这次 svg，是webpack 帮忙支持的，

所以你要把 import svg 放到 src目录下面执行
