### ISSUE TITLE
现在最新版本的 是不是打包  没有代码分离了？

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#792]
现在最新版本的 是不是打包  没有代码分离了？ 
js是一个文件了

**Comment by chenshuai2144** [comment]
[代码分割和动态加载](https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD)

**Comment by wunayou** [comment]
那现在 我的为什么 只打成一个包呢？

**Comment by afc163** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/507615/35254805-d391dbae-0026-11e8-9ba7-804ab0b9038a.png">
