### ISSUE TITLE
如何抓到通过代理请求的返回数据，报错后，errorHandler里看不到代理返回的错误

### ISSUE THREAD

**Issue by httol** [ant-design/ant-design-pro#7931]
如何抓到通过代理请求的错误，报错后，errorHandler里看不到代理返回的错误
![image](https://user-images.githubusercontent.com/4971746/104128020-32f93e00-53a0-11eb-9122-7b6546261d56.png)

![image](https://user-images.githubusercontent.com/4971746/104126432-77cca700-5397-11eb-8f2d-070f19c4442c.png)

_Originally posted by @httol in https://github.com/ant-design/ant-design-pro/issues/2779#issuecomment-757490294_

**Comment by chenshuai2144** [comment]
这个报错里只能看到真正的报错，不能看到错误的业务数据。


真正的报错 ===  status !== 200

业务报错=== 数据为空或 success=false

**Comment by httol** [comment]
Thanks. understand !
