### ISSUE TITLE
antd pro v5 侧边栏

### ISSUE THREAD

**Issue by DevilMayDead** [ant-design/ant-design-pro#7932]
请问使用ProLayout单独封装出来的app.tsx 能否自定义侧边栏
目前项目需要自己定义collapsedIcon

**Comment by DevilMayDead** [comment]
以及如果自己渲染collapsedIcon，因为是配置文件，无法使用useState控制collapsed的值，请问如何解决

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed

这里有个demo，Layout 是支持受控模式的

**Comment by DevilMayDead** [comment]
您好，但是antd pro v5里是否不支持自定义layout?

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/my-layout-cn

看这个文档

**Comment by DevilMayDead** [comment]
万分感谢
