### ISSUE TITLE
👑 [需求] 请问pro自带Authorized等组件实现的权限如何解决直接url访问的安全问题？

### ISSUE THREAD

**Issue by egene-huang** [ant-design/ant-design-pro#7933]
### 🥰 需求描述
使用自带的组件在菜单初始化时，过滤了无权限的菜单项， 但是如果知道访问url则直接通过url访问依然渲染出来了，我仔细梳理了一遍原理， 发现是因为在BasicLayout.tsx组件中这里混淆了不存在和无权限的url

> const authorized = useMemo(
    () => getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || { authority: undefined,},
    [location.pathname],
  );

然后在 `checkPermissions.tsx`组件中， authority 非真值 直接返回了权限校验通过的组件， 这里我不知道该如何解决这个问题， 我有了解umi插件  umijs/plugin-access  但是这样有点太麻烦了  需要将页面组件再包一层 然后 在菜单配置，但是菜单智能配置一个权限， 自带权限组件可以配置数组

麻烦帮忙给看一下， 非常感谢!

**Comment by wsgyp-dashuaige** [comment]
我是在checkPermissions.tsx
` if (!authority) {
    return Exception;
  } `
然后在BasicLayout里useMemo顺便判断menuDataRef.current是否为空

**Comment by YoursOwen** [comment]
直接在url地址栏输入时， authorized 的结果为 [ undifined ]

**Comment by Enzozzzz** [comment]
获取route中的authority与实际当前页面children匹配不上,应该getRouteAuthority方法出的bug, 刚刚解决这个问题, 需要重写getRouteAuthority, 代码如下:
export const getRouteAuthority = (router=[],pathname) => {
  for(let i=0; i < router.length; i++){
    console.log('xxxx', i, router[i])
    if(router[i].path === pathname){
      return router[i].authority
    } else {
      if (!router[i].children) {continue}
      return getRouteAuthority(router[i].children, pathname)
    }
  }
  return undefined;
}

**Comment by dealdot** [comment]
大佬们都是怎么解决这个问题的，听说4.2版本修复了这个bug ?

**Comment by 2010hexi** [comment]
> 大佬们都是怎么解决这个问题的，听说4.2版本修复了这个bug ?

并没有修复， 4.5 还是这样 url 直通车

**Comment by ItsJackWang** [comment]
我也发现了这个问题。问题的关键是getMatchMenu的第二个参数menuDataRef.current返回的是已经经过权限控制过滤后的menu。我把这里改成了拿过滤前的menu，具体如下：
1）从props里拿routes
`const {
    route = {
      routes: [],
    },
  } = props;
  const { routes = [] } = route`
2）调用getMenuData(routes)拿menu
3）getMatchMenu第二个参数换成menu.menuData

这样，你用user登录，再在地址栏访问/admin页面就是403了。
