### ISSUE TITLE
V5 表格columns有没有配置文档

### ISSUE THREAD

**Issue by wangjunhong** [ant-design/ant-design-pro#7935]
比如我要修改输入框placeholder里的文字，但是没有地方去改，columns里没有这个字段，直接修改没用。
于是我就得去想别的办法，方法如下：
`
 renderFormItem: () => {
        return <Input allowClear placeholder="请输入名称" />;
      },
`

虽然能做出来这个效果，但是感觉是杀鸡用牛刀，是不是有更好的方法，**我心里是没有底的。**

就是想问问有没有columns相关的配置文档（或者有地址我还不知道），没有文档加持初学者感到很迷茫，怕自己的方法**不是最佳实践**。

**还有一个问题是筛选条件设置多选是加个参数就能搞定，还是需要自定义组件。**

**Comment by c834482351** [comment]
https://procomponents.ant.design/components/table/#columns-%E5%88%97%E5%AE%9A%E4%B9%89
看看这个是否能帮助你

**Comment by c834482351** [comment]
> 比如我要修改输入框placeholder里的文字，但是没有地方去改，columns里没有这个字段，直接修改没用。
> 于是我就得去想别的办法，方法如下：
> `renderFormItem: () => { return <Input allowClear placeholder="请输入名称" />; },`
> 
> 虽然能做出来这个效果，但是感觉是杀鸡用牛刀，是不是有更好的方法，**我心里是没有底的。**
> 
> 就是想问问有没有columns相关的配置文档（或者有地址我还不知道），没有文档加持初学者感到很迷茫，怕自己的方法**不是最佳实践**。
> 
> **还有一个问题是筛选条件设置多选是加个参数就能搞定，还是需要自定义组件。**

https://procomponents.ant.design/components/table/#columns-%E5%88%97%E5%AE%9A%E4%B9%89

**Comment by wangjunhong** [comment]
> https://procomponents.ant.design/components/table/#columns-%E5%88%97%E5%AE%9A%E4%B9%89
> 看看这个是否能帮助你
是的  就是这个 谢谢了
