### ISSUE TITLE
import 和 export default  冲突  Cannot assign to read only property 'avatarFullImage' of object '#<Object>' 

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#7936]
![image](https://user-images.githubusercontent.com/45235142/104190324-e6bd0500-5456-11eb-84cb-1f3ae77db94d.png)

我这边之前是用笔记本开发的 然后换了一个电脑  就吧报of object '#<Object>' 

 Cannot assign to read only property 'avatarFullImage' of object '#<Object>' 

![image](https://user-images.githubusercontent.com/45235142/104190524-34397200-5457-11eb-9506-312ee57ade3d.png)

**Comment by Asence** [comment]
有点急 请问有到底是哪出错了

**Comment by Asence** [comment]
@chenshuai2144  大佬  帮忙看看  快急死了  明天就要上线了

**Comment by chenshuai2144** [comment]
访问私有变量，是修改了 windows 的变量吧，去掉就好了

**Comment by Asence** [comment]
已经找到问题了  当我吧config里面的 config.ts  里面的 dva  immer设置为true 的时候就会报这个错 关掉就好了
