### ISSUE TITLE
🐛[BUG]defaultSettings 里面导入本地图片 报错

### ISSUE THREAD

**Issue by antony-hai** [ant-design/ant-design-pro#7937]
### 🐛 bug 描述
用本地图片换一个logo  
import img from '.......'
console.log(img)

会报错 
Invalid or unexpected token
D:\coding\test\public\home_bg.png:1
�PNG

图片base64后  好像识别出了问题

### 🏞 期望结果
希望能正常引入

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by antony-hai** [comment]
umi 版本3.3.4

**Comment by huntdream** [comment]
defaultSettings 这里应该是不走webpack的吧

**Comment by chenshuai2144** [comment]
只有 src 里面的东西才走 webpack。

**Comment by chenyangyang123** [comment]
![image](https://user-images.githubusercontent.com/71480643/105166806-d261c200-5b52-11eb-8a53-0f812af26744.png)

如图设置,

**Comment by chenyangyang123** [comment]
`
app.tsx:

export const layout: RunTimeLayoutConfig = ({ initialState }) => ({
  rightContentRender: () => <RightContent />,
  disableContentMargin: false,
  logo: `<img alt="logo" src="/logo.svg" />`,
  menuHeaderRender: undefined,
  // 自定义 403 页面
  // unAccessible: <div>unAccessible</div>,
  ...initialState?.settings
});
`
