### ISSUE TITLE
🧐[问题]国际化报错： Error: setLocale lang format error

### ISSUE THREAD

**Issue by FreeCodersix** [ant-design/ant-design-pro#7940]
### 🧐 问题描述

我不知道修改了什么代码，导致国际化模块失效，现在我点击语言切换就会报这个错误。而且，我没有办法获得帮助
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33892855/104289362-fe969680-54f3-11eb-858f-387984adcdb6.png)
另外，这个下拉框的排版也突然变得很诡异
![image](https://user-images.githubusercontent.com/33892855/104289411-1110d000-54f4-11eb-86fe-ddd5198d6d01.png)
急需帮助

**Comment by FreeCodersix** [comment]
而且，在我的印象中，我并没有修改和这个模块有关的代码

**Comment by FreeCodersix** [comment]
@chenshuai2144

**Comment by FreeCodersix** [comment]
我在src/.umi/plugin-locale/localeExports.ts里打印了一下lang，发现传过来的是item_0
![Uploading image.png…]()

**Comment by FreeCodersix** [comment]
我在src/.umi/plugin-locale/localeExports.ts里打印了一下lang，发现传过来的是item_0
![image](https://user-images.githubusercontent.com/33892855/104290588-7e713080-54f5-11eb-8623-25e40c09f5b4.png)

**Comment by FreeCodersix** [comment]
![image](https://user-images.githubusercontent.com/33892855/104290662-95178780-54f5-11eb-8710-a1b5ede012af.png)

**Comment by FreeCodersix** [comment]
@chenshuai2144 我大概找到了问题，但是我找不到解决的方法。

**Comment by daiwenyang** [comment]
<Menu.Item key={localeObj.key} style={menuItemStyle}>
            <span role="img" aria-label={localeObj?.label || "en-US"}>
              {localeObj?.icon || "🌐"}
            </span>
            {localeObj?.label || "en-US"}
          </Menu.Item>

遇到同样的问题，原因在key={localeObj.key}这里

**Comment by FreeCodersix** [comment]
> <Menu.Item key={localeObj.key} style={menuItemStyle}>
> <span role="img" aria-label={localeObj?.label || "en-US"}>
> {localeObj?.icon || "🌐"}
> 
> {localeObj?.label || "en-US"}
> </Menu.Item>
> 
> 遇到同样的问题，原因在key={localeObj.key}这里

是的，我也找到了问题，修改成key={localeObj.lang}就OK，但是每次重启就会自动改变成key={localeObj.key}，我不知道怎么解决

**Comment by FreeCodersix** [comment]
> <Menu.Item key={localeObj.key} style={menuItemStyle}>
> <span role="img" aria-label={localeObj?.label || "en-US"}>
> {localeObj?.icon || "🌐"}
> 
> {localeObj?.label || "en-US"}
> </Menu.Item>
> 
> 遇到同样的问题，原因在key={localeObj.key}这里

你找到了解决办法吗

**Comment by daiwenyang** [comment]
<SelectLang postLocalesData={(data)=>{
            return data.map(item=> {item['key']=item.lang;return item})
          }}/>
我刚刚看了下，这样可以解决，你试下

**Comment by FreeCodersix** [comment]
> <SelectLang postLocalesData={(data)=>{
> return data.map(item=> {item['key']=item.lang;return item})
> }}/>
> 我刚刚看了下，这样可以解决，你试下

这个是放在UserLayout.tsx里面吗

**Comment by daiwenyang** [comment]
对，就是SelectLang组件使用的地方

**Comment by FreeCodersix** [comment]
> 对，就是SelectLang组件使用的地方

我试了一下，确实可以，但是这个排版为何这么奇怪你知道吗。。。

**Comment by daiwenyang** [comment]
api太简略了，你可以自己看源码改下

**Comment by FreeCodersix** [comment]
> api太简略了，你可以自己看源码改下

好的。还是谢谢你。期待作者大大给出一个好的建议

**Comment by farah** [comment]
I'm seeing this bug as well. Happens when you change the language.

**Comment by FreeCodersix** [comment]
> I'm seeing this bug as well. Happens when you change the language.

Yes, and I have found the problem, and the friends upstairs also gave suggestions, you can refer to it

**Comment by farah** [comment]
Sorry, but I don't speak Mandarin. Can there be a fix made upstream? I shouldn't have to change source code to make it compile correctly.

**Comment by FreeCodersix** [comment]
> Sorry, but I don't speak Mandarin. Can there be a fix made upstream? I shouldn't have to change source code to make it compile correctly.

Sorry ，I didn't find a better way

**Comment by chenshuai2144** [comment]
@FreeCodersix @farah  辛苦了

**Comment by FreeCodersix** [comment]
> @FreeCodersix @farah 辛苦了

小问题。但是我刚才试了一下，还是那样，是需要其他什么操作吗？比如重新npm install？而且，排版也还是原来的样子

**Comment by chenshuai2144** [comment]
更新一下依赖

```
>> Release: publish packages: plugin-locale, preset-react
[1/2] Publish package @umijs/plugin-locale
+ @umijs/plugin-locale@0.10.7
[2/2] Publish package @umijs/preset-react
+ @umijs/preset-react@1.7.11
>> Release: done

```

**Comment by FreeCodersix** [comment]
> 更新一下依赖
> 
> ```
> >> Release: publish packages: plugin-locale, preset-react
> [1/2] Publish package @umijs/plugin-locale
> + @umijs/plugin-locale@0.10.7
> [2/2] Publish package @umijs/preset-react
> + @umijs/preset-react@1.7.11
> >> Release: done
> ```
可以正常切换了，但是排版还是有问题
