### ISSUE TITLE
🧐[问题]如何修改菜单背景色

### ISSUE THREAD

**Issue by njypx** [ant-design/ant-design-pro#7941]
1、找到node_modules\antd\es\style\themes目录
2、打开default.less文件
3、找到570行， @menu-dark-submenu-bg: #000c17;
4、可以直接改颜色值。
5、还可以在src/components/GlobalHeader/index.less文件里修改
6、增加一行，@menu-dark-submenu-bg: #000c17;
7、修改一下，如改为@menu-dark-submenu-bg: #CC33CC;

**Comment by chenshuai2144** [comment]
或者 config.ts 里面的 theme:{ "@menu-dark-submenu-bg": "#000c17"  }

**Comment by codesignist** [comment]
@menu-dark-submenu-bg is not supported anymore. I have config.js and I've applied before. It was working properly but now is not working anymore. Can you control it?

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

look here ， antd mybe change var name
