### ISSUE TITLE
ModalForm 字段数据如何清空？

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7943]
@chenshuai2144 
在使用ModalForm提交数据后，再次打开，Form里显示上次输入的内容，如图：
![image](https://user-images.githubusercontent.com/17469220/104314969-3b688a80-5500-11eb-8ede-cc7aaab39c2b.png)

提交后加了resetFields()没有任何效果，按文档所说也加了initialValues，如图也没效果，请教是哪里用错了呢？

![image](https://user-images.githubusercontent.com/17469220/104314811-f3496800-54ff-11eb-807b-41d848dded14.png)

**Comment by brlala** [comment]
添加一个ref，然后加个方法清除
```
const [form] = Form.useForm();
const resetForm = () => {
  form.setFieldsValue({ username: null, email: null, password: null });
}
<ModalForm ... form={form} onFinish={resetForm}>
```
