### ISSUE TITLE
如何设置登录后的跳转页面？

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#7946]
Ant design pro version : 4.2.2

当前Ant design pro默认登录后跳转到SecurityLayout布局页面，该页面包含了顶部导航栏和侧面菜单。现在，我想要在登录页和securityLayout页面中再加一个页面pageX,登录后先跳转到pageX，在pageX作一些操作后再跳转到securityLayout

当前路由配置是
```
routes: [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
    ],
  },
  {
    path:'/pageX',
    component:'./PageX'
  },
  {
    path: '/',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/BasicLayout',
        authority: ['admin', 'user'],
        routes: [
          {
            path: '/',
            redirect: '/center',      
          },
          {
            path: '/center',
            name: '中心',
            icon: 'calendar',
            component: './Center',
          },

        ],
      },
    ],
  },
],
```
请问在哪里修改登录成功后的跳转地址呢？

**Comment by chenshuai2144** [comment]
```
{
            path: '/',
            redirect: '/center',      
          },
```

这里，用 / 跳转到哪里

**Comment by Youmyin** [comment]
我不想在SecurityLayout这个布局下，因为这个布局下有菜单栏，我想重新另起一个页面，model/login.ts中修改window.location.href可以吗，但是也不行
![image](https://user-images.githubusercontent.com/54265150/104420707-403b4600-55b5-11eb-83b4-356cca2d4024.png)

**Comment by chenshuai2144** [comment]
不行的，你可以把 路由配置在 SecurityLayout 前面。这样就可以拦阻  SecurityLayout了，本质上其实是去了首页

**Comment by Youmyin** [comment]
请问是像我的问题中那样吗，把pageX的路由写在SecurityLayout前面，可是这样还是默认跳转到SecurityLayout前面，只有将path改为‘/ ’才会跳转到pageX页面
```
  {
    path:'/',
    component:'./PageX'
  },
```
但是这样一来SecurityLayout的path又该写点啥呢？

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()


这里改一下

**Comment by Youmyin** [comment]
我之前就是改的这里，还是跳转到SecurityLayout，不过我好像知道是怎么回事了

model/login.ts中改为window.location.href = '/pageX';

路由配置中
```
  {
    path:'/pageX',
    component:'./PageX'
  },
```
但是这里不是严格匹配，还是会先匹配SecurityLayout对应的path：‘/ ’

所以这里最后需要在SecurityLayout外面再套一层路由

我明白了，谢谢你的解答！

**Comment by fengjinzhi123** [comment]
没看懂啊哥们
