### ISSUE TITLE
🧐[问题] pro-v5如何更改侧边栏收缩按钮位置

### ISSUE THREAD

**Issue by yuanye4017** [ant-design/ant-design-pro#7947]
### 🧐 问题描述
升级pro-v5以后`layout`隐藏，相关配置放到了`app.ts`，以前pro-v4的方法感觉不是很适用了，这个时候如何更改侧边栏收缩按钮位置？

### 💻 示例代码
```js
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
   collapsed,
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,
    ...initialState?.settings
  };
};
```
 这里的`collapsed`不能使用局部数据流，全局数据流不能保持动态更改

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/43987769/104430306-77175900-55c1-11eb-8004-67f2be52249a.png)

可以看到pro-v4的时候，使用的是`dva`数据流，配合`headerContentRender`将侧边栏收缩按钮放在头部，pro-v5改如何做？

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/plugins/plugin-layout#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE

https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed

这两个结合起来看看

**Comment by yuanye4017** [comment]
例子上是collapsed是使用了useState包起来，所以可动态更新的。v5放在app.ts中如何设置一个collapsed，使得collapsed改变页面也会跟着改变呢？

**Comment by chenshuai2144** [comment]
放到 initiaValues 里面

**Comment by yuanye4017** [comment]
谢谢🙏，按你说的已经实现了。
