### ISSUE TITLE
🐛[BUG]如何添加webpack的配置

### ISSUE THREAD

**Issue by njypx** [ant-design/ant-design-pro#7948]
### 🐛 bug 描述

webpack已经被umi封装掉了，请问一下，要添加新的webpack.config.js，该怎么办？
我使用了MonacoWebpackPlugin插件，但是在界面上显示不了关键字着色，估计与该插件有关，请问一下，该如何使它起作用？

**Comment by njypx** [comment]
使用react-monaco-editor，用来显示代码编辑功能，遇到了此问题，请予以解答？

**Comment by huntdream** [comment]
`config.ts`, 修改 webpack 配置参考：[chainWebpack](https://umijs.org/config#chainwebpack)

**Comment by njypx** [comment]
将已修改好的代码贴给有可能碰到此类问题的人，
在config/config.ts路径下：

import {defineConfig} from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");
const Config = require('webpack-chain');
const config = new Config();

const chainWebpack = (config) => {
  config.plugin('monaco-editor').use(MonacoWebpackPlugin, [
    {
      languages: ["json", "javascript", "typescript"],
    }
  ])
};

const {REACT_APP_ENV} = process.env;


export default defineConfig({
  chainWebpack,
  hash: true,

**Comment by LinWanCen** [comment]
@njypx 按了大佬的配置高亮实现了，提示没出现，你有出现吗？
