### ISSUE TITLE
下载最新的pro(v4 javascript) ，在vscode中发现eslint会对react等进行报错警告，🐛[BUG]

### ISSUE THREAD

**Issue by YoursOwen** [ant-design/ant-design-pro#7950]
### 🐛 bug 描述
下载最新的pro(v4 javascript) ，在vscode中发现eslint会对react等进行un-used-vars警告，

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/42412564/104546960-4e966a00-5668-11eb-90e5-40d883da1a85.png)
![image](https://user-images.githubusercontent.com/42412564/104547093-a9c85c80-5668-11eb-8502-23119d0c63cc.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] javascript 版本
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by YoursOwen** [comment]
![Uploading image.png…]()

**Comment by TernenceWu0702** [comment]
我也遇到了同样的问题，有什么解决方法吗
