### ISSUE TITLE
🐛[BUG]v4版本select虚拟滚动会造成空白，无法滚动等问题

### ISSUE THREAD

**Issue by Clago** [ant-design/ant-design-pro#7951]
### 🐛 bug 描述

v4版本select虚拟滚动会造成空白，无法滚动等问题。
ant.design单独没有问题，仅在pro下复现

### 📷 复现步骤

安装pro v4最新版本，select滚动即可复现

### 💻 复现代码

```
<Select style={{width:500}}>
          {
            [...Array(14).keys()].map(item => {
              return <Select.Option value={item} key={item}>{item}</Select.Option>
            })
          }
</Select>
```

### © 版本信息

- Ant Design Pro 版本: 1.0.28
- umi 版本 3.2.14 和 2.13.16
- 浏览器环境 chrome 87.0.4280.141
- 开发环境 macOs

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10774342/104547137-c369a400-5668-11eb-9320-76d03283cf31.png)

**Comment by chenshuai2144** [comment]
听起来和 pro 没关系，去 antd 那边提一下，那边的人更专业

**Comment by Clago** [comment]
> 听起来和 pro 没关系，去 antd 那边提一下，那边的人更专业
> 
> > 目测是是 css 样式污染，或者什么项没配置

可是我只跑antd没问题哎

**Comment by chenshuai2144** [comment]
你把 pro 的代码删掉，只留下 select 估计也没事。最好能搞个最小重现

**Comment by Clago** [comment]
> 你把 pro 的代码删掉，只留下 select 估计也没事。最好能搞个最小重现

应该是antd问题，有人提issue了，复现了问题。
