### ISSUE TITLE
🐛[BUG] antd v5: dist/static总是会生成官方logo图标：logo.f0355d39.svg

### ISSUE THREAD

**Issue by qianjinzhe** [ant-design/ant-design-pro#7955]
### 🐛 bug 描述

antd v5: 
在dist/static总是会生成官方logo图标：logo.f0355d39.svg，默认的 src/assets/logo.svg 已经替换了新图标，
但在dist/static总是会生成两个svg文件，一个是替换之后的，一个固定文件名logo.f0355d39.svg为官网图标，

dist/asset-manifest.json 中最后一行总是有   "/static/logo.svg": "/static/logo.f0355d39.svg",
请问如何删除这个多余的？

### 📷 复现步骤

正常安装 antd v5，替换logo.svg，Build后必现。

**Comment by chenshuai2144** [comment]
这个是组件库里带的。我看看能不能切成cdn

**Comment by xjb258** [comment]
麻烦告知是哪个组件库的哪个文件中可以干掉？强迫症有点受不了，感谢。

**Comment by chenshuai2144** [comment]
已经去了，你可以重新安装依赖再试试

**Comment by qianjinzhe** [comment]
> 已经去了，你可以重新安装依赖再试试

删掉node_modules，重新 yarn install，再build一样会生成，请告知你更新的依赖包名及版本号。

**Comment by chenshuai2144** [comment]
@ant-design/pro-layout

在这个仓库里，你看看版本

**Comment by qianjinzhe** [comment]
> @ant-design/pro-layout
> 
> 在这个仓库里，你看看版本

"@ant-design/pro-layout": "^6.4.19",

**Comment by chenshuai2144** [comment]
那应该不会了，f0355d39 这个全局搜都搜不到了

**Comment by qianjinzhe** [comment]
> 那应该不会了，f0355d39 这个全局搜都搜不到了

能否告知你修改了哪个文件，我在本地改，感谢。

**Comment by chenshuai2144** [comment]
先找是谁加的吧，是不是 pwa？
