### ISSUE TITLE
🐛[BUG] 新下载v2版本，启动时会报错

### ISSUE THREAD

**Issue by W-ambition** [ant-design/ant-design-pro#7956]
### 🐛 bug 描述
新下载v2版本，安装完依赖后，启动编译会报多个错误：
1. error evaluating function `darken`: color.toHSL is not a function
2. umi-plugin-polyfills has been deprecated. use config.targets instead.
3.  Tapable.plugin is deprecated. Use new API on `.hooks` instead
4. Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path 
or to `undefined` to prevent this warning.
但不影响使用

### 📷 复现步骤
通过git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project -b v2下载项目，安装依赖，npm start启动，编译会出现多个问题。

### 🏞 期望结果
正常编译，不会出现该错误

### © 版本信息

- Ant Design Pro 版本: [e.g. 2.0.0]
- umi 版本: 2.0.0
- 浏览器环境 chrome
- 开发环境  windows

**Comment by chenshuai2144** [comment]
看起来是less 的版本问题，有空清理一下插件把。

现在用 v2， 有点 49年加入国民党的感觉
