### ISSUE TITLE
🐛[BUG] 文件路径混用大小写导致warning的问题

### ISSUE THREAD

**Issue by wmf508** [ant-design/ant-design-pro#7958]
### 🐛 bug 描述
组件中import了同目录下的const.js文件，编译后报如下错误
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

因为习惯将组件的目录名头字母大写（内部包含index.jsx文件），目前的解决办法是将大写字母改小写，但这样会有点不舒服，因为就连pro自带的组件目录名也是头字母大写，请问有没有解决办法。
注意：因为const.js文件和组件的index.jsx在统一目录下所以引入的时候是直接使用 './const' 这样的相对路径方式引入，也就是没有手动写过大写字母的路径，但是仍然报错。

### 🏞 期望结果
能正常使用组件目录头字母大写，保持目录结构习惯

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 3.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个不是 pro 干的，是你的操作系统对大小写不敏感，建议你删掉文件再新建，不要直接改大小，不然你看起来改了，但是git 提交的还是旧的。

有条件可以直接用 Linux 开发。

**Comment by wmf508** [comment]
> 这个不是 pro 干的，是你的操作系统对大小写不敏感，建议你删掉文件再新建，不要直接改大小，不然你看起来改了，但是git 提交的还是旧的。
> 
> 有条件可以直接用 Linux 开发。

我是mac系统也是这个问题吗？mac好像和linux很像

**Comment by chenshuai2144** [comment]
mac 也是大小写不敏感的。
只有 linux 是敏感的， mac 需要格式化磁盘，然后重新设置
