### ISSUE TITLE
ant-design-pro项目中如何部署

### ISSUE THREAD

**Issue by woodcode** [ant-design/ant-design-pro#796]
我设置服务器地址：http://localhost:3000/api/
`
// .roadhogrc.mock.js

export default {
  'GET /api/(.*)': 'http://localhost:3000/api/',
};
`
本地测试，8000端口，api请求通过8000端口反向代理到3000端口获取数据，测试正常。

然后我通过：$ npm run build  生成静态打包文件。

这个时候serve 打开 index.html（仍然通过8000端口直接打开）， 这个时候api请求不能反向代理请求到3000端口的数据。 

我理解是不是自己要在服务器端设置反向代理？ 例如：nginx做反向代理？ api请求是8000， proxy_pass到我得3000端口。 api接口实际用golang写的。

感谢大神帮忙，谢谢。

**Comment by chenshuai2144** [comment]
配置和mock一样的代理规则就好了

**Comment by woodcode** [comment]
@chenshuai2144  也就是说生成环境中， 我的api服务器一定要配置一个反向代理对吧？
前端: admin.mydomain.com   
后端：api.mydomain.com  不同的服务器主机

然后我在admin.mydomain.com 主机上配置反向代理，例如nginx:
location / {
       index.html
}
location /api {
   proxy_pass: api.mydomain.com
}

大概是这个意思对吗？ 谢谢

**Comment by chenshuai2144** [comment]
是的！ nginx只提供静态服务

**Comment by chenshuai2144** [comment]
看一下markdown语法吧。 贴代码还是格式化了好懂
