### ISSUE TITLE
集成@umijs/plugin-qiankun插件 出现布局错乱和没办法跳转到登录页面 🐛[BUG]

### ISSUE THREAD

**Issue by lecd** [ant-design/ant-design-pro#7962]
ant-design-pro 集成@umijs/plugin-qiankun插件 

bug 描述
出现布局错乱

按官方步骤走 https://umijs.org/zh-CN/plugins/plugin-qiankun 

© 版本信息
- Ant Design Pro 版本: Ant Design Pro 5.0.0
- umi  最新版本
- 开发环境 [e.g. mac OS]

问题图片
![image](https://user-images.githubusercontent.com/17017158/104714945-cba50a80-5760-11eb-8cba-36a2b015bb0d.png)

![image](https://user-images.githubusercontent.com/17017158/104715602-bb415f80-5761-11eb-8690-1ea4c6d70805.png)

**Comment by chenshuai2144** [comment]
样式隔离导致的吧，去 umi 找 qiankun 的作者问一下？

**Comment by lecd** [comment]
> 样式隔离导致的吧，去 umi 找 qiankun 的作者问一下？

好的，谢谢

**Comment by niexq** [comment]
@lecd 老哥，解决了没
