### ISSUE TITLE
🐛[BUG]用Drawer打开ProDescriptions 无法显示，整个页面显示空白。

### ISSUE THREAD

**Issue by didi5683** [ant-design/ant-design-pro#7963]
### 🐛 bug 描述

最近更新后，通过protable 打开Drawer（其中包含ProDescription）页面显示空白。

### 📷 复现步骤

官方预览有同样问题： https://preview.pro.ant.design/list/table-list

**Comment by didi5683** [comment]
![image](https://user-images.githubusercontent.com/67136183/104834247-2bbebc80-58d9-11eb-9d20-ac48760256dd.png)

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues?q=is%3Aissue+is%3Aclosed
