### ISSUE TITLE
🧐[问题]如何自动生成路由啊，不想配置config/routes.ts

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#7967]
### 🧐 问题描述
刚使用ant-design-pro v5.　之前的版本我没有使用过，动态菜单我从后台拉取的，我以为它会自动去src目录下生成相应的路由，我刚用and-design-mobile的时候我发现它umi是自动根据目录生成了路由的。我也想这样生成，不想自己手工去配置一次，感觉每增加一个文件就要去写一个路由配置很麻烦。我把config/routes.ts　改名后我发现它并没有自动生成路由的！这就有点尴尬了。还是如里可以开启让它自动生成路由呢？

**Comment by chenshuai2144** [comment]
那你要使用约定式路由了，不过现在几乎没人用。

config/routes.ts 是个优势，他可以知道应该加载什么文件，约定式路由会加载所有的文件，不推荐你使用。

https://umijs.org/zh-CN/docs/convention-routing
