### ISSUE TITLE
🐛[BUG]Pro V5版本TS下使用Drawer组件控制台报warning

### ISSUE THREAD

**Issue by wmf508** [ant-design/ant-design-pro#7969]
### 🐛 bug 描述
Warning: React does not recognize the scrollLocker prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase scrolllocker instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
antd 的锅，升级 antd 到最新版本

**Comment by wmf508** [comment]
最新了啊，老的反而不报错

**Comment by chenshuai2144** [comment]
估计不是最新的，上个月才发布了
