### ISSUE TITLE
🐛[BUG] 菜单折叠时 没图标的菜单文本溢出 此处可只显示第一文字

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design-pro#7970]
### 🐛 bug 描述

菜单折叠时 没图标的菜单文本溢出 

### 🏞 期望结果

此处可只显示第一文字

**Comment by chenshuai2144** [comment]
这个是 antd 的设置，不允许修改。
如果你比较介意这个，可以直接关闭掉收起的功能

**Comment by pkaq** [comment]
@chenshuai2144 https://stackblitz.com/edit/ysvd4l--run?file=index.js
antd不存在这个问题啊 antd就是只显示第一个字

**Comment by chenshuai2144** [comment]
我们的最小宽度比 antd 的还要小
