### ISSUE TITLE
热更新失败？重启刷新缓存也不行🐛[BUG]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#7972]
"antd": "^3.25.2",

**Comment by chenshuai2144** [comment]
一般死活不行的问题都是因为 proxy 代理到服务器了

**Comment by lishaoh** [comment]
@chenshuai2144 我并没有代理到服务器，只是在config.js里面设置二级目录访问base和publicPath字段，然后就会热更新失败，如果不设置热更新没问题

**Comment by chenshuai2144** [comment]
base和publicPath字段 

你试试是不是和 proxy 重复了
