### ISSUE TITLE
请问v5正式版发布的话改动会很大吗？🧐[问题]

### ISSUE THREAD

**Issue by W-ambition** [ant-design/ant-design-pro#7973]
### 🧐 问题描述
请问v5正式版有发布计划吗？正式版相对于预览版会改动很大吗？

**Comment by chenshuai2144** [comment]
不会有任何改动的，现在插件的问题有点多，在修改插件的bug。因为一直服务于内部，对于外部用户的需求没什么精力接待。

而且分了很多精力到 https://procomponents.ant.design/，所以才压着一直不发的
