### ISSUE TITLE
npm create umi 在不同mac电脑执行的不一样 🧐[问题]

### ISSUE THREAD

**Issue by huixie** [ant-design/ant-design-pro#7974]
### 🧐 问题描述
node 都是 v12.14.1 
但是执行的时候一个电脑 会选择版本 这个安装是好的 一个电脑只会选择语言 然后安装会报错，并且拉下来的是ts版本的 哪怕选择了JS版本

**Comment by chenshuai2144** [comment]
你看看是不是缓存了吧。

如果是 可以用 npm uninstall create-umi -g 删除掉。
如果不是建议使用 yarn create umi 这种方式来使用。
