### ISSUE TITLE
🧐[问题]V4还在维护吗？看一下这个问题

### ISSUE THREAD

**Issue by sorryljt** [ant-design/ant-design-pro#7975]
https://github.com/umijs/umi/issues/6022

**Comment by sorryljt** [comment]
一开始以为是umi的问题，仔细思考后发现，可能是V4这里写错了，导致好的开发者，更着这样写，写出了无效的代码~

**Comment by chenshuai2144** [comment]
。。。

你这个表达，我有点看不懂，

路由匹配是贪婪匹配，只要由一个匹配上的就不会走后面的。

**Comment by sorryljt** [comment]
那这段重定向是啥意思呢？或者期望他做什么呢？
```
    {
      path: '/form',
      icon: 'form',
      name: 'form',
      routes: [
        {
          path: '/',
          redirect: '/form/basic-form',
        },
        {
          name: 'basic-form',
          icon: 'smile',
          path: '/form/basic-form',
          component: './form/basic-form',
        },
```
如果期望根路由重定向到'/form/basic-form'，实际上不是，是结合V4中路由配置的上下文，是重定向到'/dashboard/analysis'的，如果期望的是'/form'重定向到'/form/basic-form'，也是没有效果，我个人是觉得这里这个代码
有点问题，是不是应该写成
```
...
    routes: [
      {
        path: '/form',
        redirect: '/form/basic-form',
      },
...
]
...
```
这种形式呢，才能保证'/form'重定向到'/form/basic-form'上，而根路由的重定向，是在`path: '/'`哪里设置的，不需要在这设置，这里的重定向本意应该就是期望'/form'重定向到'/form/basic-form'上。
大佬，我这回表达清楚了吗？

**Comment by chenshuai2144** [comment]
这个是偷懒了，因为 '/form', 开头的路径才能走到  routes: [
        {
          path: '/',
          redirect: '/form/basic-form',
        }]

其实写成 './' 更加合理

**Comment by sorryljt** [comment]
可以，亲测'./'有效，多谢大佬~
