### ISSUE TITLE
🧐[问题] form.setFieldsValue   对于直接赋值的对象 不能删除 只能增加

### ISSUE THREAD

**Issue by zhj778930960** [ant-design/ant-design-pro#7976]
### 🧐 问题描述
表单，有一个数据是用户自己输入对象中的参数， 我使用 form.setFieldsValue   传递给form  我新增可以，但是我
删除一个自己定义的 就不行了 删除不掉

### 🚑 其他信息

这是我改了之后的
![image](https://user-images.githubusercontent.com/23496206/104983325-8a09ad80-5a47-11eb-8f6f-8cd5648418df.png)
![image](https://user-images.githubusercontent.com/23496206/104983374-a1e13180-5a47-11eb-97b7-b1e32d3f7a9a.png)

我打印 
form.getFieldsValue（）  还是原来的 但是新增是可以的  只有删除不行
![image](https://user-images.githubusercontent.com/23496206/104983353-97bf3300-5a47-11eb-82aa-928c423f4bdf.png)

**Comment by chenshuai2144** [comment]
`form.setFieldsValue`  之后执行 ` form.reset`  就可以重置掉了。

如果你是想 动态该参数建议用` form.setFieldValues`

**Comment by zhj778930960** [comment]
> setFieldValues

setFieldValues  有这个属性么。。。 好像没有吧

**Comment by chenshuai2144** [comment]
https://ant.design/components/form-cn/
看这里

**Comment by zhj778930960** [comment]
setFields 可以解决这个问题
