### ISSUE TITLE
🧐[问题]v4如何设置默认语言为中文呢？

### ISSUE THREAD

**Issue by Pythonchao** [ant-design/ant-design-pro#7977]
### 🧐 问题描述
在哪个文件设置的？

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/plugins/plugin-locale

看这个

**Comment by hfpp2012** [comment]
![image](https://user-images.githubusercontent.com/740643/106488457-b238e800-64ee-11eb-95d7-b6b421f47453.png)
