### ISSUE TITLE
🧐[问题]模块安装错误

### ISSUE THREAD

**Issue by njypx** [ant-design/ant-design-pro#7979]
### 🧐 问题描述

ERROR  Failed to compile with 10 errors                                                                                                                                                                                                    下午3:59:43

This dependency was not found:

* _@ant-design_pro-layout@6.10.6@@ant-design/pro-layout in ./src/pages/account/recharge/index.tsx, ./src/pages/account/serialnumber/index.tsx and 8 others

To install it, you can run: npm install --save _@ant-design_pro-layout@6.10.6@@ant-design/pro-layout

**Comment by njypx** [comment]
npm install 反复安装，错误解决不了。请问一下原因？

**Comment by njypx** [comment]
发现文件中，存在：
import {PageContainer} from "_@ant-design_pro-layout@6.10.6@@ant-design/pro-layout";
不知道它是如何产生的？

**Comment by chenshuai2144** [comment]
这个一般是你的 vsocode 在你改名的时候帮你自动改的，我被坑了好多次。你可以关掉这个功能
