### ISSUE TITLE
windows下安装卡住不动了

### ISSUE THREAD

**Issue by winer632** [ant-design/ant-design-pro#798]
C:\Users\0163>node -v
v8.9.4

C:\Users\0163>cnpm -v
cnpm@5.1.1 (D:\Program Files\nodejs\node_global\node_modules\cnpm\lib\parse_argv.js)
npm@5.6.0 (D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@8.9.4 (D:\Program Files\nodejs\node.exe)
npminstall@3.3.0 (D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=D:\Program
win32 x64 10.0.10240
registry=http://registry.npm.taobao.org

C:\Users\0163>

![image](https://user-images.githubusercontent.com/4931801/35259716-4d2fdafe-0042-11e8-8f02-a48c322b467d.png)

**Comment by chenshuai2144** [comment]
window 抽一鞭子ctrl+c就好了。 不行再来次。。。。。提个pr干什么。
