### ISSUE TITLE
👑 [需求]您好，我想问下ant design pro怎么设置菜单才能让点击菜单的同时跳转到对应的页面又展开自己的子菜单呢？

### ISSUE THREAD

**Issue by Shanrunan** [ant-design/ant-design-pro#7980]
### 🥰 需求描述
您好，我想问下ant design pro怎么设置菜单才能让点击菜单的同时跳转到对应的页面又展开自己的子菜单呢？

**Comment by chenshuai2144** [comment]
重定向到子菜单？

**Comment by Shanrunan** [comment]
> 重定向到子菜单？

大佬，不管用啊，重定向，而且我重定向了父菜单的页面，子菜单全部指向了同一个页面，就很奇怪。

**Comment by chenshuai2144** [comment]
看一下怎么配置的？

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it
