### ISSUE TITLE
🧐[问题]动态获取menu和修改标签上的icon

### ISSUE THREAD

**Issue by xu-Aurora** [ant-design/ant-design-pro#7981]
### 🧐 问题描述
menu和标签上icon问题

1.左侧菜单栏menu我是从后台获取的，用户在进入系统后，可能会存在刷新页面，怎么在app.tsx里面配置在刷新页面时获取menu是添加loading
2.怎么修改标签上的icon

**Comment by xu-Aurora** [comment]
3.在登陆之后，后台获取menu，通过useModel给设置初始值menu，但点击刷新后menu就又为空了，怎么达到页面刷新了menu还在

**Comment by chenshuai2144** [comment]
标签上的icon 最好不要修改，缓存很厉害，改了也不一定能过来。

剩下的问题可以看 

https://beta-pro.ant.design/docs/advanced-menu-cn
