### ISSUE TITLE
🧐[问题] fatal: unable to update url base from redirection

### ISSUE THREAD

**Issue by Jeff-Tian** [ant-design/ant-design-pro#7982]
### 🧐 问题描述

在初始化项目时碰到这个错误，请问该从哪里排查问题和解决（或者绕过）？

```
fatal: unable to update url base from redirection:
```

### 💻 示例代码

```
yarn create umi xxx
yarn create v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@tarojs/cli > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "create-umi > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@4.10.0" has unmet peer dependency "@typescript-eslint/parser@^4.0.0".
[4/4] 🔨  Building fresh packages...
success Installed "create-umi@0.26.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V5
Cloning into 'xxx'...
fatal: unable to update url base from redirection:
  asked for: https://gitee.com/ant-design/ant-design-pro/info/refs?service=git-upload-pack
   redirect: https://gitee.com/ant-design/ant-design-pro/info/refs?X-OpenDNS-Session=_fa2da2870f26f041500b5e70c763e52711499270fb54_f0urhylu_service=git-upload-pack
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 --branch v5 xxx
null
null
    at makeError (/Users/tianjef/.config/yarn/global/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/tianjef/.config/yarn/global/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/tianjef/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:1022:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments: xxx
Directory: /Users/jeff-tian/
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

### 🚑 其他信息

没有使用代理

```
➜ git config --global http.proxy

```

**Comment by chenshuai2144** [comment]
手工执行一下 
`git clone https://gitee.com/ant-design/ant-design-pro --depth=1 --branch v5 adidas-front`

看起来是路径占用之类的问题

**Comment by Jeff-Tian** [comment]
手工执行报同样的错误。但是把gitee换成github 没问题。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sanqiu0625** [comment]
初始化报错
? 🐂 使用 umi@4 还是 umi@3 ? umi@4
🧎🏻全量区块暂时不支持 umi@4
> clone repo url: https://gitee.com/ant-design/ant-design-pro
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
× An error occured while running #writing
C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 nianapi-forntend    at makeError (C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AntDesignProGenerator.writing (C:\Users\12924\AppData\Roaming\npm\node_modules\@ant-design\pro-cli\src\create\generators\ant-design-pro\index.js:119:5) {
  shortMessage: 'Command failed with exit code 1: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 nianapi-forntend',
  command: 'git clone https://gitee.com/ant-design/ant-design-pro --depth=1 nianapi-forntend',
  escapedCommand: 'git clone "https://gitee.com/ant-design/ant-design-pro" "--depth=1" nianapi-forntend',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0
