### ISSUE TITLE
🧐[问题]v5打包样式覆盖

### ISSUE THREAD

**Issue by zassq** [ant-design/ant-design-pro#7985]
### 🧐 问题描述

v5版本，打包后global.less下的全局样式修改被覆盖，开发环境不会存在这种问题
这种情况怎么办好呢？取消chunk按需加载吗？

### 💻 示例代码

![1](https://user-images.githubusercontent.com/1635161/105276412-4ac09580-5bdc-11eb-9dbd-83a685e96c81.png)
生产环境下的样式

![2](https://user-images.githubusercontent.com/1635161/105276698-f4a02200-5bdc-11eb-9d36-723641896121.png)
开发环境

**Comment by chenshuai2144** [comment]
提升一下css 的优先级就好了，前面加个前缀，或者直接无脑 important
