### ISSUE TITLE
左侧导航 异步数据同时 展开菜单不能同时用 menu={{ loading, defaultOpenAll:true }}🐛[BUG]

### ISSUE THREAD

**Issue by yangke2018** [ant-design/ant-design-pro#7986]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
祥细一点，我觉得我没听懂

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by FengHuangDong** [comment]
@chenshuai2144 他这个意思是如果menu是从api获取的，那么defaultOpenAll:true一开始的时候生效了，但是没有menu，然后API拿到menu数据后，defaultOpenAll:true这个就等于没作用了

**Comment by chenshuai2144** [comment]
设计就是这样的，自己的菜单可以自动控制 openKeys
