### ISSUE TITLE
🐛[BUG]部署到非根目录下时，生成的面包屑链接不正确

### ISSUE THREAD

**Issue by didi5683** [ant-design/ant-design-pro#7987]
### 🐛 bug 描述

当部署到非根目录下时，config.ts 中设置 

`base: '/biz/',`

面包屑生成的链接中产生了重复的路径。如图所示：

![image](https://user-images.githubusercontent.com/67136183/105338469-8ed08c00-5c16-11eb-84fc-68b531c728cf.png)

页面正确的地址是： http://localhost:8000/#/biz/config
面包屑中的链接地址是： http://localhost:8000/#/biz/biz//config

重复生成了 '/biz/'

部署到根目录中时，没有上述问题产生。

**Comment by yuandalu** [comment]
我也提了一个一样的问题，希望能够解决

**Comment by a359377420** [comment]
同遇到 希望解决

**Comment by chenshuai2144** [comment]
会抽个大时间一起解决一下。
