### ISSUE TITLE
🧐[问题] v5使用运行时 rootContainer 后 acess 权限失效

### ISSUE THREAD

**Issue by yoyooyooo** [ant-design/ant-design-pro#7989]
### 🧐 问题描述

使用运行时 rootContainer 后 acess 权限失效，我知道 layout 的 childrenRender可以做到，但是为什么 rootContainer 会影响到权限

**Comment by chenshuai2144** [comment]
这个不大可能 react不关心dom的 是不是别的技术

**Comment by yoyooyooo** [comment]
> 这个不大可能 react不关心dom的 是不是别的技术

我这边试的确实是这样，umi create 创建的新项目，加了 rootContainer，access 就失效了

**Comment by wangJacker** [comment]
@chenshuai2144  是的的确是这样很奇怪 我也遇到了  我是直接git clone V5 的项目

**Comment by xiexingen** [comment]
我也遇到了，然后umi中找到了答案
https://github.com/wetrial/wetrial-template/blob/master/src/app.tsx
这样，可以参考下

**Comment by wangJacker** [comment]
感谢，已修复！ 我找了半天没找到  我以为是access的rootContainer 影响了 ，看了半天

**Comment by qfkobe24** [comment]
没见修复记录呢

**Comment by qfkobe24** [comment]
export function rootContainer(container, opts) {
  return React.createElement(BaseLayout, opts, container);
}

opts要通过BaseLayout透传到container
