### ISSUE TITLE
🐛[BUG] vscode 报 Parsing error: Cannot find module '@babel/plugin-proposal-decorators'错误

### ISSUE THREAD

**Issue by qianls** [ant-design/ant-design-pro#7990]
### 🐛 bug 描述

 随便点进一个.jsx文件或者根目录下jsconfig.json文件 vscode 报 Parsing error: Cannot find module '@babel/plugin-proposal-decorators'错误
### 📷 复现步骤

安装好Ant Design Pro 脚手架 配置的是 ant-design-pro   V4  JavaScript  complete，使用npm install 安装好项目依赖 。随便点进一个文件就报错

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/41314635/105451240-2685b700-5cb7-11eb-8075-a3968597f694.png)

**Comment by qianls** [comment]
重启一下电脑就好了。。。。。我tm

**Comment by epubreader** [comment]
怎么解决， 我也遇到了
