### ISSUE TITLE
antd pro V5 如何修改 loading图

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#7992]
如标题，我查了 以前的贴子，但都是太老了，试过不管用。也改过document.ejs，改了后只在初次加载时有效果，进入后URL跳转时还是标准的loading图标，如图
![image](https://user-images.githubusercontent.com/17469220/105490253-817cd580-5cda-11eb-9751-3c86eae50cdb.png)

也改过
![image](https://user-images.githubusercontent.com/17469220/105490356-a7a27580-5cda-11eb-89e3-cf73c1e13ff0.png) 也没什么用，请有经验的说明下。

**Comment by chenshuai2144** [comment]
就是这两个地方，你是怎么修改的，应该是生效的

**Comment by my9988** [comment]
> @chenshuai2144 
> 
> 就是这两个地方，你是怎么修改的，应该是生效的

首先非常感谢chenshuai2144的回复，我是从一点不懂，在各位的帮助下接近完成一个系统了，如果没人支持，有时真搞不懂。

我第一处改的
![image](https://user-images.githubusercontent.com/17469220/105575067-cbbf8e80-5d8e-11eb-9d2c-c893ae72ce42.png)

这个在登录界面显示有效果了，变成了绿色。登录后无效果。

第二处，也是看了chenshuai2144 2019年的一个回复，我也只是抄了过来，没改什么，是不是这里要改？
![image](https://user-images.githubusercontent.com/17469220/105575120-2822ae00-5d8f-11eb-9b98-c565838fe543.png)

**Comment by chenshuai2144** [comment]
这个pageLoading 是我写的一个组件，源码在这里。

https://github.com/ant-design/pro-components/blob/master/packages/layout/src/components/PageLoading/index.tsx

如果只是想简单的修改一下颜色的话，建议你更换一下主题色。在 `\config\defaultSettings.ts` 中修改 `primaryColor` 为你想要的颜色

**Comment by my9988** [comment]
@chenshuai2144 用了你说的方法，就是用你写的组件，新的问题又来了，显示两个Loading了，原有的那个也显示，怎么去了呢？有很多人问怎么自定义这个，怎么改那个？其实你们要理解这个事，如果大家都不修改，发布出的系统都一个样，好难看的，所以大家都想有自己的特色，因此你们在设计的时候一定有平台的思想，尽量给开发者留有余地。否则没人参与，游戏还怎么玩

**Comment by chenshuai2144** [comment]
Debug一下 dom是哪里来的吧
