### ISSUE TITLE
path 设置外链，正则识别有缺失

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-pro#7993]
### 🐛 bug 描述

route 设置path为外链，如果路径带有hash，识别有问题

![截屏2021-01-22 22 18 07](https://user-images.githubusercontent.com/8924156/105501900-c2d3ac00-5cff-11eb-9d6d-5a64d0899620.png)

```javascript
const reg = /(((^https?:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+(?::\d+)?|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)$/
/(((^https?:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+(?::\d+)?|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)$/

const path = 'https://www.baidu.com/#/list'

console.log(reg.test(path))
```

<img width="452" alt="截屏2021-01-22 22 21 19" src="https://user-images.githubusercontent.com/8924156/105502227-31186e80-5d00-11eb-8db1-abd11a20354d.png">

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 3.2.27
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个pr吧，这个复杂的正则也没几个人能看懂

**Comment by yezongyang** [comment]
@chenshuai2144 要不简做成单识别一下吧，别弄这么复杂说不定还会有别的情况缺失识别

**Comment by chenshuai2144** [comment]
你可以搞个库来试试
