### ISSUE TITLE
增加自定义辅助操作，如下拉筛选（业务诉求）

### ISSUE THREAD

**Issue by kaichong** [ant-design/ant-design-pro#7997]
![image](https://user-images.githubusercontent.com/16532952/105575498-12b97e00-5da7-11eb-8827-224d911242b3.png)
菜单自定义辅助操作，搜索菜单的，需要怎么写呢？找不到相关文档。

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout/#%E6%90%9C%E7%B4%A2%E8%8F%9C%E5%8D%95

看看这个demo，和你这个用的一个设计稿

**Comment by wiredgril666** [comment]
在v5里边怎么实现呢？layout是在app.tsx配置了的后、
这个demo有用到useState.配置的layout是不支持的、v5里实现菜单搜索，这个有demo可以参考下吗？

**Comment by chenshuai2144** [comment]
这个在app.tsx 里面不好实现，正式发布的时候我写个demo试试
