### ISSUE TITLE
🐛[BUG] npx umi block add报错

### ISSUE THREAD

**Issue by HSIKE** [ant-design/ant-design-pro#7999]
### 🐛 bug 描述
$ npx umi block add AccountSettings --js
WARN [WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json
- 😁  Parse url and args
√ 😁  Parse url and args
- 🚛  sync file for git repo --branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
√ 🚛  sync file for git repo --branch master
×  error     AssertionError [ERR_ASSERTION]: C:\Users\Mr Huang\.umi3\blocks\github.com\umijs\umi-blocks\AccountSettings don't exists
    at G:\ant-design-pro\node_modules\@umijs\block-sdk\lib\addBlock.js:222:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (G:\ant-design-pro\node_modules\@umijs\block-sdk\lib\addBlock.js:110:103)
    at _next (G:\ant-design-pro\node_modules\@umijs\block-sdk\lib\addBlock.js:112:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by chenshuai2144** [comment]
执行一下umi block  clean

**Comment by HSIKE** [comment]
> > 执行一下umi block clean
> 
> > 手动全局安装了umi之后也是报一样的错误
> > $ npx umi block clean
> > WARN [WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json
> > ×  error     Error: Please run umi help block to checkout the usage
> > at G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:96:17
> > at Generator.next ()
> > at asyncGeneratorStep (G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:46:103)
> > at _next (G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:48:194)
> > at G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:48:364
> > at new Promise ()
> > at G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:48:97
> > at _block (G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:101:19)
> > at block (G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:71:19)
> > at G:\ant-design-pro\node_modules@umijs\plugin-blocks\lib\index.js:158:17

**Comment by chenshuai2144** [comment]
`umi block clear` 估计我记错了命令

**Comment by chenshuai2144** [comment]
这个功能已经废弃并停止维护，如果需要建议自行frok维护。
——
This function has been abandoned and stopped maintenance. If necessary, it is recommended to start maintenance by yourself.
