### ISSUE TITLE
自己搭的脚手架，请问ant-design-pro的css样式怎么引用

### ISSUE THREAD

**Issue by zl612** [ant-design/ant-design-pro#80]
1.自己搭的脚手架，请问ant-design-pro的css样式怎么引用!!!!!!!!!!!!!!!!!!!
2.可以加redux在ant-design-pro脚手架中
3.不是webpack打包的请问用了什么技术

**Comment by liumin1128** [comment]
额，建议先看下[dva](https://github.com/dvajs/dva)，使用的是roadhog，相当于增强的create-react-app，也是基于webpack的。

**Comment by nikogu** [comment]
`import` 进来就好了，如果是 `umd` 的话，样式在 `dist` 下
