### ISSUE TITLE
Error: Cannot find module 'address'     at Function.Module._resolveFilename (module.js:538:15)

### ISSUE THREAD

**Issue by winer632** [ant-design/ant-design-pro#800]
windows下报这个错，可否帮忙看下原因？

![image](https://user-images.githubusercontent.com/4931801/35263445-bd5f5988-0053-11e8-99ee-58c613742e1d.png)

**Comment by chenshuai2144** [comment]
缺包。重装一下。

**Comment by winer632** [comment]
对node版本的要求必须是 node@>=0.10.0 <7 ？
我的node是 v8.9.4 可以吗？

**Comment by chenshuai2144** [comment]
没问题。。。
我8.7.0

**Comment by winer632** [comment]
@chenshuai2144 重新安装提示已经安装好了。是否要用npm install而不是cnpm install？
![image](https://user-images.githubusercontent.com/4931801/35263752-fee2f062-0054-11e8-9a30-ffc29c579714.png)

**Comment by chenshuai2144** [comment]
理论上都一样。删了所有包再安装成功率更高哦

**Comment by zjscy666** [comment]
我把所有包删除 装了一边成功乐，感谢，不过我自己加了webpack相关配置
