### ISSUE TITLE
🧐[问题] V5 多环境配置文件 `config.dev.ts` 不生效

### ISSUE THREAD

**Issue by wywppkd** [ant-design/ant-design-pro#8000]
### 🧐 问题描述

- 指定环境变量 `REACT_APP_ENV=dev`, 设置配置文件 `config/config.dev.ts`, 但是配置不生效
- 不是应该会自动 merge `config.ts` 和 `config.dev.ts` 吗

### 💻 示例代码

```js
// config/config.dev.ts
import { defineConfig } from 'umi';

export default defineConfig({
  define: {
    REACT_APP_API_URL: 'http://xxx.com',
  },
});

// config/config.ts
export default defineConfig({
  // ...
});

// app.tsx
export const request: RequestConfig = {
  // ...
  prefix: REACT_APP_API_URL,
  // ...
}
```

```bash
$ npm start # "start": "cross-env REACT_APP_ENV=dev MOCK=none umi dev"
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20620574/105668416-3c45e700-5f18-11eb-8f1c-a5e0d446561e.png)

**Comment by chenshuai2144** [comment]
你配置错环境变量了

https://umijs.org/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE
