### ISSUE TITLE
🐛[BUG]Prolayout中breadcrumbRender的参数routers错误的返回了对象，应为数组

### ISSUE THREAD

**Issue by xiaoxiaofan123** [ant-design/ant-design-pro#8001]
### 🐛 bug 描述

升级了antd pro以及antd库后，报了“TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.”的错
发现是Prolayout中breadcrumbRender的参数routers返回了对象，错误的解构了。这里应该是返回数组的吧？

### 📷 复现步骤

routers打印出来的结果截图（开始是数组 后面变成了对象）
![image](https://user-images.githubusercontent.com/18550815/105673610-3c96b000-5f21-11eb-9fd9-2dc667f5f9ca.png)

### 💻 复现代码

   <ProLayout
 
      breadcrumbRender={(routers = []) => {
        console.log(routers);
        return [
          {
            path: '/',
            breadcrumbName: '首页',
          },
          ...routers,
        ];
      }}
/>

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.2.0]
- umi 版本
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by 18673227300** [comment]
下载下来启动就报这个错

**Comment by xyhallo** [comment]
一样的，阿里云sit项目都报这个错了，我感觉版本号没更新就发布了。

**Comment by starhu521** [comment]
是啊，不能这么搞啊，起码一个major得是兼容的啊，不然每次拉代码更新，版本不兼容的问题很难搞。

**Comment by Observer-L** [comment]
+1

**Comment by askuy** [comment]
+1

**Comment by link-duan** [comment]
+n

**Comment by yqnetwork** [comment]
+n

**Comment by richagain** [comment]
+4

**Comment by mengxuhui** [comment]
34

**Comment by sevennt** [comment]
+1

**Comment by cao-lianhui** [comment]
有谁知道怎么解决的吗，我也遇到了，求助

**Comment by xyhallo** [comment]
> 有谁知道怎么解决的吗，我也遇到了，求助

目前我的解决方案是判断是不是object 是的话就return []

**Comment by xiaoxiaofan123** [comment]
暂时的解决方案是:
1.把antd版本降低一些(我用的4.9.3)
2.在 breadcrumbRender中处理一下routers的类型

**Comment by cao-lianhui** [comment]
> > 有谁知道怎么解决的吗，我也遇到了，求助
> 
> 目前我的解决方案是判断是不是object 是的话就return []

感谢大佬，已解决

`
const renderRouter = (routers = []) => {
    console.log(routers, 'router');
    if(Object.prototype.toString.call(routers) === "[object Array]"){
      return [
        {
          path: '/',
          breadcrumbName: '首页',
        },
        ...routers,
      ]
    }
    return [];
  }
`

**Comment by j511002** [comment]
antd版本 4.11.1 会出现此问题，降到 4.10.3 就好了。

**Comment by superAo005** [comment]
+1 antd锁定版本 为4.10.3 就好了，然后 在breadcrumbRender中处理一下routers的类型

**Comment by chenshuai2144** [comment]
跟新版本吧，这个问题已经解决了

是因为和 antd 支持了同名的 api，但是功能不同导致的

**Comment by 569202812** [comment]
> 跟新版本吧，这个问题已经解决了
> 
> 是因为和 antd 支持了同名的 api，但是功能不同导致的

升级antd和pro-layout的版本吗，升级了这两个版本还是不支持的

**Comment by j511002** [comment]
> > 跟新版本吧，这个问题已经解决了
> > 是因为和 antd 支持了同名的 api，但是功能不同导致的
> 
> 升级antd和pro-layout的版本吗，升级了这两个版本还是不支持的

你可以直接执行 yarn upgrade。我整体更新了一下就好了。
