### ISSUE TITLE
🐛[BUG]Antd pro V4.2.1的版本是否可以提供Javascirpt版本，目前下载只有ts版本

### ISSUE THREAD

**Issue by okwen5566** [ant-design/ant-design-pro#8003]
### 🐛 bug 描述

Antd pro V4.2.1的版本是否可以提供Javascirpt版本，目前下载只有ts版本
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by HSIKE** [comment]
用npm create umi命令可以选择JavaScript版本

**Comment by chenshuai2144** [comment]
楼上正解。


建议稍微学习一下 ts，即使是 anyscript 也能带来很多的优势
