### ISSUE TITLE
关于Dayjs替换moment.js

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#8007]
@chenshuai2144 

1.为了减小打包体积，有人建议用Dayjs代替moment.js,可减少0.55M,请问这确实有用吗？

2.如果有用，想问ProFormDatePicker会依赖moment.js吗？antd官网DatePicker都要重写，是不是ProFormDatePicker也要重写？

**Comment by chenshuai2144** [comment]
是的，如果要改整个项目都要做改动，其实去掉locale，moment 就没有什么大小了。
你可以忽略掉 moment 的那些 locale

更换dayjs的成本还是很高的，还是不能无缝替换

**Comment by my9988** [comment]
谢谢回复，明白了。
