### ISSUE TITLE
👑 [需求]  请问有屏幕截屏的功能吗

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#8008]
### 🥰 需求描述

 可以截下可视窗口内的东西；
 
![image](https://user-images.githubusercontent.com/45235142/105814353-40433900-5fec-11eb-998e-7f6a75708abb.png)

现在这个图上有svg的标签 我使用过html2canvas 加canvg  但是svg里面有path标签 发现乜办法吧这种标签转成canvas
所有没办法做了。这边请问一下 有什么办法做截屏的功能？ 或者是插件

**Comment by chenshuai2144** [comment]
html2canvas 是唯一的办法了。

地图一般有转化为图片的功能，如果想实现浏览器截图，最好做个浏览器插件
