### ISSUE TITLE
请问antd pro v5 如何配置去掉权限管理，不进入登陆页面？

### ISSUE THREAD

**Issue by bodian520** [ant-design/ant-design-pro#8009]
v5版本中utlis目录下没有authority.ts文件，请问下具体如何设置可以跳过登陆？

**Comment by bodian520** [comment]
自问自答，没有找到特别好的办法，通过屏蔽跳转登陆页面，自动填充currentUser信息来解决问题：


src/app.tsx


`export async function getInitialState(): Promise<{
  settings?: LayoutSettings;
  currentUser?: API.CurrentUser;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    try {
      // const currentUser = await queryCurrent();
      // return currentUser;


      return {
        name: 'Serati Ma',
        avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
        userid: '00000001',
        email: 'antdesign@alipay.com',
        signature: '海纳百川，有容乃大',
        title: '交互专家',
        group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
        tags: [
          {
            key: '0',
            label: '很有想法的',
          },
          {
            key: '1',
            label: '专注设计',
          },
          {
            key: '2',
            label: '辣~',
          },
          {
            key: '3',
            label: '大长腿',
          },
          {
            key: '4',
            label: '川妹子',
          },
          {
            key: '5',
            label: '海纳百川',
          },
        ],
        notifyCount: 12,
        unreadCount: 11,
        country: 'China',
        access: 'admin',
        geographic: {
          province: {
            label: '浙江省',
            key: '330000',
          },
          city: {
            label: '杭州市',
            key: '330100',
          },
        },
        address: '西湖区工专路 77 号',
        phone: '0752-268888888',
      };


    } catch (error) {
      history.push('/user/login');
    }
    return undefined;
  };
  // 如果是登录页面，不执行
  if (history.location.pathname !== '/user/login') {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: defaultSettings,
    };
  }
  return {
    fetchUserInfo,
    settings: defaultSettings,
  };
}

export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { location } = history;
      // 如果没有登录，重定向到 login
      // if (!initialState?.currentUser && location.pathname !== '/user/login') {
      //   history.push('/user/login');
      // }
    },
    menuHeaderRender: undefined,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings,
  };
};`


修改pages/user/login/index.tsx，增加初始化方法

`useEffect(()=> {
    setSubmitting(true);
    try {
      // 登录
      // const msg = await fakeAccountLogin({ ...values, type });
      // if (msg.status === 'ok') {
      //   message.success('登录成功！');
      //   await fetchUserInfo();
      //   goto();
      //   return;
      // }

      setInitialState({
        ...initialState,
        currentUser: {
          name: 'Serati Ma',
          avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
          userid: '00000001',
          email: 'antdesign@alipay.com',
          signature: '海纳百川，有容乃大',
          title: '交互专家',
          group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
          tags: [
            {
              key: '0',
              label: '很有想法的',
            },
            {
              key: '1',
              label: '专注设计',
            },
            {
              key: '2',
              label: '辣~',
            },
            {
              key: '3',
              label: '大长腿',
            },
            {
              key: '4',
              label: '川妹子',
            },
            {
              key: '5',
              label: '海纳百川',
            },
          ],
          notifyCount: 12,
          unreadCount: 11,
          country: 'China',
          access: 'admin',
          geographic: {
            province: {
              label: '浙江省',
              key: '330000',
            },
            city: {
              label: '杭州市',
              key: '330100',
            },
          },
          address: '西湖区工专路 77 号',
          phone: '0752-268888888',
        },
      });

      goto();
      return;

      // 如果失败去设置用户错误信息
      setUserLoginState(msg);
    } catch (error) {
      message.error('登录失败，请重试！');
    }
    setSubmitting(false);


  }, []);`

**Comment by Samtoto** [comment]
是不是应该在 config/routes.ts app/access.ts 里配置？

**Comment by 569202812** [comment]
> 是不是应该在 config/routes.ts app/access.ts 里配置？
 config/routes.ts 和app.tsx

**Comment by bodian520** [comment]
> 是不是应该在 config/routes.ts app/access.ts 里配置？
> config/routes.ts 和app.tsx

具体怎么配置呢？

**Comment by 569202812** [comment]
> > 是不是应该在 config/routes.ts app/access.ts 里配置？
> > config/routes.ts 和app.tsx
> 
> 具体怎么配置呢？

注释掉onPageChange的代码就行吧

**Comment by hfpp2012** [comment]
![image](https://user-images.githubusercontent.com/740643/106488095-4bb3ca00-64ee-11eb-8ac0-31af020537d0.png)

亲测有效

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/authority-management-cn

看这里，把routers 中的权限相关配置也要已删掉，然后按照楼上来

**Comment by CrystalCAI11** [comment]
> 自问自答，没有找到特别好的办法，通过屏蔽跳转登陆页面，自动填充currentUser信息来解决问题：
> 
> 修改app.tsx和pages/user/login/index.tsx 2个文件
> 
> 1.修改 src/app.tsx
> 
> `export async function getInitialState(): Promise<{
> settings?: LayoutSettings;
> currentUser?: API.CurrentUser;
> fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
> }> {
> const fetchUserInfo = async () => {
> try {
> // const currentUser = await queryCurrent();
> // return currentUser;
> 
> ```
>   return {
>     name: 'Serati Ma',
>     avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
>     userid: '00000001',
>     email: 'antdesign@alipay.com',
>     signature: '海纳百川，有容乃大',
>     title: '交互专家',
>     group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
>     tags: [
>       {
>         key: '0',
>         label: '很有想法的',
>       },
>       {
>         key: '1',
>         label: '专注设计',
>       },
>       {
>         key: '2',
>         label: '辣~',
>       },
>       {
>         key: '3',
>         label: '大长腿',
>       },
>       {
>         key: '4',
>         label: '川妹子',
>       },
>       {
>         key: '5',
>         label: '海纳百川',
>       },
>     ],
>     notifyCount: 12,
>     unreadCount: 11,
>     country: 'China',
>     access: 'admin',
>     geographic: {
>       province: {
>         label: '浙江省',
>         key: '330000',
>       },
>       city: {
>         label: '杭州市',
>         key: '330100',
>       },
>     },
>     address: '西湖区工专路 77 号',
>     phone: '0752-268888888',
>   };
> 
> 
> } catch (error) {
>   history.push('/user/login');
> }
> return undefined;
> ```
> 
> };
> // 如果是登录页面，不执行
> if (history.location.pathname !== '/user/login') {
> const currentUser = await fetchUserInfo();
> return {
> fetchUserInfo,
> currentUser,
> settings: defaultSettings,
> };
> }
> return {
> fetchUserInfo,
> settings: defaultSettings,
> };
> }
> 
> export const layout: RunTimeLayoutConfig = ({ initialState }) => {
> return {
> rightContentRender: () => ,
> disableContentMargin: false,
> footerRender: () =>
> 
> ,
> onPageChange: () => {
> const { location } = history;
> // 如果没有登录，重定向到 login
> // if (!initialState?.currentUser && location.pathname !== '/user/login') {
> // history.push('/user/login');
> // }
> },
> menuHeaderRender: undefined,
> // 自定义 403 页面
> // unAccessible:
> unAccessible
> ,
> ...initialState?.settings,
> };
> };`
> 1. 修改pages/user/login/index.tsx，增加初始化方法
> 
> `useEffect(()=> {
> setSubmitting(true);
> try {
> // 登录
> // const msg = await fakeAccountLogin({ ...values, type });
> // if (msg.status === 'ok') {
> // message.success('登录成功！');
> // await fetchUserInfo();
> // goto();
> // return;
> // }
> 
> ```
>   setInitialState({
>     ...initialState,
>     currentUser: {
>       name: 'Serati Ma',
>       avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
>       userid: '00000001',
>       email: 'antdesign@alipay.com',
>       signature: '海纳百川，有容乃大',
>       title: '交互专家',
>       group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
>       tags: [
>         {
>           key: '0',
>           label: '很有想法的',
>         },
>         {
>           key: '1',
>           label: '专注设计',
>         },
>         {
>           key: '2',
>           label: '辣~',
>         },
>         {
>           key: '3',
>           label: '大长腿',
>         },
>         {
>           key: '4',
>           label: '川妹子',
>         },
>         {
>           key: '5',
>           label: '海纳百川',
>         },
>       ],
>       notifyCount: 12,
>       unreadCount: 11,
>       country: 'China',
>       access: 'admin',
>       geographic: {
>         province: {
>           label: '浙江省',
>           key: '330000',
>         },
>         city: {
>           label: '杭州市',
>           key: '330100',
>         },
>       },
>       address: '西湖区工专路 77 号',
>       phone: '0752-268888888',
>     },
>   });
> 
>   goto();
>   return;
> 
>   // 如果失败去设置用户错误信息
>   setUserLoginState(msg);
> } catch (error) {
>   message.error('登录失败，请重试！');
> }
> setSubmitting(false);
> ```
> 
> }, []);`

亲测好用 感恩

**Comment by 569202812** [comment]
> > 自问自答，没有找到特别好的办法，通过屏蔽跳转登陆页面，自动填充currentUser信息来解决问题：
> > 修改app.tsx和pages/user/login/index.tsx 2个文件
> > 1.修改 src/app.tsx
> > `export async function getInitialState(): Promise<{
> > settings?: LayoutSettings;
> > currentUser?: API.CurrentUser;
> > fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
> > }> {
> > const fetchUserInfo = async () => {
> > try {
> > // const currentUser = await queryCurrent();
> > // return currentUser;
> > ```
> >   return {
> >     name: 'Serati Ma',
> >     avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
> >     userid: '00000001',
> >     email: 'antdesign@alipay.com',
> >     signature: '海纳百川，有容乃大',
> >     title: '交互专家',
> >     group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
> >     tags: [
> >       {
> >         key: '0',
> >         label: '很有想法的',
> >       },
> >       {
> >         key: '1',
> >         label: '专注设计',
> >       },
> >       {
> >         key: '2',
> >         label: '辣~',
> >       },
> >       {
> >         key: '3',
> >         label: '大长腿',
> >       },
> >       {
> >         key: '4',
> >         label: '川妹子',
> >       },
> >       {
> >         key: '5',
> >         label: '海纳百川',
> >       },
> >     ],
> >     notifyCount: 12,
> >     unreadCount: 11,
> >     country: 'China',
> >     access: 'admin',
> >     geographic: {
> >       province: {
> >         label: '浙江省',
> >         key: '330000',
> >       },
> >       city: {
> >         label: '杭州市',
> >         key: '330100',
> >       },
> >     },
> >     address: '西湖区工专路 77 号',
> >     phone: '0752-268888888',
> >   };
> > 
> > 
> > } catch (error) {
> >   history.push('/user/login');
> > }
> > return undefined;
> > ```
> > 
> > 
> > };
> > // 如果是登录页面，不执行
> > if (history.location.pathname !== '/user/login') {
> > const currentUser = await fetchUserInfo();
> > return {
> > fetchUserInfo,
> > currentUser,
> > settings: defaultSettings,
> > };
> > }
> > return {
> > fetchUserInfo,
> > settings: defaultSettings,
> > };
> > }
> > export const layout: RunTimeLayoutConfig = ({ initialState }) => {
> > return {
> > rightContentRender: () => ,
> > disableContentMargin: false,
> > footerRender: () =>
> > ,
> > onPageChange: () => {
> > const { location } = history;
> > // 如果没有登录，重定向到 login
> > // if (!initialState?.currentUser && location.pathname !== '/user/login') {
> > // history.push('/user/login');
> > // }
> > },
> > menuHeaderRender: undefined,
> > // 自定义 403 页面
> > // unAccessible:
> > unAccessible
> > ,
> > ...initialState?.settings,
> > };
> > };`
> > 
> > 1. 修改pages/user/login/index.tsx，增加初始化方法
> > 
> > `useEffect(()=> {
> > setSubmitting(true);
> > try {
> > // 登录
> > // const msg = await fakeAccountLogin({ ...values, type });
> > // if (msg.status === 'ok') {
> > // message.success('登录成功！');
> > // await fetchUserInfo();
> > // goto();
> > // return;
> > // }
> > ```
> >   setInitialState({
> >     ...initialState,
> >     currentUser: {
> >       name: 'Serati Ma',
> >       avatar: 'https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png',
> >       userid: '00000001',
> >       email: 'antdesign@alipay.com',
> >       signature: '海纳百川，有容乃大',
> >       title: '交互专家',
> >       group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
> >       tags: [
> >         {
> >           key: '0',
> >           label: '很有想法的',
> >         },
> >         {
> >           key: '1',
> >           label: '专注设计',
> >         },
> >         {
> >           key: '2',
> >           label: '辣~',
> >         },
> >         {
> >           key: '3',
> >           label: '大长腿',
> >         },
> >         {
> >           key: '4',
> >           label: '川妹子',
> >         },
> >         {
> >           key: '5',
> >           label: '海纳百川',
> >         },
> >       ],
> >       notifyCount: 12,
> >       unreadCount: 11,
> >       country: 'China',
> >       access: 'admin',
> >       geographic: {
> >         province: {
> >           label: '浙江省',
> >           key: '330000',
> >         },
> >         city: {
> >           label: '杭州市',
> >           key: '330100',
> >         },
> >       },
> >       address: '西湖区工专路 77 号',
> >       phone: '0752-268888888',
> >     },
> >   });
> > 
> >   goto();
> >   return;
> > 
> >   // 如果失败去设置用户错误信息
> >   setUserLoginState(msg);
> > } catch (error) {
> >   message.error('登录失败，请重试！');
> > }
> > setSubmitting(false);
> > ```
> > 
> > 
> > }, []);`
> 
> 亲测好用 感恩

直接注释掉相关逻辑即可吧
