### ISSUE TITLE
为什么初次加载时加载这么多文件呢

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#8010]
@chenshuai2144 
使用antd pro v5开发，没新增别的组件，打包体积大，这个帖子不反馈这个问题了，在umijs里反馈了。

想问问在登录页，感觉好像所有的js css都一次加载了，也没有按需加载啊。是我哪里搞错了吗？
![image](https://user-images.githubusercontent.com/17469220/105858730-a7271900-6011-11eb-9a71-b228fa8c1f69.png)

**Comment by chenshuai2144** [comment]
layout + 用户页面

大小只有 10k 左右。纠结这个可以关掉动态分割


https://umijs.org/config#dynamicimport
