### ISSUE TITLE
dynamicImportSyntax在config文件中配置，提示无效 🧐[问题]

### ISSUE THREAD

**Issue by Alfred-kai** [ant-design/ant-design-pro#8011]
### 🧐 问题描述
项目中，不需要路由按需加载（太吃内存，阿里云打包经常挂掉），打算使用 dynamicImportSyntax，自定义按需加载模块；但是，在config.js中，使用dynamicImportSyntax，运行项目 报 该属性无效。

### 💻 示例代码

dynamicImportSyntax: {}；

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23317023/105933732-f446d180-6089-11eb-9dcc-ba0d43235502.png)

**Comment by chenshuai2144** [comment]
升级一下 umi 吧。应该是 umi 的版本太低导致的
