### ISSUE TITLE
ant-design-pro5 网络请求接口格式自定义规范

### ISSUE THREAD

**Issue by liuxiansheng2018** [ant-design/ant-design-pro#8013]
在项目中我们请求后端的接口格式可能为{code: 200, data: {} , msg: '操作成功' }这种数据格式， 我们如何在返回return response的时候只返回data:{}里面的内容，做统一处理
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/request-cn

看看这里有详细的描写

**Comment by zanmeipaul** [comment]
@chenshuai2144    我也有同样的疑问， {data:{}}  返回的不是data里面的数据，而是最外面的对象。 按照文档上说明的是 名称为data 就会自动转换，我配了 dataField 也不转换

**Comment by cdz620** [comment]
> https://beta-pro.ant.design/docs/request-cn

@chenshuai2144  datafield 已经配置，后端已经按照规范的格式返回，但是得到数据还是最外层的数据，这个是不是有bug？

**Comment by qinrongjun** [comment]
> > https://beta-pro.ant.design/docs/request-cn
> 
> @chenshuai2144 datafield 已经配置，后端已经按照规范的格式返回，但是得到数据还是最外层的数据，这个是不是有bug？

请问解决了吗？感觉这个框架的文档好残废呀。
