### ISSUE TITLE
routers.ts中配置menu下hideInMenu不会生效

### ISSUE THREAD

**Issue by liuxiansheng2018** [ant-design/ant-design-pro#8014]
在ant.design pro5中发现{
    name: 'list.table-list',
    icon: 'table',
    path: '/list',
    menu: {
      hideInMenu: true,
    },
    component: './TableList',
  }, 如果hideInMenu单独放在menu中下， 菜单不会进行隐藏， 而只有// hideInMenu:true 与path 同级的情况下才回隐藏

**Comment by chenshuai2144** [comment]
不支持 menu 这个配置的，你直接使用会有什么问题吗？

**Comment by hfpp2012** [comment]
![image](https://user-images.githubusercontent.com/740643/106488744-fcba6480-64ee-11eb-91b5-8274e42659e3.png)
