### ISSUE TITLE
如何将scripts中配置的脚本放在umi.js之后加载

### ISSUE THREAD

**Issue by yinjiefeng** [ant-design/ant-design-pro#8015]
例如我要引入BizCharts包，该包依赖React。由于该包是在umi.js之前加载的，所以导致加载的时候报错。

配置如下：

 externals: {
    bizcharts: 'BizCharts',
  },
  scripts: [
    'https://g.alicdn.com/code/lib/bizcharts/4.0.16/BizCharts.js',
  ]

html加载顺序如下：

![image](https://user-images.githubusercontent.com/6430116/105961676-ca0d0800-60b9-11eb-9edf-133e93f35416.png)
请问如何把引入的脚本放到umi.js之后加载，我放在document.ejs文件中引入也不行。

**Comment by chenshuai2144** [comment]
umd 都应该在业务之前的，你是什么特俗需要吗？

**Comment by yinjiefeng** [comment]
> umd 都应该在业务之前的，你是什么特俗需要吗？

比如我上面引起的BizCharts.js包依赖reactjs，如果umi.js放在最后，导致加载BizChart.js包的时候提示react的某些方法未定义

**Comment by chenshuai2144** [comment]
那你要把 react react-dom 都extendes掉
不然umijs后面加载window上夜挂不住
