### ISSUE TITLE
🧐[问题]umi ui启动时 tyarn start HOST=0.0.0.0不生效

### ISSUE THREAD

**Issue by anyfeng** [ant-design/ant-design-pro#8016]
### 🧐 问题描述
想要在另外一台机器部署运行，并分享给其他人使用umi ui 在线编辑，但是一直提示出于安全考虑，不允许非本地访问，启动时加上HOST=0.0.0.0 但是我如此执行了，也不生效

**Comment by xyy7260** [comment]
@anyfeng    可以这样尝 
1、先试启动项目后输入： http://localhost:3000/ 
2、 然后在把你项目添加进入
3、点击资产随便添加一个组件进去，就会出现了
