### ISSUE TITLE
🐛[BUG]  https://preview.pro.ant.design中分布表单第二次进入样式错乱

### ISSUE THREAD

**Issue by manman0310** [ant-design/ant-design-pro#8017]
### 📷 复现步骤

第一次进入是正常的，
切换菜单再回来就会出现步骤体样式错乱

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境

### 🚑 其他信息

![1](https://user-images.githubusercontent.com/22827513/106084783-f4160700-6159-11eb-86f9-8d2d03302abb.png)
![4](https://user-images.githubusercontent.com/22827513/106084789-f7a98e00-6159-11eb-8c79-0c2676ac5d3d.png)

**Comment by chenshuai2144** [comment]
已经有同类 issue了，很快就会修掉
