### ISSUE TITLE
👑 [需求] 打包后的静态资源文件支持自定义hash名

### ISSUE THREAD

**Issue by wall-wxk** [ant-design/ant-design-pro#8018]
### 需求描述

打包后的静态资源文件支持自定义hash名，config.ts文件支持以下配置

outputFilename: {
  js: `[contenthash:8].chunk.js`,
  css: `[contenthash:8].chunk.css`,
}

### 解决方案

目前的解决方案是：
在config.ts中增加以下代码

```js
export default defineConfig({
  chainWebpack: (config) => {
    // js资源
    config.output.chunkFilename(`[contenthash:8].chunk.js`);
    config.output.filename(`[contenthash:8].js`);
    // css资源
    config.plugin('extract-css').use(require('mini-css-extract-plugin'), [
      {
        filename: `[contenthash:8].css`,
        chunkFilename: `[contenthash:8].chunk.css`,
      },
    ]);
  }
});
```

### 🚑 打包后的效果

![image](https://user-images.githubusercontent.com/25104791/106109510-964ae480-6184-11eb-8a81-424cdf90c32d.png)

**Comment by wall-wxk** [comment]
### 默认的打包文件名如下

![image](https://user-images.githubusercontent.com/25104791/106110003-21c47580-6185-11eb-9461-11cf650b4dc6.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#chainwebpack

用  chainwebpack 修改一下吧。这个是 hash + 文件切割共同造成的

**Comment by LiuJiangshan** [comment]
现在开始报错了，前段时间还可以
```
Cannot find module 'mini-css-extract-plugin'
```

**Comment by wall-wxk** [comment]
> 现在开始报错了，前段时间还可以，用的是Pro V5
> 
> ```
> Cannot find module 'mini-css-extract-plugin'
> ```
> 
> @wall-wxk @chenshuai2144

```js
chainWebpack: (config) => {
    config.output.chunkFilename(`[contenthash:8].chunk.js`);
    config.output.filename(`[contenthash:8].js`);
    config.plugin('extract-css').use(require('@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin.js'), [
      {
        filename: `[contenthash:8].css`,
        chunkFilename: `[contenthash:8].chunk.css`,
        ignoreOrder: true
      },
    ]);
  },
```

查看了@umijs的文件结构，mini-css-extract-plugin依赖收敛到bundler-webpack内部，改成上述的形式就行了
