### ISSUE TITLE
部署在后台系统的backend目录下，面包屑地址不正常🧐[问题]

### ISSUE THREAD

**Issue by yuandalu** [ant-design/ant-design-pro#8019]
### 🧐 问题描述

项目配置
![image](https://user-images.githubusercontent.com/3860040/106141945-cd80bc00-61ab-11eb-8b16-74bb325024a9.png)
nginx配置
`location ~ /backend/* {
        try_files $uri $uri/ /backend/index.html break;
    }`

正常地址：
https://demo.com/backend/analysis/user
面包屑生成地址：
https://demo.com/backend/backend//analysis/user
可以看到 多了一个 /backend/

求解决，是我配置的问题吗，文档说部署在非根目录下
![image](https://user-images.githubusercontent.com/3860040/106142439-73ccc180-61ac-11eb-9b42-ea8022385ca4.png)

按照文档来的

**Comment by yuandalu** [comment]
补充一下面包屑的位置：
![image](https://user-images.githubusercontent.com/3860040/106142534-919a2680-61ac-11eb-984a-57c7d0026254.png)

**Comment by yuandalu** [comment]
催更，辛苦开发者了

**Comment by Onion17** [comment]
同问，遇到了同样的问题，请问楼主解决了么？ @yuandalu

**Comment by chenshuai2144** [comment]
prolayout新版本已经修复，可以更新后试试
