### ISSUE TITLE
./src/services/api.js Module build failed: Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

### ISSUE THREAD

**Issue by JustYJQ** [ant-design/ant-design-pro#802]
./src/services/api.js
Module build failed: Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

**Comment by chenshuai2144** [comment]
Remove node_modules and reinstall it

**Comment by JustYJQ** [comment]
@chenshuai2144 删除node_modules目录，重新cnpm/npm install 还是同样问题

**Comment by chenshuai2144** [comment]
你克隆的版本不对吧。
这个一般是babel的问题。 roadhog对于这些都是内置的。不用配置。
所以是依赖的问题。 试着用matser的pakage.json在安装一下
