### ISSUE TITLE
🐛[BUG]导航栏的文字出现错位

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design-pro#8021]
### 🐛 bug 描述

导航栏显示错误

### 📷 复现步骤

重新npm install

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/20148964/106223197-ede85f00-621b-11eb-8418-84ab91948845.png)
跟antdesign menu组件显示的一样

### 💻 复现代码

预览示例
![image](https://user-images.githubusercontent.com/20148964/106223304-17a18600-621c-11eb-8e34-18c2ee25035b.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 5.0.0
- Ant Design 版本:  4.11.2
- umi 版本 3.3.7
- 浏览器环境 Microsoft Edge版本 89.0.774.4 (官方内部版本) dev (64 位)
- 开发环境 [e.g. mac OS] Linux

### 🚑 其他信息

在本地部署是没有有问题的，但是放到线上服务器，因为要跑一次npm，所以就发现了导航栏错位的问题
后面排除了一下服务器的问题，跑去看看官方的例子，还是有错位的情况

**Comment by vVvlife** [comment]
antdesign:
![image](https://user-images.githubusercontent.com/20148964/106224923-1a51aa80-621f-11eb-9826-cf68c0b85a72.png)
antdesign Pro:
![image](https://user-images.githubusercontent.com/20148964/106225047-4f5dfd00-621f-11eb-98a2-5b6232039567.png)

**Comment by vVvlife** [comment]
还是有明显的区别的

**Comment by chenshuai2144** [comment]
pro 中 menu 处理过的，因为收起的时候变得很小，看看这里

https://pro.ant.design/blog/layout-new-style-cn

设计师希望紧凑一点

**Comment by vVvlife** [comment]
> pro 中 menu 处理过的，因为收起的时候变得很小，看看这里
> 
> https://pro.ant.design/blog/layout-new-style-cn
> 
> 设计师希望紧凑一点

明白，可是二级菜单的文字应该和一级菜单的文字要对齐吧🤣

**Comment by vVvlife** [comment]
更新pro-layout@6.15.4后，问题已修复

**Comment by Wmstone** [comment]
@vVvlife 请问一下后来对齐了么？我看官方现在还是不对齐的，该如何处理呢

**Comment by vVvlife** [comment]
> @vVvlife 请问一下后来对齐了么？我看官方现在还是不对齐的，该如何处理呢

已经对齐了，我close了，更新一下pro-layout就对齐了

**Comment by vVvlife** [comment]
> @vVvlife 请问一下后来对齐了么？我看官方现在还是不对齐的，该如何处理呢

我今天更新到了@6.19.3的版本就会出现这个问题，然后回退到6.18.0版本并没有发现这个问题

**Comment by vVvlife** [comment]
@chenshuai2144 问题再次复现
版本：pro-layout 6.19.3

**Comment by Wmstone** [comment]
@vVvlife 现在应该需要自己去对齐了，官方的设计就是非对齐的，需要自己在Layout中重新渲染
