### ISSUE TITLE
🐛[BUG]  ant-design-pro v4.5.0 权限管理问题

### ISSUE THREAD

**Issue by dealdot** [ant-design/ant-design-pro#8024]
### 🐛 bug 描述

给routes.js 相应路由添加authority, 比如  authority: ['admin']
但用user登录的时候，虽然menu侧边栏没有这个menuItem了，但是直接访问对应的pathname却依然可以访问

### 📷 复现步骤

yarn create umi app
yarn
yarn  start

### 🏞 期望结果

期望没有权限的component在浏览器直接访问相应pathname的时候直接渲染403组件，而不是渲染了对应的组件

### © 版本信息

- Ant Design Pro 版本:  4.5.0
- umi 版本  3.3.3
- 浏览器环境  chrome
- 开发环境  windows10

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19355027/106248068-6ca8c080-624b-11eb-9ceb-90eb6cc87831.png)

**Comment by 2010hexi** [comment]
也是发现这个问题，直接通过链接 就可以去访问了，  加了  authority: ['admin'] ，只是 左边菜单栏 不显示而已

**Comment by caijiang** [comment]
尝试修改了 _BasicLayout.tsx_ 自己用了下还成……

```typescript
  // get children authority
  // const authorized = useMemo(
  //   () =>
  //     getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
  //       authority: undefined,
  //     },
  //   [location.pathname],
  // );
  // 从菜单中获取权限的想法或者算法显然存在问题，此处更新为从路由中获取。
  const { route: routeForAuthorized } = props;
  const authorized = useMemo(() => {
    const path = location.pathname!;
    // 必然匹配了
    const list = [routeForAuthorized];
    let current = routeForAuthorized;
    while (current) {
      if (!current.children) break;
      current = current.children.find(
        (it) => it.path && it.path.startsWith(path),
      ) as ProLayoutProps['route'] & {
        authority: string[];
      };
      if (!current) break;
      list.unshift(current);
    }
    return {
      authority: list.map((it) => it.authority).find((it) => it),
    };
  }, [routeForAuthorized, location.pathname]);
```

**Comment by 2010hexi** [comment]
> 尝试修改了 _BasicLayout.tsx_ 自己用了下还成……
> 
> ```ts
>   // get children authority
>   // const authorized = useMemo(
>   //   () =>
>   //     getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
>   //       authority: undefined,
>   //     },
>   //   [location.pathname],
>   // );
>   // 从菜单中获取权限的想法或者算法显然存在问题，此处更新为从路由中获取。
>   const { route: routeForAuthorized } = props;
>   const authorized = useMemo(() => {
>     const path = location.pathname!;
>     // 必然匹配了
>     const list = [routeForAuthorized];
>     let current = routeForAuthorized;
>     while (current) {
>       if (!current.children) break;
>       current = current.children.find(
>         (it) => it.path && it.path.startsWith(path),
>       ) as ProLayoutProps['route'] & {
>         authority: string[];
>       };
>       if (!current) break;
>       list.unshift(current);
>     }
>     return {
>       authority: list.map((it) => it.authority).find((it) => it),
>     };
>   }, [routeForAuthorized, location.pathname]);
> ```

copy 了 你的代码去测试，发现 隐藏了 菜单，但是通过链接还是一样可以访问。 另外， authority 放在 子菜单， 还是会显示
![image](https://user-images.githubusercontent.com/43429845/107207928-dc812d00-6a3b-11eb-8aee-e6286fb9e7c8.png)

![image](https://user-images.githubusercontent.com/43429845/107208088-10f4e900-6a3c-11eb-8e87-e8fa6d6ea1fb.png)

**Comment by caijiang** [comment]
> > 尝试修改了 _BasicLayout.tsx_ 自己用了下还成……
> > ```ts
> >   // get children authority
> >   // const authorized = useMemo(
> >   //   () =>
> >   //     getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
> >   //       authority: undefined,
> >   //     },
> >   //   [location.pathname],
> >   // );
> >   // 从菜单中获取权限的想法或者算法显然存在问题，此处更新为从路由中获取。
> >   const { route: routeForAuthorized } = props;
> >   const authorized = useMemo(() => {
> >     const path = location.pathname!;
> >     // 必然匹配了
> >     const list = [routeForAuthorized];
> >     let current = routeForAuthorized;
> >     while (current) {
> >       if (!current.children) break;
> >       current = current.children.find(
> >         (it) => it.path && it.path.startsWith(path),
> >       ) as ProLayoutProps['route'] & {
> >         authority: string[];
> >       };
> >       if (!current) break;
> >       list.unshift(current);
> >     }
> >     return {
> >       authority: list.map((it) => it.authority).find((it) => it),
> >     };
> >   }, [routeForAuthorized, location.pathname]);
> > ```
> 
> copy 了 你的代码去测试，发现 隐藏了 菜单，但是通过链接还是一样可以访问。 另外， authority 放在 子菜单， 还是会显示
> ![image](https://user-images.githubusercontent.com/43429845/107207928-dc812d00-6a3b-11eb-8aee-e6286fb9e7c8.png)
> 
> ![image](https://user-images.githubusercontent.com/43429845/107208088-10f4e900-6a3c-11eb-8e87-e8fa6d6ea1fb.png)

调整了下，之前我只在工作在一级path,多级path就凉透了。
```typescript
// 从菜单中获取权限的想法或者算法显然存在问题，此处更新为从路由中获取。
  const { route: routeForAuthorized } = props;
  const authorized = useMemo(() => {
    const path = location.pathname!;
    // 必然匹配了
    const list = [routeForAuthorized];
    let current = routeForAuthorized;
    while (current) {
      if (!current.children) break;
      current = current.children
        .filter((it) => it.path)
        .sort((a, b) => b.path!.length - a.path!.length)
        .find((it) => matchPath(path, it)) as ProLayoutProps['route'] & {
        authority: string[];
      };
      if (!current) break;
      list.unshift(current);
    }
    return {
      authority: list.map((it) => it.authority).find((it) => it),
    };
  }, [routeForAuthorized, location.pathname]);
```
matchPath umi的
```typescript
import { matchPath } from 'umi';
```

**Comment by firstmetcs** [comment]
如果是从后台获取的menuData应该怎么写呢？ @caijiang

**Comment by caijiang** [comment]
> 如果是从后台获取的menuData应该怎么写呢？ @caijiang

虽然未曾试过从远端获取menuData,但我估计最终还是通过props的方式传递下去，所以应该没有区别。

**Comment by youcannot** [comment]
我的思路是，可以把 完整路由从prop中拿出来，并且把子路由也放到外层，这样就的到类似 全一级的路由表，然后再 location.pathname 改变的时候，找出权限
// 完整 类似一级路由表
let planArr: any = []
    /** 获取完整路由表 */
    const getAllRoute = (routeList: any) => {
        routeList.forEach((item: any) => {
            item.children ? (getAllRoute(item.children),planArr.push(item)) : planArr.push(item)
        })
    }
// 找权限
const authorized = useMemo(
        () => {
            getAllRoute(route.children)
            let index: any = planArr?.findIndex(item => item.path == location.pathname)
            return  index > -1 ? planArr[index].authority: []
        },
        [location.pathname],
    );
<Authorized authority={authorized} noMatch={noMatch}>
                {children}
</Authorized>

**Comment by bhavesh-webosmotic** [comment]
Routes params are passed through props to component, so authority is available in --> props.route.authority

Previously:

```javascript

 const authorized = useMemo(() => {
   const em = getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
     authority: [],
   };
   return em;
 }, [location.pathname]);

<Authorized authority={authorized.authority} noMatch={noMatch}>
   {children}
</Authorized>
```

I was able to get it working by updating code to:

```javascript
<Authorized authority={props.route.authority ?? []} noMatch={noMatch}>
   {children}
</Authorized>
```

**Comment by lukaiqi** [comment]
> Routes params are passed through props to component, so authority is available in --> props.route.authority
> 
> Previously:
> 
> ```js
>  const authorized = useMemo(() => {
>    const em = getMatchMenu(location.pathname || '/', menuDataRef.current).pop() || {
>      authority: [],
>    };
>    return em;
>  }, [location.pathname]);
> 
> <Authorized authority={authorized.authority} noMatch={noMatch}>
>    {children}
> </Authorized>
> ```
> 
> I was able to get it working by updating code to:
> 
> ```js
> <Authorized authority={props.route.authority ?? []} noMatch={noMatch}>
>    {children}
> </Authorized>
> ```

if i do this,all the page which not set authority prop is unable to vist,show 403 page

**Comment by bhavesh-webosmotic** [comment]
Remove [ ] and try

**Comment by bhavesh-webosmotic** [comment]
in my case, if authority is missing then no one allowed to see that page. so I have added **[]** because that wrapper is only for authorized users.

**Comment by lukaiqi** [comment]
> 就我而言，如果缺少权限，则没有人允许查看该页面。所以我添加了**[]**因为该包装器仅适用于授权用户。



> 删除 [ ] 并尝试
> `<Authorized authority={props.route?.authority} noMatch={noMatch}> {children} </Authorized>`
> 
> 因为如果权威不在场的手段。它应该为空，在前一种情况下，我们传递**[]（空数组）**意味着没有人允许看到该页面。



> Remove [ ] and try
> `<Authorized authority={props.route?.authority} noMatch={noMatch}> {children} </Authorized>`
> 
> because if the authority is not present means. it should be null and in the previous case, we are passing **[] (blank array)** means no one allowed to see that page.
I have changed my code to this,but if the router not set authority prop or set to [] ,  this will all page show 403,but left side menu can correct show,
I want to achieve :
   if 

> Remove [ ] and try
> `<Authorized authority={props.route?.authority} noMatch={noMatch}> {children} </Authorized>`
> 
> because if the authority is not present means. it should be null and in the previous case, we are passing **[] (blank array)** means no one allowed to see that page.

I understand your means,but this **props.route.authority** get the router top authority,cant not get the sub-page authority,any sub page can be visited

**Comment by lukaiqi** [comment]
> Remove [ ] and try
> `<Authorized authority={props.route?.authority} noMatch={noMatch}> {children} </Authorized>`
> 
> because if the authority is not present means. it should be null and in the previous case, we are passing **[] (blank array)** means no one allowed to see that page.

![image](https://user-images.githubusercontent.com/32565940/123593527-320a7a80-d821-11eb-9a91-36ae8a254ae7.png)
I changed this to
 `authority: location.pathname === '/' ? undefined : [],`
and 
 `<Authorized authority={authorized.authority} noMatch={noMatch}>`
use the demo code to change the question,until now not found other question
and I changed the getAythority method,when not authority set it to []
![image](https://user-images.githubusercontent.com/32565940/123594086-d8ef1680-d821-11eb-84c7-3ed582d69afe.png)
