### ISSUE TITLE
🧐[问题]对于blog里面提到的新特性，是已经发布版本可以使用了吗？还是在未来才可以使用？

### ISSUE THREAD

**Issue by wanliin** [ant-design/ant-design-pro#8025]
![image](https://user-images.githubusercontent.com/77980075/106377064-50d12600-63d5-11eb-8a79-4567eb2d2561.png)
随着 antd 正式版的发布，layout 也将迎来全新的设计风格。新的风格仍然会以科技的风格为主，在原来的基础上优化尺寸和体验细节，设计更加简洁，匹配更多业务场景。

**Comment by wanliin** [comment]
![image](https://user-images.githubusercontent.com/77980075/106377098-7a8a4d00-63d5-11eb-8a7c-aef7ab59285a.png)
类似于菜单过长展示tooltip，我在文档找不到相关的api

**Comment by chenshuai2144** [comment]
这个是 antd 做的，你升级一下antd的版本就能看到

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/

文档在这里

**Comment by wiredgril666** [comment]
依旧是没看到，https://beta-pro.ant.design，菜单过长展示tooltip。相关api..
