### ISSUE TITLE
🧐[问题] 关于v5的动态菜单权限

### ISSUE THREAD

**Issue by jipfqf** [ant-design/ant-design-pro#8026]
首页我在config.ts中把routes禁用了，也就是routes.ts文件不写路由
然后按照文档上写的从后台取数据，在fetchUserInfo方法中从后台取数据，放currentUser里面，menuData再取值
把后台返回的权限处理了下后确实能显示页面
![image](https://user-images.githubusercontent.com/22951659/106387038-d4f5ce80-6412-11eb-9717-fe81137f0c06.png)

![image](https://user-images.githubusercontent.com/22951659/106386071-2e0f3380-640e-11eb-9126-52d1f422ee1a.png)这个是处理菜单，但是遇到了下面几个问题
1、redirect属性好像没用，怎么试都不行
2、右上角个人中心进不去，登录页面和个人中心页面都是手动处理的，不明白为啥一个能进一个不行
3、点退出后登录页面会变成两种情况：①在登录后刷新出来菜单点退出
![image](https://user-images.githubusercontent.com/22951659/106386768-8dbb0e00-6411-11eb-8ee9-bdc95d7c95ba.png)上面header变成白条，②未刷新出菜单直接点退出
![image](https://user-images.githubusercontent.com/22951659/106386820-c529ba80-6411-11eb-831f-8858bc32333f.png)上面header就是黑背景

我看以前的issues说必须在routes.ts里面配置路由，但是这样路由全部写出来，虽然不显示菜单但是知道路径就能进去，access又得写死角色名称，后台角色名称肯定是动态添加的啊，感觉这块挺乱的

**Comment by chenshuai2144** [comment]
首先区分一下什么是 路由，什么是菜单

## 路由

路由一般是用来做路径选择的，在react 中 路由也是状态的一种，他就是在控制在什么路径下选择什么。umi 中路由是根据 config.ts 中 的 routers 来生成，routers  代表了在什么路径下展示什么组件，一般来说我们会选择 一个 pages 中的页面来进行展示。

**Comment by jipfqf** [comment]
> 首先区分一下什么是 路由，什么是菜单
> 
> ## 路由
> 路由一般是用来做路径选择的，在react 中 路由也是状态的一种，他就是在控制在什么路径下选择什么。umi 中路由是根据 config.ts 中 的 routers 来生成，routers 代表了在什么路径下展示什么组件，一般来说我们会选择 一个 pages 中的页面来进行展示。
> 
> routers 中的路由配置一般会生成 react-router 的配置, 一般来说配置会生成如下的代码。
> 
> ```
> <Switch>
>   <Route path="/">
>      <Redirect to="/dashboard" />
>    </Route>
>   <Route path="/about">
>     <About />
>   </Route>
>   <Route path="/topics">
>     <Topics />
>   </Route>
>   <Route path="/">
>     <Home />
>   </Route>
> </Switch>
> ```
> 
> 同时umi中还会根据菜单分析需要打包哪些文件，所以路由配置是必须的。
> 
> ## 菜单
> 上面的路由中我们可以看出来，路由是管理什么路径显示什么的，导航菜单的功能是点击之后去哪里的，两者的功能有一些重叠，所以在 pro 中我们利用路由来生成了菜单，所以路由中要配置 name icon 等配置，这么配置会生成一些数据帮助我们生成菜单。
> 
> ```
> export default [
>   {
>     path: '/product',
>     // 不展示菜单
>     menuRender: false,
>     name: '产品管理',
>   },
>   {
>     path: '/list/:id',
>     // 编辑的时候使用顶部菜单
>     layout: 'top',
>     name: '列表详情',
>     parentKeys: ['/product'],
>   },
> ];
> ```
> 
> 所以菜单时可以动态的，因为菜单时纯粹的运行时，但是路由时编译时。所以 redirect 是无法生效的。

那这样设计的话后台返回动态角色，现在routes.ts里面要怎么对应

**Comment by JinShuohang** [comment]
哥们，动态获取角色的问题你解决了吗？有好的解决思路嘛？

**Comment by jipfqf** [comment]
> 哥们，动态获取角色的问题你解决了吗？有好的解决思路嘛？

已放弃

**Comment by PathFun** [comment]
> 首先区分一下什么是 路由，什么是菜单
> 
> ## 路由
> 路由一般是用来做路径选择的，在react 中 路由也是状态的一种，他就是在控制在什么路径下选择什么。umi 中路由是根据 config.ts 中 的 routers 来生成，routers 代表了在什么路径下展示什么组件，一般来说我们会选择 一个 pages 中的页面来进行展示。
> 
> routers 中的路由配置一般会生成 react-router 的配置, 一般来说配置会生成如下的代码。
> 
> ```
> <Switch>
>   <Route path="/">
>      <Redirect to="/dashboard" />
>    </Route>
>   <Route path="/about">
>     <About />
>   </Route>
>   <Route path="/topics">
>     <Topics />
>   </Route>
>   <Route path="/">
>     <Home />
>   </Route>
> </Switch>
> ```
> 
> 同时umi中还会根据菜单分析需要打包哪些文件，所以路由配置是必须的。
> 
> ## 菜单
> 上面的路由中我们可以看出来，路由是管理什么路径显示什么的，导航菜单的功能是点击之后去哪里的，两者的功能有一些重叠，所以在 pro 中我们利用路由来生成了菜单，所以路由中要配置 name icon 等配置，这么配置会生成一些数据帮助我们生成菜单。
> 
> ```
> export default [
>   {
>     path: '/product',
>     // 不展示菜单
>     menuRender: false,
>     name: '产品管理',
>   },
>   {
>     path: '/list/:id',
>     // 编辑的时候使用顶部菜单
>     layout: 'top',
>     name: '列表详情',
>     parentKeys: ['/product'],
>   },
> ];
> ```
> 
> 所以菜单时可以动态的，因为菜单时纯粹的运行时，但是路由时编译时。所以 redirect 是无法生效的。

动态路由是可以实现的，vue的antDesign Pro 已经有一套完整的动态路由方案， 对于您说的编译问题，可以提前引入，只能说这套代码似乎还没有提供类似的方案

**Comment by chenshuai2144** [comment]
我理解了。
你说的动态路由是的 react-router 的配置动态修改，文件是被全量打包的，没有做按需加载。
你应该需要的是这个

https://umijs.org/docs/runtime-config#patchroutes-routes-
