### ISSUE TITLE
🧐[问题]左上角的logo怎么设置它的href呢？

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#8027]
### 🧐 问题描述

我这边进入网页默认的router是/next/welcome， 如果点击了logo的话router会是/  ，就会进入我们之前那个老版本平台。 请问怎么设置这个href呢？
我看了一下 menuHeaderRender不行，会是这样
![image](https://user-images.githubusercontent.com/23183393/106414776-72d7b080-6488-11eb-9b54-b75ac359753e.png)
![image](https://user-images.githubusercontent.com/23183393/106414798-7cf9af00-6488-11eb-8002-5d4a950c9708.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23183393/106414500-ac5bec00-6487-11eb-91f2-e5cd62ad29eb.png)
![image](https://user-images.githubusercontent.com/23183393/106414514-b8e04480-6487-11eb-9a2d-f98361ca81ce.png)

**Comment by hfpp2012** [comment]
哪个版本的 antd pro，v5 的话，有两种方法可以修改

![image](https://user-images.githubusercontent.com/740643/106486656-d4316b00-64ec-11eb-8a18-d5f643a7a17c.png)

第二种：

![image](https://user-images.githubusercontent.com/740643/106486852-0c38ae00-64ed-11eb-9b7f-a99945d2a4e1.png)

![image](https://user-images.githubusercontent.com/740643/106486893-178bd980-64ed-11eb-8003-47d7c1f110a7.png)

**Comment by xyy7260** [comment]
@hfpp2012    😆谢谢， 你可能理解错我的意思了， 我是说修改 href 不是修改logo。

**Comment by hfpp2012** [comment]
@xyy7260 好的，惭愧的

**Comment by chenshuai2144** [comment]
onMenuHeaderClick

用这个呢?  layout@6 已经去掉了

**Comment by xyy7260** [comment]
@chenshuai2144   onMenuHeaderClick不行， 点击时候已跳转了 无法在这里面做操作

menuHeaderRender :  使用后会在这里多出一个title和logo
![image](https://user-images.githubusercontent.com/23183393/106706502-c255e200-662a-11eb-8da9-d8480ab351f6.png)
![image](https://user-images.githubusercontent.com/23183393/106706763-1f519800-662b-11eb-8391-47422dc93832.png)

**Comment by xyy7260** [comment]
@chenshuai2144  我准备做新的项目从新安装了一次 v5版本， 从新按照你给的方式去尝试没问题
我怀疑是不是版本的问题造成的呢？  我把我package 贴出

{
  "name": "ant-design-pro",
  "version": "5.0.0-alpha.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "clean": "rm -rf dist/",
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run site && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "cp CNAME ./dist/ && gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier --check \"**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "prettier": "prettier -c --write \"**/*\"",
    "start": "umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none umi dev",
    "start:no-mock": "cross-env MOCK=none umi dev",
    "start:no-ui": "cross-env UMI_UI=none umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc",
    "postbuild": "cp -Rf ./dist ../../../server/nextbuild/ && rm -rf node_modules/",
    "prebuild": "npm install --unsafe-perm"
  },
  "husky": {
    "hooks": {}
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "6.0.0-3",
    "@ant-design/pro-table": "^2.2.0",
    "@apollo/client": "^3.3.6",
    "@elastic/datemath": "^5.0.3",
    "@elastic/eui": "^31.0.0",
    "@progress/kendo-theme-default": "^4.19.0",
    "@progress/kendo-ui": "^2020.2.513",
    "@rjsf/antd": "^2.4.0",
    "@rjsf/core": "^2.4.0",
    "@searchkit/apollo-resolvers": "^3.0.0-canary.12",
    "@searchkit/client": "^3.0.0-canary.19",
    "@searchkit/elastic-ui": "^3.0.0-canary.12",
    "ajv-i18n": "^3.5.0",
    "antd": "^4.8.0",
    "antd-theme-generator": "^1.2.4",
    "axios": "^0.19.2",
    "compression-webpack-plugin": "^4.0.0",
    "dayjs": "^1.8.30",
    "echarts": "^4.8.0",
    "echarts-for-react": "^2.0.16",
    "graphql": "^15.4.0",
    "lodash": "^4.17.15",
    "moment": "^2.25.3",
    "node-sass": "^4.14.1",
    "omit.js": "^1.0.2",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-countup": "^4.3.3",
    "react-dom": "^16.8.6",
    "react-highlight-words": "^0.16.0",
    "react-json-tree": "^0.11.2",
    "sass-loader": "^8.0.2",
    "searchkit": "^2.4.1",
    "umi": "^3.1.0",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^25.1.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^5.0.13",
    "@umijs/fabric": "^2.0.5",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.0-beta.2",
    "@umijs/plugin-sass": "^1.1.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.24",
    "@umijs/preset-ui": "^2.1.11",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "eslint": "^6.8.0",
    "express": "^4.17.1",
    "gh-pages": "^2.0.1",
    "husky": "^4.0.7",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "puppeteer-core": "^2.1.1",
    "stylelint": "^13.0.0",
    "url-loader": "^4.1.0"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}

**Comment by chenshuai2144** [comment]
| headerTitleRender | 自定义头标题的方法,mix 模式下生效 | `(logo,title,props)=>ReactNode` | - |

试试这个，用了mix 模式有一点特俗

**Comment by xyy7260** [comment]
@caicaishmily  ok 我把config/defaultSettings文件里的layout 从mix更换成side 解决了

**Comment by ISBN9527** [comment]
为啥我点击跳转不过去？
在mix模式下
` headerTitleRender: (logo, title) => {
      return (
        <a
          onClick={() => {
            history.push('/admin/sub-page2');
          }}
        >
          {' '}
          {logo} {title}
        </a>
      );
    },`
