### ISSUE TITLE
🐛[BUG] 为什么 publicPath  必须要 “/” 开头？

### ISSUE THREAD

**Issue by jsonchou** [ant-design/ant-design-pro#8028]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- - latest
- umi 版本
- - latest
- 浏览器环境 
- - latest
- 开发环境 [e.g. mac OS]
- - latest

### 🚑 其他信息

项目构建：
```js 
Validate config "publicPath" failed, config.publicPath must end with /.
Error: config.publicPath must end with /.
```

页面地址：
https://www.demo.com/index.html

静态资源地址：
https://demo.cdn.com/ddd.mirlRDq.js

为什么 publicPath  必须要 “/” 开头？

dist/index.html 里面的各种资源路径，如何修正成 https://demo.cdn.com 前缀呢？难道要做 web server 端的修改？

**Comment by Liuqing650** [comment]
@jsonchou 解决了吗？不知道为啥要多个 / 的校验
