### ISSUE TITLE
关于从服务器拉取菜单的问题 beta2

### ISSUE THREAD

**Issue by MikeMaldini** [ant-design/ant-design-pro#8029]
根据文档修改后 layout 存在异常提示，请问改如何修改？
<img width="944" alt="截屏2021-02-01 下午10 59 04" src="https://user-images.githubusercontent.com/29230494/106475604-1654af80-64e1-11eb-8c85-a444a9b5eab9.png">
我已经按照教程来写了：
<img width="1084" alt="截屏2021-02-01 下午11 00 02" src="https://user-images.githubusercontent.com/29230494/106475721-38e6c880-64e1-11eb-9275-42e77d8d3a85.png">

**Comment by chenshuai2144** [comment]
看提示是有个不能设置为 undfinde 的值被设置为 undefinde 了

**Comment by chenshuai2144** [comment]
重新安装了一下发现没什么问题，估计是你的依赖安装失败了
