### ISSUE TITLE
Building ant-design-pro with electron

### ISSUE THREAD

**Issue by anwfr** [ant-design/ant-design-pro#803]
Hello,
Any hint to get ant-design-pro built with electron? 
Should I build separately ant-design-pro, then integrate build result with electron, or did anyone succeed to build it together?
Best regards

**Comment by chenshuai2144** [comment]
dva is not suitable for using electron.
You need to build it yourself using webpack

**Comment by anuxs** [comment]
I have the same require . electron + ant-design-pro .
