### ISSUE TITLE
🧐[问题]Antd Pro V5 如何修改或者替换全局 Loading

### ISSUE THREAD

**Issue by liuht777** [ant-design/ant-design-pro#8030]
### 🧐 问题描述

Antd Pro V5 如何修改或者替换全局 Loading，始终找不到替换的入口，单纯的替换个颜色并不是想要的。

**Comment by drizzlesconsin** [comment]
1. https://github.com/ant-design/ant-design-pro/blob/master/src/pages/document.ejs#L194-L201

2. https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L25-L27

3. `src/app.tsx`
```ts
/** 获取用户信息比较慢的时候会展示一个 loading */
export const initialStateConfig = {
  loading: <PageLoading />,
};
```

**Comment by liuht777** [comment]
> 1. https://github.com/ant-design/ant-design-pro/blob/master/src/pages/document.ejs#L194-L201
> 2. https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L25-L27
> 3. `src/app.tsx`
> 
> ```ts
> /** 获取用户信息比较慢的时候会展示一个 loading */
> export const initialStateConfig = {
>   loading: <PageLoading />,
> };
> ```

感谢，改天试试
