### ISSUE TITLE
关于antd在externals中的配置问题

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#8031]
基于antd pro v5开发，umi是最新版，为了减少打包体积，想把antd作为外部文件访问，配置如下：
![image](https://user-images.githubusercontent.com/17469220/106550955-319fd900-653a-11eb-8880-0d0e8042aa4e.png)

build后，antd依然在包里，看了以前类似的问题，说要移走按需加载的配置，不知道怎么弄，求指教

**Comment by chenshuai2144** [comment]
babel-import-plugin 这个插件要关掉，

我觉得你不需要配置antd，一般都是200k，还每周发版本。

你可以把react moment g2 这些去掉，就稳定了

**Comment by codedart2018** [comment]
> babel-import-plugin

babel-import-plugin 插件如何关掉呢
