### ISSUE TITLE
🐛[BUG]IE11 报错 SCRIPT1004: 缺少 ';'

### ISSUE THREAD

**Issue by azx1985** [ant-design/ant-design-pro#8032]
### 🐛 bug 描述
项目里已经配置了targets: { ie: 11 }，在谷歌和火狐中都运行正常，在IE11里console  “报错SCRIPT1004: 缺少 ';'  umi.js (111326,14)”

看umi.js里面
 if ((a instanceof Map) && (b instanceof Map)) {
      if (a.size !== b.size) return false;
      for (i of a.entries())
        if (!b.has(i[0])) return false;
      for (i of a.entries())
        if (!equal(i[1], b.get(i[0]))) return false;
      return true;
    }
其中有for (i of a.entries())这行错误，原因应该是在IE中不支持  of 的这种遍历方法；

### 🏞 期望结果

能正常打包运行于IE中

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你能找到这个库是谁些的？

**Comment by seiyasolo** [comment]
我也遇到了- -

**Comment by chenshuai2144** [comment]
能定位到具体是哪个库吗？我们修改一下

**Comment by azx1985** [comment]
/***/ "./node_modules/fast-deep-equal/es6/react.js":
/*!***************************************************!*\
  !*** ./node_modules/fast-deep-equal/es6/react.js ***!
  \***************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


// do not edit .js files directly - edit src/index.jst


  var envHasBigInt64Array = typeof BigInt64Array !== 'undefined';


module.exports = function equal(a, b) {
  if (a === b) return true;

  if (a && b && typeof a == 'object' && typeof b == 'object') {
    if (a.constructor !== b.constructor) return false;

    var length, i, keys;
    if (Array.isArray(a)) {
      length = a.length;
      if (length != b.length) return false;
      for (i = length; i-- !== 0;)
        if (!equal(a[i], b[i])) return false;
      return true;
    }


    if ((a instanceof Map) && (b instanceof Map)) {
      if (a.size !== b.size) return false;
      for (i of a.entries())
        if (!b.has(i[0])) return false;
      for (i of a.entries())
        if (!equal(i[1], b.get(i[0]))) return false;
      return true;
    }

    if ((a instanceof Set) && (b instanceof Set)) {
      if (a.size !== b.size) return false;
      for (i of a.entries())
        if (!b.has(i[0])) return false;
      return true;
    }

    if (ArrayBuffer.isView(a) && ArrayBuffer.isView(b)) {
      length = a.length;
      if (length != b.length) return false;
      for (i = length; i-- !== 0;)
        if (a[i] !== b[i]) return false;
      return true;
    }


    if (a.constructor === RegExp) return a.source === b.source && a.flags === b.flags;
    if (a.valueOf !== Object.prototype.valueOf) return a.valueOf() === b.valueOf();
    if (a.toString !== Object.prototype.toString) return a.toString() === b.toString();

    keys = Object.keys(a);
    length = keys.length;
    if (length !== Object.keys(b).length) return false;

    for (i = length; i-- !== 0;)
      if (!Object.prototype.hasOwnProperty.call(b, keys[i])) return false;

    for (i = length; i-- !== 0;) {
      var key = keys[i];

      if (key === '_owner' && a.$$typeof) {
        // React-specific: avoid traversing React elements' _owner.
        //  _owner contains circular references
        // and is not needed when comparing the actual elements (and not their owners)
        continue;
      }

      if (!equal(a[key], b[key])) return false;
    }

    return true;
  }

  // true if both NaN, false otherwise
  return a!==a && b!==b;
};

**Comment by chenshuai2144** [comment]
看到了，打开一下这个吧，可以把 nodemodules 也更新掉

https://umijs.org/config#nodemodulestransform

**Comment by Zhang-haohua** [comment]
> 看到了，打开一下这个吧，可以把 nodemodules 也更新掉
> 
> https://umijs.org/config#nodemodulestransform

大佬，我的umi是2.x版本的，你说的这个属性是3版本的，**是不是必须得升级**，更改配置
`nodeModulesTransform: {
    type: 'none',
  },`

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF


看看这个文档吧， ie11 兼容是个系统功能

**Comment by hao-yue** [comment]
请问楼主最后问题解决了吗，怎么解决的呀

**Comment by azx1985** [comment]
没解决

**Comment by observerss** [comment]
我碰到了同样的问题，这样配就解决了

```javascript
{
    targets: { ie: 11 },
    esbuild: { target: 'es5' },
    nodeModulesTransform: { type: 'all' },
}
```

nodeModulesTransform必须要先改成all，这样modules才会进行翻译
