### ISSUE TITLE
我修改了less的样式后无法更新，需要手动刷新网页后才出现🧐[问题]

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#8035]
### 🧐 问题描述

- 我更改了字体的颜色，保存后网页字体颜色没有改变，需要手动刷新才会出现改变后的样式。

- 我更改了字保存后网页会更新字，但是修改样色不会更新。我不知道是不是热更无法修改样式

- 我尝试删除了.umi 和.cache 文件还是一样，

- antD-pro : v5版本
- umi : 3.1.0
- 开发系统: mac

**Comment by chenshuai2144** [comment]
是不是大小写写错了，一般热更新出错都是因为这个原因

**Comment by xyy7260** [comment]
@chenshuai2144    刚刚对了一下 router component 于文件名一模一样都是大写的。不过有一点很好奇我更改了样式，控制台出现[HMR] Detected local css modules. Reload all css  说明已经检测更新了，实际还是需要手动刷新

**Comment by chenshuai2144** [comment]
控制台来一下，是不是socket 断了

**Comment by xyy7260** [comment]
![Uploading image.png…]()

**Comment by xyy7260** [comment]
<img width="1535" alt="7F93C8BE-32A7-440C-8740-DE17F84C77DC" src="https://user-images.githubusercontent.com/23183393/106746216-30b39800-665d-11eb-835a-fac438824644.png">

**Comment by chenshuai2144** [comment]
估计是加载顺序的问题了，你提升一下优先级试试

**Comment by xyy7260** [comment]
@chenshuai2144   怎么提升呢， 把引入less和scss 放入最顶部？

**Comment by xyy7260** [comment]
@chenshuai2144 
![C3E4A48F-0A23-4432-AFDF-7B6DCF93974E](https://user-images.githubusercontent.com/23183393/106746343-5e98dc80-665d-11eb-9677-f5237ecd9356.gif)

**Comment by chenshuai2144** [comment]
!important 直接用这个

**Comment by xyy7260** [comment]
@chenshuai2144  好我明天试一试

**Comment by xyy7260** [comment]
还是不行

**Comment by xyy7260** [comment]
@chenshuai2144  我知道什么情况了主要是我这边自己在 config.ts里面配置了chainWebpack  extract-css 造成的， 我暂时屏蔽了修改css就会马上出现。
