### ISSUE TITLE
🧐[问题]config.ts文件layout: {name: 'Ant Design Pro'}这个name字段是应用哪里的配置？

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design-pro#8036]
请问🧐[问题]config.ts文件layout: {name: 'Ant Design Pro'}这个name字段是应用哪里的配置？

**Comment by chenshuai2144** [comment]
plugin-layout 的。

http://localhost:8000/zh-CN/plugins/plugin-layout
