### ISSUE TITLE
🐛[BUG] antd pro V5 中，css文件重复打包

### ISSUE THREAD

**Issue by liucong1** [ant-design/ant-design-pro#8037]
### 📷 复现步骤
直接在V5的Demo页面多次点击菜单来切换路由，会发现样式会有多次覆盖的情况。
https://preview.pro.ant.design/dashboard/analysis?fixSiderbar=true&colorWeak=false&pwa=false
![image](https://user-images.githubusercontent.com/10163380/106741744-15de2500-6657-11eb-9657-1833f687b6f3.png)

### 🏞 期望结果
每个组件的样式仅打包一次，避免自定义样式被覆盖

### 💻 复现代码
官方的预览页面能稳定复现

### © 版本信息

- Ant Design Pro 版本:  5
- umi 版本： 3
- 浏览器环境：Chrome
- 开发环境：mac OS

### 🚑 其他信息
目前是参考 https://umijs.org/zh-CN/config#chainwebpack ，修改了打包规则，config.ts中增加以下配置，解决了这个问题：
```
chunks: ['vendors', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          minChunks: 2,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      },
    });
  },
```

**Comment by Zhengyang550** [comment]
我也遇到了这个问题

**Comment by chenshuai2144** [comment]
先按照这个配置来一下吧，暂时没有好办法兼顾
