### ISSUE TITLE
🧐[问题] V5 在app.tsx进行request配置，拦截器如何设置局部？

### ISSUE THREAD

**Issue by qq382724935** [ant-design/ant-design-pro#8038]
### 🧐 问题描述
想设置局部拦截器，按照umi-request文档 request.interceptors.request.use第二个参数接收一个object对象设置core:true可设置，但是V5中的requestInterceptors数组只接收一个函数？不能传入第二个参数？
为什么要设置局部拦截器，如请求代码当我调用formData请求时如果在拦截器中进行了处理，Content-Type会变成application/json;charset=UTF-8；尝试了主要是应为重新为 option.data赋值导致
请求代码:
let formData = new FormData();
 formData.append('OSSAccessKeyId', 'STS.NT19n3oG8jHpi6DypGCFd8pEq');
request<>(
        'http://emmtest.oss-cn-shenzhen.aliyuncs.com',
        {
          method: 'POST',
          credentials: 'omit',
          headers: {
            'Access-Control-Allow-Origin': '*',
          },
          data: formData,
        },
      )

### 💻 示例代码
requestInterceptors: [
    (url, option) => {
      option.headers = { ...option.headers, Authorization };
      try {
        const currentUser = getSession(KEYS.currentUser);
        option.data = {
          ...option.data,
          comGroupName: currentUser?.comGroupName,
          comGroup: currentUser?.comGroup,
          roleId: currentUser?.roleId,
          roleName: currentUser?.roleName,
          // createUserId: currentUser?.userId,
          // createUserName: currentUser?.userName,
        };
      } catch (error) {}

      if (url !== '/api/retailauth/oauth/token') {
        try {
          const currentUser = getSession(KEYS.currentUser);
          if (currentUser.token) {
            option.headers = {
              ...option.headers,
              Authorization: `Bearer ${currentUser.token}`,
            };
          }
        } catch (error) {}
      }
      return { url, option };
    },
  ],

**Comment by chenshuai2144** [comment]
大家关之前贴一下解决方案，可以帮助到更多的人
