### ISSUE TITLE
关于登录之后重定向先前地址的疑问

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#8040]
@chenshuai2144 

这好像是个老话题，查到这么一个帖子比较老了
https://github.com/ant-design/ant-design-pro/issues/672

我的需求是这样   输入 http://127.0.0.1/license    因权限跳转到了 登录页面，希望在登录后再跳转到 /license 页面

基于antd pro v5开发，关于登录这块流程和官网代码一致，没有修改，但在这里获取到query是{},应该怎么传值才对呢？
![image](https://user-images.githubusercontent.com/17469220/106843881-15807100-66cd-11eb-8543-6720dd607030.png)

麻烦你再给大家理下这块的流程，怎么把license传过去呢

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Location/search

是这个东西，需要设置一个 query 参数。

你如果想修改默认的，你就直接修改默认的 "/",  用 redirect 的话可能会有一些安全问题
