### ISSUE TITLE
Can not read property 'Provider' of undefined

### ISSUE THREAD

**Issue by toquanghieu** [ant-design/ant-design-pro#8041]
I'm using version 4, ant design pro
I got this issue when deploy the build version make on ubuntu. this issue just happend with version is built on Ubuntu only. for Windows build version is ok.
![image](https://user-images.githubusercontent.com/15702509/106853730-c34f4800-66ec-11eb-82ab-7fffe359c831.png)

![image](https://user-images.githubusercontent.com/15702509/106853905-06112000-66ed-11eb-97c0-65b4a190e217.png)

**Comment by chenshuai2144** [comment]
try update antd to 4.11.x
