### ISSUE TITLE
🧐[问题]@ant-design/icons bundle size too large

### ISSUE THREAD

**Issue by kaisawind** [ant-design/ant-design-pro#8042]
### 🧐 问题描述

使用ant-design-pro: 4.5.0作为模板，页面打包之后部分页面非常大，里面包含了全部的ant-design/icons导致的。
但是同样使用ant-design/icons的另外一些页面却没有问题。
清理了node_modules,.umi仍然如此。

我需要帮助，我不知道接下来该如何查找问题的所在。

```json
"dependencies": {
  "@ant-design/icons": "^4.4.0",
  "antd": "^4.11.2",
  "umi": "^3.3.7",
   "umi-request": "^1.3.4"
}
```

### 🚑 其他信息

![深度截图_选择区域_20210204144636](https://user-images.githubusercontent.com/4010613/106855214-8a68a080-66f7-11eb-878c-c402717d5f1a.png)

**Comment by chenshuai2144** [comment]
看看是不是这个问题

https://github.com/ant-design/ant-design/pull/29045

**Comment by kaisawind** [comment]
@chenshuai2144 
Yes!It is. Thank you very much.
It takes me so much time.
