### ISSUE TITLE
can not run the project

### ISSUE THREAD

**Issue by joket1999** [ant-design/ant-design-pro#8043]
### 📷 复现步骤
npm create umi
npm i
npm start

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本:  3.2.14
- 浏览器环境
- 开发环境 mac OS 10.15.7
- node 版本: v12.18.4

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/6611880/106864090-62cc0500-6704-11eb-8369-c17e6a2c17b5.png)

**Comment by chenshuai2144** [comment]
升级一下你的 node 版本吧。

这个用了可选操作符，需要 node14
