### ISSUE TITLE
🧐[问题] Ant Design Pro V4版本，编辑器打印一个console，浏览器显示的行数和编辑器不一致

### ISSUE THREAD

**Issue by lx815** [ant-design/ant-design-pro#8047]
### 🧐 问题描述
[新手刚开始学Pro，在V4版本的登录页面，第42行写了一个console，但是在浏览器，查看的时候，这个console显示的是27行，查看source发现浏览器端代码被格式化了，请问有没有大大知道这是怎么回事呢？行数对不上，看起来贼难受

**Comment by chenshuai2144** [comment]
被一层层转化导致的 习惯了就好了
