### ISSUE TITLE
🧐[问题] 想引入iconfont图标，旧版本有iconfontUrl，但是V4是否取消了？

### ISSUE THREAD

**Issue by wanliin** [ant-design/ant-design-pro#8049]
### 🧐 问题描述
请问想引入iconfont图标，旧版本有iconfontUrl，但是V4是否取消了？还是在哪里入口文件引入呢？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont

看看这个
