### ISSUE TITLE
🧐[问题]  配置 externals 报  TypeError: Cannot read property 'unstable_batchedUpdates' of undefined

### ISSUE THREAD

**Issue by opamine** [ant-design/ant-design-pro#8052]
### 🧐 问题描述
错误来自 ./node_modules/react-redux/es/utils/reactBatchedUpdates.js:1

![图片](https://user-images.githubusercontent.com/49026458/107014150-3bde0380-67d6-11eb-9db5-2e899e3cdb4c.png)

### 💻 示例代码

![图片](https://user-images.githubusercontent.com/49026458/107007585-b0607480-67cd-11eb-9275-1e9b4aebbdcf.png)

### 🚑 其他信息

请教一下，这里是因为还需要配置其他地方么？

**Comment by opamine** [comment]
Pro V4

**Comment by chenshuai2144** [comment]
这个看起来是react没有注入成功
