### ISSUE TITLE
v5 版本 如何优雅 的开启高清视图发案

### ISSUE THREAD

**Issue by zlfgege** [ant-design/ant-design-pro#8054]
### 💻 示例代码
 extraPostCSSPlugins: [
    postcssPxToViewport({
      unitToConvert: 'px',
      //需要转换的单位，默认为"px"
      viewportWidth: 828,
      // 视窗的宽度，对应的是我们设计稿的宽度
      viewportHeight: 1334,
      //视窗的高度，根据375设备的宽度来指定，一般指定667，也可以不配置
      unitPrecision: 13,
      // 指定`px`转换为视窗单位值的小数位数（很多时候无法整除）
      propList: ['*'],
      // 能转化为vw的属性列表
      viewportUnit: 'vw',
      // 指定需要转换成的视窗单位，建议使用vw
      fontViewportUnit: 'vw',
      //字体使用的视口单位
      selectorBlackList: ['.ignore-', '.aaa'],
      //指定不转换为视窗单位的类，可以自定义，可以无限添加,建议定义一至两个通用的类名
      minPixelValue: 1,
      // 小于或等于`1px`不转换为视窗单位，你也可以设置为你想要的值
      mediaQuery: false,
      // 允许在媒体查询中转换`px`
      replace: true,
      //是否直接更换属性值，而不添加备用属性
      exclude: [/node_modules/, /RightBar/, /gotop.vue/],
      //忽略某些文件夹下的文件或特定文件，例如 'node_modules' 下的文件
      landscape: false,
      //是否添加根据 landscapeWidth 生成的媒体查询条件 @media (orientation: landscape)
      landscapeUnit: 'vw', //横屏时使用的单位
    }),
  ],

目前的做法是 在config 文件夹中的config 设置上页面如上配置  但是页面提示 extraPostCSSPlugins 即将弃用 
请问有没有什么更好的解决方， 我记得antd pro 之前是可以在umi ui 中直接开启高清视图方案的 但是现在这个选项没了

**Comment by chenshuai2144** [comment]
@ycjcl868 我们外网有h5相关的插件吗

**Comment by chenshuai2144** [comment]
可以试试 [ata.js](https://github.com/alitajs/alita) 还是很好用的
