### ISSUE TITLE
🐛[BUG]V5 footerRender 无法通过config控制显示隐藏

### ISSUE THREAD

**Issue by Feather130** [ant-design/ant-design-pro#8055]
### 🐛 bug 描述

V5 footerRender 无法通过config控制显示隐藏

### 📷 复现步骤

官网预览就不能隐藏

### 🏞 期望结果

可以通过config控制显示隐藏

### 💻 复现代码

https://preview.pro.ant.design/dashboard/analysis?fixSiderbar=true&colorWeak=false&pwa=false

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10240614/107013790-c7a36000-67d5-11eb-8b27-b8547cd25660.png)

**Comment by chenshuai2144** [comment]
因为官网重写了这个footerRender没有用默认的

**Comment by chenshuai2144** [comment]
已经修复，并且部署
