### ISSUE TITLE
🐛[BUG]更改全局主题色后，登录界面的密码图标颜色仍然是“拂晓蓝”

### ISSUE THREAD

**Issue by ocsxxi** [ant-design/ant-design-pro#8056]
### 🐛 bug 描述

经查找，是默认使用了组件LockTwoTone，该组件的颜色并不是defaultSettings.ts中的primaryColor所控制的

### 📷 复现步骤

1. 将仓库clone至本地
2. 使用yarn命令下载安装依赖
3. 更改 config/defaultSettings.ts 中的 DefaultSettings->primaryColor属性为任意其他颜色
4. 使用yarn start命令启动调试服务器
5. 进入localhost:8000/user/login，即可重现

### 🏞 期望结果

应与其他图标相同，例如全部是#FF0000

### © 版本信息

- Ant Design Pro 版本: 4.0
- 浏览器环境 Chrome 87.0.4280.88
- 开发环境 Windows10

**Comment by chenshuai2144** [comment]
fixed

**Comment by jinhgg** [comment]
> 

我5.2.0版本为什么还是有这个bug?

**Comment by ocsxxi** [comment]
> > 
> 
> 我5.2.0版本为什么还是有这个bug?

你好 jinhgg，经过我调试，发现是5.2.0打包的问题，在这个release中没有应用到`config/defaultSettings.ts`配置。
你可以修改`5.2.0 release`源码中的`src/app.tsx`文件如下：

第10行左右
```
import { BookOutlined, LinkOutlined } from '@ant-design/icons';

const isDev = process.env.NODE_ENV === 'development';
```
修改为如下
```
import { BookOutlined, LinkOutlined } from '@ant-design/icons';
import defaultSettings from '../config/defaultSettings';
const isDev = process.env.NODE_ENV === 'development';
```

37行左右将
```// 如果是登录页面，不执行
  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: {},
    };
  }
  return {
    fetchUserInfo,
    settings: {},
  };
```
修改为如下
```// 如果是登录页面，不执行
  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: defaultSettings,
    };
  }
  return {
    fetchUserInfo,
    settings: defaultSettings,
  };
```

@chenshuai2144 或许陈老师有空的时候可以重新打包一下`5.2.0`的`release`？我看到现在`master`分支中`app.tsx`的最新版本已经修复了这个问题

**Comment by chenshuai2144** [comment]
是因为这个 

https://ant.design/docs/react/customize-theme-variable-cn
