### ISSUE TITLE
🐛[BUG] V5版本，测试环境点击退出时，报错。

### ISSUE THREAD

**Issue by luqil** [ant-design/ant-design-pro#8059]
### 🐛 bug 描述

V5版本，测试环境点击退出时，报错。
原因：mock内的虚拟数据方法与实际请求不一致，
相关文件：https://github.com/ant-design/ant-design-pro/blob/v5/mock/user.ts
`
 'GET /api/login/outLogin': (req: Request, res: Response) => {
    access = '';
    res.send({ data: {}, success: true });
  },
`
此处声明的为GET

相关文件：https://github.com/ant-design/ant-design-pro/blob/v5/src/services/ant-design-pro/login.ts

`
/** 登录接口 POST /api/login/outLogin */
export async function outLogin(options?: { [key: string]: any }) {
  return request<Record<string, any>>('/api/login/outLogin', {
    method: 'POST',
    ...(options || {}),
  });
}
`
此处调用的为POST

### 📷 复现步骤

V5版本，测试环境点击退出时，报错。

### 🏞 期望结果

相关文件：https://github.com/ant-design/ant-design-pro/blob/v5/src/services/ant-design-pro/login.ts

`
/** 登录接口 POST /api/login/outLogin */
export async function outLogin(options?: { [key: string]: any }) {
  return request<Record<string, any>>('/api/login/outLogin', {
    method: 'GET',
    ...(options || {}),
  });
}
`
此处调用建议修改为GET类型

**Comment by chenshuai2144** [comment]
Great job
