### ISSUE TITLE
代码下载后 npm run test 包错

### ISSUE THREAD

**Issue by PancakeLa** [ant-design/ant-design-pro#806]
<img width="678" alt="wx20180124-145354 2x" src="https://user-images.githubusercontent.com/8122826/35318510-a3bd4e18-0116-11e8-8d23-2adead3b3882.png">

**Comment by stringStar** [comment]
请问一下如何解决，我这边遇到了，查询后无果

**Comment by stringStar** [comment]
@PancakeLa 您好！请问已经解决了吗？我这边查询后无果，求助
