### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by zhanglinge** [ant-design/ant-design-pro#8060]
### 🐛 bug 描述

侧边栏的 Open API 链接点击后出现如下提示：

```
Parser error on line 32
end of the stream or a document separator is expected

Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```

链接为：http://localhost:8000/umi/plugin/openapi

### 📷 复现步骤

通过 `npx` 安装 Ant Design Pro v5 -> `npm install`  -> `npm start`
点击侧边栏 Open API 后出现问题

### 🏞 期望结果

可以正常显示

### 💻 复现代码

暂无

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本: 3.3.7
- 浏览器环境: Chrome 88.0.4324.96 (Official Build) (x86_64)
- 开发环境: macOS Catalina 10.15.7 (19H512)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/4507011/107023867-31296b80-67e2-11eb-8f6d-cad86cb02bb8.png)

**Comment by chenshuai2144** [comment]
写标题

**Comment by chenshuai2144** [comment]
fix by https://github.com/chenshuai2144/openapi2typescript/commit/be77a67a9656bb8679259236fb768352f0289e88
