### ISSUE TITLE
🧐[问题] umi ui bubble not showing up

### ISSUE THREAD

**Issue by HTMHell** [ant-design/ant-design-pro#8062]
### 🧐 问题描述

After a fresh installation (I tried v4 & v5) I open localhost:8000, the app runs fine but I don't have the ui bubble.

### 💻 示例代码

```
yarn create umi myApp
cd myApp
yarn
yarn start
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/6322901/107072917-52448900-67ef-11eb-8865-680dc7ada867.png)

**Comment by HellCatVN** [comment]
have same problem

**Comment by chenshuai2144** [comment]
you can install @umijs/preset-ui 

你需要手动安装一下 `@umijs/preset-ui `

**Comment by HTMHell** [comment]
> you can install @umijs/preset-ui
> 
> You need to install it manually `@umijs/preset-ui `

Thank you! maybe you should specify this in the [documentation](https://pro.ant.design/docs/block). As a total newbie to this package, it wasn't clear.
