### ISSUE TITLE
🧐[问题]proDescriptions 可编辑的定义列表在有边框的时候，进入编辑模式输入框错位

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#8064]
### 🧐 问题描述
如图1所示，将proDescriptions的bodered属性设为true，给列表加上边框
![image](https://user-images.githubusercontent.com/54265150/107114600-030b6080-68a2-11eb-8839-8bdc14790c51.png)

然后点击进入编辑模式，此时输入框产生严重的错位，并且撑开了表格单元格，如图2所示
![image](https://user-images.githubusercontent.com/54265150/107114624-3948e000-68a2-11eb-84a1-3343db593033.png)

请问有什么办法让输入框不错位吗？

**Comment by chenshuai2144** [comment]
我从底层框架上想办法把

**Comment by Youmyin** [comment]
好的，谢谢！

在 2021年2月6日，20:54，陈帅 <notifications@github.com> 写道：

﻿

我从底层框架上想办法把，应该给个margin了
