### ISSUE TITLE
🧐[问题]如何省略models模块

### ISSUE THREAD

**Issue by jiclivi** [ant-design/ant-design-pro#8065]
### 🧐 问题描述
就是去掉models，后端api反回json直接渲染数据

流程比如：获取api json数据 => 直接绑定到ts中html里面渲染

**Comment by chenshuai2144** [comment]
看看v5 的方式，可以用 useRequest

https://zhuanlan.zhihu.com/p/106796295

**Comment by jiclivi** [comment]
> 看看v5的方式，可以用useRequest
> 
> https://zhuanlan.zhihu.com/p/106796295
好的，谢谢！

**Comment by jiclivi** [comment]
@chenshuai2144 
好的，谢谢！
