### ISSUE TITLE
🧐[BUG] type error in utils/request.ts (codeMessage[response.status])

### ISSUE THREAD

**Issue by stefango** [ant-design/ant-design-pro#8067]
```
Element implicitly has an 'any' type because expression of type 'number' can't be used to index type '{ 200: string; 201: string; 202: string; 204: string; 400: string; 401: string; 403: string; 404: string; 406: string; 410: string; 422: string; 500: string; 502: string; 503: string; 504: string; }'.
  No index signature with a parameter of type 'number' was found on type '{ 200: string; 201: string; 202: string; 204: string; 400: string; 401: string; 403: string; 404: string; 406: string; 410: string; 422: string; 500: string; 502: string; 503: string; 504: string; }'.ts(7053)
```
🤔
https://github.com/ant-design/ant-design-pro/blob/4f5e100b561f4d0d085aa35b26bac5d0b3642864/src/utils/request.ts#L27

**Comment by stefango** [comment]
I found two ways to fix the bug, but I'm wondering which is better?

1. https://github.com/microsoft/TypeScript/issues/35859#issuecomment-679986472
2. https://github.com/xzl-org/ts-app/blob/dcc9aac3bca3151f3aa4de9b252e0029982b8fca/src/utils/request.ts#L27

**Comment by chenshuai2144** [comment]
I think the first one is good

**Comment by chenshuai2144** [comment]
fixed by  https://github.com/ant-design/ant-design-pro/pull/8070

**Comment by stefango** [comment]
One more thing, vscode won't show the status code if I code like the first one does.
Before:
![Before](https://user-images.githubusercontent.com/24286594/107166868-3c52e600-69f2-11eb-912e-70a098a908de.png)

After:
![After](https://user-images.githubusercontent.com/24286594/107166858-35c46e80-69f2-11eb-9a73-22e718afe7f7.png)

Add `as const`: show both status code and message
![as const](https://user-images.githubusercontent.com/24286594/107166994-a10e4080-69f2-11eb-853c-e89ef5c05b18.png)
