### ISSUE TITLE
在login的model中,登陆成功后, 使用history.push("/")跳转首页路由报错, 用location.href="/"就可以

### ISSUE THREAD

**Issue by coderLrh** [ant-design/ant-design-pro#8069]
### 🧐 问题描述
在login的model中,登陆成功后, 使用history.push("/")跳转首页路由报错

### 💻 示例代码
![image](https://user-images.githubusercontent.com/46252189/107142132-c73ace80-6967-11eb-9211-50bec65939a3.png)
![image](https://user-images.githubusercontent.com/46252189/107142151-da4d9e80-6967-11eb-9cc2-27a5a3b80a0b.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/46252189/107142270-9c04af00-6968-11eb-8697-2e3155a33f84.png)

**Comment by chenshuai2144** [comment]
这个错误一般是因为你用别的框架修改了dom导致的，不如说开了google 翻译，导致虚拟dom和真实dom之间有了差距

**Comment by coderLrh** [comment]
> 这个错误一般是因为你用别的框架修改了dom导致的，不如说开了google 翻译，导致虚拟dom和真实dom之间有了差距

感谢提醒!!!!!
确实是因为我在 UserLayout 布局中用了一个叫  ReactCanvasNest 的库,我目的就是单纯的换个背景而已,  没想到会造成这样的问题  导致虚拟DOM和真实DOM有了差距,   跟我引入的位置有关

![image](https://user-images.githubusercontent.com/46252189/107168419-50004b80-69f6-11eb-9fdb-4a12c945b587.png)
![image](https://user-images.githubusercontent.com/46252189/107168557-a9687a80-69f6-11eb-8566-fc5ed0092256.png)
