### ISSUE TITLE
🐛[BUG] 菜单折叠后, 点击一级菜单后快速移开鼠标, 提示框不会消失

### ISSUE THREAD

**Issue by yg0x01** [ant-design/ant-design-pro#8073]
### 🐛 bug 描述
菜单折叠后, 点击一级菜单后快速移开鼠标, 提示框不会消失

### 📷 复现步骤
1. 首先将菜单折叠:
![image](https://user-images.githubusercontent.com/17229609/107225487-d008ce80-6a53-11eb-954f-79919a6ba1db.png)
2. 鼠标移动至一个当前未选中的一级菜单上:
![image](https://user-images.githubusercontent.com/17229609/107225707-16f6c400-6a54-11eb-8a1a-8d2d53b31cd3.png)
3. 点击该菜单并快速将鼠标移开:
![image](https://user-images.githubusercontent.com/17229609/107225814-40175480-6a54-11eb-9baf-0dd88c378f06.png)

### 🏞 期望结果
鼠标指向的提示框会消失

### 💻 复现代码
Ant Design Pro v5 boilerplate 即可复现

>
> ```
> yarn create umi my-app
> ```

### © 版本信息

- Ant Design Pro 版本:  5.0.0-beta.2
- umi 版本: 3.2.14
- 浏览器环境: Google Chrome 88.0.4324.146
- 开发环境: Win10

**Comment by chenshuai2144** [comment]
更新到最新的antd 吧
