### ISSUE TITLE
antd pro v5 yarn报错Cannot use import statement outside a module🐛[BUG]

### ISSUE THREAD

**Issue by whoisje** [ant-design/ant-design-pro#8076]
### 🐛 bug 描述

按照官方快速入门创建项目后，yarn时报错
/node_modules/umi-plugin-antd-icon-config/lib/index.js failed, since Cannot use import statement outside a module

### 📷 复现步骤

按照官方文档新建一个项目百分百复现。

### 🏞 期望结果

解决问题

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本
- 浏览器环境 chrome
- 开发环境  mac OS

**Comment by easeava** [comment]
@ctrl/tinycolor打包未转义es5, 暂时自己打包替换吧

**Comment by haua** [comment]
创建 Ant Design Pro 4 也出现同样问题，等待修复，今天没法干活了

**Comment by easeava** [comment]
package.json加入`"resolutions": {
    "@ant-design/colors": "5.0.0"
  }`暂时这么解决吧

**Comment by whoisje** [comment]
@easeava thank you，解决问题了。

**Comment by easeava** [comment]
@ant-design/colors已经编译新版本了,已经解决了
