### ISSUE TITLE
🧐[问题]我改了页面结构太多地方出问题了，我觉得可以调整一下页面结构

### ISSUE THREAD

**Issue by jiclivi** [ant-design/ant-design-pro#8081]
### 💻 示例代码
这样的就够有点像vue
`  
<template>
  <div class="header">头部</div>
  <div class="navbar">左侧区域</div>
</template>
<template>
  <div class="main">主区域</div>
</template>
<template>
  <div class="footer">底部</div>
</template>
 `

**Comment by chenshuai2144** [comment]
提问题要描述清楚
