### ISSUE TITLE
🐛[BUG] ant design GitHub repo disappeared

### ISSUE THREAD

**Issue by thekennysong** [ant-design/ant-design-pro#8086]
http://github.com/ant-design/ant-design/

is now 404? does anyone know why this is?

**Comment by nfau1** [comment]
I was wondering the same thing. Even https://ant.design returns 404.

**Comment by wassafr** [comment]
Same here, the repo doesn't even exist anymore

**Comment by Endevir** [comment]
Seems like entire repository at https://github.com/ant-design/ant-design is unavailable...

**Comment by laneme** [comment]
> https://3x.ant.design/docs/react/introduce

*As a side note*, The alternate link is for v3, which is an older version. They also have one for x2. Whats down is the latest version, 4x. You'll find it on top right.

**Comment by hugomn** [comment]
Here's the latest docs: https://ant-design.gitee.io/docs/react/introduce

But honestly, where's the official announcement regarding this move? Does this mean now all issues and PRs history are gone? Do all the contributors now need to also have an account in gitee?

**Comment by raindecastro** [comment]
> Here's the latest docs: https://ant-design.gitee.io/docs/react/introduce
> 
> But honestly, where's the official announcement regarding this move? Does this mean now all issues and PRs history are gone? Do all the contributors now need to also have an account in gitee?

I can also see that happening, looks like we'll be forced to use gitee :(

**Comment by rodamaral** [comment]
Looks like some people will have to migrate or fork. This _gitee_ is controlled by China's government and under no circumstances ever should it be trusted. And the fact that they deleted the Github repo and documentation site out of the blue is a red flag warning (no pun intended).

**Comment by ycjcl868** [comment]
https://github.com/ant-design/pro-components/issues/1904#issuecomment-778880352

**Comment by lsvih** [comment]
Latest response

<img width="571" alt="image" src="https://user-images.githubusercontent.com/5164225/107897421-f4910900-6f73-11eb-99d0-43e9495aa49b.png">

**Comment by afc163** [comment]
Could anyone know any employee of GitHub who could help us to cover repository?

**Comment by jaluik** [comment]
what happened?

**Comment by KieSun** [comment]
可以联系support@github.com 我当初有一个仓库被团队的人删了，联系这个邮箱，隔了一晚就帮我恢复了

**Comment by KieSun** [comment]
> Does anyone know employee of GitHub who could help us to restore the repository?
> @natfriedman @simurai



> Does anyone know employee of GitHub who could help us to restore the repository?
> @natfriedman @simurai

可以联系support@github.com 我当初有一个仓库被团队的人删了，联系这个邮箱，隔了一晚就帮我恢复了

**Comment by Ahacad** [comment]
https://github.com/ant-design/ant-design-site-temporary
Here for temporary repo.

**Comment by chenshuai2144** [comment]
Has been restored, welcome to start
