### ISSUE TITLE
OFFTOPIC https://ant.design is down and git repo does not exist anymore? WTF?

### ISSUE THREAD

**Issue by artemdumanov** [ant-design/ant-design-pro#8087]
OFFTOPIC https://ant.design is down and git repo does not exist anymore? WTF?

**Comment by elisaado** [comment]
Their new links are:
https://gitee.com/ant-design/ant-design
https://ant-design.gitee.io

**Comment by artemdumanov** [comment]
@elisaado Don't you know what is the reason to move to gitee and did I miss some notices that the repo will be moved?

**Comment by elisaado** [comment]
I'm not sure but I think it may have to do with the chinese origins of this project

**Comment by artemdumanov** [comment]
@elisaado Not really... 
![изображение](https://user-images.githubusercontent.com/14028216/107917815-340a2600-6f71-11eb-994e-e5c469c88f8f.png)
