### ISSUE TITLE
🧐[问题] https://ant.design/index-cn 突然打不开了，大家也有类似情况吗？

### ISSUE THREAD

**Issue by lixingyangok** [ant-design/ant-design-pro#8089]
### 🧐 问题描述
如题：
https://ant.design/index-cn 突然打不开了，大家也有类似情况吗？
希望马上能恢复啊，谢谢

**Comment by foo614** [comment]
一樣的情況

**Comment by liulinboyi** [comment]
@lixingyangok 
仓库可能突然被GitHub删了，先用国内版的官网吧。
https://ant-design.gitee.io/index-cn

**Comment by tomgao365** [comment]
删库跑路？

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design-pro/issues/8086#issuecomment-778891249
