### ISSUE TITLE
🐛[BUG] The Loading page is not change

### ISSUE THREAD

**Issue by toquanghieu** [ant-design/ant-design-pro#8091]
### 🐛 bug 描述
I want change default LoadingPage, I already change in src/components/LoadingPage/index as image bellow:
![image](https://user-images.githubusercontent.com/15702509/108149533-a6137400-7105-11eb-9d79-ffee3cc6d507.png)
After changed, I tried to restart the web application and reload, clear cache, But I still get this page:
![Screenshot_2](https://user-images.githubusercontent.com/15702509/108149652-e96de280-7105-11eb-9cd6-54e4b4021875.png)

### 📷 复现步骤

Change default LoadingPage in config/config.ts or change index in src/components/LoadingPage/index

I tried to comment in config.ts but nothing change:
![image](https://user-images.githubusercontent.com/15702509/108150405-31d9d000-7107-11eb-8a87-0161ac1e8077.png)

### 🏞 期望结果

The default loading page when I reload web application should be change

### 💻 复现代码

Above
### © 版本信息

"@ant-design/icons": "^4.4.0",
    "@ant-design/pro-descriptions": "1.5.1",
    "@ant-design/pro-field": "1.9.4",
    "@ant-design/pro-form": "^1.15.4",
    "@ant-design/pro-layout": "6.14.0",
    "@ant-design/pro-table": "2.29.0",
    "@antv/data-set": "^0.11.8",
    "@antv/l7": "^2.3.7",
    "@antv/l7-maps": "^2.3.7",
    "@antv/l7-react": "^2.1.9",
    "@testing-library/react": "^11.2.5",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "@umijs/route-utils": "^1.0.33",
    "@zxing/library": "^0.18.3",
    "antd": "4.12.2",

Windows, Ubuntu

**Comment by toquanghieu** [comment]
move to: https://github.com/ant-design/pro-components/issues/1971

**Comment by chenshuai2144** [comment]
this landing page in 

https://github.com/ant-design/ant-design-pro/blob/2b403a99230ac3566609d235c64374d149452207/src/pages/document.ejs
