### ISSUE TITLE
🧐[问题] v5版本插件可以贴出来么

### ISSUE THREAD

**Issue by jicvi** [ant-design/ant-design-pro#8093]
### 🧐 问题描述

因为v4版本的插件和v5有些用法和文档里说的都不一样，所以希望可以共享一下．
v5中只带了几个默认插件

### 💻 示例代码

比如components下：
Header
SiderMenu
PageHeaderWrapper
TopNavHeader
........

**Comment by chengzequn** [comment]
https://procomponents.ant.design/components/
不知道这个是不是你想要的

**Comment by jicvi** [comment]
好的！谢谢
