### ISSUE TITLE
Why doesn't antd pro 4 dashboard loads like antd pro 2 with smooth animation

### ISSUE THREAD

**Issue by awais000** [ant-design/ant-design-pro#8096]
Antd Pro v2 : https://v2-preview-ant-design-pro.netlify.app/dashboard/analysis
Antd Pro v4 : https://preview.pro.ant.design/dashboard/analysis?fixSiderbar=true&colorWeak=false&pwa=false

 You see charts and graph loads more smoothly with v2.

**Comment by chenshuai2144** [comment]
look here https://charts.ant.design/
