### ISSUE TITLE
🧐[问题]如何通过接口返回的色值动态修改主题色

### ISSUE THREAD

**Issue by ZaccheoMoon** [ant-design/ant-design-pro#8097]
### 🧐 问题描述

现有一需求，用户在登录后接口会返回一个色值，需要通过这个色值改变主题色并能在登录后生效，敢问大佬们能不能实现？

**Comment by xiaohuoni** [comment]
https://zhuanlan.zhihu.com/p/347725244

**Comment by xiaohuoni** [comment]
这里有一个实践用例：https://github.com/alitajs/umi-antd-pro/commit/c1d54b31ff26204fdcf11f77ea719df0ef1028a4

**Comment by ZaccheoMoon** [comment]
> https://zhuanlan.zhihu.com/p/347725244

@xiaohuoni 按照你这个网址里面的照做，发现有打印
![image](https://user-images.githubusercontent.com/19562297/109109555-78b36f80-7770-11eb-90bc-49967c8e57bd.png)
但是使用了@primary-color的文字并没有变色，相关组件也没有变色。
你给的实践用例的链接，是注释掉的那些为生效代码吗？

**Comment by ZaccheoMoon** [comment]
@xiaohuoni 你例子上的@layout-body-background是可以变色的，但是ant-design-pro里面的ant组件的主题色和本身框子的主题色没有办法改变

**Comment by xiaohuoni** [comment]
> @xiaohuoni 你例子上的@layout-body-background是可以变色的，但是ant-design-pro里面的ant组件的主题色和本身框子的主题色没有办法改变

是不是配置没写，需要写了配置才会提取，不然文件很大。

**Comment by ZaccheoMoon** [comment]
> > @xiaohuoni 你例子上的@layout-body-background是可以变色的，但是ant-design-pro里面的ant组件的主题色和本身框子的主题色没有办法改变
> 
> 是不是配置没写，需要写了配置才会提取，不然文件很大。自身框架的主题色没有变化，可能是主入口写的不对。如果你有可复现的仓库，我可以给你提交PR修改。会比较清晰。

@xiaohuoni 并不是，我如果设置了umi theme的@primary-color的值，则window.less.morify修改无效，如果不设置那么修改的值又不会作用完全如Select组件被选中时的外框颜色不对。所用的项目为ant design pro v5

**Comment by xiaohuoni** [comment]
> umi theme

这个还没有兼容，欢迎PR
