### ISSUE TITLE
无法初始化项目🐛[BUG]

### ISSUE THREAD

**Issue by wanglianjie91** [ant-design/ant-design-pro#8098]
### 🐛 bug 描述
按照官方教程，通过create-umi初始化项目，在npm install的时候，出现依赖错误。

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ant-design-pro@5.0.0-beta.2
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!   peer react@">=16.9.0" from antd@4.12.3
npm ERR!   node_modules/antd
npm ERR!     antd@"^4.9.4" from the root project
npm ERR!     peer antd@"4.x" from @ant-design/pro-form@1.15.4
npm ERR!     node_modules/@ant-design/pro-form
npm ERR!       @ant-design/pro-form@"^1.3.0" from the root project
npm ERR!   1 more (react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x" from @ant-design/pro-form@1.15.4
npm ERR! node_modules/@ant-design/pro-form
npm ERR!   @ant-design/pro-form@"^1.3.0" from the root project

### 🏞 期望结果

正常初始化。

### © 版本信息

- Ant Design Pro 版本: 4.0和5.0同样的问题。
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by jiclivi** [comment]
183  npm create umi
184  npm install --legacy-peer-deps
185  npm install -g npm-check-updates
186  npm start
187  npm run build

**Comment by lianzhao** [comment]
楼主是`npm@7`？这是7的新特性，退回6就没事了。参考：https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

**Comment by lianzhao** [comment]
楼主是`npm@7`？这是7的新特性，退回6就没事了。参考：https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

**Comment by xiaogliu** [comment]
不需要回退，加上 ` --legacy-peer-deps` 
```
npm install --legacy-peer-deps
```

**Comment by zhfish** [comment]
`node node_modules/esbuild/install.js`
再安装一下esbuild

**Comment by burialstance** [comment]
> 183 npm create umi 184 npm install --legacy-peer-deps 185 npm install -g npm-check-updates 186 npm start 187 npm run build

worked
