### ISSUE TITLE
👑 [需求] OpenAPI支持多后端服务和自定义path前缀吗？

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8102]
### 🥰 需求描述

1.请问V4可以用OpenAPI吗？
2.请问支持多requestLibPath吗？且前端生成service代码时，支持增加不同的自定义path前缀？因为一个前端可能对接多个后端服务，需要增加自定义path前缀，rewrite，然后做不同的转发。

**Comment by chenshuai2144** [comment]
1.请问V4可以用OpenAPI吗？

v4 可以用的

>  2.请问支持多requestLibPath吗？且前端生成service代码时，支持增加不同的自定义path前缀？因为一个前端可能对接多个后端服务，需要增加自定义path前缀，rewrite，然后做不同的转发。

这个暂时还不支持，你有好的办法可以直接提pr
