### ISSUE TITLE
🧐[问题]V5如何在errorHandler中实现状态吗为401时重新登陆（设置currentUser为undefined）？

### ISSUE THREAD

**Issue by wmf508** [ant-design/ant-design-pro#8103]
### 🧐 问题描述
情景：在登陆token超时，且网页还未关闭的情况下，用户不刷新页面而是点击菜单切换页面不会重定向到登陆页；
在errorHandler中无法使用useModel，导致获取到401错误码后无法设置currentUser为undefined，再跳转登陆页时被识别为已登陆状态

**Comment by fangqibin** [comment]
虽然我不知道你要实现的场景是什么，再不行就重定向一个地址去清掉登录状态就行了。
