### ISSUE TITLE
👑 [需求]　请问:  ProLayout悬浮布局, ProLayout自定义布局怎么修改，才能像下面的效果

### ISSUE THREAD

**Issue by jiclivi** [ant-design/ant-design-pro#8105]
####  Layout悬浮布局,悬浮的元素默认是隐藏的．
'''   

       <ProLayout>
          
            <div style={{ position: 'fixed', width: '100%', minHeight: '10vh'}}>
                <div style={{ background: '#fff', textAlign: 'center', padding: '8px 0',}}>
                  Header
                </div>
            </div>

          
          <div style={{ position: 'fixed', marginTop: 39, right: 0, width: '65%', maxWidth: 280, minHeight: '100vh'}}>
              <div style={{ marginRight: 0, width: '100%', minHeight: '100vh', background: '#DC143C' }}>
                Sider
              </div>
          </div>

          
          <div style={{ float: 'left', background: '#fff', width: '100%', minHeight: '100vh'}}>
            <div style={{ width: 'auto', marginTop: 100, minHeight: '100vh' }}>
                   Content
                   Content
                   Content
                   Content
                   Content
                   Content
                   Content
                   Content
            </div>
          </div>

          
          <div style={{ left: 0, position: 'fixed', bottom: 0, width: '100%', background: '#C71585', minHeight: 160}}>
            <div style={{ width: 'auto',  textAlign: 'center', minHeight: 160}}>
                Footer
                Ant Design ©2018 Created by Ant UED
            </div>
          </div>
       </ProLayout>

'''   

### 🚑 其他信息

![20210219195418](https://user-images.githubusercontent.com/14210650/108501488-580c9500-72ec-11eb-9907-7b6844d940ae.png)

**Comment by chenshuai2144** [comment]
你是想切换一下左右菜单吗？

**Comment by jiclivi** [comment]
@chenshuai2144
我是想弄一个小程序：
１．把头部/底部/菜单都隐藏
２．菜单靠右
３．中部容器占满全屏

**Comment by chenshuai2144** [comment]
用flex 自己拼一下吧，自带的 ProLayuot 估计实现不了，改动有点大了

**Comment by jiclivi** [comment]
＠chenshuai2144
好的，ProLayuot布局组建，我觉得后期可以改灵活一点，可以灵活拼接布局组件．

**Comment by chenshuai2144** [comment]
这个就是 antd 的组件了，我们希望大家不要关心 layout，最好每个项目都长得一样。

你这种的已经超出了 layout 能支持的范围了
