### ISSUE TITLE
🧐[问题]请问下有公共模块的最佳实践吗

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8106]
### 🧐 问题描述

to B项目，很多模块是不同客户的各项目公用的，例如用户权限管理等，有没有这方面的最佳实践文档呢

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/index-cn

看这里，我们都提供了一些解决方案，不过都是通用的。你可以试试微服务  权限来区分路由
