### ISSUE TITLE
👑 [需求] 系统更新问题

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-pro#8107]
在以前的版本里, 重新部署后, 项目从v.1.1 到 v.1.2 , 刷新地址会在右上角提示项目有更新, 是否刷新系统的, 点击刷新就切换到最新的,  请问V5怎么没有这个功能了~

**Comment by chenshuai2144** [comment]
这个是pwa，我们无法驾驭所以关掉了

https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps
