### ISSUE TITLE
ProForm表单initialValues属性设置动态数据无法回显

### ISSUE THREAD

**Issue by yi-boide** [ant-design/ant-design-pro#8108]
ProForm表单initialValues属性设置动态数据无法回显

![image](https://user-images.githubusercontent.com/63292605/108602980-34c31200-73e0-11eb-9bcb-6644f0555866.png)

![image](https://user-images.githubusercontent.com/63292605/108602767-c467c100-73de-11eb-8b44-ff25c613ef4c.png)

![image](https://user-images.githubusercontent.com/63292605/108602817-23c5d100-73df-11eb-921d-e9c24a45d3dd.png)

上面的输出是获取到了值的
奇怪的是不会回显到页面上面去，我将值写死放在initialValues里面是能够回显出来的

**Comment by kmoon216kmoon** [comment]
我也是

**Comment by Youmyin** [comment]
请问最后是如何解决的呢？

**Comment by Youmyin** [comment]
请问最后是如何解决的呢？

**Comment by yi-boide** [comment]
> 请问最后是如何解决的呢？

加一个判断，返回数据了再加载表单

**Comment by Youmyin** [comment]
好的，感谢！！

**Comment by gyx8899** [comment]
# 分享一个亲测有效的方法

## 问题： `initialValues` 更新了但是 UI 未更新问题的方法。</b>

## 方法： 使用 ProForm 的 params 和 request 参数实现更新 initialValues。

代码片段如下：

```js
<ProForm
  initialValues={updatedValues}
  params={updatedValues}
  request={(params) => {
    return Promise.resolve({
      data: params,
      success: true,
    })
  }}
>
</ProForm>
```

## 参考： API 文档
[ProForm Layouts API](https://procomponents.ant.design/components/form#layouts-api)
