### ISSUE TITLE
🐛[BUG]外链多子菜单的场景，单个子菜单hover全部子菜单被高亮显示，且点不到文字上不跳转

### ISSUE THREAD

**Issue by XiaoSK** [ant-design/ant-design-pro#8113]
### 🐛 bug 描述

多外链子菜单的场景，单个子菜单hover全部子菜单被高亮显示，且点不到文字上不跳转

### 📷 复现步骤

hover在用户管理子菜单上：
1. 角色管理也会被高亮
2. 点击在文字上可以跳转，但点击在该行菜单文字右侧的地方就不跳转

![image](https://user-images.githubusercontent.com/4531292/108626797-04857d00-748d-11eb-9319-a5db47caa0c8.png)

### 🏞 期望结果

对于外链性质的菜单：
1. hover在单个子菜单上，仅高亮该子菜单，其他菜单不受影响
2. 点击菜单文字左右的区域，也应该跳转

和非外链性质的菜单hover效果、点击有效区域保持一致。

### 💻 复现代码

routes.ts:

![image](https://user-images.githubusercontent.com/4531292/108626735-abb5e480-748c-11eb-8165-458b303d5ce3.png)

```
  "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.10.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8"
  }
```

### © 版本信息

mac chrome

**Comment by chenshuai2144** [comment]
手工写个key上去吧。path 的正则看起来有点问题

**Comment by JoernLee** [comment]
请问第二个问题怎么解决的？我也遇到同样的问题
