### ISSUE TITLE
关于ProFormText.Password的问题

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#8114]
如果类型为Password的时候，右边有个可视切换按钮，如果我想关闭它，我查了文档如下：
![image](https://user-images.githubusercontent.com/17469220/108723656-85ef1500-754a-11eb-8057-7eaa3a38ac8a.png)
![image](https://user-images.githubusercontent.com/17469220/108723717-956e5e00-754a-11eb-9e95-fcd9886017e9.png)
因此我想用这个参数关闭，但如下图是无效的，请问该如何实现
![image](https://user-images.githubusercontent.com/17469220/108723923-c8b0ed00-754a-11eb-82e7-d7de6de49ca2.png)
@chenshuai2144

**Comment by chenshuai2144** [comment]
看起来是类型没写上，你有兴趣来个 pr 吗？

**Comment by jobscq** [comment]
`
<ProFromText.Password 
  fieldProps: {
      size: 'large',
      visibilityToggle: false,
    }
/>
`

在这里设置

**Comment by jobscq** [comment]
`
<ProFormText.Password
  fieldProps={{
      size: 'large',
      visibilityToggle: false,
    }}
/>
`
在这里设置
