### ISSUE TITLE
🐛[BUG]编译启动，后报错，

### ISSUE THREAD

**Issue by itotoo** [ant-design/ant-design-pro#8115]
### 🐛 bug 描述

TypeError: _interopRequireWildcard is not a function
./node_modules/@ant-design/icons/lib/icons/SmileOutlined.js
./node_modules/@ant-design/icons/lib/icons/SmileOutlined.js:12

   9 | });
  10 | exports.default = void 0;
  11 | 
  12 | var React = _interopRequireWildcard(require("react"));
  13 | 
  14 | var _SmileOutlined = _interopRequireDefault(require("@ant-design/icons-svg/lib/asn/SmileOutlined"));
  15 | 

### 📷 复现步骤

antdpro v4/v5 下载，安装，启动，访问，就报错

### 🏞 期望结果

正常首页

### 💻 复现代码

线上包

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by mrchenxxx** [comment]
同样的报错 望解决

**Comment by chenshuai2144** [comment]
升级一下依赖？

看起来是包发的出问题了

**Comment by itotoo** [comment]
卸载重装好了，具体原因不知
