### ISSUE TITLE
🐛[BUG]ProForm中ProFormText的placeholder不生效。

### ISSUE THREAD

**Issue by SilkageNet** [ant-design/ant-design-pro#8117]
### 🐛 bug 描述

ProForm中ProFormText的placeholder不生效。

### 📷 复现步骤

最新脚手架就是这样，官方预览也没有正确显示。

### 🏞 期望结果

应正确显示placeholder。

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by SilkageNet** [comment]
![image](https://user-images.githubusercontent.com/37325878/108811006-5fcb8280-75e7-11eb-91d0-b4c20374895f.png)

**Comment by loveQr** [comment]
同样出现了

**Comment by luqil** [comment]
同样出现了

**Comment by luqil** [comment]
应该实使用的插件出现的问题：ProComponents
![image](https://user-images.githubusercontent.com/33475522/108953252-e21a7c00-76a5-11eb-928f-e3dd897b899f.png)
官方网站上出现同样的问题，能力有限，还没有定位到具体位置。
