### ISSUE TITLE
🧐[问题] 什么原因会导致菜单配置的icon识别无效

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-pro#8118]
如题, 不知道什么原因造成导致菜单上的 icon无法渲染, 直接输出文本了,

组件上使用的 icon正常, 没有异常 ~

**Comment by xoptimal** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
layout 插件删除了吧

**Comment by liu-miao-miao** [comment]
动态菜单，icon必须是组件（类似这种icon: <HomeOutlined />），否则就会渲染成文本

**Comment by liu-miao-miao** [comment]
动态菜单，icon得是组件（类似这种：`icon: <HomeOutlined />`）,否则就会被渲染成文本

**Comment by xoptimal** [comment]
> 动态菜单，icon得是组件（类似这种：`icon: <HomeOutlined />`）,否则就会被渲染成文本

亲, 我的不是这个问题 ~   我不知道怎么导致的, 反正就失效了, 只能回滚代码, 当时不清楚修改到了那里了
