### ISSUE TITLE
🐛[BUG] Pro V5 文档页面引用错误

### ISSUE THREAD

**Issue by jobscq** [ant-design/ant-design-pro#8119]
### 🐛 bug 描述
v5文档 --> 构建和部署 --> 代码分割
地址：https://beta-pro.ant.design/docs/code-split-cn

页面的内容描述和标题不一致，[代码分割] 和 [部署] 引用的页面相同，不确定是多了一个 [代码分割] 的菜单，还是页面引用错误

### 📷 复现步骤
直接访问页面地址

**Comment by chenshuai2144** [comment]
来个 pr？

**Comment by jobscq** [comment]
> 来个 pr？

你这项目里 code-split-cn.md 文件都不存在，怎么给pr  :joy:

**Comment by chenshuai2144** [comment]
跳转到umi的相关说明好了

**Comment by chenshuai2144** [comment]
已发布
