### ISSUE TITLE
umi中配置routes包含icon为双色图标，主题色怎么修改？

### ISSUE THREAD

**Issue by baixiaosh** [ant-design/ant-design-pro#8123]
### 🧐 问题描述

umi 3.2.x
在config中配置了routes，其中部分菜单路由包含了icon，并且这个icon为双色图标，这个时候渲染出来的icon颜色为antd的主题色#1890ff；
修改config中的theme主题色为其他颜色，菜单中的icon颜色并未改变。
此时icon的颜色需要怎么修改？

### 💻 示例代码

`{
    path:'index'
    name: 'dashboard',
    menuIcon: 'DashboardTwoTone',
    component: './dashboard',
}`

**Comment by chenshuai2144** [comment]
这个不支持改的，你可以通过 menuItemRender 来自定义修改一下
