### ISSUE TITLE
🧐[问题]v5要如何引用css文件

### ISSUE THREAD

**Issue by wmf508** [ant-design/ant-design-pro#8124]
### 🧐 问题描述
我在添加了xterm的js库以后，需要引用它的css文件，但是import 'xterm/dist/xterm.css';后报无法解析的错。如何解决

**Comment by chenshuai2144** [comment]
不应该的，默认是支持css的，你把报错信息贴出来吧

**Comment by tnduc** [comment]
> 不应该的，默认是支持css的，你把报错信息贴出来吧

I had the same problem, with no error message, when the `npm run build` css not applied.

**Comment by chenshuai2144** [comment]
you should  import css
