### ISSUE TITLE
打包后字体无法识别

### ISSUE THREAD

**Issue by taoeer** [ant-design/ant-design-pro#813]
# 打包后字体无法识别

# 重现：
1. npm install ant-design-pro-cli -g
2. pro new 
3. npm run build
4. 部署打包后的文件（dist文件夹下的文件）
5. 打开浏览器查看
![issue](https://user-images.githubusercontent.com/9425478/35380705-0a1dcb22-01f5-11e8-81fd-184d001b615d.jpg)

# 环境 
chrome  63.0.3239.132（正式版本） （32 位）
windows 10 64bit

**Comment by chenshuai2144** [comment]
没看懂你要做什么？

**Comment by taoeer** [comment]
![d](https://user-images.githubusercontent.com/9425478/35419892-8a9928e8-0275-11e8-8fa8-8e2b0858ca6f.jpg)
打包后字体显示不正确

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35420050-67858fc6-0276-11e8-8ca2-b3cc2cdcb39c.png)

这个字符串拷贝出来。让我看看

**Comment by taoeer** [comment]
Monospace Number,Chinese Quote,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif

**Comment by chenshuai2144** [comment]
Monospace `Number`,Chinese Quote,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif
是你自己写进去的吗？

**Comment by taoeer** [comment]
并不是自己加的！用ant-design-pro-cli创建项目之后并没有做任何修改

**Comment by chenshuai2144** [comment]
antd 那边加的，你去那边提一下把。。。
`Monospace Number` chrome 无法识别。

**Comment by taoeer** [comment]
好点，thx
