### ISSUE TITLE
Ant Pro 安装成功后，启动失败 🐛[BUG]

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/ant-design-pro#8132]
### 🐛 bug 描述

``

### 📷 复现步骤

```
╰ yarn start           
yarn run v1.16.0
$ cross-env UMI_ENV=dev umi dev
Starting the development server...

✖ Webpack
  Compiled with some errors in 1.28m

 ERROR  Failed to compile with 3 errors                                                                                                                                                        12:02:36 PM

These relative modules were not found:

* ../../../app in ./.umi/plugin-initial-state/models/initialState.ts
* ../global.less in ./.umi/umi.ts
* ../global.tsx in ./.umi/umi.ts

```

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zhengAnBin** [comment]
me too，解决了吗？我安装了echarts-wordcloud之后umi在node_modules包好像就丢失了。然后我就把整个node_modules删除重装。再自动的时候就出现和你一样的情况。app.tsx global.less global.tsx这些在我的src文件下是存在!没动过

**Comment by MaybeLin** [comment]
一样的~~~

**Comment by lxztrue** [comment]
me too

**Comment by lxztrue** [comment]
上午还高兴着,这咋就出问题了

**Comment by chenshuai2144** [comment]
@sorrycc   云谦老师看看，是不是 umi 发版本了

**Comment by zjh599245299** [comment]
一样的问题 手工修改.umi下的这三个地方的引用就能进入  但是重启又会重置掉了

**Comment by zhengAnBin** [comment]
> 一样的问题 手工修改.umi下的这三个地方的引用就能进入 但是重启又会重置掉了

怎么改能运行起来啊？暂时先跑起来再说

**Comment by zjh599245299** [comment]
> > 一样的问题 手工修改.umi下的这三个地方的引用就能进入 但是重启又会重置掉了
> 
> 怎么改能运行起来啊？暂时先跑起来再说

* ../../../app in ./.umi/plugin-initial-state/models/initialState.ts
* ../global.less in ./.umi/umi.ts
* ../global.tsx in ./.umi/umi.ts   这两个文件的三个地方加上src   ../../../src/app   ../src/global.less ../global.tsx   要运行后再改哦 一旦重新运行就又覆盖掉了

**Comment by 569202812** [comment]
me too

**Comment by xiaodin1** [comment]
我也遇到这个问题了~

**Comment by zhengAnBin** [comment]
> > > 一样的问题 手工修改.umi下的这三个地方的引用就能进入 但是重启又会重置掉了
> > 
> > 
> > 怎么改能运行起来啊？暂时先跑起来再说
> 
> * ../../../app in ./.umi/plugin-initial-state/models/initialState.ts
> * ../global.less in ./.umi/umi.ts
> * ../global.tsx in ./.umi/umi.ts   这两个文件的三个地方加上src  改成 ../../../src/app   ../src/global.less ../global.tsx   要运行后再改哦 一旦重新运行就又覆盖掉了

我改了，保存但不会刷新
访问出现一大推这样的东西

UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at C:\Users\Win10\Desktop\dev\data-visualization\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (C:\Users\Win10\Desktop\dev\data-visualization\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at C:\Users\Win10\Desktop\dev\data-visualization\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:188:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Win10\Desktop\dev\data-visualization\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (C:\Users\Win10\Desktop\dev\data-visualization\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zhengAnBin** [comment]
> > > 一样的问题 手工修改.umi下的这三个地方的引用就能进入 但是重启又会重置掉了
> > 
> > 
> > 怎么改能运行起来啊？暂时先跑起来再说
> 
> * ../../../app in ./.umi/plugin-initial-state/models/initialState.ts
> * ../global.less in ./.umi/umi.ts
> * ../global.tsx in ./.umi/umi.ts   这两个文件的三个地方加上src  改成 ../../../src/app   ../src/global.less ../global.tsx   要运行后再改哦 一旦重新运行就又覆盖掉了

好了跑起来了，修改项目根目录下的.umi文件。而不是src下的.umi文件
谢谢啦

**Comment by quicklearning123** [comment]
为啥生成了两.umi文件夹。。根目录一个，src下一个

**Comment by zhengAnBin** [comment]
我看了我以前的项目。根目录下是没有这个.umi文件。
这个问题估计就是框架读取了根目录的.umi所以出现了路径错误

**Comment by chenshuai2144** [comment]
可以先删除dumi 的依赖。

@umijs/preset-dumi 这个依赖删除一下试试

**Comment by zhengAnBin** [comment]
npm uninstall @umijs/preset-dumi 可以解决

**Comment by chenshuai2144** [comment]
fix in dumi@1.1.7
