### ISSUE TITLE
🧐[问题] 路由可以不使用dynamicImport吗？

### ISSUE THREAD

**Issue by chang-ke** [ant-design/ant-design-pro#8135]
### 🧐 问题描述

路由可以不使用dynamicImport吗？页面loading过多影响体验，document.ejs第一个，dynamicImport第二个，加上业务自己的三个，所以想去掉动态引入组件

**Comment by chenshuai2144** [comment]
https://umijs.org/config#dynamicimport

看这个配置

**Comment by chang-ke** [comment]
@chenshuai2144 关闭之后其他需要动态引入的，需要自己拿umi dynamic包一下？其实我是挺希望router.ts里面可以增加dynamic: boolean选项

**Comment by chenshuai2144** [comment]
一个个的还是不支持的，你可能需要一个  webpack 大师
