### ISSUE TITLE
🐛[BUG] <EditableProTable> 中配置列为select类型后，用optionFilterProp 指定options中对象的任意属性，过滤不起作用了（以前行，最近更新组件后就不起做用了）

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/ant-design-pro#8136]
### 🐛 bug 描述
我在<EditableProTable> 中配置列为select类型后，用optionFilterProp 指定options中的query属性（query是我自己定义用做模糊查询），现在不起作用了，最近更新后就不起做用了。。
比如：options中对象格式为：{ value: '1', label: '海星水产11', search: 'hxsc' }, 无法options中的query指定search作为过滤项
另外：filterOption的值貌似也反了，如果设置为 TRUE 则不按value搜索，官方为false
注：我提了这个问题给Ant design官方，他们回复就是这么实现的，optionFilterProp 的值可以是任意属性。详见[#29506](https://github.com/ant-design/ant-design/issues/29506#issue-816721681)

这是我的写法：在EditableProTable中，我一个列需要用到下拉select并且根据这个Lable的【拼音大写字母或其他助记符】作为搜索依据，过滤出想要的options，所以我用一个【search】字段做模糊搜索，下面是我这个select列的配置
{
      title: '供应商',
      dataIndex: 'vendorId',
      valueType: 'select',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
        ],
      },
      fieldProps: {
        allowClear: false,
        defaultActiveFirstOption: true,
        filterOption: false,//设置true则不按value查询，这个和官方是反的
        showSearch: true,
        options: [
          { value: '1', label: '海星水产11', search: 'hxsc' },
          { value: '2', label: 'A+ BuffetSushi', search: 'A+ BuffetSushi' },
          { value: '3', label: '强生农场', search: '强生农场;qsnc' },
          { value: '4', label: '焯记副食', search: '焯记副食;zjfs' },
          { value: '5', label: '海大富海产', search: 'dfhc;大富海产' },
          { value: '6', label: 'Fresh Basket Ltd', search: 'Fresh Basket Ltd' },
        ],
        **optionFilterProp: 'search',**
      },
      hideInSearch: true,
      width: 150,
    },

### 📷 复现步骤
1、设置columns中供应商字段的fieldProps/options[], 
2、增加一个【search】属性，比如 海星水产----按拼音首字母（search）过滤----{ value: '1', label: '海星水产11', search: 'hxsc' },
3、运行测试，无法按指定的search过滤

希望能解决，谢谢

### 🏞 期望结果
期望可以optionFilterProp起作用，可以按照任意字段做过滤

### 💻 复现代码
import { PageContainer } from '@ant-design/pro-layout';
import React, { useState, useEffect } from 'react';
import { Button, Input, Space, Row, Col, Form, Card, Descriptions, Tooltip } from 'antd';
// 自定义项目图标
import styles from './index.less';
import { EditableProTable } from '@ant-design/pro-table';

const StatisticTable = (props) => {
  const [form] = Form.useForm();
  const [editableKeys, setEditableRowKeys] = useState([]);

  useEffect(() => {
    //setSupplierSelectOptionResult([...supplierSelectOption])
  });

  const columns = [
    { title: '#', dataIndex: 'index', valueType: 'indexBorder', fixed: 'left', width: 50 },
    {
      title: '供应商',
      dataIndex: 'vendorId',
      valueType: 'select',
      formItemProps: {
        rules: [
          {
            required: true,
            message: '此项为必填项',
          },
        ],
      },
      fieldProps: {
        allowClear: false,
        defaultActiveFirstOption: true,
        filterOption: false,
        showSearch: true,
        options: [
          { value: '1', label: '海星水产11', search: 'hxsc' },
          { value: '2', label: 'A+ BuffetSushi', search: 'A+ BuffetSushi' },
          { value: '3', label: '强生农场', search: '强生农场;qsnc' },
          { value: '4', label: '焯记副食', search: '焯记副食;zjfs' },
          { value: '5', label: '海大富海产', search: 'dfhc;大富海产' },
          { value: '6', label: 'Fresh Basket Ltd', search: 'Fresh Basket Ltd' },
        ],
        optionFilterProp: 'search',
      },
      hideInSearch: true,
      width: 150,
    },
    {
      title: '采购数量',
      dataIndex: 'purchQty',
      hideInSearch: true,
      width: 100,
      // valueType: 'digit',
      align: 'right',
      valueType: 'digit',
      formItemProps: (formCell, { rowIndex }) => {
        return {
          rules: [
            { required: true, message: '此项为必填项' },
            {
              validator: (_, value) =>
                value > 0 ? Promise.resolve() : Promise.reject('数量必须>0'),
            },
          ],
        };
      },
      fieldProps: {
        onChange: () => {
          const rowKey = editableKeys[0];
          let purchQty = 0;
          let latestPurchPrice = 0;
          let total = 0;
          purchQty = parseFloat(form.getFieldValue([rowKey, 'purchQty']));
          latestPurchPrice = parseFloat(form.getFieldValue([rowKey, 'latestPurchPrice']));
          total = parseFloat(purchQty) * latestPurchPrice;
          form.setFieldsValue({ [rowKey]: { predictPurchTotal: total } });
        },
        allowClear: false,
      },
    },
  ];
  const data = {
    invoiceNum: 48, // 统计期间的单据数量，默认0
    statisticNum: 46, // 参与统计的单据数量,默认0
    unconfirmedOrderNum: 2, // 未确认订单数，默认0
    invoiceWarning: 2, // 单据检测警告,默认0
    productItems: 26, // 商品种类数(非商品分类),默认0
    vendorNum: 10, // 预计供应商数量，按照商品默认供应商计算,默认0
    predictTotal: 6890.0, // 预计金额，默认0
    productList: [
      {
        rowId: 1111,
        productCode: '565432', // 商品编码;
        productSortId: '2', // 商品分类
        // ...
        vendorId: '2', // 供应商id
        purchQty: 59, // 采购数量 默认0
        remark: '', // 行备注,默认空
      },
    ],
  };

  const [productList, setProductList] = useState(data.productList);

  return (
    <Card>
      <EditableProTable
        bordered
        rowKey="rowId"
        scroll={{ x: 1200 }}
        // 关闭默认的新建按钮
        recordCreatorProps={false}
        columns={columns}
        request={async () => ({
          data: productList,
          total: 3,
          success: true,
        })}
        value={productList}
        onChange={setProductList}
        onRow={(record) => {
          return {
            onClick: () => {
              setEditableRowKeys([record.rowId]);
            },
          };
        }}
        search={{
          optionRender: ({ searchText, resetText }, { formSearch }) => [
            <Button
              key="search"
              type="primary"
              onClick={() => {
                formSearch.submit();
              }}
            >
              {searchText}
            </Button>,
            <Button
              key="rest"
              onClick={() => {
                formSearch.resetFields();
              }}
            >
              {resetText}
            </Button>,
          ],
        }}
        editable={{
          form,
          editableKeys,
          onSave: (val) => {
          },
          onChange: setEditableRowKeys,
          actionRender: (row, config, dom) => [dom.save, dom.cancel],
        }}
        tableExtraRender={(_, ds) => (
          <Row justify="start" align="middle" className={styles.totalRow}>
            <Col span={6}>
              销货单数量:{data.invoiceNum} (未确认客户订单: {data.unconfirmedOrderNum} 价格预警:{' '}
              {data.invoiceWarning})
            </Col>
            <Col span={2}>参与统计:{data.statisticNum}单</Col>
            <Col span={2}>商品种类:{data.productItems}种</Col>
            <Col span={2}>供应商:{data.vendorNum} 家</Col>
            <Col span={2}>金额预计:${data.predictTotal}</Col>
            <Col span={10}>
              <Row justify="end" align="middle">
                <Space>

                  <Button>查看要货表</Button>
                  <Button type="primary">将结果生成要货表</Button>
                </Space>
              </Row>
            </Col>
          </Row>
        )}
      />
    </Card>
  );
};

export default class SaleStatistic extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    return (
      <PageContainer>
        <StatisticTable />
      </PageContainer>
    );
  }
}

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ibryanwu** [comment]
棒棒的

**Comment by ibryanwu** [comment]
@chenshuai2144 请问下 要更新那个组件呢？那个版本？ 谢谢了

**Comment by chenshuai2144** [comment]
git clean -dfx，然后安装
