### ISSUE TITLE
🐛[BUG]刷新浏览器导致菜单消失

### ISSUE THREAD

**Issue by xiaoxiaofan123** [ant-design/ant-design-pro#8138]
### 🐛 bug 描述

初次渲染完成菜单显示正常，刷新浏览器后，菜单消失，点击其他子tab后菜单重新显示
正常：
![image](https://user-images.githubusercontent.com/18550815/109326574-54e84a80-7892-11eb-91fe-25606c9442b3.png)

刷新浏览器后：
![image](https://user-images.githubusercontent.com/18550815/109327256-18691e80-7893-11eb-9be9-f5dc29bca89e.png)

### 🐛 复现步骤
当"@ant-design/pro-layout"为"6.4.18"时行为正常
更新为最新版后出现上述问题

### 🐛 原因猜测
调试过程中发现
```
<ProLayout
    menuDataRender={() => loopMenuItem(menuRouters)}
/>
```
刷新浏览器后 刚开始menuRouters为空，menuDataRender方法执行了。待服务端返回菜单信息，menuRouters有值后，该方法未执行，导致菜单未渲染。

**Comment by fangqibin** [comment]
请求服务端是否有用await

**Comment by chenshuai2144** [comment]
触发一些 `menu:{ loading:true }` 的更新，不然性能太差了

**Comment by gugu-lee** [comment]
你的问题解决了吗？

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn
看看这个

**Comment by liuqi1290** [comment]
有人知道如何处理么

**Comment by liuqi1290** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn
这个看了不会用   在哪里用

**Comment by fangqibin** [comment]
> https://beta-pro.ant.design/docs/advanced-menu-cn
> 这个看了不会用 在哪里用

ProLayout增加一个menu的参数
