### ISSUE TITLE
🐛[BUG]openAPi兼容性问题，如果后端生成的swagger.json里面没有operationId字段，就会报错

### ISSUE THREAD

**Issue by victorWuxz** [ant-design/ant-design-pro#8145]
### © 版本信息

- Ant Design Pro 版本: [v5]
- umi 3.3.9
- 浏览器环境：chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
把你的错误json 发出来

**Comment by victorWuxz** [comment]
{
  "swagger": "2.0",
  "info": {
    "title": "飞轮",
    "version": "last"
  },
  "basePath": "/",
  "tags": [
    {
      "name": "公共分类",
      "description": "公共分类"
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/crud/getList": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "crud列表接口",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "code": {
                  "type": "number",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "list": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "area": {
                            "type": "string"
                          },
                          "assistantName": {
                            "type": "string"
                          },
                          "beginTime": {
                            "type": "string"
                          },
                          "clazzBizNumber": {
                            "type": "number"
                          },
                          "clazzLessonName": {
                            "type": "string"
                          },
                          "clazzName": {
                            "type": "string"
                          },
                          "departmentNumber": {
                            "type": "number"
                          },
                          "departmentName": {
                            "type": "string"
                          },
                          "gradeNumber": {
                            "type": "number"
                          },
                          "gradeName": {
                            "type": "string"
                          },
                          "subjectName": {
                            "type": "string"
                          },
                          "subjectNumber": {
                            "type": "string"
                          },
                          "teacherName": {
                            "type": "string"
                          },
                          "complehensiveCount": {
                            "type": "number"
                          },
                          "complehensiveRatio": {
                            "type": "number"
                          },
                          "complehensivePrice": {
                            "type": "number"
                          }
                        },
                        "required": []
                      }
                    }
                  },
                  "required": []
                },
                "pager": {
                  "type": "object",
                  "properties": {
                    "current": {
                      "type": "number"
                    },
                    "pageSize": {
                      "type": "number"
                    },
                    "total": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/crud/upload": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "上传接口",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "number",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "fid": {
                      "type": "number"
                    },
                    "fileName": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "fid",
                    "fileName"
                  ]
                }
              },
              "required": [
                "code",
                "data"
              ]
            }
          }
        }
      }
    },
    "/api/crud/save": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "列表数据保存接口",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "root",
            "in": "body",
            "schema": {
              "type": "object",
              "title": "empty object",
              "properties": {
                "gradeNumber": {
                  "type": "number"
                },
                "departmentNumber": {
                  "type": "number"
                },
                "beginTime": {
                  "type": "number"
                },
                "teacherName": {
                  "type": "string"
                }
              },
              "required": [
                "gradeNumber",
                "departmentNumber",
                "beginTime",
                "teacherName"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "title": "empty object",
              "properties": {
                "code": {
                  "type": "number",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {}
                }
              },
              "required": [
                "code",
                "data"
              ]
            }
          }
        }
      }
    },
    "/api/crud/del": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "列表数据删除接口",
        "description": "",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "root",
            "in": "body",
            "schema": {
              "type": "object",
              "title": "empty object",
              "properties": {
                "id": {
                  "type": "number"
                }
              },
              "required": [
                "id"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "title": "empty object",
              "properties": {
                "code": {
                  "type": "number",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {}
                }
              },
              "required": [
                "code",
                "data"
              ]
            }
          }
        }
      }
    },
    "/api/crud/detail": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "列表详情",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "title": "empty object",
              "properties": {
                "code": {
                  "type": "string",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "activityName": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "activityName"
                  ]
                }
              },
              "required": [
                "code",
                "data"
              ]
            }
          }
        }
      }
    },
    "/user/getAuth.do": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "获取用户信息",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "code": {
                  "type": "number",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "accountDto": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "name": {
                          "type": "string"
                        },
                        "avatar": {
                          "type": "string"
                        },
                        "displayName": {
                          "type": "string"
                        },
                        "mobile": {
                          "type": "string"
                        },
                        "department": {
                          "type": "string"
                        },
                        "manager": {
                          "type": "string"
                        },
                        "company": {
                          "type": "string"
                        },
                        "type": {
                          "type": "number"
                        },
                        "managerId": {
                          "type": "number"
                        },
                        "title": {
                          "type": "string"
                        },
                        "allowedApps": {
                          "type": "string"
                        },
                        "hasRoles": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "name": {
                                "type": "string"
                              },
                              "createtime": {
                                "type": "number"
                              },
                              "type": {
                                "type": "number"
                              },
                              "nickName": {
                                "type": "string"
                              },
                              "appId": {
                                "type": "number"
                              },
                              "tag": {
                                "type": "string"
                              },
                              "parentAccountId": {
                                "type": "number"
                              },
                              "parentAccountRoleId": {
                                "type": "number"
                              },
                              "updated": {
                                "type": "number"
                              },
                              "status": {
                                "type": "number"
                              },
                              "openRoleUid": {
                                "type": "number"
                              },
                              "parentOpenRoleUid": {
                                "type": "number"
                              },
                              "hasPermissions": {
                                "type": "array",
                                "items": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        },
                        "currentRole": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "number"
                            },
                            "name": {
                              "type": "string"
                            },
                            "createtime": {
                              "type": "number"
                            },
                            "type": {
                              "type": "number"
                            },
                            "nickName": {
                              "type": "string"
                            },
                            "appId": {
                              "type": "number"
                            },
                            "tag": {
                              "type": "string"
                            },
                            "parentAccountId": {
                              "type": "number"
                            },
                            "parentAccountRoleId": {
                              "type": "number"
                            },
                            "updated": {
                              "type": "number"
                            },
                            "status": {
                              "type": "number"
                            },
                            "openRoleUid": {
                              "type": "number"
                            },
                            "parentOpenRoleUid": {
                              "type": "number"
                            },
                            "hasPermissions": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "tag": {
                                    "type": "string"
                                  }
                                },
                                "required": [
                                  "tag"
                                ]
                              }
                            }
                          }
                        }
                      }
                    },
                    "id": {
                      "type": "number"
                    },
                    "department": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    },
                    "grades": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "name": {
                            "type": "string"
                          },
                          "code": {
                            "type": "string"
                          },
                          "active": {
                            "type": "number"
                          },
                          "idx": {
                            "type": "number"
                          },
                          "subGrades": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          }
                        },
                        "required": [
                          "id",
                          "name",
                          "code",
                          "active",
                          "idx",
                          "subGrades"
                        ]
                      }
                    },
                    "subjects": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "name": {
                            "type": "string"
                          },
                          "abbreviation": {
                            "type": "string"
                          },
                          "active": {
                            "type": "number"
                          },
                          "idx": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "id",
                          "name",
                          "abbreviation",
                          "active",
                          "idx"
                        ]
                      }
                    }
                  }
                },
                "msg": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/crud/getFilter": {
      "post": {
        "tags": [
          "公共分类"
        ],
        "summary": "项目筛选条件枚举",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "code": {
                  "type": "number",
                  "mock": {
                    "mock": "0"
                  }
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "areaList": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "key": {
                            "type": "number"
                          },
                          "label": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "key",
                          "label"
                        ]
                      }
                    },
                    "gradeList": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "key": {
                            "type": "number"
                          },
                          "label": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "key",
                          "label"
                        ]
                      }
                    },
                    "departmentList": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "key": {
                            "type": "number"
                          },
                          "label": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "key",
                          "label"
                        ]
                      }
                    },
                    "subjectList": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "key": {
                            "type": "number"
                          },
                          "label": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "key",
                          "label"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
