### ISSUE TITLE
🧐[问题]按照官网指引 npm install 报错

### ISSUE THREAD

**Issue by guoxuncn** [ant-design/ant-design-pro#8147]
npm create umi

? Select the boilerplate type ant-design-pro
? 🧙 Be the first to experience the new umi@3 ? Pro V4
? 🤓 Which language do you want to use? TypeScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
? 🦄 Time to use better, faster and latest antd@4! antd@4

npm -v
7.6.0

npm 的话版本好像有问题,但是yarn是可以的???

npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ant-design-pro@4.5.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.14.0" from the root project
npm ERR!   peer react@">=16.9.0" from antd@4.13.0
npm ERR!   node_modules/antd
npm ERR!     antd@"^4.12.0" from the root project
npm ERR!     peer antd@"4.x" from @ant-design/pro-descriptions@1.6.3
npm ERR!     node_modules/@ant-design/pro-descriptions
npm ERR!       @ant-design/pro-descriptions@"^1.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-dom@17.0.1
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"^17.0.0" from the root project
npm ERR!   peer react-dom@">=16.9.0" from antd@4.13.0
npm ERR!   node_modules/antd
npm ERR!     antd@"^4.12.0" from the root project
npm ERR!     1 more (@ant-design/pro-descriptions)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by chenshuai2144** [comment]
command with --force, or --legacy-peer-deps

看样子是你的本地缓存有问题，你清理一下cache 吧

**Comment by waylon-gmail** [comment]
https://github.com/ant-design/ant-design-pro/issues/8139
我的是一样的问题。今天在另一台电脑工作突然发现另一台电脑没有问题，于是执行一下上述大佬说的参数，结果就可以了。
npm i --legacy-peer-deps
