### ISSUE TITLE
🧐[Question]  AntD v5 - Is there an example of wrapping the BasicLayout component with the Drawer Component.

### ISSUE THREAD

**Issue by vembarrajan** [ant-design/ant-design-pro#8149]
### 🧐 问题描述
I'm currently using Antd v5 version run time configuration. I want to wrap the BasicLayout with Drawer Component. So that i can use the drawer anywhere in the App. 

### 💻 示例代码

export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    onPageChange: () => {
      const { location } = history;
      if (!initialState?.currentUser && location.pathname !== '/user/login') {
        history.push('/user/login');
      } else if (
      ) {
        history.push('/role-selection');
      } else if (
      ) {
        console.log('Case where we do not want user to access role-selection');
        history.push('/dashboard');
      }
    },
    menuHeaderRender: undefined,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings
  };
};

![image](https://user-images.githubusercontent.com/13500667/109649968-97f03980-7b82-11eb-91aa-8697de83e677.png)

**Comment by focus0802** [comment]
try to use ```childrenRender```...
