### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by kinble** [ant-design/ant-design-pro#8150]
### 🐛 bug 描述

当项目中使用@umijs/plugin-openapi时，如果项目名称是“n”字母开头（例如: **niu-antd5**），项目编译时回出现找不到文件的问题：
This dependency was not found:
* **E:\workspaceiu-antd5**\src\.umi\plugin-openapi\openapi.tsx in ./src/.umi/core/routes.ts

文件正确的路径应该是：**E:\workspace\niu-antd5**\src\.umi\plugin-openapi\openapi.tsx

初步估计是webpackChunkName原因：
在编译生成src\.umi\core\routes.ts时，程序webpackChunkName把路径的\n解析成了换行

### 📷 复现步骤

1、引入插件@umijs/plugin-openapi
2、创建以n字母开头的项目名
3、yarn start

### 🏞 期望结果

成功启动项目

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本: 3.3.9
- 浏览器环境
- 开发环境: vscode

**Comment by chenshuai2144** [comment]
写标题
