### ISSUE TITLE
👑 [需求]可以支持多页签模式吗

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-pro#8151]
### 🥰 需求描述

可以支持多页签模式吗
![image](https://user-images.githubusercontent.com/42193371/109769996-f4606100-7c35-11eb-838e-8b7b92451a33.png)
-->

**Comment by drizzlesconsin** [comment]
#220 
#6730 
[#3091](https://github.com/umijs/umi/issues/3091)

**Comment by chenshuai2144** [comment]
有很多了，不要重复提
