### ISSUE TITLE
🧐[问题] 在 RequestInterceptor 中是否可以访问 @@initialState 的内容 ？

### ISSUE THREAD

**Issue by gaven004** [ant-design/ant-design-pro#8152]
### 🧐 问题描述

在网络请求拦截器 RequestInterceptor 中是否可以访问 全局初始数据 @@initialState 的内容？
还是需要使用LocalStorage作为存储？

**Comment by chenshuai2144** [comment]
不行得，最好写个拦截器用全局变量吧。
RequestInterceptor  不在 hooks得上下文里面

**Comment by xyzabc0004** [comment]
那这样，如果想在拦截器里面加上，token,用户名，只能把这两加再放到local storage

**Comment by xyzabc0004** [comment]
?

**Comment by chenshuai2144** [comment]
推荐用 sessionStorage，比较靠谱，或者直接用let申明变量

**Comment by xyzabc0004** [comment]
ok
