### ISSUE TITLE
build 后从本地打开html 进行页面跳转是报错 🧐[问题]

### ISSUE THREAD

**Issue by qq382724935** [ant-design/ant-design-pro#8153]
### 🧐 问题描述
想使用browser模式通过本地路径打开build后的项目，是否可行？

尝试了几种修改方式，目前项目build后从本地路径直接打开dist下的index.html ，进行页面跳转时报错(见截图)。

### 🚑 其他信息
一个很简单的github仓库，https://github.com/qq382724935/prodemo

![image](https://user-images.githubusercontent.com/24310904/109808090-aa8d7000-7c61-11eb-9a80-b1658115316a.png)

**Comment by chenshuai2144** [comment]
。。。。你至少给个url 服务器呀。连容器都没有肯定报错了。


试试 umi-serve，或者 serve ，执行以下能启动一个服务器

**Comment by qq382724935** [comment]
在开发app，想做离线h5应用，目前是把打包后的文件夹下载到手机路径上去，比如下载到file:///android/webview/prodemo，然后通过webview直接打开本地路径，如果需要容器那我这种思路就不行了？

**Comment by chenshuai2144** [comment]
一般不会这样做的，webview 只能做单页引用，你搞成hash，最好是的用http服务器，这样更新也比较方便。

缓存可以离线的方式

**Comment by qq382724935** [comment]
好的，那我换种方式，谢谢
