### ISSUE TITLE
🧐[问题]v4版本中未找到 src/pages/Authorized文件  请问在哪里  该文件什么用途

### ISSUE THREAD

**Issue by tzzqi** [ant-design/ant-design-pro#8154]
### 🧐 问题描述
如下图  想了解下源码  components/Authorized 能大致明白流程
但是我想知道 config.js  **Routes: ['src/pages/Authorized']**, 怎么关联到  components/Authorized 或者 utils/Authorized.js
问题是我根本没找到这个文件  求助各位

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20659294/109816737-06f58d00-7c6c-11eb-8c72-b501baa22b60.png)

**Comment by chenshuai2144** [comment]
是个 layout的拦截器，现在没啥用
