### ISSUE TITLE
🐛[BUG]在使用ProFormUploadButton时使用了listType='picture-card'的属性后，上传区域上传按钮和图片上传都展示了

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design-pro#8155]
![image](https://user-images.githubusercontent.com/31272499/109920319-15d45200-7cf5-11eb-8bc2-cfbd6d4e6da1.png)
上传按钮遮住了图片上传框
且图片上传框内不能添加dom

**Comment by chenshuai2144** [comment]
fixed in latest
