### ISSUE TITLE
🐛[BUG]随便用了一下 EditableProTable ，发现很多问题

### ISSUE THREAD

**Issue by qianjinzhe** [ant-design/ant-design-pro#8157]
随便用了一下 EditableProTable ，发现很多问题：
1、EditableProTable 当一列的 valueType 为 digit ，如果该cell的值为0，触发编辑动作时，展示的编辑框中不会自动填入 0，当为其它数字时会正确回填。
2、当 EditableProTable 设置了 pagination 分布时，actionRef.current?.addEditRecord?.({  }) 新建一行会清空表格所有数据。
3、actionRef.current?.addEditRecord?.({ id: '111' }) 如果设置了列默认值，即使该值是正确的，也会触发列 formItemProps->rules {min:1, max:999} 校验失败，在编辑框中手动输入“111”则不会再报错。
4、当启用了 EditableProTable 的 rowSelection 时，会与操作中的“编辑”功能不协调，比如：全选了，就不应该再能编辑；在编辑状态也不应该允许勾选；在新建一行的状态时，不应该允许全选，否则批量删除时要做很多判断……
5、在行编辑状态下，删除一行，下面的分页“第1-2页，共2页”数据没有变化。
6、希望以下提示语也像操作按钮一样默认实现中英繁三种语言，
     onlyAddOneLineAlertMessage: '只能同时新增一行',
     onlyOneLineEditorAlertMessage: '只能同时编辑一行',
     deletePopconfirmMessage: '删除此行？',
7、EditableProTable 中当一个cell的值为空时，为何总是默认展现这个杠字符：“-”，如何在当cell为空值时，不要默认显示这个“-” ？哪里可以设置不？

总之在Editable状态下，还有很多BUG，自己在ProTable下重写吧，又觉得麻烦，还是希望官方尽快完善。

**Comment by chenshuai2144** [comment]
>  1、EditableProTable 当一列的 valueType 为 digit ，如果该cell的值为0，触发编辑动作时，展示的编辑框中不会自动填入 0，当为其它数字时会正确回填。

这个是因为 antd 的 inputnumber 的格式检查

>  2、当 EditableProTable 设置了 pagination 分布时，actionRef.current?.addEditRecord?.({ }) 新建一行会清空表格所有数据。

估计触发下一页了

>  3、actionRef.current?.addEditRecord?.({ id: '111' }) 如果设置了列默认值，即使该值是正确的，也会触发列 formItemProps->rules {min:1, max:999} 校验失败，在编辑框中手动输入“111”则不会再报错。

注意下 number和 stirng 的区别

>  4、当启用了 EditableProTable 的 rowSelection 时，会与操作中的“编辑”功能不协调，比如：全选了，就不应该再能编辑；在编辑状态也不应该允许勾选；在新建一行的状态时，不应该允许全选，否则批量删除时要做很多判断……

这个感觉更像业务逻辑

> 5、在行编辑状态下，删除一行，下面的分页“第1-2页，共2页”数据没有变化。

来个重现，删除一行改变了 dataSource，因为我们内部没有用分页编辑的场景，社区也很少反馈所以这个方便几乎没有做处理

>  6、希望以下提示语也像操作按钮一样默认实现中英繁三种语言，
onlyAddOneLineAlertMessage: '只能同时新增一行',
onlyOneLineEditorAlertMessage: '只能同时编辑一行',
deletePopconfirmMessage: '删除此行？',


这个是希望用户可以自己设置，内部自定义不在上下中，而且每个人需要的提示语不同几乎每个项目都会改

> 7、EditableProTable 中当一个cell的值为空时，为何总是默认展现这个杠字符：“-”，如何在当cell为空值时，不要默认显示这个“-” ？哪里可以设置不？

这个是列的空设置，

| columnEmptyText | display when empty, display when not set `-`, false to disable this function | `string` \| `false` | false |

**Comment by qianjinzhe** [comment]
> > 1、EditableProTable 当一列的 valueType 为 digit ，如果该cell的值为0，触发编辑动作时，展示的编辑框中不会自动填入 0，当为其它数字时会正确回填。
> 
> 这个是因为 antd 的 inputnumber 的格式检查
> 
----------------------------  有什么好的解决办法吗？当后端返回的JSON数据类型改为字符串时，可以正确回填0，改为数值类型就不行。我在antd组件 “Table->可编辑单元格”的Demo中发现可以正确回填，编辑将age改为0，保存后再次编辑，可以正常回填0。

-----------------------------------------
当ProTable的一行中包括valueType 为 digit 的列时，点编辑，控制台会报以下错误，应该是官方组件报出的警告。

devScripts.js:5836 Warning: React does not recognize the `valueEnum` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `valueenum` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Warning: React does not recognize the `proFieldKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `profieldkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by chenshuai2144** [comment]
>  devScripts.js:5836 Warning: React does not recognize the valueEnum

这个更新一下版本

**Comment by qianjinzhe** [comment]
> > devScripts.js:5836 Warning: React does not recognize the valueEnum
> 
> 这个更新一下版本

pro系列组件都更新到了最新版本，还是会有这个错误。

-----

还有前面提到的这个问题一定要辛苦您处理一下：
当ProTable DataSource 只要有一列是 number 类型，且该值等于0时，点编辑，这个0不会回填到输入框中，
不管列的 valueType 是 digit 还是 string，都不会回填。

定义列的时候，其它什么属性都没加，像如下：
{
            title: '编号',
            dataIndex: 'ServiceNo',
            width: '10%',
}
formItemProps 啥的都没填，一样的没法回填。
像antd示例这种做法是没问题的：https://ant-design.gitee.io/components/table-cn/#components-table-demo-edit-row

麻烦兄弟帮忙检查是什么原因。

**Comment by qianjinzhe** [comment]
就这个number类型列0值不回填的问题解决就完美了，这样我就不用做浮层表单来编辑表格行，省事不少，一定帮忙解决一下这个问题吧

-------

还有个小问题不知是故意的还是问题：
当 ProTable 设置了 size='small'，点“密度”按钮调节“默认”、“中等”、“竖凑”都没有反应，其实最好的体验是 size 可以设置默认值，密度按钮仍然可以由用户手动调节。

**Comment by chenshuai2144** [comment]
要用 onSizeChange，这些 api 都是受控的。
