### ISSUE TITLE
👑 [需求]如何获取routes.ts自动生成的菜单格式？

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design-pro#8160]
你好，请问v5版本如何获取pro根据路由文件生成的菜单配置？

因为想从后端请求菜单配置，但是希望参考pro内置的根据路由文件自动生成的菜单格式

**Comment by birdycn** [comment]
还是希望能在页面内获取到路由格式

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/

在这个项目里
