### ISSUE TITLE
🐛[BUG] win下存放项目文件路径中的每个文件夹名字中不能有“n”开头

### ISSUE THREAD

**Issue by cometjun** [ant-design/ant-design-pro#8161]
### 🐛 bug 描述

我的项目文件存放在“D:\program\node\project”下，运行时老是提示：
This dependency was not found:

* D:\programode\project\src\.umi\plugin-openapi\openapi.tsx in ./src/.umi/core/routes.ts

To install it, you can run: npm install --save D:\programode\project\src\.umi\plugin-openapi\openapi.tsx

看第二行提示发现路径中少了“\n”，直接导致找不到文件，打开.umi\plugin-openapi\openapi.tsx，把下面路径添加“\n”保存即可正常运行

{
    "path": "/umi/plugin/openapi",
    "component": dynamic({ loader: () => import(/* webpackChunkName: 'D:__program__node__project__src__.umi__plugin-openapi__openapi' */'D:\\program\
ode\\project\\src\\.umi\\plugin-openapi\\openapi.tsx'), loading: LoadingComponent})
  },

在.umi目录下毕竟都是编译后的文件，在修改自己代码保存后，马上又出现这个错误，基本确认是路径名中有带“n”开头的文件夹在路径中被转义了
我还不熟悉umi底层代码，不知道这个文件是怎么生成的，于是把项目路径下的“node”文件夹名修改为“javascript”问题解决。

### 📷 复现步骤

把路径里其中一个文件夹修改为带“n”开头即可复现问题，
如“*\node\*”，“*\number\*”，“*\npm\*” 等等。
因生成路径时“*\\n**”刚好“\n”被转义成换行符

### 🏞 期望结果

修复因转义出现文件夹不能带n开头的问题

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本
- 浏览器环境 chrome  87.0.4280.88
- 开发环境：windows 10 x64，vscode 1.54.1

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/6015295/110189544-631e0400-7e5a-11eb-8362-87485de7cfe0.png)

**Comment by chenshuai2144** [comment]
修复了，重新更新一下依赖
