### ISSUE TITLE
v5 菜单 点击二级页面 显示的 还是一级页面的内容

### ISSUE THREAD

**Issue by MichaelHundSun** [ant-design/ant-design-pro#8163]
### 🧐 问题描述

v5 菜单 点击二级页面 显示的 还是一级页面的内容
前几天好使 ,今天突然就这样了. 新建了一个项目还是不好使

### 💻 示例代码

yarn create umi myapp
ant-design-pro
Pro V5
cd myapp && tyarn
npm run start

### 🚑 其他信息
<img width="1060" alt="WX20210306-122142@2x" src="https://user-images.githubusercontent.com/18067896/110195419-04678300-7e78-11eb-9637-d1d580bea3c5.png">
代码没有改动
红框应该是 welcom 页面 但是显示的是Admin的内容

**Comment by chengzequn** [comment]
![image](https://user-images.githubusercontent.com/13833722/110292194-c9a44d00-8027-11eb-920c-34df65b0c0e6.png)
welcom的页面不是这个吗，应该是routes.ts中component的缘故吧。
` {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        icon: 'smile',
        component: './Welcome',
      },
    ],
  },`

**Comment by Alt-er** [comment]
怎么关闭了 ，我也觉得不对

**Comment by chenshuai2144** [comment]
同时设置了 component 和 routes 就认为是个的layout了，要自己处理children
