### ISSUE TITLE
🧐[问题] ProForm 怎么实现左右布局

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/ant-design-pro#8164]
<ProForm.Group>
   // 左
  <ProForm.Group>
     {10个items}
  </ProForm.Group>
  // 右
  <ProForm.Group>
     {1个长item，比如富文本编辑器}
  </ProForm.Group>
</ProForm.Group>
按照上面这么写好像也无法做到左右，不知道有没有其他办法。

**Comment by chenshuai2144** [comment]
解决了可以写解决办法
