### ISSUE TITLE
API is not defined for ENUM type🐛[BUG]

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#8167]
### 🐛 bug 描述
I define an enum in the file typings.d.ts in services ant design pro. I get this error whenever I call enum type anywhere.

For example, in typings.d.ts 
```
  enum StatusEnum
	{
		Wait,
		GettingReady,
		Done,
		Cancel
	}
```

When I call API.StatusEnum on anywhere, I got that error --> API is not defined.

How can I solve this ?

### © 版本信息
- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
```tsx

declare namespace API {
  type CurrentUser = {}
}
```
