### ISSUE TITLE
[疑问] 左上角的logo要删掉该怎么做

### ISSUE THREAD

**Issue by taofeifanIT** [ant-design/ant-design-pro#8168]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/42193371/110284980-893fd180-801d-11eb-9911-0afe4ffa36f2.png)

我是右键把他delete掉了
![image](https://user-images.githubusercontent.com/42193371/110285038-a1afec00-801d-11eb-9533-6d285f56c728.png)
我想知道代码里该如何操作

**Comment by chengzequn** [comment]
你看一下/src/layout/basicLayout.tsx中有这样一段代码`return (
    <ProLayout
      logo={logo}
      onCollapse={handleMenuCollapse}
      onMenuHeaderClick={() => history.push('/')}
      menuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.isUrl || !menuItemProps.path) {
          return defaultDom;
        }`

把logo={logo}去掉应该就可以了。如果已解决请关闭问题

**Comment by lizhihao001** [comment]
> 你看一下/src/layout/basicLayout.tsx中有这样一段代码`return ( <ProLayout logo={logo} onCollapse={handleMenuCollapse} onMenuHeaderClick={() => history.push('/')} menuItemRender={(menuItemProps, defaultDom) => { if (menuItemProps.isUrl || !menuItemProps.path) { return defaultDom; }`
> 
> 把logo={logo}去掉应该就可以了。如果已解决请关闭问题

删掉了，logo还是存在

**Comment by chengzequn** [comment]
我尝试了一下，` logo={null}`这样logo就消失了。
![image](https://user-images.githubusercontent.com/13833722/110406114-aa0b3400-80bc-11eb-8ca2-9e80a33ded5c.png)

**Comment by k983551019** [comment]
defaultSettings 文件里的logo链接去掉

**Comment by taofeifanIT** [comment]
> > 你看一下/src/layout/basicLayout.tsx中有这样一段代码`return ( <ProLayout logo={logo} onCollapse={handleMenuCollapse} onMenuHeaderClick={() => history.push('/')} menuItemRender={(menuItemProps, defaultDom) => { if (menuItemProps.isUrl || !menuItemProps.path) { return defaultDom; }`
> > 把logo = {logo}去掉应该就可以了。如果已解决请关闭问题
> 
> 删掉了，logo还是存在

v5  src下面已经没有layout文件了
![image](https://user-images.githubusercontent.com/42193371/110414726-679d2380-80cb-11eb-9e23-2714170f75a3.png)

**Comment by chengzequn** [comment]
> > > 你看一下/src/layout/basicLayout.tsx中有这样一段代码`return ( <ProLayout logo={logo} onCollapse={handleMenuCollapse} onMenuHeaderClick={() => history.push('/')} menuItemRender={(menuItemProps, defaultDom) => { if (menuItemProps.isUrl || !menuItemProps.path) { return defaultDom; }`
> > > 把logo = {logo}去掉应该就可以了。如果已解决请关闭问题
> > 
> > 
> > 删掉了，logo还是存在
> 
> v5 src下面已经没有layout文件了
> ![image](https://user-images.githubusercontent.com/42193371/110414726-679d2380-80cb-11eb-9e23-2714170f75a3.png)

V5的版本可以在defaultSettings.ts文件中将logo设置为null,就可以了。
![image](https://user-images.githubusercontent.com/13833722/110446455-27a16500-80fa-11eb-8e3e-80e7b1e31147.png)
另外给一个好的建议，提问题的时候最好按官方的要求模板，把使用的版本信息等描述清楚。

**Comment by taofeifanIT** [comment]
> > > > 你看一下/src/layout/basicLayout.tsx中有这样一段代码`return ( <ProLayout logo={logo} onCollapse={handleMenuCollapse} onMenuHeaderClick={() => history.push('/')} menuItemRender={(menuItemProps, defaultDom) => { if (menuItemProps.isUrl || !menuItemProps.path) { return defaultDom; }`
> > > > 把logo = {logo}去掉应该就可以了。如果已解决请关闭问题
> > > 
> > > 
> > > 删掉了，logo还是存在
> > 
> > 
> > v5 src下面已经没有layout文件了
> > ![image](https://user-images.githubusercontent.com/42193371/110414726-679d2380-80cb-11eb-9e23-2714170f75a3.png)
> 
> V5的版本可以在defaultSettings.ts文件中将logo设置为null,就可以了。
> ![image](https://user-images.githubusercontent.com/13833722/110446455-27a16500-80fa-11eb-8e3e-80e7b1e31147.png)
> 另外给一个好的建议，提问题的时候最好按官方的要求模板，把使用的版本信息等描述清楚。

好的，我会注意要求模板的。这个已经问题解决了，感谢感谢！
