### ISSUE TITLE
🧐 请问有多个proxy在开发环境如何做选择

### ISSUE THREAD

**Issue by acsamson** [ant-design/ant-design-pro#8169]
### 🧐 问题描述

目前看到配置文档是只有配置一个代理地址
![image](https://user-images.githubusercontent.com/78223243/110286462-f3f20c80-801f-11eb-8008-0519b3e0eb3f.png)

但在实际开发中对接不同的服务端开发人员需要切换地址，并且使用沙盒环境也要切换代理
不想使用 npm start:服务器1 | 服务器2 这种，请问怎么解决呢？谢谢

![image](https://user-images.githubusercontent.com/78223243/110286367-c4430480-801f-11eb-9c72-bc142e2d4d3b.png)

**Comment by chengzequn** [comment]
'/app1/api': {
      target: 'http://127.0.0.1:8090/',
      changeOrigin: true,
      pathRewrite: { '^/app1/api': '/app1/api/' },
    },
    '/app2/api': {
      target: 'http://127.0.0.1:8081/',
      changeOrigin: true,
      pathRewrite: { '^/app2/api': '/app2/api/' },
    },


如上，不知道你要的是不这种。不过我这个是在.umirc.prod.js中配置的，不知道是否能给你些许帮助

**Comment by acsamson** [comment]
> '/app1/api': {
> target: 'http://127.0.0.1:8090/',
> changeOrigin: true,
> pathRewrite: { '^/app1/api': '/app1/api/' },
> },
> '/app2/api': {
> target: 'http://127.0.0.1:8081/',
> changeOrigin: true,
> pathRewrite: { '^/app2/api': '/app2/api/' },
> },
> 
> 如上，不知道你要的是不这种。不过我这个是在.umirc.prod.js中配置的，不知道是否能给你些许帮助

感谢，但不是这个，是在输入yarn start后，可以通过命令行进行选择服务器，例如：
> yarn start
please choose a server below:
1. zhangsan: http://.....
2. lisi: http://...
3. ....
> 1
choose server success...
想要这样一个效果

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/environment-manage

试试这个
