### ISSUE TITLE
npm run build报错，修复后 commit pre-commit报错

### ISSUE THREAD

**Issue by rocketRobin** [ant-design/ant-design-pro#817]
一开始运行npm run build 会报错，按照错误提示最后修复如下：
![image](https://user-images.githubusercontent.com/9987850/35428158-8ac51646-02a8-11e8-8c8b-ddd82f5fb98a.png)
![image](https://user-images.githubusercontent.com/9987850/35428165-9020598e-02a8-11e8-9da7-8b5b0fec1d83.png)
![image](https://user-images.githubusercontent.com/9987850/35428171-97c58a4c-02a8-11e8-9a86-4a31a01b3b45.png)

然后提交到我自己的代码仓库，eslint-trc可以提交，但是另外两个文件提交时会报错，如下：
![image](https://user-images.githubusercontent.com/9987850/35428231-d81c4e46-02a8-11e8-93de-900782d55504.png)
我手动运行 pre-commit如下：
![image](https://user-images.githubusercontent.com/9987850/35428258-ee87b0e4-02a8-11e8-98bd-a4908ac40254.png)
Lint也没有问题：
![image](https://user-images.githubusercontent.com/9987850/35428266-fc90f254-02a8-11e8-9d23-90327bb349e3.png)

我将这两个文件重置之后又可以提交了，这是为什么啊？怎么解决啊，Windows7 node 8.9.4
实在是无法解决了，我该怎么办？
另外为什么它只是报“:js found some errors. Please fix them and try committing again.”却不说明错误在哪里啊？求助.

**Comment by chenshuai2144** [comment]
试试 `npm run lint:fix`

**Comment by rocketRobin** [comment]
运行之后可以成功build 但是还是无法commit

**Comment by rocketRobin** [comment]
commit 还是抱那些错误
