### ISSUE TITLE
V5从服务器请求菜单

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#8170]
### 🧐 问题描述
看了V5的从服务器请求菜单，怎么感觉跟V4的一样，https://beta-pro.ant.design/docs/router-and-nav-cn#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95。
我初始化V5后看目录下已经没了/src/layout,而是从/node_module/pro-layout/下取的布局。想问一下现在V5应该怎么修改以便从服务器获取菜单。

**Comment by shaohuatsou** [comment]
我是在 app.tsx 的getinitialstate里面写的

**Comment by chengzequn** [comment]
看了一下issus中的问题，V5的菜但可以参考https://beta-pro.ant.design/docs/advanced-menu-cn.
代码的话
`
export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    try {
      const currentUser = await queryCurrentUser();
      return currentUser;
    } catch (error) {
      history.push('/user/login');
    }
    return undefined;
  };
  // 如果是登录页面，不执行
  if (history.location.pathname !== '/user/login') {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: {},
    };
  }
  return {
    fetchUserInfo,
    settings: {},
  };
}
`
