### ISSUE TITLE
没有权限的用户也可以访问页面，不会跳转到403页面🐛[BUG]

### ISSUE THREAD

**Issue by lukaiqi** [ant-design/ant-design-pro#8174]
### 🐛 bug 描述

路由router.js配置了权限为admin，使用user权限登录，浏览器输入admin的路由还是可以进入页面

### 📷 复现步骤

路由配置了authority:['admin']
使用user权限的用户进行登录
菜单成功过滤
浏览器地址栏输入admin权限的路由，可以正常进入，没有进入403页面

### 🏞 期望结果

没有路由权限的角色手动访问该页面应该返回403页面而不是没有权限的页面

### 💻 复现代码

{
                path: '/admin',
                name: 'admin',
                icon: 'crown',
                component: './Admin',
                authority: ['admin'],
                routes: [
                  {
                    path: '/admin/sub-page',
                    name: 'sub-page',
                    icon: 'smile',
                    component: './Welcome',
                    authority: ['admin'],
                  },
                ],
              },

### © 版本信息

- Ant Design Pro 版本: v4.5.0
- umi 版本: 3,2.14
- 浏览器环境: chrome 88.0.x
- 开发环境 : VSCode

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32565940/110407649-2dc62000-80bf-11eb-8c19-74ccabd9e87e.png)

**Comment by chenshuai2144** [comment]
v4 吗？ 为了稳定推荐用 v5

**Comment by lukaiqi** [comment]
> v4 吗？ 为了稳定推荐用 v5

但是v5只有ts版本，目前只会js，ts不会

**Comment by chenshuai2144** [comment]
ts 和 js 几乎没什么差别了。 ts 支持所有 js 的写法

**Comment by fangqibin** [comment]
应该是权限配置不对。菜单栏显示问题不能决定路由是否有权限访问。应该是权限判断不对，没有跳转到对应的403。

**Comment by tzcodingjs** [comment]
@lukaiqi 问题解决了吗？

**Comment by tzcodingjs** [comment]
@chenshuai2144 v4.5.0 同样遇到该问题，左侧的菜单可以通过权限设置隐藏，但是没有权限的角色还是可以通过地址栏输入地址进入页面。

**Comment by fangqibin** [comment]
v5就很好解决这个问题，v4要从后端发路由下来，显示这个权限允许访问的路由

**Comment by lukaiqi** [comment]
> v5就很好解决这个问题，v4要从后端发路由下来，显示这个权限允许访问的路由

v5好像只有ts版本了，代码里的ts部分看不懂

**Comment by lukaiqi** [comment]
> 应该是权限配置不对。菜单栏显示问题不能决定路由是否有权限访问。应该是权限判断不对，没有跳转到对应的403。

<Authorized authority={authorized.authority} noMatch={noMatch}>
        {children}
      </Authorized>
这里写死没有问题，但是代码这样取到的永远是自己的，进不到nomath

**Comment by fangqibin** [comment]
> > v5就很好解决这个问题，v4要从后端发路由下来，显示这个权限允许访问的路由
> 
> v5好像只有ts版本了，代码里的ts部分看不懂

如果有js基础的话，上手ts很快，等你用了ts，你会发现js回不去，实在太爽了。
