### ISSUE TITLE
🧐[问题]请教下页面如何封装成组件

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8175]
### 🧐 问题描述

我这边有一个ant design pro项目，想把一些页面放到内部私有的公共组件库里面，比如用户管理。这样其他项目直接用。所以需要包含网络请求，权限控制等逻辑。组件库准备用dumi和father打包，有几块不太清楚怎么处理，请教各位大佬们？

1.request
import from umi会使用主项目的app.tsx设置的拦截器吗？
npm run dev时，如何设置proxy

2.dva:
connect,model, service 三部分代码，在组件中如何处理？

3. Access
似乎是根据plugin-access+access.ts处理的，组件库是没有access.ts这些文件，组件中如何引入？

**Comment by chenshuai2144** [comment]
最好不要用组件库，用多 repo。

组件库涉及到版本管理，更新发布。还有缓存依赖非常复杂
