### ISSUE TITLE
🧐[问题]AntD Pro在本地运行后，点击设置主题色没有在线预览的那么多，这是需要下载插件么？

### ISSUE THREAD

**Issue by scj960529** [ant-design/ant-design-pro#8176]
第一此接触，有没有大佬解救以下！ 是我需要下载插件么还是？[
这是我本地跑的样式：[
![2](https://user-images.githubusercontent.com/53296612/110464329-f7fc5800-810d-11eb-9eb5-f639d59b1057.png)
]这是官网在线预览样式：(![微信图片_20210309192746](https://user-images.githubusercontent.com/53296612/110464295-edda5980-810d-11eb-8737-7fcf17bd9f41.png))
](url)

**Comment by chenshuai2144** [comment]
初始化的时候选择 全量区块就有了
