### ISSUE TITLE
ProTable分页切换pageSize后 current当前页没有重置到第一页

### ISSUE THREAD

**Issue by vinvin1022** [ant-design/ant-design-pro#8179]
浏览器版本360极速模式
![image](https://user-images.githubusercontent.com/6983089/110567598-be1e6680-818c-11eb-8656-14bd0e82ed16.png)
比如 pageSize处于20条/页 当前页current是第2页时,现切换到**10条/页**；
当前页current还是处于**第二页**，正常逻辑应该是处于**第一页**；

在其他浏览器没有这个问题

**Comment by chenshuai2144** [comment]
估计是settimeout的问题，我这次做了性能优化，等发布了再试试看
