### ISSUE TITLE
本地mock时请求的body不是json会直接400

### ISSUE THREAD

**Issue by zhiyan** [ant-design/ant-design-pro#818]
```
services:
export async function test(params) {
  return request('/test/api', {
    method: 'POST',
    body: 1,
  });
}

mock:
'POST /test/api': {}
```

会直接返回400, 报json错误, 如果body里传json， 或者header里ContentType不是'application/json', 就可以正常mock返回

**Comment by chenshuai2144** [comment]
Content-Type 请求头设置为 application/json。
json 要 JSON.stringify一下，才能传输json的

**Comment by zhiyan** [comment]
Content-Type没有问题，request的封装默认设的'application/json'.  
本地开发时如果请求body里传的不是一个json, 本地mock server会直接返回400. 
我觉得应该是mock server的问题

**Comment by zhiyan** [comment]
已找到原因，roadhog里body-parser默认是开的strict模式
