### ISSUE TITLE
🐛[BUG] npm install 后 ant-design-pro 包无限循环

### ISSUE THREAD

**Issue by usertan** [ant-design/ant-design-pro#8181]
### 🐛 bug 描述

git clone 克隆 ant-design-pro v5 版本后，npm install 能正常运行，但是 node_modules 里面的ant-design-pro 包 无限循环，而且该文件为快捷方式，导致无法压缩。

### 📷 复现步骤

git clone https://github.com/ant-design/ant-design-pro.git --branck v5 ant-design-pro-test
npm install
cd ant-design-pro-test/node_modules

bug: 
node_modules\ant-design-pro\node_modules\ant-design-pro\................

### 🏞 期望结果

希望node_modules\ant-design-pro 不为快捷方式，且能够打包压缩

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0-beta.2]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. window 10 OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/14966409/110577145-02b1fe00-819d-11eb-9f8f-af6ec490d17d.png)

**Comment by fangqibin** [comment]
是不是装依赖包有点问题

**Comment by chenshuai2144** [comment]
清楚一下你的link吧，这个一般是 link 导致的

**Comment by LianGee** [comment]
咋整噢，我也这样... v4 v5beta 都没这样过
