### ISSUE TITLE
🐛[BUG]ProFormSelect组件options属性的disabled属性无效

### ISSUE THREAD

**Issue by vinvin1022** [ant-design/ant-design-pro#8182]
### 🐛 bug 描述
正常配置ProFormSelect组件options属性的disabled属性
disabled没起作用

### 🏞 期望结果

正常禁用 或者启用

### 💻 复现代码

<ProFormSelect
              label="SKU种类"
              name="skuClassId"
              fieldProps={{
                options: [
                  { label: '品牌', value: 19, disabled: false },
                  { label: '型号', value: 18, disabled: true },
                  { label: '颜色', value: 17, disabled: false },
                ],
                showArrow: true,
              }}
            />

### © 版本信息

- Ant Design Pro 版本: e.g. 5.0.0
- umi 版本: "^3.3.7",
- 浏览器环境: Google Chrome 版本 88.0.4324.190（正式版本） （64 位）
- 开发环境: windows10

### 🚑 其他信息
pageage.json文件
"dependencies": {
    "@ant-design/charts": "^1.0.17",
    "@ant-design/icons": "^4.4.0",
    "@ant-design/pro-card": "^1.10.1",
    "@ant-design/pro-descriptions": "^1.5.0",
    "@ant-design/pro-form": "^1.15.3",
    "@ant-design/pro-layout": "^6.14.0",
    "@ant-design/pro-table": "^2.28.0",
    "@umijs/route-utils": "^1.0.34",
    "ahooks": "^2.9.6",
    "antd": "^4.12.1",
    "classnames": "^2.2.6",
    "cookies-utils": "^1.0.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "omit.js": "^2.0.2",
    "qs": "^6.9.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet-async": "^1.0.7",
    "react-simple-verify": "^1.0.8",
    "umi": "^3.3.7",
    "umi-request": "^1.3.5",
    "use-merge-value": "^1.0.2"
  },

**Comment by chenshuai2144** [comment]
修复了，已发布
