### ISSUE TITLE
🧐[问题]点击左侧菜单时加载页面，右侧的loading在哪里修改啊？

### ISSUE THREAD

**Issue by shaohuatsou** [ant-design/ant-design-pro#8185]
![image](https://user-images.githubusercontent.com/50793943/110732995-25f1b180-8260-11eb-8252-bceaf69a6457.png)

**Comment by firstmetcs** [comment]
应该是这个吧

![image](https://user-images.githubusercontent.com/32634443/115366846-3c444300-a1f8-11eb-8022-c578f903ecc4.png)
