### ISSUE TITLE
How to enable enableMapSet() in config.ts ?

### ISSUE THREAD

**Issue by PunKHS** [ant-design/ant-design-pro#8187]
### 🧐 问题描述
I would like to use Map structure like this for my model:
`example: Map<number, Object>;`

When I start my app, I see the error in the console:  
`devScripts.js:5836 uncaught at _callee Error: [Immer] The plugin for 'MapSet' has not been loaded into Immer. To enable the plugin, import and call `enableMapSet()` when initializing your application.`

I tried to change config.ts like this:
`export default defineConfig({
...
  dva: {
    hmr: true,
    immer: { enableMapSet: true },
  },
...
}`
and restart my app, but it not works.

### 💻 示例代码
my package.json contains: 
`"dva": "^2.6.0-beta.22", "umi": "^3.3.9",`

**Comment by chenshuai2144** [comment]
Immer and map conflict a little bit. 

https://immerjs.github.io/immer/docs/map-set


you can set  `dva :{  immer: false }`
