### ISSUE TITLE
🐛[BUG][v5]新建规则不显示label

### ISSUE THREAD

**Issue by lahvey** [ant-design/ant-design-pro#8188]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/892983/110880803-251d5600-831a-11eb-9df7-5da393ebab07.png)

### 📷 复现步骤
新建V5项目
```bash
npm create umi
npm install --legacy-peer-deps
node node_modules/esbuild/install.js
npm start
```

同时这个新建表单没法配置placeholder。

### © 版本信息

- Ant Design Pro 版本: [5.0.0-beta.2]
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
这个是个什么提示？ 是插件的吗?

**Comment by lahvey** [comment]
对的 ，应该是npm Intellisense的vscode插件，检测到项目里面没有用到，但是出现在 了node_modules，没什么关系

**Comment by chenshuai2144** [comment]
umi的自动注册机制，还是很好用的。先忽略好了
