### ISSUE TITLE
在userModel中使用国际化报错！🧐[问题]

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design-pro#8189]
### 🧐 问题描述

我在userModel中请求接口需要返回一些错误信息出来， 当我引入
import { FormattedMessage, useIntl } from 'umi';
  const intl = useIntl();
就报错
plugin-model: Invoking 'entryStore' model failed: Error: [React Intl] Could not find required `intl` object.

### 💻 示例代码
创建一个useModel 文件
import { FormattedMessage, useIntl } from 'umi';
export default function EntryStore(){
  const intl = useIntl();

  return {
       .....
    }
}

**Comment by chenshuai2144** [comment]
不要在 hooks 里面套 hooks。很容易挂。

最好在组件里面做。不然 provide 拿不到了是没法办初始化成功的。因为useModal 的时机比较早
