### ISSUE TITLE
Pie 图表当初始数据为空数组时，加载数据后 legendData 为空。

### ISSUE THREAD

**Issue by ibufu** [ant-design/ant-design-pro#819]
version: v1.0.1

```js
// getLengendData()
geom.get('dataArray') || [];
```
应该是这里的数据还没更新。

**Comment by weifansc** [comment]
似乎碰到了同样的问题， version 1.1.0

**Comment by chenshuai2144** [comment]
pie的percent为空？

**Comment by ibufu** [comment]
我看源代码，prop改变的时候取 legendData ，取的不是新的prop的数据

**Comment by chenshuai2144** [comment]
我无法再现。
给个详细的步骤吧。
设置了percent为空。然后附加数据是可以的

**Comment by ibufu** [comment]
1.先设置 data 为空数组
2.然后再给 data 填入数据
这个时候 pie 图有数据了，但是 legend 没有出现

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35472850-cb9061c6-03b1-11e8-8a09-dad26d4ec9ee.png)

pie没有data属性呀

**Comment by ibufu** [comment]
```
ReactDOM.render(
  <Pie
    hasLegend
    title="销售额"
    subTitle="销售额"
    total={yuan(salesPieData.reduce((pre, now) => now.y + pre, 0))}
    data={salesPieData}
    valueFormat={val => yuan(val)}
    height={294}
  />
, mountNode);
```
好吧，文档的实例代码是这样的。。

**Comment by chenshuai2144** [comment]
估计是文档没写好。。
@nikogu 。看一看

**Comment by ibufu** [comment]
我确认了一下，是文档写漏了，图表数据确实是用 data 这个 prop 的。更新到v1.1.0后bug依然存在。

**Comment by TDiDa** [comment]
我这也遇到pie组件的legend数据只会显示上个props的数据
