### ISSUE TITLE
🧐[问题] 请问大家如何解决在执行Ctrl + F5 （刷新）显示 的“Pro”页面

### ISSUE THREAD

**Issue by Shi-Cheng** [ant-design/ant-design-pro#8197]
在执行Ctrl + F5 刷新页面时显示  带有“Pro”的背景，请问大家如何解决这个问题的？相关的配置项是哪个呢？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/bc946642dae04e8c69692a012d20ae601d78adb3/src/pages/document.ejs
看这里

**Comment by Shi-Cheng** [comment]
非常感谢您的答复，问题已经解决。


谢谢帮助













|
NamePenov
***@***.***
公司名称:Guizhou University
地址：Guiyang, China
Telephone:
Cellphone:
A strong man will struggle with the storms of fate.
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|




在 2021-03-14 10:39:37，"陈帅" ***@***.***> 写道：

Closed #8197.

**Comment by G-02** [comment]
> https://github.com/ant-design/ant-design-pro/blob/bc946642dae04e8c69692a012d20ae601d78adb3/src/pages/document.ejs 看这里
不好意思 并没有看懂这个 可以再详细说下么
