### ISSUE TITLE
🐛[BUG] Pro v4 侧边栏二级菜单icon 无法显示，或者位置显示问题

### ISSUE THREAD

**Issue by Shi-Cheng** [ant-design/ant-design-pro#8198]
### 🐛 bug 描述
二级菜单 icon 无法显示；
通过配置 menuItemRender 和 subMenuItemRender 属性，菜单展开情况下可以显示，但是 菜单在缩放的模式下，显示出现错位。

**Comment by chenshuai2144** [comment]
无法显示的是设计师的设计，menuItemRender返回的时候主要要返回两个 dom，menu 的动画是根据dom 的数量来确定的

**Comment by Shi-Cheng** [comment]
您好，陈师傅，
        谢谢您的解答。初次上车Pro，还不够顺手。
        这边再请教一个问题：请求服务器资源，访问URL的配置。
        A：请问您在项目开发中如何 解决这个问题的呢？（PS： 如果有对应的案例就更感激不尽了）
        B：下面是我这边进行的相关配置，麻烦您那边指导一下。
再次感谢您的答复，
潘世成
2021-03-14


        我这边是如下配置的：
（1）根目录下新建sysConfig.js, 内容如下
module.exports = {
  // 开发环境
  development: {
    API_SERVER: 'http://mock-api.com/9KOGMkKk.mock'
  },
  // 生产环境
  production: {
    API_SERVER: 'http://******com'
  }
}


(2)在 config 文件下的config.js文件中引入。主要内容 如下
import defaultSysConfig from '../sysConfig'


export default defineConfig({
define: {
    APP_TYPE: APP_TYPE || '',
    'process.env': {
      NODE_ENV,
      ...(NODE_ENV === 'development' ? defaultSysConfig.development: defaultSysConfig.production)
    }
  },
})


（3）在 request.js文件中引入，主要内容如下
request.interceptors.request.use(async (url, options) => {
  // console.log('url', url)
  let c_token = localStorage.getItem("x-auth-token");
   if (c_token) {
     const headers = {
       'Content-Type': 'application/json',
       'Accept': 'application/json',
       'x-auth-token': c_token
     };
     return (
       {
         url: url,
         options: { ...options, headers: headers },
       }
     );
   } else {
     const headers = {
       'Content-Type': 'application/json',
       'Accept': 'application/json',
       'x-auth-token': c_token
     };
     return (
       {
         url: url,
         options: { ...options },
       }
     );
   }
   if(options.mock){
     delete options.mock;
   }else{
     // url = configs[process.env.API_ENV].API_SERVER+url;
     // 配置地址
      url = process.env.API_SERVER + url
      console.log(url)
   }
   return (
     {
       url: url,
       options: { ...options },
     }
   );
  
 })
  
 // response拦截器, 处理response
 request.interceptors.response.use((response, options) => {
  let token = response.headers.get("x-auth-token");
   if (token) {
    localStorage.setItem("x-auth-token", token);
   }
   return response;
 });
























        













|
NamePenov
***@***.***
公司名称:Guizhou University
地址：Guiyang, China
Telephone:
Cellphone:
A strong man will struggle with the storms of fate.
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|




在 2021-03-14 10:41:21，"陈帅" ***@***.***> 写道：

无法显示的是设计师的设计，menuItemRender返回的时候主要要返回两个 dom，menu 的动画是根据dom 的数量来确定的

**Comment by chenshuai2144** [comment]
用 proxy，你的方法有点 hack。

https://umijs.org/config#proxy

**Comment by chenshuai2144** [comment]
```
const menuItemRender = (menuItemProps, defaultDom) => {
  if (
    menuItemProps.isUrl ||
    !menuItemProps.path ||
    location.pathname === menuItemProps.path
  ) {
    return defaultDom;
  }

  return (
    <Link to={menuItemProps.path}>
      {menuItemProps.icon}
      {defaultDom}
    </Link>
  );
};
```

**Comment by feicemoon** [comment]
> 显示二级图标
> 
> ```
> const menuItemRender = (menuItemProps, defaultDom) => {
>   if (
>     menuItemProps.isUrl ||
>     !menuItemProps.path ||
>     location.pathname === menuItemProps.path
>   ) {
>     return defaultDom;
>   }
> 
>   return (
>     <Link to={menuItemProps.path}>
>       {menuItemProps.icon}
>       {defaultDom}
>     </Link>
>   );
> };
> ```

点击子菜单以后icon还是会消失
