### ISSUE TITLE
🐛[BUG] 预览无法连接服务器

### ISSUE THREAD

**Issue by 010deng** [ant-design/ant-design-pro#8199]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 010deng** [comment]
复现步骤直接访问  https://preview.pro.ant.design/dashboard/analysis?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false

**Comment by chengzequn** [comment]
不知道你说的啥

**Comment by 010deng** [comment]
有一小段时间访问服务不通，现已恢复，我close了

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日(周一) 上午10:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design-pro] 🐛[BUG] 预览无法连接服务器 (#8199



 
不知道你说的啥
