### ISSUE TITLE
🧐[问题] 请问怎么替换掉 antd 的 样式文件，找不到 antd/dist/antd.css  是哪里引入的

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design-pro#8200]
### 🧐 问题描述

我自己 fork 了一份 antd，修改了样式，打包后有 dist/my-ui.css。我想替换掉 ant-design-pro 的样式，有什么办法吗？如果在 global.less 里面引入，只是会覆盖了原来的，原来的有一些样式还会在。我想删掉原来的，使用我自己的这份样式，有什么办法吗

**Comment by hemengke1997** [comment]
请问老哥是怎么搞定的

**Comment by linxianxi** [comment]
> 请问老哥是怎么搞定的

好像是 config.ts 设置 antd:false，太久了

**Comment by hemengke1997** [comment]
我把antd关了，打包之后还是会全量引入antd的样式 T>T
