### ISSUE TITLE
🧐[问题] React design pro4 开发环境URL配置？

### ISSUE THREAD

**Issue by Shi-Cheng** [ant-design/ant-design-pro#8201]
### 🧐 问题描述
    请问在项目开发中，如何配置请求服务端地址。比如本机地址为：192.168.1.1，服务端地址为： 192.168.1.2: 8081。

个人进行如下操作：在 proxy.js 文件中
### 💻 示例代码
export default {
  dev: {
    '/api/': {
      target: 'http://192.168.1.2:8081',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
  test: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
  pre: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
};

完成这块配置后
但是在开发中却还是无法访问 192.168.1.2: 8081
以登录为例：
【点击】登录按钮后，地址栏依旧是请求本机资源  http://localhost:2529/user/login。

初次使用pro4， 遇到了很多问题，也希望社区越来越完善。

**Comment by chenshuai2144** [comment]
proxy 的工作原理看这里

https://pro.ant.design/blog/proxy-cn
它不会改变访问你的 url 的。

**Comment by Shi-Cheng** [comment]
> proxy 的工作原理看这里
> 
> https://pro.ant.design/blog/proxy-cn
> 它不会改变访问你的 url 的。

您好，如果采用这种配置方式，资源连接 【https://www.freesion.com/article/44121127088/】，请问 proxy 如何配置呢？

**Comment by chenshuai2144** [comment]
去查查文档这个很简单

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/environment-manage
