### ISSUE TITLE
🧐[问题] 简单的登录配置，希望大神指点一下：Access to fetch at 'http://192.168.2.160:8043/user/login' from origin 'http://localhost:2529' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### ISSUE THREAD

**Issue by Shi-Cheng** [ant-design/ant-design-pro#8203]
### 🧐 问题描述
Access to fetch at 'http://192.168.2.160:8043/user/login' from origin 'http://localhost:2529' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

开发环境中的配置：

/**
 * 在生产环境 代理是无法生效的，所以这里没有生产环境的配置
 * The agent cannot take effect in the production environment
 * so there is no configuration of the production environment
 * For details, please see
 * https://pro.ant.design/docs/deploy
 * http://159.75.22.181:9099
 */
export default {
  dev: {
    '/api/': {
      target: 'http://192.168.2.160:8043',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
  test: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
  pre: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
  },
};

**Comment by chenshuai2144** [comment]
跨域了。

https://pro.ant.design/blog/proxy-cn

搜一下文章，我记得阮一峰写了一篇不错的

**Comment by Shi-Cheng** [comment]
谢谢您的答复。这边有个应用场景，前端pro项目已经部署在生产环境，但是请求资源地址依旧是本地开发环境服务接口，假设生产环境地址为：192.168.1.10， 本地后端服务器地址为：192.168.1.2:8080。请问这种情况如何进行配置呢?

**Comment by Shi-Cheng** [comment]
> 跨域了。
> 
> https://pro.ant.design/blog/proxy-cn
> 
> 搜一下文章，我记得阮一峰写了一篇不错的

谢谢您的答复。这边有个应用场景，前端pro项目已经部署在生产环境，但是请求资源地址依旧是本地开发环境服务接口，假设生产环境地址为：192.168.1.10， 本地后端服务器地址为：192.168.1.2:8080。请问这种情况如何进行配置呢?

**Comment by hooliy** [comment]
> > 跨域了。
> > https://pro.ant.design/blog/proxy-cn
> > 搜一下文章，我记得阮一峰写了一篇不错的
> 
> 谢谢您的答复。这边有个应用场景，前端pro项目已经部署在生产环境，但是请求资源地址依旧是本地开发环境服务接口，假设生产环境地址为：192.168.1.10， 本地后端服务器地址为：192.168.1.2:8080。请问这种情况如何进行配置呢?

nginx代理
