### ISSUE TITLE
umi build后如何获取webpack编译日期以便在页面展示版本迭代🧐[问题]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#8204]

**Comment by lishaoh** [comment]
目前想在页面中显示系统迭代版本，需要显示版本更新的时间，那就应该是webpack编译成功后的时间，如何输出这个时间呢？？

**Comment by chenshuai2144** [comment]
https://umijs.org/config#define

试试这个，在编译的一瞬间生效，你可以在界面中直接使用
