### ISSUE TITLE
👑 [需求] V5 openapi文档能不能同时加多个，现在都是微服务了

### ISSUE THREAD

**Issue by internet5** [ant-design/ant-design-pro#8205]
### 🥰 需求描述

openapi文档配置中能不能同时加多个配置，现在都是微服务了，只能配置一个，生成代码的时候，还要注释掉一个写另一个来在跑生成，很不方便

### 🧐 解决方案

配置中的openAPI项改成数组形式

**Comment by quicklearning123** [comment]
建议做好服务之间的隔离，比如放在不同目录下面，防止重名的请求url
