### ISSUE TITLE
🐛[BUG] Failed at the ant-design-pro@5.0.0-beta.2 start script.

### ISSUE THREAD

**Issue by yao978318542** [ant-design/ant-design-pro#8207]
按照官网的步骤一步一步来的 还是报错了
node v14.16.0
python 3.6.8
![image](https://user-images.githubusercontent.com/18590746/111128681-223b9300-85b0-11eb-9b02-58e300df4dea.png)
![image](https://user-images.githubusercontent.com/18590746/111128764-3da69e00-85b0-11eb-896f-2c96ecab1a63.png)
![image](https://user-images.githubusercontent.com/18590746/111128826-531bc800-85b0-11eb-834a-890a0e697feb.png)

**Comment by chenshuai2144** [comment]
依赖没安装完成，使用 tyarn 和 cnpm 能提高成功率

**Comment by yao978318542** [comment]
@chenshuai2144  可以了谢谢！

**Comment by yao978318542** [comment]
@chenshuai2144 
我启动的时候已经加上HOST=0.0.0.0 环境变量 为什么还是链接失败呢 是在服务器上安装的 
![image](https://user-images.githubusercontent.com/18590746/111246491-527f4200-8641-11eb-89a1-c74f41578ea7.png)
![image](https://user-images.githubusercontent.com/18590746/111246505-58752300-8641-11eb-92b4-a7213eb659e0.png)
