### ISSUE TITLE
🐛[BUG] 顶部导航栏多级菜单，鼠标移入报错

### ISSUE THREAD

**Issue by jing-wu** [ant-design/ant-design-pro#8208]
### 🐛 bug 描述

使用 BasicLayout，切换为顶部导航布局，鼠标移入多级菜单，不出现子菜单弹层，控制台报错；在左侧菜单的模式下，一切正常。

[找到一个类似的问题：https://stackoverflow.com/questions/65179745/typeerror-cannot-read-property-getstate-of-null](https://stackoverflow.com/questions/65179745/typeerror-cannot-read-property-getstate-of-null)

### © 版本信息

- Ant Design Pro 版本: 4.x
- umi 版本：3.4.2
- pro-layout 版本：6.3.0
- antd 版本：4.10.2
- 浏览器环境：chrome 89
- 开发环境：win10

### 🚑 其他信息

<img width="689" alt="WX20210316-113103@2x" src="https://user-images.githubusercontent.com/6805536/111251973-25d02800-864b-11eb-8848-0f579c0eb2e2.png">

**Comment by chenshuai2144** [comment]
看起来是ant menu  的问题，更新下antd 的版本再试试呢
