### ISSUE TITLE
🧐[问题] 关于queryCurrentUser

### ISSUE THREAD

**Issue by zy0228** [ant-design/ant-design-pro#8209]
### 🧐 问题描述

关于#V5版本queryCurrentUser有些疑问：
queryCurrentUser是获取用户信息，如果失败就跳转login页面；
但是通过查看network这个请求发现并没有携带任何数据；但是queryCurrentUser依然可以鉴别是否登录怎么做到的~疑惑了很久从代码上看不出端倪，是你们服务端做的处理吗？请告知 谢谢

**Comment by chenshuai2144** [comment]
mock里面做的处理，login 执行之后会做个标记。

你可以在 mock/login 里找到
