### ISSUE TITLE
🧐[问题] V5 大概什么时候 realease 呢

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design-pro#8211]
### 🧐 问题描述

印象中 V5 试用已经好久了，希望可以有个明确的截止日期。

**Comment by ldd27** [comment]
顺便问一下现在 `master` 分支跟 `v5` 分支有什么区别？

**Comment by langengel** [comment]
master最新文件  v5 是从最新文件中提取出来都bug较少都文件  我是这样理解的

**Comment by chenshuai2144** [comment]
没时间写发布文档，等写好了就发。

**Comment by lin-mt** [comment]
> 没时间写发布文档，等写好了就发。

四月左右能发布吗

**Comment by chenshuai2144** [comment]
不影响正常使用的。迭代了这么久，稳定性肯定没问题
