### ISSUE TITLE
V5 面包屑不显示，请问可能的影响因素

### ISSUE THREAD

**Issue by Sampan-Lee** [ant-design/ant-design-pro#8216]
对项目进行了如下的改动

1. 移除国际化
2. 服务端加载菜单

config.ts 的路由结构如下  
![image](https://user-images.githubusercontent.com/34049387/111436519-0adde080-873d-11eb-95eb-cdb27a7290d6.png)

后端返回的菜单数据如下
![image](https://user-images.githubusercontent.com/34049387/111437248-d61e5900-873d-11eb-8628-7e8ea729b9c7.png)

面包屑不显示
![image](https://user-images.githubusercontent.com/34049387/111437414-07972480-873e-11eb-838d-2b4444ce6f64.png)

不知道为什么，就是不显示

**Comment by chenshuai2144** [comment]
层级太浅了，设计要求必须 3 级以上，你可以用 breadcrumbRender 在最前面加个首页来强制让其显示

| breadcrumbRender | 自定义面包屑的数据 | `(route)=>route` | - |
