### ISSUE TITLE
🐛[BUG] 生成services，报Error: not support Intl or zh-CN language

### ISSUE THREAD

**Issue by internet5** [ant-design/ant-design-pro#8217]
### 🐛 bug 描述

当前最新下载的最新pro，填上openapi数组配置后生成，控制台报错Error: not support Intl or zh-CN language

### 📷 复现步骤

当前最新下载的最新pro，填上openapi数组配置后生成

### 🏞 期望结果

正常运行

### 💻 报错信息

[openAPI]: � 将 Swagger 转化为 openAPI
(node:19344) UnhandledPromiseRejectionWarning: Error: not support Intl or zh-CN language.
    at parse (D:\CYProjects\cmii-ufb\node_modules\tiny-pinyin\dist\core.js:126:11)
    at Object.convertToPinyin (D:\CYProjects\cmii-ufb\node_modules\tiny-pinyin\dist\core.js:139:12)
    at resolveTypeName (D:\CYProjects\cmii-ufb\node_modules\@umijs\openapi\dist\serviceGenerator.js:32:34)
    at D:\CYProjects\cmii-ufb\node_modules\@umijs\openapi\dist\serviceGenerator.js:182:33
    at Array.forEach (<anonymous>)
    at D:\CYProjects\cmii-ufb\node_modules\@umijs\openapi\dist\serviceGenerator.js:181:22
    at Array.forEach (<anonymous>)
    at D:\CYProjects\cmii-ufb\node_modules\@umijs\openapi\dist\serviceGenerator.js:171:55
    at Array.forEach (<anonymous>)
    at new ServiceGenerator (D:\CYProjects\cmii-ufb\node_modules\@umijs\openapi\dist\serviceGenerator.js:169:46)
(node:19344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which 
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0-beta.2]

**Comment by chenshuai2144** [comment]
这个拼音库看起来还是不够强大

**Comment by HengCC** [comment]
有解决方案吗?

**Comment by chenshuai2144** [comment]
升级一下node，或者用 `npm i full-icu -g`

**Comment by GreatAuk** [comment]
> 升级一下node，或者用 `npm i full-icu -g`

有版本推荐，或者升级最新版本吗

**Comment by chenshuai2144** [comment]
node@14 最合适了

**Comment by lahvey** [comment]
还是换个库吧，centos上`npm i full-icu -g`也不行，为了这个升级node@14太重了

**Comment by leonkong** [comment]
同样遇到这个问题，node 10.24.1。没法升级node，牵扯太多了。

**Comment by GreatAuk** [comment]
> 同样遇到这个问题，node 10.24.1。没法升级node，牵扯太多了。

nvm 安装多个版本
