### ISSUE TITLE
🐛[BUG] v5 中layout配置menuDataRender函数只能被调用一次？

### ISSUE THREAD

**Issue by ahnuljz** [ant-design/ant-design-pro#8219]
app.tsx 配置动态菜单: 

```
export const layout = ( initialState)=> {
   return {
     menuDataRender:  (e) => {
            console.log("---menuDataRender--");
            return [];
        }
   }
}
```
组件中 const { initialState, setInitialState } = useModel('@@initialState');
第一次调用setInitialState 改变menuData后，自定义的menuDataRender函数执行了，
第二次调用setInitialState 改变menuData，无法触发menuDataRender

我用《[菜单的高级用法](https://beta-pro.ant.design/docs/advanced-menu-cn)》 中的方法动态加载菜单，可以加载，但不能多次加载

请问如何实现多次动态加载菜单？

**Comment by chenshuai2144** [comment]
```
 settings: {
      menu: {
        loading: true,
      },
    },
```
你忘记加 loading 了吧

**Comment by ahnuljz** [comment]
`
const { initialState, setInitialState } = useModel('@@initialState');
    const fetchMenuData = (index: number) => {
        setInitialState({
            ...initialState,
            settings: {
                menu: {
                    loading: true,
                },
            },
        });
        console.log(initialState);

        setInitialState({
            ...initialState,
            menuData: [],
            settings: {
                menu: {
                    loading: false,
                },
            },
        });
    };

`

**Comment by chenshuai2144** [comment]
await 一下，被 batch update 了

**Comment by loocor** [comment]
@ahnuljz 兄弟，方便贴一下配置了 `menuDataRender`  的  `app.tsx` 完整代码么，我没搞定 😂

**Comment by wushizhan** [comment]
@chenshuai2144  服务器取的菜单数据后,  怎么生成MenuDataItem 中的icon，是需要ICON组件，服务器保存的是ICON的名字，有什么生成方法吗？

**Comment by chenshuai2144** [comment]
自己写个匹配器吧

**Comment by chenshuai2144** [comment]
做了个新的api  request可以去看看怎么用
