### ISSUE TITLE
🐛[BUG]OpenAPI带file参数时生成的代码有问题

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8220]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/70048681/111473174-b7cc5380-8765-11eb-865e-426fa7d2b4be.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你的json给下

**Comment by chenshuai2144** [comment]
fix in + @umijs/openapi@1.1.13
