### ISSUE TITLE
升级了umi3 Routes  属性 权限控制失效

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design-pro#8221]
![image](https://user-images.githubusercontent.com/24559368/111562070-7cb33a00-87d0-11eb-98c1-be1048189d4e.png)
![image](https://user-images.githubusercontent.com/24559368/111562172-aff5c900-87d0-11eb-883d-591218f2ae44.png)

**Comment by 569202812** [comment]
参考下[https://beta-pro.ant.design/docs/upgrade-v5-cn](升级方案)，里面有讲解的权限相关的升级
