### ISSUE TITLE
🧐[问题]虚心求问，ant-design-pro是如何解决*.d.ts的引入问题的？

### ISSUE THREAD

**Issue by q2578443177** [ant-design/ant-design-pro#8222]
### 🧐 问题描述

我自己写的`*.d.ts`在不引入的情况下，其他文件可以识别`*.d.ts`其中的类型，但是eslin会提示类型未定义，vscode也不会有语法提示，但是假如类型写错的话，vscode就会提示了。

但是在ant-design-pro中，我发现`*.d.ts`不需要引入，不触发报错，vscode也有语法提示

所以我想求一个不引入.d.ts，不触发eslint报错，vscode也有语法提示的方案

### 💻 示例代码

```ts
// index.d.ts
interface a{
  name: string;
}
```

```ts
// test.ts
let b: a = {  //在这里eslint会提示a未定义
  name: 1  //在这里vscode会报错，number不能赋值给string，这说明vscode是已经自动引入index.d.ts的了
}
```

**Comment by chenshuai2144** [comment]
改成 .ts, d.ts 总是会被自动引入
