### ISSUE TITLE
🧐[问题]build体积过大，甚至可能内存溢出

### ISSUE THREAD

**Issue by fatesq** [ant-design/ant-design-pro#8223]
### 🧐 问题描述

使用官网最新的v5版本，build时候发现体积特别大，每个页面都会单独构建一份@antd相关进去。

### 💻 示例代码

![image](https://user-images.githubusercontent.com/11306229/111585462-4e4a5480-87fa-11eb-8f6b-98a4bfeb6376.png)

### 🚑 其他信息

将业务页面从v4迁移到v5，build出来有90多mb，单个页面都大于1mb，v4时同一个页面只有2kb，build的时候甚至有时会内存溢出

**Comment by chenshuai2144** [comment]
这个去 umi 问问试试，我试了一下不会有这个问题。是不是打开了什么不兼容的配置。

**Comment by fatesq** [comment]
> 这个去 umi 问问试试，我试了一下不会有这个问题。是不是打开了什么不兼容的配置。
上面示例代码里的图就是官方pro v5 analyze的结果，tableList有几百kb。

至于个人项目迁移v5后：
尝试用umi的splitchunks，
https://umijs.org/zh-CN/guide/boost-compile-speed#%E8%B0%83%E6%95%B4-splitchunks-%E7%AD%96%E7%95%A5%EF%BC%8C%E5%87%8F%E5%B0%91%E6%95%B4%E4%BD%93%E5%B0%BA%E5%AF%B8
处理过后变小了，但是20mb， 还是比v4时候大不少。

最后把v4的plugin.config.js也复制过来了，项目在v5的build才和v4时期一样大小，6mb左右。

**Comment by chenshuai2144** [comment]
这个东西一般在插件里配置了，应该安装依赖的就可以了

**Comment by fatesq** [comment]
> 这个东西一般在插件里配置了，应该安装依赖的就可以了

现在看好像是没生效，不知道对应的是umi的哪些，我在umi那咨询下

**Comment by htank-wang** [comment]
每次上线，install需要3min，build又需要3min。成果物16M

**Comment by chenshuai2144** [comment]
umi 中跟踪吧
