### ISSUE TITLE
🧐[问题]antd pro v4 安装umi-plugin-antd-theme以后css文件样式没有效果

### ISSUE THREAD

**Issue by TernenceWu0702** [ant-design/ant-design-pro#8224]
### 🧐 问题描述
版本：antd@4.9.4 umi@3.2.14
问题：由于项目样式是css所完成的，安装完umi-plugin-antd-theme，导致css的样式全部失效了，该插件是对项目中所有样式都有影响，还是可以通过什么设置能够避免这种情况

**Comment by chenshuai2144** [comment]
修改了样式的加载顺序，你的样式估计是优先级不够被覆盖了。
最简单的办法提升一下优先级。

**Comment by TernenceWu0702** [comment]
> umi-plugin-antd-theme 修改了样式的加载顺序，你的样式估计是优先级不够被覆盖了。
> 最简单的办法提升一下优先级。

你好，经过chrome的查看，我发现加载的都是less文件，组件中的css样式文件都没有加载

**Comment by TernenceWu0702** [comment]
> umi-plugin-antd-theme 修改了样式的加载顺序，你的样式估计是优先级不够被覆盖了。
> 最简单的办法提升一下优先级。

你好，经过chrome的查看，我发现加载的都是less文件，组件中的css样式文件都没有加载

**Comment by chenshuai2144** [comment]
那你改下名字

**Comment by TernenceWu0702** [comment]
> 那你改下名字

改啦改啦，这是什么问题呀

**Comment by TernenceWu0702** [comment]
> 那你改下名字

改啦改啦，这是什么问题呀 @ @chenshuai2144

**Comment by chenshuai2144** [comment]
@TernenceWu0702  你把你的 css 改下名字，改成 less 文件好了，因为我只打包 css
