### ISSUE TITLE
🐛[BUG]openapi生成的responseType提示不支持

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8227]
### 🐛 bug 描述

```
params: { ...params },
    data: body,
    responseType: '*/*',
    ...(options || {}),
```
![image](https://user-images.githubusercontent.com/70048681/111625983-6e910800-8828-11eb-8520-74a2e999db21.png)

umi的定义
![image](https://user-images.githubusercontent.com/70048681/111626250-be6fcf00-8828-11eb-970f-f2f3968cf0df.png)

### 📷 复现步骤

必现

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
已经删掉了，更新一下依赖
