### ISSUE TITLE
🐛[BUG]权限authority列表无法解析出现undefined

### ISSUE THREAD

**Issue by aglimmer** [ant-design/ant-design-pro#8230]
### 🐛 bug 描述

umi路由权限authority有时能解析有时不能解析，研究了两天毫无结果，请看图片
![QQ图片20210319221900](https://user-images.githubusercontent.com/51478573/111796678-5e9a2680-8903-11eb-8676-a649a75bc067.jpg)

**Comment by chenshuai2144** [comment]
看起来和你的加载顺序有关系。你要不要没加载回来之前不要渲染 layout

**Comment by aglimmer** [comment]
> 看起来和你的加载顺序有关系。你要不要没加载回来之前不要渲染 layout

自己改了一下现在又没有问题了，但是没找到问题原因

**Comment by chenshuai2144** [comment]
最好用 devtool 搞一下
