### ISSUE TITLE
🐛[BUG]umi对已删除的变量在重启服务器后仍然出现删除前的变量

### ISSUE THREAD

**Issue by aglimmer** [ant-design/ant-design-pro#8231]
拼图如下，privilege已经删除已经确认保存，但是在重启后仍然冒出之前删除的变量
<img width="500" alt="1" src="https://user-images.githubusercontent.com/51478573/111797064-c0f32700-8903-11eb-97eb-6b4b0d84b562.png">

**Comment by chenshuai2144** [comment]
忘记点保存按钮了？

**Comment by aglimmer** [comment]
> 忘记点保存按钮了？
> 
> 或者你删除以下 .umi 文件夹

保存，我尝试把.umi删除，然后重启，仍然无法解决

**Comment by chenshuai2144** [comment]
这种神奇的问题，一般都是大小写呀，环境什么的不好复现的奇怪问题。

建议你换个位置，修改一下大小写
