### ISSUE TITLE
npm v7 执行 run build 报错🧐[问题]

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-pro#8237]
### 🧐 问题描述

V4版本在npm 7 下 执行run build报错，好像less解析错误。

npm -v
7.6.0

PS：npm 6.14.10 版本下正常。

请求帮助！！！

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32634443/111903855-11db5a80-8a7f-11eb-9473-055de8bd5bae.png)

**Comment by firstmetcs** [comment]
![image](https://user-images.githubusercontent.com/32634443/111903911-45b68000-8a7f-11eb-8cd6-871fc54dcd59.png)

**Comment by firstmetcs** [comment]
![image](https://user-images.githubusercontent.com/32634443/111904924-1fdfaa00-8a84-11eb-8383-4fff816a5f98.png)

**Comment by firstmetcs** [comment]
![image](https://user-images.githubusercontent.com/32634443/111904945-3a198800-8a84-11eb-816e-a27d6b1dc29b.png)

**Comment by acooler15** [comment]
依赖冲突了，而且npm7 好像不会用npm6的lock文件（好像npm7使用的v2版本的lock文件），所以可能会下载新版本的依赖，而postcss-flexbugs-fixes@5.0.2指定了peerDependencies为`"postcss": "^8.1.4"`，虽然@umijs/bundler-webpack@3.4.3指定了dependencies为`postcss": "^8.x.x"`，但是posstcss@8却被npm装到了@umijs/bundler-webpack包下

**Comment by acooler15** [comment]
如果没有lock文件，使用npm@6现在也会报错。
如果新初始化一个项目，用node v14和npm v7，在`npm install --force`安装依赖时就会报错。。。
痛苦😢
现在还是用yarn吧😂

**Comment by firstmetcs** [comment]
> 如果没有lock文件，使用npm@6现在也会报错。
> 如果新初始化一个项目，用node v14和npm v7，在`npm install --force`安装依赖时就会报错。。。
> 痛苦😢
> 现在还是用yarn吧😂

果然还是npm大版本的问题啊，用yarn就可以了，建议官方也改一改，默认建议改成yarn吧😂
