### ISSUE TITLE
请问V5的OpenApi生成的接口的baseurl在哪？

### ISSUE THREAD

**Issue by FirstSeeing** [ant-design/ant-design-pro#8238]
```
return request<API.CurrentUserResult>(`${API_URL}/api/users/current`, {
```
我手动创建环境变量后拼接url但是每次重新生成openapi都会覆盖。这样很麻烦,而且感觉也不优雅，实在是没找到baseurl在哪，特来请教各位大神。

**Comment by acooler15** [comment]
在app.tsx里有一个request的配置好像可以实现。

**Comment by acooler15** [comment]
``` TypeScript
// https://umijs.org/zh-CN/plugins/plugin-request
export const request: RequestConfig = {
  errorHandler,
  prefix: '/bc',
};
```
`prefix`可以在reqeust请求时自动添加前缀

**Comment by FirstSeeing** [comment]
@acooler15 您好，感谢回复😄。我需要的是替换掉默认的http: //localhost: 8000，并不是要在apiurl加前缀。请问如何在不修改OpenApi生成的接口文件的前提下修改apiurl前面的BaseUrl？

**Comment by xuxiaoxiao312** [comment]
> @acooler15 您好，感谢回复😄。我需要的是替换掉默认的http: //localhost: 8000，并不是要在apiurl加前缀。请问如何在不修改OpenApi生成的接口文件的前提下修改apiurl前面的BaseUrl？

同样碰到了这个问题，发现将prefix设置为完整的接口路径就可以了
`
  prefix: 'https://xxxxxxx.com',
`

**Comment by FirstSeeing** [comment]
> > @ acooler15您好，感谢回复😄。我需要的是替换掉的的 http：//localhost：8000，并不是要在 apiurl 加附加。
> 
> 同样碰到了这个问题，发现将前缀设置为完整的接口路径就可以了
> `prefix: 'https://xxxxxxx.com',`
您好，感谢回复~请问可以发一下具体改哪个文件吗？

**Comment by xuxiaoxiao312** [comment]
在app.tsx里面修改request
```
// https://umijs.org/zh-CN/plugins/plugin-request
export const request: RequestConfig = {
  errorHandler,
  prefix: 'https://xxxxxx.com',
};
```

**Comment by FirstSeeing** [comment]
> 在 app.tsx 里面修改 request
> 
> ```
> // https://umijs.org/zh-CN/plugins/plugin-request
> export const request: RequestConfig = {
>   errorHandler,
>   prefix: 'https://xxxxxx.com',
> };
> ```

太感谢啦，问题搞定啦~😊
可以关闭问题了~

**Comment by Harry-Wei** [comment]
> 在app.tsx里面修改request
> 
> ```
> // https://umijs.org/zh-CN/plugins/plugin-request
> export const request: RequestConfig = {
>   errorHandler,
>   prefix: 'https://xxxxxx.com',
> };
> ```

请问这里的errorHandler需要处理些什么？
