### ISSUE TITLE
🧐[Question]: How to enable SettingDrawer in v5?

### ISSUE THREAD

**Issue by loia5tqd001** [ant-design/ant-design-pro#8239]
TL;DR; I've described the question in detail [on Stackoverflow here](https://stackoverflow.com/questions/66670498/how-to-enable-settingdrawer-in-ant-design-pro-v5)

`SettingDrawer` is being enabled by default in v4, but in v5 it's not. How to do that?

**Comment by chenshuai2144** [comment]
run`yarn add  umi-plugin-setting-drawer` in you project
