### ISSUE TITLE
🐛[BUG] Weird behavior when using `splitMenus`

### ISSUE THREAD

**Issue by loia5tqd001** [ant-design/ant-design-pro#8240]
If my navigation looks like:
1. Home 
2. Admin -> User
    Admin -> Job

What I want is whenever I click on `/admin`, it will ALWAYS AUTOMATICALLY redirect to `admin/user`, WHETHER I'M CURRENTLY AT `/` (Home) or `admin/user`, or `admin/job`.

The current version of v5 seems to only work well when the prior route before clicking on `/admin` is not a child of `/admin`.
For example, I want always to redirect `/admin` to `/admin/user`. And 
- From `/`, click on `Admin`, it'll automatically redirect to `/admin/user` 
- From `/admin/job`, click on `Admin`, it'll not redirect to anywhere. It's only `admin`, with redirecting to `/admin/user`

Video demo [here](https://vimeo.com/526973090)

**Comment by drizzlesconsin** [comment]
@loia5tqd001 Maybe this will help you.
```diff
{
    "path": "/admin",
    "name": "admin",
    "icon": "control",
    "routes": [
        {
            "path": "/admin/user",
            "name": "user",
            "icon": "user",
            "component": "./Admin/User"
        },
        {
            "path": "/admin/job",
            "name": "job",
            "icon": "audit",
            "component": "./Admin/Job",
            "routes": [
                {
                    "path": "/admin/job/jobTitle",
                    "name": "jobTitle",
                    "icon": "right",
                    "component": "./Admin/Job/JobTitle"
                },
+              {
+                   "path": "/admin/job",
+                   "redirect": "/admin/job/jobTitle"
+              }
            ]
        },
+       {
+           "path": "/admin",
+           "redirect": "/admin/user"
+       }
    ]
}
```

**Comment by loia5tqd001** [comment]
> @loia5tqd001 Maybe this will help you.
> 
> ```diff
> {
>     "path": "/admin",
>     "name": "admin",
>     "icon": "control",
>     "routes": [
>         {
>             "path": "/admin/user",
>             "name": "user",
>             "icon": "user",
>             "component": "./Admin/User"
>         },
>         {
>             "path": "/admin/job",
>             "name": "job",
>             "icon": "audit",
>             "component": "./Admin/Job",
>             "routes": [
>                 {
>                     "path": "/admin/job/jobTitle",
>                     "name": "jobTitle",
>                     "icon": "right",
>                     "component": "./Admin/Job/JobTitle"
>                 },
> +              {
> +                   "path": "/admin/job",
> +                   "redirect": "/admin/job/jobTitle"
> +              }
>             ]
>         },
> +       {
> +           "path": "/admin",
> +           "redirect": "/admin/user"
> +       }
>     ]
> }
> ```
Exactly what I'm looking for
