### ISSUE TITLE
🧐[问题] ProTable的搜索表单如何让右边默认生成的重置和查询按钮靠近input框？

### ISSUE THREAD

**Issue by voidzlfan** [ant-design/ant-design-pro#8241]
### 🧐 问题描述
antd pro v4 ProTable

ProTable只使用到了两个搜索条件，默认生成的重置和查询按钮距离左边太远了，不好看。因为这是默认生成的，代码层面隐藏了，我无法用样式控制，请问怎么解决？

![image](https://user-images.githubusercontent.com/38897523/111955312-4b19d600-8b24-11eb-842c-1da836787277.png)

### 💻 示例代码
查询文档，发现`form`和`search`似乎可以设置`layout: inline`实现，但是没有效果
```
<ProTable
      search={{layout: 'inline'}} //这两个设置不起作用
      form={{layout: 'inline'}} //这两个设置不起作用
      className="protable"
      rowKey="id"
      columns={columns}
      request={(params = {}) => res}
      pagination={{
        pageSize: 5,
      }}
      dateFormatter="string"
      headerTitle="成员管理"
      toolBarRender={() => [
        <Button key="button" icon={<PlusOutlined />} type="primary">
          新建
        </Button>,
      ]}
/>
```

**Comment by chenshuai2144** [comment]
你设置 span = 8 好了

**Comment by voidzlfan** [comment]
> 你设置 span = 8 好了

我想我到解决方法了，Search 搜索表单有个`optionRender`自定义操作栏
