### ISSUE TITLE
👑 [需求] 建议再项目打包是可以生成一个项目的版本号

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8243]
### 🥰 需求描述

建议再项目打包是可以生成一个项目的版本号，例如 v1.0.0-a89dfadr ，后面一个随机字符串，以便识别打包版本

**Comment by drizzlesconsin** [comment]
@hihuangwei 可以自行实现

1. Global variable
```ts
// config.ts
import Pack from '../package.json';

// https://umijs.org/config#headscripts
headScripts: [
    `window.JS_VERSION = "v${Pack.version}-${+new Date()}"`,
],
```

2. Assets filename
```ts
chainWebpack(memo) {
  memo.output.chunkFilename(`js/[name].[contenthash:8]${version}.async.js`);
  memo.output.filename(`js/[name].[contenthash:8]${version}.chunk.js`);
}
```

**Comment by hihuangwei** [comment]
> @hihuangwei 可以自行实现
> 
> 1. Global variable
> 
> ```ts
> // config.ts
> import Pack from '../package.json';
> 
> // https://umijs.org/config#headscripts
> headScripts: [
>     `window.JS_VERSION = "v${Pack.version}-${+new Date()}"`,
> ],
> ```
> 
> 1. Assets filename
> 
> ```ts
> chainWebpack(memo) {
>   memo.output.chunkFilename(`js/[name].[contenthash:8]${version}.async.js`);
>   memo.output.filename(`js/[name].[contenthash:8]${version}.chunk.js`);
> }
> ```

这样生成之后，要如何读取版本数据
