### ISSUE TITLE
🧐[问题]穿梭框Transfer设置左右区域属性listStyle不生效

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#8247]
### 🧐 问题描述

我想分别给表格穿梭框的左右两部分设置样式,，根据官方文档

![image](https://user-images.githubusercontent.com/54265150/112276912-2e180b00-8cbc-11eb-8b8a-617bb6a99e5a.png)

对listStyle进行配置，如下图所示。但是并没有效果。
![image](https://user-images.githubusercontent.com/54265150/112277048-54d64180-8cbc-11eb-9cc7-1cd3641af9fa.png)

请问这个该如何解决呢，是我写的有问题吗？

**Comment by chenshuai2144** [comment]
去 antd 问问，这里的老哥只能帮你查查 api，真正解决问题还要靠那边

**Comment by Youmyin** [comment]
antd那边只接受bug和功能需求，不接受用法使用对吗，那边说用法使用只能去 StackOverflow和SegmentFault，请问我要把这个算作bug去提问吗？

**Comment by chenshuai2144** [comment]
嗯， 你去问问

**Comment by Youmyin** [comment]
好的，谢谢！
