### ISSUE TITLE
🧐[问题]ProForm如何设置表单区域宽度为固定值

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#8248]
### 🧐 问题描述

我想要在分步表单的某一步的页面放几个组件录入数据，使用Row和Col进行了布局，如下方代码所示：
```
<StepsForm.StepForm<Partial<Goods>>
    name="other"
    title="其他"
    className={styles.other}
    id='yyyyyyyyyyyyy'
>
    <Row gutter={16}>
        <Col span={6}>
            <Card bodyStyle={{ minHeight: '500px' }}>
                <Mycom1 />
            </Card>
        </Col>
        <Col span={18}>
            <Card>
                <Mycom2 />
            </Card>
        </Col>
    </Row>
</StepsForm.StepForm>
```

结果发现，在组件中没有数据的时候，组件被挤压得很严重。检查元素发现，是因为.ant-pro-steps-form-step > form这个类width设置了max-content，如下图所示：
![image](https://user-images.githubusercontent.com/54265150/112287064-ee0a5580-8cc6-11eb-8bdd-1e2ada456941.png)

当把这两个width全部取消，组件能正常显示宽度
![image](https://user-images.githubusercontent.com/54265150/112287202-15f9b900-8cc7-11eb-8c5e-56120fe16f50.png)

但是我不知道怎么覆盖掉这两个width，已经通过 className={styles.other}在less文件中进行了覆盖，如下方代码所示，但是并没有效果，检查元素发现没有覆盖
```
.other{
    :global{
        .ant-pro-steps-form-step > form{
            min-width:500px !important;
        }
    }
}
```
请问这个问题该如何解决呢？

**Comment by fangqibin** [comment]
用className='other'试一下

**Comment by chenshuai2144** [comment]
我来改一下这个 bug

**Comment by Youmyin** [comment]
谢谢！

**Comment by chenshuai2144** [comment]
明天发个版本
