### ISSUE TITLE
单独使用ant-design-pro的组件，npm build的时候报错

### ISSUE THREAD

**Issue by swustzl** [ant-design/ant-design-pro#825]
#环境： react 16 ， antd 3.0.0, dva 2.1.0
#执行 npm install ant-design-pro --save  后
#运行报错：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:dll',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose run-script [ 'prebuild:dll', 'build:dll', 'postbuild:dll' ]
5 info lifecycle front@0.1.2~prebuild:dll: front@0.1.2
6 info lifecycle front@0.1.2~build:dll: front@0.1.2
7 verbose lifecycle front@0.1.2~build:dll: unsafe-perm in lifecycle true
8 verbose lifecycle front@0.1.2~build:dll: PATH: ...
9 verbose lifecycle front@0.1.2~build:dll: CWD: ...
10 silly lifecycle front@0.1.2~build:dll: Args: [ '/d /s /c', 'roadhog buildDll' ]
11 silly lifecycle front@0.1.2~build:dll: Returned: code: 1  signal: null
12 info lifecycle front@0.1.2~build:dll: Failed to exec build:dll script
13 verbose stack Error: front@0.1.2 build:dll: `roadhog buildDll`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid front@0.1.2
15 verbose cwd D:\...
16 verbose Windows_NT  #10.0.15063
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dll" "--scripts-prepend-node-path=auto"
18 verbose node v8.7.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error front@0.1.2 build:dll: `roadhog buildDll`
22 error Exit status 1
23 error Failed at the front@0.1.2 build:dll script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by chenshuai2144** [comment]
再试一次？  这个连报错信息都没有

**Comment by chenshuai2144** [comment]
默认就会有的，不要挖坟呀
