### ISSUE TITLE
🧐[Question (possibly yarn's or antd-pro's bug..)] Existence of Ant Design Pro Symlink in node_modules causes failure in deployment.

### ISSUE THREAD

**Issue by kevinadhiguna** [ant-design/ant-design-pro#8251]
### 🧐 Problem description

Hello, I recently tried to deploy an Ant Design Pro project (which I created using `yarn create umi <my_project_name>`) to AWS Amplify Console. However it failed in build phase over and over again. For more, please have a look at this [AWS Amplify issue](https://github.com/aws-amplify/amplify-console/issues/1676) which tells my difficulties during the deployment to AWS Amplify Console.

A contributor of AWS Amplify told that perhaps the build container is running out of memory on the caching step. So, I tried to [reduce node_modules cache size](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#how-to-reduce-node_modules-cache-size). Nevertheless, the issue still persisted. Eventually, it came to an end when a member of my team included `!node_modules/ant-design-pro` in cache.

My team found out that somehow a symlink (symbolic link) of ant-design-pro exists in `node_modules` folder. <br>
Here are the steps to reproduce the issue : 
1) Create a brand new Ant Design Pro project with **yarn**
```
yarn create umi myapp
```

2) Change directory to `myapp`
```
cd myapp
```

3) Install `node_modules`
```
yarn
```

4) Open `node_modules` > search for `ant-design-pro` folder. Then you will see that inside `./node_modules/ant-design-pro`, it contains another `node_modules` directory.

![bug-antd-pro](https://user-images.githubusercontent.com/43397636/112432350-5dd61a00-8d73-11eb-88c3-026ad2b76d6a.png)

5) It was like an infinite loop. That `node_modules` directory, contains another `ant-design-pro` project.

![bug-antd-pro-2](https://user-images.githubusercontent.com/43397636/112432699-d341ea80-8d73-11eb-88cd-1067844714c9.png)

Could you please tell me why this happens and how to avoid it ? Is this a problem with Ant Design Pro or Yarn or something else ?

Any feedback and solution will be much appreciated. Feel free to ask if there's anything unclear, thanks.

**Comment by chenshuai2144** [comment]
我们很关注这个问题，但是他已经很长时间没有回应。我们会暂时关闭它
——
We are very concerned about this issue, but he has not responded for a long time. We will temporarily close it

**Comment by ceefour** [comment]
@chenshuai2144 really sad to hear it :(

**Comment by ceefour** [comment]
@chenshuai2144 Can you explain why `ant-design-pro` module needs to have another `node_modules` folder linking back infinitely ?
