### ISSUE TITLE
🐛[BUG]proTable表格查询功能，点x后无法输入内容。   "version": "4.5.0",

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#8257]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/table
官网没什么问题，删除lock，更新一下依赖吧
