### ISSUE TITLE
🐛[BUG] 路由使用lazy方式加载，菜单栏无法自动选中

### ISSUE THREAD

**Issue by decker502** [ant-design/ant-design-pro#8258]
### 🐛 bug 描述

路由使用lazy方式加载，菜单栏无法自动选中，不使用lazy方式却可以

详细代码见下面提供的例子工程，其中 Welcome 为Lazy方式加载， Demo 为非Lazy方式加载

### 📷 复现步骤

点击菜单栏选中一个菜单，刷新页面，菜单栏变为收起状态，并未根据location选中对应菜单

### 🏞 期望结果

根据location选中对应菜单

### 💻 复现代码

参见复现工程

https://github.com/decker502/my-app

### © 版本信息

参见工程配置

**Comment by veeramarni** [comment]
@decker502 what is the solution for it?

**Comment by decker502** [comment]
@veeramarni 开启 Suspense 特性后，就能自动选中
