### ISSUE TITLE
🧐[问题]ProTable valueType选择为dateRange时，可以给dateRange限制选择时间范围吗？比如只能选择一个月内

### ISSUE THREAD

**Issue by zhulemomo** [ant-design/ant-design-pro#8259]
### 🧐 问题描述

类似Ant Design的RangePicker组件控制日期区间那样的效果，如下图：
![image](https://user-images.githubusercontent.com/20922408/112718491-5eff7680-8f2e-11eb-8130-2f87b2371bdd.png)

**Comment by drizzlesconsin** [comment]
@zhulemomo Doc: https://procomponents.ant.design/en-US/components/table#search-form-customization
```ts
fieldProps: {
  disabledDate: (current) => current && current < moment().endOf('day'),
},
```
