### ISSUE TITLE
项目中不需要菜单，应该怎么配置？文档写的配置name信息，不太明白。

### ISSUE THREAD

**Issue by zywcode** [ant-design/ant-design-pro#826]
菜单#
菜单信息配置在 src/common/menu.js 中，它的作用是：
配置菜单相关数据，菜单项的跳转链接为配置项及其所有父级配置 path 参数的拼接。

为 src/common/router.js 提供路由名称（name）等数据，根据拼接好的跳转链接来匹配相关路由。

如果你的项目并不需要菜单，你也可以直接在 src/common/router.js 中配置 name 信息。
配置文件输出的菜单数据，可以直接提供给侧边栏组件使用。SiderMenu.js。除了生成菜单，菜单数据还可辅助生成重定向路由等模块，参考 BasicLayout.js#L154。

**Comment by chenshuai2144** [comment]
隐藏一项 还是完全不需要？ 
给meun一个空数组就可以完全不显示！ 

Name是为了面包屑

**Comment by zywcode** [comment]
@chenshuai2144 明白了，我是完全不需要menu，在router中配置上name信息，面包屑也能正常显示。感谢。
