### ISSUE TITLE
🧐[问题]V5 OpenAPI 生成typings.d.ts大写

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design-pro#8260]
### 🧐 问题描述

openApi生成的typings.d.ts中数据描述能否首字母大写？

### 💻 示例代码
例如这样：
declare namespace API {
  type RuleListItem = {
    Key?: number;
    Disabled?: boolean;
    Href?: string;
    Avatar?: string;
    Name?: string;
    Owner?: string;
    Desc?: string;
    CallNo?: number;
    Status?: number;
    UpdatedAt?: string;
    CreatedAt?: string;
    Progress?: number;
  };
}

**Comment by fangqibin** [comment]
大小写不影响

**Comment by lattemj** [comment]
> 大小写不影响

服务端返回数据是大写格式，JSON中大小写不一样无法读取数据

**Comment by fangqibin** [comment]
那这个要让服务端返回驼峰，前端还是习惯驼峰。

**Comment by chenshuai2144** [comment]
这个要看你的 swagger 是怎么写的，尽量让后端规范一点
