### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GitVijayDv** [ant-design/ant-design-pro#8263]
[vg@localhost ]$ node -v
v12.21.0
[vg@localhost ]$ npm -v
6.14.11
[vg@localhost ]$ npm create umi myApp
[vg@localhost myApp]$ npm install
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated ant-design-palettes@1.1.3: Please use @ant-design/colors to replace ant-design-palettes
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated react-native-swipeout@2.3.6: Package no longer supported. Use at your own risk or consider using https://github.com/software-mansion/react-native-gesture-handler
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> puppeteer-core@1.12.2 install /home/vg/dev/pr1/myApp/node_modules/carlo/node_modules/puppeteer-core
> node install.js

> core-js@3.6.5 postinstall /home/vg/dev/pr1/myApp/node_modules/@umijs/babel-plugin-lock-core-js-3/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.8.2 postinstall /home/vg/dev/pr1/myApp/node_modules/@umijs/test/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /home/vg/dev/pr1/myApp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.9.1 postinstall /home/vg/dev/pr1/myApp/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@2.7.4 postinstall /home/vg/dev/pr1/myApp/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> esbuild@0.8.57 postinstall /home/vg/dev/pr1/myApp/node_modules/esbuild
> node install.js

> core-js@3.9.1 postinstall /home/vg/dev/pr1/myApp/node_modules/eslint-plugin-compat/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js@3.9.1 postinstall /home/vg/dev/pr1/myApp/node_modules/gg-editor/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> @umijs/yorkie@2.0.5 postinstall /home/vg/dev/pr1/myApp/node_modules/@umijs/yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation

> react-dev-inspector@1.5.3 postinstall /home/vg/dev/pr1/myApp/node_modules/react-dev-inspector
> node scripts/postinstall.js

> ant-design-pro@4.5.0 postinstall /home/vg/dev/pr1/myApp
> umi g tmp

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-environment-jsdom-fourteen/node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @antv/l7-react@2.3.0 requires a peer of react-dom@^16.8.6 but none is installed. You must install peer dependencies yourself.
npm WARN dva@2.4.1 requires a peer of react-dom@15.x || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dev-inspector@1.5.3 requires a peer of webpack@>=4.44.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@17.0.2 requires a peer of react@17.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-fittext@1.0.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-config@5.1.1 requires a peer of react-router@>=5 but none is installed. You must install peer dependencies yourself.
npm WARN esbuild-loader@2.6.3 requires a peer of webpack@^4.40.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN dva@2.6.0-beta.22 requires a peer of react-dom@^16.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN babel-plugin-dva-hmr@0.4.2 requires a peer of redbox-react@1.x but none is installed. You must install peer dependencies yourself.
npm WARN dva-immer@0.5.2 requires a peer of dva@^2.5.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN dva-loading@3.0.22 requires a peer of dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN connected-react-router@6.5.2 requires a peer of react-redux@^6.0.0 || ^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package mockjs is included as both a dev and production dependency.

added 2460 packages from 1247 contributors and audited 2484 packages in 208.744s

190 packages are looking for funding
  run `npm fund` for details

found 13 vulnerabilities (11 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by GitVijayDv** [comment]
cont...
[vg@localhost myApp]$ npm start

> ant-design-pro@4.5.0 start /home/vg/dev/pr1/myApp
> cross-env UMI_ENV=dev umi dev

Starting the development server...
Webpack
  Compiled with some errors in 6.22m

[BABEL] Note: The code generator has deoptimised the styling of /home/vg/dev/pr1/myApp/node_modules/@antv/data-set/build/data-set.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/vg/dev/pr1/myApp/node_modules/mapbox-gl/dist/mapbox-gl.js as it exceeds the max of 500KB.
 ERROR  Failed to compile with 2 errors                                                                                      
These dependencies were not found:

* /home/vg/dev/pr1/myApp/src/pages/user/register in ./src/.umi/core/routes.ts
* /home/vg/dev/pr1/myApp/src/pages/user/register-result in ./src/.umi/core/routes.ts

To install them, you can run: npm install --save /home/vg/dev/pr1/myApp/src/pages/user/register /home/vg/dev/pr1/myApp/src/pages/user/register-result

**Comment by fangqibin** [comment]
我觉得可以用yarn或者tyarn试一下，初始项目正常问题都是依赖没有下载全

**Comment by chenshuai2144** [comment]
看起来页面也不对，是不是大小写也有问题

**Comment by tongjun741** [comment]
就是大小写问题：
![image](https://user-images.githubusercontent.com/6827111/115810019-c15d7100-a41f-11eb-9b5f-b90fa59ac057.png)

**Comment by 540692039** [comment]
```javascript
```

**Comment by 540692039** [comment]
```javascript
 "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.1.9",
    "@antv/l7-maps": "^2.1.9",
    "@antv/l7-react": "^2.1.9",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.12.0",
    "bizcharts": "^3.5.3-beta.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.25.3",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^2.0.2",
    "prop-types": "^15.5.10",
    "react": "^16.14.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "react-router": "^4.3.1",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8"
  },
```

看起来应该是umi的问题？这个版本依然存在大小写问题
![image](https://user-images.githubusercontent.com/30407638/124077349-00402080-da7a-11eb-99a6-adfcc65357e8.png)


但是奇怪的是我本地  npm run build 没有报错，在ci环境内  一打包就错
![image](https://user-images.githubusercontent.com/30407638/124077454-2239a300-da7a-11eb-91c2-27a87bf887bf.png)
