### ISSUE TITLE
🧐[问题] openapi生成的代码格式问题

### ISSUE THREAD

**Issue by HengCC** [ant-design/ant-design-pro#8270]
### 🧐 问题描述

生成的api中 命名能否支持配置化? 
比如生成的的代码如下:
```
/** 查询当前用户 GET /user/currentUser */
export async function currentUserUsingGET(options?: { [key: string]: any }) {
  return request<API.ResultDTOUser>('/user/currentUser', {
    method: 'GET',
    ...(options || {}),
  });
}
```
`currentUserUsingGET` 能否直接就是原始的方法名 `currentUser` 而不带上Get

另外类似泛型中的这样的写法ResultDTOstring ,ResultDTOUser 其实对应的是ResultDTO\<String\> ResultDTO\<User\>, 这样的参数有办法泛型化吗? 

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by fangqibin** [comment]
方法名是由后端决定的，可以修改后端，泛型应该是可以的，没有尝试，弄成泛型的使用场景是？。

**Comment by HengCC** [comment]
> 方法名是由后端决定的，可以修改后端，泛型应该是可以的，没有尝试，弄成泛型的使用场景是？。

后端的方法名是currentUser, 但是openapi生成出来的是加上了请求方法类型. 就是多了一个UsingGET. 

另外泛型的场景. 举个简单的例子.  ResultDTO 是定义了统一的返回格式. 格式如下:

```
public class ResultDTO<T> {
    @Builder.Default
    @ApiModelProperty(required = true)
    private Boolean success = true;
    private T data;
    private String message;
    // 发生错误的时候可以有code&message
    @Builder.Default
    private String code = Constants.CODE_SUCCESS;
}
```
对应到TS中的代码应该也是有一个类似如下的定义. 

```

  type ResultDTO<T> = {
    code?: string;
    data?: T;
    message?: string;
    success: boolean;
  };
```
那对T来说 可以是任何泛型.  比如上面返回的是User类型. 那api生成的结构应该类似下面这样
```
/** 查询当前用户 GET /user/currentUser */
export async function currentUserUsingGET(options?: { [key: string]: any }) {
  return request<API.**ResultDTO<User>**>('/user/currentUser', {
    method: 'GET',
    ...(options || {}),
  });
}
```
而不是每个返回体都定义一个类型. 像下面这样
```
/** 查询当前用户 GET /user/currentUser */
export async function currentUserUsingGET(options?: { [key: string]: any }) {
  return request<API.**ResultDTOUser**>('/user/currentUser', {
    method: 'GET',
    ...(options || {}),
  });
}
```

**Comment by fangqibin** [comment]
> > 方法名是由后端决定的，可以修改后端，泛型应该是可以的，没有尝试，弄成泛型的使用场景是？。
> 
> 后端的方法名是currentUser, 但是openapi生成出来的是加上了请求方法类型. 就是多了一个UsingGET.
> 
> 另外泛型的场景. 举个简单的例子. ResultDTO 是定义了统一的返回格式. 格式如下:
> 
> ```
> public class ResultDTO<T> {
>     @Builder.Default
>     @ApiModelProperty(required = true)
>     private Boolean success = true;
>     private T data;
>     private String message;
>     // 发生错误的时候可以有code&message
>     @Builder.Default
>     private String code = Constants.CODE_SUCCESS;
> }
> ```
> 
> 对应到TS中的代码应该也是有一个类似如下的定义.
> 
> ```
> 
>   type ResultDTO<T> = {
>     code?: string;
>     data?: T;
>     message?: string;
>     success: boolean;
>   };
> ```
> 
> 那对T来说 可以是任何泛型. 比如上面返回的是User类型. 那api生成的结构应该类似下面这样
> 
> ```
> /** 查询当前用户 GET /user/currentUser */
> export async function currentUserUsingGET(options?: { [key: string]: any }) {
>   return request<API.**ResultDTO<User>**>('/user/currentUser', {
>     method: 'GET',
>     ...(options || {}),
>   });
> }
> ```
> 
> 而不是每个返回体都定义一个类型. 像下面这样
> 
> ```
> /** 查询当前用户 GET /user/currentUser */
> export async function currentUserUsingGET(options?: { [key: string]: any }) {
>   return request<API.**ResultDTOUser**>('/user/currentUser', {
>     method: 'GET',
>     ...(options || {}),
>   });
> }
> ```

我知道你说的意思，泛型比较适合我们平常写的习惯，但是在开发过程中好像不影响，不是吗。

**Comment by fangqibin** [comment]
> > 方法名是由后端决定的，可以修改后端，泛型应该是可以的，没有尝试，弄成泛型的使用场景是？。
> 
> 后端的方法名是currentUser, 但是openapi生成出来的是加上了请求方法类型. 就是多了一个UsingGET.
> 
> 另外泛型的场景. 举个简单的例子. ResultDTO 是定义了统一的返回格式. 格式如下:
> 
> ```
> public class ResultDTO<T> {
>     @Builder.Default
>     @ApiModelProperty(required = true)
>     private Boolean success = true;
>     private T data;
>     private String message;
>     // 发生错误的时候可以有code&message
>     @Builder.Default
>     private String code = Constants.CODE_SUCCESS;
> }
> ```
> 
> 对应到TS中的代码应该也是有一个类似如下的定义.
> 
> ```
> 
>   type ResultDTO<T> = {
>     code?: string;
>     data?: T;
>     message?: string;
>     success: boolean;
>   };
> ```
> 
> 那对T来说 可以是任何泛型. 比如上面返回的是User类型. 那api生成的结构应该类似下面这样
> 
> ```
> /** 查询当前用户 GET /user/currentUser */
> export async function currentUserUsingGET(options?: { [key: string]: any }) {
>   return request<API.**ResultDTO<User>**>('/user/currentUser', {
>     method: 'GET',
>     ...(options || {}),
>   });
> }
> ```
> 
> 而不是每个返回体都定义一个类型. 像下面这样
> 
> ```
> /** 查询当前用户 GET /user/currentUser */
> export async function currentUserUsingGET(options?: { [key: string]: any }) {
>   return request<API.**ResultDTOUser**>('/user/currentUser', {
>     method: 'GET',
>     ...(options || {}),
>   });
> }
> ```

后端的方法名是currentUser, 但是openapi生成出来的是加上了请求方法类型. 就是多了一个UsingGET.
这个可能后端在写的时候没有写对，我这边生成是正常的。我是前端，后端接口写法我的不是很清楚，但是生成的不会有GET

**Comment by HengCC** [comment]
@fangqibin 后端这样的
```
  @ApiOperation("查询当前用户")
  @GetMapping("/currentUser")
  public ResultDTO<User> currentUser() {
      return ResultDTO.<User>builder().data(userService.currentUser()).build();
  }
```
另外虽然前端对泛型这样处理对开发来说没有影响. 但是你不觉得恶心吗?  举个例子, 看下面生成的代码:
```
type ResultDTOUserLoginResult = {
    code?: string;
    data?: Record<string, any>;
    message?: string;
    success: boolean;
  };

  type ResultDTOUser = {
    code?: string;
    data?: Record<string, any>;
    message?: string;
    success: boolean;
  };
```
生成出来是不是一样的?

**Comment by HengCC** [comment]
实测这个方法的UsingGET是通过openapi中的operationId来生成的.  如果是swagger.需要为api配置nickname来实现不默认追加UsingGET.  泛型问题没找到办法.

**Comment by fangqibin** [comment]
泛型我也没有找到办法，我是有operationId这个字段

**Comment by HengCC** [comment]
关于operationid的给个通用的解决方案吧. swagger参考如下, 用此后需要尽量自己手动保持方法名唯一. 
```
@Component
@Order(Ordered.HIGHEST_PRECEDENCE + 1000)
@Slf4j
public class SwaggerOperationIdConfig implements OperationBuilderPlugin {
    @Override
    public void apply(OperationContext context) {
        context.operationBuilder()
                .codegenMethodNameStem(context.getName());
    }

    @Override
    public boolean supports(DocumentationType documentationType) {
        return true;
    }
}

```

**Comment by 15723185734** [comment]
>     @

请问 后端时微服务，每个微服务的json都有一个baseUrl  为什么生成出来的openapi没有自动拼上这段地址？
![image](https://user-images.githubusercontent.com/61341868/142339278-00502476-a450-47c2-a40e-fcbb401e5c5e.png)
