### ISSUE TITLE
🧐[问题] 我用的是V5 我在app.ts 配置中 getInitialState 开起来了webSocket 怎么 通知initialState变化

### ISSUE THREAD

**Issue by zhj778930960** [ant-design/ant-design-pro#8274]
### 🧐 问题描述
我用的是V5 我在app.ts 配置中 getInitialState 开起来了webSocket 怎么 通知initialState变化

在 getInitialState  开了webSocket 然后怎么等 webSocket 有数据时候通知 nitialState变化 呢？？？

**Comment by zhj778930960** [comment]
useModel 只有 tsx 函数中  才可以使用 普通函数不行

**Comment by fangqibin** [comment]
webSocket 在注册的时候可以监听数据变化

**Comment by zhj778930960** [comment]
> 册的时候可以监听数据变化

这个我知道 就是 websocket onmessage 写在 app.ts 中 怎么去通知变化？？

**Comment by chenshuai2144** [comment]
你做个组件来启动  websocket  ，就可以使用 useModel  了。app.ts 里面是页面加载完成之前，这里启动socket 可能导致页面重复刷新

**Comment by zhj778930960** [comment]
> 你做个组件来启动 websocket ，就可以使用 useModel 了。app.ts 里面是页面加载完成之前，这里启动socket 可能导致页面重复刷新


哈哈哈 我就是这么做的   但是useModel 是不是  有异步更新队列 我快速触发 就只返回 最后一次的   所以我又改成dva了
