### ISSUE TITLE
🧐[问题]切换主题，无法生成样式css文件，求求了

### ISSUE THREAD

**Issue by doudoucomic** [ant-design/ant-design-pro#8277]
### 🧐 问题描述
umi3，antd4，想实现主题切换，安装了umi-plugin-antd-theme和@ant-design/pro-layout，配置参照的antdPro，
本地antdPro可以，但umi+antd的项目就不行

![image](https://user-images.githubusercontent.com/28617381/112823506-f5ad6e00-90bb-11eb-88a3-15c7948c3ea4.png)

![image](https://user-images.githubusercontent.com/28617381/112824070-a87dcc00-90bc-11eb-9821-63f8cde52960.png)

![image](https://user-images.githubusercontent.com/28617381/112823726-37d6af80-90bc-11eb-9f2b-c6de3598cee1.png)

**Comment by chenshuai2144** [comment]
把你的项目发出来吧，可能有插件没装全

**Comment by doudoucomic** [comment]
你好，我自己解决了，我加你微信了，你没反应
















在 2021-05-08 11:45:00，"洁yi" ***@***.***> 写道：

请问解决了吗？ 我也遇到相同问题
