### ISSUE TITLE
建议官方文档再简洁清晰一些，或给一个快速开始案例。

### ISSUE THREAD

**Issue by SillyFlame** [ant-design/ant-design-pro#8278]
第一次看文档，我有两个需求：
1. 怎么快速添加一个新页面
2. 怎么在新页面快速调用后端（CURD）接口

然后看文档，看到"路由和菜单"，一大堆文字讲解，居然还有"从服务器请求菜单"，我都是蒙的，我觉得直接给一个简单一步一步教程就好了，不要这些文绉绉的，非常不好理解

**Comment by fangqibin** [comment]
官方文档不是给后端人员用的，是给前端开发人员看的，不能用后端的思想来看，你如果看的是蒙的，这时候你应该去提高前端技术或者使用别的框架。
关于你说的第一个问题 文档就有说如何新增页面
第二问题：前端框架不是为了让你快速调用后端接口，你可以去看看ProTable，附上地址：https://beta-pro.ant.design/blog/protable-cn
文档写的很清楚了，仔细看看吧，不要吐槽官方写的不好了

**Comment by chenshuai2144** [comment]
你需要的是视频教程，不是文字教程。
