### ISSUE TITLE
🐛[BUG]通过 menuItemRender, subMenuItemRender自定义菜单，选中时不会高亮，检查元素缺少 selectd类。

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#8279]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
可以附上menuItemRender, subMenuItemRender的代码

**Comment by huangzongming** [comment]
官网上的就不行。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-pro] 🐛[BUG]通过 menuItemRender, subMenuItemRender自定义菜单，选中时不会高亮，检查元素缺少 selectd类。 (#8279)





 
可以附上menuItemRender, subMenuItemRender的代码

**Comment by huangzongming** [comment]
![image](https://user-images.githubusercontent.com/37889515/112923435-e3c1de80-9140-11eb-9b03-0c94dd971461.png)

**Comment by fangqibin** [comment]
我知道文档有说可以自定义，大概率是你代码写的有问题，可以自查一下

**Comment by chenshuai2144** [comment]
高亮是用css做的，不是用行为做的。
可以去antd里 提个pr，帮忙加上这个功能

**Comment by fangqibin** [comment]
我的也是自定义菜单，我可以高亮
