### ISSUE TITLE
按F5的时候  官方demo好像没有刷新的感觉

### ISSUE THREAD

**Issue by wunayou** [ant-design/ant-design-pro#828]
按F5的时候  官方demo好像没有刷新的感觉
但是我的变化好大，全部重新渲染 
问题出在哪里？

**Comment by chenshuai2144** [comment]
部署和开发是不一样的。部署的时候做了很多工作保证流畅和加载速度！

**Comment by wunayou** [comment]
那能说一下这方面的知识 我顺藤摸瓜去研究一下

**Comment by chenshuai2144** [comment]
前端性能优化

**Comment by wunayou** [comment]
兄弟别弄  以前看过这些东西  好像没有东西可以达到你们这个效果  能再细一点 ？ 还是以前没有仔细看这东西 ？？？？？？？？？？？

**Comment by chenshuai2144** [comment]
慢慢研究吧。水很深的。这里毕竟不是教学的地方

**Comment by wunayou** [comment]
谢谢你的回答
