### ISSUE TITLE
🧐[问题] 为什么加载的时候标题生效，点击菜单切换页面时不生效?

### ISSUE THREAD

**Issue by jemygraw** [ant-design/ant-design-pro#8281]
我搜索了很多相关的ISSUE，但是都没有解决，所以想提问一下，谢谢。我的问题和这个现象一样，但是没有解决。https://github.com/ant-design/ant-design-pro/issues/6227

### 🧐 问题描述

 我在 umi 的 config.js 里面设置了 `title:false`，然后我打印了 BasicLayout 中 pageTitleRender 方法里面的默认标题。
![image](https://user-images.githubusercontent.com/1751166/112947564-88581680-9169-11eb-8eee-bc9ba9a2d9a8.png)

这个标题的后缀在页面初次进入和切换菜单Console打印的日志都是OK的，但是就是显示的还是 Ant Design Pro，我检查了我的route的名称，都是字符串。所以我不太清楚还有哪些地方需要更改。希望能够得到帮助。
![image](https://user-images.githubusercontent.com/1751166/112947650-a4f44e80-9169-11eb-8110-baf3ea0cdbc6.png)

```
"@ant-design/icons": "^4.0.0",
"@ant-design/pro-descriptions": "^1.2.0",
"@ant-design/pro-form": "^1.3.0",
"@ant-design/pro-layout": "^6.9.0",
"@ant-design/pro-table": "^2.17.0",
```

**Comment by jemygraw** [comment]
这个问题解决了，我在umi的config里面开启了 `layout:{}`，我对照demo看了，把这个删除之后就好了。

**Comment by haohuaZhang** [comment]
<img width="716" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/126741760/a568bbab-8655-4a7f-9318-16940290b078">
