### ISSUE TITLE
👑 [需求]能否加个功能，通过 menuItemRender, subMenuItemRender自定义菜单时,点击菜单栏进行高亮显示

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#8282]

**Comment by huangzongming** [comment]
@chenshuai2144 
![Uploading 4OC}WG[SHLN99%~)J24[[FI.png…]()

**Comment by huangzongming** [comment]
@chenshuai2144 
![高亮](https://user-images.githubusercontent.com/37889515/113653877-3a8f6100-96c9-11eb-976b-642a32424927.png)

**Comment by chenshuai2144** [comment]
说的有道理，你判断一下 selectKey 吧
