### ISSUE TITLE
🐛[BUG] windows 下yarn build 失败

### ISSUE THREAD

**Issue by linuxr** [ant-design/ant-design-pro#8283]
### 🐛 bug 描述

当存在带有参数的路由时(比如 /user/:id/detail)，
那么，windows系统下无法打包（yarn build 报错）。
linux系统下可以正常打包。

### 📷 复现步骤

新建 antd pro 工程，创建个路由和页面，比如： `/user/:id/detail`

然后 `yarn build` 打包

### 🏞 期望结果
正常打包

### 💻 复现代码
只要带有参数的路由都无法打包

### © 版本信息
和版本应该无关，是打包时在windows下无法创建带有冒号（:）的文件夹。

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/625197/112978587-1d6b0780-918a-11eb-9cfe-f96e872bf429.png)

**Comment by chenshuai2144** [comment]
关掉  https://umijs.org/config#exportstatic

umi 看起来不打算支持
