### ISSUE TITLE
🧐[问题]npm run build 的时候 触发的 postinstall ：umi g tmp 这个命令不能在docker内运行吗？

### ISSUE THREAD

**Issue by kklldog** [ant-design/ant-design-pro#8284]
### 🧐 问题描述

> ant-design-pro@4.5.0 postinstall /antd
> umi g tmp

Cannot find module '@umijs/preset-ant-design-pro' from '/antd'
Error: Cannot find module '@umijs/preset-ant-design-pro' from '/antd'
    at Function.resolveSync [as sync] (/antd/node_modules/resolve/lib/sync.js:90:15)
    at /antd/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:90:29
    at Array.map (<anonymous>)
    at getPluginsOrPresets (/antd/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:89:99)
    at resolvePresets (/antd/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:169:23)
    at new Service (/antd/node_modules/@umijs/core/lib/Service/Service.js:181:59)
    at new Service (/antd/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)
    at /antd/node_modules/umi/lib/cli.js:103:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/antd/node_modules/umi/lib/cli.js:53:103)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@4.5.0 postinstall: `umi g tmp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-30T18_01_00_745Z-debug.log

问题好像出在postinstall: `umi g tmp` 这个命令上。
umi g tmp 这个命名不能在docker内运行吗？

**Comment by chenshuai2144** [comment]
这个需要先安装依赖才能执行，看样子你的依赖没装好

**Comment by coocier** [comment]
I hava the same problem, allways alert Cannot find module '@umijs/preset-ant-design-pro'  eventhough I reinstall the packages

**Comment by aizigao** [comment]
同样问题，貌似是我看是我的docker没有写入权限的样子，楼主咋改的，不太熟悉docker

**Comment by kklldog** [comment]
> 同样问题，貌似是我看是我的docker没有写入权限的样子，楼主咋改的，不太熟悉docker

我放弃了使用 docker 来 build，我直接让 github action 构建就没问题。

**Comment by aizigao** [comment]
> > 同样问题，貌似是我看是我的docker没有写入权限的样子，楼主咋改的，不太熟悉docker
> 
> 我放弃了使用 docker 来 build，我直接让 github action 构建就没问题。

我尝试了几个小时ok了， 在npm install 后直接再跑下 npm run postintall 就可以了

```
...

# 缓存 npm install
COPY package.json package-lock.json /home/homework/
RUN cd /home/homework/ && npm install
COPY . /home/homework/


# build
RUN npm run postinstall
RUN npm run build

...
```

**Comment by Evanzew** [comment]
楼上postinstall少打了一个s, 后面的老哥们注意

**Comment by fu1-huang** [comment]
> > 同样问题，貌似是我看是我的docker没有写入权限的样子，楼主咋改的，不太熟悉docker
> 
> 我放弃了使用 docker 来 build，我直接让 github action 构建就没问题。

> 这个直接构建是怎么直接构建啊
