### ISSUE TITLE
🐛[BUG]Menu导航菜单在切换Item时需要停顿6-7秒才有反应跳到新的页面

### ISSUE THREAD

**Issue by okwen5566** [ant-design/ant-design-pro#8287]
### 🐛 bug 描述

Menu导航菜单在切换Item时需要停顿6-7秒才有反应跳到新的页面，哪怕要跳转的页面内容很简单
当减少菜单的数量时，这个速度会提升一些，目前菜单栏有60多个，最多是到三级菜单
请问是否对菜单栏的数量有所要求

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你能看到是什么堵塞了吗？ 6 7s 不至于的
