### ISSUE TITLE
🧐[问题]V5 启用按需加载，能否支持 top 进度条

### ISSUE THREAD

**Issue by artisanship** [ant-design/ant-design-pro#8289]
### 🧐 问题描述

通过dynamicImport启用按需加载，这样请求后指向了loading 组件文件，能否支持 top 进度条展示当前加载的进度。

**Comment by chenshuai2144** [comment]
export default {
  dynamicImport: {
    loading: '@/Loading',
  },
};

可以自定义组件的

**Comment by artisanship** [comment]
通过dynamicImport配置实现的加载了组件
<img width="1062" alt="QQ20210402-143449@2x" src="https://user-images.githubusercontent.com/16649952/113388898-9f914100-93c1-11eb-949c-337eec1c54db.png">



能否这样实现！
<img width="1480" alt="QQ20210402-143705@2x" src="https://user-images.githubusercontent.com/16649952/113389051-f4cd5280-93c1-11eb-97c9-d4d9e25b343c.png">

**Comment by chenshuai2144** [comment]
可以的，修改下 loading 组件就行了
