### ISSUE TITLE
构建一个新项目之后 如何修改网站的icon 我替换public里面的图片 无效 求解

### ISSUE THREAD

**Issue by yumengqin** [ant-design/ant-design-pro#829]

**Comment by chenshuai2144** [comment]
`  <link rel="icon" href="/favicon.png" type="image/x-icon">`
这东西有个刷新的事件，一般比较慢。你可以清空缓存再刷新

**Comment by MLDIE** [comment]
每次打包完都要单独编辑index.html加上`<link rel="icon" href="/favicon.png" type="image/x-icon">`吗？

**Comment by xiaohuoni** [comment]
可以在模版文件里面添加https://umijs.org/zh/guide/html-template.html#html-%E6%A8%A1%E6%9D%BF
