### ISSUE TITLE
url动态参数

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8290]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/113102421-9ae95300-9230-11eb-848a-c5a13777fe79.png)
我从另一个页面跳admin页面并且带了动态参数:key
![image](https://user-images.githubusercontent.com/27960630/113102578-cd934b80-9230-11eb-8203-a6e6b9b3f554.png)
此时url是没问题的但是，我点击左侧菜单
![image](https://user-images.githubusercontent.com/27960630/113102659-e865c000-9230-11eb-9c49-cff2cebb20bf.png)
url的动态参数没了 
![image](https://user-images.githubusercontent.com/27960630/113102740-02070780-9231-11eb-80d6-6be3213a9e56.png) 这个有没有什么办法可以处理一下
@chenshuai2144  老哥 给看看

**Comment by fangqibin** [comment]
你这样写点左侧的菜单是想跳转哪个ID？

**Comment by fangqibin** [comment]
https://beta-pro.ant.design/docs/router-and-nav-cn
这个文档有说了，可以看一下

**Comment by lovesL** [comment]
@fangqibin  就是 我点左侧菜单的时候我的那个动态id不会变成:id 就可以了

**Comment by lovesL** [comment]
相当于就是 浏览器url是动态的 菜单是静态的

**Comment by fangqibin** [comment]
> 相当于就是 浏览器url是动态的 菜单是静态的

我觉得你这个应该处理的是路由默认是ID是什么吧，左侧菜单渲染是不会自动注入ID的，在渲染的方法判断是这个路由的跳转到需要的ID

**Comment by lovesL** [comment]
在menuDataRender里面判断嘛

**Comment by fangqibin** [comment]
> 在menuDataRender里面判断嘛

看你的路由是那一级的，正常就menuItemRender处理，子菜单就subMenuItemRender这个方法处理

**Comment by chenshuai2144** [comment]
楼上正解，参数不用改放到菜单里 ，除非你写死参数的值

**Comment by lovesL** [comment]
@chenshuai2144 我这个id是动态的 就比如从A 页面链接到B页面后的url    admin/101/ccc 中间这个101是id是动态的 。然后在B页面点击左侧菜单栏希望这个id一直在ur上   我看过文档说没有注入到url   这个我在menuItemRender....也没办到 不知道还有没有别的办法  陈帅老哥

**Comment by fangqibin** [comment]
> @chenshuai2144 我这个id是动态的 就比如从A 页面链接到B页面后的url admin/101/ccc 中间这个101是id是动态的 。然后在B页面点击左侧菜单栏希望这个id一直在ur上 我看过文档说没有注入到url 这个我在menuItemRender....也没办到 不知道还有没有别的办法 陈帅老哥

没办到是遇到什么问题呢？

**Comment by lovesL** [comment]
因为我这个菜单栏的url   /project/:id/admin  在menu里面是死

**Comment by fangqibin** [comment]
> 因为我这个菜单栏的url /project/:id/admin 在menu里面是死

menuItemRender这个方法里面把ID注入进去就好了

**Comment by lovesL** [comment]
> > 因为我这个菜单栏的网址/ project /：id / admin在菜单里面是死
> 
> menuItemRender这个方法里面把ID注入进去就好了

咋注入呀 老哥  随便写个简单的代码 提供一下思路就好了

**Comment by fangqibin** [comment]
> > > 因为我这个菜单栏的网址/ project /：id / admin在菜单里面是死
> > 
> > 
> > menuItemRender这个方法里面把ID注入进去就好了
> 
> 咋注入呀 老哥 随便写个简单的代码 提供一下思路就好了

menuItemRender={(menuItemProps, defaultDom) => {
  let path = menuItemProps.path;
  if (判断不是动态路由的) {
    return <Link to={path}>{defaultDom}</Link>;
  }else{
    return <Link to={动态路由注入}>{defaultDom}</Link>;
  }
}}

**Comment by lovesL** [comment]
> > > > 因为我这个菜单栏的网址/ project /：id / admin在菜单里面是死
> > > 
> > > 
> > > menuItemRender这个方法里面把ID注入进去就好了
> > 
> > 
> > 咋注入呀 老哥 随便写个简单的代码 提供一下思路就好了
> 
> menuItemRender={(menuItemProps, defaultDom) => {
> let path = menuItemProps.path;
> if (判断不是动态路由的) {
> return {defaultDom};
> }else{
> return {defaultDom};
> }
> }}

感谢老哥 搞定了 我有点钻牛角尖了...原来这么简单

**Comment by fangqibin** [comment]
> > > > > 因为我这个菜单栏的网址/ project /：id / admin在菜单里面是死
> > > > 
> > > > 
> > > > menuItemRender这个方法里面把ID注入进去就好了
> > > 
> > > 
> > > 咋注入呀 老哥 随便写个简单的代码 提供一下思路就好了
> > 
> > 
> > menuItemRender={(menuItemProps, defaultDom) => {
> > let path = menuItemProps.path;
> > if (判断不是动态路由的) {
> > return {defaultDom};
> > }else{
> > return {defaultDom};
> > }
> > }}
> 
> 感谢老哥 搞定了 我有点钻牛角尖了...原来这么简单

祝你项目早日上线。
