### ISSUE TITLE
🧐[问题] 关于右上角dropdown快速hover会收起的问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design-pro#8291]
### 🧐 问题描述

把鼠标移动到 dropdown 下方，快速移动鼠标上下几次，发现 hover 过快可能触发了空白热区，导致了菜单收起来了。。

顺便问问，话说 dropdown 这组件能加个什么 animate = false的吗
 
### 💻 示例代码

无

**Comment by chenshuai2144** [comment]
看起来是个bug，去antd 提一下。

最好直接 更新下依赖，这种问题应该发现的人很多说不定antd 修了
