### ISSUE TITLE
🧐[问题]proTable表格（从第二页开始）如果该页只有一条数据，当数据删除重新加载表格，显示错误。（原因是传的页码此时不对）

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#8292]

**Comment by huangzongming** [comment]
![M3)B2CF_3HS)Q5Q1`VY40`B](https://user-images.githubusercontent.com/37889515/113121282-10f7b500-9245-11eb-94b1-06be0a1221fe.png)
![WCXOKSG3R8I B%~BX%_WH$2](https://user-images.githubusercontent.com/37889515/113121294-12c17880-9245-11eb-88c9-da79066aa335.png)

**Comment by fangqibin** [comment]
删除的时候应该页码初始化为第一页，这个属于逻辑开发的范畴。

**Comment by huangzongming** [comment]
@fangqibin 我在第二页以后删除，如果有多条数据，就刷新当前页也行吧~ 这时候没必要重置为第一页

**Comment by fangqibin** [comment]
> @fangqibin 我在第二页以后删除，如果有多条数据，就刷新当前页也行吧~ 这时候没必要重置为第一页

这个根据你开发的功能而定，所以你的这个问题本身就不是问题，你应该弄清楚要实现的功能是什么样子的。

**Comment by chenshuai2144** [comment]
组件库不知道你到底有几页，当前在几页的，你删除的时候最好重置一下页码。

actionRef 中有相关的方法
