### ISSUE TITLE
🐛[BUG]openapi生成的mock数据是返回的空对象，且只有200一种情况

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8294]
### 🐛 bug 描述
swagger：
![image](https://user-images.githubusercontent.com/70048681/113142409-6cce3800-925d-11eb-8879-d50c5c74ce0f.png)
![image](https://user-images.githubusercontent.com/70048681/113142792-e534f900-925d-11eb-8e90-e0783e936b51.png)

mock文件：
```
res.status(200).send({});
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
后端配置问题。

**Comment by chenshuai2144** [comment]
你 type 就是个空对象，后端应该是有什么没设置

**Comment by quicklearning123** [comment]
生成的request代码里面，对象的成员都有。就是mock数据没有，是少了啥swagger配置
