### ISSUE TITLE
🧐[问题]为什么ProLayout刷新浏览器会丢失headerContentRender内容

### ISSUE THREAD

**Issue by voidzlfan** [ant-design/ant-design-pro#8295]
### 🧐 问题描述
ant design pro 4
google浏览器

我按照[多级站点导航](https://procomponents.ant.design/components/layout#%E5%A4%9A%E7%BA%A7%E7%AB%99%E7%82%B9%E5%AF%BC%E8%88%AA)的做法，实现了两个不同菜单导航切换，点击项目条后切换菜单导航，然后设置headerContentRender为项目条的名称，如下图

![image](https://user-images.githubusercontent.com/38897523/113232885-996f6780-92d0-11eb-80f1-7ea7bd0d5586.png)

![image](https://user-images.githubusercontent.com/38897523/113233153-25818f00-92d1-11eb-9c8c-c7f92b141c30.png)

### 💻 示例代码

```javascript

<ProLayout 
  ...
  route={
        pathname === '/projectManage' || pathname === '/accountManage' ? homeMenu : projectMenu
  }
  headerContentRender={(BasicLayoutProps) => {
    if (pathname === '/projectManage' || pathname === '/accountManage') {
      return '';
    } else {
      return <span>{BasicLayoutProps.currentProject.projectName}</span>;
    }
  }}

>

</ProLayout >

这个currentProject是在点击项目条的时候设置到model

一开始以为是判断出了问题，把所有判断注释后，只返回projectName，刷新浏览器也会丢失，求帮助

```

### 🚑 其他信息
无

**Comment by fangqibin** [comment]
modal存储的当前状态下的数据，并不会缓存，刷新浏览器，model的数据是会初始化的。我觉得你应该做一下本地缓存。

**Comment by voidzlfan** [comment]
> modal存储的当前状态下的数据，并不会缓存，刷新浏览器，model的数据是会初始化的。我觉得你应该做一下本地缓存。

请问应该怎么做，用localStorage吗

**Comment by fangqibin** [comment]
sessionStorage或者localStorage都可以，看你的具体的需求

**Comment by voidzlfan** [comment]
> sessionStorage或者localStorage都可以，看你的具体的需求

谢谢，学习了，原来会初始化，导致undefined，localStorage应该能解决

**Comment by deerLoves** [comment]
实在是太坑了吧。。
