### ISSUE TITLE
🧐[问题]配置路由，多个routes导致不能渲染正确页面

### ISSUE THREAD

**Issue by AntoniaHM** [ant-design/ant-design-pro#8296]
### 🧐 问题描述
使用脚手架创建项目，在config->routes 新增一个路由，

### 💻 示例代码
`{
                name: 'list.table-list',
                icon: 'table',
                routes: [
                  {
                    path: '/list1',
                    name: 'sub-page',
                    icon: 'smile',
                    component: './TableList',
                  },
                ],
              },
              {
                name: 'list.table-list-1',
                icon: 'table',
                routes: [
                  {
                    path: '/list',
                    name: 'sub-page-1',
                    icon: 'smile',
                    component: './TableList',
                  },
                ],
              },`

### 🚑 其他信息
图有点贴不上来，抱歉

**Comment by fangqibin** [comment]
path没有配置，我建议你参考初始项目的路由。

**Comment by Enzozzzz** [comment]
name: 'list.table-list' 和name: 'list.table-list1',相当于父类的菜单， 也是需要配置path参数的，不配置当然进入不到子类菜单了

**Comment by AntoniaHM** [comment]
6666666.谢谢。
