### ISSUE TITLE
请问antd pro v5 母版页数据更新后整个页面都会刷新吗?

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#8297]
![微信图片_20210402114635](https://user-images.githubusercontent.com/33310261/113378246-1bcb5a80-93a9-11eb-8a66-41462c42a304.png)
![微信截图_20210402114738](https://user-images.githubusercontent.com/33310261/113378317-43222780-93a9-11eb-83b7-f49c9d23d575.png)
我的母版页上面有个记录通知信息条数的parrunlength-steate;但这个数据更新时内容页也重新渲染了一遍

**Comment by fangqibin** [comment]
会重新执行

**Comment by chenshuai2144** [comment]
会的，你需要用 useMemo 和 useCallBack 配置使用。

hoosk 总是会刷新 render 函数
