### ISSUE TITLE
🧐[问题]4.10.0版本如何才能防止通过URL无法进入无权限的页面？

### ISSUE THREAD

**Issue by ghostogre** [ant-design/ant-design-pro#8298]
### 🧐 防止通过URL无法进入无权限的页面

例如当前有admin和user两个权限的账户，登录admin然后退出，因为退出登录再重新登录的时候回携带原来的页面的路径，这个路径会在下次登录的时候重新跳转，那么问题来了，切换不同权限账号后，会跳入之前退出的账号才能访问的页面。怎么才能够控制当前权限不正确的时候，跳转到首页或者403页面呢。

并且4.10.0版本还是能够直接从URL进入任意页面

**Comment by fangqibin** [comment]
像你现在的问题应该是从后端返回权限路由下来才能解决这个问题，要不然就升级v5版本。
