### ISSUE TITLE
🐛[BUG] antdpro dispatch发送请求后 请求没有终止 导致挂在监听的异步函数一直loading

### ISSUE THREAD

**Issue by GamesSoul** [ant-design/ant-design-pro#8299]
### 🐛 bug 描述

在使用ProForm的onFinish时 异步函数挂载dispatch，请求异常后dispatch没有清除请求中状态，导致提交按钮无法再次点击

### 📷 复现步骤

<ProForm
        onFinish={async (values) => {
          const { dispatch } = props;
          await dispatch({
            type: 'global/login',
            payload: { ...values }
          })
        }}

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
检查下 你的代码吧，估计哪里忘记释放了，。尽量不要用 await 对 dispatch，dva 用的模型和 promise 有一些不兼容
