### ISSUE TITLE
model 是按什么纬度划分？

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design-pro#830]
业务模型还是路由又或是两者都可以。
文件命名上有什么建议呢？

**Comment by chenshuai2144** [comment]
看人需求。
按照redux的最佳实践来就好了

**Comment by yutingzhao1991** [comment]
大部分情况下业务模型和路由应该是一一对应的，然后会有一些公共的比如用户信息可以放到共用的一个 model 里面。具体要看具体业务的情况，按照路由来耦合会低一点，但是复用性差一些，所以要考虑各种因素，通常对于简单的应用一般不同路由页面直接是比较独立的，所以差不多按照路由来就行，基本上也是对应了不同的业务模型。

文件命名参考 pro 代码就行，简单明了即可。

**Comment by teeemooo** [comment]
我是按业务划分的  :-},感觉这样更清晰一些 修改哪个模块只去找对应业务文件夹就好了 实在忍不了 一个文件夹下放一坨或者一个业务模块的文件散落在不同的逻辑根目录下
```
module
  |- route
  |-service
  |- model
```

**Comment by yutingzhao1991** [comment]
嗯 这个看具体的业务就行，你觉得清晰即可。

**Comment by yangbin1994** [comment]
https://pro.ant.design/docs/server-cn#%E5%89%8D%E7%AB%AF%E8%AF%B7%E6%B1%82%E6%B5%81%E7%A8%8B
> 从上面的流程可以看出，为了方便管理维护，统一的请求处理都放在 services 文件夹中，并且一般按照 model 维度进行拆分文件，如：

上述的对应关系我觉得ok，没毛病

那么从这个角度看，model 的划分，应该主体是业务模型。

但是如果路由的公用数据，也想托管在 redux，那么也可以放到 model 里， model 不就是数据抽象吗？没毛病吧。
其实这句话的潜在意思是：我组件内部不想有共享状态，全部 connect！
