### ISSUE TITLE
antd pro 4 ProLayout 加上loading有问题

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8300]
### 🧐 问题描述
antd pro 的 ProLayout组件加上loading ，loading的state是dva-loading会出现死循环.....
![image](https://user-images.githubusercontent.com/27960630/113394080-37932880-93ca-11eb-99e2-32a78cd95cb3.png)
![image](https://user-images.githubusercontent.com/27960630/113394092-3d890980-93ca-11eb-8871-297932fa783b.png)

### 🚑 其他信息
"@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",

**Comment by lovesL** [comment]
@chenshuai2144  老哥有空的时候 给看看

**Comment by lovesL** [comment]
@chenshuai2144  老哥有空的时候 给看看

**Comment by chenshuai2144** [comment]
useLayout 多次执行了吧，你最好不要重复 useEffect

**Comment by lovesL** [comment]
> useLayout多次执行了吧，你最好不要重复useEffect
那个useEffect 不是我加的 是你们框架 自带的。。。第二个参数2 []

**Comment by chenshuai2144** [comment]
那你看看是不是有别的地方执行这个 dva ，比如首页里面

**Comment by lovesL** [comment]
> 那你看看是不是有别的地方执行这个 dva ，比如首页里面

没有，我觉得不是BasicLayout里面的useEffect的问题 
![image](https://user-images.githubusercontent.com/27960630/113663794-3e2ce300-96dd-11eb-86c1-f2e8365b558e.png) 我又加了个useEffect自定义的loading逻辑没任何问题 ，但是我吧我这个自定的不用 改用ProLayout的loading属性
![image](https://user-images.githubusercontent.com/27960630/113663960-81875180-96dd-11eb-9d70-0c2d276cf5a1.png)  
只要遇到有接口的地方。。就会出现死循环

**Comment by chenshuai2144** [comment]
是这样的，layout loaidng 会销毁掉所有子节点。

如果你里面的页面有网络调用就会不断重复，专门给 layout 做个 loaidng 吧
