### ISSUE TITLE
@ant-design/pro-layout@6.15.5 开始 头部白色bug🐛[BUG]

### ISSUE THREAD

**Issue by yuandalu** [ant-design/ant-design-pro#8302]
### 🐛 bug 描述
@ant-design/pro-layout@6.15.5 开始头部变白了
挺难看的，这么小的版本为啥改动这么大
@ant-design/pro-layout@6.15.4还没问题

具体新增代码
./node_modules/@ant-design/pro-layout/dist/layout.css:.ant-pro-basicLayout .ant-layout-header.ant-pro-header-light {
### 📷 复现步骤
直接 yarn安装，查看yarn.lock 版本超过6.15.5就会有问题
config配置开启：
  navTheme: 'light',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  splitMenus: true,

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
你不喜欢可以覆盖样式

**Comment by chenshuai2144** [comment]
headerTheme 

可以用这个 api 控制，原来是个 bug，一直覆盖不了

**Comment by yuandalu** [comment]
> 你不喜欢可以覆盖样式

不是我不喜欢，是展示样式会有问题，你可能误会我了，我不会以和人喜好去提交bug

**Comment by fangqibin** [comment]
> > 你不喜欢可以覆盖样式
> 
> 不是我不喜欢，是展示样式会有问题，你可能误会我了，我不会以和人喜好去提交bug

是我理解错了，不好意思。

**Comment by yuandalu** [comment]
> headerTheme
> 
> 可以用这个 api 控制，原来是个 bug，一直覆盖不了

好的辛苦了~

**Comment by yuandalu** [comment]
> > > 你不喜欢可以覆盖样式
> > 
> > 
> > 不是我不喜欢，是展示样式会有问题，你可能误会我了，我不会以和人喜好去提交bug
> 
> 是我理解错了，不好意思。

没关系，也是我描述问题的时候用词不清晰，带了一些感受不好的词“挺难看的”，下次我也注意，
