### ISSUE TITLE
🧐[问题]  ProFormTimePicker的format属性不起作用

### ISSUE THREAD

**Issue by xiaoxiaoll1** [ant-design/ant-design-pro#8305]
### 🧐 问题描述
ProFormTimePicker的format属性没有效果，这段代码参照的是TimePicker组件的文档

### 💻 示例代码

`<ProFormTimePicker
          name="time"
          label="上课时间"
          format="HH:mm"
        />`

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/113535886-40247280-9607-11eb-89ee-1f7fc0a45ac2.png)
