### ISSUE TITLE
🐛[BUG] HeaderSearch broken ?

### ISSUE THREAD

**Issue by jyte** [ant-design/ant-design-pro#8306]
### 🐛 bug

1st of, my appologies if I do not follow your bug template but I cannot read chinese.

I have been trying to use the HeaderSearch component, but it does not seem to behave right.

On [that page](https://v2-pro.ant.design/components/header-search), demo is working fine. However, the "CodeSandBox" as well as the "CodePen" versions look broken.

Any help to get that working ? 
Can you please update CodeSandBox and CodePen showcase ?

**Comment by chenshuai2144** [comment]
This component has been discontinued maintenance, if you want to use it, you can look at the source code here 

https://github.com/ant-design/ant-design-pro/blob/e813d0f548eec3c322b70887990510d25df3710d/src/components/HeaderSearch/index.tsx
