### ISSUE TITLE
ProTable 不触发reload的问题 🐛[BUG]

### ISSUE THREAD

**Issue by j-tyuan** [ant-design/ant-design-pro#8308]
### 🐛 bug 描述
通过使用ProTable的dataSource参数取代request参数，调用 actionRef.current?.reload();API不会触发ProTable的reload事件

### 📷 复现步骤
把ProTable的request改为dataSource调用 actionRef.current?.reload();
注意：如果两个参数同时出现则不会有问题。

### 🏞 期望结果
只有dataSource属性，调用 actionRef.current?.reload();也要触发reload事件

### 💻 复现代码
-

### © 版本信息

- ProTable 版本: 2.23.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
-

**Comment by chenshuai2144** [comment]
reload 是触发 request 的，如果用了 dataSource 就要用受控 api 自己处理了

**Comment by j-tyuan** [comment]
为什么2.17版本不是这样？用了dataSource后，protable自带刷新按钮也无效了，这该怎么解决？

**Comment by j-tyuan** [comment]
我想我可能没表达清楚：我在ProTable自定义了reload这个Api，在2.17版本通过调用actionRef.current?.reload()这个api是可以触发我自定义的reload这个api的，但是到了2.23.2这个版本，就不会触发reload这个api了（当然是dataSource取代request之后才会这样）。

**Comment by chenshuai2144** [comment]
代码展示出来试试

**Comment by Miever1** [comment]
> 我想我可能没表达清楚：我在ProTable自定义了reload这个Api，在2.17版本通过调用actionRef.current?.reload()这个api是可以触发我自定义的reload这个api的，但是到了2.23.2这个版本，就不会触发reload这个api了（当然是dataSource取代request之后才会这样）。

同样的问题，这个有后续吗？

**Comment by MidnightYKT** [comment]
> > 我想我可能没表达清楚：我在ProTable自定义了reload这个Api，在2.17版本通过调用actionRef.current?.reload()这个api是可以触发我自定义的reload这个api的，但是到了2.23.2这个版本，就不会触发reload这个api了（当然是dataSource取代request之后才会这样）。
> 
> 同样的问题，这个有后续吗？

Hello, did you manage to solve this problem?
