### ISSUE TITLE
tyarn start的时候报有关umi的错误🧐[问题]

### ISSUE THREAD

**Issue by gangli66** [ant-design/ant-design-pro#8309]
### 🧐 问题描述

执行tyarn后执行tyarn start，能看到webpack在处理各种依赖，但是处理到一段时间以后就会报下面这个错：
This dependency was not found:

* D:\IdeaProjects\re-current-report-db-webew-ewb\re-current-report-
db-web\src\.umi\plugin-openapi\openapi.tsx in ./src/.umi/core/
s.ts

To install it, you can run: npm install --save D:\IdeaProjects
urrent-report-db-webew-ewb\re-current-report-db-web\src\.umi\p
-openapi\openapi.tsx

搞了好久也没搞好，node也重装了，镜像也改成淘宝了，antd也装了。

**Comment by fangqibin** [comment]
看提示是需要执行npm install --save D:\IdeaProjects
urrent-report-db-webew-ewb\re-current-report-db-web\src.umi\p
-openapi\openapi.tsx
但是我觉得还是有依赖包没有加载全的问题。

**Comment by chenshuai2144** [comment]
感觉是路径导致的问题，src. umi 这个感觉就是不对的
