### ISSUE TITLE
npm start报错 error：I/o error,read ,binding.read

### ISSUE THREAD

**Issue by dangyanglim** [ant-design/ant-design-pro#831]
![image](https://user-images.githubusercontent.com/16640185/35497660-fef86752-0505-11e8-8ab3-6b2368e0d5ff.png)

**Comment by dangyanglim** [comment]
最新从git上面拉下来的

**Comment by chenshuai2144** [comment]
这个错误略微底层了点。 感觉像是硬件的问题。
试着重新安装node之类的。

**Comment by dangyanglim** [comment]
@chenshuai2144 重装几次了

**Comment by chenshuai2144** [comment]
i/o异常。换个文件夹？

**Comment by dangyanglim** [comment]
@chenshuai2144 ，换过文件夹，我换下盘符吧

**Comment by dangyanglim** [comment]
换了F盘就可以了
