### ISSUE TITLE
🐛[BUG]PageContainer设置了header.title=false，也没有显示面包屑，但是ghost背景还在

### ISSUE THREAD

**Issue by wuyouhuaz** [ant-design/ant-design-pro#8311]
### 🐛 bug 描述
PageContainer设置了header.title=false，也没有显示面包屑，但是ghost背景还在

### 📷 复现步骤
在umi下，
使用antd pro，
页面使用PageContainer组件，
设置了header.title = false；
标题不显示，也没有面包屑，从控制台看到背景ghost还在，因为有padding值，把整个容器撑开了

### 🏞 期望结果
可以控制header是否显示
header中的元素控制，如果没有就全部隐藏，不要显示ghost背景
如果有元素，就显示元素内容

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本:[3.4.0]
- 浏览器环境: chrome(最新)
- 开发环境 [windos 10]

**Comment by chenshuai2144** [comment]
这个好像做过了，你试试更新到新版
