### ISSUE TITLE
🧐[问题]如何在代码中获取publicPath

### ISSUE THREAD

**Issue by waylon-gmail** [ant-design/ant-design-pro#8312]
求助大佬们： 设置 img的src不加 publicPath 在build之后会找不到图片。dev时没有问题。

前缀加上publicPath就可以获取到图片。但是不知道用代码怎么获取到值。目前是写死的。

publicPath: /admin/

<img src={`/admin/abc/xxxxxx.png`}

**Comment by fangqibin** [comment]
publicPath是打包写进去的路径，按照你现在的情况，publicPath可以是"/",在public文件夹创建admin/abc/xxxxxx.png这个目录就可以了，使用的时候可以/admin/abc/xxxxxx.png
如果你图片不是想上传到别的服务器，publicPath对你来说用处不大

**Comment by waylon-gmail** [comment]
@fangqibin 谢谢大佬解答。我的需求是要部署二级目录的。功能都没有问题。只是这个图片的路径我现在只能是自己再弄个变量加前缀。

**Comment by chenshuai2144** [comment]
https://umijs.org/config#base

你需要的是这个

**Comment by szw0606** [comment]
用config中的define
![image](https://github.com/ant-design/ant-design-pro/assets/8005008/43cf3ccb-d74f-4327-b0b7-12d12d0e0cdb)
