### ISSUE TITLE
跟新最近的v5版本，头部样式控制不生效🧐[问题]

### ISSUE THREAD

**Issue by yuandalu** [ant-design/ant-design-pro#8313]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/3860040/113647521-8cca8500-96bd-11eb-8553-b65c48a1f9c4.png)
navTheme: 'light',
  headerTheme: 'dark',
原本使用白色主题，头部是黑色的，然后更新之后头部也变白了，按钮看不到了，根据上次提交的问题使用了headerTheme设置头部为黑色，但是不生效，虽然说我能自己强制重写一下，但是这个觉得还是官方支持好一些，最主要这个感觉应该是支持这样的，最早在之前的版本，默认就是没问题的

### 💻 示例代码
{
  navTheme: 'light',
  headerTheme: 'dark',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  splitMenus: true,
  title: '',
  pwa: false,
  logo: '/logo.svg',
  iconfontUrl: '',
}

https://github.com/ant-design/ant-design-pro/issues/8302

**Comment by fangqibin** [comment]
我刚想起来你这个问题，我当时是测试没有问题上线出现你的这个问题，我当时紧急就强制重写处理掉了，确实是官方应该修改一下。有修复了也告知我一下。

**Comment by yuandalu** [comment]
> 这个

👌

**Comment by cloudsnet** [comment]
官方的V4,V5演示站也一样不生效

**Comment by imgoby** [comment]
I have also encountered this problem, how to solve it?
