### ISSUE TITLE
🐛[BUG]关于组件加载失败的问题

### ISSUE THREAD

**Issue by aierweisi** [ant-design/ant-design-pro#8316]
### 🐛 bug 描述
切换路由的时候有时候会出现组件加载失败的问题，就一直在那里显示加载状态，查看控制台发现是请求的组件加载失败，请问这个问题有办法进行优化吗

### © 版本信息4.0版本

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by aierweisi** [comment]
![image](https://user-images.githubusercontent.com/33406910/113672232-04160e00-96ea-11eb-9eb8-a7ab309bd5af.png)

**Comment by YuZongYangHi** [comment]
我貌似在开发环境也出现了这个问题， 生产环境还不确定

**Comment by fangqibin** [comment]
请求的组件加载失败，这个可以截图看看吗

**Comment by chenshuai2144** [comment]
代码压缩没打开？

**Comment by aierweisi** [comment]
> 请求的组件加载失败，这个可以截图看看吗

这个不是很容易复现，就是类似于图片资源一样，请求的结果是404，然后就一直在加载中了

**Comment by chenshuai2144** [comment]
请求失败一般是 serve 的问题，最好的解决办法就是把代码分割关掉
