### ISSUE TITLE
🐛[BUG] Trend flag加载为空

### ISSUE THREAD

**Issue by YuZongYangHi** [ant-design/ant-design-pro#8318]
### © 版本信息

"@ant-design/charts": "^1.1.1",
  "@ant-design/icons": "^4.0.0",
  "@ant-design/pro-card": "^1.11.5",
  "@ant-design/pro-descriptions": "^1.2.0",
  "@ant-design/pro-form": "^1.3.0",
  "@ant-design/pro-layout": "^6.9.0",
  "@ant-design/pro-table": "^2.17.0",
  "@antv/data-set": "^0.11.0",
  "@antv/l7": "^2.1.9",
  "@antv/l7-maps": "^2.1.9",
  "@antv/l7-react": "^2.1.9",
  "ant-design-pro": "^2.3.2",
  "antd": "^4.12.0",
  "@ant-design/pro-cli": "^1.0.28",
  "@umijs/preset-ant-design-pro": "^1.2.0",

**Comment by YuZongYangHi** [comment]
![image](https://user-images.githubusercontent.com/35584408/113800170-12673700-9789-11eb-909f-c9d5aecf062d.png)

**Comment by YuZongYangHi** [comment]
<Statistic title="本月带宽总用量" suffix={'G'} value={60} />

              <span>
                月环比
                <Trend flag='up' reverseColor style={{ marginLeft: 8, color: 'rgba(0,0,0,.85)' }}>
                  12%
                </Trend>
              </span>

**Comment by YuZongYangHi** [comment]
flag的状态图标实际未展示出来， 并且控制台报错！

**Comment by YuZongYangHi** [comment]
![image](https://user-images.githubusercontent.com/35584408/113800260-375baa00-9789-11eb-9186-75a261a4891f.png)

**Comment by chenshuai2144** [comment]
Trend 已经无法支持 antd@4 了，时候跑路了



https://charts.ant.design/zh-CN/demos/global
