### ISSUE TITLE
🧐[问题]发布到线上之后，怎么去掉开发模式的URL和悬浮按钮

### ISSUE THREAD

**Issue by EvanYin** [ant-design/ant-design-pro#8319]
### 🧐 问题描述

URL里面会有这一串：
![image](https://user-images.githubusercontent.com/8558105/113802768-de424500-978d-11eb-9e9e-8c8d8dd404b9.png)
页面右侧的悬浮图标也还在：
![image](https://user-images.githubusercontent.com/8558105/113802827-f4500580-978d-11eb-8ee4-ec080efda82c.png)
这个要怎么处理？

**Comment by fangqibin** [comment]
打包的时候右边这个图标会去掉的，只有在开发模式才有。可以build的时候加TECHUI_PREVIEW='none'这个试试

**Comment by EvanYin** [comment]
> 打包的时候右边这个图标会去掉的，只有在开发模式才有。可以build的时候加TECHUI_PREVIEW='none'这个试试

好像不起作用，而且URL中的额外的参数还是有

**Comment by fangqibin** [comment]
这个额外的参数是怎么来的

**Comment by EvanYin** [comment]
> 这个额外的参数是怎么来的

看上去像是把defaultSettings.js里面的部分参数拼上去了
![image](https://user-images.githubusercontent.com/8558105/113858192-09508700-97d6-11eb-95fd-d43088de8595.png)

**Comment by fangqibin** [comment]
> > 这个额外的参数是怎么来的
> 
> 看上去像是把defaultSettings.js里面的部分参数拼上去了
> ![image](https://user-images.githubusercontent.com/8558105/113858192-09508700-97d6-11eb-95fd-d43088de8595.png)

你部署之后访问的时候不要带参数就好了。也不可能自动帮你补上去吧

**Comment by EvanYin** [comment]
> > > 这个额外的参数是怎么来的
> > 
> > 
> > 看上去像是把defaultSettings.js里面的部分参数拼上去了
> > ![image](https://user-images.githubusercontent.com/8558105/113858192-09508700-97d6-11eb-95fd-d43088de8595.png)
> 
> 你部署之后访问的时候不要带参数就好了。也不可能自动帮你补上去吧

是自动补充上去的，不知道是不是哪里有个什么配置开关

**Comment by chenshuai2144** [comment]
是不是不小心把 SettingDrawer 给发布上去了

**Comment by EvanYin** [comment]
> SettingDrawer

对的，我把BasicLayout里面的SettingDrawer注释掉就OK了，谢啦
