### ISSUE TITLE
plugin-init-state 的 refresh似乎没起作用

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8320]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/27960630/113834779-cda9c300-97bd-11eb-9c78-9b21db4c6451.png)

在useEffect去refresh  然后在format中去获取initialState还 是取不到最新的值
![image](https://user-images.githubusercontent.com/27960630/113834001-e1085e80-97bc-11eb-9509-56874782e45f.png)
但是我app.js中已经从接口拿到新的数据 

### 🚑 其他信息
proV4

**Comment by lovesL** [comment]
我刚测试了下  把 BasicLayout里面的那个refresh换到页面上去触发....在BasicLayout 还是取不到最新的

**Comment by chenshuai2144** [comment]
refresh 是什么功能？

**Comment by fangqibin** [comment]
> refresh 是什么功能？

应该是useModel的refresh

**Comment by chenshuai2144** [comment]
可以@ 一下作者试试，我好像没用过这个功能

**Comment by fangqibin** [comment]
> 可以@ 一下作者试试，我好像没用过这个功能

https://beta-pro.ant.design/docs/initial-state-cn
官方这个文档是有提到，我也试了好像没用

**Comment by lovesL** [comment]
> > 可以@ 一下作者试试，我好像没用过这个功能
> 
> https://beta-pro.ant.design/docs/initial-state-cn
> 官方这个文档是有提到，我也试了好像没用

我找到问题所在了 就是BasicLayout.js中 

![image](https://user-images.githubusercontent.com/27960630/113961566-d69ba280-9858-11eb-8861-a7125ab5257a.png)

还有没别的办法。。。可以控制菜单显示隐藏 我需要动态控制菜单

**Comment by lovesL** [comment]
> > 可以@ 一下作者试试，我好像没用过这个功能
> 
> https://beta-pro.ant.design/docs/initial-state-cn
> 官方这个文档是有提到，我也试了好像没用

其实就是个动态控制路由的需求 路由配置前端 需要调个接口查询出一个字段来作为某个菜单的显示和隐藏 但是接口是异步的 menuDataRender这个方法内部是是同步的 这就导致我在menuDataRender内部拿不到接口取出的字段无法判断 ，有没有什么别的办法可以去控制

**Comment by lovesL** [comment]
@fangqibin

**Comment by fangqibin** [comment]
> @fangqibin

我觉得可以用access试试，在文件access.ts控制菜单的权限

**Comment by lovesL** [comment]
> > @fangqibin
> 
> 我觉得可以用access试试，在文件access.ts控制菜单的权限

我没用access 我是proV4  我只想重新过滤下菜单

**Comment by lovesL** [comment]
> > > @fangqibin
> > 
> > 
> > 我觉得可以用access试试，在文件access.ts控制菜单的权限
> 
> 我没用access 我是proV4 我只想重新过滤下菜单

我觉得这算个问题 menuDataRender应该改变一下支持异步

**Comment by fangqibin** [comment]
> > > > @fangqibin
> > > 
> > > 
> > > 我觉得可以用access试试，在文件access.ts控制菜单的权限
> > 
> > 
> > 我没用access 我是proV4 我只想重新过滤下菜单
> 
> 我觉得这算个问题 menuDataRender应该改变一下支持异步

我看示例代码是支持的，官方文档地址：https://v4-pro.ant.design/docs/router-and-nav-cn

**Comment by lovesL** [comment]
> > > > > @fangqibin
> > > > 
> > > > 
> > > > 我觉得可以用access试试，在文件access.ts控制菜单的权限
> > > 
> > > 
> > > 我没用access 我是proV4 我只想重新过滤下菜单
> > 
> > 
> > 我觉得这算个问题 menuDataRender应该改变一下支持异步
> 
> 我看示例代码是支持的，官方文档地址：https://v4-pro.ant.design/docs/router-and-nav-cn

老哥 这个demo相当于是整个菜单路由是在后台。。。我想的是如过菜单路由是在前端  然后menuDataRender 支持异步的条件进行筛选

**Comment by chenshuai2144** [comment]
看这个最佳实践吧

https://pro.ant.design/zh-CN/docs/advanced-menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95

**Comment by fangqibin** [comment]
> > > > > > @fangqibin
> > > > > 
> > > > > 
> > > > > 我觉得可以用access试试，在文件access.ts控制菜单的权限
> > > > 
> > > > 
> > > > 我没用access 我是proV4 我只想重新过滤下菜单
> > > 
> > > 
> > > 我觉得这算个问题 menuDataRender应该改变一下支持异步
> > 
> > 
> > 我看示例代码是支持的，官方文档地址：https://v4-pro.ant.design/docs/router-and-nav-cn
> 
> 老哥 这个demo相当于是整个菜单路由是在后台。。。我想的是如过菜单路由是在前端 然后menuDataRender 支持异步的条件进行筛选

请求不一定要走网络，可以前端直接返回promise也是可以的
