### ISSUE TITLE
🧐[Question] Why `yarn.lock` is included in `.gitignore` ?

### ISSUE THREAD

**Issue by kevinadhiguna** [ant-design/ant-design-pro#8321]
### 🧐 问题描述

Hello, why `yarn.lock` is included in `.gitignore` ?

I wonder this after finding a couple of articles that says `yarn.lock` should be committed : 
- [Lockfiles should be committed on all projects - Yarn official blog](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)
- [Should I commit the yarn.lock file and what is it for? - Stackoverflow](https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for)

**Comment by chenshuai2144** [comment]
Our practice does not recommend locking packages
