### ISSUE TITLE
🐛[BUG]access失效，用之前对rootContainer的解决办法无用

### ISSUE THREAD

**Issue by John-Andrew-TMD** [ant-design/ant-design-pro#8322]
### 🐛 bug 描述
```
`const PageWraper = ({ children, routes }: { children: any; routes: any }) => {
  console.log(children.props.routes,"children.props.routes")
  return (
    <AliveScope>
      {React.cloneElement(children, {
        ...children.props,
        routes:children.props.routes
        // routes
      })}
    </AliveScope>
  );
};

export function rootContainer(container: JSX.Element) {
  return React.createElement(PageWraper, null, container);
}`
```

如上述代码PageWraper 的入参routes为undefined,貌似之前不会，是不是这几天改了什么，没有routes 我用children.props.routes之后，access也没生效，左侧菜单没用移除
除此以外，https://github.com/wangJacker/ant-design-pro-V5-multitab包括这个项目，重新安装依赖包，用yarn install,也出现上述情形
### 📷 复现步骤

![image](https://user-images.githubusercontent.com/14741985/113975751-93e6c400-9872-11eb-9023-717d2f88711b.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by JS-an** [comment]
估计你用了keep-alive插件，这个插件给你搞了个rootContainer
