### ISSUE TITLE
v5版本 PageContainer 根据路由自动生成的面包屑 怎么设置某一级面包屑不可点击？🧐[问题]

### ISSUE THREAD

**Issue by uennki** [ant-design/ant-design-pro#8323]
### 🧐 问题描述

根据路由配置的信息，自动生成面包屑，不可点击设置

### 💻 示例代码

这里是 route 的配置代码：
![image](https://user-images.githubusercontent.com/31059833/113992035-a1f21000-9885-11eb-8e08-78f01132a361.png)

### 🚑 其他信息

根据路由配置出来的前端界面，一级 admin 面包屑没有被禁用，还是可以点击。造成点击后，跳转的页面是空白的。
![image](https://user-images.githubusercontent.com/31059833/113991449-09f42680-9885-11eb-9801-3efc2d9cabe7.png)

**Comment by fangqibin** [comment]
我觉得/admin重定向到一个路由，就可以解决你这个问题了

**Comment by lishaoh** [comment]
@uennki  可以在app.tsx里面重写面包屑

![image](https://user-images.githubusercontent.com/20917295/115990412-ba885700-a5f5-11eb-8b69-bad0eea638be.png)

**Comment by cangsnage** [comment]
> 我觉得/admin重定向到一个路由，就可以解决你这个问题了

我想问下楼上如果动态设置面包屑应该怎么写呢  路由name 是动态的
