### ISSUE TITLE
🐛[BUG]将导航layout=mix，splitMenus=true（混合菜单布局）时headerTheme值无效

### ISSUE THREAD

**Issue by cloudsnet** [ant-design/ant-design-pro#8326]
### 🐛 bug 描述
将导航layout=mix，splitMenus=true（混合菜单布局）时headerTheme值无效
navTheme=light 时 headerTheme= dark，
header 背景色为白色，导致文字看不清楚

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
#8313
