### ISSUE TITLE
加载资源文件

### ISSUE THREAD

**Issue by qingming418** [ant-design/ant-design-pro#833]
怎样才能加载全局的资源文件呢？比如添加全局js或css文件。
因为在index.ejs的<head></head>里引用的css文件或js文件，在运行后内容不对

**Comment by chenshuai2144** [comment]
内容不对？具体是指？

**Comment by qingming418** [comment]
![image](https://user-images.githubusercontent.com/20061205/35501230-4fd7aa62-0514-11e8-83d7-1053253b8431.png)
浏览器加载后就是这个，这个不是文件的内容

**Comment by chenshuai2144** [comment]
你要加载的文件需要放到public文件夹下。

**Comment by qingming418** [comment]
哦哦，我试下哈。谢谢
