### ISSUE TITLE
yarn create umi一直失败🧐[问题]

### ISSUE THREAD

**Issue by gaomeng965** [ant-design/ant-design-pro#8330]
### 🧐 问题描述

yarn create umi一直失败，
success Installed "create-umi@0.26.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? �🧙 Be the first to experience the new umi@3 ? Pro V4
? �🧙 Which language do you want to use? JavaScript
? �🤓 Do you need all the blocks or a simple scaffold? comple
最后一步一直没成功过，也没有设置代理
![image](https://user-images.githubusercontent.com/22706391/114142897-0e344880-9946-11eb-8257-6918f7f3988b.png)

![image](https://user-images.githubusercontent.com/22706391/114142727-e04f0400-9945-11eb-8030-84e3d155d705.png)

### 💻 示例代码
fatal: unable to access 'https://gitee.com/ant-design/ant-design-pro/': getaddrinfo() thread failed to start

**Comment by gaomeng965** [comment]
![Uploading image.png…]()

**Comment by gaomeng965** [comment]
同样的网络下 ，mac都可以 git clone,
但是win下都不行

**Comment by gaomeng965** [comment]
防火墙也都关了 也不行

**Comment by fangqibin** [comment]
看着像没有权限，

**Comment by chenshuai2144** [comment]
你人肉执行一下红框内的代码呢
![image](https://user-images.githubusercontent.com/8186664/114812004-bda76a00-9de1-11eb-95bf-2c31bc48abe9.png)

**Comment by gaomeng965** [comment]
> 你人肉执行一下红框内的代码呢
> ![image](https://user-images.githubusercontent.com/8186664/114812004-bda76a00-9de1-11eb-95bf-2c31bc48abe9.png)

也不行

**Comment by chenshuai2144** [comment]
重装下 git 吧。clone 都失败估计poxy 配置的出问题了
