### ISSUE TITLE
🐛[BUG]将项目 导入idea 运行  tyarn install  命令 会报错误 

### ISSUE THREAD

**Issue by 670432337** [ant-design/ant-design-pro#8331]
### 🐛 bug 描述

下载 项目 导入idea 运行  tyarn install  命令 会报这个错误 且 下载失败
![image](https://user-images.githubusercontent.com/66188603/114149610-ae41a000-994d-11eb-88fb-82b657f28bdb.png)

Error:(9, 12) TS6046: Argument for '--jsx' option must be: 'preserve', 'react-native', 'react'.
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级一下 编辑器的 ts 版本，这个 featrue 的最新的 ts 加入的，可以减少包大小
