### ISSUE TITLE
现在v5版本组件中是不是不引用```React````都可以了🧐[问题]

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#8332]
### 🧐 问题描述
在```vs code```中引用```React```提示未使用，删除后也无影响，是否不引用也可以了

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/34082148/114151987-4b9dd380-9950-11eb-81d7-2611f9b51e40.png)

**Comment by drizzlesconsin** [comment]
React 17+ 不再需要导入 React 包，会自动导入。
具体可以阅读官方文档 [introducing-the-new-jsx-transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

**Comment by 569202812** [comment]
感谢解惑
