### ISSUE TITLE
使用 antd-pro-v5 ，配置的水印不显示

### ISSUE THREAD

**Issue by hzhijun** [ant-design/ant-design-pro#8334]
![image](https://user-images.githubusercontent.com/26991817/114166842-cff85280-9960-11eb-87b3-d1464b86a1b0.png)

**Comment by artisanship** [comment]
似乎没有发现你说的问题，不过可以这里看看 https://procomponents.ant.design/components/water-mark

**Comment by hzhijun** [comment]
我是直接配置在 app.tsx 中的。
现在项目基本开发完了，大概有几十个页面，不想改动页面的代码了，所以就想在全局配置下水印的属性，结果水印没生效。
页面的底层组件用的是 Card，不是PageContainer。

**Comment by chenshuai2144** [comment]
PageContainer 是必须的，水印是 PageContainer的功能。

layout 上面的只是快捷配置。你可以单独用水印组件在 最外面包一下

**Comment by hzhijun** [comment]
单独用水印组件在 最外面包一下是可以实现，这样的话，需要在每页页面都包裹一边，有没有别的方式实现了呢。

**Comment by chenshuai2144** [comment]
PageContainer 定向搞一下

**Comment by hzhijun** [comment]
上一个版本的 antd-pro 框架，我们是在 BasicLayout.jsx 中 ProLayout 子节点中直接加水印组件来实现的，页面没有做任何改动。
![Uploading image.png…]()

**Comment by chenshuai2144** [comment]
图挂了

**Comment by hzhijun** [comment]
![image](https://user-images.githubusercontent.com/26991817/114810603-fe51b400-9dde-11eb-82d1-25752aeeb063.png)

**Comment by chenshuai2144** [comment]
v5 也可以的。有个 childrenRender

**Comment by hzhijun** [comment]
可以了，这个属性文档中没有，之前一直没找到。

**Comment by jingege** [comment]
> 可以了，这个属性文档中没有，之前一直没找到。

怎么解决的？
