### ISSUE TITLE
route.ts 菜单PATH在哪定义的🧐[问题]

### ISSUE THREAD

**Issue by jieweili** [ant-design/ant-design-pro#8335]
![image](https://user-images.githubusercontent.com/4555301/114183434-45225280-9976-11eb-9f3e-189361d1a98b.png)
这2个路径并不相同

**Comment by drizzlesconsin** [comment]
中心化路由的 `path` 跟 `pages` 下的文件目录不一定要一一对应的
上图你可以把 path `/list` 改成 `/table-list`

**Comment by deepocean1226** [comment]
我理解的是path就是路由，component指代你pages下的页面，你目前的状态url输入/FromList就会显示FormList页面吧

**Comment by chenshuai2144** [comment]
path 是浏览器访问的路径
component 是这个路径要挂载的组件
