### ISSUE TITLE
项目启动的时候，为什么终端一直回车，出现一大块空白？

### ISSUE THREAD

**Issue by duziten** [ant-design/ant-design-pro#8337]
### 🧐 问题描述

start 的时候 webpack 编译开始，然后终端就疯狂回

### 💻 示例代码

![image](https://user-images.githubusercontent.com/29852019/114262622-9c2a3500-9a13-11eb-94a3-3def9c48003c.png)

**Comment by chenshuai2144** [comment]
base 兼容性的问题，可以试试powershell 等现代终端
