### ISSUE TITLE
🐛[BUG]yarn create umi test 创建项目时报错，请适配空格目录

### ISSUE THREAD

**Issue by JonneyDong** [ant-design/ant-design-pro#8340]
### 🐛 bug 描述

在windows开发环境中无法创建项目。本机nodejs安装目录为 "D:\Program Files\nodejs"
当运行yarn create umi test 时异常信息 'D:\Program' 不是内部或外部命令，也不是可运行的程序

### 💻 复现代码

E:\workspaces\gits\ant-design-pro>yarn create umi test
yarn create v1.22.10
[1/4] Resolving packages...
warning create-umi > sylvanas > @umijs/fabric > stylelint-config-rational-order > stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-umi@0.26.0" with binaries:
      - create-umi
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed.
Exit code: 1
Command: D:\Program Files\nodejs\node_global\bin\create-umi
Arguments: test
Directory: E:\workspaces\gits\ant-design-pro
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
先绕开一下吧，这个是 base 和 node.js 之间转化的锅。

不是很好改，需要对很多库做改动
