### ISSUE TITLE
🧐[问题] 360报esbuild中有木马？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#8345]
### 🧐 问题描述
360报esbuild中有木马？  是咋回事呀？

这个是提示
![QQ截图20210412120104](https://user-images.githubusercontent.com/34436863/114339895-e5e85c00-9b88-11eb-9b0f-be660c66aeaa.png)

**Comment by fanhualei** [comment]
查看分析页代码时，见引用了一个组件`numeral ` .  然后就执行
```
tyarn add numeral 
```

紧接着360包木马错误，按照提示立即清除。 然后antDesignPro就启动不了了。

然后把node下载的包给删除了，也不敢引用numeral。 执行下面代码，就可以运行了。
```
tyarn install
yarn start
```
难道`numeral ` 有木马？

**Comment by chenshuai2144** [comment]
可能是误报，换成火绒？

**Comment by fanhualei** [comment]
360总报错，害怕有木马，就换了这个：[accounting](http://openexchangerates.github.io/accounting.js/)



> 安装

```shell
npm i accounting
```



例子：

```tsx
// 有前缀，小数点后没有
accounting.formatMoney(12345678, '¥', 0);

// 有前缀，小数点后两位，如果没有那么就加零
accounting.formatMoney(12345678, '¥', 2);

accounting.formatNumber(5318008); // 5,318,008

accounting.toFixed(0.615, 2); // "0.62"
```
