### ISSUE TITLE
探讨Login的风格修改

### ISSUE THREAD

**Issue by my9988** [ant-design/ant-design-pro#8346]
https://technext.github.io/material_able/auth-normal-sign-in.html

现在比较流行如上网址的登录风格，如果使用antd，想要修改成这个风格好像挺难，不知道谁有好的建议？

**Comment by fangqibin** [comment]
如果只是这个登录页面，自己写一个替换就好了

**Comment by my9988** [comment]
> 
> 
> 如果只是这个登录页面，自己写一个替换就好了

自己写一个当然是可以，但是就无法利用antd的优势，我之所以在这里提出，是想让antd比较下优劣，方能进步。
