### ISSUE TITLE
🧐[问题]怎么使babel-loader exclude指定文件夹？

### ISSUE THREAD

**Issue by thornsh** [ant-design/ant-design-pro#8348]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/23608913/114357759-b7787a00-9ba4-11eb-9988-1f77ddd73e80.png)
#### 如图，好像只有include选项？但如果想exclude指定文件夹应该怎么做呢？

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#extrababelincludes

看看这里，不行就要用 webpack 来自定义了
