### ISSUE TITLE
🐛[BUG]:- Icon in submenu Children is not coming

### ISSUE THREAD

**Issue by kumarshambhu** [ant-design/ant-design-pro#8349]
### 🐛 bug 描述
Icon is submenu is not coming, even i am giving icon filed in routes.js in config folder.
For sample, i am adding stackoverflow link
https://stackoverflow.com/questions/62870512/ant-design-pro-how-to-add-icon-in-submenu

**Comment by fangqibin** [comment]
`subMenuItemRender={(menuItemProps, defaultDom) => {
        if (menuItemProps.icons) {
          const IconComp = iconsComponent[menuItemProps.icons];
          return <div><IconComp  /><span>{defaultDom}</span></div>;
        }
        return <div>{defaultDom}</div>;
      }}`

**Comment by kumarshambhu** [comment]
hi @fangqibin ,
Sorry for wrong title of defect.

Icon in submenu is coming easily, nothing is required. But Icon in submenu children is not coming.

https://imgur.com/BqO1Vhi

**Comment by chenshuai2144** [comment]
The designer thinks that the secondary menu does not need an icon, so we canceled it by default

**Comment by kumarshambhu** [comment]
Hi,
any alternative or customization to display icon?

**Comment by kumarshambhu** [comment]
Cancelled by default is good, 
but is there any way so that I can display the icon?
It is requirement in my project.

**Comment by chenshuai2144** [comment]
```
const menuItemRender = (menuItemProps, defaultDom) => {
  if (
    menuItemProps.isUrl ||
    !menuItemProps.path ||
    location.pathname === menuItemProps.path
  ) {
    return defaultDom;
  }

  return (
    <Link to={menuItemProps.path}>
      {menuItemProps.icon}
      {defaultDom}
    </Link>
  );
};
```

you can set menuItemRender

**Comment by xyzabc0004** [comment]
有效果！

**Comment by kumarshambhu** [comment]
I did little better way


menuItemRender={(menuItemProps, defaultDom) => {
 if(defaultDom.props.children[0] == null){
   const defaultDom1 = {
	 ...defaultDom,
	 props: {
	   ...defaultDom.props,
	   children: [menuItemProps.icon, defaultDom.props.children[1]]
	 }
   };
   return <Link to={menuItemProps.path}>{defaultDom1}</Link>;
 }
 if (
   menuItemProps.isUrl ||
   !menuItemProps.path ||
   location.pathname === menuItemProps.path
 ) {
   return defaultDom;
 }

 return <Link to={menuItemProps.path}>{defaultDom}</Link>;
}}
