### ISSUE TITLE
🧐[问题]pro的默认头像很好看，请问哪里可以找到类型蚂蚁的头像呢

### ISSUE THREAD

**Issue by hongcyu** [ant-design/ant-design-pro#8350]
### 🧐 问题描述
看preview.pro.ant.design的头像很可爱，想多找几个来当默认头像，想询问可以提供一些其他类似的蚂蚁头像吗？

**Comment by hongcyu** [comment]
看preview.pro.ant.design的默认头像很可爱，想拿一些作为默认头像，询问下可以提供类似蚂蚁头像的资源吗~

**Comment by chenshuai2144** [comment]
https://ant.design/docs/resources-cn
这里有资源下载哦，也可以在知乎和我们的设计师联系
