### ISSUE TITLE
用了约定式路由怎么让不同页面显示不同layout

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/ant-design-pro#8352]
![image](https://user-images.githubusercontent.com/33448924/114509553-397da700-9c68-11eb-89ef-93ad144771f2.png)
v5开启约定式路由, config.ts中的routes已注释掉，怎么让登录页不显示header

**Comment by fangqibin** [comment]
是不是路由配置有问题，还有跳转到登录页，你是直接访问登录，还是访问别的页面跳转到登录页，这个就要看业务逻辑了。

**Comment by BabyFriedCake** [comment]
> 是不是路由配置有问题，还有跳转到登录页，你是直接访问登录，还是访问别的页面跳转到登录页，这个就要看业务逻辑了。

routes被我注释掉了，约定式路由会生成路由配置。现在直接访问登录。

**Comment by chenshuai2144** [comment]
约定式好像不行，去 umi 问问 @xiaohuoni
