### ISSUE TITLE
更新文档 👑 [需求]

### ISSUE THREAD

**Issue by Itroads** [ant-design/ant-design-pro#8355]
### 🥰 需求描述

V5的文档，都是复制V4的。更新下文档吧。用V5，比如像从服务器请求左侧菜单。但是文档还是V4的更改 
   src/layouts/BasicLayout.tsx。不只一处。
### 🧐 解决方案

   请重视使用手册的编写。

**Comment by chenshuai2144** [comment]
有兴趣可以直接 pr
