### ISSUE TITLE
🧐[问题] 预览项目的代码在哪下载

### ISSUE THREAD

**Issue by BinHQing** [ant-design/ant-design-pro#8357]
预览项目的代码在哪下载

https://preview.pro.ant.design/dashboard/analysis
就是这个 找了好久没找到

**Comment by yipanhuasheng** [comment]
yarn create umi创建模板，选择ant-design-pro后边选择全量

**Comment by xiaohuoni** [comment]
下载项目之后，执行 `fetch:blocks` 代码都在 https://github.com/ant-design/pro-blocks
