### ISSUE TITLE
🐛[BUG]路由权限存在问题

### ISSUE THREAD

**Issue by wangyongsong** [ant-design/ant-design-pro#8358]
### 🐛 bug 描述
情况1：
[access.ts]如果默认返回空对象，routes里的access会默认拥有权限
情况2：
[access.ts]如果返回{ PermissionsMS: false }, 侧边导航栏第一次渲染会显示出PermissionsMS页面的入口（点击进入显示的是无访问权限页面）

导致结果：无权限的用户也能看到导航栏的入口

### 🏞 期望结果

如果为空对象，应该是没权限才对 

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

以前没出现过这个问题，是最近几天才出现的问题

**Comment by wangyongsong** [comment]
@chenshuai2144 这边方便看一下吗

**Comment by wangyongsong** [comment]
相似问题： [8322](https://github.com/ant-design/ant-design-pro/issues/8322#issue-853093732)

**Comment by laosandegudai** [comment]
路由权限定义和access返回的不匹配默认有权限是咋考虑的？

**Comment by wangyongsong** [comment]
> 路由权限定义和access返回的不匹配默认有权限是咋考虑的？
🤦🏻‍♀️其实也能处理，在access.ts里写一个router递归，获取所有的access默认给个false

**Comment by laosandegudai** [comment]
> > 路由权限定义和access返回的不匹配默认有权限是咋考虑的？
> 
> 其实也能处理，在access.ts里写一个router递归，获取所有的access默认给个false.🤦🏻‍♀️

是可以处理，但是权限这种谨慎的东西默认最大化不知道是否符合常规逻辑。
Ant 牛逼（破音💋）

**Comment by wangyongsong** [comment]
目前处理方法：
```ts
import allRouter from '../config/routes';

export default function access(initialState: { currentUser?: API.CurrentUser | undefined }) {
  const { currentUser }: any = initialState || {};
  const base = {};
  let permissionList = currentUser?.permission || {};

  function getBase(data: any[]) {
    data.forEach((ele: { access: any; routes: any }) => {
      if (ele.access) {
        Object.assign(base, { [ele.access]: false });
      }
      if (ele.routes) {
        getBase(ele.routes);
      }
    });
  }

  getBase(allRouter);

  return {
    ...base,
    ...permissionList,
  };
}

```

**Comment by laosandegudai** [comment]
目前处理办法和你这个差不多，还没尝试权限组件控制按钮那种。😁

**Comment by chenshuai2144** [comment]
一个页面如果默认不能用，为什么不直接全部403呢？

**Comment by laosandegudai** [comment]
> 一个页面如果默认不能用，为什么不直接全部403呢？

所以应该默认无权限。

**Comment by chenshuai2144** [comment]
默认无权限和不登录有什么区别？🌚🌚

Pro的设计思路还是有些页面不能看，而不是有些界面能看

**Comment by laosandegudai** [comment]
> 默认无权限和不登录有什么区别？🌚🌚
> 
> Pro的设计思路还是有些页面不能看，而不是有些界面能看

默认无权限就是等同于不登陆，但是现在是路由的权限定义和access的权限如果不匹配则权限验证是通过的，因为系统里只存了用户拥有的权限，而用户木有的权限是不存储的，现在处理办法就如
https://github.com/ant-design/ant-design-pro/issues/8358#issuecomment-887437792
类似，要把所有权限定义默认false然后再用用户拥有的权限区覆盖。
