### ISSUE TITLE
🧐[问题]如何在页面中嵌入外部链接或者网页

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#8359]
### 🧐 问题描述

使用了iframe标签，但是做不到全屏显示，还有个外边距
不清楚怎么可以弄到全屏

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/12421552/114809294-78346e00-9ddc-11eb-9f92-569b404cb1ef.png)

![image](https://user-images.githubusercontent.com/12421552/114809279-723e8d00-9ddc-11eb-9143-b489354432aa.png)

这是我想要的效果外边距没了，然后页面可以自适应全屏

![image](https://user-images.githubusercontent.com/12421552/114809464-d06b7000-9ddc-11eb-9798-3eb68e640fe9.png)

**Comment by chenshuai2144** [comment]
`margin： -24`

自带的边框你需要人肉覆盖一下
