### ISSUE TITLE
ANTDPRO table 多选 如果是请求的数据，分页就不能保持勾选的数据，官网预览都有这个问题🐛[BUG]

### ISSUE THREAD

**Issue by willdreame** [ant-design/ant-design-pro#8360]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by wangyongsong** [comment]
[详细请参考antd table文档 preserveSelectedRowKeys这个属性](https://ant.design/components/table-cn/)

![image](https://user-images.githubusercontent.com/58172091/114819276-cd2daf80-9def-11eb-80d3-4d4400d758e9.png)

**Comment by willdreame** [comment]
thanks， 当然， 建议更新 antdpro 的官网预览例子，我看了 antdpro  的 官网预览 还有这个问题，我已经用dva 自己存储数组处理，后续再有这个需求会使用这个属性，非常感谢
