### ISSUE TITLE
🐛[BUG] i18n-remove 失效

### ISSUE THREAD

**Issue by wzc0x0** [ant-design/ant-design-pro#8362]
### 🐛 bug 描述
yarn i18n-remove 执行完成并没有改变任何文件

### 📷 复现步骤

yarn  i18n-remove

### 🏞 期望结果

期望正常移除国际化代码

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本: 3.4.0
- 浏览器环境: Chrome89
- 开发环境 mac OS & Windows10

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/11566782/114835193-e50f2e80-9e03-11eb-9b73-7cf1332d26c6.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/115060192-2db90b80-9f1a-11eb-8560-d1e95c8b47df.png)
我这边看是有效的。

**Comment by chenshuai2144** [comment]
兼容性有点差，我最近在 v5 的事情把兼容性搞一搞 @xiaohuoni

最简单的其实是加 locale，删除 locale 总是有各种问题

**Comment by xiaohuoni** [comment]
@chenshuai2144  有没有todoList，不过我现在也用 mac 了。

**Comment by chenshuai2144** [comment]
@xiaohuoni  我搞一个出来

**Comment by dingtianxiu** [comment]
fixed
