### ISSUE TITLE
git commit 不能触发 precommit🐛[BUG]

### ISSUE THREAD

**Issue by niming175** [ant-design/ant-design-pro#8363]
### 🐛 bug 描述
1、修改某个jsx文件，并存在错误；
2、git add 这个文件；
3、git commit -m '...'

但是并不会触发precommit;

以往的版本，在git commit的时候，都会触发代码检查，但是这次新建的项目并没有

### 📷 复现步骤
1、根据官网创建项目`yarn create umi`
2、选择ant-design-pro, v4版本
3、JavaScript语言
4、执行 yarn install
5、创建git 仓库环境， 并提交出现项目
6、修改一个文件（jsx文件）， 并故意改错
7、执行`npm run percommit`， 会有代码检查并报错
8、执行`git commit`并不会触发代码检查和报错

### 🏞 期望结果

像以前那样，能在git commit的时候，触发`precommit`
### © 版本信息

- Ant Design Pro 版本: 4.5.0
- umi 版本 3.4.1
- 浏览器环境
- 开发环境 max os
- node v14.16.1

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26159724/114836770-91054980-9e05-11eb-9287-5dae65d7ed76.png)

![image](https://user-images.githubusercontent.com/26159724/114836871-abd7be00-9e05-11eb-9092-352df9f37cdf.png)

**Comment by chenshuai2144** [comment]
删除一下 .git/hooks 文件夹，然后再安装依赖

**Comment by niming175** [comment]
> 删除一下 .git/hooks 文件夹，然后再安装依赖

可是我的项目的`.git`文件夹在外层
```
myProject/
    - backend/(后端项目)
    - frontend/(ant 前端项目)
    - .git/
```

删除.git/hooks后，在frontend下再次执行`yarn install`并不会再外层的.git文件夹下再次生成hook文件夹, 问题还是没解决

**Comment by chenshuai2144** [comment]
这就难搞了，你估计要自己写 git hooks 了

**Comment by niming175** [comment]
> 这就难搞了，你估计要自己写 git hooks 了

可是我们以往的项目，至少去年12月份创建的项目，都是可以的

**Comment by chenshuai2144** [comment]
看看底层库的更新，或者试试 git clean，额庵后重新安装

**Comment by niming175** [comment]
> 看看底层库的更新，或者试试 git clean，然后重新安装

测试无效的。表示放弃

**Comment by WLyKan** [comment]
最新版的脚手架，钩子也不行了，查看了yorkie的文档
需要在package加入
```
"gitHooks": {
    "pre-commit": "lint-staged"
  },
```
