### ISSUE TITLE
🐛[BUG] 通知界面标签选项未居中

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8366]
### 🐛 bug 描述

https://preview.pro.ant.design 预览也是这样的情况

![QQ浏览器截图20210415183111](https://user-images.githubusercontent.com/3166799/114855790-e8f97b80-9e18-11eb-951b-8caf87a79d64.png)

**Comment by chenshuai2144** [comment]
antd的版本，下个版本会修
