### ISSUE TITLE
构建好项目后打开文件发现都是标红报错的，提示模块无法导出？

### ISSUE THREAD

**Issue by bruce-zhang932** [ant-design/ant-design-pro#8367]
按照文档提示安装好项目之后，打开这些文件发现都是标红报错的，提示模块无法导出？但是项目可以启动起来。
![image](https://user-images.githubusercontent.com/11385973/115000463-5d91f000-9ed5-11eb-9e07-8c933e9b9eca.png)

**Comment by xiaohuoni** [comment]
先执行一次dev
