### ISSUE TITLE
构建时报404

### ISSUE THREAD

**Issue by misome** [ant-design/ant-design-pro#837]
> ant-design-pro@1.0.0 build /home/user/Develop/workspace/antd/ant-design-pro-1.0.0
> cross-env DISABLE_ESLINT=true roadhog build

**404**
Compiled successfully.

能够编译成功，但前面提示一个404，请问是什么原因？

**Comment by chenshuai2144** [comment]
@sorrycc  我也是。。

**Comment by sorrycc** [comment]
新 clone 的 ant-design-pro，并没有重现。

![image](https://user-images.githubusercontent.com/35128/35544367-e60eba30-05a4-11e8-8393-5124abd563ad.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35544568-023dc2a4-05a6-11e8-9483-521b5920b4fc.png)

我这还有。
不过不影响使用

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/35546272-8c1dab30-05ae-11e8-815c-bd2df8833591.png)
昨天还没有，今天就有了。

**Comment by yanka1** [comment]
env 的变量怎样设置，我希望根据环境变量的不同，打包的不同的output文件夹， 命令使用什么呢，roadhog build 总是将命令 设置为production ，cross-env 后设置也不起作用。

**Comment by hqwlkj** [comment]
![image](https://user-images.githubusercontent.com/12181423/35578812-16e8c436-0620-11e8-92d0-4a2cc1bc33c3.png)
我也遇到这个问题了。

**Comment by chenshuai2144** [comment]
不影响使用。
应该是某个底层库更新了。。。。
过几天说不定就没了

**Comment by hqwlkj** [comment]
但愿如此吧 😂

**Comment by sorrycc** [comment]
找到原因了，会尽快修复

**Comment by chenshuai2144** [comment]
@sorrycc  顺便搞一搞 #786 吧

**Comment by sorrycc** [comment]
Fixed.

**Comment by zywcode** [comment]
我这也出404，什么原因呢？要升级roadhog还是dva？

**Comment by zywcode** [comment]
`npm install is-ali-env@0.1.3` 解决了
