### ISSUE TITLE
🧐[问题]V5关于菜单高亮的问题

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#8371]
### 🧐 问题描述
pro layout的版本是6.15.3
遇到一个问题，具体场景是
角色管理中，有个权限分配的页面，进入该页面后，想让菜单的角色管理高亮，查看了文档
https://beta-pro.ant.design/docs/advanced-menu-cn#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%AB%98%E4%BA%AE
说是要设置parentKeys属性，让接口添加了该属性，并且检查了没错，但是还是不会高亮，不知道什么原因？

### 🚑 其他信息
后台返回的结构是这个样子的

![image](https://user-images.githubusercontent.com/5431843/115140040-ca3cf400-a067-11eb-812f-429d1c96e5f4.png)

**Comment by chenshuai2144** [comment]
打全看看 ，权限分配匹配上了吗？

**Comment by ideaviewes** [comment]
@chenshuai2144 ,
权限分配key是 /rbac/role/permission/index，parentKeys是 ['/rbac/role/index'] 它的父级是角色管理
角色管理的key是 /rabc/role/index
根据上面的层级已经是匹配了的，
但是进入权限分配（/rbac/role/permission/index）,这个页面的时候，它的父级角色管理没有高亮

**Comment by chenshuai2144** [comment]
console 一下key试试

path 和key是不一样的，或者是key重复了

**Comment by ideaviewes** [comment]
@chenshuai2144 ,我看了pro layout 的文档
https://procomponents.ant.design/components/layout
关于MenuDataItem 接口，中key的注释
@name 用于标定选中的值，默认是 path 
所以我才把key和path弄成一致
key没有重复的，我把后台返回的json认真看了一遍
这个/rbac/role/permission/index页面，也没有面包屑导航
