### ISSUE TITLE
请问原先版本可以在浏览器加载到src源文件debugger调试的，怎么现在版本没有了？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design-pro#8372]
### 🧐 问题描述
请问原先版本可以在浏览器加载到src源文件debugger调试的，怎么现在版本没有了？
![image](https://user-images.githubusercontent.com/37643958/115152282-19ece100-a0a3-11eb-8cff-f70ca47e6a57.png)

配置里加了devtool:'source-map',也不生效
![image](https://user-images.githubusercontent.com/37643958/115152336-41dc4480-a0a3-11eb-8fcd-c79e2f756f9f.png)

**Comment by chenshuai2144** [comment]
去 umi 问问？
