### ISSUE TITLE
🧐[问题]eslint 报错，编译却能通过

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design-pro#8374]
### 🧐 问题描述

ts 报错，编译却能通过，希望eslint报错时，编译不通过；

期望eslint报错，停止编译，并提醒

### 💻 示例代码

比如，从props 读取一个 未定义的属性值，但是编译却能通过

**Comment by chenshuai2144** [comment]
eslint 和 ts 都只是辅助，不能做成卡点的，你要是想要作为卡点，可以配置 build

build: "tsc --noEmit && npm run eslint && umi build"

**Comment by JaylanChen** [comment]
这个只能单次，不能在开发时提示，比如开发时，但编译成功了，不能提示到开发者。在开发时，热更新期间有好的方式吗？谢谢你

**Comment by chenshuai2144** [comment]
尽量不要打开，会很卡。

https://umijs.org/zh-CN/config#forktschecker

**Comment by JaylanChen** [comment]
好的，谢谢你。打开后确实很卡。
