### ISSUE TITLE
使用ant-design-pro-v4 遇到的问题

### ISSUE THREAD

**Issue by lzb-libra** [ant-design/ant-design-pro#8375]
最近我们公司打算使用ant design pro v4 版本开发一个后台管理页面，但是在修改某些页面的时候遇到了一些无法解决的问题
1、我想修改登陆页面的foot信息, 原始信息是这个样子的
![image](https://user-images.githubusercontent.com/63389341/115220497-3177a880-a13b-11eb-9e81-63cdc09fceef.png)
我需要将 “2019 蚂蚁金服体验技术部出品”和上边的三个链接替换，发现怎么也替换不了，我尝试修改了BasicLayout.ts 文件里的defaultFooterDom 方法。
![image](https://user-images.githubusercontent.com/63389341/115220934-b9f64900-a13b-11eb-8a7f-bdf8ecd11f80.png)
但是当我登陆进去后发现foot信息已经修改
![image](https://user-images.githubusercontent.com/63389341/115221005-ced2dc80-a13b-11eb-853b-30283c55d0e9.png)
请问我想修改登陆界面的foot信息我应该怎么处理
2、我发现登陆页面的按钮名称是“提交”而不是“登录”, 我想修改这个按钮的名称，也是发现怎么都修改不了，
在src -> locales -> zh-CN -> pages.ts 文件里有这个“pages.login.submit”这个k-v属性，我尝试修改这个值为“登录”，登录页面按钮也没有修改为“登录”字符，我重启了项目也不好使。
3、还有一个最关键的问题，官网的文档和我使用“yarn careate uni ***”创建的项目有些出入，文档上有的属性或方法在项目源码里并没有找到，这让我很是疑惑

这两个问题我尝试修改@and-design的源码到时可以解决，有没有不需要修改就可以解决的办法呀。

**Comment by ideaviewes** [comment]
这个很简单，你给footer传links属性就行了

**Comment by lzb-libra** [comment]
这个问题暂时是发生在登录界面，我登录界面的foot除了自定义和修改源码外我没有找到其他的办法，我想知道的是有没有其他的办法可以解决我的问题

**Comment by lzb-libra** [comment]
我尝试修改过links的数据，但是登录界面的无法更改，但是登录进去后是修改后的内容

**Comment by fangqibin** [comment]
查到引用地方修改掉，没有无法更改这一说。

**Comment by lishaoh** [comment]
@lzb-libra 
![image](https://user-images.githubusercontent.com/20917295/115654159-2737f300-a363-11eb-9b12-cf9a29e3ab8f.png)

**Comment by lzb-libra** [comment]
我尝试过修改这里，将defaultCopyright 的值修改为空字符串，但是登陆界面就会只剩下一个©符号，最近又回去看了一下UserLayout的布局代码，发现这个页面是直接用的and-design 里 DefaultFooter, 我以为也是用的basilayout里的 foot，是我没有看仔细，感谢诸位的解答。
