### ISSUE TITLE
🧐[问题]如何根据用户类型显示不同的导航菜单

### ISSUE THREAD

**Issue by blackholll** [ant-design/ant-design-pro#8376]
### 🧐 问题描述

因为权限控制比较简单，不想通过后端接口来获取菜单。 用户登录时会返回用户的类型(超级管理员、管理员、普通用户)。
需要部分菜单只对超级管理员和管理员可见。 config.ts中菜单是写死的，请问该如何实现？
ant design v5

**Comment by blackholll** [comment]
解决了。
修改src/access.ts 和config.ts
![image](https://user-images.githubusercontent.com/6269605/115417591-52b7c200-a22b-11eb-9d2b-ace72d1d6bf3.png)
![image](https://user-images.githubusercontent.com/6269605/115417691-66632880-a22b-11eb-9242-9bd519d43f47.png)

**Comment by heyuuuu** [comment]
> 解决了。
> 修改src/access.ts 和config.ts
> ![image](https://user-images.githubusercontent.com/6269605/115417591-52b7c200-a22b-11eb-9d2b-ace72d1d6bf3.png)
> ![image](https://user-images.githubusercontent.com/6269605/115417691-66632880-a22b-11eb-9242-9bd519d43f47.png)

我擦，为啥我的不行勒

**Comment by blackholll** [comment]
> > 解决了。
> > 修改src/access.ts 和config.ts
> > ![image](https://user-images.githubusercontent.com/6269605/115417591-52b7c200-a22b-11eb-9d2b-ace72d1d6bf3.png)
> > ![image](https://user-images.githubusercontent.com/6269605/115417691-66632880-a22b-11eb-9242-9bd519d43f47.png)
> 
> 我擦，为啥我的不行勒

access.ts中根据你的currentUser的内容需要做适当修改

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn
