### ISSUE TITLE
yarn start:dev  Cannot find module 'webpack/lib/ModuleFilenameHelpers'

### ISSUE THREAD

**Issue by YangYuHub** [ant-design/ant-design-pro#8377]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/63183404/115359886-af968680-a1f1-11eb-8015-908d4e891dce.png)

**Comment by chenshuai2144** [comment]
`yarn add webpack -D`

试试这个

**Comment by chenshuai2144** [comment]
已经修复，重新安装依赖
