### ISSUE TITLE
🐛[BUG]V5在routes.ts里配置了子路由无效，点击菜单，url变了，视图没变，请大佬指点一二

### ISSUE THREAD

**Issue by wending55** [ant-design/ant-design-pro#8381]
### 🐛 bug 描述

routes.ts配置参考示例配置，见下图，配置完之后菜单可以正常展示，但是点击其他子菜单，路由不到目标页面，只是url发生了改变

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/45172661/115380727-736d2100-a205-11eb-885e-bbc1e63c192a.png)

![image](https://user-images.githubusercontent.com/45172661/115380861-95ff3a00-a205-11eb-91e6-a0bee3518a4d.png)
![image](https://user-images.githubusercontent.com/45172661/115380914-a4e5ec80-a205-11eb-860d-ca8cc2d468e8.png)

### 🏞 期望结果

是我哪里配错了吗？视图层不该变

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/115383046-f1cac280-a207-11eb-8afd-e6423e584bfb.png)

有子节点的菜单，配置 compotontens 的时候要注意处理 children

**Comment by nannan0109** [comment]
遇到了同样的问题 请问解决了吗

**Comment by nannan0109** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/115383046-f1cac280-a207-11eb-8afd-e6423e584bfb.png)
> 
> 有子节点的菜单，配置 compotontens 的时候要注意处理 children
> 
> 不知道怎么处理就不要写 compotontens ，用重定向

用了重定向 点击一级菜单 并没有反应
![image](https://user-images.githubusercontent.com/19622284/127113544-bc8c52f3-3970-4391-b99b-c77881ddecbe.png)
