### ISSUE TITLE
🧐[问题] 一个页面拆分多个菜单 传值问题

### ISSUE THREAD

**Issue by xuchunwei123** [ant-design/ant-design-pro#8384]
### 🧐 问题描述

我有一个页面 路由为 /promotion/alltabpage/see-auto-promotion  但是领导说就一个菜单中显得功能太少 要多个菜单 现在就硬是页面中有10个功能就拆10个菜单  用传入不同参数多方式来区分是哪个功能  现在这边实在不知道怎么整了 还有子页面入详情 查看之类的的页面 还要哪个页面进去的 高亮哪个菜单  要怎么整 才行

**Comment by lishaoh** [comment]
通过location获取相应的值，然后render的时候做个switch不行？

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/advanced-menu-cn

看看这里 request 很适合你
