### ISSUE TITLE
🐛[BUG] request 401不走errorHandler

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-pro#8386]
### 🐛 bug 描述

request 添加拦截器之后token过期接口报401不走errorHandler，控制台报错
![image](https://user-images.githubusercontent.com/32634443/115509749-673e9d80-a2b1-11eb-98c4-0ef5d8a1ec72.png)

### 💻 复现代码

![image](https://user-images.githubusercontent.com/32634443/115509778-6f96d880-a2b1-11eb-852c-42d5a9a08715.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
可以截图一下接口response信息

**Comment by firstmetcs** [comment]
> 可以截图一下接口response信息

![image](https://user-images.githubusercontent.com/32634443/115540638-d1b30600-a2d0-11eb-8e3d-f2f4c03f1502.png)
![image](https://user-images.githubusercontent.com/32634443/115540664-d5df2380-a2d0-11eb-99c6-01d9fc19d35f.png)

**Comment by firstmetcs** [comment]
不太懂控制台的这个报错是哪边报出来的，是request吗 @fangqibin

**Comment by chenshuai2144** [comment]
这个错误看起来是 dva 搞得。

**Comment by fangqibin** [comment]
> 不太懂控制台的这个报错是哪边报出来的，是request吗 @fangqibin

用try catch 尝试捕获一下错误看看，这样比较难看出来是什么问题。

**Comment by firstmetcs** [comment]
> > 不太懂控制台的这个报错是哪边报出来的，是request吗 @fangqibin
> 
> 用try catch 尝试捕获一下错误看看，这样比较难看出来是什么问题。

在service里catch不到，我参照网上的帖子创建了app.tsx并且写了以下代码：
![image](https://user-images.githubusercontent.com/32634443/115677312-f071d500-a382-11eb-9012-dc53473d0887.png)

然后这里是控制台的输出
![image](https://user-images.githubusercontent.com/32634443/115677361-fbc50080-a382-11eb-95d4-4c43f11f6aa9.png)


在model层try catch之后得到的结果如下：
![image](https://user-images.githubusercontent.com/32634443/115677972-99b8cb00-a383-11eb-93c8-9759aed2ba9b.png)
![image](https://user-images.githubusercontent.com/32634443/115677998-9f161580-a383-11eb-9b8a-cd0fe5c7246d.png)


按理来说dva 401也应该把这个错误抛到request里吧。但是如果401的时候刷新页面SecurityLayout里的current-user请求也会报401，这个请求就会正常走errorHandler

**Comment by firstmetcs** [comment]
断点只能走到第一个，然后应该是dva报错，以后的断点就走不到了

![image](https://user-images.githubusercontent.com/32634443/115682989-91af5a00-a388-11eb-9b10-e38619353c46.png)

@fangqibin

**Comment by fangqibin** [comment]
> 断点只能走到第一个，然后应该是dva报错，以后的断点就走不到了
> 
> ![image](https://user-images.githubusercontent.com/32634443/115682989-91af5a00-a388-11eb-9b10-e38619353c46.png)
> 
> @fangqibin

errorHandler这个里面的error可以log出来吗

**Comment by firstmetcs** [comment]
> > 断点只能走到第一个，然后应该是dva报错，以后的断点就走不到了
> > ![image](https://user-images.githubusercontent.com/32634443/115682989-91af5a00-a388-11eb-9b10-e38619353c46.png)
> > @fangqibin
> 
> errorHandler这个里面的error可以log出来吗

这个log都出不来
![image](https://user-images.githubusercontent.com/32634443/115694871-d8ef1800-a393-11eb-971c-41e870317f1d.png)


是因为我加了拦截器吗

![image](https://user-images.githubusercontent.com/32634443/115694937-ec01e800-a393-11eb-9538-1244aecd3d61.png)

@fangqibin

**Comment by fangqibin** [comment]
> > > 断点只能走到第一个，然后应该是dva报错，以后的断点就走不到了
> > > ![image](https://user-images.githubusercontent.com/32634443/115682989-91af5a00-a388-11eb-9b10-e38619353c46.png)
> > > @fangqibin
> > 
> > 
> > errorHandler这个里面的error可以log出来吗
> 
> 这个log都出不来
> ![image](https://user-images.githubusercontent.com/32634443/115694871-d8ef1800-a393-11eb-971c-41e870317f1d.png)
> 
> 是因为我加了拦截器吗
> 
> ![image](https://user-images.githubusercontent.com/32634443/115694937-ec01e800-a393-11eb-9538-1244aecd3d61.png)
> 
> @fangqibin

request.interceptors.response.use 这个也试试能不能拦截的到。

**Comment by firstmetcs** [comment]
![image](https://user-images.githubusercontent.com/32634443/115954089-98bda000-a521-11eb-9600-95092f7efa43.png)
这种方式是可以拦截的，但是控制台还是会报错，这个报错导致我页面再发同样的请求会发不出去

![image](https://user-images.githubusercontent.com/32634443/115954104-b5f26e80-a521-11eb-94f8-48f00e71b524.png)

**Comment by firstmetcs** [comment]
请求报错的页面会处于假死状态，刷新点菜单刷新路由也没有用，必须F5刷新浏览器才可以  @fangqibin

**Comment by firstmetcs** [comment]
我刚刚创建了个新项目，但是还是存在这个问题，我甚至连拦截器都没有添加

**Comment by firstmetcs** [comment]
但是很奇怪，遇到这种情况刷新一下页面current-user的请求401的时候就能正确被拦截

**Comment by chenshuai2144** [comment]
dva 配置一下 onError 吧，我觉得是因为 dva 没用的 use-request 导致的

**Comment by fangqibin** [comment]
> 请求报错的页面会处于假死状态，刷新点菜单刷新路由也没有用，必须F5刷新浏览器才可以 @fangqibin

我request用的是ahook，一直很正常，你也可以试试。

**Comment by chenshuai2144** [comment]
不要用 ahooks，用从 umi 中导出的 request，不然就没法走 app.tsx 的报错

**Comment by fangqibin** [comment]
> 不要用 ahooks，用从 umi 中导出的 request，不然就没法走 app.tsx 的报错

我是自己写了一个request文件，没有用app.tsx里面的，之前的版本就用这个，所以没有换，到现在还没有发现什么问题

**Comment by firstmetcs** [comment]
> dva 配置一下 onError 吧，我觉得是因为 dva 没用的 use-request 导致的

加了onError还是不能errorHandler拦截，不过不会卡死请求了 @chenshuai2144

**Comment by Swallower** [comment]
那个  httperror 怎么去除掉  我想要再.catch(err=>{})中拿到接口在状态码非200到300 时的 返回信息  但这时err输出后为 httperror
