### ISSUE TITLE
🧐[问题] v4怎么控制菜单和主页面的渲染顺序？

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-pro#8388]
### 🧐 问题描述

我将BasicLayout中的菜单改为从后台动态获取，由于加载需要一定的时间导致getMatchMenu没有刷新，因此页面F5进入页面时先加载了ProLayout的children，因此获取不到对应的权限导致页面403，请问怎么在获取菜单之后再将ProLayout的children刷新一下？

### 💻 示例代码

获取菜单：
![image](https://user-images.githubusercontent.com/32634443/115561843-873d8380-a2e8-11eb-9ce9-264d57b37fa0.png)

获取菜单权限修改为：
![image](https://user-images.githubusercontent.com/32634443/115561914-945a7280-a2e8-11eb-8605-15c9f9748264.png)

ProLayout的权限校验：
![image](https://user-images.githubusercontent.com/32634443/115561960-9fad9e00-a2e8-11eb-9927-9b9360b3670c.png)

### 🚑 其他信息

v4版本的antd pro

**Comment by chenshuai2144** [comment]
定义一个loading，然后 
`
{!loading && children}`

**Comment by firstmetcs** [comment]
> 定义一个loading，然后
> ` {!loading && children}`

我用了这个方法，但是似乎还是不生效，因为menuRef没刷新导致的。后来我改了4.2.1的utils，通过我修改的这种方法似乎可以解决权限问题。

BasicLayout的更改
![image](https://user-images.githubusercontent.com/32634443/115674662-77717e00-a380-11eb-8429-33426fe17138.png)

utils的修改
![image](https://user-images.githubusercontent.com/32634443/115674735-8c4e1180-a380-11eb-9f68-865f45550609.png)

CheckPermission的修改
![image](https://user-images.githubusercontent.com/32634443/115674810-9d971e00-a380-11eb-9a47-f9b87702b34c.png)

这样似乎是可以的，不过必须后台配置/和/welcome的权限。
@chenshuai2144
