### ISSUE TITLE
🐛[BUG]yarn run build 报错  本地可以

### ISSUE THREAD

**Issue by zhj778930960** [ant-design/ant-design-pro#8389]
### 🐛 bug 描述

yarn run build 报错
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0-beta]
- umi 版本 3.4.0
- 浏览器环境 
- 开发环境 [e.g. mac OS]  windows
- 部署环境 centuos
- Node 本地为14.7.0  部署环境为15.14.0

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23496206/115672821-835c4080-a37e-11eb-88ba-4252f12c159a.png)

系统： CentuOS

**Comment by zhj778930960** [comment]
有没有大老知道什么情况啊

**Comment by chenshuai2144** [comment]
linux 是大小写敏感的，检查一下你的大小写

**Comment by zhj778930960** [comment]
> 大小

没明白 是检查哪里的大小写？？

**Comment by zhj778930960** [comment]
> linux 是大小写敏感的，检查一下你的大小写

是路由配置这里的吗？？
![image](https://user-images.githubusercontent.com/23496206/115676440-2e222e00-a382-11eb-8bcf-d61099905213.png)

我想我应该明白了
