### ISSUE TITLE
是否有便捷方法只支持内容滚动查看内容？

### ISSUE THREAD

**Issue by DuduStyle** [ant-design/ant-design-pro#839]
目前基础布局为全部滚动查看，在不大改动的前提下，是否有便捷方法菜单栏和顶部固定，内容区滚动查看；

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/c2d197989ae92c46565cf28266628a48f740ef3c/src/components/GlobalHeader/index.less#L12

改成height:100vh;

**Comment by DuduStyle** [comment]
谢谢

**Comment by DuduStyle** [comment]
修改完后右边会出现两个滚动条，并且，globalFooter会出现错位现象
![qq 20180201145056](https://user-images.githubusercontent.com/31200868/35665045-63e0a336-075f-11e8-9dff-04a79a7ee920.png)
