### ISSUE TITLE
🐛[BUG]V5 发网络请求404 不触发errorHandler 

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8390]
### 🐛 bug 描述

发404的网络请求，只能看到控制台有异常
![image](https://user-images.githubusercontent.com/70048681/115689095-56b02500-a38e-11eb-9748-44a960c41d56.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 569202812** [comment]
proxy怎么写的

**Comment by ludonghai715** [comment]
the same problem .  only trigged when login action return 4xx error。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/118486169-dfcb3980-b74b-11eb-8569-038e488d78ad.png)



看看 x-real-url 是什么，然后检查一下是不是真的可以连通
