### ISSUE TITLE
部署之后 404

### ISSUE THREAD

**Issue by YangYuHub** [ant-design/ant-design-pro#8391]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/63183404/115689107-59127f00-a38e-11eb-91ac-a44ec26179f0.png)

config.ts 

` manifest: {
    basePath: '/',
  },
  publicPath: '/',
  base: '/',
  hash: true,`

**Comment by YangYuHub** [comment]
页面可以正常访问  手动刷新页面 出现此情况

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/docs/deploy-cn#%E9%83%A8%E7%BD%B2

看看这个
