### ISSUE TITLE
V5 安装umi-plugin-antd-theme 动态更新主题，但每次编译都特别慢？🧐[问题]

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#8392]

**Comment by chenshuai2144** [comment]
就是这么慢的，因为要去编译一遍less，还不并行

**Comment by GloriaCHL** [comment]
@chenshuai2144 请问怎么关掉？我希望是能有个可以控制插件打开/关闭的地方，在dev模式下调试好后就把它设置为只有production下执行，如果能这样实现就好了。不过看文档里讲是umi@3安装了这插件后就会自动调用它执行....
文档：https://pro.ant.design/docs/dynamic-theme-cn

**Comment by chenshuai2144** [comment]
你可以删除掉，然后 build的时候装回来

**Comment by GloriaCHL** [comment]
好吧，目前没有其他好的方案的话，也只能这样了。谢谢回答
