### ISSUE TITLE
🧐[问题]有没有 ant-design-pro框架的详细说明文档

### ISSUE THREAD

**Issue by lzb-libra** [ant-design/ant-design-pro#8393]
请问哪里有 ant-design-pro 框架的详细说明文档，特别是框架里封装的一些组件，组件里的某些属性都不知道是什么意思，也没有说明，全靠猜或者跟代码，初学者特别浪费精力和时间，网上教学视频比较滞后，跟着看下去看着看着就不对了。这个项目 真心缺少一个详细说明文档

**Comment by chenshuai2144** [comment]
详细说明文档 你希望了解什么，最好具体一点这样别人才能给解答

**Comment by lzb-libra** [comment]
我举个列子，src > pages > User > index.tsx 文件，在渲染登陆页面表单的ProFormText，点进去后就这个样子
![image](https://user-images.githubusercontent.com/63389341/115809670-206eb600-a41f-11eb-9e2a-64b9cd7de50d.png)
有的属性名字取得可以见名知意，但是有的就不知道是什么意思，干什么的。当然这只是举个例子。

**Comment by lishaoh** [comment]
对应的插件都有相应的文档说明属性啊
https://procomponents.ant.design/components/field-set#proformtext

**Comment by chenshuai2144** [comment]
写了一个 方便入门的时候使用

https://www.yuque.com/chenshuai/web/bqnph6

**Comment by lzb-libra** [comment]
@lishaoh @chenshuai2144  非常感谢，https://procomponents.ant.design/components/field-set#proformtext这个地址我当时是真的没有找到
