### ISSUE TITLE
 Unexpected token 'export' 

### ISSUE THREAD

**Issue by YangYuHub** [ant-design/ant-design-pro#8394]
### 🧐 问题描述

yarn create umi myapp

yarn start 

![image](https://user-images.githubusercontent.com/63183404/115808882-b30e5580-a41d-11eb-9a78-74b475e80d23.png)

**Comment by chenshuai2144** [comment]
https://github.com/mhchem/mhchemParser


这个库更新导致的，作者正在修

**Comment by hfpp2012** [comment]
快点修复吧，谢谢

**Comment by chenshuai2144** [comment]
修好了

**Comment by YangYuHub** [comment]
> 修好了

看到了 谢谢
