### ISSUE TITLE
👑 [需求]希望在创建项目的时候可以提供是否使用swagger的选项

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design-pro#8395]
### 🥰 需求描述

有时候并不需要swagger

### 🧐 解决方案

在创建项目的时候可以像选择ant design pro版本那样选择是否使用openapi、swagger

**Comment by chenshuai2144** [comment]
好想法

**Comment by chenshuai2144** [comment]
手动关闭一下吧，暂时没有好的方式
