### ISSUE TITLE
🧐[SSO回调平台后，如何以及在哪个文件获取到回调的ticket信息]

### ISSUE THREAD

**Issue by seeyouxiyou** [ant-design/ant-design-pro#8396]
能否在如图代码中获取到sso回调平台的ticket信息
回调链接示例：*****?ticket=******
![image](https://user-images.githubusercontent.com/33566223/115826014-da284f80-a43c-11eb-8dd5-9c36b6732a97.png)

**Comment by chenshuai2144** [comment]
在页面的props里面拿

**Comment by seeyouxiyou** [comment]
> 在页面的props里面拿

每次请求平台的入口都是app.tsx，如果在页面的props里面拿ticket，如何在app.tsx中做sso的校验？

**Comment by seeyouxiyou** [comment]
但是每次请求平台的入口都是app.tsx，如果在页面的props里面拿ticket，如何在app.tsx中统一做sso的校验？















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[SSO回调平台后，如何以及在哪个文件获取到回调的ticket信息] (#8396)





 
在页面的props里面拿

**Comment by seeyouxiyou** [comment]
可是每次请求平台的入口都是app.tsx，如果在页面的props里面拿ticket，如何在app.tsx中统一做sso的校验？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[SSO回调平台后，如何以及在哪个文件获取到回调的ticket信息] (#8396)





 
在页面的props里面拿

**Comment by chenshuai2144** [comment]
那只能在 window.location了，
我理解授权应该是一次性，回来之后你要换成自己的授权方式的。你应该有个页面承接，拿到之后存到一个全局的地方，换取自己业务的 token，然后存到缓存中，每次发请求的时候触发

**Comment by seeyouxiyou** [comment]
> 那只能在 window.location了，
> 我理解授权应该是一次性，回来之后你要换成自己的授权方式的。你应该有个页面承接，拿到之后存到一个全局的地方，换取自己业务的 token，然后存到缓存中，每次发请求的时候触发

多谢！

**Comment by pifuant** [comment]
@seeyouxiyou  你怎么做的， 可以给个demo 代码不？
