### ISSUE TITLE
🧐[问题] ProTable 自定义的filterdropdown ，使用setSelectedKey 更新filters ，fillter弹框不会自动关闭

### ISSUE THREAD

**Issue by Julywj** [ant-design/ant-design-pro#8397]
ProTable 中columns 自定义的filterdropdown 做filter，使用setSelectedKeys 更新filters数据，但是filter的弹框却不会自动关闭，需要手动点击空白处。

```
var cols = [
{
dataIndex: "testTime",
title: "Test Time",
dataType: "dateTime",
filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }: any) => {
                
                return (
                  <div>
                    <RangePicker value={selectedKeys} onChange={setSelectedKeys} />
                    <div>
                      <Button type="link" size="small" onClick={clearFilters}>
                        {formatMessage({ id: "reset" })}
                      </Button>
                      <Button type="primary" size="small" onClick={confirm}>
                        {formatMessage({ id: "confirm" })}
                      </Button>
                    </div>

                  </div>
                )
              },
              filterIcon: () => <SearchOutlined />
}
]

<ProTable request={getList} columns={cols} />


```

**Comment by chenshuai2144** [comment]
竟然能生效，不应该生效的。
你应该用 filedProps

**Comment by Julywj** [comment]
> 竟然能生效，不应该生效的。
> 你应该用 filedProps

官网给的例子就是这么用的呢。https://procomponents.ant.design/components/table#datasource
而且我试了fieldProps，并没有生效，不知道是不是我写的不对呢；
var cols = [
{
dataIndex: "testTime",
title: "Test Time",
dataType: "dateTime",
fieldProps: {
filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }: any) => {
                
                return (
                  <div>
                    <RangePicker value={selectedKeys} onChange={setSelectedKeys} />
                    <div>
                      <Button type="link" size="small" onClick={clearFilters}>
                        {formatMessage({ id: "reset" })}
                      </Button>
                      <Button type="primary" size="small" onClick={() => confirm({ closeDropdown: true })}>
                        {formatMessage({ id: "confirm" })}
                      </Button>
                    </div>

                  </div>
                )
              },
              filterIcon: () => <SearchOutlined />
},
}
]

<ProTable request={getList} columns={cols} />


**ps**: 问题我是解决了：onClick={() => confirm({ closeDropdown: true })}， 加个dropdown： true；哈哈
