### ISSUE TITLE
🐛[BUG]IE11 有的版本正常，有的版本打不开BaiscLayout

### ISSUE THREAD

**Issue by gugu-lee** [ant-design/ant-design-pro#8398]
<img width="720" alt="截屏2021-04-24 上午8 56 35" src="https://user-images.githubusercontent.com/6067910/115942094-098d9980-a4db-11eb-987f-279c2695da6e.png">
### 🐛 bug 描述

在UserLayout.jsx的useEffect函数中，不能使用setXXX设置state.
在IE11 11.0.9600.16384中会导致页面空白，而在IE11 11.0.9600.19000系列版本中，正常。

BasicLayout.jsx，同样IE11 11.0.9600.16384中空白页面，还较高的版本中正常。调试半天怀疑加装菜单时的问题，但实在不能最终确定

浏览器错误信息：
Warning: [app.unmodel] subscription should return unlistener function, check these subscriptions setup

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi  3.2.19
- 浏览器环境 11.0.9600.16384 ，IE11 11.0.9600.19000
- 开发环境  mac OS

**Comment by gugu-lee** [comment]
刚下载了新模板，启动后也不行。

**Comment by gugu-lee** [comment]
花了我整整两天的时间，把prolayout的源代码移动项目调试，解决了部分问题。
1、UserLayout的useEffect函数中不能有setXXX设置state的调用。否而会有登录页不显示的情况，原因未知。
2、prolayout源码中BasicLayout中useDeepCompareEffect函数中内容要注释掉。这会导致菜单显示时不流畅。
3、低版本的IE11不支持ArrayBuffer的isView方法，要把router-utils,fast-deep-equals引入，把fast-deep-equals中相关的代码删 掉。
这样基本可以登录并能正常了。
但还有一个问题，退出时会有空白页，先不管了。

**Comment by chenshuai2144** [comment]
兼容 ie 是个可怕的工程呀，ie11 还特别卡

**Comment by gugu-lee** [comment]
> 兼容 ie 是个可怕的工程呀，ie11 还特别卡

没办法，客户的环境就是这样的。
这次快到结尾了才发现不同IE11小版本，也会有差别。
