### ISSUE TITLE
roadhog-api-doc 似乎无法工作

### ISSUE THREAD

**Issue by liumin1128** [ant-design/ant-design-pro#84]
如题，mock生成api文档实在是太棒了，希望能早点使用，非常感谢。

操作步骤：

1. npm install roadhog-api-doc -g
2. cd dva(roadhog) project
3. roadhog-api-doc start 8000

结果：
![image](https://user-images.githubusercontent.com/12379461/32318720-10e4a9dc-bf86-11e7-9081-3ccd4884adc3.png)
尝试过手动安装依赖，但package.json中没有依赖项，不知道怎么办了。

**Comment by nikogu** [comment]
@liumin1128 你的项目开源了没，方便发一下地址吗，我直接 clone 下来调一下

**Comment by nikogu** [comment]
`roadhog-api-doc` 本身是没有依赖的，都是依赖于当前 dva 项目的依赖，请先确定已经 `npm install` 所有项目依赖

**Comment by liumin1128** [comment]
好的，我重新fork了，安装好依赖，项目正常运行。
![image](https://user-images.githubusercontent.com/12379461/32321083-f0410e70-bf8d-11e7-8eb2-c0e95fac8a65.png)
接着运行roadhog-api-doc start 8001（当前接口），出现以下错误
![image](https://user-images.githubusercontent.com/12379461/32321114-101f4eb4-bf8e-11e7-80ff-fa6cacc7ab36.png)
我在package.json中加入命令
```
"doc": "roadhog-api-doc start 8001"
``` 
运行 yarn doc
![image](https://user-images.githubusercontent.com/12379461/32321220-6e206980-bf8e-11e7-836a-e8721f71ec86.png)

会不会是因为我用的yarn安装依赖，导致找不到？

**Comment by nikogu** [comment]
@liumin1128 你试试全局安装这个工具呢

```bash
$ npm install roadhog-api-doc -g
$ cd yourproject
$ roadhog-api-doc start 8000
```

因为写在 `script` 里面失效的问题还没解决~ 我去提个 issue：https://github.com/nikogu/roadhog-api-doc/issues/4

**Comment by liumin1128** [comment]
有全局安装的
![image](https://user-images.githubusercontent.com/12379461/32321486-4a9b12de-bf8f-11e7-81e3-8e74ba4822fd.png)

**Comment by nikogu** [comment]
好的，我看看

**Comment by liumin1128** [comment]
是不是全局安装了要卸载项目中的

**Comment by nikogu** [comment]
> 是不是全局安装了要卸载项目中的

这个应该不影响，我调调哈

**Comment by nikogu** [comment]
@liumin1128 重新安装下 `0.2.1` 版本，应该修复了，确实有个 `roadhog` 的命令写成读取全局的了，所以报错了

**Comment by liumin1128** [comment]
抱歉，我装了0.2.1，roadhog有了，但开始报babel找不到...
![image](https://user-images.githubusercontent.com/12379461/32323710-f1f7ac98-bf96-11e7-8f65-6b9b1d87470c.png)

**Comment by nikogu** [comment]
额，我再看看~

**Comment by nikogu** [comment]
@liumin1128 这是是 `roadhog` 项目才能都用，看情况是你的项目里面没有 `babel` 的依赖。

**Comment by kevin24067** [comment]
我 用户 roadhog-api-doc 跑 ant-design-pro 也报相同的错误

**Comment by nikogu** [comment]
@kevin24067 Windows 吗？ @liumin1128 解决了没

**Comment by liumin1128** [comment]
mac，问题仍在

**Comment by nikogu** [comment]
@liumin1128 你 cd 到临时目录 `_roadhog-api-doc` 中，直接 `npm start` 可以吗，可能跟 `yarn ` 有关

**Comment by kevin24067** [comment]
@nikogu  我的mac ，直接roadhog-api-doc start 8000 报错，但是build后 dist的api.html是好的

**Comment by huyong36** [comment]
同样的问题，请问有解决办法吗？

**Comment by nikogu** [comment]
@kevin24067 报错信息贴一下

@huyong36 有办法解决啊！你也是 `babel` 的问题吗

**Comment by huyong36** [comment]
@nikogu 是的，multi ../node_modules/react-dev-utils/webpackHotDevClient.js ./src/api.js
Module not found: Can't resolve 'babel' in '/Users/zhiyong/demo/ant-design-pro-master/ant-design-pro-master/_roadhog-api-doc'
进_roadhog-api-doc运行npm start也是一样。

**Comment by nikogu** [comment]
@huyong36 你的项目依赖是用的 npm 安装的依赖还是 yarn，有用 cnpm 吗

**Comment by huyong36** [comment]
@nikogu npm安装的依赖，没有使用cnpm

**Comment by nikogu** [comment]
@huyong36 npm 版本呢，你用 [cnpm](https://npm.taobao.org/) 试试，npm 安装不慢吗。。。

**Comment by huyong36** [comment]
@nikogu npm 5.4.2  安装挺快的哇。。安装的doc版本是0.2.11,要卸载掉原来安装的roadhog-api-doc吗？

**Comment by nikogu** [comment]
@huyong36 不不不，是项目依赖

**Comment by huyong36** [comment]
@nikogu 代码重新用cnpm安装了一遍依赖再运行就可以了。。。这是为啥

**Comment by nikogu** [comment]
@huyong36 可能是推广大家使用 cnpm 吧...我研究研究

**Comment by afc163** [comment]
cnpm 和 npm 的模块路径不完全一样，@nikogu 用 npm 调试一下。

**Comment by nikogu** [comment]
> cnpm 和 npm 的模块路径不完全一样，@nikogu 用 npm 调试一下。

刚刚用 npm 5.3.0 也成功跑了起来..好奇怪，我再看看，我还没重现过

**Comment by afc163** [comment]
那只能指望 @liumin1128 @huyong36 @kevin24067 帮助排查了。

**Comment by huyong36** [comment]
刚才又试了几次，npm安装运行确实不行，cnpm没有问题，对比了一下cnpm的babel-preset
6.18.0，npm的是6.24.1  不太清楚问题点。。。

**Comment by afc163** [comment]
https://travis-ci.org/ant-design/ant-design-pro/jobs/305889082

**Comment by Bobcui001** [comment]
我也遇到问题。
环境: node(8.9.1)/npm(5.5.1)/ant-design-pro(最新版)/roadhog-api-doc(^0.2.11)
package.json详情如下:
```
{
  "name": "ant-design-pro",
  "version": "0.3.0",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "roadhog server",
    "start:no-proxy": "cross-env NO_PROXY=true roadhog server",
    "build": "roadhog build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "roadhog build --analyze",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "jest",
    "test:all": "node ./tests/run-tests.js"
  },
  "dependencies": {
    "antd": "^3.0.0-beta.1",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.9.2",
    "classnames": "^2.2.5",
    "core-js": "^2.5.1",
    "dva": "^2.1.0",
    "g-cloud": "^1.0.2-beta",
    "g2": "^2.3.13",
    "g2-plugin-slider": "^1.2.1",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.4.1",
    "lodash.clonedeep": "^4.5.0",
    "moment": "^2.19.1",
    "numeral": "^2.0.6",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "react": "^16.0.0",
    "react-container-query": "^0.9.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.0.0",
    "react-fittext": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^8.0.1",
    "babel-jest": "^21.0.0",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.2.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "eslint": "^4.8.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^6.0.0",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.0.1",
    "gh-pages": "^1.0.0",
    "husky": "^0.14.3",
    "jest": "^21.0.1",
    "lint-staged": "^4.3.0",
    "mockjs": "^1.0.1-beta3",
    "pro-download": "^1.0.0",
    "react-test-renderer": "^16.0.0",
    "redbox-react": "^1.3.2",
    "roadhog": "^1.3.1",
    "roadhog-api-doc": "^0.2.11",
    "rollbar-browser": "^1.9.5",
    "stylelint": "^8.1.0",
    "stylelint-config-standard": "^17.0.0"
  },
  "optionalDependencies": {
    "nightmare": "^2.10.0"
  },
  "babel": {
    "presets": [
      "env",
      "react"
    ],
    "plugins": [
      "transform-decorators-legacy",
      "transform-class-properties"
    ]
  },
  "jest": {
    "setupFiles": [
      "<rootDir>/tests/setupTests.js"
    ],
    "testMatch": [
      "**/?(*.)(spec|test|e2e).js?(x)"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/tests/jasmine.js",
    "moduleFileExtensions": [
      "js",
      "jsx"
    ],
    "moduleNameMapper": {
      "\\.(css|less)$": "<rootDir>/tests/styleMock.js"
    }
  },
  "lint-staged": {
    "**/*.{js,jsx}": "lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}

```
求解。。
