### ISSUE TITLE
关于antDesignPro各种模板页面的使用场景

### ISSUE THREAD

**Issue by miccuci** [ant-design/ant-design-pro#840]
最近公司准备使用antDesignPro重构项目，想根据antdpro提供的模板页面提炼出统一的页面使用场景，但是对一些页面的使用存在一些分歧，比如列表页面的编辑部分，请问是应该把编辑放到弹出框modal里还是放到详情页，在查看详情的时候也可进行修改呢？或者是否可以在文档中对各个模板页面的使用场景做个说明呢？

**Comment by doterme** [comment]
antd pro只是一个脚手架，怎么做看你的需求啊

**Comment by pkaq** [comment]
这还是的结合你自己的业务场景去做设计吧 招个产品和UI吧

**Comment by Lyndon001** [comment]
相关设计文档，内部整理中。也希望大家把页面使用的困扰发出来，以便我们进行吸收和整理。

**Comment by afc163** [comment]
> 请问是应该把编辑放到弹出框modal里还是放到详情页

一般来说，如果你希望编辑是一个独立页面（有独立地址的，可以分享给其他人的），就用详情页。
