### ISSUE TITLE
🧐[问题] 如何改变antDesignPro滚动条的宽度？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#8400]
# 如何改变antDesignPro滚动条的宽度？

[例如procomponents的文档就是窄滚动条](https://procomponents.ant.design/components/modal-form#drawer-%E8%A1%A8%E5%8D%95)

所以我在想，antDesignPro是否也可以改成窄滚动条？
* 但是不知道怎么做？ 
* 改变后，会不会影响到antDesign其他组件滚动轴的现实呢？

下面是两个滚动条大小的图片
![a](https://user-images.githubusercontent.com/34436863/115980835-51d3b700-a5c2-11eb-81ef-7f327448c9aa.png)
![b](https://user-images.githubusercontent.com/34436863/115980840-55673e00-a5c2-11eb-8d71-5d6d088224e3.png)

**Comment by fangqibin** [comment]
可以用::-webkit-scrollbar样式修改

**Comment by chenshuai2144** [comment]
自己用 css 硬写吧，千人前面，不一定大家都喜欢
