### ISSUE TITLE
V5版本的，ModalForm怎么设置冒号？

### ISSUE THREAD

**Issue by maytake** [ant-design/ant-design-pro#8401]
![image](https://user-images.githubusercontent.com/13763352/115983687-45a52500-a5d5-11eb-8da3-6b802e06d6c7.png)

**Comment by chenshuai2144** [comment]
colon | 配置 Form.Item 的 colon 的默认值。表示是否显示 label 后面的冒号 (只有在属性 layout 为 horizontal 时有效) | boolean | true
-- | -- | -- | --





layout 属性也要配置

**Comment by maytake** [comment]
![image](https://user-images.githubusercontent.com/13763352/116015758-0f1ae900-a66d-11eb-8920-bb69116cd9f0.png)
可以了，真棒
