### ISSUE TITLE
此处为什么setTimeout呢？

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#8403]
https://github.com/ant-design/ant-design-pro/blob/c0007cd63507b7db7aa367bd1669d90f83c2f849/src/pages/user/Login/index.tsx#L35-L39

**Comment by chenshuai2144** [comment]
来个 pr?

**Comment by Lind-pro** [comment]
想了解一下，为什么是这样写的。

**Comment by lishaoh** [comment]
@Lind-pro 我是这样理解的

![image](https://user-images.githubusercontent.com/20917295/115989750-747dc400-a5f2-11eb-8fe8-58b27293ee51.png)

**Comment by Lind-pro** [comment]
> @Lind-pro 我是这样理解的
> 
> ![image](https://user-images.githubusercontent.com/20917295/115989750-747dc400-a5f2-11eb-8fe8-58b27293ee51.png)

是你说的这么回事。但是用setTimeou t会不会容易出错，假如电脑配置差，卡了一下，那这个参数10会不会出问题。

**Comment by chenshuai2144** [comment]
应该从框架上解决了，给 setInitialValue  加个await 是不是会好点

**Comment by lishaoh** [comment]
感觉可以加个await，goto方法里面也就不需要setTimeout

**Comment by Lind-pro** [comment]
能加的话，那应该是非常好的处理方案了。
