### ISSUE TITLE
🧐[问题] 项目创建好后编译失败

### ISSUE THREAD

**Issue by JaynLau** [ant-design/ant-design-pro#8405]
### 🧐 问题描述

项目创建好后执行 `npm start` 编译失败，奇怪的地方是在我 AMD 的台式机上可以执行成功，在我笔记本上一直失败，所有的操作流程都一样。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1670721/115992265-579bbd80-a5ff-11eb-8467-7bef88227831.png)

**Comment by chenshuai2144** [comment]
看起来是 node 版本的问题

**Comment by JaynLau** [comment]
node 版本是14.16.1，台式机上的版本也是一样的，在笔记本上怎么都不成功，台式机我用 16.0.0 测试都可以

**Comment by chenshuai2144** [comment]
删除一下全局的 umi，`git clean -dfx` 再重新安装。
能解决大部分疑难杂症
