### ISSUE TITLE
🐛[BUG]V5 版本，修改热更新后，loading一直不会消失

### ISSUE THREAD

**Issue by maytake** [ant-design/ant-design-pro#8406]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/13763352/116018516-c5360100-a674-11eb-8e78-7174756d0928.png)

### 🏞 期望结果

修改完代码后，热更新后loading不会一直在

**Comment by chenshuai2144** [comment]
` fastRefresh: {},`

先把这个删掉，组件库很多还没适配，会有一些问题
