### ISSUE TITLE
🧐[使用ProForm.Item时提示 Property 'Item' does not exist on type 'typeof ProForm']

### ISSUE THREAD

**Issue by kaiwisdom** [ant-design/ant-design-pro#8408]
### 🧐 问题描述

使用ProForm.Item时提示 Property 'Item' does not exist on type 'typeof ProForm'

### 💻 示例代码
使用的[官网文档代码](https://procomponents.ant.design/components/form)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/5063064/116022335-94f26080-a67c-11eb-93e2-3ce45a0c4723.png)

**Comment by chenshuai2144** [comment]
这个是新版本才加的，更新下你的依赖把
