### ISSUE TITLE
想在 Table columns 里面配置 对象的子对象的显示，不知道有没有招？

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8409]
各位老师，我直接上图：
![image](https://user-images.githubusercontent.com/32530210/116024312-86a64380-a680-11eb-9944-158a17c2023b.png)

列里面这样，没有效果：
![image](https://user-images.githubusercontent.com/32530210/116024382-a89fc600-a680-11eb-8f4c-721dcf01fa53.png)

还请老师们，指点下下,有没有别的高级办法，谢谢了！

**Comment by fangqibin** [comment]
用数组['hcmPlant', 'plantCode']试试

**Comment by xyzabc0004** [comment]
太厉害了! 有效果. 谢谢, 谢谢 ! @fangqibin

那如果子对象里面还有子.是不是数组的形式,再到后面加?
['hcmPlant', 'plantCode','childattr3']

**Comment by fangqibin** [comment]
> 太厉害了! 有效果. 谢谢, 谢谢 ! @fangqibin
> 
> 那如果子对象里面还有子.是不是数组的形式,再到后面加?
> ['hcmPlant', 'plantCode','childattr3']

是这样子，文档有写

**Comment by xyzabc0004** [comment]
谢谢，谢谢！
