### ISSUE TITLE
使用 pro new page 命令时生成的page有BUG

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#841]
生成页面时的步骤如下图所示：
![image](https://user-images.githubusercontent.com/12181423/35546362-f65d8948-05ae-11e8-96ad-96e9f6385c38.png)

生成后配置好 router 后运行，出现异常。
![image](https://user-images.githubusercontent.com/12181423/35546441-383bb948-05af-11e8-8991-24a1d5f9d966.png)

问题出现先生成的代码上，
![image](https://user-images.githubusercontent.com/12181423/35546493-5ebe2e2a-05af-11e8-8c1d-3475306d4ca5.png)
将其修改为：'antd' 就正常了。
![image](https://user-images.githubusercontent.com/12181423/35546537-845ed83c-05af-11e8-9b82-6fccaa08bd14.png)
![image](https://user-images.githubusercontent.com/12181423/35546549-93a7dfa0-05af-11e8-9521-b7e3a30f4e33.png)

@afc163

**Comment by chenshuai2144** [comment]
@ 错人了

**Comment by hqwlkj** [comment]
好吧

**Comment by nikogu** [comment]
@hqwlkj 升级 pro-cli@1.0.0

**Comment by hqwlkj** [comment]
@nikogu  好的 谢谢
