### ISSUE TITLE
🐛[BUG]ant-design-pro proV4 JavaScript complete出现大量警告

### ISSUE THREAD

**Issue by w345731923** [ant-design/ant-design-pro#8410]
### 🐛 bug 描述

ant-design-pro proV4 JavaScript complete出现大量警告

`Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Provider`
### 📷 复现步骤

success Installed "create-umi@0.26.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
? � Be the first to experience the new umi@3 ? Pro V4
? � Which language do you want to use? JavaScript
? � Do you need all the blocks or a simple scaffold? complete
? � complete mode can only use the version of antd@4

### 💻 复现代码
1、ant-design-pro proV4 JavaScript simple是没有警告的。
2、complete出现大量警告

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 4.12.0
- umi 版本 3.2.14
- dva: 2.4.0
- react:16.14.0
- 浏览器环境 chrome 88.0.4324.182（正式版本） （64 位）
- 开发环境 [e.g. mac OS]win10

**Comment by chenshuai2144** [comment]
react 的过期 api 信息，估计哪个底层库用的还是旧版本的 api，能 debug 一下是哪个库吗？

**Comment by w345731923** [comment]
我应该如何进行debug?

**Comment by chenshuai2144** [comment]
控制台会告诉你是哪个组件，然后你在 代码中找一下

**Comment by SilkageNet** [comment]
![Uploading image.png…]()

**Comment by SilkageNet** [comment]
![image](https://user-images.githubusercontent.com/37325878/119097444-510a3580-ba47-11eb-92de-257f6499b58b.png)

**Comment by SilkageNet** [comment]
把PageLoading相关的代码注释掉就不会报错，应该是 `@ant-design/pro-layout/es/PageLoading` 的问题。

**Comment by chenshuai2144** [comment]
已修复重新更新依赖
