### ISSUE TITLE
🐛[BUG] v5 中服务端返回最新菜单，但是页面没有更新，添加loading属性也不行

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#8412]
#### 服务端通过currentUser接口返回对应的menu数组

![image](https://user-images.githubusercontent.com/20917295/116059167-2381d480-a6b3-11eb-825b-18a191fa92d1.png)

![image](https://user-images.githubusercontent.com/20917295/116058957-f2090900-a6b2-11eb-920a-dac7492cbdd2.png)

**Comment by chenshuai2144** [comment]
来个重新仓库吧

**Comment by lishaoh** [comment]
目前有一种解决办法：服务器菜单不要通过initialState保存，直接通过接口请求
