### ISSUE TITLE
🐛[BUG]根据menu，生成的面包屑导航，为什么会多一个/admin层级，什么原因？

### ISSUE THREAD

**Issue by wyg2103** [ant-design/ant-design-pro#8413]
![image](https://user-images.githubusercontent.com/17972908/116063637-c6d4e880-a6b7-11eb-973f-c8cdd059a00b.png)

**Comment by chenshuai2144** [comment]
用了 base 了吧？

**Comment by wyg2103** [comment]
是的，base: "/admin"，区分前台，后台，设置成“/”，路由会跳转到前台，如果设置为/，在路由表里，统一加个/admin，不知是否可行？或者有没有其他方法？

**Comment by chenshuai2144** [comment]
这个我应该支持的，是我的一个 bug

**Comment by chenshuai2144** [comment]
close https://github.com/ant-design/ant-design-pro/issues/8413
