### ISSUE TITLE
🧐[问题/BUG] 按照定制主题配置 less 变量文件的修改变量优先级不足

### ISSUE THREAD

**Issue by lcysgsg** [ant-design/ant-design-pro#8414]
### 🧐 问题描述

想修改 less 变量，但是优先级不足

### 💻 示例代码

```less
// global.less
@import '~antd/es/style/themes/default.less';
@import '~antd/dist/antd.less';

@component-background: red;
```

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19550000/116067800-19180880-a6bc-11eb-814f-5a0ce0156c81.png)

**Comment by lcysgsg** [comment]
我看到文档说更多方式参考`ant-design`文档，原来还有的是不支持吗？（ #5980 ）

那在 `config/config.ts` 中修改 `theme` 特别慢，有好的办法调试定制主题吗？

**Comment by chenshuai2144** [comment]
提升一下优先级，
改成 `xxx .ant-card `这种方式，global 会被最优先加载进去
