### ISSUE TITLE
🐛[BUG] footer 底部被遮挡

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design-pro#8416]
### 📷 复现步骤
[查看官网预览链接即可](https://preview.pro.ant.design/form/advanced-form?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false)

### 🏞 期望结果
希望页面可以被顶起来一些
 
### 💻 复现代码
 看官网预览仓库代码即可

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.5.0]
- 开发环境 [e.g. mac OS]
- 谷歌浏览器 90.0.4430.85

### 🚑 其他信息
![WechatIMG1 1](https://user-images.githubusercontent.com/81732419/116170214-f2e47e00-a738-11eb-9d2d-22406069f54e.png)

**Comment by chenshuai2144** [comment]
这个是故意的，footer 是浮动的，没有办法的给设置
