### ISSUE TITLE
🧐[问题]v5版本 服务端返回菜单只是用于左侧菜单显示，不参与访问鉴权？本地也需要写一份routes？

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design-pro#8418]
### 现象描述：
welcome 和 admin 菜单可以显示，底部的table-list菜单不显示，但是浏览器可以访问table-list页面，所以有没有文档说明一下服务端返回的menu和本地menu的关系：覆盖 or 合并？

![image](https://user-images.githubusercontent.com/20917295/116183432-6c3b9b00-a750-11eb-9808-9e6919168a89.png)

**Comment by chenshuai2144** [comment]
既然都服务器返回了，直接让服务器鉴权就好了，何必让本地再循环一遍？

**Comment by lishaoh** [comment]
@chenshuai2144 我的意思是：如果是服务端返回菜单，项目里面的config/route.ts文件里面还需要写一份路由吗？
官方代码展示现象是：如果config/route.ts里面不写路由，路由访问都是404

![image](https://user-images.githubusercontent.com/20917295/116371288-d847fd00-a83d-11eb-81a1-677aeb8139bd.png)

**Comment by chenshuai2144** [comment]
路由还要告诉webpack 需要打包哪些文件的。所以是必须的
