### ISSUE TITLE
EditableProTable在开发测试环境中校验的气泡在输入文字的时候闪烁

### ISSUE THREAD

**Issue by itrui** [ant-design/ant-design-pro#8420]
EditableProTable在本地开发的时候显示是正常的，但是打包到开发或者测试环境中时，校验的气泡闪烁，输入的每个文字都闪一下，不长久显示。

**Comment by chenshuai2144** [comment]
可以来个复现吗，？

**Comment by itrui** [comment]
https://user-images.githubusercontent.com/23165428/116337271-715e2000-a80c-11eb-9ea0-b06949019442.mp4

{
      title: (<>{props.config?.required && <i style={{color: "red"}}>*</i>} <span>描述</span></>),
      dataIndex: 'describe',
      formItemProps: {
        rules: props.config?.required ? [{required: true, message: '此项是必填项'}, {max: 200, message: '最长为 200 位',}] : [{max: 200, message: '最长为 200 位',}]
      },
    },

**Comment by chenshuai2144** [comment]
fixed in new version
