### ISSUE TITLE
🧐[问题] ModalForm 中使用useState ， 每当更改state数据，modal都会重新关闭再打开

### ISSUE THREAD

**Issue by Julywj** [ant-design/ant-design-pro#8421]
### 💻 示例代码
const PwdModal: React.FC = (props: any) => {

const { visible, closeModal  } = props;

const [ activeTab, setActiveTab ] = useState("0")
const submitForm = async (vals) => {
console.log("form vals: ", vals);
}
return (<ModalForm
        visible={visible}
        formRef={formRef}
onVisibleChange={closeModal},
        title="Password Modal"
        onFinish={submitForm}
      >
        <Tabs activeKey={activeTab} onChange={setActiveTab}>
          <TabPane key="0" tab="Tab 1">
            <ProFormText.Password
      name="password"
      label={formatMessage({ id: "newPwd" })}
      placeholder={formatMessage({ id: "regex.accountPwdRule" })}
      fieldProps={{
        size: "large"
      }}
      rules={[
        {
          required: true,
          message: formatMessage({ id: "pleaseInput" })
        },
      ]}
    />
          </TabPane>
          <TabPane key="1" tab="Tab 2">
            <ProFormText.Password
      name="password"
      label={formatMessage({ id: "newPwd" })}
      placeholder={formatMessage({ id: "regex.accountPwdRule" })}
      fieldProps={{
        size: "large"
      }}
      rules={[
        {
          required: true,
          message: formatMessage({ id: "pleaseInput" })
        },
      ]}
    />
          </TabPane>
        </Tabs>
      </ModalForm>)
}

### 引用 ###
const [pwdModal, openPwdModal] = useState(false);

<div>
<Button type="primary" onClick={() => openPwdModal(true)}>Open modal</Button>
<PwdMod visible={pwdModal} closeModal={openPwdModal} />
</div>

**Comment by chenshuai2144** [comment]
让子节点来控制父节点当然会出这个问题了
