### ISSUE TITLE
🧐[问题] How to implement integration with Sentry

### ISSUE THREAD

**Issue by ali4heydari** [ant-design/ant-design-pro#8422]
### 🧐 问题描述
I need some help to implementing the integration with [Sentry](https://sentry.io). according to [Sentry docs for React](https://docs.sentry.io/platforms/javascript/guides/react/) I should wrap all application element into error boundary component. How can I implement this? and Where should I put the `Sentry.init()` method? Also can I implement Sentry's Redux integration?

**Comment by chenshuai2144** [comment]
you can init Sentry in app.ts .  app.ts is firset
