### ISSUE TITLE
🧐[问题]JavaScript heap out of memory when modify the less file base in dynamic theme env

### ISSUE THREAD

**Issue by Benjaminbai** [ant-design/ant-design-pro#8423]
### 🧐 问题描述
本地开发环境在做动态主题，但是修改less，css热更新重新编译后会报错：<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

请问怎么解决

**Comment by chenshuai2144** [comment]
调试完之后关掉它，因为真的很费性能

尤其是 less 文件比较多的时候

**Comment by lk0606** [comment]
@chenshuai2144 有什么办法可以解决吗，目前antd-pro 2.x
