### ISSUE TITLE
🐛[BUG] table 当设置了scroll={{ y: 500 }}出现了显示异常

### ISSUE THREAD

**Issue by Asence** [ant-design/ant-design-pro#8425]
### 🐛 bug 描述
当在ProTable里面添加属性scroll={{ y: 500 }};
会出现以下问题
![image](https://user-images.githubusercontent.com/45235142/116334956-a799a080-a808-11eb-942e-523b4e4c6cf8.png)
![image](https://user-images.githubusercontent.com/45235142/116335091-d57ee500-a808-11eb-9eb5-75fe57d2c1cc.png)

以下的图片这是原本的
![image](https://user-images.githubusercontent.com/45235142/116335030-c009bb00-a808-11eb-961a-6560a7e32325.png)
![image](https://user-images.githubusercontent.com/45235142/116335064-cef06d80-a808-11eb-85c9-5d841058e190.png)

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/45235142/116335112-dfa0e380-a808-11eb-8ec7-13b5ec521608.png)

### 🏞 期望结果
当里面有值的时候scroll={{ y: 500 }}才有效；

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本   3.2.16
- 浏览器环境 谷歌
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/45235142/116335254-1e369e00-a809-11eb-9773-efefe7b9784f.png)

**Comment by chenshuai2144** [comment]
你是不是没有设置 width？
