### ISSUE TITLE
[问题]如何通过后端返回的颜色动态更新主题

### ISSUE THREAD

**Issue by huhaha24** [ant-design/ant-design-pro#8428]
### 问题描述
  看了很多资料，都是只能替换预设好的主题并且是需要手动切换的。所以想问问，有什么办法能实现在项目加载的时候就动态切换主题呢？非常感谢🙏

**Comment by chenshuai2144** [comment]
需要在浏览器中编译 less。

https://zhuanlan.zhihu.com/p/281773115
