### ISSUE TITLE
🐛[BUG]同一个接口，第一次请求提示跨域，第二次可以请求

### ISSUE THREAD

**Issue by wppeng520** [ant-design/ant-design-pro#8429]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![169](https://user-images.githubusercontent.com/70751511/116385173-1d266080-a84b-11eb-988a-8927067fc6ad.png)
![170](https://user-images.githubusercontent.com/70751511/116385228-28798c00-a84b-11eb-937a-e0fa5d006cf9.png)

**Comment by chenshuai2144** [comment]
https://www.ruanyifeng.com/blog/2016/04/cors.html

跨域还挺复杂的，多看看
