### ISSUE TITLE
Authorized权限问题

### ISSUE THREAD

**Issue by sunplum123** [ant-design/ant-design-pro#843]
在官网Authorized权限例子中，为什么没有authority参数为Promise的情况啊？我试了很多次都没有成功诶。
都报了这个错！
`Functions are not valid as a React child.`

**Comment by sunplum123** [comment]
`
import checkAuthority from './utils/authority';
<AuthorizedRoute
						path="/"
						render={props => <PluginsLayout {...props} />}
						authority={checkAuthority}
						redirectPath="/question"
					/>`

`import fetch from 'dva/fetch';
// const checkAuthority = new Promise(
// 	((
// 		resolve
// 	) => {
// 		resolve();
// 	})
// );
const url = '/pscms/examsystem/question/checkAuthority.action';
const checkAuthority = fetch(
	url
);
export default checkAuthority;
`

**Comment by chenshuai2144** [comment]
还真没这么写过 我测试一下

**Comment by sunplum123** [comment]
关闭了，是我写的有问题吗？该怎么解决呢？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/cafec890b8aaf9657ded377b70d6f90aac5117d8

**Comment by sunplum123** [comment]
@chenshuai2144 并没有完全解决，成功返回的时候还是有问题的。
