### ISSUE TITLE
🐛[BUG] mock无法关闭

### ISSUE THREAD

**Issue by Zeuny** [ant-design/ant-design-pro#8430]
### 📷 复现步骤

config/config.ts
`
export default defineConfig({
  hash: true,
  antd: {},
  mock: false //停止mock,
});
`
和 
![image](https://user-images.githubusercontent.com/21021062/116429430-76f14f80-a878-11eb-9b95-07952f1ecee3.png)
命令行都关闭了mock，并且删除了`mock`目录，但是实际上打开项目的时候，请求的地址还是localhost:8000
![image](https://user-images.githubusercontent.com/21021062/116429574-97210e80-a878-11eb-8f03-fe556f6b7d22.png)
而且也使用了环境变量
![image](https://user-images.githubusercontent.com/21021062/116429632-a2743a00-a878-11eb-8b00-3247707e4913.png)
![image](https://user-images.githubusercontent.com/21021062/116429661-a902b180-a878-11eb-86df-bd2000bcc469.png)

### 🏞 期望结果

应该请求localhost:8080才对，而且环境变量应该是可用的

### © 版本信息

- Ant Design Pro 版本: [5.0.0-beta.2]
- umi 版本 ^3.4.0
- 浏览器环境 Chrome最新版
- 开发环境 [Windows 10 20H2]

**Comment by chenshuai2144** [comment]
没看懂你在玩什么黑科技，你的目标是什么？

**Comment by Zeuny** [comment]
我看官方文档的啊……
是这样的，我想后端接口请求我自己的服务器……但是我mock关闭不了。
`https://beta-pro.ant.design/docs/environment-manage-cn` 这个是参考文档
![image](https://user-images.githubusercontent.com/21021062/116494860-50f99880-a8d4-11eb-9147-e83a78e661ee.png)
我尝试了命令行使用MOCK=none、
尝试了配置文件设置mock=false、
尝试了删除mock文件夹，结果请求的接口地址都是localhost:8000端口，请问是哪里出问题了

**Comment by chenshuai2144** [comment]
请求自己的后端要用proxy，不是用这个定义变量的方式

proxy 会把你的请求转发到服务器

**Comment by moluzhui** [comment]
> 请求自己的后端要用proxy，不是用这个定义变量的方式
> 
> proxy 会把你的请求转发到服务器

我在proxy.ts中添加了本地服务
```
# proxy.ts
  pre: {
    '/api/': {
      target: 'http://localhost:8080',
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
  },
```
执行npm run start:pre后，请求仍然发给了mock，并没有发到服务器，请问是还缺少什么配置吗？
