### ISSUE TITLE
🧐[问题]怎么在request的response拦截器刷新token并重新发送请求

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-pro#8431]
### 🧐 问题描述

这边想在request里拦截请求，如果请求返回的结果网络代码是401的话则刷新（或者重新获取）token然后重新发送之前401的请求，请问应该怎么规范的操作，是用request.interceptors.response.use吗

### 💻 示例代码

![image](https://user-images.githubusercontent.com/32634443/116507737-76959a80-a8f2-11eb-9e6e-4272244e44a2.png)

**Comment by chenshuai2144** [comment]
options 不是给你了吗，你调用一下的 request ，不过注意下重试的次数

**Comment by firstmetcs** [comment]
那请问url用哪个呢？用response里的url就可以吗 @chenshuai2144
