### ISSUE TITLE
👑 [需求] Ant Design Pro V5 动态菜单渲染， 无法调用 access.ts  鉴权函数

### ISSUE THREAD

**Issue by mzcaer** [ant-design/ant-design-pro#8432]
### 🥰 需求描述

 新渲染的菜单，访问无法调用 鉴权函数， 发现只有在 config.ts / routes.ts 内 写上 access: 'normalRouteFilter',  才会触发鉴权函数！

### 🚑 其他信息

<!--
 ```

```

```
-->
```
menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: initialState,
      request: async (params, defaultMenuData) => {
        console.log('menu____________')
        return [{
          path: '/admin',
          name: 'admin',
          icon: 'crown',
          component: './Admin',
          routes: [
            {
              path: '/admin/sub-page',
              name: 'sub-page',
              icon: 'smile',
              component: './Welcome',
              access: 'normalRouteFilter', // 会调用 src/access.ts 中返回的 normalRouteFilter 进行鉴权
            },
          ],
        },
        {
          path: '/welcome',
          name: 'welcome',
          icon: 'smile',
          component: './Welcome',
        }];
      },
    },

export default function access(initialState: { currentUser?: API.CurrentUser | undefined }) {
  const { currentUser } = initialState || {};
  return {
    canAdmin: currentUser && currentUser.access === 'admin',
    normalRouteFilter: (route:any) => {
      console.log('normalRouteFilter',route)
      return true
    }, // initialState 中包含了的路由才有权限访问
  };
}

**Comment by lishaoh** [comment]
@mzcaer 目前我的解决办法是直接在onPageChange方法里面做一次URL鉴权

![image](https://user-images.githubusercontent.com/20917295/116540510-d43edc80-a91c-11eb-8da7-2bd204c40a6c.png)

**Comment by Rada8732** [comment]
Change is good

**Comment by mzcaer** [comment]
谢谢

**Comment by chenshuai2144** [comment]
可以当成一个 featrue 来实现一下

**Comment by TrumanDu** [comment]
@chenshuai2144  `@umijs/plugin-access:2.5.0` 动态菜单渲染， 依赖无法调用鉴权函数，有何解？

**Comment by a51427051** [comment]
遇到了同样的问题，动态菜单渲染无法调用鉴权，有结果麻烦联系我
