### ISSUE TITLE
🧐[问题] V5 如何添加服务器本地svg logo

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8434]
### 🧐 问题描述

V5 如何添加服务器本地svg logo

**Comment by chenshuai2144** [comment]
在 publick 中放入 logo.svg,
使用的时候

`src="/logo.svg"`

**Comment by hihuangwei** [comment]
> 在 public 中放入 logo.svg,
> 使用的时候
> 
> `src="/logo.svg"`

defaultSettings.ts 里的logo 无法使用本地的

**Comment by chenshuai2144** [comment]
`logo: "/logo.svg"`
