### ISSUE TITLE
v5 脚手架设置了子路由会导致它后面配置的路由失效

### ISSUE THREAD

**Issue by shixibao** [ant-design/ant-design-pro#8437]
### 🐛 bug 描述
v5 脚手架里设置了子路由会导致它后面配置的路由失效，怎么解决？

### © 版本信息
- Ant Design Pro 版本: 5.0
- umi 版本：3.4.0

**Comment by DerrickTel** [comment]
有demo之类的吗？这样没头没尾的比较男排查

**Comment by chenshuai2144** [comment]
把后面配置的路由放到 它的前面，优先匹配后面的
