### ISSUE TITLE
antdpro 升级umi3.0  后页面一直loading

### ISSUE THREAD

**Issue by gejianvs** [ant-design/ant-design-pro#8438]
![image](https://user-images.githubusercontent.com/28592122/116681506-a79fc900-a9df-11eb-9b58-2d66a750e2e1.png)
看了下source, 没有加载静态资源， 只有一个模板文件
![image](https://user-images.githubusercontent.com/28592122/116681715-e897dd80-a9df-11eb-8662-62873146ddb4.png)

**Comment by yxf007** [comment]
同样问题

**Comment by chenshuai2144** [comment]
项目拉出来看看吧，估计是 js 路由没挂载
