### ISSUE TITLE
👑 [需求] v4版本的水印只支持字符串，而且好像不能换行，请问能实现React.Element的形式吗

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-pro#8439]
### 🥰 需求描述

v4版本的水印只支持字符串，而且好像不能换行，请问能实现React.Element的形式吗
比如动态显示时间

### 🧐 解决方案

目前的方案是将时间放到state里，然后更新state，不知道这种形式的话是不是资源开销有点大，而且并**不支持换行**

### 🚑 其他信息

版本v4
![image](https://user-images.githubusercontent.com/32634443/117021409-e90ade00-ad29-11eb-958b-e61bea7b9f68.png)

**Comment by chenshuai2144** [comment]
是canvs画的 只支持图片和文字 

有定制需求尽量用图片
