### ISSUE TITLE
🐛[BUG]V4.5脚手架创建出来天然就有权限问题啊，官网的preview也一样不算故障吗

### ISSUE THREAD

**Issue by yangfjiahl** [ant-design/ant-design-pro#8440]
### 🐛 bug 描述

V4.5脚手架创建出来天然就有权限问题，配置了authority，敲个地址随便访问，完全没拦截

### 📷 复现步骤

yarn create umi myapp
v4默认，或者看官网的/dashboard菜单，权限不带起作用的

### 🏞 期望结果

最基本的权限功能能work

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.5.0]
- umi 版本 3.2.4
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by firstmetcs** [comment]
默认没有权限就是有权限，你可以改一下没有权限就是没权限，参照文件：src\components\Authorized\CheckPermissions.tsx

类似的issue挺多的

**Comment by firstmetcs** [comment]
https://github.com/ant-design/ant-design-pro/blob/f68066a91e2ddb53ed821ff2b770bac9c90f8989/src/layouts/BasicLayout.tsx#L123

https://github.com/ant-design/ant-design-pro/blob/f68066a91e2ddb53ed821ff2b770bac9c90f8989/src/components/Authorized/CheckPermissions.tsx#L29

**Comment by yangfjiahl** [comment]
不仅不显示，手动敲进去也要去403，改这俩地方不行吧

**Comment by chenshuai2144** [comment]
没设置权限就是有权限，如果想开箱即用 试试 v5 版本

**Comment by yangfjiahl** [comment]
一堆问题，issue说关就关，怪不得蚂蚁每况愈下，也真是服了。

**Comment by chenshuai2144** [comment]
开源项目没手是用不了了，在使用之前最好先祥细了解一下，不要一上来就输出情绪 
不是商业方案不会提供无微不至的答疑服务的。

**Comment by yangfjiahl** [comment]
intresting
