### ISSUE TITLE
🧐[问题]面包屑导航栏有问题

### ISSUE THREAD

**Issue by ccbay** [ant-design/ant-design-pro#8441]
### 🧐 问题描述

安装官的所有区块后，导航栏链接有问题，不显示首页按钮
![图片](https://user-images.githubusercontent.com/29878956/117144440-81fe2f80-ade4-11eb-933e-2d4f450f638c.png)

![图片](https://user-images.githubusercontent.com/29878956/117144304-5d09bc80-ade4-11eb-9a9b-da7e24d3f979.png)

**Comment by chenshuai2144** [comment]
```
  breadcrumbRender={(routers = []) => [
        {
          path: '/',
          breadcrumbName: "首页",
        },
        ...routers,
      ]}
```

在 layout 的配置中加一下这个
