### ISSUE TITLE
🧐[问题]requestInterceptors中可以使用initialState里面的数据吗？

### ISSUE THREAD

**Issue by qq329401134** [ant-design/ant-design-pro#8442]
### 🧐 问题描述

在requestInterceptors中想要使用initialState中的authorization数据，该如何正确使用？

### 💻 示例代码
![image](https://user-images.githubusercontent.com/38587734/117235236-ea86f400-ae58-11eb-9893-bf20c147cf0d.png)
会报错
![image](https://user-images.githubusercontent.com/38587734/117234826-4d2bc000-ae58-11eb-8936-b63e81061757.png)

**Comment by qq329401134** [comment]
@chenshuai2144 可以帮忙解答下吗(╥﹏╥)

**Comment by qq329401134** [comment]
看提示是只能用于function component 所以只能使用LocalStorage吗  @chenshuai2144

**Comment by chenshuai2144** [comment]
windows 上挂一个吧
