### ISSUE TITLE
🧐[问题] (Question)

### ISSUE THREAD

**Issue by mortymike** [ant-design/ant-design-pro#8443]
Hello,

I'm looking to use V5 in a new project. Do you have a release date for V5 beta with ProLayout complete scaffolding (similar to V4 complete scaffolding)?

**Comment by chenshuai2144** [comment]
v5 is stable, but it lacks enough features. If you want to use the full package, you can take a look at the script in deploy, it will pull all the blocks down

```
yarn add umi-plugin-antd-theme umi-plugin-pro umi-plugin-setting-drawer
 yarn run pro fetch-blocks --branch=v5
```

**Comment by mortymike** [comment]
I see, thank you!!
I went ahead and manually merged from all-blocks branch into v5 and it seems to be working pretty well.
