### ISSUE TITLE
🧐[调用setInitialState之后，layout的initialState未改变]

### ISSUE THREAD

**Issue by yjz1004** [ant-design/ant-design-pro#8445]
### 🧐 问题描述

在页面内调用setInitialState，更新initialState的属性，触发了layout->menu->request,但是initialState值未改变

### 💻 示例代码

![WX20210506-155427](https://user-images.githubusercontent.com/48308568/117262320-b117ae00-ae83-11eb-84a8-0e7156060441.png)
![2](https://user-images.githubusercontent.com/48308568/117262338-b5dc6200-ae83-11eb-9b85-488288f08581.png)
![3](https://user-images.githubusercontent.com/48308568/117262978-634f7580-ae84-11eb-9c02-f5872921a41c.png)

### 🚑 其他信息
![4](https://user-images.githubusercontent.com/48308568/117263649-10c28900-ae85-11eb-821f-ce3ea07cc3cf.png)

**Comment by chenshuai2144** [comment]
request 里面是个闭包，你用 params 穿进去，然后` request:(params)=>{} ` 来取用

**Comment by cdz620** [comment]
> request 里面是个闭包，你用 params 穿进去，然后`request:(params)=>{ console.log(params) }` 来取用

还是一样没更新，除非页面刷新，或者手动调用getInitialState，如果手动调用getInitialState，退出时也会触发调动request一次，导致再次获取用户信息异常
