### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by mrs01dev** [ant-design/ant-design-pro#8447]
Run pnpm dev
Trying to login fail:
405 Method Not Allowed

![image](https://user-images.githubusercontent.com/64358630/117365914-e1a41b80-ae74-11eb-9dc8-e51cda573e13.png)

**Comment by mrs01dev** [comment]
Run  pnpm start 👍 I could login successfully
Thanks

**Comment by ssshooter** [comment]
it works, but what's the different between npm and pnpm ?🤔
