### ISSUE TITLE
🐛[BUG] V5 定制主题 表格组件引用主题变量失效

### ISSUE THREAD

**Issue by hs185556** [ant-design/ant-design-pro#8448]
### 🐛 bug 描述
开启黑暗主题，配置background-color-light变量，表格头部背景没有跟着变，手动覆盖才有效

### 📷 复现步骤

1.开启黑暗主题
// config.ts
antd: {
    dark: true,
  },
2.配置主题变量
// config.ts
"background-color-light": defaultSettings.backgroundColorLight,

3.表格的头部背景和hover颜色没引用主题变量

### 🏞 期望结果

表格的头部背景和hover颜色正确引用主题变量

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 3.4.8
- 浏览器环境 谷歌
开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/46480644/117389157-82024a80-af1e-11eb-9d46-52935eb17a77.png)
![image](https://user-images.githubusercontent.com/46480644/117528657-d2a0a300-b005-11eb-8580-6b2b80600297.png)

**Comment by chenshuai2144** [comment]
来个截图

**Comment by hs185556** [comment]
> 来个截图

加了

**Comment by chenshuai2144** [comment]
看起来没什么问题，能帮忙看看 devtool 里面的 css 是被谁覆盖了吗

**Comment by hs185556** [comment]
> 看起来没什么问题，能帮忙看看 devtool 里面的 css 是被谁覆盖了吗

可复现demo https://github.com/hs185556/theme-issue-recover

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/118481546-2e75d500-b746-11eb-8292-8f24cb696769.png)


看起来是好的，但是 layout 有问题，我修一下

**Comment by hs185556** [comment]
> ![image](https://user-images.githubusercontent.com/8186664/118481546-2e75d500-b746-11eb-8292-8f24cb696769.png)
> 
> 看起来是好的，但是 layout 有问题，我修一下

config里的theme变量有生效吗

**Comment by chenshuai2144** [comment]
@marcustut https://pro.ant.design/zh-CN/blog/dynamic-theme
