### ISSUE TITLE
🐛[BUG] 菜单的高级用法中使用layoutActionRef 报错

### ISSUE THREAD

**Issue by qq329401134** [ant-design/ant-design-pro#8449]
### 🐛 bug 描述

在app.tsx中加入export const layoutActionRef = createRef<{ reload: () => void }>();会报错

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/38587734/117434881-c7933780-af5f-11eb-8dfb-a0f1628fac22.png)

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
app.tsx 好像不能随便 export

**Comment by qq329401134** [comment]
> app.tsx 好像不能随便 export

文档上是那样用的，正确的方法应该是什么样子的呢，而且我发现layout->menu 的request中如果返回数组，登录成功后会调用一次request，如果返回一个promise的话登录成功后不会调用request，在request中打印的initialState的currentUser一直是undefined除非刷新页面

**Comment by chenshuai2144** [comment]
@qq329401134  params 设置一下，params 修改就会触发request


`params={initialState}` 你可以这样设置一下

**Comment by chenshuai2144** [comment]
可以更新依赖试试了

**Comment by qq329401134** [comment]
> 可以更新依赖试试了

我新开了一个更详细的   劳烦看一下

**Comment by againF** [comment]
umi4里面出现了同样的问题

**Comment by Fluox-Etine** [comment]
> ###

这样设置有问题 params={initialState} 登录后重复请求；请求了2次。 无论  params={initialState}  还是 initialState?.currentUser?.user_id, 这样设置；退出的时候会在一次请求路由接口。请问这样如何解决呢

**Comment by xlorne** [comment]
我的处理方式：
app.tsx:
```
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  const layoutActionRef = createRef<{ reload: () => void }>();

  //添加一个方法，用于刷新菜单的方法
  setInitialState((preInitialState) => ({
    ...preInitialState,
    reloadLayout: () => {
      layoutActionRef.current?.reload();
    }
  }));

return {
  actionRef: layoutActionRef,
  // 其他配置
  ...
}
```
test.tsx
```
import { Button } from "antd";
import React from "react";
import { useModel } from '@umijs/max';

const TestPage: React.FC = () => {

  const { initialState, setInitialState } = useModel('@@initialState');

  const handleReload = () => {
    //@ts-ignore
    initialState.reloadLayout();
  }

  return (
    <div>
      <Button onClick={handleReload}>reload Menu</Button>
    </div>
  )
};

export default TestPage;


```
另外在menu中，我并没有设置initialState作为param，不然的话将会一直刷新菜单。
由于我所有的请求都携带了token，所有后端是可以识别用户信息的，就不需要在前端指定用户的信息了。
