### ISSUE TITLE
👑 [需求],了支持 rtl 方向的

### ISSUE THREAD

**Issue by mrs01dev** [ant-design/ant-design-pro#8450]
### 🥰 需求描述
如何更改頁面佈局，所以它從右到左開始
How to change page layout ,so it start from right to left .

請看下面兩張圖片的區別
Please see the the difference between the two pictures below
![image](https://user-images.githubusercontent.com/64358630/117518929-821e3c80-af56-11eb-92dc-c2c44266aa51.png)

![image](https://user-images.githubusercontent.com/64358630/117518821-14721080-af56-11eb-9bbb-affd42615da4.png)

如上圖所示，來自網站 [https://ant.design/](url)
As shown in the picture above, from the website.

我需要一個按鈕來更改佈局方向
I need a button to change layout direction ("RTL" || "LTR").

當用戶單擊RTL按鈕時，側面菜單欄將位於頁面右側。
when a user click on RTL button , the side menu bar   will be will be pensioned to the Right of the page.

![image](https://user-images.githubusercontent.com/64358630/117519982-e80cc300-af5a-11eb-9db6-320dd7e58695.png)

當用戶單擊LTR按鈕時，側面菜單欄將退回到頁面左側。
when a user click on LTR button , the side menu bar  will be pensioned to the left of the page  .
![image](https://user-images.githubusercontent.com/64358630/117519931-a1b76400-af5a-11eb-98a6-6897bd108572.png)

### 🧐 解决方案
我不知道

謝謝
Thanks

**Comment by chenshuai2144** [comment]
This is a development cost. Although antd supports it by default, you need to write a lot of code to make your website wan'mei support

**Comment by mrs01dev** [comment]
For reference

GitHub user @mohitkhemwani7  have a solution:
https://github.com/mohitkhemwani7/internationalisation

RTL
![image](https://user-images.githubusercontent.com/64358630/117533370-4ceb0c00-afa1-11eb-84a5-94853f07dcc5.png)

LTR

![image](https://user-images.githubusercontent.com/64358630/117533421-9fc4c380-afa1-11eb-95d3-26e6599934bf.png)

Thanks.
