### ISSUE TITLE
🐛[BUG] menu的request不能正确触发

### ISSUE THREAD

**Issue by qq329401134** [ant-design/ant-design-pro#8452]
### 📷 复现步骤
第一种情况，request返回固定的数组，在menu的request和onPageChange分别打印initialState，然后清理缓存进行登录
![image](https://user-images.githubusercontent.com/38587734/117533374-0b00ab00-b01f-11eb-82cb-2f85cb6dd63d.png)
![image](https://user-images.githubusercontent.com/38587734/117533377-13f17c80-b01f-11eb-8ca4-c97ab942bf59.png)

自动触发menu的request并登录跳到welcome页 控制台打印如下红框
![image](https://user-images.githubusercontent.com/38587734/117533502-cde8e880-b01f-11eb-9147-5c9846dec773.png)
menu的request中打印的initialState的currentUser为undefined而onPageChange是正常的

第二种情况，request返回promise，在menu的request和onPageChange分别打印initialState，然后清理缓存进行登录
![image](https://user-images.githubusercontent.com/38587734/117533478-ab56cf80-b01f-11eb-8b00-930426b6b1f7.png)
登录跳到welcome页但是并未触发menu的request

第三种情况，在情况二的基础上使用手动刷新菜单
![image](https://user-images.githubusercontent.com/38587734/117533571-202a0980-b020-11eb-912e-bf2da6055e54.png)
![image](https://user-images.githubusercontent.com/38587734/117533575-23bd9080-b020-11eb-9268-c776763dc37a.png)
![image](https://user-images.githubusercontent.com/38587734/117533580-2e782580-b020-11eb-913f-d158282864d6.png)

手动触发，引用竟然为null..
![image](https://user-images.githubusercontent.com/38587734/117533640-6e3f0d00-b020-11eb-9e37-f67488b94b5c.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by qq329401134** [comment]
`  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@ant-design/pro-card": "^1.11.12",
    "@ant-design/pro-descriptions": "^1.7.7",
    "@ant-design/pro-form": "^1.22.1",
    "@ant-design/pro-layout": "^6.17.1",
    "@ant-design/pro-table": "^2.35.1",
    "@umijs/openapi": "^1.1.17",
    "@umijs/plugin-openapi": "^1.3.0",
    "@umijs/route-utils": "^1.0.37",
    "antd": "^4.15.4",
    "classnames": "^2.3.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "omit.js": "^2.0.2",
    "react": "^17.0.2",
    "react-dev-inspector": "^1.5.3",
    "react-dom": "^17.0.2",
    "react-helmet-async": "^1.0.9",
    "umi": "^3.4.15",
    "umi-request": "^1.3.5"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.0.4",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.11",
    "@types/history": "^4.7.8",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.168",
    "@types/react": "^17.0.5",
    "@types/react-dom": "^17.0.3",
    "@types/react-helmet": "^6.1.1",
    "@umijs/fabric": "^2.5.12",
    "@umijs/plugin-blocks": "^2.2.2",
    "@umijs/plugin-esbuild": "^1.3.1",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.17",
    "@umijs/preset-react": "^1.8.7",
    "@umijs/yorkie": "^2.0.5",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.3",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.2",
    "enzyme": "^3.11.0",
    "eslint": "^7.26.0",
    "express": "^4.17.1",
    "gh-pages": "^3.1.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^11.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.2.1",
    "puppeteer-core": "^9.1.1",
    "stylelint": "^13.13.1",
    "typescript": "^4.2.4"`

依赖版本   @chenshuai2144 麻烦再看一下  ，辛苦了

**Comment by qq329401134** [comment]
第一种情况，menu的request的initialState的currentUser不应该为undefined
第二种情况，应该被触发并且刷新菜单界面
第三种情况，引用不应该为null

**Comment by chenshuai2144** [comment]
> 第一种情况，menu的request的initialState的currentUser不应该为undefined

request 在调用的时候是闭包的，不是什么魔法引用, 在他调用的时候 initialState 当然是 undefined，所以要设置 params，initialState 改变重新触发请求。

> 第二种情况，应该被触发并且刷新菜单界面

你 console initialState 试试
```
 menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: initialState,
      request: async (params, defaultMenuData) => {
        return initialState.menuData;
      },
    },
```

> 第三种情况，引用不应该为null

参数名叫 actionRef，不叫 LayoutActionRef

**Comment by qq329401134** [comment]
`request 在调用的时候是闭包的，不是什么魔法引用, 在他调用的时候 initialState 当然是 undefined，所以要设置 params，initialState 改变重新触发请求。`

这种是在类似于这种
![image](https://user-images.githubusercontent.com/38587734/117534407-e529d500-b023-11eb-91cc-447a8871bee1.png)直接返回数组的menu的request有效
但是对于
![image](https://user-images.githubusercontent.com/38587734/117534420-f5da4b00-b023-11eb-80d0-f4d690f3c621.png)这种返回promise就不会触发
-----------------------------------
手动触发可以了
但是打印的currentUser还是undefined
![image](https://user-images.githubusercontent.com/38587734/117534453-1c988180-b024-11eb-9b6c-663fa85a2ef8.png)

**Comment by qq329401134** [comment]
因为initialState是undefined  导致最后还是无法渲染菜单
![image](https://user-images.githubusercontent.com/38587734/117534689-21aa0080-b025-11eb-8fbe-45958fabe77a.png)
![image](https://user-images.githubusercontent.com/38587734/117534683-1e167980-b025-11eb-850f-ee14b0d4aef3.png)


点击刷新菜单多次initialState仍然是undefined
![image](https://user-images.githubusercontent.com/38587734/117534724-48683700-b025-11eb-9136-6c743b6ddd9a.png)

**Comment by chenshuai2144** [comment]
你这种情况就不要用 request 了 

直接用 
```
route={
 routest:menu
}
```

**Comment by qq329401134** [comment]
我感觉是bug   网络请求的方式必须要刷新页面才能出来，不过也差不多了，大概的东西都了解了谢谢了

**Comment by qq1170623178** [comment]
> 我感觉是bug 网络请求的方式必须要刷新页面才能出来，不过也差不多了，大概的东西都了解了谢谢了
兄弟帮忙看看我的current这为啥是null啊
![image](https://user-images.githubusercontent.com/43264733/144981198-082702e8-0f3e-4f74-aa0f-25d9e72211f9.png)
![image](https://user-images.githubusercontent.com/43264733/144981295-79389de4-de5a-4414-a25b-7b9f8d4ea76d.png)
