### ISSUE TITLE
springboot+security+antd pro v5 跨域登录成功后请求接口没有携带cookie😟？

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design-pro#8453]
### 🧐 问题描述

前台：localhost:8000
后台：local host:8080

输入用户密码登录成功，再次请求另一个接口api/sysUser/currentUser时未携带之前的cookie，而导致重定向到登录页。
我在postman中携带cookie访问api/sysUser/currentUser能正常访问到。

login请求
![image](https://user-images.githubusercontent.com/13833722/117534070-7730de00-b022-11eb-9217-3ead9be376ff.png)

currentUser请求
![image](https://user-images.githubusercontent.com/13833722/117534081-82840980-b022-11eb-940f-2a5819812674.png)

报错：
![image](https://user-images.githubusercontent.com/13833722/117534355-9d0ab280-b023-11eb-8216-d949c5701632.png)

### 💻 示例代码
app.tsx中设置credentials: 'include'
```
const request = extend({
errorHandler, // 默认错误处理
credentials: 'include', // 默认请求是否带上cookie
});
```

WebSecurityConfigurerAdapter.configure(HttpSecurity http)中设置了http.cors()

WebMvcConfigurer中设置了
```
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("*")
                .allowedOrigins("*")
                .allowCredentials(true)
                .allowedMethods("*")
                .allowedHeaders("*");
    }
```

**Comment by chenshuai2144** [comment]
你的状态码怎么是 302？ 被谁重定向了

**Comment by chengzequn** [comment]
问题已解决。设置server.servlet.session.cookie.path: / ，即将cookie所在目录设置为根目录。
