### ISSUE TITLE
🐛[BUG] V5版本 的beta 官网 切换 为暗黑模式后，再切换左侧菜单，暗黑模式被取消。

### ISSUE THREAD

**Issue by Objectivezt** [ant-design/ant-design-pro#8454]
### 🐛 bug 描述

V5版本 的beta 官网 切换 为暗黑模式后，再切换左侧菜单，暗黑模式被取消。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个功能现在还有点问题，只能当玩具，先忍忍吧
