### ISSUE TITLE
🐛[BUG] 在safir浏览器中 设置中文 失效

### ISSUE THREAD

**Issue by Josncb** [ant-design/ant-design-pro#8455]
### 🐛 bug 描述

在google中设置中文正常，但是在safir中，输入提示和 弹窗之类的按钮还是英文的。

### 📷 复现步骤

修改config.ts

 locale: {
    default: 'zh-CN',
    antd: true,
    baseNavigator: true,
  },

### 🏞 期望结果

期望组件都是中文的，但是safir 组件是英文的

**Comment by chenshuai2144** [comment]
safari 可能有兼容性问题，给个重现的 repo 吧

你的代码里 是不是加了 safari 不支持的特性

**Comment by Josncb** [comment]
> safari 可能有兼容性问题，给个重现的 repo 吧
> 
> 你的代码里 是不是加了 safari 不支持的特性

你可以按照 文档运行  yarn create umi。只加一个弹窗，在 safari 里是英文的。但是 google 就是中文的。代码默认是中文的。不做任何修改运行默认代码
