### ISSUE TITLE
🧐[问题] 引入antd的样式后，css重复

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/ant-design-pro#8456]
### 🧐 问题描述

在自定义的less文件中，引入antd样式

`@import '~antd/es/style/index.less';`

浏览器会重复渲染css，类似：
![image](https://user-images.githubusercontent.com/49073282/117626566-d40ad080-b1a9-11eb-9530-30f6a1564247.png)

正式环境也会有这种情况：
![image](https://user-images.githubusercontent.com/49073282/117629035-55636280-b1ac-11eb-97a8-d31b14ac2b23.png)

请问各位大佬，如果我想在自定义的样式文件中引入antd的样式，该怎么写才不会导致css重复。或者说，我能阻止默认的antd样式导入吗

**Comment by chenshuai2144** [comment]
试试这个配置，应该能减少一些，不过我觉得 dev 环境其实无所谓
```
const webpackPlugin = (config: any) => {
  // optimize chunks
  config.merge({
    optimization: {
      minimize: true,
      splitChunks: {
        chunks: "all",
        minChunks: 2,
        automaticNameDelimiter: ".",
        cacheGroups: {
          vendor: {
            name: "vendors",
            test({ resource }: { resource: string }) {
              return /[\\/]node_modules[\\/]/.test(resource);
            },
            priority: 10,
          },
        },
      },
    },
  });

  return config;
};

```
