### ISSUE TITLE
🧐[问题]yarn后运行一直反复报一个babel的警告

### ISSUE THREAD

**Issue by oaifshdfaseo** [ant-design/ant-design-pro#8457]
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.

**Comment by kaisawind** [comment]
Same

**Comment by oaifshdfaseo** [comment]
重安几次就好了

**Comment by kangyana** [comment]
修改babel.config.js，
@babel/preset-env 加上 loose 就可以了。
`module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        loose: true,
      }
    ]
  ]
};`
