### ISSUE TITLE
V5 的ProFormText组件，max校验有bug🐛[BUG]

### ISSUE THREAD

**Issue by whaty** [ant-design/ant-design-pro#8458]
### 🐛 bug 描述
ProFormText组件，从零开始输入，校验是正常的，但是输入完，做修改功能的时候，字段长度没有超长，也会提示字段超长。只要开始往框里输入任何信息之后，提示就没有了。目前我解决不了这个bug，得修改底层代码。

![image](https://user-images.githubusercontent.com/26294919/117641815-2f908a80-b1b9-11eb-8fb1-cfec21b48f57.png)

![image](https://user-images.githubusercontent.com/26294919/117641895-47680e80-b1b9-11eb-9415-1ca544e66796.png)

**Comment by whaty** [comment]
谁能帮看看这个问题，我该怎么解决

**Comment by 569202812** [comment]
> 谁能帮看看这个问题，我该怎么解决

直接和`label`等属性一个层级写`rules`

**Comment by whaty** [comment]
> > 谁能帮看看这个问题，我该怎么解决
> 
> 直接和`label`等属性一个层级写`rules`

谢谢啦，我试过了，一样的现象，

**Comment by 569202812** [comment]
> > > 谁能帮看看这个问题，我该怎么解决
> > 
> > 
> > 直接和`label`等属性一个层级写`rules`
> 
> 谢谢啦，我试过了，一样的现象，

感觉是国际化的问题，我用普通的文字输出没啥问题，先看看国际化能拿到值吗

**Comment by chenshuai2144** [comment]
用 formartmessage 就可以了，不要用组件
