### ISSUE TITLE
高级表单中可编辑表格的问题

### ISSUE THREAD

**Issue by DingLiPlus** [ant-design/ant-design-pro#846]
[官方示例中的可编辑表格](https://preview.pro.ant.design/#/form/advanced-form)是个很方便的组件，能够大量简化用户操作。
但一直都存在一些bug，希望能继续优化加强这个组件，让其成为一个更独立的组件，使用起来更顺畅些

**Comment by chenshuai2144** [comment]
你可以pr 或者告诉我们有什么bug

**Comment by firemoon2000** [comment]
目前官方demo中.对于可以编辑表格,输入完一个输入框.移动到下个输入框.或者点击下个输入框时.整个grid就会开始转圈圈.可以试试

**Comment by DingLiPlus** [comment]
1. @firemoon2000 提到的。
2. 新增行，不填内容不能删行。
3. 连续新增两行，点保存无效。

能做成和table一样的通用型组件就更好了😆

**Comment by ddcat1115** [comment]
是有这些问题，后续需要优化。当然更欢迎pr~

**Comment by wunayou** [comment]
怎么修改PR 我来修改这个问题

**Comment by chenshuai2144** [comment]
@wunayou  https://github.com/geeeeeeeeek/git-recipes/wiki/3.3-%E5%88%9B%E5%BB%BA-Pull-Request
有教程的

**Comment by 104gogo** [comment]
希望能支持Form的rules那些配置

**Comment by billychou** [comment]
![image](https://user-images.githubusercontent.com/3585362/47286676-4cc4d400-d622-11e8-8cc6-a13298f1d3f7.png)
类似于上图中这种操作，增加省份。Ant Design 的高级表单可以实现吗？
