### ISSUE TITLE
🧐[demo http://172.16.69.108:800/ 访问疑问]

### ISSUE THREAD

**Issue by yichenw7** [ant-design/ant-design-pro#8460]
### 💻 示例代码
http://172.16.69.108:8000

**Comment by yichenw7** [comment]
[#8459]是一个已关闭issue，不是有效解答

**Comment by lishaoh** [comment]
@yichenw7 是想让你把问题描述清楚一些 😂

**Comment by yichenw7** [comment]
![image](https://user-images.githubusercontent.com/16425999/117647367-771a1500-b1bf-11eb-8f85-5eb3b46059a8.png)
![image](https://user-images.githubusercontent.com/16425999/117647399-800ae680-b1bf-11eb-9edd-f3761a0dbde3.png)

**Comment by lishaoh** [comment]
@yichenw7 那个链接好像一直都有问题，一般都是把项目直接download到本地，然后起服务

**Comment by yichenw7** [comment]
可以贴一下后端服务地址么

**Comment by lishaoh** [comment]
本地直接 yarn start 起个mock环境就可以预览

**Comment by yichenw7** [comment]
好呢，起 start 是可以的，前起 dev 需验证

**Comment by chenshuai2144** [comment]
用 dev 是没有 mock 的，所以你的接口会报错
