### ISSUE TITLE
🧐[问题] How to make Table responsive ?

### ISSUE THREAD

**Issue by kevinadhiguna** [ant-design/ant-design-pro#8461]
### 🧐 问题描述

Hi, I would like to make table responsive in Ant Design Pro. It currently looks like this : 
![not-responsive](https://user-images.githubusercontent.com/43397636/117763456-0ae9f080-b255-11eb-88f9-2f1eeb6f4cad.png)

As you can see, the table above is not responsive.

I tried both : 
- [Components Table demo responsive](https://ant.design/components/table/#components-table-demo-responsive)
- [Custom CSS in Responsive columns for table component - Ant Design issue](https://github.com/ant-design/ant-design/issues/11817#issuecomment-555699482)

Unfortunately both did not work for me. Any help will be appreciated.

**Comment by chenshuai2144** [comment]
look this api



responsive | The list of breakpoints at which to display this column. Always visible if not set. | Breakpoint[] | - | 4.2.0
-- | -- | -- | -- | --
