### ISSUE TITLE
🐛[BUG] 控制台大量报错

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design-pro#8464]
### 🐛 bug 描述

控制台报错。

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/58337359/117908681-71314a80-b30b-11eb-974b-9a1ae62ccdeb.png)

### 🏞 期望结果

无报错信息。

### 💻 复现代码

根据官网说明创建项目，install 之后打开项目首页。

### © 版本信息

- Ant Design Pro 版本: V5

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/58337359/117908774-9e7df880-b30b-11eb-8653-7eb028ad5e0d.png)

![image](https://user-images.githubusercontent.com/58337359/117908808-b05f9b80-b30b-11eb-9a40-625ba9c2f824.png)

**Comment by chenshuai2144** [comment]
dup of #8465
