### ISSUE TITLE
🧐[问题]V5版本项目初始化后，控制台出现大量警告

### ISSUE THREAD

**Issue by GreedyWhale** [ant-design/ant-design-pro#8465]
### 🧐 问题描述

1. 使用`yarn create umi`选择v5版本创建项目
2. `yarn start`
3. 控制台出现大量警告

![image](https://user-images.githubusercontent.com/22760464/117909943-a9d22380-b30d-11eb-86ab-d7b143a57c40.png)

如何消除这些警告
### 🚑 其他信息

版本信息

```
"dependencies": {
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@umijs/openapi": "^1.1.14",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/route-utils": "^1.0.36",
    "antd": "^4.14.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.4.0",
    "umi-request": "^1.0.8"
  }
```

**Comment by wumeilian** [comment]
+1，安装proV4版本也是一样出现了这些警告

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/8464

**Comment by chenshuai2144** [comment]
看起来是umi的锅，导致的 react-loadable 的

**Comment by xu-Aurora** [comment]
+1

**Comment by hasnum-stack** [comment]
+1
![image](https://user-images.githubusercontent.com/49703360/118095116-44ac2a00-b402-11eb-8784-a8c3b0592684.png)

**Comment by super20155** [comment]
什么时候解决？？！

**Comment by wanxiankai** [comment]
[8472](https://github.com/ant-design/ant-design-pro/issues/8472)
[8467](https://github.com/ant-design/ant-design-pro/issues/8467)

**Comment by lovachen** [comment]
这个要怎么解决

**Comment by JinShuohang** [comment]
我也出现了同样的错误

**Comment by chenshuai2144** [comment]
等umi修吧 是动态加载的问题

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/8472

**Comment by super20155** [comment]
可以本地自己先修复吗！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题]V5版本项目初始化后，控制台出现大量警告 (#8465)





 
等umi修吧 是动态加载的问题

**Comment by langengel** [comment]
来的时候好好的，回不去了😄

**Comment by langengel** [comment]
> #8472
机智我拷贝之前的node_modules👌

**Comment by ixi** [comment]
+1
无论v4、v5都出现这个问题

**Comment by xieww** [comment]
临时解决办法,替换components下的PageLoading组件为如下代码
```
import React from 'react';
import { Spin } from 'antd';

const PageLoading = () => {
  return (
    <div style={{ paddingTop: 100, textAlign: 'center' }}>
      <Spin size="large"  />
    </div>
  );
};

export default PageLoading;
```

**Comment by wumeilian** [comment]
> 问题原因为@ant-design/pro-layoutzh中PageLoading组件的最近的更新
> ![image](https://user-images.githubusercontent.com/26969239/118766785-7e23e000-b8af-11eb-8cde-4a331d0b23df.png)
> 
> 临时解决办法:
> 第一种：安装@ant-design/pro-layout@6.18.0以下版本；
> 第二种：替换components下的PageLoading组件为如下代码。
> 
> ```
> import React from 'react';
> import { Spin } from 'antd';
> 
> const PageLoading = () => {
>   return (
>     <div style={{ paddingTop: 100, textAlign: 'center' }}>
>       <Spin size="large"  />
>     </div>
>   );
> };
> 
> export default PageLoading;
> ```
第一种方法： 已知"@ant-design/pro-layout": "^6.9.0"也会告警的；
第二种方法可行！

**Comment by ixi** [comment]
V4，有没有解决方案？

**Comment by xieww** [comment]
> > 问题原因为@ant-design/pro-layoutzh中PageLoading组件的最近的更新
> > ![image](https://user-images.githubusercontent.com/26969239/118766785-7e23e000-b8af-11eb-8cde-4a331d0b23df.png)
> > 临时解决办法:
> > 第一种：安装@ant-design/pro-layout@6.18.0以下版本；
> > 第二种：替换components下的PageLoading组件为如下代码。
> > ```
> > import React from 'react';
> > import { Spin } from 'antd';
> > 
> > const PageLoading = () => {
> >   return (
> >     <div style={{ paddingTop: 100, textAlign: 'center' }}>
> >       <Spin size="large"  />
> >     </div>
> >   );
> > };
> > 
> > export default PageLoading;
> > ```
> 
> 第一种方法： 已知"@ant-design/pro-layout": "^6.9.0"也会告警的；具体降级到哪个版本可行待验证。。。
> 第二种方法可行！

我用的是@ant-design/pro-layout@6.17.0，PageLoading的改动是在6.18.0
![image](https://user-images.githubusercontent.com/26969239/118945389-fe1d7900-b987-11eb-9b0f-022542853237.png)

**Comment by youxdd** [comment]
+1

**Comment by Zql-mll** [comment]
+1

**Comment by xykjlcx** [comment]
解决了么？控制台有大量报错。。
