### ISSUE TITLE
 React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element

### ISSUE THREAD

**Issue by YangYuHub** [ant-design/ant-design-pro#8467]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/63183404/117923773-389f6a00-b327-11eb-90ef-974f6d16dc19.png)

### 📷 复现步骤

  1.删除node_modules 
  2.yarn 
  3.yarn start:dev 

### 🏞 期望结果

  希望不会报这个错误

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS]

**Comment by xu-Aurora** [comment]
我也遇到这个问题了，解决了嘛？

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/8465
