### ISSUE TITLE
🐛[BUG]Badge count 为 0 时报错

### ISSUE THREAD

**Issue by flrainbow** [ant-design/ant-design-pro#8468]
### 🐛 bug 描述
<TabPane tab={<Badge count={logerTotal} offset={[10, 0]} showZero>我的待/已处理</Badge>}  key="done">

logerTotal 为 接口获取 的 ，当值为0 时 报错
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {code}). If you meant to render a collection of children, use an array instead.
    in ScrollNumber (created by CSSMotion)
    in DomWrapper (created by CSSMotion)
    in CSSMotion (created by Badge)
    in span (created by Badge)
    in Badge (at MyJob/index.jsx:774)
```

**Comment by chenshuai2144** [comment]
你的 `count={logerTotal}` 输出一下吧，logerTotal 估计变成了一个对象，不是 0 本身
