### ISSUE TITLE
热加载问题

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design-pro#847]
请问为什么在model文件的effects方法里面修改console信息，不会触发热更新，就算触发热更新console信息并不会更新，必须要手动刷新当前网页，这样会造成我对热更新机制的不信任然后每次都会去手动刷新，这样很浪费时间

**Comment by chenshuai2144** [comment]
最好使用devtool工具调试！ 热更新本来就对console 不友好！effects里面更不会执行了

**Comment by firemoon2000** [comment]
目前官方demo中.对于可以编辑表格,输入完一个输入框.移动到下个输入框.或者点击下个输入框时.整个grid就会开始转圈圈.

**Comment by rookie-luochao** [comment]
好的，原来是这样
