### ISSUE TITLE
🧐[问题] 在V5中如何自定义collapsed到头部上方

### ISSUE THREAD

**Issue by liujianchaogit** [ant-design/ant-design-pro#8470]
### 🧐 问题描述

V5使用了antd pro plugin-layout插件来加载pro layout这个组件
但是参数都是app.tsx传递过去得，要如何在头部的按钮来触发菜单的collapsed呢

### 💻 示例代码

export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  const [ collapsed, setCollapsed ] = useState(false)
  return {
    collapsed: collapsed,
    headerContentRender: () => <div onClick={() => setCollapsed(!collapsed)}>自定义collapsed</div>, // **这里会报错因为useState必须使用在组件内部**
}}

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39163696/118082599-0b6abe80-b3f0-11eb-88c3-ee731460407d.png)

**Comment by rayhan999** [comment]
Did you get any solution of this?

**Comment by liujianchaogit** [comment]
```
headerContentRender: (props) => {
      const { collapsed, onCollapse, isMobile } = props
      return (
        <span onClick={() => onCollapse?.(!collapsed)}
              style={{
                cursor: 'pointer',
                fontSize: '20px',
                marginLeft: isMobile ? '16px' : 0
              }}
        >
          { collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined /> }
        </span>
      )
    }
```
