### ISSUE TITLE
🧐[问题] v4混合布局+自动分割菜单 顶部菜单如何设置默认页面

### ISSUE THREAD

**Issue by yongliangliu** [ant-design/ant-design-pro#8471]
### 🧐 问题描述

混合布局+自动分割菜单 顶部菜单如何设置默认页面

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19800207/118097375-301d6100-b405-11eb-9ab9-b36d47fea059.png)
![image](https://user-images.githubusercontent.com/19800207/118097256-08c69400-b405-11eb-97df-45e1f8151524.png)

**Comment by tanyplzu** [comment]
https://github.com/ant-design/ant-design-pro/issues/7805

**Comment by chenshuai2144** [comment]
给 list 配置一下重定向，重定向的一个有 compents 的页面
