### ISSUE TITLE
🐛[BUG] V5 添加模板失败。

### ISSUE THREAD

**Issue by EVOSpider** [ant-design/ant-design-pro#8473]
安装模板失败，更新依赖试过了 没用，清除区块缓存试过了 没用，

![image](https://user-images.githubusercontent.com/84123799/118100084-a53e6580-b408-11eb-818a-eda584bda7c1.png)

或者

![image](https://user-images.githubusercontent.com/84123799/118101151-da978300-b409-11eb-8a9c-8d335d76d560.png)

🚧  Execute task error: Error: Command failed: npm install -d @types/lodash.isequal@^4.5.5 lodash.isequal@^4.5.0 --registry=https://registry.npm.taobao.org --save
undefined
undefined

**Comment by chenshuai2144** [comment]
年久失修了，可能要自己想办法了
