### ISSUE TITLE
我有一个导航的问题需求，不知道如何解决

### ISSUE THREAD

**Issue by lzb-libra** [ant-design/ant-design-pro#8475]
Recently, I am using ant-design-pro v5 to develop a management system, the current style is like this
最近我在使用ant-design-pro v5 开发衣蛾管理系统，现在它大致长这个样子
![image](https://user-images.githubusercontent.com/63389341/118102809-d1a7b100-b40b-11eb-9304-d3664d2adab0.png)
I hope to add a quick navigation bar to the breadcrumb navigation on the right, like this
我现在希望面包屑导航上边增加一个快捷导航，形如这样子
![image](https://user-images.githubusercontent.com/63389341/118103027-087dc700-b40c-11eb-90b6-171bd35224a5.png)
What should i do
我应该怎么做

**Comment by chenshuai2144** [comment]
headerContentRender | 自定义头内容的方法 | (props: BasicLayoutProps) =&gt; ReactNode | -
-- | -- | -- | --


目测只能用这个功能了

**Comment by lzb-libra** [comment]
@chenshuai2144 好的，谢谢，我试一下
