### ISSUE TITLE
Model 里面effects一个方法调用另一个方法

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8476]
向各位老师请教下，
ant design pro 里面一个Model两个effect 方法，这两个方法各自使用都没有问题。
我想在方法二里面处理成功后，再调用下方法一，不知道怎么个写法。
我就直接截个图：

![image](https://user-images.githubusercontent.com/32530210/118135054-257ac000-b435-11eb-957c-b4d7b8f8ca03.png)

还请老师指点下下！

**Comment by xyzabc0004** [comment]
沉下去了!?

**Comment by lishaoh** [comment]
@xyzabc0004 现在是有什么问题吗

**Comment by xyzabc0004** [comment]
我是想在2的yield put完后(报废操作),再调用下Fetch方法1(查下历史),
不知道是怎么个写法.
fetchHmePKNCtainerHisList();
这样空写，不带参数是不行。
或者是
fetchHmePKNCtainerHisList({pknid:33}，{call,put});
??

**Comment by lishaoh** [comment]
就按照你截图上面写的也可以啊，你可以试试以下方法：
1、直接yield put ({
    type: 'fetchHme......',
    payload: {}
})
2、操作state改写数据

**Comment by xyzabc0004** [comment]
我去试下这种。
yield put ({
type: 'fetchHme......',
payload: {}
})

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/118428969-33fdfb80-b703-11eb-8a6c-25b1c64c3807.png)

果然有效果，
我以为，put 只能调用reducers里面写的。
没想到，put也可调用Effect里面写的。
太谢谢了！

**Comment by xyzabc0004** [comment]
又解决了我一个后顾之忧！
