### ISSUE TITLE
ProLayout 导航选择了，不想让其他的子导航关闭，请问如何设置

### ISSUE THREAD

**Issue by azx1985** [ant-design/ant-design-pro#8477]
我有两个导航A和B，我开始选择了A导航，之后我选择B导航的时候，不想让A导航收缩起来，请问如何设置呢？

**Comment by chenshuai2144** [comment]
## menu 
参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
locale | menu 是否使用国际化，还需要 formatMessage 的配合。 | boolean | true
defaultOpenAll | 默认打开所有的菜单项，要注意只有 layout 挂载之前生效，异步加载菜单是不支持的 | boolean | false
type | 菜单的类型 | sub&nbsp;\|&nbsp;group | group
autoClose | 选中菜单是否自动关闭菜单 | boolean | true
loading | 菜单是否正在加载中 | boolean | false
onLoadingChange | 菜单的加载状态变更 | (loading)=&gt;void | -
request | 远程加载菜单的方法，会自动的修改 loading 状态 | (params,defaultMenuDat) =&gt; Promise&lt;MenuDataItem[]&gt;



把 autoClose 设置为 false

**Comment by azx1985** [comment]
在setting里面添加了
export default {
  navTheme: 'light',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'sidemenu',
  contentWidth: 'Fluid',
  fixedHeader: true,
  autoHideHeader: false,
  fixSiderbar: true,
  colorWeak: false,
  menu: {
    autoClose: false,
    locale: true,
  },
  title: '云分析',
  pwa: false,
  iconfontUrl: '//at.alicdn.com/t/font_2083479_udrdpil4ae.js',
};
不能实现

**Comment by Ostaer** [comment]
> 在setting里面添加了
> export default {
> navTheme: 'light',
> // 拂晓蓝
> primaryColor: '#1890ff',
> layout: 'sidemenu',
> contentWidth: 'Fluid',
> fixedHeader: true,
> autoHideHeader: false,
> fixSiderbar: true,
> colorWeak: false,
> menu: {
> autoClose: false,
> locale: true,
> },
> title: '云分析',
> pwa: false,
> iconfontUrl: '//at.alicdn.com/t/font_2083479_udrdpil4ae.js',
> };
> 不能实现

layout下面

export default {
  layout: {
    layout: 'sidemenu',
    menu: {
      autoClose: false,
    },
  }
}

**Comment by flavour-yang** [comment]
改的时候要看一下版本,低版本的不支持
刚开始用 6.5.15版本怎么配置都没用,看了源文件给的类型没有 autoClose
后来更新到6.25.5才有的
