### ISSUE TITLE
正在保存"index.tsx", 正在从 ESLint 获取代码操作 🧐[问题]

### ISSUE THREAD

**Issue by GreatAuk** [ant-design/ant-design-pro#8478]
### 🧐 问题描述

每次保存文件大概率有这个提示，如果这个提示没有消失，`vscode` 会阻止你关闭这个文件。 保存文件，特别是文件改动多的时候，会导致 CPU 使用率上升（明显听到风扇声）。我想知道是什么配置导致了这个提示。

而且 `ESLint` 给出的错误提示（类似下图），就算你把错误修改了，错误提示也要过几秒才会消失，能感觉到明显的延迟，不知道是不是同一个问题
![image](https://user-images.githubusercontent.com/20253809/118216096-6d393000-b4a5-11eb-9b14-258eb11659ef.png)

使用 MBP 15 开发，`vue cli` 和 `create react app` 创建的项目不会有这种问题

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20253809/118213894-68727d00-b4a1-11eb-8203-39fc59b9d3ca.png)

**Comment by xiaohuoni** [comment]
你的 vscode 插件的功能，自己查一下。不确定的话，把插件全关闭了。

**Comment by GreatAuk** [comment]
> 你的 vscode 插件的功能，自己查一下。不确定的话，把插件全关闭了。

确认了下，主要是因为我开启了下面这个配置（保存文件里，根据 `eslint` 规则自动修复）。但是在 `vue` 项目或者 `cra` 创建的项目，同样的配置，并不会产生这个问题
![image](https://user-images.githubusercontent.com/20253809/118293082-df446000-b50b-11eb-81c0-af00f77e04fb.png)

**Comment by xiaohuoni** [comment]
实时修正可能比较耗性能吧？

**Comment by xiaohuoni** [comment]
看看配置文件中，是不是实时编译less 文件的webpack插件开启着？

**Comment by GreatAuk** [comment]
> 看看配置文件中，是不是实时编译less 文件的webpack插件开启着？

配置文件里面没有找到 `less` 关键字

**Comment by GreatAuk** [comment]
这个要一定的代码量才比较容易复现...,所以我没法提供一个复现版本。或者你们自己有用 `umi` 的项目，可以开启这个配置复现下
![image](https://user-images.githubusercontent.com/20253809/118451501-e8aa1400-b727-11eb-8bfc-36f981411d85.png)

**Comment by xiaohuoni** [comment]
这个 `chainWebpack` 配置，注释掉看看有没有帮助。

**Comment by xiaohuoni** [comment]
这个 `chainWebpack` 配置，注释掉看看有没有帮助。

**Comment by GreatAuk** [comment]
我没有定制 `webpack` 的配置，这是我的主要配置
```
export default defineConfig({
  // publicPath: '/test/',
  // base: '/test',
  hash: true,
  antd: {},
  fastRefresh: {},
  // dva: {
    // hmr: true,
  // },
  layout: {
    name: 'Title',
    locale: false,
    siderWidth: 165,
    ...defaultSettings,
  },
  locale: {
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: false,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  externals: {
    echarts: 'window.echarts',
  },
  scripts: [
    {
      src: process.env.NODE_ENV === 'production' ? '/echarts.min.js' : 'https://cdn.bootcdn.net/ajax/libs/echarts/4.8.0/echarts.min.js'
    }
  ],
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    // ...darkTheme,
    'primary-color': defaultSettings.primaryColor,
  },
  // @ts-ignore
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
});
```

**Comment by xiaohuoni** [comment]
注释 fastRefresh: {}, 这个看看

**Comment by GreatAuk** [comment]
> 注释 fastRefresh: {}, 这个看看

一样的

**Comment by xiaohuoni** [comment]
那真是找不到原因了。是不是就是比较卡，要到一定的体量？你说的vue和cra项目不会有这个问题，是不是只是简单demo？这个关掉不行嘛？我们一般是在commit的时候，再校验修正。

**Comment by xiaohuoni** [comment]
我这边都是移动端的项目，都没有特别大的。

**Comment by GreatAuk** [comment]
vue 的体量大多了，也没有这个问题。这个我自己再找找问题，找到问题再反馈下，谢谢了

**Comment by chenshuai2144** [comment]
估计是规则的数量导致的，pro 带的规则比较多还是 ts 的
