### ISSUE TITLE
🧐[问题]umi-plugin-antd-theme 打包出来的主题对引用的图片路径不正确

### ISSUE THREAD

**Issue by DJGDragon** [ant-design/ant-design-pro#8479]
### 🧐 问题描述

在打包dist的时候配置了本地不同的主题，现在有个主题里面的图片路径没有进行编译,导致背景图无法加载

### 💻 示例代码
.mainStyle {
  width: 100vw;
  height: 100vh;
  color: rgb(255, 255, 255);
  background-image: url('../../../assets/img/waf/wafbg.jpg');
  background-repeat: no-repeat;
  background-size: cover;
}

怎么才能让编译的主题样式也是/static/wafbg.81fd989b.jpg

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23696556/118215300-dcae2000-b4a3-11eb-82b6-7c87863b3fc2.png)
![image](https://user-images.githubusercontent.com/23696556/118215329-e768b500-b4a3-11eb-950c-5d5acc75b6cb.png)

**Comment by chenshuai2144** [comment]
background-image: "url('../../../assets/img/waf/wafbg.jpg');

包个字符串，不然 less 没法正确的处理路径
