### ISSUE TITLE
🧐[问题] tableLayout: auto  设置无效

### ISSUE THREAD

**Issue by EVOSpider** [ant-design/ant-design-pro#8481]
Table 下设置了
tableLayout="auto"，

Column 下设置了 
ellipsis: false,

为什么 Table 还是 ：style="table-layout: fixed;"

![image](https://user-images.githubusercontent.com/84123799/118233483-89989500-b4c4-11eb-9921-8600f16cc18c.png)
![image](https://user-images.githubusercontent.com/84123799/118233582-ab921780-b4c4-11eb-88b0-1cb4e7117900.png)
![image](https://user-images.githubusercontent.com/84123799/118233621-b8af0680-b4c4-11eb-87ed-0fa01117b4f5.png)

**Comment by chenshuai2144** [comment]
去 antd 问问吧，这种的一般是在什么地方 ...props 导致覆盖了
