### ISSUE TITLE
🐛[BUG]发布之后404界面无法展示。

### ISSUE THREAD

**Issue by dong136279559** [ant-design/ant-design-pro#8484]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.5.0]
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
你配置了try file了吧

**Comment by dong136279559** [comment]
额，没有设置，那我设置一下Ng试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 ***@***.***&gt;
发送时间: 2021年5月16日 21:28
收件人: ant-design/ant-design-pro ***@***.***&gt;
抄送: dong136279559 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ant-design/ant-design-pro] ��[BUG]发布之后404界面无法展示。 (#8484)





 
你配置了try file了吧

**Comment by dong136279559** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/20337504/118584102-cf0cd900-b7c8-11eb-835a-94ec574acabf.png">
您好，我配置了try file 之后，还有一些问题，我们是在同一个域名下，有两个项目，访问路径 一个为 /   另一个为 /admin/ 。但是admin 项目 访问错误的地址时，会跳转到 / 项目的登录界面，请问，这个问题如何解决呢？求解

**Comment by chenshuai2144** [comment]
提升一下 nginx 的优先级。

~ 表示执行一个正则匹配，区分大小写
~* 表示执行一个正则匹配，不区分大小写
^~ 表示普通字符匹配。使用前缀匹配。如果匹配成功，则不再匹配其他location。
= 进行普通字符精确匹配。也就是完全匹配。
@ "@" 定义一个命名的 location，使用在内部定向时，例如 error_page, try_files
/ 通用匹配, 如果没有其它匹配,任何请求都会匹配到

第一优先级：等号类型（=）的优先级最高。一旦匹配成功，则不再查找其他匹配项。
第二优先级：^~类型表达式。一旦匹配成功，则不再查找其他匹配项。
第三优先级：正则表达式类型（~ ~*）的优先级次之。如果有多个location的正则能匹配的话，则使用正则表达式最长的那个。
第四优先级：常规字符串匹配类型。按前缀匹配。
