### ISSUE TITLE
ant-design-pro v4 JavaScript simple出现大量警告🐛[BUG]

### ISSUE THREAD

**Issue by LiucyLink** [ant-design/ant-design-pro#8485]
### 🐛 bug 描述

使用npm create umi 创建的ant-design-pro v4 JavaScript simple项目出现大量警告

### 📷 复现步骤

1. npm create umi
2. npm install 
3. 控制台出现大量警告

### 🏞 期望结果

原始版本并不会出现这个错误,当前创建的项目会出现这个问题,希望能够解决.

### © 版本信息

"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.15.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^16.14.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.4.1",
    "umi-request": "^1.0.8"
  },

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/51821873/118254576-d341a980-b4dd-11eb-98e9-2909acea915c.png)
![image](https://user-images.githubusercontent.com/51821873/118254638-e18fc580-b4dd-11eb-9392-1be7a326db4c.png)

**Comment by qctxzwq** [comment]
我也遇到了同样的问题，请问现在有好的解决方案了吗？@LiucyLink

**Comment by chenshuai2144** [comment]
重复了，等umi修复吧
