### ISSUE TITLE
请问fetch如何添加超时处理

### ISSUE THREAD

**Issue by yumengqin** [ant-design/ant-design-pro#849]

**Comment by rookie-luochao** [comment]
网上有promise all版本的

**Comment by rookie-luochao** [comment]
但是我是使用的axios，自带超时处理，扩展性也好点

**Comment by yumengqin** [comment]
dva脚手架生成的项目自带的fetch 您是自己安装的axios吗 还是dva中包含axios我没发现呀

**Comment by rookie-luochao** [comment]
自己安装的axios，fetch库在dva中依赖了，但不是强依赖，只是选择性依赖，所以你完全可以根据自己的习惯和需求选择axios还是fetch，并不会存在http库重复的情况

**Comment by rookie-luochao** [comment]
当然你如果喜欢用fetch，你可以google一下fetch如何添加超时处理，但是fetch本身应该没有提供超时处理的配置，你可以再看看

**Comment by yumengqin** [comment]
好的 了解了 谢谢啦
