### ISSUE TITLE
🐛[BUG] 服务器获取菜单登录页面错误

### ISSUE THREAD

**Issue by mrcwl** [ant-design/ant-design-pro#8490]
### 🐛 bug 描述

服务器获取菜单访问登录页面会嵌套到layout中

![image](https://user-images.githubusercontent.com/26196131/118466276-46912880-b735-11eb-9d24-53c10c43c0a3.png)

### 🏞 期望结果

登录页面正常显示

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本: 2.7.7
- 浏览器环境: chrome
- 开发环境 :mac OS

**Comment by chenshuai2144** [comment]
```
 {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './user/Login',
          },
        ],
      },
    ],
  },
```

你的 layout:false 是不是忘记配置了

**Comment by mrcwl** [comment]
> ```
>  {
>     path: '/user',
>     layout: false,
>     routes: [
>       {
>         path: '/user',
>         routes: [
>           {
>             name: 'login',
>             path: '/user/login',
>             component: './user/Login',
>           },
>         ],
>       },
>     ],
>   },
> ```
> 
> 你的 layout:false 是不是忘记配置了

是用的是约定式配置没有routes

**Comment by chenshuai2144** [comment]
那就麻烦了，你可能要判断一下 pathname 是 user 开头的，在 app.tsx 里的 layout 中配置  prue : ture
