### ISSUE TITLE
项目跑不起来报错，请求帮助。

### ISSUE THREAD

**Issue by 13250515751** [ant-design/ant-design-pro#8491]
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'snapshot'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by chenshuai2144** [comment]
应该是 webpack v4 和 v5 的版本冲突问题

**Comment by 13250515751** [comment]
我现在用的webpack5，是不是不兼容？webpack那个版本合适呢？

**Comment by 13250515751** [comment]
PS E:\react\ant-design-pro-master> webpack -v
webpack 4.46.0
webpack-cli 4.7.0

**Comment by chenshuai2144** [comment]
现在 umi 内置了 webpack，你使用webpack 做什么？

**Comment by 13250515751** [comment]
之前vue2.0项目需要用来打包

**Comment by chenshuai2144** [comment]
emmm, 你把 umi 的 webpack5 的配置关掉吧，混用 webpack 还是比较危险的

**Comment by 13250515751** [comment]
大佬，我现在需要怎么配置才能把项目跑起来？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts

试着打开 webpack 的配置，或者把你的 package.json 里面的 webpack 删掉，然后重新安装依赖

**Comment by 13250515751** [comment]
好的，我试一下

**Comment by 13250515751** [comment]
package.json删除webpack配置，卸载node_modules， 重新安装依赖，还是跑不起来，报同样的错误。

**Comment by 13250515751** [comment]
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'snapshot'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by 13250515751** [comment]
已全局删除webpack

**Comment by chenshuai2144** [comment]
删除之后更新依赖就可以跑起来了
