### ISSUE TITLE
好难用的框架

### ISSUE THREAD

**Issue by nanhaibo** [ant-design/ant-design-pro#8493]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hemengke1997** [comment]
1. 这是免费开源的
2. 觉得难用可以提出哪些地方难用，怎么去优化难用的地方
3. 一个猜想，不一定对，有没有可能是你不会用呢？

**Comment by chenshuai2144** [comment]
开源项目要有手才能用的
