### ISSUE TITLE
🐛[BUG] umi 3.4.15 之后的版本 无法 启动 dev，卡在99%

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8494]
### 🐛 bug 描述

umi 3.4.16 就开始报错

D:\Web\console>npm run dev

console@0.0.64 dev D:\Web\console
npm run start:dev

console@0.0.64 start:dev D:\Web\console
cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev

Bundle with webpack 5...
Starting the development server...

× Webpack
Compiled with some errors in 1.03m

ERROR Failed to compile with 22 errors 上午8:41:07

error in ./node_modules/@babel/runtime/helpers/esm/createSuper.js

Module not found: Error: Can't resolve './getPrototypeOf' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'getPrototypeOf.js'?
BREAKING CHANGE: The request './getPrototypeOf' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/createSuper.js

Module not found: Error: Can't resolve './isNativeReflectConstruct' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'isNativeReflectConstruct.js'?
BREAKING CHANGE: The request './isNativeReflectConstruct' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/createSuper.js

Module not found: Error: Can't resolve './possibleConstructorReturn' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'possibleConstructorReturn.js'?
BREAKING CHANGE: The request './possibleConstructorReturn' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/get.js

Module not found: Error: Can't resolve './superPropBase' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'superPropBase.js'?
BREAKING CHANGE: The request './superPropBase' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/inherits.js

Module not found: Error: Can't resolve './setPrototypeOf' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'setPrototypeOf.js'?
BREAKING CHANGE: The request './setPrototypeOf' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/objectSpread.js

Module not found: Error: Can't resolve './defineProperty' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'defineProperty.js'?
BREAKING CHANGE: The request './defineProperty' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/objectSpread2.js

Module not found: Error: Can't resolve './defineProperty' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'defineProperty.js'?
BREAKING CHANGE: The request './defineProperty' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/objectWithoutProperties.js

Module not found: Error: Can't resolve './objectWithoutPropertiesLoose' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'objectWithoutPropertiesLoose.js'?
BREAKING CHANGE: The request './objectWithoutPropertiesLoose' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js

Module not found: Error: Can't resolve '../../helpers/esm/typeof' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'typeof.js'?
BREAKING CHANGE: The request '../../helpers/esm/typeof' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js

Module not found: Error: Can't resolve './assertThisInitialized' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'assertThisInitialized.js'?
BREAKING CHANGE: The request './assertThisInitialized' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/slicedToArray.js

Module not found: Error: Can't resolve './arrayWithHoles' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'arrayWithHoles.js'?
BREAKING CHANGE: The request './arrayWithHoles' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/slicedToArray.js

Module not found: Error: Can't resolve './iterableToArrayLimit' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'iterableToArrayLimit.js'?
BREAKING CHANGE: The request './iterableToArrayLimit' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/slicedToArray.js

Module not found: Error: Can't resolve './unsupportedIterableToArray' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'unsupportedIterableToArray.js'?
BREAKING CHANGE: The request './unsupportedIterableToArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/slicedToArray.js

Module not found: Error: Can't resolve './nonIterableRest' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'nonIterableRest.js'?
BREAKING CHANGE: The request './nonIterableRest' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toArray.js

Module not found: Error: Can't resolve './arrayWithHoles' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'arrayWithHoles.js'?
BREAKING CHANGE: The request './arrayWithHoles' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toArray.js

Module not found: Error: Can't resolve './iterableToArray' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'iterableToArray.js'?
BREAKING CHANGE: The request './iterableToArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toArray.js

Module not found: Error: Can't resolve './unsupportedIterableToArray' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'unsupportedIterableToArray.js'?
BREAKING CHANGE: The request './unsupportedIterableToArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toArray.js

Module not found: Error: Can't resolve './nonIterableRest' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'nonIterableRest.js'?
BREAKING CHANGE: The request './nonIterableRest' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toConsumableArray.js

Module not found: Error: Can't resolve './arrayWithoutHoles' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'arrayWithoutHoles.js'?
BREAKING CHANGE: The request './arrayWithoutHoles' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toConsumableArray.js

Module not found: Error: Can't resolve './iterableToArray' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'iterableToArray.js'?
BREAKING CHANGE: The request './iterableToArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toConsumableArray.js

Module not found: Error: Can't resolve './unsupportedIterableToArray' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'unsupportedIterableToArray.js'?
BREAKING CHANGE: The request './unsupportedIterableToArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

error in ./node_modules/@babel/runtime/helpers/esm/toConsumableArray.js

Module not found: Error: Can't resolve './nonIterableSpread' in 'D:\Web\console\node_modules@babel\runtime\helpers\esm'
Did you mean 'nonIterableSpread.js'?
BREAKING CHANGE: The request './nonIterableSpread' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '.mjs' file or a '.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

Webpack █████████████████████████ done (99%)
plugins

- **Umi Version**: 3.4.16
- **Node Version**:  14.17.0
- **Platform**: ant design pro

**Comment by a958330481** [comment]
遇到同一个问题？解决了吗？

**Comment by chenshuai2144** [comment]
@a958330481 core.js 的问题，清空缓存重新安装即可
