### ISSUE TITLE
👑 [需求]ant design pro v5编译的速度太慢了

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#8496]
### 🥰 需求描述

ant design pro v5现在编译的速度太慢了，现在不提供dll提速了吗？配置项中看没有

**Comment by drizzlesconsin** [comment]
可以考虑开启 [webpack5](https://umijs.org/config#webpack5)

```diff
# config/config.ts
+ webpack5: {},
```

**Comment by liucong1** [comment]
+1

**Comment by ideaviewes** [comment]
@drizzlesconsin @liucong1 谢谢，配置webpack5后好了很多。
