### ISSUE TITLE
最新pro编译后生成多个前端资源文件怎么使用

### ISSUE THREAD

**Issue by EvanYin** [ant-design/ant-design-pro#8497]
最新的pro工程在编译之后会生成很多前端资源文件，每个页面都会有自己的资源文件：
![image](https://user-images.githubusercontent.com/8558105/118748922-25dce600-b88f-11eb-9727-a5871ca9e7a0.png)
后端vm文件里面只引用umi.js和umi.css：
![image](https://user-images.githubusercontent.com/8558105/118749062-5f155600-b88f-11eb-8d92-2d92cb495b47.png)
![image](https://user-images.githubusercontent.com/8558105/118749078-676d9100-b88f-11eb-8850-cfaddaef0899.png)
因为前端资源文件不是保存在服务器static下，而是cdn服务器上面，导致访问页面的时候，页面对应的前端资源文件请求不到：
![image](https://user-images.githubusercontent.com/8558105/118749229-ac91c300-b88f-11eb-8f43-27bc9b61fd01.png)

谁能帮忙回答下怎么处理，谢谢～

**Comment by chenshuai2144** [comment]
内部系统，找期贤私聊一下
