### ISSUE TITLE
🧐[问题] 固定header模式，可否滚动条仅限conten区域滚动

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8498]
### 🧐 问题描述

固定header模式，可否滚动条仅限conten区域滚动

![QQ浏览器截图20210519170516](https://user-images.githubusercontent.com/3166799/118786627-97835700-b8c4-11eb-9891-868b2549f2eb.png)

**Comment by chenshuai2144** [comment]
fixedHeader | 是否固定 header 到顶部 | boolean | false
-- | -- | -- | --



配置这个

**Comment by hihuangwei** [comment]
我的意思是  仅在内容区域滚动，而不是整个body 滚动
![image](https://user-images.githubusercontent.com/3166799/119248885-bfc1cd00-bbc6-11eb-8c18-165d3a3498f4.png)

**Comment by chenshuai2144** [comment]
用css 覆盖一下，如果滚动条不在body上，会导致select 浮动的问题。
