### ISSUE TITLE
🧐[问题]Proxy如何配置全局代理，代码里嵌套了第三方服务iframe,地址/***不确定，proxy是否有代理全局请求的写法？

### ISSUE THREAD

**Issue by RayWar** [ant-design/ant-design-pro#8499]
### 🧐 问题描述

正式环境有nginx代理，本地服务调试如何配置？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31884707/118910450-0a3d1280-b957-11eb-8614-9b4a0f083fad.png)

**Comment by chenshuai2144** [comment]
https://github.com/chimurai/http-proxy-middleware

看这里，里面是个正则
