### ISSUE TITLE
antd pro 怎么搞到局域网使用，不会连到公网。

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design-pro#850]
index.ejs 中的 `<body>
  <div id="root"></div>
  <script src="https://gw.alipayobjects.com/as/g/??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js"></script>
</body>` 我试了好几种方式，都不好用。另外 还有官网antd 里面的 Icon 也是要连网使用的。

**Comment by ddcat1115** [comment]
你可以下载下来发到自己的局域网再引用，icon可以本地化部署，[参考文档](https://ant.design/components/icon-cn/#%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)

**Comment by chenshuai2144** [comment]
https://gw.alipayobjects.com 是我们的cdn，你可以用自己的替换。

**Comment by wunayou** [comment]
这个东西作用是什么？

**Comment by chenshuai2144** [comment]
[cdn](https://www.zhihu.com/question/37353035)吗？

**Comment by wunayou** [comment]
这个 链接 ttps://gw.alipayobjects.com/as/g/??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js

**Comment by chenshuai2144** [comment]
你可以直接给你本地服务器copy一份
