### ISSUE TITLE
build 后生成vendors~ 前缀的压缩文件跟在nginx里 vendors路由会有冲突的问题导致页面不能正常访问🐛[BUG]

### ISSUE THREAD

**Issue by niming175** [ant-design/ant-design-pro#8502]
### 🐛 bug 描述

build后，会生成`vendors~.....js`的文件， 而我的项目是laravel + antPro, 部分文件是需要访问laravel的文件的，所以在nginx配置里有条指向后端的路由
```conf
location /vendor { 
  try_files $uri $uri/ /index.php$is_args$args;
}
```
而`vendors~` 会被识别到，其中~表示不区分大小写， 因而导致相关文件加载失败，（按理说还有个s, 应该不会被识别到才对）， 因而卡在loading状态

### 📷 复现步骤

build后再dist文件夹下可见`vendors~`前缀的文件

### 🏞 期望结果
编译后，可以用下划线替代波浪线

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26159724/118932319-7e3ce200-b97a-11eb-86d3-6f29bc54135d.png)
![image](https://user-images.githubusercontent.com/26159724/118932427-9f053780-b97a-11eb-9aea-affe4fcc622a.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/config#dynamicimport

直接关掉这个吧，我觉得不是 nginx 的问题。`location /vendor ` 只会匹配 /vendor/xxxx

你其实可以这样配置：

```
 location ~ \.(mp4|css|png|js|ico|zip|svg|ttf|htm)$ {
            root /usr/local/var/dist/;
        }

```
