### ISSUE TITLE
🧐[问题] Menu导航菜单在切换到复杂页面时候有明显卡顿，如何在切换时添加Loading状态？

### ISSUE THREAD

**Issue by leex90** [ant-design/ant-design-pro#8503]
### 🧐 问题描述

Menu导航菜单在切换到复杂页面时候有明显卡顿，如果是第一次切换到复杂页面，页面有loading态，但是后面再次点击菜单切换到复杂页面，菜单有明显卡顿，页面渲染也不及时

由于是复杂页面，卡顿能理解，但是可以加个loading状态体验更好，如何能在点击菜单切换页面的时候，每次都加一个loading态，页面加载完了再显示呢？

### 💻 示例代码

Reproduction link
https://preview.pro.ant.design/dashboard/analysis

由其他页面跳转到“监控页”，即点击“监控页”

### 🚑 其他信息
演示卡顿动画

![74100449-f1e22380-4b69-11ea-89c6-ab6bdc81c054](https://user-images.githubusercontent.com/2292217/118985846-659bee80-b9b1-11eb-91e8-7f382ecd4109.gif)

**Comment by chenshuai2144** [comment]
在具体的页面解决问题吧，比如延迟加载图表之类的。

框架来解决会导致兼容性问题，可能会导致某些页面重复渲染

**Comment by leex90** [comment]
@chenshuai2144 可以给个思路么？试了很多方法不知道怎么在页面解决问题，页面已经尽量精简了，但是切换到页面的时候还是会有明显的卡顿，怎样在切换的过程中加一个pageloading呢？

**Comment by chenshuai2144** [comment]
```
const [loading,setLoading] = useState(true);

useEffect(()=>{
   setTimeout(()=>setLoading(false),2000)
},[])

if(loading) return null
```
