### ISSUE TITLE
🧐[问题]Antd config.ts layout 中的name如何支持I18n?

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/ant-design-pro#8504]
Antd layout 中的name如何支持I18n?
// file: config.ts
layout: {
name: "Auto ML", // 这里需要I18n
locale: true,
siderWidth: 208,
},

**Comment by chenshuai2144** [comment]
https://beta-pro.ant.design/config/runtime-api-cn#layout

// app.tsx

```tsx
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
   return {name:formartMessage({id:"xxx"}) }
}
```
