### ISSUE TITLE
🐛[BUG] V5 执行 npm update 将导致依赖丢失

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8508]
### 🐛 bug 描述

V5 执行 npm update 将导致依赖丢失

**Comment by chenshuai2144** [comment]
祥细描述一下？具体缺了什么

**Comment by hihuangwei** [comment]
![image](https://user-images.githubusercontent.com/3166799/119249139-f00a6b00-bbc8-11eb-8e72-b7fcbd1533b0.png)
![image](https://user-images.githubusercontent.com/3166799/119249152-f8fb3c80-bbc8-11eb-85ba-974cd2853c2e.png)

**Comment by chenshuai2144** [comment]
太不清晰了，再写个 issue 吧
你丢了什么
