### ISSUE TITLE
项目本地build正常，服务器上build报错，寻求大家的帮助

### ISSUE THREAD

**Issue by zengyuju0324** [ant-design/ant-design-pro#8509]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/data/node-v12.14.0-linux-x64/bin/node',
1 verbose cli   '/data/node-v12.14.0-linux-x64/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.2.1~prebuild: ant-design-pro@2.2.1
6 info lifecycle ant-design-pro@2.2.1~build: ant-design-pro@2.2.1
7 verbose lifecycle ant-design-pro@2.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.2.1~build: PATH: /data/node-v12.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/jenkins/jobs/dataMonitor-ui/workspace/node_modules/.bin:/data/node-v12.14.0-linux-x64/bin:/opt/java/jdk1.8.0_231/bin:/sbin:/usr/sbin:/bin:/usr/bin
9 verbose lifecycle ant-design-pro@2.2.1~build: CWD: /data/jenkins/jobs/dataMonitor-ui/workspace
10 silly lifecycle ant-design-pro@2.2.1~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.2.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.2.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.2.1 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/data/node-v12.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/data/node-v12.14.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid ant-design-pro@2.2.1
15 verbose cwd /data/jenkins/jobs/dataMonitor-ui/workspace
16 verbose Linux 3.10.0-1062.9.1.el7.x86_64
17 verbose argv "/data/node-v12.14.0-linux-x64/bin/node" "/data/node-v12.14.0-linux-x64/bin/npm" "run" "build"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.2.1 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by zengyuju0324** [comment]
已经解决，

**Comment by chenshuai2144** [comment]
问题可以抛出来，让大家都找找

**Comment by jaredwu** [comment]
我也遇到了这个问题，请教下什么解决方法
