### ISSUE TITLE
clone项目代码后run test提示TypeError: environment.dispose is not a function

### ISSUE THREAD

**Issue by stringStar** [ant-design/ant-design-pro#851]
![image](https://user-images.githubusercontent.com/24769809/35603313-cb298636-0677-11e8-8cb1-536a05e61659.png)
查看了网上一些消息说需要全局安装jest，测试后无效，求帮助

**Comment by sorrycc** [comment]
在 umi-test@0.3.4 里修复了，删除 node_modules 后重装试试。

**Comment by sorrycc** [comment]
只在某些机器下会出现这个。

**Comment by stringStar** [comment]
@sorrycc 谢谢，已经能跑起来了
