### ISSUE TITLE
👑 [需求]请问怎么懒加载组件？

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design-pro#8510]
做了两个布局模板layout

一套是给未登录用的，一套是给登录用的

请问pro是否已经处理了懒加载，还是自己需要如何配置呢

**Comment by chenshuai2144** [comment]
https://umijs.org/config#dynamicimport

你需要的是这个吧

**Comment by birdycn** [comment]
> https://umijs.org/config#dynamicimport
> 
> 你需要的是这个吧，pro 已经自带了

所以不需要额外配置了吗
