### ISSUE TITLE
如何使用Dockerfile进行build

### ISSUE THREAD

**Issue by guoziqin** [ant-design/ant-design-pro#8512]
### 🐛 bug 描述
我在build的时候出现了各种error(not found umi) ，我看到dockerfile的更新已经是两年前了 

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ammits** [comment]
Yes, I got bug in docker build too. I noticed that user components are incorrectly referred in config/config.js file. For login, component path is correctly referred as User/login but for register and and register-result the "u" in user is lowercase. @chenshuai2144

**Comment by chenshuai2144** [comment]
fixed
