### ISSUE TITLE
Form 下TreeSelect  怎么不默认选中其中一项呢,而input加载了一个数字

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8514]
![image](https://user-images.githubusercontent.com/32530210/119266842-f9262700-bc1e-11eb-8a3a-f95f7eafd8d8.png)

![image](https://user-images.githubusercontent.com/32530210/119266911-3a1e3b80-bc1f-11eb-900a-86a96b4551de.png)

![image](https://user-images.githubusercontent.com/32530210/119266943-5a4dfa80-bc1f-11eb-8c09-67b3a49ce50e.png)

还请各位老师指点下!!!

**Comment by chenshuai2144** [comment]
放到 form 中 value 就被 form 控制了，所以你写了没用

你用 initialvalues 来处理默认值吧

**Comment by xyzabc0004** [comment]
我试哈看。

**Comment by xyzabc0004** [comment]
废了九牛二虎之力，终于
还是没有弄出来，
想投降么
