### ISSUE TITLE
ant-design-pro 1.0版以后加载页面的问题

### ISSUE THREAD

**Issue by denggy** [ant-design/ant-design-pro#852]
我发现至从1.0的版本以后 首次点击菜单后 加载页面样式不一样了
1.0版本之前点击菜单加载页面 效果如下图
![loading](https://user-images.githubusercontent.com/3114067/35608705-2e6950a6-0695-11e8-9090-2ff30c49726e.jpg)
就是首次 加载的页面都会有这个 loading的效果  之后 就不会再有了

1.0版本之后 点击菜单加载 页面 效果如下图
![normal](https://user-images.githubusercontent.com/3114067/35608732-4c9beb24-0695-11e8-842e-30651d670c30.jpg)
感觉1.0版本之后 首次点击菜单 直接加载的是页面的数据 没有组件loading的那种感觉

PS:最奇怪是1.0版本之后 只有“监控页面”这个菜单首次点击 有那个loading的效果  其他全无
感觉好奇怪！ 
以上  求大佬们给个答复！

**Comment by longzhaobi** [comment]
上面那个图的loading是正在加载组件，相当于正在按需引入js，如果不这样弄，网络不好的时候就空白页体验不好，所以有个loading表示正在加载组件，这个是dva2.0提供的功能，如果你加载过了那就直接显示组件，下面这个loading状态，是antd提供的功能，表示正在请求数据。

**Comment by chenshuai2144** [comment]
@denggy  因为我们关掉了代码分割。

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD
