### ISSUE TITLE
🐛[BUG] 路由配置  layout: false  ProLayout 挂载 2次

### ISSUE THREAD

**Issue by bashan1884** [ant-design/ant-design-pro#8520]
### 🐛 bug 描述

在页面中不需要左侧边栏，将 路由中的布局组件 layout: false，ProLayout 挂载 2次，页面组件 useEffect 执行 2次。
将 layout: true 时 ProLayout 挂载 1次，页面组件 useEffect 执行 1次

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/15899941/119483410-85ebf480-bd87-11eb-8e3d-a836e86c4355.png)

**Comment by chenshuai2144** [comment]
@https://github.com/xiefengnian

**Comment by Macrow** [comment]
一样遇到这个问题，期待解决。
