### ISSUE TITLE
When click on the components tabs menu tabs also popup

### ISSUE THREAD

**Issue by beeena** [ant-design/ant-design-pro#8521]
### 🐛 bug 描述

When Click on the antd component tabs it also popup on the menu tabs.

![image](https://user-images.githubusercontent.com/38552626/119486674-f2f48f80-bd71-11eb-99b0-2f89eabf37d3.png)

### 📷 复现步骤

In my case, I have used a popup menu I don't want to active menu popup where are the ant tab component is active.
![image](https://user-images.githubusercontent.com/38552626/119487001-51217280-bd72-11eb-8368-345c1dac67c1.png)

**Comment by chenshuai2144** [comment]
router ： `/list/search/:id`
`/list/search/projects`

**Comment by veeramarni** [comment]
@chenshuai2144 Can you please describe what properties need to be tweaked to avoid menu selection or popup? By default based on the route page, menu item get triggered and we don't want that for `User` Menu.
