### ISSUE TITLE
V4 动态菜单 怎么总是显上次state的菜单数据。

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8522]
![image](https://user-images.githubusercontent.com/32530210/119523116-1558ce00-bdaf-11eb-8749-7ebbf84e3182.png)
![image](https://user-images.githubusercontent.com/32530210/119523657-826c6380-bdaf-11eb-89c2-da5e02771aac.png)
![image](https://user-images.githubusercontent.com/32530210/119523658-826c6380-bdaf-11eb-979e-21ddae72b6f1.png)

第一次登，state菜单为空，进去空菜单，state有值，
第二次再登，菜单出现。
第三次换用户再登，菜单用的还是二次state的值

**Comment by xyzabc0004** [comment]
还请老师们指点下！

**Comment by chenshuai2144** [comment]
用request 的把，menuRender 不是每次都执行的

https://beta-pro.ant.design/docs/advanced-menu-cn

**Comment by xyzabc0004** [comment]
OK! 好是好，就是有点难消化

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/119680447-c5900a80-be73-11eb-9c9e-7b02b23475c9.png)

![image](https://user-images.githubusercontent.com/32530210/119680539-db9dcb00-be73-11eb-9c5a-eaf24ba6280a.png)

![image](https://user-images.githubusercontent.com/32530210/119680629-f2dcb880-be73-11eb-8b72-d573abe5e193.png)

经过我的N次测试，感觉这个办法可以。
用户第一个登陆的请求login，成功后，直接把可以访问的菜单信息，在第一次请求都返回回来。
pro 拿到response 放到localstroage里面，
然后在pagelayout直接取出来用。

刚测试了几次，感觉没有多大的问题。

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/119684358-06d5e980-be77-11eb-8127-22fb7494c10f.png)


基本上抄完美了。
