### ISSUE TITLE
🧐[问题]proTable更新表单也按照新建表单的写法，应该怎么赋初始值呀

### ISSUE THREAD

**Issue by diaomina** [ant-design/ant-design-pro#8525]
### 🧐 问题描述

proTable更新表单也按照新建表单的写法，应该怎么赋初始值呀
antd pro v5

### 💻 示例代码

表格的index.tsx内

![image](https://user-images.githubusercontent.com/40923075/119593986-8d55e100-be0d-11eb-8f29-465969236a8c.png)

**Comment by diaomina** [comment]
可否通过该配置进行编辑时表单的数据初始化，如果可以的话，请问该配置应该如何写o(╥﹏╥)o
![image](https://user-images.githubusercontent.com/40923075/119596575-05bea100-be12-11eb-829d-11ca2897048b.png)

**Comment by a401554998** [comment]
你可以看例子啊，protable 里面有data，你直接填充数据就可以了嘛，把官方的例子下载下来，多的是，或者你看antd的例子 里面也是有的

**Comment by chenshuai2144** [comment]
```
form={
 initialvalues: {}
}
```
