### ISSUE TITLE
🧐[问题]点击菜单或切换路由时，网站的标题(title)为啥会动态变化？怎么控制不变，始终显示 XX系统

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#8526]

**Comment by lishaoh** [comment]
直接在路由切换时用document.title = 'xx系统'控制就好了

**Comment by chenshuai2144** [comment]
pageTitleRender | 自定义页面标题的显示方法 | (props: BasicLayoutProps) =&gt; ReactNode | -
-- | -- | -- | --
