### ISSUE TITLE
🧐[问题]组件钟models文件夹中定义的model，之前usemodel（“文件名字”），现在突然要写成（“文件路径 . [如果是models文件夹省略] .文件名字”）这样的形式。

### ISSUE THREAD

**Issue by MrArky** [ant-design/ant-design-pro#8527]
如题：
src
|-----page
|-------CRM
|---------Customer
|-------------models
|----------------CustomerModel.ts

以前的引用方式：
const { 状态基 } = useModel("CustomerModel");
现在的方式：
const { 状态基 } = useModel("CRM.Customer.CustomerModel");
这个是什么原因造成的？现在团队成员拉取了我的代码，两边不一样，导致后者报错，无法运行。

在生成的.umi/plugin-model/Provider里面也可以看到两边代码确实不一样，一个带路径，一个不带路径。

求指教。

**Comment by chenshuai2144** [comment]
估计是代码更新了，去umi问问插件是不是又修改。


const { 状态基 } = useModel("CRM.Customer.CustomerModel");    感觉这种合理一点，不然很容易重复

**Comment by MrArky** [comment]
> 估计是代码更新了，去umi问问插件是不是又修改。
> 
> const { 状态基 } = useModel("CRM.Customer.CustomerModel"); 感觉这种合理一点，不然很容易重复

是的，确实是更新了，第二种方式我也认为更合理。以前完全通过文件名唯一性编程这一点也不现代，通过命名空间来做约定性就不再那么强了。
