### ISSUE TITLE
🐛[BUG] 使用 npm run i18n-remove 移除国际化后，menu无法显示中文。

### ISSUE THREAD

**Issue by DeyuanTan** [ant-design/ant-design-pro#8528]
使用 npm run i18n-remove 移除国际化后，menu无法显示中文。

### 📷 复现步骤

1、初始化项目
2、执行 npm run i18n-remove 并删除 src/locales 中除 zh-CN 以外语言文件
3、修改config.ts。相关配置如下
![image](https://user-images.githubusercontent.com/8966624/119633793-ab8b0380-be44-11eb-8f93-d5b204f48b5f.png)
4、执行 npm start 预览页面。使用admin登录，结果如下

![image](https://user-images.githubusercontent.com/8966624/119634190-10def480-be45-11eb-98da-b2f907b955d2.png)

### 🏞 期望结果

左侧菜单显示中文。

### 💻 复现代码

--

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本  v3
- 浏览器环境 chrome
- 开发环境 mac OS

### 🚑 其他信息

app.tsx中配置了 menu: { locale: false } 也不行。
![image](https://user-images.githubusercontent.com/8966624/119634533-6c10e700-be45-11eb-9961-03220fd559a9.png)

**Comment by chenshuai2144** [comment]
你需要修改一下name的，router.ts 里面配置
