### ISSUE TITLE
判断要改下🐛[BUG]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8531]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/27960630/119755249-4848b200-bed4-11eb-9dba-0d2b5fca60a8.png)
![image](https://user-images.githubusercontent.com/27960630/119755137-1899aa00-bed4-11eb-877c-c6dc27f45dc9.png)
![image](https://user-images.githubusercontent.com/27960630/119755158-20f1e500-bed4-11eb-9d02-2c022acc3a0a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lovesL** [comment]
我倒是自己解决了这个报错 但我觉得menuRender应该还是处理一下 
![image](https://user-images.githubusercontent.com/27960630/119757208-36b4d980-bed7-11eb-8e01-c8ed8e8ee839.png)  这么写不会报错

**Comment by chenshuai2144** [comment]
是true 就给个 undfinded
