### ISSUE TITLE
🐛[BUG] 我设置了路由目录和菜单，但是没有展示箭头

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-pro#8532]
### 🐛 bug 描述

我在页面设置设置了一级目录，然后配置了一个菜单，然后给菜单在配置一个菜单，然而目录没有展示二级的箭头

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/33271366/119761455-661b1480-bede-11eb-805f-4d8c7c03f924.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
我感觉是你魔改 less 改的太厉害了，这个菜单我都看不出来是antd 了，顺便看看key是不是重复了
