### ISSUE TITLE
🧐[问题] antd pro v5 路由配置当path为'/'时，layout: false未生效

### ISSUE THREAD

**Issue by z384647062** [ant-design/ant-design-pro#8533]
### 🧐 问题描述

在routes.ts中添加路由配置：
```typescript
{
  path: '/',
  layout: false,
  component: './index'
}
```
访问后 `/` 页仍然有布局，`layout false` 未生效：
![image](https://user-images.githubusercontent.com/36412883/119792742-865fc900-bf08-11eb-9316-87a415c879fc.png)

但是将path改为非 `/` 后：
```typescript
{
  path: '/index',
  layout: false,
  component: './index'
}
```
访问后 `/index` 页 `layout false` 可以生效：
![image](https://user-images.githubusercontent.com/36412883/119792972-c32bc000-bf08-11eb-90c1-9439ec682fd7.png)

**Comment by z384647062** [comment]
以及文档 [菜单的高级用法](https://beta-pro.ant.design/docs/advanced-menu-cn) 、[@umijs/plugin-layout](https://umijs.org/zh-CN/plugins/plugin-layout#xxxrender) 中的 `xxxRender` 也无效

**Comment by chenshuai2144** [comment]
因为 / 被忽略掉了，不会特殊处理

**Comment by chenshuai2144** [comment]
修复并发布了
