### ISSUE TITLE
🧐[问题] React不能识别DOM元素上的`xxxx`prop

### ISSUE THREAD

**Issue by qingshan315** [ant-design/ant-design-pro#8534]
### 🧐 问题描述

跟着文档`https://beta-pro.ant.design/docs/getting-started-cn`一步一步走下来
运行成功后出现了4个问题
```
Warning: React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Spin (http://localhost:8000/umi.js:97260:94)
    at div
    at PageLoading
    at LoadableComponent (http://localhost:8000/umi.js:194833:75)
    at Route
    at Switch
    at Router (http://localhost:8000/umi.js:195825:30)
    at RouterComponent (http://localhost:8000/umi.js:194014:23)
    at AccessProvider (http://localhost:8000/umi.js:201749:24)
    at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
    at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
    at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
```
```
devScripts.js:6523 Warning: React does not recognize the `pastDelay` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pastdelay` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Spin (http://localhost:8000/umi.js:97260:94)
    at div
    at PageLoading
    at LoadableComponent (http://localhost:8000/umi.js:194833:75)
    at Route
    at Switch
    at Router (http://localhost:8000/umi.js:195825:30)
    at RouterComponent (http://localhost:8000/umi.js:194014:23)
    at AccessProvider (http://localhost:8000/umi.js:201749:24)
    at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
    at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
    at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
```

```
Warning: React does not recognize the `timedOut` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `timedout` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Spin (http://localhost:8000/umi.js:97260:94)
    at div
    at PageLoading
    at LoadableComponent (http://localhost:8000/umi.js:194833:75)
    at Route
    at Switch
    at Router (http://localhost:8000/umi.js:195825:30)
    at RouterComponent (http://localhost:8000/umi.js:194014:23)
    at AccessProvider (http://localhost:8000/umi.js:201749:24)
    at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
    at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
    at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
```

```
Warning: Invalid value for prop `retry` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
    at div
    at Spin (http://localhost:8000/umi.js:97260:94)
    at div
    at PageLoading
    at LoadableComponent (http://localhost:8000/umi.js:194833:75)
    at Route
    at Switch
    at Router (http://localhost:8000/umi.js:195825:30)
    at RouterComponent (http://localhost:8000/umi.js:194014:23)
    at AccessProvider (http://localhost:8000/umi.js:201749:24)
    at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
    at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
    at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
```

我试着去解决他 但是我根本不知道报错的位置在哪里

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/31505470/119819944-85886080-bf23-11eb-9a86-da4114868867.png)

**Comment by fandepeng1993** [comment]
> ### 🧐 问题描述
> 跟着文档`https://beta-pro.ant.design/docs/getting-started-cn`一步一步走下来
> 运行成功后出现了4个问题
> 
> ```
> Warning: React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at div
>     at Spin (http://localhost:8000/umi.js:97260:94)
>     at div
>     at PageLoading
>     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
>     at Route
>     at Switch
>     at Router (http://localhost:8000/umi.js:195825:30)
>     at RouterComponent (http://localhost:8000/umi.js:194014:23)
>     at AccessProvider (http://localhost:8000/umi.js:201749:24)
>     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
>     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
>     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> ```
> 
> ```
> devScripts.js:6523 Warning: React does not recognize the `pastDelay` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pastdelay` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at div
>     at Spin (http://localhost:8000/umi.js:97260:94)
>     at div
>     at PageLoading
>     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
>     at Route
>     at Switch
>     at Router (http://localhost:8000/umi.js:195825:30)
>     at RouterComponent (http://localhost:8000/umi.js:194014:23)
>     at AccessProvider (http://localhost:8000/umi.js:201749:24)
>     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
>     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
>     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> ```
> 
> ```
> Warning: React does not recognize the `timedOut` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `timedout` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at div
>     at Spin (http://localhost:8000/umi.js:97260:94)
>     at div
>     at PageLoading
>     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
>     at Route
>     at Switch
>     at Router (http://localhost:8000/umi.js:195825:30)
>     at RouterComponent (http://localhost:8000/umi.js:194014:23)
>     at AccessProvider (http://localhost:8000/umi.js:201749:24)
>     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
>     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
>     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> ```
> 
> ```
> Warning: Invalid value for prop `retry` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
>     at div
>     at Spin (http://localhost:8000/umi.js:97260:94)
>     at div
>     at PageLoading
>     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
>     at Route
>     at Switch
>     at Router (http://localhost:8000/umi.js:195825:30)
>     at RouterComponent (http://localhost:8000/umi.js:194014:23)
>     at AccessProvider (http://localhost:8000/umi.js:201749:24)
>     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
>     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
>     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> ```
> 
> 我试着去解决他 但是我根本不知道报错的位置在哪里
> 
> ### 💻 示例代码
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/31505470/119819944-85886080-bf23-11eb-9a86-da4114868867.png)

请问你是如何解决的呢？

**Comment by qingshan315** [comment]
> > ### 🧐 问题描述
> > 跟着文档`https://beta-pro.ant.design/docs/getting-started-cn`一步一步走下来
> > 运行成功后出现了4个问题
> > ```
> > Warning: React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> >     at div
> >     at Spin (http://localhost:8000/umi.js:97260:94)
> >     at div
> >     at PageLoading
> >     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
> >     at Route
> >     at Switch
> >     at Router (http://localhost:8000/umi.js:195825:30)
> >     at RouterComponent (http://localhost:8000/umi.js:194014:23)
> >     at AccessProvider (http://localhost:8000/umi.js:201749:24)
> >     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
> >     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
> >     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > devScripts.js:6523 Warning: React does not recognize the `pastDelay` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pastdelay` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> >     at div
> >     at Spin (http://localhost:8000/umi.js:97260:94)
> >     at div
> >     at PageLoading
> >     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
> >     at Route
> >     at Switch
> >     at Router (http://localhost:8000/umi.js:195825:30)
> >     at RouterComponent (http://localhost:8000/umi.js:194014:23)
> >     at AccessProvider (http://localhost:8000/umi.js:201749:24)
> >     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
> >     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
> >     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Warning: React does not recognize the `timedOut` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `timedout` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> >     at div
> >     at Spin (http://localhost:8000/umi.js:97260:94)
> >     at div
> >     at PageLoading
> >     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
> >     at Route
> >     at Switch
> >     at Router (http://localhost:8000/umi.js:195825:30)
> >     at RouterComponent (http://localhost:8000/umi.js:194014:23)
> >     at AccessProvider (http://localhost:8000/umi.js:201749:24)
> >     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
> >     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
> >     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Warning: Invalid value for prop `retry` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
> >     at div
> >     at Spin (http://localhost:8000/umi.js:97260:94)
> >     at div
> >     at PageLoading
> >     at LoadableComponent (http://localhost:8000/umi.js:194833:75)
> >     at Route
> >     at Switch
> >     at Router (http://localhost:8000/umi.js:195825:30)
> >     at RouterComponent (http://localhost:8000/umi.js:194014:23)
> >     at AccessProvider (http://localhost:8000/umi.js:201749:24)
> >     at SrcUmiPlugininitialstateProvider (http://localhost:8000/umi.js:202456:24)
> >     at _LocaleContainer (http://localhost:8000/umi.js:203879:70)
> >     at SrcUmiPluginmodelProvider (http://localhost:8000/umi.js:204555:23)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我游戏去解决他，但是我根本不知道错误的位置在哪里
> > ### 💻 示例代码
> > ### 🚑 其他信息
> > ![图像](https://user-images.githubusercontent.com/31505470/119819944-85886080-bf23-11eb-9a86-da4114868867.png)
> 
> 比如你是如何解决的呢？

使用自己的加载组件
修改Config/config.ts文件中的这句话
```
dynamicImport: {
  loading: '@ant-design/pro-layout/es/PageLoading',
}
```
为
```
dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
```
/components/PageLoading/index文件如下
```
import React from 'react';
import { Spin } from 'antd';

// loading components from code split
// https://umijs.org/plugin/umi-plugin-react.html#dynamicimport
const pageLoading: React.FC = () => {
    return (
        <div style={{ paddingTop: 100, textAlign: 'center' }}>
            <Spin size="large" />
        </div>
    )
}
export default pageLoading;
```

**Comment by chenshuai2144** [comment]
更新依赖即可，已经修复
