### ISSUE TITLE
🐛[BUG]antdPro框架后端获取菜单栏，出现点击后menu菜单不消失 

### ISSUE THREAD

**Issue by PLUTO06210331** [ant-design/ant-design-pro#8537]
### 🐛 bug 描述

umi框架搭配antdPro项目，后端返回菜单栏，结果出现点击菜单栏不关闭的情况
![image](https://user-images.githubusercontent.com/33271366/119831493-e87ff480-bf2f-11eb-9cbf-ce84029aff06.png)

### 📷 复现步骤

突然就这样，我也是一脸蒙蔽

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这种一般是菜单的key重复了，打开控制看看
