### ISSUE TITLE
👑 [需求]V5 useModel按需请求加载

### ISSUE THREAD

**Issue by sunluby** [ant-design/ant-design-pro#8538]
### 🥰 需求描述
请问V5简易数据流，如何在页面使用const { ... } = useModel('inner'); 才向后端发送请求，加载inner命名空间的数据。布署后发现进入主页，就在加载所有src/models下的请求。这时候用户并没有登录，有些共享数据是登录后才能开始加载。而且这样吃流量。

**Comment by 569202812** [comment]
> ### 🥰 需求描述
> 请问V5简易数据流，如何在页面使用const { ... } = useModel('inner'); 才向后端发送请求，加载inner命名空间的数据。布署后发现进入主页，就在加载所有src/models下的请求。这时候用户并没有登录，有些共享数据是登录后才能开始加载。而且这样吃流量。

得导出请求方法，在使用的方法调用吧

**Comment by chenshuai2144** [comment]
看起来是你的代码写的有问题。 js 里面不应该有自运行的代码，需要页面去显式调用的。除非你很细致的控制webpack 的分包策略

**Comment by xxgzzp** [comment]
问问，大佬实现了吗，我也在useModel中请求了一些数据，
