### ISSUE TITLE
🧐[问题]设置hideInMenu: true 不展示面包屑.只展示系统title

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/ant-design-pro#8541]
### 🧐 问题描述
设置hideInMenu: true 不展示面包屑.只展示系统title
怎么能在隐藏的情况下展示面包屑呢。各位大哥们🧐🧐🧐🧐

### 💻 示例代码

{
                                    name: '角色权限',
                                    icon: 'smile',
                                    path: '/organization/enterprisesetup/rolrPermissions',
                                    component: './enterprise-setup/role-permissions/RolrPermissions',
                                },
                                {
                                    name: '角色权限设置',
                                    icon: 'smile',
                                    path: '/organization/enterprisesetup/settingRolrPermissions/:id',
                                    component: './enterprise-setup/role-permissions/components/CreateRole',
                                    hideInMenu: true
                                }
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/52319042/119941677-81138480-bfc3-11eb-935f-57cab5d2dd61.png)
"name": "ant-design-pro",
    "version": "4.5.0",        
"umi": "^3.2.14",

**Comment by chenshuai2144** [comment]
breadcrumbRender | 自定义面包屑的数据 | (route)=&gt;route | -
-- | -- | -- | --





试试这个api

**Comment by TangDeYu** [comment]
> 面包屑渲染	自定义面包的数据	（路线）=>路线	——
> 用这个api

大佬，我的标题应该是描述错了。。目前的问题是加上hideInMenu: true只展示系统的title ;

怎么样才能设置hideInMenu: true时还展示config里面路由的配置面包屑呢 。？。

**Comment by chenshuai2144** [comment]
现在是不支持这样的，面包屑是根据菜单生成的。
