### ISSUE TITLE
🐛[BUG] 官网文档footer 文字显示有失误

### ISSUE THREAD

**Issue by mipawn** [ant-design/ant-design-pro#8543]
### 🐛 bug 描述

官网文档   Ant Design Landing  后面文字显示失误

### 📷 复现步骤

直接打开官网滑倒最底部就可看到

### 🏞 期望结果

文字正常显示

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39559813/119946358-22e9a000-bfc9-11eb-9c2a-1ab9d7461cab.png)

**Comment by huntdream** [comment]
> 什么错误，没看出来啊？？？

![image](https://user-images.githubusercontent.com/7903755/119958857-043dd600-bfd6-11eb-8067-86c54885bc52.png)
颜色问题，继承了Badge的颜色

**Comment by chenshuai2144** [comment]
有兴趣来个pr吗？

**Comment by lihqi** [comment]
[here](https://github.com/ant-design/ant-design-pro-site/blob/d209b6e7b2f6ce577255f8ed16cc0d924925b829/src/components/layout/Footer.tsx#L67)

**Comment by chenshuai2144** [comment]
去掉这个 Badge  吧，没什么用了
