### ISSUE TITLE
🧐[问题] v5 useModel 项目 build 后 运行 报错

### ISSUE THREAD

**Issue by Julywj** [ant-design/ant-design-pro#8544]
在dev环境运行没有问题，build之后，运行报错 Cannot read property '@@initialState' of undefined

### 💻 示例代码

const UserProfile: React.FC = () => {
  const [showUser, setShowUser] = useState("");
  const { initialState } = useModel("@@initialState");

  useEffect(() => {
    if (initialState?.currentUser) `{`
      showUser(initialState?.currentUser?.name)
    }
  }, [initialState?.currentUser])
return (
    <div>
{showUser}
</div>

  )
### 🚑 其他信息

有些页面使用没有问题，有些页面有问题

![image](https://user-images.githubusercontent.com/8746796/119951433-875b2e00-bfce-11eb-8488-58b5a31138fc.png)

之前build后，部署上也没有问题，后来新增了@umijs/hooks 依赖，出现问题，但是把这个依赖去掉再重新build也还是不行；

**Comment by PlayApple** [comment]
你最后解决了吗？

**Comment by fangqibin** [comment]
是不是umi版本太低了，你使用的是啥版本

**Comment by Julywj** [comment]
> 是不是umi版本太低了，你使用的是啥版本

3.4.0

**Comment by Julywj** [comment]
> 你最后解决了吗？

vscode 引入的包有问题，手动引用之后就没有问题了

**Comment by PlayApple** [comment]
> > 你最后解决了吗？
> 
> vscode 引入的包有问题，手动引用之后就没有问题了

import { useModel } from 'umi';

我引用的这个会有问题，你是改成了哪一个？

**Comment by Julywj** [comment]
> > > 你最后解决了吗？
> > 
> > 
> > vscode 引入的包有问题，手动引用之后就没有问题了
> 
> import { useModel } from 'umi';
> 
> 我引用的这个会有问题，你是改成了哪一个？

手动引用了一下，解决的

**Comment by giscafer** [comment]
和umi有差异，以下代码umi直接可用

```ts
  const { loading, structureAdd, structureDeleteById, structureUpdateById, structureListByParam } =
    useModel('useProtocolStructureModel');
```

antd pro v5.0 不行。build后会报错

```
TypeError: Cannot read property 'useProtocolStructureModel' of undefined
```

解决：

需要手动引入的方式，不能用useModel

```
import useProtocolStructureModel from '../models/useProtocolStructureModel';
  const { spList, pgList, slotList, structureListByParam } = useProtocolStructureModel;
```

**Comment by xykjlcx** [comment]
> > > > 你最后解决了吗？
> > > 
> > > 
> > > vscode 引入的包有问题，手动引用之后就没有问题了
> > 
> > 
> > import { useModel } from 'umi';
> > 我引用的这个会有问题，你是改成了哪一个？
> 
> 手动引用了一下，解决的

怎么手动引用解决的，老哥，同样的问题

**Comment by giscafer** [comment]
> > > > > 你最后解决了吗？
> > > > 
> > > > 
> > > > vscode 引入的包有问题，手动引用之后就没有问题了
> > > 
> > > 
> > > import { useModel } from 'umi';
> > > 我引用的这个会有问题，你是改成了哪一个？
> > 
> > 
> > 手动引用了一下，解决的
> 
> 怎么手动引用解决的，老哥，同样的问题

就是没有用useModel了，直接导入使用
