### ISSUE TITLE
🧐[问题]文档缺少了只读模式，设置footer={null}未生效

### ISSUE THREAD

**Issue by diaomina** [ant-design/ant-design-pro#8545]
### 🧐 问题描述

1、尝试使用ModalForm封装一个自定义的表单，但是编写查看表单部分时，发现文档缺少了，文档连接如下：
[https://ant-design-pro-components-preview-pr-963.surge.sh/components/form#%E5%8F%AA%E8%AF%BB%E6%A8%A1%E5%BC%8F](url)
想问一下，怎么设置整个表单都为只读的，

2、参考文档将footer设置null，但是默认的确认、取消按钮并没有消失
### 💻 示例代码

```
<ModalForm
      form={form}
      title={getTitle()}
      width={width}
      visible={visible}
      onVisibleChange={(newVisible) => {
        if (!newVisible) handleCancel();
      }}
      onFinish={onFinish}
      modalProps={{
        footer: null,
      }}
    >
      {formContent()}
    </ModalForm>
```

**Comment by chenshuai2144** [comment]
dup of  https://github.com/ant-design/pro-components/issues/2873
