### ISSUE TITLE
🧐[问题] 请问如何设置ProTable 每一行数据的 hover 背景颜色？

### ISSUE THREAD

**Issue by gerri0098** [ant-design/ant-design-pro#8547]
### 🧐 问题描述

如题，尝试过使用  rowClassName 进行设置， 结果是 鼠标悬停在数据行时，对应数据行的背景色变化只是闪一下，然后又变成默认效果

### 💻 示例代码
css: 

```
.table-row:hover {
  background-color: #ddebf6;
}
```

ProTable 设置 

```
      <ProTable<API.RuleListItem, API.PageParams>
        rowClassName={'table-row'}

      ......
```

### 🚑 其他信息

![demo](https://user-images.githubusercontent.com/61908109/120062340-4af20580-c094-11eb-828d-0be96065ad07.gif)

**Comment by chenshuai2144** [comment]
rowClassName | 表格行的类名 | function(record, index): string | -
-- | -- | -- | --






用这个api

**Comment by gerri0098** [comment]
> rowClassName	表格行的类名	function(record, index): string	-
> 用这个api，然后 再设置样式，不然你的优先级太低


试了一下，改成function也不行，其它设置都能生效,比如设置字体颜色都可以, hover 下的字体颜色也可以生效。只是 :hover下的 background-color  不行。

**Comment by chenshuai2144** [comment]
提升一下优先级

**Comment by mumu0125** [comment]
根据指定条件设置行的背景颜色，用了:
```
          onRow={(record, index) => {
            console.log('record', record, 'index', index);
            if (record.no_data) {
              return {
                style: {
                  background: 'gray',
                },
              };
            }
        }}
```
表中还有固定列，普通列颜色变成功了，固定的列还是原来的颜色，权重加到最高也不行，同问怎么解决？希望能得到答复，感谢
