### ISSUE TITLE
IE11打不开🧐[问题]

### ISSUE THREAD

**Issue by zhangpanfei** [ant-design/ant-design-pro#8549]

**Comment by lishaoh** [comment]
IE马上就要弃用了，还不抓紧迁移吗 👀

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF

为你默哀
