### ISSUE TITLE
👑 [需求]能否自己控制左边菜单的收缩

### ISSUE THREAD

**Issue by chenjunjia97** [ant-design/ant-design-pro#8552]
### 🥰 需求描述

能够自己控制左边菜单的收缩

**Comment by chenshuai2144** [comment]
collapsed | 控制菜单的收起和展开 | boolean | -
-- | -- | -- | --
onCollapse | 菜单的折叠收起事件 | (collapsed: boolean) =&gt; void | -






这里有对api

**Comment by chenjunjia97** [comment]
![image](https://user-images.githubusercontent.com/49097606/120180335-36ea0780-c23e-11eb-923d-c3853b59904d.png)
这个怎么才能控制得了

**Comment by chenjunjia97** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
控制  collapsed  变量

**Comment by fangqibin** [comment]
你是想控制左侧菜单合起来跟展开吗，还是collapsed

**Comment by chenjunjia97** [comment]
> 你是想控制左侧菜单合起来跟展开吗，还是collapsed

有些界面想让左边收起来有些展开

**Comment by fangqibin** [comment]
用openKeys控制

**Comment by fangqibin** [comment]
> > 你是想控制左侧菜单合起来跟展开吗，还是collapsed
> 
> 有些界面想让左边收起来有些展开

用openKeys控制

**Comment by chenjunjia97** [comment]
> > > 你是想控制左侧菜单合起来跟展开吗，还是collapsed
> > 
> > 
> > 有些界面想让左边收起来有些展开
> 
> 用openKeys控制

有 例子吗?

**Comment by fangqibin** [comment]
> > > > 你是想控制左侧菜单合起来跟展开吗，还是collapsed
> > > 
> > > 
> > > 有些界面想让左边收起来有些展开
> > 
> > 
> > 用openKeys控制
> 
> 有 例子吗?

onOpenChange: (keys: WithFalse<string[]>): void => {
      const newOpenKeys: string[] = [];
      // 可以写自己要展开还是收缩逻辑判断
      setInitialState({
        ...initialState,
        openKeys: newOpenKeys,
      })
    },
    openKeys: initialState?.openKeys,
