### ISSUE TITLE
🐛[BUG] ant-design-pro 浏览器兼容问题

### ISSUE THREAD

**Issue by lzb-libra** [ant-design/ant-design-pro#8555]
本人本地跑了ant-design-pro v5 的项目，项目是一两个月前下载的，我在这个项目上进行的开发。最近测试功能，发现了一个问题
我使用了360极速浏览器13.0版本，通过url "http://localhost:8000"访问可以进入到登陆页面
![image](https://user-images.githubusercontent.com/63389341/120305482-5f880500-c303-11eb-8e0e-0fba0ea55d26.png)
但是当我将localhost替换成我本机IP后发现登陆页面不展示了，一直处于下方页面
![image](https://user-images.githubusercontent.com/63389341/120305615-8e05e000-c303-11eb-81ff-3b8c53a060ca.png)
控制台打印了错误信息
![image](https://user-images.githubusercontent.com/63389341/120305644-98c07500-c303-11eb-8544-428c27886520.png)
![image](https://user-images.githubusercontent.com/63389341/120305693-a675fa80-c303-11eb-84e0-9cc5bc7d29de.png)
![image](https://user-images.githubusercontent.com/63389341/120305664-9f4eec80-c303-11eb-8855-08c4a38e26d1.png)
![image](https://user-images.githubusercontent.com/63389341/120305740-b42b8000-c303-11eb-85f3-8c8b5d14ec98.png)

正常我不管是通过IP还是localhost应该都正常进入登陆页面，这种情况好像是只在ie内核的浏览器上才会出现，我用火狐、edge、QQ浏览器暂未发现此问题。
补充一点，我自己写的代码没有使用includes方法

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF

跟着这个来一发吧

**Comment by lzb-libra** [comment]
在下才疏学浅完全看不懂(╥╯^╰╥)
