### ISSUE TITLE
🧐[问题] umi  request 请求的时候统一接口参数定义 data 字段不返回里面值

### ISSUE THREAD

**Issue by zanmeipaul** [ant-design/ant-design-pro#8559]
### 🧐 问题描述
umi request 发送请求后端返回 {"data:"{},"success":true} ,可是 request 获取出来的是{"data:"{},"success":true}  这个对象不是 data 里面的数据。 设置了config.ts 
request: {
    dataField: 'data'
  }  也没有效果

export async function captcha(options?: { [key: string]: any }) {
  return  request('/api/auth/code', {
    method: 'GET',
    ...(options || {}),
  });
}

const data = await captcha();
    console.log(data);
data 是 {"data:"{},"success":true}

**Comment by fangqibin** [comment]
先看网络请求回来的数据对不对

**Comment by cdz620** [comment]
经验证，确实有同样的问题

**Comment by roach01** [comment]
附议
