### ISSUE TITLE
权限问题建议

### ISSUE THREAD

**Issue by Paleozoic** [ant-design/ant-design-pro#856]
在[CheckPermissions.js](https://github.com/ant-design/ant-design-pro/blob/master/src%2Fcomponents%2FAuthorized%2FCheckPermissions.js)里面checkPermissions的思路是判断当前用户权限是否允许访问某资源，资源的准入权限是数组，而当前权限是字符串。实际应用对应的其实就是角色。但是这样子控制权限过于粗放。
建议如下：
能不能这个样子？前端路由资源打上一个标记，当前登录用户权限是一个数组（或者函数什么的），然后`checkPermissions`判断的是当前用户的currentAuthorityList 是否包含 资源标识authority来对权限进行控制？或者说，支持authority和currentAuthority两个参数都可以传入字符串、数组、函数？

**Comment by ddcat1115** [comment]
https://github.com/ant-design/ant-design-pro/issues/692 里有相关讨论，看用 function 是否能解决你的问题

**Comment by chenshuai2144** [comment]
@Paleozoic  这个与我们现在正好反过来了。 
你可以使用一个function参数来进行判断，function是不依赖 authority 参数的。你可以将你的逻辑在方法中实现

**Comment by Paleozoic** [comment]
你好！
看了里面的讨论，function的确可以处理……
不过我还有个建议，不知道这样设计是否可行？
authority和currentAuthority都可以传入字符串、数组、函数，但是不能同时是数组、函数。
这样子就兼容了。
关于和后端解耦，个人这样理解。
路由的path看作唯一标识（path即权限控制的最小单元，这是前提，不知道是否可行），后端返回当前用户可访问的pathArray。
然后authority, currentAuthority变成了path和pathArray，这样子前端基本不用关注后端的配置也不需要进行相关沟通，前端mock出数据就可以开发了。

**Comment by chenshuai2144** [comment]
这个和后端请求菜单又相同的作用。
这个功能可能需要修改我们的架构，暂时不会考虑支持

**Comment by Paleozoic** [comment]
= =|| 没看懂2个【这个】的指代。

**Comment by chenshuai2144** [comment]
😂
你需要的功能和后端请求菜单相同的作用。
这个功能可能需要修改我们的架构，暂时不会考虑支持。

**Comment by chengnuo** [comment]
@Paleozoic 我也是这样的实现思路，所以看到作者的实现有点蒙蔽。对我使用rbac产生了一点困难。

**Comment by A-birdFlyHigner** [comment]
反正我是把把架构修改了，common直接不用了😂
