### ISSUE TITLE
🧐[问题] umi request 发送请求后端返回统一返回参数 data 不提取问题

### ISSUE THREAD

**Issue by zanmeipaul** [ant-design/ant-design-pro#8560]
### 🧐 问题描述
umi request 发送请求后端返回 {"data:"{},"success":true} ,可是 request 获取出来的是{"data:"{},"success":true}  这个对象不是 data 里面的数据。 设置了config.ts 
request: {
    dataField: 'data'
  }  也没有效果

export async function captcha(options?: { [key: string]: any }) {
  return  request('/api/auth/code', {
    method: 'GET',
    ...(options || {}),
  });
}

const data = await captcha();
    console.log(data);
data 是 {"data:"{},"success":true}

**Comment by Cloudxiecy** [comment]
这个解决了吗？如何解决呀
