### ISSUE TITLE
🧐[问题]react-dev-inspector使用时 点击页面元素 编辑器报错 系统找不到指定的路径

### ISSUE THREAD

**Issue by dadazhouRenee** [ant-design/ant-design-pro#8562]
### 🧐 问题描述
在使用react-dev-inspector时，我运行项目成功后，ctrl +shift + commmand + c，然后点击页面元素后，我的VS code 编辑器没有打开到具体的文件。

然后控制台有报错信息为：
![image](https://user-images.githubusercontent.com/31841446/120608045-58880080-c483-11eb-8941-e1302a422d1f.png)

我感觉好像是我的项目目录没有带上所以报错

请问这种情况怎么处理呢？是否是要在 `config.dev.js`中配置什么呢

### 💻 示例代码
目前我配置了 .bashrc 文件
```bash
export REACT_EDITOR=code
```

### 🚑 其他信息
我直接在终端 输入 `code D:\Study\antdPro\complexDemo\src\layouts\BasicLayout.jsx`
编辑器是可以打开 `BasicLayout.jsx` 的

**Comment by chenshuai2144** [comment]
这个库可能对windows 的识别能力一般

**Comment by Liu-Ya** [comment]
> 这个库可能对windows 的识别能力一般

不如默认禁用掉吧，有点徒增烦恼，还容易引发问题
![image](https://user-images.githubusercontent.com/23520283/124907756-1c643480-e01b-11eb-92e6-b34dfe9c4938.png)

**Comment by chenshuai2144** [comment]
这个还是很有用的，项目大了根本找到这个页面的文件在哪里。

**Comment by drizzlesconsin** [comment]
可以试试这个组件 [click-to-component](https://github.com/ericclemmons/click-to-component)
