### ISSUE TITLE
🐛[BUG] Ant Design Pro V5 预览项目的ProTable详情页显示空白

### ISSUE THREAD

**Issue by FirstSeeing** [ant-design/ant-design-pro#8566]
### 🐛 bug 描述

新创建一个Ant Design Pro V5 预览项目，ProTable详情页里点配置后再关闭，详情页变成空白

### 📷 复现步骤

新创建一个Ant Design Pro V5 预览项目，ProTable点击列表任意一列的规则名称，在右边弹出的抽屉式详情组件的配置按钮，然后关闭弹出的配置对话框，随后抽屉式详情页就会变成一片空白。

### 🏞 期望结果

期望关闭配置页对话框详情页也不会变成一片空白

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [e.g. Windows 10]

### 🚑 其他信息
![1.png](https://i.loli.net/2021/06/04/Zk9DISXA4z3bGUn.png)
![2.png](https://i.loli.net/2021/06/04/BZiVFYs36etcapm.png)
![3.png](https://i.loli.net/2021/06/04/f5sElSIuDUtPkwd.png)
![5.png](https://i.loli.net/2021/06/04/bvEXtcuoaiRSmlB.png)

**Comment by chenshuai2144** [comment]
fixed
