### ISSUE TITLE
🐛[BUG] V5菜单高级用法中，登录页初始化拉取菜单

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#8567]
### 🐛 bug 描述
在V5菜单高级用法中，登录页初始化拉取菜单监听id变化时，初始化id为undefined也会执行拉取菜单操作

   menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: {
        // initialState,
        id: initialState?.currentUser?.id,
      },
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      request: async (params, defaultMenuData) => {
        // initialState.currentUser 中包含了所有用户信息
        console.log('获取用户菜单参数变化', params, defaultMenuData);
        const menuData = await fetchMenuData();
        return menuData;
      },
    },
登录页id为undefined也执行了请求
### 🏞 期望结果
如何解决登录页id初始化没有值时，不执行 menu中的 request

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by w345731923** [comment]
我也遇到了，登录页加载，然后登录成功后却没有再执行

**Comment by zhaojianhui129** [comment]
是的，我这边也遇到该问题，除非登录后重新刷新才会重新获取菜单。

**Comment by w345731923** [comment]
> 是的，我这边也遇到该问题，除非登录后重新刷新才会重新获取菜单。

目前的替代方案是在onPage里刷新menu，
管理大大正在修复，过几天就好了https://github.com/ant-design/ant-design-pro/issues/8501

**Comment by chenshuai2144** [comment]
已经修复了，大家更新下依赖

**Comment by YC725968** [comment]
感谢

**Comment by w345731923** [comment]
> 已经修复了，大家更新下依赖

npm outdated都使用了最新的依赖包，依然有这个问题

**Comment by fooliker** [comment]
问题依然在

**Comment by fooliker** [comment]
> onPage
问题依然在
