### ISSUE TITLE
🧐[问题] 动态主题 换色 编译css失败 [LessError: variable @alert-prefix-cls is undefined]

### ISSUE THREAD

**Issue by wu-xiaowei** [ant-design/ant-design-pro#8569]
### 🧐 问题描述

#8568 已解决 按照v4版本 需要添加mi-plugin-antd-theme 可直接使用 
目前遇到新的问题 启动编译时 theme 文件下的css文件内容为 undefined 
同时控制台报错
![image](https://user-images.githubusercontent.com/29117317/120885943-1cd56e00-c61e-11eb-973d-64c6e6dd291e.png)

css内容：
![image](https://user-images.githubusercontent.com/29117317/120885965-31196b00-c61e-11eb-8be7-4d808dfa849c.png)
![image](https://user-images.githubusercontent.com/29117317/120885977-3b3b6980-c61e-11eb-886a-b8a1cecc5b80.png)

依赖部分：
![image](https://user-images.githubusercontent.com/29117317/120885995-4b534900-c61e-11eb-9273-9bceecd8788d.png)
![image](https://user-images.githubusercontent.com/29117317/120886010-560dde00-c61e-11eb-88fd-7102684debaa.png)
 感觉像少了依赖一样 一天没解决 求大佬帮助 谢谢

**Comment by wu-xiaowei** [comment]
@chenshuai2144  大佬在吗

**Comment by chenshuai2144** [comment]
antd的版本问题，升级一下好了

**Comment by 429299291** [comment]
我也遇到了这么问题，"antd": "^4.23.4",怎么还是有问题呢
