### ISSUE TITLE
About the selectedKeys of menu

### ISSUE THREAD

**Issue by hudawen** [ant-design/ant-design-pro#857]
if the `multiple` property of `Menu` is `false`, how does the `selectedKeys` work as `string[]` type?

**Comment by ddcat1115** [comment]
Issue about antd component using should be raised [here](https://github.com/ant-design/ant-design/issues).

**Comment by hudawen** [comment]
The issue I face is that two menu items are both selected while their paths are the same even though their parent paths are different. I wonder if there is a way to solve it without changing the router.

**Comment by hudawen** [comment]
@ddcat1115 @chenshuai2144
