### ISSUE TITLE
🐛[BUG] Drawer Modal Footer Button not Internationalized

### ISSUE THREAD

**Issue by ehdwns980416** [ant-design/ant-design-pro#8572]
### 🐛 bug 描述

The `Drawer Modal` footer buttons are not Internationalized.
I confirmed that the `basic modal` button works.

#### My Internationalization Setting
![image](https://user-images.githubusercontent.com/26425092/120950206-45c24400-c781-11eb-9d00-12c27cd3bd50.png)

#### Basic Modal
![image](https://user-images.githubusercontent.com/26425092/120950191-380cbe80-c781-11eb-8618-7a9fcee06d86.png)

#### Drawer Modal
![image](https://user-images.githubusercontent.com/26425092/120950133-190e2c80-c781-11eb-96f6-23da906f21fa.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
fixed in latest
