### ISSUE TITLE
🧐public 下文件打包后可以配置指定部分文件夹，不复制到到输出路径吗

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#8573]
### 🧐 问题描述

public 下文件打包后可以配置指定部分文件夹，不复制到到输出路径吗

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#outputpath


https://umijs.org/zh-CN/config#copy

看看两个满足你的需求吗?
