### ISSUE TITLE
请问如何对接OIDC协议呢，有例程吗🧐[问题]

### ISSUE THREAD

**Issue by JhonRen** [ant-design/ant-design-pro#8575]
### 🧐 问题描述
我们需要使用ant design pro 来对接我们单点登录，SSO是使用了OIDC协议。但是我不知道改如何进行OIDC来对接ant pro。
希望能够获得帮助。

**Comment by JhonRen** [comment]
nobody

**Comment by chenshuai2144** [comment]
去专门提问的社区看看把
