### ISSUE TITLE
🧐[问题]柱状图Bar组件，当横坐标内容过长，不能自动截断，请问如何操作

### ISSUE THREAD

**Issue by sys0613** [ant-design/ant-design-pro#8577]
### 🧐 问题描述
    用默认的柱状图Bar组件，如果data中x横坐标内容过长，界面显示混乱，能否自动截断，变成后面加“...."格式,
    然后鼠标放到每个柱子上，可以看到详细名称。谢谢了。
    ，柱状图使用文档链接，目前代码是V2版本的，希望找到一个柱状图解决办法，谢谢了，
    https://v2-pro.ant.design/components/charts#scaffold-src-components-Charts-demo-bar

### 💻 示例代码

              import React from 'react';
              import ReactDOM from 'react-dom';
              import 'antd/dist/antd.css';
              import './index.css';
              import 'ant-design-pro/dist/ant-design-pro.css';
              import { Bar } from 'ant-design-pro/lib/Charts';

              const salesData = [];
              for (let i = 0; i < 12; i += 1) {
                salesData.push({
                  x: `${i + 1}汉字超长测试测试上次月`,
                  y: Math.floor(Math.random() * 1000) + 200,
                });
              }

              ReactDOM.render(<Bar height={200} title="销售额趋势" data={salesData} />, document.getElementById('container'));
     

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/10354069/121115083-44f3e580-c847-11eb-9a6f-0cf7b3812929.png)

**Comment by chenshuai2144** [comment]
这个只能设置为90度了。或者 x 稀疏一点。
