### ISSUE TITLE
🐛[BUG]splitMenus导致二级菜单无法正常渲染

### ISSUE THREAD

**Issue by johnwayen** [ant-design/ant-design-pro#8578]
### 🐛 splitMenus导致二级菜单无法正常渲染

按照Prolayout文档中设置splitMenus，并且设定一级菜单重定向到二级子菜单第一个，实际会导致二级菜单的内容无法渲染出来
![issue-1623133709325](https://user-images.githubusercontent.com/3950749/121134326-dbcf9a80-c865-11eb-8ce9-0634069d4da9.jpg)
![issue-1623133463572](https://user-images.githubusercontent.com/3950749/121134054-8d220080-c865-11eb-8921-44c4f05bd4a3.jpg)

### 📷 复现步骤

克隆ant design pro到本地运行
defaultSettings.ts设置:
`{
layout: 'mix',
splitMenus: true,
}`
config.ts路由设置：
`{
      path: '/form',
      icon: 'form',
      name: 'form',
      redirect: '/form/basic-form',
      routes: [
        {
          name: 'basic-form',
          icon: 'smile',
          path: '/form/basic-form',
          component: './form/basic-form',
        },
        {
          name: 'step-form',
          icon: 'smile',
          path: '/form/step-form',
          component: './form/step-form',
        },
        {
          name: 'advanced-form',
          icon: 'smile',
          path: '/form/advanced-form',
          component: './form/advanced-form',
        },
      ],
    }`

结果二级菜单基础表单的内容没有渲染出来

### 🏞 期望结果

![issue-1623133642222](https://user-images.githubusercontent.com/3950749/121134179-afb41980-c865-11eb-8c0e-bc9ebb47a072.jpg)

**Comment by chenshuai2144** [comment]
需要手动配置重定向的，因为一级菜单一般是空的。

```
{
    path: '/',
    redirect: '/welcome',
  },
```
