### ISSUE TITLE
🐛[BUG]ProTable树形表格组件在ant design pro build之后打开之后不显示“-”图标

### ISSUE THREAD

**Issue by johnwayen** [ant-design/ant-design-pro#8579]
### 🐛 ProTable树形表格组件在ant design pro build之后打开之后不显示“-”图标，点击不能收缩，本地非编译模式下一切正常

![issue-1623134134455](https://user-images.githubusercontent.com/3950749/121135195-d7f04800-c866-11eb-8cd6-3c984ff30161.jpg)

### 🏞 期望结果

![issue-1623134281465](https://user-images.githubusercontent.com/3950749/121135532-2d2c5980-c867-11eb-9f2c-e32ae94022f0.jpg)

**Comment by chenshuai2144** [comment]
重新更新下依赖，已经修复
