### ISSUE TITLE
饼状图样式问题

### ISSUE THREAD

**Issue by lijingcsu** [ant-design/ant-design-pro#858]
按照例子写饼状图，得到效果如下：
![image](https://user-images.githubusercontent.com/8297694/35626592-244e5ce2-06d1-11e8-83aa-477f041b2bdc.png)
![image](https://user-images.githubusercontent.com/8297694/35626615-3847812e-06d1-11e8-961a-5aedff8c566b.png)

文字没有在中间，但是按下f12后能居中如下
![image](https://user-images.githubusercontent.com/8297694/35626627-42c44240-06d1-11e8-8dea-e7f305831054.png)
对比看了下样式，样式发生变化了才居中的，请问这是为什么呢

**Comment by ddcat1115** [comment]
用的最新的脚手架么？

**Comment by lijingcsu** [comment]
没有官方的脚手架，是我自己用webpack手动建立的，中间有什么没有设置好么

**Comment by ddcat1115** [comment]
组件版本？

**Comment by lijingcsu** [comment]
"ant-design-pro": "^1.1.0",
"antd": "^3.1.6",

**Comment by ddcat1115** [comment]
跟这个应该是同一个问题  https://github.com/ant-design/ant-design-pro/issues/720

**Comment by lijingcsu** [comment]
谢谢
