### ISSUE TITLE
🐛[BUG]v5 验证码填写了，提交时也提示必填

### ISSUE THREAD

**Issue by horizontung** [ant-design/ant-design-pro#8584]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/26265876/121312912-739db900-c938-11eb-99a1-f70236b5e58b.png)

### 📷 复现步骤

[按照官方文档初始化仓库](https://beta-pro.ant.design/docs/getting-started-cn)
启动后即可复现

### 🏞 期望结果

正常提交

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/2981
