### ISSUE TITLE
How do I set the SettingDrawer in English? || set ant design pro to english by default

### ISSUE THREAD

**Issue by deepghuge36** [ant-design/ant-design-pro#8588]
### 🧐 问题描述

I have to select the language English manually the only then it shows in English
![Screen Shot 2021-06-09 at 4 08 32 PM](https://user-images.githubusercontent.com/42240311/121379677-e40d0000-c961-11eb-81d2-d77389efeec5.png)
![Screen Shot 2021-06-09 at 4 08 58 PM](https://user-images.githubusercontent.com/42240311/121379697-ea02e100-c961-11eb-9344-cecf3af2bade.png)

**Comment by chenshuai2144** [comment]
look here 
https://umijs.org/plugins/plugin-locale

**Comment by hage10** [comment]
> ### 🧐 问题描述
> I have to select the language English manually the only then it shows in English ![Screen Shot 2021-06-09 at 4 08 32 PM](https://user-images.githubusercontent.com/42240311/121379677-e40d0000-c961-11eb-81d2-d77389efeec5.png) ![Screen Shot 2021-06-09 at 4 08 58 PM](https://user-images.githubusercontent.com/42240311/121379697-ea02e100-c961-11eb-9344-cecf3af2bade.png)
> 
> ### 💻 示例代码
> ### 🚑 其他信息

How did you select it manually?
