### ISSUE TITLE
请教Table如何单击行进行选择

### ISSUE THREAD

**Issue by efairy** [ant-design/ant-design-pro#859]
请教Table如何单击行进行选择？
如复选框情况下 onRowClick如何将当前行进行复选或者取消复选状态？
另外测试了onRow = {
    onClick = () => {}
}
触发结果和onRowClick不太一样，很纠结

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35655307-305a33ac-072c-11e8-81c0-6e598ca947fb.png)
`onRow` 是用来设置行属性的
你只需要修改这个属性就能解决问题。将表格设置为一个受控组件。
