### ISSUE TITLE
🧐[问题] Get 请求如果添加请求头

### ISSUE THREAD

**Issue by fivefog** [ant-design/ant-design-pro#8590]
### 🧐 问题描述

接口是get, 需要`'Content-Type: application/json'`，但是使用很多方法都失败了，怎么给请求头添加？   
![image](https://user-images.githubusercontent.com/53244212/121488969-2be56300-ca06-11eb-8b53-a44052b0f44a.png)

### 💻 示例代码

```ts
export async function getDatasetList(params?: SystemConfigParam) {
  return request('/device-plat/management/health/fault/dataset/list', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
    skipErrorHandler: true,
    data: {
      ...params,
    },
  });
}
```

#### 截图
![image](https://user-images.githubusercontent.com/53244212/121491613-b16a1280-ca08-11eb-9df9-fa51414e7c5f.png)

![image](https://user-images.githubusercontent.com/53244212/121491521-9b5c5200-ca08-11eb-8ec8-3f84afccfcfe.png)

**Comment by fivefog** [comment]
参考`https://github.com/umijs/umi-request`使用以下方式，依然没成功
```ts
import { extend } from 'umi-request';

const requestH = extend({
  prefix: '/api/v1',
  timeout: 1000,
  headers: {
    'Content-Type': 'multipart/form-data',
  },
});

requestH
  .get('/user')
  .then(function(response) {
    console.log(response);
  })
  .catch(function(error) {
    console.log(error);
  });
```

**Comment by Julywj** [comment]
试试这个呢？？

const inter = (url: string, options: RequestOptionsInit) => {

  return {
    url,
    options: {
      ...options,
      headers: {
        ...options.headers,
        'X-Tenant-Type': localStorage.getItem('sys')
      },
    }
  }
}

export const request: RequestConfig = {
  errorHandler,
  requestInterceptors: [inter]
};

**Comment by ISBN9527** [comment]
在app.tsx中使用requestInterceptors请求拦截器或者用headers属性
