### ISSUE TITLE
👑 [需求]启动和热更新太慢

### ISSUE THREAD

**Issue by wangjunhong** [ant-design/ant-design-pro#8591]
启动需要88秒左右，热更新需要4-5秒，有没有基于浏览器原生 ES Module的解决方案（类似vite）？

**Comment by lishaoh** [comment]
@wangjunhong 是不是开通了动态主题 antd-theme?

**Comment by wangjunhong** [comment]
> @wangjunhong 是不是开通了动态主题 antd-theme?
没有开  ，创建的空项目启动也是很慢的  不知道是不是我的笔记本是15年款的8g内存mac pro的问题 现在应该配置算低了

**Comment by lishaoh** [comment]
我也是15年款8g内存的Mac，跑服务还好啊

**Comment by chenshuai2144** [comment]
mfsu 已经默认打开，欢迎大家体验

**Comment by Valar103769** [comment]
> mfsu 已经默认打开，欢迎大家体验

有什么办法,能换成vite吗
