### ISSUE TITLE
🐛[BUG] ant-design-pro V5在linux环境下执行npm install报错

### ISSUE THREAD

**Issue by huajiayi** [ant-design/ant-design-pro#8594]
### 🐛 bug 描述

ant-design-pro V5在linux环境下执行npm install报错
运行环境：CentOS Linux release 7.6.1810 (Core)
node版本：14.16.0

### 📷 复现步骤

执行npm install

### 🏞 期望结果

下载依赖成功

### 💻 复现代码

npm install

### © 版本信息

- Ant Design Pro 版本: [V5]
- umi 版本 3.2.14
- 浏览器环境 Chrome
- 开发环境 CentOS Linux release 7.6.1810 (Core)

### 🚑 其他信息

报错信息：
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /root/myapp/node_modules/speech-rule-engine/speech-rule-engine-3.3.2.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/root/myapp/node_modules/speech-rule-engine/speech-rule-engine-3.3.2.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by esailes** [comment]
speech这个包3.3.2拉取有问题，speech-rule-engine作者几小时前更新过，晚点再试试。
或者自己拉取放到目录下https://github.com/zorkow/speech-rule-engine/releases 
tar.gz->tgz

**Comment by babizhu** [comment]
同样的问题，那我再等等

**Comment by chenshuai2144** [comment]
应该是npm 的问题，重新安装就好了

**Comment by travis-joe** [comment]
服务器上拉不到， 本地也不行， 看来要摸鱼了
