### ISSUE TITLE
🧐 在typings.d.ts为window增加属性报错

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#8595]
### 🧐 问题描述

为 `Window` 增加属性 然后再组件中使用，`vscode`会报未定义。

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/34082148/121642872-afb15500-cac3-11eb-8e1b-336241c5f0c3.png)

**Comment by chenshuai2144** [comment]
```
declare global {
    interface Window { MyNamespace: any; }
}
```

需要这样了，最近有一次更新

**Comment by 569202812** [comment]
>  MyNamespace: any;
在`/src/typings.d.ts` 里面写不管用的
![image](https://user-images.githubusercontent.com/34082148/121657692-34579f80-cad3-11eb-9a6c-346faeca6736.png)

**Comment by 569202812** [comment]
> ```
> declare global {
>     interface Window { MyNamespace: any; }
> }
> ```
> 
> 需要这样了，最近有一次更新

这个试了一下，还是有问题的麻烦解答一下

**Comment by zjfresh** [comment]
修改后重启下VSCode或F1 > Restart TS Server 试试

**Comment by 569202812** [comment]
> 修改后重启下VSCode或F1 > Restart TS Server 试试

试过了不可以

**Comment by 569202812** [comment]
改成`interface Window {   }` 就可以了
