### ISSUE TITLE
m1版本mac的simple版ant rpo在yarn start时卡在99%🧐[问题]

### ISSUE THREAD

**Issue by stwbadz** [ant-design/ant-design-pro#8596]
### 🧐 问题描述

ant design pro 的simple版本在start时会卡在99%，而complete一切正常

### 💻 示例代码

yarn create umi test （如果选simple会在start时卡住，complete则不会）
cd test
yarn install
yarn start

### 🚑 其他信息

卡在99%的状态，强行访问localhost 8001可以正常看到搭建的ui，但是按查询列表右侧会报错，SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at getRule (/Users/yushitech/Documents/cms/test/mock/listTableList.ts:47:23)

**Comment by chenshuai2144** [comment]
这个应该是网络请求错误，99 那个是最近的底层库更新导致一直到不了 100%

**Comment by stwbadz** [comment]
> > 卡在99%的状态，强行访问localhost 8001可以正常看到搭建的ui，但是按查询列表右侧会报错，SyntaxError: Unexpected token u in JSON at position 0
> > at JSON.parse ()
> > at getRule (/Users/yushitech/Documents/cms/test/mock/listTableList.ts:47:23)
> 
> 这个应该是网络请求错误，
> 
> 99 那个是最近的底层库更新导致一直到不了 100%

是要梯子的意思吗

**Comment by chenshuai2144** [comment]
不用的梯子，不影响开发和使用的
