### ISSUE TITLE
tree 初始数据（treeData）怎样从后台获取？

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#8597]
const [treeData, setTreeData] = useState([])

<Tree
          showLine={showLine}
          showIcon={showIcon}
         // loadData={ async ({ key, children }: any)=>{
          //  setTreeData(await getIndicatorNodes({key}))
         // }}
          treeData={treeData}
        />

**Comment by algz** [comment]
用异步的方式获取后，怎么填入？

**Comment by TangDeYu** [comment]
你把loadData的请求另写一个函数中，在useEffect调用一下，在用setTreeData函数把请求回来的数据赋值一下不行吗？

**Comment by fangqibin** [comment]
参照这个示例：https://ant.design/components/tree-cn/#components-tree-demo-dynamic
