### ISSUE TITLE
服务器500 导致antdesignpro项目报错     🧐[问题]

### ISSUE THREAD

**Issue by qq329401134** [ant-design/ant-design-pro#8599]
### 🧐 问题描述

项目报错

### 💻 示例代码

export const request: RequestConfig = {
  errorHandler: async (error: ResponseError) => {
    const { messages } = getIntl(getLocale());
    const { response, data } = error;
    if (response && response.status) {
      const { status, statusText, url } = response;
      const requestErrorMessage = messages['app.request.error'];
      const errorMessage = `${requestErrorMessage} ${status}: ${url}`;
      const errorDescription = data.errorMessage;
      notification.error({
        message: errorMessage,
        description: errorDescription,
      });
    }
    throw error;
  },
  requestInterceptors: [authHeaderInterceptor],
  responseInterceptors: [responseInterceptor],
};
这是目前使用的代码

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/38587734/121720841-21b28a00-cb16-11eb-8be5-26268444b404.png)
![image](https://user-images.githubusercontent.com/38587734/121720863-28410180-cb16-11eb-8add-a42883dbba3a.png)

@chenshuai2144    求助  谢谢了

**Comment by fangqibin** [comment]
这个不是应该先排查一下为什么500吗，接口调通了就好了

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/122501399-323b9680-d027-11eb-939a-430cc2ff83a7.png)


不想页面挂掉就处理一下这里

try catch 包裹一下。或者使用 onError
