### ISSUE TITLE
🧐[问题] v5 实现实时更换主题

### ISSUE THREAD

**Issue by marcustut** [ant-design/ant-design-pro#8600]
### 🧐 问题描述

![AntDesignDynamicTheme](https://user-images.githubusercontent.com/59773847/121739491-474b8d80-cb2e-11eb-9d84-3722d1bdc476.gif)

我正在尝试达成这个效果就是可以实时更换 Antd 主题但不知该如何在代码中去实现因为不知道怎么在程序运行中去更改 config，我已尝试在component中去执行 `defineConfig` 却不行

![image](https://user-images.githubusercontent.com/59773847/121740633-f2a91200-cb2f-11eb-9de4-806a1fc65e45.png)

### 💻 示例代码

暂时在 v5 我已知的更换主题方法仅是更改在 `config.ts` 中的 antd 变量

```ts
  antd: {
    dark: true,
  },
```

### 🚑 其他信息

无

**Comment by lishaoh** [comment]
+1

**Comment by ripple-xaz** [comment]
+1

**Comment by chenshuai2144** [comment]
https://github.com/darkreader/darkreader

你可能需要的是这个
