### ISSUE TITLE
🐛[BUG] Light menu in dark theme?

### ISSUE THREAD

**Issue by loia5tqd001** [ant-design/ant-design-pro#8601]
### 🐛 bug 描述

I expect the menu to be in dark theme in this case but it's light.

![image](https://user-images.githubusercontent.com/31364664/121765090-ae8b3100-cb72-11eb-8174-44a95e4f5e2b.png)

### 📷 复现步骤

1. Go to https://preview.pro.ant.design/dashboard/analysis?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false&layout=top&contentWidth=Fixed
2. Narrow down screen width so that it displays the three dots symbol
3. Hover on it.

**Comment by marcustut** [comment]
If you're using v5, you'll need to go to `config.ts` and add this to the `antd` variable

```ts
  antd: {
    dark: true,
  },
```

**Comment by loia5tqd001** [comment]
> If you're using v5, you'll need to go to `config.ts` and add this to the `antd` variable
> 
> ```ts
>   antd: {
>     dark: true,
>   },
> ```

No I don't want the dark theme. I only want that weird dropdown navigation to be dark as the rest of the Menu.

**Comment by chenshuai2144** [comment]
This is a bug that we'll fix this week
