### ISSUE TITLE
如何通过hook实现PageContainer标签中this.props.children功能🧐[问题]

### ISSUE THREAD

**Issue by liuxinwang** [ant-design/ant-design-pro#8602]
### 🧐 问题描述
如何通过hook而非Component实现PageContainer标签中this.props.children展示子组件

**Comment by chenshuai2144** [comment]
展开说一下？我没理解你的意思

**Comment by lishaoh** [comment]
export default function Test({children}) {

   return <div>{children}</div>
}

使用时：<Test>
                 <div>这是children</div>
             </Test>


这样使用？
