### ISSUE TITLE
v5 自定义布局下 layout=mix, splitMenus=true二级菜单不显示

### ISSUE THREAD

**Issue by xzf123456** [ant-design/ant-design-pro#8604]
v5 自定义布局下 layout=mix, splitMenus=true二级菜单不显示
**路由配置项：**
```
{
        path: '/project',
        layout: false,
        component: '../layouts/ProjectLayout',
        routes: [
            {
                path: '/project',
                redirect: '/project/home',
            },
            {
                path: '/project/home',
                name: 'home',
                routes:[{
                    path: '/project/home',
                    redirect: '/project/home/view',
                },{
                    path: '/project/home/view',
                    name: 'view',
                    hideInMenu: true,
                    component: './Project/Home',
                }, {
                        path: '/project/detail/:id',
                        hideInMenu: true,
                        name: 'detail',
                        component: './Manage/Reservoir/projectDetail'
                    },
                ]
            },
            {
                path: '/project/data',
                name: 'data',
                component: './Project/Data',
            }, {
                path: '/project/point',
                name: 'point',
                routes: [{
                    path: '/project/point',
                    redirect: '/project/point/manage',
                },{
                    path: '/project/point/manage',
                    name: 'point-manage',
                    component: './Project/Point/PointManage',
                },{
                    path: '/project/point/project',
                    name: 'point-project',
                    component: './Project/Point/PointProject',
                },{
                    path: '/project/point/location',
                    name: 'point-location',
                    component: './Project/Point/PointLocation',
                }]
            }, {
                path: '/project/device',
                name: 'device',
                component: './Project/Device',
            }, {
                path: '/project/alarm',
                name: 'alarm',
                component: './Project/Alarm',
            }, {
                path: '/project/formula',
                name: 'formula',
                routes:[{
                    path: '/project/formula',
                    redirect: '/project/formula/list',
                },{
                    path: '/project/formula/list',
                    hideInMenu: true,
                    name: 'formula-list',
                    component: './Project/Formula',
                }, {
                    path: '/project/formula/add',
                    hideInMenu: true,
                    name: 'formula-add',
                    component: './Project/Formula/addFormula',
                }, {
                    path: '/project/formula/edit/:id',
                    hideInMenu: true,
                    name: 'formula-edit',
                    component: './Project/Formula/editFormula',
                }]
            },
        ],
    }
**自定义layout:**

/**
 * Ant Design Pro v4 use `@ant-design/pro-layout` to handle Layout.
 *
 * @see You can view component api by: https://github.com/ant-design/ant-design-pro-layout
 */
import {
    MenuDataItem,
    BasicLayoutProps as ProLayoutProps,
    Settings,
} from '@ant-design/pro-layout';
import ProLayout, { DefaultFooter } from '@ant-design/pro-layout';
import React from 'react';
import { Link, useIntl,history } from 'umi';
import { GithubOutlined } from '@ant-design/icons';
import logo from '../../public/logo.png';
import RightContent from '@/components/RightContent';
import defaultSettings from '../../config/defaultSettings';
export type BasicLayoutProps = {
    breadcrumbNameMap: Record<string, MenuDataItem>;
    route: ProLayoutProps['route'] & {
        authority: string[];
    };
    settings: Settings;
} & ProLayoutProps;

export type BasicLayoutContext = { [K in 'location']: BasicLayoutProps[K] } & {
    breadcrumbNameMap: Record<string, MenuDataItem>;
};

const menuDataRender = (menuList: MenuDataItem[]): MenuDataItem[] =>{
    return menuList.map((item) => {
        return {
            ...item,
            children: item.children ? menuDataRender(item.children) : undefined,
        };
    });
}


const defaultFooterDom = (
    <DefaultFooter
        copyright={`${new Date().getFullYear()} 蚂蚁集团体验技术部出品`}
        links={[
            {
                key: 'Ant Design Pro',
                title: 'Ant Design Pro',
                href: 'https://pro.ant.design',
                blankTarget: true,
            },
            {
                key: 'github',
                title: <GithubOutlined />,
                href: 'https://github.com/ant-design/ant-design-pro',
                blankTarget: true,
            },
            {
                key: 'Ant Design',
                title: 'Ant Design',
                href: 'https://ant.design',
                blankTarget: true,
            },
        ]}
    />
);

const ProjectLayout: React.FC<BasicLayoutProps> = (props) => {
    const {
        children,
        location = {
            pathname: '/',
        },
    } = props;

    const { formatMessage } = useIntl();

    return (
        <ProLayout
            {...defaultSettings}
            title={'新疆水科院中小水库云平台'}
            logo={logo}
            formatMessage={formatMessage}
            {...props}
            onMenuHeaderClick={() => history.push('/')}
            menuItemRender={(menuItemProps, defaultDom) => {
                if (
                    menuItemProps.isUrl ||
                    !menuItemProps.path ||
                    location.pathname === menuItemProps.path
                ) {
                    return defaultDom;
                }
                return <Link to={menuItemProps.path}>{defaultDom}</Link>;
            }}
            breadcrumbRender={(routers = []) => [
                {
                    path: '/',
                    breadcrumbName: formatMessage({ id: 'menu.home' }),
                },
                ...routers,
            ]}
            itemRender={(route, params, routes, paths) => {
                const first = routes.indexOf(route) === 0;
                return first ? (
                    <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
                ) : (
                    <span>{route.breadcrumbName}</span>
                );
            }}
            footerRender={() => defaultFooterDom}
            menuDataRender={menuDataRender}
            rightContentRender={() => <RightContent />}
        >
            {children}
        </ProLayout>
    );
};

export default ProjectLayout;
```

**defaultSetting:**

/**
 * Ant Design Pro v4 use `@ant-design/pro-layout` to handle Layout.
 *
 * @see You can view component api by: https://github.com/ant-design/ant-design-pro-layout
 */
import {
    MenuDataItem,
    BasicLayoutProps as ProLayoutProps,
    Settings,
} from '@ant-design/pro-layout';
import ProLayout, { DefaultFooter } from '@ant-design/pro-layout';
import React from 'react';
import { Link, useIntl,history } from 'umi';
import { GithubOutlined } from '@ant-design/icons';
import logo from '../../public/logo.png';
import RightContent from '@/components/RightContent';
import defaultSettings from '../../config/defaultSettings';
export type BasicLayoutProps = {
    breadcrumbNameMap: Record<string, MenuDataItem>;
    route: ProLayoutProps['route'] & {
        authority: string[];
    };
    settings: Settings;
} & ProLayoutProps;

export type BasicLayoutContext = { [K in 'location']: BasicLayoutProps[K] } & {
    breadcrumbNameMap: Record<string, MenuDataItem>;
};

const menuDataRender = (menuList: MenuDataItem[]): MenuDataItem[] =>{
    return menuList.map((item) => {
        return {
            ...item,
            children: item.children ? menuDataRender(item.children) : undefined,
        };
    });
}

const defaultFooterDom = (
    <DefaultFooter
        copyright={`${new Date().getFullYear()} 蚂蚁集团体验技术部出品`}
        links={[
            {
                key: 'Ant Design Pro',
                title: 'Ant Design Pro',
                href: 'https://pro.ant.design',
                blankTarget: true,
            },
            {
                key: 'github',
                title: <GithubOutlined />,
                href: 'https://github.com/ant-design/ant-design-pro',
                blankTarget: true,
            },
            {
                key: 'Ant Design',
                title: 'Ant Design',
                href: 'https://ant.design',
                blankTarget: true,
            },
        ]}
    />
);

const ProjectLayout: React.FC<BasicLayoutProps> = (props) => {
    const {
        children,
        location = {
            pathname: '/',
        },
    } = props;

    const { formatMessage } = useIntl();

    return (
        <ProLayout
            {...defaultSettings}
            title={'新疆水科院中小水库云平台'}
            logo={logo}
            formatMessage={formatMessage}
            {...props}
            onMenuHeaderClick={() => history.push('/')}
            menuItemRender={(menuItemProps, defaultDom) => {
                if (
                    menuItemProps.isUrl ||
                    !menuItemProps.path ||
                    location.pathname === menuItemProps.path
                ) {
                    return defaultDom;
                }
                return <Link to={menuItemProps.path}>{defaultDom}</Link>;
            }}
            breadcrumbRender={(routers = []) => [
                {
                    path: '/',
                    breadcrumbName: formatMessage({ id: 'menu.home' }),
                },
                ...routers,
            ]}
            itemRender={(route, params, routes, paths) => {
                const first = routes.indexOf(route) === 0;
                return first ? (
                    <Link to={paths.join('/')}>{route.breadcrumbName}</Link>
                ) : (
                    <span>{route.breadcrumbName}</span>
                );
            }}
            footerRender={() => defaultFooterDom}
            menuDataRender={menuDataRender}
            rightContentRender={() => <RightContent />}
        >
            {children}
        </ProLayout>
    );
};

export default ProjectLayout;

```

**Comment by xzf123456** [comment]
页面截图：
![image](https://user-images.githubusercontent.com/58057891/122001115-6b36f980-cde2-11eb-90df-a2975b587306.png)

**Comment by chenshuai2144** [comment]
`      menuData = props.menuData?.find((item) => item.key === key)?.children || [];

`
算法是这样的，你看看你配置的顶部的 pathname 是不是对应的菜单没有 children

**Comment by xzf123456** [comment]
> ` menuData = props.menuData?.find((item) => item.key === key)?.children || [];
> 
> `
> 算法是这样的，你看看你配置的顶部的 pathname 是不是对应的菜单没有 children

有二级菜单的
配置片段代码如下：
{
        path: '/project',
        layout: false,
        component: '../layouts/ProjectLayout',
        routes: [
            {
                path: '/project',
                redirect: '/project/home',
            },
            {
                path: '/project/home',
                name: 'home',
                routes:[{
                    path: '/project/home',
                    redirect: '/project/home/view',
                },{
                    path: '/project/home/view',
                    name: 'view',
                    hideInMenu: true,
                    component: './Project/Home',
                }, {
                        path: '/project/detail/:id',
                        hideInMenu: true,
                        name: 'detail',
                        component: './Manage/Reservoir/projectDetail'
                    },
                ]
            },
            {
                path: '/project/data',
                name: 'data',
                component: './Project/Data',
            }, {
                path: '/project/point',
                name: 'point',
                routes: [{
                    path: '/project/point',
                    redirect: '/project/point/manage',
                },{
                    path: '/project/point/manage',
                    name: 'point-manage',
                    component: './Project/Point/PointManage',
                },{
                    path: '/project/point/project',
                    name: 'point-project',
                    component: './Project/Point/PointProject',
                },{
                    path: '/project/point/location',
                    name: 'point-location',
                    component: './Project/Point/PointLocation',
                }]
            }, {
                path: '/project/device',
                name: 'device',
                component: './Project/Device',
            }, {
                path: '/project/alarm',
                name: 'alarm',
                component: './Project/Alarm',
            }, {
                path: '/project/formula',
                name: 'formula',
                routes:[{
                    path: '/project/formula',
                    redirect: '/project/formula/list',
                },{
                    path: '/project/formula/list',
                    hideInMenu: true,
                    name: 'formula-list',
                    component: './Project/Formula',
                }, {
                    path: '/project/formula/add',
                    hideInMenu: true,
                    name: 'formula-add',
                    component: './Project/Formula/addFormula',
                }, {
                    path: '/project/formula/edit/:id',
                    hideInMenu: true,
                    name: 'formula-edit',
                    component: './Project/Formula/editFormula',
                }]
            },
        ],
    }

**Comment by xzf123456** [comment]
> ` menuData = props.menuData?.find((item) => item.key === key)?.children || [];
> 
> `
> 算法是这样的，你看看你配置的顶部的 pathname 是不是对应的菜单没有 children

使用默认布局是没问题的，自定义布局有问题

**Comment by xzf123456** [comment]
> ` menuData = props.menuData?.find((item) => item.key === key)?.children || [];
> 
> `
> 算法是这样的，你看看你配置的顶部的 pathname 是不是对应的菜单没有 children
打印出来也有children 的 ：
![image](https://user-images.githubusercontent.com/58057891/123214598-02463480-d4fa-11eb-8e27-1bd6612fad1d.png)
