### ISSUE TITLE
🧐 [问题] web服务器更新的时候，刚好切换路由加载不成功，更新完之后，再次点击该路由页面无法重新加载?

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#8605]
如题：
web服务器更新的时候，刚好切换路由页面加载不成功，更新完之后，再次点击该路由页面无法重新加载?
请问该如何解决这个问题？

**Comment by chenshuai2144** [comment]
这个一般都是通过复杂均衡来实现的，每次更新只更新一台机器，还有一台机器是能提供工作的。
