### ISSUE TITLE
🧐[问题] V5 在 node 12.x 环境下 npm run i18n-remove 会报语法错误

### ISSUE THREAD

**Issue by lvbowen** [ant-design/ant-design-pro#8607]
### 🧐 问题描述
node: v12.13.1
npm: v6.12.1

执行 npm run i18n-remove 报语法错误

### 💻 示例代码

![image](https://user-images.githubusercontent.com/17351126/122372896-a0367e00-cf93-11eb-9674-b8079e5d5010.png)

### 🚑 其他信息
我切换到 node v14.17.0 是正常的，建议文档上能对 node 版本要求能有说明。

**Comment by chenshuai2144** [comment]
可以先升级一下 node 支持一下这个 function
