### ISSUE TITLE
ProTable valueType  查询如何实现下拉多选 ？🧐[问题]

### ISSUE THREAD

**Issue by renjinjie** [ant-design/ant-design-pro#8609]

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/schema#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE

看看这个文档

**Comment by renjinjie** [comment]
![image](https://user-images.githubusercontent.com/55084495/122501481-5c8d5400-d027-11eb-9dfe-912b42a58664.png)

**Comment by renjinjie** [comment]
您好，这个文档我没太看懂，我想实现<Select>中的mode='multiple'

**Comment by lovewaner** [comment]
ProTable的Columns 列定义里面有个renderFormItem，你可以自定义渲染查询表单的输入组件

**Comment by AceLing** [comment]
`fieldProps: {
  mode: 'multiple',
  placeholder: 'Select one or more',
},`
