### ISSUE TITLE
🧐[问题]PRO V5线上预览的基础表单与本地的基础表单样式不一致

### ISSUE THREAD

**Issue by wangchun0020** [ant-design/ant-design-pro#8610]
### 🧐 问题描述
PRO V5 下载完整版的模板后发现，PRO线上预览的基础表单与本地的基础表单样式不一致，请问这个是因为最新的规范更新了的原因吗？

### 💻 示例代码
![image](https://user-images.githubusercontent.com/8032943/122505660-61560600-d02f-11eb-8202-cce8e1040e1b.png)

![image](https://user-images.githubusercontent.com/8032943/122505813-ac701900-d02f-11eb-82a0-2a84b9b6253a.png)

**Comment by w345731923** [comment]
v5没有完整版吧，v4可以选blocks
yarn create umi myapp
ant-design-pro
Pro V5

**Comment by chenshuai2144** [comment]
fixed
