### ISSUE TITLE
🐛[BUG] 刚进去页面接口控制台报错没动代码

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8611]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20655248/122520922-ce28ca80-d046-11eb-80df-d1e2267a348a.png)
![image](https://user-images.githubusercontent.com/20655248/122520973-dd0f7d00-d046-11eb-8a8b-a2823c6c5508.png)
![image](https://user-images.githubusercontent.com/20655248/122521015-eac50280-d046-11eb-8263-02a9b74b1cc1.png)

**Comment by 569202812** [comment]
没启动mock吧

**Comment by zjfresh** [comment]
npm run dev/start:dev  是正常开发联调自己服务端的脚本

npm run start 才是本地运行mock数据的

两个控制台报错都是依赖内容版本兼容问题……，还是有点坑的，在迭代过程中也要好好打磨啊

第一个错误见 #6517
yarn add dva@2.6.0-beta.20

第一个见 #6518
这个就比较麻烦了，很多代码里面有用到formatMessage，需要：
```js
import { formatMessage } from 'umi';

- const rankingListData: { title: string; total: number }[] = [];
- for (let i = 0; i < 7; i += 1) {
-   rankingListData.push({
-     title: formatMessage({ id: 'dashboardandanalysis.analysis.test' }, { no: i }),
-     total: 323234,
-   });
- }

const SalesCard = () => {
    return (
        <div>代码中的DOM</div>
    );
}
export default SalesCard;
```
修改如下
```js
import { useIntl } from 'umi';

const SalesCard = () => {
+    const intl = useIntl()
+    const rankingListData: { title: string; total: number }[] = [];
+    for (let i = 0; i < 7; i += 1) {
+      rankingListData.push({
+        title: intl.formatMessage({ id: 'dashboardandanalysis.analysis.test' }, { no: i }),
+        total: 323234,
+      });
+    }
    return (
        <div>代码中的DOM</div>
    );
}
export default SalesCard;
```

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-blocks/pull/332
