### ISSUE TITLE
🐛[BUG]   path携带redirect重定向到路由组件会渲染多次

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#8613]
### 🐛 bug 描述
退出登录，再重新登录后，路由组件会渲染多次

### 📷 复现步骤

1. 正常登录进入首页 “/welcome”
2. 然后点击**管理页**的**二级管理页**后，点击退出，url后追加redict路由（供再登陆重定向）
3. 退出登录页后，再正常登录，如下方截图组件会渲染多次

### 🏞 期望结果

不希望渲染多次，如果这个组件初始化出现多个api接口请求，岂不是炸了；

### 💻 复现代码

https://github.com/ISBN9527/umi-access-demo

### © 版本信息

- Ant Design Pro 版本:  v5
- umi 版本 3.4
- 浏览器环境   谷歌
- 开发环境  Mac os

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/122715390-5f907a80-d29b-11eb-8c48-b217b09f6e1f.png)

**Comment by ISBN9527** [comment]
@chenshuai2144

**Comment by ISBN9527** [comment]
救救孩子吧，实在找不到原因

**Comment by jiazhuangle** [comment]
这个二级菜单本身好像就有问题，现实的不是component: './Welcome',也没有smile

**Comment by ISBN9527** [comment]
> 这个二级菜单本身好像就有问题，现实的不是component: './Welcome',也没有smile

啥意思？

**Comment by ISBN9527** [comment]
大佬救命，有人吗

**Comment by lishaoh** [comment]
救救孩子吧

**Comment by 569202812** [comment]
你是想把 `redirect` 取消吗

**Comment by ISBN9527** [comment]
我不想取消，但这个问题挂在多次解决不了就很尴尬

**Comment by fangqibin** [comment]
![image](https://user-images.githubusercontent.com/15991882/122897891-fda84180-d37c-11eb-9011-12eea515954d.png)

**Comment by fangqibin** [comment]
这样修改试一下

**Comment by ISBN9527** [comment]
不行，组件加上memo也不行
现在不得不把这个鸡肋注释掉

**Comment by ISBN9527** [comment]
> 这样修改试一下

不行，组件加上memo也不行
现在不得不把这个鸡肋注释掉

**Comment by 569202812** [comment]
> 不行，组件加上memo也不行
> 现在不得不把这个鸡肋注释掉

这样我试了下可以啊

**Comment by fangqibin** [comment]
> > 这样修改试一下
> 
> 不行，组件加上memo也不行
> 现在不得不把这个鸡肋注释掉

截图错了，用我注释掉的那一行，window.location.href = xxx

**Comment by ISBN9527** [comment]
这个可以，修复了多次渲染，但感觉不太丝滑，哈哈哈😀

**Comment by ISBN9527** [comment]
为啥location可以，history.push不行,纳闷

**Comment by 569202812** [comment]
> 为啥location可以，history.push不行,纳闷
@chenshuai2144 我也很好奇能否解答下

**Comment by ISBN9527** [comment]
@chenshuai2144 大佬，你是不是又去结婚了

**Comment by ISBN9527** [comment]
@sorrycc

**Comment by lizibeite** [comment]
history: {
    type: 'browser',
  },
这个模式下 好像不会多次渲染

**Comment by chenshuai2144** [comment]
已经修掉咯，可以刷新重试了
