### ISSUE TITLE
🧐[问题] 有啥办法可以发送同步请求嘛

### ISSUE THREAD

**Issue by diaomina** [ant-design/ant-design-pro#8614]
### 🧐 问题描述

有啥办法可以发送同步请求嘛，想进行同步请求，期望返回的直接是具体数据并不是promise。或者如何在antd pro内引入jquery

**Comment by ISBN9527** [comment]
`async await`了解下

**Comment by diaomina** [comment]
> `async await`了解下

因为调用的地方是一个子项目无法改动，是直接接收数据的，所以用不了await

**Comment by diaomina** [comment]
。
