### ISSUE TITLE
antd pro 如何适配所有分辨率？

### ISSUE THREAD

**Issue by yangbo3714** [ant-design/ant-design-pro#8617]
### 

version: antd pro v4 for react
基于: 1024 屏幕开发
如何快速实现适配所有分辨率

**Comment by yangbo3714** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [#8516][🧐[问题]antd pro v5在routes.ts配置好路由启动后，点击菜单显示404][69%]
> * [#8598][🐛[BUG]antd pro v5退出登录按钮，按了没有反应。][67%]

这个貌似不能够解决我的问题

**Comment by chenshuai2144** [comment]
现在 pro 是支持的，你能提供更详细的说明吗？
