### ISSUE TITLE
🧐[问题]顶部菜单的下拉选项怎么居中显示呢？

### ISSUE THREAD

**Issue by EvanYin** [ant-design/ant-design-pro#8620]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/8558105/123026481-d69a5000-d40e-11eb-9a52-1222b4d084d9.png)

这个悬浮上去之后展示的子菜单默认样式是左对齐，导致看上去有点偏右，怎么让这个子菜单和顶部的菜单居中对齐呢？

**Comment by lishaoh** [comment]
改CSS样式

**Comment by EvanYin** [comment]
> 改CSS样式

找了一圈没有找到应该改哪个样式，求指导

**Comment by lishaoh** [comment]
![image](https://user-images.githubusercontent.com/20917295/123052944-f2fdb300-d435-11eb-96c1-de9ce165dda6.png)

是对齐的
antd v4.x

**Comment by EvanYin** [comment]
> ![image](https://user-images.githubusercontent.com/20917295/123052944-f2fdb300-d435-11eb-96c1-de9ce165dda6.png)
> 
> 是对齐的
> antd v4.x

这个还是左对齐的，我想要子菜单和顶层菜单等宽，并且左右对齐

**Comment by lishaoh** [comment]
如果子菜单文字比顶层菜单多，等宽的话子菜单不就得换行了，那多难看（个人观点）

**Comment by chenshuai2144** [comment]
hack 是不好的，建议使用 antd 自带的
