### ISSUE TITLE
🧐[问题] 配置使用了CDN方式引入组件，部分组件的主题颜色被覆盖

### ISSUE THREAD

**Issue by BoWang816** [ant-design/ant-design-pro#8621]
### 🧐 问题描述
默认主题设置了红色，按钮以及菜单颜色变成了蓝色。

通过使用externals在config.ts中配置了相关的设置
![image](https://user-images.githubusercontent.com/26587649/123048422-f80c3380-d430-11eb-94d0-53d0d4a4068a.png)
然后在scripts属性中引入CDN文件
![image](https://user-images.githubusercontent.com/26587649/123048445-00fd0500-d431-11eb-9576-f7ca40c625d9.png)
同时在document.ejs中引入相关的css文件
![image](https://user-images.githubusercontent.com/26587649/123048617-2b4ec280-d431-11eb-984a-2970ee17c3c9.png)

但是会出现按钮、菜单、下拉框主题颜色被修改的情况。

## 正常情况
![image](https://user-images.githubusercontent.com/26587649/123048767-589b7080-d431-11eb-92bb-d5dad3e93116.png)

## 开启pro-form或pro-table或pro-list任意一个CDN配置后：
![image](https://user-images.githubusercontent.com/26587649/123049041-aca65500-d431-11eb-9435-df7c33134fd3.png)

不知道是什么情况呢？

### 💻 示例代码
document.ejs
`
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ant-design/pro-form@1.29.1/dist/form.min.css">
`

config.ts
```
externals: {
    '@ant-design/pro-form': 'window.ProForm',
  },
scripts: ['https://cdn.jsdelivr.net/npm/@ant-design/pro-form@1.29.1/dist/form.min.js']
```

**Comment by chenshuai2144** [comment]
externals  和 换主题不能共存
