### ISSUE TITLE
手机号登录获取验证码，手机号参数为空🐛[BUG]

### ISSUE THREAD

**Issue by sunknightzy** [ant-design/ant-design-pro#8622]
### 🐛 bug 描述
手机号登录获取验证码，手机号参数为空

### 📷 复现步骤
打开V5版本的预览网址，切换到手机号登录，输入手机号，点击获取验证码，在控制台可以看到传参mobile没有值

### 🏞 期望结果

传参不为空

### 💻 复现代码

https://github.com/ant-design/ant-design-pro/blob/v5/src/pages/user/Login/index.tsx
```
    onGetCaptcha={async (phone) => {
      // 这里的phone为空，换成mobile也是空
      const result = await getFakeCaptcha({
        phone,
      });
      if (result === false) {
        return;
      }
      message.success('获取验证码成功！验证码为：1234');
    }}
```

### © 版本信息

- Ant Design Pro 版本: [5.0]
- umi 版本
- 浏览器环境 Chrome
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/67646599/123120732-23b20c80-d477-11eb-8e0b-164414d9fe44.png)

**Comment by fangqibin** [comment]
ProFormCaptcha 组件加个参数phoneName="mobile"

**Comment by fangqibin** [comment]
> ProFormCaptcha 组件加个参数phoneName="mobile"
