### ISSUE TITLE
🧐[问题]v5版本里面的折叠按钮默认是在侧边栏上，没看到有暴露出来的配置可以把它换到header上，应该怎么修改？

### ISSUE THREAD

**Issue by Roxannej** [ant-design/ant-design-pro#8624]

**Comment by Roxannej** [comment]
如题

**Comment by chenshuai2144** [comment]
要用 headerRender 配合 collapsed 来实现

https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed

https://procomponents.ant.design/~demos/layout-customize-collapsed
