### ISSUE TITLE
🐛[BUG] rowSelection翻页后选中行丢失

### ISSUE THREAD

**Issue by JefferyChensp** [ant-design/ant-design-pro#8625]
### 🐛 bug 描述
ProTable勾选行后，进行翻页，之前勾选的选项丢失。

### 🏞 期望结果
ProTable勾选行后，进行翻页，保留勾选的选项。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
附上table配置代码，应该是你选中的没有保存

**Comment by JefferyChensp** [comment]
> 附上table配置代码，应该是你选中的没有保存

可以参考下ant design pro 官网的 例子就存在这个问题
[https://preview.pro.ant.design/list/table-list?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false](url)

**Comment by JefferyChensp** [comment]
解决了，加一个参数`preserveSelectedRowKeys: true`就行，目测是新版本特性
参考 [https://ant-design.gitee.io/components/table-cn/#rowSelection](url)
![image](https://user-images.githubusercontent.com/42525845/124251371-6ac78e00-db58-11eb-81ab-583983c59eb8.png)
