### ISSUE TITLE
🧐[问题] proTable内valueEnum设置title未生效

### ISSUE THREAD

**Issue by diaomina** [ant-design/ant-design-pro#8626]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/40923075/123215615-3ff78d00-d4fb-11eb-9ced-827e7793c3f7.png)

![image](https://user-images.githubusercontent.com/40923075/123215654-4d147c00-d4fb-11eb-9f05-630f3eb1ee59.png)

![image](https://user-images.githubusercontent.com/40923075/123215732-64536980-d4fb-11eb-9d43-18ac6f5e8b44.png)

### 💻 示例代码

```
valueEnum: () => {
        const valueEnumMap = new Map();
        valueEnumMap.set('2', {
          text: "已部署",
          // todo: 未生效，源码内无该属性，官方文档内存在
          title: "已部署(重设计后未部署)",
          status: 'Warning',
        });
        return valueEnumMap;
      },
```

### 🚑 其他信息

有啥简单快捷的办法设置悬浮提示的文字嘛

**Comment by chenshuai2144** [comment]
只支持text，如果你要自定义，可以用 fieldProps
