### ISSUE TITLE
Forms/TableForm.js 下有冗余代码

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design-pro#863]
https://github.com/ant-design/ant-design-pro/blob/master/src/routes/Forms/TableForm.js#L26

handleSubmit 没有被调用。

**Comment by ddcat1115** [comment]
https://github.com/ant-design/ant-design-pro/commit/5c08dabd9f1bcb87951b423df93f20e19d7111a2

**Comment by chenshuai2144** [comment]
那个需要在save的是否调用一下把
