### ISSUE TITLE
umi-request拦截器

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8631]
### 🥰 需求描述

umi-request的拦截器 能否拦截到iframe里面的请求 。以前的一些老项目集成到新搭建的框架里面通过iframe嵌套老项目地址，拦截器能否拦截到iframe里面的请求 我知道这属于跨域了，但是我还是想能否不去继续维护老代码 直接改新的框架代码就能实现全局统一处理请求拦截。

**Comment by fangqibin** [comment]
请求跟拦截器是一一对应的。要在你发的请求request处做拦截。umi-request只是一个请求方式而已。你也有可能是用别的方式请求。所以umi-request的拦截器 不可能拦截到iframe里面的请求

**Comment by lovesL** [comment]
感谢 我知道了 或许只能通过postmessage了
