### ISSUE TITLE
🧐[问题]异步加载类型的树，怎么通过key定位到树节点？

### ISSUE THREAD

**Issue by EvanYin** [ant-design/ant-design-pro#8632]
### 🧐 问题描述
异步加载类型的树，怎么通过key定位到树节点？
想要的效果：url中会有一个key，访问页面的时候能够自动展开当前key的树节点，并且处于选中状态

**Comment by chenshuai2144** [comment]
antd 中的做法是将树打平做成一个 map，

`Map<Key，Item>` ,然后通过key 来获取
