### ISSUE TITLE
Proform中的表单项部分属性无效。

### ISSUE THREAD

**Issue by luka26** [ant-design/ant-design-pro#8633]
### 🧐 问题描述
跑第一个PromFormText部分属性无效，比如size,官网文档说ProFormText
与 Input 相同，但是设置size无效只能自定义去修改。

**Comment by chenshuai2144** [comment]
一个表单除了 Form 之外还是需要一系列的表单项，ProForm 自带了数量可观的表单项, 这些组件本质上是 Form.Item 和 组件的结合，我们可以帮他们当成一个 FormItem 来使用，并且支持各种 props**。每个表单项都支持 fieldProps 属性来支持设置输入组件的props。** 我们支持了 placeholder 的透传，你可以直接在组件上设置 placeholder。

每个表单项同时也支持了 readonly ，不同的组件会有不同的只读样式，与 disable 相比 readonly 展示更加友好。生成的 dom 也更小，比如 ProFormDigit 会自动格式化小数位数。
