### ISSUE TITLE
🧐[问题] 在layout:"mix",splitMenus:true,怎么设置二级路由及以下隐藏，一级菜单显示

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design-pro#8635]
### 🧐 问题描述

如图，在进入某二级路由时，想隐藏左侧导航

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/30942709/123507819-32c6d380-d69e-11eb-8c84-04391e78581b.png)

**Comment by ISBN9527** [comment]
有大佬指点一二吗

**Comment by ISBN9527** [comment]
@pmq20 @andriijas @afc163

**Comment by chenshuai2144** [comment]
已经在procompents里加了
