### ISSUE TITLE
🧐[问题]我这样重写组件样式哪里错了为什么无效?

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#8638]
### 🧐 问题描述
 
![image](https://user-images.githubusercontent.com/33146207/123510984-4465a680-d6b1-11eb-917c-c6e9f1d53c44.png)
index.less
![image](https://user-images.githubusercontent.com/33146207/123511033-8abb0580-d6b1-11eb-9121-94ee765e6d82.png)
组件文件
![image](https://user-images.githubusercontent.com/33146207/123511067-c1911b80-d6b1-11eb-9e91-2d877621d4ae.png)

**Comment by chenshuai2144** [comment]
你看看 className 搞定了吗？
