### ISSUE TITLE
🧐[问题]获取路由参数报错

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#8639]
### 🐛 bug 描述
报错信息: TS2339: Property 'match' does not exist on type '{ children?: ReactNode; }'.
可以正常获取id参数并打印, 但是match报错
![e1641e6916af3dffbe0276336e5fd8b](https://user-images.githubusercontent.com/33146207/123511689-62350a80-d6b5-11eb-9807-bcb6314d9336.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
类型错误 你的类型没写对

建议用 hooks 
https://umijs.org/api#useparams
