### ISSUE TITLE
🧐[问题] - 打包命令可以控制选择需要打包的功能文件吗 

### ISSUE THREAD

**Issue by rodchen-king** [ant-design/ant-design-pro#8641]
### 🧐 问题描述
假设项目存在10个菜单，20个功能页面，我想在在打包的时候动态控制，只需要打包其中的10个菜单，20个功能页面，可以做到吗

**Comment by chenshuai2144** [comment]
可以用环境变量控制使用不同的 config文件




https://umijs.org/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE

**Comment by rodchen-king** [comment]
@chenshuai2144 这里是通过config里的路由来控制打包多少文件的是吗？

**Comment by chenshuai2144** [comment]
对的，自己定义其实有点难的，但是用路由的维度让 webpack 来搞就会简单很多
