### ISSUE TITLE
🧐[问题]项目可以运行, 但build时报错: Can't resolve '@@/dumi/apis'

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#8645]
### 🧐 问题描述
 
![image](https://user-images.githubusercontent.com/33146207/123725875-79e0de80-d8c1-11eb-994d-22d0a3468f10.png)
 ./node_modules/@umijs/preset-dumi/lib/theme/hooks/useApiData.js 21:36-59

**Comment by wangshangkun** [comment]
我也有一样的问题 请问你是如何解决的呢？

**Comment by onionnet606** [comment]
> 我也有一样的问题 请问你是如何解决的呢？
> 

我是因为重命名时WebStorm把不该重命名的也重命名了，重装依赖解决。

**Comment by darknessjs** [comment]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/10798107/150247709-989aa6b9-b3f1-4025-8255-cb60b9a7ba30.png">
近期导致该问题的修复
