### ISSUE TITLE
🧐[问题]v5版本下嵌套布局app.tsx的layout如何配置

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-pro#8646]
### 🧐 问题描述

如果是嵌套的layout，app.tsx里面的layout如何配置。我想实现的效果是https://procomponents.ant.design/~demos/layout-nested

**Comment by fangqibin** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
app.tsx 有个 childrenRender 的API ，你可以在里面再嵌入一个 ProLayout

**Comment by fangqibin** [comment]
> app.tsx 有个 childrenRender 的API ，你可以在里面再嵌入一个 ProLayout

菜单不会高亮这个怎么解决。我看示例代码也不会高亮。
