### ISSUE TITLE
🧐[问题]登录成功之后，页面右侧配置栏怎么取消显示？ 我发布生产环境还是会显示

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#8647]
### 🧐 问题描述

我登陆成功，页面右侧会显示配置栏，可以进行主题，样式，模式等设置，但是这个我在生产环境不需要他显示，我看官方文档说明是生产环境会自动不显示，但是这个一直在显示，无法取消，想问下怎么取消掉

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29156872/123729753-13ab8a00-d8c8-11eb-8717-cadb9b06a336.png)
![image](https://user-images.githubusercontent.com/29156872/123729818-24f49680-d8c8-11eb-86fe-fcb9c93cf8ee.png)

**Comment by chenshuai2144** [comment]
搜一下 settingDrawer 然后将其删除，或者用环境变量判断要不要再 prod 环境显示。

```tsx
let env = process.env.NODE_ENV

let baseUrl = ''

if (env === 'development') {
  baseUrl = urlDev
} else if (env === 'production') {
  baseUrl = urlProd
}
```

**Comment by jmy1944311667** [comment]
> 找一下设置抽屉然后将其删除，或者用环境变量判断要不要再生产环境显示。
> 
> ```tsx
> 让 env  = 进程。ENV 。NODE_ENV
> 
> 让 baseUrl  =  ''
> 
> 如果 （ENV  ===  '发展' ） {
>   的baseUrl  =  urlDev 
> } 否则 如果 （ENV  ===  '生产' ） {
>   的baseUrl  =  urlProd 
> }
> ```

谢谢

**Comment by alvinlee001** [comment]
hi, may i know which file is this? I am using antd pro 5.0.0, i cannot find the above mentioned settings
