### ISSUE TITLE
🧐[问题]页面跳转时标题(title)丢失

### ISSUE THREAD

**Issue by Chocomoon** [ant-design/ant-design-pro#8648]
### 🧐 问题描述

页面跳转时出现标题(title)丢失的情况，即原title为“数据标注-XX数据平台”，在切换子页面后变成了“XX数据平台”，并且页面左上角的标题显示也会变化，如附图所示。

### 💻 示例代码
该页面路由配置为:
```
  {
    name: '数据标注',
    icon: 'smile',
    path: '/dataset/:datasetId/:fileName/',
    exact: false,
    component: './Annotation',
    hideInBreadcrumb: true,
    hideInMenu: true,
  },
```
### 🚑 其他信息
当跳转至url: `http://localhost:8000/dataset/A/B/` 时，匹配到上述路由配置，载入组件Annotation，此时页面显示为
![image](https://user-images.githubusercontent.com/27075142/123745235-8de90800-d8e2-11eb-8ecc-31e081a73c79.png)
而在此url进行跳转，跳转到url: `http://localhost:8000/dataset/A/B/C`时，也成功载入了组件 Annotation，但页面title丢失，变为
![image](https://user-images.githubusercontent.com/27075142/123745334-ba9d1f80-d8e2-11eb-9796-9bdb4dcab3e7.png)
并且观察 `props.route`发现两个页面是一致的。
![image](https://user-images.githubusercontent.com/27075142/123745612-18ca0280-d8e3-11eb-8067-0fa12a7ff622.png)

**Comment by chenshuai2144** [comment]
`  path: '/dataset/:datasetId/:fileName/',`

不要写 / 结尾不然匹配效果会变差，匹配 title逻辑和匹配路由的逻辑是有不同的
