### ISSUE TITLE
How do i set language SettingDrawer English ? 

### ISSUE THREAD

**Issue by deepghuge36** [ant-design/ant-design-pro#8649]
### 🧐 问题描述
In config.js I have already set the default:'en-US' the page also loads in English but SettingDrawer in Chinese 

I want to set by default page load SettingDrawer should be English 

### 💻 示例代码
my cofig.js
```
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  history: {
    type: 'browser',
  },
  locale: {
    default: 'en-US',
    antd: true,
    // when it is true, will use `navigator.language` overwrite default
    baseNavigator: false,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  targets: {
    ie: 11,
  },
```

### 🚑 其他信息
My BasicLayout.js
```
      <SettingDrawer
        settings={settings}
        onSettingChange={(config) =>
          dispatch({
            type: 'settings/changeSetting',
            payload: config,
          })
        }
      />
```

**Comment by chenshuai2144** [comment]
```
 <SettingDrawer
       fomartMessgae={fomartMessgae}
        settings={settings}
        onSettingChange={(config) =>
          dispatch({
            type: 'settings/changeSetting',
            payload: config,
          })
        }
      />
```

you need set fomartMessgae

**Comment by deepghuge36** [comment]
> ```
>  <SettingDrawer
>        fomartMessgae={fomartMessgae}
>         settings={settings}
>         onSettingChange={(config) =>
>           dispatch({
>             type: 'settings/changeSetting',
>             payload: config,
>           })
>         }
>       />
> ```
> 
> you need set fomartMessgae

How ? can you give example for English Language
