### ISSUE TITLE
多个异步请求

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#865]
有两个异步请求，第二个的请求依赖第一个的请求结果，
请问在effects中怎么写,谢谢

**Comment by ddcat1115** [comment]
```js
dispatch({...}).then(() => {
  dispatch({...})
})
```

或者 dispatch 一个 effect，在 effect 里顺序 yield call

单纯 dva 使用问题请反馈到[dva issue](https://github.com/dvajs/dva/issues)

**Comment by kinizumi** [comment]
用then不用callback的是吧？
callback是这个样子的：
dispatch({
          type: 'rule/remove',
          payload: {
            key: selectedRows.map(row => row.key),
          },
          callback: () => {
            this.setState({
              selectedRows: [],
            });
          },
        });

**Comment by fujianbo** [comment]
> 有两个异步请求，第二个的请求依赖第一个的请求结果，
> 请问在effects中怎么写,谢谢

请问这个问题解决了吗? 我也有类似的疑惑

**Comment by yoyo837** [comment]
@fujianbo 你的问题和pro无关，

```js
await yield call()
```
