### ISSUE TITLE
🐛[BUG mock 接口 报错

### ISSUE THREAD

**Issue by qsg1215** [ant-design/ant-design-pro#8650]
### 🐛 bug 描述

mock 接口 /api/rule 报500 错误

### 📷 复现步骤

克隆主分支代码， 安装依赖 yarn start

### 🏞 期望结果

期望接口查询成功

### 💻 复现代码

不修改任何代码

### © 版本信息

- Ant Design Pro 版本: [4.5.0]
- umi 版本 [3.4.1]
- 浏览器环境 chrome  91.0.4472.114
- 开发环境 [e.g. mac OS]
- OS:  [mac OS 11.4]

### 🚑 其他信息

- userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

![image](https://user-images.githubusercontent.com/28627864/123788554-b981e780-d90e-11eb-9b88-af824b2a7f76.png)

错误原因
文件位置：/Users/ian/Downloads/myWorkSpace/ant-design-pro/mock/listTableList.ts
行位置：const sorter = JSON.parse(params.sorter as any);
报错原因：  const params = (new URLSearchParams(realUrl.split('?')[1]) as unknown) as TableListParams;
 sorter不是一个对象， 是一个URLSearchParams实例， 不能通过.访问
解决方案： const params = new URLSearchParams(realUrl) ；lconst sorter = JSON.parse(params.get（“sorter”）as any);

params 拿不到

**Comment by qsg1215** [comment]
在  JSON.parse(params.sorter as any) 的时候 params.sorter 是undefined

**Comment by copperyp** [comment]
1. Add import  
`import { URLSearchParams} from 'url'; `

Sometime  URLSearchParams import from microsoft typescript lib ... lib.dom.d.ts???

2. Then move sorter into if ..... 
```
const { current = 1, pageSize = 10 } = req.query;
  const params = (new URLSearchParams(realUrl.split('?')[1]) as unknown) as TableListParams;
  let dataSource = [...tableListDataSource].slice(
    ((current as number) - 1) * (pageSize as number),
    (current as number) * (pageSize as number),
  );
  
  if (params.sorter) {
    const sorter = JSON.parse(params.sorter as any);
  ... ... ...
```
  
It is working for me :) luck for every one:)

**Comment by chenshuai2144** [comment]
fixed in v5
