### ISSUE TITLE
🧐[问题]v5版本layout嵌套布局路由问题

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-pro#8651]
### 🧐 问题描述
layout嵌套布局，我用的childrenRender里面再嵌套一个ProLayout，但是上一级的路由跟嵌套的路由好像没有联动起来。导致菜单没有高亮

**Comment by tianlilong** [comment]
您的这个问题解决了吗？？我同样问题，有点困扰

**Comment by chenshuai2144** [comment]
要把props 里面的东西都设置进去

**Comment by tianlilong** [comment]
> 要把 props 里面的东西都设置进去

有案例吗

**Comment by chenshuai2144** [comment]
https://github.com/umijs/plugins/blob/12073b644233bb7580abea93fd50c3dfb38155a5/packages/plugin-layout/src/layout/index.tsx.tpl#L103


看看这个
