### ISSUE TITLE
better-scroll无法安装🐛[BUG]

### ISSUE THREAD

**Issue by luluseiipai** [ant-design/ant-design-pro#8654]
### 🧐 问题描述
better-scroll提示无法安装，有谁能解决一下吗

**Comment by chenshuai2144** [comment]
better-scroll 是什么东西，描述下你的场景把

**Comment by lovesL** [comment]
哈哈哈 我去 尽然还有人跑这来提问这个东西。。。。真是天下之大无奇不有

**Comment by luluseiipai** [comment]
与 better-scroll 无关，删除node_module后重新安装即可，通过npm / cnpm 安装的第三方包都有失败的可能
