### ISSUE TITLE
🧐[问题]如何在项目中下载本地文件

### ISSUE THREAD

**Issue by yuuid** [ant-design/ant-design-pro#8655]
### 🧐 问题描述

在实际项目中有导入功能，导入就需要用户先下载模板。然后问题来了，我import的文件会直接报错，说我缺少某个loader。
应该如何解决呢？

### 💻 示例代码

`import zipUrl from '@/assets/checkModal.xlsx';`
`<a href={zipUrl} download='checkModal.xlsx' target="_blank">下载模板</a>`
### 🚑 其他信息
![image](https://user-images.githubusercontent.com/41931944/124054871-767e5c00-da55-11eb-9d2b-a71e9415bed6.png)

**Comment by chenshuai2144** [comment]
你可以把这个文件放到public 中，例如 

`public/checkModal.xlsx`

在代码中可以 

`<a href="/checkModal.xlsx" download='checkModal.xlsx' target="_blank">下载模板</a>`


import xlsx 需要配置fileload 还会导致编译速度变慢
