### ISSUE TITLE
🐛[BUG] @umijs/plugin-blocks 中依赖的block-sdk的prettier包会污染本地prettier

### ISSUE THREAD

**Issue by shlroland** [ant-design/ant-design-pro#8657]
### 🐛 bug 描述
每次安装node_modules的安装包之后，block-sdk的prettier1.18版本会覆盖.bin中的prettier,该版本对于ts支持不是很好不支持`import type { xx } from 'yy'`这样的语法

### 📷 复现步骤
安装ant design pro，项目安装prettier
此时用yarn安装一个别的生产依赖包，.bin的prettier会发生变化

### 🏞 期望结果
prettier指向不变

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本 3.4.0
- 浏览器环境 edge 91.0.864.59 
- 开发环境 macos

**Comment by chenshuai2144** [comment]
发了个新版本，你再试试
