### ISSUE TITLE
请求数据问题

### ISSUE THREAD

**Issue by yumengqin** [ant-design/ant-design-pro#866]
![image](https://user-images.githubusercontent.com/22536897/35669127-069a74a8-076f-11e8-98d1-dc3d543ee5b6.png) 使用 fetch 发起的POST请求404错误 已经和后端验证过 后端没有问题

**Comment by chenshuai2144** [comment]
这么粗暴的请求。。。。。
你这样会把今天资源也给拦截了的。
当然404

**Comment by yumengqin** [comment]
那我这块应该怎么配置呢

**Comment by yumengqin** [comment]
![image](https://user-images.githubusercontent.com/22536897/35669488-360b5616-0770-11e8-96e7-4bd16ca6e226.png)
这样吗 仍然会有问题post

**Comment by chenshuai2144** [comment]
/oss/* http://192.168.228.114:80/oss/*试试

**Comment by yumengqin** [comment]
不可以 这样写连GET请求都404了

**Comment by chenshuai2144** [comment]
你们的服务器路径时给我个例子？

**Comment by yumengqin** [comment]
![image](https://user-images.githubusercontent.com/22536897/35669737-0f1d56fc-0771-11e8-8c32-f8824e19dccb.png)

**Comment by chenshuai2144** [comment]
你需要看看这个了https://github.com/sorrycc/roadhog#proxy

**Comment by yumengqin** [comment]
谢谢啦  再请教一个问题  在effects中可以调用另一个effects吗

**Comment by yumengqin** [comment]
能举个例子吗
