### ISSUE TITLE
🐛[BUG]antd pro v5安装 antd-theme和setting-drawer 切换主题 丢失登录状态.

### ISSUE THREAD

**Issue by CHENJKNB** [ant-design/ant-design-pro#8661]
### 🐛 bug 描述

 antd pro v5 安装umi-plugin-antd-theme 和 umi-plugin-setting-drawer 插件 。切换主题 登录状态就会丢失 如下图。

### 📷 复现步骤

![1](https://user-images.githubusercontent.com/18523983/124279692-6318e100-db7a-11eb-8816-fb8e4eaea3bd.gif)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0] antd pro v5  最新版本（5.0.0-beta.3）。
- umi 版本  umi 3.5  
- 依赖包都升级到了最新版本
- 浏览器环境 谷歌浏览器最新版本
- 开发环境 [windows 10 ]

**Comment by komorebi-san** [comment]
Same here.

**Comment by komorebi-san** [comment]
@chenshuai2144 

I have been trying alot of times to recreate in codesandbox, but i get not enough space or cross-env or umi not found.

Is it possible for you to create a simple codesandbox using the latest ant-design-pro v5 for me to use and i can fork it?

**Comment by chenshuai2144** [comment]
giv me a repo

**Comment by komorebi-san** [comment]
@chenshuai2144 
https://codesandbox.io/s/strange-goodall-u6wep?file=/README.md:0-83

![image](https://user-images.githubusercontent.com/8327827/126286577-6fda4f59-9757-40dd-bb1c-71189dd47c1f.png)

**Comment by CHENJKNB** [comment]
@chenshuai2144  https://gitee.com/chenjiakuan/antd-pro

**Comment by CHENJKNB** [comment]
这个插件 已经升级到了最新版本，但是还是有这个BUG?

**Comment by chenshuai2144** [comment]
不是插件哦，是umi，你最好清空依赖重新来一下

**Comment by CHENJKNB** [comment]
> 不是插件哦，是umi，你最好清空依赖重新来一下
麻烦你发一份 package.json 看看 谢谢 大佬。下图是我的 但是还是有问题
![1637247893(1)](https://user-images.githubusercontent.com/18523983/142441119-623070b0-83d5-4a68-99c5-598a12516a95.png)

**Comment by chenshuai2144** [comment]
全部安装就好了，依赖的依赖我爷看不出来呀

**Comment by CHENJKNB** [comment]
大佬  我这两天清除安装缓存，更新了全部依赖包。还是有这个问题 麻烦大佬再看看  https://gitee.com/chenjiakuan/antd-pro.git 谢谢
