### ISSUE TITLE
🧐[问题]获取antd pro的源码, 完整代码

### ISSUE THREAD

**Issue by SilentFlute** [ant-design/ant-design-pro#8664]
自己有这个需求, 多方搜索尝试后终于将带源码, 完整代码的项目运行起来了, 同时也看到有不少人有这个需求,  问这个的相关`issue`不少, 一一回答太费时间, 因此自己开一个`issue`记录一下, 提这个`issue`的时候刚把项目跑起来, 不保证很长时间之后依旧能用, 希望目前能帮到大家, 以下是详细步骤和一些描述:

1. 克隆本仓库
2. 使用`yarn`命令安装依赖
3. 使用`yarn run pro fetch-blocks --branch=v5`命令安装所有的`block`
4. 使用`yarn start`命令运行项目

PS:
- `block`的`github`地址是这个: `https://github.com/ant-design/pro-blocks`
- 安装`block`的命令是`登录`失败之后在`issue`中搜索`登录`关键字时阴差阳错在这个`issue`: #6798 中看到的, `block`的`git`仓库中有两种不同的安装命令, 但是都不同程度的有报错, `pro`文档: `https://pro.ant.design/zh-CN/docs/assets`里提到`如果你想获取全部区块，可以在 create umi 创建脚手架时 配置 🚀 Do you need all the blocks or a easy scaffold? 选择 complete 来获取与官方预览地址相同的代码。`但我用`git bash`运行`yarn create umi`之后发现无法使用光标来进行选择, 同时似乎也没有这个选项, 也可能是我没看到, 但无法使用光标来进行选择, 看到了也没用, 不知道为何不能使用光标来进行选择, 也许`power shell`中或者`win`默认的`cmd`中可以? 以前是用`mac`的, 没有遇到过这个情况
- 一开始我使用`yarn dev`命令运行项目的时候登录接口报`405`的错导致无法登录, 查看里面`登录`相关代码之后发现请求没能进到`express`的`res`中, 直接写死登录返回的内容和当前用户信息之后跳过登录页面, 但之后页面中`mock`数据的接口也都报错, 此时才恍然大悟可能是`mock`的服务没有启动, 仔细一看发现`yarn dev`这个命令实际运行的是`cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev`, 里面把`MOCK`设置为了`none`, 我怀疑就是这个问题导致登录接口无法使用, 观察了下`package.json`里的其他`script`之后我尝试使用了`yarn start`命令运行代码, 因为`yarn start`实际运行的命令是`cross-env UMI_ENV=dev umi dev`, 没有将`MOCK`设置为`none`, 最终项目终于正常运行了起来, 登录成功, 并且其他页面能获取到`mock`的数据

**Comment by hyzx86** [comment]
但是 cli 创建的似乎只是5.0 ，没有5.2 的，比如没有 站点设置选项。。
