### ISSUE TITLE
white screen in splitMenus🐛[BUG]

### ISSUE THREAD

**Issue by arpanEnbake** [ant-design/ant-design-pro#8666]
### 🐛 bug 描述

If splitMenus is choosen in mix mode, the main menu shows white screen. 
Documentation talks about redirect but its not helping either

### 📷 复现步骤

Ideally the top menu should either redirect to a specific child and highlight that child in sub menu

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/397626/124371843-622f9e80-dca3-11eb-9dd3-680791b32265.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

```
{
  "navTheme": "light",
  "primaryColor": "#1890ff",
  "layout": "mix",
  "contentWidth": "Fluid",
  "fixedHeader": false,
  "fixSiderbar": true,
  "title": "Ant Design Pro",
  "pwa": false,
  "iconfontUrl": "",
  "menu": {
    "locale": true
  },
  "headerHeight": 48,
  "splitMenus": true
}
```

**Comment by chenshuai2144** [comment]
fixed，i add some redirect
