### ISSUE TITLE
🐛[BUG] doc 404

### ISSUE THREAD

**Issue by xnng** [ant-design/ant-design-pro#8668]
![image](https://user-images.githubusercontent.com/38936252/124376404-73939d80-dcd9-11eb-972f-655e6e4e64cf.png)
![image](https://user-images.githubusercontent.com/38936252/124376367-447d2c00-dcd9-11eb-8bb2-96e5e6bfc0a3.png)

**Comment by chenshuai2144** [comment]
fixed in new version
