### ISSUE TITLE
如何通过后端接口获取菜单数据？

### ISSUE THREAD

**Issue by Coder7777** [ant-design/ant-design-pro#867]
现在的pro是在common/menu.js里写死了一个menuData，然后再调用getMenuData()函数。
我的系统的需求是根据登录用户ID，从请求后端接口，动态的返回菜单数据（结构一致与menuData）。
我试着写service和model，以及改写layouts/BasicLayout.js里getMenuData()的过程，但总是不成功，菜单数据无法同步到视图上，因该是异步请求导致的。
有没有异步获取后端菜单接口数据的Demo？

**Comment by chenshuai2144** [comment]
暂时没有。你可以看看相关的讨论 #751

**Comment by juniorselk** [comment]
我现在也遇到了同样的问题，请问一下你是怎么解决的？

**Comment by kateli** [comment]
我也遇到了同样的问题
请问你们是怎么解决的呢
