### ISSUE TITLE
v5有非ts版本的排期嘛

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8670]

**Comment by aspirantzhang** [comment]
不太可能吧，ts应该是趋势了，肯定是往上走，不太可能往下兼容

**Comment by fangqibin** [comment]
只是好奇，为什么不想要用ts

**Comment by lovesL** [comment]
> 只是好奇，为什么不想要用ts
成本上升了 对于团队成员水平高低差距大的团队很难拓展开

**Comment by fangqibin** [comment]
> > 只是好奇，为什么不想要用ts
> > 成本上升了 对于团队成员水平高低差距大的团队很难拓展开

我觉得会js来用ts，应该上手很快，而且ts对于后期维护很有帮助。团队总是要进步的。个人看法。

**Comment by lovesL** [comment]
> > > 只是好奇，为什么不想要用ts
> > > 成本上升了 对于团队成员水平高低差距大的团队很难拓展开
> 
> 我觉得会js来用ts，应该上手很快，而且ts对于后期维护很有帮助。团队总是要进步的。个人看法。

小企业。。不能和蚂蚁 阿里那样的大厂比 因为体量摆在那... 小企业需要的是简单粗暴 能实现就行 快速产出  不太在乎后期的维护成本。  我在网上看到帖子 说阿里也有一些...老项目 又臭又硬不好维护 都外包给那些外包公司去维护 ~dog  不知道是不是真的

**Comment by chenshuai2144** [comment]
ts 没什么成本的，不行你就写成 anyscript ，让 ts 做你的文档。但是不推荐使用纯 js
