### ISSUE TITLE
V5版本动态获取菜单icon不能正确显示。

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#8671]
![image](https://user-images.githubusercontent.com/51156342/124448767-5d5b0f80-ddb5-11eb-8411-0357e1468631.png)
dongt
动态获取菜单后，前台设置icon和后台设置icon都不能正确显示
![icon图标问题](https://user-images.githubusercontent.com/51156342/124448840-71067600-ddb5-11eb-8f9c-cff9925afccd.png)

**Comment by aFUZHOU** [comment]
#8101
