### ISSUE TITLE
👑 [需求]数据怎么传递给子组件

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8672]
### 🥰 需求描述

比如说，我用的是table不是protable ，但是我的datasource 有可能是通过其他的触发来得到。像第四版本的话，我只要把datasource定义出来，其他的触发只要是传过来是datasurce的数据，我的Table 就可以使用。我想问下，我们v5的话，要怎么样实现这样的需求。
再比如说我的数据可能是要传弟到子组件比如说CreateComponent 之类的。要怎么传递。难道是用useRequest直接在index里面去请求再把得到的数据往子组件里面传递?

**Comment by chenshuai2144** [comment]
可以使用useRequest 之类的库，来将数据提取到父组件中，

```tsx
const {loading,data}= useRequest(getList)

return <><Table datasource={data}/><Create datasource={data}/></>
```;

如果要全局使用，可以直接用 useModel
