### ISSUE TITLE
现在v5的版本是不是废弃掉了。

### ISSUE THREAD

**Issue by blackboy1987** [ant-design/ant-design-pro#8673]
### 🧐 问题描述

现在通过这个命令  已经没有选择v5和v4的地方了。
npm create umi admin

**Comment by kevinpursuing** [comment]
同问，v5怎么消失了

**Comment by aspirantzhang** [comment]
v5已经正式发布，现在安装好就是v5了，没有v4 v5选择的选项了。
umijs/create-umi@bcc36b5

**Comment by wgh970312** [comment]
@aspirantzhang 是5真的没了，创建出来的项目是4.5.0的，我昨天创建的是5.0.0-beta.3
![image](https://user-images.githubusercontent.com/27401176/124556329-be90ea80-de6a-11eb-9496-f24618ec8c40.png)
![image](https://user-images.githubusercontent.com/27401176/124556357-c51f6200-de6a-11eb-91c9-b15ca4cd8348.png)

**Comment by aspirantzhang** [comment]
> @aspirantzhang 是5真的没了，创建出来的项目是4.5.0的，我昨天创建的是5.0.0-beta.3
> ![image](https://user-images.githubusercontent.com/27401176/124556329-be90ea80-de6a-11eb-9496-f24618ec8c40.png)
> ![image](https://user-images.githubusercontent.com/27401176/124556357-c51f6200-de6a-11eb-91c9-b15ca4cd8348.png)

尝试更新一下create-umi的库到最新版 `v0.27.0`，两个时前刚刚发布 https://github.com/umijs/create-umi

我刚刚测试安装后即为新版v5

**Comment by aspirantzhang** [comment]
我试了五次，三次按的是github新版，二次按的是gitee的旧版，应该确定是gitee没有升级的问题，应急新版包：
[v5.zip](https://github.com/ant-design/ant-design-pro/files/6768206/v5.zip)

**Comment by Niofh** [comment]
我也是创建是v4.5,5.0代码都没有了！

**Comment by afc163** [comment]
gitee 数据已同步修复。
