### ISSUE TITLE
🧐[问题]安装时发现没有V5的选项了

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design-pro#8674]
### 🧐 问题描述

运行 yarn create umi myapp后选择ant-design-pro后没有v4,v5的选择
是不是已经废弃了？

**Comment by aspirantzhang** [comment]
v5已经正式发布，现在安装好就是v5了，没有v4 v5选择的选项了。
https://github.com/umijs/create-umi/commit/bcc36b5672b8776c88f90c22ed8795c38f68a9b5

**Comment by LiuXiaoJie** [comment]
yarn create umi myapp 安装后显示版本是4.5.0

**Comment by aspirantzhang** [comment]
> yarn create umi myapp 安装后显示版本是4.5.0

尝试更新一下create-umi的库到`v0.27.0`，两个时前刚刚发布 https://github.com/umijs/create-umi

**Comment by LiuXiaoJie** [comment]
看终端里显示的就是create-umi@0.27.0，是否与https://gitee.com/ant-design/ant-design-pro库没更新有关？

**Comment by kevinpursuing** [comment]
> > yarn create umi myapp 安装后显示版本是4.5.0
> 
> 尝试更新一下create-umi的库到`v0.27.0`，两个时前刚刚发布 https://github.com/umijs/create-umi
> 
> 我刚刚测试安装后即为新版v5

我这边版本就是0.27.0，可是安装下来还是4.5

**Comment by kevinpursuing** [comment]
@LiuXiaoJie

**Comment by kevinpursuing** [comment]
@aspirantzhang

**Comment by aspirantzhang** [comment]
> > > yarn create umi myapp 安装后显示版本是4.5.0
> > 
> > 
> > 尝试更新一下create-umi的库到`v0.27.0`，两个时前刚刚发布 https://github.com/umijs/create-umi
> > 我刚刚测试安装后即为新版v5
> 
> 看终端里显示的就是create-umi@0.27.0，是否与https://gitee.com/ant-design/ant-design-pro 库没更新有关？

我估计是，可能根据网速判断抓了国内源 🤣
@chenshuai2144

**Comment by aspirantzhang** [comment]
我试了五次，三次按的是github新版，二次按的是gitee的旧版，应该确定是gitee没有升级的问题，应急新版包：
[v5.zip](https://github.com/ant-design/ant-design-pro/files/6768206/v5.zip)

**Comment by afc163** [comment]
gitee 数据已同步修复。
