### ISSUE TITLE
yarn create umi xxx 默认antd是4.5

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design-pro#8675]
### 🧐 问题描述

yarn create umi xxx  打开项目后antd pro是4.5版本
create_umi 是0.27.0

**Comment by aspirantzhang** [comment]
我试了五次，三次按的是github新版，二次按的是gitee的旧版，应该确定是gitee没有升级的问题，应急新版包：
[v5.zip](https://github.com/ant-design/ant-design-pro/files/6768206/v5.zip)

**Comment by afc163** [comment]
gitee 数据已同步修复。
