### ISSUE TITLE
🐛 [BUG] mfsu 开启后项目第一次启动的问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#8677]
ant design pro v5 脚手架，`yarn create umi myapp`。

1. 貌似 mfsu 第一次启动时，mfsu 有个进度条，此时打开 127.0.0.1:8000 会报错
2. mfsu 进度条跑到 99%，此时打开 127.0.0.1:8000 就好了
3. mfsu 进度条 会卡在 99%

![图片](https://user-images.githubusercontent.com/507615/124588033-e8f2a000-de8a-11eb-88d0-81db674e64cb.png)

![图片](https://user-images.githubusercontent.com/507615/124588040-ed1ebd80-de8a-11eb-9d80-7fa56c845092.png)

**Comment by afc163** [comment]
@xiefengnian

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/pull/6990 和 https://github.com/umijs/umi/pull/6969 里修复了。

**Comment by lovesL** [comment]
最新版发了嘛？ 我现在也遇到卡在99%    umi 版本3.5.0
