### ISSUE TITLE
🧐[问题]antd pro v5怎么从5.0.0-beta.2升级到正式版

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#8678]
看到antd pro v5发布正式版了，我现在的版本是5.0.0-beta.2，怎么才能升级到正式版呢？

**Comment by hanzixian** [comment]
发布正式版了？给个链接呗

**Comment by fangqibin** [comment]
现在正式版相对beta没有什么大改动，可以继续用就行了。

> 发布正式版了？给个链接呗

https://github.com/ant-design/ant-design-pro/issues/8656

**Comment by fangqibin** [comment]
现在正式版相对beta没有什么大改动，可以继续用就行了。

**Comment by fangqibin** [comment]
> 发布正式版了？给个链接呗

https://github.com/ant-design/ant-design-pro/issues/8656
https://pro.ant.design/zh-CN/docs/getting-started

**Comment by hanzixian** [comment]
> 现在正式版相对beta没有什么大改动，可以继续用就行了。



> > 发布正式版了？给个链接呗
> 
> #8656
> https://pro.ant.design/zh-CN/docs/getting-started

**Comment by hanzixian** [comment]
> > 发布正式版了？给个链接呗
> 
> #8656
> https://pro.ant.design/zh-CN/docs/getting-started

好的谢谢

**Comment by QWENQWJ** [comment]
> > 发布正式版了？给个链接呗
> 
> [#8656 ](https://github.com/ant-design/ant-design-pro/issues/8656)
> https://pro.ant.design/zh-CN/docs/getting-started

直接命令创建还是bate版本吧

**Comment by hanzixian** [comment]
> > > 发布正式版了？给个链接呗
> > 
> > 
> > [#8656 ](https://github.com/ant-design/ant-design-pro/issues/8656)
> > https://pro.ant.design/zh-CN/docs/getting-started
> 
> 直接命令创建还是bate版本吧

是正式版本

**Comment by QWENQWJ** [comment]
> > > > 发布正式版了？给个链接呗
> > > 
> > > 
> > > [#8656 ](https://github.com/ant-design/ant-design-pro/issues/8656)
> > > https://pro.ant.design/zh-CN/docs/getting-started
> > 
> > 
> > 直接命令创建还是bate版本吧
> 
> 是正式版本

我创建一个。一个大大的 5.0.0-bate3

**Comment by hanzixian** [comment]
> > > > > 发布正式版了？给个链接呗
> > > > 
> > > > 
> > > > [#8656 ](https://github.com/ant-design/ant-design-pro/issues/8656)
> > > > https://pro.ant.design/zh-CN/docs/getting-started
> > > 
> > > 
> > > 直接命令创建还是bate版本吧
> > 
> > 
> > 是正式版本
> 
> 我创建一个。一个大大的 5.0.0-bate3

😳😳😳😳

**Comment by QWENQWJ** [comment]
> > > > > > 发布正式版了？给个链接呗
> > > > > 
> > > > > 
> > > > > [#8656 ](https://github.com/ant-design/ant-design-pro/issues/8656)
> > > > > https://pro.ant.design/zh-CN/docs/getting-started
> > > > 
> > > > 
> > > > 直接命令创建还是bate版本吧
> > > 
> > > 
> > > 是正式版本
> > 
> > 
> > 我创建一个。一个大大的 5.0.0-bate3
> 
> 😳😳😳
你创建的是正式的吗

**Comment by chenshuai2144** [comment]
create-umi 已经发布最新版本

**Comment by QWENQWJ** [comment]
> create-umi 已经发布最新版本

我创建 npx create-umi myapp  显示是 5.0.0-bate3 还是

**Comment by chenshuai2144** [comment]
缓存了把。把 create-umi 从全局删除一下
