### ISSUE TITLE
🧐[问题] 请问ant-design-pro 为什么不推荐锁包？

### ISSUE THREAD

**Issue by htank-wang** [ant-design/ant-design-pro#8679]
### 🧐 问题描述
  我这边多个开发者同时开发时，不锁包会导致两边出现一些界面上的细微差别或小bug。对比发现是install了依赖不同的小版本。
  请问这种情况需要怎么处理？
  谢谢！

**Comment by chenshuai2144** [comment]
前端都不推荐锁包的，这样可能导致分叉或者无法获得 bugfix

如果两边出现了微小的差别以最新的为准。
