### ISSUE TITLE
如何实现动态面包屑问题？

### ISSUE THREAD

**Issue by lefter** [ant-design/ant-design-pro#868]
面包屑大致如下：首页-商品-iphone9x
 其中iphone9x是根据商品id, 从后端请求返回的。

**Comment by chenshuai2144** [comment]
可以试着自己生成面包屑

**Comment by ddcat1115** [comment]
可以自己对 PageHeader 进行一些改造，最后加一条后台来的数据，或者直接给 PageHeader 传 breadcrumbList...如果没有 PageHeader 需求，可以直接用 antd Breadcrumb
