### ISSUE TITLE
🐛[BUG]yarn create umi选all blocks scaffold的时候无法创建v5最新版

### ISSUE THREAD

**Issue by yangliuyu** [ant-design/ant-design-pro#8680]
### 🐛 bug 描述

yarn create umi project-name的时候，在`Do you need all the blocks or a simple scaffold?`这一步，选择simple会从ant-design-pro的master分支拉代码，选择了complete会从all-block分支clone代码，all-block分支还没有更新为and-design-pro v5版本
### 📷 复现步骤

yarn create umi project-name
在`Do you need all the blocks or a simple scaffold?`这一步选择complete
结果在生成的package.json里第三行，version为4.5.0
### 🏞 期望结果
生成的package.json里，第三行版本应为5.0.0

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 5.0
- umi 版本 0.27
- 浏览器环境
- 开发环境 [e.g. mac OS] mac OS

### 🚑 其他信息

![Screen Shot 2021-07-07 at 2 08 08 PM](https://user-images.githubusercontent.com/1361821/124708420-da5cc500-df2c-11eb-9432-7fe4e647240a.png)
<img width="654" alt="Screen Shot 2021-07-07 at 2 09 01 PM" src="https://user-images.githubusercontent.com/1361821/124708467-e9437780-df2c-11eb-817d-a1141b730694.png">

**Comment by kuretru** [comment]
`yarn create umi ad3`是啥，官网文档没有ad3吧

**Comment by yangliuyu** [comment]
> `yarn create umi ad3`是啥，官网文档没有ad3吧
ad3只是项目名称

**Comment by chenshuai2144** [comment]
已经修复了
