### ISSUE TITLE
ant-design-pro启动项目报错，内存溢出了！

### ISSUE THREAD

**Issue by Amosyounger** [ant-design/ant-design-pro#8681]
在网上搜了一下，mac os系统竟然找不到 node_modules\.bin\umi.cmd，这个umi文件(同事windows电脑上有，名字叫uuid)。
求大佬赐教。谢谢。

**Comment by chenshuai2144** [comment]
cmd 是 windows 才需要的，mac 不需要。

你可以 
```
git clean -dfx
npm i
```
重新安装下
