### ISSUE TITLE
代码提交所有文件自动删除

### ISSUE THREAD

**Issue by PeculiarCode** [ant-design/ant-design-pro#8682]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by xiaohuoni** [comment]
啥操作？

**Comment by PeculiarCode** [comment]
这边提交代码没放入缓存区就提交出现编写过的代码自动删除

**Comment by xiaohuoni** [comment]
怎么复现？和操作步骤提供一下。
