### ISSUE TITLE
🧐[问题] 修改src/.umi/plugin-request/request.ts文件，在本地环境修改了有效，发布到预发或线上就无效是什么原因？

### ISSUE THREAD

**Issue by hyy520** [ant-design/ant-design-pro#8683]

**Comment by AdoKevin** [comment]
不要提交.umi目录到git仓库, 执行umi dev或umi build的时候会被删除并重新生成。可以参考 https://umijs.org/zh-CN/docs/config 以及 https://umijs.org/zh-CN/plugins/plugin-request 重新配置request.
