### ISSUE TITLE
🧐[问题] 请问ant-design-pro v5 使用官方的demo打包后, 无法兼容IE11?

### ISSUE THREAD

**Issue by znz744** [ant-design/ant-design-pro#8684]
### 🧐 问题描述

使用官方的demo, 在npm start后, 无法在ie 11打开, config中有配置{targets: {ie: 11}}, 并且有3处报错
均为语法错误, 存在问题为兼容问题

因为是第一次使用antd pro, 希望能提供相关兼容的处理方式

**Comment by ali4heydari** [comment]
Any progress on this issue?
Ant pro still is incompatible with IE11:
![image](https://user-images.githubusercontent.com/29185622/129460498-febb130c-990c-45e0-a569-cf47d5b080b4.png)

**Comment by chenshuai2144** [comment]
close 
https://umijs.org/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF
