### ISSUE TITLE
如何将pro-layout布局改成顶部-侧边布局👑 [需求]

### ISSUE THREAD

**Issue by caolaichao** [ant-design/ant-design-pro#8686]
怎么样才能将现在默认布局改成这种布局。vue版本没有这种布局，react版本有。
![image](https://user-images.githubusercontent.com/44855437/124732601-ed2fc380-df45-11eb-80dc-d8d6fbf5f2a4.png)

**Comment by fangqibin** [comment]
参考https://procomponents.ant.design/components/layout
