### ISSUE TITLE
🧐[问题]layout menu默认打开

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-pro#8687]
### 🧐 问题描述

我看menu有个参数配置defaultOpenAll，但是文档解释是默认打开所有的菜单项，要注意只有 layout 挂载之前生效，异步加载菜单是不支持的
我是异步加载菜单的有别的办法可以默认全部打开吗
（我想实现的是通过访问路径参数加载不同的路由，路由是定义在前端）

**Comment by chenshuai2144** [comment]
异步加载菜单 可以通过设置 openKeys 来打开
