### ISSUE TITLE
🐛[BUG]antd-pro启动报错

### ISSUE THREAD

**Issue by ALL-STACK** [ant-design/ant-design-pro#8689]
### 🐛 bug 描述

按照官方步骤，初始化项目，运行报错，提示找不到mfsu

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/24264872/124892223-43673a00-e00c-11eb-9a2b-04e7085b7410.png)

### 复现仓库

https://github.com/ALL-STACK/antd-pro-v5.git

### 🏞 期望结果

期望能正常启动

### © 版本信息

- Ant Design Pro 版本: v5.0.0
- umi 版本: v3.5.0
- 浏览器环境: chrome v91.0.4472.124
- 开发环境 windows 10
- node 版本: v14.17.3

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24264872/124892150-334f5a80-e00c-11eb-962e-15f2e2f6dada.png)

**Comment by chenshuai2144** [comment]
更新以下umi的依赖。
