### ISSUE TITLE
关于动态加载 model 的疑惑

### ISSUE THREAD

**Issue by zmayor** [ant-design/ant-design-pro#869]
按照文档, model 应该是动态加载的, 但是为什么我发现打开的时候所有的 model 都加载了. 我看了官方的项目也不是动态加载 , 是我打开的方式不对吗? 希望大家能帮忙解答

**Comment by yesmeck** [comment]
1.0 以后默认关闭了动态加载。去掉[这个选项](https://github.com/ant-design/ant-design-pro/blob/6b7221c263a576802b16c5d67228fd93a2571f88/.webpackrc#L20) 可以重新打开。

**Comment by afc163** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD
