### ISSUE TITLE
🧐[问题]npx create-umi myapp不能选择Pro V4

### ISSUE THREAD

**Issue by xigemall** [ant-design/ant-design-pro#8691]
### 🧐 问题描述

create-umi@0.25.1版本可以选择Pro V4, 初始的项目版本是Pro V5的
![image](https://user-images.githubusercontent.com/29243444/124892711-ad7fdf00-e00c-11eb-8cb2-0508d5239132.png)

### 💻 示例代码
![image](https://user-images.githubusercontent.com/29243444/124891980-08650680-e00c-11eb-83a4-5b672256eb8c.png)

**Comment by lukaiqi** [comment]
我也是
前几天还可以

**Comment by ideaviewes** [comment]
这个好奇怪，我的是选择不了V5，下载完了直接v4

**Comment by LingKKKK** [comment]
> 这个好奇怪，我的是选择不了V5，下载完了直接v4

你什么环境?  我下载玩就V5, 我想下载v4

**Comment by ideaviewes** [comment]
@LingKKKK 
node v14.17.3
create-umi@0.27.0
umi@3.5.4
也没人回答这类问题了，不知什么鬼这个

**Comment by chenshuai2144** [comment]
yarn create umi  你们应该是本地被缓存了
