### ISSUE TITLE
🧐[问题]使用Protable自带的全屏功能后,message无法提示。

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#8692]

**Comment by huangzongming** [comment]
![1](https://user-images.githubusercontent.com/37889515/124896237-d786d080-e00f-11eb-892a-af877af335c8.png)
![21 N(DI$X`YE0~DT)LLBDD](https://user-images.githubusercontent.com/37889515/124896430-000eca80-e010-11eb-9444-50afc2786dee.png)

**Comment by huangzongming** [comment]
![X9QHOJD%)91X2{3O 76PF}E](https://user-images.githubusercontent.com/37889515/124896749-4a904700-e010-11eb-805d-0bfbf82a8ea2.png)
这个地方尝试改了，但还是不起作用

**Comment by huangzongming** [comment]
@chenshuai2144  大佬，有空看下哈

**Comment by chenshuai2144** [comment]
全屏要用起来太难了，还是不要用了😂🤣
