### ISSUE TITLE
🐛[BUG] 开启mfsu后无法读取 `src/locales/*` 中的翻译

### ISSUE THREAD

**Issue by marcustut** [ant-design/ant-design-pro#8694]
### 🐛 bug 描述
我在本在使用的是v5 beta，看到v5正式版发出后就先更新了 umi 原本从 3.4.0 版本到 3.5.7主要是为了mfsu，结果在升级后，plugin-locale就无法读取在 `src/locales/*` 中的翻译了 

### 📷 复现步骤

1. 升级umi到3.5.7
2. 打开 yarn dev
3. 无法读取locales中的翻译

### 🏞 期望结果

能够正确读取locales中的翻译

### 💻 复现代码

以下是我打开mfsu的方式，打开后mfsu正确工作但就无法读取locales了
```ts
// config.ts
...
  nodeModulesTransform: { type: 'none' },
  mfsu: {},
  webpack5: {},
  exportStatic: {},
```

当我把mfsu关闭后，locales就恢复正常

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0 beta]
- umi 版本: 3.5.7
- 浏览器环境: Chrome
- 开发环境: Mac OS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/59773847/124975030-1fcddf00-e060-11eb-98fe-923b2f886139.png)

**Comment by chenshuai2144** [comment]
新版本中已经修复，可以重装了

**Comment by iscmcloud** [comment]
重新装了之后，也还没有修复吧？umi 版本3.5.10貌似也没好
