### ISSUE TITLE
v5版本菜单的高级用法  icon 没有生效，带参数的路由404，重定向全部失效了，有知道怎么改的吗？

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#8695]
使用v5   菜单的高级用法 使用后端返回的路由数据生成路由，但是发现icon直接解析成文字了，不是图标了，这个该怎么玩？

**Comment by yongjiangliu** [comment]
动态路由 带参数的path 会映射404

**Comment by fangqibin** [comment]
有这个方法subMenuItemRender

**Comment by yongjiangliu** [comment]
> 有这个方法subMenuItemRender

v5 菜单相关的都封起来了，都没法改了。。。。。。。。

**Comment by fangqibin** [comment]
> > 有这个方法subMenuItemRender
> 
> v5 菜单相关的都封起来了，都没法改了。。。。。。。。

都封起来了是什么意思？可以看一下这个文档https://procomponents.ant.design/components/layout#api

**Comment by chenshuai2144** [comment]
重定向已经是没法改的，因为重定向是路由的功能。

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/ant-design-pro/issues/8101

**Comment by kevinsheep** [comment]
> 动态路由 带参数的path 会映射404
图标的问题我写了个方案： https://github.com/ant-design/ant-design-pro/issues/8101#issuecomment-905133789
带参数的path 会映射404，这个我怎么没遇到？能详细点说说不？
