### ISSUE TITLE
🐛[BUG]V5 版mfsu后 config.ts中定义theme无法生效

### ISSUE THREAD

**Issue by iscmcloud** [ant-design/ant-design-pro#8696]
### 🐛 bug 描述

V5 版 启用mfsu后 config.ts中定义theme无法生效

### 📷 复现步骤

1. yarn create umi
2. yarn 
3. yarn start
4. 修改 config.ts 中 theme{ }
5. 修改的颜色配置等无法生效

### 🏞 期望结果

修改 config.ts 中 theme{ }后可以生效

### 💻 复现代码
关闭mfsu选项后可以看到生效

### © 版本信息

- Ant Design Pro 版本: V5

**Comment by iscmcloud** [comment]
@chenshuai2144 请问这个问题有计划修复一下么

**Comment by chenshuai2144** [comment]
去 umi 催一下，我这里智能跟踪

**Comment by iscmcloud** [comment]
在umi 3.5.13 貌似已经修复
