### ISSUE TITLE
🐛[BUG] yarn create umi不能选择antd pro的版本，直接是V4

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#8698]
### 🏞 期望结果

之前是可以选择V4还是V5，现在不能选，直接就是V4
### 💻 复现代码
tyarn create umi

### © 版本信息

create-umi@0.27.0
umi@3.5.4

**Comment by chenshuai2144** [comment]
已经修复，我手动更新了一下

**Comment by ideaviewes** [comment]
@chenshuai2144 ，好的，3q
