### ISSUE TITLE
我的 url 里怎么有 # 号？要如何去掉？ 启用了2行，还是去不掉？

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#87]
import dva from 'dva';
import 'moment/locale/zh-cn';
import models from './models';
import './polyfill';
import './g2';
import { browserHistory } from 'dva/router';  //启用了这行
import './index.less';

// 1. Initialize
const app = dva({
  history: browserHistory, //启用了这行
});

// 2. Plugins
// app.use({});

// 3. Model move to router
models.forEach((m) => {
  app.model(m);
});

// 4. Router
app.router(require('./router'));

// 5. Start
app.start('#root');

**Comment by nikogu** [comment]
https://pro.ant.design/docs/faq#我的-url-里怎么有-#-号？要如何去掉？

**Comment by kaoding** [comment]
@nikogu 就是按文档来做的，去不掉？

**Comment by nikogu** [comment]
看看这个呢：https://pro.ant.design/docs/deploy#在-Ant-Design-Pro-中使用前端路由

**Comment by kaoding** [comment]
@nikogu 我是拉了最新的项目，就是按这个做的 https://pro.ant.design/docs/deploy#在-Ant-Design-Pro-中使用前端路由

**Comment by linhanyang** [comment]
+1

**Comment by gebilaoman** [comment]
+1

**Comment by jiemo525** [comment]
+1

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/34658652-b9401f84-f46b-11e7-911f-df75beb19a9e.png)

这儿hai'y还有一个呢

**Comment by zhouguanglong** [comment]
怎么改的啊？ 我这里还是改不了
