### ISSUE TITLE
🐛[BUG]登录成功后initialState中的用户信息仍然是旧的

### ISSUE THREAD

**Issue by ITyaoji** [ant-design/ant-design-pro#8700]
### 🐛 bug 描述

使用不同的账号登录系统，头像和用户名显示的是上一次登录的用户，但实际接口返回了新的用户

### 📷 复现步骤

1、使用测试账号1登录系统，接口返回测试账号1的用户信息
2、退出登录
3、使用测试账号2登录系统， 接口返回测试账号2的用户信息

### 🏞 期望结果

右上角头像和用户名显示最新的用户

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 3.5.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/24262180/125046671-d23d8a80-e0d0-11eb-8f85-592b6d46c0de.png)

**Comment by fangqibin** [comment]
initialState是本地全局数据，不会缓存的。你刷新这个数据就没了

**Comment by coocier** [comment]
看看是不是因为开了msfu和webpack5的功能，msfu会强制开启webpack5物理缓存功能，我在项目中也遇到了，前端页面修改了数据之后就算页面刷新也没有发生变化，只有重新编译一次才会出现修改后的结果，后来索性把msfu和webpack5的配置都注释掉了，之后就正常了

**Comment by chenshuai2144** [comment]
修复了。
