### ISSUE TITLE
🧐[问题] 如何创建v4的项目? 

### ISSUE THREAD

**Issue by LingKKKK** [ant-design/ant-design-pro#8701]
### 🧐 问题描述

yarn create umi demo 之后没有选择版本的选项
如何创建一个v4的项目???

### 💻 示例代码

$ yarn create umi demo
.....
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? TypeScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
.....
✨  Done in 19.00s.

**Comment by TinsFox** [comment]
刚刚用命令行创建了一个，是v4.5.0，其中umi的版本是v3.2.14

**Comment by LingKKKK** [comment]
> 刚刚用命令行创建了一个，是v4.5.0，其中umi的版本是v3.2.14

谢啦, 我本地的是 umi@3.4.1 , 我降版本试试

**Comment by LingKKKK** [comment]
找到一个解决方法:
1. 将create-umi版本降为0.26.0
2. 创建好文件夹 demo
3. 进入demo执行 sudo create-umi

**Comment by chenshuai2144** [comment]
要clone 项目，然后 checkout 到 v4 分支，我们不推荐用 v4 了，已经不打算更新了

**Comment by meqdom** [comment]
还能拉取到javascript版本的v4版代码吗
