### ISSUE TITLE
🐛[BUG]新版本执行yarn build,使用nginx部署后，页面报错

### ISSUE THREAD

**Issue by liuyang-1990** [ant-design/ant-design-pro#8702]
### 🐛 bug 描述

新版本执行yarn build,使用nginx部署后，页面报错，登陆页面可以正常访问，登录后跳转首页，就会报错。
![QQ图片20210710125746](https://user-images.githubusercontent.com/29528177/125152327-7fbaa780-e17e-11eb-9153-ad15169208a9.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by liuyang-1990** [comment]
Ant Design Pro 版本: [e.g. 5.0.0]
umi 版本 3.5.0

**Comment by chenshuai2144** [comment]
看起来是modal的bug
