### ISSUE TITLE
🐛[BUG] import { request } from "umi" 在webStorm里报错

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#8703]
### 🐛 bug 描述
 这是ide的问题还是bug?
![image](https://user-images.githubusercontent.com/33146207/125163107-1eb2c400-e1be-11eb-8d87-b8bdec3c04ed.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by jinhgg** [comment]
在vs code里也报同样的错

**Comment by chenshuai2144** [comment]
```
 "paths": {
      "@/*": ["./src/*"],
      "@@/*": ["./src/.umi/*"]
    }
```

tsconfig 需要配置一下
