### ISSUE TITLE
🧐[问题] V5 动态路由

### ISSUE THREAD

**Issue by lingting** [ant-design/ant-design-pro#8704]
### 🧐 问题描述
V5 版本 有法子做到动态路由吗? 而不是动态菜单. 就是完全根据后台的菜单信息来处理,
而不是事先在  routes.ts 中配置, 在根据后台返回值的菜单信息进行展示, 
试过很多种方法都做不到...  可能是我太菜了,  请大佬们指点

我试过的法子:
1. 关闭默认layout, 指定  layout 往 props中的 route 插入路由(菜单没问题, 但是右侧页面内容无, currentPathConfig 为空)
2. umi patchRoutes 事件更新路由. 结果同上
3. app.ts 中强行覆盖默认 layout 中的 route
4. umi modifyClientRenderOpts 事件
5. app.ts layout  menuDataRender 覆写.
都不行....
求大佬们帮帮忙. .

代码地址 : https://github.com/ballcat-projects/ballcat-ui-react/tree/router

**Comment by qq1972474341** [comment]
解决了吗

**Comment by lingting** [comment]
> 解决了吗

解决了, 看dev分支的代码

**Comment by chengzi-code** [comment]
问题一样， 控制权限， 比如说通过后台来获取菜单来控制权限， 但是还要在config里面配置下路由，而这里的路由还有用access来控制权限， 不控制的话，即使后端返回的菜单没有某个路径，但是还是可以通过url来访问的， 这个是个问题

**Comment by lingting** [comment]
> 问题一样， 控制权限， 比如说通过后台来获取菜单来控制权限， 但是还要在config里面配置下路由，而这里的路由还有用access来控制权限， 不控制的话，即使后端返回的菜单没有某个路径，但是还是可以通过url来访问的， 这个是个问题

我记得我的写法是不需要在config里面配置的

**Comment by liguochuan00** [comment]
请问具体怎么解决的啊，能标注一下嘛？

**Comment by TopAlien** [comment]
> 问题一样， 控制权限， 比如说通过后台来获取菜单来控制权限， 但是还要在config里面配置下路由，而这里的路由还有用access来控制权限， 不控制的话，即使后端返回的菜单没有某个路径，但是还是可以通过url来访问的， 这个是个问题

1. 内置所有路由，打包是会打进去
2. 根据服务端返回路由信息实现动态菜单
3. 服务端返回的路由信息中的所有path做白名单，做重定向
目前是这么搞得

**Comment by xXAvoraXx** [comment]
> > 问题一样， 控制权限， 比如说通过后台来获取菜单来控制权限， 但是还要在config里面配置下路由，而这里的路由还有用access来控制权限， 不控制的话，即使后端返回的菜单没有某个路径，但是还是可以通过url来访问的， 这个是个问题
> 
> 1. 内置所有路由，打包是会打进去
> 2. 根据服务端返回路由信息实现动态菜单
> 3. 服务端返回的路由信息中的所有path做白名单，做重定向
>    目前是这么搞得

如何将菜单映射到组件？
