### ISSUE TITLE
🐛[BUG] v5 login 页面为什么会执行公共组件？？？导至页面报错

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8705]
### 🐛 bug 描述

我在公共组件开起了   Notice　组件。但是控制器台就开始报错，如果内容如下
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at NoticeIconView (http://localhost:8000/umi.js:5994:64)
```
在login页面，都不是layout了，但是我测试了下　components　下的组件在login都有执行。按道理说这个时候是不应该执行它的呀，因为都没有调用它导至控制台报错。正确情况是login页面调用哪些组件，执行哪些组件。这反而把 components 下的组件都给执行了，导致发起网络setState报错。这个我觉得不止login 其它非　layout 页面都有可能被前期执行而导至报错，这是不合理的。

### 🏞 期望结果

控制台不报错，且不执行公共组件

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
完全听不懂，来个重现把

**Comment by joesdu** [comment]
> 完全听不懂，来个重现把

hhhh,帅哥还是这么积极的解决问题.

**Comment by codedart2018** [comment]
> 完全听不懂，来个重现把

codesandbox　我无法安装。试了好多次yarn install npm install 都失败。
首先src/components/RightContent/index.tsx　引入
```
import Notice from '../NoticeIcon';
```
然后在
```
 <Avatar />
```
代码上方插入
```
<Notice />
```
然后在登陆页面，就能看到控制台的报错。如果在　src/components/NoticeIcon/index.tsx 中判断下是否登陆再请求，可以解决抒错问题。
```
  useEffect(() => {
    //这里网络请求造成报错。
    getNotices().then(({ data }) => setNotices(data || []));
  }, []);
```

然后中我想表达的是这个组件，用户没有登陆，也执行了组件渲染和网络请求。但这是不应该的。你们在没有登陆情况下随便在
```
/src/components/HeaderDropdown/index.tsx
/src/components/RightContent/index.tsx
/src/components/HeaderSearch/index.tsx
```
中执行
```
  console.log('执行了');
```
你们再看下控制台打印信息。这就是很诡异的事情呀！都没调用这些组件依然执行了。

**Comment by codedart2018** [comment]
算了　我自己做了个判断。
```
getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
  // 判断是否登陆，如果没有登陆的情况下不允许执行 layout
  isLogin: boolean;
}
```

```
layout: RunTimeLayoutConfig = ({initialState}) => {
  // 判断是否登陆，如果没有登陆的情况下不允许执行 layout
  if (!initialState?.isLogin) {
    return {};
  }

  return {
  ......code
  }
```

但目前我还不清楚有没有副作用，还望官方说明一下！

**Comment by chenshuai2144** [comment]
`  return {};`
倒是没有什么副作用，不过最好的判断还是判断以下 userinfo 是否存在来解决
