### ISSUE TITLE
Case sensitive related issue in config.js for v4.5

### ISSUE THREAD

**Issue by danwyry** [ant-design/ant-design-pro#8706]
I created a complete ant-design-pro javascript projected with umi. 
 
![image](https://user-images.githubusercontent.com/42071711/125174421-c965bb00-e19b-11eb-93c5-053b76726588.png)

downloaded package.json sets default ant-design-pro version to 4.5.0.  

I run `yarn`  and get warnings, but apparently no errors

When I run `yarn start`  fails with this error. 
```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                                         4:41:20 PM

These dependencies were not found:

* /home/dan/tmp/clients-frontend/src/pages/user/register in ./src/.umi/core/routes.ts
* /home/dan/tmp/clients-frontend/src/pages/user/register-result in ./src/.umi/core/routes.ts

To install them, you can run: npm install --save /home/dan/tmp/clients-frontend/src/pages/user/register /home/dan/tmp/clients-frontend/src/pages/user/register-result

```
I figured out that the problem was just a typo in the component attribute value of the ` register`  and `register-result` paths:
changed `./user/register` to `./User/register` and worked like a charm.

**Comment by chenshuai2144** [comment]
fixed
