### ISSUE TITLE
🐛[BUG] pro v5 & antd v4.16.6 使用格栅Row、Col报错

### ISSUE THREAD

**Issue by hellozhaoxudong** [ant-design/ant-design-pro#8707]
### 🐛 bug 描述

使用umi-create创建pro v5项目，页面中引用antd的格栅Row、Col，使用后报错。
![image](https://user-images.githubusercontent.com/25793576/125180892-ed73db80-e231-11eb-96eb-839f554f4166.png)

### 📷 复现步骤

使用umi-create创建pro v5项目，页面中引用antd的格栅Row、Col，使用后报错。
![image](https://user-images.githubusercontent.com/25793576/125180899-02506f00-e232-11eb-85fa-9a0be1bd562f.png)

使用格栅
![image](https://user-images.githubusercontent.com/25793576/125180904-109e8b00-e232-11eb-82ed-11560f5c0ded.png)

### 🏞 期望结果
正确展现格栅

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本 3.5.0
- 浏览器环境 chrome
- 开发环境  windows

**Comment by hellozhaoxudong** [comment]
的确是mfsu的问题，删除/src/.umi文件后，重新启动，就不报错了。或者关闭mfsu。

**Comment by chenshuai2144** [comment]
mfsu 要提供一个手动刷新的能力的
