### ISSUE TITLE
🧐[问题] umi add block failed

### ISSUE THREAD

**Issue by always-walking** [ant-design/ant-design-pro#8708]
### 🧐 问题描述

tong@DESKTOP-OPKVHQ5:~/code/mintP$ umi block clear
✔ 🗑  start clear: /home/tong/.umi3/blocks
tong@DESKTOP-OPKVHQ5:~/code/mintP$ umi block add DashboardAnalysis

✔ 😁  Parse url and args
⠋ 🔍  clone git repo from https://gitee.com/umijs/umi-blocks.gitCloning into 'github.com/umijs/umi-blocks'...
⠴ 🔍  clone git repo from https://gitee.com/umijs/umi-blocks.gitremote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (81/81), done.
⠸ 🔍  clone git repo from https://gitee.com/umijs/umi-blocks.gitremote: Total 2474 (delta 17), reused 2 (delta 0), pack-reused 2387
Receiving objects: 100% (2474/2474), 2.76 MiB | 4.65 MiB/s, done.
Resolving deltas: 100% (1433/1433), done.
✔ 🔍  clone git repo from https://gitee.com/umijs/umi-blocks.git
✖  error     AssertionError [ERR_ASSERTION]: /home/tong/.umi3/blocks/github.com/umijs/umi-blocks/DashboardAnalysis don't exists 
    at /home/tong/code/mintP/node_modules/@umijs/block-sdk/lib/addBlock.js:222:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/tong/code/mintP/node_modules/@umijs/block-sdk/lib/addBlock.js:110:103)
    at _next (/home/tong/code/mintP/node_modules/@umijs/block-sdk/lib/addBlock.js:112:194)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by always-walking** [comment]
怎么是gitee.com？

**Comment by always-walking** [comment]
重新从github安装了，但是为什么umi block add的时候，总是从gitee去拉取？

✔ 😁  Parse url and args
⠋ 🔍  clone git repo from https://gitee.com/umijs/umi-blocks.gitCloning into 'github.com/umijs/umi-blocks'...


而这个gitee好久没更新了
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个功能已经废弃并停止维护，如果需要建议自行frok维护。

------

This function has been abandoned and stopped maintenance. If necessary, it is recommended to start maintenance by yourself.recommended to start maintenance by yourself.
