### ISSUE TITLE
🐛[BUG] umiconfig 关闭了 antd，打包出的 umi.css 还是会有antd的样式

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/ant-design-pro#8709]
### 🐛 bug 描述

umi config 关闭了 antd，打包出的 umi.css 还是会有antd的样式

### 📷 复现步骤

用pro-v5初始化的新项目，关闭antd，直接打包

### 🏞 期望结果

umi.css中不包含antd的样式

### © 版本信息

- Ant Design Pro 版本: 2.0.2
- umi 版本 3.5.0
- 浏览器环境 chrome
- 开发环境 windows

**Comment by chenshuai2144** [comment]
来个重现的仓库把

**Comment by hemengke1997** [comment]
@chenshuai2144  搞了个打包好的仓库  https://github.com/hemengke1997/test-build

**Comment by chenshuai2144** [comment]
你确定demo是对的吗？里面用了很多antd的组件

**Comment by hemengke1997** [comment]
是的，我的疑惑是，为什么 antd 的 css 会打包到 umi.css 中
我现在的项目中也是用v5搭建的，关闭了 antd config，打包出来 vendor.css 和 umi.css 中都会有 ant 的所有样式，重复了..

**Comment by hemengke1997** [comment]
还有一个问题就是，antd 官网文档上写，要 `import 'antd/dist/style/index.less'` ，可是我从来没有引入过 antd 的样式，是 pro-components 引入了这些css文件吗？

**Comment by hemengke1997** [comment]
![image](https://user-images.githubusercontent.com/49073282/125238562-f8a23680-e319-11eb-8cc0-1aee0c59306d.png)

不知道为什么会有这么多css动态加载进来，总是非常多重复的antd样式，导致没法在global.less中自定义less变量，因为永远会被后来的覆盖

**Comment by hemengke1997** [comment]
![image](https://user-images.githubusercontent.com/49073282/125239025-a9a8d100-e31a-11eb-9b18-8b8b249856af.png)

这个css，不知道哪来的，把antd的样式全量加载了

**Comment by hemengke1997** [comment]
太折磨人了，弄了将近一天，还是没弄明白为什么会全量加载antd的css， 产品经理喊我明天提桶走人， 枯了，一个自定义样式都整不明白
