### ISSUE TITLE
🐛[BUG] target为_blank的菜单,点击span不跳转页面

### ISSUE THREAD

**Issue by lingting** [ant-design/ant-design-pro#8711]
### 🐛 bug 描述
path为http地址, target为_blank 点击菜单项文字右侧, 不跳转页面, 点击菜单文字 跳转页面

### 💻 复现代码
https://github.com/ballcat-projects/ballcat-ui-react/tree/dev
账号: admin 密码; a123456
### © 版本信息

- Ant Design Pro 版本:  5
- umi 版本  3.5.0
- 浏览器环境 chrome 91.0.4472.124
- 开发环境 win10

**Comment by chenshuai2144** [comment]
你都自定义了，这里直接用 a 标签？

```tsx
 itemRender={(nr, params, routes, paths) => {
        const first = routes.indexOf(nr) === 0;
        return first ? (
          <Link to={paths.join('/')}>{nr.breadcrumbName}</Link>
        ) : (
          <span>{nr.breadcrumbName}</span>
        );
      }}
```

**Comment by lingting** [comment]
> 你都自定义了，这里 `menuItemProps.isUrl` 直接用 a 标签？
> 
> ```tsx
>    menuItemRender={(menuItemProps, defaultDom) => {
>         if (
>           menuItemProps.isUrl ||
>           !menuItemProps.path ||
>           location.pathname === menuItemProps.path
>         ) {
>           return defaultDom;
>         }
>         return <Link to={menuItemProps.path}>{defaultDom}</Link>;
>       }}
> ```

我可以自定义改为 a标签, 不过 defaultDom 也是存在这个bug吧?

**Comment by chenshuai2144** [comment]
defaultDom  里面只是个span 而已，就是为了不依赖 Link，

**Comment by lingting** [comment]
> defaultDom 里面只是个span 而已，就是为了不依赖 Link，

懂了.

**Comment by lingting** [comment]
> defaultDom 里面只是个span 而已，就是为了不依赖 Link，

谢谢.
