### ISSUE TITLE
🧐[问题]IntroduceRow not defined

### ISSUE THREAD

**Issue by always-walking** [ant-design/ant-design-pro#8712]
### 🧐 问题描述

ReferenceError: IntroduceRow is not defined
Analysis
.ant-design-pro/src/pages/analysis/index.tsx:99
   96 | return (
   97 |   <GridContent>
   98 |     <>
>  99 |       <Suspense fallback={<PageLoading />}>
      | ^  100 |         <IntroduceRow loading={loading} visitData={data?.visitData || []} />
  101 |       </Suspense>
  102 | 
View compiled
▶ 22 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by chenshuai2144** [comment]
fixed in new blocks
