### ISSUE TITLE
🐛[BUG]使用Dva时连接时，调用dispath报错

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#8713]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/51156342/125222072-e6190480-e2fb-11eb-9036-da054bfae61b.png)

dispath 不是一个函数，有没有具体的案例使用typecript中使用Dva
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
来个重现，让我看看你 怎么写的
