### ISSUE TITLE
后面的V5版，是不是redux 观察不了state的数据了。

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8714]
![image](https://user-images.githubusercontent.com/32530210/125265849-d28b8f00-e337-11eb-9574-163dc3868391.png)

**Comment by chenshuai2144** [comment]
没有用 redux了，你可以直接在 react devtool 中看，全部用了hooks

**Comment by xyzabc0004** [comment]
这下好了，步子跨的有点大，有点被扯到蛋了。
