### ISSUE TITLE
🧐[问题] 请问pro-v5 官方预览页面，为什么全量打包了antd的css

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/ant-design-pro#8715]
### 🧐 问题描述

请问大佬，是否不应该全量打包antd的css？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/49073282/125305303-d54eaa00-e360-11eb-8499-ef509fc5d4b0.png)

**Comment by chenshuai2144** [comment]
css 是按需的，但是是打在一起的，不支持分包。你有什么需求吗？

**Comment by hemengke1997** [comment]
谢谢陈帅大哥回复，我希望能把重复的css去重打包，我现在打出来的 umi.css 有4w+行，其中有重复的样式，我只在global.less中引入过一次 `antd/dist/index.less` ，很疑惑为什么有重复的

**Comment by chenshuai2144** [comment]
不要引入 antd/dist/index.less

dist 里面是全量的，你需要什么引入什么
