### ISSUE TITLE
通过官网创建的时候没有显示是V4还是V5只有如下 图所示🧐[问题]

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8716]
![image](https://user-images.githubusercontent.com/53714134/125305579-07600c00-e361-11eb-9a04-74f2418f4f82.png)
发现大概是简单的就是v4如果是复杂的就是v4，但是没有明确的版本选择。

**Comment by TinsFox** [comment]
![image](https://user-images.githubusercontent.com/33956589/125386328-acfd9480-e3ce-11eb-977f-aaf1f8ad7376.png)
simple => 简单版，一般用于自己的项目工程，没人会基于complete开发吧，complete是完整版，所有的示例代码都在里面

**Comment by chenshuai2144** [comment]
已经改了，同步了一下代码
