### ISSUE TITLE
🧐[问题]开启msfu功能后，控制台出现很多warning

### ISSUE THREAD

**Issue by liuyang-1990** [ant-design/ant-design-pro#8717]
### 🧐 问题描述
开启msfu功能后，控制台出现很多warning，关闭msfu后，waning消失。

### 🚑 其他信息
![1626143713(1)](https://user-images.githubusercontent.com/29528177/125381263-2d6bc780-e3c6-11eb-81b5-7e6e9179860b.png)

**Comment by chenshuai2144** [comment]
这个是map没有找到的原因，不会有任何影响的
