### ISSUE TITLE
👑 [需求]搜索到的二级子菜单没有做自动展开

### ISSUE THREAD

**Issue by BigCodeDragon** [ant-design/ant-design-pro#8722]
### 🥰 需求描述
开启菜单搜索功能后，如果是搜索子菜单，会得到一个没有展开的一级菜单，如果才能让这个一级菜单做自动展开。

**Comment by chenshuai2144** [comment]
ProLayout 会根据 location.pathname 来自动选中菜单，并且自动生成相应的面包屑。如果不想使用可以自己配置 selectedKeys 和 openKeys 来进行受控配置。

**Comment by BigCodeDragon** [comment]
> ProLayout 会根据 location.pathname 来自动选中菜单，并且自动生成相应的面包屑。如果不想使用可以自己配置 selectedKeys 和 openKeys 来进行受控配置。

![企业微信截图_1626157320842](https://user-images.githubusercontent.com/50037648/125401485-d0800980-e3e5-11eb-9626-14a3d14368d7.png)
![image](https://user-images.githubusercontent.com/50037648/125401616-f7d6d680-e3e5-11eb-82bf-d2f9bbf215bf.png)

**Comment by chenshuai2144** [comment]
要自己控制 openkeys 的，我们内置没有这个逻辑
