### ISSUE TITLE
🐛[BUG] 使用openapi功能报错

### ISSUE THREAD

**Issue by JackXueX** [ant-design/ant-design-pro#8725]
### 🐛 bug 描述

使用openapi功能报错，报错如截图
![image](https://user-images.githubusercontent.com/42790406/125390197-08328580-e3d5-11eb-87f3-ca3db9e8814c.png)

### 📷 复现步骤
1. 在config文件下添加test.json文件
2. 在config.ts文件里面添加如下代码
```
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: join(__dirname, 'test.json'),
      projectName: 'test',
      mock: false,
    },
```
3.执行 npm run openapi命令

### 🏞 期望结果

能狗使用openapi

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境chrome 91.0.4472.114
- 开发环境 [e.g. mac OS Big Sur11.4 m1]

**Comment by chenshuai2144** [comment]
这个不是openapi的报错

**Comment by JackXueX** [comment]
https://github.com/JackXueX/antd-pro-issues

**Comment by JackXueX** [comment]
> 这个不是openapi的报错

https://github.com/JackXueX/antd-pro-issues

**Comment by JackXueX** [comment]
> 这个不是openapi的报错

之前的代码没问题 执行完添加openapi的操作之后会报错

**Comment by JackXueX** [comment]
> 这个不是openapi的报错

问题解决了 是openapi使用的有问题 需要把原来的代码注掉
