### ISSUE TITLE
🐛[BUG] url MUST be a string

### ISSUE THREAD

**Issue by TinsFox** [ant-design/ant-design-pro#8729]
### 🐛 bug 描述
url MUST be a string
修复 issues [8721](https://github.com/ant-design/ant-design-pro/issues/8721) 导致的

### 📷 复现步骤
正常拉取安装

### 🏞 期望结果
0 error

### 💻 复现代码
```jsx
 useEffect(() => {
    setNotices(data || []);
  }, [data]);
```

### © 版本信息

- Ant Design Pro 版本:@5.0.0
- umi 版本@3.5.0
- 浏览器环境@91.0.4472.114
- 开发环境@mac OS 10.13.4

**Comment by TinsFox** [comment]
本地修复方法
```jsx
// src/components/NoticeIcon/index.tsx
const NoticeIconView = () => {
  const {initialState} = useModel('@@initialState');
  const {currentUser} = initialState || {};
  const [notices, setNotices] = useState<API.NoticeIconItem[]>([]);
- const {data} = useRequest(getNotices());
+ const {data} = useRequest('/api/notices');
```

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/ant-design-pro/commit/12cf2f9a62ba782c94c4d4d916129546181b99d7

这样的方法是最好的， 竟然绕过了测试。我应该加个别的测试方法了
