### ISSUE TITLE
export import改动之后造成前端和后端语义化不一致

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design-pro#873]
前端现在
`export default {
  namespace: 'global',
  state: {
  },
  effects: {
  },
  reducers: {
  },
  subscriptions: {
  },
};`
import的地方需要.default
`app.model(require('./models/global').default)`
然而mock的地方import却不需要.default
'mock/notices.js'
`export default {
  'GET /api/notices': (req, res) => {
    res.json([
      {
        id: '000000001',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/ThXAXghbEsBCCSDihZxY.png',
        title: '你收到了 14 份新周报',
        datetime: '2017-08-09',
        type: '通知',
      },
    ]);
  },
};`
`import mockjs from 'mockjs';
import notices from './mock/notices';
import api from './mock/api';
import { format, delay } from 'roadhog-api-doc';

// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';

const proxy = {
  ...api, 
  ...notices, // 这里却并不需要.default
};

export default noProxy ? {} : delay(proxy, 1000);`
请问如果我还想和以前一样import时不想.default要如何做呢？

**Comment by yesmeck** [comment]
把 `require('./models/global').default` 改成 `import global from './models/global'`;

> 前端和后端语义化不一致

不是前后端不一致，本身 ES6 module 和 CommonJS module 就是不同的标准。

**Comment by rookie-luochao** [comment]
我这样导出去
'config/grids/index.js'
`
export default {
  ...gridsList,
}
`
我在需要的地方这样引入
`
import gridsConfig from 'config/grids';
import PageHeaderLayout from '../../layouts/PageHeaderLayout';
import styles from './index.less';

console.log('3333333', gridsConfig)
`
这个导入数据就给我加了default属性，以前是没有的
![image](https://user-images.githubusercontent.com/22948077/35725219-8bf2e794-083b-11e8-8f1e-54ef63fe979c.png)

**Comment by yesmeck** [comment]
你可以试试在 ant-design-pro  的 master 分支上能不能重现。

**Comment by rookie-luochao** [comment]
谢谢您的解答，是require()要加.default了，以前用require导入不用加.default，不是import的问题
