### ISSUE TITLE
如何打包生产部署， 生产环境中不想要 primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false 这些参数🧐[问题]

### ISSUE THREAD

**Issue by mlbao** [ant-design/ant-design-pro#8730]

**Comment by chenshuai2144** [comment]
<html>
<body>
<h3 id="settingdrawer" style="box-sizing: border-box; margin: 42px 0px 18px; color: rgb(69, 77, 100); font-weight: 500; line-height: 1.40625; font-size: 20px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">SettingDrawer</h3><blockquote style="box-sizing: border-box; margin: 16px 0px; padding: 0px 24px; color: rgba(69, 77, 100, 0.7); border-left: 4px solid rgb(235, 237, 241); overflow: hidden; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 16px 0px;">SettingDrawer 提供了一个图形界面来设置 layout 的配置。不建议在正式环境中使用。</p></blockquote>

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
settings | layout 的设置 | Settings \| Settings | -
onSettingChange | Settings 发生更改事件 | (settings: [Settings](#Settings) ) => void | -
hideHintAlert | 删除下方的提示信息 | boolean | -
disableUrlParams | 禁止同步设置到查询参数 | boolean | false


</body>
</html>
