### ISSUE TITLE
下载了  v5     complete  里面的model文件没有找到具体用到那里🧐[问题]

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8733]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/53714134/125469648-f2adcdd0-72d7-43a2-ba32-be4150801381.png)

只看到了这个model文件，但是并没有看到这个文件具体使用到了那里
搜索了整个文件也就是在model.ts这个文件里出现。
![image](https://user-images.githubusercontent.com/53714134/125469856-d0d6623d-1d42-4d9c-906c-91f462babfa4.png)
在v4的版本里面是会有一个dispatch 一个发一个收。

**Comment by xyzabc0004** [comment]
https://pro.ant.design/zh-cn/docs/upgrade-v5/
专家们说之前V4的一套状态数据管控在V5下面不用了（不推荐使用），redux，在V5下面没有采用了。

**Comment by chenshuai2144** [comment]
是忘记删除了。我最近会重新拉一下
