### ISSUE TITLE
🐛[BUG] 提交到自己的gitee和github前做precommit， fabric verify-commit过不去。

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-pro#8734]
### 🐛 bug 描述

提交到自己的gitee和github前做precommit， fabric verify-commit过不去。

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/18542211/125550844-7ba25cd7-671e-4e78-8e6f-c8806a2ce096.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by kaoding** [comment]
windows 上。

**Comment by chenshuai2144** [comment]
按照规范来写 commit？

**Comment by kaoding** [comment]
是按照规范来的（我在windows上），修改任务东西都commit不了。

**Comment by chenshuai2144** [comment]
你来个录屏试试，我还没碰过兼容性问题

**Comment by kaoding** [comment]
1、从 github 上 clone 下来
2、yarn (不做这步，commit 没有问题）
3、随便修改一个地方
4、再 commit 就出现上面问题

**Comment by kaoding** [comment]
@chenshuai2144 这个问题怎么解决？

**Comment by chenshuai2144** [comment]
commit  符合规范了吗？

**Comment by kaoding** [comment]
> commit 符合规范了吗？

不是 commit 规范问题，我就改一点东西（如下图加点注释）都不能 commit 通过
![image](https://user-images.githubusercontent.com/18542211/126266484-6e3bedeb-38c7-477a-91ab-9da27b526498.png)

出现这种错误

![image](https://user-images.githubusercontent.com/18542211/126266631-d355176c-d8ee-44bb-9a24-1b9b545d0445.png)

**Comment by chenshuai2144** [comment]
奇怪了我也是windows，难道是兼容性问题

**Comment by kaoding** [comment]
原因找到了，是在发布 v5 版本时，在 package.json 文件里加了
`  "gitHooks": {
    "commit-msg": "fabric verify-commit"
  } ` 
这个原因导致的。

**Comment by kaoding** [comment]
要不先移去这个。

**Comment by chenshuai2144** [comment]
不要呀，fabric verify-commit 是为了增加提交前验证，验证 commit 的合理性，你删掉了功能不就没了

**Comment by cyqhhj** [comment]
我今天也遇到这个问题了，就很奇怪

**Comment by cyqhhj** [comment]
@kaoding 怎么解决的？

**Comment by kaoding** [comment]
> @kaoding 怎么解决的？

拿掉 package.json 内的 
```
  "gitHooks": {
    "commit-msg": "fabric verify-commit"
  }
```

**Comment by chenshuai2144** [comment]
提交的时候没设置环境变量，要专门处理了

**Comment by yinzixie** [comment]
还没解决方案吗？真的离谱。

**Comment by sunguoxing0628** [comment]
1. 文件内容

```// https://umijs.org/config/
import { defineConfig } from 'umi';
import { join } from 'path';

import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const { REACT_APP_ENV } = process.env;

export default defineConfig({
  devServer: {
    port: 8091,
  },
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},
  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
  nodeModulesTransform: { type: 'none' },
  mfsu: {},
  webpack5: {},
  exportStatic: {},
});
```
2. 错误信息

``` > running commit-msg hook: fabric verify-commit
   ERROR  invalid commit message format.
  Proper commit message format is required for automated changelog generation. Examples:
    💥 feat(compiler): add 'comments' option
    🐛 fix(compiler): fix some bug
    📝 docs(compiler): add some docs
    🌷 UI(compiler): better styles
    🏰 chore(compiler): Made some changes to the scaffolding
    🌐 locale(compiler): Made a small contribution to internationalization
    See .github/commit-convention.md for more details.
commit-msg hook failed (add --no-verify to bypass)
```

@chenshuai2144   对于下载下来的文件，我只增加了下面的一个参数，就报错了，同时也没有找到`.github/commit-convention.md`这个文件在哪里，目前只有拿掉`gitHooks`才能提交，不知道这个是什么问题。

```
devServer: {
    port: 8091,
  },
```

**Comment by chenshuai2144** [comment]
按照规范写 commit，这个报错是commit 有问题不是你的代码有问题

**Comment by sunguoxing0628** [comment]
> 按照规范写commit，这个报错是commit 有问题不是你的代码有问题

@chenshuai2144  好的，是我没注意提示信息，`commit message `应该满足指定格式，如`message`写做`fix: fix some  bug`，这样我就提交成功了。

@kaoding  你可以这么试一下。

**Comment by kaoding** [comment]
不是这个原因，我都试过了（我就新拉一个antd pro 新库下来，改几个字，就提交不到自己的库中），就是报，
```
"gitHooks": {
    "commit-msg": "fabric verify-commit"
    }
```
过不去，暂时去掉这个。

**Comment by sunguoxing0628** [comment]
> 不是这个原因，我都试过了（我就新拉一个antd pro 新库下来，改几个字，就提交不到自己的库中），就是报，
> 
> ```
> "gitHooks": {
>     "commit-msg": "fabric verify-commit"
>     }
> ```
> 
> 过不去，暂时去掉这个。

@kaoding  按照提示信息来看，只是`message`格式的问题，可以注意一下那个冒号，我第一次没注意用的中文冒号也是不行的，实在不行，那就只能按照你说的来了。

**Comment by ziwosan** [comment]
@chenshuai2144 请问这个commit校验规则可以自行配置吗？

**Comment by SugarTiger** [comment]
大兄弟，就是你的commit-msg 格式不对，所以报错了，可以参考这个地址 https://learnku.com/docs/antd-pro/5/commit-msg/11203#472210
注意commit-msg里面的冒号：和描述之间，一定要有个空格，不如都会提示格式不正确。
例如：
错误的：feat:add BASE_API_URL
正确的：feat: add BASE_API_URL

**Comment by mansion-sun** [comment]
原来是空格问题，感觉这个空格没必要，我试了很多次，一直以为是模块名或代码问题，冒号中英文也试过了，谁能想的有空格啊，大佬这个规则着实有点坑，之前公司配置的规则没有渉及空格的！ @chenshuai2144

**Comment by jonny-xhl** [comment]
有没有遇到过merge branch的default message也会通不过。

通过vscode合并分支的默认message也会导致合并失败。

E.g

```
Merge branch 'feature/demo' into development
```

**Comment by yangrenmu** [comment]
![image](https://user-images.githubusercontent.com/18193168/170934169-6334bd41-08e8-47af-8f6b-2ebc6d1e7e8d.png)
这意思是，merge 的信息，都过不了么？

**Comment by chenshuai2144** [comment]
merge 搞个 -n 就能过去了

**Comment by LegionMrG** [comment]
> 按照规范写 commit，这个报错是commit 有问题不是你的代码有问题

我知道是commit有问题，比如我填“style: prettier格式调整”提交就报错，但是填“UI: prettier格式调整”就可以。报错信息说“See .github/commit-convention.md for more details.”但是找一圈没找到这个md在哪，大佬给个地址？

**Comment by LegionMrG** [comment]
> ![image](https://user-images.githubusercontent.com/18193168/170934169-6334bd41-08e8-47af-8f6b-2ebc6d1e7e8d.png) 这意思是，merge 的信息，都过不了么？

兄弟这图哪来的？

**Comment by Topppy** [comment]
> > ![image](https://user-images.githubusercontent.com/18193168/170934169-6334bd41-08e8-47af-8f6b-2ebc6d1e7e8d.png) 这意思是，merge 的信息，都过不了么？
> 
> 兄弟这图哪来的？

https://regexper.com/

**Comment by LegionMrG** [comment]
> > > ![image](https://user-images.githubusercontent.com/18193168/170934169-6334bd41-08e8-47af-8f6b-2ebc6d1e7e8d.png) 这意思是，merge 的信息，都过不了么？
> > 
> > 
> > 兄弟这图哪来的？
> 
> https://regexper.com/

哎呀呀不是啦，我是说commit信息的type类型，因为我不知道要填哪种type类型才不会报错

**Comment by LegionMrG** [comment]
经过我一顿寻根索源终于找到了判断依据 https://github.com/umijs/fabric/blob/master/src/verifyCommit.ts。
1、源码所在的@umijs/fabric竟然还没有 .github/commit-convention.md；
2、那个perf前面还有一个骚符号 Σ(￣ロ￣lll)。

希望作者大大可以放一下说明commit-convention.md，至少type统一一下，要么全部没有符号纯英文，要么全部前面加一个符号，谢谢。 @chenshuai2144

**Comment by choi2k** [comment]
> 有没有遇到过merge branch的default message也会通不过。
> 
> 通过vscode合并分支的默认message也会导致合并失败。
> 
> E.g
> 
> ```
> Merge branch 'feature/demo' into development
> ```



> merge 搞个 -n 就能过去了

想问一下在 vscode 怎么弄这个？我先在都是命令行 no-verify, 又不想删掉 hooks..

**Comment by jasonChen1234** [comment]
> merge 搞个 -n 就能过去了

@chenshuai2144 有时候是通过写可视化页面的做的合并，比如webstorm ，sourceTree，并不一定是命令行的形式。建议应该判断是否在 merge 状态下，如果是在 merge 状态下应该跳过检验 commit msg。

处理方案：
其实当处于merge状态时，git会在.git目录中生成一个MERGE_HEAD文件，不是merge状态则没有，所以可以判断这个文件是否存在来解决此问题。

MERGE_HEAD="$(git rev-parse --show-toplevel)/.git/MERGE_HEAD"
​
if [ -e $MERGE_HEAD ]; then
  echo 'skip pre-commit hook...'
  exit 0
fi

**Comment by chenshuai2144** [comment]
@jasonChen1234 

在 fabric 里来个 pr?
https://github.com/umijs/fabric

**Comment by xiaoyaozi1010** [comment]
Why you just closed this issue? Did it fixed now?
I cannot commit the default merge message with pre-commit, the default merge message just like: `Merge branch 'feature/xxxx/xxxx' to 'develop'`.
Can the maintainer help?

**Comment by fengyuchaochao** [comment]
如何在这个基础上，自定义commit msg的校验规则呀？求助

**Comment by semmywong** [comment]
> 

这代码是加在`husky.sh`里的吗？

**Comment by semmywong** [comment]
> > merge 搞个 -n 就能过去了
> 
> @chenshuai2144 有时候是通过写可视化页面的做的合并，比如webstorm ，sourceTree，并不一定是命令行的形式。建议应该判断是否在 merge 状态下，如果是在 merge 状态下应该跳过检验 commit msg。
> 
> 处理方案： 其实当处于merge状态时，git会在.git目录中生成一个MERGE_HEAD文件，不是merge状态则没有，所以可以判断这个文件是否存在来解决此问题。
> 
> MERGE_HEAD="$(git rev-parse --show-toplevel)/.git/MERGE_HEAD"​if [ -e $MERGE_HEAD ]; then  echo 'skip pre-commit hook...'  exit 0 fi

这代码是加在`husky.sh`中的吗？
