### ISSUE TITLE
🧐[问题]为啥打包的时候会重复生成样式文件，切换不同页面后会导致样式被覆盖

### ISSUE THREAD

**Issue by Martinzz** [ant-design/ant-design-pro#8736]
### 🧐 问题描述

打包的时候会重复生成样式文件，切换不同页面后会导致样式被覆盖，
请问怎么处理重复打包和覆盖的问题？

![image](https://user-images.githubusercontent.com/12439421/125577619-f3776e64-bbe1-4cee-9214-b2e9960fd165.png)

**Comment by chenshuai2144** [comment]
https://github.com/umijs/plugins/blob/master/packages/preset-ant-design-pro/src/chainWebpack.ts

试着加一下这个代码，一般来说只有开发环境会这样。可能是因为引用了不同路径的less导致的
