### ISSUE TITLE
👑 [需求] 使用ProTable 列的search属性设置为false，查询参数就会排除掉这个列，能否解决以下问题

### ISSUE THREAD

**Issue by yuandalu** [ant-design/ant-design-pro#8738]
### 🥰 需求描述

如果在外面额外控制查询的时候，还想走ProTable的param那套关系，我发现必须配一个列，，但是配置一个列就会导致原有的查询表单会显示一个查询框，我尝试隐藏这个框，比如search=false，或者renderFormItem=null，都会导致param里这个查询字段消失，能否可以支持param里面带着这个字段，且自带的查询框里不显示这个表单，这样我在外面其他位置控制；目前的笨办法是renderFormItem=<></>，但是这样会占位置，倒是即使表单不满足换行也会因为其他隐藏的表单占用了位置而换行

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/3860040/125584138-02c362f9-cbde-477d-820a-ac207c1063d0.png)

#6590

**Comment by chenshuai2144** [comment]
<html>
<body>


params | 用于 request 查询的额外参数，一旦变化会触发重新加载 | object | -
-- | -- | -- | --



</body>
</html>

**Comment by yuandalu** [comment]
> 用于 request 查询的额外参数，一旦变化会触发重新加载

自己往里面添加的话，首先得单独维护一个状态，另外表单自动管理的url带参变化也就不生效了
![image](https://user-images.githubusercontent.com/3860040/125817910-eef513d3-e709-4351-95a8-7c37a369f4bc.png)

现在是 利用setFieldsValue很好的衔接了原有的一整套方案，而且还能在外面随便自定义查询样式
![image](https://user-images.githubusercontent.com/3860040/125818427-e7dbcd37-c743-4201-80e1-cf41bb83e917.png)
这样我会控制上面的自定义的点击直接触发查询，
![image](https://user-images.githubusercontent.com/3860040/125818534-1deaf9d0-839f-447e-b57b-59c0717472bd.png)

下面的自动生成的保持原有的点击查询，

目前解决方案可以，只是因为不声明列配置，或者声明了设置为search为false，列就不会作为查询参数生效，所以我设置了自定义<></>，但是这样会导致还是占用位置：
![image](https://user-images.githubusercontent.com/3860040/125818867-59e3d716-43a2-4427-a382-e540b6679d1e.png)


params可以自定义，但是那样和原来的自动处理的事情结合就不完美了

**Comment by yuandalu** [comment]
> params	用于 request 查询的额外参数，一旦变化会触发重新加载	object	-

我追了一下源码，用了SchemaForm，他正好支持表单隐藏，是相当于 input hidden的效果吧，能否从这个角度支持下protable 的列可以配置隐藏参数，隐藏表单，单又能使他生效，我觉得这个属性很有意义，😃

**Comment by chenshuai2144** [comment]
hidden 之际不渲染了，你试试 display:none 把

**Comment by yuandalu** [comment]
> hidden 之际不渲染了，你试试 display:none 把

请问在哪里写这个样式呢，
![image](https://user-images.githubusercontent.com/3860040/128135008-37c44535-5066-4e33-8b22-03799c03df06.png)

属性里没有控制样式的地方，

**Comment by chenshuai2144** [comment]
filedprops 的 style

**Comment by dimsumc** [comment]
> > 用于 request 查询的额外参数，一旦变化会触发重新加载
> 
> 自己往里面添加的话，首先得单独维护一个状态，另外表单自动管理的url带参变化也就不生效了 ![image](https://user-images.githubusercontent.com/3860040/125819054-ace1b164-a9a2-4a4d-b8de-848da31184b2.png)
> 
> 现在是 利用setFieldsValue很好的衔接了原有的一整套方案，而且还能在外面随便自定义查询样式 ![image](https://user-images.githubusercontent.com/3860040/125818427-e7dbcd37-c743-4201-80e1-cf41bb83e917.png) 这样我会控制上面的自定义的点击直接触发查询， ![image](https://user-images.githubusercontent.com/3860040/125818534-1deaf9d0-839f-447e-b57b-59c0717472bd.png)
> 
> 下面的自动生成的保持原有的点击查询，
> 
> 目前解决方案可以，只是因为不声明列配置，或者声明了设置为search为false，列就不会作为查询参数生效，所以我设置了自定义<></>，但是这样会导致还是占用位置，这样即使不需要展开，也会出现展开，就是这个不太完美了，如果有办法能让他不占用位置就行，我设置renderFormItem:null处理结果和search=false一样： ![image](https://user-images.githubusercontent.com/3860040/125819643-58e79eae-7da6-48b3-b173-3e6fa6a9f32a.png)
> 
> ![image](https://user-images.githubusercontent.com/3860040/125818867-59e3d716-43a2-4427-a382-e540b6679d1e.png)
> 
> params可以自定义，但是那样和原来的自动处理的事情结合就不完美了
> 
> 能否这样，seach=false还是保持现有的规则，但是renderFormItem:null 让参数还能被自动管理，但是就不要在表单里渲染界面了,或者额外加个参数控制

想问最后有什么好的解决方案么... 最近遇到一个差不多的问题
