### ISSUE TITLE
🐛[BUG] splitMenus: true,模式下，使用postMenuData 获取菜单，菜单展示异常

### ISSUE THREAD

**Issue by 673019334** [ant-design/ant-design-pro#8739]
### 🐛 bug 描述

proSettings ={   splitMenus: true} 的情况下，使用postMenuData从后台获取菜单展示异常
![image](https://user-images.githubusercontent.com/54474073/125592842-5d42a52b-75d9-46c3-8dab-a0adeb6ee4b3.png)

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/54474073/125592681-5a3823b6-67a2-4621-ab82-7cfb5f707c55.png)

### 💻 复现代码
proSettings ={   splitMenus: true} 的情况下，使用postMenuData从后台获取菜单展示异常，

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
说的太模糊了，而且我们不推荐用 postMenuData 来做这种事情。postMenuData  实在最后渲染之前进行的修改，不会处理权限和layout配置的东西

https://pro.ant.design/zh-CN/docs/advanced-menu 这里有推荐的方式文档
