### ISSUE TITLE
🧐[问题] 在eslint的rules中设置了`"semi": [2, "never"]`，并且通过`yarn lint:fix`去除了分号，但在`git commit`的时候，报错：`error Extra semicolon semi`

### ISSUE THREAD

**Issue by hocko333** [ant-design/ant-design-pro#8742]
### 🧐 问题描述
举例：`git commit`的时候，报错显示在`abc.js`的第3行第2列的位置有多余的分号 `error Extra semicolon semi`，但事实上这个位置并没有分号。

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/45919606/125611023-442cddf4-8960-419f-b32e-3fa07cb4f0ba.png)
![image](https://user-images.githubusercontent.com/45919606/125611215-64db9470-a99f-4d74-9226-74bc97594d4b.png)

**Comment by chenshuai2144** [comment]
是被prettier掉了，这里不推荐你自定义，代码风格没什么好坏和别人一样才重要。

如果你要改，还需要改动 prettier 的配置

**Comment by hocko333** [comment]
> 是被prettier掉了，这里不推荐你自定义，代码风格没什么好坏和别人一样才重要。
> 
> 如果你要改，还需要改动 prettier 的配置

非常谢谢，通过修改prettier配置解决了这个问题。因为我之前一直遵循 `JavaScript Standard Style` 规范，所以在开发这个项目的时候也希望可以继续编写无分号代码。
