### ISSUE TITLE
**一直在这里等，不懂啊，好半天了**

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#8743]
**一直在这里等，等了好半天了，服务器崩了吗？**
```
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".
[5/5] 🔨  Building fresh packages...
[-/15] ⠁ waiting...
[2/15] ⠂ esbuild
[-/15] ⠂ waiting...
[-/15] ⠂ waiting...
[-/15] ⠂ waiting...
```

_Originally posted by @dhbyls in https://github.com/ant-design/ant-design-pro/issues/8656#issuecomment-880051787_

**Comment by himanhimao** [comment]
这个项目真烂，我起了半天没起来，各种BUG

**Comment by chenshuai2144** [comment]
@dhbyls 这几个包都是从服务器上下载的，都是国外的服务器国内访问很感人。

我们在文档中建议使用tyarn，你可以试试

**Comment by greenking19** [comment]
我也是服了 我今天也遇到了， yarn tyarn都是一样的问题 一天都是在building fresh packages....
