### ISSUE TITLE
🧐[问题]v5 如何通过接口返回的色值动态修改主题色

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design-pro#8744]
### 🧐 问题描述
客户需要设置网站的主题颜色，可否给个完整的例子，如何实现呢，antd pro v5版本

**Comment by PingZai-Tse** [comment]
我这联静态的都不行，你咋弄的？
我是这里配置的无效：
`
//config
theme: {
    'primary-color':defaultSettings.primaryColor,
  },

`

**Comment by chenshuai2144** [comment]
去看看antd 官方的方案把。

https://github.com/ant-design/ant-design/blob/268be65a7142d38b51a136f34591b3318e0eb463/.antd-tools.config.js#L36
