### ISSUE TITLE
正式版本v5.0.0中 ，服务器获取的菜单，项目文件路径是正确的，但是总是报404页面，怎么搞，我都是文档来的呀🧐[问题]

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#8745]
### 💻 示例代码
```
// 1. 获取菜单
const fetchMenus = async () => {
    const resp = await queryMenu();
    const menu2MenuDataItem: (m: API.Menu) => MenuDataItem = (m: API.Menu) => {
      const item: MenuDataItem = {
        name: m.name,
        path: m.path,
        hideInMenu: m.hide,
        icon: m.icon,
        locale:false,
        children: m.children?.map(menu2MenuDataItem),
      };
      return item;
    };

    if (resp.code === 0) {
      // console.log(resp.data.map(menu2MenuDataItem))
      return resp.data.map(menu2MenuDataItem);
      
    }
    return [];
  };

  // 如果是登录页面，不执行，是登录页面就执行
  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    const menus = await fetchMenus();
    // todo ...
```
```
// 2. 重新渲染菜单
menuDataRender: (menuData: MenuDataItem[]) => {
      if (initialState?.menus) {
        return initialState?.menus;
      }
      return [];
},
```

![image](https://user-images.githubusercontent.com/13744175/125734212-8e301e93-da90-4a7c-95a2-cb0f91e05d76.png)
![image](https://user-images.githubusercontent.com/13744175/125734211-4809a128-94bc-4f39-9319-cf43e9a4b2fa.png)

**Comment by dhbyls** [comment]
## 哎，发现了，服务器获取的菜单，我在routes.ts 中加了路由就可以了，可是为什么动态获取的菜单，还要在这里面配置呢，搞不明白！
![image](https://user-images.githubusercontent.com/13744175/125736816-d6f6bc9b-3cc9-45fd-9dac-6050a6a7153c.png)

**Comment by chenshuai2144** [comment]
服务器获取的是菜单，不是路由的。

路由还要单独配置

**Comment by renqian805** [comment]
> 服务器获取的是菜单，不是路由的。路由时编译态的暂时还不能动态
> 
> 路由还要单独配置

啊这，但我现在的需求是菜单和路由都是动态配置的，如果还是要在routes.ts写死的话，那还是差了点意思啊

**Comment by chenshuai2144** [comment]
路由不写，webpack 怎么知道要打包哪个文件。你要做到动态路由可能要在服务器跑个webpack，每次用户请求，重新编译js了

**Comment by chengzi-code** [comment]
那如果是控制权限呢， 比如说通过后台来获取菜单来控制权限， 但是还要在config里面配置下路由，而这里的路由还有用access来控制权限，   不控制的话，即使后端返回的菜单没有某个路径，但是还是可以通过url来访问的， 这个是个问题

**Comment by ZengJun-cloud** [comment]
@dhbyls   动态菜单的icon是怎么处理的呀？
