### ISSUE TITLE
🧐[问题]ant design pro 第一次创建项目可以选择v4 or v5 ，再次创建直接默认v5 无法再创建v4

### ISSUE THREAD

**Issue by baixuegit** [ant-design/ant-design-pro#8746]
### 🧐 问题描述
使用 yarn create umi myapp 或者yarn create umi 或者 npm create umi myapp
创建项目，没有下面的提示

? 🧙 Be the first to experience the new umi@3 ?
Pro V5
❯ Pro V4

**Comment by chenshuai2144** [comment]
更新下依赖把。这个已经太老了现在没有 v4 v5 了。直接最新的版本

**Comment by baixuegit** [comment]
我就想用v4 有没有什么办法

**Comment by 521guyu** [comment]
我依然想用v4怎么又什么操作方法吗

**Comment by zhangchuanbo** [comment]
> 我就想用v4 有没有什么办法

找到办法了吗？我降级create-umi到0.25.1选择v4也不管用

**Comment by 521guyu** [comment]
> > 我就想用v4 有没有什么办法
> 
> 我降级create-umi到0.25.1选择v4也不管用
https://github.com/ant-design/ant-design-pro/issues/8839   这个里面有提到  git clone https://github.com/ant-design/ant-design-pro && cd ant-design-pro && git checkout v4 这是simple 版的获取方式，完整版需要进一步处理(yarn run fetch:blocks)
需要clone下来项目。才行。直接创建的没有了

**Comment by qteamcheng** [comment]
这个有解决办法吗？ 有很大部分同学是想用V4版本的

**Comment by 521guyu** [comment]
> 这个有解决办法吗？ 有很大部分同学是想用V4版本的 @chenshuai2144

https://github.com/ant-design/ant-design-pro/issues/8839
