### ISSUE TITLE
开启MSFU报错

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8748]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/27960630/125759402-42db2cc9-9b3a-4cf1-bd47-60a69da9b0a5.png)
![image](https://user-images.githubusercontent.com/27960630/125759419-2b71c154-1797-4697-91f0-59c8c643d707.png)

### 🚑 其他信息
"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.0.19",
    "@ant-design/pro-form": "^1.25.0",
    "@ant-design/pro-layout": "^6.4.19",
    "@ant-design/pro-table": "^2.9.5",
    "@antv/g2plot": "^2.3.24",
    "@umijs/route-utils": "^1.0.33",
    "ahooks": "^2.10.5",
    "antd": "^4.16.0",
    "axios": "^0.20.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "classnames": "^2.2.6",
    "crypto": "^1.0.1",
    "echarts": "^5.1.2",
    "echarts-for-react": "^3.0.1",
    "lodash": "^4.17.11",
    "md5": "^2.3.0",
    "moment": "^2.25.3",
    "nsc-ol": "^0.1.1",
    "ol": "^6.5.0",
    "omit.js": "^2.0.2",
    "path-to-regexp": "^6.2.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-draggable": "^4.4.3",
    "react-helmet-async": "^1.0.4",
    "tree-utils": "0.0.21",
    "umi": "^3.4.25",
    "umi-request": "^1.0.8",
    "umi-serve": "^1.9.10",
    "url-parse": "^1.5.1",
    "use-merge-value": "^1.0.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.18",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.3.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "chalk": "^4.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "prop-types": "^15.7.2",
    "puppeteer-core": "^5.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3"
  },

**Comment by chenshuai2144** [comment]
umi 版本太低了，清空下缓存重新安装
