### ISSUE TITLE
🐛[BUG]ProTable 树形表格 展开按钮问题

### ISSUE THREAD

**Issue by JefferyChensp** [ant-design/ant-design-pro#8750]
### 🐛 bug 描述

ProTable实现树形表格点击展开按钮显示的是+。
### 📷 复现步骤
![image](https://user-images.githubusercontent.com/42525845/125760584-f8172e3b-68b6-433c-9d5e-4802fb5888ac.png)

### 🏞 期望结果

ProTable实现树形表格点击展开按钮实际应该显示的是-。
![image](https://user-images.githubusercontent.com/42525845/125760758-8a03b0f9-f6d9-4e72-a31a-6a1af948a441.png)

### 💻 复现代码
`const data = [
    {
      key: 1,
      name: 'John Brown sr.',
      age: 60,
      address: 'New York No. 1 Lake Park',
      children: [
        {
          key: 11,
          name: 'John Brown',
          age: 42,
          address: 'New York No. 2 Lake Park',
        },
        {
          key: 12,
          name: 'John Brown jr.',
          age: 30,
          address: 'New York No. 3 Lake Park',
          children: [
            {
              key: 121,
              name: 'Jimmy Brown',
              age: 16,
              address: 'New York No. 3 Lake Park',
            },
          ],
        },
        {
          key: 13,
          name: 'Jim Green sr.',
          age: 72,
          address: 'London No. 1 Lake Park',
          children: [
            {
              key: 131,
              name: 'Jim Green',
              age: 42,
              address: 'London No. 2 Lake Park',
              children: [
                {
                  key: 1311,
                  name: 'Jim Green jr.',
                  age: 25,
                  address: 'London No. 3 Lake Park',
                },
                {
                  key: 1312,
                  name: 'Jimmy Green sr.',
                  age: 18,
                  address: 'London No. 4 Lake Park',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      key: 2,
      name: 'Joe Black',
      age: 32,
      address: 'Sidney No. 1 Lake Park',
    },
  ];

  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: 'Age',
      dataIndex: 'age',
      key: 'age',
      width: '12%',
    },
    {
      title: 'Address',
      dataIndex: 'address',
      width: '30%',
      key: 'address',
    },
  ];

  return (
    ProTable
      columns={columns}
      dataSource={data}
    
  );`

以上为proTable的用法，如果使用 ant design 的Table就没有这种问题
`  return (
    <Table
      columns={columns}
      dataSource={data}
    />
  );
`

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
更新下依赖把，好久之前的问题了
