### ISSUE TITLE
📝[docs]文档中一些笔误

### ISSUE THREAD

**Issue by buqiyuan** [ant-design/ant-design-pro#8753]
### 🧐 问题描述

文档中有一些错别字或错误的标识

### 💻 示例代码

[错别字在文档中的位置](https://beta-pro.ant.design/docs/lint-cn#reactjsx-closing-tag-location-%E8%87%AA%E5%8A%A8-fix)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39730999/125787983-574b38f1-0c4a-49d0-bf4f-3ac8fa50c6fe.png)
![image](https://user-images.githubusercontent.com/39730999/125788167-a37f9a68-4fee-4387-9e57-7d07f9762055.png)

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro-site/pulls

**Comment by buqiyuan** [comment]
okay

> https://github.com/ant-design/ant-design-pro-site/pulls

thanks！I have submitted a [pull requests](https://github.com/ant-design/ant-design-pro-site/pull/569).
