### ISSUE TITLE
config.ts里面怎么区分生产和测试环境？

### ISSUE THREAD

**Issue by ztfstar** [ant-design/ant-design-pro#8757]
###  config.ts里面怎么区分生产和测试环境？

在config.ts文件里可以通过process.env.NODE_ENV拿到npm run build打包后的process.env.NODE_ENV值为'production'，但是我想区分生产和测试环境怎么办呢？因为我的项目要根据环境改变config里面的base和publicPath字段。

**Comment by kaoding** [comment]
config.dev.ts

**Comment by ztfstar** [comment]
> config.dev.ts

@kaoding 大佬，npm run build打包之后不是走config.ts里的配置逻辑吗？改config.dev.ts有用吗？

**Comment by ztfstar** [comment]
> config.dev.ts

@kaoding 大佬，npm run build打包之后不是走config.ts里的配置逻辑吗？改config.dev.ts有用吗？

**Comment by ztfstar** [comment]
@kaoding 我想根据生产环境还是测试环境在config设置不同的base和publicPath,怎么办呢

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/environment-manage#%E5%A4%9A%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83%E7%AE%A1%E7%90%86

看看这个文档
