### ISSUE TITLE
umi-request

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#8759]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/27960630/125910559-7a260196-9532-469f-b303-f3e07c7ac48c.png)
![image](https://user-images.githubusercontent.com/27960630/125910638-369bceff-5e16-4dbb-b855-9fffe287ddac.png)
这个错误我都已经拦截到了 并且没有返回响应 这不知道是哪抛出了的一个错误 每次报这个错代码不能继续运行了 必须刷新浏览器

**Comment by chenshuai2144** [comment]
关闭的时候最好解释一下或者提供一下解决方案帮助同样碰到的同学

**Comment by lovesL** [comment]
使用上的 问题在响应拦截器里必须返回一个结果 不返回就会报错
