### ISSUE TITLE
🧐[问题] 使用Ant Design tag组件报错

### ISSUE THREAD

**Issue by cdry** [ant-design/ant-design-pro#8760]
### 🧐 问题描述
按照官网的开始使用构建的新项目，使用Ant Design的Tag组件报错

### 💻 示例代码
![image](https://user-images.githubusercontent.com/20787516/125914313-604f8f7a-60b7-4f91-b836-be2ac06a84a4.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20787516/125914462-1b65e9c3-7506-42ba-aead-ddfe9bea4ed8.png)

**Comment by chenshuai2144** [comment]
mfsu 的问题把，umi 新版本会修掉

**Comment by cdry** [comment]
> mfsu 的问题把，umi 新版本会修掉

是的，就是mfsu的问题，删掉.umi重新运行就好了
