### ISSUE TITLE
🏆 Pro 体验脑暴 ❤️‍🔥 

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#8761]
* 编写 ts server 插件，带来更好的代码提示，点击 国际化的key跳转，点击 路由配置跳转，点击配置跳转到文档
* layout 支持嵌套 和 支持 icon形态
* 更好的项目初始化方案
* 增加监控最佳实践
* 优化现有的权限方案

欢迎畅所欲言,越具体越好

**Comment by xyzabc0004** [comment]
研究起来，还有点烧脑！

**Comment by iscmcloud** [comment]
问就是 多页签  multi-tab，中后台，真的少不了

**Comment by quarkcms** [comment]
@chenshuai2144 帅哥，我又来了；https://github.com/quarkcms/quark-ui基于Pro低代码构思的尝试！帅哥，帮兄弟顶顶。

**Comment by kaoding** [comment]
在前后端分离架构下，前端认证几乎是少不了，所以提交了一种最常用的认证方式

**Comment by fanhualei** [comment]
引入一个第三方的：富文本框

**Comment by 569202812** [comment]
初始化项目国际化选择大部分中台都不需要国际化，每次都需要删除增加配置

**Comment by TinsFox** [comment]
> 初始化项目国际化选择大部分中台都不需要国际化，每次都需要删除增加配置

而且现在是不是删除之后默认是英文，能不能配置删除后默认其他语言

**Comment by fangqibin** [comment]
> 初始化项目国际化选择大部分中台都不需要国际化，每次都需要删除增加配置

应该在初始化项目的时候可以选择不使用国际化，并可以指定语言

**Comment by TinsFox** [comment]
- 增加登录页面图片验证码(base64)
  对于中后台来说，很多后端都会返回一个base64的验证码进一步保证安全（虽然不知道有没有用）
- 增加网络请求拦截器/中间件最佳实践
- 文档示例语言能否使用JavaScript而不是Typescript，虽然应该推荐使用js，但是不是人人都能上手的呀，反过来会ts的那必定会js。然后在示例代码中能否写是在哪个文件中写的呢（这样我觉得会对不熟悉的人会更友好）
- 文档的示例及说明能否详细，文档调来跳去的，一会umi，一会又到插件文档，虽然Typescript是非常好用，可以解决很多问题，但是现在大部分都还是在用js的吧，希望文档中可以不要跳来跳去了，可以直接写出来，并且标注哪个文件可以么？给新手更多的友好。

**Comment by rooseve** [comment]
希望专门设置一些最佳实践之类的代码和文档，在基础层面“授人以渔”，引导中后台的开发。

Antd、AntdPro、Procomponents、Umi加在一起的学习成本是很高的，而业务开发往往有非常直接的目的，希望有相似的例子可以直接入手改（例子也不要过于集成，比如把细节都集成到ProXXX组件的内部，这样能学习的是只是组件的Api，不是写代码）

**Comment by cuibty** [comment]
问就是 多页签 multi-tab (手动狗头)

**Comment by iscmcloud** [comment]
支持国际化locale的数据从服务器端请求获取,类似"菜单的高级用法"一样

**Comment by Zach-Lu** [comment]
语雀富文本插件。支持自定义各种菜单。

**Comment by fanhualei** [comment]
> 语雀富文本插件

能给个 语雀富文本插件 的地址吗？

**Comment by TinsFox** [comment]
期望可以增加开源贡献指南，就需要遵循什么样的流程，单测编写等，有时候发现问题想要PR都不知道该怎么走

**Comment by drizzlesconsin** [comment]
**Multi Tab** 突然发现偏右大佬也+1了 😁 https://github.com/ant-design/ant-design-pro/issues/8656#issuecomment-872218115

![image](https://user-images.githubusercontent.com/69514654/128589470-3fb16582-e107-46f7-a1a2-6d0be8555104.png)

**Comment by drizzlesconsin** [comment]
**Multi Tab** 突然发现偏右大佬也+1了 😁 https://github.com/ant-design/ant-design-pro/issues/8656#issuecomment-872218115

![image](https://user-images.githubusercontent.com/69514654/128589550-beed9bd5-83fd-452a-a7fd-9288d843ddf0.png)

**Comment by xyzabc0004** [comment]
经过大半个月的时间,
终于把之前写的V4上的一个模块抄到了V5上.
由之前的ant design 全面改用ProComponents ,代码量确实少了不少。
跟V4最大的差异感觉是在Models层，晕了几天，Service的API变化也大，抄着抄着反倒更习惯了。
![image](https://user-images.githubusercontent.com/32530210/128878265-b504842d-3a99-4524-b777-e20211c64b73.png)

就是还有点小瑕疵，就是两个ProSelect ，数量做联动，没有抄出来。
其实这个联动运用的还很多。

各位老师有什么好的方法，可以指点下下。

**Comment by yuzhigang** [comment]
> 经过大半个月的时间,
> 终于把之前写的V4上的一个模块抄到了V5上.
> 由之前的ant design 全面改用ProComponents ,代码量确实少了不少。
> 跟V4最大的差异感觉是在Models层，晕了几天，Service的API变化也大，抄着抄着反倒更习惯了。
> ![image](https://user-images.githubusercontent.com/32530210/128878265-b504842d-3a99-4524-b777-e20211c64b73.png)
> 
> 就是还有点小瑕疵，就是两个ProSelect ，数量做联动，没有抄出来。
> 其实这个联动运用的还很多。
> 
> 各位老师有什么好的方法，可以指点下下。

说到这个联动，也耗费了好久时间。可以使用 ProFormDependency  组件。但有个简单的需求想了很久都没实现。第一个下拉框选择后，第二个下拉框自动显示第一个选项。

**Comment by xyzabc0004** [comment]
> > 经过大半个月的时间,
> > 终于把之前写的V4上的一个模块抄到了V5上.
> > 由之前的ant design 全面改用ProComponents ,代码量确实少了不少。
> > 跟V4最大的差异感觉是在Models层，晕了几天，Service的API变化也大，抄着抄着反倒更习惯了。
> > ![image](https://user-images.githubusercontent.com/32530210/128878265-b504842d-3a99-4524-b777-e20211c64b73.png)
> > 就是还有点小瑕疵，就是两个ProSelect ，数量做联动，没有抄出来。
> > 其实这个联动运用的还很多。
> > 各位老师有什么好的方法，可以指点下下。
> 
> 说到这个联动，也耗费了好久时间。可以使用 ProFormDependency 组件。但有个简单的需求想了很久都没实现。第一个下拉框选择后，第二个下拉框自动显示第一个选项。

休息个几天，后面再战

**Comment by langengel** [comment]
可以不报错吗？

**Comment by byan** [comment]
希望可以去掉测试相关的代码。只是前端界面而已，没那么多规矩~~

**Comment by xyzabc0004** [comment]
V5 + ProComponents 的学习，终于可以告一段落了！

**Comment by TinsFox** [comment]
> V5 + ProComponents 的学习，终于可以告一段落了！

我也在学习这个，可以分析一下你的学习历程吗？授人与渔  👀

**Comment by xyzabc0004** [comment]
我是在V5基础上一点一点做我要的东西。不会的，就在这里面叫  ：D，经高人指点，然后看代码，不断的敲啊敲...........
![1629189667(1)](https://user-images.githubusercontent.com/32530210/129693578-31eaaecf-8c65-492e-8c78-6583dfd89030.png)

**Comment by xyzabc0004** [comment]
从V4到V5，总共+起来，快有一个月时间了。

**Comment by fangqibin** [comment]
> 从V4到V5，总共+起来，快有一个月时间了。回想起来，累。

可以做一下学习过程总结吗，挺期待的。

**Comment by 569202812** [comment]
性能更好的表格，设计大量数据每个表格渲染的dom还挺多

**Comment by SilvaQ** [comment]
【配置分类  --- 讨论】
-----------------------

配置官方级别分类化是否科学？官方对此有没有考虑过？有何初衷或者考虑到的痛点？

虽然这种配置开发者自己控制就可以，但是antd系列所争取到的目标来看，这种交代清楚的配置应该官方首先开始规范化比较完美。

比如我这里以Proxxx组件库为例，其实table这种复杂的配置也应该可以的：

```javascript
const proTableProps={
        baseTable:{},  // 针对最基本table的，后面所有 配置是基于它扩展的
        proTable:{},  // 非table外扩展的protable专属的
        complexTable:{}, // treetable这种名字已经确定的独有配置
        otherKind:{}  ,// 暂先无法分类的，即将可能会归到其他分类的
}

const ProformProps={
          baseForm:{}
          proForm:{}
          modal:{}
          complexForm:{},
          otherKind:{}
}
```

对此想知道其他开发者们对这个想法怎么看？ 大佬们有何想法？

**Comment by fernandoxu** [comment]
我司现有项目还是V1，我想升级到V5会不会爆炸啊🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲

**Comment by lamorttu** [comment]
> 我是在V5基础上一点一点做我要的东西。不会的，就在这里面叫 ：D，经高人指点，然后看代码，不断的敲啊敲...........
> ![1629189667(1)](https://user-images.githubusercontent.com/32530210/129693578-31eaaecf-8c65-492e-8c78-6583dfd89030.png)

大佬可以分享下笔记嘛

**Comment by rudyzou** [comment]
1、多页签
2、更紧凑的一套设计？
3、基于pro直接出套页面设计器吧，/手动狗头

**Comment by chao325** [comment]
> 在前后端分离架构下，前端认证几乎是少不了，所以提交了一种最常用的认证方式（jwt token）。 #8756

大佬大佬~ @chenshuai2144  两位大佬~~

**Comment by cuibty** [comment]
> > > 在前后端分离架构下，前端认证几乎是少不了，所以提交了一种最常用的认证方式（jwt token）。 #8756
> > 
> > 
> > 大佬大佬~ @chenshuai2144 两位大佬~~
> 
> 如果使用 jwt token 认证可以参考这个实现，但认证方式不至这一种，antd pro 不能强加给用户可能不喜欢的方式（我理解，所以关了这个PR）。

antd pro 的用户喜欢 multi-tab （手动狗头）

**Comment by DreamPWJ** [comment]
多标签tabs   客户已经提了100次了

**Comment by liushan-github** [comment]
[https://juejin.cn/post/6993149143019421733](多页签实现方案，不过是在v2版本，可以作参考方案)

**Comment by chao325** [comment]
> 我是在V5基础上一点一点做我要的东西。不会的，就在这里面叫 ：D，经高人指点，然后看代码，不断的敲啊敲........... ![1629189667(1)](https://user-images.githubusercontent.com/32530210/129693578-31eaaecf-8c65-492e-8c78-6583dfd89030.png)

大佬~~能不能分享下笔记呀？！！！小弟先谢过

**Comment by liushan-github** [comment]
> 多标签tabs 客户已经提了100次了
多页签，支持多开参考方案，不过是v2版本
[](https://juejin.cn/post/6993149143019421733)

**Comment by liushan-github** [comment]
[多页签，支持多开参考方案，不过是v2版本](https://juejin.cn/post/6993149143019421733)

**Comment by StringKe** [comment]
请求支持 monorepo  https://nx.dev/react

**Comment by rong12345** [comment]
多页签+1

**Comment by pkaq** [comment]
不要风暴了 建议搜一下issue里提过多少次多页签了吧

**Comment by a97077088** [comment]
多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++

**Comment by tianlinzx** [comment]
多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++

**Comment by SilvaQ** [comment]
多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++
多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++

**Comment by leshalv** [comment]
ant design pro 可以建设在ice上呢？

**Comment by wuranxu** [comment]
😂可以新增个看板页面吗？类似jira，或者teambition那种的
我看antd也没有支持，如果pro或者ProComponents可以支持就好了~
估计也会有很多运用场景~

**Comment by liangxp** [comment]
引入第三方富文本编辑器的集成案例 PRO就完美了

**Comment by panhezeng** [comment]
如何升级到 umi4

**Comment by pkaq** [comment]
> 多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++ 多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++
react 18 都已经发布了

**Comment by chao325** [comment]
多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++ 多页签 multi-tab +++++++++++++++++++++++++++++++++++++++++
react 18 都已经发布了

**Comment by iscmcloud** [comment]
https://github.com/umijs/umi-next/projects/3#card-78480284

Umi这个解决实现了，Ant Design Pro的multi-tab是否有希望了？

**Comment by chenshuai2144** [comment]
[iscmcloud](https://github.com/iscmcloud) 是的，新版本 umi 会提供一个这样的功能

**Comment by iscmcloud** [comment]
> 

完美，期待中

**Comment by hyzx86** [comment]
列宽拖拽，选择列这种： https://vvbin.cn/next/#/comp/table/customerCell
![image](https://user-images.githubusercontent.com/15613121/173611851-82869c1c-081c-4922-8900-0ca581cb5f71.png)

树型表格，不是现在的展开~~ ，类似 https://vvbin.cn/next/#/comp/table/treeTable
多页签+1~
