### ISSUE TITLE
🧐[问题]反向代理前缀只能设置为api

### ISSUE THREAD

**Issue by dogscar** [ant-design/ant-design-pro#8762]
### 🧐 问题描述
反向代理前缀只能设置为api，设置为其他则报404

app.tsx中
export const request: RequestConfig = {
  errorHandler,
  **prefix: '/api',**
  requestInterceptors: [authHeaderInterceptor],
};

nginx反向代理
location **/api** {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Host              $http_host;
    proxy_set_header   X-Real-IP         $remote_addr;
}

加粗部分设置为"api"没问题，如果设置为其他，比如 abc、test等则报404

版本
"version": "5.0.0-beta.2",
"version": "5.0.0",

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/126039919-0037c867-27e9-4d8c-993a-bd3b85f25049.png)
我是直接在这里加的。

**Comment by dogscar** [comment]
> ![image](https://user-images.githubusercontent.com/32530210/126039919-0037c867-27e9-4d8c-993a-bd3b85f25049.png)
> 我是直接在这里加的。

我是生产环境，不是开发环境

**Comment by sangyuren** [comment]
pre 环境可以的，我试过。你改到这个环境就行了

**Comment by chenshuai2144** [comment]
他是个正则表达式，只要写的符合正则都是生效的
