### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by CODEOrz** [ant-design/ant-design-pro#8766]
### 🧐 问题描述

Error occured when i try to run my andt-pro project on MacBook.
I initialized the project on another Windows device. and now run it with no error when using the same node version(14.17.0)

My project repo: https://gitee.com/CODEOrz/jojo_web_pro

### 💻 示例代码

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }

**Comment by LinWanCen** [comment]
非常感谢，百度一直没找到原因，bing找到了这里，看了你的项目提交解决了我的问题：
https://gitee.com/CODEOrz/jojo_web_pro/commit/e68d892e9665762bd306b4a5aae023a7a5486845

config\config.dev.ts
```
  webpack5: {
    // lazyCompilation: {},
  },
```
```
  webpack5: false,
```

**Comment by LinWanCen** [comment]
非常感谢，百度一直没找到原因，bing找到了这里，看了你的项目提交解决了我的问题：
https://gitee.com/CODEOrz/jojo_web_pro/commit/e68d892e9665762bd306b4a5aae023a7a5486845

config\config.dev.ts
```
  webpack5: {
    // lazyCompilation: {},
  },
```
```
  webpack5: false,
```
