### ISSUE TITLE
🧐[问题] Got a "unknown property" webpack error when tried 'yarn start' command

### ISSUE THREAD

**Issue by CODEOrz** [ant-design/ant-design-pro#8767]
### 🧐 问题描述

Error occured when i try to run my antd-pro project on MacBook.
I initialized the project on another Windows device. and I can normally run it on my windows device when using the same node version(14.17.0)

My project repo: https://gitee.com/CODEOrz/jojo_web_pro

PS: this project use the **beta version** of antd-pro V5, should I upgrade the version and how should i conduct it ?

### 💻 示例代码

Error Info When tried 'yarn start' command:

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

configuration[0] has an unknown property 'experiments'. These properties are valid:
object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }

**Comment by xiongxiongjiang** [comment]
+1

**Comment by CODEOrz** [comment]
> +1
我用最新的umi新建了一个项目，然后把原项目的代码给迁移过去了。
之前的beta版跟正式的v5差距有点大

**Comment by fangqibin** [comment]
> > +1
> > 我用最新的umi新建了一个项目，然后把原项目的代码给迁移过去了。
> > 之前的beta版跟正式的v5差距有点大

差距在哪里，举个例子一下

**Comment by CODEOrz** [comment]
> > > +1
> > > 我用最新的umi新建了一个项目，然后把原项目的代码给迁移过去了。
> > > 之前的beta版跟正式的v5差距有点大
> 
> 差距在哪里，举个例子一下

主要是依赖不一样了，比如umi、umi-serve等一些依赖包有更新。
如果只有依赖包有更新，其实可以参考新版本的依赖去更新旧项目的依赖，理论上也能解决。

但这个问题在于，为什么老项目在macOS上报错。

**Comment by chenshuai2144** [comment]
是因为 webpack的版本不兼容导致的，所以要清空缓存并且重新安装依赖

**Comment by CODEOrz** [comment]
> 是因为 webpack的版本不兼容导致的，所以要清空缓存并且重新安装依赖

缓存清理肯定尝试过的。
关键是我这是新电脑，从远端仓库拉下来的代码，yarn install以后报错的，我觉得跟缓存可能关系不大。

**Comment by chenshuai2144** [comment]
那估计是lock锁了版本了

**Comment by xiongxiongjiang** [comment]
请问解决了吗~

**Comment by xiongxiongjiang** [comment]
- 把webpack卸载了： ```npm uninstall webpack  -g```
- 更新yarn：```npm install yarn@latest -g```
- 在项目中把node_modules删除
- 最后再yarn一下

试试。我的已经跑起来了

**Comment by CODEOrz** [comment]
> * npm install yarn@latest -g

我全局环境里根本就没装webpack…

**Comment by xiongxiongjiang** [comment]
> > * npm install yarn@latest -g
> 
> 我全局环境里根本就没装webpack…

当前项目呢

**Comment by CODEOrz** [comment]
> > > * npm install yarn@latest -g
> > 
> > 
> > 我全局环境里根本就没装webpack…
> 
> 当前项目呢

当前项目里也没有webpack的。webpack相关功能应该是是由项目里的 @umi/webpack-bundler 提供的

**Comment by Daph01** [comment]
我也遇到上面的webpack问题了，搞了半天才恢复，步骤如下：

1. 梳理config中config.dev.ts、config.ts 文件（与 master 保持一致）
2. 梳理package.json依赖（与 master 保持一致）
3. > yarn cache clean
4. 删除 node_modules
5. > yarn install
6. > yarn start

**Comment by CODEOrz** [comment]
> 我也遇到上面的webpack问题了，搞了半天才恢复，步骤如下：
> 
> 1. 梳理config中config.dev.ts、config.ts 文件（与 master 保持一致）
> 2. 梳理package.json依赖（与 master 保持一致）
> 3. > yarn cache clean
> 4. 删除 node_modules
> 5. > yarn install
> 6. > yarn start

是的，我发现报错原因是：config/config.dev.ts中有一个webpack5的空配置项 {}，需要将该属性设置为false。

**Comment by sundong212** [comment]
> > 我也遇到上面的webpack问题了，搞了半天才恢复，步骤如下：
> > 
> > 1. 梳理config中config.dev.ts、config.ts 文件（与 master 保持一致）
> > 2. 梳理package.json依赖（与 master 保持一致）
> > 3. > yarn cache clean
> > 4. 删除 node_modules
> > 5. > yarn install
> > 6. > yarn start
> 
> 是的，我发现报错原因是：config/config.dev.ts中有一个webpack5的空配置项 {}，需要将该属性设置为false。

亲测有效，谢谢！
