### ISSUE TITLE
🧐[问题]网络怎么了　Error occurred while trying to proxy request /api/login/account from localhost:8000 to https://preview.pro.ant.design 

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8768]
Error occurred while trying to proxy request /api/login/account from localhost:8000 to https://preview.pro.ant.design 
这个地址一直请求不过去。

**Comment by fangqibin** [comment]
你应该开启mock

**Comment by codedart2018** [comment]
> 你应该开启mock

dev start 都不自动跟着启动了的吗？

**Comment by fangqibin** [comment]
> > 你应该开启mock
> 
> dev start 都不自动跟着启动了的吗？

那应该就会请求到mock，默认项目是这样

**Comment by codedart2018** [comment]
> > > 你应该开启mock
> > 
> > 
> > dev start 都不自动跟着启动了的吗？
> 
> 那应该就会请求到mock，默认项目是这样

昨天突然就无法请求过去了。重新拉取的也是这样。我把电脑代理全关了，重启都没用。只能把接口转为请求自己的host了。

**Comment by chenshuai2144** [comment]
这个报错是网络不通导致的，是不是被防火墙拦住额

**Comment by qiannianjin** [comment]
我也遇到这个问题了，不知道咋搞

**Comment by meigesir** [comment]
可能是/etc/host文件中配置127.0.0.1映射有问题，我是把docker自动加上去的删掉可以了
