### ISSUE TITLE
🧐[问题]v5 js 版本的 routes 未来是放在config 文件里还是单独的一个routes 文件里

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8769]
### 🧐 问题描述
v5 js 版本的 routes 未来是放在config 文件里还是单独的一个routes 文件里，目前放在config文件里
![image](https://user-images.githubusercontent.com/53714134/126071731-23b12cde-1d5f-4f06-bbc3-1ee2e3f20a7e.png)

**Comment by kaoding** [comment]
现在V5是放在单独的文件内。
