### ISSUE TITLE
引入checkbox，select组件控制台报错 看看是啥原因🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8770]
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20655248/126097114-5671fbf8-1dce-4720-8298-66965521f70c.png)
![image](https://user-images.githubusercontent.com/20655248/126097186-b3f75566-8b7c-4d06-8b51-888996ab9ace.png)

**Comment by chenshuai2144** [comment]
删除 src/.umi，然后重新启动项目
