### ISSUE TITLE
🧐[基于ant-design-pro使用lerna创建monorepo项目最后运行报错]

### ISSUE THREAD

**Issue by zytqyb** [ant-design/ant-design-pro#8771]

**Comment by zytqyb** [comment]
关闭

**Comment by nthtrung09it** [comment]
@zytqyb hi, how did you solve that problem?

**Comment by zytqyb** [comment]
> @zytqyb hi, how did you solve that problem?Can run without opening mfsu,Can't compile, view [here](Can't compile, view here)

**Comment by zytqyb** [comment]
> @zytqyb嗨，你是如何解决这个问题的？



> @zytqyb嗨，你是如何解决这个问题的？

Can run without opening mfsu,Can't compile, view [无法编译](https://github.com/umijs/umi/issues/7332#issue-996867732)
