### ISSUE TITLE
🧐[问题] How to handle `default` case in `switch` in valueEnum of ProTable component?

### ISSUE THREAD

**Issue by kevinadhiguna** [ant-design/ant-design-pro#8772]
### 🧐 问题描述

Hello, I am using the ProTable component in Ant Design Pro. One of the columns is named `status`. The code looks like this : 

![image](https://user-images.githubusercontent.com/43397636/126109152-b8714150-3f42-4dd1-a964-558bfc71526a.png)

As the value of status is `U`, it displays `Unverified` just like this : 

![image](https://user-images.githubusercontent.com/43397636/126109304-f442fccc-654e-4824-a45c-06bd2a107cc0.png)

However, if I include `filters`, `onFilter`, and `valueEnum` in code : 

![image](https://user-images.githubusercontent.com/43397636/126109409-5512a8c6-0f72-4b41-aa8e-a23114e922b0.png)

It displays the `default` block in `switch` which is `No status yet...` : 

![image](https://user-images.githubusercontent.com/43397636/126109523-67d34824-2b3a-486b-836c-5b3fb03787aa.png)

Data and the records being shown are exactly same. Any help is appreciated...

**Comment by chenshuai2144** [comment]
You can enter the first parameter. If valueEnum is used, the first parameter will become reactNode, and you may need to use the second parameter to control it. 

`render:(dom,row)=>row.status`

**Comment by kevinadhiguna** [comment]
@chenshuai2144 Thank you very much! May I know where is it documented?

**Comment by chenshuai2144** [comment]
This has always been the case, there may not be an updated English version of the document
