### ISSUE TITLE
🧐[问题]splitMenus=true,混合模式，点击一级菜单，如何展开左侧菜单

### ISSUE THREAD

**Issue by wkuan** [ant-design/ant-design-pro#8773]
### 🧐 问题描述
splitMenus=true,混合模式，点击一级菜单，如何默认展开左侧的二级，三级菜单。
menu: {
            autoClose: false,
            defaultOpenAll: true,
        },
尝试这样配置，不行。

**Comment by chenshuai2144** [comment]
splitMenus 不支持 defaultOpenAll 的配置。 你可能要自定义一下 selectKeys  和 openKeys
