### ISSUE TITLE
V5 routes 配置layout:false 屏闪🐛[BUG]

### ISSUE THREAD

**Issue by Cooolyu** [ant-design/ant-design-pro#8775]
### 🐛 bug 描述
在routes.tsx中配置layout:false后，页面会先跳转到basicLayout再跳转到自定义layout，导致页面屏闪

### 🏞 期望结果

配置后能直接跳转到自定义页面

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- ant-design/pro-layout:^6.22.0
@chenshuai2144

**Comment by chenshuai2144** [comment]
来个 gif

**Comment by Cooolyu** [comment]
![1](https://user-images.githubusercontent.com/16718459/126259334-732db20e-0f6c-4a35-9dc5-1810735be85a.gif)
@chenshuai2144

**Comment by chenshuai2144** [comment]
你是在routes 中设置的把，他是异步的 😂

**Comment by Cooolyu** [comment]
那是否有其他方式可以优化这一问题呢？

**Comment by chenshuai2144** [comment]
我记个 todo，你要不要直接关掉layout？

**Comment by Cooolyu** [comment]
在app.tsx中添加
    pageTitleRender: false,
    headerRender:false,
    footerRender:false,
    menuRender:false,
    menuHeaderRender: false,
    menuExtraRender: false,
但是class ant-layout-content ant-pro-basicLayout-content中添加了24px的margin，如下图，这个怎么修改
![image](https://user-images.githubusercontent.com/16718459/126270461-291287b1-7ac0-4b9e-9faa-0a03df1473ff.png)
