### ISSUE TITLE
从服务器获取的菜单，如何点击才能显示对应的components，components组件路径如何写才能显示对应组件🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8776]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/20655248/126137821-6431ee5e-c0a9-4243-9b03-d145fff980d5.png)
![image](https://user-images.githubusercontent.com/20655248/126137924-ceb3368a-f9e3-41e2-9f96-48599f320b91.png)
![image](https://user-images.githubusercontent.com/20655248/126137988-fc816e20-b35a-4e24-9018-e477eb4c90e1.png)
![image](https://user-images.githubusercontent.com/20655248/126138697-5d439b54-2a9c-45b7-943f-a861439a9be1.png)

**Comment by chenshuai2144** [comment]
菜单和路由是分开的，菜单时 pathname，路由才有 components， 两者是根据 path 来结合的。

**Comment by qq1972474341** [comment]
同样遇到 如何解决的
