### ISSUE TITLE
ProLayout     vue版本改怎么写呢，这里面好像是react写法吧

### ISSUE THREAD

**Issue by caolaichao** [ant-design/ant-design-pro#8777]

**Comment by caolaichao** [comment]
方便能写个demo嘛。感谢

**Comment by caolaichao** [comment]
![image](https://user-images.githubusercontent.com/44855437/126140577-493ea2db-2f6a-4ef5-8845-91ce9ed527f6.png)

**Comment by chenshuai2144** [comment]
不支持的哦，用了很多react的 特性，改不过来。

https://pro.antdv.com/ 这里有 vue 版本
