### ISSUE TITLE
👑 [需求]Antd pro 是个中后台解决方案，但是中台也需要支持seo，有混合ssr、csr的实现吗？

### ISSUE THREAD

**Issue by wldos** [ant-design/ant-design-pro#8778]
### 🥰 需求描述
用Ant design pro 4.5实现的运营平台，需要支持cms(内容管理)，实现cms没有问题，但是客户端渲染没法seo了，能不能在umijs的基础上提供一些开箱即用的服务端渲染能力用于需要在互联网公开发布的信息，最好能有选择地设置渲染模式，系统管理后台和用户登陆、编辑表单等页面客户端渲染就可以。
现在的问题是，如果antd pro没法服务端渲染，或者实现起来很麻烦，就只能使用别的脚手架实现cms，这样另一个脚手架和antd pro 关系尴尬。

**Comment by wldos** [comment]
> ### 🥰 需求描述
> 用Ant design pro 4.5实现的运营平台，需要支持cms(内容管理)，实现cms没有问题，但是客户端渲染没法seo了，能不能在umijs的基础上提供一些开箱即用的服务端渲染能力用于需要在互联网公开发布的信息，最好能有选择地设置渲染模式，系统管理后台和用户登陆、编辑表单等页面客户端渲染就可以。
> 现在的问题是，如果antd pro没法服务端渲染，或者实现起来很麻烦，就只能使用别的脚手架实现cms，这样另一个脚手架和antd pro 关系尴尬。
> 
> ### 🧐 解决方案
> ### 🚑 其他信息
虽然umijs支持ssr服务端渲染和预渲染，但是悲催的是，Antd pro不支持，开启后直接报错，因为Antd Pro在render/return中用了大量的dom/bom对象，比如location、window、document。

**Comment by chenshuai2144** [comment]
mock 一下 location、window、document 把，ssr 还是很难得。

而且中后台ssr 没什么意义。加载快不是中后台的核心竞争力

**Comment by CREATE-AI** [comment]
中后台也需要，至少中后台一般都会集成个CMS模块，如果没有SSR，还是感觉很大的缺陷
