### ISSUE TITLE
菜单如何隐藏子菜单直接点击父菜单进入

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#878]
![image](https://user-images.githubusercontent.com/183884/35742034-4feb8f92-0874-11e8-89a2-90a5a16ac1f0.png)

实现 点击搜索列表 出现内容，而不出现子菜单
![image](https://user-images.githubusercontent.com/183884/35741947-110596d8-0874-11e8-8d7a-b9c0b0d72fae.png)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35765142-1d78ac18-08f9-11e8-8169-ba7e487dfac4.png)

这样

**Comment by Lzw2016** [comment]
![tim 20180203162138](https://user-images.githubusercontent.com/19291563/35765454-f46088fe-08fe-11e8-837d-9d6e647cb4c6.png)
这个需求怎么满足？

**Comment by chenshuai2144** [comment]
router设置里面也可以配置name

**Comment by Lzw2016** [comment]
![tim 20180203163319](https://user-images.githubusercontent.com/19291563/35765510-00156b5a-0900-11e8-87ac-695f671a0175.png)
![tim 20180203163325](https://user-images.githubusercontent.com/19291563/35765511-01c54376-0900-11e8-827a-857215343788.png)
![tim 20180203163329](https://user-images.githubusercontent.com/19291563/35765512-03535c0a-0900-11e8-9c80-70575c63ba76.png)
页面显示有问题 不应该是 ‘../routes/Dashboard/Workplace’  应该是 ‘../routes/List/CardList’

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/router-and-nav-cn 
看看文档
最多支持两级目录

**Comment by Lzw2016** [comment]
![tim 20180203170707](https://user-images.githubusercontent.com/19291563/35765714-c0332de2-0904-11e8-8fe9-2bcc90db463c.png)

原来“最多支持两级目录”呀，谢谢

**Comment by WuJiY** [comment]
![image](https://user-images.githubusercontent.com/183884/35767150-85996ac6-0921-11e8-8b55-c2c96741f44b.png)


点击  搜索列表  怎么默认显示的是文章的内容呢 @chenshuai2144 ，现在菜单是隐藏了

**Comment by WuJiY** [comment]
好像是要menu 菜单放在children下 隐藏起来才会重定向，如果放在同级不会重定向。

**Comment by Lzw2016** [comment]
这 menu 和 router 真不好用，换 `iview admin`吧

**Comment by Lzw2016** [comment]
`iview admin` 地址 https://iview.github.io/iview-admin/#/login

**Comment by Lzw2016** [comment]
@WuJiY  github 地址 https://github.com/iview/iview-admin

**Comment by WuJiY** [comment]
@Lzw2016 我来看看

**Comment by WuJiY** [comment]
vue的 暂时没去研究

**Comment by WuJiY** [comment]
@chenshuai2144 这样实现了，加个你上面说的跳转是吧，是这样的吧
![image](https://user-images.githubusercontent.com/183884/35774740-debd97c6-09b2-11e8-86df-58136ef85af8.png)

**Comment by WuJiY** [comment]
另外 动态切换pageheader的content 这样写的。是最优方案吗？
![image](https://user-images.githubusercontent.com/183884/35774745-287ee752-09b3-11e8-9a19-e00464df243f.png)

**Comment by chenshuai2144** [comment]
实现就很好了

**Comment by adhope** [comment]
> https://pro.ant.design/docs/router-and-nav-cn
> 看看文档
> 最多支持两级目录

并没有找到hide* 属性

**Comment by chenshuai2144** [comment]
@adhope  https://procomponents.ant.design/components/layout#menudataitem

文档有点过时了
