### ISSUE TITLE
新版本的图形编辑模块好像有点问题🧐[问题]

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8780]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/53714134/126177311-007b79e1-32c9-491b-a48d-08d5dbf78102.png)

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/53714134/126178480-970cabbc-5846-44a3-a3fe-251fdc52e957.png)

**Comment by chenshuai2144** [comment]
看起来是像是 mfsu出问题了，关掉试试

这两个组件库都停止维护了，错误了其实没法修
