### ISSUE TITLE
如何在ModalForm内实现行内布局🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8782]
### 📷 复现步骤

ModalFom内这样写无法实现行内布局，而且报错 发现ModalFrom跟QueryFilter不能嵌套写，而且无法实现行内布局

![image](https://user-images.githubusercontent.com/20655248/126281312-f79d25f9-e74c-4de3-911d-00543fcad099.png)
![image](https://user-images.githubusercontent.com/20655248/126281470-affb94ec-d508-40f0-8f34-4ac695e85ed4.png)
### 🏞 期望结果

![image](https://user-images.githubusercontent.com/20655248/126281599-5c79aa5d-694f-439b-996d-92ecf145ecf3.png)
期望在ModalForm内实现这样行内布局
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个是 form 的 layout 配置
