### ISSUE TITLE
🐛[BUG]新建项目.无法运行

### ISSUE THREAD

**Issue by Baskittle** [ant-design/ant-design-pro#8784]
按照文档...
新建目录
npm create umi
npm install
npm run

然后居然报错..真有你的啊..
搜了一堆说是 MFSU 的问题..于是关掉了..
然后..webpack 99%..继续报错.....

colorette 报错....

**Comment by chenshuai2144** [comment]
来个截图

**Comment by loshafee** [comment]
> 来个截图
![Dingtalk_20210721112039](https://user-images.githubusercontent.com/12297373/126425523-77336cb0-1331-47b7-a18e-3a93f2738b72.jpg)
![Dingtalk_20210721112205](https://user-images.githubusercontent.com/12297373/126425768-7f8dc825-9954-47a7-83f5-0fd26629559e.jpg)

刚使用脚手架初始化的项目
ant-design-pro -> simple

**Comment by chenshuai2144** [comment]
css 全乱了呀，你是不是依赖没装全？

**Comment by joysunmm** [comment]
我也是这样 样式不生效

**Comment by loshafee** [comment]
> css 全乱了呀，你是不是依赖没装全？

不是，刚使用脚手架初始化的项目
ant-design-pro -> simple

去掉配置MFSU又正常了

**Comment by chenshuai2144** [comment]
mfsu 还是很有用的，改了什么吗
