### ISSUE TITLE
ProFormText fieldProps同时设置了2个属性 后面那个属性没生效 🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8785]
### 🐛 bug 描述

ProFormText想要设置成只能输入数字的input框，然后限制输入11位，发现用fieldProps之后 type: 'number'生效了， maxLength没生效
![image](https://user-images.githubusercontent.com/20655248/126423832-6bac302d-ae35-4576-b4d2-f57580ffe54b.png)
![image](https://user-images.githubusercontent.com/20655248/126424055-45dd62ee-a5b4-4186-9a90-0e89c4f08e02.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
为何 TextArea 受控时，value 可以超过 maxLength？#
受控时，组件应该按照受控内容展示。以防止在表单组件内使用时显示值和提交值不同的问题。

**Comment by chenshuai2144** [comment]
maxLength 是html的属性，不是react的，你控制不了的
