### ISSUE TITLE
🧐[问题]alibb库引入后如何使用

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#8786]
### 🧐 问题描述
您好，在defaultsettings中添加了字体图标的地址，在页面中该如何使用呀。
![image](https://user-images.githubusercontent.com/51156342/126425377-ae488c8d-b95e-4867-9f51-d2b4fd18c308.png)
有具体的例子么，在官网上没找到。

**Comment by chenshuai2144** [comment]
如何代码中使用
https://ant.design/components/icon-cn/#components-icon-demo-iconfont


如何layout 中使用

https://procomponents.ant.design/components/layout#%E4%BD%BF%E7%94%A8-iconfont

**Comment by YC725968** [comment]
感谢！

**Comment by nhdeng** [comment]
> 除了cdn引入字体js以外，本地的iconfont 如何引入？可以说明一下吗？

内网需要的话，可以从iconfont官网上将iconfont.js下载下来放在public/fonts目录下，然后设置iconfontUrl: '/fonts/iconfont.js'
