### ISSUE TITLE
🧐[问题]谁有好用的角色授权呀，我觉得我这个不是很科学、

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8789]
[http://oss.jibei.ycoto.cn/images/github/WechatIMG1298.png](url)
![角色授权](http://oss.jibei.ycoto.cn/images/github/WechatIMG1298.png)
比如我在基础配置下面新添加了一个节点，由于Tree组件原先的值全被保存了的。所以默认新增的加的节点也会被选中。但实际上是没有选中的。所以想问问大家的怎么做的，秀秀代码看看呗！

**Comment by kaoding** [comment]
你这个是业务问题，权限不只是界面上按tree组件的方式来组织，我看你这个在后面还要做权限组。
