### ISSUE TITLE
点击编辑显示弹窗如何将record数据传递到ModalForm的request内🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8791]
### 🐛 bug 描述

编辑要显示弹窗，将table一行record的数据传递到modalForm的组件内给表单赋值，要将table的record对象的每个值传递到ModalForm的每个表单内赋值 要如何做
![image](https://user-images.githubusercontent.com/20655248/126493944-aa194432-c932-473c-b946-74f80b4b3114.png)
![image](https://user-images.githubusercontent.com/20655248/126493767-a0a6e29b-f576-4991-b298-d0392b0d3d97.png)
![image](https://user-images.githubusercontent.com/20655248/126493665-6ddf82bb-b479-4e71-a7fe-867ae4c31b97.png)
![image](https://user-images.githubusercontent.com/20655248/126493709-c9f68b8a-523a-4f4d-bf16-74fddda30d9a.png)
![image](https://user-images.githubusercontent.com/20655248/126493900-56d3960b-fd5f-42d0-92c8-15bb24087a79.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

<!--
如截图等其他信息可以贴在这里
--

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/88950d264e2a9cabc0e42e2b26e964e35feb2625/src/pages/TableList/components/UpdateForm.tsx

这里有个 demo，你看看这里，没必要用 request 的

**Comment by lovehebe330** [comment]
> https://github.com/ant-design/ant-design-pro/blob/88950d264e2a9cabc0e42e2b26e964e35feb2625/src/pages/TableList/components/UpdateForm.tsx
> 
> 这里有个 demo，你看看这里，没必要用 request 的

![image](https://user-images.githubusercontent.com/20655248/126601531-a52634a4-5da5-48eb-8a42-0fb09b8e4954.png)
![image](https://user-images.githubusercontent.com/20655248/126601688-c4609b23-1135-44ab-aa66-e6fd59e6ac99.png)
但是我用ModalForm的initialValues给文本框赋初始值 发现没法用props.values.userName给文本框赋值 ，而props.values.userName在外层打印是有值的，而且给initialValues随意赋值个字符串居然有效果，这是为啥？

**Comment by chenshuai2144** [comment]
`initialValues&& <ModalForm/>`

这样设置，initialValues 只有第一次有效
