### ISSUE TITLE
🧐[问题] How to use `DatePicker` inside `Form.Item` with default/initial value ?

### ISSUE THREAD

**Issue by kevinadhiguna** [ant-design/ant-design-pro#8793]
### 🧐 问题描述

Hi, I have a `Form` component in which I have `Form.Item` components. In one of the `Form.Item`, I use `DatePicker` component but I also assign `initialValues` in `Form` component.

This is the `initialValues` in `Form` :

![gambar](https://user-images.githubusercontent.com/43397636/126532174-59856b84-b7da-4de8-afb2-2728ea133376.png)

This code caused the error : 

![gambar](https://user-images.githubusercontent.com/43397636/126532036-413d9a9a-2379-48ed-8f72-7f313dc1e520.png)

The errors were : 

![gambar](https://user-images.githubusercontent.com/43397636/126532400-8b1d563b-0a55-4589-95ea-95a6b6cf4f2b.png)

However if I put `DatePicker` outside of the `Form.Item` like this : 

![gambar](https://user-images.githubusercontent.com/43397636/126532756-22b63ef6-ae02-4512-aff5-52b77c02338e.png)

That did not give me errors.

I found discussion about this [here](https://stackoverflow.com/questions/64527820/antd-datepicker-date-clone-is-not-a-function) but I did not get the point.

My question is how to use a `DatePicker` component inside `Form.Item` with default/initial value assigned in it?
Any help is much appreciated!

**Comment by chenshuai2144** [comment]
You need to modify the value to moment.

or try use ProForm, it will auto modify.

https://procomponents.ant.design/
