### ISSUE TITLE
删除国际化后导入antd的Form组件后出错🐛[BUG]

### ISSUE THREAD

**Issue by sskcal** [ant-design/ant-design-pro#8794]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/19920998/126587098-2dc26b47-8bdd-43fc-a505-7d024bd90357.png)

npm run i18n-remove

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by sskcal** [comment]
antd pro 5.0.0

**Comment by chenshuai2144** [comment]
mfsu 的错误吧，删除.umi 重启下试试
