### ISSUE TITLE
🧐[小白问题]v2如何使用dark mode

### ISSUE THREAD

**Issue by InVinCiblezz** [ant-design/ant-design-pro#8797]
### 🧐 问题描述
我看到了v5版本可以在config.ts下配置
` antd: {
    dark: true,
  },`来使用dark mode. 我没有使用webpack，使用的是create react app的ts版。

这是安装ant-design-pro的目录
![image](https://user-images.githubusercontent.com/18670530/126727690-0b08bfb2-ef78-43d4-a618-d995cbce2f85.png)
请问我要怎么使用dark mode呢？我尝试了在index.tsx下 `import '@ant-design/dark-theme';`但是无效。 谢谢！

这是我整个项目的结构
![image](https://user-images.githubusercontent.com/18670530/126727836-2ecd3f4f-1c33-40a0-928e-da604106b7a1.png)
### 🚑 其他信息
` "@ant-design/dark-theme": "^2.0.2",
    "@ant-design/pro-table": "^2.43.6",`

**Comment by InVinCiblezz** [comment]
我使用antd的方法全局引入了dark.css，可是ProTable的headerTitle的颜色仍然是黑色

**Comment by chenshuai2144** [comment]
这个代码写的不好，是不支持的，你可以要强制覆盖下样式了
