### ISSUE TITLE
👑 [需求]Upload组件图片会重复加载

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-pro#8798]
### 🥰 需求描述
Upload 加载上传图片设置newFileList的时候，请求blob数据的时候会把之前的图片又重新请求了一遍。
有没有唯一标识之类的。

**Comment by chenshuai2144** [comment]
展开描述一下，我有点没听懂

**Comment by fangqibin** [comment]
> 展开描述一下，我有点没听懂

listType是picture的时候，会加载上传的图片blob作为列表展示。当我FileList再上传的时候，上传列表刷新，会导致原来已经上传的图片会再重新加载图片资源。（上传是没有问题的）。

**Comment by chenshuai2144** [comment]
听起来是正常的，毕竟没法保证图片是一样的
