### ISSUE TITLE
🐛[BUG] 登录成功后，依然可以进入登录页，并无跳转

### ISSUE THREAD

**Issue by himanhimao** [ant-design/ant-design-pro#8801]
正常逻辑是登录成功后，再次访问登录页讲跳转到dashboard 页面，但是登录页面依然能访问。

**Comment by wangyongsong** [comment]
临时想到的两个方法，仅供参考。
### 方案一：
在登录页面做一个判断，如果存在`initialState?.currentUse&&token`自动跳转回原来的页面 
### 方案二：
在models里的global.ts，通过`subscriptions`监听路由如果是跳转到`/user/login`判断session是否存在token，如果存在token，则自动跳转回来

**Comment by chenshuai2144** [comment]
更新一下依赖，可能 initialState 没有更新完毕就跳转了，我们加了一个await
