### ISSUE TITLE
发出来之前自己先测试一下，开头就进不去🐛[BUG]

### ISSUE THREAD

**Issue by chunjiu** [ant-design/ant-design-pro#8802]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by tanghui28** [comment]
+1  辣鸡阿里

**Comment by Pang-BaiXu** [comment]
+1，希望开发组在发版前还是多做做集成测试吧，文档更发版内容都对不上，照着文档来根本及跑不起来，而且文档写的是真乱啊

**Comment by chenshuai2144** [comment]
有没有人能描述下问题？

**Comment by pxim** [comment]
开始进不去，是因为第一次要构建很久，起码10几分钟，第三次 start，才正常跳转到 login界面

**Comment by chenshuai2144** [comment]
来个gif，或者搞个测试项目详细描述一下。@pxim 

这个发泄情绪的issue 我先关了
