### ISSUE TITLE
Why need an extra fetchUser call in BasicLayout when SecurityLayout is calling already

### ISSUE THREAD

**Issue by TheStarkster** [ant-design/ant-design-pro#8804]
### 🐛 bug 描述
I see security layout if the parent of basic layout and in security layout user/fetchCurrent dispatch is called to check user is logged in or not yada yada! but the issue is why we are calling that effect again in basic layout see [here](https://github.com/ant-design/ant-design-pro/blob/v4/src/layouts/BasicLayout.tsx#L95). so why call that dispatch twice assuming user is logged in

and also please convert the template to english from chinese PLEASE!

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
you can  use  initalvalues
https://pro.ant.design/zh-CN/docs/simple-model
