### ISSUE TITLE
🧐[问题] 你好  我下载的5.0.0 没layout 和models 

### ISSUE THREAD

**Issue by huangtaoSyn** [ant-design/ant-design-pro#8805]
### 🧐 问题描述

你好 对于5.0.0 没有layout和models 请问如何下载指定版本

**Comment by chenminghui-git** [comment]
我的也是

**Comment by huangtaoSyn** [comment]
> 我的也是

现在不管了，版本变化太大，5.0.0引入useregister都没用，defineconfig我也找到是哪个文件将其映射为配置文件，甚至原先的basiclayout securitylaout userlayout也不知道在哪里加载的。

**Comment by chenshuai2144** [comment]
layout 和models 被替换成了 layout-plugin 和 简易数据流

https://pro.ant.design/zh-CN/docs/overview

![image](https://user-images.githubusercontent.com/8186664/127101727-fb389386-e0d4-44fa-a0ae-f74b74ca7747.png)

**Comment by huangtaoSyn** [comment]
> layout 和models 被替换成了 layout-plugin 和 简易数据流
> 
> https://pro.ant.design/zh-CN/docs/overview
> 
> ![image](https://user-images.githubusercontent.com/8186664/127101727-fb389386-e0d4-44fa-a0ae-f74b74ca7747.png)

好的 谢谢啊，请问你知不知道route.js  中的definconfig在哪个文件映射的啊，一直招不到，

**Comment by chenshuai2144** [comment]
definconfig 在 config 中配置了一个routers

**Comment by huangtaoSyn** [comment]
> definconfig 在 config 中配置了一个routers

谢谢啦

**Comment by huangtaoSyn** [comment]
> definconfig 在 config 中配置了一个routers

在问一下啊，这里的routers将其转换为Route组件在哪个文件中啊

**Comment by chenshuai2144** [comment]
是umi做的，你不能控制
