### ISSUE TITLE
🧐[问题]proTable如何根据request返回的数据自动生成valueEnum

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#8806]
### 🧐 问题描述
如何让valueEnum根据后端数据自动生成
```
  const columns: ProColumns<API.ObjectItem>[] = [
    {
      title: "分类", 
      dataIndex: "category",
      filters: true,
      onFilter: true,
      valueEnum: {
        all: { text: '全部', status: 'Default' },
        close: { text: '关闭', status: 'Default' },
        running: { text: '运行中', status: 'Processing' },
        online: { text: '已上线', status: 'Success' },
        error: { text: '异常', status: 'Error' },
      },
    },
```

**Comment by huangtaoSyn** [comment]
你好请问 你工程如何clone下的模板存在layout和models的啊，我这只能使用master 想clone指定版本的工程如何解决啊

**Comment by huangtaoSyn** [comment]
你的问题我不知道有没有包，没有的话可以使用map.reducer映射出这样的结构

**Comment by jinhgg** [comment]
> 你好请问 你工程如何clone下的模板存在layout和models的啊，我这只能使用master 想clone指定版本的工程如何解决啊

先clone下来再切换到指定版本

**Comment by huangtaoSyn** [comment]
> > 你好请问 你工程如何clone下的模板存在layout和models的啊，我这只能使用master 想clone指定版本的工程如何解决啊
> 
> 先clone下来再切换到指定版本
好的谢谢啊

**Comment by chenshuai2144** [comment]
列配置中也有个request的。

**Comment by huangtaoSyn** [comment]
> 列配置中也有个request的。
> https://procomponents.ant.design/components/schema#%E8%BF%9C%E7%A8%8B%E6%95%B0%E6%8D%AE

谢谢啊 三点中还在回复，
