### ISSUE TITLE
使用ModalForm的initialValues给文本框赋初始值失败的问题🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8809]
### 🐛 bug 描述

用ModalForm的initialValues给文本框赋初始值 发现没法用props.values.userName给文本框赋值 ，而props.values.userName在外层打印是有值的，而且给initialValues随意赋值个字符串居然有效果，这是为啥？
![image](https://user-images.githubusercontent.com/20655248/126602125-5b2e2ef7-a3a8-44ef-823f-5b42ce161e7a.png)
![image](https://user-images.githubusercontent.com/20655248/126601688-c4609b23-1135-44ab-aa66-e6fd59e6ac99.png)
如果用ProFormText的initialValue赋值也是有效果的
![image](https://user-images.githubusercontent.com/20655248/126925820-a5986b70-fb49-49da-8e2f-bffbf8e9f752.png)
![image](https://user-images.githubusercontent.com/20655248/126925873-d25c5d26-6b38-4c34-8205-2677257aac75.png)
为什么用ModalForm的initialValues属性就复制失败了呢?
![image](https://user-images.githubusercontent.com/20655248/126925961-b29a93ad-f420-41cb-8c1f-350456897de7.png)
![image](https://user-images.githubusercontent.com/20655248/126926011-a0ab675e-5b09-4b54-a170-a98b2d67cfef.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这种一般都是渲染时机的问题 在props.value不存在的时候直接返回一个null,应该就可以了

**Comment by wangyongsong** [comment]
我一般喜欢直接传一个对象使用。
![image](https://user-images.githubusercontent.com/58172091/127253874-01b298a6-0c03-42e6-a208-4447a3d98def.png)
![image](https://user-images.githubusercontent.com/58172091/127253903-f5c5bdf8-876b-483d-b949-f6ae564edc19.png)

**Comment by wangyongsong** [comment]
也可能你这个initialValues是动态的。如果是这样的情况 我更推荐用useEffect依赖visible，如果visible为true，则form.setFieldsValue(values)

**Comment by lovehebe330** [comment]
![image](https://user-images.githubusercontent.com/20655248/127260813-81467beb-5312-407c-b31e-0827dcdfed25.png)

实在太奇怪了 在ProFormText内用initialValue赋值动态属性可以， 在ModalForm的initialValues赋值动态属性就不行，赋值静态的就可以

**Comment by wangyongsong** [comment]
> 实在太奇怪了 在ProFormText内用initialValue赋值动态属性可以， 在ModalForm的initialValues赋值动态属性就不行，赋值静态的就可以

```tsx
  useEffect(() => {
    if (visible) form.setFieldsValue({ ...values });
  }, [visible]);
```
先用这个方法临时解决下吧。

**Comment by wangyongsong** [comment]
> > 实在太奇怪了 在ProFormText内用initialValue赋值动态属性可以， 在ModalForm的initialValues赋值动态属性就不行，赋值静态的就可以
> 
> ```tsx
>   useEffect(() => {
>     if (visible) form.setFieldsValue({ ...values });
>   }, [visible]);
> ```
> 
确实有这个问题，我上次也发现了。最后用这个方法临时解决了。

**Comment by chenshuai2144** [comment]
`initialValues && <ModalForm/>`

**Comment by wangyongsong** [comment]
> `initialValues && <ModalForm/>`

牛啊！没想到这种方法

**Comment by lovehebe330** [comment]
> 也可能你这个initialValues是动态的。如果是这样的情况 我更推荐用useEffect依赖visible，如果visible为true，则form.setFieldsValue(values)



> ```tsx
> useEffect(() => {
>     if (visible) form.setFieldsValue({ ...values });
>   }, [visible]);
> ```

这种方法是可以，刚按照chenshuai同学说的这样子initialValues && <ModalForm/> 复制成功了而且其实更简单觉得
![image](https://user-images.githubusercontent.com/20655248/127270054-aad3d24a-7578-457f-a57e-6289eb19009d.png)

**Comment by chenshuai2144** [comment]
initial 就是只有第一次 render 生效的意思

**Comment by wangyongsong** [comment]
> initial 就是只有第一次 render 生效的意思

猜测：是不是因为在进入页面的时候`ModalForm`实际上已经渲染了，只不过是`visible`是`false`，而此时`initialValues`已经渲染成功，这就导致后期更改`initialValues`无效。
