### ISSUE TITLE
🐛[BUG] 访问PATH/user/xxxxxxs 无法预期进入404页面

### ISSUE THREAD

**Issue by himanhimao** [ant-design/ant-design-pro#8813]
bug真多啊 。。。。

**Comment by chenshuai2144** [comment]
详细说明一下？

**Comment by himanhimao** [comment]
就是随意输入一个URL 并没有跳到404页面

**Comment by wayneee188** [comment]
4.0 的写法跟以前好像不同，匹配的时候像是从上到下依次匹配，如果要匹配到/user/xxx这个路由，可以试试这个写法。
`export default [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: 'login',
        component: './Login/Login',
      },
      {
        component: './404',
      },
    ],
  }`

解释一下，个人理解，假设要匹配/user/test，要么先会进入/user/，再去找/user下的子路由，从上到下，那么最后查到{component: './404'}会命中。
