### ISSUE TITLE
怎么把不同路由网页标题后面的-Ant Design Pro去掉🧐[问题]

### ISSUE THREAD

**Issue by CoderDgx** [ant-design/ant-design-pro#8814]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32624424/127110872-b14995b0-b15f-4c00-99c5-fb31014a981e.png)

**Comment by iainlau** [comment]
https://github.com/ant-design/ant-design-pro/blob/73d493098f3e1ddd6298e2bd2d4b557e24fe642d/config/defaultSettings.ts#L15
