### ISSUE TITLE
🧐[问题]demo分支代码在哪里

### ISSUE THREAD

**Issue by langfanZcf** [ant-design/ant-design-pro#8815]
### 🧐 问题描述

看到样例代码：https://preview.pro.ant.design/dashboard/analysis。
想问下这个代码的分支在哪里想学习一下

**Comment by chenshuai2144** [comment]
? 🚀 Do you need all the blocks or a simple scaffold? (Use arrow keys)
❯ simple
  complete

选 第二项

**Comment by jiangzhangxiang** [comment]
> ? 🚀 Do you need all the blocks or a simple scaffold? (Use arrow keys) ❯ simple complete
> 
> 选 第二项 complete

demo 的历史版本 4.2.X 还能拉吗 这边是哪个git分支呢

**Comment by chenshuai2144** [comment]
4.2 要用git 找tag了。

**Comment by jiangzhangxiang** [comment]
> 4.2 要用git 找tag了。

找到的 都是 simple 的4.2 没找到 complete

**Comment by chenshuai2144** [comment]
complete 已经没了

**Comment by jiangzhangxiang** [comment]
> complete 已经没了

好的 谢谢👍
