### ISSUE TITLE
🧐[问题]记住密码之后输入框有背景色

### ISSUE THREAD

**Issue by junhaideng** [ant-design/ant-design-pro#8816]
### 🧐 问题描述

首先先登录到界面中，然后弹出一个记住密码的框，点击记住密码，重新回到登录界面，输入框背后有一个淡蓝色的背景

### 💻 示例代码

无

### 🚑 其他信息

<img src="https://user-images.githubusercontent.com/47896650/127183181-b4d7ecf7-c710-4f88-83c7-926de720809f.png" width=400>

**Comment by chenshuai2144** [comment]
fixed
