### ISSUE TITLE
🐛[BUG]Error: build failed 使用最新pro报错啦～

### ISSUE THREAD

**Issue by fei199225** [ant-design/ant-design-pro#8818]
### 🐛 bug 描述

2021年7月27日开始用推荐流程使用pro，npm run start时会报错

### 📷 复现步骤

npx create-umi myapp
>ant-design-pro
>TypeScript
>complete
cd myapp 
npm install
npm run start

### 🏞 期望结果

27日开始，npm run start会报错，即使按照推荐流程重新启新的项目也是一样的现象，27日前是没有这样的问题的，想知道是做了什么升级或者调整导致的么，要怎么解决呢？

### 💻 复现代码

用推荐流程即可复现

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本: [3.5.14]
- 浏览器环境
- 开发环境 [mac OS or win]

### 🚑 其他信息

![21627436963_ pic_hd](https://user-images.githubusercontent.com/11814691/127251735-72f35d97-62af-4399-95fb-c69bc15c5ac0.jpg)

**Comment by qiangxue1206** [comment]
同问

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/ant-design-pro/issues/8820
