### ISSUE TITLE
V5下 引用 useModel（“namespace”） ，namespace下是个波浪线

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8819]
![image](https://user-images.githubusercontent.com/32530210/127258089-0af74ca1-031a-46b9-b670-d875aa52d5d3.png)

我还是上图吧，上图可能更明了些。

图中message打印出来是正确的。
只是namespace下是个波浪线，点击他也到不了model文件

不知道VS是什么没有安装什么，还请大侠们指点下。

**Comment by wangyongsong** [comment]
useModel的引入正确吗？
详细参考文档：https://umijs.org/zh-CN/plugins/plugin-model#usemodel

**Comment by chenshuai2144** [comment]
重启 ts 解决你的烦恼

**Comment by xyzabc0004** [comment]
果不其然！

**Comment by xyzabc0004** [comment]
> 波浪线提示的错误是什么
> 详细参考文档：https://umijs.org/zh-CN/plugins/plugin-model#usemodel

我还是按这个来！
