### ISSUE TITLE
以独立方式安装ant-design-pro，设置了@icon-url，仍然会加载alicdn的字体

### ISSUE THREAD

**Issue by lyingd** [ant-design/ant-design-pro#882]
以独立方式安装ant-design-pro，在theme.js里设置了@icon-url，存在以下现象：
1、alicdn的字体被优先加载
2、如果alicdn的字体加载失败，则加载本地字体，如果成功，则不不加载本地字体

如果是在内网环境下，会导致图标有较长一段时间（10秒左右）显示小方块，需等alicdn的连接失败后，才会开始加载本地字体，很影响体验。
![](https://github.com/lyingd/antd-pro-demo/blob/master/tests/iconfont-network.png?raw=true)

demo：
https://github.com/lyingd/antd-pro-demo

非独立版无此问题。

**Comment by chenshuai2144** [comment]
试着把ant-design的加载也搞掉。

**Comment by lyingd** [comment]
请问要怎么搞掉？我看了ant-design，也是这么设置theme.js

**Comment by zlhy** [comment]
我这没有问题，^_^

**Comment by zlhy** [comment]
@lyingd 
我这么配置的
// 'primary-color': '#10e99b',
  'icon-url': '"/antd-iconfont/iconfont"',
  'card-actions-background': '#f5f8fa',

**Comment by afc163** [comment]
最好给出重现的完整代码仓库。

**Comment by lyingd** [comment]
@afc163 问题里已给出，是这个： https://github.com/lyingd/antd-pro-demo

**Comment by afc163** [comment]
@chenshuai2144 @ddcat1115 

我们需要提供 `ant-design-pro/dist/ant-design-pro.less`。

https://github.com/lyingd/antd-pro-demo/blob/master/src/index.js#L1

**Comment by DuduStyle** [comment]
出现了同样的问题，不知怎么解决

**Comment by chenshuai2144** [comment]
这个我在搞了

**Comment by chenshuai2144** [comment]
cc https://github.com/ant-design/ant-design-pro-site/pull/153

**Comment by NicholasNC** [comment]
@lyingd 我使用提供的CLI工具——`ant-design-pro-cli`，然后按照你的方法来弄是可以的。

1. 在 `public` 目录下放置iconfont的文件，如下图
    - ![image](https://user-images.githubusercontent.com/10840542/36652236-7bd18f68-1ae8-11e8-9108-91d4f94fae5d.png)
2. 修改 `\src\theme.js` 文件，增加多你提供的一行： `'@icon-url': '"/antIconfont/iconfont"',`

测试过正式环境和开发环境都可以

**Comment by lyingd** [comment]
@NicholasNC 是这样的，非独立版是没问题的，是把ant-design-pro集成到其他项目里才会存在该问题

**Comment by zywcode** [comment]
@afc163 开发环境和测试环境的路径不一样，`/src/theme.js`的`'@icon-url': '"/fonts/antd/iconfont"'`应该怎么配？
另外，有没有anticon的最新版下载地址？[anticon](https://github.com/ant-design/ant-design/releases/download/resource/iconfont-3.x.zip)这个下载的跟cdn的不同步，缺一些icon。

**Comment by afc163** [comment]
@zywcode 

1. 试试用环境变量做区别。
2. 链接里的 zip 包已更新。

**Comment by zywcode** [comment]
好的，谢谢。 @afc163
