### ISSUE TITLE
🐛[BUG] 使用 ant-pro-v5 初始化项目，启动时报错“Cannot find module: 'isomorphic-form-data' in swagger-ui-react”

### ISSUE THREAD

**Issue by niexq** [ant-design/ant-design-pro#8820]
### 🐛 bug 描述
使用 ```ant-pro-v5``` 初始化项目，启动时，终端报错“Cannot find module: 'isomorphic-form-data' in swagger-ui-react”，但是项目可正常访问

### 📷 复现步骤
以下```或```的两种情况试过，都报错，（启动或不启动```MFSU```都会报错）

```bash
# use by npm
npx create-umi myapp
# 或
# use by yarn
yarn create umi myapp

> ant-design-pro
> TypeScript 或 JavaScript
> complete
> cd myapp

npm install 或 yarn install

npm start
```

### 🏞 期望结果
启动时无报错

### 💻 复现代码
github地址：https://github.com/niexq/ant-pro-qiankun-main

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本: [^3.5.0]
- 浏览器环境
- 操作系统：MacBook Pro（macOS Big Sur ）
- 代码编辑器：Visual Studio Code
- 版本：1.58.2
- 安装方式：yarn 或 npm

### 🚑 其他信息

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/ant-pro.gif)

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/npmlist.png)

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/openapi2.png)

**Comment by niexq** [comment]
好吧，看来像是swagger-ui依赖的问题， https://github.com/swagger-api/swagger-js/pull/2154
是不是得更新下@umijs/plugin-openapi对swagger-ui-react依赖版本

**Comment by kaisawind** [comment]
just to fixed it right now.
```bash
yarn add isomorphic-form-data
```

**Comment by niexq** [comment]
> 只是为了立即修复它。
> 
> ```shell
> 纱线添加同构形式数据
> ```

👌 🍻

**Comment by niexq** [comment]
同问题issues：https://github.com/ant-design/ant-design-pro/issues/8820#issuecomment-887996895

**Comment by chenshuai2144** [comment]
ref https://github.com/swagger-api/swagger-ui/issues/7436

看来是发包没跟上出问题了

**Comment by JERRYZFC** [comment]
you guys are just in time

**Comment by 521guyu** [comment]
我也遇到了有快速修复方案吗？

**Comment by longxuexiaojiejie** [comment]
I found the same problem
