### ISSUE TITLE
🧐ant design V5 的权限管理，好像对于请求不会进行权限的控制，

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8824]
### 🧐 问题描述
🧐ant design V5 的权限管理，好像对于请求不会进行权限的控制，
只有在刷新页面的时候才会去访问access，怎么做到每发一个请求都去请求一下权限

**Comment by chenshuai2144** [comment]
。。。让后端搞吧，不要给自己加戏了。前端简单做一下就行了的。

前端做的越重越不可靠
