### ISSUE TITLE
🧐[Question] How to access DVA state in Layout Component in V5

### ISSUE THREAD

**Issue by sarthakwebosmotic** [ant-design/ant-design-pro#8826]
### 🧐 Problem description

Hello, I am looking for way to get DVA state access in the layout component that is declared in the `app.tsx` file.  At the moment it has access to only initialState declared by useModel. 

### 💻 Sample code

`nothing to share`

### 🚑 Other information
![Pro Layout in V5](https://i.postimg.cc/PJzg4pQZ/prolayout.png "Pro Layout in V5")

**Comment by Clago** [comment]
https://pro.ant.design/zh-CN/docs/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80
