### ISSUE TITLE
阿里团队，为啥没有推出像uni-app , taro这样的框架

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#8827]
阿里团队，为啥没有推出像uni-app , taro这样的做小程序，APP的框架呢？

ant design，ant design pro都做到这么极致了。

**Comment by hengkx** [comment]
remax ?

**Comment by xyzabc0004** [comment]
What !?

**Comment by hengkx** [comment]
https://remaxjs.org/

**Comment by xyzabc0004** [comment]
好用不？
Taro我倒是有尝试。

**Comment by xyzabc0004** [comment]
要是remax，能出APP和小程序，我都选她了！

**Comment by codedart2018** [comment]
trao难用　首选reamxjs remaxjs就是没有好的ui

**Comment by xyzabc0004** [comment]
我觉得trao还可以啊.很快就上手了.
