### ISSUE TITLE
🧐[问题] 通过formatMessage切换语言包是，能否支持占位符的方式？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#8829]
### 🧐 问题描述

通过formatMessage切换语言包是，能否支持占位符的方式？

### 💻 示例代码

export default {
    'picture.size':'图片最大支持{size}M',
}

const { formatMessage } =useIntl();

formatMessage({id: 'picture.size', values: {size: 2}});

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/29156872/127464702-02faafe2-fce0-4b76-aac0-40f42e13eeb7.png)

**Comment by chenshuai2144** [comment]
https://formatjs.io/docs/react-intl/api#message-syntax

看这个

**Comment by jmy1944311667** [comment]
> https://formatjs.io/docs/react-intl/api#message-syntax
> 
> 看这个

可以了，谢谢
