### ISSUE TITLE
🧐[问题] 关于v5 JS页面拦截器的问题

### ISSUE THREAD

**Issue by Molidada** [ant-design/ant-design-pro#8832]
### 🧐 问题描述

JS页面请求拦截器该怎么写呢？ 

### 💻 示例代码

![1627609161(1)](https://user-images.githubusercontent.com/61493010/127587305-e881ca64-da3e-4ee8-94b0-991678f0da1e.jpg)

### 🚑 其他信息

错误信息如下
![1627609203(1)](https://user-images.githubusercontent.com/61493010/127587354-2ad09742-4435-4da8-be66-79a2befbbb4e.jpg)

**Comment by TinsFox** [comment]
js该用js的写法，官网上的示例代码都是用ts写的需要自己转换一下

**Comment by Molidada** [comment]
> js该用js的写法，官网上的示例代码都是用ts写的需要自己转换一下
