### ISSUE TITLE
🧐[问题]项目运行时打包报错

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#8833]
### 🧐 问题描述
项目运行报错：错误信息如下
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }

### 💻 尝试解决
前提：没有手动安装webpack，package.json文件夹中没有webpack的依赖

尝试一：使用yarn upgrade-interactive --latest更新依赖，更新@ant-design/pro-cli到2.1.4（我不太清除需要更新哪些依赖），然后删掉node_modules、.umi、yarn.lock，接着使用yarn intsall重新安装依赖，使用yarn run start启动项目，依然报错如上

尝试二：升级nodejs，当前node -v : v14.17.3，没啥用

尝试三：修改umi版本到3.4.22，没有用

尝试四：config.dev.ts文件中注释掉 webpack5: {}，项目能运行，但是layouts内的页面持续闪烁

### 🚑 其他信息

1、dependencies:
      ant-design-pro : 4.5.0
      umi : 3.4.1
      umi-reauqest : 1.0.8

2、devDependencies
    "@umijs/fabric": "^2.5.1",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",

config.dev.ts文件
```
// https://umijs.org/config/
import { defineConfig } from 'umi';

export default defineConfig({
  plugins: [
    // https://github.com/zthxxx/react-dev-inspector
    'react-dev-inspector/plugins/umi/react-inspector',
  ],
  // https://github.com/zthxxx/react-dev-inspector#inspector-loader-props
  inspectorConfig: {
    exclude: [],
    babelPlugins: [],
    babelOptions: {},
  },
  webpack5: {},
});
```

**Comment by Youmyin** [comment]
#https://github.com/ant-design/ant-design-pro/issues/8491#issue-893879529

**Comment by Youmyin** [comment]
#8491

**Comment by Youmyin** [comment]
当前issues中找到两个相似的问题但是都没有得到有效的解决办法，或者我的尝试解决方法有什么问题？
#8491
#8828

**Comment by chenshuai2144** [comment]
可以先关掉 

 webpack5: {},

**Comment by Youmyin** [comment]
谢谢！删掉`webpack5: {},`可以，不过打开页面后在user/login界面，页面持续跳动闪烁，不放在layouts页面内的倒是可以正常显示

**Comment by chenshuai2144** [comment]
问了云谦老师，推荐删掉这个配置
