### ISSUE TITLE
🧐[问题] Form组件设置initialValues，初始化正常，但是刷新页面之后，initialValues数据不见了 ？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#8834]
### 🧐 问题描述

我现在对Form设置了initialValues，页面初始化是正常的，但是我刷新页面之后，Form中的数据没了，我打印了initialValues的值，发现是渲染的时候，针对initialValues渲染了两次，第一次是空的，第二次有值，但是页面展示的时候，initialValues为第一次的值，这个怎么处理？

### 💻 示例代码
       
      const {currentUser, intl} = this.props;

     console.log(currentUser);

       <Form
            layout="vertical"
            onFinish={(values) => this.handleFinish(values)}
            initialValues={currentUser}
          >
            <Form.Item
              name="id"
              hidden={true}
              label={intl.formatMessage({
                id: 'baseManageer.userManageer.updateForm.nameLabel',
              })}
            >
              <Input disabled/>
            </Form.Item>
       </Form>

### 🚑 其他信息
初始化页面信息
![image](https://user-images.githubusercontent.com/29156872/127591223-a96d7206-f91c-44c5-b49e-e3eebdec58ac.png)
初始化时，打印的initialValues信息
![image](https://user-images.githubusercontent.com/29156872/127591782-5c26cb2e-1ac0-417b-88f2-393de2484195.png)

页面刷新之后
![image](https://user-images.githubusercontent.com/29156872/127591268-cb7ae0f2-8850-4601-9341-e5ccb407e127.png)
刷新页面，打印的initialValues信息
![image](https://user-images.githubusercontent.com/29156872/127591877-07f19cc8-b577-4ca0-9398-0873625a42df.png)

**Comment by kaoding** [comment]
initialValues 只有初始化前设置值才有效，上面你的第一次渲染和第二次渲染是react干出来的事。

**Comment by jmy1944311667** [comment]
> initialValues 只有初始化前设置值才有效，上面你的第一次渲染和第二次渲染是react干出来的事。
那这个问题知道怎么解决吗？

**Comment by jmy1944311667** [comment]
> initialValues 只有初始化前设置值才有效，上面你的第一次渲染和第二次渲染是react干出来的事。

**Comment by jmy1944311667** [comment]
> initialValues 只有初始化前设置值才有效，上面你的第一次渲染和第二次渲染是react干出来的事。

我上网查了这个问题，没找到相关的解决方法，大佬知道怎么搞吗？

**Comment by chenshuai2144** [comment]
`initialValues&&<Form/>`
