### ISSUE TITLE
antd-design-pro v5  mac 系统，每次安装完新的包，重新打包都会报一下错误AssertionError [ERR_ASSERTION]: filePath not found of /Volumes/存储盘/webspace/dom/myapp/node_modules/@umijs/renderer-react

### ISSUE THREAD

**Issue by wnagzhenwei** [ant-design/ant-design-pro#8835]

**Comment by wangtiegang** [comment]
碰到相同问题，```tyarn create umi app``` 创建pro v5项目，windows系统下 ```tyarn install``` 无问题，start 后报错
![image](https://user-images.githubusercontent.com/20106449/127607613-b7057636-2503-417e-b2b5-3250f7e5f22b.png)

**Comment by wangtiegang** [comment]
config.ts 里面注释掉 ```mfsu: {},``` 配置就可以正常启动了

**Comment by wangtiegang** [comment]
> config.ts 里面注释掉 `mfsu: {},` 配置就可以正常启动了

删除整个项目，重新操作，又没问题了。

**Comment by chenshuai2144** [comment]
看起来是你的文件夹权限问题，删除文件夹然后清空一下权限

**Comment by chenxizhang** [comment]
也遇到这个问题，之前都是好好的，不知道为啥编译出现这个错误

Module not found: Error: Can't resolve '@umijs/renderer-react/node_modules/@types/react'

**Comment by Indomi** [comment]
> Umi 3.5.20，也突然发生这个问题。确实没有renderer-react这个目录。

我这边也是，不过我完全清理掉
node_modules
src/.umi
src/.production
lock文件
重新装依赖启动就没事了
