### ISSUE TITLE
🧐[问题]Form组件设置initialValues，页面初始化正常，但是刷新页面之后，initialValues数据不见了 ？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#8836]
### 🧐 问题描述

我现在对Form设置了initialValues，页面初始化是正常的，但是我刷新页面之后，Form中的数据没了，我打印了initialValues的值，发现是react渲染的时候，渲染了两次，第一次渲染initialValues是空的，第二次渲染initialValues是正常的，但是页面展示的时候，initialValues是第一次的值，这个怎么处理？

### 💻 示例代码

      const {currentUser, intl} = this.props;

       console.log(currentUser);

    <Form
        layout="vertical"
        onFinish={(values) => this.handleFinish(values)}
        initialValues={currentUser}
      >
        <Form.Item
          name="id"
          hidden={true}
          label={intl.formatMessage({
            id: 'baseManageer.userManageer.updateForm.nameLabel',
          })}
        >
          <Input disabled/>
        </Form.Item>
    </Form>

### 🚑 其他信息

初始化页面信息
![image](https://user-images.githubusercontent.com/29156872/127610871-d9a07ae3-9e15-4e3e-9753-7f74bcfbc4d1.png)
初始化时，打印的initialValues信息
![image](https://user-images.githubusercontent.com/29156872/127610905-922be06a-7c1c-4501-a939-a3b7a419bbca.png)

页面刷新之后
![image](https://user-images.githubusercontent.com/29156872/127610924-6fecb956-52d2-4d10-9222-b0c5c884cb3c.png)
刷新页面，打印的initialValues信息
![image](https://user-images.githubusercontent.com/29156872/127610942-bb6201ea-d8da-4f46-9457-a2b7b637284b.png)

**Comment by jmy1944311667** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🧐[问题] Form组件设置initialValues，初始化正常，但是刷新页面之后，initialValues数据不见了 ？ #8834](https://github.com/ant-design/ant-design-pro/issues/8834)][🧐[问题] Form组件设置initialValues，初始化正常，但是刷新页面之后，initialValues数据不见了 ？][98%]

这个就是我之前提的，但是被我不小心关闭了，我还未获取到答案，所以重新提的

**Comment by chenshuai2144** [comment]
initialValues 顾名思义 只有 init 生效，你可以这样

```
initialValues && <Form/>
```

**Comment by jmy1944311667** [comment]
> ```tsx
> initialValues && <Form/>
> ```
这个是什么写法？  在js里面怎么写？

**Comment by jmy1944311667** [comment]
> initialValues 顾名思义 只有 init 生效，你可以这样
> 
> ```tsx
> initialValues && <Form/>
> ```

设置了，但是还是一样的效果，刷新页面会造成form数据不显示
