### ISSUE TITLE
🧐[问题] 使用 ```ant-pro-v5``` 初始化项目，按官方文档配置qiankun，终端报错 “Invalid config key: qiankun“

### ISSUE THREAD

**Issue by niexq** [ant-design/ant-design-pro#8838]
### 🧐[问题] 描述
使用 ```ant-pro-v5``` 初始化项目，按[官方文档配置qiankun](https://umijs.org/zh-CN/plugins/plugin-qiankun)，终端报错 “Invalid config key: qiankun”

### 📷 复现步骤

```bash
# use by npm
npx create-umi myapp
# 或
# use by yarn
yarn create umi myapp

> ant-design-pro
> TypeScript 或 JavaScript
> complete
> cd myapp

npm install 或 yarn install

npm start
```

### 🏞 期望结果
启动时无报错

### 💻 复现代码
github地址：https://github.com/niexq/ant-pro-qiankun-main

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本: [^3.5.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]
- 操作系统：MacBook Pro（macOS Big Sur ）
- 代码编辑器：Visual Studio Code
- 版本：1.58.2
- 安装方式：yarn 或 npm

### 🚑 其他信息

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/qiankunerror.png)

**Comment by shilianmalaxiangguo** [comment]
老哥 你是怎么解决的

**Comment by niexq** [comment]
> 老哥 你是怎么解决的

还没解决，在umi提交的issues等待处理中
https://github.com/umijs/umi/issues/7117

**Comment by shilianmalaxiangguo** [comment]
> > 老哥 你是怎么解决的
> 
> 还没解决，在umi提交的issues等待处理中
> [umijs/umi#7117](https://github.com/umijs/umi/issues/7117)

https://umijs.org/zh-CN/plugins/plugin-qiankun 这个你看了吗

**Comment by niexq** [comment]
> 老哥 你是怎么解决的

搞错了，不是同一个问题，这个是因为第一步安装出问题导致，所有直接关闭了issues

**Comment by niexq** [comment]
> 老哥 你是怎么解决的

和另外一个issues弄混了，这个issues是因为第一步安装失败导致，所有直接关闭了issues。

**Comment by niexq** [comment]
上述问题因本地安装环境问题导致，所有关闭
