### ISSUE TITLE
我在使用v5时，移除国际化命令时出现报错Error: ENOENT: no such file or directory🧐[问题]

### ISSUE THREAD

**Issue by 521guyu** [ant-design/ant-design-pro#8839]
### 🧐 问题描述

1.我在使用v5时，移除国际化命令时出现报错
环境信息：
win10
版本 "version": "5.0.0"
"umi": "^3.5.0",
![1627643372(1)](https://user-images.githubusercontent.com/42431406/127644616-010c366f-4e49-4543-8358-aa0d2b8a58a3.png)

2.v5初始化项目没有了models文件夹了吗?
4版本默认就有，5的话我看文档上目录结构有，但我初始化之后没有。是自己创建一个还像之前使用一样使用吗？

![1627643395(1)](https://user-images.githubusercontent.com/42431406/127644653-6fe8c0ab-4ab7-4b35-953e-9b0e349629b0.png)

3.如果我依然想用v4的框架，怎么使用，我记得之前创建时可以选择版本，现在默认直接v5.
因为我是在内网开发，更新依赖很麻烦（内网里的东西无法复制出来package.json），所以我想依然使用v4。v5刚发布不久担心更新频繁。相对v5我在这段时间还是想用v4,有没有接着使用v4的方法？

**Comment by TinsFox** [comment]
1. 把`routes.ts` 修改成`toutes.js` ，重新执行命令移除国际化，然后再修改回来。造成的原因应该是脚手架命令没有考虑到js版的情况，因为V5 推荐使用TypeScript
2. 默认没有，如有需要可以执行创建，用法跟以前一样，默认会识别成module
3. `git clone https://github.com/ant-design/ant-design-pro && cd ant-design-pro &&   git checkout v4` 这是`simple` 版的获取方式，完整版需要进一步处理(`yarn run fetch:blocks`)，获取到的可能会有问题，这个答案在issues中有人提问过并且有解决方案
4. v5 更新还没有太频繁，都是一些小功能的添加修复，可以根据查看每次的commit different自行改动

**Comment by chenshuai2144** [comment]
已经修复更新下版本吧
