### ISSUE TITLE
容器中不存在模块“/antd/es/tree select/style”。

### ISSUE THREAD

**Issue by zxm-hh** [ant-design/ant-design-pro#8842]
tree-select 和 Cascader 都出现了

版本: ant Design pro  v5
devScripts.js:6523 [@umijs/runtime] load component failed 
Error: Module "./antd/es/tree-select/style" does not exist in container.
while loading "./antd/es/tree-select/style" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:813
    
    mf-va_remoteEntry.js:813 Uncaught (in promise) 
Error: Module "./antd/es/tree-select/style" does not exist in container.
while loading "./antd/es/tree-select/style" from webpack/container/reference/mf

**Comment by weypro** [comment]
Upload组件也出现类似问题

**Comment by chenshuai2144** [comment]
删除缓存，然后重新启动，这个是 mfsu 没有自动编译导致的。
```
git add .
git clean -dfx
tyarn
```

**Comment by chao325** [comment]
我这边排查出来的是cross-env问题。 ` npm install -save-dev cross-env` 安装一下就OK了

**Comment by homeant** [comment]
大佬们，请我解决了吗，我这还是不行呀

**Comment by lunaSunday** [comment]
> 删除缓存，然后重新启动，这个是 mfsu 没有自动编译导致的。
> 
> ```
> git add .
> git clean -dfx
> tyarn
> ```

每次引入新的组件都要清除缓存，重新启动。。。
