### ISSUE TITLE
🐛[BUG]服务器部署后，路由上传参数刷新报错

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#8843]
### 🐛 bug 描述
服务器部署后，路由上传参数刷新报错，传参格式：
![image](https://user-images.githubusercontent.com/51156342/127726580-149402de-0cf3-4a67-921b-264048ccdaaa.png)
![image](https://user-images.githubusercontent.com/51156342/127726581-93fe18c4-cc19-418d-9616-edab40b70f36.png)

这个该怎么解决呀
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
404 ？

https://pro.ant.design/zh-CN/docs/deploy#%E4%BD%BF%E7%94%A8-nginx
