### ISSUE TITLE
🐛[BUG]使用图标出错

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#8844]
### 🐛 bug 描述
在菜单中使用antd中的图标并去掉了OutLined,但是无法生效
![image](https://user-images.githubusercontent.com/51156342/127727096-7411d8af-5655-4cab-8c83-e1bd27d4ece1.png)
shi使用后不生效，并且重启了。
![image](https://user-images.githubusercontent.com/51156342/127727104-3c690b3f-482f-49ea-a211-d4e906688374.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
icon 名要写全名，大小写也不能错

**Comment by YC725968** [comment]
![image](https://user-images.githubusercontent.com/51156342/127736082-c5336ac8-083c-4144-a35b-59f670b3fcbb.png)
umi里是这这样配置的，但我按照这个规则配置成上面部生效

**Comment by chenshuai2144** [comment]
这个估计有人写错了，我去改掉

**Comment by YC725968** [comment]
好的

**Comment by chengzi-code** [comment]
这个问题是出现在从服务器请求菜单的时候 
```
 return {
    menu: {
      params: initialState,
      // 这里从后端请求动态菜单
      request: async (params, defaultMenuData) => {
        // initialState.currentUser 中包含了所有用户信息
        // return defaultMenuData;
        // 这里返回后端的菜单配置
        return [
          {
            path: '/welcome',
            name: 'welcome',
            icon: 'SoundOutlined',
          },
          {
            name: 'list.table-list',
            path: '/list',
            icon: 'table',   // 这里的图标不会渲染
          },
        ];
      },
    },
```
