### ISSUE TITLE
🐛[BUG] 退出登录报错　Can't perform a React state update on an unmounted component. 

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8845]
### 🐛 bug 描述

登陆过后，退出重新登陆控制台报错。
```
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

### 📷 复现步骤

我在login登录页面，加入了网络请求
```
const getConfig = ()=> {
setState({.....})
}
  useEffect(() => {
    getConfig();
  }, []);
```

### 🏞 期望结果
控制台不报错。如果我不进行网络请求的话，它将不会报错。而且我仔细观察了一下，退出登陆将会造成网次网络请求。正常进入这个页面也顶多只能允许进行一次网络请求。但实际上是进行了两次。如果是我通过url直接进入，或者刷新页面，我都只看到了一次网络请求。唯独退出登陆两次网络请求进行setState报错。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你判断一下有没有解除挂载，如果解除了就不要 setState 了。
