### ISSUE TITLE
🧐[问题]像Card组件标题，而且标题在横线中的样式是什么组件

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#8847]
### 🧐 问题描述
标题在横线中的样式是什么组件？像CARD组件设置的标题属性，但又像Card+Divider组件的组合用法，测试了下都不是。这个样式的组件是什么？

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/857669/127760154-921be69c-f0c7-4625-b344-d7739c6351ae.png)

**Comment by chenshuai2144** [comment]
这个是 demo 卡片自己实现的，现在没有通用组件。
其实就是给个背景颜色，然后浮动到上面挡住线
