### ISSUE TITLE
🐛[BUG] 集成的dumi工作不正常

### ISSUE THREAD

**Issue by TanShun** [ant-design/ant-design-pro#8848]
### 🐛 bug 描述

我想使用Ant Design Pro 内置的文档工具书写项目文档，参考dumi的文档，项目中新建了`docs`，编写了相关文档，发现文档渲染不正常，会出现例如搜索不生效，文档的 toc 配置不生效等状况。

### 📷 复现步骤

安装一份最新的  ant-design-pro 5.0.0，在项目中创建一个docs目录，编写一个包含多级标题的文档，启动项目，然后查看文档，会发现文档有渲染，但工作不正常。(测试发现MFSU会生成缓存，对文档更新渲染有影响，建议先在配置文件中将其关闭)。

### 🏞 期望结果

dumi 文档的 `toc` 默认值是`content`，即应该在文档内容区域的右侧展示出本篇文档的标题锚链接。深入测试会发现，文档的其他FrontMatter配置项都无效，如果开启site模式，文档搜索也不能正常工作。

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- 开发环境: Ubuntu 20.04(WSL2)

### 🚑 其他信息

我尝试直接使用dumi项目、或者在umi项目中安装`@umijs/preset-dumi`部署文档，都未能复现此BUG，可初步排除是dumi项目的BUG。最后发现如果关闭配置文件中的`layout`配置项，可以消除此BUG，复现步骤如下：首先注释掉运行时配置`app.tsx`中的`layout`导出，再注释掉配置文件`config/config.ts`中的`layout`项（或者将值设置为false），重新启动项目，访问文档链接地址会发现文档渲染正常了。

**Comment by chenshuai2144** [comment]
@PeachScript 来看看是什么问题

**Comment by PeachScript** [comment]
@TanShun 能给个最小可复现仓库吗

**Comment by TanShun** [comment]
@PeachScript 刚搭建了一个：[演示仓库](https://github.com/TanShun/antd-pro-demo)，仅在项目中添加了一个`/docs/index.md`文档用于演示

**Comment by xietianfu** [comment]
@TanShun 我也遇到了和你一样的问题。受你的启发，我将代码做了如下的修改：
1. 首先在`package.json`中的`"scripts"`下添加`"doc": "cross-env REACT_APP_ENV=doc umi build --dumi"`,给dumi文件生成添加一个环境。
2. 然后在`src/app.tsx`中，读取该变量，`const isDoc = REACT_APP_ENV === 'doc';`。
3. 分别在`src/app.tsx`中，将相关导出直接返回`null`。
```
/**
 * @see  https://umijs.org/zh-CN/plugins/plugin-initial-state
 * */
export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
} | null> {
  if (isDoc) {
    return null;
  }
 
  // 如果是登录页面，不执行
  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: {},
    };
  }
  return {
    fetchUserInfo,
    settings: {},
  };
}

// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  if (isDoc) {
    return {};
  }
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    waterMarkProps: {
      content: initialState?.currentUser?.name,
    },
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { location } = history;
      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser && location.pathname !== loginPath) {
        history.push(loginPath);
      }
    },
    links: isDev
      ? [
          <Link to="/umi/plugin/openapi" target="_blank">
            <LinkOutlined />
            <span>OpenAPI 文档</span>
          </Link>,
          <Link to="/~docs">
            <BookOutlined />
            <span>业务组件文档</span>
          </Link>,
        ]
      : [],
    menuHeaderRender: undefined,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings,
  };
};

```
4. 最后执行`yarn doc`。就获得了，没有接口请求，与路由调整的文档了。
