### ISSUE TITLE
🧐[问题] How to use `useIntl()` hooks in `defaultSettings.ts` ?

### ISSUE THREAD

**Issue by kevinadhiguna** [ant-design/ant-design-pro#8849]
### 💻 示例代码

Hi, I tried to use `useIntl()` hooks for app title like below.

![image](https://user-images.githubusercontent.com/43397636/127795394-2ba0fcd2-0dd1-4fc9-9bae-efb2acaeacba.png)

However, even though `title` returns string and `useIntl().formatMessage({})` returns string as well, when I execute `yarn start` or `yarn`, I got this error saying `TypeError: (0 , _umi.useIntl) is not a function` like this : 

![image](https://user-images.githubusercontent.com/43397636/127795610-1039ce91-39fe-46fe-b1ab-101c1493b6d7.png)

I looked at this [issue](https://github.com/umijs/umi/issues/5138) but unfortunately none of them helped me...

Any help is appreciated, thank you !

**Comment by chenshuai2144** [comment]
在 app.tsx 中使用吧。

`src/app.tx`

```
const layout = ()=>{
return {
   title: formartMessage()
 }
}
```

**Comment by TinsFox** [comment]
> 在 app.tsx 中使用吧。
> 
> `src/app.tx`
> 
> ```
> const layout = ()=>{
> return {
>    title: formartMessage()
>  }
> }
> ```
> 
> useInit 需要在组件中使用，用 formartMessage 导出为一个 string 会更方便

借楼提问一下，怎么在网络请求拦截器里面使用`initialState?.currentUser`

在前面的登录流程中currentUser存了用户的token，使用JWT认证，目前的方案是存在localStorage里面，在拦截器的配置如下
```js
const authHeaderInterceptor = async (url, options) => {
  const authHeader = {
    Authorization: `Basic ${localStorage.getItem(`${localStorageKey}-token`) || '';}',
    'content-type': 'application/x-www-form-urlencoded',
    ...options.headers,
  };
  return {
    url: `${url}`,
    options: { ...options, interceptors: true, headers: authHeader },
  };
};
```
这样的写法感觉是每次网络请求都会调用`localStorage.getItem` 是不是会消耗性能，是不是使用initialState里面存储的token会减少消耗

**Comment by kevinadhiguna** [comment]
> 在 app.tsx 中使用吧。
> 
> `src/app.tx`
> 
> ```
> const layout = ()=>{
> return {
>    title: formartMessage()
>  }
> }
> ```
> 
> useInit 需要在组件中使用，用 formartMessage 导出为一个 string 会更方便

I import hooks at the top level of a component in `app.tsx` like below : 

![image](https://user-images.githubusercontent.com/43397636/127798674-65de4c00-5185-41b3-889c-db1ed1bd9b1d.png)

However, I got this error : 

![image](https://user-images.githubusercontent.com/43397636/127798808-8a662e65-edc7-4423-b341-ae17bad36920.png)

Could you please give a hint what was wrong ? Thank you..
