### ISSUE TITLE
🐛[BUG] 打包错误

### ISSUE THREAD

**Issue by Lind-pro** [ant-design/ant-design-pro#8854]
### 🐛 bug 描述
启动项目没问题，运行yarn run build 报错。错误如下：
![image](https://user-images.githubusercontent.com/18098618/127818280-171d11c5-a492-42f3-8a2f-d790b1b7d2ff.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TinsFox** [comment]
缺少了一个依赖，可以尝试删除依赖重新安装
`rm -rf node_modules && rm  yarn.lock && yarn install && yarn run build`

**Comment by Lind-pro** [comment]
> 缺少了一个依赖，可以尝试删除依赖重新安装
> `rm -rf node_modules && rm yarn.lock && yarn install && yarn run build`

尝试了，还是一样的错误

**Comment by kapok-jose** [comment]
最后搞定了吗？我也出现这个了

**Comment by kapok-jose** [comment]
@Lind-pro 最后怎么解决的呀大佬？
