### ISSUE TITLE
使用useRequest点击下拉加载更多加载不出更多数据🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8855]
### 🐛 bug 描述
使用useRequest点击下拉加载更多时发现打印的data数据一直都是5条没有递增， 在官方pro打印data数值是数据是有递增的，但 是按照官方的写法不知道数据为啥没用递增

![image](https://user-images.githubusercontent.com/20655248/127834367-540505c1-f580-4221-97e3-0996f0b8bde6.png)
![image](https://user-images.githubusercontent.com/20655248/127834614-1832421c-51cc-4cdd-b4f4-4509d6015b4f.png)
![image](https://user-images.githubusercontent.com/20655248/127834744-a05de440-426f-44ac-b84d-3cd6241bb891.png)
![image](https://user-images.githubusercontent.com/20655248/127834847-a703b299-e855-4fd0-afcd-331a1a19ab34.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你调用了 loadMore 还是 reload

**Comment by lovehebe330** [comment]
> 你调用了 loadMore 还是 reload
![image](https://user-images.githubusercontent.com/20655248/127949309-fc880b26-936e-440a-9702-d449bb177d5a.png)

![image](https://user-images.githubusercontent.com/20655248/127949290-0d61333f-2b79-495f-9901-e1378968ebf3.png)
2个都调了 跟官方写法一模一样 但就没法加载更多数据

**Comment by chenshuai2144** [comment]
不能调用reload的，reload是拉回来数据然后覆盖，

loadMorse是拉回来数据然后加到末尾

**Comment by lovehebe330** [comment]
> 不能调用reload的，reload是拉回来数据然后覆盖，
> 
> loadMorse是拉回来数据然后加到末尾
但是单独调用loadMore点击下拉加载更多按钮后数据依旧没有追加到末尾，数据依然是之前的条目为啥？
![image](https://user-images.githubusercontent.com/20655248/127974419-5594cdf0-58f3-4ddc-b250-6a61680eb1b8.png)
![image](https://user-images.githubusercontent.com/20655248/127974466-0e657f5d-0e27-43ab-948c-ae883c201488.png)
![image](https://user-images.githubusercontent.com/20655248/127974485-cbddb38c-86f7-4d2d-bb0d-41111603b72b.png)
![image](https://user-images.githubusercontent.com/20655248/127974608-0e09e1dd-1d30-4137-b93b-a9b09207f1f8.png)
难道数据字段问题吗

**Comment by chenshuai2144** [comment]
那还可能是key 重复了之类的
