### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by niexq** [ant-design/ant-design-pro#8861]
### 🐛 bug 描述
使用 ```ant-pro-v5``` 初始化项目，按[官方文档配置qiankun](https://umijs.org/zh-CN/plugins/plugin-qiankun)，终端报错 “Uncaught (in promise) Error: Module "./lodash/concat" does not exist in container.
while loading "./lodash/concat" from webpack/container/..”

### 📷 复现步骤

```bash
# use by npm
npx create-umi myapp
# 或
# use by yarn
yarn create umi myapp

> ant-design-pro
> TypeScript 或 JavaScript
> complete
> cd myapp

npm install 或 yarn install

npm start
```

主应用配置步骤：

1.安装`@umijs/plugin-qiankun`

```bash
@umijs/plugin-qiankun
```

2.注册子应用，`config.ts`配置`qiankun`开启

```ts
qiankun: {
    master: {
      // 注册子应用信息
      apps: [
        {
          name: 'app1', // 唯一 id
          entry: '//localhost:8899', // html entry
        },
      ],
    },
  },
```

3.装载子应用，`routes.ts`增加
```ts
  {
    path: '/app1',
    name: 'app1',
    microApp: 'app1'
  },
```

子应用配置步骤：

1.安装`@umijs/plugin-qiankun`

```bash
@umijs/plugin-qiankun
```

2.插件注册，`config.ts`配置
```ts
qiankun: {
  slave: {}
}
```

3.配置运行时生命周期钩子（可选）

```ts
export const qiankun = {
  // 应用加载之前
  async bootstrap(props) {
    console.log('app1 bootstrap', props);
  },
  // 应用 render 之前触发
  async mount(props) {
    console.log('app1 mount', props);
  },
  // 应用卸载之后触发
  async unmount(props) {
    console.log('app1 unmount', props);
  },
};
```

### 🏞 期望结果
启动时无报错

### 💻 复现代码
github地址（主应用）：https://github.com/niexq/ant-pro-qiankun-main
github地址（子应用）：https://github.com/niexq/ant-pro-qiankun-sub

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本: [^3.5.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]
- 操作系统：MacBook Pro（macOS Big Sur ）
- 代码编辑器：Visual Studio Code
- 版本：1.58.2
- 安装方式：yarn 或 npm

### 🚑 其他信息

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/ant-pro-v5-qiankun-error.png)

**Comment by chenshuai2144** [comment]
去 umi 问吧，。没用过微前端

**Comment by niexq** [comment]
> 去 umi 问吧，。没用过微前端

嗯，谢谢，已经在umi问了，当前issues已关闭
