### ISSUE TITLE
🐛[BUG] 在线等，急急急！TypeError: Cannot read property '@@initialState' of undefined

### ISSUE THREAD

**Issue by xykjlcx** [ant-design/ant-design-pro#8863]
### 🐛 bug 描述

项目打包后，部分页面白屏，控制台报错：TypeError: Cannot read property '@@initialState' of undefined
开发环境没有任何问题

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32430701/127958488-2ae0c659-6390-4ee9-8b66-a9cf1943269f.png)

**Comment by xykjlcx** [comment]
@chenshuai2144 老哥，帮忙看下

**Comment by kevinsheep** [comment]
https://github.com/ant-design/ant-design-pro/issues/9036
应该是这个问题
