### ISSUE TITLE
使用useRequest如何配置formatResult跟loadMore一起使用🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8865]
### 🐛 bug 描述

因为后端返回data是这样的 不是官方提供的数据结构= {list: Item[]}
![image](https://user-images.githubusercontent.com/20655248/128010258-aa1fea45-eacc-44e4-beb6-dce1cd6e64ad.png)
所以需要用formatResult格式一下数据，发现
![image](https://user-images.githubusercontent.com/20655248/128010488-e341af09-34f0-4648-9e65-7aefbe32a38e.png)
发现加上formatResult后loadMore红线了，这样写好像错误了，
请教一下loadMore配合formatResult的正确用法
这个问题好像就是点击加载更多按钮数据没有追加进去的原因？
没有加formatResult像效果是正常的
![image](https://user-images.githubusercontent.com/20655248/128011307-fe1f333c-8943-4c13-b532-41c0292d1ed5.png)
加上formatResult就红线了
![image](https://user-images.githubusercontent.com/20655248/128011458-8c68002d-5428-48e0-bb5a-941920a71793.png)
求教loadMore配合formatResult的正确用法 如何用formatResult配置{ data：Item[]}的数据格式
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
去 useRequest 问一下， 可能是 api 互斥了吧
