### ISSUE TITLE
预览链接无法登陆

### ISSUE THREAD

**Issue by wangjunget** [ant-design/ant-design-pro#8867]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/39700548/128032997-9e2d392f-da9b-426c-9795-5fe33e754f4a.png)
![image](https://user-images.githubusercontent.com/39700548/128033041-a3956760-c12a-4ddd-b5ee-fa0fadb0652b.png)

**Comment by noobwu** [comment]
用 npm run start 命令就可以了

**Comment by wangjunget** [comment]
> 用 npm run start 命令就可以了

是的clone下来可以打开，我是说这个预览链接直接登录不上

**Comment by chenshuai2144** [comment]
https://preview.pro.ant.design/dashboard/analysis

来个重现地址把
