### ISSUE TITLE
🧐[问题] 有的时候打开应用，页面样式部分丢失。

### ISSUE THREAD

**Issue by happydudu** [ant-design/ant-design-pro#8871]
### 🧐 问题描述
 应用保持运行，有的时候打开页面，会发现样式部分丢失。然后在同样的浏览器打开官方的预览页面，发现也有这样的情况。但是运行一段时候后，有时会恢复正常。请大神帮忙解释一下，为什么灰色的背景和分割线偶尔就不见了。
### 🚑 其他信息

 正常情况：
![YH4%_0GV4DL6VJ8YQ5M9}02](https://user-images.githubusercontent.com/5652567/128119874-69687ea8-b2f7-40f3-82fa-0583f5e2411d.png)

异常情况：
![}{1L$35QS6~UNNA`9`~(4 8](https://user-images.githubusercontent.com/5652567/128119780-bff3a861-fa7d-43cb-a73b-f8d5f7ef385d.png)

**Comment by chenshuai2144** [comment]
应该是页面样式顺序的问题，你是不是屏蔽了什么css

**Comment by happydudu** [comment]
多谢大神回复！！！！
在我本机上一直都正常，我也想不出屏蔽了什么，出现这些问题的都是项目上的服务器，区别就是操作系统版本比较老，难道和系统有关系。

**Comment by zzk1314** [comment]
我也遇到这个问题了。

**Comment by chenshuai2144** [comment]
先把 mfsu 关掉试试吗？

**Comment by happydudu** [comment]
本来也没有启用。umi的版本是3.4。

**Comment by chenshuai2144** [comment]
这个就比较奇怪了，去umi问问，云谦老师估计知道为什么
