### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#8875]
### 🧐 问题描述

使用 ProTable 生成表格页面，和上边的搜索条件，怎么设置查询条件的样式，现在的时间显示不全
![image](https://user-images.githubusercontent.com/32414361/128142820-6a38519a-e005-44bc-b4d7-bb4544831d03.png)
这块好像是自适应的，没找到相关修改的地方

**Comment by chenshuai2144** [comment]
这东西没啥办法的，拆分或者给更长的宽度
