### ISSUE TITLE
protable  生成的表单， 样式修改求助

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#8876]
使用Protable生成表单，页面自动生成的查询条件样式有问题，年月日时分秒时间段，时分秒显示不全。怎么修改样式？
![image](https://user-images.githubusercontent.com/32414361/128143859-b422f861-41b6-47d0-8361-c5c194844add.png)
现在的样式貌似是框架提供自适应的，没找到修改的地方

**Comment by drizzlesconsin** [comment]
设置 `colSize` 应该可以解决你的问题

```diff
...
{
   title: '时间范围',
   dataIndex: 'createdAt',
   valueType: 'dateTime',
+  colSize: 3,
}
...
```

**Comment by yongjiangliu** [comment]
> 设置 `colSize` 应该可以解决你的问题
> 
> ```diff
> ...
> {
>    title: '时间范围',
>    dataIndex: 'createdAt',
>    valueType: 'dateTime',
> +  colSize: 3,
> }
> ...
> ```

用colSize 这个属性解决了。把这个字段放到最后边,colSize:1.5 搞定，谢谢
