### ISSUE TITLE
多次点击，防止发多次请求，使用防抖，结果一有actionRef.current.reload() 就失效了

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#8877]
### 🧐 问题描述

业务场景：表格页面，编辑列  操作按钮，点击弹框，确认，发请求，刷新表格
问题： 如果确定按钮快速点击多次会出现向后端发多次请求的情况
尝试解决： 使用loadsh中的防抖函数进行处理，但是失败了，定位到时因为有actionRef.current.reload()  重新加载表格数据这行代码的缘故
这块该怎么处理？有什么推荐解决方案吗？
![image](https://user-images.githubusercontent.com/32414361/128147048-67bbb8d5-e9d4-44b6-b038-399d12f7e492.png)
![image](https://user-images.githubusercontent.com/32414361/128147092-dc6bd87c-0aa7-46ce-8c68-e32f08dca836.png)

**Comment by chenshuai2144** [comment]
你这个去抖没有意义，要用usecallback 包一下的
