### ISSUE TITLE
关于权限登录从服务器获取角色信息的问题。

### ISSUE THREAD

**Issue by Yunfly** [ant-design/ant-design-pro#888]
在```utils/authority.js```中 ,通过http请求获取到角色信息，但是这里是一个promise对象，并不是函数或者字符串，所以在```components/Authorize``` 中CURRENT并不能直接获取到这个返回值，异步函数也不能通过export导出，这个组件最后是在render中返回，没有合适的地方获取这个异步请求的返回值

```
import { fetchCurrentUser } from '../services/user';

export async function getAuthority() {
  const response = await fetchCurrentUser()
  return response.body.user.user.role || 'guest'
}
```

axios没有同步请求的方法，现在的解决方法是利用jq的ajax中的async配置，将请求设置成同步的，这样既可以在getAuthority中拿到角色内容，并返回。
```
export function getAuthority() {
  let data = ''
  $.ajax({
    type: "get",
    url: "api/users/current",
    async: false,
    success(res) {
      data = res
    },
  });
  return data.body.user.user.role || 'guest'
}
```

我现在就想了解一下，官方的解决思路是什么样子的呢？

**Comment by chenshuai2144** [comment]
可以先打开一个loading界面。等待加载成功之后。
再render

**Comment by chenshuai2144** [comment]
你这样写本本身就不合适吧。
网络请求是个异步的

**Comment by Yunfly** [comment]
@chenshuai2144 这个打开一个loading等待加载，跟我同步请求有什么区别呢

**Comment by chenshuai2144** [comment]
没有区别。但是体验比较好

**Comment by chenshuai2144** [comment]
```
export async function getAuthority() {
  const response = await fetchCurrentUser()
  return response.body.user.user.role || 'guest'
}
```
你这个明显是个异步

**Comment by Yunfly** [comment]
@chenshuai2144 网络请求可以是异步当然也可以是同步的，我现在是想在获取权限这个入口把这个搞定，如果只是为了体验效果，我也可在这前后loading就是了，如果我另起一个组件去获取这个权限再渲染，我甚至不需要这些个js控制了吧

**Comment by chenshuai2144** [comment]
有个reloadAuthorized 你可以试试这个

**Comment by cfkxzsat** [comment]
能给个示例吗。实际应该都是从后端异步获取权限信息吧，，

**Comment by wuqingabc** [comment]
麻烦给个示例吧，我看了下好多人在issue 里面问
