### ISSUE TITLE
Latest version in NPM

### ISSUE THREAD

**Issue by carlesba** [ant-design/ant-design-pro#8885]
The latest version published in npm for `ant-design-pro` is `2.3.2` (https://www.npmjs.com/package/ant-design-pro), however the latest release in this repository is v5. How can we use the latest version?

**Comment by TanShun** [comment]
Follow this guide: [Getting Started](https://pro.ant.design/docs/getting-started/), you can quickly initialize scaffolding:
```bash
# use by npm
npx create-umi myapp
# or use by yarn
yarn create umi myapp
```

**Comment by afc163** [comment]
@chenshuai2144 We should deprecate https://www.npmjs.com/package/ant-design-pro
