### ISSUE TITLE
🧐[tree树形控件，父子节点关联状态下的需求]

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#8888]
## 🧐 tree树形控件，父子节点关联状态下的需求

tree树形控件，父子节点关联状态下，子节点有多个，同时通过“ defaultCheckedKeys”参数设置["父节点","子节点1"]，怎么保证父节点为半选状态，而不是设置了父节点为选中后，其下的所有节点都被选中，求助！！

## 实际显示效果
![image](https://user-images.githubusercontent.com/13744175/128505634-e0a5849a-e0d9-47aa-908c-549445dc0452.png)

## 期望效果
![image](https://user-images.githubusercontent.com/13744175/128505708-26cb55fc-93ff-4688-99b9-9371f5d8680a.png)

**Comment by chenshuai2144** [comment]
defaultCheckedKeys 只设置子节点，让tree帮你设置父节点
