### ISSUE TITLE
点使用文档没有进行正确的跳转

### ISSUE THREAD

**Issue by hoticer** [ant-design/ant-design-pro#889]
![image](https://user-images.githubusercontent.com/10001817/35797077-8a14c900-0a99-11e8-8864-11a08324ecff.png)

**Comment by chenshuai2144** [comment]
浏览器的设置问题？

**Comment by hoticer** [comment]
Chrome,没设置啊，在1.0版本这个文档在侧边栏时点击是能正确打开新标签页进入文档的，然后今天更新了下，发现被移动header去了，就点了下，能打开新标签页但地址不对
