### ISSUE TITLE
在项目里把所有“Ant Design Pro”文字替换掉以后，打包上线后，（左上角LOGO旁）标题依然显示“Ant Design Pro”🐛[BUG]

### ISSUE THREAD

**Issue by amvcxavier** [ant-design/ant-design-pro#8891]
🐛 bug 描述
V5最新版本，在项目里把所有“Ant Design Pro”文字替换掉以后，打包上线后，（左上角LOGO旁）标题依然显示“Ant Design Pro”，在右边主题设置后方可显示替换后的文字，但是刷新页面后仍然显示“Ant Design Pro”。

© 版本信息
Ant Design Pro 版本: [V5.0]
umi 版本
浏览器环境 Chrome
开发环境 [e.g. mac OS]

**Comment by TanShun** [comment]
这个是标题，在配置文件`config/defaultSettings.ts`中找到`title`项进行配置。

**Comment by fangqibin** [comment]
应该有地方漏了
