### ISSUE TITLE
🐛[BUG]已install的情况下，再次执行npm install 报错

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design-pro#8892]
### 🐛 bug 描述

install 第1次成功
install 第2次失败报错
install 第3次成功
install 第4次失败报错
install 第5次成功
install 第6次失败报错
install 第7次成功
install 第8次失败报错

如此。。。

![image](https://user-images.githubusercontent.com/70048681/128588761-3b83fcd3-f659-488d-9373-d3c28cc3e390.png)

### 📷 复现步骤

按官网文档生成工程，必现

### 🏞 期望结果

不报错,正常install

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] V5
- umi 版本 3.5.15
- 浏览器环境 chrome
- 开发环境 [e.g. mac OS] mac OS

**Comment by chenshuai2144** [comment]
看起来是插件机制的问题

**Comment by xyzabc0004** [comment]
可以把你电脑上面的Node.js升到最新版。我之前也有碰到。

**Comment by quicklearning123** [comment]
我的是v14.7.0  @xyzabc0004 请问你的是什么版本呢

> 可以把你电脑上面的Node.js升到最新版。我之前也有碰到。

**Comment by xyzabc0004** [comment]
v14.17.5  跟你差不多少

**Comment by quicklearning123** [comment]
@chenshuai2144 怎么定位是哪个插件问题？这样ci没法做cache，影响打包速度

**Comment by quicklearning123** [comment]
node_modules下面，从antd开始后面的包全被删了，看起来像dumi的代码逻辑有问题
![image](https://user-images.githubusercontent.com/70048681/135594312-d8fe801f-c59e-4ec8-8985-8d6ca0af51b9.png)

**Comment by chenshuai2144** [comment]
推荐执行 
`git clean -dfx`
`npm i`
