### ISSUE TITLE
🐛[BUG]越来越复杂化，炫技？

### ISSUE THREAD

**Issue by liu-xuewen** [ant-design/ant-design-pro#8895]
### 🐛 bug 描述
![d63d40f5bdd500395b40b54c420ecaf](https://user-images.githubusercontent.com/29445066/128631890-e1e12e17-4100-48f1-817b-ec621d592f84.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
应该是js加载有问题

**Comment by TinsFox** [comment]
情况一：是你没有开启mock，antd Pro会尝试访问一些API，没有mock找不到API
情况二：浏览器禁用了JavaScript

### 你提bug的技术也是很炫啊，什么信息都不给，要人想办法去复现贴出来给你选咯

**Comment by chenshuai2144** [comment]
单页应用都是这样的。预览看不见真实的dom
