### ISSUE TITLE
🧐[问题] v5 中 layout的ErrorComponent和onError如何使用

### ISSUE THREAD

**Issue by imchaoyu** [ant-design/ant-design-pro#8896]
### 🧐 问题描述

使用v5，在app.ts的layout内添加了ErrorComponent和onError，但没起作用，请教这块该怎么使用
另外， ErrorComponent是不是可以起到错误边界的作用？

**Comment by chenshuai2144** [comment]
这个是为了我们内部封装用的，没有给外部暴露。

你可以用 childrenRender 自己搞一个

**Comment by chenshuai2144** [comment]
这个是为了我们内部封装用的，没有给外部暴露。

你可以用 childrenRender 自己搞一个
