### ISSUE TITLE
🧐[问题] 在使用自定义布局后，如何正确设置自定义的403页面？ 

### ISSUE THREAD

**Issue by zix2002** [ant-design/ant-design-pro#8898]
### 🧐 问题描述

在使用了自定义的布局后，只能通过`defaultSettings.ts` 或者 在 `config.ts` 的 `layout` 来配置 `unAccessible`，来实现自定义403页面，但是这2个都是`ts`文件，无法加载组件，所以请问在哪里可以正确配置自定义的 `403页面`呢？

### 💻 示例代码

无

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
app.tsx 里面不能设置吗？

**Comment by zix2002** [comment]
已解决，谢谢提醒，之前把`app.tsx`的`layout`注释掉了。
