### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by bluebeach** [ant-design/ant-design-pro#890]
> ant-design-pro@1.1.0 start /Users/kongti.cj/Documents/Projects/antdPro
> cross-env DISABLE_ESLINT=true roadhog dev

/Users/kongti.cj/Documents/Projects/antdPro/node_modules/.1.1.0@graceful-process/index.js:6
module.exports = (options = {}) => {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kongti.cj/Documents/Projects/antdPro/node_modules/.2.2.0@roadhog/lib/roadhog.js:9:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! ant-design-pro@1.1.0 start: `cross-env DISABLE_ESLINT=true roadhog dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.1.0 start script 'cross-env DISABLE_ESLINT=true roadhog dev'.
npm ERR! This is most likely a problem with the ant-design-pro package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env DISABLE_ESLINT=true roadhog dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ant-design-pro
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ant-design-pro
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kongti.cj/Documents/Projects/antdPro/npm-debug.log

**Comment by bluebeach** [comment]
文件 /Users/kongti.cj/Documents/Projects/antdPro/npm-debug.log 里面的内容是

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ant-design-pro@1.1.0
6 info start ant-design-pro@1.1.0
7 verbose unsafe-perm in lifecycle true
8 info ant-design-pro@1.1.0 Failed to exec start script
9 verbose stack Error: ant-design-pro@1.1.0 start: `cross-env DISABLE_ESLINT=true roadhog dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ant-design-pro@1.1.0
11 verbose cwd /Users/kongti.cj/Documents/Projects/antdPro
12 error Darwin 15.6.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.6.1
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error ant-design-pro@1.1.0 start: `cross-env DISABLE_ESLINT=true roadhog dev`
17 error Exit status 1
18 error Failed at the ant-design-pro@1.1.0 start script 'cross-env DISABLE_ESLINT=true roadhog dev'.
18 error This is most likely a problem with the ant-design-pro package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env DISABLE_ESLINT=true roadhog dev
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ant-design-pro
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ant-design-pro
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by bluebeach** [comment]
后来好了，可能是本地环境问题

**Comment by Aggie123** [comment]
后来怎么好的呢 我这报同样的错误

**Comment by Aggie123** [comment]
找到原因了 是本地node版本的问题 切换到最新就OK了 给大家参考

**Comment by xoptimal** [comment]
怎么切换 , 我的是好好的没动过, 更新到SVN ,  其余没动过, 就不行了  @Aggie123

**Comment by Aggie123** [comment]
用nvm管理和切换node版本 @xoptimal

**Comment by chenshuai2144** [comment]
options = {} 这个东西是新版本的 node 才支持的
