### ISSUE TITLE
🧐[问题] Protable嵌套表格，request获取数据的子表格，有除actionRef外的刷新方式吗？

### ISSUE THREAD

**Issue by tanglonghai-0610** [ant-design/ant-design-pro#8901]
### 🧐 问题描述

嵌套表格，嵌套了多个子表格，父表格每行都有一个子表格，但是数据是动态获取的，子表格都是用的request方式获取数据。
![image](https://user-images.githubusercontent.com/80745901/128842276-608a8fb2-b119-4718-97ac-f43b16451dee.png)
页面效果和官网示例差不多，不同的是子表格我也有单独的新增等操作，想新增后只刷新指定的表格。
由于是动态获取数据，没办法确定父表行数，actionRef也没办法根据行数来声明初始化。想知道有没有除actionRef外的刷新方式

### 💻 示例代码
<ProTable
headerTitle={<span style={{fontSize:18, fontWeight: 'bold'}}>环境列表}
columns={eColumns}
actionRef={envActionRef}
params={{queryParams: envParams}}
request={getAllEnvironments}
rowKey="id"
bordered
pagination={{
showQuickJumper: true,
}}
expandable={{
expandedRowRender: record => nestDeviceTable(record),
}}
style={{ marginBottom: 16 }}
search={false}
/>

function nestDeviceTable(record: EnvironmentListItem) {
return (
<ProTable
headerTitle={<span style={{fontSize:16, fontWeight: 'bold'}}>{record.name}的设备列表}
actionRef={nestDeviceActionRef}
rowKey="id"
bordered
columns={dColumns}
search={false}
params={{envId: record.id}}
request={getDeviceByEnv}
pagination={false}
style={{ margin: 8 }}
toolBarRender={() => [
<Button
type="primary"
onClick={ () => {
setDModelVisible(true);
setCurrEnvRow(record);
}}
>

添加设备

]}
/>
);

**Comment by chenshuai2144** [comment]
你可以做个params
```
const [now]= useState(()=>Data.now())

<ProTable
   params={{now}}

```
params 修改也会触发重新更新

**Comment by tanglonghai-0610** [comment]
可以了，多谢
