### ISSUE TITLE
🐛[BUG]构建的新项目，没有侧边菜单

### ISSUE THREAD

**Issue by fangjie-luoxi** [ant-design/ant-design-pro#8902]
如标题所示，构建的新项目，没有侧边菜单
....怎么辣么多小问题呢

**Comment by TinsFox** [comment]
![image](https://user-images.githubusercontent.com/33956589/128959785-354e6253-0cb6-44b9-b57a-72892e548d2a.png)

如图所示请按照要求提交issues
怎么辣么多人不按照要求提issues
