### ISSUE TITLE
🧐[问题] antdpro5每1分钟会自动编译一次，

### ISSUE THREAD

**Issue by caijinchun** [ant-design/ant-design-pro#8903]
### 🧐 问题描述

每一分钟会自动编译一次，然后一编译界面就会刷新，导致根本无法调试。也不知道如何关闭，求助。
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13203309/128957885-e5fc263b-104a-44bf-880c-2433afeb89f4.png)

**Comment by TinsFox** [comment]
可以提供复现步骤跟复现仓库吗？刚刚试了一下挂了五分钟都不会自动编译

**Comment by caijinchun** [comment]
我找到原因了，我用了"@loadable/component"框架去热加载组件。用了这个就会出现一分钟编译一次的情况。
