### ISSUE TITLE
🧐[问题] 我想实现一个文件在线预览，怎么操作？ 

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#8904]
### 🧐 问题描述

我现在需要实现一个在线文件预览，可以提供文件存储地址，这个怎么操作？  Image标签我看只是针对图片的，无法针对其他的文件，比如pdf，不知道怎么办？

**Comment by TinsFox** [comment]
[react-pdf](https://www.npmjs.com/package/react-pdf)

**Comment by chenshuai2144** [comment]
还有一种办法是加钱。阿里云有文件预览服务，什么文件都支持
