### ISSUE TITLE
🐛[umi@2] 这个分支项目启动就报错

### ISSUE THREAD

**Issue by crush996** [ant-design/ant-design-pro#8905]
### 🐛 [umi@2] 这个分支项目启动就报错
![image](https://user-images.githubusercontent.com/69230517/128960016-642bf4c5-9836-41f6-a2d6-afe589594665.png)

里面的 routers    对象错误

**Comment by chenshuai2144** [comment]
太老了，尽量不要用了。
如果需要用建议锁包一下，这几年发生了很多的变化
