### ISSUE TITLE
`menuHeaderRender:false` not work

### ISSUE THREAD

**Issue by fungmo** [ant-design/ant-design-pro#8906]
### 🐛 bug 描述

To follow up the configuration in the preview, configuring `menuHeaderRender:false` in the project `defaultSettings.ts` does not work.

### 📷 复现步骤

```base
// config/defaultSettings.ts
menuHeaderRender:false
```

### 🏞 期望结果

Menu head hidden

### 💻 复现代码

```base
//config/defaultSettings.ts

import { Settings as LayoutSettings } from '@ant-design/pro-layout';

const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'dark',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'side',
  contentWidth: 'Fluid',
  splitMenus: false,
  fixedHeader: true,
  fixSiderbar: true,
  colorWeak: true,
  menuHeaderRender: false,
  headerRender: false,
  title: 'KPI',
  pwa: false,
  logo: 'logo.svg',
  iconfontUrl: '',
};

export default Settings;
```

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本 [3.5.0]
- 浏览器环境 [Chrome]
- 开发环境 [win10]

### 🚑 其他信息

i want:
![image](https://user-images.githubusercontent.com/16655229/128992996-92b68467-eecd-4ee2-857a-4dd2b6004d53.png)

reality：
![image](https://user-images.githubusercontent.com/16655229/128993183-a31e2e40-c47c-4ddc-86f3-b44b108899a8.png)

**Comment by chenshuai2144** [comment]
This function will only take effect in routing config
