### ISSUE TITLE
🧐[问题] npm run build的时候提示npx browserslist@latest --update-db

### ISSUE THREAD

**Issue by maplehsu** [ant-design/ant-design-pro#8907]
### 🧐 问题描述

npm run build 打包的时候在90%左右提示
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

根据操作 删除npm 包重新安装  或者更新都无效

**Comment by chenshuai2144** [comment]
忽略掉吧，这个东西要umi做改动，你改动没用的
