### ISSUE TITLE
🧐[问题]useRequest  好像后台只能用data的方式把值传过来。用HashMap的方式  key value的方式是可以传过来，

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#8908]
### 🧐 问题描述
useRequest  好像后台只能用data的方式把值传过来。用HashMap的方式  key value的方式是可以传过来，但是如果我要传递个值过来的时候，比如说list<HashMap<string,object>> 的方式好像不知道怎么拿值出来。

**Comment by sangyuren** [comment]
搞定了

**Comment by chenshuai2144** [comment]
把解决方案show 出来。帮助更多人
