### ISSUE TITLE
求问有暴露出<App />吗🧐[问题]

### ISSUE THREAD

**Issue by wjjhhh** [ant-design/ant-design-pro#8909]
### 🧐 问题描述

现在用react-query，希望是用ReactQueryConfigProvider包裹根元素，但发现app.tsx是配置型的，请问怎么处理

```
ReactDOM.render(
    <ReactQueryConfigProvider config={queryConfig}>
        <App />
    </ReactQueryConfigProvider>
    document.getElementById('root')
  );
```

**Comment by chenshuai2144** [comment]
试试lauyout的childrenRender 呢?，不行就在layout外面包一个layout。

https://pro.ant.design/zh-CN/docs/layout
