### ISSUE TITLE
动态路由使用menu的request属性登录第一次无法显示的问题🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8910]
### 🐛 bug 描述

使用layout的menu属性做动态路由，发现第一次登录后无法显示菜单，要刷新之后才能显示菜单
![image](https://user-images.githubusercontent.com/20655248/129133134-0f7e9faf-fa97-4f12-ba4a-a8e863b4b340.png)
![image](https://user-images.githubusercontent.com/20655248/129133280-4d1083a7-00d2-405f-a3c8-21786a610a3b.png)

![image](https://user-images.githubusercontent.com/20655248/129133338-b0e43523-bf23-49a3-9db9-1089d37b1f6d.png)
![image](https://user-images.githubusercontent.com/20655248/129133390-10a7d458-4985-4c6b-ab1d-e53f4f2cad6d.png)
![image](https://user-images.githubusercontent.com/20655248/129133459-b1c72152-0346-41b2-b077-5b888d6666d6.png)
![image](https://user-images.githubusercontent.com/20655248/129133482-b637dbc9-ccb2-4bce-9cde-c4bc15e018fc.png)
![image](https://user-images.githubusercontent.com/20655248/129133602-e82fc21b-e277-49e9-8dbf-88ed631eb7c8.png)
![image](https://user-images.githubusercontent.com/20655248/129133696-f2244314-a31e-454d-bd68-18c3594c1c2d.png)

为什么每次都是第一次登录之后没法显示动态路由，要刷新之后才能显示 每次重开一个页面都这样

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
可以layout设置一下params，不然layout是闭包的获取不到最新的数据。

**Comment by lovehebe330** [comment]
> 可以layout设置一下params，不然layout是闭包的获取不到最新的数据。

![image](https://user-images.githubusercontent.com/20655248/129325747-e709982a-fd27-4772-a0e9-0f916882a1bc.png)
这一块要如何改求教

**Comment by chenshuai2144** [comment]
类似这样的
```
export const layout =()=>{

return {
 menu: {
  params: initialstate?.username
 }
}
}
```

**Comment by lovehebe330** [comment]
> 类似这样的
> 
> ```
> export const layout =()=>{
> 
> return {
>  menu: {
>   params: initialstate?.username
>  }
> }
> }
> ```

![image](https://user-images.githubusercontent.com/20655248/129329174-5ad7d9f9-aae3-4d73-ace8-fd19cf2e6b16.png)
![image](https://user-images.githubusercontent.com/20655248/129329253-f4311533-4ba0-4c0b-9825-9d4c9a905474.png)
![image](https://user-images.githubusercontent.com/20655248/129329385-0ad4b412-d6ff-4a50-a236-56acd42279a4.png)
anzh按照亲的这个方式改 routes有数据但是依旧第一次没加载

**Comment by lovehebe330** [comment]
> 类似这样的
> 
> ```
> export const layout =()=>{
> 
> return {
>  menu: {
>   params: initialstate?.username
>  }
> }
> }
> ```

![image](https://user-images.githubusercontent.com/20655248/129337636-20c2db81-d7ea-453b-b257-0a589a074efd.png)
这样子可以了哟
