### ISSUE TITLE
🧐[问题] 我使用connect(({user})引入登录用户信息currentUser，在页面切换的时候，是正常的，登录用户信息可以正常的获取，但是当我刷新页面，发现currentUser为{}，这个是为什么？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#8911]
### 🧐 问题描述

我使用connect(({user})引入登录用户信息currentUser，在菜单切换的时候，是可以正常获取currentUser信息的，但是当我F5刷新页面时，发现currentUser为{}，这个是为什么？

### 💻 示例代码
const TableList = ({currentUser}) => {
...
useEffect(() => {
    console.log(currentUser);
  }, []);
...
};
export default connect(({user}) => ({
  currentUser: user.currentUser,
}))(TableList);

### 🚑 其他信息

正常切换菜单打印
![image](https://user-images.githubusercontent.com/29156872/129159049-e27f3e12-2bf6-42da-b8d7-5e98b260037b.png)

F5刷新页面
![image](https://user-images.githubusercontent.com/29156872/129159119-3e112e43-7c15-4b2d-9d2a-9884c284af1f.png)

**Comment by chenshuai2144** [comment]
刷新页面会清空所有堆栈，你要重新请求一下用户信息。

如果接口没查到问问后端是不是session没了
