### ISSUE TITLE
🧐Antd Pro 5 浏览器标题不能正确修改

### ISSUE THREAD

**Issue by imscorpioer** [ant-design/ant-design-pro#8913]
### 🧐 问题描述

在dev下配置没有问题，build之后title依然显示 欢迎-Ant Design Pro，已经修改了defaultSetting的title配置以及document.ejs中的title，跟踪了一下代码，build之后的setting不是我配置的那一份

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26703547/129166304-60cee593-2526-41e7-b45b-dff2e95da040.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/title-landing

看看这个文档
