### ISSUE TITLE
🐛[BUG]配置关闭时完全收起 menu，无法完全收起

### ISSUE THREAD

**Issue by gezhicui** [ant-design/ant-design-pro#8915]
### 🐛 bug 描述
配置关闭时完全收起 menu，无法完全收起
### 📷 复现步骤
参考 https://prolayout.ant.design/menu#%E5%85%B3%E9%97%AD%E6%97%B6%E5%AE%8C%E5%85%A8%E6%94%B6%E8%B5%B7-menu 一章，在代码中配置如下
![图片](https://user-images.githubusercontent.com/50941611/129318913-daf8a19f-c1ba-4f93-98df-ea0d53b0542c.png)

到页面中发现，内容元素已经顶到左侧，但是菜单宽度不为0
![图片](https://user-images.githubusercontent.com/50941611/129319063-4837ec52-b68c-450f-9a60-270a4d10e53b.png)

### 🏞 期望结果
菜单宽度能变成0隐藏

### © 版本信息

- Ant Design Pro 版本: V5
- umi 版本 3.5.0
- 浏览器环境  chrome 91.0.4472.114（正式版本）
- 开发环境 [e.g. mac OS] windows

**Comment by chenshuai2144** [comment]
直接render一个false就消失了，不过这种交互很鬼畜。不推荐使用

**Comment by gezhicui** [comment]
解决了，但是这样transition的效果没了  功能倒是实现了  谢谢了
