### ISSUE TITLE
🧐How to hide settings in url?

### ISSUE THREAD

**Issue by dinhbt** [ant-design/ant-design-pro#8916]
Hi all, I want hide settings in url https://preview.pro.ant.design/dashboard/analysis**?navTheme=realDark&primaryColor=sunset&fixedHeader=true&fixSiderbar=true**. Please help me this issue

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#settingdrawer



disableUrlParams | 禁止同步设置到查询参数 | boolean | false
-- | -- | -- | --

**Comment by yogithesymbian** [comment]
> https://procomponents.ant.design/components/layout#settingdrawer
> 
> disableUrlParams	禁止同步设置到查询参数	boolean	false
> soory，my English is poor

but its hide all params ... i looking for hide only setting params instead of params like `id` and `tabs=`
```
http://localhost:3000/dashboard/data-master/company?layout=mix&splitMenus=true&navTheme=realDark&siderMenuType=sub&colorPrimary=%23FAAD14&fixedHeader=true&tabs=Agent
```

these from setting drawers
```
layout=mix&splitMenus=true&navTheme=realDark&siderMenuType=sub&colorPrimary=%23FAAD14&fixedHeader=true&
```

from manual set by an interaction.
```
tabs=Agent
```

unExpected
```
http://localhost:3000/dashboard/data-master/company
```

expected
```
http://localhost:3000/dashboard/data-master/company?tabs=Agent
```
