### ISSUE TITLE
👑 [需求] splitMenus = true,一级菜单自定义

### ISSUE THREAD

**Issue by mayhai** [ant-design/ant-design-pro#8917]
### 🥰 需求描述
antd-pro V5 ，splitMenus =true模式下，想实现一级菜单自定义渲染，不知道大佬们有没有实现方案

**Comment by chenshuai2144** [comment]
menudata的第一排数组就是一级菜单，你可以自己拼接一下数据

**Comment by mayhai** [comment]
> menudata的第一排数组就是一级菜单，你可以自己拼接一下数据
不好意思  可能我没描述太清楚。
我的一级菜单自定义指的是在splitMenus 的时候 想自己重写一级菜单的结构，原框架内是平铺开来的 ，公司这边需求收缩起来。

**Comment by chenshuai2144** [comment]
这个不支持，你可能需要 headerRender 来自己定义了
