### ISSUE TITLE
🧐[问题] 想了解一下，表格列中的render，渲染的操作列key值是不是唯一的，如果重复了，会不会造成渲染性能的降低

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#8918]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13744175/129338729-0a418a59-9a8c-4e32-80d8-cea1962136f3.png)

**Comment by TinsFox** [comment]
这个应该是你去自定义一个唯一的值，用于virtual DOM的diff

**Comment by drizzlesconsin** [comment]
[文档: Key 值在**兄弟节点之间必须唯一**](https://zh-hans.reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings)

如果 Key 一样只会渲染一个组件。
