### ISSUE TITLE
🧐[问题]如何单独更改设置侧边导航栏滚动条样式？

### ISSUE THREAD

**Issue by WilliamFocus** [ant-design/ant-design-pro#8919]
### 🧐 问题描述
如何单独更改设置侧边导航栏滚动条样式？

如何单独更改设置侧边导航栏滚动条样式？
### 💻 示例代码
global.less设置全局样式没有效果

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/64114269/129342216-0f915f64-73a2-402d-85df-d2e114f168b7.png)

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Scrollbars
看这里
