### ISSUE TITLE
上传组件 upload 代理怎么设置

### ISSUE THREAD

**Issue by codercatmomi** [ant-design/ant-design-pro#892]
我的 组件里的配置是：
const uploadProps = {
  action: "/upload"
  name: 'Filedata'
}

请问是在 roadhogrc.mock.js
里 设置 
const proxy = {
   'POST /upload': "http://upload-api.***.com/upload.php/",
}

不起作用呀。求教。

**Comment by chenshuai2144** [comment]
可以试试这个
https://github.com/sorrycc/roadhog#proxy

**Comment by codercatmomi** [comment]
@chenshuai2144 这个也试了
报“Cannot POST /upload”的错

**Comment by chenshuai2144** [comment]
我看看你的配资

**Comment by codercatmomi** [comment]
你好，下面的codepen是直接在 upload的action里写完整连接，
结果是payload不能传不过去
https://codepen.io/codercat/pen/PQzvaa?editors=0010；


然后我换成代理的：
![image](https://user-images.githubusercontent.com/8371019/35851849-33bd0e70-0b64-11e8-8394-322795452953.png)
![Uploading image.png…]()
两种方法都用了。都不能成功的传给服务器；


@chenshuai2144

**Comment by chenshuai2144** [comment]
我这里成功了 返回了一个正在处理

**Comment by codercatmomi** [comment]
![image](https://user-images.githubusercontent.com/8371019/35852197-360bfc08-0b65-11e8-842e-4fa768ee263f.png)

这个是组件里的配置

**Comment by codercatmomi** [comment]
嗯。后端是php的。
“正在处理”表示   $_FILES['Filedata']  是null的。
就是前端图片没传过来

**Comment by chenshuai2144** [comment]
呃呃呃 ！ 我默认的api是返回一个url 。
https://ant.design/components/upload-cn/

**Comment by codercatmomi** [comment]
嗯 官网的例子
每次上传的时候都会请求 2次
https://jsonplaceholder.typicode.com/posts/

第一次是没有传参的。
第二次传参了，但是503

不知道官网的例子为什么会请求2次呢。
或者有没有真实的例子可以参考一下的？
感谢

**Comment by codercatmomi** [comment]
你好，感谢回复
请求data属性里填些什么内容呢

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/3148

**Comment by codercatmomi** [comment]
问题解决了
是代理的问题
在 .webpackrc里添加
"proxy": {
    "/upload": {
      "target": "http://upload-api......./upload.php",
      "changeOrigin": true
    }
  }

**Comment by chenshuai2144** [comment]
学习一个 markdown 语法

**Comment by fancyluo88** [comment]
如果需要同时上传附件、提交表单，大家是分两步还是一步直接完成呢？

**Comment by luoandy** [comment]
但是打包的话  代理这里就没用了啊

**Comment by LeeDou** [comment]
用upload上传了图片，然后提调表单希望只提交file返回数据中的一条后台数据，请问能怎么去处理呢？
