### ISSUE TITLE
🧐[问题] 如何在组件外(比如ProTable)得到其request到的数据

### ISSUE THREAD

**Issue by qiangxinglin** [ant-design/ant-design-pro#8920]
### 🧐 问题描述

自学中, 新手问题, 后端接口返回一个对象比如
```
{
  id: '0'
  name: 'Jack',
  department: [
    {
      id: '01',
      name: 'sale'
    },
    {
      id: '02',
      name: 'QA'
    },
  ]
}
```
我想把这个 `data.department` 用ProTable列出来, 然后在同一页面内访问其他属性比如 `data.name` 去做大标题等等,
 - 现在的做法是用 `useRequest` , 然后赋值给 `ProTable.datasource` , 但是感觉这样就浪费了表格自带的loading/reload, search form等功能,
 - 另外也尝试了用 `useState`, 然后在request中 `setData(res.data); res.data = res.data.department; return res` 返回给table以显示department

请问这种情形下的best practice是什么? 拆分数据成两个接口么, 一个返回 OneToOne 属性, 一个返回 OneToMany 属性么?

另一个问题, 我想在其他组件中得到ProTable的loading状态, 如何取得?

多谢不吝指教!

**Comment by chenshuai2144** [comment]
后端明显有问题。一个接口干一件事就好了，不要搞这么多黑科技。
