### ISSUE TITLE
🧐[问题]打包后产生多个目录，目录下会产生与dist根节点完全一致的index.html,其依据的来源是？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design-pro#8921]
### 🧐 问题描述
在打包后，会产生多个index.html文件，index.html的内容与dist根节点的index.html文件内容完全一致。请问下除dist根节点的index.html外，其他的index.html的来源是？
### 💻 示例代码
无
### 🚑 其他信息
![76A00573-F71A-49B4-811C-4A9BBBF11CA4](https://user-images.githubusercontent.com/16549630/129433137-9ac3677c-ffcd-4891-a25a-f7c883323887.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/config#exportstatic
这个功能
