### ISSUE TITLE
🐛[BUG] RTL direction not working properly in production build

### ISSUE THREAD

**Issue by ali4heydari** [ant-design/ant-design-pro#8923]
### 🐛 bug 描述
Go to https://pro.ant.design/ change language to فارسی and see the problem.

When you change the language to RTL language like Farsi dashboard drawer broken. This issue happens just in the production build. In a development build, the drawer shows in the correct position as expected.

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/29185622/129460380-ebc54e53-b0cb-4f04-8029-d9d7b150b7a2.png)

**Comment by chenshuai2144** [comment]
SettingDrawer does not support RTL, do you have time to do a pr？

**Comment by ali4heydari** [comment]
> in ant design when we are gonna change locale each component usually change `configProvider` for each component have you tried `configProvider` ? [somthing like this ](https://ant.design/components/config-provider/#API)

Yes, You can pass `direction` in `config.ts` file but not working.
