### ISSUE TITLE
🧐[问题] 下拉代码后执行npm install,无法启动项目,启动命令是: npm start

### ISSUE THREAD

**Issue by songshuai10** [ant-design/ant-design-pro#8924]
### 🧐 问题描述

下拉代码后执行npm install,无法启动项目,启动命令是: npm start

### 💻 示例代码

先下拉代码,执行:npm install
然后执行:npm start  就会报错了;错误代码如下;

> ant-design-pro@5.0.0-beta.2 start
> cross-env UMI_ENV=dev umi dev

Bundle with webpack 5...
🚀 Starting Umi UI using umi@3.5.17...
🌈 Umi UI mini Ready on port 3000.
Starting the development server...
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
    at Object.webpack (C:\data\2021\test\guanfang\myapp\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:138983:9)
    at Bundler.setupDevServerOpts (C:\data\2021\test\guanfang\myapp\node_modules\@umijs\bundler-webpack\lib\index.js:197:40)
    at C:\data\2021\test\guanfang\myapp\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:300:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\data\2021\test\guanfang\myapp\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:74:103)
    at _next (C:\data\2021\test\guanfang\myapp\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:76:194)
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/9507286/129474514-ff2b07d8-0b3c-47bf-a65f-9d67dfaf9a64.png)

**Comment by chenshuai2144** [comment]
去掉umi ui 吧，已经不维护了。
出了问题要自己的解决

**Comment by weypro** [comment]
可以试试删除src/.umi
