### ISSUE TITLE
如何兼容ie11 🧐[问题]

### ISSUE THREAD

**Issue by HaoAurora** [ant-design/ant-design-pro#8927]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/89005964/129524896-33b92ddd-6fa6-4fef-a59e-8eead263d2ef.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF

**Comment by lijile** [comment]
`// 注释这一行，否则ie11出现出现“无效字符”的错误
// esbuild: {},
// nodeModulesTransform: {
    // all和none，前者速度较慢，但可规避常见的兼容性等问题，后者反之。详见：https://umijs.org/zh-CN/config#nodemodulestransform
    type: process.env.NODE_ENV === 'development' ? 'all' : 'none',
  }`

**Comment by HaoAurora** [comment]
@lijile 修改后还是在报错呢
![image](https://user-images.githubusercontent.com/89005964/130427753-07111487-6cc6-4d92-ab21-e1229f72713a.png)

**Comment by lijile** [comment]
> @lijile 修改后还是在报错呢
> ![image](https://user-images.githubusercontent.com/89005964/130427753-07111487-6cc6-4d92-ab21-e1229f72713a.png)

我上面解决的是build发布阶段的，测试start阶段还需要注释这两个：
```
 // mfsu: {},
 //webpack5: {},
```
亲测可以运行

**Comment by HaoAurora** [comment]
@lijile  可以的。感谢

**Comment by ChineseEngineer** [comment]
我ie11下没有js报错，就是进入不了登录页面 一直显示按个loading的图标
