### ISSUE TITLE
非根目录部署--public下资源访问不到

### ISSUE THREAD

**Issue by jiaicon** [ant-design/ant-design-pro#8930]
如下图nginx配置，要部署到`/dist`路径下

![image](https://user-images.githubusercontent.com/34124517/129530580-07484227-3271-4087-8ddf-64e5b43f01bb.png)

项目可以访问，接口也正常，但是图片访问不到。
```
由于开发时使用的/images/xxx.png，所以就404了，该怎么配置图片才能正常访问？
```

umi配置如下：
![image](https://user-images.githubusercontent.com/34124517/129531287-31f55642-7c58-43e6-a71b-c50932205a9e.png)

**Comment by Davi-Wei** [comment]
试试，basePath: '/dist'

**Comment by jiaicon** [comment]
> 试试，basePath: '/dist'

![image](https://user-images.githubusercontent.com/34124517/129834033-0cfd8aae-1f1d-439a-8764-45c3cc0d8465.png)

basePath应该giab改变asset-manifest.json键值的，我理解会把资源地址重定向，但是我这里这个文件一直没起作用。

**Comment by chenshuai2144** [comment]
public 没走编译逻辑，只是单纯的copy，所以很多东西都不会生效的。
你看看自己的nginx 是怎么映射的。代码里改成相同的就能保证访问了
