### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by mayhai** [ant-design/ant-design-pro#8932]
### 🐛 bug 描述

actionRef手动更新initialState，无法在menu.request中取得最新initialState渲染菜单

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/31497480/129545893-62abd0dd-811b-449e-9eba-91d9c219d422.png)

![image](https://user-images.githubusercontent.com/31497480/129545806-e9e83e1b-4796-4330-99bb-ad2f277e6e11.png)

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/31497480/129544893-bbd742cb-d1c0-49b3-85f8-2a4e0dee6e03.png)

期望能在menu.request中拿到最新的initialState并刷新菜单

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. win10 ]

**Comment by mayhai** [comment]
![image](https://user-images.githubusercontent.com/31497480/129549879-dec26688-b07b-4b16-b452-dd7e925e26de.png)
用chenshuai大神的方法 透传params可以解决这个问题 感谢

**Comment by narutohinata** [comment]
> 

Good!
