### ISSUE TITLE
🧐[问题]optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors

### ISSUE THREAD

**Issue by langengel** [ant-design/ant-design-pro#8935]
<img width="880" alt="WX20210816-181727@2x" src="https://user-images.githubusercontent.com/59662045/129549273-d12c340f-c1dc-4dd0-8a53-1df73ae55273.png">
<img width="1152" alt="WX20210816-181810@2x" src="https://user-images.githubusercontent.com/59662045/129549300-bbc83ae8-d666-4e68-8bcb-967f06accd5c.png">

V5.0.0

(node:49331) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors(node:49331) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:49331) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
(node:49331) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

**Comment by chenshuai2144** [comment]
去 umi 提吧，这个不影响功能，只是对强迫症不友好
