### ISSUE TITLE
项目使用qiankun插件，分别有app1和app2，根目录使用yarn workspaces来管理node_modules

### ISSUE THREAD

**Issue by imscorpioer** [ant-design/ant-design-pro#8936]
### 🧐 问题描述

启动app1或者app2的时候，报找不到模块的错误，例如：@ant-design/icons ，@ant-design/pro-layout/es/PageLoading找不到，实际上在根目录已经安装了，这个问题要怎么处理，贴几个错误如下：

Module build failed (from ../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @ant-design/pro-layout/es/PageLoading which is imported from @/.umi/core/routes.ts

Module build failed (from ../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep moment/locale/zh-tw which is imported from @/.umi/plugin-locale/locale.tsx

Module build failed (from ../node_modules/@umijs/deps/compiled/babel-loader/index.js):
AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep @ant-design/icons/es/icons/TableOutlined which is imported from @/.umi/plugin-layout/icons.ts

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26703547/129554294-6f0f6cfa-7661-4334-8a58-d871fdaca42a.png)

**Comment by drizzlesconsin** [comment]
```bash
rm -rf src/.umi
yarn start
```
删掉重新跑试试

**Comment by imscorpioer** [comment]
> 删掉重新跑试试
3Q
1、把所有node_modules 以及.umi都删了，重新yarn，start，一样的错误
2、删除app2的.umi ， yarn start ，一样的错误

**Comment by chenshuai2144** [comment]
去umi或者qiankun问把，超过这个仓库的能力范围了
