### ISSUE TITLE
修改了defaultSettings里的primaryColor的主题颜色

### ISSUE THREAD

**Issue by immisso** [ant-design/ant-design-pro#8938]
### 🥰 需求描述
修改了defaultSettings里的primaryColor的主题颜色,但是并未生效,左边的菜单没有改变,按钮颜色也没有改变

我已经将primaryColor值`拂晓蓝`修改成了`#FA541C`,主题并未生效
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/27406707/129651900-3cde089a-9da0-4faf-886b-7c3071045eaa.png)

**Comment by chenqiushi** [comment]
+1 哪里不对呢？

**Comment by Davi-Wei** [comment]
primaryColor 并不会应用于左侧菜单，参考 /ant-design/components/style/themes/default.less，修改主题

**Comment by immisso** [comment]
> primaryColor 并不会应用于左侧菜单，参考 /ant-design/components/style/themes/default.less，修改主题
问题是以前的版本都是可以的嘛.这样会让我很头痛.

**Comment by chenshuai2144** [comment]
看看样式被谁覆盖了。是不是你引入了一些css ，没引入less

**Comment by immisso** [comment]
> 看看样式被谁覆盖了。是不是你引入了一些css ，没引入less

我还没有把新版本正式用在自己的项目上,不存在引入了一些css.而是我用`yarn create umi myapp`生成的脚手架就是这样.

**Comment by chenqiushi** [comment]
`npx create-umi myapp`  选择 simple 类型模板，初始化出来的脚手架项目，改 `primaryColor ` 配置不生效

**Comment by chenshuai2144** [comment]
mfsu 关掉吧。是mfsu导致的

**Comment by immisso** [comment]
> mfsu 关掉吧。是mfsu导致的，dev 有问题，。build 是没问题的

可以了，谢谢了

**Comment by florida0723** [comment]
/config/config.ts文件里面的mfsu: {},注释掉就可以了。

**Comment by szmetro2019** [comment]
1、在config.ts文件中新增配置
theme: {
  'primary-color': defaultSettings.primaryColor,
},
2、在global.less中配置，先引入@import '~antd/dist/antd.less';
@import '~antd/es/style/variable.less';
//新引入
@import '~antd/dist/antd.less';
3、在global.less最后加上@primary-color: #FA541C;使自己的样式覆盖原样式。
@primary-color: #FA541C;
