### ISSUE TITLE
关于左侧导航栏随页面一起滚动的样式问题

### ISSUE THREAD

**Issue by Xiangfs** [ant-design/ant-design-pro#894]
在学习和使用ant design pro的过程中，发现当页面过长的时候，用户滚动页面向下预览的时候，左侧菜单也会随着页面一起滚动，这样的话如果页面内容过多的时候用户滚动到底部的时候就不能切换菜单了。
从用户体验上来说，在滚动一段距离后，建议在右下角增加回到顶部的按钮~~
![image](https://user-images.githubusercontent.com/20461849/35838294-965031fa-0b25-11e8-8ac4-31a637f16483.png)

**Comment by chenshuai2144** [comment]
look #43
