### ISSUE TITLE
How to customize the background image of the exception page, such as the background image of the 404 page.

### ISSUE THREAD

**Issue by fungmo** [ant-design/ant-design-pro#8941]
### 🐛 bug 描述

I want to customize the background image of the exception page, but I can't find a method in the 404 page, nor in the docs. Can I only change it in node_modules?

### 📷 复现步骤

Steps not implemented

### 🏞 期望结果

fully custom

### 💻 复现代码

No reproducible code

### © 版本信息

- Ant Design Pro 版本: [^4.14.0]
- umi 版本 [^3.5.0]
- 浏览器环境 [Chrome]
- 开发环境 [Win 10]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/16655229/129689553-ac7e7c2a-ecbf-4053-becc-6fac4655cf8b.png)

**Comment by drizzlesconsin** [comment]
```tsx
// app.tsx
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    // customize 403
    unAccessible: <div>403</div>,
    // customize 404
    noFound: <div>404</div>,
  };
};
```

**Comment by fungmo** [comment]
@drizzlesconsin 
many thx
