### ISSUE TITLE
🧐[问题]v5中如何对内置布局的PageContainer参数进行设置

### ISSUE THREAD

**Issue by fangzhengjin** [ant-design/ant-design-pro#8942]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/12680972/129710720-621197f1-44c7-478c-ba74-56b0609e5cbf.png)
请问在v5版本中如果动态关闭这个标题的显示? 或者永久关闭?
目前好像没有看到暴露PageContainer的配置

**Comment by drizzlesconsin** [comment]
[DOC: API](https://procomponents.ant.design/components/page-container#api)

PageContainer 支持 Tabs 和 PageHeader 的所有属性。

header | [PageHeader](https://ant.design/components/page-header/) 的所有属性 | PageHeaderProps
-- | -- | --

**Comment by fangzhengjin** [comment]
> [DOC: API](https://procomponents.ant.design/components/page-container#api)
> 
> PageContainer 支持 Tabs 和 PageHeader 的所有属性。
> 
> header	[PageHeader](https://ant.design/components/page-header/) 的所有属性	PageHeaderProps

可能是我描述的不太清楚, 我的意思是在app.tsx中layout配置有没有能全局配置PageContainer的方法, 就比如在layout可以配置页面水印的属性透传一样

**Comment by drizzlesconsin** [comment]
把 `<PageContainer>` 封装一层再用吧

**Comment by fangzhengjin** [comment]
> 把 `<PageContainer>` 封装一层再用吧

目前除了单独挨个配置好像也只能这样了

**Comment by soeasyjx** [comment]
我也需要设置PageContainer 在app.tsx 中，有没有更简单的方式哈

**Comment by soeasyjx** [comment]
config.ts layout 属性设置pageTitleRender=false 可隐藏，但是标签还是有占位
