### ISSUE TITLE
npm start报错🐛[BUG]

### ISSUE THREAD

**Issue by xiaoheiweb** [ant-design/ant-design-pro#8943]
### 🐛 bug 描述
新拉取的项目运行直接报错

🚀 Starting Umi UI using umi@2.13.17...
⛽️ Ready on http://localhost:3000/
✖  error     [hardSource] is no longer valid. Please remove it from the configuration file.

Warning: umi-plugin-polyfills has been deprecated.
use config.targets instead.

Building dll...

✖ Webpack
  Compiled with some errors in 4.23s

 ERROR  Failed to compile with 1 errors                                                                                                                                                            下午9:07:21

This dependency was not found:

* @babel/runtime in dll umi

To install it, you can run: npm install --save @babel/runtime

 ERROR CODE  ERR_WEBPACK_DLL_MODULE_NOT_FOUND

 DETAILS 

## 错误原因

构建 dll 文件时出错了，由于 dependencies 下的依赖会全部被打到 dll 里，所以报错可能有以下原因：

    1. dependencies 里的某些依赖没有 main 文件
    2. 应该放在 devDependencies 里的 node 相关的依赖却写在了 dependencies

## 解决方案

让不该打到 dll 的不被打到 dll 里，有几个解决方案：

    1. 把 node 相关依赖放到 devDependencies 里
    2. 把出错的依赖配置到 dll 的 exclude 里

比如：

    dll: {
      exclude: ['foo']
    }
### 📷 复现步骤
$ git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project -b v2
$ cd my-project
npm install
npm start
报错

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by TinsFox** [comment]
这是v2版本？v5都出了，你这是在考古吗 😦

**Comment by chenshuai2144** [comment]
太老了，自行解决问题把

**Comment by gitSirzh** [comment]
@xiaoheiweb 你好，这个问题怎么解决的，方便发下吗
