### ISSUE TITLE
🐛[BUG] 分割线覆盖样式无效

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#8945]
### 🐛 bug 描述

'@divider-orientation-margin': '100%',

![IMG_20210817_223224](https://user-images.githubusercontent.com/3166799/129745798-04e10b56-3ebf-460c-8511-03f446a94e4b.jpg)
![IMG_20210817_223208](https://user-images.githubusercontent.com/3166799/129745817-44fa4518-6262-47b6-b8d8-3b1013a06f00.jpg)

**Comment by hihuangwei** [comment]
@afc163

**Comment by chenshuai2144** [comment]
是不是被覆盖了,来个重现把

**Comment by hihuangwei** [comment]
> 是不是被覆盖了,来个重现把

开启 MSFU 导致的
