### ISSUE TITLE
Source Maps not generating

### ISSUE THREAD

**Issue by sagarsoni7** [ant-design/ant-design-pro#8946]
Sorry if this has been asked before. I can't understand the language.

My app isn't generating source maps

<img width="954" alt="Screenshot 2021-08-18 at 10 31 48 AM" src="https://user-images.githubusercontent.com/29792913/129840115-537b1e39-f882-4c5d-b529-495a4c9af44e.png">

I've also tried setting `devtool: "source-map"` in config.ts

**Comment by chenshuai2144** [comment]
This is a side effect of MFSU. It is not true that the code does not generate a map
