### ISSUE TITLE
An error is reported when using umi-ui to build a template in antd-pro

### ISSUE THREAD

**Issue by fungmo** [ant-design/ant-design-pro#8947]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/16655229/129833730-1e4ebf1d-eff6-4275-9ca0-8ba0e1c7cb43.png)
![image](https://user-images.githubusercontent.com/16655229/129833762-d89ffb0f-f2c3-4eab-a403-6d8d343c90e7.png)

### 📷 复现步骤

step1. yarn create-umi my-app
step2. cd my-app
step3. yarn
step4. yarn add @umijs/preset-ui -D 
step5. select tmp and create tmp

### 🏞 期望结果

create succeeds without errors

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本 [^3.5.0]
- 浏览器环境 [Chrome]
- 开发环境 [Win 10]

**Comment by chenshuai2144** [comment]
已经不维护了，可能需要自行解决了
