### ISSUE TITLE
🧐[问题] swagger内的泛型没有如期转换，返回值类型得到了any

### ISSUE THREAD

**Issue by liuyang-kevin** [ant-design/ant-design-pro#8948]
### 🧐 问题描述
对于返回值，我们设计Body为`{status:string, msg:string, data: any}`，不知是我们swagger生成的不正确，还是不支持，期望得到正确的返回类型，

目前只有当没有data配置的类型，转化成了API.responseBody返回类型。
### 💻 示例代码
swagger
`"responses": {
          "200": {
            "description": "_",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/response.Body"
                },
                {
                  "properties": {
                    "data": {
                      "items": {
                        "$ref": "#/definitions/model.OrganizationAllInfo"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              ]
            }
          }
        }`

结果 
```
/** 机构列表 POST /admin/organization/all */
export async function organizationAll(
  params: {
    // path
  },
  options?: { [key: string]: any },
) {
  const { ...queryParams } = params;
  return request<any>('/admin/organization/all', {
    method: 'POST',
    params: { ...queryParams },
    ...(options || {}),
  });
}
```

**Comment by chenshuai2144** [comment]
看样子是个bug，swagger to ts 代码写的麻烦，有兴趣可以提个pr出来

**Comment by liuyang-kevin** [comment]
> 看样子是个bug，swagger to ts 代码写的麻烦，有兴趣可以提个pr出来
> 
> https://github.com/chenshuai2144/openapi2typescript
> 
> 代码在这里

方便的话大致说下运行流程。。看了一眼没文档，不知哪里运行测试方法。。

**Comment by liuyang-kevin** [comment]
pr已提，我是最近项目用ant，直接硬刚的代码。要是ts写的有问题，告诉我

```
/** 字典数据 POST /admin/util/data */
export async function utilData(options?: { [key: string]: any }) {
  return request<API.Body & { data?: API.UtilDataRet }>('/admin/util/data', {
    method: 'POST',
    ...(options || {}),
  });
}
```

**Comment by liuyang-kevin** [comment]
我们添加这个属性生成也没起效， `"x-swagger-router-controller": "psp"`
```json
		"/admin/util/admin": {
			"post": {
				"operationId": "util_admin",
				"responses": {
					"200": {
						"description": "_",
						"schema": {
							"allOf": [{
								"$ref": "#/definitions/response.Body"
							}, {
								"properties": {
									"data": {
										"$ref": "#/definitions/model.AdminInfo"
									}
								},
								"type": "object"
							}]
						}
					}
				},
				"summary": "登录信息",
				"tags": ["系统"],
				"x-swagger-router-controller": "psp"
			}
		},
```


对应代码处，我们改了一下

```ts
// 不知原来这里的  pathItem['x-swagger-router-controller'] 判断是不是有bug，还是有其它含义。
        // const tags = pathItem['x-swagger-router-controller']
        //   ? [pathItem['x-swagger-router-controller']]
        //   : operationObject.tags || [operationObject.operationId] || [
        //       p.replace('/', '').split('/')[1],
        //     ];

        const tags = operationObject['x-swagger-router-controller'] 
            ? [operationObject['x-swagger-router-controller']] 
            : operationObject.tags || [operationObject.operationId] || [ 
              p.replace('/', '').split('/')[1], 
            ];
```

我先用本地库。等回复

**Comment by chenshuai2144** [comment]
直接来pr吧。欢迎pr
