### ISSUE TITLE
🧐[问题]V4版本创建的项目，如果添加docker部署支持

### ISSUE THREAD

**Issue by xclw2000** [ant-design/ant-design-pro#8949]
### 🧐 问题描述

我的项目是V4版本创建的，时间比较久了，没有docker支持。
目录结构里没有docker目录，package.json里也没有docker相关的build命令。
现在想添加docker支持，如何实现？官方有没有如果进行docker部署的说明？

**Comment by chenshuai2144** [comment]
抄一下，docker 其实很简单。

核心就是nginx的配置
