### ISSUE TITLE
关于左侧菜单随页面滚动的一些建议

### ISSUE THREAD

**Issue by Xiangfs** [ant-design/ant-design-pro#895]
在学习和使用ant design pro的过程中，发现当页面内容过长的时候，用户滚动页面时菜单会跟着滚动，从用户体验角度来说应该让菜单固定住吧？
另外，建议在页面滚动超过一定距离后在右下角增加返回顶部的按钮。
![image](https://user-images.githubusercontent.com/20461849/35838771-e41db338-0b27-11e8-85b6-3a51afc8538e.png)

**Comment by pkaq** [comment]
这两个需求DIY一下很简单的 ：）

**Comment by Xiangfs** [comment]
哦哦~~框架内不对这块做限制了是吧~~了解了 : )
