### ISSUE TITLE
🧐[问题]protable分页的sort类型应该如何快速解析获取到排序字段

### ISSUE THREAD

**Issue by yyhLogin** [ant-design/ant-design-pro#8950]
### 🧐 问题描述
 /** @name 一个获得 dataSource 的方法 */
    request?: (params: U & {
        pageSize?: number;
        current?: number;
        keyword?: string;
    }, sort: Record<string, SortOrder>, filter: Record<string, React.ReactText[] | null>) => Promise<Partial<RequestData<T>>>;
这里的Record<string, SortOrder>怎么快速解析，方便我传输到后台呢

### 💻 示例代码
export async function queryLicense(
  params: BaseApi.PageParams,
  sort: Record<string, SortOrder>,
  options?: { [key: string]: any }
  ) {
  let sorts = "imei2";
  let isAsc = false;
  let imei2 = sort.imei2;
  if(imei2){
    isAsc = imei2.indexOf('asc') > -1;
  }else{
    imei2 = sort.imer1;
    if(imei2){
      sorts = "imei1";
      isAsc = imei2.indexOf('asc') > -1;
    }
  }
一个个字段去判断好像很繁琐，有人指点一下吗？这段代码我看着好难受

**Comment by chenshuai2144** [comment]
你让后端适应一下protable？ isAsc 的方式也好奇怪

xxx： asc

**Comment by yyhLogin** [comment]
相对于后端适应，更想知道Record<string, SortOrder>该如何快速解析，column都是未知的属性，很不方便解析拿到想要的数据，我试了一下也不知道后台该用什么类型去接收这个Record

**Comment by chenshuai2144** [comment]
Record 就是 object. 后端用map接收就可以。
export declare type SortOrder = 'descend' | 'ascend' | null;
