### ISSUE TITLE
🧐[问题]在document.ejs引入外部js，为什么只有刷新的情况下才会加载我要执行的部分

### ISSUE THREAD

**Issue by edifangyi** [ant-design/ant-design-pro#8951]
代码：

![image](https://user-images.githubusercontent.com/12421552/129898814-50b58551-1948-4164-8dd6-c1b9c0fa7040.png)

在document.ejs引入外部js后，我创建了一个组件。

![image](https://user-images.githubusercontent.com/12421552/129898960-36cf3bb9-5a5b-4d20-9191-a96a8f9917dc.png)
![image](https://user-images.githubusercontent.com/12421552/129898989-7fd2f50f-e095-4158-ba8e-65f7a4b0fcb7.png)

效果：

![image](https://user-images.githubusercontent.com/12421552/129899390-9db11e07-cb71-4019-84e6-034faa4cfe5d.png)

在刷新浏览器进入页面后，可以正常执行，
初始化 tinymce.init 并且selector: '#ssssssss', 关联下面的<textarea id="ssssssss" />。

但是在我进入其他页面在返回该页面，aaaa(); 一样会被执行，但是 tinymce.init没作用

![image](https://user-images.githubusercontent.com/12421552/129899478-e36dfd6c-e7a4-45d0-ad80-fc1862d3962c.png)

V5版本
![image](https://user-images.githubusercontent.com/12421552/129899944-11992071-f32b-4cc6-a1ec-a36d59fbb58d.png)

**Comment by edifangyi** [comment]
selector 我写错了，不好意思

**Comment by SuperBaBa** [comment]
我一开始还以为要用useEffect引入外部js，原来在ejs模板里面就可以了
