### ISSUE TITLE
🧐[问题] ProLayout 多个路由对应一个菜单项好像无法生效，求助

### ISSUE THREAD

**Issue by houkunlin** [ant-design/ant-design-pro#8956]
### 🧐 问题描述

参照 pro-layout 组件的文档尝试使用 【多个路由对应一个菜单项】 功能，在 pro 下好像无法生效
文档地址：https://procomponents.ant.design/components/layout#%E5%A4%9A%E4%B8%AA%E8%B7%AF%E7%94%B1%E5%AF%B9%E5%BA%94%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95%E9%A1%B9
代码版本：当前的master分支，其余的配置没有变
依赖变动：`"@ant-design/pro-layout": "^6.24.1"`
我的代码仓库：https://gitee.com/houkunlin/wake-on-lan-web   （由于编译失败，下方截图的变动信息并未上传到仓库中）

### 💻 示例代码
原始 routes.ts 文件配置：
![image](https://user-images.githubusercontent.com/12333292/130032767-277f2a5d-7e05-47e5-b718-c1c0d86307f5.png)

生成的 src/.umi/core/routes.ts 文件内容：
![image](https://user-images.githubusercontent.com/12333292/130032866-feae2ea0-181a-4b9c-b422-e23ecc2732b8.png)

**Comment by chenshuai2144** [comment]
这是什么东西？

indexRouter 这个我还没写过

**Comment by houkunlin** [comment]
@chenshuai2144 我也是在 ProLayout 文档里面看到有这个东西的
 https://procomponents.ant.design/components/layout


![image](https://user-images.githubusercontent.com/12333292/130056271-56f7829d-7e5a-4fbf-85a6-b2773c86c71b.png)

**Comment by chenshuai2144** [comment]
看样子demo，copy出问题了，这东西看着像废弃了。你只要保证的路由是父子的就能选中同一个菜单

**Comment by houkunlin** [comment]
@chenshuai2144 
我目前想要就是同一个菜单能够对应多个页面，就跟文档中描述的大致一样。例如一个功能的列表页、表单页、详情页都想要只保证一个菜单。
我目前的解决方案是下面这样的：
![image](https://user-images.githubusercontent.com/12333292/130057466-a9444adf-ac69-4315-98ae-8a909b9f0921.png)

我需要在我的列表页对props进行判断；今天无意间看到 ProLayout 文档里面好像有类似的这样一个功能，然后就想着试一下，结果发现是没有用，因此才来问一下的

**Comment by chenshuai2144** [comment]
用路由参数+判断吧，这个需求太奇怪了。

/product/:type


/product/new 新建
  
/product/list 列表这样的
