### ISSUE TITLE
🧐[问题]大家有没有遇到自定义组件，有时候会导致无法热更新。

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#8958]
### 🧐 问题描述

我在　components　目录下定义了一些自定义组件。然后在别的地方调用，功能正常，就是间歇性无法热更新。有可能A页面调用不更新，但是B页面调用又更新。但只要不调用一切又正常会自动热更新它。控制台也不报错，完全摸不着头脑是因为什么问题导致不更新的。排查都没得办法排查。哪怕是写一个简单的
```
export default = ()=> <div>123</div>
```
都会可能导致无法热更新，只能手动刷新它。

**Comment by drizzlesconsin** [comment]
[快速刷新（Fast Refresh）技巧](https://umijs.org/docs/fast-refresh#%E6%8A%80%E5%B7%A7)

**Comment by codedart2018** [comment]
> [快速刷新（Fast Refresh）技巧](https://umijs.org/docs/fast-refresh#%E6%8A%80%E5%B7%A7)

fastRefresh 是开启的，折腾好久我把 mfsu: {} 关掉后就能热更新，只是热更新的时候会导致界面抖动而已，如果开启的话就不能热更新。删除什么.umi这些都没办法。那看来还是mfsu的问题的。

**Comment by HengCC** [comment]
> ### 🧐 问题描述
> 我在　components　目录下定义了一些自定义组件。然后在别的地方调用，功能正常，就是间歇性无法热更新。有可能A页面调用不更新，但是B页面调用又更新。但只要不调用一切又正常会自动热更新它。控制台也不报错，完全摸不着头脑是因为什么问题导致不更新的。排查都没得办法排查。哪怕是写一个简单的
> 
> ```
> export default = ()=> <div>123</div>
> ```
> 
> 都会可能导致无法热更新，只能手动刷新它。

我觉得这块可能是不是和fastRefresh以及mfsu的刷新机制有关.  关掉其中任何一个都可以保持一直更新.  2个都开启的情况下会概率性的在某些页面出现不更新的情况. 尤其是这个里面提到的组件(组件啥内容都没 , 就是静态内容. 但是内容变更后不会导致页面刷新和变化). 这块的机制不太清楚是什么原因.
