### ISSUE TITLE
ant-design-pro Pie组件的title属性无效；

### ISSUE THREAD

**Issue by duanliang** [ant-design/ant-design-pro#896]
ant-design-pro Pie组件的title属性无效；
![image](https://user-images.githubusercontent.com/13715221/35841667-254d0e52-0b38-11e8-8c87-ce80fb32f66d.png)

**Comment by duanliang** [comment]
失误，点错了；

**Comment by nikogu** [comment]
https://pro.ant.design/docs/use-components-alone-cn#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

独立使用 pro 的组件是需要引入样式的。

**Comment by duanliang** [comment]
![image](https://user-images.githubusercontent.com/13715221/35852974-4a5026b0-0b67-11e8-9c43-b44dd0a3a88b.png)
我想说的是<Pie>组件的title属性没有效果，样式引入了，还是有不显示出来；

**Comment by nikogu** [comment]
@duanliang 不好意思，误解了你的意思，是的，在 `percent` 模式下，title 是不显示的，这个我们后面在文档上说明下。
