### ISSUE TITLE
👑 [需求]

### ISSUE THREAD

**Issue by a8655099449** [ant-design/ant-design-pro#8960]
### 🥰 目录结构文档和实际构建有出入
[文档中的目录结构](https://pro.ant.design/zh-CN/docs/folder)在最新构建出来的项目有出入

### 🧐 解决方案

请及时更新文档
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/58685483/130173780-180dff5f-1e8a-4212-a209-01d0452d79a3.png)

**Comment by chengzi-code** [comment]
layout 已经改成插件式的了，当初找了半天，还以为项目克隆错了，笑死

**Comment by BongBongBang** [comment]
> layout 已经改成插件式的了，当初找了半天，还以为项目克隆错了，笑死

你好，请问你提到的Layout是用来动态配置Menu的配置嘛？我按照文档在src/app.tsx中进行配置，结果报layout不是有效的plugin key异常。。。
