### ISSUE TITLE
🧐[问题]v5 是不是不能用自由的添加umi 区块了？

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#8961]
### 🧐 问题描述
安装了V5基础版本，然后也安装了umi小气泡，但仍然不能安装任何区块。手动npm run fetch:blocks 安装报异常。npx umi block add EditorFlow 也异常。

### 💻 示例代码
PS D:\Source\js\VisualCodeProjects\test\myapp1> npm run fetch:blocks
npm ERR! missing script: fetch:blocks

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-08-20T06_47_36_681Z-debug.log

**Comment by chenshuai2144** [comment]
是停止维护了，导致很多功能都异常了。
如果有兴趣可以帮忙维护
