### ISSUE TITLE
👑 [需求]proTable 的工具栏位置默认在右边，能否改成传统的从最左边开始排序

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#8963]
### 🥰 需求描述 [详细地描述需求，让大家都能理解]
proTable 的工具栏位置默认在右边，能否改成传统的从最左边开始排序
![image](https://user-images.githubusercontent.com/857669/129875634-c09f249a-3d20-4332-93d4-15c95c59dfff.png)

**Comment by github262302** [comment]
css

**Comment by chenshuai2144** [comment]
不要搞微创新，没有意义。
