### ISSUE TITLE
👑 [需求] 选择数据较大（20条记录，17列）的时候，渲染比较慢（服务器返回的数据很快，只是在渲染的时候要等好几秒中

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#8964]
# 🐛  

>  ## **问题: 选择数据较大（20条记录，17列）的时候，渲染比较慢（服务器返回的数据很快，只是在渲染的时候要等好几秒中）**
## 🏞 1. 代码截图:
![image](https://user-images.githubusercontent.com/13744175/130233606-84c62052-9fa2-49e3-a501-2052f3a811b4.png)
## 🏞 2. 操作截图:选择20条/页的时候也很慢，感觉数据不多呢
![image](https://user-images.githubusercontent.com/13744175/130233173-e1b8ce3c-35b4-4413-81e2-b44d941162c8.png)
## 3.就连选中的复选框，都要停顿一下的
![image](https://user-images.githubusercontent.com/13744175/130330596-e544073a-df2b-43af-8e2c-dbced1e16cf2.png)

### © 版本信息

- Ant Design Pro 版本: [5.0.0-beta.3]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

```
{
  "name": "ant-design-pro",
  "version": "5.0.0-beta.3",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
```

## 这是没有配置正确呢，还是该怎么处理呀

**Comment by 569202812** [comment]
数据大了就是很慢，可以换个性能高点的表格

**Comment by fangqibin** [comment]
需要展示出来的才渲染dom，没有展示出来的不要渲染出来

**Comment by dhbyls** [comment]
> 数据大了就是很慢，可以换个性能高点的表格

10条记录，17列，不多吧😮‍💨，这样也卡呀，哎

**Comment by Yuaao** [comment]
最后咋解决的呀我也遇到这种问题了，我渲染500条分页页面直接挂了

**Comment by chenshuai2144** [comment]
https://ant.design/components/table-cn/#components-table-demo-virtual-list

试试这个
