### ISSUE TITLE
👑 [需求] 添加多多标签页的支持

### ISSUE THREAD

**Issue by wxq851685279** [ant-design/ant-design-pro#8965]
![image](https://user-images.githubusercontent.com/29041799/130338507-40af302a-16f5-41ec-a404-df750ca32000.png)

**Comment by jc1102** [comment]
我也要！

**Comment by CHENJKNB** [comment]
一楼的 大佬能发一份源码吗？

**Comment by chenshuai2144** [comment]
在历史issue 里面讨论吧

**Comment by phoema** [comment]
别关呀，我看到多标签就激动了。

**Comment by buxinren** [comment]
大佬，多标签的这个搞好了吗？

**Comment by buxinren** [comment]
求多标签

**Comment by buxinren** [comment]
@我看了一下，能不能加个Q什么的。像您请教一下

**Comment by ajunc** [comment]
> @buxinren. 可以使用这个插件 https://github.com/fangzhengjin/umi-plugin-panel-tabs

有用谢谢，作者说最好TS，但我用js弄的antd pro 5好像也可以运行

**Comment by buxinren** [comment]
你好。这个我当时有尝试过。但是不知道会不会有bug,所以没有用在项目上。感谢老师的分享。谢谢。你那面运用在项目上怎么样



在 2022-02-09 15:33:43，"ajunc" ***@***.***> 写道：

@buxinren. 可以使用这个插件 https://github.com/fangzhengjin/umi-plugin-panel-tabs

有用谢谢，作者说最好TS，但我用js弄的antd pro 5好像也可以运行

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by topwood** [comment]
能给这功能跪下

**Comment by lifegit** [comment]
> #220

你这个图是什么系统截的图？

**Comment by ajunc** [comment]
> 你好。这个我当时有尝试过。但是不知道会不会有bug,所以没有用在项目上。感谢老师的分享。谢谢。你那面运用在项目上怎么样 在 2022-02-09 15:33:43，"ajunc" ***@***.***> 写道： @buxinren. 可以使用这个插件 https://github.com/fangzhengjin/umi-plugin-panel-tabs 有用谢谢，作者说最好TS，但我用js弄的antd pro 5好像也可以运行 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

抱歉，刚看到，项目上线很久了，closeTag的时候会出现卡顿和无法关闭的情况，我这是做了特殊处理没有使用close tab。其它没问题
