### ISSUE TITLE
🐛[BUG] `npm run build` 还会出现配置栏

### ISSUE THREAD

**Issue by alvinlee001** [ant-design/ant-design-pro#8968]
### 🐛 `npm run build` 还会出现配置栏

在 `npm run build` 以后，deploy 到 nginx, 会有配置栏， "配置栏只在开发环境用于预览，生产环境不会展现，请拷贝后手动修改配置文件"， 没有保存config.ts 的设定。

![image](https://user-images.githubusercontent.com/20808288/130376938-e0839316-6c63-4cca-bf5f-cbecac4f6571.png)

### 📷 复现步骤

在 `npm run build` 以后，deploy 到 nginx, 会有配置栏， "配置栏只在开发环境用于预览，生产环境不会展现，请拷贝后手动修改配置文件"， 
### 🏞 期望结果

UI 会有 config.ts 的设定。 配置栏不会被显示。

### 💻 复现代码

config.ts

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本
- 浏览器环境： chrome
- 开发环境： mac OS

**Comment by Swallower** [comment]
我也遇到这个问题了 build 命令中环境变量改了挺多次也没能在线上消除配置栏

**Comment by Swallower** [comment]
1. 

- [ ] 123

- 1. 123

**Comment by Swallower** [comment]
`ssd`

**Comment by CatNulls** [comment]
@alvinlee001 可通过移除依赖项中的umi-plugin-setting-drawer来解决该问题

**Comment by alvinlee001** [comment]
> @alvinlee001 可通过移除依赖项中的umi-plugin-setting-drawer来解决该问题

可以多说明吗？不好意思我程序员普通话不太好。那个file 需要更换那个地方？ 谢谢

**Comment by CatNulls** [comment]
> > @alvinlee001 可通过移除依赖项中的umi-plugin-setting-drawer来解决该问题
> 
> 可以多说明吗？不好意思我程序员普通话不太好。那个file 需要更换那个地方？ 谢谢

package.json 中 dependencies 下 umi-plugin-setting-drawer

```bash
 // 通过yarn
 yarn remove umi-plugin-setting-drawer
 // 或 通过 npm
 npm uninstall umi-plugin-setting-drawer
```

**Comment by Swallower** [comment]
@CatNulls   给你点个赞 ，package.json里直接删除 依赖就好了

**Comment by chengluliu** [comment]
除了删除依赖就目前没有办法了吧?
