### ISSUE TITLE
🧐[问题] 如何引用本地的JS文件？

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#8970]
### 🧐 问题描述

如何引用本地的JS文件？
src/assets/custmo.js
怎样在项目里引用这个文件，访问这里的变量？
document.ejs 里添加引用 <script  src="./assets/protocolcheck.js"/>，在控制台查看无法加载。

### 💻 示例代码
    <title>Ant Design Pro</title>
    <link rel="icon" href="<%= context.config.publicPath +'favicon.ico'%>" type="image/x-icon" />
    <script  src="./assets/protocolcheck.js"/>
  </head>

**Comment by 569202812** [comment]
使用 CommonJS 或者 ES6 Module 引用吧

**Comment by algz** [comment]
> 使用 CommonJS 或者 ES6 Module 引用吧

举个例子吧。

**Comment by 569202812** [comment]
[export导出](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/export)
[import导入](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/import) 

[commonjs 导入导出](http://nodejs.cn/api/modules.html)
