### ISSUE TITLE
🐛[BUG]请求地址异常

### ISSUE THREAD

**Issue by cmy9068** [ant-design/ant-design-pro#8974]
### 🐛 bug 描述

请求地址是/api/user/login时服务端收到的请求路径不正确，改成其他的就正常了。

### 📷 复现步骤

![1629708885(1)](https://user-images.githubusercontent.com/28939517/130419369-4401e737-9480-4c88-81de-cee6f6771067.png)
![1629708906(1)](https://user-images.githubusercontent.com/28939517/130419428-124a28b6-4064-4b70-b9bb-220b83d5c524.png)
![1629708939(1)](https://user-images.githubusercontent.com/28939517/130419504-c1be4df0-583a-4d3c-bb24-6fedeacd570f.png)

### 🏞 期望结果

服务端应该收到正确的请求路径/user/login；
如果修改请求地址为其他的，则一切正常。不知为何/user/login会自动变成/user/user/login

**Comment by chengzequn** [comment]
看你herders里的请求链接

**Comment by fangqibin** [comment]
如果修改请求地址为其他的这句话是什么意思？还有header可以截图看看。

**Comment by cmy9068** [comment]
![1629711636(1)](https://user-images.githubusercontent.com/28939517/130426068-cf71c396-f137-428d-9bb2-f93b1ee64f9c.png)
修改成其他的意思是：比如修改成/api/user/login1或者/api/account/login，服务端都能正常响应，请求路径就是正确的。

**Comment by cmy9068** [comment]
请求路径/api/user/login通过proxy代理后，请求路径就变成了/user/user/login，很是纳闷儿。

**Comment by fangqibin** [comment]
> 请求路径/api/user/login通过proxy代理后，请求路径就变成了/user/user/login，很是纳闷儿。

![image](https://user-images.githubusercontent.com/15991882/130426697-a007f7a9-9e9d-4354-bc24-aecbae891894.png)
我看你上面的截图是没有错的。

**Comment by chengzequn** [comment]
根据你的截图，x-real-url是没有错的，会不会是你的后端写的有问题？

**Comment by cmy9068** [comment]
请求的是/api/user/login，通过proxy代理后，服务端实际收到的请求路径就变成了/user/user/login，正常应该是/user/login。不知道我这样描述是否能明白。

**Comment by fangqibin** [comment]
> 请求的是/api/user/login，通过proxy代理后，服务端实际收到的请求路径就变成了/user/user/login，正常应该是/user/login。不知道我这样描述是否能明白。

你可以直接访问这个地址正不正常
![image](https://user-images.githubusercontent.com/15991882/130427054-4b9e6422-7d5c-4713-97cd-7c1a6b65a730.png)

**Comment by cmy9068** [comment]
![image](https://user-images.githubusercontent.com/28939517/130427066-aff9e171-9109-40dd-b92e-fc2c5a117d7a.png)
正常用浏览器请求地址完全正常，说明服务端没有错。

**Comment by chengzequn** [comment]
> 请求的是/api/user/login，通过proxy代理后，服务端实际收到的请求路径就变成了/user/user/login，正常应该是/user/login。不知道我这样描述是否能明白。

根据你的header截图里的x-real-url可知实际请求的路径就是http://127.0.0.1:8888/user/login,所以感jio是你后端的问题，有postman吗试一下，你的请求应该是post吧，浏览器地址栏访问为get

**Comment by cmy9068** [comment]
嗯，我再试试，非常感谢你们，ant-design越来越好。

**Comment by chengzequn** [comment]
根据你header的响应状态200,可知你请求成功了。至于返回的响应体，这个是你后端自定义的响应，着重看一下你后端的请求拦截。
