### ISSUE TITLE
🧐[问题]怎样在ant-design-pro 怎样声明和引用全局变量？

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#8975]
### 🧐 问题描述
引用外部的JS文件，怎样定义成一个全局变量在访问？
<script  src="./assets/protocolcheck.js"/>
...
window.protocolcheck(url);
虽然这样使用变量没有问题，但visual Code tsx语法提示有问题。
怎样在ant-design-pro 引用外部变量？

**Comment by drizzlesconsin** [comment]
```ts
// src/typings.d.ts

declare interface Window {
  protocolcheck: any;
}
```

**Comment by algz** [comment]
> ```ts
> // src/typings.d.ts
> 
> declare interface Window {
>   protocolcheck: any;
> }
> ```

thanks
