### ISSUE TITLE
ant design有那种企业级的pc端官网模板吗 非ant design pro那种🧐[问题]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#8976]
### 🧐 问题描述

 像https://open.alipay.com/channel/miniIndex.htm 支付宝小程序这种企业级公司介绍官网模板 ，ant design有吗？ 非ant design pro那种企业级后台模板

**Comment by drizzlesconsin** [comment]
[landing.ant.design](https://landing.ant.design/)
