### ISSUE TITLE
🐛[BUG] /editor/flow 流程图编辑打开后，提示 Unhandled Rejection (TypeError): Cannot read property 'Canvas' of undefined

### ISSUE THREAD

**Issue by yibey** [ant-design/ant-design-pro#8982]
### 📷 复现步骤

按照官网下载运行V5版本的typescript 完整版，后点击了 图形编辑器=》流程图编辑器

### 🏞 期望结果

官网样例一样不会出错

### © 版本信息

- Ant Design Pro 版本: [5]
- umi 版本
- 浏览器环境
- 开发环境 [windows 10]

### 🚑 其他信息

![1629776373(1)](https://user-images.githubusercontent.com/20527603/130552236-c3f2830c-63fb-434b-968d-dad338d4f309.jpg)

**Comment by sendy943** [comment]
同样问题

**Comment by sendy943** [comment]
遇到同样的问题，解决不了

**Comment by chenshuai2144** [comment]
换成用 x6 吧， 这个停止维护了。

https://x6.antv.vision/zh/
