### ISSUE TITLE
🧐[问题] ProTable 中的search optionConfig 配置自定义按钮，设置搜索按钮和重置按钮样式，自定义的重置，无法正常刷新，麻烦问下怎么解决

### ISSUE THREAD

**Issue by DomeSy** [ant-design/ant-design-pro#8983]
### 🧐 问题描述
想要设置下 ProTable 搜索的重置按钮样式，所以在 optionConfig 重写了下按钮样式，发现刷新请求表格的时候，参数还是带入了搜索时的param，（注：搜索栏的以清空）

### 💻 示例代码
点击重置后 desc 还在
建议可以增加搜索按钮和重置按钮的其他属性解决

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/41473452/130558572-e6436b98-8174-4824-b816-cd7baf94bbc9.png)
![image](https://user-images.githubusercontent.com/41473452/130558635-811190ce-59ac-4e7d-88a4-452571891b8b.png)

**Comment by chenshuai2144** [comment]
执行一下` formRef.current?.submit()`

**Comment by yxwhb** [comment]
哥 你怎么解决的啊 我今天也遇到这个问题了
