### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by kevinsheep** [ant-design/ant-design-pro#8984]
### 🧐 问题描述
如官方文档，已知Menu组件会渲染两次：[https://ant.design/components/menu-cn/#FAQ](https://ant.design/components/menu-cn/#FAQ)
但那是在使用本地路由配置的情况。
如果是远程请求路由的情况，渲染次数会变成**四次**。

### 💻 示例代码
app.tsx 中，自定义 `menuRender` `menuItemRender` `subMenuItemRender`，console输出任意的内容；
当 menu 为本地路由，menu 的console的内容是两份，菜单项则是菜单数量x2，与已知情况一致；
当使用远程获取时，菜单项则是x4；
如果菜单规模较大时，这个渲染速度多少会受影响。

``` JavaScript
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    // ...other configuations
    menu: {
      request: async () => {
        // await backend service()
        return routes;
      },
    },
    menuRender: (menu, defaultDom) => {
      console.log({ menu });
      return defaultDom;
    },
    subMenuItemRender: (subitem, defaultDom) => {
      console.log({ subitem });
      return defaultDom;
    },
}
```

### 🚑 其他信息
![本地路由](https://user-images.githubusercontent.com/765608/130590155-76a3e85a-068e-419d-886d-b0b87188a2fc.png)

![远程路由](https://user-images.githubusercontent.com/765608/130590359-ba460e25-938c-4267-87b0-92a4914a32c2.png)

**Comment by sunbeam512** [comment]
为什么渲染了三次 ？？
