### ISSUE TITLE
🐛[BUG] 使用antd的Form组件后，开发环境正常显示，生产环境报错且页面一直处于loading状态

### ISSUE THREAD

**Issue by german4848** [ant-design/ant-design-pro#8986]
### 🐛 bug 描述

使用antd的Form组件后，开发环境正常显示，生产环境报错且页面一直处于loading状态。
显示报错
![image](https://user-images.githubusercontent.com/32978563/130594061-70c8d51d-f6e6-44ef-a8e7-11413ee1516d.png)

### 📷 复现步骤

使用antd的Form组件

### 🏞 期望结果

生产环境可以正常使用Form

### 💻 复现代码
![image](https://user-images.githubusercontent.com/32978563/130597051-a9ec77bc-57e7-439d-b745-4b4a5c58ff4f.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本[e.g. 3.5.0]
- 浏览器环境
- 开发环境 [window]

### 🚑 其他信息

暂无

**Comment by chenshuai2144** [comment]
和form 应该没有关系的，你搞个复现吧，这种的一般是js分包加载失败了

**Comment by german4848** [comment]
> 和form 应该没有关系的，你搞个复现吧，这种的一般是js分包加载失败了

https://github.com/german4848/antdPro-Form/archive/refs/heads/master.zip(项目压缩包地址)
你好,这是使用直接使用antdPro脚手架，并未新增任何页面功能（初始化状态）。在src\pages\Welcome.jsx，使用了Form组件，本地启动并无问题，但打包部署后，会处于loading状态。

**Comment by german4848** [comment]
> Hello @german4848. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
> 
> 你好 @german4848, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://github.com/german4848/antdPro-Form/archive/refs/heads/master.zip(项目压缩包地址)
你好,这是使用直接使用antdPro脚手架，并未新增任何页面功能（初始化状态）。在src\pages\Welcome.jsx，使用了Form组件，本地启动并无问题，但打包部署后，会处于loading状态。

**Comment by c-ujung** [comment]
贴出一个在线重现例子吧

**Comment by chenshuai2144** [comment]
我用 nginx 试了是没问题，估计是你们的部署环境有什么特殊的把。最好能给个线上的再现
