### ISSUE TITLE
关于嵌套表格 + 表格合并类问题

### ISSUE THREAD

**Issue by Nicolelll** [ant-design/ant-design-pro#899]
如果默认选择defaultExpandAllRows(默认展开所有行) 退出页面 再回到表格页面时会发生页面错乱
![image](https://user-images.githubusercontent.com/29426229/35847670-2ad9b62c-0b56-11e8-8445-da012bf3901b.png)
需要刷新之后才会恢复# #

**Comment by ddcat1115** [comment]
单纯的 antd 组件使用问题请到这里咨询 https://github.com/ant-design/ant-design/issues

并且需要提供在线可重现 demo，可以fork  https://u.ant.design/codesandbox-repro
