### ISSUE TITLE
面包屑点击跳转问题

### ISSUE THREAD

**Issue by WangXinQS** [ant-design/ant-design-pro#8992]
### 🧐 问题描述
为什么面包屑的点击是重新刷新了整个页面，而不是像Link一样以路由方式跳转。

### 🚑 其他信息

使用的文档中的示例
![image](https://user-images.githubusercontent.com/51841234/130729031-df0165d7-b5f3-4dc0-b252-a69c107e6c15.png)

**Comment by chenshuai2144** [comment]
```
  breadcrumbProps: {
      itemRender:()=><Link/>
    },
```

在layout 中，自定义配置一下
