### ISSUE TITLE
🧐[求帮助]从后端动态获取路由参数如何实现？

### ISSUE THREAD

**Issue by cmy9068** [ant-design/ant-design-pro#8994]
### 🧐 问题描述

菜单从后端获取文档上有说明，但是routes路由如何做到从后端动态获取？
也就是/config/routes.ts文件中的内容需要从后端动态获取。

### 🚑 其他信息
![企业微信截图_16298812787337](https://user-images.githubusercontent.com/28939517/130759623-e5302a55-972e-4eae-8e33-9730e6334e39.png)

**Comment by BongBongBang** [comment]
要通过src/app.tsx 配置运行时插件。但是按照官方文档来，一直报register failed的问题。。。我还在解决中。。。郁闷

**Comment by BongBongBang** [comment]
> 要通过src/app.tsx 配置运行时插件。但是按照官方文档来，一直报register failed的问题。。。我还在解决中。。。郁闷
解决了。官方文档有点模糊。要想开启layout插件，必须要配置官方文档中的【静态文档】部分才算配置开启。

**Comment by BongBongBang** [comment]
> 要通过src/app.tsx 配置运行时插件。但是按照官方文档来，一直报register failed的问题。。。我还在解决中。。。郁闷

解决了。官方文档有点模糊。要想开启layout插件，必须要配置官方文档中的【静态文档】部分才算配置开启。

**Comment by luojanet** [comment]
> > 要通过src/app.tsx 配置运行时插件。但是按照官方文档来，一直报register failed的问题。。。我还在解决中。。。郁闷
> 
> 解决了。官方文档有点模糊。要想开启layout插件，必须要配置官方文档中的【静态文档】部分才算配置开启。

你好，请问配置静态文档是哪里的静态文档啊

**Comment by BongBongBang** [comment]
> > > 要通过src/app.tsx 配置运行时插件。但是按照官方文档来，一直报register failed的问题。。。我还在解决中。。。郁闷
> > 
> > 
> > 解决了。官方文档有点模糊。要想开启layout插件，必须要配置官方文档中的【静态文档】部分才算配置开启。
> 
> 你好，请问配置静态文档是哪里的静态文档啊

![image](https://user-images.githubusercontent.com/10750792/131301586-5f68b987-acf9-4dda-bdf8-ca3c495b08b7.png)
哦， 是文档里的“构建时配置”

**Comment by github262302** [comment]
![route](https://user-images.githubusercontent.com/71603326/132379321-4ef0aff0-34c8-4098-b2e0-403967a24ff3.PNG)
