### ISSUE TITLE
👑 [需求] 配置文件提供schema支持，有什么办法提供schema的支持，避免拼写错误，并且提供智能感知

### ISSUE THREAD

**Issue by chenxizhang** [ant-design/ant-design-pro#8996]
### 🥰 需求描述

配置文件提供schema支持，有什么办法提供schema的支持，避免拼写错误，并且提供智能感知

### 🧐 解决方案

是不是可以通过定义接口类型来实现？或者干脆就用一个json文件，这个好像可以定义schema

**Comment by chenshuai2144** [comment]
现在我们是通过ts 来实现的。
