### ISSUE TITLE
🐛[BUG]   npm run start 和 npm run build  效果搞返了

### ISSUE THREAD

**Issue by huaiguoguo** [ant-design/ant-design-pro#8997]
### 🐛 bug 描述

感觉你们是不是在编码的时候搞反了，
npm run start 看起来像生产环境, 
npm run build 过后上传到线上，看起来像是开发环境，而且左侧还出现了配置浮动图标 ，页面title也没有和我在defaultConfig里面配置的一样

### 📷 复现步骤

感觉你们是不是在编码的时候搞反了，
npm run start 看起来像生产环境, 
npm run build 过后上传到线上，看起来像是开发环境，而且左侧还出现了配置浮动图标 ，页面title也没有和我在defaultConfig里面配置的一样

### 🏞 期望结果

期望结果是  把顺序纠正过来，npm run build  是正常按我配置的走，包括title, 右侧的浮动配置图标不要显示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 5.0
- umi 版本 最新版本
- 浏览器环境  chrome
- 开发环境 [e.g. mac OS]  win10

### 🚑 其他信息

yarn create umi test
![image](https://user-images.githubusercontent.com/1888094/130800352-e79fe969-2f35-4014-bb3a-60d64a561b07.png)

npm run build 过后部署的
![image](https://user-images.githubusercontent.com/1888094/130800041-d664a608-638e-418b-b061-51c7ea7c0906.png)

![image](https://user-images.githubusercontent.com/1888094/130799875-6efeb2d8-70c1-41fb-8992-10bfd038c0de.png)

npm run start
![image](https://user-images.githubusercontent.com/1888094/130800736-5d82fd5e-f727-4e78-8463-2d68c119b44b.png)

**Comment by dingwd** [comment]
要怎么设置，发布后去掉那个右侧设置

**Comment by dingwd** [comment]
请问下要怎么设置，发布后去掉那个右侧设置

**Comment by drizzlesconsin** [comment]
> 请问下要怎么设置，发布后去掉那个右侧设置

https://github.com/ant-design/ant-design-pro/issues/8968#issuecomment-905203997

**Comment by laosandegudai** [comment]
> > 请问下要怎么设置，发布后去掉那个右侧设置
> 
> [#8968 (comment)](https://github.com/ant-design/ant-design-pro/issues/8968#issuecomment-905203997)

这样只是啊关闭右侧设置，但是这两个命令的效果还是反的。
