### ISSUE TITLE
文档"从 mock 直接切换到服务端请求-关闭 mock"错误

### ISSUE THREAD

**Issue by Hsinky** [ant-design/ant-design-pro#900]
按照文档
关闭 mock 的方法我们推荐采用环境变量，你可以在 package.json 中设置：
"script" : {
  "start": "roadhog server",
  "start:no-proxy": "NO_PROXY=true roadhog server"
}
然后在 .roadhogrc.mock.js 中做个判断即可：
const noProxy = process.env.NO_PROXY === 'true';
export default noProxy ? {} : delay(proxy, 1000);

问题：
在.roadhogrc.mock.js中获取NO_PROXY是undefined

**Comment by ynnyh** [comment]
还是那个问题，关闭代理不要按照官网文档那个走，只需要在配置文件中加入代理即可对请求进行转发，所以如果你需要请求转发就在配置文件加上代理请求，不加则会自动请求mock，不知道这样说你能不能理解

**Comment by Hsinky** [comment]
@afc163 解决都没解决就关闭？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/35894815-8a00bd8c-0bef-11e8-8619-1effa95b853c.png)
看看这个提交

**Comment by xjchenhao** [comment]
开发你们好：

[看官方文档](https://pro.ant.design/docs/mock-api-cn#%E8%81%94%E8%B0%83)：`当本地开发完毕之后，如果服务器的接口满足之前的约定，那么你只需要不开本地代理或者重定向代理到目标服务器就可以访问真实的服务端数据，非常方便。`。**具体是这么关闭呢？是注释吗？**

我看antd-pro默认是走mock代理的，当我在`.webpackrc`文件中增加以下代码，就可以走正常后端server请求了：
```
  "proxy": {
    "/nodeApi": {
      "target": "http://localhost:7001/",
      "changeOrigin": true
    }
  },
```

当我尝试在`package.json`中修改script的时候，发现运行`"start:no-proxy": "cross-env NO_PROXY=true DISABLE_ESLINT=true roadhog server",`是没有效果的。不管是写true还是false，如果我写了上面的`proxy`，就是会请求到后端server去。

请问关于这个需求要这么处理呢？
@chenshuai2144 @afc163
