### ISSUE TITLE
🐛[BUG] 增加 outputpath 配置以后热更新失效

### ISSUE THREAD

**Issue by zzhzero** [ant-design/ant-design-pro#9002]
### 🐛 bug 描述
增加 outputpath 配置以后热更新失效
### 📷 复现步骤
1. config.ts 增加 outputpath 配置
2. npm run start
3. 修改 pages 里的代码发现页面无法更新
4. 删除 outputpath 配置
5. 重启项目发现热更新恢复正常

### 💻 复现代码
outputpath: process.env.NODE_ENV === 'production' ? '/xxx/' : '/',

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
outputpath 是什么的配置？ webpack 的

**Comment by wensiqun** [comment]
+1 我这里也有同样的问题。期待官方解决下

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/api/config#outputpath
