### ISSUE TITLE
🧐[问题]配置二级路由的重定向后面包屑没了

### ISSUE THREAD

**Issue by liqingitt** [ant-design/ant-design-pro#9003]
![image](https://user-images.githubusercontent.com/84669383/130938786-fe932ef4-ba4f-48a8-a6f0-493236a05e75.png)
![image](https://user-images.githubusercontent.com/84669383/130938913-31cc84cf-1b1c-46a4-8eed-da932a891327.png)
![image](https://user-images.githubusercontent.com/84669383/130938990-1c87a460-0b75-4e9e-9d89-4a3ce6cd21bd.png)
![image](https://user-images.githubusercontent.com/84669383/130939017-7028f561-752f-4bb0-a315-acffb9c0bb2b.png)
是不是我配置的方式不对呢

**Comment by chenshuai2144** [comment]
这个 *太狠了，用 ./ 就够了，或者不要写
