### ISSUE TITLE
 🧐[问题] pro 如何通过外部事件 设置pro table 中查询表单的值

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#9004]
### 🚑 例如如何实现以下图例所示：
![image](https://user-images.githubusercontent.com/13744175/130941063-c09e4f3b-1b1e-47be-8909-4a3bea905863.png)

**Comment by xyzabc0004** [comment]
https://procomponents.ant.design/components/table?current=1&pageSize=5
左右结构
可以参考这里面两组件的，传值思想。
