### ISSUE TITLE
🐛[BUG] ProTable 属性 params，参数变动后，请求页码应重置但未重置

### ISSUE THREAD

**Issue by dhbyls** [ant-design/ant-design-pro#9005]
#### ProTable 属性 params，参数变动后，请求页码应重置但未重置
![image](https://user-images.githubusercontent.com/13744175/130942719-b818cd9b-22aa-4dfb-b36b-dd38e1ceffc4.png)

**Comment by qq1170623178** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
修复了

**Comment by qq1170623178** [comment]
什么时候修复的，我把pro-table升级到最新版本还是不行，也没看见fix记录

**Comment by qq1170623178** [comment]
@chenshuai2144  help
