### ISSUE TITLE
我的项目我来秀--->肝了两天终于把多sku肝完了，秀一下

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#9008]
## 开发人员：一个

# 🎃🎃🎃:不提供源码。

# 展示图片： 🏞 👹👺🤡👀🧑‍🔧🧑‍🔧🧝‍♀️
![秀](http://oss.jibei.ycoto.cn/demo/goods01/WechatIMG226.png)
![秀](http://oss.jibei.ycoto.cn/demo/goods01/WechatIMG227.png)
![秀](http://oss.jibei.ycoto.cn/demo/goods01/WX20210823-155932%402x.png)

**Comment by fangqibin** [comment]
什么时候可以预览，很期待。

**Comment by codedart2018** [comment]
> 什么时候可以预览，很期待。

等些天吧

**Comment by codedart2018** [comment]
> 什么时候可以预览，很期待。

等我把商品发布这块弄完后，再弄演示。
