### ISSUE TITLE
配置代理，无法访问.roadhogrc.mock.js中的api

### ISSUE THREAD

**Issue by Hsinky** [ant-design/ant-design-pro#901]
1、在.webpackrc中配置：
"proxy": {
    "/Handler": {
      "target": "http://[我的IP]/Handler/",
      "changeOrigin": true
    }
  }
2、在.roadhogrc.mock.js中
export default noProxy ? {
  //非mock环境接口
  'POST /Handler/UserHandler.ashx': (req, res) => { 
    const { password, userName, type } = req.body;
    console.log(req.body);
    res.send({
      status: 'error',
      type,
      y:1223,
      currentAuthority: 'guest'
    });
  },
} : delay(proxy, 1000);

现在出现的问题是：代码走到services层后，直接就访问了后端服务，并不会走.roadhogrc.mock.js

**Comment by ynnyh** [comment]
如果你想走到mock，就不要配置代理，如果你要访问后端服务再使用代理

**Comment by Hsinky** [comment]
@ynnyh 您的意思是如果在.webpackrc配置了代理，就直接访问到了服务端，如果没在这个文件里面配置代理就走mock？那mock里面判断代理是怎么处理呢？因为service里面请求的路经是相对路经（不带域名和IP的），那mock里面post/get后面的路经怎么在代理或不代理时保持统一

**Comment by ynnyh** [comment]
mock不判断代理啊，如果你加上代理配置，那么就会将你的请求转发，如果你不加代理就会进到mock里面，这个流程是通的啊

**Comment by Hsinky** [comment]
@ynnyh 但是在.roadhogrc.mock.js里面pro示例中有判断代理const noProxy=process.env.NO_PROXY === true;

**Comment by ynnyh** [comment]
这个我暂时不知道有什么用，你不用管这个，只需要在配置文件中加上代理就可以了

**Comment by Hsinky** [comment]
那从后端返回来的数据，就只能在model层里面进行逻辑处理了？

**Comment by ynnyh** [comment]
难道处理逻辑不应该在model里面吗，redux不就是搞这个的吗

**Comment by Hsinky** [comment]
嗯，明白，谢谢老大指导

**Comment by chenshuai2144** [comment]
noProxy 是为了关闭代理。方便做一些特殊的调试

**Comment by Hsinky** [comment]
@chenshuai2144 并不知道特殊调试体现在什么地方！因为noProxy在webpackrc配置了代理并没有起到什么作用

**Comment by chenshuai2144** [comment]
设计就是这样的。。。。。
我从来没用过！
webpackrc的更好用，支持的规则也更多

**Comment by Hsinky** [comment]
你们官方都没用过？那这个功能很容易误导我这种小白，搞的一头雾水

**Comment by GoatherdNaN** [comment]
我也想问，怎么通过npm指令来切换mock和代理啊？总不可能只能手动删除webpack配置中的proxy配置来切换吧

**Comment by GoatherdNaN** [comment]
@Hsinky 在.roadhogrc.mock.js里面判断代理const noProxy=process.env.NO_PROXY === true已经没有必要了感觉，我现在在.roadhogrc.mock.js里面就直接暴露mock api了，noProxy的判断应该放在.webpackrc.js中，以切换mock和代理

**Comment by lyingd** [comment]
我尝试过在mock里标记proxy，然后在.webpackrc.js里处理标记实现按需代理，
比如在mock里，想对某个url开启代理，只需如此：
'POST /api/login/account': proxy('http://xxx.com')
但目前的实现对proxy还不支持method解析。

参考： https://github.com/lyingd/antd-pro-standalone/commit/c9b6984ddd246e99224c76dddc69798da3e86149
