### ISSUE TITLE
如何修改 Ant Design Pro全局默认的loading icon

### ISSUE THREAD

**Issue by yiluxiangbei87110** [ant-design/ant-design-pro#9014]
### 🧐 问题描述

antdesignpro 全局有默认的loading样式icon，比如dva处理数据请求时的默认loading图。如何一次性快速更改默认的loading？比如我想换个loading图标？

### 💻 示例代码

```
import { PageLoading } from '@ant-design/pro-layout';

```

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/23131032/131102765-3a3ef49a-07a3-4de9-818e-c2a836492bda.png)

**Comment by sanmmm** [comment]
修改 document.ejs

**Comment by github262302** [comment]
# 修改config.ts
![截屏2021-09-08 下午1 16 58](https://user-images.githubusercontent.com/71603326/132450740-7319f4aa-31d4-4d5f-b15a-dc9a82bcbfaa.png)
