### ISSUE TITLE
🐛[BUG]and-design-pro 5.0 开启MFSU，是不是和umi版本配套有问题

### ISSUE THREAD

**Issue by super20155** [ant-design/ant-design-pro#9016]
### 🐛 bug 描述
![1630121135(1)](https://user-images.githubusercontent.com/31334147/131204824-ca031be6-3404-4216-8980-418f750bdb5d.png)

### © 版本信息

- Ant Design Pro 版本: 5
- umi 版本
- 浏览器环境：chrome
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
区块不维护了，所以不支持新的特性。
