### ISSUE TITLE
🧐[问题]protable查询框内的日期组件没有被汉化。

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design-pro#9017]
### 🧐 问题描述

protable查询框内的日期组件没有被汉化

### 💻 示例代码
![%}M~$O8ON41~6VL8DMMY`~8](https://user-images.githubusercontent.com/37889515/131235872-2372f577-6b17-4ed4-8f44-1a592aa3ac5d.png)

![$R4_9 ~2V3_DL81F5S5LN3R](https://user-images.githubusercontent.com/37889515/131235882-6a066ef0-f309-42ac-a0dd-68fca491b644.png)

### 🚑 其他信息
![11](https://user-images.githubusercontent.com/37889515/131235888-0aa3ac90-78a6-4570-8d01-20de6073b8f9.png)

**Comment by huangzongming** [comment]
![1630203116(1)](https://user-images.githubusercontent.com/37889515/131235902-218bb880-363f-458e-bca9-74598e1c2fbf.png)
期待是这个样子的

**Comment by drizzlesconsin** [comment]
重装 moment 试下

再不行先搜下相关 issues https://github.com/ant-design/ant-design-pro/issues/2184#issuecomment-613904279

**Comment by chenshuai2144** [comment]
这个要设置一下moment的locale的。不是光用antd的就可以
