### ISSUE TITLE
🐛[BUG] Layout布局 使用main 小写命名组件导致在IE浏览器长时间无响应，同时浏览器报错。

### ISSUE THREAD

**Issue by zllisa** [ant-design/ant-design-pro#9020]
### 🐛  Layout布局 使用main section等小写命名组件导致在IE浏览器长时间无响应。
问题#5453 只提出main的组件报错。

### 🚑  问题如图：

![image](https://user-images.githubusercontent.com/28992888/131298033-49689e83-cd3f-4d8d-8320-6a244559f050.png)
![image](https://user-images.githubusercontent.com/28992888/131298082-e4383ae9-fdee-40c4-a7e3-6e5100cb2ac9.png)

### 🏞 期望结果
希望兼容IE浏览器。

### © 版本信息

- Ant Design ："antd": "^4.16.10",
- 浏览器环境 ：[IE,或者兼容IE的浏览器 如360兼容模式]
- 开发环境 [Windows]

**Comment by zllisa** [comment]
主要问题使用了Content组件标签

**Comment by chenshuai2144** [comment]
字面意思，组件必须要首字母大写
