### ISSUE TITLE
🐛[BUG] 能否在定义路由时设置某个路由不加载landing page

### ISSUE THREAD

**Issue by chenxizhang** [ant-design/ant-design-pro#9025]
### 🐛 bug 描述

在某些场合下，我们需要实现简单的着陆页，它只是用来做跳转的。这个跳转的页面，能否在定义路由时，指定不加载landing page（就是默认的那个document.ejs）？目前只看到一个属性 layout可以设置为false，避免出现布局。最好能禁用 document.ejs的加载效果。

本来我想用一个完全静态的页面，例如redirect.html（放在public目录）来解决。但这样的话，又无法利用到React的一些特性。

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS] Windows 10

**Comment by chenshuai2144** [comment]
现在不行的，因为我们的配置是全局的，不是一个个配置的。是不是可以拆分一下配置

**Comment by marlti7** [comment]
我也有同样的需求

**Comment by marlti7** [comment]
> 现在不行的，因为我们的配置是全局的，不是一个个配置的。是不是可以拆分一下配置

如何拆分
