### ISSUE TITLE
🧐[问题]关于后端返回分页参数的问题

### ISSUE THREAD

**Issue by kanhebei** [ant-design/ant-design-pro#9027]
后端返回的数据格式为 
{ data:[], page:1, per_page: 20, total: 500}

前端分页的数据字段格式实际为 { data: [], current: 1, pageSize: 20, total: 500}

后端不变，前端如何转换一下呢。。

**Comment by xyzabc0004** [comment]
如果你想后端也不变，我的搞法是在model层拿到旧的值{ data:[], page:1, per_page: 20, total: 500}，再return 成新对象，转换下。
