### ISSUE TITLE
🧐[使用sourcetree进行commit时不能正常提交]

### ISSUE THREAD

**Issue by baibaibai455** [ant-design/ant-design-pro#9030]
##### 使用sourcetree进行commit时不能正常提交
会出现如下错误
```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/0k/6v6r16yj0j3_hxv0qgmgggw00000gn/T/SourceTreeTemp.4KR1xW 
 > running pre-commit hook: npm run precommit

> ant-design-pro@5.0.0 precommit
> lint-staged

✖ Current directory is not a git directory!

pre-commit hook failed (add --no-verify to bypass)
Completed with errors, see above
```
![image](https://user-images.githubusercontent.com/47173675/131620122-6bf3926b-ce5c-4287-85a3-170a6476b210.png)

执行 npm run precommit        时没有问题
![image](https://user-images.githubusercontent.com/47173675/131620369-f6048777-8394-40e1-bff0-58a3d5aa75ea.png)

### 🚑 其他信息
使用命令行提交时是可以的
![image](https://user-images.githubusercontent.com/47173675/131770327-de37cad9-96ff-4887-8abc-eb7210238f01.png)

**Comment by 569202812** [comment]
这不是提醒不是git目录吗，git init过了嘛

**Comment by baibaibai455** [comment]
> 这不是提醒不是git目录吗，git init过了嘛

这个是从github上拉下来的仓库，然后将myapp的文件完整复制过来的。

**Comment by fangqibin** [comment]
我觉得你把precommit关了吧。你把握不住。

**Comment by baibaibai455** [comment]
> 我觉得你把precommit关了吧。你把握不住。

emm   这不是解决办法，我用命令行提交是正常的，就是用sourcetree有问题，因为用习惯了所以想弄好它
![image](https://user-images.githubusercontent.com/47173675/131770173-ce3e3636-9716-485c-886f-dc2f6a873c40.png)

**Comment by baibaibai455** [comment]
> 我觉得你把precommit关了吧。你把握不住。

**Comment by chenshuai2144** [comment]
感觉是pwd 的问题，sorucetree 里面的pwd是错的，导致库挂了

**Comment by 569202812** [comment]
> 感觉是pwd 的问题，sorucetree 里面的pwd是错的，导致库挂了

看看我的问题 https://github.com/ant-design/ant-design-pro/issues/9064 手动鞠躬
