### ISSUE TITLE
🧐[问题] How is src/manifest.json being used?

### ISSUE THREAD

**Issue by schwannden** [ant-design/ant-design-pro#9031]
### 🧐 问题描述

The manifest.json file
https://github.com/ant-design/ant-design-pro/blob/master/src/manifest.json

does not appear to be used anywhere? For example it doesn't appear in document.ejs, nor does it appear in the built dist folder, then what is the purpose of this file?

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Manifest
look here
