### ISSUE TITLE
🧐[问题]自定义layout后不想路由重定向整个页面显示403，需要显示左侧菜单

### ISSUE THREAD

**Issue by shindouhiro** [ant-design/ant-design-pro#9032]
### 🧐 问题描述

自定义的BasicLayout布局后,
当redirect: '/resources/contract'没有权限，
整个页面显示了403
需要显示左侧菜单和头部nav

### 💻 示例代码
```js
  {
    name: 'resources',
    path: '/resources',
    access: 'canAdmin',
    zhname: ['资源'],
    component: '../layouts/BasicLayout',
    routes: [
      {
        path: './',
        redirect: '/resources/contract',
      },
      {
        path: './contract',
        name: 'contract',
        access: 'canAdmin',
        zhname: ['资源-合同资源'],
```

### 🚑 其他信息

自定义layout
![image](https://user-images.githubusercontent.com/8401237/131632153-9d955c01-4d4b-4f59-a299-8bcf0845ba7a.png)
想要403在菜单右侧，而不是整个页面
![image](https://user-images.githubusercontent.com/8401237/131632636-c13b96f2-57d8-4016-a06f-7bab5d55117f.png)

**Comment by fangqibin** [comment]
那你配置的403路由应该在BasicLayout这个底下

**Comment by shindouhiro** [comment]
![image](https://user-images.githubusercontent.com/8401237/131814715-5a2dfb24-4638-4414-b5fc-54e618dfc112.png)
@fangqibin 这样？

**Comment by fangqibin** [comment]
> ![image](https://user-images.githubusercontent.com/8401237/131814715-5a2dfb24-4638-4414-b5fc-54e618dfc112.png)
> @fangqibin 这样？

这样不行吗

**Comment by shindouhiro** [comment]
不行，还是整个页面显示 @fangqibin

**Comment by fangqibin** [comment]
> 不行，还是整个页面显示 @fangqibin

![image](https://user-images.githubusercontent.com/15991882/131940918-477d931c-faaa-4882-885f-403823833c91.png)
我是v5版本的，这样就可以，也没有改

**Comment by fangqibin** [comment]
没有layout放在里面

**Comment by shindouhiro** [comment]
@fangqibin 我没有自定义layout也可以

**Comment by shindouhiro** [comment]
@fangqibin 404可以  403还是会占整个页面

**Comment by shindouhiro** [comment]
@fangqibin 加到最外层所有页面都显示404了.

**Comment by shindouhiro** [comment]
我通过自定义暂时替代解决了
```
 <Access accessible={access.canReadFoo} fallback={<div>Can not read foo content.</div>}>
        Foo content.
      </Access>
```
