### ISSUE TITLE
Pro V5 怎么和websocket 连一起用

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#9033]
V5 怎么和websocket 连一起用，现在还没有头绪。

还请，
各位老师，
推荐下相关的文章，学习资料什么的。

**Comment by 569202812** [comment]
`ahooks` 里面 有个 `useWebSocket` 你可以看看

**Comment by xyzabc0004** [comment]
这个用了ahooks会不会把之前用的hooks 盖掉。

**Comment by 569202812** [comment]
> 这个用了ahooks会不会把之前用的hooks 盖掉。
之前用的什么hook

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/131763933-296a30d6-ea84-4982-b125-5dfa73c7d817.png)

我好像只用到这两种。

**Comment by 569202812** [comment]
> ![image](https://user-images.githubusercontent.com/32530210/131763933-296a30d6-ea84-4982-b125-5dfa73c7d817.png)
> 
> 我好像只用到这两种。

从不同库中引入没影响

**Comment by fangqibin** [comment]
> 这个websocket之前没玩过，还得从头学下。

弄懂了记得给我们分享一下。我也是都没玩过，一头雾水。

**Comment by xyzabc0004** [comment]
好嘞！
