### ISSUE TITLE
🐛[BUG] Cannot read property "@@initialState" of undefined, 开发环境与生产环境表现不一致.

### ISSUE THREAD

**Issue by hakunamatata** [ant-design/ant-design-pro#9036]
### 🐛 bug 描述

在开发环境  npm start 运行没有问题
                    npm build 过程中也没有错误
但是在生产环境中运行不了, 报 TypeError: Cannot read property '@@initialState' of undefined

### 📷 复现步骤
1. 在app.tsx 中自定义 初始状态数据
![image](https://user-images.githubusercontent.com/1525245/131736011-8a85b739-d02d-45d3-9696-c2eda8ed14ea.png)
2. 在 ./src/components/Footer/index.tsx 中使用自定义数据
![image](https://user-images.githubusercontent.com/1525245/131736150-782aed9f-e0d6-489a-a033-25da955aff66.png)

3. 在开发环境完全无法感知错误, build 过程中也没有任何错误提醒
4. 在生产环境中使用是报错的, 打开是空白页面

### 🏞 期望结果
期望在开发过程中所呈现的效果, build 之后得到的结果是一致的

### 💻 复现代码
见: https://github.com/hakunamatata/an-umi-production-build-bug.git

### © 版本信息

- Ant Design Pro 版本: 
-    > yarn create umi
-    > ant-design-pro 
-    > TypeScript
-    > simple

- umi 版本 3.5.0
- 浏览器环境 Chrome
- 开发环境 windows 10 

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/1525245/131718521-81ab0c60-f9a1-4a68-9b2d-2d12b924256f.png)

开发环境-正常运行:
![image](https://user-images.githubusercontent.com/1525245/131735677-78323591-0ccd-4ac9-98df-53484d417322.png)
生产环境-无法运行
![image](https://user-images.githubusercontent.com/1525245/131735874-bcaa443f-dbe1-4448-96d3-26cdfa1d16b6.png)

**Comment by hakunamatata** [comment]
问题找到了

   使用 useModel 的时候 vscode 自动会自动 import { useModel } from '@/.umi/plugin-model/useModel'
---------------
   其实应该 import  { useModel } from 'umi'
   留意这个坑位......

**Comment by deerLoves** [comment]
> 问题找到了
> 
> ## 使用 useModel 的时候 vscode 自动会自动 import { useModel } from '@/.umi/plugin-model/useModel'
> 其实应该 import { useModel } from 'umi' 留意这个坑位......

太坑了。。一上生产就全身哆嗦
