### ISSUE TITLE
🐛[BUG]最新版本antdpro Module parse failed: Unexpected token (1:0)  SONEditor.svelte

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design-pro#9039]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/5111701/131791492-65342207-ad9a-464a-a89a-37fbfb468df5.png)

昨天刚从 这个git 仓库master分支下载的，然后同样的代码在 v5-alpha版本里是ok的，

### 📷 复现步骤

https://github.com/josdejong/svelte-jsoneditor
npm install svelte-jsoneditor

在antd pro里使用这个组件
使用参考https://codesandbox.io/s/svelte-jsoneditor-react-59wxz

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
svelte-jsoneditor 这个组件不支持mfsu，你关掉之后用吧

**Comment by pxim** [comment]
> svelte-jsoneditor 这个组件不支持mfsu，你关掉之后用吧

好的，谢谢
