### ISSUE TITLE
.roadhogrc.mock.js  传递参数 报400   后台拿不到数据

### ISSUE THREAD

**Issue by hkl921010** [ant-design/ant-design-pro#904]
无参数请求  正常 数据都拿得到    是传不了参数吗

**Comment by fancyluo88** [comment]
遇到同样的问题

**Comment by chenshuai2144** [comment]
chrome devtool screenshot？

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/400

**Comment by hkl921010** [comment]
![aa](https://user-images.githubusercontent.com/23328281/35902862-c3fc7102-0c17-11e8-82e2-8e26c00d985a.png)
![aa2](https://user-images.githubusercontent.com/23328281/35902873-c9da79d4-0c17-11e8-9246-0d6f6fbe58ac.png)

**Comment by hkl921010** [comment]
![image](https://user-images.githubusercontent.com/23328281/35902905-e185afc2-0c17-11e8-8566-08fbcc604046.png)

**Comment by chenshuai2144** [comment]
你后台需要的参数是否是 key=value  或者没有 JSON.stringify

**Comment by fancyluo88** [comment]
后台 说什么也没有接收到呢

**Comment by chenshuai2144** [comment]
400了 后台当然收不到。被框架打回来了。
发的格式夫妇和需求

**Comment by fancyluo88** [comment]
![image](https://user-images.githubusercontent.com/29801687/35908176-d44e7b28-0c2a-11e8-8663-f4ea0a194f95.png)
![image](https://user-images.githubusercontent.com/29801687/35908196-e05dc8d8-0c2a-11e8-9754-1ae015a499f7.png)
就是按照说明文档来的么

**Comment by chenshuai2144** [comment]
这个和文档没关系 你问问你们后台需要什么数据
你怎么搞就行了
你可以先学学http 发送数据的集中方式

**Comment by fancyluo88** [comment]
就是说 我们 前端 直接 按文档来 就好了 是吧

**Comment by chenshuai2144** [comment]
额 看你们公司是什么主导的 你要是厉害 你可以让后台改

**Comment by fancyluo88** [comment]
好的  谢谢了

**Comment by fancyluo88** [comment]
解决了 完全参照文档就好了  后台的问题

**Comment by CherryaMao** [comment]
你好，我想问一下你是怎么接上后台真实数据的？我按照文档修改了.roadhogrc.mock.js文件为：export default {
   'GET /(.)': 'http://192.168.1.102:8080/ ',
   'POST /(.)': 'http://192.168.1.102:8080/ ',
 };
也修改了.roadhogrc.js文件为：
"proxy": {
  "/api": {
    "target": "http://192.168.1.102:8080/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}，
没有报任何错，
当我npm start 时查看我的请求情况时 Request URL:http://localhost:8000/ 的地址是否要变成http://192.168.1.102:8080/才算正确？能否告诉除了以上我讲到的能改的地方以外还有其他地方要改么？

**Comment by fancyluo88** [comment]
只修改.roadhogrc.js文件就可以了

**Comment by CherryaMao** [comment]
还是没有接上后台， Request URL的地址还是没有变为 http://192.168.1.102:8080/，

**Comment by fancyluo88** [comment]
proxy 只是做一个请求转发，直接fetch请求可以接上后台么，你的请求URL怎么写的？

**Comment by fancyluo88** [comment]
你是否了解 谁最先接到这个dispatch？

**Comment by CherryaMao** [comment]
不了解，还请告知。

**Comment by fancyluo88** [comment]
看文档啊 和服务端进行交互的过程

**Comment by fancyluo88** [comment]
在 Ant Design Pro 中，一个完整的前端 UI 交互到服务端处理流程是这样的：

UI 组件交互操作；
调用 model 的 effect；
调用统一管理的 service 请求函数；
使用封装的 request.js 发送请求；
获取服务端返回；
然后调用 reducer 改变 state；
更新 model。

**Comment by CherryaMao** [comment]
我在service文件下的api.js中写了
export async function queryLab() {
  return request('/users/userColumn');
}，
然后在models文件下新建了一个文件名为labColumn.js 内容如下：
import { queryLab } from '../services/api';
export default {
    namespace: 'userlist',
    state: {
      userslist: [],
      //loading: false,
    },
  
    effects: {
      *fetch({ payload }, { call, put }) {
        yield put({
          type: 'changeLoading',
          payload: true,
        });
        const response = yield call(queryLab, payload);
        yield put({
          type: 'usersList',
          payload: Array.isArray(response) ? response : [],
        });
        yield put({
          type: 'changeLoading',
          payload: false,
        });
      },
    },
    reducers: {
        usersList(state, action) {
            return {
            ...state,
            userslist: action.payload,
            };
        },
        changeLoading(state, action) {
            return {
            ...state,
            loading: action.payload,
            };
        },
    },
  };
然后在要用数据的页面用connect链接起来。这样子写还有什么地方不对么？这个文档是不能100%理解。

**Comment by fancyluo88** [comment]
this.props.dispatch({
type:'/labColumn/fetch',
})    不知道对不对，但肯定不是你那个dispatch

**Comment by CherryaMao** [comment]
也是不对，可否帮我看看上面的代码是否有误？

**Comment by fancyluo88** [comment]
还有 几个地方要改呢 menu.js  connect中 你得先完整的了解下 框架

**Comment by CherryaMao** [comment]
menu.js是什么js，我的项目中根本就没有这个js
