### ISSUE TITLE
🧐[问题]proTable新增一行后，再新增一行时，行内数据没有清空为空值，自动带上次新增的值。

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#9042]
### 🧐 问题描述
proTable新增一行后，再新增一行时，行内数据没有清空为空值，自动带上次新增的值。
虽然可以通过给id设置随机值后就是空值，但后台逻辑就是以id来判断是否新增还是更新。

### 💻 示例代码
                            let a = { id:' ',name: '', description: ''};
                            ref.current.addEditRecord?.(a, {
                              position: 'top',
                            });

**Comment by chenshuai2144** [comment]
他是跟据id来判断的，你可以用 rowkey设置另外一个唯一值，然后再前端用 hash 生成
