### ISSUE TITLE
🧐[问题]Pro 5.0 期望在   layout: 'mix',是展示默认页

### ISSUE THREAD

**Issue by liangxp** [ant-design/ant-design-pro#9043]
### 🧐 问题描述
想要效果见图片标注。
![image](https://user-images.githubusercontent.com/6928085/131883324-15b317ee-e7c8-4723-92f4-6d9115e1ad58.png)

### 💻 示例代码
在4.X中，路由如下配置即可实现展示/logistics/index的内容
`
{
                name: 'logistics',
                path: '/logistics',
                authority: ['logistics'],
                redirect:'/logistics/index',
                routes: [
                  {
                    name: 'index',
                    path: '/logistics/index',
                    component: './Dev',
                    authority: ['logistics'],
                    hideInMenu: true
                  },
                  {
                    name: 'customsInfo',
                    path: '/logistics/customsInfo',
                    icon: 'MenuOutlined',
                    component: './Logistics/CustomsInfo',
                    authority: ['logistics:customsInfo:list'],
                  }
         ]
`
在最新5.0中这样配置无法生效，甚至导致其他子路由也无法正常展示。不知道是否有好的解决方案，谢谢！

**Comment by drizzlesconsin** [comment]
```diff
{
  path: '/abc',
  name: 'ABC',
  routes: [
    {
      path: '/abc/eeeeee',
      name: '默认页面',
      icon: 'xx',
      component: './xx',
    },
+   {
+     path: '/abc',
+     redirect: '/abc/eeeeee',
+   },
  ],
}
```
