### ISSUE TITLE
🐛[BUG]tabs组件在放大或者缩小的时候会出现三个点

### ISSUE THREAD

**Issue by fangqibin** [ant-design/ant-design-pro#9044]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/15991882/131957045-a8a9957e-bea7-46c2-80fd-2a70ef3e55f4.png)
官方文档，我缩小了就会出现这样。
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个看起来是宽度计算 表现不正常，去antd 问问吧。

我觉得这个不大会修，缩放的问题太难修了
