### ISSUE TITLE
【配置分类  --- 讨论】

### ISSUE THREAD

**Issue by SilvaQ** [ant-design/ant-design-pro#9045]
【配置分类  --- 讨论】
-----------------------

配置官方级别分类化是否科学？官方对此有没有考虑过？有何初衷或者考虑到的痛点？

虽然这种配置开发者自己控制就可以，但是antd系列所争取到的目标来看，这种交代清楚的配置应该官方首先开始规范化比较完美。

比如我这里以Proxxx组件库为例，其实table这种复杂的配置也应该可以的：

```javascript
const proTableProps={
        baseTable:{
            row:{},
           col:{}
           header:{
                toolbar:{}
           }
           footer:{}
           ....
          },  // 针对最基本table的，后面所有 配置是基于它扩展的
        proTable:{},  // 非table外扩展的protable专属的
        complexTable:{}, // treetable这种名字已经确定的独有配置
        otherKind:{}  ,// 暂先无法分类的，即将可能会归到其他分类的
}

const ProformProps={
          baseForm:{}
          proForm:{}
          modal:{}
          complexForm:{},
          otherKind:{}
}
```

对此想知道其他开发者们对这个想法怎么看？ 大佬们有何想法？

_Originally posted by @SilvaQ in https://github.com/ant-design/ant-design-pro/issues/8761#issuecomment-912287302_

**Comment by chenshuai2144** [comment]
很棒的想法， 可以搞个rfc吗？

**Comment by SilvaQ** [comment]
> 很棒的想法， 可以搞个rfc吗？

没做过rfc,这方面经验欠缺，还有一个就是平常开发时，尤其是pro系列组件是才开始留意 and组件和pro组件的差异，有时候甚至给我感觉混淆的，甚至有时候得看源码中的值传递链才能推测我应该用什么，如：propsField字段。
这下才意识到 如果我们的配置的分类更加清晰 看文档也好，写代码时的记忆也好应该有非常大的提升，但是针对 how 我目前是没有其他想法，而且作为后端开发，对前端更多是使用层面的研究，所以知道的不多，这事儿还是望团队成员，尤其是核心成员出发整理推行成rfc 我认为更合适。

**Comment by SilvaQ** [comment]
但如果有这方面的工作开始进行我愿意作为学者加入进来，能贡献就贡献，贡献不了起码当个体验师，这是没问题的。

**Comment by chenshuai2144** [comment]
rfc 有点类似产品设计搞的东西。

你可以搞个最小的实现让我看看效果。我们一起讨论讨论 。讨论好了就可以开始干了

**Comment by chenshuai2144** [comment]
对的。嫌麻烦，直接提pr好了，我会处理的

**Comment by SilvaQ** [comment]
> 对的。嫌麻烦，直接提pr好了，我会处理和审查的
@chenshuai2144 

我去看了几个项目的rfc,发现他们对同一个产品都是单独创建一个rfcs的仓库来收集rfc并且把它分类进行管理的。
我这里是参考的rfc仓库:
- [React Rfcs](https://github.com/reactjs/rfcs)
- [Yarn RFCs](https://github.com/yarnpkg/rfcs)
- [Ember RFCs](https://github.com/emberjs/rfcs)

我们以 Antd为主 或者pro和antd分开建立对应的 rfc项目，参考以上实践案例来推进试试看你觉得如何？
这个需要你启动rfc 仓库，并把issue中的经典讨论移植到rfc上开启一个师范？
