### ISSUE TITLE
🐛[BUG] proxy 配置不起作用

### ISSUE THREAD

**Issue by chenxizhang** [ant-design/ant-design-pro#9048]
### 🐛 bug 描述

我配置了pre这个环境，希望把api转发到一个外部服务地址。然后用 yarn start:pre 启动，但永远都不会发起请求到我需要的地址，还是读取mock的数据。 

我使用默认模板，并没有做任何特别的修改。请问这个原因是什么。

```
export default {
  dev: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
  },
  test: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
  },
  pre: {
    '/api/': {
      target: 'http://localhost:7071',
      changeOrigin: true,
      pathRewrite: { '^': '' },
    },
  },
};
```

**Comment by chenxizhang** [comment]
将dev这个环境的target 设置为外部地址也无效，感觉就没有起作用

**Comment by chenxizhang** [comment]
@chenshuai2144  这个问题能否帮忙看一下，感觉不应该是一个问题，但我用标准模板没有做任何修改，也是这样。目前对我们项目开发影响较大。多谢

**Comment by xyzabc0004** [comment]
我把我写的截个图,给你参考下吧.
ant design pro里面是这样写的:
![image](https://user-images.githubusercontent.com/32530210/132181365-75a84214-a324-473e-b3b1-b396800466f0.png)
nginx里面是这样配的:
![image](https://user-images.githubusercontent.com/32530210/132181679-9deae0ce-12f6-4824-838a-405b1b839d35.png)

**Comment by chenxizhang** [comment]
后来摸索得到，设置MOCK=none 是可以起作用的。不过，近两周试用这个框架，发现不少问题，暂时还是不用了。感谢

**Comment by hyzx86** [comment]
@chenxizhang 刚打算铺开。。看到你要放弃了😂，遇到什么问题了啊？可以讲讲么？
