### ISSUE TITLE
🐛[BUG] 添加二级路由时一级路由不能有component属性

### ISSUE THREAD

**Issue by Alt-er** [ant-design/ant-design-pro#9049]
### 🐛 bug 描述

有二级路由时一级路由不能有component ， 如果一级路由设置了component属性，则二级路由永远匹配不到。

### 📷 复现步骤

```
{
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin', //一级路由设置了component ，则访问 /admin/sub-page 也会显示Admin组件，不会显示Welcome组件
    routes: [
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        icon: 'smile',
        component: './Welcome',
      },
      {
        component: './404',
      },
    ],
  }
```

### 🏞 期望结果

访问 /admin 显示 Admin组件
访问 /admin/sub-page 显示Welcome组件

### 💻 复现代码

Antd Pro V5最新版本直接启动项目，就能看到这个问题

### © 版本信息

- Ant Design Pro 版本: V5

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80

把chilren 吐出来就可以了，不然就用重定向跳转到相应的页面

**Comment by Alt-er** [comment]
> https://pro.ant.design/zh-CN/docs/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80
> 
> 把chilren 吐出来就可以了，不然就用重定向跳转到相应的页面
> 
> ```
> 
>   routes: [
>        {path:".", redirect:"/admin/sub-page"}
>       {
>         path: '/admin/sub-page',
>         name: 'sub-page',
>         icon: 'smile',
>         component: './Welcome',
>       },
>       {
>         component: './404',
>       },
>     ],
> ```

这样的话不就都是一级菜单了吗？
正确的效果应该是这样的吧
>管理页
    >二级管理页

**Comment by chenshuai2144** [comment]
看这个

https://github.com/ant-design/ant-design-pro-cli/blob/master/src/fetch-blocks/router.config.js
