### ISSUE TITLE
【bug】下拉按钮区域点击无反应(手机端)

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/ant-design-pro#905]
如题，在手机端访问prod的demo，出现按钮区域点击无反应的bug。
如图：**更多**按钮
手机型号：iphone8plus、Safair
备注：安卓手机偶尔能点出来下拉框，但是一样不是每次都能点出来
![image](https://user-images.githubusercontent.com/26354664/35904263-6d7ce3f6-0c1d-11e8-93b7-8155ed12ae37.png)

**Comment by ddcat1115** [comment]
trigger 改成 click 试试？默认是 hover 的

**Comment by gebilaoman** [comment]
乌龙，trigger少了
