### ISSUE TITLE
🐛[BUG] 开启mfsu编译，全局样式替换不成功

### ISSUE THREAD

**Issue by VegeChou** [ant-design/ant-design-pro#9050]
### 🐛 bug 描述
开启mfsu编译，全局样式替换不成功

通过 config.ts 文件中 theme 字段修改全局样式（例如 primary-color）：
开启 mfsu 编译，部分组件样式替换不成功，比如输入框 boder-color；
关闭 mfsu 编译，全局替换成功

### 🏞 期望结果

全局样式替换成功

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本：^3.5.0
- 浏览器环境：chrome
- 开发环境：Mac OS

**Comment by chenshuai2144** [comment]
是执行顺序的原因，你可以通过修改优先级来完美实现

**Comment by s464446877** [comment]
如何修改优先级

**Comment by VegeChou** [comment]
> 是执行顺序的原因，你可以通过修改优先级来完美实现

@chenshuai2144 如何修改优先级？文档里没有找到说明

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity

**Comment by vision-ken** [comment]
@chenshuai2144 
config.ts中theme里面配置的是变量：
```js
'font-size-sm': '12px',
```
具体应该怎么修改优先级呢，能给个例子吗？
