### ISSUE TITLE
🧐[问题]为什么使用npm install 后，umi就需要重新安装

### ISSUE THREAD

**Issue by Alt-er** [ant-design/ant-design-pro#9051]
### 🧐 问题描述

每次执行npm install  xxx 后 ，使用npm start 启动项目都会报错找不到umi 

重新 npm install umi 后就能正常启动了

**Comment by chenshuai2144** [comment]
只有上帝知道 node_modules 里面有什么恭喜，建议你使用tyarn，超好用
