### ISSUE TITLE
🐛[BUG]v5正式版simple模式安装后样式文件不全？

### ISSUE THREAD

**Issue by sinofaneliu** [ant-design/ant-design-pro#9052]
### 🐛 bug 描述
v5正式版simple模式安装后样式文件不全？安装complete没问题

![image](https://user-images.githubusercontent.com/9162073/132045261-285a77e5-2f14-40de-9b94-28763d6961d3.png)

![image](https://user-images.githubusercontent.com/9162073/132045081-d1cfaec4-a069-4908-a5c0-474fcbf0755a.png)

**Comment by sinofaneliu** [comment]
1. complete安装没问题
2. 关闭mfsu后也没有问题了

**Comment by chenshuai2144** [comment]
complete 才是全部，simple 是最简单的
