### ISSUE TITLE
protable type=form是怎么实现表单的其他元素的item联动🧐[问题]

### ISSUE THREAD

**Issue by 15723185734** [ant-design/ant-design-pro#9053]
### 🧐 问题描述

比如我用Columns实现一个Protable时，Columns中的一个select选项等某个值的时候控制，Columns中其他项显示或者隐藏，
能实现吗？ 如果可以实现请问实现思路是什么？

### 🚑 其他信息

根据权限范围select框判断是否展示 数据权限树
![image](https://user-images.githubusercontent.com/61341868/132129460-d0640b8d-12ef-4d1a-8986-e81577a1491e.png)
![image](https://user-images.githubusercontent.com/61341868/132129505-3794f2c1-2d11-4a58-ab34-074e23680275.png)

**Comment by 15723185734** [comment]
这个问题已经困扰我很久了 希望各位能给个解决方案 我自己尝试了很多解决方案 比如通过useMemo 监听改变columns的hideInForm值 都无法控制，由于我这边封装的太多，拿不出代码展示

**Comment by drizzlesconsin** [comment]
[DOC: 研究下这个看能不能帮到你](https://procomponents.ant.design/components/table#table-linkage_form)

> _这种业务相关的，用 [codesandbox.io](https://codesandbox.io/) 搞个 Demo, 胜万语啊！_

**Comment by xyzabc0004** [comment]
![image](https://user-images.githubusercontent.com/32530210/132187262-aba12c31-90c1-446b-b256-833a83dd0012.png)

我是我的联动的写法，不知道你看不看得上。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/pro-components/pull/3895

看看这个用法应该完美解决了问题了。


如果是select 可以直接使用 dependency  配置，我会自动把dependency  的name 注入到params里面

**Comment by 15723185734** [comment]
> [ant-design/pro-components#3895](https://github.com/ant-design/pro-components/pull/3895)
> 
> 看看这个用法应该完美解决了问题了。
> 
> 如果是选择可以直接使用依赖配置，我会自动把依赖的注入到params里面

自己封装了一个比较全面的组件 支持联动  支持多表单公用一个组件
https://gist.github.com/15723185734/e8ebbd6e90215af3973e55b4829e85f0

**Comment by 15723185734** [comment]
> > [ant-design/pro-components#3895](https://github.com/ant-design/pro-components/pull/3895)
> > 看看这个用法应该完美解决了问题了。
> > 如果是选择可以直接使用依赖配置，我会自动把依赖的注入到params里面
> 
>

 自己封装了一个比较全面的组件支持联动支持多表单公用一个组件 https://gist.github.com/15723185734/e8ebbd6e90215af3973e55b4829e85f0

用该组件实现的一些案列，只用专注于json的配置 
![image](https://user-images.githubusercontent.com/61341868/141735161-677453da-256d-416b-a862-30f71726085b.png)
![image](https://user-images.githubusercontent.com/61341868/141735204-8e849ad7-9ec7-4819-9956-4e16e583e753.png)
![image](https://user-images.githubusercontent.com/61341868/141735309-cc7c7643-c3d5-482c-a34b-aa33b4652b44.png)
![image](https://user-images.githubusercontent.com/61341868/141735343-d167f6cb-cd57-4558-b914-14004eebadaf.png)
![image](https://user-images.githubusercontent.com/61341868/141735455-a0069fa7-ae55-47ad-a7dd-84d915b5e81a.png)
![image](https://user-images.githubusercontent.com/61341868/141735500-b6c8e32a-e786-4fda-95a4-ef49c2a45839.png)
