### ISSUE TITLE
🐛[BUG] 重复执行npm install，会删除已经安装的依赖

### ISSUE THREAD

**Issue by xuchaobei** [ant-design/ant-design-pro#9055]
### 🐛 bug 描述
在一个已经执行过 npm install ，且依赖被正确安装的项目下，再次执行 npm install ，绝大部分已安装依赖会被删除。

### 📷 复现步骤
1. npx create-umi myapp 创建项目，语言选择：JavaScript，模板选择：Simple。
2. 在项目根路径下，执行npm install。 依赖正常安装。
3. 在项目根路径下，再次执行 npm install。 大部分依赖都被删除，包括 umi ，导致后续执行 umi 等相关命令出错。
4.  npm install -verbose 的详细日志见截图。可以发现，再次执行 npm install 时，有大量 uninstall 操作。

 
![image](https://user-images.githubusercontent.com/5110783/132174176-c416073f-b81b-492b-bee8-7a330496c60b.png)

![image](https://user-images.githubusercontent.com/5110783/132174811-c8b509c0-b942-463e-87e3-df4f60f719c5.png)

### 🏞 期望结果

重复执行npm install，不会删除正常安装的依赖

### © 版本信息

- Ant Design Pro 版本:  5.0.0
- umi 版本: ^3.5.0
- 开发环境: mac OS
- npm: 6.14.12
- Nodejs: 12.22.1

**Comment by pxim** [comment]
最新的，我npm install安装个axios，有时候最后umi都会没了；yarn add 有时候也没用；

**Comment by github262302** [comment]
# 用yarn

**Comment by chenshuai2144** [comment]
tyarn  yyds

**Comment by xuchaobei** [comment]
> # 用yarn

既然这样的话，文档里应该写清楚：不支持 npm （或某些场景下不支持npm）吧

**Comment by chenshuai2144** [comment]
如果要用npm，可以用 git clean 清理掉再安装一下
