### ISSUE TITLE
docker 刷新页面会重定向到docker启动端口🧐[问题]

### ISSUE THREAD

**Issue by yyhLogin** [ant-design/ant-design-pro#9056]
### 🧐 问题描述
V5版本
docker80部署，映射到8080
可以正常访问，但是当在页面刷新之后，启动的8080会被重定向到80端口导致页面不见了
### 💻 示例代码
nginx配置
`
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
		listen 80;
		# gzip config
		gzip on;
		gzip_min_length 1k;
		gzip_comp_level 9;
		gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
		gzip_vary on;
		gzip_disable "MSIE [1-6]\.";
		location / {
			root   /usr/share/nginx/html;
			index  index.html index.htm;
		}
		location ^~ /auth/ {
			# 用于配合 browserHistory使用
			root /usr/share/nginx/html;
#			alias D:/env/nginx-1.21.0/html/auth/;
			try_files $uri $uri/ /index.htm;
			# 如果有资源，建议使用 https + http2，配合按需加载可以获得更好的体验
			# rewrite ^/(.*)$ https://preview.pro.ant.design/$1 permanent;
		}
		location /api { #反向代理， 
			proxy_pass   http://111.222.333:9152; # http请求地址
			rewrite  ^/api/(.*)$ /$1 break; 
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
			# proxy_cookie_domain localhost http://192.168.1.249:8000;            
		}       
        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
`
项目配置
`export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  base: '/auth/',
  publicPath: '/auth/',
  // history: {
  //   type: 'hash',
  // },
  manifest: {
    basePath: '/auth/',
    publicPath: '/auth/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},
  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
  nodeModulesTransform: { type: 'none' },
  mfsu: {},
  webpack5: {},
  exportStatic: {},
});`

### 🚑 其他信息
之前见到有人提供V4版本这个问题，没看到答案，所以又提了一次

**Comment by yyhLogin** [comment]
![image](https://user-images.githubusercontent.com/19282994/132203943-15d416b2-a3a4-47f7-8a09-cc40a3833e9b.png)

**Comment by yyhLogin** [comment]
问题好像就出在了docker里Nginx启动端口和映射的端口不一样导致，请问这个地方怎么处理

**Comment by xyzabc0004** [comment]
直接把docker里面的80映射到外面的80吧

**Comment by yyhLogin** [comment]
> 直接把docker里面的80映射到外面的80吧

没别的办法吗，我看vue打包的项目没有这个问题

**Comment by lg0812** [comment]
是因为exportstatic配置，https://umijs.org/config#exportstatic

**Comment by yyhLogin** [comment]
> 是因为exportstatic配置，https://umijs.org/config#exportstatic

需要怎么配置呢，我看这个介绍不知道怎么下手

**Comment by lg0812** [comment]
可以选择删掉这个配置项



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: talkbird ***@***.***&gt;
发送时间: 2021年9月7日 18:50
收件人: ant-design/ant-design-pro ***@***.***&gt;
抄送: lg0812 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ant-design/ant-design-pro] docker 刷新页面会重定向到docker启动端口��[问题] (#9056)

**Comment by yyhLogin** [comment]
> 可以选择删掉这个配置项 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: talkbird ***@***.***&gt; 发送时间: 2021年9月7日 18:50 收件人: ant-design/ant-design-pro ***@***.***&gt; 抄送: lg0812 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[ant-design/ant-design-pro] docker 刷新页面会重定向到docker启动端口��[问题] (#9056)

删掉这个配置，F5刷新直接就找不到页面了，应该还是需要这个配置的

**Comment by lg0812** [comment]
location / {
        try_files $uri $uri/ /index.html;
    }

**Comment by lg0812** [comment]
你删除exportstatic配置后，要重新build。 然后看下 dist 目录下是不是有 /login/index.html 这样的文件，这个文件 可能会被 nginx 中配置的 $uri/ 匹配到，然后你就访问到  /login/ 这样的路径了, 然后就出现你上面截图的那个问题了。

**Comment by yyhLogin** [comment]
> 你删除exportstatic配置后，要重新build。 然后看下 dist 目录下是不是有 /login/index.html 这样的文件（删除exportstatic配置后，应该不会有了），这个文件 可能会被 nginx 中配置的 $uri/ 匹配到，然后你就访问到 /login/ 这样的路径了, 然后就出现你上面截图的那个问题了。

重新build之后只有根目录有个index.html，之前的子文件夹login这些都没了，现在刷新还是不行，Nginx需要怎么配置呢

**Comment by laoxubuer** [comment]
server下添加 server_name_in_redirect off; 亲测可行
