### ISSUE TITLE
想问一下and-design-pro官网预览中的源码在哪里可以获取？

### ISSUE THREAD

**Issue by Ervilhas-Liu** [ant-design/ant-design-pro#9057]
想问一下and-design-pro官网预览中的源码在哪里可以获取？

**Comment by OnlyEatCairoubao** [comment]
在all-blocks这个分支下

**Comment by OnlyEatCairoubao** [comment]
> 想问一下and-design-pro官网预览中的源码在哪里可以获取？

在all-blocks这个分支下

**Comment by Ervilhas-Liu** [comment]
> > 想问一下and-design-pro官网预览中的源码在哪里可以获取？
> 
> 在all-blocks这个分支下

感谢~

**Comment by xgj1988** [comment]
拉下来 运行就报错。

**Comment by Benleie** [comment]
运行npm run start，就报错啊
![image](https://user-images.githubusercontent.com/24362871/211234147-f15f3f3a-dc3b-4101-be43-83d148845342.png)

**Comment by javalcl** [comment]
官方是不是没打算放出预览版的代码？

**Comment by javalcl** [comment]
刚试过了
npm install --force
npm run start
即可运行预览版
