### ISSUE TITLE
请问怎么访问自己项目的openApi文档？🧐[问题]

### ISSUE THREAD

**Issue by 15723185734** [ant-design/ant-design-pro#9058]
### 🧐 问题描述

访问报错：Not Found /umi-plugins_openapi.json
但是我通过swagger生成的openapi请求是没有问题的 可以使用

![image](https://user-images.githubusercontent.com/61341868/132299836-413f4ab2-1e85-4b18-9c33-5d12e29d7ca5.png)

![image](https://user-images.githubusercontent.com/61341868/132299903-f038ab82-b09f-4017-931d-42f104dbb531.png)
![image](https://user-images.githubusercontent.com/61341868/132300130-12e4a844-0041-4833-b92e-4dd2bae5b233.png)

![image](https://user-images.githubusercontent.com/61341868/132299626-77d834a3-7154-4358-93c0-1d7733b11c36.png)

**Comment by github262302** [comment]
schemaPath 需要json文件
