### ISSUE TITLE
🐛[BUG]开启mfsu后设置theme无效

### ISSUE THREAD

**Issue by s464446877** [ant-design/ant-design-pro#9059]
### 🐛 bug 描述

开启mfsu后，设置theme任何变量都无效，关闭后theme正常生效
### 🏞 期望结果

开启mfsu后theme可以正常使用
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by zozopen** [comment]
今天也遇见这个问题了，等待回复

**Comment by WuJiY** [comment]
> 清空缓存并硬性重新加载

没有效果

**Comment by chenshuai2144** [comment]
现在还不支持。。只能先关掉了

**Comment by WenLonG12345** [comment]
有什么解决方案吗？
