### ISSUE TITLE
🧐[问题]Pro项目从一台机器移动到另一台后，项目样式失效如何解决

### ISSUE THREAD

**Issue by moluzhui** [ant-design/ant-design-pro#9060]
### 🧐 问题描述
多人协作时，项目push到gitlab后在另一台电脑拉取，运行后样式失效，并且尝试直接压缩包形式同样失效，两台电脑node版本并不完全相同，但都是v14.17.+

### 💻 示例代码
![image](https://user-images.githubusercontent.com/44611938/132345303-c2046fee-81fb-40a7-89bf-29f78e94fdd9.png)

**Comment by drizzlesconsin** [comment]
关闭 [mfsu](https://umijs.org/config#mfsu) 运行一次(`npm start`)，再开启 `mfsu` 重新启动试试。

**Comment by moluzhui** [comment]
> 关闭 [mfsu](https://umijs.org/config#mfsu) 运行一次(`npm start`)，再开启 `mfsu` 重新启动试试。

关闭(通过注释)后启动可以，但是再开启依旧无样式
```
# config.ts
  // mfsu: {},
```

**Comment by github262302** [comment]
# 删除所有.umi文件(自动生成的配置文件)  node_modules 
# yarn && yarn start

**Comment by moluzhui** [comment]
> # 删除所有.umi文件(自动生成的配置文件) node_modules
> # yarn && yarn start

试过了还是样式不生效

**Comment by chenshuai2144** [comment]
这样试试一般都不会有问题
```
git clean -dfx
yarn
```
