### ISSUE TITLE
🐛[BUG] PageContainer是个什么玩劣份子。header头怎么都干不掉呢！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#9061]
直接上图吧！
![图片](http://oss.jibei.ycoto.cn/temp/WX20210908-104019%402x.png)
红圈那块。我在app.tsx里设置了
```
  breadcrumbRender: false,
```
同时也设置了
```
<PageContainer title={false} ghost={false} header={undefined} breadcrumbRender={false}>
</PageContainer>
```
它还是显示留白，就想问下这狗皮膏药如何去掉，我不想显示它！

控制台查看节点
```
<div class="ant-pro-page-container">
  <div class="ant-pro-page-container-warp">
  <div class="ant-page-header"></div>
  </div>
  <div class="ant-pro-grid-content">
  </div>
</div>
```

© 版本信息
Ant Design Pro 版本: [e.g. 5.0.0]
umi 版本:[3.5.17]
浏览器环境: chrome(最新)
开发环境 [macos]

**Comment by github262302** [comment]
全局css 试试 height:0 display:none

**Comment by codedart2018** [comment]
> 全局css 试试 height:0 display:none

css肯定不合理的。虽然我不想要，但不是所有都不想要！

**Comment by github262302** [comment]
![截屏2021-09-08 下午12 43 36](https://user-images.githubusercontent.com/71603326/132447996-028dc4f2-ea6d-4de1-841d-5e28247c0a63.png)
![截屏2021-09-08 下午12 44 09](https://user-images.githubusercontent.com/71603326/132448001-62608f6c-0109-4517-be67-090272364929.png)
![截屏2021-09-08 下午12 44 38](https://user-images.githubusercontent.com/71603326/132448011-a71f886c-27da-41df-8032-421c1852168e.png)
![截屏2021-09-08 下午12 44 58](https://user-images.githubusercontent.com/71603326/132448013-f7a677fb-5ae3-4def-b240-7df1053a3ae3.png)

**Comment by chenshuai2144** [comment]
是个bug，上次版本更新修掉了，判断写反了

**Comment by codedart2018** [comment]
> 是个bug，上次版本更新修掉了，判断写反了

我重新安装了，你们没有修复掉吧 ghost={true} 虽然白色块不显示了　但是占位还在啊。这太坑了吧。你们额外加个参数一招否定这个　ant-pro-page-container-warp　这个div 行不行哦。太坑了

**Comment by qq1170623178** [comment]
建议官方收纳一下，不想用header，可以加个参数header={false}来关闭的功能

**Comment by codedart2018** [comment]
> 建议官方收纳一下，不想用header，可以加个参数header={false}来关闭的功能

我都还没有处理这个东西。这个确实应该关闭，不应该留白。很讨厌的

**Comment by qq1170623178** [comment]
可以好好利用这个占位，正好当个maigin了，再不行就只能用css了
