### ISSUE TITLE
EditableProTable表格组件在新建一行数据时，报错

### ISSUE THREAD

**Issue by Ervilhas-Liu** [ant-design/ant-design-pro#9069]
### 🧐 问题描述

EditableProTable表格组件在新建一行数据时，报错。报错信息为:```Warning: [antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode. ```
### 💻 示例代码
        <EditableProTable<API.RuleListItem, API.PageParams>
            headerTitle='Enquiry form'
            rowKey="wallpaper_id"
            actionRef={actionRef}
            request={getList}
            search={{
                defaultCollapsed:false,
                labelWidth: 90,
                collapseRender:false
            }}
            pagination={
                {
                    defaultPageSize:10
                }
            }
            columns={columns}
            
            recordCreatorProps={{
                record: () => ({
                  wallpaper_id: Date.now(),
                }),
            }}
        />

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/66231384/132495445-f01b0bf8-be74-4f4a-b890-b9de8081d37d.png)

**Comment by chenshuai2144** [comment]
可编辑表格和分页一起用一定会有这个问题的。

强迫症不严重就忽略掉。不然就关掉 pagination
