### ISSUE TITLE
RangePicker 放在table 当筛选条件位置会变

### ISSUE THREAD

**Issue by LKCheng** [ant-design/ant-design-pro#907]
![image](https://user-images.githubusercontent.com/10054789/35917020-7967af6e-0c47-11e8-9268-da2c4e3e993c.png)
第二次移入要选择日期的时候就位置变了，如下图。求指教怎么改
![image](https://user-images.githubusercontent.com/10054789/35917000-5d260ee0-0c47-11e8-9d9d-627a058f2108.png)

**Comment by chenshuai2144** [comment]
css的问题吧
