### ISSUE TITLE
> 我也是，楼主解决没

### ISSUE THREAD

**Issue by 123wangjinfeng** [ant-design/ant-design-pro#9070]
> 我也是，楼主解决没

我解决不了，等陈大师亲自解决。

_Originally posted by @kaoding in https://github.com/ant-design/ant-design-pro/issues/6561#issuecomment-630604483_

**Comment by 123wangjinfeng** [comment]
楼主，解决没

**Comment by chenshuai2144** [comment]
重新更新一下就能解决
