### ISSUE TITLE
🧐[问题]complete版示例/list/table-list页面无数据显示，添加等操作均无效

### ISSUE THREAD

**Issue by moluzhui** [ant-design/ant-design-pro#9071]
### 🧐 问题描述
项目打算参考此页面的部分控件，但是似乎其本身存在错误无法显示mock信息，新增等操作也无法进行，并且出现`const sorter = JSON.parse(params.sorter as any);`报错`SyntaxError: Unexpected token u in JSON at position 0`
新建时Modal传递的数据也是未定义**undefined**
```
const { method, name, desc, key } = body;
```

### 🚑 其他信息
通过yarn create clone的complete项目，ant design pro为v5.0.0
```
# package.json
  "name": "ant-design-pro",
  "version": "5.0.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
```
node.js 版本为v14.17.5

**Comment by chenshuai2144** [comment]
修复了，重新拉取一下
