### ISSUE TITLE
🐛[BUG]想问一下有谁成功阻止了回车提交事件，尤其是富文本。深受其害啊，天理不容啊！！！！🤬🤬🤬😡😡😡

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#9073]
### 🐛 bug 描述

form表单应该给出一个参数完全阻止回车事件，回车事件。
深受其害过程，
在表单中用了富文本编辑器（wangEditor）,富文本编辑器中本来回车用的比较多，一回车就给提交数据，找了半天找来找去也没有发现有全局阻止的。冒泡阻止吧，阻止了会导致编辑器无法回车。
我退而求其次吧，submiter设置成false, onShinsh不使用。我自己用ref.submit来提交。恩暂时没有发现问题。但是我一旦在别的表单上增加了rules校验规则，好家伙，我在富文本编辑器中回车就把别的字段给校验了。能不能加一个全局禁止回车啊。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by codedart2018** [comment]
@chenshuai2144 什么时候发包呢！

**Comment by chenshuai2144** [comment]
@codedart2018  明天就发，我这里还有点车要上
