### ISSUE TITLE
🐛[BUG] proFromText 添加 addonAfter 时, 表单校验重复

### ISSUE THREAD

**Issue by lingting** [ant-design/ant-design-pro#9074]
### 🐛 bug 描述
ProFormText 如果添加了 addonAfter, 表单校验的错误信息会展示多次

### 🏞 期望结果
字段未填写时, 表单校验提示值未填写(仅提示一次)

### 💻 复现代码

`     <ProFormText
        required
        allowClear
        name="title"
        label="菜单名称"
        rules={[{ required: true, message: '请输入菜单名称!' }]}
        addonAfter={
          <Button onClick={() => setShowI18n(!showI18n)} type="primary">
            {!showI18n ? (
              <>
                <Icon type="down" /> 展开
              </>
            ) : (
              <>
                <Icon type="up" /> 收起
              </>
            )}
            国际化配置
          </Button>
        }
      />`
### © 版本信息

- Ant Design Pro 版本:  5
- umi 版本 ^v3.4.0
- 浏览器环境 chrome
- 开发环境 win10

### 🚑 其他信息

![微信图片_20210909220437](https://user-images.githubusercontent.com/59352063/132700788-76f897bf-a422-4032-8526-cca815b68d6d.png)

**Comment by chenshuai2144** [comment]
修掉了，可以更新一下

ref https://github.com/ant-design/pro-components/pull/3611
