### ISSUE TITLE
还是不行啊

### ISSUE THREAD

**Issue by 123wangjinfeng** [ant-design/ant-design-pro#9075]
重新更新一下依赖就能解决

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/9070#issuecomment-915823923_

**Comment by chenshuai2144** [comment]
搞个复线，把事情讲清楚

**Comment by 123wangjinfeng** [comment]
啥意思？

**Comment by 123wangjinfeng** [comment]
能远程帮忙搞一下吗？
