### ISSUE TITLE
🧐[问题]请问node版本低于12.20怎么办呢？

### ISSUE THREAD

**Issue by fei199225** [ant-design/ant-design-pro#9076]
### 🧐 问题描述

本地环境node版本14.x，之前发包没跟上的时候报错，是用yarn install + yarn add isomorphic-form-data 后启动；
线上部署编译，node版本12.16.2，用yarn install + yarn add isomorphic-form-data 也是可以的；
但是现在不需要yarn add isomorphic-form-data了，反而yarn install 时会报错：
error formdata-node@4.2.0: The engine "node" is incompatible with this module. Expected version ">= 12.20". Got "12.16.2"；
那低版node就不行了么？😭本地啥版本都行，部署的没办法升级。help～

### 💻 示例代码

help～

**Comment by zhouchunguang2020** [comment]
百度 node ，重新下载，然后安装就行了

**Comment by fei199225** [comment]
> 百度 node ，重新下载，然后安装就行了

线上部署没办法升级。

**Comment by zhouchunguang2020** [comment]
之前我本地提示我node版本过低，用npm安装依赖是可以的。可以试一下

**Comment by fei199225** [comment]
> 之前我本地提示我node版本过低，用npm安装依赖是可以的。可以试一下

我本地没问题，是线上部署环境版本低嘞～

**Comment by chenshuai2144** [comment]
`yarn  --ignore-engines`

这个可以忽略掉版本检查
