### ISSUE TITLE
🐛[BUG] 生产环境右边的配置栏依旧渲染

### ISSUE THREAD

**Issue by wangshangkun** [ant-design/ant-design-pro#9077]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
需要手动删除，只是不推荐，不是完全不能用

**Comment by wangshangkun** [comment]
> 需要手动删除，只是不推荐，不是完全不能用

请问在哪里能删除不显示右边的配置栏呢，一部署到服务器就显示出来了，还是有点影响的。

**Comment by chenshuai2144** [comment]
用环境变量设置一下
