### ISSUE TITLE
🧐[问题] 请问 ant-design-pro 如何集成okta

### ISSUE THREAD

**Issue by pengzj** [ant-design/ant-design-pro#9078]
我们需要在项目中使用okta，但是不知道如何 集成，请指导，感谢。

**Comment by chenshuai2144** [comment]
okta是什么？有资料吗?

**Comment by pengzj** [comment]
https://developer.okta.com/code/?_ga=2.29158524.1342846012.1631674509-1632756088.1630290088

**Comment by pengzj** [comment]
@chenshuai2144 国外的单点登录

**Comment by chenshuai2144** [comment]
这个应该是后端接入的吧，前端负责401了跳转去登陆
