### ISSUE TITLE
🧐[问题] 在antdpro中需要通过iframe打开其他项目中的html文件，但是会报如下错误，请问有办法处理吗

### ISSUE THREAD

**Issue by ai180508** [ant-design/ant-design-pro#9084]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/77037794/132822792-501a4717-995b-401c-9c92-392df81eb938.png)

###

这个处理方式是参照这篇博客来的：
https://blog.csdn.net/qq_38519358/article/details/100667730?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_title~default-0.no_search_link&spm=1001.2101.3001.4242
其中html-loader的配置方式在umi中并不适用，该如何配置呢？或者有没有其他什么处理方法

**Comment by drizzlesconsin** [comment]
```diff
+ import data from './2.js'
- import data from './2.html'
```
```js
// 2.js
export default `
<html>
  ...
</html>
`
```

**Comment by ai180508** [comment]
> ```diff
> +从“./2.js”
> 导入数据-从“./2.html”导入数据
> ```
> 
> ```js
> // 2.js
> 导出 默认 ` 
> <html> 
>   ... 
> </html> 
> `
> ```

![image](https://user-images.githubusercontent.com/77037794/132825947-d464e201-48a1-4126-b972-5da1007fe25f.png)
会报这个错误

**Comment by drizzlesconsin** [comment]
...闭合标签
先试一下简单的标签 <h1></h1>

**Comment by ai180508** [comment]
> ...闭合标签
> 先试一下简单的标签

![image](https://user-images.githubusercontent.com/77037794/132828652-3dc33253-5351-4e25-aaea-f316f35a5092.png)
是这里的问题，删除后面的 \9就可以了，但是通过这个方式，原页面引用的img和js都不起作用，请问这个可以解决吗

**Comment by chenshuai2144** [comment]
看起来是file-loader 配置的原因，不能放到public中，然后用绝对路径引入吗
