### ISSUE TITLE
🐛[BUG]动态菜单component属性必须要和 path路径一样吗,我不可以在page使用别的文件夹吗

### ISSUE THREAD

**Issue by huiruo** [ant-design/ant-design-pro#9086]
### 🐛 bug 描述
动态菜单component属性必须要和 path路径一样吗,我不可以在page使用别的文件夹吗(和path路径不一样的组件，如下面例子中的‘/mainPage/index’)

        {
          name: 'Tanalysis',
          icon: 'smile',
          path: '/dashboard/Tanalysis',
          component: '/mainPage/index',
         //component: '/dashboard/Tanalysis',
        },
比如在这个路由中加载 '/mainPage/index',但是加载失败，必须实际上加载 '/dashboard/Tanalysis'才能成功
这个需求该怎么实现？

### 📷 复现步骤

我想在这个路由中加载 '/mainPage/index',但是加载失败，必须加载 '/dashboard/Tanalysis'才能成功

弃用了，动态配置在config.ts 里面，根本无法实现需求，太不灵活了

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
不能的，路由和菜单不是一个概念。

菜单只是个导航，路由实在编译的时候确定的，再也不能改了
