### ISSUE TITLE
🐛[BUG] console 输出行数有问题

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#9088]
### 🐛 bug 描述

使用 umi 3.5.17 console输出行数不是打包前的文件行数

### 📷 复现步骤

更新到3.5.17支持console

### 🏞 期望结果

开发环境下可以正常显示输出文件位置

### © 版本信息

- umi 版本 3.5.17

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/34082148/132933873-6efa6e84-9872-4394-9648-b90ee3473415.png)
![image](https://user-images.githubusercontent.com/34082148/132933876-f8386445-997b-465d-9cff-f82cd3d5e0c5.png)

**Comment by chenshuai2144** [comment]
@sorrycc  云谦老师看看，我也碰到了这个问题，debug起来很痛苦

**Comment by chao325** [comment]
解决了吗，大佬
