### ISSUE TITLE
与后台进行交互的问题

### ISSUE THREAD

**Issue by anghuang** [ant-design/ant-design-pro#909]
![image](https://user-images.githubusercontent.com/17631600/35954187-3e689dca-0cc3-11e8-8efd-be0494288275.png)

按照文档上和百度的结果这么设置，通过start:no-proxy命令但是
![image](https://user-images.githubusercontent.com/17631600/35954201-4cfe72d8-0cc3-11e8-90cd-c81ba18fa5a1.png)请求地址还是没有改过来，还需要改哪里，求救！！！

**Comment by afc163** [comment]
请求地址是按照你的源码来的，不会因为 proxy 发生变化的。

**Comment by anghuang** [comment]
![image](https://user-images.githubusercontent.com/17631600/35957322-f7c51bce-0cd5-11e8-89ed-ed5c987fd2b9.png)
![image](https://user-images.githubusercontent.com/17631600/35957339-0ec9e066-0cd6-11e8-9575-c2ed1f3e99fe.png)
经过修改以后还是有问题
