### ISSUE TITLE
🧐[问题] npm run build 后提示 cant resolve @@/dumi/apis

### ISSUE THREAD

**Issue by wangshangkun** [ant-design/ant-design-pro#9091]
### 🧐 问题描述

如题。

### 💻 示例代码
`in ./node_modules/@umijs/preset-dumi/lib/theme/hooks/useApiData.js

Module not found: Error: Can't resolve '@@/dumi/apis' in '/Users/wangshk/WebstormProjects/shipping/node_modules/@umijs/preset-dumi/lib/theme/hooks'

ERROR in ./node_modules/@umijs/preset-dumi/lib/theme/hooks/useApiData.js 19:38-61
Module not found: Error: Can't resolve '@@/dumi/apis' in '/Users/wangshk/WebstormProjects/shipping/node_modules/@umijs/preset-dumi/lib/theme/hooks'
 @ ./node_modules/@umijs/preset-dumi/lib/theme/index.js 113:41-70
 @ ./src/pages/user/manage/index.tsx 20:0-52 115:32-36
 @ ./src/.umi-production/core/routes.ts 208:19-210:77
 @ ./src/.umi-production/umi.ts 9:0-42 25:33-42

webpack compiled with 1 error
`

### 🚑 其他信息

macos 11.2.3

**Comment by chenshuai2144** [comment]
```shell
git add .
git clean -dfx
npm I tyarn  -g
tyarn
```
可以用这个方式重新安装一下依赖
