### ISSUE TITLE
啥意思？能远程帮忙搞一下吗？

### ISSUE THREAD

**Issue by 123wangjinfeng** [ant-design/ant-design-pro#9092]
搞个复现，把事情讲清楚
不要挖坟

_Originally posted by @chenshuai2144 in https://github.com/ant-design/ant-design-pro/issues/9075#issuecomment-916626373_

**Comment by chenshuai2144** [comment]
先把事情讲清楚。不要乱开issue。GitHub 不是你一个人的

**Comment by 123wangjinfeng** [comment]
奥


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 啥意思？能远程帮忙搞一下吗？ (#9092)





 
先把事情讲清楚。不要乱开issue。GitHub 不是你一个人的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123wangjinfeng** [comment]
点完菜单，菜单就立马收起来了，还要就是没有选择状态


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 啥意思？能远程帮忙搞一下吗？ (#9092)





 
先把事情讲清楚。不要乱开issue。GitHub 不是你一个人的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123wangjinfeng** [comment]
能不能远程帮忙一下啊？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 啥意思？能远程帮忙搞一下吗？ (#9092)





 
先把事情讲清楚。不要乱开issue。GitHub 不是你一个人的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
