### ISSUE TITLE
🐛[BUG] 十万火急，生产环境 tyarn run build Can't resolve '@@/dumi/apis'

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#9093]
### 🐛 bug 描述

tyarn run build 后报错Can't resolve '@@/dumi/apis'

### 📷 复现步骤

tyarn run build 后报错Can't resolve '@@/dumi/apis'

### 🏞 期望结果

正常编译

### 💻 复现代码

tyarn run build

### © 版本信息

- Ant Design Pro 版本: 5.0.0-beta.2
- umi 版本 3.4.0
- 浏览器环境
- 开发环境 centos

### 🚑 其他信息

git add .
git clean -dfx
npm i tyarn  -g
tyarn
这样操作过了，不行。
写程序这么多年，从来没出过这么大的问题

**Comment by ideaviewes** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🧐[问题] npm run build 后提示 cant resolve @@/dumi/apis #9091](https://github.com/ant-design/ant-design-pro/issues/9091)][🧐[问题] npm run build 后提示 cant resolve @@/dumi/apis][69%]

根据提示操作了，没有任何作用

**Comment by chenshuai2144** [comment]
```
git clean -dfx
tyarn 
```

这种是因为依赖版本锁包导致的

**Comment by ideaviewes** [comment]
@chenshuai2144 ,
git clean -dfx
tyarn 
按照这个操作了，还是不行，同样是问题

**Comment by ideaviewes** [comment]
@chenshuai2144 ,我这个是生产环境，
已经挂了快一个小时了，有什么办法能让这个快速恢复一下的吗？

**Comment by chenshuai2144** [comment]
生产环境怎么会有 import？

清空缓存重新部署一下吧

**Comment by ideaviewes** [comment]
生产环境怎么会有 import？不是很理解这个是什么意思
缓存也请过了，还是同样的问题，确认不是umi或是antd pro的bug吗？

**Comment by chenshuai2144** [comment]
那就是你锁包了吧，我刚刚重试了ci，没有碰到相同的问题

**Comment by ideaviewes** [comment]
并没有，我看了git仓库中没有yarn.lock文件，这个问题具体是哪个依赖的版本不对？

**Comment by ideaviewes** [comment]
我把服务器上的node环境整个删除掉，重装后还是这个问题

**Comment by chenshuai2144** [comment]
umi 的版本的依赖。

**Comment by ideaviewes** [comment]
我现在要解决这个问题的思路大概是什么？
我弄了个新的服务器，
安装的新的node环境，也是同意的问题

**Comment by ideaviewes** [comment]
我本地有一个ant design pro v5的正式版，我试了下，是可以build成功的，5.0.0-beta.2怎么升级成正式版？

**Comment by ideaviewes** [comment]
最后解决了，是我引入Link的时候，不小心导错包了
![61b08ac8c88dad57650da24bd2053bc](https://user-images.githubusercontent.com/5431843/133069493-208b65cd-646e-4e2d-a501-2846f38e9a0e.png)
问题就是出在这里，跟版本啥的都无关
