### ISSUE TITLE
🐛[BUG] 安装 umi-plugin-setting-drawer 会导致构建时更改 layout title 失败

### ISSUE THREAD

**Issue by sakura-flutter** [ant-design/ant-design-pro#9095]
### 🐛 bug 描述

安装 umi-plugin-setting-drawer 会导致构建时更改 layout title 失败

### 📷 复现步骤

想要更改标题为：新标题

运行 npm start，本地环境可以更改成功，标题为：新标题
构建发布运行 npm run build，后再运行 npm rum serve 查看，菜单和网站标题依然为最初的 Ant Design Pro，但是在界面更改一下 SettingDrawer 设置，才会触发更新

### 🏞 期望结果

标题更改成功

### 💻 复现代码

https://github.com/sakura-flutter/ant-design-pro-template-layout-title

### © 版本信息

- Ant Design Pro 版本: [5]
- umi 版本 3.5.18
- 浏览器环境 Chrome 93
- 开发环境 [windows 10]

### 🚑 其他信息

变更：https://github.com/sakura-flutter/ant-design-pro-template-layout-title/commit/2956a0b21ce90bfa8408dbb7da29c6fa956fa6e5

这个问题看起来与 #8526、#8890 类似

**Comment by chenshuai2144** [comment]
yarn add umi-plugin-setting-drawer

安装即可使用

**Comment by hatch1994** [comment]
我的package.json 安装了 "umi-plugin-antd-theme": "^2.1.2" , "umi-plugin-setting-drawer": "^1.0.3"
并且也在app.tsx getInitialState方法中初始化了插件 
`export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser;
  settingDrawer?: Partial<SettingDrawerProps>;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
}> {
  const fetchUserInfo = async () => {
    try {
      const msg = await queryCurrentUser();
      return msg.data;
    } catch (error) {
      history.push(loginPath);
    }
    return undefined;
  };
  // 如果是登录页面，不执行
  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: {},
      settingDrawer: {
        hideCopyButton: true,
        hideHintAlert: true,
      },
    };
  }
  return {
    fetchUserInfo,
    settings: {},
  };
}`

**Comment by hatch1994** [comment]
@chenshuai2144 ？？？？？为何不回答我的问题了？

**Comment by chenshuai2144** [comment]
我为啥一定要回答你的问题？

**Comment by hatch1994** [comment]
@chenshuai2144 KPI项目，顺便开个源？这也怪我，贵厂一直以来都是喜欢造轮子，弃轮子，对你我太苛刻了。 egg, weex。。。 哈哈哈

**Comment by chenshuai2144** [comment]
开源的意义就是不满意可以自己改，没手就不要用开源。你也没有商业订阅，我们也没有义务 24*7的回复你。

如果你真的想好好用好开源社区，就像 @Derrick 一样提供最小复线，进行根因分析。而不是像个小丑一样靠道德绑架和污名化商业公司来希望别人帮你解决问题

**Comment by sakura-flutter** [comment]
There's no timetable ATM.
