### ISSUE TITLE
🧐[svg图标如何加载进去使用？]

### ISSUE THREAD

**Issue by apgk** [ant-design/ant-design-pro#9096]
### 🧐 问题描述

由于官方的icon有些不够使用，自己扩展了，一些采用svg方式
在菜单中死活不能用

左侧菜单采用动态拼接的

### 💻 示例代码

src->cord->icons.js 已经加载
import bxAnaalyse from '@/assets/icons/bx-analyse.svg?inline'
export {bxAnaalyse }

在路由中我直接使用Icon: 'bxAnaalyse'
但是无效，前端没有渲染出来，能看到<i class="anticon anticon-bxAnaalyse ></i>

**Comment by chenshuai2144** [comment]
iconfont 需要以icon开头

**Comment by apgk** [comment]
> iconfont 需要以icon开头

单纯的加判断使用可以的 采用
const IconFont = Icon.createFromIconfontCN({ scriptUrl: iconFront })
Vue.component('icon-font', IconFont)
这样在页面中使用 <icon-font type="xxx">可行
但目前想扩展的图标在菜单中使用，看了支持svg这种，但案例中我按照设置去，没生效。

**Comment by apgk** [comment]
官方建议采用方式：https://github.com/visualfanatic/vue-svg-loader/tree/dev/docs
文档地址：[https://www.antdv.com/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-SVG-%E5%9B%BE%E6%A0%87](https://www.antdv.com/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-SVG-%E5%9B%BE%E6%A0%87)

src->cord->icons.js 
`/**
 * Custom icon list
 * All icons are loaded here for easy management
 * @see https://vue.ant.design/components/icon/#Custom-Font-Icon
 *
 * 自定义图标加载表
 * 所有图标均从这里加载，方便管理
 */
import bxAnaalyse from '@/assets/icons/bx-analyse.svg?inline'
export { bxAnaalyse }`

vue.Config.js内已经有这个了

` chainWebpack: (config) => {
    config.resolve.alias
      .set('@$', resolve('src'))

    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()
    svgRule
      .oneOf('inline')
      .resourceQuery(/inline/)
      .use('vue-svg-icon-loader')
      .loader('vue-svg-icon-loader')
      .end()
      .end()
      .oneOf('external')
      .use('file-loader')
      .loader('file-loader')
      .options({
        name: 'assets/[name].[hash:8].[ext]'
      })

    // if prod is on
    // assets require on cdn
    if (isProd) {
      config.plugin('html').tap(args => {
        args[0].cdn = assetsCDN
        return args
      })
    }
  },
`

**Comment by apgk** [comment]
> 有兴趣帮我们补充一下文档吗？

不是这个就是项目内的源代码，就是这样也无法调用

**Comment by chenshuai2144** [comment]
用 menuItemRender 自定义来设置一下
