### ISSUE TITLE
[问题]看不到umi ui的设计器

### ISSUE THREAD

**Issue by wz2cool** [ant-design/ant-design-pro#9097]
用脚手架创建的项目 然后 yarn start 启动项目 但是就是找不到教程里面那个小球， 希望大家帮忙看看

 
![image](https://user-images.githubusercontent.com/11556152/133188267-a0f626cc-8ed2-4615-8cf4-e865b76ceb69.png)

这个小球在项目里面就是看不到

**Comment by wz2cool** [comment]
![image](https://user-images.githubusercontent.com/11556152/133187010-a4081798-8f5f-48ff-a443-d8dd92225820.png)
这个小球在项目里面就是看不到

**Comment by chenshuai2144** [comment]
需要自己装插件，已经停止维护了，不推荐使用
