### ISSUE TITLE
🐛[BUG]通过预览页面,登录报错405

### ISSUE THREAD

**Issue by tuihou123321** [ant-design/ant-design-pro#9099]
### 🐛 bug 描述

通过预览页面登录报错
https://preview.pro.ant.design/user/login 

![image](https://user-images.githubusercontent.com/7146036/133203603-870580cf-cf6c-4fce-8da5-572cc2bef962.png)
![image](https://user-images.githubusercontent.com/7146036/133203628-10b77a4c-afa1-4086-8e49-219f479c0920.png)
![image](https://user-images.githubusercontent.com/7146036/133203647-334f7dd8-05bd-48ea-9b0d-006f266d3f01.png)

**Comment by chenshuai2144** [comment]
亲测可以，清空缓存的

**Comment by Gonaldo7** [comment]
@chenshuai2144 我今天重新安装项目，首次打开还是登录报405，mock默认起不来？

**Comment by zjxpcyc** [comment]
@chenshuai2144 我这边也是的，没办法，现在新建项目，都是直接拷贝之前的

**Comment by chenshuai2144** [comment]
使用 yarn start
