### ISSUE TITLE
🧐[问题] 控制台出现很多Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#9100]
### 🧐 问题描述
<img width="1164" alt="截屏2021-09-14 下午7 54 08" src="https://user-images.githubusercontent.com/183884/133253061-72762aed-02a3-46d6-9b50-813f417a86c1.png">

这些是哪里出了问题，进入项目就会出现这个

**Comment by github262302** [comment]
用了JSON.strfly 什么的么 定义默认值就好了

**Comment by chenshuai2144** [comment]
忽略掉吧， mfsu 打开导致的
