### ISSUE TITLE
🐛antd pro v5怎么实现两个请求控制同一个数据源

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-pro#9101]
### 🐛 bug 描述
假如我现在使用protalbe 如果数据源为dataSource ,现在我页面加载完成的时候有一个请求得到dataSource ,然后我再进行查询，根据条件查询完成之后我又得到一个数据源，如果都能指定为dataSource我觉得就很完美，但是目前我用下来就是查询出来的数据就不能再使用dataSource,那么这个时候我又想让我的表格显示 我查询出来的数据，请问要如何 实现。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by sangyuren** [comment]
useState

**Comment by tlianglstyle** [comment]
自定义调取数据的方法，在方法里面返回不同的数据源
`const getData = async(params:any,options?:any)=>{
...
}`
`<ProTable rowKey={config.rowKey} request={getData} /> `
