### ISSUE TITLE
🧐[问题] 如何在子组件中修改collapsed的值

### ISSUE THREAD

**Issue by grubby14** [ant-design/ant-design-pro#9102]
### 🧐 问题描述
 如题

### 💻 示例代码
app.tsx
![image](https://user-images.githubusercontent.com/32976706/133277193-48cdd3d9-ff1f-4a32-a713-c70a28a290f9.png)

子组件代码
export default (): React.ReactNode => {
  // const intl = useIntl();
  return (
    <>
      <RouteContext.Consumer>
        {(value: RouteContextType) => {
          console.log(value)
          return (
            <PageContainer>
              <Button onClick={() => value.onCollapse?.(!value.collapsed)}>收起</Button>
            </PageContainer>
          )
        }}
      </RouteContext.Consumer>
    </>
  );
};

### 🚑 其他信息
我想要在子组件里面修改collapsed的值，以实现菜单收起展开的效果

**Comment by chenshuai2144** [comment]
collapsed  存在  initialValue里面，修改 initialValue 里好了
