### ISSUE TITLE
protable type='form'  我想实现多列展示👑 [需求]

### ISSUE THREAD

**Issue by 15723185734** [ant-design/ant-design-pro#9105]
### 🥰 需求描述
使用protable 自动生成的编辑表单时，只能一列显示，我想实现多列显示的话，目前只有改内部CSS或者写自定义写一个ProFrom，我现在想实现通过columns生成的编辑表单能自定义样式，自定义多列。

### 🧐 解决方案
在ProTable上加一个类似于ProDescriptions的column属性，让内部在的列通用显示为多少列，再在protable 的columns上新增一个属性column单独让该columns的子项显示占比

### 🚑 其他信息
 让第一张图片生成第二张的排列样式，第一张图是通过proTable type=from生成的 第二章是通过ProFrom生成的
![image](https://user-images.githubusercontent.com/61341868/133371413-c8af3a4b-e7e7-4924-9edd-13521beae42b.png)
![image](https://user-images.githubusercontent.com/61341868/133371475-b3f18aca-bee3-404e-b03d-ea2621f67e1c.png)

**Comment by chenshuai2144** [comment]
用 valueType= group 包一下。


```
{
            title: '分组',
            valueType: 'group',
            columns: [
              {
                title: '状态',
                dataIndex: 'groupState',
                valueType: 'select',
                width: 'xs',
                valueEnum,
              },
              {
                title: '标题',
                width: 'md',
                dataIndex: 'groupTitle',
                formItemProps: {
                  rules: [
                    {
                      required: true,
                      message: '此项为必填项',
                    },
                  ],
                },
              },
            ],
          },
```

**Comment by 15723185734** [comment]
> 用 valueType= group 包一下。
> 
> ```tsx
>  {
>   title: "分组",
>   valueType: "group",
>   columns: [
>     {
>       title: "状态",
>       dataIndex: "groupState",
>       valueType: "select",
>       width: "xs",
>       valueEnum,
>     },
>     {
>       title: "标题",
>       width: "md",
>       dataIndex: "groupTitle",
>       formItemProps: {
>         rules: [
>           {
>             required: true,
>             message: "此项为必填项",
>           },
>         ],
>       },
>     },
>   ],
> };
> ```

我需要更新一下依赖吗？valueType:'group'报错
