### ISSUE TITLE
Form表单如何用setFieldsValue设置upload组件的默认图片🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9106]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/20655248/133431045-96938dc3-3172-433c-b4c6-5ae1ff59a488.png)

![image](https://user-images.githubusercontent.com/20655248/133431097-1809794a-4dd6-4b4a-9c7c-afc1426f4c47.png)
![image](https://user-images.githubusercontent.com/20655248/133431216-892eecdd-f1ee-41f3-bd10-094be52c20f4.png)
如果不用upload组件的fileList属性设置upload组件的默认显示的图片， 要使用formRef?.current?.setFieldsValue设置upload组件默认显示的图片要如何做
发现如果没用getValueFromEvent属性自定义的值 upload组件默认的传递的值显示如图
![image](https://user-images.githubusercontent.com/20655248/133431877-cd4b6d26-90d5-48be-9eb8-17e753a899a0.png)
难道要用formRef?.current?.setFieldsValue构造这样一个对象吗？
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
对的 按照这个来吧

**Comment by lovehebe330** [comment]
> 对的 按照这个来吧

![image](https://user-images.githubusercontent.com/20655248/133434856-477b1f11-e570-4662-9fe4-392307c1b856.png)
![image](https://user-images.githubusercontent.com/20655248/133435061-897d2ec4-3617-4c09-9e37-3bed0fc4026e.png)
但按照这样写没显示出默认图片

**Comment by chenshuai2144** [comment]
你的设置错了，要用这个


```tsx
getValueFromEvent: (value: { fileList: UploadProps['fileList'] }) => value.fileList,
valuePropsName:"fileList"
```
