### ISSUE TITLE
在登录页Login.tsx打印initialState为undefined🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9109]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/20655248/133561096-8e5fc650-40cd-48a5-82b8-0d05bd239abf.png)
在Login.tsx登录页面组件中打印initialState的值发现第一次为undefined，
![image](https://user-images.githubusercontent.com/20655248/133561502-905a5e1b-be28-4615-bed6-9fbf624a509c.png)
第二次再刷新当前页面initialState就有数据
![image](https://user-images.githubusercontent.com/20655248/133561801-f5faa51e-248b-45a4-a900-a6f6dac0c098.png)
这样导致第一次进页面没获取到initialState的数据，没法进行登录，只有刷下页面获取到initialState数据才能登陆，这要咋解决呢
app.tsx的getInitialState方法代码如图
![image](https://user-images.githubusercontent.com/20655248/133562566-e65da68f-7f5c-45a5-a2be-de9339c9a061.png)
![image](https://user-images.githubusercontent.com/20655248/133562413-e7824d9f-ed34-4f7e-b7a0-60698485c334.png)
![image](https://user-images.githubusercontent.com/20655248/133562413-e7824d9f-ed34-4f7e-b7a0-60698485c334.png
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangqibin** [comment]
应该在app.tsx那边调用获取用户信息的接口，如果没有登录再跳转到登录，这样比较合适

**Comment by lovehebe330** [comment]
在app.tsx有调用户的接口， 问题是第一次打印在登录页第一次打印initialState为undefined，第二次刷了登录页面initialState才有值

**Comment by chenshuai2144** [comment]
是不是你接口有缓存？ 第二次请求会快很多

**Comment by vincevincetang** [comment]
> 在app.tsx有调用户的接口， 问题是第一次打印在登录页第一次打印initialState为undefined，第二次刷了登录页面initialState才有值

请问您解决了吗，我也遇到这样的问题

**Comment by Inuyashaaaaa** [comment]
我也有同样的问题

**Comment by Inuyashaaaaa** [comment]
这个问题似乎只有在配置了base和publicPath的时候会出现

**Comment by tomseanmy** [comment]
同
