### ISSUE TITLE
ajax请求后台的问题

### ISSUE THREAD

**Issue by anghuang** [ant-design/ant-design-pro#911]
![image](https://user-images.githubusercontent.com/17631600/35957404-5728f734-0cd6-11e8-95d8-ee2eb0e4a38a.png)
![image](https://user-images.githubusercontent.com/17631600/35957406-5d543bb4-0cd6-11e8-91af-33ebe73ebfbe.png)
还需要设置哪里么

**Comment by chenshuai2144** [comment]
你这是跨域。
百度一下你就知道
