### ISSUE TITLE
GGEditor的Folw组件如何设置只读？Flow组件的顶点和边如何设置只读不能编辑和拖动？

### ISSUE THREAD

**Issue by githubldld** [ant-design/ant-design-pro#9110]
GGEditor的Folw组件如何设置只读？Flow组件的顶点和边如何设置只读不能编辑和拖动？

**Comment by chenshuai2144** [comment]
这个库已经停止维护了，使用新的库吧，

https://antv-x6.gitee.io/zh 这个更适合你，还有专属答疑群
