### ISSUE TITLE
🧐[问题] 登录结束 设置 token 会出现跳转不过去

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#9112]
### 🧐 问题描述
登录成功 设置token 保存到localStorage 里
然后获取用户数据，然后 fetchUserInfo 没有携带token。返回401 导致跳转不过去

**Comment by fangqibin** [comment]
看看request是不是有啥问题。要不是token没有，要不然就是写错了。

**Comment by WuJiY** [comment]
在request里获取token的时候 我是调用 gettoken 就会出现 。需要直接获取 就可以

> 看看request是不是有啥问题。要不是token没有，要不然就是写错了。
