### ISSUE TITLE
🧐[问题]V5 pro 怎么设置导航折叠按钮

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/ant-design-pro#9113]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/52319042/133714666-c2dea9c4-e599-43ca-a5d6-9f5026069267.png)
我看官网上面这个按钮都是在上面的 怎么clone下来代码后就变成下面啦。请问怎么放在上面展示呢。api中也没找到

### 💻 示例代码

![image](https://user-images.githubusercontent.com/52319042/133714862-935261a2-e12d-4a18-bb18-9199b64a4462.png)
就像这样展示，怎么搞？ 大哥们
### 🚑 其他信息
版本：V5

**Comment by drizzlesconsin** [comment]
[自定义的 collapsed](https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed)

**Comment by TangDeYu** [comment]
> [自定义的 collapsed](https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-collapsed)

是这样我看了这个api后。在app.jsx里面添加了这个函数 header里面渲染出来这个图标之后。发现没有办法去控制它的开关，并且左侧下面的 图标还是存在的。 用的是V5的版本
![image](https://user-images.githubusercontent.com/52319042/133728758-8b3b5b90-0a1c-4b33-b9c9-5a997bc2beaf.png)
![image](https://user-images.githubusercontent.com/52319042/133728843-9b56db49-0a0a-454a-bc4c-b51afa5d030d.png)
