### ISSUE TITLE
🧐[问题]怎么在子组件中动态的设置menuRender属性

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/ant-design-pro#9114]
### 🧐 问题描述
在config中设置首页路由不展示左边的菜单栏...   但是怎么能动态就设置回来呢。也就是点击header里面的控制图标怎么能把menuRender为true 然后展示出来左边的菜单栏。。。 求解，大哥们。
![image](https://user-images.githubusercontent.com/52319042/133739091-39b290a3-83aa-467d-b44e-36f1639efc98.png)

![image](https://user-images.githubusercontent.com/52319042/133739065-6683133b-c121-47ac-8ec9-b03c98e8caed.png)

### 🚑 其他信息
版本：V5

**Comment by chenshuai2144** [comment]
你应该是像设置隐藏菜单吧。

` menuRender={(props, defaultDom) => (props.collapsed ? null : defaultDom)}`

可以用这个api

**Comment by TangDeYu** [comment]
> 你应该是像设置隐藏菜单吧。
> 
> ` menuRender={(props, defaultDom) => (props.collapsed ? null : defaultDom)}`
> 
> 可以用这个api

我目前是这个问题哈：
首页设置menuRender: false 属性就是把左边的菜单栏给隐藏掉，但是我控制左边菜单栏的那个按钮被我自定义在上面的header里面了。。现在就是怎么点击上面的那个按钮把左边的菜单栏给展示出来呢。。。我看dom元素是设置menuRender: false 属性之后就没有菜单栏的dom了。。请问这种应该怎么处理哈

**Comment by chenshuai2144** [comment]
props 里面有pathname 写个判断应该能实现。

**Comment by chenshuai2144** [comment]
我感觉你的这个交互有点反直觉，用户体验不会很好

**Comment by TangDeYu** [comment]
> 我感觉你的这个交互有点反直觉，用户体验不会很好

是的呢  我要去和产品商量商量这个问题。
