### ISSUE TITLE
🐛[BUG] 页面长时间放置不动，导致部分页面无法打开

### ISSUE THREAD

**Issue by wayneee188** [ant-design/ant-design-pro#9116]
### 🐛 bug 描述 
页面长时间放置不动，导致部分页面无法打开

1. 在某个页面长时间停留，大概5分钟，不进行任何操作。
2. 切换到其他页面，点击按钮，使用 history.push() 方法进行跳转，发现页面一直处于加载中，无法打开，且无请求调用。
3. 使用F5刷新页面，可以正常打开。

### 📷 复现步骤
请参考bug描述。

### 🏞 期望结果
1. 个人怀疑是history.push()方法用的不对。
2. 个人路由是否存在问题。路由配置放到浮现代码中了。

### 💻 复现代码
因为特殊原因，个人暂时只能提供部分路由配置，请大佬尽可能解惑。
`[
  {
  name: 'test',
  path: 'test',
  component: './test/list',
  },
  {
  name: 'test.config',
  path: 'test/config',
  component: './test/config',
  hideInMenu: true,
  },
  {
  name: 'test.preview',
  path: 'test/preview',
  component: './test/preview',
  hideInMenu: true,
  }
]`

### © 版本信息

- Ant Design Pro 版本: [4.11.2]
- umi 版本: [3.3.7]
- 浏览器环境: [Microsoft Edge 版本 93.0.961.47 (官方内部版本) (64 位)]
- 开发环境 [Windows 10]

### 🚑 其他信息

注：active接口是右上角的告警组件调用的，与此页面无关，此页面在获取两个文件后停止了网络请求。

![image](https://user-images.githubusercontent.com/38581778/133740900-087018fb-8504-4794-9be3-4e1509cfc65f.png)
![Animation](https://user-images.githubusercontent.com/38581778/133741126-a289aab3-d8db-40c2-9624-e50b69beff0f.gif)

**Comment by chenshuai2144** [comment]
去看看什么服务挂了吧，这种的一般都是内存泄漏导致webserver 挂了
