### ISSUE TITLE
🧐[问题]  enable mfsu 本地source-map失效

### ISSUE THREAD

**Issue by chenzio** [ant-design/ant-design-pro#9117]
### 🧐 问题描述  enable mfsu 本地source-map异常

报错：
![image](https://user-images.githubusercontent.com/24283515/133748813-07be8e90-0eca-40f5-bbc4-f4036848e67f.png)

### 💻 示例代码
开启 mfsu
```
export default defineConfig({
...
mfsu: {},
})
```
关闭mfsu后 source-map正常

### 🚑 其他信息

版本如下：
react： 17.0.2
umi： 3.5.18
umi-serve： 1.9.10

**Comment by chenshuai2144** [comment]
忽略掉吧，本来就没有map，只是浏览器要提示
