### ISSUE TITLE
🧐[问题]ProFormUploadButton上传文件，.net core怎么接收到文件

### ISSUE THREAD

**Issue by bieshaoxiong** [ant-design/ant-design-pro#9121]
### 🧐 问题描述
前端可以正常访问到后端接口，但是后端怎么接收不到文件

![1631948593(1)](https://user-images.githubusercontent.com/64937534/133879676-5cec60d1-1e8b-435d-9940-71141b792eff.jpg)

![image](https://user-images.githubusercontent.com/64937534/133879709-ac2c8ce6-3193-4021-b5c6-38015b1df439.png)

### 💻 示例代码

前端 ：
    <ProFormUploadButton
          name="upload"
          label={props.uploadLabel}
          max={1}
          fieldProps={{
            name: 'file',
          }}
          action="/api/ProjectManagement/products/ReceiveFile"
        />

后端
  [HttpPost]
        [Route("ReceiveFile")]
        public AntProResultDto<ProductInfoDto> ReceiveFile()
        {
            var files = Request.Form.Files;
             var headers = Request.Headers;            
            var CurrentContext = HttpContext;
        }

**Comment by chenshuai2144** [comment]
.net 我也不会用，等社区的小伙伴帮你把

**Comment by Liu-Ya** [comment]
![image](https://user-images.githubusercontent.com/23520283/134270059-9ea086b6-8659-4536-b851-879955d8adb4.png)

```tsx
<ProFormUploadButton name="file" fieldProps={{ name: 'file' }} action="/api/api/upload" />
```

**Comment by bieshaoxiong** [comment]
> ![图片](https://user-images.githubusercontent.com/23520283/134270059-9ea086b6-8659-4536-b851-879955d8adb4.png)
> 
> ```tsx
> < ProFormUploadButton  name = "file"  fieldProps = { {  name : 'file'  } }  action = "/api/api/upload"  / >
> ```

奇怪
![image](https://user-images.githubusercontent.com/64937534/134270522-1abdda34-f47a-463b-80aa-3423c5618f67.png)
![image](https://user-images.githubusercontent.com/64937534/134270565-73bfd04b-a86a-4551-b8af-132350cc744a.png)

**Comment by bieshaoxiong** [comment]
我的基类集成的是 AbpController
![image](https://user-images.githubusercontent.com/64937534/134271395-542faddf-2a22-4ab7-9dee-83fa2165da18.png)
跟这个有关系吗

**Comment by bieshaoxiong** [comment]
还没整明白是前端写错了 还是后端写错了

**Comment by Liu-Ya** [comment]
https://stackoverflow.com/questions/27533317/uploading-files-using-angualrjs-and-abp-boilerplate-with-webapi

应该是后端问题

**Comment by Liu-Ya** [comment]
看起来跟你用的framework有关系，你得慢慢找原因了
https://stackoverflow.com/questions/46294091/how-do-you-do-file-upload-method-in-appservices-for-aspnetboilerplate
