### ISSUE TITLE
🐛[BUG]使用js-cookie或者react-cookie报错

### ISSUE THREAD

**Issue by zhangxj** [ant-design/ant-design-pro#9122]
### 🐛 bug 描述

import Cookies from 'js-cookie'   //正常

Cookies.set("name", "test")   //报错
Uncaught (in promise) Error: Module "./js-cookie" does not exist in container.
while loading "./js-cookie" from webpack/container/reference/mf

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本  3.5.0

**Comment by chenshuai2144** [comment]
关掉mfsu就可以了，现在只支持es6的包，比较古老的包支持的不好。
