### ISSUE TITLE
mfsu报braft-utils报富文本编辑器的错🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9123]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/20655248/133963241-f996de2c-54ad-43b9-bf09-6fc6a85701c1.png)
![image](https://user-images.githubusercontent.com/20655248/133963258-bf88140f-9fe4-409b-86cb-64e0a4b87adf.png)
![image](https://user-images.githubusercontent.com/20655248/133963334-2878cb32-45e5-4527-8106-525ef6261688.png)
在ant design pro 中安装braft-editor后正常，然后引入braft-utils 这个在官方文档说不需要安装的，但引入完mfsu就报错了，删掉.umi文件再重启页木有效果的

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这里没办法帮你转到 umi，你去umi 提一下这种兼容性问题把。
