### ISSUE TITLE
How to trigger some event on collapse/expand sidebar toggle?

### ISSUE THREAD

**Issue by Ankzy** [ant-design/ant-design-pro#9124]
I want to trigger window resize event every time the basic sidebar of Ant Design Pro collapse/expand button was pushed
`window.dispatchEvent(new Event('resize'));`
Is it possible? I can't find where this toggle and its handler defined.

**Comment by chenshuai2144** [comment]
you need this demo

https://procomponents.ant.design/en-US/components/layout#customized-collapsed
