### ISSUE TITLE
🐛[BUG] LayoutSettings中title修改失效问题

### ISSUE THREAD

**Issue by fei199225** [ant-design/ant-design-pro#9126]
### 🐛 bug 描述

layout标题修改后，开发环境是好的，build后默认标题还是显示‘Ant design pro’，切换一下设置就好了。应该是打包默认状态有误。
### 📷 复现步骤

修改一下LayoutSettings里的title；
npm run build；
打包后的默认title还是显示‘Ant design pro’，但修改页面设置后会生效，刷新后又失效啦。
### 🏞 期望结果

查找了一下，发现与 #9095 问题高度一致。请问这个bug大概什么时候能修复呢？或者有没有可替代的解决方案？
### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本: [3.5.0]
- 浏览器环境: Chrome 92
- 开发环境: mac OS

**Comment by chenshuai2144** [comment]
dup of  #9095
