### ISSUE TITLE
🐛[BUG]弹出层分离怎么搞啊

### ISSUE THREAD

**Issue by github262302** [ant-design/ant-design-pro#9128]
### © 版本信息

- Ant Design Pro 版本: [5.0]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

### 🚑 其他信息

![截屏2021-09-22 下午11 33 49](https://user-images.githubusercontent.com/71603326/134375101-f67723ff-6cd3-49bb-ad51-2f90a65829cd.png)

**Comment by chenshuai2144** [comment]
去antd的configProvide一章去看看

**Comment by github262302** [comment]
# nice    🎉
