### ISSUE TITLE
👑 [需求]table 搜索框如何进行单独设置 搜索表单的 col 呢，统一设置好傻的呀！希望table columns search能自定义满足

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#9130]
### 🧐 问题描述
![image](https://user-images.githubusercontent.com/12706830/134609887-0900cd27-a967-4573-90df-d72d1049bbc0.png)
![image](https://user-images.githubusercontent.com/12706830/134610021-724e64d2-f13e-4b97-8c50-ed606a02bb85.png)

我想要一个form.item点一个col 24 或者12　6　8等等。而不是在search那里统一设置成这样
```
search={{
    span: {
      xs: 24,
      sm: 24,
      md: 12,
      lg: 12,
      xl: 8,
      xxl: 6
    }
  }}
```
这样风格出来都是一样的，对于特殊的搜索根本无法满足，如果想要做成那种条件复杂的，只能在froFrom search=false了。然后自己去写一堆的代码，这也背离了proForm简洁的初衷。
如果我要做成像原型一样的搜索。这个只能自定义了，如果能在coloumns search里把col单独定义我就可以做成这样了
![image](https://user-images.githubusercontent.com/12706830/134611261-0ef7af88-eb1d-4552-8ff3-a339669aceca.png)

### 💻 示例代码
我希望在columns的search里也可以设置　span 而不是只有　transform　
```
      search: {
        span: {xxxx}
      },
```

### 🚑 其他信息
这个截图是我通过改 dom节点生成的效果，而不是代码生成的，特别希望能自定义搞定它。
![image](https://user-images.githubusercontent.com/12706830/134611574-007c952d-df1d-4538-afc3-3a3118c84d94.png)

**Comment by drizzlesconsin** [comment]
可以参考 https://github.com/ant-design/ant-design-pro/issues/8876#issuecomment-894611862
