### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by UnqiueLi** [ant-design/ant-design-pro#9132]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

在ie11 打不开页面

![image](https://user-images.githubusercontent.com/23392078/134612463-184aa302-c1ff-4cfe-9178-4bfbce1e694a.png)

**Comment by drizzlesconsin** [comment]
[IE 报错和压缩问题解决思路](https://umijs.org/docs/faq#ie%E6%8A%A5%E9%94%99%E5%92%8C%E5%8E%8B%E7%BC%A9%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3%E6%80%9D%E8%B7%AF)

**Comment by pxim** [comment]
怎么解决的

**Comment by gezhicui** [comment]
mfsu 去掉
