### ISSUE TITLE
生产项目中使用mock数据🧐[问题]

### ISSUE THREAD

**Issue by fungmo** [ant-design/ant-design-pro#9133]
### 🧐 问题描述
我想在我的演示项目中使用mock数据，我尝试在config/config.ts中，将mock:false改为true, 然后打包并部署到服务器，然而mock数据没有生效。

我看文档中有关使用mock数据在部署中的介绍只有简短的说可使用umi-serve，但是不清楚怎么使用，我又尝试安装umi-serve,但是并没有效果。

### 💻 示例代码

> config/config.ts

```base
 openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: true,
    },
```

### 🚑 其他信息

"name": "ant-design-pro",
"version": "5.0.0",
"private": true,

**Comment by chenshuai2144** [comment]
学习一下 express 和部署的知识把。不然要学会很困难
