### ISSUE TITLE
🧐如何在CI/CD中的CD阶段替换config内的变量

### ISSUE THREAD

**Issue by scrapstation** [ant-design/ant-design-pro#9134]
### 🧐 问题描述

如何在CI/CD中的CD阶段替换config内的变量

### 🚑 其他信息

Build(CI)之后, 变量被打包到umi.7cfe5b23.js，替换难度较高（ps: 替换array会导致混淆之后的代码报错）

请教一个优雅方案

**Comment by chenshuai2144** [comment]
https://segmentfault.com/a/1190000011683741

用这个功能

**Comment by scrapstation** [comment]
CD过程我部署到了类似（oss）的静态空间里，没有Node运行环境。
那是不是意味着我只能在CI的时候指定NODE_ENV？
