### ISSUE TITLE
🐛[BUG]用IP地址访问网页时，navigator.mediaDevices 获取不到

### ISSUE THREAD

**Issue by shenyinabcd** [ant-design/ant-design-pro#9135]
## What happens?

用IP地址访问网页时，navigator.mediaDevices 获取不到。用 localhost 倒是可以

<img width="1044" alt="截屏2021-09-24 下午4 31 38" src="https://user-images.githubusercontent.com/4917536/134645953-e7f0bb90-8c83-4543-91e4-f2f3de8365bd.png">
<img width="1024" alt="截屏2021-09-24 下午4 31 44" src="https://user-images.githubusercontent.com/4917536/134645970-0af0ddce-ea7f-43a2-bf87-1321e12320d9.png">

## Mini Showcase Repository(REQUIRED)
使用 yarn create umi my-app 创建一个 ant design pro 项目

## How To Reproduce
创建一个 ant design pro 项目，运行起来。然后用chrome浏览器分别访问 IP 地址和 localhost 网址。在网页console 中查看 navigator.mediaDevices 是否存在

## Context

- **Umi Version**: 3.5.0
- **Node Version**:15.14.0
- **Platform**: mac os x 11.4

**Comment by Liu-Ya** [comment]
启用https
