### ISSUE TITLE
🐛[引入组件报错

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design-pro#9137]
### 🐛 bug 描述
引入anta组件报错

./antd/es/date-picker/style" does not exist in container
### 📷 复现步骤
![image](https://user-images.githubusercontent.com/51156342/134658388-51ac5ab3-872f-48d8-a198-3c92548a72f7.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by lunaSunday** [comment]
请问解决了吗，我这边引入 Switch组件的时候也报错了。。 一样的错误

**Comment by drizzlesconsin** [comment]
把 [mfsu](https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L69) 关掉，`npm run start`。再开启 mfsu.
