### ISSUE TITLE
🧐[问题]我需要使用旧的antd-pro 4.5

### ISSUE THREAD

**Issue by bjrxyz** [ant-design/ant-design-pro#9138]
### 🧐 问题描述

我需要使用旧的4.5版本，但是使用create umi创建默认就是V5版本。我该怎样使用旧版本

### 🚑 其他信息

因为项目的进度问题，我暂时没有时间来学习V5版本

**Comment by chenshuai2144** [comment]
为了项目进度才应该用新的 固步自封用不维护的东西更影响进度

最后还坑了接手项目的人

**Comment by Martinzz** [comment]
我晕，原来创建不了 4.5了啊，我还是出bug了，疯狂删了创删了创，全是5
