### ISSUE TITLE
[BUG] access 配置路由权限没有效果 还是可以访问到

### ISSUE THREAD

**Issue by xdyz** [ant-design/ant-design-pro#9139]
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/23496206/134797833-90206aca-7d1c-44ea-b526-c4d0140153bd.png)
![image](https://user-images.githubusercontent.com/23496206/134797846-7f838a90-4f3d-4c33-8e7b-d87bddb45375.png)
![image](https://user-images.githubusercontent.com/23496206/134797855-2bbdec1e-bb31-4ed1-936d-956266574349.png)

**Comment by zhj778930960** [comment]
![image](https://user-images.githubusercontent.com/23496206/134798530-67793bc9-f32d-4dd3-bc5b-19c1f85b782a.png)

**Comment by johnnylc** [comment]
同样遇到这个问题

**Comment by chenshuai2144** [comment]
是不是自定义菜单了？

**Comment by watsonhaw5566** [comment]
@xdyz @Koomita 搞定了没，我也遇到这个问题了，不知道是不是某个版本的问题
