### ISSUE TITLE
effects调用reducers更改状态，页面回调函数无法获取到

### ISSUE THREAD

**Issue by Hsinky** [ant-design/ant-design-pro#914]
业务逻辑：
删除数据，在页面上显示删除结果
问题：前台回调函数callback获取到的project是上一次的对象
routes:
dispatch({
              type:'project/remove',
              payload:{
                Id:selectedRows.map(row => row.Id),
              },
              callback:()=>{
                console.info(project)//project是connect model对象，想找到自定义错误信息并显示               
                _this.setState({
                  selectedRows:[]
                })
              }
            });
Model:
export default {
  namespace: 'project',

  state: {
    data: {
      list: [],
      pagination: {},
    },
    actionState: undefined,
    actionStateText:''
  },

  effects: {
    *remove({payload,callback},{call,put,take}){
      const response = yield call(remove, payload);
     //请求服务端后将返回来的值放到reducers处理，更改状态，此处，服务端返回了正确的数据
      yield put({
        type: 'changeActionStatus',
        payload: response,
      });
      if (callback) callback();
    },
  },

  reducers: {
    changeActionStatus(state,{payload}){
      state.data.list=state.data.list.filter(item => item.Id !== 22);
      return {
        ...state,
        actionState: payload.State,
        actionStateText:payload.StausText,
      };
    }
  },

**Comment by chenshuai2144** [comment]
去看看 markdown？ 你这样不能看呀

**Comment by afc163** [comment]
http://segmentfault.com/markdown

**Comment by Hsinky** [comment]
![image](https://user-images.githubusercontent.com/10111222/36012940-66f77fac-0d9c-11e8-8f8e-73962c45587f.png)

想根据服务端返回的数据，更改前台页面的状态，上面这种设值才行，而下面这种方式，始终是上一次服务端返回的数据

**Comment by afc163** [comment]
了解一下 redux 的 Immutable Update Patterns：https://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html
