### ISSUE TITLE
项目部署后，浏览器刷新后，url pathname尾部会多出一个 /

### ISSUE THREAD

**Issue by indown** [ant-design/ant-design-pro#9140]
### 🧐 问题描述

项目部署后，浏览器刷新后，url pathname尾部会多出一个 /
如何阻止这一行为

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32740525/134802520-f1374930-05e9-464b-8e99-bed42bc07d1b.png)

**Comment by indown** [comment]
![image](https://user-images.githubusercontent.com/32740525/134802584-0591ac4c-ab98-4bdd-8f46-4fea6c8e6a18.png)

**Comment by fangqibin** [comment]
路由怎么配置的

**Comment by indown** [comment]
@fangqibin 

> 路由怎么配置的

就是脚手架创建出来没有改变的，官方预览页同样有这个问题https://preview.pro.ant.design/

**Comment by Wster11** [comment]
我的问题是不带/， 页面正常显示，但是控制台有1个404的error

**Comment by fangqibin** [comment]
具体不知道了，我都是用官方的创建出来的，挺正常的

**Comment by Wster11** [comment]
> 具体不知道了，我都是用官方的创建出来的，挺正常的

我这里就是有个error 提示， 不影响正常使用

**Comment by fangqibin** [comment]
> > 具体不知道了，我都是用官方的创建出来的，挺正常的
> 
> 我这里就是有个error 提示， 不影响正常使用

你那个应该是接口没有吧。

**Comment by Wster11** [comment]
> > > 具体不知道了，我都是用官方的创建出来的，挺正常的
> > 
> > 
> > 我这里就是有个error 提示， 不影响正常使用
> 
> 你那个应该是接口没有吧。

有接口 线上的项目， 接手别人的发现有这个error

**Comment by fangqibin** [comment]
> > > > 具体不知道了，我都是用官方的创建出来的，挺正常的
> > > 
> > > 
> > > 我这里就是有个error 提示， 不影响正常使用
> > 
> > 
> > 你那个应该是接口没有吧。
> 
> 有接口 线上的项目， 接手别人的发现有这个error

都报404了，还有这个接口？

**Comment by Wster11** [comment]
> > > > > 具体不知道了，我都是用官方的创建出来的，挺正常的
> > > > 
> > > > 
> > > > 我这里就是有个error 提示， 不影响正常使用
> > > 
> > > 
> > > 你那个应该是接口没有吧。
> > 
> > 
> > 有接口 线上的项目， 接手别人的发现有这个error
> 
> 都报404了，还有这个接口？

抱歉，我可能没说清楚，我是这个页面的路由 404 , 但是页面还能正常访问 ，刷新浏览器访问 /user 会有该路由的404 error提示， 访问/user/则没有这个error.

**Comment by indown** [comment]
> ### 🧐 问题描述
> 项目部署后，浏览器刷新后，url pathname尾部会多出一个 /
> 如何阻止这一行为
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/32740525/134802520-f1374930-05e9-464b-8e99-bed42bc07d1b.png)

问题解决了，
解决方法：
开启
history: {
    type: 'browser',
},
关闭exportStatic

**Comment by Wster11** [comment]
> > ### 🧐 问题描述
> > 项目部署后，浏览器刷新后，url pathname尾部会多出一个 /
> > 如何阻止这一行为
> > ### 🚑 其他信息
> > ![image](https://user-images.githubusercontent.com/32740525/134802520-f1374930-05e9-464b-8e99-bed42bc07d1b.png)
> 
> 问题解决了，
> 解决方法：
> 开启
> history: {
> type: 'browser',
> },
> 关闭exportStatic

刷新页面会有404 error吗

**Comment by RichardZhang12** [comment]
> > ### 🧐 问题描述
> > 项目部署后，浏览器刷新后，url pathname尾部会多出一个 /
> > 如何阻止这一行为
> > ### 🚑 其他信息
> > ![image](https://user-images.githubusercontent.com/32740525/134802520-f1374930-05e9-464b-8e99-bed42bc07d1b.png)
> 
> 问题解决了， 解决方法： 开启 history: { type: 'browser', }, 关闭exportStatic

这样没解决问题啊，配置项中，history默认就是type:browser, exportStatic设置为false或{ }，打包结果没有变化。
![image](https://user-images.githubusercontent.com/40022151/150262311-e2e586af-c967-468a-b05f-4fc5fbf76cb7.png)

我分析这个问题出现的原因是项目默认打包出来的文件不是平常我们使用webpack那样，打包出来只有一个index.html的单页面应用，他是根据配置的routes.ts里的路径，生成的不同的文件夹，每个下面都有个index.html，大家可以看一下我上面的贴图，如果不显示，自己打包看一下
我的服务端用的express，按照文档上提供的配置静态文件夹的方案，实际平常对vue项目也是这样配置的.

这时候我浏览器访问/user/login这个路由时，express静态文件查找到静态文件夹public下 user/login目录，这里服务端我理解像webpack引入文件没加后缀一样，会有一个查找顺序（js,json,...）。这时候找到user/login，发现有这个目录，返回了目录下的index.html,浏览器访问路径重定向到/user/login/下，我觉得是这里导致的，但是不太清楚原因和现在我在试着更改exportStatic配置项，能不能解决

**Comment by 775083111** [comment]
我是这么干的:    
 import {  history } from 'umi';

      useEffect(() => {
              let routeKey = location.pathname;
              if (location.pathname.endsWith('/')) {
                  routeKey = location.pathname.substring(0, location.pathname.length - 1)
                  history.push(routeKey)
                  return;
              }
         }, [location.pathname]);
