### ISSUE TITLE
AutoComplete组件配合Input.Search使用无法设置文本框最大长度🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9141]
### 🐛 bug 描述
搜索查找AutoComplete组件配合Input.Search使用， 设置文本框的最大长度，要给Input.Search设置maxLength 设了之后没有效果 这个要咋解决
![image](https://user-images.githubusercontent.com/20655248/134873249-c0c67e71-a73b-41ad-a31b-4241f8d5665a.png)

![image](https://user-images.githubusercontent.com/20655248/134873424-991991db-3347-49f8-9eaa-28616bab7f8c.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
用 rule 呗，写了rule 来控制长度不要太长
