### ISSUE TITLE
React 类组件中使用国际化FormattedMessage组件报错🐛[BUG]

### ISSUE THREAD

**Issue by lujun5068** [ant-design/ant-design-pro#9142]
### 🐛 bug 描述
在React类组件中，结合antd的message组件来展示国际化文案，由于formatMessage被废弃，所以使用FormattedMessage组件的方式来展示，但控制台报错：[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry. Using default message as fallback.

### 🏞 期望结果
不报错，正常使用

### 💻 复现代码
```
import { FormattedMessage } from 'umi';
import { Button, message } from 'antd';

const ShowMessage = () => (
<Button onClick={() => message.error(<FormattedMessage id="common.invalid" defaultMessage="废弃" />}
>click</Button>
 
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/38418599/134881969-3914b0d1-0cd0-4897-958d-998abc02c740.png)

**Comment by zhuiluo0987** [comment]
> 必须要要用provide 包裹的，这个看起来是国际化的provide 没加进去
> 
> 检查一下是不是把组件放到路由里面了

在ant-design-pro 如何添加<IntlProvider></IntlProvider>。 没有入口文件呀？求大佬指教

**Comment by zhuiluo0987** [comment]
> 必须要要用provide 包裹的，这个看起来是国际化的provide 没加进去
> 
> 检查一下是不是把组件放到路由里面了

在ant-design-pro4 河图添加IntlProvider，没有入口App 组件呀？求大佬赐教
