### ISSUE TITLE
程序打包页面title问题？

### ISSUE THREAD

**Issue by Mrheqiang** [ant-design/ant-design-pro#9147]
使用yarn create umi myapp拉下来的包更改title后，打包程序自动变成‘Ant Design Pro’

**Comment by drizzlesconsin** [comment]
全局搜索替换.

**Comment by Mrheqiang** [comment]
在开发环境里面已经完全没有‘Ant Design Pro’字样了   在打包后的程序里面就出现这个，自己设置的title已经不存在了

**Comment by drizzlesconsin** [comment]
全局搜索打包后的产物，也没有会不会是缓存？(隐身模式打开试试？)
