### ISSUE TITLE
🧐ant-design-pro V4 默认登录页面中 发生网络请求回刷新登录页

### ISSUE THREAD

**Issue by denganjia** [ant-design/ant-design-pro#9148]
### 🧐 问题描述

ant-design-pro V4 默认登录页面中 发生网络请求回刷新登录页。
我需要调用API让后端发送验证码，但是在登录页中执行API回刷新页面

### 💻 示例代码
<Button onClick={async () => {
				dispatch({
					type: 'login/getCode'
				})
			}}>测试</Button>
// 或者
<Button onClick={()=>{getCode()}}></Button>

**Comment by denganjia** [comment]
![b0esj-e2je1](https://user-images.githubusercontent.com/46669447/135193725-4d14a332-ffa6-44c5-ba6e-0d3b1998a4b2.gif)

**Comment by denganjia** [comment]
help me

**Comment by SilentFlute** [comment]
@denganjia 你好, 我也是有这个需求, 需要请求后端获取验证码, 但发送请求就刷新页面, 请问你最后是怎么解决的呢?

**Comment by SilentFlute** [comment]
图片验证码, 因为这个功能有些着急, 所以最后我让后端小伙伴改了一下接口, 不再返回`json`, 而是直接返回图片, 这样就可以用`img`的`src`发送请求了, 然后就完成了这个功能

**Comment by chenshuai2144** [comment]
是不是触发了表单提交

**Comment by denganjia** [comment]
@SilentFlute 你好 ，这个问题是出于框架中的配置文件的问题，有一个叫做app.ts/app.js的文件拦截了你的请求，你需要在文件中的whiteList中添加你所访问的路径

**Comment by SilentFlute** [comment]
@denganjia 没有app.js/ts文件啊, 这个项目是有人离职, 我接手的, 没看到这个文件, 被删除了? 能看下你的代码吗?

**Comment by denganjia** [comment]
你好 如果你的项目能跑起来 麻烦把你的项目目录截图给我看  具体的文件我也不知道 我现在已经不再负责这块了

小镇靓仔 ***@***.***> 于2021年12月9日周四 17:27写道：

**Comment by SilentFlute** [comment]
@denganjia
![image](https://user-images.githubusercontent.com/28900312/145739378-a50947cc-805c-4088-8b2d-fa7e2303ef4c.png)
