### ISSUE TITLE
关于dva中dva/dynamic做代码分割时候，路由第一次跳转页面明显刷新的问题

### ISSUE THREAD

**Issue by wdao7** [ant-design/ant-design-pro#915]
不使用dva/dynamic做代码分割，路由跳转页面没有明显刷新效果，可是如下配置后，就有问题
![qq 20180208183229](https://user-images.githubusercontent.com/34474826/35968958-493a35dc-0d00-11e8-8278-b083fad86ed4.png)；
初始化的时候页面是这样的
![qq 20180208183713](https://user-images.githubusercontent.com/34474826/35968985-5a813dea-0d00-11e8-93c6-047cfecb9809.png)
当我点击users后，路由第一次跳转users的时候界面有明显刷新效果，同时会去加载一个js文件
![qq 20180208183735](https://user-images.githubusercontent.com/34474826/35969081-b14d3d72-0d00-11e8-9e14-35f1099d474b.png)
貌似代码确实分割了，可明显的页面刷新效果还是是单页吗，不能忍呀，求解答，自己弄一天了

**Comment by chenshuai2144** [comment]
这样的表现是对的。
cc https://doc.webpack-china.org/guides/code-splitting/

**Comment by wdao7** [comment]
可我运行ant-design-pro这个项目在用户中心我在左边栏点击路由菜单，第一次控制台也会去请求不同的js，可是页面用户中心页面没有明显的刷新效果呀，若果代码分割会有明显刷新效果，那还做啥单页？

**Comment by chenshuai2144** [comment]
去看看文档吧

**Comment by wdao7** [comment]
您好，刚看过文档了，但是正对我目前的问题并没有啥帮助，我只是想用dva做代码分割，同时页面路由跳转无明显刷新效果即可，就想ant-design-pro当中使用dva用户中心左边栏点击右边栏页面变化也无明显刷新那样而已，如果您发现我的问题有什么解决方案，还请告知下，不胜感激 @chenshuai2144

**Comment by chenshuai2144** [comment]
拆分的更细一点就好了  你要求这么高的话 没必要用代码分割。
代码分割牺牲了加载速度来换取更快的首屏加载速度
