### ISSUE TITLE
👑 [需求]ProTable删除一行或是更新一行的数据的时候，在不重载表格的情况下刷新到列表中

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design-pro#9151]
### 🥰 需求描述

ProTable删除一行或是更新一行的数据的时候，在不重载表格的情况下刷新到列表中，现在更新或是删除必须要重新请求下数据接口，有没有什么办法可以实现。

**Comment by drizzlesconsin** [comment]
[mutate](https://hooks.umijs.org/hooks/async#mutate)

**Comment by chenshuai2144** [comment]
用 dataSouce 和  onDataSourceChange 来受控的设置数据。
不过推荐还是重新刷新一下，这样能保证数据的一致性

**Comment by ideaviewes** [comment]
@chenshuai2144 ,谢谢
