### ISSUE TITLE
👑 [需求] Use Playwright instead of Puppeteer for e2e tests

### ISSUE THREAD

**Issue by coding-everywhere** [ant-design/ant-design-pro#9152]
### 🥰 需求描述

Since [Playwright](https://github.com/microsoft/playwright) was released 2 years ago they built a solid end-to-end testing system with integrated [test-runner](https://playwright.dev/docs/intro), [inspector](https://playwright.dev/docs/inspector) to analyse failed tests and other [debugging utilities](https://playwright.dev/docs/debug). This should make it easier for users to write more reliable cross-platform end-to-end tests, debug them, and scale them across different projects, teams, or different browsers.

### 🧐 解决方案

Replace Puppeteer by Playwright and its [test-runner](https://playwright.dev/docs/intro#first-test).

### 🚑 其他信息

- https://playwright.dev/docs/intro
- https://github.com/microsoft/playwright
- https://playwright.dev/docs/test-assertions

**Comment by benwiley4000** [comment]
I have experienced some issues with `locator.press()` / `page.press()` in playwright with antd number inputs after entering invalid values. the range correction doesn't work and the field goes blank instead. Have you experienced this issue?

**Comment by chenshuai2144** [comment]
great
