### ISSUE TITLE
🧐[问题] 怎么让document.ejs页面不跳转/或者控制消失的时长

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9154]
### 🧐 问题描述

项目需要定制打开的效果，也就是document.ejs页面，但是目前遇到的问题是没办法调试，一打开就消失，请问怎么延长消失的时长或者不消失。

**Comment by chenshuai2144** [comment]
document.ejs ->document.html
直接用浏览器打开 document.html

**Comment by jacktang** [comment]
@chenshuai2144 可以控制时长吗？需要有个开场动画播放。

**Comment by chenshuai2144** [comment]
开场动画写到js里面把，html 里面就不要搞太多花活了

**Comment by jacktang** [comment]
有个loading, 再有个动画很难看啊，求告知document.ejs载入的代码片段？我找了很长时间没找到。

**Comment by chenshuai2144** [comment]
自动注入的，你控制不了的

**Comment by chenshuai2144** [comment]
浏览器加载js的速度你没法控制的。

或者你做个遮罩不要放到 root里面，root里面的会被react清空掉
