### ISSUE TITLE
How to start with PM2 ？

### ISSUE THREAD

**Issue by mpv945** [ant-design/ant-design-pro#916]
Now that PM2 has become the mainstream, how does this project be managed by the same PM2？

**Comment by chenshuai2144** [comment]
Why do I need PM2?

**Comment by chengs** [comment]
@mpv945 I guess you are confusing a bit. This project produces fronted resources, although it relies on node. Nevertheless, Pm2 manages the backend. So how to use pm2 is totally NOT a problem of this project.

**Comment by jasp402** [comment]
I have a project in Ant Design PRO. I have created my BackEnd in NodeJS. I want to use "pm2" to keep track of all applications. I understand that Ant design PRO. It is initialized with a "UMI" I think it is not possible. but it would be interesting if you could.
In this case it would be a matter of "pm2" to be able to start projects in "UMI"
