### ISSUE TITLE
🐛[BUG] 新创建项目运行不起来

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design-pro#9160]
### 🐛 bug 描述

用  yarn create umi  创建  pro 的项目，运行报错。

### 📷 复现步骤

yarn create umi  pro

? Select the boilerplate type (Use arrow keys)
ant-design-pro

? 🤓 Which language do you want to use? (Use arrow keys)
TypeScript

? 🚀 Do you need all the blocks or a simple scaffold? (Use arrow keys)

simple

cd pro
yarn 
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ umi g tmp
✨  Done in 75.16s.

 yarn run start

yarn run v1.22.4
$ cross-env UMI_ENV=dev umi dev
Bundle with webpack 5...
⏱️  MFSU Enabled
Starting the development server...

✔ Webpack
  Compiled successfully in 7.86s

✔ MFSU
  Compiled successfully in 37.80s

✔ Webpack

 DONE  Compiled successfully in 7895ms                                                                                                                                                           下午2:42:19

  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.31.198:8000
 DONE  Compiled successfully in 37802ms                                                                                                                                                          下午2:42:58

✔ MFSU

✔ Webpack

打开浏览器输入 http://localhost:8000

![image](https://user-images.githubusercontent.com/24469601/136153197-4afa2613-9351-49ea-8b32-c6701150ae62.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
依赖有问题，看起来没装全
```bash
git clean -dfx
yarn
```

**Comment by buxinren** [comment]
我好像遇到过，你找到相应的文件里，代码有可能没有导入组件，你import一下应该可以
