### ISSUE TITLE
【新版本上线出问题，急急急】报错：Something went wrong。

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#9165]
重新install一下proTable就出问题了，之前版本一直是正常的。@ant-design/pro-table升到最新的2.54.3也解决不了问题

一、错误
![image](https://user-images.githubusercontent.com/20454290/136550302-a31f007f-8aef-4005-a6e7-a459d4745a0d.png)

二、报错代码：这行代码在以前的版本是没任何问题

!!text为false（布尔值）

![image](https://user-images.githubusercontent.com/20454290/136550360-16256083-34e8-412b-b598-54ce8e51d84f.png)

三、版本
"@ant-design/pro-table": "^2.1.11",
"antd": "^4.16.13",

node：10.13.0

四、其他版本
"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^5.0.8",
    "@ant-design/pro-table": "^2.1.11",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.0.0",
    "@antv/l7-maps": "^2.0.0",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "antd": "^4.16.13",
    "bizcharts": "^3.5.3-beta.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.2.6",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.24.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "prop-types": "^15.5.10",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "react-router": "^4.3.1",
    "umi": "^3.0.14",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.18",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^25.1.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.8.4",
    "@types/react-helmet": "^5.0.13",
    "@umijs/fabric": "^2.0.5",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/preset-ant-design-pro": "^1.0.1",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/preset-ui": "^2.0.9",
    "chalk": "^3.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "enzyme": "^3.11.0",
    "eslint": "^6.8.0",
    "express": "^4.17.1",
    "gh-pages": "^2.0.1",
    "husky": "^4.0.7",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "stylelint": "^13.0.0"
  },

五、麻烦帮忙看下，急着发布新版本。

**Comment by xrkffgg** [comment]
这个 text 是啥？

**Comment by 419280377** [comment]
问题已解决，ant design pro老版本的解决办法是给ProTable加上columnEmptyText={false}，不加的话默认会给null的数据转为“-”

**Comment by 419280377** [comment]
问题已解决，ant design pro老版本的解决办法是给ProTable加上columnEmptyText={false}，不加的话默认会给null的数据转为“-”
