### ISSUE TITLE
🧐按照文档创建一个新的项目，node_module 里会重复复制项目

### ISSUE THREAD

**Issue by jimStyle88** [ant-design/ant-design-pro#9168]
### 🧐 问题描述
按照文档创建一个新的项目，node_module 里会重复复制项目，不明白为何会出现这种情况，以及npm i  的时候，会出现丢包的可能性

### 💻 示例代码
无

如图所示：
![image](https://user-images.githubusercontent.com/20588608/136656751-68527a8b-8b70-42b5-a337-7e44fe2b73a6.png)

**Comment by chenshuai2144** [comment]
不要用这个依赖库了，已经废弃了。
然后你本地link了一下，就形成循环依赖了

**Comment by jimStyle88** [comment]
> 不要用这个依赖库了，已经废弃了。 然后你本地link了一下，就形成循环依赖了

我是在npm start 的时候生成的，没有执行link 的操作，生成的这个文件夹是项目本身。我不明白的是怎么产生的？大佬帮忙解答一下

**Comment by chenshuai2144** [comment]
执行一下` npm unlink ant-design-pro`和 `yarn unlink ant-design-pro`

**Comment by LuYangYang** [comment]
解决了吗？同样问题 node_modules里无限循环 @jimStyle88

**Comment by PeachScript** [comment]
node_modules 里只是软连接，不影响项目运行，可以忽略

**Comment by jimStyle88** [comment]
> 解决了吗？同样问题 node_modules里无限循环 @jimStyle88

没有

**Comment by jimStyle88** [comment]
> node_modules 里只是软连接，不影响项目运行，可以忽略
想知道产生这种情况的原因，大佬解答一下疑问？

**Comment by PeachScript** [comment]
是 dumi 的一个 workaround，为了实现写 demo 时可以以 NPM 包的形式 import 当前组件库项目的组件，但对于 pro 项目来说确实不需要，后续版本会对集成模式禁用该特性

**Comment by jimStyle88** [comment]
> 是 dumi 的一个 workaround，为了实现写 demo 时可以以 NPM 包的形式 import 当前组件库项目的组件，但对于 pro 项目来说确实不需要，后续版本会对集成模式禁用该特性

谢谢大佬解答

**Comment by PeachScript** [comment]
> 是 dumi 的一个 workaround，为了实现写 demo 时可以以 NPM 包的形式 import 当前组件库项目的组件，但对于 pro 项目来说确实不需要，后续版本会对集成模式禁用该特性

[dumi@1.1.32](https://github.com/umijs/dumi/releases/tag/dumi%401.1.32) 已对集成模式移除软连接逻辑
