### ISSUE TITLE
手机端表单录入界面自动放大的问题

### ISSUE THREAD

**Issue by huangxingpark** [ant-design/ant-design-pro#918]
在手机端点击“基础表单”等表单页面时，
第一步：表单显示很好，没有问题。
第二步：点击输入框后，弹出输入键盘，界面会放大一些。
第三步：点击任意地方，退出输入键盘，表单界面保持放大状态，没有恢复过来，必须手工缩小，很麻烦。
建议：1、进入输入状态，界面不放大。2、或者退出输入状态，界面自动缩小到正常状态。

第一步：
![1](https://user-images.githubusercontent.com/8498206/36008701-999cda7e-0d83-11e8-868a-2f3acae43ce0.jpg)

第二步：
![2](https://user-images.githubusercontent.com/8498206/36008711-9e9cebe0-0d83-11e8-9df9-2f93e5a9183e.jpg)

第三步：
![4](https://user-images.githubusercontent.com/8498206/36008798-f4a55c84-0d83-11e8-8bce-4ae5db607214.jpg)

**Comment by ddcat1115** [comment]
这是浏览器默认行为，如果不需要，可以试下在头部加入

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
```

或者设置字体大小 https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
