### ISSUE TITLE
🧐[问题]还是三级路由问题（列表->详情，详情隐藏，但是选中态在列表）

### ISSUE THREAD

**Issue by jiachaosun** [ant-design/ant-design-pro#9182]
```
{
  path: '/coupons',
  name: 'coupons',    // 一级，只展开
  routes: [
    {
      path: '/coupons/coupon-list',
      name: 'coupon-list',
      component: './coupons/coupon-list',  // 二级，可点击
      hideChildrenInMenu: true,                   // 这里把子routes在菜单隐藏
      routes: [
        {
          path: 'detail',
          name: 'coupon-detail',    
 
          // 三级，就是个详情页，不能在菜单出现，但是选中态一定要是从上一级进去的，很正常的需求吧？？？
          // 但是这里，无论如何都无法访问到这个页面,path等价于/coupons/coupon-list/detail 对吧？
          component: './coupons/coupon-detail',    
        },
      ],
    },
  ],
},
```

pro版本5.0
头都大了，一共就3个hideXXX参数，看了下也就hideChildrenInMenu和hideInMenu有关系，怎么试都不对

**Comment by TangDeYu** [comment]
> > 详情页 path: '/coupons/coupon-list/detail' 这样不行吗？
> 
> 不行呀，行的话我就不发这issue了...

![image](https://user-images.githubusercontent.com/52319042/137051178-a4a92f9c-b938-4f17-b235-09280a88a444.png)
我的意思是这样。。。

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/137609301-ce2c038c-d1b4-42ad-8b90-e9de0780b817.png)

为啥要配置components ，配置了就会走 components ，当成了一个layout。你最好设置成平级的

**Comment by a354123417** [comment]
@chenshuai2144 同样的需求，或许您说的这种方案可行，但是层级关系没楼主说的那样直观

**Comment by chenshuai2144** [comment]
那就不要设置 components 就可以了。不设置会用下面的

**Comment by a354123417** [comment]
> 那就不要设置 components 就可以了。不设置会用下面的

您没明白我的意思，一开始我要显示二级菜单，比如商品列表，这时候必须要有 componets 吧，然后我点商品详情，我把他归类到商品列表的子分类，即三级菜单，但是又不想让它在菜单栏显示，这时二级菜单跟三级菜单都有 components ，貌似目前点详情会显示二级菜单的 components ，显示不了三级菜单的，不知道有没有其他合理的解决方案。

**Comment by uliian** [comment]
我这有个很明确要三级路由的需求，场景和楼主的问题类似，但是我的第三级页面需要面包屑导航，能回到第二级页面

**Comment by chengshihard** [comment]
楼主最后解决了吗  一模一样的需求 头大

**Comment by xiaofeisss** [comment]
> 我这有个很明确要三级路由的需求，场景和楼主的问题类似，但是我的第三级页面需要面包屑导航，能回到第二级页面

加一   解决了吗 兄弟
