### ISSUE TITLE
使用iframe嵌入报错

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#9185]
动态路由，组件中使用iframe，访问的时候报错
![image](https://user-images.githubusercontent.com/32414361/137248618-fdd7c03b-322a-4142-a651-98e0559be862.png)
![image](https://user-images.githubusercontent.com/32414361/137248632-bb51c47c-2736-4ee4-a9a5-120db44b21a3.png)

**Comment by yingying0824** [comment]
请问你解决了吗？

**Comment by yongjiangliu** [comment]
这个涉及到跨域，需要服务端Access-Control-Allow-Origin 相关字段的设置，不然会报错
baidu,com禁止iframe嵌入
bing.com 可以嵌入
这是我的理解
