### ISSUE TITLE
新增页面为什么不能访问🧐[问题]

### ISSUE THREAD

**Issue by linghuchong-123** [ant-design/ant-design-pro#9188]
### 🧐 问题描述

pre文件夹下的代码是复制的list文件夹下的，在config.js中也已经配置了路由还是不能访问

### 🚑 其他
![image](https://user-images.githubusercontent.com/67812417/137333442-2f15547c-fbca-4be7-8e14-8d1f6527cf01.png)
![image](https://user-images.githubusercontent.com/67812417/137333474-59d1dd92-9a86-4dd6-8b5d-1de41338791d.png)

**Comment by 569202812** [comment]
都没有articles这个页面组件

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/137608727-c885f202-d443-45c2-8e5c-ae3890e44f66.png)

估计是这里d的原因，因为components 配置了，导致路由去了 /search 里面了
