### ISSUE TITLE
SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS

### ISSUE THREAD

**Issue by nxg916** [ant-design/ant-design-pro#9189]
## What happens?
![image](https://user-images.githubusercontent.com/7166587/136914375-0e54203d-dc24-4b05-b7fe-997bc905a62d.png)

访问的url 地址是 https 开头的， 实际访问是通过nginx代理转发到127.0.0.1。 如果使用http://localhost访问没有问题， 如果用https访问就会报上面的错误，导致页面白屏。
有什么方法屏蔽这个问题或者解决这个问题？？？

## Context
  "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@umijs/route-utils": "^1.0.36",
    "antd": "^4.14.0",
    "classnames": "^2.2.6",
    "fflate": "^0.7.1",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "three": "^0.132.2",
    "umi": "3.5.0",
    "umi-serve": "^1.9.10"

- **Node Version**:14.15.1
- **Platform**:mac-chorme

**Comment by chenshuai2144** [comment]
umi 升级一下，旧版本因为https证书的问题会导致整个服务挂掉
