### ISSUE TITLE
Dynamic theme switching documentation unavailable

### ISSUE THREAD

**Issue by rishii1909** [ant-design/ant-design-pro#9194]
The given documentation path doesn't have any page, there's no available documentation on how to implement the very cool theme/layout switcher right-sidebar from Preview.
![image](https://user-images.githubusercontent.com/61195716/137475769-123b9f84-16bb-4aa8-a36d-29a16c180a8b.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


I apologize for the inconvenience and thank you for bringing this issue to our attention. 

To implement a dynamic theme/layout switcher like the one in the Preview, you can start by creating multiple stylesheets or CSS classes for each theme/layout you want to support.
For example, you can create a stylesheet for a light theme and a stylesheet for a dark theme. 

Then you can use JavaScript to switch between these stylesheets or classes based on the user's selection. 
You can do this by:

1. Creating a button or menu for the user to select their preferred theme/layout. 

2. Adding an event listener to the button/menu. 

3. Using JavaScript to change the `href` attribute of the stylesheet link or the `class` attribute of the HTML element that defines the layout. 

Here's an example of how you can switch between two themes using JavaScript:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Dynamic Theme Switching</title>
  <link id="theme" rel="stylesheet" href="light.css">
</head>
<body>
  <h1>Hello World!</h1>
  <button id="theme-toggle">Toggle Theme</button>
  
  <script>
    const toggleButton = document.getElementById('theme-toggle');
    const themeLink = document.getElementById('theme');
    
    toggleButton.addEventListener('click', () => {
      if (themeLink.getAttribute('href') === 'light.css') {
        themeLink.setAttribute('href', 'dark.css');
      } else {
        themeLink.setAttribute('href', 'light.css');
      }
    });
  </script>
</body>
</html>
```

In this example, we have an HTML file that links to a `light.css` stylesheet. We also have a button with an ID of `theme-toggle` that the user can click to toggle the theme between light and dark.
 
We use JavaScript to listen for a `click` event on the `theme-toggle` button. 
When the user clicks the button, we check the `href` attribute of the stylesheet link. If the `href` value is `light.css`, we switch to `dark.css`. If it's `dark.css`, we switch to `light.css`.

I hope this helps you implement the dynamic theme switching feature. If you have any further questions, please feel free to ask.
