### ISSUE TITLE
🐛[问题] 新项目为什么build速度这么慢？

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design-pro#9196]
### 🐛 bug 描述

从初始化后也就新加了6-7个简单界面，为什么build速度会如此慢？

![image](https://user-images.githubusercontent.com/20419163/137607959-7269e2fc-8b63-4c93-b963-5ec5b695ebee.png)

![image](https://user-images.githubusercontent.com/20419163/137608125-4f0a3c5f-ee20-4b43-926e-955f095d140a.png)

### 📷 复现步骤

npm run build

### 🏞 期望结果

30s内

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本:  5.0.0
- umi 版本 :3.5.19
- 浏览器环境: 在ternimal下编译
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
36s 不算慢的。前端的生态现在就是这么难受。小文件太多了

**Comment by chenshuai2144** [comment]
那就是电脑的问题了。用github 的action 跑一下试试

**Comment by kevinpursuing** [comment]
有点影响效率了，而且在使用mfsu时，对于在app.tsx中的改动有几率页面不生效，不管如何刷新也是

**Comment by kevinpursuing** [comment]
只能重新启动项目，我们基本只是简单的列表功能迭代，有点奇怪

**Comment by chenshuai2144** [comment]
mfsu 是惰性的依赖，可能命中了缓存。
用这个试试，看看是什么在浪费你的时间
https://umijs.org/zh-CN/docs/env-variables#analyze

**Comment by kevinpursuing** [comment]
@chenshuai2144 大佬想请问下，什么情况下build后umi.js里的内容不会包含app.tsx内的配置呢？我发现我在build后app.tsx配置里的拦截器以及自定义收起按钮逻辑都没有打进去，线上已没有生效，umi.xxxx.js也没有相应的内容
