### ISSUE TITLE
从mock切换到服务器

### ISSUE THREAD

**Issue by yccy1230** [ant-design/ant-design-pro#92]
`// .roadhogrc.mock.js
export default {
  'GET /api/*': 'https://your.server.com/api/',
};`

按照这个切换之后并没有成功转发。

**Comment by nikogu** [comment]
请给出提示或者其它详细信息？

**Comment by ecfxs** [comment]
@nikogu  
我也碰到了这个问题 , 以前一直写 VUE 看到模版不错打算尝试一下 , 
根据教程修改了 .roadhogrc.mock.js 中 84 行的代码为 
export default {
  'GET /api/*': 'https://www.xxxx.com/Api/',
};
在浏览器的请求中发现 , 无论线上还是本地请求的地址都还是 当前域名 + 请求 API

列如,部署的前端域名为 abc.com   API域名为 123.com
正常请求应该是  123.com/api/xxx
但是浏览器中请求地址依旧是  abc.com/api/xxx
我不知道哪里错了,第一次使用.希望得到帮助.谢谢

**Comment by ecfxs** [comment]
已经解决了,谢谢 问题是 api 路径问题.请求地址是转发代理的.

**Comment by basicfu** [comment]
@ecfxs @nikogu 开发环境切换到代理可以，但是build之后放到nginx下就不行了，如果路径错了也就算了，关键是后台压根收不到请求，请问你是如何解决的呢，而且他这个是get，我不可能所有的接口都get，去掉get也不行，参照roadhogrc官网的方式设置也不行,
生产环境.roadhogrc.mock.js是如下
```
export default {
  'GET /api/*': 'http://127.0.0.1:8888/',
};
```
我需要将/api/*下的请求代理到服务器8888端口的根路径下，现在404

在开发环境下，只有这样才可以将/api代理到/下，但是打包后放到nginx就不可以，请问到nginx改如何操作？
```
export default {
  'GET /api/(.*)': 'http://127.0.0.1:8888/',
  'POST /api/(.*)': 'http://127.0.0.1:8888/',
};
```

**Comment by basicfu** [comment]
还是说打包成静态文件就不能代理了？以前做的生产环境也是node启动的

**Comment by nikogu** [comment]
@basicfu 打包肯定不能代理呀，代理服务是本地 `roadhog server` 起的服务的功能，你打包以后就只有静态文件

**Comment by basicfu** [comment]
@nikogu 现在有java后台，那意思就是，打包后，比如我nginx端口是8080，java端口是8888，我需要在nginx处设置代理，让8080的/api/代理到8888的/下对吧？

**Comment by basicfu** [comment]
@nikogu 非常感谢，现在通过nginx代理已经可以了，是我理解错roadhog了，现在明白了

**Comment by xiaoNiuNew** [comment]
@ecfxs 最后是怎么改的就问题解决了，你最后的说的`api 路径问题`是什么意思,详细说说...发现好多人不懂怎么关闭mock

**Comment by myyyy** [comment]
@ecfxs 

> 已经解决了,谢谢 问题是 api 路径问题.请求地址是转发代理的.

请问你这个是怎么解决的呢，大哥哥

**Comment by lucasleelz** [comment]
我也没搞懂，不知道打包，部署到服务器应该如何处理了。
