### ISSUE TITLE
typescript项目无法解析组件类型

### ISSUE THREAD

**Issue by sundaypig** [ant-design/ant-design-pro#920]
我的pro组件导入方式：  
  

![image](https://user-images.githubusercontent.com/20181476/36013383-be7d601e-0d9e-11e8-92dd-3df02cfbcf06.png)  
  
ts报错：  
  
![image](https://user-images.githubusercontent.com/20181476/36013409-eb8d5b36-0d9e-11e8-875f-b530e3441bd6.png)
  
  
这么写虽然能正常运行，但是ts会提示错误

**Comment by chenshuai2144** [comment]
不要加*试试看

**Comment by sundaypig** [comment]
不加*得到的AntLogin是undefined

**Comment by chenshuai2144** [comment]
给我看一下你的 tsconfig

**Comment by sundaypig** [comment]
![image](https://user-images.githubusercontent.com/20181476/36068310-4f0de058-0f0d-11e8-8732-ab269d9efd7f.png)

**Comment by chenshuai2144** [comment]
allowSyntheticDefaultImports

**Comment by sundaypig** [comment]
增加allowSyntheticDefaultImports: true后组件导入方式：  
  
![image](https://user-images.githubusercontent.com/20181476/36069352-d311369c-0f22-11e8-9797-575cc0d5fee6.png)
  
开发环境编译配置：  
  
![image](https://user-images.githubusercontent.com/20181476/36069364-f2101928-0f22-11e8-98a9-5cf44c43a9cd.png)
  
以上在开发环境是正常  
  
生产环境编译配置改成 `module: 'commonjs'` 后报错：  
  
![image](https://user-images.githubusercontent.com/20181476/36069401-c4a78ba0-0f23-11e8-8b1e-78d655c6ad57.png)

![image](https://user-images.githubusercontent.com/20181476/36069397-b62e56bc-0f23-11e8-96e5-84b260b8880a.png)

**Comment by chenshuai2144** [comment]
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es2016",
    "lib": [
      "es6",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
```

试试我的这个

**Comment by chenshuai2144** [comment]
跟随一下最佳实践吧
esnext 才是未来

**Comment by sundaypig** [comment]
还需要考虑一下编译不支持esnext的模块吧

**Comment by chenshuai2144** [comment]
typescript 已经处理了 你不需要担心的
