### ISSUE TITLE
await initialState?.fetchUserInfo?.() 传参

### ISSUE THREAD

**Issue by fungmo** [ant-design/ant-design-pro#9202]
### 🧐 问题描述

由于获取当前用户接口需要等到登录接口拿到的token作为参数，所以我的想法是在
await initialState?.fetchUserInfo?.() 中的（）中传参，但是fecthUserInfo接口并没有获取到参数。

### 💻 示例代码

await initialState?.fetchUserInfo?.(’token123456‘) 

### 🚑 其他信息

antd pro v5

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design-pro/blob/319d889bbe6789477e4c430fb881558c25b43f1b/src/app.tsx#L26-L28 这里有没有入参，要把相关代码都贴出来

**Comment by chenshuai2144** [comment]
看样子是类型没定义的问题。另外 initialState 是有闭包的。最好搞成无状态的，或者把 token 也用 initialState 存起来

**Comment by chenshuai2144** [comment]
直接console 一下 funtion.toString 就能看到里面的源码了
