### ISSUE TITLE
Select 和 Input 图标风格不一致 看图🐛[BUG]

### ISSUE THREAD

**Issue by github262302** [ant-design/ant-design-pro#9205]
### 🐛 bug 描述

Select 和 Input 图标风格不一致 

### 🏞  图片

![截屏2021-10-19 下午4 42 48](https://user-images.githubusercontent.com/71603326/137875767-7c0b8379-8dc9-4181-88a4-fe7874c6c665.png)

### © 版本信息

- Ant Design Pro 版本: [5.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by github262302** [comment]
> 有什么不一样？

没有在输入框里面啊

**Comment by buxinren** [comment]
看着一样啊
