### ISSUE TITLE
jest测试与简易数据流以及全局初始数据不兼容🐛[BUG]

### ISSUE THREAD

**Issue by JackXueX** [ant-design/ant-design-pro#9206]
### 🐛 bug 描述

在组件中进行单元测试的时候，如果该组件使用了简易数据流或者全局初始数据，测试通不过，并且报错

### 🏞 期望结果

测试通过

### 💻 复现代码

```
import React from 'react';
 import { render, cleanup, screen } from '@testing-library/react';
 import '../matchMedia.mock';
 import CashRecharge from '../../components/CashRecharge';
 
 afterEach(cleanup);
 describe('CashRecharge 测试', () => {
   test('renders CashRecharge component', () => {
     render(<CashRecharge />);
     screen.debug();
   });
 });
```

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本 3.5.0
- 浏览器环境 
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🚀 解决方案

在单元测试中使用简易数据流或全局初始数据，需要在测试文件中引入对应的 Provider 组件，并注入相应的数据。

以 Redux 为例，可以按照以下的方式进行测试：

```javascript
import React from 'react';
import { render, cleanup, screen } from '@testing-library/react';
import { Provider } from 'react-redux';
import configureStore from 'redux-mock-store';
import CashRecharge from '../../components/CashRecharge';

const mockStore = configureStore([]);

describe('CashRecharge 测试', () => {
  let store;

  beforeEach(() => {
    store = mockStore({
      // 在这里设置全局初始数据
      globalData: {
        userName: 'test',
      },
    });
  });

  afterEach(cleanup);

  test('renders CashRecharge component', () => {
    render(
      // 在这里使用 Provider 注入数据
      <Provider store={store}>
        <CashRecharge />
      </Provider>,
    );
    screen.debug();
    // 验证测试是否通过
    expect(screen.getByText('Cash Recharge')).toBeInTheDocument();
  });
});
```

需要注意的是，在测试文件中需要手动设置全局初始数据，否则在测试中无法获取到数据，从而导致测试失败。

关于简易数据流的测试，也需要类似的进行数据注入和 Provider 的使用，不同的简易数据流有不同的具体实现方式，请查看对应的文档进行测试。

### 📖 参考文档

- [Redux Testing Guide](https://redux.js.org/recipes/writing-tests/#component-tests)
