### ISSUE TITLE
🧐[问题]ProTable自带的搜索表单

### ISSUE THREAD

**Issue by DengJie001** [ant-design/ant-design-pro#9208]
### 🧐 问题描述
ProTable自带的搜索表单，如果我没有输入过内容，获取不到字段信息，如果输入过，然后再删除表单输入的内容会得到空字符串，这是设计上就是这样的吗？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/41319355/138019431-1704c013-8bb3-4d1a-b93d-39b569af2d4f.png)

**Comment by chenshuai2144** [comment]
用clear 点一下就是 undefined，这个 html 的规范。
