### ISSUE TITLE
🐛[BUG]ant design  中的modal image 打开或预览后 滚动条自动置顶 

### ISSUE THREAD

**Issue by chenpeizhen** [ant-design/ant-design-pro#9209]
### 🐛 bug 描述

当页面长度超于屏幕，在底部点击image 或 打开modal  关闭后 滚动条自动置顶

### 🏞 期望结果

当页面长度超于屏幕，在底部点击image 或 打开modal  关闭后 滚动条保持当前位置
像ant design 中的modal 和 image  一样

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个问题应该是你的滚动条不在body上导致的。
modal 只会处理 在body上的滚动条可能吧别的滚动条弄坏了

**Comment by chenpeizhen** [comment]
> 这个问题应该是你的滚动条不在body上导致的。 modal 只会处理 在body上的滚动条可能吧别的滚动条弄坏了


你可以直接创建一个umi项目，超过屏幕高度创建一个modal 打开模态框后 滚动条自动置顶
