### ISSUE TITLE
👑 [需求] 能否提供一个单元测试的示例，示意如何 mock 国际化和 useModel 之类的？

### ISSUE THREAD

**Issue by GreatAuk** [ant-design/ant-design-pro#9211]
### 🥰 需求描述

能否提供一个单元测试的示例，示意如何 mock 国际化 、useModel、dva 等功能？难道说阿里内部也不进行单元测试吗
目前国际化和 useModel 这些功能对普通开发者来说就是个黑盒，如果一个组件使用了国际化、useModel 之类的功能，直接单元测试是直接报错的。

挺多 issue 也是类似的问题
https://github.com/ant-design/ant-design-pro/issues/6151
https://github.com/ant-design/ant-design-pro/issues/9206
https://github.com/umijs/umi/issues/5138
https://github.com/umijs/umi/issues/4598
https://github.com/umijs/umi/issues/4358
。。。

**Comment by Yovven** [comment]
m

**Comment by Bourhjoul** [comment]
why there is no answer to this? 
--- no test example provided for useModel and useIntl....!

**Comment by httol** [comment]
> 邮件收到啦~~谢谢你！

怎么解决的？倒是说一句啊，你这回复有什么用

**Comment by Yovven** [comment]
邮件收到啦~~谢谢你！

**Comment by chenshuai2144** [comment]
在umi那边跟踪吧

**Comment by httol** [comment]
社区也就这意思了，没啥意思

**Comment by SiO2-A** [comment]
https://blog.csdn.net/qq_37904407/article/details/131581751
我写了一个示例，能用，有问挺给我反馈
