### ISSUE TITLE
🧐[问题] 每次打完包更新到服务器上打开项目页面并未更新到最新代码，需要刷新，怎么样每次打开就是最新的数据?

### ISSUE THREAD

**Issue by LB-nan** [ant-design/ant-design-pro#9212]
### 🧐 问题描述

每次项目打包完毕，虽然umi.js里面会有hash值，但是更新到服务器上之后，运营人员打开网站还是更新前的样子，需要刷新才可以获取到最新的页面，检查完之后发现umi.xxxx.js没有改变，还是之前的js文件，但是打包的时候每次都打出来不同的hash后缀了，猜测可能是`index.html`被缓存然后里面引用的还是旧版本的.js文件

现在的需求是：每次打开网站自动是最新的，不走缓存，是需要后台返回的响应头设置`Cache-control:no-cache`么？或者怎么刷新`index.html`或者有其他解决方案，麻烦告知个具体思路或代码。谢谢~~

**Comment by Yuaao** [comment]
咋配置呀

**Comment by cuiliming666** [comment]
大佬请问下怎样配置
