### ISSUE TITLE
使用 `useRequest` 导致 Uncaught Error: url MUST be a string

### ISSUE THREAD

**Issue by codthing** [ant-design/ant-design-pro#9217]
### 🐛 bug 描述

在使用useRequest调用接口func的时候，会报 `Uncaught Error: url MUST be a string`，
更确切地说，应该是useRequest不支持url传参。

### 📷 复现步骤
1. pages/DashboardWorkplace/index.tsx
```base
const sign = {token:'123456', type: '1'}
const { loading: activitiesLoading, data: activities = [] } = useRequest(queryActivities({sign}))
```

2. pages/DashboardWorkplace/service.ts
```base
export async function queryActivities(params: {sign?: Object}): Promise<{ data: ActivitiesType[] }> {
  return request(
    '/kpi/notice/getNoticelast',
    {
      method: 'GET',
      params: { ...params },
      headers: {
        'Content-Type': 'application/json',
      }
    },
  );
}
```

3. 查看network中的请求，可以看到请求成功且返回成功的数据

### 我尝试将url中的参数改为字符串，依然会收到同样的错误信息
1. pages/DashboardWorkplace/index.tsx
```base
const sign = '1111'
const { loading: activitiesLoading, data: activities = [] } = useRequest(queryActivities(sign))
```

2. pages/DashboardWorkplace/service.ts
```base
export async function queryActivities(sign?: String): Promise<{ data: ActivitiesType[] }> {
  return request(
    '/kpi/notice/getNoticelast',
    {
      method: 'GET',
      params: { ...sign },
      headers: {
        'Content-Type': 'application/json',
      }
    },
  );
}
```

### 🏞 期望结果

没有报错

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本 [^3.5.0]
- 浏览器环境  [Chrome]
- 开发环境 [Win10专业版]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/16655229/138426561-e8ea6a8e-ffbc-4ddd-ab77-b97961e4792e.png)
![image](https://user-images.githubusercontent.com/16655229/138426624-c2afbabc-28ee-4db4-ab9b-b1d37a262dea.png)
![image](https://user-images.githubusercontent.com/16655229/138426487-9802fdea-6ee4-4668-be5f-1d8084a1dedf.png)

**Comment by FanNick** [comment]
如果你有参数，就这样调 `useRequest(()=>queryActivities(params))`
