### ISSUE TITLE
有类似java shiro这样的RBAC（基于角色的权限管理）模块吗？

### ISSUE THREAD

**Issue by febzhang** [ant-design/ant-design-pro#922]
中后台，有不少按照角色分配菜单、button权限的需求

**Comment by chenshuai2144** [comment]
全世界都没有这么强大的前端框架 我们提供了很简单的，你可以在上面封装一下 二次开发

**Comment by leeyisoft** [comment]
自己写 “按角色分配菜单”，在现在的代码的基础上面，貌似不好实现，能否提供一些参考方法 @chenshuai2144
