### ISSUE TITLE
What is the right way to enable web pack asyncWebAssembly: true?

### ISSUE THREAD

**Issue by judeebene** [ant-design/ant-design-pro#9223]
### 🧐 Problem description
 The config.ts has webpack5 configuration with the following options
```
webpack5?: {
lazyCompilation?: {
entries?: boolean
imports?: boolean
test?: any
},
```
But there is no asyncWebAssembly:boolean to enable web assembly.

I am trying to use a wasm library that require  me to enable 
```
experiments: {
      asyncWebAssembly: true,
    }
```
I know we can Modify webpack configuration through webpack-chain API , using `chainWebpack() in config.ts`

But I am not sure how to use chainWebpack() to enable asyncWebAssembly.

Please Can someone point me to the right way of enabling asyncWebAssembly for webpack in Ant design pro?

**Comment by judeebene** [comment]
Hi @sorrycc  please any update on this?

**Comment by caicai1998** [comment]
how to resole

**Comment by judeebene** [comment]
@caicai1998  try this in config.ts
`chainWebpack: function (config, { webpack }) {
    config.merge({
      experiments: {
        asyncWebAssembly: true,
    
      },
      resolve: {
        extensions: [ '.wasm'],
      },
    });
  },`

**Comment by caicai1998** [comment]
> config.merge({
> experiments: {
> asyncWebAssembly: true
> },
> resolve: {
> extensions: [ '.wasm'],
> },
> });

![image](https://user-images.githubusercontent.com/64702233/170642747-2ac7074d-25b2-42e7-8332-7f8c925fd4f2.png)
![image](https://user-images.githubusercontent.com/64702233/170642768-7e615af1-5cb3-4d99-843e-6ddb29e5b09e.png)
why?
