### ISSUE TITLE
proTable中columns中数据时通过request获取，每次清空选项也会触发request

### ISSUE THREAD

**Issue by nanianlisao** [ant-design/ant-design-pro#9224]
如省市区这种联动的下拉选择框， 每次清空选项都会导致request重新出发， 有什么办法能避免吗

部分代码：

        {
          title: '站点',
          valueEnum: allSite
          order: 1,
          dataIndex: 'countryCode',
        },
        {
          title: '仓库名称',
          dataIndex: 'warehouseCode',
          fieldProps: {
            showSearch: true,
          },
          dependencies: ['countryCode'],
          request: async ({ countryCode }) => {
            formRef?.current?.setFieldsValue({ warehouseCode: undefined });
            if (countryCode) {
              const res = await getAllWarehouse(countryCode);
              return res?.map((item) => ({
                label: item.name,
                value: item.code,
              }));
            } else {
              return [];
            }
          },
        },

现在需要给下拉框加一个搜索功能， 每次输入都导致了一次request 有什么办法能解决呢

**Comment by chenshuai2144** [comment]
默认加了一个去抖，会显著减少请求
