### ISSUE TITLE
👑 [需求] v4版本 routes怎么做国际化处理

### ISSUE THREAD

**Issue by dushanchuang** [ant-design/ant-design-pro#9225]
### 🥰 需求描述

因为业务需要，之前的项目使用的是v4版本，老板让做中英文的国际化处理。其他地方都能够正常的中英文切换，但是路由菜单这块不清楚怎么处理，求帮助。

**config/routes.ts 中**
`    routes: [
      {
        path: '/',
        component: '../layouts/BasicLayout',
        Routes: ['src/pages/Authorized'],
        routes: [
          {
            path: '/',
            redirect: '/analysis',
          },

          {
           name: "welcome",
            path: '/analysis',            
            icon: 'dashboard',
            locale: 'menu.welcome', 
            tenant: ['admin', 'member'],
            iconfont: 'icon-tongjifenxi',
            component: './analysis',
          },`

**zh-CN页面**
`export default {
  'menu.welcome': '欢迎页面',`

**en-US页面**
`export default {
  'menu.welcome': 'welcome',`

### **显示结果**
无论怎么切换中文或者英文， 左侧的菜单 就显示 welcome， 中文也不显示欢迎页面。

求大神一个解决办法，最好详细点说明一下，谢谢

**Comment by HaMi033** [comment]
@chenshuai2144 name: "welcome", 是不是没传入 formartMessage 方法 这个是要在config/routes.ts中配置吗？还是自己在菜单组件展示时，自己使用formartMessage方法去转换

**Comment by MEDASSSSSSS** [comment]
如果使用了ProLayout组件 ，将formatMessage传入ProLayout组件 试试

import { Link, useIntl, connect } from 'umi';

const MyLayout= （）=>{
     ......
     const { formatMessage } = useIntl();
     return <ProLayout formatMessage={formatMessage }>
     ......
</ProLayout>
}
