### ISSUE TITLE
浏览器地址栏直接访问后端接口404

### ISSUE THREAD

**Issue by codercatmomi** [ant-design/ant-design-pro#923]
浏览器地址栏直接访问后端接口404

需求：不跳到404页面，可以直接新页面打开后端接口

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。
