### ISSUE TITLE
🐛[BUG] 使用 @testing-library/react 测试组件时，报`React is not defined`

### ISSUE THREAD

**Issue by hackers267** [ant-design/ant-design-pro#9231]
### 🐛 bug 描述

使用 ant-design-pro项目，React版本为17时，测试组件，报`React is not defined`

### 📷 复现步骤

1. 使用`npx create-umi myapp` 创建项目。
2. 修改 jest的配置文件`jest.config.js` ，extraSetupFiles为setupFiles。
3. 添加依赖`@testing-library/react`.
4. 创建测试组件文件。
5. 运行`npm run test` 进行测试。

### 🏞 期望结果

在React组件和测试文件中，不需要显式引入`import React from 'react'`。可以运行测试。

### 💻 复现代码

在`Component`目录下创建`__tests__`目录，创建`footer.test.tsx`文件，使用以下代码：

```typescript-react
import Footer from '../index';
import { render } from '@testing-library/react';
describe("Footer",()=>{
    test("render",()=>{
      render(<Footer/>)
    })
})

```
### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本: ^3.5.17
- 开发环境: archLinux  node v12.22.1
- React: ^17.0.0

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/22020318/138793204-4023f284-2053-425b-9723-885047ebdda6.png)

**Comment by chenshuai2144** [comment]
这个好像不行，因为要初始化组件就要调用react，你google一下是不是有什么办法可以注入。

我自己写测试用例用到了mount 和render 还是要自己引入的

**Comment by hackers267** [comment]
了解到这个问题是umi的测试框架的bug。umi修改好了，这里自然就可用了

**Comment by hlouis** [comment]
@hackers267 hi 请问一下有 Umi 这里和 test 问题相关的 issue 么，我也遇到了同样的问题，但是没有找到解决的方案。
