### ISSUE TITLE
useModel('xxx')，类型xxx的参数不能赋值给类型@initialState的参数

### ISSUE THREAD

**Issue by codthing** [ant-design/ant-design-pro#9232]
### 🐛 bug 描述

按照文档的使用方式，在src/models/中，命名一个叫xxx(举例)的namespace，然后在使用的地方调用的时候，有红色波浪线提示如题。

### 📷 复现步骤

src/models/test.ts
```base
export default () => {
    const testData = '测试'
    return testData
}
```
src/pages/edit.tsx
```base
 export default () => {
  const {testData} = useModel('test')
}
```

### 🏞 期望结果

没有红色波浪线的提示

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本 [^3.5.0]
- 浏览器环境 [Chrome]
- 开发环境 [win10]

### 🚑 其他信息
app.tsx中的getInitialState是有在使用的
https://github.com/ant-design/ant-design-pro/issues/8404#issuecomment-826292053
，我的初始化等用户信息都是通过这个去获取的。

![image](https://user-images.githubusercontent.com/16655229/138855929-6dec1a4c-e832-4000-94da-28a5bcf44687.png)

**Comment by chenshuai2144** [comment]
fixed
