### ISSUE TITLE
🧐[问题] TreeSelect异步加载数据的回显问题

### ISSUE THREAD

**Issue by MrTung** [ant-design/ant-design-pro#9233]
### 🧐 问题描述

TreeSelect数据量在较大时候，通常都会采用异步加载下一级数据源的方式。比如行政区划，点击浙江省，才会去加载浙江省下面的市列表，点击杭州市，才会去加载杭州市下面的区列表。那假如我此刻选择了杭州市区下面的西湖区，并完成业务操作。

在表单页打开回显的时候，该TreeSelect的初始数据实际只有省数据，而form-item的数据是【西湖区】的id，就不能正确的回显。

请问有没有好的解决方案？

**Comment by iamxiaojianzheng** [comment]
> ### 🧐 问题描述
> TreeSelect数据量在较大时候，通常都会采用异步加载下一级数据源的方式。比如行政区划，点击浙江省，才会去加载浙江省下面的市列表，点击杭州市，才会去加载杭州市下面的区列表。那假如我此刻选择了杭州市区下面的西湖区，并完成业务操作。
> 
> 在表单页打开回显的时候，该TreeSelect的初始数据实际只有省数据，而form-item的数据是【西湖区】的id，就不能正确的回显。
> 
> 请问有没有好的解决方案？
> 
> ### 💻 示例代码
> ### 🚑 其他信息

你好，请问最后怎么解决的呀？跟你一样的情况

**Comment by ShuBuShao** [comment]
怎么解决，大佬们提供一下思路
