### ISSUE TITLE
顶栏菜单对应着哪个文件

### ISSUE THREAD

**Issue by linghuchong-asen** [ant-design/ant-design-pro#9236]
1.顶栏菜单对应着哪个文件，我想改变顶栏的布局，增加文字，在pages文件夹和components文件夹下都没有找到，
2.另外想问一下怎么现在没有layout文件夹了，这一部分功能放哪里了，
3.项目的打包入口文件是哪个
![image](https://user-images.githubusercontent.com/67812417/139041353-1a5d2d47-f838-42cc-9996-5e8921acacd5.png)

**Comment by wiredgril666** [comment]
遇到了同样的问题。有demo可以教下怎么使用吗？在app layout里面想用useState

**Comment by wiredgril666** [comment]
遇到了同样的问题。有demo可以教下initialState怎么配合layout使用吗？在app layout里面想用useState,好比菜单搜索的功能
const filterByMenuDate = (data: MenuDataItem[], keyWord: string): MenuDataItem[] =>
  data
    .map((item) => {
      if (
        (item.name && item.name.includes(keyWord)) ||
        filterByMenuDate(item.routes || [], keyWord).length > 0
      ) {
        return {
          ...item,
          routes: filterByMenuDate(item.routes || [], keyWord),
        };
      }

      return undefined;
    })
    .filter((item) => item) as MenuDataItem[];
export const layout = ({
  initialState,
}: {
  initialState: {
    settings?: LayoutSettings;
    currentUser?: API.CurrentUser;
    globalEnum?: API.GlobalEnum;
    keyWord?: string;
  };
}): BasicLayoutProps => {
  const [keyWord, setKeyWord] = useState('');
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { currentUser } = initialState;
      const { location } = history;
      if (location.pathname !== '/user/login' && location.pathname !== '/dashboard') {
        addPath(location.pathname, location.search);
      }
      // 如果没有登录，重定向到 login
      if (!currentUser && location.pathname !== '/user/login') {
        history.push('/user/login');
      }
    },
    menuExtraRender: ({ collapsed }) =>
      !collapsed && (
        <Input.Search
          onSearch={(e) => {
            setKeyWord(e);//怎么替换initialState?
          }}
        />
      ),
    postMenuData: (menus) => filterByMenuDate(menus || [],keyWord),
    ...initialState?.settings,
  };
};
