### ISSUE TITLE
未在menu里配置的页面 对应某个导航高亮的问题

### ISSUE THREAD

**Issue by codercatmomi** [ant-design/ant-design-pro#924]
问题：
未在menu里配置的页面 想要对应menu里的某个导航项；
如何配置呢?

**Comment by chenshuai2144** [comment]
暂时无法实.你可以在源代码里面修改一下逻辑。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/SiderMenu/SiderMenu.js
