### ISSUE TITLE
🐛[BUG]5.0版本点击OpenAPI文档报错：ReferenceError: arrayConfig is not defined

### ISSUE THREAD

**Issue by BenlovedLamphere** [ant-design/ant-design-pro#9247]
🐛 bug 描述
启动项目以后，点击左下角的 OpenApi文档 ，页面报错：

ReferenceError: arrayConfig is not defined

.ant-design-pro/src/.umi/plugin-openapi/openapi.tsx:8

>  8 |   const [value, setValue] = useState(arrayConfig[0]?.projectName || "openapi");

📷 复现步骤
启动项目以后，点击左下角的 OpenApi文档 。

🏞 期望结果
正常展示。

© 版本信息
Ant Design Pro 版本: [e.g. 5.0.0]
umi 版本 ：3.5.0
node 版本：12.13.0
浏览器环境：chrome
开发环境 [e.g. mac OS BigSur 11.6.1 (20G224)]

**Comment by xkw-ayl** [comment]
V5的监控页也报错
Unhandled Rejection (Error): Cannot apply @injectable decorator multiple times.

**Comment by xkw-ayl** [comment]
上周我拉下来安装还没问题，这两天就各种报错，感觉应该是某个依赖小版本更新导致的
