### ISSUE TITLE
登录问题，我修改了登录接口，但是登录接口只能用GET提交，无法使用POST提交

### ISSUE THREAD

**Issue by siufong-cheung** [ant-design/ant-design-pro#925]

**Comment by siufong-cheung** [comment]
不是头信息问题，是使用POST访问的话提示404，用GET访问的话就正常

**Comment by chenshuai2144** [comment]
使用工具测试一下吧 这个锅可不是我们能做的。
你的代理配置了？

**Comment by siufong-cheung** [comment]
代理已经配置好了
`export default noProxy ? {'/*': 'http://service.dev/'} : delay(proxy, 1000);`
也使用postman测试过，直接POST访问http://service.dev是正常的，但是POST代理过去就提示404了

**Comment by chenshuai2144** [comment]
noProxy 是 true 吗？

**Comment by siufong-cheung** [comment]
是的
`const noProxy = true;`

`export async function fakeAccountLogin(params) {
  return request('/api/web/v1/accounts', {
    method: 'POST',
    body: params,
  });
}`

我用的是restful规则，method用GET正常，改成POST就404

**Comment by siufong-cheung** [comment]
![image](https://user-images.githubusercontent.com/35514479/36069485-bf715e3e-0f25-11e8-9291-c6572c04875e.png)
![image](https://user-images.githubusercontent.com/35514479/36069492-d59fc966-0f25-11e8-9094-1396a4f302bb.png)

**Comment by chenshuai2144** [comment]
试试 roadhog 的代理？

**Comment by siufong-cheung** [comment]
![image](https://user-images.githubusercontent.com/35514479/36069540-b28e345c-0f26-11e8-8d68-eb4640b82fa2.png)
开启代理后，访问本地 servic mock的静态数据是正常的

**Comment by siufong-cheung** [comment]
问题已经解决了，感谢帮助

**Comment by chenshuai2144** [comment]
怎么解决的？

**Comment by siufong-cheung** [comment]
`export default noProxy ? {
  'GET /*': 'http://service.dev/',
  'POST /*': 'http://service.dev/'
} : delay(proxy, 1000);`
添加多一个POST，源代码只有GET

**Comment by chenshuai2144** [comment]
.....
