### ISSUE TITLE
🧐[问题] 开发/正式版本打印的服务器302重定向请求url不一致

### ISSUE THREAD

**Issue by guogeer** [ant-design/ant-design-pro#9250]
### 🧐 问题描述
最近更新的ant design pro v5版本。开发版本收到的服务器302重定向Response
![image](https://user-images.githubusercontent.com/5010851/139393823-b4b6996c-5312-49e2-a2f0-5a95d5cff861.png)
发布的版本收到的服务器302重定向Response
![image](https://user-images.githubusercontent.com/5010851/139393930-52fa1736-1780-455f-a10c-998c2a269ac4.png)

### 💻 示例代码
const responseInterceptor = (response: Response) => {
  console.log(response);
}

**Comment by MachoManCk** [comment]
我也遇到了这个问题  发布后pathname不相等了 自动在后缀加了一个/的符号

**Comment by chenshuai2144** [comment]
这个东西是你们后端接口给的吧，这个前端还来不及处理呢

**Comment by guogeer** [comment]
![image](https://user-images.githubusercontent.com/5010851/139761121-1432fea7-3f47-4538-b46e-7d031297d07c.png)
这是后端回复的302请求协议头
@chenshuai2144

**Comment by chenshuai2144** [comment]
这个应该是后端给的，让他帮你设定一下呢

**Comment by guogeer** [comment]
> 这个应该是后端给的，让他帮你设定一下呢

主要是不知道为啥链接最后多了一个右斜杆“http://example.com/user/login/”，我自己就是后端。这个框架好处就是门槛低。
