### ISSUE TITLE
router部署到服务器之后，pathname后面多了一个/的符号

### ISSUE THREAD

**Issue by MachoManCk** [ant-design/ant-design-pro#9252]
部署到服务器之后 pathname后多了一个/的符号 比如本地开发的时候pathname为/user/login 部署到服务器上就变成/user/login/ 是什么原因导致的呢

**Comment by chenshuai2144** [comment]
这个一般是容器配置的重定向， 你检查一下你的容器配置。

nginx 一般是 server_name_in_redirect off;
