### ISSUE TITLE
🧐[问题]初始化项目后 ./vscode/settings.json 中 "editor.defaultFormatter": "esbenp.prettier-vscode" 收到警告信息 

### ISSUE THREAD

**Issue by puxiao** [ant-design/ant-design-pro#9254]
### 🧐 问题描述

使用脚手架创建一个基于 TS 的项目后，在 VSCode 中打开，遇到了一个警告信息。

### 🚑 其他信息

![](https://puxiao.com/temp/andt_pro_warrn.jpg)

**Comment by chenshuai2144** [comment]
没装 prettier  插件，去装一下吧

**Comment by puxiao** [comment]
我平时使用 Beautify 这个插件，我刚开始使用 Antd Pro，感谢解惑。

**Comment by chenshuai2144** [comment]
prettier 最棒了
