### ISSUE TITLE
👑 [需求]根据路由自动收起侧边菜单

### ISSUE THREAD

**Issue by liangxp** [ant-design/ant-design-pro#9255]
### 🥰 需求描述
官方原有已经支持隐藏，见：https://pro.ant.design/zh-CN/docs/layout#%E6%A0%B9%E6%8D%AE%E8%B7%AF%E7%94%B1%E9%9A%90%E8%97%8F%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95%E9%9A%90%E8%97%8F%E5%AF%BC%E8%88%AA%E5%A4%B4footer
期望进入某些页面可以支持自动收起侧边菜单，如下图：
![image](https://user-images.githubusercontent.com/6928085/139654161-f72cf2d2-628f-4cb9-900c-26696b1d7419.png)

### 🧐 解决方案
建议在官方目前实现隐藏的方案中增加如下实现：
`
// config/route.ts
export default [
  {
    path: '/overview',
    component: 'Overview/index',
    name: 'overview',
    icon: 'testicon',
    layout: {
      collapsed:true
    },
  },
];
`

**Comment by chenshuai2144** [comment]
手动写一下吧，不会支持的。
