### ISSUE TITLE
antdpro脚手架,antd4.4.2，umi2.8.7中，使用webassembly+wasm编译的视频解码文件无法正常运行？

### ISSUE THREAD

**Issue by lulu116** [ant-design/ant-design-pro#9258]
### 🧐 问题描述
c++端使用FFmpeg库，webassembly+wasm编译的文件index.js和index.wasm、index.worker.js做动态视频解码功能，现在想要在antdpro脚手架启动的前端项目中使用这三个文件，这三个文件放在public中，但项目启动后这些编译的文件运行异常，错误太多，哪位大佬能帮忙看下呢

项目中放在位置：
![image](https://user-images.githubusercontent.com/32627557/140006193-21bded49-f72c-45f8-9628-ab89447eabe2.png)

使用的三个编译文件：
[11.3sdk.zip](https://github.com/ant-design/ant-design-pro/files/7465163/11.3sdk.zip)

**Comment by chenshuai2144** [comment]
放到public下，然后用 /文件名  饮用吧，import 估计没法生效要自己配置webpack了
