### ISSUE TITLE
🧐[问题] Ant Design Pro 表格某一列不需要html转义

### ISSUE THREAD

**Issue by yhy0** [ant-design/ant-design-pro#9262]
### 🧐 问题描述

Ant Design Pro 表格某一列不需要html转义
{
            title: '指纹',
            dataIndex: 'fingerprint',
            valueType: 'text',
 },

表格这一列，数据返回没有转义

"fingerprint":"<span class=\"ant-tag ant-tag-red\"> Shiro </span>",

前端显示时，转义了，
![image](https://user-images.githubusercontent.com/31311038/140251432-b163d828-4f9e-40a8-b6be-5ab8d76077e6.png)

怎么原样输出？

**Comment by chenshuai2144** [comment]
react 为了解决xss的问题，永远都会转的。你用pre 或者 code 包一下。
```

<pre>
   {text}
</pre>
```
