### ISSUE TITLE
And design pro umi layout - Language select icon to update prop

### ISSUE THREAD

**Issue by nadun94** [ant-design/ant-design-pro#9263]
Hi, 

I am using Ant Design Pro version 4. I am trying to change the Select Language Icon. But It is hard coded in my umi-plugin-locale. 

` <HeaderDropdown overlay={langMenu} placement="bottomRight" {...restProps}>
      <span className={globalIconClassName} style={inlineStyle}>
        <i className="anticon" title={allLangUIConfig[selectedLang]?.title}>
          <svg
            viewBox="0 0 24 24"
            focusable="false"
            width="1em"
            height="1em"
            fill="currentColor"
            aria-hidden="true"
          >
            <path d="M0 0h24v24H0z" fill="none" />
            <path
              d="M12.87 15.07l-2.54-2.51.03-.03c1.74-1.94 2.98-4.17 3.71-6.53H17V4h-7V2H8v2H1v1.99h11.17C11.5 7.92 10.44 9.75 9 11.35 8.07 10.32 7.3 9.19 6.69 8h-2c.73 1.63 1.73 3.17 2.98 4.56l-5.09 5.02L4 19l5-5 3.11 3.11.76-2.04zM18.5 10h-2L12 22h2l1.12-3h4.75L21 22h2l-4.5-12zm-2.62 7l1.62-4.33L19.12 17h-3.24z "
              className="css-c4d79v"
            />
          </svg>
        </i>
      </span>
    </HeaderDropdown>`

My package.json related dependecies are as follows.

` "dependencies": {
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@types/react-slick": "^0.23.5",
    "@umijs/openapi": "^1.1.14",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/route-utils": "^1.0.36",
    "antd": "^4.14.0",
    "react": "^17.0.0",
    "react-chrono": "^1.10.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "umi": "^3.5.20",
    "umi-request": "^1.0.8",
    "umi-types": "^0.5.14"
  },`

  

That would be great if it is possible to change the language icon using a prop.

<img width="153" alt="Screenshot 2021-11-04 at 08 37 46" src="https://user-images.githubusercontent.com/27319447/140251614-5c0156fe-a69a-4284-af82-4a418d096858.png">

Thanks in advance.

**Comment by mankiet** [comment]
Hi, 
I have encountered a similar issue. I would like to change the select language icon to black color. Is there anyway to do that?
