### ISSUE TITLE
🐛[BUG]开启mfsu,有部分表单的样式会失效,比如说日期区间

### ISSUE THREAD

**Issue by sifongithub** [ant-design/ant-design-pro#9266]
### 🐛 bug 描述

开启mfsu,有部分表单的样式会失效,比如说日期区间,关闭mfsu,样式正常显示
### 📷 复现步骤

![微信截图_20211104153609](https://s3.bmp.ovh/imgs/2021/11/6fe30255b3e31d9f.png)

- Ant Design Pro 版本: 5
- umi 版本 3.5.20
- 浏览器环境 edge
- 开发环境 win

### 🚑 其他信息
```javascript
{
 "@ant-design/pro-form": "^1.46.0",
 "@ant-design/pro-table": "^2.30.8",
 "antd": "4.16.13",
 "umi": "^3.5.20",
}
```

**Comment by linjunc** [comment]
对，我也有这个问题，裂开了，全局的procomment组件的样式都会失效

**Comment by sifongithub** [comment]
> 对，我也有这个问题，裂开了，全局的procomment组件的样式都会失效

你这个好像关了mfsu打包一次,然后再开启就解决了,我这个是部分样式失效

**Comment by chenshuai2144** [comment]
@sifongithub  问题是一样的，先关闭一下mfsu吧。umi 在做5.0 ，到时候会有更好的方案
