### ISSUE TITLE
🐛[BUG] 菜单栏的三级菜单使用自定义icon无法显示，一二级菜单显示正常

### ISSUE THREAD

**Issue by 0212lewis** [ant-design/ant-design-pro#9267]
### 🐛 bug 描述

在routes.js配置里使用自定义icon，一二级菜单的图标显示正常，但是三级菜单没法显示icon

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这是个featrue，故意这么搞得。有issue 可以hack 出来，但是和我们的设计规范不符合。

`推荐你不要这么搞，太花了反而影响体验。`
