### ISSUE TITLE
动态菜单🧐[问题]

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#9268]
### 🧐 问题描述
![C274AEC8-0740-4251-95A7-59A948D86902](https://user-images.githubusercontent.com/27960630/140450636-516259f8-e22d-4e51-a59d-0d6a05b426ef.png)
1.如果是从后台获取的菜单 这种字符怎么转成dom了 我没找到有相关示例
![image](https://user-images.githubusercontent.com/27960630/140453515-d479f6be-cc20-41c6-a8be-8c2b90a54135.png)

![image](https://user-images.githubusercontent.com/27960630/140453144-fa79c264-8df3-4991-9398-931020abd992.png)

2.还有个问题就是我尝试写死Test组件发现 菜单渲染没问题但是页面组件没有对应渲染
@chenshuai2144  老哥指教一下

### 💻 示例代码
在线示例 
https://codesandbox.io/s/twilight-sound-h1mrn?file=/src/app.jsx:2157-2163

https://github.com/lovesL/myapp

### 🚑 其他信息
@ant-design/pro-layout": "^6.15.3",

**Comment by lovesL** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
compents是不生效的

菜单和路由是两个概念。菜单是导航 路由管理你到底要打包什么文件。你不能动态路由的

**Comment by lovesL** [comment]
> compents是不生效的
> 
> 菜单和路由是两个概念。菜单是导航 路由管理你到底要打包什么文件。你不能动态路由的

那compent不生效。。那怎么渲染内容了。。。官网例子写的太玄乎了，没搞懂   https://pro.ant.design/zh-CN/docs/advanced-menu

**Comment by chenshuai2144** [comment]
你在路由里配置的是什么就显示什么。菜单只是个导航
