### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by TigerBill2016** [ant-design/ant-design-pro#927]
failed to compile
./src/router.js
typeerror: _core.type.cloneNode is not a function

**Comment by benvirus** [comment]
@TigerBill2016  Node 版本多少

**Comment by TigerBill2016** [comment]
7.1.0

**Comment by chenshuai2144** [comment]
看起来是一个 js 的错误。
你做了什么特殊操作吗？

**Comment by TigerBill2016** [comment]
环境问题吧，重新install可以了
