### ISSUE TITLE
🧐[问题] 点击proTable的全屏后，在手机端上下滑动时触发调音量功能

### ISSUE THREAD

**Issue by ramen-curator** [ant-design/ant-design-pro#9270]
### 🧐 问题描述
请问 proTable点击自带的全屏按钮后，在手机端上下滑动时触发手机的音量/亮度调节功能（左半边屏幕上下滑时调亮度，右半边屏幕上下滑时调音量），这该怎么办呢？谢谢
环境：红米K30

### 💻 示例代码

option:{
    fullscreen: true
}

### 🚑 其他信息

![1636110944212](https://user-images.githubusercontent.com/26692240/140503001-57e19909-8cdc-4a5b-87e2-d89c1734b836.jpg)

**Comment by chenshuai2144** [comment]
这个还真没处理过，一般手机没这个功能吧。你看看能不能禁用掉原生事件。

https://developer.mozilla.org/zh-CN/docs/Web/API/Event/stopPropagation
