### ISSUE TITLE
🧐[问题] 我写了一个util，请问一下这个util 是否能使用 defaultSettings.js 里面的属性，如果能使用，怎么使用呢？

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design-pro#9273]
### 🧐 问题描述

我写了一个util，请问一下这个util 是否能使用 defaultSettings.js 里面的属性，如果能使用，怎么使用呢？

### 💻 示例代码

一个util工具类。就不如pro ant 项目下面的utils下面的 utils 想使用这个defaultSetting.js 里面的东西。怎么搞呢？

**Comment by TangDeYu** [comment]
import { useModel } from 'umi';
const { initialState } = useModel('@@initialState');

**Comment by chenshuai2144** [comment]
直接  import 就可以了，会自动打包的
