### ISSUE TITLE
🧐[问题]  请问怎么主动页面loading

### ISSUE THREAD

**Issue by 15723185734** [ant-design/ant-design-pro#9274]
![image](https://user-images.githubusercontent.com/61341868/140671381-a5856239-3f7b-422e-b200-7fdc6537af45.png)
当我点击菜单上的切换员工端时，我想页面主动loading一下 怎么做呢？

**Comment by 15723185734** [comment]
![image](https://user-images.githubusercontent.com/61341868/140673366-6e9da5bf-294b-4c84-8a25-a1141229885f.png)
我想主动出发这个

**Comment by chenshuai2144** [comment]
在 initialvalues 里面搞个loading，然后在layout的children里面监听一下。


```
// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
     childrenRender: (children) => {
       if (initialState.loading) return <PageLoading />;
        return children;
     },
  };
};
```

**Comment by chenshuai2144** [comment]
在 initialvalues 里面搞个loading，然后在layout的children里面监听一下。


```
// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
      // childrenRender: (children) => {
     if (initialState.loading) return <PageLoading />;
      return children;
     },
  };
};
```

**Comment by baiwumm** [comment]
> 在 initialvalues 里面搞个loading，然后在layout的children里面监听一下。
> 
> ```
> // ProLayout 支持的api https://procomponents.ant.design/components/layout
> export const layout: RunTimeLayoutConfig = ({ initialState }) => {
>   return {
>       // childrenRender: (children) => {
>      if (initialState.loading) return <PageLoading />;
>       return children;
>      },
>   };
> };
> ```

但是切换菜单的时候怎么修改 initialState.loading 的状态呢
