### ISSUE TITLE
🧐[问题] 暗黑模式 设置不生效  多刷新几次会生效 不稳定

### ISSUE THREAD

**Issue by 15723185734** [ant-design/ant-design-pro#9276]
暗黑模式设置无效  反复刷新几次能成功 在刷新几次  有没有效果
![image](https://user-images.githubusercontent.com/61341868/140721152-2120cd1a-191b-417a-b169-8ba7dfe73296.png)

![image](https://user-images.githubusercontent.com/61341868/140721228-57d1af04-deec-4139-a62c-92d0fecb2101.png)
这是包的版本
![image](https://user-images.githubusercontent.com/61341868/140721410-745307a4-0414-4d46-a7ae-b03d984fa158.png)
![image](https://user-images.githubusercontent.com/61341868/140721514-385b09b7-5c5a-459d-ada8-8aacb88ae682.png)
![image](https://user-images.githubusercontent.com/61341868/140721606-5dba051b-cfda-4a39-b1b1-77d8497c9ce3.png)

请问是什么原因

**Comment by chenshuai2144** [comment]
在config.ts 里面这样配置好了，永远都是的黑色的。现在的方案效果不行。稳定性堪忧，等antd@5 才能提供完美的动态的

```
export default {
  antd: {
    dark: true,
    compact: true,
  },
}
```
