### ISSUE TITLE
🧐[问题]ant-pro打包的时候，在umi.js文件中出现了模板字符串，在ie11下报错请问有什么办法

### ISSUE THREAD

**Issue by dongcer** [ant-design/ant-design-pro#9277]

**Comment by dongcer** [comment]
![image](https://user-images.githubusercontent.com/35223950/140855251-4b8afbdd-b8da-4cfb-96f9-1cfe44d45fe5.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#nodemodulestransform

最简单的办法把这个打开。虽然会变慢但是兼容性好
