### ISSUE TITLE
列表点击编辑弹出浮层表单，并填充上当前行的值🧐[问题]

### ISSUE THREAD

**Issue by linghuchong-123** [ant-design/ant-design-pro#9278]
### 🧐 问题描述

我想实现列表点击编辑弹出浮层表单，并填充上当前行的值，现在用的是initialValues，但是这个是一加载就渲染，而列表是异步获取，所以拿不到当前行的值，应该怎么实现这个功能；
2.setFieldsValue 这个属性在哪个位置可以设置，我在modalform里设置提示没有这个属性；
3.render属性在哪个表单中有

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/67812417/140881501-3cd81ad4-30cc-46f3-9a3c-6032088ff264.png)
![image](https://user-images.githubusercontent.com/67812417/140881522-84a285de-12a5-4811-80f9-51bbeb336a39.png)

**Comment by chenshuai2144** [comment]
destroyOnClose 打开一下就能解决你的问题了。这样每次打开的时候就会重新生成表单，initalvalues 会再次生效

**Comment by linghuchong-123** [comment]
> destroyOnClose

直接在ModalForm中添加destroyOnClose属性，提示ModalForm没有这个属性 @chenshuai2144

**Comment by lovewaner** [comment]
`{
modalProps: {
destroyOnClose: true
}
}`
