### ISSUE TITLE
[Feature Request] Gantt component

### ISSUE THREAD

**Issue by federico-piazza** [ant-design/ant-design-pro#9279]
### 🥰 需求描述

It would be great if we can have a **Gantt chart**.
如果我们能有甘特图就好了.

### 🧐 解决方案

https://developers.google.com/chart/interactive/docs/gallery/ganttchart
https://ourcodeworld.com/articles/read/509/top-5-best-reactjs-gantt-chart-solutions

### 🚑 其他信息

https://www.gantt.com/img/gantt-chart-1.jpg

**Comment by chenshuai2144** [comment]
https://antv.vision/en


是有的，这个是兄弟团队的作品

**Comment by federico-piazza** [comment]
@chenshuai2144 could you please point me where the Gantt chart is?

你能告诉我甘特图在哪里吗?
