### ISSUE TITLE
How to inject GA in compliance with route changes within Umi.js 

### ISSUE THREAD

**Issue by sambhav2612** [ant-design/ant-design-pro#9280]
As mentioned, we need to add a GA script but we are not sure what's the best way to do this given Umi.js provides a SPA API and hides everything underneath itself. Sharing some package info if it helps:

- antd: ^4.9.4
- @umijs/core: ^3.4.13
- @umijs/route-utils: ^1.0.33
- @umijs/fabric: ^2.8.0
- @umijs/preset-react: ^1.4.8

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#headscripts

look here
