### ISSUE TITLE
🧐[问题]可不可以默认以guest身份进入，访问特定路由下才会触发登录

### ISSUE THREAD

**Issue by Celading** [ant-design/ant-design-pro#9287]
### 🧐 问题描述

我想给让无登录纪录的首次登录用户直接跳转到一个子路由，然后在其点击“登录”页面或者其他子路由的时候才会触发登录。
我试着将跳转登录的部分给注销了，在npm run start可以正常实现效果，但是一旦部署就出问题了...

**Comment by Celading** [comment]
转了好多很棒的开源项目，但是antd和antdpro让我爱不释手，希望大佬们能指点一下（

**Comment by chenshuai2144** [comment]
你可以用权限来做到这个事情。在 跳转登录 的地方加个例外的判断。让没有登陆的跳转到你想要他进入的地方

**Comment by Celading** [comment]
好的谢谢

**Comment by Celading** [comment]
> 你可以用权限来做到这个事情。在 跳转登录 的地方加个例外的判断。让没有登陆的跳转到你想要他进入的地方

不对啊，如果让没有登录的直接跳转到我想要他进入的地方，那登录页面也进不去了啊😂

**Comment by Celading** [comment]
> 你可以用权限来做到这个事情。在 跳转登录 的地方加个例外的判断。让没有登陆的跳转到你想要他进入的地方

以及如果用这种方式进入的话，会正常访问到router里access: 'canAdmin',的页面

**Comment by chenshuai2144** [comment]
if 是你自己写的，你想怎么搞都行的
