### ISSUE TITLE
npm run build之后proxy为何不起作用？

### ISSUE THREAD

**Issue by owengaozhen** [ant-design/ant-design-pro#929]
"proxy": {
     "*":{
        "target": "http://localhost:8080/",
        "changeOrigin": true,
        "pathRewrite": {"^/api" : ""}
     }
  }

编译之后怎么不能使用了。。开发测试是可以的

**Comment by chenshuai2144** [comment]
build 之后是需要你自己部署一个服务用来响应请求的
mock 就是为了开发用

**Comment by benvirus** [comment]
@owengaozhen 开发的时候有用是因为本地起了一个 Node 服务来做代理转发，build 之后本地服务进程关掉了，所以不能代理了，如果需要转发，可以通过 Nginx 或其他方式来实现代理。
