### ISSUE TITLE
🧐[问题]使用官方推荐的openapi生成的接口中怎么传递header参数

### ISSUE THREAD

**Issue by DarkGodOne** [ant-design/ant-design-pro#9292]
### 🧐 问题描述

根据官方推荐使用了openapi生成接口代码，但是发现无法生成header参数，参数会被加到params里面
### 💻 示例代码
json文件如下：
![image](https://user-images.githubusercontent.com/12151282/141446772-87293212-ec1f-4e04-9fbf-0a98d1067edc.png)
生成的接口代码，注释了参数在header里，但是实际没有传递到header里面：
![image](https://user-images.githubusercontent.com/12151282/141446921-747b9665-d97e-4479-9282-6515d5da813b.png)
同样的json在sagger ui里面都是正常的：
![image](https://user-images.githubusercontent.com/12151282/141447340-d74092d0-d28a-4980-933c-6ef0e3156b4e.png)

所以在这里向确认下，这个是我配置的问题，还请各位大佬帮我解惑

**Comment by github262302** [comment]
拦截器自己加

**Comment by chenshuai2144** [comment]
这种token的用拦截器加一下把，不过这个的确是个bug，应该给一个设置header的入口
