### ISSUE TITLE
🧐[问题] 如何关闭CSS Modules

### ISSUE THREAD

**Issue by cwtuan** [ant-design/ant-design-pro#9294]
### 🧐 问题描述
之前这里 #5144 提供的方式，已经失效了，最新版本的ant-design-pro@5.0.0没有`cssLoaderOptions`配置项了

### 💻 示例代码

config.ts
```
cssLoaderOptions: {
    modules: false,
  },
```

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/3455798/141614950-c6a31ecc-53a8-4455-ab3d-1da2bf708e6a.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#cssloader

看看这个，换了个名字了
