### ISSUE TITLE
🧐[问题] mock使用问题

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design-pro#9295]
### 🧐 问题描述
我想使用mock功能，
mock文件是只能放在根目录的mock文件夹下面么？
 我看`antd pro`官网的文档中写到 `在 src/page 中的 mock.ts 的文件中配置`
我在`page/mock.ts `     `/page/mock/xxx.ts` 运行时都不会生效

我用的是 antd rpo最新版本，V5

**Comment by chenshuai2144** [comment]
```
约定式 Mock 文件
Umi 约定 /mock 文件夹下所有文件为 mock 文件。

```

另外 pages 中的也是可以的，但是不能是  page
