### ISSUE TITLE
🐛[BUG] ‘新增加页面’文档中的layout文件指什么？

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9296]
### 🐛 bug 描述

https://beta-pro.ant.design/docs/new-page-cn 中的`新增加布局`段落，没找到layouts文件夹。请问下通过什么命令才能生产？初始化脚手架生成的代码没有

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
手动新建一下好了，这个是一个约定，layout 放到 layouts 文件夹中，但是新版本没有layout了，就没有设置

**Comment by jacktang** [comment]
@chenshuai2144 建议layouts文件夹还是留着，里面放一个SimpleLayout类似的模板。我是之前用antd的，转到antd pro还能去看原来的layout怎么写的。新手真的会很糊涂。。。

**Comment by chenshuai2144** [comment]
我们希望大家都用我们自带的layout，没必要重写了
