### ISSUE TITLE
TypeScript version please

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design-pro#93]

**Comment by afc163** [comment]
TypeScript version is not in our plan now.

**Comment by chenshuai2144** [comment]
typescript增加的成本和带来的便利相比微不足道吧

**Comment by nikogu** [comment]
@chenshuai2144 有兴趣把 v1 的 ts 支持搞了吗（Pro 组件）貌似你已经提交了很多 pr 了

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design-pro/issues/202

**Comment by chenshuai2144** [comment]
@nikogu  我是因为着急要用. 
可以试试

**Comment by zhaojinxiang** [comment]
@chenshuai2144 typescript版本的可以试试用 parcel 咩？这样子就可以在 typescript 版本里面混用
 bucklescript 啦

**Comment by chenshuai2144** [comment]
一直对 OCaml 无感

**Comment by zhaojinxiang** [comment]
@chenshuai2144 parcel 可以免配置支持很多种类型的文件，这样子貌似会很方便扩展包括 typescript 内的很多东西呐

**Comment by chenshuai2144** [comment]
parcel 好评  我正在试着跑项目.生态还是有点问题.期待越来越好

**Comment by zhaojinxiang** [comment]
不过 parcel 跑 ant design pro 有个问题，就是 roadhog 起了个 api 的 mock 服务器。貌似暂时没有发现parcel 的多入口配置方案

**Comment by chenshuai2144** [comment]
毕竟基于webpack webpack4也会做这些.期待把

**Comment by WhatAKitty** [comment]
@chenshuai2144 这个是特性已经完成了吗？

**Comment by chenshuai2144** [comment]
没有 只是0.3的

**Comment by tianlinzx** [comment]
please support typescript

**Comment by chenshuai2144** [comment]
look commit [2baef5e8e39bc1137c70327310f35da3490f2b61](https://github.com/ant-design/ant-design-pro/commit/2baef5e8e39bc1137c70327310f35da3490f2b61).
如果有错误，欢迎提醒，或者直接pr

**Comment by jinrichardJIN** [comment]
support typescript,soud good
