### ISSUE TITLE
使用 dva 进行数据操作请求之后，如何优雅的处理服务器端返回来的数据？

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-pro#930]
例子code:
`
@connect(({paper, loading}) => ({
  paper,
  loading: loading.models.paper,
}))
export default class Paper extends PureComponent {
    handleModalOk() {
    const {dispatch, form} = this.props;
    form.validateFields((err, fieldsValue) => {
      console.log('fieldsValue', fieldsValue);
      if (err) return;
      //Delete unneeded data items
      let questionIds = fieldsValue.questionIds || [];
      delete fieldsValue.questionIds;
      fieldsValue['questionIds'] = questionIds.join(',');
      dispatch({
        type: 'paper/addOrUpdateTest',
        payload: fieldsValue,
      }).then((data)=>{
        console.log('data    =+=======> ',data); //这里怎么处理才能获取到服务器端返回的数据
        message.success('操作成功');
        form.resetFields();
      });
    });
  }
}
`
上代码没有格式了。
看图吧！
![image](https://user-images.githubusercontent.com/12181423/36086420-3951a6fa-1007-11e8-94cf-567a79b100bc.png)

![image](https://user-images.githubusercontent.com/12181423/36086426-470501f2-1007-11e8-9359-3bfe3411e72c.png)

request.js 使用的是ant-design-pro中的 request.js

@sorrycc   @chenshuai2144

**Comment by dengfuping** [comment]
@hqwlkj 你的 `paper/addOrUpdateTest` 有返回 `data` 吗？如果没有，`then` 方法中 `data` 就没有意义。

**Comment by hqwlkj** [comment]
@dengfuping  `paper/addOrUpdateTest`  是 有返回的 `data` ，但是我没有存在 `state` 中，
![image](https://user-images.githubusercontent.com/12181423/36090689-4ba9ee24-101c-11e8-8605-8681d510622d.png)

**Comment by dengfuping** [comment]
@hqwlkj 没有返回 `data` 啊。返回要 return 的。而且也没必要返回，想获取最新的 state，通过 connect 进组件就可以啊。

**Comment by hqwlkj** [comment]
@dengfuping   返回是有必要的啊!如果请求的数据是不存在的或者是有数据异常的，这时候需要处理或者提示服务端返回的`message`，

比如正常的请求返回结果是：`{status:'ok',data:{list:[1,2,3,4,5,6,7,8,9],pagination:{total:1,pageNo:1,pageSize:10}}}`,这样的数据是可以通过`state` 获取的；然后请求的是错误的数据结果是`{status:'error',message:'你访问的信息不存在'}` ，那么这时候就需要将这个错误的 `message` 提出出来，这时候这个返回的`data` 又怎么获取呢？还是通过`state`吗？ 那通过`state` 获取的话，`dispatch`后的 `then` 中的`data`就会永远都是 `undefined`

**Comment by xgenvn** [comment]
一般model里不会返回任何数据的，如果需要callback就用dispatch({type,payload,callback}).

**Comment by hqwlkj** [comment]
@xgenvn   还有这种操作 ，那我试试。谢谢
