### ISSUE TITLE
🧐[问题]使用ProTable，request是获取datasource的方法，这个request是不是页面一刷新的时候就调用，但是我想实现点击按钮才展示数据能不能实现

### ISSUE THREAD

**Issue by linghuchong-123** [ant-design/ant-design-pro#9300]

**Comment by drizzlesconsin** [comment]
manualRequest | 是否需要手动触发首次请求, 配置为 true 时不可隐藏搜索表单 | boolean | false
-- | -- | -- | --

**Comment by linghuchong-123** [comment]
> manualRequest

您说的这个是必须配合Protable自带的search搜索表单才可以使用把，点击搜索按钮的查询时触发，是不是这样？但是我想点击页面别的按钮时触发能做到吗 @drizzlesconsin

**Comment by drizzlesconsin** [comment]
关闭首次请求后，可以用 `actionRef` 自定义触发
actionRef | Table action 的引用，便于自定义触发 | MutableRefObject<ActionType> | -
-- | -- | -- | --

**Comment by linghuchong-123** [comment]
> 关闭首次请求后，可以用 `actionRef` 自定义触发
> 
> actionRef	Table action 的引用，便于自定义触发	MutableRefObject	-

![image](https://user-images.githubusercontent.com/67812417/141762656-5e3ea67c-432c-49a8-a792-87ab47788bc2.png)
actionRef.current上面没有request，请问怎么触发请求，；还有protable上只有request能够改变列表的值吗？为什么不让用datasource属性来改变值，这样设计的初衷是什么，想实现一个动态改变列表值怎么感觉变的更难了 @drizzlesconsin

**Comment by drizzlesconsin** [comment]
[ActionRef 手动触发](https://procomponents.ant.design/components/table/#actionref-%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91)

不想用 request，可以用回 `datasource`

**Comment by linghuchong-123** [comment]
> [ActionRef 手动触发](https://procomponents.ant.design/components/table/#actionref-%E6%89%8B%E5%8A%A8%E8%A7%A6%E5%8F%91)
> 
> 不想用 request，可以用回 `datasource`

您能举例一下怎么用actionRef重新发起requst请求吗，打印出来current确实没有request

**Comment by linghuchong-123** [comment]
还要Proform表单的动态改变默认值，在Pro里也不能很好的实现，是不是涉及到动态改变value的都用antd来实现，Pro自己没有方法实现？

**Comment by chenshuai2144** [comment]
先把文档看完吧，感觉你基础有点薄弱，需要补点上下文，不然issue也看不懂
