### ISSUE TITLE
🐛[BUG] https://preview.pro.ant.design/ 无法打开

### ISSUE THREAD

**Issue by Tonytonyy** [ant-design/ant-design-pro#9304]
### 🐛 bug 描述
https://preview.pro.ant.design/?navTheme=light&primaryColor=%231890ff&layout=mix&fixSiderbar=true&title=Ant+Design+Pro
无法打开

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by RiteshMakan** [comment]
It has been reported here as well
https://github.com/ant-design/ant-design-pro/issues/9302

**Comment by chenshuai2144** [comment]
fixed
