### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dasewan** [ant-design/ant-design-pro#9305]
### 重现链接

http://localhost:8000/user/login

### antd 版本

v5

### 重现步骤
![image](https://user-images.githubusercontent.com/8346782/141883354-de62543c-e214-4537-ad86-f52e5e6b3b71.png)
![image](https://user-images.githubusercontent.com/8346782/141883379-96bc40fc-8db5-44a6-87c4-b17d5b9b5ac1.png)

![image](https://user-images.githubusercontent.com/8346782/141883034-9820219c-22df-4ebc-b057-8107cf292d9d.png)

### 期望的结果是什么？

按照官网上周还可以运行simple成功，这周再拉取运行失败

### 实际的结果是什么？

加载页面后，跳转login页面空白

### 浏览器

Chrome

### 操作系统

Windows

**Comment by jylAJjjsSJDkI** [comment]
实测pro-layout降级到6.27.2就好了

**Comment by ScrappyZhang** [comment]
同出现该问题

**Comment by ScrappyZhang** [comment]
> ### 重现链接
> http://localhost:8000/user/login
> 
> ### antd 版本
> v5
> 
> ### 重现步骤
> ![image](https://user-images.githubusercontent.com/8346782/141883354-de62543c-e214-4537-ad86-f52e5e6b3b71.png) ![image](https://user-images.githubusercontent.com/8346782/141883379-96bc40fc-8db5-44a6-87c4-b17d5b9b5ac1.png)
> 
> ![image](https://user-images.githubusercontent.com/8346782/141883034-9820219c-22df-4ebc-b057-8107cf292d9d.png)
> 
> ### 期望的结果是什么？
> 按照官网上周还可以运行simple成功，这周再拉取运行失败
> 
> ### 实际的结果是什么？
> 加载页面后，跳转login页面空白
> 
> ### 浏览器
> Chrome
> 
> ### 浏览器版本
> _No response_
> 
> ### 操作系统
> Windows
> 
> ### 其他

操作系统：mac 浏览器：chrome
安装时采用yarn 便同出现该问题，主要原因是这样安装的pro-layout是0.几版本。

解决办法：采用npm吧
这样安装的依赖pro-layout是6.29.0

**Comment by chenshuai2144** [comment]
是 @umijs/route 的bug。升级到最新版本就能解决。

也可以锁到 1.x 来保证兼容性

**Comment by coderlcb** [comment]
> pro-layout
你好，我在antd pro中升级了@umijs/route-utils依旧没有解决，报错除了` Maximum call stack size exceeded`还有`he above error occurred in the <BaseProLayout> component`，但是我找不到具体错误在哪
