### ISSUE TITLE
🐛[BUG] ant-design-proV5 开启qiankun报错

### ISSUE THREAD

**Issue by knight-peter** [ant-design/ant-design-pro#9308]
### 🐛 bug 描述
ant-design-proV5 开启qiankun，无法正常使用

### 📷 复现步骤
1. 下载https://github.com/ant-design/ant-design-pro/releases/tag/v5.0.0
2.  安装 `tyarn add @umijs/plugin-qiankun -D`
3. `config/config.ts` 增加配置

```
qiankun: {
    master: {
      // 注册子应用信息
      apps: [
        {
          name: 'system-app1', // 唯一 id
          entry: '//localhost:10020', // html entry
        },
      ],
    },
  },
```
4. loading无法正常关闭，微前端没起作用。

### 🏞 期望结果

希望像直接使用umi框架那样，开启qiankun,不会报错。

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 [3.5.20]
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/3077802/141891719-6dcf828e-ba4c-44e6-8d28-0cbe8b75ee5e.png)

**Comment by YC725968** [comment]
同理。开启微前端报错，进入页面会出现两个页面

**Comment by nekic** [comment]
俺也一样

**Comment by milk-hall** [comment]
开启qiankun了以后，会渲染到root-master这个节点上，需要手动在umi的config里面配置`mountElementId:"root"`，或者修改document.ejs的id

**Comment by milk-hall** [comment]
> 同理。开启微前端报错，进入页面会出现两个页面

开启qiankun了以后，会渲染到root-master这个节点上，需要手动在umi的config里面配置`mountElementId:"root"`，或者修改document.ejs的id
