### ISSUE TITLE
如何设置 浏览器地址栏访问后端接口不跳到404页面

### ISSUE THREAD

**Issue by codercatmomi** [ant-design/ant-design-pro#931]
例子：我浏览器地址栏 直接访问后端接
http://xx.xx.com/pro/index/download
会自动跳到404页面；

如何能不跳到404，而是访问接口？

**Comment by dengfuping** [comment]
@codercatmomi 接口地址如果能匹配上应该不会有这个问题。能否贴一下代码？

**Comment by chenshuai2144** [comment]
定义成post接口

**Comment by dengfuping** [comment]
@codercatmomi 有可能像 @chenshuai2144 说的，你定义成了 post 接口。浏览器访问默认是 get 请求。

**Comment by codercatmomi** [comment]
嗯确实是 @chenshuai2144  的原因
感谢回复
