### ISSUE TITLE
treeSelect 低版本怎么可以做到 多选 时 筛选 不清除 input值。

### ISSUE THREAD

**Issue by 521guyu** [ant-design/ant-design-pro#9310]
### 🧐 问题描述
treeSelect 低版本怎么可以做到 多选 时 筛选 不清除 input值 ，3.7.0 新增了一个autoClearSearchValue 属性 可以做到 ，但如果无法升级新版本的情况下，怎么做到类似的效果？

treeSelect 低版本怎么可以做到 多选 时 筛选 不清除 input值 ，3.7.0 新增了一个autoClearSearchValue 属性 可以做到 ，但如果无法升级新版本的情况下，怎么做到类似的效果？

**Comment by chenshuai2144** [comment]
这个好像不行，为啥不能升级呢？

**Comment by 521guyu** [comment]
> 这个好像不行，为啥不能升级呢？

老项目了，升级成本有些大。那有什么做法可以一个项目使用两个版本的ui库。

**Comment by chenshuai2144** [comment]
这个成本总要有人支付的。

> 那有什么做法可以一个项目使用两个版本的ui库。

不要给后来人挖坑

**Comment by 521guyu** [comment]
> 这个成本总要有人支付的。
> 
> > 那有什么做法可以一个项目使用两个版本的ui库。
> 
> 不要给后来人挖坑

那又没有 技术 可以实现 用两个不同版本的库，推荐一下，我去 看看

**Comment by chenshuai2144** [comment]
微前端
