### ISSUE TITLE
🐛[BUG]5.0版本输入错误导航路径，无法跳转404页面

### ISSUE THREAD

**Issue by joman-jiang** [ant-design/ant-design-pro#9314]
### 🐛 bug 描述
**错误的导航路径URL无法正确显示404页面，查询官方当前最新的demo也是一样的，但是历史版本是可以显示404页面的。**

### 📷 复现步骤
输入 地址 [http://127.0.0.1:8000/welcome3](http://127.0.0.1:8000/welcome3)
/welcome3是不存在的路由。
这时页面会一直处在加载中

### 🏞 期望结果
显示404页面

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [win10]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/9638899/142336348-1577685b-9847-4289-9801-4381538fdc5b.png)

**Comment by chenshuai2144** [comment]
已经修复，更新版本即可解决
