### ISSUE TITLE
ant-design    simple模式创建项目后出现部分样式错乱

### ISSUE THREAD

**Issue by EnoughLove** [ant-design/ant-design-pro#9317]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pro.ant.design/zh-CN/docs/getting-started](https://pro.ant.design/zh-CN/docs/getting-started)

### Steps to reproduce
按步骤安装即可看到

### What is expected?
样式不错乱

### What is actually happening?
样式错乱

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.0 |
| System | windows |
| Browser | 谷歌浏览器 |

**Comment by EnoughLove** [comment]
npm&nbsp; &nbsp;创建后就可看到&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月18日(星期四) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-pro] ant-design    simple模式创建项目后出现部分样式错乱 (Issue #9317)





 
Hello @EnoughLove. Please provide a online reproduction by forking this link https://codesandbox.io/ or a minimal GitHub repository.
 
你好 @EnoughLove, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。
 

 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by momtboy** [comment]
![image](https://user-images.githubusercontent.com/9612078/166421507-2bc979e8-975d-4635-ab67-ac3b5b4b94f3.png)![image](https://user-images.githubusercontent.com/9612078/166421571-ce262434-1e41-4490-bc8e-d83aa6df44c8.png)
遇到相同的问题啦

**Comment by 251205668** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> https://pro.ant.design/zh-CN/docs/getting-started
> 
> ### Steps to reproduce
> 按步骤安装即可看到
> 
> ### What is expected?
> 样式不错乱
> 
> ### What is actually happening?
> 样式错乱
> 
> Environment	Info
> antd	4.16.13
> React	17.0.0
> System	windows
> Browser	谷歌浏览器

一样的问题，关闭msfu就可以了，这应该是他们的一个bug

**Comment by chenshuai2144** [comment]
新版本的umi马上要发布了，发布之后就好了，大家先忍忍
