### ISSUE TITLE
🧐[问题] 后端接口设计疑问

### ISSUE THREAD

**Issue by qiangxinglin** [ant-design/ant-design-pro#9318]
### 🧐 问题描述
目前正在尝试spring boot做后端, 现有以下几个疑问 (可能超出前端范畴), 希望不吝赐教:
1. 按照[AntD Pro 网络请求](https://pro.ant.design/zh-CN/docs/request#统一接口规范)和[umi request doc](https://umijs.org/zh-CN/plugins/plugin-request), 是所有的response (正确&错误)都设计成这样么?
```
public class CommonResponse<T> {
    private boolean success; // 靠 success 来区分是 happy or sad ending
    private T data;
    private String errorCode, errorMessage;
    private int showType;
}
```

还是只有在错误时返回`ErrorResponse`,  然后在成功时返回一个纯粹的data?
```
public class ErrorResponse<T> {
    private boolean success = false;
    private T data;
    private String errorCode, errorMessage;
    private int showType;
}
```

2. 接上一个问题, 我个人理解是第一种做法, 即`CommonResponse`, 然后在前端中使用 `useRequest` 来提取 `data & error` 做进一步的逻辑显示, 但一个新的问题是: 当我想使用ProComponents时(考虑分页), [request](https://procomponents.ant.design/components/table/#request)的返回格式要求为
```
interface {
  success: boolean
  total: number
  data: T
}
```
然而`total`字段并不存在于`CommonResponse`中, 这是否意味着应该新建一个`CommonPageResponse`
```
public class CommonPageResponse <T> extends CommonResponse <T> {
  private int total;
}
```
还是放弃掉泛型的做法, 写一些很重复的dto, 诸如`XListResponse, YListResponse`

3. 在考虑错误时, 除了将约定好的错误码放在`errorCode`中, 是否应该同时修改Http status?

即: 假如发生未鉴权访问, response body 为
```
{
  success: false,
  errorCode: 自定义错误码,
  errorMessage: 自定义错误信息
}
```
是否应该同时修改status为 Http 401? 还是说正常返回一个 Http 200?

4. 这个问题并没那么重要但还是问一下... 在使用openapi产生文档的时候
```
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-ui</artifactId>
</dependency>
```
正确处理泛型的姿势?

我现在使用了泛型, 所以在Schemas中产生了很多CommonResponse开头的泛型Schema, 诸如`CommonResponseCurrentUser`, `CommonResponseLoginResult`等等, 我觉得这种看起来很怪...

**希望各位大大们能不吝赐教!**

**Comment by FrankSFLYS** [comment]
关于第三个问题，如果 Response 状态码不是 4XX 的话，在 umi-request 中走的还是正常的 then 路径，而不走 catch 路径，所以就需要自己根据 success 进行判断。所以用哪种就看需求了。

**Comment by qinrongjun** [comment]
目前也遇到了这个问题，请问有好的解决方案吗？

**Comment by chenshuai2144** [comment]
业务错误尽量都用200，不然错误处理会很麻烦。

http 默认的状态码太少了，实在是不好处理
