### ISSUE TITLE
真实的数据交互问题

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#932]
官方能否出一个关于pro真实的数据交互实例，主要是看到演示的页面数据都是死的，不知道怎么将真实数据渲染到页面上

**Comment by dengfuping** [comment]
@zhaxingaz 这个和请求后端的真实数据效果是一样的啊，具体的项目开发最好还是要懂得一些后端的知识。

**Comment by zhaxingaz** [comment]
我其实想知道的是拿到后台数据后的过程，我现在卡到models.js里面了，能否指点一下

**Comment by zhaxingaz** [comment]
比如说下面这个models
import { queryFakeList } from '../services/api';

export default {
  namespace: 'list',

  state: {
    list: [],
    loading: false,
  },

  effects: {
    *fetch({ payload }, { call, put }) {
      yield put({
        type: 'changeLoading',
        payload: true,
      });
      const response = yield call(queryFakeList, payload);
      yield put({
        type: 'queryList',
        payload: Array.isArray(response) ? response : [],
      });
      yield put({
        type: 'changeLoading',
        payload: false,
      });
    },
    *appendFetch({ payload }, { call, put }) {
      yield put({
        type: 'changeLoading',
        payload: true,
      });
      const response = yield call(queryFakeList, payload);
      yield put({
        type: 'appendList',
        payload: Array.isArray(response) ? response : [],
      });
      yield put({
        type: 'changeLoading',
        payload: false,
      });
    },
  },

  reducers: {
    queryList(state, action) {
      return {
        ...state,
        list: action.payload,
      };
    },
    appendList(state, action) {
      return {
        ...state,
        list: state.list.concat(action.payload),
      };
    },
    changeLoading(state, action) {
      return {
        ...state,
        loading: action.payload,
      };
    },
  },
};
当我拿到response以后，我不清楚后面怎么做

**Comment by dengfuping** [comment]
@zhaxingaz 难道 response 中的 data，然后更新到 state 中去，然后在组件中 connect，然后通过 this.props.xxx 引用就行。逻辑很清晰啊，还是说对 redux 或 dva 不熟？

**Comment by zhaxingaz** [comment]
刚开始接触，可能理解的不是很到位，谢谢回答了
