### ISSUE TITLE
🐛[BUG] ProFormDatePicker className 和 style 属性无效

### ISSUE THREAD

**Issue by lovehql** [ant-design/ant-design-pro#9320]
### 🐛 bug 描述
ProFormDatePicker className 和 style 属性无效

### 📷 复现步骤
width属性填写具体数字会生效，填写'100%'也会生效，但是JSX提示类型错误，因为width是number
![image](https://user-images.githubusercontent.com/19810110/142525460-2ed5f698-2f47-470d-afdd-a4d4011cf99a.png)

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本
- 浏览器环境 [Chrome]
- 开发环境 [Window 10]

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/19810110/142521287-20ab2e18-25a7-4d1f-86ce-9460a8a1dd86.png)

**Comment by chenshuai2144** [comment]
filedProps里面设置

外面的都是快捷方式

**Comment by lovehql** [comment]
谢谢！filedProps = {{ width: '100%' }}在手机端不生效，其他可以。
