### ISSUE TITLE
🐛[BUG]ProFormDigit 加了addOnAfter 属性之后， 下面的红色提示文字，会多出一个来，这是个bug 

### ISSUE THREAD

**Issue by rotd01** [ant-design/ant-design-pro#9321]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/29349504/142581616-f725fb35-04fe-4ec4-923e-21077d7fb9a4.png)

ProFormDigit 加了addOnAfter 属性之后， 下面的红色提示文字，会多出一个来，这是个bug
### 📷 复现步骤
![image](https://user-images.githubusercontent.com/29349504/142581816-1a9cb0ff-caa8-4acf-90be-33718b34ac36.png)

### 🏞 期望结果
去掉一个红色提示

### 💻 复现代码
<ProFormDigit fieldProps={{ precision: 2, maxLength: 8, min: 0 }} label="优惠券金额" rules={[ {
          required:true, message: '请输入优惠券金额'
        }  ]} addonAfter={<span>元</span>} name="limitedCollar" />

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
已经修复了。升级一下版本
