### ISSUE TITLE
<ProFormSelect/>选择表单，利用request请求回数据，但是属性名并不是label和value,表单无法正常显示🧐[问题]

### ISSUE THREAD

**Issue by linghuchong-123** [ant-design/ant-design-pro#9322]
### 🧐 问题描述

尝试用antd的fieldNames,但是提示没有这个属性，请问有什么好的方法解决这个问题，目前我是用的数组循环把对象的属性名给改了

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/67812417/142592343-1629b47c-0ff1-44d5-8e25-931d59545b7a.png)

![image](https://user-images.githubusercontent.com/67812417/142592221-1717ec73-5d14-4030-90c3-5afd7b571d51.png)

**Comment by xtcel** [comment]
fieldNames要写在fieldProps里面吧，我现在是在ProForm里面用Form.Item,Form.Item再放Select

**Comment by linghuchong-123** [comment]
> fieldNames要写在fieldProps里面吧，我现在是在ProForm里面用Form.Item,Form.Item再放Select

您现在用的是antd中的select组件还是antd Pro中的ProFormSelct组件

**Comment by chenshuai2144** [comment]
promise 可以用.then 遍历一下的

**Comment by yaoshenyang** [comment]
fieldProps把fieldNames括号包起来
