### ISSUE TITLE
🐛[BUG]V5版本的侧边栏点击一个菜单，其他菜单自动折叠的功能怎么实现？ 现在只能自定义menuRender吗

### ISSUE THREAD

**Issue by lizengjia** [ant-design/ant-design-pro#9325]
### 🐛 bug 描述

V5版本的侧边栏点击一个菜单，其他菜单自动折叠的功能怎么实现？ 现在只能自定义menuRender吗

**Comment by chenshuai2144** [comment]
看看menu的api，我记得是openKeys

**Comment by lizengjia** [comment]
@chenshuai2144  openKeys是在app.jsx里配的  但是app.jsx里没有办法更改openKeys的值
