### ISSUE TITLE
ProLayout 以插件的方式提供，怎么用xxxProvider将其包裹起来？? 🧐[问题]

### ISSUE THREAD

**Issue by wuxuejie** [ant-design/ant-design-pro#9326]
### 🧐 问题描述
4.0版本之前使用的ProLayout组建，所以我很方便的将Web3ReactProvider等Provider将其包裹起来，然后在任何位置使用对应的方法
### 💻 示例代码
v4.x：
`<Web3ReactProvider getLibrary={getLibrary}><ProLayout ...>XXX</ProLayout ></Web3ReactProvider>`
![image](https://user-images.githubusercontent.com/31883495/142789538-f46b134f-e429-4952-93d1-ce54aa34320d.png)

v5.x
`export const layout = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    ...
  }
}
`
![image](https://user-images.githubusercontent.com/31883495/142789662-46564af0-e5a0-41b9-ad3d-40749c5a7f06.png)

我应该怎么调整我的项目
### 🚑 其他信息
我尝试着在BasicLayout中使用Web3ReactProvider覆盖，但是header和其他组建里面无法使用
![image](https://user-images.githubusercontent.com/31883495/142789219-248c4d0a-ad27-402d-a76d-ba5b40b4d09f.png)

**Comment by chenshuai2144** [comment]
childrenRender 应该能解决你的问题
