### ISSUE TITLE
🧐[问题]不同的接口使用不同的域名, 应该如何配置

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#9327]
### 🧐 问题描述
在app.tsx中, 我所有接口都是一个域名的配置如图, 如果不同接口用不同域名应该这么配置? 
![955f99ed839ace9d92062ba24340508](https://user-images.githubusercontent.com/33146207/142789605-b6e086e7-d5d5-40c6-96b8-4e51e8d66f36.png)

**Comment by chenshuai2144** [comment]
手动写if吧，写个拦截器
