### ISSUE TITLE
🐛[BUG]求救，我的ProTable时间筛选器不能正常使用了！

### ISSUE THREAD

**Issue by yuan-ze** [ant-design/ant-design-pro#9333]
### 🐛 bug 描述
valueType设置为date,time,datetime,dateRange等时间类型的都不能正常使用了，其他类型正常

### 💻 复现代码

```
const MyComponent = () => {

  const columns = [
    {
      title: '创建时间',
      hideInTable: true,
      dataIndex: 'date_Range',
      valueType: 'dateRange',
      search: {
        transform: (value) => {
          return {
            start_date: value[0],
            end_date: value[1]
          }
        }
      },
    }
  ]

  return (
    <PageContainer>
      <ProTable
        columns={columns}
        request={myRequest}
      />
    </PageContainer>
  )
};
```
### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS] maxOS
  "name": "ant-design-pro",
  "version": "5.0.0",
    "@ant-design/charts": "^0.9.4",
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-card": "^1.15.3",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.3.7",
    "@antv/l7-maps": "^2.3.7",
    "@antv/l7-react": "^2.1.9",
    "@umijs/route-utils": "^1.0.36",
    "ahooks": "^2.0.0",
    "antd": "^4.14.0",

maxOS

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/53718020/143010363-fecbb63f-3938-48cc-99f3-36d78259cb6b.png)

**Comment by realoldroot** [comment]
我刚刚也遇到了这个问题，在我关了广告拦截插件，禁用cache之后，再刷新页面控件就正常显示了。

**Comment by yuan-ze** [comment]
看了应该是chorme的问题，彻底清理缓存就好了
