### ISSUE TITLE
动态路由 指向组件，与本来的项目引入冲突。直接报错了。不加  @  符号 没问题🧐[问题]

### ISSUE THREAD

**Issue by scepter0430** [ant-design/ant-design-pro#9335]
![1637725530](https://user-images.githubusercontent.com/63215136/143172042-b6b44e55-b92a-4352-a659-b2645ad28326.png)

**Comment by scepter0430** [comment]
上面的是动态引入组件，
下面是原有代码报错，倒是也能处理，但是我想清楚，问题出在哪里？

**Comment by chenshuai2144** [comment]
看看这个

https://juejin.cn/post/6899640414446780430

**Comment by chenshuai2144** [comment]
这种高级语法兼容性总是很奇葩
