### ISSUE TITLE
官方自带的组件主题，这个颜色在哪里加？  不引入其他插件的情况下,默认只有一种颜色   🧐[问题]

### ISSUE THREAD

**Issue by scepter0430** [ant-design/ant-design-pro#9336]
![image](https://user-images.githubusercontent.com/63215136/143172354-040d6cc3-ad4b-48bd-b7f0-82efed7f0a34.png)

**Comment by HQDragon** [comment]
![image](https://user-images.githubusercontent.com/15418465/144223678-74087cd5-c00f-48a2-9b09-edb29c4fd46e.png)
你可以点下面的按钮，把配置复制下来

**Comment by chenshuai2144** [comment]
[umi-plugin-theme](https://github.com/chenshuai2144/umi-plugin-antd-theme)

这个库，推荐不要用。等layout的新版本会更新方案

**Comment by DaiAnpeng** [comment]
> 
请问什么时候出新版本的在线主题切换方案，我看官方有说已经出了，但是就给了一个效果展示https://pro.ant.design/zh-CN/blog/dynamic-theme，找不到其他的信息

**Comment by DaiAnpeng** [comment]
> [umi-plugin-theme](https://github.com/chenshuai2144/umi-plugin-antd-theme)
> 
> 这个库，推荐不要用。等layout的新版本会更新方案

请问什么时候出新版本的在线主题切换方案，我看官方有说已经出了，但是就给了一个效果展示https://pro.ant.design/zh-CN/blog/dynamic-theme
找不到其他的信息

**Comment by changlin0501** [comment]
请问哪个时候layout会更新呢
