### ISSUE TITLE
咱们在运行时配置    request  设置里，可以直接使用  initialState 吗？ 在token 等信息传输，比较麻烦，声明变量或者 缓存🧐[问题]

### ISSUE THREAD

**Issue by scepter0430** [ant-design/ant-design-pro#9337]
![image](https://user-images.githubusercontent.com/63215136/143172564-936623b1-43ab-41e4-87a5-4179edc2efa9.png)

**Comment by jenawant** [comment]
Head里用到的鉴权信息，服务端返回后，加密后存储在sessionStorage里，当前会话关闭后自动销毁。我是这么处理的。

**Comment by chenshuai2144** [comment]
楼上正解
