### ISSUE TITLE
运行时动态路由的动态组件引入，动态更新，这个方案，不能够直接放到  getInitialState 里面吗？虽是网格业务，但是问一下整合的方案。🧐[问题]

### ISSUE THREAD

**Issue by scepter0430** [ant-design/ant-design-pro#9338]
![image](https://user-images.githubusercontent.com/63215136/143172663-5d465bd2-d516-40b3-8de2-ca942b702f8d.png)

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/advanced-menu

看这个
