### ISSUE TITLE
关于models.js里接收到response以后的处理问题

### ISSUE THREAD

**Issue by zhaxingaz** [ant-design/ant-design-pro#934]
import { queryFakeList } from '../services/api';

export default {
  namespace: 'list',

  state: {
    list: [],
    loading: false,
  },

  effects: {
    *fetch({ payload }, { call, put }) {
      yield put({
        type: 'changeLoading',
        payload: true,
      });
      **const response = yield call(queryFakeList, payload);**
      **yield put({
        type: 'queryList',
        payload: Array.isArray(response) ? response : [],
      });**
      yield put({
        type: 'changeLoading',
        payload: false,
      });
    },
    *appendFetch({ payload }, { call, put }) {
      yield put({
        type: 'changeLoading',
        payload: true,
      });
      const response = yield call(queryFakeList, payload);
      yield put({
        type: 'appendList',
        payload: Array.isArray(response) ? response : [],
      });
      yield put({
        type: 'changeLoading',
        payload: false,
      });
    },
  },

  reducers: {
    **queryList(state, action) {
      return {
        ...state,
        list: action.payload,
      };**
    },
    appendList(state, action) {
      return {
        ...state,
        list: state.list.concat(action.payload),
      };
    },
    changeLoading(state, action) {
      return {
        ...state,
        loading: action.payload,
      };
    },
  },
};
上面字体标粗的部分是不是处理数据部分？能否解释一下？

**Comment by dengfuping** [comment]
@zhaxingaz 以后同一个问题在原来的 `issue` 下回复，下次贴代码的话用 `markdown` 格式，注意贴关键代码，不要全贴上来。

**Comment by zhaxingaz** [comment]
sorry 我还以为问题关了就不再回复了，以后注意，谢谢指点

**Comment by dengfuping** [comment]
@zhaxingaz 关了之后如果确实是官方的问题，或者有讨论的价值，我们会重新 open 的。

**Comment by zhaxingaz** [comment]
ok
