### ISSUE TITLE
🐛[BUG] antd pro v5 更新依赖包后在jsx 中eslint 失效

### ISSUE THREAD

**Issue by Donlei** [ant-design/ant-design-pro#9343]
### 🐛 bug 描述

antd pro v5 更新依赖包后在jsx 中eslint 失效，vscode之前用的好好，有提示，更新依赖包后好像变成TS版本的校验了，所以在jsx中么有提示

### 📷 复现步骤
现在根本没有提示
![1637750680(1)](https://user-images.githubusercontent.com/24711571/143224097-c37b803e-912d-4697-808f-257b4581c477.jpg)

### 🏞 期望结果

 能够在jsx中有提示

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本 3.5.2
- 浏览器环境 chrome
- 开发环境 win 11

**Comment by chenshuai2144** [comment]
把tsconfig.json 删除掉就可以了。

**Comment by Donlei** [comment]
@chenshuai2144 大佬， 一开始用的 就是jsx版本 ，所以 没有tsconfig.json，这种情况还是 没有提示

**Comment by forzalianjunting** [comment]
遇到了同样的问题

**Comment by Jiangyidan** [comment]
遇到了同样的问题，请问如何解决

**Comment by PeachScript** [comment]
Umi 4 lint 配置默认没开 `no-unused-vars` 规则，手动在 eslintrc 里启用规则即可：https://eslint.org/docs/latest/rules/no-unused-vars#options
