### ISSUE TITLE
为什么项目 进入页面  直接渲染3次？   导致使用useCallback 报错  🐛[BUG]

### ISSUE THREAD

**Issue by scepter0430** [ant-design/ant-design-pro#9344]
![image](https://user-images.githubusercontent.com/63215136/143375203-0081b90f-acda-4811-951b-539b76b8f488.png)
![image](https://user-images.githubusercontent.com/63215136/143375274-c94a3f45-0b3a-4a2f-9bbe-7de422bc5b9c.png)

**Comment by chenshuai2144** [comment]
不要在非生命周期里面搞有副作用的事情。
每次 render 所有的数据都会被重置的
