### ISSUE TITLE
动态路由如何让登录页面单独显示，路由数据是从后端拿过来的，不是前端写死的。不要菜单

### ISSUE THREAD

**Issue by 15629040742** [ant-design/ant-design-pro#9346]
![image](https://user-images.githubusercontent.com/45229892/143380776-00a6123d-f62c-4234-b16b-b2b1b4a7dbda.png)
![image](https://user-images.githubusercontent.com/45229892/143380886-43c78141-388b-4a15-b9f8-03d67bbe13ff.png)

**Comment by neil-lei0921** [comment]
如果不要header和sider的话直接在路由里设置layout:false就行了
你要是需要header不要sider的话 设置layout: {hideMenu: true}即可
如图所示：
![image](https://user-images.githubusercontent.com/92282065/143550216-d30a8e27-5b6f-4c81-a844-26b5ea9144ac.png)

**Comment by 15629040742** [comment]
> 如果不要header和sider的话直接在路由里设置layout:false就行了 你要是需要header不要sider的话 设置layout: {hideMenu: true}即可 如图所示： ![图片](https://user-images.githubusercontent.com/92282065/143550216-d30a8e27-5b6f-4c81-a844-26b5ea9144ac.png)
路由是动态获取的，没有在config文件写路由配置文件，在配置文件如何写路由配置的话，动态获取的路由又失效了

**Comment by chenshuai2144** [comment]
动态获取的路由可以用 menuRender:false。

layout 的配置被废弃了不支持了
