### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by RJM1996** [ant-design/ant-design-pro#9347]
### 🧐 问题描述

app.jsx 中的 layout 里设置 menuRender 不生效

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33800707/143404926-666607d9-8ff3-4ccf-a760-8da733c293ef.png)

![image](https://user-images.githubusercontent.com/33800707/143405686-37585c61-b4da-4356-bd50-1d27ebc8c9f6.png)

menuRender 不就是自定义菜单吗？但是设置后并未生效。但是设置 menuItemRender 是可以生效的

**Comment by xbcc123** [comment]
然后还是没人解决
