### ISSUE TITLE
🧐[问题] app.jsx 中的 layout 里设置 menuRender 不生效

### ISSUE THREAD

**Issue by RJM1996** [ant-design/ant-design-pro#9348]
### 🧐 问题描述

app.jsx 中的 layout 里设置 menuRender 不生效
menuRender 不就是自定义菜单吗？但是设置后并未生效。但是设置 menuItemRender 是可以生效的

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33800707/143406353-03a0ca3b-371a-4752-8ef5-c5c9e1dfc8e4.png)
![image](https://user-images.githubusercontent.com/33800707/143406383-fca99367-6a1e-4874-b825-38ae2d5f5a98.png)

**Comment by volcanicll** [comment]
[https://github.com/ant-design/pro-components/blob/09de4986903b0ed320c70cf7d45a1c74609f2ed1/packages/layout/src/ProLayout.tsx#L300C26-L300C26 ](url)
