### ISSUE TITLE
🐛[BUG] umi history.push erases the page title

### ISSUE THREAD

**Issue by artemdumanov** [ant-design/ant-design-pro#9349]
Hi! Often I need to use histroy.push to change the route and I noticed that when I do that the HTML page title changes to the URL instead of the supposed to be. 

Example code

```
import { formatMessage, history } from 'umi'

history.push(`/courses/lessons/${lesson.id}`)
```

How the page title looks after the code was executed (localhost....)
![image](https://user-images.githubusercontent.com/14028216/143439581-616e14d9-9342-46b3-a978-3df820e21f62.png)

The page reload helps (Lesson details...)
![image](https://user-images.githubusercontent.com/14028216/143439633-5443ea65-2a68-4331-92bb-7a2780fc03ad.png)

In most such cases I cannot use "Link" component or "useHistory" because the code can be in the dispatch actions.

Libraries:
├─ umi@3.5.20
├─ antd@4.16.13
├─ @ant-design/colors@6.0.0
├─ @ant-design/icons-svg@4.2.1
├─ @ant-design/icons@4.7.0
├─ @ant-design/pro-cli@1.0.28
├─ @ant-design/pro-field@1.22.5
├─ @ant-design/pro-form@1.42.1
├─ @ant-design/pro-layout@5.0.19
├─ @ant-design/pro-provider@1.4.19
├─ @ant-design/pro-table@2.54.4
├─ @ant-design/pro-utils@1.24.6
├─ @ant-design/react-slick@0.28.4
├─ @antv/adjust@0.1.1
├─ @antv/attr@0.1.2
├─ @antv/component@0.3.9
├─ @antv/coord@0.1.0
├─ @antv/g@3.3.6
├─ @antv/g2@3.5.15
├─ @antv/gl-matrix@2.7.1
├─ @antv/scale@0.1.5
├─ @antv/util@1.3.1
├─ @types/invariant@2.2.35
├─ @umijs/plugin-antd@0.11.0
├─ @umijs/preset-ant-design-pro@1.3.3
├─ antd-img-crop@3.16.0
├─ antd-mobile@2.3.4

What I want is to get to know how can I use "history.push" and keep the HTML title valid

**Comment by artemdumanov** [comment]
So this happens only for dynamic routes. For example ```history.push(`/courses/lessons/${lessonId}`)``` would erase the HTML title but `history.push(`/courses`)` will keep the HTML title as expected.

**Comment by artemdumanov** [comment]
Ping @chenshuai2144 @afc163 @nikogu @ddcat1115 @yutingzhao1991 @kaoding @xiaohuoni  ping

**Comment by chenshuai2144** [comment]
You have to configure it in the route to find the title, if not you need to set it manually
