### ISSUE TITLE
如何在 request.js里 读取 fetch后的response.body

### ISSUE THREAD

**Issue by codercatmomi** [ant-design/ant-design-pro#935]
这个是request.js里 fetch后的 response
![qq 20180212232258](https://user-images.githubusercontent.com/8371019/36104133-1e4aa48e-104c-11e8-9304-d4b57cf83a9a.png)

显示 body 是 locked:true 的

如果我想 当  response.body.code == -99 时，跳到登录页，
就读不到这个code值。

请问如何 unlock 这个 body呢？

感谢

**Comment by chenshuai2144** [comment]
reques就是封装fetch.  
body 需要转化一下 我们默认请是一个 json 所以对它做了 json的转化。
https://github.com/ant-design/ant-design-pro/blob/38f1302ab5716336401c32d352f4c918e38b3514/src/utils/request.js#L74
你可以修改成 response.text()

**Comment by mitoriko** [comment]
这个问题其实问的是fetch的问题。。。
@codercatmomi 这个你在fetch返回前都不能获取数据流
但是你可以在then里return response.json()
然后再继续then里获取这个data
问题就是你不能再使用response.json()传递了

PS.或者你可以考虑把code写在header里。。。

**Comment by gucciwu** [comment]
@codercatmomi 
return fetch(url, newOptions)
    .then(checkStatus)
    .then((response) => {
      if (newOptions.method === 'DELETE' || response.status === 204) {
        return response.text();
      }
      return response.json();
    })
    .then((responseData) => {
      if ( responseData.code === '-99') {
        //redirect to home
      }
      return responseData;
    });
