### ISSUE TITLE
proxy中pathRewrite不生效

### ISSUE THREAD

**Issue by eandei-me** [ant-design/ant-design-pro#9350]
### 🧐 问题描述

proxy代理后端接口时，配置了pathRewrite，并未生效，请求路径没有被替换。后端接口使用postman调用正常。本地开发时不想走网关，所以想把地址替换。如下配置后不生效

### 💻 示例代码
```
export default {
  dev: {
    '/api/': {
      target: 'https://preview.pro.ant.design',
      changeOrigin: true,
      pathRewrite: {
        '^': '',
      },
    },
    '/zuul/': {
      target: 'http://127.0.0.1:8080',
      changeOrigin: true,
      pathRewrite: {
        '^/zuul/api-lcback': '',
      },
    },
  }
}
```

**Comment by chenshuai2144** [comment]
去看看正则的写法 你这个看起来有点看不懂

**Comment by eandei-me** [comment]
就是请求地址是http://127.0.0.1:8080/zuul/api-lcback/user的请求，本地要代理到http://127.0.0.1:8080/user，所以要把/zuul/api-lcback替换为空

**Comment by chenshuai2144** [comment]
https://segmentfault.com/q/1010000012607105

看看这篇里面写的很详细。包括正则怎么写
