### ISSUE TITLE
Ant Design Pro 在内容页面里 如何实现打开一个新的标签页或浏览器窗口完成页面跳转

### ISSUE THREAD

**Issue by lizhuo-code** [ant-design/ant-design-pro#9356]
如题，我发现 Ant Design Pro 中 按住 command + 导航菜单 可以打开一个新的浏览器标签实现页面跳转，而在内容页面里就只能在当前标签页中刷新实现跳转，我想实现在容页面中点击弹出一个新页面或新标签完成跳转，请问如何实现呢？

**Comment by chenshuai2144** [comment]
window.open 呢？

**Comment by lizhuo-code** [comment]
> window.open 呢？

在ant design pro里，内容页之间的跳转是这样的：“router.push(`/app-form/app-info?id=${record.id}`);”，怎样使用window.open呢？请指教，谢谢

**Comment by chenshuai2144** [comment]
```
//跳转
window.open(`/app-form/app-info?id=${record.id}`)

```
