### ISSUE TITLE
🐛[BUG]使用 cz-conventional-changelog 生成提交信息，重复运行 precommit

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design-pro#9357]
### 🐛 bug 描述

`npm scripts` 设置 `precommit` 不是会默认执行吗？`@umijs/yorkie` 中为什么要再次设置 `pre-commit` ？

![image](https://user-images.githubusercontent.com/5070722/143804909-476cb25e-9e0c-434c-86c0-68cca5341038.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
这个hooks是追加的，所以会存在这种问题，只用一个就好了。
