### ISSUE TITLE
关于混合模式菜单的折叠问题

### ISSUE THREAD

**Issue by zkteco-home** [ant-design/ant-design-pro#9359]
@chenshuai2144 ![image](https://user-images.githubusercontent.com/66519168/143808295-e1e0168e-d0eb-4d5b-a889-1b9a7addda34.png)

我的菜单使用mixed 模式，默认想全部展开，初次第一次左边菜单是展开的，但是如果操作了上面的其他主菜单后再回到刚才的那个主菜单，左边的菜单就成折叠模式了。不知道为什么不能一直展开？

**Comment by chenshuai2144** [comment]
mix模式不支持自动展开的。有一点数据计算的问题。如果急需可以手动设置下 defaultOpenKeys
