### ISSUE TITLE
🐛[BUG] V5.1中dockerfile镜像不兼容

### ISSUE THREAD

**Issue by HQDragon** [ant-design/ant-design-pro#9363]
### 🐛 bug 描述

dockerfile与dockerfile.env使用了各自最新的nodejs，但本项目无法在node17下完成启动 ，本质上是antd-pro目前与node17不兼容
ℹ Compiling Webpack
ant-design-pro_dev  | node:internal/crypto/hash:67
ant-design-pro_dev  |   this[kHandle] = new _Hash(algorithm, xofLen);
ant-design-pro_dev  |                   ^
ant-design-pro_dev  |
ant-design-pro_dev  | Error: error:0308010C:digital envelope routines::unsupported
![image](https://user-images.githubusercontent.com/15418465/143991810-00caf14d-1b0a-4978-8b5b-9cacad310b2c.png)

### 📷 复现步骤

git clone 
cd docker
docker compose -f docker-compose.dev.yml up

### 🏞 期望结果

正常启动开发docker服务

### © 版本信息

- Ant Design Pro 版本: 5.1.0
- umi 版本 ^3.5
- 浏览器环境
- 开发环境 [windows wsl2]

### 🚑 其他信息

将dockerfile的image修改为node:14可以运行。

**Comment by Re9iNee** [comment]
I have the same issue as well.

**Comment by chenshuai2144** [comment]
现在还是不能使用这个高级的node版本
