### ISSUE TITLE
🧐[问题] ProFormUploadButton 配合ModalForm 使用，无法阻止组件自动上传

### ISSUE THREAD

**Issue by Aixic-Love** [ant-design/ant-design-pro#9365]
### 🧐 问题描述

ProFormUploadButton 配合ModalForm 使用
我在添加文件的时候会自动向当前路径发送Post请求附带文件。
![image](https://user-images.githubusercontent.com/50495439/144187460-ab22bfdd-5860-44e1-81d4-2f7b603e004f.png)

但是我的预期不希望在添加图片的时候就上传。
我想在ModalForm触发onFinish的时候一起通过form表单上传。

但是我无法阻止ProFormUploadButton自动上传。
### 💻 示例代码

```
<ProFormUploadButton action={undefined}
                             name="upload"
                             label="Upload"
                             accept=".csv,.jpg"
                             max={1}
                             fieldProps={{
                               name: 'file',
                             }}

                             extra="上传数据文件 csv后缀"
                             rules={[
                               {
                                 required: true,
                                 message: '必填',
                               },
                             ]}
        >
```

**Comment by chenshuai2144** [comment]
用 filedProps 配置一下 action

**Comment by Aixic-Love** [comment]
设置成什么呢？求个demo呀

**Comment by chenshuai2144** [comment]
beforeUpload | 上传文件之前的钩子，参数为上传的文件，若返回 false 则停止上传。支持返回一个 Promise 对象，Promise 对象 reject 时则停止上传，resolve 时开始上传（ resolve 传入 File 或 Blob 对象则上传 resolve 传入对象）；也可以返回 Upload.LIST_IGNORE，此时列表中将不展示此文件。 注意：IE9 不支持该方法 | (file, fileList) => boolean \| Promise<File> \| Upload.LIST_IGNORE | -
-- | -- | -- | --

**Comment by Aixic-Love** [comment]
并没有这个action是什么原因？
![image](https://user-images.githubusercontent.com/50495439/148486690-de2d80f0-57db-4618-970b-397297aa0351.png)
我看源代码就没这个方法呀。。
![image](https://user-images.githubusercontent.com/50495439/148486741-7a27ce4b-a733-4564-84c7-e440f40ec465.png)
