### ISSUE TITLE
🐛[BUG]antd 更新到4.17.2 切换主题颜色失效，

### ISSUE THREAD

**Issue by CHENJKNB** [ant-design/ant-design-pro#9370]
### 🐛 bug 描述

antd 更新到4.17.2 切换主题颜色失效，但是暗黑主题下 切换颜色正常。
### 📷 复现步骤

antd 更新到4.17.2 切换主题颜色失效，但是暗黑主题下 切换颜色正常。

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.1.0]
- umi 版本 3.5.20
- 浏览器环境 谷歌 v96
- 开发环境 windows 10

### 🚑 其他信息

![开始](https://user-images.githubusercontent.com/18523983/144392436-b18210d4-5f96-4add-a7e2-3902c32c89de.gif)

**Comment by chenshuai2144** [comment]
需要新版本，请稍微等待一段时间。

**Comment by Gzbox** [comment]
> 需要新版本，请稍微等待一段时间。

新版本大概会在什么时间 推出呢？

**Comment by chenshuai2144** [comment]
已经发布了，可以试试了
