### ISSUE TITLE
app.js 调用全局getInitialState接口不实时刷新🧐[问题]

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/ant-design-pro#9371]
### 🧐 问题描述

app.js 调用全局getInitialState接口不实时刷新
![image](https://user-images.githubusercontent.com/52319042/144538002-8ce5943b-6ac0-48e8-a79e-ee89a3736abd.png)
这里面就是初始化的info接口 虽然时调用了 但是没有执行refresh函数的效果

请问这里全局调用的话怎么能实时更新数据呢，大佬们

**Comment by chenshuai2144** [comment]
这个东西不是给你调用的。你要调用 setInitialValues
