### ISSUE TITLE
ant design pro simple 登录页面样式显示不全🐛[BUG]

### ISSUE THREAD

**Issue by zFitness** [ant-design/ant-design-pro#9372]
### 🐛 bug 描述
我使用 whistle 代理了项目，发现样式显示不全, 不使用代理没有问题，使用代理发现 css 并没有缺少。
* 不使用代理
![image](https://user-images.githubusercontent.com/41500499/144590012-b99268b7-1311-4830-8568-2c8acbf89b36.png)
* 使用代理
![image](https://user-images.githubusercontent.com/41500499/144590056-b4375d63-50f5-4c4f-9378-9724d18b508d.png)
* 使用代理的css
![image](https://user-images.githubusercontent.com/41500499/144590226-3f7d2b64-de09-4ade-b118-4500e5582886.png)

**Comment by chenshuai2144** [comment]
估计是mfsu的问题，清空一下再打开一下

**Comment by jassonxian** [comment]
最后是怎么解决的
