### ISSUE TITLE
🐛[BUG]all-blocks 分支的代码与package.json依赖不匹配

### ISSUE THREAD

**Issue by LuoHuacheng** [ant-design/ant-design-pro#9374]
### 🐛 bug 描述

按文档使用npm或yarn create 项目之后运行 start 或者 dev 会报错, 截图如下:
![image](https://user-images.githubusercontent.com/14214871/144697552-cf92fa95-e8b3-4c98-b8e9-28468cb05b85.png)
![image](https://user-images.githubusercontent.com/14214871/144697977-4879794a-b1a1-495d-891e-794e65973459.png)

### 📷 复现步骤

使用npm 或 yarn create 新项目, 或者从仓库里克隆下来切换到 all-blocks 分支, 安装完依赖之后运行.

### 🏞 期望结果

代码内使用的依赖应该和package.json中的同步更新

### 💻 复现代码

![image](https://user-images.githubusercontent.com/14214871/144697671-8ddc0813-b8c1-4412-b86b-f9abfd221c0d.png)

### © 版本信息

- Ant Design Pro 版本: v5.0.0
- umi 版本 ^3.5.0
- 浏览器环境 Chrome/96.0.4664.55
- 开发环境 Intel Mac OS X 10_15_7

**Comment by chenshuai2144** [comment]
欢迎来个pr
