### ISSUE TITLE
🧐[问题] V5 路由设置access字段无效

### ISSUE THREAD

**Issue by JS-an** [ant-design/ant-design-pro#9375]
### 🧐 问题描述
当我设置路由的access字段为false时，侧边栏菜单不隐藏且地址栏可进入，无权限；

### 💻 示例代码
![image](https://user-images.githubusercontent.com/25688878/144703384-46a0dbb0-252d-4dbe-a927-b4d1bdaf2869.png)
![image](https://user-images.githubusercontent.com/25688878/144703418-baadaef0-9aff-44b0-a24f-f3b7cae544ac.png)
![image](https://user-images.githubusercontent.com/25688878/144704262-e47148c8-3fab-4f59-88f9-5349840ca142.png)

### 🚑 其他信息
debugger了一下,看到如下信息:

src\.umi\plugin-layout\Layout.tsx:
![image](https://user-images.githubusercontent.com/25688878/144703464-a28823bb-cd46-4f36-8ecd-c813e90b4d62.png)

src\.umi\plugin-layout\layout\layout\index.tsx:
![image](https://user-images.githubusercontent.com/25688878/144703482-8511ddcd-efdb-42e6-ad9f-52fbcfab7399.png)

src\.umi\plugin-access\AccessProvider.ts:
![image](https://user-images.githubusercontent.com/25688878/144703556-cc89e755-0a7a-495d-a73b-586abad5390d.png)
![image](https://user-images.githubusercontent.com/25688878/144703565-939edd5d-768b-4616-820a-7bb46475e352.png)

### 🌹 新进展
我是做了类似keep-alive的功能的，routes也是做了wrappers功能，引入了一个依赖”umi-plugin-keep-alive“；
当我删除这个依赖时权限功能就没问题了；

**Comment by Koomita** [comment]
救命恩人啊！！！！！！！

**Comment by buzhongbuyi** [comment]
没法兼容吗？

**Comment by chenshuai2144** [comment]
看起来是因为缓存了数据导致的，找下 umi-plugin-keep-alive 的作者适配一下吧

**Comment by JS-an** [comment]
umi-plugin-keep-alive 已修复, 可更新最新版本

**Comment by 15723185734** [comment]
同样的问题
