### ISSUE TITLE
🧐[问题]两秒就请求超时？设置timeout没有啥用啊，一直报504的错误

### ISSUE THREAD

**Issue by hongliang-hub** [ant-design/ant-design-pro#9377]
### 💻 示例代码

export async function getAllBanner(options?: { [key: string]: any }) {
  return request<API.RuleListItem>('/api/getAllBanner', {
    method: 'GET',
    timeout: 5000, // 超时时间
    ...(options || {}),
  });
}

**Comment by chenshuai2144** [comment]
timeout不只是前端的问题，504 是后端给你的。和前端没有关系的
