### ISSUE TITLE
ReferenceError: LocaleProvider is not defined

### ISSUE THREAD

**Issue by herrdu** [ant-design/ant-design-pro#938]
import { LocaleProvider, Spin } from 'antd'; 在编译后的代码中就没有了
1.roadhog 2.0+ 的配置
![image](https://user-images.githubusercontent.com/6762269/36133519-73f6f64a-10b9-11e8-8bf0-fd190e998ebf.png)
2.router.js 
![image](https://user-images.githubusercontent.com/6762269/36133550-b2083994-10b9-11e8-92b6-e96e9de628d7.png)

3. chrome 中devtool 的源码
![image](https://user-images.githubusercontent.com/6762269/36133561-cd20b364-10b9-11e8-9aa9-becf63a80faa.png)

我猜想是roadhog 配置的问题，但我是clone 的antpro 的源码，并没有做改动。
请问这里是哪里的配置有问题呢？

**Comment by yesmeck** [comment]
Duplicate of #936
