### ISSUE TITLE
动态菜单问题

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#9381]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/27960630/144804269-1f43f28b-d220-4af9-95cb-8a5092119445.png)
![image](https://user-images.githubusercontent.com/27960630/144804301-4201645e-b7be-4d0d-b798-0c3f14a3c126.png)
上面我已经吧路由配好了
![image](https://user-images.githubusercontent.com/27960630/144804447-297248cc-70b6-4e28-bbb2-da3f57347a71.png)
获取动态菜单
![image](https://user-images.githubusercontent.com/27960630/144804649-7e8f4a25-39c0-47eb-968d-6749f2f0dcd0.png)
菜单显示没什么问题 但是 菜单对应的内容显示的不对啊。菜单是动态的 路由不是动态的 但是 菜单对应的内容显示没有渲染
@chenshuai2144 
### 💻 示例代码
https://codesandbox.io/s/musing-noether-ytqik?file=/package.json

**Comment by chenshuai2144** [comment]
动态路由是无法实现的，建议路由菜单路径一对一
