### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by denglinyi7** [ant-design/ant-design-pro#9383]
### 🐛 bug 描述
1、本地环境启动后点击OpenAPI 文档
![1638786878(1)](https://user-images.githubusercontent.com/5925154/144831285-ee3289b7-b7f3-4068-89bc-574d9e856ef6.png)
2、错误页面
![1638786819(1)](https://user-images.githubusercontent.com/5925154/144831154-67eb87b2-5e0b-44fe-abdb-7081d9c84cc5.png)
### 📷 复现步骤
1、git clone
2、yarn
3、yarn start
4、admin用户登录
5、点击OpenAPI 文档菜单

### 🏞 期望结果
正常打开swagger-ui页面

### 💻 复现代码
![1638787434(1)](https://user-images.githubusercontent.com/5925154/144832634-03b6b420-30f9-44a9-93a1-3e8111be1b6f.png)
评估是useState参数设置有误
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本[3.5.0]
- 浏览器环境：Google Chrome[96.0.4664.45]
- 开发环境 [e.g. Windows]

**Comment by tangquanawj** [comment]
这个问题已经修复了么？ 为什么我这边还是有报错
