### ISSUE TITLE
🐛[BUG][BUG]本地环境--[菜单]OpenAPI 文档--Not Found /umi-plugins_undefined.json

### ISSUE THREAD

**Issue by denglinyi7** [ant-design/ant-design-pro#9384]
### 🐛 bug 描述
1、本地环境启动后点击OpenAPI 文档
![1638786878(1)](https://user-images.githubusercontent.com/5925154/144831285-ee3289b7-b7f3-4068-89bc-574d9e856ef6.png)
2、错误页面
![1638786819(1)](https://user-images.githubusercontent.com/5925154/144831154-67eb87b2-5e0b-44fe-abdb-7081d9c84cc5.png)
### 📷 复现步骤
1、git clone
2、yarn
3、yarn start
4、admin用户登录
5、点击OpenAPI 文档菜单

### 🏞 期望结果
正常打开swagger-ui页面

### 💻 复现代码
![1638787434(1)](https://user-images.githubusercontent.com/5925154/144832634-03b6b420-30f9-44a9-93a1-3e8111be1b6f.png)
评估是useState参数设置有误
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本[3.5.0]
- 浏览器环境：Google Chrome[96.0.4664.45]
- 开发环境 [e.g. Windows]

### 🚑 其他信息

**Comment by chenshuai2144** [comment]
你的openAPI没配地址吧

**Comment by denglinyi7** [comment]
> 你的openAPI没配地址吧

按照简单安装，默认未作处理，启动打开页面报错。

**Comment by chenshuai2144** [comment]
那就是某个老包了，更新一下依赖。

**Comment by chenshuai2144** [comment]
那就是某个老包了，更新一下依赖。

**Comment by jing2uo** [comment]
config/config.ts  文件，openapi 部分有两段，默认配置第一段 oneapi 没有 projectName, 参考 swagger 添加后正常。

`  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      projectName: 'oneapi',                                // 增加这一行
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],`
