### ISSUE TITLE
🧐[问题] ant design pro v5 版本，使用localStorage不生效问题

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#9386]
### 🧐 问题描述
我现在使用的是v5版本的，使用localStorage进行信息的存储，但是我发现localStorage无法存进去数据，我之前使用v4版本就是正常的

### 💻 示例代码
localStorage储存代码
/* 人工模拟缓存 */
export function setExpire(key, value, expire) {
  const obj = {
    data: value,
    time: Date.now(),
    expire
  };
  debugger
  localStorage.setItem(key, JSON.stringify(obj));
}

### 🚑 其他信息

登录前
![image](https://user-images.githubusercontent.com/29156872/144954872-8ef301fd-a71b-4c38-a9f4-e5982c9ef1a7.png)

登录调用
![image](https://user-images.githubusercontent.com/29156872/144955000-114d5878-8b85-457b-8b29-a2e7c87af1c5.png)

登录后
![image](https://user-images.githubusercontent.com/29156872/144954955-bdb72a9e-4958-4949-8bbc-c7e95fc99f8c.png)

**Comment by jmy1944311667** [comment]
> ### 以下的问题可能会帮助到你/以下问题可能对你有帮助
> * [ [Ant Design Pro V5 已经支持预览](https://github.com/ant-design/ant-design-pro/issues/6605)[ #6605](https://github.com/ant-design/ant-design-pro/issues/6605) ][Ant Design Pro V5 已经支持预览][80%][](https://github.com/ant-design/ant-design-pro/issues/6605)
> * [ [ant design 有什么企业级的pc端官网模板吗 非ant design pro哪个好](https://github.com/ant-design/ant-design-pro/issues/8976)[🧐[问题]  #8976](https://github.com/ant-design/ant-design-pro/issues/8976) ][ant design有没有企业级的pc端官网模板吗非ant design pro哪个好🧐[问题]][73%]
> * [ [ant design pro v4 怎么自定义动态主题](https://github.com/ant-design/ant-design-pro/issues/8482)[🧐[问题]  #8482](https://github.com/ant-design/ant-design-pro/issues/8482) ][ant design pro v4 怎么自定义动态主题🧐[问题]][71%]
> * [ [ant design pro 简单登录页面样式显示不全](https://github.com/ant-design/ant-design-pro/issues/9372)[🐛[BUG]  #9372](https://github.com/ant-design/ant-design-pro/issues/9372) ][ant design pro 简单登录页面样式显示不全🐛[BUG]][64%]
> * [ [Ant Design Pro 用户👨🏻‍💻👩🏻‍💻👨🏻‍💻👩🏻‍💻 ](https://github.com/ant-design/ant-design-pro/issues/99)[ #99](https://github.com/ant-design/ant-design-pro/issues/99) ][Ant Design Pro 用户👨🏻‍💻👩🏻‍💻👨🏻‍💻💩🏻‍💻][64%[](https://github.com/ant-design/ant-design-pro/issues/99)
> * [[🧐[问题]Ant Design Pro 如何对接公司的sso  #7763](https://github.com/ant-design/ant-design-pro/issues/7763) ][🧐[问题]Ant Design Pro 如何对接公司的sso][63%]
> * [[🐛[BUG]蚂蚁设计V5的权限管理访问，很重要，重新启动无法使用 #8886](https://github.com/ant-design/ant-design-pro/issues/8886) ][🐛[BUG]蚂蚁设计V5的权限管理访问，很重要，重新启动无法使用][62%]
> * [[🧐[问题] Ant Design Pro 表格某一列无需html转义 #9262](https://github.com/ant-design/ant-design-pro/issues/9262) ][🧐[问题] Ant Design Pro 表格某一列无需html转义][62%]
> * [ [Ant Design Pro 在内容页面里如何实现打开一个新的标签页或浏览器窗口完成页面跳转](https://github.com/ant-design/ant-design-pro/issues/9356)[ #9356](https://github.com/ant-design/ant-design-pro/issues/9356) ][Ant Design Pro 在内容页面里如何实现一个新的标签页或浏览器窗口完成页面跳转转][60%][](https://github.com/ant-design/ant-design-pro/issues/9356)
> * [[🧐[问题]ant design pro 如何根据理解直接构建页面 #9243](https://github.com/ant-design/ant-design-pro/issues/9243) ][🧐[问题]ant design pro 如何根据直接构建页面][60%]

这个对我没用

**Comment by chenshuai2144** [comment]
开了隐私模式？ 这是浏览器提供的API 框架不会去改的

**Comment by jmy1944311667** [comment]
> 开了隐私模式？ 这是浏览器提供的API 框架不会去改的

隐私模式？ 怎么关闭？ 我现在是刚拉取的代码，使用npx create-umi app命令获取的代码，我只是添加了一个localStorage的存储，其他的没改东西

**Comment by jmy1944311667** [comment]
> 开了隐私模式？ 这是浏览器提供的API 框架不会去改的

我刚刚发现，登录的时候localStorage会存信息，但是我在切换菜单的时候，localStorage自动清理了，不知道为什么？
