### ISSUE TITLE
🧐[问题] 通过url 直接进入的页面 和 通过点击菜单 进入的页面 渲染层级不一样是为啥?

### ISSUE THREAD

**Issue by lingting** [ant-design/ant-design-pro#9388]
### 🧐 问题描述
通过url 直接进入的页面 和 通过点击菜单 进入的页面 渲染层级不一样是为啥?

### 💻 示例代码
https://github.com/ballcat-projects/ballcat-ui-react
账号: lingting
密码: lingting
### 🚑 其他信息
layout 自定义使用的 ProLayout
下面两个图片可以明显看出渲染层级的差别
下图为通过在浏览器直接输入 url 进入的页面(或者在某个页面按f5刷新也会出现)
![image](https://user-images.githubusercontent.com/59352063/145044138-a864b9e8-210f-4c39-8b93-d213829b37e5.png)

下图为点击菜单进入的页面
![image](https://user-images.githubusercontent.com/59352063/145044359-d6e38135-2a1a-4890-988f-a2b9b3e1f3ba.png)

**Comment by chenshuai2144** [comment]
看起来是 antd 的config 同时存在了n份，这个会导致功能异常吗？
毕竟没有真实渲染dom

**Comment by lingting** [comment]
> 看起来是 antd 的config 同时存在了n份，这个会导致功能异常吗？ 毕竟没有真实渲染dom


目前是影响了页面缓存功能. 当切换到层级不一致的页面时.  所有其他层级页面的缓存会失效.
缓存用的是 react-activation 实现

**Comment by chenshuai2144** [comment]
去umi问问，应该是什么底层的锅
