### ISSUE TITLE
🧐[问题] ant design pro v5 的app.js里面，怎么使用useMemo去监听路由地址变化？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#9389]
### 🧐 问题描述
我在v4使用useMeno去监听路由变化，判断是否有权限已经是否登录，但是我现在换到v5版本了，继续使用给我报错了，现在v5怎么写可以监听到路由呢？

### 🚑 其他信息

v4使用useMeno截图
![image](https://user-images.githubusercontent.com/29156872/145136327-69baa798-f568-4ddf-982f-6211346f9848.png)

v5截图
![image](https://user-images.githubusercontent.com/29156872/145136514-6cb2ae73-835f-49cb-92bf-ea6433826f3c.png)
 
v5异常截图
![image](https://user-images.githubusercontent.com/29156872/145136543-b83d9284-499e-482a-b6ee-c1473b8c5e0b.png)

**Comment by jmy1944311667** [comment]
> ### 以下的 Issues 可能会帮助到你 / The following issues may help you
> * [[🧐[问题] ant design pro v5 版本，使用localStorage不生效问题 #9386](https://github.com/ant-design/ant-design-pro/issues/9386)][🧐[问题] ant design pro v5 版本，使用localStorage不生效问题][82%]
> * [[Ant Design Pro V5 已经支持预览 #6605](https://github.com/ant-design/ant-design-pro/issues/6605)][Ant Design Pro V5 已经支持预览][80%]
> * [[ant design有那种企业级的pc端官网模板吗 非ant design pro那种🧐[问题] #8976](https://github.com/ant-design/ant-design-pro/issues/8976)][ant design有那种企业级的pc端官网模板吗 非ant design pro那种🧐[问题]][73%]
> * [[ant design pro v4 怎么自定义动态主题🧐[问题] #8482](https://github.com/ant-design/ant-design-pro/issues/8482)][ant design pro v4 怎么自定义动态主题🧐[问题]][71%]
> * [[Ant Design Pro Users 👨🏻‍💻👩🏻‍💻👨🏻‍💻👩🏻‍💻 #99](https://github.com/ant-design/ant-design-pro/issues/99)][Ant Design Pro Users 👨🏻‍💻👩🏻‍💻👨🏻‍💻👩🏻‍💻][64%]
> * [[ant design pro simple 登录页面样式显示不全🐛[BUG] #9372](https://github.com/ant-design/ant-design-pro/issues/9372)][ant design pro simple 登录页面样式显示不全🐛[BUG]][64%]
> * [[🧐[问题]Ant Design Pro 如何对接公司的sso #7763](https://github.com/ant-design/ant-design-pro/issues/7763)][🧐[问题]Ant Design Pro 如何对接公司的sso][63%]
> * [[🐛[BUG] ant design V5 的权限管理access，经常不起重要，重新启动也没用 #8886](https://github.com/ant-design/ant-design-pro/issues/8886)][🐛[BUG] ant design V5 的权限管理access，经常不起重要，重新启动也没用][62%]
> * [[🧐[问题] Ant Design Pro 表格某一列不需要html转义 #9262](https://github.com/ant-design/ant-design-pro/issues/9262)][🧐[问题] Ant Design Pro 表格某一列不需要html转义][62%]
> * [[Ant Design Pro 在内容页面里 如何实现打开一个新的标签页或浏览器窗口完成页面跳转 #9356](https://github.com/ant-design/ant-design-pro/issues/9356)][Ant Design Pro 在内容页面里 如何实现打开一个新的标签页或浏览器窗口完成页面跳转][61%]
> * [[🧐[问题]ant design pro 如何根据路由直接构建静态页面 #9243](https://github.com/ant-design/ant-design-pro/issues/9243)][🧐[问题]ant design pro 如何根据路由直接构建静态页面][60%]

这个没办法帮到我

**Comment by chenshuai2144** [comment]
方法里面不能用的 hooks的。
用这个事件好了

| onPageChange | 页面切换时触发 | `(location: Location) => void` | - |
