### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by tttaotie** [ant-design/ant-design-pro#939]
我新建了一个页面，里面只有TimelineChart这个组件，并用chart/fetch异步请求了数据，但是会报TypeError: Cannot read property 'x' of undefined。打了log，好像是render的时机有问题，还没有获取到数据就render了，但是用MiniBar或者MiniArea这些组件都是获取数据之后才 render的，很奇怪，小白求大神们请教下～不胜感激！！！

**Comment by chenshuai2144** [comment]
Give an empty default value.
