### ISSUE TITLE
ant-design-pro 2中怎么使用speed-measure-webpack-plugin

### ISSUE THREAD

**Issue by superSheng11** [ant-design/ant-design-pro#9390]
### 🧐 问题描述
因为项目一直用的ant-design-pro 2，由于项目越来越大，打包编译现在很慢，想用speed-measure-webpack-plugin查看下具体哪些环节耗时，看到speed-measure-webpack-plugin插件需要包裹webpack配置才行，但是项目对webpack进行了二次封装。怎么解决这个问题呢？百度了好长时间也没有好的进展

**Comment by chenshuai2144** [comment]
在老代码上不断的做改进只会越来越难迁移，有功夫还是到最新版吧。
