### ISSUE TITLE
🧐[问题] v5 ProTable 操作列展示不完全

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#9391]
### 🧐 问题描述
我使用的是v5版本，在使用protable组件进行列表展示的时候，操作列展示的数据有部分缺失

### 🚑 其他信息

实际展示：
![image](https://user-images.githubusercontent.com/29156872/145159248-7ee3aa75-c238-432e-889d-d1bacc3917c7.png)

预计展示：
![image](https://user-images.githubusercontent.com/29156872/145159214-2552a819-0f17-496f-b3b8-b7d6a5e2e372.png)

**Comment by chenshuai2144** [comment]
一般是你设置的css的问题，检查一下

**Comment by jmy1944311667** [comment]
> css

我没有自己写css设置，都是组件默认的

**Comment by chenshuai2144** [comment]
width 或者 `overflow:hidden`

**Comment by jmy1944311667** [comment]
> overflow:hidden

这个什么意思？  我是个前端小白，不太懂
