### ISSUE TITLE
🧐[问题]config.ts 的 scripts 选项中怎么配置本地 js 文件

### ISSUE THREAD

**Issue by duandanyang** [ant-design/ant-design-pro#9392]
### 🧐 问题描述
>
config.ts 的 scripts 选项中怎么配置本地 js 文件。比如 ‘https://unpkg.com/@ant-design/charts@1.0.5/dist/charts.min.js’ 这个图表资源我想替换成本地导入，因为我的部署机器无法访问外网
>

### 💻 示例代码
> 比如 antd pro charts 静态文件导入在官方教程里是下面这样的，我想换成在本地导入应该怎么配置
  scripts: [
    'https://unpkg.com/react@17/umd/react.production.min.js',
    'https://unpkg.com/react-dom@17/umd/react-dom.production.min.js',
    'https://unpkg.com/@ant-design/charts@1.0.5/dist/charts.min.js',
    // 使用 组织架构图、流程图、资金流向图、缩进树图 才需要使用
    'https://unpkg.com/@ant-design/charts@1.0.5/dist/charts_g6.min.js',
  ],
>

**Comment by chenshuai2144** [comment]
放到public 文件夹里面，如果没有就新建。


然后 srcipts 里面配置 '/xxx.png'

**Comment by duandanyang** [comment]
按照你说的并不行啊，还是报错。
代码如下，这四个文件都是放在 public 下的
scripts: [
    '/react.production.min.js',
    '/react-dom.production.min.js',
    '/charts.min.js',
    '/charts_g6.min.js',
]
报错信息：
![image](https://user-images.githubusercontent.com/44666090/145513143-de177a07-ed98-406a-a5eb-28221d3d91ee.png)

**Comment by chenshuai2144** [comment]
看看加载顺序的问题

**Comment by duandanyang** [comment]
应该跟加载顺序无关，看 Source 那里是直接把路径直接渲染到 <script></script> 中了。把这个四个资源按相同顺序换成远程链接就没问题
![image](https://user-images.githubusercontent.com/44666090/145527720-d39fbf90-3d17-4752-bbd0-5690e2d8770a.png)

**Comment by chenshuai2144** [comment]
估计是判断方式不对，判断了http 开头才能加进去。。。

**Comment by Youmyin** [comment]
> 应该跟加载顺序无关，看 Sources 那里是直接把路径直接渲染到 <script></script> 中，而不是 src 属性上。把这个四个资源按相同顺序换成远程链接就没问题。感觉还是使用方式不对 ![image](https://user-images.githubusercontent.com/44666090/145527994-23910aeb-02bd-43ea-8210-ffcaba8f41e6.png) ![image](https://user-images.githubusercontent.com/44666090/145528252-97e788db-3dae-446c-b936-39480b1e583a.png)
遇到相似的问题，请问最后解决了吗？
