### ISSUE TITLE
🧐[问题]openapi 报错 reason: self signed certificate

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#9393]
如题：该如何处理？
 看到可以增加如下配置，但是项目定义里面没有这些配置
```
new https.Agent({
  rejectUnauthorized: false
})
```

**Comment by chenshuai2144** [comment]
报错详细一点。

**Comment by z-lionel** [comment]
> 报错详细一点。

UnhandledPromiseRejectionWarning: FetchError: request to https://ip:port/api-docs failed, reason: self signed certificate
应该用了https地址之后报错

**Comment by chenshuai2144** [comment]
有截图吗？我无法确定这是那个模块设置的

**Comment by z-lionel** [comment]
> 有截图吗？我无法确定这是那个模块设置的

![image](https://user-images.githubusercontent.com/37678805/145325624-240b25b6-89de-4161-ade9-360ba12ee400.png)

**Comment by chenshuai2144** [comment]
了解了，会尽快修复

**Comment by askurat** [comment]
Any update on this? I ran into the same issue.
