### ISSUE TITLE
🐛[BUG]动态二级菜单不高亮

### ISSUE THREAD

**Issue by yangbo960618** [ant-design/ant-design-pro#9395]
### 🐛 bug 描述
这是我的router.js文件
![image](https://user-images.githubusercontent.com/51116068/145356093-e1ffca71-f4f4-4501-bf68-8ab34dd20b89.png)

这是我从后台取回来的菜单数据
[
    {
        "name": {
            "key": null,
            "ref": null,
            "props": {
                "children": [
                    "guest-229 1",
                    " ",
                    {
                        "type": {
                            "displayName": "Avatar",
                            "defaultProps": {
                                "shape": "circle",
                                "size": "default"
                            }
                        },
                        "key": null,
                        "ref": null,
                        "props": {
                            "src": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAnklEQVRYw+3WwQ3DMAwDQG7VFbKVdrUX6AbKP2gNipYABxD95z1iyQE65+TChAtn4uKAIdU7HIMDfOOcBUTSwHnAcjYygZ+zkQt4Aw28HPjgK65rCojXB4F4/YgBO49+ADAooQGtngbUehLQ6ynAtj/6ErCEW7UALOXa/gUsaS7onTaqAfV3XtnKVKwaeBKoJlBNoJpANYFqAtVE55jcxKrB3515tRYAAAAASUVORK5CYII=",
                            "shape": "square",
                            "style": {
                                "backgroundColor": "#fff",
                                "width": "15px",
                                "height": "12px"
                            },
                            "size": "default"
                        },
                        "_owner": null,
                        "_store": {}
                    }
                ]
            },
            "_owner": null,
            "_store": {}
        },
        "path": "/ChatsOpen/view/61b18a92befa5a39a",
        "isLoading": true,
        "key": "rF4wHGwk8E6WZv4z6",
        "showBadge": false,
        "type": "ChatsOpen"
    },
    {
        "name": {
            "key": null,
            "ref": null,
            "props": {
                "children": [
                    "111111",
                    " ",
                    {
                        "type": {
                            "displayName": "Avatar",
                            "defaultProps": {
                                "shape": "circle",
                                "size": "default"
                            }
                        },
                        "key": null,
                        "ref": null,
                        "props": {
                            "src": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAnklEQVRYw+3WwQ3DMAwDQG7VFbKVdrUX6AbKP2gNipYABxD95z1iyQE65+TChAtn4uKAIdU7HIMDfOOcBUTSwHnAcjYygZ+zkQt4Aw28HPjgK65rCojXB4F4/YgBO49+ADAooQGtngbUehLQ6ynAtj/6ErCEW7UALOXa/gUsaS7onTaqAfV3XtnKVKwaeBKoJlBNoJpANYFqAtVE55jcxKrB3515tRYAAAAASUVORK5CYII=",
                            "shape": "square",
                            "style": {
                                "backgroundColor": "#fff",
                                "width": "15px",
                                "height": "12px"
                            },
                            "size": "default"
                        },
                        "_owner": null,
                        "_store": {}
                    }
                ]
            },
            "_owner": null,
            "_store": {}
        },
        "path": "/ChatsOpen/view/61ae79899591c9ee8",
        "isLoading": true,
        "key": "iTTWK4JTM9kt8RngD",
        "showBadge": false,
        "type": "ChatsOpen"
    },
    {
        "name": {
            "key": null,
            "ref": null,
            "props": {
                "children": [
                    "5  3",
                    " ",
                    {
                        "type": {
                            "displayName": "Avatar",
                            "defaultProps": {
                                "shape": "circle",
                                "size": "default"
                            }
                        },
                        "key": null,
                        "ref": null,
                        "props": {
                            "src": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAnklEQVRYw+3WwQ3DMAwDQG7VFbKVdrUX6AbKP2gNipYABxD95z1iyQE65+TChAtn4uKAIdU7HIMDfOOcBUTSwHnAcjYygZ+zkQt4Aw28HPjgK65rCojXB4F4/YgBO49+ADAooQGtngbUehLQ6ynAtj/6ErCEW7UALOXa/gUsaS7onTaqAfV3XtnKVKwaeBKoJlBNoJpANYFqAtVE55jcxKrB3515tRYAAAAASUVORK5CYII=",
                            "shape": "square",
                            "style": {
                                "backgroundColor": "#fff",
                                "width": "15px",
                                "height": "12px"
                            },
                            "size": "default"
                        },
                        "_owner": null,
                        "_store": {}
                    }
                ]
            },
            "_owner": null,
            "_store": {}
        },
        "path": "/ChatsOpen/view/61ae7958e0bf707e2",
        "isLoading": true,
        "key": "qxB5FHZtj2rYjbtqo",
        "showBadge": false,
        "type": "ChatsOpen"
    },
    {
        "name": {
            "key": null,
            "ref": null,
            "props": {
                "children": [
                    "yoyoYun",
                    " ",
                    {
                        "type": {
                            "displayName": "Avatar",
                            "defaultProps": {
                                "shape": "circle",
                                "size": "default"
                            }
                        },
                        "key": null,
                        "ref": null,
                        "props": {
                            "src": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAnklEQVRYw+3WwQ3DMAwDQG7VFbKVdrUX6AbKP2gNipYABxD95z1iyQE65+TChAtn4uKAIdU7HIMDfOOcBUTSwHnAcjYygZ+zkQt4Aw28HPjgK65rCojXB4F4/YgBO49+ADAooQGtngbUehLQ6ynAtj/6ErCEW7UALOXa/gUsaS7onTaqAfV3XtnKVKwaeBKoJlBNoJpANYFqAtVE55jcxKrB3515tRYAAAAASUVORK5CYII=",
                            "shape": "square",
                            "style": {
                                "backgroundColor": "#fff",
                                "width": "15px",
                                "height": "12px"
                            },
                            "size": "default"
                        },
                        "_owner": null,
                        "_store": {}
                    }
                ]
            },
            "_owner": null,
            "_store": {}
        },
        "path": "/ChatsOpen/view/61ac31bb518441e02",
        "isLoading": true,
        "key": "utMa6WCsPZKmx3uAi",
        "showBadge": false,
        "type": "ChatsOpen"
    },
    {
        "name": {
            "key": null,
            "ref": null,
            "props": {
                "children": [
                    "liaotian  li",
                    " ",
                    {
                        "type": {
                            "displayName": "Avatar",
                            "defaultProps": {
                                "shape": "circle",
                                "size": "default"
                            }
                        },
                        "key": null,
                        "ref": null,
                        "props": {
                            "src": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAnklEQVRYw+3WwQ3DMAwDQG7VFbKVdrUX6AbKP2gNipYABxD95z1iyQE65+TChAtn4uKAIdU7HIMDfOOcBUTSwHnAcjYygZ+zkQt4Aw28HPjgK65rCojXB4F4/YgBO49+ADAooQGtngbUehLQ6ynAtj/6ErCEW7UALOXa/gUsaS7onTaqAfV3XtnKVKwaeBKoJlBNoJpANYFqAtVE55jcxKrB3515tRYAAAAASUVORK5CYII=",
                            "shape": "square",
                            "style": {
                                "backgroundColor": "#fff",
                                "width": "15px",
                                "height": "12px"
                            },
                            "size": "default"
                        },
                        "_owner": null,
                        "_store": {}
                    }
                ]
            },
            "_owner": null,
            "_store": {}
        },
        "path": "/ChatsOpen/view/61a6763deab717a94",
        "isLoading": true,
        "key": "fHDtXYs47S2zB6Gju",
        "showBadge": false,
        "type": "ChatsOpen"
    }
]

被点击的菜单不高亮
![image](https://user-images.githubusercontent.com/51116068/145356591-389ede8c-af06-44be-bbb6-4cdfad3d9057.png)

**Comment by codedart2018** [comment]
检查自己从后台取出来的菜单，你是否有二次处理过，如果没有二次处理　parentKeys　它是不会高亮的。

**Comment by yangbo960618** [comment]
> 检查自己从后台取出来的菜单，你是否有二次处理过，如果没有二次处理　parentKeys　它是不会高亮的。

 我不要parent高亮 我需要的是子菜单高亮 就是我点击的那个

**Comment by codedart2018** [comment]
> 

那你就要检查你的key是否是路由地址，如果不是不会高亮的。
给你看下我二次处理
![image](https://user-images.githubusercontent.com/12706830/145532797-512f3ea6-67da-4633-be01-b1fe49878d02.png)

**Comment by 0xZzOrz** [comment]
遇到相同问题,动态获取的菜单，点击以后路由跳转了但是被点击的menu没有高亮
![image](https://user-images.githubusercontent.com/93694134/145540598-762da384-65bb-4d39-9dba-b10319413d7d.png)

**Comment by 0xZzOrz** [comment]
> 遇到相同问题,动态获取的菜单，点击以后路由跳转了但是被点击的menu没有高亮 ![image](https://user-images.githubusercontent.com/93694134/145540598-762da384-65bb-4d39-9dba-b10319413d7d.png)

![image](https://user-images.githubusercontent.com/93694134/145743136-bc428ae8-5e3b-406b-a0d3-edaf9631f380.png)

解决了把这段代码去掉就好了

**Comment by yangbo960618** [comment]
> > 
> 
> 那你就要检查你的key是否是路由地址，如果不是不会高亮的。 给你看下我二次处理 ![image](https://user-images.githubusercontent.com/12706830/145532797-512f3ea6-67da-4633-be01-b1fe49878d02.png)

我已经把key处理的和path一样，而且我发现我只有在router.js定义了key才能高亮，问题是key又不能像path一样:id以这样的形式接收动态接收

**Comment by codedart2018** [comment]
> 给你看下我的　http://dev.jibei.ycoto.cn/　admin qw123456

**Comment by 0xZzOrz** [comment]
> > 给你看下我的　http://dev.jibei.ycoto.cn/
> > admin qw123456

特别好 谢谢
