### ISSUE TITLE
🧐[问题] 怎么来看当前使用的antd pro版本是多少？

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9396]
### 🧐 问题描述

怎么来看当前使用的antd pro版本是多少？

**Comment by codedart2018** [comment]
package.json version

**Comment by jacktang** [comment]
> package.json version

这个不是当前项目的版本信息吗？建议提供更好的版本信息显示方法

**Comment by chenshuai2144** [comment]
package 是唯一的指示器。

**Comment by jacktang** [comment]
应该是我的问题没表达清楚。我想请教的是使用 `yarn create umi myapp` 脚手架生成的框架的antd pro的版本信息在哪里看？

@chenshuai2144 @codedart2018

**Comment by mahalo777** [comment]
same question
