### ISSUE TITLE
🧐[问题] 导航菜单右侧的多语言选择怎么去掉？

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9397]
### 🧐 问题描述

入下图右侧多语言选择怎么去掉?
<img width="226" alt="截屏2021-12-09 下午11 16 28" src="https://user-images.githubusercontent.com/44341/145423871-3419a15e-88c6-4d7b-a5e1-2292cd222424.png">

**Comment by codedart2018** [comment]
coponents/RightCotent 
把　
```
 <SelectLang className={styles.action} />
```
去掉即可
