### ISSUE TITLE
🐛[BUG]HeaderDropdown组件内换行报错

### ISSUE THREAD

**Issue by bluef1ash** [ant-design/ant-design-pro#9398]
### 🐛 bug 描述

src/components/RightContent/AvatarDropdown.tsx文件

`<HeaderDropdown overlay={menuHeaderDropdown}>
      <span className={`${styles.action} ${styles.account}`}>
        <Avatar size="small" className={styles.avatar} src={currentUser.avatar} alt="avatar" />
        <span className={`${styles.name} anticon`}>{currentUser.username}</span>
      </span>
    </HeaderDropdown>`

上述代码报错

![](https://codeantenna.com/image/https://img-blog.csdn.net/2018062816523259?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM4MDU0MjM5/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)

如果换成以下代码就正常

`<HeaderDropdown overlay={menuHeaderDropdown}><span className={`${styles.action} ${styles.account}`}><Avatar size="small" className={styles.avatar} src={currentUser.avatar} alt="avatar" /><span className={`${styles.name} anticon`}>{currentUser.username}</span></span></HeaderDropdown>`

使用了自动整理代码插件，editconfig是默认的

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. Windows 10]

**Comment by bluef1ash** [comment]
我找到报错原因了，我用的webstrom格式化后，在`</span></HeaderDropdown>`之间生成了`{' '}`，从而报错，请问有什么方法，不让webstrom不自动生成`{" "}`呢

**Comment by chenshuai2144** [comment]
这个好像是ts server 的原因，注意下就好了。
