### ISSUE TITLE
🐛[BUG][BUG]react-dev-inspector在v5版本下快捷键不生效

### ISSUE THREAD

**Issue by maqinghao** [ant-design/ant-design-pro#9400]
### 🐛 bug 描述
页面div元素有 react-dev-inspector的属性,但是快捷键不起作用

### 📷 复现步骤
正常启动项目,但是快捷键不起作用  command+shift+ctrl+c

### 🏞 期望结果
起作用

### © 版本信息

- Ant Design Pro 版本: v5
- umi 版本 3
- 浏览器环境 谷歌
- 开发环境 vscode

**Comment by drizzlesconsin** [comment]
### 贴一下为什么不生效

> 源码只是加上插件而已，并没有调用。

https://github.com/ant-design/ant-design-pro/blob/master/config/config.dev.ts#L5-L14=

还需要参照 [react-dev-inspector 插件的使用文档第一步](https://github.com/zthxxx/react-dev-inspector#1-add-inspector-react-component=) 在 [app.tsx 这里](https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L89=) 修改。

```tsx
// app.tsx
import { Fragment } from 'react';
import { Inspector } from 'react-dev-inspector';

const isDev = process.env.NODE_ENV === 'development';
const loginPath = '/user/login';
```
```diff
+ const InspectorWrapper = isDev ? Inspector : Fragment;

+ <InspectorWrapper keys={['control', 'shift', 'command', 'c']} disableLaunchEditor={false}>
  {children}
+ </InspectorWrapper>
```

最后控制台验证
```js
window.__REACT_DEV_INSPECTOR_TOGGLE__()
```

**Comment by drizzlesconsin** [comment]
参考 https://github.com/ant-design/ant-design-pro/issues/7873#issuecomment-1112210839 可以解决问题
