### ISSUE TITLE
🐛[BUG]顶右的主题设置设置按钮不见了

### ISSUE THREAD

**Issue by cshcsh** [ant-design/ant-design-pro#9403]
### 🐛 bug 描述

顶右的主题设置按钮不见了，见截图

### 📷 复现步骤

登录后，顶右的主题设置按钮不见了

### 🏞 期望结果

顶右的主题设置按钮显示

### 💻 复现代码

无

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本 
- 浏览器环境 谷歌
- 开发环境 [e.g. windows10  node.js v16.13.1]

### 🚑 其他信息

![1b20ea64a097c425d2e67003e219252](https://user-images.githubusercontent.com/33857892/145704686-24a6acd7-236a-4b81-b2d1-262fca73ab87.png)

**Comment by chenshuai2144** [comment]
这个功能挂掉了，正好在重新实现。
