### ISSUE TITLE
🧐[问题] ProLayout 折叠之后，左侧导航栏的 Tip 中的文字是蓝色，请问怎么改？

### ISSUE THREAD

**Issue by FrankSFLYS** [ant-design/ant-design-pro#9404]
### 🧐 问题描述

我在 `defaultSettings.ts` 中把 `primaryColor` 改成了蓝色，似乎是这个的影响，导致折叠之后，鼠标悬浮在导航上面，弹出的 Tip 文字是蓝色，该页面是当前页面时会变回白色。

由于蓝色+黑色辨识度有点低，所以请问怎么能把它全改成白色？

如下图所示，这是该页面不是当前页面时的情况：
![Snipaste_2021-12-12_14-05-20](https://user-images.githubusercontent.com/10843159/145706636-289b45ee-b42f-4b0a-b738-c1f1453cba75.png)

下图是点击跳转到该页面，悬浮文字变成白色：
![Snipaste_2021-12-12_17-02-02](https://user-images.githubusercontent.com/10843159/145706649-3b0232ef-f2d2-4171-96cd-56ee8213c30b.png)

### 💻 示例代码

这个问题是最近发现的，因为之前没怎么测试过这种情况。其他的设置好像没有动过，用的是 `create-umi` 。

这是 `defaultSettings.ts`，也没什么特别的：
```ts
const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  primaryColor: '#2f54eb', // 极客蓝
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: true,
  splitMenus: true,
  headerTheme: 'light',
  title: '',
  pwa: false,
  logo: '/logo.svg',
  iconfontUrl: '',
};
```

**Comment by FrankSFLYS** [comment]
看了一下 [Preview](https://preview.pro.ant.design/) 页面，只要打开了自动分割菜单，也会出现这样的情况，这个出现蓝色是因为它是一个链接，只不过 Preview 中颜色稍微浅一点，所以我的问题变成了怎么把这个 Tip 中的链接变成非链接形式。

**Comment by chenshuai2144** [comment]
是个bug 会和antd一起修

**Comment by chenshuai2144** [comment]
已经修复了
