### ISSUE TITLE
🧐[问题]fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to

### ISSUE THREAD

**Issue by GHTlinyu** [ant-design/ant-design-pro#9405]
### 🧐 问题描述
环境：
node版本14.17.5 
npm版本6.14.14
windows10

选择的是
1.ant-design-pro
2.simple
3.typescript

在npm install时出现：
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! cb() never called!

**Comment by chenshuai2144** [comment]
不要用最新版本的 npm 安装可能会有问题。试试 yarn 1.0
