### ISSUE TITLE
🐛[BUG]刚刚创建的项目只做了npm run i18n-remove，登录页div节点样式丢失

### ISSUE THREAD

**Issue by Iveon** [ant-design/ant-design-pro#9406]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21276534/145747385-2dbfcde4-655c-4c78-9bf5-84f8937ff057.png)

**Comment by Iveon** [comment]
控制台输出：
[MFSU] require('/Projects/node_modules/@umijs/preset-ui/lib/bubble') found in /Projects/ChengYa/src/.umi/um
i.ts, which will broken the MFSU prebuild match, please change to esm module import.

我在config中注释了mfsu: {},就可以了。

有什么更好的解决办法吗?

**Comment by Iveon** [comment]
package.json中：
 "name": "ant-design-pro",
  "version": "5.0.0",

使用yarn create umi myapp创建的
我克隆一个试试

**Comment by Iveon** [comment]
- Local:   http://localhost:8000 (copied to clipboard)
 - Network: http://192.168.1.197:8000
用Local地址访问正常，Network访问样式就没有。

**Comment by Iveon** [comment]
不能用yarn insatll得用npm install才可以

**Comment by Iveon** [comment]
> 控制台输出： [MFSU] require('/Projects/node_modules/@umijs/preset-ui/lib/bubble') found in /Projects/ChengYa/src/.umi/um i.ts, which will broken the MFSU prebuild match, please change to esm module import.
> 
> 我在config中注释了mfsu: {},就可以了。
> 
> 有什么更好的解决办法吗?

出现这个是因为安装了@umijs/preset-ui
2个人用了都link了package.json和node_modules

**Comment by Iveon** [comment]
> ### 🐛 bug 描述
> ### 📷 复现步骤
> ### 🏞 期望结果
> ### 💻 复现代码
> ### © 版本信息
> * Ant Design Pro 版本: [e.g. 4.0.0]
> * umi 版本
> * 浏览器环境
> * 开发环境 [e.g. mac OS]
> 
> ### 🚑 其他信息
> ![image](https://user-images.githubusercontent.com/21276534/145747385-2dbfcde4-655c-4c78-9bf5-84f8937ff057.png)

用npm install后就没有问题了

**Comment by chenshuai2144** [comment]
非常好的排查思路
