### ISSUE TITLE
如果配合antd pro router进行锚点的快速定位

### ISSUE THREAD

**Issue by 1998729** [ant-design/ant-design-pro#9407]
我发现本身如果在router里面的path中定义#xxx的行为会出现404的情况，我觉得一定是我的用法有问题，但是现在还确实有这个需求，需要进行根据左侧的菜单栏点击对应的menu，然后右侧进行锚点定位， 目前解决的方案是这样的， 看起来是行的通的， 期待大佬帮忙review及有更好的建议推荐；

# routers.ts
export default [
  {
    path: '/db#db',
    name: 'db1',
    icon: 'smile',
    redirect: '/db/',
  },

  {
    path: '/db',
    name: 'db333',
    icon: 'smile',
    component: './Welcome',
    hideInMenu: true,
  }
]

# app.tsx
const jumpToHash = () => {
    const hash = window.location.hash;
    if (hash) {
      // default 120
      scrollToElement('#deploy', { offset: -80 });
    }
  };

  useEffect(() => {
    jumpToHash();
  });

**Comment by chenshuai2144** [comment]
应该是个bug。默认应该忽略的

**Comment by chenshuai2144** [comment]
发现和 react-router 有关。没有办法无副作用的支持
