### ISSUE TITLE
🧐[问题] antd pro demo的背景水印是通过那个插件实现的？

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9409]
### 🧐 问题描述

Demo的背景水印是通过那个模块/插件来实现的？
https://preview.pro.ant.design/form/step-form?navTheme=light&primaryColor=%231890ff&layout=mix&fixSiderbar=true&title=Ant+Design+Pro

<img width="1244" alt="截屏2021-12-13 下午3 56 11" src="https://user-images.githubusercontent.com/44341/145773616-30d233d4-7d7a-4a07-9eb9-96fa2ce91df5.png">

**Comment by chenshuai2144** [comment]
waterMarkProps | 配置水印，水印是 PageContainer 的功能，layout 只是透传给 PageContainer | WaterMarkProps
-- | -- | --
