### ISSUE TITLE
更新了？

### ISSUE THREAD

**Issue by imhxc** [ant-design/ant-design-pro#941]

**Comment by chenshuai2144** [comment]
请自行查阅文档

**Comment by imhxc** [comment]
就是走的文档
![](http://oscyun0zw.bkt.clouddn.com/QQ20180213-190036@2x.png)

**Comment by imhxc** [comment]
已经删掉重新下载了3遍了。使用的pro new 命令
![](http://oscyun0zw.bkt.clouddn.com/QQ20180213-190036@2x.png)
