### ISSUE TITLE
🧐[问题]  image组件的preview填入img的属性不生效 是因为版本的问题吗

### ISSUE THREAD

**Issue by KIngCrzy** [ant-design/ant-design-pro#9410]
### 🧐 问题描述

image组件的preview填入img的属性不生效，以及如果需要针对不同图片配置不同的宽高，除了每个image都配置preview属性，还有其他办法吗，用:global会导致所有图片的preview都同一个尺寸。

### 💻 示例代码

<Image preview={{ width: xxx}}>

**Comment by KIngCrzy** [comment]
antd v4.10

**Comment by chenshuai2144** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/8186664/145929047-09bda7fd-a922-4d08-a7fa-d71f2838cf27.png">


文档里好像不支持这个属性。

**Comment by KIngCrzy** [comment]
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/8186664/145929047-09bda7fd-a922-4d08-a7fa-d71f2838cf27.png">
> 
> https://ant.design/components/image-cn/ 文档里好像不支持这个属性。

我看到其他属性见<img>  img里面有宽高的属性 不是这个意思吗？

**Comment by chenshuai2144** [comment]
你用dom的写法，width:"200px" 这样的。不行的话看看源码怎么透出的

**Comment by KIngCrzy** [comment]
> 你用dom的写法，width:"200px" 这样的。不行的话看看源码怎么透出的
dom写法试过还是不行 好的 请问有办法批量控制preview的图片的宽高吗 每个image单独设置preview也不是可行的方案

**Comment by chenshuai2144** [comment]
去 antd 问问吧，我没使用过这个组件。
