### ISSUE TITLE
🧐[问题] 这个loading如何去除

### ISSUE THREAD

**Issue by metaatom** [ant-design/ant-design-pro#9412]
### 🧐 问题描述

这个loading如何去除

### 🚑 其他信息

<img width="920" alt="WX20211213-224125@2x" src="https://user-images.githubusercontent.com/93690389/145835119-93992ba4-2500-4e0b-a901-c6b551173a08.png">

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/title-landing

看这个

**Comment by metaatom** [comment]
> https://pro.ant.design/zh-CN/docs/title-landing
> 
> 看这个

路由切换时空白的加载页面能去掉不

**Comment by chenshuai2144** [comment]
给个 空字符串就去掉了

**Comment by marlti7** [comment]
> 给个 空字符串就去掉了

不行 不能设置成空字符串 
ValidationError: "loading" is not allowed to be empty
