### ISSUE TITLE
🧐[问题]defaultSettings.ts 里面是无法使用REACT_APP_ENV这种环境变量进行判断吗，声明了会拿不到，不声明运行就会报错

### ISSUE THREAD

**Issue by OnePieceLiu** [ant-design/ant-design-pro#9413]
### 🧐 问题描述
defaultSettings.ts 里面是无法使用REACT_APP_ENV这种环境变量进行判断吗，声明了会拿不到，不声明运行就会报错

### 💻 示例代码

import { Settings as ProSettings } from '@ant-design/pro-layout';

type DefaultSettings = ProSettings & {
  pwa: boolean;
};

// const { REACT_APP_ENV } = process.env;
// console.log(REACT_APP_ENV, '11111');

const proSettings: any = {
  navTheme: 'dark',
  primaryColor: '#0CBF53',
  layout: 'top',
  contentWidth: 'Fixed',
  fixedHeader: false,
  fixSiderbar: true,
  title: 'BCTS',

  // title:
  //   REACT_APP_ENV === 'production' ? 'BCTS' : `BCTS-QA`,
  pwa: false,
  iconfontUrl: '',
  splitMenus: false,
};

export type { DefaultSettings };

**Comment by chenshuai2144** [comment]
defaultSettings.ts 既要在node中使用也要在浏览器中使用。你再app.ts 里面的layout 里面配置吧

**Comment by OnePieceLiu** [comment]
> 

兄弟哪个app.ts ，我并没有找到你说这个文件配置layout

**Comment by OnePieceLiu** [comment]
> defaultSettings.ts 既要在node中使用也要在浏览器中使用。你再app.ts 里面的layout 里面配置吧

兄弟哪个app.ts ，我并没有找到你说这个文件配置layout

**Comment by chenshuai2144** [comment]
在src 下面，没有的话新建一个
