### ISSUE TITLE
🐛[BUG] 二级菜单的面包屑问题

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9414]
### 🧐 问题描述

有两个问题：

1）二级菜单 如图
<img width="485" alt="截屏2021-12-14 上午10 21 59" src="https://user-images.githubusercontent.com/44341/145921906-b8ec3c39-329f-4990-8509-6fd66f819224.png">
划线的一级菜单怎么自动跳转到默认的第一个菜单项？我看了路由配置并没有。我自己的程序只会到第一级菜单项。

2）在面包屑导航里怎么去重写默认的跳转行为。比如我想去掉最顶级菜单的连接。

**Comment by chenshuai2144** [comment]
pro 里面是通过redirect实现的
```
{
    path: '/',
    redirect: '/xxxx',
  },
```

这个操作面包屑的api
```tsx
breadcrumbRender: (routes) => {
          return [
            {
              breadcrumbName: '财务经管',
              path: '/',
            },
            ...(routes || []),
          ];
        },
```

**Comment by jacktang** [comment]
> pro 里面是通过redirect实现的
> 
> ```
> {
>     path: '/',
>     redirect: '/xxxx',
>   },
> ```
你看这个`详细页`：https://preview.pro.ant.design/profile/advanced?navTheme=light&primaryColor=%231890ff&layout=mix&fixSiderbar=true&title=Ant+Design+Pro

他的配置是
```json
    {
      path: '/profile',
      name: 'profile',
      icon: 'profile',
      routes: [
        {
          name: 'basic',
          icon: 'smile',
          path: '/profile/basic',
          component: './profile/basic',
        },
        {
          name: 'advanced',
          icon: 'smile',
          path: '/profile/advanced',
          component: './profile/advanced',
        },
      ],
    },
```
没有redirect。

**Comment by jacktang** [comment]
@chenshuai2144 上面的问题能继续看下吗？没解决呀。。。

**Comment by chenshuai2144** [comment]
你找错代码位置了。。。是配置了的
