### ISSUE TITLE
🧐[问题]Cannot read properties of null (reading 'split')     at stripQueryStringAndHashFromPath

### ISSUE THREAD

**Issue by Iveon** [ant-design/ant-design-pro#9416]
### 🧐 问题描述

我就测试通过服务器获取菜单和权限控制，测试完了。删除了几个测试用的页面，然后就这样了。

用什么办法可以快速的定位问题的所在吗？

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/21276534/145928881-0d0fab6e-5d68-4a3b-a0b3-4039c81d7c32.png)

**Comment by chenshuai2144** [comment]
这个应该是底层库报错了，这种的最好的办法就是二分法了。
删掉一半的代码，如果还有问题，再删除一半你就能找到最后的问题了
