### ISSUE TITLE
🧐[问题] ant desigin pro V5(JavaScript版本) 使用 @react-pdf/renderer出现报错: Unhandled Rejection (TypeError): Cannot read properties of undefined

### ISSUE THREAD

**Issue by ScarecrowFu** [ant-design/ant-design-pro#9417]
### 🧐 问题描述

```
import { pdf } from '@react-pdf/renderer';
```

项目中需要使用到 [@react-pdf/renderer](https://github.com/diegomura/react-pdf)， 但只要 import 就会出现 `Unhandled Rejection` 错误。感觉是umi的问题，改用webpack开发是可以正常使用 [@react-pdf/renderer](https://github.com/diegomura/react-pdf)的。

### 💻 示例代码

```
import { pdf } from '@react-pdf/renderer';
```

[@react-pdf/renderer源代码 renderer/index.d.ts](https://github.com/diegomura/react-pdf/blob/master/packages/renderer/index.d.ts)

### 🚑 其他信息

谷歌浏览器错误：

```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'prototype')
▼ 19 stack frames were expanded.
__extends
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166189:200
(anonymous function)
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166202:5
(anonymous function)
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166331:5
./node_modules/restructure/src/EncodeStream.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166335:4
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
(anonymous function)
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:165759:26
./node_modules/restructure/index.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:165797:4
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
Module../node_modules/@react-pdf/fontkit/lib/fontkit.browser.es.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:790:69
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./node_modules/@react-pdf/font/lib/index.browser.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:418:15
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
Module../node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:73391:73
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
Module../src/.umi/.cache/.mfsu/mf-va_@react-pdf_renderer.js
http://localhost:8001/mf-dep_src_umi_cache_mfsu_mf-va__react-pdf_renderer_js.a7a2ecb5.async.js:50:77
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
(anonymous function)
http://localhost:8001/mf-va_remoteEntry.js:654:652
__webpack_require__.m.<computed>
webpack:/ant-design-pro/webpack/runtime/remotes loading:913
options.factory
webpack:/ant-design-pro/webpack/runtime/react refresh:6
▲ 19 stack frames were expanded.
__webpack_require__
http://localhost:8001/umi.js:6815:33
  6812 | /******/ 			var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  6813 | /******/ 			__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  6814 | /******/ 			module = execOptions.module;
> 6815 | /******/ 			execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
       |                    			          ^  6816 | /******/ 		} catch(e) {
  6817 | /******/ 			module.error = e;
  6818 | /******/ 			throw e;
```

火狐浏览器错误:

```
Unhandled Rejection (TypeError): parent is undefined
__extends
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166189:176
./node_modules/restructure/src/EncodeStream.js/</EncodeStream<
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166202:14
./node_modules/restructure/src/EncodeStream.js/<
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166331:5
./node_modules/restructure/src/EncodeStream.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:166335:4
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./node_modules/restructure/index.js/<
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:165759:26
./node_modules/restructure/index.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:165797:4
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./node_modules/@react-pdf/fontkit/lib/fontkit.browser.es.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:790:88
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./node_modules/@react-pdf/font/lib/index.browser.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:418:34
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
http://localhost:8001/mf-dep_vendors-node_modules_react-pdf_renderer_lib_react-pdf_browser_es_js.088d623c.async.js:73391:92
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./src/.umi/.cache/.mfsu/mf-va_@react-pdf_renderer.js
http://localhost:8001/mf-dep_src_umi_cache_mfsu_mf-va__react-pdf_renderer_js.a7a2ecb5.async.js:50:96
__webpack_require__
http://localhost:8001/mf-va_remoteEntry.js:23:42
./@react-pdf/renderer/</<
http://localhost:8001/mf-va_remoteEntry.js:654:652
__webpack_require__.f.remotes/</onFactory/__webpack_require__.m[id]
webpack:/ant-design-pro/webpack/runtime/remotes loading:913
options.factory
webpack:/ant-design-pro/webpack/runtime/react refresh:6
__webpack_require__
.ant-design-pro/webpack/bootstrap:24

  21 | 	var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  22 | 	__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  23 | 	module = execOptions.module;
> 24 | 	execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
     | ^  25 | } catch(e) {
  26 | 	module.error = e;
  27 | 	throw e;
```

**Comment by chenshuai2144** [comment]
把mfsu 关掉一下试试呢

**Comment by ScarecrowFu** [comment]
> 把mfsu 关掉一下试试呢

关闭 mfsu  以及 删除 .umi 缓存 依然是一样的错误呢

**Comment by ScarecrowFu** [comment]
` yarn create umi` 创建一个完整的版本，然后install @react-pdf/renderer ，什么都不改，只在 'login' 页面加入一句 `import { pdf } from '@react-pdf/renderer';`  就出现上述错误了，两者似乎有什么冲突

**Comment by chenshuai2144** [comment]
报错是什么？

**Comment by ScarecrowFu** [comment]
> 报错是什么？

一样的错误

![Uploading WeChat Screenshot_20211218235715.png…]()

**Comment by ScarecrowFu** [comment]
> 报错是什么？

一样的错误

![Uploading WeChat Screenshot_20211218235715.png…]()

**Comment by ScarecrowFu** [comment]
> 报错是什么？

一样的错误

![WeChat Screenshot_20211218235715](https://user-images.githubusercontent.com/10743090/146647475-a0e69326-0b31-4fe0-9547-5ff10ad585fb.png)

**Comment by chenshuai2144** [comment]
mfsu  关闭之后试试，这个报错都是 mfsu 打包的问题

**Comment by gaspire** [comment]
遇到同样的问题，关闭mfsu了，还是不行。
`[@umijs/runtime] load component failed TypeError: Cannot read properties of undefined (reading 'prototype')`

**Comment by chenshuai2144** [comment]
去umi 问一下，好像见过这个问题

**Comment by linpingchuan** [comment]
> 去umi 问一下，好像见过这个问题

I was able to fix it:

npm install assert browserify-zlib buffer process stream-browserify util
modify 'plugin.config.ts' (umijs chainWebpack config)
export default (config: any, { webpack }: { webpack: any }) => {

  // Set alias
  config.resolve.alias.set('process', 'process/browser');
  config.resolve.alias.set('stream', 'stream-browserify');
  config.resolve.alias.set('zlib', 'browserify-zlib');

  // Set plugin
  config.plugin('record').use(webpack.ProvidePlugin, [{
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
  }]);
};


also add in config.ts like this below.

`chainWebpack: (memo, { env, webpack, createCSSRule }) => {
    // Set alias
    memo.resolve.alias.set('process', 'process/browser');
    memo.resolve.alias.set('stream', 'stream-browserify');
    memo.resolve.alias.set('zlib', 'browserify-zlib');

    // Set plugin
    memo.plugin('record').use(webpack.ProvidePlugin, [
      {
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
      },
    ]);
  },`

**Comment by greenking19** [comment]
> > 去umi 问一下，好像见过这个问题
> 
> I was able to fix it:
> 
> npm install assert browserify-zlib buffer process stream-browserify util modify 'plugin.config.ts' (umijs chainWebpack config)
> 
> ```ts
> export default (config: any, { webpack }: { webpack: any }) => {
> 
>   // Set alias
>   config.resolve.alias.set('process', 'process/browser');
>   config.resolve.alias.set('stream', 'stream-browserify');
>   config.resolve.alias.set('zlib', 'browserify-zlib');
> 
>   // Set plugin
>   config.plugin('record').use(webpack.ProvidePlugin, [{
>         process: 'process/browser',
>         Buffer: ['buffer', 'Buffer'],
>   }]);
> };
> ```
> 
> also add in config.ts like this below.
> 
> ```ts
> chainWebpack: (memo, { env, webpack, createCSSRule }) => {
>     // Set alias
>     memo.resolve.alias.set('process', 'process/browser');
>     memo.resolve.alias.set('stream', 'stream-browserify');
>     memo.resolve.alias.set('zlib', 'browserify-zlib');
> 
>     // Set plugin
>     memo.plugin('record').use(webpack.ProvidePlugin, [
>       {
>         process: 'process/browser',
>         Buffer: ['buffer', 'Buffer'],
>       },
>     ]);
>   },
> ```

I use "umi@3.5.20", and I can't find the file "plugin.config.ts".
I added it in "config.ts" 
```typescript
chainWebpack: (memo, { env, webpack, createCSSRule }) => {
    // Set alias
    memo.resolve.alias.set('process', 'process/browser')
    memo.resolve.alias.set('stream', 'stream-browserify')
    memo.resolve.alias.set('zlib', 'browserify-zlib')
   // The command line can see the information printed and mome
    console.log('chainWepack')
    // Set plugin
    memo.plugin('record').use(webpack.ProvidePlugin, [
      {
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
      },
    ])
  },
```
but it didn't work. Still the same error

**Comment by greenking19** [comment]
> > 去umi 问一下，好像见过这个问题
> 
> I was able to fix it:
> 
> npm install assert browserify-zlib buffer process stream-browserify util modify 'plugin.config.ts' (umijs chainWebpack config)
> 
> ```ts
> export default (config: any, { webpack }: { webpack: any }) => {
> 
>   // Set alias
>   config.resolve.alias.set('process', 'process/browser');
>   config.resolve.alias.set('stream', 'stream-browserify');
>   config.resolve.alias.set('zlib', 'browserify-zlib');
> 
>   // Set plugin
>   config.plugin('record').use(webpack.ProvidePlugin, [{
>         process: 'process/browser',
>         Buffer: ['buffer', 'Buffer'],
>   }]);
> };
> ```
> 
> also add in config.ts like this below.
> 
> ```ts
> chainWebpack: (memo, { env, webpack, createCSSRule }) => {
>     // Set alias
>     memo.resolve.alias.set('process', 'process/browser');
>     memo.resolve.alias.set('stream', 'stream-browserify');
>     memo.resolve.alias.set('zlib', 'browserify-zlib');
> 
>     // Set plugin
>     memo.plugin('record').use(webpack.ProvidePlugin, [
>       {
>         process: 'process/browser',
>         Buffer: ['buffer', 'Buffer'],
>       },
>     ]);
>   },
> ```

Well, it's solved now. I just deleted all node_modules .umi.
thank you very much!🥲
