### ISSUE TITLE
更新了吗，为什么启动是这样的

### ISSUE THREAD

**Issue by imhxc** [ant-design/ant-design-pro#942]
就是走的文档,这是什么情况，已经删掉重新下载了3遍了。使用的pro new 命令。什么代码都没改动
![](http://oscyun0zw.bkt.clouddn.com/QQ20180213-190036@2x.png)

**Comment by chenshuai2144** [comment]
拷贝一份clone的配置？
这个应该是roadhog的配置问题

**Comment by imhxc** [comment]
已解决，是因为路径问题。pro new生成的默认文件如果拷贝到其他地方需要修改路径。
