### ISSUE TITLE
👑 [需求]请更新一下EditableProTable的文档，API和例子中的差距太大了。

### ISSUE THREAD

**Issue by Iveon** [ant-design/ant-design-pro#9420]
请更新一下EditableProTable的文档，API和例子中的差距太大了。

看的一头雾水，比如我在例子中看到expandable

        expandable={{
          defaultExpandAllRows: true,
        }}
看字面意思是默认展开所有行，可是貌似没有用。
文档里也没有相关的资料。
request属性也没有介绍，是EditableProTable可以使用ProTable的所有API吗？

**Comment by Iveon** [comment]
> 请更新一下EditableProTable的文档，API和例子中的差距太大了。
> 
> 看的一头雾水，比如我在例子中看到expandable
> 
> ```
>     expandable={{
>       defaultExpandAllRows: true,
>     }}
> ```
> 
> 看字面意思是默认展开所有行，可是貌似没有用。 文档里也没有相关的资料。 request属性也没有介绍，是EditableProTable可以使用ProTable的所有API吗？

看到了一行小字 别的 API 与 ProTable 相同。

**Comment by Iveon** [comment]
EditableProTable中editable是一个bool类型；
ProTable中是一个TableRowEditable
![image](https://user-images.githubusercontent.com/21276534/145960063-bcaf2522-9e3c-4ae6-b221-403872e395a3.png)

**Comment by chenshuai2144** [comment]
文档已更新
