### ISSUE TITLE
直接复制ant design pro完整模板到另外一个目录安装完依赖报找不到Module🧐[问题]

### ISSUE THREAD

**Issue by labike** [ant-design/ant-design-pro#9425]
### 🧐 问题描述

直接复制ant design pro完整模板到另外一个目录安装完依赖报找不到Module

### 💻 示例代码

![微信截图_20211215173333](https://user-images.githubusercontent.com/15871933/146160984-bf17b4f3-9e4f-49ec-901d-1b3a154ddf15.png)

**Comment by chenshuai2144** [comment]
关掉 mfsu 试试，这个应该是mfsu导致的 modlue 没找到
