### ISSUE TITLE
How to add custom component before header ?

### ISSUE THREAD

**Issue by onnyprima** [ant-design/ant-design-pro#9427]
how to add space before header ? HOC on prolayout not working

**Comment by chenshuai2144** [comment]
css over write？

**Comment by onnyprima** [comment]
want to add my component above logo or rightcontent hedaer espsecially above header SettingDrawer

**Comment by onnyprima** [comment]
<img width="1675" alt="Screen Shot 2022-01-03 at 11 12 13" src="https://user-images.githubusercontent.com/23044546/147899210-ba700ea5-ce0b-4d6e-a2fa-60680a8795d5.png">

how to add component above header

**Comment by chenshuai2144** [comment]
<html>
<body>


headerTitleRender | Custom header title method, works in mix mode | (logo,title,props)=>ReactNode | -
-- | -- | -- | --



</body>
</html>
