### ISSUE TITLE
🐛[BUG]antd-pro文档bug，点击某路由报错白屏

### ISSUE THREAD

**Issue by wang-cola** [ant-design/ant-design-pro#9429]
### 🐛 bug 描述

antd-pro文档报错，点击某个路由，页面白屏，100%必现

### 📷 复现步骤

![image](https://user-images.githubusercontent.com/21015798/146294769-7f3f79bb-d0af-46c9-a4b5-4c5f7b678c59.png)

### 🏞 期望结果

正常查看文档

### 💻 复现代码

![image](https://user-images.githubusercontent.com/21015798/146294805-7e1efdc1-25c8-4628-9c0e-1412bf7038ec.png)

### © 版本信息

antd-pro在线文档 https://procomponents.ant.design/components/layout/
- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
修复了，清空缓存重新刷新一下
