### ISSUE TITLE
Async call response from getAuthority

### ISSUE THREAD

**Issue by rafapetter** [ant-design/ant-design-pro#943]
On the utils/Authorized.js I want to get an async call response from getAuthority()

What's the recommended solution to handle it?

**Comment by chenshuai2144** [comment]
this ?
 https://github.com/ant-design/ant-design-pro/pull/879

**Comment by rafapetter** [comment]
Hi @chenshuai2144 , I've just tried the solution from @kamote but 2 things: 1) on every page refresh it loses the currentAuthority state, causing a redirect to user/login; and 2) I still can't see how I may use an async call on getAuthority(), isn't there a simple/better solution?

Thanks

**Comment by chenshuai2144** [comment]
add loading page. then reloadAuthorized
 https://github.com/ant-design/ant-design-pro/blob/fd9773f5c3ac1a6b561b8982a6c030e6ca7af327/src/utils/Authorized.js#L7

**Comment by rafapetter** [comment]
I'm sorry for insisting on, but it's still not clear. How do I add this loading page when I'm doing an async inside utils/Authorized? 

When defining the routes, I need to handle the Promises responses following this hierarchy: 

**router.js** > **utils/Authorized.js** > **components/Authorized** > **utils/authority.js** > **getAuthority()**

**Comment by chenshuai2144** [comment]
This is a complex requirement！
My idea is to add a loading interface.
Waiting for the permission to load after the authentication.

getAuthority is a synchronization method.
Give a default value then load successfully after reloadAuthorized.

hope I can help you.

**Comment by kamote** [comment]
@rafapetter Can you explain the issue on #879 ,on this PR currentAuthority is stored in store. Initially when store will be initialize it will pick current https://github.com/ant-design/ant-design-pro/pull/879/files#diff-1fdf421c05c1140f6d71444ea2b27638R20 from local storage.

Also `currentAuthority` is persisted during store subscribe so it will persist on a page reload https://github.com/ant-design/ant-design-pro/pull/879/files#diff-1fdf421c05c1140f6d71444ea2b27638R46

**Comment by kamote** [comment]
@rafapetter I've updated my PR `register.currentAuthority` is undefined on start and it replace `login.currentAuthority` on any store changes please give a try again.

**Comment by rafapetter** [comment]
@chenshuai2144 Ok, I've decided to check authentication on login and request/api calls, this way I can use the async process with no impact to the authorization's hierarchy. But I'll keep your second suggestion as a fallback plan. Thank you for the insights.

@kamote, unfortunately your solution differs from what I was looking for, which it was just a simple async during authorization. Although I agree with the currentAuthority behaviour change you have suggested, I won't shift to it now to avoid future collateral damages. As per the issue I was getting, I can't reproduce it now, but it was related to 2 things: 1) having the currentAuthority as undefined on start; and 2) the subscribe was setting the currentAuthority to the current value, but it would set back to undefined right after, which was causing it to lose state and redirect to the login page. With your latest update I think you got it fixed.

**Comment by chenshuai2144** [comment]
I'm fixing his pr problem

**Comment by rafapetter** [comment]
@jzoe good idea, I'll try that. Thanks ;-)

**Comment by LIPSong** [comment]
@jzoe Morning! If "authority" and "currentAuthority" are both Promise, could you find out some solution?
