### ISSUE TITLE
🧐[展示] 我来展示下我用ant做的后台。看到有问题欢迎给我个提醒。

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#9430]
![image](https://user-images.githubusercontent.com/12706830/146296414-4976fc77-cbf8-487f-bb58-517488b23505.png)

网址：http://dev.jibei.ycoto.cn
帐号：admin qw123456

没啥优点，欢迎指点缺点。

## 各位上来别删除我图片资源吧。图片资源我放在第三方的，删除了就没了。别的数据你们删除删除还无所谓，我本地有备份。

**Comment by ZengJun-cloud** [comment]
看着像是V4？

**Comment by codedart2018** [comment]
> 看着像是V4？

v5

**Comment by ZengJun-cloud** [comment]
> > 看着像是V4？
> 
> v5

我看上面的菜单缩进 还以为是v4呀

**Comment by 569202812** [comment]
总算看到例子了期待ing

**Comment by codedart2018** [comment]
> 

最近折腾前端去了，要折腾到订单入库才更新后台了

**Comment by fangqibin** [comment]
哪里可以看源码学习一下。你太牛逼了。等着你更新。

**Comment by codedart2018** [comment]
> 哪里可以看源码学习一下。你太牛逼了。等着你更新。

源码就不放出来。我也是菜鸡！

**Comment by fangqibin** [comment]
> > 哪里可以看源码学习一下。你太牛逼了。等着你更新。
> 
> 源码就不放出来。我也是菜鸡！

那你有什么心得也跟我们分享一下。或者有什么经验，怎么学习，怎么提高

**Comment by ZengJun-cloud** [comment]
顶部的面包屑怎么处理呀？

**Comment by codedart2018** [comment]
> 

headerContentRender　中　获取 breadcrumb 与 pathname做的二次处理

**Comment by xnng** [comment]
有几个页面样式有问题
![image](https://user-images.githubusercontent.com/38936252/146925177-2ebab418-c42e-4214-980d-233f2f0f03b0.png)

**Comment by codedart2018** [comment]
> 有几个页面样式有问题 ![image](https://user-images.githubusercontent.com/38936252/146925177-2ebab418-c42e-4214-980d-233f2f0f03b0.png)

这个我知道是，PageContainer组件header问题导致的。v4升级上来还有这个问题。先不管它！

**Comment by codedart2018** [comment]
> ![image](https://user-images.githubusercontent.com/12706830/146296414-4976fc77-cbf8-487f-bb58-517488b23505.png)
> 
> 网址：http://dev.jibei.ycoto.cn 帐号：admin qw123456
> 
> 没啥优点，欢迎指点缺点。

各位上来别删除我图片资源吧。图片资源我放在第三方的，删除了就没了。别的数据你们删除删除还无所谓，我本地有备份。

**Comment by ZengJun-cloud** [comment]
你的主题色修改正常吗？我这5.1版本有点问题

**Comment by codedart2018** [comment]
> 

我不改主题色

**Comment by scrapstation** [comment]
@codedart2018 
订单详情页面如何让侧边栏高亮的，小妹

**Comment by CarlKong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
