### ISSUE TITLE
🧐[问题]多次切换菜单，样式文件会有多份

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design-pro#9433]
### 🧐 问题描述

多次切换菜单，查看控制台

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/47104575/146317125-013d6cae-7022-4c61-a5c5-6eb26f91b447.png)

**Comment by chenshuai2144** [comment]
本地环境就不要纠结了。正式环境不会的。

**Comment by linxianxi** [comment]
> 本地环境就不要纠结了。正式环境不会的。
> 
> 原因是因为热更新会导致重复加载，但是css没有模块化的能力，导致一直被重复加载。

是 ant-design-pro 预览页面啊。https://preview.pro.ant.design/，这个是本地环境？

**Comment by chenshuai2144** [comment]
这个是异步加载导致的，如果觉得难受可以关掉异步加载

**Comment by linxianxi** [comment]
> 这个是异步加载导致的，如果觉得难受可以关掉异步加载

dynamicImport 关掉是么

**Comment by chenshuai2144** [comment]
是的。css 被打包了多份了
