### ISSUE TITLE
protable  查询按钮点击监测

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#9434]
表格页面需要埋点，点击查询按钮的时候，触发埋点
但是页面修改数据，启用，禁用都会使用 actionRef?.current?.reload();来刷新数据
在内置的查询方法中不好区分是点击了查询按钮还是修改数据修改成功之后的重新查询
这个应该怎么处理？

**Comment by chenshuai2144** [comment]
好像没什么好办法。不会你好像也没要区分。

你可以自己封装一个reload方法，在调用的时候手动传入不通的type来区分刷新类型。这样可以保证数据是准确的
