### ISSUE TITLE
🧐[问题]创建项目之后Eslint快速修复失效？？？:rocket: 

### ISSUE THREAD

**Issue by lkzwc** [ant-design/ant-design-pro#9436]
### 🧐 问题描述
创建项目之后，js下修改代码，eslint 无任何提示。npm uninstall eslint 之后才有提示

但是会出现这样的效果，自动导包失效
![image](https://user-images.githubusercontent.com/84896877/146333175-dea6a2c6-87d3-4655-92fc-0839cd84b182.png)
正常不应该是这样的吗？

![image](https://user-images.githubusercontent.com/84896877/146333333-f963aa9f-3604-4f23-851f-418c525b9091.png)

**Comment by lkzwc** [comment]
目前只有JS模版会有这样的问题 TS OK的  已测试。

**Comment by lkzwc** [comment]
目前只有JS模版会有这样的问题 TS OK的  已测试。

**Comment by lkzwc** [comment]
社区这没人吗

**Comment by chenshuai2144** [comment]
自动导入包是ts的功能。不是eslint的
