### ISSUE TITLE
prolayout  文档异常，滚动之后页面白屏

### ISSUE THREAD

**Issue by yongjiangliu** [ant-design/ant-design-pro#9437]
![image](https://user-images.githubusercontent.com/32414361/146333786-704ee779-cb7a-47c2-a0cb-ded4cfc15d9a.png)
![image](https://user-images.githubusercontent.com/32414361/146333863-cd49c8bd-1fcb-43ba-9f63-9461df6e0a9c.png)
![image](https://user-images.githubusercontent.com/32414361/146334205-02499564-16ce-4136-9d67-3a615a254df6.png)

**Comment by chenshuai2144** [comment]
修复了。ssr的问题，请下缓存
