### ISSUE TITLE
🧐[问题]v5开启了mfsu后，修改打包地址就会报错

### ISSUE THREAD

**Issue by ZengJun-cloud** [ant-design/ant-design-pro#9440]
### 🧐 问题描述

v5开启了mfsu后，修改打包地址就会报错

### 💻 示例代码

![image](https://user-images.githubusercontent.com/52198079/146389377-207d1314-8725-4439-a5ee-b22900cdfed9.png)

![image](https://user-images.githubusercontent.com/52198079/146389940-f6f9e1e7-b7a2-4914-8391-f8922f1c88b7.png)

@codedart2018  感觉应该要加一个生产环境的判断

**Comment by chenshuai2144** [comment]
mfsu的限制挺多的。 兼容性不是很好。有花活的尽量不要用

**Comment by codedart2018** [comment]
> 

formCascader 何时能把loding关闭啊

**Comment by codedart2018** [comment]
> formCascader 何时能把loding关闭啊



> mfsu的限制挺多的。 兼容性不是很好。有花活的尽量不要用

formCascader 何时能把loding关闭啊

**Comment by chenshuai2144** [comment]
写pr。pr必看

**Comment by codedart2018** [comment]
> 

在antproCompoents提有issue.

**Comment by chenshuai2144** [comment]
pr是你写好代码。我是为了白嫖你们的劳动力。

**Comment by codedart2018** [comment]
> 

我们提issue就是让你们pr，我们白嫖的。formCascader　如果在一个列表页面有用的话，且用了远程请求数据。常见在搜索栏上，本身有table然后还有cascader会满屏看到都是loading.
