### ISSUE TITLE
Duplicated menus for root url / 

### ISSUE THREAD

**Issue by Mayazure** [ant-design/ant-design-pro#9441]
I'm trying to build a site where the root url (i.e. '/') directs to a standalone home page rather than a layout with nested routes. 
Here I have a very simple route config:

```ts
// routes.ts
export default [
  {
    path: '/',
    name: 'home',
    icon: 'smile',
    component: './Home',
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    component: './404',
  },
];
```

And my pages folder:

![image](https://user-images.githubusercontent.com/17568266/146468987-25354a70-d6aa-4451-892d-700d5820d27f.png)

The above routes give me the following menu render:

<img width="481" alt="root1" src="https://user-images.githubusercontent.com/17568266/146468442-928e9843-2aa6-433e-acaf-a84d618c0533.PNG">

It works except that there are two 'Home' menus rendered on the header, the second of which is selected by default when entering the site. 

The first 'Home' menu directs to '/index.html', which is a strange url. I don't even understand where does this 'indx.html' come from.

<img width="527" alt="root2" src="https://user-images.githubusercontent.com/17568266/146468761-7d2c9696-9437-409b-8033-8df4829c1c54.PNG">

Am I missing something here? What is the correct way to config path and component for root url?

**Comment by Mayazure** [comment]
@chenshuai2144 Thanks. Please check this repo: https://github.com/Mayazure/demo-antdpro-rooturl

**Comment by chenshuai2144** [comment]
you can close exportStatic or set Router.exact = false。

```
 {
    path: '/',
    exact: false,
    name: 'home',
    icon: 'smile',
    component: './Home',
  }, 
```

**Comment by Mayazure** [comment]
> you can close exportStatic or set Router.exact = false。
> 
> ```
>  {
>     path: '/',
>     exact: false,
>     name: 'home',
>     icon: 'smile',
>     component: './Home',
>   }, 
> ```

@chenshuai2144 That does not solve the problem. With the root path's exact match set to false, all other path will be directed to the root component. Following is my routes and now both '/' and '/welcome' will be directed to './Home'. What I need is '/' directs to './Home' while '/welcome' directs to './Welcome'

// routes.ts
export default [
  {
    path: '/',
    name: 'home',
    icon: 'smile',
    exact: false,
    component: './Home',
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    component: './404',
  },
];

**Comment by chenshuai2144** [comment]
```
{
    path: '/',
    exact: false,
    name: 'home',
    icon: 'smile',
    component: './Home',
  },
```

放到最后
