### ISSUE TITLE
🧐[需要帮住]有个需求：需要将左边菜单栏做成这样

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/ant-design-pro#9443]
我做的：
![image](https://user-images.githubusercontent.com/38531906/146511883-2f88e2a3-623f-4079-a194-9dc28cf33ba0.png)
UI设计图：
![image](https://user-images.githubusercontent.com/38531906/146511956-d49a48b2-4739-49bc-914f-f78df1a7d13d.png)
* 现在有两个问题
 ** 1.怎么给左边菜单栏增加背景色或者背景图
 ** 2.怎么将菜单栏给做成居中放到一个框子里
急求大佬们指教！！！

**Comment by chenshuai2144** [comment]
天呐好丑啊。

你用css 魔改吧。css什么都能做。
