### ISSUE TITLE
👑 菜单左右分栏需求

### ISSUE THREAD

**Issue by tianlilong** [ant-design/ant-design-pro#9445]
### 🥰 需求描述

在较大的功能站点的时候，会出现一种尴尬的问题就是菜单下拉不完，所以就想到了分栏的设计，相信也不只我一个人有这个需求

### 🧐 解决方案

采用分栏的方式展现，左侧为大的功能点或者模块，点击右侧展示相对的子菜单，类似下图
不知官方有没有计划添加这个需求点，如果添加了真的就方便了很多
### 🚑 其他信息
<img width="241" alt="image" src="https://user-images.githubusercontent.com/24712729/146522798-00b2f2be-1d74-4684-b8d5-c56939024e4c.png">

**Comment by tianlilong** [comment]
@chenshuai2144 大佬，有时间的关注一下 谢谢

**Comment by chenshuai2144** [comment]
现在这种要通过嵌套才来实现

**Comment by tianlilong** [comment]
> 现在这种要通过嵌套才来实现

我明白，一般两种方式：使用子渲染的API去做，问题是使用起来很别扭而且样式不是很美观，另外一种方式是禁用默认布局自己自定义，但又回到了V4的方式，感觉退回去了。所以有什么更好的方案吗？或者官方会不会代实现这个需求？？

**Comment by chenshuai2144** [comment]
我和豆酱大佬商量过了。新版的menu看看要不要做

**Comment by tianlilong** [comment]
> 我和豆酱大佬商量过了。新版的menu看看要不要做

有排期吗 期待上线啊

**Comment by WuJiY** [comment]
> 豆酱大佬

豆酱大佬 是哪位

**Comment by tianlilong** [comment]
> > 豆酱大佬
> 
> 豆酱大佬 是哪位

估计要等好久了

**Comment by tianlilong** [comment]
> > 豆酱大佬
> 
> 豆酱大佬 是哪位

你是不是也有这样的需求

**Comment by WuJiY** [comment]
> > > 豆酱大佬
> > 
> > 
> > 豆酱大佬 是哪位
> 
> 你是不是也有这样的需求

是的

**Comment by tianlilong** [comment]
> > > > 豆酱大佬
> > > 
> > > 
> > > 豆酱大佬 是哪位
> > 
> > 
> > 你是不是也有这样的需求
> 
> 是的

等官方吧  我也在等  他们不知道有没有排期

**Comment by sicun-github** [comment]
一样需要这个

**Comment by chenshuai2144** [comment]
ProLayout  next 版本支持了。

https://next-procomponents.ant.design/components/layout#%E6%94%B6%E8%B5%B7%E6%97%B6%E5%B1%95%E7%A4%BA-title

**Comment by adymilk** [comment]
> https://next-procomponents.ant.design/components/layout#%E6%94%B6%E8%B5%B7%E6%97%B6%E5%B1%95%E7%A4%BA-title

我也是想要这样的
