### ISSUE TITLE
V5版本中怎么使用dva？还是有别的方式进行全局状态管理？？

### ISSUE THREAD

**Issue by resuper** [ant-design/ant-design-pro#9446]

**Comment by resuper** [comment]
尝试了下useModel，浏览器点刷新，数据就没了。
登录逻辑中setInitialState也一样，浏览器刷新数据就没，
源码中通过控制变量ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION返回一个静态的用户数据。
怎么全局共享用户信息？？用户前一秒登录了，然后刷新浏览器被打到了登录界面。。。求大佬教教我呜呜呜~~~
我就想有个全局共享一部分数据

**Comment by chenshuai2144** [comment]
什么库刷新浏览器都会消失的，如果想一直保存需要后端存入的数据库。

**Comment by resuper** [comment]
@chenshuai2144 收到，谢谢大佬指点，应该在后端使用cookie、session或者token机制来保存用户的登录信息
