### ISSUE TITLE
🧐[问题]ProFormDigit组件增加addonAfter在ProForm里面的样式问题

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#9447]
如下图所示，在proform的ProFormDigit增加后缀，后缀跑到布局外了
正常的两个是用InputNumber组件重写了，代码如下：
还有个问题，如果有些组件在ProForm.Item重写，能不能给这个组件加个width的属性，
这样就不用加个classname等于 "pro-field-md"，或者是有其它方法？

```
<ProForm.Item className="pro-field-md">
     <InputNumber />
</ProForm.Item>
```

组件版本如下：
 "antd": "^4.17.3"
"@ant-design/pro-form": "^1.18.3"

![image](https://user-images.githubusercontent.com/37678805/146697868-718738c2-20c2-434e-b38c-1967625641e0.png)

**Comment by chenshuai2144** [comment]
来个重现，我看看怎么修

**Comment by z-lionel** [comment]
> 来个重现，我看看怎么修

https://codesandbox.io/s/proform-ox2en?file=/src/App.tsx
看看可以打开不，代码再里面，我这边页面loading不出来

**Comment by hkklearn** [comment]
<ProFormDigit width="xs" name="duration" label="任务时长" fieldProps={{addonAfter:"分钟"}} initialValue={5}/>
![image](https://user-images.githubusercontent.com/14145196/185101752-910b6bef-20f3-4755-a1c3-3c7352e67e67.png)
还是有问题
