### ISSUE TITLE
🧐[问题]ProFormText的rules，min没有校验空格

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#9448]
如题，配置了min:4,但是输入4个空格也能通过，能否加上字符串为空的判断？

**Comment by z-lionel** [comment]
已经有不为空的校验了  { whitespace: true }

**Comment by z-lionel** [comment]
还是觉得设置了最小长度，能不能判断不为空，这样就不用多加个{ whitespace: true }

**Comment by chenshuai2144** [comment]
空格很多时候算字符串的，默认的行为无法修改了
