### ISSUE TITLE
使用chrome，会出现 post failed to load response data

### ISSUE THREAD

**Issue by cnhans** [ant-design/ant-design-pro#945]
使用chrome，会出现 post failed to load response data，然后就会导致第一次访问的时候，出现304跳转到http://xxx.com/? 切换了firefox浏览器后，此问题没有出现。

**Comment by chenshuai2144** [comment]
这个应该不是框架的问题。
chrome的安全策略比较严格。
是不是跨域之类的？

**Comment by cnhans** [comment]
跨域已经设置为
const defaultOptions = {
    /*credentials: 'include',*/
  };

这个没法截图，就是第一次登陆，加入了权限后，就会导致第一次使用ajax的时候，出现304跳转的http://xxx.com/?  使用了firefox后，没有出现这个问题，只有在登录成功，授予了authory的才会这样。
