### ISSUE TITLE
🧐[问题]如何去除列表EditableProTable，的内边距padding

### ISSUE THREAD

**Issue by linghuchong-123** [ant-design/ant-design-pro#9450]
### 🧐 问题描述

我想要去除左边的内边距，在浏览器的调试面板也找到了.ant-card-body的padding的原因，但是我没找到组件暴露的介绍可以让我设置这个padding，我看antd 中的Card组件有bodystyle属性，但是在protable中没有相应的属性

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/67812417/146738875-190020d0-8a5c-4770-bbac-0fe7c7e38529.png)

**Comment by linghuchong-123** [comment]
可以设置Protable的style的负margin属性来实现抵消padding

`

     <ProTable
       // tableStyle={
        // {
        // marginLeft: '-24px',
        // padding: 0,
        // overflow: 'hidden',
        // textOverflow: 'ellipsis',
        // whiteSpace: 'nowrap',
        // }
        // }
        style={{ width: 1050, marginLeft: '-24px' }}
      />
`

**Comment by ville-vv** [comment]
<ProTable
        cardProps={{
            bodyStyle: { padding: 0 }, // 直接设置 padding
        }}
>
</ProTable>
