### ISSUE TITLE
🧐[问题]  ant design pro 使用中发现一个不知道算不算bug的问题，关于不存在的菜单路由，进行展示的问题？

### ISSUE THREAD

**Issue by jmy1944311667** [ant-design/ant-design-pro#9455]
### 🧐 问题描述

首先我在ant 的预览网站(https://preview.pro.ant.design/dashboard/analysis) 也试过了，存在这个问题

问题：当路由为两级时，比如我的账户管理路由是/baseManager/account，当我地址栏输入的是/baseManage,这个因为不属于我系统的路由，所以会展现404页面，正常的。但是当我第二级路由有问题是，也就是我输入 /baseManager/00，这样的地址时，正常情况下应该还是给出的404页面，因为这个也不是属于我的路由地址，但是实际上显示的却是一个灰色的页面，什么内容都没有，这个发现不知道算不算一个bug，我也不能确定，其实这个影响不大

### 🚑 其他信息

一级路由有问题时，显示的页面
![image](https://user-images.githubusercontent.com/29156872/146755479-44ac9c9e-329f-4a11-976c-eb1c0b12a950.png)

二级路由有问题时，显示的页面
![image](https://user-images.githubusercontent.com/29156872/146755567-9c698e17-bceb-42fb-8a0e-28c89d2849ab.png)

**Comment by jmy1944311667** [comment]
> ### 以下的问题可能会帮助到你/以下问题可能对你有帮助
> * [[🧐[问题]Ant Design Pro 如何对接公司的sso  #7763](https://github.com/ant-design/ant-design-pro/issues/7763) ][🧐[问题]Ant Design Pro 如何对接公司的sso][78%]
> * [[🧐[问题] Ant Design Pro 表格某一列无需html转义 #9262](https://github.com/ant-design/ant-design-pro/issues/9262) ][🧐[问题] Ant Design Pro 表格某一列无需html转义][77%]
> * [[🧐[问题]ant design pro 如何根据理解直接构建页面 #9243](https://github.com/ant-design/ant-design-pro/issues/9243) ][🧐[问题]ant design pro 如何根据直接构建页面][76%]
> * [[获取Ant Design Pro V5模板后安装模块依赖报错](https://github.com/ant-design/ant-design-pro/issues/9176)[🐛[BUG]  #9176](https://github.com/ant-design/ant-design-pro/issues/9176) ][获取Ant Design Pro V5模板后安装模块依赖报错🐛[BUG]][68%]
> * [[🧐[问题] ant design pro v5 的app.js里面，怎么用usememo去监听地址变化？ #9389](https://github.com/ant-design/ant-design-pro/issues/9389) ][🧐[问题]ant design pro v5的app.js里面，怎么用usememo去监听地址变化？][63%]
> * [[🧐[问题] ant design pro v5 版本，使用localStorage不生效问题 #9386](https://github.com/ant-design/ant-design-pro/issues/9386) ][🧐[问题]ant design pro v5 版本，使用localStorage不生效问题][63%]
> * [ [Ant Design Pro 在内容页面里如何实现打开一个新的标签页或浏览器窗口完成页面跳转](https://github.com/ant-design/ant-design-pro/issues/9356)[ #9356](https://github.com/ant-design/ant-design-pro/issues/9356) ][Ant Design Pro 在内容页面里如何实现一个新的标签页或浏览器窗口完成页面跳转转][61%][](https://github.com/ant-design/ant-design-pro/issues/9356)
> * [ [ant design pro 简单登录页面样式显示不全](https://github.com/ant-design/ant-design-pro/issues/9372)[🐛[BUG]  #9372](https://github.com/ant-design/ant-design-pro/issues/9372) ][ant design pro 简单登录页面样式显示不全🐛[BUG]][61%]
> * [ [ant design pro v4 怎么自定义动态主题](https://github.com/ant-design/ant-design-pro/issues/8482)[🧐[问题]  #8482](https://github.com/ant-design/ant-design-pro/issues/8482) ][ant design pro v4 怎么自定义动态主题🧐[问题]][61%]
> * [ [Ant Design Pro V5 已经支持预览](https://github.com/ant-design/ant-design-pro/issues/6605)[ #6605](https://github.com/ant-design/ant-design-pro/issues/6605) ][Ant Design Pro V5 已经支持预览][61%][](https://github.com/ant-design/ant-design-pro/issues/6605)
> * [ [Ant Design Pro 用户👨🏻‍💻👩🏻‍💻👨🏻‍💻👩🏻‍💻 ](https://github.com/ant-design/ant-design-pro/issues/99)[ #99](https://github.com/ant-design/ant-design-pro/issues/99) ][Ant Design Pro 用户👨🏻‍💻👩🏻‍💻👨🏻‍💻💩🏻‍💻][61%][](https://github.com/ant-design/ant-design-pro/issues/99)

这个帮不了我

**Comment by chenshuai2144** [comment]
在二级下面配置一个没有path 的路由就好了
