### ISSUE TITLE
🐛[BUG] public下的js文件打包后会被压缩混淆问题

### ISSUE THREAD

**Issue by FZUKingDuck** [ant-design/ant-design-pro#9460]
### 🐛 bug 描述

最近项目开发的时候碰到了个问题，我们业务中有一份js文件，需要放到public文件底下，打包出来后，在V4版本的项目中能正常的时候，在V5版本的项目中，该文件会被混淆加密。排查对比后发现，是因为开启了webpack5和mfsu这两个配置。通过demo复现可以发现，在js中未export出来的方法和变量，都会被压缩混淆。public文件夹下的文件不应该是直接复制到输出路径中去的吗，或者是否可以提供配置项对对应的文件进行排除

### 📷 复现步骤

通过umi脚手架创建了一个项目webpack5-test
public文件夹里新建一个testfile.js文件：

```js
const thisIsATestFileFunc = () => {
  console.log('this is a test file')
}

export const fileJson = {
  name: "aaa",
  fileInfo: "bbb",
  func: thisIsATestFileFunc,
}
```

配置文件中打开webpack5配置(这里只有webpack5和msfu都不打开的时候才会出现不混淆加密的情况)

```ts
const { REACT_APP_ENV } = process.env;

export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  ...//其余忽略，刚创的项目，都是默认的配置
  nodeModulesTransform: { type: 'none' },
  mfsu: {}, // 这两个配置，除非同时不开启，不然public下的js都会被混淆
  webpack5: {},
  exportStatic: {},
});
```

#### 不同参数打包结果对比：

- [x] mfsu开启 

- [x] webpack5开启

执行build命令后，打包后，testfile.js内容如下：

  ```js
const s=()=>{console.log("this is a test file")};export const fileJson={name:"aaa",fileInfo:"bbb",func:s};
// 可以看到文件被压缩了
  ```

  

- [ ] mfsu开启
- [x] webpack5开启

执行build命令后，打包后，testfile.js内容如下：

```js
const s=()=>{console.log("this is a test file")};export const fileJson={name:"aaa",fileInfo:"bbb",func:s};
// 同样的会被压缩混淆
```

- [ ] mfsu开启
- [ ] webpack5开启

执行build命令，打包出来的testfile.js如下：

```js
// 这是期望的状态
const thisIsATestFileFunc = () => {
  console.log('this is a test file')
}

export const fileJson = {
  name: "aaa",
  fileInfo: "bbb",
  func: thisIsATestFileFunc,
}
```

- [x] mfsu开启
- [ ] webpack5开启

```js
const s=()=>{console.log("this is a test file")};export const fileJson={name:"aaa",fileInfo:"bbb",func:s};
// 还是会被压缩
```

通过copy等配置进行复制到输出目录也同样会被压缩。

测试了ts类型的文件，发现ts类型的文件，开启上述两个配置也不会出问题。

在V4的版本里不会出现。

有怀疑过是Terser的问题，但是webpack修改terser插件的配置，增加exclude参数依旧无效。配置自己引入的terser也无效。

### 🏞 期望结果

期望的结果是public文件夹下的文件都不进行处理，直接输出 
或
增加配置项过滤相关文件

### © 版本信息

- Ant Design Pro 版本: [5.1.0]
- umi 版本 3.5.20
- nodejs版本：v14.15.5
- 开发环境 [Win10]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。




你好，根据你的描述，看起来你出现的问题是由于生产环境下，public文件夹下的js文件被压缩混淆，而期望的结果是public文件夹下的文件都不进行压缩混淆直接输出。由于你的问题比较具体，我将为你提供一些思路来解决这个问题。

首先，生产环境下，webpack将所有的js文件都进行了压缩混淆，这就导致了public文件夹下的js文件也被压缩混淆了。那么，如何避免这个问题呢？

解决方案：

方案一：将public文件夹下的js文件放在src目录下，这样就能享受到webpack的优化了，而且打包之后也不会被压缩混淆了。

方案二：可以通过添加exclude或include属性，从而来控制webpack从哪些目录或文件中提取出模块并生成对应的chunk。示例如下：

```javascript
module.exports = {
  ...
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        exclude: /\/public\//, // 排除 public 目录下的 js 文件
      }),
    ],
  },
  ...
};
```

当使用exclude属性时，被匹配的资源将不会被压缩混淆。如果你将public文件夹下的js文件放到了其他目录下，也可以通过指定include属性来实现相同的功能，示例如下：

```javascript
module.exports = {
  ...
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        include: /\/your_custom_directory\//, // 匹配你的自定义目录下的js文件
      }),
    ],
  },
  ...
};
```

需要注意的是，exclude和include匹配的是相对于工程根目录而言的路径。

参考文档：

[webpack配置exclude和include详解](https://zhuanlan.zhihu.com/p/50453845)

[webpack optimization](https://webpack.js.org/configuration/optimization/)

[TerserPlugin](https://webpack.js.org/plugins/terser-webpack-plugin/)

本次回答能否解决你的问题呢？

**Comment by EquinoxFlowerJG** [comment]
> 看相关issue，云谦老师已经解决了

那我是不是应该将 umi 升级到2022 年 7 月 7 日发布的 3.5.28版本？

**Comment by EquinoxFlowerJG** [comment]
> > 看相关issue，云谦老师已经解决了
> 
> 那我是不是应该将 umi 升级到2022 年 7 月 7 日发布的 3.5.28版本？

我试了试，不起作用，public 下的 js 还是被压缩了，而且项目还跑不起来了。😂
