### ISSUE TITLE
🐛[BUG]  edge 浏览器 simple 模板样式混乱

### ISSUE THREAD

**Issue by xnng** [ant-design/ant-design-pro#9461]
### 🐛 bug 描述

如图，样式混乱

![image](https://user-images.githubusercontent.com/38936252/146926123-dba463a2-b2ca-4ebb-aae8-7e5e7f09a18c.png)

![image](https://user-images.githubusercontent.com/38936252/146926067-386460b4-829b-4376-9219-36664a1bec59.png)

### 📷 复现步骤

1. run `npx create-umi demo`
2. select `ant-design-pro`
3. select `TypeScript`
4. select `simple`
5. run `cd demo && yarn && yarn start`
6. open `http://localhost:8000`

### 🏞 期望结果

显示效果同 `complete` 模板

### © 版本信息

- Ant Design Pro 版本: 5.1.0
- umi 版本 3.5.0
- 浏览器环境 Microsoft Edge 96.0.1054.62 (官方内部版本) (arm64)
- 开发环境 [mac OS m1]

### 🚑 其他信息

simple 模板在 chrome 显示没问题，只有 edge 有问题，都是 chromium 内核，控制台无报错

edge 上 complete 模板显示是没问题的

**Comment by 1007283085q** [comment]
同样出现问题在Chrome 96.0.4664.110
![QQ截图20211223095155](https://user-images.githubusercontent.com/41245643/147176399-15a3d2e4-9112-41c5-a69f-719f8a294a03.png)

**Comment by zhouchen33** [comment]
同样出现这个问题，进去后查询表格页也是样式错乱的

**Comment by zhfish** [comment]
build出来好像没问题，只有dev错乱

**Comment by feima-ccba** [comment]
> ### 🐛 错误描述
> 样式，样式
> 
> ![图片](https://user-images.githubusercontent.com/38936252/146926123-dba463a2-b2ca-4ebb-aae8-7e5e7f09a18c.png)
> 
> ![图片](https://user-images.githubusercontent.com/38936252/146926067-386460b4-829b-4376-9219-36664a1bec59.png)
> 
> ### 📷 复现步骤
> 1. 跑 `npx create-umi demo`
> 2. 选择 `ant-design-pro`
> 3. 选择 `TypeScript`
> 4. 选择 `simple`
> 5. 跑 `cd demo && yarn && yarn start`
> 6. 打开 `http://localhost:8000`
> 
> ### 🏞 期望结果
> 显示效果同`complete`模板
> 
> ### © 版本信息
> * Ant Design Pro 版本：5.1.0
> * umi 版本 3.5.0
> * 浏览器环境 Microsoft Edge 96.0.1054.62 (官方内部版本) (arm64)
> * 开发环境 [mac OS m1]
> 
> ### 🚑 其他信息
> 简单的模板在chrome显示没问题，只有边缘有问题，都是chrome内核，识别无报错
> 
> 边上完成模板显示是没问题的

**Comment by feima-ccba** [comment]
好像是msfu的问题，// mfsu: {}, 注释掉

**Comment by six-ben** [comment]
为啥不给个解释？
