### ISSUE TITLE
🐛[BUG]刚拉取的项目，跑不起来

### ISSUE THREAD

**Issue by JinShuohang** [ant-design/ant-design-pro#9464]
### 🐛 bug 描述
![Snipaste_2021-12-22_14-52-27](https://user-images.githubusercontent.com/49704308/147048712-358025aa-2032-4c34-b76e-af90ada2eae4.jpg)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.1.0]
- umi 版本
- 浏览器环境
- 开发环境 [win10]

**Comment by xnng** [comment]
+1

**Comment by Gonaldo7** [comment]
+1,同样问题，antd-pro团队没有检测bug就上线了吗

**Comment by zy0423** [comment]
+1，昨天拉的都没问题

**Comment by GitHubWuYi** [comment]
+1 相同的问题出现过好几次了。

**Comment by GitHubWuYi** [comment]
> +1，昨天拉的都没问题

牛蛙，看了下昨天的代码提交记录，把package.json 依赖包版本恢复就好了。

**Comment by GitHubWuYi** [comment]
@zy0423  拉取的项目代码和官网预览的不是同一个？

**Comment by zy0423** [comment]
@GitHubWuYi 忘了。。 应该是吧，之前也是通过create-umi创建的项目。

**Comment by micky09119** [comment]
+1

**Comment by zy0423** [comment]
@GitHubWuYi 刚刚大佬修复了，又可以了

**Comment by micky09119** [comment]
我也正常了

**Comment by Gonaldo7** [comment]
@zy0423 我重新创建项目安装后，还是报less错误

**Comment by starsoul666** [comment]
> 又可以了

yarn create umi 重新创建项目吗？

**Comment by xnng** [comment]
> @GitHubWuYi 刚刚大佬修复了，又可以了

哪里修复了，我重新创建项目，还是这样啊

**Comment by chenshuai2144** [comment]
这个是锁了antd的包导致的 升级antd的包到最新版本

**Comment by showtan001** [comment]
原有项目升级后样式大乱，有大坑。
各位谨慎升级！

**Comment by mrstierchen** [comment]
😅我还以为是我的问题

**Comment by litttley** [comment]
我说今天重新构建突然有问题了,升级ant包完美解决

**Comment by ZengJun-cloud** [comment]
> 我说今天重新构建突然有问题了,升级ant包完美解决

升级到多少？

**Comment by litttley** [comment]
> > 我说今天重新构建突然有问题了,升级ant包完美解决
> 
> 升级到多少？

"antd": "^4.17.0",

**Comment by litttley** [comment]
是这个上面发错了 "antd": "4.17.4",
