### ISSUE TITLE
🧐[问题] EditableProTable 在編輯模式時如何調整步進量(step)

### ISSUE THREAD

**Issue by fapjsc** [ant-design/ant-design-pro#9466]
### 🧐 问题描述

EditableProTable 點擊編輯進入編輯模式後
假設valuesType是digit
請問要如何調整步進量 (step) ?

<img width="920" alt="截圖 2021-12-22 下午4 28 00" src="https://user-images.githubusercontent.com/74793624/147060845-30a12e52-ca10-47ee-bf3b-4ba82eecb0d2.png">

**Comment by chenshuai2144** [comment]
可以使用 filedProps 

和antd 使用方式一样了
