### ISSUE TITLE
如何在table中设置表格栏的文本格式🧐[问题]

### ISSUE THREAD

**Issue by lizhuo-code** [ant-design/ant-design-pro#9467]
如题，我的表格某些字段的内容是一些表达式，如JSON对象的文本形式等，我已经将这些JSON对象按照文本的内容进行了空格换行等文本格式化，但在table中仍然是按照一行或多行显示，完全不是我设置的格式，如下图：<img width="825" alt="截屏2021-12-22 下午4 32 08" src="https://user-images.githubusercontent.com/95171813/147062289-6c33b115-9720-425d-9b68-105c33267062.png">另外我尝试过在表格字段中加入Input.TextArea组件来显示格式化文字，但会将TextArea的边框也显示出来，并且显示的背景颜色也跟表格不一致，感官上无法接受，如下图：<img width="1027" alt="截屏2021-12-22 下午4 27 00" src="https://user-images.githubusercontent.com/95171813/147062566-27688219-a615-4978-be84-9bcfc89eaa3b.png">
我想知道如何怎么做才能让table显示我格式化的文本,大侠们帮我想想办法，谢谢

**Comment by huntdream** [comment]
用`<pre>`标签啊
