### ISSUE TITLE
动态加载路由和菜单，已解决！！！🐛[BUG]

### ISSUE THREAD

**Issue by caimingyi484** [ant-design/ant-design-pro#9468]
### 🐛 bug 描述
我动态加载菜单，但是没办法解析component，提示404页面不存在：
app.jsx
```
import { dynamic } from '@umijs/runtime';
import LoadingComponent from '@ant-design/pro-layout/es/PageLoading';
```
```
export const layout = ({ initialState }) => {
  return {
    menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: initialState,
      request: async (params, defaultMenuData) => {
        console.log(defaultMenuData,initialState);
        const menuData = [{
          path: '/welcome2',
          name: 'welcome',
          icon: 'smile',
          // hideInMenu: true,
          exact: true,
          access: "canAdmin",
          component: dynamic({ loader: () => import('./pages/Form'), loading: LoadingComponent}),
        }];
        return menuData;
      },
  };
};
```
麻烦请教一下该如何解决？

**Comment by caimingyi484** [comment]
```
let extraRoutes = [];
export function patchRoutes({ routes }) {
  routes[1].routes = routes[1].routes.concat(extraRoutes);
  console.log(history.location.pathname, routes)
  console.log(extraRoutes)
}
export function render(oldRender) {
  // fetch('/api/routes').then(res=>res.json()).then((res) => {
    // const comp2 = ()=> import('./pages/Welcome');
    import('./pages/Welcome').then((module) => {
      console.log(module);
      extraRoutes = [{
        path: '/welcome2',
        name: 'welcome',
        icon: 'smile',
        // hideInMenu: true,
        // exact: true,
        // component: Form,
        component: module.default,
      }];
      oldRender();
    });
  // })
}
```
也是不行....

**Comment by WhiteTheIce** [comment]
> 已解决！！！！ 不要使用menu配置
> 
> ```
> let extraRoutes = [];
> export function patchRoutes({ routes }) {
>   routes[1].routes = routes[1].routes.concat(extraRoutes);
>   // 如果最后页面是404，所以要插入到时候第二个
>   // routes[1].routes.splice(-1, 0, ...extraRoutes);
>   console.log(history.location.pathname, routes)
>   console.log(extraRoutes)
> }
> export function render(oldRender) {
>   // fetch('/api/routes').then(res=>res.json()).then((res) => {
>       extraRoutes = [{
>         path: '/welcome2',
>         name: 'welcome',
>         icon: 'smile',
>         // hideInMenu: true,
>         exact: true,
>         access: "canAdmin",
>         component: dynamic({ loader: () => import('./pages/Form'), loading: LoadingComponent}),
>       }];
>       oldRender();
>   // })
> }
> ```

可以说下具体怎么写么

**Comment by tanchang123** [comment]
就算是不使用menu属性配置，他会默认使用约定是路由，如果你不在route.js里面配置的话一样是404

**Comment by tanchang123** [comment]
let extraRoutes;

export function patchRoutes({ routes }) {
  merge(routes, extraRoutes);
}

export function render(oldRender) {
  fetch('/api/routes').then(res=>res.json()).then((res) => { 
    extraRoutes = res.routes;
    oldRender();
  })
}

可以参考 umi 官方文档，在app.tsx里面调用这两个方法可以实现

**Comment by JbfGod** [comment]
> 就算是不使用menu属性配置，他会默认使用约定是路由，如果你不在route.js里面配置的话一样是404

那这个menu属性着实是有点鸡肋，只能控制菜单显示，在route.js里面没有与之配对的还得是显示404。一点没感受到“菜单的高级用法”

**Comment by yxyfb** [comment]
感觉componen用dynamic很关键，一开始没用这个，第一次从登录页跳转到首页，会出现不能正确显示组件，但是退出再登录，就正常显示；   加上后这个后，就不会出现这个问题；感谢

**Comment by Olimiya** [comment]
请问下已解决是怎么样解决的。同样的代码，但是还是404错误。

**Comment by xXAvoraXx** [comment]
我需要有关如何动态加载路线和菜单的演示。
