### ISSUE TITLE
🐛[BUG] Dockerfile.hub build EACCES: permission denied

### ISSUE THREAD

**Issue by oulp** [ant-design/ant-design-pro#9469]
### 🐛 bug 描述

使用阿里云的容器镜像服务编译(https://cr.console.aliyun.com/cn-hangzhou/instances),
clone的代码https://code.aliyun.com/oulei/ant-design-pro

报如下错误：

316#14 [builder 6/6] RUN npm run build
317#14 sha256:6f67255bc778b8b4af0a4e725d9a3fa223b96b30afa31dd9912f2d36a7806dc6
318#14 0.296
319#14 0.296 > ant-design-pro@5.2.0 build
320#14 0.296 > umi build
321#14 0.296
322#14 0.778 Babel could not read cache file: /root/.babel.7.14.0.production.json
323#14 0.778 due to a permission issue. Cache is disabled.
324#14 0.793 Browserslist: caniuse-lite is outdated. Please run:
325#14 0.793 npx browserslist@latest --update-db
326#14 0.793
327#14 0.793 Why you should do it regularly:
328#14 0.793 https://github.com/browserslist/browserslist#browsers-data-updating
329#14 2.197 Bundle with webpack 5...
330#14 2.327 EACCES: permission denied, mkdir '/usr/src/app/src/.umi-production/core'
331#14 2.328 Error: EACCES: permission denied, mkdir '/usr/src/app/src/.umi-production/core'
332#14 2.328 at Object.mkdirSync (node:fs:1334:3)
333#14 2.328 at d (/usr/src/app/node_modules/@umijs/deps/compiled/mkdirp/index.js:1:2145)
334#14 2.328 at Function.f [as sync] (/usr/src/app/node_modules/@umijs/deps/compiled/mkdirp/index.js:1:372)
335#14 2.328 at Proxy.fn (/usr/src/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/registerMethods.js:78:24)
336#14 2.328 at Object.<anonymous> (/usr/src/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:83:9)
337#14 2.328 at Generator.next (<anonymous>)
338#14 2.328 at asyncGeneratorStep (/usr/src/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:48:103)
339#14 2.328 at _next (/usr/src/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:50:194)
340#14 2.328 at /usr/src/app/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/generateFiles/core/history.js:50:364
341#14 2.328 at new Promise (<anonymous>)
342#14 ERROR: executor failed running [/bin/sh -c npm run build]: buildkit-runc did not terminate successfully

- Ant Design Pro 版本: [e.g. 5.2.0]

**Comment by chenshuai2144** [comment]
把 docker 镜像权限升级给的高一点，操作文件还很多

**Comment by oulp** [comment]
> 把 docker 镜像权限升级给的高一点，操作文件还很多，不好一个个设置

这个怎么给高？ --> 阿里云的容器镜像服务编译(https://cr.console.aliyun.com/cn-hangzhou/instances),
