### ISSUE TITLE
🐛[BUG] 切换路由有时就会报错 Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by cy188** [ant-design/ant-design-pro#9470]
### 🐛 bug 描述

初始化项目之后，运行初始项目，切换路由就会报错 

### 📷 复现步骤

根据官网的快速开始步骤，初始化项目，选择ant design pro，再选择Typescript，再选择simple
然后安装依赖，然后yarn start 运行项目
然后在页面上切换路由有时候就会报错
[![Tg01YD.png](https://s4.ax1x.com/2021/12/29/Tg01YD.png)](https://imgtu.com/i/Tg01YD)

### 💻 复现代码

初始化项目就可以复现

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本
- 浏览器环境  Chrome 96.0.4664.45
- 开发环境 [e.g. windows 10]

### 🚑 其他信息

报错信息：

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at PageHeader (http://localhost:8000/vendors-node_modules_antd_es_affix_index_js-node_modules_antd_es_page-header_index_js-node_mo-f3e00b.js:1152:60)
    at div
    at ProPageHeader (http://localhost:8000/vendors-node_modules_ant-design_pro-layout_es_components_PageContainer_index_js.js:319:65)
    at div
    at PageContainer (http://localhost:8000/vendors-node_modules_ant-design_pro-layout_es_components_PageContainer_index_js.js:384:24)
    at Welcome (http://localhost:8000/p__Welcome.js:151:58)
    at LoadableComponent (http://localhost:8000/umi.js:141692:68)
    at Route
console.<computed> @ devScripts.js:6523
overrideMethod @ react_devtools_backend.js:4045
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js:23914
scheduleUpdateOnFiber @ react-dom.development.js:21840
dispatchAction @ react-dom.development.js:16139
onResize @ index.js:108
(anonymous) @ index.js:74
Promise.then (async)
(anonymous) @ index.js:73
(anonymous) @ observerUtil.js:11
(anonymous) @ observerUtil.js:10
onResize @ observerUtil.js:6

**Comment by cy188** [comment]
这个问题其他人没有遇到过吗？

**Comment by qiangguoguo** [comment]
5.2.0 也遇到了这个错误

**Comment by yuwenzhuifeng** [comment]
+1

**Comment by yuandalu** [comment]
确实遇到了，希望有人帮忙看下，追了下代码貌似是PageContainer组件报的，在深入搞不太明白了

**Comment by qq1170623178** [comment]
网络请求回来之后使用setState，如果组件被销毁的话就会报这个错误，希望react能把这个报错放宽一点，虽然没啥影响，或者当个告警也行

**Comment by chenshuai2144** [comment]
[qq1170623178](https://github.com/qq1170623178)

不好好处理很容易内存泄露的，最好用生命周期销毁一下

**Comment by gaona233** [comment]
所以解决方案是啥，为啥就关掉了
