### ISSUE TITLE
🧐[问题]请问一下开发模式下,如何配置SameSite=None.使用高德地图,刷新浏览器报跨域错误.

### ISSUE THREAD

**Issue by Iveon** [ant-design/ant-design-pro#9477]
今天使用高德地图的时候出现一个问题,正常访问没有问题

但是一刷新浏览器,页面就返回:

Something went wrong.
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.

名称	网域 & 路径
dev_help	.amap.com/
gray_auth	.amap.com/
l	.amap.com/
tfstk	.amap.com/

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.

**Comment by chenshuai2144** [comment]
SameSite要后端配置了吧。前端好像不能搞。

https://juejin.cn/post/6844904096575537166
