### ISSUE TITLE
卡片列表页卡片标题过长时样式错乱

### ISSUE THREAD

**Issue by atmjs** [ant-design/ant-design-pro#948]
![image](https://user-images.githubusercontent.com/12792057/36292319-d875db32-130b-11e8-9985-795b0ed95c69.png)

**Comment by atmjs** [comment]
期望：多余的文字显示省略号，另外鼠标hover之后能显示title

**Comment by chenshuai2144** [comment]
欢迎 pr 。
功能不是很难 你可以试试。

**Comment by pkaq** [comment]
@atmjs 
可以用[Ellipsis](https://pro.ant.design/components/Ellipsis-cn/) 包一下 注意中英文长度上的不同

**Comment by atmjs** [comment]
嗯 好的 现在我还没具体的业务用的到，只是根据以往的经验测试下这个功能，等用到了我再处理。

**Comment by ddcat1115** [comment]
Ellipsis 只能限制字数或行数，这里还是设置最大宽度比较灵活，如需 tooltip 可以加上

**Comment by atmjs** [comment]
好的 辛苦！

**Comment by atmjs** [comment]
![image](https://user-images.githubusercontent.com/12792057/36832791-f2912cfe-1d67-11e8-864e-1581b6452c46.png)

![image](https://user-images.githubusercontent.com/12792057/36832699-89646e6c-1d67-11e8-94f6-2fabfbb0cccc.png)

标题长度在70多个的时候，第一列cardtooltip提示内容跑最后一列去了
ps: placement设置为left时正常
