### ISSUE TITLE
🐛[BUG]在global.less中引入src/assets/img下面的文件打包出来后找不到路径，开发模式可以找到图片

### ISSUE THREAD

**Issue by MorningStarHu** [ant-design/ant-design-pro#9481]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
放到 public 里面，然后用绝对路径吧。不然打包之后路由就变了
