### ISSUE TITLE
🧐[问题] 使用 request 统一配置错误处理无效。

### ISSUE THREAD

**Issue by FanNick** [ant-design/ant-design-pro#9484]
### 🧐 问题描述

尝试使用 框架自己带的错误处理，但是使用 useRequest 时，成功可以返回数据，后台返回错误时，前端不会报错。

后台返回的数据如下：

`{
    "success": false,
    "data": {},
    "errorMessage": "Parameters Error.",
    "showType": 1
}`

此时 useRequest 没有返回错误，触发了 onSuccess 事件。

使用默认配置不成功后，尝试使用自定义配置：
在 app.tsx 中添加了如下代码：, 拦截器与自定义的错误配置均不生效, 
关于拦截器，网上有人和我一样，可参考 https://www.sunzhongwei.com/ant-design-pro-v5-using-umi-request-interceptor-for-request-header-and-jwt-token

想知道 app.tsx 除了直接导出 还需要增加其他配置吗？

```
const authHeaderInterceptor = (url: string, options: any) => {
  let token = localStorage.getItem('token');
  if (null === token) {
    token = '';
  }
  const authHeader = { Authorization: `Bearer ${token}` };
  return {
    url: url,
    options: { ...options, interceptors: true, headers: authHeader },
  };
};


export const request: RequestConfig = {
  timeout: 1000,
  errorConfig: {
    adaptor: (resData) => {
      console.log(resData)
      return {
        ...resData,
        success: resData.success,
        errorMessage: resData.errorMessage,
      };
    },
  },
  middlewares: [],
  requestInterceptors: [authHeaderInterceptor],
  responseInterceptors: [],
};




```

**Comment by FanNick** [comment]
经过能测试， 如果我在 http 返回 400 的错误会提示，但如果只是 success = false 不会触发错误事件。

**Comment by sunzhongwei** [comment]
老哥，你用了我的链接，哈哈 😂

**Comment by FanNick** [comment]
我升级了 5.2  这个问题就解决了。但 defaultSetting 又加载不了。

**Comment by chenshuai2144** [comment]
defaultSetting 看看是不是 路径错了

**Comment by Valar103769** [comment]
> 我升级了 5.2 这个问题就解决了。但 defaultSetting 又加载不了。

你升级的哪个依赖?
