### ISSUE TITLE
mapbox with ant-design-pro emitValidationErrors

### ISSUE THREAD

**Issue by hasanmumin** [ant-design/ant-design-pro#9485]
#### Description
I am trying use mapbox with ant-design-pro but there are some console errors.

#### Repro Steps

https://github.com/hasanmumin/ant-design-pro-mapbox
Mapbox code https://github.com/hasanmumin/ant-design-pro-mapbox/blob/master/src/pages/Welcome.tsx

#### Environment (please complete the following information):

- Library Version: ^6.1.18
- React Version: ^17.0.0
- Browser Version: Chrome 96.0.4664.110
- OS: Mac OS X 12.0.1

#### Logs
There are many console errors
- sources.earthquakes: unknown property "data-inspector-line" at Object.ai [as emitValidationErrors]
- sources.earthquakes: unknown property "data-inspector-column" at Object.ai [as emitValidationErrors]
- sources.earthquakes: unknown property "data-inspector-relative-path" at Object.ai [as emitValidationErrors]

etc

I created the same issue for Mapbox, but they think PageContainer injection some props to mapbox. 
https://github.com/visgl/react-map-gl/issues/1648

**Comment by iossocket** [comment]
Hi hasanmumin, any update for it, I got the same issue.
thanks

**Comment by chenshuai2144** [comment]
try  close  `react-dev-inspector`
