### ISSUE TITLE
重新拉下代码安装完依赖再启动的时候就报这个错误Module build failed (from ./node_modules/@umijs/bundler-webpack/mini-css-extract-plugin/dist/loader.js)🐛 🐛[BUG]

### ISSUE THREAD

**Issue by complete-fangzr** [ant-design/ant-design-pro#9493]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
报错日志贴详细点

**Comment by complete-fangzr** [comment]
> 报错日志贴详细点
![image](https://user-images.githubusercontent.com/93582316/147656951-8ab295ab-bbc9-49ac-b99a-10f9518e9751.png)麻烦帮忙看一下

**Comment by ZengJun-cloud** [comment]
升级antd

**Comment by zhuozhihaiCloud** [comment]
我与遇到这样的问题了
`

 error  in ./node_modules/@ant-design/pro-form/es/components/List/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):


    &:hover {
      color: @primary-color-hover;
           ^
Variable @primary-color-hover is undefined
      in /Users/dylan/Desktop/caldron-ai-pc/node_modules/@ant-design/pro-form/es/components/List/index.less (line 59, column 13)
    at processResult (/Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115794:19)
    at /Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
    at /Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
    at context.callback (/Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 error  in ./node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):


    &:hover {
      color: @primary-color-hover;
           ^
Variable @primary-color-hover is undefined
      in /Users/dylan/Desktop/caldron-ai-pc/node_modules/@ant-design/pro-utils/es/components/LabelIconTip/index.less (line 16, column 13)
    at processResult (/Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115794:19)
    at /Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
    at /Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
    at context.callback (/Users/dylan/Desktop/caldron-ai-pc/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

`

**Comment by complete-fangzr** [comment]
config.ts文件中theme配置个primary-color-hover的颜色



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月14日 15:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ant-design/ant-design-pro] 重新拉下代码安装完依赖再启动的时候就报这个错误Module build failed (from .***@***.***/bundler-webpack/mini-css-extract-plugin/dist/loader.js)🐛 🐛[BUG] (Issue #9493) |

我与遇到这样的问题了
`

error in .***@***.***/pro-form/es/components/List/index.less

Module build failed (from .***@***.***/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from .***@***.***/deps/compiled/less-loader/cjs.js):

&:hover {

  color: @primary-color-hover;

       ^



Variable @primary-color-hover is undefined
in ***@***.***/pro-form/es/components/List/index.less (line 59, column 13)
at processResult ***@***.***/deps/compiled/webpack/5/bundle5.js:115794:19)
at ***@***.***/deps/compiled/webpack/5/bundle5.js:115900:5
at ***@***.***/deps/compiled/webpack/5/bundle5.js:35125:11
at ***@***.***/deps/compiled/webpack/5/bundle5.js:34977:18
at context.callback ***@***.***/deps/compiled/webpack/5/bundle5.js:34850:13)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:95:5)

error in .***@***.***/pro-utils/es/components/LabelIconTip/index.less

Module build failed (from .***@***.***/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from .***@***.***/deps/compiled/less-loader/cjs.js):

&:hover {

  color: @primary-color-hover;

       ^



Variable @primary-color-hover is undefined
in ***@***.***/pro-utils/es/components/LabelIconTip/index.less (line 16, column 13)
at processResult ***@***.***/deps/compiled/webpack/5/bundle5.js:115794:19)
at ***@***.***/deps/compiled/webpack/5/bundle5.js:115900:5
at ***@***.***/deps/compiled/webpack/5/bundle5.js:35125:11
at ***@***.***/deps/compiled/webpack/5/bundle5.js:34977:18
at context.callback ***@***.***/deps/compiled/webpack/5/bundle5.js:34850:13)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:95:5)

`

**Comment by zhuozhihaiCloud** [comment]
> config.ts文件中theme配置个primary-color-hover的颜色
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年04月14日 15:04 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [ant-design/ant-design-pro] 重新拉下代码安装完依赖再启动的时候就报这个错误Module build failed (from .***@***.***/bundler-webpack/mini-css-extract-plugin/dist/loader.js)🐛 🐛[BUG] (Issue #9493) | 我与遇到这样的问题了 ` error in .***@***.***/pro-form/es/components/List/index.less Module build failed (from .***@***.***/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js): ModuleBuildError: Module build failed (from .***@***.***/deps/compiled/less-loader/cjs.js): &:hover { color: @primary-color-hover; ^ Variable @primary-color-hover is undefined in ***@***.***/pro-form/es/components/List/index.less (line 59, column 13) at processResult ***@***.***/deps/compiled/webpack/5/bundle5.js:115794:19) at ***@***.***/deps/compiled/webpack/5/bundle5.js:115900:5 at ***@***.***/deps/compiled/webpack/5/bundle5.js:35125:11 at ***@***.***/deps/compiled/webpack/5/bundle5.js:34977:18 at context.callback ***@***.***/deps/compiled/webpack/5/bundle5.js:34850:13) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5) error in .***@***.***/pro-utils/es/components/LabelIconTip/index.less Module build failed (from .***@***.***/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js): ModuleBuildError: Module build failed (from .***@***.***/deps/compiled/less-loader/cjs.js): &:hover { color: @primary-color-hover; ^ Variable @primary-color-hover is undefined in ***@***.***/pro-utils/es/components/LabelIconTip/index.less (line 16, column 13) at processResult ***@***.***/deps/compiled/webpack/5/bundle5.js:115794:19) at ***@***.***/deps/compiled/webpack/5/bundle5.js:115900:5 at ***@***.***/deps/compiled/webpack/5/bundle5.js:35125:11 at ***@***.***/deps/compiled/webpack/5/bundle5.js:34977:18 at context.callback ***@***.***/deps/compiled/webpack/5/bundle5.js:34850:13) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:95:5) ` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

谢谢  可以了
