### ISSUE TITLE
🧐[问题]项目中API这个命名空间并没有导入，为什么使用不会报错

### ISSUE THREAD

**Issue by jinglun2019** [ant-design/ant-design-pro#9494]
### 🧐 问题描述

src/services/ant-design-pro/typings.d.ts文件下声明了API namespace，
src/services/ant-design-pro/api.ts 文件中使用了这个API namespace，比如API.CurrentUser，API.LoginResult，
src/access.ts也使用了API.CurrentUser，
没看到API被import
，使用却是正常的，why？

**Comment by chenshuai2144** [comment]
d.ts 会自动导入的

**Comment by jinglun2019** [comment]
请问下具体是通过什么实现的

**Comment by jinglun2019** [comment]
> d.ts 会自动导入的

具体是怎么实现的

**Comment by jcahsy170324** [comment]
src/services/ant-design-pro/typings.d.ts文件下声明了API namespace，
src/services/ant-design-pro/api.ts 文件中使用了这个API namespace，比如API.CurrentUser，API.LoginResult，
src/access.ts也使用了API.CurrentUser，
没看到API被import
，使用却是正常的，why？
