### ISSUE TITLE
🐛[BUG]v5.2.0 安装umi-plugin-keep-alive  导致 access.ts 权限管理 失效

### ISSUE THREAD

**Issue by CHENJKNB** [ant-design/ant-design-pro#9496]
### 🐛 bug 描述

v5.2.0 安装umi-plugin-keep-alive  导致 access.ts 权限管理 失效。代码没做任何修改 ，单单安装这个插件 权限管理 就无效。

### 💻 复现代码
export default function access(initialState: { currentUser?: API.CurrentUser | undefined }) {
  const { currentUser } = initialState || {};
  return {
    canAdmin: currentUser && currentUser.access === 'admin',
  };
}

### © 版本信息

- Ant Design Pro 版本: [v. 5.2.0]
- umi 版本3.5.0
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by gaoyayun** [comment]
umi-plugin-keep-alive 作者 在 0.0.1-beta.30 版本修复了此问题
