### ISSUE TITLE
🧐[打包后chunk css 覆盖了 umi，本地没问题]

### ISSUE THREAD

**Issue by deerLoves** [ant-design/ant-design-pro#9499]
![image](https://user-images.githubusercontent.com/43427994/147799382-3a2eb49f-85cf-4264-baf3-dad7327a69ad.png)

**Comment by deerLoves** [comment]
ant-pro-basicLayout-content 是我在/src/globel.less 中改的

**Comment by chenshuai2144** [comment]
手动提升下优先级吧，顺序问题的确是个很麻烦的点
