### ISSUE TITLE
🧐[问题]pro-table列表页码不是pageSize和current该如何修改？

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design-pro#9500]
如题，能提供全局的替换字段方法吗？
在beforeSearchSubmit方法里面通过解构返回，但是在request里面还是返回了current，pageSize；
在beforeSearchSubmit 拿不到params里面的值，不知道算不算问题

params={{ params1: 1, params2: 2 }}

beforeSearchSubmit={params => {
         // params 无法获取 params1,params2
        const { current, pageSize, ...rest } = params;
        return { ...rest, page: current, sizes: pageSize };
 }}

 request={async params => {
    // params 拿到 {current, pageSize, page, sizes}
     const data = await rule();
     return { data: data.list, success: true, total: data.count };
}}

**Comment by chenshuai2144** [comment]
在requeut 里面拦截一下吧
