### ISSUE TITLE
🧐[问题] .d.ts是如何实现自动导入的

### ISSUE THREAD

**Issue by jinglun2019** [ant-design/ant-design-pro#9502]
### 🧐 问题描述

.d.ts是如何实现自动导入的，没有看到这方面相关的代码，还望前辈指点一二

https://github.com/ant-design/ant-design-pro/issues/9494#issue-1090452843
还是之前的那个问题，不过被closed了，还是不明白怎么就隐式自动导入了

**Comment by jinglun2019** [comment]
研究了好久，后来发现只要这么写就回自动导入，啥也不用配置

**Comment by chenshuai2144** [comment]
这是 ts的规范
