### ISSUE TITLE
🧐[问题]

### ISSUE THREAD

**Issue by Pseven7** [ant-design/ant-design-pro#9503]
### 💻 示例代码
![image](https://user-images.githubusercontent.com/54761890/147900447-5d9e29a6-e798-433b-9534-c88874d19811.png)
![image](https://user-images.githubusercontent.com/54761890/147900467-d20e30ad-333e-4b85-97dc-69f38d5d2b5d.png)

**Comment by Lind-pro** [comment]
同样遇到了这个问题

**Comment by Lind-pro** [comment]
注释这几行代码。 https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L94-L97
