### ISSUE TITLE
🐛[BUG]官方文档纠错

### ISSUE THREAD

**Issue by qq1170623178** [ant-design/ant-design-pro#9504]
### 📷 复现步骤

![image](https://user-images.githubusercontent.com/43264733/148028134-47aa4593-14cc-4f83-bd11-1b254232be8c.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
直接来pr把。文档必合并
