### ISSUE TITLE
👑 [需求]我使用了个第三方库要求配置webpack.config.js  fallback 我不知道如何配置 chainWebpack没有fallback 属性配置

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design-pro#9505]
### 🚑 其他信息

第三方opencv库 https://github.com/TechStark/opencv-js#readme

使用这个库运行直接卡死了没任何报错信息
文档说需要配置webpack.config.js 我怀疑是我没配置的原因,我也不知道这个配置有何作用?

module.exports = {
  resolve: {
    modules: [...],
    fallback: {
      fs: false,
      path: false,
      crypto: false
    }
  }
};

**Comment by chenshuai2144** [comment]
你要用chainwebpack 来配置的，umi是不支持配置 webpack.config.js 的
