### ISSUE TITLE
开发模式 proxy  如何请求后台接口 🧐[问题]

### ISSUE THREAD

**Issue by ifnk** [ant-design/ant-design-pro#9506]
### 💻 示例代码
前端端口 ：8005 ，后端端口 8180
代码如下 
config.ts 
![image](https://user-images.githubusercontent.com/39295458/148038564-65e60d69-c738-4b2a-8307-5d45f96fedca.png)

proxy.ts 因为默认是dev 环境 我就只改了dev 的代码 
![image](https://user-images.githubusercontent.com/39295458/148038738-162a9c86-ccd3-40d4-a8c5-06d6e24535e3.png)

axiosInstance.ts 我用了 axios 请求 因为有proxy ,所以axios baseurl 设置成空的 
![image](https://user-images.githubusercontent.com/39295458/148038996-b5586f69-548a-4557-b229-f7f5ed47614d.png)

具体的请求 apiDevice.ts
![image](https://user-images.githubusercontent.com/39295458/148039105-5d12173f-59b5-40ae-a5e6-1c7f420fddda.png)

我看issue 说要把 mock 禁用了 ，所以我的  package.json 为    start   "start": "cross-env UMI_ENV=dev MOCK=none umi dev "

但是结果却是 一个网页 
![image](https://user-images.githubusercontent.com/39295458/148039622-b9e59d14-6737-4749-b6c3-0c2a0cdd437f.png)

我注意到他请求的 url 是 http://localhost:8005/user/api/capacity ,按常理来说应该是  http://localhost:8005/api/capacity 才对， 然后 proxy才能根据 api 前缀 进行 代理 和后台请求 ，但是不知道他怎么搞的 把 http://localhost:8005/user 当成 是基础 url 了 

然后 我又切换到 列表页,请求相同的接口 ，
![image](https://user-images.githubusercontent.com/39295458/148040232-9a069e5a-f5be-4bcc-96c3-dcd2fc8bf642.png)

发现他 请求 的url 就换了 变成 http://localhost:8005/list/api/capacity  , 就是说 ant design pro 通过 axios 请求 后台接口时 ，baseurl 为什么会 带 上 当前 的 page 后缀呢？ ，我要怎么设置 才能让他 变成 http://localhost:8005/api/capacity ，因为这样才能通过 proxy 和 后台请求

**Comment by 569202812** [comment]
baseurl 问题吧 设置成前端地址

**Comment by ifnk** [comment]
> baseurl 问题吧 设置成前端地址

关键 我没有在哪里设置 ant design pro  baseurl 呢？ 我没有设置过baseurl

**Comment by chenshuai2144** [comment]
serve 要用 / 开头，不然会拼接当前页面路径上去。这样的proxy正则就匹配不上去了

**Comment by ifnk** [comment]
> serve 要用 / 开头，不然会拼接当前页面路径上去。这样的proxy正则就匹配不上去了

请问 具体 serve 在哪里配置呢 ？ 我看 uimi 的配置文档 没有找到 serve 这个选项 ，只找到了 base 这个配置项，但是他 默认就是 "/" 开头的呀？

**Comment by chenshuai2144** [comment]
你的URL就是server 要写成绝对路径
