### ISSUE TITLE
[BUG] yarn build 还会出现配置栏

### ISSUE THREAD

**Issue by justin75qxw** [ant-design/ant-design-pro#9507]
#8968 
#9257 
遇到的问题差不多，start 和 build 都有配置栏
没有找到解决方案中的依赖项`umi-plugin-setting-drawer`, **yarn.lock**中也无此插件

📷 复现步骤
```
yarn create umi
yarn
yarn start
yarn build
```

🏞 期望结果
UI 会有 config.ts 的设定。 配置栏不会被显示。

💻 复现代码
config.ts

© 版本信息
Ant Design Pro 版本: 5.2.0
umi 版本: 3.5.20
node： 16.13.1
开发环境： windows 10

**Comment by linchengzzz** [comment]
删除 SettingDrawer  这个组件就好了，详细可见 https://procomponents.ant.design/components/layout#settingdrawer

**Comment by justin75qxw** [comment]
> 删除 SettingDrawer 这个组件就好了，详细可见 https://procomponents.ant.design/components/layout#settingdrawer

感谢答复~
在`app.tsx`里删除掉这块就好了。
之前自己删除没效果应该是忘记刷新页面了。。。
