### ISSUE TITLE
🧐[问题]菜单选中，对应不同的路由页面，要怎么配置？

### ISSUE THREAD

**Issue by nickrogit** [ant-design/ant-design-pro#9508]
### 🧐 问题描述
菜单选中，对应不同的路由页面，要怎么配置？

（如：用户列表页里'新增'，是跳到新的路由页面的，但菜单还是选中'用户管理'）
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/4743941/148348381-dc0965e1-1dea-4665-956d-ba71c13e35f9.png)
设置了hideInMenu不行，期望：‘角色管理’列表页面按钮点击，跳转到‘角色设置’页面，菜单仍为‘角色管理’

**Comment by ZengJun-cloud** [comment]
参考
![image](https://user-images.githubusercontent.com/52198079/148353634-6a9d7fef-c3df-41bb-8d2e-bf76d258e51c.png)
