### ISSUE TITLE
🧐[问题]开启mfsu后theme主题失效

### ISSUE THREAD

**Issue by ZengJun-cloud** [ant-design/ant-design-pro#9509]
### 🧐 问题描述

5.1版本 theme主题修改失效，热更新一下css样式就正常了，但是f5刷新后会重置。

### 💻 示例代码
 theme: {
    'primary-color': '#1DA57A',
    'border-radius-base': '6px'
 }

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/52198079/148353366-75806d6d-e552-4443-8ee3-fef74c14ce83.png)
![image](https://user-images.githubusercontent.com/52198079/148353443-a534cdb7-26f3-44fe-9d50-1edcf626da51.png)

**Comment by ZengJun-cloud** [comment]
开启mfsu后，设置theme任何变量都无效，关闭后theme正常生效
同(https://github.com/ant-design/ant-design-pro/issues/9059)

**Comment by chenshuai2144** [comment]
因为css的问题，你可以先关掉 mfsu。暂时没什么好办法

**Comment by WenLonG12345** [comment]
有什么解决方法吗？ 求解
