### ISSUE TITLE
🧐[问题]请问下这是什么错误啊。开发着突然就这样了。删除了umi node_models 只要启动就这样子。心态搞崩了！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-pro#9510]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/12706830/148356807-ee090044-afc3-4b24-91e5-61e57c9238a3.png)

![image](https://user-images.githubusercontent.com/12706830/148356828-c348bff7-49ef-4656-b72f-ece676c0efd3.png)

开发我也没干什么就新建了个文件，引入了　
```
<DatePicker onChange={onChange} />
```
就像惹了它一样，编译过后就报错。然后我就删除重新安装，怎么搞都是报这样的错误。删除我新建的文件还是这样

**Comment by ZengJun-cloud** [comment]
老哥我炸主题了 你是哪个版本？

**Comment by codedart2018** [comment]
v5.1

**Comment by codedart2018** [comment]
新clone v5.2下来　我只要引入
Calendar
DatePicker
组件就会报这个错。

**Comment by chenshuai2144** [comment]
mfsu的锅，你需要 删除一下 .umi ,然后重新启动一下
