### ISSUE TITLE
🧐[问题]需要检查protable里的每行数据有没有空数据，所以怎样获取proTable里的所有数据（datasource）

### ISSUE THREAD

**Issue by algz** [ant-design/ant-design-pro#9512]
### 🧐 问题描述
需要检查protable里的数据是否为空，所以需要获取protable里的所有数据。

### 💻 示例代码
      <ProTable<TableListItem>
        actionRef={tableRef} //引用ProTable
        columns={columns} 
        rowKey="id" /
        search={false} //隐藏内嵌的表单查询
        //request、params 用于向服务端请求
        params={{ state: '0' }}
        request={async (params?: any)=> {
          // ProTable的params 参数作为形参(params)传入。
          return request('/testdata', {params,});
        }}
      />

**Comment by chenshuai2144** [comment]
<html>
<body>


dataSource | Table 的数据，protable 推荐使用 request 来加载 | T[] | -
-- | -- | -- | --
onDataSourceChange | Table 的数据发生改变时触发 | (dataSource: T[]) => void | -


</body>
</html>

**Comment by susanforme** [comment]
> dataSource	Table 的数据，protable 推荐使用 request 来加载	T[]	-
> onDataSourceChange	Table 的数据发生改变时触发	(dataSource: T[]) => void	-
https://procomponents.ant.design/components/editable-table/#%E4%B8%8E-formitem-%E9%85%8D%E5%90%88



protable 如何像edittable这样取到DataSource呢
![image](https://user-images.githubusercontent.com/51266600/204756489-ff813ac7-e3dc-4934-8b89-38e8774b9b69.png)

因为,使用了request,所以拿不到DataSource,或者有没有什么好方法能在protable中直接删除某一行,(table中嵌套的button,)
