### ISSUE TITLE
config配置不生效🐛[BUG]

### ISSUE THREAD

**Issue by sunguoxing0628** [ant-design/ant-design-pro#9521]
### 🐛 bug 描述

根据最新模版生成程序后，界面布局与预期不相符。

### 📷 复现步骤

1、根据[官网](https://pro.ant.design/zh-CN/docs/getting-started)生成程序，并安装依赖包。

2、打开配置文件`config.ts`，`layout`节点引用了`defaultSettings`

`config`内容如下：
```
import defaultSettings from './defaultSettings';
····
layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
```
`defaultSettings`内容如下:
```
import { Settings as LayoutSettings } from '@ant-design/pro-layout';

const Settings: LayoutSettings & {
  pwa?: boolean;
  logo?: string;
} = {
  navTheme: 'light',
  // 拂晓蓝
  primaryColor: '#1890ff',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixSiderbar: false,
  colorWeak: false,
  title: '南水设备管理系统',
  pwa: false,
  logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  iconfontUrl: '',
};

export default Settings;
```

### 🏞 期望结果

期望程序布局为下图所示，即`defaultSettings`的`layout: 'mix',`配置生效：菜单在左侧，标题在头部。

![image](https://user-images.githubusercontent.com/27573161/148594205-c42b1494-ba3f-459c-83bf-26e2ac7b2ac1.png)

### 🏞 实际结果

实际结果为下图所示，`defaultSettings`的`layout: 'mix',`配置不生效，显示为`layout: 'side',`配置：菜单与标题同时在左侧。

![image](https://user-images.githubusercontent.com/27573161/148594680-1cffe480-9251-4187-b89a-da9ac9877bb9.png)

### 💻 复现代码

使用[官网](https://pro.ant.design/zh-CN/docs/getting-started)的步骤建立程序。

### © 版本信息

- Ant Design Pro 版本: 5.2.0
- umi 版本: 3.5.0
- 浏览器环境: Chrome 96.0.4664.110
- 开发环境: mac OS 12.0.1

### 🚑 其他信息

无。

**Comment by cielu** [comment]
你这个生效了吗？我改了headerHeight 也不管用

**Comment by sunguoxing0628** [comment]
> 你这个生效了吗？我改了headerHeight 也不管用

可以了，按照[官方修复方式](https://github.com/ant-design/ant-design-pro/commit/50ee90f646e02837e28686a090e3a011a30228a4)修改`src/app.tsx`文件， 把`settings: {},`改为`settings: defaultSettings,`，就可以了，你试试。 @cielu
