### ISSUE TITLE
ant design pro v5权限配置不生效问题

### ISSUE THREAD

**Issue by spring-xql** [ant-design/ant-design-pro#9524]
### ant design pro v5 在routes.ts文件加了access，也在access.ts文件中配置了权限，但是还是不生效。请求大神解答下。
ps：两个项目，我自己这套项目一直在开发功能的却配置权限不生效，另外一套今天下载下来配置却能生效，对比了配置代码几乎都一样。很奇怪啊，麻烦各位大神解答下，有没有遇到同样问题的小伙伴～

![image](https://user-images.githubusercontent.com/59687677/148644361-0590c504-aafb-40e4-804b-7c8a48876159.png)
![image](https://user-images.githubusercontent.com/59687677/148644399-45e3888a-5537-4345-8c02-46f626ef46b3.png)

**Comment by laosandegudai** [comment]
看不到你的代码，但是有一点切记如果route里面的权限码（access）在access中木有定义，那么默认会认为有这个权限，通常的判断都是认为木有这个权限码就默认木有权限，这里不太一样。
