### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zkteco-home** [ant-design/ant-design-pro#9525]
刚更新了代码 antd 4.8.2
直接编译我的项目出现如下错误
![image](https://user-images.githubusercontent.com/66519168/148712619-76a92d14-76d5-4963-9024-4285489f2409.png)
@chenshuai2144

**Comment by zkteco-home** [comment]
> 刚更新了代码 antd 4.8.2 直接编译我的项目出现如下错误 ![image](https://user-images.githubusercontent.com/66519168/148712619-76a92d14-76d5-4963-9024-4285489f2409.png)

@chenshuai2144

**Comment by zkteco-home** [comment]
> 升级antd 版本

我刚更新了antd 4.18.3还是同样的问提 @chenshuai2144

**Comment by zkteco-home** [comment]
@chenshuai2144 请问有什么解决方案，估计只是我有问题，看报错又是antd有问题

**Comment by zkteco-home** [comment]
> 升级antd 版本

升级了还是不行啊，查了下别人也没人报告此问题，可我的错误也不是我的代码问题，请问为何?

**Comment by zkteco-home** [comment]
@chenshuai2144 @andriijas waiting ....

**Comment by andriijas** [comment]
> @chenshuai2144 @andriijas waiting ....

Don't wait for me I stop using less years ago.
