### ISSUE TITLE
🐛[BUG] 点击菜单跳转页面时 url 上保留了 query，这是正常的表现吗？

### ISSUE THREAD

**Issue by seif-wu** [ant-design/ant-design-pro#9526]
### 🧐 问题描述
拿[官网](https://preview.pro.ant.design/dashboard/analysis?a=1)来说，我在链接上添加了 a = 1, 然后点击菜单上的其他页面时 query 被保留了下来。

### 💻 示例代码

无

### 🚑 其他信息
![预览](https://user-images.githubusercontent.com/33513256/148723695-208e8023-51be-42ac-86bc-78461394414e.gif)

**Comment by seif-wu** [comment]
个人认为这是umi `history` , `Link` 的 BUG。

```
<Link to="/roles?a=2">跳转到 roles?a=2</Link>
<Link to="/roles?a=3">跳转到 roles?a=3</Link>
<Link to="/">跳转到 /</Link>
```

- 未刷新页面时是正常表现
![个人认为正常的表现](https://user-images.githubusercontent.com/33513256/148741954-f9dcbdd0-6b51-4944-a93c-55561e7ebf08.gif)
- 刷新页面后就出现异常
![屏幕录制2022-01-10 17 (1)](https://user-images.githubusercontent.com/33513256/148742033-acf6eb79-83f1-48ed-a005-fed99fd48ea5.gif)

**Comment by chenshuai2144** [comment]
你能找到是谁干的吗？

**Comment by seif-wu** [comment]
> 你能找到是谁干的吗？

我起了一个空白的 umi 用了同样的link 试了试没有这个问题

**Comment by seif-wu** [comment]
> 你能找到是谁干的吗？


目前知道是被他影响了
![image](https://user-images.githubusercontent.com/33513256/148765136-558479cc-ad01-4c11-9686-d96008401093.png)

**Comment by chenshuai2144** [comment]
这个会存下来有点蛋疼。
我想想怎么搞

**Comment by 363676727** [comment]
> 这个会存下来有点蛋疼。 我想想怎么搞

useUrlSearchParams，useMergedState，getDifferentSetting在某个环节对settings数据omit下？

**Comment by chenshuai2144** [comment]
你可以先 disableUrlParams ，我会想办法 omit 一下

**Comment by chenshuai2144** [comment]
修复了已经
