### ISSUE TITLE
👑 [需求] 替换所有services的请求使用axios

### ISSUE THREAD

**Issue by 1247748612** [ant-design/ant-design-pro#9527]
### 🥰 需求描述

目前有看到umi-next有[废弃使用umi-request](https://github.com/umijs/umi-next/issues/122#issuecomment-951638883)的可能，避免用户看到示例请求直接使用类似方式 `import { request } from "umi"` 发送请求，避免造成项目迁移成本，应对所有示例请求从 `import { request } from "umi";`应改成使用`import axios from "axios"`，使用axios代替

**Comment by proactivefly** [comment]
还不如4.x好用

**Comment by chenshuai2144** [comment]
会把 request  用 axios 重写的。不用修改
