### ISSUE TITLE
🐛[BUG]使用ProFormTimePicker.RangePicker组件报错

### ISSUE THREAD

**Issue by xiehan520** [ant-design/ant-design-pro#9528]
### 🐛 bug 描述

![微信截图_20220111194856](https://user-images.githubusercontent.com/54789520/148937704-a6632039-5a44-425f-b228-b5b22b1f9467.png)
![微信截图_20220111194914](https://user-images.githubusercontent.com/54789520/148937724-7f8ea3a0-db27-41b1-94a5-48f717497bbb.png)

使用ProFormTimePicker.RangePicker组件报错
不影响使用
build后线上不会出现

### © 版本信息
![微信截图_20220111195325](https://user-images.githubusercontent.com/54789520/148938047-859664c0-98d4-49b3-bee7-47a1f856ea62.png)

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by vosonwang** [comment]
same problem

**Comment by chenshuai2144** [comment]
修复了，是个warning
