### ISSUE TITLE
Module parse failed: Unexpected token (19:29)

### ISSUE THREAD

**Issue by hnxyhcz** [ant-design/ant-design-pro#9529]
### 🧐 问题描述

下载最新的zip包，安装依赖后，执行npm run start:dev报错

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/10190358/149050871-784dc705-e215-456b-934e-75472d8ef066.png)

**Comment by chenshuai2144** [comment]
来个重现，看起来是没有编译成 js ，node 不支持导致的。
