### ISSUE TITLE
simple版本登录页样式失效🐛[BUG]

### ISSUE THREAD

**Issue by Lin-Yudong** [ant-design/ant-design-pro#9530]
### 🐛 bug 描述
通过npx create-umi myapp创建simple版本项目，加载依赖项后打开项目，登录页的样式出现问题：输入框的样式失效

### 🏞 期望结果
![image](https://user-images.githubusercontent.com/75419736/149053791-7e088753-83d1-4357-8740-ff1a57b8a116.png)

### 💻 复现代码
问题解决：src/pages/user/login/index.less页面代码第一行
![image](https://user-images.githubusercontent.com/75419736/149053886-ae35e039-4880-40ed-9480-79e852e43391.png)
去除(reference)
![image](https://user-images.githubusercontent.com/75419736/149053926-4ee13053-046d-4d3f-a59d-72527a77f80a.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
问题截图
![image](https://user-images.githubusercontent.com/75419736/149051513-8bb734c2-9647-4781-bad2-905cdf8c1782.png)
![image](https://user-images.githubusercontent.com/75419736/149051536-7d46e38e-25eb-4db4-b72f-55748803383f.png)

**Comment by chaochaokeji** [comment]
我也是同样的问题，解决了吗？

**Comment by chenshuai2144** [comment]
mfsu 关掉就好了
