### ISSUE TITLE
🧐[问题] 登录之后会出现一串随机数国际化一闪而过

### ISSUE THREAD

**Issue by deerLoves** [ant-design/ant-design-pro#9533]
### 🧐 问题描述

devScripts.js:6523 [React Intl] Missing message: "menu.f39743cca95b7ad5e7ed68b657124b6c3d9efe976f806cb15f7813978d643194" for locale: "en-US"

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/43427994/149281360-9ee46f45-1525-40f2-82e0-fed99875fb80.png)

**Comment by chenshuai2144** [comment]
配置

`menu={  locale:false }`

**Comment by peter064226** [comment]
刚好解决了我的问题，感谢
