### ISSUE TITLE
🧐[问题]ant design pro V5 react版本动态路由绑定

### ISSUE THREAD

**Issue by netSharks** [ant-design/ant-design-pro#9534]
### 🧐 问题描述

从服务器获取了用户的菜单信息，左侧菜单可以正常显示，但是点击后，右侧并未展示相应菜单，如何将菜单信息动态绑定到路由routes中呢，现在是将routes写成静态的，如何做到动态添加

**Comment by chenshuai2144** [comment]
动态路由时不支持的，只支持动态菜单
