### ISSUE TITLE
🧐[问题] 麻了，是我不会玩吗？登录不上

### ISSUE THREAD

**Issue by wy2022** [ant-design/ant-design-pro#9536]
麻了，
"scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "openapi": "umi openapi",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc --noEmit"

"start": "cross-env UMI_ENV=dev umi dev", 启动这个还是提示 帐号密码错误,不知道咋玩.........

**Comment by wy2022** [comment]
大家都是怎么玩的？

**Comment by chenshuai2144** [comment]
好好写 issue，发泄情绪去群里

**Comment by rawbin-** [comment]
哈哈 想吐槽就吐槽下，做个记录，确实有坑，兄弟们扶一把

想搞个全量demo跑跑
直接 yarn create umi antd-pro-full && yarn && yarn dev 

这个时候你发现，不管咋登录，返回的都是405，玩不起来
然后想着是mock没开，就去config.ts config.dev.ts 里面开mock配置`mock:{}`,不管怎么配，没什么区别，重启devServer也不行

然后看`package.json` `scripts` `start:dev` 里面有个mock，于是改成true，不管你用VSCode 还是 Webstorm，改完命令行里有反应，看起来是重新编译了，然并卵，还是405

最终测试结果，`start:dev` 中 `MOCK=none` 改为 `MOCK=true`，同时重启devServer 即可开启默认的登录

**Comment by MINGLIANG98** [comment]
> 哈哈 想吐槽就吐槽下，做个记录，确实有坑，兄弟们扶一把
> 
> 想搞个全量demo跑跑 直接 yarn create umi antd-pro-full && yarn && yarn dev
> 
> 这个时候你发现，不管咋登录，返回的都是405，玩不起来 然后想着是mock没开，就去config.ts config.dev.ts 里面开mock配置`mock:{}`,不管怎么配，没什么区别，重启devServer也不行
> 
> 然后看`package.json` `scripts` `start:dev` 里面有个mock，于是改成true，不管你用VSCode 还是 Webstorm，改完命令行里有反应，看起来是重新编译了，然并卵，还是405
> 
> 最终测试结果，`start:dev` 中 `MOCK=none` 改为 `MOCK=true`，同时重启devServer 即可开启默认的登录

谁干的

**Comment by gitcute** [comment]
确实，我也遇到了
