### ISSUE TITLE
🧐[问题]proxy的配置问题有点迷惑

### ISSUE THREAD

**Issue by NTnewStudent** [ant-design/ant-design-pro#9539]
### 🧐 问题描述
proxy配置问题：
前端服务端口是8000
后端API接口是3000
在dev下面是可以正常转发的，
但是我打包umi build以后就没法正常访问了，
前端是nginx下的服务，api是express服务

### 💻 示例代码
![image](https://user-images.githubusercontent.com/35213035/149749846-b9e6fe7d-eafc-434e-a93c-5795037fc747.png)
![image](https://user-images.githubusercontent.com/35213035/149749891-5ad3ae54-39e7-4f82-83ad-e34965e9ca76.png)
![image](https://user-images.githubusercontent.com/35213035/149749957-37e2092e-0c3a-4c73-b59f-3ccf29007267.png)
请问我该怎么去配置代理和API接口，本地调试就可以。不知道为什么打包以后就不行

**Comment by NTnewStudent** [comment]
![image](https://user-images.githubusercontent.com/35213035/149752267-63f4be81-51b7-4741-8054-91f6b00e0a65.png)
pei'zhi配置了nginx代理也没有用

**Comment by chenshuai2144** [comment]
稍微了解下基础知识吧
