### ISSUE TITLE
what is OMM in the docs?🧐[问题]

### ISSUE THREAD

**Issue by huanganfree** [ant-design/ant-design-pro#9542]
![Dingtalk_20220118115157](https://user-images.githubusercontent.com/41275935/149868012-fffe340b-b8be-445d-85ed-4dc08022c93e.jpg)

It is my advice that the docs should be clear for new user.

**Comment by huanganfree** [comment]
> Out Of Memory
> 
> 写了错别字，来个pr修一下把

OK！ Thank you for reply!!

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/ant-design-pro-site/pull/607
