### ISSUE TITLE
如何在父子路由中设置了component，还能正确跳转页面🧐[问题]

### ISSUE THREAD

**Issue by MirUac1e** [ant-design/ant-design-pro#9543]
### 🧐 问题描述
如下图所示
在Ant Design Pro的预览项目中可以点击面包屑上的‘表单页’重新定向到基础表单
![image](https://user-images.githubusercontent.com/57610507/149881556-c3f641ca-04c1-4386-90c2-81528634cd98.png)
如果可能的话，希望可以提供一下预览<https://preview.pro.ant.design/form/basic-form>的源码

再如下图所示
如果/admin的component设置了‘./admin’，下面子路由设置的component无论设置哪里都是访问‘./admin'
![image](https://user-images.githubusercontent.com/57610507/149882271-69a615fb-822c-4d69-a138-54d55c04a443.png)
重定向到‘/admin/sub-page’的话，页面是空白的

**Comment by MirUac1e** [comment]
补充：如果取消父路由的component，子路由的访问全部正常，但是要访问‘/admin’的话肯定就是404页面了

**Comment by Sh0214** [comment]
![image](https://user-images.githubusercontent.com/40195143/149900958-9b504a85-e892-460f-b3f6-e064bdb4730d.png)
应该这样子写父子路由的重定向 父路由不绑定组件

**Comment by MirUac1e** [comment]
> 

🙏感谢，确实这样就可以了
