### ISSUE TITLE
proTable中的renderFormItem是否能更改原先的数据类型👑 [需求]🧐[问题]

### ISSUE THREAD

**Issue by MirUac1e** [ant-design/ant-design-pro#9544]
### 🧐 问题描述
1. 在columns中我的某个列valueType设置为‘dateTime',上面的搜索框则会是显示时间和日期的datepick

现在我通过renderFormItem return一个` <DatePicker />`则上面搜索框显示为只有日期的datepick

但是在ProTable的request属性的函数接收到的参数 则还是时间+日期的格式，虽然可以通过更改格式直接获取到日期
是否可以直接获取到` <DatePicker />`的格式

2. 
![image](https://user-images.githubusercontent.com/57610507/149893016-1966ac13-0844-4eed-b7df-7e693538f5ab.png)
图中红框内的属性,在某个列valueType设置为‘dateTime'的时候是undefined的，找到源码也是没有这2个属性，是否已经被废弃

**Comment by MirUac1e** [comment]
补充：能否不在ProTable的request的回调中修改参数的某个名称
而是在renderFormItem中修改

**Comment by chenshuai2144** [comment]
用renderText 转化一下？
你的目标是什么我有点没搞清楚

**Comment by MirUac1e** [comment]
> 用renderText 转化一下？ 你的目标是什么我有点没搞清楚

就是protable的某个列valueType设置为‘dateTime' 显示年月日时分秒之类的

我想在搜索框中 只搜索年月日 不需要时分秒 所以使用renderFormItem return一个 <DatePicker />
这样前端显示的是就是年月日的格式了

但是在request函数里面的参数 获取到的数据是根据为‘dateTime' 返回的年月日时分秒的数据
不是由return 的datePicker返回的年月日数据格式

虽然是可以直接手动二次修改，就是想问一下能不能支持根据renderFormItem return的新类型返回request中的函数

时间过得比较久了 记得可能不太清楚

**Comment by MirUac1e** [comment]
上面回复第三行少了个` <DatePicker />`

**Comment by chenshuai2144** [comment]
这个不行的，组件不知道你到底render了什么东西出来。
