### ISSUE TITLE
🧐[问题]框架开启msfu之后生产环境部署报错

### ISSUE THREAD

**Issue by aierweisi** [ant-design/ant-design-pro#9547]
1、报错信息：mf-va_remoteEntry.js:1 Uncaught (in promise) Error: Module "./core-js" does not exist in container.
while loading "./core-js" from 36326
2、配置文件开启配置：	mfsu: { production: { output: '.mfsu-production' } },
3、表现：页面一直处在loading状态，不能加载进去

**Comment by chenshuai2144** [comment]
生产环境建议关掉，还没支持。
