### ISSUE TITLE
🐛[BUG]路由切换时，tableColumns 中的request 不执行 

### ISSUE THREAD

**Issue by yangxuefneng** [ant-design/ant-design-pro#9548]
### 🐛 bug 描述
路由切换时，tableColumns 中的request 不执行，导致下拉框数据不是最新的

### 📷 复现步骤
第一次进来会触发request获取下拉框数据，但是路由切换时，不会重新执行request

### 🏞 期望结果
期望： 路由切换时，重新执行request，获取最新下拉框数据

### 💻 复现代码
const tableColumns: ProColumns[] = [
    {
      title: 'xxx',
      dataIndex: 'xxxxxx',
      valueType: 'select',
      order: 10,
      async request() {
        const res = await queryDeptUsingPOST(params);
        return res?.data || [];
      }
    },
]

### © 版本信息

- @ant-design/pro-table: 2.62.4
- antd: 4.18.3
- umi 版本 3.5.0
- 浏览器环境 谷歌
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
把pathname 放到 params 里面把，

```tsx

const tableColumns: ProColumns[] = [
    {
      title: 'xxx',
      dataIndex: 'xxxxxx',
      valueType: 'select',
      params:{ pathname }
      order: 10,
      async request() {
        const res = await queryDeptUsingPOST(params);
        return res?.data || [];
      }
    },
]

```

**Comment by yangxuefneng** [comment]
并不需要pathname参数，，如果是空对象也不会重新触发 request;
const res = await queryDeptUsingPOST({});

**Comment by chenshuai2144** [comment]
pathname  更改会重新触发 request

**Comment by GreedyWhale** [comment]
同样的问题，这个bug不准备修复吗？
