### ISSUE TITLE
🐛[BUG]这是什么情况，上手就不顺

### ISSUE THREAD

**Issue by abelzhyb** [ant-design/ant-design-pro#9557]
E:\dev\code\ant-test>npm create umi
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? complete
> 🙈 complete mode can only use the version of antd@4
Cloning into 'E:\dev\code\ant-test'...
remote: Enumerating objects: 486, done.
remote: Counting objects: 100% (486/486), done.
remote: Compressing objects: 100% (401/401), done.
remote: Total 486 (delta 74), reused 345 (delta 58), pack-reused 0R
Receiving objects: 100% (486/486), 249.70 KiB | 1.22 MiB/s, done.
Resolving deltas: 100% (74/74), done.
> 🚚 clone success
> [Sylvanas] Prepare js environment...
> [JS] Clean up...
> Clean up...
✨ File Generate Done

E:\dev\code\ant-test>git init
Initialized empty Git repository in E:/dev/code/ant-test/.git/

E:\dev\code\ant-test>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ant-design-pro@5.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.4" from @ant-design/charts@0.9.13
npm ERR! node_modules/@ant-design/charts
npm ERR!   @ant-design/charts@"^0.9.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\abel\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abel\AppData\Local\npm-cache\_logs\2022-01-21T04_02_45_264Z-debug.log

**Comment by CoolSpot** [comment]
This happens only when "complete" set of blocks is installed which uses antd@4.
`npm install --force` seem to work around this issue (with many warnings).

**Comment by qinbinhua601** [comment]
I happened to run into this issue, too.

**Comment by chenshuai2144** [comment]
使用tyarn 或者 cnpm 吧，看起来是网络问题
