### ISSUE TITLE
👑 [需求]ant design pro v5 约定式路由后左侧菜单栏在登录页面会显示出来

### ISSUE THREAD

**Issue by WhiteTheIce** [ant-design/ant-design-pro#9559]
![image](https://user-images.githubusercontent.com/35474637/150486140-fb1c2522-282d-4b32-9799-60209903c03f.png)

**Comment by WhiteTheIce** [comment]
就想问改为约定式路由以后login的 layout: false,怎么去设置

**Comment by zmm2tysu** [comment]
> 就想问改为约定式路由以后login的 layout: false,怎么去设置

Login > index.tsx   在export Login之 前  Login.layout = false

**Comment by WhiteTheIce** [comment]
> > 就想问改为约定式路由以后login的 layout: false,怎么去设置
> 
> Login > index.tsx 在export Login之 前 Login.layout = false
能截图看看嘛

**Comment by chenshuai2144** [comment]
ref https://github.com/ant-design/ant-design-pro/issues/9560

**Comment by 1979044994** [comment]
> > 就想问改为约定式路由以后login的 layout: false,怎么去设置
> 
> Login > index.tsx 在export Login之 前 Login.layout = false
我尝试这么去做，但是没有效果
