### ISSUE TITLE
这里能不能获取个语雀的邀请码

### ISSUE THREAD

**Issue by atmjs** [ant-design/ant-design-pro#956]
前几天在语雀网上申请了，还没发放: wangjinqiang@gongchang.com
今年我们团队会用到文档协作工具，看了语雀的文档很是期待，这两天想体验下是否符合团队的需求。
看到这里面有语雀的开发者，希望能通融通融 ^_^ 不胜感激。

**Comment by dengfuping** [comment]
@atmjs 如果已经申请开通企业空间的话，只需等待申请结果即可。最近年假期间，申请结果可能会稍晚。
