### ISSUE TITLE
🐛[BUG]ant design pro v5 约定式路由后左侧菜单栏在登录页面会显示出来

### ISSUE THREAD

**Issue by WhiteTheIce** [ant-design/ant-design-pro#9560]
![image](https://user-images.githubusercontent.com/35474637/150486224-5c129380-918f-4cb9-8db8-62008cfc889b.png)

**Comment by JennyLeung030** [comment]
你應該是忘了routes設定了
![image](https://user-images.githubusercontent.com/51438629/150487030-20be6531-fd5d-4ea8-bf78-26ba99c8bb2f.png)

**Comment by WhiteTheIce** [comment]
> 你应该是通知路线设置了 ![图片](https://user-images.githubusercontent.com/51438629/150487030-20be6531-fd5d-4ea8-bf78-26ba99c8bb2f.png)

约定式路由是没法控制登录路由的配置

**Comment by WhiteTheIce** [comment]
> 你应该是通知路线设置了 ![图片](https://user-images.githubusercontent.com/51438629/150487030-20be6531-fd5d-4ea8-bf78-26ba99c8bb2f.png)
![image](https://user-images.githubusercontent.com/35474637/150487369-e79a610b-7d86-4b16-90ce-9c49b402f6af.png)

**Comment by WhiteTheIce** [comment]
> 你應該是忘了routes設定了 ![image](https://user-images.githubusercontent.com/51438629/150487030-20be6531-fd5d-4ea8-bf78-26ba99c8bb2f.png)

大神有木有解决方案啊？急需请求帮助！！！

**Comment by JennyLeung030** [comment]
你可以發一下你route關於login page截圖來看看嗎?

**Comment by WhiteTheIce** [comment]
> 你可以發一下你route關於login page截圖來看看嗎?

![image](https://user-images.githubusercontent.com/35474637/150490940-a2d86ff5-3a7b-44cb-8bf3-0e205665ad6e.png)
![image](https://user-images.githubusercontent.com/35474637/150491005-2da992ff-ff35-4b50-ad06-6cd3b2df7c82.png)

**Comment by WhiteTheIce** [comment]
> 你可以發一下你route關於login page截圖來看看嗎?

![image](https://user-images.githubusercontent.com/35474637/150491096-7ad7f0bc-692b-43b2-8ed7-257a6d7aeb6f.png)
![image](https://user-images.githubusercontent.com/35474637/150491159-4c80d048-4856-45a9-9759-b3c6a7c6cc8b.png)

**Comment by WhiteTheIce** [comment]
> 你可以發一下你route關於login page截圖來看看嗎?

路由完全是约定式的由后端请求控制

**Comment by JennyLeung030** [comment]
> > 你可以發一下你route關於login page截圖來看看嗎?
> 
> 路由完全是约定式的由后端请求控制

的確是可以用後端控制

**Comment by WhiteTheIce** [comment]
> > > 你可以發一下你route關於login page截圖來看看嗎?
> > 
> > 
> > 路由完全是约定式的由后端请求控制
> 
> 的確是可以用後端控制

后端控制的结果就是改为约定式路由然后就出现了登录页的layout控制不了出现了上图所出现的问题

**Comment by JennyLeung030** [comment]
> > > > 你可以發一下你route關於login page截圖來看看嗎?
> > > 
> > > 
> > > 路由完全是约定式的由后端请求控制
> > 
> > 
> > 的確是可以用後端控制
> 
> 后端控制的结果就是改为约定式路由然后就出现了登录页的layout控制不了出现了上图所出现的问题

因為我不是用後端控制,我是利用前端routes控制, 所以在後端那要加上控制login界面不可以套用現有的layout

**Comment by JennyLeung030** [comment]
在ant design pro 5.0.0 的使用例子中, 它是有把login父親那一層的layout關掉的

**Comment by JennyLeung030** [comment]
你可以在app.jsx中看見它有用那一些組件

**Comment by JennyLeung030** [comment]
> 你可以在app.jsx中看見它有用那一些組件

這一頁的組件是應用給所有頁面,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content

**Comment by WhiteTheIce** [comment]
> > > > > 你可以發一下你route關於login page截圖來看看嗎?
> > > > 
> > > > 
> > > > 路由完全是约定式的由后端请求控制
> > > 
> > > 
> > > 的確是可以用後端控制
> > 
> > 
> > 后端控制的结果就是改为约定式路由然后就出现了登录页的layout控制不了出现了上图所出现的问题
> 
> 因為我不是用後端控制,我是利用前端routes控制, 所以在後端那要加上控制login界面不可以套用現有的layout

后端请求只有登录以后才会去请求路由去所以还是有这问题

> > 你可以在app.jsx中看見它有用那一些組件
> 
> 這一頁的組件是給所有頁面應用,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content

v5没法在app.jsx控制layout

**Comment by WhiteTheIce** [comment]
> > 你可以在app.jsx中看見它有用那一些組件
> 
> 這一頁的組件是給所有頁面應用,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content

他是由umi动态生成的layout
![image](https://user-images.githubusercontent.com/35474637/150494287-f44b7990-275d-4721-a36f-a054a368ed74.png)

**Comment by WhiteTheIce** [comment]
> > 你可以在app.jsx中看見它有用那一些組件
> 
> 這一頁的組件是給所有頁面應用,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content

所以只能在路由上控制，但是约定式路由必须把config中的routes注释掉才生效所以导致了没法控制login的路由

**Comment by JennyLeung030** [comment]
> > > 你可以在app.jsx中看見它有用那一些組件
> > 
> > 
> > 這一頁的組件是給所有頁面應用,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content
> 
> 所以只能在路由上控制，但是约定式路由必须把config中的routes注释掉才生效所以导致了没法控制login的路由

對丫, 所以我才說你要後端那要加上控制login界面不可以套用現有的layout

**Comment by WhiteTheIce** [comment]
> > > > 你可以在app.jsx中看見它有用那一些組件
> > > 
> > > 
> > > 這一頁的組件是給所有頁面應用,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content
> > 
> > 
> > 所以只能在路由上控制，但是约定式路由必须把config中的routes注释掉才生效所以导致了没法控制login的路由
> 
> 對丫, 所以我才說你要後端那要加上控制login界面不可以套用現有的layout

在没登录以前都没法获取到menu所以在后端加入了也没用因为根本控制不到

**Comment by WhiteTheIce** [comment]
我已经试过了

**Comment by JennyLeung030** [comment]
> > > > > 你可以在app.jsx中看見它有用那一些組件
> > > > 
> > > > 
> > > > 這一頁的組件是給所有頁面應用,你需要route裏面的不想應用的頁面都關掉,你才看不見左側菜單和上面的Right content
> > > 
> > > 
> > > 所以只能在路由上控制，但是约定式路由必须把config中的routes注释掉才生效所以导致了没法控制login的路由
> > 
> > 
> > 對丫, 所以我才說你要後端那要加上控制login界面不可以套用現有的layout
> 
> 在没登录以前都没法获取到menu所以在后端加入了也没用因为根本控制不到

不對丫, 你要先一個API專給不登錄的人用丫

**Comment by JennyLeung030** [comment]
你要拋棄那些孤兒嗎? QAQ

**Comment by WhiteTheIce** [comment]
> 
我也试过单独传手动在app.jsx里面固定写死一个login的配置路由在没登录以前用但是也没用，因为我改成了约定式路由就由umi自己生成了

**Comment by JennyLeung030** [comment]
有些頁面不用登錄用的丫, 例如: login, forgot password and activation acount

**Comment by JennyLeung030** [comment]
> 

可能你要轉回自己寫的route了

**Comment by WhiteTheIce** [comment]
umi又没法修改控制感觉这就是一个约定式路由的bug

**Comment by JennyLeung030** [comment]
> umi又没法修改控制感觉这就是一个约定式路由的bug

其實不算bug, 因為後端的api是否一定要登錄才能連是可以設定的

**Comment by JennyLeung030** [comment]
因為我上司有給我的API, 有幾個API是不需要登錄的

**Comment by WhiteTheIce** [comment]
感觉就约定式路由的一个bug，因为改为约定式的路由后login的权限没法控制了

**Comment by JennyLeung030** [comment]
> 感觉就约定式路由的一个bug，因为改为约定式的路由后login的权限没法控制了

login本來就不用權限去控制, 按到理說你要先登錄之後才知你有甚麽權限能看甚麽東西

**Comment by JennyLeung030** [comment]
如果你是swagger寫API的話, 裏面有一個security值是可以調需不需要登錄才能使用

**Comment by WhiteTheIce** [comment]
> 如果你是swagger寫API的話, 裏面有一個security值是可以調需不需要登錄才能使用

其实不需要什么权限的就是约定式路由以后没法控制login， layout: false,

![image](https://user-images.githubusercontent.com/35474637/150497445-63c274ec-2d22-4737-8d86-f352b412199c.png)

**Comment by WhiteTheIce** [comment]
所以就导致了左侧菜单栏在登录页面会显示出来

**Comment by WhiteTheIce** [comment]
> 如果你是swagger寫API的話, 裏面有一個security值是可以調需不需要登錄才能使用


其实我就想问改为约定式路由以后login的 layout: false,怎么去设置

**Comment by JennyLeung030** [comment]
> > 如果你是swagger寫API的話, 裏面有一個security值是可以調需不需要登錄才能使用
> 
> 其实我就想问改为约定式路由以后login的 layout: false,怎么去设置

https://blog.csdn.net/mayazure/article/details/108790898

**Comment by JennyLeung030** [comment]
> > 如果你是swagger寫API的話, 裏面有一個security值是可以調需不需要登錄才能使用
> 
> 其实我就想问改为约定式路由以后login的 layout: false,怎么去设置

我找到這個link, 或許能幫助你, 作者有說要把組件清空

**Comment by WhiteTheIce** [comment]
其实我也删除过umi 可是没用

**Comment by JennyLeung030** [comment]
> 其实我也删除过umi 可是没用

https://pro.ant.design/zh-CN/docs/layout 這個你試試

**Comment by WhiteTheIce** [comment]
![image](https://user-images.githubusercontent.com/35474637/150501821-7cdb9e3d-0215-4591-bcfe-c2eba922d081.png)
他这个也是要配置了config/route.ts才有用

**Comment by JennyLeung030** [comment]
> ![image](https://user-images.githubusercontent.com/35474637/150501821-7cdb9e3d-0215-4591-bcfe-c2eba922d081.png) 他这个也是要配置了config/route.ts才有用

![image](https://user-images.githubusercontent.com/51438629/150502054-b4d0396d-2761-4f96-b49e-6f9a820bfed4.png)
我指這個XD

**Comment by WhiteTheIce** [comment]
设置过再v5中会报错

**Comment by JennyLeung030** [comment]
> 设置过再v5中会报错

截圖給我看看

**Comment by WhiteTheIce** [comment]
![image](https://user-images.githubusercontent.com/35474637/150502504-37df0a39-3f72-4412-b778-78dd4c544c96.png)
![image](https://user-images.githubusercontent.com/35474637/150502620-632f7f55-decd-4e98-a742-484d7ce9be9e.png)

**Comment by WhiteTheIce** [comment]
感觉只要用约定路由就无解

**Comment by JennyLeung030** [comment]
> 感觉只要用约定路由就无解

看來你不能用了

**Comment by WhiteTheIce** [comment]
你不需要用约定路由吗？

**Comment by WhiteTheIce** [comment]
改为约定路由很好控制，v5以前的我都用约定路由控制

**Comment by JennyLeung030** [comment]
> 你不需要用约定路由吗？

不需要, 因為我要搞多語言顥示,還有有些頁面有好多地方會重複使用,我還自己寫了一些組件重用 (T^T)

**Comment by JennyLeung030** [comment]
> 改为约定路由很好控制，v5以前的我都用约定路由控制

我的case用自己寫的路由比較好操控

**Comment by WhiteTheIce** [comment]
我们需要后端去控制路由这些所以我前端写了没用写死了后期维护有问题name不好改变

**Comment by JennyLeung030** [comment]
> 

所以我用locales, 改那邊就好

**Comment by WhiteTheIce** [comment]
后期打包发布了呢

**Comment by JennyLeung030** [comment]
> 后期打包发布了呢

打包也是這樣, 因為網頁要定期維護, 我這有後端的同事幫我推上docker

**Comment by WhiteTheIce** [comment]
客户的需求千奇百怪，一会要改icon 一会要改name，一旦打包发布了就没有源代码了全是压缩文件

**Comment by JennyLeung030** [comment]
> 客户的需求千奇百怪，一会要改icon 一会要改name，一旦打包发布了就没有源代码了全是压缩文件

所以我們會把source code存進公司server

**Comment by WhiteTheIce** [comment]
所以我的处理方式就是让约定路由后端控制routes

**Comment by lg970044** [comment]
`Login.layout = false;
export default Login;`

**Comment by WhiteTheIce** [comment]
> `Login.layout = false; export default Login;`

请问在哪里设置啊

**Comment by zmm2tysu** [comment]
> > `Login.layout = false; export default Login;`
> 
> 请问在哪里设置啊

https://umijs.org/zh-CN/docs/convention-routing#扩展路由属性
把.title 换成.layout就行了

**Comment by pepperbeibei** [comment]
这样就可以解决了。
![图片](https://user-images.githubusercontent.com/36815671/156698293-9df483d8-11cb-4192-b708-def51f7877eb.png)

**Comment by Iveon** [comment]
通过AntDesginPro学了好久的React，@[chenshuai2144](https://github.com/chenshuai2144)每次我有问题都会给出解决方法。
总算可以反哺了，其实方法有很多种，既然是路由就改路由就好了。
约定式路由不能有配置文件，那就在运行时改：

> 在src/app.tsx文件中增加

![image](https://user-images.githubusercontent.com/21276534/156916148-9ee3ee3b-f55f-407a-af5c-6424aa739b6e.png)

**Comment by StringKe** [comment]
umi4 max 可以采用一下这个方式

修改对应路由的 parentId 为空就行。

```ts

import {minimatch} from 'minimatch'
const skipLayoutRoutes = ['/access']

export async function patchRoutes({routes}: {
    routes: Record<string, IRoute>; routeComponents: any;
}) {
    const allRoutes: Record<string, IRoute> = {};
    Object.keys(routes).forEach((key: string) => {
        const route = routes[key];
        const path = '/' + route.path.toLowerCase();
        const isSkipLayout = skipLayoutRoutes.some((skipPath) => {
            return minimatch(path, skipPath)
        })

        if (isSkipLayout) {
            Object.assign(route, {
                parentId: undefined,
            })
        }
        allRoutes[key] = route;
    })

    console.log("allRoutes", allRoutes)

    return allRoutes;
}
```
