### ISSUE TITLE
🧐[问题] 上传组件 ProFormUploadButton ，onChange 方法 某个状态下会重复执行

### ISSUE THREAD

**Issue by AFunnyKitty** [ant-design/ant-design-pro#9564]
### 🧐 问题描述
版本号：V5

使用上传组件 ProFormUploadButton ，上传文件时，onChange 方法会重复执行。

"uploading" 这个状态下会执行两次，
"done" 这个状态下也会执行两次，

有没有大佬知道原因？

### 💻 示例代码

![image](https://user-images.githubusercontent.com/42233806/150636497-64b23637-14d7-4b07-9f52-9438d5fd0923.png)

![image](https://user-images.githubusercontent.com/42233806/150636454-f2a3be55-bd3b-42d7-9440-2d83557607f1.png)

![image](https://user-images.githubusercontent.com/42233806/150636557-3c2eb2ed-f25f-4c2f-ba3f-c76dd4af7922.png)

**Comment by HQDragon** [comment]
目前考虑到 pro component 的改动量比较大，建议你将事件写在这个组件的 fieldProps 里面。
``<ProFormUploadDragger
          label="文件上传"
          max={1}
          name="dragger"
          accept=".kmz,.kml,.csv,.txt"
          action="/api/gis/parse_kmlz"
          fieldProps={{
            onChange: (e) => {
              if (e.file.status === 'done') {
                const pureName = e.file.name;
                formRef?.current?.setFieldsValue({
                  dataSource: e.file.response.data.coordinates,
                  name: pureName?.substring(0, pureName.lastIndexOf('.')),
                });
                // setEditableRowKeys(
                //   e.file.response.data.coordinates.map((item: DataSourceType) => item.id),
                // );
              }
            },
          }}
        />``

**Comment by HQDragon** [comment]
此问题，多个月以前我自己也遇到过，是某个 issue 下看到的解决方案。
暂时不确定是官方会一个一个 pro 组件的修，还是 设计如此。所以，个人建议你在以后的 pro component 中尽量写在 fieldProps 里

**Comment by AFunnyKitty** [comment]
-- @ant-design/pro-form 组件已更新到最新版     "@ant-design/pro-form": "^1.52.13",  依然存在此问题。

非常感谢，使用此方式（事件放到 fieldProps 中）解决了这个问题。
