### ISSUE TITLE
🧐[问题] 增加页面，不需要登录就能访问，如何配置?

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design-pro#9566]
### 🧐 问题描述

想请教2个问题：

* 需要增加个页面，不需要登录即可访问。但是脚手架生产的代码会拦截跳转到登录页面。请教如何配置？(已解决)
* 如果需要定义没有登录页面的layout，怎么自己定义或者引用？

**Comment by jacktang** [comment]
我在 `app.tsx`的`RunTimeLayoutConfig`函数中返回自动的layout配置，但是左侧菜单还是有的。请问怎么去掉？

**Comment by a97077088** [comment]
怎么解决的

**Comment by chenshuai2144** [comment]
根据pathname设置 layout=false

**Comment by hooliy** [comment]
> 根据pathname设置 layout=false
> 
> 菜单可以设置menuRender 为false

具体layout=false配置写在哪里?

**Comment by chenshuai2144** [comment]
在config.ts 的路由配置中。也就是你新加的路由
