### ISSUE TITLE
全量模板默认开启用户认证mock+相关文档说明

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design-pro#9570]
希望可以在官方文档里面加上一页专门说明几种starterkit的内容

真正实现开箱即用

解决如下问题： 

> 想搞个全量demo跑跑
> 直接 yarn create umi antd-pro-full && yarn && yarn dev

> 这个时候你发现，不管咋登录，返回的都是405，玩不起来
> 然后想着是mock没开，就去config.ts config.dev.ts 里面开mock配置mock:{},不管怎么配，没什么区别，重启devServer也不行

> 然后看package.json scripts start:dev 里面有个mock，于是改成true，不管你用VSCode 还是 Webstorm，改完命令行里有反应， > 看起来是重新编译了，然并卵，还是405

> 最终测试结果，start:dev 中 MOCK=none 改为 MOCK=true，同时重启devServer 即可开启默认的登录认证mock，`package.json`中的优先级比配置文件中的高

**Comment by chenshuai2144** [comment]
默认应该使用 `yarn start`。
