### ISSUE TITLE
🧐[问题] 怎么根据路由动态设置 contentStyle

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design-pro#9572]
### 🧐 问题描述

比如我想单独设置路由为 /home 的 contentStyle

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/47104575/151131618-43b42190-1149-406d-a1aa-304e196a5552.png)

**Comment by chenshuai2144** [comment]
自己判断一下pathname。

**Comment by linxianxi** [comment]
> 自己判断一下pathname。

```
contentStyle: pathname === "/home"? { } : { }
```
在这里判断切换路由是不会执行的
