### ISSUE TITLE
🧐[问题] ProTable 里面的新增加一行的时候 怎么修改提示信息 (只能新增一行) ？

### ISSUE THREAD

**Issue by MirUac1e** [ant-design/ant-design-pro#9573]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/57610507/151137637-9f8b8e77-7386-44f2-9130-4c4e60cdbf4e.png)

新增一行后，再继续点击新增按钮
提示 ‘只能新增一行’ 需要修改这个提示的方法

**Comment by Sh0214** [comment]
![image](https://user-images.githubusercontent.com/40195143/151305066-f01d1ed9-3c9b-43d4-9bf5-95bcd49d252c.png)
