### ISSUE TITLE
将 ant-design-pro 组件拆分成插件或者独立的安装包模式

### ISSUE THREAD

**Issue by guoqqqi** [ant-design/ant-design-pro#9577]
### 🥰 需求描述

使用 ant-desigin-pro 时，如何将不同的页面模块、组件或者新增的页面，拆分成独立的插件或者安装包，或者独立的仓库来维护。便于对每个模块单独管理和维护，而无需关心其余无关的代码。

**Comment by juzhiyuan** [comment]
Hi, could you please give a more detailed description?

**Comment by chenshuai2144** [comment]
试过了 失败了

**Comment by guoqqqi** [comment]
嗨 @chenshuai2144 ，如果想要完成它，有什么思路可以参考的嘛 😄😄

**Comment by chenshuai2144** [comment]
去看看 umi ui
