### ISSUE TITLE
antd 在编译时未被引入

### ISSUE THREAD

**Issue by MuLodMan** [ant-design/ant-design-pro#958]
创建 app 失败，antd模块没有被引入，请问一下这是什么情况？
![antdproissuepng](https://user-images.githubusercontent.com/24437520/36518159-439e3bda-17c0-11e8-873c-4a4d1a2fdb12.png)

**Comment by yesmeck** [comment]
重新安装依赖。

**Comment by yesmeck** [comment]
#936

**Comment by MuLodMan** [comment]
谢谢，问题已经解决@yesmeck
