### ISSUE TITLE
[问题] 通用布局更换目录后无法启动

### ISSUE THREAD

**Issue by relaxyel** [ant-design/ant-design-pro#9581]
### 🧐 问题描述
将原本在 components 目录下的 Footer、HeaderDropdown、RightContent 移动到新建的layouts目录下无法启动.

### 💻 示例代码
![image](https://user-images.githubusercontent.com/55173820/152675901-8e3d578a-7dfb-4290-a407-4648f32213d9.png)

![image](https://user-images.githubusercontent.com/55173820/152675918-13e416c9-7c43-4672-9dcd-d7ff5279f1d6.png)

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本: 3.5.0
- 浏览器环境: Chrome
- 开发环境: [Windows10 node.js v12.22.9]

**Comment by chenshuai2144** [comment]
路径也要改的

**Comment by relaxyel** [comment]
> 路径也要改的

您好，可以详细说明下或给下相关文档吗？目前我没找到需要同步修改的地方，感谢😀

**Comment by chenshuai2144** [comment]
字面意思，跟着提示改。
