### ISSUE TITLE
SettingDrawer一直显示英文，如何设置成中文

### ISSUE THREAD

**Issue by tilkofjin** [ant-design/ant-design-pro#9586]
### 🧐 问题描述

在Pro V5.0基础上升级到可以动态切换主题后，设置按钮展开全是英文，按文档在config中设置local也无效，不知如何解决此问题，盼大佬们答疑解惑

### 💻 示例代码
```ts
<SettingDrawer
      enableDarkTheme
      settings={initialState?.settings}
      disableUrlParams
      hideHintAlert
      onSettingChange={(nextSettings: Partial<LayoutSettings> | undefined) => {
        setInitialState({
          ...initialState,
          settings: { ...nextSettings},
        });
      }}
    />
```

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/24365622/153109500-2014dea8-ef21-47bc-9960-d3c70530c8ea.png)

**Comment by tilkofjin** [comment]
> https://github.com/ant-design/pro-components/blob/8e907d8bbe48848c37e8ce1d5a584880e181f250/packages/layout/src/locales/index.ts#L24
> 
> 看这里
> 
> ```
> const getLanguage = (): string => {
>   // support ssr
>   if (!isBrowser()) return 'zh-CN';
>   const lang = window.localStorage.getItem('umi_locale');
>   return lang || (window as unknown as GLocaleWindow).g_locale || navigator.language;
> };
> 
> export { getLanguage };
> ```

我在项目中可以从哪里修改后生效呢？

**Comment by chenshuai2144** [comment]
```tsx
import { setLocale } from 'umi'


setLocale("zh-CN")
```

**Comment by tilkofjin** [comment]
> ```tsx
> import { setLocale } from 'umi'
> 
> 
> setLocale("zh-CN")
> ```

好的，谢谢！~
