### ISSUE TITLE
🐛[BUG]protable的params发生变化后，分页的page未充值到第一页

### ISSUE THREAD

**Issue by qq1170623178** [ant-design/ant-design-pro#9590]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
procomponents 中有一个一样的了

**Comment by chenshuai2144** [comment]
加回来试试，我忘记了
