### ISSUE TITLE
official website chrome error

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design-pro#96]
![image](https://user-images.githubusercontent.com/8358236/32363817-251d4126-c0ac-11e7-9618-0359280aa3a8.png)

**Comment by afc163** [comment]
强刷。

**Comment by hengkx** [comment]
https://segmentfault.com/q/1010000005872734

**Comment by afc163** [comment]
Try <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>r</kbd>

**Comment by hengkx** [comment]
thanks
