### ISSUE TITLE
🧐[问题]面包屑中，没有首页，是什么原因？

### ISSUE THREAD

**Issue by gaspire** [ant-design/ant-design-pro#9602]
### 🧐 问题描述
<img width="814" alt="image" src="https://user-images.githubusercontent.com/49259119/154419062-d170129c-6b77-49b0-b0ef-eca177b99208.png">

### 💻 示例代码
`export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './login',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        icon: 'smile',
        component: './Welcome',
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/users',
    name: 'users',
    icon: 'user',
    component: './users/',
  },
  {
    path: '/system',
    name: 'system',
    icon: 'setting',
    routes: [
      {
        path: '/system/city',
        name: 'cities',
        component: './system/cities/',
      },
      {
        path: '/system/admin',
        name: 'admins',
        component: './system/admins/',
      },
      {
        path: '/system/menu',
        name: 'menus',
        component: './system/menus/',
      },
      {
        path: '/system/role',
        name: 'roles',
        component: './system/roles/',
      },
      {
        path: '/system/permission',
        name: 'permissions',
        component: './system/permissions/',
      },
    ],
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  
  {
    component: './404',
  },
];`

**Comment by sarufarr** [comment]
以我的了解 目前需要自己写

**Comment by gaspire** [comment]
在app.tsx 里加上配置可以了：

**Comment by gaspire** [comment]
v4 版本好像不需要这样设置

**Comment by sarufarr** [comment]
看实际需求和路由设计吧
我在做的站 首页是要求置灰的。。

**Comment by gaspire** [comment]
嗯，需求点不一样，这样也有好处，比较灵活！
