### ISSUE TITLE
🐛[BUG] Pro5.0使用antd的Calendar组件报错

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-pro#9603]
### 🐛 bug 描述

在pro5.0中引入antd的Calendar组件提示未找到
![image](https://user-images.githubusercontent.com/20454290/154431838-5764bc2f-27ae-4f01-b70d-e84ead64760a.png)

![image](https://user-images.githubusercontent.com/20454290/154432171-4843db81-b7b7-4dea-8bc2-ae2deb879f41.png)

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本 [3.5.0]
- 浏览器环境 [chrome]
- 开发环境 [e.g. mac OS]
- antd [^4.18.7]
- node [v16.13.1]

**Comment by sarufarr** [comment]
清理下 `.num` 的缓存再试试
