### ISSUE TITLE
🧐[问题] 模板项目里的Admin页面在哪里？

### ISSUE THREAD

**Issue by Valar103769** [ant-design/ant-design-pro#9606]
刚下载的模板， 没看到有admin菜单啊，这个admin页面到底显示到哪里去了？

**Comment by chenshuai2144** [comment]
用admin 登录就能看见的

**Comment by Valar103769** [comment]
> 用admin 登录就能看见的

没看到啊， user 和admin 看到的都是一样的页面， 没看到区别
