### ISSUE TITLE
🧐Dark theme not work, after remove SettingDrawer

### ISSUE THREAD

**Issue by sorcerb** [ant-design/ant-design-pro#9608]
I set dark theme in defaultSettings.ts:
`navTheme: 'realDark',`

It work fine on all site, but not on login page, because it haven't SettingDrawer.
```
{!props.location?.pathname?.includes('/login') && ( 
 <SettingDrawer
```

After Drawer remove - all theme show as light on all site. I think it is not good - control theme with component. 
May be I need change another setting somewhere? I want change drawer to switch, like on https://pro.ant.design/
       
```
  <SettingDrawer
            prefixCls='hide'
            themeOnly={true}
            disableUrlParams
            enableDarkTheme
            settings={initialState?.settings}
            onSettingChange={(settings) => {
              setInitialState((preInitialState) => ({
                ...preInitialState,
                settings,
              }));
            }}
          />
```

**Comment by chenshuai2144** [comment]
realDark is SettingDrawer featrue
