### ISSUE TITLE
一个函数调用的疑问

### ISSUE THREAD

**Issue by atmjs** [ant-design/ant-design-pro#961]
![image](https://user-images.githubusercontent.com/12792057/36573954-3871c164-187e-11e8-98f5-747c86f56328.png)
![image](https://user-images.githubusercontent.com/12792057/36573974-4f961bf6-187e-11e8-979a-f29b15abeb20.png)
调用的时候 第二个参数不用传？怎么做到的？

**Comment by chenshuai2144** [comment]
```
const check = (authority, target, Exception) => {
  return checkPermissions(authority, CURRENT, target, Exception);
};

export default check;
```

导出的是这个方法

**Comment by atmjs** [comment]
哦 确实 不过这写法一眼看去太迷惑了。。。

**Comment by chenshuai2144** [comment]
新版本会改一改的。
