### ISSUE TITLE
🧐[问题]路由页面在切页回来后为什么会触发两次渲染

### ISSUE THREAD

**Issue by fssh** [ant-design/ant-design-pro#9610]
### 🧐 问题描述

我按照官方示例初始化的脚手架，但是切页回来后会触发两次渲染

### 💻 示例代码

npx create-umi myapp
然后一路回车
cd myapp && npm install

### 🚑 其他信息
然后我在welcome的函数组件中打了个log，结果第一次进欢迎页时是只显示了一次log，这是正常的，但是当切到其他菜单页后再切回欢迎页时log会触发两次，求解。

**Comment by chenshuai2144** [comment]
用 开发者工具看看？ 我试了一下不会的

**Comment by fssh** [comment]
就是在开发者工具看的，确有问题。
![page](https://user-images.githubusercontent.com/18034841/155256406-bddfa845-ae33-4d15-9998-de9362d79697.png)
![code](https://user-images.githubusercontent.com/18034841/155256584-9a58c5a2-7596-4412-8bb8-09a4a41175e8.png)

**Comment by chenshuai2144** [comment]
hooks的渲染只要props改变都会渲染的，不是 useEffect 重新调用就没事

**Comment by fssh** [comment]
> hooks的渲染只要props改变都会渲染的，不是 useEffect 重新调用就没事

问题是这里props为什么会改变，如果我在每次渲染时有大量计算，这样会影响性能。

**Comment by chenshuai2144** [comment]
计算要放到 useEffect 里面，而不是直接在render 里面

**Comment by fssh** [comment]
如果useEffect的依赖项内容较大，写在useEffect里一样会有性能问题。

**Comment by chenshuai2144** [comment]
那就改成 class 模式把，hooks 模式很难避免重复render。
