### ISSUE TITLE
👑 [需求] protable 的复选框不可以变化位置

### ISSUE THREAD

**Issue by 15723185734** [ant-design/ant-design-pro#9613]
使用proTable时无法像antd的table那样随意的变化复选框的位置，并且使用Table.SELECTION_COLUMN，和protable的rowSelection={{fixed:'right'}}都无法生效，并且自己不能使用css处理 把路堵死了啊。是我打开方式不对吗？

![image](https://user-images.githubusercontent.com/61341868/154813249-d92d732d-36ae-4f28-a809-1d3dd0352b03.png)
![image](https://user-images.githubusercontent.com/61341868/154813274-3959eb6e-8767-44f4-9960-5e18232ce521.png)
<img width="698" alt="lQLPDhsqkMa7TgrNA0rNBXSwBrXwuG2Up_QCFmmdgwAvAA_1396_842" src="https://user-images.githubusercontent.com/61341868/154813481-8e909e95-4561-47fe-a3e3-9d78c0291710.png">

**Comment by 15723185734** [comment]
https://codesandbox.io/s/sparkling-sunset-97rcgs?file=/App.tsx

**Comment by 15723185734** [comment]
![image](https://user-images.githubusercontent.com/61341868/154814970-673185a7-84d7-4f86-83b7-d1a3af8b946d.png)

**Comment by chenshuai2144** [comment]
支持了，可以试试咯
