### ISSUE TITLE
🐛[BUG] 启动报错

### ISSUE THREAD

**Issue by a1067111756** [ant-design/ant-design-pro#9614]
### 🐛 bug 描述

  按文档操作指南，克隆新的项目出来，启动出现错误

### 📷 复现步骤
  yarn create umi myapp
  yarn install
  npm run start:dev

### 🏞 期望结果
  启动项目正常，出现登录页面

### 💻 复现代码
  无，按复现步骤即可复现

### © 版本信息

- Ant Design Pro 版本: v5.2.0
- umi 版本 v3.5.0
- 浏览器环境 chrome v98.0.4758
- 开发环境 windows

### 🚑 其他信息
  编译正常，打开页面出现ant-design_colors包加载错误，
Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors-node_modules_ant-design_colors_dist_index_esm_js-node_modules_classnames_index_js failed.
(missing: http://localhost:8000/mf-dep_vendors-node_modules_ant-design_colors_dist_index_esm_js-node_modules_classnames_index_js.3384c032.async.js)
while loading "./@ant-design/icons/SmileOutlined" from webpack/container/reference/mf
while loading "./@ant-design/icons/es/icons/SmileOutlined" from webpack/container/reference/mf
while loading "./antd/es/config-provider" from webpack/container/reference/mf

   已尝试过删除重装项目，清楚yarn缓存，降级@ant-design/icons版本等操作均无效。也尝试issue中https://github.com/ant-design/ant-design-pro/issues/8076 这些方法也没得到解决

**Comment by chenshuai2144** [comment]
删除.umi 然后 关掉 mfsu 试试

**Comment by zhuwei** [comment]
@chenshuai2144 只能关掉吗？
