### ISSUE TITLE
🐛[BUG] DrawerForm 和 ProFormSelect 共用有奇怪的问题

### ISSUE THREAD

**Issue by FrankSFLYS** [ant-design/ant-design-pro#9618]
### 🐛 bug 描述 & 复现步骤

有一个抽屉表单 `DrawerForm`，里面有个 `ProFormSelect`。界面上有两个按钮，一个是用来新建的，给抽屉表单这个字段传的是 `undefined`，另一个是编辑按钮，给抽屉表单传的是 `[]`。

如果刷新页面之后，首先点击的是新建按钮，那么一切正常。但如果首先点击的是编辑按钮，那么选择框里面就没有数据，如图。如果选择框开启了 showSearch，那么输入内容之后选择框又可以正常使用了。
如果把  `DrawerForm` 换成 `ModalForm`，这个问题就没有了。但是我的表单内容比较多，倾向于使用  `DrawerForm`。

![image](https://user-images.githubusercontent.com/10843159/155049152-080cd145-68c7-434d-9f35-47ade341e9f8.png)

正常情况下的图片。选择框是直接从 `ProFormSelect` 文档中抄的，使用 `request` 获取数据。
![image](https://user-images.githubusercontent.com/10843159/155049231-0b712a4c-1fee-4064-9b53-a671129fa0af.png)

### 💻 复现代码

这是表单的代码，没什么特别的东西：
```tsx
interface ModalPropsTest {
  visible: boolean;
  setVisible: (visible: boolean) => void;
  task: undefined | { assign_to_departments: number[]; };
}

const TaskEditModalTest: FC<ModalPropsTest> = (props) => {
  const formRef = useRef<ProFormInstance>();

  const { task } = props;

  useEffect(() => {
    console.log(task?.assign_to_departments);
    if (task) {
      formRef.current?.resetFields();
      formRef.current?.setFieldsValue({
        ...task,
      });
    } else {
      formRef.current?.resetFields();
    }
  }, [task]);

  return (
    <DrawerForm visible={props.visible} formRef={formRef} onVisibleChange={props.setVisible}>
      <ProFormSelect
        name="assign_to_departments"
        label="任务分配给这些部门"
        key="assign_to_departments_selects"
        // mode="multiple"
        // showSearch
        request={async () => [
          { label: '全部', value: 'all1' },
          { label: '未解决', value: 'open2' },
          { label: '已解决', value: 'closed3' },
          { label: '解决中', value: 'processing4' },
        ]}
        placeholder="选择要分配给的部门"
        initialValue={task?.assign_to_departments}
      />
    </DrawerForm>
  );
};

export default TaskEditModalTest;
```

### 🏞 期望结果

正常情况下，不论点击编辑还是新建，选择框都应该显示所有选项。不论设成单选还是多选，是否显示搜索，都有这个问题。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境：MS Edge
- 开发环境 [e.g. mac OS]

**Comment by FrankSFLYS** [comment]
补充：只放一个选择框也会出问题，所以并不是两个选择框导致的。
如果一开始点了新建按钮，选择框可以正常选择，之后不刷新，再点编辑，
选择框也是正常使用的。

**Comment by FrankSFLYS** [comment]
补充：`Drawer` 套 `ProForm` 也有同样的问题。

**Comment by FrankSFLYS** [comment]
补充：我将数据使用 `useMemo` 存起来，然后用 `valueEnum` 展示，是可以的，但是遇到了新的问题。我的 `assign_to_departments` 数组里面放的是 value，但是使用 valueEnum 之后无法将 value 转成文字，只显示 value，又只能用 request 了。

**Comment by FrankSFLYS** [comment]
需求暂时解决了，手动转化了一下，使用 valueEnum，但是希望可以修复此 BUG。

**Comment by chenshuai2144** [comment]
你要保证 drawer 打开之后再设置，
drawer 打开要300ms

**Comment by FrankSFLYS** [comment]
好吧，我明白了，谢谢
