### ISSUE TITLE
🧐[问题]级联选择框三级，当二级和三级只有一个可选之后，选中默认选中第一级

### ISSUE THREAD

**Issue by yang-chuanjiang** [ant-design/ant-design-pro#9619]
### 🧐 问题描述

* 级联选择框三级，当二级和三级只有一个可选之后，选中默认选中第一级。
![image](https://user-images.githubusercontent.com/38531906/155052567-d015b90d-8ce7-4123-8ba4-1b86c679b5cc.png)
请问这种情况下能显示一二三级内容嘛

### 💻 示例代码
    <ProFormCascader
                    width={item.width}
                    name={item.dataIndex}
                    label={item.title}
                    placeholder={`请选择${item.title}`}
                    fieldProps={{
                      options: item.option,
                      multiple: item.title === '管辖地区', // 管辖地区多选
                      showSearch: (inputValue: any, path: any) => {
                        return path.some(
                          (option: any) =>
                            option.label.toLowerCase().indexOf(inputValue.toLowerCase()) > -1,
                        );
                      },
                      onChange: (label: any, selectedOptions: any) => {
                        console.log(label, 'label');
                        console.log(selectedOptions, 'selectedOptions');
                      }

                    }}
                    rules={[{ required: true, message: `${item.title}必填` }]}
                  />

**Comment by chenshuai2144** [comment]
这种情况要自己操作 value，做个 hoc 组件吧

**Comment by lincong1498** [comment]
<ProFormCascader
              name="apostilleDepart"
              label=""
              fieldProps={{
                options: cascaderOptions,
                multiple: true,
               ###  showCheckedStrategy: SHOW_CHILD,
              }}
              width="lg"
              placeholder="请输入"
            />
