### ISSUE TITLE
🐛[BUG] antd升级到4.18.8后，时间选择器月份显示英文

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#9620]
### 🐛 bug 描述
antd升级到4.18.8后，时间选择器月份显示英文，降级到4.18.6后可以，已经设置的moment和antd的中文配置

### 📷 复现步骤
升级到antd 4.18.8 复现

### 🏞 期望结果
时间选择器月份展示中文

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本 3.5.20
- 浏览器环境 chrome
- 开发环境 win11

**Comment by 569202812** [comment]
> 一般是打包两份antd，yarn list 或者 npm ls 一下，你就能看到了

好的我试一下

**Comment by ahKevinXy** [comment]
我也是的你解决了吗

**Comment by 569202812** [comment]
> 我也是的你解决了吗

我回退后删除了所有依赖又重装，然后升级后就可以了
