### ISSUE TITLE
🐛[BUG] 登录失败

### ISSUE THREAD

**Issue by csm12s** [ant-design/ant-design-pro#9622]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/64699457/155316883-ef76d3f6-470f-459d-8382-bce559d8fd56.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
405 是 get 和 post 用错了，你看看 mock 里面是不是写错了。

**Comment by huguangju** [comment]
报同样的错，项目是 `yarn create umi myapp` 新生成，没改过代码直接运行的。
mock 和 service 里的都是 POST，看起来没问题。

**Comment by manfwh** [comment]
同样的错，npx create-umi myapp新创建的项目

**Comment by u10k** [comment]
使用 yarn start

**Comment by dongweiq** [comment]
我用的是 pro create myapp 创建的
然后 yarn install后使用yarn dev启动遇到相同的问题
看了上面u10k的评论使用 yarn start 启动后就没有问题了
确实有效，感谢
