### ISSUE TITLE
🐛[BUG] Expected "~`colorPalette" to be "~`colorpalette" function-name-case

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#9624]
Expected "~`colorPalette" to be "~`colorpalette" function-name-case

<img width="605" alt="image" src="https://user-images.githubusercontent.com/30397655/155437808-e63ccac8-b643-4ce8-a866-6fd546d4de84.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/30397655/155437815-9bcb15db-7973-4610-9cc6-a31b94424ede.png">

**Comment by leshalv** [comment]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/30397655/155439817-30586342-f98f-458c-aa7a-8a0d21924646.png">

我配置了规则，但还是没有生效。

**Comment by chenshuai2144** [comment]
直接关掉呢？

**Comment by vipycm** [comment]
"function-name-case": ["lower", { ignoreFunctions: ["colorPalette", "~`colorPalette"] }],
