### ISSUE TITLE
使用chrome，第一次登陆后，点击任意一个表单提交，都会出现 post failed to load response data

### ISSUE THREAD

**Issue by cnhans** [ant-design/ant-design-pro#963]
使用chrome，第一次登陆后，点击任意一个表单提交，都会出现 post failed to load response data，然后就会导致，出现304跳转的http://xxx.com/? ，再然后，就会刷新页面了，这种体验非常不好，每次用户登录都会出现这个问题，只要使用了一次的表单提交后，就不会了，很神奇的问题。
这个问题，在firefox里面就不会存在，请问，pro能否在兼容性上面再做点更新呢，谢谢！！

截图：
![image](https://user-images.githubusercontent.com/563838/36593490-d1087e58-18d4-11e8-8e32-b4e98a5cb284.png)

![image](https://user-images.githubusercontent.com/563838/36593505-dca86566-18d4-11e8-9962-f1b8c6ab6579.png)

![image](https://user-images.githubusercontent.com/563838/36593526-f399186a-18d4-11e8-8672-3ac0a5ca1c7d.png)

最后一张图是自动刷新了当前页。

是不是有什么cookies或者缓存被刷新了？
在firefox不存在这个问题。

这种自动刷新当前页面的体验真的很不好，有时提交数据的时候，其实是成功了，被刷新页面后，还以为不成功，又会再操作一次，导致操作重复了。

**Comment by mitoriko** [comment]
提交表单的时候
e.preventDefault();

**Comment by cnhans** [comment]
是的，已经解决了，谢谢。
