### ISSUE TITLE
5.0中为啥Cascader找不到multiple属性呢?

### ISSUE THREAD

**Issue by shixiaoxiang** [ant-design/ant-design-pro#9631]
### 🧐 问题描述

我做动态部门级联查询，现在只能单选，无法多选，multiple属性不生效

### 💻 问题截图
![image](https://user-images.githubusercontent.com/15920209/155706032-3f6a8943-7703-4f96-829e-4dff45ce14ac.png)
![image](https://user-images.githubusercontent.com/15920209/155706230-df90d485-bc43-48df-9951-578dbfdcaf3a.png)
![image](https://user-images.githubusercontent.com/15920209/155706258-da6044e4-ee1a-4e5f-bc68-b5cbaa2740f3.png)

**Comment by fangqibin** [comment]
看一下antd的版本。这个跟pro5.0没有多大关系

**Comment by shixiaoxiang** [comment]
好的 ，谢谢
