### ISSUE TITLE
🐛[BUG] 谷歌云 Firebase 9 sdk 不支持

### ISSUE THREAD

**Issue by Dragon201701** [ant-design/ant-design-pro#9632]
### 🐛 bug 描述

无法支持谷歌云 firebase sdk 9, 页面无法加载

### 📷 复现步骤

[Google Cloud Platform Firebase SDK 9](https://firebase.google.com/docs/web/setup?authuser=0&hl=zh)

### 🏞 期望结果

支持，页面正常加载。

### 💻 复现代码
```Javascript
import { initializeApp } from 'firebase/app';
const firebaseConfig = {
  ...
};
const app = initializeApp(firebaseConfig);
```

### © 版本信息

- Ant Design Pro 版本: 5
- umi 版本
- 浏览器环境 Chrome
- 开发环境 PC

### 🚑 其他信息

根据官网描述，sdk9 可以支持webpack打包器来减小APP的大小，能够更快的加载等等。

**Comment by chenshuai2144** [comment]
有报错吗？国内不好用这个，我没有处理过相关问题
