### ISSUE TITLE
[BUG] prolist和list无法在flex布局下实现ellipsis

### ISSUE THREAD

**Issue by aadog** [ant-design/ant-design-pro#9634]
### 🐛 bug 描述
如果title是这样，标题栏在flex下不会自动收缩省略实现ellipsis效果
` 
title: {
      dataIndex: 'title',
      render:(dom)=>{
      return <Text ellipsis={true}>{dom}</Text>
    }
},
`
![image](https://user-images.githubusercontent.com/18098725/156096571-9c0507e8-0002-44b2-8316-a8c568ad1a66.png)

### 📷 复现步骤

<Row wrap={true}>
          <Col className={Styles.newsPics} style={{marginTop: 20}}>
            <Carousel autoplay>
              <img src="assets/images/news1.jpg"/>
              <img src="assets/images/news1.jpg"/>
              <img src="assets/images/news1.jpg"/>
              <img src="assets/images/news1.jpg"/>
              <img src="assets/images/news1.jpg"/>
              <img src="assets/images/news1.jpg"/>
            </Carousel>
          </Col>
          <Col flex={1}>
            <ProList
              headerTitle={<Title level={5}>新闻公告</Title>}
              size={"small"}
              dataSource={
                [
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                  {title: "广东深圳：专精特新“小巨人”企业169家平均拥有发明专利超20项"},
                ]
              }
              split={true}

              metas={{
                title: {
                  dataIndex: 'title',
                },
                subTitle: {},
                type: {},
                content: {},
                actions: {},
                avatar: {
                  render: () => {
                    return (<span style={{color: "red"}}>●</span>)
                  }
                },
              }}
            />
          </Col>
        </Row>

左侧指定宽度右侧flex:1

### 🏞 期望结果

![image](https://user-images.githubusercontent.com/18098725/156097744-1f63bd38-fce4-42b4-a393-fbcd00d075ad.png)
如果给ant-pro-list-row-title加入min-width:0就可以达到这个效果，不过好像没地方指定

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
已经修复并发布咯

**Comment by FangLikai** [comment]
感谢您的通知，但我对此邮件内容不感兴趣。



在 2022-04-08 09:48:26，"陈帅" ***@***.***> 写道：

Closed #9634.
