### ISSUE TITLE
something went wrong之后，路由失效

### ISSUE THREAD

**Issue by nannan0109** [ant-design/ant-design-pro#9635]
### 项目中某段代码报错后，会出现Something went wrong，点击路由失效

报错之后，切换路由会发现 地址栏路由有变化，但是页面不刷新无变化。

截图如下
<img width="1046" alt="WeChat028383ccd081337f9fd2ffb38159a10a" src="https://user-images.githubusercontent.com/19622284/156120920-c2cc4b6d-afca-487b-9024-6e84ea0d5594.png">

**Comment by chenshuai2144** [comment]
报错了，只能刷新了。因为runtime 挂了，恢复不过来了
