### ISSUE TITLE
🧐[问题]动态菜单渲染不出来

### ISSUE THREAD

**Issue by dreamerjdwGit** [ant-design/ant-design-pro#9637]
### 🧐 问题描述

v5  complete模式
需求：一级菜单写死，再根据一级菜单向服务器请求对应子菜单，页面渲染出整合后的菜单

实现：
<img width="759" alt="image" src="https://user-images.githubusercontent.com/20147593/156307908-b5fdc89b-c8b3-47d0-a763-1881c3042823.png">

出现的问题：request请求在路由变化时成功请求并返回了整合后的菜单数据，但是左侧菜单栏并未渲染出来子菜单

**Comment by chenshuai2144** [comment]
设置一个params 来触发一下 request 的更新。默认是不会触发修改的。
