### ISSUE TITLE
SiderMenu的一个细节问题

### ISSUE THREAD

**Issue by EssenRoc** [ant-design/ant-design-pro#964]
以官方预览([https://preview.pro.ant.design](https://preview.pro.ant.design))为例，
步骤：
1.展开“列表页”
2.展开”搜索列表“
3.收缩”列表页“
4.展开”列表页“
当执行步骤4时，SiderMenu会有一闪的效果。
给人造成的视觉：展开”列表页“的同时”搜索列表“被收缩了。
我个人建议，步骤3时，即收缩”列表页“ 时 ”搜索列表“ 一起被收缩。或者干脆就不要收缩子项。

**Comment by ddcat1115** [comment]
fixed in https://github.com/ant-design/ant-design-pro/commit/cec0f45a8d84109638eb8996c71dde978093af84

不会收缩子项了（除非点击了其他根节点）
