### ISSUE TITLE
🐛[BUG]OpenAPI报错，不支持HTTP

### ISSUE THREAD

**Issue by bluef1ash** [ant-design/ant-design-pro#9644]
### 🐛 bug 描述

在config.ts中配置如下代码：

```typescript
openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'http://localhost:8080/v3/api-docs',
      projectName: 'swagger',
    },
  ],
```

启动报错

```shell
fetch openapi error: TypeError: Protocol "http:" not supported. Expected "https:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)

```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chen-kay** [comment]
[chenshuai2144/openapi2typescript/blob/700ff14119bd047e315d022a2f165e127ed9e822](https://github.com/chenshuai2144/openapi2typescript/blob/700ff14119bd047e315d022a2f165e127ed9e822/src/index.ts#L85)

[openapi2typescript#46](https://github.com/chenshuai2144/openapi2typescript/issues/46)
v1.4.1更新导致
先切换到v1.4.0版本或者使用https

**Comment by chenshuai2144** [comment]
fixed in https://github.com/chenshuai2144/openapi2typescript/issues/46
