### ISSUE TITLE
🐛[BUG]文档配置路由页面打不开

### ISSUE THREAD

**Issue by calmchang** [ant-design/ant-design-pro#9645]
### 🐛 bug 描述

在 配置-routes板块: https://pro.ant.design/zh-CN/config/config#routes
有一个 路由配置的超链接跳转至：https://pro.ant.design/zh-CN/config/docs/routing
目前是打不开的

**Comment by tianyuan233** [comment]
这个已经 fix 了https://github.com/ant-design/ant-design-pro-site/pull/635
@chenshuai2144
