### ISSUE TITLE
🧐[问题]在config.ts中配置了define，在其他文件中怎样使用

### ISSUE THREAD

**Issue by bluef1ash** [ant-design/ant-design-pro#9646]
如题，例如在app.ts中直接使用常量，tslint报错`cannot find name`

**Comment by bluef1ash** [comment]
我明白了

**Comment by mayhai** [comment]
所以怎么在其他页面调用这个常量呢

**Comment by bluef1ash** [comment]
> 所以怎么在其他页面调用这个常量呢

在 `app.ts` 的 `define` 块定义常量后，还要在 `.eslintrc.js` 的 `globals` 中定义常量，最后就可以在其他页面中直接用了，想要eslint不提示错误，还要在 `typing.d.ts` 里面声明该常量。

**Comment by mayhai** [comment]
> > 所以怎么在其他页面调用这个常量呢
> 
> 在 `app.ts` 的 `define` 块定义常量后，还要在 `.eslintrc.js` 的 `globals` 中定义常量，最后就可以在其他页面中直接用了，想要eslint不提示错误，还要在 `typing.d.ts` 里面声明该常量。

多谢，可以了
