### ISSUE TITLE
🧐[问题]:global全局样式不生效

### ISSUE THREAD

**Issue by strongyc** [ant-design/ant-design-pro#9648]
### 🧐 问题描述
在global.less中定义

:global {
  .title-block {
    padding: 14px;
    font-size: 16px;
    letter-spacing: 1px;
    background: #ddffff;
    border-left: 6px solid #2196f3;
  }
  .backcolor {
    color: @primary-color;
    font-size: 30px;
  }
}
 在页面中使用  <div className='backcolor'>测试</div>样式不生效
<!--

**Comment by chenshuai2144** [comment]
提升一下样式优先级的。

https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity
