### ISSUE TITLE
ProFormDatePicker组件月份显示的是英文🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9649]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/20655248/157149577-6a432fd5-4f56-46ad-b9b7-dde8430beb4d.png)

![image](https://user-images.githubusercontent.com/20655248/157149615-932033e9-c6fe-41fb-83d6-7df71d40742b.png)

### 📷 复现步骤

正常使用

### 🏞 期望结果

ProFormDatePicker组件月份显示的是中文

### 💻 复现代码

版本如下
![image](https://user-images.githubusercontent.com/20655248/157149797-fba00a53-f6cb-4f67-b707-7a08dc8f977d.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://ant.design/components/config-provider-cn/#为什么我使用了-ConfigProvider-locale，时间类组件的国际化还有问题？

```
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
```
