### ISSUE TITLE
umi  没有导出useDispatch

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-pro#9650]
### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/27960630/157156639-aa5bd31c-792d-4564-b619-ba174e5b4f55.png)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/27960630/157156660-eba4fd2b-c821-4207-844e-b373f4fbb54e.png">
  我本地 没有单独安装dva

### © 版本信息
 "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.52.0",
    "@ant-design/pro-layout": "^6.32.0",
    "@ant-design/pro-table": "^2.61.0",
    "@umijs/route-utils": "^2.0.0",
    "ahooks": "v2.10.12",
    "antd": "^4.17.0",
    "classnames": "^2.3.0",
    "jsencrypt": "^3.2.1",
    "json-stable-stringify": "^1.0.1",
    "lodash": "^4.17.0",
    "md5": "^2.3.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-contexify": "^5.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "umi": "^3.5.0",
    "umi-request": "^1.4.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.8.0",
    "@umijs/openapi": "^1.3.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/plugin-openapi": "^1.3.0",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^1.8.17",
    "@umijs/yorkie": "^2.0.5",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "enzyme": "^3.11.0",
    "eslint": "^7.32.0",
    "express": "^4.17.0",
    "gh-pages": "^3.2.0",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "swagger-ui-react": "^3.52.0",
    "typescript": "^4.5.0",
    "umi-serve": "^1.9.10"
  },
- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/plugins/plugin-dva

需要打开这个

**Comment by lovesL** [comment]
> https://umijs.org/zh-CN/plugins/plugin-dva
> 
> 需要打开这个

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/27960630/157175015-72b2f718-6123-49f0-ba8a-0e7674093b05.png">
 这个是官方的配置啊  默认不是就开的嘛  现在还是没导出


export default defineConfig({
  hash: true,
  antd: {},
  history: {
    type: 'browser',
  },
  dva: {
    immer: true,
    hmr: false,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    // 'root-entry-name': 'variable',
    'primary-color': '#109c98',
    'border-radius-base':'4px',
    'layout-sider-background':'#026062',
    'menu-inline-submenu-bg':'#026062',
    'menu-bg': '#026062',
    'menu-item-color': '#02f6d6',
    'menu-highlight-color': '#fff',
    'menu-item-active-bg': '#08b9aa',
    'menu-dark-bg': '#026062',
    'menu-dark-submenu-bg': '#09a19d',
    'menu-dark-inline-submenu-bg': '#026062',
    'menu-dark-item-active-bg': '#0bcac5',
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  publicPath:defaultSettings.publicPath,
  base:defaultSettings.basePath,
  // Fast Refresh 热更新
  fastRefresh: {},
  nodeModulesTransform: {
    type: 'none',
  },
  // mfsu: {},
  webpack5: {},
  exportStatic: {},
});

**Comment by lovesL** [comment]
@chenshuai2144
