### ISSUE TITLE
🐛[BUG] Couldn't find any versions for "@ant-design/pro-utils" that matches "1.35.2"

### ISSUE THREAD

**Issue by JennyLeung030** [ant-design/ant-design-pro#9651]
### 🐛 bug 描述

When I using "yarn upgrade --latest" for upgrade the dependencies, but the terminal will tell me error.
![image](https://user-images.githubusercontent.com/51438629/157161993-b18f40b1-af0c-4905-88f9-b1524aae276a.png)

### 📷 复现步骤

enter "yarn upgrade --latest" in terminal 

### 🏞 期望结果

No need to choose the  "@ant-design/pro-utils" version in the upgrade progress

### 💻 复现代码

yarn upgrade --latest

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本 : 3.5.0
- 浏览器环境 : chrome
- 开发环境 : windows 10

**Comment by chenshuai2144** [comment]
看看相关的issue，里面有解释

**Comment by JennyLeung030** [comment]
> 看看相关的issue，里面有解释

我暫時看不見有人和我一樣在更新過程中"@ant-design/pro-utils"找不到"1.35.2"而要用家選擇其他版本的問題
