### ISSUE TITLE
🐛[BUG]修改主题色登录页面和部分组件不生效

### ISSUE THREAD

**Issue by jinhgg** [ant-design/ant-design-pro#9653]
### 🐛 bug 描述
1. 创建一个新项目
2. 仅修改config/defaultSettings.ts中的primaryColor
3. 然后npm start

登录页不生效
![0f53f26cd63db821e2457a0922e0d56](https://user-images.githubusercontent.com/33146207/157219377-a8f7e77a-853b-4637-b7f4-79851da45ed0.png)
部分组件不生效
![edd66daf98cbe729e648802f374735d](https://user-images.githubusercontent.com/33146207/157219413-74f70a31-7b79-444e-b241-a0e1cfc8b42a.png)

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本: [3.5.0]
- 浏览器环境 [edge, chrome]
- 开发环境 [windows 10]

**Comment by Rock-Moon** [comment]
参考这个链接[https://ant-design.gitee.io/docs/react/customize-theme-cn](url)
在config.ts设置
`
  theme: {
    'primary-color': '#1DA57A',
  },
`

**Comment by jaxsh** [comment]
> 参考这个链接https://ant-design.gitee.io/docs/react/customize-theme-cn 在config.ts设置 `theme: { 'primary-color': '#1DA57A', },`

hover相关的组件和控件边框都不会变化。目前可以把默认蓝色的色号替换掉(blue-base': '#52c41a',)，效果非常完美
<img width="283" alt="微信图片_20220311231146" src="https://user-images.githubusercontent.com/86786042/157896540-8a1c31bb-fc31-4a34-b4e6-2aac570d9fc4.png">

**Comment by zhouwenwu30** [comment]
极有可能是在项目组件中引入了antd.css，引入后编译的时候会把antd.css整个编译一遍，这里面全是默认颜色，这样会导致自定义的主题色被覆盖。
`import 'antd/dist/antd.css';`
