### ISSUE TITLE
👑 [需求] ProForm 有规划使用 jsonschema 吗？

### ISSUE THREAD

**Issue by zhangchuangye** [ant-design/ant-design-pro#9654]
### 🥰 需求描述

1. 对于大部分中后台项目表单是必不可少的，目前使用 pro ant.design 业务代码会出现较多冗余的表单代码

### 🧐 解决方案

1. 是否可以基于 jsonschema 动态生成表单？https://rjsf-team.github.io/react-jsonschema-form/

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/schema-form

看这个
