### ISSUE TITLE
请问怎么样在RunTimeLayoutConfig的menu加载远程数据时，动态创建路由，而不是在routes.ts里固定配置？

### ISSUE THREAD

**Issue by whiteshader** [ant-design/ant-design-pro#9655]
请问怎么样在RunTimeLayoutConfig的menu加载远程数据时，动态创建路由，而不是在routes.ts里固定配置？

**Comment by chenshuai2144** [comment]
路由是不能动态的，只能动态菜单。


你可以把所有的路由都配置出来，然后动态菜单选择是否能访问到

**Comment by whiteshader** [comment]
访问是可以的，但是后台做不了像VUE一样的动态修改URL
