### ISSUE TITLE
🐛[BUG]ant desigin pro V5使用 @react-pdf/renderer出现报错: Unhandled Rejection (TypeError): Cannot read properties of undefined

### ISSUE THREAD

**Issue by gaspire** [ant-design/ant-design-pro#9657]
### 🐛 bug 描述

ant desigin pro V5使用 @react-pdf/renderer出现报错: Unhandled Rejection (TypeError): Cannot read properties of undefined

### 📷 复现步骤
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/49259119/157575393-0a3d32b0-41ca-43a8-93ca-647c6c445ffe.png">

### 🏞 期望结果
期望运行正常

### 💻 复现代码
`
import React from 'react';
import { Button } from 'antd';
import { PageContainer } from '@ant-design/pro-layout';
import { useLocation } from 'umi';
import DetailContent from './components/detail-content';
import { Page, Document, StyleSheet } from '@react-pdf/renderer';

const DetailPage: React.FC = () => {
  const location: any = useLocation();
  const id = location?.query.id;

  const PdfDoc = () => (
    <Document>
      <Page size="A4">
        <DetailContent id={id || 0}/>
      </Page>
    </Document>
  );

  return (
    <PageContainerextra={[
      <Button key="1" onClick={() => {
        //ReactPDF.render(<PdfDoc />, `${__dirname}/example.pdf`);
      }}>生成PDF报告</Button>,
    ]}>
       
    </PageContainer>
  );
}

export default DetailPage;
`
### © 版本信息

- Ant Design Pro 版本: 5.0
- umi 版本 3.5.21
- 浏览器环境 chrome
- 开发环境 [mac OS]

**Comment by chenshuai2144** [comment]
关掉 mfsu 再用吧。这种特殊的包支持的比较差

**Comment by gaspire** [comment]
关掉 mfsu 不起作用
