### ISSUE TITLE
ProTable中的columns的有个搜索下拉项select 要给这个select动态的赋值initialValue🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9658]
### 🐛 bug 描述

使用ProTable组件 要有个select下拉筛选项 下拉数据从接口获取的， 要给这个selec组件赋初始值 发现获取下拉列表接口一直不断调用 请看看是哪个地方写错了

![image](https://user-images.githubusercontent.com/20655248/157604626-95ac97e4-aef9-4556-b3a8-5a2840b4435f.png)
![image](https://user-images.githubusercontent.com/20655248/157604727-652eb3d0-8bdc-40ab-a4b7-46818921792f.png)

![image](https://user-images.githubusercontent.com/20655248/157604810-811bde10-8dbe-427c-8346-3d19fffaebed.png)
发现一直不断调用接口
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by 1247748612** [comment]
用valueType: 'select'

https://procomponents.ant.design/components/schema#valuetype-%E5%88%97%E8%A1%A8

**Comment by lianggh98** [comment]
# 不知道有没有更好的解决方案
![image](https://user-images.githubusercontent.com/63761745/158089122-c931fbe3-9b3b-493f-ae09-f5f3a3a8cc98.png)
![image](https://user-images.githubusercontent.com/63761745/158089162-f96ee54e-aed5-4a13-bc93-11091b957e2c.png)

**Comment by chenshuai2144** [comment]
select + request 很完美了。

自己写很容易写出死循环的。
