### ISSUE TITLE
ProTable组件中的columns的initialValue怎么获取select下拉数据request列表的第一个的值 🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9659]
### 🐛 bug 描述
ProTable中有个下拉select搜索项，要用initialValue动态获取request下拉列表数组的第一个value值要怎么做 
![image](https://user-images.githubusercontent.com/20655248/157613561-f2b6cfd4-392f-4293-9ed2-37f7e28e38d5.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
只能等request 回来之后用 form.set  设置回去了，暂时没有更优雅的办法。
