### ISSUE TITLE
🧐[问题] : (0 , _umi.useModel) is not a function (please provide an example of testing app using useModel !!)

### ISSUE THREAD

**Issue by Bourhjoul** [ant-design/ant-design-pro#9660]
### 🧐 问题描述
I'm trying to test a component using useModel but I can't,it gives me this :
TypeError: (0 , _umi.useModel) is not a function

### 💻 示例代码

![code-usemodel](https://user-images.githubusercontent.com/66276688/157677322-50e1327e-4666-4327-b47f-9d62d82e868f.png)

### 🚑 其他信息
![usemodel](https://user-images.githubusercontent.com/66276688/157675728-43a326a6-b392-4efa-b6f6-253e6530aae1.png)

**Comment by chenshuai2144** [comment]
暂时还不支持测试，让你失望了

**Comment by Bourhjoul** [comment]
@chenshuai2144 so the only solution is to use another state management library?

**Comment by chenshuai2144** [comment]
ref to https://github.com/ant-design/ant-design-pro/issues/9206
