### ISSUE TITLE
🧐[问题]ProTable需要什么格式的数据？以及Columns设置有什么要求吗？

### ISSUE THREAD

**Issue by zhang-hongshen** [ant-design/ant-design-pro#9661]
## 我是一个Ant Design Pro的新手，我不知道怎样才算往ProTable里面传参成功，我已经尝试过网上的很多方法了，都没有效果。我能够获取从后台来的数据，为了方便展示，这里是使用Postman请求的结果
![image](https://user-images.githubusercontent.com/51166261/157711518-8075ad07-4d15-4697-882f-18a2850d5b9d.png)
## 下面是我的数据定义，和官网给的是一样的
![image](https://user-images.githubusercontent.com/51166261/157710360-e1976b27-4b62-4631-95a6-3d170c2c729c.png)
## 下面是我请求后台的函数
![image](https://user-images.githubusercontent.com/51166261/157710149-2b18800e-1f66-423f-a509-e03247a35272.png)
## 下面是我在ProTable传入的参数
![image](https://user-images.githubusercontent.com/51166261/157710953-d4a6d0f7-f318-44a5-aa02-fcca437a2e88.png)

**Comment by 1247748612** [comment]
这里看看 https://procomponents.ant.design/components/table#%E6%9F%A5%E8%AF%A2%E8%A1%A8%E6%A0%BC

**Comment by chenshuai2144** [comment]
demo 里面都有的哦
