### ISSUE TITLE
🐛[BUG]主题色配置相关问题

### ISSUE THREAD

**Issue by jaxsh** [ant-design/ant-design-pro#9665]
### 🐛 bug 描述

1：不使用SettingDrawer，无法自定义主题色
2：使用SettingDrawer，自定义主题色后，刷新页面，主题变回默认值
3：ant 定制主题色，hover相关css未更新

### 📷 复现步骤
问题1步骤
使用脚手架安装后
1：注释src/app.tsx如下代码
    // childrenRender: (children, props) => {
    //   // if (initialState?.loading) return <PageLoading />;
    //   return (
    //     <>
    //       {children}
    //       {!props.location?.pathname?.includes('/login') && (
    //         <SettingDrawer
    //           enableDarkTheme
    //           settings={initialState?.settings}
    //           onSettingChange={(settings) => {
    //             setInitialState((preInitialState) => ({
    //               ...preInitialState,
    //               settings,
    //             }));
    //           }}
    //         />
    //       )}
    //     </>
    //   );
    // },
2：修改config/defaultSettings
primaryColor: '#52c41a',
3：重启服务后，主题色未更新（尝试过关闭mfsu以及yarn build）只要SettingDrawer注释，primaryColor就不会生效，不注释primaryColor有用。

问题2步骤
1：打开https://preview.pro.ant.design/
2：配置主题色
3：刷新页面

问题3步骤
1：使用脚手架安装后
2：修改config/config.ts
  theme: {
    'root-entry-name': 'variable',
    // 'blue-base': '#52c41a',
    'primary-color': '#52c41a',
  },
3：重启服务后，主题色有变化，但文本框边框，以及hover颜色还是默认，只有配置了blue-base才能正确展示

### 🏞 期望结果

问题1：不使用SettingDrawer，也能通过修改defaultSettings中primaryColor修改主题色
问题2：刷新后保存已配置的主题色
问题3：配置主题色后能使所有组件都使用此主题色

### © 版本信息

- Ant Design Pro 版本: [5.2]
- umi 版本[3.5.21]
- 浏览器环境 [99.0.4844.51（正式版本） （64 位）]
- 开发环境 [windows 11]

### 🚑 其他信息

<img width="283" alt="微信图片_20220311231146" src="https://user-images.githubusercontent.com/86786042/157895492-6520f426-b366-46c8-bcea-30fafe3d391e.png">

**Comment by zhangwen1932** [comment]
同遇到

**Comment by 756370340** [comment]
同上

**Comment by wangJacker** [comment]
看似已经修改好了但是 点击以后会回复默认的主题 深蓝色

**Comment by 756370340** [comment]
楼主 第二个问题我是写了个缓存解决的 你可以试下 onSettingChange 里写入缓存

**Comment by wangJacker** [comment]
参考https://github.com/ant-design/ant-design-pro/issues/9653 
配置： theme: {
        'primary-color': defaultSettings.primaryColor, // 主题配置
        'root-entry-name': 'variable',
        "blue-base": "#f5711e" // 这里修改为自己相应的主题色问题得以解决
    },

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/9d8b711605a280d4339f29ab2dfb83851061ef98/config/config.ts#L40-L45

这个看一下，如果不想改，可以覆盖掉 SettingDrawer 的配置。


`< SettingDrawer setting={primaryColor:"XXX"}`

**Comment by aoxiang78** [comment]
@jaxsh 在不使用childrenRender的情况下如何 app.ts文件中 调用ConfigProvider.config来实现的，
`  
      ConfigProvider.config({
          theme: {
            primaryColor: '#f00',
            infoColor: '#00f',
            errorColor: '#000'
          }
        }); `

调用ConfigProvider.config方法来配置主题色的方式，这样才可以完整支持antd支持的所有[风格](https://github.com/ant-design/ant-design/blob/master/components/config-provider/context.tsx)配置，

最终方案： @chenshuai2144 能否在SettingDrawer中支持所有theme风格配置？如可以我可以提供PR，假如不适合在SettingDrawer中支持所有风格配置，那原因也能否分享下。

**Comment by maokty** [comment]
https://github.com/ant-design/ant-design-pro/blob/683f75159d06f3dab45f4d8a1f92d6fb6c2f8f08/src/app.tsx#L90

注释掉 这个登录页路径判断 就好了；

**Comment by lcc908** [comment]
同样遇到

**Comment by lcc908** [comment]
> ConfigProvider



> @jaxsh在不使用childrenRender的情况下如何调用app.ts文件中调用ConfigProvider.config来实现的， ` ConfigProvider.config({ theme: { primaryColor: '#f00', infoColor: '#00f', errorColor: '#000' } });`
> 
> 调用ConfigProvider.config方法来配置主题色支持的，这样才可以完整支持的所有[风格](https://github.com/ant-design/ant-design/blob/master/components/config-provider/context.tsx)配置方式，
> 
> 最终方案：@@@ SettingDrawer中可以配置吗？如果我可以PR，有些配置不适合在SettingDrawer中支持所有的配置，那个原因也可以提供下分享。

问一下，ConfigProvider 是在哪里配置？app.jsx里面吗

**Comment by maokty** [comment]
@lcc908 config.ts

**Comment by lcc908** [comment]
> 

![image](https://user-images.githubusercontent.com/32050051/163556738-ca3ecb3c-2471-44f0-851b-0664384deb71.png)
不是这样吧。。。。

**Comment by lcc908** [comment]
> @lcc908 config.ts

额，能说的详细点吗

**Comment by lcc908** [comment]
> @lcc908配置文件



> 同遇到，头疼 我也是屏蔽SettingDrawer，primaryColor就失效

请问，最终解决了吗

**Comment by lcc908** [comment]
> @lcc908配置文件

能说的详细点么

**Comment by rumunanfeng** [comment]
此问题可以通过在theme中配置blue-base': '#52c41a'解决
![Uploading image.png…]()

**Comment by vanstline** [comment]
同样的问题  本地保存后 热更新是显示正常 一但强制刷新页面就会失效
@chenshuai2144  我们的需求都是不想使用  SettingDrawer

**Comment by YaYaPao** [comment]
我也碰到了这个问题，发现使用 css module，配置 primaryColor 等方式，重新刷新后都被原样式覆盖了，请问下有什么解决方案吗？

**Comment by aoxiang78** [comment]
> > ConfigProvider
> 
> > @jaxsh在不使用childrenRender的情况下如何调用app.ts文件中调用ConfigProvider.config来实现的， ` ConfigProvider.config({ theme: { primaryColor: '#f00', infoColor: '#00f', errorColor: '#000' } });`
> > 调用ConfigProvider.config方法来配置主题色支持的，这样才可以完整支持的所有[风格](https://github.com/ant-design/ant-design/blob/master/components/config-provider/context.tsx)配置方式，
> > 最终方案：@@@ SettingDrawer中可以配置吗？如果我可以PR，有些配置不适合在SettingDrawer中支持所有的配置，那个原因也可以提供下分享。
> 
> 问一下，ConfigProvider 是在哪里配置？app.jsx里面吗

是的，在app.jsx里的
childrenRender 》SettingDrawer》onSettingChange 更新当前配置，同时缓存至浏览器中
 childrenRender 》SettingDrawer》settings 这里获取浏览器缓存里保存的存配置，

**Comment by xtay** [comment]
同遇到删除SettingsDrawer后，主题配置就失效的问题。

**Comment by soeasyjx** [comment]
有解决方案么，我也遇到了这个问题

**Comment by soeasyjx** [comment]
有解决方案么，我也遇到 这个问题，设置config.ts-theme '@primary-color': '#c63136'  只有部分颜色变了，像输入法hover 还是蓝色，搞啥么子搞

**Comment by suqingdong** [comment]
> 此问题可以通过在theme中配置blue-base和primary-color一致来解决，比如 blue-base': '#52c41a' ![image](https://user-images.githubusercontent.com/37805363/164964924-ecc13d39-6797-49ad-b42f-6431d0b733d6.png)

this works!

**Comment by lazyermax** [comment]
这个问题解决了吗？重新获取了V5代码好像依然存在

**Comment by mahalo777** [comment]
same here
