### ISSUE TITLE
🐛[BUG] ProTable在手机端导致Table数据无法正常显示

### ISSUE THREAD

**Issue by heyzoeys** [ant-design/ant-design-pro#9666]
### 🐛 bug 描述

ProTable在手机端显示不正常， 导致Table数据无法正常显示。  

### 📷 复现步骤
F12 移动端展示。

### © 版本信息
官网最新版本
- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/93904235/158009709-0b1ce079-f9f4-40ad-bf1b-900c8b12e56f.png)

**Comment by chenshuai2144** [comment]
移动端要自己想办法处理。官方提供的只能是凑合的方案
