### ISSUE TITLE
🧐[问题]通过界面安装流程编辑器时报错Execute task error: Error: Command failed:。

### ISSUE THREAD

**Issue by jiagouview** [ant-design/ant-design-pro#9668]
### 🧐 问题描述

Execute task error: Error: Command failed: npm install -d @ant-design/icons@^4.0.0 @antv/data-set@^0.11.0 bizcharts@^3.5.3-beta.0 bizcharts-plugin-slider@^2.1.1-beta.1 gg-editor@^2.0.2 moment@^2.22.2 numeral@^2.0.6 react-fittext@^1.0.0 --registry=https://registry.npm.taobao.org --save

**Comment by fangqibin** [comment]
用淘宝npm试一下

**Comment by lianghong1234** [comment]
Execute task error: Error: Command failed: yarn add @ant-design/charts@^1.2.11 numeral@^2.0.6 --registry=https://registry.npm.taobao.org
