### ISSUE TITLE
升级 ant-design-pro 到 1.1.0 版本后 Route 组件无法渲染，回退到 1.0.1 版本后问题不存在

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design-pro#967]
#### 1. 项目依赖
- dva "^2.1.0"
- roadhog "^1.2.1"

#### 3. yarn start 开始调试，Switch 组件下面的 Route 没有渲染，控制台无异常日志
![image](https://user-images.githubusercontent.com/2703455/36627942-488f2bd8-1985-11e8-8733-3f9f530b09b4.png)

#### 5. yarn start 开始调试，应用正常渲染
![image](https://user-images.githubusercontent.com/2703455/36627988-1a8ad59c-1986-11e8-8d67-74189edace9e.png)

**Comment by chenshuai2144** [comment]
meunData？

**Comment by xiaosongxiaosong** [comment]
这个问题找到原因了：
#### 1. 检查 yarn.lock 文件发现  ant-design-pro 升级到 1.1.0 版本后多了了 path-to-regexp@^2.1.0 和 url-polyfill@^1.0.10:

#### 2. path-to-regexp@2.1.0 版本的匹配所有 url 的方式有变更

> No wildcard asterisk (\*) - use parameters instead ((.\*))

[变更说明](https://www.npmjs.com/package/path-to-regexp#compatibility-with-express--4x)

#### 3. React Router 也使用了path-to-regexp

#### 4. 我的 RouterConfig 中恰好使用到了匹配所有 url
```jsx
function RouterConfig({ history, app }) {
  return (
    <Router history={history}>
      <Switch>
        <Route path="/" exact component={Loading} />
        <Route path="/guide" render={props => <GuideLayout {...props} app={app} />} />
        <Route path="*" render={props => <ClientLayout {...props} app={app} />} />
      </Switch>
    </Router>
  );
}
```

#### 5. 由于 `path="*"` 已经不能匹配所有 url，导致 ClientLayout 不会被 render，也就导致了我的问题

#### 6. 将 `path="*"` 修改成 `path="(.*)"` 后页面正常渲染
