### ISSUE TITLE
Needed help regarding pushing the app into production.

### ISSUE THREAD

**Issue by Ditou007** [ant-design/ant-design-pro#9671]
We have followed the below process to build the app ->

1) npm run build -> which creates a dist folder 
2) we upload the dist folder content to server and configure the same to nginx(as given in https://beta-pro.ant.design/docs/deploy) 
3) we tried to access the deployed application and we are able to access login page and after successful authentication, we still stuck in login page.

Looks like routing issue.
Could someone please help here ?

We use Antd pro v4.

**Comment by chenshuai2144** [comment]
You need to provide more detailed error information, this information is too simple
