### ISSUE TITLE
🧐[问题]非函数组件如何获取initialState中的值

### ISSUE THREAD

**Issue by dreamerjdwGit** [ant-design/ant-design-pro#9673]
### 🧐 问题描述

问题：initialState中保存了一些全局数据，现在想在非函数组件中去拿到这些数据，但是useModel是hooks，无法在普通函数中去调用来获取，请问应该怎么去做。或者说这类全局数据应该使用何种方式去存储使用。

**Comment by dong136279559** [comment]
请问，如果我想在普通js，或者ts文件中使用model中的值该如何使用呢。

**Comment by chenshuai2144** [comment]
上下文一定要有的。

如果要使用可以试试 **事件模式**

https://zhuanlan.zhihu.com/p/108447200

**Comment by AtLastDopamine** [comment]
> 上下文一定要有的。
> 
> 如果要使用可以试试 **事件模式**
> 
> https://zhuanlan.zhihu.com/p/108447200

我也存在这个问题，尤其是请求拦截器中要使用 `model` 的状态

我没有明白 **事件模式** 有什么优势，不知道是不是我思路有问题，期待您的回答
如果我使用 **事件模式**，获取同一个 `model` 的状态就要定义 2 个事件，一个是获取一个是返回数据，有点类似于请求；
或者找个中转，例如 `Storage` 或 直接挂在 `Window` 上，感觉这 2 个方法在 `model` 多后，都不好维护

**Comment by gdutleung** [comment]
我也遇到一样的问题，登录之后我的token存在 initialState 里面，但是我当想在 interceptor 中把 token 加到 request header 的时候，我发现无法获取 initialState 。

**Comment by chenshuai2144** [comment]
windows 上挂一个

**Comment by wubiao1024** [comment]
> 我也遇到一样的问题，登录之后我的token存在 initialState 里面，但是我当想在 interceptor 中把 token 加到 request header 的时候，我发现无法获取 initialState 。

我也是这个问题，该怎么解决
