### ISSUE TITLE
🧐[问题]动态菜单每次更新 都会闪一下 出现骨架屏

### ISSUE THREAD

**Issue by dreamerjdwGit** [ant-design/ant-design-pro#9675]
### 🧐 问题描述
ant pro v5 
complete模式

使用了pro-layout插件

主菜单每次都会闪一下，出现骨架屏，这个体验，不太好，有方法能改善吗
![tOFtsW9TVv](https://user-images.githubusercontent.com/20147593/158590545-b104c8ce-c827-4d79-94ea-289bfff117d6.png)

### 💻 示例代码

使用了pro-layout插件，根据一级路由获取该路由下的所有菜单，动态更新menuData，
但是每次页面交互上都会闪一下，出现骨架屏，有方法可以改善这个闪一下的交互体验吗

`menu: {
      params: {
        pathname: history?.location?.pathname,
      },
      request: async (params) => {
        const pathname = params?.pathname;
        // 路由变更，重新整合动态菜单目录
        const menuData = await reloadCurrentUserMenus(pathname, initialState?.menuData);
        if (initialState.menuData) {
          // eslint-disable-next-line
          initialState.menuData = menuData;
        }
        setInitialState((s: any) => ({ ...s, menuData }));
        return initialState?.menuData;
      },
    },`

**Comment by chenshuai2144** [comment]
menu.loading 设置成false ，不要更新就可以了

**Comment by caimingyi484** [comment]
> menu.loading 设置成false ，不要更新就可以了

异步动态设置菜单，路由是不是要事先全部都做好，如果超过路由配置的菜单，显示空页面？

**Comment by lcc908** [comment]
> loading

同问

**Comment by pkaq** [comment]
> > menu.loading 设置成false ，不要更新就可以了
> 
> 异步动态设置菜单，路由是不是要事先全部都做好，如果超过路由配置的菜单，显示空页面？

是的，动态路由不支持哦，路由会让umi知道应该编译哪些文件，如果没有路由那么 umi 不会编译文件了。你最好预先设置好所有的路由
