### ISSUE TITLE
🧐[问题]调试代码时在source中无法搜到.tsx文件，只有less文件

### ISSUE THREAD

**Issue by SilentRio** [ant-design/ant-design-pro#9679]
### 🧐 问题描述

使用umi 脚手架搭建ant-design-pro+ts项目，没有修改配置，但是想调试代码时在source中无法搜到.tsx文件，只有less文件

### 🚑 其他信息
官方提供的调试说明文档：
<img width="1622" alt="官方调试文档" src="https://user-images.githubusercontent.com/19779285/158743071-2179cdc0-7777-45ea-b49b-a9c38edc9d3c.png">

本地的现象：
<img width="1185" alt="soureMap" src="https://user-images.githubusercontent.com/19779285/158742699-de2eadd2-c71e-41cb-92e5-3c3a49e4196d.png">

**Comment by chenshuai2144** [comment]
名字给变了 ，mfsu会帮你预编译一下。你最好用debuger 或者 console 定位一下。

如果觉得难受可以关掉 mfsu 来debug。
