### ISSUE TITLE
关于部署生产环境，proxy代理🧐[问题]

### ISSUE THREAD

**Issue by lcc908** [ant-design/ant-design-pro#9680]
### 🧐 问题描述
部署线上环境，接口前面的/api 如何处理？

我本地通过proxy代理来实现了联调，现在每个接口前面都加了‘/api’，没任何问题，但是实际接口前面是没有/api字段的啊，
如果我直接打包部署到线上接口岂不是会直接404？身边的人的说不用管，让后台配置一下，有的人说配置环境变量等等，可惜没有找到有关的示例，劳驾解惑，我应该怎么做
### 💻 示例代码
1，这是我的proxy.js文件配置：
![image](https://user-images.githubusercontent.com/32050051/158771300-28dd8029-513b-4e4e-a5a2-6c02d37d2c4b.png)
2，这是我的接口
![image](https://user-images.githubusercontent.com/32050051/158771477-bd3ff507-e604-42ee-b318-fe8e5cd0174b.png)

### 🚑 其他信息
我这边部署线上之后就不存在跨域问题了，接口前面还带着/api 肯定会有问题的，如果您有好的解决办法，能不能贴一下代码看看呢
示例

**Comment by lcc908** [comment]
目前解决办法是在 请求拦截前做的：
![image](https://user-images.githubusercontent.com/32050051/158784466-8d754b74-1c6d-4904-8275-2ac6fcf73ab0.png)

请问各位有没有更好的办法？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/zh-CN/docs/deploy

看这个，你需要让容器帮你配置

**Comment by lcc908** [comment]
> https://pro.ant.design/zh-CN/docs/deploy
> 
> 例如 nginx
> 
> ```
>     location / {
>         # 用于配合 browserHistory使用
>         try_files $uri $uri/ /index.html;
> 
>         # 如果有资源，建议使用 https + http2，配合按需加载可以获得更好的体验
>         # rewrite ^/(.*)$ https://preview.pro.ant.design/$1 permanent;
> 
>     }
>     location /api {
>         proxy_pass https://ant-design-pro.netlify.com;
>         proxy_set_header   X-Forwarded-Proto $scheme;
>         proxy_set_header   X-Real-IP         $remote_addr;
>     }
> ```
> 
> 看这个，你需要让你陪陪

谢谢

**Comment by lcc908** [comment]
> https://pro.ant.design/zh-CN/docs/deploy
> 
> 比如 nginx
> 
> ```
>     location / {
>         # 用于配合 browserHistory使用
>         try_files $uri $uri/ /index.html;
> 
>         # 如果有资源，建议使用 https + http2，配合按需加载可以获得更好的体验
>         # rewrite ^/(.*)$ https://preview.pro.ant.design/$1 permanent;
> 
>     }
>     location /api {
>         proxy_pass https://ant-design-pro.netlify.com;
>         proxy_set_header   X-Forwarded-Proto $scheme;
>         proxy_set_header   X-Real-IP         $remote_addr;
>     }
> ```
> 
> 看这个，你需要让容器帮你配置

谢谢，这一块 只需要让我们后台人员来处理吧，毕竟前端不涉及部署

**Comment by xiahller** [comment]
蹲环境配置

**Comment by afresh** [comment]
@xiahller `nginx` 配置

```bash
server {
	# 有关自签ssl证书可参见 https://cloud.tencent.com/developer/article/1160294
	listen 44342 ssl; #如果不需要ssl地址，可不加ssl
	listen [::]:44342 ssl; #如果不需要ssl地址，可不加ssl
	include snippets/self-signed.conf; #如果不需要ssl地址，可不加此行
	include snippets/ssl-params.conf; #如果不需要ssl地址，可不加此行

	server_name 192.168.20.141; # 服务ip或域名

	# gzip config
	gzip on;
	gzip_min_length 1k;
	gzip_comp_level 9;
	gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
	gzip_vary on;
	gzip_disable "MSIE [1-6]\.";

	root /home/apps/onecard.data-center;

	location / {
		# 用于配合 browserHistory使用
		try_files $uri $uri/ /index.html;

		# 如果有资源，建议使用 https + http2，配合按需加载可以获得更好的体验
		# rewrite ^/(.*)$ https://preview.pro.ant.design/$1 permanent;

	}
	location /connect {
		# 当路由为 /connect 时，自动跳转到本地 44340 端口的鉴权地址，
		proxy_pass http://127.0.0.1:44340;
		proxy_set_header   X-Forwarded-Proto $scheme;
		proxy_set_header   X-Real-IP         $remote_addr;
	}
	location /api {
		# 当路由为 /api 时，自动跳转到本地 44341 端口的 web api 地址，
		proxy_pass http://127.0.0.1:44341;
		proxy_set_header   X-Forwarded-Proto $scheme;
		proxy_set_header   X-Real-IP         $remote_addr;
	}
}
```
