### ISSUE TITLE
👑 [需求] 希望能開發或者支援使用barcode scanner相關的API

### ISSUE THREAD

**Issue by JennyLeung030** [ant-design/ant-design-pro#9681]
### 🥰 需求描述
 希望Ant design pro能開發或者支援使用barcode scanner API
1. https://github.com/mebjas/html5-qrcode

2. https://github.com/zxing-js/library

因為我加入不同類型的barcode scanner API都因為找不到element, 但是我使用F12打開body來找element郤找到相關element

**Comment by chenshuai2144** [comment]
有报错吗？ 感觉是封装的问题，react中使用dom需要用ref 来暂存一下。

**Comment by JennyLeung030** [comment]
> 有报错吗？ 感觉是封装的问题，react中使用dom需要用ref 来暂存一下。

OK, Thanks
