### ISSUE TITLE
🐛[BUG] 网络请求文件流下载问题

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#9684]
### 🐛 bug 描述

 请求设置成  `responseType: 'blob', `，下载文件流报错 再catch和错误拦截器里面拦截到 `SyntaxError: Unexpected token P in JSON at position 0`, 看着像是对流数据进行了parse。

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0] 5.00
- umi 版本 3.5.20
- 浏览器环境 chorem
- 开发环境 [e.g. mac OS] win

### 🚑 其他信息
请求
![image](https://user-images.githubusercontent.com/34082148/158957094-143d8aae-c7d6-41f2-b716-0c3df0810673.png)
调用
![image](https://user-images.githubusercontent.com/34082148/158957153-103ebb1c-9e2a-4c6c-8624-bb991b735036.png)

**Comment by xiexingen** [comment]
感觉可以config里面自己增加一个配置项，如果满足那个配置项，直接返回respone不做处理

**Comment by 569202812** [comment]
> 感觉可以config里面自己增加一个配置项，如果满足那个配置项，直接返回respone不做处理

这个感觉是umi-request里面处理的，还没到我的处理逻辑

**Comment by chenshuai2144** [comment]
这个 server 是oneapi生成的吗？有个属性叫 responseType ，既可以手动配置一下




responseType | How to parse the returned data | string | json , text , blob , formData ... | json , text
-- | -- | -- | -- | --

**Comment by 569202812** [comment]
> 这个 server 是oneapi生成的吗？有个属性叫 responseType ，既可以手动配置一下
> 
> responseType	How to parse the returned data	string	json , text , blob , formData ...	json , text

不是是自己手写的，并且也配置了responseType为blob,项目在线上有的用户可以有的用户直接就拦截了看着报错被json了一下，跟浏览器有关系吗

**Comment by chenshuai2144** [comment]
其实可以 window.open 一下，理论上应该没有问题

**Comment by 569202812** [comment]
> 其实可以 window.open 一下，理论上应该没有问题

响应直接走then走的catch，大部分客户都可以

**Comment by xiexingen** [comment]
window.open 有几个不好的地方
1. 使用post形式提交了一些请求数据
2. token 形式的身份认证

**Comment by 569202812** [comment]
> window.open 有几个不好的地方
> 
> 1. 使用post形式提交了一些请求数据
> 2. token 形式的身份认证

哦哦对的，当时没看懂陈帅说的

**Comment by 569202812** [comment]
> 其实可以 window.open 一下，理论上应该没有问题

这是有没有可能跟后台数据有问题，但是有的浏览器可以有的就不可以

**Comment by 569202812** [comment]
> 这个 server 是oneapi生成的吗？有个属性叫 responseType ，既可以手动配置一下
> 
> responseType	How to parse the returned data	string	json , text , blob , formData ...	json , text

我又测试了一下，启用`React Developer Tools`这个扩展程序就可以用文件流导出，关闭后数据就被json了一下，`responseType	: blob`也设置了

**Comment by chenshuai2144** [comment]
直接用 fetch 算了， request 暂时也没人维护了。
要等umi4发布才有人力。
