### ISSUE TITLE
antd pro  如何使用rem，可以适配ipad端

### ISSUE THREAD

**Issue by tanchang123** [ant-design/ant-design-pro#9686]
antd pro 如何使用rem进行pc端兼容ipad端。看到网上有
px2rem({
      rootValue: 16,//开启hd后需要换算：rootValue=designWidth*100/750,此处设计稿为1920，所以1920*100/750=256
      // propBlackList:['border','border-top','bor)der-left','border-right','border-bottom','border-radius','font-size'],//这些属性不需要转换
      // selectorBlackList:['t_npx']//以包含t_npx的class不需要转换
    })
下面这种方法，但是  rootValue没法动态获取。这个config 文件编译的时候就能执行，没法动态根据设备信息进行动态赋值。
有大佬帮忙解答一项吗 @chenshuai2144

**Comment by tanchang123** [comment]
@chenshuai2144 ,大佬抽空解答一下吧

**Comment by chenshuai2144** [comment]
试试 https://alitajs.com


我们官方不支持的

**Comment by changlin0501** [comment]
> antd pro 如何使用rem进行pc端兼容ipad端。看到网上有 px2rem({ rootValue: 16,//开启hd后需要换算：rootValue=designWidth_100/750,此处设计稿为1920，所以1920_100/750=256 // propBlackList:['border','border-top','bor)der-left','border-right','border-bottom','border-radius','font-size'],//这些属性不需要转换 // selectorBlackList:['t_npx']//以包含t_npx的class不需要转换 }) 下面这种方法，但是 rootValue没法动态获取。这个config 文件编译的时候就能执行，没法动态根据设备信息进行动态赋值。 有大佬帮忙解答一项吗 @chenshuai2144

你好，请问后面如何解决这个问题的呢
