### ISSUE TITLE
🧐[问题]Pro加载ant部分组件报错找不到样式

### ISSUE THREAD

**Issue by GrowingMonkey** [ant-design/ant-design-pro#9688]
### 🧐 pro报无法找到ant组件样式

在Pro项目中使用ant的某些组件。列如TextArea,Panel等会报错找不到组件样式
<img width="221" alt="image" src="https://user-images.githubusercontent.com/24692542/159271178-c9a9e79f-efce-486b-b568-6512b44959f1.png">

### 💻 示例代码

<img width="721" alt="image" src="https://user-images.githubusercontent.com/24692542/159270471-e58473e6-f3f3-4120-a437-6f68f191b601.png">

### 🚑 其他信息
<img width="389" alt="image" src="https://user-images.githubusercontent.com/24692542/159271429-da92a852-12ee-44c5-8a56-5d9f763095c3.png">

**Comment by SilentRio** [comment]
我也遇到过这个问题，把.umi文件夹删除，然后重启项目试试
