### ISSUE TITLE
👑 [需求] 进入创建页面，高亮列表页面的menu

### ISSUE THREAD

**Issue by scrapstation** [ant-design/ant-design-pro#9689]
### 🥰 需求描述

从列表页面进入创建（或详情）页面，高亮列表页面的menu （创建页面无单独入口）

![image](https://user-images.githubusercontent.com/56467036/159298462-eb3e0751-4e85-4da4-b35d-bcf82697cc6e.png)

### 🧐 解决方案

1、平级路由，使用hideInMenu隐藏，并使path嵌套
可以实现，但xxx/list/create不符合路由规范

2、子路由（list二级，create三级）
未能实现，因为二级路由需要展示列表所以带有component，导致三级路由显示了二级路由的内容

### 🚑 其他信息

#7443
#6856
#7413

但有一大佬的侧边栏实现了：
#9430

**Comment by scrapstation** [comment]
结案了！

#7351

```
  {
    name: 'order',
    icon: 'smile',
    path: '/order',
    routes: [
      {
        name: 'list',
        icon: 'smile',
        path: '/order/list',
        component: './Order/List',
      },
      {
        name: 'detail',
        icon: 'smile',
        path: '/order/detail',
        component: './Order/List/Detail',
        parentKeys:['/order/list'],
        hideInMenu: true,
      },
    ],
  }
```

@chenshuai2144 这个配置没有在文档里体现

**Comment by chenshuai2144** [comment]
@scrapstation 有兴趣来个文档的pr吗？
