### ISSUE TITLE
login是否会有JWT 方案

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#969]
请求header头Authorization 携带TOKEN

**Comment by Alexorz** [comment]
可以自行包装一下 utils/request.js，统一传入 TOKEN

**Comment by chenshuai2144** [comment]
暂时不会 自行包装一下就好了。也很简单

**Comment by 510846** [comment]
> 可以自行包装一下 utils/request.js，统一传入 TOKEN

同问，在 utils/request.js 加入 token 现在碰到一个问题，就是当你登录后，这个 token 依然发送的是老的，一定要重新刷新了页面才会生效，请教该如何解决？

```
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'omit', // include 默认请求是否带上cookie
  headers: {
    Authorization: `Bearer ${getToken()}`
  }
});
```

**Comment by 510846** [comment]
搞定了！ `request.interceptors.request`

**Comment by knight2018** [comment]
> 搞定了！ `request.interceptors.request`

我将extend里加的默认请求头放在了request.interceptors.request.use，似乎还是之前的问题，获取上一次的token不知道能否贴一下这块的代码呢？
