### ISSUE TITLE
🧐[问题]可编辑表格，如何于不用dataSource Props情况下，在onSave中以新数据来更新该行数据？

### ISSUE THREAD

**Issue by ramen-curator** [ant-design/ant-design-pro#9690]
### 🧐 问题描述
如图中代码所示，当可编辑表格在编辑模式下保存时，调取后端update接口，得到更新后的本行数据。
如何在不用dataSource这个Props的情况下，用接口返回数据来更新被编辑的那行的数据？
谢谢❤

### 🚴‍♀️ 已作尝试
1. 如图中代码所示，修改record有效。
但有没有更好的办法？因为我这业务里，所有表格共用该组件。

2. 在onSave中return新数据，无效。
`return res.data`

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/26692240/159398941-2f370daa-d969-4413-b1f1-a8ce0d31fbbe.png)

**Comment by chenshuai2144** [comment]
不能reload一下表格吗？

**Comment by ramen-curator** [comment]
> 不能reload一下表格吗？

不能，后端给的排序是“更新时间从新到旧”，如果编辑了第3行的数据后reload，该行数据会跳到第1行，降低体验。

**Comment by chenshuai2144** [comment]
给你加个新api

**Comment by ramen-curator** [comment]
> 给你加个新api

非常感谢！

**Comment by chenshuai2144** [comment]
看了一下好像不行，设置了不更新，除非修改 keys，让后端的改下排序吧
