### ISSUE TITLE
🧐[问题] 我添加了eslint不要分号的规则，但是commit之后总会报这个检验不通过(但是我已经删除了分号)

### ISSUE THREAD

**Issue by SirChu-zhwu** [ant-design/ant-design-pro#9692]
![image](https://user-images.githubusercontent.com/79432177/159454693-aebcc17f-04c2-41b2-aada-b860ff463ac0.png)
![image](https://user-images.githubusercontent.com/79432177/159454765-38392c96-0a54-4f43-bdb8-c4ab5ce88a93.png)

**Comment by chenshuai2144** [comment]
估计是prettier 和 eslint 打架了。

建议自己不要管这些，全部交给 prettier
