### ISSUE TITLE
https post 程序中断

### ISSUE THREAD

**Issue by cenmes** [ant-design/ant-design-pro#9695]
使用proxy代理到后端的https服务器，  get请求没有问题，  post 请求时yarn start 启动的程序直接中断了。

后端部署http时没有问题。

和后端没有任何关系，proxy代理到任何后端的post请求都有问题。

不使用proxy不会中断程序，但需要后端配置跨域，目前后端不太方便配置。

和配置没有关系，直接用UMI脚手架创建的项目，只是添加代理到后端的https请求。

希望能提供帮助

thanks

![微信图片_20220322210712](https://user-images.githubusercontent.com/21157837/159489404-997a4418-d310-4b67-9f3c-643abee0d067.jpg)

![1](https://user-images.githubusercontent.com/21157837/159489808-06433689-edde-4554-99e9-8e4f61c44869.jpg)

**Comment by cenmes** [comment]
加：  vue的项目 使用proxy代理 https 没有问题

**Comment by chenshuai2144** [comment]
你看看报错是什么。看样子是跨域了
