### ISSUE TITLE
👑 [需求]ProFormDependency 嵌套依赖 取不到值

### ISSUE THREAD

**Issue by hugangyongxiangsha** [ant-design/ant-design-pro#9697]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/32123482/159630316-d151c43f-777b-49b4-a82b-6c67d683e6a4.png)

### 💻 示例代码

 <ProFormDependency name={['productmode']}>
            {({ productmode }) => {
              if (productmode === 'customize') {
                return null;
              }
              return (
                <div>
                  <ProFormSelect
                    dependencies={['productmode']} 
                    request={async (params) =>
                      structuresSelectOptions(params?.productmode)
                      // console.log("a");
                    }
                    rules={[
                      {
                        required: true,
                        message: '产品类型为必填项',
                      },
                    ]}
                    // width="md"
                    name={['eme_product_structure','eme_structure_id']}
                  />
                  <ProFormDependency name={['eme_product_structure','eme_structure_id']}>
                      {({ eme_structure_id }) => {
                        if (eme_structure_id?.eme_structure_istest === 0) {
                          return null;
                        }
                        return (
                          <ProFormSelect
                                
                              // key = {`${product?.eme_product_protocol?.eme_protocol_id}eme_product_protocol`}
                              // name="eme_product_protocol"
                              // name={['eme_product_protocol', 'eme_protocol_id']}
                              
                              label='检测方法'//label={`网关协议/联网方式《${eme_product_nodeTypeid}》合同约定生效方式`}
                              // width="md"
                              // fieldNames={{ label: 'eme_protocol_name', value: 'eme_protocol_id', options: {} }}
                              // dependencies 的内容会注入 request 中
                              // defaultValue={defaulSelect}
                              
                              request={async (params) =>
                                protocolsSelectOptions(params?.eme_product_nodeType.eme_nodetype_id)
                                // console.log("a");
                              }
                              // rules={[
                              //   {
                              //     required: true,
                              //     message: '检测方法为必选项',
                              //   },
                              // ]}
                            />
                        );
                      }}
                    </ProFormDependency>
                </div>
              );
            }}
          </ProFormDependency>

把里面的依赖放在外面一样取不到

**Comment by 1247748612** [comment]
ProFormDependency的name是一个list

你得这样传[['eme_product_protocol', 'eme_protocol_id']]
