### ISSUE TITLE
config.ts里设置local.title为true的话，defaultsettings里的title没有实现国际化🧐[问题]

### ISSUE THREAD

**Issue by perryhong** [ant-design/ant-design-pro#9698]
### 🧐 问题描述

config.ts里设置local.title为true的话，defaultsettings里的title没有实现国际化
如何实现侧边栏顶部的title的国际化

**Comment by chenshuai2144** [comment]
menuHeaderRender 这个api 可以自定义title 和logo

| menuHeaderRender | 渲染 logo 和 title | `ReactNode` \| `(logo,title)=>ReactNode` | - |
