### ISSUE TITLE
🧐[问题] index.txs 错误提示怎么解决？

### ISSUE THREAD

**Issue by li-xiao-shuang** [ant-design/ant-design-pro#9702]
### 🚑 其他信息

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/34903552/160222724-2b2d7d77-8a37-4756-b3ce-ed303f5eb19b.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/34903552/160222738-2bf61700-34d7-4359-9423-d8799195efbd.png">

**Comment by li-xiao-shuang** [comment]
> ### 🧐 问题描述
> ### 💻 示例代码
> ### 🚑 其他信息
> <img alt="image" width="1088" src="https://user-images.githubusercontent.com/34903552/160222724-2b2d7d77-8a37-4756-b3ce-ed303f5eb19b.png">
> 
> <img alt="image" width="1035" src="https://user-images.githubusercontent.com/34903552/160222738-2bf61700-34d7-4359-9423-d8799195efbd.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/34903552/160223282-c67223c6-2bf6-4c6e-aeac-f6d35e3f0474.png">

**Comment by li-xiao-shuang** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/34903552/160223291-ff5ff249-e470-454d-8e23-626be01ceb06.png">

**Comment by li-xiao-shuang** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/34903552/160223301-0a0e1dbd-3416-4b40-ad14-cc7bc07a8b05.png">

**Comment by li-xiao-shuang** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/34903552/160223322-f5227517-cbba-4b53-bf28-974f9bf5058a.png">

**Comment by chenshuai2144** [comment]
修复了，已经发布

**Comment by li-xiao-shuang** [comment]
> 修复了，已经发布

有钉钉交流群吗？

**Comment by chenshuai2144** [comment]
<img width="123" alt="image" src="https://user-images.githubusercontent.com/8186664/160743038-08f6db16-bf13-41b0-bc30-7831b05b5bd8.png">


看这个 issue
