### ISSUE TITLE
🧐[问题]关于路由文件层级的推荐规范

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design-pro#9704]
### 🧐 问题描述
如下图所示，有没人提供一个案例说明下，目前感觉开发中，确实不是很好区分出来是路由还是组件？
比如 以一个角色模块为例
admin
| - users (用户下的路由有用户列表、用户编辑、用户查看。。。，然后有些地方抽象一层组件该怎么放，有些是非纯组件又怎么放，再有些共用发业务方法又怎么放，以及哪些该大写，哪些该小写)
| - roles
![image](https://user-images.githubusercontent.com/7939085/160229363-c14f318c-0b52-48aa-ad61-913cea3aaa41.png)

**Comment by chenshuai2144** [comment]
```
- Users 
|-- List
|-- New 
```

这样就好了，尽量大写。User 那个是错别字
