### ISSUE TITLE
为啥我今天新建了一个项目，启动后发现table的查询框  跟table连在一起了。🐛[BUG]

### ISSUE THREAD

**Issue by htaoji1988** [ant-design/ant-design-pro#9706]
### 🐛 bug 描述

为啥我今天新建了一个项目，启动后发现table的查询框  跟table连在一起了。什么也没动。5.0.0的版本照着文档创建的。

![image](https://user-images.githubusercontent.com/19965334/160250645-c63e6551-e8c8-42bd-b6c5-a6b207c178c7.png)

**Comment by imoxuan** [comment]
是啊。我也发现这个问题了。上间距、有间距都没有了。在线等

**Comment by blakeyoungc** [comment]
同样的问题
