### ISSUE TITLE
🐛[BUG] pro-list metas内容不显示了

### ISSUE THREAD

**Issue by 7937505** [ant-design/ant-design-pro#9709]
### 🐛 bug 描述

[
![1648398721765](https://user-images.githubusercontent.com/19165229/160291359-7ca398ec-ceaa-4747-8126-6435ddfa550d.jpg)
](url)
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息

- [ ] [](url)

**Comment by chenshuai2144** [comment]
dup of https://github.com/ant-design/pro-components/issues/4939
