### ISSUE TITLE
面包屑路径中缺少非页面的菜单节点

### ISSUE THREAD

**Issue by Alexorz** [ant-design/ant-design-pro#971]
![image](https://user-images.githubusercontent.com/660581/36634762-85b922e8-19e4-11e8-84d4-4c4113ce7f02.png)

如上图，合理的面包屑应该显示 “列表页” 这个节点，用于说明当前是在哪个板块下，即便不能点击。

**Comment by chenshuai2144** [comment]
故意的
专门没有写 因为不能点击

**Comment by afc163** [comment]
应该要有。

**Comment by Alexorz** [comment]
一般的面包屑应该是基于菜单树生成，但目前是基于页面URL路径切分来实现。

个人感觉现在的整个 菜单、路由、Layout 三者之间的耦合有些严重。

**Comment by ddcat1115** [comment]
面包是跟路由走的，原因是：

- 没有配置路由的菜单项加到面包屑里意义不大
- 经常会有菜单里不需要但面包屑中需要体现的情况

如果需要面包屑中有路由中不存在的结点，可以通过传递 [breadcrumbList](https://pro.ant.design/components/PageHeader-cn/) 实现
