### ISSUE TITLE
🐛[BUG]antd pro5移动设备点击菜单时如何自动收起侧边栏?

### ISSUE THREAD

**Issue by tankpanv** [ant-design/ant-design-pro#9711]
### 🐛 bug 描述
移动端点击菜单时不会字段收起侧边栏。我找到了antd pro4 之前的相关的issue ，但是里面的解决方案似乎在antd-pro 不能解决

### © 版本信息

- Ant Design Pro 版本: 5.0。0
- umi 版本
- 浏览器环境
- 开发环境mac OS

**Comment by chenshuai2144** [comment]
后来关掉自动关闭了。你可以手动设置一下。

监听菜单点击，然后受控 collapsed。

**Comment by semmywong** [comment]
> 

怎么监听菜单点击？

**Comment by chenshuai2144** [comment]
menu 有 onclick 事件的
