### ISSUE TITLE
🧐[问题]打包失败Big integer literals are not available in the configured target environment

### ISSUE THREAD

**Issue by itxiaoe** [ant-design/ant-design-pro#9712]
### 🧐 问题描述

libs/potree-1.8/potree/potree.js:66398:39: error: Big integer literals are not available in the configured target environment
文件地址
path: public/libs/potree/potree.js
文件大小
potree.js：2.3MB
potree.js.map：5.2MB

**Comment by chenshuai2144** [comment]
这个库应该不支持低版本的浏览器，你把target设置的高一点。

https://github.com/sveltejs/kit/issues/859

至少要到 2020.

https://umijs.org/config#targets

**Comment by itxiaoe** [comment]
问题解决了，根本原因是config.js配置项esbuild，开启之后会transform代码(Default: 'es2015')，包括public下的内容，而es2015不支持bigint
`
// config.js
export default defineConfig({
   esbuild: {}, // https://umijs.org/plugins/plugin-esbuild
})
`
