### ISSUE TITLE
🧐[问题]ProTable查询样式问题

### ISSUE THREAD

**Issue by TrumanDu** [ant-design/ant-design-pro#9714]
### 🧐 问题描述

官方demo，显示不符合期望

![image](https://user-images.githubusercontent.com/16727775/160393296-da26fd63-75a4-4067-b610-9390de93884d.png)

### 💻 示例代码

查看多了一个样式` ant-pro-card`

![image](https://user-images.githubusercontent.com/16727775/160393459-5c499c82-00af-4cac-abb4-5946df6ca689.png)

### 🚑 其他信息

删除掉该样式，就正常了

![image](https://user-images.githubusercontent.com/16727775/160393667-90a66e48-1184-41d9-8747-f2494f96a31f.png)

**Comment by chenshuai2144** [comment]
重新升级一下依赖，是优先级顺序的问题
