### ISSUE TITLE
🧐[问题]部分页面免登录

### ISSUE THREAD

**Issue by ANWSY** [ant-design/ant-design-pro#9715]

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/d4391552c1787fae3df6bf60244387f0ff3e07bf/src/app.tsx#L62-L69

代码在这里，你可以改写这个判断

**Comment by ANWSY** [comment]
尝试过了噢，尝试将整个方法都屏蔽，但是还是会自动跳到登录界面，所以不是清楚，是不是脚手架里面放了默认的部分，这是我的代码
![image](https://user-images.githubusercontent.com/13809509/160743540-46b223c3-2b69-48df-805c-04298c96da14.png)
![image](https://user-images.githubusercontent.com/13809509/160743583-27ce1d13-cc75-422a-8884-e0004940e3b3.png)

**Comment by chenshuai2144** [comment]
搜一下有什么地方 history push了。标准项目里面只有这个地方有
