### ISSUE TITLE
ant-design-pro@5.2项目中集成windicss. 🧐[问题]

### ISSUE THREAD

**Issue by single-thread** [ant-design/ant-design-pro#9719]
### 🧐 问题描述
我参照windicss提供的umi项目配置示例，在and-design-pro simple 模板中配置windicss，配置后windicss不能自动更新，必须重新启动项目才会生成对应的样式。我还尝试了在 umi 基础模板中配置是可以自动更新的。

### 💻 示例代码
复现仓库（是在and-design-pro simple初始模板的基础上配置的）：
[https://github.com/single-thread/windicss-in-antd-pro](https://github.com/single-thread/windicss-in-antd-pro)  
复现步骤：
启动项目 -> 修改`src/pages/user/Login/index.tsx`文件`281`行的className -> 样式丢失 -> 重启项目 -> 样式更新了

具体配置步骤：
[https://github.com/single-thread/windicss-in-antd-pro/commit/9f3ff35456031c01c3e1fe5fd39e4d1e6d0455d5](https://github.com/single-thread/windicss-in-antd-pro/commit/9f3ff35456031c01c3e1fe5fd39e4d1e6d0455d5)  

### 🚑 其他信息
参考文档：
windicss配置教程: [https://windicss.org/integrations/webpack.html](https://windicss.org/integrations/webpack.html)

**Comment by chenshuai2144** [comment]
https://github.com/xinlei3166/umi-windicss-template/blob/83ae2e06fe0f2536ee908c45510312ed6266d4b9/config/config.ts

我没试过这个，但是我找到了一个demo

**Comment by single-thread** [comment]
@chenshuai2144 谢谢，我之前试过在umi项目中配置，是成功了。windicss官方也给了demo，[https://github.com/windicss/windicss-webpack-plugin/tree/main/example/umijs](https://github.com/windicss/windicss-webpack-plugin/tree/main/example/umijs)。但是同样的配置(umi版本也相同)在ant-design-pro中不行，我有时间再研究一下
