### ISSUE TITLE
/src/common/router.js178行，有个判断menuKey的正则，是不是多了个'/'？

### ISSUE THREAD

**Issue by hudianlao48** [ant-design/ant-design-pro#972]
按照这种正则条件，menuKey老是空的，下面的menuItem也总是空的。还是我理解有错啊？

**Comment by sangxiaolong** [comment]
BasicLayout中getRedirect方法里
`redirectData.push({
        from: `/${item.path}`,
        to: `/${item.children[0].path}`,
      });`

多了前边的/ ，不能正确重定向

**Comment by chenshuai2144** [comment]
是。
多了一个
