### ISSUE TITLE
🧐[问题] Stuck on loading page

### ISSUE THREAD

**Issue by titipakorn** [ant-design/ant-design-pro#9720]
### 🧐 问题描述 Stuck on loading page

I deployed the sample antd pro v5 on the S3 (AWS) provided access to the S3 by using CloudFront (AWS).

Accessing the website directly to CloudFront is no problem, but when I used Cloudflare as the firewall when accessing the website, there was an error in the attached images. I solved this problem by adding a rule for bypassing cache in Cloudflare. My question is, "Is it our problem that doesn't support this deployed solution?".

Here is the summary of the deployed architecture.

S3 --> CloudFront --> Cloudflare

Stuck Loading Image:
<img width="1728" alt="Screen Shot 2022-03-30 at 20 03 45" src="https://user-images.githubusercontent.com/22910644/160819758-a0457056-cca1-4a14-9725-4add0d58b98f.png">
Error Line:
<img width="1463" alt="Screen Shot 2022-03-30 at 20 03 06" src="https://user-images.githubusercontent.com/22910644/160819624-71795917-edff-42bc-a73e-e8f92b457827.png">
Response Header of that error file:
<img width="262" alt="Screen Shot 2022-03-30 at 20 03 29" src="https://user-images.githubusercontent.com/22910644/160819716-f42fe17e-5cf1-4c35-a16b-ec27253361bb.png">

**Comment by chenshuai2144** [comment]
It looks like you used a regular expression that sarfari doesn't support

**Comment by titipakorn** [comment]
What do you mean by that since I used your initial project without editing anything?

This problem occurred every browser types not only Safari.

I saw your preview antd pro website also but I'm not sure that you used this architecture or not . "S3 --> CloudFront --> Cloudflare"

**Comment by yudewei** [comment]
我遇到上面的问题 通过修改国际化配置解决了 但是遇到这个问题
<img width="1676" alt="WX20220406-215243@2x" src="https://user-images.githubusercontent.com/30426014/161990941-600e186d-6483-411d-9643-62fd0ffd29f3.png">

**Comment by titipakorn** [comment]
> 我遇到上面的问题 通过修改国际化配置解决了 但是遇到这个问题
> <img alt="WX20220406-215243@2x" width="1676" src="https://user-images.githubusercontent.com/30426014/161990941-600e186d-6483-411d-9643-62fd0ffd29f3.png">

Isn't it the same problem since you cannot go to the main route? That's why I called "Stuck on loading page".

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/9f16dae8d7dd4e372aeb8d477d5b86a36710a669/src/pages/document.ejs

look here

**Comment by titipakorn** [comment]
Your answer doesn't give me any clue.

**Comment by chenshuai2144** [comment]
Look at the relative position of your resources, it seems that js is loaded into html
