### ISSUE TITLE
👑 [需求]如何从服务端获取菜单数据名渲染菜单和路由

### ISSUE THREAD

**Issue by oneplusonecy** [ant-design/ant-design-pro#9722]
### 🥰 需求描述
如何从服务端获取菜单数据名渲染菜单和路由

`// https://umijs.org/zh-CN/plugins/plugin-layout
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: initialState,
      request: async (params, defaultMenuData) => {
        return initialState.menuData;
      },
    },
  };
};`
按这个配置只能渲染菜单，但服务生成路由，怎么才能渲染路由

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8A%A0%E8%BD%BD-menu-%E5%B9%B6%E4%B8%94%E4%BD%BF%E7%94%A8-icon

动态路由不支持哦，路由会让umi知道应该编译哪些文件，如果没有路由那么 umi 不会编译文件了。你最好预先设置好所有的路由
