### ISSUE TITLE
valueType为什么是字符串?🧐[问题]

### ISSUE THREAD

**Issue by okool** [ant-design/ant-design-pro#9723]
### 🧐 问题描述
有个疑问,为什么pro table中的render组件使用的是string类型?而icon却从string变成组件?

自定义变成很复杂与react的一切都是组件的理念背道而驰.

formColumn,searchColumn,tableColumn混在一起需要写大量的hidexxx,是不是背离了antd的设计原则?组件的解耦,反用户第一直觉. 

在没升级前我们的valueType是这样定义的.

```react
// 通用的
{
 ...
  "valueType":"date"
}
// 私有的
{
  ...
 "valueType":<EnumField>
}
```

而不需要复杂的,重写组件
```react
<ProProvider.Provider
      value={{
        ...values,
        valueTypeMap: {
          "enum":{
               "xxxRender":<>
               "xxxRender"
            }
       }

```

职权分离原则:ProTable ,没升级前我们是这样定义的.

```react
const searchColumns=[
  {
   dataIndex:'updated_at',
   render:<DateRangeFormItem>
  }
];
const tableColumns=[
  {
     dataIndex:'updated_at',
     render:<DateCell>
    }
];
const createColumns=[
 {
     dataIndex:'updated_at',
     render:<DateFormItem>
 }
];
const updateColumns=[
 {
     dataIndex:'updated_at',
     render:<DateFormItem>
 }
];
<ProTable
  searchColumns
  tableColumns
  createColumns
  updateColumns
/>
```
为什么分开呢? 
1. 因为表格和查询表单虽然大部相似,但大部分情况是各不相同.
各自有自己的render逻辑, renderFormItem和renderCell是两个不同的组件,从视觉上和数据上就不是同一个东西. 从ts上来说他们两个type.

2. columns是列配置,不等同map 结构. 
列数据dataIndex是可以重复,不具有唯一性,map字典key才具有唯一性.

混在代码一起可读性变差. 违返了直觉. 如果使用json配置化低代码. 应该由前端拆分.

如:我们后端给的数据字典.
```json
fields:{
 name:{type:"string","size":150},
 image:{type:"image"},
 created_at:{type:"date"}
}
```
前端根据配置在不同场景使用不同组件.

**Comment by chenshuai2144** [comment]
重型组件的思路 和 一般组件的是不同的。


重型组件是配置友好的，而不是编程友好。所以很多东西尽量用 string 和 boolean 这种基本数据方便转化为输入框，可以用静态生成。
