### ISSUE TITLE
🧐[问题] Ant Design Pro v5  在IE浏览器中无法使用

### ISSUE THREAD

**Issue by JnbCnb** [ant-design/ant-design-pro#9724]
### 🧐 问题描述
初始化脚手架，选择TypeScript/simple，在IE浏览器中报错，一直处于加载状态。尝试在 config.ts 中添加配置，删除国际化、动态样式，引入babel-polyfill、babel/core等，无变化。望大佬指教下，不想就此放弃这个框架

### 🚑 其他信息
修改配置如下，其他无变化
![image](https://user-images.githubusercontent.com/68832210/160985259-40650240-166f-48cc-a589-7664163075fb.png)
报错信息如下：
![image](https://user-images.githubusercontent.com/68832210/160985306-c2442a2f-baf4-4c4b-b2fe-bdd5b30f95f8.png)

**Comment by chenshuai2144** [comment]
dev 环境是完全没法跑起来的，你要 build 之后用 dist目录来测试哦
