### ISSUE TITLE
🧐样式无法加载或加载缓慢

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#9725]
### 🧐 问题描述
在本地开发和上线后，大概率出现部分样首次始加载不出来的情况，或者初始能够加载切换一下页面样式就没了，此时需要刷新页面才能显示出来，请问又遇到过这种情况的吗，该怎么解决呢？

**Comment by chenshuai2144** [comment]
一般来说都是网络问题，你看看network 自己debug一下。

如果想要别人帮你解决，最好把问题提交清楚

**Comment by Youmyin** [comment]
好的，谢谢
