### ISSUE TITLE
ant design pro 打包之后部署到OSS静态服务网站，无法访问外部接口，应该是OSS不能使用代理模式。  请问如何在生产环境直接使用生产环境的接口地址呢？🧐[问题]

### ISSUE THREAD

**Issue by aizhimin** [ant-design/ant-design-pro#9727]
### 🧐 问题描述

ant design pro V5

我通过yarn buld:rpod  方式打包，并将dist文件部署到OSS上。

无法访问服务器的接口，提示405 Method not allowed。

**Comment by scrapstation** [comment]
跟代理模式没啥关系吧，我能正常用

**Comment by chenshuai2144** [comment]
405 Method not allowed。

这个是 get 和 post 方法错了的意思
