### ISSUE TITLE
POST请求，Content-Type设为application/x-www-form-urlencoded时，服务端接受到的格式为{'{key:value}': ''},理想中应该为{key: value},body用qs转过，格式打印出来应该是对的。

### ISSUE THREAD

**Issue by crazycheese** [ant-design/ant-design-pro#973]
request.js修改如下，并且该场景不是本地MOCK，是代理到服务端。
```
if (!(newOptions.body instanceof FormData)) {
   newOptions.headers = {
      Accept: 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded',
      ...newOptions.headers,
    };
    // newOptions.body = JSON.stringify(newOptions.body);
    newOptions.body = qs.stringify(newOptions.body);
    // console.log(JSON.stringify(newOptions.body))
  }
```

**Comment by crazycheese** [comment]
在Chrome network中，请求的信息都是没问题的，代理到服务器，却看起来好像被转过一次。
<img width="368" alt="network" src="https://user-images.githubusercontent.com/22310464/36641465-b13e5ede-1a6a-11e8-9b4c-eee2bc7ae0e5.png">
server端接收如下
<img width="407" alt="server" src="https://user-images.githubusercontent.com/22310464/36641473-c77d2446-1a6a-11e8-8179-d15eda1ce4d8.png">

**Comment by chenshuai2144** [comment]
你用的什么当后台。这个看起来像是后台没有识别转化错误了

**Comment by crazycheese** [comment]
@chenshuai2144 你好
这个问题是在配置完代理之后出现。
这应该不是后台的问题，同样的后台，pro的请求，就会变成这个样子。
我用另外一个项目代理到这个后台，是vue的,参数就是正常的
截图如下，network都是一样的，
![log](https://user-images.githubusercontent.com/22310464/36652373-6878e6e0-1ae9-11e8-9ef9-fb7c99a1075b.png)
<img width="563" alt="post" src="https://user-images.githubusercontent.com/22310464/36652377-6d501256-1ae9-11e8-8b73-6b6738aa3e2b.png">
怀疑是否pro在代理这一层，统一将参数处理过？比如json转换之类。
如果有，请问是否有配置可以避免？

**Comment by crazycheese** [comment]
@valleykid
按照文档配置，代理是OK的
![proxy](https://user-images.githubusercontent.com/22310464/36654901-7aa11750-1afa-11e8-880f-4d7a0fff6e11.png)

**Comment by valleykid** [comment]
依赖库[express-http-proxy](https://github.com/villadora/express-http-proxy)的原因，已提交了[PR](https://github.com/villadora/express-http-proxy/pull/322)

**Comment by crazycheese** [comment]
@valleykid 
目前开发是在在.webpackrc中配置代理，一切正常。

**Comment by valleykid** [comment]
它们是两套不同的代理机制，mock中的proxy依赖了express-http-proxy，而在webpackrc中设置的代理，依赖了webpack-dev-server.

**Comment by badounan** [comment]
同样遇到这个问题，什么时候能解决啊

**Comment by valleykid** [comment]
#1011

**Comment by chenshuai2144** [comment]
已经发布到最新的版本中，放心使用吧

**Comment by valleykid** [comment]
express-http-proxy原作者只是把PR合并到了master，并没有发新版本出来。这个issue先开着吧，我会在roadhog上彻底解决下这种类型的问题。

**Comment by Qingtian239113** [comment]
您好，请问是如何在.webpackrc.js中配置的代理？？

**Comment by valleykid** [comment]
@Qingtian239113 请参考https://github.com/sorrycc/roadhog#proxy
