### ISSUE TITLE
🧐[路由配置] 

### ISSUE THREAD

**Issue by januwA** [ant-design/ant-design-pro#9732]
### 🧐 问题描述

你好，请问下`/config/config.js`里面的`routes`配置和`/config/routes.js`中导出的路由有什么区别。

### 💻 示例代码

![image](https://user-images.githubusercontent.com/22570563/162110866-6190ed5a-646b-476e-8c9a-1c7a125f450a.png)

**Comment by chenshuai2144** [comment]
好好写标题。

没区别，放到文件里面好管理
