### ISSUE TITLE
🧐[问题]如何做到settingDrawer在生产环境中隐藏按钮并且使用之前配置好的样式的？

### ISSUE THREAD

**Issue by zhengsongjunj** [ant-design/ant-design-pro#9733]
### 🧐 问题描述
🧐[问题]如何做到settingDrawer在生产环境中隐藏按钮并且使用之前配置好的样式的？

**Comment by chenshuai2144** [comment]
https://ant.design/docs/react/customize-theme-variable-cn

看这个哦，settingDrawer用的它

**Comment by xixichensh** [comment]
https://ant.design/docs/react/customize-theme-variable-cn

现在是404
