### ISSUE TITLE
AntDesignPro - Problem with change in plugin-layout

### ISSUE THREAD

**Issue by Manshadi1359** [ant-design/ant-design-pro#9734]
When I change the plugin-layout in umi folder and start the project, all changes are deleted.
I want add some change in plugin-layout. I use AndDesignPro v5.2.0

**Comment by chenshuai2144** [comment]
You shouldn't change anything in the .umi folder, it's just a temporary file

**Comment by Manshadi1359** [comment]
How i can change plugin-layout?

**Comment by chenshuai2144** [comment]
you should set it by Runtime API

**Comment by Manshadi1359** [comment]
Do you have any sample code for Runtime API ?

**Comment by Manshadi1359** [comment]
How i can change plugin-layout in Runtime API?

**Comment by chenshuai2144** [comment]
For this feature you should use prolayout directly instead of plugins

**Comment by Manshadi1359** [comment]
Can you help me where to put the prolayout?

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/components/layout

here

**Comment by Manshadi1359** [comment]
I read the link above and did not understand how to disable the plugin-layout and use the prolayout directly instead of the plugin-layout in AndDesingPro
