### ISSUE TITLE
🧐[问题]ProForm.Group嵌套下的ProFormText 设置自定义样式无效

### ISSUE THREAD

**Issue by wangxing0204** [ant-design/ant-design-pro#9736]
[###]([url](url)) 🧐 问题描述
ProFormText  设置自定义样式无效
![1649379514(1)](https://user-images.githubusercontent.com/81609796/162343066-313067e0-8e1b-49ea-b837-6f6b3459ca13.jpg)

### 💻 示例代码
![1649379474](https://user-images.githubusercontent.com/81609796/162343114-d518e024-d701-4749-9432-3d08a1f2b923.jpg)

**Comment by chenshuai2144** [comment]
ProFormGroup 有个 叫做 size 的属性，可以控制宽度。margin 会被合并的。

https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Block_formatting_context

看看这个

**Comment by wangxing0204** [comment]
🚑 已解决


修改为    labelCol={{ style: { marginLeft: 15 } }}

**Comment by wangxing0204** [comment]
> ProFormGroup 排列组合大小的属性，可以控制丰富。margin 会被合并的。
> 
> https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Block_formatting_context
> 
> 看看这个
已经解决了   之前一直以为只有span  就被局限到了

**Comment by wangxing0204** [comment]
labelCol={{ style: { marginLeft: 15 } }}
