### ISSUE TITLE
🧐layout设置为side，能控制某一个路由为弹出式菜单吗

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#9739]
### 🧐 问题描述
1. layout设置为side，能控制某一个路由为弹出式菜单吗
2. 有没有计划开发子菜单多列菜单，平常遇到多列菜单的需求挺多的

**Comment by chenshuai2144** [comment]
> 有没有计划开发子菜单多列菜单，平常遇到多列菜单的需求挺多的

有图图吗？

**Comment by chenshuai2144** [comment]
> layout设置为side，能控制某一个路由为弹出式菜单吗

不支持单个模式

**Comment by 569202812** [comment]
> > 有没有计划开发子菜单多列菜单，平常遇到多列菜单的需求挺多的
> 
> 有图图吗？
类似于这种，要是还可以加入分组就更好了，不过这种的子菜单下面再有嵌套显示感觉有问题
![image](https://user-images.githubusercontent.com/34082148/162357256-b8587585-0ac2-4d13-b7ac-c90daaaf109c.png)
![image](https://user-images.githubusercontent.com/34082148/162357521-c5ec3101-958e-4d88-a335-4aafad3006d4.png)

**Comment by chenshuai2144** [comment]
antd 支持了，我们就支持了，你试试

**Comment by 569202812** [comment]
> antd 支持了，我们就支持了，你试试

我改的样式哈哈

**Comment by chenshuai2144** [comment]
那估计不行了，自己实现吧。

这个设计改动过大

**Comment by 569202812** [comment]
> 那估计不行了，自己实现吧。
> 
> 这个设计改动过大

嗯嗯自定义的渲染了菜单项
