### ISSUE TITLE
打包部署问题 

### ISSUE THREAD

**Issue by sowdf** [ant-design/ant-design-pro#974]
👍 
1818/48.bf21edfe.async.js Failed to load resource: the server responded with a status of 404 (Not Found)

```code
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ant Design Pro</title>
  <link rel="icon" href="/favicon.png" type="image/x-icon">
<link href="http://localhost:1818/dist/index.46cca24a.css" rel="stylesheet"></head>
<body>
  <div id="root"></div>
  <script src="https://gw.alipayobjects.com/as/g/??datavis/g2/2.3.12/index.js,datavis/g-cloud/1.0.2/index.js,datavis/g2-plugin-slider/1.2.1/slider.js"></script>
<script type="text/javascript" src="http://localhost:1818/dist/index.adaa4a57.js"></script></body>
</html>
```

我用的是绝对路径 ，  按道理 来说 index.adaa4a57.js 这个js 应该是相对 路径引用的 

引用的ji 应该是http://localhost:1818/dist/48.bf21edfe.async.js

但是 它却引用的是 http://localhost:1818/48.bf21edfe.async.js 这个 JS

**Comment by sowdf** [comment]
publicPath 在webpackrc 里面加 我发现我的项目里面 webpackrc 没有这个文件

只有roadhogrc 这个文件  请问怎么加呢  publicPath

**Comment by chenshuai2144** [comment]
roadhog 2.0 使用了webpackrc 
1.0就是使用的 roadhogrc。
https://github.com/sorrycc/roadhog#publicpath
