### ISSUE TITLE
🐛[BUG] yarn create umi 创建的simple 为 5.2.0 , complete 为5.0.0

### ISSUE THREAD

**Issue by doucheng** [ant-design/ant-design-pro#9740]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
忘记同步了 我同步一下

**Comment by hyzx86** [comment]
@chenshuai2144 请问大神同步好了吗？

**Comment by chenshuai2144** [comment]
同步好了

**Comment by hyzx86** [comment]
额~~ 为啥我这还是5.0 ，是不是哪里姿势不对？
` npx create-umi EasyOC.AntdAdmin`


![image](https://user-images.githubusercontent.com/15613121/172784674-87dc3386-8445-4806-9a32-d0b9685a1e7e.png)

**Comment by hyzx86** [comment]
额。。是yarn 的问题么？要怎么操作啊？
是不是可以迭代个小版本解决这个问题啊？

**Comment by wooxyz** [comment]
咋整啊 试了几次  还不行

**Comment by LzhH5** [comment]
@chenshuai2144 缓存已清除 还是不行 ？？？

**Comment by chenshuai2144** [comment]
gitee 好像有点问题，不能更新了
