### ISSUE TITLE
🐛[BUG]Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by manager668899** [ant-design/ant-design-pro#9741]
### 🐛 bug 描述
Cannot read properties of undefined (reading 'toString')

这样的错误提示 让人无从下手。无法解决 24小时了 没有排查出来 

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
错误全一点！目测是必填给了一个空
