### ISSUE TITLE
🧐[问题]关于 layout 的配置项 `onPageChange` 能否处理登录鉴权的疑问

### ISSUE THREAD

**Issue by zqran** [ant-design/ant-design-pro#9742]
### 🧐 问题描述

可以直接通过 `layout` 的运行时配置提供的 `onPageChange` 函数，来进行**登录鉴权**吗？

### 💻 示例代码

```tsx
// src/app.tsx 中：
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    // ... 省略其他配置
    onPageChange: () => {
      const { location } = history
      if (location.pathname === loginPath) return

      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser) {
        return history.push(loginPath)
      }

      // --- 在此处，添加登录鉴权逻辑 ---
     if (!isAuth()) {
       history.push(loginPath)
     }
    },
  }
}
```

### 🚑 其他信息

疑问：
1. 这种处理方式存在问题吗？
2. 该方式与使用路由中的 `wrappers` 进行登录鉴权的区别是什么？

**Comment by WuJiY** [comment]
你切换了页面，没有调用接口？接口不就是鉴权了吗

**Comment by zqran** [comment]
> 你切换了页面，没有调用接口？接口不就是鉴权了吗

你说的是接口鉴权，接口鉴权可以展示 403，不一定非要让用户重新登录吧？另外一些没有接口调用的页面或者接口没有鉴权的，该咋处理呢？

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-request
看看这个有拦截器的

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi-request
看看这个有拦截器的

**Comment by zqran** [comment]
@chenshuai2144 我的需求不是对接口进行权限校验，我是想从路由层面做登录拦截

**Comment by WuJiY** [comment]
> @chenshuai2144 我的需求不是对接口进行权限校验，我是想从路由层面做登录拦截

路由拦截直接写在路由里就好了，有个叫 access 的满足你 了解下

**Comment by zqran** [comment]
@WuJiY 我知道 `access` 可以进行权限校验，可以用来在没有权限访问该页面时，展示 403 之类的页面。

但是，现在我想要的是：**跳转页面时，判断有没有登录，没有登录就跳回到登录页面，也就是我描述的 `登录拦截`**

**Comment by WuJiY** [comment]
那还是切换页面接口鉴权啊，没登录就返回401 ，你拦截器拦截到401 就跳转login

**Comment by zqran** [comment]
> 那还是切换页面接口鉴权啊，没登录就返回401 ，你拦截器拦截到401 就跳转login

这样的话，未登录时也可以进入后台页面，闪一下（等网络请求响应）确定没有登录，然后，再跳回登录页面吗？这用户体验好吗？

**Comment by WuJiY** [comment]
未登录就没有initialState 进不了后台 app.ts里已经判断了。我大概明白你的意思了 你说的意思是：进入后台 不用请求 就进入登录页面？那请问你从哪里来判断登没登录？我估计单页应用目前都解决不了这个问题，至少目前解决不了。

**Comment by zqran** [comment]
我描述的操作是：

1. 访问后台首页
2. **在某个地方进行登录鉴权，来确定是否登录**
3. 如果登录了，允许访问
4. 如果未登录，跳转到登录页面

然后我的问题是：

上述步骤中的**第 2 步**，这个登录鉴权，在哪里做比较合适？也就是该 issue 最开始问的：
> 可以直接通过 layout 的运行时配置提供的 onPageChange 函数，来进行登录鉴权吗？

这应该就是你描述的 `app.ts里已经判断了` 代码所在的地方吧？

---

然后，另外一个问题是：
`onPageChange` 里面做登录鉴权，与使用路由的 `wrappers` 做登录鉴权，有啥区别？

**Comment by WuJiY** [comment]
// 如果没有登录，重定向到 login
      if (!initialState?.currentUser) {
        return history.push(loginPath)
      }

**Comment by tuonioooo** [comment]
> 

可以的 ，你的意思是静态访问路由，如果是已登录的话，就直接跳转到欢迎页，而不是一下就跳转到登录页吧

以前pro4 有登录布局、安全布局  可以很简单的实现 ，pro5 给干掉了

所以在这里做  第一步
`export async function getInitialState(): Promise<{
  settings?: Partial<LayoutSettings>;
  currentUser?: API.CurrentUser | undefined;
  menuData?: MenuDataItem[];
  authority?: TreeNode[];
  loading?: boolean;
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>;
}> {

  //获取用户基本信息
  const fetchUserInfo = async () => {
    // to do...
  };

  //获取菜单和权限
  const fetchUserPermission = async (): Promise<API.BasePermission> => {
    //to do...
  };

  // 如果不是登录页面或已登录，执行
  const userOAuthId = parseInt(getStoreData("userOAuthId") + "");
  const token = getStoreData("token");
  if ((history.location.pathname !== loginPath) || (userOAuthId && token)) {
    const currentUser = await fetchUserInfo();
    //从服务器获取路由菜单
    const { menuData, flatData: authority } = await fetchUserPermission();
    return {
      fetchUserInfo,
      currentUser,
      menuData,
      authority,
      settings: defaultSettings,
    };
  }
  return {
    fetchUserInfo,
    settings: defaultSettings,
  };
}
第二步

export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {

  return {
    // ...你的配置
    onPageChange: () => {
      const { location } = history;
      // 如果登录，且访问的是登录页重定向到欢迎页
      if(initialState?.currentUser && location.pathname === loginPath){
        history.push("/");
      }
      // 如果没有登录，重定向到 login
      if (!initialState?.currentUser && location.pathname !== loginPath) {
        history.push(loginPath);
      }
    },

   // ...你的配置
    
  };
};
`
希望我的回答你能够明白 ，再说一点 umi-request  他是网络http 请求后端接口拦截 不处理route

**Comment by WuJiY** [comment]
wrappers

**Comment by 985563349** [comment]
wrappers吧，目前看来 onPageChange 并不适合做路由拦截。因为改方法的执行是在 useEffect 中。假设你在未登录的情况下，通过输入 url 的方式强行进入需要登录后才能浏览的页面，而该页面正好在 useEffect 中发送了请求，那么本不该发出的请求，仍然发出了，想要控制好其实并不是件容易的事。

**Comment by dimsumc** [comment]
但用 wrapper 的话好像得每个页面写一次，好像没办法弄成全局的处理？
