### ISSUE TITLE
🐛[BUG] InitialState refresh after successful login

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#9743]
The refresh in the InitialState model does not work after the user is logged in on the login page.

```
const Login: React.FC = () => {
  const [success, setSuccess] = useState<boolean>(false);
  const [type, setType] = useState<string>('account');
  const { refresh } = useModel('@@initialState');

  const { run: login, data: dataLogin } = useRequest(accountLogin, {
    manual: true,
    onSuccess: async (msg: API.AuthTokenType | undefined) => {
      token.save(msg!);
      if (token.check()) {
        setSuccess(true);
        message.success('Success');

        goto();

        await refresh();  // NOT WORKING!!!


      }
    },
  });

}
```

**Comment by xXAvoraXx** [comment]
> 

Since the login page is not part of the layout, the refresh from the initial state does not work.

**Comment by xXAvoraXx** [comment]
> ```
>       
> 
>         await refresh();  // NOT WORKING!!!
> 
>         goto();
> ```

Since the login page is not part of the layout, the refresh from the initial state does not work.

**Comment by chenshuai2144** [comment]
https://github.com/umijs/plugins/blob/193a3d66c9f70727d60bcac69565a4221d7010ef/packages/plugin-initial-state/src/utils/getModelContent.tsx#L42

look here
