### ISSUE TITLE
🐛[BUG]配合XFlow使用，切换菜单布局，不显示

### ISSUE THREAD

**Issue by zhangxiaojun11** [ant-design/ant-design-pro#9749]
### 📷 复现步骤

Ant DesignPro中使用XFlow， 切换顶部菜单模式时，页面内容不显示

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境 firfox
- 开发环境 Windows11

### 🚑 其他信息

![火狐截图_2022-04-11T15-42-06 261Z](https://user-images.githubusercontent.com/1852461/162779650-14913f2c-1503-4084-83ff-68519cc78364.png)
![火狐截图_2022-04-11T15-41-43 077Z](https://user-images.githubusercontent.com/1852461/162779684-0fdfd92a-761c-427b-b30f-596539a6d29b.png)

**Comment by zhangxiaojun11** [comment]
知道没啥关系， 我没有改任何代码， 生成的simple ant design pro， 如图利用页面内部的设置变更的顶部菜单栏， 然后就显示不出来了

**Comment by chenshuai2144** [comment]
搞个重现看看

**Comment by zhangxiaojun11** [comment]
嗯嗯， 你试试， 重新生成项目， 我直接把https://github.com/antvis/XFlow/tree/master/packages/xflow-docs/docs/tutorial/solutions/dag  整个目录搬进去了
