### ISSUE TITLE
登录成功之后如果访问login页面应该加个判断吧

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#975]
登录成功之后如果访问login页面，直接跳转至管理首页，现在好像没有判断吧

**Comment by afc163** [comment]
这是有意的，否则演示页的登录页会始终无法访问。有需求的可以自行加上。

**Comment by chenshuai2144** [comment]
这个是专门关掉的。原来有个权限做控制。。。
后来发现如果什么权限都没有就会造成无限重定向，
就改成这样了。
你可以通过AuthorizedRoute 自己加一个
