### ISSUE TITLE
🧐[问题]在ant design pro中，引入Tag、Tooltip后，页面一直无法刷新出来？

### ISSUE THREAD

**Issue by whyyue** [ant-design/ant-design-pro#9754]
### 🧐 问题描述
在antdesign pro中，引入Tag、Tooltip后，页面一直无法刷新出来。

### 💻 示例代码
见图。

### 🚑 其他信息
使用位置：
![image](https://user-images.githubusercontent.com/9195955/163039318-0f667e52-bf73-43bc-abf6-b9c101ba15a4.png)
页面显示：
![image](https://user-images.githubusercontent.com/9195955/163039554-c1ad4f35-c31a-46eb-9793-eb0d2dedc910.png)
将Tag、Tooltip相关代码注释后：
![image](https://user-images.githubusercontent.com/9195955/163039754-524b37f9-c8b0-438c-94f0-4ce01d268e25.png)
页面可以正常刷新出来：
![image](https://user-images.githubusercontent.com/9195955/163039854-a2155432-5d14-41e6-a6e3-b1524b1a3089.png)

**Comment by chenshuai2144** [comment]
关掉 mfsu，再打开一下就行了。
