### ISSUE TITLE
🧐[问题] 配置了publicPath后，组件使用路径引入资源的情况下，没有加上publicPath的路径

### ISSUE THREAD

**Issue by zjstudy** [ant-design/ant-design-pro#9756]
### 🧐 问题描述

部署在非根路径：如部署在 http://xxx.com/admin/ 下
config 配置了
base: '/admin/',
publicPath: '/admin/',

路由、JS、CSS等都正确的加上了/admin/前缀
但是下面的这两种写法，没有加上/admin/的前缀，导致资源404

background-image: url('/img/login-bg.jpg');
<img src="/img/login-bg.png"/>

上述资源请求地址为： http://xxx.com/img/login-bg.jpg
期望资源请求地址为：http://xxx.com/admin/img/login-bg.jpg

在配置了publicPath的情况下，这种资源应该怎么处理呢

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#runtimepublicpath
