### ISSUE TITLE
Trigger error cause endless loading

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-pro#976]
https://preview.pro.ant.design/#/exception/trigger

1. click one button
2. then all buttons wrapped by a Spin, can't click anymore.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/507615/36652402-977c63cc-1ae9-11e8-826c-7ff927da3027.png">

**Comment by chenshuai2144** [comment]
After clicking on the page should jump.

**Comment by zhfish** [comment]
@nikogu @chenshuai2144 
my page can't jump, just send notification to user
how endless loading when catch ？
i need catch to endless process and loading

step 1,  i don't catch the error
```
return fetch(url, newOptions)
    .then(checkStatus)
    .then(response => {
      if (newOptions.method === 'DELETE' || response.status === 204) {
        return response.text();
      }
      return response.json();
    });
    // .catch(e => {
    //   const { dispatch } = store;
    //   const status = e.name;
    //   if (status === 401) {
    //     dispatch({
    //       type: 'login/logout',
    //     });
    //     return;
    //   }
    //   if (status === 403) {
    //     dispatch(routerRedux.push('/exception/403'));
    //     return;
    //   }
    //   if (status <= 504 && status >= 500) {
    //     dispatch(routerRedux.push('/exception/500'));
    //     return;
    //   }
    //   if (status >= 404 && status < 422) {
    //     dispatch(routerRedux.push('/exception/404'));
    //   }
    // });
```

step2:
```
    *query({ payload }, { call, put }) {
      yield call(query, payload.code);  // error
      // when error,this break
      yield put(routerRedux.push(`/exception/${payload.code}`));
      yield put({
        type: 'trigger',
        payload: payload.code,
      });
```

in step2, break this process on line 1, this right, but the loading isn't endless

**Comment by chenshuai2144** [comment]
use `try catch`

**Comment by zhfish** [comment]
@chenshuai2144 
我是不想挨个try catch才这样问的，
毕竟现在pro的做法，也是在返回之前catch住，再返回正常值。
因为catch的同时做了跳转，所以call下面的put执行没执行也无所谓了

我的需求是不条转，只报错
目前我是在request里返回undefined，然后在call后面 if 判断，以达到目的

如果做到能在哪统一try catch住throw，然后结束loading，就最好了
