### ISSUE TITLE
👑 [需求] 增加路由懒加载功能，减小打包后js 文件体积

### ISSUE THREAD

**Issue by sunxinGitHub** [ant-design/ant-design-pro#9760]
### 🥰 需求描述

打包后有些js文件太大了，导致第一次加载非常非常慢，给用户的使用感受非常不好

### 🧐 解决方案

希望增加路由懒加载功能

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/18341093/163533721-ede12c48-20a9-46d7-a642-4c9eb0d327a5.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#dynamicimport
看这个
