### ISSUE TITLE
🧐[问题] 你好，我想问一下antd-pro 默认报错错误信息是在哪个地方发起

### ISSUE THREAD

**Issue by tankpanv** [ant-design/ant-design-pro#9763]
### 🧐 问题描述
我的问题是，在注册页面，点击手机注册点击获取数据，这时候数据有问题，会触发一个空的message，在表单等页面也会出现这个。我想了解下，这个默认的message在哪里配的。或者我可以在哪里改这个message信息，而不是报一个空的错误信息。比如下图

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/13927744/163726948-b6a185a0-2b67-4ceb-ae79-6716a7afc241.png)

**Comment by jerryyxu** [comment]
+1

**Comment by iainlau** [comment]
src/.umi/plugin-request/request.ts 的第 204 行。
可以在 app.tsx 下使用 request 的运行时配置，重写 errorHandler 方法。
