### ISSUE TITLE
🧐[问题]先有二级菜单，再有一级菜单，而且前缀路由都一样，则一级菜单无法显示页面

### ISSUE THREAD

**Issue by caimingyi484** [ant-design/ant-design-pro#9765]
```
{
    path: undefined,
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    // exact: true,
    // component: './Admin',
    routes: [
      {
        path: '/pi-v1.sf/views/pages/list-page',
        name: 'list-page',
        exact: true,
        icon: 'smile',
        component: './Table',
      },
      {
        path: '/ac-v1.sf/views/pages/list-page',
        name: 'list-page2',
        exact: true,
        icon: 'smile',
        component: './Table',
      }
    ]
  },
  {
    path: '/pi-v1.sf/views/pages/view-add',
    name: 'form-page',
    exact: true,
    icon: 'smile',
    component: './Form',
  }
```
前缀路由都是/pi-v1.sf/views/pages，菜单form-page的页面无法显示，请问该如何解决？

**Comment by shadowfish07** [comment]
刚想问这个问题，是一个问题吧？

官网初始化的项目：
```
  {
    path: '/admin',
    name: '管理页',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      { path: '/admin/sub-page', name: '二级管理页', icon: 'smile', component: './Welcome' },
      { component: './404' },
    ],
  },
```

二级管理页的component不生效，改什么都没用，管理页的component会覆盖掉它的配置，只有管理页不设置component二级管理页才会生效

**Comment by caimingyi484** [comment]
> 刚想问这个问题，是一个问题吧？
> 
> 官网初始化的项目：
> 
> ```
>   {
>     path: '/admin',
>     name: '管理页',
>     icon: 'crown',
>     access: 'canAdmin',
>     component: './Admin',
>     routes: [
>       { path: '/admin/sub-page', name: '二级管理页', icon: 'smile', component: './Welcome' },
>       { component: './404' },
>     ],
>   },
> ```
> 
> 二级管理页的component不生效，改什么都没用，管理页的component会覆盖掉它的配置，只有管理页不设置component二级管理页才会生效

不是同一个问题，它现在路由都是父类会覆盖子类，除非你父类的component不设置；
