### ISSUE TITLE
🐛[BUG]初始化项目,组件样式会错乱

### ISSUE THREAD

**Issue by xiangyuisabatman** [ant-design/ant-design-pro#9767]
### 🐛 bug 描述
初始化项目,样式会错乱

### 📷 复现步骤
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/23613080/164193822-93557ba7-e91e-4442-bf4f-9903708c181c.png">

### 🏞 期望结果

<img width="791" alt="image" src="https://user-images.githubusercontent.com/23613080/164193900-691f94b6-5d07-4640-91cd-f93d68e2e2ff.png">

### © 版本信息

- Ant Design Pro 版本: 4.0.0
- umi 版本: 3.5.0
- 浏览器环境: 版本 99.0.4844.84（正式版本） (arm64)
- 开发环境 mac OS

**Comment by chenshuai2144** [comment]
清理下你的缓存，用最新版本的依赖。

这看起来是新旧版本混合了
