### ISSUE TITLE
🧐[primaryColor修改主题色不生效]

### ISSUE THREAD

**Issue by windman-only** [ant-design/ant-design-pro#9768]
### 💻 示例代码
theme: {
        '@primary-color': ’#fff‘,
    },

**Comment by ALostKing** [comment]
1. 检查一下app.tsx文件是否设置了<SettingDrawer>.
2. 在defaultSettings.ts文件中设置primaryColor
![image](https://user-images.githubusercontent.com/85096116/165035842-7d6ed5e1-220f-4e6c-8f3d-28530cd919fd.png)

**Comment by windman-only** [comment]
> 1. 检查一下app.tsx文件是否设置了.
>    ![image](https://user-images.githubusercontent.com/85096116/165035924-0bdf5fa0-1b4a-43a3-a5a8-38df3533402d.png)
> 2. 在defaultSettings.ts文件中设置primaryColor
>    ![image](https://user-images.githubusercontent.com/85096116/165035842-7d6ed5e1-220f-4e6c-8f3d-28530cd919fd.png)

雀氏，我把那个SettingDrawer组件取消了。那我正式发布，是不能携带那个的呀？请问怎么处理呢

**Comment by ALostKing** [comment]
![image](https://user-images.githubusercontent.com/85096116/165207588-f64acdbd-bcff-4239-b3bb-4971e3fea081.png)
@windman-only

**Comment by windman-only** [comment]
> ![image](https://user-images.githubusercontent.com/85096116/165207588-f64acdbd-bcff-4239-b3bb-4971e3fea081.png) @windman-only
我也看到这个辣，我以为他指的是 拷贝功能

**Comment by windman-only** [comment]
> ![image](https://user-images.githubusercontent.com/85096116/165207588-f64acdbd-bcff-4239-b3bb-4971e3fea081.png) @windman-only

您好，我这块生产环境打包后，还是出现这个配置栏了，这个要怎么处理呢

**Comment by Lutreer** [comment]
> 1. 检查一下app.tsx文件是否设置了.
>    ![image](https://user-images.githubusercontent.com/85096116/165035924-0bdf5fa0-1b4a-43a3-a5a8-38df3533402d.png)
> 2. 在defaultSettings.ts文件中设置primaryColor
>    ![image](https://user-images.githubusercontent.com/85096116/165035842-7d6ed5e1-220f-4e6c-8f3d-28530cd919fd.png)

开发环境也不想显示，仅注释不可以吗？

**Comment by windman-only** [comment]
> 

注释了的话，这个自定义主题色就不生效了呀，我目前build打包放到服务器，还是有这个配置栏

**Comment by yqcs** [comment]
> SettingDrawer

打包之后还有怎么搞？注释了的话黑白就切换不了了

**Comment by windman-only** [comment]
> > SettingDrawer
> 
> 打包之后还有怎么搞？注释了的话黑白就切换不了了

是呀注释了就无法切换，目前我也遇到这个问题

**Comment by darkfiredarkhalo** [comment]
咦, 没解决怎就关了呢? issue太多影响绩效了?

**Comment by windman-only** [comment]
> 

解决了😂

**Comment by yqcs** [comment]
> 

怎么解决的。

**Comment by windman-only** [comment]
> > 
> 
> 怎么解决的。

我直接把那个 控制栏 给了个css, display: none
