### ISSUE TITLE
🧐[问题] Pro demo工程的部署后logo.svg出不来

### ISSUE THREAD

**Issue by ldwonday** [ant-design/ant-design-pro#9769]
将Pro的demo部署到服务器（非根目录）上发现logo.svg出不来，原因是因为使用了```<img alt="logo" src="/logo.svg" />```使用了根路径。这里如何能让logo.svg出来呢？设置了base也不起作用。需要设置相对路径吗？

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy/

看看这里
