### ISSUE TITLE
 Layout confused of Description component which as a content of PageHeaderLayout in IE 11

### ISSUE THREAD

**Issue by gucciwu** [ant-design/ant-design-pro#977]
DescriptionList layout confused when it contained by PageHeaderLayout as content under IE11, see following pics for detail

![image](https://user-images.githubusercontent.com/6937570/36656231-4efdf12e-1b02-11e8-9f94-6671fcdb2c1a.png)

In Chrome is OK
![image](https://user-images.githubusercontent.com/6937570/36656216-30db4b38-1b02-11e8-95f4-f02610e0a0cc.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/commit/7176b4ac74fae1ace1b93f52e018a48813d50b0b
