### ISSUE TITLE
🧐[问题]使用yarn create umi my-app并没有出现ant design pro的选项

### ISSUE THREAD

**Issue by 191830230** [ant-design/ant-design-pro#9770]
### 🚑 其他信息

![1](https://user-images.githubusercontent.com/90442779/164456847-f21075f3-57af-4f19-bd24-579581439109.png)

**Comment by wuwu14321** [comment]
有一样的问题

**Comment by TangDeYu** [comment]
有一样的问题

**Comment by TangDeYu** [comment]
@chenshuai2144

**Comment by TangDeYu** [comment]
@chenshuai2144 辛苦大佬帮忙看下～

**Comment by Chryseis** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/13757352/164512134-cc91e2b8-7ef8-41de-9d7a-3aba38e94f6d.png">
没有文档的pro 选项

**Comment by sunny8cj** [comment]
一样的问题，直接默认的umi提取结束了，没有选项目类型

**Comment by sufaith** [comment]
+1 没有选项目类型

**Comment by chenshuai2144** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/8186664/164958104-1d113a72-1257-411c-8ac0-9a8812887111.png">


看起来是云谦老师新版本影响到你们了

**Comment by chenshuai2144** [comment]
周五已经解决了，大家更新一下重新试试
