### ISSUE TITLE
🧐[问题] yarn create umi 没有ant-design-pro 选项

### ISSUE THREAD

**Issue by DuncanXiao** [ant-design/ant-design-pro#9773]
### 🧐 问题描述
文档里面yarn create umi 会有ant-design-pro 选项，但是现在没有了，ant-design-pro选项不见了，无法创建各种类型的项目了.这是为什么？

<img width="507" alt="image" src="https://user-images.githubusercontent.com/34067083/164512811-6ef6f3cd-1180-4563-9a79-d2cdf93762d6.png">

**Comment by weixiaozhan** [comment]
是不是刚刚装这个是4.0版本的问题啊？没做好测试？

**Comment by doraemonxxx** [comment]
I have the same issue and I can't resolve it. is there any workaround to solve it?

**Comment by hengqu4** [comment]
+1,macOS 10.15.7

**Comment by KirillSBarsukov** [comment]
+1, mac 12.3.1, m1

**Comment by flycj** [comment]
+ 1

**Comment by yaoboqin** [comment]
+1 mac 11.6.4

**Comment by 1adybug** [comment]
尝试全局安装一下 yarn global add create-umi@0.27.0，在项目文件夹中直接 create-umi 即可

**Comment by 1adybug** [comment]
> 尝试全局安装一下 yarn global add create-umi@0.27.0，在项目文件夹中直接 create-umi 即可

或者不全局安装直接 npx create-umi@0.27.0

**Comment by kangyana** [comment]
+1 mac 11.5.2

**Comment by shuaizhouliu** [comment]
没有人来解决这个问题嘛？

**Comment by Es-Rell** [comment]
+1，Mac M1 12.3.1

**Comment by kangyana** [comment]
使用0.27版本可以创建ant-design-pro 。
1. 建一个文件夹，yarn add create-umi@0.27.0
2. package.json 添加script, start: create-umi
3. yarn start xxx(项目名)

**Comment by shuaizhouliu** [comment]
> > 尝试全局安装一下 yarn global add create-umi@0.27.0，在项目文件夹中直接 create-umi 即可
> 
> 或者不全局安装直接 npx create-umi@0.27.0

用这个方案 暂时可以

**Comment by chenshuai2144** [comment]
周五解决了，清空重新来

**Comment by LJZJIANG** [comment]
> 周五解决了，清空重新来

还是没有解决呢……

**Comment by LJZJIANG** [comment]
> > > 尝试全局安装一下 yarn global add create-umi@0.27.0，在项目文件夹中直接 create-umi 即可
> > 
> > 
> > 或者不全局安装直接 npx create-umi@0.27.0
> 
> 用这个方案 暂时可以

这个方法确实可以，但是只能选择**simple**模版，如果选择**complete**项目跑不起来……
