### ISSUE TITLE
保存至initialState的defaultSettings.ts配置里的title信息在返回登陆页后丢失

### ISSUE THREAD

**Issue by rhyme97** [ant-design/ant-design-pro#9776]
### 🐛 bug 描述
试图将defaultSettings.ts中的title信息作为登陆页的标题，通过initialState去获取，初次取值正常，登陆后再返回登陆页面，title属性直接丢失了

> 使用了create-umi创建的simple模板项目，默认是将defaultSettings.ts的配置在app.tsx中通过getInitialState保存起来了，然后就在登陆页打印：`initialState?.settings?.title`
### 📷 复现步骤
1. 初始进入登陆页，看到控制台打印`Ant Design Pro`
2. 登陆成功跳转至主页后在点击浏览器回退返回至登陆页，看到控制台打印`initialState?.settings?.title`的结果是`undifined`
3. 打印`initialState?.settings`再重复操作，发现返回登录页后里面的属性只少了title

### 🏞 期望结果
title应该正常获取

### 💻 复现代码
![image](https://user-images.githubusercontent.com/60975123/164585162-913413af-6d99-4e4b-bf39-4bd0c7e86f51.png)

### © 版本信息

![image](https://user-images.githubusercontent.com/60975123/164585454-530e4802-e326-446b-a62a-ac58e23f8909.png)

**Comment by chenshuai2144** [comment]
这个是异步的，你在useEffect 里面配置吧

**Comment by BaoXianSheng** [comment]
页面切换，title就丢失了，navTheme 不会丢失，这里面的title是做了什么操作嘛
`  if (ignorePaths.findIndex((item) => item === history.location.pathname) === -1) {
    currentUser = await fetchUserInfo();
    const settings = defaultSettings as Partial<LayoutSettings>;
    settings.title = currentUser!.organization.name;
    settings.navTheme = 'realDark';
    return {
      fetchUserInfo,
      settings,
      storeInitialState,
      currentUser,
    };
  }`
