### ISSUE TITLE
🐛[BUG]请求前拦截 authHeaderInterceptor 中获取getInitialState中变量有问题。

### ISSUE THREAD

**Issue by longa30** [ant-design/ant-design-pro#9777]
### 🐛 bug 描述

```
const authHeaderInterceptor = async (url: string, options: RequestOptionsInit) => {
  const initialState = await getInitialState();//一直处于卡死状态
  // console.log(initialState);
  // const { initialState, setInitialState } = useModel('@@initialState');//这里是无法http请求、提示这里的错误errorHandler
   console.log(initialState?.currentStoreIds);
}
```
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.19]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. win10]

**Comment by chenshuai2144** [comment]
里面不是hooks，不能这么用的。

你是要实现什么需求？
如果是token 建议存到cookie 或者是 localstrong

**Comment by longa30** [comment]
![image](https://user-images.githubusercontent.com/17867961/167439538-ab8cdff3-2745-4360-adce-d98708abd19c.png)
sessionStorage /  localStorage等方法没办法同步这里的选择。。但是再authHeaderInterceptor 需要用到这里的id。这么多天一直没找到解决方案。
