### ISSUE TITLE
🐛[BUG] Browser history does not work with custom URL parameters after build

### ISSUE THREAD

**Issue by mortymike** [ant-design/ant-design-pro#9778]
### 🐛 Using ant-design-pro v5, I am attempting to use parameter routing described here:
https://pro.ant.design/docs/router-and-nav#routing-with-parameters

Both Browser and Hash history (defined in config.ts) work when using development server (npm run start, or npm run start:dev), But Browser history does not work when deploying the application (after npm run build, using files in the dist/ directory). User can not directly access a URL with parameters using Browser history in production environment (after npm run build)

All normal routes (routes without custom parameters) work OK with both Browser and Hash history.

Here is a summary of the configurations that work and do not work:
Environment                                               History Type         Working Correctly
dev (npm run start:dev)                              Hash                      Yes
dev (npm run start:dev)                              Browser                 Yes
prod (npm run build, using httpd)             Hash                      Yes
prod (npm run build, using httpd)             Browser                 NO🐛

### 📷 Steps to reproduce

1. Clone Use latest ant-design-pro v5
2. Change history type in config.ts to "browser"
3. Add route with custom URL parameter
4. npm run build and deploy on production server
5. Try to access custom route directly does not work (changing location within the app via history.push() does work correctly). Ant design pro does not handle the request, and Httpd 403 error returned 🐛

### 🏞 Expected results

Expected result is that I can access a URL directly using both Browser and Hash history on development server, as well as production server. However, behavior after npm run build is not the same for Browser history only.

### © Version Information

- Ant Design Pro version: [e.g. 5.2.0]
- umi version ^3.5.0
- Browser environment Apache (httpd)
- Development Environment [e.g. mac OS] mac OS

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy

look here

**Comment by mortymike** [comment]
Thank you! That pointed me in the correct direction. In case any one needs this in the future, here is the solution that worked for me:

in config.ts:
`exportStatic: {}`

in my Apache httpd VirtualHost config:
`<VirtualHost *:443>

   ...

    # Route in routes.ts with custom url parameters configured as:
    # { path: '/dashboard/:page', hideInMenu: true, name: 'analysis', component: './Dashboard/Analysis' }

   # Here is the corresponding rewrite rule
    RewriteEngine On
    RewriteRule   "^/dashboard/(.+)"  "/dashboard/:page/index.html"  [QSA,L]

    ....

</VirtualHost>`

Be sure that the /dist/ directory does contain dashboard/:page/index.html file.

Thanks again for the help!
