### ISSUE TITLE
🧐[问题] how to modify sidebar menu

### ISSUE THREAD

**Issue by doraemonxxx** [ant-design/ant-design-pro#9779]
### 🧐 问题描述
I want to modify  (add tooltip with description to its submenus) the sidebar menu in ant design pro but I cant seem locate the file and code. I assume the sidebar is already built-in in pro?

### 💻 示例代码
No sample code.

### 🚑 其他信息
**Edit**
ant design pro latest version
umijs latest version
windows 10 OS
node v16.14.2
React JS

**Thanks in advance!**

**Comment by longa30** [comment]
![image](https://user-images.githubusercontent.com/17867961/164817076-6290366d-06f2-4d09-b294-e4c60aaead09.png)
我也很想自定义成这种样式

**Comment by chenshuai2144** [comment]
https://next-procomponents.ant.design/components/layout#收起时展示-title

看看这个

**Comment by doraemonxxx** [comment]
hello, there @chenshuai2144 , the ant design pro with umijs doesn't have a file with a sidebar component, and the routes are defined in config.js. I can't seem to understand the examples provided since both are constructed in different ways

**Comment by vitalijalbu** [comment]
> ![image](https://user-images.githubusercontent.com/17867961/164817076-6290366d-06f2-4d09-b294-e4c60aaead09.png) 我也很想自定义成这种样式

Hi, did you found a way for that?
