### ISSUE TITLE
关于与服务端数据交换的数据无法实时显示更新

### ISSUE THREAD

**Issue by heibais** [ant-design/ant-design-pro#978]
在routes里面使用dispatch，调用model发送请求，获取到数据存入state后，在routes里面不能实时显示获取到的数据，这个问题困扰了很久，希望有人能帮忙解答下，非常感谢！！！

**Comment by heibais** [comment]
![tim 20180227110243](https://user-images.githubusercontent.com/34224645/36708527-5a3312fc-1bae-11e8-8f57-1314d9e50a42.png)
![tim 20180227110625](https://user-images.githubusercontent.com/34224645/36708534-645bceae-1bae-11e8-99cf-f502641af038.png)
感谢你的回答，脚手架里面的页面没有涉及到这一方面的

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically
