### ISSUE TITLE
🐛[BUG]项目部署后，浏览器刷新后，url pathname尾部会多出一个 /

### ISSUE THREAD

**Issue by wh77572** [ant-design/ant-design-pro#9781]
### 🐛 bug 描述

项目部署后，浏览器刷新后，url pathname尾部会多出一个 /，

#9140   https://github.com/ant-design/ant-design-pro/issues/9140  并未能解决问题

1、关闭exportStatic，页面刷新Failed to load resource，直接404
2、不关闭则会加上/

官方预览页同样有这个问题https://preview.pro.ant.design/  刷新后，末尾会加上/

### 📷 复现步骤

1、在当前页刷新
2、复制当前链接在新窗口打开

### 🏞 期望结果

项目部署后，浏览器刷新后，url pathname正常

### 💻 复现代码

exportStatic: {},

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by iainlau** [comment]
换成 nginx 的 try_files 到 index.html 就行。

**Comment by wh77572** [comment]
> 
好的  我来试下

**Comment by wh77572** [comment]
> 换成 nginx 的 try_files 到 index.html 就行。

好的   我等下来试下
