### ISSUE TITLE
🐛[BUG]只有一级菜单时，菜单收缩，快速切换菜单时菜单的tooltip鼠标移走之后不会消失

### ISSUE THREAD

**Issue by qq1170623178** [ant-design/ant-design-pro#9789]
### 🐛 bug 描述

只有一级菜单时，菜单收缩，快速切换菜单时菜单的tooltip鼠标移走之后不会消失

### 📷 复现步骤

 经过测试：如果去掉页面echarts图表或者切换的时候过一会鼠标再移开，不会出现此类问题，有可能是页面元素过多加载卡住了菜单的tooltip？

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
![1651050444(1)](https://user-images.githubusercontent.com/43264733/165483744-4b1a9d71-4517-4db1-b076-d3d1a5c8356e.jpg)

**Comment by chenshuai2144** [comment]
升级一下antd 版本现在ok了

**Comment by LamdoHeaven** [comment]
![image](https://user-images.githubusercontent.com/45940666/179714539-77df548b-54c4-4e64-aa1c-b55b31d8e856.png)
二级菜单也会
