### ISSUE TITLE
form 里能添加和label 并列的元素吗？

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#979]
![image](https://user-images.githubusercontent.com/183884/36708539-6bf798c8-1bae-11e8-8be5-8b7b0cd78eb0.png)

**Comment by ddcat1115** [comment]
FormItem 生成的结构是确定的（label+wrapper），你具体要实现什么需求？

**Comment by WuJiY** [comment]
![image](https://user-images.githubusercontent.com/183884/36716723-4e1bc112-1bd6-11e8-8b5f-f881b37d844d.png)

实现这样的功能。现在固定宽度是可以解决的，就是想额外增加几列，还能自适应，而不单纯通过固定宽度来解决

**Comment by ddcat1115** [comment]
没太看明白，是要多列共用一个label？可以通过嵌套栅格和FormItem实现 [demo](https://ant.design/components/form-cn/#components-form-demo-validate-static) 或者简单的指定控件的百分比，具体用哪种要看你提示信息的展示需求

**Comment by WuJiY** [comment]
恩 是多列公用一个lable 。其实就是要实现个类似这个的结构
FormItem解析出来第一个Row
<Row>
<col>label</col>
<col>wrapper</col>
<Row>
FormItem解析出来第二个Row
<Row>
<col>label</col>
<col>wrapper</col>
<col>extra点击添加产品</col>
<Row>
主要实现在不设置具体宽度的情况下第二个Row里的前两个col 要和第一个Row的两个col对齐.。extrar内容则显示在第三列

**Comment by ddcat1115** [comment]
你把 label 写在外层 FormItem，里面再用 Row Col 来对每组控件进行布局就可以了吧
