### ISSUE TITLE
🧐[问题]从app.tsx来看，在初始化获取用户信息必须要用getInitialState和plugin-model这2个插件?

### ISSUE THREAD

**Issue by zhugexinxin** [ant-design/ant-design-pro#9790]
### 🧐 问题描述
从app.tsx来看，在初始化获取用户信息必须要用getInitialState和plugin-model这2个插件?

假设我是用dva，我该如何初始化存储到store上？
是要在getInitialState用上 useDispatch？如果是这个情况下，getInitialState和plugin-model对我是个毫无意义插件。
之前版本还有BasicLayout可以进行设置，目前似乎没找到这类似的入口。。。

**Comment by fangqibin** [comment]
如果app.tsx的配置解决不了你的问题，可以使用自定义BasicLayout。
如果你要用dva，保留v4版本就好了，但是我觉得v5版本的useModel更方便使用。
如果是新项目可以不要用dva那种方式。
