### ISSUE TITLE
🐛[BUG] 配置栏配置好布局样式，点击“拷贝设置”无任何反应

### ISSUE THREAD

**Issue by Mankvis** [ant-design/ant-design-pro#9791]
### 🐛 bug 描述

配置栏配置好布局样式，点击“拷贝设置”无任何反应

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本 [3.5]
- 浏览器环境 [chrome 100]
- 开发环境 [mac OS]

### 🚑 其他信息

<img width="299" alt="image" src="https://user-images.githubusercontent.com/49258868/165664842-4a09cd4d-f4ef-4b2b-bc01-43fbb0ff9544.png">

**Comment by januwA** [comment]
同样的问题

```
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0",
    "@ant-design/pro-table": "^2.71.0",
   "@ant-design/pro-cli": "^2.1.0",
```

```
node --version
v16.14.2
```

**Comment by floki2020** [comment]
半年了 这个问题都没解决吗？现在也是点击没有反应
