### ISSUE TITLE
🐛[BUG]antd pro v5 登入后就报错Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by bluecai520** [ant-design/ant-design-pro#9792]
### 🐛 bug 描述

下载的基础模板，项目启动登入后，以及按F5都会报错。

### 📷 复现步骤
项目启动后，登入
或者，登入后页面刷新

### 🏞 期望结果
消除这个这个错误（错误信息好长，挺哈人的）

### 💻 复现代码
代码未改动过， 下载自antd pro 5.2.0 基础版，直接启动登入。

### © 版本信息
- Ant Design Pro 版本: 5.2.0
- umi 版本 ：3.5.0
- 浏览器环境：Google Chrome 版本 100.0.4896.127（正式版本） （64 位）
- 开发环境：Windows10

### 🚑 其他信息
截图Gif
![rnxyc-mmxt3 (1)](https://user-images.githubusercontent.com/32674213/165711056-2eed36c9-a29d-4072-8f37-53dd495f4836.gif)

**Comment by Mankvis** [comment]
一样的问题，请问解决了吗

**Comment by bluecai520** [comment]
> 一样的问题，请问解决了吗
没有，我自己电脑前两周下载下来的版本是正常的，这个问题是昨天重新下载时才有的。

**Comment by Mankvis** [comment]
> > 一样的问题，请问解决了吗
> 
> 没有，我自己电脑前两周下载下来的版本是正常的，这个问题是昨天重新下载时才有的。

估计是升级了吧，我也是这几天下载直接出现的，还有一个Menu组件20的问题

**Comment by zhoachenIt** [comment]
我也遇到了，解决了吗？

**Comment by chenshuai2144** [comment]
fixed
