### ISSUE TITLE
🐛[BUG] Ant design pro with axios is not compatible

### ISSUE THREAD

**Issue by doraemonxxx** [ant-design/ant-design-pro#9796]
### 🐛 bug 描述
I encountered abnormal behavior when using axios in ant design pro and umijs. Technically I have a laravel app as my API and currently using Sanctum as authentication. When I try to get the sanctum cookie for csrf ( `axios.get('/sanctum/csrf-cookie)` ), axios didn't put the  **X-CSRF-TOKEN**  in the header, that's why I've got **csrf token mismatch** when logging in.

Tried to use CRA with axios as a basic template and axios **X-CSRF-TOKEN**  is perfectly working yet in ant design pro have a bug.

**NOTES**
The laravel API is configured properly. I've tested my backend properly and everything is fine. There's no issue in my API at all. only in Ant design pro with axios. I don't think it's axios problem since axios is working fine in CRA.

**Screenshots**

![image](https://user-images.githubusercontent.com/88119911/165942286-4d2e24e8-fca1-42b2-a8e2-cbf9263ebea7.png)
![image](https://user-images.githubusercontent.com/88119911/165942535-8e086530-a588-4451-9db5-9a8b56780fc7.png)
![image](https://user-images.githubusercontent.com/88119911/165942585-e09c8b0e-4b02-47c7-8331-a448c717817f.png)
![image](https://user-images.githubusercontent.com/88119911/165942613-60ed966c-56a4-4ba4-b769-8ee2ee237e72.png)
![image](https://user-images.githubusercontent.com/88119911/165942800-c8732ec9-0783-486b-84b3-862fd599189f.png)
![image](https://user-images.githubusercontent.com/88119911/165943107-a465953e-8f64-4fb0-b2ba-09f9c2fbc0bc.png)
![image](https://user-images.githubusercontent.com/88119911/165943295-8e42139c-2526-4a24-b8db-f0616d80b700.png)

### 🏞 期望结果
Should have X-CSRF-TOKEN in the header when using axios

### 🚑 其他信息
ant design pro latest version
umijs latest version
windows 10 OS
node v16.14.2
React JS

**Comment by 18854160806** [comment]
我的也是umi开启了之后没有模板

**Comment by chenshuai2144** [comment]
https://github.com/axios/axios/issues/2024

look here
