### ISSUE TITLE
🧐[问题]protable的列设置不能取消左右固定选项吗？

### ISSUE THREAD

**Issue by blueman-lsl** [ant-design/ant-design-pro#9797]
![Lark20220429-203531](https://user-images.githubusercontent.com/57511481/165945564-1c3fb25d-6e6a-46b8-80d8-4ba7b694d122.png)

**Comment by drizzlesconsin** [comment]
[talb components-table-demo-order-column](https://ant.design/components/table/#components-table-demo-order-column=) 这个能帮到你
