### ISSUE TITLE
🧐[问题] How to authenticate route as public and private

### ISSUE THREAD

**Issue by doraemonxxx** [ant-design/ant-design-pro#9798]
### 🧐 问题描述
How to authenticate route as public and private? currently when user is logged in successfully, the user can still access the **/user/login** route, i want to authenticate  it but seems like the umijs routing is different. and when i try to grant an access the route in **/user/login** , the initialState in access function is **undifiend**  even though i already logged in. I cant find out why.

### Expected Output
after user logged in, the **/user/login** route cannot be access and instead it will redirect to dashboard route.

### 🚑 其他信息
React JS
Ant design pro
Umi js

**Comment by chenshuai2144** [comment]
look here 

https://github.com/ant-design/ant-design-pro/blob/486635ef7675226a17335aa49a6d0c80880bfa0b/Dockerfile

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案
在umijs中，你可以通过在路由配置中使用嵌套路由来实现公共和私有路由认证。对于私有路由，你可以使用“权限”来检查是否授权访问该路由。这里提供两种方法来实现项目中的公共和私有路由认证。

#### 方法1: 使用 umijs 提供的access方法
umijs提供了一个名为access的API，它是在路由渲染之前作用的，可以返回用于指示路由是否具有访问权限的布尔值。

这里是示例代码，它演示了如何将用户重定向到登录页面以进行身份验证，并在用户成功登录后将其重定向回默认的私有路由：

```jsx
import Redirect from 'umi/redirect';

export default ({ children, location: { pathname } }) => {
  const authInfo = getAuthority();
  const isLogin = authInfo && authInfo[0] !== 'guest';
  const isPublic = ['/user/login'].includes(pathname);
  
  if (!isLogin && !isPublic) {
    return <Redirect to="/user/login" />;
  }
  
  if (isLogin && isPublic) {
    return <Redirect to="/" />;
  }
  
  return children;
};
```

#### 方法2：使用react-router-config
react-router-config是一个用于简化配置和渲染的工具，可以让你将路由配置从模板循环迭代中抽取出来。下面的代码演示了如何在使用react-router-config时从身份验证中返回路由配置。它还使用了一个私有路由包装器组件，用来检查用户是否授权访问该路由。

```jsx
import { Route, Switch, Redirect } from 'react-router-dom';
import { renderRoutes } from 'react-router-config';
import PrivateRoute from './PrivateRoute';

const routes = [
  {
    path: '/user/login',
    component: LoginPage,
    exact: true,
    public: true, // public routes
  },
  {
    path: '/',
    component: DashboardPage,
    exact: true,
    private: true, // private routes
  },
];

export default function AppRouter() {
  return (
    <Switch>
      {renderRoutes(
        routes.map(route => ({
          ...route,
          component: route.private ? PrivateRoute : Route,
        })),
      )}
      <Redirect to="/user/login" />
    </Switch>
  );
}
```

在上述代码中，每个路由都有一个与之相关联的"public"或"private"属性，以指示该路由是公共还是私有。"PrivateRoute"组件是路由认证的核心部分。它返回真正的路由组件，如果用户未经身份验证，则会将其重定向到指定的登录页面。

```jsx
import { Route, Redirect } from 'react-router-dom';

export default function PrivateRoute({ component: Component, ...rest }) {
  const authInfo = getAuthority();
  const isLogin = authInfo && authInfo[0] !== 'guest';

  return (
    <Route
      {...rest}
      render={props =>
        isLogin ? <Component {...props} /> : <Redirect to="/user/login" />
      }
    />
  );
}
```

#### 参考文档
- [Umijs 认证路由处理](https://umijs.org/zh-CN/docs/routing)
- [React路由配置React Router Config](https://juejin.cn/post/6844903934055006200)
