### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by syozzz** [ant-design/ant-design-pro#9799]
![QQ截图20220430182310](https://user-images.githubusercontent.com/39989549/166101768-ab51cdf5-5102-4980-b2d8-b03b4f119031.png)
请问这种情况可能是什么原因导致的，右侧实际页面和面包屑中的标题都读取了 locale 中的 menu.js 的配置了，为什么左边子菜单栏不读取呢？还是显示的配置的 name 的 key。
配置内容：

{
    name: 'query',
    icon: '',
    path: '/query',
    routes: [
      {
        name: 'year',
        path: 'year',
        component: './Query'
      },
      {
        name: 'detail',
        path: 'detail',
        component: './Query/QueryDetail',
      },
    ]
  }

**Comment by cxqy** [comment]
楼主解决了么？
