### ISSUE TITLE
关于使用问题

### ISSUE THREAD

**Issue by fmzwy** [ant-design/ant-design-pro#98]
1、昨天刚刚看这个感觉上手还是有定门槛的
2、什么时候出正式版吧啊
3、是否可以弄一个菜单权限从服务器获取的demo

**Comment by afc163** [comment]
1. 😄 
2. https://pro.ant.design/docs/faq#%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E5%9C%A8%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-Ant-Design-Pro%EF%BC%9F
3. #41
