### ISSUE TITLE
为什么我的dragleave方法添加e.preventDefault();后报TypeError: Cannot read property 'preventDefault' of undefined？？

### ISSUE THREAD

**Issue by chluknight** [ant-design/ant-design-pro#980]
**TypeError: Cannot read property 'preventDefault' of undefined**
DragglableDiv._this.dragLeave
D:/workspaces/ant-design-pro/src/routes/AntDesign/DraggableDiv.js:32
  29 | };
  30 | 
  31 | _this.dragLeave = function (e) {
> 32 |   e.preventDefault();
  33 |   console.log("dragLeave---", e);
  34 | };
  35 |

**Comment by afc163** [comment]
不了解，目测和 pro 没有关系。
