### ISSUE TITLE
🐛[BUG]子菜单标题不读取 locale 配置

### ISSUE THREAD

**Issue by syozzz** [ant-design/ant-design-pro#9800]
![QQ截图20220430182310](https://user-images.githubusercontent.com/39989549/166102011-893ae3e1-33ee-4b89-816c-4e71c20b5253.png)
请问这种情况可能是什么原因导致的，右侧实际页面和面包屑中的标题都读取了 locale 中的 menu.js 的配置了，为什么左边子菜单栏不读取呢？还是显示的配置的 name 的 key。
配置项：
{
    name: 'query',
    icon: '',
    path: '/query',
    routes: [
      {
        name: 'year',
        path: 'year',
        component: './Query'
      },
      {
        name: 'detail',
        path: 'detail',
        component: './Query/QueryDetail',
      },
    ]
  }

**Comment by cxqy** [comment]
楼主解决了么？

**Comment by syozzz** [comment]
> 楼主解决了么？

没解决哦，我发现不在 locale 中配置，name 直接写中文也行。下面这个问题好像有提到是 pro-layout 版本的问题，可以参考一下。
#9810
