### ISSUE TITLE
想问一下umi-request发送formdata重复设置content-type这个bug在新的npm发行版上面修复了吗🐛[BUG]

### ISSUE THREAD

**Issue by crazyCoderLi** [ant-design/ant-design-pro#9808]
### 🐛 bug 描述
想问一下umi-request发送formdata重复设置content-type这个bug在新的npm发行版上面修复了吗，"@umijs/openapi": "^1.4.4", 以及"@umijs/plugin-openapi": "^1.3.*", 生成出来的依旧重复设置了这个header字段，会不会是我操作的问题
https://github.com/ant-design/ant-design-pro/issues/9080

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
手动写一个 serve吧，这个生成逻辑很复杂
