### ISSUE TITLE
🐛[BUG] 有关菜单的错误显示问题、蛮严重的。

### ISSUE THREAD

**Issue by Xiaochena** [ant-design/ant-design-pro#9810]
### 🐛 bug 描述

```
// 以下是我初始化后修改的路由结构、我增加了一端路由
{
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        icon: 'smile',
        component: './Welcome',
      },
// #region 增加的路由、可以看到我注释了name
      {
        path: '/admin/sub-page2',
        // name: 'sub-page2',
        icon: 'smile',
        component: './Welcome',
      },
// 可以看到我使用了 hideInMenu
      {
        path: '/admin/sub-page3',
        hideInMenu: true,
        icon: 'smile',
        component: './Welcome',
      },
// #endregion
      {
        component: './404',
      },
    ],
  },
```
可以看到我注释了路由的`name`、根据 `proComponents`中 的描述
> hideInMenu 会把这个路由配置在 menu 中隐藏这个路由，name 不填会有相同的效果
一直以来的表现也是这样的、但是在最近的更新中、没写name的也出现了、并且使用`hideInMenu`也不会隐藏

![image](https://user-images.githubusercontent.com/48006842/166464540-94d825ca-20a1-48e5-b7bd-c1e8ccbe1ec2.png)

![image](https://user-images.githubusercontent.com/48006842/166464480-56a94cf8-e73b-48bc-b482-ee4244fe2380.png)

甚至我们可以发现、`component: './404',`，也出现在了菜单上

### 📷 复现步骤
初始化一个typescript 、antd pro后使用以下路由
```
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        icon: 'smile',
        component: './Welcome',
      },
      {
        path: '/admin/sub-page2',
        // name: 'sub-page2',
        icon: 'smile',
        component: './Welcome',
      },
      {
        path: '/admin/sub-page3',
        hideInMenu: true,
        icon: 'smile',
        component: './Welcome',
      },
      {
        component: './404',
      },
    ],
  },
```

### 🏞 期望结果
隐藏本改隐藏的菜单

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本
- 浏览器环境
- 开发环境 [window 10]

### 🚑 其他信息
在我这里不仅仅是最新版本出了问题、甚至是重新跑过一边`npm install`的老项目也出现了这个问题

**Comment by blueiky** [comment]
hideChildrenInMenu 也是如此，新建个项目想要隐藏子路由，失效了，但hideInMenu是正常的，这个就很离谱

**Comment by liucys** [comment]
我也是存在同样的问题，二级菜单的name无法读取menu.js中的内容进行相应的渲染。

**Comment by Xiaochena** [comment]
现在我没办法复现了、搞得我好难受啊

**Comment by Xiaochena** [comment]
> hideChildrenInMenu 也是如此，新建个项目想要隐藏子路由，失效了，但hideInMenu是正常的，这个就很离谱

现在我没办法复现了

**Comment by liucys** [comment]
@Xiaochena 你这是问题解决了吗？

> > hideChildrenInMenu 也是如此，新建个项目想要隐藏子路由，失效了，但hideInMenu是正常的，这个就很离谱
> 
> 现在我没办法复现了

**Comment by blueiky** [comment]
> > hideChildrenInMenu 也是如此，新建个项目想要隐藏子路由，失效了，但hideInMenu是正常的，这个就很离谱
> 
> 现在我没办法复现了

我这边是Ant Design Pro5.2.0版本不行，对应的@ant-design/pro-layout版本是6.35.0
但在Ant Design Pro5.0.0上面是正常的

**Comment by Xiaochena** [comment]
目前、尝试、
@ant-design/pro-layout版本6.35.0、antd版本4.20.0。没有问题
@ant-design/pro-layout版本6.15.3、antd版本4.17.0。没有问题
我这边之前是固定了antd的版本。
怀疑是antd的menu或者说是rc-menu发生改变、pro-layout使用了4.20.0 升级用法
![image](https://user-images.githubusercontent.com/48006842/166897752-4ba838a7-5f3f-4191-bdc6-dcbef2792431.png)

**Comment by liucys** [comment]
我尝试升级了一下@ant-design/pro-layout版本为6.37.0问题解决了。我的antd版本是4.19.0。看起来确实是@ant-design/pro-layout版本的问题。
看了一下文档。@ant-design/pro-layout组件，现在可以直接写
```js
{
  path:"/overview",
  name:"中文名称",
  ....
}
```
看起来这样写就不用配置menu.js文件了好像

**Comment by barakaxp** [comment]
> 6.37.0

This worked for me too.
