### ISSUE TITLE
🧐[问题] Permission/Authority

### ISSUE THREAD

**Issue by doraemonxxx** [ant-design/ant-design-pro#9811]
### 🧐 问题描述
Since the authority is depreciated for routers, i can still use permission such as access property.
My question is how to set multiple values in access property in config.js routes?

Expected output should be:
access can handle value in array

`routes: [{
  path: '/admin',
  access: ['admin', 'super_admin', 'developer']
}]`

### 🚑 其他信息
Ant design pro
umi js
React js

**Comment by allan8212** [comment]
同问

**Comment by zjfresh** [comment]
这个应该提给 [umijs/plugins](https://github.com/umijs/plugins)
