### ISSUE TITLE
🐛[BUG] HMR not working

### ISSUE THREAD

**Issue by doraemonxxx** [ant-design/ant-design-pro#9812]
### 🐛 bug 描述
Hello there, The HMR is not working on all pages except for the login page, but sometimes the login page HMR doesn't work also. the document says that HMR is built-in and I don't know why the bug happens. Please check.

Thank you

### © 版本信息
- Ant Design Pro latest
- umi latest
- Google Chrome

**Comment by chenshuai2144** [comment]
Generally, the failure is caused by different capitalization.
You can check your import
