### ISSUE TITLE
🐛[BUG]引入外部样式的时候，如果样式带有-符合就会报错

### ISSUE THREAD

**Issue by liyi563257046** [ant-design/ant-design-pro#9813]
例如div className={utils.my-color-page}，页面就会报错，我分析是因为“-”这个符号影响了系统，不知道该怎么解决

**Comment by liyi563257046** [comment]
`例如
<div className={utils.row-cols-1}>
，页面就会报错，我分析是因为“-”这个符号影响了系统，不知道该怎么解决`

**Comment by liyi563257046** [comment]
更准确的说，如果样式是.one-two只带有一个“-”符号，生成页面的时候就会被antdesign系统替换成“NaN”；
如果样式是.one-two-three这种形式带有两个“-”符号，生成也页面的时候就会报错。

**Comment by fangqibin** [comment]
可以用下划线

**Comment by liyi563257046** [comment]
> 可以用下划线

因为引入的是外部css，里面有大量的“-”，不好修改。如果是自己写的我就直接删掉符号就好了。

**Comment by fangqibin** [comment]
> > 可以用下划线
> 
> 因为引入的是外部css，里面有大量的“-”，不好修改。如果是自己写的我就直接删掉符号就好了。

那你只能当做全局样式。

**Comment by tangbzai** [comment]
如果引入的时候没有报错，只是写了`className={utils.my-color-page}`的时候报错的话。
可以试试改成`className={utils['my-color-page']}`
