### ISSUE TITLE
🧐Support for React 18

### ISSUE THREAD

**Issue by askurat** [ant-design/ant-design-pro#9814]
### 🧐
Is there going to be support for React 18? If so, do you have a timeline?

**Comment by kisslove** [comment]
+1

**Comment by pkaq** [comment]
+1

**Comment by chenshuai2144** [comment]
已经支持了，有那些地方还不能支持吗？

**Comment by kisslove** [comment]
@chenshuai2144 我看项目里面目前的react包还是17版本的，是哪个版本开始支持的？

**Comment by webmatrixxxl** [comment]
React 18 support is needed

**Comment by chenshuai2144** [comment]
https://github.com/umijs/umi/pull/8031

升级到本地的react 到18就可以使用了
