### ISSUE TITLE
🧐 [问题]antdPro是否有配置项目中所有button默认尺寸的配置项呢

### ISSUE THREAD

**Issue by lvxiaoxing** [ant-design/ant-design-pro#9815]
### 🧐 问题描述
比如说在config.ts中配置button默认尺寸为small，全局button只要没有size属性都为small

antd提供了ConfigProvider组件，里面有一个componentSize属性，但是是控制全部组件的size

所以想请问antdPro是否有这样的配置项

**Comment by fangqibin** [comment]
估计要单独抽一个组件出来自定义
