### ISSUE TITLE
🧐[问题] V5版本如何配置请求地址的Base Url？ 

### ISSUE THREAD

**Issue by h1nson** [ant-design/ant-design-pro#9817]
### 🧐 问题描述

以前的版本有request.ts文件可以去配置请求的Base Url， 但V5版本没有找到，请问如何去配置。 
另外加入Mock后，如何区分真实api和mock的api呢？ 现在使用完全没有头绪。

希望能完善一下文档，使用yarn create umi选择Ant design pro模板创建的项目结构与官网描述的不一致。

非常感谢！

**Comment by fangqibin** [comment]
https://github.com/umijs/umi-request

**Comment by longa30** [comment]
可以阅读  https://pro.ant.design/zh-CN/docs/request

我的代码如下。
export const request: RequestConfig = {
  prefix: 'http://www.eju.com/admin',
。。。
}

**Comment by h1nson** [comment]
@longa30 dev环境它默认是走的代理，我生成的项目模板应该在哪个文件进行配置？ app.tsx?  另外prefix设置https好像不起作用。
