### ISSUE TITLE
在线求解

### ISSUE THREAD

**Issue by ADheight** [ant-design/ant-design-pro#9818]
初次启动antdesignpro项目是出现以下两个错误
ERROR in ./node_modules/swagger-ui-react/swagger-ui.js 2:107055-107070
Module not found: Error: Can't resolve 'btoa' in 'D:\A-AZJ\AntDesignPro\ant-design-proV5\node_modules\swagger-ui-react'
 @ ./node_modules/swagger-ui-react/index.js 13:0-61 59:15-35 65:53-65
 @ ./src/.umi/.cache/.mfsu/mf-va_swagger-ui-react.js 1:0-33 2:15-16
 @ container entry ./swagger-ui-react[0]
webpack compiled with 1 error
null
Error: build failed
    at D:\A-AZJ\AntDesignPro\ant-design-proV5\node_modules\@umijs\bundler-webpack\lib\index.js:172:29
    at D:\A-AZJ\AntDesignPro\ant-design-proV5\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114591:14
    at processQueueWorker (D:\A-AZJ\AntDesignPro\ant-design-proV5\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114529:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by kakuilan** [comment]
我也是这两天遇到，删除了node_moduels，重新安装后启动报错
 error  in ./node_modules/swagger-ui-react/swagger-ui.js

Module not found: Error: Can't resolve 'btoa' in 'D:\www\_gitee\admin\node_modules\swagger-ui-react'

ERROR in ./node_modules/swagger-ui-react/swagger-ui.js 2:107055-107070
Module not found: Error: Can't resolve 'btoa' in 'D:\www\_gitee\admin\node_modules\swagger-ui-react'
 @ ./node_modules/swagger-ui-react/index.js 13:0-61 59:15-35 65:53-65
 @ ./src/.umi/.cache/.mfsu/mf-va_swagger-ui-react.js 1:0-33 2:15-16
 @ container entry ./swagger-ui-react[0]

webpack compiled with 1 error
null
Error: build failed
    at D:\www\_gitee\admin\node_modules\@umijs\bundler-webpack\lib\index.js:172:29
    at D:\www\_gitee\admin\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114591:14
    at processQueueWorker (D:\www\_gitee\admin\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:114529:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by ADheight** [comment]
> 我也是这才开始遇到问题，删除了node_mods，重新安装了./node_modules/swagger-ui-react/swagger-ui.js 中的错误
> 
> 找不到模块：错误：无法解析“D:\www_gitee\admin\node_modules\swagger-ui-react”中的“btoa”
> 
> ./node_modules/swagger-ui-react/swagger-ui.js 中的错误 2:107055-107070 找不到 模块：错误：无法解析 'D:\www_gitee\admin\node_modules\swagger-ui- 中的 'btoa'反应' @ ./node_modules/swagger-ui-react/index.js 13:0-61 59:15-35 65:53-65 @ ./src/.umi/.cache/.mfsu/mf-va_swagger-ui -react.js 1:0-33 2:15-16 @ 容器入口 ./swagger-ui-react[0]
> 
> webpack 编译时出现 1 个错误 null Error: build failed at D:\www_gitee\admin\node_modules@umijs\bundler-webpack\lib\index.js:172:29 at D:\www_gitee\admin\node_modules@umijs\deps\compiled \webpack\5\bundle5.js:114591:14 at processQueueWorker (D:\www_gitee\admin\node_modules@umijs\deps\compiled\webpack\5\bundle5.js:114529:6) at processTicksAndRejections (node:internal/process /task_queues:78:11)

请问，您解决了这个问题了嘛？

**Comment by kakuilan** [comment]
> > 我也是这才开始遇到问题，删除了node_mods，重新安装了./node_modules/swagger-ui-react/swagger-ui.js 中的错误
> > 找不到模块：错误：无法解析“D:\www_gitee\admin\node_modules\swagger-ui-react”中的“btoa”
> > ./node_modules/swagger-ui-react/swagger-ui.js 中的错误 2:107055-107070 找不到 模块：错误：无法解析 'D:\www_gitee\admin\node_modules\swagger-ui- 中的 'btoa'反应' @ ./node_modules/swagger-ui-react/index.js 13:0-61 59:15-35 65:53-65 @ ./src/.umi/.cache/.mfsu/mf-va_swagger-ui -react.js 1:0-33 2:15-16 @ 容器入口 ./swagger-ui-react[0]
> > webpack 编译时出现 1 个错误 null Error: build failed at D:\www_gitee\admin\node_modules@umijs\bundler-webpack\lib\index.js:172:29 at D:\www_gitee\admin\node_modules@umijs\deps\compiled \webpack\5\bundle5.js:114591:14 at processQueueWorker (D:\www_gitee\admin\node_modules@umijs\deps\compiled\webpack\5\bundle5.js:114529:6) at processTicksAndRejections (node:internal/process /task_queues:78:11)
> 
> 请问，您解决了这个问题了嘛？

么有

**Comment by zhoujiaxu2014** [comment]
我也遇到了 。。。。。

**Comment by ADheight** [comment]
> 我也遇到了 。。。。。

您解决了嘛？

**Comment by michaelbennn** [comment]
我也是遇到这个问题，之前用antd pro 5.0.0版本貌似没有这个问题，不知道是不是版本比较新的原因

**Comment by zhoujiaxu2014** [comment]
> > 我也遇到了 。。。。。
> 
> 您解决了嘛？
没

**Comment by KoenigSegg1992** [comment]
同样的问题 :<

**Comment by k-fire** [comment]
yarn add swagger-ui-react
yarn start

**Comment by zhoujiaxu2014** [comment]
> yarn add swagger-ui-react yarn start

好用

**Comment by huang-xiong** [comment]
同样的问题，尝试 npm i -D btoa ，已解决。

**Comment by ADheight** [comment]
> > yarn add swagger-ui-react yarn start
> 
> 好用

我这两个命令进行完msfu只能进行到99%然后伴有7个警告...您有这个问题嘛

**Comment by ADheight** [comment]
> 同样的问题，尝试 npm i -D btoa ，已解决。

谢谢，确实没了

**Comment by puxiao** [comment]
> 同样的问题，尝试 npm i -D btoa ，已解决。

我感觉 `yarn add swagger-ui-react` 是正解，因为 package.json 中本身就有 swagger-ui-react，执行这个只不过是对它的升级而已，而你的安装 `npm i -D btoa` 会额外出现 btoa 这一项。

**Comment by ADheight** [comment]
> > 同样的问题，尝试 npm i -D btoa ，已解决。
> 
> 我感觉 `yarn add swagger-ui-react` 是正解，因为 package.json 中本身就有 swagger-ui-react，执行这个只不过是对它的升级而已，而你的安装 `npm i -D btoa` 会额外出现 btoa 这一项。

我用了 `yarn add swagger-ui-react` 出现了警告，请问这个你们有遇到过吗

**Comment by wangxiaopings** [comment]
> 我也遇到了同样的问题，执行完yarn add swagger-ui-react出现了警告，还是跑不起来
