### ISSUE TITLE
🧐[问题] access.js不执行 怎么回事控制台不打印

### ISSUE THREAD

**Issue by huangtaoSyn** [ant-design/ant-design-pro#9819]

**Comment by fangqibin** [comment]
你这个神仙来了也帮不了你

**Comment by huangtaoSyn** [comment]
> 你这个神仙来了也帮不了你

哎 上面说的keep-alive之类的 我都没用   canAdmin直接设置为false 也没用，

**Comment by huangtaoSyn** [comment]
大佬们 有没有解决的呀

**Comment by fangqibin** [comment]
> 大佬们 有没有解决的呀

能复现的示例代码

**Comment by huangtaoSyn** [comment]
> > 大佬们 有没有解决的呀
> 
> 能复现的示例代码

- access.js文件
   export  default function access(initialState) {
  console.log("initialState+++++++++++++")
  const { currentUser } = initialState || {};
  return {
    canAdmin: currentUser && currentUser.access === 'admin',
    isAdmin:false,
    isEditor:()=>{console.log("run+++++++++++++=================");return false}
  };
}

-   path: '/employeeAdmin',
    name: '招聘管理',
    icon: 'UserAddOutlined',
    access:'isAdmin',

菜单依然显示  且在控制台不会打印
以及将access:'isAdmin',直接对称false 也没有效果

**Comment by fangqibin** [comment]
> > > 大佬们 有没有解决的呀
> > 
> > 
> > 能复现的示例代码
> 
> * access.js文件
>   export  default function access(initialState) {
>   console.log("initialState+++++++++++++")
>   const { currentUser } = initialState || {};
>   return {
>   canAdmin: currentUser && currentUser.access === 'admin',
>   isAdmin:false,
>   isEditor:()=>{console.log("run+++++++++++++=================");return false}
>   };
>   }
> * path: '/employeeAdmin',
>   name: '招聘管理',
>   icon: 'UserAddOutlined',
>   access:'isAdmin',
> 
> 菜单依然显示 且在控制台不会打印 以及将access:'isAdmin',直接对称false 也没有效果

我建议你初始最新项目下来改一下，看看有没有效果。

**Comment by huangtaoSyn** [comment]
我上面自己使用了多页签 我不敢重新搞 项目在催了  我也不知道是不是多页签的影响，现在动态路由 点击也会出现在多页签列表中 想通过将原先的component替换为动态路由的component 也不行，给动态路由 动态添加title 菜单栏又会出现动态路由的列表  



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月10日(星期二) 下午4:44
收件人: "ant-design/ant-design-pro";
抄送: "Author";
主题: Re: [ant-design/ant-design-pro] 🧐[问题] access.js不执行 怎么回事控制台不打印 (Issue #9819)





    
大佬们 有没有解决的呀
  
能复现的示例代码
   
access.js文件
 export  default function access(initialState) {
 console.log("initialState+++++++++++++")
 const { currentUser } = initialState || {};
 return {
 canAdmin: currentUser &amp;&amp; currentUser.access === 'admin',
 isAdmin:false,
 isEditor:()=&gt;{console.log("run+++++++++++++=================");return false}
 };
 }
 
path: '/employeeAdmin',
 name: '招聘管理',
 icon: 'UserAddOutlined',
 access:'isAdmin',
  
菜单依然显示 且在控制台不会打印 以及将access:'isAdmin',直接对称false 也没有效果
  
我建议你初始最新项目下来改一下，看看有没有效果。
 
&mdash;

**Comment by chenshuai2144** [comment]
听起来是状态乱了导致的。估计 keeplive 导致了什么问题吧

**Comment by Liruwei** [comment]
> \config\config.ts ` access: {},`
> 
> 打开这个看看

我也遇到这个问题了，在 config.ts 添加 `access: {}` 之后就可以了。
