### ISSUE TITLE
🐛[BUG]Module not found: Error: Can't resolve 'btoa' 

### ISSUE THREAD

**Issue by pengyuwei** [ant-design/ant-design-pro#9824]
### 🐛 bug 描述

```
npx create-umi myapp
cd myapp/
npm install
npm run start
后端提示：
 ERROR  Failed to compile with 1 errors                                                         12:29:51 PM

 error  in ./node_modules/swagger-ui-react/swagger-ui.js

Module not found: Error: Can't resolve 'btoa' in '/home/ubuntu/adp/myapp/node_modules/swagger-ui-react'


● MFSU █████████████████████████ cache (99%)
 begin idle

✔ Webpack


ERROR in ./node_modules/swagger-ui-react/swagger-ui.js 2:107055-107070
Module not found: Error: Can't resolve 'btoa' in '/home/ubuntu/adp/myapp/node_modules/swagger-ui-react'
 @ ./node_modules/swagger-ui-react/index.js 13:0-61 59:15-35 65:53-65
 @ ./src/.umi/.cache/.mfsu/mf-va_swagger-ui-react.js 1:0-33 2:15-16
 @ container entry ./swagger-ui-react[0]

webpack compiled with 1 error
null
Error: build failed
    at /home/ubuntu/adp/m ya l l/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at /home/ubuntu/adp/myap p/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114591:14
    at processQueueWorker (/home/ubuntu/adp/myapp/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:114529:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### 📷 复现步骤

```
npx create-umi myapp
cd myapp/
npm install
npm run start
```

### 🏞 期望结果

正确编译

### © 版本信息

- Ant Design Pro 版本: 5.2.0
- umi 版本: unknown
- 浏览器环境: chrome 101
- 开发环境: ubuntu 18.04

**Comment by KoenigSegg1992** [comment]
同样出现此bug

**Comment by pengyuwei** [comment]
```
yarn add swagger-ui-react
yarn start
```

问题解决

**Comment by KoenigSegg1992** [comment]
> 

点赞！

**Comment by hesetiema** [comment]
yarn add swagger-ui-react -D

**Comment by xujintao** [comment]
我看到packagejson的devDependencies里面有"swagger-ui-react": "^3.52.0"，按照道理来说npm install或者yarn应该会按照要求去把这个swagger-ui-react拉下来，怎么又要手动去yarn add swagger-ui-react了？

**Comment by frankgo81** [comment]
```
yarn add swagger-ui-react -D
yarn start
```

fixed.

**Comment by ldwonday** [comment]
一样遇到这个问题，烦躁

**Comment by pikadun** [comment]
把openapi，swagger相关代码都删掉就行了

**Comment by liqiujiong** [comment]
![image](https://user-images.githubusercontent.com/5794205/172748716-0ab38ada-a469-4f44-af6d-fa3a8e03f61e.png)
把这三个包删掉，真是越来越脓肿

**Comment by itstunahan** [comment]
**The error I get when I set up the project as js**
**_i need to solve it urgently_**

ReferenceError: styles is not defined
Analysis
.ant-design-pro/src/pages/dashboard/analysis/index.jsx:69
`
  66 |   </Menu>
  67 | );
  68 | const dropdownGroup = (
> 69 |   <span className={styles.iconGroup}>
     | ^  70 |     <Dropdown overlay={menu} placement="bottomRight">
  71 |       <EllipsisOutlined />
  72 |     </Dropdown>
`

![Screen Shot 2022-06-16 at 15 34 38](https://user-images.githubusercontent.com/59246528/174070724-5e102e1c-746d-4d5f-a15e-beb26dcb8fc1.png)

**Comment by zevsdflkjiuxcvb** [comment]
i get this error too
