### ISSUE TITLE
🧐[问题] 获取http401返回码对应的response内容

### ISSUE THREAD

**Issue by wurijie** [ant-design/ant-design-pro#9825]
### 🧐 问题描述

服务端会有返回http code=401的情况，前端需要根据返回内容做进一步的逻辑判断和处理，目前使用自带的request只能拿到一个exception，麻烦指导一下怎么拿到返回内容，谢谢！

**Comment by OxOld** [comment]
https://pro.ant.design/zh-CN/docs/request
中间件 & 拦截器
