### ISSUE TITLE
如何获取login成功后Respose返回的 token

### ISSUE THREAD

**Issue by cdscawd** [ant-design/ant-design-pro#983]
<img width="1152" alt="wx20180227-153018 2x" src="https://user-images.githubusercontent.com/16070662/36715894-2b7466d0-1bd3-11e8-8fde-8de58c899389.png">

**Comment by cdscawd** [comment]
@chenshuai2144

**Comment by WuJiY** [comment]
你后端要返回个token，在login/login 里把他存本地），在request.js 里fetch的时候本地获取token然后添加到header 里

**Comment by cdscawd** [comment]
response.headers.get('authorization')
