### ISSUE TITLE
🐛[BUG] 设置 breakpoint: false时菜单还是会自动收起

### ISSUE THREAD

**Issue by 569202812** [ant-design/ant-design-pro#9831]
### 🐛 bug 描述

app.tsx 设置 `breakpoint: false, collapsedButtonRender: false,` 时还是会自动收起菜单和logo区域不渲染title

### 📷 复现步骤
app.tsx 设置 `breakpoint: false, collapsedButtonRender: false,` 

### 🏞 期望结果
设置时渲染title和不收起菜单

### © 版本信息

- Ant Design Pro 版本: 5.2.0
- umi 版本 ^3.5.0
- 浏览器环境 chorme
- 开发环境 win

### 🚑 其他信息

title未渲染
![image](https://user-images.githubusercontent.com/34082148/167752284-28c11be5-9034-446b-8af8-1690537c9f00.png)

![image](https://user-images.githubusercontent.com/34082148/167752242-39551f00-9dda-415d-9074-ed3e90872502.png)

**Comment by 569202812** [comment]
看着`onCollapse`没处理`breakpoint`，是本来就是这么设置的嘛，可否加个设置或者`breakpoint === false`直接组织掉触发
![image](https://user-images.githubusercontent.com/34082148/167755977-03be4a45-44bf-414c-ad68-9a7360831711.png)

**Comment by chenshuai2144** [comment]
https://ant.design/components/layout-cn/#breakpoint-width

breakpoint 是关掉它的
