### ISSUE TITLE
🧐[问题]菜单消失了

### ISSUE THREAD

**Issue by skiinaurora** [ant-design/ant-design-pro#9834]
### 💻 示例代码

pacakage.json内容
`{
  "name": "ant-design-pro",
  "version": "5.1.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "cross-env SERVE_ENV=idc umi build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "openapi": "umi openapi",
    "playwright": "playwright install && playwright test",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env SERVE_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "test": "umi test",
    "test:component": "umi test ./src/components",
    "test:e2e": "node ./tests/run-tests.js",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.9.0",
    "@ant-design/pro-form": "^1.43.0",
    "@ant-design/pro-layout": "^6.26.0",
    "@ant-design/pro-table": "^2.56.0",
    "@umijs/route-utils": "^2.0.3",
    "antd": "4.18.7",
    "bizcharts": "^4.1.15",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.0.13",
    "rc-util": "^5.14.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10",
    "react-color": "^2.19.3",
    "swagger-ui-react": "^4.11.0",
    "video.js": "^7.17.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@playwright/test": "^1.16.3",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.6.2",
    "@umijs/openapi": "^1.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-dumi": "^1.1.7",
    "@umijs/preset-react": "^1.8.17",
    "@umijs/preset-ui": "^2.2.9",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.3.2",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "swagger-ui-react": "^4.11.0",
    "typescript": "^4.2.2"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "gitHooks": {
    "commit-msg": "fabric verify-commit"
  }
}`

### 🚑 其他信息

菜单内容是配置好了的，也能获取到菜单内容。就是渲染不出来。
![20220511204802](https://user-images.githubusercontent.com/105364939/167853756-6752cacb-9801-48c4-b705-9bac87fad94b.png)

**Comment by wanglihuaya** [comment]
俺也一样

**Comment by wanglihuaya** [comment]
更新下 ant 和 pro-layout就好了

**Comment by echo-machile** [comment]
> 更新下 ant 和 pro-layout就好了

怎么更新

**Comment by echo-machile** [comment]
刚发布的新版本，把
![image](https://user-images.githubusercontent.com/76896357/168417046-ad9f9b45-e0cf-4cc4-86f4-bad68ad8a508.png)
这些组件的符号去掉换成之前的版本号

**Comment by echo-machile** [comment]
所有的pro组件

**Comment by DearVikki** [comment]
ant-design-pro v4 在不久前更新的 @ant-design/pro-layout@6.37.0 及更新版本下会有菜单无法渲染的问题。目测与 https://github.com/ant-design/pro-components/commit/e7606ff 这个 commit 相关。目前大家可以锁死 @ant-design/pro-layout@6.36.0 这一版。

@chenshuai2144 看看是否可以补充下 v4 文档依赖的兼容问题，或者 @pro-components/layout 那边做个兼容

**Comment by lu185** [comment]
dependencies:{    
    "@ant-design/icons": "4.6.2",
    "@ant-design/pro-card": "1.11.13",
    "@ant-design/pro-descriptions": "1.7.8",
    "@ant-design/pro-field": "1.18.2",
    "@ant-design/pro-form": "1.23.0",
    "@ant-design/pro-layout": "6.38.0",
    "@ant-design/pro-table": "2.39.2",
    "@umijs/route-utils": "1.0.37",
    "antd": "4.18.0",
    "classnames": "^2.3.1",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "omit.js": "^2.0.2",
    "qs": "^6.10.1",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "3.5.20",
    "umi-request": "^1.3.5"
}

问题依旧，postMenuData数据是正确的，就是无法渲染。
