### ISSUE TITLE
🐛[BUG] run build后，生产环境配置栏仍然会展现，SettingDrawer去除后，样式就失效了

### ISSUE THREAD

**Issue by yangbinsoft** [ant-design/ant-design-pro#9835]
### 🐛 bug 描述
官方给的demo，下载下来，build后还是有设置

run build后，生产环境配置栏仍然会展现，SettingDrawer去除后，样式就失效了
![image](https://user-images.githubusercontent.com/15042338/168055110-a66de2ba-7581-4f4e-a2a5-684665c08ca3.png)

[Ant Design Pro 预览官网](https://preview.pro.ant.design/dashboard/analysis)

### © 版本信息

- Ant Design Pro 5.0.0

**Comment by yangbinsoft** [comment]
求大佬指教，如何隐藏配置按钮？

**Comment by yangbinsoft** [comment]
`java`
 childrenRender: (children, props) => {
      // if (initialState?.loading) return <PageLoading />;
      return (
        <>
          {children}
          {!props.location?.pathname?.includes('/login') && (
            <SettingDrawer
              disableUrlParams
              enableDarkTheme
              settings={initialState?.settings}
              onSettingChange={(settings) => {
                setInitialState((preInitialState) => ({
                  ...preInitialState,
                  settings,
                }));
              }}
            />
          )}
        </>
      );
    },

**Comment by peng307git** [comment]
同求，我的也有这个问题

**Comment by yangbinsoft** [comment]
我现在去掉了SettingDrawer，用了这种方式了
![image](https://user-images.githubusercontent.com/15042338/169189027-1e0a02c3-3812-4e80-a579-270a0ebf6423.png)

参考网站（静态方法配置）：[https://ant.design/docs/react/customize-theme-variable-cn](https://ant.design/docs/react/customize-theme-variable-cn)

**Comment by guwan** [comment]
我也出现这个问题，不是生产环境没有这个东西的吗

**Comment by zhoujiaxu2014** [comment]
+1

**Comment by chenshuai2144** [comment]
要自己关掉的，可能把官方代码改坏了

**Comment by gaojunxin** [comment]
问题依然存在。
