### ISSUE TITLE
🧐[问题] 在使用table中的树形数据展示的时候 关于dataindex无效

### ISSUE THREAD

**Issue by huangtaoSyn** [ant-design/ant-design-pro#9838]
### 💻 示例代码
{
    title: '栏目名称',
    width: 90,
    key:"name",
    dataIndex: ['sysTopCataName'],  

dataIndex: ['sysTopCataName'],  是正常的   但是如果数组中在加上一个变为['sysTopCataName','sysSubCataId'] 此时就连
 dataIndex: ['sysTopCataName'],  也不会显示了

**Comment by huangtaoSyn** [comment]
大佬们帮帮忙啊

**Comment by chenshuai2144** [comment]
['sysTopCataName','sysSubCataId']  是 sysTopCataName.sysSubCataId 的意思，

认真看看文档吧
