### ISSUE TITLE
我在使用yarn create umi myapp创建项目是swagger-ui-react报Can't resolve 'btoa' 的错误

### ISSUE THREAD

**Issue by kwhyyi** [ant-design/ant-design-pro#9839]
### 🧐 问题描述

Module not found: Error: Can't resolve 'btoa' in 'D:\myapp\node_modules\swagger-ui-react'

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/48544320/168410647-e90ed20f-99a8-4525-baa4-eee2e1951050.png)

**Comment by chenfeiwu** [comment]
我也是。。。

**Comment by smileLixiaoning** [comment]
npm或yarn安装一下btoa依赖

**Comment by whisper540** [comment]
能尽快修复这个问题么，版本都起不来，这个bug也太严重了！！！！！

**Comment by linuxgcc** [comment]
我也遇到相同问题了。

**Comment by simba-ch** [comment]
me too

**Comment by TinsFox** [comment]
`gcl git@github.com:ant-design/ant-design-pro.git` 直接拉取仓库代码创建项目吧

**Comment by keoku** [comment]
> yarn add btoa -D

我试了一下这个命令后就可以了

**Comment by zhouxiaofu** [comment]
+1

**Comment by zyddf1206** [comment]
+1

**Comment by yaohwu** [comment]
The [pr](https://github.com/ant-design/ant-design-pro/pull/9826) has fixed the bug.
Before releasing the latest version, you can change the package.json just like the pr did.

**Comment by Moo920** [comment]
'npm install swagger-ui-react' solved my problem

**Comment by 2045425118** [comment]
> 纱线加铅-D

你好，能说一下为什么会出现这个问题，和为什么加了这个就没有问题了
