### ISSUE TITLE
🧐[问题]关于data.d.ts的疑问

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design-pro#9842]
### 🧐 问题描述
data.d.ts不是用来做js的类型声明的吗？ant-design-pro中我看到好多的data.d.ts。里面没有declare的语法，只是单纯的导出了一些类型。

是不是可以写成data.ts也可以，没必要data.d.ts。

### 💻 示例代码
比如dashboard/monitor中
```
export type TagType = {
  name: string;
  value: number;
  type: string;
};

```

**Comment by Dunqing** [comment]
> 是不是可以写成data.ts也可以，没必要data.d.ts。

可以的

我个人是不太喜欢把类型都写在data.d.ts中，这会导致类似类型太多难以管理

**Comment by qingfengmy** [comment]
> > 是不是可以写成data.ts也可以，没必要data.d.ts。
> 
> 可以的
> 
> 我个人是不太喜欢把类型都写在data.d.ts中，这会导致类似类型太多难以管理

或者就是集中写到一个文件，或者就是分开定义多个文件，各有利弊吧
