### ISSUE TITLE
👑 [需求]V5 菜单如何做到展开点击菜单，其他展开菜单收缩

### ISSUE THREAD

**Issue by dawnsongpeng** [ant-design/ant-design-pro#9845]
### 🥰 需求描述
如何做到点击菜单，收起其他展开的所有菜单在ant design pro里，原生的ant design可以通过states实现，但是在pro里面没有做到

**Comment by dawnsongpeng** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
默认现在就是这样的吧。

你可以通过 menuProps 这个 props 来修改 menu 的数据
