### ISSUE TITLE
🐛[问题]如何做到点击菜单，收起其他展开的所有菜单在ant design pro里，原生的ant design可以通过states实现，但是在pro里面没有做到

### ISSUE THREAD

**Issue by dawnsongpeng** [ant-design/ant-design-pro#9847]
### 🐛 问题描述
如何做到点击菜单，收起其他展开的所有菜单在ant design pro里，原生的ant design可以通过states实现，但是在pro里面没有做到

### © 版本信息

- Ant Design Pro 版本: [5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
默认就是这样的。
https://procomponents.ant.design/components/layout
你试试
