### ISSUE TITLE
🐛[BUG]login界面账户及密码输入框格式异常

### ISSUE THREAD

**Issue by essapp** [ant-design/ant-design-pro#9849]
### 🐛 bug 描述

EDGE中目前master中存在login界面账户、密码及手机号等input元件格式异常，主要表现为长短不一，没有充满父组件。

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本
- 浏览器环境[edge]
- 开发环境 [mac OS]

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/92622299/169225927-06fa3218-f707-407a-b093-53740c6644b4.png)

**Comment by MachoManCk** [comment]
如何解决的

**Comment by MachoManCk** [comment]
@essapp 为什么关闭了？

**Comment by chenshuai2144** [comment]
看起来是mfsu导致样式没有加载导致的

**Comment by MachoManCk** [comment]
听说umi4修复了这个问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🐛[BUG]login界面账户及密码输入框格式异常 (Issue #9849)





 
看起来是mfsu导致样式没有加载导致的

**Comment by chenshuai2144** [comment]
umi@4 是完美的mfsu，默认就打开了

**Comment by MachoManCk** [comment]
好的，抽时间会迁移一下。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🐛[BUG]login界面账户及密码输入框格式异常 (Issue #9849)





 
***@***.*** 是完美的mfsu，默认就打开了
