### ISSUE TITLE
登陆成功之后 如何跳转首页 需要进行那些配置？

### ISSUE THREAD

**Issue by cdscawd** [ant-design/ant-design-pro#985]

**Comment by hudianlao48** [comment]
/src/layouts/BasicLayout.js
112行。

**Comment by cdscawd** [comment]
@hudianlao48 我这里登陆跳转之后 各种报错

**Comment by pkaq** [comment]
各种报错 然额一个也没贴？

**Comment by 769062159** [comment]
登录成功后根据登录成功状态进入modal中的login.js修改此处为想要跳转的地址![image](https://user-images.githubusercontent.com/28591241/62818031-716b4780-bb73-11e9-82e7-bdbc082810b2.png)
同时在登录成功后台获取的字段必须加currentAuthority:'admin'如下
![image](https://user-images.githubusercontent.com/28591241/62818048-c018e180-bb73-11e9-8825-081664f8f167.png)
之后就可以登录成功后跳转到想要的页面
