### ISSUE TITLE
🧐[问题]  ProTable editable  新增编辑行在尾部时如何与分页器搭配使用，能否出个示例

### ISSUE THREAD

**Issue by MINGLIANG98** [ant-design/ant-design-pro#9851]
### 🧐 问题描述

editable 开启pagination分页  新增编辑行 position选择 bottom 的时候会自动跳到数据页尾 。 能不能手动控制current页？手动设置current到最后一页的话，如果最后一页满数据需要新增空页如何实现呢？

### 💻 示例代码

                pagination={{
                    showQuickJumper: true,
                    defaultPageSize: 10,
                    current: current,
                }}
                options={false}
                search={false}
                controlled={false}
                editable={{
                    type: 'single',
                    editableKeys,
                    onSave: async (
                        rowKey,
                        row,
                        originRow,
                    ) => {
                     //逻辑代码
                    },
                    onCancel: async () => {
                        ref.current?.reload();
                    },
                    onChange: setEditableRowKeys,
                    actionRender: (row, config, defaultDom) => [defaultDom.save, defaultDom.cancel],
                }}
                recordCreatorProps={{
                    // 末尾添加
                    position: 'bottom',
                    newRecordType: 'dataSource',
                    onClick: () => {
                     // setcurrent(尾页);
                    },
                    // 不写 key ，会使用 index 当行 id
                    record: () => {
                        return {
                            id: Date.now(),
                        };
                    },
                }}

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/67278171/169445557-51ab99d2-183b-4c74-aae5-dc4bb2b910db.png)
###   版本信息
  "name": "ant-design-pro",
  "version": "4.5.0",

**Comment by chenshuai2144** [comment]
通过 pagination 来控制吧，组件有点不好搞这个
