### ISSUE TITLE
🐛[BUG] QueryFilter 的 ProForm.Item 不支持 colSize 参数

### ISSUE THREAD

**Issue by yangbinsoft** [ant-design/ant-design-pro#9854]
### 🐛 bug 描述
QueryFilter 的 ProForm.Item 不支持 colSize 参数，但是又有效果，会提示错误：
`devScripts.js:6523 Warning: React does not recognize the `colSize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `colsize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`
![image](https://user-images.githubusercontent.com/15042338/169516411-024a9f81-d697-4969-8a72-36b66bddc4dc.png)

![image](https://user-images.githubusercontent.com/15042338/169516299-0d37cf86-49b5-4690-8834-f5e291ac1e97.png)

### 💻 复现代码

```
 <QueryFilter       
        formRef={formRef}
        onFinish={async () => refresh()}
        onValuesChange={(changeValues) => {
          if (changeValues.lastSql) return;
          refresh();
        }}
      >
 <ProFormSelect
          name="selectAccrued"
          label="是否计提"
          valueEnum={{
            false: '否',
            true: '是',
          }}
        />
  <ProForm.Item label="lastSql" name="lastSql" colSize={2}>
          <AutoComplete allowClear options={options} onSearch={onSearch}/>
  </ProForm.Item>
</QueryFilter>
```

### © 版本信息

- Ant Design Pro 版本: 5

希望在 ProForm.Item 中增加 colSize 参数

**Comment by chenshuai2144** [comment]
先忽略一下，procomponents 那边修
