### ISSUE TITLE
🧐[问题] Ant Design Pro 开启 Umi UI没有模板

### ISSUE THREAD

**Issue by zyddf1206** [ant-design/ant-design-pro#9856]
![4](https://user-images.githubusercontent.com/103043384/169687855-c0336a94-50d1-429e-9e89-2dec374dac41.png)
![5](https://user-images.githubusercontent.com/103043384/169687859-a6647f21-5e64-440b-b0a4-37fd93ccb66a.png)

**Comment by chenshuai2144** [comment]
废弃了，不要挣扎了
