### ISSUE TITLE
🧐[问题]根据官网操作初始化的项目，开启了资产，但是资产没有数据

### ISSUE THREAD

**Issue by 18854160806** [ant-design/ant-design-pro#9857]
### 🧐 问题描述
按照官网进行初始化项目，然后想安装资产用一下，不知道为什么一直打开无数据，node用14版本和16版本都试了，都是这个效果，并且页面一点击右下角小气泡就有报错,并且初始化项目的时候会出现找不到btoa的依赖，需要npm安装下

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/35982631/169700873-f617ccd4-374c-4205-b14e-79d129e8e8d0.png)

**Comment by StevenChu1125** [comment]
+1

**Comment by dasewan** [comment]
+1

**Comment by hyzx86** [comment]
资产停止维护了
