### ISSUE TITLE
🧐[问题]孩子需要javascript不想要typescript，从哪里获取啊，球球了 

### ISSUE THREAD

**Issue by meizizi66** [ant-design/ant-design-pro#9859]
### 🧐 问题描述
孩子需要javascript不想要typescript，从哪里获取啊，球球了

**Comment by TinsFox** [comment]
`npx create-umi`创建项目的时候可选语言，但是不知道相关的错误修复了没有

**Comment by chenshuai2144** [comment]
不要挣扎了， 现在还不写 ts 怎么找好工作

**Comment by Yu2xd** [comment]
你好，请问，你解决了嘛，我也有同样的需求
