### ISSUE TITLE
👑 [需求] 建议在docker/nginx.conf location / 中添加absolute_redirect off;

### ISSUE THREAD

**Issue by undo-nothing** [ant-design/ant-design-pro#9861]
### 🥰 需求描述

当我用Dockerfile.hub编译镜像，并部署时，将并未将服务器配置在默认的80/443端口，并且访问的url中没有添加“/”结尾，刷新时nginx返回301，自动加上了location自动加上“/”, 但是端口未正确添加到location，导致无法访问。

### 🧐 解决方案

在docker/nginx.conf location / 中添加absolute_redirect off;
nginx返回301，自动加上了location自动加上“/”, 并且没有返回hostname:port的绝对路径，刷新访问正常。

**Comment by chenshuai2144** [comment]
pr 合并了
