### ISSUE TITLE
Use antd Pro as a standalone library. 使用 antd Pro 作为独立库。

### ISSUE THREAD

**Issue by russelRajitha** [ant-design/ant-design-pro#9864]
I have well established and stable project built with react and redux. so I hope to integrate antd pro and make it a little bit beautiful. but I may not be able to convert the entire project with antd pro structure and use umi structure, so I tried to install packages such as @antd/pro-layout and I couldn't get it to work. can someone help me with this? 

我已经使用 react 和 redux 构建了完善且稳定的项目。 所以希望能集成antd pro，让它变得漂亮一点。 但是我可能无法将整个项目转换为antd pro结构并使用umi结构，所以我尝试安装@antd/pro-layout之类的包，但无法正常工作。 有人可以帮我弄这个吗？

**Comment by chenshuai2144** [comment]
https://procomponents.ant.design/en-US

What you need is it？
