### ISSUE TITLE
🧐[问题]工作是内网无法使用npx create-umi myapp，该如何下载代码

### ISSUE THREAD

**Issue by RenJie-Z** [ant-design/ant-design-pro#9867]
### 🧐 问题描述

我想直接去gitee网站下载代码，但是不知道怎么下载simple基础模板。

**Comment by qiudaoermu** [comment]
npm可用的话,可以直接安装Cli

**Comment by RenJie-Z** [comment]
> npm可用的话,可以直接安装Cli

如何安装？需要基础模板

**Comment by qiudaoermu** [comment]
用自己手机热点装啊

**Comment by RenJie-Z** [comment]
> 用自己手机热点装啊

我说的内网是部分网站受限，npx下载显示超时，但是直接去GitHub下载代码文件是可以下的

**Comment by chenshuai2144** [comment]
国内是从git ee 拉代码的，可能是 gitee 的问题
