### ISSUE TITLE
🐛[BUG]react-dev-inspector 引用兼容问题

### ISSUE THREAD

**Issue by Ricky816845** [ant-design/ant-design-pro#9870]
### 🐛 bug 描述
package 
"react-dev-inspector": "^1.7.0"
由于实际安装的是1.8.0版本,其下引用react-dev-util 编译环境需要node 14.0以上
不满足 node >=12.0的要求
### 📷 复现步骤
node version 13.14.0
yarn install

**Comment by chenshuai2144** [comment]
这个作者不维护了，去掉吧
