### ISSUE TITLE
jekins构建时报错🐛[BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9872]
### 🐛 bug 描述

突然构建时报错 少了啥配置吗
![image](https://user-images.githubusercontent.com/20655248/170403566-6eac67f0-2628-4edf-bfd8-f22c6a19ad18.png)
![image](https://user-images.githubusercontent.com/20655248/170403599-847c6ae4-4029-4d24-a0a8-7dc628664a30.png)
![image](https://user-images.githubusercontent.com/20655248/170404040-b2a2fd80-59ac-4562-98d3-bc6b0b44239a.png)

**Comment by chenshuai2144** [comment]
babel 的版本问题，升级一下各类版本。
这个问题是上个月babel做了改动导致的，大家已经适配了
