### ISSUE TITLE
🐛[BUG]拉下来的项目，输入框显示异常

### ISSUE THREAD

**Issue by MachoManCk** [ant-design/ant-design-pro#9873]
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本
- 浏览器环境 
- 开发环境 [mac OS]

### 🚑 其他信息

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/34299788/170446959-4d3e07c9-5563-42cd-83c7-68334b62dde8.png">

**Comment by YongPengDing** [comment]
yarn add swagger-ui-react

**Comment by chenshuai2144** [comment]
重新安装一下，看起来是样式加载失败了
