### ISSUE TITLE
🐛[BUG]浏览器tab切换时，页面会重新请求接口

### ISSUE THREAD

**Issue by lzecheng** [ant-design/ant-design-pro#9875]
### 🐛 bug 描述
浏览器tab切换时，页面会重新请求接口

### 📷 复现步骤
浏览器打开多个tab，从其它tab切换回来，页面就会重新请求接口

### 🏞 期望结果
浏览器tab切换时，页面不会重新请求接口

### © 版本信息
5.2.0
- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by ShibaInuOfMars** [comment]
是ProTable会重新请求，添加revalidateOnFocus={false}

**Comment by chenshuai2144** [comment]
更新到最新版本，默认关掉了
