### ISSUE TITLE
🧐[问题]无法同时启动两个ant-design-pro项目

### ISSUE THREAD

**Issue by SilentRio** [ant-design/ant-design-pro#9879]
### 🧐 问题描述
第一个项目正常启动后，当启动第二个项目时就会报错如图所示：
<img width="828" alt="image" src="https://user-images.githubusercontent.com/19779285/170615160-1284c7fc-3a3e-4c92-888b-8e3097167095.png">

**Comment by chenshuai2144** [comment]
看起来是文件冲突了，你的node 和操作系统版本给下

**Comment by hyzx86** [comment]
看样子是再一个目录下同一份代码 用不同命令启动两次。。
估计是热更新的问题，文件被前一个命令锁定了
