### ISSUE TITLE
右侧内容页(列表页，新增页，编辑页，删除页，详情页)一个完整的路由交互示范

### ISSUE THREAD

**Issue by Sayi** [ant-design/ant-design-pro#988]
#### 最常见的一个需求：
```
点击左侧菜单（客户管理-所有客户），右侧出现客户列表页面（比如url为/#/customer/query），
可以在这个页面点击
新增（比如url为/#/customer/create，对应一个页面）、
编辑（比如url为/#/customer/edit/:customerId，对应一个页面）、
删除（可能是个弹框确认，不需要一个url），
点击table的一行可以查看客户详情(比如url为/#/customer/:customerId，对应一个页面)
```

#### 现有问题：
**不知道如何配置路由以支持如上的交互跳转**。
1. 如何参数带上业务模型(此处是客户)的ID，支持restful风格的路由，从而跳转到详情页？
2. 只有一个二级菜单，在这个二级菜单选中的前提下，右侧页面支持新增页面、编辑页面、不同客户的详情页页面切换？

#### 建议：
* 在官方demo中基本一个菜单都是一些组件的集合，缺乏在这个菜单下，右侧内容页(列表页，新增页，编辑页，删除页，详情页)一个完整的路由交互示范。

期待回复，谢谢。

**Comment by ddcat1115** [comment]
看上去有两个问题？

1. 缺乏『查看』『新增』『编辑』『删除』的交互演示
2. 支持上述页面互相跳转的路由配置

对于第一点，正在开发的二期页面中包含了此流程，但设计上给出的方案是这几个功能都在一个页面里利用弹窗完成，不涉及页面的跳转，初步效果可以查看 v2 分支的『查询表格』页面（点击 `配置` 或 `新建`）。

如果希望用页面跳转串联整个流程，目前的路由/菜单功能也可以完成，[路由和菜单](https://pro.ant.design/docs/router-and-nav-cn)文档里有介绍，你可能需要着重关注 [带参数的路由/菜单](https://pro.ant.design/docs/router-and-nav-cn#%E5%B8%A6%E5%8F%82%E6%95%B0%E7%9A%84%E8%B7%AF%E7%94%B1/%E8%8F%9C%E5%8D%95) 以及 [嵌套路由同级展示](https://pro.ant.design/docs/router-and-nav-cn#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA)

**Comment by Sayi** [comment]
有的业务字段很多，弹窗可能只能满足一部分业务。

感谢，我明天尝试用页面跳转把流程串联起来。

**Comment by Sayi** [comment]
已经成功串联，谢谢。

**Comment by WuJiY** [comment]
@Sayi 我也遇到这个问题，你是怎么解决的，是否有案列看一下

**Comment by Sayi** [comment]
@WuJiY 你看下[嵌套路由同级展示](https://pro.ant.design/docs/router-and-nav-cn#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1%E5%90%8C%E7%BA%A7%E5%B1%95%E7%A4%BA)，然后就可以配置增删查改的路径了。
