### ISSUE TITLE
🐛[BUG] 安装完依赖 运行错错 Can't resolve 'btoa'

### ISSUE THREAD

**Issue by YongPengDing** [ant-design/ant-design-pro#9880]
### 🐛 bug 描述

Module not found: Error: Can't resolve 'btoa' in '/home/ubuntu/myapp/node_modules/swagger-ui-react'

### 📷 复现步骤

yarn create umi myapp
 ant-design-pro
 TypeScript
 simple
cd myapp
yarn
yarn start

### 🏞 期望结果

可以按照官网说明正常运行

### © 版本信息

- Ant Design Pro 版本: [e.g. 5.2.0]
- umi 版本 ^3.5.0
- 浏览器环境 火狐 100.0.2 (64 位)
- 开发环境 [e.g. Ubuntu]

### 🚑 其他信息

![图片](https://user-images.githubusercontent.com/49970333/170615665-1bee8d7b-cbae-4380-8fb2-47f408d80c71.png)

**Comment by Valar103769** [comment]
+1

**Comment by btlfe** [comment]
run
npm install btoa
