### ISSUE TITLE
🧐[最佳实践] 我的 登录鉴权 errHandler 异常处理 请求封装模板,大家可参考

### ISSUE THREAD

**Issue by Valar103769** [ant-design/ant-design-pro#9885]
app.tsx
```ts
import Footer from '@/components/Footer'
import RightContent from '@/components/RightContent'
import type { Settings as LayoutSettings } from '@ant-design/pro-layout'
import { PageLoading } from '@ant-design/pro-layout'
import { message } from 'antd'
import ClipboardJS from 'clipboard'
import type { RequestConfig, RunTimeLayoutConfig } from 'umi'
import { history, request as umiRequest } from 'umi'
import type { RequestOptionsInit, ResponseError, ResponseInterceptor } from 'umi-request'
import defaultSettings from '../config/defaultSettings'
import { apiUserInfo, fetchChannelList } from './api/ant-design-pro/api'
import { channelListToMap, clearLocalStorage, messageOnce } from './utils'

// Sentry.init({
//   dsn: 'https://45fb3e51287b42738cff3b62e585f60a@o1171004.ingest.sentry.io/6453859',
//   integrations: [new BrowserTracing()],
//   environment: process.env.NODE_ENV,
//   // Set tracesSampleRate to 1.0 to capture 100%
//   // of transactions for performance monitoring.
//   // We recommend adjusting this value in production
//   tracesSampleRate: 1.0,
// })

type InitialState = {
  settings: Partial<LayoutSettings>
  currentUser?: API.CurrentUser | undefined
  fetchUserInfo?: () => Promise<API.CurrentUser | undefined>
  channelMap?: Map<string, string>
  channelList?: any[]
  gameId?: string | null
  gameList?: any[]
}

const loginPath = '/user/login'

new ClipboardJS('.copy-btn')

/**
 * https://github.com/blueju/umi-request-practice/blob/main/src/lib/error-handler.ts
 */
const codeMaps = {
  // 200: '成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  405: '请求方法不支持,请联系开发人员',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
}

/** 获取用户信息比较慢的时候会展示一个 loading */
export const initialStateConfig = {
  loading: <PageLoading />,
}

/**
 * @see  https://umijs.org/zh-CN/plugins/plugin-initial-state
 * */

export async function getInitialState(): Promise<InitialState> {
  const isLogin = localStorage.getItem('x-token')
  let res: InitialState = {
    settings: defaultSettings,
  }

  if (isLogin) {
    // 初始化和 login 都会执行
    const pCurrentUser = apiUserInfo()
    const pChannelList = fetchChannelList()

    const currentUser = await pCurrentUser
    const channelList = await pChannelList
    let { data: gameList } = await umiRequest('/sys/basic/game_list')

    gameList = gameList.map((item: any) => ({ ...item, label: item.name, value: item.game_id }))

    const gameId =
      localStorage.getItem('gameId') ||
      gameList?.find?.((item: any) => item.is_stop === '0')?.game_id
    res = {
      // 页面接口需要game-id,
      gameId,
      currentUser,
      gameList: gameList || [],
      settings: defaultSettings,
      channelList: channelList,
      channelMap: channelListToMap(channelList),
    }
    console.assert(gameId && gameId !== 'undefined', 'gameID:' + gameId)

    localStorage.setItem('gameId', gameId)
    // Sentry.setUser({ username: currentUser?.name })
    window.localStorage.wmUserInfo = JSON.stringify({
      userId: currentUser?.name,
      userTag: 'tag',
      projectVersion: __PROJECT_VERSION__,
      env: process.env.NODE_ENV === 'production' ? 'pro' : 'dev',
    })
  }

  console.log('获取初始化数据', res, location.pathname)
  return res
}

// ProLayout 支持的api https://procomponents.ant.design/components/layout
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    waterMarkProps: {
      content: initialState?.currentUser?.name,
    },
    footerRender: () => <Footer />,
    // 初始化时也会执行一次
    onPageChange: async (location: {
      state: { fromType: 'loginSubmit' } | undefined
      query: Record<string, any>
      pathname: string
    }) => {
      const isLogin = localStorage.getItem('x-token')
      const redirect = location.pathname.includes('user/login') ? '' : location.pathname
      if (!isLogin) {
        history.push({
          pathname: loginPath,
          query: {
            ...location.query,
            ...(redirect && { redirect }),
          },
        })
      }
    },
    links: [],
    menuHeaderRender: undefined,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings,
  }
}

const authHeaderInterceptor: any = (url: string, options: RequestOptionsInit) => {
  // setInitial 是异步的, localStorage 中取
  const authHeader = {
    'x-token': localStorage.getItem('x-token'),
    'game-id': localStorage.getItem('gameId'),
    'Content-Type': 'application/json',
  }

  // if (process.env.NODE_ENV === 'production') {
  //   url = location.protocol + '/api.aaa.com' + url
  // }

  return {
    url: `${url}`,
    options: { ...options, interceptors: true, headers: authHeader },
  }
}

// handling error in response interceptor
const responseInterceptor: ResponseInterceptor = (response) => {
  if (response.status !== 200) {
    message.error(`[${response.status}] ${codeMaps[response.status] || response.url}`)
  }

  return response
}

export const request: RequestConfig = {
  // http状态码非200 || res.success 不为true 时触发,必须返回值
  errorHandler: (err: ResponseError) => {
    // sentry的接入demo
    //  https://github.com/umijs/umi/tree/cb304ae03b36d689d85336a7f516fe4e41cff900/examples/with-sentry
    // Sentry.captureException(error);
    // https://github.com/umijs/umi-request

    // 可以打印 404 500状态码,意味着可以捕获codeMaps, 但某些时候取不到值,感觉有风险
    // console.log('error.response.status', err.response.status)
    console.log(err)
    console.log('errorHandler', JSON.parse(JSON.stringify(err)))

    if (err.name === 'BizError') {
      // 业务错误时, 假如 return Promise.reject() 将会导致页面一直loading,
      // 所以总是返回成功的promise
      // 进而 页面中无法使用tryCatch判断是否success === 0
      const response = err.data
      if (response.code === 0) {
        return err.data
      } else if (response.code >= 701 && response.code <= 720) {
        messageOnce(response.msg)
        clearLocalStorage()
        if (!history.location?.pathname.includes('user/login')) {
          history.push({
            pathname: loginPath,
            query: {
              ...history.location.query,
              redirect: location?.pathname,
            },
          })
        }

        // 当token失效时,data并非为空对象,需要在这里清空

        // 不能使用null, 因为深度结构默认值={}不会生效,

        response.data = undefined
      } else {
        if (response.msg) {
          message.error(response.msg)
        }
        return Promise.reject(response)
      }
    }

    // 对于其他的错误, 需要实践中一个个找出来,源码可能有,懒得看
    if (err.name === 'RequestError') {
      console.group('RequestError', JSON.parse(JSON.stringify(err)))
      switch (err.type) {
        case 'Timeout': {
          message.error('系统超时,请联系开发人员')
        }
      }
    }
    if (err.name === 'ResponseError') {
      switch (err.type) {
        case '"HttpError"': {
          message.error('HttpError 请重试')
        }
      }
    }

    return err.data
  },

  // 必须配置
  errorConfig: {
    adaptor: (resData: any) => {
      return {
        ...resData,
        data: resData.data,
        success: resData.code === 0,
        errorMessage: resData.msg,
        showType: 2,
      }
    },
  },
  timeout: 5 * 60 * 1000,
  requestInterceptors: [authHeaderInterceptor],
  responseInterceptors: [responseInterceptor],
}
```

utils.ts

```ts
const warned: Record<string, boolean> = {}
export const messageOnce = (msg: string) => {
  if (!warned[msg]) {
    message.error(msg)
    warned[msg] = true
  }
}

export const clearLocalStorage = () => {
  const gameId = localStorage.getItem('gameId')
  const avatar = localStorage.getItem('avatar')
  localStorage.clear()
  if (gameId) {
    localStorage.setItem('gameId', gameId)
  }
  if (avatar) {
    localStorage.setItem('avatar', avatar)
  }
}
export const channelListToMap = (list: any[]) => {
  const map = new Map()
  if (isEmpty(list)) return map
  // id:name
  list.forEach((item: any) => {
    map.set(item.value, item.label)
  })
  return map
}
```

**Comment by xiahller** [comment]
> import Footer from '@/components/Footer' import RightContent from '@/components/RightContent' import type { Settings as LayoutSettings } from '@ant-design/pro-layout' import { PageLoading } from '@ant-design/pro-layout' import { message } from 'antd' import ClipboardJS from 'clipboard' import type { RequestConfig, RunTimeLayoutConfig } from 'umi' import { history, request as umiRequest } from 'umi' import type { RequestOptionsInit, ResponseError, ResponseInterceptor } from 'umi-request' import defaultSettings from '../config/defaultSettings' import { apiUserInfo, fetchChannelList } from './api/ant-design-pro/api' import { channelListToMap, clearLocalStorage, messageOnce } from './utils'
> 
> type InitialState = { settings: Partial currentUser?: API.CurrentUser | undefined fetchUserInfo?: () => Promise<API.CurrentUser | undefined> channelMap?: Map<string, string> channelList?: any[] gameId?: string | null gameList?: any[] }
> 
> const loginPath = '/user/login'
> 
> new ClipboardJS('.copy-btn')
> 
> /**
> 
> * https://github.com/blueju/umi-request-practice/blob/main/src/lib/error-handler.ts
>   */
>   const codeMaps = {
>   // 200: '成功返回请求的数据。',
>   201: '新建或修改数据成功。',
>   202: '一个请求已经进入后台排队（异步任务）。',
>   204: '删除数据成功。',
>   400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
>   401: '用户没有权限（令牌、用户名、密码错误）。',
>   403: '用户得到授权，但是访问是被禁止的。',
>   404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
>   405: '请求方法不支持,请联系开发人员',
>   406: '请求的格式不可得。',
>   410: '请求的资源被永久删除，且不会再得到的。',
>   422: '当创建一个对象时，发生一个验证错误。',
>   500: '服务器发生错误，请检查服务器。',
>   502: '网关错误。',
>   503: '服务不可用，服务器暂时过载或维护。',
>   504: '网关超时。',
>   }
> 
> /** 获取用户信息比较慢的时候会展示一个 loading */ export const initialStateConfig = { loading: , }
> 
> export async function getInitialState(): Promise { const isLogin = localStorage.getItem('x-token') let res: InitialState = { settings: defaultSettings, }
> 
> if (isLogin) { // 初始化和 login 都会执行 const pCurrentUser = apiUserInfo() const pChannelList = fetchChannelList()
> 
> ```
> const currentUser = await pCurrentUser
> const channelList = await pChannelList
> const { data: gameList } = await umiRequest('/sys/basic/game_list')
> 
> const gameId =
>   localStorage.getItem('gameId') ||
>   gameList?.find?.((item: any) => item.is_stop === '0')?.game_id
> res = {
>   // 页面接口需要game-id,
>   gameId,
>   currentUser,
>   gameList: gameList,
>   settings: defaultSettings,
>   channelList: channelList,
>   channelMap: channelListToMap(channelList),
> }
> console.assert(gameId && gameId !== 'undefined', 'gameID:' + gameId)
> 
> localStorage.setItem('gameId', gameId)
> ```
> 
> }
> 
> console.log('获取初始化数据', res, location.pathname) return res }
> 
> // ProLayout 支持的api https://procomponents.ant.design/components/layout export const layout: RunTimeLayoutConfig = ({ initialState }) => { return { rightContentRender: () => , disableContentMargin: false, waterMarkProps: { content: initialState?.currentUser?.name, }, footerRender: () =>
> 
> ,
> // 初始化时也会执行一次
> onPageChange: async (location: {
> state: { fromType: 'loginSubmit' } | undefined
> query: Record<string, any>
> pathname: string
> }) => {
> const isLogin = localStorage.getItem('x-token')
> const redirect = location.pathname.includes('user/login') ? '' : location.pathname
> if (!isLogin) {
> history.push({
> pathname: loginPath,
> query: {
> ...location.query,
> ...(redirect && { redirect }),
> },
> })
> }
> },
> links: [],
> menuHeaderRender: undefined,
> // 自定义 403 页面
> // unAccessible:
> unAccessible
> ,
> ...initialState?.settings,
> }
> }
> const authHeaderInterceptor: any = (url: string, options: RequestOptionsInit) => { // setInitial 是异步的, localStorage 中取 const authHeader = { 'x-token': localStorage.getItem('x-token'), 'game-id': localStorage.getItem('gameId'), 'Content-Type': 'application/json', }
> 
> return { url: `${url}`, options: { ...options, interceptors: true, headers: authHeader }, } }
> 
> // handling error in response interceptor const responseInterceptor: ResponseInterceptor = (response) => { if (response.status !== 200) { message.error(`[${response.status}] ${codeMaps[response.status] || response.url}`) }
> 
> return response }
> 
> export const request: RequestConfig = { // http状态码非200 || res.success 不为true 时触发,必须返回值 errorHandler: (err: ResponseError) => {
> 
> ```
> console.log(err)
> console.log('errorHandler', JSON.parse(JSON.stringify(err)))
> 
> if (err.name === 'BizError') {
>   // 业务错误时, 假如 return Promise.reject() 将会导致页面一直loading,
>   // 所以总是返回成功的promise
>   // 进而 页面中无法使用tryCatch判断是否success === 0
>   const response = err.data
>   if (response.code === 0) {
>     return err.data
>   } else if (response.code >= 701 && response.code <= 720) {
>     messageOnce(response.msg)
>     clearLocalStorage()
>     if (!history.location?.pathname.includes('user/login')) {
>       history.push({
>         pathname: loginPath,
>         query: {
>           ...history.location.query,
>           redirect: location?.pathname,
>         },
>       })
>     }
> 
>     // 当token失效时,data并非为空对象,需要在这里清空
> 
>     // 不能使用null, 因为深度结构默认值={}不会生效,
> 
>     response.data = undefined
>   } else {
>     if (response.msg) {
>       message.error(response.msg)
>     }
>     return Promise.reject(response)
>   }
> }
> 
> // 对于其他的错误, 需要实践中一个个找出来,源码可能有,懒得看
> if (err.name === 'RequestError') {
>   console.group('RequestError', JSON.parse(JSON.stringify(err)))
>   switch (err.type) {
>     case 'Timeout': {
>       message.error('系统超时,请联系开发人员')
>     }
>   }
> }
> if (err.name === 'ResponseError') {
>   switch (err.type) {
>     case '"HttpError"': {
>       message.error('HttpError 请重试')
>     }
>   }
> }
> 
> return err.data
> ```
> 
> },
> 
> // 必须配置 errorConfig: { adaptor: (resData: any) => { return { ...resData, data: resData.data, success: resData.code === 0, errorMessage: resData.msg, showType: 2, } }, }, timeout: 5 * 60 * 1000, requestInterceptors: [authHeaderInterceptor], responseInterceptors: [responseInterceptor], }

请问messageOnce是啥

**Comment by Valar103769** [comment]
> ```ts
> Promise.reject(response)
> ```

```
const warned: Record<string, boolean> = {}
export const messageOnce = (msg: string) => {
  if (!warned[msg]) {
    message.error(msg)
    warned[msg] = true
  }
}
```
因为页面中会有很多接口, 每个接口都弹个message就很烦, 所以控制一下
