### ISSUE TITLE
🧐[问题] v5版本使用model 出错

### ISSUE THREAD

**Issue by sendy-dev** [ant-design/ant-design-pro#9886]
### 🧐 问题描述

在v5版本使用model，按照文档使用会报错，正常的使用方法不是这样的吗？

### 💻 示例代码
**counts.ts**
![image](https://user-images.githubusercontent.com/56161847/170823861-7e2141fd-d98b-427b-a018-97fbc092d175.png)

**index.tsx**
![1653737323(1)](https://user-images.githubusercontent.com/56161847/170823841-ef0a0530-a286-4ad4-83b3-c74f1035e36a.jpg)

**Comment by YongPengDing** [comment]
src/models

**Comment by yang-ren-ting** [comment]
同样问题，解决了吗

**Comment by ZeXinWork** [comment]
解决了吗
