### ISSUE TITLE
关于build后的疑问

### ISSUE THREAD

**Issue by wdao7** [ant-design/ant-design-pro#989]
路由中不是使用了按需加载吗，为什么打包出来的js是一个js文件，大小快2M了呀？不改一个个小模块的js吗

**Comment by chenshuai2144** [comment]
https://pro.ant.design/docs/deploy-cn#%E4%BB%A3%E7%A0%81%E5%88%86%E5%89%B2%E5%92%8C%E5%8A%A8%E6%80%81%E5%8A%A0%E8%BD%BD
