### ISSUE TITLE
🐛[BUG] ProTable操作列用<a>标签控制台报错：Uncaught TypeError: Cannot read properties of null (reading 'match')

### ISSUE THREAD

**Issue by dongyuwhz** [ant-design/ant-design-pro#9892]
### 🐛 bug 描述

![image](https://user-images.githubusercontent.com/24761932/171323355-5e95bb9f-b011-4b78-bf8e-8957dac28391.png)
### 📷 复现步骤
{
      title: '操作',
      dataIndex: 'x',
      valueType: 'option',
      render: (_, record) => {
        let node = renderRemoveUser('退出');
        if (record.role === 'admin') {
          node = renderRemoveUser('移除');
        }
        return [<a key="edit">编辑</a>, node];
      },
    },
点击编辑控制台报错：Uncaught TypeError: Cannot read properties of null (reading 'match')

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 🚑 其他信息
换乘其他标签就没有报错，比如：button、span等

**Comment by chenshuai2144** [comment]
他分析了你的 href，不写href 最好不要用 a 标签

**Comment by dongyuwhz** [comment]
主要是官网上例子都是用的a然后就用它的例子里的，加上href确实不报错了
