### ISSUE TITLE
🐛[BUG]窗口从小拖到大 menu显示在内容区域 

### ISSUE THREAD

**Issue by hzylab** [ant-design/ant-design-pro#9893]
### 💻 复现代码
![image](https://user-images.githubusercontent.com/63150289/171404205-0c9423c6-6c5d-4782-a7d2-a74ae2d7d915.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
升级一下antd版本能解决一部分。

这个是个焦点的问题，可以点一下别的地方会消失掉
