### ISSUE TITLE
🐛[BUG] Cannot find module 'btoa'

### ISSUE THREAD

**Issue by weypro** [ant-design/ant-design-pro#9894]
### 🐛 bug 描述
创建新项目，在启动时出现
```
error  in ./node_modules/swagger-ui-react/swagger-ui.js
Module not found: Error: Can't resolve 'btoa' in 'D:\netproject\umimyapp\node_modules\swagger-ui-react'
```
点击首页菜单中的openapi一项，出现 `Unhandled Rejection (Error): Cannot find module 'btoa'`
### 📷 复现步骤

按照官方文档给出步骤，执行`yarn create umi myapp`后选择`ant-design-pro`, `Typescript`, `simple`

### 🏞 期望结果
没有报错，且openapi(swagger)能正常使用

### © 版本信息

- Ant Design Pro 版本: 5.2.0
- umi 版本: 3.5.0
- 浏览器环境 chrome
- 开发环境 windows

**Comment by chenshuai2144** [comment]
手动安装一下 btoa 吧

**Comment by weypro** [comment]
然而问题并没有解决，点击openapi菜单会会报错`Fetch error
Not Found /umi-plugins_undefined.json`
