### ISSUE TITLE
🧐[问题] 将依赖全部更新为@ant-design/pro-components 报错

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design-pro#9895]
将依赖（@ant-desion/pro-card / @ant-design/pro-layout........）全部更新为@ant-design/pro-components 报错
<img width="1012" alt="截屏2022-06-02 23 17 35" src="https://user-images.githubusercontent.com/183884/171665185-bce78376-829e-4204-90e1-86d3f7a04b21.png">

**Comment by WuJiY** [comment]
应该是config.ts 里的配置报错了
<img width="547" alt="截屏2022-06-02 23 29 28" src="https://user-images.githubusercontent.com/183884/171665339-23aba011-4cf4-4322-927f-e3d8eb3623d9.png">

**Comment by chenshuai2144** [comment]
写到项目里面吧，配置为自己的项目。
