### ISSUE TITLE
🧐[问题]  调用后端接口 没有返回后台response 返回如下

### ISSUE THREAD

**Issue by jxp1147** [ant-design/ant-design-pro#9897]
### 🧐 问题描述

Hi there! Please
[enable Javascript](https://www.enablejavascript.io/en)
in your browser to use Ant Design, Out-of-the-box mid-stage front/design solution!

### 💻 示例代码

    userLogin(values).then((res) => {
      if (res.token) {
        window.sessionStorage.setItem('token', res.token);
        history.push('/');
      } else {
        message.error('登录失败!');
      }
    });
### 🚑 其他信息

![image](https://user-images.githubusercontent.com/38196590/172134011-1e45a5e6-c977-45a8-9b79-0bed3fe456e7.png)

**Comment by gaoobin** [comment]
> 解决了吗，什么原因呀

你解决了吗，怎么解决的？

**Comment by jxp1147** [comment]
前端配置写错了






ls
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 上午8:23
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-pro] 🧐[问题]  调用后端接口 没有返回后台response 返回如下 (Issue #9897)





  
解决了吗，什么原因呀
  
你解决了吗，怎么解决的？

**Comment by gaoobin** [comment]
> 

感谢！我的代理url确实配置错了
