### ISSUE TITLE
请问Ant Pro v5 中，右侧的设置如何去掉🧐[问题]

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/ant-design-pro#9901]
### 🧐 问题描述

![image](https://user-images.githubusercontent.com/24889151/172363674-6d96f79d-bea5-4e4f-93f8-10e0f50c1c8f.png)

开发中显示ok，我这边部署项目的时候是，build静态文件，通过nginx去部署的。发现build完部署线上时候这个还是存在，请问通过什么设置可以取消显示

**Comment by pluooo** [comment]
老哥，这个问题处理了没

**Comment by AkarinServer** [comment]
找到App.tsx，然后把
<SettingDrawer
            disableUrlParams
            enableDarkTheme
            settings={initialState?.settings}
            onSettingChange={(settings) => {
              setInitialState((preInitialState) => ({
                ...preInitialState,
                settings,
              }));
            }}
          />
这一段注释掉就好了。
