### ISSUE TITLE
🧐[问题] Cors Policy Problem, No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-pro#9902]
Hello, I'm trying to send a request to another web service API other than its own web service API, but I'm stuck with cors policy.

```
  async getPaymentAccessToken() {
    const msg = await request<PaymentAccessTokenResponse>(`https://apitest.domain.com/accessToken/get`, {
      method: 'POST',
      prefix: undefined,
      headers: {
        client_id: this.client.client_id,
        client_secret: this.client.client_secret,
        'Access-Control-Allow-Origin': '*',
      },
    });

    return msg;
  }
```

> Access to fetch at 'https://apitest.domain.com/accessToken/get' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by xXAvoraXx** [comment]
Is there any solution for this ?

**Comment by xXAvoraXx** [comment]
Upp+++

**Comment by xXAvoraXx** [comment]
+UPPPPPP

**Comment by chenshuai2144** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_request_headers

@xXAvoraXx  [request headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_request_headers) 

need serve give
