### ISSUE TITLE
🧐[问题] preview.pro.ant.design 是否开源

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design-pro#9903]
### 🧐 问题描述

我想参考下preview.pro.ant.design里的实现，但是没有找到源码

**Comment by blockfsd** [comment]
不知道你找的是不是这个。
文档：https://pro.ant.design/zh-CN/docs/getting-started
![image](https://user-images.githubusercontent.com/40328254/172544466-a58e8c0b-c235-4c4d-ae3f-691a43a551fa.png)

**Comment by jackywei1228** [comment]
楼上的正解.
