### ISSUE TITLE
路由配置 target: "_blank" 时只有第一次会打开新窗口，后面点击不会打开新的窗口

### ISSUE THREAD

**Issue by jx-zyf** [ant-design/ant-design-pro#9905]
### 🧐 问题描述

路由配置 path为非http/https地址 并且 target 为 _blank 时只有第一次会打开新窗口，后面点击不会打开新的窗口

只有path是http/https地址时，每次才会打开新的窗口

### 💻 示例代码

```js
export default [
  {
    path: '/test',
    name: 'test',
    component: 'xxx',
    target: '_blank',   // 只有第一次会打开新窗口，后面都是刷新第一次打开的窗口
  },
  {
    path: '/test',
    name: 'test',
    component: 'https://pro.ant.design',
    target: '_blank',  // 每次都是新窗口
  },
]
```

**Comment by jx-zyf** [comment]
@chenshuai2144 请问这是bug还是我使用方式有问题？

**Comment by chenshuai2144** [comment]
我忘记查了

**Comment by jx-zyf** [comment]
@chenshuai2144 请问查了么？

**Comment by chenshuai2144** [comment]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/8186664/176373945-beb08447-1812-4238-9d42-f113c53ab611.png">


看起来没什么问题

**Comment by chenshuai2144** [comment]
![Uploading image.png…]()



估计是因为这个原因，浏览器版本有相关的优化
