### ISSUE TITLE
编译后为什么会按路由配置生成

### ISSUE THREAD

**Issue by ywzou** [ant-design/ant-design-pro#9906]
yarn build 编译以后，按路由生成了资源文件，并且每个里面都是相同内容的index.html文件

![image](https://user-images.githubusercontent.com/11622651/172755869-1f1d6ab9-6221-449d-a76d-003cbd4edf97.png)

**Comment by chenshuai2144** [comment]
https://umijs.org/zh-CN/config#exportstatic

exportStatic
Type: object
配置 html 的输出形式，默认只输出 index.html。

如果需要预渲染，请开启 [ssr](https://umijs.org/zh-CN/config#ssr-32) 配置，常用来解决没有服务端情况下，页面的 SEO 和首屏渲染提速。

如果开启 exportStatic，则会针对每个路由输出 html 文件。
