### ISSUE TITLE
🧐[问题]antd pro v5中，从服务器获取菜单之后，这个菜单的路径在routes.ts中没有申明，该component不显示，但是这个component写的路径我本地有代码，如何解决

### ISSUE THREAD

**Issue by dj49846917** [ant-design/ant-design-pro#9908]
请问下，如何实现在app.tsx的layout中，从服务器获取菜单数据后，把路由也渲染上去

我现在遇到个需求，就是菜单路径是动态的，每个菜单里面的这个components的地址我本地有的，我没有在routes.ts中声明，当加载服务器接口的菜单之后，点击菜单路由就不显示了，怎么解决呢，比如说点击/test或者/formtest，右边的页面不显示

💻 示例代码
在app.tsx中：
menu: {
request: async () => {
const params = {
"data": "983320445981683712",
"operator": "",
"source": "PC",
"traceId": "",
"version": "1"
}
return loopMenuItem(result.data)
}
},
这个接口返回的路由是
[
{"path":"/","redirect":"/test"},{"menuId":"1534456918397591553","path":"/test","icon":"InboxOutlined","name":"dashboard","component":"./DashBoard?pageId=983773871026860032","routes":[]},{"menuId":"984395911631073280","path":"/formTest","icon":"ProjectOutlined","name":"dashboard","component":"./DashBoard?pageId=983773871026860032","routes":[]}
]

routes.ts中的路由文件
{
path: '/',
redirect: '/dashboard',
},
{
path: '/dashboard',
icon: 'HomeOutlined',
name: 'dashboard',
component: './DashBoard',
}

**Comment by chenshuai2144** [comment]
你把全量路由配置上去，不要玩花活。路由在umi中起到了组织文件的作用，你如果路由不配，文件都不会打包的

**Comment by dj49846917** [comment]
难道框架不支持那种动态菜单跳转到动态路由吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈帅 ***@***.***&gt;
发送时间: 2022年6月9日 11:43
收件人: ant-design/ant-design-pro ***@***.***&gt;
抄送: dujiang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ant-design/ant-design-pro] ��[问题]antd pro v5中，从服务器获取菜单之后，这个菜单的路径在routes.ts中没有申明，该component不显示，但是这个component写的路径我本地有代码，如何解决 (Issue #9908)





 
你把全量路由配置上去，不要玩花活。路由在umi中起到了组织文件的作用，你如果路由不配，文件都不会打包的

**Comment by dj49846917** [comment]
路由component映射的地址是有页面文件的

**Comment by chenshuai2144** [comment]
动态路由和动态菜单是两种东西。

动态菜单只是 导航不同而已，路由早就存在了，只是透出的导航不同。什么路径访问什么代码已经确定了。
动态路由 需要在前端确定什么路径访问什么代码，这个对应关系需要自己维护，并且自己实现路径到代码的映射

**Comment by GanYongHao** [comment]
为什么打包不能自己加入pages下component组件？动态路由无法实现
