### ISSUE TITLE
GET请求参数的拼接有没有更为便捷的办法？

### ISSUE THREAD

**Issue by DuduStyle** [ant-design/ant-design-pro#991]
![qq 20180228102837](https://user-images.githubusercontent.com/31200868/36766793-61373ffa-1c72-11e8-8431-4ef39e7a61e3.png)

get请求时，怎么向类似如红线处所示自己拼接参数，而不是我手动拼接；

**Comment by chenshuai2144** [comment]
https://github.com/ljharb/qs
试试这个
