### ISSUE TITLE
🐛[BUG]无法使用键盘方向键控制表格滚动条滚动，完全没反应

### ISSUE THREAD

**Issue by Grain-full** [ant-design/ant-design-pro#9912]
使用 ant-design-pro 脚手架搭的项目，表格滚动条是无法使用键盘的方向键操作滚动的，点击表格后，按动方向键，如果有页面级滚动条就会把页面级滚动条滚动，表格的滚动条完全没有反应，此外，这种情况对于其它组件也同样是这样，我自己写过的 div DOM 的滚动条也同样无法使用键盘控制

期望：表格组件滚动条能使用键盘正常控制

使用的 antd 是 v4.16.13，@ant-design/pro-layout 是 v6.26.0，@ant-design/pro-table 是 v2.61.0

**Comment by chenshuai2144** [comment]
去antd 问一下，这个对 pro 来说有点超纲了

**Comment by Grain-full** [comment]
感觉不是 antd 那边导致，因为连普通的 div 产生的滚动条也无法使用键盘方向键控制
