### ISSUE TITLE
👑 [需求] 页面组件命名风格统一问题

### ISSUE THREAD

**Issue by moodpo** [ant-design/ant-design-pro#9913]
### 🥰 需求描述

pages 中目录命名混乱，有的大写有的小写，从很久之前就是这样，代码洁癖的我实在受不了了！

src/pages/user

其他组件是乱套的

![image](https://user-images.githubusercontent.com/2900814/173212738-3b6d1050-8fc7-4b6b-b175-c9d498934e1e.png)

### 🧐 解决方案

统一一下命名，要么是小写，要么大写！

### 🚑 其他信息

无

**Comment by chenshuai2144** [comment]
有子路径的小写，没子路径的是大写，看看文档
