### ISSUE TITLE
🧐[问题]runtimePublicPath  使用后umi自动引入的js路径不变

### ISSUE THREAD

**Issue by 3252152** [ant-design/ant-design-pro#9916]
### 🧐 问题描述
 在config中配置了 runtimePublicPath: true，然后再document.ejs 中对 window.resourceBaseUrl 中的值进行了赋值，但是启动后自动引入的umi.js和umi.css前缀没有变化，还是使用的 publicPath 的前缀，其他 url 前缀使用的是 window.resourceBaseUrl 中我指定的前缀，请问我使用的方法有没有问题。

### 🚑 **其他信息**
![image](https://user-images.githubusercontent.com/48384193/173476834-2324df19-e403-4321-9317-b84745b76775.png)
![image](https://user-images.githubusercontent.com/48384193/173476919-97bff16f-f174-4e81-b206-166098c80c14.png)
![image](https://user-images.githubusercontent.com/48384193/173477001-f21aecf1-ec47-4fee-9e79-d9069085969c.png)
![image](https://user-images.githubusercontent.com/48384193/173477087-a5293cc9-ba2d-4fe8-bd6e-0e3bc97dfaac.png)

**Comment by chenshuai2144** [comment]
注意一下顺序，要放到最前面

**Comment by 3252152** [comment]
> 注意一下顺序，要放到最前面

我已经把它放到最上面了，还是不行，看build生成的index,html，href是写死的，这里是不是一个bug？

**Comment by chenshuai2144** [comment]
js 和 css 是base控制的，不是 runtimePublicPath

**Comment by 3252152** [comment]
> 
base 好像是不能动态去变的吧，我这边有个需求要根据不同的ip显示不同的前缀，请问有没有办法能实现。

**Comment by 3252152** [comment]
> js 和 css 是base控制的，不是 runtimePublicPath

base 好像是不能动态去变的吧，我这边有个需求要根据不同的ip显示不同的前缀，请问有没有办法能实现。

**Comment by chenshuai2144** [comment]
这个让容器做吧，nginx可以配置servename。
js不能再加载自己前控制自己的加载。
