### ISSUE TITLE
@ant-design/pro-layout 6.38.4 pageTitleRender={false} 设置无效 🧐[问题]

### ISSUE THREAD

**Issue by zhouyan1992** [ant-design/ant-design-pro#9917]
### 💻 示例代码
 <ProLayout
      logo={logo}
      formatMessage={formatMessage}
      {...props}
      pageTitleRender={false}
      onMenuHeaderClick={() => history.push('/')}
      menuItemRender={(item, defaultDom) => {
        return <Link to={item.path}>{defaultDom}</Link>;
      }}
      menuDataRender={menuDataRender}
      rightContentRender={() => <RightContent />}
    >
      <PageTab>{children}</PageTab>
    </ProLayout>

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/19989534/173521902-af033906-bbf0-4c7b-a25d-3dc3c6f60ef3.png)

**Comment by chenshuai2144** [comment]
看看是不是版本重复了，引入了两个 pageTitleRender 了

**Comment by chenshuai2144** [comment]
...props 这种的代码看看有没有

pageTitleRender 在项目中是可以跑得。
