### ISSUE TITLE
🐛[BUG]菜单配置的path值，会影响菜单的高亮逻辑

### ISSUE THREAD

**Issue by Wensheng2276** [ant-design/ant-design-pro#9919]
### 🐛 bug 描述

菜单配置的path值，会影响菜单的高亮逻辑

### 📷 复现步骤

1、路径为`/app/a/b`时，`/app`和`/app/a`高亮：
![image](https://user-images.githubusercontent.com/28287913/173772683-94d7bc08-baab-4be0-ad44-a04cd924b99a.png)

为了验证菜单的高亮逻辑，我试了下面的情况
2、路径为`/app/c`时，`/app`高亮，且`/app`有展开动作：
![image](https://user-images.githubusercontent.com/28287913/173776315-8b7448dc-63b0-4a90-920a-273bafbad898.png)

3、路径为`/app/d`时， `/app`、`/app2`高亮，且`/app`有展开动作：
![image](https://user-images.githubusercontent.com/28287913/173776364-c659bb64-d9f4-4975-818e-f6512c196109.png)
4、路径为`/app2/e`时，`/app`、`/app2`高亮，且`/app2`有展开动作：
![image](https://user-images.githubusercontent.com/28287913/173776399-d17d2f35-17d9-4f40-8c5e-fe0f4a161898.png)

### 🏞 期望结果

期望根据配置的层级关系来高亮菜单，不希望受到path值的影响。

### 💻 复现代码

routers.js配置如下
```
[
  {
    name: "/app",
    path: "/app",
    exact: true,
    routes: [
      {
          name: "/app/a",
          path: "/app/a",
          exact: true,
          component: './Welcome',
      },
      {
          name: "/app/a/b",
          path: "/app/a/b",
          exact: true,
          component: './Welcome',
      },
      {
          name: "/app2/e",
          path: "/app2/e",
          exact: true,
          component: './Welcome',
      },
    ]
  },
  {
      name: "/app/c",
      path: "/app/c",
      exact: true,
      component: './Welcome',
  },
  {
    name: "/app2",
    path: "/app2",
    exact: true,
    routes: [
      {
          name: "/app/d",
          path: "/app/d",
          exact: true,
          component: './Welcome',
      },
    ]
  }
]
```

### © 版本信息

- Ant Design Pro 版本: [5.2.0]
- umi 版本 [3.5.0]
- 浏览器环境 [chrome 102.0.5005.63]
- 开发环境 [ win10]

**Comment by chenshuai2144** [comment]
菜单高亮就是跟着路由 和 pathname 来着。

菜单是一棵树，pathname 也是一棵树。

**Comment by Wensheng2276** [comment]
> 

我目前的项目因为历史遗留的问题会出现这种菜单位置不合理的情况，不知道是不是可以把pathname的影响给去掉。

**Comment by Wensheng2276** [comment]
> 菜单高亮就是跟着路由 和 pathname 来着。
> 
> 菜单是一棵树，pathname 也是一棵树。

我目前的项目因为历史遗留的问题会出现这种菜单位置不合理的情况，不知道是不是可以把pathname的影响给去掉。

**Comment by chenshuai2144** [comment]
用selectKeys 自己搞吧，pathname是我layout做任何事情的基石

**Comment by Wensheng2276** [comment]
> 用selectKeys 自己搞吧，pathname是我layout做任何事情的基石

好吧，如果要实现demo里的菜单展示形式的切换，是不是就不能用layout了，要自己实现全部的layout功能

**Comment by chenshuai2144** [comment]
你可以自定义 openKeys 自己管高亮逻辑，别的可以继续用

**Comment by Wensheng2276** [comment]
> 你可以自定义 openKeys 自己管高亮逻辑，别的可以继续用

好的，非常感谢

**Comment by Wensheng2276** [comment]
> 你可以自定义 openKeys 自己管高亮逻辑，别的可以继续用

抱歉又要打扰下，我设置了selectKeys，可以实现左侧菜单按照想要的逻辑选中和展开。

可是当切换到mix模式下，出现了下面的问题：
当选中/app下的/app2/e的时候，会跳转到/app2菜单下。
在onOpenChange事件里看到，还是触发了/app2的展开。
请问有什么方式可以完全按照openKeys来吗？

![image](https://user-images.githubusercontent.com/28287913/174587580-5695f326-e2c4-4a21-8984-3f8eb4143a6f.png)

**Comment by chenshuai2144** [comment]
忽略掉他的自动change 呢？ 
因为内部计算发生了改变所以还是会触发一下onchange 的，方便数据同步
