### ISSUE TITLE
如何动态创建菜单？后台加载🧐[问题]

### ISSUE THREAD

**Issue by hyzx86** [ant-design/ant-design-pro#9920]
### 🧐 问题描述
低代码应用中，需要从现有组件根据参数不同渲染不同结果，比如动态列表/菜单等

以下这段代码将在默认路由加载后根据后台配置加载
所有动态页面都是用  `'./develop/dynamicPage'` 组件根据 `meta.schemaId` 进行渲染
 ``` typescript
[
{
        name: 'amisEditor111',
        path: '/editor111',
        locale: false,
        meta: { schemaId: '111111' },
        component: './develop/dynamicPage',
      },
{
        name: '客户管理',
        path: '/customers',
        locale: false,
        meta: { schemaId: '22222' },
        component: './develop/dynamicPage',
      },

]
```

根据这个地址的 介绍，https://blog.csdn.net/qq_38506368/article/details/118495903
``` javascript
let normalizedRoutes;

// umi3.x 需要将 routes 选项从第一个参数中解构: patchRoutes({ routes }) {}
export function patchRoutes(routes) {
  if (normalizedRoutes) {
    mergeRoutes(normalizedRoutes, routes);
  }
}

// oldRender 至少需要被调用一次
export function render(oldRender) {
  fetch('/api/routes').then(res=>res.json()).then((res) => { 
    normalizedRoutes = res.routes;
    oldRender();
  })
}

const mergeRoutes = (routes, parentRoute) => {
	if (!Array.isArray(routes)) return [];
	return routes.map(route => {
 		if (route.path) {
         	route.path = route.path.startsWith('/')
             	? route.path
             	: `${parentRoute?.path || ''}/${route.path}`;
     	}
     	if (route.component) {
         	route.component = (component => {
             	if (typeof component === 'function') {
                 	return component;
             	}
             	// eslint-disable-next-line global-require, import/no-dynamic-require, prefer-template
             	return require('./pages/' + component.substr(component.indexOf('/') + 1)).default;
         	})(route.component);
     	}
     	if (route.routes) {
         	route.routes = mergeRoutes(route.routes, route);
     	}
     	return route;
 	});
 };
```
 在 app.tsx 中调用：

``` JavaScript
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    // 后台菜单
    menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: {
        // userId: initialState?.currentUser?.userid,
        menuData: initialState?.serverSideSettings?.menuData,
      },
      request: async (params, defaultMenuData: []) => {
        const serverSideMenudata = initialState?.serverSideSettings?.menuData;
        if (serverSideMenudata) {
          const routes = [...staticRoutes, ...serverSideMenudata];
          patchRoutes([...routes]); //动态路由
          return fixMenuItemIcon(routes);
        } else {
          console.log('params, defaultMenuData: ', params, defaultMenuData);

          return defaultMenuData;
        }
      },
    },
```

vscode 控制台但是会出现 这个问题报错：
是不是处理了 ejs的解析器就能解决这个问题了呢？
``` log

 error  in ./src/pages/document.ejs

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!DOCTYPE html>
| <html lang="en">
|   <head>
```

![image](https://user-images.githubusercontent.com/15613121/173944743-ec1f3ff7-8162-4f64-8466-47951f1783cd.png)

可能与此需求类似
https://github.com/ant-design/ant-design-pro/issues/9655

**Comment by xiahller** [comment]
有动态加载路由的方法吗，而不是routes里面默认获取，不仅仅是菜单动态获取，路由可以动态获取吗

**Comment by hyzx86** [comment]
> 有动态加载路由的方法吗，而不是routes里面默认获取，不仅仅是菜单动态获取，路由可以动态获取吗


我也想知道。。
这个文档不知道是过期的还是怎么的。。不起作用啊

https://umijs.org/zh-CN/docs/runtime-config#patchroutes-routes-

**Comment by hyzx86** [comment]
菜单出来了。。但是路由还是404
``` javascript
export function patchRoutes({ routes }) {
  routes[0].routes[7].routes.push({
    name: 'amisEditor111',
    path: '/editor111',
    locale: false,
    meta: { schemaId: '40emtqq91aqe855bydkj268gx6' },
    component: dynamic({
      loader: () => import(/* webpackChunkName: 'README.md' */ './pages/develop/dynamicPage'),
      loading: LoadingComponent,
    }),
  });

  console.log(routes, 'patchRoutespatchRoutes');
  return routes;
}
```

持续爬坑中...

**Comment by hyzx86** [comment]
以上的测试

![image](https://user-images.githubusercontent.com/15613121/173977150-3955a97f-91a6-43d6-a331-4dc0ed0d0c58.png)

**Comment by xiahller** [comment]
> 

请问你截图上的菜单和路由都是动态加载的吗？

**Comment by hyzx86** [comment]
> 请问你截图上的菜单和路由都是动态加载的吗？`

只有 editor111 ，截图选中的部分

**Comment by hyzx86** [comment]
官方文档 https://umijs.org/zh-CN/docs/runtime-config#patchroutes-routes-
没用~~

**Comment by xiahller** [comment]
> > 请问你截图上的菜单和路由都是动态加载的吗？`
> 
> 只有 editor111 ，截图选中的部分

https://github.com/ant-design/ant-design-pro/issues/9468你看看这个呢

**Comment by hyzx86** [comment]
修复下你的链接，然后看了下。。表示没看懂~ 懵逼树上懵逼果

https://github.com/ant-design/ant-design-pro/issues/9468

**Comment by hyzx86** [comment]
我试了他的代码，没用。。我只是没有写, 加上去也不行。
```
 export function render(oldRender: () => void) {
  // fetch('/api/routes').then(res=>res.json()).then((res) => {
  oldRender();
  // })
}
```

**Comment by chenshuai2144** [comment]
动态路由是没有前途的。

**Comment by hyzx86** [comment]
为啥没前途啊。。
我要做低代码，菜单不能动态渲染哇。。
所以我可以在不改变 路由定义的情况下修改菜单？

比如 下面这个。。
但是动态菜单又要怎么耍嘞？


[
{
       name: 'amisEditor111',
       **path: '/page/:schemaId',**
       locale: false,
       _meta: { schemaId: '111111' },_
       component: './develop/dynamicPage',
     },
{
       name: '客户管理',
       **path: '/page/:schemaId',**
       locale: false,
       component: './develop/dynamicPage',
     },

]

**Comment by hyzx86** [comment]
@chenshuai2144  大佬先别关啊。。。
问题还没解决嘞~~

**Comment by chenshuai2144** [comment]
菜单和路由是两个概念
动态菜单已经很方便了

**Comment by xiahller** [comment]
> 

请问，如果需要在页面上添加菜单页面，但路由里面不包括新添加的页面路径，如何做呢

**Comment by chenshuai2144** [comment]
你全量写路由。

路由不写代码直接不会被编译进去。

**Comment by xiahller** [comment]
> 你全量写路由。
> 
> 路由不写代码直接不会被编译进去。

但我无法将用户再页面添加的菜单（特别是有几级菜单的那种）和路由匹配结合起来

**Comment by hyzx86** [comment]
> 你全量写路由。
> 
> 路由不写代码直接不会被编译进去。

是的 我这个动态页面在路由定义的时候实际上已经写了
![image](https://user-images.githubusercontent.com/15613121/173983537-e2943914-bcd3-41b4-a8c5-671231b9d9e5.png)

![image](https://user-images.githubusercontent.com/15613121/173983526-b9f98f3b-daa3-4771-b479-59cd8d7e6a52.png)

**Comment by xiahller** [comment]
> 



> > 你全量写路由。
> > 路由不写代码直接不会被编译进去。
> 
> 是的 我这个动态页面在路由定义的时候实际上已经写了 ![image](https://user-images.githubusercontent.com/15613121/173983537-e2943914-bcd3-41b4-a8c5-671231b9d9e5.png)
> 
> ![image](https://user-images.githubusercontent.com/15613121/173983526-b9f98f3b-daa3-4771-b479-59cd8d7e6a52.png)

但我不知道如何设计页面才能让用户添加的菜单、页面（特别是有几级菜单的那种页面）匹配起来

**Comment by chenshuai2144** [comment]
```
path: '/page/:schemaId',

path: '/page/:id',
```

这两个 path 不相等吧

**Comment by hyzx86** [comment]
诶 对 。。可以了 
我再试试加meta 行不行，这样可读性不太好
![image](https://user-images.githubusercontent.com/15613121/173984294-9f1be3f5-2672-47ed-945b-04b25aca26d2.png)

**Comment by hyzx86** [comment]
额 传不过去，  不用id 该用name 传参好嘞，
感谢答复

**Comment by xiahller** [comment]
> 诶 对 。。可以了 我再试试加meta 行不行，这样可读性不太好 ![image](https://user-images.githubusercontent.com/15613121/173984294-9f1be3f5-2672-47ed-945b-04b25aca26d2.png)

如果存在新增二级甚至三级页面如何解决，比如：新增的第一级是配置的amisEditor111，但还需要新增子级

**Comment by hyzx86** [comment]
> 如果存在新增二级甚至三级页面如何解决，比如：新增的第一级是配置的amisEditor111，但还需要新增子级

难道不是随便加么？
刚才大佬讲了 ，菜单跟路由是两回事，路由配置可以设置规则
菜单这里只是一个跳转啊，匹配上路由规则就可以了

**Comment by xiahller** [comment]
> > 如果存在新增二级甚至三级页面如何解决，比如：新增的第一级是配置的amisEditor111，但还需要新增子级
> 
> 难道不是随便加么？ 刚才大佬讲了 ，菜单跟路由是两回事，路由配置可以设置规则 菜单这里只是一个跳转啊，匹配上路由规则就可以了

可以了，刚刚自己mock数据的时候自己写错了数据。谢谢~完美落幕

**Comment by hyzx86** [comment]
简单总结下，我不知道 dynamic() 导入是否存在问题，在上面的测试中，组件确实是导入进去了

1. 那么会不会是打包的问题？打包时只打包静态路由配置文件中指定的文件，难道不能直接将所有pages 文件夹下打包么？
2. 如果组件找到了，还是报404 ， 那就是路由规则不能动态注册？？ 这东西没得法子在运行时调整？

**Comment by haiyatx** [comment]
[ttps://blog.csdn.net/haiyabtx/article/details/127363731](https://blog.csdn.net/haiyabtx/article/details/127363731)
配置路由+登录路由

**Comment by fengjihua** [comment]
/config/routes.ts
```
  {
    name: 'low-code',
    path: '/low-code/:name',
    component: './LowCode',
    hideInMenu: true,
  },
```

/app.tsx
```
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    // 自定义菜单：动态添加低代码页面
    menu: {
      params: {},
      request: async (params, defaultMenuData: any[]) => {
        console.log('[menu]', params, defaultMenuData);
        const lowCodePages = [
          {
            name: 'suppliers',
            path: '/low-code/suppliers',
          },
          {
            name: 'customers',
            path: '/low-code/customers',
          },
        ];
        defaultMenuData.push(...lowCodePages);
        return defaultMenuData;
      },
    },
    ...initialState?.settings,
  };
};
```


/src/pages/LowCode/index.tsx
```
import { useParams, useLocation } from 'umi';

function LowCode() {
  // 使用useParams获取动态路由参数
  const { name } = useParams();
  const location = useLocation();

  return (
    <div>
      <h1>Welcome to {name} Page</h1>
      <p>This is a dynamic page for {name}.</p>
      <p>Dynamic routes: {location.pathname}.</p>
    </div>
  );
}

export default LowCode;
```

**Comment by xXAvoraXx** [comment]
https://github.com/ant-design/ant-design-pro/discussions/10898
