### ISSUE TITLE
🧐[问题] 项目过大的时候 开启了mfsu功能 修改以后，项目全局刷新，但是异常缓慢。

### ISSUE THREAD

**Issue by wangJacker** [ant-design/ant-design-pro#9921]
### 🧐 问题描述
修改项目文件，发现修改组件代码，以及自定义hooks的代码，热更新全局刷新，基本要等一分钟左右才能全部刷新出来，修改页面的内容似乎会快一些，尝试关闭mfsu但是并没有生效，请问有人遇到果这个问题么？

**Comment by hpf0532** [comment]
同遇到

**Comment by chenshuai2144** [comment]
> 修改项目文件，发现修改组件代码，以及自定义hooks的代码，热更新全局刷新，基本要等一分钟左右才能全部刷新出来，修改页面的内容似乎会快一些，尝试关闭mfsu但是并没有生效，请问有人遇到果这个问题么？

修改config 会重启 umi。

修改正常代码应该是问题不大的，用这个方法看看详细数据

https://juejin.cn/post/6844904056985485320

**Comment by wangJacker** [comment]
感谢大佬的回复，目前发现问题是webpack编译是很快就过了 但是更多的时间是在等待浏览器的进程刷新，似乎有某个进程一直在占用浏览器，有时候手动刷新，还不如重新开个浏览器标签来的更快目前我折中的方法是：
1、关闭mfsu，（将mfsu配置项注释掉）
2、删除本地.umi文件
3、开启fastRefresh配置项

这样做的缺点：项目启动没有开启mfsu功能的时候快
优点：像刚刚那种占用浏览器进程刷新不出来的问题得以解决 

也不知道是不是我自己配置的问题，目前这样做开发相率不会受影响，只是启动时候慢一些

**Comment by chenshuai2144** [comment]
能看一下是什么东西堵塞了吗？来个截图试试

**Comment by wangJacker** [comment]
![image](https://user-images.githubusercontent.com/33062942/177145652-969b7ddf-329b-4fb8-a2ae-3efde03275d8.png)

**Comment by httol** [comment]
遇到了；不知道怎么解决。另外内存经常爆

**Comment by httol** [comment]
> 感谢大佬的回复，目前发现问题是webpack编译是很快就过了 但是更多的时间是在等待浏览器的进程刷新，似乎有某个进程一直在占用浏览器，有时候手动刷新，还不如重新开个浏览器标签来的更快目前我折中的方法是： 1、关闭mfsu，（将mfsu配置项注释掉） 2、删除本地.umi文件 3、开启fastRefresh配置项
> 
> 这样做的缺点：项目启动没有开启mfsu功能的时候快 优点：像刚刚那种占用浏览器进程刷新不出来的问题得以解决
> 
> 也不知道是不是我自己配置的问题，目前这样做开发相率不会受影响，只是启动时候慢一些

一样的问题

**Comment by chenshuai2144** [comment]
要不升级下 umi@3 吧，旧版本我们估计不会看问题了
