### ISSUE TITLE
🧐[Modal 弹窗使用 useAccess]

### ISSUE THREAD

**Issue by KiligFei** [ant-design/ant-design-pro#9922]
### 🧐 问题描述

Modal 弹窗使用 useAccess() 返回 null
弹窗是不可以使用吗

**Comment by chenshuai2144** [comment]
理论上是可以的。有代码吗

**Comment by KiligFei** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/69230517/174741077-49dd7386-719b-4d8a-977c-b71cf04ed073.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/69230517/174741175-f7be22fb-54cc-468c-8c69-d481e65b8320.png">
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/69230517/174741243-6ac418bb-ba7e-41d2-b461-1f99e0b3321d.png">

**Comment by KiligFei** [comment]
谢谢，暂时没有太多时间去做一个简单的 demo ，抱歉只能贴几张图，有空我会去做一个demo

**Comment by chenshuai2144** [comment]
不能在utils 中使用的，因为没有hooks的上下文，你可以封装一个自己的modal组件，在组件里面去使用useAccess。

```

const AccessModal = ()=>{
 const Access = useAccess();
 return <Moda l/>
}
```

**Comment by KiligFei** [comment]
👌。谢谢
