### ISSUE TITLE
侧边栏渲染 ul 标签 items="[object Object]" 🧐[问题]

### ISSUE THREAD

**Issue by goodkirk** [ant-design/ant-design-pro#9925]
远程加载数据，使用菜单高级使用方法的代码，DOM渲染出来ul 标签 items="[object Object]" 没有li标签
![image](https://user-images.githubusercontent.com/107540004/174456823-521609e1-1756-4500-8703-4994452c94f7.png)

**Comment by chenshuai2144** [comment]
注意下 antd 的版本，是不是4.20 以上了

**Comment by goodkirk** [comment]
antd升级到最新解决此问题

陈帅 ***@***.***> 于2022年6月20日周一 14:28写道：
