### ISSUE TITLE
🧐[问题] ant design pro 5.2.0 npm start error

### ISSUE THREAD

**Issue by robin536180** [ant-design/ant-design-pro#9926]
### 🧐 问题描述

yarn install success，but npm start failed

### 💻 示例代码
 ERROR  Failed to compile with 1 errors                                                                                                                 23:00:28 error  in ./node_modules/react-sticky-box/dist/index.jsModule not found: Error: Can't resolve '/Users/carol/Desktop/ui/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/slicedToArray' in '/Users/carol/Desktop/ui/node_modules/react-sticky-box/dist'Did you mean 'slicedToArray.js'?
BREAKING CHANGE: The request '/Users/carol/Desktop/ui/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/slicedToArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by chenshuai2144** [comment]
清空缓存重新处理下你的依赖吧。
应该是库不规范导致的

**Comment by robin536180** [comment]
> 清空缓存重新处理下你的依赖吧。 应该是库不规范导致的

清理魂村也没用，请问需要怎么处理呢？能给点建议吗？

**Comment by chenshuai2144** [comment]
这个是babel的错误，只能全部清空然后重试了
