### ISSUE TITLE
🐛[BUG] 通用配置页面Crash

### ISSUE THREAD

**Issue by Corazon0513** [ant-design/ant-design-pro#9928]
### 🐛 bug 描述

通用配置页面Crash
https://procomponents.ant.design/components/schema/

### 📷 复现步骤

https://procomponents.ant.design/components/schema/
打开该页面 向下滑动至“远程数据”附近即可触发

### © 版本信息

- 浏览器环境 Safari 15.5 (arm64) & Chrome 102.0.5005.115 (arm64)
- 开发环境 macOS (arm64)

### 🚑 其他信息

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/41325162/174553988-181b857a-ae87-491c-8f37-98581cd52f4d.png">

**Comment by chenshuai2144** [comment]
已经修复了，感谢提醒
