### ISSUE TITLE
🧐[问题] 基于umijs4 的 pro 什么时候发布呀？

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#9929]

**Comment by hihuangwei** [comment]
期待...

**Comment by shizhier** [comment]
试了antd pro。最新的项目使用的模版默认就是umi4，样子太丑了。没有以前的好看。有啥办法使用原来的模版？？？

**Comment by iscmcloud** [comment]
`antd: {
    compact: true, 
  }`
umi4中examples带的pro例子，在紧凑模式下，一级菜单比二级菜单的字体还小

**Comment by luxu1220** [comment]
怎么不能选 ts 和 js 了....

**Comment by way-jm** [comment]
期待~

**Comment by gaspire** [comment]
期待~

**Comment by chenshuai2144** [comment]
发布了

**Comment by imoxuan** [comment]
> 发布了

哪里呢？没找到呢

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues
