### ISSUE TITLE
使用yarn create umi myapp模版问题🧐[问题]

### ISSUE THREAD

**Issue by shizhier** [ant-design/ant-design-pro#9930]
### 🧐 问题描述

umi4.0后，现在使用yarn creat umi app，默认使用的是Umi4.0。如何才可以使用原来的模版？？？
### 💻 示例代码

yarn create umi myapp 默认umi 4.0

**Comment by edifangyi** [comment]
两天了 没人处理吗？？？

**Comment by yuli-lovely** [comment]
官方大大快出来

**Comment by 4LostGreyWolf** [comment]
直接整成 umijs/max 的框架了

**Comment by 4LostGreyWolf** [comment]
文档也不改一下，配置信息也不能用，现在的模板样式都不能调整

**Comment by kkh666** [comment]
> 

create-umi.cmd myapp2 请问这个命令提示不存在是咋回事呀 @gsgs-libin

**Comment by denghuishenmi** [comment]
先在全局配置上添加create-umi命令，然后再使用添加的create-umi命令去指定项目名称生成项目即可创建umi3的项目。
>yarn global add create-umi@0.27.0
>create-umi myapp

**Comment by denghuishenmi** [comment]
> > 
> 
> create-umi.cmd myapp2 请问这个命令提示不存在是咋回事呀 没看懂cmd路径改一下要咋改 @gsgs-libin @shizhier

先在全局配置上添加create-umi命令，然后再使用添加的create-umi命令去指定项目名称生成项目即可创建umi3的项目。

yarn global add create-umi@0.27.0
create-umi myapp

以后创建umi3.0的项目都是用该命令，如果重新使用了yarn create umi myapp会导致配置被覆盖，需要重新按上述添加命令

**Comment by robeterlk** [comment]
> > > 
> > 
> > 
> > create-umi.cmd myapp2 请问这个命令提示不存在是咋回事呀 没看懂cmd路径改一下要咋改 @gsgs-libin @shizhier
> 
> 先在全局配置上添加create-umi命令，然后再使用添加的create-umi命令去指定项目名称生成项目即可创建umi3的项目。
> 
> yarn global add create-umi@0.27.0 create-umi myapp
> 
> 以后创建umi3.0的项目都是用该命令，如果重新使用了yarn create umi myapp会导致配置被覆盖，需要重新按上述添加命令

你好，我照着你的来，create-umi myapp显示不是内部命令，前面的和你描述的一样的，这是什么原因导致的
