### ISSUE TITLE
[BUG] 每次从当前页面，切到浏览器其它tab，然后再返回当前tab时，ProTable组件里的request方法就会执行一次

### ISSUE THREAD

**Issue by EricWong1994** [ant-design/ant-design-pro#9932]
当前 Issue 未检测到标题，请规范填写，谢谢！

The title of the current issue is not detected, please fill in according to the specifications, thank you!

_Originally posted by @github-actions[bot] in https://github.com/ant-design/ant-design-pro/issues/9931#issuecomment-1161477850_

**Comment by chenshuai2144** [comment]
新版本默认关掉了，更新一下。



revalidateOnFocus | 窗口聚焦时自动重新请求 | boolean | true
-- | -- | -- | --
