### ISSUE TITLE
网络请求400错误页面有多个message告警

### ISSUE THREAD

**Issue by lihong12500** [ant-design/ant-design-pro#9933]
### 🧐 问题描述
使用mock，让返回400状态码，页面提示有多个message告警，其中一个没有内容。另外是页面配置，请问下没有内容那个哪儿来的？

mock:
function deleteRule(req: Request, res: Response, u: string)  {
  console.log('execute method of delete')
  res.send(400)
  // res.json({
  //   success: true,
  //   errorMessage: 'success error message',
  // })
}
app.tsx  code:
![1655802964(1)](https://user-images.githubusercontent.com/36000887/174764281-04eadee1-06fb-49e6-b493-3ec3b02147a5.png)
page code：
![1655803063(1)](https://user-images.githubusercontent.com/36000887/174764537-c8ba5be6-72f3-4b98-8aef-23f370641a26.png)

页面错误：
 
![1655803161(1)](https://user-images.githubusercontent.com/36000887/174765066-626a92eb-3c80-42c5-8012-139329319ae6.png)

**Comment by chenshuai2144** [comment]
https://v3.umijs.org/plugins/plugin-request#request

试试这个配置，你可以自定义一下错误处理

**Comment by kamasylvia** [comment]
> https://v3.umijs.org/plugins/plugin-request#request
> 
> 试试这个配置，你可以自定义一下错误处理

我试过，skipErrorHandler 后拿不到后端返回的 errorMessage
