### ISSUE TITLE
🧐[问题]yarn create umi没有办法选择语言且报node版本不支持

### ISSUE THREAD

**Issue by iodeal** [ant-design/ant-design-pro#9935]
### 🧐 问题描述
我使用yarn create umi来创建新项目，前天还是可以选择语言（ts/js）的，但是，今天再创建时，已经没有这一个选项了。我依次 选择模板->选择客户端->选择npm仓库，最终提示失败。我的npm版本是v17.8.0

### 🚑 其他信息
success Installed "create-umi@4.0.0" with binaries:
      - create-umi
✔ Pick Umi App Template › Simple App
✔ Pick Npm Client › yarn
✔ Pick Npm Registry › npm
.....省略
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ umi setup
error - Your node version 17 is not supported, please upgrade to 14 or above except 15 or 17.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
✨  Done in 478.66s.

**Comment by narutohinata** [comment]
![image](https://user-images.githubusercontent.com/7847534/174779890-5deacc87-5059-4181-b94e-b63170d49a65.png)
这样创建

**Comment by iodeal** [comment]
#9936

**Comment by iodeal** [comment]
#9936
