### ISSUE TITLE
create-umi命令 创建项目时 “ant-design-pro” 选项找不到 🧐[问题]

### ISSUE THREAD

**Issue by erichow** [ant-design/ant-design-pro#9936]

**Comment by erichow** [comment]
? Select the boilerplate type (Use arrow keys)
❯ ant-design-pro  - Create project with a layout-only ant-design-pro boilerplate, use together with umi block.
  app             - Create project with a easy boilerplate, support typescript.
  block           - Create a umi block.
  library         - Create a library with umi.
  plugin          - Create a umi plugin.
  
我想要上面这种的 simple 作为项目进行开发，但是现在找不到，变成了下面这样
  -------------------------------------------------------

erichow@zhoudamindeMacBook-Air workspace % npx create-umi pro
? Pick Umi App Template › - Use arrow-keys. Return to submit.
❯   Simple App
    Ant Design Pro
    Vue Simple App

**Comment by chentao2022621** [comment]
我也遇到同样的问题了 ，按官方文档执行 yarn create umi myapp 后 出现的是
![image](https://user-images.githubusercontent.com/17583790/174912386-a0d7098a-ff1a-4c47-a0ab-b861617b236f.png)

**Comment by maqinghao** [comment]
umi4.0 发布了吗,看官网没有更新呀! 同样遇到这个问题? 但是奇怪的是我在两台电脑上 效果不一样,npm版本不一样,一个是正常的克隆存储库,一个就是现在的问题了

**Comment by LinruoT** [comment]
我也是初学者，花了一上午才解决😂
create-umi已经升级到umi4的模板了，创建antd pro项目需要：
```
yarn create umi@0.27.0 umi3-app

#上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
yarn add create-umi@0.27.0
C:\Users\linrt\AppData\Local\Yarn\bin\create-umi.cmd myapp2
```
Select the boilerplate type ant-design-pro
Which language do you want to use? TypeScript
Do you need all the blocks or a simple scaffold? Simple

**Comment by tyanbiao** [comment]
> 我也是初学者，花了一上午才解决😂 create-umi已经升级到umi4的模板了，创建antd pro项目需要：
> 
> ```
> yarn create umi@0.27.0 umi3-app
> 
> #上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
> yarn add create-umi@0.27.0
> C:\Users\linrt\AppData\Local\Yarn\bin\create-umi.cmd myapp2
> ```
> 
> Select the boilerplate type ant-design-pro Which language do you want to use? TypeScript Do you need all the blocks or a simple scaffold? Simple

It works fine.

**Comment by nqhd3v** [comment]
oh no, when I run the command `yarn create umi@0.27.0 ui01`, it showed this error:
```
/bin/sh: /usr/local/bin/create-umi@0.27.0: No such file or directory
```
I am running it with node@16, Is something else?

**Comment by nqhd3v** [comment]
# [UPDATE]
# On *MacOS*, run some commands below to create a new app:
```
cd ~
yarn global add create-umi@0.27.0  
 ~/.config/yarn/global/node_modules/create-umi/cli.js your-app-name
```
Done, it should be something like that:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/106160187/174979053-a4035358-03a0-4227-aa07-ae5430e1e455.png">

**Comment by chentao2022621** [comment]
> 我也是初学者，花了一上午才解决😂 create-umi已经升级到umi4的模板了，创建antd pro项目需要：
> 
> ```
> yarn create umi@0.27.0 umi3-app
> 
> #上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
> yarn add create-umi@0.27.0
> C:\Users\linrt\AppData\Local\Yarn\bin\create-umi.cmd myapp2
> ```
> 
> Select the boilerplate type ant-design-pro Which language do you want to use? TypeScript Do you need all the blocks or a simple scaffold? Simple

it work fine!

**Comment by erichow** [comment]
> > 我也是初学者，花了一上午才解决😂 create-umi已经升级到umi4的模板了，创建antd pro项目需要：
> > ```
> > yarn create umi@0.27.0 umi3-app
> > 
> > #上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
> > yarn add create-umi@0.27.0
> > C:\Users\linrt\AppData\Local\Yarn\bin\create-umi.cmd myapp2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Select the boilerplate type ant-design-pro Which language do you want to use? TypeScript Do you need all the blocks or a simple scaffold? Simple
> 
> It works fine.

非常感谢~

**Comment by Xinjb** [comment]
> 我也是初学者，花了一上午才解决😂create-umi已经升级到umi4的模板了，创建antd pro项目需要：
> 
> ```
> yarn create umi@0.27.0 umi3-app
> 
> #上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
> yarn add create-umi@0.27.0
> C:\Users\linrt\AppData\Local\Yarn\bin\create-umi.cmd myapp2
> ```
> 
> 选择样板类型 ant-design-pro 你想使用哪种语言？TypeScript 你需要所有的积木还是一个简单的脚手架？简单

我也是初学者，花了一上午才解决😂
create-umi已经升级到umi4的模板了，创建antd pro项目需要：

yarn create umi@0.27.0 umi3-app

#上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
yarn add create-umi@0.27.0
C:\Users\linrt\AppData\Local\Yarn\bin\create-umi.cmd myapp2
Select the boilerplate type ant-design-pro
Which language do you want to use? TypeScript
Do you need all the blocks or a simple scaffold? Simple

**Comment by robeterlk** [comment]
> create-umi.cmd myapp2

能详细说下cmd路径改一下应该怎么修改么
