### ISSUE TITLE
🧐[问题] 热加载中断

### ISSUE THREAD

**Issue by ahan** [ant-design/ant-design-pro#9937]
### 🧐 问题描述
编写代码时，若不小心保存了一个 not defined 的变量时，热编译会中断退出。
因为重新 npm run start 一次要挺久的，所以想问下有没有办法编译代码发现有错时，可以打出错误日志，但不退出热加载？

### 💻 示例代码
<img width="403" alt="image" src="https://user-images.githubusercontent.com/654880/174851509-f38e58cb-8d9e-470a-bcd9-1398ca41bc11.png">

### 🚑 其他信息
<img width="516" alt="WX20220622-002752@2x" src="https://user-images.githubusercontent.com/654880/174850999-9c68d50c-4a23-43ab-8c62-f1f918021ee7.png">

**Comment by frontend-winter** [comment]
同感

**Comment by chenshuai2144** [comment]
config 文件里面是node，每次修改都要重启项目，src里面的就好了

**Comment by minlib** [comment]
这个问题能解决吗？

开发大部分时间都在运行 npm start

**Comment by chenshuai2144** [comment]
"React 热加载中断" 是开发人员在使用 React 热加载时常遇到的问题。当热加载过程（负责实时更新组件）被中断或未能顺利完成时，就会发生这个问题。

造成这个中断的原因可能有以下几点：

- 代码中的语法错误
- 代码的更改破坏了预期行为
- 其他第三方模块的问题

要解决这个问题，请检查代码以确保其正确无误，并检查是否有其他模块对热加载过程造成影响。
