### ISSUE TITLE
app.tsx中使用useModel👑 [需求]

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design-pro#9938]
### 🥰 需求描述

某些场景需要在app渲染时执行一些model，例如从服务端获取Menus并保存在model中，或者获取一些额外业务数据。此类数据较为业务性，不适合放入initialState中。并且，有些静态数据，数据仅需要在app第一次挂载时获取，随后在页面间切换时无需再获取。

当前app.tsx仅暴露了约定式的变量，无法编写组件，即无法在里面执行hooks（useXXXModel）等。

### 🧐 解决方案

1. 在app.tsx中暴露出一个 useInit hook，用户可以执行相应的初始化，在layout变量中能够访问这些models变量。
2. 或者允许用户返回一个function component version of ProLayout，用来替代当前的layout变量。

### 🚑 其他信息

最新版本Ant Design Pro

**Comment by chenshuai2144** [comment]
`export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
`

注入了 initialState 了，太自由是不好的，必需严格控制数据流向。
