### ISSUE TITLE
项目build太慢，build成功需要十二分钟🧐[问题]

### ISSUE THREAD

**Issue by complete-fangzr** [ant-design/ant-design-pro#9939]

**Comment by chenshuai2144** [comment]
搞个重现 ，你是不是搞了一堆比较大的库？

**Comment by complete-fangzr** [comment]
> 
![image](https://user-images.githubusercontent.com/93582316/175925782-d1c1b0c8-f30d-4296-8094-61c2ec25b239.png)
![image](https://user-images.githubusercontent.com/93582316/175925990-afd740ed-bf93-4201-8f3a-8239ae977932.png)
有什么优化方案吗

**Comment by complete-fangzr** [comment]
> 搞个重现 ，你是不是搞了一堆比较大的库？
![image](https://user-images.githubusercontent.com/93582316/175926230-4d27c5a9-8896-4c8b-b000-f362d4898b29.png)
![image](https://user-images.githubusercontent.com/93582316/175926272-cc20bbb9-d489-4806-b096-b46bd1c5c811.png)
有什么优化方案吗@chenshuai2144

**Comment by chenshuai2144** [comment]
看起来还行，你要用webpack debug模式看看什么在浪费时间。

如果是压缩  可以改用esbuild
如果是编译 可以控制babel的配置，尽量减少编译的文件数量
如果是页面太多导致的  建立升级机器

**Comment by complete-fangzr** [comment]
@chenshuai2144 babel也是在config.ts里面配吗，要怎么配啊

**Comment by chenshuai2144** [comment]
chainWebpack

https://umijs.org/docs/api/config#chainwebpack

看看这个
