### ISSUE TITLE
用手机 访问ant-design-pro发现Dropdown菜单无效

### ISSUE THREAD

**Issue by xiak** [ant-design/ant-design-pro#994]
手机: iphoneX

访问地址： https://preview.pro.ant.design/#/dashboard/analysis

问题： 点击右上角用户头像，不能像在电脑上一样有下拉菜单出现

**Comment by xiak** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
@afc163  用的 iPhone x 试试

**Comment by xiak** [comment]
Iphone 7也有同样的问题

**Comment by xiak** [comment]
这个问题和#765有点像，一直按着，菜单就有可能出现

**Comment by chenshuai2144** [comment]
试着删除一下 fastclikc

**Comment by xiak** [comment]
删除了fastclick就可以了

**Comment by xiaohuoni** [comment]
横屏下可以弹出

**Comment by neil-mao** [comment]
代码里写是 hover方式打开 下拉菜单，改成 click，就可以了，也不用删除fastClick
 <Dropdown overlay={menu} trigger={['click']}>  <!--------之前是hover
