### ISSUE TITLE
🧐[问题]执行 npx create-umi myapp 为啥不是umi4?

### ISSUE THREAD

**Issue by maqinghao** [ant-design/ant-design-pro#9940]
### 🧐 问题描述
执行 npx create-umi myapp 

大家都是umi4
### 🚑 其他信息

<img width="610" alt="截屏2022-06-23 00 30 08" src="https://user-images.githubusercontent.com/57055415/175088458-e1df6bb4-21f6-43f2-93da-fc9042eeb101.png">

应该是下边的才对,是有缓存吗?还是?
<img width="624" alt="截屏2022-06-23 00 35 20" src="https://user-images.githubusercontent.com/57055415/175089901-f3cbb1be-10f5-4ee4-9a36-7390494d5f40.png">

**Comment by gsgs-libin** [comment]
使用如下命令来创建老的项目：
1.yarn create umi@0.27.0 umi3-app
#上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
2.yarn add create-umi@0.27.0
3.create-umi.cmd myapp2

**Comment by maqinghao** [comment]
> 使用如下命令来创建老的项目： 1.yarn create umi@0.27.0 umi3-app #上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下） 2.yarn add create-umi@0.27.0 3.create-umi.cmd myapp2

我不是要装老的项目,我是想装新的项目,使用umi/max

**Comment by chenshuai2144** [comment]
look  https://github.com/ant-design/ant-design-pro/issues/9958
