### ISSUE TITLE
🧐[问题] 执行 yarn run start 后一直卡在Starting the development server...

### ISSUE THREAD

**Issue by xuxuMaster** [ant-design/ant-design-pro#9941]
### 🧐 问题描述

老旧项目迁移后执行 yarn run start 命令后卡住

### 🚑 其他信息

yarn run v1.22.17
$ cross-env UMI_ENV=dev umi dev
Bundle with webpack 5...
Starting the development server...

√ Webpack

**Comment by chenshuai2144** [comment]
建议搞个新项目，然后copy老项目的代码。

**Comment by xuxuMaster** [comment]
> 建议搞个新项目，然后copy老项目的代码。

我确实拉的新项目，然后copy的呀 (╯°Д°)╯︵ ┻━┻

**Comment by xuxuMaster** [comment]
已解决，我推测是因为一次性迁移太多文件，出现错误太多导致mfsu缓存过大？导致没有打印任何错误信息。总之关闭mfsu功能根据错误提示更改后再开启mfsu就可以了。
