### ISSUE TITLE
🙇 如何创建旧版本的项目？

### ISSUE THREAD

**Issue by likaiji** [ant-design/ant-design-pro#9943]
通过yarn create umi myapp新建的项目，步骤与文档不符，没有选择antd 的模板这步，直接是simple基础模板，是还在优化中吗
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/24820280/175225495-86fdac7c-96e5-41d5-bfce-afabd6fca882.png">

**Comment by gsgs-libin** [comment]
使用如下命令来创建老的项目：
1.yarn create umi@0.27.0 umi3-app
#上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
2.yarn add create-umi@0.27.0
3.create-umi.cmd myapp2

**Comment by chenshuai2144** [comment]
## 使用 ant design pro cli 来生成

`npm I @ant-design/pro-cli -g`

然后使用  `pro create demo`

<img width="532" alt="image" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">


选择umi@4 暂时不能使用全部区块

<img width="822" alt="image" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">


查看 demo 文件夹即可。


## 使用全量的block

选择 umi@3 和 complete

<img width="809" alt="image" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

**Comment by hanf1990** [comment]
pro什么时候能跟新？

**Comment by chenshuai2144** [comment]
会和antd@5一起发布正式版本，大概8月份

**Comment by 666-arch** [comment]
> ## 使用 ant design pro cli 来生成
> `npm I @ant-design/pro-cli -g`
> 
> 然后使用 `pro create demo`
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">
> 
> 选择umi@4 暂时不能使用全部区块
> 
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">
> 
> 查看 demo 文件夹即可。
> 
> ## 使用全量的block
> 选择 umi@3 和 complete
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

这是默认安装的v5版本吧，我需要v4的？之前的命令全对不上，官方都没人维护的么？也没特殊通知？太不专业了吧

**Comment by doYbest** [comment]
使用旧版本可以创建js的项目吗？

**Comment by Gzbox** [comment]
> 会和antd@5一起发布正式版本，大概8月份

期待，具体时间确定了吗？

**Comment by kkh666** [comment]
> create-umi.cmd myapp2 请问这个命令提示不存在是咋回事呀

**Comment by Dnzzk2** [comment]
> 使用如下命令来创建老的项目：
> 
> 1. yarn create umi@0.27.1 umi3-app
> 
> > 上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
> 
> 2. yarn add create-umi@0.27.1
> 3. create-umi.cmd myapp2

有没有更细的教程，我这运行了，cmd，没有其他目录。

**Comment by iamzhangxin** [comment]
现在按照文档生成出来的东西全是报错，根本没法用

**Comment by 764213522** [comment]
> > ## 使用蚂蚁设计pro cli 来生成> > `npm I @ant-design/pro-cli -g`> > 然后使用`pro create demo`> > <img alt="image" width="532" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">> > 选择umi@4 暂时不能使用全部区块> > <img alt="image" width="822" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">> > 查看演示文件夹即可。> > ## 使用全量的block> > 选择umi@3和完整> > <img alt="image" width="809" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">>> 这是默认安装的v5版本吧，我需要v4的？之前的命令全对不上，官方都没人维护的么？也没特别通知？太不专业了吧钨

> ## 使用 ant design pro cli 来生成
> `npm I @ant-design/pro-cli -g`
> 
> 然后使用 `pro create demo`
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">
> 
> 选择umi@4 暂时不能使用全部区块
> 
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">
> 
> 查看 demo 文件夹即可。
> 
> ## 使用全量的block
> 选择 umi@3 和 complete
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

为什么我这里连选择umi@3 、4的这一步都没有

**Comment by 764213522** [comment]
我这里都没的选择umi@3 umi@4

**Comment by echoyl** [comment]
> 会和antd@5一起发布正式版本，大概8月份

大佬 v6 还出吗？ 是等antd@6出了再出吗🧐

**Comment by robeterlk** [comment]
> > 使用如下命令来创建老的项目：
> > 
> > 1. yarn create umi@0.27.1 umi3-app
> > 
> > > 上面这个会报错命令不存在，然后运行这两行就可以了（cmd路径改一下）
> > 
> > 
> > 
> > 2. yarn add create-umi@0.27.1
> > 3. create-umi.cmd myapp2
> 
> 有没有更细的教程，我这运行了，cmd，没有其他目录。

请问你的问题解决了么，能分享下如何修改cmd路径么

**Comment by robeterlk** [comment]
> ## 使用 ant design pro cli 来生成
> `npm I @ant-design/pro-cli -g`
> 
> 然后使用 `pro create demo`
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">
> 
> 选择umi@4 暂时不能使用全部区块
> 
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">
> 
> 查看 demo 文件夹即可。
> 
> ## 使用全量的block
> 选择 umi@3 和 complete
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

管理员窗口中在项目下进行第一步后，第二步输入pro create demo 说不是内部或外部命令请问该如何解决 @chenshuai2144

**Comment by mindsfsdfwe** [comment]
请问下，这个项目还继续维护吗？？ V6还出正式版吗？
