### ISSUE TITLE
🧐[问题]请问如何在request拦截器中取消请求

### ISSUE THREAD

**Issue by tanglonghai** [ant-design/ant-design-pro#9949]
### 🧐 问题描述

想在拦截器中调用接口，判断是否登录，如未登录就取消request请求，请问有方法实现吗？

### 💻 示例代码
const requestInterceptor = async (url: string, options: RequestOptionsInit) => {
    const resp = await getAccessInfo();
    if (resp.code == 403) {
        // cancal request
        // go to login
    }
}

**Comment by Tzng** [comment]
看这个：https://blog.csdn.net/cmdfas/article/details/120454770#:~:text=fetch%20%E5%9C%A8fetch%E8%AF%B7%E6%B1%82%E4%B8%AD%EF%BC%8C%E9%9C%80%E8%A6%81%E4%BD%BF%E7%94%A8%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%96%B0%E7%9A%84%20AbortController%20%E5%AF%B9%E8%B1%A1%EF%BC%8C%E6%9D%A5%E5%8F%96%E6%B6%88%E8%AF%B7%E6%B1%82%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%AF%B9%E8%B1%A1%E4%B8%AD%E6%9C%89%E4%B8%80%E4%B8%AA%20signal%20%E5%B1%9E%E6%80%A7%EF%BC%8C%E5%B0%86,signal%20%E4%BC%A0%E5%85%A5fetch%E8%AF%B7%E6%B1%82%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%AD%EF%BC%8C%E7%84%B6%E5%90%8E%E6%88%91%E4%BB%AC%E4%BD%BF%E7%94%A8%20AbortController%20%E7%9A%84%20abort%20%E6%96%B9%E6%B3%95%E5%8F%AF%E5%8F%96%E6%B6%88%E6%AD%A4%E6%AC%A1%E8%AF%B7%E6%B1%82%E3%80%82
