### ISSUE TITLE
ie浏览器下运行ant-design-pro项目，添加了polyfill，还是白屏，

### ISSUE THREAD

**Issue by zerocsss** [ant-design/ant-design-pro#995]
白屏浏览器：360，qq浏览器ie兼容模式，ie浏览器，
Chrome,Firefox,Edge没有问题

**Comment by yutingzhao1991** [comment]
![image](https://user-images.githubusercontent.com/1061968/36773292-e1f8b4cc-1c93-11e8-9780-2f3e8a416116.png)

@zerocsss IE 11 是 好的，IE 9 白屏。360，qq浏览器ie兼容模式应该都是用的 IE 内核，你那里 IE 是什么版本。 

可以参考下 antd 的兼容性： https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7

@chenshuai2144  antd pro 支持 IE9 吗？

**Comment by zerocsss** [comment]
@yutingzhao1991 ok了，线上版本的就可以了，在本地测用ie打开不行

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design-pro/issues/210

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design/pull/9444
