### ISSUE TITLE
🧐[问题]打包命令需要区分测试和线上环境吗

### ISSUE THREAD

**Issue by xiahller** [ant-design/ant-design-pro#9951]
### 🧐 问题描述

antd pro v5 react ts打包的时候，需要区分开发 测试 线上吗 还是直接用默认的build

### 💻 示例代码

/

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/55370123/175475978-9b3397ed-17c0-49a1-a2ec-954335fe8eb8.png)

**Comment by chenshuai2144** [comment]
环境只能修改代理的地址，代理编译之后就无效了。 线上的环境都是靠容器决定的。理论上每个环境都一样。

**Comment by IOLOII** [comment]
https://github.com/ant-design/ant-design-pro/issues/10239#issuecomment-1861232884
