### ISSUE TITLE
🧐[问题]Input 右侧有黑色的x

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design-pro#9952]
### 🧐 问题描述

下载ant design pro5代码，运行后，Input框出现样式问题，截图所示

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/33221294/175514500-ff084d09-f50c-4d6c-bda5-94c15b586ef9.png)

**Comment by chenshuai2144** [comment]
试试删除一下依赖，应该是ant design icons 这个包版本出现了问题

**Comment by wooxyz** [comment]
之前用的是ant design pro5.0.0，对应的ant-design/icons@4.5.0，没问题。现在用的是ant design pro5.2.0（提供的ant-design/icons@4.7.0），降到4.5.0都不行。我要降到哪个版本？

**Comment by chenshuai2144** [comment]
要升级到最新版本吧。 看看npm
https://www.npmjs.com/package/@ant-design/icons
