### ISSUE TITLE
ProLayout menu.request在login页面就被调用，导致endpoint无token🐛[BUG]

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design-pro#9955]
### 🐛 bug 描述

menu.request函数过早被调用，导致token还未获取。正常应该在login以后再调用。

### 📷 复现步骤

1. 退出登录
2. 刷新页面
3. 重新登录
4. menu.request获取失败

### 🏞 期望结果

menu.request在主界面被渲染时才被调用，或者提供额外的函数来完成这个任务。

### 💻 复现代码

```ts
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    ...
    menu: {
      // 当login页面被渲染时，这个函数就被调用了
      // 导致还没获取到token, API返回401 unauthorized
      request: async (_, defaultMenus) => {
        console.log('request menu');
        const menus = await fetchMyMenus();
        if (menus.length === 0) {
          return defaultMenus;
        }
        return [...menus, ...defaultMenus];
      },
...
    },
```

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
这个它不支持在不在loading，你用pathname 判断一下吧。

```ts
export const layout: RunTimeLayoutConfig = ({ initialState }) => {
const pathName = document.location.pathname;
  return {
    rightContentRender: () => <RightContent />,
    ...
    menu: {
      params:{ pathName },
      // 当login页面被渲染时，这个函数就被调用了
      // 导致还没获取到token, API返回401 unauthorized
      request: async (params, defaultMenus) => {
        if(params.pathName==="login") return 
        console.log('request menu');
        const menus = await fetchMyMenus();
        if (menus.length === 0) {
          return defaultMenus;
        }
        return [...menus, ...defaultMenus];
      },
...
    },
```

**Comment by kennylbj** [comment]
@chenshuai2144 测试了一下这样还是不行，首先params是个空对象，无法判断path；其次request只会被调用一次，如果我登出了，刷新了Login页面，request就被调用了，而后登录后，它并不会再被调用，这样`fetchMyMenus`仍然得不到token。

我觉得需要提供一个requstAfterLogin这样函数。

**Comment by chenshuai2144** [comment]
```
params={{
 pathname:""
}}
```

你手动注入一下，我不知道你什么时候 login 的

**Comment by kennylbj** [comment]
> 我不知道你什么时候 login 的

这里的问题就在于request函数会在login页面被刷新时候就调用，即login页面被渲染，但是用户还没点击登陆时候就被调用了，这时候的问题是： 未登陆往往导致无token, 进而导致request中的fetchMenus失败。

希望layout能提供一个requstAfterLogin，保证它在login页面点击登陆后再被调用。 @chenshuai2144 @afc163

**Comment by kennylbj** [comment]
通过注入userId解决问题。

[menu params](https://pro.ant.design/zh-CN/docs/advanced-menu#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AF%B7%E6%B1%82%E8%8F%9C%E5%8D%95)

```js
params: {
        userId: initialState?.currentUser?.id,
      },
```
