### ISSUE TITLE
🚀 升级到 umi@4

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro#9958]
## 升级到 umi@4 

安装 `yarn add  @umijs/max`

同时删除以下的依赖

```
"@umijs/plugin-blocks": "^2.2.0",
"@umijs/plugin-esbuild": "^1.4.0",
"@umijs/plugin-openapi": "^1.3.0",
"@umijs/preset-ant-design-pro": "^1.3.0",
"@umijs/preset-dumi": "^1.1.0",
"@umijs/preset-react": "^2.1.0",
```

修改   `"postinstall": "max setup",`

删除  `config/config.dev.ts`

修改 `fastRefresh: true`

删除 dva 的配置

```
dva: {
    hmr: true,
  },
```
删除  config 中 `dynamicImport, esbuild, openAPI, nodeModulesTransform, exportStatic` 的配置。

使用 max 命令来替换 umi，`max dev，max build` 等。

```
umi dev -> max dev
umi build -> max build
umi openapi -> max openapi
```

将  `from 'umi'; ` 修改为 `from '@umijs/max';`，详细这个diff

https://github.com/ant-design/ant-design-pro/pull/9956/files#diff-4f15e8cec0638e78138fbc4f2096e379a024084d76329b5b50bef0eccf1aee3e

删除 `lint:style` ，stylelint 需要的越来越少了

## 删除的功能

* 区块功能
* 删除对 IE 的支持，如果对 IE 有需求，请使用旧版本，（react，antd 都将不支持的 ie11）

## 新建 umi@4 或 umi@3 项目

`npm i @ant-design/pro-cli -g`

然后使用  `pro create demo`

<img width="532" alt="image" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">

选择umi@4 暂时不能使用全部区块

<img width="822" alt="image" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">

查看 demo 文件夹即可。

## 使用全量的block

选择 umi@3 和 complete

<img width="809" alt="image" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

**Comment by gaspire** [comment]
yarn create umi myapp

**Comment by chenshuai2144** [comment]
## 使用 ant design pro cli 来生成

`npm I @ant-design/pro-cli -g`

然后使用  `pro create demo`

<img width="532" alt="image" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">


选择umi@4 暂时不能使用全部区块

<img width="822" alt="image" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">


查看 demo 文件夹即可。


## 使用全量的block

选择 umi@3 和 complete

<img width="809" alt="image" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

**Comment by see** [comment]
为啥ant design pro要绑定自己的umi框架，我觉得应该舍弃掉?

**Comment by DreamPWJ** [comment]
umi确实是毒瘤，各种问题

> 为啥ant design pro要绑定自己的umi框架，我觉得应该舍弃掉?

**Comment by HalcyonDaysssss** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/24239032/175888516-c6541e1d-be10-40b3-ba54-ad0e6512a784.png">
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/24239032/175888555-d245e782-9be1-416f-9128-9e1dae891653.png">
没跑起来。。。。

**Comment by edifangyi** [comment]
> <img alt="image" width="1124" src="https://user-images.githubusercontent.com/24239032/175888516-c6541e1d-be10-40b3-ba54-ad0e6512a784.png">
> 
> <img alt="image" width="1375" src="https://user-images.githubusercontent.com/24239032/175888555-d245e782-9be1-416f-9128-9e1dae891653.png">
> 
> 没跑起来。。。。

我也是~~

**Comment by HalcyonDaysssss** [comment]
> > <img alt="image" width="1124" src="https://user-images.githubusercontent.com/24239032/175888516-c6541e1d-be10-40b3-ba54-ad0e6512a784.png">
> > <img alt="image" width="1375" src="https://user-images.githubusercontent.com/24239032/175888555-d245e782-9be1-416f-9128-9e1dae891653.png">
> > 没跑起来。。。。
> 
> 我也是~~

我好像知道了,npm install swagger-ui-react

**Comment by xingming2020** [comment]
![image](https://user-images.githubusercontent.com/67719106/176106510-128311ca-63f4-4065-8d6b-206325cc5cda.png)
[请求-API-RequestConfig](https://umijs.org/docs/max/request#requestconfig)

**Comment by lazyhero** [comment]
是被[umijs](https://umijs.org/)接管了吗？看v4、v5文档 生成的脚手架都是@umijs/max的……

**Comment by chenshuai2144** [comment]
pro 是 umijs 和 ant design 的组合。

**Comment by see** [comment]
阿里的项目都是强行绑定自己公司的产品，向用户推出。

**Comment by chenshuai2144** [comment]
尽量不要用js，我们这里已经没有 js 项目了，出了问题没办法保证支持。

**Comment by blueiky** [comment]
windows安装了 `@ant-design/pro-cli`之后，没办法创建项目
![image](https://user-images.githubusercontent.com/51806785/176814759-60c2d459-ec02-4889-8fdd-7f0e78555d90.png)
没有任何反应

**Comment by chenshuai2144** [comment]
@[blueiky](https://github.com/blueiky) 注意下版本？

**Comment by blueiky** [comment]
测试了一下，npm使用taobao的源安装 `@ant-design/pro-cli`可以正常使用，使用默认的源就不行

**Comment by chenzheio** [comment]
用最新的cli选择umi4生成的项目，在手机端打开页面因为宽度不够直接不显示菜单了，该怎么处理呢？

**Comment by iscmcloud** [comment]
@chenshuai2144 
1）Antd Pro V5 原来的Layout，深色导航菜单模式是否可以保留
2）左侧 Sider Collapsed Button这个圆形的折叠按钮，位置能否可选，现在在右边，不需要面包屑的页面，会遮挡页面内容

**Comment by chenshuai2144** [comment]
开个新issue 聊设计问题

**Comment by geyitu** [comment]
按文档升级后，报错Unhandled Rejection (Error): register failed, invalid key getInitialState from plugin

**Comment by 666-arch** [comment]
> 为啥ant design pro要绑定自己的umi框架，我觉得应该舍弃掉?

版本迭代对不怎么使用typescript的人来说太不友好了

**Comment by skyunBoss** [comment]
max openapi报错
![image](https://user-images.githubusercontent.com/29365288/178131708-df5ca050-92bf-4daa-a2a5-5795b4ad7304.png)

**Comment by chenshuai2144** [comment]
```
 //================ pro 插件配置 =================
  presets: ['umi-presets-pro'],
  /**
   * @name openAPI 插件的配置
   * @description 基于 openapi 的规范生成serve 和mock，能减少很多样板代码
   * @doc https://pro.ant.design/zh-cn/docs/openapi/
   */
  openAPI: [
    {
      requestLibPath: "import { request } from '@umijs/max'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from '@umijs/max'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
```

**Comment by await-ovo** [comment]
真的好难升级呀:
1. 要改代码不说，router 没法用 v5, 鬼知道之前代码里面有没有啥不兼容的用法，
2. 之前的 defaultSettings 啥的也不生效了，layout 也要改成 pro-components 了，页面样式啥的也都和之前一样
3. app.tsx 里面 initialStateConfig 不生效了，怎么加 PageLoading 咱也不知道，升级文档也没有 
4. webpack bundler 的时候，CLI 里面倒是秒级启动，浏览器页面整个进度的界面一直挂着估计得有5min，掩耳盗铃？

纯纯无语，真就喂着吃 💩 呀

**Comment by see** [comment]
难用就用其他的啊，或者收费的，推荐一款[ant-design-vue](https://store.antdv.com/items/admin-pro)。我就不用阿里的开源，一身轻松，哈哈哈哈

**Comment by skyunBoss** [comment]
layout设置mix，headerBgColor设置无效

**Comment by tangbzai** [comment]
> 按文档升级后，报错Unhandled Rejection (Error): register failed, invalid key getInitialState from plugin 看.umi文件中，没有plugin-initialState这个插件

我也出现了这个问题，后面发现需要在 `config.ts` 文件里配置 `initialState: {}`
建议检查一下自己的 `config.ts` 与 [官方 diff 的 config.ts](https://github.com/ant-design/ant-design-pro/pull/9956/files#diff-81e45c8f93c956ca5d965b73760e8e9ee75a86dbcab27b4b4d46c90d6b2c81b2) 的差异

**Comment by chb584890926** [comment]
现在还能downjs版本的吗

**Comment by zhanchengkun** [comment]
app.tsx 中拿不到 node 的自定义环境变量呢。pages/页面  可以拿到。

**Comment by soqt** [comment]
开启ssr后会显示less文件无法解析

**Comment by HdjPoppy** [comment]
> pro 是 umijs 和 ant design 的组合。
升级后路由咋搞呢

**Comment by HdjPoppy** [comment]
> ## 升级到 umi@4
> 
> 安装 `yarn add @umijs/max`
> 
> 同时删除以下的依赖
> 
> ```
> "@umijs/plugin-blocks": "^2.2.0",
> "@umijs/plugin-esbuild": "^1.4.0",
> "@umijs/plugin-openapi": "^1.3.0",
> "@umijs/preset-ant-design-pro": "^1.3.0",
> "@umijs/preset-dumi": "^1.1.0",
> "@umijs/preset-react": "^2.1.0",
> ```
> 
> 修改 `"postinstall": "max setup",`
> 
> 删除 `config/config.dev.ts`
> 
> 修改 `fastRefresh: true`
> 
> 删除 dva 的配置
> 
> ```
> dva: {
>     hmr: true,
>   },
> ```
> 
> 删除 config 中 `dynamicImport, esbuild, openAPI, nodeModulesTransform, exportStatic` 的配置。
> 
> 使用 max 命令来替换 umi，`max dev，max build` 等。
> 
> ```
> umi dev -> max dev
> umi build -> max build
> umi openapi -> max openapi
> ```
> 
> 将 `from 'umi'; ` 修改为 `from '@umijs/max';`，详细这个diff
> 
> https://github.com/ant-design/ant-design-pro/pull/9956/files#diff-4f15e8cec0638e78138fbc4f2096e379a024084d76329b5b50bef0eccf1aee3e
> 
> 删除 `lint:style` ，stylelint 需要的越来越少了
> ## 删除的功能
> 
>     * 区块功能
> 
>     * 删除对 IE 的支持，如果对 IE 有需求，请使用旧版本，（react，antd 都将不支持的 ie11）
> 
> 
> ## 新建 umi@4 或 umi@3 项目
> 
> `npm i @ant-design/pro-cli -g`
> 
> 然后使用 `pro create demo`
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/8186664/175860409-cc90ce03-480c-4df1-a259-4be8e00522de.png">
> 
> 选择umi@4 暂时不能使用全部区块
> 
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/8186664/175860472-b0b4afb2-fac6-492f-a5ff-39753cc35455.png">
> 
> 查看 demo 文件夹即可。
> ## 使用全量的block
> 
> 选择 umi@3 和 complete
> 
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/8186664/175860552-64bb02ac-b65b-471a-8749-f928d87a01dc.png">

升级umi4后路由凉凉了呀

**Comment by HebeHealer** [comment]
* 区块功能

* 删除对 IE 的支持，如果对 IE 有需求，请使用旧版本，（react，antd 都将不支持的 ie11） 

不支持iE了么? 这么坑

**Comment by minm2015** [comment]
新版本把默认菜单的样式丢了？以前默认的活动菜单蓝色没了
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/19508192/182068266-cc328ca0-1f32-42f1-9ca4-8ed11f7816e7.png">

**Comment by chenliangngng** [comment]
> 新版本把默认菜单的样式丢了？以前默认的活动菜单蓝色没了 <img alt="image" width="1186" src="https://user-images.githubusercontent.com/19508192/182068266-cc328ca0-1f32-42f1-9ca4-8ed11f7816e7.png">

貌似是pro-layout后面几个版本就把样式重写了，我现在用的是"@ant-design/pro-layout": "^6.34.0",可以用以前的样式@minm2015

**Comment by 775146061** [comment]
大佬，umi4里删除了openapi，现在怎么集成进去啊

**Comment by chenliangngng** [comment]
> 大佬，umi4里删除了openapi，现在怎么集成进去啊

```
  plugins: ['@umijs/max-plugin-openapi'],
  openAPI: {
    requestLibPath: "import { request } from '@umijs/max'",
    schemaPath: resolve(__dirname, './openapi.json'),
    mock: false,
  },
```

我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061

**Comment by 775146061** [comment]
> > 大佬，umi4里删除了openapi，现在怎么集成进去啊
> 
> ```
>   plugins: ['@umijs/max-plugin-openapi'],
>   openAPI: {
>     requestLibPath: "import { request } from '@umijs/max'",
>     schemaPath: resolve(__dirname, './openapi.json'),
>     mock: false,
>   },
> ```
> 
> 我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061

感谢感谢大佬🙏！可以问下具体是什么问题吗？我配置成功了，暂时还没发现问题

**Comment by chenliangngng** [comment]
> > > 大佬，umi4里删除了openapi，现在怎么集成进去啊
> > 
> > 
> > ```
> >   plugins: ['@umijs/max-plugin-openapi'],
> >   openAPI: {
> >     requestLibPath: "import { request } from '@umijs/max'",
> >     schemaPath: resolve(__dirname, './openapi.json'),
> >     mock: false,
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061
> 
> 感谢感谢大佬🙏！可以问下具体是什么问题吗？我配置成功了，暂时还没发现问题

我这边配了openapi项目跑不起来，要跑起来就要把openapi的配置删掉，不知道是我一个人的问题

**Comment by 775146061** [comment]
> > > > 大佬，umi4里删除了openapi，现在怎么集成进去啊
> > > 
> > > 
> > > ```
> > >   plugins: ['@umijs/max-plugin-openapi'],
> > >   openAPI: {
> > >     requestLibPath: "import { request } from '@umijs/max'",
> > >     schemaPath: resolve(__dirname, './openapi.json'),
> > >     mock: false,
> > >   },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061
> > 
> > 
> > 感谢感谢大佬🙏！可以问下具体是什么问题吗？我配置成功了，暂时还没发现问题
> 
> 我这边配了openapi项目跑不起来，要跑起来就要把openapi的配置删掉，不知道是我一个人的问题

我是这个版本的"@umijs/max-plugin-openapi": "^1.0.5"，会不会是已经修复了

**Comment by 775146061** [comment]
> > > > 大佬，umi4里删除了openapi，现在怎么集成进去啊
> > > 
> > > 
> > > ```
> > >   plugins: ['@umijs/max-plugin-openapi'],
> > >   openAPI: {
> > >     requestLibPath: "import { request } from '@umijs/max'",
> > >     schemaPath: resolve(__dirname, './openapi.json'),
> > >     mock: false,
> > >   },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061
> > 
> > 
> > 感谢感谢大佬🙏！可以问下具体是什么问题吗？我配置成功了，暂时还没发现问题
> 
> 我这边配了openapi项目跑不起来，要跑起来就要把openapi的配置删掉，不知道是我一个人的问题

确实是启动报错😂

**Comment by tonny008** [comment]
> 
用pro create的umi4项目里config还是有
  targets: {
    ie: 11,
  },
然后又不支持IE11

**Comment by CookyG** [comment]
max openapi 跑起来报错

**Comment by 775146061** [comment]
> > > > 大佬，umi4里删除了openapi，现在怎么集成进去啊
> > > 
> > > 
> > > ```
> > >   plugins: ['@umijs/max-plugin-openapi'],
> > >   openAPI: {
> > >     requestLibPath: "import { request } from '@umijs/max'",
> > >     schemaPath: resolve(__dirname, './openapi.json'),
> > >     mock: false,
> > >   },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061
> > 
> > 
> > 感谢感谢大佬🙏！可以问下具体是什么问题吗？我配置成功了，暂时还没发现问题
> 
> 我这边配了openapi项目跑不起来，要跑起来就要把openapi的配置删掉，不知道是我一个人的问题

大佬，安装这个依赖包`pnpm i -D swagger-ui-dist`，然后启动就没问题了

**Comment by CookyG** [comment]
> > > > > 大佬，umi4里删除了openapi，现在怎么集成进去啊
> > > > 
> > > > 
> > > > ```
> > > >   plugins: ['@umijs/max-plugin-openapi'],
> > > >   openAPI: {
> > > >     requestLibPath: "import { request } from '@umijs/max'",
> > > >     schemaPath: resolve(__dirname, './openapi.json'),
> > > >     mock: false,
> > > >   },
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我是这样配置的，就可以用了。不过这样配置有问题，跑项目的时候要删掉那些@775146061
> > > 
> > > 
> > > 感谢感谢大佬🙏！可以问下具体是什么问题吗？我配置成功了，暂时还没发现问题
> > 
> > 
> > 我这边配了openapi项目跑不起来，要跑起来就要把openapi的配置删掉，不知道是我一个人的问题
> 
> 大佬，安装这个依赖包`pnpm i -D swagger-ui-dist`，然后启动就没问题了

<img width="631" alt="image" src="https://user-images.githubusercontent.com/20312873/183030419-d84dec64-6133-4aff-b673-a3c51ec1d984.png">
我觉得可以先这样解决

**Comment by darkfiredarkhalo** [comment]
新版给人的感觉:  版本迭代没做好就放出来了

**Comment by xiaoguikeji** [comment]
升级以后凉凉，ui只有白色，不好看了，适配也没做好，看来只能先用umi3了，公司新招了设计总监需要三把火吗

**Comment by kkh666** [comment]
@chenshuai2144  大佬 请问按照现在的官方文档引入antd pro 直接这样报错是为什么呀 [我看下载的源是gitee不是GitHub]
![image](https://user-images.githubusercontent.com/95608029/184573149-af1f634f-6ecd-4a4a-af85-feb973fbb62a.png)

**Comment by codering** [comment]
这个适配进度有点慢啊。我理解开源维护不易，但这都过了一个多月了，看问题还是很多，就感觉我不如回到直接用antd自己维护一套的好，pro-components 我觉得也应该少用 :(

**Comment by dreamerjdwGit** [comment]
![image](https://user-images.githubusercontent.com/20147593/185285104-f26a964d-ea97-4826-ab7d-5e5feb561919.png)

useModel怎么都在umi中找不到，最新版本和上面例子版本，都没有，求助。

**Comment by chenliangngng** [comment]
显式申明，umi4文档上有@dreamerjdwGit

**Comment by wushizhan** [comment]
升级后 config.ts antd: { compact: true, }, 设置紧凑模式无效

**Comment by yuandalu** [comment]
从v5 beta开始用，一直跟着升级到了5.2，此次跟着升级到了6beta，升级过程花了点时间，但是都没问题，项目开发内容也不少了，我觉得升级兼容性还好，layout确实不好兼容，直接单独引入了，也就是没有使用layout的7.0版本，等稳定了再改回来，大家细心点，多看看文档，不行拉个新项目，自己一点点对比，我每次升级都这样处理，我现在都能背下来项目都有啥文件了，

**Comment by lbyupup** [comment]
> ![image](https://user-images.githubusercontent.com/20147593/185285104-f26a964d-ea97-4826-ab7d-5e5feb561919.png)
> 
> useModel怎么都在umi中找不到，最新版本和上面例子版本，都没有，求助。

俺也一样

**Comment by DylanAlloy** [comment]
umi is destroying this project. It will not be used by anyone in 1 year.

**Comment by icecreamzhao** [comment]
> > ![image](https://user-images.githubusercontent.com/20147593/185285104-f26a964d-ea97-4826-ab7d-5e5feb561919.png)
> > useModel怎么都在umi中找不到，最新版本和上面例子版本，都没有，求助。
> 
> 俺也一样

同

**Comment by YaoHuangMark** [comment]
升级升麻了，目前找不到，Prompt，dynamic

**Comment by YaoHuangMark** [comment]
有没有升级通关秘籍呀

**Comment by zeyujay** [comment]
> 

exportStatic删除了，路由怎么处理的？history打包之后发服务器，刷新一下，页面就404了。用hash子目录不能访问，根目录可以访问

**Comment by chenshuai2144** [comment]
exportStatic 会搞一个新的api出来的，去umi 官方蹲一下

**Comment by saltdg** [comment]
v6正式版什么时候发呀

**Comment by tpc-ht** [comment]
![image](https://user-images.githubusercontent.com/59469126/195303843-17bea4b9-7c03-4d7b-af8b-05fb5e55acbb.png)
这个问题有遇到吗？

**Comment by tpc-ht** [comment]
![image](https://user-images.githubusercontent.com/59469126/195306015-756060e6-fe51-4f3a-9390-463c218318a6.png)
yarn 自动执行 max generate tmp 。保存是什么情况

**Comment by lbyupup** [comment]
> ![image](https://user-images.githubusercontent.com/59469126/195306015-756060e6-fe51-4f3a-9390-463c218318a6.png)
> yarn 自动执行 max generate tmp 。保存是什么情况

https://umijs.org/docs/introduce/upgrade-to-umi-4#%E4%BE%9D%E8%B5%96%E5%A4%84%E7%90%86
可以看看这个配置，更改一下指令

**Comment by tpc-ht** [comment]
> > ![image](https://user-images.githubusercontent.com/59469126/195306015-756060e6-fe51-4f3a-9390-463c218318a6.png)
> > yarn 自动执行 max generate tmp 。保存是什么情况
> 
> https://umijs.org/docs/introduce/upgrade-to-umi-4#%E4%BE%9D%E8%B5%96%E5%A4%84%E7%90%86 可以看看这个配置，更改一下指令

感谢。这个配置改漏了

**Comment by webpon** [comment]
这东西真他吗是毒瘤

**Comment by wenjianzhang** [comment]
> 老项目umi2.8 antdpro 4.5.9 antd3.26.3，尝试了下升级后来放弃了，实在是升不上去，成本太大

一直跟着master升的话问题也不大

**Comment by dino9999** [comment]
真真一坨屎💩💩 umi kpi届毒瘤

**Comment by gitlwz** [comment]
> 

initialStateConfig 不生效怎么解决？

**Comment by gaohongwei** [comment]
我的umijs升级，花了很久时间也没成功。
感觉umijs应该淘汰掉。

把其中好的功能，例如。path alias, menu config 做成npm package.
其他的功能。例如，request, i18n没必要保留。

**Comment by kakuilan** [comment]
> > 老项目umi2.8 antdpro 4.5.9 antd3.26.3，尝试了下升级后来放弃了，实在是升不上去，成本太大
> 
> 一直跟着master升的话问题也不大
> 
> 已经部署， https://antd6.go-admin.pro/

你好，demo方便开源给我们参考下吗？

**Comment by hyzx86** [comment]
> 
> 版本迭代对不怎么使用typescript的人来说太不友好了

这个有点矛盾，版本迭代意味着要追新，
不怎么使用  ts 代表着守旧。。
为什么不去学下呢~~忒好用了

> > 为啥ant design pro要绑定自己的umi框架，我觉得应该舍弃掉?
非常赞同。。。！！

**Comment by hyzx86** [comment]
history.query  要从哪里拿啊？

**Comment by scepter0430** [comment]
最近搭建了尝试了一下。
1、initialStateConfig 不好用，但是文档没有更新这些对应的问题，这个很重要。
2、patchClientRoutes、getInitialState执行顺序或者说（动态配置菜单及路由）不友好，如果全部动态更改，那么会删掉咱们比较多的执行代码，反而不能优雅的使用了。
3、能来个tabbar吗。提了好几年了。

**Comment by hyzx86** [comment]
@scepter0430 
`patchClientRoutes`  还有这东西？？ 在哪里噢？

**Comment by hyzx86** [comment]
> 我的umijs升级，花了很久时间也没成功。感觉umijs应该淘汰掉。
> 
> 把其中好的功能，例如：path alias, menu config 做成npm package. 其他的功能,例如，request, i18n，useHistory， useModel没必要保留。
> 
> 早期使用umijs是想使用 menu config，path alias。 目前正试图把umijs 换为 create react app. 也不容易。 求建议。

直接把业务代码复制到新框架里不久行啦？
6.0正式版发布了，现在可以用了
我是直接把官方仓库克隆下来搞，然后连同所有提交带入到自己仓库，后续有更新直接同步下，有差异再Merge ，香喷喷

**Comment by hyzx86** [comment]
开发环境 无法使用子目录么？
6.0 版本 子目录发布要改哪些啊？

我从 5.x 搬过来的配置不管用了
``` ts
import { defineConfig } from '@umijs/max';
const publicPathPrefix = '/sea'
export default defineConfig({

    define: {
        // API地址
        API_BASE_URL: 'http://localhost:2919/SalesPortal',
        CLIENT_ROOT: 'http://localhost:1688',
        // OpenId 客户端名称
        CLIENT_ID: 'SalesPortal',
        SKIP_LOGIN_PAGE: false,
        LOGIN_PAGE: '/user/login',
        //启用语言切换
        DISABLE_LANGSELECT: false,
        PUBLIC_PATH: publicPathPrefix + '/'
    },
    base: publicPathPrefix + "/",
    outputPath: "dist" + publicPathPrefix,
    publicPath: publicPathPrefix + "/",
    manifest: {
        basePath: publicPathPrefix,
    },
    headScripts: [
        // 解决首次加载时白屏的问题
        //@ts-ignore
        { src: publicPathPrefix + '/scripts/loading.js', async: true },
    ] 
});

```

**Comment by scepter0430** [comment]
@hyzx86 umi4  文档  运行时配置里面。

**Comment by hyzx86** [comment]
https://github.com/umijs/umi/issues/10189
大佬说 runtime 不是在这种情况下用的。。

**Comment by scepter0430** [comment]
@hyzx86 你说动态菜单和动态路由配置？
![image](https://user-images.githubusercontent.com/63215136/210201141-839cdf0e-5c0f-4f8c-8a08-7a830145d8f6.png)

**Comment by hyzx86** [comment]
> @hyzx86 你说动态菜单和动态路由配置？ ![image](https://user-images.githubusercontent.com/63215136/210201141-839cdf0e-5c0f-4f8c-8a08-7a830145d8f6.png)

84，我说的是 子目录部署的问题，
主要是 history.location.pathname 的行为跟 旧版不一致了

**Comment by scepter0430** [comment]
@hyzx86 方便加个联系方式吗？请教几个问题。

**Comment by hyzx86** [comment]
> @hyzx86 方便加个联系方式吗？请教几个问题。

不是有个钉钉群么？

**Comment by tsingsun** [comment]
> > 老项目umi2.8 antdpro 4.5.9 antd3.26.3，尝试了下升级后来放弃了，实在是升不上去，成本太大
> 
> 一直跟着master升的话问题也不大
> 
> 已经部署， https://antd6.go-admin.pro/

这个项目有开源吗?

**Comment by jmy2022** [comment]
> 

解决了没

**Comment by mzvast** [comment]
解决了没

**Comment by cuijiudai** [comment]
less的报错了变量引用，import 都报错了

**Comment by gaohongwei** [comment]
花了几个星期，终于换掉了umijs.
跟大家分享一下。

用的是这些
vitejs, 解决path alias
Antd menu, 
Antd useRoutes
Antd Layout

**Comment by SolinMa** [comment]
> less报错了,变量引用、@import 都报错了

解决了吗

**Comment by hyzx86** [comment]
把config 里面 这个干掉实时？


  /**
   * ModifyVars
   */
  // lessLoader: {
  //   modifyVars: {
  //     hack: 'true; @import "~@/assets/styles/antdVars.less"'
  //   },
  //   javascriptEnabled: true
  // },

**Comment by zhu0629** [comment]
antd pro+vite

**Comment by mendellin** [comment]
antd v6 (umi4) 选择语言签名的图标如何不显示？ 谢谢
![image](https://github.com/ant-design/ant-design-pro/assets/5884945/15071d48-7431-4683-afaa-62196ff2eab3)

**Comment by chenshuai2144** [comment]
windows 就是这样的 mac 就显示了

**Comment by mendellin** [comment]
> 您好，选择语言的菜单，我需要它 不显示这个： US  ，CN，HK 或 不显示任何图标。
要如何实现呢？ 谢谢  @chenshuai2144
