### ISSUE TITLE
文档修正

### ISSUE THREAD

**Issue by ZhangTianCi** [ant-design/ant-design-pro#9959]
### Reproduction link

[https://pro.ant.design/zh-CN/config/config#history](https://pro.ant.design/zh-CN/config/config#history)

### Steps to reproduce

点击"history 类型和配置项"，链接错误。

### What is expected?

跳转到正确的链接地址

### What is actually happening?

跳转到了错误

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | * |
| System | * |
| Browser | * |

**Comment by ZhangTianCi** [comment]
我在这个仓库中没有找到"docs"的相关信息，文档是一个单独的开源项目吗？

如果是的话，项目地址是什么？

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro-site

这里

**Comment by tianyuan233** [comment]
https://github.com/ant-design/ant-design-pro-site/pull/631

@chenshuai2144

**Comment by chenshuai2144** [comment]
好样的
