### ISSUE TITLE
如何控制某个页面上链接的权限以及按钮的权限呢？

### ISSUE THREAD

**Issue by duoluzhu** [ant-design/ant-design-pro#996]
请问：
1，页面上有指向其他页面的链接，不同角色，有些可以访问这个页面有些不让访问这个页面，这个时候如何做权限控制呢？ 
2，页面上的按钮，也会根据用户角色来划分权限，这个时候又如何控制呢？

**Comment by chenshuai2144** [comment]
```
import RenderAuthorized from 'ant-design-pro/lib/Authorized';
import { Alert } from 'antd';

const Authorized = RenderAuthorized('user');
const noMatch = null;

ReactDOM.render(
  <div>
    <Authorized authority="admin" noMatch={noMatch}>
      <Alert message="user Passed!" type="success" showIcon />
    </Authorized>
  </div>,
  mountNode,
);
```

**Comment by duoluzhu** [comment]
@chenshuai2144   陈老师 您好，请问一下，这种是可以做统一的权限限制是吗？等于是写一个公共的组件，涉及权限验证的页面就去调用？ 新手，勿喷，谢谢

**Comment by chenshuai2144** [comment]
对，相当于权限不通过给一个空组件。

**Comment by Tommy-White** [comment]
@chenshuai2144 
请问authority是只能为admin和user吗？

**Comment by Jiangwr** [comment]
> noMatch = null 就可以了
> 
> ```
> import RenderAuthorized from 'ant-design-pro/lib/Authorized';
> import { Alert } from 'antd';
> 
> const Authorized = RenderAuthorized('user');
> const noMatch = null;
> 
> ReactDOM.render(
>   <div>
>     <Authorized authority="admin" noMatch={noMatch}>
>       <Alert message="user Passed!" type="success" showIcon />
>     </Authorized>
>   </div>,
>   mountNode,
> );
> ```

请教一下，imort这两个报错了，

![image](https://user-images.githubusercontent.com/19362571/53613811-38b56280-3c12-11e9-9063-8eae081fab5d.png)

提示我安装，但是我安装不上，
![image](https://user-images.githubusercontent.com/19362571/53613819-479c1500-3c12-11e9-81ac-56cf140ee662.png)
![image](https://user-images.githubusercontent.com/19362571/53613839-55519a80-3c12-11e9-8ddd-46710f2e9ef9.png)

**Comment by Jiangwr** [comment]
> > noMatch = null 就可以了
> > ```
> > import RenderAuthorized from 'ant-design-pro/lib/Authorized';
> > import { Alert } from 'antd';
> > 
> > const Authorized = RenderAuthorized('user');
> > const noMatch = null;
> > 
> > ReactDOM.render(
> >   <div>
> >     <Authorized authority="admin" noMatch={noMatch}>
> >       <Alert message="user Passed!" type="success" showIcon />
> >     </Authorized>
> >   </div>,
> >   mountNode,
> > );
> > ```
> 
> 请教一下，imort这两个报错了，
> 
> ![image](https://user-images.githubusercontent.com/19362571/53613811-38b56280-3c12-11e9-9063-8eae081fab5d.png)
> 
> 提示我安装，但是我安装不上，
> ![image](https://user-images.githubusercontent.com/19362571/53613819-479c1500-3c12-11e9-81ac-56cf140ee662.png)
> ![image](https://user-images.githubusercontent.com/19362571/53613839-55519a80-3c12-11e9-8ddd-46710f2e9ef9.png)

知道了，需要这样引入import RenderAuthorized from '@/components/Authorized';
