### ISSUE TITLE
更新protable组件版本时jekins构建时报错了🐛 [BUG]

### ISSUE THREAD

**Issue by lovehebe330** [ant-design/ant-design-pro#9961]
### 🐛 bug 描述

更新@ant-design/pro-table组件到@2.76.4版本时，本地运行没问题，jenkins构建时报错，提示有东西未安装。
如图所示:
![image](https://user-images.githubusercontent.com/20655248/176121377-5bcd4c8b-9ed6-4391-8ced-ab6aace14f86.png)
导致测试地址有的protable组件没法显示报这个错
![image](https://user-images.githubusercontent.com/20655248/176121732-327340ef-7132-428b-afa3-3e255add7414.png)
这个要如何解决
### © 版本信息

- Ant Design Pro 版本: [e.g. 5.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
你应该没找到核心问题。

 > 更新一下lock再来一下。

目测这个保措施代码引起的，可能和protable 也没有关系
