### ISSUE TITLE
🐛 [BUG]umi4版本开启lowImport报错

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/ant-design-pro#9964]
### 🐛 bug 描述

在config中启用lowImport: {},启动项目失败，错误提示如下

### 📷 复现步骤 | Recurrence steps

![微信截图_20220630091742](https://user-images.githubusercontent.com/76459860/176572208-d217c7b5-e3fe-4959-a4ef-8b14bdf41358.png)

因为没有找到文档，也有可能是我开启方式不正确？

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本 4.0.0-rc.22
- 浏览器环境 Edge
- 开发环境 Windows

**Comment by chenshuai2144** [comment]
这个还没完全搞好，先不要用。

不然就要自己解决问题了
