### ISSUE TITLE
现在新下下来的ant design pro怎么变成这个样子了

### ISSUE THREAD

**Issue by xyzabc0004** [ant-design/ant-design-pro#9965]
现在新下下来的ant design pro怎么变成这个样子了

![图片](https://user-images.githubusercontent.com/32530210/176576282-3b5137a1-e390-497c-b016-4d43a7b7a528.png)

**Comment by chenshuai2144** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/8186664/176580369-0947371c-da63-4e80-9935-507c61009cb4.png">


用这种方式吧

**Comment by chenshuai2144** [comment]
初始化
我们提供了 pro-cli 来快速的初始化脚手架。

# 使用 npm
npm i @ant-design/pro-cli -g
# 使用 yarn
pro create myapp
选择 umi 的版本

? 🐂 使用 umi@4 还是 umi@3 ? (Use arrow keys)
❯ umi@4
  umi@3
如果选择了 umi@4 版本，展示还不支持全量区块。

如果选择了 umi@3，还可以选择 pro 的模板，pro 是基础模板，只提供了框架运行的基本内容，complete 包含所有区块，不太适合当基础模板来进行二次开发

? 🚀 要全量的还是一个简单的脚手架? (Use arrow keys)
❯ simple
  complete
安装依赖：

$ cd myapp && tyarn
// 或
$ cd myapp && npm install

**Comment by xyzabc0004** [comment]
是不是 yarn pro create myapp
@chenshuai2144

**Comment by xyzabc0004** [comment]
![图片](https://user-images.githubusercontent.com/32530210/176583369-ee18b7ab-1a62-4140-8eb0-45f80329be60.png)
@chenshuai2144 
帅锅

**Comment by chenshuai2144** [comment]
看看有没有安装成功吧。
