### ISSUE TITLE
🧐[问题 | question]umi4版本在配置base和publicPath后，history.location和useLocation()返回的pathname不同

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/ant-design-pro#9968]
### 🧐 问题描述 | Problem description
umi4版本
在config中配置了base和publicPath
![image](https://user-images.githubusercontent.com/76459860/176608818-ef33cfa8-bc30-44ca-a76d-1e00127af091.png)
分别使用history.location和useLocation()获取patnname
history.location返回的是 /xmPortal/user/login (带了base)
useLocation()返回的是 /user/login
请问这是正常的吗？因为在app.tsx里有一些token校验并重定向的逻辑，而且这里是没法调用hooks，只能走history，这就导致重定向的路径里重复了一个base，跳转错误了
![image](https://user-images.githubusercontent.com/76459860/176611593-9e95e662-62d8-4063-bf47-1373007b3294.png)

### 💻 示例代码 | Sample code

![image](https://user-images.githubusercontent.com/76459860/176609483-4f003de9-1f63-48ae-8445-3eabfd5e52fe.png)
![image](https://user-images.githubusercontent.com/76459860/176609569-37839431-b4bf-4356-805c-84755347e382.png)

OS: Windows

Node：16+

浏览器 | browser：EDGE

**Comment by chenshuai2144** [comment]
base 会增加最前面，不用你手动设置的。建议以 react router 为准

**Comment by zhangheng0317** [comment]
> base 会增加最前面，不用你手动设置的。建议以 react router 为准
没太明白，我的项目不是部署在根目录的，不是得设置base吗？如果不设置base部署路径就不对了啊

**Comment by chenshuai2144** [comment]
对的 但是在react router中他不会把base 拼到pathname上去 和浏览器自带的就不一样了

**Comment by lecd** [comment]
> 对的 但是在react router中他不会把base 拼到pathname上去 和浏览器自带的就不一样了
请问在运行时不能用hooks，如何访问真实的地址？而不是加上base。

**Comment by lecd** [comment]
请问：在运行时不能用hooks，如何取到到真实的地址，而在history.location 是有加上base这样一级的？
