### ISSUE TITLE
🐛 [BUG] pro6 bate1，layout 指定使用 6.x 系列，页面可以展示，但是会出现请求类型为 test/html 的请求 ，并出现 404错误。

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design-pro#9969]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/30397655/176632154-8c8c31d6-a1a2-4189-b4a8-88f1fef0d1e8.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/30397655/176632008-4ab8c80c-8581-47cb-861d-cbf0e09bfcc2.png">

**Comment by chenshuai2144** [comment]
更详细一点？

**Comment by leshalv** [comment]
添加 "@ant-design/pro-layout": "^6.38.9" ，启动项目，登录成功，打开开发者模式，然后点击右侧菜单，就可复现。

**Comment by chenshuai2144** [comment]
按照描述来准备 demo

**Comment by echoyl** [comment]
楼主这个问题解决了吗？我也碰到这个错误了

**Comment by leshalv** [comment]
没有的，官方没有解决。
