### ISSUE TITLE
🐛 [BUG] v6，头像下拉菜单与多语言下来长度高度不一致

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#9974]
### 🐛 bug 描述

![微信截图_20220630194735](https://user-images.githubusercontent.com/3166799/176670097-68687769-a257-4bae-bbb3-f56e78a56981.png)
![微信截图_20220630194754](https://user-images.githubusercontent.com/3166799/176670104-c7edcf7a-7d21-4960-9d0d-684229bbb924.png)

**Comment by chenshuai2144** [comment]
项目不一样多，这不是很合理吗？

**Comment by hihuangwei** [comment]
![image](https://user-images.githubusercontent.com/3166799/176679609-e0bc15df-5d13-498c-a12f-5fbb22b1e887.png)
像素级的误差，一个下来菜单再灰色线条之上，另一个之下 @chenshuai2144

**Comment by chenshuai2144** [comment]
debug一下来个pr？ 不怎么容易看出来

**Comment by hihuangwei** [comment]
> debug一下来个pr？ 不怎么容易看出来

css 比较菜
