### ISSUE TITLE
🧐[问题] v5版本在已登录的状态下，再次进入登录页如何实现自动跳转首页

### ISSUE THREAD

**Issue by hpf0532** [ant-design/ant-design-pro#9975]
### 🧐 问题描述 | Problem description
在登录页判断状态跳转发现还是会回到登录页面，求解

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/f82338dc6236e8a16359537b5d1aa3a8f288857a/src/app.tsx#L60

这里
