### ISSUE TITLE
🐛 [BUG]pro create myapp命令在非空文件夹创建失败

### ISSUE THREAD

**Issue by s464446877** [ant-design/ant-design-pro#9976]
### 🐛 bug 描述

使用pro create myapp创建项目，在非空文件夹内创建失败，报错如图，在空文件夹内可以创建成功
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/52397868/176814953-ab013c1d-7499-4fe8-b3dc-0b29e4313443.png">

### © 版本信息

- Ant Design Pro 版本: [e.g. 6.0.0-beta]
- umi 4.0
- 浏览器环境
- 开发环境 [mac OS node: 16.15.1, npm: 8]

**Comment by chenshuai2144** [comment]
不能在非空创建的，要求要新建文件夹
