### ISSUE TITLE
DatePicker”不能用作 JSX 组件

### ISSUE THREAD

**Issue by lisai-666** [ant-design/ant-design-pro#9978]
![image](https://user-images.githubusercontent.com/64343424/176841825-e16b0f05-cad0-4190-8b1f-43fa4b725abd.png)
![image](https://user-images.githubusercontent.com/64343424/176841976-d0f41c31-a159-4acb-bd05-381f3a695953.png)
![image](https://user-images.githubusercontent.com/64343424/176841999-869f3d8e-a570-4756-bbdf-f2ba758d93af.png)
未得到有效的解决，开发人员让我升级antd版本，我升级到4.24.4，结果类型检测错误更多，我个人觉得这并不是ant版本的问题

**Comment by chenshuai2144** [comment]
这个就是没有支持 react17 类型导致的，你要把@types 和 antd 的版本都升级上来。

可以用git clean -dfx 清空掉所有的缓存的。
