### ISSUE TITLE
🐛 [BUG]umi4版本Access权限菜单导航没有及时渲染

### ISSUE THREAD

**Issue by zhangheng0317** [ant-design/ant-design-pro#9979]
### 🐛 bug 描述

从脚手架初始化一个umi4的项目就可以测试出来。admin和user两个用户
登录user用户。菜单有欢迎和查询表格。
退出user用户再登录admin用户，菜单依然是欢迎和查询表格，但是刷新后增加了管理页

### 📷 复现步骤 | Recurrence steps

![image](https://user-images.githubusercontent.com/76459860/176849505-ed780c98-9fba-42ff-9cb0-a2fa67952987.png)
![image](https://user-images.githubusercontent.com/76459860/176849637-1393be47-d07a-4568-b286-cb9b670291a5.png)
![image](https://user-images.githubusercontent.com/76459860/176849698-891b7b78-cee3-44cd-a4f3-e6ae214345d5.png)

### 🏞 期望结果 | Expected results

登录后及时改变

### 💻 复现代码 | Recurrence code

空的脚手架项目就能试出来，就不传沙盒了

### © 版本信息

- Ant Design Pro 版本: 6.0.0-beta.1
- umi 版本 ^4.0.0-rc.22
- 浏览器环境 Edge
- 开发环境 Windows

**Comment by ratelgogo** [comment]
@chenshuai2144 @zhangheng0317 已经解决了吗？我用官网的demo跑还是这样诶

**Comment by mashirozx** [comment]
@chenshuai2144  这边同样的问题～

"@ant-design/pro-components": "1.1.15",
"@umijs/route-utils": "2.2.0",
"antd": "4.22.4",
"@ant-design/pro-cli": "2.1.0",
"@umijs/max": "4.0.11",
"umi-presets-pro": "1.0.5",
"umi-serve": "1.9.11"

**Comment by mashirozx** [comment]
看了一下 @umijs/route-utils 是 2.2.0 的，似乎 https://github.com/umijs/route-utils/commit/89727e2046d62fac5ee9578280b5c5ce3e80c4c4 并没有能够修复
