### ISSUE TITLE
👑 [需求]ProTable 切换页码选中行也能保留其他页的选中行信息

### ISSUE THREAD

**Issue by zengxf98** [ant-design/ant-design-pro#9980]
### 🥰 需求描述 | Requirements description

在ProTabble 第一页选中几行后切换到其他页，再选中几行，能保留全部的选中行信息，而不是切换到其他页再选中行会把之前页的选中行清空

### 🧐 解决方案 | Solution

在切换页选中行时从Store中先把之前的选中行浅拷贝，然后再把切换页的选中行push到之前的选中行数组中，回到之前选中行中用rowKey去判断是否选中，rowkey可以用当前页数-1*当前页数据条数+ index

**Comment by chenshuai2144** [comment]
默认是不会这么做的，如果你想做到可以用 受控 api 来将数据缓存下来。

Q: 为什么 ProTable 不默认内置呢?

A: 因为 缓存就涉及到去重和缓存失效的问题，不同的项目有不同的选择，所以只保留了接口可以做，但是没有默认做

**Comment by xugege1** [comment]
大佬 最后怎么解决的啊 没看懂，能贴下代码吗

**Comment by xugege1** [comment]
我看ant的示例代码是默认支持多页码选中的，pro这里我看代码都和ant一样，没看懂是为啥不支持多页码选中，有大佬能解释一下吗
<img width="1219" alt="image" src="https://github.com/ant-design/ant-design-pro/assets/40876847/55a57b4f-a028-49f4-826e-b3a85a7d4600">

**Comment by xugege1** [comment]
我的数据之前用了分页接口，然后我现在改成接口一次性返回所有数据，现在支持多页码选中了
