### ISSUE TITLE
🧐请教一下，我把代码clone到本地，如何才能像在package里写"@ant-design/pro-table": "2.70.0"一样，通过npm拉下来相同的包

### ISSUE THREAD

**Issue by zhangdy2027** [ant-design/ant-design-pro#9982]
### 🧐 问题描述 | Problem description
我将代码clone到本地后，代码结构是ProComponents的结构，我把这些代码上传到我自己建的仓重，通过在package.json中写"@ant-design/pro-table": "我自己仓的地址"，然后执行npm install，在node_modules中发现，下载的依赖仍然是ProComponents的源码，而不是"@ant-design/pro-table": "2.70.0"这样，下载的是pro-xxx这样好几个包，请问这个是怎么做到的？

### 🚑 其他信息 | Other information
我的行为绝对没有任何商业性质哈

OS: windows

Node：14.15.1

浏览器 | browser：Chrome

**Comment by chenshuai2144** [comment]
去看看procomponents
这个库。这件事是npm干的
