### ISSUE TITLE
🐛 [BUG] ant-design/pro-cli 生成的项目yarn lint报错

### ISSUE THREAD

**Issue by ABeastofPrey** [ant-design/ant-design-pro#9983]
### 🐛 bug 描述
> ant-design-pro@5.2.0 lint:js /**/adp-demo
> eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src

  src/pages/account/settings/index.tsx:57:6
  ⚠  57:6  React Hook useLayoutEffect has a missing dependency: resize. Either include it or remove the dependency array. Mutable values like dom.current aren't valid dependencies because mutating them doesn't re-render the component.  react-hooks/exhaustive-deps

  src/pages/account/center/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/account/settings/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/form/advanced-form/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/form/basic-form/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/form/step-form/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/list/basic-list/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/list/card-list/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/list/search/applications/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/list/search/articles/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/list/table-list/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.                                                                                                                                                             import/no-extraneous-dependencies

  src/pages/user/register/_mock.ts:1:1
  ✖   1:1  Definition for rule import/no-extraneous-dependencies was not found.

### 📷 复现步骤 | Recurrence steps
1. npm i @ant-design/pro-cli -g
2. pro create myapp
3. yarn
4. yarn lint

### 🏞 期望结果 | Expected results
success!

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]  
package.json
"dependencies": {
    "@ant-design/charts": "^0.9.4",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-card": "^1.19.0",
    "@ant-design/pro-descriptions": "^1.10.0",
    "@ant-design/pro-form": "^1.64.0",
    "@ant-design/pro-layout": "^6.35.0",
    "@ant-design/pro-table": "^2.71.0",
    "@antv/data-set": "^0.11.0",
    "@antv/l7": "^2.3.7",
    "@antv/l7-maps": "^2.3.7",
    "@antv/l7-react": "^2.1.9",
    "@umijs/route-utils": "^2.0.0",
    "ahooks": "^2.0.0",
    "antd": "^4.19.0",
    "bizcharts": "^3.5.3-beta.0",
    "bizcharts-plugin-slider": "^2.1.1-beta.1",
    "classnames": "^2.3.0",
    "gg-editor": "^2.0.2",
    "lodash": "^4.17.0",
    "lodash-decorators": "^6.0.0",
    "moment": "^2.29.0",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.2.0",
    "react-router": "^4.3.1",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
  },
- umi 版本
"umi": "^3.5.0",
- 浏览器环境
- 开发环境 [e.g. mac OS]
mac OS
### 🚑 其他信息
pro -v
3.0.0

**Comment by chenshuai2144** [comment]
有几个规则被去掉了 删除一下 import开头的那些

**Comment by bigmgreen** [comment]
具体应该怎么操作？

**Comment by bigmgreen** [comment]
https://github.com/umijs/umi/issues/4518#issuecomment-627723109
