### ISSUE TITLE
🐛 [BUG] build后侧边routes列表UI无法正常展示

### ISSUE THREAD

**Issue by slatejack** [ant-design/ant-design-pro#9985]
### 🐛 [BUG] build后侧边routes列表UI无法正常展示

版本：ant-design-pro 5.0.0
bug描述：本地run dev后可以正常展示侧边栏及routes layout, 但build后发现侧边栏存在，但routes layout无法正常展示。

### 📷 复现步骤 | Recurrence steps
https://table.slatejack.cn/
扫码登录后进入页面可观察到侧边栏为空

### 🏞 期望结果 | Expected results

同本地测试运行结果一致，展示侧边栏及路由列表

### 💻 复现代码 | Recurrence code

https://table.slatejack.cn/

### © 版本信息

- Ant Design Pro 版本: 5.0.0
- umi 版本: 3.5.0
- 浏览器环境: chorme
- 开发环境 : mac os

**Comment by chenshuai2144** [comment]
代码？

**Comment by kaoding** [comment]
@umijs/route-utils 2.1.4 好像恢复了。

**Comment by chenshuai2144** [comment]
是 route-utils  的问题吗？ 你有重现吗

**Comment by kaoding** [comment]
> 是 route-utils 的问题吗？ 你有重现吗
> 
> 我是在内部发现了这个问题

这个问题我没有重现，2.1.4 解决了我的问题。

**Comment by chenshuai2144** [comment]
[slatejack](https://github.com/slatejack)   大佬你的示例还要登录，能给个最小重现吗

**Comment by slatejack** [comment]
> [slatejack](https://github.com/slatejack) 大佬你的示例还要登录，能给个最小重现吗

刚刚登录网站发现routes列表已可以正常展示了，目前网页已回复正常，后续还需要继续观察下这里

**Comment by slatejack** [comment]
> > 是 route-utils 的问题吗？ 你有重现吗
> > 我是在内部发现了这个问题
> 
> 这个问题我没有重现，2.1.4 解决了我的问题。

今天重新登录后发现问题已消失，目前可以正常展示路由列表了

**Comment by chenshuai2144** [comment]
那估计是一样的问题，麻烦了
