### ISSUE TITLE
🐛 [BUG] 基于文档创建的Umi4项目 antd 配置没有生效

### ISSUE THREAD

**Issue by iscmcloud** [ant-design/ant-design-pro#9987]
### 📷 复现步骤 | Recurrence steps
按照 [文档创建umi4版本项目](https://github.com/ant-design/ant-design-pro/issues/9958#issue-1285170228)，将config/config.ts 中antd配置更改：
`  antd: {
    // themes
    dark: true,
    compact: true,
  }`
紧凑模式和暗色主题没有生效

### 🏞 期望结果 | Expected results

紧凑模式和暗黑模式生效

### 💻 复现代码 | Recurrence code

按照文档操作，只更改上述两个配置

### © 版本信息

- Ant Design Pro 版本: [v6.0.0-beta.1]
- umi 版本 v4.0.5
- 浏览器环境 
- 开发环境 [Win 10]

**Comment by iscmcloud** [comment]
@chenshuai2144 大佬，大概什么时间点发V6的正式版？

**Comment by chenshuai2144** [comment]
要等 antd 更新到  5 了，有很多细节要做

**Comment by iscmcloud** [comment]
@chenshuai2144 大佬，V6 发布正式版本，有大概的时间点吗

**Comment by chenshuai2144** [comment]
发掉了
