### ISSUE TITLE
🐛 [BUG]ant design pro V5为什么在ie浏览器中打不开

### ISSUE THREAD

**Issue by littleGitYxr** [ant-design/ant-design-pro#9988]
🐛 [BUG]ant design pro V5为什么在ie浏览器中打不开

**Comment by littleGitYxr** [comment]
![image](https://user-images.githubusercontent.com/19453209/177153868-3194c032-a542-405a-b20c-af3bcaa8ddb6.png)
是不是根本 就不支持ie

**Comment by chenshuai2144** [comment]
是的。ie支持要自己调整。

**Comment by littleGitYxr** [comment]
> 是的。ie支持要自己调整。

怎么调整呢，求教~

**Comment by chenshuai2144** [comment]
https://v3.umijs.org/docs/faq#ie报错和压缩问题解决思路
