### ISSUE TITLE
🧐[问题]构建的预发项目 引用的aplus怎么去掉呢

### ISSUE THREAD

**Issue by Zoe-Lu** [ant-design/ant-design-pro#9990]
### 🧐 问题描述 | Problem description

怎么去掉预发环境引入的aplus？

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/77383426/177246090-e9dc67dd-ce6c-45e7-a296-76f30a0031eb.png)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
aplus 是一个采集埋点吧，

自己做个环境变量配置一下，不要手动注入了
