### ISSUE TITLE
🧐[问题 | question]配置通用布局文件layout获取的props中为空对象配置通用布局文件layout获取的props中为空对象

### ISSUE THREAD

**Issue by oneFox399** [ant-design/ant-design-pro#9991]
### 🧐 问题描述 | Problem description
根据使用说明文档在项目中手动创建通用布局文件Layout后，在layout组件中获取的props为空对象，无法获取到路由信息？请问应该如何配置？

### 🚑 其他信息 | Other information

![image](https://user-images.githubusercontent.com/108709872/177264562-19d85ffe-1bda-49ce-a3f0-6fb53c941fa5.png)
![image](https://user-images.githubusercontent.com/108709872/177264575-b3af5f6d-2715-4fe5-9bd5-072b4e31006b.png)
![image](https://user-images.githubusercontent.com/108709872/177264592-b8dbb7c7-c7a7-4797-af6d-6f5a5e07e5e0.png)
OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
https://umijs.org/docs/api/api#matchroutes

试试这个方法

**Comment by zozopen** [comment]
> https://umijs.org/docs/api/api#matchroutes
> 
> 试试这个方法

这个方法会导致渲染两次。。

**Comment by zozopen** [comment]
请问这个问题解决了吗，我今天也遇见这个问题了

**Comment by chenshuai2144** [comment]
> 这个方法会导致渲染两次。。

hooks 没办法的
