### ISSUE TITLE
🐛 [BUG]umi@4 layout在手机模式下无法展开菜单

### ISSUE THREAD

**Issue by reusu** [ant-design/ant-design-pro#9993]
好像菜单这个按钮就缩在了奇怪的地方
点击无效
使用 mix/side 都是这样子
用的umi-max示例
![QQ20220705-131015](https://user-images.githubusercontent.com/8424240/177273830-e2d5282c-8847-4ca4-9c37-1e9c7110840f.png)

另外pro-layout在使用默认logout的TableDropdown时
唤出会提示如下警告
Warning: [antd: Menu] children will be removed in next major version. Please use items instead.

**Comment by Lukiya** [comment]
同样问题

**Comment by Antoine-lb** [comment]
我可以确认。我试着用`pro create my-app`>`ui v4`（`v4.0.6`）重新安装，得到了同样的结果。
<img width="366" alt="Screen Shot 2022-07-11 at 9 20 52 AM" src="https://user-images.githubusercontent.com/27826950/178210420-660d7dd5-d98f-4328-987b-fe5f93d2d7aa.png">

即使我们能看到部分按钮，菜单也根本打不开，我真的试过了😂。

**Comment by yuenzp** [comment]
同样 能否快点给个解决方案。。。

**Comment by Xavier-LB** [comment]
这里有同样的问题

**Comment by owalid** [comment]
我也能够重新制作它

**Comment by chenshuai2144** [comment]
已经修复 更新下版本
