### ISSUE TITLE
真的不是我吐槽你们

### ISSUE THREAD

**Issue by 666-arch** [ant-design/ant-design-pro#9997]
你们的版本迭代的文档，对于第一次使用的人来说版本迭代文档啥的基本就不管了。代码写完就完事了。一些重要的细节啥也没说。

**Comment by drizzlesconsin** [comment]
文档基本在这几个地方可以看，想要详细的跟踪看 Commits

https://github.com/ant-design/ant-design-pro/releases

https://procomponents.ant.design/changelog

https://github.com/ant-design/pro-components/releases

**Comment by chenshuai2144** [comment]
欢迎来提pr，让文档变得更好

**Comment by 666-arch** [comment]
> 欢迎来提pr，让文档变得更好.
> 
> > 现在没有人专职维护，时间和精力都很不足

估计钞票给得还不是很到位

**Comment by chenshuai2144** [comment]
开源项目都是靠大公司包养的

**Comment by 569202812** [comment]
> > 欢迎来提pr，让文档变得更好.
> > > 现在没有人专职维护，时间和精力都很不足
> 
> 估计钞票给得还不是很到位

少点戾气，让社区更美好
