### ISSUE TITLE
默认安装都是typescript版本🧐[问题 | question]

### ISSUE THREAD

**Issue by buslightyear** [ant-design/ant-design-pro#9998]
### 🧐 问题描述 | Problem description
我想要安装一个js版本的antdpro，但是所有的命令方式安装的antdpro默认安装都是typescript版本。现在不让选择javascript版本？

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design-pro/issues/9958#issuecomment-1171848353

anyscript 就好了

**Comment by SullivanJia** [comment]
顶一下，找不到js的版本了

**Comment by chenshuai2144** [comment]
不支持非 typescript 了，typescript 已经是中后台事实上的解决方案了

**Comment by chb584890926** [comment]
> Reference in ne
还有方式可以下载js版本吗。大佬

**Comment by doYbest** [comment]
你找到什么方法可以下载js的版本了吗？
