### ISSUE TITLE
关于国际化泰语选择之后翻转页面

### ISSUE THREAD

**Issue by zhenghaotian09089** [ant-design/ant-design-pro#9999]
### Reproduction link

[https://joincoffeeverse.com/](https://joincoffeeverse.com/)

### Steps to reproduce

https://joincoffeeverse.com/

### What is expected?

不要翻转页面

### What is actually happening?

翻转页面

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17 |
| System | window |
| Browser | 谷歌最新 |

---
国际化切换到泰国语言的时候页面发生镜像

**Comment by chenshuai2144** [comment]
你想了解是  rtl 吗？

https://ant.design/components/config-provider-cn/#components-config-provider-demo-direction

泰语的阅读方向和中文也是不同的
